### ISSUE TITLE
C++ API for developers using CNTK C++ API for training

### ISSUE THREAD

**Issue by DPJep** [Microsoft/onnxruntime#100]
Right now it is TBD, but I really think that for production systems, it would be really beneficial to have a proper C++ inferface?

**Comment by snnn** [comment]
I'm trying to avoid having two C++ API in onnx runtime.
One is a thin wrapper around the c API. It's header only.
Another is the InferenceSession and its dependencies.

**Comment by pranavsharma** [comment]
Thanks for your feedback. We do have a [C++ interface](https://github.com/Microsoft/onnxruntime/blob/master/onnxruntime/core/session/inference_session.h), just that we've not packaged it yet since it's not an ABI.
