### ISSUE TITLE
Compilation ERROR  ‘nodiscard’

### ISSUE THREAD

**Issue by lizezheng** [microsoft/onnxruntime#10001]
onnxruntime/include/onnxruntime/core/common/status.h:115:21: error: ‘nodiscard’ attribute directive ignored [-Werror=attributes]

========
Env Info
1. onnxruntime commit  : 9345894c823de67f913d907da91dbc07ac322041
2. cmake version 3.20.4
3. gcc (GCC) 5.4.0

========
while the compilation runs ok with another env. 
Env info : 
1. cmake version 3.18.2
2. gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)

========
so is this gcc version issue?

**Comment by snnn** [comment]
I believe it requires gcc>=7.x. https://gcc.gnu.org/projects/cxx-status.html

**Comment by lizezheng** [comment]
Thanks for you reply, snnn.
