### ISSUE TITLE
Inference with iobinding is slower than without iobinding

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/onnxruntime#10000]
**Describe the bug**
I'm trying to improve my gpt2 model's performance on CPUs. I tried the official gpt2 notebook: https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/notebooks/Inference_GPT2-OneStepSearch_OnnxRuntime_CPU.ipynb

and I observed that with iobinding, the inference is slower than without iobinding:
![image](https://user-images.githubusercontent.com/8640918/145532913-cb3c2d99-dd08-457e-b5c2-fc9512aa96a4.png)

According the documentation [here](https://github.com/microsoft/onnxruntime/blob/master/docs/python/inference/api_summary.rst#iobinding), the performance can be improved by binding ort values directly. But in my test, it doesn't.

**Urgency**
high

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 12
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.8.1
- Python version: 3.9
- Visual Studio version (if applicable): 1.63.0

**Comment by hanbitmyths** [comment]
The purpose of IO Binding is to reduce memory copy between CPU and devices. Since your scenario runs over CPU only, there is no benefit of IO Binding and it has an extra cost. If you try to run a model on GPU, you'll see performance gain with IO Binding.

**Comment by HaoboGu** [comment]
Thanks!

**Comment by fxmarty** [comment]
@hanbitmyths Hi, is your answer still valid as of today?
