### ISSUE TITLE
Mask-RCNN succesfully runs inference on empty image but gives CUDNN error if next image is not empty

### ISSUE THREAD

**Issue by JeroenDelcour** [microsoft/onnxruntime#10020]
**Describe the bug**
I exported torchvision's mask-RCNN as an ONNX model and used `onnxruntime-gpu` to run inference with it. This works fine for a single image. Running a list of images, one at a time, through the same onnxruntime session works fine using the CPU execution provider. When using the CUDA execution provider, however, I get a CUDNN error if the first image has zero detections and the next image has at least some detections.

**Urgency**
I can work around this for now by re-instantiating the onnxruntime session as necessary, but it's not a preferred solution.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- ONNX Runtime installed from (source or binary): binary from PyPI
- ONNX Runtime version: onnxruntime-gpu 1.10.0
- Python version: 3.8
- CUDA/cuDNN version: CUDA version 11.4, cuDNN version 8.2.4.15-1 (installed using `apt install libcudnn8==8.2.4.15-1+cuda11.4`)
- GPU model and memory: Tried on NVIDIA GeForce 2070 Super 8GB and NVIDIA GeForce 950M 4GB

**To Reproduce**

Here's a minimum reproducible example:

```python
import torch
import torchvision
import numpy as np
import onnxruntime
from PIL import Image
import urllib

torch.manual_seed(0)

# download test image from COCO dataset
urllib.request.urlretrieve(
    "https://farm9.staticflickr.com/8289/7717265494_a6c6ac01bb_z.jpg",
    filename="test.jpg",
)

model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
model.eval()

dummy_input = torch.rand(1, 3, 800, 800)

torch.onnx.export(
    model,
    dummy_input,
    "maskrcnn.onnx",
    opset_version=14,
    input_names=["input"],
    output_names=["boxes", "labels", "scores", "masks"],
    dynamic_axes={
        "input": [0, 1, 2, 3],
        "boxes": [0, 1],
        "labels": [0],
        "scores": [0],
        "masks": [0, 1, 2, 3],
    },
)

# load model
with open("maskrcnn.onnx", "rb") as f:
    sess = onnxruntime.InferenceSession(f.read(), providers=["CUDAExecutionProvider"])
input_name = sess.get_inputs()[0].name

# run inference on empty image
image = np.zeros(shape=(1, 3, 800, 800), dtype=np.float32)
pred = sess.run(None, {input_name: image})
boxes, labels, scores, masks = pred
print("Number of detections: ", len(boxes))

# run inference on test image
image = Image.open("test.jpg")
image = np.float32(image)
image = np.moveaxis(image, -1, 0)  # HWC to CHW
image = image[np.newaxis, :]  # add batch dimension

pred = sess.run(None, {input_name: image})
boxes, labels, scores, masks = pred
print("Number of detections: ", len(boxes))

```

**Expected behavior**

Expected output:
```
Number of detections:  0
Number of detections:  3 (or some number greater than zero)
```

Instead I get this CUDNN error:
```
Number of detections:  0
2021-12-13 17:00:49.863435165 [E:onnxruntime:Default, cuda_call.cc:118 CudaCall] CUDNN failure 3: CUDNN_STATUS_BAD_PARAM ; GPU=0 ; hostname=jeroen-P6661-MD60117 ; expr=cudnnFindConvolutionForwardAlgorithmEx( s_.handle, s_.x_tensor, s_.x_data, s_.w_desc, s_.w_data, s_.conv_desc, s_.y_tensor, s_.y_data, 1, &algo_count, &perf, algo_search_workspace.get(), max_ws_size); 
2021-12-13 17:00:49.863676672 [E:onnxruntime:, sequential_executor.cc:346 Execute] Non-zero status code returned while running FusedConv node. Name:'Conv_2425_Relu_2426' Status Message: CUDNN error executing cudnnFindConvolutionForwardAlgorithmEx( s_.handle, s_.x_tensor, s_.x_data, s_.w_desc, s_.w_data, s_.conv_desc, s_.y_tensor, s_.y_data, 1, &algo_count, &perf, algo_search_workspace.get(), max_ws_size)
Traceback (most recent call last):
  File "main.py", line 54, in <module>
    pred = sess.run(None, {input_name: image})
  File "/home/jeroen/.virtualenvs/tmp/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running FusedConv node. Name:'Conv_2425_Relu_2426' Status Message: CUDNN error executing cudnnFindConvolutionForwardAlgorithmEx( s_.handle, s_.x_tensor, s_.x_data, s_.w_desc, s_.w_data, s_.conv_desc, s_.y_tensor, s_.y_data, 1, &algo_count, &perf, algo_search_workspace.get(), max_ws_size)k
```

**Additional context**

I've tried exporting using different opsets to no avail. The first image also doesn't necessarily need to be completely black - it seems any image that doesn't produce detections is sufficient. Faster-RCNN does not show this issue, suggesting it has something to do with the mask segmentation head.

I don't know if this is an onnxruntime issue or something to do with CUDA. I'm hoping someone here can at least point me in the right direction to investigate this further, since we use mask-RCNN quite a bit so this issue affects us quite broadly.

**Comment by RyanUnderhill** [comment]
Just to update, I was able to repro the error locally. Not sure what the solution is yet.

**Comment by RyanUnderhill** [comment]
Are you building from source or would you wait until the next release to get a fix for this issue?

**Comment by JeroenDelcour** [comment]
I'd probably wait for the next release, since the workaround is straightforward and this happens rarely enough that it doesn't really affect our inference time.
