### ISSUE TITLE
Fatal error: SentencepieceTokenizer is not a registered function/op

### ISSUE THREAD

**Issue by alexantoinefortin** [microsoft/onnxruntime#10029]
**Describe the bug**
Loading `ONNX` model results in `onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /app/models/guse-ml-small-v3.onnx failed:Fatal error: SentencepieceTokenizer is not a registered function/op` error.

**Urgency**
-

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- ONNX Runtime installed from (source or binary): `1.9.0` installed from `python -m pip install onnxruntime==1.9.0`
- ONNX Runtime version: `1.9.0` installed from `python -m pip install onnxruntime==1.9.0`
- Python version: `3.9.5`
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a (cpu)
- GPU model and memory: n/a (cpu)
- other dependencies: `tensorflow==2.7.0`, `tensorflow-text==2.7.0`, `tf2onnx==1.9.3`, `onnx==1.10.1`

**To Reproduce**
Step 1: Downloading the model from tfhub and decompress:
```
wget "https://tfhub.dev/google/universal-sentence-encoder-multilingual/3?tf-hub-format=compressed" -O guse-multilingual-small-v3.tar.gz

mkdir ./guse-multilingual-small-v3
tar -xvf guse-multilingual-small-v3.tar.gz --directory ./guse-multilingual-small-v3
```

Step 2: Export model to `.onnx`
```
python -m tf2onnx.convert --saved-model ./guse-multilingual-small-v3 --output /app/models/guse-ml-small-v3.onnx --opset 15 --extra_opset ai.onnx.contrib:1 --custom-ops SentencepieceTokenizer:ai.onnx.contrib
```

- Attach the ONNX model to the issue (where applicable) to expedite investigation.
The command above produces the `.onnx` model available [here](https://www.dropbox.com/s/yph6j4xzlvo9d93/guse-ml-small-v3.onnx?dl=1).

**Expected behavior**
I run the following script for loading the model
```
import onnxruntime as ort
import tensorflow_text

model_path = "/app/models/guse-ml-small-v3.onnx"
session = ort.InferenceSession(model_path)
```
I am getting the following stacktrace
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 324, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.9/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 358, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /app/models/guse-ml-small-v3.onnx failed:Fatal error: SentencepieceTokenizer is not a registered function/op
```

I expect the model to load smoothly since, when converting the model to `.onnx`, I used the `--extra_opset` and `--custom-ops` flags.

**Screenshots**
-

**Additional context**
-

**Comment by ytaous** [comment]
@wenbingl

**Comment by alexantoinefortin** [comment]
Thank you !!

**Comment by debjyoti003** [comment]
@wenbingl this won't work when we try to deploy the model on onnxruntime server, so we need a way which will some how incorporate this custom op in the model file, so that we don't have to register the custom op every time when we load the model. Do you know a way that could do this?

**Comment by wenbingl** [comment]
> @wenbingl this won't work when we try to deploy the model on onnxruntime server, so we need a way which will some how incorporate this custom op in the model file, so that we don't have to register the custom op every time when we load the model. Do you know a way that could do this?

Did you build onnxruntime engine by yourself? If so, you can just register the custom op library on sessionoptions creation.
