### ISSUE TITLE
ONNX runtime mysterious crash

### ISSUE THREAD

**Issue by niyazidageek** [microsoft/onnxruntime#10039]
**Problem**
My code is unable to create an inference session. The program doesn't even throw an exception. Process is being automatically killed and that is it. I don't know what to do.

**System information**
- OS MacOS  (Big Sur):
- ONNX Runtime installed from : Nuget.org
- ONNX Runtime version: 1.10
- Visual Studio 2019 (for Mac OS, version: 8.10.14)
- CPU: M1 Silicon, 8gb RAM

**ONNX Model**
- [yolov5n.onnx.zip](https://github.com/microsoft/onnxruntime/files/7714246/yolov5n.onnx.zip)

**Screenshots**
- As you can see, code doesn't throw any exceptions and process is being killed at that line.
<img width="842" alt="Screen Shot 2021-12-14 at 23 25 32" src="https://user-images.githubusercontent.com/82367001/146067063-99d1bfcf-f62f-4f18-a6d3-430e94c0a21c.png">

- Here is the window that i get after the process is killed
<img width="1440" alt="Screen Shot 2021-12-14 at 23 25 52" src="https://user-images.githubusercontent.com/82367001/146067237-dd0778ec-0c0f-4586-bd87-0ac0b45a3df9.png">

**Additional message**
I really don't know what to do. Please, help me. I haven't been able to handle this problem for more than 1 week. Additionally, the same piece of code works perfectly on Windows. Don't know what is wrong with **onnx** on Mac OS

**Comment by skottmckay** [comment]
Can you provide a complete working example to reproduce the issue? Hard to tell what other factors to consider when there's just the code that creates the session. Need to see how that is called, how the session is run, and what other dependencies the code has. 

Is the crash from attempting to load an MKL library? The error mentions dlopen and libmklml.dylib. Not sure where that dependency would come from as afaik the ORT package doesn't include or use that.

**Comment by niyazidageek** [comment]
I have solved the problem. The thing is that i had version **1.10.0** of the **onnxruntime** library. I have downloaded the previous version, namely **1.8.1** and it finally worked. Thank you!
