### ISSUE TITLE
how to build an unit8 model!

### ISSUE THREAD

**Issue by Chenhait** [microsoft/onnxruntime#10037]
hi, I convert a onnx model, and use triton server to infer.
however, the data and the model not in the same computer.
the input and output of ONNX model are fp32, it is too big to transmit.
so, I want to change the input and output to  int8.
is it possible?
thank you very much if any advance!!

**Comment by ytaous** [comment]
No we don't. But perhaps you can try a couple things:
1. we have fp32 -> fp16 converter util : https://github.com/microsoft/onnxruntime/blob/5e197698b8964875bb9b979070c325b51bb0228a/onnxruntime/python/tools/transformers/onnx_model.py#L500
2. perhaps you can zip the data before transmission?

**Comment by yufenglee** [comment]
@Chenhait, you can try '[QuantizeLinear](https://github.com/onnx/onnx/blob/master/docs/Operators.md#QuantizeLinear)' the input and output before transferring, then [DequantizeLinear](https://github.com/onnx/onnx/blob/master/docs/Operators.md#dequantizelinear) it back after transferring, but it may introduce accuracy loss though.

I think @ytaous 2 tip is better.

**Comment by Chenhait** [comment]
> No we don't. But perhaps you can try a couple things:
> 
> 1. we have fp32 -> fp16 converter util : https://github.com/microsoft/onnxruntime/blob/5e197698b8964875bb9b979070c325b51bb0228a/onnxruntime/python/tools/transformers/onnx_model.py#L500
> 2. perhaps you can zip the data before transmission?

OK, thank you so much for your advance!!!
