### ISSUE TITLE
How to config the developing ide?

### ISSUE THREAD

**Issue by ZinuoCai** [microsoft/onnxruntime#10043]
I am new to onnxruntime, and I wonder how to config the ide to code. Both vscode and clion are all right.

**Comment by pranavsharma** [comment]
This has nothing to do with the ORT product. Please see https://code.visualstudio.com/docs/languages/cpp.

**Comment by ZinuoCai** [comment]
I gave to say that directly closing the issue shows the community is very, very unfriendly to freshmen.
