### ISSUE TITLE
Running inference on a batch of tensors using the C API

### ISSUE THREAD

**Issue by xgirones** [microsoft/onnxruntime#1004]
Hi, I am new to onnxruntime and I have some doubts:

1-For the sake of performance I would like to run inference on a batch of input tensors, but I do not know how to specify it using the C API. Are there any samples and/or instructions I can use?

2-How can I load a model from a memory buffer using the C API?

3-Is it possible to build the onnxruntime DLL to incorporate both the MKLDNN/MKLML and CUDA providers and selecting one of the two as a session option? 

* I am using ONNX Runtime version v0.4.0 on Windows

**Comment by snnn** [comment]
1. At API level, it doesn't have the 'batch' concept.  You may combine multiple tensors into one single tensor.  Tensor is a n-dim array, you may use the first dimension as batch size. Again, at API level, onnxruntime doesn't understand what is batch and which dimension is 'batch'. It should be defined in the model.

2. Working on that.

3. Yes.

**Comment by xgirones** [comment]
Thanks for your answer. 

I have models trained with CNTK 2.7 and I am using CNTK for inference too. I am familiar with the CNTK API, which has functionality to create batches of inputs and I find it very convenient. The CNTK model (converted to ONNX) I would like to fed batched inputs is:
 
![ocr_basic_model_3rps_cntk27_eval_2017](https://user-images.githubusercontent.com/30896820/57511114-c0050d80-7308-11e9-800f-b77e50fb9f6f.png)

I have tried to follow your advice and use the first dimension of the input as the batch size. However, when I attempt to run the model with a tensor with shape

           [#batch_elements] x 3 x 24 x 16

I get the error

> 2019-05-10 09:02:01.9356049 [E:onnxruntime:, sequential_executor.cc:125 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Node: Times605 Status Message: Not satsified: K_ == right_shape[right_num_dims - 2]
> 
> matmul_helper.h:38 onnxruntime::MatMulComputeHelper::ComputeMatMul dimension mis
> match

How should I arrange the input tensor to avoid this error?

Thanks!

**Comment by snnn** [comment]
@KeDengMS Any idea? Looks like the CNTK exporter doesn't support batch very well.

**Comment by KeDengMS** [comment]
@liqunfu and @BowenBao for awareness of CNTK issues.

This is known issue. To support batch, the exported model needs to be modified to have batch axis > 1. Here's an script I used for generate Scan test from CNTK and add batch axis to it. You may modified it to suite your needs:

```
import cntk as C
import numpy as np
import onnx
import os
from onnx import numpy_helper

model_file = 'model.onnx'
data_dir = 'test_data_set_0'

def SaveTensorProto(file_path, variable, data, name):
    # ONNX input shape always has sequence axis as the first dimension, if sequence axis exists
    if len(variable.dynamic_axes) == 2:
        data = data.transpose((1,0,)+tuple(range(2,len(data.shape))))
    tp = numpy_helper.from_array(data, name if name else variable.uid)
    with open(file_path, 'wb') as f:
        f.write(tp.SerializeToString())

def SaveData(test_data_dir, prefix, variables, data_list, name_replacements=None):
    if isinstance(data_list, np.ndarray):
        data_list = [data_list]
    for (i, d), v in zip(enumerate(data_list), variables):
        SaveTensorProto(os.path.join(test_data_dir, '{0}_{1}.pb'.format(prefix, i)), v, d, name_replacements[v.uid] if name_replacements else None)

def Save(dir, func, feed, outputs):
    if not os.path.exists(dir):
        os.makedirs(dir)
    onnx_file = os.path.join(dir,model_file)
    func.save(onnx_file, C.ModelFormat.ONNX)

    # onnx model may have different name for RNN initial states as inputs
    cntk_to_actual_names = {}
    with open(onnx_file, 'rb') as ff:
        sf = ff.read()
    model = onnx.ModelProto()
    model.ParseFromString(sf)
    for actual_input in model.graph.input:
        actual_input_name = actual_input.name
        for cntk_input in func.arguments:
            cntk_name = cntk_input.uid
            if actual_input_name.startswith(cntk_name):
                cntk_to_actual_names[cntk_name] = actual_input_name

    if type(feed) is not dict:
       feed = {func.arguments[0]:feed}

    if type(outputs) is not dict:
       outputs = {func.outputs[0]:outputs}

    test_data_dir = os.path.join(dir, data_dir)
    if not os.path.exists(test_data_dir):
        os.makedirs(test_data_dir)

    SaveData(test_data_dir, 'input', func.arguments, [feed[var] for var in func.arguments], cntk_to_actual_names)
    SaveData(test_data_dir, 'output', func.outputs, [outputs[var] for var in func.outputs])

def LSTM(cell_dim, use_scan=True):
    # we now create an LSTM_cell function and call it with the input and placeholders
    LSTM_cell = C.layers.LSTM(cell_dim)

    @C.Function
    def func(dh, dc, input):
        LSTM_func = LSTM_cell(dh, dc, input)
        if use_scan:
            LSTM_func_root = C.as_composite(LSTM_func.outputs[0].owner.block_root)
            args = LSTM_func_root.arguments
            LSTM_func = LSTM_func_root.clone(C.CloneMethod.share, {args[0]:input, args[1]:dh, args[2]:dc})
        return LSTM_func

    return func

def GenScan():
    np.random.seed(0)
    feature = C.sequence.input_variable((3,), np.float32)
    model = C.layers.For(range(4), lambda : C.layers.Recurrence(LSTM(2, use_scan=True)))(feature)

    data_feature = np.random.rand(2,5,3).astype(np.float32)
    data_output = np.asarray(model.eval(data_feature))

    Save('test_Scan', model, data_feature, data_output)
    
    # Currently CNTK only outputs batch == 1, do some editing
    in_mp = onnx.ModelProto()
    with open('test_Scan/model.onnx', 'rb') as ff:
        in_mp.ParseFromString(ff.read())

    out_mp = onnx.ModelProto()
    out_mp.CopyFrom(in_mp)
    out_mp.graph.ClearField('initializer')

    # change LSTM init_c/h into inputs to support truncated sequence
    # as batch dimension is unknown on those data when building model
    # note here we assume init_c/h starts from 0
    # if not the case, user need to manually broadcast it for feed
    num_inputs = 1
    for i in in_mp.graph.initializer:
        if i.name.startswith("Constant"):
            shape = i.dims
            shape[0] = 2
            aa = np.zeros(shape, dtype=np.float32)
            tp = numpy_helper.from_array(aa, i.name)
            with open('test_Scan/test_data_set_0/input_' + str(num_inputs) + '.pb', 'wb') as ff:
                ff.write(tp.SerializeToString())
            num_inputs = num_inputs + 1
        else:
            out_mp.graph.initializer.add().CopyFrom(i)

    for vi in list(out_mp.graph.input) + list(out_mp.graph.output) + list(out_mp.graph.value_info):
        dim = vi.type.tensor_type.shape.dim
        dim[len(dim) - 2].dim_param = 'batch'
        
    for n in out_mp.graph.node:
        if n.op_type == 'Scan':
            body = [attr for attr in n.attribute if attr.name == 'body'][0]
            for vi in list(body.g.input) + list(body.g.output) + list(body.g.value_info):
                dim = vi.type.tensor_type.shape.dim
                dim[0].dim_param = 'batch'

    with open('test_Scan/model.onnx', 'wb') as ff:
        ff.write(out_mp.SerializeToString())

if __name__=='__main__':
    GenScan()
```

**Comment by xgirones** [comment]
Thanks for your response. When I tried

`in_mp = onnx.read(pathMyEvalModeONNX, 'rb')`

I got the error

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-2d8db548dda2> in <module>
----> 1 in_mp = onnx.read(pathMyEvalModeONNX, 'rb')

AttributeError: module 'onnx' has no attribute 'read'
```

On the other hand, I was able to load the model using

`in_mp = onnx.load(pathMyEvalModeONNX)`

Then, I was able to run this part of your code

```
    out_mp = onnx.ModelProto()
    out_mp.CopyFrom(in_mp)
    out_mp.graph.ClearField('initializer')

    # change LSTM init_c/h into inputs to support truncated sequence
    # as batch dimension is unknown on those data when building model
    # note here we assume init_c/h starts from 0
    # if not the case, user need to manually broadcast it for feed
    num_inputs = 1
    for i in in_mp.graph.initializer:
        if i.name.startswith("Constant"):
            shape = i.dims
            shape[0] = 2
            aa = np.zeros(shape, dtype=np.float32)
            tp = numpy_helper.from_array(aa, i.name)
            with open('test_Scan/test_data_set_0/input_' + str(num_inputs) + '.pb', 'wb') as ff:
                ff.write(tp.SerializeToString())
            num_inputs = num_inputs + 1
        else:
            out_mp.graph.initializer.add().CopyFrom(i)

    for vi in list(out_mp.graph.input) + list(out_mp.graph.output) + list(out_mp.graph.value_info):
        dim = vi.type.tensor_type.shape.dim
        dim[len(dim) - 2].dim_param = 'batch'
        
    for n in out_mp.graph.node:
        if n.op_type == 'Scan':
            body = [attr for attr in n.attribute if attr.name == 'body'][0]
            for vi in list(body.g.input) + list(body.g.output) + list(body.g.value_info):
                dim = vi.type.tensor_type.shape.dim
                dim[0].dim_param = 'batch'
```

However, when I tried to save the model with

`onnx.save(out_mp, 'pathMyEvalModeONNX_fixed', 'wb')`

I got the error
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-25-a59b10f11a54> in <module>
----> 1 onnx.save(out_mp,pathMyEvalModeONNX_fixed,'wb')

AttributeError: module 'onnx' has no attribute 'save'
```

I have a Conda environment with CNTK 2.7 and the ONNX Runtime. I installed the ONNX Runtime using

`pip install onnxruntime `

But it seems that the 'save' function is missing in the onnx module as

`dir(onnx)`

returns 

```
['AttributeProto',
 'DESCRIPTOR',
 'GraphProto',
 'IR_VERSION',
 'IR_VERSION_2017_10_10',
 'IR_VERSION_2017_10_30',
 'ModelProto',
 'NodeProto',
 'OperatorSetIdProto',
 'StringStringEntryProto',
 'TensorProto',
 'TensorShapeProto',
 'TypeProto',
 'ValueInfoProto',
 'Version',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'absolute_import',
 'checker',
 'defs',
 'descriptor_pb2',
 'division',
 'enum_type_wrapper',
 'google',
 'helper',
 'load',
 'load_from_string',
 'mapping',
 'numpy_helper',
 'onnx',
 'onnx_cpp2py_export',
 'onnx_pb',
 'onnx_pb2',
 'print_function',
 'sys',
 'unicode_literals',
 'version']
```

Could you please tell me I am doing wrong? I develop mostly in C++ and my Python skills are very limited.

Thanks!

**Comment by tmccrmck** [comment]
Not a response to your previous question, but I think it should be mentioned that loading from an in-memory buffer just got merged with #718

**Comment by xgirones** [comment]
> Not a response to your previous question, but I think it should be mentioned that loading from an in-memory buffer just got merged with #718

This is great! Now if I manage to get the batch axis issue solved I will have everything I need to migrate to ONNX Runtime. Thanks!

**Comment by xgirones** [comment]
More problems, this time when trying to convert a very simple CNTK RNN model to ONNX:

```
def BiRecurrence(fwd, bwd):
    F = C.layers.Recurrence(fwd)
    G = C.layers.Recurrence(bwd, go_backwards=True)
    x = C.placeholder()
    apply_x = C.splice(F(x), G(x))
    return apply_x

def vanilla_model():
    co = 24
    num_classes = 39
    rnn_dim = 128
    dense_dim = 96
    
    x = C.input_variable(**C.layers.Sequence[C.layers.Tensor[co]])
    y = C.sequence.input_variable( shape=num_classes , name="output_1" )
        
    h=C.layers.SequentialConvolution(filter_shape=(3,3), num_filters=8, strides=(1,1), pad=True, activation = C.leaky_relu, reduction_rank=0)( x )
    h=C.reshape(h,-1)
    h = BiRecurrence(C.layers.RNNStep(rnn_dim//2, activation=C.leaky_relu),C.layers.RNNStep(rnn_dim//2,activation=C.leaky_relu))( h )
    h = C.layers.Dense(dense_dim, activation = C.leaky_relu)( h )
    h = C.layers.Dense(num_classes, activation = None)( h )

    return h
```

![ocr_basic_line_model_cntk27_2017](https://user-images.githubusercontent.com/30896820/57652913-f2489080-75d0-11e9-8598-1e3117c00ab5.png)

In can be trained with CNTK and it works. However, when I try to save it as ONNX using

`vanilla_model().save(pathRNNModelONNX,C.ModelFormat.ONNX)`

CNTK issues an error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-26-00943619e4be> in <module>
----> 1 vanilla_model().save(pathRNNModelONNX,C.ModelFormat.ONNX)

C:\ProgramData\Anaconda3\envs\cntk-2.7-gpu-py36\lib\site-packages\cntk\internal\swig_helper.py in wrapper(*args, **kwds)
     67     @wraps(f)
     68     def wrapper(*args, **kwds):
---> 69         result = f(*args, **kwds)
     70         map_if_possible(result)
     71         return result

C:\ProgramData\Anaconda3\envs\cntk-2.7-gpu-py36\lib\site-packages\cntk\ops\functions.py in save(self, filename, format, use_external_files_to_store_parameters)
   1557              to external files. This is for models larger than 2GB. Defaults to False.
   1558         '''
-> 1559         return super(Function, self).save(filename, format.value, use_external_files_to_store_parameters)
   1560 
   1561     @typemap

C:\ProgramData\Anaconda3\envs\cntk-2.7-gpu-py36\lib\site-packages\cntk\cntk_py.py in save(self, *args)
   2080 
   2081     def save(self, *args):
-> 2082         return _cntk_py.Function_save(self, *args)
   2083 
   2084     def restore(self, filepath):

RuntimeError: A RNN block does not have expected input count (5). Actual input count is 7

[CALL STACK]
    > std::enable_shared_from_this<Microsoft::MSR::CNTK::MatrixBase>::  weak_from_this
    - CNTK::  XavierInitializer (x15)
```

**Comment by bencherian** [comment]
@snnn In your earlier reply, you say the following:

> 1. At API level, it doesn't have the 'batch' concept.  You may combine multiple tensors into one single tensor.  Tensor is a n-dim array, you may use the first dimension as batch size. Again, at API level, onnxruntime doesn't understand what is batch and which dimension is 'batch'. It should be defined in the model.

Does this imply that you cannot run batched inference with varying batch sizes? (e.g., run inference with a batch of 128, and then on a batch of 140?)

**Comment by snnn** [comment]
No, you can

**Comment by snnn** [comment]
Close this issue as the original problem is solved. 
I'll add a sample program for demonstrating inferencing with batching.

**Comment by snnn** [comment]
#853

**Comment by chenglinzhang** [comment]
> Close this issue as the original problem is solved.
> I'll add a sample program for demonstrating inferencing with batching.

Hi @snnn , I am also looking for a batch inference C/C++ example. Can you provide an URL to your solution? Thanks.

**Comment by snnn** [comment]
https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx/imagenet

**Comment by chenglinzhang** [comment]
Thanks @snnn for the quick response. I am looking for multiple inputs in ONE run. The ```session_.Run``` in the example imagenet ```main.cc``` takes 1 input? 
```
main.cc:      session_.Run(Ort::RunOptions{nullptr}, &input_name_, &input_tensor, 1, &output_name_, &output_tensor, 1);
```

**Comment by snnn** [comment]
```
&input_tensor, 1,
```
Please create a C array of tensors, replace the above things as array name and array length.

**Comment by chenglinzhang** [comment]
I have ```input_tensors``` of size 2 populated with two sets of OrtValues, and ```output_tensors``` of size 2 initialized with nullptr. Executing ```session_.Run(...,2,...,2,...)``` does fill the results to ```output_tensors```. ```output_tensors[0]``` is correct. However, ```output_tensor[1]``` ALWAYS gives the same results as ```output_tensor[0]```, though their corresponding OrtValues in the ```input_tensors``` are different. I am using onnxruntime 0.5.0.

**Comment by snnn** [comment]
Sounds like a bug?

**Comment by chenglinzhang** [comment]
Thanks @snnn. To illustrate the problem, I modified the C API sample at
https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp

The modified file is at 
https://github.com/chenglinzhang/c_onnxruntime/blob/master/C_Api_Sample.cpp

New codes are marked with, e.g., ```//++++ 4.START NEW CODE: ... //++++ 4. END NEW CODE``` .

For two different input tensors in an array, I got the same results in the two output tensors:
```
  // PROBLEM FOUND:
  // output_tensors[0] and output_tensors[1] printed the same results
  // output_tensors[0] looks overwrittern by output_tensors[1]
  // the floatarr3 and floatarr4 happended to share the same pointer address 0x7f71eed76040,
  // though they are from separate GetTensorMutableData() calls
  // where could it be wrong in the new codes?
  ```
