### ISSUE TITLE
Unexpected numerical differences between batch and single row predictions

### ISSUE THREAD

**Issue by cbourjau** [microsoft/onnxruntime#10058]
**Describe the bug**
`onnxruntime` version `1.10.0` (Python bindings) produces slightly different results in batch mode with four or more rows than when performing single-row predictions for float32 input of the `Log` node. ~Other node types such as `Exp` do not exhibit this behavior.~ Turns out at least `Exp` is also affected. I updated the test case below. 

**Urgency**
Our production use case requires reproducible predictions regardless if they were submitted as a single row (or batch of less then 4 rows) or within a larger batch. We are currently forced to fall back to single-row predictions which naturally causes a large performance hit.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Linux  5.4.0-1060-aws #63~18.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux`
- ONNX Runtime installed from (source or binary): binary from [conda-forge](https://github.com/conda-forge/onnxruntime-feedstock)
- ONNX Runtime version: `1.10.0`
- Python version: `3.9.7`
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**To Reproduce**
The following test case reproduces the issue reliably in the above described environment:
```python
from onnx import helper, checker, TensorProto, version
import onnxruntime as rt
import numpy as np


def test_minimal_log():
    assert rt.__version__ == "1.10.0"
    assert version.version == "1.10.2"  # ONNX version
    node = helper.make_node("Log", inputs=["input"], outputs=["output"])
    inputs = [helper.make_tensor_value_info("input", TensorProto.FLOAT, [None])]
    outputs = [helper.make_tensor_value_info("output", TensorProto.FLOAT, [None])]
    g = helper.make_graph([node], "log_batch_issue", inputs, outputs)
    model = helper.make_model(g)
    checker.check_model(model, full_check=True)
    sess = rt.InferenceSession(model.SerializeToString())
    # Issue only occurs for certain values. For example, `42.42` works
    # as expected.
    input_vals = np.array([1.06023156] * 4, dtype="float32")
    first_row_batch = sess.run(["output"], {"input": input_vals})[0][0]
    first_row_single = sess.run(["output"], {"input": input_vals[:1]})[0][0]
    assert first_row_batch == first_row_single
    
def test_minimal_exp():
    assert rt.__version__ == "1.10.0"
    assert version.version == "1.10.2"
    node = helper.make_node("Exp", inputs=["input"], outputs=["output"])
    inputs = [helper.make_tensor_value_info("input", TensorProto.DOUBLE, [None])]
    outputs = [helper.make_tensor_value_info("output", TensorProto.DOUBLE, [None])]
    g = helper.make_graph([node], "log_batch_issue", inputs, outputs)
    model = helper.make_model(g)
    checker.check_model(model, full_check=True)
    sess = rt.InferenceSession(model.SerializeToString())
    # Issue only occurs for certain values. For example, `42.42` works
    # as expected.
    input_vals = np.array([-0.26606467366] * 4, dtype="float64")  # For Exp
    first_row_batch = sess.run(["output"], {"input": input_vals})[0][0]
    first_row_single = sess.run(["output"], {"input": input_vals[:1]})[0][0]
    assert first_row_batch == first_row_single
```

**Expected behavior**
I expect the results of each row to be independent of the batch size in which they were submitted.

**Comment by ytaous** [comment]
Hi, have u installed onnxruntime-gpu? If not, please also install onnxruntime-gpu and try again. ref- https://onnxruntime.ai/docs/install/#install-onnx-runtime-ort-1

I found it's repro-able if I don't install it. BTY minor change on your code:

    sess = rt.InferenceSession(model.SerializeToString(), providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])

**Comment by cbourjau** [comment]
@ytaous No, I have not installed `onnxruntime-gpu` nor do I have a compatible GPU for testing. Or are you saying that the `CPUExecutionProvider` does not exhibit this issue if `onnxruntime-gpu` is installed?

**Comment by jtilly** [comment]
These slight discrepancies appear to be caused by eigen. We opened an upstream issue at https://gitlab.com/libeigen/eigen/-/issues/2413.

**Comment by cbourjau** [comment]
This issue has been extensively explored on the Eigen issue tracker as mentioned earlier: https://gitlab.com/libeigen/eigen/-/issues/2413

The gist of the discussion is that depending on the memory alignment Eigen chooses different code paths for different "rows" of the input. One can think of the situation as having two competing use-cases: One of uncompromising optimal performance (Eigen default) and one of "reproducibility" (i.e. a prediction can always be reproduced without knowledge of the previous input's batch size). The latter is our use case. We have to guarantee such reproducibility for several reasons including regulatory ones.

There are a couple of compile time flags (`EIGEN_FAST_MATH` and `EIGEN_DONT_VECTORIZE`) that Eigen offers to mitigate the issue, but I have not yet found the time to try them out with `onnxruntime`.

It would be great to know if `onnxruntime` is interested in officially supporting the "reproducible" use-case by providing its own (optional) compile time flags?

**Comment by snnn** [comment]
> These slight discrepancies appear to be caused by eigen. We opened an upstream issue at https://gitlab.com/libeigen/eigen/-/issues/2413.

Eigen is only used in some of the kernels, and the root cause of this issue is quite general. So even the flag is added, it will only address the concern for some kernels. It may confuse users in a sense that sometimes it works sometimes it doesn't. 

>  if onnxruntime is interested in officially supporting the "reproducible" 

No. We don't have such a plan for the CPU EP. If any other EP, for example CUDA, has the functionality in its underlying engine, then we will leverage it. Otherwise we wouldn't spend time on it.
