### ISSUE TITLE
[ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node ArgMax_1094:ArgMax(11)

### ISSUE THREAD

**Issue by cendelian** [microsoft/onnxruntime#10068]
hi i run
`onnx_session1 = onnxruntime.InferenceSession("./pretrained/textmodel.onnx")`
and generate error as below:

**File "D:\anaconda3\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 312, in _create_inference_session
    sess.initialize_session(providers, provider_options)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node ArgMax_1094:ArgMax(11)**

ONNX - 1.7.0
onnxruntime - 1.7.0

could you help me to solve this problem?

and the onnx model i transfered here

![企业微信截图_16397227177148](https://user-images.githubusercontent.com/50360389/146499754-a24ac96f-cd16-41ce-9006-5cf1030adc37.png)

**Comment by ytaous** [comment]
Hi, can u pls check what's the type you are using for ArgMax. It's like it's not supported for opset 11.
ref - https://github.com/microsoft/onnxruntime/issues/9760

search for ArgMax for either CPU/CUDA provider:
ref - https://github.com/microsoft/onnxruntime/blob/master/docs/OperatorKernels.md 

If CUDA, there's an PR in progress - https://github.com/microsoft/onnxruntime/pull/9700

**Comment by cendelian** [comment]
> Hi, can u pls check what's the type you are using for ArgMax. Likely it's not supported for opset 11. ref - #9760
> 
> search for ArgMax for either CPU/CUDA provider: ref - https://github.com/microsoft/onnxruntime/blob/master/docs/OperatorKernels.md
> 
> If CUDA, there's an PR in progress - #9700

the type using for ArgMax is int64.  and only can be int64,   could yuo give me some advices?
which opset can support int64 for ArgMax?

**Comment by cendelian** [comment]
I solve it ,   only change ArgMax's input to int32, everything else stays the same, and it ok!!
