### ISSUE TITLE
TreeEnsembleClassifier: base_value not tested, fails for binary classification

### ISSUE THREAD

**Issue by xadupre** [microsoft/onnxruntime#1007]
**Describe the bug**
If base_value is specified and the number of classes is 2, the score of the second class is constant.

**System information**
- OS Platform and Distribution: Windows
- ONNX Runtime installed from source
- ONNX Runtime version: 0.4
- Python version: 3.7
- Visual Studio version 2017

**Comment by snnn** [comment]
Reopen it because the fix got reverted

**Comment by xadupre** [comment]
Fixed on the converter side: https://github.com/onnx/sklearn-onnx/pull/255
