### ISSUE TITLE
How to use ep TensorrtExecutionProvider_fp16

### ISSUE THREAD

**Issue by QuantumLiu** [microsoft/onnxruntime#10070]
**Is your feature request related to a problem? Please describe.**
I' m using `TensorrtExecutionProvider `which build by command:
`./build.sh --cudnn_home "/usr/local/cuda" --cuda_home "/usr/local/cuda" --use_tensorrt --tensorrt_home "/home/tianqing/Downloads/TensorRT-7.2.3.4" --skip_submodule_sync --build_wheel --parallel --skip_tests --use_openvino --config Release`
It use `TensorrtExecutionProvider ` perfectly, but I can't using TensorrtExecutionProvider_fp16.  
I tried to build and run with 
`export ORT_TENSORRT_FP16_ENABLE=1
`
https://github.com/microsoft/onnxruntime/issues/2967

**System information**
- ONNX Runtime version (you are using):
```
# packages in environment at /home/tianqing/anaconda3/envs/infer:
#
# Name                    Version                   Build  Channel
onnx                      1.10.1                   pypi_0    pypi
onnx-simplifier           0.3.6                    pypi_0    pypi
onnx2keras                0.0.24                   pypi_0    pypi
onnxconverter-common      1.8.1                    pypi_0    pypi
onnxmltools               1.10.0                   pypi_0    pypi
onnxoptimizer             0.2.6                    pypi_0    pypi
onnxruntime-gpu-tensorrt  1.8.1                    pypi_0    pypi
skl2onnx                  1.10.0                   pypi_0    pypi
```
**Describe the solution you'd like**
An option to build TensorrtExecutionProvider_fp16 ep.

**Describe alternatives you've considered**

**Additional context**
`session.get_providers()
`
got:
`['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'OpenVINOExecutionProvider', 'CPUExecutionProvider']`

**Comment by stevenlix** [comment]
To enable FP16 in ORT-TRT, just set ORT_TENSORRT_FP16_ENABLE to 1. You can also use provider options in C/python API. Details can be found here,
https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#execution-provider-options
Can you provide more details of why you think FP16 is not enabled? Do you see errors or perf is not getting better?

**Comment by QuantumLiu** [comment]
> To enable FP16 in ORT-TRT, just set ORT_TENSORRT_FP16_ENABLE to 1. You can also use provider options in C/python API. Details can be found here, https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#execution-provider-options Can you provide more details of why you think FP16 is not enabled? Do you see errors or perf is not getting better?

Solved, thank you very much.
