### ISSUE TITLE
[fp16] InstanceNorm generate totally wrong result on fp16

### ISSUE THREAD

**Issue by yetingqiaqia** [microsoft/onnxruntime#10079]
**Describe the bug**
Hi, I found InstanceNorm generates totally wrong result on fp16, while both fp32 model and partial fp16 model (i.e., InstanceNorm is fp32) generate correct result. See below: 

  | Fp32 model | Partial fp16 model | Full fp16 model
-- | -- | -- | --
Result | [[ 6.0549564 -3.183563  -2.8680713]    [   6.1917925 -3.354034  -2.8344436]    [   6.169338  -3.3007898 -2.8652153]    [   6.1567574 -3.3921351 -2.7612722]    [   6.079842  -3.1844094 -2.8921494]    [   6.04279   -3.3625133 -2.6769447]] | [[ 6.0546875 -3.1835938 -2.8671875]    [   6.1914062 -3.3535156 -2.8339844]    [   6.1679688 -3.3007812 -2.8632812]    [   6.15625   -3.390625  -2.7617188]    [   6.078125  -3.1835938 -2.890625 ]    [   6.0429688 -3.3613281 -2.6757812]] | **[[   3.953125  -1.5253906 -2.4238281]    [ 3.953125    -1.5253906 -2.4238281]    [ 3.953125    -1.5253906 -2.4238281]    [ 3.953125    -1.5253906 -2.4238281]    [ 3.953125    -1.5253906 -2.4238281]    [ 3.953125    -1.5253906 -2.4238281]]**

Could you help check if there anything wrong for InstanceNorm on fp16? 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.10
- Python version: 3.6
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: CUDA 11.5, CuDNN 8.3.1
- GPU model and memory: V100, 16GB

**To Reproduce**
- Test code: 
```python
import numpy as np
import onnxruntime as ort

sess_options = ort.SessionOptions()
sess_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
sess_options.enable_mem_pattern=False

#Full fp16 model
sess = ort.InferenceSession("graph_opset12_optimized_fp16_keep_io_True_unblockInstanceNormalization.onnx", sess_options, providers=["CUDAExecutionProvider"])

#Partial fp16 model (every other ops are fp16 except InstanceNormalization)
#sess = ort.InferenceSession("graph_opset12_optimized_fp16_keep_io_True.onnx", sess_options, providers=["CUDAExecutionProvider"])

#Full fp32 model
#sess = ort.InferenceSession("graph_opset12_optimized.onnx", sess_options, providers=["CUDAExecutionProvider"])

input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name

#warm-up run
np.random.seed(123)
batch_size=6
input = np.random.rand(batch_size, 3, 480, 480)*256
input = np.floor(input).astype(np.float32)
pred = sess.run([label_name], {input_name: input})[0]
print(pred)
```

- Test models:
  Full fp16 model: https://drive.google.com/file/d/1lvoLHigqiWaB3eFPoStQ22L5Avh316h8/view?usp=sharing
  Partial fp16 model: https://drive.google.com/file/d/1Z2lrFbQ61mqZOapz4GQUUINn4aFCgvRH/view?usp=sharing
  Full fp32 model: https://drive.google.com/file/d/1LIFFxD8O39VITABQuH0H0Zx4kT3Wk-xd/view?usp=sharing

**Comment by ytaous** [comment]
@hariharans29 / @RyanUnderhill - any idea?

**Comment by hariharans29** [comment]
Paraphrasing the internal email we are having on this subject:

I believe this behavior is because the random input being fed to the model is not from a distribution that is representative of the distribution that was used to train the model. The scaling factor of 256 (input = np.random.rand(batch_size, 3, 480, 480)*256) seems to trigger overflows in InstanceNorm in the fp16 model. Ting has subsequently confirmed that feeding "real" images (with associated pre-processing) or even random inputs sampled from a distribution closer to the "real" distribution returns right results in fp16. There is no evidence to suggest that there is a problem with fp16 InstanceNorm at this stage.

@yetingqiaqia : If you feel this explains the behavior, can you please close this issue ?

**Comment by yetingqiaqia** [comment]
Thanks @hariharans29 . After internal sync through email, I think the behavior makes sense. I closed this issue for now and will do more tests.
