### ISSUE TITLE
how to use dynamic_quant to quantize an onnx model with custom op

### ISSUE THREAD

**Issue by wangyunxiaa** [microsoft/onnxruntime#10082]
**Is your feature request related to a problem? Please describe.**
Hi, I have a custom op, and i have register the op in onnxruntime.
now, I can use the api `opts.register_custom_ops_library(_lib_path("my_custom_op.so"))` to load the .so file, and do inference on the model with this custom op.
but, when I try to quant the model with this custom op, I git an error:
`onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from dfsmn_online.onnx failed:Fatal error: fsmn_forward is not a registered function/op`
I am confused that how to add the build .so file to onnxruntime.quantization and quant the model

**System information**
- ONNX Runtime version (you are using):
- 1.10.0

**Describe the solution you'd like**
quant the model with custom op 

**Describe alternatives you've considered**

**Additional context**

**Comment by wangyunxiaa** [comment]
I have solved this issue by add opts.register_custom_ops_library in python/tools/quantization/quantize.py
thanks.

**Comment by ruihe774** [comment]
@wangyunxiaa I ran into the same problem. I looked through quantize.py and did not find a way to solve the issue. How did you solve it?

**Comment by protoling** [comment]
If someone needs it someday.
You need to find the file `quant_utils.py` and add two lines:

import line
`from onnxruntime_extensions import get_library_path as _lib_path`
(probably pre-install the package first `pip install onnxruntime-extensions`)

And

`sess_option.register_custom_ops_library(_lib_path())`
in the method `def optimize_model(model_path: Path, opt_model_path: Path)`

**Comment by Liuhehe2019** [comment]
> If someone needs it someday. You need to find the file `quant_utils.py` in your site-packages and add two lines:
> 
> import line `from onnxruntime_extensions import get_library_path as _lib_path` (probably pre-install the package first `pip install onnxruntime-extensions`)
> 
> And in the method `def optimize_model(model_path: Path, opt_model_path: Path)`
> 
> `sess_option.register_custom_ops_library(_lib_path())`

I register the custom op in quant_utils.py, but also got the same error:

onnx.onnx_cpp2py_export.shape_inference.InferenceError: [TypeInferenceError] Cannot infer type and shape for node name xxx. No opset import for domain ai.onnx.contrib optype xxxx

could you give some more imformation, thanks!
