### ISSUE TITLE
DecoderAttention kernel Shape Inference bug on dynamic axes

### ISSUE THREAD

**Issue by rom1K** [microsoft/onnxruntime#10087]
**Describe the bug**

When specifying the past key and value in a `DecoderAttention` node, the shape inference fails if the batch size and sequence length are dynamic.

**Urgency**
Due to this bug the kernel is basically unusable, since you either must fix the batch size and sequence length, or not use the last key / value feature - which is the main feature of the kernel.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- ONNX Runtime installed from (source or binary): binary (wheel)
- ONNX Runtime version: 1.10
- Python version: 3.9.9
- Visual Studio version (if applicable): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 11.4
- GPU model and memory: GeForce RTX 2060, 6GB

**To Reproduce**
I've created this GIST to exhibit the error
-  [link](https://gist.github.com/rom1K/b9a1dbb313ce8cb1d53a188b170ed0cc)

**Expected behavior**
I expected dynamic shapes to be usable with the kernel, as is the case with the regular self-attention kernel.

**Additional context**
The line raising the error is [here](https://github.com/microsoft/onnxruntime/blob/4e9e01cb3c008335a2471c27dbdf7dd5d12e4224/onnxruntime/core/graph/contrib_ops/contrib_defs.cc#L557). As we can see from this [line](https://github.com/microsoft/onnxruntime/blob/4e9e01cb3c008335a2471c27dbdf7dd5d12e4224/onnxruntime/core/graph/contrib_ops/contrib_defs.cc#L518) a bit above, which does the shape inference check for the older attention kernel, the check is done only on non-dynamic axis (number of heads and head size).

**Comment by wangyems** [comment]
@rom1K Thanks for reporting the issue!

**Comment by rom1K** [comment]
No problem, thanks for the fix !
