### ISSUE TITLE
RandomNormal with integer output seems ill-specified

### ISSUE THREAD

**Issue by ArchRobison** [microsoft/onnxruntime#10101]
The specification https://github.com/onnx/onnx/blob/master/docs/Operators.md#RandomNormal seems to allow `RandomNormal` to have integer output. It's not clear to me if the implementation is correct, or even how to write a correct implementation.

For example, suppose the output has type `int32`, the mean is 1, and the scale is 1.0.  Simply generating a set of floating-point values with that mean and scale, and then converting to `int32` biases the mean towards zero and shrinks standard deviation. The net effect is a mean of about 0.66 and standard deviation of 0.83.  I have not yet run this example with the ONNX runtime, but looking over the code I didn't see compensation for these effects.

What does the ONNX runtime do, and what _should_ it do for int32 output?

**Comment by skottmckay** [comment]
>Type Constraints
T : tensor(float16), tensor(float), tensor(double)
Constrain output types to float tensors.

What makes you think it allows integer output?

**Comment by ArchRobison** [comment]
My error. I missed the type constraints at the end. Thanks!
