### ISSUE TITLE
Can't Use INT8 Input Data on Quantized Model

### ISSUE THREAD

**Issue by Hamptonjc** [microsoft/onnxruntime#10100]
I am currently trying to export a LSTM from PyTorch and quantize it. However I would like for it to accept INT8 data instead of FP32. When trying to use static quantization with an INT8 calibration data, I get the error: "InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int8)) , expected: (tensor(float))". 

Below is my process:

```python
# Imports
import torch
import onnx
import onnxruntime as ort
import numpy as np
from onnxruntime.quantization import quantize_static, CalibrationDataReader

# Create Torch module
class MyLSTM(torch.nn.Module):

  def __init__(self):
    super().__init__()
    self.model = torch.nn.LSTM(input_size=512, hidden_size=128, batch_first=True)

  def forward(self, input, hx, cx):
    return self.model(input, (hx, cx))

# Instantiate
m = MyLSTM()

# Create samples/names for exporter
input_sample = torch.randn((1,1,512))
hidden_sample = torch.randn((1,1,128))
cs_sample = torch.randn((1,1,128))
input_names = ["input", "hidden_0", "cell_st_0"]
output_names = ["output", "hidden_1", "cell_st_1"]

# Export to ONNX
torch.onnx.export(m, (input_sample, hidden_sample, cs_sample),
                  "./LSTM.float.onnx", input_names=input_names, 
                  output_names=output_names)


# fake data for onnx quantizer to calibrate on
class PsuedoData(CalibrationDataReader):

    def __init__(self, size):
        super().__init__()
        self.size = size
        self.it = 0

        
    def get_next(self):
        self.it += 1
        if self.it == self.size:
            return None
        else:          
            return {'input':np.random.random((1,1,512)).astype(np.int8),
                    'hidden_0':np.random.random((1,1,128)).astype(np.int8),
                    'cell_st_0':np.random.random((1,1,128)).astype(np.int8)
                   }

# Instantiate
cali_data = PsuedoData(size=1000)

# Quantize
quantize_static("./LSTM.float.onnx", "/LSTM.quant.onnx", cali_data)
```

I have also used float32 data in the calibration dataset. The model successfully quantizes. However I still get the error when I try to use INT8 data on the quantized model. Any suggestions?

**Comment by chausner** [comment]
I think quantization only changes the data types internally for weights and activations but keeps the original data type for input and output nodes. This means, even after quantizing your model to int8 you are supposed to provide float32 data as input if that was the original data type.

**Comment by Hamptonjc** [comment]
> I think quantization only changes the data types internally for weights and activations but keeps the original data type for input and output nodes. This means, even after quantizing your model to int8 you are supposed to provide float32 data as input if that was the original data type.

Correct. Is there a way I can change the input data type to int8? To use int8 data in PyTorch I must quantize the model using their quantization. However to my knowledge PyTorch quantized models can't be exported to onnx.

**Comment by skottmckay** [comment]
Usually the input would be fp32 otherwise you need zero point and scale information. 

In the pytorch quantization [documentation](https://pytorch.org/docs/stable/quantization.html) the input to the quantized model is still fp32.

```python
# Convert the observed model to a quantized model. This does several things:
# quantizes the weights, computes and stores the scale and bias value to be
# used with each activation tensor, and replaces key operators with quantized
# implementations.
model_int8 = torch.quantization.convert(model_fp32_prepared)

# run the model, relevant calculations will happen in int8
res = model_int8(input_fp32)
```
