### ISSUE TITLE
is batch inference supported in dynamic quantization?

### ISSUE THREAD

**Issue by rohanshingade** [microsoft/onnxruntime#10111]
**Describe the bug**
I used dynamic quantization to quanitze the model. However running with different batch size, give inconsistent model prediction.

**System information**
- OS Platform and Distribution: Ubuntu 18.04.5 LTS
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.
- Python version: 1.8.0
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Expected behavior**
Model prediction should not change as batch size changes

**Comment by yufenglee** [comment]
It is expected. For dynamic quantization, quantization parameters of activation(scale and zero point) are computed dynamically. With different batch size, the scale and zero point will change and thus introduce difference. You can use static quantization if you requires result to be exactly same.
