### ISSUE TITLE
What's the fastest way to view my implemented changes?

### ISSUE THREAD

**Issue by igaloly** [microsoft/onnxruntime#10112]
I'm implementing some modifications to the python module, which includes modifying `CPP`, `header`, and `python` files.

Currently, when I modify files, I run `.\build.bat --build_wheel --parallel` to generate a `wheel` file to install.
This process is pretty slow.

Is there any other way, so that I'll be able to work fast on it? :)

**Comment by harshithapv** [comment]
Unfortunately, this is the only way for now. You can turn off tests using --skip_tests. If you are modifying only python files you can replace them in your "site-packages" but it should be done with caution.

**Comment by igaloly** [comment]
@harshithapv Thanks for the help! :)

**Comment by skottmckay** [comment]
Specify `--build` so it will skip both the update and the test stages.

Additionally, in the build output directory would be a folder called 'onnxruntime' with the python module. I usually make sure onnxruntime is not installed as a pip package, and run python from the build output directory. It will use the 'onnxruntime' directory there for the 'import onnxruntime'. With that setup there's no need to install the wheel. To validate you're loading ORT from there you can run `help(onnxruntime)` and check the directory at the end of that output. 

e.g. output from python console where the location of the package is listed at the end. in this case it's using the pip package on Windows. if it was loading from the build output directory the path to __init__.py should reflect that.

```
>>> import onnxruntime
>>> help(onnxruntime)
...
FILE
    c:\users\bob\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages\onnxruntime\__init__.py

```

**Comment by igaloly** [comment]
Great tips @skottmckay ! Much appreciated
