### ISSUE TITLE
Error of building onnxruntime from source

### ISSUE THREAD

**Issue by brevity2021** [microsoft/onnxruntime#10125]
**Describe the bug**
Hi, I was trying to build the onnxruntime from source (with no changes), but it results in the following error when the building was 56%:
"/home/xx/docker_container/onnxruntime/cmake/external/onnx-tensorrt/onnx2trt_utils.hpp:377:117: error: ‘**nvinfer1::ScatterMode’ has not been declared**
  377 |     IImporterContext* ctx, const ::ONNX_NAMESPACE::NodeProto& node, std::vector<TensorOrWeights>& inputs, nvinfer1::ScatterMode mode, int32_t axis = 0);
      |                                                                                                                     ^~~~~~~~~~~
make[2]: *** [external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/build.make:76: external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/NvOnnxParser.cpp.o] Error 1"

Can you help take a look at what causes this?
I was trying to build an OnnxRuntime with tensorrt, with java bindings inside a nvidia container. I put the details in the "Reproduce" section.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: latest master (the last commit is [this](https://github.com/microsoft/onnxruntime/pull/10105))
- Python version: 3.8.10
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): cmake 3.22
- CUDA/cuDNN version:  11.4
- GPU model and memory: V100, 16G

**To Reproduce**
Start a nvidia tensorrt container 21.10-py3
Install the cmake cmake-3.22.1-linux-x86_64.sh (from [here](https://cmake.org/download/))
Git clone the onnxruntime repo. The last commit is [this](https://github.com/microsoft/onnxruntime/pull/10105)
Run "./build.sh --cudnn_home /usr/lib/x86_64-linux-gnu --cuda_home /usr/local/cuda --use_tensorrt --tensorrt_home /opt/tensorrt --build_java"

**Expected behavior**
Build success

**Comment by jywu-msft** [comment]
onnxruntime master requires tensorrt 8.2 - please use the latest nvidia tensorrt container 21.12-py3 which includes tensorrt 8.2
container 21.10 includes tensorrt 8.0

**Comment by brevity2021** [comment]
Thanks! 21.12 works. I also wonder can we build onnxruntime_gpu.jar instead of onnxruntime.jar? I only find onnxruntime-1.11.0-javadoc.jar onnxruntime-1.11.0-sources.jar  onnxruntime-1.11.0.jar in the build folder.

**Comment by jywu-msft** [comment]
sorry, i'm not very familiar with the java build.
@craigacp would you be able to answer the question?

**Comment by Craigacp** [comment]
The onnxruntime_gpu.jar is produced by the CI when it aggregates all the different GPU build artifacts together, and I think it's just a renamed onnxruntime jar with an updated pom, so there isn't much special about it. If you rename the jar (and update the pom) that's produced by Gradle you'll end up with the same thing.

**Comment by brevity2021** [comment]
Thanks for the explanations! Really helpful.
