### ISSUE TITLE
Large performance discrepancy between Chrome and Firefox onnxruntime-web WASM inference (unless Chrome profiler is enabled)

### ISSUE THREAD

**Issue by ziyadedher** [microsoft/onnxruntime#10134]
**Describe the bug**
There is a large discrepancy in execution speed of the attached model depending on whether it is running in Chrome or Firefox, being nearly twice as fast on Firefox. Both inference sessions are using the same WASM back-end. However, if we run the model with Chrome profiling enabled, the speeds are much closer.

All times are measured using `performance.now` calls. Running regularly on Chrome, model execution time is ~2600ms. Running regularly in Firefox, model execution time is ~1350ms. If we enable profiling on Chrome, model execution time is ~1200ms. I have no clue what is causing this, and I can't really profile it to figure it out :stuck_out_tongue: 

**Urgency**
None.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- ONNX Runtime installed from (source or binary): Binary
- ONNX Runtime version: 1.10.0

**Additional context**
The model is too large to attach to this GitHub Issue, you can download it [here](https://storage.ziyadedher.com/darkarts/models/onnx/stylegan2-ffhq-256x256.generator.onnx.pb).

**Comment by fs-eire** [comment]
Thank you for the feedback. Did you check if the multi-threading and SIMD features are ON or OFF? (it can be figured out by checking the requested .wasm file name)

**Comment by ziyadedher** [comment]
Wow... :face_with_head_bandage: Devtools being open is what caused this. Closing devtools brings it down to ~1350ms. Yikes. I would have never expected such a large difference. Amazing!

Thanks a lot, I'll close this issue out.

**Comment by fs-eire** [comment]
> Wow... 🤕 Devtools being open is what caused this. Closing devtools brings it down to the expected latency. Yikes. I would have never expected such a large difference. Amazing!
> 
> Thanks a lot, I'll close this issue out.
> 
> EDIT: FYI, the Devtools were still open when profiling in Chrome. I assume Chrome does some stuff to make it so that the performance is much more similar to Devtools not being open, when running perf.

yes, by defualt devtools attach a debugger to JS VM which slows down the execution, and it is disabled by devtool in profiling mode
