### ISSUE TITLE
What's the most time-consuming process in python's `InferenceSession` class init?

### ISSUE THREAD

**Issue by igaloly** [microsoft/onnxruntime#10131]
What's the most time-consuming process in python's `InferenceSession` class init?
By profiling using `cProfile`, I have noticed that the `_create_inference_session` which runs in `InferenceSession`'s init is the most time-consuming.

I consulted with the great @xadupre which explained to me that the process of `InferenceSession` is generally as follows:
Model Loading -> Graph Optimization -> Data Structure Modifications.

Xavier recommended that saving and using the optimized graph **may** save time. I've tried it, and even though a bit of time was saved, the change wasn't significant.
You can try it yourself in this Colab notebook: https://colab.research.google.com/drive/1KwtH90g2NPC8P_bmTT31GdytV2OlS8Y7?usp=sharing

If the Graph Optimization isn't the bottleneck, then I may assume that `Model Loading` or `Data Structure Modifications` is.

I want to understand a bit more about the Model Loading process.
If for example, instead of passing a string (file path) to `InferenceSession`, I'd pass model bytes buffer, will there still be a Model Loading process? I assume No because the model is already loaded in the memory and the CPP code should just get the pointer to the memory location.

Also, I want to understand a bit better the Data Structure Modifying process.
Why is it needed and what's happening in the process?

**Comment by yuslepukhin** [comment]
ORT is designed to give you the best performance at inference time. So we try to do as much work as possible when we load it once, optimized it and then you can execute it multiple times.
That is why we read the model (does not matter if the bytes are on disk or already in memory), sort the graph in topological order, resolve it (find appropriate kernels - implementations for each graph node that take into account versioning and kernel signatures), apply optimizations and do many other things to make execution possible.
Your question is very wide. Read the documentation and if you want to know more details, read the code.

**Comment by igaloly** [comment]
@yuslepukhin 
Why some of the procedures that are running in Inference Time were not implemented during the build time (conversion to the ONNX model)?

**Comment by skottmckay** [comment]
Model loading involves conversion from the ONNX format to the internal ORT data structures. Whether the ONNX model comes from bytes or a file on disk doesn't affect the need for this conversion.

During the creation of the session we do this conversion, run any applicable optimizations (which take into account the execution providers that are enabled and the current hardware), create plans for execution and memory allocation, move initializers to the device they're required on, and various other things. This is all one-off work though, and what generally matters the most is the execution time to run the model, as an InferenceSession instance supports multiple concurrent requests. i.e. you should re-use the InferenceSession and not create a new one for each request.

**Comment by igaloly** [comment]
@skottmckay 
The extra details about the `InferenceSession` init are great!

From what you said, I assume there aren't many procedures that can be made in build time, right?

Moreover, I think your idea of re-using the `InferenseSession` instance is great.
Unfortunately, I don't see how it is possible currently.

For example, I have a web server that returns a prediction on request.
For each request, I need to: Fetch the model -> Create an `InferenceSession` instance -> Predict.
You can see that the instance initialization happens on each request.

I can cache the instance on the current server, but if my infrastructure is horizontally scaled, and because of the lack of serialization of the instance, the user might end up reaching a different server, that doesn't have the instance in memory.

Moreover, if I have a lot of models, saving all of them always in memory is not efficient.

I would love to hear more of your thoughts! :)

**Comment by skottmckay** [comment]
If you save the optimized model there's not much else you can do to reduce the cost of creating the inference session.

If the cost of caching all the models on all servers is too high, I'd suggest the selection of the server for a request should take into account the model involved so that you limit the number of models an individual server would need to cache.

**Comment by igaloly** [comment]
Got it.
Thank you for all of your help, @skottmckay 
I really appreciate it!

**Comment by AnakTeka** [comment]
@igagoly

> What's the most time-consuming process in python's `InferenceSession` class init? By profiling using `cProfile`, I have noticed that the `_create_inference_session` which runs in `InferenceSession`'s init is the most time-consuming.
> 
> I consulted with the great @xadupre which explained to me that the process of `InferenceSession` is generally as follows: Model Loading -> Graph Optimization -> Data Structure Modifications.
> 
> Xavier recommended that saving and using the optimized graph **may** save time. I've tried it, and even though a bit of time was saved, the change wasn't significant. You can try it yourself in this Colab notebook: https://colab.research.google.com/drive/1KwtH90g2NPC8P_bmTT31GdytV2OlS8Y7?usp=sharing
> 
> If the Graph Optimization isn't the bottleneck, then I may assume that `Model Loading` or `Data Structure Modifications` is.
> 
> I want to understand a bit more about the Model Loading process. If for example, instead of passing a string (file path) to `InferenceSession`, I'd pass model bytes buffer, will there still be a Model Loading process? I assume No because the model is already loaded in the memory and the CPP code should just get the pointer to the memory location.
> 
> Also, I want to understand a bit better the Data Structure Modifying process. Why is it needed and what's happening in the process?

@igaloly do you still have the Colab notebook? I'm trying to pickle the `InferenceSession objects` to no avail, would be great if you have any pointer to pickle the `InferenceSession objects` object.
