### ISSUE TITLE
ONNXRTv1.10 Model Format v8, works on python and crash on C++ run. 

### ISSUE THREAD

**Issue by ibrahimsoliman97** [microsoft/onnxruntime#10145]
**Describe the bug**
I am using a ONNX Model with v8 format, it works using python, but it crash on Run() for C++ without showing any error message. I am using the latest ONNXRuntime v.1.10.0. I have attached the model for your reference. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.10.0
- Python version: 3.8
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- [code.txt](https://github.com/microsoft/onnxruntime/files/7787198/code.txt)
- [model](https://drive.google.com/file/d/149KO9WjhrkCnGYb9ag6C_8Jv7KD_vJSx/view?usp=sharing)
- [Session VERBOSE log running ONNXRuntime](https://github.com/microsoft/onnxruntime/files/7787205/logs.txt)

**Expected behavior**
Model should work and run smoothly on C++ as well / **Show error message about the problem**.

**Screenshots**
![image](https://user-images.githubusercontent.com/30038478/147624636-86656905-d6ae-423b-8675-fbe7eddb1509.png)

**Comment by skottmckay** [comment]
I created a unit test with the contents of code.txt it ran without any problems using the model you provided. Is the contents of code.txt exactly the same as when you see the issue?

**Comment by ibrahimsoliman97** [comment]
@skottmckay Sorry for inconvenience and Thanks for testing this.
The issue is caused by my environment: 
1- My anti-virus sometimes crash the Visual Studio project/Unit Test(In Debug Mode), it is not related to onnxruntime.
2- there was a spelling mistake in (input) at my code before copying to code.txt which cause ORT_INVALID_ARGUMENT as shown on my screenshot.

I will close this issue and Thanks again.
