### ISSUE TITLE
Bug ld: error: undefined symbol: pthread_cancel  for android runtime AAR build

### ISSUE THREAD

**Issue by shichaog** [microsoft/onnxruntime#10144]
**Describe the bug**
Build onnxruntime package for Android AAR

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from source
- ONNX Runtime version: master branch
- Python version:
Python 3.9.9 (v3.9.9:ccb0e6a345)
[Clang 6.0 (clang-600.0.57)] on darwin

**To Reproduce**
./build.sh --android --use_nnapi --build_java --android_sdk_path Android/sdk --android_ndk_path Android/sdk/ndk/23.1.7779620/ --android_abi arm64-v8a --android_api 27 --parallel

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7869827/147619548-fcca4d3c-18d4-4e5a-ba53-7e5be204c964.png)
![image](https://user-images.githubusercontent.com/7869827/147619581-ce6e0bdf-88fd-4d34-ab9a-a20e9f876eb6.png)

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by skottmckay** [comment]
CMake seems to have an issue on macos finding gradle, even if its directory is included in PATH. The error you have pasted about pthread_cancel is not the actual problem, and there was most likely some cmake output to the terminal saying it couldn't find gradle immediately prior to where your first screenshot starts.

I was able to work around this by manually specifying the path to gradle in cmake/onnxruntime_java.cmake. Short term can you try doing that?

```cmake
diff --git a/cmake/onnxruntime_java.cmake b/cmake/onnxruntime_java.cmake
index 722fb09eb..7e2a3d83b 100644
--- a/cmake/onnxruntime_java.cmake
+++ b/cmake/onnxruntime_java.cmake
@@ -26,7 +26,8 @@ else()
     # fall back to gradle on our PATH
     find_program(GRADLE_EXECUTABLE gradle)
     if(NOT GRADLE_EXECUTABLE)
-        message(SEND_ERROR "Gradle installation not found")
+        # message(SEND_ERROR "Gradle installation not found")
+        set(GRADLE_EXECUTABLE "/Users/smckay/Downloads/gradle-7.3.3/bin/gradle")
     endif()
 endif()
```
