### ISSUE TITLE
onnxruntime-web build contains browser incompatible requires e.g. worker_threads, fs, os

### ISSUE THREAD

**Issue by lincolnneu** [microsoft/onnxruntime#10140]
**Describe the bug**
The onnxruntime-web npm package 1.10.0 contains node.js exclusive requires, such as
```
var a=require("worker_threads")
var r=require("fs")
...
```
in [onnxruntime-web@1.10.0/dist/ort-wasm-threaded.worker.js](https://cdn.jsdelivr.net/npm/onnxruntime-web@1.10.0/dist/ort-wasm-threaded.worker.js)

These requires make the onnxruntime-web not usable in browser environment.

**Urgency**
Blocker.

**System information**
This is a universal issue for web users.

**To Reproduce**
Go to https://cdn.jsdelivr.net/npm/onnxruntime-web@1.10.0/dist/ort-wasm-threaded.worker.js search for a=require("worker_threads")

**Expected behavior**
onnxruntime-web for browser should not contains node.js exclusive libraries.

**Screenshots**
![image](https://user-images.githubusercontent.com/39422558/147463652-5b013768-b9bd-486a-b70d-302156610bcc.png)

**Additional context**
Suggestion: instead of using require("worker_threads"), use __non_webpack_require__("worker_threads")  [Similar issue in stackoverflow](https://stackoverflow.com/questions/52581441/ignoring-specific-requires-in-webpack)

**Comment by fs-eire** [comment]
Hi @lincolnneu did you try to use multi-threading in browsers? Those lines ( that uses `require()` ) are in an if-clause that will only run in Node.js (condition is `process.versions.node` is not undefined). This is by-design and expected. If it fails in browser environment, please let me know the reproduce steps and I will take a further investigation.

The stackoverflow link is about how to preserve "require()" in the source code, which is what we have now.

**Comment by lincolnneu** [comment]
@fs-eire  thanks for explanation. This is confusing our linter system. Is it possible to separate node.js version from browser version? e.g. instead of having one npm package onnxruntime-web for both node.js and browser, create two npm packages, maybe onnxruntime-web-node and onnxruntime-web-browser?

**Comment by fs-eire** [comment]
I am not sure how do you configure your repository for linter, but usually we don't enable linter for dependencies (eg. exclude /node_modules folder). Specifically, you should skip those build tools for the dist files (.js) of all your dependencies ( This is also the default behavior of bundlers eg. webpack)

There are different properties inside the package's package.json ( "main" and "browser" ) to indicate tools to behave as expected. For example, we have different main file for browsers (ort.min.js) and node.js (ort-web.node.js) for ONNX Runtime. To simplify the distribution process, we use single file **ort-wasm-threaded.js** for both web and node.js

If this linter error is generated by webpack, that is another story. We do not expect webpack to process file ort-wasm-threaded.worker.js if onnxruntime-web is consumed as a dependency library. If this is the case, please share the reproduce steps and I will take a look into it.

**Comment by sonovice** [comment]
I believe this is directly related to https://github.com/microsoft/onnxruntime-web-demo/issues/15

**Comment by fs-eire** [comment]
@sonovice, Thank you for sharing the information.

I didn't use Vite as a bundler before. ORT Web always use webpack as its bundler. But this is not the problem. The problem is, we didn't expect users (webapp developers who consume onnxruntime-web) to run bundlers on source code of onnxruntime-web.

As mentioned in https://github.com/microsoft/onnxruntime-web-demo/issues/15, Vite actually run into scan file 'onnxruntime-web/lib/wasm/proxy-wrapper.js'. This is not what I expected; my expectation is the bundler picks up the single file 'dist/ort-web.min.js' directly, skipping the building phrase and ignores anything under folder 'onnxruntime-web/lib'.

[the "browser" field](https://github.com/microsoft/onnxruntime/blob/master/js/web/package.json#L3)

**Comment by guschmue** [comment]
I assume this is no longer an issue.
