### ISSUE TITLE
Unable to compile with #include onnxruntime_cxx_api.h

### ISSUE THREAD

**Issue by yusramoni** [microsoft/onnxruntime#10158]
**Describe the bug**
I currently have a simple project where the code will simply print hello word. I am unable to compile the executable because the #include <onnxruntime_cxx_api.h> has several seemingly syntax issues that I believe is a compilation issue and not the code itself. I would like some clarification

**Urgency**
Urgent: ASAP. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS
- ONNX Runtime installed from (source or binary): onnxruntime-osx-arm64-1.10.0.tgz
- ONNX Runtime version: v1.10.0
- Python version: n/a
- Visual Studio version (if applicable): using vs code because visual studio for Mac is not compatible with c++
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**To Reproduce**
simple have a main with #include <iostream> and #include<onnxruntime_cxx_api.h> with the main printing hello word.
the makefile or cmakelists include_directories to the onnxrutime installation path as well as folders within such as include and lib. 

**Expected behavior**
hello word and file compiles without any errors

**Screenshots**
the errors: (I removed some of the errors from the messages to be a little more concise and provide an overall idea of the error message)
[ 50%] Building CXX object CMakeFiles/onnxruntime_test.dir/Users/rahmayi1/Documents/onnx_test/model_explorer.cpp.o
In file included from /Users/rahmayi1/Documents/onnx_test/model_explorer.cpp:6:
In file included from /Users/rahmayi1/Documents/onnxruntime-osx-arm64-1.10.0/include/onnxruntime_cxx_api.h:16:
/Users/rahmayi1/Documents/onnxruntime-osx-arm64-1.10.0/include/onnxruntime_c_api.h:349:41: error: expected member name or ';' after declaration specifiers
  OrtCUDAProviderOptions() : device_id{}, cudnn_conv_algo_search{OrtCudnnConvAlgoSearchExhaustive}, gpu_mem_limit{SIZE_MAX}, arena_extend_strategy{}, do_copy_in_default_stream{1}, has_user_compute_stream{}, user_compute_stream{}, default_memory_arena_cfg{} {}
                                        ^
/Users/rahmayi1/Documents/onnxruntime-osx-arm64-1.10.0/include/onnxruntime_c_api.h:349:39: error: expected '('
  OrtCUDAProviderOptions() : device_id{}, cudnn_conv_algo_search{OrtCudnnConvAlgoSearchExhaustive}, gpu_mem_limit{SIZE_MAX}, arena_extend_strategy{}, do_copy_in_default_stream{1}, has_user_compute_stream{}, user_compute_stream{}, default_memory_arena_cfg{} {}
                                      ^
/Users/rahmayi1/Documents/onnxruntime-osx-arm64-1.10.0/include/onnxruntime_c_api.h:408:41: error: expected member name or ';' after declaration specifiers
  OrtROCMProviderOptions() : device_id{}, miopen_conv_exhaustive_search{0}, gpu_mem_limit{SIZE_MAX}, arena_extend_strategy{}, do_copy_in_default_stream{1}, has_user_compute_stream{}, user_compute_stream{}, default_memory_arena_cfg{} {}
                                        ^
/Users/rahmayi1/Documents/onnxruntime-osx-arm64-1.10.0/include/onnxruntime_c_api.h:408:39: error: expected '('
  OrtROCMProviderOptions() : device_id{}, miopen_conv_exhaustive_search{0}, gpu_mem_limit{SIZE_MAX}, arena_extend_strategy{}, do_copy_in_default_stream{1}, has_user_compute_stream{}, user_compute_stream{}, default_memory_arena_cfg{} {}
                                      ^
In file included from /Users/rahmayi1/Documents/onnx_test/model_explorer.cpp:6:
/Users/rahmayi1/Documents/onnxruntime-osx-arm64-1.10.0/include/onnxruntime_cxx_api.h:40:24: warning: rvalue references are a C++11 extension [-Wc++11-extensions]
  Exception(std::string&& string, OrtErrorCode code) : message_{std::move(string)}, code_{code} {}
                       ^
/Users/rahmayi1/Documents/onnxruntime-osx-arm64-1.10.0/include/onnxruntime_cxx_api.h:40:83: error: expected member name or ';' after declaration specifiers
  Exception(std::string&& string, OrtErrorCode code) : message_{std::move(string)}, code_{code} {}
                                                                                  ^
/Users/rahmayi1/Documents/onnxruntime-osx-arm64-1.10.0/include/onnxruntime_cxx_api.h:40:64: error: expected '('
  Exception(std::string&& string, OrtErrorCode code) : message_{std::move(string)}, code_{code} {}
                                                               ^
/Users/rahmayi1/Documents/onnxruntime-osx-arm64-1.10.0/include/onnxruntime_cxx_api.h:40:82: error: expected ';' after expression
  Exception(std::string&& string, OrtErrorCode code) : message_{std::move(string)}, code_{code} {}
                                                                                 
/Users/rahmayi1/Documents/onnxruntime-osx-arm64-1.10.0/include/onnxruntime_cxx_api.h:154:3: error: unknown type name 'constexpr'
  constexpr bool operator!=(const Float16_t& rhs) const noexcept { return value != rhs.value; };
  ^
/Users/rahmayi1/Documents/onnxruntime-osx-arm64-1.10.0/include/onnxruntime_cxx_api.h:154:56: error: expected ';' at end of declaration list
  constexpr bool operator!=(const Float16_t& rhs) const noexcept { return value != rhs.value; };
                                                       ^
                                                       ;
/Users/rahmayi1/Documents/onnxruntime-osx-arm64-1.10.0/include/onnxruntime_cxx_api.h:169:3: error: unknown type name 'constexpr'
  constexpr BFloat16_t() noexcept : value(0) {}
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
3 warnings and 20 errors generated.

the make list:
cmake_minimum_required(VERSION 3.10)
project(onnxruntime_test)
add_executable(onnxruntime_test ../model_explorer.cpp)
set(ONNXRUNTIME_ROOTDIR "/Users/rahmayi1/Documents/onnxruntime-osx-arm64-1.10.0")
include_directories("${ONNXRUNTIME_ROOTDIR}/include")
link_directories("${ONNXRUNTIME_ROOTDIR}/lib")

**Comment by skottmckay** [comment]
Which specific C++ compiler are you using? ORT requires C++17, however `constexpr` has been part of C++ since C++11 so the last error about constexpr being an unknown type name suggests your compiler may be even older than that. 

What if you tell cmake that C++17 is required by adding this to the CMakeLists.txt?

```cmake
set(CMAKE_CXX_STANDARD 17)
```

**Comment by yusramoni** [comment]
that worked for most of the errors! I'm getting a new one about architecture which I'm not familiar with. is there a dependent I'm missing?

new error:
Undefined symbols for architecture x86_64:
  "_OrtGetApiBase", referenced from:
      ___cxx_global_var_init in model_explorer.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by skottmckay** [comment]
Does your cmake file add the onnx runtime library as a dependency of your executable, or you just add the link directory? I would expect you need to explicitly tell cmake which library to link against and not just where the library is.

**Comment by yusramoni** [comment]
I was able to figure out the issue. I've realized I installed the wrong onnxruntime for my platform. I needed the onnxruntime-osx-x86_64-1.10.0.tgz and not the onnxruntime-osx-arm64-1.10.0.tgz. Thanks for your help!

**Comment by yusramoni** [comment]
I am still unable to include the #include<onnxruntime_cxx_api.h>. I get a red line saying it is not found. does include_directories(${ONNXRUNTIME_ROOTDIR}/include) not simply provide the path in which it will be?
