### ISSUE TITLE
sample code for vitis-ai provider using c/c++

### ISSUE THREAD

**Issue by manuel-sanchez-nttdisruption** [microsoft/onnxruntime#10164]
**Is your feature request related to a problem? Please describe.**
I don't see any documentation using C++ API and Vitis-AI as EP.

**System information**
ONNX Runtime version (you are using): libonnxruntime.so.1.11.0

**Describe the solution you'd like**
Sample code for using onnxruntime library, with C++ API and vitis-ai as execution provider.

**Additional context**
execution of onnxruntime_test_all:
[----------] Global test environment tear-down
[==========] 3156 tests from 222 test suites ran. (76256 ms total)
[  PASSED  ] 3146 tests.
[  SKIPPED ] 10 tests, listed below:
[  SKIPPED ] InferenceSessionTests.TestLenientShapeInferencing
[  SKIPPED ] SoftmaxOperator.InvalidAxis_opset13
[  SKIPPED ] SoftmaxOperator.DimWithZero
[  SKIPPED ] ConvTest.Conv1D_Invalid_Input_Shape
[  SKIPPED ] ConvTest.Conv2D_Invalid_Input_Shape
[  SKIPPED ] TfIdfVectorizerTest.Int32_TF_onlyBigrams_Skip0_Empty_Dim1Fail
[  SKIPPED ] TfIdfVectorizerTest.Int32_TF_onlyBigrams_Skip0_Empty_Dim2
[  SKIPPED ] TfIdfVectorizerTest.Int32_TF_onlyBigrams_Skip01_Empty_Dim2
[  SKIPPED ] TensorOpTest.Unsqueeze_Duplicate
[  SKIPPED ] TensorOpTest.Unsqueeze_OutOfRange

**Comment by pranavsharma** [comment]
You can call OrtSessionOptionsAppendExecutionProvider_VITISAI from vitisai_provider_factory.h.

**Comment by manuel-sanchez-nttdisruption** [comment]
hi @pranavsharma, I already found OrtSessionOptionsAppendExecutionProvider_VITISAI but my question is how do I fill the arguments. What does it mean each of the parameters?

_In_ OrtSessionOptions* options: I guess this is the options struct as in any other EP.
const char* backend_type: ???
int device_id: I guess is the device id from "xbutil scan"
const char* export_runtime_module: ???
const char* load_runtime_module: ???

Regards.

**Comment by pranavsharma** [comment]
Have you checked https://onnxruntime.ai/docs/execution-providers/Vitis-AI-ExecutionProvider.html?

**Comment by manuel-sanchez-nttdisruption** [comment]
Sure I did. That is why I am asking. There is no sample code for C++, just for python. Am I missing something?

**Comment by pranavsharma** [comment]
Yes, we don't have API for C++ currently. The C++ API is just a thin wrapper on top of the C API.

**Comment by manuel-sanchez-nttdisruption** [comment]
OK, then this chart needs to be updated dimming C++ and C boxes.

![imagen](https://user-images.githubusercontent.com/60776650/147990361-25c74f3f-b8ff-42e4-899e-6a9f0337a64e.png)

Thanks for your support.

**Comment by manuel-sanchez-nttdisruption** [comment]
by the way I successfully compiled the library and run onnxruntime_test_all on Xilinx Kria board. You can add it to the list of supported boards.

**Comment by pranavsharma** [comment]
> OK, then this chart needs to be updated dimming C++ and C boxes.
> 
> ![imagen](https://user-images.githubusercontent.com/60776650/147990361-25c74f3f-b8ff-42e4-899e-6a9f0337a64e.png)
> 
> Thanks for your support.

@faxu FYI
