### ISSUE TITLE
ONNXRUNTIME import error in container in Jetson 

### ISSUE THREAD

**Issue by EnricoBeltramo** [microsoft/onnxruntime#10182]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.
onnxruntime import error inside docker container running in Jetson Xavier

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.
Production application, due time for project: 15/01/22

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Jetson Xavier
- ONNX Runtime installed from (source or binary): 1.4
- ONNX Runtime version: 1.4
- Python version: 3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2
- GPU model and memory: Jetson Xavier

**To Reproduce**
- Describe steps/code to reproduce the behavior.
-  inside Jetson, create a simple docker container based on jetpack4.4 called Dockerfile.onnx.base:
FROM mcr.microsoft.com/azureml/onnxruntime:v.1.4.0-jetpack4.4-l4t-base-r32.4.3
- build the docker image:
docker build -t onnx.cuda -f Dockerfile.onnx.base .
- start docker using nvidia runtime:
docker run -it --runtime nvidia --name runtime.onnx nnx.cuda
- try import onnxruntime in python3:
- >>> import onnxruntime
/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/_pybind_state.py:14: UserWarning: Cannot load onnxruntime.capi. Error: 'libcublas.so.10: cannot open shared object file: No such file or directory'.
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'.".format(str(e)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/__init__.py", line 13, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
ImportError: cannot import name 'get_all_providers'

- Attach the ONNX model to the issue (where applicable) to expedite investigation. NA

**Expected behavior**
import run correctly

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.
We tried to install either different versions of onnxruntime, but we always have similar issue

**Comment by tianleiwu** [comment]
Usually, the error means some dependency (CUDA and cuDNN) is installed correctly.

According to https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html, 
<html>
<body>


ONNX Runtime | CUDA | cuDNN | Notes
-- | -- | -- | --
1.2-1.4 | 10.1 | 7.6.5 | Requires cublas10-10.2.1.243; cublas 10.1.x will not work


</body>
</html>

**Comment by EnricoBeltramo** [comment]
But the docker: mcr.microsoft.com/azureml/onnxruntime:v.1.4.0-jetpack4.4-l4t-base-r32.4.3 should not install all dependencies included CUDA?
Something shall be installed outsido of docker on Jetson OS in order to let in work? I tried to install either onnxruntime 1.6.0 but I have same issue

**Comment by EnricoBeltramo** [comment]
Any version of onnxruntime for arm64 looks be compiled for CUDA 10.2. The issues was due to a lot of missing dependencies in the base docker onnxruntime:v.1.4.0-jetpack4.4-l4t-base-r32.4.3. After we added the dependecies, the runtime worked correctly

**Comment by ksaye** [comment]
> Any version of onnxruntime for arm64 looks be compiled for CUDA 10.2. The issues was due to a lot of missing dependencies in the base docker onnxruntime:v.1.4.0-jetpack4.4-l4t-base-r32.4.3. After we added the dependecies, the runtime worked correctly

@EnricoBeltramo what did you run to add the dependencies?
