### ISSUE TITLE
 [python api] ShapeInferenceError：Mismatch between number of source and target dimensions. Source=2 Target=3 

### ISSUE THREAD

**Issue by zhuxiaoxuhit** [microsoft/onnxruntime#10197]
**Describe the bug**
I have checked onnx, it was really valid. But when use "sess_ort = ort.InferenceSession("model_ch.onnx")", I got error here:

```
Node:tagger_predict Output:tagger_predict [ShapeInferenceError] Mismatch between number of source and target dimensions. Source=2 Target=3
```

The code to check valid:
```
import onnx

# Preprocessing: load the ONNX model
#model_path = 'path/to/the/model.onnx'
model_path = 'model_ch.onnx'
onnx_model = onnx.load(model_path)

print('The model is:\n{}'.format(onnx_model))

# Check the model
try:
    onnx.checker.check_model(onnx_model)
except onnx.checker.ValidationError as e:
    print('The model is invalid: %s' % e)
else:
    print('The model is valid!')
```
result:
```
.......
  output {
    name: "tagger_predict"
    type {
      tensor_type {
        elem_type: 7
        shape {
          dim {dim_value: 1}
          dim {dim_value: 60 }
          dim {dim_value: 1}
}}}}}


opset_import {
  version: 15
}

The model is valid!

```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS
- ONNX Runtime version:1.10.0
- Python version: 1.13

**To Reproduce**
onnx model here:
https://drive.google.com/file/d/1JNPx-Eh8uzw8N-l4sWL1au5PGi8MqsON/view?usp=sharing

**Comment by zhuxiaoxuhit** [comment]
@snnn @skottmckay @edgchen1 Can someone help me~

**Comment by zhuxiaoxuhit** [comment]
Or Can we manual modify the output shape of onnx model?

**Comment by askhade** [comment]
ONNX checker by default does not run shape inference. You can enable shape inference by setting option full_check=True

I think once you run shape inference you will see the same error. You can manually modify the output typeproto - You can either update it or simply delete it and run shape inference again.

**Comment by zhuxiaoxuhit** [comment]
> manually modify the output typeproto

@askhade Pls share me documents~ I tred using python api like this :
```
import onnx
from onnx.tools import update_model_dims

model = onnx.load('path/to/the/model.onnx')

variable_length_model = update_model_dims.update_inputs_outputs_dims(model, {'input_name': ['seq', 'batch', 3, -1]}, {'output_name': ['seq', 'batch', 1, -1]})
```

It didn't work~

**Comment by skottmckay** [comment]
This will remove the shapes from graph outputs and subgraph inputs. After updating it runs shape inference and checks the model. 

I would recommend saving the model without the inferred shapes as it's smaller and they can obviously be inferred at runtime. Doesn't matter if you save the model with that info though.

```python
import onnx

def remove_shape(value):
  if value.type.HasField("tensor_type"):
    shape = value.type.tensor_type.shape
    if shape:
      value.type.tensor_type.ClearField('shape')


def update_graph(graph, level=0):
  # subgraph input shapes can be inferred so those can be removed if level > 0
  if level > 0:
    for input in graph.input:
      remove_shape(input)

  for output in graph.output:
    remove_shape(output)

  for node in graph.node:
    for attr in node.attribute:
      if attr.HasField('g'):
        update_graph(attr.g, level + 1)


model_path = "model_ch.onnx"
model = onnx.load_model(model_path)

update_graph(model.graph)

# check model
model_with_shape_info = onnx.shape_inference.infer_shapes(model)
onnx.checker.check_model(model_with_shape_info, True)
```

**Comment by zhuxiaoxuhit** [comment]
@skottmckay Thank you for your reply. I tried your code, it didnt work~

**Comment by zhuxiaoxuhit** [comment]
@skottmckay I got another error again~
```
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Gemm node. Name:'tagger_logits_1/add_Gemm__372' Status Message: GEMM: Dimension mismatch, W: {256,4} K: 15360 N:4
```

**Comment by skottmckay** [comment]
Your model appears to be invalid if that's the error.

https://github.com/onnx/onnx/blob/main/docs/Operators.md#inputs-2---3-3

```
Inputs (2 - 3)
A (differentiable) : T
Input tensor A. The shape of A should be (M, K) if transA is 0, or (K, M) if transA is non-zero.
B (differentiable) : T
Input tensor B. The shape of B should be (K, N) if transB is 0, or (N, K) if transB is non-zero.
C (optional, differentiable) : T
Optional input tensor C. If not specified, the computation is done as if C is a scalar 0. The shape of C should be unidirectional broadcastable to (M, N).
```

<img width="367" alt="image" src="https://user-images.githubusercontent.com/979079/148723197-bda67b36-750e-4d48-ba02-5b3934e0564a.png">

For this node, K == 15360 but the B input has shape {256, 4}. 15360 != 256 so the error is correct.

**Comment by zhuxiaoxuhit** [comment]
@skottmckay 
I do reshape it in my tensorflow code. I donnt know why now cann't find it in ONNX model.
Could you give me some advices?
```
output = tf.reshape(tf.concat(outputs, 1), [-1, 256])
```

**Comment by zhuxiaoxuhit** [comment]
@skottmckay
