### ISSUE TITLE
How to get rid of large native/onnxruntime.pdb

### ISSUE THREAD

**Issue by hanabi1224** [microsoft/onnxruntime#102]
**Describe the bug**
The onnxruntime.pdb is ~100M big and makes published netcoreapp2.1 package super large,  is there any way to opt out this file?  Thanks.

BTW, I would argue that given the file is so large, it will be better to opt-in packaging this pbd file than opt-out.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- ONNX Runtime installed from (source or binary): dotnet nuget package  v0.1.5
- ONNX Runtime version:  dotnet nuget package  v0.1.5
- Python version:
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: 

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pranavsharma** [comment]
@shahasad can you take a look? thx.

**Comment by shahasad** [comment]
It is a trade-off between debuggability and package size. Once option is the package the symbol files in a separate package.

**Comment by hanabi1224** [comment]
@jignparm  I'm not talking about nuget package size, when I publish a self-contained dotnet core app which consumes onnx runtime package,  the 100M+ pdb file will be part of binary output to deploy, which is unreasonable large, does that make sense?

**Comment by hanabi1224** [comment]
@jignparm  @pranavsharma  @shahasad   Kindly ping

**Comment by thomaslundgaard** [comment]
This issue has been marked as closed, even though it is still unsolved. When deploying ONNX runtime, it includes the 100M+pdb  file with debug symbols. It is not standard behaviour for nugets to include the symbols, especially when they are this big.
I would suggest to include the debug symbols in a separate nuget package, see https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

**Comment by snnn** [comment]
Change has been merged. The issue will be fixed in onnxruntime 1.9 release.
