### ISSUE TITLE
int8 poor performance

### ISSUE THREAD

**Issue by dodler** [microsoft/onnxruntime#10207]
Poor int8 performance during benchmark (int8 model is slower than float32) with openvino provider

not urgent

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18 04
- ONNX Runtime installed from (source or binary): docker image - openvino/onnxruntime_ep_ubuntu18
- ONNX Runtime version: onnxruntime-openvino==1.10
- Python version: 3.6.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: - 
- GPU model and memory: - 

**To Reproduce**
I'm using this code to prepare int8 model

`import onnx
from onnxruntime.quantization import quantize_dynamic, QuantType

model_fp32 = 'resnet50-v1-12.onnx'
model_quant = 'q_r50.onnx'
quantized_model = quantize_dynamic(model_fp32, model_quant, weight_type=QuantType.QUInt8)`

my benchmark script source

`import onnxruntime as ort
import numpy as np
import time
import sys

sess_options = ort.SessionOptions()

sess_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL

x=np.random.uniform(size=(1,3,224,224)).astype(np.float32)
n=1000
ort_sess = ort.InferenceSession(sys.argv[1], options=sess_options, providers=['OpenVINOExecutionProvider'], provider_options=[{'num_of_threads':4, 'device_type': 'CPU_FP32'}])

times = []
for i in range(n):
    s=time.perf_counter()
    outputs = ort_sess.run(None, {'data':x})
    e=time.perf_counter()
    est = int(1000*(e-s))
    times.append(est)

times = np.array(times)
print('avg', times.mean(), 'std', times.std(), '99p', np.percentile(times, 99))
`

Base model is this - https://github.com/onnx/models/blob/master/vision/classification/resnet/model/resnet50-v1-12.onnx

**Expected behavior**
I'm expecting int8 is 3 times faster (or at least not slower) than float32 (like here for example - https://community.intel.com/t5/Blogs/Tech-Innovation/Artificial-Intelligence-AI/Deep-Learning-Performance-Boost-by-Intel-VNNI/post/1335670)

Also onnxruntime is using 10 cores, but I'm trying to set 4
![image](https://user-images.githubusercontent.com/6881262/148362041-7ed480c7-abda-42c2-8aed-0ecdd433f1c6.png)

My cpu is Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz (also tested in aws and Intel(R) Core(TM) i9-9960X CPU @ 3.10GHz, same behaviour)

**Comment by yufenglee** [comment]
1. please use the static quantization, like the document below. And please use the weight_type QInt8 and quantize weight symmetrically, which get better perf usually: https://onnxruntime.ai/docs/performance/quantization.html#method-selection. 
2. the blog you mentioned is for CPU with VNNI(caslake or ice lake), but your CPU is pretty old(broadwell). 

BTW, why do you disable GraphOptimization?
