### ISSUE TITLE
how to merge two of Ort::Value together?

### ISSUE THREAD

**Issue by zzhhccqq** [microsoft/onnxruntime#10218]
Ort::Value value1, value2;
Ort::Value t_value;
// are there any functions to do as folllow:
t_value = Ort::Merge(value1, value2);

**Comment by snnn** [comment]
No. First, you need to define how to merge them.

**Comment by zzhhccqq** [comment]
i want to implement concat function like torch.tensor.cat()
for example, i want concate all Ort::Value to one Ort::Value
std::vector<Ort:Value> outputs;
Ort::Value output;
output = outputs.cat(outputs);
