### ISSUE TITLE
Inference time fluctuates hugely after calling Thread.Sleep() in C # API

### ISSUE THREAD

**Issue by feiyuhuahuo** [microsoft/onnxruntime#10226]
**Describe the bug**
I use the following code to do test.
```
    class Program
    {
        public static void Main()
        {
            string cls_model = "E:\\c_sharp_deploy/cls/solar_cell_cls.onnx";
            string cls_img = "E:\\c_sharp_deploy/cls/test_imgs/10005.png";

            int gpuDeviceId = 0;
            var cls_session = new InferenceSession(cls_model, SessionOptions.MakeSessionOptionWithCudaProvider(gpuDeviceId));

            for (int tt = 0; tt < 60; tt++)
            {
                int aa = Environment.TickCount;
                var cv2_img = cv2.imread(cls_img, IMREAD_COLOR.IMREAD_COLOR);
                var img = np.array(cv2_img).astype(NPTypeCode.Float);
                float[] sys_array = img.ToArray<float>();
                Tensor<float> img_tensor = new DenseTensor<float>(sys_array, new[] { 512, 512, 3 });
           
                var cls_input = new List<NamedOnnxValue> { NamedOnnxValue.CreateFromTensor("input", img_tensor) };
               
                int bb = Environment.TickCount;
                Console.WriteLine($"create input tensor {bb - aa}");
                using IDisposableReadOnlyCollection<DisposableNamedOnnxValue> cls_result = cls_session.Run(cls_input);
                int cc = Environment.TickCount;
                Console.WriteLine($"inference {cc - bb}");
                Console.WriteLine("----------------------------\n");
                Thread.Sleep(20);

            }
        }
    }
```
Inference time keeps the same if I do not use Thread.Sleep() or use sleep time <=50ms after each each inference iteration. 
![image](https://user-images.githubusercontent.com/32631344/148628249-2017e8ba-7252-432a-98f3-a4c3d05101a6.png)
If I use Thread.Sleep(500), some inference iteration times become long.
![image](https://user-images.githubusercontent.com/32631344/148628356-34c124b4-73cd-40b9-a9ed-54a8058633c5.png)
If I use Thread.Sleep(2000), all the inference times become  quite long.
![image](https://user-images.githubusercontent.com/32631344/148629456-5a89a70f-1665-499d-aab1-75ac172da3f1.png)

**Urgency**
It's some kind of urgent. Our product is delayed because of this.

**System information**
- WIN10
- ONNX Runtime installed from (source or binary): NuGet
- ONNX Runtime version: 1.10.0
- Python version: None
- Visual Studio version (if applicable): Microsoft Visual Studio Community 2019 version 16.11.8
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.5 / 8.2
- GPU model and memory: RTX2080 with MAX-Q design 8GB

**To Reproduce**
See description. Model will be attached if is needed.

**Expected behavior**
Whenever how long Thread.Sleep() is used, the inference time keeps the same.

**Screenshots**
None

**Additional context**
None

**Comment by skottmckay** [comment]
Please measure with System.Diagnostics.Stopwatch as that can use the high resolution timer. Environment.TickCount uses the system timer and is less precise.

Additionally, do not include a Console.Writeline in the section you measure as that's a potentially blocking call that is irrelevant.. Put your start/stop around just the session.Run call.

**Comment by feiyuhuahuo** [comment]
@skottmckay 
Hi, I use stopwatch to measure the time now.
```
                var cls_input = new List<NamedOnnxValue> { NamedOnnxValue.CreateFromTensor("input", img_tensor) };

                sw.Start();
                using IDisposableReadOnlyCollection<DisposableNamedOnnxValue> cls_result = cls_session.Run(cls_input);
                sw.Stop();
                long seconds = sw.ElapsedMilliseconds;
                sw.Reset();
                inf_time.Add(seconds);
                Thread.Sleep(2000);
```
But the problem still comes.
This is with sleep time=20ms:
![image](https://user-images.githubusercontent.com/32631344/148714790-83b64ff9-625a-40c8-82f2-ce9cfb646887.png)
This is with sleep time=500ms:
![image](https://user-images.githubusercontent.com/32631344/148714834-d80c230c-7399-40ae-a3fa-c02fe84ecdc1.png)
This is with sleep time=2000ms:
![image](https://user-images.githubusercontent.com/32631344/148714859-f8d54b96-0ed5-4710-a918-8c4b95b183f0.png)
I also get the problem with Python API on WIN10, but I did not get the problem on Ubuntu20.04. So this is related with OS?
Is there any solution?
https://github.com/microsoft/onnxruntime/issues/7449#issuecomment-1008499600

**Comment by skottmckay** [comment]
Does this happen if you're using just the CPU Execution Provider (i.e. don't register the CUDA provider and use the default InferenceSesssion)?

**Comment by feiyuhuahuo** [comment]
This does not happen on CPU and also does not happen on RTX3090. I can't locate where is the key factor now. Maybe RTX2080 with max-q design has a special power schedule? Since it's a laptop GPU.

**Comment by fdwr** [comment]
@feiyuhuahuo This is common behavior on laptops for GPU battery saving, to run in low power mode until enough frames have been submitted to increase performance. It occurs at the Nvidia graphics driver level, and I don't know that ORT can influence that :/. You don't see it on Ubuntu 20.04 because it uses a different graphics driver. You might find some settings in the Nvidia control panel for that, but unfortunately it requires the user to configure it before running your application. e.g. This option looks promising:

![image](https://user-images.githubusercontent.com/1809166/156086029-264b495c-38c9-414d-b77a-0012f9d5c43e.png)

**Comment by fdwr** [comment]
@feiyuhuahuo Thanks for the confirmation. Evidently the driver is applying https://en.wikipedia.org/wiki/Dynamic_frequency_scaling. I don't see any means of controlling via Direct3D besides one function `ID3D12Device::SetStablePowerState`, but it's only enabled for developer mode, not intended for release applications, and NVidia says not to call it in your main code (https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12device-setstablepowerstate). So the driver has the control.

**Comment by cqray1990** [comment]
> 

i use 456.71 the problem also exists,are you sure the driver version impact on this?
