### ISSUE TITLE
Cannot load ort model for onnxruntime-react-native

### ISSUE THREAD

**Issue by realphongha** [microsoft/onnxruntime#10253]
**Describe the bug**

I have a .onnx model file and successfully converted it to .ort format using:
```python -m onnxruntime.tools.convert_onnx_models_to_ort model.onnx```
When I tried to create inference session with InferenceSession.create("model.ort"), I got an error: 
```Error: Can't load a model: Can't create InferenceSession```, but it works perfectly fine with the example ort file from js/react_native/example/src/mnist.ort:
```Session: {"handler": {"inputNames": ["flatten_2_input"], "outputNames": ["Identity"]}}```

How to make it work?
Thanks!

**System information**
- OS Platform and Distribution: Android 10 
- ONNX Runtime installed from (source or binary): yarn add onnxruntime-react-native
- ONNX Runtime version: 1.8.1
- React Native version: 0.66.4

**Comment by hanbitmyths** [comment]
ONNX Runtime react native packages supports a limited set of operators in [here](https://onnxruntime.ai/docs/reference/operators/mobile_package_op_type_support_1.8.html). If all operators in your model are supported, can you share your onnx model to take a look?

**Comment by realphongha** [comment]
> ONNX Runtime react native packages supports a limited set of operators in [here](https://onnxruntime.ai/docs/reference/operators/mobile_package_op_type_support_1.8.html). If all operators in your model are supported, can you share your onnx model to take a look?

I think they are all supported. [Here ](https://drive.google.com/drive/folders/1kx8XxX-sj7SBVLMkJ0x49PcMpR9ExBHO?usp=sharing) is my onnx model (and the converted .ort file too).

**Comment by hanbitmyths** [comment]
It seems your model was exported using ONNX opset 11. ONNX Runtime react native leverages ONNX Runtime mobile runtime package which supports only opset 12 and 13 at 1.8.1. Check [here](https://onnxruntime.ai/docs/reference/operators/mobile_package_op_type_support_1.8.html)).

You can either export a model with opset 12/13 or you can convert onnx version using [this script](https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md#converting-version-of-an-onnx-model-within-default-domain-aionnx).

**Comment by realphongha** [comment]
It seems to work fine this time. Thank for your supporting.
