### ISSUE TITLE
much slower in GPU after quantization

### ISSUE THREAD

**Issue by Hap-Zhang** [microsoft/onnxruntime#10267]
Hi,all

I quantized a bert-base model to int8 by quantize_dynamic, the command listed as follows:
```
onnx_model_path = "model.onnx"
quantized_model_path = onnx_model_path + "-quantized"
quantize_dynamic(onnx_model_path, quantized_model_path)
```

The original model size:388M
The quantized model size:98M

The reference time in CPU reduced from 259ms to 204ms.However, it increased from 12ms to 232ms. It seems that the GPU（V100） is not successfully used in the background and fp16 is ok with same code. The inference command listed as follows:
```
#onnx_fp16_path = "model_fp16.onnx"
onnx_int8_path = "model.onnx-quantized"
opt_so = rt.SessionOptions()
opt_so.graph_optimization_level = rt.GraphOptimizationLevel.ORT_ENABLE_ALL
opt_session = rt.InferenceSession(onnx_int8_path, opt_so, ['CUDAExecutionProvider'])
inputs_onnx_op = {'input_ids': input_ids.cpu().numpy(), 'attention_mask': attention_mask.cpu().numpy(), 'token_type_ids': token_type_ids.cpu().numpy()}
opt_onnx_outputs = opt_session.run(None, inputs_onnx_op)
```

**Comment by Tian14267** [comment]
@Hap-Zhang 
Did you solve it ? I get similar problem with no quantization .  Inference time in GPU is similar in CPU.

**Comment by Hap-Zhang** [comment]
@Tian14267 
Yeah, me too. When use GPU , CPU usage rate  increase to 2000%, and the GPU is still used(can be found by nvidia-smi). I did not solve this problem now.

**Comment by yufenglee** [comment]
We don't have quantization support for CUDAExecutionProvider yet. Please try TensorRT EP for quantization of BERT model: https://github.com/microsoft/onnxruntime-inference-examples/tree/main/quantization/nlp/bert/trt.

BTW, tensor core starts supporting int8 from arch sm7.5. V100 is sm70. You need T4 or A100 to get benefits from quantization.

**Comment by Hap-Zhang** [comment]
OK, thanks for your kind reply. I will have a try.
