### ISSUE TITLE
C++ inference with IOBinding and DirectML

### ISSUE THREAD

**Issue by adepierre** [microsoft/onnxruntime#10279]
**Is your feature request related to a problem? Please describe.**
(I'm not sure this is a request, maybe I've juste missed something in the doc, I'm sorry if this is the case but I've looked everywhere and I can't get it to work)

I'm trying to perform an inference in C++ with both input and output already on the device (as an intermediary step in a process for example). I'm using DirectML as provider, and I've seen that creating DML memory is supported since 1.10, but I can't get the session to run properly.

**System information**
- ONNX Runtime version (you are using): 1.10 version (nuget in C++ project)

**Describe the solution you'd like**
I'd like the session to run normally and set the value passed as output to the output of the model, without copy to the CPU.

**Describe alternatives you've considered**
I've considered getting the data on the CPU and transfer them back to the device, but it adds an overhead.

**Additional context**
Here is the code I use with this [model.onnx](https://github.com/microsoft/onnxruntime/files/7864780/model.txt) (it's just a Pytorch 4x upsample exported with opset 11) for testing. Everything runs fine until the ``session.Run`` call, where the program just stops.

```cpp
#include <iostream>
#include <vector>
#include "onnxruntime_cxx_api.h"
#include "dml_provider_factory.h"

int main(int argc, char** argv) {

    const std::string model_s = "model.onnx";
    std::basic_string<ORTCHAR_T> model = std::basic_string<ORTCHAR_T>(model_s.begin(), model_s.end());
    
    // onnxruntime setup
    Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "batch-model-explorer");
    Ort::SessionOptions session_options;
    OrtSessionOptionsAppendExecutionProvider_DML(session_options, 0);
    Ort::Session session = Ort::Session(env, model.c_str(), session_options);

    Ort::IoBinding io_binding = Ort::IoBinding::IoBinding(session);
    Ort::MemoryInfo memory_info("DML", OrtAllocatorType::OrtDeviceAllocator, 0, OrtMemType::OrtMemTypeDefault);
    Ort::RunOptions run_options;

    // Create input tensor with 0 on device memory
    std::vector<int64_t> input_shape{ 1,3,1000,1000 };
    std::vector<float> input_tensor_values(1*3*1000*1000, 0.0f);
    Ort::Value input_tensor = Ort::Value::CreateTensor<float>(memory_info, input_tensor_values.data(), input_tensor_values.size(), input_shape.data(), 4);
    // bind the tensor to the input of the model
    io_binding.BindInput("input", input_tensor);

    // Create output tensor on device memory
    std::vector<int64_t> output_shape{ 1,3,4*1000,4*1000 };
    std::vector<float> output_tensor_values(1*3*4000*4000, 0.0f);
    Ort::Value output_tensor = Ort::Value::CreateTensor<float>(memory_info, output_tensor_values.data(), output_tensor_values.size(), output_shape.data(), 4);
    // bind the tensor to the output of the model
    io_binding.BindOutput("output", output_tensor);
    
    try {
        session.Run(run_options, io_binding);
    }
    catch (const Ort::Exception& exception)
    {
        std::cout << "ERROR running model inference: " << exception.what() << std::endl;
        return -1;
    }
    catch (const std::exception& exception)
    {
        std::cout << "ERROR running model inference: " << exception.what() << std::endl;
        return -1;
    }

    std::cout << "Done!" << std::endl;

    return 0;
}

```

Thanks for any help on this!

**Comment by pranavsharma** [comment]
@fdwr

**Comment by smk2007** [comment]
Hi,

The problem with the above snippet is that it is trying to use the "DML" memory info with a raw cpu buffer. You need to:

1) Create an appropriate ID3D12Resource. You can take a look here at how WinML does this: https://github.com/microsoft/onnxruntime/blob/775f862067b305f8dcba3ff1d65d47c15119c30d/winml/lib/Api/impl/TensorBase.h#L199
2) Get the DML EP extension APIs via GetExecutionProviderApi
3) Use the new CreateGPUAllocationFromD3DResource API to create a DML GPU Allocation using said resource.
4) Create a DML Memory Info Object.
5) Create an OrtValue using CreateTensorWithDataAsOrtValue, using the DML GPU Allocation and the DML Memory Info.

To see a more complete example of the code see this snippet being used by WinML to do the same.
https://github.com/microsoft/onnxruntime/blob/a757bd7186deb855634b70c1a583d18e98cfa9ca/winml/lib/Api.Ort/OnnxruntimeEngine.cpp#L625

This OrtValue can be used to avoid CPU copies.
NOTE: If you are trying to bind an output ID3D12Resource backed OrtValue you will run into this issue: https://github.com/microsoft/onnxruntime/issues/9962

Alternatively you can avoid writing this, and use WinML which exercises the same logic to support this scenario. See example here: https://github.com/microsoft/onnxruntime/blob/53c43e99498d792ecd3bea158e95a51e4db94ae0/winml/test/scenario/cppwinrt/scenariotestscppwinrt.cpp#L451

From your code snippet it seems like you intend to use CreateTensor to upload "output_tensor_values" to the GPU.
If you want to do this, you simply need to bind a CPU tensor while running with the DML Execution provider. The data will be moved to the appropriate context automatically.

**Comment by adepierre** [comment]
Oh I see, I thought the CreateTensor function used the memory_info to create the memory on the right device.  But it's just wrapping some pre-existing memory (FYI, I followed [this example](https://onnxruntime.ai/docs/performance/tune-performance.html#iobinding), but it's not complete so a bit hard to get exact information from).

> NOTE: If you are trying to bind an output ID3D12Resource backed OrtValue you will run into this issue: #9962

So at the moment there is basically no way to perform a GPU-only inference due to this other issue, correct?

> Alternatively you can avoid writing this, and use WinML which exercises the same logic to support this scenario. See example here:

Will check this out too, but it says ``pass a Tensor in as an input GPU``, but nothing about the output. 

> From your code snippet it seems like you intend to use CreateTensor to upload "output_tensor_values" to the GPU. If you want to do this, you simply need to bind a CPU tensor while running with the DML Execution provider. The data will be moved to the appropriate context automatically.

In fact, I was just trying to measure the raw inference time of my model only with DML the same way it would be used in production (= no in/out allocation or copy). I didn't really want to pass any data, I just thought the CreateTensor function would allocate memory and copy from CPU, so I had to provide some data.

I tried to measure the runtime with WinMLRunner or similar tools, but the timings are insanely high (tens of ms, while the same operation in CUDA takes only ~1-2ms). So my idea was that most of this time came from the data transfer and I wanted to measure without them.

Will definitely try the ID3D12Resource thing, at least for the input, and let you know if it works. Thanks for the help!

**Comment by fdwr** [comment]
@adepierre: @sumitsays is working on that bug right now. In the meantime, to unblock yourself (if you are able to build locally), you could try adding `Sync` and `RunEnd`:

> onnxruntime\core\providers\dml\DmlExecutionProvider\src\ExecutionProvider.h

```
    class ExecutionProvider : public onnxruntime::IExecutionProvider
    {
...
        onnxruntime::common::Status OnSessionInitializationEnd() override
        { 
            return m_impl->OnSessionInitializationEnd();
        }
---------->
        virtual onnxruntime::Status Sync() const final override
        {
            // Completely wait until the device has completed all preceding tasks.
            // The application could have called SynchronizeBoundOutputs().
            m_impl->WaitForOutstandingWork();
            return Status::OK();
        }

        virtual onnxruntime::Status OnRunEnd(bool /*sync_stream*/) final override
        {
            // Flush any pending work to the GPU, but don't block for completion, permitting it
            // to overlap other work.
            m_impl->Flush();
            return Status::OK();
        }
<----------
...
```

> onnxruntime\core\providers\dml\DmlExecutionProvider\src\ExecutionProvider.cpp

```
---------->
    void ExecutionProviderImpl::WaitForOutstandingWork() 
    {
        Flush();
        m_context->GetCurrentCompletionEvent().WaitForSignal();
    }
<----------
```

I also have a standalone sanity test app [here main.cpp](https://github.com/microsoft/onnxruntime/files/7917063/main.txt). It doesn't upload to/down from the GPU, just creating empty tensors with no specific data, but it might help. Interestingly `Run` has high overhead when called from ORT, even after session load and binding, but calling the same operator by itself in DirectML is ~2ms. It seems there is still overhead somewhere 🤔.

```
Beginning execution.
Finished execution.
d3dDeviceCreationTime ...   441.404800
sessionCreationTime .....   103.000300
tensorCreationTime ......    92.893400
bindingTime .............     0.020200
runTime .................    10.439200
synchronizeOutputsTime ..     0.002800
```

**Comment by adepierre** [comment]
@fdwr Thanks for the reply! I've been able to recompile the onnx runtime with your modifications. For completeness if anyone tries to do the same, I also had to add:

> onnxruntime\core\providers\dml\DmlExecutionProvider\src\ExecutionProvider.cpp
```cpp
---------->
    void WaitForOutstandingWork();
<----------
```

Regarding your code snippet, I get similar times you do, with an extra overhead compared to raw operation unfortunately :/

Maybe I should try to directly call the operations of my net in DirectML for best efficiency.

**Comment by fdwr** [comment]
@adepierre Do you time only the first iteration of Upsample? 🤔 It would be interesting to call .Run() a few times, to see if the 2nd/3rd runs are faster.

Btw, https://github.com/microsoft/onnxruntime/pull/10362.

**Comment by adepierre** [comment]
> @adepierre Do you time only the first iteration of Upsample? 🤔 It would be interesting to call .Run() a few times, to see if the 2nd/3rd runs are faster.

You were right about that @fdwr. I looped the inference part of your example main.cpp. Inference time is divided by 10 for the second iteration, and again by 2 from the third one. The raw timings results are below, but it's basically even faster than the 2ms you had with directML. Is this even possible? Could the measured time be biased in a way?

Anyway, this might be beyond the point of the original issue. I tried to time my inference and now I can do it properly so feel free to close this. And thanks again for your help!


```shell
d3dDeviceCreationTime ...   322.800000
sessionCreationTime .....    58.710000
tensorCreationTime ......    59.209000
bindingTime .............     0.035000
runTime .................    10.618000
synchronizeOutputsTime ..     4.174000


tensorCreationTime ......    53.268000
bindingTime .............     0.011000
runTime .................     1.128000
synchronizeOutputsTime ..     4.196000


tensorCreationTime ......    68.596000
bindingTime .............     0.017000
runTime .................     0.412000
synchronizeOutputsTime ..     5.067000


tensorCreationTime ......    82.570000
bindingTime .............     0.019000
runTime .................     0.390000
synchronizeOutputsTime ..     5.129000


tensorCreationTime ......    76.321000
bindingTime .............     0.018000
runTime .................     0.419000
synchronizeOutputsTime ..     5.042000


tensorCreationTime ......    98.152000
bindingTime .............     0.021000
runTime .................     0.484000
synchronizeOutputsTime ..     5.165000


tensorCreationTime ......    80.610000
bindingTime .............     0.020000
runTime .................     0.450000
synchronizeOutputsTime ..     5.084000


tensorCreationTime ......    71.752000
bindingTime .............     0.018000
runTime .................     0.423000
synchronizeOutputsTime ..     5.372000


tensorCreationTime ......    87.846000
bindingTime .............     0.017000
runTime .................     0.435000
synchronizeOutputsTime ..     5.111000


tensorCreationTime ......   114.686000
bindingTime .............     0.019000
runTime .................     0.452000
synchronizeOutputsTime ..     5.163000
```

**Comment by fdwr** [comment]
@adepierre Glad to hear, and welcome. I'm curious what the first-run overhead is 🤔 (would take some time to figure out...), maybe additional delayed allocations in the graph on CPU side, because the GPU work *should* be done by OnSessionInitializationEnd. There are other potential confounding factors too, such as certain GPU's switching from a low power mode to a higher power mode (that's why my teammate recommends ignoring 50-100ms on some laptops).

Note a realistic GPU-to-GPU case (e.g. video frame input) would only create the tensors once rather than recreate them each frame, wouldn't rebind, and it wouldn't necessarily wait to synchronize the outputs either (such that things could be pipelined onto another step). Cheers.

**Comment by wojtuss** [comment]
@adepierre , Could you please share your final version of your app code? I struggle to do exactly the same as you did: to run an onnx model on GPU using onnxruntime with DirectML. Still to no avail.

**Comment by adepierre** [comment]
> Could you please share your final version of your app code?

I used the code provided above ([here](https://github.com/microsoft/onnxruntime/issues/10279#issuecomment-1018928665)). It worked great with the fix mentionned in this issue, I've been able to measure the exact inference time of my network.

**Comment by wojtuss** [comment]
@adepierre , Thank you for your prompt response.
I am not familiar with GPU programming. The above instructions seems clear to me except for creating the D3D12 Resource. How did you do that? The WinML method uses `winmlp::LearningModelSession` to get the device. The Ort::Session does not provide this functionality.

**Comment by adepierre** [comment]
> The above instructions seems clear to me except for creating the D3D12 Resource. How did you do that?

The ressources are created in the ``CreateTensorValueUsingD3DResource`` function (at line 327 in the provided file). The device is obtained at line 95 with ``D3D12CreateDevice(nullptr, D3D_FEATURE_LEVEL_11_0, IID_PPV_ARGS(&d3d12Device))``

**Comment by wojtuss** [comment]
@adepierre, Right, I missed that file.
Thank you very much for your help!

**Comment by JiaPai12138** [comment]
Is there any to use python inference with IOBinding and DirectML?
