### ISSUE TITLE
error: ‘Ort::g_api’ should have been declared inside ‘Ort’ while compiling with g++

### ISSUE THREAD

**Issue by abilashravi-ta** [microsoft/onnxruntime#10295]
**Description**
I built **onnxruntime** from source following [these](https://onnxruntime.ai/docs/build/inferencing.html#cpu) instructions.
Getting `error: ‘Ort::g_api’ should have been declared inside ‘Ort’` when trying to _include_ **onnxruntime_cxx_api.h** in a simple `hello_world.cpp` code.

**System information**
- OS Platform and Distribution: **WSL 2.0** _Ubuntu 20.04.3 LTS on Windows 10 x86_64_
- ONNX Runtime installed from (source or binary): source (using the link mentioned above)
- G++ Compiler version: 9.3.0

**To Reproduce**
When I compile the following piece of code with `g++ -o run1 imp_onnx.cpp -I/home/abilashravi/trials/onnx_in_c/onnxruntime/include/onnxruntime/core/session`
```
// imp_onnx.cpp
#include <iostream>
#include <onnxruntime_cxx_api.h>

int main()
{
	std::cout << "Hello world.!";
	return 0;
}
```
I get this
![g++ er1](https://user-images.githubusercontent.com/53215532/149608263-b2b064ff-e5eb-485e-b69c-30644c2d3cfc.JPG)

I tried to fix it based on discussions [here](https://github.com/microsoft/onnxruntime/issues/2081) by adding `const OrtApi* Ort::g_api = OrtGetApi(ORT_API_VERSION);` to the code. But when I compile the following
```
// imp_onnx.cpp
#include <iostream>
#include <onnxruntime_cxx_api.h>

const OrtApi* Ort::g_api = OrtGetApi(ORT_API_VERSION);

int main()
{
	std::cout << "Hello world.!";
	return 0;
}
```
I'm getting this
![g++ er2](https://user-images.githubusercontent.com/53215532/149608545-e3ce26f8-6ec6-456f-8ad3-3510c3d84303.JPG)

Any suggestion would be helpful.!

**Comment by edgchen1** [comment]
> **To Reproduce** When I compile the following piece of code with `g++ -o run1 imp_onnx.cpp -I/home/abilashravi/trials/onnx_in_c/onnxruntime/include/onnxruntime/core/session`
> 
> ```
> // imp_onnx.cpp
> #include <iostream>
> #include <onnxruntime_cxx_api.h>
> 
> int main()
> {
> 	std::cout << "Hello world.!";
> 	return 0;
> }
> ```
> 
> I get this ![g++ er1](https://user-images.githubusercontent.com/53215532/149608263-b2b064ff-e5eb-485e-b69c-30644c2d3cfc.JPG)

It looks like you need to link to the onnxruntime library too, from the "undefined reference" in the error message.
See here for details: https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html (`-l`)

**Comment by abilashravi-ta** [comment]
> > **To Reproduce** When I compile the following piece of code with `g++ -o run1 imp_onnx.cpp -I/home/abilashravi/trials/onnx_in_c/onnxruntime/include/onnxruntime/core/session`
> > ```
> > // imp_onnx.cpp
> > #include <iostream>
> > #include <onnxruntime_cxx_api.h>
> > 
> > int main()
> > {
> > 	std::cout << "Hello world.!";
> > 	return 0;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I get this ![g++ er1](https://user-images.githubusercontent.com/53215532/149608263-b2b064ff-e5eb-485e-b69c-30644c2d3cfc.JPG)
> 
> It looks like you need to link to the onnxruntime library too, from the "undefined reference" in the error message. See here for details: https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html (`-l`)

I compiled with `g++ -o run1 imp_onnx.cpp -I/home/abilashravi/trials/onnx_in_c/onnxruntime/include/onnxruntime/core/session -L/usr/local/lib -l onnxruntime` command and the **run1** _executable file_ got generated.
But when I try to _run_ it using `./run1` command, I get the following error
`./run1: error while loading shared libraries: libonnxruntime.so.1.8.2: cannot open shared object file: No such file or directory`

**Comment by abilashravi-ta** [comment]
> Looks like you need to specify where to find the library at runtime. Setting LD_LIBRARY_PATH is one option. Or put the library in a known location. Found some info here: https://stackoverflow.com/a/21173918

Thanks @edgchen1. I ran this `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/` and the compiled the code with 
`g++ -o run1 imp_onnx.cpp -I/home/abilashravi/trials/onnx_in_c/onnxruntime/include/onnxruntime/core/session -L/usr/local/lib -l onnxruntime` command. I'm able to run the _executable_ file without any error.!
