### ISSUE TITLE
Cannot find OrtCUDAProviderOptionsV2 APIs in released onnxruntime_c_api.h

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/onnxruntime#10298]
Hello,

I'm using `onnxruntime-win-x64-gpu-1.10.0.zip` from release page and I found there is no OrtCUDAProviderOptionsV2 APIs in `include/onnxruntime_c_api.h`

This api can be found in onnxruntime's doc page: https://onnxruntime.ai/docs/api/c/group___global.html#ga6b319b3ba435fb46c3808d7957c4684f

Do I miss something?

**Comment by edgchen1** [comment]
OrtCUDAProviderOptionsV2 was added in #10188 after 1.10. It should be available in the next release.

**Comment by pranavsharma** [comment]
These APIs were added after 1.10 release. But unfortunately our docs are not versioned.

**Comment by HaoboGu** [comment]
Okay, is there a plan about when will the next version be released?

**Comment by edgchen1** [comment]
@faxu when is the ORT 1.11 release?

**Comment by faxu** [comment]
The ORT 1.11 release is planned for late March. We do have nightly packages here though if needed: https://aiinfra.visualstudio.com/PublicPackages/_packaging?_a=feed&feed=ORT-Nightly

**Comment by HaoboGu** [comment]
Thanks guys
