### ISSUE TITLE
bug: ONNX Runtime error: node->GetOutputEdgesCount() == 0 was false. Can't remove node

### ISSUE THREAD

**Issue by mattans** [microsoft/onnxruntime#10305]
**Describe the bug**

I have a simple Keras RNN model, composed by embedding, LSTM, and linear layers. The model works well in Keras when dumped and loaded. I converted the loaded model to ONNX opset 15 using `tf2onnx.convert.from_keras`, but I get this error when I init the `InferenceSession` object:

`onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\graph\graph.cc:3275 onnxruntime::Graph::RemoveNode node->GetOutputEdgesCount() == 0 was false. Can't remove node sequential/lstm_7/transpose as it still has output edges.`

This is the relevant node in Netron: https://i.stack.imgur.com/cBKqy.png

Indeed it has output edges...

Is this some kind of optimization that I can turn off in with `disabled_optimizers=...`? (this argument is not documented unfortunately)

Thank you.

**Urgency**
two weeks project

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11
- ONNX Runtime installed from (source or binary): from pip
- ONNX Runtime version: 1.10.0
- Python version: 3.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: no

**To Reproduce**
Cannot attach ONNX file without hiding params

**Comment by skottmckay** [comment]
https://onnxruntime.ai/docs/performance/graph-optimizations.html has details. Most likely this is an issue with the transpose optimizer which runs in the 'basic' level, so you'd need to use ORT_DISABLE_ALL. 

Would be great if we could take a look at the model somehow to find out what's breaking. If an optimization is removing a node it first needs to remove the output edges. In this case that hasn't happened, leading to the exception.

**Comment by wangyems** [comment]
Have seen a similar issue from an internal model. The pattern is "->Transpose->Transose->(output_edge)" where the output_edge is consumed implicitly by a different-level graph. 
Looks like here https://github.com/microsoft/onnxruntime/blob/c12cafa524f254dc2ed1c80b22fa1821239fa137/onnxruntime/core/optimizer/transpose_optimizer/api_impl.cc#L432 the consumer nodes of that output are not correctly returned as map defined in https://github.com/microsoft/onnxruntime/blob/c12cafa524f254dc2ed1c80b22fa1821239fa137/include/onnxruntime/core/graph/graph.h#L1518 is not initialized using the whole graph during the transpose optimization.

**Comment by skottmckay** [comment]
`graph_` in the transpose optimizer is != to the ORT Graph instance. It's a wrapper API so that the transpose optimizer can be plugged into other places (e.g. converters or a standalone tool to change the layout of a model). It's designed to support running on a subgraph - e.g. the NNAPI EP identifies a set of nodes if can run and we want to change the layout of those to NHWC.  

`consumers->comprehensive = false;` should be set if implicit inputs are involved, and a node providing the implicit input should not be removed. It's possible there's a bug where that restriction is not correctly enforced. A model that fails would be helpful to identify if that is the case.
