### ISSUE TITLE
Crash on IOBinding synchronize_inputs()

### ISSUE THREAD

**Issue by jeshels** [microsoft/onnxruntime#10300]
**Describe the bug**
Python program crash with exit code 139 (SIGSEGV Segmentation fault (core dumped)) when invoking `IOBinding.synchronize_inputs()`.

**Urgency**
None.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source installation. Built with `--use_cuda --cudnn_home /usr --cuda_home /usr/local/cuda --build_wheel --enable_pybind --config RelWithDebInfo --build_shared_lib --parallel`
- ONNX Runtime version: 1.10.0
- Python version: 3.9.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: CUDA version 10.1.105 / cuDNN version 8.0.5
- GPU model and memory: Quadro RTX 4000

**To Reproduce**
I can reproduce with this minimal example:

```python
import onnxruntime as ort

model = ort.InferenceSession(PATH, providers=['CUDAExecutionProvider'])
io = model.io_binding()
io.synchronize_inputs() # CRASH - exit code 139 - Segmentation fault
```

I get the same behavior when using `bind_input()` and `bind_output()` prior to invoking `synchronize_inputs()`.

**Expected behavior**
I expect the method to work without crashing the program, and to yield an informative error message in case of misuse.

**Additional context**
I cannot provide the model, but I can execute it successfully with `session.run()` and `IOBinding` (as far as I don't invoke `synchronize_inputs()`). I didn't check whether `synchronize_outputs()` cause a crash as well.

**Update:** I am able to reproduce the segmentation fault with this [CenterFace](https://github.com/Star-Clouds/CenterFace) ONNX model (I downloaded [this](https://github.com/Star-Clouds/CenterFace/blob/master/models/onnx/centerface.onnx) file). Moreover, it seems to be related to the model, since there is not segmentation fault when using the minimal example code with [Tiny YOLOv2](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny-yolov2) ONNX model. I deliberately chose detection models since I am facing this with a detection model.

**Comment by yuslepukhin** [comment]
We would need more information to see what's wrong. However, `synchronize_inputs()` are optional and is usually needed to ensure that the data in your GPU buffer finished copying to the device.

**Comment by edgchen1** [comment]
I was unable to reproduce the segmentation fault with the minimal example code. Likely it depends on the model. Are you able to reproduce it with a different model that you can share?

**Comment by jeshels** [comment]
@edgchen1, You are correct! It seems to depend on the model (also updated my initial message with the details).

I am able to reproduce the segmentation fault with this [CenterFace](https://github.com/Star-Clouds/CenterFace) ONNX model (I downloaded [this](https://github.com/Star-Clouds/CenterFace/blob/master/models/onnx/centerface.onnx) file). In contrast, with [Tiny YOLOv2](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny-yolov2) ONNX model, there is no segmentation fault.

I deliberately chose detection models since I am facing this with a detection model.

Is there any more information I can provide which will be useful?

Hi @yuslepukhin, I couldn't find documentation on `synchronize_inputs()`. How can one tell if `synchronize_inputs()` should be used? (I asked you the same question in another issue. Feel free to answer in a single place and I'll update my other message to avoid duplication).

**Comment by yuslepukhin** [comment]
`synchronize_inputs/outputs` has been recently exposed so it may not have made to the generated published documentation. [Here ](https://github.com/microsoft/onnxruntime/blob/master/csharp/src/Microsoft.ML.OnnxRuntime/OrtIoBinding.shared.cs#L91)how it is worded in C# code

The functionality of it is device specific. For CUDA GPU it means a call to `cudaSynchronize()`. You use it to ensure that the content of the memory you are binding as inputs finished copying the device before inference. And for outputs, you want all of the CUDA operations to finish before reading the bound outputs. If you see that you are getting wrong or inconsistent results, you may try calling it.

[Here ](https://pytorch.org/docs/stable/generated/torch.cuda.synchronize.html)is how Pytorch docs put it.

**Comment by edgchen1** [comment]
Thanks for the link to the CenterFace model, I am able to reproduce the segmentation fault with it.
onnxruntime-gpu 1.10 python package on Ubuntu 20.04
Will investigate.
