### ISSUE TITLE
rationalize documentation on ORT-Windows integration

### ISSUE THREAD

**Issue by garymm** [microsoft/onnxruntime#10324]
Currently there's some documentation of how ORT is integrated into Windows on the [DirectML EP page](https://onnxruntime.ai/docs/execution-providers/DirectML-ExecutionProvider.html) and some on the [High Level Design page](https://onnxruntime.ai/docs/reference/high-level-design.html).

There are a lot of details on the High Level Design page that don't really seem like they're about the high level design (e.g. distribution choices table).

It seems to me that it might be best to move the content from High Level Design to a dedicated page about how to use ONNX Runtime on Windows (possibly taking some content from the DirectML EP page).

**Comment by natke** [comment]
Thanks for pointing this out @garymm! Do you have a customer usage scenario for these changes? i,e. did you figure this out because you were trying to answer a specific question? Any more detail would be appreciated as we try and improve this

**Comment by garymm** [comment]
No. I was reading the High Level Design page for my own education and I found the existing organization confusing.

**Comment by snnn** [comment]
I hope someone can help me review this: https://github.com/microsoft/onnxruntime/pull/11304

**Comment by garymm** [comment]
Fixed by https://github.com/microsoft/onnxruntime/pull/12096/
