### ISSUE TITLE
quantize/__init__.py, line 97 | SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Available input ports:")?

### ISSUE THREAD

**Issue by danielbellhv** [microsoft/onnxruntime#10344]
Quantization bug occurs when running both code snippets in [ONNXRuntime README](https://github.com/microsoft/onnxruntime/blob/fe0b2b2abd494b7ff14c00c0f2c51e0ccf2a3094/onnxruntime/python/tools/quantization/README.md).

[Example - Quantize an ONNX Model](https://github.com/microsoft/onnxruntime/blob/fe0b2b2abd494b7ff14c00c0f2c51e0ccf2a3094/onnxruntime/python/tools/quantization/README.md#example---quantize-an-onnx-model):
```python
import onnx
from quantize import quantize, QuantizationMode

# Load the onnx model
model = onnx.load('path/to/the/model.onnx')
# Quantize
quantized_model = quantize(model, quantization_mode=QuantizationMode.IntegerOps)
# Save the quantized model
onnx.save(quantized_model, 'path/to/the/quantized_model.onnx')
```

[End-to-end example](https://github.com/microsoft/onnxruntime/blob/fe0b2b2abd494b7ff14c00c0f2c51e0ccf2a3094/onnxruntime/python/tools/quantization/README.md#end-to-end-example):
```python
import onnx
from quantize import quantize, QuantizationMode
model = onnx.load('albert.opt.onnx')
quantized_model = quantize(model, quantization_mode=QuantizationMode.IntegerOps, force_fusions=True)
onnx.save(quantized_model, 'albert.opt.quant.onnx')
```

Both get the same Traceback:
```
Traceback (most recent call last):

  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-36-95f122b772e5>", line 2, in <module>
    from quantize import quantize, QuantizationMode

  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/quantize/__init__.py", line 97
    print "Available input ports:"
                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Available input ports:")?
```

**Comment by yufenglee** [comment]
It's a little bit out of data. Please change:
`from quantize import quantize, QuantizationMode` to
`import onnxruntime
from onnxruntime.quantization import quantize, QuantizationMode`

**Comment by danielbellhv** [comment]
I tried out an alternative quantisation package, which I have since removed code for. @yufenglee Would you be so kind as to help out in this [post](https://github.com/microsoft/onnxruntime/issues/10342)?
