### ISSUE TITLE
Converting PyTorch to ONNX model changes file size for Albert but not BERT

### ISSUE THREAD

**Issue by danielbellhv** [microsoft/onnxruntime#10340]
**Performance** Issue.

Based on [SO post](https://stackoverflow.com/q/70786010/17840900).

Goal: Use this [Notebook][1] to perform quantisation on **albert-base-v2** model.

Kernel: `conda_pytorch_p36`.

---

Outputs in **Sections 1.2 & 2.2** show that:
- converting vanilla **BERT** from **PyTorch to ONNX** stays the **same size**, `417.6 MB`.
- **Quantization models are smaller** than vanilla BERT, PyTorch `173.0 MB` and ONNX `104.8 MB`.

However, when running Albert:
- PyTorch and ONNX model **sizes are different**.
- Quantized model sizes are **bigger** than vanilla.

I *think* this is the reason for **poorer model performance of both Quantization** methods of Albert, compared to vanilla Albert.

PyTorch:
```
Size (MB): 44.58906650543213
Size (MB): 22.373255729675293
```

ONNX:
```
ONNX full precision model size (MB): 341.64233207702637
ONNX quantized model size (MB): 85.53886985778809
```

---

**Why might exporting **Albert** from PyTorch to ONNX increase model size, but not for BERT?**

Please let me know if there's anything else I can add to post.

  [1]: https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/notebooks/bert/Bert-GLUE_OnnxRuntime_quantization.ipynb

**Comment by tianleiwu** [comment]
@danielbellhv, ALBert has shared weights. Could you take a look whether those weights no longer become different after quantization? If so, you might try to share quantized weight in some way.
