### ISSUE TITLE
Optional outputs of the Loop Node crash the InferenceSession

### ISSUE THREAD

**Issue by alexeykarnachev** [microsoft/onnxruntime#10361]
**Describe the bug**
Python API of InferenceSession crashes silently on inference (but I assume, there is something inside c++ core). It happens when I use Loop Node inside my ONNX model and it has optional outputs. I've marked all Loop carry dependencies as empty strings and in such case inference just crashes silently. When I set appropriate names for the Loop carry dependencies, the inference goes fine. 

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 20.04
- ONNX Runtime installed from (source or binary): via `pip install onnxruntime-gpu`
- ONNX Runtime version: 1.10.0
- Python version: 3.8.12
- CUDA/cuDNN version: 11.5
- GPU model and memory: RTX 3090, 24245MiB

**To Reproduce**
To reproduce the behavior use the following inference code:
```python
import numpy as np
from onnxruntime import InferenceSession

def _get_pasts_input_feed(session, batch_size):
    pasts_shape = session.get_inputs()[-1].shape[:]
    pasts_shape[0] = batch_size
    pasts_shape[2] = 0

    pasts_input_feed = {}
    for inp in session.get_inputs():
        if inp.name.startswith('input_past_key_values_'):
            pasts_input_feed[inp.name] = np.zeros(pasts_shape, dtype=np.float16)

    return pasts_input_feed

model_file_path = 'loop_toy.onnx'  # or 'loop_toy_optional.onnx'. See models.tar.gz archive.
session = InferenceSession(model_file_path, providers=['CUDAExecutionProvider'])
batch_size = 16
n_steps = 30
prefix_ids = np.random.randint(0, 10, (batch_size, 20))
pasts_input_feed = _get_pasts_input_feed(session=session, batch_size=prefix_ids.shape[0])
input_feed = {
    'n_steps': np.array([n_steps], dtype=np.int64),
    'input_ids': prefix_ids,
    'temperature': np.array(0.7, dtype=np.float64),
    'top_k': np.array(50, dtype=np.int64),
    **pasts_input_feed
}

outputs = session.run(['all_output_ids'], input_feed)
output_ids = outputs[0].T

assert output_ids.shape == (batch_size, n_steps)
print('SUCCESS!')
```
Models: [models.tar.gz](https://github.com/microsoft/onnxruntime/files/7919071/models.tar.gz) 
There are two models: `loop_toy.onnx` and `loop_toy_optional.onnx`. Inference of the second one fails. `SUCCESS!` print is not reached.

**Expected behavior**
It's expected that the inference with the model with optional loop carry dependencies will not fail and not-ignored output will be returned.

**Additional context**
The goal I want to achieve here is to avoid unnecessary copies of the loop graph outputs from the last step. I need only scan outputs and another ones just consumes memory. If I understood the details of the Loop Node implementation, it is possible to achieve this by not returning unnecessary tensors from the loop (and I even don't use them in the downstream graph).

**Comment by skottmckay** [comment]
A loop carried dependency needs to be carried between each iteration so cannot become optional during subgraph execution. The ONNX checker should probably fail the model if it doesn't already. 

If you just want to consume a value, refer to the original name in the outer scope instead of passing it in as a loop carried dependency. See the description and example usage of the outer scope 'a' value in https://github.com/onnx/onnx/blob/main/docs/Operators.md#loop

**Comment by alexeykarnachev** [comment]
I have a graph (body of Loop Node) which returns valid outputs, they are not marked as empty strings.
The only thing I've tried to make an empty is an output of the Loop Node itself.

And you are right, there is no any information in the docs/Operators, that these Loop Node output values could be optional.
But at least, they say that the `cond` could be an optional:
```
cond (optional) : B
A boolean termination condition. Optional. Pass empty string to skip.
```

And if I try to pass an empty string here, I face with the same behavior: InferenceSession just falls silently on initialization.
I attach graph with an optional `cond` and you can run it with the code above.

[loop_optional_cond.onnx.tar.gz](https://github.com/microsoft/onnxruntime/files/7931110/loop_optional_cond.onnx.tar.gz)

**Comment by skottmckay** [comment]
Cond is optional as we can default its value to False when running the subgraph. 

I don't believe it's possible to avoid creating the Loop outputs as the spec doesn't allow for them to be optional. As such I don't think your model is valid according to the ONNX spec. If you would like to request an update to the spec please do so via https://github.com/onnx/onnx/issues.

**Comment by alexeykarnachev** [comment]
I got the point with output carried dependency. 
But now I want to understand if is this true, that I can `Pass empty string to skip.` for `cond`? The spec says that yes, I can do it.
And I did it in my last attached model. The inference fails.

Is there something I'm missing? Or it's just inaccuracy in spec and I should explicitly pass `False` instead of empty string? And why there are no any warnings or errors from the onnxruntime (just silent shut down)

**Comment by skottmckay** [comment]
Using an empty string for 'cond' or 'M' should be valid. The Loop implementation handled it, however the type/shape inferencing didn't allow for it, leading to a null reference. Somewhat amazing that in multiple years and many models using Loop that none have ever treated 'cond' or 'M' as optional!

**Comment by alexeykarnachev** [comment]
Okay, now it's all clear for me.
I'll make the spec update request to allow optional Loop Node carried outputs.
We can close this one.

Thank you!
