### ISSUE TITLE
ThreadPool unit test fails when compiling ONNXRuntime on Hybrid Core platform

### ISSUE THREAD

**Issue by aparnagollapudi** [microsoft/onnxruntime#10369]
Describe the bug
When building ONNXRuntime on Hybrid core windows platform, the "`ThreadPoolTest.TestConcurrentParallelFor_4Thread_4Conc_8Tasks_dynamic_block_base_1`" unit test consistently fails with error "`RunInParallel n<= num_threads_ + 1 was false.`" 

System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: build from source , commit : d2b14249683d3e25994c2209027dbf5df9d98c16
- Python version: 3.9.7
- Visual Studio version (if applicable): Visual Studio 16.11.9
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

To Reproduce
build the code: `.\build.bat --config RelWithDebInfo --parallel --build_shared_lib --cmake_generator "Visual Studio 16 2019"`
run the unit tests in quesiton
`.\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime_test_all.exe --test_filter=ThreadPoolTest.TestConcurrentParallelFor_4Thread_4Conc_8Tasks_dynamic_block_base_1`

Expected behavior
The test should run and pass without failure.

Additional context
Issue might be related to [8495](https://github.com/microsoft/onnxruntime/pull/8495)

**Comment by snnn** [comment]
Let me try it. You mean, Intel Gen 12 CPUs?

**Comment by aparnagollapudi** [comment]
Yes, it is Intel Gen 12 CPU with a Hybrid core architecture.

**Comment by snnn** [comment]
Yes I can reproduce it.

**Comment by RandySheriffH** [comment]
@aparnagollapudi, @snnn, mind trying out the fix on your hybrid?

**Comment by aparnagollapudi** [comment]
Thank you, will test out the changes.

**Comment by aparnagollapudi** [comment]
It works now. Thank you

**Comment by snnn** [comment]
I found it still always crashes at ThreadPoolTest.TestConcurrentParallelFor_4Thread_4Conc_8Tasks_dynamic_block_base_1
