### ISSUE TITLE
Add CoreML EP to macOS builds so that Apple Silicon Macs can benefit from CoreML execution cores in the SOC

### ISSUE THREAD

**Issue by diddledani** [microsoft/onnxruntime#10367]
**Is your feature request related to a problem? Please describe.**
Currently, if I'm reading the documentation and CI config right, macOS builds do not include the CoreML EP by default. This means that Macs with Apple Silicon chips cannot use their CoreML cores to accelerate inference.

**System information**
- ONNX Runtime version (you are using): 1.10.0

**Describe the solution you'd like**
Add CoreML EP to default package generation for macOS builds.

**Describe alternatives you've considered**
Building a .NET application with a custom compilation of ONNX Runtime. I don't believe the nuget packages can utilise a custom compiled runtime easily.

**Comment by skottmckay** [comment]
Will be included in next release
