### ISSUE TITLE
"Type Error: Type parameter (T) of Optype (MatMul) bound to different types (tensor(int32) and tensor(int64) in node (MatMul_627)"

### ISSUE THREAD

**Issue by mszuyx** [microsoft/onnxruntime#10372]
**Describe the bug**

I am trying to convert a pytorch model to ONNX for a real-time application. Besides the Type Error "_Type parameter (T) of Optype (MatMul) bound to different types (tensor(int32) and tensor(int64) in node (MatMul_627)_", I also encounter "_WARNING: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function._"

**I wonder if there is a simple fix I can do to the pytorch model itself to make it easier for ONNX conversion.**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- ONNX Runtime version: 1.10.0
- Python version: 3.8
- Visual Studio version (if applicable): 1.63.2
- CUDA/cuDNN version: 11.3
- GPU model and memory: NVIDIA 3060

```
import numpy as np
import torch.onnx
import onnxruntime
print(onnxruntime.__version__)

model_path_ = '/home/ros/OS_TR/log/tcd_alot_dtd_lmt_OSnet_mb_large_ver2_weighted_bce_LR_0.001/snapshot-epoch_2022_01_06_19_03_30_texture.pth'

model_name_ = 'ostr_mb3_large_ver2'

from utils.model import models
model = models['OSnet_mb_large_ver2']()
model.load_state_dict(torch.load(model_path_))
model.eval()
if torch.cuda.is_available():
    print('pytorch using CUDA version: ',torch.version.cuda)
    model = model.cuda()

# Input to the model
x1 = torch.randn(1, 3, 256, 256, requires_grad=True).float()
x2 = torch.randn(1, 3, 256, 256, requires_grad=True).float()
if torch.cuda.is_available():
    x1 = x1.cuda()
    x2 = x2.cuda()

torch_out = model(x1,x2)

# Export the model
torch.onnx.export(model,                     # model being run
                  (x1,x2),                         # model input (or a tuple for multiple inputs)
                  model_name_ + ".onnx",   # where to save the model (can be a file or file-like object)
                  export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=14,          # the ONNX version to export the model to
                #   do_constant_folding=True,  # whether to execute constant folding for optimization
                  input_names = ['input1','input2'],   # the model's input names
                  output_names = ['output'], # the model's output names
                #   dynamic_axes={'input' : {0 : 'batch_size'},    # variable length axes
                #                 'output' : {0 : 'batch_size'}}
                )

onnx_model = onnxruntime.InferenceSession(model_name_ + ".onnx")

def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

# compute ONNX Runtime output prediction
onnx_inputs = {onnx_model.get_inputs()[0].name: to_numpy(x1), onnx_model.get_inputs()[0].name:to_numpy(x2)}
onnx_outs = onnx_model.run(None, onnx_inputs)

# compare ONNX Runtime and PyTorch results
np.testing.assert_allclose(to_numpy(torch_out), onnx_outs[0], rtol=1e-03, atol=1e-05)

print("Exported model has been tested with ONNXRuntime, and the result looks good!")
```

**Comment by garymm** [comment]
I think this code is wrong:
`onnx_inputs = {onnx_model.get_inputs()[0].name: to_numpy(x1), onnx_model.get_inputs()[0].name:to_numpy(x2)}`

Should be:
`onnx_inputs = {onnx_model.get_inputs()[0].name: to_numpy(x1), onnx_model.get_inputs()[1].name:to_numpy(x2)}`

Does that fix the error you're seeing?

If not, please try exporting with the latest PyTorch nightly version.

If that doesn't work, please open an issue in github.com/pytorch/pytorch.
However we won't be able to help you unless you can provide the model so we can reproduce the issue.
