### ISSUE TITLE
Update examples in documentation

### ISSUE THREAD

**Issue by xadupre** [microsoft/onnxruntime#1037]
**Describe the bug**
One python example raises the following exception:

ImportError: cannot import name 'convert_keras' from 'onnxmltools'

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): all
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: git
- Python version: 3.7

**Comment by faxu** [comment]
@xadupre which example? Can you help fix this?

**Comment by xadupre** [comment]
Fixes with #1151.
