### ISSUE TITLE
installation via pip fails on python 3.10.2

### ISSUE THREAD

**Issue by xfnw** [microsoft/onnxruntime#10389]
**Describe the bug**
attempting to install via pip results in
```
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime
```

attempting to install manually via the wheel file from pypi results in
```
ERROR: onnxruntime-1.10.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl is not a supported wheel on this platform.
```

**System information**
- Arch Linux 5.16.2-arch1-1 x86_64
- Python 3.10.2

**Comment by YUNQIUGUO** [comment]
Hi, wheel on python 3.10 might not be supported with onnxruntime yet. There has been a discussion on that already. #9782 

Hopefully it will get supported soon.
