### ISSUE TITLE
MLAS Library Documentation

### ISSUE THREAD

**Issue by Darshcg** [microsoft/onnxruntime#10388]
Hi ONNXRT team,

Do I get the MLAS Library official Documentation?

Thanks and Regards,
Darshan

**Comment by snnn** [comment]
Sorry there isn't any. All we have is public, in this repo.

**Comment by Darshcg** [comment]
Hi @snnn,

Thanks for your reply.

May I now how the Conv kernel(MLAS) is being called on CPU? When I inspect on i7-9th gen the ConvnchwcFMA3 and ConvnchwFMA3 kernels are being called. But I want to understand how there is a link between CPP code to Assembly code.
For example: https://github.com/microsoft/onnxruntime/blob/d2b14249683d3e25994c2209027dbf5df9d98c16/onnxruntime/core/mlas/lib/snchwc.cpp#L724 here the Conv kernel is called, but how this call is linked to Assembly code?

Looking forward to your reply.

Thanks,
Darshan

**Comment by yufenglee** [comment]
@Darshcg , the assembly code are mainly dynamically bound/linked by the [MLAS_PLATFORM](https://github.com/microsoft/onnxruntime/blob/df16c605e8aa287c7936e5fe80fdc337e744804b/onnxruntime/core/mlas/lib/platform.cpp#L105). 

For the Conv kernel case, Kernel is assigned here: https://github.com/microsoft/onnxruntime/blob/df16c605e8aa287c7936e5fe80fdc337e744804b/onnxruntime/core/mlas/lib/snchwc.cpp#L678, and the real kernel(assembly) code is linked according to the cpu info (arch, extensions)

**Comment by Darshcg** [comment]
Thanks a lot, @yufenglee. 

I inspected the Assembly files for the Conv op being executed on my CPU. And the corresponding files are: 
https://github.com/microsoft/onnxruntime/blob/df16c605e8aa287c7936e5fe80fdc337e744804b/onnxruntime/core/mlas/lib/x86_64/SconvKernelFma3.S and https://github.com/microsoft/onnxruntime/blob/df16c605e8aa287c7936e5fe80fdc337e744804b/onnxruntime/core/mlas/lib/x86_64/SconvKernelCommon.h. Can you please assist me in understanding the execution flow of the macros in these two files? and which is the first macro that is being executed in these two files?

Looking forward to your reply

Thanks
Darshan

**Comment by yufenglee** [comment]
The first macros are at the end of the file:
https://github.com/microsoft/onnxruntime/blob/df16c605e8aa287c7936e5fe80fdc337e744804b/onnxruntime/core/mlas/lib/x86_64/SconvKernelFma3.S#L242

**Comment by Darshcg** [comment]
Thanks a lot for your kind response @yufenglee.

Now I got the flow of the execution of the macros.

Lastly, can you please explain within a few lines about the ProcessFilterCountN, ProcessOutputCountN and computeBlock macros shortly? Would be a great help from your side.

Thanks

**Comment by Darshcg** [comment]
Hi @yufenglee,

Looking forward to your reply.

Thanks

**Comment by Darshcg** [comment]
Hi @yufenglee, @snnn 

What is the Convolution implementation used in the default EP? Is it only Direct or any other implementation like Winograd?

Thanks

**Comment by snnn** [comment]
@Darshcg , I don't know more than you.  :-) All the answers are in the source code.  I also need time to read it.

**Comment by Darshcg** [comment]
Hi @yufenglee

Look forward to your reply.

Thanks

**Comment by snnn** [comment]
Dear @Darshcg , this is an open source project, we encourage everyone to read the source code and make it better.
