### ISSUE TITLE
Fully convolutional NN support

### ISSUE THREAD

**Issue by elevir** [microsoft/onnxruntime#1039]
Hello!

I have a question about using fully convolutional neural networks. FCNNs have a very useful property that allows their usage on images with variable resolution, is this feature supported by onnxruntime? For example, in CNTK I can clone a model with substitution of input variables, is there any way to do this in onnxruntime?

Thanks in advance!

**Comment by pranavsharma** [comment]
onnxruntime implements the ONNX [standard ops](https://github.com/onnx/onnx/blob/master/docs/Operators.md). If you don't find an operator that meets your needs, feel free to [add](https://github.com/onnx/onnx/blob/master/docs/AddNewOp.md) one.

**Comment by elevir** [comment]
@pranavsharma thanks for answer!

> onnxruntime implements the ONNX standard ops

I think that input data substitution must be implemented on onnxruntime level, not on computation graph level.

**Comment by linkerzhang** [comment]
what do you mean by "input data substitution" please? do you mean input variables with different shape/resolution? if yes, I think both onnx and onnx runtime support that.

For FCNN, I think the part that ONNX (op spec) does not support is "dynamic output shape for ConvTranspose", which should be used as the last layer of FCNN? https://github.com/onnx/onnx/pull/1839 has been trying to solve the case. However, in ONNXRUNTIME, we are trying to have a custom ConvTranspose to support the case - https://github.com/microsoft/onnxruntime/pull/638

**Comment by elevir** [comment]
@linkerzhang 

> do you mean input variables with different shape/resolution?

Yes, I do.

> if yes, I think both onnx and onnx runtime support that.

That is great! Is there any example of using FCNN with different shaped variables?

**Comment by linkerzhang** [comment]
we don't have such examples right now. :(

**Comment by linkerzhang** [comment]
btw, is my understanding that ConvTranspose is the one used in FCNN to replace with FC correct? @elevir 

(i am not an expert of FCNN :))

**Comment by elevir** [comment]
@linkerzhang 

> we don't have such examples right now. :(

It is sad :( It will be grateful if someone show how to solve this task in couple lines of code (desired on C/C++)

> ConvTranspose is the one used in FCNN to replace with FC correct?

FC can be easy replaced by convolution :) This one is just special case of convolution.

**Comment by faxu** [comment]
@elevir: do you have the CNTK-exported (or other) ONNX model you are referring to? Having a concrete example will help us advise on this. 

CC: @liqunfu

**Comment by elevir** [comment]
@faxu it can be any model with shape independent layers. For example, a model which has just one convolutional layer. There is example of how can I solve the problem in CNTK:
```
// define model with input image of size 20x20x3
auto image = CNTK::InputVariable({ /*some shape, i.e.*/ 20, 20, 3 }, CNTK::DataType::Float, { CNTK::Axis::DefaultBatchAxis() });
std::wcout << image.AsString() << std::endl;
auto model = CNTK::LeakyReLU(Layers::Convolution(image, /*filter size*/{ 3, 3, }, /*count of filters*/1, /*strides*/{ 1, 1, 3 }), 0.01);
std::wcout << model->AsString() << std::endl;
model->Save(L"Simple FCNN.onnx", CNTK::ModelFormat::ONNX);
model->Save(L"Simple FCNN.model", CNTK::ModelFormat::CNTKv2);
auto loadedModel = CNTK::Function::Load(L"Simple FCNN.model", CNTK::DeviceDescriptor::UseDefaultDevice(), CNTK::ModelFormat::CNTKv2);
// we want to replace source input image by image with shape 640x480x3
auto variableToBeReplacing = CNTK::InputVariable({ 640, 480, 3 }, CNTK::DataType::Float, { CNTK::Axis::DefaultBatchAxis() });
std::wcout << variableToBeReplacing.AsString() << std::endl;
auto modelWithReplacedInput = CNTK::AsComposite(loadedModel)->Clone(CNTK::ParameterCloningMethod::Clone, { { loadedModel->Arguments()[0], variableToBeReplacing } });
std::wcout << modelWithReplacedInput->AsString() << std::endl;
// now we have model with input with size 640x480x3 and it will work fine!
```
And the input/output shape inference:
![image](https://user-images.githubusercontent.com/8929511/59083793-6b51b400-8901-11e9-91d0-a604a10d1592.png)
Also there is the [model](https://github.com/microsoft/onnxruntime/files/3264552/Simple.FCNN.zip) in onnx format from this simple example

I can give as an example of more useful FCNN model - [SuperPoint model](https://github.com/MagicLeapResearch/SuperPointPretrainedNetwork)

**Comment by linkerzhang** [comment]
a little bit confused. 

@elevir I am assuming that you can use any of our API (python/C/C++) to run your onnx model if any. here's a CAPI sample code. https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp

**Comment by elevir** [comment]
@linkerzhang I've already seen these examples, but the question is not how to use onnxruntime to evaluate pretrained model, but how to evaluate a model, for example, for images with shape 20x20 and 640x480 without modifying this model in any external framework. Examples show how to evaluate model with known and fixed input variable shape, if I understood correctly.

**Comment by pranavsharma** [comment]
@elevir  you should be able to construct the input of any shape you desire. Have you tried it?

**Comment by elevir** [comment]
@pranavsharma that is what I needed! Thanks!
