### ISSUE TITLE
.PDB file still included in NuGet and required to run application

### ISSUE THREAD

**Issue by matthewDDennis** [microsoft/onnxruntime#10401]
**Describe the bug**
Despite what is stated in [#8903](https://github.com/microsoft/onnxruntime/pull/8903) the PDBs are still include in the NuGet and are required to run the application.

If you run and application that uses Microsoft.ML.OnnxRuntime 1.10 and you deploy it without the PDB files you get
```
Error:
  An assembly specified in the application dependencies manifest (<application-name>.deps.json) was not found:
    package: 'Microsoft.ML.OnnxRuntime', version: '1.10.0'
    path: 'runtimes/win-x64/native/onnxruntime.pdb'
```
Also the application .deps.json file includes
```
      "Microsoft.ML.OnnxRuntime/1.10.0": {
        "dependencies": {
          "Microsoft.ML.OnnxRuntime.Managed": "1.10.0"
        },
        "native": {
          "runtimes/win-x64/native/onnxruntime.dll": {
            "fileVersion": "1.10.21.1206"
          },
          "runtimes/win-x64/native/onnxruntime.lib": {
            "fileVersion": "0.0.0.0"
          },
          "runtimes/win-x64/native/onnxruntime.pdb": {
            "fileVersion": "0.0.0.0"
          },
          "runtimes/win-x64/native/onnxruntime_providers_shared.dll": {
            "fileVersion": "0.0.0.0"
          },
          "runtimes/win-x64/native/onnxruntime_providers_shared.lib": {
            "fileVersion": "0.0.0.0"
          },
          "runtimes/win-x64/native/onnxruntime_providers_shared.pdb": {
            "fileVersion": "0.0.0.0"
          }
        }
```
**Urgency**
This increases the storage requirements by186 M,  and installation package size is also increases.  Our application may be installed on memory and storage constrained machines, so this is very important to us.

**System information**
- Windows 10
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version: Microsoft.ML.OnnxRuntime 1.10
- Python version: NA
- Visual Studio version (if applicable): 2019 16.11.9
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Expected behavior**
The PDB files are not include in the NuGet package, nor required by applications using the package.

**Comment by snnn** [comment]
I really don't know what I can do.
Someone wants the PDBs. But I can't publish them as a symbol package to nuget.org because nuget.org doesn't accept symbols for native code. 
Then what's the better place?

**Comment by matthewDDennis** [comment]
How about two different Nuget Packages. one with the .debug suffix that has the PDBs and one without the suffix without the PDBs.  The PDBs are only needed for someone debugging the onnxruntime and have little use for the majority of the other users.

**Comment by snnn** [comment]
> How about two different Nuget Packages. one with the .debug suffix that has the PDBs and one without the suffix without the PDBs. The PDBs are only needed for someone debugging the onnxruntime and have little use for the majority of the other users.

It doesn't seem to be a standard way and nuget.org maintainers may not like it.

**Comment by snnn** [comment]
The following note is for our devs:

At this moment, the quickest solution is to delete the pdb files just before building the package.

Go to https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/azure-pipelines/templates/c-api-cpu.yml#L491, insert a delete files task just before that line. 

Please let me know what you think.

**Comment by nums11** [comment]
Closing as resolved.
