### ISSUE TITLE
[WinML] [C++/WinRT] Empty output after GPU to GPU inference via VideoFrame

### ISSUE THREAD

**Issue by aergistal** [microsoft/onnxruntime#10410]
**Describe the bug**

Empty texture on output after GPU-GPU inference using DirectX 11 textures (single-channel) which are wrapped in `VideoFrame` for input/output binding. I am making the assumption this is a supported use-case.

**System information**
- ONNX Runtime installed from: binary (NuGet)
- ONNX Runtime version: v1.10.0
- Visual Studio version: 2019
- GPU model and memory: Nvidia RTX 2070,  8 GB

**To Reproduce**
Please see the example code below.

**Expected behavior**
Getting a valid texture instead of a zero-filled one from the output `VideoFrame` representing the inference result.

Additional notes:
- input/output textures are on the same device which is used to do the inference, there shouldn't be any sharing issues
- a copy of the output texture with the required binding flags is used as a shader resource further in the pipeline

Sanity tests:
- passing the input `VideoFrame`'s surface as a texture down the pipeline works, the input is not empty
- using a CPU `LearningModelDevice` and just creating the input/output `VideoFrame` on the source Direct3D device also works, at least with a simple test model

**Additional context**
Example code:

```
// source D3D11 device and a texture created on it
ID3D11Device *sourceDevice;
ID3D11Texture2D *sourceTexture;

// get the Direct3D11 device
com_ptr<IDXGIDevice> dxgiDevice;
sourceDevice->QueryInterface(IID_PPV_ARGS(&dxgiDevice));

com_ptr<IInspectable> inspectableDevice;
CreateDirect3D11DeviceFromDXGIDevice(dxgiDevice.get(), inspectableDevice.put());

// initialize the session using the source Direct3D11 device
LearningModel model = LearningModel::LoadFromFilePath(L"model.onnx");
LearningModelDevice device = LearningModelDevice::CreateFromDirect3D11Device(inspectableDevice.as<IDirect3DDevice>());
LearningModelSession session = LearningModelSession(model, device);
LearningModelBinding binding = LearningModelBinding(session);

// create the input/output video frames on the same Direct3D11 device
VideoFrame inputFrame = VideoFrame::CreateAsDirect3D11SurfaceBacked(
    DirectXPixelFormat::R8UIntNormalized, ONNX_INPUT_W, ONNX_INPUT_H, session.Device().Direct3D11Device());
VideoFrame outputFrame = VideoFrame::CreateAsDirect3D11SurfaceBacked(
    DirectXPixelFormat::R8UIntNormalized, ONNX_OUTPUT_W, ONNX_OUTPUT_H, session.Device().Direct3D11Device());

// create the source video frame from the source D3D11 texture
com_ptr<IDXGISurface> dxgiSurface;
sourceTexture->QueryInterface(IID_PPV_ARGS(&dxgiSurface));

com_ptr<::IInspectable> inspectableSurface;
CreateDirect3D11SurfaceFromDXGISurface(
    dxgiSurface.get(),
    reinterpret_cast<IInspectable**>(winrt::put_abi(inspectableSurface))
);

VideoFrame sourceFrame = VideoFrame::CreateWithDirect3D11Surface(inspectableSurface.as<IDirect3DSurface>());

// copy the source frame to the input frame
sourceFrame.CopyToAsync(inputFrame).get();

// create the input/output tensors
ImageFeatureValue inputTensor = ImageFeatureValue::CreateFromVideoFrame(inputFrame);
ImageFeatureValue outputTensor = ImageFeatureValue::CreateFromVideoFrame(outputFrame);

// bind and evaluate
binding.Bind(model.InputFeatures().First().Current().Name(), inputTensor);
binding.Bind(model.OutputFeatures().First().Current().Name(), outputTensor);
session.Evaluate(binding, L"");

// get the output D3D11 texture from the output tensor
auto spDxgiInterfaceAccess = outputTensor.VideoFrame().Direct3DSurface().as<IDirect3DDxgiInterfaceAccess>();
com_ptr<ID3D11Texture2D> outputTexture;
spDxgiInterfaceAccess->GetInterface(IID_PPV_ARGS(&outputTexture));

// make a copy of the output texture with D3D11_BIND_SHADER_RESOURCE and pass it down the pipeline
// ...
```

Maybe there is a sort of DirectX synchronization issue?
Is there a better alternative approach for doing GPU-GPU inference on DirectX texture data?

Thank you.

**Comment by fdwr** [comment]
If the code was calling `GetExecutionProviderApi` with "DML" directly, then I'd say it might be [this recent issue](https://github.com/microsoft/onnxruntime/issues/9962) with the new API fixed [here](https://github.com/microsoft/onnxruntime/pull/10362), but it's going through WinML which should work 🤔. Tagging @smk2007 for visibility.

**Comment by aergistal** [comment]
@smk2007 @fdwr Thank you for the patch, it's much appreciated! Do you know if a release including this fix is planned soon, it's a blocker for our project. I would build it myself but it seems to require Windows Core OS.

**Comment by fdwr** [comment]
@aergistal 
>Do you know if a release including this fix is planned soon
Historically ORT releases every ~2-3 months, and the [last release](https://github.com/microsoft/onnxruntime/releases) was December. So, not as soon as you'd like.

>it seems to require Windows Core OS
"Windows Core OS"? 🤔 We're just building it on regular Windows 10 (21H1 19043).  It's been a while since I built full WinML too, but where's what I wrote down last time:

```python.exe tools\ci_build\build.py --config RelWithDebInfo --build_shared_lib --cmake_generator "Visual Studio 16 2019" --build_wheel --use_winml --build_shared_lib --enable_wcos --gen_doc --use_dml --cmake_extra_defines CMAKE_SYSTEM_VERSION=10.0.18362.0```

**Comment by aergistal** [comment]
@fdwr Nevermind, it was missing the WCOS flag. I'll try to test the changes.

**Comment by aergistal** [comment]
@fdwr @smk2007 It works correctly now, will close the issue. Thank you again!

**Comment by smk2007** [comment]
@aergistal I am glad it has unblocked you. If you want to produce a local NuGet package with WinML for easier consumption, you can use the --build_nuget option as well to create a desired package with the desired architecture build.
