### ISSUE TITLE
How to build from source on macOS m1??

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#10435]
How to build from source on macOS m1??

**Comment by Craigacp** [comment]
For what platform & language API?

**Comment by jinfagang** [comment]
@Craigacp I managed build with command with Release and enabled macOS arm64. But the speed to slower than I using x86 version, how could this possible?

**Comment by chenfucn** [comment]
MacOS is not open and utilizing all its hardware resources is not straight forward. We are actively working on improvements.

**Comment by jinfagang** [comment]
@chenfucn when will there be a stable version for M1 version Mac?

**Comment by chenfucn** [comment]
Every stable version works on Mac. Unfortunately, Apple platform is not open, optimizing for it is difficult and slow

**Comment by jinfagang** [comment]
@chenfucn  AFAIK, there is no support for **M1** Mac stable.
