### ISSUE TITLE
Error with model input size

### ISSUE THREAD

**Issue by yusramoni** [microsoft/onnxruntime#10446]
**Describe the bug**
Hello,

I'm having an issue with the model input size that I'm getting from onnx. I've converted my model from Matlab to an onnx model and the input should be a simple column vector of 6x1 size. Or at least, that is the only model input when I've used it within Matlab. When I print out the shape of the input after it's been loaded my onnx in c++, I get an input shape of -1x-1x6. I'm confused as to where the three dimensions came from. I also can't create a tensor using this shape because of its negative value. Below is a part of my code in c++ to provide a bit more context. If the problem is still unclear, I can try to clarify further. Thanks so much in advance.

My input data should look like this (per say printing data.data()):
0.720925
0.141332
-0.890676
0.5409
0.0348706
0.252149

Output of the model in C++ prints: (This is when I print out inputShape.data() and inputShape.size() = 3 which is provided by onnx):
My code:

```
std::vector<int64_t> inputShape = session.GetInputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape();
cout << "Input Node Name/Shape (" << session.GetInputCount() << "):" << endl;
cout << "\t" << input_name << " : " << print_shape(inputShape) << endl;
```

the print_shape function:

```
string print_shape(const std::vector<int64_t>& v) {
stringstream ss("");
for (size_t i = 0; i < v.size() - 1; i++)
ss << v[i] << "x";
ss << v[v.size() - 1];
return ss.str();
}
```

The output:
`Number of model inputs: 1 Number of model outputs: 1 Input Node Name/Shape (1): sequenceinput : -1x-1x6`

When I run this portion of the code:
```
auto memoryInfo = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU);
auto input_tensors = Ort::Value::CreateTensor<float>(memoryInfo, data.data(), data.size(), inputShape.data(), inputShape.size());
```
Throws the exception:
`ERROR running model inference: tried creating tensor with negative value in shape`

My biggest issue currently is the input size of the model which is supposedly requiring a -1 x -1 x 6 input. Instead, I believe the input shape should be similar to the printed input I displayed earlier a 6 x 1 or a 1 x 6. It should simply be a vector.

**Urgency**
as soon as possible

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS
- ONNX Runtime installed from (source or binary): onnxruntime-osx-x86_64-1.10.0
- ONNX Runtime version: 1.10
- Python version:
- Visual Studio version (if applicable): visual studio code
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by garymm** [comment]
Maybe a bug in MATLAB converter. I'd try reporting it to MATLAB.
To work around you could edit the ONNX model file to set the input shapes to whatever you want.

**Comment by yuslepukhin** [comment]
You can visualize your model using [Netron](https://netron.app/) and see if the shape required are actually dynamic (symbolic)

**Comment by yusramoni** [comment]
The visualization for the model was pretty helpful, thanks. If I wanted to create an input vector for my model in onnx to be something like [number of features, batchSize, 6], where 6 is original input data vector I mentioned in my original post, how would I create a Ort Value of this? 
A CreateSparseTensor call is not enough for a vector<vector<float> > type. I'm not familiar with onnx so if there's an easier way to go about this it would be helpful.

**Comment by yuslepukhin** [comment]
@yusramoni When you feed data as input for inference you need to supply both shape and the data. Even though the shape has a dynamic component (symbolic) in it (designated in your output as -1) it must actually be a specific positive number when you feed an input. The symbolic token must be substituted by your batch size for a given inference run.
The data is fed as a flat buffer in single allocation that does not depend on your language construct that holds it. `std::vector<std::vector >` would not represent a single buffer, but a `std::vector` would. However, you also simply allocate a chunk of memory and hold it in a smart pointer, it does not matter. The size of the buffer in bytes must be the product of all dimensions multiplied byte the size of a single element sizeof(float). The shape determines how the buffer is interpreted.
Keep in mind, `CreateTensor() ` does not copy your data internally and your buffers must be alive and well for the entire duration of inference call.

**Comment by yusramoni** [comment]
Apologies if I'm still not understanding. The input for my model looks like this from Netron: 
name: sequenceinput
type: float32[sequenceinput_SequenceLength,BatchSize,6]

I'm assuming the last dimension is where I put in my vector data and the first two are integer values, so for example [6, 8, data]. I've tried using a vector that simply holds all the values so 
data = {6, 8, 0.720925, 0.141332, ...} and then using this with the positive converted inputShape 1x1x6 to create a tensor with Ort::Value::CreateTensor<float>, but I am getting pretty different values out of the model. I don't think I'm providing the input correctly.

**Comment by yuslepukhin** [comment]
``

> Apologies if I'm still not understanding. The input for my model looks like this from Netron: name: 

The metadata you get about this input:
sequenceinput type: `float32[sequenceinput_SequenceLength,BatchSize,6]`

This means that your input should have type float32 (in C++ simply float). That buffer must be a contiguous chunk of memory filled with floats.

The shape `[sequenceinput_SequenceLength,BatchSize,6]` describes the shape of your buffer. It does not affect the content of your buffer in any way. Just a description of how the model interprets it.

It tells you that your input shape must have 3 dimensions. The last axis is fixed = 6. You cannot change it. However, the first two axis you must substitute for specific integer values. The product of all the dimensions is the number of float elements in your buffer. It must be equal to the actual number of float elements in your buffer.
