### ISSUE TITLE
warning: 'cpuinfo_arm_fixup_raspberry_pi_chipset'

### ISSUE THREAD

**Issue by a76yyyy** [microsoft/onnxruntime#10444]
**Describe the bug**
```shell
/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/chipset.c: In function 'cpuinfo_arm_linux_decode_chipset':
/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/chipset.c:3853:25: warning: 'cpuinfo_arm_fixup_raspberry_pi_chipset' reading 64 bytes from a region of size 9 [-Wstringop-overread]
 3853 |                         cpuinfo_arm_fixup_raspberry_pi_chipset(&chipset, revision);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/chipset.c:3853:25: note: referencing argument 2 of type 'const char * restrict'
/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/chipset.c:3777:14: note: in a call to function 'cpuinfo_arm_fixup_raspberry_pi_chipset'
```

**Urgency**
No hard deadlines.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 11 x86_64 -Docker DeskTop - alpine:edge - Dockerfile**
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master
- Python version: 3.10.2
- Visual Studio version (if applicable): No
- GCC/Compiler version (if compiling from source):
```
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-alpine-linux-musl/11.2.1/lto-wrapper
Target: aarch64-alpine-linux-musl
Configured with: /home/buildozer/aports/main/gcc/src/gcc-11.2.1_git20220117/configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --build=aarch64-alpine-linux-musl --host=aarch64-alpine-linux-musl --target=aarch64-alpine-linux-musl --with-pkgversion='Alpine 11.2.1_git20220117' --enable-checking=release --disable-fixed-point --disable-libstdcxx-pch --disable-multilib --disable-nls --disable-werror --disable-symvers --enable-__cxa_atexit --enable-default-pie --enable-default-ssp --enable-cloog-backend --enable-languages=c,c++,d,objc,go,fortran,ada,jit --with-arch=armv8-a --with-abi=lp64 --disable-libquadmath --disable-libssp --disable-libmpx --disable-libmudflap --disable-libsanitizer --enable-shared --enable-threads --enable-tls --enable-host-shared --with-system-zlib --with-linker-hash-style=gnu
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.2.1 20220117 (Alpine 11.2.1_git20220117)
```
- CUDA/cuDNN version: No
- GPU model and memory: No

**To Reproduce**
```Dockerfile
# Base Image
FROM alpine:edge

# Envirenment for pycurl
ENV ONNXRUNTIME_TAG=master

# Install packages
RUN apk update && \
    apk add --update --no-cache openrc redis bash git tzdata nano openssh-client ca-certificates\
    file libidn2-dev libgsasl-dev krb5-dev zstd-dev nghttp2-dev zlib-dev brotli-dev \
    python3 py3-numpy-dev py3-pip py3-setuptools py3-wheel py3-opencv py3-pillow && \
    ln -s /usr/bin/python3 /usr/bin/python

# git clone onnxruntime & Pip install onnxruntime
RUN apk add --update --no-cache --virtual .build_deps cmake make perl autoconf g++ automake \
    linux-headers libtool util-linux libexecinfo-dev openblas-dev python3-dev \
    protobuf-dev flatbuffers-dev date-dev gtest-dev eigen-dev || \
    apk add --update --no-cache --virtual .build_deps cmake make perl autoconf g++ automake \
    linux-headers libtool util-linux libexecinfo-dev openblas-dev python3-dev \
    protobuf-dev date-dev gtest-dev eigen-dev && \
    git clone --depth 1 --branch $ONNXRUNTIME_TAG https://github.com./Microsoft/onnxruntime && \
    cd /onnxruntime && \
    git submodule update --init --recursive && \
    cd .. && \
    rm /onnxruntime/onnxruntime/test/providers/cpu/nn/string_normalizer_test.cc && \
    sed "s/    return filters/    filters += \[\'^test_strnorm.*\'\]\n    return filters/" \
    -i /onnxruntime/onnxruntime/test/python/onnx_backend_test_series.py && \
    [[ $(getconf LONG_BIT) = "32" && -z $(file /bin/busybox | grep -i "arm") ]] &&  \
    { bashtmp='setarch i386 /onnxruntime/build.sh' && cxxtmp='-msse -msse2'; } || {\
    [[ -z $(file /bin/busybox | grep -i "arm") ]] && \
    { bashtmp='/onnxruntime/build.sh' && cxxtmp=''; } || \
    { [[ $(getconf LONG_BIT) = "32" ]] && \
    { bashtmp='/onnxruntime/build.sh --arm' && cxxtmp=''; } || \
    { bashtmp='setarch arm64 /onnxruntime/build.sh' && cxxtmp=''; }; }; } && \
    echo 'add_subdirectory(${PROJECT_SOURCE_DIR}/external/nsync EXCLUDE_FROM_ALL)' >> /onnxruntime/cmake/CMakeLists.txt && \
    echo $bashtmp && echo $cxxtmp && \
    $bashtmp --config MinSizeRel  \
        --parallel \
        --build_wheel \
        --enable_pybind \
        --cmake_extra_defines \
            CMAKE_CXX_FLAGS="-Wno-deprecated-copy -Wno-unused-variable $cxxtmp"\
            onnxruntime_BUILD_UNIT_TESTS=OFF \
            onnxruntime_BUILD_SHARED_LIB=OFF \
            onnxruntime_USE_PREINSTALLED_EIGEN=ON \
            onnxruntime_PREFER_SYSTEM_LIB=ON \
            eigen_SOURCE_PATH=/usr/include/eigen3 \
        --skip_tests && \
    apk del .build_deps && \
    apk add libprotobuf-lite && \
    pip install --no-cache-dir /onnxruntime/build/Linux/MinSizeRel/dist/onnxruntime*.whl && \
    ln -s $(python -c 'import warnings;warnings.filterwarnings("ignore");\
    from distutils.sysconfig import get_python_lib;print(get_python_lib())')/onnxruntime/capi/libonnxruntime_providers_shared.so /usr/lib && \
    cd / && rm -rf /onnxruntime
```
Shell:
`docker buildx build  --platform linux/arm64 .  -t test/onnxruntime --load`

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by chenfucn** [comment]
Seems a typo on the cpuinfo code, no real overread possible. Let me study how to get around this.

**Comment by chenfucn** [comment]
@a76yyyy does this warning break build?

**Comment by a76yyyy** [comment]
This warning does not affect the build, but the following errors occur when building armv6 wheels:
```shell
[ 98%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_exceptions.cc.o
[100%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_iobinding.cc.o
[100%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_mlvalue.cc.o
[100%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_ortvalue.cc.o
[100%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_module.cc.o
[100%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_sparse_tensor.cc.o
[100%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_state.cc.o
[100%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_state_common.cc.o
[100%] Linking CXX shared module onnxruntime_pybind11_state.so
/usr/lib/gcc/armv6-alpine-linux-musleabihf/11.2.1/../../../../armv6-alpine-linux-musleabihf/bin/ld: external/pytorch_cpuinfo/libcpuinfo.a(init.c.o): in function `cpuinfo_initialize':
init.c:(.text.cpuinfo_initialize+0x28): undefined reference to `cpuinfo_arm_linux_init'
/usr/lib/gcc/armv6-alpine-linux-musleabihf/11.2.1/../../../../armv6-alpine-linux-musleabihf/bin/ld: onnxruntime_pybind11_state.so: hidden symbol `cpuinfo_arm_linux_init' isn't defined
/usr/lib/gcc/armv6-alpine-linux-musleabihf/11.2.1/../../../../armv6-alpine-linux-musleabihf/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/onnxruntime_pybind11_state.dir/build.make:265: onnxruntime_pybind11_state.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:1866: CMakeFiles/onnxruntime_pybind11_state.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

DockerFile:
```shell
FROM alpine:edge

# Envirenment 
ENV ONNXRUNTIME_TAG=master

# 换源 & Install packages
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
    apk update && \
    apk add --update --no-cache openrc redis bash git tzdata nano openssh-client ca-certificates\
    file libidn2-dev libgsasl-dev krb5-dev zstd-dev nghttp2-dev zlib-dev brotli-dev \
    python3 py3-numpy-dev py3-pip py3-setuptools py3-wheel py3-opencv py3-pillow && \
    ln -s /usr/bin/python3 /usr/bin/python

# git clone onnxruntime & Pip install onnxruntime
RUN apk add --update --no-cache --virtual .build_deps cmake make perl autoconf g++ automake \
    linux-headers libtool util-linux libexecinfo-dev openblas-dev python3-dev \
    protobuf-dev flatbuffers-dev date-dev gtest-dev eigen-dev || \
    apk add --update --no-cache --virtual .build_deps cmake make perl autoconf g++ automake \
    linux-headers libtool util-linux libexecinfo-dev openblas-dev python3-dev \
    protobuf-dev date-dev gtest-dev eigen-dev && \
    git clone --depth 1 --branch $ONNXRUNTIME_TAG https://github.com./Microsoft/onnxruntime && \
    cd /onnxruntime && \
    git submodule update --init --recursive && \
    cd .. && \
    rm /onnxruntime/onnxruntime/test/providers/cpu/nn/string_normalizer_test.cc && \
    sed "s/    return filters/    filters += \[\'^test_strnorm.*\'\]\n    return filters/" \
    -i /onnxruntime/onnxruntime/test/python/onnx_backend_test_series.py && \
    echo 'add_subdirectory(${PROJECT_SOURCE_DIR}/external/nsync EXCLUDE_FROM_ALL)' >> /onnxruntime/cmake/CMakeLists.txt && \
    [[ $(getconf LONG_BIT) = "32" && -z $(file /bin/busybox | grep -i "arm") ]] &&  \
    { bashtmp='setarch i386 /onnxruntime/build.sh' && cxxtmp='-msse -msse2'; } || {\
    [[ -z $(file /bin/busybox | grep -i "arm") ]] && \
    { bashtmp='/onnxruntime/build.sh' && cxxtmp=''; } || \
    { [[ $(getconf LONG_BIT) = "32" ]] && \
    { bashtmp='' && cxxtmp=''; } || \
    { bashtmp='' && cxxtmp=''; }; }; } && \
    { [[ -z $bashtmp ]] && { \
    cmaketmp="-DCMAKE_BUILD_TYPE=MinSizeRel -Dprotobuf_WITH_ZLIB=OFF -DCMAKE_TOOLCHAIN_FILE=/onnxruntime/build/tool.cmake \
    -Donnxruntime_ENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 -Donnxruntime_BUILD_SHARED_LIB=OFF \
    -Donnxruntime_DEV_MODE=OFF -DONNX_CUSTOM_PROTOC_EXECUTABLE=/usr/bin/protoc -Donnxruntime_BUILD_UNIT_TESTS=OFF \
    -Donnxruntime_USE_PREINSTALLED_EIGEN=ON -Donnxruntime_PREFER_SYSTEM_LIB=ON -Deigen_SOURCE_PATH=/usr/include/eigen3" && \
    mkdir -p /onnxruntime/build && \
    echo "SET(CMAKE_SYSTEM_NAME Linux)" > /onnxruntime/build/tool.cmake && \
    echo "SET(CMAKE_SYSTEM_VERSION 1)" >> /onnxruntime/build/tool.cmake && \
    echo "SET(CMAKE_C_COMPILER gcc)" >> /onnxruntime/build/tool.cmake && \
    echo "SET(CMAKE_CXX_COMPILER g++)" >> /onnxruntime/build/tool.cmake && \
    echo "SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)" >> /onnxruntime/build/tool.cmake && \
    echo "SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)" >> /onnxruntime/build/tool.cmake && \
    echo "SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)" >> /onnxruntime/build/tool.cmake && \
    echo "SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)" >> /onnxruntime/build/tool.cmake && \
    echo "SET(CMAKE_FIND_ROOT_PATH /)" >> /onnxruntime/build/tool.cmake && \
    echo 'STRING(APPEND CMAKE_CXX_FLAGS " -Wno-deprecated-copy -Wno-unused-variable -Wno-psabi")' >> /onnxruntime/build/tool.cmake && \
    cd /onnxruntime/build && cmake ../cmake $cmaketmp && \
    make -j$(($(grep -c ^processor /proc/cpuinfo) - 0)) && python3 setup.py bdist_wheel && cd /; } || {\
    echo $bashtmp && echo $cxxtmp && \
    $bashtmp --config MinSizeRel  \
        --parallel \
        --build_wheel \
        --enable_pybind \
        --cmake_extra_defines \
            CMAKE_CXX_FLAGS="-Wno-deprecated-copy -Wno-unused-variable $cxxtmp"\
            onnxruntime_BUILD_UNIT_TESTS=OFF \
            onnxruntime_BUILD_SHARED_LIB=OFF \
            onnxruntime_USE_PREINSTALLED_EIGEN=ON \
            onnxruntime_PREFER_SYSTEM_LIB=ON \
            eigen_SOURCE_PATH=/usr/include/eigen3 \
        --skip_tests ;};} && \
    apk del .build_deps && \
    apk add libprotobuf-lite && \
    pip install --no-cache-dir /onnxruntime/build/Linux/MinSizeRel/dist/onnxruntime*.whl && \
    ln -s $(python -c 'import warnings;warnings.filterwarnings("ignore");\
    from distutils.sysconfig import get_python_lib;print(get_python_lib())')/onnxruntime/capi/libonnxruntime_providers_shared.so /usr/lib && \
    cd / && rm -rf /onnxruntime

```

**Comment by chenfucn** [comment]
I can build libonnxruntime.so without problem on Linux ARM64. I am not familiar with python part of the build. We need to investigate more where the problem lies.

**Comment by snnn** [comment]
armv6 is not ARM64. We don't have an Linux ARMv6 pipeline, so I don't know if it could work.

**Comment by a76yyyy** [comment]
> I can build libonnxruntime.so without problem on Linux ARM64. I am not familiar with python part of the build. We need to investigate more where the problem lies.

This warning does not affect the build on the ARM64, but I think it is a noticeable problem

**Comment by a76yyyy** [comment]
> armv6 is not ARM64. We don't have an Linux ARMv6 pipeline, so I don't know if it could work.

When i build the arm wheel (either v6 or v7), the first 99% of the progress is smooth, only in the last 1% is the error that prompts the following `cpuinfo` initialization failure.

**Maybe I should reopen an issue? ** 

> This warning does not affect the build, but the following errors occur when building armv6 wheels:
> 
> ```shell
> [ 98%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_exceptions.cc.o
> [100%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_iobinding.cc.o
> [100%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_mlvalue.cc.o
> [100%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_ortvalue.cc.o
> [100%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_module.cc.o
> [100%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_sparse_tensor.cc.o
> [100%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_state.cc.o
> [100%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/onnxruntime/onnxruntime/python/onnxruntime_pybind_state_common.cc.o
> [100%] Linking CXX shared module onnxruntime_pybind11_state.so
> /usr/lib/gcc/armv6-alpine-linux-musleabihf/11.2.1/../../../../armv6-alpine-linux-musleabihf/bin/ld: external/pytorch_cpuinfo/libcpuinfo.a(init.c.o): in function `cpuinfo_initialize':
> init.c:(.text.cpuinfo_initialize+0x28): undefined reference to `cpuinfo_arm_linux_init'
> /usr/lib/gcc/armv6-alpine-linux-musleabihf/11.2.1/../../../../armv6-alpine-linux-musleabihf/bin/ld: onnxruntime_pybind11_state.so: hidden symbol `cpuinfo_arm_linux_init' isn't defined
> /usr/lib/gcc/armv6-alpine-linux-musleabihf/11.2.1/../../../../armv6-alpine-linux-musleabihf/bin/ld: final link failed: bad value
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/onnxruntime_pybind11_state.dir/build.make:265: onnxruntime_pybind11_state.so] Error 1
> make[1]: *** [CMakeFiles/Makefile2:1866: CMakeFiles/onnxruntime_pybind11_state.dir/all] Error 2
> make: *** [Makefile:166: all] Error 2
> ```
> 
> DockerFile:
> 
> ```shell
> FROM alpine:edge
> 
> # Envirenment 
> ENV ONNXRUNTIME_TAG=master
> 
> #  Install packages
> RUN apk update && \
>     apk add --update --no-cache openrc redis bash git tzdata nano openssh-client ca-certificates\
>     file libidn2-dev libgsasl-dev krb5-dev zstd-dev nghttp2-dev zlib-dev brotli-dev \
>     python3 py3-numpy-dev py3-pip py3-setuptools py3-wheel py3-opencv py3-pillow && \
>     ln -s /usr/bin/python3 /usr/bin/python
> 
> # git clone onnxruntime & Pip install onnxruntime
> RUN apk add --update --no-cache --virtual .build_deps cmake make perl autoconf g++ automake \
>     linux-headers libtool util-linux libexecinfo-dev openblas-dev python3-dev \
>     protobuf-dev date-dev gtest-dev eigen-dev && \
>     git clone --depth 1 --branch $ONNXRUNTIME_TAG https://github.com./Microsoft/onnxruntime && \
>     cd /onnxruntime && \
>     git submodule update --init --recursive && \
>     cd .. && \
>     rm /onnxruntime/onnxruntime/test/providers/cpu/nn/string_normalizer_test.cc && \
>     sed "s/    return filters/    filters += \[\'^test_strnorm.*\'\]\n    return filters/" \
>     -i /onnxruntime/onnxruntime/test/python/onnx_backend_test_series.py && \
>     echo 'add_subdirectory(${PROJECT_SOURCE_DIR}/external/nsync EXCLUDE_FROM_ALL)' >> /onnxruntime/cmake/CMakeLists.txt && \
>     cmaketmp="-DCMAKE_BUILD_TYPE=MinSizeRel -Dprotobuf_WITH_ZLIB=OFF -DCMAKE_TOOLCHAIN_FILE=/onnxruntime/build/tool.cmake \
>     -Donnxruntime_ENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 -Donnxruntime_BUILD_SHARED_LIB=OFF \
>     -Donnxruntime_DEV_MODE=OFF -DONNX_CUSTOM_PROTOC_EXECUTABLE=/usr/bin/protoc -Donnxruntime_BUILD_UNIT_TESTS=OFF \
>     -Donnxruntime_USE_PREINSTALLED_EIGEN=ON -Donnxruntime_PREFER_SYSTEM_LIB=ON -Deigen_SOURCE_PATH=/usr/include/eigen3" && \
>     mkdir -p /onnxruntime/build && \
>     echo "SET(CMAKE_SYSTEM_NAME Linux)" > /onnxruntime/build/tool.cmake && \
>     echo "SET(CMAKE_SYSTEM_VERSION 1)" >> /onnxruntime/build/tool.cmake && \
>     echo "SET(CMAKE_C_COMPILER gcc)" >> /onnxruntime/build/tool.cmake && \
>     echo "SET(CMAKE_CXX_COMPILER g++)" >> /onnxruntime/build/tool.cmake && \
>     echo "SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)" >> /onnxruntime/build/tool.cmake && \
>     echo "SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)" >> /onnxruntime/build/tool.cmake && \
>     echo "SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)" >> /onnxruntime/build/tool.cmake && \
>     echo "SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)" >> /onnxruntime/build/tool.cmake && \
>     echo "SET(CMAKE_FIND_ROOT_PATH /)" >> /onnxruntime/build/tool.cmake && \
>     echo 'STRING(APPEND CMAKE_CXX_FLAGS " -Wno-deprecated-copy -Wno-unused-variable -Wno-psabi")' >> /onnxruntime/build/tool.cmake && \
>     cd /onnxruntime/build && cmake ../cmake $cmaketmp && \
>     make -j$(($(grep -c ^processor /proc/cpuinfo) - 0)) && python3 setup.py bdist_wheel && cd /; } && \
>     apk del .build_deps && \
>     apk add libprotobuf-lite && \
>     pip install --no-cache-dir /onnxruntime/build/Linux/MinSizeRel/dist/onnxruntime*.whl && \
>     ln -s $(python -c 'import warnings;warnings.filterwarnings("ignore");\
>     from distutils.sysconfig import get_python_lib;print(get_python_lib())')/onnxruntime/capi/libonnxruntime_providers_shared.so /usr/lib && \
>     cd / && rm -rf /onnxruntime
> ```
