### ISSUE TITLE
Question about packed data in QGEMM kernel

### ISSUE THREAD

**Issue by RajalakshmiSR** [microsoft/onnxruntime#10451]
I am preparing a patch to optimize QGEMM for POWER10 hardware and I have a question about the packed kernel.

As per the following structure, there are two kernels to handle non-packed dataB and packed dataB.

struct MLAS_GEMM_QUANT_DISPATCH {
    MLAS_GEMM_QUANT_OPERATION* Operation;
    MLAS_GEMM_QUANT_OPERATION* PackedOperation;
    MLAS_GEMM_QUANT_COPY_PACKB_ROUTINE* CopyPackBRoutine;
    size_t PackedK;
    size_t PackedStrideK;
};

1. I see a note that “MlasGemmQuantOperation and MlasGemmQuantPackedOperation are shared kernel drivers” and the main difference is packed kernel does not explicitly call copypackB routine as dataB is prepacked. 
When dataB is prepacked, what is the packing routine used for it? Is it the default generic packB routine? 
2. For getting into POWER10 specific QGEMM  unless dataB is packed using  POWER10CopyPackBRoutine, I cannot reuse the P10 kernel for PackedOperation. So if I specify POWER10CopyPackBRoutine as the third element in the above structure,
Can I expect dataB to be packed using POWER10CopyPackBRoutine before getting to the POWER10 kernel in case of PackedOperation?
3. On some architecture-specific qgemm* files , PackedOperation is specified as nullptr .  When PackedOperation is nullptr, does it take the default kernel for PackedOperation?

**Comment by RajalakshmiSR** [comment]
@yufenglee Do you have any suggestions on this?

**Comment by yufenglee** [comment]
In most cases for deep learning, Matrix B is const and packing it in advance can improve performance. 

So the CopyPackBRoutine in MLAS_GEMM_QUANT_DISPATCH is used to prepack B. Caller calls [MlasGemmPackBSize ](https://github.com/microsoft/onnxruntime/blob/df0c819850d8426706e853b629af3803ad5cc469/onnxruntime/core/mlas/lib/qgemm.cpp#L317) firstly to get packBSize to allocate buffer for packing and [MlasGemmPackB](https://github.com/microsoft/onnxruntime/blob/df0c819850d8426706e853b629af3803ad5cc469/onnxruntime/core/mlas/lib/qgemm.cpp#L386), which calls CopyPackBRoutine, to pack Matrix B. Then it sets [BIsPacked](https://github.com/microsoft/onnxruntime/blob/df0c819850d8426706e853b629af3803ad5cc469/onnxruntime/core/mlas/lib/qgemm.cpp#L102) and call PackedOperation. 

You can use the same CopyPackBRoutine and same kernels for both cases(packed and unpacked). The only difference is CopyPackBRoutine is called in ahead of time or at runtime.

If packed operation is nullptr, it won't prepack B in advance, so only the Operation will be called.

**Comment by RajalakshmiSR** [comment]
Thanks @yufenglee
