### ISSUE TITLE
"Non-zero status code returned while running Reshape node" on dynamic batch sized model

### ISSUE THREAD

**Issue by Naveassaf** [microsoft/onnxruntime#10463]
I have a Yolo_v3 onnx model that I am trying to run dynamically-sized batches on. **When utilizing a BS of 1**, all works well. When I try to utilize BS of size 8, I hit the following runtime error:

`
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_331' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:42 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape &, std::vector<int64_t> &, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{8,255,52,52}, requested shape:{1,3,85,52,52}
`

Meanwhile, looking with ONNX GraphSurgeon at the problematic node seems to indicate it should accept dynamic batch sizes. It looks like the data input to the Reshape block is (-1, 255, 52, 52) and the output shape is (-1, 3, 85, 52, 52). Since (255 * 52 * 52)==(3 * 85 * 52 * 52), you would expect that during runtime, ORT would make the first axis values both equal to the batch size, but apparently that is not the case. 

Image of values interpreted by GraphSurgeon when loading the model:

![image](https://user-images.githubusercontent.com/55059536/152407095-d731dc74-4653-436e-ae44-4dffa4f604ea.png)

Netron View:
![image](https://user-images.githubusercontent.com/55059536/152410567-79987c1e-2e7b-470d-9693-7b44e70520c8.png)

- Am i missing something?
- Could there be any alteration i could make to this model to fix such an issue?

**System information**
- OS: MacOS Monterey 12.1
- Onnxruntime Version: onnxruntime==1.10.0 (installed from pypi)
- Python version: Python 3.8.12

**Comment by skottmckay** [comment]
Are you able to share the model? Not sure how to interpret the graph surgeon output. I would have expected the second input to the Reshape node to be the requested shape but your screen capture seems to say that has shape [-1] (vs [5] if that provided a requested shape value of {-1, 3, 85, 52, 52}. 

<img width="296" alt="image" src="https://user-images.githubusercontent.com/979079/152439900-009d7dc0-85c7-4295-a3f2-99b57273ad03.png">

**Comment by Naveassaf** [comment]
Thanks for the quick reply! Unfortunately i cannot share the model. 

The shape (second) input to the reshape block is expected to be the number of dimensions of the output shape? Didnt get that from the ONNX IR docs... I have tried manually setting the second input to [5] as you suggested (using GraphSurgeon) and am still hitting the same error. Attaching a screenshot of the updated relevant node based on GS output.

![image](https://user-images.githubusercontent.com/55059536/152563960-16e64dca-2d8c-46b7-b885-f8d4ac4ed0c8.png)


Following your suggestion, I have tried using ONNX's shape_inference (with and without the GS alteration) and now see that the value of the shape input of the Reshape block, as displayed by Netron, seems to be {1, 3, 85, 52, 52}. Sounds like this could be the source of the problem..? Where in the ONNX protobuf would this value be stored? Any other suggestions as to where you would continue looking if you did have the model would be appreciated. Thanks again!

![image](https://user-images.githubusercontent.com/55059536/152565575-21e4fd06-507c-4b1a-be67-3c959206e6e2.png)

**Comment by skottmckay** [comment]
I meant that [5] would be the shape of the value and it would have 5 elements to provide the dimensions for the Reshape.

Your issue is that '791' is a constant with a fixed value of 1 for the first dimension. It needs to adjust to the batch size. You could try updating the value of the constant to have a -1 for the first dimension instead of 1.

**Comment by Naveassaf** [comment]
I appreciate the help. After having looked more into it, the model is indeed faulty and the problem was with the constant that is fed into the second input of the reshape block. Changing this constant fixed the problem.

**Comment by shifujain** [comment]
@[Naveassaf](https://github.com/Naveassaf), 

> I appreciate the help. After having looked more into it, the model is indeed faulty and the problem was with the constant that is fed into the second input of the reshape block. Changing this constant fixed the problem.

Can you please elaborate on what exactly helped you fix this issue? I am facing a similar problem with a reshape node in my model with its shape being a constant of value 60. It needs to be adjusted to [bs, 60].

```
shape
name: 4040
kind: Constant
type: int64[1]
[
60
]
```
Thank you!

**Comment by Naveassaf** [comment]
> 

Unfortunately, I dont believe my fix will be relevant for you.. I was simply changing the wrong value within a correctly shaped tensor while you seems to be trying to reshape (unsqueeze) the tensor.

**Comment by shifujain** [comment]
Actually, I am trying to write a 3D tensor in a loop over time_steps. The code works fine in PyTorch but fails in dynamic batch sizing.

`att_ta[decoder_time_step, :, :] = torch.reshape(o_weights, shape=[ -1, enc_len])
`
`Non-zero status code returned while running Reshape node. Name:'Reshape_3102' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:40 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{2,60}, requested shape:{60}
`
I tried reshaping o_weights to {-1,60}, but while running ONNX conversion it automatically adds another reshape node which converts it back to {60}. 
So far, I have not been able to figure out how the extra reshape node is getting added to the ONNX graph. Any suggestions on how this can be fixed?

**Comment by Priyanshu88** [comment]
@Naveassaf I am facing the similar kind of issue and the error log is:`[E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Reshape node. Name:'/Reshape_17_output_0_ReduceMax_Reshape' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:44 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) input_shape_size == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{0,1}, requested shape:{1}`. Can you please assist me on this problem!
