### ISSUE TITLE
PropagateCastOps uses and modifies 3 global containers at runtime

### ISSUE THREAD

**Issue by yuslepukhin** [microsoft/onnxruntime#10473]
**Describe the bug**
`PropagateCastOps` transformer makes use of 3 global containers at runtime. This presents a risk that two or more models being loaded at the same time can have side effects on each other's optimizations as different instances of the transformer modify the same global structures. This may also result in data corruption. Specific containers in question:
* [fp16_allow_ops](https://github.com/microsoft/onnxruntime/blob/ef7b4dc05cae1084546ff7caba048a2f908ac1d8/onnxruntime/core/optimizer/propagate_cast_ops.cc#L72) cleared and populated at construction time
* [inserted_node_names](https://github.com/microsoft/onnxruntime/blob/ef7b4dc05cae1084546ff7caba048a2f908ac1d8/onnxruntime/core/optimizer/propagate_cast_ops.cc#L103) used at runtime and cleared at the end of each run
* [converted_node_names](https://github.com/microsoft/onnxruntime/blob/ef7b4dc05cae1084546ff7caba048a2f908ac1d8/onnxruntime/core/optimizer/propagate_cast_ops.cc#L104)  used at runtime and cleared at the end of each run

**Urgency**
IMHO, this must be fixed before the release time

**System information**
Generic code

**Comment by satyajandhyala** [comment]
The graph transformer is not designed to be thread safe. It is originally designed to be used in training flow only if the user explicitly specifies the options on ORTModule to perform cast propagation. I understand ORTModule training flow instantiates TrainingSession only once per process.
Having said that, I will make this graph transformation thread safe by replacing file-scope (static) non-constant variables with automatic variables.
