### ISSUE TITLE
C++ OnnxRuntime_GPU: Session Run throws an access violation exception

### ISSUE THREAD

**Issue by zerovirus123** [microsoft/onnxruntime#10472]
**Describe the bug**
I am writing a .dll extension that takes in NumPy images from Python and performs inference on them. The inference works fine on a CPU session.  

I then used the CUDA provider in hopes of getting a speedup, using the default settings.

```
    Ort::Session OnnxRuntime::CreateSession(string onnx_path) {
	// Don't declare raw pointers in the headers and try to return a reference here.
	// ORT will throw an access violation.

	Ort::Env env;
	Ort::SessionOptions session_options;
	OrtCUDAProviderOptions cuda_options;
	cuda_options.device_id = 0;
	cuda_options.cudnn_conv_algo_search = OrtCudnnConvAlgoSearchExhaustive;
	cuda_options.gpu_mem_limit = static_cast<int>(SIZE_MAX * 1024 * 1024);
	cuda_options.arena_extend_strategy = 1;
	cuda_options.do_copy_in_default_stream = 1;
	cuda_options.has_user_compute_stream = 1;
	cuda_options.default_memory_arena_cfg = nullptr;
	session_options.AppendExecutionProvider_CUDA(cuda_options);

	session_options.SetGraphOptimizationLevel(
		GraphOptimizationLevel::ORT_ENABLE_EXTENDED);

	wstring widestr = std::wstring(onnx_path.begin(), onnx_path.end());
	const wchar_t* onnx_path_widecstr = widestr.c_str();
	Ort::Session _session = Ort::Session(env, onnx_path_widecstr, session_options);
	return _session;
    }
```

I got a violation access exception when trying to run the session.

```
    Windows fatal exception: access violation

    Thread 0x000058e0 (most recent call first):
      File "C:\Users\Deployment\.conda\envs\sw_2021\lib\concurrent\futures\thread.py", line 78 in _worker
      File "C:\Users\Deployment\.conda\envs\sw_2021\lib\threading.py", line 870 in run
      File "C:\Users\Deployment\.conda\envs\sw_2021\lib\threading.py", line 926 in _bootstrap_inner
      File "C:\Users\Deployment\.conda\envs\sw_2021\lib\threading.py", line 890 in _bootstrap
```
**Urgency**
Moderately urgent. There is no hard deadline but this is a bottleneck for the rest of my projects. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): binary (Microsoft.ML.OnnxRuntime.GPU from the NuGet installer)
- ONNX Runtime version: 1.10.0
- Python version: 3.7.11
- Visual Studio version (if applicable): VS 2019
- GCC/Compiler version (if compiling from source): MSVC Version 19.16.27043 for x86
- CUDA/cuDNN version: CUDA10.2/CUDNN7.6.5
- GPU model and memory: GeForce RTX2080 Ti 

**To Reproduce**

The code would not run without the model, data and suitable infrastructure (which I cannot share). However, the main inference code is shown below.

```
py::dict run(string onnx_path, py::dict images, py::list image_stats, py::list np_labels) {
	DataLoader dataloader = DataLoader(images, image_stats, np_labels);
	
	std::vector<string> labels = dataloader.GetLabels();
	unordered_map<int, cv::Mat> frames = dataloader.GetImages();

	OnnxRuntime onnx = OnnxRuntime();
	Ort::Session session = onnx.CreateSession(onnx_path);

	//as of 4th Feb 2022 Onnx only supports allocation on the CPU
	Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu( 
		OrtAllocatorType::OrtArenaAllocator, OrtMemType::OrtMemTypeDefault);

	//onnx.SessionInfo(&session);
	Ort::TypeInfo inputTypeInfo = session.GetInputTypeInfo(0);
	auto inputTensorInfo = inputTypeInfo.GetTensorTypeAndShapeInfo();
	Ort::TypeInfo outputTypeInfo = session.GetOutputTypeInfo(0);
	auto outputTensorInfo = outputTypeInfo.GetTensorTypeAndShapeInfo();

	std::vector<int64_t> inputDims = inputTensorInfo.GetShape();
	std::vector<int64_t> outputDims = outputTensorInfo.GetShape();
	size_t inputTensorSize = vectorProduct(inputDims);
	size_t outputTensorSize = vectorProduct(outputDims);
	std::vector<float> inputTensorValues(inputTensorSize);
	std::vector<float> outputTensorValues(outputTensorSize);

	Ort::AllocatorWithDefaultOptions allocator;
	const char* inputName = session.GetInputName(0, allocator);
	const char* outputName = session.GetOutputName(0, allocator);

	py::dict results;

	for (const auto& [id, frame] : frames) {
		std::vector<Ort::Value> inputTensors;
		std::vector<Ort::Value> outputTensors;
		std::vector<const char*> inputNames{ inputName };
		std::vector<const char*> outputNames{ outputName };

		inputTensors.push_back(Ort::Value::CreateTensor<float>(
			memoryInfo, inputTensorValues.data(), inputTensorSize, inputDims.data(),
			inputDims.size()));
		outputTensors.push_back(Ort::Value::CreateTensor<float>(
			memoryInfo, outputTensorValues.data(), outputTensorSize,
			outputDims.data(), outputDims.size()));

		inputTensorValues.assign(frame.begin<float>(), frame.end<float>());

		try {
			session.Run(Ort::RunOptions{ nullptr }, inputNames.data(),
				inputTensors.data(), 1, outputNames.data(), outputTensors.data(), 1);
		}
		catch (const std::runtime_error& re) {
			std::cerr << "Runtime error: " << re.what() << std::endl;
		}
		catch (const std::exception& ex)
		{
			std::cerr << "Error occurred: " << ex.what() << std::endl;
		}

		int predId = 0;
		float activation = 0;
		float maxActivation = std::numeric_limits<float>::lowest();
		float expSum = 0;

		for (int i = 0; i < labels.size(); i++)
		{
			activation = outputTensorValues.at(i);
			expSum += std::exp(activation);
			if (activation > maxActivation)
			{
				predId = i;
				maxActivation = activation;
			}
		}

		results[id] = labels.at(predId);
	}
	return results;
}
```
The code is taken from https://github.com/leimao/ONNX-Runtime-Inference/blob/main/src/inference.cpp. 

**Expected behavior**
The .dll returns a Python dictionary with image IDs and classifications.

**Screenshots**
![Screenshot from 2022-02-04 14-47-54](https://user-images.githubusercontent.com/9401015/152491544-093b8b16-6009-49ef-8547-950b3257fcd9.png)
Expected behavior.

![Screenshot from 2022-02-04 14-52-50](https://user-images.githubusercontent.com/9401015/152492156-c6fb3883-8e4b-489b-80be-b0787043f773.png)
Error

**Additional context**
A PyTorch ResNet34 model is converted into an ONNX model which is used by the C++ OnnxRuntime. But since the model works fine for the CPU provider, I don't see why it would fail with the CUDA provider.

**Comment by zerovirus123** [comment]
Hi all,

Managed to find a solution for this problem. This is not a problem with OnnxRuntime, but instead a problem with how I passed by OrtSession around.

I moved by OrtSession initialization code from my class function to my inference code and that fixed the problem. It seems like the object lifetime of either the OrtSession, session options, OrtEnv is only limited to the function's scope. When the OrtSession is returned (as a pointer or otherwise) that object is destroyed.

What is the correct way to create an ORTSession object and returning it safely?

**Comment by zerovirus123** [comment]
Oddly enough, this is only an issue when the CUDA provider is used. If I use the CPU provider then returning a session object is not a problem.

Also, since the OrtSessions are move only objects, is it possible to transfer ownership from the called function to the calling function?

**Comment by hariharans29** [comment]
`Ort::Env env;` is defined in a local scope and will get destroyed as the function scope ends. The environment must be alive when performing inferencing (as it hosts some crucial components like the default logger). 

It is hard to say why this works for the CPU EP and not for the CUDA EP without running it through the debugger, but it is possible that some component in the CUDA EP is trying to use the default logger from the environment and the environment instance is destroyed (one possible explanation).

As a mild aside, this line doesn't seem right `cuda_options.has_user_compute_stream = 1;` especially since there is no compute stream being passed in for the CUDA EP to use. I would have expected this to be 0 to allow the CUDA EP to use its own stream.

**Comment by zerovirus123** [comment]
@hariharans29 thanks for the explanation. Would ```cuda_options.has_user_compute_stream = 1;``` slow down the CUDA runs?

**Comment by hariharans29** [comment]
> @hariharans29 thanks for the explanation. Would `cuda_options.has_user_compute_stream = 1;` slow down the CUDA runs?

No it wouldn't. But it would mean that you would have to provide the user stream for ORT to use. I suggest setting it to 0 and let ORT create and use its own stream for compute.

**Comment by hariharans29** [comment]
Closing this as it seems there is nothing left to be discussed here. Feel free to re-open if you feel otherwise.

**Comment by adnan134j2** [comment]
@hariharans29 would you please look at the issue  #11235 i shared. I am stuck at this issue since many days. Please Please help me solve this issue. 
![Capture](https://user-images.githubusercontent.com/101260877/163891320-78923968-109b-4bb0-9adf-e3b7dca3ca1f.PNG)
this is the issue i am facing while running the model on GPU. The object detection model runs perfectly on CPU.

Here is the code :


// https://github.com/microsoft/onnxruntime/blob/v1.8.2/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp
// https://github.com/microsoft/onnxruntime/blob/v1.8.2/include/onnxruntime/core/session/onnxruntime_cxx_api.h
#include <onnxruntime_cxx_api.h>

#include <opencv2/dnn/dnn.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc.hpp>

#include <chrono>
#include <cmath>
#include <exception>
#include <fstream>
#include <iostream>
#include <limits>
#include <numeric>
#include <string>
#include <vector>

template <typename T>
T vectorProduct(const std::vector<T>& v)
{
    return accumulate(v.begin(), v.end(), 1, std::multiplies<T>());
}


template <typename T>
std::ostream& operator<<(std::ostream& os, const std::vector<T>& v)
{
    os << "[";
    for (int i = 0; i < v.size(); ++i)
    {
        os << v[i];
        if (i != v.size() - 1)
        {
            os << ", ";
        }
    }
    os << "]";
    return os;
}

std::ostream& operator<<(std::ostream& os,
    const ONNXTensorElementDataType& type)
{
    switch (type)
    {
    case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_UNDEFINED:
        os << "undefined";
        break;
    case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT:
        os << "float";
        break;
    case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT8:
        os << "uint8_t";
        break;
    case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_INT8:
        os << "int8_t";
        break;
    case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT16:
        os << "uint16_t";
        break;
    case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_INT16:
        os << "int16_t";
        break;
    case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_INT32:
        os << "int32_t";
        break;
    case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_INT64:
        os << "int64_t";
        break;
    case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_STRING:
        os << "std::string";
        break;
    case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL:
        os << "bool";
        break;
    case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT16:
        os << "float16";
        break;
    case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_DOUBLE:
        os << "double";
        break;
    case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT32:
        os << "uint32_t";
        break;
    case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT64:
        os << "uint64_t";
        break;
    case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_COMPLEX64:
        os << "float real + float imaginary";
        break;
        case ONNXTensorElementDataType::
        ONNX_TENSOR_ELEMENT_DATA_TYPE_COMPLEX128:
            os << "double real + float imaginary";
            break;
        case ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_BFLOAT16:
            os << "bfloat16";
            break;
        default:
            break;
    }

    return os;
}

std::vector<std::string> readLabels(std::string& labelFilepath)
{
    std::vector<std::string> labels;
    std::string line;
    std::ifstream fp(labelFilepath);
    while (std::getline(fp, line))
    {
        labels.push_back(line);
    }
    return labels;
}

int main(int argc, char* argv[])
{
    bool useCUDA{ false };
    if (useCUDA)
    {
        std::cout << "Inference Execution Provider: CUDA" << std::endl;
    }
    else
    {
        std::cout << "Inference Execution Provider: CPU" << std::endl;
    }
    std::string instanceName{ "image-classification-inference" };
    std::string imageFilepath{ "D:\\OOOOOONNNNNXXXXX\\cpp-onnxruntime-resnet-console-app-main\\OnnxRuntimeResNet\\assets\\dog.png" };
    Ort::Env env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING, instanceName.c_str());
    Ort::SessionOptions sessionOptions;
    sessionOptions.SetIntraOpNumThreads(1);
    if (useCUDA)
    {
        OrtCUDAProviderOptions cuda_options{ 0 };
        sessionOptions.AppendExecutionProvider_CUDA(cuda_options);
    }
    sessionOptions.SetGraphOptimizationLevel(
        GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
    Ort::Session session(env, L"D:\\OOOOOONNNNNXXXXX\\cpp-onnxruntime-resnet-console-app-main\\OnnxRuntimeResNet\\assets\\model.onnx", sessionOptions);


    Ort::AllocatorWithDefaultOptions allocator;
    size_t numInputNodes = session.GetInputCount();
    size_t numOutputNodes = session.GetOutputCount();
    std::cout << "Number of Input Nodes: " << numInputNodes << std::endl;
    std::cout << "Number of Output Nodes: " << numOutputNodes << std::endl;
    Ort::TypeInfo inputTypeInfo = session.GetInputTypeInfo(0);
    auto inputTensorInfo = inputTypeInfo.GetTensorTypeAndShapeInfo();
    ONNXTensorElementDataType inputType = inputTensorInfo.GetElementType();
    std::cout << "Input Type: " << inputType << std::endl;
    Ort::TypeInfo outputTypeInfo = session.GetOutputTypeInfo(0);
    auto outputTensorInfo = outputTypeInfo.GetTensorTypeAndShapeInfo();
    ONNXTensorElementDataType outputType = outputTensorInfo.GetElementType();
    std::cout << "Output Type: " << outputType << std::endl;


    ///Things used later on
    const char* inputName = session.GetInputName(0, allocator);
    std::cout << "Input Name: " << inputName << std::endl;
    std::vector<int64_t> inputDims = inputTensorInfo.GetShape();
    std::cout << "Input Dimensions: " << inputDims << std::endl;
    const char* outputName = session.GetOutputName(0, allocator);
    std::cout << "Output Name: " << outputName << std::endl;
    std::vector<int64_t> outputDims = outputTensorInfo.GetShape();
    std::cout << "Output Dimensions: " << outputDims << std::endl;


    Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu(OrtAllocatorType::OrtArenaAllocator, OrtMemType::OrtMemTypeDefault);
    std::vector<Ort::Value> inputTensors;
    static constexpr const int width = 500;
    static constexpr const int height = 500;
    static constexpr const int channel = 3;
    std::array<int64_t, 4> input_shape_{ 1,height, width,channel };


    std::array<int64_t, 2> outputt_shape_{ 1, 8 };

    std::string img_path = "D:\\cpp-onnxruntime-resnet-console-app-main\\OnnxRuntimeResNet\\assets\\dog.jpg";
    cv::Mat imgSource = cv::imread(img_path);
    std::array<uint8_t, width* height* channel> input_image_{};
    uint8_t* input = input_image_.data();
    for (int i = 0; i < imgSource.rows; i++) {
        for (int j = 0; j < imgSource.cols; j++) {
            for (int c = 0; c < 3; c++)
            {
                //NHWC 
                if (c == 0)
                    input[i * imgSource.cols * 3 + j * 3 + c] = imgSource.ptr<uint8_t>(i)[j * 3 + 2];
                if (c == 1)
                    input[i * imgSource.cols * 3 + j * 3 + c] = imgSource.ptr<uint8_t>(i)[j * 3 + 1];
                if (c == 2)
                    input[i * imgSource.cols * 3 + j * 3 + c] = imgSource.ptr<uint8_t>(i)[j * 3 + 0];
            }
        }
    }
    inputTensors.push_back(Ort::Value::CreateTensor<uint8_t>(
        memoryInfo, input, input_image_.size(), input_shape_.data(), input_shape_.size()));
 


   // size_t outputTensorSize = vectorProduct(outputt_shape_);

    std::vector<const char*> inputNames{ inputName };
    std::vector<const char*> outputNames{ "detection_anchor_indices", "detection_boxes", "detection_classes", "detection_multiclass_scores", "detection_scores", "num_detections", "raw_detection_boxes", "raw_detection_scores" };






    std::vector<float> outputTensorValues(outputt_shape_.size());


    // inputTensors.push_back(Ort::Value::CreateTensor<uint8_t>(
       //  memoryInfo, input, input_image_.size(), input_shape_.data(), input_shape_.size()));
     /////////////////////////////////////////////////////////////////////////////////
    std::vector<Ort::Value> outputTensors;                                         //
    /////////////////////////////////////////////////////////////////////////////////

    //std::cout << "memoryInfo: " << memoryInfo << std::endl;
    //std::cout << "outputTensorValues.data(): " << outputTensorValues.data() << std::endl;
    //std::cout << "outputDims.data(): " << outputDims.data() << std::endl;
    //std::cout << "outputDims.size(): " << outputDims.size() << std::endl;
    std::cout << "memoryInfo: " << memoryInfo << std::endl;

    outputTensors.push_back(Ort::Value::CreateTensor<float>(
        memoryInfo, outputTensorValues.data(), 8,
        outputt_shape_.data(), outputt_shape_.size()));



    //std::cout << "memoryInfo: " << memoryInfo << std::endl;
    //std::cout << "inputDims.data(): " << inputDims.data() << std::endl;
    //std::cout << "inputDims.size(): " << inputDims.size() << std::endl;
    //std::cout << "memoryInfo: " << memoryInfo << std::endl;
    ///std::cout << "outputTensorValues.data(): " << outputTensorValues.data() << std::endl;
    ////std::cout << "outputTensorSize: " << outputTensorSize << std::endl;





    //std::cout << "inputNames.data(): " << inputNames.data() << std::endl;
    //std::cout << "inputTensors.data() " << inputTensors.data() << std::endl;
    //std::cout << "outputNames.data()  " << outputNames.data() << std::endl;
    //std::cout << "outputTensors.data() " << outputTensors.data() << std::endl;
    std::cout << "Done with test 1" << std::endl;

    //session.Run(Ort::RunOptions{ nullptr }, inputNames.data(),
      //  inputTensors.data(), 1, outputNames.data(), outputTensors.data(),
        //outputNames.size());
   


    try {
        session.Run(Ort::RunOptions{ nullptr }, inputNames.data(),
            inputTensors.data(), 1, outputNames.data(),
            outputNames.size());
    }
    catch (const std::runtime_error& re) {
        std::cerr << "Runtime error: " << re.what() << std::endl;
    }
}
