### ISSUE TITLE
When using CUDA device, Attempt to use DefaultLogger but none has been registered.

### ISSUE THREAD

**Issue by bvitaz-ck** [microsoft/onnxruntime#10486]
**Describe the bug**
When executing `options.AppendExecutionProvider_CUDA(0);`, application crashes and displays error "Attempt to use DefaultLogger but none has been registered."

**Urgency**
Low

**System information**
- OS Platform and Distribution: Windows 11
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.10
- .net framework: 4.7.2
- CUDA/cuDNN version: 11.6
- GPU model and memory: Quadro RTX 5000    16384MiB

**To Reproduce**
- Create .net framework 4.7.2 project
- Install nuget package Microsoft.ML.OnnxRuntime.Gpu - 1.10.0
- Copy program from https://gist.github.com/pranavsharma/939d93fc7291c5a1638bfa3b190d72e3
- Replace model file with attached model file

**Expected behavior**

**Screenshots**
![nvidia-smi output](https://user-images.githubusercontent.com/40186195/152904159-4311c148-8ab5-4615-afb6-3fdca319fab3.png)
![Output directory listing](https://user-images.githubusercontent.com/40186195/152904162-77f075f8-253b-45e0-930f-7ff2108f7f15.png)
![Error message](https://user-images.githubusercontent.com/40186195/152904165-32fd306f-346f-48e1-b89f-e21c7307331d.png)

**Additional context**

**Comment by bvitaz-ck** [comment]
Model: https://gofile.me/4tJmr/z2jwhLC75

**Comment by hariharans29** [comment]
The CUDA version you are using is not the correct requirement for ORT 1.10. ORT 1.10 requires CUDA 11.4 (but any minor version < 4 should work as well).

Please see requirements here - https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements

**Comment by bvitaz-ck** [comment]
Thank you for your response. I have removed all NVIDIA applications and drivers, and then installed CUDA 11.4.1 as shown in the screenshot. I am getting the same error message. Is there anything else I can try?

![Screenshot 2022-02-08 153332](https://user-images.githubusercontent.com/40186195/153093715-1683b7fa-9ea2-4a36-b8b7-c3a88fd84ed7.png)

**Comment by hariharans29** [comment]
Have you installed CuDNN and are the CUDA/CuDNN dlls findable via PATH ?

**Comment by bvitaz-ck** [comment]
cudnn was not properly installed. It is working now. Thank you for the help.
