### ISSUE TITLE
Release 1.7.0 build issue

### ISSUE THREAD

**Issue by kristoftunner** [microsoft/onnxruntime#10501]
**Describe the bug**
During building `element_wise_ops.cc` i got this error message several times: ` error C2039: 'end': is not a member of 'Eigen
::Map<const Eigen::Matrix<T,-1,1,,-1,1>,0,Eigen::Stride<0,0>>'`

**Urgency**
This issue is urgent, deadline: this week

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): just building the source
- ONNX Runtime version: 1.7.0
- Python version: -
- Visual Studio version (if applicable): 2017
- GCC/Compiler version (if compiling from source): Visual Studio 2017 Professional
- CUDA/cuDNN version: -
- GPU model and memory: -

**To Reproduce**
- clone the repo with the tag v1.7.0
- build with this instruction: `.\build.bat --config RelWithDebInfo --build_shared_lib --parallel --cmake_generator "Visual Studio 15 2017"`

**Expected behavior**
Several compiler errors

**Screenshots**
![image](https://user-images.githubusercontent.com/41192433/153159578-63291927-0cf3-4ddc-8e5e-c75cdd988678.png)

**Additional context**
First i tried to build the latest v1.10.0 release with Visual Studio 2017, similar outcome, a LOT of compiler and linker errors, then I moved to this release, with similar outcome.

**Comment by snnn** [comment]
The latest code works well with VS 2019 and VS 2022.  Our build pipelines do not test VS 2017, so we don't officially support it.  I would suggest everyone use the latest Visual Studio when possible. 

But I guess VS 2017 still works, otherwise @[kristoftunner](https://github.com/kristoftunner) won't hit the link error: #10457
