### ISSUE TITLE
Onnxruntime infer bn node failed

### ISSUE THREAD

**Issue by wangxudong-cq** [microsoft/onnxruntime#10500]
**Describe the bug**
model:[https://github.com/onnx/models/blob/master/vision/object_detection_segmentation/duc/model/ResNet101-DUC-7.onnx](url)
Inference using onnxruntime fails after appending ["conv1_1_3x3_s2", "conv1_1_3x3_s2/bn"] to model.graph.output
```
['seg_loss', 'conv1_1_3x3_s2', 'conv1_1_3x3_s2/bn']
2022-02-09 16:13:57.305141340 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running BatchNormalization node. Name:'conv1_1_3x3_s2/bn' Status Message: Invalid input scale: NumDimensions() != 3
Traceback (most recent call last):
  File "/home/wang/wangxudong/RPP_iTest/netmodel/test.py", line 45, in <module>
    ort_array = ort_session.run(ort_outnames, ort_ins)
  File "/usr/local/anaconda3/envs/ubuntu/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running BatchNormalization node. Name:'conv1_1_3x3_s2/bn' Status Message: Invalid input scale: NumDimensions() != 3
```

**Urgency**
The model cannot be split by nodes

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS
- ONNX Runtime installed from (source or binary):python3 -m pip
- ONNX Runtime version: Version: 1.8.0
- Python version: Python 3.8.10
- Visual Studio version (if applicable): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: None
- GPU model and memory: None

**To Reproduce**
```
    ort_ins={}
    in_file = "/home/wang/wangxudong/RPP_iTest/netmodel/save_model_all_nodes/ResNet101-DUC-7/test_data_set_0/input_0.pb"
    tensor = onnx.TensorProto()
    with open(in_file, "rb") as f:
        tensor.ParseFromString(f.read())
    ort_array = onnx.numpy_helper.to_array(tensor)
    ort_ins.update({"data":ort_array})

    modelFile = "/home/wang/wangxudong/RPP_iTest/netmodel/model_zoo/ResNet101-DUC-7/ResNet101-DUC-7.onnx"
    model = onnx.load_model(modelFile)
    ort_outnames = ["conv1_1_3x3_s2","conv1_1_3x3_s2/bn"]
    model.graph.output.extend([onnx.ValueInfoProto(name=x) for x in ort_outnames])
    ort_session = ort.InferenceSession(model.SerializeToString())
    ort_outnames = [x.name for x in ort_session.get_outputs()]
    print(ort_outnames)

    ort_results = {}
    ort_outshapes = {}
    ort_array = ort_session.run(ort_outnames, ort_ins)
    ort_results = OrderedDict(zip(ort_outnames, ort_array))
    for k,v in ort_results.items():
        ort_outshapes.update({k:v.shape})
    print(ort_outshapes)
```

**Expected behavior**
Onnxruntime infer all nodes successed

**Screenshots**
None

**Additional context**
None

**Comment by snnn** [comment]
@[oliviajain](https://github.com/oliviajain), will you be able to help? The model is in our TensorRT perf tests. So I believe ONNX Runtime can run it without problems.  Most likely @wangxudong-cq fed in wrong shape.

**Comment by wangxudong-cq** [comment]
@snnn you can reproduce the issue by referring to my script! And i think it is a issue with [https://github.com/microsoft/onnxruntime/issues/10044](url)

**Comment by zhanghuanrong** [comment]
I think 
model.graph.output.extend([onnx.ValueInfoProto(name=x) for x in ort_outnames])

Do not give correct value information. Basically you need to a ShapeInference on the model, and get shape information from its valueinfos after shapeinference.

**Comment by snnn** [comment]
I guess the model is from ONNX model zoo? Please save your modified model to disk, and run ONNX model checker with it.  
https://github.com/onnx/onnx/blob/main/docs/PythonAPIOverview.md

And reopen this issue if ONNX thinks the model is valid but ONNX Runtime can't run it.
