### ISSUE TITLE
Attempt to statically quantize BERT with `percentile` schema results in out of memory

### ISSUE THREAD

**Issue by mfuntowicz** [microsoft/onnxruntime#10503]
Hello there 👋🏻,

I'm trying to statically quantize BERT through ONNX Runtime with a `percentile` calibration method (`entropy` results in the same). but I consume a huge amount of memory (>= 256Gb + 32Gb swp) and it's always being killed by the OS (see below).

I was wondering if there is anything that might be leaking somewhere? Or is it expected to consume so much memory?

```python
{
          per_channel=True,
          seed=42,
          opt_level=0,
          optimize_model=True,
          calibration_method="minmax",
          quant_format="qdq",
          activation_type="int8",
          weight_type="int8",
          quantization_approach="static",
          calib_batch_size=1,  # Required <= 1 otherwise OOM even with minmax
          max_samples=512,
          op_types_to_quantize=["MatMul", "Add"],
          extra_options={'ActivationSymmetric': False, 'WeightSymmetric': True, 'OpTypesToExcludeOutputQuantizatioin': ['MatMul', 'Add'], 'QDQOpTypePerChannelSupportToAxis': {'MatMul': 1}}

}
```

tagging @yufenglee about quantization 🙏🏻 

Thanks a lot!
Morgan

![image](https://user-images.githubusercontent.com/2241520/153181791-a3c86ba8-2afc-4b55-84ac-399fbb32d161.png)

**Comment by mfuntowicz** [comment]
Reducing the number of samples to `32` requires 123Gb of memory which seems to fit, but might not be sufficient to correctly calibrate the model. 

I assume the consumption comes from all the intermediate values that need to be stored in order to generate the distributions.

**Comment by yufenglee** [comment]
Here is an example to split the data to multiple stride: 
https://github.com/microsoft/onnxruntime-inference-examples/blob/ba19aa8f14366aaf8d43374320a897bf98f695f8/quantization/nlp/bert/trt/e2e_tensorrt_bert_example.py#L249

**Comment by mfuntowicz** [comment]
I have been looking at this example all day long and didn't spot these lines...

Thanks a lot for pointing out !

**Comment by zhanghuanrong** [comment]
Seem solution exists. Close this. Please reopen if more help needed.
