### ISSUE TITLE
Model errors our on unsupported If operator in gradient builder

### ISSUE THREAD

**Issue by groenenboomj** [microsoft/onnxruntime#10517]
When running a model with DeepSpeed 0 and onnxruntime the model fails with the following message:
`RuntimeError: [dir]/onnxruntime/orttraining/orttraining/core/graph/gradient_builder_registry.cc:29 onnxruntime::training::GradientDef onnxruntime::training::GetGradientForOp(const onnxruntime::training::GradientGraphConfiguration&, onnxruntime::Graph*, const onnxruntime::Node*, const std::unordered_set<\
std::__cxx11::basic_string<char> >&, const std::unordered_set<std::__cxx11::basic_string<char> >&, const onnxruntime::logging::Logger&, std::unordered_set<std::__cxx11::basic_string<char> >&) gradient_builder != nullptr was false. The gradient builder has not been registered: If for node If_3216`

Is this a known issue or is there a plan to add support for the `If` node in the gradient builder?

It is interrupting a workflow.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.6 LTS
- ONNX Runtime installed from (source or binary): source, built from tips
- ONNX Runtime version: 1.11
- Python version: 3.8.12
- ROCm version: 4.5.2
- GCC: 7.5.0

**Comment by thiagocrepaldi** [comment]
@groenenboomj 

* Could you provide a full repro?
* How did you get the ONNX model? Did you use ORTModule or ORTTrainer?
* Does your model use torch script in it?

Both ORT frontends use pytorch tracing for creating an onnx graph, which probably wouldn' t emit `If` nodes

**Comment by groenenboomj** [comment]
The repo is a just running huggingface RoBERTa XXL with ORT and DeepSpeed 0 layered on.  The issue only comes up with the addition on DeepSpeed.  I can get a reproducer up for the discussion of the issue.

Am I correct in understanding that the resolution is to remove the If node?

**Comment by jambayk** [comment]
Hello, have you found a fix for this issue? I get a similar issue when using ORTTraininer from huggingface optimum (which essentially wraps the model with ORTModule) on a huggingface `roberta-large` model.

**Comment by ashbhandare** [comment]
@groenenboomj could you attach the exported model here?

**Comment by iK1D** [comment]
Could you please try using latest nightly onnxruntime-training (pip install --pre --no-deps --no-index onnxruntime-training -f https://onnxruntimepackages.z14.web.core.windows.net/onnxruntime_nightly_cu113.html) to see if this issue is solved or not? https://github.com/microsoft/onnxruntime/pull/10970 might already fix this.

**Comment by baijumeswani** [comment]
Seems resolved now. Closing this as complete.
