### ISSUE TITLE
.NET onnxruntime Protobuf parsing failed

### ISSUE THREAD

**Issue by grammophone** [microsoft/onnxruntime#10525]
**Describe the bug**
I get an `OnnxRuntimeException` with message " Protobuf parsing failed" for a small model converted from TF/Keras 2.7, exported as ONNX, opening successfully in Netron as seen below, which reports format "ONNX v4", containing only vanilla convolution, dense and maxpool operators in it. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64
- ONNX Runtime installed from (source or binary):  Microsoft.ML.OnnxRuntime.DirectML from Nuget
- ONNX Runtime version: 1.10.0
- Visual Studio version (if applicable): 2019

**To Reproduce**
Try opening an `InferenceSession` using the model in the attached zip file, then you get the exception. Netron is fine with it.

**Expected behavior**
File should be able to be opened since Netron opens it correctly detecting "ONNX v4" format, or at least we should have a more descriptive error.

**Screenshots**

![image](https://user-images.githubusercontent.com/2425684/153543109-327f383e-f7f0-4237-9f45-222dd439e8e1.png)
[OrientationOriginalModel13.zip](https://github.com/microsoft/onnxruntime/files/8046187/OrientationOriginalModel13.zip)

Thank you for your help.

**Comment by grammophone** [comment]
I suspect that the problem is that model is saved as text-format protobuf.

**Comment by snnn** [comment]
We don't support text-format.

**Comment by grammophone** [comment]
Thank you for your answer. Have a good day.

**Comment by rghavimi** [comment]
Coming across a similar error when trying to use an ONNX model generated by optimum:

optimum-cli export onnx --model avsolatorio/GIST-small-Embedding-v0 --optimize O3 --device cpu --library-name transformers --trust-remote-code gist_quantized_fp16_O3_vcpu_tranformers/

- Transformers version: 4.39.1
- Platform: Linux-5.15.0-1055-aws-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.22.1
- Safetensors version: 0.4.2
- Accelerate version: 0.23.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Tensorflow version (GPU?): 2.14.0 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed

onnx==1.15.0
onnxruntime-gpu==1.17.1
optimum==1.18.0

Getting the following error when trying when opening an InferenceSession using the model:

[ErrorCode:InvalidProtobuf] Load model from ... failed:Protobuf parsing failed.
