### ISSUE TITLE
Onnx runtime accuracy result

### ISSUE THREAD

**Issue by Shawn314** [microsoft/onnxruntime#10540]
My Issue from. https://github.com/onnx/onnx/issues/3997. Please check this link.

My question is:
How to generate accuracy result from onnxruntime for softplus.
For this use case, my runtime onnx result is same with below attachment.
![image](https://user-images.githubusercontent.com/30689370/153796739-418a109d-e11f-4d66-bcba-3ffb2e40dd8f.png)
runtime inference result
![image](https://user-images.githubusercontent.com/30689370/153825516-7d1658bf-3d33-46c2-b9f7-264d12a23de8.png)
I found this in this repo.
![image](https://user-images.githubusercontent.com/30689370/153831164-eed24651-56cf-41d7-bde6-4a24102a19ba.png)
I use this formula to simulate the calculation, I got correct result. 
![image](https://user-images.githubusercontent.com/30689370/153831180-b1aa3925-c443-47d8-9483-65f5bbd957a7.png)

**Comment by henrywu2019** [comment]
what is your numpy version?

**Comment by gwang-msft** [comment]
Seems the https://github.com/onnx/onnx/issues/3997 is resolved and it's a numpy issue.
Please close this issue if you have no further issue.

**Comment by Shawn314** [comment]
@henrywu2019 Hi henry, numpy version is '1.19.5'.

**Comment by Shawn314** [comment]
From jcwchen reply.
   

> To clarify: Since ONNX doesn't have any Runtime kernel, it uses NumPy to compute result for backend data

@gwang-msft Hi gwang, so I wonder whether onnx runtime softplus compution is using numpy. How to do I can get accuuray result. If so, how to call log1p get accuracy result. Thank you!

**Comment by gwang-msft** [comment]
ONNX Runtime using its own kernel (not numpy) for computation. Have you tried ONNX Runtime and got incorrect result?

**Comment by Shawn314** [comment]
@gwang-msft, thank you for your reply. I will try it.
