### ISSUE TITLE
Provide a way to handle errors in the C++ API when exceptions are disabled

### ISSUE THREAD

**Issue by leandro-gracia-gil** [microsoft/onnxruntime#10564]
I'm using ONNX Runtime as a shared library inside a project where exceptions are disabled and enabling them is not an option. So, to avoid build errors from the throw statements I define the macro ORT_NO_EXCEPTIONS. However, doing so causes std::abort() to be called on error.

Now let's say that, as part of some other bigger process, I want to create an Ort::Session to check if a model file is fine and extract its metadata. If things go wrong, I just want to say "nope, this didn't work" and carry on. However, because exceptions are disabled, the current API provides no way to handle the error if there is a problem. The entire process just dies from the call to std::abort().

Would it be possible to provide a way to handle errors in the C++ API when exceptions are disabled?

**System information**
- ONNX Runtime version (you are using): v1.10.0

**Describe the solution you'd like**
I'd like to have some way to get an OrtStatus I can use to handle errors instead of an automatic std::abort() when exceptions are disabled. Ideally this would apply to any C++ APIs that currently have this throw on error behavior, but at the very least I'd like it when initializing Ort::Session objects and running them.

**Describe alternatives you've considered**
I've tried using the underlying APIs that Ort::Session constructors call to handle the error, but the `p_` pointer is declared as protected and cannot be accessed externally. This forces me out of the Ort::Session API.

**Comment by RyanUnderhill** [comment]
For the alternative you tried, you should be able to pass an Ort::Session to any C API function that takes an OrtSession* without accessing the p_ member. There are conversion operators in every C++ type to return the C type to make this automatic (https://github.com/microsoft/onnxruntime/blob/0c3e88944d789a6779f3722eb0cf67710b3dab3f/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L205). Does that help?

**Comment by gwang-msft** [comment]
In reality, it is not feasible to convert C++ API and all the internal code from throwing exception to returning status, plus `abort()` can happen on external code ORT are referencing.

You may try our C API, to create session with a return status.

https://github.com/microsoft/onnxruntime/blob/0c3e88944d789a6779f3722eb0cf67710b3dab3f/include/onnxruntime/core/session/onnxruntime_c_api.h#L666-L667

**Comment by leandro-gracia-gil** [comment]
@RyanUnderhill
Thanks for the suggestion, but that does not seem to work in my case. I'm trying to call (minus the ThrowOnError) is this:

https://github.com/microsoft/onnxruntime/blob/0c3e88944d789a6779f3722eb0cf67710b3dab3f/include/onnxruntime/core/session/onnxruntime_cxx_inline.h#L561

However, despite `Ort::Session` being covertible to `OrtSession*`, what I need is to pass a `OrtSession**` to receive the result, and for that I'd need direct access to the underlying pointer. Similarly, there's currently no way to create a `Ort::Session` from a `OrtSession*`, which could also solve the issue. Though I understand that this latter approach can be unsafe if you don't effectively transfer management of the pointer.

@gwang-msft 
Using the C API might be possible, but then I'll end mixing C and C++ APIs to workaround design limitations. In fact, because of the issue I just described above, this wouldn't affect just session creation but it would force me to use C APIs for anything related to sessions.

Would it be reasonable to create something like a GetLastStatus function combined with some way to disable automatic `abort()` in `ORT_CXX_API_THROW` when exceptions are disabled? The last status could then be simply set by `ThrowOnError`.

Using a GetLastStatus-like function brings in thread safety issues, although I don't know if the current C++ API is thread-safe or not. If it is, maybe storing this status information in thread-local variables could help, although I'm not familiar enough with the inner implementation details to say this confidently.

**Comment by RyanUnderhill** [comment]
Ah, I see what you mean. Since the C++ wrapper classes are just holding the individual pointers, you could reinterpret_cast<OrtSession **>(&session) but that would be dangerous if you want long term safety.

We do have this in some classes: https://github.com/microsoft/onnxruntime/blob/4f76c386862bfe6dcba5a427969f0071b95a9ab9/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L326

And we could certainly add that to the other classes to be consistent, but it won't solve your general problem of a C++ API that doesn't throw exceptions.

Since the C++ headers are simply a wrapper around the C API, you could just make a local copy of them and do a small modification to do a SetLastError approach like you mention above. Looks like all you need to do is have your own version of this macro: #define ORT_CXX_API_THROW(string, code).

We could probably modify the code so that if the user has already defined ORT_CXX_API_THROW that we won't use our own macro. To allow custom exception creation (or not using exceptions) in the client for special cases like this.

**Comment by leandro-gracia-gil** [comment]
> Since the C++ headers are simply a wrapper around the C API, you could just make a local copy of them and do a small modification to do a SetLastError approach like you mention above. Looks like all you need to do is have your own version of this macro: #define ORT_CXX_API_THROW(string, code).

Actually, that doesn't fully work either because `ORT_CXX_API_THROW` is only used in case of error, so it wouldn't catch the cases where things worked fine. Fixing that would require also changing `ThrowOnError`.
https://github.com/microsoft/onnxruntime/blob/4f76c386862bfe6dcba5a427969f0071b95a9ab9/include/onnxruntime/core/session/onnxruntime_cxx_inline.h#L12

I could probably hack my way out of the headers, but if possible I'd prefer to avoid it since this adds the task of merging local changes on library updates. It's not a big task to do, but it is error-prone in the long term.

Would it be possible to figure out a good approach for this and push it upstream?

**Comment by RyanUnderhill** [comment]
I was expecting the errors to be sticky, in that it's not clearing the error when no error happens, that's something you as the user would do. So when your client code handles an error, you then clear it, then it's ready for the next error.

So, hypothetically:

`
struct OrtError { std::string error; OrtErrorCode error_code };

void SetLastOrtError(std::string error, OrtErrorCode error_code) { /* Store the error, generate an error if one is already set*/ }
OrtError GetLastOrtError() { /* Retreive the last error, and clear the error storage */ }

#define ORT_CXX_API_THROW(string, code) SetLastOrtError(string, code)
`

**Disclaimer**

This could run into cases where you'll be forced to call abort() or use some other mechanism like setjmp/etc.. to avoid having the code set an error, then instead of throwing and leaving the scope of execution, it would then call the next method which would fail/crash on the output of the previous failed function. For example, the Env::Env constructors.

So... with that said

I could probably justify doing the simple change for #ifdef ORT_CXX_API_THROW inside the ORT_NO_EXCEPTIONS block, but going beyond that would surely get pushback to just use the C API.

**Comment by leandro-gracia-gil** [comment]
I see, so then using the API would be something like...

```c++
// Clear last error.
GetLastOrtError();

Ort::Env env{ORT_LOGGING_LEVEL_WARNING, "test"};
OrtError last_error = GetLastOrtError();
if (last_error.error_code) { ... }

Ort::Session session{env, L"model.onnx", Ort::SessionOptions{nullptr}};
last_error = GetLastOrtError();
if (last_error.error_code) { ... }
```

Sounds reasonable and simple enough.

However, my current use case is not just a piece of code where I can define these extra functions before including `onnxruntime_cxx_api.h`. Rather, it's part of building a plugin that enables using ORT in a much bigger codebase and exposes its headers to other code that is not necessarily under my control. So, while I can easily add global definitions like `ORT_CXX_API_THROW` that would affect everywhere, I cannot implement these extra functions without changing the API headers or adding additional headers that should be used instead of it.

So, it would be great if these extra functions could also be added to the API, but I understand there might be pushback beyond not redefining `ORT_CXX_API_THROW`if it already exists.

Also, there's a subtle catch in the implementation of your proposal. Having `GetLastOrtError` and `SetLastOrtError` as separate functions requires a global static `OrtError` object that will run the `std::string` constructor on static initialization, which might be undesirable in some situations involving dynamic libraries that my use case also happens to hit (I'm aware of `ORT_API_MANUAL_INIT`). To avoid this an extra function would be needed:

```c++
struct OrtError {
    std::string error_message;
    OrtErrorCode error_code{ ORT_OK };
};

inline OrtError& GetStoredError() {
    static thread_local OrtError stored_error;
    return stored_error;
}

inline void SetLastError(std::string error_message, OrtErrorCode error_code) {
    GetStoredError() = OrtError{ std::move(error_message), error_code };
}

inline OrtError GetLastError() {
    OrtError last_error = std::move(GetStoredError());
    GetStoredError() = OrtError{};
    return last_error;
}
```

This way `stored_error` is allocated when loading the code, but its constructor does not run until `GetStoredError()` is called for the first time.

Then an external `#define ORT_CXX_API_THROW(string, code) Ort::SetLastError(string, code)` would indeed fix the problem. But I guess adding all that might be too much to ask.

**Comment by RyanUnderhill** [comment]
Yeah, adding all of that would be harder to justify. Plus it would assume a more specific behavior when this sounds like a very custom requirement.

I figured you'd probably want to use thread local errors (unless you know you're only using it from one thread at a time), but that's all on how you want to handle things on your side.

Why would the functions need to be inline in the header? I imagined you'd just define prototypes for them, and implement them in your cpp file. Or you could make a third header where you define your functions, #define ORT_CXX_API_THROW, and then #include onnxruntime_cxx_api.h.

If you would like the one line #ifndef change (where we will use your `ORT_CXX_API_THROW`), let us know.

**Comment by leandro-gracia-gil** [comment]
I think I'll go the third header route where I'll define my functions, then `ORT_CXX_API_THROW`, then include onnxruntime_cxx_api.h. So, if you would make the #ifndef change to be able to use my `ORT_CXX_API_THROW` that would be great. Thank you very much for your help.

By the way, if you allow me a side question, is there any particular reason why allow of this...

```c++
```

**Comment by RyanUnderhill** [comment]
Sounds like a plan. Here's the change I'll make to onnxruntime_cxx_api.h:

```#ifndef ORT_CXX_API_THROW
#define ORT_CXX_API_THROW(string, code) \
  throw Ort::Exception(string, code)
#endif 
```

To explain the preprocessor blob, we initially didn't use a magic static because we wanted the 'GetApi()' method to inline away into nothing. The magic static would require a check on every call. So that's just due to wanting zero overhead for the C++ API wrappers.

The 'ORT_API_MANUAL_INIT' was due to the static initializer happening too soon for some cases. The magic static would have avoided this, but then isn't zero overhead.


T

**Comment by leandro-gracia-gil** [comment]
I think you missed the initial `#ifndef ORT_CXX_API_THROW`, but yes, that should be it. Thank you very much!

**Comment by RyanUnderhill** [comment]
Haha, how weird, it's in there if I edit the comment, but looks like made the markup invalid by putting it after the ``` vs on the next line. I'll make a pr and mention you then.

**Comment by RyanUnderhill** [comment]
The PR is merged, so closing this issue.

**Comment by leandro-gracia-gil** [comment]
Sorry to reopen this, but the way the patch is implemented is in fact preventing me from defining my own `ORT_CXX_API_THROW`.

The issue is that I also define `ORT_NO_EXCEPTIONS` (which is the very reason I need to customize error management, because I cannot use exceptions), but as it is now you can only redefine `ORT_CXX_API_THROW` when `ORT_NO_EXCEPTIONS` is not defined.

This is how it looks like now.

```c++
#ifdef ORT_NO_EXCEPTIONS
#define ORT_CXX_API_THROW(string, code)       \
  do {                                        \
    std::cerr << Ort::Exception(string, code) \
                     .what()                  \
              << std::endl;                   \
    abort();                                  \
  } while (false)
#else
// The #ifndef is for the very special case where the user of this library wants to define their own way of handling errors.
// NOTE: This header expects control flow to not continue after calling ORT_CXX_API_THROW
#ifndef ORT_CXX_API_THROW
#define ORT_CXX_API_THROW(string, code) \
  throw Ort::Exception(string, code)
#endif
#endif
```

Instead, it should be something like this:
```c++
#ifdef ORT_NO_EXCEPTIONS
// The #ifndef is for the very special case where the user of this library wants to define their own way of handling errors.
// NOTE: This header expects control flow to not continue after calling ORT_CXX_API_THROW
#ifndef ORT_CXX_API_THROW
#define ORT_CXX_API_THROW(string, code)       \
  do {                                        \
    std::cerr << Ort::Exception(string, code) \
                     .what()                  \
              << std::endl;                   \
    abort();                                  \
  } while (false)
#endif
#else
#define ORT_CXX_API_THROW(string, code) \
  throw Ort::Exception(string, code)
#endif
```

Or alternatively, allow redefinition in both cases if you think that's more appropriate. My use case only needs to allow redefinition when `ORT_NO_EXCEPTIONS` is defined.

**Comment by leandro-gracia-gil** [comment]
@RyanUnderhill 
Sorry to ping you directly. I'm in no hurry about this, but I'd like to make sure saw my last comment since it's possible that with the issue already closed you didn't get any notification. I tried to ping you in the previous comment too, but as an edit instead of the first post, so I don't know if you were really notified.
