### ISSUE TITLE
LoadLibrary error 126 when creating CUDA session

### ISSUE THREAD

**Issue by Sl3dge78** [microsoft/onnxruntime#10563]
**Describe the bug**
I get an LoadLibrary (Win32 error 126) when creating a Cuda session through the C api.  Cpu works fine
One thing to note, is that I dont create the session on main thread. 
I could be doing something wrong, but I've followed the docs thoroughly.  
My debugger prints the following before the error occurs : 
```
Module loaded: 00007ff8`1a600000 00007ff8`1a607000   REDACTED\bin\onnxruntime_providers_shared.dll (symbols loaded)
Module loaded: 00007fff`c6b40000 00007fff`d7b2f000   REDACTED\bin\onnxruntime_providers_cuda.dll (symbols loaded)
Module loaded: 00007ff8`02c70000 00007ff8`02cf4000   C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cudart64_110.dll 
Module loaded: 00007fff`a81f0000 00007fff`b1079000   C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cublas64_11.dll 
Module loaded: 00007fff`b1080000 00007fff`c6b3c000   C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cufft64_10.dll 
Module loaded: 00007fff`94720000 00007fff`a81e9000   C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cublasLt64_11.dll 
Module unloaded: 00007fff`94720000 00007fff`a81e9000 C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cublasLt64_11.dll
Module unloaded: 00007fff`a81f0000 00007fff`b1079000 C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cublas64_11.dll
Module unloaded: 00007fff`b1080000 00007fff`c6b3c000 C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cufft64_10.dll
Module unloaded: 00007ff8`02c70000 00007ff8`02cf4000 C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cudart64_110.dll
Module unloaded: 00007fff`c6b40000 00007fff`d7b2f000 REDACTED\bin\onnxruntime_providers_cuda.dll
``` 

Which makes me believe that a cuda dll is missing, but now way to know which.  

Here are the contents of the CUDA\bin folder : 
```
bin2c.exe
compute-sanitizer.bat
crt
cu++filt.exe
cublas64_11.dll
cublasLt64_11.dll
cuda-memcheck.exe
cudafe++.exe
cudart32_110.dll
cudart64_110.dll
cufft64_10.dll
cufftw64_10.dll
cuinj64_116.dll
cuobjdump.exe
curand64_10.dll
cusolver64_11.dll
cusolverMg64_11.dll
cusparse64_11.dll
fatbinary.exe
nppc64_11.dll
nppial64_11.dll
nppicc64_11.dll
nppidei64_11.dll
nppif64_11.dll
nppig64_11.dll
nppim64_11.dll
nppist64_11.dll
nppisu64_11.dll
nppitc64_11.dll
npps64_11.dll
nvblas64_11.dll
nvcc.exe
nvcc.profile
nvdisasm.exe
nvjpeg64_11.dll
nvlink.exe
nvprof.exe
nvprune.exe
nvrtc-builtins64_116.dll
nvrtc64_112_0.dll
nvvp.bat
ptxas.exe
__nvcc_device_query.exe
```

**Urgency**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10 x64
- ONNX Runtime installed from (source or binary): Binary, downloaded from github releases.
- ONNX Runtime version: v1.10.0
- Python version: /
- Visual Studio version (if applicable): /
- GCC/Compiler version (if compiling from source): /
- CUDA/cuDNN version: v11.6
- GPU model and memory: /

**To Reproduce**
Here's the code I'm using : 
```c
    const OrtApiBase *base_api = OrtGetApiBase();
    onnx->api = base_api->GetApi(ORT_API_VERSION);

    ONNXCheckError(onnx->api, onnx->api->CreateEnvWithCustomLogger(&OrtLog, 0, ORT_LOGGING_LEVEL_WARNING, "0", &onnx->env));

    OrtSessionOptions *options;
    ONNXCheckError(onnx->api, onnx->api->CreateSessionOptions(&options));

    OrtCUDAProviderOptions cuda_options;
    cuda_options.device_id = 0;
    cuda_options.arena_extend_strategy = 1;
    cuda_options.gpu_mem_limit = (i64)(2147483648); // 2Go
    cuda_options.cudnn_conv_algo_search = OrtCudnnConvAlgoSearchExhaustive;
    cuda_options.do_copy_in_default_stream = 1;
    ONNXCheckError(onnx->api, onnx->api->SessionOptionsAppendExecutionProvider_CUDA(options, &cuda_options));
    wchar_t model_path[MAX_PATH] = {'\0'};
    swprintf(model_path, MAX_PATH, L"%S\\onnx\\%S", onnx->root_path, model_name);
    ONNXCheckError(onnx->api, onnx->api->CreateSession(onnx->env, model_path, options, &onnx->session));
    onnx->api->ReleaseSessionOptions(options);
``` 

Here's the full error message
``` provider_bridge_ort.cc:940 onnxruntime::ProviderLibrary::Get : LoadLibrary failed with error 126 "The specified module could not be found." when trying to load "D:\Guigui\Work\Mocaplab\eye_tracking\bin\onnxruntime_providers_cuda.dll" ```

**Expected behavior**
Cuda should load properly or ONNX could give a clearer error message.

**Screenshots**

**Additional context**
I'm building my program with clang with the following command line args (some irrelevant ones are omitted): 
```clang files -g  -I "include" -L "lib\x64" -lonnxruntime.lib -lonnxruntime_providers_shared.lib -lonnxruntime_providers_cuda.lib -std=c++20 -o bin\app.exe -Xlinker -pthread -SUBSYSTEM:WINDOWS```

- include\ has an onnx subfolder with the .h from the release
- lib\x64\ has all the .lib from the release
- bin\ has all the .dll from the release

**Comment by snnn** [comment]
To identify the problem:
1. Install [windbg](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools)
2.  Find the gflags.exe in the windbg install folder and start it, 

3. Select the image file tab
![image](https://user-images.githubusercontent.com/856316/74082914-91d96900-4a13-11ea-95eb-d73db8a5cf13.png)

4. Put your exe name there. Here I use python.exe as an example. Then please press the "tab" key, check "Show loader snaps" box

![image](https://user-images.githubusercontent.com/856316/74082958-b7667280-4a13-11ea-9eaf-6752695b4904.png)


5.  Start windbg, run your application
![image](https://user-images.githubusercontent.com/856316/74083043-7d49a080-4a14-11ea-90fa-2960544a3dce.png)

6. in the command windows, type "g", then press the enter key
![image](https://user-images.githubusercontent.com/856316/74083078-d285b200-4a14-11ea-9df4-e86c421c5617.png)

7. You'll see a lot of outputs in the debugging windows.  Please search the lines that have "LdrpProcessWork - ERROR: Unable to load DLL", and put the result here.
e.g.
 "cublas64_100.dll", Parent Module: "C:\intelpython3\lib\site-packages\onnxruntime\capi\onnxruntime_pybind11_state.pyd", Status: 0xc0000135


Please post the log here if you can't find the problematic DLL by yourself.

**Comment by yuslepukhin** [comment]
Recursive use of `dumpbin /DEPENDENTS` starting with onnxruntime cuda provider dll may be an option.

**Comment by Sl3dge78** [comment]
Hello!

Thank you for the reply. I ran windbg and figured out that cudnn wasn't installed properly. Instead of using the install exe I downloaded the zip, added the dlls in my path and now it give me a different error (invalid device ordinal), that I'll try to figure out on my own!  

I'm closing this issue cheers!
