### ISSUE TITLE
ORT library files are missing versions.

### ISSUE THREAD

**Issue by fkavache** [microsoft/onnxruntime#10589]
**Describe the bug**
ORT library files, **onnxruntime.dll**, **onnxruntime_providers_cuda.dll**, **onnxruntime_providers_shared.dll** and **onnxruntime_providers_tensorrt.dll** are missing version and other information. Is there any good reason behind it?

Thank you in advance.

**Screenshots**
![image](https://user-images.githubusercontent.com/29062515/154549725-47736682-3bd4-4e28-b1cb-77a6ffce2d7a.png)

**Comment by snnn** [comment]
We will fix it in the next release

**Comment by fkavache** [comment]
Thank you for your response @snnn
