### ISSUE TITLE
commit 7e092a7e3f8f9f590de0ac5548035e8fa4d512f8 caused build error

### ISSUE THREAD

**Issue by jeyblu** [microsoft/onnxruntime#10580]
**Describe the bug**

Commit 7e092a7e3f8f9f590de0ac5548035e8fa4d512f8 caused error in building onnxruntime oneDNN execution provider. The build error didn't occur in previous commit, 5df15c56444fe1b5f770eaca38d8031b5ffe151e.

```
provider_bridge_provider.cc
provider_bridge_provider.obj : error LNK2005: "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl
onnxruntime::operator<<(class std::basic_ostream<char,struct std::char_traits<char> > &,class onnxruntime::TensorShape
const &)" (??6onnxruntime@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEAV12@AEBVTensorShape@0@@Z) already defi
ned in dnnl_reduce.obj [C:\Users\MTC\source\repos\onnxruntime\build_dnnl_cpu\Debug\onnxruntime_providers_dnnl.vcxproj]
     Creating library C:/Users/MTC/source/repos/onnxruntime/build_dnnl_cpu/Debug/Debug/onnxruntime_providers_dnnl.lib a
  nd object C:/Users/MTC/source/repos/onnxruntime/build_dnnl_cpu/Debug/Debug/onnxruntime_providers_dnnl.exp
C:\Users\MTC\source\repos\onnxruntime\build_dnnl_cpu\Debug\Debug\onnxruntime_providers_dnnl.dll : fatal error LNK1169:
one or more multiply defined symbols found [C:\Users\MTC\source\repos\onnxruntime\build_dnnl_cpu\Debug\onnxruntime_prov
iders_dnnl.vcxproj]
```

**Urgency**
High, affecting code development.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): https://github.com/microsoft/onnxruntime.git
- ONNX Runtime version: master
- Python version: 3.10.1
- Visual Studio version (if applicable): 2019, 16.11.10

**To Reproduce**
Checkout commit 5df15c56444fe1b5f770eaca38d8031b5ffe151e and build. No error.
```
git clone --recursive https://github.com/microsoft/onnxruntime.git
cd onnxruntime
git checkout 5df15c564
build.bat --config Debug --build_shared_lib --build_wheel --parallel --use_dnnl --skip_tests --cmake_generator "Visual Studio 16 2019"
```
Checkout next commit, 7e092a7e3f8f9f590de0ac5548035e8fa4d512f8 and build. Build error encountered.
```
git checkout 7e092a7e3
build.bat --config Debug --build_shared_lib --build_wheel --parallel --use_dnnl --skip_tests --cmake_generator "Visual Studio 16 2019"
```

**Expected behavior**
Successful build

**Comment by RyanUnderhill** [comment]
That symbol is defined in the core code here: onnxruntime/core/framework/tensor_shape.cc
But it's really weird that dnnl_reduce.cc would define it, since it's not defined in any headers.

You could try defining it early in dnnl_reduce.cc to cause the second definition to generate an error during compiling, just in case there is something odd going on we're luckily avoiding.

**Comment by jeyblu** [comment]
The build error occurred in building "Debug" but not in building "RelWithDebInfo".

**Comment by RyanUnderhill** [comment]
Checked in the fix linked above, closing the issue. Sorry about that!
