### ISSUE TITLE
error:TypeError: unsupported operand type(s) for ^: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by chuangzhidan** [microsoft/onnxruntime#10593]
**Describe the bug**
When i **executed  code _In [7]_ in colab env, error occurs:**
**2. Export the loaded model
Once the model is loaded, we can export the loaded PyTorch model to ONNX.**

TypeError                                 Traceback (most recent call last)
[<ipython-input-49-fc4074ea6605>](https://localhost:8080/#) in <module>()
      8                  do_constant_folding=True,
      9                  input_names=['input_ids','input_mask','segment_ids'],
---> 10                  output_names=['start','end']
     11 )
     12         print("Model exported at ", export_model_path)

1 frames
[/usr/local/lib/python3.7/dist-packages/torch/onnx/utils.py](https://localhost:8080/#) in export(model, args, f, export_params, verbose, training, input_names, output_names, aten, export_raw_ir, operator_export_type, opset_version, _retain_param_name, do_constant_folding, example_outputs, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, custom_opsets, enable_onnx_checker, use_external_data_format)
     79     if aten or export_raw_ir:
     80         assert operator_export_type is None
---> 81         assert aten ^ export_raw_ir
     82         operator_export_type = OperatorExportTypes.ONNX_ATEN if aten else OperatorExportTypes.RAW
     83     elif operator_export_type is None:

**TypeError: unsupported operand type(s) for ^: 'NoneType' and 'int'**
**Urgency**
no hard deadlines

**System information**
- ONNX Runtime installed from (binary):

**Comment by gwang-msft** [comment]
Seems this is a PyTorch Converter issue, please open the issue on https://github.com/pytorch/pytorch/issues
