### ISSUE TITLE
how to get DML device index of specified card

### ISSUE THREAD

**Issue by StayYouth1993** [microsoft/onnxruntime#10606]
I could get gpu device card list and card info through wmi, I don't know how onnxruntime with dml backend index mean. I could only test this on my own computer by watching the gpu card ocupation on windows manager.

by the way, I use python wrapper, python version is 3.7.4

**Comment by fdwr** [comment]
@StayYouth1993: The device id list just corresponds to what Windows DXGI returns [IDXGIFactory::EnumAdapters(https://docs.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgifactory-enumadapters), (which includes all GPU's, not just Nvidia). On a single GPU machine, device id is always 0, and on a machine with multiple GPU's, device id = 0 is typically the integrated GPU and id = 1 the discrete card (e.g. Intel for id 0, Nvidia for id 1). I'm unsure the best way to reach that from Python, but I found this [coalpy library](https://kecho.github.io/coalpy/coalpy.gpu.html) with a promising-sounding `get_adapters()` function. Does that work?

**Comment by StayYouth1993** [comment]
I'll take a try, thank you for your patience answer!
