### ISSUE TITLE
How to Create String Tensor Properly Using C API?

### ISSUE THREAD

**Issue by GuanLuo** [microsoft/onnxruntime#1060]
Hi, I am using the C API of Onnx Runtime. It seems like I can use `OrtCreateTensorWithDataAsOrtValue()` to create String tensor, but I notice that the data being passed to the function is an array of string. I have heard that passing STL objects across shared library boundary is not a good practice, is that a valid concern in this case?

**Comment by snnn** [comment]
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_inference.cc#L266

**Comment by GuanLuo** [comment]
Thanks.
