### ISSUE TITLE
Yolov3 Pytorch

### ISSUE THREAD

**Issue by gwestner94** [microsoft/onnxruntime#1063]
Is there any example of using yolov3 trained in pytorch (e.g https://github.com/ultralytics/yolov3) or the original darknet yolov3 in the onnx runtime? 

When testing the pretrained model from https://github.com/ultralytics/yolov3,
 I keep having trouble applying the correct pre/ postprocessing operations (output parsing, nms) to replicate the pytorch output.

Thx
Georg

**Comment by EmmaNingMS** [comment]
there is Yolov3 in ONNX model zoo. https://github.com/onnx/models/tree/master/yolov3

**Comment by linkerzhang** [comment]
we're having a notebook for it in the progress https://github.com/vinitra/onnx-docker/blob/object-detect-demo/onnx-ecosystem/inference_demos/Yolov3_Object_Detection_ONNXRuntime.ipynb. @vinitra

**Comment by faxu** [comment]
@gwestner94 Does that example notebook help with the pre/post-processing logic to replicate the output in the pytorch version? We've had success with it using the model zoo version wrt accruacy and correctness.

**Comment by gwestner94** [comment]
@linkerzhang  Thank you I will try to apply the logic of the notebook.

@faxu The pytorch model is a bit different especially because the whole nms process isn't included in the graph like in the keras version. So the outputs differ in that no 'Indices' output is given.

I will give an update when I figure out how to apply it.

**Comment by faxu** [comment]
@gwestner94 - any update on this? let us know if you need more assistance

**Comment by rlewkowicz** [comment]
@gwestner94 

https://github.com/ultralytics/yolov3
