### ISSUE TITLE
Issue using NNAPI on Android device

### ISSUE THREAD

**Issue by ashwinjoseph95** [microsoft/onnxruntime#10660]
Hi,
I was using the shared library files available from the zip file in release section here to make an inference with two output values and was able to successfully get outputs via onnxruntime on the Android device.

![image](https://user-images.githubusercontent.com/30999857/155495687-b053513f-388b-4077-9315-a97aafc81e7a.png)

Then I tried to bring in NNAPI, by including the headers and adding the flags in my cpp code as follows:

```

    Ort::Env env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING,
                 instanceName.c_str());
    Ort::SessionOptions sessionOptions;
    uint32_t nnapi_flags = 0;
    nnapi_flags |= NNAPI_FLAG_USE_FP16;
    //nnapi_flags |= NNAPI_FLAG_CPU_DISABLED;
    //nnapi_flags |= NNAPI_FLAG_CPU_ONLY;
    Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_Nnapi(sessionOptions, nnapi_flags));
    sessionOptions.SetIntraOpNumThreads(1);

    sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
    //sessionOptions.AddConfigEntry("session.load_model_format", "ORT");

    Ort::Session session(env, modelFilepath.c_str(), sessionOptions);

    Ort::AllocatorWithDefaultOptions allocator;
```
but I am facing an issue saying:

```
terminating with uncaught exception of type Ort::Exception: model_builder.cc:369 RegisterModelOutputs shape_proto cannot be null for output: Affine_3
Aborted 
```
Not sure why, upon adding NNAPI related headers and flags is causing the issue. Any guidance on solving the same will be helpful.
My Android API version for the device is 30 and ABI is arm64-v8a.

**Comment by ashwinjoseph95** [comment]
My bad, I was trying to inference using an ort file with optimization level: all. switching it to basic mode resolved the issue. 
I would like to get a clarification as to whether the use_nnapi flag mentioned in https://onnxruntime.ai/docs/reference/ort-model-format.html is needed for convert onnx model to ort. It was not working for my case, hence the query.

Also kindly advice on how to assign different hardware accelerators for different operations in the NN graph. The Google's Android NNAPI documentation does mention about it. How can we do it on onnxruntime as well?

**Comment by skottmckay** [comment]
You don't need the `--use-nnapi` flag and it's actually removed in the latest ORT version as we have runtime optimizations that make it unnecessary. 

There's currently no way to assign specific accelerators for different operations in the graph. There is a flag to prevent NNAPI using CPU though. 

https://github.com/microsoft/onnxruntime/blob/3f42665a40f1e3a655a9703ae668d903fbcd87d7/include/onnxruntime/core/providers/nnapi/nnapi_provider_factory.h#L39
