### ISSUE TITLE
run time

### ISSUE THREAD

**Issue by cqray1990** [microsoft/onnxruntime#10676]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:1.6
- Python version:3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:cuda 10.2/8.0
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

when i run the same code to inference for  qoo times ,
at the first time it costs  3.53,second time is 0.111,wht the first need 3.53,that's not balance of tme

3.537665605545044
0.11125826835632324
0.08307480812072754
0.08356046676635742
0.08286333084106445
0.0826883316040039

**Comment by snnn** [comment]
The first iteration has a lot of things to do. When people do benchmark usually they will not measure the first one, or do a couple of warm up first. This is a general principal for all perf benchmarks. 

See #10608 also.
