### ISSUE TITLE
run time at the first time

### ISSUE THREAD

**Issue by cqray1990** [microsoft/onnxruntime#10683]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:1.6
- Python version:3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.2/8.0
- GPU model and memory:2080ti

i try to test code for 100 times ,but the first is so slow
3.537665605545044
0.11125826835632324
0.08307480812072754
0.08356046676635742
0.08286333084106445
0.0826883316040039

and u set CUDA like this in code : is it normal?
  self.sess = rt.InferenceSession(MODEL_PATH)
  #way1
  self.sess.set_providers(['CUDAExecutionProvider'], [ {'device_id': 0}])

**Comment by yuslepukhin** [comment]
Perhaps, this is [related](https://github.com/microsoft/onnxruntime/issues/10608) ?

**Comment by faxu** [comment]
See: https://github.com/microsoft/onnxruntime/issues/10746
Please reactivate if this does not resolve your issue.
