### ISSUE TITLE
Local function with If: GraphProto attribute inferencing is not enabled in this InferenceContextImpl instance.

### ISSUE THREAD

**Issue by jantonguirao** [microsoft/onnxruntime#10698]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.

Error when running a model with a model local function and an operator containing graph arguments (e.g. If).
```
Traceback (most recent call last):
  File "test_fn_if.py", line 74, in <module>
    session = onnxruntime.InferenceSession('test_fn_if.onnx', None)
  File "/home/janton/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/janton/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 368, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from test_fn_if.onnx failed:Node () Op (fn) [TypeInferenceError] GraphProto attribute inferencing is not enabled in this InferenceContextImpl instance.

```

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04.3 LTS
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.10.0
- Python version: Python 3.8.10
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.
```
import onnx
from onnx import numpy_helper
from onnx import checker
import numpy as np
import onnxruntime
from onnx import FunctionProto

then_out = onnx.helper.make_tensor_value_info('then_out', onnx.TensorProto.FLOAT, [5])
else_out = onnx.helper.make_tensor_value_info('else_out', onnx.TensorProto.FLOAT, [5])

x = np.array([1, 2, 3, 4, 5]).astype(np.float32)
y = np.array([5, 4, 3, 2, 1]).astype(np.float32)

then_const_node = onnx.helper.make_node(
    'Constant',
    inputs=[],
    outputs=['then_out'],
    value=onnx.numpy_helper.from_array(x)
)

else_const_node = onnx.helper.make_node(
    'Constant',
    inputs=[],
    outputs=['else_out'],
    value=onnx.numpy_helper.from_array(y)
)

then_body = onnx.helper.make_graph(
    [then_const_node],
    'then_body',
    [],
    [then_out]
)

else_body = onnx.helper.make_graph(
    [else_const_node],
    'else_body',
    [],
    [else_out]
)

if_node = onnx.helper.make_node(
    'If',
    inputs=['f_cond'],
    outputs=['f_res'],
    then_branch=then_body,
    else_branch=else_body
)

f = FunctionProto()
f.domain = 'custom'
f.name = 'fn'
f.input.extend(['f_cond'])
f.output.extend(['f_res'])
f.node.extend([if_node])
f.opset_import.extend([onnx.helper.make_opsetid("", 14)])


graph = onnx.helper.make_graph(
    nodes=[onnx.helper.make_node('fn', domain='custom', inputs=['cond'], outputs=['res'])],
    name='graph',
    inputs=[onnx.helper.make_tensor_value_info('cond', onnx.TensorProto.BOOL, [])],
    outputs=[onnx.helper.make_tensor_value_info('res', onnx.TensorProto.FLOAT, [5])],
)

m = onnx.helper.make_model(graph, producer_name='test',
                           opset_imports= [onnx.helper.make_opsetid("", 14), onnx.helper.make_opsetid("custom", 1)])
m.functions.extend([f])

onnx.checker.check_model(m)
print(m)

onnx.save(m, 'test_fn_if.onnx')
session = onnxruntime.InferenceSession('test_fn_if.onnx', None)

result = session.run(
    [],
    {'cond' : np.array(True)}
)

print(result)
```

**Expected behavior**
The model should run normally.

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by souptc** [comment]
@gramalingam , the error is from onnx function shape inference implementation, could you take a look?

**Comment by gramalingam** [comment]
@jantonguirao : the restructure function inliner PR added multiple tests with a model-local-function with a conditional (If) inside. See the test-cases starting from: https://github.com/microsoft/onnxruntime/blob/05c31a036d5a2932ac09fe367cfcfbb125e32fb2/onnxruntime/test/framework/function_test.cc#L128

**Comment by jantonguirao** [comment]
I checked again with the latest main branch and the issue no longer appears. Thank you!
