### ISSUE TITLE
The ONNX graph converted from tf.image.crop_and_resize() function will cause a different result by ORT nightly build.

### ISSUE THREAD

**Issue by fatcat-z** [microsoft/onnxruntime#10710]
**Describe the bug**
Install ORT nightly job. Try to execute the example script provided in this issue which is trying to inference an ONNX file generated by converting tf.image.crop_and_resize() op to ONNX via tf2onnx. The result of ORT is different than tensorflow.

**Urgency**
This is breaking tf2onnx CI pipeline so please fix it soon.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 20.04
- ONNX Runtime installed from (source or binary): pip install --index-url https://test.pypi.org/simple/ ort-nightly
- ONNX Runtime version:  ort-nightly 1.11.0.dev20220228001
- Python version: Python 3.7
- Tensorflow version: 1.13.1

**To Reproduce**

1. Download the attached zip file [crop_and_resize_failure.zip](https://github.com/microsoft/onnxruntime/files/8163158/crop_and_resize_failure.zip).
2. Unzip it and execute the command "python crop_resize_issue.py" under this folder.

**Expected behavior**
It should display Pass without any exceptions.

**Comment by pranavsharma** [comment]
- can you attach the onnx model?
- what vers of ORT gave different results?
- how much was the difference?

**Comment by yufenglee** [comment]
It should be caused by #10554. Here is the fix #10824 in review.

**Comment by RandySheriffH** [comment]
@yufenglee: I have build the fix and tried out, it seems the diffs are still there.
https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=198775&view=results

**Comment by RandySheriffH** [comment]
@fatcat-z : now with https://github.com/microsoft/onnxruntime/pull/10917 the diffs are gone.
