### ISSUE TITLE
Component Governance updates for branch `rel-1.9.1`

### ISSUE THREAD

**Issue by jambayk** [microsoft/onnxruntime#10733]
I am from the AI Platform Pytorch team and we are responsible for handling the ModelCompiler project. This project relies on `rel-1.9.1` branch of onnxruntime. 

Recently, we received some component governance alerts wrt onnxruntime. So, I wanted to ask if you could help us with it.

The following are the components and the recommended solutions:

## pillow
**Location:** `docs/python/requirements.txt`                     `tools/ci_build/github/linux/docker/scripts/training/ortmodule/stage2/requirements.txt`
**Root Dependencies:** `pytorch-lightning 1.3.8`, `matplotlib 3.4.3`
**Recommendation:** Upgrade Pillow from 8.3.1 to 9.0.0 to fix the vulnerability. (Although I think upgrading the root dependencies might be better)

## tensorflow
**Location:** `docs/python/requirements.txt`                     
**Root Dependencies:** `tensorflow 2.5.0`,
**Recommendation:** Upgrade tensorflow from 2.5.0 to 2.5.2 to fix the vulnerability.

## pytorch-lightning
**Location:** `tools/ci_build/github/linux/docker/scripts/training/ortmodule/stage2/requirements.txt`               
**Root Dependencies:** `pytorch-lightning 1.3.8`
**Recommendation:** A specific remediation has not been provided for this vulnerability. For managing alerts without remediation guidance, see the [Component Governance documentation](https://docs.opensource.microsoft.com/tools/cg/security-alerts.html#what-to-do-when-no-fix-is-available). For more details on the advisory that raised this alert, see the advisory link in the Resources section below.

*** 

The following seem fixable on the local machine

## node-fetch
**Location:** `js/react_native/example/yarn.lock` `js/react_native/yarn.lock`               
**Root Dependencies:** `release-it 14.6.1`, `react-native 0.63.4`
**Recommendation:** Upgrade node-fetch to 2.6.7 to fix the vulnerability.
If you are using NPM 6 or above, you can run `npm audit fix` on your local machine to fix vulnerabilities. For more info, please visit https://docs.npmjs.com/cli/audit

## simple-get
**Location:** `js/node/package-lock.json`               
**Root Dependencies:** `prebuild-install 6.1.2`
**Recommendation:** Upgrade simple-get to 3.1.1 to fix the vulnerability.
If you are using NPM 6 or above, you can run npm audit fix on your local machine to fix vulnerabilities. For more info, please visit https://docs.npmjs.com/cli/audit

*** 

The following arise from external dependencies, so they might require updating the versions we are using

## com.google.code.gson:gson 
**Location:** `cmake/external/protobuf`, `cmake/external/coremltools`
**Recommendation:** Upgrade to version com.google.code.gson:gson:2.8.9

## com.google.protobuf:protobuf-java 
**Location**: `cmake/external/coremltools`, `cmake/external/protobuf`, `tools/perf_util/pom.xml` (mysql:mysql-connector-java 8.0.22)
**Recommendation:** Upgrade com.google.protobuf:protobuf-java to 3.16.1 to fix the vulnerability.

## com.google.protobuf:protobuf-parent 
**Location:** `cmake/external/coremltools`
**Recommendation:** Upgrade com.google.protobuf:protobuf-parent to 3.15.0 to fix the vulnerability.

## mkdocs
**Location:** `cmake/external/json`
**Recommendation:** Upgrade mkdocs to 1.2.3 to fix the vulnerability.

## nltk
**Location:** `cmake/external/json`
**Recommendation:** Upgrade nltk to 3.6.6 to fix the vulnerability.

**Comment by snnn** [comment]
Sorry we will not go back and patch that version. Please try to use the latest ONNX Runtime release.
