### ISSUE TITLE
ILearningModelSessionOptionsNative for setting IntraopNumThreads not available on Windows 10

### ISSUE THREAD

**Issue by triplef** [microsoft/onnxruntime#10732]
**Describe the bug**

The `ILearningModelSessionOptionsNative` interface required for setting the IntraopNumThreads as described [here](https://docs.microsoft.com/en-us/windows/ai/windows-ml/native-apis/intraopnumthreads) seems to be only available on Windows 11, but not on Windows 10 (tested on build 19043), even though the documentation says it’s available in build 17763.

I’m not sure this is the correct place to report this, although this feature was exposed in this project in https://github.com/microsoft/onnxruntime/pull/4638, so please let me know if there’s a better place to report this.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 build 19043
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: unknown
- Visual Studio version (if applicable): 2022
- GCC/Compiler version (if compiling from source): clang 12.0.0
- CUDA/cuDNN version: unknown
- GPU model and memory: unknown

**To Reproduce**

Run the following code (here using C++/WinRT, but should also apply to other language bindings):
```c
LearningModelSessionOptions options;
auto nativeOptions = options.as<ILearningModelSessionOptionsNative>();
nativeOptions->SetIntraOpNumThreadsOverride(1);
```

This throws an exception "No such interface supported" in the second line.

**Expected behavior**
No exception is thrown.

**Additional context**
This works fine on Windows 11.

**Comment by RyanUnderhill** [comment]
Yes, there is a better place! The Windows team has a separate github for the Windows specific API: https://github.com/Microsoft/Windows-Machine-Learning

Please log the issue there and they'll be much more helpful than we were.

**Comment by triplef** [comment]
Thanks, I opened https://github.com/microsoft/Windows-Machine-Learning/issues/468.
