### ISSUE TITLE
Unable to inference on exported ONNX model - Seeing error "Non concat axis dimensions must match: Axis has mismatched dimensions"

### ISSUE THREAD

**Issue by mstfbl** [microsoft/onnxruntime#10741]
**Describe the bug**
I am working on exporting a PyTorch model to ONNX and run inferencing on the same exported ONNX model with ORT. Specifically, I export the model `210105_0.812534_relu_e3e3.pth` [here](https://github.com/mstfbl/riiid-acp-pub/blob/cfc195128727d913338891113a38bb7a576a3c6a/05_inference_no_fastai_torch_export.py#L845-L855). The dummy input being given to the model is the same as the first input given to the vanilla PyTorch vanilla, which [is a tuple of 5 Torch Tensors](https://github.com/mstfbl/riiid-acp-pub/blob/cfc195128727d913338891113a38bb7a576a3c6a/05_inference_no_fastai_torch_export.py#L968-L972). They have the following dimensions (star denotes dynamic size, as it is the batch size of the given inputs):

- x_mask : Bool(*, 500)
- x_cat : Long(*, 500, 11)
- x_cont : Float(*, 500, 23)
- x_tags : Long(*, 500, 6)
- x_tagw : Float(*, 500, 6)

Then, I convert the Torch Tensor inputs to Numpy arrays and run inferencing with `onnxruntime.InferenceSession` [here](https://github.com/mstfbl/riiid-acp-pub/blob/cfc195128727d913338891113a38bb7a576a3c6a/05_inference_no_fastai_torch_export.py#L982-L991). This is where the error below occurs:

```bash
Traceback (most recent call last):
  File "05_inference_no_fastai_torch_export.py", line 982, in <module>
    preds1 = torch.from_numpy(ort_session_1.run(
  File "/opt/conda/envs/TorchNightly/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Concat node. Name:'Concat_1355' Status Message: concat.cc:156 PrepareForCompute Non concat axis dimensions must match: Axis 1 has mismatched dimensions of 2500 and 3500
``` 

I looked into the "Concat 1355" node, and did not see mismatched dimensions. I do see that all the inputs going into "Concat 1355" haves axes "1" but the "Concat 1355" node has axis 0.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): Source-Nightly
- ONNX Runtime version: 1.11.0.dev20220214001+cu111
- Python version: 3.8.12
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 11.1/cuDNN 8.0.5
- GPU model and memory: Azure VM ND40rsV2 - 8 Tesla V100 GPUs

**To Reproduce**
1) Clone https://github.com/mstfbl/riiid-acp-pub
2) Make a new folder named "input" in the riiid-acp-pub directory, and unzip the contents of the model-data.zip into the input folder. This is the data for running training and inferencing on the model.
[Download model-data.zip](https://github.com/microsoft/onnxruntime/files/8201778/model-data.zip)

3) Run `pip install requirements.txt`, then run `01_pre.py`, then `03_pre_sub.py`, then `04_pre_validation_set.py`. Skip `02_train.py` as we we will use the pretrained provided models `210105_0.812534_relu_e3e3.pth` and `210105_0.812154_gelu_e4d4_ep30.pth` in `kaggle/root/resources`.
Note: If you have less than 128 GB RAM, you won't be able to run `01_pre.py`. In this case, please extract the contents of the zip file "riiid-pkls.zip" into the "input" folder, which is what `01_pre.ipynb` gives at the end. [Download riiid-pkls.zip](https://microsoft-my.sharepoint.com/:u:/p/mubal/EU3e3twsNgRHjjOFX4xbntEBQZDcMt-4XJMuqNDc5M-l_w?e=fWPJdp)

4) Run the following commands, as described in the repo's README:
```bash
ln input/data_500_last_interactions_v210101b.pkl kaggle_dataset/root/resources
ln input/data_attempt_num_v210101b.npy kaggle_dataset/root/resources
ln input/data_attempts_correct_v210101b.npy kaggle_dataset/root/resources
ln input/meta_v210101b.pkl kaggle_dataset/root/resources

cd kaggle_dataset
make
```
5) Run `05_inference_no_fastai_torch_export.py`. You should see the error noted above.

I've attached the original model (`210105_0.812534_relu_e3e3.pth`) that is being converted to ONNX [here](https://github.com/mstfbl/riiid-acp-pub/blob/cfc195128727d913338891113a38bb7a576a3c6a/05_inference_no_fastai_torch_export.py#L845-L855), the converted model (`model1_exported.onnx`), and the full log printout of running `05_inference_no_fast_ai_torch_export.py` that includes a printout of the exported ONNX graph into the linked ZIP for debugging below.

**Expected behavior**
I expect [this ](https://github.com/mstfbl/riiid-acp-pub/blob/cfc195128727d913338891113a38bb7a576a3c6a/05_inference_no_fastai_torch_export.py#L982)`onnxruntimeInferenceSession` to run without errors.

**Screenshots**

**Additional context**
LINKED ZIP: [Download link](https://microsoft-my.sharepoint.com/:u:/p/mubal/EbanhkkRcTtGrD7JSGHYfbUBMuTiXiMfGvtjKYbWOdCL6w?e=B8qy5P)

CC'ing those who I've previously reached out to for support on this issue
@yuslepukhin 
@thiagocrepaldi 
@harshithapv 
@askhade 
@garymm 
@alonbochman 
@liqunfu

**Comment by garymm** [comment]
@yuslepukhin can you take a look to at least determine if it's a problem with ORT vs the model?

**Comment by garymm** [comment]
@BowenBao it seems @yuslepukhin is busy with things for the ORT release.
Could you take a look to determine if it's a problem with ORT or the exported model?

**Comment by garymm** [comment]
@BowenBao determined this is an exporter issue and provided @mstfbl a model change to work-around.
Tracked internally by AB#1698160
