### ISSUE TITLE
Where is the .lib file and headers located after build from source?

### ISSUE THREAD

**Issue by dilne** [microsoft/onnxruntime#10751]
Hi, I'm trying to build from source a static library of ONNX Runtime so that I can import it into UE4, which I believe requires static libraries and not dynamic ([according to this tutorial](https://unreal.blog/how-to-include-any-third-party-library)).

I'm on Windows 10 and I build like this. Note I have omitted the build dynamic library option:

```
git clone --recursive https://github.com/Microsoft/onnxruntime
cd onnxruntime
.\build.bat --config RelWithDebInfo --parallel --cmake_generator "Visual Studio 16 2019"
```

Where are the .lib files and headers that I need located after building? I go to Build > Windows > RelWithDebInfo but after that I'm none-the-wiser on where to be looking.

![Screenshot (13)](https://user-images.githubusercontent.com/50206336/156563893-925af7f7-58fe-463d-ba69-bfd27f186e4b.png)

Apologies for the newbiness of my question, I'm new to building from source.

Thanks

**Comment by snnn** [comment]
In the debug folder.

**Comment by snnn** [comment]
In the RelWithDebInfo folder.

**Comment by snnn** [comment]
If you are looking for onnxruntime.lib, then I'm sorry, the command you used,
```
.\build.bat --config RelWithDebInfo --parallel --cmake_generator "Visual Studio 16 2019"
```
does not generate it.

You need to append another flag: "--build_shared_lib"

**Comment by dilne** [comment]
Thanks @snnn, is there a way to build ORT as static libraries? I believe it is a requirement for implementation in Unreal Engine 4

**Comment by snnn** [comment]
The Requirements.txt is for python packages. I think you are talking C++, so please ignore it. 
You can build ORT as static libraries, but we couldn't provide much support and we don't publish such packages.  As you saw, it's hard to gather the static libraries and header files together.  We don't have build scripts to do that.  We believe if someone wants to static link to onnxruntime he need to integrate his build scripts to our cmake files.

**Comment by RyanUnderhill** [comment]
@dilne I think the Unreal requirements are for your plugin, not what your plugin depends on (to require only static libraries would be incredibly restrictive and unexpected).

So you should be able to have your plugin built as a static library and have it dynamically depend on onnxruntime. Hopefully...!

**Comment by WilliamTambellini** [comment]
@dilne  static linking still possible so convenient for plugins:
https://github.com/microsoft/onnxruntime/issues/8555
