### ISSUE TITLE
Error about  'Undefined symbol: _OrtGetApiBase'

### ISSUE THREAD

**Issue by big-zZ** [microsoft/onnxruntime#10767]
Xcode 13.1  
iPad  mini 14.8.1
I have made a static library called libonnxruntime.a  by using script under official way, in a simple ios project, i imported it and those headers, i add the marco 'ORT_API_MANUAL_INIT=1' in the project, and i test the api 'Ort::InitApi();' , it occurred a error 'Undefined symbol: _OrtGetApiBase', see the following pics

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/75821787/156744253-cd97860b-d93f-4474-8805-73ff17de6f53.png">
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/75821787/156744421-614b0eb2-6fe6-4728-8823-138d13c29c26.png">
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/75821787/156744534-1eb227a0-0103-46c8-9dd4-10e63f37b9fd.png">
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/75821787/156744360-7b6e6b96-92d8-4f24-8453-627e35ef5273.png">

have tried a lot of methods, but not fixed, anyone has seen this before? how to fix it?  thanks a lot~~~

**Comment by edgchen1** [comment]
One thing to resolve is `-F<...>/lib/ios/libonnxruntime.a` seems to be looking for a directory with that name, but I assume that's the static library file.

Can you verify that it's correctly linking to your libonnxruntime.a?

Also, in the next release (1.11) there will be "onnxruntime-c" and "onnxruntime-objc" pods for iOS that may make this easier.

**Comment by big-zZ** [comment]
> 

thanks a lot! i have fixed this bug by compiling a dynamic library！

**Comment by big-zZ** [comment]
fixed
