### ISSUE TITLE
Shape Inference does not work with onnx1.11.0 due to onnx shape inference enchancement

### ISSUE THREAD

**Issue by liqunfu** [microsoft/onnxruntime#10761]
**Describe the bug**
Before onnx1.11.0, op shape inference output empty dim values if it cannot be deduced to a number. With onnx1.11.0, it may may set to a symbolic unk__xx value:
```
ir_version: 6
producer_name: "tf2onnx"
producer_version: "1.6.0"
graph {
  node {
    input: "cell_stem_0/comb_iter_1/right/Relu:0"
    input: "cell_0/Pad/paddings:0"
    output: "cell_stem_1/Pad:0"
    name: "cell_stem_1/Pad"
    op_type: "Pad"
  }
  name: "tmp"
  input {
    name: "cell_stem_0/comb_iter_1/right/Relu:0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_param: "unk__3566"
          }
          dim {
            dim_value: 32
          }
          dim {
            dim_value: 111
          }
          dim {
            dim_value: 111
          }
        }
      }
    }
  }
  input {
    name: "cell_0/Pad/paddings:0"
    type {
      tensor_type {
        elem_type: 7
        shape {
          dim {
            dim_value: 8
          }
        }
      }
    }
  }
  output {
    name: "cell_stem_1/Pad:0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_param: "unk__0"
          }
          dim {
            dim_param: "unk__1"
          }
          dim {
            dim_param: "unk__2"
          }
          dim {
            dim_param: "unk__3"
          }
        }
      }
    }
  }
  value_info {
    name: "cell_stem_1/Pad:0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_param: "unk__0"
          }
          dim {
            dim_param: "unk__1"
          }
          dim {
            dim_param: "unk__2"
          }
          dim {
            dim_param: "unk__3"
          }
        }
      }
    }
  }
}
opset_import {
  version: 11
}
```
in onnxruntime\python\tools\symbolic_shape_infer.py, its logic relays on dim value being None to do symbolic derivation. Its logic is broken with onnx1.11.0. 

For this reason, I have skipped 3 test cases (in test_symbolic_shape_infer) that will fail at: 
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/python/onnxruntime_test_python_symbolic_shape_infer.py

**Urgency**
It depends on whether symbolic inference is needed for inferencing and/or training. Please triage 

**System information**
- Windows
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version: 1.11.0
- Python version: 3.8
- Visual Studio version (if applicable): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**To Reproduce**
prepare test models
python onnxruntime_test_python_symbolic_shape_infer.py TestSymbolicShapeInference.test_symbolic_shape_infer

**Screenshots**
NA

**Additional context**
NA

**Comment by tianleiwu** [comment]
I also noticed that shape inference for GPT-2 model has issue with ONNX 1.11 but good in 1.10. That could be an issue since some of our offline tools (like transformers optimization) uses symbolic shape inference, and we will see complains from customers soon.
