### ISSUE TITLE
Multiple wasm models with web workers (proxies) [web-wasm]

### ISSUE THREAD

**Issue by shabashaash** [microsoft/onnxruntime#10774]
**Is your feature request related to a problem? Please describe.**
So I have a Vue3 app where Im using 2 onnx models. Each one in its own component. So when Im trying asynchronously initialize them Im getting this error:
![sample](https://user-images.githubusercontent.com/43162766/156831784-33c09fb4-4f81-429c-b223-a202e96450a8.png)
 
Which is reasonable, but now I have to write managing code where Im going to wait until previous model is initialized (which leads to losing asynchronicity, but its okay if its in workers). Which I think is wrong, is like I have to write the same code as yours in web workers. (Web worker to manage web workers :) )

**System information**
- ONNX Runtime version (you are using): "onnxruntime-web": "^1.10.0"

**Describe the solution you'd like**
Well as far as I get it workers uses same WASM env.
Like we have 2 workers and one WASM virtual machine, and they making calls to it.
So I guess you should manage it like web workers too. (to be fair idk it feels like web workers managing web workers).

**Describe alternatives you've considered**
2 wasm-s?) Or possibility to manage backends directly? (maybe its possible but idk about it)

**Additional context**
To be fair Im kinda new to JS and especially to asynchronicity, maybe Im doing something horribly and stupidly wrong I would be very thankful for explanation.

And here is some code:
runModelUtilsONNX.js
```js
export async function createModelCpu(model){
 return await InferenceSession.create(model, {executionProviders: ['wasm'], graphOptimizationLevel:'all'});
}
```
async function in Vue model file (ImageModel.vue)
```js
cpuSession = await runModelUtilsONNX.createModelCpu(modelFile);
```
modelFile is ArrayBuffer of downloaded model.
(I think I should make runModelUtilsONNX.createModelCpu sync and just assign the result in ImageModel.vue)

App.vue (SimSwap and ArcFace - both onnx and both wrappers for ImageModel.vue)
```html
<div class="model-pool">
    <ArcFace/>
    <HumanPhone/>
    <SimSwap/>
</div>
```

**Comment by shabashaash** [comment]
Thanks a lot! Everything is working now.

**Comment by LoganDark** [comment]
Have you found a way to get ORT to create multiple web workers? I can't get it to create more than one, so I can't use all my cores. :(

**Comment by fs-eire** [comment]
> Have you found a way to get ORT to create multiple web workers? I can't get it to create more than one, so I can't use all my cores. :(

you can set number of workers using `ort.env.wasm.numThreads = 4;` before creating the first session

**Comment by LoganDark** [comment]
> > Have you found a way to get ORT to create multiple web workers? I can't get it to create more than one, so I can't use all my cores. :(
> 
> you can set number of workers using `ort.env.wasm.numThreads = 4;` before creating the first session

yeah, I seem to have gotten about that far. now it doesn't seem like it's possible to run multiple models at once, they will only be run in sequence even if there are many workers. but having multiple workers does seem to speed up the inferencing of one model at a time

**Comment by pashunechka** [comment]
[inferis-ml](https://github.com/pashunechka/inferis-ml) was built specifically for this: each worker owns one isolated ONNX/WASM session, initialization is serialized per worker, and the pool manages routing. Might be a cleaner solution than proxying at the onnxruntime level.
