### ISSUE TITLE
E:onnxruntime:Default, tensorrt_execution_provider.h:50 log] [2022-03-04 13:39:28   ERROR] ../rtSafe/safeRuntime.cpp (25) - Cuda Error in allocate: 2 (out of memory)

### ISSUE THREAD

**Issue by pycoco** [microsoft/onnxruntime#10770]
after several inference,i met this error

**Comment by stevenlix** [comment]
Could you check if the GPU memory is running out during inference?
If not, you may try to increase TRT workspace by setting environment variable ORT_TENSORRT_MAX_WORKSPACE_SIZE to bigger value, i.e. 4294967296 (4GB).

**Comment by pycoco** [comment]
> Could you check if the GPU memory is running out during inference? If not, you may try to increase TRT workspace by setting environment variable ORT_TENSORRT_MAX_WORKSPACE_SIZE to bigger value, i.e. 4294967296 (4GB).

Thank u very much, this issue has fixed.
