### ISSUE TITLE
What is default backend for python CPU implementation?

### ISSUE THREAD

**Issue by Jamiroquai88** [microsoft/onnxruntime#1079]
Hi,

I was trying to find out, which backend is used at default in python implementation. I used C api with MKL backend and my C code is around 3x slower compared to python.
Installed with
```bash
pip install onnxruntime
```
Version: `0.3.0`

**Comment by pranavsharma** [comment]
The 'onnxruntime' python pkg uses CPU as the default execution provider with MLAS enabled. MLAS is a compute library containing processor optimized GEMM kernels and platform specific threading code. You can read more about MLAS [here](https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/core/mlas). We don't support building with MKL; you can either use mklml or mkldnn along with mklml.

**Comment by Jamiroquai88** [comment]
Thanks, closed.

**Comment by whutbd** [comment]
Now support building with MKL ?
