### ISSUE TITLE
T5 Model with ONNX Runtime on GPU

### ISSUE THREAD

**Issue by GenVr** [microsoft/onnxruntime#10807]
Hi,
I would like to get shorter inference time for a T5-base model on GPU. I noticed there is [this](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/notebooks/PyTorch_Bert-Squad_OnnxRuntime_GPU.ipynb) script for a BERT model. Can it be compatible/reproduced also for a T5 model?
Alternatively, are there any methods to decrease the inference time of a T5 model, on GPU (not CPU)?
Thank you.

**Comment by wangyems** [comment]
You can rely on that script for partial optimization. Further optimizations for T5 are in our backlog. 

As an alternative, ORT with TRT EP(with TRT version 8.2) has better performance on T5 which was confirmed by us. You can build ORT with TRT EP and run model with specifying TensorrtExecutionProvider in EP list.

reference:
[build ORT with TRT EP](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.tensorrt)
[inference example](https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html)

**Comment by gennarovaccaro** [comment]
@wangyems My model has a max_length = 1024, and using TensorRT (I created the container and used the code) I have worse times than pytorch. This is because with lengths greater than 256 it seems not to be convenient. Can you confirm this too?

Then
> You can rely on that script for partial optimization. Further optimizations for T5 are in our backlog.

What are the codes or parts of interest for the T5 model from the [code](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/notebooks/PyTorch_Bert-Squad_OnnxRuntime_GPU.ipynb)? Is it convenient for models with max_length = 1024?

Thank you.

**Comment by wangyems** [comment]
We only compare it with ORT CUDA EP so I have limited information about how it compares with Pytorch. 

There are a couple of possible causes that could make your ORT-TRT run looks slow:
1. ORT-TRT needs a few warm-ups run. It's better to benchmark it after that.
2. Use IOBinding just like in ORT CUDA run.
3. Compare to Pytorch with exact same input. Avoid padding in ORT-TRT run by exporting the onnx model with dynamic input.

If you'd like to use the CUDA EP, just follow the Bert tutorial. The code is shared.

**Comment by GenVr** [comment]
@wangyems I'm using a TensorRT container for TRT, [this ](https://developer.nvidia.com/blog/optimizing-t5-and-gpt-2-for-real-time-inference-with-tensorrt/)"setting up" code and then [this ](https://github.com/NVIDIA/TensorRT/blob/release/8.2/demo/HuggingFace/notebooks/t5.ipynb)code for conversion and inference. 

Are they the most up-to-date versions and codes? I know that for a T5 with lengths greater than 256 the inference time is worse than pytorch, but a TRT fix had to be made about that.

**Comment by wangyems** [comment]
@GenVr Seems like you're working on native TRT. Suggest raising an issue here: https://github.com/NVIDIA/TensorRT/issues
