### ISSUE TITLE
"Where" Op Is Not Implemented

### ISSUE THREAD

**Issue by GuanLuo** [microsoft/onnxruntime#1080]
Hi all, I created a model containing "Where" operator but failed to load it via Onnx Runtime C API:
```
Could not find an implementation for the node Where(9)
```
However, the [version matrix](https://github.com/Microsoft/onnxruntime/blob/master/docs/Versioning.md#version-matrix) says it supports Onnx opset version 10.

The Python script to generate the model:
```Python
import onnx
onnx_input_str = onnx.helper.make_tensor_value_info("INPUT0", onnx.TensorProto.STRING, [1])
onnx_input_int = onnx.helper.make_tensor_value_info("INPUT1", onnx.TensorProto.INT32, [1])
onnx_flag = onnx.helper.make_tensor_value_info("READY", onnx.TensorProto.INT32, [1])
onnx_output = onnx.helper.make_tensor_value_info("OUTPUT", onnx.TensorProto.STRING, [1])

internal_input = onnx.helper.make_node("Cast", ["INPUT0"], ["_INPUT"], to=onnx.TensorProto.INT32)
add = onnx.helper.make_node("Add", ["_INPUT", "INPUT1"], ["add"])
zeros = onnx.helper.make_node("Sub", ["READY", "READY"], ["zeros"])
equal = onnx.helper.make_node("Equal", ["READY", "zeros"], ["equal"])
where = onnx.helper.make_node("Where", ["equal", "zeros", "add"], ["CAST"])
cast = onnx.helper.make_node("Cast", ["CAST"], ["OUTPUT"], to=onnx.TensorProto.STRING)

onnx_nodes = [internal_input, add, zeros, equal, where, cast]
onnx_inputs = [onnx_input_str, onnx_input_int, onnx_flag]
onnx_outputs = [onnx_output]

graph_proto = onnx.helper.make_graph(onnx_nodes, "conditional_and_cast", onnx_inputs, onnx_outputs)
model_def = onnx.helper.make_model(graph_proto)
onnx.save(model_def, "model.onnx")
```

**Comment by skottmckay** [comment]
> Could not find an implementation for the node Where(9)

This suggests you model has opset set to 9. What version of ONNX are you using?

**Comment by GuanLuo** [comment]
@skottmckay The onnx version is '1.4.1', and it is using opset 9 as you said. So it is not backward capatible?

**Comment by skottmckay** [comment]
Sorry - I thought Where was new in opset 10. What version of onnxruntime are you using as our implementation of Where was added a few months ago (and is valid for opset 9).

https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/tensor/where_op.cc

**Comment by GuanLuo** [comment]
I am using Onnx Runtime 0.4.0 built from source. Now I looked at the `where_op.cc` at branch `rel-0.4.0` and I noticed that the types `int32_t` and `bool` is [commented out](https://github.com/microsoft/onnxruntime/blob/rel-0.4.0/onnxruntime/core/providers/cpu/tensor/where_op.cc#L38), so I suppose that "where" op is implemented in Onnx Runtime but it is limited to certain data types?

**Comment by skottmckay** [comment]
The current implementation does limit the supported types, I believe to try and keep the overall binary size small. Support for int32_t was enabled last week though, so if you pulled the latest master it would be in that. 

https://github.com/microsoft/onnxruntime/commit/31cbb5d33de775dae852a4b566e3a82cadcc1c0e#diff-3276925863124d4b46cb2f4e29e49b9f

**Comment by GuanLuo** [comment]
I see. I wonder if there is a option / mode that I can enable to build the library with full Onnx support? Right now it seems to be inconvenient as I need to do something similar to 31cbb5d33de775dae852a4b566e3a82cadcc1c0e and to rebuild to support some data types.

**Comment by GuanLuo** [comment]
Opened a new issue #1122 for the feature requested in followup comment.
