### ISSUE TITLE
OnnxRuntime GPU very poor perfomance in .Net

### ISSUE THREAD

**Issue by sportbilly21** [microsoft/onnxruntime#10805]
System information
Windows 10 build 19044
ML.Net 1.7.0
Microsoft.ML.OnnxRuntime.GPU 1.10.0

Issue

Currently our application is in .Net and for deploying the models and getting the predictions we are using Flask and python. The models this way are running very fast all models run in around 10ms and GPU utilizsation is very low. GPU is a Quadro P400. We are trying to remove Flask and run everything within .NET so I have converted 4 models trained in Tensorflow/Keras to ONNX and I using them for inference with the use of ML.Net. I have created the pipeline and the prediction engine. I have installed CUDA and CuDNN needed for the package. I have both 10.2 and 11 Cuda versions in the PC. Performance when running with ML.Net is very poor and GPU is utilisation are 50%. Any suggestions or thoughts regarding this

Code of pipeline and prediction engine:

            var pipeline = this.mlContext.Transforms.ResizeImages("input", height, width, inputColumnName: nameof(ImageData.ImgInput), resizing: ImageResizingEstimator.ResizingKind.Fill)// inputColumnName: nameof(ImageInputData.Image))
            .Append(mlContext.Transforms.ExtractPixels(inputLayer, "input", colorsToExtract: ImagePixelExtractingEstimator.ColorBits.Rgb, orderOfExtraction: ImagePixelExtractingEstimator.ColorsOrder.ARGB, interleavePixelColors: true, outputAsFloatArray: true))
                .Append(mlContext.Transforms.ApplyOnnxModel(outputLayer, inputLayer, modelFile, gpuDeviceId: gpuID));
            //var pipeline = this.mlContext.Transforms.ExtractPixels(inputLayer, inputColumnName: nameof(ImageData.ImgInput), colorsToExtract: ImagePixelExtractingEstimator.ColorBits.Rgb, orderOfExtraction: ImagePixelExtractingEstimator.ColorsOrder.ARBG, interleavePixelColors: true);

            var data = mlContext.Data.LoadFromEnumerable(new List<ImageData>());
            var transformedData = pipeline.Fit(data).Transform(data);
            //var data = mlContext.Data.LoadFromEnumerable(new ImageData());
            this.model = pipeline.Fit(data); //;
            this.categories = cats;
            this.predictor = this.mlContext.Model.CreatePredictionEngine<ImageData, ImagePrediction>(this.model);

**Comment by yuslepukhin** [comment]
Have you tried running it with ONNXRuntime, say python interface and what is the performance there?
