### ISSUE TITLE
Missing documentation on LayerNormalization contrib spec

### ISSUE THREAD

**Issue by eralmual** [microsoft/onnxruntime#10839]
The Layer normalization entry is missing from the _ContribOperators.md_ file. Could you please add the corresponding documentation? 

- ONNX Runtime version: 1.10.0

**Comment by wschin** [comment]
Looks like `LayerNormalization`'s is wrongly [assigned to ONNX domain](https://github.com/microsoft/onnxruntime/blob/463fac67a383611a507a0138a17e1403bd2cc04b/onnxruntime/core/graph/contrib_ops/contrib_defs.cc#L1970). It should be [kMSDomain](https://github.com/microsoft/onnxruntime/blob/463fac67a383611a507a0138a17e1403bd2cc04b/onnxruntime/core/graph/contrib_ops/contrib_defs.cc#L792).

**Comment by faxu** [comment]
@wschin does changing the domain impact usage compatibility for models?

**Comment by wschin** [comment]
It's possible. We wrongly put `LayerNormalization` in `ai.onnx` domain and generate several internal tests. If I correct the domain of `LayerNormalization`, those tests need to be updated to add `com.microsoft` domain. If end user inherit this incorrect assumption, their model will fail.

**Comment by faxu** [comment]
ORT has a backward compatibility guarantee, so let's keep it as-is. It does not impact anything other than cleanliness I think. 

Is there a reason it's not in ONNX? Can it be represented as a function? Related issue: https://github.com/onnx/onnx/issues/2379

**Comment by wschin** [comment]
It's a bit surprising ONNX doesn't include it... Given that ORT has a LayerNormation implementation, we can easily add it to ONNX.

**Comment by faxu** [comment]
Thanks. @wschin can you please propose the function in ONNX?

**Comment by wschin** [comment]
Yep.

**Comment by eralmual** [comment]
Thank you!

**Comment by wschin** [comment]
Just a heads up. This is a [PR](https://github.com/onnx/onnx/pull/4076) for defining LayerNormalization in ONNX.
