### ISSUE TITLE
I can't find a example for GPU multi input

### ISSUE THREAD

**Issue by pycoco** [microsoft/onnxruntime#10834]

**Comment by natke** [comment]
Thank you @pycoco, Can you please give some more detail about what sort of example you would like? Which API are you using? Are working with a particular scenario?

**Comment by pycoco** [comment]
> Thank you @pycoco, Can you please give some more detail about what sort of example you would like? Which API are you using? Are working with a particular scenario?

My onnx model is with more than one input, and i want to my input data already in gpu before inferencing the model. Now i just known how to create on cpu.

**Comment by natke** [comment]
Hi @pycoco, this sample which is currently in PR might be helpful. It has a two input example, with inputs on GPU

https://github.com/natke/onnxruntime-inference-examples/blob/iobinding-sample/python/api/onnxruntime-python-api.py

Let us know if this helps.

**Comment by pycoco** [comment]
> https://github.com/natke/onnxruntime-inference-examples/blob/iobinding-sample/python/api/onnxruntime-python-api.py

thank u very much!!

**Comment by natke** [comment]
You're welcome. I'll close the issue. Please reach out again if you need more information.
