### ISSUE TITLE
Plan to support OnnxRuntimeTraining on Windows?

### ISSUE THREAD

**Issue by chethanpk** [microsoft/onnxruntime#10837]
Currently Onnxruntime training is not supported on Windows. To build and run my torch scripts to use ORT, it can only be done on Linux. Is there a plan to support this for Windows OS?

**Comment by baijumeswani** [comment]
Closing this for now. Please provide us with your use case and we will gauge whether we should prioritize it. Thanks.

**Comment by chethanpk** [comment]
Sorry for the late reply. I did not have any use case to support prioritizing this. I was just curious about your plan to support it.
