### ISSUE TITLE
Potential issue with asymmetric calibration resulting in very low accuracy

### ISSUE THREAD

**Issue by mfuntowicz** [microsoft/onnxruntime#10846]
Hey there 👋🏻 , 

I'm running some tests with the newly introduced `symmetric = <True/False>` when calibrating tensors.

My plan was to set `symmetric = False` has I would like to use asymmetric activations, but using this schema leads to very high drop in accuracy (evaluated on [DistilBERT](https://huggingface.co/distilbert-base-cased-distilled-squad) / SQuAD)

`symmetric = True`:
- EM = 75.818
- F1 = 83.979

`symmetric = False`: 
- EM = 0.36
- F1 = 1.70

One thing I'm noticing is that in the case of `symmetric = False` I tend to get qdq nodes with zero point = 255 which seems wrong.

**Comment by yufenglee** [comment]
Thanks @mfuntowicz for bringing out the issue. It is caused by a confusion of percentage to keep and percentage to drop.
