### ISSUE TITLE
does nnapi (armv7a or armv8a) support model contain lstm ?

### ISSUE THREAD

**Issue by mmxuan18** [microsoft/onnxruntime#10854]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macos 
- ONNX Runtime installed from (source or binary): source 
- ONNX Runtime version: 1.11
- Python version: 3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): ndk 20
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
i get a model from pytorch export onnx, when not use Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_Nnapi(sessionOptions, nnapi_flags));  i can get the right result, but when i use nnapi provider get follow error :

 I/TypeManager: Failed to read /vendor/etc/nnapi_extensions_app_allowlist ; No app allowlisted for vendor extensions use.
E/onnxruntime:  [E:onnxruntime:, inference_session.cc:1548 operator()] Exception during initialization: unordered_map::at: key not found
I/com.tc.tar.dem: Thread[6,tid=2710,WaitingInMainSignalCatcherLoop,Thread*=0xe5e4a810,peer=0x12fc04f8,"Signal Catcher"]: reacting to signal 3

i build static library , and use ndk ar tools to combine all .a to libonnxruntime.a 
nnapi build cmd:  ./build.sh --update --parallel --skip_tests --android --android_abi armeabi-v7a --android_api 21 --android_sdk_path $ANDROID_HOME  --android_ndk_path $ANDROID_NDK --cmake_extra_defines CMAKE_INSTALL_PREFIX=install --skip_onnx_tests --use_nnapi --nnapi_min_api 27 --minimal_build extended

**Expected behavior**
right result

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/6283983/158012597-47ab5fb7-1452-4d84-8199-16e16f9c4932.png">

**Comment by wschin** [comment]
I don't think NNAPI EP supports LSTM. There is no such op in [its op registration code](https://github.com/microsoft/onnxruntime/blob/03181caeaef9343bd2e8d7999386893562ebb23a/onnxruntime/core/providers/nnapi/nnapi_builtin/builders/op_builder.cc#L2633).

**Comment by mlinxiang** [comment]
but crash at set nnapi provider, even not reach Session create code, as error info:

Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_Nnapi(sessionOptions, nnapi_flags)); i can get the right result, but when i use nnapi provider get follow error :

I/TypeManager: Failed to read /vendor/etc/nnapi_extensions_app_allowlist ; No app allowlisted for vendor extensions use.
E/onnxruntime: [E:onnxruntime:, inference_session.cc:1548 operator()] Exception during initialization: unordered_map::at: key not found
I/com.tc.tar.dem: Thread[6,tid=2710,WaitingInMainSignalCatcherLoop,Thread*=0xe5e4a810,peer=0x12fc04f8,"Signal Catcher"]: reacting to signal 3

**Comment by mlinxiang** [comment]
> I don't think NNAPI EP supports LSTM. There is no such op in [its op registration code](https://github.com/microsoft/onnxruntime/blob/03181caeaef9343bd2e8d7999386893562ebb23a/onnxruntime/core/providers/nnapi/nnapi_builtin/builders/op_builder.cc#L2633).

as nnapi doc show, it support lstm op, 
![image](https://user-images.githubusercontent.com/6283983/158162563-4db65906-7be1-4a39-b008-3c1040bb6f9b.png)

https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0ad0377e8c305e596fb7f64ff896671fc5

**Comment by YUNQIUGUO** [comment]
Hi, 

just first want to make sure that the `android_api`in your pasted nnapi build cmd, is it a typo or you actually used 21? I guess min android api should be >=27. 

> nnapi build cmd: ./build.sh --update --parallel --skip_tests --android --android_abi armeabi-v7a --android_api 21 --android_sdk_path $ANDROID_HOME --android_ndk_path $ANDROID_NDK --cmake_extra_defines CMAKE_INSTALL_PREFIX=install --skip_onnx_tests --use_nnapi --nnapi_min_api 27 --minimal_build extended

**Comment by skottmckay** [comment]
Seems like your runtime error comes from a vendor extensions issue, which is outside of ORT. https://source.android.com/devices/neural-networks/vendor-extensions

Currently the ORT NNAPI execution provider does not have support for converting the ONNX operator to the NNAPI equivalent. That would mean the LSTM operator would run using the ORT CPU kernel. We can look at adding support for LSTM to NNAPI. Is this for a production scenario?

**Comment by skottmckay** [comment]
We could certainly look at adding support for LSTM to the NNAPI EP in the next release, but that will be a few months away. 

Contributions are welcome if you want to ensure that support is implemented in that timeframe. 

It would be helpful to know the details of the parameters to the LSTM node/s you have to see if that can be mapped from ONNX to what NNAPI LSTM supports.

**Comment by mlinxiang** [comment]
@skottmckay do nnapi support armv7a,  in my case i compiled nnapi arm64v8a run success, but armv7a crash on create session?

**Comment by skottmckay** [comment]
As the ORT NNAPI EP doesn't have handling for LSTM currently it will be using the CPU execution provider for LSTM operations on all ARM platforms. 

If there's a crash we can investigate if you share the model and/or logs from the crash.
