### ISSUE TITLE
Cannot run IO Binding with int64 PyTorch tensors

### ISSUE THREAD

**Issue by natke** [microsoft/onnxruntime#10853]
**Describe the bug**
Running IOBinding with int64 PyTorch tensors fails with the following error:

```
RuntimeError: No corresponding Numpy type for Tensor Type.
```

**Urgency**
This is important because we are trying to improve ONNX Runtime documentation and we need to know if this is a supported scenario.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): installed from binary
- ONNX Runtime version: 1.10
- Python version: 3.9
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.4
- GPU model and memory: V100

**To Reproduce**
- Run this python script: https://github.com/natke/onnxruntime-inference-examples/blob/iobinding-sample/python/api/onnxruntime-python-api.py

**Expected behavior**
That int64 PyTorch tensors should be able to take advantage of IO Binding

**Additional context**
See also where the same issue is noted
- https://www.reddit.com/r/MachineLearning/comments/sobfvm/p_what_we_learned_by_accelerating_by_5x_hugging/

**Comment by mstfbl** [comment]
Hi @natke @xadupre , I am also seeing this issue on my end when working on my ONNX exported model, at this specific [line](https://github.com/mstfbl/riiid-acp-pub/blob/2800c89df8b6571f0bd88c63289e224a3dba85a1/05_inference_no_fastai_torch_export.py#L989), with the input being a Numpy `dtype('int64')`/`dtype('long')` matrix. It seems that int64/long Numpy tensors are currently buggy with ORT.

**Comment by natke** [comment]
Are you able to build ONNX Runtime from source and try with the fix that has just been merged? @mstfbl

**Comment by mstfbl** [comment]
@natke Yes, it does!

**Comment by natke** [comment]
Awesome @mstfbl!

**Comment by natke** [comment]
Fixed by #10943
