### ISSUE TITLE
A function decorator for PyTorch modules, to export ONNX

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#1087]
**Is your feature request related to a problem? Please describe.**
I have this `MVN` implementation:

```python
class MVN(nn.Module):
    """Mean-Variance Normalization (MVN) Layer
    """
    def __init__(self, normalize_variance=True, across_channels=False, eps=None):
        super(MVN, self).__init__()
        self.normalize_variance = normalize_variance
        self.across_channels = across_channels
        if eps is None:
            eps = 1e-9
        self.eps = eps

    def extra_repr(self):
        """Extra information
        """
        return "eps={}{}{}".format(
                self.eps,
                ", normalize_variance" if self.normalize_variance else "",
               ", across_channels" if self.across_channels else "",
        )

    def forward(self, x):
        std = None
        shape = x.data.shape
        n_b = shape[0]
        if self.across_channels:
            if shape[0] == 1:
                # single batch normalization reduction
                mean = x.mean()
                if self.normalize_variance:
                    std = x.std()
            else:
                mean = x.view(n_b, -1).mean(1).view(n_b, 1, 1, 1)
                if self.normalize_variance:
                    std = x.view(n_b, -1).std(1).view(n_b, 1, 1, 1)
        else:
            n_c = shape[1]
            mean = std = x.view(n_b, n_c, -1).mean(2).view(n_b, n_c, 1, 1)
            if self.normalize_variance:
                std = x.view(n_b, n_c, -1).std(2).view(n_b, n_c, 1, 1)
        if std is not None:
            return (x - mean) / (std + self.eps)
        return x - mean
```

I cannot export it because [std is not supported in ONNX](https://github.com/onnx/onnx/issues/2045) but ONNX already has [MeanVarianceNormalization](https://github.com/onnx/onnx/blob/master/docs/Operators.md#MeanVarianceNormalization) that I would like to be used with this `nn.Module`. 

**System information**
- ONNX Runtime version (you are using): 0.4.0

**Describe the solution you'd like**
I would like to have a decorator like

```python
    @onnx_convert('MeanVarianceNormalization')
    def forward(self, x):
        ....
```

To return correct `g.op(MeanVarianceNormalization)` to the tracer.

**Describe alternatives you've considered**

1. Modify symbolic.py (not a good idea because it may change in the next update)
2. monkey-patch symbolic.py, this file already monke-patches using `import torch.onnx.utils` so I hope this works
3. provide decorator as `Functional` level instead of `nn.Module`, a little more cumbersome in simple cases but not bad

**Additional context**
I also need this functionality for custom layers, I would like to use custom layers and use this functionality to automatically export ONNX from full model that includes custom layer/ops

**Comment by bencherian** [comment]
This seems like something that should be a PyTorch issue relating to its ONNX export functionality.

**Comment by dashesy** [comment]
@bencherian opened the issue there. It is related to PyTorch's ONNX exporter
