### ISSUE TITLE
FunctionImpl should consider nested subgraphs when updating graph inputs/outputs

### ISSUE THREAD

**Issue by jantonguirao** [microsoft/onnxruntime#10876]
**Is your feature request related to a problem? Please describe.**

I believe there is a bug in the `FunctionImpl` expansion logic in ONNX Runtime. I found this issue when testing https://github.com/onnx/onnx/pull/3892, which uses an ONNX function that contains a subgraph.

The function expansion logic in `FunctionImpl` visits the schema input names, and replaces any occurrences of those in the graph with the actual function input names. While doing so, it detects which inputs are consumed by the function graph and updates the function body graph inputs and outputs based on that information. The problem comes when the inputs/outputs are consumed by a node in a sub-graph nested within the main graph. Those are currently not taken into consideration when populating `graph_inputs`/`graph_outputs`, which results in an error.

**Edit**: 
Now that SequenceMap has been merged. This can be easily reproduced by running ONNX tests during the ORT build, producing an error such as:
```
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for SequenceMap(16) node with name ''
```
The issue is fixed when applying the patch I am suggesting below.

It can also be reproduced easily by running the Example 2 from https://github.com/onnx/tutorials/blob/f5f6e2ce4e764304fbf042f25b0c82875c243f2c/tutorials/BatchProcessingSequenceMap.ipynb

**System information**
- ONNX Runtime version (you are using): Top-of-tree

**Describe the solution you'd like**

`FunctionImpl` should visit and take into account any nested subgraphs, when updating the function body graph inputs/outputs.

I am attaching a diff of a fix I've tested on my end and seems to resolve the issue.
[subgraph_function_body_fix.patch.txt](https://github.com/microsoft/onnxruntime/files/8255977/subgraph_function_body_fix.patch.txt)

UPDATE: The previous diff can no longer be applied. Here is a new one:
[UPDATED_subgraph_function_body_fix.patch.txt](https://github.com/microsoft/onnxruntime/files/8668164/UPDATED_subgraph_function_body_fix.patch.txt)

Note: While this fixes my particular issue, I think it might not be considering all relevant cases.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jantonguirao** [comment]
@gramalingam Could you please take a look at this issue?

**Comment by gramalingam** [comment]
@jantonguirao , thanks for catching the issue. The inliner has been re-implemented (see: https://github.com/microsoft/onnxruntime/pull/11731 ), and I think it should address this issue.

**Comment by jantonguirao** [comment]
I can confirm that the issue is fixed now. Thank you!
