### ISSUE TITLE
Building for Wasm - Undefined Symbols from absiel

### ISSUE THREAD

**Issue by houserrob** [microsoft/onnxruntime#10918]
Hi,  I'm trying to build a C++ project, which utilizes OnnxRuntime, into a web assembly.  The build process worked for a coworker several months back  so I'm assuming a dependency has changed since then.   My steps:

Setup an emscripten environment

Clone OnnxRuntime
.\build.bat --build_wasm --skip_tests --config Release --disable_wasm_exception_catching

this successfully generated a number of libonnxruntime_xxxx.a libraries

Then in our project 
emcmake cmake -B cmake-build-emscripten -G Ninja
cmake --build cmake-build-emscripten

this successfully generated our library, I'll call it ourwasm.a

Then I tried to build the final output with this command
emcc -o output.html -s "EXPORTED_FUNCTIONS=['_create']" -s "EXPORTED_RUNTIME_METHODS=['ccall']" -s DISABLE_EXCEPTION_CATCHING=0 -O0 -s ALLOW_MEMORY_GROWTH=1 ourwasm.a %onnxbuildout%\libonnxruntime_session.a %onnxbuildout%\libonnxruntime_common.a %onnxbuildout%\libonnxruntime_util.a %onnxbuildout%\libonnxruntime_framework.a %onnxbuildout%\libonnxruntime_providers.a %onnxbuildout%\libonnxruntime_flatbuffers.a %onnxbuildout%\libonnxruntime_graph.a %onnxbuildout%\external\protobuf\cmake\libprotobuf-lited.a %onnxbuildout%\libonnxruntime_optimizer.a %onnxbuildout%\libonnxruntime_mlas.a %onnxbuildout%\external\onnx\libonnx.a %onnxbuildout%\external\onnx\libonnx_proto.a %onnxbuildout%\external\re2\libre2

This results in the following repeated a number of times (snipped for clarity)
_wasm-ld: error: e:\repos\onnxruntime\build\Windows\Release\libonnxruntime_framework.a(allocation_planner.cc.o): undefined symbol: absl::lts_20211102::container_internal::kEmptyGroup
wasm-ld: error: e:\repos\onnxruntime\build\Windows\Release\libonnxruntime_framework.a(allocation_planner.cc.o): undefined symbol: absl::lts_20211102::container_internal::kEmptyGroup
wasm-ld: error: e:\repos\onnxruntime\build\Windows\Release\libonnxruntime_framework.a(allocation_planner.cc.o): undefined symbol: absl::**lts_20211102**::hash_internal::MixingHashState::kSeed
wasm-ld: error: e:\repos\onnxruntime\build\Windows\Release\libonnxruntime_framework.a(allocation_planner.cc.o): undefined symbol: absl::lts_20211102::hash_internal::MixingHashState::kSeed_

This has some similarities to Missing symbols when using windows shared build · [Issue #1118 · abseil/abseil-cpp · GitHub](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fabseil%2Fabseil-cpp%2Fissues%2F1118&data=04%7C01%7Crhouser%40microsoft.com%7Cf48ea37f10f84032b74c08da082fbc89%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637831298374691684%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Z9KeflZQm%2FgFScu5wWxSGwzEiP2pz0GXLr7zygWWx4M%3D&reserved=0) and [Missing internal targets in AbseilDll.cmake? · Issue #1114 · abseil/abseil-cpp · GitHub](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fabseil%2Fabseil-cpp%2Fissues%2F1114&data=04%7C01%7Crhouser%40microsoft.com%7Cf48ea37f10f84032b74c08da082fbc89%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637831298374742121%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yAGTpPXQH9wpEr9DYRpvF5DsFa342pFbymq%2BP7IERpY%3D&reserved=0) 

I've tried looking through the abseil libs and found that onnxruntime pulls in external\abseil-cpp\absl\flags\libabsl_flags_reflection.a which appears to define kEmptyGroup.  However the version appear to be different

__class_type_infoE_ZN4absl12lts_**2021110218**container_internal11kEmptyGroupE_ZN4absl12lts_2021110213hash_internal15MixingHashState5kSeedE_ZTINSt3__217bad_function_callE_ZTVNSt3__217bad_function_callE_ZTVNSt3__210

How can I get the proper version specified for the onnxruntime build so I can get this all to link?

**Comment by hanbitmyths** [comment]
Instead of '--build_wasm', try to use '--build_wasm_static_lib' to build the static library of ONNX Runtime WebAssembly. This build option was introduced at [this PR](https://github.com/microsoft/onnxruntime/pull/10184).

_build.bat --config Release --build_wasm_static_lib_

**Comment by houserrob** [comment]
Thanks for the suggestion. I tried the --build_wasm_static_lib option but ended up with a lot more linker errors than before: 

_error: undefined symbol: _ZN4absl12lts_2021110213base_internal18ThrowStdOutOfRangeEPKc (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: __ZN4absl12lts_2021110213base_internal18ThrowStdOutOfRangeEPKc may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN4absl12lts_2021110213hash_internal10CityHash32EPKcm (referenced by top-level compiled C/C++ code)
warning: __ZN4absl12lts_2021110213hash_internal10CityHash32EPKcm may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN4absl12lts_2021110213hash_internal15MixingHashState28CombineLargeContiguousImpl32EyPKhm (referenced by top-level compiled C/C++ code)
warning: __ZN4absl12lts_2021110213hash_internal15MixingHashState28CombineLargeContiguousImpl32EyPKhm may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN4absl12lts_2021110218container_internal19find_first_non_fullIvEENS1_8FindInfoEPKNS1_6ctrl_tEmm (referenced by top-level compiled C/C++ code)
warning: __ZN4absl12lts_2021110218container_internal19find_first_non_fullIvEENS1_8FindInfoEPKNS1_6ctrl_tEmm may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN4absl12lts_2021110218container_internal37ConvertDeletedToEmptyAndFullToDeletedEPNS1_6ctrl_tEm (referenced by top-level compiled C/C++ code)
warning: __ZN4absl12lts_2021110218container_internal37ConvertDeletedToEmptyAndFullToDeletedEPNS1_6ctrl_tEm may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN5nsync13nsync_cv_waitEPNS_11nsync_cv_s_EPNS_11nsync_mu_s_E (referenced by top-level compiled C/C++ code)
warning: __ZN5nsync13nsync_cv_waitEPNS_11nsync_cv_s_EPNS_11nsync_mu_s_E may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN5nsync13nsync_mu_lockEPNS_11nsync_mu_s_E (referenced by top-level compiled C/C++ code)
warning: __ZN5nsync13nsync_mu_lockEPNS_11nsync_mu_s_E may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN5nsync15nsync_cv_signalEPNS_11nsync_cv_s_E (referenced by top-level compiled C/C++ code)
warning: __ZN5nsync15nsync_cv_signalEPNS_11nsync_cv_s_E may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN5nsync15nsync_mu_unlockEPNS_11nsync_mu_s_E (referenced by top-level compiled C/C++ code)
warning: __ZN5nsync15nsync_mu_unlockEPNS_11nsync_mu_s_E may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZN5nsync18nsync_cv_broadcastEPNS_11nsync_cv_s_E (referenced by top-level compiled C/C++ code)
warning: __ZN5nsync18nsync_cv_broadcastEPNS_11nsync_cv_s_E may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZNKSt3__215basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv (referenced by top-level compiled C/C++ code)
warning: __ZNKSt3__215basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_no_aliasILb0EEERS5_PKcm (referenced by top-level compiled C/C++ code)
warning: __ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_no_aliasILb0EEERS5_PKcm may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_no_aliasILb1EEERS5_PKcm (referenced by top-level compiled C/C++ code)
warning: __ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_no_aliasILb1EEERS5_PKcm may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE26__erase_external_with_moveEmm (referenced by top-level compiled C/C++ code)
warning: __ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE26__erase_external_with_moveEmm may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZNSt3__212basic_stringIwNS_11char_traitsIwEENS_9allocatorIwEEE26__erase_external_with_moveEmm (referenced by top-level compiled C/C++ code)
warning: __ZNSt3__212basic_stringIwNS_11char_traitsIwEENS_9allocatorIwEEE26__erase_external_with_moveEmm may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZNSt3__213basic_filebufIcNS_11char_traitsIcEEE4openEPKcj (referenced by top-level compiled C/C++ code)
warning: __ZNSt3__213basic_filebufIcNS_11char_traitsIcEEE4openEPKcj may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZNSt3__213basic_filebufIcNS_11char_traitsIcEEEC1Ev (referenced by top-level compiled C/C++ code)
warning: __ZNSt3__213basic_filebufIcNS_11char_traitsIcEEEC1Ev may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZNSt3__213basic_filebufIcNS_11char_traitsIcEEED1Ev (referenced by top-level compiled C/C++ code)
warning: __ZNSt3__213basic_filebufIcNS_11char_traitsIcEEED1Ev may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: _ZNSt3__215basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strERKNS_12basic_stringIcS2_S4_EE (referenced by top-level compiled C/C++ code)
warning: __ZNSt3__215basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strERKNS_12basic_stringIcS2_S4_EE may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
emcc: error: 'E:/repos/emsdk/node/14.18.2_64bit/bin/node.exe E:\repos\emsdk\upstream\emscripten\src\compiler.js C:\Users\rhouser\AppData\Local\Temp\tmpods1ivfn.txt' failed (1)_

**Comment by guschmue** [comment]
The instructions [here](https://onnxruntime.ai/docs/build/web.html#build-instructions) should work.
