### ISSUE TITLE
How to choose execution provider using Python?

### ISSUE THREAD

**Issue by adriacabeza** [microsoft/onnxruntime#1093]
I've seen some documentation about it using C but using Python I have not seen anything in order to choose execution provider; or does Onnxruntime choose the best one in order to get the best performance?

**Comment by pranavsharma** [comment]
Currently we offer 2 separate packages - one for CPU and one for GPU execution provider. The individual packages compile and link the specific execution provider code in the ORT (onnxruntime) binary. Hence, you can't really choose an execution provider unless you're building ORT with several providers in the same binary. Currently, there is no capability to choose the best one.

**Comment by pranavsharma** [comment]
Please reopen if the above comment doesn't address your question. Thanks!
