### ISSUE TITLE
torch_onnx_export_helper.py hits wrong path for preproduction Torch versions

### ISSUE THREAD

**Issue by causten** [microsoft/onnxruntime#10946]
**Describe the bug**
This recent merged pull request causes a failure...
Fix benchmark bugs and add Pytorch version control (https://github.com/microsoft/onnxruntime/pull/10928)

It checks if my torch version is >= 1.11.0  .  The Torch version I have is Torch 1.11.0.a0+gitbe370c1.  
The Version check believes my Torch is less then 1.11.0 (which is accurate by the Version documentation), goes down the path of 1.10.x parameters, and causes a failure.  In reality a Torch version that matches the Release Tuple should hit the `True` path.  

As a result from onnxruntime/build/Release/onnxruntime/transformers

```
[benchmark.py:601 -                 main()] Exception
Traceback (most recent call last):
  File "./benchmark.py", line 599, in main
    args.model_source, args)
  File "./benchmark.py", line 116, in run_onnxruntime
    validate_onnx, use_raw_attention_mask, overwrite, model_fusion_statistics, fusion_options)
  File "/workspace/onnxruntime/build/Release/onnxruntime/transformers/onnx_exporter.py", line 399, in export_onnx_model_from_pt
    use_external_data_format=use_external_data_format)
  File "/workspace/onnxruntime/build/Release/onnxruntime/transformers/torch_onnx_export_helper.py", line 74, in torch_onnx_export
    use_external_data_format=use_external_data_format)
TypeError: export() got an unexpected keyword argument '_retain_param_name'
[benchmark.py:610 -                 main()] No any result avaiable.
``` 

Python 3.7.11 (default, Jul 27 2021, 14:32:16)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from packaging.version import Version
>>> v1 = Version("1.11.0.a0+gitbe370c1")
>>> v2 = Version("1.11.0")
>>> v1 >= v2
False

**Urgency**
High enough that I'll have to patch the torch_onnx_export_helper.py in my repo until this is fixed
onnxruntime/build/Release/onnxruntime/transformers/torch_onnx_export_helper.py 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): master branch
- Python version: 3.7

**To Reproduce**
```
onnxruntime/build/Release/onnxruntime/transformers# python3 ./benchmark.py -g -b 1 -m bert-base-cased --sequence_length 128 --precision fp16 --provider migraphx --verbose -o no_opt 
```
Note: you can not have  `onnx_models/bert_base_cased_1.onnx` file already downloaded since the failure occurs during the process of obtaining it

**Expected behavior**
No failure and the onnx file is downloaded and the benchmark runs

**Comment by causten** [comment]
This works...

`if Version(torch.__version__).release >= Version("1.11.0").release:`

**Comment by wangyems** [comment]
The API change was introduced between Torch 1.10 and 1.11 and it's also possible that Torch with version 1.11.0.xxx has the older API. I assume users stick to a released version of Torch if released or nightly version(before the release).

In your case of using branch binary, there seems a way(not elegant though) to inspect the args:

```python
inspect.getfullargspec(torch.onnx.export).args
['model', 'args', 'f', 'export_params', 'verbose', 'training', 'input_names', 'output_names', 'operator_export_type', 'opset_version', '_retain_param_name', 'do_constant_folding', 'example_outputs', 'strip_doc_string', 'dynamic_axes', 'keep_initializers_as_inputs', 'custom_opsets', 'enable_onnx_checker', 'use_external_data_format']
```

**Comment by causten** [comment]
ok, thanks for the other changes.  I'll keep a patch and push to get on the released version of Torch.
