### ISSUE TITLE
The onnxruntime nuget package can be installed under xamarin forms and run on the android system?

### ISSUE THREAD

**Issue by sharpwood** [microsoft/onnxruntime#1094]
The onnxruntime nuget package can be installed under xamarin forms and run on the android system?

**Comment by pranavsharma** [comment]
We've not tested this. Have you? The nuget pkg is essentially a zip file; you should be able to install it if you've space.

**Comment by sharpwood** [comment]
I checked the nuget package, there is no arm cpu support library, this project will add arm support?

**Comment by jignparm** [comment]
@Sharpwood -- the NuGet package does not contain the arm binaries currently. The latest runtimes are listed below for the latest 0.4.0 version of the package.

One option for a quick workaround is to build the arm binaries from source (**onnxruntime.dll** mainly), , unzip the package, place the dlls into the correct arm-x64 folder, and reconstruct an updated NuGet package which contains the arm dlls.

What device/app are you looking to use this on?

* \runtimes
   *  \linux-x64
   *  \linux-x86
   *  \osx-x64
   *  \win-x64
   *  \win-x86

**Comment by sharpwood** [comment]
Thank you for your quick answer. I will try this method first and look forward to the official support for arm.
