### ISSUE TITLE
Error Nodes in a graph must be topologically sorted, however input 'Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Slice_1/begin:0' of node: name: Add__1005 OpType: Add

### ISSUE THREAD

**Issue by mengniwang95** [microsoft/onnxruntime#10941]
**Describe the bug**
Hi, I can not run this quantized model successfully with 'Error Nodes in a graph must be topologically sorted, however input 'Postprocessor/BatchMultiClassNonMaxSuppression/map/while/Slice_1/begin:0' of node: name: Add__1005 OpType: Add'
But this node is not in this model.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version: 1.10.0
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
```python
model = onnx.load(model_path)
session = ort.InferenceSession(model.SerializeToString(), None)
```
[order.zip](https://github.com/microsoft/onnxruntime/files/8305325/order.zip)

**Comment by jcwchen** [comment]
See https://github.com/onnx/onnx/issues/4070#issuecomment-1072569764. Thanks!
