### ISSUE TITLE
why convert onnx model to ort, only basic optim level can run but extend or all level create session failed?

### ISSUE THREAD

**Issue by mmxuan18** [microsoft/onnxruntime#10951]
**Describe the bug**
i compile static library of onnxruntime from source, and use python install of 1.10 for convert tools. when use basic optim level, my c++ code can load and run success, but when i use extended or all optim level, my code can't create session <the only differcence is the model path>, but the same time i use python code to load the convert saved optim onnx model, basic extended all level totoal can run sucess, so what's the problem?

when i compile python wheel package  from master branch of the newest code, and use the new convert, the extend optim level ort model can run success on up c++ code no matter the libonnxruntime.a lib is 1.10 or master newest code

**my model has lstm node** 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macos 
- ONNX Runtime installed from (source or binary): source of 1.10
- ONNX Runtime version: 1.10 
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by garymm** [comment]
Not entirely sure, but this seems to be saying that ORT behaves differently with different compilation options, which doesn't have anything to do with converters.

**Comment by RandySheriffH** [comment]
@garymm : so exactly what errors did u see when "...my code can't create session..."?

**Comment by mlinxiang** [comment]
i check my process steps again as follow:
1. pip install onnxruntime    which install onnxruntime 1.10
2. follow command generate "all" optimization level model:
python -m onnxruntime.tools.convert_onnx_models_to_ort --optimization_level all --enable_type_reduction --save_optimized_onnx_model test.onnx
and follow command generate "basic" optimization level model with the same onnx model:
python -m onnxruntime.tools.convert_onnx_models_to_ort --optimization_level basic --enable_type_reduction --save_optimized_onnx_model test.onnx
3. git clone 1.10 tag code and use follow build command compile static library used for c++:
./build.sh --update --build --parallel --config Release --skip_tests --android --android_abi armeabi-v7a --android_sdk_path $ANDROID_HOME  --android_ndk_path $ANDROID_NDK --android_api 29  --disable_contrib_ops --disable_ml_ops --disable_rtti --disable_exceptions --minimal_build --use_openmp --cmake_extra_defines CMAKE_INSTALL_PREFIX=install-static
4. use follow code to load ort format model
<img width="965" alt="image" src="https://user-images.githubusercontent.com/6283983/159442256-6d08a3e8-d99e-4906-a92f-5a658fe5603c.png">
5. the basic optimization level model run success and result is all right
but the all optimization level model crash on Session create, as libonnxruntime.a is Release type, so the crash stack has no any information only "Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 12961"  /apex/com.android.runtime/lib/bionic/libc.so (abort+172)

**Comment by mlinxiang** [comment]
anthor problem is also very strange, my android app can debug and step into jni ndk code, but when i add onnxruntime code to the app, then android studio debug can't step into jni ndk code, breakpoint at java can hold, but c++ code breakpoint become gray and the debuger invalid and exit.

**Comment by RandySheriffH** [comment]
@mlinxiang, seems like we have a optimizer issue - during graph loading ort will transform the graph for better performance, and there might be issues doing so under certain conditions. Just added another tag - "optimizer".

**Comment by mlinxiang** [comment]
if i use "basic" level when convert onnx model to ort format, and in c++ code sessionOptions set graph optimization level to ORT_ENABLE_ALL , is this has the same effect as the convert set to "all" level?

**Comment by mlinxiang** [comment]
as the 1.11 release which support dynamic input on nnapi, i test up convert again, but very bad result as follow:

when use nnapi ep can't create session with log "Failed to read /vendor/etc/nnapi_extensions_app_allowlist ; No app allowlisted for vendor extensions use." both "fixed" and "runtime" optim level 

when not use nnapi ep, the "runtime" level ort model can run but "fixed" level ort can't run 

the compile android_api level and build.gradle level set all "29"

**Comment by mmxuan18** [comment]
@RandySheriffH  when the 1.11.1 released i test the new version again, but still has problem.
torch=1.11 + onnxruntime_python=1.10 <convert onnx to ort> + onnxruntime=1.10/1.11.1<c++> can run success
but when use onnxruntime_python=1.11.1 convert onnx to ort use Fixed type，in c++ model load failed. but 1.11.1 verson python converter can't set optim level 'basic',  Fixed mean optim level 'all'， so how to process this bug?
