### ISSUE TITLE
MatMul fusion failed at scalar input

### ISSUE THREAD

**Issue by yz6790** [microsoft/onnxruntime#10950]
**Describe the bug**
When fusing ```MatMul``` and ```Mul``` for an input of ```rank=0```, there is an error. 

Perhaps it is because ```Mul``` outputs a result of ```rank=1```, and the input's rank was not raised to 1 in fusion? Since ```MatMul``` does not support inputs of ```rank=0```, this error happens?
**Urgency**
None.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Mojave
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.10.0
- Python version: 3.9.7
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a
- PyTorch version: 1.10.2

**To Reproduce**
- Describe steps/code to reproduce the behavior.
```
import torch

class Model(torch.nn.Module):
    @torch.no_grad()
    def forward(self, i1):
        y = torch.mul(i1, torch.ones(1,dtype=torch.float32))
        o2 = torch.matmul(y, torch.ones((1,64),dtype=torch.float32))

        return o2


model = Model()
inputs = (torch.randn((), dtype=torch.float32))
output_names = ["o1"]
torch.onnx.export(model, inputs, "1.onnx", verbose=False,
                  input_names=["i1"], output_names=output_names, opset_version=14)
```
- Attach the ONNX model to the issue (where applicable) to expedite investigation.
[MatMul.onnx .zip](https://github.com/microsoft/onnxruntime/files/8308724/MatMul.onnx.zip)

**Expected behavior**
MatMul will take the input as rank=1 after Mul.
**Screenshots**
<img width="632" alt="屏幕快照 2022-03-19 上午2 26 36" src="https://user-images.githubusercontent.com/71030634/159110186-3443eec3-1157-41b1-b814-f6e04cefe081.png">
<img width="250" alt="屏幕快照 2022-03-18 下午11 20 26" src="https://user-images.githubusercontent.com/71030634/159110188-f9b82928-55a5-41c1-8040-8f06a51d4809.png">

**Comment by ytaous** [comment]
thanks for report the issue, let me take a look

**Comment by ytaous** [comment]
x1 = np.array((1.0)).astype(np.float32)
session = ort.InferenceSession("./1.onnx", providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
res = session.run(None,{"i1":x1})
