### ISSUE TITLE
Reference for adding two custom kernels to onnxruntime #211

### ISSUE THREAD

**Issue by Darshcg** [microsoft/onnxruntime#10968]
Hi Onnxrt team,

I had a requirement of adding two custom ops, exporting to onnx, and executing it. As the first step: I had registered the custom ops and exported to onxx model. But I am not sure how to add the two kernels in onnxruntime. I got the reference for adding one custom kernel(https://github.com/neginraoof/CustomOperators/tree/master/CustomOperator/ort_custom_op), but I need a reference for adding two custom kernels. Kindly assist me in finding the reference for the same.

Thanks,
Darshan

**Comment by RandySheriffH** [comment]
@Darshcg : thanks for reaching out - https://github.com/neginraoof/CustomOperators/blob/9572221ba8e964fa9b260a00b3c7ddd230574223/CustomOperator/ort_custom_op/custom_op_test.cc#L87
Just add your 2nd op to the domain.

**Comment by Darshcg** [comment]
Hi @RandySheriffH,

Thanks a lot for your reply. I was able to solve it. 

Thank you.
