### ISSUE TITLE
can openmp used for android device of armv7a or armv8a?

### ISSUE THREAD

**Issue by mmxuan18** [microsoft/onnxruntime#10961]
**Describe the bug**

can openmp used for android device of armv7a or armv8a, if this support, how to set the thread num:
this->sessionOptions.SetIntraOpNumThreads(2);
    this->sessionOptions.SetInterOpNumThreads(4);
if openmp can't use, for the default cpu model on android , what't is the recommand strategy for these two option?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu  16.04): macOS
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.10 
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by RandySheriffH** [comment]
We have deprecated OMP, for intra... you could set it to be the number of cores in your arm device. for inter just set to 1 if you are with sequential executor.

**Comment by mlinxiang** [comment]
> We have deprecated OMP, for intra... you could set it to be the number of cores in your arm device. for inter just set to 1 if you are with sequential executor.

as other issue mentioned, the ORT_PARALLEL mode not recommand: https://github.com/microsoft/onnxruntime/issues/10330#issuecomment-1018135942
so is this infromation also apply to android arm?

**Comment by skottmckay** [comment]
> so is this infromation also apply to android arm?

Yes. Same C++ implementation is used on all platforms
