### ISSUE TITLE
Slow load time of .onnx model with external data from 1.7 to 1.10

### ISSUE THREAD

**Issue by kiennguyen94** [microsoft/onnxruntime#10977]
**Describe the bug**
Load time of `.onnx` format model with external data increases 2-3 times going from v1.7 to v1.10. Observed with C++ api.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7
- ONNX Runtime installed from (source or binary): installed from source
- ONNX Runtime version: tag v1.10.0
- Python version: None
- Visual Studio version (if applicable): None
- GCC/Compiler version (if compiling from source): GCC 7.5.0
- CUDA/cuDNN version: None
- GPU model and memory: None

**To Reproduce**
- Simply load any models (bigger better) and observe the slowdown
```
    typedef std::unique_ptr<Ort::Env> OrtEnvPtr;
    typedef std::unique_ptr<Ort::Session> OrtSessPtr;
    typedef std::unique_ptr<Ort::RunOptions> OrtRunOpt;
    OrtEnvPtr ort_env = OrtEnvPtr(new Ort::Env(ORT_LOGGING_LEVEL_VERBOSE));
    Ort::SessionOptions ort_opts;
    ort_opts.SetGraphOptimizationLevel(ORT_ENABLE_BASIC);
    ort_opts.SetExecutionMode(ORT_SEQUENTIAL);
    ort_opts.SetIntraOpNumThreads(1);
    ort_opts.SetInterOpNumThreads(1);
    auto start = std::chrono::high_resolution_clock::now();
    OrtSessPtr sess = OrtSessPtr(new Ort::Session(*ort_env, argv[1], ort_opts));
    auto end = std::chrono::high_resolution_clock::now();
    std::cout << "time " << std::chrono::duration_cast<std::chrono::milliseconds>(end-start).count() << std::endl;
```
- Sample cmake project that does this: https://github.com/kiennguyen94/ort_load_repro
- Sample model: https://github.com/kiennguyen94/ort_load_repro/blob/master/citrinet.tgz, just untar, compile the test project, then
```
./main citrinet_ext_1/citrinet.onnx
```

**Expected behavior**
Building against v1.7, load time is ~190ms
Against v1.10, load time is ~600ms

**Screenshots**
N/A

**Additional context**
I suspect that the culprit is this commit https://github.com/microsoft/onnxruntime/pull/6820/commits/fcbc171dc5c4c5a47fdb94de042a3e537e5adee1 

Prior to the commit, when data is mmap, we skip calling `UnpackTensor` thanks to this block 
```
if (endian::native == endian::little && raw_data != nullptr && deleter_for_file_data.d.f != nullptr) {
      tensor_data = raw_data;
      MoveOrtCallback(deleter_for_file_data.d, deleter);
    }
```
after the commit, `UnpackTensor` always gets called.

This commit https://github.com/kiennguyen94/onnxruntime/commit/cbd8e4c58fafebd3cf0aafc8206a59d928dd3fa0 from my fork seems to fix the load time, but of course creates a memory leak, since the deleter callback is no longer available.

Edit:
I can confirm that commit `4a4488baa` introduces the behavior.

**Comment by RandySheriffH** [comment]
@chenfucn : comments?

**Comment by chenfucn** [comment]
I haven't worked on this part for over a year now. let me spend some time on this.

**Comment by chenfucn** [comment]
ok here is the trade off: when the function TensorProtoToTensor is called, tensor memory is already allocated. In most cases onnxruntime pre-allocate memory for most tensors on one continuous memory region. This would greatly reduce memory fragmentation and also reduce memory usage. However this makes freeing individual tensor memory difficult. 

Now the case of directly mapping raw data to tensors, this requires extra memory holding that raw data to be held on for the life time of the tensor, which is forever.  It's a waste of memory, which is a bigger concern for us than loading time.

So we need a solution that only pre-allocate memory for tensors that can not be directly mapped. A year ago when I worked on this, this "optimal" solution need an overhaul of session initialization, for which we do not have resources.

**Comment by chenfucn** [comment]
It was just an idea, probably I should not have used the word 'solution'. in session_state_utils.cc function SaveInitializedTensors computes the total memory needed for constant tensors. These are called initializers in the comments. We don't really know whether the initializers can be memory mapped or not when SaveInitializedTensors is called. So we have to allocate for all constant tensors.
