### ISSUE TITLE
Onnxruntime slower than tensorflow keras when infer data

### ISSUE THREAD

**Issue by chunweihuangya** [microsoft/onnxruntime#10989]
**Describe the bug**
I using tf2onnx convert resnet50 h5 model to onnx model, then using onnxruntime infer data. But onnxruntime is slower than keras predict.

**Urgency**
none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version: gpu 1.10.0
- Python version: 3.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2 / 8.1.0
- GPU model and memory: RTX 3070 Ti 8 GB

**To Reproduce**
- Describe steps/code to reproduce the behavior.

```
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input
import onnxruntime as ort
import os
import pandas as pd
import time

so = ort.SessionOptions()
so.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
providers = [
    ('CUDAExecutionProvider', {
        'device_id': 0,
        'arena_extend_strategy': 'kNextPowerOfTwo', #'kNextPowerOfTwo', 'kSameAsRequested' 
        'cudnn_conv_algo_search': 'EXHAUSTIVE', # 'EXHAUSTIVE', 'HEURISTIC', 'DEFAULT'
        'do_copy_in_default_stream': False,
        'cudnn_conv_use_max_workspace': '1' # '0', '1'
    }),
]

sess = ort.InferenceSession('model.onnx', 
                            sess_options = so, 
                            providers = providers)
							
batch_size = 32
list_pred_onnx = []
dataIndex = 0
imageListArray = []
for image_path in list_file_path:   
    img = image.load_img(image_path, target_size=(img_size, img_size))
    x = image.img_to_array(img)
    imageListArray.append(x)
    dataIndex = dataIndex + 1
    if ((dataIndex % batch_size) == 0) or (dataIndex == len(list_file_path)):
        image_np_array = np.array(imageListArray)
        image_np_array = preprocess_input(image_np_array)      
        image_np_array = image_np_array if isinstance(image_np_array, list) else [image_np_array]                 
		feed = dict([(input.name, image_np_array[n]) for n, input in enumerate(sess.get_inputs())])        
        pred_onnx = sess.run(None, feed)       
        for pred in pred_onnx[0]:
            list_pred_onnx.append(np.argmax(pred))        
        imageListArray = []

```
**Expected behavior**
The onnx model should have given much higher inference speeds than h5 model

**Screenshots**
test images : 512 pcs 
tensorflow keras h5 model infer time:
![2022-03-24_143227](https://user-images.githubusercontent.com/18112635/159856371-777c4b43-76d4-489b-ae61-46681505ae53.jpg)

onnxruntime onnx model infer time:
![2022-03-24_142557](https://user-images.githubusercontent.com/18112635/159856381-5f387deb-1357-4c7f-a40a-8f0ec4e651d8.jpg)

**Comment by skottmckay** [comment]
There's no info on how or what you're timing in the python you've shared. For the most accurate time, create the InferenceSession, call Run once (this will initialize a lot of things), and time just the subsequent calls to Run. Otherwise you're including a lot of one-off costs to optimize later calls to Run.

**Comment by chunweihuangya** [comment]
Thanks! Run once is faster
