### ISSUE TITLE
Could not find an implementation for Trilu node - ORT Model Optimizer

### ISSUE THREAD

**Issue by mstfbl** [microsoft/onnxruntime#10994]
**Describe the bug**
We are seeing the following error when using the [ONNX Model optimizer](https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/transformers#model-optimizer) to optimize our ONNX exported model:
```bash
Traceback (most recent call last):
  File "/repos/onnxruntime/onnxruntime/python/tools/transformers/optimizer.py", line 391, in <module>
    main()
  File "/repos/onnxruntime/onnxruntime/python/tools/transformers/optimizer.py", line 367, in main
    optimizer = optimize_model(args.input,
  File "/repos/onnxruntime/onnxruntime/python/tools/transformers/optimizer.py", line 222, in optimize_model
    temp_model_path = optimize_by_onnxruntime(input, use_gpu=False, opt_level=1)
  File "/repos/onnxruntime/onnxruntime/python/tools/transformers/optimizer.py", line 91, in optimize_by_onnxruntime
    session = onnxruntime.InferenceSession(onnx_model_path,
  File "/opt/conda/envs/TorchNightly/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/opt/conda/envs/TorchNightly/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 381, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for Trilu(14) node with name 'Trilu_77'
```
I've attached the full run logs to this issue: 
[model_optimizer_full_run_logs.txt](https://github.com/microsoft/onnxruntime/files/8344973/model_optimizer_full_run_logs.txt)

**Urgency**
This is in regard to exporting the RIIID Kaggle Model ([GitHub repo](https://github.com/mstfbl/riiid-acp-pub), [Overview of model](https://www.kaggle.com/c/riiid-test-answer-prediction/discussion/209585)) to using ORT for inferencing. This model was generated with [this ](https://github.com/mstfbl/riiid-acp-pub/blob/f13fbee105ed3d2bfe4b0399e3c96b4969064754/05_inference_no_fastai_torch_export.py#L846-L856)ONNX export command.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 20.04
- ONNX Runtime installed from (source or binary): Binary
- ONNX Runtime version: 1.11.0.dev20220321003+cu111
- Python version: 3.8
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CU111/8.0.5
- GPU model and memory: 8 Nvidia Tesla V100 GPUs/ND40rsv2 Azure VMs

**To Reproduce**
[Link](https://microsoft-my.sharepoint.com/:u:/p/mubal/EUpjrAyqe31IkjmrWSbsNRgBPsMx63g2fj5ALSVdAcfOuw?e=mBZ6rO) to ONNX model in question
This same error is seen with the following commands:
```bash
python /repos/onnxruntime/onnxruntime/python/tools/transformers/optimizer.py --input generated_models/model1_exported.onnx --output generated_models/model1_exported_bert.onnx --model_type bert
python /repos/onnxruntime/onnxruntime/python/tools/transformers/optimizer.py --input generated_models/model1_exported.onnx --output generated_models/model1_exported_gpt2.onnx --model_type gpt2 --num_heads 16 --hidden_size 1024
python /repos/onnxruntime/onnxruntime/python/tools/transformers/optimizer.py --input generated_models/model1_exported.onnx --output generated_models/model1_exported_tnlr.onnx --model_type tnlr --num_heads 16 --hidden_size 1024
```

**Expected behavior**
I wish to optimize this model so that the performance of running inferencing with this model is comparable to running its PyTorch vanilla version.

**Comment by hanbitmyths** [comment]
Trilu has different supporting type for CPUExecutionProvider and CUDAExecutionProvider. Since your target device is GPU, you can try '--use_gpu' option with optimizer script.

It seems that optimizer isn't updated for a change to set an explicit execution provider when creating a session. We'll fix this issue.

**Comment by mstfbl** [comment]
@hanbitmyths I've tried the optimizer commands above with the `--use_gpu` flag, I am seeing the same error I've shared.

**Comment by wangyems** [comment]
Hi @mstfbl, you can work around this by modifying this line https://github.com/microsoft/onnxruntime/blob/0d09dd5d20c3a5133e6e6ae1218cdc45ccaf0358/onnxruntime/python/tools/transformers/optimizer.py#L222 with use_gpu=True and run with --use_gpu flag

**Comment by wangyems** [comment]
> Trilu has different supporting type for CPUExecutionProvider and CUDAExecutionProvider. Since your target device is GPU, you can try '--use_gpu' option with optimizer script.
> 
> It seems that optimizer isn't updated for a change to set an explicit execution provider when creating a session. We'll fix this issue.

I'm a little concerned about this fix: If using cuda ep in optimize_by_onnxruntime(), the exported model will contain "memcpy" and runs only on cuda ep.
