### ISSUE TITLE
Accessing OrtStatus from external C code

### ISSUE THREAD

**Issue by matteosal** [microsoft/onnxruntime#10993]
C API functions return a pointer to an `OrtStatus` objects which is not fully defined in `onnxruntime_c_api.h`. As a result, code like this fails to compile with message `invalid use of incomplete type ‘OrtStatus’ {aka ‘struct OrtStatus’}` when trying to access `status->code` and `status->msg`:
```
#include "onnxruntime_c_api.h"
...
	OrtStatus *status = ort_api->CreateSession(ort_env, file_path, session_options, &session);
	if(status != nullptr) {
		// access status->code and status->msg
	}
```
So what is the recommended way to access `OrtStatus` fields?

**Comment by snnn** [comment]
Use the GetErrorCode and GetErrorMessage functions. 

https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h#L601
