### ISSUE TITLE
Sigmoid and relu ONNXRuntimeError

### ISSUE THREAD

**Issue by olegzhos** [microsoft/onnxruntime#11012]
Hello everybody! I have the next error when I inference sigmoid and relu operators with dtype=float64(double), opset version=11:

self._create_inference_session(providers, provider_options)
self = <onnxruntime.capi.onnxruntime_inference_collection.InferenceSession object at 0x7fd0734ef220>
providers = None, provider_options = None

def _create_inference_session(self, providers, provider_options):
    # Tensorrt can fall back to CUDA. All others fall back to CPU.
    if 'TensorrtExecutionProvider' in C.get_available_providers():
        self._fallback_providers = ['CUDAExecutionProvider', 'CPUExecutionProvider']
    else:
        self._fallback_providers = ['CPUExecutionProvider']

    session_options = self._sess_options if self._sess_options else C.get_default_session_options()
    if self._model_path:
        sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    else:
        sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)

    # initialize the C++ InferenceSession
  sess.initialize_session(providers or [], provider_options or [])
E onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Sigmoid(Relu)

I inference these activation functions succesfully when I use dtype=float16 or float32. It looks strange bacause in all the opset versions of these operators according to https://github.com/onnx/onnx/blob/main/docs/Changelog.md Type Constraints: T : tensor(float16), tensor(float), tensor(double). But it seems to me dtype=float64 is not supported in reality

**Comment by skottmckay** [comment]
Whilst ORT does not implement every single type the ONNX spec includes, both Sigmoid and Relu support double. Are you sure your model is defined correctly? The error message usually says the operator name, and `Sigmoid(Relu)` is not a valid operator name.

**Comment by olegzhos** [comment]
@skottmckay, I'm sorry for confusing. I have written (Relu) in the end of the message error myself. It means in the first case (sigmoid inference):
E onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Sigmoid,
and in the second case (relu inference):
E onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Relu.
I supose my model is defined correctly

**Comment by skottmckay** [comment]
Are you able to share the model? 

Not sure what ORT version you are using as you didn't fill out the requested information for creating a new issue.

**Comment by olegzhos** [comment]
@skottmckay,
[activations.zip](https://github.com/microsoft/onnxruntime/files/8397706/activations.zip)

**Comment by skottmckay** [comment]
I tried with ORT v1.10 without issue. If a kernel wasn't able to be found the model load would fail. 

```
>>> import onnxruntime as ort
>>> s = ort.InferenceSession('sigmoid.onnx')
>>> s = ort.InferenceSession('relu.onnx')
>>>
```

Can you please provide step-by-step instructions to reproduce, including details of the specific ORT python package you're using?

**Comment by olegzhos** [comment]
My ORT version is 1.6. Thank you for your reply! I have tried to use other newer versions of ORT after your last comment and I have noticed if I use ORT v.1.7 and newer I inference these operators with dtype=double successfully
