### ISSUE TITLE
MAUI: Unable to use ONNX: Reference to type 'ReadOnlySpan<>' claims it is defined in 'mscorlib', but it could not be found

### ISSUE THREAD

**Issue by jdluzen** [microsoft/onnxruntime#11013]
**Describe the bug**
This bug was originally on [MAUI](https://github.com/dotnet/maui/issues/5078), but was advised to move it to here.
I am unable to use `Microsoft.ML.OnnxRuntime.Managed` with MAUI, it works on a regular net6.0 library, and latest Xamarin Forms.
Error: `Reference to type 'ReadOnlySpan<>' claims it is defined in 'mscorlib', but it could not be found`

**Urgency**
None, though it is a complete blocker.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MAUI Android
- ONNX Runtime installed from (source or binary): Nuget binary
- ONNX Runtime version: 1.10 and 1.11
- Python version: N/A
- Visual Studio version (if applicable): VS 2022 Preview 2.0
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
Repro here: https://github.com/dotnet/maui/issues/5078#issuecomment-1069738942

**Expected behavior**
Compilation.

**Screenshots**
N/A

**Additional context**
It works with Xamarin Forms.

**Comment by skottmckay** [comment]
Possibly a new iteration of a longstanding issue with System.Memory.

https://stackoverflow.com/a/69770184
https://stackoverflow.com/a/63825340

I tried adding references to System.Memory and System.Buffers but it didn't help. 

@mikeparker104 any ideas about how to work around this?

**Comment by skottmckay** [comment]
I tried adding net6.0 as a target framework and your test app at least builds with that. Zip file (to make github happy) with the nupkg is attached. It was built from the current master with configuration of Release. Only diff is this:

https://github.com/microsoft/onnxruntime/compare/skottmckay/TestNet6TargetFramework

[Microsoft.ML.OnnxRuntime.Managed.1.12.0-dev-20220405-1036-60f4d6a03.nupkg.zip](https://github.com/microsoft/onnxruntime/files/8417274/Microsoft.ML.OnnxRuntime.Managed.1.12.0-dev-20220405-1036-60f4d6a03.nupkg.zip)
 
You will need to put the nupkg file in a local folder, add that folder as a nuget package source, and update the test app to use it. No change to the native package (Microsoft.ML.OnnxRuntime) is needed.

We will need additional infrastructure to handle all the different .net 6 platforms gracefully. If this at least builds and runs it's a step in the right direction.

**Comment by salarcode** [comment]
Hope #11908 fixes this issue

**Comment by skottmckay** [comment]
Should do. Here's a zipped nuget package with those changes if you want to test it out.

[Microsoft.ML.OnnxRuntime.Managed.1.12.0-dev-20220619-0602-c3e78373d.zip](https://github.com/microsoft/onnxruntime/files/8953628/Microsoft.ML.OnnxRuntime.Managed.1.12.0-dev-20220619-0602-c3e78373d.zip)

**Comment by salarcode** [comment]
I can confirm that with this dev package the sample project is building and working correctly in both Windows and Android.
I've used the sample tutorial here: https://onnxruntime.ai/docs/tutorials/resnet50_csharp.html

Thank you for the zip file. I can now proceed with my project :)

**Comment by skottmckay** [comment]
Should be resolved with 1.12 which is now released.
