### ISSUE TITLE
MlasConvertHalfToFloatBuffer   the CPU usage is high.

### ISSUE THREAD

**Issue by ms-zhibinwang** [microsoft/onnxruntime#11022]
**Describe the bug**
![image](https://user-images.githubusercontent.com/95850872/160389909-9a7f464f-91a1-484b-b72a-9b9ce45c59d2.png)

**System information**
win, onnx 1.7 cpu 32core
hi , I use onnx, I found the model Inference has performance problems. CAST half to float. 
MlasConvertHalfToFloatBuffer   why cpu usage high?

**Comment by yuslepukhin** [comment]
@chenfucn

**Comment by skottmckay** [comment]
Can you share the model? If the model uses fp16 data it is likely to have a lot of conversions to fp32 to run on the CPU EP as the CPU kernels generally do not have fp16 support. 

fp16 is much better supported on GPU (e.g. CUDA EP).

**Comment by ms-zhibinwang** [comment]
@skottmckay thanks, i see

**Comment by SolomidHero** [comment]
@ms-zhibinwang ,
sorry for offtop. But how did you profile onnx model and built such flamegraph? Is it python util?
