### ISSUE TITLE
A core dump happens when sending zero shape input to Mul operator

### ISSUE THREAD

**Issue by maybeLee** [microsoft/onnxruntime#11024]
**Describe the bug**
I was generating a ONNX graph which will produce a zero shape tensor to Mul operator. After I construct this graph and send it to the `onnxruntime` for inference, it will directly result in a core dump. The ONNX graph is as follows, and can be accessed through this [file](https://drive.google.com/file/d/1NPLMO7mxIVkD1jk4c5a-5Ym2vWNo8Mlp/view?usp=sharing).

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/32777264/160444586-06398d63-f99f-4927-819d-0ef322ae92b2.png">

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- ONNX Runtime installed from (source or binary):binary
- ONNX Runtime version:1.11.0
- Python version:3.7
- Visual Studio version (if applicable):N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
The ONNX model can be loaded from [here](https://drive.google.com/file/d/1NPLMO7mxIVkD1jk4c5a-5Ym2vWNo8Mlp/view?usp=sharing)

After downloading the ONNX model and save as `generated_model.onnx`, you may run the following code to reproduce the bug:
```
import onnxruntime as ort
providers = [
    'CPUExecutionProvider',
]
onnx_path = "generated_model.onnx"
model = ort.InferenceSession(onnx_path, providers=['CPUExecutionProvider'])
```

**Expected behavior**
I think a core dump should not be allowed.

**Comment by fs-eire** [comment]
Thanks for reporting this issue.

In my understanding, the behavior of operator Mul dealing with zero shape input is undefined. It could be an ORT failure or a silent success (what will be the output? a zero shaped tensor?), but should not be a crash (core dump).

**Comment by maybeLee** [comment]
Hi, for your information, I construct this graph by generating a keras model and convert to ONNX following below code:
```
import numpy as np
input = np.random.rand(10,10)
import keras
x = keras.layers.Input((10,))
y1 = keras.layers.Dense(0)(x)
y = keras.layers.Dot(axes=-1)([y1,y1])
keras_model = keras.models.Model(x,y)
keras_model.save("generated_model.h5")
keras_output = keras_model.predict(input)
print(keras_output)

import tensorflow as tf
import tf2onnx
def transform_onnx(model_path: str):
    model = keras.models.load_model(model_path)
    model_name = model_path.split(".h5")[0]
    onnx_path = f"{model_name}.onnx"
    input_shape = model.layers[0].input_shape[0]
    spec = (tf.TensorSpec(input_shape, tf.float32, name="input"),)
    _, _ = tf2onnx.convert.from_keras(model, input_signature=spec, \
        opset=15, output_path=onnx_path)
transform_onnx("generated_model.h5")
```

The model output of keras is:
```
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
```

**Comment by ytaous** [comment]
I can repro the seg fault on InferenceSession creation, is this the same for you? e.g., you didn't even get to run() yet, correct?

    ort_session = ort.InferenceSession(onnx_path, providers=providers, sess_option=sess_option)

**Comment by maybeLee** [comment]
Yes, the program will crash during the InferenceSession creation. I didn't actually inference the graph

**Comment by ytaous** [comment]
Hi, thanks for reporting the issue. Although the PR will address the core dump issue. However, your testing model is edge case and it won't pass the "ReduceSum" op that we enforce the check on the keepdim value internally. 

![image](https://user-images.githubusercontent.com/4484531/160545625-5d4f563a-53e0-4655-99ab-bb838d3b28be.png)


Like so:
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    res = ort_session.run(output_names, {input_name0: input})
  File "/bert_ort/ettao/conda/py38/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running ReduceSum node. Name:'dot_1_1/Sum' Status Message: /bert_ort/ettao/ort-0328/onnxruntime/onnxruntime/core/providers/cpu/reduction/reduction_ops.cc:763 void onnxruntime::ValidateKeepDims(const onnxruntime::TensorShape&, int64_t) keepdims was false. Can't reduce on dim with value of 0 if 'keepdims' is false. Invalid output shape would be produced. input_shape:{10,0}

I did a quick test to hardcode keepdim=1 in the code, I am able to finish the inference and get results:

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

Here is my sample code in case:

import onnx
import onnx.numpy_helper
import onnxruntime as ort
from collections import OrderedDict
import numpy as np

  
if __name__=="__main__":

    providers = ['CPUExecutionProvider']
    sess_option = ort.SessionOptions()
    onnx_path = "/bert_ort/ettao/dri-test/generated_model.onnx"
    ort_session = ort.InferenceSession(onnx_path, providers=providers, sess_option=sess_option)

    # should be input_1 here
    input_name0 = ort_session.get_inputs()[0].name
    print(ort_session.get_inputs()[0].shape)
    # dot_1
    output_names = [x.name for x in ort_session.get_outputs()]
    print("ort_outnames:{0}".format(output_names))

    input = np.random.rand(10,10).astype('f')
    res = ort_session.run(output_names, {input_name0: input})

    ort_outputs = []
    for output in ort_session.get_outputs():
        ort_outputs.append(output)

    print(res)
    print(res[0])

    print("finished")

**Comment by ytaous** [comment]
hi, the PR has been merged, you can try our nightly in a couple days, thx.
https://download.onnxruntime.ai/

**Comment by maybeLee** [comment]
Hi, sorry for the late reply, I was trapped by something else. Thanks a lot for your prompt action.
