### ISSUE TITLE
pip install onnxruntime --- No matching distribution found for onnxruntime

### ISSUE THREAD

**Issue by davidatorres** [microsoft/onnxruntime#11037]
**Describe the bug**
Unable to install onnxruntime via pip/pip3

**Urgency**
Trying to get this up and running for a business project we have due in a couple weeks.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11 & Mac OSX (latest)
- ONNX Runtime installed from (source or binary): binary (attempting - pip install onnxruntime)
- ONNX Runtime version: 1.11.0
- Python version: 3.9
- Visual Studio version (if applicable): VS Code (latest) / Juptyer (latest)
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
`pip install onnxruntime`

**Expected behavior**
Installation of runtime libraries

**Screenshots**
![2022-03-28_16-39-04](https://user-images.githubusercontent.com/10944960/160504666-2513aff0-093c-4b1f-94be-e49e8a27a940.png)

**Comment by faxu** [comment]
CC @chilo-ms 

Does this repro on Windows or just on Mac? What is the specific version of Mac you are using?

**Comment by ShomyLiu** [comment]
Same issue on MacOS with MacBook Pro( M1 2020) , macOS Monterey 12.1;
Python 3.9
```
pip3 install onnxruntime 
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime
```
@faxu  @chilo-ms

**Comment by pranavsharma** [comment]
We don't support packages for M1 yet.
It works just fine for other macosx versions. Tested on Catalina 10.15.7.
```
(py39) MACHINE-M-Q132:~ MACHINE$ pip install onnxruntime
Collecting onnxruntime
  Downloading onnxruntime-1.11.0-cp39-cp39-macosx_10_15_x86_64.whl (5.7 MB)
     |████████████████████████████████| 5.7 MB 3.5 MB/s 
Collecting numpy>=1.21.0
  Downloading numpy-1.22.3-cp39-cp39-macosx_10_14_x86_64.whl (17.6 MB)
     |████████████████████████████████| 17.6 MB 4.2 MB/s 
Collecting flatbuffers
  Downloading flatbuffers-2.0-py2.py3-none-any.whl (26 kB)
Collecting protobuf
  Downloading protobuf-3.19.4-cp39-cp39-macosx_10_9_x86_64.whl (961 kB)
     |████████████████████████████████| 961 kB 3.6 MB/s 
Installing collected packages: protobuf, numpy, flatbuffers, onnxruntime
Successfully installed flatbuffers-2.0 numpy-1.22.3 onnxruntime-1.11.0 protobuf-3.19.4

(py39) MACHINE-M-Q132:~ MACHINE$ python -V
Python 3.9.11
(py39) MACHINE-M-Q132:~ MACHINE$ python
Python 3.9.11 (main, Mar 28 2022, 05:06:49) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.

i>>> import onnxruntime as rt
>>> rt.__version__
'1.11.0'
>>> 
```

**Comment by troyliu0105** [comment]
for now, there is a workaround for u. to install onnxruntime on Apple silicon with conda-forge
```shell
conda install onnxruntime -c conda-forge
``` 
@ShomyLiu @davidatorres

**Comment by mattbell87** [comment]
I'm getting this error just today on Windows and Docker (alpine container)

**Comment by ShomyLiu** [comment]
@troyliu0105  thanks for the solution.  That is indeed works except that I have to install anconda and set a new python environmen since i use the native python environment.
Thanks all.

**Comment by troyliu0105** [comment]
> @troyliu0105 thanks for the solution. That is indeed works except that I have to install anconda and set a new python environmen since i use the native python environment. Thanks all.

And I tried to compile the wheels for Python 3.8/3.9 (Apple Silicon), maybe u need it. and here is the command I used to compile them (Tested on Macbook M1 Pro)
```shell
./build.sh --config Release --osx_arch arm64 --osx_arch arm64 --build_wheel --enable_pybind --parallel --use_coreml --use_extensions --skip_tests --build_shared_lib
```
<img width="654" alt="image" src="https://user-images.githubusercontent.com/5518286/160582362-1aea10f1-b8cd-447e-9443-dbef125907ec.png">


[onnxruntime-1.11.0-cp38-cp38-macosx_12_0_arm64.whl](https://storage.asswecan.org:9443/f/a74e04178247436eb6c0/?dl=1)
[onnxruntime-1.11.0-cp39-cp39-macosx_12_0_arm64.whl](https://storage.asswecan.org:9443/f/f4b7fb28b2f74709a76e/?dl=1)

**Comment by ShomyLiu** [comment]
@troyliu0105  great! 
Thanks a lot for this compile command and the whl files. It helps a lot

**Comment by davidatorres** [comment]
@troyliu105  - Using Conda worked for me on Mac OSX with Python 3.9, but fails on Windows with Python 3.10.

`conda install onnxruntime -c conda-forge`

**Comment by venttola** [comment]
Same issue on Manjaro Linux 21.2.5 with Python 3.10.2.
`pip install -r requirements.txt 
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.7.0 (from versions: none)
ERROR: No matching distribution found for onnxruntime==1.7.0`

However my docker build works and I am using public.ecr.aws/lambda/python:3.8 as base image.

**Comment by troyliu0105** [comment]
@davidatorres @venttola for now, offical pypi only has wheels for 3.7 to 3.9. If you wanna use onnxruntime with 3.10. You should compile it by yourself.

**Comment by venttola** [comment]
@troyliu0105 Thanks! I should have probably discovered this by myself. Works with Python 3.9.

**Comment by faxu** [comment]
We'll plan to add 3.10 soon so thank you for your input!

**Comment by amibeuret** [comment]
> > @troyliu0105 thanks for the solution. That is indeed works except that I have to install anconda and set a new python environmen since i use the native python environment. Thanks all.
> 
> And I tried to compile the wheels for Python 3.8/3.9 (Apple Silicon), maybe u need it. and here is the command I used to compile them (Tested on Macbook M1 Pro)
> 
> ```shell
> ./build.sh --config Release --osx_arch arm64 --osx_arch arm64 --build_wheel --enable_pybind --parallel --use_coreml --use_extensions --skip_tests --build_shared_lib
> ```
> 
> <img alt="image" width="654" src="https://user-images.githubusercontent.com/5518286/160582362-1aea10f1-b8cd-447e-9443-dbef125907ec.png">
> 
> [onnxruntime-1.11.0-cp38-cp38-macosx_12_0_arm64.whl](https://storage.asswecan.org:9443/f/a74e04178247436eb6c0/?dl=1) [onnxruntime-1.11.0-cp39-cp39-macosx_12_0_arm64.whl](https://storage.asswecan.org:9443/f/f4b7fb28b2f74709a76e/?dl=1)

Thanks, this was really helpful!

**Comment by themanyone** [comment]
Thanks for suggestions. I had to use `python3.1 -m pip install onnxruntime` because of python3.11 being default.

**Comment by wixphotos** [comment]
> We don't support packages for M1 yet. It works just fine for other macosx versions. Tested on Catalina 10.15.7.
> 
> ```
> (py39) MACHINE-M-Q132:~ MACHINE$ pip install onnxruntime
> Collecting onnxruntime
>   Downloading onnxruntime-1.11.0-cp39-cp39-macosx_10_15_x86_64.whl (5.7 MB)
>      |████████████████████████████████| 5.7 MB 3.5 MB/s 
> Collecting numpy>=1.21.0
>   Downloading numpy-1.22.3-cp39-cp39-macosx_10_14_x86_64.whl (17.6 MB)
>      |████████████████████████████████| 17.6 MB 4.2 MB/s 
> Collecting flatbuffers
>   Downloading flatbuffers-2.0-py2.py3-none-any.whl (26 kB)
> Collecting protobuf
>   Downloading protobuf-3.19.4-cp39-cp39-macosx_10_9_x86_64.whl (961 kB)
>      |████████████████████████████████| 961 kB 3.6 MB/s 
> Installing collected packages: protobuf, numpy, flatbuffers, onnxruntime
> Successfully installed flatbuffers-2.0 numpy-1.22.3 onnxruntime-1.11.0 protobuf-3.19.4
> 
> (py39) MACHINE-M-Q132:~ MACHINE$ python -V
> Python 3.9.11
> (py39) MACHINE-M-Q132:~ MACHINE$ python
> Python 3.9.11 (main, Mar 28 2022, 05:06:49) 
> [Clang 12.0.0 ] :: Anaconda, Inc. on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> 
> i>>> import onnxruntime as rt
> >>> rt.__version__
> '1.11.0'
> >>> 
> ```

Hi, any idea when M1, M2 and M3 will be supported?

**Comment by jainabhishek** [comment]
I faced the same issue and the following command worked for me:
`python3 -m pip install onnxruntime`

**Comment by sidsarasvati** [comment]
> I faced the same issue and the following command worked for me: `python3 -m pip install onnxruntime`

This worked 
Why?

**Comment by devinschumacher** [comment]
> > I faced the same issue and the following command worked for me: `python3 -m pip install onnxruntime`
> 
> This worked Why?

Running python3 -m pip install onnxruntime ensures that onnxruntime is installed in the specific environment associated with the python3 command.

maybe you were accident installing to a diff env?

**Comment by hteeyeoh** [comment]
Facing the same issue here: I was using an python3.10-alpine base image for my container application.
When I try to install onnxruntime, 
 > [build 7/8] RUN pip install onnxruntime:
0.977 ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
0.990 ERROR: No matching distribution found for onnxruntime

Any comment or suggestion for next steps?

**Comment by lucifiel1618** [comment]
> Facing the same issue here: I was using an python3.10-alpine base image for my container application. When I try to install onnxruntime,
> 
> > [build 7/8] RUN pip install onnxruntime:
> > 0.977 ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
> > 0.990 ERROR: No matching distribution found for onnxruntime
> 
> Any comment or suggestion for next steps?

same for me with the official python3.11-alpine image

**Comment by hteeyeoh** [comment]
> > Facing the same issue here: I was using an python3.10-alpine base image for my container application. When I try to install onnxruntime,
> > > [build 7/8] RUN pip install onnxruntime:
> > > 0.977 ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
> > > 0.990 ERROR: No matching distribution found for onnxruntime
> > 
> > 
> > Any comment or suggestion for next steps?
> 
> same for me with the official python3.11-alpine image

Seems like is because alpine linux does not support that.
