### ISSUE TITLE
cuda memory free or empty cashe on python

### ISSUE THREAD

**Issue by zelabean** [microsoft/onnxruntime#11057]
**Is your feature request related to a problem? Please describe.**

Hello, I am doing deep learning inference using onnxruntime-gpu.

I want to see the memory usage in nvidia-smi using pytorch's torch.cuda.empty_cache() function. Is there a method that has the same or similar function in python when using onnxruntime?

The runtime session should be persisted and should only be removed when the program exits.

**System information**
- ONNX Runtime version (you are using):
1.8.0

**Comment by ytaous** [comment]
Yes, you can look it up on internet:
psutil will be good:
https://stackoverflow.com/questions/938733/total-memory-used-by-python-process
https://stackoverflow.com/questions/58216000/get-total-amount-of-free-gpu-memory-and-available-using-pytorch

**Comment by lfxx** [comment]
> Yes, you can look it up on internet: psutil will be good: [stackoverflow.com/questions/938733/total-memory-used-by-python-process](https://stackoverflow.com/questions/938733/total-memory-used-by-python-process) [stackoverflow.com/questions/58216000/get-total-amount-of-free-gpu-memory-and-available-using-pytorch](https://stackoverflow.com/questions/58216000/get-total-amount-of-free-gpu-memory-and-available-using-pytorch)

Will you update a functiun which can free cuda memory while keeping runtime session running.It is sth like torch.cuda.empty_cache().
