### ISSUE TITLE
Missing benchmark_t5.py

### ISSUE THREAD

**Issue by azsh1725** [microsoft/onnxruntime#11052]
Hi, 
The repository does not contain the file for the benchmarking of T5 based models. Could you add the file or tell me where it can be found?

Reference to file can be found here: https://github.com/microsoft/onnxruntime/blob/1424b796ff0af60b1d8b6e96fdc61515b41b305f/onnxruntime/python/tools/transformers/huggingface_models.py#:~:text=%23%20T5%20(use%20benchmark_t5.py%20instead

**Comment by azsh1725** [comment]
In addition, I would like to note that there is a problem with importing recently added scripts for the T5 model. It seems to me that there are problems with the build for the latest version (1.11.0), because not in a pip package, not when building from source, I was unable to import everything that is [here](https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/transformers/models)

**Comment by ytaous** [comment]
@tianleiwu - any idea on this line commented out?

**Comment by tianleiwu** [comment]
@azsh1725, the benchmark_t5.py script in tlwu/benchmark_t5 branch was not up to date. We will have an updated script and add it to master branch. (We are still working on the integration of t5 and beam search. Hopefully, it will be able to available to try in a few weeks. After that, new benchmark script for t5 will be added.)

You are right, t5 onnx conversion script is not in pip package. I will add it to pip package later. For now, you can directly run it from the source directory like the following:
```
git clone https://github.com/microsoft/onnxruntime.git
cd onnxruntime/onnxruntime/python/tools/transformers/models/t5
python convert_to_onnx.py --help
```

**Comment by azsh1725** [comment]
@tianleiwu Thanks for the clarifications. Looking forward to t5 benchmark.
