### ISSUE TITLE
onnxruntime runs inference on CPU even though GPU is available

### ISSUE THREAD

**Issue by sicklife** [microsoft/onnxruntime#11086]
**Describe the bug**
here is my code:
```python
[root@ip-10-0-137-89 demo]# cat onnx_test.py 

import onnxruntime as ort
print(f"the available provider is : {ort.get_available_providers()}")

provider =  ['CUDAExecutionProvider', 'CPUExecutionProvider']
ort_sess = ort.InferenceSession('../inference/det_onnx/model.onnx', providers=provider)
ort_sess.set_providers(provider)
print(f"the result of get_provider is: {ort_sess.get_providers()}")

ort_sess.set_providers(['CUDAExecutionProvider'],  provider_options=[{'device_id': 1,}])
print(f"the result of get_provider is: {ort_sess.get_providers()}")

```

here is the output:
```
[root@ip-10-0-137-89 demo]# python3 onnx_test.py 
the available provider is : ['CUDAExecutionProvider', 'CPUExecutionProvider']
the result of get_provider is: ['CPUExecutionProvider']
the result of get_provider is: ['CPUExecutionProvider']


```

**Urgency**
Yes

**System information**
- OS Platform and Distribution: centos rhel fedora/Amazon Linux 2
- ONNX Runtime installed from :  python3.7 -m pip install onnxruntime-gpu==1.9.0 
- ONNX Runtime version: 1.9.0
- Python version: 3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.4
- GPU model and memory: Tesla T4/15G

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**
use gpu.

**Comment by sicklife** [comment]
[model.zip](https://github.com/microsoft/onnxruntime/files/8398121/model.zip)
here is my  model

**Comment by ytaous** [comment]
Hi, can you please latest version and see?
I tested your code in my dev env from latest master, it works fine:
the available provider is : ['CUDAExecutionProvider', 'CPUExecutionProvider']
the result of get_provider is: ['CUDAExecutionProvider', 'CPUExecutionProvider']
the result of get_provider is: ['CUDAExecutionProvider', 'CPUExecutionProvider']

Here is my pip list - FYI:
onnx                     1.10.2
onnxconverter-common     1.9.0
onnxruntime-gpu          1.11.0
onnxruntime-gpu-tensorrt 1.9.0
onnxruntime-olive        0.1.0
onnxruntime-training     1.11.0+cu111
torch                    1.10.0+cu111
torchtext                0.11.0
torchvision              0.11.0+cu111

**Comment by ytaous** [comment]
https://pypi.org/project/onnxruntime/1.11.0/#files

**Comment by sicklife** [comment]
> https://pypi.org/project/onnxruntime/1.11.0/#files

Thank you. I have figure it out.
This turn out to  be a problem of running any GPU-related service on EKS.

EKS has a plugin to control the GPU resources, so only deploy/pod from EKS can use the GPU.

Thank you anyway~ I'll close this issue.

**Comment by satpalsr** [comment]
I am facing same issue on my linux machine.
`onnxruntime-gpu Version: 1.13.1`

I ran the same above code
```
the available provider is : ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
the result of get_provider is: ['CPUExecutionProvider']
the result of get_provider is: ['CPUExecutionProvider']
```
