### ISSUE TITLE
Is TVM Working ? 

### ISSUE THREAD

**Issue by joyIntel** [microsoft/onnxruntime#1108]
There is --use_tvm option for building the onnxruntime. However, is it working for ONNX inference now? What is the way to enable it for ONNX apps?

If it is working, what option(-e) needs to be passed to do the ONNXRuntime Performance Test ?

**Comment by KeDengMS** [comment]
https://github.com/microsoft/onnxruntime/pull/881 is our TVM-based execution provider. It is still being actively worked on.

**Comment by joyIntel** [comment]
Thanks @KeDengMS . So it is not ready to use till now. Am I right ?

**Comment by KeDengMS** [comment]
You can try [Nuphar branch](https://github.com/microsoft/onnxruntime/tree/gt/Nuphar) before it's merged into master. Here is the [build instructions](https://github.com/microsoft/onnxruntime/blob/gt/Nuphar/BUILD.md#nuphar), and [document](https://github.com/microsoft/onnxruntime/blob/gt/Nuphar/docs/execution_providers/Nuphar-ExecutionProvider.md).

**Comment by joyIntel** [comment]
Thanks @KeDengMS
