### ISSUE TITLE
ONNX model gives different outputs when run in python vs javascript

### ISSUE THREAD

**Issue by kheyer** [microsoft/onnxruntime#11095]
**Describe the bug**
The same ONNX model gives different outputs when run in a python environment vs a javascript environment

**System information**
Python info:
• Ubuntu 20.04
• Python 3.8.10
• Pytorch 1.9.0
• ONNX 1.10.2
• ONNX runtime 1.10.0

Javascript info
Running in browser with ORT pulled from `https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.min.js`

**To Reproduce**
I am trying to deploy a GAN model in browser. Currently I am using a toy model that generates `8x8x4` PNG images. The model takes as input a vector of size `(256,)` sampled from a random normal distribution. The model should give the exact same output for a specific input vector. Between runtimes (python, javascript), the output might not be identical, but it should be similar. Currently, python and javascript runtimes are giving completely different results.

Python setup:

```python
layers = nn.Sequential(
            nn.Linear(dim, dim*2),
            nn.Dropout(p=0.3),
            nn.ReLU(),
            nn.Linear(dim*2, dim*2),
            nn.Dropout(p=0.3),
            nn.ReLU(),
            nn.Linear(dim*2, dim),
            nn.ReLU(),
            nn.Linear(dim, dim)
        )

class InferenceModel(nn.Module):
    def __init__(self, layers):
        super().__init__()
        self.layers = layers
        
    def forward(self, input):
        input = input.unsqueeze(0) # convert (256,) to (1,256)
        # model generates an output of float values
        # these floats are clamped to 0,1, multiplied by 255 and converted to Longs
        output = (self.layers(input).clamp(0,1) * 255).type(torch.LongTensor)
        # output is a vector, we reshape to an image
        output = output.view((8,8,4))
        return output

im = InferenceModel(layers)
im.eval() # eval called before onnx trace
im.cpu()

dummy_input = torch.randn((256)
torch.onnx.export(im, args=dummy_input, f='model.onnx', verbose=True, input_names=['input'], output_names=['output'])
```

Python / JS runtimes

Rather than clutter things here, I've attached a zip file with the ONNX model and testing code for both python and javascript

[onnx_example.zip](https://github.com/microsoft/onnxruntime/files/8403643/onnx_example.zip)

```
onnx_example
- js_output.json - javascript output in json format
- main.html - html for javascript testing
- model.onnx - onnx model file
- onnx_test.py - code to test onnx model in python
- python_output.npy - python output in npy format (np.save)
- script.js - javascript snippet for generating an output and saving it to a json file
```

You will notice in `onnx_test.py` and `script.js`, the input vector to the model is hard coded to be the exact same input.

You can see the output arrays in `js_output.json` and `python_output.npy` are significantly different.

**Expected behavior**
Expected greater correspondence between output arrays in python / javascript runtime for the same input vector

**Comment by skottmckay** [comment]
Not sure what's going on. The javascript output seems to have additional '0's between each output value. If I output the index and value for all non-zero values that's a bit clearer. 

@fs-eire any idea why that is?

Javascript |   | Python |  
-- | -- | -- | --
Index | Value | Index | Value
94 | 180 | 47 | 180
102 | 255 | 51 | 255
150 | 253 | 75 | 253
152 | 95 | 76 | 95
154 | 87 | 77 | 87
156 | 67 | 78 | 67
158 | 254 | 79 | 254
166 | 254 | 83 | 254
168 | 16 | 84 | 16
170 | 10 | 85 | 10
172 | 2 | 86 | 2
174 | 255 | 87 | 255
214 | 254 | 107 | 254
216 | 171 | 108 | 171
218 | 111 | 109 | 111
220 | 73 | 110 | 73
222 | 254 | 111 | 254
224 | 163 | 112 | 163
226 | 119 | 113 | 119
228 | 80 | 114 | 80
230 | 254 | 115 | 254
232 | 156 | 116 | 156
234 | 118 | 117 | 118
236 | 72 | 118 | 72
238 | 255 | 119 | 255
  |   | 136 | 160
  |   | 137 | 114
  |   | 138 | 81
  |   | 139 | 254
  |   | 140 | 154
  |   | 141 | 113
  |   | 142 | 72
  |   | 143 | 254
  |   | 144 | 160
  |   | 145 | 115
  |   | 146 | 81
  |   | 147 | 254
  |   | 148 | 157
  |   | 149 | 108
  |   | 150 | 67
  |   | 151 | 254
  |   | 171 | 254
  |   | 172 | 158
  |   | 173 | 117
  |   | 174 | 76
  |   | 175 | 254
  |   | 176 | 152
  |   | 177 | 120
  |   | 178 | 85
  |   | 179 | 254
  |   | 180 | 152
  |   | 181 | 104
  |   | 182 | 63
  |   | 183 | 254
  |   | 200 | 1
  |   | 203 | 254
  |   | 204 | 157
  |   | 205 | 119
  |   | 206 | 75
  |   | 207 | 254
  |   | 208 | 161
  |   | 209 | 113
  |   | 210 | 75
  |   | 211 | 254
  |   | 212 | 154
  |   | 213 | 120
  |   | 214 | 80
  |   | 215 | 255
  |   | 235 | 254
  |   | 236 | 155
  |   | 237 | 117
  |   | 238 | 75
  |   | 239 | 255

**Comment by kheyer** [comment]
I found that removing the cast to Long and reshaping at the end of the pytorch model fixed the issue. ie changing 

```python
class InferenceModel(nn.Module):
    def __init__(self, layers):
        super().__init__()
        self.layers = layers
        
    def forward(self, input):
        input = input.unsqueeze(0)
        output = (self.layers(input).clamp(0,1) * 255).type(torch.LongTensor)
        output = output.view((8,8,4))
        return output
```

to

```python
class InferenceModel(nn.Module):
    def __init__(self, layers):
        super().__init__()
        self.layers = layers
        
    def forward(self, input):
        input = input.unsqueeze(0)
        output = self.layers(input).clamp(0,1) * 255
        return output
```

was able to fix the issue. Not sure if the problem was caused by the type change or the reshaping

**Comment by fs-eire** [comment]
This is a known issue (int32/int64 mismatch for output) which is fixed in master but not yet in latest release. link to the PR: https://github.com/microsoft/onnxruntime/pull/11049

**Comment by kheyer** [comment]
Loos like the core issue is known and I'm able to fix my code by removing the cast to long. Going to close the issue
