### ISSUE TITLE
Runtime error during infer a Constant Node with "value_floats" or "value_ints"

### ISSUE THREAD

**Issue by RunnerZhong** [microsoft/onnxruntime#11091]
**Describe the bug**
Runtime error during infer a Constant Node with "value_floats" or "value_ints"

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version: 1.10.2
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
[Constant_test.zip](https://github.com/microsoft/onnxruntime/files/8401749/Constant_test.zip)

**Expected behavior**
Can infer without error

**Screenshots**
![image](https://user-images.githubusercontent.com/30307463/161364784-e9bc8a54-3b75-49d6-9f03-f4492e245161.png)

**Additional context**
Traceback (most recent call last):
  File "C:/src_code/samples/new_convert.py", line 23, in <module>
    sess = ort.InferenceSession(r"C:\src_code\samples\Sample_Models\Constant_test.onnx")
  File "C:\miniconda\extra_envs\latest\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\miniconda\extra_envs\latest\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 381, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core/optimizer/initializer.h:96 onnxruntime::Initializer::Initializer size_ == size was false. size is different

**Comment by skottmckay** [comment]
Fix is checked in.
