### ISSUE TITLE
ONNX Runtime Mobile Training (Android/iOS)

### ISSUE THREAD

**Issue by danieljanes** [microsoft/onnxruntime#11098]
**Is your feature request related to a problem? Please describe.**

The ONNX Runtime supports inference on mobile devices, but there is no support for training on mobile devices.

**System information**
- ONNX Runtime version (you are using): latest

**Describe the solution you'd like**

Support training on mobile devices (Android, iOS) using the ONNX Runtime.

On-device training is rising in popularity, among the most prominent use cases are on-device fine tuning / personalization and federated learning. An ideal solution would leverage native accelerator APIs (NNAPI, CoreML), but a CPU-only version would already provide considerable value.

**Describe alternatives you've considered**

- Use a different framework / runtime: TFLite has recently added support for on-device training, TensorFlow.js could be a viable solution in some scenarios, Deeplearning4j seems to support training on Android
- Hand-code model training without using a framework

**Additional context**
I'm one of the creators of the Flower federated learning framework (https://flower.dev/). Flower could be described as an environment-agnostic middleware for federated learning. While support for federated learning across servers is great (one can use mature ML frameworks like TensorFlow or PyTorch), the same can not be said for mobile devices. Training support in the ONNX Runtime could provide a stable cross-platform target for on-device learning. We'd be excited to collaborate and pilot integration in Flower!

**Comment by askhade** [comment]
@danieljanes : Thanks for your interest. We are in a preliminary stage for on-device training on mobile. Would you be open to engaging deeper in a couple of months once we have more clarity on our plans? Additionally, do you have any specific timelines in your mind?

**Comment by danieljanes** [comment]
Thanks for the fast reply @askhade - absolutely, I'd be happy to engage whenever there's something to discuss, even if it's just for gathering requirements. No specific timeline in mind, we're currently involved in different projects using the alternative solutions mentioned above, but we haven't converged on a solution that provides the level of generality we'd like to see.

**Comment by baijumeswani** [comment]
ONNX Runtime now supports training on mobile devices. Please have a look at out [On-Device Training with ONNX Runtime getting started page](https://onnxruntime.ai/docs/get-started/training-on-device.html).

Closing this issue as feature complete. Please open more issues in case there are questions.
