### ISSUE TITLE
Link to onnxruntime test data is down

### ISSUE THREAD

**Issue by galv** [microsoft/onnxruntime#11104]
**Describe the bug**
I, and apparently no one else, can download the testing models here: https://github.com/microsoft/onnxruntime/blob/master/docs/Model_Test.md

**Urgency**
None

**System information**
Irrelevant

**To Reproduce**
Try to download: https://onnxruntimetestdata.blob.core.windows.net/models/20190419.zip

You'll see an error like "The specified blob does not exist."

**Expected behavior**
This is documented here as being the way to access models for testing: https://github.com/microsoft/onnxruntime/blob/master/docs/Model_Test.md

**Additional context**
Someone else has had this problem years ago apparently: https://github.com/microsoft/onnxruntime/issues/7447

It was closed with a maintainer saying "I can sent it to you offline. We can discuss it later today." However, sending data privately is not really a solution for everyone else who might want to run these tests.

**Comment by snnn** [comment]
The link is 404 because we no longer use it in our build pipelines. When I made zip file, it only contains public models from onnx model zoo and https://github.com/onnx/onnx.  Later on I was asked to add some private models to our CI build pipelines. So I can't share the new model set to you.
