### ISSUE TITLE
Conversion of  T5 decoder with past_key_values to float16.

### ISSUE THREAD

**Issue by VikasOjha666** [microsoft/onnxruntime#11119]
**Describe the bug**
@tianleiwu  @sam-writer @wangyems 
With the converted ONNX model generated using FastT5 project. I was trying to convert the decoder_init and decoder to float16. I did the quantization with onnxruntime's transformer optimizer. I was able to convert the decoder_init to fp16 but while converting the decoder with past_key_values I am getting following issue:

AssertionError                            Traceback (most recent call last)
[<ipython-input-10-42606fa3cf84>](https://localhost:8080/#) in <module>()
     25     ,
     26     )
---> 27 optimized_model.convert_float_to_float16()  # FP32 -> FP16
     28 optimized_model.save_model_to_file('/content/optimized_models/t5-base-qa-qg-hl-decoder.onnx')
     29 

6 frames
[/usr/local/lib/python3.7/dist-packages/onnxruntime/transformers/../tools/symbolic_shape_infer.py](https://localhost:8080/#) in _add_suggested_merge(self, symbols, apply)
    216 
    217     def _add_suggested_merge(self, symbols, apply=False):
--> 218         assert all([(type(s) == str and s in self.symbolic_dims_) or is_literal(s) for s in symbols])
    219         symbols = set(symbols)
    220         for k, v in self.suggested_merge_.items():

AssertionError:

**Urgency**
Its very urgent as soon we need to productionize the model.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- ONNX Runtime installed from (source or binary):PyPi
- ONNX Runtime version:1.11
- Python version:3.7.12
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: Nvidia Tesla T4 GPU

**To Reproduce**
Using FastT5 project on github convert the t5-base model to ONNX  or download the model from the below link:
https://drive.google.com/file/d/1EmBu1mZmUu7FpOi7jeE_uCkk9BDdMq8g/view?usp=sharing

And run the script below:

from onnxruntime.transformers import optimizer

optimized_model =optimizer.optimize_model(
        input='/content/models/t5-base-qa-qg-hl-decoder.onnx',
        use_gpu=True,
        opt_level=1, only_onnxruntime= True
    ,
    )
optimized_model.convert_float_to_float16()  # FP32 -> FP16
optimized_model.save_model_to_file('/content/optimized_models/t5-base-qa-qg-hl-decoder.onnx')

What do I need to change in order to convert the T5 decoder with past_key_values to float16. I suspect the inclusion of past_key_values has to do something with it as decoder init which doesn't takes past_key_values as input was converted sucessfully.

**Comment by wangyems** [comment]
Can you try without the symbolic shape infer:
optimized_model.convert_float_to_float16(use_symbolic_shape_infer=False)

**Comment by VikasOjha666** [comment]
@wangyems  Thanks for your time and the answer. Setting the above option solved the issue. Thanks for the quick response again.

**Comment by VikasOjha666** [comment]
@wangyems Sorry to revive this issue again. But when I am doing prediction using the above decoder I am getting this issue:

RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Cast node. Name:'graph_input_cast5' Status Message: /onnxruntime_src/onnxruntime/core/framework/op_kernel.cc:78 OrtValue* onnxruntime::OpKernelContext::OutputMLValue(int, const onnxruntime::TensorShape&) status.IsOK() was false. Shape mismatch attempting to re-use buffer. {4,12,1,64} != {4,12,163,64}. Validate usage of dim_value (values should be > 0) and dim_param (all values with the same string should equate to the same size) in shapes in the model.

**Comment by VikasOjha666** [comment]
@wangyems The same issue was coming in the fp16 version of decoder_init which is the version of decoder with inputs: input_ids,attention_mask and encoder_ouputs. But setting use_symbolic_shape_infer=False did solved this issue in decoder init. But I am already doing the same for decoder and I am getting this issue. Could you please suggest any fix?

**Comment by VikasOjha666** [comment]
@tianleiwu No fp32 model doesn't produce this issue.

**Comment by VikasOjha666** [comment]
@tianleiwu  Does the conversion script above can convert model with past_key_values to fp16 as I need model which uses past_key_values as this model is faster for longer sequences as well.

**Comment by VikasOjha666** [comment]
@tianleiwu No fp32 model doesn't have this issue.

**Comment by VikasOjha666** [comment]
I converted the model using this script:optimized_model.convert_float_to_float16(use_symbolic_shape_infer=False, keep_io_types=False, op_block_list=["Pow", "ReduceMean", "Add", "Sqrt", "Div", "Mul", "Softmax", "Relu"]) but now I am getting different error. While loading the inference session from the converted model file, I am getting the below error:

Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /content/optimized_models/t5-base-qa-qg-hl-decoder.onnx failed:Type Error: Type parameter (T) of Optype (Add) bound to different types (tensor(float16) and tensor(float) in node (Add_73).

**Comment by VikasOjha666** [comment]
@tianleiwu Using optimized_model.convert_float_to_float16(use_symbolic_shape_infer=False, keep_io_types=False) the model has been converted sucessfully to fp16 and is producing no issues. But might effect accuracy a bit like you mentioned. Hence please let me know if there is a way to perform conversion in the way you suggested.

**Comment by VikasOjha666** [comment]
@tianleiwu Could you please tell me how can I solve the above issue while converting the model with the above op_block_list?

**Comment by VikasOjha666** [comment]
@tianleiwu @wangyems It loads with performing conversions using below script:
optimized_model.convert_float_to_float16(use_symbolic_shape_infer=False, keep_io_types=False,op_block_list='Relu') 

From this I suspect it has something to do with Add initializers ?

**Comment by tianleiwu** [comment]
@VikasOjha666, 

Add, Mu and Div might not impact the accuracy, they are optional to compute in float16. They might have slight performance boost since adding them could avoid some data Cast.

When you compare fp32 graph to mixed graph, you can see that major difference is some Cast nodes (either from fp32 to fp16, or fp16 to fp32 data conversion) are added to the graph, and some weights are converted to fp16. The error means that one input of Add_73 is fp16 and another input is fp32, so the solution is to make both inputs to be same data type (by adding or removing a Cast node).

You can use Netron to open the graph to see which Cast node is missing or not needed to be added. Then change the conversion script (https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/float16.py) to resolve the issue. For example, add a post process to insert a Cast node, or remove a Cast node.

**Comment by VikasOjha666** [comment]
@tianleiwu Thanks for taking out time for answer the question.I will try this.

**Comment by tianleiwu** [comment]
@VikasOjha666, I just drafted mixed precision conversion for T5 decoder, it seems working fine without problem.

It is still in a branch, and you can try it like the following:
```
git clone https://github.com/microsoft/onnxruntime
git checkout tlwu/t5_auto_mixed_precision
cd onnxruntime/onnxruntime/python/tools/transformers/models/t5
python convert_to_onnx.py -m t5-base -o --use_gpu -p fp16
```
The mixed precision model is output as ./onnx_model/t5-base_decoder_fp16.onnx

**Comment by VikasOjha666** [comment]
@tianleiwu . Is it fast for longer sequences too?.And is it's accuracy good?. I mean no disrespect but I am just clearing my doubts as I am sticking on the same problem since past month. As the model I optimized last time was faster for large sequences but was same as torch model for longer sequences even with IO bindings. Then I followed the same with decoder utilizing past_key_values taking idea from a previous thread of yours. This model was fast even for larger sequences but had accuracy issues as I converted all the nodes in the decoder to float16.

**Comment by tianleiwu** [comment]
@VikasOjha666, 
Based on my previous experience on GPT-2, converting decoder to pure float16 will lead to accuracy issue, and mixed precision is the recommended solution to trade off performance and accuracy.

Of course, it need some experiment to see the performance/accuracy impact when converting some operators to FP16/FP32. For example, we have a tool for GPT-2: https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/gpt2_parity.py
We have not started similar tuning work on T5.

Tip: using float16 for past state (make sure past_key_values  inputs and present outputs are in float16) bring most performance gain, and you can put more operators to compute in float32 if you need higher accuracy.

**Comment by VikasOjha666** [comment]
Thanks for the tip @tianleiwu will try it and let you know the results.

**Comment by 1615070057** [comment]
> @tianleiwu @wangyems 我使用以下脚本转换了模型：optimized_model.convert_float_to_float16(use_symbolic_shape_infer=False, keep_io_types=False, op_block_list=["Pow", "ReduceMean", "Add", "Sqrt", "Div", "Mul", "Softmax" ，“Relu”]）但现在我遇到了不同的错误。从转换后的模型文件加载推理会话时，我收到以下错误：
> 
> 失败：[ONNXRuntimeError]：1：失败：从/content/optimized_models/t5-base-qa-qg-hl-decoder.onnx加载模型失败：类型错误：Optype（Add）的类型参数（T）绑定到不同类型（节点（Add_73）中的张量（float16）和张量（float）。

I also encountered a similar problem, can you help me solve it?
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from model_fp16.onnx failed:This is an invalid model. Type Error: Type 'tensor(float16)' of input parameter (const_empty_float__132) of operator (Resize) in node (Resize__139) is invalid.

**Comment by tianleiwu** [comment]
You can try `python -m onnxruntime.transformers.models.t5.convert_to_onnx -m t5-base -o --use_gpu -p fp16`, or run it in source code like the following:

```
/git/onnxruntime/onnxruntime/python/tools/transformers$ python -m models.t5.convert_to_onnx -m t5-base -o --use_gpu -p fp16
Arguments:Namespace(model_name_or_path='t5-base', model_type='t5', cache_dir='./cache_models', output='./onnx_models', optimize_onnx=True, use_gpu=True, precision=<Precision.FLOAT16: 'fp16'>, verbose=False, use_external_data_format=False, use_decoder_start_token=False, overwrite=False, disable_auto_mixed_precision=False, separate_encoder_and_decoder_init=False, use_int64_inputs=False, state_dict_path='')
PyTorch Version:2.0.1+cu117
Transformers Version:4.31.0
OnnxRuntime Version:1.15.1
Graph optimization for T5 is not implemented yet.
Downloading (…)lve/main/config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.21k/1.21k [00:00<00:00, 8.00MB/s]
Downloading model.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 892M/892M [01:17<00:00, 11.6MB/s]
Downloading (…)neration_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 147/147 [00:00<00:00, 1.30MB/s]
Exporting ONNX model to ./onnx_models/t5-base_encoder_decoder_init.onnx
/nvme/tlwu/anaconda3/envs/llama/lib/python3.10/site-packages/transformers/modeling_utils.py:847: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if causal_mask.shape[1] < attention_mask.shape[1]:
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Optimizing model to ./onnx_models/t5-base_encoder_decoder_init_fp16.onnx
Fused RelativePositionBias: 2
Fused MultiHeadAttention: 24
Removed 331 nodes
Fused Reshape: 1
Removed 1 nodes
Remove reshape node /t5_decoder_init/decoder/Reshape since its input shape is same as output: ['batch_size', '1']
Remove reshape node /t5_encoder/encoder/Reshape since its input shape is same as output: ['batch_size', 'encode_sequence_length']
Removed 9 nodes
opset version: 12
fp32 op: {'Relu', 'SkipSimplifiedLayerNormalization', 'Add', 'SimplifiedLayerNormalization'} fp16 op: {'Shape', 'MultiHeadAttention', 'Attention', 'MatMul', 'Mul', 'Gather', 'RelativePositionBias'}
Found last MatMul node for logits: /t5_decoder_init/lm_head/MatMul
auto_mixed_precision parameters: {'keep_io_types': [], 'op_block_list': ['SimplifiedLayerNormalization', 'SkipSimplifiedLayerNormalization', 'Relu', 'Add'], 'node_block_list': [], 'force_fp16_initializers': True}
Removed 118 cascaded Cast nodes
Removed 60 nodes
Removed 118 Cast nodes with output type same as input
Sort graphs in topological order
Model saved to ./onnx_models/t5-base_encoder_decoder_init_fp16.onnx
batch_size=4 encode_sequence_length=11, max_diff=0.04118633270263672
batch_size=1 encode_sequence_length=2, max_diff=0.037670135498046875
batch_size=3 encode_sequence_length=1, max_diff=0.041233062744140625
batch_size=8 encode_sequence_length=5, max_diff=0.04552507400512695
PyTorch and OnnxRuntime results max difference = 0.04552507400512695
PyTorch and OnnxRuntime results are NOT close
Exporting ONNX model to ./onnx_models/t5-base_decoder.onnx
/nvme/tlwu/anaconda3/envs/llama/lib/python3.10/site-packages/torch/onnx/utils.py:2029: UserWarning: Provided key encoder_hidden_states for dynamic axes is not a valid input/output name
  warnings.warn(
/nvme/tlwu/anaconda3/envs/llama/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py:508: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  elif past_key_value.shape[2] != key_value_states.shape[1]:
In-place op on output of tensor.shape. See https://pytorch.org/docs/master/onnx.html#avoid-inplace-operations-when-using-tensor-shape-in-tracing-mode
In-place op on output of tensor.shape. See https://pytorch.org/docs/master/onnx.html#avoid-inplace-operations-when-using-tensor-shape-in-tracing-mode
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Optimizing model to ./onnx_models/t5-base_decoder_fp16.onnx
Fused RelativePositionBias: 1
Fused MultiHeadAttention: 24
Removed 202 nodes
Remove reshape node /decoder/Reshape since its input shape is same as output: ['batch_size', 1]
Removed 20 nodes
opset version: 12
fp32 op: {'Relu', 'SkipSimplifiedLayerNormalization', 'Add', 'SimplifiedLayerNormalization'} fp16 op: {'Shape', 'Neg', 'Unsqueeze', 'MultiHeadAttention', 'Gather', 'Slice', 'Mul', 'MatMul', 'RelativePositionBias'}
Found last MatMul node for logits: /lm_head/MatMul
auto_mixed_precision parameters: {'keep_io_types': [], 'op_block_list': ['SimplifiedLayerNormalization', 'SkipSimplifiedLayerNormalization', 'Relu', 'Add'], 'node_block_list': [], 'force_fp16_initializers': True}
Removed 71 cascaded Cast nodes
Removed 36 nodes
Removed 71 Cast nodes with output type same as input
Sort graphs in topological order
Model saved to ./onnx_models/t5-base_decoder_fp16.onnx
batch_size=4, encode_sequence_length=11, past_decode_sequence_length=3, max_diff=0.030418396
batch_size=1, encode_sequence_length=2, past_decode_sequence_length=5, max_diff=0.036548615
batch_size=3, encode_sequence_length=1, past_decode_sequence_length=1, max_diff=0.027641296
batch_size=8, encode_sequence_length=5, past_decode_sequence_length=2, max_diff=0.034591675
PyTorch and OnnxRuntime results max difference = 0.0345916748046875
PyTorch and OnnxRuntime results are NOT close
Done! Outputs: ['./onnx_models/t5-base_encoder_decoder_init_fp16.onnx', './onnx_models/t5-base_decoder_fp16.onnx']
```
