### ISSUE TITLE
Memory leak during inference

### ISSUE THREAD

**Issue by shameem198** [microsoft/onnxruntime#11118]
Hi,

I have converted cascade mask rcnn detection model from PyTorch to ONNX using ONNXRuntime as backend. During the load test, I noticed that RAM consumption is increasing with respect to number of inferences.

**platform = Linux-x86_64
python = 3.7
pytorch = 1.8.0
torchvision = 0.9.0
onnx = 1.8.1
onnxruntime = 1.8.1
device = cpu**

![161519183-47d5b49f-bab7-4d12-89e6-ab4adddfd70b](https://user-images.githubusercontent.com/45461737/161737834-28fb49a1-3564-44b5-9e3e-b7490d81dca5.jpg)

I have already tried with latest versions of above packages, garbage collection and deleted unnecessary variables after inference. It didn't help to reduce memory leak. 

Also, I found that the memory usage would increase when a tensor with new shapes feed to ONNXRuntime session.
I guess, ONNXRuntime would record some information about that input tensor shape so it can be accelerated when the session gets a new tensor with the same shape. Is it the reason for the increment of memory when we do continuous inference with different samples? How can I fix this issue? 

_[](https://github.com/microsoft/onnxruntime/blob/8db180c245512f5bb5bdefc0f8b643ad6ff51294/onnxruntime/core/framework/execution_frame.cc#L524 .)_

**Comment by pranavsharma** [comment]
Can you attach the model and the repro code? Also, try disabling memory pattern; that should definitely help.

**Comment by skottmckay** [comment]
The setting is called enable_mem_pattern in SessionOptions. Set that to false. 

e.g. for python https://onnxruntime.ai/docs/api/python/api_summary.html#onnxruntime.SessionOptions.enable_mem_pattern

**Comment by skottmckay** [comment]
Yes. If the memory pattern is enabled we use offsets into one big block of memory for the tensors required during execution. If it's disabled we have to do allocations instead. Those allocations are via an arena, but it's still more expensive than using an offset into pre-allocated memory.

**Comment by kopyl** [comment]
@skottmckay why did you close it? It still not fixed. 

Nothing helps. Here is ho my code looks:

```
options = onnxruntime.SessionOptions()
        options.enable_mem_pattern = False
        options.enable_cpu_mem_arena = False
        options.enable_mem_reuse = False
        self.session = onnxruntime.InferenceSession(path,
                                                    sess_options=options,
                                                    providers=['CUDAExecutionProvider',
                                                               'CPUExecutionProvider'])
```

**Comment by skottmckay** [comment]
@kopyl not quite following given this was the reply from the OP. 

> thanks, I also disabled cpu_mem_arena, it helped to keep memory and cpu consumption stable.

If you think there's a new problem please create a new issue with the model and repro including details of how the model is being run and how the inputs/outputs are managed.
