### ISSUE TITLE
[Documentation Request] Undocumented removed args in mobile performance tuning page

### ISSUE THREAD

**Issue by gqgs** [microsoft/onnxruntime#11124]
Arguments `--optimization_level` and `--use_nnapi`  being used in this page to call the `convert_onnx_models_to_ort.py` script were apparently removed in 1.11.0 with e53422c6d0ff6f44cb96a3a706eebcd5d8850d11.

The page should probably make it clear that those parameters will no longer work if that's the case and maybe document `--optimization_style` if that's the alternative.

---
#### Document Details
* Title: Tune Mobile Performance
* Page: [https://onnxruntime.ai/docs/performance/mobile-performance-tuning.html](https://onnxruntime.ai/docs/performance/mobile-performance-tuning.html)
* Page Source: mobile-performance-tuning.md

**Comment by skottmckay** [comment]
That performance tuning page is outdated by the new runtime optimization abilities in ORT 1.11. 

@edgchen1 were you in the process of removing that page or did you want me to?

**Comment by edgchen1** [comment]
It's still applicable for 1.10 and earlier. We need updated instructions for 1.11. I can update that page too.

**Comment by edgchen1** [comment]
Updated the docs. That page has a note saying it is only for 1.10 and earlier now.
