### ISSUE TITLE
create inference session failed for onnxrt1.9.0

### ISSUE THREAD

**Issue by mengniwang95** [microsoft/onnxruntime#11140]
**Describe the bug**
I use onnxrt1.9.0 to generate a qdq model and inference session can not be created with onnxrt1.9.0 but can create with onnxrt1.10.0.
This is the error info:
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : This is an invalid model. Error: two nodes with same node name (Postprocessor/stack_1_Concat__431).
But I can not find the second 'Postprocessor/stack_1_Concat__431' node in this model.

**To Reproduce**

[qdq.zip](https://github.com/microsoft/onnxruntime/files/8441318/qdq.zip)

```python
import onnxruntime as ort
ort.InferenceSession('qdq.onnx')
```

**Comment by skottmckay** [comment]
Possibly there was a bug in 1.9. As the newer releases work it appears that is fixed. 

Is there any issue running the model with ORT 1.10 or 1.11?

**Comment by mengniwang95** [comment]
It can run successfully with ORT1.10

**Comment by skottmckay** [comment]
Closing as bug is fixed in latest ORT versions.
