### ISSUE TITLE
Documentation for c++ libs linux installs

### ISSUE THREAD

**Issue by ahmednofal** [microsoft/onnxruntime#11142]
Thank you for the work on this project.

There does not seem to be anything in the documentation that references a standard way of installing the onnxruntime shared libs in linux. The only way to use it on linux for C++ is to build it from source or download the zipped release and manually installing the files in the lib directory of your chosen OS (Not a good idea). Is there a standard way I am not seeing of how to install the onnxruntime for C++ on linux ? If there is none is there future plans to provide linux OS-specific packages ? or even OS-agnostic ?

Thanks.

**Comment by snnn** [comment]
Sorry currently we don't have a plan to provide deb or rpm packages. I'm not familiar with these stuff. Currently the only way to install onnxruntime is as you said, to manually copy the shared lib and head files to your system.
