### ISSUE TITLE
C# - InferenceSession fails with "invalid weights type of Int8" even though Int8 enabled in TensorRT

### ISSUE THREAD

**Issue by dannetsecure** [microsoft/onnxruntime#11141]
Am encountering an issue with C# onnxruntime and TensorRT.  I have a quantized onnx model that builds fine when using the trtexec command line:

> [04/06/2022-19:41:36] [I]
> &&&& PASSED TensorRT.trtexec [TensorRT v8203] # trtexec --explicitBatch --onnx=model.onnx --workspace=10000 --verbose --dumpProfile --int8

However, when I try and create an InferenceSession in C#, I get the following error

Code:
>            // Step 1 - Input path to model and create an inferencing session.                        
>            OrtTensorRTProviderOptions trt_options = new OrtTensorRTProviderOptions();            
>            trt_options.UpdateOptions(new Dictionary<string, string>() 
>           {
>               // Enable INT8 for QAT models, disable otherwise.
>               { "trt_int8_enable", "1" },
>               { "trt_engine_cache_enable", "1" },
>              { "trt_engine_cache_path", engineCachePath }
>          });            
>          SessionOptions so = new SessionOptions();            
>          so.AppendExecutionProvider_Tensorrt(trt_options);
>          so.AppendExecutionProvider_CUDA(0); 
>          var session = new InferenceSession(modelPath, so);

This fails with the following output:

> 2022-04-07 09:42:09.2747384 [W:onnxruntime:CSharpOnnxRuntime, tensorrt_execution_provider.h:53
>  onnxruntime::TensorrtLogger::log] [2022-04-07 15:42:09 WARNING] D:\a\_work\1\s\cmake\external\onnx-
> tensorrt\onnx2trt_utils.cpp:364: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively 
> support INT64. Attempting to cast down to INT32.
> 
> 2022-04-07 09:42:09.2752636 [E:onnxruntime:CSharpOnnxRuntime, tensorrt_execution_provider.h:51 
> onnxruntime::TensorrtLogger::log] [2022-04-07 15:42:09   ERROR] 140: invalid weights type of Int8
> Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other 
> memory is corrupt.
> at Microsoft.ML.OnnxRuntime.InferenceSession.Init(System.String, Microsoft.ML.OnnxRuntime.SessionOptions, 
> Microsoft.ML.OnnxRuntime.PrePackedWeightsContainer)
>  at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(System.String, Microsoft.ML.OnnxRuntime.SessionOptions)
>    at CSConsoleApp1.TensorRT_Test.Run()
>    at Program.<Main>$(System.String[])

I've enabled int8 as per the docs.  Is this an issue with onnxruntime or am I missing something important?

**Comment by dannetsecure** [comment]
As a side question - is it possible to work around this issue by deserializing the .engine file output by trtexec and using that instead?  I don't see a way to do that in the docs.

**Comment by skottmckay** [comment]
@stevelix any ideas?

**Comment by stevenlix** [comment]
Please add this line to disable ORT optimization for TRT INT8,
so.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_DISABLE_ALL

**Comment by stevenlix** [comment]
I see you've enabled trt_engine_cache_enable, then the TRT engines should have been serialized into *.engine files. Next time when you run the same inference, engines will be loaded from the files.

**Comment by dannetsecure** [comment]
Thanks Steven.

**Comment by fxmarty** [comment]
> Please add this line to disable ORT optimization for TRT INT8, so.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_DISABLE_ALL

Hello, will this decrease runtime performances?
