### ISSUE TITLE
bug need to solve

### ISSUE THREAD

**Issue by DXZDXZ** [microsoft/onnxruntime#11166]
**Describe the bug**
I can not fint the tvm test floder in path: onnxruntime/test/tvm.

```
if (onnxruntime_USE_TVM)
  file (GLOB_RECURSE onnxruntime_test_tvm_src CONFIGURE_DEPENDS
    "${TEST_SRC_DIR}/tvm/*.h"
    "${TEST_SRC_DIR}/tvm/*.cc"
  )

  list(APPEND onnxruntime_test_providers_dependencies onnxruntime_providers_tvm)
endif()

```

**Comment by DXZDXZ** [comment]
I am hoping for your reply!

Thans!

**Comment by skottmckay** [comment]
Doesn't look like any test files were ever checked in. #10260 added those lines but no files. 

@xadupre should there be test files, or should the cmake file be cleaned up?

**Comment by xadupre** [comment]
There are unit test files but they were renamed and this file was not updated. I missed that when I reviewed the PR. I'll create another PR to fit it.
