### ISSUE TITLE
OnnxRuntime library in 3rd-party x64 .NET Framework 4.5 application

### ISSUE THREAD

**Issue by whitmark** [microsoft/onnxruntime#1118]
I am looking to reference the OnnxRuntime library in my 3rd-party x64 .NET Framework 4.5 application (as I did easily with the [CNTK library](https://docs.microsoft.com/en-us/cognitive-toolkit/cntk-library-evaluation-on-windows))  Is this feasible given the dependencies, and if so which DLLs would I need to include?

**Comment by faxu** [comment]
There are official Nuget packages published with C# APIs. Details 
 here - https://github.com/microsoft/onnxruntime#apis-and-official-builds

Does that work for you?

**Comment by jignparm** [comment]
The NuGet packages are tested on .NET Framework 4.6.1, and .Net Core 2.0. 

The latest version NuGet version (0.4.0) contains both the x64 as well as x86 native runtimes.

For native C++ projects, you only need the x64 **onnxruntime.dll** library.

For C# projects, you'll need both the managed AnyCPU **Microsoft.ML.OnnxRuntime.dll**, as well as the appropriate native **onnxruntime.dll** libraries.

Your project should pick these up automatically when you install the package.

Also see  [C# API ](https://github.com/microsoft/onnxruntime/blob/master/docs/CSharp_API.md) and [C++ API](https://github.com/microsoft/onnxruntime/blob/master/docs/C_API.md) for examples.

**Comment by whitmark** [comment]
@faxu, @jignparm Thank you.  Since OnnxRuntime adheres to the NETStandard 1.1, I am hopeful this will work for CPU inferencing on my 3rd-party x64 .NETFramework 4.5 app that compiles its own C# script and can reference external DLLs, but they must be specified individually.  The script I am using is similar to the one provided in the OnnxRuntime C# API docs, but I cannot get the DLLs to load cleanly.

As I examine the NuGet package library folders, it is unclear which of the numerous DLLs available are required or which version to use that is compatible with .NETFramework 4.5.  Perhaps there is a better way to identify these or reference them all.  

Upon reviewing the installation guide and DLL dependencies I see the following:
- NETStandard.Library (>= 1.6.1)
- System.Numerics.Tensors (>= 0.1.0)
- Microsoft.NETCore.Platforms (>= 1.1.0)
- System.Runtime.InteropServices.RuntimeInformation (>= 4.3.0)
- System.Memory (>= 4.5.0)
- System.Buffers (>= 4.4.0)
- System.Runtime.CompilerServices.Unsafe (>= 4.5.2)

and the native runtimes
- onnxruntime.dll
- libiomd.dll
- mklml.dll

It is unclear if this is a complete list of required DLLs and when attempting to load this list, the compiler calls for System.Runtime 0.4.0 which, when added, results in duplicate data types with mscorelib.dll.

As point of reference, I was able to get the Microsoft CNTK library to work well referencing the correct DLLs based on specific  documentation at this [link](https://docs.microsoft.com/en-us/cognitive-toolkit/CNTK-Library-Evaluation-on-Windows#shipping-cntk-library-with-your-windows-application) and am hoping to do the same with OnnxRuntime to tap into other ML./DL frameworks. 

Thanks in advance for any additional insight you can provide.

**Comment by jignparm** [comment]
@whitmark, using the  [Microsoft.ML.OnnxRuntime](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/0.4.0) as an example, if you are compiling a C# project and plan to run on a Windows operating system, you'll require these DLLs from the package.

───microsoft.ml.onnxruntime.0.4.0
    │
    ├───lib
    │   └───netstandard1.1
    │           Microsoft.ML.OnnxRuntime.dll
    ├───runtimes
    │   │
    │   ├───win-x64
    │   │   └───native
    │   │           onnxruntime.dll

The Microsoft.ML.OnnxRuntime.dll is the .NetStandard 1.1 **managed** C#  DLL, which is portable to multiple operating systems (Linux, Mac, Windows etc.). However, it depends on  the appropriate native DLLs (e.g. **onnxruntime.dll** for windows) to run successfully on the target OS.

The  Microsoft.ML.OnnxRuntime.dll has additional dependencies as well (e.g. System.Numerics.Tensor, which then depends on System.Memory and System.Buffers from your list above).

The "dotnet restore" (or NuGet restore) command will  download/install all the dependent packages for your project. Since you are compiling for the .Net 4.5 framework, you should see a "packages" folder containing all the C# packages. Additionally, every required DLL will also be copied to the output folder of the project (if you want a comprehensive list).

Is the packaging failing when you use it in a project? Or rather, you are looking to deconstruct the package and copy out a minimal set of DLLs to get a project to compile, without depending on the NuGet package?

**Comment by whitmark** [comment]
@jignparm, thanks for the follow-up on this atypical use-case.  Yes, precisely . . . since I am not using it as one typically would in a VS project, I am "**looking to deconstruct the package and copy out a minimal set of DLLs to get a project to compile [and run without errors], without depending on the NuGet package**"

To see what packages are included in the OnnxRuntime (and MKLML) I started a .NETFramework 4.5 project and inspected the "packages" folder.

![image](https://user-images.githubusercontent.com/8396992/58834152-a19ce400-8620-11e9-872c-030446915326.png)

From here it is unclear which DLL to use.  For example, if I look in the System.Runtime.4.3.0 folder, there is no DLL in the "net45" or "portable-net45-win8+wp80+wpa81" subfolders that I would expect to use.

![image](https://user-images.githubusercontent.com/8396992/58834349-2b4cb180-8621-11e9-8448-d09b42be7463.png)

My sense is not all of these packages / DLLs are needed so it would be quite useful to have a culled down list of required DLLs.

**Comment by jignparm** [comment]
Every package (e.g. the **System.Runtime.4.3.0** package you mentioned above) can have specialized DLLs and properties files, for different versions of Windows (e.g. 7, 8, 10), locales (e.g. de, es), framework versions etc.

Inspecting the individual package sub-folders would  error prone.  You should be able to view the correct list of DLLs in the output folder of a sample project. For example, see the version of **System.Runtime.dll** that is selected by Visual Studio and copied to the output folder below. If you want to find out where it came from, you can match it back to DLL in one of the packages sub folders (check for file size, checksum etc.).

Directory of D:\ConsoleApp1\ConsoleApp1\bin\x64\Release

03/28/2019  01:46 AM    <DIR>          .
03/28/2019  01:46 AM    <DIR>          ..
04/29/2019  11:31 AM            40,528 Microsoft.ML.OnnxRuntime.dll
04/29/2019  11:18 AM            14,436 Microsoft.ML.OnnxRuntime.pdb
02/22/2019  03:43 AM            21,216 Microsoft.Win32.Primitives.dll
02/22/2019  03:43 AM            98,616 netstandard.dll
04/29/2019  11:32 AM         4,206,456 onnxruntime.dll
02/22/2019  03:43 AM            21,176 System.AppContext.dll
07/19/2017  10:01 AM            27,992 System.Buffers.dll
...
...
05/15/2018  01:29 PM            14,080 System.Runtime.CompilerServices.Unsafe.xml
02/22/2019  03:43 AM            21,784 System.Runtime.CompilerServices.VisualC.dll
02/22/2019  03:43 AM            29,360 **System.Runtime.dll**
02/22/2019  03:43 AM            21,720 System.Runtime.Extensions.dll
02/22/2019  03:43 AM            21,200 System.Runtime.Handles.dll
02/22/2019  03:43 AM            24,296 System.Runtime.InteropServices.dll
02/22/2019  03:43 AM            28,624 System.Runtime.InteropServices.RuntimeInformation.dll
02/22/2019  03:43 AM            21,200 System.Runtime.Numerics.dll

**Comment by whitmark** [comment]
@jignparm thanks for the additional info.  I did build a release solution in VS 2019 using the sample csharp inferencing code found [HERE](https://github.com/microsoft/onnxruntime/blob/master/csharp/sample/Microsoft.ML.OnnxRuntime.InferenceSample/Program.cs) targeting .NETFramework 4.5 so my list of DLLs is different.

This generated the following files in \bin\release output:
System.Memory.dll
System.Memory.xml
System.Numerics.Tensors.dll
System.Numerics.Tensors.xml
System.Runtime.CompilerServices.Unsafe.dll
System.Runtime.CompilerServices.Unsafe.xml
System.Runtime.InteropServices.RuntimeInformation.dll
Microsoft.ML.OnnxRuntime.dll
Microsoft.ML.OnnxRuntime.pdb
System.Buffers.dll
System.Buffers.xml

However, when referencing the above DLLs from the 3rd Party app and compiling my C# script, I get several errors such as the following suggesting I am missing or have the wrong version of "System.Runtime, Version=4.0.0.0"

> The type   'System.IDisposable' is defined in an assembly that is not referenced. You   must add a reference to assembly 'System.Runtime, Version=4.0.0.0,   Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

Looking at the lib/ref folders, there are several System.RunTime.dll assemblies listed to choose from (that I have annotated with version number from File Explorer Properties):

---- System.Runtime.4.3.0
|   
+---lib
|   +---net45
|   |       _._
|   +---net462 
|   |       System.Runtime.dll  (ver. 4.6.24705.01)
|   +---portable-net45+win8+wp80+wpa81
|   |       _._
\---ref
    +---net45
    |       _._
    +---net462
    |       System.Runtime.dll  (ver. 4.6.24705.01)
    +---netstandard1.0
    |   |   System.Runtime.dll  (ver. 4.0.30319.17929)
    +---netstandard1.2
    |   |   System.Runtime.dll  (ver. 4.0.40013.0)
    +---netstandard1.3
    |   |   System.Runtime.dll  (ver. 4.6.23123.00)
    +---netstandard1.5
    |   |   System.Runtime.dll  (ver. 1.0.24212.1)?
    +---portable-net45+win8+wp80+wpa81
    |       _._

The System.Runtime.dll wasn't listed in the bin/release output, although it was the only one listed in the , packages\System.Runtime.4.3.0\lib folder so I referenced it and was able to get a clean compile in my 3rd Party app.  I am testing for runtime errors at the moment but am definitely farther along than I was before now that I can debug my C# script in VS 2019 .  Thanks you, I will report back.

**Comment by jignparm** [comment]
You may need to use **BindingRedirect** and/or **CodeBase** to load up the force loading of specific versions of the strong-named assemblies. 

See this [blog post](https://michaelscodingspot.com/how-to-resolve-net-reference-and-nuget-package-version-conflicts/) on how to do this.

**Comment by jignparm** [comment]
Closing this issue for now. Please re-open if needed.
