### ISSUE TITLE
Evaluating oonxruntime .ORT format by Python

### ISSUE THREAD

**Issue by binhpht** [microsoft/onnxruntime#11189]
I managed to convert a model from .onnx format to .ort to run on the device. Is there any way to measure performance of .ort model on the desktop by Python. 
Thanks

**Comment by edgchen1** [comment]
Running an ORT format model is also supported by InferenceSession.
https://onnxruntime.ai/docs/api/python/api_summary.html#inferencesession
You can measure calls to InferenceSession.run().

**Comment by binhpht** [comment]
Great, thanks
