### ISSUE TITLE
Load the ONNX model  error

### ISSUE THREAD

**Issue by Smile-L-up** [microsoft/onnxruntime#11202]
Thank you for your work. I'd like to ask you a question . I tried to convert the pb file of the distillation model Albert Tiny CRF into ONNX format and load the model using the ONNX engine. However, the following error occurred during loading.

**onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from D:\Smile_L\new_too1\albert_crf_inference\ner\engines\model.onnx failed:Node (StatefulPartitionedCall/cond_1) Op (If) [TypeInferenceError] Graph attribute inferencing failed: Node (__inference_cond_1_false_3605_frozen_11806_cond_1/scan/while_loop) Op (Loop) [TypeInferenceError] Graph attribute inferencing failed: Node (cond_1/scan/while/add) Op (Add) [ShapeInferenceError] Incompatible dimensions**

**Information about model transformation**
2022-04-13 14:05:14,721 - INFO - Successfully converted TensorFlow model ./albert_crf_pb to ONNX
2022-04-13 14:05:14,722 - INFO - Model inputs: ['X_train_batch', 'att_mask_batch', 'inputs_length', 'targets']
2022-04-13 14:05:14,722 - INFO - Model outputs: ['output_0', 'output_1', 'output_2']
2022-04-13 14:05:14,726 - INFO - ONNX model is saved at model.onnx

**Here is the model I constructed：**
```Python
class ATNerModel(tf.keras.Model):
    def __init__(self,configs,num_classes):
        super(ATNerModel, self).__init__()
        self.bert_model = TFDistilBertModel.from_pretrained(os.path.join(os.path.dirname(os.path.dirname(__file__)), 'albert_tiny_chinese'), from_pt=True)
        self.dropout = tf.keras.layers.Dropout(configs.dropout)
        self.dense1 = tf.keras.layers.Dense(156)  # numclass = 8
        self.dense2 = tf.keras.layers.Dense(num_classes)
        #self.ce = tf.nn.sparse_softmax_cross_entropy_with_logits()
        self.transition_params = tf.Variable(tf.random.uniform(shape=(num_classes, num_classes)))
    @tf.function
    def call(self, X_train_batch,att_mask_batch, inputs_length, targets,training=None):
        bert_outputs = self.bert_model(X_train_batch, attention_mask=att_mask_batch)[0]
        outputs = self.dropout(bert_outputs,training)
        logits1 = self.dense1(outputs)
        logits = self.dense2(logits1)
        tensor_targets = tf.convert_to_tensor(targets)
        # #self.ce(targets,logits)
        log_likelihood, self.transition_params = crf_log_likelihood(
            logits, tensor_targets, inputs_length, transition_params=self.transition_params)
        return logits, log_likelihood, self.transition_params
```

**Comment by garymm** [comment]
@Smile-L-up please inspect the model and see if it looks correct to you. If it does, then this is an issue in onnxruntime. Otherwise please close this and open an issue in github.com/onnx/tensorflow-onnx
