### ISSUE TITLE
linker error douring build for Xamarin.ios on Apple M1 based host

### ISSUE THREAD

**Issue by enny1170** [microsoft/onnxruntime#11204]
During Build for my Xamarin.Ios App using ORT 1.11.0 i got some Errors and the Build will be interrupted.
  /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/enricoziehe/Library/Caches/Xamarin/mtbs/builds/BeetControl.iOS/481a9da9dded3425f26c86f26810958b457ceb30151c1ab9afcbee08f779190c/obj/iPhone/Debug/response-file.rsp --gcc_flags=-lc++ 
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): warning : '/Users/enricoziehe/Library/Caches/Xamarin/mtbs/builds/BeetControl.iOS/481a9da9dded3425f26c86f26810958b457ceb30151c1ab9afcbee08f779190c/obj/iPhone/Debug/mtouch-cache/arm64/Xamarin.iOS.dll.o' was built with class_ro_t pointer signing enabled, but previous .o files were not
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): error : linker command failed with exit code 1 (use -v to see invocation)
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): error : warning: '/Users/enricoziehe/Library/Caches/Xamarin/mtbs/builds/BeetControl.iOS/481a9da9dded3425f26c86f26810958b457ceb30151c1ab9afcbee08f779190c/obj/iPhone/Debug/mtouch-cache/arm64/Xamarin.iOS.dll.o' was built with class_ro_t pointer signing enabled, but previous .o files were not
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): error MT5214: Native linking failed, undefined symbol: _OrtSessionOptionsAppendExecutionProvider_ROCM. This symbol was referenced by the managed member Microsoft.ML.OnnxRuntime.NativeMethods.OrtSessionOptionsAppendExecutionProvider_ROCM. Please verify that all the necessary frameworks have been referenced and native libraries linked.
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): warning MT5215: References to 'ole32' might require additional -framework=XXX or -lXXX instructions to the native linker
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): warning MT5215: References to 'System.Net.Security' might require additional -framework=XXX or -lXXX instructions to the native linker
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): warning MT5215: References to 'c' might require additional -framework=XXX or -lXXX instructions to the native linker
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): warning MT5215: References to 'Kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): warning MT5215: References to 'libEGL' might require additional -framework=XXX or -lXXX instructions to the native linker
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): warning MT5215: References to 'ole32' might require additional -framework=XXX or -lXXX instructions to the native linker
2>C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(238,3): error MT5201: Native linking failed. Please review the build log and the user flags provided to gcc: -lc++

When i build on another Intel Cpu based Build Host its works as expected. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOs 12.3.1 on Apple M1 Pro
- ONNX Runtime installed from (source or binary): Nuget
- ONNX Runtime version: 1.11.0
- Python version:
- Visual Studio version (if applicable): 17.1.4
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Create a new xamarin Form Project from Template in Vs2022
- Add ORT to all Projects
- Connect to Mac 
- Start debugging on Ios Emulator or Device

**Expected behavior**
the Build should be successfuly and Debugger starts

**Comment by skottmckay** [comment]
There's a stub here that should provide the symbol here: https://github.com/microsoft/onnxruntime/blob/a00d24066a3f7bd99ae2bec2dc6c1ebff522aa67/onnxruntime/core/session/provider_bridge_ort.cc#L1408-L1413

There are stubs for a number of other EPs in that file and I don't see any errors for them in the output you included, so I'm not sure why only ROCM has an issue, and why that doesn't occur on Intel based machines. 

@mikeparker104 do you have any ideas? 

Short term you could comment out the ROCM usage in the C# bindings. 

Here: https://github.com/microsoft/onnxruntime/blob/a00d24066a3f7bd99ae2bec2dc6c1ebff522aa67/csharp/src/Microsoft.ML.OnnxRuntime/NativeMethods.shared.cs#L832-L833
and here: https://github.com/microsoft/onnxruntime/blob/a00d24066a3f7bd99ae2bec2dc6c1ebff522aa67/csharp/src/Microsoft.ML.OnnxRuntime/SessionOptions.shared.cs#L297-L298

**Comment by markive** [comment]
I have this same issue on a brand new Macbook Pro

**Comment by skottmckay** [comment]
Does commenting out that code in the two .cs files I mentioned work around the problem?

**Comment by skottmckay** [comment]
Hopefully that PR will fix it. May take a couple of days to get a nuget package onto the nuget test repo for validation.

**Comment by skottmckay** [comment]
Is it possible to try building with ORT v1.10 to see if that works? Would give another data point as _OrtSessionOptionsAppendExecutionProvider_ROCM should have been excluded from an iOS build in that release.

**Comment by mikeparker104** [comment]
@enny1170 please can you share a binlog with us?

**Comment by smilingjack10** [comment]
> Is it possible to try building with ORT v1.10 to see if that works? Would give another data point as _OrtSessionOptionsAppendExecutionProvider_ROCM should have been excluded from an iOS build in that release.

Building with ORT v1.10 works without errors. It is possible to build with v1.11 when setting the linker behavior to: "enable framework SDKs only".
As a workaround: I currently set ORT to v1.10 when debugging with linking disabled and update ORT to v1.11 for the release with linking enabled. Otherwise, each build takes over 3 minutes and hot reload doesn't work with linking.

**Comment by skottmckay** [comment]
Awesome. Thanks for the info and valuable tips around usage @smilingjack10. Much appreciated. Issue should be fixed in the next ORT release. 

If you want to test things out prior to that, you could possibly download the two nuget packages from https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly. Those are published from the current builds with the latest code. Download to a folder and setup that folder as a nuget source.

**Comment by skottmckay** [comment]
Should be resolved with the 1.12 release.

**Comment by enny1170** [comment]
Where i can get this log?

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________
