### ISSUE TITLE
Create script to export BART encoder and decoder for use with custom beam search op

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnxruntime#11210]
**Is your feature request related to a problem? Please describe.**
Under https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/transformers/models, a set of tools to enable users to export BART encoder and decoder to ONNX, for use with custom beam search op.

**Comment by mfuntowicz** [comment]
ORT folks contributed an example for this on the transformers repository if it can be useful: https://github.com/huggingface/transformers/tree/main/examples/research_projects/onnx/summarization

**Comment by tianleiwu** [comment]
@BowenBao, thanks for raising the feature request. we are working on encoder and decoder support in beam search op (currently using T5 as example). After that is ready, we will work on BART integration.

**Comment by BowenBao** [comment]
@tianleiwu thanks for following up. I have created a simple initial version for helping Ye with the implementation. Will create a PR afterwards.

**Comment by BowenBao** [comment]
PR work in progress.

**Comment by AllenTiTaiWang** [comment]
8/11 Update:

1. Model has been exported successfully.
2. Model has mismatched performance between Pytorch and ONNX
3. Validated Encoder and Decoder parts of model, and the results match Pytorch
4. Now, Having ONNXRUNTIME team checks beam search op result
