### ISSUE TITLE
[web] Why is `ort.env.wasm.proxy` not `true` by default?

### ISSUE THREAD

**Issue by josephrocca** [microsoft/onnxruntime#11218]
**Is your feature request related to a problem? Please describe.**
It's almost never a good idea to run heavy computation on the main thread, so it seems like most of the time people would want to set this to true.

Perhaps the idea was that the inference session may sometimes be created by the developer inside a worker, and the extra layer of indirection would then be a waste? In that case I think the burden should be on those developers to find/understand/adjust the options to suit their use case, since it's likely a less common situation, and also is not really a big deal (having an extra, unnecessary worker) compared to lagging the main thread.

Perhaps, to get the best of both worlds, the library could detect whether it's running on the main thread ([like this](https://stackoverflow.com/a/18002694)) and default to proxying via a worker if so. But unless I'm missing something here I think defaulting to creating the proxy worker is fine.

**System information**
- ONNX Runtime version (you are using): https://cdn.jsdelivr.net/npm/onnxruntime-web@1.11.0/dist/ort.js

**Describe the solution you'd like**
If most users should be setting `ort.env.wasm.proxy` to `true`, then that should be the default value.

**Describe alternatives you've considered**
Another possibility is to adjust the default based on whether it's executing on the main thread vs. the worker.

**Comment by fs-eire** [comment]
there are 3 reasons for not setting this to 'true' by default.

the first reason is for backward compatibility. some users do not expect to have a new web worker created without any code change.

the second reason is that for some small models, the inference time is very small so that does not hurt the main thread performance. instead, using a proxy in this scenario will increase the latency (there is anyway overhead)

the third reason is we have a plan to make onnxruntime web available in web worker (ie. something like `importScript('./ort.min.js')`. currently this is not supported yet), which eventually supports more flexible usages in different scenarios, so using proxy is one of the options that users can choose from.

**Comment by josephrocca** [comment]
@fs-eire, do you have usage data/feedback which supports your second point? I'd guess that this is not the case for most users. IIRC, a `postMessage` takes less than a millisecond (unless the data is huge - but in that case transferable objects should help keep it on the order of a few milliseconds at most).

RE your first point, I wouldn't have thought that the creation of a webworker would be a breaking change, since it seems like just an implementation detail that can't break existing code (though it could slow it down by a millisecond or so for some users - RE your second point).

IIUC, the third point doesn't preclude the proxy mode from being the default.

Thinking about this from a user experience perspective, I think it makes sense for the defaults to match what the vast majority of users would want. If you have data/feedback to suggest that most users have models that inference in just a few milliseconds (and have super low latency as a strong requirement), then I think the current situation is a good default, but if not (and if you can't change it for v1), then I hope you'll consider changing it for v2. Otherwise, please feel free to close this.

Thanks for your reply!

**Comment by guschmue** [comment]
we have no plan to enable the proxy by default.

**Comment by josephrocca** [comment]
Hey @guschmue, would it be possible to warn users in the console if main thread is blocked for more than e.g. 100ms, and tell them about the `ort.env.wasm.proxy` feature? I.e. just track start and end time of the computation and check if it's too long.

**Comment by guschmue** [comment]
fair request, we'll discuss it what we can do.
