### ISSUE TITLE
Option/Mode to Build Onnx Runtime with Full Onnx Support

### ISSUE THREAD

**Issue by GuanLuo** [microsoft/onnxruntime#1122]
**Is your feature request related to a problem? Please describe.**
I am using Onnx Runtime library and expecting it to have full Onnx support as it promises. But some data types for some operators are turned off as discussed in #1080. Right now it is inconvenient to ensure that the Onnx Runtime library has all Onnx operators enabled, as I need to do something similar to 31cbb5d and then rebuild to support some data types.

**System information**
- ONNX Runtime version (you are using): 0.4.0

**Describe the solution you'd like**
I am looking for a build option/mode so that I can build the library with full Onnx support. If the option/mode is not set, then the library will fall back to the current setting.

**Comment by faxu** [comment]
Hi, are there some common types you've found are needed but not currently supported? We're looking into ways to support types more fully, though it's a balance between minimizing binary size and breadth of support. If there are specific things you've commonly found missing, this will be useful for the assessment.

**Comment by GuanLuo** [comment]
Hi, I haven't encountered actual use cases that required unsupported data types, I was just expanding our application's test cases to cover some custom models and noticed some data types are unsupported.

That being said, our application allows users to provide their own Onnx models which may come with various operators and types. That is why I wish there is a build option to build the library with Onnx support that matches the version matrix. Perhaps if that build option is not set, the library will be built with minimized setting to meet the balance between size and breadth of support as you mentioned.

I understand that it will be a long process to add such build option (or other equivalent), so at the meantime, it will be helpful if there is a table about what types in operators are currently disabled in Onnx Runtime. So that in the case similar to #1080, I can refer to the table and know if the error is due to incorrect usage of the APIs.

**Comment by linkerzhang** [comment]
Thank you @GuanLuo for the constructive feedback!

Let's do it this way, as you suggested, to firstly come out of the table containing not supported types for each op in ONNX, secondly, add type support drive by demand (as there's no missing common data type list right now, and it's not that good to just add all types). Make sense please?

**Comment by GuanLuo** [comment]
@linkerzhang Sure, and do you mind to point me to the table once it is available? Thanks.

**Comment by shahasad** [comment]
@linkerzhang, @GuanLuo:
Here is a table of currently implemented ops and the supported types. Hope this helps -
https://github.com/microsoft/onnxruntime/blob/master/docs/OperatorKernels.md

**Comment by faxu** [comment]
At this time, there is no plan for ORT to support all data types due to binary size considerations and utility of such support.
