### ISSUE TITLE
Question on quantize tool 

### ISSUE THREAD

**Issue by yeliang2258** [microsoft/onnxruntime#11225]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.

**I would like to ask, why do you need to delete relu and clip in the quantization tool? Would such an operation result in a precision error ?**

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary):binary
- ONNX Runtime version: develop
- Python version: python3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**
**I would like to ask, why do you need to delete relu and clip in the quantization tool? Would such an operation result in a precision error ?**
![image](https://user-images.githubusercontent.com/30516196/163541971-e2695c7a-353a-429b-87ce-916e76b44b28.png)

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by yufenglee** [comment]
Relu and Clip can be removed from quantized model directly because both of them just squeeze the tensor to a certain range [min, max] and actually we can incorporate the range into the calibration range that is used to calculate scale and zero point. Take relu for example, it makes tensor to range [0, inf) and let's say the calibration range of the input of the Relu node is [a, b]. Then the output range of Relu must be [max(0,a), b]. Thus, we can remove Relu directly and only keep the output of Relu with calibration range [max(0,a), b].

**Comment by yeliang2258** [comment]
But in asymmetric quantization, deleting relu will give wrong results. In actual verification, I find that my inference results are wrong.

**Comment by yufenglee** [comment]
Do you mean in '**symmetric**' quantization on activation? This issue was discussed in #9424.

**Comment by yeliang2258** [comment]
Thank you for your reply. 
I have another question, dynamic quantization can obtain scale information in real time, which is more flexible and convenient than static quantization, so what are the advantages and characteristics of static quantization? When should static quantization be used? How should we choose?
Looking forward to your answer, thanks
