### ISSUE TITLE
C++ Library Linking Question

### ISSUE THREAD

**Issue by lsy323** [microsoft/onnxruntime#1123]
Hi all,

I would like to use the C++ API of ONNX Runtime in my C++ program. I successfully built the ONNX Runtime from source code, however, I couldn't find the shared library (.so) in the build directory. Dose someone have the experience of using the C++ API of ONNX Runtime? 

Thanks!

**Comment by jywu-msft** [comment]
build shared lib option is by default off https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L66

if you're using build script (build.sh/build.bat) you can use the --build_shared_lib option
https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/build.py#L96

**Comment by lsy323** [comment]
> build shared lib option is by default off https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L66
> 
> if you're using build script (build.sh/build.bat) you can use the --build_shared_lib option
> https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/build.py#L96

Appreciate it, I can generate the shared library now.
