### ISSUE TITLE
Quantied model get impossiable to inference result mode.

### ISSUE THREAD

**Issue by luohao123** [microsoft/onnxruntime#11234]
I have a quantized model which is instance sgmentation.
the float32 model can inference can run, but after quantized: 

```
quantization/qlinear_concat.cc:36 onnxruntime::contrib::QLinearConcat::QLinearConcat(const onnxruntime::OpKernelInfo &) input_def_count >= 8 && (input_def_count - 2) % 3 == 0 was false. At least two inputs are needed, and each input must be (tensor, scale, zero_point) tuple!
```

this error make my model unable to run.  It says some concat issue, how to resolve??

For model information, this might related about the problem:

<img width="626" alt="image" src="https://user-images.githubusercontent.com/49749220/163676345-ab63b066-f04b-4cf4-a01f-0ec399d8bad8.png">

**Comment by yufenglee** [comment]
dup with #11242
