### ISSUE TITLE
Unable to use any OnnxRuntime packages >1.7 with CMake

### ISSUE THREAD

**Issue by aravindyeduvaka** [microsoft/onnxruntime#11230]
**Describe the bug**
I am using the prebuilt binaries from Github release to setup OnnxRuntime with a CMake Project. However, I am unable to use any version higher than 7. I get the following error: 
_"The given version [8] is not supported, only version 1 to 7 is supported in this build="_
Same with any other releases including  9,10 and 11. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11
- ONNX Runtime installed from (source or binary): Prebuilt Binaries
- ONNX Runtime version: 1.8 to 1.11
- Python version: -
- Visual Studio version (if applicable): 16.11.12
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory: 

**To Reproduce**
- Describe steps/code to reproduce the behavior.
(I setup a very bare bones CMake project that repros this issues. https://github.com/aravindyeduvaka/OnnxCMake )
Setup a new CMake Projects that downloads the prebuilt binary and links it to the target executable. 
When running the project, it throws an error complaining about the version 
"The given version [10] is not supported, only version 1 to 7 is supported in this build"
The sample does work with version 7 so something changed between 7 and 8 that is not supported for CMake projects

- Attach the ONNX model to the issue (where applicable) to expedite investigation.
This error is thrown when creating the environment so the actual model that we are loading is irrelevant. 

**Expected behavior**
I would expect this should work since its a very basic setup with prebuilt binaries. Is the support for CMake discontinued since version 8?

**Comment by snnn** [comment]
Sorry I can't reproduce the problem.  Very likely you loaded a wrong onnxruntime.dll (just my guessing). 

To debug it. I recommend using windbg and enable loader snaps. Here is one example: https://github.com/microsoft/onnxruntime/issues/4009#issuecomment-665763403

When you get it enabled, you will see where onnxruntime.dll was loaded from. Please check the path. Is it the one which was just downloaded by cmake? I suspect on that.

**Comment by aravindyeduvaka** [comment]
Thank you for helping with this. I setup the CMake dependency using FetchDeclareContent automatically and the links are from the github relelase. Here's the line where this is done. 
[https://github.com/aravindyeduvaka/OnnxCMake/blob/77b85611098dd27cff01da96e039bd637634f9b3/CMakeLists.txt#L16 ](url)
I am pretty sure we are loading the right dll since I manually link the dependency into the CMake project and I do not encounter any issue when I load version 1.7 but only see errors at runtime when using any higher versions.

**Comment by snnn** [comment]
Have you tried windbg?

**Comment by WilliamVenner** [comment]
I am also getting this. I downloaded version 1.11 of the GPU runtime from https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.gpu and linked against `runtimes/win-x64/native/*.[dll|lib]` and included the `build/native/include/*` headers in my program, yet I get:

`The given version [11] is not supported, only version 1 to 7 is supported in this build.`

**Comment by WilliamVenner** [comment]
Oh my god it's loading 1.7.0 from System32

This must be a Windows 11 thing

![image](https://user-images.githubusercontent.com/14863743/163689683-3836b0bf-f5d9-4ce4-a53a-0ce7567ea329.png)

**Comment by snnn** [comment]
That's the problem.

**Comment by snnn** [comment]
For more information, please read: https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order

The Standard Search Order for Desktop Applications starts with the directory from which the application loaded. i.e. where your main executable(*.exe) lives. So, please put onnxruntime.dll there.

**Comment by yuslepukhin** [comment]
Do not load System32 copy of `onnxruntime.dll`

**Comment by tildekarthik** [comment]
I am not an expert in dotnet or CPP but here is what solved the problem - I installed Visual C++ runtime for x64 (Server was Xeon running Windows 2016 server 64 bit)

solved the problem for me

**Comment by smaslov-intel** [comment]
@snnn, we are hitting a similar issue now. It's certainly not OK to have a system library to print something if loaded, but not used. Are you going to fix that?

**Comment by snnn** [comment]
@smaslov-intel, surely. I will fix what is certainly not OK. Feel free to create an issue to tell me what you want me to fix, and assign it to me. I would be happy to help.

**Comment by smaslov-intel** [comment]
> @smaslov-intel, surely. I will fix what is certainly not OK. Feel free to create an issue to tell me what you want me to fix, and assign it to me. I would be happy to help.

This issue is exactly about what is wrong: the system's onnxruntime.dll is printing out  the
> "The given version [X] is not supported, only version 1 to Y is supported in this build."

Please also consider renaming the system's version to something else than onnxruntime.dll since many users are going to be affected by this due to obscure DLL search rules in Windows.

**Comment by wenkaiH** [comment]
> > @smaslov-intel, surely. I will fix what is certainly not OK. Feel free to create an issue to tell me what you want me to fix, and assign it to me. I would be happy to help.
> 
> This issue is exactly about what is wrong: the system's onnxruntime.dll is printing out the
> 
> > "The given version [X] is not supported, only version 1 to Y is supported in this build."
> 
> Please also consider renaming the system's version to something else than onnxruntime.dll since many users are going to be affected by this due to obscure DLL search rules in Windows.

same problem on Linux!!!

**Comment by Sencc** [comment]
@wenkaiH Hi,have you solved it?

**Comment by snnn** [comment]
@wenkaiH , which Linux version do you have? Do you have multiple libonnxruntime.so in your system?

**Comment by ShubhamSaini01** [comment]
any movement on this?

> > @smaslov-intel, surely. I will fix what is certainly not OK. Feel free to create an issue to tell me what you want me to fix, and assign it to me. I would be happy to help.
> 
> This issue is exactly about what is wrong: the system's onnxruntime.dll is printing out the
> 
> > "The given version [X] is not supported, only version 1 to Y is supported in this build."
> 
> Please also consider renaming the system's version to something else than onnxruntime.dll since many users are going to be affected by this due to obscure DLL search rules in Windows.

any movement on this? I'm using 1.17.1 and facing same problem.

**Comment by gabriellanzer** [comment]
> any movement on this? I'm using 1.17.1 and facing same problem.

Copying the right DLL to your binary location should fix the problem. I have an xmake project using 1.17.1 and I was facing this issue and all I had to do was to setup a small post-build step to copy the files over. Like so:
```
    -- Copy the ONNX Runtime DLL to the target directory after build
    after_build(function (target)
		print("Copying ONNX Runtime DLLs to target directory")
        local onnxruntime_dir = path.join(target:pkg("onnxruntime"):installdir(), "bin")
        local dll_files = os.files(path.join(onnxruntime_dir, "*.dll"))
        for _, dll in ipairs(dll_files) do
            os.cp(dll, target:targetdir())
        end
    end)
```
