### ISSUE TITLE
Windows PDB files?

### ISSUE THREAD

**Issue by WilliamVenner** [microsoft/onnxruntime#11243]
Hello, where are the PDB files for onnxruntime.dll and friends?

They don't appear to be included in the NuGet packages, and the Microsoft Symbol Server allegedly doesn't have them:

![image](https://user-images.githubusercontent.com/14863743/163728320-e72b6049-abaa-4370-9c39-7278b0139c8c.png)

**Comment by snnn** [comment]
I suggest you download them from https://github.com/microsoft/onnxruntime/releases

**Comment by snnn** [comment]
The DLLs in the zip files are the same as what you got from nuget. But the zip files also contain PDBs. Nuget.org doesn't accept native(C/C++) debug symbols. We can publish our symbols to Microsoft Symbol Servers. In the past, we always did it. But we only published stripped ones(without [private symbols](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/public-and-private-symbols) ). We could publish the full version, it's just I didn't have enough time to do it yet.

**Comment by WilliamVenner** [comment]
Brilliant, thanks!
