### ISSUE TITLE
how to convert the quantized onnx model gnerated by ort into tensorrt?

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#11258]
how to convert the quantized onnx model gnerated by ort into tensorrt?

**Comment by yufenglee** [comment]
we have tensorrt ep. you can quantize the model with QDQ format and run with tensorrt ep, like the example here: https://github.com/microsoft/onnxruntime-inference-examples/tree/main/quantization/nlp/bert/trt.

**Comment by jinfagang** [comment]
@yufenglee  Hi, what if I want using tensorrt purely? Is the possible convert the onnx to trt engine?

**Comment by yufenglee** [comment]
For this question, you'd better go to the onnx-parser for official answer. In general, if you quantized the model with QDQ format, TRT should be able to run.

**Comment by jinfagang** [comment]
@yufenglee may I ask what's the difference between QDQ format and QOperator format?
