### ISSUE TITLE
Test data 404

### ISSUE THREAD

**Issue by xkszltl** [microsoft/onnxruntime#11253]
**Describe the bug**

https://github.com/microsoft/onnxruntime/blob/master/docs/Model_Test.md

> Download https://onnxruntimetestdata.blob.core.windows.net/models/20190419.zip and unzip it.

Got 404 from this URL today.
Given the same date (20220419) as in file name, is it "expired"?

**Comment by xkszltl** [comment]
Same issue with the URL in CI pipelines: https://github.com/microsoft/onnxruntime/blob/8d737f977056444a307f1b7f0bcd402fba62d790/tools/ci_build/github/azure-pipelines/templates/set-test-data-variables-step.yml#L4

**Comment by pranavsharma** [comment]
@snnn any idea?

**Comment by snnn** [comment]
I'm removing the outdated files. Like this:  #8894

**Comment by xkszltl** [comment]
> I'm removing the outdated files. Like this: #8894

What's outdated? The yaml or the data?
That PR seems to be staled.

And which test data are you currently using?

**Comment by snnn** [comment]
The file https://onnxruntimetestdata.blob.core.windows.net/models/20191107.zip  only contains public models from ONNX model zoo and TF slim models: https://github.com/tensorflow/models/tree/master/research/slim . Now it is not used in our build pipelines. The test data was about 30GB, and we have over 50 build jobs for each PR, which means need to download 1.5TB data for each PR iteration.  Instead,  now I preinstall the test data and models to our build machines, so that we don't need to download the huge file in every build pipeline run.

**Comment by xkszltl** [comment]
Could you provide alternative for other people, not just your CI machine, to use?
We rely on ort's unit tests to validate our build, for both correctness, linkage, permission, path, ...
The removal of data completely blocks 3rd-party from running ort tests.

**Comment by xkszltl** [comment]
Or maybe your script for packaging that zip file? We can pull from public zoo instead, actually that's better, but we want to make sure we're fully align with whatever assumption/layout you have.

**Comment by snnn** [comment]
I don't have any script for doing that.

**Comment by xkszltl** [comment]
So did you manually put together that?
Any way we can recreate (at least a subset of) that?

**Comment by snnn** [comment]
It was a shared folder. Many engineers wrote data into it.

**Comment by xkszltl** [comment]
So can we have some way to allow people outside of ort/microsoft get unit test data? Or there'll be a big gap for whoever trying to build ort themselves.

Feel free to include PM here if you think it's a feature request rather than a big fix.
IMHO this is a critical feature for an open-source lib.

**Comment by snnn** [comment]
We can distribute onnxruntime source code and binary, but we can't redistribute the other one's models as they are not made by us. 
And I can't make internal models public.  Please think how I can satisfy both of the following needs:
1. Validate each change in ORT to make sure it would not break @xkszltl 's in-production model
2. Share the models to everyone

**Comment by xkszltl** [comment]
Maybe there're some misunderstanding here.
I never asked for private model, and didn't expect to guard the code quality by downstream use case.
What I'm asking for is the public data required for CI/unit testing, i.e. a way to run ctest.

**Comment by snnn** [comment]
Updated the doc: https://github.com/microsoft/onnxruntime/blob/main/docs/Model_Test.md
