### ISSUE TITLE
provider_api.h can easily cause redefinition error

### ISSUE THREAD

**Issue by cloudhan** [microsoft/onnxruntime#11276]
provider_api.h  defines multiple enum and macro, they are defined in other header files. If they are both included, redefinition error, this violates the ODR rule of C++. All these potential redefinition should be extracted into shared header files or guarded by include guard to avoid the ODR violation.

**Comment by cloudhan** [comment]
@RyanUnderhill Ping you because provider_api.h is added by you and the comment left as:
```
// NOTE: This is still in development so there are many parts that will be fixed in the future. This is just the first version of
//       switching providers to be runnable as shared libraries. The interfaces will become more tightly integrated into the core code.

```
after 23 month...

**Comment by snnn** [comment]
ODR rule is on paper only. It seems to be true as an idea, but may not be true in a real situation.  If you read https://en.wikipedia.org/wiki/One_Definition_Rule, it says "... cannot have more than one definition in the entire program". It is not true.  It should be corrected as  "... in the entire PE or ELF binary".  I'm not going to fight with the bureaucracies.

**Comment by snnn** [comment]
I guess it was causing trouble for you when you included both this file and some other ONNX header files.  For now the usage is not supported yet.
