### ISSUE TITLE
" CMAKE_CUDA_ARCHITECTURES must be valid if set" when manually building onnx runtime on jetson nano 

### ISSUE THREAD

**Issue by quangsonle** [microsoft/onnxruntime#11273]
**Describe the bug**
moving as the instruction at https://onnxruntime.ai/docs/build/eps.html
this step " ./build.sh --config Release --update --build --parallel --build_wheel \
 --use_cuda --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu" results in "CMake Error at /usr/local/share/cmake-3.23/Modules/CMakeDetermineCUDACompiler.cmake:311 (message):
  CMAKE_CUDA_ARCHITECTURES must be valid if set.
Call Stack (most recent call first):
  CMakeLists.txt:1697 (enable_language)
"
while jetpack 4.61 comes with cuda 10.2
**Urgency**
it is urgent because there is no release of onnx runtime for aarch64 gpu, must build it from source

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): jetpack 4.6.1: ubuntu 18.04
- ONNX Runtime installed from source 

- Python version:3.6.9
- Visual Studio version (if applicable):
- GCC/Compiler version:7.5.0
- CUDA/cuDNN version:10.2

**To Reproduce**
nano jetson with jetpack 4.6.1. upgrade cmake to the newest version (here is 3.23). ensure python, pip are installed

**Comment by snnn** [comment]
First, please find out the correct CUDA ARCH value from https://developer.nvidia.com/cuda-gpus 
Then add the following to your build command

--cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES=put_your_value_here"
