### ISSUE TITLE
C# Api for Training

### ISSUE THREAD

**Issue by 3threeFX** [microsoft/onnxruntime#11297]
System information:
    OS version/distro: Win10(19044)
    Visual Studio 2022 IDE
    .NET Version (eg., dotnet --info): .Net 6

Is there a plan/roadmap to support ONNX training API through C# in the future? so for example we can retrain a pretrained onnx model on ML.NET or ...

**Comment by baijumeswani** [comment]
@3threeFX, there is a plan to introduce C++ training API in onnxruntime-training package and we will also be extending the api to C# using language bindings. Please stay tuned as we execute this plan over the next few months.

**Comment by 3threeFX** [comment]
dear @baijumeswani is there any news about C# training API ?? As it seems it was not implemented in [v1.12.0](https://github.com/microsoft/onnxruntime/releases/tag/v1.12.0) release ...

**Comment by baijumeswani** [comment]
Hi @3threeFX. These APIs are not available in ort 1.12.0. Having said that, please take a look at this PR: https://github.com/microsoft/onnxruntime/pull/12404 for more details. We are still working actively on this front. Thanks for being patient as we work through these new developments.
