### ISSUE TITLE
Can't find gpt2_helper  ModuleNotFoundError: No module named 'gpt2_helper'

### ISSUE THREAD

**Issue by causten** [microsoft/onnxruntime#11292]
**Describe the bug**

I built the code and installed it (pip install ./build/Release/dist/*.whl ; ldconfig).  I now get an error indicating the module could not be found.   

I have to run `export PYTHONPATH=/opt/conda/lib/python3.7/site-packages/onnxruntime/transformers/models/gpt2/` to get it to work.  Likely something to do with  #11256 

```
onnxruntime/build/Release/onnxruntime/transformers# python3 ./benchmark.py  -g -m bert-base-cased --sequence_length 384 --batch_sizes 1 --provider=migraphx -p fp16 --disable_gelu --disable_layer_norm --disable_attention --disable_skip_layer_norm --disable_embed_layer_norm --disable_bias_skip_layer_norm --disable_bias_gelu
Traceback (most recent call last):
  File "./benchmark.py", line 58, in <module>
    from onnx_exporter import create_onnxruntime_input, load_pretrained_model, export_onnx_model_from_pt, export_onnx_model_from_tf
  File "/workspace/onnxruntime/build/Release/onnxruntime/transformers/onnx_exporter.py", line 15, in <module>
    from gpt2_helper import GPT2ModelNoPastState, PRETRAINED_GPT2_MODELS, TFGPT2ModelNoPastState
ModuleNotFoundError: No module named 'gpt2_helper'
```

**Urgency**
The benchmark is used often, I have a workaround but others will not.  Please fix

**System information**
- Linux Ubuntu 20.04:
- ONNX Runtime installed from (source or binary):  Source
- ONNX Runtime version: master branch
- Python version: 3.7.13
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: ROCm 5.1.1
- GPU model and memory: gfx90a

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**
Script should run to completion

**Comment by wangyems** [comment]
Thanks for reporting the issue!
