### ISSUE TITLE
Cross compile error on Linux for ARM

### ISSUE THREAD

**Issue by enobufs** [Microsoft/onnxruntime#113]
**Describe the bug**
I tried to build ARM package with cross-compiling on my Linux PC (Ubuntu 16.04), following the instruction [BUILD.md](https://github.com/Microsoft/onnxruntime/blob/master/BUILD.md).  Cmake completed, but during the `make`, I saw the following error:

```
  :
[ 31%] Built target protoc
[ 31%] Running cpp protocol buffer compiler on /home/ytakeda/Projects/onnxruntime/onnxruntime/onnxruntime/core/protobuf/onnx-operators-ml.proto
../external/protobuf/cmake/protoc: 1: ../external/protobuf/cmake/protoc: Syntax error: word unexpected (expecting ")")
onnx/CMakeFiles/onnx_proto.dir/build.make:70: recipe for target 'onnx/onnx-operators-ml.pb.h' failed
make[2]: *** [onnx/onnx-operators-ml.pb.h] Error 2
CMakeFiles/Makefile2:1185: recipe for target 'onnx/CMakeFiles/onnx_proto.dir/all' failed
make[1]: *** [onnx/CMakeFiles/onnx_proto.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master rev `4801e` and `resease-0.1.5` (the same result)
- Python version: 2.7.12 and 3.5.2 installed (I guess not used by cmake/make)
- GCC/Compiler version (if compiling from source): gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**To Reproduce**
First, downloaded gcc-linaro-6.3.1 as instructed, extracted it into /opt/.
Then, downloaded pre-compiled protoc from [here](https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip), then moved ./bin/protoc into /usr/bin/.
Then, on the terminal...
```
   export PATH=/opt/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/bin:$PATH
   export CC=arm-linux-gnueabihf-gcc
   export CXX=arm-linux-gnueabihf-g++```
```
Next, I created `tool.cmake` file as following:
```
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_CXX_COMPILER arm-linux-gnueabihf-c++)
set(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```
> Note: both `arm-linux-gnueabihf-c++`  and `arm-linux-gnueabihf-gcc` had to be modified from what BUILD.md had. (this should be updated)

```
git clone --recursive https://github.com/Microsoft/onnxruntime
cd onnxruntime
mkdir my_build
cd my_build
cmake -DCMAKE_TOOLCHAIN_FILE=../../tool.cmake ../cmake
```
Then;
```
make
```

**Expected behavior**
`make` command to be complete successfully.

**Additional context**

Please let me know what could cause the error.  Thanks.

**Comment by enobufs** [comment]
Thanks! Following cmake command worked for me:
```
cmake \
    -DCMAKE_TOOLCHAIN_FILE=../../tool.cmake \
    -DONNX_CUSTOM_PROTOC_EXECUTABLE=/usr/bin/protoc \
    ../cmake
```

Things to be fixed in BUILD.md:
* Add description for `ONNX_CUSTOM_PROTOC_EXECUTABLE` variable
* Fix the example for `tool.cmake` as I mentioned earlier.

**Comment by enobufs** [comment]
Could you tell me if building python wrapper (for ARM) using cross-compiling is possible? I believe libpython3.5-dev for armhf is needed, which is not included in linaro...

**Comment by Klein-Hu** [comment]
Sorry, I don't think we currently have the instruction for cross compiling the python binding. You could try 
to use [Azure Container Registry](https://azure.microsoft.com/en-us/services/container-registry/) to [build](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tutorial-quick-task) in the cloud or setup [QEMU](https://www.qemu.org/) locally and build with it.

> Could you tell me if building python wrapper (for ARM) using cross-compiling is possible? I believe libpython3.5-dev for armhf is needed, which is not included in linaro...

**Comment by snnn** [comment]
Close the issue as the original problem is solved.

**Comment by Clarence-wcz** [comment]
Does cross-compilation only generate static libraries? I generate dynamic libraries when I execute the "./build.sh "command on my PC. But when compiled directly with cmake, it appears that only static libraries are generated.
