### ISSUE TITLE
CPUExecutionProvider but GPU visible

### ISSUE THREAD

**Issue by alwynmathew** [microsoft/onnxruntime#11323]
**Describe the bug**
Even thought onnxruntime can see my GPU I cant set `CUDAExecutionProvider` as provider. I get `[W:onnxruntime:Default, onnxruntime_pybind_state.cc:535 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider.`

**System information**
- OS Platform and Distribution: Ubuntu 20.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.10.0
- ONNX version: 1.10.2
- Python version: 3.7
- CUDA/cuDNN version: CUDA 11.3 cuDNN 8200

**To Reproduce**
```
print(onnxruntime.get_available_providers()) 
# ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']

torch.onnx.export(model, 
                  dummy_input,  
                  save_path,  
                  operator_export_type=torch.onnx.OperatorExportTypes.ONNX, 
                  export_params=True, 
                  opset_version=11, 
                  verbose=False)
# while onnx export I get below warning
# Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.

if torch.cuda.is_available():
    ort_session = onnxruntime.InferenceSession(save_path, providers=['CUDAExecutionProvider'])
else:
    ort_session = onnxruntime.InferenceSession(save_path, providers=['CPUExecutionProvider'])

print(ort_session.get_providers()) 
# ['CPUExecutionProvider']
onnxruntime.get_device()
# GPU
```

I also found, if I uninstall `onnxruntime` and just keep `onnxruntime-gpu`, I'm not able to import `onnxruntime`. Currently my system has
```
onnxruntime==1.9.0
onnxruntime-gpu==1.10.0
```

I also recorded 
Pytorch inference time : 0.4931 sec
ONNX inference time : 0.0290 sec
Is onnx model running on GPU?

**Expected behavior**
```
ort_session = onnxruntime.InferenceSession(save_path, providers=['CUDAExecutionProvider'])
print(ort_session.get_providers()) 
# ['CUDAExecutionProvider']
onnxruntime.get_device()
# GPU
```

**Comment by tianleiwu** [comment]
You only need install onnxruntime-gpu but not onnxruntime. onnxruntime-gpu supports both CPU and CUDA execution providers. Otherwise, python might not be able to import the right package of onnxruntime.

**Comment by alwynmathew** [comment]
[CUDA-ExecutionProvider.html#requirements](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements) page shows CUDA versions 11.4 and 11.03 but I have CUDA 11.3 and cuDNN 8.3, which version of `onnxruntime-gpu` is recommended?

**Comment by alwynmathew** [comment]
I removed both `onnxruntime` and `onnxruntime-gpu`, and reinstalled `onnxruntime-gpu==1.10`  inside my conda env
```
pip uninstall onnxruntime
pip uninstall onnxruntime-gpu
pip install onnxruntime-gpu==1.10
```

But still the problem persist.
```
ort_session = onnxruntime.InferenceSession(save_path, providers=['CUDAExecutionProvider'])
print(ort_session.get_providers()) 
# ['CPUExecutionProvider']
onnxruntime.get_device()
# GPU
```
I still get this warning

> [W:onnxruntime:Default, onnxruntime_pybind_state.cc:535 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.

**Comment by Ki6an** [comment]
please update your Cuda version to 11.4 try again

**Comment by yuslepukhin** [comment]
The error message says that it can not load `dependacies`. Please, ensure that the system can fine all the necessary libraries.

**Comment by alwynmathew** [comment]
Thank you @Ki6an.  Updating to `CUDA 11.4` with `cudnn 8` solved this issue. 

Correct me if I'm wrong, officially `onnruntime-gpu` does not support `CUDA 11.3` as per [official requirement page](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html). `onnruntime-gpu` officially only support `CUDA 11.3, 11.0.3, 10.2 ...` with corresponding `cudnn 8.2.4, 8.0.4, 8.0.3 ...`.

**Comment by KASHIFMD** [comment]
> [CUDA-ExecutionProvider.html#requirements](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements) page shows CUDA versions 11.4 and 11.03 but I have CUDA 11.3 and cuDNN 8.3, which version of `onnxruntime-gpu` is recommended?

How do you get cuDNN version as 8.3?
