### ISSUE TITLE
Use C++ API in shared library

### ISSUE THREAD

**Issue by lsy323** [microsoft/onnxruntime#1134]
Hi all,

I'm trying to using the C++ API (APIs in inference_session.h and model.h). I built the Onnxruntime from source with the flag --build_shared_lib and I got the libonnxruntime.so.

Then I wrote a simple C++ program. It can be compiled, but undefined reference errors were raised during the linking stage.

Code:
```C++
#include "core/session/inference_session.h"
using namespace onnxruntime;
int main(){
  SessionOptions so;
  const SessionOptions& so_ref = so;
  InferenceSession session_object(so_ref);
  return 0;
}
```

The error during linking is:
```
undefined reference to `onnxruntime::InferenceSession::InferenceSession(onnxruntime::SessionOptions const&, onnxruntime::logging::LoggingManager*)'
undefined reference to `onnxruntime::InferenceSession::~InferenceSession()'
```

The compiling command is: (Those flags are from some flags.make generated by CMake when I built from source)
```
g++ -o test -std=gnu++14 -DONNX_ML -DEIGEN_MPL2_ONLY -DONNX_NAMESPACE=onnx -DONNX_USE_LITE_PROTO \
-DPLATFORM_POSIX -DUSE_EIGEN_FOR_BLAS -DUSE_MLAS -DUSE_OPENMP -D__ONNX_NO_DOC_STRINGS \
-I<INCLUDE_DIRS> -L<LINKING_DIRS> 
-lonnxruntime -lonnx_proto -lprotobuf
```
g++ version is 5.4.0

I would like to know whether the APIs in core/session/inference_session.h are packed into the shared library. Should I compile inference_session.cc with the test.cc together?

Many thanks!

**Comment by snnn** [comment]
We hide it intentionally. We won't export any C++ symbol in a shared library.

Please use the [C API](https://github.com/microsoft/onnxruntime/blob/master/docs/C_API.md) instead.
