### ISSUE TITLE
Tensor type mismatch. T !=N11onnxruntime17PrimitiveDataTypeIfEE error when inferencing with resnet50_v1.onnx in C++

### ISSUE THREAD

**Issue by abilashravi-ta** [microsoft/onnxruntime#11341]
**Description**
I built **onnxruntime** from source following [these](https://onnxruntime.ai/docs/build/inferencing.html#cpu) instructions.
I'm using `resnet50_v1.onnx` model, downloaded from [here](https://zenodo.org/record/2592612/files/resnet50_v1.onnx), to perform _inferencing_ in **C++**.
_Note: Download the model from the [github page](https://github.com/mlcommons/inference/tree/r0.5/v0.5/classification_and_detection) if direct download link given above is not working_

**System information**
- OS Platform and Distribution: **Ubuntu 20.04.3 LTS x86_64**
- ONNX Runtime installed from (source or binary): source (using the link mentioned above)
- G++ Compiler version: 9.3.0

**To Reproduce**
When I compile the following piece of code with 
_g++ -o run1 inference.cpp -I/usr/local/include/onnxruntime/core/session/ -lonnxruntime  \`pkg-config --cflags --libs opencv4\`_

```
// inference.cpp
#include<onnxruntime_cxx_api.h>

#include<opencv2/dnn/dnn.hpp>
#include<opencv2/imgcodecs.hpp>
#include<opencv2/imgproc.hpp>

#include<iostream>
#include<string>
#include<vector>
#include<numeric>

using namespace std;

template<class T>
T vectorProduct(vector<T>& v)
{
        return accumulate(v.begin(), v.end(), 1, multiplies<T>());
}

int main()
{
        string modelFilepath{"resnet50_v1.onnx"};
        Ort::Env env;
        Ort::SessionOptions sessionOptions;
        Ort::Session session(env, modelFilepath.c_str(), sessionOptions);
        Ort::AllocatorWithDefaultOptions allocator;

        string imageFilepath{"european-bee-eater-224X224.jpg"};
        cv::Mat imageBGR = cv::imread(imageFilepath);
        cv::Mat preprocessedImage, resizedImage;
        cv::dnn::blobFromImage(imageBGR, preprocessedImage);
        preprocessedImage.convertTo(resizedImage, CV_32F, 1.0);
        cout << "resizedImage.size: " << resizedImage.size << endl;  // resizedImage.size: 1 x 3 x 224 x 224

        const char* inputName = session.GetInputName(0, allocator);
        vector<int64_t> inputDims{1, 3, 224, 224};
        const char* outputName = session.GetOutputName(0, allocator);
        vector<int64_t> outputDims{1};

        size_t inputTensorSize = vectorProduct(inputDims);
        vector<const char*> inputNames{inputName};
        vector<Ort::Value> inputTensors;

        size_t outputTensorSize = vectorProduct(outputDims);
        vector<float> outputTensorValues(outputTensorSize);
        vector<const char*> outputNames{outputName};
        vector<Ort::Value> outputTensors;

        Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu(OrtAllocatorType::OrtArenaAllocator, OrtMemType::OrtMemTypeDefault);
        inputTensors.push_back(Ort::Value::CreateTensor<float>(memoryInfo, (float*)resizedImage.data, inputTensorSize, inputDims.data(), inputDims.size()));
        outputTensors.push_back(Ort::Value::CreateTensor<float>(memoryInfo, outputTensorValues.data(), outputTensorSize, outputDims.data(), outputDims.size()));

        session.Run(Ort::RunOptions{nullptr}, inputNames.data(), inputTensors.data(), 1, outputNames.data(), outputTensors.data(), 1);

        return 0;
}
```
I don't get any compilation error. 
But when I _execute_ `./run1`, after successful compilation, I get
![error_in_run1](https://user-images.githubusercontent.com/53215532/165039708-340e9057-1696-425b-b29c-2f41e5f93655.JPG)

Any suggestion would be helpful.!

**Comment by hariharans29** [comment]
This is interesting. The output of ArgMax is int64 and that enforce shouldn't have evaluated to false. I wonder if this triggering a bug in the optimizer suite (since the ArgMax feeds to Identity which feeds the graph output). Can you please try lowering the graph optimization level to ORT_DISABLE_ALL ?

**Comment by abilashravi-ta** [comment]
> This is interesting. The output of ArgMax is int64 and that enforce shouldn't have evaluated to false. I wonder if this triggering a bug in the optimizer suite (since the ArgMax feeds to Identity which feeds the graph output). Can you please try lowering the graph optimization level to ORT_DISABLE_ALL ?

I changed the 1st block of code in the `main` to following (keeping the remaining code as it is)
```
        string modelFilepath{"resnet50_v1.onnx"};
        Ort::Env env;
        Ort::SessionOptions sessionOptions;
        sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_DISABLE_ALL);
        Ort::Session session(env, modelFilepath.c_str(), sessionOptions);
        Ort::AllocatorWithDefaultOptions allocator;
```

After compiling, when I _run_ the _executable_, I get
![with_GO_disable](https://user-images.githubusercontent.com/53215532/166622608-2aec2ad7-b2c2-46bc-bbec-6518708e49e3.JPG)

**Comment by hariharans29** [comment]
So, your model has two outputs, but you are only providing one pre-allocated fetch to Session::Run() (`outputTensors` in your program has only one element). Once you fix this, the crash should go away (you can go back to the full optimization now). Please re-open if this doesn't fix it.

![image](https://user-images.githubusercontent.com/9969784/166827800-8257f13f-d6ca-4d73-92a2-2a380bbbef92.png)
