### ISSUE TITLE
Possible to run inference purely sequentially and not have onnx pin a thread

### ISSUE THREAD

**Issue by brettfazio** [microsoft/onnxruntime#11347]
If you want to run onnx cpu on a single thread using SEQUENTIAL - is it possible to do so without onnx pinning a new thread?

Presently I looked at the issue [here](https://github.com/microsoft/onnxruntime/issues/8313) and did the same solution of `options = ort.SessionOptions() options.intra_op_num_threads = 1 options.inter_op_num_threads = 1`  - but that pins a new thread?
Is it possible to just run inference in the same thread that onnx gets called from and have onnx pin *no* threads? In the case where one is doing external cpu pinning.

**Comment by snnn** [comment]
>  but that pins a new thread?

I don't think so. Did you see a new thread got started? If you set both of values to 1, I think ONNX Runtime should not create any thread pool.

**Comment by snnn** [comment]
The code is there:
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/util/thread_utils.cc#L18

If the size is 1, then the function directly returns.

**Comment by brettfazio** [comment]
Got it, thanks
