### ISSUE TITLE
OrtIoBinding GetBoundOutputValues to CPU from CUDA

### ISSUE THREAD

**Issue by seddonm1** [microsoft/onnxruntime#11342]
**Is your feature request related to a problem? Please describe.**
I have been using the C `OrtApi` with `OrtIoBinding` using the `BindOutputToDevice` method to execute a graph and leave the resulting data on an Nvidia CUDA device (via the TensorRT runtime).  I am trying to implement behavior similar to the Python API's `io_binding.copy_outputs_to_cpu()` method but am unclear the expected behavior of `GetBoundOutputValues`. The API so far seems very good but I am unclear how to complete the final step of copying the data back from the GPU to system memory.

**System information**
ONNX Runtime version 1.11.0 on Linux via C API

**Describe the solution you'd like**
Is there an example somewhere that demonstrates how, using the C API, tensors can be copied from the GPU based `OrtValue` to a system memory based `OrtValue`?

**Describe alternatives you've considered**
I have implemented the `GetBoundOutputNames` and `GetBoundOutputValues` methods but the documentation is not clear on how to perform this `io_binding.copy_outputs_to_cpu()` type behavior.

**Comment by yuslepukhin** [comment]
`cudaMemcpy*`

**Comment by seddonm1** [comment]
Thanks. I was hoping that I had missed something in the C API. Having gone through the code in more detail it seems I need to expose something like `CopyOutputsAcrossDevices` https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/framework/utils.cc#L617 through the C layer. I will see what I can pull together but would like your input as to what such a method would should be called/behave.

**Comment by yuslepukhin** [comment]
> Thanks. I was hoping that I had missed something in the C API. Having gone through the code in more detail it seems I need to expose something like `CopyOutputsAcrossDevices` 

We do not want to expose this. We are not in the business of providing APIs that are either vendor or device specific. You can simply  invoke cuda API for this.

**Comment by seddonm1** [comment]
Ok thank you I will try the CUDA API.

I am confused as to why you say `CopyOutputsAcrossDevices` is vendor or device specific. It uses the inbuilt `core/framework/data_transfer_manager` and the `IDataTransfer` interface to copy data back from any provider that implements it. This is what happens already when the `::Run` method ultimately executes `::ExecuteGraphImpl` to return results of the inferencing. Implementing it must be basically how the Python `.copy_outputs_to_cpu()` works?

**Comment by hariharans29** [comment]
It is a good initiative to have a parity betwen the C API and the Python API, but the `copy_outputs_to_cpu() in the Python API suite is mostly because it provides a way for Python users to bring data to the host and inspect its contents should they wish to do so.

For the C API users, exposing such an API is nice but nothing they wouldn't be able to write-up themselves using the CUDA RT APIs (for CUDA based OrtValues). As @yuslepukhin states, such an API would just be a thin wrapper over the cudaMemcpy* (for CUDA based OrtValues) APIs (something that the C API user can write-up themselves).

**Comment by seddonm1** [comment]
Thanks both.

Happy to close this issue but here is an example implementation of exposing the `CopyOutputsAcrossDevices` method for future visitors: https://github.com/microsoft/onnxruntime/compare/master...seddonm1:feature/CopyOutputsAcrossDevices. The benefit of exposing this is that this will work with _any_ provider rather than having to add implementation specific copy functions like you have suggested.
