### ISSUE TITLE
Integrate LGTM for code quality monitoring

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxruntime#11350]
LGTM is a code analysis platform for continuous code quality and security analysis. It is quite easy to set up and gives recommendations in the code review process. The company behind LGTM is part of Github (which is then part of MS)

https://lgtm.com/projects/g/microsoft/onnxruntime/alerts/?mode=list

**Comment by snnn** [comment]
LGTM, semmel and CodeQL, the same thing with different names. We already run semmel  for every commit in the master branch,  but due to some setup error(which I can't fix) it didn't have any finding reported. https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=204295&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=85cf3fbe-27e2-5670-dd77-39cbed2579a2 

It seems the LGTM github action works well. If you'd like to provide help, welcome to add it!

**Comment by justinchuby** [comment]
That's cool to know! With the app integrated I am hoping we can get real time feedback in our pr process (the current check doesn't seem to surface the info like unused imports etc.). I was trying to add it to our repo but it seems I lack the necessary access. I used https://github.com/marketplace/lgtm which took me to https://github.com/apps/lgtm-com/installations/new.

**Comment by snnn** [comment]
For any permission issue, please contact @faxu or @pranavsharma .

**Comment by justinchuby** [comment]
LGTM enabled

**Comment by jcwchen** [comment]
FYI: https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/ LGTM.com will be shut down in Dec. 2022 and they encourage to use GitHub code scanning instead. It seems there will be an automatic PR to help migration in Oct. according to this blog.

**Comment by justinchuby** [comment]
Thanks for the reminder! Sadly it seems like the code scanning feature will have less of the checks available than the current lgtm. Not sure if we can enable them manually.

**Comment by snnn** [comment]
Then we should stop using it.

**Comment by justinchuby** [comment]
I think Githubs code scanning feature will allow for a tighter feedback loop than the internal lgtm (because it doesn't comment). I think setting `queries: security-extended,security-and-quality` enables the quality checks we have in lgtm.
