### ISSUE TITLE
For CUDA Provider, ConcatFromSequence Op Used Inappropriate cudaMemcpyAsync Kind

### ISSUE THREAD

**Issue by Magnus1cheng** [microsoft/onnxruntime#11360]
**Describe the bug**
In ConcatFromSequence Operation, input and output tensors should have already copied into device memory before executed by using `GPUDataTransfer::CopyTensor.` So in ComputeInternal struct of this Op, use cudaMemcpyHostToDevice is inappropriate. 
```
      for (size_t idx_copy = 0, end = input_size / input_axis_pitch; idx_copy < end; ++idx_copy) {
        CUDA_RETURN_IF_ERROR(cudaMemcpyAsync(
            output + (initial_output_offset + cur_out_offset) * element_bytes,
            input + cur_in_offset * element_bytes, input_axis_pitch * element_bytes,
            cudaMemcpyHostToDevice, Stream()));
        cur_out_offset += p.output_axis_pitch;
        cur_in_offset += input_axis_pitch;
      }
```
Instead, should use cudaMemcpyDeviceToDevice  
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cuda/tensor/sequence_op.h#L152
This bug is not revealed could because of Unified Virtual Addressing (UVA) mechanism in latest CUDA version, so cuda driver only cares about the pointer value, not the kind of Memcpy.
Also, this is the only one operation using cudaMemcpyHostToDevice in   sequence_op.h, other opeations all use cudaMemcpyDeviceToDevice. So this might be a typo I guess.

**Urgency**
Urgent for some cuda-compatible systems (no UVA supported), but not urgent for official CUDA sdk. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux 7
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: v1.11.0 
- Python version: Python 3.6.8
- Visual Studio version (if applicable): 
- GCC/Compiler version (if compiling from source): gcc 9.3.1
- CUDA/cuDNN version: 10.2
- GPU model and memory: Self-designed GPU architecture, with 32GB GPU memory

**To Reproduce**
Can reproduce by UT tester.
./onnxruntime_test_all --gtest_filter=SequenceOpsTest.ConcatFromSequence_Stack_Axis0
gdb attach to program, set break point at cudaMemcpyAsync function, can identify the value  of src and dst if they are all device pointers till https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cuda/tensor/sequence_op.h#L152

**Comment by hariharans29** [comment]
CC: @RandySheriffH 

Thanks!

Since UVA is supported since CUDA 4 according to this: https://developer.nvidia.com/blog/unified-memory-in-cuda-6/, would it take a device running something lower for the test to break ?

**Comment by Magnus1cheng** [comment]
Any driver/SDK that supports CUDA but not UVA would trigger this bug. It probably looks fine on latest official CUDA, not sure for lower version. I used this on self-developed CUDA SDK, but driver does not support UVA for now, so triggered this bug.

**Comment by hariharans29** [comment]
Fix merged
