### ISSUE TITLE
When I build ios framework with "--use_coreml", can this framework run on iOS 11.0 ?

### ISSUE THREAD

**Issue by zepingWww** [microsoft/onnxruntime#11377]
**Describe**
I noticed that onnxruntime support coreml which requires iOS devices with iOS 13 or higher, but I can make clear to set "--apple_deploy_target 11.0 " and build this framework successfully. Does it means iOS devices with iOS 11.0 can execute it even if only  with CPU?

**System information**
- iOS version: 11.0
- ONNX Runtime version : 1.9.0
- ONNX Runtime supports coreml and the minimum version of the target platform is 11.0

**Questions**
Can iOS devices with iOS 11.0 deploy it? If it supports, which engine can be used? Or should it only rebuild without "--use_coreml"?

**Comment by edgchen1** [comment]
This page says that CoreML is available in iOS 11.0+.
https://developer.apple.com/documentation/coreml
Is that not the case?

**Comment by zepingWww** [comment]
> This page says that CoreML is available in iOS 11.0+. https://developer.apple.com/documentation/coreml Is that not the case?

Thanks, but this page says onnxruntime with CoreML requires iOS devices with iOS 13 or higher.
https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider
So I'm not sure whether it is available in iOS 11.0. If not, that means I have to build two libraries with cpu and coreml.

**Comment by zepingWww** [comment]
> Ah I see. Looks like the CoreML EP does indeed require at least iOS 13:
> 
> https://github.com/microsoft/onnxruntime/blob/4b875e354352ddc8e837800f429ae3c215fd6a7b/onnxruntime/core/providers/coreml/model/host_utils.h#L11-L12

Yeah, thanks. I'm sure that coreml is only supported on iOS13. But I think it could be played on iOS 11 with cpu, becaues the onnxruntime provides two headers - "cpu_provider_factory.h" and "coreml_provider_factory.h". There is no connection between onnxruntime and coreml, so I guess it may run with onnxruntime cpu backend on iOS 11.0. 

In my test, using onnxruntime cpu is a liitle slower than coreml on iOS simulator.
