### ISSUE TITLE
"Parameter 'b' set but not used" error on M1 mac 

### ISSUE THREAD

**Issue by ductranit** [microsoft/onnxruntime#11373]
**Describe the bug**
I'm not able to build the iOS project after import `onnxruntime-mobile-objc` from cocoapod. It says error `Parameter 'b' set but not used` in `SafeInt.hpp` file
And this issue only happen on my M1 mac, it works fine on another intel mac

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macos 12.3.1, iOS 15.4.1
- ONNX Runtime installed from (source or binary):  pod onnxruntime-mobile-objc 1.11.0
- ONNX Runtime version: 1.11.0
- Python version: 3.10.2

**To Reproduce**
- Create a new ios project
- Import latest `nnxruntime-mobile-objc` cocoapod
- The error happens when build project

**Expected behavior**
The error should not happen when import in M1 mac

**Screenshots**
<img width="1398" alt="Screen Shot 2022-04-27 at 09 07 28" src="https://user-images.githubusercontent.com/2063905/165425432-3637d3f6-6635-4e64-a06e-53689014d9a4.png">

**Comment by skottmckay** [comment]
I believe this is the issue: https://github.com/dcleblanc/SafeInt/issues/37

I'm not sure how the iOS dependencies work and what the best fix is. From the sound of it you can safely delete the CastThrow method as per this change: https://github.com/dcleblanc/SafeInt/commit/ff15c6ada150a5018c5ef2172401cb4529eac9c0

@edgchen1 Can we remove SafeInt.hpp from the pod? I didn't see any direct usage of SafeInt in the objective-c api. There's an include of SafeInt.hpp in ort_value.mm but no actual usage.

**Comment by ductranit** [comment]
@skottmckay thank you. I can build project after delete `CastThrow` in pod source file as your suggestion.
Hope the pod can be fixed in the next release

**Comment by edgchen1** [comment]
@skottmckay Thanks for finding the SafeInt issue.

> @edgchen1 Can we remove SafeInt.hpp from the pod? I didn't see any direct usage of SafeInt in the objective-c api. There's an include of SafeInt.hpp in ort_value.mm but no actual usage.

There is a usage of a SafeInt helper here: https://github.com/microsoft/onnxruntime/blob/88ff48910da946ebce8d695ea721e86ea9a13c7d/objectivec/src/ort_value.mm#L112

Trying to update ORT's SafeInt version: #11379
