### ISSUE TITLE
Could not find an implementation for the node Relu(1)

### ISSUE THREAD

**Issue by GuanLuo** [microsoft/onnxruntime#1138]
**Describe the bug**
Failed to load VGG-19 model from Azure AI Gallery ([link](https://gallery.azure.ai/Model/VGG-19)) with the message shown in title

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 0.4.0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
- CUDA/cuDNN version: CUDA_VERSION=10.1.163 / CUDNN_VERSION=7.6.0.64
- GPU model and memory: TITAN V

**To Reproduce**
Download the model from link above and try to load the model using C API (`OrtCreateSession`). The same error message is shown no matter if I was using CUDA provider or CPU provider.

**Expected behavior**
The model should be loaded successfully.

**Additional context**
Other models (tried [Resnet50](https://gallery.azure.ai/Model/ResNet-50-1-2-2) and [Inception](https://gallery.azure.ai/Model/Inception-v1-1-2-3)) from the gallery can be loaded properly.

**Comment by hariharans29** [comment]
Hi @GuanLuo,

The VGG-19 seems to be an opset 3 model -

![image](https://user-images.githubusercontent.com/9969784/58675661-28447f00-830a-11e9-9cf2-06fbc123b370.png)

ONNXRuntime supports Opset 7 and onwards only as documented [here](https://github.com/microsoft/onnxruntime/blob/master/docs/Versioning.md)

`ResNet50` and `Inception` models seem to be opset 7 models and hence load fine.

**Comment by GuanLuo** [comment]
@hariharans29 Oh I see, thanks for pointing it out. Before closing the issue, do you mind to tell me if there is a way to check the opset for a given model?

**Comment by hariharans29** [comment]
Sure. There are a couple of ways - 

1) Use Python APIs documented [here](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md) and print opset_import from ModelProto like this - 

import onnx
onnx_model = onnx.load("model.onnx")
print(onnx_model.opset_import)

2) Use [Netron](https://github.com/lutzroeder/netron) and use the highlighted button -

![image](https://user-images.githubusercontent.com/9969784/58676450-3516a200-830d-11e9-9342-b3fdd03e8fd9.png)

**Comment by hariharans29** [comment]
Closing this for now. Please re-open if there are any other concerns. Thanks.
