### ISSUE TITLE
Can API CreateTensorWithDataAsOrtValue take const void* as the input parameter type?

### ISSUE THREAD

**Issue by zhwa** [microsoft/onnxruntime#11406]
**Is your feature request related to a problem? Please describe.**

The second parameter ```p_data``` in API [CreateTensorWithDataAsOrtValue](https://tomwildenhain-microsoft.github.io/onnxruntime/docs/api/c/struct_ort_api.html) is ```void*```.  If a const data array is provided, the caller has to either cast away the constness, or create a copy of the array, before calling this API.

**Describe the solution you'd like**

I wonder if a second API that's similar to CreateTensorWithDataAsOrtValue can be added. The new API could take ```const void*``` as the type of ```p_data```.

Or, if a breaking change of this API to use ```const void*``` is acceptable. Based on the doc: *```p_data``` is owned by caller. ReleaseValue won't release ```p_data```.* Making it a ```const void*``` seems to be fine.

**Comment by RyanUnderhill** [comment]
This won't quite make sense, as this is to create a tensor with a user supplied buffer. If the resulting OrtValue is used as an output the buffer cannot be const. So putting 'const' here will be misleading.

For an input only buffer, it's logically const, but the user of the API does need to cast away constness.

**Comment by hariharans29** [comment]
@RyaUnderhill - Yeah, I was forgetting the scenario where-in an OrtValue created with a user-provided buffer can be passed in as a fetch to Session::Run().

**Comment by hariharans29** [comment]
Closing this for now. Please re-open if you have further questions.
