### ISSUE TITLE
SIGSEGV when convert_version

### ISSUE THREAD

**Issue by olegzhos** [microsoft/onnxruntime#11410]
Hello everybody! When I try to convert a opset version of any onnx model to:
14-16 (when onnx==1.8 is installed),
15-16 (when onnx==1.9 is installed),
16 (when onnx==1.10 is installed)
with convert_version that I import from onnx.onnx_cpp2py_export.version_converter, I have the next error: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV). But I don't face this error if I convert to a target version less 14, 15 and 16 respectively. I was installing onnx with pip install onnx==... and I have installed ort with pip install onnxruntime==1.11.1 for all these cases.
Can you help me please or ask the information I should provide to resolve this error?

**Comment by hariharans29** [comment]
Can you please ask this question in the ONNX repo - https://github.com/onnx/onnx ?

**Comment by hariharans29** [comment]
Closing this for now as this is not a question related to ORT usage. Please re-open if you have any further questions.
