### ISSUE TITLE
Load/Inference on GPU (C, C++)

### ISSUE THREAD

**Issue by adaber** [microsoft/onnxruntime#1142]
Hi everyone,

What DLLs (besides GPU onnxruntime.dll ) are required to load and run a model on GPU (Visual Studio 2017, Windows 10) ?

Also, it seems that I would need to include cuda_provider_factory.h in my project and use the OrtSessionOptionsAppendExecutionProvider_CUDA method to add the CUDA execution provider.

Any help would be very appreciated. Thanks!

**Comment by faxu** [comment]
Please see: https://github.com/microsoft/onnxruntime#system-requirements
The official GPU builds require the CUDA 9.1 and cuDNN 7.1 runtime libraries being installed in the system.

CUDA binaries are published here: https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.gpu
If you use this, you do not need to register any execution provider. 

To build from source, instructions are here: https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#windows-cuda-build

**Comment by snnn** [comment]
>　Also, it seems that I would need to include cuda_provider_factory.h in my project and use the OrtSessionOptionsAppendExecutionProvider_CUDA method to add the CUDA execution provider.

Yes.

**Comment by adaber** [comment]
Thank you for answering my question, faxu and snnn.

I always try to manually include the necessary header, library and dll files in my C++ projects initially to know exactly what files I need to be able to compile them.

I've already included the ONNXRuntime GPU binaries in my project manually and that's fine.

I am not trying to build ONNXRuntime from source right now and would try to avoid installing the whole CUDA computing platform.

For example, the CNTK GPU NuGet package already contains the necessary CUDA and cuDNN dlls (nvml, cusparse64_, cudart64_, curand64_, cublas64_ and cudnn64_ ) that need to be placed in your CNTK executable's folder.

I have just started using/testing ONNXRuntime and will definitely look into this myself but was hoping someone had already tried it.

Thanks.

**Comment by torkeldanielsson** [comment]
Thank you for the OrtSessionOptionsAppendExecutionProvider_CUDA tip! That was what I was missing to get CUDA inference running using the c api.

Dont't you think this info should be included in the "C_API.md" file that is in the zip file for the GPU distributable? I followed those instruction and apart from this everything was really easy to get up and running! Let me know if you want me to make a PR with this info added :)

**Comment by adaber** [comment]
Glad you got it working, torkeldanielsson :)

Also, I'd like to report that I got "GPU model loading and inference" working without installing the whole CUDA 9.1 package. The currently required NVIDIA dlls to run the GPU version of "C_Api_Sample" are cudnn64_7.dll and cudart64_91.dll on my laptop.
I believe I hadn't installed any NVIDIA CUDA package in the past and shouldn't have any other dll files, from the list I mentioned in my previous post, stored on my computer. I believe that nvml.dll gets installed along with the NVIDIA display driver, though.

You can extract cudnn64_7.dll and cudart64_91.dll from the temp folder that the CUDA installer unpacks the installation files to at the start of the installation process.

I also had to add my app in the NVIDIA "Manage 3D Settings->Program Settings" and set the preferred graphics processor to HIGH-performance NVIDIA processor since I have an integrated graphics card besides the NVIDIA one.

**Comment by snnn** [comment]
> Let me know if you want me to make a PR with this info added :)

@torkeldanielsson  That would be great, thank you!
