### ISSUE TITLE
How to use more gpu to parallel compute?

### ISSUE THREAD

**Issue by PingYufeng** [microsoft/onnxruntime#11435]
**Describe the bug**
Does it mean using more gpu to parallel execution in java with 'CUDA Execution Provider' when OrtSession.SessionOptions.ExecutionMode sets 'PARALLEL' ? How to use parallel execution mode on CUDA Execution Provider, while executing onnxruntime session in parallel ?
Another, if I create two sessions, could they use the same gpu when they run at the same time？

**Urgency**
none.

**System information**
- ONNX Runtime version: 1.11.0  in java

**Screenshots**

**Comment by pranavsharma** [comment]
1. Parallel execution mode has nothing to do with using multiple gpus in parallel. Parallel execution mode is deprecated.
2. For now, you can create 2 sessions each tied to a different gpu device id. 
Can you elaborate on your use case?

**Comment by PingYufeng** [comment]
> 

Thanks, I understand.
