### ISSUE TITLE
cannot import name 'quantize_qat' from 'onnxruntime.quantization'

### ISSUE THREAD

**Issue by MrRace** [microsoft/onnxruntime#11434]
When `from onnxruntime.quantization import quantize_qat, QuantType` come errors:
```
ImportError: cannot import name 'quantize_qat' from 'onnxruntime.quantization'
```
onnxruntime-gpu Version: 1.11.1

**Comment by baijumeswani** [comment]
@MrRace I was not able to find `quantize_qat` in `onnxruntime` repo. Were you expecting it to be there?

**Comment by shcchen** [comment]
quantize_qat cannot be found in recent versions, but in an earlier version like v1.5.1
See https://github.com/microsoft/onnxruntime/blob/rel-1.5.1/onnxruntime/python/tools/quantization/quantize.py#L248

**Comment by baijumeswani** [comment]
I found this pull request https://github.com/microsoft/onnxruntime/pull/10549. @yufenglee can provide more details on this.

**Comment by yufenglee** [comment]
For a QAT model in ONNX format, you don't need to quantize it anymore. ORT can run it directly with quantized ops.

**Comment by yan12125** [comment]
Hi, could you update docs at https://onnxruntime.ai/docs/performance/quantization.html#quantization-api ? That page still mentions `quantize_qat` as one of three quantization APIs.
