### ISSUE TITLE
Is the OrtEnvironment  only one in global?

### ISSUE THREAD

**Issue by PingYufeng** [microsoft/onnxruntime#11433]
**Describe the bug**
I want to ask a question that the OrtEnvironment instance is only one in global? When I got different OrtEnvironment instance, it was the same.

**Urgency**
none.

**System information**
- ONNX Runtime version: 1.11.0

**Screenshots**
![image](https://user-images.githubusercontent.com/37933036/166627897-961f459f-cda2-4f53-822c-e2e82993d9f1.png)

**Comment by pranavsharma** [comment]
Yes, ort environment is a singleton.

**Comment by PingYufeng** [comment]
> Yes, ort environment is a singleton.

Thanks, I get it.
