### ISSUE TITLE
Add  a C/C++ header with full semantic version of the library

### ISSUE THREAD

**Issue by dpar39** [microsoft/onnxruntime#11444]
**Is your feature request related to a problem? Please describe.**
I see that we can retrieve `ORT_API_VERSION` number from `onnxruntime_c_api.h` but nowhere on the install headers I can find the full semantic version of the library being built. Would it be possible to add it?

**System information**
- ONNX Runtime version (you are using):  11.1.0

**Describe the solution you'd like**
Perhaps something like this?
```
constexpr char ORT_SEMVER[] = "1.11.0";
```

**Describe alternatives you've considered**
I currently have to edit the file after being installed via a Python script.

**Additional context**
-

**Comment by baijumeswani** [comment]
Would you be able to share your purpose of needing such a version number through C++ API?
`onnxruntime_c_api.h` has a `ORT_API_VERSION` that can be used.

**Comment by RyanUnderhill** [comment]
I think what you want is this API: GetVersionString()

See here: https://github.com/microsoft/onnxruntime/blob/8d69b9398baf95e0c0781dd96e9fbb7f70294f4f/include/onnxruntime/core/session/onnxruntime_c_api.h#L549

**Comment by dpar39** [comment]
Yes! That's exactly what I wanted. I tried searching for it in the source code but never find it. Thanks!
