### ISSUE TITLE
onnxruntime gpu inference benchmarking

### ISSUE THREAD

**Issue by bchinnari** [microsoft/onnxruntime#11449]
Hi,

I have an onnx model and I am measuring the model inference time, using onnxruntime,  using cuda execution provider.
I am using mini batch of 128 utts, feat dim is 80 and seq length is also 128
batch size =[ 128, 80, 128]
I am running the experiment three times.
In each run, I am using 20 minibatches as warmup and measuring the time as average over next 80 minibatches

`
import time
import numpy as np
import onnxruntime as ort

onnx_mdl = '/path/to/the/model'

opts = ort.SessionOptions() 
opts.intra_op_num_threads = 1                                                                      
opts.inter_op_num_threads = 1
opts.execution_mode = ort.ExecutionMode.ORT_SEQUENTIAL
opts.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_BASIC                        

deviceID=0
batch = 128                                                                                        
seq = 128                                                                                          

runs=3                                                                                             
mB=100

providers = [
    ('CUDAExecutionProvider', {                                                                    
        'device_id': deviceID,                                                                     
    })                                                                                             
]

avg = 0                     

for run in range(runs):  

    ## creating a new session for each run
    session = ort.InferenceSession(onnx_mdl, sess_options=opts,  providers=providers)              
    io_binding = session.io_binding()

    for mini in range(mB):  ## 100 mini Batches per run

        X = np.random.randn(batch,80, seq).astype('f')
        stime = time.time()  ## timing the start here itsel because next step (copy i/p to cuda) is considered as running on gpu 
                                                                  
        X_ortvalue = ort.OrtValue.ortvalue_from_numpy(X,'cuda',deviceID) 

        io_binding.bind_input(name='audio_signal', device_type=X_ortvalue.device_name(), device_id=deviceID, element_type=np.float32, shape=X_ortvalue.shape(), buffer_ptr=X_ortvalue.data_ptr())     
        io_binding.bind_output('logprobs')

        session.run_with_iobinding(io_binding)  
        dur = time.time() - stime
        if mini >= 20:    ### first 20 mini batches taken as warmup
            avg = avg+ dur
    del session ##deleting the session after the run

avg = avg/(runs*(mB-20))

gpuAudio = avg*100/(batch*seq)

print ("cuda EP - batch :{}, SeqLength:{} , avg time taken per minibatch:  {:.5f} seconds".format( batch, seq, gpuAudio))

print ("cuda EP - batch :{}, SeqLength:{} , gpu/Audio:  {:.5f} seconds".format( batch, seq, gpuAudio))
`

can we measure the time using time.time() ? I read in some issues like [https://discuss.pytorch.org/t/how-to-measure-time-in-pytorch/26964/2 
](url) wherein torch.cuda.Event() .record() and torch.cuda.synchronize() is used after the session run. 
Kindly help. me to figure out the best way to measure average time taken for a mini batch using gpu.

**Comment by tianleiwu** [comment]
Yes, you can use time.time() since run_with_iobinding has synchronized cuda. Once it is done, the output is ready.

**Comment by baijumeswani** [comment]
closing this issue. @bchinnari, if you feel you need more details, please respond to this thread or open the issue again.

**Comment by hariharans29** [comment]
Make your io_binding.bind_output('logprobs') -> io_binding.bind_output('logprobs', 'cuda') and start your timer AFTER X_ortvalue = ort.OrtValue.ortvalue_from_numpy(X,'cuda',deviceID) because in PyTorch, you usually would take the data to the device first before calling Run(). And as Tianlei mentioned, our Run() is synchronous and doesn't need a sync like in PyTorch.

**Comment by bchinnari** [comment]
Thank you @tianleiwu @hariharans29  for the quick response. 
I have few questions
1. The first minibatch only in every run is taking lot of time compared to the subsequent minibatches. What are the reasons for this ?
2. I am using Cuda EP. to bind the input , there is a function called bind_input() which copies the input from CPU to GPU. Does bind_cpu_input() also copies from CPU to GPU?
3. bind_output('logprobs','cuda')--> stores the output on GPU. what does bind_output('logprobs') do? output is stored on GPU and then transferred to CPU ?

**Comment by hariharans29** [comment]
1. The very first Run() for a session does some "one-time things". It is hard to list to everything - but the pre-dominant load comes from cuda memory allocations for the internal memory pool. Please ignore it in the benchmarking. Typically, it is normal to perform 2-3 runs of warm-ups before the actual "model serving" starts.

2. Yes, bind_cpu_input() expects cpu input whereas bind_input() is generic - it can also take input on cuda (and leave it on cuda if it is ultimately consumed there)

3. Yes

**Comment by bchinnari** [comment]
I have an onnx model,  I can run on CPU as follows
 `session.run(None, {'audio_signal' : X1, 'length': X2} )  `
THough X2, X1 are related like this `X2 = np.array( [ X1.shape[2] ] )` , the session runs when we give both X1, X2 like above

How can I do this with GPU ?
------------------------
`
                X1 = np.random.randn(batch,80, seq).astype('f')                           
                X1_ortvalue = ort.OrtValue.ortvalue_from_numpy(X,'cuda',DID)
                io_binding.bind_input(name='audio_signal', device_type=X1_ortvalue.device_name(), device_id=DID, element_type=np.float32, shape=X1_ortvalue.shape(), buffer_ptr=X1_ortvalue.data_ptr())                                                                       
                io_binding.bind_output('logprobs')  
                
                session.run_with_iobinding(io_binding)
`
------------
The above snippet is not working and is giving the following message
---------------
RuntimeError: Error in execution: Non-zero status code returned while running Cast node. Name:'Cast_1' Status Message: /n/w1-bchinnari/onnxruntime/include/onnxruntime/core/framework/op_kernel_context.h:40 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: length
-----------------

**Comment by bchinnari** [comment]
Never mind.  I got the answer.
I just have to  bind_input() two times for the two expected inputs.
But , is there a need to call synchronizedboundinputs() ?
