### ISSUE TITLE
JAVA API does not handle exceptions correctly - causing crash or potential memory leak

### ISSUE THREAD

**Issue by fs-eire** [microsoft/onnxruntime#11451]
**Describe the bug**
I found this bug when I try to create a React Native app targeting Android. The current Java API does not handle exceptions correctly: If an input tensor with wrong shape is passed to `OrtRun()`, the design behavior is to throw an exception of type `OrtException`(Java), but instead it crashes silently.

After debugging into the JNI implementation, I found this code line:
https://github.com/microsoft/onnxruntime/blob/d2ae0f49b2cd7824613c27df7baa0dfa9559e1db/java/src/main/native/ai_onnxruntime_OrtSession.c#L288

This is the actual call to C-API of OrtRun(). The call is wrapped in a helper function `checkOrtStatus()`. And this is where the problem occurred.

Looking at the implementation of `checkOrtStatus()`, it calls `throwOrtException()`:

https://github.com/microsoft/onnxruntime/blob/d2ae0f49b2cd7824613c27df7baa0dfa9559e1db/java/src/main/native/OrtJniUtil.c#L1032-L1045

https://github.com/microsoft/onnxruntime/blob/d2ae0f49b2cd7824613c27df7baa0dfa9559e1db/java/src/main/native/OrtJniUtil.c#L990-L999

Here is the explanation of the problem:

The `env->Throw()` sets status of Java environment, but does not return or throw in C/C++ context. It always continue to execute the rest code in the function. This causes the behavior of function `checkOrtStatus()` behaves differently to macros like `ORT_ENFORCE()` or `ORT_API_RETURN_IF_ERROR`, which guarantees further code will not be executed (via either return or throw C++ exceptions/abort()).

Line 300 will have undefined behavior if the `OrtRun()` fails.
https://github.com/microsoft/onnxruntime/blob/d2ae0f49b2cd7824613c27df7baa0dfa9559e1db/java/src/main/native/ai_onnxruntime_OrtSession.c#L288-L304

I have a workaround to mitigate this issue for my usage. However this is not a complete fix for this issue. A complete fix should carefully check after every ORT API calls and make sure errors being handled correctly.

@craigacp

**Urgency**
If users don't generate any non-zero OrtStatus in all the API calls to ORT, they will not be impacted. Otherwise there is risk for potential memory leak or crash.

**System information**
- OS Platform and Distribution: Windows 10 21H2 (19044.1645)
- Java: 11

**To Reproduce**
- This branch contains the code to reproduce the issue: https://github.com/fs-eire/ort-rn-hello-world/tree/fs-eire/wrong-dimension

**Comment by Craigacp** [comment]
Yep, the JNI code needs rewriting and it's on my to-do list for the next release.
