### ISSUE TITLE
Update docs for CUDA Execution Provider

### ISSUE THREAD

**Issue by EmanuelAlogna** [microsoft/onnxruntime#11464]
Currently, the docs for CUDA Execution Provider does not contain requirements information for ONNX Runtime version 1.11. 
In `https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html ` is specified which CUDA version should be used with ONNX Runtime 1.11 but I would like also to know which is the correct version of cuDNN (both for Linux and Windows).

---
#### Document Details
* Title: CUDA
* Page: [https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html)
* Page Source: CUDA-ExecutionProvider.md

**Comment by natke** [comment]
Fixed by linked PR #11788
