### ISSUE TITLE
Wish to use "convert_onnx_models_to_ort.py" and requesting guide

### ISSUE THREAD

**Issue by yonggunlee** [microsoft/onnxruntime#11519]
Hello,

I wish to convert *.onnx model into *.ort file as onnxruntime required.
I was trying to check the webpage of "https://onnxruntime.ai/docs/tutorials/mobile/model-conversion.html" for model conversion test, but the link was down or unavailable. 

Is there some way I can convert my *.onnx or *.pth model file simply into *.ort?
I was trying to find some guides, but there isn't any available.

**Comment by edgchen1** [comment]
Try: https://onnxruntime.ai/docs/reference/ort-format-models.html#convert-onnx-models-to-ort-format

That looks like an old link, where did you find it? It might need to be updated.

Conversion from .onnx to .ort is supported (but probably not from .pth).

**Comment by aseprohman** [comment]
Hello, 

is it possible to load & inference ORT model in PC or laptop ? not in mobile device ? 
I need to check model accuracy when converting into mobile format

regards

**Comment by edgchen1** [comment]
> Hello,
> 
> is it possible to load & inference ORT model in PC or laptop ? not in mobile device ? I need to check model accuracy when converting into mobile format
> 
> regards

@aseprohman Yes, loading and running an ORT format model is possible in a normal ORT build too.

**Comment by yonggunlee** [comment]
Is there specific required input and output format for this *.ort model
file? My model takes [batch size, img channel, img h, img w] I wonder if
there is some required format for it.

**Comment by edgchen1** [comment]
> Is there specific required input and output format for this *.ort model file? My model takes [batch size, img channel, img h, img w] I wonder if there is some required format for it.

The ORT format model should have the same inputs and outputs as the original ONNX model. You can call [Run()](https://onnxruntime.ai/docs/api/c/struct_ort_api.html#ad8b12cad4160d43da92f49191cd91895) on the session the same way for either type of model.

**Comment by lamarvwoods** [comment]
How do we know what the inputs to a model are supposed to be?

**Comment by lamarvwoods** [comment]
Thanks for the suggestion! It helped me get closer to solving my issue. Once is used Netron to get the inputs and image name fixed, I ran into another issue because I'm swapping from using the ORT file in the example to an ORT that I created. 
Since you already helped with this issue. I went ahead and created a different github issue here: https://github.com/microsoft/onnxruntime/issues/11541
Thanks again!

**Comment by edgchen1** [comment]
The link from https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/object_detection/ios/README.md has been fixed.
Closing this issue for now. If you have particular questions about the info at https://onnxruntime.ai/docs/reference/ort-format-models.html#convert-onnx-models-to-ort-format feel free to re-open or create a new issue.
