### ISSUE TITLE
Can't run a model on ARM64 device

### ISSUE THREAD

**Issue by hongyangdengms** [microsoft/onnxruntime#11515]
**Describe the bug**
When running DNN model on ARM64 devices with ARM64 native build, the program crashes without any error message when running the session. The same code built for x64 platform can run on the same device without issue.

The ARM64 onnxruntime.dll version is 1.10.21.1206

There is no error message. The program just silently exited when calling Ort::session.run().

**Urgency**
Not urgent.

**System information**
- Windows 11
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:
- 
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Run the code.

**Expected behavior**
Program finishes with correct outputs

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by pranavsharma** [comment]
> There is no error message. The program just silently exited when calling Ort::session.run().
As discussed, since we don't have any Windows ARM64 devices can you turn on verbose logging and see what was printed last? Also, it'll help if you can run it in a debugger and attach the output here.

**Comment by hongyangdengms** [comment]
Please see attached verbose output.

I don't think I can run with debugger since Visual Studio doesn't run on ARM64.

Thanks,

Hongyang
________________________________

**Comment by hongyangdengms** [comment]
It turns out the root cause is that we use a local buffer (on stack) to prepare the data for the model input. The default stack size seems not large enough to hold the buffer. Changing the buffer as static resolved this issue. Closed it for now.
