### ISSUE TITLE
ARM64 build need manually add onnxruntime.lb and it's path to the VC project file

### ISSUE THREAD

**Issue by hongyangdengms** [microsoft/onnxruntime#11512]
**Describe the bug**
When using Nuget package to get the onnxruntime 1.10, ARM64 builds failed on VS unless manually add the "onnxruntime.lib" as additional dependency in the vcproj file. 

error message: 
Error	LNK2001	unresolved external symbol OrtGetApiBase	

x64 builds don't have this issue.

**Urgency**
Not urgent

**To Reproduce**
- Add onnxruntime through the Nuget package manager on Visual Studio
- Compile the code for ARM64 platform

**Expected behavior**
Build success

**Comment by hariharans29** [comment]
I think the props file needs support for ARM/ARM64 - https://github.com/microsoft/onnxruntime/blob/master/csharp/src/Microsoft.ML.OnnxRuntime/targets/netstandard/props.xml#L15

**Comment by pranavsharma** [comment]
FWIW the relevant bits are already present in the Nuget. May be the folder naming convention is different for ARM64.

<img width="224" alt="image" src="https://user-images.githubusercontent.com/2732907/168343200-cf224cd3-c501-4f6f-b68c-0abad2fc4146.png">

**Comment by hariharans29** [comment]
It is different. It is win-arm* as opposed to win-x64/win-x86 and there needs to be entries in the props file to add the onnxruntime.lib dependency (exactly like line 15 in the props file).

**Comment by pranavsharma** [comment]
Both win-arm* have the appropriate libs. See above screenshot and this one.
<img width="238" alt="image" src="https://user-images.githubusercontent.com/2732907/168373537-4348464f-2142-42ca-8171-bba3941dfe34.png">

**Comment by hariharans29** [comment]
It certainly is :) That is not the problem here. The problem is that the props file is lacking support for this. Please open the link that I shared above and it will instantly be clear what line is missing for the arm binaries.

**Comment by hongyangdengms** [comment]
So what's the plan to add the dependencies to the props file to fix this issue? Another thing missing is for ARM64 build, the correct dll files (onnxruntime.dll and onnxruntime_providers_shared.dll) are not copied to the output directory.

**Comment by hongyangdengms** [comment]
Verified with the test  package 

https://artprodcus3.artifacts.visualstudio.com/Abc038106-a83b-4dab-9dd3-5a41bc58f34c/530acbc4-21bc-487d-8cd8-348ff451d2ff/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL2FpaW5mcmEvcHJvamVjdElkLzUzMGFjYmM0LTIxYmMtNDg3ZC04Y2Q4LTM0OGZmNDUxZDJmZi9idWlsZElkLzIxMjcxMy9hcnRpZmFjdE5hbWUvZHJvcC1zaWduZWQtbnVnZXQtQ1BV0/content?format=file&subPath=%2FMicrosoft.ML.OnnxRuntime.1.12.0-dev-20220611-0215-0869f4f4e.nupkg 

fix the issue. The DLLs are copied and the onnxruntime.lib doesn't need to be specified as dependency in the VS project file.
