### ISSUE TITLE
How to use the onnxruntime API to request cuda memory 

### ISSUE THREAD

**Issue by scuizhibin** [microsoft/onnxruntime#11528]
Ort::AllocatorWithDefaultOptions allocator_;
 allocator_ = Ort::AllocatorWithDefaultOptions(); 
float *columns = (float *)allocator_.Alloc(sizeof(float) * column_len);

This is the cpu memory request. My question is how to allocate memory on gpu accordingly? Is there a corresponding onnxruntime-API?

**Comment by yuslepukhin** [comment]
`Ort::MemoryInfo cuda_mem_info("Cuda", OrtDeviceAllocator, 0, OrtMemTypeDefault);`
`Ort::Allocator cuda_allocator(mem_info);`

The above allocates memory from ORT inference session internal allocator.
However, you can use CUDA API directly such as `cudaMalloc`.

**Comment by scuizhibin** [comment]
thanks&nbsp;a&nbsp;lot


---Original---
From: &quot;Dmitri ***@***.***&gt;
Date: Wed, May 18, 2022 05:14 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [microsoft/onnxruntime] How to use the onnxruntime API to requestcuda memory  (Issue #11528)




 
Ort::MemoryInfo cuda_mem_info("Cuda", OrtDeviceAllocator, 0, OrtMemTypeDefault);
 Ort::Allocator cuda_allocator(mem_info);
 
The above allocates memory from ORT inference session internal allocator.
 However, you can use CUDA API directly such as cudaMalloc.
 
&mdash;
