### ISSUE TITLE
CUDA/CPU EP session creation fails with Could not find an implementation for QuantizeLinear(13)

### ISSUE THREAD

**Issue by PeterZhizhin** [microsoft/onnxruntime#11537]
**Describe the bug**
I am trying to load a quantized model in ONNX Runtime, loading fails with the following error:
```
$ python3.8 test_crash_2.py transformer_encoder_layer_shape_inferred_quantized_fails_to_load.onnx 
Trying CPU without optimizations...
CPU without optimizations success!
Trying CPU with basic optimizations...
Traceback (most recent call last):
  File "test_crash_2.py", line 34, in <module>
    main()
  File "test_crash_2.py", line 30, in main
    session = rt.InferenceSession(args.model_path, session_options, ['CPUExecutionProvider'])
  File "/home/zhizhin/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/zhizhin/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 381, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for QuantizeLinear(13) node with name 'x_DequantizeLinear_post_dq_post_dq_post_dq_post_dq_post_dq_post_dq_post_dq_post_dq_post_dq_post_dq_q'
```

The model loads fine without optimizations, but the `ORT_ENABLE_BASIC` optimization level crashes on both CPU and CUDA EP with the same error.

Here is the model checkpoint: https://drive.google.com/file/d/1mllFVs_u4zNLBPhtSpllEozmOQ9era_7/view?usp=sharing
`test_crash_2.py` is provided below.

The model has been quantized like this:
```
onnxruntime.quantization.quantize_static(model_path, quantized_model_path, calibration_data_reader, op_types_to_quantize=['MatMul', 'Add'])
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): pip onnxruntime-gpu
- ONNX Runtime version: 1.11.1
- Python version: 3.8
- CUDA/cuDNN version: 11.4
- GPU model and memory: A100 40Gb

**To Reproduce**
1. Download the model: https://drive.google.com/file/d/1mllFVs_u4zNLBPhtSpllEozmOQ9era_7/view?usp=sharing
2. Run `python3 test_crash_2.py <path to the downloaded model file>`:
```python
import onnxruntime as rt
import argparse
import os


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('model_path', default='transformer_encoder_layer_shape_inferred_quantized.onnx')
    return parser.parse_args()


def main():
    args = parse_args()
    session_options = rt.SessionOptions()
    session_options.graph_optimization_level = rt.GraphOptimizationLevel.ORT_DISABLE_ALL

    print('Trying CPU without optimizations...')
    session = rt.InferenceSession(args.model_path, session_options, ['CPUExecutionProvider'])
    print('CPU without optimizations success!')

    print('Trying CPU with basic optimizations...')
    session_options.graph_optimization_level = rt.GraphOptimizationLevel.ORT_ENABLE_BASIC
    session = rt.InferenceSession(args.model_path, session_options, ['CPUExecutionProvider'])
    print('CPU with basic optimizations success!')

if __name__ == "__main__":
    main()
```
 
**Expected behavior**
`CPU with basic optimizations success!` is printed, no exception occurs. Changing `CPUExecutionProvider` to `CUDAExecutionProvider` also works.

**Additional context**
I am trying a layer of a transformer network in my neural network.

**Comment by PeterZhizhin** [comment]
Interestingly enough, the problem doesn't occur with a single transformer layer, only when I have two layers.

**Comment by huismiling** [comment]
I met this error.
have any update?
There is not any node named "x_DequantizeLinear_post_dq_post_dq_post_dq_post_dq_post_dq_post_dq_post_dq_post_dq_post_dq_post_dq_q" in onnx graph !

**Comment by PeterZhizhin** [comment]
I have not found any solution, hopefully someone from the team responds.
