### ISSUE TITLE
Run part of the graph

### ISSUE THREAD

**Issue by lsy323** [microsoft/onnxruntime#1153]
Hi Ort team,

I'm playing around the ORT and it is a great backend for ONNX models. Here I have a question regarding running part of the network in ORT.

I'd like to know is it possible to run part of the ONNX model?

For example, we network is: input->fc1->fc2->fc3->fc4->output. Is it possible to only run fc2->fc3 in the network? (manually load input for fc2, instead of using the output of fc1)
One use case could be that a mask is applied to the activation of each layer. Basically, we get the output of the (L-1)^th layer and apply the mask, then feed it to the L^th layer. (Suppose that the mask is not part of the model, so it is not exported in the ONNX model ^ ^)

Thanks a lot!

**Comment by snnn** [comment]
Thanks for interesting in onnxruntime. I believe this issue is duplicated with #852 .

**Comment by lsy323** [comment]
Hi snnn,

Thanks for your reply. I've done some experiments by add output to the protobuf object to dump the output of each layer. 

However, I wonder is it possible to load input for a specific layer. Like in the example above, we start running the network from the intermediate layer, which needs to load the input for the intermediate layer. (in that case, we only feed the input of fc2 instead of the original input for fc1, as is shown in the example above)

Many thanks!~

**Comment by snnn** [comment]
Sorry, I'm not aware of any existing tool for your requirement. 
For me, it's not an issue as I always got the model from a converter, or another framework. I usually modify the graph at the source(e.g. Tensorflow), For example, If you need input/output of the intermediate level, the tf2onnx converter can do this for you.  I would treat onnx model as compiled binary, usually people want to read or modify the source code of the binary, not operating the binaries directly. However, if you want, you can.

**Comment by snnn** [comment]
See: https://github.com/onnx/onnx/issues/2078

**Comment by lsy323** [comment]
Hi @snnn,

Thanks for the reply. I'm modifying the model structure using ONNX API to achieve that.
