### ISSUE TITLE
Undefined symbols for architecture arm64:   "_OrtGetApiBase" ... ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by HULEIYI** [microsoft/onnxruntime#11545]
**Describe the bug**
I just want to run onnx file with C++, and I can't #include <onnxruntime_cxx_api.h> successfully.
The ERROR is:
Undefined symbols for architecture arm64:

  "_OrtGetApiBase", referenced from:
      ___cxx_global_var_init in main.cpp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Urgency**
If it's possible, it;s better to solve it quickly, 'cause I have a ddl next week. PLEASE!

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS Montery with Apple M1 Pro.
- ONNX Runtime installed from (source or binary): onnxruntime-osx-arm64-1.11.1.tgz and onnxruntime-osx-arm64-1.10.0.tgz
- ONNX Runtime version: onnxruntime-osx-arm64-1.11.1  and onnxruntime-osx-arm64-1.10.0 (I tried both of them.)
- Python version: None
- Visual Studio version (if applicable): I use CLion.
- GCC/Compiler version (if compiling from source): None.
- CUDA/cuDNN version: None.
- GPU model and memory: None.

**To Reproduce**
Just have a main.cpp with #include and #include<onnxruntime_cxx_api.h> with the main printing "hello word".
the makefile or cmakelists include_directories to the onnxrutime installation path as well as folders within such as include and lib.

**Expected behavior**
Only want to use onnxruntime successfully to deploy the yolov5.onnx.

**Screenshots**
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/66046309/168732397-d380f2a9-4626-4aa4-b115-17cabe1fcf33.png">

**Additional context**
- main.cpp is:
#include <iostream>

#include <opencv2/core.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/opencv.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc_c.h>
#include <opencv2/dnn.hpp>

#include <onnxruntime_cxx_api.h>

#include <assert.h>
#include <vector>
#include <fstream>

using namespace cv;
using namespace std;
// using namespace Ort;
using namespace cv::dnn;

int main() {
    cout << "Exe Done!" << endl;
    return 0;
}

- cmakelist.txt is:
cmake_minimum_required(VERSION 3.20)

project(onnx)

set(CMAKE_CXX_STANDARD 14)

find_package(OpenCV REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})

include_directories("${CMAKE_CURRENT_SOURCE_DIR}/onnxruntime-osx-arm64-1.11.1/include/")

link_libraries("${CMAKE_CURRENT_SOURCE_DIR}/onnxruntime-osx-arm64-1.11.1/lib/")
add_executable(onnx main.cpp)

target_link_libraries(onnx ${OpenCV_LIBS})
target_link_libraries(onnx "${CMAKE_CURRENT_SOURCE_DIR}/onnxruntime-osx-arm64-1.11.1/lib/")

**Comment by lanyuer** [comment]
link_libraries("${CMAKE_CURRENT_SOURCE_DIR}/onnxruntime-osx-arm64-1.11.1/lib/")
-----------
You should link a library, not a direction?

**Comment by RyanUnderhill** [comment]
Looks resolved, closing.
