### ISSUE TITLE
Enable Debug Prints Though out the Execution

### ISSUE THREAD

**Issue by jeffsaremi** [microsoft/onnxruntime#1155]
For those who write convert models to onnx and test them using the runtime, debugging issues in the runtime is very painful. This request is to add features to the runtime whereby one could ask for verbose prints (with different levels) while the model is being executed.

Current runtime version is 0.5.0 and it does not have such feature.

I'd like to have options to run a model and print details about each operation.
I need a multi-level debug print option. 
Level 0: current print out
Level 1: input and output shapes after each operation
Level 2: print out -- the numpy style -- all outputs of each operation or as specified (see below)

If I specify any level 1 or 2 I would want the runtime to stop all optimizations and leave the graph alone to be as supplied.

For Level 2, a separate option could accept Operator names and patterns. If this option is specified along with Level 2 then only the matching operators will have their outputs printed out.

The alternatives are very painful and include running multiple versions of a graph, and modifying the runtime code to print out data.

**Comment by snnn** [comment]
You can control the logging level. 
onnx_test_runner.exe is an example.  If you run the with '-v', you will see more logs.

**Comment by skottmckay** [comment]
Configuration around running optimizations should be separate from configuration for logging. There is a session option for the optimization level. 

There is the notion of a vlog level for the VERBOSE logging level which sounds like it matches better what you're after, however that's different to 'normal' logging with levels such as INFO, WARNING, ERROR.

I would think it's relatively easy to add output of the input and output shapes to the executor with VLOG statements, as the number of inputs/outputs is known and the shape should be accessible.

Logging full data would be more work as you would need some awareness of the data type involved for each input/output.

**Comment by pranavsharma** [comment]
@jeffsaremi can this be closed? Does Scott's fix work for you?

**Comment by jeffsaremi** [comment]
Yes
Scott's solution is perfect for us and has been already helped us in a few cases.
