### ISSUE TITLE
missing header files from win gpu zip package in rev 1.11.1

### ISSUE THREAD

**Issue by shdalton** [microsoft/onnxruntime#11573]
**Describe the bug**
a number of header files (cuda_provider_factory.h, cuda_provider_options.h...) are missing from the onnxruntime-win-x64-gpu-1.11.1.zip archive

**System information**
- Win 10 64
- ONNX binary package
- ONNX 1.11.1 GPU
- Visual Studio version (2019)
- CUDA/cuDNN version: 11.7
- GPU model and memory: RTX3090

**To Reproduce**
- Describe steps/code to reproduce the behavior.
Follow the build instructions for the inference examples :)

**Comment by RyanUnderhill** [comment]
These files are not public header files so are not meant to be included in the .zip.

The OrtCUDAProviderOptionsV2 is now an opaque type to the outside world.

Please use CreateCUDAProviderOptions, and UpdateCUDAProviderOptions to create and set values in it. Do not try to include the internal definition as it's not ABI.
