### ISSUE TITLE
TensorRT EP doesn't load in C# API

### ISSUE THREAD

**Issue by RoudyES** [microsoft/onnxruntime#11572]
**Describe the bug**
I am trying to use ONNXRuntime with TensorRT EP in a .NET 6 application. However it keeps crashing with `onnxruntime::logging::LoggingManager::DefaultLogger Attempt to use DefaultLogger but none has been registered` error. The application works fine on CPU or even CUDA EP but not on TensorRT EP.

**Urgency**
None.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11
- ONNX Runtime installed from (source or binary): Installed from NuGet.
- ONNX Runtime version: 1.11.0
- Visual Studio version (if applicable): VS 2022 (v17.0.6).
- CUDA/cuDNN version: CUDA version 11.4. CuDNN version 8.2.1
- GPU model and memory: GTX 1050Ti 4GB memory.
- TensorRT version: 8.2.4.2

**To Reproduce**
- Simply trying to initialize an InferenceSession object with TRT provider like so: `var session = new InferenceSession(modelPath, SessionOptions.MakeSessionOptionWithTensorrtProvider());`
- I've also tried created the SessionOptions first then appending the TRT provider like so: `    var options = new SessionOptions();
    options.AppendExecutionProvider_Tensorrt();`

**Expected behavior**
Initialize the session normally.

**Additional context**
I've copied all CUDA and CuDNN and TensorRT dll files into the project's output directory (CUDA/CuDNN dlls are also added into the PATH env variable).

Also worth adding, I've tried the same test on .Net Framework 4.7.2 and it initialized fine. The problem seems to be specific to .NET 6.

**Comment by jywu-msft** [comment]
interesting. we haven't encountered issues with specific .NET versions.
the error suggests the env with default logger wasn't created successfully.
maybe you can try debug further with the suggestion in https://github.com/microsoft/onnxruntime/issues/8545#issuecomment-1082451066

@chilo-ms , any ideas? have you had any issues with .NET 6 ?

**Comment by skottmckay** [comment]
You could try explictly creating the environment by calling OrtEnv.Instance(). You don't need to do anything with the return value.

**Comment by RoudyES** [comment]
@jywu-msft @skottmckay Thank you so much for your input! I was able to resolve the issue with the information that you guys provided.

Calling `OrtEnv.Instance()` allowed me to bypass the issue of initializing the environment with the default logger and then initializing the `InferenceSession` threw another exception about failing to load "onnxruntime_providers_tensorrt.dll" library. However, it pointed to the DLL that resides in "bin\Debug\net6.0\runtimes\win-x64\native" path instead of the DLL in the  application output directory "bin\Debug\net6.0". Copying TensorRT DLLs to the former path solved the issue and now everything works fine as intended.

.NET framework doesn't have the same output directory structure as .NET 6 so it had everything thrown together into the "bin/Debug" output directory and it seems this is why I didn't have this issue there. 

Again, thank you both for your help. Issue is now resolved!

**Comment by jywu-msft** [comment]
Glad to hear your issue is resolved!
On our side, we need to find a better way to surface warning message about the missing/incorrect dependency.
As you might have noticed in the other issues I pointed to. the DefaultLogger error message is usually an indication of a missing dependency, but in your original comment it sounded like you had the correct dependencies. (but it turns out .net6.0 looks for them in a different location)

**Comment by RoudyES** [comment]
Exactly. This is my first time trying TensorRT EP in a .NET 6 app and it was kinda confusing why it didn't work even though the dlls were there. Initializing ORT environment explicitly got me the correct error message along with the path of the failing DLL so this seems to be a great debugging workaround until more informative error messages are used!

**Comment by z1521183003** [comment]
I also have the same problem
I tried net4.7.2 and net6.0, both are the same problem

my code  
![image](https://user-images.githubusercontent.com/29905356/177042282-2c150e00-3367-411b-a8c0-d08e868297ff.png)

In Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus) in D:\a\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\NativeApiStatus.shared.cs: line 31
    In Microsoft.ML.OnnxRuntime.SessionOptions.AppendExecutionProvider_CUDA(Int32 deviceId) in D:\a\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\SessionOptions.shared.cs: line 212


My cuda environment is as follows

![image](https://user-images.githubusercontent.com/29905356/177042320-7987952f-4a87-41eb-a81e-2dabd16ff836.png)

![image](https://user-images.githubusercontent.com/29905356/177042363-447e8538-bd09-42ca-b150-3dd3321e7ea0.png)

**Comment by HemantTiwariGitHub** [comment]
Hi @RoudyES 
I am facing same issue , however for me onnxruntime_providers_tensorrt.dll is already existing at  "bin\Debug\net6.0\runtimes\win-x64\native"

**Comment by PTA00** [comment]
> OrtEnv.Instance

You figured it out？

**Comment by Eve-88** [comment]
> Hi [@RoudyES](https://github.com/RoudyES) I am facing same issue , however for me onnxruntime_providers_tensorrt.dll is already existing at "bin\Debug\net6.0\runtimes\win-x64\native"

I have the same issue, Have you solved it now？
