### ISSUE TITLE
onnxruntime-gpu inference slow when once, but fast when continuous

### ISSUE THREAD

**Issue by g782373711** [microsoft/onnxruntime#11581]
**Describe the bug**
I export a onnx model from yolov5, when I test it performance, a strange phenomenon has occurred. it take long time in first inference。if you start inference after last inference in some seconds later，it take about 89ms，but if start inference after last inference immediately, it take only 17ms。

performance log in attach files, you need modify suffix from .txt to .json

**Urgency**
it's a performance issue in my project,  if you know, please tell me why, thank you!!!

**System information**
- OS Platform: Windows 10 21H2 19044.1620:
- ONNX Runtime installed from (source or binary): pip install onnxruntime-gpu 
- ONNX Runtime version:1.10.0
- Python version: python 3.8.10
- CUDA/cuDNN version: CUDA 11.4  cudnn8.2.5
- GPU model and memory: 2080Ti

**To Reproduce**
some detail as shown below:
1) the first inference, it take 1274ms，
2) 2s later，the second inference started, take 361ms
3) 2s later agian,the third inference started,  take 39ms,
4) 2s later agian,  the fourth inference started, take 39ms,
5) 2s later agian,  the fifth inference started, take 89ms,
6) 4s later agian,  the sixth inference started, take 89ms,
7) after the sixth inference, the seventh inference start immediately, take 89ms,
8) after the seventh inference, the eighth inference start immediately, take 89ms,
9) after the eighth inference, the ninth inference start immediately, take 80ms,
10) after the ninth inference, the tenth inference start immediately, take 17ms,
11) after this, if start inference after last inference immediately, it take 17ms only.

**Expected behavior**
The inference is fast every time and time could not fluctuate.

**Additional context**
onnx setting:
opt = ort.SessionOptions()
opt.enable_mem_reuse = True
opt.intra_op_num_threads = 4
opt.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL

data input by io_binding, size is 3 x 640 x 640 
[onnxruntime_profile__2022-05-20_16-31-43.txt](https://github.com/microsoft/onnxruntime/files/8738009/onnxruntime_profile__2022-05-20_16-31-43.txt)

**Comment by RoudyES** [comment]
Hello! Are you re-initializing the session on each inference run?
I tried re-creating your issue in C# also on Yolov5 like so:

```
while (true)
    {
        Stopwatch watch = Stopwatch.StartNew();

        UnmanagedMemoryManager<float> test = new UnmanagedMemoryManager<float>((float*)inputBlob.DataPointer, 3 * 640 * 640);

        // create input tensor
        var inputTensor = new DenseTensor<float>(test.Memory, new int[] { 1, 3, 640, 640 });

        // Create input data for session.
        var input = new List<NamedOnnxValue> { NamedOnnxValue.CreateFromTensor<float>("images", inputTensor) };

        // Run session and send input data in to get inference output.
        var output = session.Run(input);
        watch.Stop();
        Debug.WriteLine(watch.ElapsedMilliseconds);
        Thread.Sleep(5000);
    }
```

The first inference takes a bit of time (which is normal because the runtime is initializing and loading everything to memory), after that it was stable at 15ms. I initialized the `InferenceSession` outside the while loop so it is being created only once and re-using it inside the loop, it performs as expected.

**Comment by g782373711** [comment]
> 

I think not ,  just initialize the session only once. my python code cannot obtain right now，but i have a c++ version, i has the same problem.  the code like below:

**C++ code:**
```c++
ModelLoader::ModelLoader(std::wstring modelFilePath_): modelFilePath(std::move(modelFilePath_)) {
    env = new Ort::Env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING, "logs");
    Ort::SessionOptions sessionOptions;
    sessionOptions.SetIntraOpNumThreads(4);
    sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
    OrtSessionOptionsAppendExecutionProvider_CUDA(sessionOptions, 0);
    session = new Ort::Session(*env, modelFilePath.c_str(), sessionOptions);
    ioBinding = new Ort::IoBinding{ *session };
}
 

std::vector<cv::Mat> ModelLoader::_detect(cv::Mat &blob) {
    std::vector<int64_t> inputDimsInFact{ batchSize, 3, imgH, imgW };
    size_t inputTensorSize = vectorProduct(inputDimsInFact);
    std::vector<float> inputTensorValues(inputTensorSize);
    inputTensorValues.assign(blob.begin<float>(), blob.end<float>());
    std::vector<const char*> inputNames{"input"};
    std::vector<const char*> outputNames{"output"};
    std::vector<Ort::Value> inputTensors;
    Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu(OrtAllocatorType::OrtArenaAllocator, OrtMemType::OrtMemTypeDefault);
    inputTensors.push_back(Ort::Value::CreateTensor<float>(memoryInfo, inputTensorValues.data(), inputTensorSize, inputDimsInFact.data(), inputDimsInFact.size()));


    auto output = session->Run(Ort::RunOptions{ nullptr }, inputNames.data(), inputTensors.data(), 1, outputNames.data(), 1);

 
    return output;
}

**Comment by g782373711** [comment]
> Hello! Are you re-initializing the session on each inference run? I tried re-creating your issue in C# also on Yolov5 like so:
> 
> ```
> while (true)
>     {
>         Stopwatch watch = Stopwatch.StartNew();
> 
>         UnmanagedMemoryManager<float> test = new UnmanagedMemoryManager<float>((float*)inputBlob.DataPointer, 3 * 640 * 640);
> 
>         // create input tensor
>         var inputTensor = new DenseTensor<float>(test.Memory, new int[] { 1, 3, 640, 640 });
> 
>         // Create input data for session.
>         var input = new List<NamedOnnxValue> { NamedOnnxValue.CreateFromTensor<float>("images", inputTensor) };
> 
>         // Run session and send input data in to get inference output.
>         var output = session.Run(input);
>         watch.Stop();
>         Debug.WriteLine(watch.ElapsedMilliseconds);
>         Thread.Sleep(5000);
>     }
> ```
> 
> The first inference takes a bit of time (which is normal because the runtime is initializing and loading everything to memory), after that it was stable at 15ms. I initialized the `InferenceSession` outside the while loop so it is being created only once and re-using it inside the loop, it performs as expected.
I think not , just initialize the session only once. my python code cannot obtain right now，but i have a c++ version, i has the same problem. the code like below:

C++ code:
```C++
ModelLoader::ModelLoader(std::wstring modelFilePath_): modelFilePath(std::move(modelFilePath_)) {
    env = new Ort::Env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING, "logs");
    Ort::SessionOptions sessionOptions;
    sessionOptions.SetIntraOpNumThreads(4);
    sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
    OrtSessionOptionsAppendExecutionProvider_CUDA(sessionOptions, 0);
    session = new Ort::Session(*env, modelFilePath.c_str(), sessionOptions);
    ioBinding = new Ort::IoBinding{ *session };
}
 

std::vector<cv::Mat> ModelLoader::_detect(cv::Mat &blob) {
    std::vector<int64_t> inputDimsInFact{ batchSize, 3, imgH, imgW };
    size_t inputTensorSize = vectorProduct(inputDimsInFact);
    std::vector<float> inputTensorValues(inputTensorSize);
    inputTensorValues.assign(blob.begin<float>(), blob.end<float>());
    std::vector<const char*> inputNames{"input"};
    std::vector<const char*> outputNames{"output"};
    std::vector<Ort::Value> inputTensors;
    Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu(OrtAllocatorType::OrtArenaAllocator, OrtMemType::OrtMemTypeDefault);
    inputTensors.push_back(Ort::Value::CreateTensor<float>(memoryInfo, inputTensorValues.data(), inputTensorSize, inputDimsInFact.data(), inputDimsInFact.size()));


    auto output = session->Run(Ort::RunOptions{ nullptr }, inputNames.data(), inputTensors.data(), 1, outputNames.data(), 1);

 
    return output;
}

**Comment by g782373711** [comment]
> Hello! Are you re-initializing the session on each inference run? I tried re-creating your issue in C# also on Yolov5 like so:
> 
> ```
> while (true)
>     {
>         Stopwatch watch = Stopwatch.StartNew();
> 
>         UnmanagedMemoryManager<float> test = new UnmanagedMemoryManager<float>((float*)inputBlob.DataPointer, 3 * 640 * 640);
> 
>         // create input tensor
>         var inputTensor = new DenseTensor<float>(test.Memory, new int[] { 1, 3, 640, 640 });
> 
>         // Create input data for session.
>         var input = new List<NamedOnnxValue> { NamedOnnxValue.CreateFromTensor<float>("images", inputTensor) };
> 
>         // Run session and send input data in to get inference output.
>         var output = session.Run(input);
>         watch.Stop();
>         Debug.WriteLine(watch.ElapsedMilliseconds);
>         Thread.Sleep(5000);
>     }
> ```
> 
> The first inference takes a bit of time (which is normal because the runtime is initializing and loading everything to memory), after that it was stable at 15ms. I initialized the `InferenceSession` outside the while loop so it is being created only once and re-using it inside the loop, it performs as expected.





I think not , just initialize the session only once. my python code cannot obtain right now，but i have a c++ version, i has the same problem. the code like below:

C++ code:

ModelLoader::ModelLoader(std::wstring modelFilePath_): modelFilePath(std::move(modelFilePath_)) {
    env = new Ort::Env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING, "logs");
    Ort::SessionOptions sessionOptions;
    sessionOptions.SetIntraOpNumThreads(4);
    sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
    OrtSessionOptionsAppendExecutionProvider_CUDA(sessionOptions, 0);
    session = new Ort::Session(*env, modelFilePath.c_str(), sessionOptions);
    ioBinding = new Ort::IoBinding{ *session };
}
 

std::vector<cv::Mat> ModelLoader::_detect(cv::Mat &blob) {
    std::vector<int64_t> inputDimsInFact{ batchSize, 3, imgH, imgW };
    size_t inputTensorSize = vectorProduct(inputDimsInFact);
    std::vector<float> inputTensorValues(inputTensorSize);
    inputTensorValues.assign(blob.begin<float>(), blob.end<float>());
    std::vector<const char*> inputNames{"input"};
    std::vector<const char*> outputNames{"output"};
    std::vector<Ort::Value> inputTensors;
    Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu(OrtAllocatorType::OrtArenaAllocator, OrtMemType::OrtMemTypeDefault);
    inputTensors.push_back(Ort::Value::CreateTensor<float>(memoryInfo, inputTensorValues.data(), inputTensorSize, inputDimsInFact.data(), inputDimsInFact.size()));


    auto output = session->Run(Ort::RunOptions{ nullptr }, inputNames.data(), inputTensors.data(), 1, outputNames.data(), 1);

 
    return output;
}

**Comment by g782373711** [comment]
> Hello! Are you re-initializing the session on each inference run? I tried re-creating your issue in C# also on Yolov5 like so:
> 
> ```
> while (true)
>     {
>         Stopwatch watch = Stopwatch.StartNew();
> 
>         UnmanagedMemoryManager<float> test = new UnmanagedMemoryManager<float>((float*)inputBlob.DataPointer, 3 * 640 * 640);
> 
>         // create input tensor
>         var inputTensor = new DenseTensor<float>(test.Memory, new int[] { 1, 3, 640, 640 });
> 
>         // Create input data for session.
>         var input = new List<NamedOnnxValue> { NamedOnnxValue.CreateFromTensor<float>("images", inputTensor) };
> 
>         // Run session and send input data in to get inference output.
>         var output = session.Run(input);
>         watch.Stop();
>         Debug.WriteLine(watch.ElapsedMilliseconds);
>         Thread.Sleep(5000);
>     }
> ```
> 
> The first inference takes a bit of time (which is normal because the runtime is initializing and loading everything to memory), after that it was stable at 15ms. I initialized the `InferenceSession` outside the while loop so it is being created only once and re-using it inside the loop, it performs as expected.




I think not , just initialize the session only once. my python code cannot obtain right now，but i have a c++ version, i has the same problem. the code like below:

C++ code:
```C++
ModelLoader::ModelLoader(std::wstring modelFilePath_): modelFilePath(std::move(modelFilePath_)) {
    env = new Ort::Env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING, "logs");
    Ort::SessionOptions sessionOptions;
    sessionOptions.SetIntraOpNumThreads(4);
    sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
    OrtSessionOptionsAppendExecutionProvider_CUDA(sessionOptions, 0);
    session = new Ort::Session(*env, modelFilePath.c_str(), sessionOptions);
    ioBinding = new Ort::IoBinding{ *session };
}
 

std::vector<cv::Mat> ModelLoader::_detect(cv::Mat &blob) {
    std::vector<int64_t> inputDimsInFact{ batchSize, 3, imgH, imgW };
    size_t inputTensorSize = vectorProduct(inputDimsInFact);
    std::vector<float> inputTensorValues(inputTensorSize);
    inputTensorValues.assign(blob.begin<float>(), blob.end<float>());
    std::vector<const char*> inputNames{"input"};
    std::vector<const char*> outputNames{"output"};
    std::vector<Ort::Value> inputTensors;
    Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu(OrtAllocatorType::OrtArenaAllocator, OrtMemType::OrtMemTypeDefault);
    inputTensors.push_back(Ort::Value::CreateTensor<float>(memoryInfo, inputTensorValues.data(), inputTensorSize, inputDimsInFact.data(), inputDimsInFact.size()));


    auto output = session->Run(Ort::RunOptions{ nullptr }, inputNames.data(), inputTensors.data(), 1, outputNames.data(), 1);

 
    return output;
}

**Comment by RoudyES** [comment]
Are you calling `ModelLoader::_detect` in a loop? I'm not very familiar with the C++ API but I think you have some unnecessary operations in there. Example:
```
std::vector<const char*> inputNames{"input"};
std::vector<const char*> outputNames{"output"};
std::vector<Ort::Value> inputTensors;
Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu(OrtAllocatorType::OrtArenaAllocator, OrtMemType::OrtMemTypeDefault);
```
These lines never change so why re-initialize them on each iteration (especially the Ort::MemoryInfo::CreateCPU() call)?

Also, assuming your image dimensions arent't changing, you can also initialize those lines only once:

```
std::vector<int64_t> inputDimsInFact{ batchSize, 3, imgH, imgW };
size_t inputTensorSize = vectorProduct(inputDimsInFact);
std::vector<float> inputTensorValues(inputTensorSize);
```

This way your detect method will simply overwrite data on existing memory.
Again, I'm not very familiar with the C++ API so correct me if I'm wrong there.
As for your problem, I'd say use a timer to check the `session->Run()` operation alone and see if it is slower when there's a slight pause between its calls.

**Comment by g782373711** [comment]
> Are you calling `ModelLoader::_detect` in a loop? I'm not very familiar with the C++ API but I think you have some unnecessary operations in there. Example:
> ```
> std::vector<const char*> inputNames{"input"};
> std::vector<const char*> outputNames{"output"};
> std::vector<Ort::Value> inputTensors;
> Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu(OrtAllocatorType::OrtArenaAllocator, OrtMemType::OrtMemTypeDefault);
> ```
> These lines never change so why re-initialize them on each iteration (especially the Ort::MemoryInfo::CreateCPU() call)?
> 
> Also, assuming your image dimensions arent't changing, you can also initialize those lines only once:
> 
> ```
> std::vector<int64_t> inputDimsInFact{ batchSize, 3, imgH, imgW };
> size_t inputTensorSize = vectorProduct(inputDimsInFact);
> std::vector<float> inputTensorValues(inputTensorSize);
> ```
> 
> This way your detect method will simply overwrite data on existing memory.
> Again, I'm not very familiar with the C++ API so correct me if I'm wrong there.
> As for your problem, I'd say use a timer to check the `session->Run()` operation alone and see if it is slower when there's a slight pause between its calls.



yeah, you idea is nice. in addition, I only measure the time of session->run().

**Comment by RoudyES** [comment]
If that's the case then it could be that your GPU is shifting resources away from your application when there's a wait between runs. This happens on my machine but it's a 1050Ti in my case..

That's just my 2 cents though, I'm sorry I couldn't help you further. Hope someone with more experience than me can better help you in your issue.

**Comment by g782373711** [comment]
> If that's the case then it could be that your GPU is shifting resources away from your application when there's a wait between runs. This happens on my machine but it's a 1050Ti in my case..
> 
> That's just my 2 cents though, I'm sorry I couldn't help you further. Hope someone with more experience than me can better help you in your issue.



It may seems that way, and I try to see if I can figure out why. Thank you for your idea

**Comment by g782373711** [comment]
> Are you calling `ModelLoader::_detect` in a loop? I'm not very familiar with the C++ API but I think you have some unnecessary operations in there. Example:
> 
> ```
> std::vector<const char*> inputNames{"input"};
> std::vector<const char*> outputNames{"output"};
> std::vector<Ort::Value> inputTensors;
> Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu(OrtAllocatorType::OrtArenaAllocator, OrtMemType::OrtMemTypeDefault);
> ```
> 
> These lines never change so why re-initialize them on each iteration (especially the Ort::MemoryInfo::CreateCPU() call)?
> 
> Also, assuming your image dimensions arent't changing, you can also initialize those lines only once:
> 
> ```
> std::vector<int64_t> inputDimsInFact{ batchSize, 3, imgH, imgW };
> size_t inputTensorSize = vectorProduct(inputDimsInFact);
> std::vector<float> inputTensorValues(inputTensorSize);
> ```
> 
> This way your detect method will simply overwrite data on existing memory. Again, I'm not very familiar with the C++ API so correct me if I'm wrong there. As for your problem, I'd say use a timer to check the `session->Run()` operation alone and see if it is slower when there's a slight pause between its calls.


Sorry to bother you again, I wonder how to avoid the long Inference time of the first inference on CUDA?

**Comment by RoudyES** [comment]
I'm afraid there's no avoiding this first slow inference. This doesn't only happen with onnxruntime. Even in torch and TF the first inference on gpu takes a bit of time just to initialize everything.

**Comment by g782373711** [comment]
> I'm afraid there's no avoiding this first slow inference. This doesn't only happen with onnxruntime. Even in torch and TF the first inference on gpu takes a bit of time just to initialize everything.

OK， thanks.

**Comment by Mihir-Gajera1** [comment]
Experiencing the same issue with hifigan vocoder fp16 quantized onnx model? First inference and inference after a pause is taking 10x time than continuous inference. How to avoid this?

**Comment by g782373711** [comment]
> the issue be solved here.

#https://github.com/NVIDIA/TensorRT/issues/2042#issue-1264440607

**Comment by g782373711** [comment]
> Experiencing the same issue with hifigan vocoder fp16 quantized onnx model? First inference and inference after a pause is taking 10x time than continuous inference. How to avoid this?

the issue be solved here.   https://github.com/NVIDIA/TensorRT/issues/2042#issue-1264440607

**Comment by Mihir-Gajera1** [comment]
Thanks.  @g782373711.
