### ISSUE TITLE
Where to find how QLinearConv is implemented?

### ISSUE THREAD

**Issue by vvolhejn** [microsoft/onnxruntime#11599]
Hi, I'm trying to understand how exactly static quantization with QDQ works on x86_64. Specifically, I'm wondering whether matrix multiplication and convolutional layers use floating-point or integer instructions (PyTorch's backend FBGEMM [uses vpmaddubsw and vpaddsw](https://engineering.fb.com/2018/11/07/ml-applications/fbgemm/)), and what instructions specifically. I am testing on a simple conv2d->maxpool model. Here are the .onnx files: [onnxruntime-qlinearconv-question.zip].(https://github.com/microsoft/onnxruntime/files/8754853/onnxruntime-qlinearconv-question.zip)

I assumed integer instructions are used (that's what quantization is for, right?) but was confused by the fact that Netron shows me

![Screenshot 2022-05-23 at 14 50 53](https://user-images.githubusercontent.com/8401624/169827581-d3698011-cda5-4e0e-a2ea-e3605704e838.png)

when I visualize the saved quantized model. This seems to imply that the weights are first dequantized and a regular fp32 convolution is performed. That's what the [quantization docs](https://onnxruntime.ai/docs/performance/quantization.html#data-type-selection) seem to imply as well:
> Tensor Oriented, aka Quantize and DeQuantize (QDQ). This format uses DQ(Q(tensor)) to simulate the quantize and dequantize process, and QuantizeLinear and DeQuantizeLinear operators also carry the quantization parameters

Then I figured out that this representation might not correspond to what's actually being done, so I tried loading my model using the following:

```python
session_options = ort.SessionOptions()
session_options.graph_optimization_level = (
    ort.GraphOptimizationLevel.ORT_ENABLE_EXTENDED
)
session_options.optimized_model_filepath = "quantized_model_optimized.onnx"

self.session = ort.InferenceSession(
    "quantized_model.onnx",
    sess_options=session_options,
)
```

When I visualize `optimized_model.onnx` using Netron, I see

![Screenshot 2022-05-23 at 14 51 44](https://user-images.githubusercontent.com/8401624/169827667-5f7f40dd-bc7b-42e3-acbf-a447081be3fa.png)

where the convolution turned into a QLinearConv. I assume this operation uses integer instructions but I wanted to verify this in the code. I found the corresponding implementation in [`qlinearconv.cc`](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/quantization/qlinearconv.cc) - I guess the relevant call is [`MlasGemm`](https://github.com/microsoft/onnxruntime/blob/6072c6b65e9a8816ba53ccbdb15dbd7fc7001e18/onnxruntime/core/providers/cpu/quantization/qlinearconv.cc#L863). I'm having trouble figuring out what this calls exactly since there are several implementations defined in the [`mlas`](https://github.com/microsoft/onnxruntime/tree/0d0edc071f24112dea9719096bd609b99954bfc0/onnxruntime/core/mlas) directory - is it `qgemm`, `sgemm` or something else? The documentation is unfortunately pretty sparse.

How can I determine which `MlasGemm` implementation is being called, and which machine instructions it actually uses?

**System information**
- ONNX Runtime version (you are using): 1.11.1
- OS: CentOS Linux release 7.9.2009 (Core)
- CPU: Intel Xeon Gold 5118
- `/proc/cpuinfo` says:
```
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_pkg_req pku ospke md_clear spec_ctrl intel_stibp flush_l1d
```

I would also appreciate general pointers on where to look for similar sorts of information: what implementation/instructions are used on specific hardware for specific operations. 

Thank you!

**Comment by tianleiwu** [comment]
The implementation of QLinearConv: https://github.com/microsoft/onnxruntime/blob/6072c6b65e9a8816ba53ccbdb15dbd7fc7001e18/onnxruntime/core/providers/cpu/quantization/qlinearconv.cc

**Comment by vvolhejn** [comment]
Hi @tianleiwu, thank you - indeed I did manage find this file, however I didn't manage to make out what implementation the `MlasGemm` call (assuming it is the relevant one) is actually calling.
