### ISSUE TITLE
Is there a C++ API in onnxruntime like torch::autograd::grad()?

### ISSUE THREAD

**Issue by Fansomone** [microsoft/onnxruntime#11637]
is there a C++ API in onnxruntime like torch::autograd::grad()?

**Comment by baijumeswani** [comment]
Hi @Fansomone. We have an API that can auto generate the gradient graph given the forward graph in C++: https://github.com/microsoft/onnxruntime/blob/main/orttraining/orttraining/core/framework/gradient_graph_builder.h#L83

However, this api is not publicly exposed through the training c apis (https://github.com/microsoft/onnxruntime/blob/main/orttraining/orttraining/training_api/include/onnxruntime_training_c_api.h).

There could be an update on this in the near future. Please let me know if this would be of help for you.

Sorry for the late response.

**Comment by newton-raphson** [comment]
Hello, is the api ending now publicly available ?
