### ISSUE TITLE
[C#] Provide custom_op_library.dll

### ISSUE THREAD

**Issue by GeorgeS2019** [microsoft/onnxruntime#11653]
**Is your feature request related to a problem? Please describe.**
Without building and just using the provided release onnxruntime.dll, In c#, it is only possible to run all tests EXCEPT those associated with custom_op_library.dll

**System information**
- ONNX Runtime v1.11.1
- Windows 11
- VS2022

**Describe the solution you'd like**
Provide **custom_op_library.dll** together with onnxruntime.dll in release so it is possible to run ALL Tests in c#

**Comment by snnn** [comment]
custom_op_library.dll is a part of the unit tests. We don't publish binaries of unit tests. The DLL has no real value.

**Comment by GeorgeS2019** [comment]
@snnn  We are stuck. Without successfully building for Windows, which I wasted 2 days, I could not test the custom Op feature
