### ISSUE TITLE
Missing link on InferenceHighLevelDesign.md

### ISSUE THREAD

**Issue by GeorgeS2019** [microsoft/onnxruntime#11661]
The following document is missing

https://github.com/microsoft/onnxruntime/blob/master/docs/InferenceHighLevelDesign.md

Possible alternative

- https://github.com/microsoft/onnxruntime-openenclave/blob/openenclave-public/docs/InferenceHighLevelDesign.md

**Comment by GeorgeS2019** [comment]
The [link](https://github.com/microsoft/onnxruntime/blob/master/docs/InferenceHighLevelDesign.md) was referenced by other doc within the onnxruntime repository.

**Comment by natke** [comment]
@GeorgeS2019 Where is the source page from which this doc linked? Thank you!

**Comment by GeorgeS2019** [comment]
-[CONTRIBUTING.md](https://github.com/microsoft/onnxruntime/blob/master/CONTRIBUTING.md)
![image](https://user-images.githubusercontent.com/49812372/172532734-2680ab35-80c7-471e-aff8-b82938b8e0f8.png)

- [Roadmap.md](https://github.com/microsoft/onnxruntime/blob/master/docs/Roadmap.md)
![image](https://user-images.githubusercontent.com/49812372/172532803-7a8bd6ea-7028-4e33-8556-9ff205d78b6b.png)
