### ISSUE TITLE
The problem that the output image of super-resolution reconstructed image is gray nine-pattern

### ISSUE THREAD

**Issue by djdll** [microsoft/onnxruntime#11677]
1.When I call an onnx model about video super-resolution reconstruction via c++, the output image after the final result is a gray nine-pane grid, which should be a rgb image normally.

**System information**
- ONNX Runtime version (you are using):1..8.1+gpu

**Describe the solution you'd like**
In torch (pytorch/libtorch) there is a contiguous() method, by testing my results in libtorch deleting this method will get the same problem with onnx output, so using onnx there is no corresponding libtorch same method to solve this problem?

I hope you can understand my problem better through my code:
std::vector<Ort::Value> ort_outputs = session.Run(Ort::RunOptions{ nullptr }, input_names.data(),ort_inputs.data(),ort_inputs.size(),output_names.data(),3);
float* floatarr = ort_outputs[0].GetTensorMutableData<float>();
std::vector<float>results(outputSizeCount);
for (unsigned i = 0; i < outputSizeCount; i++)
{
	results[i] = floatarr[i];
}
cv::Mat output_tensor(results);
cv::Mat dest = output_tensor.reshape(3, { sr_h,sr_w }) * 255.0f;
cv::imwrite("E:/SR/RealBasic_pt/onnx_res1.png", dest);
Thanks.

**Comment by RyanUnderhill** [comment]
In pytorch, contiguous() just ensures the data in the tensor is contiguous in memory. In onnxruntime the data returned by 'GetTensorMutableData()' is always contiguous, so this shouldn't be needed.

I'm not sure how the ordering of the memory would affect it being gray vs rgb, can you give more details?

**Comment by djdll** [comment]
I finally solved the problem by converting float* floatarr = ort_outputs[0].GetTensorMutableData<float>(); to a tensor and then saving it as a mat. I suspect that since I'm saving an rgb image, I can't convert float* floatarr to mat directly and need to go through a Tensor as an intermediary.
Here's how I found it on the web hopefully it will help others:
`std::vector<cv::Mat> results;
	torch::Tensor result_r = torch::from_blob(floatarr, { sr_h,sr_w,1 });
	torch::Tensor result_g = torch::from_blob(&floatarr[sr_h * sr_w - 1], { sr_h,sr_w,1 });
	torch::Tensor result_b = torch::from_blob(&floatarr[sr_h * sr_w * 2 - 1], { sr_h,sr_w,1 });
	torch::Tensor result = torch::cat({ result_r, result_g, result_b }, 2);
	result = result.mul(255);
	result = result.clamp(0, 255);
	result = result.to(torch::kU8);
	cv::Mat resultImg(sr_h, sr_w, CV_8UC3);
	std::memcpy((void*)resultImg.data, result.data_ptr(), sizeof(torch::kU8)* result.numel());
	//cv::cvtColor(resultImg, resultImg, cv::COLOR_RGB2BGR);
	results.push_back(resultImg);`

**Comment by djdll** [comment]
@RyanUnderhill The key to this problem I think is the problem of converting float * floatarr to three-channel mat, if you have a more official solution, please tell me more

**Comment by kikirizki** [comment]
@djdll Hi did you find another solution without libtorch?

**Comment by kikirizki** [comment]
I have the same problem where my cv::Mat is not contiguous

**Comment by kikirizki** [comment]
@djdll it also happened on python but it can be solved with this following code

`        img is not contiguous
        
        # First slice missing dims
        N_slice = 0 if 'N' not in format else slice(None)
        H_slice = 0 if 'H' not in format else slice(None)
        W_slice = 0 if 'W' not in format else slice(None)
        C_slice = 0 if 'C' not in format else slice(None)
        img = img[N_slice, H_slice, W_slice, C_slice]

        f = ''
        if 'N' in format: f += 'N'
        if 'H' in format: f += 'H'
        if 'W' in format: f += 'W'
        if 'C' in format: f += 'C'

        if f != format:
            # Transpose to target
            d = { s:i for i,s in enumerate(f) }
            transpose_order = [ d[s] for s in format ]
            img = img.transpose(transpose_order)

        return np.ascontiguousarray(img)`

**Comment by djdll** [comment]
@kikirizki If you are using torch(pytorch/libtorch), you can try a = a.contiguous(); If you are not using torch you can try to process the three channels of the image separately before merging the final output, I don't know if it can help you
