### ISSUE TITLE
OnnxRuntime on python 3.10.*

### ISSUE THREAD

**Issue by Kieran-Bacon** [microsoft/onnxruntime#11680]
OnnxRuntime is not available on python 3.10.* and it would be great if it could be 

```
ERROR: Could not find a version that satisfies the requirement onnxruntime (from ***) (from versions: none)
ERROR: No matching distribution found for onnxruntime
```

**System information**
According to this issue https://github.com/Microsoft/onnxruntime/issues/250 and the project file https://pypi.org/project/onnxruntime/#files this is true for all systems. (no *cp310* release) 

**Additional Context**

It's been 8 months since its release, it's quite frustrating that it's not been incremented yet.

**Comment by GeorgeS2019** [comment]
https://test.pypi.org/simple/ort-nightly/

**Comment by Kieran-Bacon** [comment]
@GeorgeS2019 Thanks, that's great for testing temporarily but won't be something I can depend on.

**Comment by devalexqt** [comment]
Please release for python 3.10!

**Comment by GeorgeS2019** [comment]
[additional discussion](https://github.com/ivadomed/ivadomed/issues/1136#issuecomment-1141537454)

**Comment by zouzhen** [comment]
Please release for python 3.10!

**Comment by gc-plp** [comment]
Seems that 1.12.0 has entered the RC phase two weeks ago: https://github.com/microsoft/onnxruntime/issues/12133

**Comment by tux-o-matic** [comment]
Issue can be closed. 1.13.1 is out now and it works on Python 3.10.

**Comment by wangjia184** [comment]
now it is python 3.11
