### ISSUE TITLE
Converted ONNX model works with v1.9.0 but not with v1.11.1

### ISSUE THREAD

**Issue by darkcoder2000** [microsoft/onnxruntime#11686]
I can load and use a model that has been converted from TFlite to ONNX with ONNX runtime v1.9.0.
But after updating to ONNX runtime v1.11.1 the model can't be used anymore.

I am getting the follwing error message

NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for QuantizeLinear(13) node with name 'Transpose_token_0_out0_post_dq_post_dq_post_dq_post_dq_post_dq_post_dq_post_dq_post_dq_post_dq_post_dq_q'

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): binary 
- ONNX Runtime version: 1.9.0 and 1.11.1
- Python version: 3.7.11
- Visual Studio version (if applicable): none
- GCC/Compiler version (if compiling from source): none
- CUDA/cuDNN version: none
- GPU model and memory: none

**To Reproduce**

Load the attached model with onnx runtime v1.11.1
[model.zip](https://github.com/microsoft/onnxruntime/files/8804951/model.zip)

```python
import onnxruntime as ort

onnx_file = "model.onnx"

sess_ort = ort.InferenceSession(onnx_file)

input_name = sess_ort.get_inputs()[0].name
print("input name", input_name)
input_shape = sess_ort.get_inputs()[0].shape
print("input shape", input_shape)
input_type = sess_ort.get_inputs()[0].type
print("input type", input_type)

output_name = sess_ort.get_outputs()[0].name
print("output name", output_name)
output_shape = sess_ort.get_outputs()[0].shape
print("output shape", output_shape)
output_type = sess_ort.get_outputs()[0].type
print("output type", output_type)
```

**Expected behavior**
The model should work as it is with ONNX runtime v1.9.0
Since the website is saying that it should work in that case.

https://onnxruntime.ai/docs/reference/compatibility#backwards-compatibility

**Comment by yufenglee** [comment]
It is same issue as #11605.
