### ISSUE TITLE
RunOpt object has no attribute 'add_run_config_entry'

### ISSUE THREAD

**Issue by codender** [microsoft/onnxruntime#11683]
**Describe the bug**
I am trying to use this [cfg](https://github.com/microsoft/onnxruntime/blob/0292356bd7ce5b379be8ee9820bfbf4fd321ebc5/onnxruntime/test/python/onnxruntime_test_python.py#L1197) to shrink mem in python, but error occored: `AttributeError: 'onnxruntime.capi.onnxruntime_pybind11_state.RunOpt' object has no attribute 'add_run_config_entry'`

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.6 LTS
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: onnxruntime-gpu 1.11.1
- Python version: 3.8
- Visual Studio version (if applicable): 1.65.2
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
run_option = onnxruntime.RunOptions()
run_option.add_run_config_entry("memory.enable_memory_arena_shrinkage", "gpu:0")

**Expected behavior**
error missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/21005749/171106947-1238adf8-827d-4b26-95ed-3a1a80c36b93.png)
![image](https://user-images.githubusercontent.com/21005749/171106395-53a4cccf-9c20-4600-b6cb-7b125ef95f31.png)

**Comment by yuslepukhin** [comment]
This is a part of the [test](https://github.com/microsoft/onnxruntime/blob/84918ff028110a2a095facce4f8d57bd06a2ffc3/onnxruntime/test/python/onnxruntime_test_python.py#L1183) we run. Does it not work for you?

**Comment by jywu-msft** [comment]
that feature isn't part of 1.11.x   , seems like it just missed the cut-off.
can you try the latest nightly package? https://test.pypi.org/project/ort-nightly-gpu/

**Comment by codender** [comment]
> This is a part of the [test](https://github.com/microsoft/onnxruntime/blob/84918ff028110a2a095facce4f8d57bd06a2ffc3/onnxruntime/test/python/onnxruntime_test_python.py#L1183) we run. Does it not work for you?

@yuslepukhin Not work in 1.11.x. As @jywu-msft said, it works in the latest nightly package.
