### ISSUE TITLE
WASM build process not outputting WASM and JS file

### ISSUE THREAD

**Issue by Jonah1234567** [microsoft/onnxruntime#11691]
**Describe the bug**
When using the build process as specified at the following link: https://github.com/microsoft/onnxruntime/blob/master/js/README.md#Build-2 
There are no WASM or JS wrapper files being outputted. 
I was trying to build the wasm artifacts rather than pull them.

**Urgency**
As soon as possible, this is the primary blocker in a sizeable project

**System information**
I have tried with Windows 10, Colab and Ubuntu 22.04 with Python 3.7.13 (Colab) 3.8.8 for Windows and 3.8 for Ubuntu.

**To Reproduce**
Use the build procedure specified in the build process for js/web with any of the system info I specified above. I tried building the wasm artifacts rather than pull them.

**Expected behavior**
WASM and JS files to be outputted with the build procedure

**Comment by fs-eire** [comment]
could you share your build commandline and the build logs so that I can take a look?

**Comment by Jonah1234567** [comment]
The build takes like 2 hours and is really long, the guide points me to the build output folder although no such folder exists or is it not pointed out properly. Where would I find the build logs?

**Comment by Jonah1234567** [comment]
I'll work on reproducing them

**Comment by fs-eire** [comment]
the build logs are those from stdout/stderr

**Comment by Jonah1234567** [comment]
The issue was that I was not using the recursively cloned github repo for my build. In general the github's build instructions differs from the docs quite a bit so I would recommend cleaning that up if possible!
