### ISSUE TITLE
onnx_runtime speed unstable when inference on cpu

### ISSUE THREAD

**Issue by saxh** [microsoft/onnxruntime#11698]
**Describe the bug**
onnx_runtime model is so unstable when doing inference.
i do inference on cpu only.
this is code,only 4 layers CNN.

  class ONNXModel:

      def __init__(self):
          self.onnx_model = onnxruntime.InferenceSession("weights/CNN4-10216.onnx")
          self.onnx_model.get_modelmeta()

      def inference_model_with_word(self, img):
          results = self.onnx_model.run(["output"], {"input": img.numpy()})
          return results

this is the cost time analysis.
<img width="401" alt="image" src="https://user-images.githubusercontent.com/22788088/171344777-f3e2408b-778d-43f9-b53c-a0b8bd1f74c5.png">

can anybody help?

**Comment by yuslepukhin** [comment]
Please, follow the template to specify the version of the software. 
Also, would be nice to provide a link to a model along with a repro test case with input. Just knowing the model is 4 layers is not enough.

**Comment by skottmckay** [comment]
Also please include the code you're using to measure performance so it's clear what is and isn't included in the elapsed time, and how many iterations you're doing.

**Comment by saxh** [comment]
thank you for reply.
the version is 1.9.0.

I have solved it by setting SessionOptions like this.

sess_options = onnxruntime.SessionOptions()
sess_options.intra_op_num_threads = 8
sess_options.execution_mode = onnxruntime.ExecutionMode.ORT_SEQUENTIAL
sess_options.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_ENABLE_ALL

and i will create a repro later.
