### ISSUE TITLE
Inference Session in GPT-NEO-1.3B fails

### ISSUE THREAD

**Issue by Zapotecatl** [microsoft/onnxruntime#11708]
**Inference Session in GPT-NEO-1.3B fails**

I exported the model GPT-NEO-1.3B to onnx with this command:

`python -m transformers.onnx --model=EleutherAI/gpt-neo-1.3B --feature=causal-lm onnx/`

I get a lot the files in the onnx folder plus the model.onnx. I tested the model with this code:

```
import onnx
# Check we can load the model
onnx_model = onnx.load('onnx/model.onnx')
# Check the model
onnx.checker.check_model('onnx/model.onnx', full_check=True)
#print(onnx.helper.printable_graph(onnx_model.graph))
print("Ok")
```
The result is OK.

However, when I try to do the inference with this code:

```
import onnxruntime as ort
from transformers import GPT2Tokenizer, GPTNeoModel
import torch

tokenizer = GPT2Tokenizer.from_pretrained("EleutherAI/gpt-neo-1.3B")
utterance = "I want to order a Pizza"
tokens_ids = tokenizer(utterance, return_tensors="pt")

input_ids = torch.cat((tokens_ids['input_ids'], torch.zeros(1, 120, dtype=torch.int64)), dim=1)
attention_mask = torch.cat((tokens_ids['attention_mask'], torch.zeros(1, 120, dtype=torch.int64)), dim=1)
decoder_input_ids = torch.zeros(1, 128, dtype=torch.int64)
decoder_attention_mask = torch.zeros(1, 128, dtype=torch.int64)

print(input_ids)
print(attention_mask)

options = ort.SessionOptions()
print(options)

ort_session = ort.InferenceSession('C:/Users/Jorge/PycharmProjects/inteBERT/onnx/model.onnx', options)

print("Ok")
```
I get the error:

**[ONNXRuntimeError] : 1 : FAIL : Deserialize tensor transformer.h.16.attn.attention.out_proj.bias failed.open file transformer.h.16.attn.attention.out_proj.bias fail, errcode = 2 - The system cannot find the specified file.**

Nevertheless, the file transformer.h.16.attn.attention.out_proj.bias is in the onnx folder.

The error occurs in the line: 

`ort_session = ort.InferenceSession('C:/Users/Jorge/PycharmProjects/inteBERT/onnx/model.onnx', options)`

Please, can you someone give me an advice?

**Comment by tianleiwu** [comment]
@[Zapotecatl](https://github.com/Zapotecatl), what ONNX Runtime version do you use? ORT used to work for model with external data. You can try older release version to see whether the problem reproduces.

**Comment by yuslepukhin** [comment]
What version of ORT are you using? Please, follow the template to avoid follow-up questions and speedup responses. Thanks!

**Comment by yuslepukhin** [comment]
> Please, can you someone give me an advice?
Run procmon from sysinternals tools and trace file system calls from your process. You will see where the process is looking for files and what the exact windows error on trying to open the fil.

**Comment by Zapotecatl** [comment]
@tianleiwu and @yuslepukhin   Thanks for the suggestions
The ONNX Runtime that I am using is the 1.11.0. 

I have tried with:

version 1.10.0

```
File "C:\Users\Jorge\PycharmProjects\pythonProject\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 379, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Deserialize tensor 4751 failed.open file 4751 fail, errcode = 2 - The system cannot find the specified file.
```
versions 1.9.0 and 1.8.0

```
File "C:\Users\Jorge\PycharmProjects\pythonProject\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 369, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Deserialize tensor transformer.h.12.ln_1.weight failed.open file transformer.h.12.ln_1.weight fail, errcode = 2 - The system cannot find the specified file.
```

@yuslepukhin I have tried to do the trace with procmon in my process pycharm64.exe, but the only thing regarding my script tha I found is this (to be honest, I don't undestand very well procmon, is the first time that I use it).

![pocharm](https://user-images.githubusercontent.com/6554457/171967774-22d4d3fc-b162-4e22-bb25-6cda9bde89ba.jpg)

**Comment by yuslepukhin** [comment]
@Zapotecatl The initial report indicates that you are running `python`
`python -m transformers.onnx --model=EleutherAI/gpt-neo-1.3B --feature=causal-lm onnx/`

**Comment by tianleiwu** [comment]
@[Zapotecatl](https://github.com/Zapotecatl),  I did not reproduce the issue with ORT 1.11.0. The onnx model can be loaded in both CPU and GPU.

```
Python 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime as ort
>>> options = ort.SessionOptions()
>>> ort_session = ort.InferenceSession('gpt-neo-1.3B/model.onnx', options, providers=['CPUExecutionProvider'])
>>> ort_session2 = ort.InferenceSession('/data/gpt_neo/gpt-neo-1.3B/model.onnx', options, providers=['CUDAExecutionProvider','CPUExecutionProvider'])
>>>
```
Here is my environment: 
  PyTorch: 1.11.0+cu113
  Transformers: 4.18.0
  Onnx: 1.11.0

**Comment by Zapotecatl** [comment]
Thanks a lot @yuslepukhin and @tianleiwu , the use of  "\\\\" is the solution.

`ort_session = ort.InferenceSession('C:\\Users\\Jorge\\PycharmProjects\\inteBERT\\onnx\\model.onnx', options)`
