### ISSUE TITLE
Ort::SessionOptions::AppendExecutionProvider_CUDA_V2 missing from C++ API

### ISSUE THREAD

**Issue by CarlPoirier** [microsoft/onnxruntime#11703]
So I was looking at the [documentation](https://onnxruntime.ai/docs/performance/tune-performance.html) on how to use the new opaque cuda options to set the value of cudnn_conv_use_max_workspace. 

It seems it has not been made available yet in the C++ API, according to [this](https://onnxruntime.ai/docs/api/c/struct_ort_1_1_session_options.html). Is it planned soon?

Thanks

**Comment by hariharans29** [comment]
It was added by https://github.com/microsoft/onnxruntime/pull/11153/ and should be available in the next release.

**Comment by CarlPoirier** [comment]
Awesome, thanks!
