### ISSUE TITLE
"Build for Android" docs doesn't mention how to run tests

### ISSUE THREAD

**Issue by garymm** [microsoft/onnxruntime#11720]
[Build for Android](https://onnxruntime.ai/docs/build/android.html) should link to https://github.com/microsoft/onnxruntime/blob/c170061998e1adfb5a37dfe87d2f845b202cd348/docs/Android_testing.md

**Comment by mszhanyi** [comment]
Currently, it would run building and testing unless `--skip_tests` is specified.
cc @snnn

**Comment by natke** [comment]
Fixed by #11766
