### ISSUE TITLE
float 16 inference support

### ISSUE THREAD

**Issue by vsooda** [microsoft/onnxruntime#1173]
**Is your feature request related to a problem? Please describe.**
I try to use c-api as this [demo](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp), it is ok. but when I try to quantize squeeze.onnx to float 16, and then inference again, it report:

```
Unexpected input data type. Actual: (N11onnxruntime11NonOnnxTypeIfEE) , expected: (N11onnxruntime11NonOnnxTypeINS_9MLFloat16EEE)
```

I use the follow script to convert float32 model to float16:

```
import onnxmltools
from onnxmltools.utils.float16_converter import convert_float_to_float16

input_onnx_model = 'squeezenet/model.onnx'
output_onnx_model = 'squeezenet/model_fp16.onnx'

onnx_model = onnxmltools.utils.load_model(input_onnx_model)
onnx_model = convert_float_to_float16(onnx_model)
onnxmltools.utils.save_model(onnx_model, output_onnx_model)
```

can onnxruntime support fp16 inference?  any plan?

**System information**
0.4

**Describe the solution you'd like**
load fp 16 model, input float 32 data, then get float 32 result.

**Describe alternatives you've considered**
how to convert float32 input to float16 for inference?

**Comment by pranavsharma** [comment]
Here's a unit test that demonstrates conversion of float32 input to float16 - https://github.com/microsoft/onnxruntime/blob/2663b9c44381b30525ae6234e13ed25c69206d07/onnxruntime/test/framework/float_16_test.cc#L161. Let us know if this doesn't work for you.

**Comment by vsooda** [comment]
@pranavsharma thank you. it works
