### ISSUE TITLE
how to convert protobuf based onnx model to flat buffer based onnx model?

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#11739]
I saw there are another faltbuffer based schema of onnx, is there any way to convert a protobuf based onnx model to flat buffer based one?

**Comment by yuslepukhin** [comment]
This is called optimized model.  Optimized for the given hardware and version, compatibility not guaranteed. If you are looking for an equivalent, then, there is not a way. However, if you need an optimized model that you want to deploy and run then [check this](https://onnxruntime.ai/docs/performance/graph-optimizations.html#offline-mode). Unless specified, the extension would be `.ort`

**Comment by skottmckay** [comment]
The flatbuffer version of the model (an 'ORT format model') is for usage with a minimal ORT build. That build excludes a lot of things to minimise the binary size. This is an ORT specific thing though - the official format for onnx models is protobuf based.

https://onnxruntime.ai/docs/tutorials/mobile/

**Comment by jinfagang** [comment]
thank u! So from I can understand, this api helps serialized a flatbuffer format optimized model:

```
sess_options.optimized_model_filepath = "<model_output_path\optimized_model.onnx>"

```

if I want deploy on mobile platform, I can using this directly even onnxruntime doesn't built with protobuf enabled?

**Comment by fs-eire** [comment]
`sess_options.optimized_model_filepath` is for optimizing the model (like apply const folding, clean up unused nodes, remove duplicated `Reshape`s, fuse activations into conv or so on). However, the output is still an ".onnx" model.

".ort" model is a flatbuffer model. see [ort format](https://onnxruntime.ai/docs/reference/ort-format-models.html) for details.

**Comment by jinfagang** [comment]
@fs-eire thank u so much for your clear. I found this :+1: 
```
python -m onnxruntime.tools.convert_onnx_models_to_ort <onnx model file or dir>
```

then I wonder, does ort model can also using sess API to inference?

**Comment by fs-eire** [comment]
Yes. They are all the same for API.
