### ISSUE TITLE
How to give built DLLs different names?

### ISSUE THREAD

**Issue by Karnav123** [microsoft/onnxruntime#11744]
I am trying to build onnxruntime from the source. I am able to successfully build it and get onnxruntime.dll and other files. But I have a requirement to have a different name for the dll like onnxruntime_test.dll etc.

I have tried changing the target name in VS2019 "Configuration Properties -> General -> Target name for the onnxruntime. BUt now I am getting a linking error
Severity	Code	Description	Project	File	Line	Suppression State
Warning	LNK4070	/OUT:onnxruntime.dll directive in .EXP differs from output filename 'C:\workdir\MyOnnxruntime\onnxruntime\build\Windows\Release\Release\onnxruntimeNX.dll'; ignoring directive

I wanted to know what kind of changes I need to make to successfully build it to get a different named DLL.

**Comment by yuslepukhin** [comment]
Why not simply rename it after the build? Far simpler than tracking CMake files and finding all the places.

**Comment by Karnav123** [comment]
> Why not simply rename it after the build? Far simpler than tracking CMake files and finding all the places.

I think just renaming it doesn't work correctly when it is linked to another DLL that is loading it. Even after renaming dumpbin shows dependency as the original name that is onnxruntime.dll.

**Comment by snnn** [comment]
Should be already addressed in #11058

**Comment by moritzsur** [comment]
How did you manage to rename it?
