### ISSUE TITLE
QLinearAdd accuracy issue

### ISSUE THREAD

**Issue by developerChans** [microsoft/onnxruntime#11759]
**Describe the bug**

I implemented the operator QlinearAdd of ONNX_RUNTIME in C language. However, it was found that for a specific input value, a different result from onnx_runtime and 1 difference appeared.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- ONNX Runtime installed from (source or binary): 
- ONNX Runtime version: 1.8.1
- Python version: Anaconda Navigator 2.1.4, Jupyer Notebook 6.4.8, 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
- Visual Studio version (if applicable): not used
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- CUDA/cuDNN version: Not use
- GPU model and memory: Not use
 

**To Reproduce**
I implemented QlinearAdd in c language by looking at the operator document in onnx_runtime. But check the two input values ​​attached. When the A buffer is 91 and the B buffer value is 100, a small error occurs.

![image](https://user-images.githubusercontent.com/68864422/172334905-099d5384-e983-422b-a923-0aeef52d18a4.png)

We want to use the model by quantizing the onnx mobilenet model. Meanwhile, QlinearAdd encountered a problem.
This model is also attached.(it is not only qlinearAdd model)

Finally, I used onnx runtime with the following code in jupyter environment.

```
ort_session = onnxruntime.InferenceSession("dataset/make/model.onnx", providers=["CPUExecutionProvider"])
output = ort_session.run(None,{ort_session.get_inputs().name : input_numpy})
generate_testcase("dataset/output_0.data",output[0])
```

**Additional context**
.data (binary) file format
- data type (int32)
- data dim (int32)
- data shape(each dim) (int32)
data_buffer...

Also, what rounding rules exist in the onnx runtime? Or is the decimal handling method different in python and c?

**Comment by developerChans** [comment]
How Can I attach data file with model file..

**Comment by developerChans** [comment]
[add_dataset.zip](https://github.com/microsoft/onnxruntime/files/8851628/add_dataset.zip)

**Comment by developerChans** [comment]
[add_dataset.zip](https://github.com/microsoft/onnxruntime/files/8851646/add_dataset.zip)

**Comment by developerChans** [comment]
Before C code
`
#define roundNum(x) ((x) >= 0 ? (float32_t)((x) + 0.5):(float32_t)((x) - 0.5))

int QlinearAdd(...) {
            ...
            ...
            int32_t temp;
            int32_t A_value = A[A_index] - A_zeropoint;
            int32_t B_value = B[B_index] - B_zeropoint;
            temp = roundNum((A_scale * A_value + B_scale * B_value) / C_scale);
            if(temp + (int32_t)c_zero_point >= TYPE_MAX) {
                temp = TYPE_MAX;
            }
            else if(temp + (int32_t)c_zero_point <= DTYPE_MIN) {
                temp = TYPE_MIN;
            } else {
                temp = temp + (int32_t)c_zero_point;
            }
            C[C_index] = (TYPE)temp;
}
`

After C code

In addition to the existing accuracy problems, problems arose with other results.

The number of different 98(99) results that occurred before was 20 out of 75264.

However, if you change it like the suggested method, it was 100 out of 75264.

![image](https://user-images.githubusercontent.com/68864422/172761700-70d28211-d504-4879-bc8e-2e36a1c2d14c.png)


`
#define roundNum(x) ((x) >= 0 ? (float32_t)((x) + 0.5):(float32_t)((x) - 0.5))
int QlinearAdd(...) {
            ...
            ...
            int32_t temp;
            float32_t fixed_scale_A = A_scale/ C_scale;
            float32_t fixed_scale_B= B_scale / C_scale;
            float32_t vector_fixed_part = (float32_t)C_zeropoint - (fixed_scale_A * A_zeropoint + fixed_scale_B * B_zeropoint);

            float32_t temp1 = (float32_t)(A[A_index] * A_scale) + (float32_t)(B[B_index] * B_scale) + vector_fixed_part;
            if(temp1 >= (float32_t)TYPE_MAX) {
                temp = TYPE_MAX;
            }
            else if(temp1 <= (float32_t)TYPE_MIN) {
                temp = TYPE_MIN;
            } else {
                temp = roundNum(temp1);
            }
            C[C_index] = (TYPE)temp;
`

**Comment by yufenglee** [comment]
You roundNum implementation is not right. it actually round x.5 up, not to even. Please use this function:
https://en.cppreference.com/w/c/numeric/math/nearbyint

**Comment by developerChans** [comment]
Edited by referring to the link.

Existing accuracy problems have been resolved.

However, new problems arose in the new part.

This part is also 137.499992... If you follow the round rule of onnx_runtime, it should be 138, but the result of onnx_runtime is 137.

Only 5 out of the total of 75264 show different values, A and B values ​​are the same in all errors.

![image](https://user-images.githubusercontent.com/68864422/172787362-da3715c1-ef10-4968-8844-bb1fcaaa3ba6.png)


I used nearbyIntf...

```
#include <math.h>
#define roundNum(x) ((x) >= 0 ? (float32_t)((x) + 0.5):(float32_t)((x) - 0.5))
int QlinearAdd(...) {
            ...
            ...
            int32_t temp;
            float32_t fixed_scale_A = A_scale/ C_scale;
            float32_t fixed_scale_B= B_scale / C_scale;
            float32_t vector_fixed_part = (float32_t)C_zeropoint - (fixed_scale_A * A_zeropoint + fixed_scale_B * B_zeropoint);

            float32_t temp1 = (float32_t)(A[A_index] * fixed_scale_A ) + (float32_t)(B[B_index] * fixed_scale_B ) + vector_fixed_part;
            if(temp1 >= (float32_t)TYPE_MAX) {
                temp = TYPE_MAX;
            }
            else if(temp1 <= (float32_t)TYPE_MIN) {
                temp = TYPE_MIN;
            } else {
                temp = nearbyintf(temp1);
            }
            C[C_index] = (TYPE)temp;
}
```

This is gcc terminal capture image...
![image](https://user-images.githubusercontent.com/68864422/172788070-39a3cc03-c716-4e82-927c-53acbffccb36.png)

**Comment by yufenglee** [comment]
137.499992 is less than 137.5 and should be rounded to 137. 137.5 will be rounded to 138, so OnnxRuntime's result is correct. 
Please note that the rounding rule is "round to nearest, ties to even". for 137.499992, its nearest integer is 137, so it will be rounded to 137. For 137.5, its nearest integers are 137 and 138 (tie). Then round to even(138).

**Comment by developerChans** [comment]
Thank you. @yufenglee  I solved the problem in the following way. First, the rounding rule was modified through nearbyintf, and finally, it was converted from calculating in 32-bit to calculating in 64-bit format. For decimal arithmetic, I think 64-bit arithmetic should be preferred.
