### ISSUE TITLE
pip installed Transformer's benchmark.py has incorrect call to config_modifier.

### ISSUE THREAD

**Issue by raikonenfnu** [microsoft/onnxruntime#11750]
**Describe the bug**

I am trying to benchmark with onnxruntime's run_pytorch, but it throws me this error:
```bash
  File "/home/python3.9/site-packages/onnxruntime/transformers/benchmark.py", line 201, in run_pytorch
    config_modifier(config)
TypeError: 'ConfigModifier' object is not callable
```

Upon investigation of the offending line of code:
```py
        config = AutoConfig.from_pretrained(model_name, torchscript=torchscript, cache_dir=cache_dir)
        config_modifier(config)
```
It is trying to call on config_modifier directly, unlike the reference implementation on the main repo:
```py
        config = AutoConfig.from_pretrained(model_name, torchscript=torchscript, cache_dir=cache_dir)
        config_modifier.modify(config)
```
Where it calls the `modify` method.
[source](https://github.com/microsoft/onnxruntime/commit/fdce4fa6af437b0b822958ab47b3b8f77f9e14ae#L326)

**System information**
- Linux Ubuntu18.04
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.11.
- Python version:Python 3.9.12
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

Would be nice to get another release that fixes this! :)

**Comment by wangyems** [comment]
Please try nightly version:
cpu: https://test.pypi.org/project/ort-nightly/
cuda: https://test.pypi.org/project/ort-nightly-gpu/

**Comment by raikonenfnu** [comment]
@wangyems Thanks! Nightly pip install fixed this! closing this issue :)
