### ISSUE TITLE
Need to be able to explain predictions from ONNX models (aka need Shapley values from onnxruntime)

### ISSUE THREAD

**Issue by jim-meyer** [microsoft/onnxruntime#1176]
**Is your feature request related to a problem? Please describe.**
Many ML frameworks supported by ONNX provide [Shapley values](https://en.wikipedia.org/wiki/Shapley_value) . These values are import for explaining a model's predictions.
LightGBM optionally provides them if the [predict()](https://github.com/microsoft/LightGBM/blob/master/python-package/lightgbm/basic.py#L2288-L2324) function's pred_contrib parameter is set to True. The [shap](https://pypi.org/project/shap/) python package supports providing the values for most tree ensembles like XGBoost, sklearn, LightGBM.
But onnxruntime does not provide a way to get these values. 

**System information**
- ONNX Runtime version (you are using):
onnxruntime==0.4.0

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
I looked at using the 'shap' python package to get the Shapley values. But it doesn't support ONNX.

**Additional context**

**Comment by faxu** [comment]
Thanks for sharing the feature request. We'll discuss this and get back to you soon.

**Comment by faxu** [comment]
Explainability will not be part of the core ONNX Runtime. If you need to explain a model, you can try the resources/tools from https://github.com/interpretml/interpret-community. [Any model](https://github.com/interpretml/interpret-community#supported-models) can be explained using those tools provided there is a wrapper that exposes predict and predict_proba according to the scikit convention. There are notebook examples in that repo, and it can be used in conjunction with ONNX Runtime for explaining your model.

**Comment by MilesZhao** [comment]
Not sure whether it's too late. We just released the paper [ONNXExplainer](https://arxiv.org/abs/2309.16916) and it can explain an arbitrary neural network in ONNX ecosystem. We will release the code soon once it's approved.

**Comment by tadhgpearson** [comment]
I just read your paper - this is awesome, well done. I'd really look forward to using this. Can this also explain trees, or only neural networks?

**Comment by MilesZhao** [comment]
> I just read your paper - this is awesome, well done. I'd really look forward to using this. Can this also explain trees, or only neural networks?

Thank you for your interest in our work. Once our legal team approves the publishing of the codebase, I will share the link here. Currently, we do not support TreeSHAP which is used in explaining tree models. Nevertheless, we definitely on the way to add the support for TreeSHAP, also fast TreeSHAP and  linear TreeSHAP. If I am understanding correctly, ONNX does not support recursive functions. I am figuring out a way to convert the super complicated recursive process to iterative process. Stay tuned for further updates.

**Comment by tadhgpearson** [comment]
Cool, I look forward to it! I'm happy to help if you're stuck on unrolling the recursion - it is usually possible with a stack and a loop but it sometimes gets messy :D  We can continue this correspondence by email if you like - can I contact you at the email address in the header of your research paper?

**Comment by jlerouge** [comment]
Hello @MilesZhao ! Thanks for your interesting paper :)
Any chance for the code of ONNXExplainer to be published soon ?

**Comment by tadhgpearson** [comment]
FYI a colleage and I did look into this more deeply for trees, and I see why the feature request is declined. 

Specifically the ai.onnx.ml.Tree* operators generated from Spark using [Onnx ML Tools](https://github.com/onnx/onnxmltools), you would need to modify both the generator tools and the runtime to fit this in today. It would be a heavy lift and a disruptive change that is unlikely to be approved by project maintainers, reasonably so IMO.

The correct way to do this is to create a new custom operator, like ExplainedTreeEnsemble and then, 
1. fork Onnx ML tools to generate your new operator with the required output shape to return the Shapely Values, and 
2. add custom operator support in the runtime you need for this operator that traces the execution using the TreeSHAP algorithm and returns the shapely values in addition to the result of the tree
3. Share the source code for others to use and extend its support to other tools and runtimes

Once its supported it in a reasonable set of tools and runtimes you'd have a good case to support adding it to the standard opset.

Hope that clarifies a bit.
