### ISSUE TITLE
Inconsistent RPATH setting in Linux gpu package binaries

### ISSUE THREAD

**Issue by admayber** [microsoft/onnxruntime#11770]
**Describe the bug**
It is common practice to set the `RPATH` configuration of a Linux shared library to `$ORIGIN` so that the linker will look in the local directory. This is a requirement for one of our applications where we are bundling the ORT binaries together in a nuget package as opposed to installing them in the Linux system directories.

Most of the .so files in the official ORT release do have the `RPATH` set. However, `libonnxruntime_providers_cuda.so.1.*.*` and `libonnxruntime_providers_tensorrt.so.1.*.*` do not have it set. See the attached screenshot. Confirmed that this is true in 1.10.0 and forward, did not look earlier than that.

Since the RPATH is missing, if we try to link these libraries the linker will not find the core ORT libraries if they are in the same folder (as shown). The ORT libs would have to be installed into the Linux system directories for linking to work, which is not feasible in our scenario (nuget packaging).

**Urgency**
Urgency is low since we are able to use the `patchelf` utility to manually add the RPATH value. That said, it would be good to be able to remove this step and not have to modify the official binaries.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.10.0 and forward (possibly earlier as well)
- Python version: N/A
- Visual Studio version (if applicable): N/A 
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A 
- GPU model and memory: N/A

**To Reproduce**
Download and unpack any Linux gpu release `.tgz` file, then use `objdump` as shown in the screenshot to test for the presence of an RPATH config in the binaries.

**Screenshots**
![image](https://user-images.githubusercontent.com/44822281/172479786-517221fd-73ad-4734-bb51-7a2f87058d7d.png)

**Comment by snnn** [comment]
I believe they don't need it. See: https://github.com/microsoft/onnxruntime/blob/master/cmake/onnxruntime_providers.cmake#L315

libonnxruntime_providers_cuda.so is not linked to any onnxruntime shared libs. So it doesn't need a RPATH setting to locate onnxruntime libs.

**Comment by admayber** [comment]
Ah, my apologies - I have a mistake in the issue description. In addition to the ORT binaries we are also bundling some of the cuda binaries, which then causes a link failure.

**Comment by admayber** [comment]
@snnn no problem if this is just on the backlog for now, but should the issue be marked as open for clarity in case others run into it?
