### ISSUE TITLE
Runtime Error: module compiled against API version 0xf but this version of numpy is 0xd

### ISSUE THREAD

**Issue by alyserecord** [microsoft/onnxruntime#11771]
Anytime I import onnxruntime I receive the following import error. It does not prevent me from utilizing onnxruntime as it seems like it is related to numpy, but I am now confused if there is a certain numpy requirement for ort?

```
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xd
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError: <built-in function __import__> returned a result with an error set
```

Additional details:
- python version: 3.8.5
- numpy version: 1.19.1
- onnxruntime version: 1.11.0

**Comment by snnn** [comment]
> if there is a certain numpy requirement for ort?
Yes. It is specified the in package's requirements, pip can read it and use the information. And if the requirement was not satisfied,  onnxruntime python package won't be installed. So, there must be something wrong in your python environment.

**Comment by alyserecord** [comment]
I see https://github.com/microsoft/onnxruntime/blob/master/requirements.txt.in#L3 in the requirements file. Therefore, after reading https://github.com/microsoft/onnxruntime/pull/8130 I was assuming that any version of numpy was acceptable. Please clarify since it sounds like that is not the case? 

Also to clarify, even after receiving the error I as able to use onnxruntime with my onnx model, hence my confusion if this is a real issue or not. Also to note, I have no issue importing numpy in my environment, only onnxruntime.

**Comment by snnn** [comment]
[requirements.txt.in#L3](https://github.com/microsoft/onnxruntime/blob/master/requirements.txt.in#L3) is a template. It is not the actually content what was included in the release packages.
