### ISSUE TITLE
Question about ParallelFor

### ISSUE THREAD

**Issue by clin99** [microsoft/onnxruntime#1177]
Hi, just out of curiosity, I have a question about the [ParallelFor](https://github.com/microsoft/onnxruntime/blob/1a86421affa7a3cd677931a5b8e88cf81e9ee086/onnxruntime/core/common/threadpool.cc#L78). The `ParallelFor` function uses a `Barrier` to wait for  task completion. I was thinking the `Barrier` can be simply replaced by a `promise` and an `atomic variable` like this:

```cpp
std::atomic<unsigned> counter = static_cast<unsigned int>(total-1);
std::promise<void()> promise;
auto future = promise.get_future();
std::function<void(int32_t)> handle_iteration = [&counter, &promise](int iteration) {
  fn(iteration);
  if(counter.fetch_sub(1, std::memory_order_relaxed) == 1) {
    promise.set_value();
  }
};

for (int32_t id = 1; id < total; ++id) {
  Schedule([=, &handle_iteration]() { handle_iteration(id); });
}

fn(0);
future.wait();
```
To me this is more lightweight (no mutex and condition variable). Is there any reason (such as better performance) to use `Barrier`?

**Comment by snnn** [comment]
How could you implement future.wait(); without using mutex and condition variable(or similar things)?

**Comment by clin99** [comment]
Thanks for the answering!  Yes, I agree `future` should internally use something similar to the `mutex` and `condition_variable` for thread communication. But condition variable is more complicated as it allows you to notify others multiple times and this seems unnecessary in the `ParallelFor`. So I was wondering will this cause any performance difference?

**Comment by snnn** [comment]
if `future` is implemented upon `condition variable`, why do you think `condition variable` is more complex than `future`?

**Comment by clin99** [comment]
Hi @snnn , If `future` is implemented upon `condition variable`, then the `Barrier` is a good solution to me. I will close this issue.  Thanks for your answering!
