### ISSUE TITLE
A onnxruntime.dll from C:\windows\system32 is loaded from python cytpes.CDLL call while loading an x64 onnxruntime based dll, resulting in a crash

### ISSUE THREAD

**Issue by ankur2051** [microsoft/onnxruntime#11799]
**Describe the bug**
I am using onnxruntime library in my c++ project. The project is building fine and I am getting the libraries. While loading these libraries from Python ctypes, the system is crashing reporting %1 is not a valid win32 application.
The issue is while python is getting the onnxruntime.dll at c:\windows\system32. I am guessing that this DLL is part of some standard package may be of windows or Nvidia, but I don't want to remove it.
I cannot put the onnxruntime.dll (1.11.1) at the location of python.exe (although this would have worked) as this would be a solution specific to my system.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version:1.11.1
- Python version:3.7
- Visual Studio version (if applicable):2015
- GCC/Compiler version (if compiling from source): VC 14.0
- CUDA/cuDNN version:-
- GPU model and memory:-

**To Reproduce**
This is the exact issue https://github.com/microsoft/onnxruntime/discussions/5589 . Although i am looking for more generalized solution which can work on every system.

**Expected behavior**
I want that the incorrect 32 bit DLL should not be loaded from C:\windows\system32.

**Comment by snnn** [comment]
See: https://github.com/python/cpython/issues/85083

**Comment by siddjain** [comment]
Ran into same issue. In my case I am not loading onnxruntime from Python. I built a C++ DLL but when I try to register it, `regsvr32` fails with:

```
The module ""%1"" may not compatible with the version of Windows that you're running. Check if the module is compatible with an x86 (32-bit) or x64 (64-bit) version of regsvr32.exe
```

After much debugging I found that even though I have the correct x64 onnxruntime.dll in my application directory, it gets superseded by this:

```
dir c:\windows\system32\onnxruntime.dll
 Volume in drive C has no label.
 Volume Serial Number is 7E48-9F39

 Directory of c:\windows\system32

12/07/2019  02:08 AM             2,832 onnxruntime.dll
```

No idea how this DLL ended up on my system and the size is only 2kB. What is this DLL? How do I fix this please? I am not looking for a hacky solution. I checked the [link](https://github.com/python/cpython/issues/85083) but it does not help me as this scenario does not involve Python.

**Comment by siddhsql** [comment]
ONNX team - any update on above?

**Comment by snnn** [comment]
> why is onnxruntime.dll being installed under c:\windows\system32 and by whom?

By Windows team.  It is not a malware.  😄

> why does Windows prioritize c:\windows\system32 over the local path?

For safety. Windows always prioritize this folder over other folders in PATH env. However, if you put onnxruntime.dll into the same directory where your exe lives, that one will have the highest precedence.

> when I try to register it, regsvr32 fails with:

onnxruntime.dll doesn't have COM interface. So `regsvr32` doesn't work.

> How is this completed? 
If you want to use onnxruntime.dll in a python application, and the python version is >= 3.8, you need to read the discussions in https://github.com/python/cpython/issues/85083 . Most important, 
```
You can use add_dll_directory to add directories to the DLL load path (see https://docs.python.org/3/library/os.html#os.add_dll_directory). More information can be found e.g. here https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew
```
