### ISSUE TITLE
How to install a custom build of onnxruntime with CUDA as execution provider?

### ISSUE THREAD

**Issue by ae137** [microsoft/onnxruntime#11807]
### Discussed in https://github.com/microsoft/onnxruntime/discussions/11765

<div type='discussions-op-text'>

<sup>Originally posted by **ae137** June  7, 2022</sup>
I am trying to create a custom build of onnxruntime for C++ with CUDA execution provider and install it on Windows (the encountered issue is independent of the custom build). I have built the library as described [here](https://onnxruntime.ai/docs/build/eps.html#cuda), using the tag `v1.10.0`, CUDA 11.4, CMake 3.21.1 and MSVC 19.29. Building and testing works fine. 

However, when I switch to `build/Windows/Release` and type `cmake --install .`, the installation folder seems to be incomplete: There is a folder `include/onnxruntime/core/providers/cpu`, but none for `cuda`. In the source directory, there is a corresponding folder `onnxruntime/core/providers`, and I wonder which of its content should end up in the installation directory?

I have found a somewhat similar discussion for Linux [here](https://github.com/microsoft/onnxruntime/issues/4725), but there are no direct equivalents for the scripts on Windows. Is it possible to bundle the installation files with CMake, or required to use Nuget?</div>

The same issue actually arises on Linux, too, using tag `v1.10.0`, Cmake 3.22.1, g++ 11.2 and CUDA 11.4.

I noticed that the nuget package for ONNX Runtime with GPU only contains `cpu_provider_factory.h` and `tensorrt_provider_factory.h`, but no `cuda_provider_factory.h` (which existed in previous versions). Regarding libraries, there is one for `_cuda` and one for `_tensorrt`, tough. Having in mind that the package is called `Microsoft.ML.OnnxRuntime.Gpu`, does this suggest that it can be used for inference on a system with GPU and CUDA, but without TensorRT?

**Comment by skottmckay** [comment]
The GPU nuget package should be able to be used with CUDA. Using TensorRT is optional.

You shouldn't need the CUDA EP header any more as the ORT API has functions to enable the CUDA EP. See https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#using-v2-provider-options-struct

**Comment by nums11** [comment]
Closing as resolved.

**Comment by ae137** [comment]
Thanks for the reply, @skottmckay! It indeed works without that header.
