### ISSUE TITLE
android deployment

### ISSUE THREAD

**Issue by hossein1387** [microsoft/onnxruntime#1180]
**Is your feature request related to a problem? Please describe.**
I was able to cross compile onnxruntime for android using  steps provided in [https://github.com/microsoft/onnxruntime/labels/enhancement](BUILD.MD) I have also read #271. However I am still lost on how to use it. The following is the steps I took to cross compile for android:

1- `git clone --recursive https://github.com/Microsoft/onnxruntime`
2- `cd onnxruntime`
3- download android NDK and set `ANDROID_NDK` to point to the unzipped doanloaded file
4- download pre-compiled `protoc` and set `PROTOC_ANDROID` to point to binary protoc
5- while in `onnxruntime` directory, 'cd cmake'
6- `cmake -CMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DONNX_CUSTOM_PROTOC_EXECUTABLE=PROTOC_ANDROID`
7- After cmake successful execution, run `make` to build (takes ~20min)

I successfully completed all these steps but I don't know whats output to all of this? how can I use it in my app?

**System information**
- I used latest code on onnxruntime github repo
- I am using ubuntu 16LTS

**Comment by pranavsharma** [comment]
@daquexian can you please address this? thanks!

**Comment by pranavsharma** [comment]
@hossein1387 the current support for Android is not complete in the sense that onnxruntime only cross-compiles, but doesn't produce an artifact that can be used on android machines. This issue https://github.com/microsoft/onnxruntime/issues/919 is tracking full support for Android. Please follow that issue.

**Comment by pranavsharma** [comment]
Closing as per previous comment.

**Comment by daquexian** [comment]
@hossein1387 @pranavsharma Sorry for the late reply. onnxruntime can compile for Android and a c++ library and also binary files of tests will be produced. The binary files can be executed in adb shell. However, it needs some extra code like jni (Java Native Interface) to make onnxruntime library usable directly in an Android app.

**Comment by hossein1387** [comment]
Hi @daquexian, @pranavsharma thanks for your reply. As I said I am confused on what is the output of the build? When I compiled onnxruntime for Android, I did not find any .whl being generated (which is not a surprise to me).

**Comment by daquexian** [comment]
@hossein1387 We don't expect python installed on Android devices. The output is static libraries like libonnxruntime_common.a and libonnxruntime_session.a, and also binaries of tests, like onnxruntime_test_all. These binaries (like onnxruntime_test_all) can be executed in adb shell after pushing it to the device. 

To deploy onnxruntime in an Android app, an Android package (.aar) may be what you wanted. Some extra Java and JNI code are needed to get this .aar file, which currently not exists in onnxruntime and might be added in the progress of #919.

**Comment by hossein1387** [comment]
@daquexian Thanks a lot for clarification.
