### ISSUE TITLE
Issue while creating session for mt5 model 

### ISSUE THREAD

**Issue by OriAlpha** [microsoft/onnxruntime#11813]
Hallo, I have MT5 pretrained model, and model is converted to onnx. The convestion of the model works fine. But when creating the session it fails at

```
# initialize the C++ InferenceSession
sess.initialize_session(providers, provider_options, disabled_optimizers)
```
it fails without any error, as
`Process finished with exit code 135 (interrupted by signal 7: SIGEMT)` and `onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: SystemError : 2`

I am using latest version of onnxruntime==1.11.1
Any ideas to create session.

System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04

- ONNX Runtime installed from (source or binary): binary

- ONNX Runtime version: >>> onnxruntime.version '1.11.1'

- Python version: Python 3.8.13

**Comment by yuslepukhin** [comment]
This is not too much to by.

**Comment by OriAlpha** [comment]
Thanks @tianleiwu. This worked

**Comment by OriAlpha** [comment]
while inference i am facing some issues as 
`INVALID_ARGUMENT : Invalid Feed Input Name:pkv_95`

**Comment by tianleiwu** [comment]
@OriAlpha, you can open the graph with Netron to view graph input names, then use the correct input name in inference.

**Comment by OriAlpha** [comment]
Is there any example for inference of mt5/t5 model after conversion of model

**Comment by tianleiwu** [comment]
Example of T5 model used in beam search:
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/convert_beam_search.py

The output is an ONNX model with BeamSearch operator. It is very simple to do text generation, like
```
    inputs = {
        "input_ids": input_ids.cpu().numpy().astype(np.int32),
        "max_length": np.array([args.max_length], dtype=np.int32),
        "min_length": np.array([args.min_length], dtype=np.int32),
        "num_beams": np.array([args.num_beams], dtype=np.int32),
        "num_return_sequences": np.array([args.num_return_sequences], dtype=np.int32),
        "temperature": np.array([args.temperature], dtype=np.float32),
        "length_penalty": np.array([args.length_penalty], dtype=np.float32),
        "repetition_penalty": np.array([args.repetition_penalty], dtype=np.float32),
        "vocab_mask": vocab_mask,
    }
    
    result = session.run(None, inputs)
    output_sequences = result[0]
```
You need install https://test.pypi.org/project/ort-nightly-gpu/or https://test.pypi.org/project/ort-nightly/ to try it. Or wait for  the coming 1.12 release.

**Comment by OriAlpha** [comment]
To be clear, now its bit confusing. Firstly i converted model to onnx by, 
`python convert_to_onnx.py -m mt5_model/ --output converted_model -e -w --separate_encoder_and_decoder_init`
This creates 3 model separately as encoder, decoder and  decoder_sess_init. Now when create session do i have to combine all theses and pass inputs as you mentioned in above example.

**Comment by OriAlpha** [comment]
i was able to debug further on this issue. After model is converted to onnx, it fails to create session in `create_onnxruntime_session() `function in convert_to_onnx.py file. While model is loaded it fails as 
`onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Deserialize tensor onnx::MatMul_7360 failed.Invalid fd was supplied: -1`

**Comment by OriAlpha** [comment]
> To be clear, now its bit confusing. Firstly i converted model to onnx by, `python convert_to_onnx.py -m mt5_model/ --output converted_model -e -w --separate_encoder_and_decoder_init` This creates 3 model separately as encoder, decoder and decoder_sess_init. If i dont use `separate_encoder_and_decoder_init`. By `python convert_to_onnx.py -m mt5_model/ --output converted_model -e` it gives out issue as `AttributeError: 'NoneType' object has no attribute 'get_inputs'` this is in `verify_onnx()` func in `t5_encoder_decoder_init.py` Now when create session do i have to combine all theses and pass inputs as you mentioned in above example.

I thnik this is fixed installing nightly versions of onnx

**Comment by OriAlpha** [comment]
If you want to try model please use https://huggingface.co/google/mt5-large/tree/main

**Comment by nuruddin-jiru** [comment]
@OriAlpha, I am trying to convert my mT5 model to onnx and run inference as well. Could you help me out with how you edited the T5 code for a fine-tuned mT5 architecture? As well as how to run inference on it?

**Comment by OriAlpha** [comment]
Currently its buggy, When it work i can help.

**Comment by tianleiwu** [comment]
@[OriAlpha](https://github.com/OriAlpha), for T5 model, the final model is t5_small_beam_search.onnx as in the following example:
```
python convert_beam_search.py -m t5-small --model_type t5 --output t5_small_beam_search.onnx
```
So you only need one session. The script also has example for inference.

Later, I will modify the script to support mt5 as well.

**Comment by OriAlpha** [comment]
OK i tried to convert model, small t5 model works without any problem. When i use large t5 model its not saved in right way i guess. So far i got these errors:
`File format is not onnx.ModelProto (invalid typed array length: 4918704554) in 'encoder_decoder_init.onnx'` this error i say in netron. 
WIth onnx loading i found out: `Protobuf parsing failed.`

**Comment by OriAlpha** [comment]
My assumption is that, it fails in c++ api, which is in line 384 `onnxruntime_inference_collection.py`
`sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)`

**Comment by OriAlpha** [comment]
Thanks for your work, i will try to do some benchmarking and see how better is from pytorch framework.

**Comment by christine1729** [comment]
Hi @OriAlpha, hope your experiments went well. How is the speedup for mt5-base or mt5-large for onnx V torch? I'm recently trying to optimize inference for mT5 models. thanks!
