### ISSUE TITLE
Wrong output with GPT-NEO-1.3B using onnxruntime

### ISSUE THREAD

**Issue by Zapotecatl** [microsoft/onnxruntime#11810]
I am trying to run GPT-NEO-1.3B with onnxruntime in phyton, but I can't get the correct output.

**Enviroment**
OS: Windows 10 64 bits
IDE: PyCharm2021.3
PyTorch: 1.10.0+cu113
Transformers: 4.19.2
Onnx: 1.11.0
onnxruntime-gpu: 1.11.0

**To reproduce**

This is my example python code and it run correctly.
```
from transformers import GPTNeoForCausalLM, GPT2Tokenizer
model = GPTNeoForCausalLM.from_pretrained("EleutherAI/gpt-neo-1.3B")
tokenizer = GPT2Tokenizer.from_pretrained("EleutherAI/gpt-neo-1.3B")

prompt = "I want to order a Pizza"
input_ids = tokenizer(prompt, return_tensors="pt").input_ids
gen_tokens = model.generate(
    input_ids,
    do_sample=True,
    temperature=0.9,
    max_length=100,
)
gen_text = tokenizer.batch_decode(gen_tokens)[0]

print("------GPT-NEO-------")
print(gen_text)
```
Output

```
------GPT-NEO-------
I want to order a Pizza from you guys. The place I am ordering from will be at the top of my list (even if I don't have a place to stay, or even if I am just there to have it for delivery and eat it later).
What kind of pizza I want: Cheese + mushroom-crust, tomato-sauce, sausage, pepperoni, etc., plus a cup of soda. The food itself will be nice too. I'll be arriving from
```
I exported GPT-NEO with this command (I checked the model when it was exported):

`python -m transformers.onnx --model=EleutherAI/gpt-neo-1.3B --feature=causal-lm onnx/`

**My program with onnxruntime**

```
import torch.onnx
import onnxruntime as ort
from transformers import GPT2Tokenizer

options = ort.SessionOptions()
ort_session = ort.InferenceSession('C:\\Users\\Jorge\\PycharmProjects\\inteBERT\\onnx\\model.onnx', options)

tokenizer = GPT2Tokenizer.from_pretrained("EleutherAI/gpt-neo-1.3B")

prompt = "I want to order a Pizza"
tokens_ids = tokenizer(prompt, return_tensors="pt").input_ids

size_sequence = 128
size_tokens = tokens_ids.size(dim=1)
size_complement = size_sequence - size_tokens

input_ids = torch.cat((tokens_ids, torch.zeros(1, size_complement, dtype=torch.int64)), dim=1)
attention_mask = torch.cat((torch.ones(1, size_tokens, dtype=torch.int64), torch.zeros(1, size_complement, dtype=torch.int64)), dim=1)
args = {'input_ids': input_ids.numpy(), 'attention_mask': attention_mask.numpy()}

outputs = ort_session.run(None, args,)
res = outputs[0][0].argmax(axis=1)

# Decoding the model output
deco = tokenizer.decode(res)
print(deco)
```
**Wrong Output**
```
'm to be a new from

The
The gunned Adds Adds

 andThes
 Adds and

 Adds

The

s

 Adds�AAAandA
andThe andand
s
TheTheA

ATheA and
�
```
I haven't been able to find any documentation or a tutorial that can guide me to run gpt-neo correctly. Please, could someone give me some suggestion of my problem?

**Comment by tianleiwu** [comment]
I think you need export ONNX model with past state (past_key_values) for GPT-2 like model for performance consideration.

You can follow convert_to_onnx.py in
https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/transformers/models/gpt2 for onnx export.
You might need slight code change since the script is designed for GPT-2 model, but not GPT-NEO.

For text generation, you can try [BeamSearch](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/convert_beam_search.py), it need some modification to support sampling or greedy search etc.

**Comment by Zapotecatl** [comment]
Hi @tianleiwu , thanks alot for your help.

I am triying to run onnxruntime, but i'm a bit stuck. Let me show you.

1. I opened Visual Studio 2019 and I clone my project from repository: https://github.com/microsoft/onnxruntime.git
2. I used the power shell for developers. In the shell I run the command:
`.\build.bat --config Release --build_wheel --parallel --use_cuda --cuda_version 11.7 --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7" --cmake_generator "Visual Studio 16 2019" --skip_tests`
3. This command create the wheel: onnxruntime_gpu-1.12.0-cp39-cp39-win32.whl. I had to change the name for the installation: onnxruntime_gpu-1.12.0-cp39-none-any.whl
4. For install: 
`python -m pip install C:\Users\Jorge\source\repos\onnxruntime\build\Windows\Release\Release\dist\onnxruntime_gpu-1.12.0-cp39-none-any.whl`

I think all looks fine, however when I try to run in the cmd: 

`C:\Users\Jorge>python -m onnxruntime.transformers.convert_to_onnx -m gpt2 --model_class GPT2LMHeadModel --output gpt2.onnx -p fp32`

I get:

`C:\Users\Jorge\AppData\Local\Programs\Python\Python39\python.exe: No module named onnxruntime.transformers.convert_to_onnx`

![NotModule](https://user-images.githubusercontent.com/6554457/173736033-698b7db7-06cc-4f34-be7a-1ab2c4d76f08.jpg)

I checked my PATH but looks right as well.

**Comment by Zapotecatl** [comment]
Hi @tianleiwu , I have worked on the export of gpt neo, however, I get an error: **ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 5774820212**. Please, let me show my steps.

I added the MyGPTNeoForCausalLM in the gpt2_helper.py, essentially something like this:

```
class MyGPTNeoForCausalLM(GPTNeoForCausalLM):
    """Here we wrap a class for Onnx model conversion for GPTNeoForCausalLM with past state."""

    def __init__(self, config):
        super().__init__(config)
...

        return MyGPT2Model.post_process(result, self.config.num_layers)
		
MODEL_CLASSES = {
    "GPT2LMHeadModel": (MyGPT2LMHeadModel, "logits", True),
    "GPT2LMHeadModel_NoPadding": (MyGPT2LMHeadModel_NoPadding, "logits", False),
    "GPT2Model": (MyGPT2Model, "last_state", True),
	"GPTNeoForCausalLM": (MyGPTNeoForCausalLM, "logits", True),
}
```

There is only one parameter that differs: for GPT2 is config.n_layer and for GPTNEO is config.num_layers. I had to add my own ugly functions for export and tests (my knowledge in python is basic), for example:


```
#TODO(Jorge) I added this function, line: num_layer = config.num_layers
    @staticmethod
    def export_onnx_neo(
        model,
        device,
       ...
    ):
        """Export GPT-2 model with past state to ONNX model."""
        config: GPT2Config = model.config
        num_layer = config.num_layers
       ...
```
	   
I modified convert_to_onnx_neo.py in order to call my functions (export, tests). I get a model like this:



![01neopast](https://user-images.githubusercontent.com/6554457/184501404-5cbd9022-f648-4285-8d0b-cca38e57989f.jpg)



Next, I modified convert_generation.py so that it calls my functions when it executes the convert_gpt2_to_onnx function. 

The conversion to onnx with gpt2helper.export_onnx takes around 25 min, but the conversion with gpt2helper.optimize_onnx takes around 8 hours and I get a protobuf error: **ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 5774820212**.

Te error occurs here:

```
  if args.optimize_onnx or args.precision != Precision.FLOAT32:
        output_path = onnx_model_paths[str(args.precision) if args.precision != Precision.INT8 else "fp32"]

        print("*** args.optimize_onnx", output_path )
        logger.info(f"Optimizing model to {output_path}")
        gpt2helper.optimize_onnx(
```
		
Let me share the output:



![02neopast](https://user-images.githubusercontent.com/6554457/184501498-207789c0-bf47-4d64-b269-be9e70d5c07a.jpg)


![03neopast](https://user-images.githubusercontent.com/6554457/184501551-9356f31f-4e0d-4a3a-a3ab-ff579cdf3183.jpg)


Excuse me, my steps make sense?

**Comment by Zapotecatl** [comment]
I updated onnxruntime repo and I used `--use_external_data_format` in my command, then the error regarding the protobuf size was overcome. After, I did some ugly trick with the paths... Now, I have GPT NEO with good outputs and I can run it in C++!

I really realy aprecciate your help @tianleiwu. My final files are:
![gptneowindows](https://user-images.githubusercontent.com/6554457/184562693-6d08d00a-8806-42d9-a7f8-8caefad735bc.jpg)
I have a question, I did changes in order to use GPTNeoForCausalLM instead of GPT2LMHeadModel. 
```
helpers = {
            "default": Gpt2Helper,
            "beam_search_step": Gpt2BeamSearchHelper,
            "configurable_one_step_search": Gpt2BeamSearchHelper,
			"GPTNeoForCausalLM": Gpt2Helper,
        }
```
I understand the basic concept of beam search  (https://huggingface.co/blog/how-to-generate)  and I understand I am not using the beam_search_step and the configurable_one_step_search. My question are:

- What means beam_search_step and configurable_one_step_search? 
- What are the the advantages and disadvantages vs the default Gpt2Helper?

Thanks for the time!

**Comment by tianleiwu** [comment]
@Zapotecatl, sorry I missed the thread. For beam search, you might try [convert_generation](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/convert_generation.py) tool. It will create an onnx-graph with BeamSearch operators and a subgraph of GPT model. Since you have exported the GPT-NEO model, you can use --decoder_onnx to point to that onnx model, and create a model for beam search. The beam search parameter in the operator has similar meaning as in huggingface transformer beam search.
