### ISSUE TITLE
onnxruntime with Openvino build error.

### ISSUE THREAD

**Issue by viharigandrakota** [microsoft/onnxruntime#1187]
I am trying to build onnxruntime with openvino on Windows10. I am using openvino 2019 R1 version and I have cloned the main Repo. 
In the process of building I find a lot of errors in the following projects:
1. onnxruntime_providers_openvino
2. onnxruntime_graph
3. onnx_test_runner
4. onnxruntime_test_all

I am using visual studio 2017.

Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4251	'InferenceEngine::LayoutOffsetCounter::_dims': class 'std::vector<onnxruntime::NodeIndex,std::allocator<_Ty>>' needs to have dll-interface to be used by clients of class 'InferenceEngine::LayoutOffsetCounter'	
Project: onnxruntime_providers_openvino	
File : c:\program files (x86)\intelswtools\openvino\deployment_tools\inference_engine\include\ie_layouts.h	346	

Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4456	declaration of 'it' hides previous local declaration	
Project: onnxruntime_providers_openvino	
file: C:\Program Files (x86)\onnxruntime\onnxruntime\core\providers\openvino\openvino_execution_provider.cc	211	

And a lot more errors.

Any advice?

**Comment by snnn** [comment]
Are you talking #935 ?

**Comment by jywu-msft** [comment]
that PR is for linux. windows is not yet supported.

**Comment by jywu-msft** [comment]
FYI @smkarlap , @suryasidd

**Comment by viharigandrakota** [comment]
Thanks for the reply.

**Comment by jywu-msft** [comment]
I'm going to close this for now. CMakeLists.txt was updated to throw error if you try to build on Windows.
ORT + OpenVINO on Windows will be supported in the future.
