### ISSUE TITLE
How is QlinearConv calculated?

### ISSUE THREAD

**Issue by developerChans** [microsoft/onnxruntime#11883]
**Describe the bug**
I am implementing in C language referring to the Contrib Operator document of ONNX Runtime. However, the QLinearConv I implemented and the QLinearConv of ONNX Runtime show different output values, so I want to review whether the implementation is correct.

First, QLinearConv is implemented to operate in the following steps.
Step1) Convolution
Step2) Quantize

A part of the source code of Step1 is as follows.

STEP 1 : Convolution
TYPE(INT8, UINT8)
-> If there is a problem with the convolution algorithm, please point it out

```
static void conv_2d_TYPE_INT8(TYPE* X_buffer, int32* X_shape, Tensor* x_zero_point,
                                    int8* W_buffer, int32* W_shape, Tensor* w_zero_point,
                                    int32* Temp_buffer, int32* dilations, int32* strides, int32* pads){
    int32 height_dilations = 0;
    TYPE x_zp = ((TYPE*)x_zero_point->buffer)[0];
    int8 w_zp = ((int8*)w_zero_point->buffer)[0];

    for(int32_t W_height = 0; W_height < W_shape[2]; W_height++) {
        int32 Y_unit = 0;
        for(int32 X_height = -pads[0]; X_height < X_shape[2] + pads[2] - dilations[0] * (W_shape[2] - 1); X_height += strides[0]) {
            for(int32 X_width = -pads[1]; X_width < X_shape[3] + pads[3] - dilations[1] * (W_shape[3] - 1); X_width += strides[1]) {
                for(int32 W_width = 0; W_width < W_shape[3]; W_width++) {
                    **if(X_height + height_dilations < 0 || X_width + W_width * dilations[1] < 0 || X_height + height_dilations > X_shape[2] - 1 || X_width + W_width * dilations[1] > X_shape[3] - 1) {
                        Temp_buffer[Y_unit] += 0;
                    } else {
                        Temp_buffer[Y_unit] += (int32)(X_buffer[(X_height + height_dilations) * X_shape[3] + X_width + W_width * dilations[1]] - x_zp) * (int32)(W_buffer[W_height * W_shape[3] + W_width] - w_zp);
                    }**
                }
                Y_unit++;
            }
        }
        height_dilations += dilations[0];
    } 
}
```

A part of the source code of Step2 is as follows.

STEP 2 : Quantize
-> If the rounding rule or the clip rule is wrong, please point it out
-> dst array == y array

```
static void quantize_output_TYPE(int32 count, TYPE* dst, int32* src, float32 x_scale, float32 w_scale, float32 y_scale, TYPE y_z, int32 y_type){
    **float64 val = (float64)x_scale * (float64)w_scale / (float64)y_scale;**
    if( y_type == 2) {
        for(int32 i = 0; i < count; i++) {
            float32 rounded_val = **nearbyintf(**(float64)src[i] * val);            
            if(rounded_val + (int32)y_z <= 0) {
                dst[i] = (uint8)0;
            } else if(rounded_val  + (int32_t)y_z >= 255) {
                dst[i] = (uint8)255;
            } else {
                dst[i] = (uint8)((rounded_val) + y_z);
            }
        } 
    } else {
        for(int32 i = 0; i < count; i++) {
            float32 rounded_val = **nearbyintf((**float64)src[i] * val);            
            if(rounded_val + (int32)y_z <= -128) {
                dst[i] = (int8)-128;
            } else if(rounded_val  + (int32_t)y_z >= 127) {
                dst[i] = (int8)127;
            } else {
                dst[i] = (int8)((rounded_val) + y_z);
            }
        } 
    }
}
```

The following source code is a part of main that calls the functions of Step1 and Step2.

main code
- Temp_buffer : type - int32
- Temp_buffer is a temporary y_buffer for weight reduction after calculating as int32.

```
                for (int32 batch = 0; batch < batch_count; batch++) {
                    for(int32 feature = 0; feature < feature_count; feature++) {
                        int32 g = feature / feature_group;

                        for(int32 channel = 0; channel < channel_count; channel++) {
                            TYPE* X_buffer = X_flatten + X_unit * (channel_count * g + channel);
                            int8* W_buffer = W_flatten + W_unit * (channel_count * feature + channel);
                            // step1 : convolution data
                            **conv_2d_TYPE_INT8(X_buffer, X_shape, x_zero_point,
                                                    W_buffer, W_shape, w_zero_point,
                                                    _Temp_buffer_, dilations, strides, pads);**
                        }
                        
                        if(B_buffer != NULL) {
                            int32 bias = B_buffer[feature];
                            for(int32 i = 0; i < Y_unit; i++) {
                                Temp_buffer[i] += bias;
                            }
                        }
                        Temp_buffer += Y_unit;
                    }

                    X_flatten += X_unit * channel_count * group;
                }
                // step 2 : quantize
                **quantize_output_TYPE(Y_total, Y_buffer, Temp_buffer - Y_total, x_scale, w_scale, y_scale, y_zeropoint, y_zero_point->dtype);**
```

Here are the questions to ask:
1. In Step2 (Quantize), I used the nearbyintf() function of math.h to use the same rounding rule as the QLinearAdd Operator. Is it implemented correctly?
2. Am i using casting correctly when calculating different types of data? (for both Step1 and Step2)
3. In Step1 (Convolution), is there anything not specified in the Contrib Operator documentation? (Convolution algorithm refer to ONNX Operator document)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary): pip install onnx_runtime
- ONNX Runtime version: 1.11.1
- Python version: 3.8.10
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 9.4.0
- CUDA/cuDNN version: not use (only CPU)
- GPU model and memory: not use (only CPU)

**To Reproduce**
- Model used for testing: Quantized MobileNet(int8), Quantized MobileNet(uint8), Sub graph of Quantized MobileNet(int8), Sub graph of Quantized MobileNet(uint8)

**Expected behavior**
- (None)

**Screenshots**

For the operation test of QLinearConv, the sub graph of Quantized MobileNet was extracted and tested. It can be seen that different values ​​are output like screenshots as a result of calculation with the same image or random values.

A random value used as an input was generated in the following way.
`input_numpy = np.random.rand(1, 3, 224, 224).astype(np.float32)`

The image used as input used the imagenet sample image of the following link.
https://github.com/EliSchwartz/imagenet-sample-images

make random input code
`input_numpy = np.random.rand(1, 3, 224, 224).astype(np.float32)`

**QLINEARCONV (Input/Weight TYPE INT8)**
Each test case was run more than 50 times.
- random input (range 0 ~ 1)  --> SUCCESS
![image](https://user-images.githubusercontent.com/68864422/174199221-6f59b2a4-6163-4b63-ba6d-bc9e70522fb0.png)

- random input (range 0 ~ 10) --> almost success
![image](https://user-images.githubusercontent.com/68864422/174199616-8ff76415-657d-4d2f-8e93-e972cfcb55c8.png)

- random input (range 0 ~ 100)--> almost success
![image](https://user-images.githubusercontent.com/68864422/174199796-6d11e22d-e5ae-4e83-b087-5647b9b82cd7.png)

- imagenet sample (999 SUCCESS /1000) --> ONLY ONE CASE FAILED 
![image](https://user-images.githubusercontent.com/68864422/174200439-41e5f140-6639-4909-8f95-d3434aa358f6.png)

**QLINEARCONV (Input TYPE UNSIGNED INT8 / Weight TYPE INT8)**
Each test case was run more than 50 times.
- random input  (range 0 ~ 1)  --> SUCCESS
![image](https://user-images.githubusercontent.com/68864422/174201004-2ff762e6-3eee-49ee-bef9-d4b636c75c4d.png)

- random input (range 0 ~ 10)  --> 98 % failed
![image](https://user-images.githubusercontent.com/68864422/174200952-3d258eaf-cb9c-432e-8f99-330f80809566.png)

- random input (range 0 ~ 100) --> 98 % failed
![image](https://user-images.githubusercontent.com/68864422/174200905-10967e28-0859-4bbc-b0f2-88c71642686d.png)

- imagenet sample --> 98 % failed
![image](https://user-images.githubusercontent.com/68864422/174200815-5305f14f-9086-4dec-96b8-b2618300e523.png)

If the resulting values ​​are always output differently, i can debug my algorithm implementation by deciding that it is wrong, but only for a specific case, the two output values ​​are different, so I need help.

**Additional context**

External Question

**Comment by yufenglee** [comment]
Are you comparing the result of whole model or one operator? What's the criteria you used to determine if the result match or not?

And on x86-64 machines with AVX2 and AVX512 extensions, ONNX Runtime uses the VPMADDUBSW instruction for U8S8(uint8,int8) for performance. This instruction will saturate for large value:
https://onnxruntime.ai/docs/performance/quantization.html#when-and-why-do-i-need-to-try-u8u8. 

I would recommend you to use U8U8 to verify your implementation.

**Comment by developerChans** [comment]
First, answer the above question. We compare the result of whole model...

We also used the following criteria.

If the following conditions are satisfied, we judge that the values ​​are equal.
"difference < 1e-07 + 0.001 * fabs(compare_result)" 

But onnx_runtime and my_onnx difference is very big...

**Comment by developerChans** [comment]
@yufenglee 
I tried the method you recommended. However, U8U8 and S8S8 showed lower accuracy by reducing_range, and U8S8 did not improve much either. 
I want to make all calculation results of U8U8, U8S8, S8S8 like onnx_runtime. Maybe my QlinearConvolution calculation method is wrong or the rounding method is wrong?
Or is there an operation to adjust the range of input in onnx_runtime?

Additional question: The value was different when onnx_runtime was executed in the ARM environment and when it was not. Are ARM's results more accurate?

**Comment by yufenglee** [comment]
@developerChans, I would recommend you compare the result of one QLinearConv node (i.e., using unit test) instead of comparing result of the whole model, if you want to verify your implementation correctness? Rounding difference can propagate through the model, which may lead larger differences of the final result of the model.
