### ISSUE TITLE
ONNX Opset 3 is under development and not supported?

### ISSUE THREAD

**Issue by Rui-Ren** [microsoft/onnxruntime#11898]
**Describe the bug**
When using the below packages, the test case can pass.
```
onnx == 1.11.0
onnxruntime == 1.10.0
```

However, if upgrade the onnxruntime version from `1.10.0` to `1.11.0`, got the error like below:

**Opset 3 is under development and support for this is limited**

```
21:32:46.695499 183080 error rassert at line 195 of /src/private/dev/unidec/src/speech_lib_2/CNTKDNNEvalWrapper.h: false 

21:32:46.695531 183080 error CNTKCLibrary function CNTK_LoadModel returned code CNTK_ERROR_INTERNAL_ERROR with additional error info Exception: Load model from /tmp/pytest-of-root/pytest-249/test_conversion_and_decoding_R0/onnx/richlandpack/model failed:/home/nupharwrapperdev/onnxruntime/onnxruntime_src/onnxruntime/core/graph/model_load_utils.h:57 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::__cxx11::basic_string<char>, int>&, const onnxruntime::logging::Logger&, bool, const string&, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 3 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain ai.onnx.ml is till opset 2.
```

For the documentation, ONNX Opset3 is supported for ONNX, reference: https://github.com/onnx/onnx/blob/main/docs/Versioning.md#released-versions doc,

<html>
<body>

<html>
<body>

ONNX version | IR version | Opset version ai.onnx | Opset version ai.onnx.ml | Opset version ai.onnx.training
-- | -- | -- | -- | --
1.11.0 | 8 | 16 | 3 | 1

</body>
</html>

**Urgency**
Happens in `onnxruntime==1.11.0`

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- ONNX Runtime version: 1.11.0
- ONNX Version: 1.11.0
- Python version: 3.8.12
- CUDA/cuDNN version: 11.6
- GPU model and memory:  Tesla M60

**Question**
When releasing `onnxruntime==1.11.0`, we didnot update the version of onnx in this line
https://github.com/microsoft/onnxruntime/blob/f97bd38c4fe3b745d67f5fa05fa4b10f258fbfab/tools/ci_build/github/linux/docker/scripts/manylinux/requirements.txt#L6
, as such `onnx==1.10.2` is used here. If that could cause the issue described above.

**Comment by snnn** [comment]
The [requirements.txt](https://github.com/microsoft/onnxruntime/blob/f97bd38c4fe3b745d67f5fa05fa4b10f258fbfab/tools/ci_build/github/linux/docker/scripts/manylinux/requirements.txt#L6) doesn't indicate which ONNX version was used in ORT. The file is only for running tests after build.

**Comment by Rui-Ren** [comment]
Hi @snnn Thank you for your quick reply. Do you have any insights why it caused the error after upgrading to 1.11.0 and got 
```
The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. 
Current official support for domain ai.onnx.ml is till opset 2.
```
However, using onnxruntime=1.10.0, it can pass my tests. Thanks!

**Comment by t170815518** [comment]
I encounter the same issue, any insights?

**Comment by thiagocrepaldi** [comment]
Just as extra information, we probably will never support any ONNX opset older than 9 for ONNX + ORT.
