### ISSUE TITLE
Problem with onnxruntime-tools: No module named onnxruntime.transformers.convert_to_onnx and unexpected keyword argument 'example_outputs'

### ISSUE THREAD

**Issue by Zapotecatl** [microsoft/onnxruntime#11907]
Hi, I built the onnxruntime wheel onnxruntime_gpu-1.12.0-cp39-cp39-win_amd64.whl and installed it. However, when I try to run the command:
`C:\Users\Jorge>python -m onnxruntime.transformers.convert_to_onnx -m gpt2 --model_class GPT2LMHeadModel --output gpt2.onnx -p fp32`
I get:
`C:\Users\Jorge\AppData\Local\Programs\Python\Python39\python.exe: No module named onnxruntime.transformers.convert_to_onnx`

After, If I uninstall my wheel version and I install with: `pip install onnxruntime-gpu`, I get the version: onnxruntime_gpu-1.11.1-cp39-cp39-win_amd64.whl

With the gpu version 1.11.1 the command is recognized. However I get:

```
python -m onnxruntime.transformers.convert_to_onnx -m gpt2 --model_class GPT2LMHeadModel --output gpt2.onnx -p fp32
Arguments:Namespace(model_name_or_path='gpt2', model_class='GPT2LMHeadModel', cache_dir='.\\cache_models', output='gpt2.onnx', optimize_onnx=False, use_gpu=False, tolerance=0.0005, input_test_file='', precision=<Precision.FLOAT32: 'fp32'>, test_cases=1000, test_runs=10, verbose=False, use_external_data_format=False, use_int32_inputs=False, beam_size=4, ignore_eos=False, repetition_penalty=1, temperature=1, excluded_token_ids=None, length_penalty=1, do_sample=False, do_sample_top_p=0.95, do_sample_top_k=0, auto_mixed_precision=False, keep_io_types=False, io_block_list=[], op_block_list=[], node_block_list=[], force_fp16_initializers=False)
PyTorch Version:1.11.0+cu113
Transformers Version:4.20.0
Onnxruntime Version:1.11.1
Downloading: 100%...
Exporting ONNX model to gpt2_past.onnx
Shapes: input_ids=torch.Size([1, 1]) past=torch.Size([2, 1, 12, 1, 64]) output=torch.Size([1, 1, 50257]) present=torch.Size([2, 1, 12, 2, 64])
Traceback (most recent call last):
  File "C:\Users\Jorge\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Jorge\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Jorge\AppData\Local\Programs\Python\Python39\lib\site-packages\onnxruntime\transformers\convert_to_onnx.py", line 515, in <module>
    main()
  File "C:\Users\Jorge\AppData\Local\Programs\Python\Python39\lib\site-packages\onnxruntime\transformers\convert_to_onnx.py", line 306, in main
    gpt2helper.export_onnx(model,
  File "C:\Users\Jorge\AppData\Local\Programs\Python\Python39\lib\site-packages\onnxruntime\transformers\gpt2_helper.py", line 405, in export_onnx
    torch.onnx.export(model,
TypeError: export() got an unexpected keyword argument 'example_outputs'
```
Then:
**First question**: How can I force my wheel to be built in version 1.11 instead of 1.12?
**Second question**: How can I overcome the problem about
`TypeError: export() got an unexpected keyword argument 'example_outputs'?`
Thanks for your time and help!

**System information**
- Windows 10 64 bits
- - CMake 3.23.2
- ONNX Runtime version: 1.12
- Python version: 3.9.7
- Microsoft Visual Studio Community 2019 Versión 16.11.15
- CUDA/cuDNN version: 11.7
- GPU model and memory: NVIDIA GeForce RTX 2080

**To Reproduce**

1. I clone my project from repository: https://github.com/microsoft/onnxruntime.git
2. In the cmd I run the command:
`.\build.bat --config Release --build_wheel --parallel --use_cuda --cuda_version 11.7 --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7" --cmake_generator "Visual Studio 16 2019" --skip_tests`
This command create the wheel: **onnxruntime_gpu-1.12.0-cp39-cp39-win_amd64.whl**
3. Now, I go to the folder:
`cd C:\Users\Jorge\source\repos\onnxruntime\build\Windows\Release\Release\dist`
4. I can install with: 
`pip install onnxruntime_gpu-1.12.0-cp39-cp39-win_amd64.whl`
5. After, I had a little error: 
```ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
onnx 1.12.0 requires protobuf<=3.20.1,>=3.12.2, but you have protobuf 4.21.1 which is incompatible.
```
Then, I install: `pip install protobuf==3.20.1` and I execute the step 4 again.
6. I run: `pip list | findstr onnx`
I get: 
```
onnx               1.12.0
onnxruntime-gpu    1.12.0
```
7. The problem is when I run:
`C:\Users\Jorge>python -m onnxruntime.transformers.convert_to_onnx -m gpt2 --model_class GPT2LMHeadModel --output gpt2.onnx -p fp32`
I get:
`C:\Users\Jorge\AppData\Local\Programs\Python\Python39\python.exe: No module named onnxruntime.transformers.convert_to_onnx`

**Comment by tianleiwu** [comment]
Please try the following:
```
pip uninstall onnxruntime onnxruntime-gpu
pip install -i https://test.pypi.org/simple/ ort-nightly-gpu
python -m onnxruntime.transformers.models.gpt2.convert_to_onnx --help
```

**Comment by Zapotecatl** [comment]
Thanks @tianleiwu , that works!
