### ISSUE TITLE
Implement LayerNormalization kernel for opset version 17

### ISSUE THREAD

**Issue by garymm** [microsoft/onnxruntime#11916]
ai.onnx version 17 added LayerNormalization as a function.
ORT already has a LayerNormalization kernel but:
* It's not registered for version 17, and
* I think it needs to be updated to be compatible with the standard op schema (e.g., it doesn't consider the attribute `stash_type`).

See also https://github.com/onnx/onnx/issues/4295

CC @wschin

**Comment by pranavsharma** [comment]
Work done here https://github.com/microsoft/onnxruntime/commit/394c249c7cd2634a74f1eef55a108a6f5a1bff54
