### ISSUE TITLE
Percentile/entropy calibration not working for quantizing Resnet-50/MobileNet

### ISSUE THREAD

**Issue by regisss** [microsoft/onnxruntime#11928]
**Describe the bug**
The [image classification CPU example](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/quantization/image_classification/cpu) of `onnxruntime-inference-examples` returns an error with `calibrate_method=CalibrationMethod.Entropy` or `calibrate_method=CalibrationMethod.Percentile` and `quant_format=QDQ`.

Here is the error I got with Resnet-50:
```shell
Traceback (most recent call last):
  File "run.py", line 144, in <module>
    main()
  File "run.py", line 125, in main
    quantize_static(
  File "/home/regis/HuggingFace/dev/venv/lib/python3.8/site-packages/onnxruntime/quantization/quantize.py", line 290, in quantize_static
    quantizer.quantize_model()
  File "/home/regis/HuggingFace/dev/venv/lib/python3.8/site-packages/onnxruntime/quantization/qdq_quantizer.py", line 114, in quantize_model
    self.quantize_tensors()
  File "/home/regis/HuggingFace/dev/venv/lib/python3.8/site-packages/onnxruntime/quantization/qdq_quantizer.py", line 169, in quantize_tensors
    raise ValueError(
ValueError: Quantization parameters are not specified for param resnetv17_dense0_fwd.In static mode quantization params for inputs and outputs of nodes to be quantized are required.
```

It seems no data were collected for the output of the model.

**I get the same error with the MobileNet model of the same example**.

**Urgency**
I think this is pretty urgent because the only way to statically quantize such models at the moment is to use MinMax calibration.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- ONNX Runtime installed from (source or binary): installed with `pip`
- ONNX Runtime version: 1.11.1
- Python version: 3.8.10
- Visual Studio version (if applicable): /
- GCC/Compiler version (if compiling from source): /
- CUDA/cuDNN version: not using GPU
- GPU model and memory: not using GPU

**To Reproduce**
I ran [this official example](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/quantization/image_classification/cpu) with two small modifications to be able to use another calibration method:

- add `from onnxruntime.quantization import CalibrationMethod`
- add the argument `calibrate_method=CalibrationMethod.Entropy` to `quantize_static` on line 111

The command: `python run.py --input_model resnet50-v1-13.onnx --output_model resnet50-v1-13_quant.onnx --calibrate_dataset ./test_images/ --quant_format QDQ` returns the error above.

**Expected behavior**
Quantization of these models should work with percentile/entropy calibration.

**Additional context**
I tried with the Hugging Face implementation of Resnet-50 and got the same issue, so I do not think it is related to these models in particular.

**Comment by allen123wzh** [comment]
Same problem here, only MinMax calibration works, either Entropy or Pencentile would yield the same error

**Comment by yufenglee** [comment]
The bug was fixed with #12089. Could you please try with nightly build and report back if you still see the issue? Thanks

**Comment by regisss** [comment]
> The bug was fixed with #12089. Could you please try with nightly build and report back if you still see the issue? Thanks

Thanks for this fix, it works fine with a nightly build!

However I get extremely bad accuracy with entropy calibration. I am going to investigate it a bit more and will create a new issue if needed.

**Comment by JasonMaojinsong** [comment]
> 

Hi @regisss ,  the accuracy is very bad for entropy calibration on my site too,  did you resolve it ?  thanks

**Comment by regisss** [comment]
> > 
> 
> Hi @regisss , the accuracy is very bad for entropy calibration on my site too, did you resolve it ? thanks

Hi @JasonMaojinsong, I took a look at the implementation of entropy calibration and I think it's wrong but I have not had time to fix it and open a PR yet.

**Comment by irasin** [comment]
Hi, @JasonMaojinsong 
I found the same problem when I quantize my model. The range of conv output is very wide, so the scale is very large, e.g. 0.449, so the qdq error is very large because of the large scale factor, which makes the final precision drops a lot.

I wonder what should we do to avoid the presicion lost when we come across big scale factor?
