### ISSUE TITLE
Wrong header included for CoreML provider factory

### ISSUE THREAD

**Issue by carsonswope** [microsoft/onnxruntime#11973]
In the latest macOS release (`onnxruntime-osx-arm64-1.11.1`) the header `coreml_execution_provider.h` is included. I think that the correct header to include is `coreml_provider_factory.h`.

Apologies if this is totally wrong, I'm pretty new to onnx-runtime. Anyway, here's my reasoning:

I needed to call `OrtSessionOptionsAppendExecutionProvider_CoreML` to add the CoreML EP to my session options pointer. Indeed the function is exported from `libonnxruntime.dylib` (i.e. run `nm -gU libonnxruntime.dylib`), but the only header it is declared in is `coreml_provider_factory.h`. I had to add `#include <coreml_provider_factory.h>`, then I could call the function because I was already linking to `libonnxruntime.dylib`. Also, `coreml_execution_provider.h` includes header files that seem to be internal to onnxruntime and not part of the public API.

I guess this would be a change to `copy_strip_binary.sh`, like what happened in https://github.com/microsoft/onnxruntime/pull/10675 , but just a different file name. Happy to make a PR for this, just would like some confirmation that it's correct first.

Thanks!

**Comment by faxu** [comment]
CC @edgchen1

**Comment by edgchen1** [comment]
@carsonswope I think you are right. coreml_provider_factory.h should be in the released header files instead of coreml_execution_provider.h. Thanks for the find! PRs are welcome.
