### ISSUE TITLE
build for iOS error: ld: library not found for -latomic

### ISSUE THREAD

**Issue by JuntaoLiu01** [microsoft/onnxruntime#12002]
**Describe the bug**
ld: library not found for -latomic
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 11.6.2
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.10.0
- Python version: 3.8.12
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
git clone --depth=1 --branch v1.10.0 https://github.com.cnpmjs.org/microsoft/onnxruntime.git
./build.sh --config MinSizeRel --use_xcode --ios --ios_sysroot iphoneos --osx_arch arm64 --apple_deploy_target 12.0

**Comment by edgchen1** [comment]
Can you please provide more build output?

FWIW, these build.py options worked in a recent CI build:
`--ios --use_xcode --build_apple_framework --use_coreml --apple_deploy_target=11.0 --config=Release --ios_sysroot=iphoneos --osx_arch=arm64`
