### ISSUE TITLE
Update the ROIAlign op to the current ONNX spec

### ISSUE THREAD

**Issue by samurdhikaru** [microsoft/onnxruntime#12015]
**Is your feature request related to a problem? Please describe.**
The ROIAlign op in ONNX Runtime seems to be still compliant to the older [RoiAlign-10](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#RoiAlign-10) ONNX spec. It would be really helpful if this is updated to conform to the [newer ROIAlign spec](https://github.com/onnx/onnx/blob/main/docs/Operators.md#RoiAlign).

The difference between the two versions is that there is an additional attribute in the newer spec called `coordinate_transformation_mode` which allows for the input coordinate shift behavior to be user-configured. This is somewhat frustrating because the current ONNX Runtime implementation [chooses NOT to do half-pixel alignment,](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cuda/object_detection/roialign_impl.cu#L109) which is the non-default behavior according to the newer spec. So there doesn't seem to be a straightforward way to emulate the default behavior of the current ROIAlign spec on ONNX Runtime.

**System information**
- ONNX Runtime v1.11.1 

**Describe the solution you'd like**
It seems that bringing the ROIAlign op to be conformant to the new spec is quite straightforward: there is a boolean `continuous_coordinate` which is [hard-coded to be `false`](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cuda/object_detection/roialign_impl.cu#L109); this could be set to a user-provided boolean attribute instead.

**Comment by edgchen1** [comment]
should be fixed by #12036. thanks @jywu-msft!
