### ISSUE TITLE
Test failed when building wheel

### ISSUE THREAD

**Issue by luvclear** [microsoft/onnxruntime#1203]
I met a problem when running  ./build.sh --config RelWithDebInfo --build_wheel 
result:
3:      Models: 35
3:      Total test cases: 35
3:              Succeeded: 24
3:              Not implemented: 0
3:              Failed: 11
3:                      Other reason:11
3:      Stats by Operator type:
3:              Not implemented(0):
3:              Failed:
3: Failed Test Cases:
3/3 Test #3: onnx_test_pytorch_operator .......   Passed    0.33 sec

67% tests passed, 1 tests failed out of 3

Total Test time (real) =  17.44 sec

The following tests FAILED:
          1 - onnxruntime_test_all (Failed)
Errors while running CTest
Traceback (most recent call last):
  File "/home/onnxruntime/tools/ci_build/build.py", line 863, in <module>
    sys.exit(main())
  File "/home/onnxruntime/tools/ci_build/build.py", line 820, in main
    args.use_tvm, args.use_tensorrt, args.use_ngraph)
  File "/home/onnxruntime/tools/ci_build/build.py", line 519, in run_onnxruntime_tests
    cwd=cwd, dll_path=dll_path)
  File "/home/onnxruntime/tools/ci_build/build.py", line 179, in run_subprocess
    return subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/ctest', '--build-config', 'RelWithDebInfo', '--verbose']' returned non-zero exit status 8

so how can i deal with it?

**Comment by jywu-msft** [comment]
is the test failing consistently or it's an intermittent failure?
to disable running tests when building the wheel, use the following build command

./build.sh --config RelWithDebInfo --build_wheel --update --build

**Comment by luvclear** [comment]
> is the test failing consistently or it's an intermittent failure?
> to disable running tests when building the wheel, use the following build command
> 
> ./build.sh --config RelWithDebInfo --build_wheel --update --build

the test failed intermittently
i tried to disable the test using that command and build complete 
but whether it would work well if i disable the test?

**Comment by skottmckay** [comment]
It should work. 

Which test in onnxruntime_test_all fails and why? You'd have to scroll back up in the test output to find the information.

**Comment by luvclear** [comment]
> It should work.
> 
> Which test in onnxruntime_test_all fails and why? You'd have to scroll back up in the test output to find the information.
[  FAILED  ] 1 test, listed below:
1: [  FAILED  ] ContribOpTest.StringNormalizerTest
1:
1:  1 FAILED TEST
1/4 Test #1: onnxruntime_test_all .............***Failed   15.28 sec
...
  Models: 80
2:      Total test cases: 80
2:              Succeeded: 57
2:              Not implemented: 0
2:              Failed: 23
2:                      Other reason:23
2:      Stats by Operator type:
2:              Not implemented(0):
2:              Failed:
2: Failed Test Cases:
2/4 Test #2: onnx_test_pytorch_converted ......   Passed    0.82 sec

it did not show the reason for the failure

**Comment by jywu-msft** [comment]
I believe that test fails due to missing locale on your system.

From the System Requirements section in https://github.com/microsoft/onnxruntime/blob/master/README.md

Certain operators makes use of system locales. At the very least you will need to install English language package and configure en_US.UTF-8 locale.
For Ubuntu install language-pack-en package
Run the following commands:
locale-gen en_US.UTF-8
update-locale LANG=en_US.UTF-8
Follow similar procedure to configure other locales on other platforms.

**Comment by luvclear** [comment]
> I believe that test fails due to missing locale on your system.
> 
> From the System Requirements section in https://github.com/microsoft/onnxruntime/blob/master/README.md
> 
> Certain operators makes use of system locales. At the very least you will need to install English language package and configure en_US.UTF-8 locale.
> For Ubuntu install language-pack-en package
> Run the following commands:
> locale-gen en_US.UTF-8
> update-locale LANG=en_US.UTF-8
> Follow similar procedure to configure other locales on other platforms.

 ok i'll try ,thanks

**Comment by faxu** [comment]
@luvclear were you able to resolve this?

**Comment by pranavsharma** [comment]
@luvclear did you try setting the locale as commented before?

**Comment by faxu** [comment]
Closing the issue. Please reactivate if issue still persists.

**Comment by ZeroCool11000** [comment]
Ok i was able to build onnxruntime with the comment like 

./build.sh --use_cuda --cudnn_home /usr --cuda_home /usr/local/cuda --use_tensorrt --tensorrt_home /usr/lib/x86_64-linux-gnu/ --update --build

it works with --update --build but without it am getting this kind of error

**Comment by code-wangshuyi** [comment]
it works with apt-get install language-pack-en on ubuntu 18.04

**Comment by hoangmt** [comment]
> it works with apt-get install language-pack-en on ubuntu 18.04

It works like a charm. I install it inside a docker container.

**Comment by vinnfeng** [comment]
> 它适用于 apt-get install language-pack-en 在 ubuntu 18.04

亲测有效，大家可以试试
