### ISSUE TITLE
Fp16 Resnet50 Model cannot run in cuda provider. 

### ISSUE THREAD

**Issue by Magnus1cheng** [microsoft/onnxruntime#12045]
**Describe the bug**
Following codes import pretrained resnet50 model from torchvision and use onnxmltools tools to convert into half type model, then run on cuda EP.
Codes can run without any error in onnxruntime v1.10, but can't run after onnxruntime v1.11
Testing environments are all the same (including dependency packages' versions).

```
import io
import numpy as np
import torchvision

from torch import nn
import torch.utils.model_zoo as model_zoo
import torch.onnx
import torch.nn as nn
import torch.nn.init as init
import onnx
from onnx import load_model, save_model
import onnxruntime
from onnxmltools.utils import float16_converter

torch.manual_seed(0)
np.random.seed(0)
torch_model = torchvision.models.resnet50(pretrained=True).eval()
batch_size = 10  

map_location = lambda storage, loc: storage
if torch.cuda.is_available():
    map_location = None

torch_model = torch_model.cuda().half()
data = np.random.rand(batch_size,3,224,224).astype(np.float32)
x = torch.from_numpy(data).cuda().half()
torch_out = torch_model(x)

torch.onnx.export(torch_model,               
                  x,                        
                  "resnet.onnx",             
                  export_params=True,       
                  opset_version=10,          
                  do_constant_folding=True,  
                  input_names = ['input'],   
                  output_names = ['output'], 
                  dynamic_axes={'input' : {0 : 'batch_size'},    
                                'output' : {0 : 'batch_size'}})
onnx_fp32_model = load_model("resnet.onnx")
onnx_fp16_model = float16_converter.convert_float_to_float16(onnx_fp32_model,keep_io_types=True)
save_model(onnx_fp16_model, "resnet_fp16.onnx")

def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

ort_session = onnxruntime.SessionOptions()
ort_session.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_ENABLE_EXTENDED
session = onnxruntime.InferenceSession("resnet_fp16.onnx", ort_session,providers=['CUDAExecutionProvider'])
ort_inputs = {session.get_inputs()[0].name: to_numpy(x)}
ort_outs = session.run(None, ort_inputs)

print("diff is:",to_numpy(torch_out)-ort_outs[0])
np.testing.assert_allclose(to_numpy(torch_out), ort_outs[0], rtol=1e-03, atol=1e-05)
print("Exported model has been tested with ONNXRuntime, and the result looks good!")
```
Error message in ORT v1.11.0:
`
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /home/cheng.chen/git/onnxruntime/onnxruntime/core/optimizer/transformer_memcpy.cc:374 bool onnxruntime::TransformerMemcpyImpl::ProcessInitializers(const onnxruntime::KernelRegistryManager&, const InitializedTensorSet&) status.IsOK() was false. Failed to find kernel for FusedConv(1) (node Conv_8). Op with name (Conv_8) and type (FusedConv) kernel is not supported in CUDAExecutionProvider. Encountered following errors: (Found kernel for Op with name (Conv_8) and type (FusedConv) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented only for the following types (tensor(float),), but the node in the model has the following type (tensor(float16)) 
`

**Urgency**
Resnet50 is a simple and basic model, so same error might happen in other complex models.

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: v1.11.0
- Python version: Python3.7
- CUDA/cuDNN version: CUDA 11.4, cudnn 8
- GPU model and memory: Nvidia GTX1080Ti

**To Reproduce**
Python3 to run above codes

**Expected behavior**
Exported model has been tested with ONNXRuntime, and the result looks good!

**Additional context**
This might be same issue to [#11768](https://github.com/microsoft/onnxruntime/issues/11768)
I tried method like https://github.com/microsoft/onnxruntime/issues/11768#issuecomment-1150221102 says, but still no pass.
Not sure if this is related to the onnxmltools.
Tried to debug, found this might relate to the graph that ORT modified internally. In v1.10, no FusedConv Nodes are added, but in v1.11, they are added. However, there are no FusedConv Op implemention for half type. Per https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/contrib_ops/cuda/fused_conv.cc#L117

**Comment by hariharans29** [comment]
Thanks for reporting. Looks like the actual bug is that the fusion (to make the Conv node + some other node(s)) shouldn't happen if there is no support for that kernel in the first place. Whether we can enhance the FusedConv kernel to support fp16 is the next question. 

The default optimization level is ALL, until this is fixed, please make it BASIC and try running the model. It shouldn't trigger this optimization.

**Comment by hariharans29** [comment]
Interestingly, there is a check in the FusedConv optimizer to ensure that the data type is float before going ahead with the fusion - 
https://github.com/microsoft/onnxruntime/blob/f468ea40e59c6f3d7ca06c3d0c0b6d325c185602/onnxruntime/core/optimizer/conv_activation_fusion.cc#L79. This was there in 1.10, the only refacotring that took place in 1.11 is the change to make the ConvActivationFusion a SelectActionTransformer - https://github.com/microsoft/onnxruntime/commit/9e7d7a9e97c979c3b32fac4d54324e3f9c6b1d40. #edgchen1 - Not sure if this inadvertently introduced a regression in 1.11

**Comment by Magnus1cheng** [comment]
Thank you for fixing this. I also did some debug before but got no clue how did ORT generate FusedConv Node. Can you explain to me a little about how does ORT optimize or modify the graph when get a `.onnx` file. I thought ORT just add everything that the `.onnx` file has, but apparently it did many complex modification to the graph, where's the entry point to the graph optimization/modification. Thank you so much.

**Comment by hariharans29** [comment]
ORT has in-memory graph optimizations that fuse together nodes and execute them in one-shot where it makes sense logically. For example, combine Conv + Add + Relu = FusedConv. This has to happen ONLY if there is a kernel for FusedConv. There is a kernel for FusedConv but only for the float32 data type. Until we add support for the other types, we must ensure that the fusion does not happen in lieu of the missing implementation for the fusion.

**Comment by OvervCW** [comment]
> The default optimization level is ALL, until this is fixed, please make it BASIC and try running the model. It shouldn't trigger this optimization.

What do you mean by ALL/BASIC? Where should that be configured?

**Comment by deepernewbie** [comment]
so = onnxruntime.SessionOptions()
    if use_fp16:
        so.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_ENABLE_BASIC
    else:
        so.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_ENABLE_ALL
    sess = onnxruntime.InferenceSession(model_path,providers=EP_list,sess_options=so)

**Comment by deepernewbie** [comment]
> > The default optimization level is ALL, until this is fixed, please make it BASIC and try running the model. It shouldn't trigger this optimization.
> 
> What do you mean by ALL/BASIC? Where should that be configured?
> 
> **Update:** Never mind, found that it can be configured in Triton through the `level` parameter: https://github.com/triton-inference-server/onnxruntime_backend#model-config-options

so = onnxruntime.SessionOptions()
if use_fp16:
    so.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_ENABLE_BASIC
else:
    so.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_ENABLE_ALL
sess = onnxruntime.InferenceSession(model_path,providers=EP_list,sess_options=so)
