### ISSUE TITLE
Eager mode code gen support sequence of ops with multiple using attributes

### ISSUE THREAD

**Issue by WilBrady** [microsoft/onnxruntime#12055]
**Is your feature request related to a problem? Please describe.**
aten::equal has been handwritten for eager mode. It can almost be generated by specifying the following in atenops.py:
`"aten::equal": Not(ReduceMin(Cast(Equal("self", "other"), 6), keepdims=0))`

**Describe the solution you'd like**
The generator can create the code from the mapping or similar mapping listed above.

However, this fails for 2 reasons
1. the reuse of `NodeAttributes attrs` which is needed for `Cast` and `ReduceMin`
2. Returning of a bool type (not a tensor)

If the generator can be modified to handle this then the handwritten code can be removed.

This issue is for fixing NodeAttributes attrs.

Note: I have not measured the impact on making these changes for supporting other aten->onnx ops mapping so reward for these changes should be measured before investing.

**Comment by WilBrady** [comment]
PR the hand implements `aten::equal` https://github.com/microsoft/onnxruntime/pull/12020

**Comment by msftlincoln** [comment]
PR #12111 addresses issue 1.  Suggest we break this feedback into two separate issue items for the two separate issues called out.
