### ISSUE TITLE
onnx optimization distilbert failure

### ISSUE THREAD

**Issue by kamalkraj** [microsoft/onnxruntime#12064]
**Describe the bug**
onnx optimization of distilbert model runtime failure with batch size > 1. 
```python
InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running EmbedLayerNormalization node. Name:'EmbedLayerNormalization_0' Status Message: input_ids and position_ids shall have same shape
```

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: (onnx==1.12.0, onnxconverter-common==1.9.0, onnxruntime==1.11.1, onnxruntime-tools==1.7.0, tf2onnx==1.11.1 )
- Python version: 
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.1, V11.1.105
- GPU model and memory: Tesla T4

**To Reproduce**
https://colab.research.google.com/drive/1san0_xGSO-97WJOqtgOjn-i-ezsU9fYp?usp=sharing

**Expected behavior**
Model should work with all the batch size

**Screenshots**
![Screenshot 2022-07-01 at 12 37 35 PM](https://user-images.githubusercontent.com/17096858/176842801-c54bfc0a-ee56-4cde-84c6-706015a9c168.png)

**Comment by wschin** [comment]
@justinchuby, could you please take a look? I assume it's related to model optimization.

**Comment by tianleiwu** [comment]
Looks like a bug in EmbedLayerNormalization fusion. 

@[kamalkraj](https://github.com/kamalkraj), could you try disable the fusion by setting the following to **False**:
https://github.com/microsoft/onnxruntime/blob/0292356bd7ce5b379be8ee9820bfbf4fd321ebc5/onnxruntime/python/tools/transformers/fusion_options.py#L23

**Comment by kamalkraj** [comment]
@tianleiwu 
With `enable_embed_layer_norm` False, works fine. No error.

**Comment by vgrabovets** [comment]
So, maybe it is time to fix it?

**Comment by tianleiwu** [comment]
@vgrabovets, I think it is fixed in main branch. Please try build from source or use nightly package.
