### ISSUE TITLE
GemmTransposeFusion error when C is transposed (`Gemm(A,B,Transpose(C)`), complained with confusing name `_transformed_transformed_transformed...`

### ISSUE THREAD

**Issue by lazycal** [microsoft/onnxruntime#12071]
**Describe the bug**
On this graph:
![image](https://user-images.githubusercontent.com/7333325/177007319-7c33b7d2-cdd3-49ce-83ff-709ea072c5fe.png)
ORT with full optimization throws error: `onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for Gemm(13) node with name '_transformed_transformed_transformed_transformed_transformed_transformed_transformed_transformed_transformed_transformed_transformed`

- This may not be a NOT_IMPLEMENTED issue given the weird pattern of the name `_transformed_transformed_transformed...`? 
- When I turn off all optimization, ORT passes with no error
- When I remove the transpose node, there is no issue
- When I also mark Transpose(C) as the output, there is no issue.

I skimmed through the related code and I guess this is because the optimizer fails to realize that the graph is fused already so keeps transforming until some budget runs out? Specifically, the fusion condition here https://github.com/microsoft/onnxruntime/blob/df712d80ca33b56ce7d63ca3acdb6a4888638c58/onnxruntime/core/optimizer/gemm_transpose_fusion.cc#L103-L107
assums only two inputs so it also passes whenever C is tranaposed, but the fusion logic only removes the transpose at A and B:
https://github.com/microsoft/onnxruntime/blob/df712d80ca33b56ce7d63ca3acdb6a4888638c58/onnxruntime/core/optimizer/gemm_transpose_fusion.cc#L27-L46

One quick fix may be to change the fusion condition to trigger only on A && B?

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.11.1
- Python version: 3.7.11
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**To Reproduce**
Run the following code
```python
import numpy as np
import onnxruntime as ort
import onnx
from onnx import helper, checker, version_converter
from onnx import TensorProto

ash = [1, 1]
bsh = [1, 1]
csh = [1, 1]

a = helper.make_tensor_value_info('a', TensorProto.FLOAT, ash)
b = helper.make_tensor_value_info('b', TensorProto.FLOAT, bsh)
c = helper.make_tensor_value_info('c', TensorProto.FLOAT, csh)
d = helper.make_tensor_value_info('d', TensorProto.FLOAT, csh[::-1])
Y = helper.make_tensor_value_info('y', TensorProto.FLOAT, [1, 1])

node = onnx.helper.make_node(
    'Gemm',
    inputs=['a', 'b', 'd'],
    outputs=['y'],
    alpha=0.25,
    beta=0.35,
)
node_trans = onnx.helper.make_node(
    'Transpose',
    inputs=['c'],
    outputs=['d'],
)
graph_def = helper.make_graph(
    [node_trans, node],
    'test-model',
    [a, b, c],
    # outputs=[d, Y],  # passed
    outputs=[Y],       # failed
)
model_def = helper.make_model_gen_version(
    graph_def, producer_name='onnx-example')
model_def = version_converter.convert_version(model_def, 14)

print('The model is:\n{}'.format(model_def))
checker.check_model(model_def, full_check=True)
print('The model is checked!')

onnx.save(model_def, 'output.onnx')

anp = np.random.rand(*ash).astype(np.float32)
bnp = np.random.rand(*bsh).astype(np.float32)
cnp = np.random.rand(*csh).astype(np.float32)
sess_opt = ort.SessionOptions()
# uncomment this line then no issue
# sess_opt.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL
sess = ort.InferenceSession("output.onnx", sess_opt, providers=[
                            "CPUExecutionProvider"])
sess.run(["y"], {"a": anp, "b": bnp, "c": cnp})
```

[output.onnx.zip](https://github.com/microsoft/onnxruntime/files/9033240/output.onnx.zip)

**Expected behavior**
Throw no error or a better error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/7333325/177007402-10e1ca70-ec2b-47c9-95b8-f96d3e9c0810.png)

**Additional context**
None

**Comment by ytaous** [comment]
Hi, thanks for reporting the issue. If I try earlier version of ort 1.12, I can repro the same.
However, using latest build from master, the issue is not reproducible.
We are having ort 1.12 releasing soon, you can try that. Or build from source is also fine.
Thanks.
