### ISSUE TITLE
onnxruntime use more GPU memory than pytorch

### ISSUE THREAD

**Issue by nicken** [microsoft/onnxruntime#12070]
I made it to work using cuda 11, and even the onxx model is only 600 mb, onxx uses around 2400 mb of memory. And pytorch uses around 1200 mb of memory, so the memory usage is around 2x more.

And ONXX should use less memory, as far as i read right.

I used the same code as above to convert the model.

_Originally posted by @Oxi84 in https://github.com/microsoft/onnxruntime/issues/9292#issuecomment-987590269_

**Comment by nicken** [comment]
I get same question, and i don't known how to solve it;

This my test env:
* T4
* [yolox onnx](https://github.com/Megvii-BaseDetection/YOLOX/tree/main/demo/ONNXRuntime)
* docker: nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04
* onnxruntime: 1.11.1
* data: COCO dataset random 1000 images

this my test result:
*  yolox_m

| env/provider             | CUDA | ONNX             | 
| ------------------------ | ---- | ---------------- | 
| T4 | 1393Mib, 28.420s | 1811MiB, 24.646s |
| 1060  | | 593 MiB, 47.36s |
| 3080  |  | 1427MiB, 11.03s |

**Comment by nicken** [comment]
#9289 Similar problems

**Comment by tianleiwu** [comment]
@[nicken](https://github.com/nicken)

Sometime, the default arena extend strategy might allocate more memory than needed.

Could you try set execution provider options like the following python code:
```
import onnxruntime as ort
sess_options = ort.SessionOptions()
cuda_provider_options = {
"arena_extend_strategy": "kSameAsRequested",
}
execution_providers = [("CUDAExecutionProvider", cuda_provider_options), "CPUExecutionProvider"]
ort_sess = ort.InferenceSession(onnx_path, sess_options, providers=execution_providers)
```

Then use one input (warm up query) that need most memory to inference after session is created. That will allocate just enough memory for your need, and also ensure that future inference does not allocate heap memory.

**Comment by nicken** [comment]
> @[nicken](https://github.com/nicken)
> 
> Sometime, the default arena extend strategy might allocate more memory than needed.
> 
> Could you try set execution provider options like the following python code:
> 
> ```
> import onnxruntime as ort
> sess_options = ort.SessionOptions()
> cuda_provider_options = {
> "arena_extend_strategy": "kSameAsRequested",
> }
> execution_providers = [("CUDAExecutionProvider", cuda_provider_options), "CPUExecutionProvider"]
> ort_sess = ort.InferenceSession(onnx_path, sess_options, providers=execution_providers)
> ```
> 
> Then use one input (warm up query) that need most memory to inference after session is created. That will allocate just enough memory for your need, and also ensure that future inference does not allocate heap memory.

Thank you you can help me! @tianleiwu 

I try this method on 3080, I get similar result:
| device | ONNX|
| --- | ---|
| 3080  | 1463MB 11.41s|
