### ISSUE TITLE
where is demo/pcd_demo.py?

### ISSUE THREAD

**Issue by zheyuanWang** [microsoft/onnxruntime#12085]
Hi, 
I followed the [installation guide](https://mmdetection3d.readthedocs.io/en/latest/getting_started.html#installation) to install the framework. Not error popped up during installation.

After `Successfully installed mmcls-0.23.1 mmsegmentation-0.26.0 prettytable-3.3.0 wcwidth-0.2.5` I want to test if I've done everything right. But I cound found the file `pcd_demo.py`. 

Is this guidance outdated? Or do I have to further install the whole package via `pip install -v -e .[all]`?

---
Enviroment:
Python 3.10.4
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
cuda driver Version: 460.56

**Comment by faxu** [comment]
This does not look related to onnxruntime. Please post in support forum for mmdetection3d
