### ISSUE TITLE
Requesting example on graph neural network

### ISSUE THREAD

**Issue by Debottam** [microsoft/onnxruntime#12103]
Hi,
I would like to know how onnx is dealing with graph neural network? I don't see any example of converting any pytorch or tensorflow GNN model to onnx . I am mostly wondering about the adjacency matrix? Does onnx treat it as part of input data? 
**System information**
- ONNX Runtime version (you are using): 1.11.1

Thanks,
Debottam.

**Comment by ytaous** [comment]
@garymm - does onnx export support gnn model?

**Comment by Debottam** [comment]
Hi @ytaous 
Any news on this?

Thanks

**Comment by ytaous** [comment]
I can't find any UT using GNN in our code base. 
You can check https://github.com/pytorch/pytorch/tree/master/test/onnx, if you can't find it there. Then there's no such example. However, you can still search internet. For example - https://github.com/alinutzal/gnn_onnx

If you can find an sample, you can make this call:
torch.onnx.export(model, tuple(input), '/path/to/model.onnx')

@thiagocrepaldi - pls feel free to add more comment, thx.

**Comment by garymm** [comment]
This isn't a runtime issue, so closing this. Please open an issue in https://github.com/onnx/tutorials or https://github.com/onnx/models, though realistically it's not going to be a priority and you will be asked to contribute it. I guess https://github.com/alinutzal/gnn_onnx may be an example you can look at.
