### ISSUE TITLE
CUDA Specified device is not supported.

### ISSUE THREAD

**Issue by ox-prog** [microsoft/onnxruntime#12104]
I have some code on C++/ONNX which works fine both CPU and GPU (using cv::Mat) - it's accelerated by CUDA fine.
I need to run session with tensor will then be placed on the GPU directly: #https://github.com/microsoft/onnxruntime/issues/5555

I'm confirmed that cuda provider works fine (as well as CUDA acceleration):
```C++
  OrtCUDAProviderOptions cuda_options;
  cuda_options.device_id = 0;

  session_options.AppendExecutionProvider_CUDA(cuda_options);
```

But, when I add the following line from the [shared_lib/test_inference.cc](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_inference.cc#L967)
```C++
Ort::MemoryInfo info_cuda("Cuda", OrtAllocatorType::OrtArenaAllocator, 0, OrtMemTypeDefault);
```
I get an exception: "Specified device is not supported." [this line of code](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/framework/allocator.cc#L140)

**Card**: GTX 1660 SUPER 6 GB, RTX 3060 Laptop 6GB, RTX Quadro 4000 8GB

**Windows 10**

**ONNX**: win-x64-gpu-1.11.1

**nvcc**: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:36:24_Pacific_Standard_Time_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0

Is my card too old, or I did something wrong?

**Comment by zengjie617789** [comment]
I meet the same problem, did you find the solution?

**Comment by arvindsouza** [comment]
Hello, I have been having this problem as well. Were you able to find a solution?
