### ISSUE TITLE
Beamsearch operator reports error

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/onnxruntime#12102]
I've exported a gpt2 beam search model using `convert_beam_search.py`. But when I was doing inference, the model occasionally reports:
```
Status Message: /Users/runner/work/1/s/onnxruntime/contrib_ops/cpu/transformers/beam_search_scorer.cc:206 virtual void onnxruntime::contrib::transformers::BeamSearchScorer::Process(onnxruntime::contrib::transformers::ISequences *, gsl::span<const float> &, gsl::span<const int32_t> &, gsl::span<const int32_t> &) hypothesis_buffer_offset_ <= batch_size_ * num_beams_ * max_length_ was false.
```

This error does not always occur, but I have some experience to reproduce this:
1. set beam size to a large number, like 10 or 20
2. set max_length also to a large number, like input_ids + 100
3. After all beams reaches eos_token, the subsequent inferences reports this error

**Comment by faxu** [comment]
CC @tianleiwu

**Comment by tianleiwu** [comment]
@HaoboGu, the bug has been fixed in release branch, see the line: https://github.com/microsoft/onnxruntime/blob/def78a1b815ae2b60d19df97c352230591e7d7a6/onnxruntime/contrib_ops/cpu/transformers/beam_search_scorer.cc#L207.

Please try release candidate of ORT 1.12:

For CPU:
```
pip uninstall onnxruntime
pip install -i https://test.pypi.org/simple/ ort-nightly==1.12.0.dev20220707003
```

For GPU:
```
pip uninstall onnxruntime-gpu
pip install -i https://test.pypi.org/simple/ ort-nightly-gpu==1.12.0.dev20220707003
```

You need export the model again using convert_beam_search.py in the master branch, since there is interface change of BeamSearch operator.

**Comment by HaoboGu** [comment]
Thanks, I'll have a try

**Comment by HaoboGu** [comment]
@tianleiwu I re-exported the model using
```shell
python convert_beam_search.py -m gpt2 --output gpt2_beam_search.onnx --prefix_vocab_mask
```
But when I inference using the exported model, it reports:
```
2:Non-zero status code returned while running BeamSearch node. Name:'BeamSearch_gpt2' Status Message: Input 'vocab_mask' is expected to have 1 dimension, got 2'
```

I enabled `prefix_vocab_mask` only, and `vocab_mask` is disabled.

**Comment by HaoboGu** [comment]
When I enable `vocab_mask` and `prefix_vocab_mask` both, the model cannot be loaded:
```
onnxruntime error: 10:Load model from /Users/haobogu/Projects/python/cosine/tmp/converted/converted_beam_search_model.onnx failed:This is an invalid model. Type Error: Type 'tensor(int32)' of input parameter (vocab_mask) of operator (BeamSearch) in node (BeamSearch_gpt2) is invalid.'
```

**Comment by tianleiwu** [comment]
@HaoboGu, 
I cannot reproduce it. I can run the command in my machine without problem.
```
D:\git\onnxruntime\onnxruntime\python\tools\transformers>python convert_beam_search.py -m gpt2 --output gpt2_beam_search.onnx --prefix_vocab_mask
...
Torch and ORT result is  same
ORT {'test_times': 1, 'latency_variance': '0.00', 'latency_90_percentile': '2930.18', 'latency_95_percentile': '2930.18', 'latency_99_percentile': '2930.18', 'average_latency_ms': '2930.18', 'QPS': '1.02', 'parity': True}
Output file: gpt2_beam_search.onnx
```
Please git pull the latest master to get the convert_beam_search.py and install ort-nightly package as I mentioned.

**Comment by HaoboGu** [comment]
@tianleiwu I found the cause. I used `libonnxruntime1.11.1.dylib` dynamic lib. This op is not compatible with previous versions. Seems I have to compile the lib with latest master. Thanks a lot!
