### ISSUE TITLE
Compatibility matrix mismatch with release version.

### ISSUE THREAD

**Issue by mohammedfazil003** [microsoft/onnxruntime#12117]
Hello,

I want to use onnxruntime(v1.11.0), but i do see there has been a mismatch with the version matrix and the release notes with respect to onnx version.

https://github.com/microsoft/onnxruntime/blob/master/docs/Versioning.md
https://github.com/microsoft/onnxruntime/releases/tag/v1.11.0

As per compatibility matrix 1.11.0 onnxruntime supports till 1.10 of onnx where as the release note says that onnxruntime 1.11.0 supports onnx 1.11 with opset 16.This has been a bit confusing to understand.

I am eager to know which version of onnx we should agree on with some details about it.

**Comment by snnn** [comment]
Open https://github.com/microsoft/onnxruntime/blob/master/docs/OperatorKernels.md, then switch the branch to what you are interested in. Then you will know if the version of ONNX Runtime has the implementation of a particular opset of a particular kernel.   

In the last release, bumping ONNX version was a last-minute change.  It was just after a new ONNX version was released.  The dev team of ONNX Runtime need time to implement the new operators(expect those who already have function bodies). So even the release note says that onnxruntime 1.11.0 supports onnx 1.11 with opset 16, it doesn't mean that version of ONNX Runtime has implemented all the new operators of ONNX 1.11. Instead, it means that version of ONNX Runtime was built with ONNX 1.11 and knows what operators ONNX 1.11 has and has implemented **some** of the new operators.
