### ISSUE TITLE
Build from source can not run python setup.py build wheel

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#12115]
<img width="951" alt="image" src="https://user-images.githubusercontent.com/21303438/177683121-211d8e15-d499-411a-a331-38588fba11d1.png">

<img width="606" alt="image" src="https://user-images.githubusercontent.com/21303438/177683145-70607770-0d06-41c9-ad15-804a2e1dc18f.png">

Also, the requirements.txt.in can not copy to requirements.txt automatically

**Comment by justinchuby** [comment]
The bullet point is for building onnx (not ort) from source. It makes sense for us to make this more clear.
