### ISSUE TITLE
Question about using same logid for different session

### ISSUE THREAD

**Issue by ZhuGeRoastedFish** [microsoft/onnxruntime#12116]
Notice that we need to pass a param named "logid" when creating env, then using the env create a new session, so here comes the question:
what if I pass the same logid to create 2 different sessions?
Like, in function foo1, g_ort1->CreateEnv(ORT_LOGGING_LEVEL_WARNING, "model0", &env);
in function foo2, g_ort2->CreateEnv(ORT_LOGGING_LEVEL_WARNING, "model0", &env);
Will such operation lead to crash? In my test nothing happend, but I'm afraid something may happend in the futrue if I don't quite understand the meaning of logid.
Thanks for reading here!

**Comment by skottmckay** [comment]
The logid is an arbitrary string that is included in log messages to allow a user to disambiguate log messages from different sessions. It's fine to use the same value in multiple sessions.
