### ISSUE TITLE
torch.scatter_add converts to onnx format and inference result is wrong when I use onnxruntime with version 1.11.1

### ISSUE THREAD

**Issue by zhang0557kui** [microsoft/onnxruntime#12119]
torch.scatter_add converts to onnx format and inference result is wrong when I use onnxruntime with version 1.11.1

```python
def Pool(x, trans, dim=1):
    row, col, value = trans[0].to(x.device), trans[1].to(x.device), trans[2].to(x.device)
    value = value.unsqueeze(-1)
    out = torch.index_select(x, dim, col) * value
    out2 = torch.zeros(x.size(0), row.size(0)//3, x.size(-1)).to(x.device)
    idx = row.unsqueeze(0).unsqueeze(-1).expand_as(out)
    out2 = torch.scatter_add(out2, dim, idx, out)
    return out2
```

**Comment by AllenTiTaiWang** [comment]
So the latest versio of Pytorch solved this?

**Comment by EJShim** [comment]
I still have wrong results.
my pytorch and onnxruntime versions are both '1.12.1' 

I exported my model including 'scatter_add' with parameter `opset=16`.

**Comment by AllenTiTaiWang** [comment]
Could you provide a simple repro that we can investigate on it? I see we suppot this since [#79103](https://github.com/pytorch/pytorch/pull/79103), and the test case seems to pass all the time.

**Comment by KominA** [comment]
Are there any updates? I have the same problem

**Comment by titaiwangms** [comment]
torch 1.13 should support scatter_add with opset_version=16. If not in your case, please raise an issue with simple repro in PyTorch.

**Comment by interestingzhuo** [comment]
The  mistake stiil  exits!!!!
