### ISSUE TITLE
Getting CUDA out of memory when converting a large model

### ISSUE THREAD

**Issue by NouamaneTazi** [microsoft/onnxruntime#12124]
**Describe the bug**
When running the following command to convert a large model like `t5-11b` I get a CUDA out of memory error.
```shell
python convert_beam_search.py -m t5-11b --model_type t5 --output onnx_models/t5-11b/t5-11b.onnx -e --use_gpu
```

 How can I convert a large model?

**System information**
PyTorch Version:1.12.0
Transformers Version:4.21.0.dev0
Onnxruntime Version:1.11.1

**Comment by NouamaneTazi** [comment]
Thank you @tianleiwu. How can I run inference for such large models on a multi GPU setup? Can you point me to some example?

**Comment by tianleiwu** [comment]
@NouamaneTazi, currently ORT supports one session in one GPU (That also means BeamSearch operator can only run in one GPU).

A possible walkaround is to split a large model to multiple models (like split 24 layers to 4 models with 6 layers in each model), then create one inference session for each model, and each session is running in different GPU. You will need implement a custom version of beam search for this purpose.
 
@viboga, could you share prototype of beam search custom operator when it is ready. Other users could modify it to support multiple models.

**Comment by YifanWang-22** [comment]
@tianleiwu Hello there, I encountered the same CUDA out of memory error when converting a large transformer model. However I want to convert my model in FP16, which cpu does not support. Thus disabling `--use_gpu` cannot help me.
I wonder if there's any other workaround to convert the large model to onnx with gpu? Really appreciate your help!

**Comment by tianleiwu** [comment]
@YifanWang-22, you can convert the model to fp32 in CPU with large memory.

There is separated python script that could convert ONNX model from FP32 to FP16. The script can run in CPU only: https://github.com/microsoft/onnxconverter-common/blob/master/onnxconverter_common/float16.py

**Comment by YifanWang-22** [comment]
Thanks for your advice @tianleiwu, but the problem I had encountered was the model I wanted to convert has mixed-precision where the cpu doesn't support fp16 part and CUDA lacked enough memory. We later solved such problem by just using a larger memory of CUDA.
