### ISSUE TITLE
[TypeInferenceError] Graph attribute inferencing failed

### ISSUE THREAD

**Issue by vsooda** [microsoft/onnxruntime#1212]
**Describe the bug**
I use c api to load [tacotron](https://github.com/keithito/tacotron/blob/master/models/tacotron.py) model witch I had converted to onnx fp format. It report error:

```
Load model from decoder_fp16.onnx failed:[TypeInferenceError] Graph attribute inferencing failed: Node:generic_loop_Loop__97 Tensor element type mismatch. 10 != 1
```

What is `Node:generic_loop_Loop__97`,  how can I debug.  

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 0.4.0
- Python version: c++ cpu

**To Reproduce**
the origin tensorflow model is something like:
```
      attention_cell = AttentionWrapper(
        GRUCell(hp.attention_depth),
        BahdanauAttention(hp.attention_depth, encoder_outputs),
        alignment_history=True,
        output_attention=False)                                                  # [N, T_in, attention_depth=256]
      
      # Apply prenet before concatenation in AttentionWrapper.
      attention_cell = DecoderPrenetWrapper(attention_cell, is_training, hp.prenet_depths)

      # Concatenate attention context vector and RNN cell output into a 2*attention_depth=512D vector.
      concat_cell = ConcatOutputAndAttentionWrapper(attention_cell)              # [N, T_in, 2*attention_depth=512]

      # Decoder (layers specified bottom to top):
      decoder_cell = MultiRNNCell([
          OutputProjectionWrapper(concat_cell, hp.decoder_depth),
          ResidualWrapper(GRUCell(hp.decoder_depth)),
          ResidualWrapper(GRUCell(hp.decoder_depth))
        ], state_is_tuple=True)                                                  # [N, T_in, decoder_depth=256]

      # Project onto r mel spectrograms (predict r outputs at each RNN step):
      output_cell = OutputProjectionWrapper(decoder_cell, hp.num_mels * hp.outputs_per_step)
      decoder_init_state = output_cell.zero_state(batch_size=batch_size, dtype=tf.float32)

      if is_training:
        helper = TacoTrainingHelper(inputs, mel_targets, hp.num_mels, hp.outputs_per_step)
      else:
        helper = TacoTestHelper(batch_size, hp.num_mels, hp.outputs_per_step)

      (decoder_outputs, _), final_decoder_state, _ = tf.contrib.seq2seq.dynamic_decode(
        BasicDecoder(output_cell, helper, decoder_init_state),
        maximum_iterations=hp.max_iters)                                         # [N, T_out/r, M*r]

      # Reshape outputs to be one output per entry
      mel_outputs = tf.reshape(decoder_outputs, [batch_size, -1, hp.num_mels])   # [N, T_out, M]

      # Add post-processing CBHG:
      post_outputs = post_cbhg(mel_outputs, hp.num_mels, is_training,            # [N, T_out, postnet_depth=256]
                               hp.postnet_depth)
      linear_outputs = tf.layers.dense(post_outputs, hp.num_freq)                # [N, T_out, F]

      # Grab alignments from the final decoder state:
      alignments = tf.transpose(final_decoder_state[0].alignment_history.stack(), [1, 2, 0])

```

**Additional context**
I can load model and inference with model float 32, but fail with fp 16.  I use the script to convert model from float 32 to float 16:

```
import onnxmltools
from onnxmltools.utils.float16_converter import convert_float_to_float16
input_onnx_model = 'decoder.onnx'
output_onnx_model = 'decoder_fp16.onnx'
onnx_model = onnxmltools.utils.load_model(input_onnx_model)
onnx_model = convert_float_to_float16(onnx_model)
onnxmltools.utils.save_model(onnx_model, output_onnx_model)
```

**Comment by pranavsharma** [comment]
Can you attach decoder.onnx? generic_loop_Loop__97 is the name of a node in the graph and it looks like there's a type mismatch. 10 = float16 and 1 = float32.

**Comment by vsooda** [comment]
@pranavsharma  thank you. I'm checking model convert tools.

**Comment by hariharans29** [comment]
Hi @vsooda,

Were you able to resolve this ?

Thanks

**Comment by vsooda** [comment]
Hi @hariharans29 ,

No. I had checked the model convert tool, couldn't not found any problem. 

could onnxruntime support seq2seq model fp16 inference?  I was worried about wasting too much time on it, and finally found out that was onnxruntime kernel's problem

**Comment by hariharans29** [comment]
Can you share your model ?

**Comment by vsooda** [comment]
@hariharans29 thank you. I had tried to ask our company to share the model,  but failed.  I will debug onnx convert tool and onnxruntime after I finish the job at hand. or I will try to use an open source model to reproduce this problem.

**Comment by faxu** [comment]
Closing this issue for now. If you have an example model or portion of a model to share, feedback on error messaging/debuggability, let us know and feel free to reactivate in future.

**Comment by un-certainty** [comment]
Hi @hariharans29 @faxu 

I encountered a similar `TypeInferenceError` while loading an ONNX model with `onnxruntime.InferenceSession`. It was a `torch.jit.script` model and exported with `torch.onnx.export`. There is a loop implemented in the computation graph.

The error message was:
```
[ONNXRuntimeError] : 1 : FAIL : Node (/Loop) Op (Loop) [TypeInferenceError] Graph attribute inferencing failed: Type Error: Type (seq(tensor(float16))) of output arg (/model/model/glm/transformer/layers.0/attention/SplitToSequence_output_0) of node (/model/model/glm/transformer/layers.0/attention/SplitToSequence) does not match expected type (seq(tensor(float))).
```

And here is the graph of `layers.0/attention/SplitToSequence`:
![image](https://user-images.githubusercontent.com/102007104/219846527-38400cfe-e315-4282-b5c8-b73dbda588f7.png)

Related codes are:

```python
def split_tensor_along_last_dim(tensor, num_partitions: int):
    """Split a tensor along its last dimension.
    Arguments:
        tensor: input tensor.
        num_partitions: number of partitions to split the tensor
    """
    return torch.tensor_split(tensor, num_partitions, dim=-1)

# self.query_key_value = Linear(hidden_size, 3 * hidden_size)
mixed_x_layer = self.query_key_value(hidden_states)
mixed_query_layer, mixed_key_layer, mixed_value_layer) = split_tensor_along_last_dim(mixed_x_layer, 3)
query_layer = self._transpose_for_scores(mixed_query_layer)
key_layer = self._transpose_for_scores(mixed_key_layer)
value_layer = self._transpose_for_scores(mixed_value_layer)
```

I am not able to share the ONNX file. Could you provide some directions on where to start to debug the problem? I have competely no idea why a tensor(float) is epected, since all my weights and tensors are in float16.

Not sure if this is related: https://github.com/pytorch/pytorch/issues/72498
