### ISSUE TITLE
ORT 1.12 Release Candidate available for testing

### ISSUE THREAD

**Issue by faxu** [microsoft/onnxruntime#12133]
[ORT 1.12](https://github.com/microsoft/onnxruntime/projects/9) will be released later this month. Release candidate builds are available now for testing. If you encounter issues, please report them by responding in this issue.

Release branch: [rel-1.12.0](https://github.com/microsoft/onnxruntime/tree/rel-1.12.0)
Release manager: @RandySheriff 

Pypi | Nuget | npm | Maven (Java)
--- | --- | --- | ---
CPU: [1.12.0.dev20220707003](https://test.pypi.org/project/ort-nightly/1.12.0.dev20220707003/)<br/>GPU: [1.12.0.dev20220707003](https://test.pypi.org/project/ort-nightly-gpu/1.12.0.dev20220707003/) | CPU: [1.12.0-dev-20220707-0901-62226d030](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/NuGet/Microsoft.ML.OnnxRuntime/overview/1.12.0-dev-20220707-0901-62226d030)<br/>GPU (CUDA/TRT): [1.12.0-dev-20220707-0843-62226d030](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/NuGet/Microsoft.ML.OnnxRuntime.Gpu/overview/1.12.0-dev-20220707-0843-62226d030)<br/>DirectML: [1.12.0-dev-20220707-0643-62226d03](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/NuGet/Microsoft.ML.OnnxRuntime.DirectML/overview/1.12.0-dev-20220707-0643-62226d03)<br/>WindowsAI: [1.12.0-dev-20220707-0638-62226d030](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/NuGet/Microsoft.AI.MachineLearning/overview/1.12.0-dev-20220707-0638-62226d030) | onnxruntime-node: [1.12.0-dev.20220707-62226d030](https://www.npmjs.com/package/onnxruntime-node/v/1.12.0-dev.20220707-62226d030)<br/>onnxruntime-react-native [1.12.0-dev.20220707-62226d030](https://www.npmjs.com/package/onnxruntime-react-native/v/1.12.0-dev.20220707-62226d030)<br/>onnxruntime-web [1.12.0-dev.20220707-62226d030](https://www.npmjs.com/package/onnxruntime-web/v/1.12.0-dev.20220707-62226d030)|CPU: [ort-nightly-1.12.0](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fort-nightly/overview/1.12.0)<br/>GPU: [ort-nightly-gpu-1.12.0](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fort-nightly-gpu/overview/1.12.0)

**Comment by dvolgyes** [comment]
Probably there is a related issue somewhere tracking the remaining work for 1.12  , but I haven't found it,
and with a new issue it will be just lost among the open ones, so:
The new python3.10 support implies that the setup.py classifiers should be updated, and 
` "Programming Language :: Python :: 3.10" `
should be added both to master and to the 1.12 release branch.
These tags are used by Pypi.org, e.g. to show supported version. 
Similarly, 3.6 should be removed, because only 3.7+ is supported.

**Comment by RandySheriffH** [comment]
https://github.com/microsoft/onnxruntime/pull/12141

**Comment by faxu** [comment]
Edited to add npm packages

**Comment by HaoboGu** [comment]
Are dynamic libraries(.dll/.dylib/.so files) available for testing?

**Comment by fatcat-z** [comment]
Issue #12151 has been opened.

**Comment by RandySheriffH** [comment]
> Are dynamic libraries(.dll/.dylib/.so files) available for testing?

@HaoboGu: for now we are yet to have a plan for release candidate on native DLLs, mind try build from the source on https://github.com/microsoft/onnxruntime/tree/rel-1.12.0
https://github.com/microsoft/onnxruntime/blob/gh-pages/docs/build/inferencing.md

**Comment by faxu** [comment]
Added Java release candidates to table above (CC @craigacp)

**Comment by sam-h-bean** [comment]
Using 🤗 [Optimum](https://github.com/huggingface/optimum/) to optimize a model for GPU and load an ORT inference session using TensorrtExecutionProvider results in the following error

```bash
ort.InferenceSession("./artifacts/model-optimized.onnx", providers=["TensorrtExecutionProvider"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1025 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: /usr/local/lib/python3.8/dist-packages/onnxruntime/capi/libonnxruntime_providers_tensorrt.so: undefined symbol: getBuilderPluginRegistry
```

**Comment by Craigacp** [comment]
> Added Java release candidates to table above (CC @Craigacp)

@faxu the jars only contain the pom file, they don't have the class files or the native libraries, so it looks like something has gone wrong with the packaging of them.

**Comment by RandySheriffH** [comment]
@Craigacp, thanks for spotting this. Mind try new links?
https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fort-rc/overview/1.12.0
https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fort-rc-gpu/overview/1.12.0

**Comment by RandySheriffH** [comment]
@jywu-msft for the tensorrt optimizer a

> Using 🤗 [Optimum](https://github.com/huggingface/optimum/) to optimize a model for GPU and load an ORT inference session using TensorrtExecutionProvider results in the following error
> 
> ```shell
> ort.InferenceSession("./artifacts/model-optimized.onnx", providers=["TensorrtExecutionProvider"])
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
>     self._create_inference_session(providers, provider_options, disabled_optimizers)
>   File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
>     sess.initialize_session(providers, provider_options, disabled_optimizers)
> RuntimeError: /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1025 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: /usr/local/lib/python3.8/dist-packages/onnxruntime/capi/libonnxruntime_providers_tensorrt.so: undefined symbol: getBuilderPluginRegistry
> ```
> 
> For more background on this please see the following issues [274](https://github.com/huggingface/optimum/issues/274) and [288](https://github.com/huggingface/optimum/issues/288).
> 
> Steps to reproduce:
> 
> 1. Run `nvcr.io/nvidia/tensorrt:22.06-py3` container on GPU machine
> 2. Install onnxruntime-gpu from 1.12.0 RC
> 
> ```shell
> pip install -i https://test.pypi.org/simple/ ort-nightly-gpu==1.12.0.dev20220707003
> ```
> 
> 3. Install other deps
> 
> ```shell
> pip install transformers datasets onnx optimum
> ```
> 
> 4. Export 🤗 model to ONNX optimized for GPU with the following script
> 
> ```python
> from transformers import AutoTokenizer, AutoModelForCausalLM
> from optimum.onnxruntime.configuration import OptimizationConfig
> from optimum.onnxruntime import ORTModelForCausalLM, ORTOptimizer
> 
> 
> model = AutoModelForCausalLM.from_pretrained('distilgpt2')
> tokenizer = AutoTokenizer.from_pretrained('distilgpt2', padding=True, truncation=True)
> 
> optimization_config = OptimizationConfig(optimization_level=99, optimize_for_gpu=True)
> optimizer = ORTOptimizer(
>     model=model, preprocessor=tokenizer, feature="causal-lm", opset=13,
> )
> optimizer.export(
>     onnx_model_path="model.onnx",
>     onnx_optimized_model_output_path="model-optimized.onnx",
>     optimization_config=optimization_config,
>     use_external_data_format=True,
> )
> ```
> 
> 5. Try to load model using TensorrtExecutionProvider
> 
> ```python
> optimized_model = ORTModelForCausalLM.load_model("./model-optimized.onnx", provider="TensorrtExecutionProvider")
> ```
> 
> 6. (Optional) Try to load model directly with ORT
> 
> ```python
> import onnxruntime as ort
> 
> 
> ort.InferenceSession("./model-optimized.onnx", providers=["TensorrtExecutionProvider"])
> ```
> 
> ### UPDATE
> This Docker image actually comes with TensorRT 8.2 pip package installed. After upgrading to 8.4.1.5 I get
> 
> ```shell
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.8/dist-packages/optimum/onnxruntime/modeling_ort.py", line 143, in load_model
>     return ort.InferenceSession(path, providers=[provider])
>   File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
>     self._create_inference_session(providers, provider_options, disabled_optimizers)
>   File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
>     sess.initialize_session(providers, provider_options, disabled_optimizers)
> onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc:798 SubGraphCollection_t onnxruntime::TensorrtExecutionProvider::GetSupportedList(SubGraphCollection_t, int, int, const onnxruntime::GraphViewer&, bool*) const [ONNXRuntimeError] : 1 : FAIL : TensorRT input: onnx::MatMul_345 has no shape specified. Please run shape inference on the onnx model first. Details can be found in https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#shape-inference-for-tensorrt-subgraphs
> ```
> 
> Upon trying to run the suggested script I get
> 
> ```shell
> python symbolic_shape_infer.py --input ./model-optimized.onnx --output ./model-new-optimized.onnx --auto_merge
> Traceback (most recent call last):
>   File "symbolic_shape_infer.py", line 2424, in <module>
>     out_mp = SymbolicShapeInference.infer_shapes(
>   File "symbolic_shape_infer.py", line 2360, in infer_shapes
>     raise Exception("Incomplete symbolic shape inference")
> Exception: Incomplete symbolic shape inference
> ```

@jywu-msft

**Comment by jywu-msft** [comment]
> 

If i'm reading this issue and your other linked issues correctly, this is not a specific issue with ORT 1.12 per se. I think you mentioned in https://github.com/huggingface/optimum/issues/288 that you encountered the issue with 1.11 as well.
It looks like there is an issue with symbolic_shape_infer.py for that model. can you file a separate issue in github.com/microsoft/onnxruntime/issues so it can be tracked separately? Thanks.

**Comment by sam-h-bean** [comment]
> > 
> 
> If i'm reading this issue and your other linked issues correctly, this is not a specific issue with ORT 1.12 per se. I think you mentioned in [huggingface/optimum#288](https://github.com/huggingface/optimum/issues/288) that you encountered the issue with 1.11 as well. (can you please confirm that?) It looks like there is an issue with symbolic_shape_infer.py for that model. can you file a separate issue in github.com/microsoft/onnxruntime/issues so it can be tracked separately? Thanks.
> 
> Also, thank you for pointing out that ORT 1.12 requires TensorRT 8.4 (and no longer works with TensorRT 8.2 which is what ships in the nvidia TensorRT 22.06 container image

They were separate issues with 1.11. Yes I think the optimized model symbolic inference was fixed by passing `--guess_output_rank` to the script. However for a quantized model through optimum when I run symbolic inference I am getting 
```bash
root@tensorrt-nrfkc:/workspace# python symbolic_shape_infer.py --input model-quantized.onnx --output new-model-quantized.onnx --save_as_external_data --guess_output_rank --auto_mer
ge --verbose 3
Potential unsafe merge between symbolic expressions: (floor(Min(64, Reshape_6250_o0__d3)/2 + 1/2),floor(Min(64, Reshape_6250_o0__d3)/2))
Potential unsafe merge between symbolic expressions: (floor(Min(64, Reshape_6252_o0__d3)/2),floor(Min(64, Reshape_6252_o0__d3)/2 + 1/2))
Traceback (most recent call last):
  File "symbolic_shape_infer.py", line 2424, in <module>
    out_mp = SymbolicShapeInference.infer_shapes(
  File "symbolic_shape_infer.py", line 2357, in infer_shapes
    all_shapes_inferred = symbolic_shape_inference._infer_impl()
  File "symbolic_shape_infer.py", line 2127, in _infer_impl
    self.dispatcher_[node.op_type](node)
  File "symbolic_shape_infer.py", line 1818, in _infer_Tile
    input_sympy_shape = self._get_sympy_shape(node, 0)
  File "symbolic_shape_infer.py", line 367, in _get_sympy_shape
    for d in self._get_shape(node, idx):
TypeError: 'NoneType' object is not iterable

```

**Comment by sam-h-bean** [comment]
@jywu-msft also opened up an issue https://github.com/microsoft/onnxruntime/issues/12173. But would love to ensure if there is an issue with this script then it is fixed for 1.12.0 so will track here as well. Installing from the nightly GPU makes things hard 😢

**Comment by leqiao-1** [comment]
Tests on machine mac m1 with for inception_v2 model work fine from python 3.7 to python 3.10.

**Comment by Craigacp** [comment]
> @Craigacp, thanks for spotting this, mind try new links?
> 
> * [cpu](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fort-rc/overview/1.12.0)
> * [gpu](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fort-rc-gpu/overview/1.12.0)

That's also not packaged right. Now it's a jar file which contains another jar file which has the classes & native libraries in:
```shell
$ jar tf ~/.m2/repository/com/microsoft/onnxruntime/ort-rc/1.12.0/ort-rc-1.12.0.jar 
META-INF/
META-INF/MANIFEST.MF
onnxruntime-1.12.0-javadoc.jar
onnxruntime-1.12.0-javadoc.jar.asc
onnxruntime-1.12.0-sources.jar
onnxruntime-1.12.0-sources.jar.asc
onnxruntime-1.12.0.jar
onnxruntime-1.12.0.jar.asc
onnxruntime-1.12.0.pom
onnxruntime-1.12.0.pom.asc
```
when it should look like this:
```shell
$ jar tf onnxruntime-1.12.0.jar 
ai/
ai/onnxruntime/
ai/onnxruntime/MapInfo.class
ai/onnxruntime/native/
ai/onnxruntime/native/linux-aarch64/
ai/onnxruntime/native/linux-aarch64/libonnxruntime.so
ai/onnxruntime/native/linux-aarch64/libonnxruntime4j_jni.so
ai/onnxruntime/native/linux-x64/
ai/onnxruntime/native/linux-x64/libonnxruntime.so
ai/onnxruntime/native/linux-x64/libonnxruntime4j_jni.so
ai/onnxruntime/native/osx-arm64/
ai/onnxruntime/native/osx-arm64/libonnxruntime.dylib
ai/onnxruntime/native/osx-arm64/libonnxruntime.dylib.dSYM/
ai/onnxruntime/native/osx-arm64/libonnxruntime.dylib.dSYM/Contents/
ai/onnxruntime/native/osx-arm64/libonnxruntime.dylib.dSYM/Contents/Info.plist
ai/onnxruntime/native/osx-arm64/libonnxruntime.dylib.dSYM/Contents/Resources/
ai/onnxruntime/native/osx-arm64/libonnxruntime.dylib.dSYM/Contents/Resources/DWARF/
ai/onnxruntime/native/osx-arm64/libonnxruntime.dylib.dSYM/Contents/Resources/DWARF/libonnxruntime.dylib
ai/onnxruntime/native/osx-arm64/libonnxruntime4j_jni.dylib
ai/onnxruntime/native/osx-arm64/libonnxruntime4j_jni.dylib.dSYM/
ai/onnxruntime/native/osx-arm64/libonnxruntime4j_jni.dylib.dSYM/Contents/
ai/onnxruntime/native/osx-arm64/libonnxruntime4j_jni.dylib.dSYM/Contents/Info.plist
ai/onnxruntime/native/osx-arm64/libonnxruntime4j_jni.dylib.dSYM/Contents/Resources/
ai/onnxruntime/native/osx-arm64/libonnxruntime4j_jni.dylib.dSYM/Contents/Resources/DWARF/
ai/onnxruntime/native/osx-arm64/libonnxruntime4j_jni.dylib.dSYM/Contents/Resources/DWARF/libonnxruntime4j_jni.dylib
ai/onnxruntime/native/osx-x64/
ai/onnxruntime/native/osx-x64/libonnxruntime.dylib
ai/onnxruntime/native/osx-x64/libonnxruntime.dylib.dSYM/
ai/onnxruntime/native/osx-x64/libonnxruntime.dylib.dSYM/Contents/
ai/onnxruntime/native/osx-x64/libonnxruntime.dylib.dSYM/Contents/Info.plist
ai/onnxruntime/native/osx-x64/libonnxruntime.dylib.dSYM/Contents/Resources/
ai/onnxruntime/native/osx-x64/libonnxruntime.dylib.dSYM/Contents/Resources/DWARF/
ai/onnxruntime/native/osx-x64/libonnxruntime.dylib.dSYM/Contents/Resources/DWARF/libonnxruntime.dylib
ai/onnxruntime/native/osx-x64/libonnxruntime4j_jni.dylib
ai/onnxruntime/native/osx-x64/libonnxruntime4j_jni.dylib.dSYM/
ai/onnxruntime/native/osx-x64/libonnxruntime4j_jni.dylib.dSYM/Contents/
ai/onnxruntime/native/osx-x64/libonnxruntime4j_jni.dylib.dSYM/Contents/Info.plist
ai/onnxruntime/native/osx-x64/libonnxruntime4j_jni.dylib.dSYM/Contents/Resources/
ai/onnxruntime/native/osx-x64/libonnxruntime4j_jni.dylib.dSYM/Contents/Resources/DWARF/
ai/onnxruntime/native/osx-x64/libonnxruntime4j_jni.dylib.dSYM/Contents/Resources/DWARF/libonnxruntime4j_jni.dylib
ai/onnxruntime/native/win-x64/
ai/onnxruntime/native/win-x64/onnxruntime.dll
ai/onnxruntime/native/win-x64/onnxruntime.pdb
ai/onnxruntime/native/win-x64/onnxruntime4j_jni.dll
ai/onnxruntime/native/win-x64/onnxruntime4j_jni.pdb
ai/onnxruntime/NodeInfo.class
ai/onnxruntime/OnnxJavaType$1.class
ai/onnxruntime/OnnxJavaType.class
ai/onnxruntime/OnnxMap$1.class
ai/onnxruntime/OnnxMap$OnnxMapValueType.class
ai/onnxruntime/OnnxMap.class
ai/onnxruntime/OnnxModelMetadata.class
ai/onnxruntime/OnnxRuntime.class
ai/onnxruntime/OnnxSequence$1.class
ai/onnxruntime/OnnxSequence.class
ai/onnxruntime/OnnxTensor$1.class
ai/onnxruntime/OnnxTensor.class
ai/onnxruntime/OnnxValue$OnnxValueType.class
ai/onnxruntime/OnnxValue.class
ai/onnxruntime/OrtAllocator.class
ai/onnxruntime/OrtEnvironment$OrtEnvCloser.class
ai/onnxruntime/OrtEnvironment$ThreadingOptions.class
ai/onnxruntime/OrtEnvironment.class
ai/onnxruntime/OrtException$OrtErrorCode.class
ai/onnxruntime/OrtException.class
ai/onnxruntime/OrtLoggingLevel.class
ai/onnxruntime/OrtProvider.class
ai/onnxruntime/OrtProviderOptions$1.class
ai/onnxruntime/OrtProviderOptions$OrtProviderSupplier.class
ai/onnxruntime/OrtProviderOptions.class
ai/onnxruntime/OrtSession$Result.class
ai/onnxruntime/OrtSession$RunOptions.class
ai/onnxruntime/OrtSession$SessionOptions$ExecutionMode.class
ai/onnxruntime/OrtSession$SessionOptions$OptLevel.class
ai/onnxruntime/OrtSession$SessionOptions.class
ai/onnxruntime/OrtSession.class
ai/onnxruntime/OrtUtil$1.class
ai/onnxruntime/OrtUtil.class
ai/onnxruntime/providers/
ai/onnxruntime/providers/CoreMLFlags.class
ai/onnxruntime/providers/NNAPIFlags.class
ai/onnxruntime/providers/OrtCUDAProviderOptions.class
ai/onnxruntime/providers/OrtFlags.class
ai/onnxruntime/providers/OrtTensorRTProviderOptions.class
ai/onnxruntime/providers/StringConfigProviderOptions.class
ai/onnxruntime/SequenceInfo.class
ai/onnxruntime/TensorInfo$1.class
ai/onnxruntime/TensorInfo$OnnxTensorType.class
ai/onnxruntime/TensorInfo.class
ai/onnxruntime/ValueInfo.class
GIT_COMMIT_ID
libcustom_op_library.dylib
libcustom_op_library.so
META-INF/
META-INF/MANIFEST.MF
META-INF/maven/
META-INF/maven/com.microsoft.onnxruntime/
META-INF/maven/com.microsoft.onnxruntime/onnxruntime/
META-INF/maven/com.microsoft.onnxruntime/onnxruntime/pom.xml
Privacy.md
ThirdPartyNotices.txt
```

I'm also not sure what the `libcustom_op_library.dylib` or `libcustom_op_library.so` files are doing in there. My understanding was that the onnx-extension static library was going to be compiled into `libonnxruntime.dylib`/`libonnxruntime.so`, and it's also not clear if they are aarch64 or x86 binaries.

**Comment by RandySheriffH** [comment]
@Craigacp: the jar uploaded contains three jar files and one pom, with onnxruntime-1.12.0.jar being one of them.

**Comment by RandySheriffH** [comment]
@Craigacp : maybe libcustom... should be removed from package, while I am working on that mind try this package?
https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fonnxruntime/overview/1.12.0

**Comment by Craigacp** [comment]
> @Craigacp : maybe libcustom... should be removed from package, while I am working on that, mind try these packages?
> 
> * [cpu](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fonnxruntime/overview/1.12.0)
> * [gpu](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fonnxruntime_gpu/overview/1.12.0)
> 
> See if you could install directly with Maven or Gradle.

I tested out the CPU one on macOS x86_64, and everything works fine. I had to add this snippet (which is given in the link but I'm repeating to help anyone else interested) to Tribuo's Maven build file and then modify the version number we pull in, but that was it.

``` 
   <repositories>
    <repository>
      <id>ORT-Nightly</id>
      <url>https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/maven/v1</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
  </repository>
  </repositories>
```

The name & version is a bit problematic though as Maven expects there to be only ever one artifact named by a group id, artifact id and version tuple, so testing out that one will mean people cache it locally in preference to downloading the real `v1.12.0` when it is released. Maybe it should have `v1.12.0-rc1` as the version number?

**Comment by RandySheriffH** [comment]
@Craigacp, like these?

- [cpu](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fonnxruntime/overview/1.12.0-rc1)
- [gpu](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fonnxruntime_gpu/overview/1.12.0-rc1)

**Comment by leqiao-1** [comment]
> @Craigacp, like these?
> 
> * [cpu](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fonnxruntime/overview/1.12.0-rc1)
> * [gpu](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fonnxruntime_gpu/overview/1.12.0-rc1)
> 
> Plus I have removed those custom_op_libs. Some investigation showed that the [PR](https://github.com/microsoft/onnxruntime/pull/10981) might be the culprit of misplacing of those custom_op_libs, since you are one of reviewers, any suggestions for a fix to @leqiao-1 ?

The wrong placed libs are removed in this PR https://github.com/microsoft/onnxruntime/pull/12201. 
The jar file can be added with ```mvn install:install-file -Dfile=onnxruntime-1.12.0.jar -DpomFile=onnxruntime-1.12.0.pom```
Here is the updated structure:
```
jar tf onnxruntime-1.12.0.jar
ai/
ai/onnxruntime/
ai/onnxruntime/MapInfo.class
ai/onnxruntime/native/
ai/onnxruntime/native/linux-aarch64/
ai/onnxruntime/native/linux-aarch64/libonnxruntime.so
ai/onnxruntime/native/linux-aarch64/libonnxruntime4j_jni.so
ai/onnxruntime/native/linux-x64/
ai/onnxruntime/native/linux-x64/libonnxruntime.so
ai/onnxruntime/native/linux-x64/libonnxruntime4j_jni.so
ai/onnxruntime/native/osx-arm64/
ai/onnxruntime/native/osx-arm64/libonnxruntime.dylib
ai/onnxruntime/native/osx-arm64/libonnxruntime.dylib.dSYM/
ai/onnxruntime/native/osx-arm64/libonnxruntime.dylib.dSYM/Contents/
ai/onnxruntime/native/osx-arm64/libonnxruntime.dylib.dSYM/Contents/Info.plist
ai/onnxruntime/native/osx-arm64/libonnxruntime.dylib.dSYM/Contents/Resources/
ai/onnxruntime/native/osx-arm64/libonnxruntime.dylib.dSYM/Contents/Resources/DWARF/
ai/onnxruntime/native/osx-arm64/libonnxruntime.dylib.dSYM/Contents/Resources/DWARF/libonnxruntime.dylib
ai/onnxruntime/native/osx-arm64/libonnxruntime4j_jni.dylib
ai/onnxruntime/native/osx-arm64/libonnxruntime4j_jni.dylib.dSYM/
ai/onnxruntime/native/osx-arm64/libonnxruntime4j_jni.dylib.dSYM/Contents/
ai/onnxruntime/native/osx-arm64/libonnxruntime4j_jni.dylib.dSYM/Contents/Info.plist
ai/onnxruntime/native/osx-arm64/libonnxruntime4j_jni.dylib.dSYM/Contents/Resources/
ai/onnxruntime/native/osx-arm64/libonnxruntime4j_jni.dylib.dSYM/Contents/Resources/DWARF/
ai/onnxruntime/native/osx-arm64/libonnxruntime4j_jni.dylib.dSYM/Contents/Resources/DWARF/libonnxruntime4j_jni.dylib
ai/onnxruntime/native/osx-x64/
ai/onnxruntime/native/osx-x64/libonnxruntime.dylib
ai/onnxruntime/native/osx-x64/libonnxruntime.dylib.dSYM/
ai/onnxruntime/native/osx-x64/libonnxruntime.dylib.dSYM/Contents/
ai/onnxruntime/native/osx-x64/libonnxruntime.dylib.dSYM/Contents/Info.plist
ai/onnxruntime/native/osx-x64/libonnxruntime.dylib.dSYM/Contents/Resources/
ai/onnxruntime/native/osx-x64/libonnxruntime.dylib.dSYM/Contents/Resources/DWARF/
ai/onnxruntime/native/osx-x64/libonnxruntime.dylib.dSYM/Contents/Resources/DWARF/libonnxruntime.dylib
ai/onnxruntime/native/osx-x64/libonnxruntime4j_jni.dylib
ai/onnxruntime/native/osx-x64/libonnxruntime4j_jni.dylib.dSYM/
ai/onnxruntime/native/osx-x64/libonnxruntime4j_jni.dylib.dSYM/Contents/
ai/onnxruntime/native/osx-x64/libonnxruntime4j_jni.dylib.dSYM/Contents/Info.plist
ai/onnxruntime/native/osx-x64/libonnxruntime4j_jni.dylib.dSYM/Contents/Resources/
ai/onnxruntime/native/osx-x64/libonnxruntime4j_jni.dylib.dSYM/Contents/Resources/DWARF/
ai/onnxruntime/native/osx-x64/libonnxruntime4j_jni.dylib.dSYM/Contents/Resources/DWARF/libonnxruntime4j_jni.dylib
ai/onnxruntime/native/win-x64/
ai/onnxruntime/native/win-x64/onnxruntime.dll
ai/onnxruntime/native/win-x64/onnxruntime.pdb
ai/onnxruntime/native/win-x64/onnxruntime4j_jni.dll
ai/onnxruntime/native/win-x64/onnxruntime4j_jni.pdb
ai/onnxruntime/NodeInfo.class
ai/onnxruntime/OnnxJavaType$1.class
ai/onnxruntime/OnnxJavaType.class
ai/onnxruntime/OnnxMap$1.class
ai/onnxruntime/OnnxMap$OnnxMapValueType.class
ai/onnxruntime/OnnxMap.class
ai/onnxruntime/OnnxModelMetadata.class
ai/onnxruntime/OnnxRuntime.class
ai/onnxruntime/OnnxSequence$1.class
ai/onnxruntime/OnnxSequence.class
ai/onnxruntime/OnnxTensor$1.class
ai/onnxruntime/OnnxTensor.class
ai/onnxruntime/OnnxValue$OnnxValueType.class
ai/onnxruntime/OnnxValue.class
ai/onnxruntime/OrtAllocator.class
ai/onnxruntime/OrtEnvironment$OrtEnvCloser.class
ai/onnxruntime/OrtEnvironment$ThreadingOptions.class
ai/onnxruntime/OrtEnvironment.class
ai/onnxruntime/OrtException$OrtErrorCode.class
ai/onnxruntime/OrtException.class
ai/onnxruntime/OrtLoggingLevel.class
ai/onnxruntime/OrtProvider.class
ai/onnxruntime/OrtProviderOptions$1.class
ai/onnxruntime/OrtProviderOptions$OrtProviderSupplier.class
ai/onnxruntime/OrtProviderOptions.class
ai/onnxruntime/OrtSession$Result.class
ai/onnxruntime/OrtSession$RunOptions.class
ai/onnxruntime/OrtSession$SessionOptions$ExecutionMode.class
ai/onnxruntime/OrtSession$SessionOptions$OptLevel.class
ai/onnxruntime/OrtSession$SessionOptions.class
ai/onnxruntime/OrtSession.class
ai/onnxruntime/OrtUtil$1.class
ai/onnxruntime/OrtUtil.class
ai/onnxruntime/providers/
ai/onnxruntime/providers/CoreMLFlags.class
ai/onnxruntime/providers/NNAPIFlags.class
ai/onnxruntime/providers/OrtCUDAProviderOptions.class
ai/onnxruntime/providers/OrtFlags.class
ai/onnxruntime/providers/OrtTensorRTProviderOptions.class
ai/onnxruntime/providers/StringConfigProviderOptions.class
ai/onnxruntime/SequenceInfo.class
ai/onnxruntime/TensorInfo$1.class
ai/onnxruntime/TensorInfo$OnnxTensorType.class
ai/onnxruntime/TensorInfo.class
ai/onnxruntime/ValueInfo.class
GIT_COMMIT_ID
META-INF/
META-INF/MANIFEST.MF
META-INF/maven/
META-INF/maven/com.microsoft.onnxruntime/
META-INF/maven/com.microsoft.onnxruntime/onnxruntime/
META-INF/maven/com.microsoft.onnxruntime/onnxruntime/pom.xml
Privacy.md
ThirdPartyNotices.txt
```
