### ISSUE TITLE
perftest: set parallel executor and thread pool size separately

### ISSUE THREAD

**Issue by letmaik** [microsoft/onnxruntime#1213]
In perftest, currently, there's only `-x <pool_size>` which activates both parallel execution plan and sets the session thread pool size. It would be good for benchmarking to be able to set these things separately. I suggest changing `-x <pool_size>` to only set the pool size (and mentioning that the default is the hw thread count) and add another flag `-P` (or whatever you like) that only enables parallel execution planning, with default being sequential execution plan.

**Comment by snnn** [comment]
Welcome to change it

**Comment by snnn** [comment]
Thanks!
