### ISSUE TITLE
Build fails, complains __builtin_isnan is not a member of std

### ISSUE THREAD

**Issue by SidGATOR** [microsoft/onnxruntime#1215]
**Describe the bug**
Building onnxruntime from source fails for gcc-5.5 for c++11 standard. While building, cmake errors out on onnxruntime/onnxruntime/test/framework/data_type_test.cc on line 363, with error __builtin_isnan is not a member of std. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04) :Ubuntu 18.04.2 LTS
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 0.4.0
- Python version: 3.6.6
- Visual Studio version (if applicable): NA
- GCC/Compiler version (if compiling from source): gcc-5.5
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**To Reproduce**
run "./build.sh --config RelWithDebInfo --build_wheel"

**Expected behavior**
It should build properly

**Screenshots**

**Additional context**

**Comment by SidGATOR** [comment]
Issue can be fixed by added `#include <cmath>`

**Comment by skottmckay** [comment]
Fix is merged.
