### ISSUE TITLE
[ORT 1.12] One test relative to DequantizeLinear op failed to be inferenced.

### ISSUE THREAD

**Issue by fatcat-z** [microsoft/onnxruntime#12151]
**Describe the bug**
The attached onnx file could not be inferenced successfully by ORT 1.12 while the previous ORT could work well.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 20.04.4 LTS
- ONNX Runtime installed from (source or binary):  pip install -i https://test.pypi.org/simple/ ort-nightly==1.12.0.dev20220707003
- ONNX Runtime version: 1.12.0.dev20220707003
- Python version: python 3.7

**To Reproduce**
The attached zip file contains an ONNX file which was generated by one [tf2onnx test](https://github.com/onnx/tensorflow-onnx/blob/9ce72be41ba8db4629e4647624998f2345c37f91/tests/test_optimizers.py#L2366). It could not be inferenced successfully by ORT 1.12 RC. The error is:

onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running DequantizeLinear node. Name:'dequantize' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/quantization/quantize_linear.cc:35 void onnxruntime::PrepareForQDQ(const onnxruntime::TensorShape&, const onnxruntime::Tensor&, const onnxruntime::Tensor*, int64_t, int64_t&, int64_t&, int64_t&) scale.Shape().NumDimensions() == 1 && scale.Shape()[0] == broadcast_dim was false. scale must be 1D tensor with size 5

**Expected behavior**
It should be inferenced successfully, just like previous ORT version.

[test_const_dequantize_transpose_per_channel_origin.zip](https://github.com/microsoft/onnxruntime/files/9092307/test_const_dequantize_transpose_per_channel_origin.zip)

**Comment by yufenglee** [comment]
@skottmckay , could you please help take a look at this issue? It looks like same issue as https://github.com/microsoft/onnxruntime/pull/12099.

We also need to handle axis.

**Comment by skottmckay** [comment]
Did this test pass with the previous version of ORT or is it new? I don't see anything that handles the update to the axis (as Yufeng mentioned) when it's per-axis dequantization so it seems like the transpose optimization should never have worked correctly. possibly the move of the Transpose node didn't get attempted previously so the issue with the transpose optimizer was there but not triggered by this model. 

@TomWildenhain-Microsoft should the DQ processing do something similar to what HandleSimpleNodeWithAxis does?

https://github.com/microsoft/onnxruntime/blob/178a413ca1ae74c3b7c70ee6c07fb86ead61b3c1/onnxruntime/core/optimizer/transpose_optimizer/transpose_optimizer.cc#L1204-L1234

**Comment by fatcat-z** [comment]
> Did this test pass with the previous version of ORT?
> 
> The axis should be handled by
> 
> https://github.com/microsoft/onnxruntime/blob/178a413ca1ae74c3b7c70ee6c07fb86ead61b3c1/onnxruntime/core/optimizer/transpose_optimizer/transpose_optimizer.cc#L1219
> 
> but maybe we're missing a step of updating the attribute in the 'real' node.

Yes, it passed with the previous version of ORT 1.11.1.

**Comment by fatcat-z** [comment]
The issue has gone, so close it.
Thanks!
