### ISSUE TITLE
Transformer Benchmark Failures

### ISSUE THREAD

**Issue by groenenboomj** [microsoft/onnxruntime#12154]
**Describe the bug**
Model export issues are seen on inferencing benchmarks when using PyTorch 1.12.

**Urgency**
High

**System information**
- OS Platform and Distribution: Ubuntu 20.04.1
- ONNX Runtime installed from: source from c6732c079b4fbf644bc939729c87d70195251d83
- ONNX Runtime version: 1.11.1
- Python version: 1.12
- GCC/Compiler version (if compiling from source): 9.4.0
- ROCm version: 5.1.1
- GPU model and memory: MI100 but also fails on other vendors and architectures

**To Reproduce**
To reproduce just spin up an image with PyTorch 1.12 and run the benchmarks in onnxruntime/onnxruntime/python/tools/transformers/ with any of thee following parameters:
```
python benchmark.py -g -m bert-base-cased --sequence_length 32 384 --batch_sizes 1 32 --provider=migraphx -p fp16 --disable_gelu --disable_layer_norm --disable_attention --disable_skip_layer_norm --disable_embed_layer_norm --disable_bias_skip_layer_norm --disable_bias_gelu

python benchmark.py -g -m bert-large-uncased --sequence_length 32 384 --batch_sizes 1 32 --provider=migraphx -p fp16 --disable_gelu --disable_layer_norm --disable_attention --disable_skip_layer_norm --disable_embed_layer_norm --disable_bias_skip_layer_norm --disable_bias_gelu
```

**Fails in PyTorch 1.12 but not 1.13**
```
python benchmark.py -g -m distilgpt2 --model_class AutoModelForCausalLM --sequence_length 32 384 --batch_sizes 1 8 --provider=migraphx -p fp16 --disable_gelu --disable_layer_norm --disable_attention --disable_skip_layer_norm --disable_embed_layer_norm --disable_bias_skip_layer_norm --disable_bias_gelu
```

**Failure message:**

```
Run onnxruntime on bert-large-uncased with input shape [1, 32]
Exception
Traceback (most recent call last):
  File "benchmark.py", line 599, in main
    args.model_source, args)
  File "benchmark.py", line 178, in run_onnxruntime
    ort_outputs = ort_session.run(ort_output_names, ort_inputs)
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: input_ids for the following indices
 index: 1 Got: 32 Expected: 512
 Please fix either the inputs or the model.
```

**Expected behavior**
We expect the benchmark to finish and provide performance results.

**Additional context**
This was tested with CUDA and ROCm execution providers and the PyTorch level is what allows reproduction.  Both BERT runs are hitting model issues.

**Comment by tianleiwu** [comment]
@[groenenboomj](https://github.com/groenenboomj), Thanks for reporting the issue. The cause is symbolic shape inference is used in converting fp32 model to fp16, and it changes input shape [batch_size, seq_len] to [batch_size, 512]. I will provide a fix later.

Note that benchmarking fp32 model will not trigger this issue.

**Comment by groenenboomj** [comment]
Great, we need the fp16 version of this model working for some testing.  Let us know if you need more information.

**Comment by tianleiwu** [comment]
@[groenenboomj](https://github.com/groenenboomj), you can git clone and run the script in master branch. 
In my machine, I could runt the script with cuda EP (after removing `--provider=migraphx`).

**Comment by groenenboomj** [comment]
When I tested I saw it on the tensorRT and migraphx backends. Was there a change recently? I can retest.

**Comment by groenenboomj** [comment]
The issue is resolved.  Thanks!
