### ISSUE TITLE
how to use cuda?

### ISSUE THREAD

**Issue by dmjeong** [microsoft/onnxruntime#12186]
env
visual studio 2019
windows10
onnx-runtime 1.11.0
cuda 11.3
cudnn8.2.2

now i can use cpu processing

but i got some problem when i try to use cuda processing

i search lots of things about it but still i can not solve it

it is my code below

const OrtApi* api = OrtGetApiBase()->GetApi(ORT_API_VERSION);
OrtCUDAProviderOptionsV2* cuda_options = nullptr;
api->CreateCUDAProviderOptions(&cuda_options);
api->SessionOptionsAppendExecutionProvider_CUDA_V2(sessionOptions, cuda_options);
api->ReleaseCUDAProviderOptions(cuda_options);

there is no error when i run this code

but inference speed is same as using cpu

what am i wrong?

please help me

thank you

**Comment by dmjeong** [comment]
i fi

**Comment by dmjeong** [comment]
i solved it sorry

**Comment by LYF915** [comment]
What did you find the problem at the end?

> i solved it sorry
