### ISSUE TITLE
[Documentation Request] Update Documentation for ARM Cross-Compilation on Linux

### ISSUE THREAD

**Issue by LauSto** [microsoft/onnxruntime#12198]
The documentation states that the current version of protobuf used is 3.11.2. The actual version used is 3.18.1. Utilizing version 3.11.2 yields errors when calling make.

---
#### Document Details
* Title: Build for inferencing
* Page: [https://onnxruntime.ai/docs/build/inferencing.html](https://onnxruntime.ai/docs/build/inferencing.html)
* Page Source: inferencing.md

**Comment by natke** [comment]
Thank you for finding and reporting this issue @LauSto. If you want to take your contribution a step further you could update the page (using the "Edit in GitHub" link at the bottom of the page). Thanks again!

**Comment by pranavsharma** [comment]
This is the commit id we use https://github.com/microsoft/onnxruntime/blob/4bf22e2a40b5cbc8193f985bd784693d07e0e3b5/cgmanifests/generated/cgmanifest.json#L354-L362. It corresponds to 3.18.1.

**Comment by LauSto** [comment]
I see you just had the same idea :). I also wanted to include instructions for specifying the target arch in the toolchain, but @snnn already made a pull request for that (#8710). However the pull request was never approved. Could you add these changes?

**Comment by natke** [comment]
That would be great @snnn, thank you!

**Comment by natke** [comment]
Fixed by #12198 #12242
