### ISSUE TITLE
symbolic_shape_infer infinite loop

### ISSUE THREAD

**Issue by tianleiwu** [microsoft/onnxruntime#12192]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.

symbolic_shape_infer seems have issue to process gpt-2 model. It goes in an infinite loop during processing the model.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

Not urgent

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master 
- Python version: 3.8
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11.0
- GPU model and memory: GTX 1080

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

To reproduce the issue, install PyTorch 1.12, transformers 4.18.0, and ort nightly build.

```
python -m onnxruntime.transformers.models.gpt2.benchmark_gpt2 -m gpt2 --precision fp16 -o -b 1 --sequence_lengths 2 -s 3 --use_gpu
```

The onnx model can be found in ./onnx_models/gpt2_past_fp32.onnx

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by HaoboGu** [comment]
I have the same problem in latest ort 1.12.0:
<img width="850" alt="image" src="https://user-images.githubusercontent.com/8640918/180751189-d0fae0c1-e547-45ff-8635-f6c200e5bd30.png">

**Comment by Hzfinfdu** [comment]
Is there any followup in this issue? I have the same problem as @HaoboGu posted in ort 1.13.1. I am also trying to do symbolic shape infer on a gpt2 model with past kvs.
