### ISSUE TITLE
Failed to load pdb file for onnxruntime.dll when using OnnxRuntime.DirectML

### ISSUE THREAD

**Issue by Nagamani71** [microsoft/onnxruntime#12193]
I am getting "A matching symbol file was not found in this folder" error while loading onnxruntime.pdb file downloaded from

https://github.com/microsoft/onnxruntime/releases/download/v1.11.0/Microsoft.AI.MachineLearning.1.11.0.symbols.zip

I am using following nuget package 
"nuget": {
                    "name": "Microsoft.ML.OnnxRuntime.DirectML",
                    "version": "1.11.0"
                }

**Comment by fdwr** [comment]
@Nagamani71 🤔 Hmm, that symbol mismatch issue doesn't sound specific to the DML package given it's for `onnxruntime.pdb`. Do you get the same symbol mismatch with the non-DML package https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime? I presume this is with Visual Studio 2019?

**Comment by Nagamani71** [comment]
Hi @fdwr , I am trying to debug https://github.com/microsoft/DirectML/tree/master/DxDispatch with "mobilenetv2-7.onnx" model. Yes, I am using Visual Studio 2019.

**Comment by RyanUnderhill** [comment]
Can you paste the information from the Modules debugger window saying the Name/Path/Version/Timestamp info from the onnxruntime.dll you have loaded?

**Comment by Nagamani71** [comment]
@RyanUnderhill, here are the details:
onnxruntime.dll	onnxruntime.dll	C:\workspace\DirectML\DxDispatch\build\win-x64\Debug\onnxruntime.dll	N/A	Yes	Cannot find or open the PDB file.		19	1.11.20220321.2.b713855	3/21/2022 11:52 AM	00007FFFC2620000-00007FFFC2F59000	[12396] dxdispatch.exe

**Comment by nums11** [comment]
Closing as stale.
