### ISSUE TITLE
> > `WebGLBackend 2021-10-19T19:05:16.905Z|Unable to initialize WebGLBackend. ReferenceError: document is not defined`

### ISSUE THREAD

**Issue by Amadeuy** [microsoft/onnxruntime#12203]
> > `WebGLBackend 2021-10-19T19:05:16.905Z|Unable to initialize WebGLBackend. ReferenceError: document is not defined`
> > 
> > 
> > 
> > Is there any other way we can initialize WebGL
> 
> 

__Originally posted by @Amadeuy in https://github.com/microsoft/onnxruntime/issues/9458#issuecomment-1186343009__

__Originally posted by @Amadeuy in https://github.com/microsoft/onnxruntime/issues/12202__

**Comment by fs-eire** [comment]
As you mentioned in this issue, it is the same issue to #9458. Please don't create duplicated issue.
