### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by tulasiram58827** [microsoft/onnxruntime#12208]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): 1.11
- ONNX Runtime version: 1.11
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 7.5
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**

While building from source I am getting this error

```
src/onnxruntime/core/providers/cpu/nn/string_normalizer.cc:11:26: error: missing binary operator before token "or"
 #elif defined(__APPLE__) or defined(__ANDROID__)
                          ^~
```

Command Used:

```
./build.sh --config Release --build_shared_lib --parallel --use_dnnl 
```

Any idea on this error?

**Comment by yuslepukhin** [comment]
I don't know the reason behind it, but you can simply replace `or` => `||`

**Comment by tulasiram58827** [comment]
Issue solved after updating. But I need to make similar change in 2-3 files I guess. Thanks for the PR.
