### ISSUE TITLE
Why is there a cudaStreamSynchronize on the end of the run

### ISSUE THREAD

**Issue by skakunm** [microsoft/onnxruntime#12216]
**Describe the bug**
Is there a need for cudaStreamSynchronize when using Cuda execution provider and when code before and after the inference is on the GPU and in the same stream? I'm trying to run multiple inferences from same CPU thread on multiple GPU streams.

**Urgency**
No urgency.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.10
- Python version: 3.8
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2
- GPU model and memory: 2080 Ti

**To Reproduce*
Looking at Nsight Systems and running a model revealed that there is a cudaStreamSynchronize, source code also confirms:
https://github.com/microsoft/onnxruntime/blob/0d6cbc6e57c2ecd0722cefaa87d300f301864e3b/onnxruntime/core/session/inference_session.cc#L1991
https://github.com/microsoft/onnxruntime/blob/927bac0f862d56bed135c451424ae39467e5b530/onnxruntime/core/providers/cuda/cuda_execution_provider.cc#L411

If there is no memory copy from GPU to CPU after the inference (if the Ort::Value of the output is on the GPU), there is no real need to force CPU synchronization to the GPU.

**Expected behavior**
I would expect that the GPU stream is not forcefully synchronized, especially if the user has specified a stream, and provides an output variable that is on the GPU.

**Screenshots**
No screenshots

**Additional context**
This should be applicable to any model.

**Comment by hariharans29** [comment]
That is because Ort::Run() is a synchronous API and we need to guarantee that all the operations enqueued on the device has completed before returning back. If at any time in the future, there is an async Run() API then we do not need the cudaStreamSynchronize() then.

**Comment by skakunm** [comment]
In the case I specified it would still technically be synchronous. Any usage of the output memory on the CPU (memory copy from gpu to cpu) would cause an automatic stream synchronization. Also, execution would be synchronous on the GPU in that stream. The cudaStreamSynchronize would be required only to synchronize different streams, but if user is already specifying streams, I guess the user should know how to synchronize the streams as well. Anyway, I understand why this would be considered an async run. I just think enabling it either way would be useful.

**Comment by hariharans29** [comment]
The users don't always specify the stream. When the users don't, the CUDA EP creates a stream to use. Are you proposing conditional logic like the following:  don't sync when the user specifies the stream && sync when the CUDA EP maintains its own stream ?

**Comment by skakunm** [comment]
That sounds like the simplest way to implement it, or some "no stream sync" or "async run" flag.

**Comment by hariharans29** [comment]
Since this is essentially an ask for async Run(), marked it as enhancement. Not sure if this is in the planned list of work-items in the near future though.

**Comment by gedoensmax** [comment]
This is extremely important to have a performance optimal pipeline. I would love to see an asynchronous API in ORT.

**Comment by skakunm** [comment]
I also don't see how is this different from user's point of view in terms of sync/async. Because as soom as user copies output from GPU to CPU there will be an implicit sync. Or if user adds some GPU functions after Run those will be after the Run, which is expected. And if user does some stuff unrelated to the output, it doesn't really matter if the output is really ready. I think of Run as a standard Cuda kernel when it runs on GPU, and it is not standard practice that Cuda kernels call cudaDeviceSynchronize() inside. There is just no need for this, since there is automatic synchronization. And if someone does need something more advanced, it is not possible due to this non standard Cuda implementation.

**Comment by gedoensmax** [comment]
@hariharans29 Would it be an option to add an `run_async` floag to the session creation optionf for CUDA and TensorRT Execution provider and decide based on this how the synchronous behaviour is used ?

**Comment by gedoensmax** [comment]
Just found https://github.com/microsoft/onnxruntime/commit/b5904c40dd781f13739d471ba088911386f2c01d#diff-a57e626ba456c2386c8a00eabf477ec075027fc12f0a6054e46c594cdef687ba which seems to contain the changes we are talking about but only exposes them to python. Should i take care of also enabling this change in C and CPP  or will someone else possibly do that ?

**Comment by gedoensmax** [comment]
@pranavsharma I think this can be closed now right ?

**Comment by jywu-msft** [comment]
resolved by https://github.com/microsoft/onnxruntime/pull/14088
