### ISSUE TITLE
C++ ONNXRuntime predictions are all zero

### ISSUE THREAD

**Issue by wenhwu** [microsoft/onnxruntime#12231]
**Describe the bug**

The Python ONNXRuntime predictions are fine, but the C++ ONNXRuntime predictions are all zero.

Please see the [OnnxRuntimeDemoGPUTest](https://github.com/wenhwu/OnnxRuntimeDemoGPUTest) for details and reproduce the problem.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  **win10**
- ONNX Runtime installed from (source or binary):  **NuGet, Microsoft.ML.OnnxRuntime.Gpu.1.11.0**
- ONNX Runtime version: **Microsoft.ML.OnnxRuntime.Gpu.1.11.0**
- Python version: **Python3.7.6**
- Visual Studio version (if applicable): **VS2019**
- GCC/Compiler version (if compiling from source):  None
- CUDA/cuDNN version: **CUDA10.2, CuDNN7.6.5**
- GPU model and memory: **Nvidia GTX2080 8G**

thanks

**Comment by hariharans29** [comment]
Under the hood, the Python and C++ runtimes use the same core engine. Are you sure the raw input tensors (after image pre-processing) are exactly same in Python and C++ ?

**Comment by wenhwu** [comment]
@hariharans29, thanks

I have carefully checked the inputs (after image pre-processing) for both and found them to be the same.
