### ISSUE TITLE
Protobuf error in Onnx Model Zoo github repo when validating models

### ISSUE THREAD

**Issue by IzanCatalan** [microsoft/onnxruntime#12235]
**Describe the bug**
I'm using Onnx Model Zoo GitHub repo (https://github.com/onnx/models). I tried to execute in Jupyter Notebook via Visual Studio Code and replicate in a separate python script the "imagenet_validation.ipynb" file under models/vision/classification path (https://github.com/onnx/models/tree/main/vision/classification).
I also tried to execute "onnxrt_inference.ipynb" example using onnxruntime.

However, after installing all dependencies I always get some errors no mater the onnx model file (squeeznet or resnet) (see de images).

I don't understand why these errors, apparently is because Protobuf and MXnet loading method fail when the model is loaded. It does not recognize quantize models or these models are not parsing correctly after quantization. Either way, those errors are estrange, because those models are officials files in the official GitHub repo.

  101     raise google.protobuf.message.DecodeError(
  102         "Protobuf decoding consumed too few bytes: {} out of {}".format(
  103             decoded, len(s)))

Maybe someone can help me or give me some guidelines to solve o at least, replicate these imaginet validation files.
Which is the setup to make them work? which frameworks or dependencies versions should be installed?

Thank you,

Izan

**Urgency**
I would like to know the answer as soon as possible, because I cannot find another repo or method to calculate the entire data-set accuracy using Imaginet and ONNX pretrained models.  

**System information**
- OS Platform and Distribution: Ubuntu 20.04.4 LTS
- ONNX Runtime installed from pip: 1.9.0
- Python version: 3.8.10
- Visual Studio version (if applicable):  1.69.0
- GCC/Compiler version (if compiling from source): 9.4.0
- CUDA/cuDNN version: NO NEED, CPU use only, Python and Jupyter notebooks
- GPU model and memory: NONE
- gluoncv version: 0.10.5
- matplotlib version: 3.4.3
- numpy version: 1.22.3
- mxnet version: 1.9.0.
- onnx version: 1.11.0
- protobuf version: 3.16.0

**To Reproduce**
All is described on jupyter notebooks at github repo on these links:

https://github.com/onnx/models/blob/main/vision/classification/imagenet_validation.ipynb
https://github.com/onnx/models/blob/main/vision/classification/onnxrt_inference.ipynb

You only have to follow the commands, download github repo and imagenet dataset, open jupyter notebooks via Visual Studio Code and see if it works. 

**Expected behavior**
What it should happen is that you should see the predictions on onnxrt_inference.ipynb and, the top 1 or top 5 accuracy on imagenet_validation.ipnb:

Top-1 accuracy: 0.56336, Top-5 accuracy: 0.7912

**Screenshots**
![post3](https://user-images.githubusercontent.com/40836734/179766394-8a6c7d41-32a3-4063-980f-db4eb51635ba.png)
![post2](https://user-images.githubusercontent.com/40836734/179766397-184fd73d-c266-43ad-a5e8-926af994f478.png)
![post1](https://user-images.githubusercontent.com/40836734/179766400-1181967f-5914-422a-ada7-5857f1cc81a7.png)

**Comment by jcwchen** [comment]
Hi @IzanCatalan,

For notebooks related to mxnet in ONNX Model Zoo, probably many of them cannot work with the latest mxnet and onnx, because  onnx import module from mxnet has not been maintained for a long time. See issue: https://github.com/apache/incubator-mxnet/issues/20985. To solve that, the notebook was contributed in 07/2019 so perhaps you can try mxnet 1.4.1 (released on 05/2019) with corresponding ONNX version if you really want to use mxnet. Also please note that I don't think mxnet's onnx importer supports quantization-based ONNX operators so probably you cannot run any quantized ONNX model with mxnet.

Or, you can always try ONNX Runtime (ORT) to inference the ONNX Model Zoo models. I have verified the models couple weeks ago with ORT's CPU provider and most of them should work well. If you see any issue with ORT on ONNX Model Zoo models, please file an issue in https://github.com/onnx/models/issues.

Regarding https://github.com/onnx/models/blob/main/vision/classification/onnxrt_inference.ipynb, it works fine in my local with the latest onnx and onnxruntime, may I understand what errors did you get for this notebook?

**Comment by jcwchen** [comment]
> Do you know another way or framework to validate accuracy for quantize or not quantize onnx models with imagenet dataset?

ONNX Runtime (ORT) supports backward compatibility so I believe even latest ORT is still reliable (quantize and no quantize) with ancient ONNX models. As mentioned above, I have verified [this notebook](https://github.com/onnx/models/blob/main/vision/classification/onnxrt_inference.ipynb) (which takes resnet50 as an example). Please give it a try and let me know if there is any issue. Thanks!

**Comment by IzanCatalan** [comment]
Yes, I already saw it, however with that notebook, you only check the probability of one image. Therefore, if I want to use the entire Imagenet Dataset, should I pass all images one by one? Otherwise, how I can get the top1 69.93%  and top5 89.29% values for Resnet18 accuracy tested on https://github.com/onnx/models/tree/main/vision/classification/resnet ? Thanks!!

**Comment by IzanCatalan** [comment]
I also updated my numpy version to 1.23.1, my onnx to 1.12.0 and onnxruntime to 0.1.4 in order to check https://github.com/onnx/models/blob/main/vision/classification/onnxrt_inference.ipynb , however this is the output
![onnxrt](https://user-images.githubusercontent.com/40836734/180246875-0214d784-db0a-4188-bbcc-beabe9d8d1fe.png)
:

**Comment by jcwchen** [comment]
> therefore, if I want to use the entire Imagenet Dataset, should I pass all images one by one? Otherwise, how I can get the top1 69.93% and top5 89.29% values for Resnet18 accuracy

The demo code for onnxruntime only provides inference example for single image. Thus you need to write your own code to go through the whole dataset and get top1/top5 accuracy results. IIUC, not every ONNX Model Zoo model supports batch. If you do see symbolic dimension in the input, you can try to run onnxruntime by giving a batch. At least recently we just batchified ResNet models: https://github.com/onnx/models/pull/537.

> @jcwchen I also updated my numpy version to 1.23.1 and my onnx to 1.12.0 in order to check https://github.com/onnx/models/blob/main/vision/classification/onnxrt_inference.ipynb , however this is the output

It seems like an output limitation from Visual Studio Code, although I don't see this error from my VSCode (perhaps different settings). You can either modify the settings for output (see [here](https://stackoverflow.com/questions/72823258/vscode-interactive-python-output-exceeds-size-limit)) or run the notebook via other ways (for instance, put them into a python file).
