### ISSUE TITLE
clean up build instructions for ORT Web

### ISSUE THREAD

**Issue by fs-eire** [microsoft/onnxruntime#12244]
This is an issue for tracking document clean up for ONNX Runtime Web build instructions.

Currently the build instructions are not clean. There are 2 places with similar contents:

- https://github.com/microsoft/onnxruntime/blob/master/js/README.md#Build-2
- https://onnxruntime.ai/docs/build/web.html

The current status causes some developers confusing (eg. #11691).

Here is the plan:
- use only one place for build instructions. This place will be https://onnxruntime.ai/docs/build/web.html.
- [x] [action item] revise the doc to keep instructions up-to-date
- [x] [action item] after (2) is done, remove the duplicated contents from /js/README.md and add a link to the document in (2).

**Comment by natke** [comment]
Thank you for this @fs-eire. Are you able to make the changes, or do you need someone else to do it?

**Comment by fs-eire** [comment]
> Thank you for this @fs-eire. Are you able to make the changes, or do you need someone else to do it?

@shalvamist is doing #12247. This PR is still ongoing

**Comment by shalvamist** [comment]
Hey All,

I think that we addressed and updated the documentation for ORT web building.
In addition, we added an ORT Web build script to simplify the process - [PR link](https://github.com/microsoft/onnxruntime/pull/12643)

Can we close the issue ?

Thanks

**Comment by natke** [comment]
Yes, I think so. Looks good! @fs-eire are you happy to close this?

**Comment by natke** [comment]
Fixed by #12247
