### ISSUE TITLE
Some love for MacOS gpu

### ISSUE THREAD

**Issue by evrial** [microsoft/onnxruntime#12252]
```
$ pip install onnxruntime-gpu
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu
```
Please make wheels, god bless

**Comment by snnn** [comment]
onnxruntime-gpu depends on CUDA. From what I know, CUDA on macOS is not a thing. Therefore we don't want to spend on it.

**Comment by evrial** [comment]
Ok thanks, makes sense

**Comment by snnn** [comment]
Thank you for being interested in ONNX Runtime. If you have any other questions, welcome to reach out us.  I'd love to provide help.

Take care!

**Comment by snnn** [comment]
Nvidia only provide CUDA downloads for two operating system: Linux and Windows.  See: https://developer.nvidia.com/cuda-downloads . macOS users need to use coreml for GPU acceleration, or webgpu which we are still developing the support.
