### ISSUE TITLE
Failed to compile from the source with cuda on windows 10 (The CMAKE_CUDA_ARCHITECTURES do not all work with this compiler)

### ISSUE THREAD

**Issue by shizidushu** [microsoft/onnxruntime#12272]
**Describe the bug**
Failed to compile from the source with cuda on windows 10.

**Urgency**
none

**System information**
- Python version: 3.8
- Visual Studio version (if applicable): 2022
- CUDA/cuDNN version: cudnn-windows-x86_64-8.3.3.40_cuda11.5
- GPU: RTX 3060
- System: Windows 10

**To Reproduce**
```bash
git clone --recursive https://github.com/Microsoft/onnxruntime
cd onnxruntime
.\build.bat --cmake_generator "Visual Studio 17 2022" --build_shared_lib --parallel --use_cuda --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5" --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5"  --config Release --cuda_version "11.5" --cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES=75;80;86;87"
```

It says  
    
    The CMAKE_CUDA_ARCHITECTURES:
    
        75;80;86;87
    
      do not all work with this compiler

**Expected behavior**
no error

**Screenshots**
![Snipaste_2022-07-22_02-04-02](https://user-images.githubusercontent.com/13694980/180283157-5b0debc6-b6f1-485c-a5fb-3f960c5cc908.png)

**Comment by snnn** [comment]
Search your GPU name in https://developer.nvidia.com/cuda-gpus, then only keep that number in the list.
