### ISSUE TITLE
Ort::Session has no "FromArrayWithPrepackedWeightsContainer"  interface

### ISSUE THREAD

**Issue by heliqi** [microsoft/onnxruntime#12285]
**Is your feature request related to a problem? Please describe.**
As shown in the figure below:
There are "CreateSessionFromArrayWithPrepackedWeightsContainer" interfaces in OrtApi, but there is no corresponding interface in Ort::Session

![image](https://user-images.githubusercontent.com/34152981/180415909-93ecb9f1-29c1-4531-b636-cbdd08c5fe9b.png)

**System information**
- ONNX Runtime version (you are using):  1.11.1

**Describe the solution you'd like**
I would like to add a corresponding constructor in Ort::Session so that I don't have to switch between Ort::Session and OrtApi

**Comment by zhanghuanrong** [comment]
Thanks for the suggestion. Yet I am not sure the reasoning behind it. Could you give more specific reason?

**Comment by hariharans29** [comment]
@heliqi - Do you have a use-case of using a prepacked weights container AND still contruct a session from a byte array ? At the time we introduced th prepacked weights container, we did not have such a use-case and hence this ctor was not added.

**Comment by heliqi** [comment]
@hariharans29  Yes, Ort::Session doesn't expose that ctor in the c++ API but C API has it . Thanks!

**Comment by heliqi** [comment]
> Thanks for the suggestion. Yet I am not sure the reasoning behind it. Could you give more specific reason?

@zhanghuanrong  I created some of the same sessions using the C++ API, but it consumes too much memory. 
I want to use "PrepackedWeightsContainer"  save memory, but  Ort::Session doesn't expose that ctor.
