### ISSUE TITLE
W:onnxruntime:, execution_frame.cc:811 VerifyOutputSizes] Expected shape from model of {800,10} does not match actual shape of {32,10} for output 499

### ISSUE THREAD

**Issue by xxxleonxx** [microsoft/onnxruntime#12284]
May I use onnxruntime in linux ,I have got this "W:onnxruntime:, execution_frame.cc:811 VerifyOutputSizes] Expected shape from model of {800,10} does not match actual shape of {32,10} for output 499" warning, so,how can i do it?

**Comment by zhanghuanrong** [comment]
Generally this is caused either a)  some incorrect tensor information in the onnx model. b) onnxruntime bug.
Most of them are caused by a), specially when the model could give you correct result by onnxruntime.
you could clean the model by remove some value_info.
