### ISSUE TITLE
How to limit the cpu_num to 1?

### ISSUE THREAD

**Issue by flak1990** [microsoft/onnxruntime#1228]
**Describe the bug**
i converted a tensorflow-1.7 model to onnx model, and wish to run it with only 1 cpu core.  
but the onnxruntime.SessionOptions() seems does not make effect. How can i control the cpu core nums like we do in tensorflow?

**System information**
- OS Platform and Distribution: CentOS Linux release 7.5.1804 (Core)
- ONNX Runtime installed from : binary
- ONNX Runtime version: 0.4.0
- Python version:3.6.6
- Visual Studio version (if applicable):None
- GCC/Compiler version (if compiling from source):None
- CUDA/cuDNN version:CUDA-9.0.176, cudnn705
- GPU model and memory: not GPU model

**To Reproduce**
* our codes for session config
```python
sessionOptions = onnxruntime.SessionOptions()
sessionOptions.enable_sequential_execution = False
sessionOptions.session_thread_pool_size = 1
self.session = onnxruntime.InferenceSession(self.FLAGS.checkpoint_path, sess_options=sessionOptions)
```  

* other codes to generate variables
```python
input_x_word = self.session.get_inputs()[0].name
input_x_mask = self.session.get_inputs()[1].name
input_x_length = self.session.get_inputs()[2].name
dropout_keep_prob = self.session.get_inputs()[3].name
predict = self.session.get_outputs()[0].name
logits = self.session.get_outputs()[1].name
```

* other codes for session.run
```python
feed_dict = {input_x_word: np.array(x_word_batch, dtype=np.int32),
                    input_x_length: np.array(x_length_batch, dtype=np.int32),
                    input_x_mask: np.array(x_mask_batch, dtype=np.int32),
                    dropout_keep_prob: np.array([1.0], dtype=np.float32),
                    }
predict_, logits_ = self.session.run([predict, logits], feed_dict)
```

* it can work but th cpu count is usually 600%~800%, i can not use only one cpu core.  
![微信截图_20190614161233](https://user-images.githubusercontent.com/20789417/59494230-4f30b280-8ebf-11e9-83fc-2361e678bc05.png)

**Expected behavior**
The cpu count by top or htop is not more than 100.0% after the model is loaded

**Comment by flak1990** [comment]
i've already tried to set the OMP_NUM_THREADS to 1, or/and set SessionOptions.enable_sequential_execution to True, but it still has no effect. (The default value of sessionOptions.enable_sequential_execution is True)  
Perhaps it really needs to enhance...

**Comment by snnn** [comment]
Fixed in master branch. Please try it again. If you don't enable openmp, and if your model doesn't have any RNN ops, it should be ok.
