### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by Ziba-li** [microsoft/onnxruntime#12298]
First of all, thank you for seeing this question from me.
I'm trying to convert the VIT model to onnx format, but it keeps saying:
 `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`
I'm using the pytorch framework. This is my code:

`
def vit2onnx():

    clipmodel, preprocess = clip.load("./ViT-L-14-336px.pt")

    clipmodel.to(device)

    pilimg = Image.fromarray(cv2.cvtColor(cv2.imread("./1.png"), cv2.COLOR_BGR2RGB))

    image = preprocess(pilimg).unsqueeze(0).to(device)

    text1 = clip.tokenize("white").to(device)

    torch.onnx.export(clipmodel, (image, text1), "vit.onnx", opset_version=11, verbose=True).to(device)
`

But I can do it on Mac, only the parameters are wrong. look at this image.How can i  solve this mistake?
![image](https://user-images.githubusercontent.com/90883114/180594954-29f64033-7ad6-4978-b466-f7c9d4725f50.png)

**Comment by skottmckay** [comment]
That would be an issue with torch.onnx.export in creating the ONNX model rather than in ONNX Runtime which would execute an ONNX model.

https://github.com/pytorch/pytorch/issues/72175 may be of help. If not, the PyTorch Issues is where you should move this question.

**Comment by Ziba-li** [comment]
Thank you for your reply. I have solved the problem. The solution is here https://github. com/LEDNIK7/clip-onnx.

**Comment by zengjie617789** [comment]
@Ziba-li this link is a repo, can you tell solution in detail ?
https://github.com/Lednik7/CLIP-ONNX
