### ISSUE TITLE
MeanVarianceNormalization operator test uses undocumented attributes in ONNX.

### ISSUE THREAD

**Issue by tsocha** [microsoft/onnxruntime#1230]
In [ONNX documentation of MeanVarianceNormalization](https://github.com/onnx/onnx/blob/master/docs/Operators.md#MeanVarianceNormalization) there should be only an `axes` attribute.

But [this test](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/providers/cpu/tensor/tensor_op_test.cc#L500-L519) in testsuite uses attributes which are undocumented in ONNX standard.
`across_channels` and `normalize_variance`

Please explain.

**Comment by hariharans29** [comment]
Hi @tsocha,

The test you are referring to tested the opset 7 version of the operator -  

https://github.com/microsoft/onnxruntime/blob/2148827d3a82916da45a24a99a52996ed56772c5/onnxruntime/test/providers/cpu/tensor/tensor_op_test.cc#L499

The opset 7 version (corresponding to ONNX release 1.2) of the operator is documented here - 

https://github.com/onnx/onnx/blob/rel-1.2.3/docs/Operators.md#MeanVarianceNormalization and as you can see it does have those attributes.

Thanks

**Comment by hariharans29** [comment]
Closing this for now. Please re-open in case you need more clarifications.

**Comment by tsocha** [comment]
Thanks for your reply.

I suspected that test was prepared for old MeanVarianceNormalization but I didn't found it in [Operator Changelog](https://github.com/onnx/onnx/blob/master/docs/Changelog.md) and that is a reason why I asked about this test.

**Comment by hariharans29** [comment]
Hi @tsocha,

I am not sure how the Changelog is created/maintained honestly. But the way I go about finding an operator spec for a specific opset version is to try and map it to particular ONNX release. Like in the case, for opset 7, I looked at 1.2.x, for opset 8 it would be 1.3.x and so on. Hope this helps for the future.

Thanks
