### ISSUE TITLE
What header files/ lib i need to deploy my model using onnxruntime in C++

### ISSUE THREAD

**Issue by Ray-0403** [microsoft/onnxruntime#12304]
Hi, i want to deploy my ML model in C++ using onnxruntime. I know i need to include onnxruntime_cxx_api.h at the head of my code, but i wonder is it the only header file i need to deploy model using onnxruntime in C++? Is there any other header file/ lib i need to place to my folder? (i need to run my code remotely using onnxruntime in the end, so i wann know what other files i need to upload to the remote folder)

**Comment by snnn** [comment]
>  is it the only header file i need to deploy model using onnxruntime in C++?
Yes, as you said.
