### ISSUE TITLE
Licence the ONNX Runtime Java Inference

### ISSUE THREAD

**Issue by cugurm** [microsoft/onnxruntime#12306]
Hi, 

We'd like to license _the ONNXRuntime Java Inference_ into our product. 

Does _the ONNXRuntime Java Inference 1.12.0_ ([maven link](https://mvnrepository.com/artifact/com.microsoft.onnxruntime/onnxruntime/1.12.0)) have any dependency on _the ONNXRuntime Core_?

Many thanks for considering my request.
Milan

**Comment by Craigacp** [comment]
The jar file for the ORT Java API contains a compiled version of the ONNX Runtime native shared library for each platform (`libonnxruntime.so`, `onnxruntime.dll` and `libonnxruntime.dylib`).

**Comment by cugurm** [comment]
Thanks!
