### ISSUE TITLE
Creating a tensor causes an error in C++ program using GPT2 with beam search

### ISSUE THREAD

**Issue by Zapotecatl** [microsoft/onnxruntime#12300]
**Creating a tensor causes an error in C++ program using GPT2 with beam search**

I am doing a program in C++ using the  gpt2_beam_search.onnx. My program crash when I call the function:

`CreateTensor(const OrtMemoryInfo * info, void* p_data, size_t p_data_byte_count, const int64_t * shape, size_t shape_len, ONNXTensorElementDataType type)`

I suspect that there is a error between the shape of my input and the creation of my input tensor, but I can not find that. The shape of my input is:

`const array<int64_t, 2> input_shape = { 1, input_ids.size() * sizeof(int32_t) };`

Any help is appreciated!

**To Reproduce**

I export the GPT 2 model with the Beam Search option with the following command:

`python convert_generation.py -m gpt2 --output C:\\workspace\\onnxruntime\\onnxruntime\\python\\tools\\transformers\\Output2\\gpt2_beam_search.onnx`

The model has the next arquitecture:

![GPT2BeamSearch](https://user-images.githubusercontent.com/6554457/180692937-074271ff-913c-4878-a624-4c1f7ee9eec3.jpg)

I did a python script base on test_gpt_model of convert_generation.py, the gpt2_beam_search.onnx works fine.

My program in C++:

```
#include <iostream>
#include <onnxruntime_cxx_api.h>

using namespace std;
using namespace Ort;

int main()
{
	auto model_path = L"C:\\workspace\\onnxruntime\\onnxruntime\\python\\tools\\transformers\\Output2\\gpt2_beam_search.onnx";

	// create session
	Ort::Env env;
	Ort::Session session(nullptr);
	SessionOptions sess_options;

	//string execution_providers = "CPUExecutionProvider";
	sess_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_DISABLE_ALL);
	sess_options.SetExecutionMode(ExecutionMode::ORT_SEQUENTIAL);

	session = Ort::Session(env, model_path, sess_options);

	constexpr int32_t k_input_size = 128;
	std::vector<int32_t> input_ids(k_input_size);

	const array<int64_t, 2> input_shape = { 1, input_ids.size() * sizeof(int32_t) };

	auto memory_info = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU);
	std::vector<Ort::Value> input_tensors;
	//Format: CreateTensor(const OrtMemoryInfo * info, void* p_data, size_t p_data_byte_count, const int64_t * shape, size_t shape_len, ONNXTensorElementDataType type)

       //-------------------------THE CRASH HAPPEN HERE---------------------------------------------------
	input_tensors.push_back(Ort::Value::CreateTensor(memory_info, input_ids.data(), (size_t)input_ids.size() * (size_t)sizeof(int32_t), input_shape.data(), input_shape.size(), ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_INT32));

	cout << "GPT2 Beam Search " << endl;
}
```

**System information**
Windows 10 64 bits
CMake 3.23.2
ONNX Runtime version: 1.12
Python version: 3.9.7
Microsoft Visual Studio Community 2019 Versión 16.11.15
GPU model and memory: NVIDIA GeForce RTX 2080

**Screenshot of crash**

![Error](https://user-images.githubusercontent.com/6554457/180695200-7b9a2ecc-d3cb-4127-a47d-4a7a2c585acf.jpg)

**Comment by tianleiwu** [comment]
I think the following line has problem:
```
const array<int64_t, 2> input_shape = { 1, input_ids.size() * sizeof(int32_t) };
```
I guess you are creating a tensor with shape (1, 128). There is no need to multiply size of int32_t.

Here is an example of CreateTensor:
https://github.com/microsoft/onnxruntime/blob/b038f4e56f90a810b47cf8176b84306a4c8bed57/onnxruntime/test/wasm/test_inference.cc#L13-L17

**Comment by Zapotecatl** [comment]
I changed the declaration in this way:
```
int64_t k_input_size = input_ids.size();
std::array<int64_t, 2> input_shape{ 1, k_input_size };
auto memory_info = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeDefault);
std::vector<Ort::Value> input_tensors;
input_tensors.push_back(Ort::Value::CreateTensor<int32_t>(memory_info, input_ids.data(), input_ids.size(), input_shape.data(), input_shape.size()));
```
Now, GPT2 is working in C++. Thanks a lot @tianleiwu!
