### ISSUE TITLE
Runtime Exception during initialization

### ISSUE THREAD

**Issue by carzh** [microsoft/onnxruntime#12312]
**Describe the bug**
When running Python script that uses Optimum to run ORT on model training, runs into the following error: `[E:onnxruntime:, inference_session.cc:1529 operator()] Exception during initialization: all symbols must have a namespace, <namespace>::<string>, but found: embedding`

**Urgency**
Blocking migration of example scripts to ORT 1.12.0

**System information**
- Linux Ubuntu 20.04
- ORT installed from index
`python -m pip install onnxruntime-training==1.12.0 -f https://download.onnxruntime.ai/onnxruntime_stable_cu113.html`
- ORT version 1.12.0+cu113 (also tried with PyPi install of ORT==1.12.0, and 1.12.0+cu115 installed from index)
- Python 3.8
- CUDA version 11.5
- CUDNN version 8.3.3
- GPU model and memory: 8 V100 GPU's

**To Reproduce**
- Ran huggingface's Optimum example from [here](https://github.com/huggingface/optimum/tree/main/examples/onnxruntime/training/translation)
- Installed requirements using `python -m pip install -r requirements.txt`
- Ran the following command:
```
python -m torch.distributed.launch --nproc_per_node 8 run_translation.py --dataset_name wmt16 --dataset_config ro-en --model_name_or_path facebook/bart-large --output_dir /tmp/tst-translation --do_train --label_smoothing 0.1 --logging_steps 200 --overwrite_output_dir --per_device_train_batch_size 1 --predict_with_generate --source_lang en --target_lang ro --warmup_steps 5 --fp16 --max_steps 8000 
```
- (runs smoothly without errors within an error when using ORT 1.11.1+cu113)

**Expected behavior**
Model trains without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/22922935/180895710-8fda5d76-73aa-43e5-97ee-096fde95e681.png)
image of the stack trace produced

**Additional context**
running BART on a translation task

Also tried running RoBERTa on a question-answering task and got the same results.

**Comment by prathikr** [comment]
Did you run the post-installation script for ORTModule?

python -m torch_ort.configure

**Comment by carzh** [comment]
Thanks!! That resolved the issue!
