### ISSUE TITLE
Onnxruntime-gpu Inference system memory leak over

### ISSUE THREAD

**Issue by s1022486** [microsoft/onnxruntime#12313]
I use C# onnxruntime-gpu inference happen system memory leak over, but using onnxruntime-cpu not.

**Urgency**
none

**System information**
- OS Platform and Distribution : windows 11
- ONNX Runtime installed from (source or binary): Visual Studio nuget
- ONNX Runtime version: 1.12.0
- Python version: none (using C#)
- Visual Studio version : Visual Studio 2019
- GCC/Compiler version : none
- CUDA/cuDNN version: cuda 11.5.56
- GPU model and memory:  RTX 3060

**To Reproduce**

Onnx Model : https://github.com/onnx/models/blob/main/vision/object_detection_segmentation/faster-rcnn/model/FasterRCNN-10.onnx

            string modelFilePath = @"C:\Users\ubuntu\Downloads\model\FasterRCNN-10.onnx";
            SessionOptions gpu = new SessionOptions();
            gpu.GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_EXTENDED;
            gpu.AppendExecutionProvider_CUDA(0);

            var _session = new InferenceSession(modelFilePath, gpu);

            for (int index = 0; index < 5000; index++) {
                Console.WriteLine(index.ToString());
                Console.WriteLine("================================================");
                IDisposableReadOnlyCollection<DisposableNamedOnnxValue> results = _session.Run(inputs);

                results.Dispose();
                GC.Collect();
            }

**Expected behavior**

onnxruntime-gpu inference system can`t leak over

**Screenshots**
source code
![未命名3](https://user-images.githubusercontent.com/18395451/180940881-7a5a9acc-11a0-4038-8eb6-439e6748f4e9.png)
![未命名](https://user-images.githubusercontent.com/18395451/180916403-64185329-fefc-4e07-a53b-e6a5dbb291f3.png)
Windows 11 Task Manager
![未命名1](https://user-images.githubusercontent.com/18395451/180916412-8f5ab8a2-3bd9-449f-ab39-7de460a09a0d.png)
Visual Studio Nuget  Install Package
![未命名2](https://user-images.githubusercontent.com/18395451/180918974-ffbfe818-adcd-4c92-9e09-26c462af3fb0.png)

**Comment by hariharans29** [comment]
Might be related to https://github.com/microsoft/onnxruntime/issues/9643 (although that was for Linux). What happens if you make the optimization level BASIC ? In https://github.com/microsoft/onnxruntime/issues/9643, the issue was while calling into CuDNN from an optimized node (`FusedConv`). If the leak still happens with optimization lvel made BASIC, it is a new issue altogether.

**Comment by s1022486** [comment]
@hariharans29 Thank you for your reply. 
I have solved the problem by ORT_ENABLE_BASIC.

**Comment by hariharans29** [comment]
CC: @RandySheriff 

If the problem goes away by turning on only the basic optimizations, it is likely that it is the same issue as in #9643. Please try updating your CuDNN version and then re-enable EXTENDED or ALL optimizations.
