### ISSUE TITLE
ORT v1.12.0 is no longer caching with TensorRT 

### ISSUE THREAD

**Issue by FHSatis** [microsoft/onnxruntime#12322]
**Describe the bug**
When running ONNX weights of a YOLOv5 model with providers set as:
`[('TensorrtExecutionProvider', {'trt_engine_cache_enable': True,
                                       'trt_engine_cache_path': <trt_engine_cache_path>,
                                       "trt_fp16_enable": True,
                                       'device_id': 0,
                                       })]`
A cache directory is created by no .engine files are placed in there. The system operates as usual (takes the time to cache and then runs object detection), but does not store anything in the cache folder. So when reloading the file it tries to cache again. When reverting back to onnxruntime-gpu==1.11.1 the caching works correctly.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 20.04):
- ONNX Runtime installed from (source or binary): pip 
- ONNX Runtime version: 1.12.0
- Python version: 3.8.10
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.7
- GPU model and memory: NVIDIA GeForce RTX 3080 Laptop GPU - 16Gb

**To Reproduce**
```
providers = [('TensorrtExecutionProvider', {'trt_engine_cache_enable': True,
                                       'trt_engine_cache_path': batched_trt_cache_path,
                                       "trt_fp16_enable": True,
                                       'device_id': 0,
                                       })]

session = onnxruntime.InferenceSession(str(onnx_weights_path), providers=providers)
im = np.random.rand(1, 896, 896, 3).astype(np.float32)
X_ortvalue = onnxruntime.OrtValue.ortvalue_from_numpy(im, 'cuda', 0)
warmup = session.run(None, {"images": X_ortvalue})
```

**Expected behavior**
Model caches within <trt_engine_cache_path>

**Comment by pranavsharma** [comment]
@stevenlix is this a regression?

**Comment by chilo-ms** [comment]
This is the behavior change for TRT EP in ORT 1.12
https://github.com/microsoft/onnxruntime/pull/11045
TRT engine cache won't be saved to file until destructor of inference session is called.

**Comment by robertbagge** [comment]
Thanks for the information @chilo-ms. We are running multiple instances of the same model on the same machine and getting the TensorRT cache in the beginning of the first session that comes up is helpful as we get significantly lower upstart time for consecutive inference sessions that comes up. Have any advice for how to handle that?

**Comment by chilo-ms** [comment]
Hi, you can have a warmup session to generate TRT engine and destroy the warmup session to generate the TRT engine cache.
Once the engine cache is there, you can then run the multiple inferences of the same model.

**Comment by chilo-ms** [comment]
After discussion, we plan to revert this to old behavior, please stay tuned.

**Comment by FHSatis** [comment]
Hi @chilo-ms is there any update on timelines of when this is to be reverted? Thanks!

**Comment by chilo-ms** [comment]
ORT 1.12.1 reverted to old behavior.

**Comment by invlpg** [comment]
the AI is on TRT ??? 😳
