### ISSUE TITLE
ARM build fail both on cross and native compile (requested alignment 128 is larger than 64)

### ISSUE THREAD

**Issue by meynety** [microsoft/onnxruntime#1232]
**Describe the bug**
Following instructions in [Build ONNX Runtime](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md), build fails using both the cross compiling with Docker method [(Cross compiling with Docker)](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#cross-compiling-for-arm-with-docker-linuxwindows---faster-recommended) and with the native compiling on the device (a RaspberryPi 3 B+) [(Native compiling on Linux ARM)](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#native-compiling-on-linux-arm-device-slower)
Both compilations seems to fail at `Building CXX object CMakeFiles/onnx_test_runner_common.dir/code/onnxruntime/onnxruntime/test/onnx/sync_api.cc.o`, with the error `/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/src/ThreadPool/EventCount.h:173:56: error: requested alignment 128 is larger than 64 [-Werror=attributes]
     EIGEN_ALIGN_TO_BOUNDARY(128) std::atomic<uint64_t> next;`

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Fedora 30 running Docker
Linux Raspbian 9.9 (stretch)
- ONNX Runtime installed from (source or binary): not installed
- ONNX Runtime version: master ?
- Python version:
Raspbian : 3.5.3
- GCC/Compiler version (if compiling from source): 
Raspbian : 6.3.0 20170516

**To Reproduce**
Docker : Follow the instructions on [Cross compiling with Docker](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#cross-compiling-for-arm-with-docker-linuxwindows---faster-recommended), build fails
Raspbian : Same but with [Native compiling on Linux ARM](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#native-compiling-on-linux-arm-device-slower)

**Expected behavior**
Build succeed and produce the onnx-runtime and python binding for ARM

**Screenshots**
Attached are the two console ouput of the errors, being a noob I'm not quite sure where the error really is between warnings and errors.
[docker.log](https://github.com/microsoft/onnxruntime/files/3292981/docker.log)
[raspbian.log](https://github.com/microsoft/onnxruntime/files/3292982/raspbian.log)

**Additional context**
On Raspbian, I switched from cmake 3.12.3 to cmake 3.13.5 because during the build it was complaining about requiring cmake 3.13 min.

Noobie question : Is there any pre-build ARM binaries that we can use ?

Thank you for the help

**Comment by pranavsharma** [comment]
At this point we don't ship any pre-built ARM binaries.

**Comment by meynety** [comment]
Alright thank you, what about the build error then ?

**Comment by pranavsharma** [comment]
I’ll look into it.

**Comment by RandySheriffH** [comment]
Let's review a solution:
https://github.com/microsoft/onnxruntime/pull/1261

**Comment by snnn** [comment]
We should fix the problem, instead of ignore the warning.

**Comment by RandySheriffH** [comment]
It is eigen code.

**Comment by RandySheriffH** [comment]
Issue fixed by the PR.

**Comment by RandySheriffH** [comment]
> We should fix the problem, instead of ignore the warning.



> It is eigen code.

**Comment by snnn** [comment]
Please see the discussion at : https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89357

I think that is a compiler bug, and it has been fixed in gcc 9 and 10.
