### ISSUE TITLE
The Clone Session interface is expected

### ISSUE THREAD

**Issue by heliqi** [microsoft/onnxruntime#12337]
**Is your feature request related to a problem? Please describe.**
I'm going to dynamically add and create sessions on what's happening online, deal with the sudden increase in requests.
`Ort::Env`, `Ort::SessionOptions`, and  `void* model_data` must be required when creating seesion for the same model.
Whether to add a Clone interface on Ort::Session ？ 
example: `std::unique_ptr<Ort::Session> new_session = session.Clone();`

If this interface is not available, there are several problems:
1. When I want to create an new Ort::Session  that is identical to an existing session, I must save the previous Ort::SessionOptions and mode_data. When the model is large, saving model_data incurs additional memory growth.
2. f the Clone interface is implemented, memory optimizations between Ort::Sessions (e.g. Share allocator, Share initializer, Share ORT pre-processed ...) could be done internally. The user can easily select the optimization through the configuration, and without having to write a lot of codes for complex optimizations.

**System information**
- ONNX Runtime version (you are using):1.11.1

**Describe the solution you'd like**
Add a `Clone` interface on Ort::Session.
example: `std::unique_ptr<Ort::Session> new_session = session.Clone()`

**Describe alternatives you've considered**

**Additional context**

**Comment by skottmckay** [comment]
InferenceSession::Run is stateless and supports concurrent requests. Why do you think you need multiple instances of it given that?

**Comment by heliqi** [comment]
> InferenceSession::Run is stateless and supports concurrent requests. Why do you think you need multiple instances of it given that?
@skottmckay 
To improve QPS(Queries Per Second), we used multithreading  to process requests. Each thread corresponds to a Ort::Session.

"InferenceSession::Run is stateless" means to support the simultaneous use `Session::Run` by different threads and different inputs data. example：
```
//A simple example
Ort::session session = {env, model_data, model_size,  session_options}
.....
std::thread thread1(session.run,  input1, output1);
std::thread thread2(session.run,  input2, output2);
thread1.join();
thread2.join();

```

**Comment by skottmckay** [comment]
Yes. Sharing one InferenceSession instance between threads is the correct way to use it.

**Comment by heliqi** [comment]
Thanks!  It's just like you said.
