### ISSUE TITLE
The latency of 1.12.0 onnxruntime-android is higher than 1.11.0 onnxruntime-android on Android

### ISSUE THREAD

**Issue by BangwenHe** [microsoft/onnxruntime#12339]
**Describe the bug**
I upgraded onnxruntime-android in [my demo](https://github.com/BangwenHe/ORTSegDemo) yesterday to roughly estimate a custom model's latency. However, I found the latency increased several times without changing the code, compared to the old tests. After using the other models in my demo, I found the latency of all the models increased. It may be a bug due to upgrading, so I downgrade the version of onnxruntime-android to 1.11.0 and everything is back to normal. 

Below is the latency table for using different versions: 

| model | version | latency | phone |
| :--: | :--: | :--: | :--: |
| mobilenetv2_7 | 1.11.0 | 29ms | Pixel 4 |
| mobilenetv2_7 | 1.12.0 | 180ms | Pixel 4 |

**Urgency**
NONE

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 19044.1826
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.11.0 and 1.12.0
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:
- Android Studio version: Chipmunk 2021.2.1 Patch 1

**To Reproduce**
1. clone [the repo](https://github.com/BangwenHe/ORTSegDemo)
2. open this project in AndroidStudio and install it on the phone
3. after running several iterations, you'll get the inference latency
4. change the version of onnxruntime-android in `src/app/build.gradle` from 1.11.0 to 1.12.0
5. repeat step 1~3

**Expected behavior**

1. after upgrading onnxruntime-android from 1.11.0 to 1.12.0, the latency won't change drastically

**Screenshots**

![image](https://user-images.githubusercontent.com/32662175/181234827-de12729f-a257-476b-8486-2287714969b7.png)

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by edgchen1** [comment]
Thanks for reporting the issue. It's been fixed in 1.12.1.
