### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxruntime#12343]
Python 3.11 is going to be released in 2 months.

**Comment by snnn** [comment]
I will make a PR to update our private copy of manylinux build scripts first. 

https://github.com/microsoft/onnxruntime/tree/snnn/p3

It is still WIP.

**Comment by snnn** [comment]
Related: https://github.com/actions/virtual-environments/issues/4246

**Comment by snnn** [comment]
After a discussion with the team, we will pause this work until Python 3.11 is finally released.

**Comment by rooterkyberian** [comment]
3.11 provides some significant performance benefits and we would love to jump on it in production as soon as it is out, but onxxruntime is also crucial for us making it harder to test it out beforehand

**Comment by snnn** [comment]
Thank you for letting me know. I'm sorry it is not in the project's plan for the next release. I will close this issue for now. We will evaluate it next year.
