### ISSUE TITLE
For same onnx model, the onnx runtime inference working well on python but not working on c#.

### ISSUE THREAD

**Issue by lakpa-tamang9** [microsoft/onnxruntime#12357]

**Comment by askhade** [comment]
Can you add more details regarding the issue? Are you running into build issues, perf or correctness issues?

**Comment by lakpa-tamang9** [comment]
The model that i used is EfficientDet0 from TensorFlow object detection API. I converted the TF savedmodel to onnx format and ran inference on Python, the model was loaded with no issues and performed detections as well. But, while i am trying to load the same model in C#, i get the following error. 

`Unhandled exception. Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:InvalidArgument] Failed to load model with error: Unknown model file format version.
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Init(String modelPath, SessionOptions options)
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath)
   at HelloWorld.Program.Main(String[] args) in C:\Users\Y720-15\Downloads\testing\testing\Program.cs:line 20`

**Comment by yuslepukhin** [comment]
Can you open and visualize the model with  [Netron](https://netron.app/)?

**Comment by lakpa-tamang9** [comment]
@yuslepukhin Yes, i visualized the model with Netron.
Update: The problem was solved. The issue was due to the version of ML.onnxruntime. I updated the onnxruntime version to 1.12 and the inference worked well.
```
Install-Package Microsoft.ML.OnnxRuntime -Version 1.12.0
```
Thank you.
