### ISSUE TITLE
Failed to build onnxruntime with TensorRT on Windows 11

### ISSUE THREAD

**Issue by fortminors** [microsoft/onnxruntime#12375]
**Describe the bug**
I am unable to build onnxruntime with TensorRT provider after following all of the given instructions. The issue is similar to [this](https://github.com/microsoft/onnxruntime/issues/3630) and [this](https://github.com/microsoft/onnxruntime/issues/4741), but what is suggested there does not work for me. I have also set `Language for non-Unicode programs` to English as suggested in the latter issue.
I was able to build successfully about a year ago with older versions, following the same steps, but now it does not work.

**Urgency**
No urgency, but I've been trying to build the newest version for a several days now, trying out various options to no success.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Windows 11`
- ONNX Runtime installed from (source or binary): `source`
- ONNX Runtime version: master from commit [0e85af6](https://github.com/microsoft/onnxruntime/commit/0e85af6990ac41b8925722d4aee990909421a729)
- Python version: `3.9`
- Visual Studio version (if applicable): `VS 2019`
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: `CUDA 11.4.4`, `cuDNN 8.2.4` as suggested [here](https://onnxruntime.ai/docs/build/eps.html#tensorrt)
- TensorRT version: `TensorRT-8.2.3.0`
- GPU model and memory: Nvidia GeForce RTX 2060 with Max-Q Design 6 GB

**To Reproduce**
- `git clone --recursive https://github.com/microsoft/onnxruntime.git`
- `cd onnxruntime`
- `build.bat --config Release --build_shared_lib --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4" --use_tensorrt --tensorrt_home "C:\Libraries\TensorRT-8.2.3.0" --cuda_version 11.4 --cmake_generator "Visual Studio 16 2019"`

**Expected behavior**
Successfully build onnxruntime with TensorRT execution provider

**Screenshots**
![image](https://user-images.githubusercontent.com/36015059/181648633-25a5a38a-d55c-4768-8d8a-6dd0819bb95d.png)

**Additional context**
- Changing `--config` and removing `--build_shared_lib` does not help
- I tried both `--cmake_generator "Visual Studio 16 2019"` and `--cmake_generator "Visual Studio 17 2022"`, the latter fails with a different error in the beginning of the script

**Comment by fortminors** [comment]
Just noticed this. Are there any plans on fixing this? And if so, when is that planned for? Thanks!

![image](https://user-images.githubusercontent.com/36015059/181834704-3932b218-2382-4ee7-8ed9-34a52434090d.png)

**Comment by faxu** [comment]
> Just noticed this. Are there any plans on fixing this? And if so, when is that planned for? Thanks!
> 
> ![image](https://user-images.githubusercontent.com/36015059/181834704-3932b218-2382-4ee7-8ed9-34a52434090d.png)

Looks like that failure was intermittent - it's succeeding now. @stevenlix  can you advise on this?

**Comment by fortminors** [comment]
@faxu Thank you. I see it is succeeding now, but I am still receiving this error for some reason. I recloned the repository and reran the command

**Comment by fortminors** [comment]
If I do `git checkout v1.11.0 `, it builds is successfully.
But the latest version does not work

**Comment by faxu** [comment]
CC @jywu-msft @stevenlix

**Comment by jywu-msft** [comment]
ort master and 1.12 requires TensorRT 8.4

**Comment by fortminors** [comment]
@jywu-msft My bad, thank you! I was looking [here](https://onnxruntime.ai/docs/build/eps.html#tensorrt) for the versions

**Comment by balajik27** [comment]
i have installed onnx==1.12.0 , onnxruntime==1.12.0 , torch==1.12.1 and cuda 11.6 in windows 11 with python version 3.8, can u suggest me which tensorRT version supports for me. 
i have nvdia gforce gtx 1650
