### ISSUE TITLE
[Documentation Request] Java API docs need updating

### ISSUE THREAD

**Issue by skottmckay** [microsoft/onnxruntime#12389]
Java docs are out of date. SessionOptions is missing addConfigEntry. 

---
#### Document Details
* Title: API Docs
* Page: [https://onnxruntime.ai/docs/api/](https://onnxruntime.ai/docs/api/)
* Page Source: index.md

**Comment by Craigacp** [comment]
Yeah, looks like a bunch of things are missing from SessionOptions, including different providers.

**Comment by natke** [comment]
@skottmckay Are these autogen'd?

**Comment by Craigacp** [comment]
Hmm, they might still be the initial ones I sent over with the original merge of the Java API. The html source says `Generated by javadoc (1.8.0_221) on Fri Dec 06 15:15:32 EST 2019` which would be the right time for that.

You can generate it with `gradle javadoc` and it'll appear in `onnxruntime/java/build/docs/javadoc`. I don't know how the rest of the docs are generated, but hopefully it should be straightforward to build that into however they are generated.

**Comment by natke** [comment]
Created PR #12515
