### ISSUE TITLE
Is there a compiled onnxruntime c++ library that i can directly place it in my source code folder and include it in my code?

### ISSUE THREAD

**Issue by Ray-0403** [microsoft/onnxruntime#12437]
Hi, i wonder is there a compiled onnxruntime c++ library i can download. And can i use it without cmake? 
Is it possible to just place the compiled library in my source code folder (need to use onnxruntime to deploy ML model remotely) and include it in my code?

**Comment by HectorSVC** [comment]
We have nuget packages: https://www.nuget.org/packages?q=onnxruntime
But it only has packages for CPU and GPU. If you need other Execution Provider, you need to build from source: https://onnxruntime.ai/docs/build/inferencing.html

**Comment by Ray-0403** [comment]
Thank you!
