### ISSUE TITLE
CMake Enabling AVX AVX2 does not improve performance

### ISSUE THREAD

**Issue by dsj178** [microsoft/onnxruntime#12438]
I find that the instruction set of convolution walk is SSE

**Comment by snnn** [comment]
It is expected. Our code has the ability to detect the capability at runtime, for some part of the code. And that part usually takes the most time. 

Enabling AVX AVX2 may still help, but not much.

**Comment by dsj178** [comment]
But I've noticed that some computations of the convolution you only distinguish MLAS_NEON_INTRINSICS MLAS_SSE2_INTRINSICS MLAS_VSX_INTRINSICS @snnn
