### ISSUE TITLE
How to get the predicted output value (float) using onnxruntime c++

### ISSUE THREAD

**Issue by Ray-0403** [microsoft/onnxruntime#12467]
Hi, i am using onnxruntime to deploy my lightgbm classifier model in c++, and i followed the tutorial from youtube: https://www.youtube.com/watch?v=exsgNLf-MyY. However, i have some problems to get the final predicted value. 

i tested the onnx model in python, which works fine.
<img width="623" alt="Screenshot 2022-08-04 at 00 07 24" src="https://user-images.githubusercontent.com/49976973/182858173-4cda176e-943a-4975-bc0d-4a186a5e2d28.png">

So i tried to get the same predicted value in c++ using following code:
<img width="600" alt="Screenshot 2022-08-04 at 00 04 51" src="https://user-images.githubusercontent.com/49976973/182858327-ae5bc02a-e04b-4655-b8fa-f6ed86e5c1ca.png">

 But i got errors when i tried to get the predicted float value using the following c++ code:  float pred = output1  or  float pred = floats. 

i don't know how to get the final predicted value in the above code, can you help me? Thank you.

**Comment by HectorSVC** [comment]
Please try follow the examples here:
https://github.com/microsoft/onnxruntime-inference-examples
https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/MNIST
