### ISSUE TITLE
Extracting 4D mask output of Mask RCNN with ONNX C++ API

### ISSUE THREAD

**Issue by tommyvtran97** [microsoft/onnxruntime#12464]
Hi everyone, 

I am trying to write inference code for the ONNX Mask RCNN model in C++. The model has 1 input [1, C, H, W] and it gives 4 outputs with dynamic shapes. 

- Bounding Boxes [-1, 4]
- Classes [-1]
- Scores [-1]
- Masks [-1, 1, -1, -1]

I managed to extract the information regarding bounding boxes, classes and scores. However I do not know how to deal with the mask output. It seems that the mask output is completely flatted (floatarr4), whereas I want an output something like [1, 1, H, W]. Below the code that I am using to extract the information. I hope someone can push me into the right direction
```
  /**************** Create ORT session ******************/
  Ort::SessionOptions sessionOptions;
  sessionOptions.AppendExecutionProvider_CUDA(OrtCUDAProviderOptions{});
  sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
  mSession = std::make_shared<Ort::Session>(*mEnv, modelFilepath.c_str(), sessionOptions);

  /**************** Create allocator ******************/
  Ort::AllocatorWithDefaultOptions allocator;

  // Get the name of the output
  mOutputName1 = mSession->GetOutputName(0, allocator);
  mOutputName2 = mSession->GetOutputName(1, allocator);
  mOutputName3 = mSession->GetOutputName(2, allocator);
  mOutputName4 = mSession->GetOutputName(3, allocator);

  std::vector<const char*> inputNames{mInputName};
  std::vector<const char*> outputNames{mOutputName1, mOutputName2, mOutputName3, mOutputName4};

  std::vector<Ort::Value> outputTensors =  mSession->Run(Ort::RunOptions{nullptr}, inputNames.data(), inputTensors.data(), 1, outputNames.data(), 4); 

  // Get the inference result
  float* floatarr1 = outputTensors[0].GetTensorMutableData<float>();
  float* floatarr2 = outputTensors[1].GetTensorMutableData<float>();
  float* floatarr3 = outputTensors[2].GetTensorMutableData<float>();
  float* floatarr4 = outputTensors[3].GetTensorMutableData<float>();
  
```

**Comment by HectorSVC** [comment]
That's expected. The data inside the Ort::Value is always a flat buffer. You can get the shape information from the Ort::Value and iterate through the buffer.

**Comment by tommyvtran97** [comment]
Thanks, I looked into the examples but could not find a good approach. Ideally I want to convert the flat buffer tensor into an image with shape  for example [1, H, W] in cv::Mat to visualize the masks with OpenCV. Is there a good approach to resize this flat buffer into the correct desired shape?

**Comment by mpashchenkov** [comment]
@tommyvtran97, Hi you can use this approach (with copy to cv::Mat):
https://github.com/opencv/opencv/blob/e80b443cd93012f1fdd79baf7ed325beff606a89/modules/gapi/src/backends/onnx/gonnxbackend.cpp#L188
Also you can try G-API for inference of ONNX models.

**Comment by abayet15** [comment]
Hi Tommy,
I have the same problem. Did you find a solution ? Possible to share your source code ? Thank you for your help.
