### ISSUE TITLE
[Documentation Request]

### ISSUE THREAD

**Issue by andrew-ml** [microsoft/onnxruntime#12466]
There's a type: `--build_was_static_lib`  should be `--build_wasm_static_lib`

---
#### Document Details
* Title: Build for web
* Page: [https://onnxruntime.ai/docs/build/web.html](https://onnxruntime.ai/docs/build/web.html)
* Page Source: web.md

**Comment by HectorSVC** [comment]
Thanks for reporting this. I created a PR to fix it.
