### ISSUE TITLE
Got error: cpu exception in c++

### ISSUE THREAD

**Issue by Ray-0403** [microsoft/onnxruntime#12478]
Hi, I successfully compiled the code, but when I run it, I got cpu exception error. If i only included the cxx api header file in code, the code runs well, but when the code has: Orr:: Env env; (even I didn't load my model file), it got cpu exception error.
Idk what caused it, my code is ok, can you help me?

**Comment by HectorSVC** [comment]
Could you provide more details of your code?

**Comment by Ray-0403** [comment]
I used it as a dll inside a software running c++, I can include the header files with no error, but it got that cpu exception error at line 1: Ort :: Env env; even I didn't do any calculation

**Comment by Ray-0403** [comment]
> Could you provide more details of your code?

I used it as a dll inside a software running c++, I can include the header files with no error, but it got that cpu exception error at line 1: Ort :: Env env; even I didn't do any calculation

What happened when the code runs Ort::Env env? Is it possible that the error was caused by the code trying to access the cpu recourse and the software that dll runs on prevents it from accessing cpu recourse?
