### ISSUE TITLE
Error 126: Cant Run Inference On GPU 

### ISSUE THREAD

**Issue by SingletonInstance** [microsoft/onnxruntime#12488]
As the title states I am not able to run an inference model on the GPU, using a .NET Core 3.1 application.

"Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:RuntimeException] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1025 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\Singleton\Sauce\Repos\CODEBASE\TESTS\bin\Debug\netcoreapp3.1\runtimes\win-x64\native\onnxruntime_providers_cuda.dll"

I am using the following content:
Microsoft.ML.OnnxRuntime.GPU (nuget package VERSION 1.12.0)
NVIDIA CUDA Tool Kit (VERSION 11.4)
CUDNN (VERSION 8.2.2.26)  

The content I have selected conforms to what is listed here: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements.

Please note that I have followed the instructions of copying CUDNN files and adding that directory to the path as described here:https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installwindows

Thank you in advance for help!!!

**Comment by skottmckay** [comment]
You can use something like https://github.com/lucasg/Dependencies to potentially find missing dependencies.

Sometimes the need to copy the zlib dll is overlooked. Did you do that step?

**Comment by yufenglee** [comment]
For me, it is because CUDNN64_8.dll cannot be located. It is solved by adding folder containing the dll to path.

**Comment by SingletonInstance** [comment]
I resolved this issue by copying the "Bin" "Lib" and "Include" contents of CudaNN into the same respective folders in the CudaToolKit installation folder.

I dont understand why this step is needed and it clearly is not specified in the Cuda documentation.

**Comment by miniminiming** [comment]
> For me, it is because CUDNN64_8.dll cannot be located. It is solved by adding folder containing the dll to path.

resolved my problem,thanks
