### ISSUE TITLE
ConvAdd Fusion produces wrong outputs when Conv has `group` attribute

### ISSUE THREAD

**Issue by xuzijian629** [microsoft/onnxruntime#12498]
**To Reproduce**
```python3
import torch
import pytorch_pfn_extras.onnx as tou
import numpy as np

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.cv = torch.nn.Conv2d(136, 136, 1, groups=4)
        self.c = torch.rand(1, 136, 28, 28)

    def forward(self, x):
        x = self.cv(x)
        return x + self.c


model = Model()
x = torch.rand(1, 136, 28, 28)

tou.export_testcase(model, (x,), "conv_add", output_names=["y"])



import onnxruntime as rt
import onnx
import onnx.numpy_helper

opts = rt.SessionOptions()
# opts.graph_optimization_level = rt.GraphOptimizationLevel.ORT_DISABLE_ALL
sess = rt.InferenceSession("conv_add/model.onnx", opts)
x = onnx.numpy_helper.to_array(onnx.load_tensor("conv_add/test_data_set_0/input_0.pb"))
y = onnx.numpy_helper.to_array(onnx.load_tensor("conv_add/test_data_set_0/output_0.pb"))

outputs = sess.run(["y"], {"input_0": x})

np.testing.assert_allclose(outputs[0], y, rtol=1e-3, atol=1e-4)
```

Assertion fails and you'll got
```txt
Not equal to tolerance rtol=0.001, atol=0.0001

Mismatched elements: 106589 / 106624 (100%)
Max absolute difference: 0.9999966
Max relative difference: 45601.883
 x: array([[[[ 0.262129,  0.369218,  0.172452, ...,  0.201673,  0.095873,
           0.367868],
         [ 0.357392,  0.510156,  0.089016, ...,  0.182598,  0.20851 ,...
 y: array([[[[ 0.554469,  0.932921,  0.185684, ...,  0.463452,  0.645789,
           0.38952 ],
         [ 0.799119,  1.164005,  0.608806, ...,  0.228106,  0.775098,...
```

**Expected behavior**
By setting `opts.graph_optimization_level = rt.GraphOptimizationLevel.ORT_DISABLE_ALL`, we got correct results and the assertion succeeds.

**Screenshots**
![](https://github.com/xuzijian629/tekito/blob/main/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202022-08-08%209.29.29.png?raw=true)

**Additional context**
If `groups=4` is omitted, onnxruntime inferences correctly.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- ONNX Runtime installed from (source or binary): pip installed
- ONNX Runtime version: 1.12.1
- Python version: 3.8.10

**Comment by raiseirql** [comment]
Hi, I was hitting the same problem in our use of ONNX Runtime at Unity, but with a batch count > 1. When the support for ConvAdd fusion was added, MlasConvGemmDirectThreaded was not updated to use the beta parameter but is still hard-coded to 0.0f. The MlasConvAlgorithmDepthwise path was also not updated to use beta, but that might be trickier: maybe the code should not select that path if beta is non-zero.

**Comment by wejoncy** [comment]
Hi @raiseirql  @xuzijian629 Thanks for reporting the bug. I can reproduce it in local.
Will fix it ASAP.


If you want to take a quick workaround, please add such param to filter out `ConvAddActivationFusion` temporary.

https://github.com/microsoft/onnxruntime/blob/cc0a6213e4dfba3c2bc1d684e5b4d3054242e5f0/onnxruntime/python/onnxruntime_inference_collection.py#L357
