### ISSUE TITLE
Can I run Ort::Env env; every time there’s a new input?

### ISSUE THREAD

**Issue by Ray-0403** [microsoft/onnxruntime#12494]
Hi, if I run Ort::Env env; every time the code receives a new input(the new input will be generated every second), will it cause problem?

**Comment by ZiyueWangUoB** [comment]
Why? Couldn't you just generate the Ort::Env and keep it alive in memory?

**Comment by skottmckay** [comment]
InferenceSession supports multiple and concurrent requests to 'run'. Creating the InferenceSession can be expensive, so you don't want to do that unnecessarily. Re-creating the Env implies you're also recreating the InferenceSession. 

Expected usage is to create the Env and keep it alive. Create an InferenceSession that is dependent on the Env. Send as many requests as you like to run the inference session.
