### ISSUE TITLE
Could not find a version that satisfies the requirement onnxruntime==1.10.0

### ISSUE THREAD

**Issue by bramses** [microsoft/onnxruntime#12502]
**Describe the bug**

```
pip install onnxruntime==1.10.0  
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.10.0 (from versions: 1.12.0, 1.12.1)
ERROR: No matching distribution found for onnxruntime==1.10.0
```

**Urgency**

None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Monterey, Silicon
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:
- Python version: 3.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**

`pip install onnxruntime==1.10.0`

**Comment by jcwchen** [comment]
Hi @bramses,
ONNX Runtime just started to provide Mac wheel for M1 machines since ORT 1.12: https://github.com/microsoft/onnxruntime/releases/tag/v1.12.0. So you can only find it for ORT>=1.12 on M1/M2 machines.

**Comment by bramses** [comment]
gotcha, thank you @jcwchen!
