### ISSUE TITLE
onnxruntime-android - ld: error: cannot find -lonnxruntime when building the native C++ project

### ISSUE THREAD

**Issue by abilashravi-ta** [microsoft/onnxruntime#12521]
**Describe the bug**
I'm trying to do `onnxruntime` _inferencing_ on Android with _Android studio_ and _Pixel 5 emulator_.  I followed the instructions given [here](https://onnxruntime.ai/docs/install/#install-on-android) to use the pre-built `libonnxruntime.so` (_onnxruntime-android_). Getting this error `C/C++: D:/Android_sdk/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin\ld: error: cannot find -lonnxruntime` while _building_ the project.

**System information**
- OS Platform: Windows 10 Pro
- ONNX Runtime installed from (source or binary): `onnxruntime-android-1.11.0.aar` downloaded from [here](https://mvnrepository.com/artifact/com.microsoft.onnxruntime/onnxruntime-android), extracted and placed at `D:/MLE_AR/ort_precompiled` location.

**To Reproduce**
The project structure is a `Native C++` template created from Android studio.

My `CMakeList.txt` looks like the following
```
cmake_minimum_required(VERSION 3.18.1)

project("onnx_try_v1")

set(precompiled_DIR D:/MLE_AR/ort_precompiled)

add_library(onnx_try_v1 SHARED native-lib.cpp)

include_directories(onnx_try_v1 PRIVATE ${precompiled_DIR}/headers)
set(ONNX_RUNTIME_LIB ${precompiled_DIR}/jni/arm64-v8a/libonnxruntime.so)

find_library(log-lib log)

target_link_libraries(onnx_try_v1 ${ONNX_RUNTIME_LIB} ${log-lib})
```

I have added the following to `build.gradle(onnx_try_v1)` file
```
repositories {
    mavenCentral()
}
```

I have also inserted the following in the _dependencies_ block in `build.gradle(app)` file
```
implementation 'com.microsoft.onnxruntime:onnxruntime-android:latest.release'
```

My `native-lib.cpp` looks like the following
```
#include <jni.h>
#include <string>

extern "C" JNIEXPORT jstring JNICALL
Java_com_example_onnx_1try_1v1_MainActivity_stringFromJNI(
        JNIEnv* env,
        jobject /* this */) {
    std::string hello = "Hello from C++";
    return env->NewStringUTF(hello.c_str());
}
```

**Expected behavior**
I'm expecting to see an output like this on the _emulator_ as I've not made any changes to `native-lib.cpp` file.
![expected_emulator_output2](https://user-images.githubusercontent.com/53215532/183653263-3b06cabc-9b00-4f1e-b985-4318e1a24ecb.JPG)

But I'm getting this error when I build the project (`Ctrl+F9`)
![buil_error_on_studio](https://user-images.githubusercontent.com/53215532/183651563-63e3510d-6e7f-4913-89ae-a4dd896692c3.JPG)

Full text of the error:
```
C/C++: D:/Android_sdk/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lonnxruntime
```

Any suggestion would be helpful.!

**Comment by skottmckay** [comment]
You could take a look at the example Android app we have to see what differences there are between your setup and that working one. 

https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/image_classification/android

**Comment by abilashravi-ta** [comment]
@skottmckay, I'm developing an app using the _C++ onnxruntime_ library android through _JNI_. The setup in the link shaded above was not of much help. Any sample App built using the _C++ api_ would be very helpful.

**Comment by skottmckay** [comment]
It's more about the build setup than the type of app. In either case the linker needs to be able to find the onnxruntime library. The error you're getting from the linker indicates it can't find what it needs.

If you're trying to run on the emulator though I would expect the build needs to use the library matching the architecture of the machine the emulator is running on, which typically would not be arm64.

So possibly this:
`set(ONNX_RUNTIME_LIB ${precompiled_DIR}/jni/arm64-v8a/libonnxruntime.so)`

needs to adjust for whether you're building something targeting the emulator vs. an actual Android device. Based on the path in the NDK toolchain having `prebuild/windows-x86_64` in it, the x86_64 binary from the ORT package is what you should be linking against when using the emulator.

<img width="273" alt="image" src="https://user-images.githubusercontent.com/979079/184246850-26856e09-d77d-4577-bca7-88d118c73709.png">

**Comment by skottmckay** [comment]
Assuming issue was due to wrong binary being referenced. Please re-open if a problem persists.
