### ISSUE TITLE
ORT built with CUDA but no processing is happening on the GPU

### ISSUE THREAD

**Issue by NourIslamPSPDFKit** [microsoft/onnxruntime#12524]
**Describe the bug**
I have been trying to make ORT work with NVIDIA GPU. I have built it from source successfully using : 

`.\build.bat --config Release --update --parallel --build --enable_msvc_static_runtime --use_cuda --cudnn_home D:\Tools\cudnn_v8.2.2.26 --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4" --cuda_version 11.4
`
Then in my code, I have something like this:

```
SessionOptions session_options = SessionOptions{};
std::vector<std::string> availableProviders = Ort::GetAvailableProviders();
auto cudaAvailable = std::find(availableProviders.begin(), availableProviders.end(), "CUDAExecutionProvider");

std::cout << "List of available ORT providers : " << std::endl;
for (auto f : availableProviders) {
std::cout << "Provider : " << f << std::endl;
}
session_options.AppendExecutionProvider_CUDA(OrtCUDAProviderOptions());
OrtCUDAProviderOptions cuda_options;
cuda_options.device_id = 0;
session_options.AppendExecutionProvider_CUDA(cuda_options);
```

In the output, I notice that there is in fact a CUDA provider (as well as CPU provider) but when I look at the processes running on my machine, I see 0% in the NVIDIA GPU.

Is this normal? Is there something that I'm missing in the code or at build time?

**Urgency**
We really need this.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: latest (from source)
- Python version:
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: 11.4/8.2.2.26
- GPU model and memory: Nvidia GeForce GTX 1650

**To Reproduce**
- Build ORT from source.
- Add the necessary libs to your project.
- Use the code above to run inference on GPU.

**Expected behavior**
I should have seen some level of processing happening on the GPU right?

**Additional context**
The models that I'm using are small in size (around 4 convolutional layers and 3 recurrent layers).

**Comment by yuslepukhin** [comment]
A lot depends on the model and how you measure the GPU usage. For some usages, you may not be able to see it with a naked eye.
The best way is to enable logging to see where model nodes are placed for execution.
