### ISSUE TITLE
Remove executor threadpool

### ISSUE THREAD

**Issue by letmaik** [microsoft/onnxruntime#1253]
There's currently a session threadpool but also an executor threadpool here:
https://github.com/microsoft/onnxruntime/blob/e26e11b9f7f7b1d153d9ce2ac160cffb241e4ded/onnxruntime/core/framework/parallel_executor.cc#L29

Will the executor threadpool go away such that the parallel executor uses the session thread pool? Is someone working on it? I could PR this but I'm not sure whether it breaks something or degrades performance. It would be very useful to have only a single threadpool.

**Comment by pranavsharma** [comment]
The threading design is being reworked as we speak to use a single threadpool like you said. @shschaefer is working in it.
