### ISSUE TITLE
Python Wrapper for Raspberry Pi

### ISSUE THREAD

**Issue by hossein1387** [microsoft/onnxruntime#1256]
**Is your feature request related to a problem? Please describe.**
Currently only C API is available for ARM (Raspberry Pi for instance)

**Describe the solution you'd like**
A Python wrapper for onnxruntime on ARM devices.

**Comment by snnn** [comment]
Do you have some docs for setting up cross compiling environment for Raspberry Pi? Especially, how to create the sysroot, which is essential for building python binding.

**Comment by pranavsharma** [comment]
Doesn't [this](https://github.com/Microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.arm32v7) create the whl as well?

**Comment by hossein1387** [comment]
Running docker image as explained results in:

```
usage: 
Default behavior is --update --build --test for native architecture builds.
Default behavior is --update --build for cross-compiled builds.

The Update phase will update git submodules, and run cmake to generate makefiles.
The Build phase will build all projects.
The Test phase will run all unit tests, and optionally the ONNX tests.

Use the individual flags to only run the specified stages.
                                     
build.py: error: unrecognized arguments: --use_openmp
The command '/bin/sh -c ./build.sh ${BUILDARGS} --update --build' returned a non-zero code: 2
```

**Comment by snnn** [comment]
I tried to remove the '--use_openmp' argument, but I reverted the change. I'm wondering which source version you are using.

**Comment by hossein1387** [comment]
I am working on master branch commit 
`e26e11b9f7f7b1d153d9ce2ac160cffb241e4ded`

**Comment by snnn** [comment]
Could you please open tools/ci_build/build.py and search if there is a line like:

```python
    parser.add_argument("--use_openmp", action='store_true', help="Build with OpenMP.")
```

?

**Comment by hossein1387** [comment]
I tried it today and apparently, this line was added long time ago by [yourself](https://github.com/microsoft/onnxruntime/commit/6c9d815de592a77d83f5a5e2d66ce12c43bfa4da#diff-98790bd74beaa51d0196dd9bba024269).

However, I am used the latest commits and the docker file is now working.
05a222a961c4729c729c24cbbbc19a12dde6e211

I was able to create the wheel, however, when I try to import onnxruntime, I get the following error:

```
>>> import onnxruntime as rt
/home/hossein/.local/lib/python3.5/site-packages/onnxruntime/capi/onnxruntime_validation.py:22: UserWarning: Unsupported architecture (32bit). ONNX Runtime supports 64bit architecture, only.
  warnings.warn('Unsupported architecture (%s). ONNX Runtime supports 64bit architecture, only.' % __my_arch__)
ImportError: No module named 'numpy.core._multiarray_umath'
```

the output of uname is as follow:
```
> uname -a
Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
```

The docker file name implies that the build is targeting armv7 32bit arch but the import error is showing it is targeting 64bit.

**Comment by hossein1387** [comment]
Apparently, right now the build system only supports ARM 64bit: https://github.com/microsoft/onnxruntime/blob/a8ff209ab6587d6276d7b30b9dd861d27320b3af/tools/ci_build/build.py#L343

So I tried to install the generated wheel on NVIDIA Jetson TX2 which has 4 64bit ARM v8 cpus and got the following error:

`onnxruntime-0.4.0-cp35-cp35m-linux_armv7l.whl is not a supported wheel on this platform.
`

cpuinfo on Jetson TX2:
```

processor	: 0
model name	: ARMv8 Processor rev 3 (v8l)
BogoMIPS	: 62.50
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 3

processor	: 3
model name	: ARMv8 Processor rev 3 (v8l)
BogoMIPS	: 62.50
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 3

processor	: 4
model name	: ARMv8 Processor rev 3 (v8l)
BogoMIPS	: 62.50
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 3

processor	: 5
model name	: ARMv8 Processor rev 3 (v8l)
BogoMIPS	: 62.50
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 3

```
Any idea how can I install onnxruntime on either of these platforms?

**Comment by jywu-msft** [comment]
you can ignore the import error message. we should remove that. even though it says only 64bit is supported, it does indeed work on 32bit as well. see https://github.com/microsoft/onnxruntime/issues/590
I think the error message you're encountering is saying you don't have numpy module installed.

re: 64bit arm on jetson, you can build natively (don't cross compile) on jetson ,and it should work. 
we haven't tested on jetson tx2 specifically, but we have tested a fair amount on jetson nano.
see https://github.com/microsoft/onnxruntime/issues/995

**Comment by jywu-msft** [comment]
will close as the issue seems resolved.

**Comment by hossein1387** [comment]
@jywu-msft With your help I was able to run my code on RaspberryPi. For TX2, when I try to natively compile onnxruntime,  I get the final error right at the end:

```
[100%] Building CXX object CMakeFiles/onnxruntime_perf_test.dir/home/askari/repos/onnxruntime/onnxruntime/core/framework/path_lib.cc.o
[100%] Linking CXX executable onnxruntime_perf_test
[100%] Built target onnxruntime_perf_test
2019-07-18 16:39:29,962 Build [DEBUG] - Running subprocess in '/home/askari/repos/onnxruntime/build/Linux/Release'
['/usr/bin/python3', '/home/askari/repos/onnxruntime/setup.py', 'bdist_wheel', '--use_tensorrt']
running bdist_wheel
running build
running build_py
error: package directory 'onnxruntime' does not exist
Traceback (most recent call last):
  File "/home/askari/repos/onnxruntime/tools/ci_build/build.py", line 910, in <module>
    sys.exit(main())
  File "/home/askari/repos/onnxruntime/tools/ci_build/build.py", line 901, in main
    build_python_wheel(source_dir, build_dir, configs, args.use_cuda, args.use_ngraph, args.use_tensorrt, args.use_openvino, nightly_build)
  File "/home/askari/repos/onnxruntime/tools/ci_build/build.py", line 707, in build_python_wheel
    run_subprocess(args, cwd=cwd)
  File "/home/askari/repos/onnxruntime/tools/ci_build/build.py", line 181, in run_subprocess
    return subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/home/askari/repos/onnxruntime/setup.py', 'bdist_wheel', '--use_tensorrt']' returned non-zero exit status 1

```

however, in my onnxruntime directory, I have a directory named onnxruntime. So I am not sure what exactly is happening

**Comment by jywu-msft** [comment]
i'm not sure. haven't seen that before.

if you add your build dir (/home/askari/repos/onnxruntime/build/Linux/Release) to your PYTHONPATH
and run python3 and import onnxruntime does it work?

**Comment by jywu-msft** [comment]
does your build/Linux/Release directory contain onnxruntime directory (with backend, capi,datasets etc. underneath)

**Comment by hossein1387** [comment]
No I do not have onnxruntime directory in my Release folder. So when I try to import onnxruntime in pyhton3 after adding (/home/askari/repos/onnxruntime/build/Linux/Release) to PYTHONPATH, I get **ImportError: No module named 'onnxruntime'**

**Comment by jywu-msft** [comment]
Where is your build directory that contains the onnxruntime package dir

**Comment by hossein1387** [comment]
I have cloned  onnxruntime into /home/askari/repos/onnxruntime directory.

**Comment by jywu-msft** [comment]
and which directory contains the build objs?

**Comment by hossein1387** [comment]
Here is the steps I take:

```
git clone --recursive https://github.com/Microsoft/onnxruntime
cd onnxruntime
export CUDACXX="/usr/local/cuda/bin/nvcc"
Modify CMakeLists.txt
    -  set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -gencode=arch=compute_50,code=sm_50") # M series
    +  set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -gencode=arch=compute_53,code=sm_53") # Jetson support

./build.sh --config Release --update --build --build_wheel --use_tensorrt --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu --tensorrt_home /usr/lib/aarch64-linux-gnu

```

With the latest commit (f052966972d2d7fc0b09572ceb40079f4f7799f1) I get the following errors:


```
...
/home/askari/repos/onnxruntime/onnxruntime/core/providers/cuda/cudnn_common.cc:94:84: error: ‘cudnnSetRNNDataDescriptor’ was not declared in this scope
                                                   static_cast<void*>(&padding_fill)));
                                                                                    ^
/home/askari/repos/onnxruntime/include/onnxruntime/core/common/common.h:141:21: note: in definition of macro ‘ORT_RETURN_IF_ERROR’
     auto _status = (expr);                 \
                     ^
/home/askari/repos/onnxruntime/onnxruntime/core/providers/cuda/cuda_common.h:23:57: note: in expansion of macro ‘CUDNN_CALL’
 #define CUDNN_RETURN_IF_ERROR(expr) ORT_RETURN_IF_ERROR(CUDNN_CALL(expr) ? common::Status::OK() : common::Status(common::ONNXRUNTIME, common::FAIL))
                                                         ^
/home/askari/repos/onnxruntime/onnxruntime/core/providers/cuda/cudnn_common.cc:89:3: note: in expansion of macro ‘CUDNN_RETURN_IF_ERROR’
   CUDNN_RETURN_IF_ERROR(cudnnSetRNNDataDescriptor(tensor_, dataType, layout,
   ^
CMakeFiles/onnxruntime_providers_cuda.dir/build.make:153: recipe for target 'CMakeFiles/onnxruntime_providers_cuda.dir/home/askari/repos/onnxruntime/onnxruntime/core/providers/cuda/cudnn_common.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/home/askari/repos/onnxruntime/onnxruntime/core/providers/cuda/cudnn_common.cc.o] Error 1
CMakeFiles/Makefile2:193: recipe for target 'CMakeFiles/onnxruntime_providers_cuda.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/askari/repos/onnxruntime/tools/ci_build/build.py", line 954, in <module>
    sys.exit(main())
  File "/home/askari/repos/onnxruntime/tools/ci_build/build.py", line 903, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "/home/askari/repos/onnxruntime/tools/ci_build/build.py", line 442, in build_targets
    run_subprocess(cmd_args)
  File "/home/askari/repos/onnxruntime/tools/ci_build/build.py", line 190, in run_subprocess
    return subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/askari/repos/onnxruntime/build/Linux/Release', '--config', 'Release']' returned non-zero exit status 2

```

**Comment by jywu-msft** [comment]
I don't have access to a Jetson TX2, but I tested on a Jetson Nano with Jetpack 4.2.1 
and the wheel built fine. I had to additionally set onnxruntime_DEV_MODE=OFF in build.py

diff --git a/tools/ci_build/build.py b/tools/ci_build/build.py
index 9da8b5d0..5b28b2b9 100755
--- a/tools/ci_build/build.py
+++ b/tools/ci_build/build.py
@@ -318,7 +318,7 @@ def generate_build_tree(cmake_path, source_dir, build_dir, cuda_home, cudnn_home
     cmake_args = [cmake_path, cmake_dir,
                  "-Donnxruntime_RUN_ONNX_TESTS=" + ("ON" if args.enable_onnx_tests else "OFF"),
                  "-Donnxruntime_GENERATE_TEST_REPORTS=ON",
-                 "-Donnxruntime_DEV_MODE=ON",
+                 "-Donnxruntime_DEV_MODE=OFF",
                  "-DPYTHON_EXECUTABLE=" + sys.executable,
                  "-Donnxruntime_USE_CUDA=" + ("ON" if args.use_cuda else "OFF"),
                  "-Donnxruntime_USE_NSYNC=" + ("OFF" if is_windows() or not args.use_nsync else "ON"), 

so the build doesn't treat warnings as errors.

but I don't think that's the source of your failure.
this seems to be the main error:
error: ‘cudnnSetRNNDataDescriptor’ was not declared in this scope

which suggests it's not finding cudnn header files?

**Comment by faxu** [comment]
@hossein1387 are you still experiencing this issue and need additional assistance? If not, please close the issue. If so, please provide an update with your latest experience.

**Comment by liuwuliuyun** [comment]
@hossein1387 have you succeeded running code on raspberry pi? I follow the instuctions in this issue but after install I encounter segmentation fault when running model.

**Comment by hossein1387** [comment]
Sorry I haven't had the time to check if the issue still exists, you can close the issue and re-open later

**Comment by hossein1387** [comment]
Please refer to this [issue](#2684) if you are compiling for aarch64
