### ISSUE TITLE
YOLO V3 error 

### ISSUE THREAD

**Issue by saipj** [microsoft/onnxruntime#1257]
**Describe the bug**

Encountering error when running YOLO V3 perf test. Please find the error below. 
[E:onnxruntime:Default, runner.cc:185 RunTests] Test yolov3 failed:Load model from /onnx_models//yolov3/yolov3.onnx failed:[ShapeInferenceError] Number of elements of input 'scales' must be same as rank of input 'X' and element type must be float. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: github
- Python version: 3.5
- Visual Studio version (if applicable): NA
- GCC/Compiler version (if compiling from source): gcc 7.4.0 
- CUDA/cuDNN version:NA
- GPU model and memory: NA

**To Reproduce**
Describe steps/code to reproduce the behavior:
Download the YOLO V3 model from ONNX model zoo.
Run the following command:
~/onnxruntime/build/Linux/RelWithDebInfo# ./onnxruntime_perf_test -e cpu -m times -r 1
  
**Expected behavior**

It should run with out errors on OnnxRunTime default CPU. 

**Screenshots**

**Additional context**

complete log after executing the command:
/onnx_models/yolov3/yolov3.onnx ./results.txt
Setting thread pool size to 0
Load model from /onnx_models/yolov3/yolov3.onnx failed:[ShapeInferenceError] Number of elements of input 'scales' must be same as rank of input 'X' and element type must be float.

**Comment by hariharans29** [comment]
Hi,

This should have been fixed by https://github.com/microsoft/onnxruntime/commit/c96049fe4ad16f1964257e442fad6906e0acb198. Di d you include this commit in your build ?

CC: @raymondxyang

**Comment by raymondxyang** [comment]
Yes the changes were merged last afternoon.. would u mind kindly confirm you are using the latest version of onnxruntime?

**Comment by saipj** [comment]
Thanks, this worked. We can close the issue now.

**Comment by hariharans29** [comment]
Thanks for confirming. Closed.
