### ISSUE TITLE
Potential updates on `ONNXModel.save_model_to_file` of quantization and optimization

### ISSUE THREAD

**Issue by JingyaHuang** [microsoft/onnxruntime#12576]
## Context

Hi ORT team, recently we got some issues from the Optimum side about exporting large proto after graph optimization or quantization. We found that unlike the [`save_model_to_file` for the optimization](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/onnx_model.py), for the quantization `save_model_to_file` export the external tensors on the local working path
https://github.com/microsoft/onnxruntime/blob/24eab921bee4dbf9002942fbc514b2b2d9ee3a64/onnxruntime/python/tools/quantization/onnx_model.py#L342
instead of the path where I store the model proto
https://github.com/microsoft/onnxruntime/blob/24eab921bee4dbf9002942fbc514b2b2d9ee3a64/onnxruntime/python/tools/quantization/onnx_model.py#L344

In terms of user experience, it seems to be quite confusing, would it make sense to put the external files in the same directory as what is done for the optimization?

Besides, ONNX now provides [more variables](https://github.com/onnx/onnx/blob/main/onnx/__init__.py#L188) including `all_tensors_to_one_file`(already added for the optimization but not for the quantization), `size_threshold` and `convert_attribute` to help export large proto, is there any plan from ONNX Runtime side to integrate those extra flags?

**System information**
- ONNX Runtime version (you are using): 1.12.0
- ONNX version: 1.12.0
- Optimum version: built from src

**Describe the solution you'd like**

Export directly with 
```python
OnnxModel.save(self.model, output_path, use_external_data_format)
```
instead of treating `use_external_data_format` separately.

**Describe alternatives you've considered**

Define the external file path the same as the model proto

**Additional context**

I can help to submit a PR for it.

**Comment by yufenglee** [comment]
quantization also saves model file and the external files in the same directory. location specifies the external file name under the same directory as the model file.

**Comment by JingyaHuang** [comment]
Hi @yufenglee,

Thanks for the explanation! After further debugging, it turns out that the reason why the external data was put outside of the folder where stores the model proto comes from the fact that our `output_path` is a PosixPath object and [`onnx._get_file_path`](https://github.com/onnx/onnx/blob/e6547e8b41578c766dd2ccf298a01b2b1b6335cd/onnx/__init__.py#L50-L56) return `os.path.abspath(f.name)` instead of `os.path.abspath(f)` which remove the folder from the path. 


Out of curiosity, is there any particular reasons that quantization add additional lines for saving the external tensors instead of using the [flags `location` and `save_as_external_data`](https://github.com/onnx/onnx/blob/main/onnx/__init__.py#L194) of `onnx.save_model` directly?
