### ISSUE TITLE
 How do I understand the error message such as: 7508808

### ISSUE THREAD

**Issue by 1093919186** [microsoft/onnxruntime#12622]
The model I converted with sklearn-onnx and run on onnxruntime-web, the error message is only: 7508808. How should I understand this error message？

**System information**
- 1.11.0

**Comment by shalvamist** [comment]
Hi,

Thanks for the info, can you please share a bit more information on the issue -
1. full error message 
2. Code snippet for the conversion 
3. Model used to generate the issue - if you can share it 

Thanks

**Comment by 1093919186** [comment]
Hi, thanks a lot for your reply and I will share my generated error files and code.

#### 1、The onnx model created by the sklearn-onnx as shown below:
```
import numpy as np
from sklearn.linear_model import LogisticRegression

np.random.seed(12)
num_observations = 5000 
x1 = np.random.multivariate_normal([0, 0], [[1, .75],[.75, 1]], num_observations) 
x2 = np.random.multivariate_normal([1, 4], [[1, .75],[.75, 1]], num_observations) 

X = np.vstack((x1, x2)).astype(np.float32) 
y = np.hstack((np.zeros(num_observations), 
               np.ones(num_observations))) 
print (X.shape, y.shape) 

lf = LogisticRegression(fit_intercept=True, C = 1e15)
lf.fit(X, y)
print ("(sklearn)逻辑回归的参数w, b分别为: ", lf.coef_, lf.intercept_) 
print(lf.predict([ X[4998],X[5001], X[5003], X[4997] ]))

from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType

onx = convert_sklearn(lf, initial_types=[('float_input', FloatTensorType([None, 2]))]
)
with open("./models/lg_model.onnx", "wb") as f:
    f.write(onx.SerializeToString())
```

#### 2、The model file as shown in the email attachment.

#### 3、Calling the model using javascript by onnxruntime-web
```
 <script src="https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.min.js"></script>
        <script>
            // use an async context to call onnxruntime functions.
            async function main() {
                try {
                    // create a new session and load the specific model.
                    const session = await ort.InferenceSession.create('http://localhost:5500/项目学习/19-机器学习js版本/2-逻辑回归/models/lg_model.onnx');
                    console.log(session);
                    // prepare inputs. a tensor need its corresponding TypedArray as data
                    const dataA = Float32Array.from([ 5,8, 1, -1 ]);
                    const tensorA = new ort.Tensor('float32', dataA, [2, 2]);

                    // prepare feeds. use model input names as keys.
                    const feeds = { float_input: tensorA };

                    // feed inputs and run
                    const results = await session.run(feeds);

                    // read from results
                    const dataC = results.c.data;
                    document.write(`data of result tensor 'c': ${dataC}`);

                } catch (e) {
                    console.log(e);
                    document.write(`failed to inference ONNX model: ${e}.`);
                }
            }

            main();
        </script>
```

4、The error is "8176872", no other information.
<img width="513" alt="image" src="https://user-images.githubusercontent.com/61229971/185521043-2ef725d8-c9fb-45f6-ae67-4dc344415f90.png">

**Comment by 1093919186** [comment]
Hi shalvamist, thanks a lot for your reply and I will share my files and code which generated error.

The code, I display it in the github issue comments. The onnx model file is shown in the attachment of this email.

The models converted by sklearn-onnx cannot be run(api) in the browser, and some cannot even be created by onnxruntime-web apis(create and run).&nbsp;

I look forward to your reply, if you have any more doubts, contact me, please.


Thanks again.&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/onnxruntime"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月18日(星期四) 凌晨5:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/onnxruntime]  How do I understand the error message such as: 7508808 (Issue #12622)





 
Hi,
 
Thanks for the info, can you please share a bit more information on the issue -
  
full error message
 
Code snippet for the conversion
 
Model used to generate the issue - if you can share it
  
Thanks

**Comment by shalvamist** [comment]
Thanks for the detailed response :).
I will review and try to reproduce the issue on my side - I will update as soon as I have more to share

**Comment by shalvamist** [comment]
Hey - A quick update - I was able to reproduce the issue as you described. I got the following output - 
"failed to inference ONNX model: 8176872."

I am debugging to isolate the cause - I will keep you posted

**Comment by 1093919186** [comment]
Thanks a lot, I am looking forward to your answer.&nbsp;
Aside from this example, linear_model can't do this either.
The model file&nbsp;is shown in the attachment of this email.
Thanks again.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/onnxruntime"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月24日(星期三) 凌晨1:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/onnxruntime]  How do I understand the error message such as: 7508808 (Issue #12622)





 
Hey - A quick update - I was able to reproduce the issue as you described. I got the following output -
 "failed to inference ONNX model: 8176872."
 
I am debugging to isolate the cause - I will keep you posted

**Comment by shalvamist** [comment]
Hey,

We have an update. here are the current findings - 
1. The issue seems to be a crash with a particular build of ORT Web
2. The cause for the crash was the nature of the out generated by the model - 
![image](https://user-images.githubusercontent.com/94086448/186532720-a8fc9577-64b0-45ce-803d-7d27b2b1aef1.png)
The output isn't a tensor which is a problem - there is a way to bypass this kind of issue when converting the model, please review https://github.com/onnx/sklearn-onnx/issues/754
3. We are still working on the silent crash to find out the root and fix it

I will keep you posted with more findings as we uncover them.

**Comment by 1093919186** [comment]
Hey,


I’m grateful for your answer. The lg_model.onnx can already be run in my browser After converting the model as the review&nbsp;onnx/sklearn-onnx#754.
However, there are still two troubles.


1. The Linear_model.onnx I sent you in the last email still doesn't work. How can I bypass when I converted the LinearRegression model?
2. I run my code in <script&gt; tag is ok. But, the way I import it by npm package will throw an error as follows:




My code:






Thanks again.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/onnxruntime"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月25日(星期四) 上午6:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/onnxruntime]  How do I understand the error message such as: 7508808 (Issue #12622)





 
Hey,
 
We have an update. here are the current findings -
  
The issue seems to be a crash with a particular build of ORT Web
 
The cause for the crash was the nature of the out generated by the model -
 
 The output isn't a tensor which is a problem - there is a way to bypass this kind of issue when converting the model, please review onnx/sklearn-onnx#754
 
We are still working on the silent crash to find out the root and fix it
  
I will keep you posted with more findings as we uncover them.

**Comment by os1ma** [comment]
Hi,

I also encountered a similar error with sklearn-onnx and onnxruntime-web using LogisticRegression for the model.
I could bypass the error by adding `options={'zipmap': False}` to `convert_sklearn` argument, referring to https://github.com/onnx/sklearn-onnx/issues/754 !

Thanks for this Issue and debugging!

**Comment by 1093919186** [comment]
Hey shalvamist,&nbsp;I’m grateful for&nbsp;your efforts, And&nbsp;Sorry for the late reply.
The Linear_model.onnx I sent you in this email.&nbsp;If you haven't received it, contact me immediately, please.
In addition to,&nbsp;the trouble I import it by npm package will throw an error as follows:









Thanks again.
I look forward to your reply, if you have any more doubts, contact me, please.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/onnxruntime"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月1日(星期四) 凌晨3:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/onnxruntime]  How do I understand the error message such as: 7508808 (Issue #12622)





 
Hey All,
 
I have an update on the root cause - it resulted from an uncaught exception (since the exceptions aren't built into the CDN repo). I opened a new PR to fix the issue - #12811
 
@1093919186 - can you please send the model again ? I can't find the Linear_model.onnx model in my inbox

**Comment by shalvamist** [comment]
Hi,

Thanks for sharing the images - I will try to reproduce and get back to you on that.
For the model - I am sorry I didn't get the email. Can you please try to resend it ?

**Comment by 1093919186** [comment]
> Hi,
> 
> Thanks for sharing the images - I will try to reproduce and get back to you on that. For the model - I am sorry I didn't get the email. Can you please try to resend it ?

[linear_model.onnx.zip](https://github.com/microsoft/onnxruntime/files/9561910/linear_model.onnx.zip)

**Comment by 1093919186** [comment]
> Hi,
> 
> Thanks for sharing the images - I will try to reproduce and get back to you on that. For the model - I am sorry I didn't get the email. Can you please try to resend it ?

**Comment by 1093919186** [comment]
Hi,
I'm sorry, I don't know why you can't receive the attachment that I sent in my email.
I have attached a link for the file in the github comment, you can download it, hard work.


Thanks again, Looking forward to your reply.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/onnxruntime"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月13日(星期二) 凌晨0:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/onnxruntime]  How do I understand the error message such as: 7508808 (Issue #12622)





 
Hi,
 
Thanks for sharing the images - I will try to reproduce and get back to you on that.
 For the model - I am sorry I didn't get the email. Can you please try to resend it ?

**Comment by 1093919186** [comment]
> Hi,
> 
> Thanks for sharing the images - I will try to reproduce and get back to you on that. For the mod
[linear_model.onnx.zip](https://github.com/microsoft/onnxruntime/files/9561968/linear_model.onnx.zip)

**Comment by 1093919186** [comment]
> Hi,
> 
> Thanks for sharing the images - I will try to reproduce and get back to you on that. For the model - I am sorry I didn't get the email. Can you please try to resend it ?

[linear_model.onnx.zip](https://github.com/microsoft/onnxruntime/files/9561973/linear_model.onnx.zip)

**Comment by shalvamist** [comment]
Hey,

I think I might have the answer for your npm error - you might be missing a step in the consumption ORT Web. Can you please refer to this example - [Classify images with ONNX Runtime and Next.js - onnxruntime](https://onnxruntime.ai/docs/tutorials/web/classify-images-nextjs-github-template.html#nextconfigjs)

**Comment by shalvamist** [comment]
Updating the issue with the PR fixing the problem - [PR link](https://github.com/microsoft/onnxruntime/pull/13644)
Please let me know if you have any feedback on the fix - Thanks.

**Comment by guschmue** [comment]
onnxruntime-1.14 has the changes to that produce a proper error message.
