### ISSUE TITLE
Worker Errror :  Error: no available backend found. ERR: [wasm] TypeError: n(...).dirname is not a function

### ISSUE THREAD

**Issue by juliangdz** [microsoft/onnxruntime#12665]
Hi i need some help on this issue. 

I have a react-app built using create-react-app that loads the onnx models and does inference fine . The react app works fine . 

However my issue is encountered when i try to Create a Webview Application using electronjs with the react-app . The onnx backend wasm was loaded fine and the worker scripts loads the models and did inference when i use the script 

"start": "set BROWSER=none&&react-scripts start",
"start-electron": "set ELECTRON_START_URL=http://localhost:3000&&electron .",

Running npm run start and npm run start-electron in different terminals brings up the Developer Version of the Electron-react application and everything works fine without error . 

However i get the following error when i Try to package the Electron-React Application . I first run the build script to build the react app and copy my electron files to the build folder. Then i run the script 

"package": "set ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true&&electron-builder build  -c.extraMetadata.main=build/electron/main.js --publish never",

This creates a dist with the .exe. 

The following error is what i see in the devtools console 

Worker Eerrror :  Error: no available backend found. ERR: [wasm] TypeError: n(...).dirname is not a function
    at inference-session-impl.js:170:39
    at async h.create (backend-impl.js:51:31)

I use ort.min.js and its files all exist in the public folder along with the wasm* files . 

Please provide some insight into this , i have tried a few methods trying to understand if its a issue with my package.json by checking my build files path , but i have overcome those issues by adding "homepage": "./",

**Comment by baijumeswani** [comment]
@fs-eire @shalvamist for more info.

**Comment by juliangdz** [comment]
The issue has been resolved . Something you need to specify in the documentation is about packaging Web assembly while building ReactJS and electron applications . The *.wasm files do not get bundled .

I fixed my error in bundling the *.wasm files for build production by setting ort.env.wasm.wasmpaths overide .

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by baijumeswani** [comment]
Thanks @juliangdz. I'll close this issue. @shalvamist @fs-eire Do we need to update our documentation for this use case?

**Comment by cassiebreviu** [comment]
> Thanks @juliangdz. I'll close this issue. @shalvamist @fs-eire Do we need to update our documentation for this use case?

I documented it here a while ago: https://onnxruntime.ai/docs/tutorials/web/classify-images-nextjs-github-template.html#nextconfigjs

Are we able to fix this issue in the package? It is a problem that has come up many times.
