### ISSUE TITLE
Request to add convert_beam_search for model conversion 

### ISSUE THREAD

**Issue by OriAlpha** [microsoft/onnxruntime#12666]
**Is your feature request related to a problem? Please describe.**
This was a feature, already exist which helped to convert mt5 pytorch model to onnx runtime. But not sure why this script was removed from onnxruntime. The script i am talking is about `convert_beam_search.py `. This script helped to export model easily, not sure why this was removed???

**System information**
- ONNX Runtime version (you are using): 1.12.1

**Describe the solution you'd like**
It would be nice, to add this script back. 

For more details i can tagging git log here, https://github.com/microsoft/onnxruntime/commit/def78a1b815ae2b60d19df97c352230591e7d7a6

**Comment by baijumeswani** [comment]
From this pull request: https://github.com/microsoft/onnxruntime/commit/89ac61f4d446e4a3a628203c31f5291a3a739c4c#diff-b62a7964f33072e46e15de8bcb49df48c72adf77b1b14bd85ea01b6e10c441a5, it seems like the name of the file was changed to [convert_generation.py](https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/python/tools/transformers/convert_generation.py)

@wangyems, @tianleiwu for more details.

**Comment by tianleiwu** [comment]
@OriAlpha, the script was renamed to convert_generation.py since we add support of other generation methods like greedy search (right now greedy search is for GPT-2 only). You can use it to convert t5 with beam search.

**Comment by baijumeswani** [comment]
Thanks @tianleiwu for the context. @OriAlpha closing this issue. Let us know if you have more questions on this.

**Comment by OriAlpha** [comment]
Thanks for confirming it.
