### ISSUE TITLE
[Build] error: ‘if constexpr’ only available with -std=c++17 or -std=gnu++17

### ISSUE THREAD

**Issue by jiangjiajun** [microsoft/onnxruntime#12683]
**Describe the bug**
While buiding on jetson nano with jetpack 4.6, it will throw an error `onnxruntime/include/onnxruntime/core/framework/data_types_internal.h:531:4: error: ‘if constexpr’ only available with -std=c++17 or -std=gnu++17 [-Werror]`

The g++/gcc version is 7.5.0, I also tried to upgrade g++/gcc to 8.4 to solve the problem, but it will throw the same error information

![image](https://user-images.githubusercontent.com/19339784/186181033-0d55064c-8b67-4f2a-a02a-2772b0148ad0.png)

**Comment by baijumeswani** [comment]
@jiangjiajun with that version of gcc/g++, I don't think you should be seeing that error. I am not sure what might be going on with your build. Can you provide the build log for the compiler identification that is printed at the begining of the `onnxruntime` build?
For example, when I build, I can see the below at the beginning of the build:

```
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
```

**Comment by yuslepukhin** [comment]
We used to have `ORT_IF_CONSTEXPR` macro that automatically handled this issue. We no longer support non C++17 compliant compilers. See https://github.com/microsoft/onnxruntime/commit/ac7538b909990f89f9bfebb325cd53c3d31cf158
