### ISSUE TITLE
[win7 dlls]Failure to run ORT on win7 64-bit system, missing api-ms-win-core-* dlls

### ISSUE THREAD

**Issue by taijizhao** [microsoft/onnxruntime#12718]
**Describe the bug**
We plan to deploy a PyTorch model with onnxruntime on windows platforms. We build our APP using visual studio 2019 for both x86 and x64 platforms. Everything is fine on win7 32-bit/win8/win10 systems but fails to run on win7 64-bit systems. For testing, we built a minimal program that just starts an ORT session.:
```C++
#include <iostream>
#include <onnxruntime_cxx_api.h>
using namespace std;
int main()
{
    Ort::Env env;
    Ort::RunOptions runOptions;
    Ort::Session session(nullptr);
    std:cout << "onnx env established. " << endl;
    system("pause");
    return 0;
}
```
and run it on a freshly installed win7 sp1 64-bit system, it gives the following error:
![微信图片_20220825101134](https://user-images.githubusercontent.com/7842342/186558498-861f40cc-915c-4170-98a9-be49cd7a26a0.jpg)
Following issue #4570 , I installed two windows updates [Update KB3068708](https://support.microsoft.com/en-us/help/3068708/update-for-customer-experience-and-diagnostic-telemetry) [Update KB3080149](https://support.microsoft.com/en-us/help/3080149/update-for-customer-experience-and-diagnostic-telemetry) and  VC_redist.x64.exe, the problem persists. 
I checked the dependencies using the depends.exe tool and found that a couple of API-MS-WIN-CORE-* Dlls are missing.
 
![无标题](https://user-images.githubusercontent.com/7842342/186571636-5941354f-ad23-42d3-900a-fddd8b9e3584.png)
The app runs well on win8/win10 systems, and the x86-built app can run on a win7 32-bit system. The only failure is with win7-64bit.

**Urgency**
At least for me, it is an urgent issue that has to be handled in a few days. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Development on Win10 with Visual Studio 2019, deployed on win7 64-bit system.
- ONNX Runtime installed from (source or binary): NuGet of VS
- ONNX Runtime version: 1.12.1
- Python version:
- Visual Studio version (if applicable): VS2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None
- GPU model and memory: None

**To Reproduce**
- Describe steps/code to reproduce the behavior.
1. start a VS 2019 console application project
2. Install ORT 1.12.1 using NuGet
3. Use the following test code which only setup an empty ORT session
```C++
#include <iostream>
#include <onnxruntime_cxx_api.h>
using namespace std;
int main()
{
    Ort::Env env;
    Ort::RunOptions runOptions;
    Ort::Session session(nullptr);
    std:cout << "onnx env established. " << endl;
    system("pause");
    return 0;
}
```
4. build in x64 release mode. (I also build an x86 version and the problem persists)
5. run the resulting build on a freshly installed Win7 SP1 x64 system.  With VC_redist.x64 installed, the problem persists. With the two windows updates installed, the problem persists.

- Attach the ONNX model to the issue (where applicable) to expedite the investigation.
No ONNX model is needed. Just start an empty session. 

**Expected behavior**
<img width="411" alt="无标题" src="https://user-images.githubusercontent.com/7842342/186572382-756e7793-49bb-4b97-961c-523e6e29d0e5.png">

**Comment by snnn** [comment]
Build it from source by yourself. 

https://onnxruntime.ai/docs/build/inferencing.html

**Comment by hittoome** [comment]
@taijizhao 你好，请问重新build有解决这个问题吗

**Comment by taijizhao** [comment]
> @taijizhao 你好，请问重新build有解决这个问题吗

我没有重新build，只是暂时降级了onnxruntime的版本，好像是1.6还是1.7，就没有这个问题了。

**Comment by hittoome** [comment]
> > @taijizhao 你好，请问重新build有解决这个问题吗
> 
> 我没有重新build，只是暂时降级了onnxruntime的版本，好像是1.6还是1.7，就没有这个问题了。

Release V1.13.1 更新说明有提到不再支持win7，需要用户自己编译。可能在1.12.1版本就已经不支持win7了吧，想用opest16以上的话看来只能自己编译了QwQ

**Comment by taijizhao** [comment]
> > > @taijizhao 你好，请问重新build有解决这个问题吗
> > 
> > 
> > 我没有重新build，只是暂时降级了onnxruntime的版本，好像是1.6还是1.7，就没有这个问题了。
> 
> Release V1.13.1 更新说明有提到不再支持win7，需要用户自己编译。可能在1.12.1版本就已经不支持win7了吧，想用opest16以上的话看来只能自己编译了QwQ

是啊，但是我完全不知道怎么自己编译。。。请问您尝试过自己重新编译吗？我现在也面临这个问题，老版本的ort只能凑活用，很多op都不支持了。

**Comment by snnn** [comment]
> 是啊，但是我完全不知道怎么自己编译。。。请问您尝试过自己重新编译吗？我现在也面临这个问题，老版本的ort只能凑活用，很多op都不支持了。

You can try this doc: https://onnxruntime.ai/docs/build/inferencing.html

**Comment by taijizhao** [comment]
> > 是啊，但是我完全不知道怎么自己编译。。。请问您尝试过自己重新编译吗？我现在也面临这个问题，老版本的ort只能凑活用，很多op都不支持了。
> 
> You can try this doc: https://onnxruntime.ai/docs/build/inferencing.html

Thank you very much! I will try.

**Comment by taijizhao** [comment]
> > 是啊，但是我完全不知道怎么自己编译。。。请问您尝试过自己重新编译吗？我现在也面临这个问题，老版本的ort只能凑活用，很多op都不支持了。
> 
> You can try this doc: https://onnxruntime.ai/docs/build/inferencing.html

Please excuse me for a stupid question. 
If I want to make my APP compatible with both win7 32-bit / win7 64-bit and win10, what I should do?
According to my understanding, I should first build ORT with each system. But should I build my APP with each system too?

**Comment by leoxiaoping** [comment]
最后支持win7的版本是1.13

**Comment by hittoome** [comment]
你好，邮件我已收到，我会尽快阅读并且给您回自复。

**Comment by hittoome** [comment]
你好，邮件我已收到，我会尽快阅读并且给您回自复。
