### ISSUE TITLE
MSBuild .props copies x64 onnxruntime_providers_shared.dll to output folder when target platform is arm64

### ISSUE THREAD

**Issue by fpribeiro** [microsoft/onnxruntime#12731]
**Describe the bug**
Microsoft.ML.OnnxRuntime.props that comes with the nuget package copies the x64 build of onnxruntime_providers_shared.dll to the output directory, irrespective of the target architecture. On ARM64, this results in a x64 dll being copied.

**Urgency**
Our build pipeline is working around this issue with post-build steps.

**System information**
- OS Platform and Distribution: Windows 11
- ONNX Runtime installed from (source or binary): binary (nuget package)
- ONNX Runtime version: 1.12.0
- Visual Studio version (if applicable): 2022

**To Reproduce**
1. Build a project with an ARM64 target.
2. Check the output directory. onnxruntime_providers_shared.dll is a x64 binary (instead of ARM64). onnxruntime.dll is a ARM64 binary as expected. 

**Expected behavior**
All ONNX dlls copied to the output folder match the target architecture.

**Additional context**
Microsoft.ML.OnnxRuntime.props always copies x64 dll, without filtering for target architecture.

    <None Include="$(MSBuildThisFileDirectory)..\..\runtimes\win-x64\native\onnxruntime_providers_shared.dll"
          Condition="Exists('$(MSBuildThisFileDirectory)..\..\runtimes\win-x64\native\onnxruntime_providers_shared.dll')">
      <Link>onnxruntime_providers_shared.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </None>

**Comment by hariharans29** [comment]
Thanks. It seems like the `Condition` neeeds to be modified so as to make the conditionally copy the dlls from the win-x64 or win-arm64 folders based on the target platform of the user.
