### ISSUE TITLE
Two gathers followed by a matmul fail to load on DML

### ISSUE THREAD

**Issue by AXKuhta** [microsoft/onnxruntime#12767]
**Describe the bug**
A small graph consisting of two gather operations followed by a matmul operation works fine on the CPU backend but fails to load on the DML backend.

Here's the cleaned up error text:

```
2022-08-29 11:36:44.6399539 [E:onnxruntime:, inference_session.cc:1530 onnxruntime::InferenceSession::Initialize::<lambda_300271ae079a93faf30b4ef2a83d2ebc>::operator ()] Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\FusedGraphKernel.cpp(148)\onnxruntime_pybind11_state.pyd!00007FFEB4352652: (caller: 00007FFEB434EDBE) Exception(1) tid(1b40) 80070057 ¤ ¤ ¤ ¤ ¤ ¤ ¤ ¤  ¤ ¤ ¤¤ ¤  ¤ ¤ ¤ ¤ ¤ ¤ ¤ .
```

Discovered while trying to make [RWKV-4](https://github.com/BlinkDL/RWKV-LM) language model run on DML. 

**Urgency**
Not urgent. Workaround found.

**System information**
- OS Platform and Distribution: Windows 10, 21H2
- ONNX Runtime installed from: pip install onnxruntime-directml
- ONNX Runtime version: 1.12.1
- Python version: 3.10.5
- GPU model and memory: Nvidia GTX1060, 6GB

**To Reproduce**
Here's a sample file: [matmul.zip](https://github.com/microsoft/onnxruntime/files/9441509/matmul.zip)

Run this code to produce a similar .onnx file:

```python
import torch

class MATMUL(torch.nn.Module):
	def __init__(self):
		super().__init__()
		self.mat = torch.rand([768, 768])

	def forward(self, idx):
		return self.mat @ self.mat[idx[-1]]

model = MATMUL()

idx = torch.randint(768, [1024])

torch.onnx.export(model, args=(idx,), f="matmul.onnx", input_names = ["idx"], output_names = ["x"], verbose=True)
```

Run this code to reproduce the error:

```python
from onnxruntime import InferenceSession

# ['DmlExecutionProvider', 'CPUExecutionProvider']
session = InferenceSession('matmul.onnx', providers=['DmlExecutionProvider'])

inputs = { "idx": [0] * 1024 }
outputs = session.run(output_names=["x"], input_feed=inputs)

print(outputs)
```

**Expected behavior**
The model loads on the DML backend and produces outputs identical to the CPU backend.

**Screenshots**
Here's the error message: 
![error_in_python](https://user-images.githubusercontent.com/11133304/187123153-623fe9fa-b98b-43d7-8911-af029fb47c8a.PNG)

**Additional context**
Here's the graph as seen in netron.app:
![graph](https://user-images.githubusercontent.com/11133304/187123413-35de12e7-898c-4173-95b4-c5d35353611d.PNG)

**Comment by AXKuhta** [comment]
Well, 15 minutes later I found a workaround:

```diff
        def forward(self, idx):
-               return self.mat @ self.mat[idx[-1]]
+               return self.mat @ self.mat[idx[-1]].unsqueeze(1)
```

So it must be matmul dimension mismatch: [768, 768] @ [768] doesn't work, but [768, 768] @ [768, 1] works.

**Comment by fdwr** [comment]
@AXKuhta: 1D inputs should work and broadcast to 2D implicitly, but I'm glad you were able to easily work around it by reshaping. The bug is in the ORT EP DmlOperatorMatMul.cpp, which calls `MatMulShapeMapping` but then calls the generic `CreateTensorDescFromInput` helper to broadcast strides, and MatMul has special rules to follow which the generic broadcasting doesn't handle. Surprisingly it's been this way 4 years without an earlier report (thanks), but we should fix it for 1.4.

**Comment by nums11** [comment]
Closing as resolved.

**Comment by fdwr** [comment]
@nums11 Do you know the corresponding CR that fixed this?

**Comment by nums11** [comment]
No I'm not sure. I just assumed it had been addressed but we can reopen if that's not the case.
