### ISSUE TITLE
ONNX model fails to load on amd GPU, but loads fine on CPU

### ISSUE THREAD

**Issue by simona198710** [microsoft/onnxruntime#12761]
**Describe the bug**
Getting this error when trying to load the huggingface unet and vae exported to onnx using DmlExecutionProvider.

[E:onnxruntime:, inference_session.cc:1484 onnxruntime::InferenceSession::Initialize::<lambda_70debc81dc7538bfc077b449cf61fe32>::operator ()] Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\AbiCustomRegistry.cpp(507)\onnxruntime_pybind11_state.pyd!00007FF8BFF220E6: (caller: 00007FF8BFF2CA4F) Exception(3) tid(5a34) 80070057 The parameter is incorrect.

Works fine when loading on CPUExecutionProvider.

**Urgency**
Somewhat, prevents AMD users from using stable diffusion on gpu

**System information**
- OS Platform and Distribution: Windows 10
- ONNX Runtime installed from (source or binary): python package using pip install
- ONNX Runtime version: Currently on ort-nightly-directml 1.13.0.dev20220823003 (after the fix for this https://github.com/microsoft/onnxruntime/issues/12677). But also tried with 1.12.1, same error
- Python version: 3.9
- GPU model and memory: AMD RX 480 8g vram 16gb ram

**To Reproduce**
Original model is here: https://huggingface.co/CompVis/stable-diffusion-v1-4
Onnx version here (not the same as mine, but getting same error): 
https://huggingface.co/bes-dev/stable-diffusion-v1-4-onnx/

**Expected behavior**
To properly load without errors, like it does on CPU.

**Additional context**

Export settings:
exinp = torch.randn([1, 4, 64, 64], device='cpu')
torch.onnx.export(vae.decoder, exinp, "vae.onnx", opset_version=15, do_constant_folding=False)

**Comment by harishanand95** [comment]
@simona198710 I have been looking into this work recently and was able to get diffusers library working on AMD GPUs in Windows with DirectML. It needs a build of the onnxruntime and I have written down the instruction on the link here https://github.com/harishanand95/diffusers/blob/main/examples/inference/readme.md#instructions-for-onnx-dml-execution-on-windows

**Comment by simona198710** [comment]
@harishanand95 Thank you, compiling from source works. It does let me load it now. 
I incorrectly assumed that nightly actually had the most recent directml changes.

**Comment by AssasinatorCzar** [comment]
> @harishanand95 did you get the solution I'm having the same problem... It's using CPU not gpu

**Comment by AssasinatorCzar** [comment]
I'm having the same problem...what's the solution??? It's working with cpu but not GPU. I install it more than 7 times with every version of python but still it's using CPU

**Comment by pranavsharma** [comment]
cc @fdwr

**Comment by pauldog** [comment]
Same. Anyone found a solution?

**Comment by fdwr** [comment]
@simona198710 I noticed this old issue was still open - is it closeable now? I've come across a few other projects using DML+ORT with Stable Diffusion too (e.g. https://github.com/axodox/axodox-machinelearning, and even my own little test app...):

![image](https://github.com/microsoft/onnxruntime/assets/1809166/420d768d-58cb-4212-912c-4fa97e778c46)

**Comment by nums11** [comment]
Closing as resolved.
