### ISSUE TITLE
Build failing on Windows: onnxruntime master branch

### ISSUE THREAD

**Issue by kubansal** [microsoft/onnxruntime#1278]
**Describe the bug**
Syntax errors:
Onnx\OnnxRuntimev4\onnxruntime\onnxruntime\core\mlas\lib\amd64\SgemmKernelAvx512F.asm(488): error A2008: syntax error : k1 [D:\Onnx\OnnxRuntimev4\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_mlas.vcxproj]      
:\Onnx\OnnxRuntimev4\onnxruntime\onnxruntime\core\mlas\lib\amd64\SgemmKernelAvx512F.asm(488): error A2008: syntax error : k1 [D:\Onnx\OnnxRuntimev4\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_mlas.vcxproj]      
:\Onnx\OnnxRuntimev4\onnxruntime\onnxruntime\core\mlas\lib\amd64\SgemmKernelAvx512F.asm(488): error A2008: syntax error : k1 [D:\Onnx\OnnxRuntimev4\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_mlas.vcxproj].

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows x86_64
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: git master branch
- Python version: 3.7
- Visual Studio version (if applicable): VS 15 2017
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
cd onnxruntime
build.bat --config=RelWithDebInfo --mkldnn
Describe steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tracysh** [comment]
Hello. The error is what you'd see if you were using too old of a Visual Studio build that doesn't support AVX-512 instructions. What is the version number shown in the cmake output? Can you try updating your compiler to the latest VS 2017?

Example:
-- The C compiler identification is MSVC 19.16.27027.1
-- The CXX compiler identification is MSVC 19.16.27027.1

**Comment by pranavsharma** [comment]
There is no option called ```--mkldnn```. It's ```--use_mkldnn```.

**Comment by kubansal** [comment]
@pranavsharma : Sorry it was a typo. I actually used --use_mkldnn. 

As per @tracysh, I checked the ml64.exe version and it built with an outdated version (14.10.*) which didn't have support for AVX-512 instructions. Updated the VS and now it is building fine 👍  Thanks @tracysh
