### ISSUE TITLE
Build with Intel C++ Compiler

### ISSUE THREAD

**Issue by joyIntel** [microsoft/onnxruntime#1279]
In Windows, the default compiler is VC. I want to build onnxruntime in windows with Intel C++ compiler. What are the necessary changes I need to make ?

**Comment by snnn** [comment]
```
CC=icc CXX=icpc cmake ......
```

see: https://cmake.org/cmake/help/v3.15/envvar/CXX.html

**Comment by joyIntel** [comment]
Hello,

Thanks for giving the hints. I am trying the following command –

cmake -DCMAKE_C_COMPILER="C:\Program Files (x86)\IntelSWTools\parallel_studio_xe_2019\compilers_and_libraries_2019\windows\bin\intel64" -DCMAKE_CXX_COMPILER="C:\Program Files (x86)\IntelSWTools\parallel_studio_xe_2019\compilers_and_libraries_2019\windows\bin\intel64" -DCMAKE_BUILD_TYPE=Release


But it is not generating the binaries.


Thanks,
Joy

**Comment by snnn** [comment]
Hi @joyintel,  

It's a commercial software, I don't have it, so I can't reproduce your error. Sorry. 

Could you please post the full build log here?

**Comment by tracysh** [comment]
Maybe it should instead be (add icl.exe to the parameters instead of just the directory):

cmake -DCMAKE_C_COMPILER="C:\Program Files (x86)\IntelSWTools\parallel_studio_xe_2019\compilers_and_libraries_2019\windows\bin\intel64\**icl.exe**" -DCMAKE_CXX_COMPILER="C:\Program Files (x86)\IntelSWTools\parallel_studio_xe_2019\compilers_and_libraries_2019\windows\bin\intel64\**icl.exe**" -DCMAKE_BUILD_TYPE=Release

**Comment by joyIntel** [comment]
I have given the trace here. The build is successful but there are no binaries (onnxruntime_perf_test.exe) created in the specified directory. 

C:\ICC_Vs_VC\ICC\onnxruntime\build>cmake ..\cmake\ -DCMAKE_C_COMPILER="C:\Program Files (x86)\IntelSWTools\parallel_studio_xe_2019\compilers_and_libraries_2019\windows\bin\intel64\icl.exe*" -DCMAKE_CXX_COMPILER="C:\Program Files (x86)\IntelSWTools\parallel_studio_xe_2019\compilers_and_libraries_2019\windows\bin\intel64\icl.exe*" -DCMAKE_BUILD_TYPE=Release
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.16.27031.1
-- The CXX compiler identification is MSVC 19.16.27031.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Performing Test HAS_QSPECTRE
-- Performing Test HAS_QSPECTRE - Failed
-- Performing Test HAS_GUARD_CF
-- Performing Test HAS_GUARD_CF - Success
-- Found ZLIB: C:/Users/jchakrab/Anaconda/Library/lib/z.lib (found version "1.2.11")
-- Found PNG: C:/Users/jchakrab/Anaconda/Library/lib/libpng.lib (found version "1.6.36")
# date: USE_SYSTEM_TZ_DB ON
# date: USE_TZ_DB_IN_DOT OFF
# date: BUILD_SHARED_LIBS OFF
# date: ENABLE_DATE_TESTING OFF
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.21.0.windows.1")
-- Found PythonInterp: C:/Users/jchakrab/Anaconda/python.exe (found version "3.7.3")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/ICC_Vs_VC/ICC/onnxruntime/build

C:\ICC_Vs_VC\ICC\onnxruntime\build>

**Comment by snnn** [comment]
Hi @joyIntel

Could you find a "*.sln" file in C:\ICC_Vs_VC\ICC\onnxruntime\build dir? 
If it exists, please open it, **select build config  to 'Release',** then build the solution.

**Comment by joyIntel** [comment]
That works. Thanks @snnn

**Comment by priyanka1023** [comment]
I have tried to use the CMAKE_C_COMPILER and CMAKE_CXX_COMPILER flags. But every time MSVC is selected instead.

**Comment by joyIntel** [comment]
@priyanka1023 Use the following commands -
1> cmake -A x64 -G "Visual Studio 15 2017" -T "Intel C++ Compiler 19.0" ..\cmake
2> msbuild "onnxruntime.sln" /t:Rebuild /p:Configuration=Release /m
