### ISSUE TITLE
MKLDNN Update

### ISSUE THREAD

**Issue by xkszltl** [microsoft/onnxruntime#1281]
**Describe the bug**

FYI MKLDNN 0.19 is out for a while with new version of MKLML, and MKLDNN v0.20 is already in RC

https://github.com/microsoft/onnxruntime/blob/204bd38d6a4d40d13affd234ec55459e354f1f4a/cmake/external/mkldnn.cmake#L5

**Comment by pranavsharma** [comment]
Thanks for the updated? Have you tested it? How much perf improvement does it show?

**Comment by xkszltl** [comment]
No. It's just FYI.

Here's the story about what brings me to this:

I was faking MKLML with full MKL, which works great with native C++.
When we integrate it with .Net, C# tries to check for all symbols at load time, even if it's unused.
And interestingly it found a missing function in the latest version of full MKL (2019 update 4) but exists the version of MKLML used by onnxruntime (2019.0.3.20190220).

**Comment by snnn** [comment]
Talked with George, we are planning to do it. @faxu, you may follow up with George.

**Comment by peterjc123** [comment]
Any updates for this?

**Comment by peterjc123** [comment]
Do you have any plan to update MKLDNN to v0.20.1?

**Comment by faxu** [comment]
Will be addressed by #2102
