### ISSUE TITLE
CPU runtime uint8 quantize model inference speed much slower

### ISSUE THREAD

**Issue by yszhou2019** [microsoft/onnxruntime#12854]
**Describe the bug**
Inference speed of quant QUInt8 on ONNXruntime is nearly 10x slower than default fp32 on CPU for the same model (cpp).
Can we expect an approach to speed up inference?

**Urgency**
none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 22.04
- ONNX Runtime installed from (source or binary):binary
- ONNX Runtime version:1.12.0
- CPU: Intel(R) Xeon(R) Gold 6342 CPU @ 2.80GHz
- CPU support flags: avx512, avx512_vnni
- Python version: 3.9.12
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:none
- GPU model and memory:none

**To Reproduce**
I ran this code and successfully quantized hifiGAN to QUInt8 and I can use onnxruntime for reasoning. But the reasoning speed is reduced a lot. Why?
```python
from onnxruntime.quantization import quantize_dynamic, QuantType
quantize_dynamic("vocoder.onnx", "vocoder_uint8.onnx", weight_type=QuantType.QUInt8)
```

```
fp32
[2022-09-05 06:20:06.503][ INFO] [TTS-Core]: vocoder inference cost: 207ms
[2022-09-05 06:20:06.684][ INFO] [TTS-Core]: vocoder inference cost: 180ms
[2022-09-05 06:20:06.853][ INFO] [TTS-Core]: vocoder inference cost: 169ms
[2022-09-05 06:20:07.156][ INFO] [TTS-Core]: vocoder inference cost: 302ms
[2022-09-05 06:20:07.335][ INFO] [TTS-Core]: vocoder inference cost: 179ms
[2022-09-05 06:20:07.557][ INFO] [TTS-Core]: vocoder inference cost: 221ms
[2022-09-05 06:20:07.903][ INFO] [TTS-Core]: vocoder inference cost: 345ms
[2022-09-05 06:20:08.170][ INFO] [TTS-Core]: vocoder inference cost: 267ms
[2022-09-05 06:20:08.323][ INFO] [TTS-Core]: vocoder inference cost: 153ms
[2022-09-05 06:20:08.590][ INFO] [TTS-Core]: vocoder inference cost: 266ms
BM_websocketVocoder/iterations:1                2295 ms         2283 ms            1

quint8
[2022-09-05 05:47:21.439][ INFO] [TTS-Core]: vocoder inference cost: 1793ms
[2022-09-05 05:47:23.348][ INFO] [TTS-Core]: vocoder inference cost: 1909ms
[2022-09-05 05:47:25.349][ INFO] [TTS-Core]: vocoder inference cost: 2000ms
[2022-09-05 05:47:28.525][ INFO] [TTS-Core]: vocoder inference cost: 3176ms
[2022-09-05 05:47:30.349][ INFO] [TTS-Core]: vocoder inference cost: 1822ms
[2022-09-05 05:47:32.569][ INFO] [TTS-Core]: vocoder inference cost: 2220ms
[2022-09-05 05:47:35.748][ INFO] [TTS-Core]: vocoder inference cost: 3178ms
[2022-09-05 05:47:38.595][ INFO] [TTS-Core]: vocoder inference cost: 2847ms
[2022-09-05 05:47:40.400][ INFO] [TTS-Core]: vocoder inference cost: 1804ms
[2022-09-05 05:47:42.726][ INFO] [TTS-Core]: vocoder inference cost: 2326ms
BM_websocketVocoder/iterations:1               23081 ms        22552 ms            1
```

**Expected behavior**
quantize-model is faster than origin-model.

**Screenshots**
Exactly same input data.
![image](https://user-images.githubusercontent.com/59953951/188373386-bb22965a-f47e-47e3-86d3-23d5ef909c1a.png)

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by xadupre** [comment]
I was able to replicate your issue with this model [vocoder.onnx](https://huggingface.co/npc-engine/exported-flowtron-waveglow-librispeech-tts/blob/main/vocoder.onnx) and the following code:

```python
import numpy
import pandas
import matplotlib.pyplot as plt
from onnxruntime import InferenceSession
from mlprodict.onnxrt import OnnxInference

def profile_plot(df, size=(12, 4)):
    gr_dur = df[['dur', "args_op_name"]].groupby("args_op_name").sum().sort_values('dur')
    gr_n = df[['dur', "args_op_name"]].groupby("args_op_name").count().sort_values('dur')
    gr_n = gr_n.loc[gr_dur.index, :]

    fig, ax = plt.subplots(1, 2, figsize=size)
    gr_dur.plot.barh(ax=ax[0])
    gr_n.plot.barh(ax=ax[1])
    ax[0].set_title("duration")
    ax[1].set_title("n occurences");
    return df, ax

def profile(filename):
    x = numpy.random.random([1, 80, 10]).astype(numpy.float32)
    oinf = OnnxInference(filename, runtime="onnxruntime1",
                         runtime_options={"enable_profiling": True})
    for i in range(0, 10):
        oinf.run({"mels": x})
    df = oinf.get_profiling(as_df=True)
    return df

df1 = profile("vocoder.onnx")
df2 = profile("vocoder_uint8.onnx")
df2["args_op_name"] = df2["args_op_name"] + "-Q"
df = pandas.concat([df1, df2], axis=0)
profile_plot(df, size=(14, 8));
```

It gives the following results:

![image](https://user-images.githubusercontent.com/22452781/188454034-fefc18c3-3c2c-4f3d-a260-0971f4090409.png)

ConvInteger is slow than Conv on this particular example. I compare the input sizes. First model:

| shape                     |              dur |
|:--------------------------|-----------------:|
| 1x256x320@512x256x3@512   |      3.05178e+06 |
| 1x640x320@4096x640x1@4096 |      2.34432e+06 |
| 1x256x320@512x256x1@512   | 933696           |
| 1x256x320@256x256x1@256   |  69256           |
| 1x2x320@256x2x1@256       |   5858           |

Second model:

| shape                |              dur |
|:---------------------|-----------------:|
| 1x256x320@512x256x3  |      6.29231e+06 |
| 1x640x320@4096x640x1 |      1.88803e+06 |
| 1x256x320@512x256x1  | 750161           |
| 1x256x320@256x256x1  |  53866           |
| 1x2x320@256x2x1      |   4132           |

It needs more investigation.

**Comment by yszhou2019** [comment]
Thank you, xadupre.
I will profile the two TTS models tomorrow and give out the exact profiler outputs. (Although I think few efforts can be made to accelerate the inference speed based on the current CPU.

**Comment by skottmckay** [comment]
@yufenglee Is there a known reason why the ConvInteger nodes in a dynamically quantized model are taking longer than Conv Nodes in the original fp32 model?

**Comment by yszhou2019** [comment]
The profile result shows the ConvInteger nodes cost a lot of time.
![image](https://user-images.githubusercontent.com/59953951/188590933-a89a4851-f3f8-4528-bbc9-0784e30c231d.png)

**Comment by yufenglee** [comment]
It is recommended to use static quantization for CNN based models and we don't have special performance optimization on ConvInteger yet. Please refer to the doc here: https://onnxruntime.ai/docs/performance/quantization.html#method-selection.

@jchen351 is working on consolidating ConvInteger and QLinearConv. Once it is done, perf of ConvInteger will be improved.

**Comment by yszhou2019** [comment]
@yufenglee thanks~ I'll try the static quantize method. Hope it works. I will give out the static quant result later.

**Comment by yszhou2019** [comment]
> It is recommended to use static quantization for CNN based models and we don't have special performance optimization on ConvInteger yet. Please refer to the doc here: https://onnxruntime.ai/docs/performance/quantization.html#method-selection.
> 
> @jchen351 is working on consolidating ConvInteger and QLinearConv. Once it is done, perf of ConvInteger will be improved.

Thank you! I tried it today. The static_quantized model infer 25% faster than before. Although the quality of audio generated deduced heavily, at least it proved Integer quantization not fit for vocoder. Thank you anyway.

**Comment by yszhou2019** [comment]
Here is the profiler result of the static quantized model. 
![profile_uint8](https://user-images.githubusercontent.com/59953951/190324544-6bbd7b14-21a0-4c88-bdc1-769ce8a4d10d.png)
Maybe I should try half-precision inference. The half-precision model is thought to be faster than fp32 if supported by CPU(For my case, I guess not. It seems only few products of Intel support the bf16 according to the [link](https://en.wikichip.org/wiki/brain_floating-point_format). Unfortunately, when I type "lscpu | grep bf", no result is showed.

**Comment by yszhou2019** [comment]
> > Here is the profiler result of the static quantized model. ![profile_uint8](https://user-images.githubusercontent.com/59953951/190324544-6bbd7b14-21a0-4c88-bdc1-769ce8a4d10d.png) Maybe I should try half-precision inference. The half-precision model is thought to be faster than fp32 if supported by CPU(For my case, I guess not. It seems only few products of Intel support the bf16 according to the [link](https://en.wikichip.org/wiki/brain_floating-point_format). Unfortunately, when I type "lscpu | grep bf", no result is showed.
> 
> Hi, could you please provide the code you used to perform this static quantization? Kind Regards

Hi, here it is.
```python
import numpy
import pandas
import matplotlib.pyplot as plt
from onnxruntime import InferenceSession
from mlprodict.onnxrt import OnnxInference

def profile_plot(df, name, size=(12, 4)):
    gr_dur = df[['dur', "args_op_name"]].groupby("args_op_name").sum().sort_values('dur')
    gr_n = df[['dur', "args_op_name"]].groupby("args_op_name").count().sort_values('dur')
    gr_n = gr_n.loc[gr_dur.index, :]

    fig, ax = plt.subplots(1, 2, figsize=size)
    gr_dur.plot.barh(ax=ax[0])
    gr_n.plot.barh(ax=ax[1])
    ax[0].set_title("duration")
    ax[1].set_title("n occurences")
    fig.savefig(f"{name}_profile.png")
    return df, ax

def profile(filename):
    x = numpy.random.random([1, 80, 80]).astype(numpy.float32)
    oinf = OnnxInference(filename, runtime="onnxruntime1",
                         runtime_options={"enable_profiling": True})
    for i in range(0, 10):
        oinf.run({"mel": x})
    df = oinf.get_profiling(as_df=True)
    return df

df1 = profile("/path/to/model.onnx")

# quint8
df2 = profile("/home/shane/repos/tts-server/resources/vocoder_uint8.onnx")
df2["args_op_name"] = df2["args_op_name"] + "-Quint8"
df = pandas.concat([df1, df2], axis=0)
profile_plot(df, "quint8", size=(14, 8))

# # int8
# df2 = profile("/path/to/model_int8.onnx")
# df2["args_op_name"] = df2["args_op_name"] + "-Qint8"
# df = pandas.concat([df1, df2], axis=0)
# profile_plot(df, "qint8", size=(14, 8))

# fp16
df2 = profile("/path/to/model_fp16.onnx")
df2["args_op_name"] = df2["args_op_name"] + "-Qfp16"
df = pandas.concat([df1, df2], axis=0)
profile_plot(df, "fp16", size=(14, 8))
```

**Comment by yszhou2019** [comment]
> > Here is the profiler result of the static quantized model. ![profile_uint8](https://user-images.githubusercontent.com/59953951/190324544-6bbd7b14-21a0-4c88-bdc1-769ce8a4d10d.png) Maybe I should try half-precision inference. The half-precision model is thought to be faster than fp32 if supported by CPU(For my case, I guess not. It seems only few products of Intel support the bf16 according to the [link](https://en.wikichip.org/wiki/brain_floating-point_format). Unfortunately, when I type "lscpu | grep bf", no result is showed.
> 
> Hi, could you please provide the code you used to perform this static quantization? Kind Regards

Hi @mllopartbsc,  here it is.
```python
import numpy
import pandas
import matplotlib.pyplot as plt
from onnxruntime import InferenceSession
from mlprodict.onnxrt import OnnxInference

def profile_plot(df, name, size=(12, 4)):
    gr_dur = df[['dur', "args_op_name"]].groupby("args_op_name").sum().sort_values('dur')
    gr_n = df[['dur', "args_op_name"]].groupby("args_op_name").count().sort_values('dur')
    gr_n = gr_n.loc[gr_dur.index, :]

    fig, ax = plt.subplots(1, 2, figsize=size)
    gr_dur.plot.barh(ax=ax[0])
    gr_n.plot.barh(ax=ax[1])
    ax[0].set_title("duration")
    ax[1].set_title("n occurences")
    fig.savefig(f"{name}_profile.png")
    return df, ax

def profile(filename):
    x = numpy.random.random([1, 80, 80]).astype(numpy.float32)
    oinf = OnnxInference(filename, runtime="onnxruntime1",
                         runtime_options={"enable_profiling": True})
    for i in range(0, 10):
        oinf.run({"mel": x})
    df = oinf.get_profiling(as_df=True)
    return df

df1 = profile("/path/to/model.onnx")

# quint8
df2 = profile("/path/to/model_uint8.onnx")
df2["args_op_name"] = df2["args_op_name"] + "-Quint8"
df = pandas.concat([df1, df2], axis=0)
profile_plot(df, "quint8", size=(14, 8))

# # int8
# df2 = profile("/path/to/model_int8.onnx")
# df2["args_op_name"] = df2["args_op_name"] + "-Qint8"
# df = pandas.concat([df1, df2], axis=0)
# profile_plot(df, "qint8", size=(14, 8))

# fp16
df2 = profile("/path/to/model_fp16.onnx")
df2["args_op_name"] = df2["args_op_name"] + "-Qfp16"
df = pandas.concat([df1, df2], axis=0)
profile_plot(df, "fp16", size=(14, 8))
```

**Comment by mllopartbsc** [comment]
Hi @yszhou2019, thank you for providing the script you used for profiling, but I meant the script you've used to statically quantize your ONNX model. 

Kind Regards.
