### ISSUE TITLE
failed to run QDQ quantization model with XNNPACK backend

### ISSUE THREAD

**Issue by JasonMaojinsong** [microsoft/onnxruntime#12860]
**Describe the bug**
failed to run the QDQ quantization model with XNNPACK backend, the error message is:
![image](https://user-images.githubusercontent.com/95834241/188533300-dbcb252f-04d9-43c1-9c35-1337c1383fe6.png)

**Urgency**
yes, it's urgent

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  windows
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version:  the lastest
- Python version:
- Visual Studio version (if applicable): vs2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: no cuda
- GPU model and memory:

**To Reproduce**
I will attach the onnx model

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

[resnet50-v1-7_quant_QDQ.zip](https://github.com/microsoft/onnxruntime/files/9492832/resnet50-v1-7_quant_QDQ.zip)

**Comment by JasonMaojinsong** [comment]
@wejoncy Cheng,  thanks for checkin the XNNPACK basic QDQ operator support, could u please help to check this issue?

**Comment by skottmckay** [comment]
How was the model created? 

It has an explicit import for an internal domain with an incorrect opset version. The value of com.ms.internal.nhwc should match the ai.onnx version. It's somewhat unexpected that the model would have that as an import as that domain is intended for runtime-only internal usage by ORT.

<img width="228" alt="image" src="https://user-images.githubusercontent.com/979079/188554931-f2a030f7-7c06-4b45-905a-8e96eb5f4d45.png">

**Comment by skottmckay** [comment]
This will fix that issue, but the original model is strangely using a very old ONNX format (IR version 3 which is many years old) and fails the onnx checker. 

```python
import onnx

model_filename = 'resnet50-v1-7_quant_QDQ.onnx'
m = onnx.load(model_filename)

# original model fails this check if uncommented due to ONNX IR version 3 requiring all initializers to be inputs
# onnx.checker.check_model(m)

onnx_opset = -1
for entry in m.opset_import:
    if entry.domain == 'ai.onnx' or entry.domain == '':  # empty string == onnx domain
        onnx_opset = entry. version

for entry in m.opset_import:
    if entry.domain == 'com.ms.internal.nhwc':
        entry.version = onnx_opset

onnx.save(m, model_filename.replace('.onnx', '.updated.onnx'))
```

The fixed model will fail with this error, so that's multiple things about the model which are unexpected/incorrect.

    [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid model. Node input 'resnetv17_stage1_activation0_DequantizeLinear_token_238' is not a graph input, initializer, or output of a previous node.

**Comment by JasonMaojinsong** [comment]
>

**Comment by JasonMaojinsong** [comment]
@skottmckay   thanks for your quick reply,   here is the step of how I got this model,  
1,  download the float model from https://github.com/onnx/models/blob/main/vision/classification/resnet/model/resnet50-v1-7.onnx

2,  quantize this float model with script/example of onnxruntime quantization script at: 
https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/image_classification/cpu/run.py

3, got the quantized model and run with the onnxruntime inference engine with XNNPACK.  

could u please take a look and see if something wrong?

thanks

**Comment by wejoncy** [comment]
@JasonMaojinsong  I think `python -m onnxruntime.tools.qdq_helpers.optimize_qdq_model <model.onnx> <fixed_model.onnx>` would be still required for this model. Then you will see each `conv/add` have its own DQ/Q nodes.

**Comment by JasonMaojinsong** [comment]
@wejoncy this script still leads to another issue: python -m onnxruntime.tools.qdq_helpers.optimize_qdq_model <model.onnx> <fixed_model.onnx>
![image](https://user-images.githubusercontent.com/95834241/188567283-202a654d-9151-4a69-9fd7-d392371a8957.png)

the quantized model is generated by "quantize_static" of onnxruntime quantization package.  looks it adds some additional information,

**Comment by skottmckay** [comment]
Add this after onnx.load to update the IR to v4 (which doesn't require initializers to be inputs) and to validate.

```python
m = onnx.load(model_filename)
m.ir_version = 4
onnx.checker.check_model(m)
```

After that the QDQ optimizer script should work with the updated model

**Comment by JasonMaojinsong** [comment]
@skottmckay @wejoncy many thanks, it's working now, 
1,  it make sense that the initalizer should not put in graph input, so the quantization script should update ir_version before saving the output model. 
2,  the version to domain "com.ms.internal.nhwc" has been update to 17 on the latest onnxruntime quantization package. 
![image](https://user-images.githubusercontent.com/95834241/188575106-70491b36-2d2d-453d-9ef5-211e7c626c55.png)

3,  I still don't understand why onnxruntime.tools.qdq_helpers.optimize_qdq_model can fix the issue:
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid model. Node input 'resnetv17_stage1_activation0_DequantizeLinear_token_238' is not a graph input, initializer, or output of a previous node.
![image](https://user-images.githubusercontent.com/95834241/188575975-706019d7-1f0f-432b-a38b-fcc6d4a778b3.png)
looks this node has two consumer edges.

**Comment by skottmckay** [comment]
> 2, the version to domain "com.ms.internal.nhwc" has been update to 17 on the latest onnxruntime quantization package.

That just means ORT is aware of ONNX opset 17 as the internal domain is 1:1 with the ONNX op schemas with the only difference being they use NHWC layout instead of NCHW. The opset import for the internal domain should not need to be manually set in the onnx model. It MUST match the imported ONNX opset as we convert an ONNX operator to the internal domain with the assumption there are no opset differences to handle.

The QDQ handling in ORT assumes a DQ node will not have 2 output edges as it makes the processing a lot more complicated. The script will duplicate the DQ node so this doesn't happen. There's no strict definition of what a QDQ format model should conform to, so things like this can occur. We can look at moving the logic in the script into an optimizer that runs as part of ORT so the extra step isn't required.

**Comment by JasonMaojinsong** [comment]
many thanks,  it's clear to me now.  👍 :)
