### ISSUE TITLE
onnxruntime doesn't contain ReLU

### ISSUE THREAD

**Issue by NicolasNierenbergPersyst** [microsoft/onnxruntime#12869]
When I run the following on my Mac using the nightly PyTorch build I get the error that ReLU is not implemented.  My onnxruntime says it is 1.7.2 which I realize is not the latest, but I have tried installing the dependencies directly and still I only get that version.  Just a few days ago I was not getting this error.

```
import torch
from torch import nn
import onnx
import onnxruntime

y = torch.randn(1)
model = nn.ReLU()
torch.onnx.export(model, y, 'test.onnx', export_params=True)
onnx_model = onnx.load('test.onnx')
onnx.checker.check_model(onnx_model)
ort_session = onnxruntime.InferenceSession('test.onnx')
```

**Comment by skottmckay** [comment]
ORT has had Relu from the beginning with support for float and double. int8 and int32 were added in ONNX opset 14. 

I tried your script and it ran without issue with ORT 1.12.1 and torch 1.11.0.

**Comment by NicolasNierenbergPersyst** [comment]
Ok, agreed I can run it successfully with the latest version of ORT.
