### ISSUE TITLE
Extremely Slow Download Speed of Test Data in China

### ISSUE THREAD

**Issue by xkszltl** [microsoft/onnxruntime#1286]
**Describe the bug**

I'm trying to download `https://onnxruntimetestdata.blob.core.windows.net/models/20190419.zip` for test but it's very hard.
I tried a few machines in US and Asia, outside Microsoft.
Most of them only reached 3 Mbps, the fastest one got ~12 Mbps.

Note that Internet bandwidth is not the bottleneck.
All of them has 100-1000 Mbps capacity available.

**Comment by raymondxyang** [comment]
It's stored on azure central us and ncus data center.. and we use aria2c and curl for accessing it

**Comment by xkszltl** [comment]
If I access it from SCUS Azure, it can reach ~500Mbps.
But outside Microsoft network it's barely reachable (Will take ridiculously long, and with high chance of non-resumable connection lost)
I wonder if it's better to put it simply as the Release assert on GitHub.
They got nice CDN.

**Comment by raymondxyang** [comment]
@snnn do we have any security concern on hosting the test data on outside site?

**Comment by snnn** [comment]
For the files under https://onnxruntimetestdata.blob.core.windows.net/models, no. They are public.
However, our ci build won't fetch the data from github.  It's like, when you live in the U.S., you won't go to Microsoft's Beijing cafeteria for lunch.

**Comment by xkszltl** [comment]
Haha but that makes it less friendly to the open source community.
What I'm proposing is more like `wget azure` in CI file only + `wget -c github` in general script, which means the second step basically does nothing in your CI.

**Comment by raymondxyang** [comment]
Does our subscription include Azure's China region?

**Comment by snnn** [comment]
No. China is totally different. For example, your .S. Amazon account can't be used in Amazon China.

**Comment by faxu** [comment]
The data set is quite large and probably not well suited to be hosted in github. The azure blob store is publicly accessible and @raymondxyang will update the documentation to include the link. If this is only a non-blocking inconvenience for users physically located in China, then this is a low priority fix for us at this time. This should mostly be a one-time cost to download the data for anyone that needs it.

**Comment by xkszltl** [comment]
@faxu It is not only China. I also tried machines in US west coast.
Because the connection is slow and unstable, in fact I wasn't able to download it at all, and end up using an Azure VM to download first and relay the traffic out via rsync.

Also, correct me if I'm wrong but I don't think github has limit for release asset size. I'm not talking about check it into the git.

**Comment by snnn** [comment]
Hi @xkszltl the data is hosted in central us. I live in the west coast. I can download the data at full internet speed. If you are having connectivity issue with Azure blob storage, please feel free to contact Azure networking team. 
 
 And also, I would suggest you use the tools provided by Azure blob storage team. For example, azcopy. It has very good retry and error recovery function.

**Comment by xkszltl** [comment]
azcopy is probably a good suggestion. Thanks!

**Comment by xkszltl** [comment]
FYI I did a curl in Redmond office just now, after normal working hours so no much traffic to interfere with.
Here's the speed pattern:
![image](https://user-images.githubusercontent.com/5203025/60230847-25c33f80-984c-11e9-867a-3a8ac57d1c33.png)

Machine is connected with GE network and I can certainly reach line speed during my daily work.
