### ISSUE TITLE
parallel mode is slower than sequential mode when high concurrency

### ISSUE THREAD

**Issue by nilshinngmailcom** [microsoft/onnxruntime#12877]
why the latency of parallel mode is slower than sequential mode when high concurrency ?
my model is small, and the latency of parallel mode is faster than sequential mode when the concurrency level is 1,
but the latency of parallel mode is slower than sequential mode when concurrency level is 4

**Comment by xadupre** [comment]
Is it possible to know more about the environment you are using to experiment (which language, which processor, whick kind of model (deep learning, forest trees, ...), the size of your data, are using CPU, GPU)? Parallelisation is not always faster. It is usually when the processor has multiple cores, the model is big and the input data is big too.

**Comment by tianleiwu** [comment]
This is the reason that sequential mode is the default option. It is no slower than parallel model in majority use cases. You can open your onnx graph: In many cases, like CNN, transformers etc, the graph is sequential pattern. Parallel model won't help in such cases.

**Comment by skottmckay** [comment]
Also note that by having multiple threads for the concurrent requests and multiple threads to execute each request by using the parallel executor you're most likely creating thread contention that is hurting performance once the total number of threads exceeds the number of cores you have.
