### ISSUE TITLE
[C#] Lack a clear instruction on how to edit the MAIN tutorial page

### ISSUE THREAD

**Issue by GeorgeS2019** [microsoft/onnxruntime#12876]
<img src="https://user-images.githubusercontent.com/49812372/188856589-e3235b78-7d3d-4713-99de-3ea05fc0fc1f.png" width=400px >

Clicking this:
[Edit this page on GitHub](https://github.com/microsoft/onnxruntime/tree/gh-pages/docs/tutorials/index.md) leads to a wrong page
<img src="https://user-images.githubusercontent.com/49812372/188857156-297b1b85-9484-4ac7-9732-ca34acc95a43.png" width=400px >

There is **no clear instruction** how to edit this page to ADD/Update the recently added CSharp tutorials: [Create C# inference section and added C# BERT NLP tutorial](https://github.com/microsoft/onnxruntime/pull/12472)

**Comment by natke** [comment]
Thank you for the feedback @GeorgeS2019. This page is largely autogenerated by the tutorials than are in this section. Can you let us know how we could improve this?

**Comment by GeorgeS2019** [comment]
Hi @natke, I believe for others who are familiar with the framework behind the autogeneration is obvious.

By creating this issue, I hope this will help others who have yet to learn the framework behind the autogeneration.
