### ISSUE TITLE
[C#] Wrong link to c#: Go to API Documentation

### ISSUE THREAD

**Issue by GeorgeS2019** [microsoft/onnxruntime#12875]
There is a recent significant CSharp binding update
- [Csharp bindings for on-device training APIs](https://github.com/microsoft/onnxruntime/pull/12404)
- [[Automated]: Update C# API docs to the gh-pages branch](https://github.com/microsoft/onnxruntime/pull/12807)

![image](https://user-images.githubusercontent.com/49812372/188853985-f9d03f54-bfbf-49f2-b034-7f029397e72c.png)

Clicking [improve this doc](https://github.com/microsoft/onnxruntime/blob/main/csharp/ApiDocs/api/index.md/#L1) [Top Right corner]
leads to this [document](https://github.com/microsoft/onnxruntime/blob/main/csharp/ApiDocs/index.md): 

which has the [**first link**](https://github.com/microsoft/onnxruntime/blob/main/docs/api/csharp/api/index.html ) with following a mistake 

https://github.com/microsoft/onnxruntime/blob/main/docs/api/csharp/api/index.html <= wrong
https://onnxruntime.ai/docs/api/csharp/api/  <= right

**Comment by cassiebreviu** [comment]
This is a dynamic link which works from the page where it will be clicked [here](https://onnxruntime.ai/docs/api/csharp/), not from the github edit page. I could change it to a static link "https://onnxruntime.ai/docs/api/csharp/api/index.html" if you think it is important to be able to click it from GitHub. The GitHub page is meant for editing not navigating.

**Comment by GeorgeS2019** [comment]
@cassiebreviu  This is a trivial feedback.  

After I have gone through it, now I have a better overview. The next person will have to go through what I did.  Potentially a **Readme.md** file to explain the static link in the same folder as the **index.md** 
 => https://github.com/microsoft/onnxruntime/blob/main/csharp/ApiDocs/index.md
