### ISSUE TITLE
[Build]  Failed to build onnxruntime for Android

### ISSUE THREAD

**Issue by Archie-eng** [microsoft/onnxruntime#12886]
### Describe the issue

I use the below command to build onnxruntime for Android, and it builds successful.
```
build.bat --android --android_sdk_path D:\Android_SDK --android_ndk_path D:\Android_SDK\ndk\23.0.7599858 --android_abi arm64-v8a --android_api 30 --cmake_generator Ninja   --build_java
```
When I add the argument  "--include_ops_by_config", it failed to build with error as below.
```
build.bat --android --android_sdk_path D:\Android_SDK --android_ndk_path D:\Android_SDK\ndk\23.0.7599858 --android_abi arm64-v8a --android_api 30 --cmake_generator Ninja   --build_java --include_ops_by_config F:\required_operators.config  --enable_reduced_operator_type_support  --skip_tests
```
Error:
-- Java Build is enabled                                                                                                                                                         -- Using gradle: C:/Gradle/gradle-6.8.3/bin/gradle                                                                                                                               -- GRADLE_ARGS: --console=plain;cmakeBuild;-DcmakeBuildDir=F:/onnx/onnxruntime/build/Windows/Debug;--no-daemon                                                                   -- Running Java tests                                                                                                                                                            -- Configuring done                                                                                                                                                              -- Generating done                                                                                                                                                               -- Build files have been written to: F:/onnx/onnxruntime/build/Windows/Debug                                                                                                     2022-09-08 10:46:12,428 util.run [DEBUG] - Subprocess completed. Return code: 0                                                                                                  2022-09-08 10:46:12,429 build [INFO] - Building targets for Debug configuration                                                                                                  2022-09-08 10:46:12,429 util.run [INFO] - Running subprocess in 'F:\onnx\onnxruntime'                                                                                              'C:\Program Files\CMake\bin\cmake.EXE' --build 'F:\onnx\onnxruntime\\build\Windows\Debug' --config Debug                                                                       [0/2] Re-checking globbed directories...                                                                                                                                         [22/416] Building CXX object CMakeFiles/onnxruntime_shared_lib_test.dir/F_/onnx/onnxruntime/onnxruntime/test/shared_lib/test_inference.cc.o                                      FAILED: CMakeFiles/onnxruntime_shared_lib_test.dir/F_/onnx/onnxruntime/onnxruntime/test/shared_lib/test_inference.cc.o                                                           D:\Android_SDK\ndk\23.0.7599858\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android30 --sysroot=D:/Android_SDK/ndk/23.0.7599858/toolchains/llvm/prebuilt/windows-x86_64/sysroot -DCPUINFO_SUPPORTED_PLATFORM=1 -DEIGEN_MPL2_ONLY -DEIGEN_USE_THREADS -DNSYNC_ATOMIC_CPP11 -DONNX_ML=1 -DONNX_NAMESPACE=onnx -DONNX_USE_LITE_PROTO=1 -DPLATFORM_POSIX -DREDUCED_OPS_BUILD -DUSE_DUMMY_EXA_DEMANGLE=1 -DUSE_ONNXRUNTIME_DLL -IF:/onnx/onnxruntime/include/onnxruntime -IF:/onnx/onnxruntime/include/onnxruntime/core/session -IF:/onnx/onnxruntime/cmake/external/nsync/public -IF:/onnx/onnxruntime/build/Windows/Debug -IF:/onnx/onnxruntime/onnxruntime -IF:/onnx/onnxruntime/build/Windows/Debug/_deps/abseil_cpp-src -IF:/onnx/onnxruntime/cmake/external/date/include -IF:/onnx/onnxruntime/cmake/external/flatbuffers/include -IF:/onnx/onnxruntime/onnxruntime/test/util/include -IF:/onnx/onnxruntime/cmake/external/SafeInt -IF:/onnx/onnxruntime/cmake/external/mp11/include -IF:/onnx/onnxruntime/cmake/external/pytorch_cpuinfo/include -IF:/onnx/onnxruntime/build/Windows/Debug/external/onnx -IF:/onnx/onnxruntime/cmake/external/protobuf/src -isystem F:/onnx/onnxruntime/cmake/external/googletest/googletest/include -isystem F:/onnx/onnxruntime/cmake/external/googletest/googletest -isystem F:/onnx/onnxruntime/cmake/external/googletest/googlemock/include -isystem F:/onnx/onnxruntime/cmake/external/googletest/googlemock -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions -frtti -stdlib=libc++ -ffunction-sections -fdata-sections -DCPUINFO_SUPPORTED -Wno-deprecated -g  -fno-limit-debug-info -DGSL_THROW_ON_CONTRACT_VIOLATION -fPIE -Wall -Wextra -Wno-unused-parameter -Werror -Wno-deprecated-copy -Wno-tautological-pointer-compare -Wno-ambiguous-reversed-operator -Wno-deprecated-anon-enum-enum-conversion -Wno-undefined-var-template -Wno-error=sign-compare -Wno-error=uninitialized -pthread -std=gnu++17 -MD -MT CMakeFiles/onnxruntime_shared_lib_test.dir/F_/onnx/onnxruntime/onnxruntime/test/shared_lib/test_inference.cc.o -MF CMakeFiles\onnxruntime_shared_lib_test.dir\F_\onnx\onnxruntime\onnxruntime\test\shared_lib\test_inference.cc.o.d -o CMakeFiles/onnxruntime_shared_lib_test.dir/F_/onnx/onnxruntime/onnxruntime/test/shared_lib/test_inference.cc.o -c F:/onnx/onnxruntime/onnxruntime/test/shared_lib/test_inference.cc              F:/onnx/onnxruntime/onnxruntime/test/shared_lib/test_inference.cc:185:28: error: unused variable 'OPTIONAL_TYPE_GH_11717_MODEL' [-Werror,-Wunused-const-variable]                static constexpr PATH_TYPE OPTIONAL_TYPE_GH_11717_MODEL = TSTR("testdata/gh_issue_11717.onnx");                                                                                                             ^                                                                                                                                                     1 error generated.             

File: required_operators.config
```
# Generated from model/s in F:\code\onnx\conversion\onnx_models\demo
ai.onnx;13;ArgMax,Cast,Concat,ReduceMean
ai.onnx;14;Reshape
ai.onnx.ml;1;ArrayFeatureExtractor,TreeEnsembleClassifier,ZipMap
 ```

### Target platform

Android

### Build script

build.bat --android --android_sdk_path D:\Android_SDK --android_ndk_path D:\Android_SDK\ndk\23.0.7599858 --android_abi arm64-v8a --android_api 30 --cmake_generator Ninja   --build_java --include_ops_by_config F:\required_operators.config  --enable_reduced_operator_type_support  --skip_tests

### Error / output

F:/onnx/onnxruntime/onnxruntime/test/shared_lib/test_inference.cc:185:28: error: unused variable 'OPTIONAL_TYPE_GH_11717_MODEL' [-Werror,-Wunused-const-variable]                static constexpr PATH_TYPE OPTIONAL_TYPE_GH_11717_MODEL = TSTR("testdata/gh_issue_11717.onnx");                                                                                                             ^                                                                                                                                                     1 error generated.                                                           

### Visual Studio Version

2019

**Comment by skottmckay** [comment]
Needs a tweak. We are usually doing a minimal build with reduced ops so that test file is excluded and the issue wasn't noticed.

Short term you can skip building the unit tests in a reduced ops build. Will improve build times as well. Add 
`--cmake_extra_defines onnxruntime_BUILD_UNIT_TESTS=OFF`

**Comment by snnn** [comment]
I think it is related to #11839

**Comment by Archie-eng** [comment]
> build.bat --android --android_sdk_path D:\Android_SDK --android_ndk_path D:\Android_SDK\ndk\23.0.7599858 --android_abi arm64-v8a --android_api 30 --cmake_generator Ninja   --build_java --include_ops_by_config F:\required_operators.config  --enable_reduced_operator_type_support  --skip_tests

Add this argument, it builds successful. Thanks.
