### ISSUE TITLE
Optimize and save an onnx model that's >= 2GB

### ISSUE THREAD

**Issue by CanyonWind** [microsoft/onnxruntime#12882]
### Describe the issue

When doing ORT's graph optimization through different `graph_optimization_level`s, we can save the optimized graph later when specifying the `optimized_model_filepath`. But this fails when the original onnx model is `>= 2GB`. Is there any way to circumvent the limitation and save the `>= 2GB`  optimized model with external memory?

```
[libprotobuf ERROR /home/username/onnxruntime_self_parser/cmake/external/protobuf/src/google/protobuf/message_lite.cc:410] onnx.ModelProto exceeded maximum protobuf size of 2GB: 3219536219
Traceback (most recent call last):
  File "src/deploy/ort_inference.py", line 60, in <module>
    inference(
  File "src/deploy/ort_inference.py", line 42, in inference
    sess = ort.InferenceSession(model_path, sess_options, providers=eps)
  File "/home/username/Model/ort_trt_parser_env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/username/Model/ort_trt_parser_env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Protobuf serialization failed.
```

### To reproduce

optimize and save any model larger than 2GB will verify this.

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.13.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
I don't believe we currently have an option to write initializers out as external data when saving the optimized model. 

@pranavsharma is supporting that on the backlog at all?

**Comment by pranavsharma** [comment]
@RyanUnderhill - can you take a look when you've some time? Thanks.

**Comment by josephrocca** [comment]
Related:

* https://github.com/microsoft/onnxruntime/issues/14213
* https://github.com/microsoft/onnxruntime/issues/14697

**Comment by kkang-groq** [comment]
Is there any update on this issue? Thanks!

**Comment by bxing-groq** [comment]
https://github.com/microsoft/onnxruntime/pull/14244#issuecomment-1379655474

Here's my previous unsuccessful attempt, and we will keep on pushing in the near future. I think it's close to the finish line - if anyone wants to carry it to the finish line please feel free to do so.

**Comment by lordrebel** [comment]
is there any updates for large model (>=2GB) deserializing and inference?

**Comment by pranavsharma** [comment]
@satyajandhyala will start working on this today.

**Comment by pranavsharma** [comment]
PR that addresses this has been merged: https://github.com/microsoft/onnxruntime/pull/16440
