### ISSUE TITLE
[Performance] parallel mode is slower than sequential mode when high concurrency

### ISSUE THREAD

**Issue by nilshinngmailcom** [microsoft/onnxruntime#12891]
### Describe the issue

why the latency of parallel mode is slower than sequential mode when high concurrency ?
my model is small, and the latency of parallel mode is faster than sequential mode when the concurrency level is 1,
but the latency of parallel mode is slower than sequential mode when concurrency level is 4.

the core of cpu is 64, and parameter of IntraOpThreadPool is 8, parameter of InterOpThreadPool is 8, the model like wide&deep, the batch of request is only one.
parallel mode: latency is 2ms when  the concurrency level is 1, latency is 10ms  the concurrency level is 4,
sequential model: latency is 5ms when  the concurrency level is 1, latency is 8ms  the concurrency level is 4,

I found mem_pattern and mem_reuse is only support by ExecutionMode::ORT_SEQUENTIAL;
I enable mem_pattern and mem_reuse on ExecutionMode::ORT_PARALLEL, the latency is a bit quick, but slower than sequential mode when high concurrency. I don't know the other config can boost performance parallel-mode.

### To reproduce

Wide & Deep Learning for Recommender Systems
https://arxiv.org/abs/1606.07792
My model like wide&deep.

### Platform

Linux

### OS Version

centos7

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

rel-1.10.0

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

### Is this a quantized model?

No

**Comment by xadupre** [comment]
When you say the concurrency level is 4, you mean both InterOpThreadPool and IntraOpThreadPool  are set to 4? Did you measure the latency when IntraOpThreadPool is 32 or 64 and InterOpThreadPool is 1? IntraOp parallelization is usually more efficient than InterOp parallelization. InterOp parallelization is usually used when the graph does not have too many operators with a parallelized implementation which is rarely the case in deep learning.

**Comment by skottmckay** [comment]
As per the responses in #12877 in concurrent scenarios we'd recommend using the sequential executor. Based on your own testing, you get better performance with that option.

What is the problem you're trying to solve? Do you think the performance with the recommended sequential executor is problematic? Or do you have some specific latency target that you think should be achievable but due to an issue with ORT isn't?

There are many factors that affect performance, and the model itself is significant. If you want to fully understand performance for your specific model on your hardware you might want to do some profiling including, looking at thread contention.

**Comment by nilshinngmailcom** [comment]
First, my model is too small, the latency is strict and the QPS is a bit more.
The qps is 1, parallel mode is quicker than sequential mode, but the qps is 4 or more, sequential mode is quicker than parallel mode. I prefer to parallel mode on my scene.
%usr      %system    %guest    %CPU
514.00   24.00          0.00         538.00  : parallel mode
724.00   37.00          0.00         761.00   : sequential mode
At present, I found the cpu utile of parallel mode is less than sequential mode; I guess some mutex wait more time, but I can't found where it is.

**Comment by skottmckay** [comment]
>  I prefer to parallel mode on my scene.

Sorry I don't understand this. Why do you prefer parallel mode if sequential mode works better for your scenario? Concurrency and the intra-op threads provide parallelization as well.

**Comment by nilshinngmailcom** [comment]
> Sorry I don't understand this. Why do you prefer parallel mode if sequential mode works better for your scenario? Concurrency and the intra-op threads provide parallelization as well.

When qps is 1, parallel mode is quicker than sequential mode

**Comment by skottmckay** [comment]
I don't think there's a perfect solution if you're trying to optimize for both sequential (QPS==1) and concurrent execution. Typically it's one or the other.

You didn't say what QPS your CPU utilization numbers are for, or what latency you see for parallel vs sequential at that rate. There will be more mutexes involved when using the parallel executor. You can look for the usage of OrtMutex in https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/framework/parallel_executor.cc

**Comment by nilshinngmailcom** [comment]
> I don't think there's a perfect solution if you're trying to optimize for both sequential (QPS==1) and concurrent execution. Typically it's one or the other.
> 
> You didn't say what QPS your CPU utilization numbers are for, or what latency you see for parallel vs sequential at that rate. There will be more mutexes involved when using the parallel executor. You can look for the usage of OrtMutex in https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/framework/parallel_executor.cc

I found there is a function named ReleaseNodeMLValues in SequentialExecutor::Execute, but not in ParallelExecutor::Execute. If I delete the function of ReleaseNodeMLValues in SequentialExecutor::Execute, the latency of SequentialExecutor is equal with ParallelExecutor when QPS == 4.
Why ReleaseNodeMLValues is not in ParallelExecutor::Execute?

**Comment by wschin** [comment]
> 

ReleaseNodeMLValues release used tensors according to a static graph execution plan. If there are multiple threads running the same graph, we need some mutexes to guard access to those values and it will cause performance problems.

**Comment by nilshinngmailcom** [comment]
> Calling ReleaseNodeMLValues helps reducing peak memory in SequentialExecutor.

But I don't know why removing ReleaseNodeMLValues can increase the latency in SequentialExecutor?

**Comment by wschin** [comment]
ReleaseNodeMLValues is executed after every op (search for its name in sequential_executor.cc). If your model is small and op doesn't have much computation, the time spending on ReleaseNodeMLValues will be more significant than that in big models.

**Comment by wschin** [comment]
Please let me close this issue. @nilshinngmailcom, it will require a lot of time to figure out the reasons behind the observed phenomenon and I think it's already beyond the scope of "issue" and more like a "study". I'd suggest to just stay with the fastest configuration you have tried. If you still feel uncomfortable or have an efficient way going forward, please open it again.
