### ISSUE TITLE
[Mobile] There is native memory leak when running ortSession.run() for Android 

### ISSUE THREAD

**Issue by Archie-eng** [microsoft/onnxruntime#12895]
### Describe the issue

System information

OS Platform and Distribution: Android S
ONNX Runtime installed from: source
ONNX Runtime version:  [Craigacp](https://github.com/Craigacp/onnxruntime/tree/jni-util-refactor)    15a104400 (HEAD -> jni-util-refactor, origin/jni-util-refactor) Make the strings const.
To Reproduce

Start to run six models periodly(10 seconds).
Attach the ONNX model to the issue (where applicable) to expedite investigation.
Expected behavior
There is no memory leak.

Please refer to  OnnxRuntime crashed when running ortSession.run() for Android #12679

### To reproduce

Demo：https://1drv.ms/u/s!AlIiJbF2ZUwIcE3FxCoMVZQgAP0?e=fX9HbY
1. build a custom onnxruntime for Android with  [Craigacp](https://github.com/Craigacp/onnxruntime/tree/jni-util-refactor)  
2. import the aar file to Demo
3. run demo and clieck the first button.

### Platform

Android

### OS Version

Android S

### ONNX Runtime Installation

Built from Source

### Compiler Version (if 'Built from Source')

15a104400 (HEAD -> jni-util-refactor, origin/jni-util-refactor) 

### ONNX Runtime Version or Commit ID

15a104400 (HEAD -> jni-util-refactor, origin/jni-util-refactor) 

### ONNX Runtime API

Java/Kotlin

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by Craigacp** [comment]
The analyze method in your example code doesn't close any of the tensors or result objects. Those objects must be closed in Java to release the native memory. Similarly the session object must also be closed to release the memory associated with it.
