### ISSUE TITLE
change the ukernel of XNNPACK EP

### ISSUE THREAD

**Issue by JasonMaojinsong** [microsoft/onnxruntime#12905]
### Describe the issue

thanks for the great work on XNNPACK EP,  is there any document or simple introduction on how to change the ukernel of XNNPACK,  maybe for optimal performance or user defined ukernel. 
thanks

### To reproduce

normal

### Urgency

normal

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

latest

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Other / Unknown

### Execution Provider Library Version

XNNPACK

**Comment by skottmckay** [comment]
Not sure what you mean by 'ukernel'. Can you elaborate or maybe provide a specific example?

**Comment by JasonMaojinsong** [comment]
@skottmckay ,  sorry, i didn't describe it clearly,  
for example, I am running resnet50 which mapping one conv operation (qlinearconv) to micro kernel of XNNPACK : 
xnn_qs8_igemm_minmax_fp32_ukernel_4x16c8__avx512skx (),  

looks the CreateXnnpackKernel() on conv.cc of xnnpack EP setup this "ukernel",  which calls xnn_create_convolution2d_nhwc_qs8() of XNNPACK library internally.   

as there are lots of kernels in xnnpack qs8-igemm,  https://github.com/google/XNNPACK/tree/master/src/qs8-igemm/gen
xnn_qs8_igemm_minmax_fp32_ukernel_4x16c8__avx512skx () is determined by XNNPACK internally or any options in onnxruntime XNNPACK EP for users to change?

thanks

**Comment by skottmckay** [comment]
I would expect a higher-level function like xnn_create_convolution2d_nhwc_qs8 will utilize the appropriate low-level kernels that plug in device and usage specific things like an avx512 specific kernel. It most likely isn't practical for ORT to try and directly use the low-level device specific kernels. 

I think that equates to ORT only calling functions in https://github.com/google/XNNPACK/blob/master/include/xnnpack.h.

Do you have a production use-case involving a specific device where the model has operators that would benefit from adding them to the xnnpack EP? That would most likely involve any model running on 32-bit ARM or an fp32 model running on 64-bit ARM. For other devices the internal ORT MLAS kernels would provide similar capabilities without having to use xnnpack.

**Comment by JasonMaojinsong** [comment]
> I would expect a higher-level function like xnn_create_convolution2d_nhwc_qs8 will utilize the appropriate low-level kernels that plug in device and usage specific things like an avx512 specific kernel. It most likely isn't practical for ORT to try and directly use the low-level device specific kernels.
> 
> I think that equates to ORT only calling functions in https://github.com/google/XNNPACK/blob/master/include/xnnpack.h.
> 
looks it's determined by XNNPACK internally.  

> Do you have a production use-case involving a specific device where the model has operators that would benefit from adding them to the xnnpack EP? That would most likely involve any model running on 32-bit ARM or an fp32 model running on 64-bit ARM. For other devices the internal ORT MLAS kernels would provide similar capabilities without having to use xnnpack.

not any specific device requirement,  I am just curious about the requantization flow between different method,  Google involves that they use XNNPACK to replace QNNPACK with higher precision for fixed point inference,  
I compared the final output confidence/score of resnet50 for one input image between CPUexecution_provider and CPU+XNNPACK execution provider with int8 quantized QDQ model.   which shows that XNNPACK can provide similar results compared to CPU execution provider(MLAS).  I am not sure if MLAS implement QDQgroup in fixedpoint inference or float point inference.

thanks
