### ISSUE TITLE
[Documentation] increase Mask RCNN  Tutorials

### ISSUE THREAD

**Issue by monkeycc** [microsoft/onnxruntime#12912]
### Describe the documentation issue

[Documentation] increase Mask RCNN  Tutorials

**Comment by skottmckay** [comment]
Increase in what way? Is there a specific gap in the documentation that we can fill?

**Comment by natke** [comment]
Hi @monkeycc Can you provide us with the type of information or questions you would like answered in these requested tutorials?

**Comment by natke** [comment]
Closing this issue. Please re-open it, or open a new issue if you have new information to share
