### ISSUE TITLE
[Performance] Relative time gains from dynamic quantization decrease over the number of CPU cores used (CPUExecutionProvider)

### ISSUE THREAD

**Issue by fxmarty** [microsoft/onnxruntime#12925]
### Describe the issue

As seen below, relative gains from quantization seem to decrease with the number of physical CPU cores used. I would be curious to know why.

A second issue is that quantizing Conv (passing as well with `weights_dtype=QUInt8`) layers actually hurt time performances, this could be related to https://github.com/microsoft/onnxruntime/issues/12854 and is an other issue than the one addressed here.

![ncores_c6i](https://user-images.githubusercontent.com/9808326/189612771-4327013a-d390-4a98-a30a-94c7feaa6f14.png)

### To reproduce

This was done on an AWS EC2 c6i instance, using only the physical cores 0-7.

Typically, in order to pin onnxruntime to specific CPU ids, e.g. 0-3, I do: `taskset -c 0-3 benchmark_script.py`, and set `intra_op_num_threads = 4` within the session options. In this example, we verify with `mpstat` that indeed only the requested CPU ids are used.

The full script is not reproduced here, but the main piece is here: https://github.com/huggingface/optimum/blob/9b0474973cecbf15f1ba8280e2d0f25f5e8c4021/optimum/runs_base.py#L189-L282

I use a batch size of 1, and run the benchmark for 15 seconds.

Model used: https://huggingface.co/fxmarty/levit-256-onnx

### Urgency

Not urgent

### Platform

Linux

### OS Version

Ubuntu 22.04 jammy, x86_64 Linux 5.15.0-47-generic

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Is this a quantized model?

Yes

**Comment by yufenglee** [comment]
It is expected. Let's just assume quantization can achieve 4 more times parallelism than full precision. According to [Amdahl's law](https://en.wikipedia.org/wiki/Amdahl%27s_law) and assuming the parallelism portion is 0.6, then:
- with 1 thread,  quant gets 1/(0.4 + 0.6/4) = 1.82x speedup and fp32 gets 1x speedup. Then quant/fp32 = 1.82x. It is quite similar to your case.
- with 2 threads, quant gets 1/(0.4 + 0.6/(4*2)) = 2.1x speedup and fp32 gets 1/(0.4 + 0.6/2) = 1.43x. Then quant/fp32 = 2.1/1.43  = 1.47x.
- with 4 threads, quant gets 1/(0.4 + 0.6/(4*4)) = 2.29x speedup and fp32 gets 1/(0.4 + 0.6/4) = 1.82x. Then quant/fp32 = 1.26x.

This is simple model, but it can explain why quant get less speedup with more threads. In addition, quant also introduces extra overhead(quantize and dequantize) which makes quant's parallelism portion smaller.

**Comment by yufenglee** [comment]
The computation uses fp32 with 1 thread as baseline.

**Comment by fxmarty** [comment]
@yufenglee Thanks a lot for your detailed reply, I was not familiar with Amdahl's law, very interesting! Closing then!
