### ISSUE TITLE
Big endian issue: Graph Transformation Attention Fusion tests are failing

### ISSUE THREAD

**Issue by tvkai** [microsoft/onnxruntime#12921]
### Describe the issue

Basically I am observing on AIX which is a big endian platform, following tests are failing, when onnxruntime is built from source .

1: [  FAILED  ] GraphTransformationTests.AttentionFusionInt32Test
1: [  FAILED  ] GraphTransformationTests.AttentionFusionInt64Test
1: [  FAILED  ] GraphTransformationTests.AttentionFusionFloat32Test

The underlying issue seems to be onnxruntime is adding initializers to the graph during tranfsormation of the graph.
When initializers are getting added to the graph. the initializers are containing the raw_data, according to the 
current implementation the graph should have little endian data and whenever it processes the data
UnpackTensors takes care of endianess of the machine. The issue is on a Big endian platform the data
is already in the BE and this makes graph to contain BE data instead of LE.

Below is the place where seems to be the actual issue.

In the file : onnxruntime/core/optimizer/attention_fusion.cc 
Function: MergeQkvWeights

if (data_type == ONNX_NAMESPACE::TensorProto_DataType_FLOAT) {
    const float* q_weight = q_initializer.data<float>();
    const float* k_weight = k_initializer.data<float>();
    const float* v_weight = v_initializer.data<float>();
    std::vector<float> result;
    result.reserve(gsl::narrow<size_t>(element_count));
    if (is_matmul) {
      MergeMatMulWeights<float>(q_weight, k_weight, v_weight, result, hidden_size);
    } else {
      MergeWeights<float>(q_weight, k_weight, v_weight, result, hidden_size);
    }
    initializer.set_raw_data(result.data(), gsl::narrow<size_t>(element_count) * sizeof(float)); <=== Here we are setting the raw_data using BE data when run on a Big endian platform.

Also in else  block the same issue, initializer is getting formed with BE data and this is getting added to Graph.

One way to fix this issue is ..we need do byte swapping before we set the raw_data for Big Endian platforms.
I tested the byteswapping code before we actually set the raw data and tests are working fine.

### To reproduce

Run graphtransformation on a Big Endian platform like AIX on IBM Power.

### Platform

Other / Unknown

### OS Version

AIX

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

latest

### ONNX Runtime API

C

### Architecture

IBM Power

### Execution Provider

Default CPU

**Comment by madurais** [comment]
The raw data initilaizers which are read from onnx or ort files are in LE format. They should be modified to BE on BE systems. But the initializers which are input to any node, are expected to be in LE before running inference in RunInferencing() in graph.cc as onnx code expects the data in LE. 

In above code it is Fusion test and hence the initializer raw data has to be converted to be in BE, either before merge, or after merge.

**Comment by tvkai** [comment]
@snnn @tianleiwu @skottmckay @edgchen1 can you let us know your comments on this issue.

**Comment by tianleiwu** [comment]
@tvkai. Since you have a fix, could you please submit a pull request?

@snnn, could we add a build pipeline on Big Endian platform?  We can run occasionally (like before each release) to avoid similar issue.

**Comment by tvkai** [comment]
@tianleiwu, @snnn thanks a lot for giving your view on this issue, actually when we are testing on AIX, we are observing
multiple other places in the code which are adding initializers to the graph with raw_data.   We may need to fix in all those places where the byte swapping is needed.

Basically following places where the initializers are getting added :

  1. onnxruntime/core/optimizer/attention_fusion.cc
    
      initializer is getting added to the graph in the function MergeQkvWeights()

2. onnxruntime/core/optimizer/constant_folding.cc

shape_constant initializer is getting added to the graph in the function ConstantFoldShapeNode().

3. onnxruntime/core/optimizer/embed_layer_norm_fusion.cc 

initializer is getting added to the graph in the function ExtractEmbedding() 

4. onnxruntime/core/optimizer/transpose_optimizer/transpose_optimizer.c

Initializer is getting added to the graph .

5. onnxruntime/core/optimizer/transpose_optimizer/optimizer_api_impl.cc

ApiGraph::AddInitializer is getting added to the graph


Above are the actual core runtime areas, similar to this there are some places the in the test folder as well.
We may need a common way to convert and add the initializers to the graph.

To avoid future misses we might need a better way to handle the big endian platform support.

One approach  to handle this is probably for big endian systems convert the Graph’s raw_data to Big Endian 
values when we load them from a model file and existing UnpackTensors can probably skip the conversion 
( skip ReadLittleEndian()) But one issue with this approach is RunInferencing() 
( schema->GetTypeAndShapeInferenceFunction()(*this) ) code that invokes the ONNX name space routines 
which always expects raw data to be in Little Endian Format. However the advantage with this approach in 
onnxruntime is less number of changes all over the code and in future we may not miss any of such above 
places.

**Comment by tvkai** [comment]
@snnn @tianleiwu @skottmckay @edgchen1 any suggestions here ?.

**Comment by madurais** [comment]
We tried the above approach mentioned by @tvkai ie) convert the Graph’s raw_data to Big Endian
values when we load them from a model file and existing UnpackTensors can probably skip the conversion
( skip ReadLittleEndian()). We also changed the code to convert the input initializers for a node back to Little Endian before calling RunInferencing(), so that Input initializers are in Little Endian as expected by onnx code. 

We could see all onnxruntime_test_all test suits are passing.

**Comment by skottmckay** [comment]
@madurais are you able to create a PR with the changes so they can be reviewed?

**Comment by tvkai** [comment]
@skottmckay @tianleiwu @snnn @edgchen1 

We tried both approaches on latest main.

1. Whenever we are setting raw_data in the graph, convert the data to Big endian on Big endian platform. We identified all the potential places ( along with core, test code as well ) for this change. We see all tests ( c & c++ ) are passing.
2.  The other approach of converting the Graph's raw_data to Big endian values when we load them from a model file and existing unpack tensors can skip the conversion.  But we are observing one test 
( AttentionTest.Attention_Mask1D_Fp32_B2_S64 ) failure.   

Any suggestions on which approach we should be focusing on ?.

**Comment by ranjitshs** [comment]
we can raise PR for both approaches for review.

**Comment by ranjitshs** [comment]
@tianleiwu 
Thanks for the reply and suggestion. 
1.  I am not able to find C/C++ API using which I can save the model to disk . Could you please guide and tell us the reference for API usage ?

2. Regarding AttentionTest.Attention_Mask1D_Fp32_B2_S64, I have modified the  tolerance threshold  from 0.002 to 0.005. Using this value also, it's failing.

With 0.002f, 27834 entries of  were mismatched , but
with 0.005f , 27337 entries are mismatching. 
Total entires in output array is 98304.

**Comment by tianleiwu** [comment]
> 1. I am not able to find C/C++ API using which I can save the model to disk . Could you please guide and tell us the reference for API usage ?
> 2. Regarding AttentionTest.Attention_Mask1D_Fp32_B2_S64, I have modified the  tolerance threshold  from 0.002 to 0.005. Using this value also, it's failing.

@ranjitshs, 

1.
An example of C++ API (there is another example for C API in the page):
https://onnxruntime.ai/docs/performance/model-optimizations/graph-optimizations.html#c-api-example-2

2. Could you try change one line of the test code of Attention_Mask1D_Fp32_B2_S64 from
```
mask_index_data.push_back(i == 0 ? sequence_length : (sequence_length / 2));
```
to
```
mask_index_data.push_back(sequence_length);
```
That could make the result more deterministic.

**Comment by ranjitshs** [comment]
@tianleiwu 
Thanks for link and code change suggestion

1.  I am able to save the optimized model using SetOptimizedModelFilePath() and reload it properly.

2. The  Attention_Mask1D_Fp32_B2_S64 test is also passing now with the tolerance threshold  value 0.006 , along with the above suggested change 'mask_index_data.push_back(sequence_length)'.   So to make it pass in AIX , I will put these two change in #ifdef flag.

We are trying to evaluate performance of the two approaches .

**Comment by ranjitshs** [comment]
@skottmckay @tianleiwu @snnn @edgchen1
For enabling AIX and 2nd approach of this issue, there are around **28 changed files with 413 additions and 53 deletions.**
As per PR guide-line, changes are big , So could you suggest the better way to raise PR
or is it fine to raise these changes in single PR.

**Comment by tianleiwu** [comment]
@ranjitshs, please use one PR for one approach (or you can choose one approach based on your judgement). It's fine for big changes. Thanks.

**Comment by ranjitshs** [comment]
@skottmckay @tianleiwu @snnn @edgchen1
Based on our (@tvkai , @ranjitshs ) understanding , we are going ahead with approach 1.  We have designed a wrapper utility API SetRawDataInTensorProto for handling big-endian issue  and replaced with this wrapper function wherever onnxrunime is setting the raw data in tensor proto. Changes are in https://github.com/microsoft/onnxruntime/pull/21133  along with enablement for AIX.
Please have a look and suggest if any better approach for our changes.

**Comment by ranjitshs** [comment]
@skottmckay @tianleiwu @snnn @edgchen1
Hi All, 
May I know the next step/process on this issue.How we will take if forward further. Please let me know.

**Comment by snnn** [comment]
@yufenglee, the PR needs your review.

**Comment by tianleiwu** [comment]
The main challenge is to add an Azure CI pipeline that could test big endian. Otherwise, the code is not validated, and we cannot prevent regression in the future. 

One possible way to run docker like https://til.simonwillison.net/docker/emulate-s390x-with-qemu. That might need some additional change to enable such test pipeline.

**Comment by ranjitshs** [comment]
@tianleiwu 
is it possible to integrate AIX OS in the Azure CI pipeline ?

**Comment by tianleiwu** [comment]
@ranjitshs, Since we do no have AIX in CI pipeline, it has to use QEMu. I suggest to try some docker like https://github.com/WilliamHeaven/docker-aix to see whether it could work. @mszhanyi, could you help setup a pipeline?

**Comment by ranjitshs** [comment]
@tianleiwu 
So if we provide a dedicated AIX System for CI activity, is it possible to integrate this system under CI pipeline ?

Also, may I know when is next release ?

**Comment by tianleiwu** [comment]
@ranjitshs, I have no experience to setup such CI pipeline, and there is little information in web for github CI using AIX.

Even without integrating to CI pipeline, it is easy to schedule daily build by yourself to make sure the main branch is good for AIX build. That could make sure build issue is found and resolved quickly.

The next release 1.19 is tentatively feature complete by July 19, release branch freeze by end of July, and release at mid of Aug.

**Comment by ranjitshs** [comment]
@tianleiwu 
Yes. We do have local CI setup which is configured to run the main branch along with AIX patches .

Can we fast track the review process ? Generally, how much time will it take to complete the review process

**Comment by ranjitshs** [comment]
Thanks @tianleiwu @snnn @liqunfu @yihonglyu @skottmckay  @edgchen1 for providing suggestion/help on this issue/PR.
We will monitor local CI setup and create issue if we see any build/tests failure in main branch.

**Comment by tvkai** [comment]
Thank you @tianleiwu @snnn @liqunfu @yihonglyu @skottmckay @edgchen1 for all the help.

**Comment by ranjitshs** [comment]
@tianleiwu 
Hi , 
I see branch 1.19.0 branch is forked.  Any idea about the release date ?

**Comment by tianleiwu** [comment]
@ranjitshs, 1.19 was released: https://github.com/microsoft/onnxruntime/releases/tag/v1.19.0

**Comment by ranjitshs** [comment]
@tianleiwu 
Thanks for info. I just noticed.
