### ISSUE TITLE
[Documentation] Missing link to AddingCustomOp.md

### ISSUE THREAD

**Issue by GeorgeS2019** [microsoft/onnxruntime#12923]
In [Custom Op Registration and Implementation](https://github.com/microsoft/onnxruntime/issues/6564)

The [link ](https://github.com/microsoft/onnxruntime/blob/main/docs/AddingCustomOp.md) to documentation on 3 ways to write Contributed Ops is wrong

The correct link should be: [Adding a new op](https://github.com/alecona/onnx_clo/blob/master/docs/AddingCustomOp.md)

**Comment by natke** [comment]
Actually the correct link is https://onnxruntime.ai/docs/reference/operators/add-custom-op.html 

I've updated the original issue too

**Comment by GeorgeS2019** [comment]
@natke

Under your leadership, we see many positive visibilities for c# => Thank you 

I will be back with more feedback.
