### ISSUE TITLE
Optimizer adds incompatible node

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#12930]
### Describe the issue

I have a model that works in 1.10 but is broken in 1.12

The optimizer adds a node that then the runtime cannot run! Previously I noticed the CPU issue #12579 but this is the related issue on CUDA as well

```text
2022-09-12 17:50:05.671400400 [E:onnxruntime:, inference_session.cc:1529 operator()] Exception during initialization: /onnxruntime_src/onnxruntime/core/optimizer/transformer_memcpy.cc:374 bool onnxruntime::TransformerMemcpyImpl::ProcessInitializers(const onnxruntime::Ker
nelRegistryManager&, const InitializedTensorSet&) status.IsOK() was false. Failed to find kernel for SimplifiedLayerNormalization(1) (node SimplifiedLayerNormalization). Op with name (SimplifiedLayerNormalization) and type (SimplifiedLayerNormalization) kernel is not sup
ported in CUDAExecutionProvider. Encountered following errors: (Found kernel for Op with name (SimplifiedLayerNormalization) and type (SimplifiedLayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). H
owever the types are incompatible. This op has been implemented only for the following types (tensor(float),), but the node in the model has the following type (tensor(float16))
Found kernel for Op with name (SimplifiedLayerNormalization) and type (SimplifiedLayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented
only for the following types (tensor(double),), but the node in the model has the following type (tensor(float16))
Found kernel for Op with name (SimplifiedLayerNormalization) and type (SimplifiedLayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented
only for the following types (tensor(float16),), but the node in the model has the following type (tensor(float))
Found kernel for Op with name (SimplifiedLayerNormalization) and type (SimplifiedLayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented
only for the following types (tensor(float),), but the node in the model has the following type (tensor(float16))
```

This model worked on 1.10 so this is a regression. Even then, optimzier should not add SimplifiedLayerNormalization if it cannot run it. For now I have to disable optimization which is not ideal

### To reproduce

```python
sess_enc = rt.InferenceSession(onnxfile_enc_optimized, providers=['CUDAExecutionProvider'])
```

### Urgency

We have a new model that needs 1.12 because of the opset 14 version, but we are now blocked

### Platform

Linux

### OS Version

18

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by skottmckay** [comment]
@iK1D does there need to be a datatype check added?

**Comment by iK1D** [comment]
> @iK1D does there need to be a datatype check added?

I guess so. We don't have FP16 impl for CPU kernel, but for CUDA, I think all the float types are supported, not sure why it still hits the error. @dashesy , could you please share a sample onnx file that can reproduce this issue? Or share the data types of all the inputs to the SimplifiedLayerNormalization node (if you have the optimized graph)?

**Comment by dashesy** [comment]
@iK1D shared the model with @skottmckay 

If CPU does not have the FP16 implementation, optimizer should not add it. The CUDA implementation did work in 1.10 
For now I am downgrading to 1.10 and re-exporting some models to avoid the need for 1.12
