### ISSUE TITLE
[Performance] .onnx Model runtime(using ORT Api) too high in C#(~30ms) but not in Python(<1ms) 

### ISSUE THREAD

**Issue by kkulkarniMS** [microsoft/onnxruntime#12937]
### Describe the issue

Hi,
I have created a C# dotnet core demo app that imports a .onnx model and provides inferences based on the features provided by the user from an HTML form. I am importing the .onnx ML model using ORT API. I am also loading an encoder.json file to convert the features taken from HTML form to convert/encode into a format that is acceptable by the model. However, this model is having a runtime of ~30ms for a single float[] input. This runtime is way too high for us. I ran the same model using Inference sessions in a python app and the model ran is 0.85ms. We want to bring down the runtime of the model in a C# app to <1ms. Please help me understand why the ORT API's session.Run(input) method is taking ~30ms to provide an inference in C# but is taking <1ms in Python. 
P.S: I am running this on my local machine and not using GPU in either apps (C# or Python)  

### To reproduce

Here is the link to my C# demo app - 
[https://microsoft-my.sharepoint.com/:f:/p/kkulkarni/Eq3J_Iy_yZ5Im-Jpr_ejmY8BQ2Pc3uNcLmwHjOuRKHSKQg?e=4MeZXX](url) 

Just download the files, open the solution in Visual Studio, install necessary nuget packages (Microsoft.ML) and run the application. An HTML form will appear in the browser. Fill out the form like attached example and hit 'Submit'. The results of the app will appear on the same page at the bottom. Checkout 'Model Run Time' result. 

![HTMLForm](https://user-images.githubusercontent.com/101832248/189775631-068e9382-6d28-4aff-b49c-6d72e20c0fbb.png)

![HTML Form Results](https://user-images.githubusercontent.com/101832248/189775688-2b87791b-23a7-433e-99f2-8ab5f1dfc99e.png)

### Urgency

We wish to decrease the runtime of the model asap(within 1 week) so that we can use the ORT Api in our prod service(by the end of Sept 2022)

### Platform

Windows

### OS Version

Windows 11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.1

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

Default CPU

### Model File

https://microsoft-my.sharepoint.com/:u:/p/kkulkarni/EWSoSEcM6LBBpKDttZzJqX4Bjv_hMYYKIjVo88S-8ylUKw?e=B88leO

### Is this a quantized model?

Unknown

**Comment by yuslepukhin** [comment]
Somehow, I cannot gain access to your C# App.

**Comment by kkulkarniMS** [comment]
What's the error you are seeing? Can you share a screenshot?

Kedar Kulkarni
Software Engineer
UX & Foundation US
***@***.******@***.***>

[Microsoft Logo]

**Comment by kkulkarniMS** [comment]
> Just to make sure I understand this right, you are measuring Onnxruntime C# API performance against Onnxruntime Python performance?

Yes 

> Also, would you like to file this issue with ML.NET first? 
I talked to Cassie Breviu and Pranav Sharma about this and Pranav mentioned I should create a github issue for this. I am not sure which team would be appropriate for this. I will contact Microsoft.ML as well.

**Comment by pranavsharma** [comment]
If you're using the ORT C# APIs directly, @yuslepukhin can help investigate. If you're using ML.NET, you're better off reaching out to them first. ML.NET uses the ORT C# APIs internally, but the inefficiencies could be at the ML.NET layer.

**Comment by skottmckay** [comment]
For one, don't create an InferenceSession for every request. Session creation is expensive. Do it once and re-use. It supports multiple requests and concurrent requests.

**Comment by skottmckay** [comment]
I added a loop calling Run with the same input, and saved the elapsed time in both milliseconds and microseconds. First call is 17ms. Subsequent calls are way less than 1ms. i.e. first call is slow, but that shouldn't be an issue as long as you re-use the InferenceSession.

<img width="172" alt="image" src="https://user-images.githubusercontent.com/979079/190032286-2e25e065-f0ef-4ba2-b73b-db6be7dc2c77.png">

**Comment by kkulkarniMS** [comment]
Yes, I tried the same after my chat with Dmitri in which the first couple of calls were expensive, but the later ones were <1ms. Thanks for the help, Dmitri and Scott. This issue can be closed.
