### ISSUE TITLE
[Build] Cannot compile 'main' branch from sources on Windows using MS VS 2022

### ISSUE THREAD

**Issue by favorart** [microsoft/onnxruntime#12957]
### Describe the issue

When I try to compile the source of 'main' branch with the command
**.\build.bat --config Debug --build_shared_lib --parallel  --cmake_generator "Visual Studio 17 2022"**

I have the next errors:

All of these errors are from project 'libprotobuf-lite'.
When I investigate the code there are no such problems, fields and methods of classes are exist and the non-static calls are inside other non-static methods.
The IntelliSense of MS VS does not find such a probles, but compiller fails

```
error C2660: 'google::protobuf::internal::ThreadSafeArena::Init': function does not take 1 arguments 
error C2065: 'kUserOwnedInitialBlock': undeclared identifier 
error C2511: 'void google::protobuf::internal::ThreadSafeArena::InitializeWithPolicy(void *,size_t,bool,google::protobuf::internal::AllocationPolicy)': overloaded member function not found in 'google::protobuf::internal::ThreadSafeArena' 
error C2660: 'google::protobuf::internal::ThreadSafeArena::Init': function does not take 1 arguments
error C2065: 'kUserOwnedInitialBlock': undeclared identifier absl_exponential_biased.vcxproj ->  error C2597: illegal reference to non-static member 'google::protobuf::internal::ThreadSafeArena::alloc_policy_' 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ThreadSafeArena::alloc_policy_' 
error C2671: 'google::protobuf::internal::ThreadSafeArena::InitializeWithPolicy': static member functions do not have 'this' pointers 
error C3536: 'sa': cannot be used before it is initialized 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ThreadSafeArena::alloc_policy_' 
error C2511: 'void google::protobuf::internal::ThreadSafeArena::Init(bool)': overloaded member function not found in 'google::protobuf::internal::ThreadSafeArena' 
error C2065: 'kRecordAllocs': undeclared identifier 
error C2065: 'kUserOwnedInitialBlock': undeclared identifier 
error C2065: 'kUserOwnedInitialBlock': undeclared identifier 
error C3861: 'ShouldRecordAlloc': identifier not found 
error C2065: 'kUserOwnedInitialBlock': undeclared identifier 
error C2660: 'google::protobuf::internal::ThreadSafeArena::Init': function doesnot take 1 arguments
error C2660: 'google::protobuf::internal::ThreadSafeArena::GetSerialArenaFast': function does not take 2 arguments 
error C2660: 'google::protobuf::internal::ThreadSafeArena::GetSerialArenaFast': function does not take 2 arguments 
error C3861: 'AddCleanupFallback': identifier not found 
error C3861: 'ShouldRecordAlloc': identifier not found 
error C3861: 'RecordAlloc': identifier not found 
error C2660: 'google::protobuf::internal::ThreadSafeArena::GetSerialArenaFast': function does not take 2 arguments 
error C3861: 'ShouldRecordAlloc': identifier not found 
error C2660: 'google::protobuf::internal::ExtensionSet::LazyMessageExtension::GetMessage': function does not take 1 arguments 
error C3861: 'RecordAlloc': identifier not found 
error C2660: 'google::protobuf::internal::ThreadSafeArena::GetSerialArenaFast': function does not take 2 arguments 
error C2660: 'google::protobuf::internal::ExtensionSet::LazyMessageExtension::SetAllocatedMessage': function does not take 1 arguments 
error C2039: 'AddCleanupFallback': is not a member of 'google::protobuf::internal::ThreadSafeArena' 
error C2660: 'google::protobuf::internal::ExtensionSet::LazyMessageExtension::UnsafeArenaSetAllocatedMessage': function does not take 1 arguments 
error C2660: 'google::protobuf::internal::ExtensionSet::LazyMessageExtension::ReleaseMessage': function does not take 1 arguments 
error C2660: 'google::protobuf::internal::ExtensionSet::LazyMessageExtension::UnsafeArenaReleaseMessage': function does not take 1 arguments 
error C3861: 'AllocPolicy': identifier not found 
error C2511: 'void google::protobuf::internal::ExtensionSet::MergeFrom(const google::protobuf::internal::ExtensionSet &)': overloaded member function not found in 'google::protobuf::internal::ExtensionSet' 
error C2352: 'google::protobuf::internal::ExtensionSet::is_large': a call of a non-static member function requires an object 
error C2668: 'google::protobuf::internal::ExtensionSet::flat_begin': ambiguous call to overloaded function 
error C2668: 'google::protobuf::internal::ExtensionSet::flat_end': ambiguous call to overloaded function 
error C2672: 'SizeOfUnion': no matching overloaded function found 
error C2660: 'google::protobuf::internal::ExtensionSet::InternalExtensionMergeFrom': function does not take 2 arguments 
error C2512: 'google::protobuf::internal::ExtensionSet::MergeFrom::<lambda_39687e8566c881e0ac4c175fe03b7b22>': no appropriate default constructor available 
error C2672: 'google::protobuf::internal::ExtensionSet::ForEach': no matching overloaded function found 
error C2511: 'void google::protobuf::internal::ExtensionSet::InternalExtensionMergeFrom(int,const google::protobuf::internal::ExtensionSet::Extension &)': overloaded member function not found in 'google::protobuf::internal::ExtensionSet' 
error C2352: 'google::protobuf::internal::ExtensionSet::MaybeNewExtension': a call of a non-static member function requires an object 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2352: 'google::protobuf::internal::ExtensionSet::SetInt32': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetInt64': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetUInt32': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetUInt64': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetFloat': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetDouble': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetBool': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetEnum': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetString': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::MaybeNewExtension': a call of a non-static member function requires an object
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2660: 'google::protobuf::internal::ExtensionSet::LazyMessageExtension::GetMessage': function does not take 1 arguments
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2511: 'void google::protobuf::internal::ExtensionSet::Swap(google::protobuf::internal::ExtensionSet *)': overloaded member function not found in 'google::protobuf::internal::ExtensionSet' 
error C2352: 'google::protobuf::internal::ExtensionSet::GetArena': a call of a non-static member function requires an object 
error C2352: 'google::protobuf::internal::ExtensionSet::InternalSwap': a call of a non-static member function requires an object 
error C2660: 'google::protobuf::internal::ExtensionSet::MergeFrom': function does not take 1 arguments
error C2671: 'google::protobuf::internal::ExtensionSet::Swap': static member functions do not have 'this' pointers 
error C2660: 'google::protobuf::internal::ExtensionSet::MergeFrom': function does not take 1 arguments
error C2352: 'google::protobuf::internal::ExtensionSet::Clear': a call of a non-static member function requires an object
error C2660: 'google::protobuf::internal::ExtensionSet::MergeFrom': function does not take 1 arguments 
error C2511: 'void google::protobuf::internal::ExtensionSet::SwapExtension(google::protobuf::internal::ExtensionSet *,int)': overloaded member function not found in 'google::protobuf::internal::ExtensionSet' 
error C2671: 'google::protobuf::internal::ExtensionSet::SwapExtension': static member functions do not have 'this' pointers 
error C2352: 'google::protobuf::internal::ExtensionSet::GetArena': a call of a non-static member function requires an object 
error C2352: 'google::protobuf::internal::ExtensionSet::UnsafeShallowSwapExtension': a call of a non-static member function requires an object 
error C2668: 'google::protobuf::internal::ExtensionSet::FindOrNull': ambiguous call to overloaded function
error C2660: 'google::protobuf::internal::ExtensionSet::InternalExtensionMergeFrom': function does not take 2 arguments
error C2352: 'google::protobuf::internal::ExtensionSet::GetArena': a call of a non-static member function requires an object 
error C2671: 'google::protobuf::internal::ExtensionSet::SwapExtension': static member functions do not have 'this' pointers 
```

I tried to change the C++ standard of 'libprotobuf-lite' project from C++14 to C++17 or latest, but it does not help.
The full compilation log is in file below:

[full-log.txt](https://github.com/microsoft/onnxruntime/files/9566123/full-log.txt)

### Target platform

Windows x64 

### Build script

.\build.bat --config Debug --build_shared_lib --parallel  --cmake_generator "Visual Studio 17 2022"

### Error / output

error C2660: 'google::protobuf::internal::ThreadSafeArena::Init': function does not take 1 arguments 
error C2065: 'kUserOwnedInitialBlock': undeclared identifier 
error C2511: 'void google::protobuf::internal::ThreadSafeArena::InitializeWithPolicy(void *,size_t,bool,google::protobuf::internal::AllocationPolicy)': overloaded member function not found in 'google::protobuf::internal::ThreadSafeArena' 
error C2660: 'google::protobuf::internal::ThreadSafeArena::Init': function does not take 1 arguments
error C2065: 'kUserOwnedInitialBlock': undeclared identifier absl_exponential_biased.vcxproj ->  error C2597: illegal reference to non-static member 'google::protobuf::internal::ThreadSafeArena::alloc_policy_' 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ThreadSafeArena::alloc_policy_' 
error C2671: 'google::protobuf::internal::ThreadSafeArena::InitializeWithPolicy': static member functions do not have 'this' pointers 
error C3536: 'sa': cannot be used before it is initialized 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ThreadSafeArena::alloc_policy_' 
error C2511: 'void google::protobuf::internal::ThreadSafeArena::Init(bool)': overloaded member function not found in 'google::protobuf::internal::ThreadSafeArena' 
error C2065: 'kRecordAllocs': undeclared identifier 
error C2065: 'kUserOwnedInitialBlock': undeclared identifier 
error C2065: 'kUserOwnedInitialBlock': undeclared identifier 
error C3861: 'ShouldRecordAlloc': identifier not found 
error C2065: 'kUserOwnedInitialBlock': undeclared identifier 
error C2660: 'google::protobuf::internal::ThreadSafeArena::Init': function doesnot take 1 arguments
error C2660: 'google::protobuf::internal::ThreadSafeArena::GetSerialArenaFast': function does not take 2 arguments 
error C2660: 'google::protobuf::internal::ThreadSafeArena::GetSerialArenaFast': function does not take 2 arguments 
error C3861: 'AddCleanupFallback': identifier not found 
error C3861: 'ShouldRecordAlloc': identifier not found 
error C3861: 'RecordAlloc': identifier not found 
error C2660: 'google::protobuf::internal::ThreadSafeArena::GetSerialArenaFast': function does not take 2 arguments 
error C3861: 'ShouldRecordAlloc': identifier not found 
error C2660: 'google::protobuf::internal::ExtensionSet::LazyMessageExtension::GetMessage': function does not take 1 arguments 
error C3861: 'RecordAlloc': identifier not found 
error C2660: 'google::protobuf::internal::ThreadSafeArena::GetSerialArenaFast': function does not take 2 arguments 
error C2660: 'google::protobuf::internal::ExtensionSet::LazyMessageExtension::SetAllocatedMessage': function does not take 1 arguments 
error C2039: 'AddCleanupFallback': is not a member of 'google::protobuf::internal::ThreadSafeArena' 
error C2660: 'google::protobuf::internal::ExtensionSet::LazyMessageExtension::UnsafeArenaSetAllocatedMessage': function does not take 1 arguments 
error C2660: 'google::protobuf::internal::ExtensionSet::LazyMessageExtension::ReleaseMessage': function does not take 1 arguments 
error C2660: 'google::protobuf::internal::ExtensionSet::LazyMessageExtension::UnsafeArenaReleaseMessage': function does not take 1 arguments 
error C3861: 'AllocPolicy': identifier not found 
error C2511: 'void google::protobuf::internal::ExtensionSet::MergeFrom(const google::protobuf::internal::ExtensionSet &)': overloaded member function not found in 'google::protobuf::internal::ExtensionSet' 
error C2352: 'google::protobuf::internal::ExtensionSet::is_large': a call of a non-static member function requires an object 
error C2668: 'google::protobuf::internal::ExtensionSet::flat_begin': ambiguous call to overloaded function 
error C2668: 'google::protobuf::internal::ExtensionSet::flat_end': ambiguous call to overloaded function 
error C2672: 'SizeOfUnion': no matching overloaded function found 
error C2668: 'google::protobuf::internal::ExtensionSet::flat_begin': ambiguous call to overloaded function 
error C2660: 'google::protobuf::internal::ExtensionSet::InternalExtensionMergeFrom': function does not take 2 arguments 
error C2512: 'google::protobuf::internal::ExtensionSet::MergeFrom::<lambda_39687e8566c881e0ac4c175fe03b7b22>': no appropriate default constructor available 
error C2672: 'google::protobuf::internal::ExtensionSet::ForEach': no matching overloaded function found 
error C2511: 'void google::protobuf::internal::ExtensionSet::InternalExtensionMergeFrom(int,const google::protobuf::internal::ExtensionSet::Extension &)': overloaded member function not found in 'google::protobuf::internal::ExtensionSet' 
error C2352: 'google::protobuf::internal::ExtensionSet::MaybeNewExtension': a call of a non-static member function requires an object 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2352: 'google::protobuf::internal::ExtensionSet::SetInt32': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetInt64': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetUInt32': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetUInt64': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetFloat': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetDouble': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetBool': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetEnum': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::SetString': a call of a non-static member function requires an object
error C2352: 'google::protobuf::internal::ExtensionSet::MaybeNewExtension': a call of a non-static member function requires an object
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2660: 'google::protobuf::internal::ExtensionSet::LazyMessageExtension::GetMessage': function does not take 1 arguments
error C2597: illegal reference to non-static member 'google::protobuf::internal::ExtensionSet::arena_' 
error C2511: 'void google::protobuf::internal::ExtensionSet::Swap(google::protobuf::internal::ExtensionSet *)': overloaded member function not found in 'google::protobuf::internal::ExtensionSet' 
error C2352: 'google::protobuf::internal::ExtensionSet::GetArena': a call of a non-static member function requires an object 
error C2352: 'google::protobuf::internal::ExtensionSet::InternalSwap': a call of a non-static member function requires an object 
error C2660: 'google::protobuf::internal::ExtensionSet::MergeFrom': function does not take 1 arguments
error C2671: 'google::protobuf::internal::ExtensionSet::Swap': static member functions do not have 'this' pointers 
error C2660: 'google::protobuf::internal::ExtensionSet::MergeFrom': function does not take 1 arguments
error C2352: 'google::protobuf::internal::ExtensionSet::Clear': a call of a non-static member function requires an object
error C2660: 'google::protobuf::internal::ExtensionSet::MergeFrom': function does not take 1 arguments 
error C2511: 'void google::protobuf::internal::ExtensionSet::SwapExtension(google::protobuf::internal::ExtensionSet *,int)': overloaded member function not found in 'google::protobuf::internal::ExtensionSet' 
error C2671: 'google::protobuf::internal::ExtensionSet::SwapExtension': static member functions do not have 'this' pointers 
error C2352: 'google::protobuf::internal::ExtensionSet::GetArena': a call of a non-static member function requires an object 
error C2352: 'google::protobuf::internal::ExtensionSet::UnsafeShallowSwapExtension': a call of a non-static member function requires an object 
error C2668: 'google::protobuf::internal::ExtensionSet::FindOrNull': ambiguous call to overloaded function
error C2660: 'google::protobuf::internal::ExtensionSet::InternalExtensionMergeFrom': function does not take 2 arguments
error C2660: 'google::protobuf::internal::ExtensionSet::InternalExtensionMergeFrom': function does not take 2 arguments
error C2660: 'google::protobuf::internal::ExtensionSet::InternalExtensionMergeFrom': function does not take 2 arguments
error C2660: 'google::protobuf::internal::ExtensionSet::InternalExtensionMergeFrom': function does not take 2 arguments
error C2660: 'google::protobuf::internal::ExtensionSet::InternalExtensionMergeFrom': function does not take 2 arguments
error C2352: 'google::protobuf::internal::ExtensionSet::GetArena': a call of a non-static member function requires an object 
error C2671: 'google::protobuf::internal::ExtensionSet::SwapExtension': static member functions do not have 'this' pointers 

### Visual Studio Version

MS VS 2022

### GCC / Compiler Version

--

**Comment by wschin** [comment]
I just build ORT from source on VS2022. Here is my setup. All commands were run under `Developer PowerShell for VS 2022` .
1. Install VS2022
2. Install Python
3. Install CUDA
4. Download CUDNN
5. Build with ` .\build.bat --config RelWithDebInfo --build_shared_lib --parallel --enable_training --cmake_generator "Visual Studio 17 2022" --use_cuda --cudnn_home "download\cudnn-windows-x86_64-8.4.1.50_cuda11.6-archive" --cuda_home "NVIDIA GPU Computing Toolkit\CUDA\v11.7" --cuda_version=11.7

**Comment by favorart** [comment]
I also have installed the MS VS 2019 community.
And I tried your advice:
Execute **'git clean -xdf**' and '**git submodule update --recursive**', also I pulled last git commits of the 'main' branch.
Then I executed the command '**.\build.bat --config Debug --build_shared_lib --parallel --cmake_generator "Visual Studio 16 2019"**' to build the onnx-runtime, again I got the same errors in 1 project 'libprotobuf-lite' of solution for MS VS 2019 (see log attached).
[MS-VS-2019.txt](https://github.com/microsoft/onnxruntime/files/9569622/MS-VS-2019.txt)

Python.exe v3.9.12 from Anaconda installed today
CMake.exe v3.24.1
I did not install CUDA or CUDNN, I want to try cpu inference (no training)

In log:
_-- Use protobuf from submodule -- 3.18.1.0_

![image](https://user-images.githubusercontent.com/9784285/190254035-375d79ba-24ab-487f-9db8-6ea383364715.png)

**Comment by snnn** [comment]
Your protobuf was from conda, not this repo. The version of protobuf you got from  conda is incompatible with our code. 

Your protobuf was from: 

C:\Users\kgolikov\Anaconda3\Library\include\google/protobuf/arena_impl.h


Please try to get a clean environment. Either a clean conda environment without protobuf C/C++ library, or a cpython environment from python.org.
