### ISSUE TITLE
NN_RET_CHECK failed error when trying to run a model on NNAPI, but model runs successfully on CPU

### ISSUE THREAD

**Issue by LakshmiTeja17** [microsoft/onnxruntime#12979]
**Describe the bug**

I am trying to run a YOLOv7 model (https://github.com/WongKinYiu/yolov7), that I have downloaded from here: https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-tiny.pt

I have converted this model to onnx, using the export.py script provided in the repo, using the following command:
`python export.py --weights yolov7-tiny.pt --grid --end2end --simplify --img-size 320 320 --max-wh 320`

Now, my aim is to run this ONNX model on an Android Device. The model runs successfully when I try to run it without NNAPI on CPU. But, when I try to run the model on GPU, using the NNAPI Execution Provider, I get the following error:

```
09-15 16:50:33.485  8203  8217 V onnxruntime:  [V:onnxruntime:, model_builder.cc:480 AddOperations] Adding node [135]
09-15 16:50:33.485  8203  8217 V onnxruntime:  [V:onnxruntime:, model_builder.cc:398 AddNewOperand] operand name: Sigmoid_140
09-15 16:50:33.485  8203  8217 E Operations: NN_RET_CHECK failed (packages/modules/NeuralNetworks/common/operations/Activation.cpp:384): getNumberOfDimensions(input) <= 4 (getNumberOfDimensions(input) = 5, 4 = 4) 
09-15 16:50:33.485  8203  8217 E ModelBuilder: Invalid Operation: NN_RET_CHECK failed (packages/modules/NeuralNetworks/common/operations/Activation.cpp:384): getNumberOfDimensions(input) <= 4 (getNumberOfDimensions(input) = 5, 4 = 4) 
```

**System information**

- Android Version: 12
- onnxruntime Version: 1.12 
I have built the .so file for Android using the following command: 
`./build.sh --android --android_sdk_path $SDK --android_ndk_path $NDK --android_api 33 --android_abi arm64-v8a --build_shared_lib --android_cpp_shared --cmake_generator Ninja --cmake_extra_defines onnxruntime_BUILD_UNIT_TESTS=OFF --parallel 8 --config MinSizeRel --build_dir $HOME/onnxruntime/build-dir --use_nnapi
`

**To Reproduce**

Create a onnxruntime session with the following option:

`Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_Nnapi(*gp_session_options_, flag));`

Then try opening the session as follows:

`session_ = new Ort::Session(*env_, modelBuffer, length, *gp_session_options_);`

**Comment by skottmckay** [comment]
Unfortunately the NNAPI Sigmoid (ANEURALNETWORKS_LOGISTIC) only supports up to 4 dimensions. 

https://developer.android.com/ndk/reference/group/neural-networks

We can update the ORT NNAPI EP to add a check so we don't attempt to use NNAPI for that node.

**Comment by YUNQIUGUO** [comment]
Just sent out a PR to add limit to NNAPI EP sigmoid handling to only accept input rank <=4. Hopefully can resolve the error.

**Comment by LakshmiTeja17** [comment]
Ok thanks a lot! After this fix, I am able to run the model successfully using NNAPI. 
But, the execution time is an issue. Using only CPU, the execution time was around 75 ms for an image. But the same image is taking around 500 ms on using NNAPI.
Is the execution of this particular Sigmoid Node on CPU instead of GPU, leading to this huge overhead? Or is it some other independent issue?

**Comment by skottmckay** [comment]
That performance would be as expected. Looking at [an onnx model in the release from that repo](https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7-nms-640.onnx) there's a Sigmoid node after every Conv. If NNAPI can't run the Sigmoid the cost of switching between NNAPI and the CPU EP so frequently would far outweigh any benefit of using NNAPI.

That said, in that onnx model the data is 4D not 5D so the Sigmoid nodes would be able to be handled by NNAPI and performance should be significantly better. Not sure what about your model export causes things to become 5D and unsupported.

**Comment by LakshmiTeja17** [comment]
In the ONNX model u referenced, even though most of the Sigmoid nodes are in 4D, there are 3 nodes towards the end of the model, ( a few layers before the Non-Max Suppression), which are in 5D. 
Same is the case, with my own ONNX model as well.
So, the switching between NNAPI and CPU would be only for these 3 nodes. Will that cause such a huge overhead?

**Comment by skottmckay** [comment]
Ah ok - missed those 3. Didn't expect it to become 5D at that point.

Those switches could potentially cause a lot of overhead as you have to move data to/from NPU each time NNAPI is run, which is expensive. I wouldn't expect it to be quite as much as you're seeing though. 

NNAPI performance is somewhat unpredictable as a lot depends on the hardware vendor's implementation. If that is missing operators it will fall back to using a very basic CPU based implementation within NNAPI. One way to test if that is the case is setting the 'cpu only' NNAPI flag. That will fail during model loading if a node assigned to NNAPI would fall back to the slow implementation.

https://onnxruntime.ai/docs/execution-providers/NNAPI-ExecutionProvider.html#nnapi_flag_cpu_disabled

You could also set the log severity to VERBOSE (0) to see additional information about the node placements and where NNAPI is planning on running things. 

https://onnxruntime.ai/docs/api/c/struct_ort_api.html#ac364c1ca9e610962ba96c37112a36d3e

**Comment by LakshmiTeja17** [comment]
Ah yes! that explains the increase in execution time. I get these relevant logs:

```
09-21 18:16:45.355 18206 18227 V onnxruntime:  [V:onnxruntime:, session_state.cc:1010 VerifyEachNodeIsAssignedToAnEp] Node placements
09-21 18:16:45.355 18206 18227 V onnxruntime:  [V:onnxruntime:, session_state.cc:1016 VerifyEachNodeIsAssignedToAnEp]  Node(s) placed on [NnapiExecutionProvider]. Number of nodes: 45
09-21 18:16:45.355 18206 18227 V onnxruntime:  [V:onnxruntime:, session_state.cc:1016 VerifyEachNodeIsAssignedToAnEp]  Node(s) placed on [CPUExecutionProvider]. Number of nodes: 103
```

Looks like it is not just those sigmoid nodes, even nodes like Mul, Pow, Add, Concat, Transpose, Reshape, LeakyRelu etc. have support only upto 4 dimensions,  while my model wants to execute them in 5 dimensions. A few relevant logs:

```
09-21 18:16:44.812 18206 18227 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:143 operator()] Node supported: [0] Operator type: [LeakyRelu] index: [106] name: [LeakyRelu_111] as part of the NodeUnit type: [LeakyRelu] index: [106] name: [LeakyRelu_111]
09-21 18:16:44.812 18206 18227 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:608 IsOpSupportedImpl] Mul only support up to 4d shape, input1 is 5d shape, input 2 is 0d shape
09-21 18:16:44.812 18206 18227 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:143 operator()] Node supported: [0] Operator type: [Mul] index: [137] name: [Mul_143] as part of the NodeUnit type: [Mul] index: [137] name: [Mul_143]
09-21 18:16:44.812 18206 18227 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:608 IsOpSupportedImpl] Pow only support up to 4d shape, input1 is 5d shape, input 2 is 0d shape
09-21 18:16:44.812 18206 18227 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:143 operator()] Node supported: [0] Operator type: [Pow] index: [139] name: [Pow_147] as part of the NodeUnit type: [Pow] index: [139] name: [Pow_147]
09-21 18:16:44.812 18206 18227 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:608 IsOpSupportedImpl] Add only support up to 4d shape, input1 is 5d shape, input 2 is 5d shape
09-21 18:16:44.812 18206 18227 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:143 operator()] Node supported: [0] Operator type: [Add] index: [138] name: [Add_145] as part of the NodeUnit type: [Add] index: [138] name: [Add_145]
09-21 18:16:44.812 18206 18227 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:608 IsOpSupportedImpl] Mul only support up to 4d shape, input1 is 5d shape, input 2 is 5d shape
09-21 18:16:44.812 18206 18227 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:143 operator()] Node supported: [0] Operator type: [Mul] index: [140] name: [Mul_149] as part of the NodeUnit type: [Mul] index: [140] name: [Mul_149]
09-21 18:16:44.812 18206 18227 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:1676 IsOpSupportedImpl] Concat only supports up to 1-4d shape, input is 5d shape
09-21 18:16:44.812 18206 18227 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:143 operator()] Node supported: [0] Operator type: [Concat] index: [141] name: [Concat_150] as part of the NodeUnit type: [Concat] index: [141] name: [Concat_150]
09-21 18:16:44.812 18206 18227 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:650 IsOpSupportedImpl] Transpose only supports 1-4d shape, input is 5d shape
09-21 18:16:44.812 18206 18227 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:143 operator()] Node supported: [0] Operator type: [Transpose] index: [471] name: [Transpose_token_344] as part of the NodeUnit type: [Transpose] index: [471] name: [Transpose_token_344]
09-21 18:16:44.812 18206 18227 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:720 IsOpSupportedImpl] Reshape only supports up to 1-4d shape, input is 5d shape
```
I see that this reshaping of 4D to 5D tensors is not just in YOLOv7, but in YOLOv5 architectures as well.
Now, I wonder why NNAPI has support only upto 4 dimensions, and whether it would be possible to add support for upto 5 dimensions.

**Comment by skottmckay** [comment]
5D support is really an NNAPI question and not something we have control over.

FWIW there was a competition to export YOLOv5 for Android. https://github.com/ultralytics/yolov5/discussions/3434

The conversion information for the winning entry specifically mentions avoiding the 5D shapes [here](https://github.com/lp6m/yolov5s_android/tree/master/convert_model#why-we-exclude-detect-head-layers)

Side note: Internally ORT will convert the model from NCHW to NHWC when using NNAPI, so there's no need for [this](https://github.com/lp6m/yolov5s_android/tree/master/convert_model#why-we-convert-the-model-via-openvino-format) process.

**Comment by LakshmiTeja17** [comment]
Oh, that is a great resource. Thanks a lot! Will try to use their ideas for my use-case.

**Comment by CarlSchader** [comment]
@LakshmiTeja17 were you able to get yolov7 to work on Android using the NNAPI? I am currently in the process of doing this myself but instead of using the ONNX runtime, I am using Pytorch-Lite for Android.

**Comment by skottmckay** [comment]
Any NNAPI limitation is going to apply to either ONNX Runtime or PyTorch.

@CarlSchader what benefit are you expecting PyTorch-Lite to provide over ONNX Runtime?

FWIW we also have the ability to handle the pre and post processing in the model so your application code doesn't need to do that. If the model is updated that way the input is the bytes from a png or jpeg and output is the bytes of the original image with the best bounding boxes drawn on it.

https://github.com/microsoft/onnxruntime-extensions/blob/main/tutorials/yolo_e2e.py
