### ISSUE TITLE
Documentation on JSON profile report

### ISSUE THREAD

**Issue by hossein1387** [microsoft/onnxruntime#1297]
I am using **onnxruntime 0.4.0** and I am using profiler.  I am trying to understand how to use this report. I am unable to find documentation on what the numbers represent. I enable the profiling using the following code:

```
        options = onnxrt.SessionOptions()
        options.enable_profiling = True
```
I then end profiling by:

```
     sess.end_profiling()
```

After running, I get a Json file with the following information (just couple of lines from the report with 14619 lines) :

```
{"cat" : "Session","pid" :7838,"tid" :7838,"dur" :30779,"ts" :13,"ph" : "X","name" :"model_loading_uri","args" : {}},
{"cat" : "Session","pid" :7838,"tid" :7838,"dur" :30116,"ts" :30796,"ph" : "X","name" :"session_initialization","args" : {}},
{"cat" : "Node","pid" :7838,"tid" :7838,"dur" :1,"ts" :96802,"ph" : "X","name" :"_fence_before","args" : {"op_name" : "Conv"}},
{"cat" : "Node","pid" :7838,"tid" :7838,"dur" :12944,"ts" :96807,"ph" : "X","name" :"_kernel_time","args" : {"op_name" : "Conv"}},
{"cat" : "Node","pid" :7838,"tid" :7838,"dur" :1,"ts" :109756,"ph" : "X","name" :"_fence_after","args" : {"op_name" : "Conv"}},
{"cat" : "Node","pid" :7838,"tid" :7838,"dur" :1,"ts" :109760,"ph" : "X","name" :"_fence_before","args" : {"op_name" : "BatchNormalization"}},
{"cat" : "Node","pid" :7838,"tid" :7838,"dur" :9342,"ts" :109763,"ph" : "X","name" :"_kernel_time","args" : {"op_name" : "BatchNormalization"}},
{"cat" : "Node","pid" :7838,"tid" :7838,"dur" :1,"ts" :119109,"ph" : "X","name" :"_fence_after","args" : {"op_name" : "BatchNormalization"}},
{"cat" : "Node","pid" :7838,"tid" :7838,"dur" :0,"ts" :119113,"ph" : "X","name" :"_fence_before","args" : {"op_name" : "Relu"}},

...
```

I can obviously guess some of the metrics description, however, it would be much more useful to have them in onnxruntime documentation.

**Comment by ybrnathan** [comment]
This is a standard performance tracing file, you can open it by
1. Open Chrome browser, and type chrome://tracing/
2. Load the saved JSON file, then you can see the performance along the time

**Comment by hossein1387** [comment]
Thanks, but what is the best way to use these statistics in the code? or do I need to parse the json file to get the statistics?

**Comment by ybrnathan** [comment]
Those data are for performance profiling and debugging purpose. It should not be used in prod scenario since it impacts performance. Can you elaborate your scenario?

**Comment by hossein1387** [comment]
I am trying to measure performance before and after I apply my optimization. So I want to mesaure Flops, executation time, model size. What is the best way to do this?

**Comment by jthelin** [comment]
Here's some links describing the Chrome tracing format which onnxruntime profiler produces. 

http://dev.chromium.org/developers/how-tos/trace-event-profiling-tool

https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/edit
