### ISSUE TITLE
LayerNorm, as ONNX operator, decomposition produces orphan node 

### ISSUE THREAD

**Issue by sumitsays** [microsoft/onnxruntime#12986]
### Describe the issue

[ORT decomposes](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/framework/graph_partitioner.cc#L496) the LayerNorm into its expanded form while executing LayerNorm as a ONNX operator (opset17) via CPU EP. This decomposition produces an orphan node in the expanded graph.

### To reproduce

Run onnxruntime_perf_text.exe via CPU EP and output the optimized model via -u parameter.

`.\onnxruntime_perf_test.exe -I -e cpu -d 0 -o 99 -m duration -r 1 -u <optimizedModelPath> <inputModelPath>`

Attaching the test input model as JSON.
[InputModel_LayerNormWithoutBias.txt](https://github.com/microsoft/onnxruntime/files/9579449/InputModel_LayerNormWithoutBias.txt)

_Screenshots_

**Input Model**

![image](https://user-images.githubusercontent.com/11188170/190522058-eb6fa86a-d12c-4f47-9e5f-94c296d237c8.png)

**Optimized Model**

![image](https://user-images.githubusercontent.com/11188170/190522127-d80fe556-f329-4933-9c18-6566d646977b.png)

### Platform

Windows

### OS Version

Windows 11 | 10.0.22000 Build 22000 

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

739b5675c8d28d3177ecc0f24cb82373014365f6

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
That is for an optional output as LayerNormalization has 2 of those. The bottom Concat is the other one.

https://github.com/onnx/onnx/blob/main/docs/Operators.md#LayerNormalization

ORT should drop the redundant nodes when it detects it has no consumer. The expansion is correct though.

**Comment by wschin** [comment]
That `orphan node` is for generating inverse stdev. See PyTorch equation below
![image](https://user-images.githubusercontent.com/3524474/191368087-11b5485e-1baa-4c41-b9f8-172fb955c1c8.png)

**Comment by sumitsays** [comment]
In that should that orphan node be marked as graph output?

**Comment by skottmckay** [comment]
Whether the output/s a node produces are consumed is controlled externally. The model author decides if an output is consumed, either via another node or by explicitly making it a graph output. It's not something that should happen implicitly as that would a) pollute the list of graph outputs and b) unnecessarily force the model to produce the value even though there's no explicit consumer for it.
