### ISSUE TITLE
[Training] pytorch exporter deleted symbolic_registry  while ort still uses it

### ISSUE THREAD

**Issue by zhijxu-MS** [microsoft/onnxruntime#13008]
### Describe the issue

this pytorch PR https://github.com/pytorch/pytorch/pull/84382 removed "torch.onnx.symbolic_registry", while ort still uses [it ](https://github.com/microsoft/onnxruntime/blob/14365b67a0de0acc1e6423477d7363bd5a98f0d7/onnxruntime/python/tools/pytorch_export_contrib_ops.py#L19)

@justinchuby could you give some suggestion on what kind of change ort need to take according to this torch change?

### To reproduce

the python code `import torch.onnx.symbolic_registry as sym_registry` will fail to run.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

ort nightly

### PyTorch Version

torch nightly

### Execution Provider

CUDA

**Comment by justinchuby** [comment]
Thanks for reminding. I will push a PR this week
