### ISSUE TITLE
Fatal error: ATen is not a registered function/op'

### ISSUE THREAD

**Issue by ritvickgupta-art** [microsoft/onnxruntime#13009]
### Describe the issue

I have taken a Mobilenet_V3 model from the torchvision and was trying to convert it to ONNX using the onnxruntime and was facing the issue
Fatal error: ATen is not a registered function/op'

Ubuntu: 20.04
onnxruntime: 1.7.0
numpy: 1.17.5
onnx 1.9.0

### To reproduce

Just take the model from torchvision library and run the onnxruntime session on the converted onnx model.

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.7.0

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA11.6

**Comment by justinchuby** [comment]
Can you share a snippet showing how you convert the model?

**Comment by ritvickgupta-art** [comment]
I converted the torchvision model to ONNX using:
`torch.onnx.export(
                self.py_model,
                model_inputs,
                self.onnx_model_path,
                opset_version=13,
                operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK)`

and was running the onnxruntime 
`      sess_options = onnxrt.SessionOptions()
        sess_options.log_severity_level = 4
        sess = onnxrt.InferenceSession(ort_onnx_model_path, sess_options)`

Pytorch verison:
1.8.1+cu111
torchvison version:
0.9.1+cu111

**Comment by justinchuby** [comment]
Please consider using the latest onnxruntime (1.12) (and if still doesn't work) and the latest PyTorch (1.12.1) version.

**Comment by GeorgeS2019** [comment]
@justinchuby 
Is this info relevant?
https://github.com/pytorch/pytorch/blob/bcc544e9d7b257c8b287151194d87565e95eb893/torch/onnx/symbolic_opset13.py#L32

**Comment by jbfhx** [comment]
I 've encountered the same problem. Have you solved your problem?

**Comment by justinchuby** [comment]
Please use the latest PyTorch version (2.0) for model conversion.
