### ISSUE TITLE
[Mobile] NNAPI: ANeuralNetworksModel_identifyInputsAndOutputs Can't set operand 2 to be an input or output

### ISSUE THREAD

**Issue by LakshmiTeja17** [microsoft/onnxruntime#13056]
### Describe the issue

I am trying to run a U-net model for semantic segmentation, with an EfficientNet-b0 model backbone.
I am using this repo for creation of the model: https://github.com/qubvel/segmentation_models.pytorch
I have created my model as follows:
```
import segmentation_models_pytorch as smp
model = smp.create_model('unet', encoder_name='efficientnet-b0', in_channels=in_channels, classes=out_classes)
```

I have converted this model to onnx, as follows:
```
model.set_swish(memory_efficient=False)
x = torch.randn(1, 3, 128, 256, requires_grad=True)
model.to_onnx(f'trained_models/{model_name}.onnx', 
                    x, 
                    export_params=True,
                    opset_version=16, 
                    do_constant_folding=True,
                    input_names = ['image'],
                    output_names = ['output'],)
```

Now, my aim is to run this ONNX model on an Android Device. The model runs successfully when I try to run it without NNAPI on CPU. But, when I try to run the model on GPU, using the NNAPI Execution Provider, I get the following error:

```
09-21 17:56:41.133 17687 17705 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name x shape [ 1 3 128 256 ]
09-21 17:56:41.133 17687 17705 E ModelBuilder: ANeuralNetworksModel_identifyInputsAndOutputs Can't set operand 2 to be an input or output.  Check that it's not a constant or already an input or output
09-21 17:56:41.136 17687 17705 E OnnxRTCore: Error code is 1
```

### To reproduce

Create a onnxruntime session with the following option:

`Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_Nnapi(*gp_session_options_, flag));`

Then try opening the session as follows:

`session_ = new Ort::Session(*env_, modelBuffer, length, *gp_session_options_);`

### Platform

Android

### OS Version

13

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.12

### ONNX Runtime API

C++/C

### Architecture

ARM64

### Execution Provider

NNAPI

**Comment by skottmckay** [comment]
Could you share the ONNX model as well as the exact values you're using when creating the session (specifically anything set in SessionOptions and the value of `flag`)?

**Comment by skottmckay** [comment]
@YUNQIUGUO could you maybe take a look?

**Comment by YUNQIUGUO** [comment]
@LakshmiTeja17 Hi, is it possible to maybe share the model you created with us? Just so to make sure we have the same models. Thanks!
