### ISSUE TITLE
Msbuild fails using onnxruntime.sln

### ISSUE THREAD

**Issue by joyIntel** [microsoft/onnxruntime#1305]
I am trying to build onnxruntime master branch using the following commands.

git clone https://github.com/microsoft/onnxruntime.git
cd onnxruntime
git submodule update –-init -–recursive
mkdir build
cd build
cmake -G "Visual Studio 15 2017 Win64" ..\cmake\
msbuild "onnxruntime.sln" /t:Rebuild /p:Configuration=Release /m

But I am getting errors -
![Error](https://user-images.githubusercontent.com/39498824/60226596-cc094800-9840-11e9-8f6f-aa2a760ca00b.png)

I need to use msbuild. I can not use build.bat because I have to modify some compiler options.

**Comment by snnn** [comment]
You can find an example in our CI build.
And you can modify compiler flags freely, it doesn't matter if you'll build it with msbuild or visual studio.

**Comment by joyIntel** [comment]
Could you be more specific ? I want to build the onnxruntime.sln and I am getting the linker errors.

**Comment by snnn** [comment]
Please tell me if you want a 32 bits build or 64 bits?

**Comment by joyIntel** [comment]
64 bits

**Comment by snnn** [comment]
Did you set it in your msbuild command?

**Comment by tracysh** [comment]
In case this helps, when you run the initial cmake, you need to specify "-A x64":

cmake -A x64 -G "Visual Studio 15 2017" ..\cmake

I tried what you originally had and the generated files for the MLAS project were missing the assembly files. With the above command, I see the expected files. The above is what is done in tools\ci_build\build.py.

**Comment by snnn** [comment]
Hi @tracysh,

Your hit is helpful. Please allow me elaborate more.

For cmake and VS, there are two ways to specify architecture(32 bits or 64)

1. (new) cmake -A x64 -G "Visual Studio 15 2017"
2. (old) cmake -G "Visual Studio 15 2017 Win64"

Everybody today should use the new one.
The old one, in most projects other than onnxruntime, should continue to work. For us, looks like it's not.  If somebody knows how to fix it, I'd like accept the change. Otherwise, I would think this is a low priority thing.

**Comment by skottmckay** [comment]
build.bat has a --cmake_extra_defines flag to pass through additional arguments to cmake. Is that insufficient? If so can you give an example of what you need to do?

**Comment by joyIntel** [comment]
Thanks guys for helping. As @snnn mentioned, option 1 is working but I was using option 2.  To answer @skottmckay 's question, I am using different compiler (not MSVC). I think the only thing I was doing wrong was x64 tag.

**Comment by joyIntel** [comment]
MSVC works fine. But while using Intel compiler, I am getting the following error. 
![compile_error](https://user-images.githubusercontent.com/39498824/60470703-502f4700-9c16-11e9-8642-86901ee0836c.png)

Steps to reproduce -
git clone https://github.com/microsoft/onnxruntime.git
cd onnxruntime
git submodule update –-init -–recursive
mkdir build
cd build
cmake -A x64 -G "Visual Studio 15 2017" -T "Intel C++ Compiler 19.0" ..\cmake
msbuild "onnxruntime.sln" /t:Rebuild /p:Configuration=Release /m

**Comment by skottmckay** [comment]
All those errors seem to come from static_assert(std::is_pod<T>::value, ...). Given they're only happening for the Intel compiler, and they are coming from code in external libraries (re2 and protobuf), what potential change to onnxruntime would address the problem? 

You could try and get more information on which specific types are involved by temporarily updating the code with the static_assert to add something like 'typeid(T).name()' to the error message. If they're onnxruntime types maybe there's something we can change for the Intel compiler to consider them PODs.

**Comment by joyIntel** [comment]
I don't think static_assert() will help. As far as I know , the second argument must be a string literal.

**Comment by joyIntel** [comment]
@skottmckay, @snnn  I don't think static_assert() will help. As far as I know , the second argument must be a string literal.

I am assuming the followings may cause the trouble -

onnxruntime\cmake\external\re2\util\sparse_arry.h - `PODArray <IndexValue>`
onnxruntime\cmake\external\re2\re2\simplify.cc - `PODArray<Regexp*>`
onnxruntime\cmake\external\re2\re2\set.cc - `PODArray<re2::Regexp*>`
onnxruntime\cmake\external\protobuf\src\google\protobuf\extension_set.cc - `CreateArray<KeyValue>`

**Comment by snnn** [comment]
There are separated things. I think the original issue was for how to use msbuild. Now you are asking support for Intel c++ compiler.
Would you please create an new issue or change the title of this one please?

**Comment by joyIntel** [comment]
@snnn You are right. I will close this one and create a new issue. Sorry, it was my bad !
