### ISSUE TITLE
Relax protobuf version requirement.

### ISSUE THREAD

**Issue by xkszltl** [microsoft/onnxruntime#13053]
### Describe the issue

Protobuf now has 3.20.2.
Recommend to write <4 instead.
- https://github.com/microsoft/onnxruntime/blob/c7a4093db8d78fd9a98e836292170b41ab688f54/requirements-training.txt#L7
- https://pypi.org/project/protobuf/3.20.2/

Issue filed to onnx as well:
- https://github.com/onnx/onnx/issues/4532

**Comment by pranavsharma** [comment]
+ @askhade to evaluate this.

**Comment by askhade** [comment]
https://github.com/microsoft/onnxruntime/pull/13596/files fixes the issue.
