### ISSUE TITLE
where is the definition of Struct OrtSession

### ISSUE THREAD

**Issue by weishengying** [microsoft/onnxruntime#13051]
### Describe the issue

I want to ask a simple question: 
when I use c/c++ API, I can't find the definition of Struct OrtSession in the source code; only the forward declaration

### To reproduce

when i use c/c++ API, I can't find the definition of Struct OrtSession in the source code; only the forward declaration

### Platform

Linux

### OS Version

ubuntu18.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

main branch

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by pranavsharma** [comment]
OrtSession is intentionally designed to be an opaque object to ensure binary compatibility of our APIs. What's your use case for knowing the definition?

**Comment by weishengying** [comment]
Just to study the source code , but can't find the definition of OrtSession makes me confused。
so does this repo not contain all the source code of onnxruntime？ And which static library contain the implementation of OrtSession？

**Comment by weishengying** [comment]
thank for your answer，I have comprehended this design！
