### ISSUE TITLE
Not working!: [Issue labeler] C# api as separate label (trying again)

### ISSUE THREAD

**Issue by GeorgeS2019** [microsoft/onnxruntime#13085]
### Describe the issue

When I submit e.g. feature request involving c#, I do not get the issue [**labeled** ](https://github.com/microsoft/onnxruntime/pull/12951)

In turn, I received multiple emails from github stated that the labelling fails

##### No labbeling of **api:CSharp**

![image](https://user-images.githubusercontent.com/49812372/192089926-9a0fbe74-5304-411a-a4ba-4c1e753c4232.png)

### Urgency

**api:CSharp** not working

### Platform

Web Browser

### OS Version

Browser

### ONNX Runtime Installation

Other / Unknown

### ONNX Runtime Version or Commit ID

https://github.com/microsoft/onnxruntime/pull/12951/files

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

Default CPU

**Comment by GeorgeS2019** [comment]
I believe there are more issues related to c# than java, yet 10 are shown for java and none for c# and javascript

![image](https://user-images.githubusercontent.com/49812372/192167157-7d9baeb4-da9e-465c-83ae-92dd0d8a0632.png)

**Comment by GeorgeS2019** [comment]
Using dark read with black text makes it hard to read.   Consider bright or light red

**Comment by GeorgeS2019** [comment]
Finally it works!

**Comment by faxu** [comment]
> Using dark read with black text makes it hard to read. Consider bright or light red

Thanks for the suggestion. Updated to a lighter color

**Comment by GeorgeS2019** [comment]
@faxu, 

The lighter color is a good improvement.  We are facing many global challenges, bright and happy color does help :-)

This issue has not been labelled yet
https://github.com/microsoft/onnxruntime/issues/13049
