### ISSUE TITLE
python onnxruntime not using multiple threads for application of ml model

### ISSUE THREAD

**Issue by MaxNoe** [microsoft/onnxruntime#1308]
**Describe the bug**

Despite declaring the options 
```
options = onnxruntime.SessionOptions()
options.enable_sequential_execution = False
options.session_thread_pool_size = 12
```

the application is only run on a single core.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux, Ubuntu 18.04
- ONNX Runtime installed from (source or binary): pip 
- ONNX Runtime version: 0.4.0
- Python version: 3.7.3

**To Reproduce**

```
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType
import onnxruntime
import numpy as np
import time
from onnxmltools import save_model
from skl2onnx.helpers.onnx_helper import select_model_inputs_outputs




y = np.random.randint(0, 2, size=100_000)
X = np.random.normal(y, 0.5, size=(25, len(y))).T.astype('float32')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.95)

clr = RandomForestClassifier(n_estimators=100, n_jobs=12)
clr.fit(X_train, y_train)

# Convert into ONNX format with onnxmltools
initial_type = [('float_input', FloatTensorType([1, 4]))]
onnx = convert_sklearn(
    clr,
    name='classifier',
    initial_types=initial_type,
)
onnx = select_model_inputs_outputs(onnx, 'probabilities')
save_model(onnx, 'random.onnx')


options = onnxruntime.SessionOptions()
options.enable_sequential_execution = False
options.session_thread_pool_size = 12


# Compute the prediction with ONNX Runtime
sess = onnxruntime.InferenceSession("random.onnx", sess_options=options)
input_name = sess.get_inputs()[0].name


print('Starting prediction')
t0 = time.perf_counter()
pred_onx = sess.run(None, {input_name: X_test})[0][:, 1]
print(time.perf_counter() - t0)
```

**Expected behavior**

onnxruntime is using 12 cores to apply model.

**Comment by skottmckay** [comment]
SessionOptions.enable_sequential_execution is more about executing multiple nodes in parallel. In this case it looks like you only have a RandomForestClassifier node, which I believe converts to TreeEnsembleClassifier in onnx.  

There was a recent change to that to allow multiple threads to execute within the TreeEnsembleClassifier node if OpenMP is being used. https://github.com/microsoft/onnxruntime/pull/1276. 

There's also a future task to convert this to use our ParallelFor so it's not limited to OpenMP.

**Comment by MaxNoe** [comment]
Even if the tree ensemble is not parallelized, why is the application over the events not?

This is the trivial parallelzation that's possible with every learner.

**Comment by faxu** [comment]
Related to https://github.com/microsoft/onnxruntime/issues/827 - please use that for discussion. Resolving this as dupe.
