### ISSUE TITLE
[Build] DML and TensorRT cannot be used at the same time

### ISSUE THREAD

**Issue by 1017354253** [microsoft/onnxruntime#13099]
### Describe the issue

I want to use both DML and Tensorrt on my project.
When Tensorrt tool is installed on their computers, use Tensorrt , otherwise use DML,But I found that they can't exist at the same time,
I wonder if this idea is feasible

### Target platform

Windows

### Build script

C++

### Error / output

First install Onnxruntime Tensorrt. I can find the Tensorrt acceleration options，After I install the Onnxruntime DML again, I cannot find the Tensorrt option.

**Comment by fdwr** [comment]
@1017354253 Are you building locally yourself? If so, what build flags are you passing during build? This *should* already be possible when building C++ locally 🤔, because I recall do this earlier this year. It's been a while since I tried, but the last time I used the following:

```
build.bat --build_shared_lib --parallel --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\cudnn-11.3-windows-x64-v8.2.1.32" --tensorrt_home "C:\Program Files\NVIDIA GPU Computing Toolkit\TensorRT-8.2.4.2" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3" --use_cuda --use_tensorrt --cuda_version 11.3 --config RelWithDebInfo --skip_tests --skip_submodule_sync --use_dml --cmake_generator "Visual Studio 16 2019"
```

(obviously update the paths according to your own installation paths)

**Comment by skottmckay** [comment]
Can you clarify what you are doing when installing? The ORT TRT and DML packages are independent alternative versions of 'onnxruntime'. If you install one after the other it replaces the first one. They don't accumulate.

If you want a package that includes both TRT and DML you would have to build that yourself.

**Comment by 1017354253** [comment]
Yes, I used to install via NuGet package,but I found that it doesn't do what I want.
After I build it, I found that they work！
Thanks!
