### ISSUE TITLE
[Build] building DirectML as external project is blocked; git repo is on a private Microsoft server

### ISSUE THREAD

**Issue by diablodale** [microsoft/onnxruntime#13094]
### Describe the issue

https://github.com/microsoft/onnxruntime/pull/11827/commits/9435369550532989f6bcc009b1e928cca5fdf587 introduced the ability to build DirectML itself from a git repo. However, the git repo coded in `dml.cmake` is private. Also, the commit SHA referenced is something private to that repo and was not pushed to the public https://github.com/microsoft/DirectML repro

### Repro

* Onnxruntime v1.12.1

From `dml.cmake`
```cmake
...
include(ExternalProject)
    ExternalProject_Add(
        directml_repo
        GIT_REPOSITORY https://dev.azure.com/microsoft/WindowsAI/_git/DirectML
        GIT_TAG 2290bd6495fdf8c35822816213516d13f3742cc9
        GIT_SHALLOW OFF # not allowed when GIT_TAG is a commit SHA, which is preferred (it's stable, unlike branches)
        GIT_PROGRESS ON
        BUILD_IN_SOURCE ON
        CONFIGURE_COMMAND ${CMAKE_COMMAND} --preset ${dml_preset_name} -DDML_BUILD_TESTS=OFF
        BUILD_COMMAND ${CMAKE_COMMAND} --build --preset ${dml_preset_name}
        INSTALL_COMMAND ${CMAKE_COMMAND} --install build/${dml_preset_name}
        STEP_TARGETS install
    )
```

### Result

`GIT_REPOSITORY` is private and requires a RSA key, user/pass, etc.
For example ,this fails...
```
git clone https://dev.azure.com/microsoft/WindowsAI/_git/DirectML
Cloning into 'DirectML'...
<3>init: (31959) ERROR: UtilConnectToInteropServer:307: connect failed 2
^[<3>init: (32035) ERROR: UtilConnectToInteropServer:307: connect failed 2
fatal: Authentication failed for 'https://dev.azure.com/microsoft/WindowsAI/_git/DirectML/'
```

`2290bd6495fdf8c35822816213516d13f3742cc9` is a commit that doesn't exist on https://github.com/microsoft/DirectML

### Expected

`GIT_REPOSITORY` points to https://github.com/microsoft/DirectML.git
`GIT_TAG` is a hash valid on that public repo

### Target platform

Windows

### Build script

as above

### Error / output

as above

### Visual Studio Version

VS2019 Community v16.11.19

**Comment by fdwr** [comment]
@diablodale That little snippet is only for internal builds and testing, as DirectML.dll itself is not open source (distributed via https://www.nuget.org/packages/Microsoft.AI.DirectML/ and as a Windows system component). The repo https://github.com/microsoft/DirectML.git contains our samples.

If you're trying to run ORT against a specific version of DirectML.dll, you can use the custom option mentioned in dml.cmake.

```
# 2) Custom = the build points at a local copy of DirectML (bin/, include/, lib/). The dml_INCLUDE_DIR and 
#    dml_LIB_DIR variables are also expected to be set to the custom build location.
```

Or you can temporarily locally hack your packages.config (e.g. https://github.com/microsoft/onnxruntime/pull/12931/files).

**Comment by diablodale** [comment]
haha, my understanding...I thought DirectML was also open sourced at its git repro.
I'm closing this issue as I see no issue understanding that. 👍
