### ISSUE TITLE
LayerNormalization crashes on execution on CUDA with fp16 operands

### ISSUE THREAD

**Issue by borisfom** [microsoft/onnxruntime#13104]
### Describe the issue

This error happens during deployment of NVIDIA Riva TTS (fastpitch). ONNX file was generated with cuda.autocast. 
This used to work until onnxruntime-1.12. Now it fails:

onnx runtime error 6: Exception during initialization: /workspace/onnxruntime/onnxruntime/core/optimizer/transformer_memcpy.cc:374 bool onnxruntime::TransformerMemcpyImpl::ProcessInitializers(const onnxruntime::KernelRegistryManager&, const InitializedTensorSet&) status.IsOK() was false. Failed to find kernel for LayerNormalization(1) (node LayerNormalization_token_21). Op with name (LayerNormalization_token_21) and type (LayerNormalization) kernel is not supported in CUDAExecutionProvider. Encountered following errors: (Found kernel for Op with name (LayerNormalization_token_21) and type (LayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented only for the following types (tensor(float),), but the node in the model has the following type (tensor(float16))
Found kernel for Op with name (LayerNormalization_token_21) and type (LayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented only for the following types (tensor(double),), but the node in the model has the following type (tensor(float16))
Found kernel for Op with name (LayerNormalization_token_21) and type (LayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented only for the following types (tensor(float16),), but the node in the model has the following type (tensor(float))
Found kernel for Op with name (LayerNormalization_token_21) and type (LayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented only for the following types (tensor(float),), but the node in the model has the following type (tensor(float16))
Found kernel for Op with name (LayerNormalization_token_21) and type (LayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented only for the following types (tensor(bfloat16),), but the node in the model has the following type (tensor(float16))
)

### To reproduce

Download ONNX file : 
https://drive.google.com/file/d/11zKmOKxz9G6JHbaav0ec7ozd4gWMMU9S/view?usp=sharing

Run, e.g:
> polygraphy run --onnxrt ./fastpitch.onnx

### Urgency

This issue is blocking use of recent Triton server images bundled with onnxruntime-1.12, for Riva.

### Platform

Linux

### OS Version

20.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

onnxruntime-1.12

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.6, 11.8

**Comment by tianleiwu** [comment]
@borisfom, there is recent commit for the operator. Could you try https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/PyPI/ort-nightly-gpu/overview/1.13.0.dev20220927003 ?

**Comment by borisfom** [comment]
Thanks! Yes I saw https://github.com/microsoft/onnxruntime/pull/12975. I will try the new build. 
Just a side note: in our case, we were adding FP32 casts before LayerNorm on purpose - so the fact fp16 ops were there may be an indication of fusing being too eager to discard 'unneeded' casts. 12975 enables fp16 operands for LayerNorm, but they should not have been there in the first place.

**Comment by borisfom** [comment]
@tianleiwu : When is 1.13.0 coming out ? If it's not soon - can we have another 1.12.x release to pick up that bugfix ?

**Comment by tianleiwu** [comment]
@Borisfom, 1.13 will be released soon (maybe end of next week or so).

**Comment by borisfom** [comment]
Thanks! We can close this issue then.

**Comment by borisfom** [comment]
@tianleiwu : any word on 1.13 release ?

**Comment by borisfom** [comment]
I can also see the nightly builds are now using 1.14xxx numbers - is 1.13 being skipped altogether ?

**Comment by tianleiwu** [comment]
@borisfom, I saw 1.13.1 released in https://github.com/microsoft/onnxruntime/releases.

**Comment by cliveseldon** [comment]
I'm seeing this with 1.14.1 release
```
/onnxruntime_src/onnxruntime/core/optimizer/transformer_memcpy.cc:374 bool onnxruntime::TransformerMemcpyImpl::ProcessInitializers(const onnxruntime::KernelRegistryManager&, const InitializedTensorSet&) status.IsOK() was false. Failed to find kernel for SimplifiedLayerNormalization(1) (node SimplifiedLayerNormalization). Op with name (SimplifiedLayerNormalization) and type (SimplifiedLayerNormalization) kernel is not supported in CUDAExecutionProvider. Encountered following errors: (Found kernel for Op with name (SimplifiedLayerNormalization) and type (SimplifiedLayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented only for the following types (tensor(float),), but the node in the model has the following type (tensor(double))
Found kernel for Op with name (SimplifiedLayerNormalization) and type (SimplifiedLayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented only for the following types (tensor(double),), but the node in the model has the following type (tensor(float))
Found kernel for Op with name (SimplifiedLayerNormalization) and type (SimplifiedLayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented only for the following types (tensor(float16),), but the node in the model has the following type (tensor(float))
Found kernel for Op with name (SimplifiedLayerNormalization) and type (SimplifiedLayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented only for the following types (tensor(float16),), but the node in the model has the following type (tensor(float))
Found kernel for Op with name (SimplifiedLayerNormalization) and type (SimplifiedLayerNormalization) in the supported version range (node_version: 1 kernel start version: 1 kernel_end_version: 2147483647). However the types are incompatible. This op has been implemented only for the following types (tensor(float16),), but the node in the model has the following type (tensor(double))
```

Is this expected?
