### ISSUE TITLE
[Performance] dml EP does not align output tensor data; it is defaulting to 16-byte alignment

### ISSUE THREAD

**Issue by diablodale** [microsoft/onnxruntime#13119]
### Describe the issue

The DML EP is not aligning its output tensor data `GetTensorMutableData()`. Instead, it is default aligned by Windows to only 16-bytes. For a decade, it is far more useful, given AVX and better, to align to 32-bytes or...even better...64-bytes. Data from tensors is often further processed and having it 32 or 64-bit aligned is required or better for performance

I isolated the issue to `BucketizedBufferAllocator.cpp` where it uses the simpliest of host mem allocation...
https://github.com/microsoft/onnxruntime/blob/94e34ace15f4c7011590d387c5dcabaa3e446d7f/onnxruntime/core/providers/dml/DmlExecutionProvider/src/BucketizedBufferAllocator.cpp#L261-L274

### Setup

* Onnxruntime v1.12.1
* Microsoft Windows [Version 10.0.19044.2006]
* VS2019 v16.11.19

### Repro

1. Create a simple app to infer with `squeezenet1.0-7.onnx`. Use the DML exec provider with all else the defaults.
2. Get the memory address of the resulting tensor's data `reinterpret_cast<uintptr_t>(frame.GetTensorMutableData<char>()) % 64` and inspect its alignment.

### Result

The alignment will vary on different runs of the app. It will randomly be 0, 16, 32, or 48

### Expected

To be able programatically or by compile define/setting to declare the desired alignment of output data.

### Notes and Workarounds

No workarounds. The onnxruntime codebase has to be changed.
The changes are easy. I have already done them in my private build of onnxruntime for my solution that requires 64-bit align.
What's needed in this issue is a discussion on a approach which can make alignment available to the general public on `main`

### Platform

Windows

### OS Version

10.0.19044.2006

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

v1.12.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

DirectML

### Execution Provider Library Version

1.9.0

### Is this a quantized model?

Unknown

**Comment by diablodale** [comment]
In my local build of onnxruntime, I did the following to achieve 64-bit align of DML output tensor data. This will demonstrate the codepaths and start our discussion on how this can be generalized for everyone.

`BucketizedBufferAllocator.cpp` I like this change for everyone as it will use the Default's os-specific aligners
```c++
void* CPUAllocator::Alloc(size_t size)
{
    return onnxruntime::AllocatorDefaultAlloc(size);
}

void CPUAllocator::Free(void* p)
{
    return onnxruntime::AllocatorDefaultFree(p);
}
```

`framework/allocator.cc` is a unproven tweak to prevent repeated calls to `MlasGetPreferredBufferAlignment()` that is not always a compile-time constant. Add `static` in two places for std and mimalloc
```c++
void* AllocatorDefaultAlloc(size_t size) {
  static const size_t alignment = MlasGetPreferredBufferAlignment();
  ...
```

Finally for my amd64 capable machine, which onnxruntime code defines as `MLAS_TARGET_AMD64` I need to change `MlasGetPreferredBufferAlignment()` to always return 64. I changed `onnxruntime/core/mlas/lib/mlasi.h` to `#define MLAS_DEFAULT_PREFERRED_BUFFER_ALIGNMENT 64`. Then the initialization and later call to `GetMlasPlatform().PreferredBufferAlignment` will return that 64.

Though for my private build, I later changed `AllocatorDefaultAlloc()` to have a hardcoded 64 to eliminate unneeded codepaths.

**Comment by fdwr** [comment]
@diablodale We can just forward `Dml::CPUAllocator` forward to [AllocatorDefaultAlloc](https://github.com/microsoft/onnxruntime/blame/main/onnxruntime/core/framework/allocator.cc#L74) like you say, which would return a larger alignment (32 or 64 byte) and is consistent with the CPU EP, but for any changes to core ORT like framework/allocator.cc or mlasi.h, we'd want input from someone on ORT core. Dmitri? @yuslepukhin

**Comment by diablodale** [comment]
ping. Awakening the conversation on using appropriate CPU allocators that align with other parts of onnxruntime and that align with something better than 16 bytes so wide SIMD instructions work efficiently on results.

I've been running my fixes for ~5 months. Work great in my scenario.

1. We can we do better than malloc(). Its already done and ready to be used as I suggest above and @fdwr supports.
2. What about the alignment flexibility? I use a fixed value as described above for my private hack. For the public API I suggest a compile-time param with default(s).

**Comment by fdwr** [comment]
> I've been running my fixes for ~5 months. Work great in my scenario.

Dale, are you willing to create a PR for it? (just the [AllocatorDefaultAlloc](https://github.com/microsoft/onnxruntime/blame/main/onnxruntime/core/framework/allocator.cc#L74) part) Thanks.

**Comment by diablodale** [comment]
@fdwr sure. PR pushed.
