### ISSUE TITLE
[Web] Failed to load model because protobuf parsing failed.

### ISSUE THREAD

**Issue by freemanliu** [microsoft/onnxruntime#13117]
### Describe the issue

This happens when executing             this.session = await InferenceSession.create(`./${this.model_name}`);
the model is converted from pytorch and the size is 63M.(Not sure if it can be uploaded.) It can be loaded and run with python without a problem.

Failed to load model because protobuf parsing failed.
overrideMethod @ react_devtools_backend.js:4026
i @ ort-web.min.js:6
$func3799 @ ort-wasm-simd.wasm:0x2da96e
$func1891 @ ort-wasm-simd.wasm:0x14738e
$func491 @ ort-wasm-simd.wasm:0x3c71f
$func3740 @ ort-wasm-simd.wasm:0x2d485f
$func2317 @ ort-wasm-simd.wasm:0x18c96b
$func1609 @ ort-wasm-simd.wasm:0x103310
$func823 @ ort-wasm-simd.wasm:0x7759d
$func238 @ ort-wasm-simd.wasm:0x1e6f0
$T @ ort-wasm-simd.wasm:0x5b6d84
t._OrtCreateSession @ ort-web.min.js:6
t.createSession @ ort-web.min.js:6
t.createSession @ ort-web.min.js:6
loadModel @ ort-web.min.js:6
await in loadModel (async)
createSessionHandler @ ort-web.min.js:6
await in createSessionHandler (async)
create @ inference-session-impl.ts:189
await in create (async)
getMoveAsync @ OnnxAgent.ts:23
(anonymous) @ Board.tsx:73
setTimeout (async)
(anonymous) @ Board.tsx:70
commitHookEffectList @ react-dom.development.js:19986
commitPassiveHookEffects @ react-dom.development.js:20016
callCallback @ react-dom.development.js:347
invokeGuardedCallbackDev @ react-dom.development.js:397
invokeGuardedCallback @ react-dom.development.js:454
flushPassiveEffectsImpl @ react-dom.development.js:22868
unstable_runWithPriority @ scheduler.development.js:643
runWithPriority$2 @ react-dom.development.js:11305
flushPassiveEffects @ react-dom.development.js:22841
(anonymous) @ react-dom.development.js:22419
scheduler_flushTaskAtPriority_Normal @ scheduler.development.js:436
flushTask @ scheduler.development.js:482
flushWork @ scheduler.development.js:607
performWorkUntilDeadline @ scheduler.development.js:231

### To reproduce

InferenceSession.create(`./${this.model_name}`);

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.1

### Execution Provider

WASM

**Comment by freemanliu** [comment]
the model is too big to load.

**Comment by freemanliu** [comment]
A smaller version (16M) has the same problem. Model attached. 
[conv-13.onnx.zip](https://github.com/microsoft/onnxruntime/files/9652658/conv-13.onnx.zip)
Here is the graph:
graph torch_jit (
  %boards[FLOAT, 1x1x13x13]
  %turns[FLOAT, 1x1]
) initializers (
  %conv.conv1.weight[FLOAT, 128x1x5x5]
  %conv.conv1.bias[FLOAT, 128]
  %conv.conv2.weight[FLOAT, 256x128x5x5]
  %conv.conv2.bias[FLOAT, 256]
  %conv.conv3.weight[FLOAT, 512x256x5x5]
  %conv.conv3.bias[FLOAT, 512]
  %linear.weight[FLOAT, 1x513]
  %linear.bias[FLOAT, 1]
) {
  %input0 = Conv[dilations = [1, 1], group = 1, kernel_shape = [5, 5], pads = [0, 0, 0, 0], strides = [1, 1]](%boards, %conv.conv1.weight, %conv.conv1.bias)
  %result = Relu(%input0)
  %input2 = Conv[dilations = [1, 1], group = 1, kernel_shape = [5, 5], pads = [0, 0, 0, 0], strides = [1, 1]](%result, %conv.conv2.weight, %conv.conv2.bias)
  %result.3 = Relu(%input2)
  %input4 = Conv[dilations = [1, 1], group = 1, kernel_shape = [5, 5], pads = [0, 0, 0, 0], strides = [1, 1]](%result.3, %conv.conv3.weight, %conv.conv3.bias)
  %result.7 = Relu(%input4)
  %conv_output = Flatten[axis = 1](%result.7)
  %linear_input = Concat[axis = 1](%conv_output, %turns)
  %output = Gemm[alpha = 1, beta = 1, transB = 1](%linear_input, %linear.weight, %linear.bias)
  return %output
}

**Comment by fs-eire** [comment]
I checked the model and it works on my PC.

The model is OK. Your code is OK, and the log tells that it successfully run into the WebAssembly so the wasm is loaded OK.

One possible reason is that the model file is not served by the server correctly. From devtool, check the following headers:

content-length: 16408506
content-type: application/octet-stream

**Comment by freemanliu** [comment]
Thanks, Yulong! You nailed it! Somehow this file was missing from the server side. All good now.
One more thought, the error message is kind of misleading, it would be better if it just says something like "file xxx not found".

**Comment by arnabtarwani** [comment]
Hi, I have been trying to solve this issue in Vercel however, the issue is persistent https://github.com/xenova/transformers.js/issues/295 
Can someone help me out with this please?
