### ISSUE TITLE
cannot use fasterrcnn onnx model in c# api

### ISSUE THREAD

**Issue by i-newton** [microsoft/onnxruntime#1311]
steps:
download https://github.com/onnx/models/tree/master/faster_rcnn
try to run model in .net
```
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.ML;
using AlexNet.DataStructures;
using Microsoft.ML.Transforms.Image;

namespace SomeNet
{
    public class ImageClassifier
    {
        private readonly string dataLocation;
        private readonly string labelsLocation;
        private readonly string imagesLocation;
        private readonly string modelLocation;
        private readonly MLContext mLContext;

        public ImageClassifier(string dataLocation, string imagesLocation, string labelsLocation, string modelLocation)
        {
            this.dataLocation = dataLocation;
            this.labelsLocation = labelsLocation;
            this.imagesLocation = imagesLocation;
            this.modelLocation = modelLocation;
            mLContext = new MLContext();
        }

        public struct ImageSettings
        {
            public const int imageHeight = 224;
            public const int imageWidth = 224;
        }

        public struct OnnxModelSettings
        {
            public const string ModelInput = "image";
        }

        public void Score()
        {
            var model = LoadModel(dataLocation, imagesLocation, modelLocation);

            var predictions = PredictData(dataLocation, imagesLocation, labelsLocation, model).ToArray(); 
        }

        private PredictionEngine<ImageData, ImagePrediction> LoadModel(string dataLocation, string imagesLocation, string modelLocation)
        {
            var data = mLContext.Data.LoadFromTextFile<ImageData>(dataLocation, hasHeader: false);

            var pipeline = mLContext.Transforms.LoadImages(outputColumnName: "loadedimage", imageFolder: imagesLocation, inputColumnName: nameof(ImageData.ImagePath))
                .Append(mLContext.Transforms.ResizeImages(outputColumnName: "resizedimage",inputColumnName:"loadedimage", imageWidth: ImageSettings.imageWidth, imageHeight: ImageSettings.imageHeight))
                .Append(mLContext.Transforms.ExtractPixels(outputColumnName: "image", inputColumnName:"resizedimage", orderOfExtraction: ImagePixelExtractingEstimator.ColorsOrder.ABGR))
                .Append(mLContext.Transforms.ApplyOnnxModel(modelFile: modelLocation, outputColumnNames: new[] { "6379", "6381", "6383" }, inputColumnNames: new[] { "image"}));
            var model = pipeline.Fit(data);

            var predictionEngine = mLContext.Model.CreatePredictionEngine<ImageData, ImagePrediction>(model, ignoreMissingColumns:false);

            return predictionEngine;
        }

        protected IEnumerable<ImageData> PredictData(string imageLocation, string imageFolder, string labelsLocation, PredictionEngine<ImageData, ImagePrediction> model)
        {
            var labels = labelsLocation;
            var p = model.Predict(new ImageData{
                ImagePath = "/home/snake/aspose/anton.perhunov/AlexNet/AlexNet/assets/Data/html.jpg"
            });
            var im =  new ImageData{
                ImagePath = imageFolder + "/e5725c32f8be4da8b6a27375fc7669ae_html.jpg"
            };
            yield return im;
        }
    }
}


```
when inference any image you will get
Unhandled Exception: System.ArgumentException: Length of memory (150528) must match product of dimensions (3).
   at System.Numerics.Tensors.DenseTensor`1..ctor(Memory`1 memory, ReadOnlySpan`1 dimensions, Boolean reverseStride)
   at Microsoft.ML.Transforms.Onnx.OnnxUtils.CreateNamedOnnxValue[T](String name, ReadOnlySpan`1 data, List`1 shape)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.NamedOnnxValueGetterVec`1.GetNamedOnnxValue()
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.UpdateCacheIfNeeded(Int64 position, INamedOnnxValueGetter[] srcNamedOnnxValueGetters, String[] activeOutputColNames, OutputCache outputCache)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.<>c__DisplayClass13_0`1.<MakeGetter>b__0(VBuffer`1& dst)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.<>c__DisplayClass8_0`1.<CreateDirectVBufferSetter>b__0(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.FillValues(TRow row)
   at Microsoft.ML.PredictionEngineBase`2.Predict(TSrc example)

it seems that .net api does not support dynamic input sizes(-1 in dimension), it just treat them as 1, model supports inputs with (3, -1,-1), however onnx value size become (3,1,1).

**Comment by skottmckay** [comment]
The error seems to be coming from Microsoft.ML code rather than Microsoft.ML.OnnxRuntime code. Should this issue be for https://github.com/dotnet/machinelearning?

**Comment by jignparm** [comment]
@i-netwon,  I was able to score the faster-rcnn model just fine using the OnnxRuntime C# API and the sample test data that comes with the model, using [this code snippet](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs#L21).

As sckottmckay mentioned,  the ML.NET project is under a different [repo](https://github.com/dotnet/machinelearning), but uses OnnxRuntime  library under the hood. 

In the  `AdjustDimensions()` function [here](https://github.com/dotnet/machinelearning/blob/master/src/Microsoft.ML.OnnxTransformer/OnnxTransform.cs#L289), the dimensions are converted from (3, -1, -1) to (3, 1, 1), with the  assumption that the input node shape will match the shape of the input tensor later on at scoring time. However,  the faster-rcnn model has dynamic axes, and the input node shape will not be equal to  shape of the input tensor at scoring time. The input tensor's shape needs to be set correctly, otherwise the `System.Numerics.Tensor` class will throw the message you see above.

A fix for this is to pass the tensor shape values as part of the dataset, or else as a user argument (both require code changes in the OnnxTransform codebase however).

If you just need to score the model in C# somehow (and don't have ML.NET dependency) you can use the snippet I pointed to above.

**Comment by i-newton** [comment]
Thanks, I tried the snippet, set fixed dimensions and it worked,
I also created another issue under  https://github.com/dotnet/machinelearning
Could you please help me with one question:
how can i transform jpeg image into bench.in file? i can't find any examples of doing this.

**Comment by jignparm** [comment]
The bench.in format (assuming you're referring to the file below) contains a header line containing input column names, followed by text version of the linearlized data values.

See [the LoadTensorFromFile() function](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs#L723) which parses the bench.in file for more details about the format.

```
$ less csharp/testdata/bench.in
data_0
[[[[1.7640523911,0.4001572132,0.9787380099,2.2408931255,....
```

**Comment by i-newton** [comment]
i am closing the issue since it is related to https://github.com/dotnet/machinelearning
