### ISSUE TITLE
Fails to load model with function using `Concat`

### ISSUE THREAD

**Issue by maekawatoshiki** [microsoft/onnxruntime#13121]
### Describe the issue

The following code (in **To reproduce** section) generates a model with a function containing single `Concat` node, and tries to execute it.
I think that ONNX Runtime should successfully execute it, but it fails to load the model with the error message below.

```sh
Traceback (most recent call last):
  File "concat.py", line 46, in <module>
    main()
  File "concat.py", line 39, in main
    sess = ort.InferenceSession(filepath, providers=["CPUExecutionProvider"])
  File "/path/to/.env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/path/to/.env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ./concat.onnx failed:vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
```

### To reproduce

The code: (opset version 13 doesn't matter) 

```python
import onnxruntime as ort
import onnx
from onnx import helper, ValueInfoProto, TensorProto

import numpy as np


def main():
    inputs = [
        helper.make_tensor_value_info("x", TensorProto.FLOAT, [6, 10]),
        helper.make_tensor_value_info("y", TensorProto.FLOAT, [6, 10]),
    ]
    outputs = [helper.make_tensor_value_info("z", TensorProto.FLOAT, [12, 10])]

    f = helper.make_function(
        "MyDomain",
        "func",
        ["a", "b"],
        ["c"],
        [helper.make_node("Concat", ["a", "b"], ["c"], axis=0)],
        opset_imports=[helper.make_opsetid("", 13)],
    )

    nodes = [helper.make_node("func", ["x", "y"], ["z"], domain="MyDomain")]
    graph = helper.make_graph(nodes, "main", inputs, outputs)

    model = helper.make_model(
        graph,
        functions=[f],
        opset_imports=[
            helper.make_opsetid("", 13),
            helper.make_opsetid("MyDomain", 13),
        ],
    )

    filepath = "./concat.onnx"
    onnx.save(model, filepath)

    sess = ort.InferenceSession(filepath, providers=["CPUExecutionProvider"])
    x = np.random.rand(6, 10).astype(np.float32)
    y = np.random.rand(6, 10).astype(np.float32)
    sess.run(None, {"x": x, "y": y})


if __name__ == "__main__":
    main()
```

Netron:

- Main graph
![Screenshot from 2022-09-28 00-39-52](https://user-images.githubusercontent.com/9913176/192571936-88b30055-d35d-4bac-8550-cfaf11b5d81b.png)

- Function `func`
![Screenshot from 2022-09-28 00-39-58](https://user-images.githubusercontent.com/9913176/192571928-0f54147e-9bb8-4fd8-a05f-29a7ac536105.png)

### Urgency

Not urgent.

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
Does the onnx checker believe the model to be valid? That's not a guarantee it is, but it's a starting point.

Add this before the onnx.save:

`onnx.checker.check_model(model, True)`

**Comment by maekawatoshiki** [comment]
I added `onnx.checker.check_model(model, True)` before `onnx.save`, but it raises no error.

**Comment by skottmckay** [comment]
This issue is that the code processing the function is not handling a node with variadic inputs. Due to that it causes an invalid access to node_op_schema->inputs here as the Concat schema has a single variadic input, but the Concat node itself has 2 inputs:

https://github.com/microsoft/onnxruntime/blob/32c2c4b480c3983de216a92b19ce06b9cf75780c/onnxruntime/core/graph/function_utils.cc#L120-L127

@souptc or @gramalingam could you please take a look?

**Comment by maekawatoshiki** [comment]
The PR (https://github.com/microsoft/onnxruntime/pull/13140) seems to be merged. Is the problem fixed?
