### ISSUE TITLE
How to populate onnx model with custom meta data map ?

### ISSUE THREAD

**Issue by ac4922** [microsoft/onnxruntime#1315]
I have an array which I intend to append in the onnx file itself.

In my opninion, onnxruntime provides an option to retrieve custom meta data map/

from onnxruntime import InferenceSession
sess = InferenceSession(example)
meta = sess.get_modelmeta()
print("custom_metadata_map={}".format(meta.custom_metadata_map))
source - https://microsoft.github.io/onnxruntime/auto_examples/plot_metadata.html#sphx-glr-auto-examples-plot-metadata-py

However, it is always populated empty. My goal is to append some custom_metadata when I convert a scikit learn model to onnx which is available when the onnx is read by onnxruntime.

Please suggest if that is possible and how.

**Comment by pranavsharma** [comment]
Please file this issue here https://github.com/onnx/sklearn-onnx/issues. Thanks!
