### ISSUE TITLE
Onnxruntime C++ resize/reshape/squeeze

### ISSUE THREAD

**Issue by EmreOzkose** [microsoft/onnxruntime#13166]
Hi,

Is there a function to resize/squeeze/reshape an Ort::Value object? 

I saw [these codes](https://github.com/microsoft/onnxruntime/tree/e86214e5c00ffbb95b85478c111c8eb21de94fe9/onnxruntime/core/providers/cpu/tensor), but should I include some directories in cmake to use them?

My CMakeLists is:
```
include_directories( 
    ${ONNXRUNTIME_ROOTDIR}/include/onnxruntime/core/session/
    ${ONNXRUNTIME_ROOTDIR}/include/onnxruntime/core/providers/tensorrt/
)
```

**Comment by pranavsharma** [comment]
> Is there a function to resize/squeeze/reshape an Ort::Value object?

No, these are not directly exposed. You can use CreateOp, InvokeOp if you want to use the public APIs, otherwise you'll have to copy source files from the  onnxruntime/core/providers/cpu/tensor folder.

**Comment by EmreOzkose** [comment]
And [reshape](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/cpu/tensor/reshape.h) also require GSL.

**Comment by EmreOzkose** [comment]
I will try CreateOp, and InvokeOp, thank you.

**Comment by manickavela-uni** [comment]
Hi @pranavsharma,

Can you please share some reference or example, for the same?
This issue is a little old, if there is any straight forward way to do this it will be helpful.

Thank you
