### ISSUE TITLE
Batch inference fails with ONNXRuntime

### ISSUE THREAD

**Issue by IzanCatalan** [microsoft/onnxruntime#13184]
### Describe the issue

Hi, I'm trying to make Infference with ORT 1.9 with any vgg16 model from ONNXModel zoo repo (https://github.com/onnx/models/tree/main/vision/classification/vgg). 
I load de datased and the bath with gluoncv, however I do the inferenc with ORT (line 166). With a batch size of 1, variable "data" (line 162) has a shape of (1, 3, 224, 224) but if I change the batch size to 128 or 512 It will have a shape of (512, 3,224,224). 
In doing so, it fails with the following output:

Traceback (most recent call last):
  File "insertValidate.py", line 236, in <module>
    evaluate(new_model, data)
  File "insertValidate.py", line 166, in evaluate
    outputs=ort_session_cpu.run(None, ort_inputs_cpu)
  File "/mnt/beegfs/users/izan/.local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: data for the following indices
 index: 0 Got: 512 Expected: 1
 Please fix either the inputs or the model.

I would like to know how I can make batch inference with  ORT.

Thanks!

![imagen](https://user-images.githubusercontent.com/40836734/193315378-1c5dfcfa-13ba-47f4-81bc-ce3d7f3d326c.png)

### To reproduce

Installa:

Onnx 1.10
Onnxruntime 1.9
GluonCV
Mxnet
Python 3.7

Download Onnx Model Zoo models.

### Platform

Linux

### OS Version

Ubuntu 18

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

onnxruntime-gpu 1.9.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

Cuda 10.2

**Comment by snnn** [comment]
Not a bug of ORT. The model doesn't support it. I suggest getting the model from TF then you convert the model by yourself. The model you were using was from MXNet. Or you contact the MXNet team.  I don't have any experience with MXNet, so I can't help you.
