### ISSUE TITLE
[Feature Request] LongT5(from Transformer) Support 

### ISSUE THREAD

**Issue by caffeinetoomuch** [microsoft/onnxruntime#13189]
### Describe the feature request

I am currently using [optimum](https://github.com/huggingface/optimum) in order apply optimization and quantization for LongT5 checkpoint(`google/long-t5-tglobal-xl`) and `optimum` is using `Optimizer` from `onnxruntime`. However, it does not seems LongT5 is being supported now although T5 is supported. I wish we get support for LongT5 as well!

### Describe scenario use case

Optimize and serve!

**Comment by kunal-vaishnavi** [comment]
You can export the LongT5 model with optimum

```
python3 -m optimum.exporters.onnx --model google/long-t5-tglobal-xl xl/
```

and then optimize directly with the optimizer script

```
python3 -m onnxruntime.transformers.optimizer --input xl/model.onnx --output xl/model.onnx --use_external_data_format
```

Then you can test your model

```
import onnxruntime
import numpy as np

# Replace these values with your data
batch_size = 4
sequence_length = 16
inputs = {
     ‘input_ids’: np.ones((batch_size, sequence_length)).astype(np.int64),
     ‘attention_mask’: np.ones((batch_size, sequence_length)).astype(np.int64),
     ‘decoder_input_ids’: np.ones((batch_size, sequence_length)).astype(np.int64)
}

# Run inference session
sess = onnxruntime.InferenceSession(‘xl/model.onnx’, providers=[‘CUDAExecutionProvider’, ‘CPUExecutionProvider’])
outputs = sess.run(None, inputs)
print(outputs)
```
by replacing the values in `batch_size`, `sequence_length`, and `inputs` with your data.

Environment:
- onnx: v1.12.0
- onnxruntime: v1.13.1
- optimum: v1.5.1
- transformers: v4.24.0
- torch: v1.11.0

**Comment by hanbitmyths** [comment]
PR in Optimum: [Add support for LongT5 optimization using ORT transformer optimizer script](https://github.com/huggingface/optimum/pull/683)
