### ISSUE TITLE
How to turn off warnings during execution in Python?

### ISSUE THREAD

**Issue by fuzzyBatman** [microsoft/onnxruntime#1319]
I've tried setting SessionOptions and RunOptions but they have no effect.
I get output of the form

```
2019-06-29 14:55:47.517754566 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2798 exists in this graph's initializers but it is not used by any node
2019-06-29 14:55:47.517784053 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2429 exists in this graph's initializers but it is not used by any node
2019-06-29 14:55:47.517791860 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2428 exists in this graph's initializers but it is not used by any node
2019-06-29 14:55:47.517804215 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2253 exists in this graph's initializers but it is not used by any node
2019-06-29 14:55:47.517838501 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2252 exists in this graph's initializers but it is not used by any node
2019-06-29 14:55:47.517843125 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2231 exists in this graph's initializers but it is not used by any node
2019-06-29 14:55:47.517847523 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2230 exists in this graph's initializers but it is not used by any node
2019-06-29 14:55:47.517851823 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2221 exists in this graph's initializers but it is not used by any node
```

and then some.

Can someone help me with this?
Also, is it possible to redirect onnx warnings and errors to a file on the system?
Thanks.

**Comment by skottmckay** [comment]
What did you try setting in SessionOptions and RunOptions? The latest code has the ability to set the logging severity (was checked in a couple of weeks ago), but the 0.4 release only let you set the verbose logging level.

Another approach would be to fix the model so that it doesn't have unused initializers. Is that an option?

It should be possible to add a class that implements ISink and uses the py::print from pybind instead of using the std::cerr based CErrSink [here:](https://github.com/microsoft/onnxruntime/blob/f67a1629fcb6ce24ad54fb33b19709c2b30e9c66/onnxruntime/python/onnxruntime_pybind_state.cc#L205) 

Details on py::print: https://pybind11.readthedocs.io/en/stable/advanced/pycpp/utilities.html

**Comment by faxu** [comment]
@fuzzyBatman - does the answer above help? please let us know if you require any additional assistance.

**Comment by fuzzyBatman** [comment]
Sorry. Had to take care of other things in the meantime.
I will be using this again in the following week and will post an update.

**Comment by faxu** [comment]
@fuzzyBatman any update on this?

**Comment by fuzzyBatman** [comment]
It seems to have been added to onnxruntime.
I did an update with pip and all the warnings disappeared.

**Comment by FraLupo** [comment]
I tried 
[        rt.SessionOptions().log_severity_level=3
        rt.RunOptions().log_severity_level=3](url)

But I still get all the warnings I was getting before. What am I doing wrong?

**Comment by hpc203** [comment]
> I've tried setting SessionOptions and RunOptions but they have no effect.
> I get output of the form
> 
> ```
> 2019-06-29 14:55:47.517754566 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2798 exists in this graph's initializers but it is not used by any node
> 2019-06-29 14:55:47.517784053 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2429 exists in this graph's initializers but it is not used by any node
> 2019-06-29 14:55:47.517791860 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2428 exists in this graph's initializers but it is not used by any node
> 2019-06-29 14:55:47.517804215 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2253 exists in this graph's initializers but it is not used by any node
> 2019-06-29 14:55:47.517838501 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2252 exists in this graph's initializers but it is not used by any node
> 2019-06-29 14:55:47.517843125 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2231 exists in this graph's initializers but it is not used by any node
> 2019-06-29 14:55:47.517847523 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2230 exists in this graph's initializers but it is not used by any node
> 2019-06-29 14:55:47.517851823 [W:onnxruntime:Default, graph.cc:2208 CleanUnusedInitializers] 2221 exists in this graph's initializers but it is not used by any node
> ```
> 
> and then some.
> 
> Can someone help me with this?
> Also, is it possible to redirect onnx warnings and errors to a file on the system?
> Thanks.

Env env{ORT_LOGGING_LEVEL_ERROR, "test"};

**Comment by skottmckay** [comment]
They're warnings as your model has a lot of unused initializers that could be cleaned up. Ideally you'd fix the model, but if you just want to ignore the warnings you can set the default logger to ERROR level with this:
```
import onnxruntime as ort
ort.set_default_logger_severity(3)
```

Or when setting the session or run options you must pass in the options when creating the session or calling `run`. You code is creating a new instance of SessionOptions or RunOptions but essentially throwing it away before using it.

e.g.
```
    so = ort.SessionOptions()
    so.log_severity_level = 3
    s = ort.InferenceSession(<model_path>, so)  # <-- pass in the SessionOptions instance here
```

**Comment by AbhijitManepatil** [comment]
> ort.set_default_logger_severity(3)

It works for me, thanks

**Comment by AbhijitManepatil** [comment]
> > ort.set_default_logger_severity(3)
> 
> It works for me, thanks

**Comment by oscar-lima** [comment]
> ```
> import onnxruntime as ort
> ort.set_default_logger_severity(3)
> ```

Huge thanks @skottmckay !
