### ISSUE TITLE
[Feature Request] C# : how I can innovate the language generation using com.microsoft.nlp contributed ops?

### ISSUE THREAD

**Issue by GeorgeS2019** [microsoft/onnxruntime#13209]
#### Original title
C# : how I can innovate the language generation in onnx gpt-2 model with the beam search and/or other custom operators of similar class (Deep NLP)

### Describe the feature request

[how I can stop or truncate the generation in onnx gpt-2 model with the beam search option](https://github.com/microsoft/onnxruntime/issues/13088) provides an **unmet** Deep NLP use case, especially langauge generation.

Currently, early stopping needs to be enabled with appropriately generated eos token to customize BeamSearch results

### Describe scenario use case

The [feedback ](https://github.com/microsoft/onnxruntime/issues/13088#issuecomment-1264791404)from user suggests additional ways to customize BeamSearch is needed to provide more optimum language generation results.

This is just with BeamSearch, how about other Contributed Operators of similar class? e.g. GreedySearch discussed in [Classify Contributed Ops ](https://github.com/microsoft/onnxruntime/issues/13084)

##### nlp
com.microsoft.nlp
- [com.microsoft.nlp.BeamSearch](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.BeamSearch)
- [com.microsoft.nlp.GreedySearch](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.GreedySearch)

**Comment by GeorgeS2019** [comment]
Potentially related discussion on how to provide the contributed Ops outside the standard boundaries to innovate freely

> [It is important that we are able to innovate freely when outside the standard boundaries.](https://github.com/microsoft/onnxruntime/issues/13049#issuecomment-1266056729)

E.g. provide [c# example](https://github.com/microsoft/onnxruntime-extensions/issues/298) on pre- and postprocessing custom ops derived from contributed ops: [OpenCV Image Decoder & SuperResolution CustomOps](https://github.com/microsoft/onnxruntime-extensions/pull/295)

**Comment by yuslepukhin** [comment]
> Potentially related discussion on how to provide the contributed Ops outside the standard boundaries to innovate freely
> 
> From @yuslepukhin
> 
> > [It is important that we are able to innovate freely when outside the standard boundaries.](https://github.com/microsoft/onnxruntime/issues/13049#issuecomment-1266056729)
> 
> E.g. provide [c# example](https://github.com/microsoft/onnxruntime-extensions/issues/298) on pre- and postprocessing custom ops derived from contributed ops: [OpenCV Image Decoder & SuperResolution CustomOps](https://github.com/microsoft/onnxruntime-extensions/pull/295)

Contributed ops are not standard ops and they are not supported. They are usually not subject to any standard specification. Sometimes they are developed to try an op out before it makes to the standard, other times they exist for optimization purposes.
If we commit to support them, we cannot change and drop them as we see fit and that would impact our ability to improve things. They are not for public consumption.

**Comment by yuslepukhin** [comment]
I guess the term `contributed` throws people off.

**Comment by GeorgeS2019** [comment]
@yuslepukhin  In fact, the term `contributed` literally means these are Ops contributed through **iterative discussions** `by` and `for `the ONNX industry partners.

I keep voicing feature requests because I believe strongly that these `contributed` ops need to be **democratized** to minority communities such as c# users. :-)

**Comment by tianleiwu** [comment]
@GeorgeS2019, 
You can follow some c# examples to run inference on an ONNX model with beamsearch operator: https://onnxruntime.ai/docs/tutorials/csharp/bert-nlp-csharp-console-app.html and
https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_sharp

The interface of ONNX model are tensors (inputs and outputs), so the code for inference does not need know what ops is inside the ONNX model.

**Comment by GeorgeS2019** [comment]
@tianleiwu 
Thank you.!
