### ISSUE TITLE
Running models taking empty tensors via C API

### ISSUE THREAD

**Issue by matteosal** [microsoft/onnxruntime#13219]
### Describe the issue

ONNX supports empty tensors (tensors with a shape of `[0]`), but I couldn't find a way to run these models with the C API, for example [this ONNX node test](https://github.com/onnx/onnx/tree/5a5f8a5935762397aa68429b5493084ff970f774/onnx/backend/test/data/node/test_reduce_sum_default_axes_keepdims_example). 

The `Run` C function expects inputs in the form of `OrtValue`s, so I've tried to create the empty input with the following call:
```
 CreateTensorWithDataAsOrtValue(
    mem_info, // some OrtMemoryInfo*
    nullptr, // data pointer
    0, // data length 
    nullptr, // shape pointer 
    0, // shape length
    type, // ONNXTensorElementDataType
    out // output OrtValue
);
```
The above call appears to work but then a crash occurs when such `OrtValue` is passed to the `Run` function.

### To reproduce

Separating my code into a standalone C executable program is nontrivial and I hope the above description is enough to get guidance. I will provide a standalone C example if needed.

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

b6c04f48c131d54a8e0fbe27e66ca7a9f6383737

### ONNX Runtime API

C

### Architecture

X64

### Execution Provider

Default CPU

**Comment by pranavsharma** [comment]
What would be the point of passing an empty tensor to ORT? In this case the input 'axes' is optional. If you don't intend to use it, you can simply choose to omit it in the Run call.

**Comment by matteosal** [comment]
@pranavsharma I have actually tried to do that, but it seems it's required. The `Run` function fails with this message:
```
Non-zero status code returned while running ReduceSum node. Name:'' Status Message: /home/matteo/Git/onnxruntimelink/3rdparty/onnxruntime/include/onnxruntime/core/framework/op_kernel_context.h:40 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: axes
```
I think this is happening because the `ReduceSum' operator in the model is explicitly listing a second input in its input list. Optional inputs can be omitted when the operator is constructed, but if they are not omitted in that phase they are required at runtime.

**Comment by pranavsharma** [comment]
As per [opset 13](https://github.com/onnx/onnx/blob/main/docs/Changelog.md#ReduceSum-13), axes is optional. If you don't intend to use it you should remove it as a required input from the model. If you intend to use it you should supply a valid memory buffer to ORT.

**Comment by matteosal** [comment]
@pranavsharma another ping on this :)

**Comment by matteosal** [comment]
Ok I have figured this out. The shape pointer should not be `nullptr` because empty arrays do have a shape (which must include a 0). If an empty array is created this way then the `Run` function works properly.
