### ISSUE TITLE
Broken link on docs page

### ISSUE THREAD

**Issue by tall-josh** [microsoft/onnxruntime#13218]
The link on the [ORT Format Models](https://onnxruntime.ai/docs/reference/ort-format-models.html#load-and-execute-a-model-in-ort-format) page is broken.
![image](https://user-images.githubusercontent.com/18511395/193992207-a366eeba-6d5b-44b3-aa0c-c13d10d2b975.png)

it leads to `https://onnxruntime.ai/api`
![image](https://user-images.githubusercontent.com/18511395/193992254-ff7d6a2a-e9af-4e25-a92a-a0bd64e94808.png)

When I guess it should lead to https://onnxruntime.ai/docs/api/

**Comment by natke** [comment]
Fized by #13220
