### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by xkszltl** [microsoft/onnxruntime#1322]
**Describe the bug**

"session_op[t]ions"
https://github.com/microsoft/onnxruntime/blob/2698edbc98950c31edbae91af8ca049f61c46eb6/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp#L22

**System information**
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master

**Comment by faxu** [comment]
@xkszltl can you please send a PR to fix it?

**Comment by xkszltl** [comment]
A little bit overkill but sure -_-|||
