### ISSUE TITLE
How to use C API to do inference with models with multiple inputs and outputs？

### ISSUE THREAD

**Issue by doruime** [microsoft/onnxruntime#1323]
How to use C API to deal with models with multiple inputs and outputs？

**Comment by pranavsharma** [comment]
Did you take a look at the header file? The Run() function takes multiple inputs and returns multiple outputs already. Take a look [here](https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h#L196). Let us know which part of this function is not clear?

**Comment by doruime** [comment]
> Did you take a look at the header file? The Run() function takes multiple inputs and returns multiple outputs already. Take a look [here](https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h#L196). Let us know which part of this function is not clear?

Thank you. I have multiple inputs and read data from memory, how can I create OrtValue with multiple inputs?

**Comment by snnn** [comment]
One ortvalue is only for one input.

**Comment by ZJU-lishuang** [comment]
In OrtRun, the size of  output_names is three,but I can set the output_names_len to three,why?

**Comment by k2kobayashi** [comment]
Hi, I'm currently extend s following code to make multiple inputs and outputs. But I could not understand how to make two input OrtValues to a single argument to run OrtRun function. Could you give me any way to do that?
https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp

I use onnxruntime-0.5.0 on Linux and Its inputs follow:
```
Number of inputs = 2
Input 0 : name=actual_input
Input 0 : type=1
Input 0 : num_dims=3
Input 0 : dim 0=1
Input 0 : dim 1=11
Input 0 : dim 2=25
Input 1 : name=actual_hidden
Input 1 : type=1
Input 1 : num_dims=3
Input 1 : dim 0=2
Input 1 : dim 1=1
Input 1 : dim 2=256
```

**Comment by doruime** [comment]
> Hi, I'm currently extend following code to make multiple inputs and outputs. But I could not understand how to make two input OrtValues to a single argument to run OrtRun function. Could you give me any way to do that?
> https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp
> 
> I use onnxruntime-0.5.0 on Linux and Its inputs follow:
> 
> ```
> Number of inputs = 2
> Input 0 : name=actual_input
> Input 0 : type=1
> Input 0 : num_dims=3
> Input 0 : dim 0=1
> Input 0 : dim 1=11
> Input 0 : dim 2=25
> Input 1 : name=actual_hidden
> Input 1 : type=1
> Input 1 : num_dims=3
> Input 1 : dim 0=2
> Input 1 : dim 1=1
> Input 1 : dim 2=256
> ```
Using OrtValue* input_tensors[input_node_names_.size()] works fine.
OrtRun(....,(const OrtValue* const*)&input_tensors,.....)

**Comment by faxu** [comment]
@doruime did you have any further questions on this?

**Comment by wangchuan** [comment]
@doruime : Your comments "Using OrtValue* input_tensors[input_node_names_.size()] works fine.
OrtRun(....,(const OrtValue* const*)&input_tensors,.....)" makes me confused. input_tensors is an array of OrtValue*, so it should be of type OrtValue**, so &input_tensors is of type OrtValue***, how can we force convert it into a (const OrtValue* const*)?

**Comment by yaleimeng** [comment]
@wangchuan  I met the same question.
Did you suceed finally? and how ?

**Comment by jie-chen** [comment]
same question here,  the input values is
 const Value* as shown here https://onnxruntime.ai/docs/api/c/struct_ort_1_1detail_1_1_session_impl.html#af3f7d273f5e468ef21ef0d56d48c32fd . How to make it as multiple inputs ? There is no default instructor of Value
