### ISSUE TITLE
[Build] when include cuda_provider_factory.h ,it will report error

### ISSUE THREAD

**Issue by Dsqds** [microsoft/onnxruntime#13230]
### Describe the issue

when #include <core/providers/cuda/cuda_provider_factory.h>, it will report the following error:
In file included from /home/featurize/work/pytorch-cifar100/0-demo-onnxruntime-cpp/main.cc:4:
/home/featurize/work/onnxruntime/onnxruntime/core/providers/cuda/cuda_provider_factory.h:37:11: error: ‘Status’ does not name a type; did you mean ‘OrtStatus’?
   37 |   virtual Status CudaCall_false(int retCode, const char* exprString, const char* libName, int successCode, const char* msg) = 0;
      |           ^~~~~~
      |           OrtStatus

### Target platform

x86,cuda-11.2

### Build script

git clone --recursive https://github.com/Microsoft/onnxruntime
git submodule update --init --recursive
./build.sh --skip_tests --use_cuda --config Release --build_shared_lib --parallel --cuda_home /usr/local/cuda-11.2 --cudnn_home /usr/local/cuda-11.2

# CMakeLists.txt
cmake_minimum_required(VERSION 2.8)
project(main)

set(CMAKE_BUILD_TYPE "Release")
set(CMAKE_INCLUDE_CURRENT_DIR ON)

#onnxruntime
set(ONNXRUNTIME_ROOT_PATH /home/featurize/work/onnxruntime)
set(ONNXRUNTIME_INCLUDE_DIRS ${ONNXRUNTIME_ROOT_PATH}/include/onnxruntime
                             ${ONNXRUNTIME_ROOT_PATH}/onnxruntime
                             ${ONNXRUNTIME_ROOT_PATH}/include/onnxruntime/core/session/)
set(ONNXRUNTIME_LIB ${ONNXRUNTIME_ROOT_PATH}/build/Linux/Release/libonnxruntime.so)
include_directories(${ONNXRUNTIME_INCLUDE_DIRS})

add_executable(${PROJECT_NAME} "main.cc")
target_link_libraries(${PROJECT_NAME} ${ONNXRUNTIME_LIB})

// main.cc
#include <iostream>
#include <core/session/onnxruntime_cxx_api.h>
#include <core/session/onnxruntime_c_api.h>
#include <core/providers/cuda/cuda_provider_factory.h>

int main()
{
    std::cout << "hello" << std::endl;
    return 0;
}

### Error / output

when #include <core/providers/cuda/cuda_provider_factory.h>, it will report the following error:
In file included from /home/featurize/work/pytorch-cifar100/0-demo-onnxruntime-cpp/main.cc:4:
/home/featurize/work/onnxruntime/onnxruntime/core/providers/cuda/cuda_provider_factory.h:37:11: error: ‘Status’ does not name a type; did you mean ‘OrtStatus’?
   37 |   virtual Status CudaCall_false(int retCode, const char* exprString, const char* libName, int successCode, const char* msg) = 0;
      |           ^~~~~~
      |           OrtStatus

**Comment by pranavsharma** [comment]
https://github.com/microsoft/onnxruntime/issues/12636#issuecomment-1220927257

**Comment by cloudhan** [comment]
You are using a private header and it is not meant to be used outside of ort itself. You should remove `${ONNXRUNTIME_ROOT_PATH}/onnxruntime` from you include path.

Internally, some headers are not self contained due to some historical reason. So devs need to include the missing files and enforce the include order manually. And there is a non mandatory IWYU check to improve the situation.

**Comment by ytaous** [comment]
Close it for now, pls feel free to reopen if the feedback above doesn't help.
