### ISSUE TITLE
How to use SNPE provider?

### ISSUE THREAD

**Issue by VictoryDong** [microsoft/onnxruntime#13247]
### Discussed in https://github.com/microsoft/onnxruntime/discussions/13244

<div type='discussions-op-text'>

<sup>Originally posted by **VictoryDong** October  8, 2022</sup>
There are too few documents for using SNPE, so I don't know how to load the model into a session, so far I have done a little experiment:
1. Load the onnx format model and it can run normally, but looking at the cpu ratio, it should be that the dsp is not used, and all run on the cpu.
2. When loading the dlc format model, an error is reported directly, and the model cannot be loaded correctly。

Can anyone help me？

more Information：
I followed the documentation steps to compile the library using snpe and configure the options of snpe。

```
std::unordered_map<std::string, std::string> snpe_options;
 snpe_options["runtime"] = "DSP";
 snpe_options["buffer_type"] = "FLOAT";
 sessionOptions->AppendExecutionProvider("SNPE", snpe_options);
```

</div>

**Comment by HectorSVC** [comment]
Please check the inference examples here: https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/Snpe_EP.
Let me know if any further question.

**Comment by VictoryDong** [comment]
> Please check the inference examples here: https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/Snpe_EP.
> Let me know if any further question.


Thanks for your help, a loadable onnx file is now exported.

Currently on the Xiaomi Mi 8 phone, the UNSIGNEDPD_CHECK check fails. Please, if this does not pass, what effect will it have on running the model?
