### ISSUE TITLE
DynamicSlice was a removed  experimental ops. In the future, we may directly reject this operator

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#1326]
**Describe the bug**
I use PyTorch to export a model with dynamic input size (using `torch.script`) and now I get this warning

> DynamicSlice was a removed  experimental ops. In the future, we may directly reject this operator
> Please update your model as soon as possible.Warning: DynamicSlice was a removed  experimental ops. In the future, we may directly reject this operator. Please upd ate your model as soon as possible.

So, if I export again in the future would it have issue with dynamic input size, or would normal `Slice` do the correct thing?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- ONNX Runtime installed from (source or binary): nuget
- ONNX Runtime version: 0.4.0
- Visual Studio version (if applicable): 2015

**To Reproduce**
Run previously exported module

**Expected behavior**
No warning, or make sure new exports will continue supporting dynamic input sizes

**Context**

This is module that results in `DynamicSlice`

```python
@torch.jit.script
def center_slice_helper(x, h_offset, w_offset, h_end, w_end):
    return x[:, :, h_offset:h_end, w_offset:w_end]


class CenterCrop(nn.Module):
    def __init__(self, crop_size):
        """Crop from the center of a 4d tensor
        Input shape can be dynamic
        :param crop_size: the center crop size
        """
        super(CenterCrop, self).__init__()
        self.crop_size = crop_size

    def extra_repr(self):
        """Extra information
        """
        return 'crop_size={}'.format(
            self.crop_size
        )

    def forward(self, x):
        h_offset = (x.shape[2] - self.crop_size) / 2
        w_offset = (x.shape[3] - self.crop_size) / 2
        h_end = h_offset + self.crop_size
        w_end = w_offset + self.crop_size
        return center_slice_helper(x, h_offset, w_offset, h_end, w_end)
```

**Comment by pranavsharma** [comment]
Slice operator (since opset 10) now supports dynamic inputs. Please use that instead.

**Comment by snnn** [comment]
The "DynamicSlice" operator has been removed from ONNX.  But onnxruntime still has it, so you may ignore this warning.

**Comment by dashesy** [comment]
Thanks, nice to have a single Slice.

**Comment by dashesy** [comment]
@pranavsharma can you please add this to the error message? (to use opset10). Also the export of slice with `dynamic_axes` is incorrect, instead of using shape it uses constants
