### ISSUE TITLE
Failed to create CUDAExecutionProvider

### ISSUE THREAD

**Issue by Serenaneres1** [microsoft/onnxruntime#13264]
### Describe the issue

when I run yolov5 val.py, the problem occurs.

[W:onnxruntime:Default, onnxruntime_pybind_state.cc:566 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.

### To reproduce

python val.py --weights yolov5s.onnx --device 0

I think the environment already satisfied the requirements, the details as follows.
The environment:
onnx(i have alread run pip uninstall onnxruntime, pip uninstall onnxruntime-gpu, pip install onnxruntime):
# Name                    Version                   Build  Channel
onnx                      1.12.0                    <pip>
onnxruntime-gpu           1.12.0                    <pip>

nvidia-smi:
| NVIDIA-SMI 515.76       Driver Version: 515.76       CUDA Version: 11.7     |

cuda and cudnn:
cuda 11.3 and cudnn 8.2.4

### Platform

Linux

### OS Version

CentOS Linux release 7.7.1908 (Core)

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

cuda 11.3

**Comment by ytaous** [comment]
Can u pls share the model and code for us to try? Thx.

**Comment by pranavsharma** [comment]
You need only 1 pkg for CPU+GPU inferencing: `onnxruntime-gpu`. Please get rid of `onnxruntime` pkg (which is meant for CPU only inferencing).

**Comment by Serenaneres1** [comment]
> You need only 1 pkg for CPU+GPU inferencing: `onnxruntime-gpu`. Please uninstall `onnxruntime` pkg (which is meant for CPU only inferencing).

I have already uninstall onnxruntime

**Comment by pranavsharma** [comment]
Can you please try again in a fresh environment? Assuming all deps are in place and in path this should work.

**Comment by Serenaneres1** [comment]
[yolov5s.zip](https://github.com/microsoft/onnxruntime/files/9751517/yolov5s.zip)
The Model file here

**Comment by Serenaneres1** [comment]
> You need only 1 pkg for CPU+GPU inferencing: `onnxruntime-gpu`. Please uninstall `onnxruntime` pkg (which is meant for CPU only inferencing).
The code as follows:
import onnxruntime as ort
providers = ['CUDAExecutionProvider', 'CPUExecutionProvider']
w = 'yolov5s.onnx'
session = onnxruntime.InferenceSession(w, providers=providers)

**Comment by Serenaneres1** [comment]
When i change the CUDA 11.3 to CUDA11.1, no error occurs!

**Comment by oguz-hanoglu** [comment]
Replacing:
`import onnxruntime as rt`
with
`import torch`
`import onnxruntime as rt`
solved my problem.

**Comment by XZLancer** [comment]
> Replacing: `import onnxruntime as rt` with `import torch` `import onnxruntime as rt` solved my problem.

@oguz-hanoglu
Exactly solved my problem! Thank you very much and i’d like to know why import torch before onnxruntime fix this problem?

**Comment by oguz-hanoglu** [comment]
You are welcome :) The reason might be related to the fact that requirements include "CUDA" and "cuDNN" and these are installed within pytorch in conda(I use conda environments). Importing torch would be enabling CUDA/cuDNN in the kernel(I use VsCode Jupyter notebooks).

**Comment by kienld3049** [comment]
> Replacing: `import onnxruntime as rt` with `import torch` `import onnxruntime as rt` solved my problem.

thank you so much,  I've got this problem for 1 month. I did anything but didn't work. you are my hero.

**Comment by huknn** [comment]
when load model  ,true class_name=["a","b"]  ,but i class_name=["a"]  ,when i class_name=["a","b“]，the problem solved.

**Comment by kopyl** [comment]
Importing Torch helps. But we need a better solution since Torch takes a lot of time to load.

**Comment by Arcitec** [comment]
> I hate that this fixed it, but yes, importing `torch` before `onnxruntime` fixed it for me as well.

# Read this if you want to know why this issue happens:

The problem is that ONNX doesn't know how to search for CUDA. PyTorch knows how to search for it, and adds it to Python's internal path, so that ONNX can later find it.

The bug/issue is with ONNX library. I have coded a workaround here:

https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/238

**Comment by robinjoe93** [comment]
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

**Comment by Arcitec** [comment]
> export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

That doesn't work. It assumes one specific system, with one specific CUDA version, at this specific point in time. It will not work for you in the future, and it does not work for people today whose distro doesn't match yours.

My guide takes care of anyone both now and in the future on any distro:

https://github.com/microsoft/onnxruntime/issues/13264#issuecomment-2063073729
