### ISSUE TITLE
The same input outputs different results under the model of libtorch and onnxruntime

### ISSUE THREAD

**Issue by hctym1995** [microsoft/onnxruntime#13274]
### Describe the issue

1. I have exported some onnx models use torch.onnx.export()  in my Python codes
2. Then i try to use one of my onnx models to run LSTM, and i got a output data(a std::vector<Ort::Value>)
3. I converted my std::vector<Ort::Value> to at::tensor
4. I found that the output of the onnx lstm model is very different from the output of my original libtorch lstm
But I don't know where I am going wrong, is the model export wrong or the input parameters wrong? Or am I converting std::vector<Ort::Value> to at::tensor wrong? Can someone provide some troubleshooting tips idea?

### To reproduce

```cpp
at::Tensor OnnxValueVecToTorchTensor(std::vector<Ort::Value> &onnx_value_vector)
{
    const auto &output_tensor = onnx_value_vector.front();
    auto type_info = output_tensor.GetTensorTypeAndShapeInfo();
    auto elem_type = type_info.GetElementType();
    auto elem_count = type_info.GetElementCount();
    auto shape_info = type_info.GetShape();
    std::cout << "this onnx tensor's elem_count:" << elem_count << std::endl;
    std::cout << "this onnx tensor's shape info:[";
    for(auto a:shape_info)
    {
        std::cout << a << ",";
    }
    std::cout << "]" << std::endl;
    
    DataType_t datatype = static_cast<DataType_t>(elem_type);

    std::vector<float> onnx_out;
    for(int i = 0; i < elem_count; i++)
    {
        onnx_out.emplace_back(*(output_tensor.GetTensorData<float>()+i));
    }
    
    c10::IntArrayRef shape = c10::ArrayRef<int64_t>(shape_info.data(), shape_info.size());
    return torch::tensor(onnx_out).view(shape); 
}
```

### Platform

Linux

### OS Version

ubuntu18.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by faxu** [comment]
Which version of PyTorch are you using to export, and can you share your exported model?

**Comment by hctym1995** [comment]
> Which version of PyTorch are you using to export, and can you share your exported model?

Thank you for your reply. After a bit of debugging, my current progress is that the same onnx model outputs different results in the python and cpp environments. I will try to solve it myself first.
Bests.

**Comment by hctym1995** [comment]
> Which version of PyTorch are you using to export, and can you share your exported model?

Sorry to bother you, for some reason I have to convert between at::Tensor and std::vevtor<Ort::Value> through cpp codes, this is the code I converted, but I'm not sure if it's correct, can you please Can you provide some advice?
```cpp
void ShowOnnxTensor(std::vector<Ort::Value> &onnx_value_vector)
{
    const auto &output_tensor = onnx_value_vector.front();
    auto type_info = output_tensor.GetTensorTypeAndShapeInfo();
    auto elem_type = type_info.GetElementType();
    auto elem_count = type_info.GetElementCount();
    auto shape_info = type_info.GetShape();
    std::cout << "this onnx tensor's elem_count:" << elem_count << std::endl;
    std::cout << "this onnx tensor's shape info:[";
    for(auto a:shape_info)
    {
        std::cout << a << ",";
    }
    std::cout << "]" << std::endl;
}

at::Tensor OnnxValueVecToTorchTensor(std::vector<Ort::Value> &onnx_value_vector)
{
    ShowOnnxTensor(onnx_value_vector);
    const auto &output_tensor = onnx_value_vector.front();
    auto elem_count = output_tensor.GetTensorTypeAndShapeInfo().GetElementCount();
    std::vector<float> onnx_out;
    for(int i = 0; i < elem_count; i++)
    {
        onnx_out.emplace_back(*(output_tensor.GetTensorData<float>()+i));
    }
    
    auto shape_info = onnx_value_vector.front().GetTensorTypeAndShapeInfo().GetShape();
    c10::IntArrayRef shape = c10::ArrayRef<int64_t>(shape_info.data(), shape_info.size());
    return torch::tensor(onnx_out).view(shape); 
}

std::vector<Ort::Value> TorchTensorToOnnxValueVec(const at::Tensor &torch_tensor)
{
    auto onnx_tensor_type = ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_UNDEFINED;
    auto torch_tensor_type = torch_tensor.scalar_type();
    switch(torch_tensor_type)
    {
    case c10::ScalarType::Long:
        onnx_tensor_type = ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_INT64;
        break;
    case c10::ScalarType::Int:
        onnx_tensor_type = ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_INT32;
        break;
    case c10::ScalarType::Float:
        onnx_tensor_type = ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT;
        break;
    default:
        onnx_tensor_type = ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_INT64;
        break;
    }
    std::vector<Ort::Value> onnx_value_vector;
    onnx_value_vector.emplace_back(\
        Ort::Value::CreateTensor(g_memory_info, \
        torch_tensor.data_ptr(), torch_tensor.numel()*torch_tensor.element_size(), \
        torch_tensor.sizes().vec().data(), torch_tensor.sizes().vec().size(), \
        onnx_tensor_type
    ));
    ShowOnnxTensor(onnx_value_vector);
    return onnx_value_vector;
}
```

**Comment by pranavsharma** [comment]
The conversion code seems fine. I haven't verified it by running it. How different are the results between ORT and pytorch?

**Comment by hctym1995** [comment]
> The conversion code seems fine. I haven't verified it by running it. How different are the results between ORT and pytorch?
The inconsistency of the results at the beginning was caused by the wrong use of the model. Before the onnx lstm model is called, several conv onnx models need to be called. After correction, the results of ort and pytorch in the python environment are consistent, and this result is the same as that of pytorch. The results of libtorch in the cpp environment are consistent.
The current problem is that with the same input, the results of the ORT run under python and cpp are different.
Bests.

**Comment by hctym1995** [comment]
> The conversion code seems fine. I haven't verified it by running it. How different are the results between ORT and pytorch?

this is ORT python result:
0 onnx conv: tensor([[[0.43287665, 0.92264843, 0.85526216,  ..., 0.00000000,
          0.00000000, 0.00000000],
         [0.27830604, 0.00000000, 0.00000000,  ..., 0.00000000,
          0.00000000, 0.00000000],
         [1.05590820, 1.39529300, 0.00000000,  ..., 0.00000000,
          0.00000000, 0.28432399],
         ...,
         [1.13374209, 0.44391441, 0.00000000,  ..., 0.00000000,
          0.00000000, 0.32217979],
         [1.15626276, 1.04869151, 0.00000000,  ..., 0.94101638,
          0.00762467, 0.03260963],
         [0.64859706, 0.45960706, 0.00000000,  ..., 0.00000000,
          0.00000000, 0.00000000]]])

this is cpp result:
encoder_conv0_relu_onnx[1,512,11]
  0.4709   0.1469   0.0998   0.4865   0.2728   0.0000   0.1237   0.0906   0.0000   0.0000   0.2461
  0.1604   0.0588   0.0940   0.3608   0.3488   0.1654   0.2605   0.2648   0.0000   0.0000   0.5105
  0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.1670
  0.0000   0.1631   0.0000   0.0000   0.1277   0.2019   0.1033   0.0000   0.1317   0.0000   0.0295
  0.4988   0.4181   0.4021   0.4631   0.4670   0.0000   0.1707   0.2284   0.4618   1.1383   0.3019
  1.5579   0.2585   0.1957   0.0463   0.2401   0.1314   0.1272   0.0509   0.6904   0.3459   1.3164
  0.0000   0.1155   0.0000   0.0000   0.2443   0.0990   0.1295   0.1307   0.0000   0.0000   0.0088
  1.5135   0.0000   0.0000   0.1891   0.0052   0.0000   0.3858   0.3756   0.3510   0.8354   1.0246
  0.0000   0.3935   0.0299   0.0786   0.2099   0.2773   0.1651   0.1727   0.0000   0.1859   0.1207
  2.0392   1.0214   0.6895   0.0000   0.0000   0.0000   0.1529   0.1703   1.2075   0.0000   1.9541
 ...
  0.0000   0.1046   0.6367   0.0330   0.0174   0.5802   0.3907   0.0708   0.0000   0.0000   0.0000
  0.0000   0.2514   0.0000   0.2141   0.0036   0.0000   0.0000   0.0000   0.2058   0.4672   0.0000
  0.0000   0.5071   0.6065   0.2233   0.4113   0.0556   0.2508   0.2708   0.3172   0.8985   0.0000
  0.3024   0.0000   0.7308   0.3597   0.1212   0.0000   0.0643   0.2113   0.0000   0.0000   0.5955
  0.4909   0.0256   0.0000   0.2540   0.1258   0.0981   0.0963   0.1163   0.3354   0.0000   0.2759
  0.0000   0.0438   0.0000   0.2004   0.1052   0.0000   0.3342   0.2906   0.5349   0.5362   0.3120
  0.0000   0.4248   0.0000   0.0003   0.0000   0.2356   0.2680   0.0547   0.4824   0.0000   0.0000
  0.0000   0.0000   0.2561   0.3076   0.0244   0.0000   0.2349   0.4221   0.9033   1.3652   0.0000
  0.2761   0.0779   0.2201   0.0000   0.0132   0.1243   0.0000   0.0477   0.4711   0.0485   0.0766
  1.8727   0.5849   0.0000   0.0559   0.0375   0.0000   0.0560   0.1265   0.0000   0.1006   1.4216

Their input is the same, the onnx model used is the same, but the output tensor is very different

**Comment by hctym1995** [comment]
I think I have found a solution. The main reason is that when reading torch::tensor, the data is not read according to the dimension of tensor. After modifying my conversion code, I can get the correct result through onnx.
This is my new conversion code(relatively rough):
```cpp
//input_params is a torch::tensor, shape info is [1, 512, 11]
std::vector<int64_t> input_node_dims;
    for (int d=0; d<input_params.dim(); d++)
	{
		input_node_dims.emplace_back(input_params.sizes()[d]);
	}
    size_t input_tensor_size = input_params.numel(); 
    std::vector<float> input_tensor_values(input_tensor_size);
    auto index = 0;
    for(unsigned int i = 0; i < input_node_dims[0]; i++)
    {
        for(unsigned int j = 0; j < input_node_dims[1]; j++)
        {
            for(unsigned int k = 0; k < input_node_dims[2]; k++)
            {
                input_tensor_values[index++] = input_params[i][j][k].item<float>();
            }
        }
    }
        
    // create input tensor object from data values
    auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
    Ort::Value input_tensor = Ort::Value::CreateTensor<float>(memory_info, \
        input_tensor_values.data(), input_tensor_size, \
        input_node_dims.data(), input_node_dims.size());
    assert(input_tensor.IsTensor());
```
I will close issue, thanks all.
