### ISSUE TITLE
Shape inference is not working for some contrib operators

### ISSUE THREAD

**Issue by Alexey-Kamenev** [microsoft/onnxruntime#13279]
### Describe the issue

I'm trying to export my PyTorch model to ONNX and would like to use some of the ONNX [contrib operators](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md). For some of the operators, I'm getting the following warning:
```
The shape inference of [op_name] type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function
```
even when using `setType` when calling the operator. For others, the shape inference works fine even without `setType`.

How to enable shape inference for such operators?

### To reproduce

No warning, proper shape:
```py
import io
import onnxruntime
import torch
from torch.onnx import register_custom_op_symbolic, unregister_custom_op_symbolic, symbolic_helper

@symbolic_helper.parse_args("v", "s")
def my_gelu(g, self, approximate):
    # approximate must be none to use contrib implementation.
    assert approximate == "none"
    return g.op("com.microsoft::Gelu", self, approximate_s=approximate)

register_custom_op_symbolic('::gelu', my_gelu, 1)

class CustomGelu(torch.nn.Module):
    def forward(self, x):
        return torch.nn.functional.gelu(x, approximate="none")

x = torch.eye(2, 2)

with io.BytesIO() as f:
    torch.onnx.export(CustomGelu(), x, f, verbose=True)
    
unregister_custom_op_symbolic("::gelu", 1)
```

Graph:
```
graph(%com.microsoft::Gelu_0 : Float(2, 2, strides=[2, 1], requires_grad=0, device=cpu)):
  %1 : Float(2, 2, strides=[2, 1], requires_grad=0, device=cpu) = com.microsoft::Gelu[approximate="none", onnx_name="Gelu_0"](%com.microsoft::Gelu_0) # 
  return (%1)
```

Warning, no shape inference:
```py
import io
import onnxruntime
import torch
from torch.onnx import register_custom_op_symbolic, unregister_custom_op_symbolic

def my_inverse(g, self):
    return g.op("com.microsoft::Inverse", self).setType(self.type())

register_custom_op_symbolic('::inverse', my_inverse, 1)

class CustomInverse(torch.nn.Module):
    def forward(self, x):
        return torch.inverse(x)

x = torch.eye(2, 2)

with io.BytesIO() as f:
    torch.onnx.export(CustomInverse(), x, f, verbose=True)

unregister_custom_op_symbolic("::inverse", 1)
```

Graph:
```
graph(%com.microsoft::Inverse_0 : Float(2, 2, strides=[2, 1], requires_grad=0, device=cpu)):
  %1 : Float(*, *, strides=[1, 2], requires_grad=0, device=cpu) = com.microsoft::Inverse[onnx_name="Inverse_0"](%com.microsoft::Inverse_0) # 
  return (%1)
```

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU, CUDA

### Execution Provider Library Version

CUDA 11.7

**Comment by justinchuby** [comment]
Please feel free to open an issue on the pytorch repo where you should receive more help. Thanks!

**Comment by thiagocrepaldi** [comment]
@justinchuby either pytorch or onnxrutnime repo's issues related to ONNX are assigned to our team, so we could help him with an issue here, especially because there is a repro :)

@Alexey-Kamenev You can use the `setType` API to set shape and type as mentioned in the [poor documentation](https://github.com/pytorch/pytorch/blob/f3db2a634103690c6a87f5f34d29cd6c8b622a92/torch/onnx/utils.py#L1976-L1979).

You can also see an example with `setType` and custom op [here](https://github.com/pytorch/pytorch/blob/f3db2a634103690c6a87f5f34d29cd6c8b622a92/test/onnx/test_operators.py#L1189-L1219) and in several other tests at [shape inference unit tests](https://github.com/pytorch/pytorch/blob/master/test/onnx/test_pytorch_onnx_shape_inference.py)

**Comment by thiagocrepaldi** [comment]
resolving. user received proper doc reference to cimplement shape inference for contrib op
