### ISSUE TITLE
Are there any performance/benchmark numbers available to share?

### ISSUE THREAD

**Issue by hehaifengcn** [Microsoft/onnxruntime#133]
Particularly, performance comparison against different platforms (PyTorch, MXNet, TF). Also performance comparison among different hardware: cpu vs gpu(cuda) vs MKL-DNN.

**Comment by yufenglee** [comment]
We have a tool (https://github.com/Microsoft/onnxruntime/tree/master/onnxruntime/test/perftest) that can do performance measurement against a certain model. It's written in C++. For python, you can follow (https://github.com/Microsoft/onnxruntime/blob/master/onnxruntime/python/tools/onnxruntime_test.py) to measure the performance. For now, we don't provide official benchmark data and would like the users to do the performance comparison against the models that they are interesting in.

**Comment by mmxuan18** [comment]
> We have a tool (https://github.com/Microsoft/onnxruntime/tree/master/onnxruntime/test/perftest) that can do performance measurement against a certain model. It's written in C++. For python, you can follow (https://github.com/Microsoft/onnxruntime/blob/master/onnxruntime/python/tools/onnxruntime_test.py) to measure the performance. For now, we don't provide official benchmark data and would like the users to do the performance comparison against the models that they are interesting in.
@yufenglee does this tool support android / ios devices benchmark?
