### ISSUE TITLE
SSD-Resnet34 model load fails with CPU-MKL-DNN backend

### ISSUE THREAD

**Issue by minus-one** [microsoft/onnxruntime#1332]
**Describe the bug**
ssd-resnet34 onnx model fails to load on onnxruntime with mkl-dnn as backend. Fails with the following error:
```
    self._sess.load_model(path_or_bytes)
RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : This is an invalid model. Error: the graph is not acyclic.

```
The model loads correctly with onnxruntime as GPU as backend.
The model also loads correctly with a CPU backend from the pypi builds.
In all the cases it does throw warnings like
[W:onnxruntime:Default, graph.cc:2227 CleanUnusedInitializers]

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04
- ONNX Runtime installed from (source or binary):
source - master
- ONNX Runtime version:
0.4.0
- Python version:
3.6.8
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
7.4.0
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Describe steps/code to reproduce the behavior:
Download model from https://onnxzoo.blob.core.windows.net/models/opset_10/ssd/ssd.onnx
Run inside python 
import onnxruntime as rt
rt.InferenceSession('ssd.onnx')

**Expected behavior**
Model loads correctly.
**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by snnn** [comment]
@guschmue @jywu-msft FYI

**Comment by jywu-msft** [comment]
@sreekanth-yalachigere , can you please take a look? i'm assuming this is with your latest subgraph changes.

**Comment by guschmue** [comment]
Yes, I see the same on a resnet50. 
I have the same resnet50 in opset8 and that one is ok.
```export ORT_MKLDNN_SUBGRAPH=0``` will fix it but of course we'd want the subgraph.

**Comment by jywu-msft** [comment]
@sreekanth-yalachigere , can you take a look? seems like new opset is not being handled properly?

**Comment by sreekanth-yalachigere** [comment]
Yes. Working on it. Thank you

**Comment by sreekanth-yalachigere** [comment]
@guschmue Can you please provide me resnet50 model to test my fix?

**Comment by guschmue** [comment]
Easy to create by running:
```
wget https://zenodo.org/record/2535873/files/resnet50_v1.pb
pip install tf2onnx==1.5.2
python -m tf2onnx.convert --input resnet50_v1.pb --output resnet50_v1.onnx \
    --inputs-as-nchw input_tensor:0 \
    --inputs input_tensor:0 \
    --outputs ArgMax:0,softmax_tensor:0 --fold_const --verbose  --opset 10
```

**Comment by faxu** [comment]
@minus-one does the fix resolve the issue for you?

**Comment by minus-one** [comment]
Yes, it does. Sorry for the delayed confirmation.
