### ISSUE TITLE
[Build] CUDA build failed with CUDA 11.8, VS 2022, Windows 10

### ISSUE THREAD

**Issue by tianleiwu** [microsoft/onnxruntime#13374]
### Describe the issue

Failed to build cuda package in windows with CUDA 11.8, cuDNN 8.6

### Target platform

Windows

### Build script

build.bat --config Debug --build_shared_lib --parallel --cmake_generator "Visual Studio 17 2022" --use_cuda --cuda_version  11.8 --cuda_home C:\CUDA\v11.8 --cudnn_home C:\CUDA\v11.8 --build_wheel  --gen_doc --gen-api-doc

### Error / output

E:\git\onnxruntime\onnxruntime\gsl\gsl-lite.hpp(1147): error : device code does not support exception handling [E:\git\onnxruntime\build\Windows\Debug\onnxruntime_providers_cuda.vcxproj]
            detected during instantiation of "T gsl::narrow<T,U>(U) [with T=size_t, U=int64_t]"
  E:\git\onnxruntime\onnxruntime\core/providers/cpu/tensor/utils.h(210): here

E:\git\onnxruntime\onnxruntime\gsl\gsl-lite.hpp(1161): error : device code does not support exception handling [E:\git\onnxruntime\build\Windows\Debug\onnxruntime_providers_cuda.vcxproj]
            detected during instantiation of "T gsl::narrow<T,U>(U) [with T=size_t, U=int64_t]"
  E:\git\onnxruntime\onnxruntime\core/providers/cpu/tensor/utils.h(210): here

  2 errors detected in the compilation of "E:/git/onnxruntime/onnxruntime/contrib_ops/cuda/math/complex_mul_impl.cu".

### Visual Studio Version

Microsoft Visual Studio Professional 2022 (64-bit)

### GCC / Compiler Version

VS 2022 Version 17.3.6

**Comment by EmreOzkose** [comment]
Hi, I am also trying to build. Are you sure if `cudnn_home` is `C:\CUDA\v11.8`? What does `C:\CUDA\v11.8` contain ?

**Comment by tianleiwu** [comment]
@EmreOzkose, I copied cudnn into cuda directory. Of course, you can separate CUDA and cuDNN to different folders.

**Comment by tianleiwu** [comment]
I had to remove CUDA 11.8 and install 11.7 to avoid such build error.
