### ISSUE TITLE
HuggingFace stable-diffusion-v1-4 inference failed with DML EP

### ISSUE THREAD

**Issue by skyline75489** [microsoft/onnxruntime#13379]
### Describe the issue

The inference session failed with the following error:

```text
2022-10-20 14:22:17.2149975 [E:onnxruntime:, sequential_executor.cc:368 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running InstanceNormalization node. Name:'InstanceNormalization_172'
```

### To reproduce

```python
from diffusers import StableDiffusionOnnxPipeline

model_id = "CompVis/stable-diffusion-v1-4"
prompt = "a photo of an astronaut riding a horse on mars"

sess = StableDiffusionOnnxPipeline.from_pretrained(model_id, provider='DmlExecutionProvider')
sess(prompt)
```

### Urgency

N/A

### Platform

Windows

### OS Version

10.0.22623.746

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

DirectML

### Execution Provider Library Version

Raedon RX570

**Comment by skyline75489** [comment]
I see a spike in GPU memory usage. The failure is possibly due to low GPU memory.

**Comment by fdwr** [comment]
@skyline75489 Does this still repro for you? I've been running SD 1.5 with ORT+DML EP for a few months now (different GPU though).

**Comment by skyline75489** [comment]
I'm not actively testing DML for now. Feel free to close this issue. Thanks for the response 😃

**Comment by fdwr** [comment]
Well if you *do* someday try it again, it should work better now 🤞🙂 (many optimizations went in since then). Closing...
