### ISSUE TITLE
[Performance] InferenceSession crashes 

### ISSUE THREAD

**Issue by yehudit96** [microsoft/onnxruntime#13370]
### Describe the issue

The SO works great when I add only one initializer, but when I add two or more initializers, I encounter the following runtime error:
```
Traceback (most recent call last):
  File " AppData\Roaming\Python\Python39\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File " AppData\Roaming\Python\Python39\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\include\onnxruntime\core/framework/ort_value.h:102 OrtValue::Get IsTensor() was false. Trying to get a Tensor, but got: (null)  
```

I have attached the relevant code I am running. The exception occurred at the end of the code

The code iterates a list of params:
1.	creates random OrtValue instance based on the param shape
2.	adds the OrtValue to the SO
After adding all parameters, create an InferenceSession with the SO

In order to isolate the exception cause, I added only one param to the SO and created an InferenceSession for each param (did this for each param in params). As a result, it works without any problems, indicating that the problem is not related to a specific parameter.
Only when len(params) > 1 this exception occurs.

To reproduce the bug, download the zip 
[net1.zip](https://github.com/microsoft/onnxruntime/files/9820195/net1.zip)
file and extract it, you need the path of net1.onnx

### To reproduce

```python
import onnxruntime
import numpy as np
params = {"fc1.weight": [3, 4], "fc1.bias": [3]}
options = onnxruntime.SessionOptions()
for p, dim in list(params.items()):
    ortvalue_initializer = onnxruntime.OrtValue.ortvalue_from_numpy(
        np.float32(np.random.rand(*dim))
    )
    options.add_initializer(p, ortvalue_initializer)

onnx_ner2 = net_session = onnxruntime.InferenceSession(
            'net1.onnx',
            sess_options=options,
            providers=["CPUExecutionProvider"])
```

### Urgency

high, it is blocking a production release

### Platform

Windows

### OS Version

Windows 11 Enterprise

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Is this a quantized model?

No

**Comment by pranavsharma** [comment]
I don't think this is a threadpool issue. Why would it fail for 2 initializers and not 1? Besides the error returned is completely different. I'll look into this.

**Comment by yuslepukhin** [comment]
> I don't think this is a threadpool issue. Why would it fail for 2 initializers and not 1? Besides the error returned is completely different. I'll look into this.

I agree

**Comment by pranavsharma** [comment]
@yehudit96 - in your code the initializers go out of scope when you exit the for loop and hence the pointers may not be valid by the time session is constructed. You need to keep the initializers around until you're done with the session. Following works.
`
import onnxruntime
import numpy as np

params = {"fc1.weight": [3, 4], "fc1.bias": [3]}
options = onnxruntime.SessionOptions()
ortvalue_initializers = []
for p, dim in list(params.items()):
    ortvalue_initializers.append(onnxruntime.OrtValue.ortvalue_from_numpy(
        np.float32(np.random.rand(*dim))
    ))
    options.add_initializer(p, ortvalue_initializers[-1])

net_session = onnxruntime.InferenceSession(
    'net1.onnx',
    sess_options=options,
    providers=["CPUExecutionProvider"])

input = np.random.random((1,4)).astype('f')
output = net_session.run(["output"], {"input": input})
print(output)
`

**Comment by aribornstein** [comment]
That worked thank you @pranavsharma for the quick resolution.
