### ISSUE TITLE
[Web]  Uncaught (in promise) 12768952

### ISSUE THREAD

**Issue by josephrocca** [microsoft/onnxruntime#13383]
### Describe the issue

The error message "Uncaught (in promise) 12768952" is logged to the console when running inference on [this model](https://huggingface.co/rocca/lyra-v2-soundstream/resolve/main/onnx/soundstream_encoder.onnx) with ORT Web.

This model was converted from a tflite model using [this notebook](https://colab.research.google.com/gist/josephrocca/401efe82bf18ffe93d5f3deca7ed7515/notebook.ipynb) - there were no errors or warnings. There were [some initial conversion troubles](https://github.com/onnx/tensorflow-onnx/issues/2059), but after some fixes (see that issue for details), the conversion process appears to be fixed.

### To reproduce

Minimal example: https://jsbin.com/finulodeji/edit?html,output

Full code from that example, for quick reference:
```html
  <script src="https://cdn.jsdelivr.net/npm/onnxruntime-web@1.12.1/dist/ort.js"></script>
  <script>
    async function start() {
      console.log("Loading model...")
      let session = await ort.InferenceSession.create("https://huggingface.co/rocca/lyra-v2-soundstream/resolve/main/onnx/soundstream_encoder.onnx", { executionProviders: ["wasm"] });
      console.log("Running inference");
      let feeds = {"serving_default_input_audio:0": new ort.Tensor('float32', new Float32Array(320).fill(0), [1,320])};
      let results = await session.run(feeds);
      console.log("Results:", results);
    }
    start();
  </script>
```

### Urgency

No strict deadlines. It is blocking the process of trying to get [Google's new Lyra V2 model](https://opensource.googleblog.com/2022/09/lyra-v2-a-better-faster-and-more-versatile-speech-codec.html) working in the browser.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.1

### Execution Provider

WASM

**Comment by josephrocca** [comment]
I'm wondering if it's possible for a "debug" build to be published which makes error messages like this more informative? Just something like:
```
https://cdn.jsdelivr.net/npm/onnxruntime-web@1.12.1/dist/ort-debug.js
```
so it's easy to switch in and out of debug mode. That is, assuming it's possible to configure build flags to make error messages like these more informative.

**Comment by shalvamist** [comment]
Hey @josephrocca,

Thanks for reporting the issue in such detail.
I was able to reproduce the issue on my side - I will investigate the problem and update you with my findings.

BTW, regarding this debug build - I will see what we can do. In the meanwhile just FYI we are working on simplifying the ORT Web build process. But please refer to [ORT Web build instructions] (https://onnxruntime.ai/docs/build/web.html)

**Comment by iishiishii** [comment]
I got similar error. The session was created but failed to run for [this model](https://huggingface.co/iishiishii/brain_mask/resolve/main/model.onnx) with onnxruntime-web. The inference in python works just fine.

**Comment by abb128** [comment]
I'm getting a similar error with my own models. Two of my models are working fine, but the third one logs an error like this with a random number each time, regardless of what inputs I give it.

**Comment by shalvamist** [comment]
Hey Everyone,

Sorry for the delay in response. We have some progress on the issue - I was able to find that the model might has issues to run with ORT. here is the error - 

> onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'streamable_model_12/first_layerconv/conv1d_36/BiasAdd;streamable_model_12/first_layerconv/conv1d_36/Conv1D/Squeeze;streamable_model_12/first_layerconv/conv1d_36/BiasAdd/ReadVariableOp;Conv1D;streamable_model_12/first_layerconv/conv1d_36/Conv1D__39' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:41 onnxruntime::ReshapeHelper::ReshapeHelper gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,320,1}, requested shape:{1,1,1,368}

There might be an issue with the conversion - @josephrocca, where you able to run the model on ORT without ORT Web?
I am continuing to debug the issue but if you have a working set up it will help to isolate the problem.

In regards of the broader issue of exception handling, we are aware of the limited debugging capabilities with the current build, and we are examining different ways to address the problem. Right now, we know how to retrieve the debug messages, but it requires a re-build. Our team is looking at a few option that might resolve the problem and how enable exception throwing will impact ORT Web. I will update soon with the decision - and I will also update (https://github.com/microsoft/onnxruntime/issues/13408).

Thanks

**Comment by josephrocca** [comment]
Hi @shalvamist, I've just tested it and am seeing the same error in ORT Python. Here's a minimal reproduction:

https://colab.research.google.com/gist/josephrocca/91e876fd90e6b7c88429258ba2384a36/onnx-runtime-python-inference.ipynb

But I think the particular problem in my case may be due to a tf2onnx conversion issue. Please see [this comment](https://github.com/onnx/tensorflow-onnx/issues/2059#issuecomment-1296301499) and the ones above it for more context.

**Comment by shalvamist** [comment]
Hi @josephrocca,

Thanks for sharing the colab, this aligns with my findings. (The errors match)
Since you already have an ongoing discussion on the conversion it seems like the right place to resolve the issue.
I will update this thread with the upcoming PR regarding exception handling. Please let me know if you need anything else related to the issue or ORT Web.

**Comment by josephrocca** [comment]
Thanks @shalvamist - the other commenters likely having different issues so I'm reluctant to close, but I think this is best tracked at #13408? I'll close it and let you re-open if needed.

**Comment by xiaohk** [comment]
I had a similar issue. Updating v0.1.3 to v0.1.4 fixed it for me!
