### ISSUE TITLE
[Web] InferenceSession.dispose method is not exposed

### ISSUE THREAD

**Issue by gcampax** [microsoft/onnxruntime#13391]
### Describe the issue

ONNXRuntime WASM backend will create native resources in WASM memory every time an InferenceSession is created. These resources are addessed by sessionId and retained until explicitly disposed by the user, but the `dispose` method is not exposed on InferenceSession, so it is not possible to actually dispose of InferenceSession properly and release memory.

### To reproduce

See above. The `dispose` method is present in OnnxruntimeWebAssemblyBackend but not in InferenceSession or InferenceSessionImpl. Memory release is not possible.

### Urgency

This affects long running web processes - such as browser extensions - that want to periodically update a model by creating a new InferenceSession. Eventually they run out of memory and session creation fails.
It is possible to work around the issue by overriding TypeScript and calling `session.handler.dispose()`, but this is a hack that uses undocumented APIs, so I'd rather not do that.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

onnxruntime-web@npm:1.12.1

### Execution Provider

WASM

**Comment by luxaritas** [comment]
I believe this was implemented in #16169
