### ISSUE TITLE
[Web] ONNX Runtime throws undescriptive exception

### ISSUE THREAD

**Issue by gcampax** [microsoft/onnxruntime#13408]
### Describe the issue

In the default configuration published to NPM, ONNX Runtime is compiled without exception support in emscripten, but it still makes heavy of use of C++ exceptions. As a result, it still calls into emscripten C++ exception code, which is stubbed out, and throws the C++ exception pointer as a JS exception (without even wrapping it into a WebAssembly.Exception or JS Error).
The C++ exception pointer appears a bare number, and it lacks context (stack) or even an error message, so it is essentially useless to debug what is going wrong.

I think ONNX Runtime should either compile with emscripten exceptions enabled (given it makes use of C++ exceptions), or it should disable C++ exceptions completely, and report errors in a different way that preserves error message.
Compiling with native WASM exceptions would be best, as it gives best performance and best observability. It is supported by all recent browsers: https://webassembly.org/roadmap/

### To reproduce

There are different ways to trigger C++ exceptions, and I don't know all of them (if I did, I could guard against all of them, and avoid this issue entirely). One way I know of is to pass an input that is too large for the model, which triggers a C++ exception in BroadcastIterator. Another way is to run out of WASM memory, which causes std::bad_alloc.

### Urgency

This issue makes it very hard to deploy ONNX Runtime in production, because without observability if errors occur one is stuck with no debugging options, but the alternative is to deploy a custom debug build, which does not seem appropriate for production.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

onnxruntime-web@npm:1.12.1

### Execution Provider

WASM

**Comment by gcampax** [comment]
This issue is in fact the same as #12622 and #13383

**Comment by josephrocca** [comment]
I very much agree with this. I have very little C++/emscripten experience, so I'm not sure what the performance/file-size implications would be, but if the performance impact is non-trivial, then an `ort-debug.js` file (along with associated wasm files) could be published alongside the normal `ort.js`, so it's easy to switch in and out of debug mode.

**Comment by shalvamist** [comment]
Hi,

Sorry for the late response. We agree that there is a gap here that needs to be addressed. 
The team is examining different ways to resolve the problem. We are looking at a few options that will minimize impact on ORT Web and enable exception handling. We are exploring a few options and I will update soon with our findings.

Thanks

**Comment by guschmue** [comment]
this should be fixed in 1.14.
