### ISSUE TITLE
Support for Intel Compiler

### ISSUE THREAD

**Issue by joyIntel** [microsoft/onnxruntime#1341]
I am trying to build onnxruntime using Intel compiler with the following commands -

git clone https://github.com/microsoft/onnxruntime.git
cd onnxruntime
git submodule update –-init -–recursive
mkdir build
cd build
cmake -A x64 -G "Visual Studio 15 2017" -T "Intel C++ Compiler 19.0" ..\cmake
msbuild "onnxruntime.sln" /t:Rebuild /p:Configuration=Release /m

I am getting the following error. 
![compile_error](https://user-images.githubusercontent.com/39498824/60626679-6832d200-9da0-11e9-9bd6-a292d3c8bee6.png)

All those errors seem to come from static_assert(std::is_pod::value, ...). There is no way to find the exact templates from static_assert() because the second argument must be a string literal.

I am assuming the followings may cause the trouble -

onnxruntime\cmake\external\re2\util\sparse_arry.h - `PODArray <IndexValue>`
onnxruntime\cmake\external\re2\re2\simplify.cc - `PODArray<Regexp*>`
onnxruntime\cmake\external\re2\re2\set.cc - `PODArray<re2::Regexp*>`
onnxruntime\cmake\external\protobuf\src\google\protobuf\extension_set.cc - `CreateArray<KeyValue>`

There are some templates which are considered as POD by MSVC but not ICC.

Any help would be highly appreciated.

**Comment by faxu** [comment]
@joyIntel were you able to resolve this issue?
