### ISSUE TITLE
Unable to load DLL 'onnxruntime_providers_shared.dll': The specified module could not be found.

### ISSUE THREAD

**Issue by MuliMuri** [microsoft/onnxruntime#13439]
### Describe the issue

Hello.
When I try to run the program, it always reports an error. But the dll does exist in the compilation directory

Thank you. :)

### To reproduce

```
public Deeplabv3(string modelPath)
{
     this.model = new InferenceSession(modelPath, SessionOptions.MakeSessionOptionWithCudaProvider(0));
}
```

### Urgency

Within 3 days.

### Platform

Windows

### OS Version

Windows 10 21H2

### ONNX Runtime Installation

Other / Unknown

### ONNX Runtime Version or Commit ID

NuGet 1.13.1

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA Version: 11.6

**Comment by snnn** [comment]
Duplicated with #10563

**Comment by snnn** [comment]
And please note CUDA 11.6 depends on zlib. You need to install zlib DLLs as well.

**Comment by MuliMuri** [comment]
> And please note CUDA 11.6 depends on zlib. You need to install zlib DLLs as well.

Thanks your reply.
But this library still can't import my program.
I don't know why there is such a problem. Maybe is the dllname problem? (ANSI or Unicode?)

**Comment by MuliMuri** [comment]
> > And please note CUDA 11.6 depends on zlib. You need to install zlib DLLs as well.
> 
> Thanks your reply. But this library still can't import my program. I don't know why there is such a problem. Maybe is the dllname problem? (ANSI or Unicode?)

Maybe is not CUDA version problem
Because I can't load the dll
(The program has not been executed to cuda)

**Comment by snnn** [comment]
Which line of code threw the error?

**Comment by MuliMuri** [comment]
> SessionOptions.MakeSessionOptionWithCudaProvider(0)

SessionOptions.MakeSessionOptionWithCudaProvider(0)
This one,
This is screenshot

![image](https://user-images.githubusercontent.com/44513759/198250907-d8d13ea3-5369-475d-8623-bbea82e98c1b.png)

But, in this directory, exist the dll
![image](https://user-images.githubusercontent.com/44513759/198251218-52287226-cc67-4e73-aaf1-4d0363185992.png)

I tried to find the solution in souce code, but nothing found

**Comment by snnn** [comment]
Would you mind to run your application with windbg so that we could know which DLL failed to load? Without more information, I can't tell you what went wrong.

**Comment by CanyonWind** [comment]
Hi @snnn, thanks for your help on both this thread and the one you posted earlier. I've met the same error and am 
 investigating with windbg. 

Windbg could run my test script but there seems not to be any related lines about "LdrpProcessWork - ERROR: Unable to load DLL" in the [log](https://github.com/microsoft/onnxruntime/files/9976195/windbg_log.txt). At the same time, python output still throws the same error:
```
2022-11-09 16:22:50.5725246 [E:onnxruntime:Default, provider_bridge_ort.cc:1269 onnxruntime::TryGetProviderInfo_CUDA] C:\Users\user\projects\onnxruntime.cuda\onnxruntime\core\session\provider_bridge_ort.cc:1072 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\user\projects\test\env\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2022-11-09 16:22:50.5811151 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:579 onnxruntime::python::CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
```

I also used the dependency walker to identify the onnxruntime_providers_cuda.dll dependencies (screenshot attached). It seems able to locate all the other dlls.

Any thoughts on where I did wrongly? Thanks a lot

![image](https://user-images.githubusercontent.com/8852730/200970760-265a429d-a1d1-4a0d-8f3d-3ad1530aa382.png)

**Comment by snnn** [comment]
I don't recommend using dependency walker. I can't provide any help for the software.

**Comment by CanyonWind** [comment]
Sorry for the confusion, the dependency walker screenshot is just attached as another reference. I investigated with windbg tool and the windbg output log is [here](https://github.com/microsoft/onnxruntime/files/9976195/windbg_log.txt).  

The debug tool throws the error `FAIL : LoadLibrary failed with error 126` but the log doesn't contain any `LdrpProcessWork - ERROR: Unable to load DLL` related error as you suggested in [the other post](https://github.com/microsoft/onnxruntime/issues/10563). Any suggestions on this would be much appreciated.

**Comment by RealSoulS** [comment]
楼主解决了嘛= =

**Comment by MuliMuri** [comment]
> 
过了好久了，忘了，我记得好像是重新导出了模型，这东西挺神（xie）奇（men）的，同个模型同样参数有时候导出能用有时候就用不了

**Comment by MuliMuri** [comment]
> 楼主解决了嘛= =

过了好久了，忘了，我记得好像是重新导出了模型，这东西挺神（xie）奇（men）的，同个模型同样参数有时候导出能用有时候就用不了
