### ISSUE TITLE
[Web] Failed to load ONNX model: Error: Aborted(). Build with -sASSERTIONS for more info.

### ISSUE THREAD

**Issue by josephrocca** [microsoft/onnxruntime#13445]
### Describe the issue

When attempting to load [this large model](https://huggingface.co/rocca/rwkv-4-pile-web/resolve/main/169m/rwkv-4-pile-430m.onnx) (~1.6GB) with ORT Web I get this error:
```
Uncaught (in promise) RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
```
I'm using `1.13.2` which should allow up to 4GB of memory, so I'm guessing this isn't a memory capacity problem, but I guess it could be if there are a lot of unnecessary(?) allocations?

This is also logged as a warning:
```
b.<computed> | @ | runner-4.1.8.min.js:1
-- | -- | --
  | G | @ | ort.js:802
  | d | @ | ort.js:819
  | $func40 | @ | ort-wasm-simd.wasm:0x931b
  | $func44 | @ | ort-wasm-simd.wasm:0x9789
  | $func113 | @ | ort-wasm-simd.wasm:0xf79a
  | $func429 | @ | ort-wasm-simd.wasm:0x35be2
  | $func1793 | @ | ort-wasm-simd.wasm:0x131aca
  | $func1103 | @ | ort-wasm-simd.wasm:0xa66e1
  | $func2344 | @ | ort-wasm-simd.wasm:0x1aa6ae
  | $func3823 | @ | ort-wasm-simd.wasm:0x319ade
  | $func5777 | @ | ort-wasm-simd.wasm:0x47cdf4
  | $func1811 | @ | ort-wasm-simd.wasm:0x138a51
  | $func1347 | @ | ort-wasm-simd.wasm:0xe6f5f
  | $func5672 | @ | ort-wasm-simd.wasm:0x475f36
  | $U | @ | ort-wasm-simd.wasm:0x64100c
  | b._OrtCreateSession | @ | ort.js:825
  | createSession | @ | ort.js:28246
  | createSession | @ | ort.js:27831
  | loadModel | @ | ort.js:27987
  | await in loadModel (async) |   |  
  | createSessionHandler | @ | ort.js:11362
  | await in createSessionHandler (async) |   |  
  | create | @ | ort.js:429
  | await in create (async) |   |  
  | (anonymous) | @ | runner:4
  | (anonymous) | @ | runner:6
```

### To reproduce

https://jsbin.com/cotimemilo/edit?html,output

```html
  <script src="https://cdn.jsdelivr.net/npm/onnxruntime-web@1.13.1/dist/ort.js"></script>
  <script>
    (async function() {
      
      let session = await ort.InferenceSession.create("https://huggingface.co/rocca/rwkv-4-pile-web/resolve/main/430m/rwkv-4-pile-430m.onnx", {executionProviders: [ "wasm" ]});
    
    })();
  </script>
```

### Urgency

No hard deadlines.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### Execution Provider

WASM

**Comment by guschmue** [comment]
that model once unpacked is a little over 2GB but during model load with have it twice in memory so even with 4GB it doesn't fit. One could try the .ort format that would have some memory. 
But it is sure a large model for a browser - the poor cache!

**Comment by josephrocca** [comment]
Thanks for your reply! Is it necessary to have it twice in memory?

Yeah, the model is big! But it's surprisingly possible to run large models at reasonable speeds in the browser these days (thanks to ORT and friends) - e.g. https://josephrocca.github.io/rwkv-v4-web/demo

If it's not to hard to avoid loading models into memory twice, then that would be great! Otherwise I guess Wasm Memory64 will solve this when that eventually lands in browsers.

**Comment by guschmue** [comment]
for the regular onnx files we need to those 2 copies.
The .ort files are flatbuffers and we should be able to use the initializers without copy.
Needs some extra session options:
```
  const sessionOption = {
    executionProviders: ["wasm"],
    enableMemPattern: false,
    enableCpuMemArena: false,
    extra: {
      session: {
        disable_prepacking: "1",
        use_device_allocator_for_initializers: "0",
        use_ort_model_bytes_directly: "1",
        use_ort_model_bytes_for_initializers: "1"
      }
    }
```

**Comment by josephrocca** [comment]
That works - thanks! For those coming across this thread in the future, I installed ONNX Runtime with pip, and then ran this:
```
python -m onnxruntime.tools.convert_onnx_models_to_ort myOriginalModel.onnx
```
And then I used `myOriginalModel.with_runtime_opt.ort` to create an inference session using the session options given above.

**Comment by guschmue** [comment]
thanks for trying!
