### ISSUE TITLE
System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe,

### ISSUE THREAD

**Issue by oohlala1204** [microsoft/onnxruntime#1344]
When I load the onnx model in the ASP.NET application, an error occurred:
```
System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference
```
It seems that the vision of  "System.Runtime.CompilerServices.Unsafe.dll" is wrong.

 I install the onnx runtime via NuGet, and here the onnx runtime is installed as a package reference. 
In the csproj file, I find that:
```
    <PackageReference Include="Microsoft.ML.OnnxRuntime">
      <Version>0.4.0</Version>
    </PackageReference>
```
The "System.Runtime.CompilerServices.Unsafe.dll"  isn't included in the .csproj file.

Compared with the aforementioned error,  when I load the onnx model in the C# console application,  it runs normally.  I also install the onnx runtime via NuGet. But in the .csproj file, the references are arranged separately, and I find :
```
    <Reference Include="System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\packages\System.Runtime.CompilerServices.Unsafe.4.5.0\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
    </Reference>
```
Any help would be appreciated.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win 10
- ONNX Runtime installed from (source or binary): NuGet
- ONNX Runtime version: 0.4.0
- Python version:
- Visual Studio version (if applicable): VS2017
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by jignparm** [comment]
> The located assembly's manifest definition does not match the assembly reference

The message above means the linker found a `System.Runtime.CompilerServices.Unsafe.dll` somewhere in the load path, but it happens to be the incorrect version needed by the project. Does a clean build fix the error? Delete all output folders , and also remove any stale  OnnxRuntime packages in the NuGet cache folder. The NuGet cache folder location varies -- for .NetFramework projects, all DLLs are copied to a folder called **packages** alongside your project. For .NetCore projects, they are stored centrally under C:\Users\username\\.nuget\packages folder.

**Comment by jignparm** [comment]
@oohlala1204 , I was able to create an Inference session in an ASP.NET app successfully using the steps below. You can compare your project with the one generated by the dotnet command to see what the difference is.

* create project -> `dotnet new webApp -o myWebApp --no-https`
* `cd myWebApp`
* Edit **myWebApp.csproj** file to include the following
```c#
<PackageReference Include="Microsoft.ML.OnnxRuntime" Version="0.4.0" />
```
* Edit **Program.cs**  to something like below
```c#
        public static void Main(string[] args)
        {
            using (var session = new InferenceSession(@"d:\models\squeezenet\1.2\model.onnx"))
            {
                Console.Write("****hello world ****");
            }
            CreateWebHostBuilder(args).Build().Run();
        }
```
* run using `dotnet run`, to get the following log
```
D:\usingonnxruntime\asp\myWebApp>dotnet run
Using launch settings from D:\usingonnxruntime\asp\myWebApp\Properties\launchSettings.json...
****hello world ****
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\localadmin\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Development
Content root path: D:\usingonnxruntime\asp\myWebApp
Now listening on: http://localhost:5000
```

**Comment by jignparm** [comment]
Closing this out. Please reopen if this is still an issue (with some minimalist steps to repro).
