### ISSUE TITLE
Performance optimization using inplace

### ISSUE THREAD

**Issue by xadupre** [microsoft/onnxruntime#1348]
**Description**

When the output of one node is used by only one another (activation function in a neural network), the runtime is sure that this output will only be used once and it reuse the same container instead of allocating a new one. This information could be stored in OpKernelContext so that it is available in method Compute.of every node implementation. Many allocations could be avoided and the cost of small operators should be reduced (Add, Sub, Divide, …) in that particular case.

**Describe the solution you'd like**

Add a boolean *inplace* in OpKernelContext determined for each node by InferenceSession.

**Describe alternatives you've considered**

Add an attribute to all method Compute but it requires to change many files.

**Comment by linkerzhang** [comment]
is this all about memory reuse please? I think in your case, our memoryplanner is doing the job. @gramalingam

**Comment by yuanbyu** [comment]
It is in KernelDef. It is an attribute on a particular kernel, which provides the contract to reason about the memory uses.

**Comment by gramalingam** [comment]
Yes, the infrastructure for doing this already exists. If some specific opkernel is not doing this and could do it, we should update that specific opkernel's registration to achieve it.

**Comment by xadupre** [comment]
Are you referring to MayInplace? It seems to indicate that one output may be written at the same location than one input. I did not see that for binary operators Add, Sub… One input could be rewritten by the output.

**Comment by yuanbyu** [comment]
I don't understand your comment. For Add, MayInplace(0, 0) means output 0 shares input 0, MayInplace(1, 0) means output 0 shares with input 1.

**Comment by xadupre** [comment]
I'm confused about the way it works then. The best option, MayInplace(0, 0) or MayInplace(1, 0) can only be determined when the graph is defined. Is there a way to find the list of operators which supports that option and to know when onnxruntime activates it?
