### ISSUE TITLE
The question of computation of GetErfGradient in gradient_builder.cc

### ISSUE THREAD

**Issue by rGitcy** [microsoft/onnxruntime#13512]
### Describe the documentation issue

In the page:
https://github.com/microsoft/onnxruntime/blob/df712d80ca33b56ce7d63ca3acdb6a4888638c58/orttraining/orttraining/core/graph/gradient_builder.cc?from_wecom=1#L119

ii found the compuation 'NodeDef("Mul", {GO(0), IA("Mul_Exp_Neg_Squared_X")}, {GI(0)})'of "GetErfGradient" is not match to the formual of "erf" as follows:
![image](https://user-images.githubusercontent.com/8943172/198950403-c6c13609-94cd-4439-8d1f-1eacbacc2265.png)

please check it!

### Page / URL

https://github.com/microsoft/onnxruntime/blob/df712d80ca33b56ce7d63ca3acdb6a4888638c58/orttraining/orttraining/core/graph/gradient_builder.cc?from_wecom=1#L119

**Comment by baijumeswani** [comment]
From what I am reading in the code, the gradient is exactly the same as described in the equation. Commented code for clarity:

```cc
ArgDef X = I(0);
std::vector<NodeDef> result;

NodeDef two_sqrt_pi_node = ConstantScalarNode(static_cast<float>(M_2_SQRTPI), Name("Two_Sqrt_Pi"), IElemType(0));
ArgDef two_sqrt_pi_arg = two_sqrt_pi_node.output_args[0];

// 2/sqrt(pi) = 1.12837916709551257390
result.push_back(two_sqrt_pi_node);

// x*x
result.push_back(NodeDef("Mul", {X, X}, {IA("Squared_X")}));

// -(x*x)
result.push_back(NodeDef("Neg", {IA("Squared_X")}, {IA("Neg_Squared_X")}));

// e^(-(x*x))
result.push_back(NodeDef("Exp", {IA("Neg_Squared_X")}, {IA("Exp_Neg_Squared_X")}));

// (2/sqrt(pi)) * (e^(-(x*x)))
result.push_back(NodeDef("Mul", {two_sqrt_pi_arg, IA("Exp_Neg_Squared_X")}, {IA("Mul_Exp_Neg_Squared_X")}));

// chain rule - gradient of input = gradient of output * (2/sqrt(pi)) * (e^(-(x*x)))
result.push_back(NodeDef("Mul", {GO(0), IA("Mul_Exp_Neg_Squared_X")}, {GI(0)}));


return result;
```

cc @iK1D @pengwa

**Comment by baijumeswani** [comment]
I think this can be closed. @rGitcy feel free to add more questions (and re-open) if you think the answer provided does not add up.

**Comment by gjm441** [comment]
Maybe the last operator is div, not mul, according to the chain rule.

**Comment by rGitcy** [comment]
> Maybe the last operator is div, not mul, according to the chain rule.

i argee with you!

**Comment by rGitcy** [comment]
> I think this can be closed. @rGitcy feel free to add more questions (and re-open) if you think the answer provided does not add up.

thx. But i think the last operator is div, not mul according to the differentiation formulas of erf. please check it.

**Comment by baijumeswani** [comment]
forward graph:

x->erf->output

output = erf(x)

backward graph:

gradient_of_output -> erf_grad -> gradient_of_x

chain rule
gradient_of_x = gradient_of_output * erf_grad(x)

**Comment by rGitcy** [comment]
> ```c++
> gradient of input = gradient of output * (2/sqrt(pi)) * (e^(-(x*x)))
> ```

thx. i get it!

**Comment by gjm441** [comment]
> forward graph:
> 
> x->erf->output
> 
> output = erf(x)
> 
> backward graph:
> 
> gradient_of_output -> erf_grad -> gradient_of_x
> 
> chain rule gradient_of_x = gradient_of_output * erf_grad(x)

![image](https://user-images.githubusercontent.com/22522161/199135980-2c58fb82-00ed-44d4-93b4-189f81c211a4.png)
The formula is  y=erf(x), dy/dx= (2/sqrt(pi)) * (e^(-(x*x))), not dx/dy

**Comment by rGitcy** [comment]
> forward graph:
> 
> x->erf->output
> 
> output = erf(x)
> 
> backward graph:
> 
> gradient_of_output -> erf_grad -> gradient_of_x
> 
> chain rule gradient_of_x = gradient_of_output * erf_grad(x)

The computation should be rule gradient_of_output = gradient_of_input * erf_grad(x) according to the differentiation formulas of erf.

**Comment by rGitcy** [comment]
@baijumeswani @mattetti  please check it again!

**Comment by iK1D** [comment]
> @baijumeswani @mattetti please check it again!

It's not to compute dx, let C is cost function, so gradient(x) is dC/dx and gradient(y) is dC/dy.

gradient(x) = dC/dx = (dC/dy)*f' = gradient(y)*f'.
