### ISSUE TITLE
"CUDA execution provider is not enabled in this build" issue (c# CUDA)

### ISSUE THREAD

**Issue by lxq306** [microsoft/onnxruntime#13542]
Hello, we got an exception "[ErrorCode:Fail] CUDA execution provider is not enabled in this build" when we new an OrtCUDAProviderOptions object using 
        `OrtCUDAProviderOptions cudaProviderOptions = new OrtCUDAProviderOptions();` 
Do you have any advice for us? Really appreciate !!!

**Platform**
windows10

**IDE**
visual studio 2019

**ONNX Runtime Installation**
NuGet

**ONNX Runtime Version or Commit ID**
1.12.1

**ONNX Runtime API**
C#

**Architecture**
X64

**Execution Provider**
CUDA 11.4.4

**CUDNN**
[cuDNN v8.6.0 (October 3rd, 2022), for CUDA 11.x](https://developer.nvidia.cn/rdp/cudnn-download#a-collapse860-118)

**NOTES**
libcudart 11.4.148
libcufft 10.5.2.100
libcurand 10.2.5.120
libcublas 11.6.5.2

**Is this a quantized model?**
Yes

**Comment by jywu-msft** [comment]
wanted to confirm you're using the GPU Package?  https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.Gpu ?

**Comment by lxq306** [comment]
> wanted to confirm you're using the GPU Package? https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.Gpu ?

Thanks for your reply!  Yes, I'm using the following packages
![image](https://user-images.githubusercontent.com/90364372/199633773-042acebf-9c82-4b8f-adbf-ccdbbfdaf23b.png)
and CUDA 11.4.4 is also well installed:
![image](https://user-images.githubusercontent.com/90364372/199634498-d239042f-f744-487c-8b4a-e4eec873b9dd.png)

**Comment by jywu-msft** [comment]
could it be you're somehow accidentally using the CPU package instead of GPU package?
I see you have both installed. 
the error indicates you're trying to calling an api that isn't present in your build (presumably CPU build)

**Comment by lxq306** [comment]
> 

yeah right, I installed both of them. But when I installed just gpu package, I got a "cannot find entry point for "OrtGetApiBase"" exception, then I check online and  found someone said:
"When these packages are updated to 1.5.1+, a reference to Microsoft.ML.OnnxRuntime (1.5.1+) must also be added, otherwise InferenceSession becomes unavailable. Updating anything to 1.5.1 breaks ApplyOnnxModel GPU functionality." [https://developercommunity.visualstudio.com/t/applyonnxmodel-signature-for-gpu-execution-of-onnx/1392548]
https://developercommunity.visualstudio.com/t/applyonnxmodel-signature-for-gpu-execution-of-onnx/1392548

so I also installed CPU package, and the EntryPointNotFoundException gone, but got "CUDA execution provider is not enabled in this build" instead.

**Comment by Hungqh333** [comment]
How did you check to see if you are using the CPU package or the GPU package?

**Comment by GrahamTheCoder** [comment]
I think it means in your csproj **replace** this CPU one:
*  `<PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.18.1" />`

With this Gpu one:
*  `<PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu" Version="1.18.1" />`
