### ISSUE TITLE
onnx runtime csharp InferenceSession failing with mask_rcnn from model zoo

### ISSUE THREAD

**Issue by royoung** [microsoft/onnxruntime#1355]
**Describe the bug**
Running the sample input and model from https://github.com/onnx/models/tree/master/mask_rcnn is results in following exception message:

Microsoft.ML.OnnxRuntime.OnnxRuntimeException: '[ErrorCode:Fail] C:\agent\_work\43\s\onnxruntime\core/providers/cpu/math/element_wise_ops.h:341 onnxruntime::BroadcastIterator::Init axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 0 by 1

**System information**
- Windows 10 x64
- ONNX Runtime installed from nuget (non GPU)
- ONNX Runtime version: 0.4
- Visual Studio version: 2017 15.9.12

**Comment by BowenBao** [comment]
@royoung Thanks for reporting. Are you using 'demo.jpg' or the sample test data as sample input? Did you apply the preprocessing step?

**Comment by royoung** [comment]
Yes I tried with 'demo.jpg' and wrote/applied preprocessing step in line with the example python code given. Has this model ever been verified with onnx runtime 0.4?

**Comment by royoung** [comment]
Thanks Bowen - update from my side - I went through and cleaned up my example to annotate with comments to share with, in process I found and fixed a bug with proprocessing and extracting vals into tensor and now its working as expected. Closing.

**Comment by WonderAndMaps** [comment]
Hi @royoung , I've seen the same error. What was your bug and how did you fix it?
