### ISSUE TITLE
 CUDA_PATH is set but CUDA wasn't able to be loaded

### ISSUE THREAD

**Issue by CanyonWind** [microsoft/onnxruntime#13576]
### Describe the issue

Hi, I've installed the listed CUDA (11.4) and cuDNN(8.2.2.26) versions as suggested [here](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html). But after `pip install onnxruntime-gpu`, it still cannot load CUDA ep correctly. Saying:
```
CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
```

Here's my cuda_path:
```
$env:CUDA_PATH
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4
```
And PATH:
```
 $env:PATH
C:\Users\user\projects\test\env\Scripts;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2021.2.1\;C:\Program Files\CMake\bin;C:\Program Files (x86)\Vim\vim82;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin;
```

Help would be much apprecaited.

### To reproduce

NA

### Urgency

Very urgent

### Platform

Windows

### OS Version

Windows 11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1/1.12.1/1.12.0 all tried

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.4

**Comment by CanyonWind** [comment]
To update -- I also tried to build from source with CUDA EP (specified my cuda and cudnn paths explicitly) and succeeded to build. But after installing the built wheel it still says the same error: `CUDA_PATH is set but CUDA wasn't able to be loaded.`

Could anyone please guide me on which step I did wrongly? Thanks a lot

**Comment by mszhanyi** [comment]
So far, I couldn't reproduce it.

Could you install pytorch to double check whether it is an issue of CUDA installation ?
`python -c "import torch; torch.cuda.is_available()"`

And it'd better provide the output message of 
`nvidia-smi`
and
`nvcc --version`

**Comment by CanyonWind** [comment]
Hi I tried all three just now (installed cuda 11.6 and the onnxruntime-gpu is complied locally with my current cuda and cudnn):
```
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> exit()
```
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:36:24_Pacific_Standard_Time_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
```
```
Wed Nov  9 22:06:20 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 512.72       Driver Version: 512.72       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   38C    P3    10W /  N/A |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by CanyonWind** [comment]
Since the onnxruntime with cuda ep could be compiled on my local machine, is it verified that my local cuda and cudnn works fine with onnxruntime? Felt like it might be some of the dynamic libraries (dll files on windows) couldn't be loaded successfully. 

I checked with dependency walker but it shows that all dependencies could be located. And also tried to run the test script with windbg -- no error throws for dll loading but the python terminal still says ` LoadLibrary failed with error 126`. I've been stuck on this for days and would really need some help. Thanks a lot

**Comment by mszhanyi** [comment]
From your `PATH`, the nvcc version should be 11.4, but it shows 11.6
run `where nvcc` you might find C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin at the first place.

what's the output `set | findstr CUDA`

**Comment by CanyonWind** [comment]
Sorry the first post is outdated. I tried to uninstall cuda 11.4, installed cuda 11.6 and compile ort + cuda ep with the current cuda 11.6 earlier today. 

The path now is
```
C:\Users\yankang\projects\cmgan_pth_test\env_py38\Scripts;C:\Windows\System32;C:\Program Files\NVIDIA GPU Computing Toolkit\dll_x64;C:\Program Files\NVIDIA GPU Computing Toolkit\dll_x64;C:\Program Files\NVIDIA GPU Computing Toolkit\dll_x64;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\dll_x64;C:\Program Files (x86)\Vim\vim82;C:\Users\yankang\AppData\Local\Microsoft\WindowsApps;C:\Users\yankang\AppData\Local\Programs\Microsoft VS Code\bin;
```

**Comment by CanyonWind** [comment]
`set | findstr CUDA` only prompts me to  set variables, not sure if this is expected.
```
PS C:\Users\user> set | findstr CUDA

cmdlet Set-Variable at command pipeline position 1
Supply values for the following parameters:
Name[0]:
```

**Comment by CanyonWind** [comment]
`where nvcc` outputs the cuda 11.6 path:
```
C:\Users\user>where nvcc
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc.exe
```

**Comment by mszhanyi** [comment]
> `set | findstr CUDA` only prompts me to set variables, not sure if this is expected.
> 
> ```
> PS C:\Users\user> set | findstr CUDA
> 
> cmdlet Set-Variable at command pipeline position 1
> Supply values for the following parameters:
> Name[0]:
> ```

`set | findstr CUDA` is  a batch command. it runs in normal windows command window.

Why there're multiple `C:\Program Files\NVIDIA GPU Computing Toolkit\dll_x64` in PATH? what's in it?

Since you've already installed the CUDA11.6, could you try re-installing the offical onnxruntime-gpu 1.13.1 in a clean virtual environment. 
And check the output of  
`pip show onnxruntime-gpu`
`python -c "import onnxruntime as ort; print(ort.get_device())"`
`python -c "import onnxruntime as ort; print(ort.__version__)"`

**Comment by CanyonWind** [comment]
Thanks! here's the output of `set | findstr CUDA`
```
C:\Users\user\projects\test>set | findstr CUDA
Path=%PATH%;C:\Program Files\NVIDIA GPU Computing Toolkit\dll_x64;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\dll_x64;C:\Program Files (x86)\Vim\vim82;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin;C:\WINDOWS\system32;
```
I left the zlib dll in the `dll_x64` folder and added it in the path as instructed in [cuda install guide](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-zlib-windows), sorry for the confusion.

And for the outputs of the newly install onnxruntime-gpu 1.13.1 in a clean venv:
```
(clean_env) PS C:\Users\user\projects\test> pip show onnxruntime-gpu
Name: onnxruntime-gpu
Version: 1.13.1
Summary: ONNX Runtime is a runtime accelerator for Machine Learning models
Home-page: https://onnxruntime.ai
Author: Microsoft Corporation
Author-email: onnxruntime@microsoft.com
License: MIT License
Location: c:\users\user\projects\test\clean_env\lib\site-packages
Requires: coloredlogs, flatbuffers, numpy, packaging, protobuf, sympy
Required-by:
(clean_env) PS C:\Users\user\projects\test> python -c "import onnxruntime as ort; print(ort.get_device())"
GPU
(clean_env) PS C:\Users\user\projects\test> python -c "import onnxruntime as ort; print(ort.__version__)"
1.13.1
```

Sadly the problem persists with the new ort-gpu 1.13.1 as well..
```
['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
2022-11-10 00:46:19.8506006 [E:onnxruntime:Default, provider_bridge_ort.cc:1266 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1069 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\user\projects\test\clean_env\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2022-11-10 00:46:19.8601278 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:578 onnxruntime::python::CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
```

**Comment by mszhanyi** [comment]
It looks you didn't add the cuDNN directory into the PATH
```
Add the NVIDIA cuDNN bin directory path to the PATH variable:
Variable Name: PATH 
Value to Add: C:\Program Files\NVIDIA\CUDNN\v8.x\bin
```
https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installwindows

Where did you put your cudnn file?
if you copy the cudnn files into the same directory as cuda files , you don't need to specify additional ENV.
```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v{version}\include\x64
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v{version}\h
```
If you copied them into another directory, such as  
`C:\Program Files\NVIDIA\CUDNN\v8.x\includ`e and` C:\Program Files\NVIDIA\CUDNN\v8.x\lib`
you could try adding ENV CUDNN_HOME=C:\Program Files\NVIDIA\CUDNN\v8.x

**Comment by CanyonWind** [comment]
The cudnn related files in bin/lib/include were copied into cuda corresponding folders before. And my local ort-gpu was able to be compiled with these cuda and cudnn versions.

To double check 
- I have another standalone folder with cudnn v8.2.2.26
- I added `CUDA_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6` and `CUDNN_HOME=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDNN\v8.2.2.26` variables to env, still the same error
- Also added `;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDNN\v8.2.2.26\bin`  to my `PATH`, same error as well.

I'm really confused, if environment paths have all been set correctly, are there any other reasons why the ort binary files are able to be compiled with cuda and cudnn but they couldn't be loaded during inference? And how may I investigate deeper on the causes. Thanks!

**Comment by mszhanyi** [comment]
Since it's completed successfully, could you debug with 
![image](https://user-images.githubusercontent.com/16190118/201256383-120664d6-035e-4f52-a2a9-238982b547de.png)

**Comment by CanyonWind** [comment]
Apologies that I'm new to windows programming and VS, please bear with me on this silly question -- how may I debug on this? I tried to run the local debugger (as in the screenshot) and it seems just to compile the library again. I used to compile through command line with 
```
./build.bat --build_wheel --config RelWithDebInfo --skip_tests --build_shared_lib --parallel --use_cuda --cudnn_home 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6' --cuda_home 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6' --cmake_generator "Visual Studio 17 2022" --cuda_version 11.6
```

In the VS, the arguments are not being specified, is this only compiling the cpu version? Do I need to compile with cuda (possibly with command line again), then use VS to debug on the compiled output? Thanks a lot

![image](https://user-images.githubusercontent.com/8852730/201278194-fb868625-4cf4-48ba-add4-773910db72db.png)

**Comment by CanyonWind** [comment]
The build seems somehow failed and it prompted to use the previous build (I would assume it's the one built with cuda, not sure now though). And here are the outputs. It looks like the $CUDAToolKitDir is empty. Do I need to specify it manually or maybe it's some  internal variable onnxruntime set and use?

![image](https://user-images.githubusercontent.com/8852730/201280260-597fbfca-110d-4367-bbb2-35a1eba00c0a.png)

**Comment by mszhanyi** [comment]
![image](https://user-images.githubusercontent.com/16190118/201297603-c6593a27-895e-429f-af6d-7483108bf2db.png)
update to `RelWithDebInfo`

**Comment by BertieJim** [comment]
> ![image](https://user-images.githubusercontent.com/16190118/201297603-c6593a27-895e-429f-af6d-7483108bf2db.png) update `Debug` to `RelWithDebInfo`
> 
> And set(right click) onnxruntime_test_all to `Setup As a Startup Project`

Hello, I encounter the same problem, I solved it by install cuDNN. It seemed that I installed CUDA only. I download the cuDNN zip, and copy the include, lib, bin folder to the same folder in CUDA path, problem solved.

**Comment by CanyonWind** [comment]
For anyone who might find this helpful -- it turned out to be some mess in the setting of my system path. Using conda to create an isolated environment with clean installed cuda and cudnn solved this.

**Comment by rookie-coder99** [comment]
> For anyone who might find this helpful -- it turned out to be some mess in the setting of my system path. Using conda to create an isolated environment with clean installed cuda and cudnn solved this.

I want to know how to solve this problem in the end, I am also troubled by the same problem as you before, thank you for your answer, it is very helpful.

**Comment by taeyoonwf** [comment]
I resolved the same issue lately.
Install torch==1.x.y+cu11x (The version won't be important.)
Use "import torch" before "import onnxruntime"

**Comment by thainguyentrong** [comment]
> Tôi đã giải quyết vấn đề tương tự gần đây. Giải pháp của tôi là pip install torch==1.x.y+cu11x (Phiên bản sẽ không quan trọng.) Sử dụng "nhập ngọn đuốc" trước khi "nhập onnxruntime"

It worked for me tks

**Comment by thainguyentrong** [comment]
> I resolved the same issue lately. My solution is pip install torch==1.x.y+cu11x (The version won't be important.) Use "import torch" before "import onnxruntime"

It worked for me tks

**Comment by Jarvan-via** [comment]
i  solved this problem by this video  https://www.youtube.com/watch?v=2TcnIzJ1RQs

**Comment by kylekam** [comment]
Also solved this issue recently by changing to specific CUDA version mentioned in the chart here: [https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html). I thought the CUDA 11.x family was backwards compatible but only the specific driver version mentioned worked for me.

**Comment by RifadsWork** [comment]
I had the same problem and [here's the solution](https://www.youtube.com/watch?v=ctQi9mU7t9o&t=3s)

**Comment by neoyxm** [comment]
>Use "import torch" before "import onnxruntime"

works for me, thx

**Comment by 7kms** [comment]
> Also solved this issue recently by changing to specific CUDA version mentioned in the chart here: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html. I thought the CUDA 11.x family was backwards compatible but only the specific driver version mentioned worked for me.
Tks, you provide the correct resolution.
For me, my cuda verions is 12.x, and this error is absolutely  caused by version incompatible

just reinstall like this according to the offcial document
```shell
pip uninstall onnxruntime-gpu
pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
```

**Comment by yotraxxx** [comment]
> i solved this problem by this video https://www.youtube.com/watch?v=2TcnIzJ1RQs

This solved the issue for me as well ! Thanks a lot :)

**Comment by lugui1998** [comment]
In case you do not want to watch the video, the solution is to install CUDA 10.1 and the respective version of cuDNN for cuda 10.1
here are the archive links to get it:
https://developer.nvidia.com/cuda-toolkit-archive
https://developer.nvidia.com/rdp/cudnn-archive

**Comment by mashaz** [comment]
> > Also solved this issue recently by changing to specific CUDA version mentioned in the chart here: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html. I thought the CUDA 11.x family was backwards compatible but only the specific driver version mentioned worked for me.
> 
> Tks, you provide the correct resolution. For me, my cuda verions is 12.x, and this error is absolutely caused by version incompatible
> 
> just reinstall like this according to the official document
> 
> ```shell
> pip uninstall onnxruntime-gpu
> pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
> ```

Solved my problem. Thanks!

**Comment by bejaranoo** [comment]
> > Also solved this issue recently by changing to specific CUDA version mentioned in the chart here: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html. I thought the CUDA 11.x family was backwards compatible but only the specific driver version mentioned worked for me.
> 
> Tks, you provide the correct resolution. For me, my cuda verions is 12.x, and this error is absolutely caused by version incompatible
> 
> just reinstall like this according to the official document
> 
> ```shell
> pip uninstall onnxruntime-gpu
> pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
> ```

This is the way

**Comment by Vashthareaper** [comment]
> I resolved the same issue lately. My solution is pip install torch==1.x.y+cu11x (The version won't be important.) Use "import torch" before "import onnxruntime"

hi could you guide me what exactly is the command to run please?

**Comment by xxss2018** [comment]
`conda install pytorch-cuda=11.8 -c pytorch -c nvidia `
works for me

**Comment by Vashthareaper** [comment]
here is what i did exactly to fix this annoying issue for comfyui

1- Starting from scratch
    1 - deleted cuda from program files >> Nvidia GPU toolkit
    2 - im a noob so installed 3 different python versions (deleted all but only kept python 3.10)
    3 - deleted every extra version of visual studio and only kept visual studio 2015-2022 + visual studio community 2022

2- Installation (installed Anaconda alongside pip)
     1 - Installed pytorch , ran these two commands in anaconda  
     conda install pytorch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 pytorch-cuda=11.8 -c pytorch -c nvidia
     pip install torch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 --index-url https://download.pytorch.org/whl/cu118
       
      2 - downloaded cuda toolkit 11.8 and cuddn 8.9.2 and followed this video for installation (https://www.youtube.com/watch?v=ctQi9mU7t9o&t=642s) , please watch it full as you have to copy paste files for cuddn to conda dir, and set paths in environmental variables.
      3 - ran this command for tensorflow      pip install tensorflow


Please ignore my lack of knowlege as ive only been using comfyui or even downloded python for first time last week. it took me 2 days to figure this out but i realised downloading exact versions for everything do matter. Hope this helps anyone still struggling with cuda not loaded for Onnxruntime

**Comment by maxwelhelp** [comment]
To troubleshoot CUDA and ONNX Runtime issues:

Use Dependency Walker:
Download and run Dependency Walker (http://www.dependencywalker.com/) to analyze onnxruntime_providers_cuda.dll. This will help identify missing dependencies.
Check for missing files:
The analysis revealed that the following files were missing:

cudnn64_8.dll
cudnn_ops_infer64_8.dll
cublasLt64_11.dll
cublas64_11.dll


Locate the missing files:
These files were found in the Python site-packages directory:
AppData\Local\Programs\Python\Python39\Lib\site-packages
Copy the files:
The missing files were manually copied to the CUDA binary directory:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin
Verify the solution:
After copying the files, the CUDA-related issues with ONNX Runtime were resolved.

This manual file relocation solved the immediate problem by ensuring all required CUDA and cuDNN libraries were in a location accessible to the system and ONNX Runtime. However, for a more robust long-term solution, it's recommended to properly reinstall CUDA and cuDNN according to NVIDIA's official documentation to ensure all components are correctly placed and registered in the system.

**Comment by Dimasilham7** [comment]
> > Also solved this issue recently by changing to specific CUDA version mentioned in the chart here: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html. I thought the CUDA 11.x family was backwards compatible but only the specific driver version mentioned worked for me.
> 
> Tks, you provide the correct resolution. For me, my cuda verions is 12.x, and this error is absolutely caused by version incompatible
> 
> just reinstall like this according to the official document
> 
> ```shell
> pip uninstall onnxruntime-gpu
> pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
> ```

still works on my side, tks!

**Comment by tfinseth** [comment]
> To troubleshoot CUDA and ONNX Runtime issues:
> 
> Use Dependency Walker: Download and run Dependency Walker (http://www.dependencywalker.com/) to analyze onnxruntime_providers_cuda.dll. This will help identify missing dependencies. Check for missing files: The analysis revealed that the following files were missing:
> 
> cudnn64_8.dll cudnn_ops_infer64_8.dll cublasLt64_11.dll cublas64_11.dll
> 
> Locate the missing files: These files were found in the Python site-packages directory: AppData\Local\Programs\Python\Python39\Lib\site-packages Copy the files: The missing files were manually copied to the CUDA binary directory: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin Verify the solution: After copying the files, the CUDA-related issues with ONNX Runtime were resolved.
> 

Got it working!! Turns out it was multiple things. First, I needed to figure out what pytorch version was installed, that determined what cuDNN i could use, then i had to look up the CUDA version, which determined the onnxruntime and onnxruntime-gpu i needed (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html). But... it wasnt enough to uninstall, re-install, and add environment variable paths. When I checked with the Dependency Walker to assess my nnxruntime_providers_cuda.dll, I was still missing a bunch of dll's. So then I had to search through my computer and copy and paste those dlls to the CUDA bin folder. Then it worked!! (note only had to copy and paste the 1st level dlls, not any of the missing APIs that Dependency Walker found).

**Comment by aditmaul** [comment]
> > Also solved this issue recently by changing to specific CUDA version mentioned in the chart here: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html. I thought the CUDA 11.x family was backwards compatible but only the specific driver version mentioned worked for me.
> 
> Tks, you provide the correct resolution. For me, my cuda verions is 12.x, and this error is absolutely caused by version incompatible
> 
> just reinstall like this according to the official document
> 
> ```shell
> pip uninstall onnxruntime-gpu
> pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
> ```

thanks! finally.. :)

**Comment by FurkanGozukara** [comment]
Just made a video that shows exactly this error and its solution and logic

It is really ultimate Python CUDA cuDNN C++ Tools tutorial

### [**How to Install Python, CUDA, cuDNN, C++ Build Tools, FFMPEG & Git Tutorial for AI Applications**](https://youtu.be/DrhUHnYfwC0)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/hchc2xHcOkF2VX-wBh0tW.png)](https://youtu.be/DrhUHnYfwC0)

**Comment by Episode-Zhang** [comment]
> > Also solved this issue recently by changing to specific CUDA version mentioned in the chart here: https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html. I thought the CUDA 11.x family was backwards compatible but only the specific driver version mentioned worked for me.
> 
> Tks, you provide the correct resolution. For me, my cuda verions is 12.x, and this error is absolutely caused by version incompatible
> 
> just reinstall like this according to the official document
> 
> pip uninstall onnxruntime-gpu
> pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/

Works for me on Windows with cuda==12.4, cuDNN==8.9.7.29, onnxruntime==1.17.0. Thx
