### ISSUE TITLE
how long may GPU version of C#/C++/C be available?

### ISSUE THREAD

**Issue by xinheblue** [Microsoft/onnxruntime#136]
we are planing a windows desktop project which need the GPU versioin of C#/C++/C, any language would be great. The status now is coming soon or TBD. We would want to know, how long we can expect to use the features.
And last, Great thanks for your work!

**Comment by pranavsharma** [comment]
@xinheblue you should be able to build the GPU version of onnxruntime for C/C++ today; you don't have to wait. C# is being currently worked on by @shahasad.

**Comment by xinheblue** [comment]
@pranavsharma  thinks, that's great
