### ISSUE TITLE
ONNX XGBoost classifier result mismatch with `early_stopping_rounds`

### ISSUE THREAD

**Issue by ht93** [microsoft/onnxruntime#13610]
### Describe the issue

I am converting a simple XGBoost model with `early_stopping_rounds` to ONNX format. However, the results of the ONNX model mismatch the original model.

Then I use the best_ntree_limit (number of rounds learnt) got from first training to retrain the model with fixed round. I got exact same result for the original model and ONNX saved model.

Version:
onnxmltools.__version__ 1.11.1
xgboost.__version__ 1.6.2
onnxconverter_common.__version__ 1.13.0
onnxruntime.__version__ 1.13.1
Python version 3.7.15 (default, Oct 12 2022, 19:14:55) 
[GCC 7.5.0]

### To reproduce

This bug is reproduced in [this Colab notebook](https://colab.research.google.com/drive/1mw514RwOC4eONkZBSdXo-LzSukLZVd1Z?usp=sharing)

### Urgency

Quite urgent. This bug can cause harm if people deploy their XGBoost model in ONNX format without noticing this error.

### Platform

Web Browser

### OS Version

colab

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

Python

### Architecture

Other / Unknown

### Execution Provider

Default CPU

**Comment by faxu** [comment]
CC @xadupre
