### ISSUE TITLE
[Performance] 

### ISSUE THREAD

**Issue by igormis** [microsoft/onnxruntime#13626]
### Describe the issue

The onnx runtime inference looks ok, but lets say one in a thousand requests generates error like this when executing sess.run:
`onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'StatefulPartitionedCall/model/tfxlm_roberta_for_token_classification/roberta/encoder/layer_._0/attention/self/Reshape' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:35 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) size != 0 && (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{0,128,1024}, requested shape:{0,-1,16,64}`

### To reproduce

Unfortunately I am not able to send the models. However here is the initialization for the session:
```
sess_options = rt.SessionOptions()

cuda_provider_options = {"arena_extend_strategy": "kNextPowerOfTwo"}
cpu_provider_options = {"arena_extend_strategy": "kNextPowerOfTwo", }
execution_providers = [("CUDAExecutionProvider", cuda_provider_options), ("CPUExecutionProvider", cpu_provider_options)]
sess = rt.InferenceSession("roberta_onnx_model/__MODEL_PROTO.onnx", providers=execution_providers)

run_options = rt.RunOptions()
run_options.add_run_config_entry("kOrtRunOptionsConfigEnableMemoryArenaShrinkage", "cpu:0,gpu:0")

input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
gpus = tf.config.experimental.list_physical_devices('GPU')
 X_test_sample = preprocess(words, ner_labels ,128)
 #print(X_test_sample, flush=True)
 logits = sess.run([label_name], {input_name: X_test_sample}, run_options)[0]
```

### Platform

Linux

### OS Version

20.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

Python

### Architecture

X86

### Execution Provider

CUDA

### Execution Provider Library Version

NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4

### Is this a quantized model?

No

**Comment by tianleiwu** [comment]
what value is the allowzero attribute of the Reshape node?
