### ISSUE TITLE
[Mobile] 

### ISSUE THREAD

**Issue by Svenhu123** [microsoft/onnxruntime#13652]
### Describe the issue

1. I used the NNAPI backend, when I load the ONNX model with UINT8 quantizated, the API createSession crashed with log"
"ORT_RUNTIME_EXCEPTION - message: Exception during initialization: unordered_map::at: key not found"

2. I used the CPU backend, there is no issue when createSession, but crash when run, the crashed log was:
"ORT_NOT_IMPLEMENTED - message: These types are unsupported - ONNX_TYPE_UNKNOWN, ONNX_TYPE_OPAQUE, ONNX_TYPE_SPARSETENSOR."

Did the onnxruntime-android:1.13.1 support the  ONNX model with UINT8 quantizated?

### To reproduce

1. Just createSession when using NNAPI.
2. Run the model when using CPU.

### Platform

Android

### OS Version

Android 9

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

onnxruntime-android

### ONNX Runtime Version or Commit ID

onnxruntime-android:1.13.1

### ONNX Runtime API

Java/Kotlin

### Architecture

ARM32

### Execution Provider

NNAPI

**Comment by Svenhu123** [comment]
Dear:

There's no issue when using QuantFormat.QOperator, maybe there's some issue when using QuantFormat.QDQ.

Thanks.

**Comment by skottmckay** [comment]
Are you able to share the model so we can investigate the exception? QDQ format is generally preferred so we'd like to fix whatever the issue is there.
