### ISSUE TITLE
C/C++ Interface how to deal with input tensors that need different types

### ISSUE THREAD

**Issue by Mut1nyJD** [microsoft/onnxruntime#1366]
First I like this ONNX runtime best platform-independent ONNX model execution engine I've seen so far and I've tried quiet a few.

Unfortunately the C/C++ example is a bit thin on the ground so is the documentation for this bit as well. 
I did manage to get some more simple ONNX models working like a couple of image classification models, however I am struggling at some of the more complicated ones. In particular I am trying the YoloV3 model from the ONNX model zoo (https://github.com/onnx/models/tree/master/yolov3)  However unlike most other models this requires two input tensors one is the image as usually and the second one is the shape of the original image. Now the problem is they are of two different types. One is a float32 and the other an int32 if I am correct.
 
So I am not quiet sure how I would be able to use the OrtRun function to handle this type of case

**Comment by hariharans29** [comment]
@RyanUnderhill - Is this something you can help with ? Thanks.

**Comment by RyanUnderhill** [comment]
@Mut1nyJD Are you using the C++ APIs or the C APIs? With the C++ API, you can use the templates to create tensors from C++ types more easily.

Also, which C/C++ example were you referring to? There is a more recent one added in here https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx/MNIST (though it only uses float types, but you can easily see how to change what type the tensors are).

**Comment by Mut1nyJD** [comment]
@RyanUnderhill Thank you for your anwer, I am actually using the C API but in a C++ environment. I am referencing the to the C API example that is linked in the readme.md on this github. Thank you for the link for the new example

**Comment by RyanUnderhill** [comment]
@Mut1nyJD Ah, if you want a direct comparison of the C to C++ API, there's two versions of one sample that differ only by API. You probably saw the C one but here they are:

https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp

https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp

Feel free to ask any more questions if you're having any troubles!

**Comment by hariharans29** [comment]
Hi @Mut1nyJD ,

Please close this issue if the above answers your question.

Thanks
