### ISSUE TITLE
Type 'tensor(bool)' of input parameter (1074) of operator (CumSum) in node (CumSum_422) is invalid

### ISSUE THREAD

**Issue by AllentDan** [microsoft/onnxruntime#13681]
### Describe the issue

In a PyTorch model, there is a func named `torch.any` which is not accepted by ONNX. So I rewrite the func to:
```
@FUNCTION_REWRITER.register_rewriter(func_name='torch.Tensor.any')
@FUNCTION_REWRITER.register_rewriter(func_name='torch.any')
def any__default(ctx, input, *args, **kwargs) -> torch.Tensor:
    """Rewrite `any` for ONNX.
    """
    if len(args) == 0 and kwargs == {}:
        return (input != 0).float().sum() > 0

    keepdim = False
    if len(args) == 2:
        keepdim = args[1]
    if 'keepdim' in kwargs:
        keepdim = kwargs['keepdim']
    dim = None
    if len(args) > 0 and isinstance(args[0], int):
        dim = args[0]
    if 'dim' in kwargs:
        dim = kwargs['dim']
    return (input != 0).sum(dim, keepdim=keepdim) > 0
```
which looks reasonable to me. However, the exported ONNX file would raise the error as title shows in ONNXRuntime.

### To reproduce

https://drive.google.com/file/d/159L5_Y-lCED5-zLtHherHeLG-eQilbKH/view?usp=sharing

### Platform

Linux

### OS Version

18.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.10

### ONNX Runtime API

Python

### Architecture

X86

### Execution Provider

Default CPU

**Comment by yuslepukhin** [comment]
`CumSum` does not handle booleans per spec. Seems to be a converter issue.

**Comment by AllentDan** [comment]
Will close since it's not because of rewriting `torch.any` after finishing inspecting codes. It is indeed a converter issue. Thanks.
 
> `CumSum` does not handle booleans per spec. Seems to be a converter issue.
