### ISSUE TITLE
[Build] [Node.js] `npm install onnxruntime` fails

### ISSUE THREAD

**Issue by mxkrn** [microsoft/onnxruntime#13712]
### Describe the issue

I'm unable to install `onnxruntime` using `npm`, from the error logs it seems like a build script is missing or misplaced. This has been reported before in #5829.

### Urgency

This is urgent because I cannot install the package from `npm`.

### Target platform

Ubuntu-20.04 (WSL2)

### Build script

`npm install onnxruntime`

### Error / output
I've dedacted my filepaths and replaced with `...`
```
❯ npm install onnxruntime
npm ERR! code 1
npm ERR! path /home/.../node_modules/onnxruntime
npm ERR! command failed
npm ERR! command sh -c -- prebuild-install -r napi || (tsc && node ./script/build)
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=3 runtime=napi arch=x64 libc= platform=linux)
npm ERR! node:internal/modules/cjs/loader:998
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module '/home/.../node_modules/onnxruntime/script/build'
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:841:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:23:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }
npm ERR!
npm ERR! Node.js v18.12.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.../.npm/_logs/2022-11-19T11_58_29_972Z-debug-0.log
```

**Comment by skottmckay** [comment]
That looks like an old package name that hasn't been updated in a couple of years. I believe the latest is called `onnxruntime-node`. I can repro the error with `npm install onnxruntime`, and can successfully run `npm install onnxruntime-node`.

**Comment by faxu** [comment]
@mxkrn did you see reference to `npm install onnxruntime` somewhere? See: https://onnxruntime.ai/docs/install/#javascript-installs

**Comment by mxkrn** [comment]
No I didn't, but my problem is that I never actually had to update the `onnxruntime` dependency in my app until now and didn't know the Node.js package was migrated to `onnxruntime-node`. Anyway, installing `onnxruntime-node` works, thanks for the feedback!
