### ISSUE TITLE
[Build] No matching distribution found for onnxruntime

### ISSUE THREAD

**Issue by C26H52** [microsoft/onnxruntime#13717]
### Describe the issue

I am installing onnxruntime when facing errors
![image](https://user-images.githubusercontent.com/113350640/203006545-ac9eac6c-8f3f-499b-a873-1c0436d887a3.png)
i am windows 11 with a python 3.11

### Target platform

sorry...but i don't know what is Target platform

### Build script

sorry...but i don't know what is Build script

### Error / output

![image](https://user-images.githubusercontent.com/113350640/203006545-ac9eac6c-8f3f-499b-a873-1c0436d887a3.png)

**Comment by skottmckay** [comment]
Python versions 3.7 to 3.10 are currently supported, 

https://pypi.org/project/onnxruntime/

**Comment by C26H52** [comment]
> Python versions 3.7 to 3.10 are currently supported,
> 
> https://pypi.org/project/onnxruntime/

Thank you

**Comment by snnn** [comment]
Duplicated with #13482
