### ISSUE TITLE
[Feature Request] C++ api for OrtThreadingOptions

### ISSUE THREAD

**Issue by we1559** [microsoft/onnxruntime#13710]
### Describe the feature request

add a c++ class ThreadingOptions, wraps OrtThreadingOptions

### Describe scenario use case

I need to use some model(Session in c++ api) using the global thread pool.
Then I need to create The Env with global thread pool.
https://github.com/microsoft/onnxruntime/blob/2d732e97292e58821afef6792d457b63fd864771/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L358-L362
But it needs the OrtThreadingOptions* as one of the paramater, which can be only created by the c api.
I'd like create a c++ class ThreadingOptions, which wraps OrtThreadingOptions.

**Comment by RyanUnderhill** [comment]
@pranavsharma Added to the new API: https://github.com/microsoft/onnxruntime/pull/13725/commits/55e5f58871b9199e814c745d03945961fa054d5d

**Comment by we1559** [comment]
@RyanUnderhill I notice you've add it to the new API, which looks like some experiment API in different headers.
I'd like to add to the existing API by merging my PR

**Comment by pranavsharma** [comment]
> @pranavsharma could you get some one to review my PR？

@we1559 We'll be merging @RyanUnderhill's PR soon. Hence, your PR may not be needed.
