### ISSUE TITLE
Missing cuda_provider_factory.h file in release for windows gpu

### ISSUE THREAD

**Issue by dgarlor** [microsoft/onnxruntime#1373]
**Describe the bug**
Using the release onnxruntime-win-x64-gpu-0.4.0.zip.
Following the example to execute a model using the C API, I couldn't activate the CUDA provider because cuda_provider_factory.h file is missing.

I found a workaround compiling the project myself and copying the generated file into my include folder (also modifying the #include inside the file)

**Urgency**
No urgency as I found the workaround but it would be easier for future releases.

**System information**
- Windows 10
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 0.4.0
- Python version: 3.7 (irrelevant)
- Visual Studio version (if applicable): 2017
- CUDA/cuDNN version: 9.1 / 7.1

Thanks and good work

**Comment by hariharans29** [comment]
Thanks for reporting this. 

CC: @pranavsharma @snnn

**Comment by shahasad** [comment]
resolved by https://github.com/microsoft/onnxruntime/pull/1461

**Comment by OpDaSo** [comment]
I have the same problem with the release version onnxruntime-win-x64-gpu-1.11.0.zip

**Comment by LizardM4** [comment]
Also absent from `onnxruntime-linux-x64-gpu-1.11.0`.

**Comment by snnn** [comment]
It is not relevant any more .
```c++
#include "onnxruntime_c_api.h"

        OrtCUDAProviderOptionsV2* cuda_options = nullptr;
        api->CreateCUDAProviderOptions(&cuda_options));
        std::unique_ptr<OrtCUDAProviderOptionsV2, decltype(&OrtApis::ReleaseCUDAProviderOptions)> rel_cuda_options(
            cuda_options, &OrtApis::ReleaseCUDAProviderOptions);
        api->SessionOptionsAppendExecutionProvider_CUDA_V2(ortso, cuda_options));
```

**Comment by OpDaSo** [comment]
What is the type of the variable "api"?

I want to run the mnist example (https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/MNIST).
Unfortunately, I get the error "Cannot open source file: cuda_provider_factory.h" in the file providers.h line 8.

Do you have an example for using onnxruntime with CUDA in C++?

**Comment by snnn** [comment]
```
const OrtApi* api = OrtGetApiBase()->GetApi(ORT_API_VERSION);
```

**Comment by jywu-msft** [comment]
the examples need to be updated to not include cuda_provider_factory.h
