### ISSUE TITLE
The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception

### ISSUE THREAD

**Issue by tungfpmss** [microsoft/onnxruntime#13744]
### Describe the issue

Hello everyone!
Currently I have problem when deploying Onnx with windows 7 x64 professional sp1 (on windows 10 it works properly)
I installed and used:
- NetFramework 4.5.2 and 4.7.2
- C++ 2015-2019 Redistributable (x64) 14.26
- C++ 2015-2019 Redistributable (x64) 14.26
- Microsoft.ML.OnnxRuntime 1.13.1 from Nuget

But when running on windows 7 error as below:
Unable to load DLL 'onnxruntime': The specified module could not be found. (Exception from HRESULT: 0x8007007E) at Microsoft.ML.OnnxRuntime.NativeMethods.OrtGetApiBase()
The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.
Do you have any suggestions for me in this case? Am i missing something?

### To reproduce

using Microsoft.ML.OnnxRuntime;
================================
try
{
    InferenceSession _session = new InferenceSession(_path_Weight); // cannot load 
}
catch (Exception _ex)
{
    //Exception - issue
}

### Platform

Windows

### OS Version

Windows 7 x64 professional sp1

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

Default CPU

**Comment by yuslepukhin** [comment]
Check [this ](https://github.com/microsoft/onnxruntime/issues/11230)first.

**Comment by ShiiikK** [comment]
Have still the same problem.

**Comment by yuslepukhin** [comment]
There is a fix for a similar issue in 1.15.1

**Comment by iperov** [comment]
same,
onnxruntime.dll loaded from system32 which is outdated and from 2019 year 
![Procmon64_2023-07-22_15-52-12](https://github.com/microsoft/onnxruntime/assets/8076202/b662432e-6ccc-426a-8151-bb2aa6c4fdb6)

**Comment by aayush0419** [comment]
I am facing similar issue. Did you manage to fix this?

**Comment by tungfpmss** [comment]
> I am facing similar issue. Did you manage to fix this?

Hi. I found a way to fix this error: use onnxruntime.dll version 1.6.0 (File version: 1.6.20.12.09 - Date modified: 10/12/2020). Because this version does not have missing files dependent on windows 7.

**Comment by tungfpmss** [comment]
I found a way to fix this error: use onnxruntime.dll version 1.6.0 (File version: 1.6.20.12.09 - Date modified: 10/12/2020). 
Because this version does not have missing files dependent on windows 7. And using Microsoft.ML.OnnxRuntime 1.6.0.

**Comment by 512286910** [comment]
你好，这个问题解决没，遇到同样问题了

**Comment by Beavencos** [comment]
The problem is with the computer arquitecture you are setting up in the project. This is what worked for me: Changing on the project properties from any CPU to x64, built, clean and publish. Worked on other computers with no problems.
