### ISSUE TITLE
[Build] Visual Studio 2017 fails in cpu_execution_provider.cc

### ISSUE THREAD

**Issue by fischeruben** [microsoft/onnxruntime#13746]
### Describe the issue

Hello.

When attempting to build from source using Visual Studio 15 2017 as cmake generator, I encounter several compiler errors.
One of the issues is with onnxruntime\onnxruntime\core\providers\cpu\cpu_execution_provider.cc.

There seems to be a compiler bug, where an implicit cast from constexpr int of value 0 to int16_t fails. An explicit static cast solves the errors. 

The changes would affect two lines:

old line 36: OrtDevice cpu_device{OrtDevice::CPU, OrtDevice::MemType::DEFAULT, DEFAULT_CPU_ALLOCATOR_DEVICE_ID};
new line 36: OrtDevice cpu_device{OrtDevice::CPU, OrtDevice::MemType::DEFAULT, static_cast<int16_t>(DEFAULT_CPU_ALLOCATOR_DEVICE_ID)};

old line 54: DEFAULT_CPU_ALLOCATOR_DEVICE_ID, create_arena};
new line 54: static_cast<int16_t>(DEFAULT_CPU_ALLOCATOR_DEVICE_ID), create_arena};

### Target platform

Windows

### Build script

build.bat --build_shared_lib --minimal_build --skip_tests --cmake_generator "Visual Studio 15 2017" --config Release

### Error / output

C:\onnxruntime\onnxruntime\core\providers\cpu\cpu_execution_provider.cc(36): error C2398: Element "3": Die Konvertierun
g von "const int" zu "OrtDevice::DeviceId" erfordert eine einschränkende Konvertierung [C:\onnxruntime\build\Windows\Re
lease\onnxruntime_providers.vcxproj]
C:\onnxruntime\onnxruntime\core\providers\cpu\cpu_execution_provider.cc(54): error C2398: Element "2": Die Konvertierun
g von "const int" zu "OrtDevice::DeviceId" erfordert eine einschränkende Konvertierung [C:\onnxruntime\build\Windows\Re
lease\onnxruntime_providers.vcxproj]

### Visual Studio Version

Visual Studio 15 2017

**Comment by snnn** [comment]
Since VS 2017 has reached the End of Mainstream Support, we would prefer to put our limited resources on adding VS2022 support instead.
