### ISSUE TITLE
[Build] Visual Studio 2017 fails in upsample.h/.cpp

### ISSUE THREAD

**Issue by fischeruben** [microsoft/onnxruntime#13745]
### Describe the issue

Hello.

When attempting to build from source using Visual Studio 15 2017 as cmake generator, I encounter several compiler errors.
One of the issues is with C:\onnxruntime\onnxruntime\core/providers/cpu/tensor/upsample.h.

For some reason the compiler cannot find some variables inside a lambda, even though the lambda has an implicit [&] capture (I hope the german error message below is still mostly understandable).

Adding the Variables "input_width", "input_height" and "extrapolation_value" explicitely inside the capture solves the compiler error.
I am aware that this is not a problem of the code, but for support of an older compiler, I would ask to add these explicit captures.

The changes would be at two lines only:

old 163: [&](std::ptrdiff_t first, std::ptrdiff_t last) {
new 163: [&, input_width, input_height, extrapolation_value](std::ptrdiff_t first, std::ptrdiff_t last) {

old 260: [&](std::ptrdiff_t first, std::ptrdiff_t last) {
new 260: [&, input_width, input_height, extrapolation_value](std::ptrdiff_t first, std::ptrdiff_t last) {

### Target platform

Windows 

### Build script

build.bat --build_shared_lib --minimal_build --skip_tests --cmake_generator "Visual Studio 15 2017" --config Release

### Error / output

C:\onnxruntime\onnxruntime\core/providers/cpu/tensor/upsample.h(269): error C2065: "input_height": nichtdeklarierter Be
zeichner [C:\onnxruntime\build\Windows\Release\onnxruntime_providers.vcxproj]
C:\onnxruntime\onnxruntime\core/providers/cpu/tensor/upsample.h(270): error C2065: "input_width": nichtdeklarierter Bez
eichner [C:\onnxruntime\build\Windows\Release\onnxruntime_providers.vcxproj]
C:\onnxruntime\onnxruntime\core/providers/cpu/tensor/upsample.h(272): error C2065: "extrapolation_value": nichtdeklarie
rter Bezeichner [C:\onnxruntime\build\Windows\Release\onnxruntime_providers.vcxproj]
C:\onnxruntime\onnxruntime\core/providers/cpu/tensor/upsample.h(172): error C2065: "input_height": nichtdeklarierter Be
zeichner [C:\onnxruntime\build\Windows\Release\onnxruntime_providers.vcxproj]
C:\onnxruntime\onnxruntime\core/providers/cpu/tensor/upsample.h(173): error C2065: "input_width": nichtdeklarierter Bez
eichner [C:\onnxruntime\build\Windows\Release\onnxruntime_providers.vcxproj]
C:\onnxruntime\onnxruntime\core/providers/cpu/tensor/upsample.h(175): error C2065: "extrapolation_value": nichtdeklarie
rter Bezeichner [C:\onnxruntime\build\Windows\Release\onnxruntime_providers.vcxproj]

### Visual Studio Version

Visual Studio 15 2017

**Comment by snnn** [comment]
Since VS 2017 has reached the End of Mainstream Support, we would prefer to put our limited resources on adding VS2022 support instead.
