### ISSUE TITLE
[Build] can't include the onnxruntime_cxx_api.h file

### ISSUE THREAD

**Issue by QDPeng** [microsoft/onnxruntime#13773]
### Describe the issue

I download a onnxruntime archive file, windows version: onnxruntime-win-x64-1.12.1.zip

int my source file I add the c++ api head file:
#include "onnxruntime_cxx_api.h" 

use cmake to link the onnxruntime.dll
link_directories(xx/xx/xx/onnxruntime-win-x64-1.12.1)
add_executable(myapp  test.cc)
target_link_libraries(myapp onnxruntime)

make success, but when I run the exe file, it crash.

### Target platform

windows x64

### Build script

use cmake and vs2019 to build, c++17

### Error / output

add the head file, it crash in run exe file

### Visual Studio Version

2019

**Comment by RyanUnderhill** [comment]
For your crash, are you crashing on the first call into the onnxruntime API with a nullptr access exception?

**Comment by QDPeng** [comment]
I have resolved this problem, just put onnxruntime.dll and myapp.exe in the same directory.
