### ISSUE TITLE
onnxruntime server can use a GPU backend when available

### ISSUE THREAD

**Issue by minus-one** [microsoft/onnxruntime#1382]
**Is your feature request related to a problem? Please describe.**
The current build of the onnxruntime server only uses CPU as the backend while serving requests. It can use the GPU backend when compiled with CUDA support

**System information**
- ONNX Runtime version (you are using):
master from source

**Describe the solution you'd like**
onnxruntime uses GPU (or any other) backend when available

**Describe alternatives you've considered**
I just made the following change for that to happen for the GPU
```
diff --git a/onnxruntime/server/environment.cc b/onnxruntime/server/environment.cc
index 6ebcb90b..d9f3031c 100644
--- a/onnxruntime/server/environment.cc
+++ b/onnxruntime/server/environment.cc
@@ -4,6 +4,9 @@
 #include <memory>
 #include "environment.h"
 #include "core/session/onnxruntime_cxx_api.h"
+#ifdef USE_CUDA
+#include "core/providers/cuda/cuda_provider_factory.h"
+#endif

 namespace onnxruntime {
 namespace server {
@@ -44,7 +47,11 @@ ServerEnvironment::ServerEnvironment(OrtLoggingLevel severity, spdlog::sinks_ini
 }

 void ServerEnvironment::InitializeModel(const std::string& model_path) {
-  session = Ort::Session(runtime_environment_, model_path.c_str(), Ort::SessionOptions());
+  Ort::SessionOptions session_options = Ort::SessionOptions();
+#ifdef USE_CUDA
+  ORT_THROW_ON_ERROR(OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0));
+#endif
+  session = Ort::Session(runtime_environment_, model_path.c_str(), session_options);

   auto output_count = session.GetOutputCount();

```
**Additional context**
I did not submit it as a bug because I am not if this is one. And I was not sure of the code changes, or if it is in the pipeline, hence just the diff.

**Comment by hariharans29** [comment]
CC: @Klein-Hu

**Comment by skyshard** [comment]
> onnxruntime server doesn't support GPU yet.

_Originally posted by @pranavsharma in https://github.com/microsoft/onnxruntime/issues/4077#issuecomment-637037620_
   
@pranavsharma I saw you aren't supporting non-CPU backends yet in #4077, is this something you would accept this patch around or are there other plans already?

**Comment by pranavsharma** [comment]
> > onnxruntime server doesn't support GPU yet.
> 
> _Originally posted by @pranavsharma in [#4077 (comment)](https://github.com/microsoft/onnxruntime/issues/4077#issuecomment-637037620)_
> 
> @pranavsharma I saw you aren't supporting non-CPU backends yet in #4077, is this something you would accept this patch around or are there other plans already?

yes, we encourage contributions. please go ahead and contribute the patch.
