### ISSUE TITLE
Does onnxruntime custom op support dynamic number of inputs?

### ISSUE THREAD

**Issue by sleepwalker2017** [microsoft/onnxruntime#13839]
### Describe the issue

I didn't see an example for this.

For example, I want to write a custom op that supports any number of inputs/outputs, how can I achieve this ?

### To reproduce

-- just a question

### Platform

Mac

### OS Version

11.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

latest

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by tianleiwu** [comment]
I think you can mark some inputs/outputs as optional. For example, you can create an operator with 32 optional inputs, that could support 0~32 inputs.

**Comment by adrianlizarraga** [comment]
Hi, I just want to note that we're considering adding support for variadic inputs and outputs for custom ops: https://github.com/microsoft/onnxruntime/pull/13946. _If_ merged, this would enable custom ops to specify that an input takes in N or more arguments. 
 
For now, however, @tianleiwu's suggestion of using optional inputs may meet your needs.

**Comment by adrianlizarraga** [comment]
PR https://github.com/microsoft/onnxruntime/pull/13946 was merged. Custom operators can now specify [variadic inputs and outputs](https://github.com/microsoft/onnxruntime/blob/main/include/onnxruntime/core/session/onnxruntime_c_api.h#L3654).

Here's an example of how to specify that a custom op takes in a dynamic number of input arguments, where each input argument can be of a different type.

```C++
struct MyCustomOp : Ort::CustomOpBase<MyCustomOp, MyKernel> {
  // ...

  OrtCustomOpInputOutputCharacteristic GetInputCharacteristic(size_t /* index */) const noexcept {
    return OrtCustomOpInputOutputCharacteristic::INPUT_OUTPUT_VARIADIC;  // Input is variadic
  }

  ONNXTensorElementDataType GetInputType(size_t /* index */) const noexcept {
    return ONNXTensorElementDataType::ONNX_TENSOR_ELEMENT_DATA_TYPE_UNDEFINED;  // Input can be of any numberic tensor type
  }

  bool GetVariadicInputHomogeneity() const noexcept {
    return false;  // Each argument to the variadic input can have different tensor types
  }
}
```
