### ISSUE TITLE
Exception when running OrtRun(): Attempt to use DefaultLogger but none has been registered. 

### ISSUE THREAD

**Issue by doruime** [microsoft/onnxruntime#1384]
How to fix it？ Thanks.

**Comment by skottmckay** [comment]
Please provide details of how you were attempting to run it. Python? C#? C++? C?

If using the C API see https://github.com/microsoft/onnxruntime/blob/master/docs/C_API.md#usage-overview

Do you call OrtCreateEnv? That is were the default logger is normally setup.

**Comment by doruime** [comment]
> Please provide details of how you were attempting to run it. Python? C#? C++? C?
> 
> If using the C API see https://github.com/microsoft/onnxruntime/blob/master/docs/C_API.md#usage-overview
> 
> Do you call OrtCreateEnv? That is were the default logger is normally setup.

I run  it in C. My calling steps are:
OrtCreateEnv
OrtSetSessionThreadPoolSize
OrtSetSessionGraphOptimizationLevel
OrtCreateSession
OrtReleaseSessionOptions(session_options);
OrtReleaseEnv(env);
OrtCreateCpuAllocatorInfo
OrtCreateTensorWithDataAsOrtValue
OrtReleaseAllocatorInfo(allocator_info)
OrtRun()

**Comment by skottmckay** [comment]
The runtime environment needs to remain for the entire duration so please don't release that by calling OrtReleaseEnv until you're completely done.

**Comment by hariharans29** [comment]
Hi @doruime 
 
Please close this issue if your issue was resolved. Thanks!

**Comment by myafei** [comment]
> The runtime environment needs to remain for the entire duration so please don't release that by calling OrtReleaseEnv until you're completely done.

you can use like this
