### ISSUE TITLE
Redefinition due to missing guard in onnxruntime_cxx_inline.h

### ISSUE THREAD

**Issue by xkszltl** [microsoft/onnxruntime#1385]
**Describe the bug**

https://github.com/microsoft/onnxruntime/blob/bfda9ca1c1e396411850e335f6c22ab1ffb90fe7/include/onnxruntime/core/session/onnxruntime_cxx_inline.h

This file doesn't work.
There're redefinition everywhere.
![image](https://user-images.githubusercontent.com/5203025/61037536-1e3d8380-a380-11e9-90d5-44b89c5535b1.png)

Where's the `#pragma once`?

**Urgency**

ASAP.
We need to carefully craft our code now to ensure it is included only once.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master
- GCC/Compiler version (if compiling from source): gcc-8

**Comment by snnn** [comment]
I don't think it's an issue. It's an internal file, you shouldn't include it directly.

**Comment by xkszltl** [comment]
> I don't think it's an issue. It's an internal file, you shouldn't include it directly.

That's a longer reply than adding `#pragma once`......

There's no way for us to tell easily it a file is internal or not.
When we found an usable function, by default we'll include the minimum file for it.
In this case it's non-trivial to trace upward and figure out which file should we include.

**Comment by snnn** [comment]
I'll add a comment to say the file is private, don't include it directly.

**Comment by linkerzhang** [comment]
I agree that adding "#pragma once" should be done.

**Comment by faxu** [comment]
@snnn based on comments here, can you make the suggested update?

**Comment by snnn** [comment]
@xkszltl, have you tried the fix locally yet? Does it fully solve your problem?

**Comment by xkszltl** [comment]
In general we don't fix ort locally to avoid inconsistency with upstream.

**Comment by RyanUnderhill** [comment]
snnn asked since we expect you to get other errors even if '#pragma once' was added.

That file is only included by 'onnxruntime_cxx_api.h' if you try to include it directly you'll get other compile errors since it'll try to define implementations for class members of classes that have not been defined.

**Comment by xkszltl** [comment]
I see, I was able to just use cxx_api.
The problem I ran into is because I found a function in cxx_inline so I inlcuded in addition to cxx_api and causes redef.
