### ISSUE TITLE
PermissionError in Windows while converting a fp32 model to fp16

### ISSUE THREAD

**Issue by valeriosofi** [microsoft/onnxruntime#13878]
### Describe the issue

While trying to convert a fp32 model to half precision using the function `convert_float_to_float16_model_path`, in Windows I get this error: 
```
Traceback (most recent call last):
  File "C:\Users\Administrator\PycharmProjects\nebullvm\model_half.py", line 48, in <module>
    new_onnx_model = convert_float_to_float16_model_path(model_path)
  File "C:\ProgramData\Anaconda3\envs\nebullvm\lib\site-packages\onnxconverter_common\float16.py", line 328, in convert_float_to_float16_model_path
    model = onnx.load(shape_infer_model_path)
  File "C:\ProgramData\Anaconda3\envs\nebullvm\lib\site-packages\onnx\__init__.py", line 115, in load_model
    s = _load_bytes(f)
  File "C:\ProgramData\Anaconda3\envs\nebullvm\lib\site-packages\onnx\__init__.py", line 29, in _load_bytes
    with open(cast(str, f), 'rb') as readable:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\PycharmProjects\\nebullvm\\tmpeu4ij2qk'
```
The same code works for linux and MacOS, so it's only a Windows related problem.

### To reproduce

Create an example onnx model:
```python
import onnx
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


# Dummy Model
net = Net()

# Dummy Input
x = torch.randn(1, 3, 32, 32)

# Export the model
torch.onnx.export(
    net,
    x,
    "model.onnx",
    export_params=True,
    opset_version=17,
    do_constant_folding=True,
    input_names=['input'],
    output_names=['output'],
    dynamic_axes={
        'input': {0: 'batch_size'},
        'output': {0: 'batch_size'}
    }
)

```
Convert the previously created model to half precision:
```python
from onnxconverter_common import convert_float_to_float16_model_path

model_path = "model.onnx"
new_onnx_model = convert_float_to_float16_model_path(model_path)
onnx.save(new_onnx_model, "model_half.onnx")
```

### Platform

Windows

### OS Version

Windows Server 2022

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by bbeaumatin** [comment]
Hi, got the same issue and got there. I'm not a Python developer but I managed to solve my issue by adding `delete=False` argument to the call of NamedTemporaryFile of onnxconverter_common/float16.py lib, line 325.  On windows the file seems to be deleted before the lib tries to read it later. I haven't checked if there is an update of onnxconverter_common as I don't have too much time ^^.

Hope this will help

**Comment by slhodak** [comment]
Having the same issue, and the file does seem to exist when the method is being called, or at least `pathlib.Path(f).is_file()` returns True at that point (in `_load_bytes`) The file isn't there once execution ends, but my guess is onnx cleans up the temp file when the exception is caught.

**Comment by slhodak** [comment]
I made the program sleep for 30 seconds to inspect the file, and it was there, but 0KB. I suspect a different Windows system error saying it was impossible to read the empty file is being mapped to PermissionError.

**Comment by MaanavD** [comment]
Hi @slhodak 

We’ve gone ahead and closed this issue because it is stale.
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary.
