### ISSUE TITLE
Fail to create vector<Ort::Value> using onnxruntime_cxx_api and the official built issues

### ISSUE THREAD

**Issue by qw2208** [microsoft/onnxruntime#1390]
**Describe the bug**
I try to integrate onnxruntime using the **onnxruntime_cxx_api.h**. However, I'm met with some weird issues.

I use multiple `Ort::Values` (i.e., `std::vector<Ort::Value>.data()`) as the input of the function: `std::vector<Ort::Value> Run(const RunOptions& run_options, const char* const* input_names, Value* input_values, size_t input_count, const char* const* output_names, size_t output_count);`.

Input_values are created as the pseudo code shows:
```
std::vector<Ort::Value> input_vectors;
for (input count){
    input_vectors.push_back(CreateTensor(const OrtAllocatorInfo* info, T* p_data, size_t p_data_element_count, const int64_t* shape, size_t shape_len));
}
```

However, when accessing the input_vectors with `input_vectors[0].GetTensorMutableData<float>()` out of the for loop, the values seem incorrect.

**System information**
- Windows server 2016
- From source: https://github.com/Microsoft/onnxruntime/blob/master/BUILD.md (Built offline with `build.bat --build_shared_lib`)
- ONNX Runtime version: 0.4.0 cpu-x64
- Python version: 3.6
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source): x64
- CUDA/cuDNN version: null
- GPU model and memory: null

**Screenshots**
![image](https://user-images.githubusercontent.com/24438413/61096478-5204d000-a48a-11e9-8b42-3f12e90c4dff.png)

![image](https://user-images.githubusercontent.com/24438413/61096499-6517a000-a48a-11e9-9657-becac27e07fd.png)

**Additional context**
the official built [onnxruntime-win-x64-0.4.0.zip](https://github.com/microsoft/onnxruntime/releases/download/v0.4.0/onnxruntime-win-x64-0.4.0.zip) seems incorrect. Ort::GetDimensionsCount() is not included in the pre-built .lib.

**Comment by snnn** [comment]
Not a bug. 
The data pointer passed into OrtValue's constructor is owned by you. You need to keep it alive until the OrtValue is dead.
