### ISSUE TITLE
[Web] [xnnpack] Invalid model when use xnnpack but works fine with wasm

### ISSUE THREAD

**Issue by vacing** [microsoft/onnxruntime#13912]
### Describe the issue

The model works fine in ort-web wasm backend and python platform, but failed with xnnpack.
error:
```sh
Invalid model. Node input 'PPQ_Operation_27' is not a graph input, initializer, or output of a previous node.
```
![image](https://user-images.githubusercontent.com/6896966/206618788-cbd0f111-27cd-4a39-a736-75e9736bb980.png)

Actually, PPQ_Operation_27 is a node, not a tensor.

### To reproduce

js version: https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.min.js
set provider to xnnpack

here is the model
[convnets_modified_v2.zip](https://github.com/microsoft/onnxruntime/files/10191613/convnets_modified_v2.zip)

### Urgency

urgent, will add as any details ASAP if needed

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

release version

### Execution Provider

WASM

**Comment by vacing** [comment]
@fs-eire Could you take a look at this issue, many thanks

**Comment by vacing** [comment]
I did more tests and found that the problem may be caused by such pattern: quant-dequant in chain
![_A6CVLP)GXGU XM{)X7ETAQ](https://user-images.githubusercontent.com/6896966/206634184-8c7b291e-38ea-42ae-8189-c3d6642e4bb6.png)

**Comment by fs-eire** [comment]
@shalvamist

another xnnpack correctness issue. There are possibly problems with quantization implementation in web assembly build.

**Comment by shalvamist** [comment]
Hey @vacing,

Sorry for the late response, I have been backlogged on a few issues.
I have reviewed the issue you reported and tried to run the model in python but couldn't - I got an error when I try to run the model on random data. [Please see this colab notebook](https://colab.research.google.com/gist/shalvamist/784e277b9f679d040bd6be90660a2ff3/model_load_issue_13912.ipynb)
I think I might be running the model with incorrect inputs or there might be an issue with the model itself. Can you please share a way to reproduce the issue you reported ?

Thanks

**Comment by shalvamist** [comment]
OK cool - thanks for the info. I can run the model in python now.
I will try to reproduce the problem in ORT Web - I will keep you posted with and finding I might have.

**Comment by wejoncy** [comment]
Hi @vacing  Could you please use this [script](https://github.com/microsoft/onnxruntime/blob/main/tools/python/util/qdq_helpers/qdq_model_utils.py#L77) to fix your model  and run again?

It's as a DQ node shared by more than one node.

**Comment by shalvamist** [comment]
Hey @wejoncy,

Thanks for the pointer. I ran the script on the model and got this output - 
```
(test1) C:\git_repo\Microsoft\GitHub13912>python -m onnxruntime.tools.qdq_helpers.optimize_qdq_model C:\git_repo\Microsoft\GitHub13912\convnets_modified_v2.onnx output.onnx
Traceback (most recent call last):
  File "C:\Users\Shalva\anaconda3\envs\test1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Shalva\anaconda3\envs\test1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Shalva\anaconda3\envs\test1\lib\site-packages\onnxruntime\tools\qdq_helpers\optimize_qdq_model.py", line 37, in <module>
    optimize_qdq_model()
  File "C:\Users\Shalva\anaconda3\envs\test1\lib\site-packages\onnxruntime\tools\qdq_helpers\optimize_qdq_model.py", line 31, in optimize_qdq_model
    fix_dq_nodes_with_multiple_consumers(model)
  File "C:\Users\Shalva\anaconda3\envs\test1\lib\site-packages\onnxruntime\tools\qdq_helpers\qdq_model_utils.py", line 107, in fix_dq_nodes_with_multiple_consumers
    onnx.checker.check_model(model)
  File "C:\Users\Shalva\anaconda3\envs\test1\lib\site-packages\onnx\checker.py", line 119, in check_model
    C.check_model(protobuf_string, full_check)
onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of 'type' is required but missing.
```
Does this points to an issue in the model ?

**Comment by wejoncy** [comment]
> Hey @wejoncy,
> 
> Thanks for the pointer. I ran the script on the model and got this output -
> 
> ```
> (test1) C:\git_repo\Microsoft\GitHub13912>python -m onnxruntime.tools.qdq_helpers.optimize_qdq_model C:\git_repo\Microsoft\GitHub13912\convnets_modified_v2.onnx output.onnx
> Traceback (most recent call last):
>   File "C:\Users\Shalva\anaconda3\envs\test1\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "C:\Users\Shalva\anaconda3\envs\test1\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Shalva\anaconda3\envs\test1\lib\site-packages\onnxruntime\tools\qdq_helpers\optimize_qdq_model.py", line 37, in <module>
>     optimize_qdq_model()
>   File "C:\Users\Shalva\anaconda3\envs\test1\lib\site-packages\onnxruntime\tools\qdq_helpers\optimize_qdq_model.py", line 31, in optimize_qdq_model
>     fix_dq_nodes_with_multiple_consumers(model)
>   File "C:\Users\Shalva\anaconda3\envs\test1\lib\site-packages\onnxruntime\tools\qdq_helpers\qdq_model_utils.py", line 107, in fix_dq_nodes_with_multiple_consumers
>     onnx.checker.check_model(model)
>   File "C:\Users\Shalva\anaconda3\envs\test1\lib\site-packages\onnx\checker.py", line 119, in check_model
>     C.check_model(protobuf_string, full_check)
> onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of 'type' is required but missing.
> ```
> 
> Does this points to an issue in the model ?

This model has dynamic shape, so shape can not  be determinated if input is unknow. I guess onnx.checker.check_model only works for static model.

For this issue, just comment `onnx.checker.check_model(model)` in the function. 

[colab notebook](https://colab.research.google.com/gist/shalvamist/784e277b9f679d040bd6be90660a2ff3/model_load_issue_13912.ipynb#scrollTo=UexTTisvg06z)

**Comment by vacing** [comment]
> 

ok, it seems this is a known issue

**Comment by vadimkantorov** [comment]
Does onnxruntime-web support XNNPACK (which supports wasm-simd/quantization)? https://github.com/microsoft/onnxruntime/discussions/16724
