### ISSUE TITLE
[Build] Main branch build failed with --gen_doc on Linux

### ISSUE THREAD

**Issue by wangyems** [microsoft/onnxruntime#13949]
### Describe the issue

As title

### Target platform

Linux

### Build script

--config RelWithDebInfo --use_cuda --cuda_home /usr/local/cuda-11.6 --cudnn_home /usr/local/cuda-11.6 --parallel --enable_pybind --build_wheel --skip_tests --build_shared_lib --gen_doc

### Error / output

![image](https://user-images.githubusercontent.com/52801275/207168895-5526c82d-2be6-41fc-84a2-292efdc2f721.png)

**Comment by skottmckay** [comment]
Is onnxruntime_PYBIND_EXPORT_OPSCHEMA set to ON in the CMakeCache.txt file?

**Comment by wangyems** [comment]
> onnxruntime_PYBIND_EXPORT_OPSCHEMA

no it's not

**Comment by skottmckay** [comment]
Should be set by this: 

https://github.com/microsoft/onnxruntime/blob/d7d932c1c223d8749f1962d5bab8af2fcee5b634/tools/ci_build/build.py#L1243

Was set correctly in my test just now and I don't believe there's anything in build.py that unsets or changes the value of args.gen_doc. I also tried changing between having and not having `--gen_doc` and the value in CMakeCache.txt was correctly updated each time. 

Is onnxruntime_PYBIND_EXPORT_OPSCHEMA being added to the cmake command line?

**Comment by wangyems** [comment]
Thanks! Figured out that I need to first build with setting onnxruntime_PYBIND_EXPORT_OPSCHEMA=ON and then build with --gen_doc.
