### ISSUE TITLE
[Performance] same size and same structure onnx model, but inference time different via cpu

### ISSUE THREAD

**Issue by wnzhyee** [microsoft/onnxruntime#13968]
### Describe the issue

Hi，I trained two models on pytorch and transfer them to onnx, they have same structure and same size, but when i test on cpu, one model inference time is much slower than another. I'm confused, can someone help me please?

for 100 infer trys, model_slow cost 1.57s/infer, and model_fast just cost 0.1s

### To reproduce

```
import onnxruntime
import time
import numpy as np
from tqdm import tqdm

model = "model_s.onnx"

t1 = time.time()
sess = onnxruntime.InferenceSession(model)
t2 = time.time()
print(f"init time {t2-t1}")

input_data = np.random.random((1,3,48,512)).astype(np.float32)
# input_data = onnxruntime.OrtValue.ortvalue_from_numpy(input_data)

t1 = time.time()
for _ in tqdm(range(100)):
    results = sess.run(["out"], {"input": input_data})
t2 = time.time()
print(f"avg infer time {(t2-t1)/100}")
```

### Platform

Linux

### OS Version

ubuntu16.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.6.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Model File

https://drive.google.com/file/d/1XGZE9l0FExTK_NcbFChL3gbzWpkpkr3U/view?usp=sharing

### Is this a quantized model?

No

**Comment by wejoncy** [comment]
Would this one be helpful for you? Sounds you get the same issue.

https://github.com/microsoft/onnxruntime/issues/12959#event-7484772188

**Comment by wnzhyee** [comment]
> 

thanks! we find it is caused by denormal values and simply set denormal to 0 it works well
