### ISSUE TITLE
when built with flag --gen_doc, onnx and onnxruntime cannot be imported in the same python script

### ISSUE THREAD

**Issue by xadupre** [microsoft/onnxruntime#1397]
**Describe the bug**
import onnx, onnxruntime fails whatever the order is. I detected the failure on July 4th.

**Urgency**
It is an issue if onnxruntime on pypi is released with this flag switched on because onnxruntime and onnx cannot be imported in the same script.

**System information**
- OS Platform and Distribution: Windows and Linux
- ONNX Runtime installed from (source or binary): master branch
- ONNX Runtime version: latest
- Python version: 3.7

**To Reproduce**

import onnx
import onnxruntime

ImportError: cannot import name 'RunOptions' from 'onnxruntime.capi._pybind_state'

import onnxruntime
import onnx

ImportError: generic_type: type "OpSchema" is already registered!

**Expected behavior**
No exception.

**Comment by pranavsharma** [comment]
@shahasad can you please take a look? thanks.

**Comment by shahasad** [comment]
The onnxruntime_PYBIND_EXPORT_OPSCHEMA is only defined for —gen_doc build flag.

Current release builds do not run with —gen_doc flag.

**Comment by shahasad** [comment]
resolved by https://github.com/microsoft/onnxruntime/pull/1398
