### ISSUE TITLE
Where can we find Windows debug symbols(pdb files) for released binaries

### ISSUE THREAD

**Issue by ssgwos** [microsoft/onnxruntime#1399]
**Is your feature request related to a problem? Please describe.**

**System information**
- ONNX Runtime version (you are using):

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by joyIntel** [comment]
I guess you should build with `RelWithDebInfo` mode for the pdb files. But I do agree even with that mode, we do not get sufficient symbols.

**Comment by ssgwos** [comment]
Yes we could do that by building from source, my question was for binaries that are in public releases [here](https://github.com/microsoft/onnxruntime/releases):

**Comment by pranavsharma** [comment]
All our release builds are built with RelWithDebInfo and the pdb file is shipped with the packages (both nuget and zip packages). Nuget pkg can be found here https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/.

**Comment by snnn** [comment]
If my PR #8754 get accepted and merged, then you can use the symbols published to nuget.org symbol server by adding https://symbols.nuget.org/download/symbols to your symbol sources in Visual Studio, which allows stepping into package code in the Visual Studio debugger.  I believe it will be much easier.
