### ISSUE TITLE
Wrong result when evaluating a batch of padded sequences with varying lengths on GPU

### ISSUE THREAD

**Issue by xgirones** [microsoft/onnxruntime#1400]
**Describe the bug**
When supplying the attached model with a batch of padded sequences with varying lengths the results on GPU are incorrect:

```
Discrepancy between CPU and GPU evaluations.
Number of sequences in batch: 16
Sequence lengths: [12 32  4 52  8 64 20 36 48 40 24 60 44 16 28 56]
Maximum absolute pairwise difference: 0.9621068835258484
Average absolute pairwise difference: 0.019491384112097738
```

On the other hand, the results on CPU are fine:

```
Discrepancy between CPU and PyTorch evaluations.
Number of sequences in batch: 16
Sequence lengths: [12 32  4 52  8 64 20 36 48 40 24 60 44 16 28 56]
Maximum absolute pairwise difference: 1.2218952178955078e-06
Average absolute pairwise difference: 1.330953997859751e-08
```

**Urgency**
Stuck on this

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- ONNX Runtime installed from (source or binary): Source
- ONNX Runtime version: Code pulled from the master branch in 13/7/2019
- Python version: 3.6
- Visual Studio version (if applicable): 2017
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1/7.6
- GPU model and memory: NVIDA Quadro K1200 with 4GB

**To Reproduce**
Unzip the attached [discrepancy_CPU_GPU.zip](https://github.com/microsoft/onnxruntime/files/3389130/discrepancy_CPU_GPU.zip) file and run the model **model.onnx** in the _model_ folder on both CPU and GPU using **tensor_CPU_padded_sequences.npy** and **tensor_CPU_lengths.npy** as inputs (all _tensor_XXX_padded_sequences.npy_ and _tensor_XXX_lengths.npy_ in the folder _inputs_output_ are the same). 

**Expected behavior**
Results on GPU and CPU should be the same.

**Screenshots**

**Additional context**
[discrepancy_CPU_GPU.zip](https://github.com/microsoft/onnxruntime/files/3389130/discrepancy_CPU_GPU.zip)

**Comment by HectorSVC** [comment]
Our cuda implementation for LSTM uses cudnn libray, it has some limitation: the sequences in the mini-batch need to be sorted in descending order according to length. refers to 
https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html#cudnnRNNForwardInferenceEx

**Comment by xgirones** [comment]
Hi Hector, 

 Thanks for your answer. I tried with sorted sequences as you suggested but the problem did not go away:

```
Discrepancy between CPU and GPU evaluations.
Number of sequences in batch: 16
Sequence lengths: [64 60 56 52 48 44 40 36 32 28 24 20 16 12  8  4]
Total non zero elements: 21216
Maximum absolute pairwise difference: 0.9727079272270203
Average absolute pairwise difference: 0.018673043804830376
```

Here you can find the model and the input/output tensors in case you need to take a look at them: 
[discrepancy_CPU_GPU_sorted.zip](https://github.com/microsoft/onnxruntime/files/3399061/discrepancy_CPU_GPU_sorted.zip)

**Comment by HectorSVC** [comment]
Root cause addressed, will send a PR.
@xgirones By they way, Is it possible for us to put your model in our build pipeline to make sure no regression in future?

**Comment by xgirones** [comment]
This is great news, thanks!

> @xgirones By they way, Is it possible for us to put your model in our build pipeline to make sure no regression in future?

Yes, of course. You can use it freely if you find it convenient. It is just a toy model I created to learn more about the best loss functions for sequences.

**Comment by HectorSVC** [comment]
https://github.com/microsoft/onnxruntime/pull/1428

**Comment by HectorSVC** [comment]
The fix is merged. Also sorted sequence_lengths is not a limitation any more. Your first model also works. I'll add them to our test pipeline.
Great thanks for you findings!

**Comment by HectorSVC** [comment]
@xgirones Do you mind to close the issue or you still need some verification?

**Comment by xgirones** [comment]
Closing it... Thanks for your help!
