### ISSUE TITLE
segmentation fault when calling C API, specifically  g_ort->Run(). 

### ISSUE THREAD

**Issue by ruyanyinian** [microsoft/onnxruntime#14028]
### Describe the issue

Hi, all. I was using onnxruntime 1.12.1 C API to get output from model, however crashed on g_ort->Run(), and program gave me error like "/bin/bash: line 1: 10219 Segmentation fault". I was checking many times but the code seemed to be fine. By the way, the code worked well when using C++ api. If you wants to know more infos, please let me konw. Thanks a  lot!

### To reproduce

This is my code and used model.
[onnxruntime_c_code.zip](https://github.com/microsoft/onnxruntime/files/10265830/onnxruntime_c_code.zip)

### Platform

Linux

### OS Version

WSL2 ubuntu 16.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

onnxruntime 1.12.1

### ONNX Runtime API

C

### Architecture

X64

### Execution Provider

Default CPU

**Comment by pranavsharma** [comment]
You're allocating the output tensor incorrectly. The following will work.

```
  const int num_outputs = sizeof(output_names) / sizeof(char *);
  OrtValue *output_tensor[num_outputs] = {NULL, NULL};

  printf("start to run onnxruntime\n");
  ORT_ABORT_ON_ERROR(g_ort->Run(
      session, NULL, input_names, (const OrtValue *const *)&input_tensor, 1,
      output_names, num_outputs, (OrtValue **)output_tensor));

  printf("finish!!!");
```

**Comment by ruyanyinian** [comment]
@pranavsharma, it passed.  Thanks a lot.  I didn't realize that the output tensors need to be allocated, as I saw the sample code for  windows(C API) and  it was only NULL ptr output tensor left to the g_ort->run. So that I was misled.  Anyway, Thanks a again!

**Comment by ruyanyinian** [comment]
I will close the issue
