### ISSUE TITLE
Performance Test Issue With gt/Nuphar Branch on Windows & Linux build Fails

### ISSUE THREAD

**Issue by joyIntel** [microsoft/onnxruntime#1402]
I am working on Nuphar EP. So I am using the `gt/Nuphar` branch. I have two separate issues.

# Issue 1 (Windows)
 In Windows, there is no building issues with it. But when I am using `onnxruntime_perf_test` for an onnx model, it is not generating the output.

Steps to reproduce -
`git clone -b gt/Nuphar https://github.com/microsoft/onnxruntime.git`
`cd onnxruntime`
`git submodule update –-init -–recursive`
`build.bat --use_tvm --use_llvm --llvm_path=C:\llvm\install\path\lib\cmake\llvm --use_mklml --use_nuphar --config=Release`

All the .exe files are successfully generated inside `build` folder.

`cd build\Windows\Release\Release`
`onnxruntime_perf_test -m times -r 100 -e nuphar <onnx model> result.txt`

I am getting an warning message - 
`onnxruntime\cmake\external\tvm\src\arithmetic\int_set.cc:535: cannot evaluate set type Cast`

and `result.txt` not generated. 

I think @kedengms is the best person to answer this question. 

# Issue 2 (Linux)

In Linux, the build fails with following error (image attached)-

`git clone -b gt/Nuphar https://github.com/microsoft/onnxruntime.git`
`cd onnxruntime`
`git submodule update –-init -–recursive`
`./build.sh --use_tvm --use_llvm --llvm_path=/llvm/install/path/lib/cmake/llvm --use_mklml --use_nuphar --config=Release`

![Build_Error](https://user-images.githubusercontent.com/39498824/61177547-0d159200-a58d-11e9-82d6-b23c8bf6266c.png)

I understand that `gt/Nuphar` is a development branch. So, there could be issues. But I think some recent changes are causing these issues. Earlier, I used this branch and did not face any issue. That time I used `f18356ead6083a204ee00a860b1145b5f536d186` commit Id. But I can not revert back also, because that commit no longer exists.
![Working_commit](https://user-images.githubusercontent.com/39498824/61177589-439fdc80-a58e-11e9-96ce-bb3b2579cf66.png)

`

**Comment by snnn** [comment]
The second one is because your png lib version is too low. At this time point, you should either uninstall it or upgrade it to png 1.6. I will remove this source file from onnxruntime project.  I already sent out a pull request for it. And, please use Ubuntu 16.04 and our official install scripts to prepare the dev environment, so that you won't hit the problem again.

**Comment by joyIntel** [comment]
Thanks @snnn for replying. Issue 2 is resolved now. I had to remove `-Werror` from `cmake/CMakeLists.txt` so that warnings are not treated as error. 

I still need help for Issue 1.

**Comment by KeDengMS** [comment]
Thanks for your interest in Nuphar EP. Issue 1 is a warning from TVM when running int set analysis:
```
virtual R VisitExpr_(const Cast* op, Args... args) EXPR_FUNCTOR_DEFAULT;

  IntSet VisitExprDefault_(const Node* op, const Expr& e) final {
    LOG(WARNING) << "cannot evaluate set type " << e->type_key();
    return IntSet::everything();
  }
```

The reason is that it tries to find out the integer range of an expression, and Cast would return anything. IMO this is a normal behavior and should not be warning. We will try to suppress it in our forked TVM repo.

**Comment by yangchen-MS** [comment]
I have a relevant patch somewhere locally on my disk. Let me try to apply it.

**Comment by joyIntel** [comment]
Issue 1 is not just related to that warning. When I run any onnx model with the `onnxruntime_perf_test` binary, no output file is generated (Windows).

The command is `onnxruntime_perf_test -m times -r 100 -e nuphar <onnx model> result.txt`

In Linux, I get the same warning but `result.txt` is generated. But in Windows, it is not.

**Comment by KeDengMS** [comment]
Sounds like a crash, and may not related to the warning message. Could you share the model, preferably with test data if possible?

**Comment by joyIntel** [comment]
Hey @KeDengMS,

I am trying to share my data and model. But it is above 10 MB. GitHub is not allowing me to do so. Could you refer me any other way of sharing ? I am using resnet50 model by the way.

**Comment by KeDengMS** [comment]
It is possible that there are some code path allocated unaligned buffer which triggered AV in memory access. There's a flag in NupharProviderInfo to allow unaligned data, and it's set to true in onnx_test_runner/python binding, false in onnxruntime_perf_test. Please try onnx_test_runner or python if you continue to hit this issue in onnxruntime_perf_test.

**Comment by joyIntel** [comment]
@KeDengMS , I am using this model and data - https://github.com/onnx/models/tree/master/vision/classification/resnet/resnet50.  I do not think using onnx_test_runner would serve my purpose. As I mentioned before, it is working in Linux.

**Comment by KeDengMS** [comment]
I hit similar problems before both on Linux and Windows. Since it is caused by unaligned memory access, it's up to the allocator's mood.
As a temporary workaround, if you have to use onnxruntime_perf_test, you may change [this line](https://github.com/microsoft/onnxruntime/blob/gt/Nuphar/onnxruntime/test/perftest/ort_test_session.cc#L53) to allow unaligned buffer.

**Comment by joyIntel** [comment]
That works. Thanks a lot @KeDengMS

**Comment by snnn** [comment]
Hi Ke Deng, if the buffer is passed in from outside, then there is not alignment garrantee.

**Comment by joyIntel** [comment]
@KeDengMS , I have a general query. Why the performance of Nuphar is pretty stable with increasing batch size ? This is not true for all other EPs. For other Execution Providers, when the batch size increases, the `total time cost` increases.

**Comment by KeDengMS** [comment]
Do you mean running a model with batch > 1? Or just running multiple inference threads simultaneously? For the resnet50 model, I'd expect the majority of computation spent in convolution, which is not what currently Nuphar is optimized for. Conv ops uses other providers. Given that, I don't have a good explanation of the performance diff you observed.

**Comment by joyIntel** [comment]
When I do this - `onnxruntime_perf_test -m times -r 100 -e <EP> <onnx model of various batch size> result.txt`

Resnet50 | Default | ngraph | nuphar
-- | -- | -- | --
BS1 | 17.67s | 1.28s | 7.24s
BS2 | 32.89s | 1.94s | 7.27s
BS32 | 516s | 26.31s | 7.35s

**Comment by KeDengMS** [comment]
OK I guess the model with batch has some issues in its shape inference. Nuphar execution provider relies on ONNX shape inference, and if graph.value_info still has batch == 1, you'll still run as if batch ==1.

Please use the [symbolic_shape_infer.py](https://github.com/microsoft/onnxruntime/blob/gt/Nuphar/onnxruntime/core/providers/nuphar/scripts/symbolic_shape_infer.py) to update the value_info in the model and try again.

Or, maybe just use [ONNX shape inference](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#running-shape-inference-on-an-onnx-model) would be fine.

**Comment by joyIntel** [comment]
So, you are saying even when I am running BS32, nuphar is assuming as if batch == 1 ??

**Comment by KeDengMS** [comment]
Nuphar's dependency on ONNX shape inference is stated in [its doc](https://github.com/microsoft/onnxruntime/blob/gt/Nuphar/docs/execution_providers/Nuphar-ExecutionProvider.md). Since it's compiler-based, it is critical to have the right model to statically declare the shapes upfront. Shape of data arrived at runtime is ignored, and we may add some checks at runtime when shapes mismatch.

**Comment by joyIntel** [comment]
Hey @KeDengMS , I am very new using onnx. I can understand that I have to change here -
<a href="https://github.com/onnx/onnx/blob/v1.5.0/onnx/helper.py#L290">onnx.helper.make_tensor_value_info</a> to give a new batch size. I guess shape is "NCHW" means a data whose layout is (batch_size, channel, height, width). So, I just have to change the `batch_size`. But I am not sure how to do that.

**Comment by KeDengMS** [comment]
Simply put a string in the shape list/tuple passed to make_tensor_value_info would be fine, like [this](https://github.com/onnx/onnx/blob/master/onnx/test/shape_inference_test.py#L720-L726).

**Comment by joyIntel** [comment]
Hey @KeDengMS , I have attached the graph of my model (Resnet50). In every node, the shape information is present. So, I do not think it is caused by Nuphar Shape Inference Dependency. 

I have the directory structure as mentioned like [this](https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/test/perftest)

Still in these two following cases , I am getting the almost same result for Nuphar EP - 

1> `onnxruntime_perf_test -m times -r 100 -e nuphar Models\FinalResnet50\converted_tf_fp32\BS1\converted_TF_FP32_Resnet50_withshapes.onnx result.txt`

2> `onnxruntime_perf_test -m times -r 100 -e nuphar Models\FinalResnet50\converted_tf_fp32\ BS32\converted_TF_FP32_Resnet50_withshapes.onnx result.txt`


Resnet50 | Default | ngraph | nuphar
-- | -- | -- | --
BS1 |  17.67s | 1.28s | 7.18s
BS32 | 516s | 26.31s |7.23s


In the first one, the batch size is 1, and in the second one the batch size is 32
[Resnet50_Graph.txt](https://github.com/microsoft/onnxruntime/files/3419463/Resnet50_Graph.txt)
