### ISSUE TITLE
CUDA error 46 with CUDA 11.6 on Azure ML Linux image

### ISSUE THREAD

**Issue by friggog** [microsoft/onnxruntime#14030]
### Describe the issue

 I am trying to run onnxruntime-gpu on an Azure Machine Learning instance with this base image: [openmpi4.1.0-cuda11.6-cudnn8-ubuntu20.04](https://github.com/Azure/AzureML-Containers/blob/master/base/gpu/openmpi4.1.0-cuda11.6-cudnn8-ubuntu20.04/Dockerfile) using CUDA. When trying to create an inference session I get this error:

```
  File "/azureml-envs/azureml_4ab38fdb3b18635e56f7e63921a429e8/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/azureml-envs/azureml_4ab38fdb3b18635e56f7e63921a429e8/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 46: all CUDA-capable devices are busy or unavailable ; GPU=0 ; hostname=c7b375a29d54407dad59b0dd621129a7000000 ; expr=cudaDeviceSynchronize(); 
```

I previously had this working with near identical environments using earlier versions of CUDA (e.g. [11.3](https://github.com/Azure/AzureML-Containers/blob/master/base/gpu/openmpi4.1.0-cuda11.3-cudnn8-ubuntu20.04/Dockerfile) with onnxruntime-gpu 1.12) which makes me think it is some error between CUDA versions and onnxruntime rather than a general configuration error.

The only potential difference I can see is that the docker image uses cudnn 8.4 while the compatibility list for onnxruntime says cudnn 8.2, though I think 8.4 should be back compatible? The error given doesn't really seem to match this case either

Any advice would be much appreciated!

### To reproduce

Install onnxruntime-gpu in a conda env with the above dockerfile and try to create an inference session

### Platform

Linux

### OS Version

20.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13 and 1.12

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.6

**Comment by yuslepukhin** [comment]
You might get more meaningful help at https://github.com/Azure/AzureML-Containers/issues

**Comment by vizhur** [comment]
> You might get more meaningful help at https://github.com/Azure/AzureML-Containers/issues

I think it's more of a question of onnx runtime support for cudnn 8.4

**Comment by friggog** [comment]
I managed to get this running (with cuDNN 8.4) by instead installing CUDA/cuDNN through conda (either CUDA 11.6 and 11.7 both with cuDNN 8.4 work fine this way...) with a "blank" base image. To me that suggests an issue with nvidia's base image? 
I don't think the problem is either onnxruntime or AML images so will close this issue
