### ISSUE TITLE
[Build] Create InferenceSession hanging forever in Xamarin forms IOS project

### ISSUE THREAD

**Issue by sunshine007ren** [microsoft/onnxruntime#14031]
### Describe the issue

Hi, I am building a xamarin forms application in VS 2022 windows, in the application I used onnxruntime to run a model trained by myself. I first tried run the model in a console application (.net 6) and the inference session was created successfully and the model run prediction correctly. Then I put similar code into xamarin form project and added the onnxruntime nuget package. but this time the project debug/release stuck when :

**var session = new InferenceSession(model, new SessionOptions() { LogSeverityLevel = 0, LogVerbosityLevel = 0});**

I then tried a few different things: 
1. use options = new SessionOptions() { LogSeverityLevel = 0, InterOpNumThreads = 1, IntraOpNumThreads = 1 };
2. change onnxruntime version to 1.10.0 and 1.13.1 (latest)
3. use different IOS build options
4. use or remove mtouch arguments --registrar:dynamic
none of these works.

Then I downloaded the example xamarin forms project CustomVisionSample and this one works in my vs/iphone11 without problem. I then checked the versions of xamarin/.net/onnxruntime referenced in the example project and I could not find anything different to my own project.

Can someone please help me with this? I have stuck on this issue for days

xamarin project reference:
![image](https://user-images.githubusercontent.com/83771617/208666404-1e198bbd-59ba-484f-b4b9-f09ca70ff4e6.png)

ios project reference:
![image](https://user-images.githubusercontent.com/83771617/208666551-b2e7ede5-7355-4798-9c34-f6f30e843420.png)
the warnings exists in example onnx xamarin forms project CustomVisionSample as well.

### Target platform

iPhone 11 14,6 , vs 2022 windows, xcode 14.1

### Build script

public App()
        {
            InitializeComponent();

            //test
            var assembly = GetType().Assembly;

            // Get model
            var modelStream = assembly.GetManifestResourceStream($"{assembly.GetName().Name}.ONNXModels.PlanktonModel.onnx");
            var modelMemoryStream = new MemoryStream();

            modelStream.CopyTo(modelMemoryStream);
            var model = modelMemoryStream.ToArray();

            var options = new SessionOptions() { LogSeverityLevel = 0, InterOpNumThreads = 1, IntraOpNumThreads = 1 };
            var session = new InferenceSession(model, new SessionOptions() { LogSeverityLevel = 0, LogVerbosityLevel = 0});

            //finish test

            MainPage = new Xamarin.Forms.ContentPage();
            //iOS needs to know what´s the root controller (UIViewController) to init the app, This will add an empty view controller at the app initialization
            // Otherwise error thrown

            DependencyService.Register<RealmUserLocalDataStore>();
            DependencyService.Register<RealmLocalDataStore>();
            DependencyService.Register<BackendConnClient>();
        }

### Error / output

by checking the iphone log in mac->xcode->window->devices->iphone->open console->

we found the execution of example app continues from inference_session.cc line 280 (using per session threadpools) to line 1228 (initializing session) 

but for my app this log stopped at line 280 without executing initializing session

**Comment by skottmckay** [comment]
Does it work if run in the iOS simulator? 

What specifically in the output says it doesn't get past the call to create the inference session? Is there an explicit log statement immediately after that which isn't hit?

**Comment by skottmckay** [comment]
Given the sample works, what happens if you put the model from the sample in your app? If that works, it would rule out an issue with your model being the cause.

**Comment by skottmckay** [comment]
Can you comment out code in your app to the bare minimum to attempt to create the InferenceSession and see if it works? Guessing something else the app is doing is causing a deadlock attempt to access some resource. 

Alternatively can you debug using the iOS simulator to try and see where it's hung by looking at the callstacks of the threads? These instructions are old, but I assume the process is similar with VS 2022. https://devblogs.microsoft.com/cppblog/debugging-c-code-on-ios-with-visual-studio-2015/

**Comment by skottmckay** [comment]
@mikeparker104 any suggestions?

**Comment by skottmckay** [comment]
Closing due to lack of response.
