### ISSUE TITLE
ImportError: cannot import name 'RunOptions' 

### ISSUE THREAD

**Issue by 137996047** [microsoft/onnxruntime#1404]
**Describe the bug**

![image](https://user-images.githubusercontent.com/30762967/61184354-61993a00-a67f-11e9-842a-ce1c4b1e1425.png)

![image](https://user-images.githubusercontent.com/30762967/61184361-7aa1eb00-a67f-11e9-94ff-44e0bc3b1acd.png)

I use python=3.6.8 , use the Intel nGraph accelerators and  only use cpu.
I don't use the GPU. The codes following:
`build.bat --config RelWithDebInfo --build_wheel  --use_ngraph`
`pip install ***.whl`
When I try `build.bat --config RelWithDebInfo --build_wheel  --use_mkldnn`  it can be success,  only the 
`--use_ngraph` be replaced with`--use_ngraph` the error happened. 

And I don't know what is the DEX model in the following picture,  could you explain more detailed ?
Thank you very much.
![image](https://user-images.githubusercontent.com/30762967/61184405-f865f680-a67f-11e9-8c12-eaae37e2077c.png)

**Comment by jywu-msft** [comment]
usually this error indicates that there's a missing dependency dll or not in the path.
can you use dependency walker on onnxruntime_pybind11_state.pyd and ensure all dependencies are present?

@tvtrimel, FYI, can you help take a look?

DEX vs codegen should not be relevant to the issue you're seeing.

**Comment by tvtrimel** [comment]
I was under the impression support for the nGraph Python wheel was still being added in Windows. There's already a request for it, so the functionality should come soon. Linux Python support should already be in master though.

**Comment by rgesteve** [comment]
Hi, @137996047.  As @jywu-msft  pointed out, this error usually shows up when Python cannot find a dependency.  For some reason ngraph.dll is not being included in the Windows wheel, so, as a stopgap, would you add the place in your build directory where ngraph.dll is located to your PATH environment variable?  With that, python should be able to load the library.  (Alternatively, copy ngraph.dll to a directory listed in your PATH)

**Comment by 137996047** [comment]
@jywu-msft @tvtrimel  @rgesteve  
I copy the `ngraph.dll` to `C:\Users\v-hadong\AppData\Local\Continuum\anaconda2\envs\onx_graph\Lib\site-packages\onnxruntime\capi`, then it works. Thank you very much!
But I still don't know what's the DEX model .

**Comment by rgesteve** [comment]
I've submitted #1415, a small change that seems to obviate the need for copying ngraph.dll around, @tvtrimel , would you mind confirming?

**Comment by rgesteve** [comment]
@137996047 , as far as I understand, ngraph can work in one of two modes: "DEX", or "direct execution", where a DL model is executed by the onnxruntime/ngraph runtime (I tend to think of it as immediate mode in a graphics library, or an interpreter), and "codegen" mode, where the DL model is not executed, but  "translated" into an executable format, which can then be executed without the need of the whole runtime (in the previous analogy, this would be, roughly, like retained mode or a compiler).  I believe (please @jywu-msft  correct me if I'm wrong) that most documented use cases of the onnxruntime through python make use of the DEX mode of operation (and equivalent in other EPs).

Sorry for the length of the reply, I hope this information is useful and goes some ways towards answering your question.

**Comment by 137996047** [comment]
> I've submitted #1415, a small change that seems to obviate the need for copying ngraph.dll around, @tvtrimel , would you mind confirming?

Although I can import onnxruntime module successfully, When I execute the `self.session.run([self.output_name], {self.input_name: data})`, the error happened:
Exception while creating nGraph CPU Backend: Backend 'CPU' not registered.
![image](https://user-images.githubusercontent.com/30762967/61272915-d3d26180-a7da-11e9-8d3b-dc222d27ad45.png)

**Comment by kile0** [comment]
> > I've submitted #1415, a small change that seems to obviate the need for copying ngraph.dll around, @tvtrimel , would you mind confirming?
> 
> Although I can import onnxruntime module successfully, When I execute the `self.session.run([self.output_name], {self.input_name: data})`, the error happened:
> Exception while creating nGraph CPU Backend: Backend 'CPU' not registered.
> ![image](https://user-images.githubusercontent.com/30762967/61272915-d3d26180-a7da-11e9-8d3b-dc222d27ad45.png)
> 
> And I don't know how to solve it.

I hit the same issue as you - you're probably missing a dll called cpu_backend.dll that you need to copy over into the same directory as ngraph.dll (I also copied tbb.dll to be safe but this might unnecessary)

**Comment by tvtrimel** [comment]
@rgesteve - your PR worked for me. I can't add a review to the PR itself though.

**Comment by 137996047** [comment]
> > > I've submitted #1415, a small change that seems to obviate the need for copying ngraph.dll around, @tvtrimel , would you mind confirming?
> > 
> > 
> > Although I can import onnxruntime module successfully, When I execute the `self.session.run([self.output_name], {self.input_name: data})`, the error happened:
> > Exception while creating nGraph CPU Backend: Backend 'CPU' not registered.
> > ![image](https://user-images.githubusercontent.com/30762967/61272915-d3d26180-a7da-11e9-8d3b-dc222d27ad45.png)
> > And I don't know how to solve it.
> 
> I hit the same issue as you - you're probably missing a dll called cpu_backend.dll that you need to copy over into the same directory as ngraph.dll (I also copied tbb.dll to be safe but this might unnecessary)

You are right and the tbb.dll is necessary from my test.

**Comment by 137996047** [comment]
> @137996047 , as far as I understand, ngraph can work in one of two modes: "DEX", or "direct execution", where a DL model is executed by the onnxruntime/ngraph runtime (I tend to think of it as immediate mode in a graphics library, or an interpreter), and "codegen" mode, where the DL model is not executed, but "translated" into an executable format, which can then be executed without the need of the whole runtime (in the previous analogy, this would be, roughly, like retained mode or a compiler). I believe (please @jywu-msft correct me if I'm wrong) that most documented use cases of the onnxruntime through python make use of the DEX mode of operation (and equivalent in other EPs).
> 
> Sorry for the length of the reply, I hope this information is useful and goes some ways towards answering your question.

Thank you for your explain, I think I get it.
To summarize, When we built onnxruntime using ngraph, if we encounter such an error,  we can try copying `cpu_backend.dll`,  `ngraph.dll` and `tbb.dll` in `\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime\capi` to `C:\Users\user_name\AppData\Local\Continuum\anaconda2\envs\onx_graph\Lib\site-packages\onnxruntime\capi`.

**Comment by jywu-msft** [comment]
PR https://github.com/microsoft/onnxruntime/pull/1415 was checked in.
This issue seems to be resolved.
