### ISSUE TITLE
onnxruntime_providers_cuda.dll

### ISSUE THREAD

**Issue by pythongc** [microsoft/onnxruntime#14048]
[Enter feedback here]

---
#### Document Details
* Title: Java
* Page: [https://onnxruntime.ai/docs/get-started/with-java.html](https://onnxruntime.ai/docs/get-started/with-java.html)
* Page Source: with-java.md

**Comment by chenfucn** [comment]
duplicate https://github.com/microsoft/onnxruntime/issues/14047
