### ISSUE TITLE
--use_openmp is removed, how to build ort with openmp

### ISSUE THREAD

**Issue by mengniwang95** [microsoft/onnxruntime#14067]
### Describe the issue

--use_openmp is removed, how to build ort with openmp?

### Target platform

linux

### Build script

./build.sh --config RelWithDebInfo --build_shared_lib --parallel --use_openmp

### Error / output

build.py: error: unrecognized arguments: --use_openmp

**Comment by yuslepukhin** [comment]
OpenMP is no longer supported with Onnxruntime. OpenMP `#pragmas` are removed from the code.

**Comment by wschin** [comment]
Per @yuslepukhin's reply, the short answer is no.
