### ISSUE TITLE
LoadLibrary failed with error 126

### ISSUE THREAD

**Issue by callbarian** [microsoft/onnxruntime#14063]
### Describe the issue

I am using onnxruntime gpu 1.12.1 in c# and it works fine.

When I change the name of the parent directory of the executable to Korean "디버그" which mean "Debug", I encounter this error.
![image](https://user-images.githubusercontent.com/50005149/209301797-b7c788d3-3def-479f-ae0c-3911e432d9ad.png)

Basically the error is saying that onnxruntime_provders_shared.dll cannot be loaded. As you can see some characters are broken in the path.

I believe my case is related to #13439 , because he seems to have Chinese character as a parent folder.

I have run Windbg, and the result is as following.
![image](https://user-images.githubusercontent.com/50005149/209302403-d17596d0-1d62-4e42-8123-2024cd15c4d9.png)

The first exception occurred just before loading the onnxruntime_providers_shared.dll, so I thought core/session/provider_bridge_ort.cc:978 was the first cause of the exception.

![image](https://user-images.githubusercontent.com/50005149/209303141-810ed532-4269-49a2-8528-aa5d52e0177d.png)

I followed the line, and went to 
core/platform/windows/env.cc

![image](https://user-images.githubusercontent.com/50005149/209303415-a946499b-0faa-448b-8812-0a7cfd6454d2.png)

However, when I ran this on a seperate c++ project, I was able to get a correct path.
![image](https://user-images.githubusercontent.com/50005149/209303676-ddf232ef-eb6b-481f-bddc-2a1fee28c7c5.png)

I tried both GetModuleNameA and GetModuleNameW with wchar_t to char conversion.
Both worked.

(I also tried building from source with GetModuleNameW, but didn't work as well)

Any guess why the path is not decoded properly on onnxruntime.dll?

Thank you.

by the way, if you want to try korean characters, you can try these below
한글
디버그

### To reproduce

put a korean or chinese character in an executable path, and see if onnxruntime.dll can load onnxruntime_providers_shared.dll

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.1

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.4

**Comment by yuslepukhin** [comment]
Thank you for reporting.

**Comment by zhijxu-MS** [comment]
@callbarian the PR is merged, could you try it again to see if your issue being resolved?

**Comment by callbarian** [comment]
@zhijxu-MS I am sorry I got very late. I tested the merged code and works fine in korean paths. Thank you.
