### ISSUE TITLE
[Documentation] The ‘resize’ operator convert data to cpu

### ISSUE THREAD

**Issue by DennisJcy** [microsoft/onnxruntime#14070]
### Describe the documentation issue

Hello, i'm converting a pytorch network to onnx,but i meet the following problem:
Why the resize operator convert data to cpu to calculate which cost much time
Here is my export code
```
def export():
def export_superpoint():
    model = Net().to('cuda')
    model.eval()
    img = torch.zeros((1,1,640,640)).to('cuda')
    checkpoint = torch.load('model/weights/model.pth', map_location='cuda')
    model.load_state_dict(checkpoint)
 torch.onnx.export(model,img,'model/weights/model.onnx',verbose=True,do_constant_folding=True ,input_names=['imgs'],output_names=['outputs'],opset_version=11)
```
**Platform**
Ubuntu  NVIDIA3090
**ONNX Runtime Installation**
onnxruntime-gpu=1.13.1
torch=1.10.0+cu111
![image](https://user-images.githubusercontent.com/106725464/209621407-acae8a3b-0fdd-4825-9dc2-4ff437363368.png)
![image](https://user-images.githubusercontent.com/106725464/209621478-85b2fa07-d557-491c-8386-7b739c5c250d.png)

**Comment by wschin** [comment]
It's a scalar so putting it on CPU is more reasonable. Say,
```
float cpu_float = 2.0;
float* cpu_ptr = &cpu_float;
cudaMalloc(&gpu_ptr, sizeof(float));
cudaMemcpy(&gpu_ptr, &cpu_ptr, cudaMemcpyHostToDevice);
cuda_resize(..., gpu_ptr, ...);
```

is way more expensive than

```
float cpu_float = 2.0;
cuda_resize<<<...>>>(..., cpu_float, ...);
```

**Comment by wschin** [comment]
Feel free to reopen if any concerns.

**Comment by DennisJcy** [comment]
Sorry,i may understand a little.But is there a way to binding data to cuda with ONNX API?

**Comment by natke** [comment]
Yes, there is. Please have a look at the IO Binding API documentation: 
https://onnxruntime.ai/docs/api/python/api_summary.html#data-on-device
https://onnxruntime.ai/docs/api/python/api_summary.html#iobinding

And samples here: https://github.com/microsoft/onnxruntime-inference-examples/blob/main/python/api/onnxruntime-python-api.py

**Comment by DennisJcy** [comment]
Thank you for your guide!  @natke 
I have two question on the samples and API you given me:
1.why the sample set the output to a constant value?`np.float32([1.0, 2.0, 3.0, 4.0, 5.0])`
For example, actually the model result may be an unsure resullt? I cant understand that

2.the sample replace `InferenceSession.run()` with `InferenceSession.run_with_iobinding()`,and use `io_binding.bind_input()`
`bind_output()` to binding the input and output to a Specific device(may be cuda).
So,will the Intermediate data binding to cuda too?,because i still want to solve the time which cost by the converting time between cuda and cpu

**Comment by natke** [comment]
Hi @DennisJcy 
The constant value in the sample is for demonstration purposes. For your own application, you can set these to the inputs of your model.

And yes, the intermediate data will remain on device.

Let us know if this helps!

**Comment by DennisJcy** [comment]
Thank you for your precious time! @natke 
I make an easy cost time test between `InferenceSession.run()` and `io_binding.bind_input()` .But i see no improvement.Following is my test code.
```python
def cuda_binding():
    img_path = 'data/images/test.jpg'
    model = ort.InferenceSession('best.onnx', providers=['CUDAExecutionProvider'])
    io_binding = model.io_binding()
    input = cv2.imread(img_path)
    input = cv2.resize(input, (640, 640)) / 255.
    input = np.transpose(input, (2, 0, 1))[np.newaxis, ...].astype(np.float32)
    t=0
    for i in range(100):
        t1=time.time()
        x_ortvalue = ort.OrtValue.ortvalue_from_numpy(input,'cuda',0)
        io_binding.bind_input('images','cuda',0,input.dtype,x_ortvalue.shape(),x_ortvalue.data_ptr())
        io_binding.bind_output('output')
        model.run_with_iobinding(io_binding)
        output = io_binding.copy_outputs_to_cpu()[0]
        t2=time.time()
        if i == 0:
            continue# cuda warm up
        else:
            t+=round((t2-t1)*1000,3)
    print("average time = {}".format(t/99))
``` 
__average time = 32.175474747474745ms__

```python
def cuda_no_binding():
    img_path = 'data/images/test.jpg'
    model = ort.InferenceSession('best.onnx', providers=['CUDAExecutionProvider'])
    input = cv2.imread(img_path)
    input = cv2.resize(input, (640, 640)) / 255.
    input = np.transpose(input, (2, 0, 1))[np.newaxis, ...].astype(np.float32)
    t=0
    for i in range(100):
        t1=time.time()

        output = model.run(None, {'images': input.astype(np.float32)})[0]
        t2=time.time()
        if i == 0:
            continue# cuda warm up
        else:
            t+=round((t2-t1)*1000,3)
    print("average time = {}".format(t/99))  
```
__average time = 34.20883838383838__

__Whats important, two function output the same Log:__
```
[W:onnxruntime:, session_state.cc:1136 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
[W:onnxruntime:, session_state.cc:1138 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
```


The time of the two methods is almost equal, and does it have something to do with the way I export? Because some operators in verbose are labeled __cpu__
![image](https://user-images.githubusercontent.com/106725464/224586254-0780e187-2c4e-45e6-a0c4-d02b11a55b1c.png)
