### ISSUE TITLE
[Documentation] TensorRT execution provider doc is uninformative for onnxruntime-gpu==1.13.1

### ISSUE THREAD

**Issue by fxmarty** [microsoft/onnxruntime#14090]
### Describe the documentation issue

Hi, 1.13 is missing in https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#requirements

Also, is there any reason why TensorRT 8.5 is not supported?

Thanks!

**Comment by chilo-ms** [comment]
Thanks for pointing this out, we will update the document. The upcoming ORT 1.14 will support TensorRT 8.5.

**Comment by zhijxu-MS** [comment]
as said, TRT 8.5 will be supported in ort 1.14, and pls wait that version released.

going to close this issue, pls feel free to reopen it if you have more questions @fxmarty

**Comment by natke** [comment]
Fixed by #14331
