### ISSUE TITLE
[Documentation] Doc for `trt_engine_cache_enable` is wrong

### ISSUE THREAD

**Issue by fxmarty** [microsoft/onnxruntime#14091]
### Describe the documentation issue

Hi,

The python side documentation does not exist: https://onnxruntime.ai/docs/api/python/search.html?q=trt_engine_cache_enable

There is a C++ side documentation: https://onnxruntime.ai/docs/api/c/struct_ort_tensor_r_t_provider_options.html . This doc states that the provider option `trt_engine_cache_enable` should be an `int`. This leads me to think that it should be `0` or `1`.

But actually, when passing `trt_engine_cache_enable` in Python, it can only be `True`, `False`, `"true"`, or `"false"`. The values `0` and `1` are not accepted, and raise:

```
RuntimeError: /onnxruntime_src/onnxruntime/python/onnxruntime_pybind_state.cc:499 std::unique_ptr<onnxruntime::IExecutionProvider> 
onnxruntime::python::CreateExecutionProviderInstance(const onnxruntime::SessionOptions&, const string&, const ProviderOptionsMap&) [ERROR] [TensorRT] The 
value for the key 'trt_engine_cache_enable' should be 'True' or 'False'. Default value is 'False'.
```

**Comment by natke** [comment]
Fixed by #14911
