### ISSUE TITLE
Question: Does Nuphar EP use openmp?

### ISSUE THREAD

**Issue by joyIntel** [microsoft/onnxruntime#1410]
I have a general question related to Nuphar EP. Does it use openmp ? According to my observation,  in case of Nuphar EP ,  the performance remains same irrespective of building with `--use_openmp` flag or not. 

For giving relevance of the question - Ngraph uses openmp. The performance of Ngraph EP heavily depends on the `OMP_NUM_THREADS`

**Comment by KeDengMS** [comment]
Nuphar didn't explicitly use openmp. It has a flag to use TVM [parallel schedule](https://docs.tvm.ai/api/python/schedule.html#tvm.schedule.Stage.parallel) though, but it's not enabled yet. OMP_NUM_THREADS affects MKLML performance greatly. Both int8 GEMM and SGEMM uses MKLML if --use_mklml is specified in build. Nuphar's special GEMV is single threaded.

**Comment by snnn** [comment]
BTW, don't enable mklml and openmp at the same time , on Linux. They conflict with each other
