### ISSUE TITLE
[Documentation Request] Update documentation to exclude 1st generation Movidius NCS

### ISSUE THREAD

**Issue by ksaye** [microsoft/onnxruntime#14105]
I assume the VPU support only includes the 2nd generation of Network Compute Stick (Movidius) and that the documentation should be updated to include this.

On an Intel device with the 1st generation USB Neural Compute Stick plugged in:

![image](https://user-images.githubusercontent.com/15837044/210280167-757a6be8-6c65-45ea-9487-489d811044a4.png)

> ksaye@home:~$ lsusb
> Bus 002 Device 006: ID 03e7:f63b Intel Myriad VPU [Movidius Neural Compute Stick]
> 
> ksaye@home:~$ pip3 list installed | grep openvino
> onnxruntime-openvino         1.13.1
> openvino                     2021.4.2
> 
> ksaye@home:~$ python3
> Python 3.8.10 (default, Nov 14 2022, 12:59:47)
> [GCC 9.4.0] on linux
> import onnxruntime
> RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
> onnxru

On a Up2 (https://up-board.org/upkits/up-squared-ai-vision-kit/) which I believe has the 2nd generation Movidius named MyriadX

> ksaye@up1:~$ lsusb
> Bus 003 Device 002: ID 03e7:2485 Intel Movidius MyriadX
> 
> ksaye@up1:~$ pip3 list installed | grep openvino
> onnxruntime-openvino     1.13.1
> openvino                 2021.4.2
> 
> ksaye@up1:~$ python3
> Python 3.8.10 (default, Nov 14 2022, 12:59:47)
> [GCC 9.4.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> import onnxruntime
> onnxruntime.capi._pybind_state.get_available_openvino_device_ids()
> ['CPU', 'MYRIAD']

---
#### Document Details
* Title: Intel - OpenVINO™
* Page: [https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html](https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html)
* Page Source: OpenVINO-ExecutionProvider.md

**Comment by natke** [comment]
ONNX Runtime does support Movidius, as you can see here: https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html#support-coverage. Please raise an another issue if you continue to see problems after following @xadupre's advice above.
