### ISSUE TITLE
[Build]  offline machine

### ISSUE THREAD

**Issue by divastar** [microsoft/onnxruntime#14117]
### Describe the issue

I have an offline machine and now I got these:
Submodule 'cmake/external/FP16 ... cloning into 'cmake/external/FP16'... fatal unable to access 'https://github.com/Maratyszcza/FP16.git/':Could not resolve host ....
so should I download and install these first
so I will be able to build onnxruntime offline?

### Urgency

urgant

### Target platform

centos7

### Build script

./build.sh

### Error / output

Submodule 'cmake/external/FP16 ... cloning into 'cmake/external/FP16'... fatal unable to access 'https://github.com/Maratyszcza/FP16.git/':Could not resolve host ....

### GCC / Compiler Version

7.3.1

**Comment by zhijxu-MS** [comment]
onnxruntime has 3rd party dependency, if you want to build from src then you should download these dependency.

**Comment by zhijxu-MS** [comment]
try these command to clone 3rd party dependency and clone to your offline machine

git submodule sync --recursive
git submodule update --init --recursive

and then add this option to your build command "--skip_submodule_sync"

**Comment by divastar** [comment]
Thank you!

**Comment by zhijxu-MS** [comment]
@divastar is your issued resolved?

**Comment by zhijxu-MS** [comment]
close the issue, pls feel free to reopen it if you still need support @divastar

**Comment by joey9503** [comment]
> try these command to clone 3rd party dependency and clone to your offline machine
> 
> git submodule sync --recursive git submodule update --init --recursive
> 
> and then add this option to your build command "--skip_submodule_sync"

i ran these 2 commands, and added build command "--skip_submodule_sync", but it still needs to download dependency..
