### ISSUE TITLE
Rename onnxruntime-gpu to onnxruntime-cuda [Documentation] 

### ISSUE THREAD

**Issue by Vidyut** [microsoft/onnxruntime#14124]
### Describe the documentation issue

Onnxruntime does not appear to detect non-cuda GPU possibilities including Microcoft's own NEO drivers offering OpenCL 3.0, but the "gpu" in the name is misleading and wastes as much time as AMD does with their useless drivers. If you're limiting support to proprietary Nvidia technology and abandoning your own, at least be honest about it.

**Comment by faxu** [comment]
The onnxrutime-gpu package includes CUDA and TensorRT, as we see these are the most popular used GPUs for ML workloads. We also have a separate package for Windows DirectML - pypi-[onnxruntime-directml](https://pypi.org/project/onnxruntime-directml/) / nuget-[Microsoft.ML.OnnxRuntime.DirectML](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.DirectML)

You can find all the supported EPs here: https://onnxruntime.ai/docs/execution-providers/#summary-of-supported-execution-providers

We also have a matrix on https://onnxruntime.ai/ to help find the recommended build/pkg based on deployment target.
