### ISSUE TITLE
Incorrect output of onnx BertForQuestionAnswering

### ISSUE THREAD

**Issue by Zapotecatl** [microsoft/onnxruntime#14153]
### Describe the issue

I don't get the correct output of onnx BertForQuestionAnswering.

Common example for Bert

```
from transformers import BertTokenizer, BertForQuestionAnswering
import torch

tokenizer = BertTokenizer.from_pretrained("deepset/bert-base-cased-squad2")
model = BertForQuestionAnswering.from_pretrained("deepset/bert-base-cased-squad2")

question, text = "Who was Jim Henson?", "Jim Henson was a nice puppet"

inputs = tokenizer(question, text, return_tensors="pt")
with torch.no_grad():
    outputs = model(**inputs)

answer_start_index = outputs.start_logits.argmax()
answer_end_index = outputs.end_logits.argmax()

print(answer_start_index)
print(answer_end_index)

predict_answer_tokens = inputs.input_ids[0, answer_start_index : answer_end_index + 1]
res = tokenizer.decode(predict_answer_tokens, skip_special_tokens=True)
print(predict_answer_tokens)
print(res)
```
Output correct
```
tensor(12)
tensor(14)

a nice puppet
```

However, I get wrong ouputs with my onnx version.

```
7626
12
```

### To reproduce

I ran this command to get Bert onnx.

`python -m transformers.onnx --model=deepset/bert-base-cased-squad2 --feature=default onnx/`

My program in onnx:

```
from transformers import BertTokenizer, BertForQuestionAnswering
import onnx
import onnxruntime

onnx_model = onnx.load("model.onnx")
onnx.checker.check_model(onnx_model)
ort_session = onnxruntime.InferenceSession("model.onnx")

tokenizer = BertTokenizer.from_pretrained("deepset/bert-base-cased-squad2")
question, text = "Who was Jim Henson?", "Jim Henson was a nice puppet"
inputs = tokenizer(question, text, return_tensors="pt")
print(inputs)

# compute ONNX Runtime output prediction
# inputs to onnx format
ort_inputs = {
    "input_ids": inputs['input_ids'].cpu().numpy(),
    "attention_mask": inputs['attention_mask'].cpu().numpy(),
    "token_type_ids": inputs['token_type_ids'].cpu().numpy()
}

ort_outs = ort_session.run(None, ort_inputs)

answer_start_index = ort_outs[0].argmax()
answer_end_index = ort_outs[1].argmax()

print(answer_start_index)
print(answer_end_index)
```

Wrong ouput

```
7626
12
```
The expected output is 12 and 14.

What is wrong in my code? 

As a extra question, how can I get the answer score (for example 0.993)?

![image](https://user-images.githubusercontent.com/6554457/210926981-a6adb520-1b83-48c1-8165-0d3ca05a0029.png)

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by tianleiwu** [comment]
I think the command line has problem (try change --feature=default to --feature=question-answering):
```
python -m transformers.onnx --model=deepset/bert-base-cased-squad2 --feature=default onnx/
```

Related example for SQuAD: https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/models/bert/eval_squad.py

**Comment by Zapotecatl** [comment]
Awesome! I get the correct output! Thanks @tianleiwu 

About the score, I read your example code. My understanding is I need to use the evaluate library [https://pypi.org/project/evaluate/](url), right?

If the answer is yes. My final goal is work with C++, then I guess I won't be able to use this library, right?

**Comment by tianleiwu** [comment]
Evaluate can help measure precision. You do not need evaluate to work with C++.
