### ISSUE TITLE
'boost/mp11.hpp' file not found while build SNPE

### ISSUE THREAD

**Issue by Kmoment** [microsoft/onnxruntime#14158]
### Describe the issue

while build for SNPE machine with the code:
./build.sh --build_shared_lib --skip_submodule_sync --android --config Release --use_snpe --snpe_root ${snpe_root} --android_sdk_path ${android_sdk_path}  --android_ndk_path ${android_ndk_path}  --android_abi arm64-v8a --android_api 21 --cmake_generator Ninja --build_dir build/Android

### Urgency

urgent

### Target platform

aarch64, SNPE

### Build script

./build.sh --build_shared_lib --skip_submodule_sync --android --config Release --use_snpe --snpe_root ${snpe_root} --android_sdk_path ${android_sdk_path}  --android_ndk_path ${android_ndk_path}  --android_abi arm64-v8a --android_api 21 --cmake_generator Ninja --build_dir build/Android

### Error / output

onnxruntime/include/onnxruntime/core/framework/op_kernel.h:6:10: fatal error: 'boost/mp11.hpp' file not found
#include "boost/mp11.hpp"
         ^~~~~~~~~~~~~~~~
1 error generated.

subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', 'build/Android/Release', '--config', 'Release']' returned non-zero exit status 1.

**Comment by Kmoment** [comment]
gcc version 11.1.0 (Ubuntu 11.1.0-1ubuntu1~20.04)

SNPE version 1.64

**Comment by skottmckay** [comment]
Did you do at least one build without the `--skip_submodule_sync` argument? If you did not, it would be missing dependencies.

**Comment by Kmoment** [comment]
Thank you for your answer. I had a build before :  "./build.sh --android --android_sdk_path  --android_ndk_path --android_abi  arm64-v8a --android_api 21", Will this affect my subsequent build？

**Comment by skottmckay** [comment]
Given those arguments look incomplete I would guess it may not have gotten to the stage of syncing submodules. 

Please try again with the complete arguments from your failed build, but without `--skip_submodule_sync`. Skipping the submodule sync doesn't save much time on linux anyway (it's far more beneficial on Windows).

**Comment by Kmoment** [comment]
Thanks, I'll try
By the way, armv8 lib file name aarch64 android-clang8.0 in SNPE version 1.64, but armv8 lib file name aarch64 android-clang8.0 in SNPE version 1.61

**Comment by Kmoment** [comment]
@skottmckay I use "./build.sh --build_shared_lib  --android --config Release --use_snpe --snpe_root 'Qualcomm/snpe-1.64.0.3605'  --android_sdk_path 'Android/Sdk'  --android_ndk_path 'android-ndk-r19c'  --android_abi arm64-v8a --android_api 21 --cmake_generator Ninja --build_dir build/Android" .   The above error still occurs

**Comment by Kmoment** [comment]
This error can also occur

CMake Error at external/onnxruntime_external_deps.cmake:463 (include):
  include could not find requested file:

    find_snpe.cmake
Call Stack (most recent call first):
  CMakeLists.txt:457 (include)

**Comment by Kmoment** [comment]
@edgchen1 Thanks ！ BR.
