### ISSUE TITLE
please reopen the issue

### ISSUE THREAD

**Issue by shu0o0yX** [microsoft/onnxruntime#14187]
### Describe the issue

Could you please reopen this issue? We get the same problem in opset_version=16.
issue: https://github.com/microsoft/onnxruntime/issues/2756#issue-543199292.

### Target platform

Windows

### Build script

.

### Error / output

onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running BatchNormalization node. Name:'BatchNormalization_123' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\op_kernel.cc:81 onnxruntime::OpKernelContext::OutputMLValue status.IsOK() was false. Shape mismatch attempting to re-use buffer. {1,3,256,192} != {1,6,256,192}. Validate usage of dim_value (values should be > 0) and dim_param (all values with the same string should equate to the same size) in shapes in the model.

**Comment by skottmckay** [comment]
The original issue was with ONNX shape inferencing for Slice. As the error you see is coming from a BatchNormalization node it's not the same problem.

Can you share the model and details of how it was created?

**Comment by shu0o0yX** [comment]
> The original issue was with ONNX shape inferencing for Slice. As the error you see is coming from a BatchNormalization node it's not the same problem.
> 
> Can you share the model and details of how it was created?

Thanks for your reply, my model is from https://github.com/OFA-Sys/DAFlow/blob/main/models/sdafnet.py. it's my export code: 

x = torch.randn(1, 6, 256, 192)
y = torch.randn(1, 3, 256, 192)
z = torch.randn(1, 3, 256, 192)

dynamic_axes = {'ref_input': {0: 'batch_size', 1: 'channel', 2: 'height', 3: 'width'},
                'cloth_img': {0: 'batch_size', 1: 'channel', 2: 'height', 3: 'width'},
                'img_agnostic': {0: 'batch_size', 1: 'channel', 2: 'height', 3: 'width'},
                'output': {0: 'batch_size', 1: 'channel', 2: 'height', 3: 'width'}}

with torch.no_grad():
    torch.onnx.export(
        model,
        (x, y, z),
        "srcnn.onnx",
        opset_version=16,
        input_names=['ref_input', 'cloth_img', 'img_agnostic'],
        output_names=['output'],
        dynamic_axes = dynamic_axes)

onnx_model = onnx.load("srcnn.onnx")
try:
    onnx.checker.check_model(onnx_model)
except Exception:
    print("Model incorrect")
else:
    print("Model correct")

Did I do something wrong?

**Comment by skottmckay** [comment]
You are using different values for the 'channel' input. Think of it as a variable name. It can't be both 6 (x) and 3 (y and z) at the same time. You could run with 3 inputs that all had a 6 for 'channel' or 3 inputs that all had a 3 for 'channel', but not a mix.

**Comment by shu0o0yX** [comment]
It can't be solved, The model already specifices the farmat of the input, If I changed the 'channel' value, it will get this error:
RuntimeError: running_mean should contain 3 elements not 6.

> You are using different values for the 'channel' input. Think of it as a variable name. It can't be both 6 (x) and 3 (y and z) at the same time. You could run with 3 inputs that all had a 6 for 'channel' or 3 inputs that all had a 3 for 'channel', but not a mix.

**Comment by skottmckay** [comment]
You're declaring which dimensions have a named value called 'channel'. You can use a different name for the value that doesn't match. based on your input, you could maybe do `'ref_input': {0: 'batch_size', 1: 'channel_x2', 2: 'height', 3: 'width'`

**Comment by shu0o0yX** [comment]
> You're declaring which dimensions have a named value called 'channel'. You can use a different name for the value that doesn't match. based on your input, you could maybe do `'ref_input': {0: 'batch_size', 1: 'channel_x2', 2: 'height', 3: 'width'`

Thanks for your reply, I'm just learning this stuff. problem has been solved above, but I get a new error:

onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Loop node. Name:'Loop_702' Status Message: Non-zero status code returned while running Reshape node. Name:'Reshape_719' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:36 onnxruntime::ReshapeHelper::ReshapeHelper size != 0 && (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,6,256,8,6}, requested shape:{-1,256,256,8}

I saw some previous issues, but can't solve, could you please tell me the solution?

**Comment by skottmckay** [comment]
Based on [this](https://github.com/OFA-Sys/DAFlow/blob/f46388809dd4c1ada8a7202b1338a84f5147c9dc/models/sdafnet.py#L321-L323) I would expect your input needs to have matching sizes. Most models require specific input shapes so you can't arbitrarily pick a different one.

i.e. x: {1, 6, 128, 128}, y and z: {1, 3, 128, 128}

**Comment by shu0o0yX** [comment]
> Based on [this](https://github.com/OFA-Sys/DAFlow/blob/f46388809dd4c1ada8a7202b1338a84f5147c9dc/models/sdafnet.py#L321-L323) I would expect your input needs to have matching sizes. Most models require specific input shapes so you can't arbitrarily pick a different one.
> 
> i.e. x: {1, 6, 128, 128}, y and z: {1, 3, 128, 128}

Thanks for your reply. I try, but error still exists, so I think that it's not the reason of this error, It's my whole code:
def init_torch_model():
    torch_model = SDAFNet_Tryon(ref_in_channel=6)
    torch_model.load_state_dict(torch.load("ckpt_viton.pt"))
    torch_model.eval()
    return torch_model

model = init_torch_model()
# torch_output = model(torch.from_numpy(input_img)).detach()
x = torch.randn(1, 6, 128, 128)
y = torch.randn(1, 3, 128, 128)
z = torch.randn(1, 3, 128, 128)

dynamic_axes = {'ref_input': {0: 'batch_size', 1: 'channel_x2', 2: 'height', 3: 'width'},
                'cloth_img': {0: 'batch_size', 1: 'channel', 2: 'height', 3: 'width'},
                'img_agnostic': {0: 'batch_size', 1: 'channel', 2: 'height', 3: 'width'},
                'output': {0: 'batch_size', 1: 'channel', 2: 'height', 3: 'width'}}

with torch.no_grad():
    torch.onnx.export(
        model,
        (x, y, z),
        "srcnn.onnx",
        opset_version=16,
        input_names=['ref_input', 'cloth_img', 'img_agnostic'],
        output_names=['output'],
        dynamic_axes = dynamic_axes)

onnx_model = onnx.load("srcnn.onnx")
try:
    onnx.checker.check_model(onnx_model)
except Exception:
    print("Model incorrect")
else:
    print("Model correct")

def get_opt():
    parser = argparse.ArgumentParser()
    parser.add_argument('--name', type=str, required=True)
    parser.add_argument('--load_height', type=int, default=256)
    parser.add_argument('--load_width', type=int, default=192)
    parser.add_argument('--mode', type=str, default='test')
    parser.add_argument('--dataset_dir', type=str, default='./data')
    parser.add_argument('--dataset_imgpath', type=str, default='VITON/VITON_test')
    parser.add_argument('--dataset_list', type=str, default='VITON/test_unpairs.txt')
    parser.add_argument('--save_dir', type=str, default='./results/')
    parser.add_argument('-b', '--batch_size', type=int, default=4)
    opt = parser.parse_args()
    return opt

def test(opt):
    test_dataset = VITONDataset(opt)
    test_loader = data.DataLoader(test_dataset)
    with torch.no_grad():
        for i, inputs in enumerate(tqdm.tqdm(test_loader)):
            img_names = inputs['img_name']
            cloth_names = inputs['c_name']['paired']
            img = inputs['img']
            img_agnostic = inputs['img_agnostic']  # Masked model image
            pose = inputs['pose']
            cloth_img = inputs['cloth']['paired']
            img = F.interpolate(img, size=(256, 192), mode='bilinear')
            cloth_img = F.interpolate(cloth_img, size=(256, 192), mode='bilinear')

            img_agnostic = F.interpolate(img_agnostic, size=(256, 192), mode='bilinear')
            pose = F.interpolate(pose, size=(256, 192), mode='bilinear')
            ref_input = torch.cat((pose, img_agnostic), dim=1)
            ref_input = np.array(ref_input)
            cloth_img = np.array(cloth_img)
            img_agnostic = np.array(img_agnostic)
            ort_session = onnxruntime.InferenceSession("srcnn.onnx")
            ort_inputs = {'ref_input': ref_input, 'cloth_img': cloth_img,
                          'img_agnostic': img_agnostic}
            
            ort_output = ort_session.run(['output'], ort_inputs)[0]
            

if __name__ == '__main__':
    opt = get_opt()
    test(opt)

Else parameters are the same as project: https://github.com/OFA-Sys/DAFlow.
