### ISSUE TITLE
Model loading failed with CUDA EP

### ISSUE THREAD

**Issue by tulasiram58827** [microsoft/onnxruntime#14211]
### Describe the issue

RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:122 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:116 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 999: unknown error ; GPU=192915439 ; expr=cudaSetDevice(info_.device_id); 

```
ldd libonnxruntime_providers_cuda.so
```

```
	linux-vdso.so.1 (0x00007ffc2a99f000)
	libcublas.so.11 => /usr/local/cuda-11.1/lib64/libcublas.so.11 (0x00007f04c359a000)
	libcudnn.so.8 => /usr/local/cuda-11.1/lib64/libcudnn.so.8 (0x00007f04c3372000)
	libcurand.so.10 => /usr/local/cuda-11.1/lib64/libcurand.so.10 (0x00007f04be442000)
	libcufft.so.10 => /usr/local/cuda-11.1/lib64/libcufft.so.10 (0x00007f04b00de000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f04afec0000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f04afcb8000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f04af936000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f04af5f6000)
	libcudart.so.11.0 => /usr/local/cuda-11.1/lib64/libcudart.so.11.0 (0x00007f04af371000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f04af15b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f04aedae000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f04dccd4000)
	libcublasLt.so.11 => /usr/local/cuda-11.1/lib64/libcublasLt.so.11 (0x00007f04a0fe4000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f04a0de0000)
	

### To reproduce

`session = ort.InferenceSession(model_path, providers=['CUDAExecutionProvider'])`

### Urgency

_No response_

### Platform

Linux

### OS Version

18..04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.11

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.1

**Comment by tulasiram58827** [comment]
CUDA and CudNN versions matches with the documentation https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html

**Comment by tulasiram58827** [comment]
@snnn, Any insights?

**Comment by yuslepukhin** [comment]
Searching the internet for `CUDA failure 999` gives plenty of results. `GPU=192915439` also supports card issues theory. NVIDIA folks would probably be in a better position to comment.

**Comment by xadupre** [comment]
I wonder if torch is producing a similar error. In that case, the error probably comes from the driver installation and not from onnxruntime.

**Comment by tulasiram58827** [comment]
Seems like it was mostly because of CUDA installation issue. Reinstallation was successful.
