### ISSUE TITLE
[Performance]  Static Quantization for yolov5s produce 0 confidence for all detection

### ISSUE THREAD

**Issue by AbdelsalamHaa** [microsoft/onnxruntime#14233]
### Describe the issue

I'm trying to speed up the performance of yolov5s using static quantization. 
I have followed the onnxruntime official tutorial on how to apply static quantization and managed to do it and build it. 

Everything is working, but the only issue is when I try to do detection all confidence = 0, so I can't do any detection. 

Note: Using the original onnx file can produce good detection and confidence.  

Here is my code to quantize the onnx model: 

### To reproduce

        def format_yolov5(frame):
  
              row, col, _ = frame.shape
  
              _max = max(col, row)
  
              result = np.zeros((_max, _max, 3), np.uint8)
  
              result[0:row, 0:col] = frame
  
              return result
  
        def _preprocess_images(images_folder: str, height: int, width: int, size_limit=0):
          """
          Loads a batch of images and preprocess them
          parameter images_folder: path to folder storing images
          parameter height: image height in pixels
          parameter width: image width in pixels
         parameter size_limit: number of images to load. Default is 0 which means all images are 
         picked.
         return: list of matrices characterizing multiple images
         """
         image_names = os.listdir(images_folder)
         if size_limit > 0 and len(image_names) >= size_limit:
              batch_filenames = [image_names[i] for i in range(size_limit)]
         else:
             batch_filenames = image_names
         unconcatenated_batch_data = []
  
         for image_name in batch_filenames:
             image_filepath = images_folder + "/" + image_name
             pillow_img = cv2.imread(image_filepath)
             pillow_img = format_yolov5(pillow_img)
             nchw_data = cv2.dnn.blobFromImage(pillow_img, 1 / 255.0, (640,640), swapRB=True)
             unconcatenated_batch_data.append(nchw_data)
          
         batch_data = numpy.concatenate(
             numpy.expand_dims(unconcatenated_batch_data, axis=0), axis=0)
      
             
         return batch_data
  
  
        class yolov5(CalibrationDataReader):
            def __init__(self, calibration_image_folder: str, model_path: str):
                self.enum_data = None
        
                # Use inference session to get input shape.
                session = onnxruntime.InferenceSession(model_path, None)
                (_, _, height, width) = session.get_inputs()[0].shape
        
                # Convert image to input data
                self.nhwc_data_list = _preprocess_images(
                    calibration_image_folder, height, width, size_limit=0
                )
                self.input_name = session.get_inputs()[0].name
                self.datasize = len(self.nhwc_data_list)
        
            def get_next(self):
                if self.enum_data is None:
                    self.enum_data = iter(
                        [{self.input_name: nhwc_data} for nhwc_data in self.nhwc_data_list]
                    )
                return next(self.enum_data, None)
        
          def rewind(self):
              self.enum_data = None`
        
         dr = yolov5("./test_images/", "./best.onnx")
        model_quant = './bests.quant.onnx'
        quantize_static(
              model_fp32,
              model_quant,
              dr,
              quant_format=QuantFormat.QDQ,
              per_channel=False,
              weight_type=QuantType.QInt8,
              optimize_model=True,
          )
I have tried with this as well but same issue 
        
        quantize_static(
          model_fp32,
          model_quant,
          calibration_data_reader=dr,
          activation_type=QuantType.QUInt8,
          weight_type=QuantType.QInt8,
          nodes_to_exclude=['Mul_214', 'Mul_225', 'Mul_249', 'Mul_260', 'Mul_284', 'Mul_295', 'Concat_231', 'Concat_266', 'Concat_301', 'Concat_303'],
          per_channel=True,
          reduce_range=True,
              )

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Is this a quantized model?

Yes

**Comment by xadupre** [comment]
Did you try a dynamic quantization?

**Comment by AbdelsalamHaa** [comment]
> Did you try a dynamic quantization?

Thank you for your reply. 

Yes I did try. But I had to set the weightType to be QUInt which cause the model to be slower. But the detection and the confidence is normal this way.

If I use weightType =QInt I would get some error during inference time

**Comment by xadupre** [comment]
The quantization done by onnxruntime is basic. Did you try to quantize before converting your model into ONNX?

**Comment by xadupre** [comment]
torch documentation is usually a good starting point: https://pytorch.org/docs/stable/quantization.html.

**Comment by AbdelsalamHaa** [comment]
@xadupre 
Okay noted, thank you very much for your reply. Just curious, what could have caused my static quantization implementation to behave this way( all output confidence are zeros )? Any ideas or thoughts on that? 

In terms of speed, the model became 2x faster but all confidence values are zero

Thanks again for your help.

**Comment by xadupre** [comment]
I'm not sure. I would compare the quantized model in torch with the original torch model. If there is no discrepancies, that means the quantization done by onnxruntime is different from what torch is doing. The onnxruntime quantization is basic so I would not be surprised. The quantization may impact a different set of nodes and the parameter may be different.

**Comment by yufenglee** [comment]
@AbdelsalamHaa, the quantization of nodes at the end of yolov5 model causes the accuracy drop because their tensor range is very large. Please exclude them from quantization. (You can also exclude the ones that are marked by blue). I think **this** doesn't work is because your model has different names for those nodes:
 `    quantize_static(
      model_fp32,
      model_quant,
      calibration_data_reader=dr,
      activation_type=QuantType.QUInt8,
      weight_type=QuantType.QInt8,
      **nodes_to_exclude=['Mul_214', 'Mul_225', 'Mul_249', 'Mul_260', 'Mul_284', 'Mul_295', 'Concat_231', 'Concat_266', 'Concat_301', 'Concat_303'],**
      per_channel=True,
      reduce_range=True,
          )`


![image](https://user-images.githubusercontent.com/30486710/211874423-bf6951b1-f085-4b05-b7dc-cf371f0f4c8b.png)

**Comment by AbdelsalamHaa** [comment]
@yufenglee 
Thank you very much for your help. That worked. the model now is 2x faster. Next is for me to check the accuracy and see if I can compromise a bit of that. 

It would be very helpful if you can share with me some links on how to debug this kind of issue in coming future. 

@xadupre 
Thank you for your reply I will take note of that :).

**Comment by AbdelsalamHaa** [comment]
You can speed up yolov5 2x on CPU by quantizing the model using onnxruntime. This will work for raspberrypi4. You can check out this blog on how to achieve that. 

https://medium.com/@abdelsalam.h.a.a/boosting-yolov5-performance-on-cpu-with-quantization-techniques-for-raspberry-pi4-too-dc2e24f68269

**Comment by AbdelsalamHaa** [comment]
I will close this issue since it has been resolved, @yufenglee I will be delighted if you still can comment and give me some advice on how to debug and over come this kind of issue in the future. thanks
