### ISSUE TITLE
[Build] 

### ISSUE THREAD

**Issue by ankitmaurya001** [microsoft/onnxruntime#14263]
### Describe the issue

Has anyone able to build onnxruntime for Coral edge TPU?

### Target platform

Edge TPU (aarch64)

### Build script

docker build -t onnxruntime-source -f Dockerfile.arm64 ..

### Error / output

Successfully installed numpy-1.19.5
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2023-01-12 14:44:56,692 tools_python_utils [INFO] - flatbuffers module is not installed. parse_config will not be available
2023-01-12 14:44:56,730 build [DEBUG] - Command line arguments:
  --build_dir /code/build/Linux --skip_submodule_sync --config Release --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=1.14.0
2023-01-12 14:44:56,757 build [ERROR] - Failed to resolve executable path for 'cmake'.
The command '/bin/sh -c /code/dockerfiles/scripts/install_centos_arm64.sh && cd /code && CC=/opt/rh/devtoolset-10/root/usr/bin/gcc CXX=/opt/rh/devtoolset-10/root/usr/bin/g++ ./build.sh --skip_submodule_sync --config Release --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=$(cat ./VERSION_NUMBER)' returned a non-zero code: 1

**Comment by snnn** [comment]
ONNX Runtime doesn't have special support for Coral edge TPU. It cannot utilize the device. 

However, the build failure you got was:
```
2023-01-12 14:44:56,757 build [ERROR] - Failed to resolve executable path for 'cmake'.
```

Installing cmake will resolve it.
