### ISSUE TITLE
TensorRT engine cache fails due to ever increasing integer in engine filename

### ISSUE THREAD

**Issue by diablodale** [microsoft/onnxruntime#14269]
### Describe the issue

TensorRT EP generates engine cache files with ever increasing integers in filenames for new Sessions. Therefore, it never finds an existing cache file in the same process. It is required to stop/kill the process and restart for an engine cache to be found.

### To reproduce

* Create C++ app that uses given setup and config of this issue.
* App must create Ort::Env once on startup. Then with a ui element or keypress create/run/destroy an Ort::Session with the same model_file. The whole time, the app continues running with its single Env.
* App should use the TensorRT EP and configure it with...
```c++
OrtTensorRTProviderOptions options{};
options.device_id = 0; // code the device id needed
options.trt_max_workspace_size = 2ull * 1024 * 1024 * 1024; // same as default yet prevents warnings in console
options.trt_max_partition_iterations = 1000;                // same as default yet prevents warnings in console
options.trt_min_subgraph_size = 1;                          // same as default yet prevents warnings in console
options.trt_engine_cache_enable = 1;
options.trt_engine_cache_path = "C:\\blahblah\\mycustomdirectory";
session_options.AppendExecutionProvider_TensorRT(options);
session = Ort::Session(onnx_env, model_file.c_str(), session_options);
```

1. Run app. This creates an `Env`
2. Load model1 onnx file. This creates a `Session`. Many seconds later (mine takes 105 seconds) the session will start and you will see an engine file appear in the cache directory.
3. Cause the Session to gracefully stop/end. **Your app and Env are still running**
4. Again, load model1 onnx file. This creates a `Session`. Many seconds later (mine takes 105 seconds) the session will start and you will see a 2nd engine file appear in the cache directory.
5. Cause the Session to gracefully stop/end. **Your app and Env are still running**
6. Again, load model1 onnx file. This creates a `Session`. Many seconds later (mine takes 105 seconds) the session will start and you will see a 3rd engine file appear in the cache directory.
7. Stop/kill your app and its process.
8. Run app. This creates an `Env`
9. Load model1 onnx file. This creates a `Session`. In 1 or 2 seconds, the TensorRT EP will load a cached engine file and your session will start.
10. Cause the Session to gracefully stop/end. **Your app and Env are still running**
11. Again, load model1 onnx file. This creates a `Session`. In 1 or 2 seconds, the TensorRT EP will load a cached engine file and your session will start.
12. Cause the Session to gracefully stop/end. **Your app and Env are still running**
13. Again, load model1 onnx file. This creates a `Session`. In 1 or 2 seconds, the TensorRT EP will load a cached engine file and your session will start.
14. Cause the Session to gracefully stop/end. **Your app and Env are still running**
15. Again, load model1 onnx file. This creates a `Session`. Many seconds later (mine takes 105 seconds) the session will start and you will see a 4th engine file appear in the cache directory.

I suspect there is some global counter that is part of the generation of cache filenames. Every time a Session is started, this global counter is incremented. Therefore when the Session ends and a new Session starts (in the same app), its global counter has incremented higher than the already existing cache file. This means that cache files are never found unless the app is killed and therefore the global counter is reset.

When I isolated this in my app, I never got cache usage yet generated 4 engine cache files.
This is EXACTLY the same app config, model file, and even the same process.
Notice the `_1_` that increments +2 on each start of each Session.
```
TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_18389142000517052976_1_0.engine
TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_18389142000517052976_3_0.engine
TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_18389142000517052976_5_0.engine
TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_18389142000517052976_7_0.engine
```

I suspect the first session looks for `_1_`, doesn't find it, and then creates `_1_`
I suspect the second session looks for `_3_`, doesn't find it, and then creates `_3_`
I suspect the third session looks for `_5_`, doesn't find it, and then creates `_5_`
...and it repeats forever.

But on app/process kill and restart...
First session looks for `_1_`, finds and loads the cached engine.
Second session looks for `_3_`, finds and loads the cached engine.
Third session looks for `_5_`, finds and loads the cached engine.
Fourth session looks for `_7_`, doesn't find it, and then creates `_7_`

Logs of it loading cached engine files proving it is incrementing a counter and loading the cache file using that counter
```
onnxruntime:0 [tensorrt_execution_provider.cc:1333 onnxruntime::TensorrtExecutionProvider::Compile] [TensorRT EP] DeSerialized C:\Users\dale\AppData\Local\Temp\dp.oak\onnx.cache\vNgj4DQ6DoYtrYc5RUZLGz45KmY\TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_18389142000517052976_1_0.engine
onnxruntime:0 [tensorrt_execution_provider.cc:1333 onnxruntime::TensorrtExecutionProvider::Compile] [TensorRT EP] DeSerialized C:\Users\dale\AppData\Local\Temp\dp.oak\onnx.cache\vNgj4DQ6DoYtrYc5RUZLGz45KmY\TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_18389142000517052976_3_0.engine
onnxruntime:0 [tensorrt_execution_provider.cc:1333 onnxruntime::TensorrtExecutionProvider::Compile] [TensorRT EP] DeSerialized C:\Users\dale\AppData\Local\Temp\dp.oak\onnx.cache\vNgj4DQ6DoYtrYc5RUZLGz45KmY\TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_18389142000517052976_5_0.engine
```

Also strange is the dramatic difference in file sizes of the cached engine files. Again this is EXACTLY the same app config, model file, and they were saved in the same process. Smallest to largest is 56972 bytes, or 0.3% of its file size. 

```
-rwxr-x--- 1 dale dale 19531139 Jan 11 21:34 TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_18389142000517052976_1_0.engine
-rwxr-x--- 1 dale dale 19587407 Jan 11 21:35 TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_18389142000517052976_3_0.engine
-rwxr-x--- 1 dale dale 19582063 Jan 11 21:40 TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_18389142000517052976_5_0.engine
-rwxr-x--- 1 dale dale 19588111 Jan 11 21:42 TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_18389142000517052976_7_0.engine
```

### Platform

Windows

### OS Version

10.0.19045.2486

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

TensorRT

### Execution Provider Library Version

CUDA 11.4.152, cudnn 8.4.1, TensorRT 8.4.1.5

**Comment by jywu-msft** [comment]
thanks for reporting. yes this is an issue. we are in process of fixing it.
