### ISSUE TITLE
Still link MPI when --use_mpi=False [Build] 

### ISSUE THREAD

**Issue by Magnus1cheng** [microsoft/onnxruntime#14278]
### Describe the issue

https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/build.py#L1040 here says if set use_mpi as False, then Build will continue without linking MPI libraries. However, it is not the case when you actually build. If your build environment has openMPi, and https://github.com/microsoft/onnxruntime/blob/main/cmake/CMakeLists.txt#L1345 will find it and auto link dynamic libraries of MPI, no matter how you set use_mpi arguments. So, I'm not sure if this is a bug or the warning message should be changed. https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/build.py#L1044.
When you build onnxruntime in a environment with openMPI installed and set use_mpi as False, the onnxruntime binary will still dynamic links to openMPI binary.
This cause error when my bulding environment has openMPI  but installing environment does not.

### Target platform

CentOS Linux 7

### Build script

./build.sh --config Release \
           --build_shared_lib \
           --enable_training \
           --skip_tests \
           --skip_submodule_sync \
           --parallel \
           --build_wheel \
           --use_cuda \
           --cudnn_home /opt/sw_home/local/cuda \
           --cuda_home /opt/sw_home/local/cuda \
           --use_mpi=False \
           --disable_nccl 2>&1 | tee build.log

### Error / output

Error comes when you actually `import onnxruntime ` in python

### GCC / Compiler Version

gcc-9

**Comment by pengwa** [comment]
Created a PR fixing this issue, thanks for reporting!

**Comment by Magnus1cheng** [comment]
Issue resolved. Thank you!
