### ISSUE TITLE
[Build] The dynamic libraries released in v1.13.1 were compiled with which version of gcc?

### ISSUE THREAD

**Issue by liuyx-baller** [microsoft/onnxruntime#14276]
### Describe the issue

I used it on embedded linux, and the dynamic libraries released by v1.13.1 worked fine.
However, I wish to use a static library. I tried to compile using gcc 7.5, which compiled normally, but run into Segmentation fault。
Could you please provide the download address of gcc used when compiling v1.13.1? Thank you very much。

### Target platform

embedded linux

### Build script

cmake -Donnxruntime_GCC_STATIC_CPP_RUNTIME=ON -DCMAKE_BUILD_TYPE=Release -Dprotobuf_WITH_ZLIB=OFF -DCMAKE_TOOLCHAIN_FILE=.//tool.cmake  -Donnxruntime_BUILD_SHARED_LIB=OFF -Donnxruntime_DEV_MODE=OFF -DONNX_CUSTOM_PROTOC_EXECUTABLE=/home/liuyx/Desktop/bin/protoc -DCMAKE_INSTALL_PREFIX=`pwd`/install_aarch64 -Donnxruntime_ENABLE_PYTHON=OFF  ../cmake/

### Error / output

none

### GCC / Compiler Version

gcc 7.5

**Comment by liuyx-baller** [comment]
I used arm gcc 7.3(https://releases.linaro.org/components/toolchain/binaries/7.3-2018.05/aarch64-linux-gnu/gcc-linaro-7.3.1-2018.05-i686_aarch64-linux-gnu.tar.xz) to compile the v1.13.1 dynamic library. The compilation was successful, but the version of CXXABI required was too high。

```
# strings libonnxruntime-gcc73.so.1.13.1 | grep CXXABI
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_1.3.11
CXXABI_1.3.9
CXXABI_1.3
CXXABI_1.3.5
_ZSt11_Hash_bytesPKvmm@@CXXABI_1.3.5
__cxa_begin_catch@@CXXABI_1.3
__cxa_allocate_exception@@CXXABI_1.3
__cxa_guard_abort@@CXXABI_1.3
__cxa_guard_release@@CXXABI_1.3
_ZTVN10__cxxabiv117__class_type_infoE@@CXXABI_1.3
__cxa_free_exception@@CXXABI_1.3
__cxa_demangle@@CXXABI_1.3
_ZdlPvm@@CXXABI_1.3.9
_ZnwmSt11align_val_t@@CXXABI_1.3.11
_ZTVN10__cxxabiv120__si_class_type_infoE@@CXXABI_1.3
_ZdlPvSt11align_val_t@@CXXABI_1.3.11
__cxa_throw_bad_array_new_length@@CXXABI_1.3.8
__cxa_rethrow@@CXXABI_1.3
__cxa_end_catch@@CXXABI_1.3
__gxx_personality_v0@@CXXABI_1.3
__cxa_throw@@CXXABI_1.3
__cxa_thread_atexit@@CXXABI_1.3.7
__cxa_guard_acquire@@CXXABI_1.3
__cxa_pure_virtual@@CXXABI_1.3

```

But the officially released dynamic library does not require such a high CXXABI version.
```
CXXABI_1.3.7
CXXABI_1.3
CXXABI_1.3.5
```

Is it a different compiler or compiler command?

**Comment by snnn** [comment]
The binaries we released were not built in a cross-compile environment. 

1. So far python doesn't support cross-compiling yet, and we need to release python arm64 packages. 
2. We use Red Hat devtoolset to get a newer GCC with an old GLIBC. It is not possible in cross-compiling. 
 
So, to make things simpler, we build every thing in a CentOS7 arm64 docker image with GCC 9.x(or newer)
