### ISSUE TITLE
[Web]   pytorch export to onnx does not work on runtime-web but it does work locally

### ISSUE THREAD

**Issue by Pensarfeo** [microsoft/onnxruntime#14312]
### Describe the issue

I exported  yolov8 to onnx, following this tutorial:

https://github.com/ibaiGorordo/ONNX-YOLOv8-Object-Detection

Running the model with the tutorial works, however running the same model with runtime-web and I get this error:

"33220496" ( yes, a number)

### To reproduce

following this tutorial:
https://github.com/ibaiGorordo/ONNX-YOLOv8-Object-Detection

to generate the onnx model
Used the following script to load onnx, and run the model on a browser:
```js
function importModule(moduleUrl) {
    return new Promise((resolve, reject) => {
      const script = document.createElement('script');
      script.src = moduleUrl;
      script.onload = resolve;
      script.onerror = reject;
      document.head.appendChild(script);
    });
  }

  async function initOnnxModel() {
    await importModule('https://cdnjs.cloudflare.com/ajax/libs/onnxruntime-web/1.10.0/ort.min.js')
    const yolo = await ort.InferenceSession.create('./yolov8n.onnx');

  }
  initOnnxModel()
```

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.10.0

### Execution Provider

WASM

**Comment by shalvamist** [comment]
Hi Pensarfeo,

Thanks for the detailed report of the issue.
I think there are a couple of issue - 
1. the session creation is called with "await" 
2. The version of ORT Web is a bit old - currently we are at 1.13.0 and 1.14.0 is coming up :). Do you have a requirement to use this version?

I have run the following code locally on my machine and found it working - 
```
<script>
  function importModule(moduleUrl) {
    return new Promise((resolve, reject) => {
      const script = document.createElement('script');
      script.src = moduleUrl;
      script.onload = resolve;
      script.onerror = reject;
      document.head.appendChild(script);
    });
  }

  async function initOnnxModel() {
    await importModule('https://cdn.jsdelivr.net/npm/onnxruntime-web@1.13.1/dist/ort.min.js')
    const yolo = ort.InferenceSession.create('./yolov8n.onnx', { executionProviders: ["wasm"] });
  }
  initOnnxModel()
</script>
```

can you please try it on your end?

Thanks,
Shalva

**Comment by Pensarfeo** [comment]
@shalvamist Thanks! updating to 1.130 did the trick!
