### ISSUE TITLE
[Build] How could I use pre-build Microsoft.ML.OnnxRuntime.DirectML.1.13.1?

### ISSUE THREAD

**Issue by yunyaoXYY** [microsoft/onnxruntime#14325]
### Describe the issue

Hello,
I am trying to run the sample from here.  https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/fns_candy_style_transfer

I would like to know if I could use pre-build library from https://github.com/microsoft/onnxruntime/releases rather than build the onnxruntime with DirectML from source code? ( I ran the sample successfully when I build onnxruntime with DirectML from source code, but the build time is too long, I wonder if I can start from pre-build library, like download released package from github)

In this page https://github.com/microsoft/onnxruntime/releases, I download and [Microsoft.ML.OnnxRuntime.DirectML.1.13.1.zip](https://github.com/microsoft/onnxruntime/releases/download/v1.13.1/Microsoft.ML.OnnxRuntime.DirectML.1.13.1.zip), and do the following steps:

1)Then I build the samples using:
cmake .. -A x64 -T host=x64 -Donnxruntime_USE_DML=ON -DONNXRUNTIME_ROOTDIR=D:\XXX\Microsoft.ML.OnnxRuntime.DirectML.1.13.1 
,which shows 
![image](https://user-images.githubusercontent.com/109218879/212878511-817060cc-c587-4742-b35c-28b4d0615d1c.png)

2)Then I use devenv onnxruntime_samples.sln , open the VS2019， set the head files from D:\xieyunyao\Microsoft.ML.OnnxRuntime.DirectML.1.13.1\build\native\include
Set the dll from D:\xieyunyao\Microsoft.ML.OnnxRuntime.DirectML.1.13.1\runtimes\win-x64\native
And Finish the building of fns_candy_style_transfer project, get the .exe

3）I copy onnxruntime.dll to D:\XXX\onnxruntime-inference-examples-main\c_cxx\build\fns_candy_style_transfer\Debug and ready to start the .exe.

4)  Run in the VS2019 command prompt, 
When I use : fns_candy_style_transfer.exe candy.onnx image.png out.png cpu  , I got the result.
But When I use: fns_candy_style_transfer.exe candy.onnx image.png out.png dml , I Got Nothing, there is no error printed in the command prompt, just end without output (out.png).

### Urgency

Urgent.

### Target platform

Windows Intel CPU/ Intel Graphic Card

### Build script

Follow the documents

### Error / output

Can not build it from VS2019, I guess I build from a wrong way using pre-build Lib

### Visual Studio Version

2019

**Comment by snnn** [comment]
echo %ERROELEVEL%

Very likely the test process aborted.

**Comment by RyanUnderhill** [comment]
I tested with the pre-built Onnxruntime library linked here and it ran successfully for me.

You'll need to launch the process using the debugger to see why it's exiting.

**Comment by yunyaoXYY** [comment]
> I tested with the pre-built Onnxruntime library linked here and it ran successfully for me.
> 
> You'll need to launch the process using the debugger to see why it's exiting.

Hi，I launch the process and use debug mode， there is exception shows as below:
"
Exception thrown at 0x00007FFB231586E0 (directml.dll) in fns_candy_style_transfer.exe: 0xC0000005: Access violation writing location 0x00007FFB24C9F800.
"
![image](https://user-images.githubusercontent.com/109218879/215309792-068590cb-6f88-4a98-892d-f456b7aa6f82.png)

I meet the problem using Microsoft.ML.OnnxRuntime.DirectML.1.13.1 and Microsoft.ML.OnnxRuntime.DirectML.1.12.1 (Both version has this problem)

**Comment by yunyaoXYY** [comment]
> 

Hello， I meet the exception "Exception thrown at 0x00007FFB231586E0 (directml.dll) in fns_candy_style_transfer.exe: 0xC0000005: Access violation writing location 0x00007FFB24C9F800." at  the code of ORT_ABORT_ON_ERROR(OrtSessionOptionsAppendExecutionProvider_DML(session_options, 0));  The details are shown at last comments.

**Comment by yunyaoXYY** [comment]
> echo %ERROELEVEL%
> 
> Very likely the test process aborted.

Hello， I meet the exception "Exception thrown at 0x00007FFB231586E0 (directml.dll) in fns_candy_style_transfer.exe: 0xC0000005: Access violation writing location 0x00007FFB24C9F800." at the code of ORT_ABORT_ON_ERROR(OrtSessionOptionsAppendExecutionProvider_DML(session_options, 0)); The details are shown at last comments.

**Comment by yunyaoXYY** [comment]
I guess it could be the problem of "directml.dll" ? Because I did not find this file in [Microsoft.ML.OnnxRuntime.DirectML.1.13.1.zip](https://github.com/microsoft/onnxruntime/releases/download/v1.13.1/Microsoft.ML.OnnxRuntime.DirectML.1.13.1.zip) and also in https://github.com/microsoft/onnxruntime/releases/download/v1.12.1/Microsoft.AI.MachineLearning.1.12.1.zip

**Comment by nums11** [comment]
Closing as resolved.
