### ISSUE TITLE
Compatibility issue with gcc 8.3 and/or protobuf?

### ISSUE THREAD

**Issue by christian-vorhemus** [microsoft/onnxruntime#1433]
**Describe the bug**
When building onnxruntime (based on [this guide](https://github.com/Microsoft/onnxruntime/blob/master/BUILD.md#build)) on the latest Raspbian version ([Buster Lite](https://www.raspberrypi.org/downloads/raspbian/)) with the command `./build.sh --config RelWithDebInfo --build_wheel`, the linking of protoc fails with the following error message:

```
Scanning dependencies of target protoc
[ 28%] Building CXX object external/protobuf/cmake/CMakeFiles/protoc.dir/__/src/google/protobuf/compiler/main.cc.o​
[ 28%] Linking CXX executable protoc​
/usr/bin/ld: libprotobuf.a(arena.cc.o): in function `google::protobuf::internal::ArenaImpl::Init()':​
/usr/include/c++/8/bits/atomic_base.h:514: undefined reference to `__atomic_fetch_add_8'​
collect2: error: ld returned 1 exit status​
make[2]: *** [external/protobuf/cmake/CMakeFiles/protoc.dir/build.make:88: external/protobuf/cmake/protoc] Error 1​
make[1]: *** [CMakeFiles/Makefile2:1011: external/protobuf/cmake/CMakeFiles/protoc.dir/all] Error 2​
make: *** [Makefile:141: all] Error 2​
Traceback (most recent call last):​
  File "/home/pi/onnxruntime/tools/ci_build/build.py", line 910, in <module>​
    sys.exit(main())​
  File "/home/pi/onnxruntime/tools/ci_build/build.py", line 859, in main​
    build_targets(cmake_path, build_dir, configs, args.parallel)​
  File "/home/pi/onnxruntime/tools/ci_build/build.py", line 425, in build_targets​
    run_subprocess(cmd_args)​
  File "/home/pi/onnxruntime/tools/ci_build/build.py", line 181, in run_subprocess​
    return subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)​
  File "/usr/lib/python3.7/subprocess.py", line 487, in run​
    output=stdout, stderr=stderr)​
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/pi/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo']' returned non-zero exit status 2.​
```

I tried to use the protoc version which comes with onnxruntime in the cmake/externals folders first and got the error as shown above. Then, I built protoc v 3.9.0 from source as described [here](https://github.com/protocolbuffers/protobuf/tree/master/src#c-installation---unix) and set the env path to 

`export CMAKE_ARGS="-DONNX_CUSTOM_PROTOC_EXECUTABLE=/usr/local/bin/protoc"`

I got the same error message as above

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian Buster
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 0.4.0
- Python version: 3.4
- Visual Studio version (if applicable): -
- GCC/Compiler version (if compiling from source): (Raspbian 8.3.0-6+rpi1) 8.3.0​
- CUDA/cuDNN version: -
- GPU model and memory: -

**Comment by snnn** [comment]
See https://github.com/protocolbuffers/protobuf/pull/6337

**Comment by faxu** [comment]
@christian-vorhemus is your issue resolved?

**Comment by snnn** [comment]
To solve this issue, we need to upgrade protobuf to the latest, which is a not released version yet. So the operation has a risk. @faxu, please consider it and make a decision whether we want to fix this issue now, or delay it a few months.

**Comment by paulvid** [comment]
@snnn when is this planned to be released in protobuf?

**Comment by snnn** [comment]
Hi @paulvid , it's out of our control.  Protobuf is owned by Google. 
Before having it, you may:
1. in your local branch, update the protobuf module to the latest upstream version
2. In onnxruntime's cmake folder, open CMakeLists.txt and add a line of 
```
  list(APPEND onnxruntime_EXTERNAL_LIBRARIES atomic)
```
This line of code should be just before 
```
list(APPEND onnxruntime_EXTERNAL_LIBRARIES ${CMAKE_DL_LIBS} Threads::Threads)
```

The second step may not be necessary.

**Comment by faxu** [comment]
@christian-vorhemus does the suggested solution work for you to fix it just in a local fork? We don't plan to pick up a non-official release version of protobuf, but when they release the next version that includes the fix, we can update.

**Comment by christian-vorhemus** [comment]
I just tried to build onnxruntime by using the latest protobuf version 3.9.1 [which apparently fixed the compatibility issue](https://github.com/protocolbuffers/protobuf/releases/tag/v3.9.1). There is a new error coming up but it seems to be unrelated to protobuf, will look closer into it and potentially open a new issue.

**Comment by snnn** [comment]
Thanks.

**Comment by snnn** [comment]
I'll close it when our protobuf version is upgraded to 3.9.1

**Comment by snnn** [comment]
Hi @christian-vorhemus , we can't do the update because the latest protobuf has a bug that it doesn't work in Windows x86 32bits mode.

protocolbuffers/protobuf#6098

We have to wait them fixing it.

**Comment by snnn** [comment]
Protobuf 3.11 will be released soon, it will include my fix.
