### ISSUE TITLE
[Build] Prebuilt Binaries GPU fails - Building from Source with Cuda works

### ISSUE THREAD

**Issue by fischeruben** [microsoft/onnxruntime#14364]
### Describe the issue

I want to run some models with cuda. For that purpose is downloaded the prebuilt binaries onnxruntime-gpu v1.13.1. The following lines of code fail

  auto env = Ort::Env(ORT_LOGGING_LEVEL_ERROR, "Foobar");
  auto session_opt = Ort::SessionOptions();
  auto cuda_options = OrtCUDAProviderOptions();
  session_opt.AppendExecutionProvider_CUDA(cuda_options);

With error message (sorry for the german):
Ausnahme ausgelöst bei 0x00007FFD52FC21B0 (onnxruntime.dll) in SurfaceInspectionModules_UnitTestd.exe: 0xC0000005: Zugriffsverletzung beim Lesen an Position 0x000000000000001F.

The only further information I get ist, that this exception happens several calls deeper in. Three calls in onnxruntime.dll, three calls in onnxruntime_providers_cuda.dll, then finally a call in onnxruntime.dll fails.

I have then built the binaries from source (tag v1.13.1) with Debug to be able to look at the failing call. The build command was 

build.bat --config Debug --build_shared --parallel --cmake_generator "Visual Studio 16 2019" --use_cuda --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6" --cuda_version "11.6"

Using the generated binaries, the same code above works without a problem. This poses some questions:

1. Does the build use some local information?
2. Does this mean that I cannot port the prebuilt binaries?
3. Can I get some information which are the limitations of portability? I really don't want to build for every machine, I want to run my code on.

### Target platform

window 10 

### Build script

build.bat --config Debug --build_shared --parallel --cmake_generator "Visual Studio 16 2019" --use_cuda --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6" --cuda_version "11.6"

### Error / output

No error with my own build, but an error with prebuilt binaries.

### Visual Studio Version

msvc2019

### GCC / Compiler Version

--

**Comment by fischeruben** [comment]
Maybe as additional info: I have cuda 11.6.55 and cudnn 8.5.0 installed, as distributed by nvidia. Which should be the recommended versions.

**Comment by fischeruben** [comment]
And another curiosity: Running onnxruntime-gpu with the python package works just fine and uses the GPU. So it might be independent of the installed cuda.

**Comment by yuslepukhin** [comment]
It is difficult to repro the problem without the model and your code. Python and C++ APIs are using the same binaries. You might want to show your code. It is also possible that the issue has to do with your C++ program failing to find the relevant shared libraries while running when built with NuGet and it is easily found in the build tree.

> Does the build use some local information?

No.

> Does this mean that I cannot port the prebuilt binaries?

It does not.

>Can I get some information which are the limitations of portability? I really don't want to build for every machine, I want to run my code on.

There should not be limitations. While the binaries have certain CUDA code compiled it, CUDA would re-compile kernels on the fly.

However, you must have VS Redist installed on your machine in order to run. We are working to improve documentation in this regard.

**Comment by fischeruben** [comment]
Update: I built release from v1.13.1 with the same remaining arguments. Running my code with prebuilt binaries, I get the error. Switching out just the dll's with my own custom built ones, all is fine.

Regarding Code and model: I do not think that this is a code issue. But for completeness sake, I will include the unittest. A model is not involved at any time.

test.cpp:
```
#include <chrono>
#include <thread>
#include <memory>

#include <LoggingHelper.h>
#include <catch2/catch.hpp>

#include "onnxruntime_cxx_api.h"

TEST_CASE("Simple cuda test")
{
	MELOG_INFO(Catch::getResultCapture().getCurrentTestName());

	auto env = Ort::Env(ORT_LOGGING_LEVEL_ERROR, "CudaTest");
	auto session_opt = Ort::SessionOptions();
	auto cuda_opt = OrtCUDAProviderOptions{};
	session_opt.AppendExecutionProvider_CUDA(cuda_opt);

	REQUIRE(cuda_opt.device_id == 0);
}
```

main.cpp:

```
#define CATCH_CONFIG_RUNNER
#include <catch2/catch.hpp>

// Include for detecting memory leaks
// Note: Must be the last include!
#include "debug_new.h"

int main(int argc, char * argv[])
{
#if defined(_WIN32) && defined(_DEBUG)
  _CrtSetDbgFlag(_CRTDBG_LEAK_CHECK_DF | _CRTDBG_ALLOC_MEM_DF);
#endif // _WIN32 && _DEBUG

  // catch test cases instantiation
  int result = Catch::Session().run(argc, argv);
  // system("pause"); // please do not check this line without comment
  return (result < 0xff ? result : 0xff);
}
```

Regarding missing Dependencies: Unless prebuilt and custom build require different dll's, which by the above statement should not happen, I don't see how that could be an issue. I do not do anything else, but switching out the onnxruntime.dll, onnxruntime_provider_cuda.dll and onnxruntime_provider_shared.dll.

**Comment by fischeruben** [comment]
I am sorry for the unneeded trouble. Turns out the dll was corrupted - I don't know how it happened. Downloading from the repo solved the issue.
