### ISSUE TITLE
DirectML becomes  slower than CUDA in build 1.14 (When change batch numbers of session) - premature optimization?

### ISSUE THREAD

**Issue by pauldog** [microsoft/onnxruntime#14387]
### Describe the issue

For onnxruntime I have found that in DirectML mode, if I first run a input through the Unet Onnx with x batchs and then do a different input with a different number of batches the second time is less efficient than the first. It seems like the session get's optimised for a particular sized input. The only way to combat this is to reload the session from the disk.

I thought I'd just put this issue here for posterity.
(Using latest developer build of onnxruntime 1.14.)

In the following I did the guidance=1 case first. But I get **different results** if I do the experiment running the model with guidance>1 first.  e.g. if I but guidance>1 first I get 0.78 seconds for DirectML (f16) instead of 0.95 but then 0.6 seconds switich to guidance=1

For guidance=1 (batch size=1)
(f32) **0.44 seconds** for DirectML vs 0.47 for CUDA
(f16) 0.42 seconds for DirectML vs 0.38 for CUDA
For guidance>1 (batch size=2) [Reusing same sessions]
(f32) 0.92 seconds for DirectML vs 0.83 CUDA     **(0.77 for DirectML if do this one first  - or reload session)**
(f16) 0.95 seconds for DirectML vs 0.77 for CUDA  **(0.78 for DirectML if do this one first - or reload session)**

I have Quadro P5000 graphics card.

We see that DirectML is roughly equal to or better than CUDA, except if you reuse the session and have a different sized input. Then it is far worse. 

I understand you are not to supposed to change the shape of the dynamic input, but should this also apply to batch numbers? And if so, why does CUDA not have this problem?

**QUESTION**
Is there a way to tell the session to reoptimize itself for a different sized input, or must I reload the session from the disk. CUDA doesn't have this problem!

### To reproduce

run unet onnx from stable diffusion f16 version.
First run the session with 1 batch several times. Then with 2 several times.
Repeat the experiment but the other way round.
try it with CUDA and DirectML providers.
Use graphics card Nvidia Quadro P5000 (equivalent to GTX 1080)

### Platform

Windows

### OS Version

Windows 10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

CUDA, DirectML

**Comment by canaxx** [comment]
How did you make DirectML  run ?

**Comment by pauldog** [comment]
> How did you make DirectML run ?

Are you using c#? Make sure you download the latest DirectML.dll version and put it in your project folder.

**Comment by nums11** [comment]
Closing as stale.
