### ISSUE TITLE
Onnxruntime-DirectML 1.14  inference blocks main thread.

### ISSUE THREAD

**Issue by pauldog** [microsoft/onnxruntime#14388]
### Describe the issue

I was running onnxruntime in Unity c#. The previous version didn't block the main thread.

Now when I update to onnxruntime 1.14 the models load on their own thread.

But when I run inference it blocks the main thread. And the graphics freeze until the inference is finished.

This is a problem with DirectML only as CUDA doesn't block and it can run on it's own thread. Nor does loading the models block anything.

Also in the previous version DirectML didn't block. 

Yes, now DirectML is 2x faster in this new build but unfortunately (unlike CUDA) it blocks the main thread. (Or blocks something in the GPU which stops the graphics showing).

### To reproduce

Try running inference session in c# on a separate thread while drawing other graphics to the screen.

### Platform

Windows

### OS Version

Windows 10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

DirectML

**Comment by pauldog** [comment]
I think I may have sort of solved the issue by making my Unity version work in DirectX 11 mode instead of DirectX 12 mode.

Perhaps there was some sort of collision between DirectML working in DirectX 12 mode and also Unity.

Not sure if this is the best solution or just a work around.

**Comment by nums11** [comment]
Closing as stale.
