### ISSUE TITLE
[Feature Request]  NNAPI Execution provider session options enable is not working

### ISSUE THREAD

**Issue by ravitejaj90** [microsoft/onnxruntime#14419]
### Describe the feature request

Enabled session options for NNAPI execution provider. But ONNX inferencing is not working. 

Hi,

when enabled the session options execution provider NNAPI(OrtSessionOptionsAppendExecutionProvider_Nnapi). 
Getting error as neural networks passed a nullpointer.

please provide some inputs on this 

Enabled NNAPI session option code:
============================
Ort::SessionOptions *gp_session_options_;

allocator = Ort::AllocatorWithDefaultOptions();
gp_session_options_ = new Ort::SessionOptions();
gp_session_options_->SetIntraOpNumThreads(3);
gp_session_options_->SetExecutionMode(ORT_PARALLEL);

*uint32_t nnapi_flags = 0;
Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_Nnapi(*gp_session_options_, nnapi_flags));*

gp_session_options_->SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_DISABLE_ALL);

Log snippet:
============
// Sessions option enabled 
01-19 18:32:33.337 16761 16761 I onnxruntime:  [I:onnxruntime:, inference_session.cc:1213 Initialize] Initializing session.
01-19 18:32:33.338 16761 16761 I onnxruntime:  [I:onnxruntime:, inference_session.cc:1250 Initialize] Adding default CPU execution provider.
01-19 18:32:33.338 16761 16761 I onnxruntime:  [I:onnxruntime:, bfc_arena.cc:26 BFCArena] Creating BFCArena for Cpu with following configs: initial_chunk_size_bytes: 1048576 max_dead_bytes_per_chunk: 134217728 initial_growth_chunk_size_bytes: 2097152 memory limit: 18446744073709551615 arena_extend_strategy: 0
01-19 18:32:33.338 16761 16761 V onnxruntime:  [V:onnxruntime:, bfc_arena.cc:62 BFCArena] Creating 21 bins of max 

//Onnx run time logs 
01-19 18:32:33.396 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [1] Operator type: [Reshape] index: [215] name: [Reshape_3] as part of the NodeUnit type: [Reshape] index: [215] name: [Reshape_3]
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [1] Operator type: [Reshape] index: [211] name: [Reshape_2] as part of the NodeUnit type: [Reshape] index: [211] name: [Reshape_2]
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [1] Operator type: [Reshape] index: [227] name: [Reshape_5] as part of the NodeUnit type: [Reshape] index: [227] name: [Reshape_5]
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [1] Operator type: [Reshape] index: [223] name: [Reshape_4] as part of the NodeUnit type: [Reshape] index: [223] name: [Reshape_4]
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [1] Operator type: [Reshape] index: [269] name: [Reshape_11] as part of the NodeUnit type: [Reshape] index: [269] name: [Reshape_11]
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [1] Operator type: [Reshape] index: [265] name: [Reshape_10] as part of the NodeUnit type: [Reshape] index: [265] name: [Reshape_10]
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [1] Operator type: [Reshape] index: [257] name: [Reshape_9] as part of the NodeUnit type: [Reshape] index: [257] name: [Reshape_9]
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [1] Operator type: [Reshape] index: [253] name: [Reshape_8] as part of the NodeUnit type: [Reshape] index: [253] name: [Reshape_8]
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [1] Operator type: [Reshape] index: [293] name: [Reshape_15] as part of the NodeUnit type: [Reshape] index: [293] name: [Reshape_15]
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [1] Operator type: [Reshape] index: [289] name: [Reshape_14] as part of the NodeUnit type: [Reshape] index: [289] name: [Reshape_14]
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [1] Operator type: [Reshape] index: [239] name: [Reshape_7] as part of the NodeUnit type: [Reshape] index: [239] name: [Reshape_7]
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [1] Operator type: [Reshape] index: [235] name: [Reshape_6] as part of the NodeUnit type: [Reshape] index: [235] name: [Reshape_6]
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:409 operator()] Dynamic shape is not supported for now, for input:conv2d_218.tmp_0
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [0] Operator type: [BatchNormalization] index: [1] name: [BatchNormalization_0] as part of the NodeUnit type: [BatchNormalization] index: [1] name: [BatchNormalization_0]
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:409 operator()] Dynamic shape is not supported for now, for input:batch_norm_0.tmp_3
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [0] Operator type: [Add] index: [2] name: [Add_0] as part of the NodeUnit type: [Add] index: [2] name: [Add_0]
01-19 18:32:33.397 16761 16761 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:409 operator()] Dynamic shape is not supported for now, for input:Add_0
01-19 18:32:33.398 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [0] Operator type: [Clip] index: [3] name: [Clip_0] as part of the NodeUnit type: [Clip] index: [3] name: [Clip_0]
01-19 18:32:33.398 16761 16761 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:409 operator()] Dynamic shape is not supported for now, for input:batch_norm_0.tmp_3
01-19 18:32:33.398 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [0] Operator type: [Mul] index: [4] name: [Mul_0] as part of the NodeUnit type: [Mul] index: [4] name: [Mul_0]
01-19 18:32:33.398 16761 16761 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:409 operator()] Dynamic shape is not supported for now, for input:Mul_0
01-19 18:32:33.398 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [0] Operator type: [Div] index: [5] name: [Div_0] as part of the NodeUnit type: [Div] index: [5] name: [Div_0]
01-19 18:32:33.398 16761 16761 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:409 operator()] Dynamic shape is not supported for now, for input:hardswish_0.tmp_0
01-19 18:32:33.398 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [0] Operator type: [Conv] index: [6] name: [Conv_1] as part of the NodeUnit type: [Conv] index: [6] name: [Conv_1]
01-19 18:32:33.398 16761 16761 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:409 operator()] Dynamic shape is not supported for now, for input:conv2d_219.tmp_0
01-19 18:32:33.398 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [0] Operator type: [BatchNormalization] index: [7] name: [BatchNormalization_1] as part of the NodeUnit type: [BatchNormalization] index: [7] name: [BatchNormalization_1]
01-19 18:32:33.423 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [0] Operator type: [Conv] index: [276] name: [Conv_66] as part of the NodeUnit type: [Conv] index: [276] name: [Conv_66]
01-19 18:321-19 18:32:33.423 16761 16761 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:409 operator()] Dynamic shape is not supported for now, for input:conv2d_264.tmp_0
01-19 18:32:33.423 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [0] Operator type: [Add] index: [258] name: [Add_46] as part of the NodeUnit type: [Add] index: [258] name: [Add_46]
01-19 18:32:33.423 16761 16761 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:409 operator()] Dynamic shape is not supported for now, for input:conv2d_271.tmp_0
01-19 18:32:33.423 16761 16761 V onnxruntime:  [V:onnxruntime:, nnapi_execution_provider.cc:146 operator()] Node supported: [0] Operator type: [GlobalAveragePool] index: [287] name: [GlobalAveragePool_7] as part of the NodeUnit type: [GlobalAveragePool] index: [287] name: [GlobalAveragePool_7]
01-19 18:32:33.423 16761 16761 V onnxruntime:  [V:onnxruntime:, op_support_checker.cc:409 operator()] Dynamic shape is not supported for now, for input:conv2d_269.tmp_0
......

01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, op_builder.cc:553 AddToModelBuilder] Operator name: [Reshape_8] type: [Reshape] was added
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:486 AddOperations] Adding node [293]
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, op_builder.cc:805 CanSkipReshape] Reshape/Flatten can not be skipped when the output is a graph output, output name, Reshape_15
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:404 AddNewOperand] operand name: Reshape_15conv2d_52.b_0newshape_token_14
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:404 AddNewOperand] operand name: Reshape_15
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:539 AddOperation] Added NNAPI Operation Type [22]
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, op_builder.cc:553 AddToModelBuilder] Operator name: [Reshape_15] type: [Reshape] was added
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:486 AddOperations] Adding node [289]
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, op_builder.cc:805 CanSkipReshape] Reshape/Flatten can not be skipped when the output is a graph output, output name, Reshape_14
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:404 AddNewOperand] operand name: Reshape_14conv2d_51.b_0newshape_token_15
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:404 AddNewOperand] operand name: Reshape_14
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:539 AddOperation] Added NNAPI Operation Type [22]
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, op_builder.cc:553 AddToModelBuilder] Operator name: [Reshape_14] type: [Reshape] was added
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:486 AddOperations] Adding node [239]
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, op_builder.cc:805 CanSkipReshape] Reshape/Flatten can not be skipped when the output is a graph output, output name, Reshape_7
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:404 AddNewOperand] operand name: Reshape_7conv2d_49.b_0newshape_token_16
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:404 AddNewOperand] operand name: Reshape_7
01-19 18:32:33.441 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:539 AddOperation] Added NNAPI Operation Type [22]
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, op_builder.cc:553 AddToModelBuilder] Operator name: [Reshape_7] type: [Reshape] was added
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:486 AddOperations] Adding node [235]
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, op_builder.cc:805 CanSkipReshape] Reshape/Flatten can not be skipped when the output is a graph output, output name, Reshape_6
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:404 AddNewOperand] operand name: Reshape_6conv2d_48.b_0newshape_token_17
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:404 AddNewOperand] operand name: Reshape_6
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model_builder.cc:539 AddOperation] Added NNAPI Operation Type [22]
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, op_builder.cc:553 AddToModelBuilder] Operator name: [Reshape_6] type: [Reshape] was added
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_17 shape [ 1 1 1 1 ]
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_16 shape [ 1 24 1 1 ]
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_13 shape [ 1 24 1 1 ]
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_12 shape [ 1 6 1 1 ]
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_1 shape [ 1 96 1 1 ]
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_0 shape [ 1 24 1 1 ]
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_3 shape [ 1 96 1 1 ]
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_2 shape [ 1 24 1 1 ]
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_5 shape [ 1 96 1 1 ]
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_4 shape [ 1 24 1 1 ]
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_11 shape [ 1 24 1 1 ]
01-19 18:32:33.442 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_10 shape [ 1 6 1 1 ]
01-19 18:32:33.443 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_9 shape [ 1 24 1 1 ]
01-19 18:32:33.443 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_8 shape [ 1 6 1 1 ]
01-19 18:32:33.443 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_15 shape [ 1 24 1 1 ]
01-19 18:32:33.443 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_14 shape [ 1 6 1 1 ]
01-19 18:32:33.443 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_7 shape [ 1 96 1 1 ]
01-19 18:32:33.443 16761 16761 V onnxruntime:  [V:onnxruntime:, model.cc:36 AddOutput] Model::AddOutput output name Reshape_6 shape [ 1 24 1 1 ]

*01-19 18:32:33.443 16761 16761 E NeuralNetworks: ANeuralNetworksModel_identifyInputsAndOutputs passed a nullptr
01-19 18:32:33.455 16761 16761 E Threat_Detector[OnnxSession]: Error code is 1*

### Describe scenario use case

To run the model inferencing on the accelerators to increase the performance.

**Comment by skottmckay** [comment]
Can you please share the model you're trying to load?

**Comment by ravitejaj90** [comment]
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/models_list_en.md#2.2

We have converted the raw model to onnx model and tries to excute using NNAPI.

**Comment by natke** [comment]
@ravitejaj90 Can you share the ONNX file that you are trying to load?

**Comment by ravitejaj90** [comment]
[text_detection_paddle.zip](https://github.com/microsoft/onnxruntime/files/10529191/text_detection_paddle.zip)
Uploaded the ONNX file. please let me know if any extra information is needed

**Comment by YUNQIUGUO** [comment]
hi there,

I am trying to repro the same issue locally and had a trial run with the text_detection_paddle.onnx model you attached. Seems like the model input is dynamic input shape and currently it's not supported by nnapi ep. 

But from your log, looks like you did pass in a fixed shape. maybe would you mind sharing what's the exact set up you had on your end to help me reproduce it locally? Thanks!

![Screenshot 2023-02-06 at 3 12 45 PM](https://user-images.githubusercontent.com/35738743/217108368-c4771e94-9f75-4886-b6cb-aa14c5ce44a4.png)

And from my log currently will only show : 

_02-06 15:00:05.703 30322 30322 V onnxruntime:  [V:onnxruntime:Verbose, base_op_builder.cc:104 operator()] Dynamic shape is not supported for now, for input:x
02-06 15:00:05.703 30322 30322 V onnxruntime:  [V:onnxruntime:Verbose, nnapi_execution_provider.cc:143 operator()] Node supported: [0] Operator type: [Conv] index: [0] name: [p2o.Conv.0] as part of the NodeUnit type: [Conv] index: [0] name: [p2o.Conv.0]
02-06 15:00:05.703 30322 30322 V onnxruntime:  [V:onnxruntime:Verbose, base_op_builder.cc:104 operator()] Dynamic shape is not supported for now, for input:batch_norm_0.tmp_3
02-06 15:00:05.703 30322 30322 V onnxruntime:  [V:onnxruntime:Verbose, nnapi_execution_provider.cc:143 operator()] Node supported: [0] Operator type: [Add] index: [2] name: [p2o.Add.0] as part of the NodeUnit type: [Add] index: [2] name: [p2o.Add.0]
02-06 15:00:05.703 30322 30322 V onnxruntime:  [V:onnxruntime:Verbose, base_op_builder.cc:104 operator()] Dynamic shape is not supported for now, for input:p2o.Add.1
02-06 15:00:05.703 30322 30322 V onnxruntime:  [V:onnxruntime:Verbose, nnapi_execution_provider.cc:143 operator()] Node supported: [0] Operator type: [Clip] index: [3] name: [p2o.Clip.0] as part of the NodeUnit type: [Clip] index: [3] name: [p2o.Clip.0]_

Thanks!

**Comment by YUNQIUGUO** [comment]
just another fyi: there's a tool for making the dynamic input shapes for the models to be fixed for it to be run on NNAPI:
https://onnxruntime.ai/docs/tutorials/mobile/helpers/make-dynamic-shape-fixed.html
