### ISSUE TITLE
[Feature Request] Make Sessions available through Environment

### ISSUE THREAD

**Issue by fischeruben** [microsoft/onnxruntime#14418]
### Describe the feature request

I am in the following scenario: There are several threads that want to call the same model/session. For efficiency's sake I do not want to make one session for each thread. 
I am aware that there are environment options that mitigate the inefficiency (like shared initializers), but as far as i know there is no clean solution - I am happy to be convinced otherwise.
So my solution would be to create some shared memory where one session lives and the threads can access it.

However the environment is already a global object. So if I could register the sessions in the environment and make them accessible via the env, I would have a clean solution that is living inside the onnxruntime. 
The first thread would register the session and any successive call would use the already registered session.

Would that be a common use-case, i.e. worth to implement?
Or is there a better solution that is already supported by the onnxruntime?

### Describe scenario use case

Multithreading, where each thread wants to call the same model/session.

**Comment by yuslepukhin** [comment]
Why don't you create just one session and make it available to all the threads which then can call Run() on it? It is a feature of Onnxruntime.

**Comment by fischeruben** [comment]
As I said above, I can do that, yes. In the framework, I am working in, getting access to the shared memory between the threads is connected to some complications, I would like to avoid.

I was just wondering, why the sessions are not global, while the environment is. Is there a good reason, why the environment should not have say a weak pointer to its sessions?

**Comment by fischeruben** [comment]
Ok. Seems like there is no interest. Closing.
