### ISSUE TITLE
[Performance] INT8 model is running 10x slower than FP32 version

### ISSUE THREAD

**Issue by gianmarcocr** [microsoft/onnxruntime#14439]
### Describe the issue

i'm trying to get an INT8 model running on TensorRT as EP and it runs 10x slower than its counterpart fp32an

### To reproduce

I followed this exact [tutorial](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/image_classification/trt/resnet50/e2e_tensorrt_resnet_example.py) found in the official [docs.](https://onnxruntime.ai/docs/performance/quantization.html#quantization-on-gpu)
then I ran this simple script to compare the runtimes:

```
import onnxruntime as ort
import onnx
import numpy as np
import time
from tqdm import tqdm

batch_size = 8

so = ort.SessionOptions()
so.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
prov = [('TensorrtExecutionProvider',{"device_id":0,
                                      'trt_int8_enable': True,
                                      "trt_engine_cache_enable" : True,
                                      "trt_engine_cache_path" : r"D:\Projects_AI\2023_01_26_quantize",
                                      "trt_int8_calibration_table_name": "calibration.flatbuffers" }),
                                'CUDAExecutionProvider']


def infer(model_path, x):
    m = onnx.load(model_path)
    ort_session = ort.InferenceSession(model_path,sess_options=so, providers=prov)
    t = []
    for i in tqdm(range(100)):
        start = time.time()
        ort_session.run(None, {m.graph.input[0].name: x})
        end = time.time()
        t.append(end-start)
    tmean = sum(t) / (len(t)*batch_size)
    print(tmean)
    return tmean


model_quant =r"D:\Projects_AI\2023_01_26_quantize\augmented_model.onnx"
x = np.random.uniform(size=(8, 3, 224, 224)).astype("float32")
t_quant = infer(model_quant, x)

model_orig =r"D:\Projects_AI\2023_01_26_quantize\resnet50-v2-7.onnx"
t_orig = infer(model_orig, x)
```

what I get is (per image)
- **INT8: 0.341 s**
- **FP32: 0.033 s**

I'm using:
- GPU: RTX 2070
- CUDA: 11.4.4
- TRT: 8.4.1.5
- ONNXRUNTIME-GPU: 1.13.1

Also why the official tutorial enables both fp16 and int8 on TRT? shouldn't it be int8 enough?

Why the graph obtained with quantization looks this weird? 
![image](https://user-images.githubusercontent.com/43784889/214871232-44b4892d-26c2-420b-a0e2-8b15a56d6907.png)
the original graph is the following:
![image](https://user-images.githubusercontent.com/43784889/214871900-ae5f99a7-6001-4288-9a9d-22af647b6e15.png)

### Platform

Windows

### OS Version

10 22H2

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

TensorRT

### Execution Provider Library Version

CUDA: 11.4.4, TRT: 8.4.1.5

### Model File

models on [Gdrive](https://drive.google.com/drive/folders/11AStGTcvA5PArVmpeeAzJF95dfwFEyeQ?usp=sharing)

### Is this a quantized model?

Yes

**Comment by yufenglee** [comment]
"D:\Projects_AI\2023_01_26_quantize\augmented_model.onnx" is the model for calibration. It is not the quantized model. 

There should be a calibrated table generated. You can use the calibrated table and original model to create InfereceSession to run in quantization mode for TRT EP. 

Please refer to:https://github.com/microsoft/onnxruntime-inference-examples/blob/d8afbb845ff19853183f27fe57fc4e749694f727/quantization/image_classification/trt/resnet50/e2e_tensorrt_resnet_example.py#L358

@stevenlix and @chilo-ms, please provide more details.

**Comment by pauldog** [comment]
From what I read, for most GPUs, uint8 is going to be really slow unless you have some kind of super tensor-core thingamejig.
I think float16 is the best speed for most commerical graphics cards such as GTX 1080. Someone correct me if I'm wrong.

**Comment by gianmarcocr** [comment]
thank you @yufenglee. the model now works as expected and it's way faster.
@pauldog from what I've understood both ways are helpful in accelerating the model. Still, for me, FP16 conversion never worked: I followed this https://natke.github.io/onnxruntime/docs/performance/float16.html but neither of the methods was able to produce a model that could work using TRT EP. the model was either running slower than fp32 counterparts or producing meaningless outputs.
