### ISSUE TITLE
SafeIntOnOverflow in non-existent node Transpose_719

### ISSUE THREAD

**Issue by Numeri** [microsoft/onnxruntime#14454]
### Describe the issue

I am seeing the following exception for a model in production:
```
2023-01-22 13:09:51.094435070 [E:onnxruntime:, sequential_executor.cc:369 Execute] Non-zero status code returned while running Transpose node. Name:'Transpose_719' Status Message: /onnxruntime_src/onnxruntime/core/common/safeint.h:17 static void SafeIntExceptionHandler<onnxruntime::OnnxRuntimeException>::SafeIntOnOverflow() Integer overflow

Traceback (most recent call last):
  File "script.py", line 258, in main
    session.run(outputs, inputs, run_options=run_options)
  File "/path/to/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Transpose node. Name:'Transpose_719' Status Message: /onnxruntime_src/onnxruntime/core/common/safeint.h:17 static void SafeIntExceptionHandler<onnxruntime::OnnxRuntimeException>::SafeIntOnOverflow() Integer overflow
```

This is occurring in the decoder graph of a Transformer model, and seems (although I unfortunately can't prove it) to be correlated to very large inputs (batches that are pushing the limits of the NVIDIA T4 GPU's 16GiB of memory – a batch size of around 70 to 300 and up to 1500 tokens per segment). I was testing segments that caused OOMs, and this exception came up more often in the datasets with more OOMs, and far less often in the more normal datasets.

My reason for submitting this issue, and my main question is: Why is it reporting that this occurs in node `Transpose_719`? My model does not have 719 Transpose nodes – it doesn't have 719 nodes total! Occasionally, this exception also occurs for the nodes `Concat_718` and `Transpose_15`, neither of which exist in my model, either. 

Is there documentation on where the node names reported in this exception come from? I'm not sure how to debug this further without knowing where this integer overflow is occurring.

Edit: For the session used in these tests, I first loaded it into ORT with all optimizations enabled, then exported and used that optimized graph for everything mentioned above. The session is created with
`onnxruntime.GraphOptimizationLevel.ORT_DISABLE_ALL` to ensure that the ONNX graph I can see/inspect in Netron is identical to the one being run.

### To reproduce

I unfortunately cannot share the ONNX graph producing this. I'd be very open to being told next steps for debugging this, and following them myself, so that I can find a shareable minimal example graph and set of inputs that triggers this.

### Platform

Linux

### OS Version

Ubuntu 20

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU, CUDA

**Comment by andrekh** [comment]
the graph being run might not be exactly the one you see when opening the onnx file.
the model is optimized by ORT before being run.
you should create an inference session with your model and dump the optimized model to disk.
maybe this optimized model has the nodes it is talking about.

**Comment by Numeri** [comment]
@andrekh Thanks! I should have mentioned that I did that, and use the optimized graphs in all of my sessions here, which I then run with `onnxruntime.GraphOptimizationLevel.ORT_DISABLE_ALL`. I'll edit that into my question :)

**Comment by skottmckay** [comment]
The node name is specified in the model and is an arbitrary unique string, so 'X_12345' doesn't mean there are 12345 nodes. Technically nodes don't even require names. 

Are there any Scan, Loop or If nodes? Those will have subgraphs with additional nodes. You can navigate to the subgraph using Netron.

**Comment by Numeri** [comment]
@scottmckay Thanks for your reply! It's exported from PyTorch, so, as I understand it, each node is automatically named with the name of the module it belongs to, and if there are more than one of the same node type in a module, they are named sequentially, which is why I was expecting `Transpose_719` to be the 719th transpose node in some kind of context (e.g., nodes could hypothetically be renamed internally when loaded onto the GPU, or something else I'm unaware of).

The graph has no subgraphs, no conditionals or flow control operators, etc. Searching for `Transpose_719`, `Transpose_15` or `Concat_718` in Netron comes up with nothing. There are Transpose and Concat nodes, but the highest number is 4 (i.e., no PyTorch module had more than 4 Transposes), with maybe 15 or 16 Transposes in total.

**Comment by Numeri** [comment]
The model was updated in production without me being told, so the model I was examining in Netron was _not_ the model that was throwing this error. Sorry about that! Closing this issue.
