### ISSUE TITLE
Will have plan to support RISC-V processor? Or how to port to different processor?

### ISSUE THREAD

**Issue by rayeh5** [microsoft/onnxruntime#145]
Will you have plan to support more processors or can provide porting guide.

**Comment by pranavsharma** [comment]
Not at this time. We welcome contributions.

**Comment by pranav-prakash** [comment]
The existing arm cross-compile flow gets you 95% of the way there. The only major changes to be made are substituting the SIMD mlas functions with scalar equivalents. Ideally you'd make use of the v-extension but that's still a wip. 

I'm maintaining a [fork](https://github.com/pranav-prakash/onnxruntime-riscv) that works on riscv. It also supports the [gemmini](https://arxiv.org/abs/1911.09925) matmul accelerator (a rocc co-processor).
