### ISSUE TITLE
[SNPE] C# sample error on Windows DevKit 2023

### ISSUE THREAD

**Issue by thnkim** [microsoft/onnxruntime#14502]
### Describe the issue

When I run vgg16_image_classification C# sample in onnxruntime-inference-example, I got error at options.AppendExecutionProvider. It looks a string is regarded as 1961015344.

```
var providerOptions = new Dictionary<string, string>();
providerOptions.Add("runtime", "DSP"); // CPU, DSP
providerOptions.Add("buffer_type", "FLOAT");
options.AppendExecutionProvider("SNPE", providerOptions);  // Error at this line!
```

Full error messages are as follows:

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '1961015344' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.ML.OnnxRuntime.OnnxRuntimeException..ctor(ErrorCode errorCode, String message)
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.SessionOptions.AppendExecutionProvider(String providerName, Dictionary`2 providerOptions)
   at image_classification.Program.Main(String[] args) in C:\Users\thnki\Downloads\onnxruntime-inference-examples-main\c_sharp\Snpe_EP\vgg16_image_classification\Program.cs:line 46
```

### To reproduce

1. Download onnxruntime0inference-example from github.
2. Open project file in c_sharp\Snpe_EP\vgg16_image_classification.
3. Install onnxruntime as described in https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.Snpe
4. Set build target to be Debug - ARM64.
5. Run the project.
* We have to add model and resource files, but they are not necessary to reproduce this error.
* I also copied all .dll and .so files in lib folders of snpe-2.6.0.4131 to the directory containing .exe file. Not helpful.

### Platform

Windows

### OS Version

11 Pro

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

C#

### Architecture

ARM64

### Execution Provider

SNPE

### Execution Provider Library Version

snpe-2.6.0.4131 (Snapdragon SDK for Windows)

**Comment by yuslepukhin** [comment]
Make sure that the `onnxruntime.dll` is loaded from the package you downloaded and not from System32

**Comment by thnkim** [comment]
Thank you, @ yuslepukhin.
It's weird. 

I've installed Microsoft.ML.OnnxRuntime.Snpe surely.
When I build the project, Microsoft.ML.OnnxRuntime.dll is copied into the folder, Debug\net6.0 .
I copied SNPE.dll, SnpeDspV66Stub.dll, SnpeHtpV68Stub.dll from SnapDragon SDK for Windows; I copied onnxruntime.dll from Debug\net6.0\runtimes\win-arm64\native. 
But, the dependency walker (https://github.com/lucasg/Dependencies) says Microsoft.ML.OnnxRuntime.dll loads onnxruntime.dll in C:\Windows\SysWOW64. 

BTW, the dependency walker says SnpeDspV66Stub.dll needs libcdsprpc.dll, which does not exist in Snapdragon SDK for Windows. :(

**Comment by yuslepukhin** [comment]
The search results may depend on the current directory of the process. I recommend you to read [this](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order).

Furthermore, Dependancy Walker has not been updated for a while and has some sharp edges.

I recommend setting a breakpoint in your program, go to Debug/Windows/Modules menu and see what is being loaded during debugging session.

**Comment by HectorSVC** [comment]
Try the steps suggested by Dmitri. We encountered this issue before. It was because onnxruntime.dll in system path got loaded.
Also, the NuGet package we published is for SNPE v1 only, check the release notes -> Dependency SDK: snpe_win-1.61.46.

**Comment by thnkim** [comment]
Thank you. 
It looks that the main reason for the issue was my SNPE SDK was 2.6. 
When I try to build onnxruntime for SNPE EP, I got the error that 'find_snpe.cmake is not found'. But it is not an issue that should be addressed in this thread. I'll use SNPE SDK v1.

Thank you again.
