### ISSUE TITLE
NOT_IMPLEMENTED : Could not find an implementation for Tile(13) node with name 'Tile_1'

### ISSUE THREAD

**Issue by srastatter** [microsoft/onnxruntime#14511]
### Describe the feature request

Hello,

I have converted a Tensorflow model to onnx using [tf2onnx](https://github.com/onnx/tensorflow-onnx); however, when I attempt to use the model through onnxruntime it throws the following error:

```
Traceback (most recent call last):
  File "test_loader.py", line 46, in <module>
    sess = rt.InferenceSession(model_path, so, providers=EP_list)
  File "/home/jupyter/sandbox/venv/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/jupyter/sandbox/venv/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for Tile(13) node with name 'Tile_1'
```
I have noticed this is similar to issues others have faced [issues/10068](https://github.com/microsoft/onnxruntime/issues/10068), [issues/3130](https://github.com/microsoft/onnxruntime/issues/3130), [issues/6116](https://github.com/microsoft/onnxruntime/issues/6116) - the workarounds recommended in these tickets did not seem to work. Tile also seems be to a [supported op](https://github.com/microsoft/onnxruntime/blob/main/docs/OperatorKernels.md).

**Note that the model passes the validation check in the onnx module (see below)**
```
import onnxruntime as rt
from onnxruntime_extensions import (
            onnx_op, PyCustomOpDef,
            get_library_path as _lib_path)
import onnx

model_path = 'example.onnx'
onnx_model = onnx.load(model_path)
# Check the model
try:
    onnx.checker.check_model(onnx_model)
except onnx.checker.ValidationError as e:
    print("The model is invalid: %s" % e)
else:
    print("The model is valid!")

EP_list = ['CPUExecutionProvider']
so = rt.SessionOptions()
so.register_custom_ops_library(_lib_path())

sess = rt.InferenceSession(model_path, so, providers=EP_list)
```

Below is a snapshot of the graph:
![example onnx](https://user-images.githubusercontent.com/104024446/215880571-0e2307d4-c1eb-4d1f-bd91-ffcd7da0c294.svg)

Runtime environment:
* `onnx==1.13.0`
* `onnxruntime==1.13.1`
* `onnxruntime-extensions==0.4.2`
* `protobuf==3.20.3`
* `tensorflow==2.8.0`
* `tf2onnx==1.13.0`

Please advise.

Tagging:
@TomWildenhain-Microsoft 

### Describe scenario use case

Adding support for Tile op

**Comment by RyanUnderhill** [comment]
Can you say what both of your input tensor types are?

If you can read C++, here's the code with the kernel registration for this op, you can see the types listed:
https://github.com/microsoft/onnxruntime/blob/d06ad9462b680163e4d83f8a294979ba23114bd6/onnxruntime/core/providers/cpu/tensor/tile.cc#L41

**Comment by srastatter** [comment]
tf2onnx has a conversion step that turns the input shape nodes from int32 to int64 to fit with the onnxruntime spec that you shared (see below):

```
@tf_op("Tile")
class Tile:
    @classmethod
    def version_1(cls, ctx, node, **kwargs):
        # onnx wants shape input to be int64
        _convert_shapenode_to_int64(ctx, node, 1)
...
def _convert_shapenode_to_int64(ctx, node, input_number):
    """cast int32 shape into int64 shape."""
    name = node.input[input_number]

    cast_node = ctx.insert_new_node_on_input(node, "Cast", name, to=onnx_pb.TensorProto.INT64)
    ctx.set_dtype(cast_node.output[0], onnx_pb.TensorProto.INT64)
    ctx.copy_shape(name, cast_node.output[0])
```
This conversion works for all the tile node in the graph except for one at the very end: `tile_1`. This node has a string input tensor, which is likely what is throwing the runtime error. Any recommendations for how to convert this single tensor input without being too prescriptive? Also not sure why tile_1 is different from the others in the graph either

![image](https://user-images.githubusercontent.com/104024446/216084603-1c0ac6e5-de32-4e19-96ca-74e6371def09.png)

**Comment by RyanUnderhill** [comment]
I'm not sure if there's an easy workaround. We can add string tensor support for this op. Are you building onnxruntime yourself?

**Comment by srastatter** [comment]
That would be great! Hopefully would fix the issue. I've been pip installing onnxruntime from PyPI.

**Comment by hardikrj** [comment]
@RyanUnderhill Any update on this issue?

**Comment by crispindev** [comment]
> 

@RyanUnderhill We are also facing this issue. Anything we can help out with ? Disclaimer: not really familiar with the onnxruntime

**Comment by hardikrj** [comment]
@RyanUnderhill thank you. Please let us know when it's out! :)

**Comment by RyanUnderhill** [comment]
PR is now merged, tile should support strings now.

@hardikrj @crispindev in case you weren't subscribed
