### ISSUE TITLE
TensorRT doest support opset10, onnxruntime support?

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#1452]
Hi, I have some models which samely with onnx model zoo SSD and FasterRCNN.

Those model can not convert to trt engine since they have new opset but TensorRT does not support it.

Since onnxruntime using TensorRT backend, does it support still support opset10 even tensorrt does't support? How?

I wanna ask does onnxruntime can using TensorRT inference on onnx model zoo SSD or FasterRCNN model?

**Comment by jywu-msft** [comment]
yes, onnxruntime can use TensorRT backend. If TensorRT cannot support the op/opset then it will try to fall back to an onnxruntime implementation (CUDA or CPU implementation)
So in this way, onnxruntime may still be able to execute the model where TensorRT cannot by itself.

**Comment by jinfagang** [comment]
@jywu-msft Thank u so much for this clear answer..... Another thing is that does onnxruntime abundant develop or not? It seems long time not update.....

**Comment by jywu-msft** [comment]
> @jywu-msft Thank u so much for this clear answer..... Another thing is that does onnxruntime abundant develop or not? It seems long time not update.....

what is your expectation for update frequency?

onnxruntime is in active development. there are many commits per day and our next release (0.5.0) is coming soon.

**Comment by jinfagang** [comment]
@jywu-msft  Good to hear that. I mean the other repo such as onnx and onnx_tensorrt
