### ISSUE TITLE
Mobile Object Detection on Android

### ISSUE THREAD

**Issue by dsbyprateekg** [microsoft/onnxruntime#14525]
### Describe the issue

I tried but have not found any single object detection example for android.
There is only an image classification example for android.
If anybody knows please share it with me.

### To reproduce

Any example code to use ort in android for object detection?

### Platform

Android

### OS Version

13

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

Java

### Architecture

X64

### Execution Provider

Default CPU

**Comment by YUNQIUGUO** [comment]
Hi there,

we do have a separate examples repo where we have object detection sample usage. See: https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile#object-detection

**Comment by YUNQIUGUO** [comment]
Hi there,

currently we don't have object detection sample on Android platform, but we do have one for iOS usage for reference: https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile#object-detection

And for calling Ort related apis to create session and prepare input tensors, etc for the Android app, it should be similar if you follow the image classification Android one.

**Comment by dsbyprateekg** [comment]
@YUNQIUGUO Thanks for your reply!
It's a suggestion that you can add a working example of object detection in android with YOLOv7 in the future-
[https://github.com/WongKinYiu/yolov7](url)

**Comment by YUNQIUGUO** [comment]
Sure, we can certainly consider that. thanks!

**Comment by skottmckay** [comment]
https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/object_detection/android
