### ISSUE TITLE
[release:1.14] some Opset(18) operators NOT Implemented

### ISSUE THREAD

**Issue by xiaowuhu** [microsoft/onnxruntime#14522]
### Describe the feature request

pls add Pad(18), ScatterElements(18)

### Describe scenario use case

when loading onnx model which has Pad(18) or ScatterElements(18) operators, failed.

**Comment by pranavsharma** [comment]
@liqunfu can you please check?

**Comment by liqunfu** [comment]
https://github.com/microsoft/onnxruntime/pull/14224
https://github.com/microsoft/onnxruntime/pull/14219

**Comment by faxu** [comment]
@xiaowuhu - these fixes were added in the PRs linked above. Can you validate using the [latest build](https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=271030&view=artifacts&pathAsName=false&type=publishedArtifacts) that includes these fixes?

**Comment by xiaowuhu** [comment]
fixed.
