### ISSUE TITLE
Wheel file not generated

### ISSUE THREAD

**Issue by priyanka1023** [microsoft/onnxruntime#1453]
I am trying to generate python wheel in windows but cannot do it.

I am following [this](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md) instructions. 

When I am running `python setup.py bdist_wheel` command , I am getting an error - `error: package directory 'onnxruntime\backend' does not exist`

When I try `build.bat --config RelWithDebInfo --build_wheel` , the build is successful but there is no wheel file present. 

I think my system setup is perfect because when I build normally(`build.bat --config RelWithDebInfo`), I do not face any issue.

**Comment by jywu-msft** [comment]
Can you provide exact repro steps and logs?
Is your build in a different directory from your sources directory?

I was able to create the wheel as follows:
git clone --recursive https://github.com/microsoft/onnxruntime.git
cd onnxruntime
build.bat --config RelWithDebInfo --build_wheel

-------------------------

D:\onnxruntime>cd build\windows\RelWithDebInfo\RelWithDebInfo\dist
D:\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\dist>dir
 Volume in drive D is New Volume
 Volume Serial Number is B6BF-4FF4

 Directory of D:\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\dist

07/22/2019  09:28 AM    <DIR>          .
07/22/2019  09:28 AM    <DIR>          ..
07/22/2019  09:28 AM         2,844,066 onnxruntime-0.4.0-cp35-cp35m-win_amd64.whl
               1 File(s)      2,844,066 bytes
               2 Dir(s)  59,937,443,840 bytes free

**Comment by priyanka1023** [comment]
Hello @jywu-msft ,

I a running the same steps as you and my build is in the same directory. There is no `dist` folder created inside the `ReWithDebInfo` folder. Am I missing some previous steps ?

**Comment by jywu-msft** [comment]
> Hello @jywu-msft ,
> 
> I a running the same steps as you and my build is in the same directory. There is no `dist` folder created inside the `ReWithDebInfo` folder. Am I missing some previous steps ?

just to confirm, this there are 2 RelWithDebInfo directories. 

and is there an onnxruntime directory under RelWithDebInfo ? if so, can you display its contents?

it should have:

 Directory of D:\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnxruntime

07/22/2019  09:28 AM    <DIR>          .
07/22/2019  09:28 AM    <DIR>          ..
07/22/2019  09:28 AM    <DIR>          backend
07/22/2019  09:28 AM    <DIR>          capi
07/22/2019  09:28 AM    <DIR>          datasets
07/22/2019  09:28 AM             1,099 LICENSE
07/22/2019  09:28 AM           181,621 ThirdPartyNotices.txt
07/22/2019  09:28 AM    <DIR>          tools
07/22/2019  09:28 AM               990 __init__.py
07/22/2019  09:28 AM    <DIR>          __pycache__
               3 File(s)        183,710 bytes
               7 Dir(s)  59,937,443,840 bytes free

**Comment by priyanka1023** [comment]
Hey @jywu-msft ,

Here is my content of `onnxruntime` folder.

![Wheel](https://user-images.githubusercontent.com/46866239/61654353-15e32380-ac71-11e9-8319-ee05c85aaed9.png)

**Comment by jywu-msft** [comment]
is it possible to provide the log output of your  
build.bat --config RelWithDebInfo --build_wheel  command?

or at least the section where it is trying to run setup.py bdist_wheel

should look something like:

2019-07-22 09:28:53,009 Build [DEBUG] - Running subprocess in 'D:\onnxruntime\\build\Windows\RelWithDebInfo\RelWithDebInfo'
['C:\\Users\\jywu\\AppData\\Local\\Continuum\\Anaconda3\\python.exe', 'D:\\onnxruntime\\setup.py', 'bdist_wheel']
running bdist_wheel
running build
running build_py
creating build
creating build\lib
creating build\lib\onnxruntime
copying onnxruntime\__init__.py -> build\lib\onnxruntime
creating build\lib\onnxruntime\backend
copying onnxruntime\backend\backend.py -> build\lib\onnxruntime\backend
copying onnxruntime\backend\backend_rep.py -> build\lib\onnxruntime\backend
copying onnxruntime\backend\__init__.py -> build\lib\onnxruntime\backend
creating build\lib\onnxruntime\capi
copying onnxruntime\capi\onnxruntime_validation.py -> build\lib\onnxruntime\capi
copying onnxruntime\capi\session.py -> build\lib\onnxruntime\capi
copying onnxruntime\capi\_ld_preload.py -> build\lib\onnxruntime\capi
copying onnxruntime\capi\_pybind_state.py -> build\lib\onnxruntime\capi
copying onnxruntime\capi\__init__.py -> build\lib\onnxruntime\capi
creating build\lib\onnxruntime\datasets
copying onnxruntime\datasets\__init__.py -> build\lib\onnxruntime\datasets
creating build\lib\onnxruntime\tools
copying onnxruntime\tools\onnxruntime_test.py -> build\lib\onnxruntime\tools
copying onnxruntime\tools\__init__.py -> build\lib\onnxruntime\tools
copying onnxruntime\capi\onnxruntime_pybind11_state.pyd -> build\lib\onnxruntime\capi
copying onnxruntime\datasets\mul_1.onnx -> build\lib\onnxruntime\datasets
copying onnxruntime\datasets\logreg_iris.onnx -> build\lib\onnxruntime\datasets
copying onnxruntime\datasets\sigmoid.onnx -> build\lib\onnxruntime\datasets
copying onnxruntime\LICENSE -> build\lib\onnxruntime
copying onnxruntime\ThirdPartyNotices.txt -> build\lib\onnxruntime
installing to build\bdist.win-amd64\wheel

**Comment by priyanka1023** [comment]
![bdist_wheel](https://user-images.githubusercontent.com/46866239/61654971-7161e100-ac72-11e9-8fcf-63677665a0bd.png)

**Comment by jywu-msft** [comment]
i meant running it from the build.bat script.

anyway, i think python setup.py bdist_wheel needs to be run in the same directory where your onnxruntime folder resides (that you screenshot'd above)
i.e. onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo

my build output shows this:
2019-07-22 09:28:53,009 Build [DEBUG] - Running subprocess in 'D:\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo'
['C:\Users\jywu\AppData\Local\Continuum\Anaconda3\python.exe', 'D:\onnxruntime\setup.py', 'bdist_wheel']

**Comment by priyanka1023** [comment]
Thanks @jywu-msft , I got it now. So, there are two steps -

1> `build.bat --config RelWithDebInfo --build_wheel`
2> `cd build\Windows\RelWithDebInfo\RelWithDebInfo & python 'D:\onnxruntime\setup.py' bdist_wheel`

**Comment by jywu-msft** [comment]
> Thanks @jywu-msft , I got it now. So, there are two steps -
> 
> 1> `build.bat --config RelWithDebInfo --build_wheel`
> 2> `cd build\Windows\RelWithDebInfo\RelWithDebInfo & python 'D:\onnxruntime\setup.py' bdist_wheel`

not quite. the build.bat script should internally call python setup.py bdist_wheel in the appropriate directory when you pass the --build_wheel option.
this is why i was asking for the relevant part of the output of build.bat to see what happened.

**Comment by georgen117** [comment]
> Thanks @jywu-msft , I got it now. So, there are two steps -
> 
> 1> `build.bat --config RelWithDebInfo --build_wheel`
> 2> `cd build\Windows\RelWithDebInfo\RelWithDebInfo & python 'D:\onnxruntime\setup.py' bdist_wheel`

@priyanka1023 thank you so much for posting this solution.  I agree with @jywu-msft that the build script should internally call the `pythong setup.py bdist_wheel`.  However, till that is fixed I was able to generate and use the wheel file.

**Comment by andrei-pokrovsky** [comment]
In my case --skip_tests helped. Without --skip_tests the wheel wasn't produced.
