### ISSUE TITLE
[Build] Why does DirectML.dll NOT exist in release package Microsoft.ML.OnnxRuntime.DirectML.1.12.1.zip?

### ISSUE THREAD

**Issue by yunyaoXYY** [microsoft/onnxruntime#14539]
### Describe the issue

Why does DirectML.dll does not exist in release package Microsoft.ML.OnnxRuntime.DirectML.1.12.1.zip?

I download the [Microsoft.AI.MachineLearning.1.12.1.zip](https://github.com/microsoft/onnxruntime/releases/download/v1.12.1/Microsoft.AI.MachineLearning.1.12.1.zip) pre-build package to run the https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/fns_candy_style_transfer demo. But I did not find the DirectML.dll which is needed for this program. 
So I need to download the DirectML.dll and put them into the files where the .exe exists ? and then I could run the program.

### Urgency

Urgent

### Target platform

Windows Intel CPU/ Intel Graphic Card

### Build script

Pre-build [Microsoft.AI.MachineLearning.1.12.1.zip](https://github.com/microsoft/onnxruntime/releases/download/v1.12.1/Microsoft.AI.MachineLearning.1.12.1.zip) 

### Error / output

Why does DirectML.dll NOT exist in release package Microsoft.ML.OnnxRuntime.DirectML.1.12.1.zip?

**Comment by NarutoUA** [comment]
DirectML.dll is preinstalled on Windows 10 so you dont need to download it. In case you are missing this file or you want newer version I would recommend you to install DirectML package from [nuget](https://www.nuget.org/packages/Microsoft.AI.DirectML/) . You might need to switch your build configuration to x64 (or x86) because DirectML package doesnt copy its files in AnyCPU configuration.

**Comment by martinb35** [comment]
DirectML comes from a separate package and needs to be downloaded either automatically by a package manager or manually by following the dependency. 
When you use a package manager like the one in Visual Studio, it will pull down the necessary version of DirectML as a dependency. When downloading the zip file, you need to do this step manually. Go to the dependencies tab in NuGet and it will point you to the right version of DirectML.
