### ISSUE TITLE
OrtRun doesn't return results unless 'output' is nullptr

### ISSUE THREAD

**Issue by ivannp** [microsoft/onnxruntime#1454]
**Describe the bug**
Calling the C api's OrtRun with a non null output parameter doesn't set the output.

**Urgency**
Not urgent - I can initialize the pointer, but it takes to debug and is not clear from the documentation.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 0.40

**To Reproduce**
Call OrtRun with a non null output parameter

**Expected behavior**
I expect the pointer to contain the result regardless of the input value of the pointer. In any case, this should be documented.

**Comment by snnn** [comment]
Did check the  returned OrtStatus, what does it say?

**Comment by snnn** [comment]
We have a unitest for this feature. So it should work:https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_inference.cc#L104

**Comment by ivannp** [comment]
p = nullptr;
    ORT_THROW_ON_ERROR(OrtRun(
        session.get(),
        runOptions.get(),
        inames.data(),
        inputs.data(), 2,
        onames.data(), 1,
        reinterpret_cast<OrtValue **>(&p)));

Without the *nullptr* assignment, p was pointing to the second input and I was getting it as output.

**Comment by snnn** [comment]
Yes. 
If the tensor shapes of the output values are known, you can preallocate the buffers and OrtValues, and pass them into the OrtRun function. Otherwise, onnxruntime will allocate(and own) the buffers for you.

**Comment by snnn** [comment]
I'll make a doc update.
