### ISSUE TITLE
TensorRT provider fails with yoloX network

### ISSUE THREAD

**Issue by rbenes** [microsoft/onnxruntime#14546]
### Describe the issue

Hi,we have a yoloX (tiny version) train in mmdetect framework. We are inferring it in onnx runtime and everything works fine except TensorRt provider (CPU and CUDA providers works correctly). With TensorRt provider, it fails with error

```
FAIL : TensorRT input: onnx::Shape_1452 has no shape specified. Please run shape inference on the onnx model first.
```

Inspired by https://github.com/microsoft/onnxruntime/issues/10443 we run shape_inference but the error only changes to:

```
Unexpected Internal Error: [virtualMemoryBuffer.cpp::~StdVirtualMemoryBufferImpl::104] Error Code 1: Cuda Runtime (driver shutting down)
```

To be even more strange - it does not fail everywhere. We have two machines and it fails on only one of them. 
Onnx runtime is run in docker on both machines (same docker => same version of cuda and TensorRt), the drivers on the host machines are the same. Only one difference seems to be in hw (Quadro P4000 - failing vs TITAN X - works well).
Cuda driver Version: 525.60.13
Cuda: 11.4
TensorRT: 8.4.3-1

We also notice the failure on the Jetson device (Xavier with 4.6 Jetpack).

Does someone encounter similar issues? Can it really be in the hardware or is it a wrong clue?
Is there some workaround? E.g. switch to CUDA provider for part of the network?

Thank you,
Radek

### To reproduce

-

### Platform

Linux

### OS Version

linux

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

TensorRT

### Execution Provider Library Version

CUDA 11.4

**Comment by jywu-msft** [comment]
from your description, it sounds like an internal issue with TensorRT that impacts certain GPU HW configs. 
I haven't encountered this specific error before. It's interesting that it works okay on Titan X but not on the other HW.
Maybe it's memory related? (Titan X has more GPU memory than P4000 and Jetson Xavier)
We will soon be releasing ORT 1.14 which supports TensorRT 8.5, maybe you can try that on your P4000? 
if you're able to build from source, you can build main branch. or wait until the 1.14 binary packages are released.

**Comment by rbenes** [comment]
Hi, sorry for delayed response. We were trying to prepare a reproducer or debug it properly. 

We found that the reported different behavior was due to some inaccuracies in our infrastructure. After adjustments in infrastructure we found that tiny yoloX model was invalid for all architectures (Quadro P4000, TITAN X, Jetson).

We go deeper to the mmdetection and mmdeploy, that is responsible for train/export, and we found that problem was in the export

```
python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmdet/detection/detection_onnxruntime_dynamic.py \
    $CONFIG_FILE \
    $file \
    ...
```

change to static

```
python mmdeploy/tools/deploy.py \
    mmdeploy/configs/mmdet/detection/detection_onnxruntime_static.py \
    $CONFIG_FILE \
    $file \
    ...
```

after this, we had to call 

```
python onnxruntime/python/tools/symbolic_shape_infer.py --input $MODEL_PATH --output $MODEL_PATH --auto_merge
```

now, it is working on all platforms.
