### ISSUE TITLE
Segmentation fault when calling SessionImpl<T>::Run

### ISSUE THREAD

**Issue by RomanShnurov** [microsoft/onnxruntime#14564]
### Describe the issue

Hello! I tried to write code for Arcface and Retinaface using c++, but I ran into a problem: my code runs on macOS, but on Ubuntu(runs with Virtualbox) I get a segmentation fault.

>Program terminated with signal SIGSEGV, Segmentation fault.
>#0  0x00007f9d09ea6508 in MlasConvNchwFloatSingleAvxFilter1 () from /home/vboxuser/workspace/libs/onnxruntime/build/Linux/Release/libonnxruntime.so.1.14.0

If I run Arcface before Retinaface, Retinaface runs without segmentation fault.

### To reproduce

[GDB log(backtrace included)](https://github.com/microsoft/onnxruntime/files/10579895/gdb_log.txt)

Source code: [retina.zip](https://github.com/microsoft/onnxruntime/files/10579717/retina.zip)
> mkdir build && cd build
>  cmake ..
>  make -j4

### Platform

Linux

### OS Version

Ubuntu 22.10

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.14.0

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by RyanUnderhill** [comment]
A quick look at your code shows that you're creating an Ort::Env per class, you should have one single global one:

`std::shared_ptr<Ort::Env> m_env;`

This might not be the problem, but could be causing a problem.

**Comment by RomanShnurov** [comment]
@RyanUnderhill, thanks, good point! 
But I'm sure it's not the main problem, because in case of Segmentation fault, I have only one Ort::Env created at a time.

**Comment by yuslepukhin** [comment]
In 
```.cpp
Ort::Value Classifier::createTensorFromImage(const cv::Mat& img)
```
The last line creates an `Ort::Value` object on top of the buffer that is owned by the `inputTensorValues`. However, the vector is a local var to the function. The buffer is deallocated right before the function returns.
There might be something else. Generally, this is a subject for a C++ related discussion.

**Comment by RomanShnurov** [comment]
@yuslepukhin, thank you, you saved my day! It wasn't very obvious to me, so I missed it when I was writing the code.
