### ISSUE TITLE
[Build] find_snpe.cmake is not found during build for SNPE

### ISSUE THREAD

**Issue by thnkim** [microsoft/onnxruntime#14562]
### Describe the issue

https://github.com/microsoft/onnxruntime/blob/c6c11039d76c95798238e358c898a562a200a239/cmake/external/onnxruntime_external_deps.cmake#L465
needs to be changed from
`include(find_snpe.cmake)`
to
`include(external/find_snpe.cmake).`

### Target platform

Windows

### Build script

build.bat --use_snpe --snpe_root=[location-of-SNPE_SDK] --build_shared_lib --cmake_generator "Visual Studio 16 2019" --skip_submodule_sync --config Release --build_dir \build\Windows --arm64

### Error / output

find_snpe.cmake is not found.

### Visual Studio Version

Visual Studio 2022

**Comment by HectorSVC** [comment]
@thnkim Would you like to commit a fix for this since you already worked it out?

**Comment by HectorSVC** [comment]
made a PR https://github.com/microsoft/onnxruntime/pull/14616

**Comment by HectorSVC** [comment]
PR merged
