### ISSUE TITLE
how to get onnxruntime version with c++ api 

### ISSUE THREAD

**Issue by cqray1990** [microsoft/onnxruntime#14584]
### Describe the documentation issue

how to get onnxruntime version with c++ api

**Comment by pranavsharma** [comment]
```OrtGetApiBase()->GetVersionString()```
https://github.com/microsoft/onnxruntime/blob/638f21b969143f65f4c47ce6b0f41f435e1d3ec3/include/onnxruntime/core/session/onnxruntime_c_api.h#L594

**Comment by natke** [comment]
Hi @cqray1990, did the above information help to solve your problem? We have noticed the version API is not annotated with docs comments. We will be fixing this and re-publishing the docs

**Comment by yuslepukhin** [comment]
There is not a C++ API that returns ORT version. Only C. We will fix that.

**Comment by natke** [comment]
@cqray1990 Please try out the [GetVersionString API]( https://onnxruntime.ai/docs/api/c/namespace_ort.html#aab1b2d08af45de1d59ce7d86196cd72d) and let us know how you go!

**Comment by natke** [comment]
Fixed by #14873
