### ISSUE TITLE
Microsoft.ML.OnnxRuntime.OnnxRuntimeException: '[ErrorCode:InvalidArgument] Failed to load model with error: D:\a\_work\1\s\engine\lotus\onnxruntime\core/graph/

### ISSUE THREAD

**Issue by Desync3** [microsoft/onnxruntime#14591]
### Describe the issue

I reinstalled my pc and reinstalled the source. It was working before but when i run it now i get "Microsoft.ML.OnnxRuntime.OnnxRuntimeException: '[ErrorCode:InvalidArgument] Failed to load model with error: D:\a\_work\1\s\engine\lotus\onnxruntime\core/graph/"
![image](https://user-images.githubusercontent.com/49792134/216837960-d46bf762-13e7-496d-9d7b-99aa1f057878.png)

I have no idea what's causing this because the source was working before.

### To reproduce

I have no idea.

### Urgency

Important for me.

### Platform

Windows

### OS Version

Newest Update

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

Microsoft.ML.OnnxRuntime.Managed 1.13.1

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

Default CPU

**Comment by Desync3** [comment]
I fixed it.

**Comment by dededivad** [comment]
Umm, please explain how? I have the same issue.
