### ISSUE TITLE
Warnings during compilation on VS2022/32 bits treated as errors.

### ISSUE THREAD

**Issue by BengtGustafsson** [microsoft/onnxruntime#14595]
### Describe the issue

Two warnings in DmlDFT.h are treated as warnings when compiling on VS2022 (17.3.6) in x86 configurations. We tried this on r1.13.1 but it does not seem to have been fixed in the 1.14 RC branch, which is a pity.

Here is a diff I got after fixing the errors to my best ability. Note two gsl casts on line 281, and one int cast on line 310:
```diff
--- a/onnxruntime/core/providers/dml/DmlExecutionProvider/src/Operators/DmlDFT.h
+++ b/onnxruntime/core/providers/dml/DmlExecutionProvider/src/Operators/DmlDFT.h
@@ -278,7 +278,7 @@ public:
         }
         else
         {
-            params.DFTLength = inputDims[m_axis];
+            params.DFTLength = gsl::narrow_cast<uint32_t>(inputDims[gsl::narrow_cast<uint32_t>(m_axis)]);
         }

         auto isPowerOfTwo = [](uint32_t n) { return (n != 0) && ((n & (n - 1)) == 0); };
@@ -307,7 +307,7 @@ public:
             std::array<uint32_t, 4> reshapedOutputSize = { 1, 1, 1, outputDims.back() };

             size_t reshapedIndex = 0;
-            for (int i = 0; i < inputDims.size() - 1; i++)
+            for (int i = 0; i < int(inputDims.size()) - 1; i++)
             {
                 if (i == m_axis || i == (m_axis + 1))
                 {
```

### Target platform

Windows 32 bit

### Build script

"C:\Program Files\CMake\bin\cmake.EXE" --build "build_gpu/Windows\Release" --config Release -- /maxcpucount:4 /nodeReuse:False

### Error / output

C:\gitlab-runner\builds\ZrJ2zsyR\0\cv\impl\thirdpartylibs\onnxruntime\onnxruntime\core\providers\dml\DmlExecutionProvider\src\Operators\DmlDFT.h(281,42): error C2220: the following warning is treated a
s an error [C:\gitlab-runner\builds\ZrJ2zsyR\0\cv\impl\thirdpartylibs\onnxruntime\build_gpu\Windows\Release\onnxruntime_providers_dml.vcxproj]
C:\gitlab-runner\builds\ZrJ2zsyR\0\cv\impl\thirdpartylibs\onnxruntime\onnxruntime\core\providers\dml\DmlExecutionProvider\src\Operators\DmlDFT.h(281,42): warning C4244: 'argument': conversion from 'int
64_t' to 'const unsigned int', possible loss of data [C:\gitlab-runner\builds\ZrJ2zsyR\0\cv\impl\thirdpartylibs\onnxruntime\build_gpu\Windows\Release\onnxruntime_providers_dml.vcxproj]
C:\gitlab-runner\builds\ZrJ2zsyR\0\cv\impl\thirdpartylibs\onnxruntime\onnxruntime\core\providers\dml\DmlExecutionProvider\src\Operators\DmlDFT.h(310,31): warning C4018: '<': signed/unsigned mismatch [C
:\gitlab-runner\builds\ZrJ2zsyR\0\cv\impl\thirdpartylibs\onnxruntime\build_gpu\Windows\Release\onnxruntime_providers_dml.vcxproj]

### Visual Studio Version

2022, 17,3,6

**Comment by yuslepukhin** [comment]
Can you submit a PR? Also, it may or may not be important to use the correct VS Developer Prompt. In this case, you are absolutely correct. We no longer use `gsl::narrow`, use `onnxruntime::narrow`.

**Comment by BengtGustafsson** [comment]
I have a branch in my git clone, but I'm not allowed to push it to the main repo. I guess you have to enable my user or something. I get this error:

remote: Permission to Microsoft/onnxruntime.git denied to BengtGustafsson.
fatal: unable to access 'https://github.com/Microsoft/onnxruntime.git/': The requested URL returned error: 403

Also: I get one failed test when running RUN_TESTS in VS2022 after fixing it so it builds. Seems to be unrelated to this bug:
SkipLayerNormTest.SkipLayerNormBatch1_Float16. The test runs but reports a too large diff in the result:

The difference between f_expected[i] and f_output[i] is 0.015625, which exceeds threshold, where
f_expected[i] evaluates to 11.59375,
f_output[i] evaluates to 11.609375, and
threshold evaluates to 0.0080000003799796104.
i:33, provider_type: DmlExecutionProvider

As you don't seem to test Win32 + DML in your CI this may well be some

**Comment by BengtGustafsson** [comment]
What do I need to do to be allowed to push a branch and create a PR for it? Is there a list of allowed user names? How do I get on it? I have scanned all your docs I could find and there is no mention of any rules for who can push, which is a bit frustrating as you explicitly asked me to make a PR.

**Comment by BengtGustafsson** [comment]
When it comes to the failing test mentioned above that does not happen on my development machine which has a Titan XP GPU, only on the Quadro T1000 in the CI computer. I will make a separate issue for this if this one gets resolved so I can get that far again.

**Comment by yuslepukhin** [comment]
> I have a branch in my git clone, but I'm not allowed to push it to the main repo. I guess you have to enable my user or something. I get this error:
> 
> remote: Permission to Microsoft/onnxruntime.git denied to BengtGustafsson. fatal: unable to access 'https://github.com/Microsoft/onnxruntime.git/': The requested URL returned error: 403
> 
> Also: I get one failed test when running RUN_TESTS in VS2022 after fixing it so it builds. Seems to be unrelated to this bug: SkipLayerNormTest.SkipLayerNormBatch1_Float16. The test runs but reports a too large diff in the result:
> 
> The difference between f_expected[i] and f_output[i] is 0.015625, which exceeds threshold, where f_expected[i] evaluates to 11.59375, f_output[i] evaluates to 11.609375, and threshold evaluates to 0.0080000003799796104. i:33, provider_type: DmlExecutionProvider
> 
> As you don't seem to test Win32 + DML in your CI this may well be some long standing issue, I don't know.

The policy is to have a fork, then branch and then PR.

**Comment by BengtGustafsson** [comment]
The PR has now been ready for review and CI build for 40 hours with no progress, is this normal or am I still missing some step?

**Comment by nums11** [comment]
Closing as resolved.
