### ISSUE TITLE
[Web] ORT-web does not support both float16 and quantization.

### ISSUE THREAD

**Issue by jkla139** [microsoft/onnxruntime#14601]
### Describe the issue

ORT-web does not support both float16 and quantization.
I think its application is severely limited on web.

### To reproduce

...

### ONNX Runtime Installation

Other / Unknown

### ONNX Runtime Version or Commit ID

1.13.1

### Execution Provider

Other / Unknown

**Comment by guschmue** [comment]
quantization should work with ort-web when using wasm. 
fp16 should work but is going to be real slow.
Is there a specific model that doesn't work?

**Comment by jkla139** [comment]
> quantization should work with ort-web when using wasm. fp16 should work but is going to be real slow. Is there a specific model that doesn't work?

For quantization,

webgl does not support as in [js/web/docs/operators.md](https://github.com/microsoft/onnxruntime/blob/main/js/web/docs/operators.md),

and if use wasm as backend to run quantizated model,
`
<script src="https://cdn.bootcdn.net/ajax/libs/onnxruntime-web/1.13.1/ort.min.js"></script>
try {
      ......
      Inferer.session = await ort.InferenceSession.create(onnx, sessionOption);
      ......
);
} catch (e) {
      document.write(`failed to create session: ${e}.`);
      console.log('e.stack:', e.stack);
}
`
I catch an exception without any useful error message, and get a number:
![image](https://user-images.githubusercontent.com/44624598/217289217-b381225a-2604-4579-ad6f-057cf2730019.png)
the call stack is undefined:
![image](https://user-images.githubusercontent.com/44624598/217289353-9f9369ea-4ccf-43ff-b55d-82d02e40e78b.png)

==========================================

For fp16,

`const results = await Inferer.session.run(feeds);`

raise this error:
![image](https://user-images.githubusercontent.com/44624598/217294583-fa5fa74e-df6b-4b1a-bc45-3f3984cca032.png)

The input type is float32. Does it caused by wrong type inputs ?
But there are no float16 [TensorConstructor](https://onnxruntime.ai/docs/api/js/interfaces/TensorConstructor.html) ...

**Comment by fs-eire** [comment]
ONNX Runtime Web does not support float16 as input types. It still works if there are float16 initializers inside the model. we cannot support as there is no such typed array `Float16Array` in JavaScript

**Comment by jkla139** [comment]
> ONNX Runtime Web does not support float16 as input types. It still works if there are float16 initializers inside the model. we cannot support as there is no such typed array `Float16Array` in JavaScript

Yes, I know. But the input type in "feeds" is float32, and since the model is converted by code:
`import onnx
from onnxmltools.utils import float16_converter

model = onnx.load('model.onnx')
model = float16_converter.convert_float_to_float16(model)
onnx.save(model, 'model-fp16.onnx')`

but get the following error:
![5a3949355dc2f1198f6b3c7ac91b9643_217294583-fa5fa74e-df6b-4b1a-bc45-3f3984cca032](https://user-images.githubusercontent.com/44624598/217478688-f6e9333b-19c7-42d6-8c33-cf87d9907924.png)

So I think the error comes from incompatible input type.

**Comment by fdwr** [comment]
I'm content just passing a bitwise representation of float16f10e5s1 via `Uint16Array` for now until we get a proper `Float16Array` (e.g. https://github.com/webmachinelearning/webnn/issues/373), so long as ORT can distinguish that it really is float16 (and not uint16) somehow when creating the `ort.Tensor`, but it's important to have float16 inputs/outputs for GPU's for a backend like [WebNN via DML](https://github.com/fdwr/chromium-src-webnn-dml/pull/1) where the model file size is 1/2 the size and can execute faster.

I suppose as a work-around, we could temporarily hack the model to insert a Cast at the graph input and output, so that at least all the internal computation is float16.
