### ISSUE TITLE
Does API AppendExecutionProvider_DML exist for C++?

### ISSUE THREAD

**Issue by yunyaoXYY** [microsoft/onnxruntime#14610]
### Describe the issue

Hi, I would like to use DirectML in onnxruntime for a C++ program, I notice that some API like AppendExecutionProvider_CUDA exists in onnxruntime_cxx_api.h, but there is no AppendExecutionProvider_DML. 

So , for now, I can only call the C API in to use DirectML?
Is there any way or guidence to implement the C++ API AppendExecutionProvider_DML?
Thanks. 

### To reproduce

Does API AppendExecutionProvider_DML exist for C++?

### Urgency

Urgent

### Platform

Windows

### OS Version

win10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

prebuild 1.12, download from Release

### ONNX Runtime API

C++

### Architecture

X86

### Execution Provider

DirectML

**Comment by fdwr** [comment]
The free function `OrtSessionOptionsAppendExecutionProvider_DML` from `#include "dml_provider_factory.h"` still works but is deprecated. We recommend using `SessionOptionsAppendExecutionProvider_DML` instead. See [example](https://github.com/fdwr/OnnxRuntimeDirectMLEPSample/blob/7a33ceea98ae850903771399e95250f2903d244b/main.cpp#L322). e.g. :

```
    OrtApi const& ortApi = Ort::GetApi();
    OrtDmlApi const* ortDmlApi = nullptr;
    ortApi.GetExecutionProviderApi("DML", ORT_API_VERSION, reinterpret_cast<void const**>(&ortDmlApi));
...
    Ort::SessionOptions sessionOptions;
    sessionOptions.SetExecutionMode(ExecutionMode::ORT_SEQUENTIAL); // For DML EP
    sessionOptions.DisableMemPattern(); // For DML EP
...
    ortApi.AddFreeDimensionOverrideByName(sessionOptions, "batch_size", batchSize); // If your model has this dimension
...
    ortDmlApi->SessionOptionsAppendExecutionProvider_DML(sessionOptions, /*device index*/ 0);
```

**Comment by yunyaoXYY** [comment]
> The free function `OrtSessionOptionsAppendExecutionProvider_DML` from `#include "dml_provider_factory.h"` still works but is deprecated. We recommend using `SessionOptionsAppendExecutionProvider_DML` instead. See [example](https://github.com/fdwr/OnnxRuntimeDirectMLEPSample/blob/7a33ceea98ae850903771399e95250f2903d244b/main.cpp#L322). e.g. :
> 
> ```
>     OrtApi const& ortApi = Ort::GetApi();
>     OrtDmlApi const* ortDmlApi = nullptr;
>     ortApi.GetExecutionProviderApi("DML", ORT_API_VERSION, reinterpret_cast<void const**>(&ortDmlApi));
> ...
>     Ort::SessionOptions sessionOptions;
>     sessionOptions.SetExecutionMode(ExecutionMode::ORT_SEQUENTIAL); // For DML EP
>     sessionOptions.DisableMemPattern(); // For DML EP
> ...
>     ortApi.AddFreeDimensionOverrideByName(sessionOptions, "batch_size", batchSize); // If your model has this dimension
> ...
>     ortDmlApi->SessionOptionsAppendExecutionProvider_DML(sessionOptions, /*device index*/ 0);
> ```

Thanks! I will have try following your example :D
