### ISSUE TITLE
[Documentation] Difference of onnxruntime1.13.1_gpu.zip and onnxruntime1.13.1_cuda.zip?

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#14629]
### Describe the documentation issue

[Documentation] Difference of onnxruntime1.13.1_gpu.zip and onnxruntime1.13.1_cuda.zip?

**Comment by natke** [comment]
Hi @jifagang, the -gpu zip contains support for both CUDA and TensorRT and the -cuda zip only contains support for CUDA.

**Comment by jinfagang** [comment]
@natke thank u, but

![image](https://user-images.githubusercontent.com/21303438/217704678-3a72ac57-6696-4aa8-93f7-ec9a92aa9065.png)


does cuda same as tensort? from size, it's the same

**Comment by natke** [comment]
Actually you should use the -gpu package as that is the official release containing CUDA and TensorRT. We are looking into the publication of the other variants. Please use -gpu

**Comment by jinfagang** [comment]
@natke thanks !

**Comment by natke** [comment]
These intermediate zips were uploaded in error. We are removing them.
