### ISSUE TITLE
Supported input types during InferenceSesssions

### ISSUE THREAD

**Issue by JoachimMoe** [microsoft/onnxruntime#14625]
### Describe the issue

Hi,

I am currently trying to figure out how to correctly create an InferenceSession that accepts something else than a NumPy array. I have been trying to search my way through tutorials and stackoverflow, and I have not yet found clear pointers as to how to deal with specific input types that are not NumPy (Tensorflow, CuPy, PyTorch, etc). The reasoning behind this is that tutorials such as https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/notebooks/PyTorch_Bert-Squad_OnnxRuntime_GPU.ipynb will in block 10 print that inference is done on the GPU but several calls to .cpu() and .numpy() -- so the entire data point is converted back to NumPy? 

So my point of this post is to try to fully comprehend and maybe create a small tutorial as [to how to run inferenceSessions](https://github.com/onnx/tutorials) has only very small (yet useful!) tutorials mostly concerned with exporting models.

CuPy currently has zero-copy conversion from a CuPy array to a Torch tensor. Torch, CuPy and TensorFlow objects can be represented as  DLpacks, yet an ORT InferenceSession can not predict directly on PyCapsules. Essentially, this boils down the question: *Do all inputs have to be converted to NumPy arrays in ORT inference sessions?* 

### To reproduce

```
import torch
import torch.onnx
import cupy as cp
import onnx
import os
import matplotlib.pyplot as plt
import numpy as np
import torch
import onnxruntime as ort
from PIL import Image


# Load a pre-trained ResNet model
model = torch.hub.load('pytorch/vision', 'resnet50', pretrained=True)

# Convert the model to work with CuPy arrays
model = model.cuda()

# Export the model to ONNX format
dummy_input = torch.randn(1, 3, 224, 224, device='cuda')
torch.onnx.export(model, dummy_input, "GPUNetworks/resnet50.onnx")


model_path = '../networks/GPUNetworks/resnet50.onnx'
session = ort.InferenceSession(model_path, providers = ["CUDAExecutionProvider"])
print("ONNX runtime session using :", ort.get_device())

use_gpu = torch.cuda.is_available()
device = torch.device("cuda" if use_gpu else "cpu")
print(device)

print('CUDAExecutionProvider' in ort.get_available_providers())


 # Directly passing a PyTorch tensor
def predict(path):
    x = cp.array(Image.open(path))
    #Convert x to torch tensor
    x = torch.as_tensor(x, device='cuda')
    ort_inputs = {session.get_inputs()[0].name: x}
    preds = session.run(None, ort_inputs)[0]
    return preds 

predict(path)

```

One could also be tempted to keep the inputs in DLpack, as this seems to be the community work-around 

```
def predict(path):
    x = cp.array(Image.open(path))
    cp2dl = x.toDlpack()

    # Pass the DLPack tensor to the ONNX runtime session
    ort_inputs = {session.get_inputs()[0].name: cp2dl}
    preds = session.run(None, ort_inputs)[0]

predict(path)

```

Both errors with similar errors, such as:

```
RuntimeError: Input must be a list of dictionaries or a single numpy array for input 'input.1'.
```

### Platform

Linux

### OS Version

Manjaro

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.6

**Comment by vasanthzoh** [comment]
Any reason why this was closed? Have you found a way to pass CUDA tensors or CuPy arrays to InferenceSessions? @JoachimMoe
