### ISSUE TITLE
Build on master failed on PyBind11

### ISSUE THREAD

**Issue by oreoero** [microsoft/onnxruntime#1464]
**Describe the bug**
Encountered build errors on Pybind11, more in the attached files below:
```
onnxruntime_pybind_mlvalue.obj : error LNK2001: unresolved external symbol __imp_PyObject_Type [C:\onnxruntime\build\Wi
ndows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
onnxruntime_pybind_mlvalue.obj : error LNK2001: unresolved external symbol __imp_PyErr_Occurred [C:\onnxruntime\build\W
indows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
onnxruntime_pybind_mlvalue.obj : error LNK2001: unresolved external symbol __imp_PyUnicode_AsUTF8AndSize [C:\onnxruntim
e\build\Windows\RelWithDebInfo\onnxruntime_pybind11_state.vcxproj]
```
**Urgency**
Totally blocked on experimenting ONNX RT.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 
- Python version: 3.7
- Visual Studio version (if applicable): Latest VS 2017
- GCC/Compiler version (if compiling from source): 
-- The C compiler identification is MSVC 19.16.27032.1
-- The CXX compiler identification is MSVC 19.16.27032.1
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
1. New Windows machine
2. Install Git, Python3.7, CMake, VS 2017 and upgrade
3. Git clone --recursive https://github.com/Microsoft/onnxruntime
4. cd onnxruntime
5. Open Powershell in Admin mode, run "./build.bat --config RelWithDebInfo --build_wheel"
**Expected behavior**
A clean build
**Screenshots**
![Build failure on Pybind11](https://user-images.githubusercontent.com/6767830/61671274-bea67880-ac9b-11e9-9522-5a793ed9f2a9.png)

[Build error on Pybind11.txt](https://github.com/microsoft/onnxruntime/files/3419443/Build.error.on.Pybind11.txt)

**Additional context**
Let me know anything else is needed, thanks for helping!

**Comment by snnn** [comment]
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Found PythonInterp: C:/Users/chuw/AppData/Local/Programs/Python/Python37-32/python.exe (found suitable version "3.7.4", minimum required is "3.5")

You can't mix 64 bits and 32 bits libraries up.
