### ISSUE TITLE
Question about quantiation ，the inference results of different CPU models are inconsistent ？

### ISSUE THREAD

**Issue by shiqingzhangCSU** [microsoft/onnxruntime#14642]
### Describe the issue

By use dynamic quantization,   the results of bert model on different machines are inconsistent

### To reproduce

bert download from hunggingface

### Platform

Linux

### OS Version

7.4

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.7.0

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

### Execution Provider Library Version

Intel Xeon Processor (Skylake) vs Intel(R) Xeon(R) CPU E5-2650

### Is this a quantized model?

Yes

**Comment by andrekh** [comment]
I think it is likely a case of VNNI vs non-VNNI CPU. Non-VNNI AVX suffer from register saturation with int8 conv.

**Comment by chenfucn** [comment]
AVX2 and AVX512 instructions have saturation problems:

https://www.intel.com/content/www/us/en/develop/documentation/onednn-developer-guide-and-reference/top/advanced-topics/nuances-of-int8-computations.html

You can turn on session option "session.x64quantprecision". With this, ORT will promote int8 to int16 in GEMM operations. This will preserve accuracy but has significant performance degradation.

See
https://github.com/microsoft/onnxruntime/pull/12088
