### ISSUE TITLE
Cannot associate the IsReleaseBuild to Nuget DML pipeline

### ISSUE THREAD

**Issue by rui-ren** [microsoft/onnxruntime#14660]
### Describe the issue

When generating the release package for Nuget DML,  the IsReleaseBuild flag is invalid for Nuget DML.

<img width="234" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/15321482/218186048-4c86a3b5-96c1-477c-87c8-7b186bef6afd.png">

The release package will still have `dev-***` tag.

### To reproduce

Try this pipeline https://aiinfra.visualstudio.com/Lotus/_build?definitionId=940&_a=summary

### Urgency

Not urgent

### Platform

Web Browser

### OS Version

---

### ONNX Runtime Installation

Other / Unknown

### ONNX Runtime Version or Commit ID

release

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Other / Unknown

**Comment by rui-ren** [comment]
Here is a fix https://github.com/microsoft/onnxruntime/pull/13417 ,

but did not get into main branch. Will do cherry-pick and test it. Thanks

**Comment by fdwr** [comment]
@rui-ren Appears this is the pertinent cherry-pick: https://github.com/microsoft/onnxruntime/pull/14662

**Comment by rui-ren** [comment]
issue got fix by #14662. Close this ticket.
