### ISSUE TITLE
Reason for Stable Performance of Nuphar EP with increasing batch size of onnx model 

### ISSUE THREAD

**Issue by joyIntel** [microsoft/onnxruntime#1467]
The performance of Nuphar EP is pretty stable compared to other EPs with increasing batch size of onnx model ( I am using Resnet50 ).

I have the directory structure as mentioned like [this](https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/test/perftest)

In these two following cases , I am getting the almost same result for Nuphar EP - 

1> `onnxruntime_perf_test -m times -r 100 -e nuphar Models\FinalResnet50\converted_tf_fp32\BS1\converted_TF_FP32_Resnet50_withshapes.onnx result.txt`

2> `onnxruntime_perf_test -m times -r 100 -e nuphar Models\FinalResnet50\converted_tf_fp32\ BS32\converted_TF_FP32_Resnet50_withshapes.onnx result.txt`

Resnet50 | Default | ngraph | nuphar
-- | -- | -- | --
BS1 | 17.67s | 1.28s | 7.24s
BS32 | 516s | 26.31s | 7.35s

In the first one, the batch size is 1, and in the second one the batch size is 32

Initially @KeDengMS suggested me that Nuphar has a ONNX shape inference dependency. Maybe my onnx model has not explicit information about batch size in the `graph.value_info`. But I checked it and also used  [ONNX shape inference](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#running-shape-inference-on-an-onnx-model). 

In the model, the batch size information is present inside `shape`. I have also attached the graph of the model.
[Resnet50_Graph.txt](https://github.com/microsoft/onnxruntime/files/3419463/Resnet50_Graph.txt)

Am I still making any mistake ?

**Comment by KeDengMS** [comment]
The model has batch_size of 1 from Resnet50_Graph.txt:
```
name: "input:0"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_value: 1
      }
      dim {
        dim_value: 224
      }
      dim {
        dim_value: 224
      }
      dim {
        dim_value: 3
      }
    }
  }
```
Below is the script I used to generate resnet50 model with batch, as well as random test data:
```
import numpy as np
import os
import tarfile
import unittest
import urllib.request
import onnx
from onnx import numpy_helper
from onnx import shape_inference

# download
cwd = os.getcwd()
download_url = 'https://s3.amazonaws.com/download.onnx/models/opset_9/resnet50.tar.gz'
download_local = os.path.join(cwd, 'resnet50.tar.gz')
if not os.path.exists(download_local):
    urllib.request.urlretrieve(download_url, download_local)
    with tarfile.open(download_local, 'r') as f:
        f.extractall(cwd)

# load model to edit
mp = onnx.load(os.path.join(cwd, 'resnet50', 'model.onnx'))
input_name = 'gpu_0/data_0'
batch_symbol = 'batch'
graph_input = [i for i in mp.graph.input if i.name == input_name][0]
# change input to have symbolic batch
graph_input.type.tensor_type.shape.dim[0].dim_param = batch_symbol
# clear stale shape inference
mp.graph.ClearField('value_info')
# fix the reshape op that outputs OC2_DUMMY_0 to forward 'batch' using 0
shape_const = [i for i in mp.graph.initializer if i.name == 'OC2_DUMMY_1'][0]
shape_const.CopyFrom(numpy_helper.from_array(np.asarray([0,2048], dtype=np.int64), 'OC2_DUMMY_1'))
# add batch to graph output shape
mp.graph.output[0].type.tensor_type.shape.dim[0].dim_param = batch_symbol
# run shape inference
mp = shape_inference.infer_shapes(mp)
# save model with batch
onnx.save(mp, os.path.join(cwd, 'resnet50', 'model_batch.onnx'))

# generate test data for batch == 32
test_data_dir = os.path.join(cwd, 'resnet50', 'test_data_set_32')
os.makedirs(test_data_dir)
onnx.save_tensor(numpy_helper.from_array(np.random.rand(32,3,224,224).astype(np.float32), input_name), os.path.join(test_data_dir, 'input_0.pb'))
```

I tested the model on an old SandyBridge CPU single threaded, and with mklml it's 68ms for batch=1, 2s for batch=32. Nuphar seems to have a bug with the model, other than alignment issue, so no test results. Not sure how you got your numbers...

**Comment by joyIntel** [comment]
Are you getting ` Graph input with name ## is not associated with a node` error when you run the default resnet50 model availabe on amazonaws ??

I am using a modified version of resnet50. I want to share it but GitHub is not allowing me to share that big file. Is there any other way to share ??

Yeah, you identified it correctly. Nuphar has issue with default resnet50.

**Comment by joyIntel** [comment]
I got the idea of changing batch size and also modified my model. I have collected new perf data for Nuphar EP. Now it is not stable, so I guess my query is resolved.

But yes, there is a new issue that Nuphar has an error for default Resnet50 model.



Resnet50 | Default | nuphar
-- | --  | --
BS1 | 17.67s  | 7.24s
BS4 | 60.56s | 26.75s
BS8 | 127.53s | 49.25s
BS32 | 516s | 201.21s

**Comment by KeDengMS** [comment]
The Nuphar bug would be addressed in future PR update. We are in the progress to expand the test for Nuphar. Since CNN is not the current focus of Nuphar, this is unnoticed until recently.
