### ISSUE TITLE
Cannot see DMLExecutionProvider

### ISSUE THREAD

**Issue by oneengineer** [microsoft/onnxruntime#14687]
### Describe the issue

I tried to use DirectML to do inference for an onnx file.
After the installation, I cannot find DML executor.

### To reproduce

I run the following command and scripts

```
pip install onnxruntime-directml
```

```
import onnxruntime

providers = onnxruntime.get_available_providers()

print(providers)

print(f'current device: {onnxruntime.get_device()}')
```

It only shows CPUExecutionProvider

### Platform

Windows

### OS Version

21H 22000

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

DirectML

### Execution Provider Library Version

1.2.1

**Comment by pauldog** [comment]
try uninstalling onnxruntime

**Comment by nums11** [comment]
Closing as stale.
