### ISSUE TITLE
[Documentation] High Level Design docs are missing

### ISSUE THREAD

**Issue by ivberg** [microsoft/onnxruntime#14735]
### Describe the documentation issue

For example this link is missing
https://github.com/microsoft/onnxruntime/blob/main/docs/InferenceHighLevelDesign.md

It is linked from
https://github.com/microsoft/onnxruntime/blob/main/docs/Roadmap.md

I don't see HighLevelDesign.md OR InferenceHighLevelDesign.md in docs

Rename:
https://github.com/microsoft/onnxruntime/pull/4058/files

### Page / URL

https://github.com/microsoft/onnxruntime/blob/main/docs/InferenceHighLevelDesign.md

**Comment by prasanthpul** [comment]
high level design is at https://onnxruntime.ai/docs/reference/high-level-design.html

**Comment by natke** [comment]
Fixed by #11786
