### ISSUE TITLE
[Documentation] Broken link in onnxruntime_c_api.h

### ISSUE THREAD

**Issue by csukuangfj** [microsoft/onnxruntime#14741]
### Describe the documentation issue

https://github.com/microsoft/onnxruntime/blob/8372c86e7f15ed0d8d47e1e0afc115c30db39252/include/onnxruntime/core/session/onnxruntime_c_api.h#L300

The above link results in the following error:
<img width="947" alt="Screenshot 2023-02-18 at 14 46 26" src="https://user-images.githubusercontent.com/5284924/219845885-1d90d951-a6c0-4393-baeb-622efa76099d.png">

**Comment by natke** [comment]
Fixed by #14748
