### ISSUE TITLE
What's the difference between onnxruntime-linux-x64-gpu-1.13.1.tgz and onnxruntime-linux-x64-cuda-1.13.1.tgz?

### ISSUE THREAD

**Issue by liuyx-baller** [microsoft/onnxruntime#14763]
### Describe the documentation issue

What's the difference between https://github.com/microsoft/onnxruntime/releases/download/v1.13.1/onnxruntime-linux-x64-gpu-1.13.1.tgz and https://github.com/microsoft/onnxruntime/releases/download/v1.13.1/onnxruntime-linux-x64-cuda-1.13.1.tgz?

**Comment by natke** [comment]
Please use the -gpu package. This contains the official release and has support for CUDA

**Comment by natke** [comment]
We have removed the unnecessary packages. Please let us re-open the issue if you have any other questions

**Comment by Archie3d** [comment]
Looking at [the latest 1.17.1 release](https://github.com/microsoft/onnxruntime/releases/tag/v1.17.1), both `linux-x64-gpu` and `linux-x64-cuda12` are still provided. So what is the difference, and why these two separate packages are provided if the `-gpu` one is supposed to cover for CUDA as well?
