### ISSUE TITLE
ORT_RUNTIME_EXCEPTION V1.12.0 - GPU T1200 - CUDA 11.4

### ISSUE THREAD

**Issue by Guru-Deep-Singh** [microsoft/onnxruntime#14771]
### Describe the issue

I'm trying to run a sample model on GPU, however while appending the CUDA options I get an error i.e. ORT_RUNTIME_EXCEPTION.

![image](https://user-images.githubusercontent.com/68775950/220674929-ef22ac92-a4ef-4588-8531-f7323d0f0973.png)

The error occurs in _AppendExecutionProvider_CUDA_ function 

![image](https://user-images.githubusercontent.com/68775950/220674496-e14007d5-7776-4d5a-9476-0cc7acedb634.png)

My GPU - T1200
CUDA toolkit - 11.4

Sorry if it might be a silly question.

### To reproduce

-

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

v1.12.0

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.4

**Comment by yuslepukhin** [comment]
What is the error message in the exception?

**Comment by yuslepukhin** [comment]
Check that your binary is able to find CUDA DLLs. Check the DLL search order. 
https://github.com/microsoft/onnxruntime/issues/13658

**Comment by Guru-Deep-Singh** [comment]
![image](https://user-images.githubusercontent.com/68775950/220851156-f54fbaf9-5cad-4d5a-b401-f4edd58c2137.png)
The CUDA dlls are loaded

**Comment by yuslepukhin** [comment]
Can you set an breakpoint on `OnnxRuntimeException` and see the stack where it originated from?

**Comment by Guru-Deep-Singh** [comment]
I solved this by updating cuDNN which was the problem.
