### ISSUE TITLE
What is "error number 13"

### ISSUE THREAD

**Issue by alanwilter** [microsoft/onnxruntime#14788]
### Describe the issue

I have an aws lambda function that's throwing this error:

```python
rate_model = rt.InferenceSession("models/rate.onnx", providers=["CPUExecutionProvider"])
[ONNXRuntimeError] : 1 : FAIL : Load model from models/rate.onnx failed:system error number 13
```

I'm deploying via serverless using docker and testing the docker container locally seems all fine.

All I want to know what this `error number 13` may mean.

### To reproduce

NA

### Urgency

No, but the question is simple if someone know the answer.

### Platform

Linux

### OS Version

public.ecr.aws/lambda/python:3.8

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by alanwilter** [comment]
It's file permission. Giving "all" read permission solved.

**Comment by ninghui048** [comment]
I also had the same error on Windows 10, but it can be detected normally. What is the reason and how to solve it. I don't want to see this error message
