### ISSUE TITLE
Invalid model produced by `convert_generation.py` for GPT2 with greedysearch

### ISSUE THREAD

**Issue by un-certainty** [microsoft/onnxruntime#14790]
### Describe the issue

I use `convert_generation.py` to convert my GPT2 model. The process runs smoothly without errors. But when I load the model with `ort.InferenceSession`, an exception is raised:

```
failed to load 'gpt_onnx' version 1: Internal: onnx runtime error 10: Load model from /models/gpt_onnx/1/model.onnx failed:This is an invalid model. In Node, ("GreedySearch_gpt2", GreedySearch, "com.microsoft", -1) : ("input_ids": tensor(int32),"max_length": tensor(int32),"min_length": tensor(int32),"repetition_penalty": tensor(float),"","","",) -> ("sequences": tensor(int32),) , Error Node (GreedySearch_gpt2) has input size 7 not in range [min=2, max=6].
```

But according to the document, [GreedySearch op](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#commicrosoftgreedysearch) accepts 2-7 inputs.

![image](https://user-images.githubusercontent.com/102007104/220800847-14c565a1-eca0-4998-a767-5bef699234c6.png)

### To reproduce

1. Convert GPT checkpoint into onnx with [convert_to_onnx.py](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/models/gpt2/convert_to_onnx.py)
2. Convert decoder.onnx to with [convert_generation.py](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/convert_generation.py)

opset=11

### Urgency

This blocks a release plan in one week

### Platform

Linux

### OS Version

Ubuntu 18.04.6 LTS

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

onnxruntime-gpu==1.13.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.4

**Comment by hariharans29** [comment]
It seems like an optional input to the GreedySearch op schema ("Attention Mask") got added between 1.13.1 and 1.14.0 (see this commit - https://github.com/microsoft/onnxruntime/commit/928c9889a36ab13a00737cd439726140ddbab3a6).

If you used the `convert_generation.py` script from 1.14.0 to generate the GreedySearch model and try loading with the 1.13.1 bits, you will get this error.

Can you try using the latest release to run your model ?
