### ISSUE TITLE
onnxruntime C# library 1.13.1 and 1.14.0 keeps external data files open after loading

### ISSUE THREAD

**Issue by fillmore** [microsoft/onnxruntime#14815]
### Describe the issue

After we upgraded onnxruntime C# library from `1.12.1` to `1.14.0`, we found that the external data files of the onnx model were kept open even after the model was loaded; while the onnx file was closed. We also tried `1.13.1` and saw the same issue with `1.14.0`. Is this behavior expected?

Use `1.14.0`
![image](https://user-images.githubusercontent.com/4267105/221064175-61fc7b81-81dd-458d-a2bf-53f33ca2692e.png)

Use `1.12.1`
![image](https://user-images.githubusercontent.com/4267105/221064585-2c675dc9-db7b-4514-8221-63dfd3a595e1.png)

### To reproduce

use `ctor` of `InferenceSession` to load a model with external data files.

```csharp
new InferenceSession(modelPath)
```

### Platform

Linux

### OS Version

CBL-Mariner 2.0

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1, 1.14.0

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

Default CPU

**Comment by pauldog** [comment]
Hi I also reported this issue #14466 (I assume its the same issue?)

I think it's a big issue but pity they didn't fix it for version 1.14

**Comment by pranavsharma** [comment]
Do you've a small repro? Is this specific to C#? Did you try the C++ API as well?

**Comment by fillmore** [comment]
I'll try to create a small repro on Monday.

**Comment by fillmore** [comment]
I create a simple repro in python.
```python
import numpy as np
import onnx
from onnx import helper, TensorProto
import onnxruntime
import os

# create a simple model
shape = (1, 1024, 1024)
values = np.random.randn(*shape).flatten().astype(np.float32)
values = np.asarray(values, dtype=np.float32).tobytes()
initializer_tensor = onnx.helper.make_tensor(name='Const', data_type=TensorProto.FLOAT, dims=shape, vals=values, raw=True)

add_node = helper.make_node("Add", ["X", 'Const'], ["Y"], name="add")

graph = helper.make_graph(
    [add_node],
    "test",
    inputs=[helper.make_tensor_value_info("X", TensorProto.FLOAT, shape)],
    outputs=[helper.make_tensor_value_info("Y", TensorProto.FLOAT, shape)],
    initializer=[initializer_tensor],
)

model = helper.make_model(graph)
onnx.checker.check_model(model)

model_path = "text.onnx"
external_data_path = "test.external_data.bin"

# remove existing model files
try:
    os.remove(model_path)
    os.remove(external_data_path)
except:
    pass

# save model
onnx.save_model(model, model_path, save_as_external_data=True, location=external_data_path)

session = onnxruntime.InferenceSession(model_path)
print(f'InferenceSession created: {session}')

input("Press Enter to exit.\n")
```

When I ran this script with onnxruntime `1.12.1`, `lsof | grep test.external_data.bin` returned nothing; and when I ran this script with onnxruntime `1.13.1` or `1.14.0`, `lsof | grep test.external_data.bin` showed the external data file `test.external_data.bin` was hold by the python process.
![image](https://user-images.githubusercontent.com/4267105/221644790-d6171cf0-0c49-4969-a55d-80b1cc944290.png)

**Comment by fillmore** [comment]
Can someone from ORT team comment on this issue?

**Comment by pranavsharma** [comment]
Thanks for providing the repro. We'll try to take a look at it this week.

**Comment by pranavsharma** [comment]
The external data files are memory mapped after [this PR](https://github.com/microsoft/onnxruntime/pull/11789/). If you see the lsof output it confirms that (see 5th column). This is a more efficient way of reading external initializer files. Is this causing any unintended side effects? If not, this issue can be closed with reason "as designed".

**Comment by fillmore** [comment]
I see. We use [CRIU](https://github.com/checkpoint-restore/criu) to create a snapshot of our application after loading all onnx models, so that we restore it later in many Kubernetes pod instances when we need to scale up the deployments within a short amount of time. With the change you mentioned, we got below error.
![image](https://user-images.githubusercontent.com/4267105/223888656-f06c1761-0a60-4a26-a364-95a6722e2270.png)

**Comment by pranavsharma** [comment]
I can't comment on errors raised by CRIU. This https://github.com/checkpoint-restore/criu/issues/537#issuecomment-419013435 might help.

**Comment by fillmore** [comment]
Is it posible to provide one of the workarounds as below?
- Allow caller to disable the usage of mmap when constructing an `InferenceSession`
- Allow caller to provide the external data as a byte buffer, like the ctor `public InferenceSession(byte[] model)`

**Comment by pranavsharma** [comment]
To solve your problem you can use this API https://github.com/microsoft/onnxruntime/blob/c6074f3a4b09cb44b46ca4422717deb067015bfa/include/onnxruntime/core/session/onnxruntime_c_api.h#L3399-L3401
