### ISSUE TITLE
there are some errors when i try to build onnxruntime with openvino

### ISSUE THREAD

**Issue by shixinlishixinli** [microsoft/onnxruntime#1481]
the error is 
"/home/lisas/program/onnxruntime/onnxruntime/core/providers/openvino/openvino_graph.h:9:32: fatal error: inference_engine.hpp: No such file or directory
compilation terminated."

i am sure . i have successfully installed openvino

best
lisa shi

**Comment by jywu-msft** [comment]
@suryasidd @smkarlap , FYI 

did you follow the build/install instructions at https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#openvino-build 

can you provide your build steps and log outputs?

**Comment by suryasidd** [comment]
You might have missed a step for sourcing environment variables. Could you please follow the steps in the above link? Especially `source setupvars.sh` step.

**Comment by shixinlishixinli** [comment]
hi
thank you for your reply.
i have follow this instructions and i have source setupvars.sh.  i can build onnxruntime without openvino. i can successfully run a demo of openvino . but there are the same error (fatal error: inference_engine.hpp: No such file or directory)

best
lisa shi

**Comment by suryasidd** [comment]
So after you source the setupvars.sh, did you see a message saying OpenVINO environment is initialized? 
Can you send me the build output log and also can you send me the output of the command `echo $INTEL_CVSDK_DIR`?

**Comment by shixinlishixinli** [comment]
i can see a  message saying OpenVINO environment is initialized.
echo $INTEL_CVSDK_DIR : /opt/intel/openvino_2019.1.144
[CMakeOutput.log](https://github.com/microsoft/onnxruntime/files/3435314/CMakeOutput.log)

**Comment by suryasidd** [comment]
Can you please send us the output of the following commands?

- `./build.sh --config RelWithDebInfo --use_openvino CPU_FP32 --build_wheel --parallel` '

- `env`

Just want to make sure your environment is setup properly.

**Comment by shixinlishixinli** [comment]
env
[env.txt](https://github.com/microsoft/onnxruntime/files/3440045/env.txt)
./build.sh --config RelWithDebInfo --use_openvino CPU_FP32 --build_wheel --parallel
[build.txt](https://github.com/microsoft/onnxruntime/files/3440051/build.txt)

**Comment by suryasidd** [comment]
The environment looks fine. We were not able to reproduce this issue on our side. I would be more than happy to understand it further and fix it if we it is possible to schedule a call sometime

**Comment by faxu** [comment]
@shixinlishixinli Do you still need assistance on this? If so, can you please follow up with @suryasidd on a call to deep dive?

**Comment by faxu** [comment]
please reopen if issue still persists or assistance is needed.

**Comment by Godricly** [comment]
identical issue here. Car demo is functional.
## ENV
```
/opt/intel/openvino_2019.2.275
```
## build option
```
./build.sh --config RelWithDebInfo --build_wheel --use_openvino CPU_FP32
```

**Comment by smkarlap** [comment]
ONNX Runtime currently supports OpenVINO version 2019-R1.1. Your environment shows that you have installed version 2019-R2. Please try to build with R1.1.
