### ISSUE TITLE
[Training] Error with installing Stable packages of ORTModule for Pytorch of ROCm

### ISSUE THREAD

**Issue by Looong01** [microsoft/onnxruntime#14821]
### Describe the issue

When I installed the Stable packages of ORTModule for Pytorch of ```ROCm 5.4``` version with following the steps [here](https://onnxruntime.ai/), I met an error that Cannot find "CUDA_HOME" with ```python -m torch_ort.configure```.
Like this:
```
(ONNX) loong@home:~/Codes$ python -m torch_ort.configure
No ROCm runtime is found, using ROCM_HOME='/opt/rocm-5.4.2'
No ROCm runtime is found, using ROCM_HOME='/opt/rocm-5.4.2'
Traceback (most recent call last):
  File "/home/loong/anaconda3/envs/ONNX/lib/python3.9/site-packages/onnxruntime/training/ortmodule/torch_cpp_extensions/cuda/torch_gpu_allocator/setup.py", line 35, in <module>
    cpp_extension.CUDAExtension(
  File "/home/loong/anaconda3/envs/ONNX/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1047, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/home/loong/anaconda3/envs/ONNX/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1179, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/home/loong/anaconda3/envs/ONNX/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 2230, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
There was an error compiling 'torch_gpu_allocator' PyTorch CPP extension
```

I have fully installed ROCm and RCCL and MIOpen. And I can run my machine learning models successfully with the pytorch on ROCm.

### To reproduce

1. ```conda create -n Ort python=3.9```
2. ```conda activate Ort```
3. ```pip install onnxruntime-training -f https://download.onnxruntime.ai/onnxruntime_stable_rocm523.html```
4. ```pip install torch-ort```
5. ```python -m torch_ort.configure```

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.0+rocm523

### PyTorch Version

1.13.1

### Execution Provider

ROCm

### Execution Provider Library Version

ROCm 5.4.2

**Comment by baijumeswani** [comment]
@Looong01 from the error it seems like the torch version might not be rocm. Is that possible?

Would you please share the output of this command?
`python -c "import torch; print(torch.version.cuda); print(torch.version.hip)"`

**Comment by Looong01** [comment]
> @Looong01 from the error it seems like the torch version might not be rocm. Is that possible?
> 
> Would you please share the output of this command? `python -c "import torch; print(torch.version.cuda); print(torch.version.hip)"`

(ONNX) loong@home:~$ python -c "import torch; print(torch.version.cuda); print(torch.version.hip)"
11.7
None

**Comment by Looong01** [comment]
> @Looong01 from the error it seems like the torch version might not be rocm. Is that possible?
> 
> Would you please share the output of this command? `python -c "import torch; print(torch.version.cuda); print(torch.version.hip)"`

And when I take the 4th step, ```pip install torch-ort```, of "To reproduce", it shows that pip tried to install ```nvidia-cuda-nvrtc-cu11```, ```nvidia_cudnn_cu11```, ```nvidia-cuda-runtime-cu11``` and ```nvidia-cublas-cu11```. And at that time, I started feeling something wrong would be made. Then, it comes true.

**Comment by Looong01** [comment]
> Ok, so that confirms my hypothesis. You have torch cuda installed.
> 
> In order to use ORTModule (onnxruntime-training) with rocm, you also need torch with rocm installed since ORTModule takes a dependency on torch.
> 
> You could install it by following the PyTorch instructions here: https://pytorch.org/
> 
> `pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.2`
> 
> Or alternatively, use the rocm docker image to run ORTModule: https://hub.docker.com/r/rocm/pytorch/tags

It works.

But actually, I know how to solve this problem before I put up this issue.

The purpose of my post is to remind you ONNX runtime team that the installing procedure of Ort-training version of ROCm on your [official website](https://onnxruntime.ai/) are wrong. And you should make it correct. When the users use ```pip install torch-ort```, it should detect whether it should install ROCm version of torch or CUDA version. But now, it installs the CUDA version by default, even if the previous installation ```onnxruntime-training```` is the version of ROCm.

**Comment by Looong01** [comment]
> Ok, so that confirms my hypothesis. You have torch cuda installed.
> 
> In order to use ORTModule (onnxruntime-training) with rocm, you also need torch with rocm installed since ORTModule takes a dependency on torch.
> 
> You could install it by following the PyTorch instructions here: https://pytorch.org/
> 
> `pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.2`
> 
> Or alternatively, use the rocm docker image to run ORTModule: https://hub.docker.com/r/rocm/pytorch/tags

Plus:

When I try to install the Active Nightly Packages of Ort-training version of ROCm, it will install CUDA version of ```onnxruntime-training``` (```onnxruntime-training-1.15.0.dev20230201002```, but it should be onnxruntime-training-1.15.0.dev20230201002+rocm54), with ```pip install onnxruntime-training -f https://download.onnxruntime.ai/onnxruntime_nightly_rocm54.html```

**Comment by Looong01** [comment]
> @baijumeswani - thanks for answering the issue. @Looong01 - thanks for bring in this up. Per https://github.com/pytorch/ort/blob/main/torch_ort/requirements.txt , torch_ort would perform default installation if one of them is missing. So I am gonna tag this as doc issue to be fixed in future release. @natke - can we please add more instruction here to clarify for rocm users? https://github.com/pytorch/ort#pre-requisites (would be even better if we can detect it's in rocm env, thus it won't pull cuda as default) thx !!

Yeah, both Stable Packages and Activate Nightly Packages have problems. And theirs are not the same. The former is of the installation step for ```python -m torch_ort.configure```, the latter is of ```pip install onnxruntime-training -f https://download.onnxruntime.ai/onnxruntime_nightly_rocm54.html```.

**Comment by natke** [comment]
Thanks @ytaous. I have created an issue for this in the pytorch/ort repo: https://github.com/pytorch/ort/issues/171

Can this issue otherwise be closed?
