### ISSUE TITLE
[Documentation] cuda options v2 unable to called

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#14836]
### Describe the documentation issue

OrtApi::CreateCUDAProviderOptions”

where to include and how too call    `CreateCUDAProviderOptions(&cuda_options);`?

the docuementation is unclear

### Page / URL

https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#using-v2-provider-options-struct

**Comment by natke** [comment]
@hariharans29 Can you please have a look at this issue and provide more detail on how to use the CUDA options V2?

**Comment by hariharans29** [comment]
> @hariharans29 Can you please have a look at this issue and provide more detail on how to use the CUDA options V2?

Hi @jinfagang - You call it just like the code snippet (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#using-v2-provider-options-struct) shows you to. 

Can you please fill in the complete issue template and explain what you would like to achieve with the CUDA options that led you to look at the afore-mentioned link? Filling in the issue template gives people responding vital details like the API you are trying to use (C++/C#/Python/Java?) and the final goal of trying to use an API.

**Comment by jinfagang** [comment]
resolved it, thanks

**Comment by xeeetu** [comment]
> решил это, спасибо
Можете подсказать, как именно решили?
