### ISSUE TITLE
[Regression] `onnxruntime-gpu==1.14.0` + TensorrtExecutionProvider raises "Please run shape inference on the onnx model first." while `onnxruntime==1.13.1` do not

### ISSUE THREAD

**Issue by fxmarty** [microsoft/onnxruntime#14849]
### Describe the issue

A few tests in our CI related to TensorRT that were passing with `onnxruntime-gpu==1.13.1` are not passing anymore with `onnxruntime-gpu==1.14.0`.

---
Edit: even simplier reproduction: https://huggingface.co/fxmarty/bugged-tensorrtexecutionprovider-ort-1-14/raw/main/encoder_model.onnx

```python
import onnxruntime as ort
import numpy as np

session = ort.InferenceSession(
    "/path/to/encoder_model.onnx",
    providers=["TensorrtExecutionProvider", "CUDAExecutionProvider", "CPUExecutionProvider"]
)

ort_inputs = {
    "input_ids": np.random.randint(20, size=(1, 12)),
    "attention_mask": np.random.randint(2, size=(1, 12)),
}

res = session.run(None, ort_inputs)
```
---

You can try:

```
git clone https://github.com/huggingface/optimum.git
cd optimum
pytest tests/onnxruntime/test_modeling.py -k "ORTModelIntegrationTest and test_passing_provider_options_seq2seq" -s
pytest tests/onnxruntime/test_modeling.py -k "test_pipeline_on_trt_execution_provider_1_t5_False" -s
```

that are
https://github.com/huggingface/optimum/blob/728596e2b5c6255fcef24043c86e6e05a9391c18/tests/onnxruntime/test_modeling.py#L447
https://github.com/huggingface/optimum/blob/728596e2b5c6255fcef24043c86e6e05a9391c18/tests/onnxruntime/test_modeling.py#L2978

With `onnxruntime-gpu==1.13.1` the tests pass, while on 1.14.0 the error
`E       onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc:897 SubGraphCollection_t onnxruntime::TensorrtExecutionProvider::GetSupportedList(SubGraphCollection_t, int, int, const onnxruntime::GraphViewer&, bool*) const [ONNXRuntimeError] : 1 : FAIL : TensorRT input: /block.0/layer.0/SelfAttention/Abs_output_0 has no shape specified. Please run shape inference on the onnx model first. Details can be found in https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#shape-inference-for-tensorrt-subgraphs`

is raised.

Let me know if you would like me to provide a more minimal reproducible example.

### To reproduce

See above

Versions:
TensorRT: 8.4.3.1
CUDA: 11.7
cuDNN: 8.7.0

### Urgency

medium

### Platform

Linux

### OS Version

Linux 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

TensorRT

**Comment by yf711** [comment]
Hi @fxmarty thanks for sharing the context. 

Could you try upgrading TensorRT to 8.5 and see if it works on your side? ORT1.14 has dependency on TRT8.5 if using TensorrtExecutionProvider

I had some experiments on your case and here is the comparison from my side:
  ORT1.13+TRT8.4: pass
  ORT1.13+TRT8.5: pass
  ORT1.14+TRT8.4: error
  ORT1.14+TRT8.5: pass

**Comment by yf711** [comment]
I followed the printouts you shared and run shape inference:
`python /path/to/onnxruntime/python/tools/symbolic_shape_infer.py--input=/path/to/encoder_model.onnx --output=/path/to/inferred_encoder_model.onnx --auto_merge`
On my side, this workaround could skip the issue that trt8.4+ort114 can't support abs op in int32

**Comment by fxmarty** [comment]
Thank you!

Indeed it appears that TensorRT 8.5 is now required https://github.com/microsoft/onnxruntime/pull/14789/files . Thanks for pointing out. It indeed fixes the issue, awesome!
