### ISSUE TITLE
Linker problem in MAUI iOS

### ISSUE THREAD

**Issue by Saravanan-QWC** [microsoft/onnxruntime#14846]
Why do i receive this error when i build the project on MAC book for iOS buid?

    Tool xcrun execution finished (exit code = 1).
            
    ld: framework not found System
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.1024/targets/Xamarin.Shared.Sdk.targets(1225,3): error : clang++ exited with code 1:
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.1024/targets/Xamarin.Shared.Sdk.targets(1225,3): error : ld: framework not found System
    /usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.1024/targets/Xamarin.Shared.Sdk.targets(1225,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation)
Done building target "_LinkNativeExecutable" in project "TestProject.csproj" -- FAILED.

Done building project "TestProject.csproj" -- FAILED.

Build FAILED.

/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.1024/targets/Xamarin.Shared.Sdk.targets(1225,3): error : clang++ exited with code 1:
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.1024/targets/Xamarin.Shared.Sdk.targets(1225,3): error : ld: framework not found System
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/16.2.1024/targets/Xamarin.Shared.Sdk.targets(1225,3): error : clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Saravanan-QWC** [comment]
I have identified the problem. When you add `Microsoft.EntityFrameworkCore.SqlServer` to your project i get this error.

**Comment by natke** [comment]
Thanks for this @Saravanan-QWC. Are you able to work around the issue or does it need more investigation?

If more investigation, can you please list as many details of your environment as possible? 

O/S version
ORT version
Exact build command

**Comment by Saravanan-QWC** [comment]
Yes, Correct.

But Microsoft.EntityFrameworkCore.SqlServer 7.x package does not work. Therefore, I had downgraded to Microsoft.EntityFrameworkCore.SqlServer 6.0.14.
