### ISSUE TITLE
How to infer multiple neural network models in parallel on CPU

### ISSUE THREAD

**Issue by WANG-XIN-EE** [microsoft/onnxruntime#14853]
### Describe the issue

In my application of onnxruntime, I want to inference multiple neural network models in parallel on CPU. Thus, I want to know how can i realize this? 

### To reproduce

there are several diffrent onnx models. they need to be inferenced at the same time

### Platform

Linux

### OS Version

centos 7

### ONNX Runtime Installation

Other / Unknown

### ONNX Runtime Version or Commit ID

12.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by pranavsharma** [comment]
Create a session per model and call Run() on each session in separate threads. You can also choose to use multiple processes to do the same.

**Comment by WANG-XIN-EE** [comment]
> Create a session per model and call Run() on each session in separate threads. You can also choose to use multiple processes to do the same.

Thanks for your reply！I will have a try

**Comment by WANG-XIN-EE** [comment]
> Create a session per model and call Run() on each session in separate threads. You can also choose to use multiple processes to do the same.

There is another problem when i try to realize the method. All models have the same shape of input. Thus i try to use "vector" to to contain all the inputs like this:

std::vector<std::vector<Ort::Value>> ort_inputs;
ort_inputs.resize(Num_LSTM);
for (int i = 0;i <= Num_LSTM - 1;i++)
{
    /*********input**********/
    std::vector<float> input_tensor_values(input_tensor_size);
    for (unsigned int i = 0; i < input_tensor_size; i++)
        input_tensor_values[i] = (float)1;
    // create input tensor object from data values
    auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
    Ort::Value input_tensor = Ort::Value::CreateTensor<float>(memory_info, input_tensor_values.data(), input_tensor_size, input_node_dims.data(), 3);
    
    /*********h0**********/
    std::vector<float> input_h0_tensor_values(input_h0_tensor_size);
    for (unsigned int i = 0; i < input_h0_tensor_size; i++)
        input_h0_tensor_values[i] = (float)0;
    // create input tensor object from data values
    auto h0_memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
    Ort::Value input_h0_tensor = Ort::Value::CreateTensor<float>(h0_memory_info, input_h0_tensor_values.data(), input_h0_tensor_size, input_h0_node_dims.data(), 3);

    /*********c0**********/
    std::vector<float> input_c0_tensor_values(input_c0_tensor_size);
    for (unsigned int i = 0; i < input_c0_tensor_size; i++)
        input_c0_tensor_values[i] = (float)0;
    // create input tensor object from data values
    auto c0_memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
    Ort::Value input_c0_tensor = Ort::Value::CreateTensor<float>(c0_memory_info, input_c0_tensor_values.data(), input_c0_tensor_size, input_c0_node_dims.data(), 3);

    ort_inputs[i].push_back(static_cast<Ort::Value&&>(input_tensor));        
    ort_inputs[i].push_back(std::move(input_h0_tensor));
    ort_inputs[i].push_back(std::move(input_c0_tensor));
}
std::vector<std::vector<Ort::Value>> output_tensors;
output_tensors.resize(Num_LSTM);
std::vector<Ort::Value> output_tensorstemp;
    
for(int i = 0; i <= Num_LSTM - 1; i++)
{        
    output_tensorstemp = (*(session_ + i)).Run(Ort::RunOptions{nullptr}, input_node_names.data(), ort_inputs[i].data(), ort_inputs[i].size(), output_node_names.data(), 1);
}

but the results inferenced from the models are not right. Could you give me some advice for these codes. Thanks!

**Comment by WANG-XIN-EE** [comment]
> Create a session per model and call Run() on each session in separate threads. You can also choose to use multiple processes to do the same.

Create a session per model and call Run() on each session in separate threads. You can also choose to use multiple processes to do the same.

There is another problem when i try to realize the method. All models have the same shape of input. Thus i try to use "vector" to to contain all the inputs like this:

std::vector<std::vectorOrt::Value> ort_inputs;
ort_inputs.resize(Num_LSTM);
for (int i = 0;i <= Num_LSTM - 1;i++)
{
/input*/
std::vector input_tensor_values(input_tensor_size);
for (unsigned int i = 0; i < input_tensor_size; i++)
input_tensor_values[i] = (float)1;
// create input tensor object from data values
auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
Ort::Value input_tensor = Ort::Value::CreateTensor(memory_info, input_tensor_values.data(), input_tensor_size, input_node_dims.data(), 3);
/*********h0**********/
std::vector<float> input_h0_tensor_values(input_h0_tensor_size);
for (unsigned int i = 0; i < input_h0_tensor_size; i++)
    input_h0_tensor_values[i] = (float)0;
// create input tensor object from data values
auto h0_memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
Ort::Value input_h0_tensor = Ort::Value::CreateTensor<float>(h0_memory_info, input_h0_tensor_values.data(), input_h0_tensor_size, input_h0_node_dims.data(), 3);
/*********c0**********/
std::vector<float> input_c0_tensor_values(input_c0_tensor_size);
for (unsigned int i = 0; i < input_c0_tensor_size; i++)
    input_c0_tensor_values[i] = (float)0;
// create input tensor object from data values
auto c0_memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
Ort::Value input_c0_tensor = Ort::Value::CreateTensor<float>(c0_memory_info, input_c0_tensor_values.data(), input_c0_tensor_size, input_c0_node_dims.data(), 3);

ort_inputs[i].push_back(static_cast<Ort::Value&&>(input_tensor));        
ort_inputs[i].push_back(std::move(input_h0_tensor));
ort_inputs[i].push_back(std::move(input_c0_tensor));
}
std::vector<std::vectorOrt::Value> output_tensors;
output_tensors.resize(Num_LSTM);
std::vectorOrt::Value output_tensorstemp;
for(int i = 0; i <= Num_LSTM - 1; i++)
{
output_tensorstemp = (*(session_ + i)).Run(Ort::RunOptions{nullptr}, input_node_names.data(), ort_inputs[i].data(), ort_inputs[i].size(), output_node_names.data(), 1);
}

but the results inferenced from the models are not right. Could you give me some advice for these codes. Thanks!

**Comment by WANG-XIN-EE** [comment]
> Create a session per model and call Run() on each session in separate threads. You can also choose to use multiple processes to do the same.

There is another problem when i try to realize the method. All models have the same shape of input. Thus i try to use "vector" to to contain all the inputs like this:

std::vector<std::vectorOrt::Value> ort_inputs;
ort_inputs.resize(Num_LSTM);
for (int i = 0;i <= Num_LSTM - 1;i++)
{
/*********input**********/
std::vector input_tensor_values(input_tensor_size);
for (unsigned int i = 0; i < input_tensor_size; i++)
input_tensor_values[i] = (float)1;
// create input tensor object from data values
auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
Ort::Value input_tensor = Ort::Value::CreateTensor(memory_info, input_tensor_values.data(), input_tensor_size, input_node_dims.data(), 3);
/*********h0**********/
std::vector<float> input_h0_tensor_values(input_h0_tensor_size);
for (unsigned int i = 0; i < input_h0_tensor_size; i++)
    input_h0_tensor_values[i] = (float)0;
// create input tensor object from data values
auto h0_memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
Ort::Value input_h0_tensor = Ort::Value::CreateTensor<float>(h0_memory_info, input_h0_tensor_values.data(), input_h0_tensor_size, input_h0_node_dims.data(), 3);
/*********c0**********/
std::vector<float> input_c0_tensor_values(input_c0_tensor_size);
for (unsigned int i = 0; i < input_c0_tensor_size; i++)
    input_c0_tensor_values[i] = (float)0;
// create input tensor object from data values
auto c0_memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
Ort::Value input_c0_tensor = Ort::Value::CreateTensor<float>(c0_memory_info, input_c0_tensor_values.data(), input_c0_tensor_size, input_c0_node_dims.data(), 3);

ort_inputs[i].push_back(static_cast<Ort::Value&&>(input_tensor));        
ort_inputs[i].push_back(std::move(input_h0_tensor));
ort_inputs[i].push_back(std::move(input_c0_tensor));
}
std::vector<std::vectorOrt::Value> output_tensors;
output_tensors.resize(Num_LSTM);
std::vectorOrt::Value output_tensorstemp;

for(int i = 0; i <= Num_LSTM - 1; i++)
{
output_tensorstemp = (*(session_ + i)).Run(Ort::RunOptions{nullptr}, input_node_names.data(), ort_inputs[i].data(), ort_inputs[i].size(), output_node_names.data(), 1);
}

but the results inferenced from the models are not right. Could you give me some advice for these codes. Thanks!

**Comment by WANG-XIN-EE** [comment]
> Create a session per model and call Run() on each session in separate threads. You can also choose to use multiple processes to do the same.

I have try to create a session per model and use openmp for parallel running, but the results are not satisfying. When I use "#pragma omp parallel num_threads(1)", the time use is 4.7ms, but when i use "#pragma omp parallel num_threads(10)", the time use is 8.3ms. It means that when i use multi-threads for parallel, there is no improvement in time-consuming. The codes are as follows:

int main()
{
    int Num_LSTM = 100;

    Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");
    Ort::SessionOptions session_options;
    session_options.SetIntraOpNumThreads(1);
  
    session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);

    const char* model_path = "../net_LSTM_IEEE2383_20220820_G0V4_gpu_static.onnx";
    Ort::Session session_template(env, model_path, session_options);
    
    void *p = operator new(Num_LSTM*sizeof(Ort::Session));
    Ort::Session* session_ = static_cast<Ort::Session*>(p);
    for(int i = 0; i <= Num_LSTM - 1; i++)
    {
        new(session_ + i) Ort::Session(env, model_path, session_options);
    }
    // session_.resize(Num_LSTM);
    // print model input layer (node names, types, shape etc.)
    Ort::AllocatorWithDefaultOptions allocator;

    // // print number of model input nodes
    // std::vector<const char*> input_node_names = {"input","h0","c0"};
    // std::vector<const char*> output_node_names = {"output,hn,cn"}; 
    // /*********input**********/
    std::vector<int64_t> input_node_dims = {1, 1, 6};
    size_t input_tensor_size = 6; 
    // /*********h0**********/
    std::vector<int64_t> input_h0_node_dims = {3, 1, 32};
    size_t input_h0_tensor_size = 3 * 1 * 32; 
    // /*********c0**********/
    std::vector<int64_t> input_c0_node_dims = {3, 1, 32};
    size_t input_c0_tensor_size = 3 * 1 * 32; 
    
    double t_1;
    
      auto start1_1 = std::chrono::steady_clock::now();
      #pragma omp parallel num_threads(10)
      for (int i = 0;i <= Num_LSTM - 1;i++)
      {
          size_t num_input_nodes = session_[i].GetInputCount();
          
          /*********input**********/
          std::vector<float> input_tensor_values(input_tensor_size);
          for (unsigned int i = 0; i < input_tensor_size; i++)
              input_tensor_values[i] = (float)1;
          // create input tensor object from data values
          auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
          Ort::Value input_tensor = Ort::Value::CreateTensor<float>(memory_info, input_tensor_values.data(), input_tensor_size, input_node_dims.data(), 3);
          assert(input_tensor.IsTensor());
          
          /*********h0**********/
          std::vector<float> input_h0_tensor_values(input_h0_tensor_size);
          for (unsigned int i = 0; i < input_h0_tensor_size; i++)
              input_h0_tensor_values[i] = (float)0;
          // create input tensor object from data values
          auto h0_memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
          Ort::Value input_h0_tensor = Ort::Value::CreateTensor<float>(h0_memory_info, input_h0_tensor_values.data(), input_h0_tensor_size, input_h0_node_dims.data(), 3);
          assert(input_h0_tensor.IsTensor());

          /*********c0**********/
          std::vector<float> input_c0_tensor_values(input_c0_tensor_size);
          for (unsigned int i = 0; i < input_c0_tensor_size; i++)
              input_c0_tensor_values[i] = (float)0;
          // create input tensor object from data values
          auto c0_memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
          Ort::Value input_c0_tensor = Ort::Value::CreateTensor<float>(c0_memory_info, input_c0_tensor_values.data(), input_c0_tensor_size, input_c0_node_dims.data(), 3);
          assert(input_c0_tensor.IsTensor());

          std::vector<Ort::Value> ort_inputs;
          ort_inputs.push_back(std::move(input_tensor));        
          ort_inputs.push_back(std::move(input_h0_tensor));
          ort_inputs.push_back(std::move(input_c0_tensor));

          std::vector<const char*> input_node_names = {"input","h0","c0"};
          std::vector<const char*> output_node_names = {"output,hn,cn"}; 
          std::vector<Ort::Value> output_tensors = (*(session_ + i)).Run(Ort::RunOptions{nullptr}, input_node_names.data(), ort_inputs.data(), ort_inputs.size(), output_node_names.data(), 1);
      }
      auto end1_1 = std::chrono::steady_clock::now();
      std::chrono::duration<double, std::milli> elapsed_temptui_1 = end1_1 - start1_1;
      t_1 = elapsed_temptui_1.count();
 
    cout<<t_1<<"ms"<<endl;

    std::cout<<"ok"<<endl;
    printf("Done!\n");
    return 0;
}

could you give me a help for this? Thanks

**Comment by RandySheriffH** [comment]
@WANG-XIN-EE: how many physical cores are there on your system? The first thing to debug such an observation is to make sure you are not over-subscribing.

**Comment by WANG-XIN-EE** [comment]
thanks for your attention! it has been solved now. there is a error in "openmp" programming syntax. it is solved by change "#pragma omp parallel num_threads(10)" to "#pragma omp parallel **for** num_threads(10)"

**Comment by WANG-XIN-EE** [comment]
@RandySheriffH thanks for your attention. the problem has been solved. there is a mistake in "openmp" programming syntax. it is sovled by change " #pragma omp parallel num_threads(10)" to " **#pragma omp parallel for num_threads(10)**".  unforgettable experience
