### ISSUE TITLE
[Build] Unable to checkout in cmake/external/onnx

### ISSUE THREAD

**Issue by UsterNes** [microsoft/onnxruntime#14861]
### Describe the issue

I'm building onnxruntime on CentOS 7.9 x86 (32 bit).

Command: git submodule update --init --recursive
Error:
fatal: reference is not a tree: 9b7bca2a723ff94edcd007d93b5d0cf1838591dc
Unable to checkout `9b7bca2a723ff94edcd007d93b5d0cf1838591dc` in submodule path `cmake/external/onnx`.

### Target platform

Linux

### Build script

./build --config Release --build_shared_lib --use_xnnpack

### Error / output

fatal: reference is not a tree: 9b7bca2a723ff94edcd007d93b5d0cf1838591dc
Unable to checkout `9b7bca2a723ff94edcd007d93b5d0cf1838591dc` in submodule path `cmake/external/onnx`.

**Comment by snnn** [comment]
Add "--skip_submodule_sync" to your build command.

**Comment by UsterNes** [comment]
Thank you!

**Comment by kishorenc** [comment]
The SHA `9b7bca2a723ff94edcd007d93b5d0cf1838591dc` no longer exists on the `onnx` repository: https://github.com/onnx/onnx/commit/9b7bca2a723ff94edcd007d93b5d0cf1838591dc

While the workaround helps. the actual issue should still be fixed.

**Comment by snnn** [comment]
I will delete the submodule. I have too many things on my hands. I will try to finish them as soon as I can.
