### ISSUE TITLE
Model optimized with `convert_float_to_float16` handles well model using `torch.uint8` , but fails for `torch.bool` with `Shape mismatch attempting to re-use buffer`

### ISSUE THREAD

**Issue by fxmarty** [microsoft/onnxruntime#14865]
### Describe the issue

Hi ORT team,

In transformers, replacing in the modeling of decoder models `self.bias` to use `torch.bool` instead of `torch.uint8` breaks the usage of ONNX Runtime's `convert_float_to_float16` with the classic `Shape mismatch attempting to re-use buffer` error. As I see, the PR linked below introduces no other changes than that.

Is it something expected? Maybe ONNX Runtime optimizations have a harder time working with `boolean` dtype?

See this PR: https://github.com/huggingface/transformers/pull/21384

The sole changes are here (as seen in the PR diff):
* https://github.com/huggingface/transformers/blob/v4.26.1/src/transformers/models/gpt2/modeling_gpt2.py#L129 (replace `torch.uint8` by `torch.bool`)
* https://github.com/huggingface/transformers/blob/ae54e3c3b18bac0832ad62ea9b896dfd52a09850/src/transformers/models/gpt2/modeling_gpt2.py#L195 (remove `to(torch.bool)`)

### To reproduce

Reproduction:
```
git clone https://github.com/huggingface/transformers.git && cd transformers && pip install -U -e .
git clone https://github.com/huggingface/optimum.git && cd optimum && pip install -U -e .
```

On the previous working commit (that uses uint8):
```
cd transformers
git checkout cc44e72d147f9d334367acf96045704194357903
optimum-cli export onnx --model hf-internal-testing/tiny-random-gpt2 --task causal-lm-with-past --device cuda --optimize O4 --no-post-process gpt2_onnx_old
```

And (that uses bool):
```
cd transformers
git checkout c51dc4f92755c67a83f3fc8a0bd6b3e64df199e4
optimum-cli export onnx --model hf-internal-testing/tiny-random-gpt2 --task causal-lm-with-past --device cuda --optimize O4 --no-post-process gpt2_onnx
```

raising:
`Exception: An error occured during validation, but the model was saved nonetheless at gpt2_onnx. Detailed error: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION :
Non-zero status code returned while running Concat node. Name:'/transformer/h.0/attn/Concat_3' Status Message: 
/onnxruntime_src/onnxruntime/core/framework/op_kernel.cc:83 virtual OrtValue* onnxruntime::OpKernelContext::OutputMLValue(int, const 
onnxruntime::TensorShape&) status.IsOK() was false. Shape mismatch attempting to re-use buffer. {2,4,16,8} != {2,4,17,8}. Validate usage of dim_value (values
should be > 0) and dim_param (all values with the same string should equate to the same size) in shapes in the model.`

Alternatively, find the models, with the issue being on `decoder_with_past_model.onnx`:
* On commit c51dc4f92755c67a83f3fc8a0bd6b3e64df199e4, using bool during the export: 
    * repo: https://huggingface.co/fxmarty/gpt2-tiny-c51dc4f92755c67a83f3fc8a0bd6b3e64df199e4-bool/tree/main
    * netron: https://netron.app/?url=https://huggingface.co/fxmarty/gpt2-tiny-c51dc4f92755c67a83f3fc8a0bd6b3e64df199e4-bool/blob/main/decoder_with_past_model.onnx
* On commit cc44e72d147f9d334367acf96045704194357903, using uint8 during the export:
    * repo: https://huggingface.co/fxmarty/gpt2-tiny-cc44e72d147f9d334367acf96045704194357903-uint8/tree/main
    * netron: https://netron.app/?url=https://huggingface.co/fxmarty/gpt2-tiny-cc44e72d147f9d334367acf96045704194357903-uint8/blob/main/decoder_with_past_model.onnx
 
Note that the error raised is on `/transformer/h.0/attn/Concat_3`, although the change to `torch.bool` seem to affect rightfully only `/transformer/h.0/attn/Slice_3` that is later in the model. So I'm surprised that the error is raised on `/transformer/h.0/attn/Concat_3`.

And run the code (you can run this one on transformers and optimum stable):

```python
from optimum.onnxruntime import ORTModelForCausalLM, ORTOptimizer, AutoOptimizationConfig
from transformers import AutoTokenizer

#model_id = "fxmarty/gpt2-tiny-c51dc4f92755c67a83f3fc8a0bd6b3e64df199e4-bool"
model_id = "fxmarty/gpt2-tiny-cc44e72d147f9d334367acf96045704194357903-uint8"
model = ORTModelForCausalLM.from_pretrained(model_id, provider="CUDAExecutionProvider")
tokenizer = AutoTokenizer.from_pretrained(model_id)

inp = tokenizer("This is me and", return_tensors="pt").to("cuda")

res = model.generate(**inp)

print(res)

```

### Urgency

medium

### Platform

Linux

### OS Version

Linux 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.7

**Comment by fxmarty** [comment]
cc @tianleiwu

**Comment by tianleiwu** [comment]
I can reproduce the issue. Let me do some debugging and find out the cause.

**Comment by tianleiwu** [comment]
@fxmarty, Further investigation shows that the root cause is dynamic axes of inputs and outputs are not correct. Since past_key_values and present_key_values are assigned same symbolic shape, and ORT will try reuse buffer.

For example, the shape:
```
input_ids: [batch_size, 1]
past_key_values.0.key: [batch_size, 4, past_sequence_length + sequence_length, 8]
present_key_values.0.key: [batch_size, 4, past_sequence_length + sequence_length, 8]
```

Recommended change (by setting dynamic axes during torch.onn.export):
```
input_ids: [batch_size, 1]
past_key_values.0.key: [batch_size, 4, past_sequence_length, 8]
present_key_values.0.key: [batch_size, 4, past_sequence_length + 1, 8]
```
