### ISSUE TITLE
[Build] 

### ISSUE THREAD

**Issue by UsterNes** [microsoft/onnxruntime#14893]
### Describe the issue

Compiling on 32 bit Centos7.9.

There are some hints for X86 or I386 in the code, however they mostly if-else statements for Mac or Windows.

Is 32bit any doable for Linux ?
We have ~400 relatively new x32 servers, we would like to run onnxruntime.

### Target platform

CentOS 7.9 i686 | Python 3.9

### Build script

./build.sh --config Release --build_shared_lib --skip_submodule_sync --compile_no_warning_as_error [--use_xnnpack]

### Error / output

[ 17%] Building CXX object _deps/abseil_cpp-build/absl/hash/CMakeFiles/absl_hash.dir/internal/hash.cc.o

In file included from /home/onnxruntime/build/Linux/Release/_deps/abseil_cpp-src/absl/hash/internal/hash.cc:15:0:
/home/onnxruntime/build/Linux/Release/_deps/abseil_cpp-src/absl/hash/internal/hash.h: In lambda function:
/home/onnxruntime/build/Linux/Release/_deps/abseil_cpp-src/absl/hash/internal/hash.h:447:24: error: ‘has_unique_object_representations_v’ is not a member of ‘std’
     static_assert(std::has_unique_object_representations_v<T C::*>);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/onnxruntime/build/Linux/Release/_deps/abseil_cpp-src/absl/hash/internal/hash.h:447:24: note: suggested alternative: ‘has_unique_object_representations’
     static_assert(std::has_unique_object_representations_v<T C::*>);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        has_unique_object_representations
/home/onnxruntime/build/Linux/Release/_deps/abseil_cpp-src/absl/hash/internal/hash.h:447:62: error: expected primary-expression before ‘C’
     static_assert(std::has_unique_object_representations_v<T C::*>);
                                                              ^
/home/onnxruntime/build/Linux/Release/_deps/abseil_cpp-src/absl/hash/internal/hash.h:447:62: error: expected ‘,’ before ‘C’
/home/onnxruntime/build/Linux/Release/_deps/abseil_cpp-src/absl/hash/internal/hash.h:447:62: error: expected string-literal before ‘C’
/home/onnxruntime/build/Linux/Release/_deps/abseil_cpp-src/absl/hash/internal/hash.h:447:62: error: expected ‘)’ before ‘C’
gmake[2]: *** [_deps/abseil_cpp-build/absl/hash/CMakeFiles/absl_hash.dir/internal/hash.cc.o] Error 1

### GCC / Compiler Version

gcc 7.3

**Comment by yuslepukhin** [comment]
It does not appear to be an issue of 64 vs 32 bit. We require C++17 compiler to build the product, although the users who build their clients could get away with C++14 or even 11.

`has_unique_object_representations_v is not a member of std` is a good indicator.

Type shortcuts for `_v` instead of writing `std::has_unique_object_representations<>::value` appeared only C++17.

Shortcuts such as `std::enable_if_t<>` instead of writing `std::enable_if<>::type` are available since C++14.

**Comment by UsterNes** [comment]
I see `set(CMAKE_CXX_STANDARD  17)` in most places in the code, except of some cmake/external/ folders.
I will try to fix shoutcuts `_v` in the code.
Thank you!

**Comment by yuslepukhin** [comment]
The error most likely means that the compiler's support for C++17 is incomplete.

**Comment by UsterNes** [comment]
Thank you, looks like that is it!
I compiled gcc-7.3 and removed gcc-4.8, but I found out that some libraries are still 4.8 version, such as libgcc.
