### ISSUE TITLE
wrong input parameter of operator (NonMaxSuppression)

### ISSUE THREAD

**Issue by wunianqing** [microsoft/onnxruntime#14899]
ONNX runtime version: 1.13.1
API version: cxx API

I am trying to run the model posted here. It is a yolov8 model with an extra node to do NMS. The original model is downloaded from the official website. The modified model passed the `onnx.checker.check_model()` funtion. However, it reported error when trying to reference.
Load model from yolov8n_nms.onnx failed:This is an invalid model. Type Error: Type 'tensor(float)' of input parameter (score_threshold) of operator (NonMaxSuppression) in node () is invalid.
[yolov8n_nms.zip](https://github.com/microsoft/onnxruntime/files/10879263/yolov8n_nms.zip)

I have no idea why this could happen. Any help would be appreciated. Thanks!

**Comment by PINTO0309** [comment]
I don't know how you generated the NMS, but it is obvious that the parameters are interchanged.
![image](https://user-images.githubusercontent.com/33194443/222877585-c4842aec-c5c2-4aaf-8d71-80362faec793.png)

**Comment by wunianqing** [comment]
Thanks for the quick response.
I use Netron to view the model. But it does not provide the parameter info. What tool do you use?

I still have one question. Why the error message says _Type '**tensor(float)**' of input parameter (score_threshold) of operator (NonMaxSuppression) in node () is invalid._ Should not  be tensor(int64) is invalid? I tried to change float to float16. And the error message changed to tensor(float16) too. So the type in the error message is not the one it should be, but the one it actually is.
