### ISSUE TITLE
[Mobile] Failed to load DLL 'onnxruntime' on Unity App for iOS

### ISSUE THREAD

**Issue by digitalmonkey** [microsoft/onnxruntime#14914]
### Describe the issue

I am building a Unity App for iOS using onnxruntime. I was able to test my code in the editor using the MacOS plugin for onnxruntime and everything works fine.  To build to iOS, I first tried adding the iOS onnxruntime.framework provided in the nuget build and embedding the libraries in the binary. I was unable to install due to code signing issues.

I then tried to manually add the framework to the generated Xcode project and was able to install, but at runtime, I see these following errors the moment I reach by onnxruntime code (I'm using the C# bindings). Any insight will be appreciated!

macOS Version 13.1 (Build 22C65)
Xcode 14.2 (21534) (Build 14C18)
Timestamp: 2023-03-03T21:23:57-08:00

DllNotFoundException: Unable to load DLL 'onnxruntime'. Tried the load the following dynamic libraries: Unable to load dynamic library '/onnxruntime' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen(/onnxruntime, 0x0005): tried: '/onnxruntime' (errno=2), '/private/preboot/Cryptexes/OS/onnxruntime' (errno=2), '/onnxruntime' (errno=2)
  at Microsoft.ML.OnnxRuntime.NativeMethods.OrtGetApiBase () [0x00000] in <00000000000000000000000000000000>:0 
  at Microsoft.ML.OnnxRuntime.NativeMethods..cctor () [0x00000] in <00000000000000000000000000000000>:0 
  at Microsoft.ML.OnnxRuntime.SessionOptions..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at Microsoft.ML.OnnxRuntime.InferenceSession..ctor (System.String modelPath) [0x00000] in <00000000000000000000000000000000>:0 
  at MuscleActivationPredictor.InferWithOnnxRuntime () [0x00000] in <00000000000000000000000000000000>:0 
  at MuscleActivationPredictor.Update () [0x00000] in <00000000000000000000000000000000>:0 
Rethrow as TypeInitializationException: The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.
  at Microsoft.ML.OnnxRuntime.SessionOptions..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at Microsoft.ML.OnnxRuntime.InferenceSession..ctor (System.String modelPath) [0x00000] in <00000000000000000000000000000000>:0 
  at MuscleActivationPredictor.InferWithOnnxRuntime () [0x00000] in <00000000000000000000000000000000>:0 
  at MuscleActivationPredictor.Update () [0x00000] in <00000000000000000000000000000000>:0 

### To reproduce

1. Create a Unity project with some Onnx runtime code.
2. Build to Xcode project.
3. Install on the iOS device.
4. The moment you reach the onnx runtime code, the Unable to load DLL error appears in the debug output of Xcode.
Note: this is a silent error, execution continues but no onnx runtime code is run.

### Urgency

We are working on a science project competition to be presented next week. We can run things on a laptop but would prefer to use a mobile tablet.

### Platform

iOS

### OS Version

iOS (iPadOS) 16.3

### ONNX Runtime Installation

Built from Source

### Compiler Version (if 'Built from Source')

Xcode 14.2

### Package Name (if 'Released Package')

Microsoft.ML.OnnxRuntime

### ONNX Runtime Version or Commit ID

6c8538f0862f213ba8df3ffde67e81024a7a810f

### ONNX Runtime API

C#

### Architecture

ARM64

### Execution Provider

CoreML

**Comment by skottmckay** [comment]
It sounds off for it to be trying to load a DLL for the native ORT code on iOS as usually when you link against the xcframework which has static libraries they would be included as part of the app. Not sure if Unity is throwing something off, but here is where we set the library name to call the native ORT code (Microsoft.ML.OnnxRuntime) from the C# managed bindings (Microsoft.ML.OnnxRuntime.Managed). For iOS that should be `__Internal` not `onnxruntime`.

https://github.com/microsoft/onnxruntime/blob/f88b97ede272e54d67e7f4da165359df4b534a4a/csharp/src/Microsoft.ML.OnnxRuntime/NativeMethods.shared.cs#L451-L465

Which managed library from Microsoft.ML.OnnxRuntime.Managed is being included in your app? It should either be net6.0-ios16.1 or xamarinios10. The various libraries that the nuget package contains are shown here:

<img width="534" alt="image" src="https://user-images.githubusercontent.com/979079/223098897-7d2b6810-28d7-4fe3-b827-46ca7606151a.png">

You can possibly check by looking at the managed dll being used by your app in ILSpy. Here's what NativeMethods.NativeLib.DLLName is set to in microsoft.ml.onnxruntime.managed.1.14.1\lib\net6.0-ios16.1\Microsoft.ML.OnnxRuntime.dll:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/979079/223099197-19f829f8-edd6-431f-9fb9-ba4d9f2cb0f6.png">

**Comment by digitalmonkey** [comment]
Thank you! I'll take a look at these. In the meantime, I have a workaround - I ended up writing a native iOS plugin for Unity that links to onnxruntime directly with Cocoapods. It works. However, I will try to get the managed version of Onnxruntime working with your suggestions too.

**Comment by supnaobed** [comment]
@digitalmonkey 

Hi there,

I've run into the same issue you've described here and it's been stalling my progress for weeks now. Could you please share the solution you've found or the plugin you used to overcome this problem? Any help would be greatly appreciated.

Thank you in advance for your time and assistance.

**Comment by skottmckay** [comment]
IIUC Unity is C# based so I would expect you'd need to use the Microsoft.ML.OnnxRuntime.Managed nuget package for the C# bindings, and the Microsoft.ML.OnnxRuntime native package for the native library. 

The native package contains an xcframework for iOS with static libraries. Due to that the onnxruntime native code should be built into the app as there's no dynamic library to load. Any error about failing to load onnxruntime.dll would indicate something is incorrect with the setup and it's choosing the wrong option for iOS.

Which library from the Microsoft.ML.OnnxRuntime.Managed package is being included in your app?

**Comment by natke** [comment]
@digitalmonkey Did you manage to get this working? Let us know how you went!

**Comment by digitalmonkey** [comment]
@natke I eventually got things to work by implementing my own C-based native iOS plugin using the Onnx C runtime libraries. I used Cocoapods to add the onyx runtime libraries to the Xcode project produced by Unity. My Podfile looked like this:
`platform :ios, '13.0'

target 'UnityFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnityFramework
  pod 'onnxruntime-c'
  
  pod 'onnxruntime-extensions-c'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end`

I also had to include my .onnx file in the resource bundle of my Unity-iPhone project. 

However, I hope with the new Unity Sentis coming out, they apparently can support LSTM networks better than the Barracuda version, so if I can get that to work, there hopefully will not be the need to do this nasty workaround.

**Comment by blueyred** [comment]
One of the issues here is that Unity supports upto .Net4 not .Net6, so using the libraries from the nuget "net6.0-ios16.1" will be problematic. Is it possible to use the "netstandard2.0" to build the IOS managed code?

**Comment by skottmckay** [comment]
@blueyred AFAIK there's no iOS target for netstandard2.0 so it's not possible. We include Xamarin builds for older versions of .net. .net6 was when Xamarin was essentially merged into .net as MAUI.

**Comment by yosun** [comment]
hey just wondering if there are any updates on a more streamlined method to use onyx for unity ios?
