### ISSUE TITLE
numbeam=1 not working for beamsearchT5 

### ISSUE THREAD

**Issue by shiqingzhangCSU** [microsoft/onnxruntime#14920]
### Describe the issue
![image](https://user-images.githubusercontent.com/44834482/223006614-6bda7e08-aed5-4bcf-b00c-d80eee653a73.png)

I use beamserchT5, numbeam is 2 and 3, the model can output normally, but numbeam is 1 when it reports an error, how can I use greedy mode?

### To reproduce

Use the T5 model exported by the transformer tool》

### Platform

Linux

### OS Version

7.4

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

Python

### Architecture

X86

### Execution Provider

CUDA

### Execution Provider Library Version

cuda 11.3

**Comment by wangyems** [comment]
Thanks for reporting this issue. We'll have a look.
The greedy mode is currently not available for T5.

**Comment by wangyems** [comment]
This issue should have been resolved by https://github.com/microsoft/onnxruntime/pull/14928/files#diff-a1e55fcadd7c5108d7cf89e5c813c787e625c9e9a5e727d8f8f4c67fc56d4f25
