### ISSUE TITLE
Graph is not a DAG assertion error when quantizing onnx model

### ISSUE THREAD

**Issue by Hrayo712** [microsoft/onnxruntime#14937]
### Describe the issue

I am trying to quantize a custom onnx model, but when running it through the quantization API, I get a
"Graph is not a DAG" assertion error.

### To reproduce

[custom_model.zip](https://github.com/microsoft/onnxruntime/files/10908770/custom_model.zip)

Quantize the model via `quantize_static`  with the following quantization settings:

QuantFormat = QuantFormat.QOperator
activation type = QuantType.QUInt8
weight type = QuantType.QUInt8
Calibrate method = CalibrationMethod.MinMax
quantize_per_channel = True

I am attaching the onnx model to facilitate reproducing the error

Thanks in advance for the team's support

### Platform

Linux

### OS Version

18

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.8.1

### ONNX Runtime API

Python

### Architecture

X86

### Execution Provider

Default CPU

**Comment by jchen351** [comment]
@Hrayo712 Can you provide me with a CalibrationDataReader so I can run it in debug mode?

**Comment by Hrayo712** [comment]
Of course!

In the attached zip, you'll find a python script which defines `CalibrationDataGen` you can use.

Thanks in advance for your support!

[datareader.zip](https://github.com/microsoft/onnxruntime/files/10942640/datareader.zip)

**Comment by jchen351** [comment]
@Hrayo712  I cannot reproduce the error. I am using onnxruntime 1.14.1 (lastest) this is what I got running following python script:

```
import onnx
from onnxruntime.quantization import quantize_static, QuantFormat, QuantType, CalibrationMethod ,preprocess

from datareader import CalibrationDataGen

class Main:
    input_model = None
    out_model = None

    def static_quantize(self, model_path: str):
        self.input_model = model_path
        self.out_model = f'quantized_{self.input_model}'
        print('Quantizing...')
        reader = CalibrationDataGen(model=onnx.load(self.input_model))
        quantize_static(
            self.input_model, self.out_model,
            calibration_data_reader=reader,
            quant_format=QuantFormat.QOperator,
            per_channel=True,
            activation_type=QuantType.QUInt8,
            weight_type=QuantType.QUInt8,
            calibrate_method=CalibrationMethod.MinMax,
        )


def main():
    main_class = Main()
    main_class.static_quantize('custom_model.onnx')
if __name__ == '__main__':
    main()
```
Please try it out from the [Archive.zip](https://github.com/microsoft/onnxruntime/files/10946411/Archive.zip)

**Comment by Hrayo712** [comment]
I used your script and it seems to be a version problem. It shows the error on onnxruntime `1.8.1` but works on version >= `1.10` . I'll update. Thanks for the support!
