### ISSUE TITLE
MatMul + Add -> 

### ISSUE THREAD

**Issue by fdwr** [microsoft/onnxruntime#1494]
**Describe the bug**
(performance) ONNX runtime applies an optimization that transforms the graph MatMul + Add -> GEMM for floating point tensors. However, an overly strict type check prevents that same fusion optimization from being applied to float16 tensors, which deprives a noticeable perf improvement in models.

The issue appears to be in [matmul_add_fusion.cc](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/optimizer/matmul_add_fusion.cc), expecting tensors to be only float32:

    if ((*matmul_type) != "tensor(float)" || (*add_type) != "tensor(float)") {
      continue;
    }

When I locally make the change (checking that MatMul and Add use the same tensor type, and that they are either float32 or float16), the fusion occurs with correct output (reaching the GEMM GPU kernel).

**Urgency**
Before Vibranium desired, but not necessary. The results are still correct.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 18874 2019-04-05
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: bf6f19c engine/lotus (v0.1.4-709-gbf6f19c6)
- Python version: NA
- Visual Studio version (if applicable): Visual Studio 2017 15.8.5
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: AMD Radeon, 32GBs system RAM

**To Reproduce**
Run the following reduced model:

    {
      "graph_name": "Gemm via MatMul Add fusion", // It's possible to reach GEMM via graph transformation, fusing MatMul + Add.
      "nodes": [
        {
          "op_type": "MatMul",
          "inputs": [
            "Input0", // [[1, 2, 3], [4, 5, 6]]
            "Input1"  // [[1, 2], [3, 4], [5, 6]]
          ],
          "outputs": ["MatMulOutput"], // [[22, 28], [49, 64]]
        },
        {
          "op_type": "Add",
          "inputs": [
            "MatMulOutput", // [[22, 28], [49, 64]]
            "Input2"        // [[1, 1], [1, 1]]
          ],
          "outputs": ["AddOutput"], // [[23, 29], [50, 65]]
        }
      ],
      "inputs": {
        "Input0": {
          "type": "float16",
          "value": [[1, 2, 3], [4, 5, 6]]
        },
        "Input1": {
          "type": "float16",
          "value": [[1, 2], [3, 4], [5, 6]]
        },
        "Input2": {
          "type": "float16",
          "value": [[1, 1], [1, 1]]
        }
      },
      "outputs": {
        "AddOutput": {
          "type": "float16",
          "value": [[23, 29], [50, 65]]
        }
      }
    }

--------

    ir_version: 3
    producer_name: "OnnxConformanceTest"
    graph {
      node {
        input: "Input0"
        input: "Input1"
        output: "MatMulOutput"
        op_type: "MatMul"
        domain: ""
      }
      node {
        input: "MatMulOutput"
        input: "Input2"
        output: "AddOutput"
        op_type: "Add"
        domain: ""
      }
      initializer {
        dims: 2
        dims: 3
        data_type: FLOAT16
        name: "Input0"
        raw_data: "\000<\000@\000B\000D\000E\000F"
      }
      initializer {
        dims: 3
        dims: 2
        data_type: FLOAT16
        name: "Input1"
        raw_data: "\000<\000@\000B\000D\000E\000F"
      }
      initializer {
        dims: 2
        dims: 2
        data_type: FLOAT16
        name: "Input2"
        raw_data: "\000<\000<\000<\000<"
      }
      input {
        name: "Input0"
        type {
          tensor_type {
            elem_type: FLOAT16
            shape {
              dim {
                dim_value: 2
              }
              dim {
                dim_value: 3
              }
            }
          }
        }
      }
      input {
        name: "Input1"
        type {
          tensor_type {
            elem_type: FLOAT16
            shape {
              dim {
                dim_value: 3
              }
              dim {
                dim_value: 2
              }
            }
          }
        }
      }
      input {
        name: "Input2"
        type {
          tensor_type {
            elem_type: FLOAT16
            shape {
              dim {
                dim_value: 2
              }
              dim {
                dim_value: 2
              }
            }
          }
        }
      }
      output {
        name: "AddOutput"
        type {
          tensor_type {
            elem_type: FLOAT16
            shape {
              dim {
                dim_value: 2
              }
              dim {
                dim_value: 2
              }
            }
          }
        }
      }
    }
    opset_import {
      version: 1
    }
    opset_import {
      version: 7
    }

**Expected behavior**
Fusion MatMul + Add -> GEMM for float16 too.

**Additional context**
This perf issue came from EmotionFerPlus (Emotion_Ferplus_fp16.onnx) and was raised by an external hardware vendor.

**Comment by hariharans29** [comment]
Hi @fdwr ,

This logically makes sense but I am curious as to how your local change went through given that Gemm only seems to support `float` type (and not float16) based on the kernel declaration - https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/math/gemm.cc.

Also notice this comment in the very file that you are referring to -  

// Gemm only support float, so the inputs of MatMul

**Comment by fdwr** [comment]
ONNX runtime supports float16 for many operators (MatMul, Add, GEMM...), but it's not obvious by just looking at the kernel implementation. Rather it's implicitly supported via the cast nodes (whereas on the GPU, DirectML just supports float16 directly without cast nodes).

core\session\inference_session.cc

    common::Status InferenceSession::TransformGraph(onnxruntime::Graph& graph,
                                                    const onnxruntime::GraphTransformerManager& graph_transformer_mgr,
                                                    const ExecutionProviders& providers,
                                                    KernelRegistryManager& kernel_registry_manager,
                                                    const InsertCastTransformer& insert_cast_transformer,
                                                    SessionState& session_state) {
      // The transformer order:
      // 1. built-in graph rewriter
      // 2. each execution provider's transformer
      // 3. do node placement according to kernel definition
      // 4. insert copy nodes
      // 5. insert cast nodes.

So this makes the logic agnostic to execution provider.

**Comment by hariharans29** [comment]
Thanks @fdwr !

**Comment by faxu** [comment]
@fdwr - could you send a PR for this change?

**Comment by fdwr** [comment]
@faxu @hariharans29 : I'm happy to start the PR (which I've locally tested against our ONNX conformance tests and WinML model zoo), but I'll need someone else to usher it through and include whatever new DRT's you want.

**Comment by askhade** [comment]
Closing this issue since this PR has been merged
