### ISSUE TITLE
[Build]  Building onnxruntime with OpenVINO unit tests fail (onnxruntime_test_all and onnxruntime_shared_lib_test). 

### ISSUE THREAD

**Issue by cyrusbehr** [microsoft/onnxruntime#14947]
### Describe the issue

I start by downloading OpenVINO 2202.3 Runtime for Ubuntu 20.04 [here](https://storage.openvinotoolkit.org/repositories/openvino/packages/2022.3/linux). Next, I source the `setupvars.sh`.
Next, I run the below build script. 
The library builds ok, but then the following two unit tests fail.

```
The following tests FAILED:
	  1 - onnxruntime_test_all (Failed)
	  4 - onnxruntime_shared_lib_test (Failed)

```

### Urgency

standard

### Target platform

Ubuntu 20.04.5 LTS, 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz

### Build script

```
test -e onnxruntime || git clone --recursive https://github.com/Microsoft/onnxruntime
cd onnxruntime
git checkout v1.14.1
git reset HEAD --hard
git submodule update --recursive


./build.sh --config Release --parallel --build_shared_lib --use_openvino CPU_FP32

```

### Error / output

[CTestCostData.txt](https://github.com/microsoft/onnxruntime/files/10914259/CTestCostData.txt)
[LastTest.log](https://github.com/microsoft/onnxruntime/files/10914260/LastTest.log)
[LastTestsFailed.log](https://github.com/microsoft/onnxruntime/files/10914261/LastTestsFailed.log)

### Visual Studio Version

Not using visual studio 

### GCC / Compiler Version

gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**Comment by cyrusbehr** [comment]
I got v1.13.1 of onnxruntime to work with OpenVINO 2022.2, so I guess the combination I was trying is not yet supported. Any ideas of when v1.14 will support OpenVINO? I tried v1.14 with 2022.2 and that didn't work either.

**Comment by sfatimar** [comment]
Please update if the issue is still open
