### ISSUE TITLE
Unrecognized attribute: axes for operator ReduceSum for 1.14.1

### ISSUE THREAD

**Issue by yuwenzho** [microsoft/onnxruntime#14959]
### Describe the issue

For onnxruntime1.14.1, optimized model generated from `optimizer.optimize_model` function will cause the following error in InferenceSession.  This error will not occur if onnxruntime is downgraded to 1.13.1.

`onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from bert.opt.onnx failed:This is an invalid model. In Node, ("MaskReduceSum_0", ReduceSum, "", -1) : ("input_mask_int32": tensor(int32),) -> ("mask_index_0",) , Error Unrecognized attribute: axes for operator ReduceSum`

### To reproduce

1. export onnx model
```python
import onnxruntime
import torch
from transformers import BertForSequenceClassification

def export_onnx_model(model, onnx_model_path):
    with torch.no_grad():
        inputs = {'input_ids':      torch.ones(1,128, dtype=torch.int64),
                    'attention_mask': torch.ones(1,128, dtype=torch.int64),
                    'token_type_ids': torch.ones(1,128, dtype=torch.int64)}
        outputs = model(**inputs)

        symbolic_names = {0: 'batch_size', 1: 'max_seq_len'}
        torch.onnx.export(model,                                            # model being run
                    (inputs['input_ids'],                             # model input (or a tuple for multiple inputs)
                    inputs['attention_mask'], 
                    inputs['token_type_ids']),                                         # model input (or a tuple for multiple inputs)
                    onnx_model_path,                                # where to save the model (can be a file or file-like object)
                    do_constant_folding=True,                         # whether to execute constant folding for optimization
                    input_names=['input_ids',                         # the model's input names
                                'input_mask', 
                                'segment_ids'],
                    output_names=['output'],                    # the model's output names
                    dynamic_axes={'input_ids': symbolic_names,        # variable length axes
                                'input_mask' : symbolic_names,
                                'segment_ids' : symbolic_names})
        print("ONNX Model exported to {0}".format(onnx_model_path))

model = BertForSequenceClassification.from_pretrained('Intel/bert-base-uncased-mrpc')
export_onnx_model(model, "bert.onnx")
```

2. optimize model
```python
import onnx
import onnxruntime
from onnxruntime.transformers import optimizer
from onnxruntime.transformers.fusion_options import FusionOptions
opt_options = FusionOptions('bert')
opt_options.enable_embed_layer_norm = False

model_optimizer = optimizer.optimize_model(
    'bert.onnx',
    'bert',
    num_heads=12,
    hidden_size=768,
    optimization_options=opt_options)
model_optimizer.save_model_to_file('bert.opt.onnx')
sess_options = onnxruntime.SessionOptions()
sess = onnxruntime.InferenceSession('bert.opt.onnx', sess_options)
```

3. other package version:
onnx                     1.13.1
torch                    1.13.1
transformers             4.26.1

### Urgency

There is a regression in ONNX Runtime functionality.

### Platform

Linux

### OS Version

Linux mlt2-clx105 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
The definition of ReduceSum changed in ONNX opset 13 to move the `axes` from being a static attribute to a runtime input. 

Based on the error I would guess this line needs updating to adjust to the new ReduceSum spec.

https://github.com/microsoft/onnxruntime/blob/538d64891ac8e43c1faf7846635c3a1bf7b6b6c5/onnxruntime/python/tools/transformers/fusion_attention.py#L78

There are probably other places using reduction ops that need an update. 

@tianleiwu or @wangyems would you be able to take a look?

What opset is the model being exported from pytorch with? Short term it might be possible to workaround the issue by explictly specifying opset 12 in the torch.onnx.export call.

**Comment by tianleiwu** [comment]
It is a known issue. I will provide a fix soon.

**Comment by datinje** [comment]
Hi , there may be a similar issue when exporting a model with pytorch 2.0 with ONNX opset18 (while it works with opset17).
Cf
/usr/local/lib/python3.10/dist-packages/torch/onnx/symbolic_opset9.py:5589: UserWarning: Exporting aten::index operator of advanced indexing in opset 18 is achieved by combination of   multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  warnings.warn(
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1636, in _export
    _C._check_onnx_proto(proto)
RuntimeError: Unrecognized attribute: axes for operator ReduceMax

==> Context: Bad node spec for node. Name: /model/ReduceMax OpType: ReduceMax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cad-engine/export_onnx.py", line 359, in <module>
    main()
  File "/cad-engine/export_onnx.py", line 332, in main
    onnx_model = export_tracing(torch_model, sample_inputs, args, logger)
  File "/cad-engine/export_onnx.py", line 115, in export_tracing
    torch.onnx.export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/usr/local/lib/python3.10/dist-packages/torch/onnx/utils.py", line 1638, in _export
    raise errors.CheckerError(e) from e
torch.onnx.errors.CheckerError: Unrecognized attribute: axes for operator ReduceMax

==> Context: Bad node spec for node. Name: /model/ReduceMax OpType: ReduceMax

**Comment by skottmckay** [comment]
@datinje seems like the same underlying issue that the ONNX spec changed, but torch.onnx.export is a different tool so you're better off adding this as an issue in [the pytorch github repo](https://github.com/pytorch/pytorch). The original issue was due to one of the tools in the onnxruntime github repo needing updating.

**Comment by datinje** [comment]
@skottmckay  : thanx for the answer . It confirms there may be an issue with Pytroch 2.0 torch.onnx.export with onnx opset18. I will try to precise the issue in pytroch github repo.
