### ISSUE TITLE
OrtGetWinMLAdapter

### ISSUE THREAD

**Issue by shelllet** [microsoft/onnxruntime#14954]
### Describe the issue

model = LearningModel::LoadFromFilePath(path); // crash

crash here:
![image](https://user-images.githubusercontent.com/16729017/223609484-1d640ab9-0e36-40f2-90cb-5de6b6428f97.png)

C:\__w\1\s\winml\lib\Api.Ort\OnnxruntimeEnvironment.cpp(71)\Microsoft.AI.MachineLearning.dll!00007FFAD693FC80: (caller: 00007FFAD6936E07) FailFast(1)

![image](https://user-images.githubusercontent.com/16729017/223609649-133072f4-e164-4248-826f-6e9c6ad2de0c.png)

can't not found 'OrtGetWinMLAdapter' export function.

onnxruntime.dll version:1.13.22.1021
![image](https://user-images.githubusercontent.com/16729017/223611010-6d52278b-f323-47be-ab5e-72542f65c0c4.png)

onnxruntime.dll version 1.14.23.224, there is no `OrtGetWinMLAdapter` export function
![image](https://user-images.githubusercontent.com/16729017/223611558-2f6e1a27-49fd-491c-88aa-8b70cf41ac59.png)

### To reproduce

1. NuGet\Install-Package Microsoft.ML.OnnxRuntime -Version 1.14.1, like this:

![image](https://user-images.githubusercontent.com/16729017/223611285-204451de-f873-4866-be61-9c5b95f7bb88.png)

2. call LearningModel::LoadFromFilePath(path)

### Platform

Windows

### OS Version

windows 10 21H2

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1..14.23.224

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by smk2007** [comment]
Hi it appears that you have both the Microsoft.AI.MachineLearning NuGet package as well as the Microsoft.ML.Onnxruntime package installed at the same time.

The Microsoft.ML.Onnxruntime package is not built with support for WinML, so it should not be installed when trying to use WinML.

Please just install the Microsoft.AI.MachineLearning package, and the correct version of onnxruntime.dll with the appropriate exports will be binplaced for you.

**Comment by shelllet** [comment]
@smk2007 ☕ . thks, this solved my problem.
