### ISSUE TITLE
[Build] Detect mac and install onnxruntime otherwise onnxruntime-gpu

### ISSUE THREAD

**Issue by seanmcb-smarsh** [microsoft/onnxruntime#14961]
### Describe the issue

I have a python library in which I specify onnxruntime-gpu as the dependency in setup.py.

My python library is built and published to a pypi repo.

My python library is then used as a dependency in another python application and is specified in its setup.py

When I `pip install` on my python app in a linux environment all the dependencies get installed ok, but I also need to be able to do development on a Mac, and `pip install` fails due to `onnxruntime-gpu` not being supported on Mac.

```
Collecting onnxruntime-gpu==1.13.1
  Could not find a version that satisfies the requirement onnxruntime-gpu==1.13.1 (from versions: )
No matching distribution found for onnxruntime-gpu==1.13.1
```

I know for Macs I should be using `onnxruntime`, not `onnxruntime-gpu`.

How can I make the python library wheel smart enough to detect it is being installed on a Mac and install `onnxruntime` otherwise install `onnxruntime-gpu` when being installed? Or is there alternative onnxruntime dependency that can do this for me?

### Target platform

Mac and linux

### Build script

`pip install` with setup.py

### Error / output

```
Collecting onnxruntime-gpu==1.13.1
  Could not find a version that satisfies the requirement onnxruntime-gpu==1.13.1 (from versions: )
No matching distribution found for onnxruntime-gpu==1.13.1
```

**Comment by snnn** [comment]
Sorry, I'm afraid I don't have a good answer for it.

**Comment by seanmcb-smarsh** [comment]
Using environment markers solved the issue: https://peps.python.org/pep-0496/

```
    f'onnxruntime; sys_platform == "darwin"',
    f'onnxruntimegpu; sys_platform == "linux"',
```

Closing
