### ISSUE TITLE
[Web] ONNX model gives different outputs when run in python vs javascript, Using same model and passing same input

### ISSUE THREAD

**Issue by mohitLb** [microsoft/onnxruntime#14995]
### Describe the issue

I am getting issue in running [silero models](https://github.com/snakers4/silero-models) in JavaScript.
It is giving right output in python but in the case of JavaScript the result is different and unable to decode the result. 

sample: ["https://models.silero.ai/examples/en_sample.wav"](https://models.silero.ai/examples/en_sample.wav)
labels for decorder : ["https://models.silero.ai/models/en/en_v1_labels.json"](https://models.silero.ai/models/en/en_v1_labels.json)
Onnx Model : ["https://models.silero.ai/models/en/en_v5.onnx"](https://models.silero.ai/models/en/en_v5.onnx)

I'm referring this repo to run silero stt model in the web : ["https://github.com/AliceCyber/silero-stt-demo"](https://github.com/AliceCyber/silero-stt-demo)

### To reproduce

sample: ["https://models.silero.ai/examples/en_sample.wav"](https://models.silero.ai/examples/en_sample.wav)
labels for decorder : ["https://models.silero.ai/models/en/en_v1_labels.json"](https://models.silero.ai/models/en/en_v1_labels.json)
Onnx Model : ["https://models.silero.ai/models/en/en_v5.onnx"](https://models.silero.ai/models/en/en_v5.onnx)

I'm referring this repo to run silero stt model in the web : ["https://github.com/AliceCyber/silero-stt-demo"](https://github.com/AliceCyber/silero-stt-demo)

Silero models repo : ["https://github.com/snakers4/silero-models"](https://github.com/snakers4/silero-models)

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.0

### Execution Provider

WASM, Other / Unknown

**Comment by skottmckay** [comment]
Not clear what exactly you are doing without step by step repro instructions. Could you please provide?

Most of the source in that repo is minified so it's hard to see what is being used. Have you asked the author of the repo you're using if they have seen any issues?  

Have you verified the input in js is exactly the same as the input used in python?

The javascript and python bindings are thin layers that are just providing input/receiving output from executing the nodes in the model using the same native code, so issues with different results are usually be traced back to differences in the input.

**Comment by mohitLb** [comment]
Hi @skottmckay 

Please take a look on this repo which I created : [https://github.com/mohitLb/silero-stt-web](https://github.com/mohitLb/silero-stt-web)

In this repo there are two different versions one is for web and another one is for python ["silero-stt-python"](https://github.com/mohitLb/silero-stt-web/tree/main/silero-stt-python).

In this [repo](https://github.com/AliceCyber/silero-stt-demo) author is using *onnx.js* not *onnxruntime-web*.

Yes, I have verified that input in web is exactly same as the input used in python. But the output in both versions is different.

Please let me know if anything else will be require from my side.

Thanks!

**Comment by skottmckay** [comment]
What steps did you take to validate the input was exactly the same for each? Ideally you'd do something like save the bytes from the input generated by the python code and use those as input in the javascript code. 

It looks like different components are used to resample the input (AudioContext vs. torchaudio) so with floating point numbers being involved some small differences would be expected. That shouldn't significantly affect the output though.

**Comment by skottmckay** [comment]
Small differences are expected and probably unavoidable. Depends on the sequence of floating point operations and the assembly instructions used to do the calculations. That's completely normal, and using something other than torchaudio is unlikely to make them go away.

Those small differences generally shouldn't change the overall predictions made by the model if it has a high level of accuracy. 

If you feed in the same pre-processed input values from python and javascript do you see the same output from onnxruntime? Ideally that pre-processed input is saved/loaded as a chunk of bytes and used directly so there's no conversion logic that could affect things.

**Comment by mohitLb** [comment]
@skottmckay 
Thanks for your input !

It seems there is issue with javascript audioContext functionality which is down sampling the audio file. Because onnx runtime works fine with the preprocessed output from python side. There is small variation in output but that is fine. 

Do you know any down sampling api or library at javascript front end which works similar to python torchaudio??

Thanks

**Comment by fs-eire** [comment]
the web uses audio API just like demonstrated in https://github.com/mohitLb/silero-stt-web/blob/main/main.js. you can specify the sample rate in the options when creating AudioContext instance. see https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/AudioContext

**Comment by mohitLb** [comment]
@fs-eire 
I have tried Web Audio API [Audiocontext](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/AudioContext) But the preprocessed data is not matching with pytorch audio's preprocessed data.
I am unable to get right predictions.

**Comment by shalvamist** [comment]
Hi mohitLb,

Not sure if it will be helpful but have you tried using 'OfflineAudioContext' for resampling ?
I found this to generate correct results for down sampling audio files - 
```
// Pad, Trim & resample the incoming signal
let offlineCtx = new OfflineAudioContext(NUMBER_CHANNELS, N_SAMPLES, TARGET_SAMPLE_RATE);
let offlineSource = offlineCtx.createBufferSource();
offlineSource.connect(offlineCtx.destination);
offlineSource.buffer = audioData;
offlineSource.start();
let resampled = await offlineCtx.startRendering().then((resampled) => {
    return resampled;
});
offlineSource.stop();
```

Hope it helps

**Comment by mohitLb** [comment]
Hi @shalvamist ,

Thanks for your inputs!!!
After integrating your code the model is working fine and now It is giving correct predictions.
