### ISSUE TITLE
[WEIRD inference result] 

### ISSUE THREAD

**Issue by phelogges** [microsoft/onnxruntime#15009]
### Describe the issue

i got a onnx model, use python and onnxruntime cpp to inference this model.
On windows11, python gave an expected result, but on cpp, debug mode gave same result but unexpected, release mode somethimes gave expected result, sometimes gave different unexpected results,
i don't know why

### To reproduce

Windows11
VS2019 amd64
onnxruntime 1.11.0 (both py lib from pypi and [cpp lib](https://github.com/microsoft/onnxruntime/releases/download/v1.11.0/onnxruntime-win-x64-1.11.0.zip))
backend cpu

some results:
python (expected)
![image](https://user-images.githubusercontent.com/31875260/224484170-63b9d95f-76dd-44bf-ae0c-abb055352ec1.png)

cpp debug (unexpected but fixed)
![@ SQP$BR3Q{%E)1 PHL2P`B](https://user-images.githubusercontent.com/31875260/224484202-182751dd-beae-4e41-b47d-be5f6eb50e19.jpg)

cpp release1 (expected)
![R8MO7KO81H${ YKW$X`A2 7](https://user-images.githubusercontent.com/31875260/224484213-76b41484-9aa0-40cf-941d-f4c404fd0ac3.jpg)

cpp release others (unexpected)
![@{73D JJ7)QG9FITYFL{I(6](https://user-images.githubusercontent.com/31875260/224484229-37743993-c5b3-4ec1-8638-50138f8b5180.jpg)
![%9J(NN)3TZ~86` @T3H7($D](https://user-images.githubusercontent.com/31875260/224484236-9f63383d-7bde-43dc-9b6a-f8407c524562.jpg)
![R L((}XC@6)PU$U{XGTWYBV](https://user-images.githubusercontent.com/31875260/224484241-05f6b697-3cbc-47c5-ade8-5f8bf2d84362.jpg)

python inference code:
```
import numpy as np
import onnxruntime

import argparse

if __name__ == "__main__":
    parser =argparse.ArgumentParser()
    parser.add_argument("model_path", type=str)
    args = parser.parse_args()

    model_path = args.model_path
    sess = onnxruntime.InferenceSession(model_path)
    shape=(1, 3, 224, 224)
    arr = np.ones(shape=shape).astype(np.float32) * 0.5

    loops = 10
    for i in range(loops):
        print(sess.run(None, {sess.get_inputs()[0].name: arr}))
```

cpp inference code
```

#include <vector>

#include <onnxruntime_cxx_api.h>

void infer(const char* model_path) {
    auto env_ = new Ort::Env(ORT_LOGGING_LEVEL_ERROR);
    auto options_ = Ort::SessionOptions();
    options_.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);

    const size_t s = strlen(model_path) + 1;
    auto *wc = new wchar_t[s];
    mbstowcs(wc, model_path, s);
    auto session_ = new Ort::Session(*env_, wc, options_);
    delete[] wc;

    std::vector<char *> input_names_;
    std::vector<char *> output_names_;

    Ort::AllocatorWithDefaultOptions allocator;
    int input_count = session_->GetInputCount();
    for (int i = 0; i < input_count; ++i) {
        input_names_.push_back(session_->GetInputName(i, allocator));
    }

    int output_count = session_->GetOutputCount();
    for (int i = 0; i < output_count; ++i) {
        output_names_.push_back(session_->GetOutputName(i, allocator));
    }

    std::vector<int64_t> shape = {1, 3, 224, 224};
    int size = 3 * 224 * 224;
    auto chw = new float[size];
    for (int i = 0; i < size; ++i) {
        chw[i] = 0.5f;
    }

    auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
    auto input_tensor = Ort::Value::CreateTensor<float>(memory_info, chw, size, shape.data(), 4);
    delete[] chw;

    // shape [1, 4]
    auto output_tensor = session_->Run(Ort::RunOptions(),
                                       input_names_.data(), &input_tensor, 1,
                                       output_names_.data(), output_names_.size());

    fprintf(stdout, "vec len: %d\n", output_tensor.size());

    for (int i=0; i<4; ++i) {
        fprintf(stdout, "%f ", output_tensor[0].At<float>({0, i}));
    }
    fprintf(stdout, "\n");


    delete session_;
    delete env_;
}

int main(int argc, char* argv[]) {
    const char *model_path = argv[1];

    const int loops = 10;
    for (int i=0; i<loops; ++i) {
        infer(model_path);
    }

    return 0;
}
```

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.11.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Execution Provider Library Version

onnxruntime 1.11.0

### Model File

[mobilenetv3l_0311.zip](https://github.com/microsoft/onnxruntime/files/10948513/mobilenetv3l_0311.zip)

### Is this a quantized model?

No

**Comment by skottmckay** [comment]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/979079/224595946-3715228c-50a3-462c-8b87-968f52703bd2.png">


<img width="769" alt="image" src="https://user-images.githubusercontent.com/979079/224595675-d225099f-e7df-43b8-ad29-41adb4467f22.png">

I believe the issue is that you're deleting the buffer used for the input prior to running the model.

```
    auto input_tensor = Ort::Value::CreateTensor<float>(memory_info, chw, size, shape.data(), 4);
    delete[] chw;

    // shape [1, 4]
    auto output_tensor = session_->Run(Ort::RunOptions(),
                                       input_names_.data(), &input_tensor, 1,
                                       output_names_.data(), output_names_.size());
```

**Comment by phelogges** [comment]
> <img alt="image" width="516" src="https://user-images.githubusercontent.com/979079/224595946-3715228c-50a3-462c-8b87-968f52703bd2.png">
> 
> <img alt="image" width="769" src="https://user-images.githubusercontent.com/979079/224595675-d225099f-e7df-43b8-ad29-41adb4467f22.png">
> 
> I believe the issue is that you're deleting the buffer used for the input prior to running the model.
> 
> ```
>     auto input_tensor = Ort::Value::CreateTensor<float>(memory_info, chw, size, shape.data(), 4);
>     delete[] chw;
> 
>     // shape [1, 4]
>     auto output_tensor = session_->Run(Ort::RunOptions(),
>                                        input_names_.data(), &input_tensor, 1,
>                                        output_names_.data(), output_names_.size());
> ```

you are right, issue solved by keeping buffer before inference. i didn't read this api detail, i thought Tensor was created by copy buffer data so released it immediately after Tensor created.
