### ISSUE TITLE
Is there an example of dynamic batch?

### ISSUE THREAD

**Issue by qing-shang** [microsoft/onnxruntime#15014]
### Describe the issue

python dynamic batch processing will, but it will not change to c++. i need an example

### To reproduce

no problem

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.12.0

### ONNX Runtime API

C++

### Architecture

X86

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
Sorry - not clear what you're asking. Could you please clarify?

If the input to the model has a symbolic value for the batch size, the input data provided at runtime can have one or more batches. For example, this model has a single input with a symbolic value called `batch_size` for dim 0. The other 3 dimensions have fixed sizes or 1, 224 and 224 respectively so the input data must match those exactly.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/979079/224594509-bc5bcf8f-735e-427d-a105-ea8f22a4d838.png">

You could execute this model with any value >= 1 as the batch size. e.g. {1, 1, 224, 224} for a single item in the batch, or {5, 1, 224, 224} for 5 items in the batch.

This is determined by the model and not by whether the model is executed from python or C++ or any other language bindings.

**Comment by qing-shang** [comment]
> 对不起 - 不清楚你在问什么。你能澄清一下吗？
> 
> 如果模型的输入具有批大小的符号值，则运行时提供的输入数据可以有一个或多个批。例如，此模型具有单个输入，其符号值称为 dim 0。其他 3 个维度具有固定大小或分别为 1、224 和 224，因此输入数据必须与这些大小完全匹配。`batch_size`
> 
> <img alt="image" width="409" src="https://user-images.githubusercontent.com/979079/224594509-bc5bcf8f-735e-427d-a105-ea8f22a4d838.png">
> 
> 您可以使用任何值 >= 1 作为批大小来执行此模型。例如，{1， 1， 224， 224} 表示批次中的单个项目，或 {5， 1， 224， 224} 表示批次中的 5 个项目。
> 
> 这是由模型决定的，而不是由模型是从 python 还是C++或任何其他语言绑定执行的。

how to submit multiple batch inputs and outputs in C++? can you provide examples
![20230313185608](https://user-images.githubusercontent.com/61321831/224682685-da143284-c759-4622-94f5-a9f25f2407b2.jpg)

**Comment by skottmckay** [comment]
The number of items in the batch determines the shape of the input. Call Ort::Value::CreateTensor to create the input.

https://onnxruntime.ai/docs/api/c/struct_ort_1_1_value.html#a3898146b5fc35b838bd48db807dd6c8e

In your example each item in the batch is 3 x 64 x 64, so the input shape will be { batch_size, 1, 3, 64, 64 } and the shape_len will be 4. 

If for example the batch has 4 items the shape will be { 4, 3, 64, 64 } and the buffer size for the input will be 4 x 3 x 64 x 64. Each input is written to the buffer sequentially.

You can call CreateTensor with an existing buffer, or it can create the buffer and you can write your input data to that. 

See https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/test/shared_lib/test_inference.cc for examples of CreateTensor usage.

**Comment by qing-shang** [comment]
> 

I'll try it, but it was wrong except for the first result. Is it wrong to create it
![20230313200908](https://user-images.githubusercontent.com/61321831/224697942-228f6713-810d-4372-a079-3283551617b1.jpg)

**Comment by skottmckay** [comment]
Your memcpy looks incorrect as it doesn't take into account which item in the batch you're processing.

**Comment by qing-shang** [comment]
> Your memcpy looks incorrect as it doesn't take into account which item in the batch you're processing. 

can you write an example for me?

**Comment by wejoncy** [comment]
![image](https://user-images.githubusercontent.com/9417365/224900587-562100a3-c728-4dc0-974e-114a392fd4b2.png)
you should give a batch_offset, such as "batch_idx*target_channel*target_height*target_width", Otherwise, you are always copying the data in the first batch.

**Comment by qing-shang** [comment]
> ![image](https://user-images.githubusercontent.com/9417365/224900587-562100a3-c728-4dc0-974e-114a392fd4b2.png) you should give a batch_offset, such as `batch_idx*target_channel*target_height*target_width`, Otherwise, you are always copying the data into the first batch.

thanks, i've fixed the problem.
