### ISSUE TITLE
[Performance] RunWithBinding stuck when run from multiple threads

### ISSUE THREAD

**Issue by idruker-cerence** [microsoft/onnxruntime#15022]
### Describe the issue

**The observed behavior**

Two threads run in parallel the same sequence of calls of onnxruntime functions. Each thread creates a separate session and uses its own data set.

```
    ....
    size_t inputCount;
    api->SessionGetInputCount(session, &inputCount);

    size_t outputCount;
    api->SessionGetOutputCount(session, &outputCount);

    OrtIoBinding* iobinding;
    api->CreateIoBinding(session, &iobinding);

    OrtMemoryInfo* memoryInfo;
    api->CreateCpuMemoryInfo(OrtAllocatorType::OrtArenaAllocator, OrtMemType::OrtMemTypeDefault, &memoryInfo);

    // bind input tensor values to ort values
    vector<OrtValue*> inputOrts(inputs.size());
    for(int i=0; i<inputs.size(); ++i) {
        vector<int64_t> shape = {....};
        api->CreateTensorWithDataAsOrtValue(
            memoryInfo,
            (float*)inputs[i].data(),
            inputs[i].size()*sizeof(float),
            shape.data(),
            shape.size(),
            ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,
            &inputOrts[i]);
        api->BindInput(iobinding, "input-name", inputOrts[i]);
    }

    vector<OrtValue*> outputOrts(outputs.size());
    for(int i=0; i<outputs.size(); ++i) {
        vector<int64_t> shape = {.....};

        outputs[i].resize(/* allocate size*/);

        api->CreateTensorWithDataAsOrtValue(
            memoryInfo,
            (float*)outputs[i].data(),
            outputs[i].size()*sizeof(float),
            shape.data(),
            shape.size(),
            ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,
            &outputOrts[i]));

         api->BindOutput(iobinding, "output-name", outputOrts[i]));
     }
    // run the model
    OrtRunOptions* options;
    api->CreateRunOptions(&options);
    api->RunWithBinding(session, options, iobinding);

    ...
```

One thread successfully completes while another **gets stuck forever in api->RunWithBinding(..)**

**Side information**
We have multiple machines and various platforms. The issue occurs only on one machine and only on Linux i86_64 platform

**Question**
Is there anything wrong with the code? Is there any limitation on running onnxruntime with multiple threads? 

### To reproduce

It's only reproducible in our environment. I can't point to anything special about it. The issue is **not** observed on other machines or other platforms.  

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.10.0

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

### Is this a quantized model?

No

**Comment by skottmckay** [comment]
>          api->BindOutput(iobinding, "output-name", outputOrts[i]));

Is this example code and in the 'real' implementation the actual output name is used?

Are you able to attach and see where exactly within RunBinding it's stuck? There are no locks in the RunWithBinding implementation. That calls InferenceSession::Run which is designed to be stateless. The IOBinding class also has no locks. Given all that it's not obvious where it could get stuck. 

Do you see the same issue with the latest version of ORT 1.14?

Is there a need to use IOBinding? If input/output is on CPU I wouldn't have expected that to be necessary.

**Comment by idruker-cerence** [comment]
Hi Scott

Well, the actual name is different (I changed it for this example only) but it's the same as in the model.  

Thanks for the information about RunBinding. That confirms my expectation that the stuff must be thread safe. Maybe I'll try to dig in code. 

We'll soon move to v1.13.1 - I'll see then if the issue is gone.
