### ISSUE TITLE
[Feature Request] load external data/weights from a byte buffer

### ISSUE THREAD

**Issue by ssube** [microsoft/onnxruntime#15024]
### Describe the feature request

I would like to modify and then load ONNX models entirely in memory, without writing them to disk, for models > 2GB - like the Stable Diffusion UNet and LoRA weights (https://github.com/ssube/onnx-web/issues/213).

The following works great for writing the model to disk:

```python
convert_model_to_external_data(
    base_model,
    all_tensors_to_one_file=True,
    location=f"lora-{dest_type}-external.pb",
)
bare_model = write_external_data_tensors(base_model, dest_path)

dest_file = path.join(dest_path, f"lora-{dest_type}.onnx")
with open(dest_file, "wb") as model_file:
    model_file.write(bare_model.SerializeToString())
```

Calling `base_model.SerializeToString()` fails because the model is > the 2GB protobuf limit, so I cannot get a single `bytes` object with the entire model in it.

I can implement a custom version of `write_external_data_tensors` that writes the external data to a `bytearray` or `BytesIO` object (a mutable byte buffer), but as far as I can tell, `InferenceSession()` does not have a way to load the external data from a buffer like that.

I'm looking at the Python API, but if that option is available in the C++, I can start a PR. This does not seem like it could be a security issue, since there is no filesystem/network access. I'm not sure what the ONNX spec says about this behavior, but it would be great for testing as well - writing 3GB+ scratch files during CI is not super fast either.

This was requested in https://github.com/microsoft/onnxruntime/issues/14815#issuecomment-1461522616 as well.

### Describe scenario use case

When calling `onnxruntime.InferenceSession()`, add a parameter like `external_data_bytes`:

```python
data_buffer = BytesIO()
convert_model_to_external_data(
    base_model,
    all_tensors_to_one_file=True,
    location="lora-unet-external.pb",
)
bare_model = custom_write_external_data_tensors_to_buffer(base_model, data_buffer)
model_bytes = bare_model.SerializeToString()

data_buffer.seek(0)
sess = onnxruntime.InferenceSession(model_bytes, external_data_bytes=data_buffer, providers=["CPUExecutionProvider"])
```

**Comment by pranavsharma** [comment]
A C API for this already exists. Does this work for you? https://github.com/microsoft/onnxruntime/blob/c6074f3a4b09cb44b46ca4422717deb067015bfa/include/onnxruntime/core/session/onnxruntime_c_api.h#L3399-L3401

**Comment by ssube** [comment]
I think that could work, but I'm currently working in Python. Is that function exposed in the C binding module at all (I've been looking, but have not found it)? If not, would that be a good PR?

**Comment by ssube** [comment]
Thanks, that works. I have been able to build and run models without ever writing them to disk, which is excellent, but there is one part I'm not sure about. I wrote a function to convert the initializers with external data to bytes:

```python
def buffer_external_data_tensors(model: ModelProto) -> Tuple[ModelProto, List[Tuple[str, OrtValue]]]:
    external_data = []
    for tensor in model.graph.initializer:
        name = tensor.name

        logger.info("externalizing tensor: %s", name)
        if tensor.HasField("raw_data"):
            npt = numpy_helper.to_array(tensor)
            orv = OrtValue.ortvalue_from_numpy(npt)
            external_data.append((name, orv))
            # mimic set_external_data
            set_external_data(tensor, location="foo.bin")
            tensor.name = name
            tensor.ClearField("raw_data")

    return (model, external_data)
```

but that conversion through numpy is not ideal: `OrtValue.ortvalue_from_numpy(numpy_helper.to_array(tensor))`.

Is there a way I can create an `OrtValue` directly from the `TensorProto`? It looks like that used to exist, but might have been removed: https://github.com/microsoft/onnxruntime/issues/1640#issuecomment-522196462 . 

This method only takes a few seconds on a 3GB model (SD v1.5 Unet), so that's still pretty good.
