### ISSUE TITLE
ORT fails on unused input in a function

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxruntime#15046]
### Describe the issue

In the example below, `self` was not used in the function, and ORT complains with `failed validating the check: !(it.GetName().empty())` (https://github.com/microsoft/onnxruntime/discussions/13278)

```python
import onnxscript

@onnxscrpt.script()
def aten_copy(
    self: TTensor, src: TTensor, non_blocking: bool = False  # pylint: disable=unused-argument
) -> TTensor:
    """copy(Tensor self, Tensor src, bool non_blocking=False) -> Tensor"""

    self = op.Identity(src)
    return self
```

### To reproduce

Any function with unused inputs

### Platform

Linux

### OS Version

N/A

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
This seems like it's either an onnxscript issue or an onnx issue given the error comes from onnx code here: https://github.com/onnx/onnx/blob/a1a07538126649528486e0afce8d6f9a6923d5b5/onnx/defs/schema.cc#L965-L971

Is there a change you think could be made in onnxruntime?

**Comment by justinchuby** [comment]
When an input in the function is unused, I assume it would still have a name but simply get ignored? Would it be reasonable to expect ort to proceed without errors?

**Comment by justinchuby** [comment]
Ok I see what you are referring to. It does seem like an ONNX error.

**Comment by justinchuby** [comment]
I moved the issue to onnx instead. Thanks Scott!

**Comment by gramalingam** [comment]
I do think it is a problem in onnxruntime. Specifically, it [creates a schema for the function](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/graph/function_utils.cc#L251) and does not seem to handle this corner case ... it is creating a schema with an empty input name.

**Comment by skottmckay** [comment]
@gramalingam is it expected that someone would create an onnx::FunctionProto with an empty input name? 

We could update the ORT code to skip those inputs, but isn't that just masking a misuse issue and maybe the user made a mistake by having an empty input name? e.g. what if input 2 out of 3 has an empty name? does input 3 now move to input 2 or do we have to create a fake name?

**Comment by justinchuby** [comment]
There is one example in the issue. To match the aten signature we take self as the first input. But it is not used in the function

**Comment by justinchuby** [comment]
@gramalingam i wonder if the name was dropped during the translation process in onnxscript. I will experiment more

**Comment by gramalingam** [comment]
It is ORT code that creates this erroneous input. Specifically, ORT internally depends on creating a schema for all model-local functions. To do this, it creates type-constraints for all inputs of the function: for any input X, this logic looks at where X is used inside the function-body to figure out an appropriate type-constraint for X.

So, this logic ends up assuming that every input X will be used somewhere within the function-body. When this is not true, it ends up creating an erroneous input with no name in the generated schema.

Please see: https://github.com/microsoft/onnxruntime/pull/15130 for a proposed fix.
