### ISSUE TITLE
[Performance]  Intel HD 520 Card is slow than CPU inference use DirectML.

### ISSUE THREAD

**Issue by yunyaoXYY** [microsoft/onnxruntime#15059]
### Describe the issue
HardWare:
CPU: i5-6300 
GPU: Intel HD 520

Hi, I have a problem when using DirectML on Intel HD 520. Thanks a lot if you could help.

For example, there is an inference program, consists of 3 stage: CPU_preprocess + DML_GPU_Infer + CPU_PostProcess.

I did 2 tests, case A and Case B.

![image](https://user-images.githubusercontent.com/109218879/225320705-ca8f86ef-3872-4270-9844-b3eda06c3a87.png)

In Case A, I found the GPU usage is 95% and avg Inference times is about 30ms；
But in Case B， I found the GPU usage is 40% and inference time is about 60ms；

what's more, When I use CPU to inference my model, the inference time is about 40ms in Case B,  means the GPU is slow than CPU; 

Question：
Is this a correct or reasonable phenomenon ?  
If I want to improve the performance of GPU on Case B ( make it faster, close to Case A, or faster than CPU ) , any suggestions?  Thanks A lot !

### To reproduce

See details.

### Urgency

High

### Platform

Windows

### OS Version

Win10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

ONNXRuntime DirectML Release 1.12.1

### ONNX Runtime API

C++

### Architecture

X86

### Execution Provider

DirectML

### Is this a quantized model?

No

**Comment by skottmckay** [comment]
Depends on the model and which nodes DML can run. Can you share the model?

Alternatively set the logging severity to VERBOSE and look for 'Node placement' in the output. See https://github.com/microsoft/onnxruntime/issues/15027#issuecomment-1469345053

**Comment by yunyaoXYY** [comment]
> Depends on the model and which nodes DML can run. Can you share the model?
> 
> Alternatively set the logging severity to VERBOSE and look for 'Node placement' in the output. See [#15027 (comment)](https://github.com/microsoft/onnxruntime/issues/15027#issuecomment-1469345053)

Hi， Thanks for your reply. 
I'm sorry the model can not be shared. 

One of my new findings : When I turn the power model from "balance" to "high performance" in the Intel GPU manager, the HD520 is faster than CPU. 
Do you know how to change the GPU power model using C++ code? or other command line ? I want to set that just in my program.

BTW, I will try your way and analysis the output.

**Comment by nums11** [comment]
Closing as stale.
