### ISSUE TITLE
Type Error: Type parameter (T) of Optype (Concat) bound to different types (tensor(bool) and tensor(int64) 

### ISSUE THREAD

**Issue by liudaotan** [microsoft/onnxruntime#15082]
### Describe the issue

Hi:

Background:
I'm trying to convert interactive segmentation model (pytorch) to ONNX,  `torch.onnx.export` goes well while Loading inference session I get an error:  

```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from hrnet18.onnx failed:Type Error: Type parameter (T) of Optype (Concat) bound to different types (tensor(bool) and tensor(int64) in node (Concat_204).
```

### To reproduce

To reproduce:

    torch_model.eval()

    batch_size = 1
    img = torch.randn(batch_size, 4, 256, 256, requires_grad=True)
    coor = torch.randn(1, 2, 3, requires_grad=True)  # the coordinates of points

    x = (img, coor)

    # Export the model
    torch.onnx.export(torch_model,  # model being run
                      x,  # model input (or a tuple for multiple inputs)
                      "hrnet18.onnx",  # where to save the model (can be a file or file-like object)
                      export_params=True,  # store the trained parameter weights inside the model file
                      opset_version=11,  # the ONNX version to export the model to
                      do_constant_folding=True,  # whether to execute constant folding for optimization
                      input_names=['input'],  # the model's input names
                      output_names=['output'],  # the model's output names
                      dynamic_axes={'input': {0: 'batch_size'},  # variable length axes
                                    'output': {0: 'batch_size'}})

    onnx_model = onnx.load("hrnet18.onnx")
    try:
        onnx.checker.check_model(onnx_model)
    except Exception:
        print("Model incorrect")
    else:
        print("Model correct")

Then

    ort_session = onnxruntime.InferenceSession("hrnet18.onnx")

The link of the onnx here https://drive.google.com/file/d/1b1_VESOcyA3HP8TIm2g4VWoXoVQS3xah/view?usp=share_link

### Urgency

This issue is very important, any help or advice would be appreciated. 

### Platform

Linux

### OS Version

Ununtu 20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

onnxruntime-1.14.1

### ONNX Runtime API

Python

### Architecture

X86

### Execution Provider

Default CPU

**Comment by liudaotan** [comment]
@michaelbenayoun @hariharans29 @NielsRogge Would you please help here?

**Comment by kunnalparihar** [comment]
@liudaotan I am having the same issue. how did you solve above issue?
Thanks in advance

**Comment by liudaotan** [comment]
Sorry for the late reply. You can use this site (https://netron.app/) to check the operator that is getting this error. Then find the source code and rewrite the operator using your own method. Hope it helps.

**Comment by liudaotan** [comment]
> @liudaotan I am having the same issue. how did you solve above issue? Thanks in advance

Sorry for the late reply. You can use this site (https://netron.app/) to check the operator that is getting this error. Then find the source code and rewrite the operator using your own method. Hope it helps.
