### ISSUE TITLE
[Build] met build error when building for window

### ISSUE THREAD

**Issue by qing-shang** [microsoft/onnxruntime#15101]
### Describe the issue

met build error when building for window

### Urgency

high

### Target platform

window

### Build script

git clone https://github.com/microsoft/onnxruntime.git

cd onnxruntime

git checkout -b --recursive v1.12.0

git submodule update --init --recursive

build.bat --skip_submodule_sync --parallel --skip_tests --enable_msvc_static_runtime --config Release --cmake_generator "Visual Studio 16 2019"

build.bat --skip_submodule_sync --parallel --skip_tests --enable_msvc_static_runtime --config Release --cmake_generator "Visual Studio 16 2019"

### Error / output

 absl_failure_signal_handler.vcxproj -> E:\env\onnxruntime\build\Windows\Release\external\abseil-cpp\absl\debugging\Re
  lease\absl_failure_signal_handler.lib
MASM : warning A4018: invalid command-line option : /utf-8 [E:\env\onnxruntime\build\Windows\Release\onnxruntime_mlas.v
cxproj]
MASM : warning A4018: invalid command-line option : /sdl [E:\env\onnxruntime\build\Windows\Release\onnxruntime_mlas.vcx
proj]
MASM : warning A4018: invalid command-line option : /wd4251 [E:\env\onnxruntime\build\Windows\Release\onnxruntime_mlas.
vcxproj]
MASM : warning A4018: invalid command-line option : /wd4201 [E:\env\onnxruntime\build\Windows\Release\onnxruntime_mlas.
vcxproj]
MASM : warning A4018: invalid command-line option : /wd5054 [E:\env\onnxruntime\build\Windows\Release\onnxruntime_mlas.
vcxproj]
MASM : warning A4018: invalid command-line option : /w15038 [E:\env\onnxruntime\build\Windows\Release\onnxruntime_mlas.
vcxproj]
MASM : warning A4018: invalid command-line option : /wd6385 [E:\env\onnxruntime\build\Windows\Release\onnxruntime_mlas.
vcxproj]
MASM : warning A4018: invalid command-line option : /wd4127 [E:\env\onnxruntime\build\Windows\Release\onnxruntime_mlas.
vcxproj]
D:\Progarm\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\masm.targets(70,5): err
or MSB3721: 命令“ml64.exe /c /nologo /WX /Fo"onnxruntime_mlas.dir\Release\QgemmU8S8KernelAvx2.obj" /D"WIN32" /D"_WINDOWS"
 /D"CPUINFO_SUPPORTED" /D"EIGEN_HAS_C99_MATH" /D"NDEBUG" /D"GSL_UNENFORCED_ON_CONTRACT_VIOLATION" /D"EIGEN_USE_THREADS"
 /D"PLATFORM_WINDOWS" /D"NOGDI" /D"NOMINMAX" /D"_USE_MATH_DEFINES" /D"_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS" /D"EIGEN
_MPL2_ONLY" /D"EIGEN_HAS_CONSTEXPR" /D"EIGEN_HAS_VARIADIC_TEMPLATES" /D"EIGEN_HAS_CXX11_MATH" /D"EIGEN_HAS_CXX11_ATOMIC
" /D"EIGEN_STRONG_INLINE=inline" /D"WINAPI_FAMILY=100" /D"WINVER=0x0601" /D"_WIN32_WINNT=0x0601" /D"NTDDI_VERSION=0x060
10000" /D"CMAKE_INTDIR="Release"" /I "E:\env\onnxruntime\include\onnxruntime" /I "E:\env\onnxruntime\include\onnxruntim
e\core\session" /I "E:\env\onnxruntime\build\Windows\Release" /I "E:\env\onnxruntime\onnxruntime" /I "E:\env\onnxruntim
e\build\Windows\Release\_deps\abseil_cpp-src" /I "E:\env\onnxruntime\onnxruntime\core\mlas\inc" /I "E:\env\onnxruntime\
onnxruntime\core\mlas\lib" /W3 /errorReport:prompt  /utf-8 /sdl /wd4251 /wd4201 /wd5054 /w15038 /wd6385 /wd4127 /TaE:\e
nv\onnxruntime\onnxruntime\core\mlas\lib\amd64\QgemmU8S8KernelAvx2.asm”已退出，返回代码为 1。 [E:\env\onnxruntime\build\Windows\R
elease\onnxruntime_mlas.vcxproj]
  tml.pb.cc
  absl_random_internal_randen_hwaes_impl.vcxproj -> E:\env\onnxruntime\build\Windows\Release\external\abseil-cpp\absl\r
  andom\Release\absl_random_internal_randen_hwaes_impl.lib
  absl_status.vcxproj -> E:\env\onnxruntime\build\Windows\Release\external\abseil-cpp\absl\status\Release\absl_status.l
  ib
  absl_flags_private_handle_accessor.vcxproj -> E:\env\onnxruntime\build\Windows\Release\external\abseil-cpp\absl\flags
  \Release\absl_flags_private_handle_accessor.lib
  absl_random_internal_randen_hwaes.vcxproj -> E:\env\onnxruntime\build\Windows\Release\external\abseil-cpp\absl\random
  \Release\absl_random_internal_randen_hwaes.lib
  absl_statusor.vcxproj -> E:\env\onnxruntime\build\Windows\Release\external\abseil-cpp\absl\status\Release\absl_status
  or.lib
  onnxruntime_providers.vcxproj -> E:\env\onnxruntime\build\Windows\Release\Release\onnxruntime_providers.lib
  absl_random_internal_randen_slow.vcxproj -> E:\env\onnxruntime\build\Windows\Release\external\abseil-cpp\absl\random\
  Release\absl_random_internal_randen_slow.lib
  absl_flags_config.vcxproj -> E:\env\onnxruntime\build\Windows\Release\external\abseil-cpp\absl\flags\Release\absl_fla
  gs_config.lib
  absl_random_internal_randen.vcxproj -> E:\env\onnxruntime\build\Windows\Release\external\abseil-cpp\absl\random\Relea
  se\absl_random_internal_randen.lib
  absl_flags_internal.vcxproj -> E:\env\onnxruntime\build\Windows\Release\external\abseil-cpp\absl\flags\Release\absl_f
  lags_internal.lib
  absl_flags_reflection.vcxproj -> E:\env\onnxruntime\build\Windows\Release\external\abseil-cpp\absl\flags\Release\absl
  _flags_reflection.lib
  absl_random_internal_pool_urbg.vcxproj -> E:\env\onnxruntime\build\Windows\Release\external\abseil-cpp\absl\random\Re
  lease\absl_random_internal_pool_urbg.lib
  absl_random_seed_sequences.vcxproj -> E:\env\onnxruntime\build\Windows\Release\external\abseil-cpp\absl\random\Releas
  e\absl_random_seed_sequences.lib

### Visual Studio Version

16.11.25

**Comment by snnn** [comment]
Randy, it's your branch.

**Comment by victorsoyvictor** [comment]
I have the same, it looks like onnxruntime_mlas.dir\Release\QgemmU8S8KernelAvx2.obj is not found. When I built the 1.15.1 I don't have that error. Thanks.

**Comment by qing-shang** [comment]
> Randy, it's your branch.

i made a copy error. `git clone -b --recursive v1.12.0`, because I tried other versions and still made the same mistake. i have solved this problem. I will reduce the cmake `3.26 rc6` to `3.24.4`

**Comment by victorsoyvictor** [comment]
> > Randy, it's your branch.
> 
> i made a copy error. `git clone -b --recursive v1.12.0`, because I tried other versions and still made the same mistake. i have solved this problem. I will reduce the cmake `3.26 rc6` to `3.24.4`

Sorry could you be more specific? have you built 1.12.1?

**Comment by qing-shang** [comment]
> > > 兰迪，这是你的分支。
> > 
> > 
> > 我犯了一个复制错误。，因为我尝试了其他版本，但仍然犯了同样的错误。我已经解决了这个问题。我会将cmake减少到`git clone -b --recursive v1.12.0``3.26 rc6``3.24.4`
> 
> 对不起，你能更具体一点吗？你构建了 1.12.1 吗？

yeah, i lowered the version of cmake to 3.24.4 and it was resolved.

**Comment by toothache** [comment]
Check this issue, https://gitlab.kitware.com/cmake/cmake/-/issues/24660.

CMake changed the behavior of ASM_MASM complier in version 3.26.

**Comment by snnn** [comment]
The build warning you saw should have been fixed.
