### ISSUE TITLE
[Feature Request] Optimization for Whisper ONNX model

### ISSUE THREAD

**Issue by zara0m** [microsoft/onnxruntime#15100]
### Describe the feature request

ONNX Runtime doesn't support the graph optimization of whisper yet. Only ['bert', 'gpt2', 'bart', 'unet'] are supported. I want the support for whisper.

### Describe scenario use case

Transformers/Optimum have some optimization function for onnx model of transformers, however it does not support whisper model yet.

I appreciate it if you could add this feature.

**Comment by yufenglee** [comment]
The work is in progress.
