### ISSUE TITLE
Update the onnxruntime nugets for cuda10 and include Arm64v8 as target

### ISSUE THREAD

**Issue by snzen** [microsoft/onnxruntime#1510]
Or should we build from source all the time?

**Comment by faxu** [comment]
The next version of ONNX Runtime (0.5) will be released next week and includes CUDA 10. We'll publish updated Nuget packages for this release. We do not plan to publish ARM64 builds at this time but these can be built from source.

**Comment by faxu** [comment]
The next release of ONNX Runtime (0.5) will be available next week and uses CUDA 10 and will have corresponding nuget packages published. We are not releasing an arm64 build at this time so you'll need to build from source. Is this for usage with a specific execution provider?

**Comment by snzen** [comment]
Yes TensorRT, the devices are Nvidia Jetson Xavier. To me building from source is for dev, going to prod with a snapshot of the source at a random point in time feels very wrong. It's kind of OK if the releases are also dead branches, but are they (i.e. do you fix bugs there)?  
Should I build from rel-0.5.0?

**Comment by faxu** [comment]
Once rel-0.5.0 is published, it will be tagged and maintained for servicing (as needed). Same applies for older releases. You can consider the release branch part of the official release and build from source there.
