### ISSUE TITLE
Couldnt pass image as input to CreateTensor

### ISSUE THREAD

**Issue by Maniron28** [microsoft/onnxruntime#15120]
### Describe the issue

I have been trying to understand how to integrate the DL model and C++, as a part of it I downloaded an open source DL model and trying to understand from it, but I have been facing issue when I try to use "CreateTensor" functionality

Error - Error C2440 'initializing': cannot convert from '_Ty *' to 'const int64_t *'

    #include<GLFW/glfw3.h>
    #define STB_IMAGE_IMPLEMENTATION
    #include "stb_image.h"

    #include <iostream>
    #include <onnxruntime_cxx_api.h>
    #include<dml_provider_factory.h>
    #include <vector>

     std::vector<float> load_image_and_preprocess(std::string& filename, int& x, int& y);

     std::vector<float> load_image_and_preprocess(std::string& filename, int& x, int& y) 
    {
        std::cout << x<<y<<filename<<std::endl;
        x = 0;
        y = 0;
        std::vector<float> ret;
        int n;
        unsigned char* data = stbi_load(filename.c_str(), &x, &y, &n, 3);
        ret.resize(x * y * 3);
        float* rptr = &ret[0 * x * y], * gptr = &ret[1 * x * y], * bptr = &ret[2 * x * y];
        for (int i = 0; i < x * y; i++) {
            *rptr++ = (float(data[3 * i + 0]) / 255 - 0.485) / 0.229;
            *gptr++ = (float(data[3 * i + 1]) / 255 - 0.456) / 0.224;
            *bptr++ = (float(data[3 * i + 2]) / 255 - 0.406) / 0.225;
        }
        stbi_image_free(data);
        return ret;
    
        }

    int main() 
    { 

    const std::string model_s = "C:/Downloads/resnet18-v1-7.tar/resnet18-v1-7/resnet18-v1-7.onnx";
    std::basic_string<ORTCHAR_T> model = std::basic_string<ORTCHAR_T>(model_s.begin(), model_s.end());
    std::cout << model.c_str();
    // onnxruntime setup
    Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "batch-model-explorer");
    Ort::SessionOptions session_options;
    
    OrtSessionOptionsAppendExecutionProvider_DML(session_options, 0);
    Ort::Session session = Ort::Session(env, model.c_str(), session_options);
  
    std::cout << "number of model input:" << session.GetInputCount() << std::endl;
    std::cout << "number of model Output:" << session.GetOutputCount() << std::endl;

    Ort::AllocatorWithDefaultOptions allocator;

    auto val = session.GetInputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape().size();
    auto val1 = session.GetOutputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape().size();
    std::cout << "number of model input:" << val << std::endl;
    std::cout << "number of model Output:" << val1 << std::endl;

    auto input_names = session.GetInputNameAllocated(0, allocator);
    auto output_names = session.GetOutputNameAllocated(0, allocator);
    std::cout << "Val:" << input_names << std::endl;
    std::cout << "Val:" << output_names << std::endl;

    std::vector<std::vector<int64_t>> input_node_dims(1);
    int i = 0;
    input_node_dims[0] = session.GetInputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape();

    for (int j = 0; j < input_node_dims[i].size(); j++)
        printf("Input %d : dim %d=%jd\n", i, j, input_node_dims[i][j]);
    
    int x = 0, y = 0;
    std::string sVal = "C:/Desktop/Image.png";
    std::vector<float> vecVal = load_image_and_preprocess(sVal, x, y);
    std::cout << vecVal.size() << std::endl;
    //for (int j = 0; j < vecVal.size(); j++)
     //   std::cout << vecVal[j] << std::endl;
    
    constexpr size_t input_tensor_size = 224 * 224 * 3;
    auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
    
    auto input_tensor = Ort::Value::CreateTensor<float>(memory_info, vecVal.data(), vecVal.size(),input_node_dims.data(), 4);

 
    return 0;
    }

### To reproduce

Try to compile the above code in visual studio and it gets reproduced

### Platform

Windows

### OS Version

Windows 10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

DirectML

**Comment by skottmckay** [comment]
Please see the examples for correct usage of CreateTensor.

https://github.com/search?q=repo%3Amicrosoft%2Fonnxruntime-inference-examples%20CreateTensor&type=code

The input dimensions are an array of int64_t values. You're using a vector of a vector of int64_t values, so `input_node_dims.data()` is returning a pointer to another vector and not to the int64_t values. 

`std::vector<std::vector<int64_t>> input_node_dims(1);`

**Comment by Maniron28** [comment]
![image](https://user-images.githubusercontent.com/71628009/226278706-ca866906-1bc4-4277-8266-319c61d22869.png)

I have changed the code to look something like this 

     #include<GLFW/glfw3.h>
     #define STB_IMAGE_IMPLEMENTATION
     #include "stb_image.h"
    
     #include <iostream>
     #include <onnxruntime_cxx_api.h>
     #include<dml_provider_factory.h>
     #include <vector>

      std::vector<float> load_image_and_preprocess(std::string& filename, int& x, int& y);

      std::vector<float> load_image_and_preprocess(std::string& filename, int& x, int& y) 
     {
         std::cout << x<<y<<filename<<std::endl;
         x = 0;
         y = 0;
         std::vector<float> ret;
         int n;
         unsigned char* data = stbi_load(filename.c_str(), &x, &y, &n, 3);
         ret.resize(x * y * 3);
         float* rptr = &ret[0 * x * y], * gptr = &ret[1 * x * y], * bptr = &ret[2 * x * y];
         for (int i = 0; i < x * y; i++) {
             *rptr++ = (float(data[3 * i + 0]) / 255 - 0.485) / 0.229;
             *gptr++ = (float(data[3 * i + 1]) / 255 - 0.456) / 0.224;
             *bptr++ = (float(data[3 * i + 2]) / 255 - 0.406) / 0.225;
         }
         stbi_image_free(data);
         return ret;

         }

     int main() 
     { 

     const std::string model_s = "C:/Downloads/resnet18-v1-7.tar/resnet18-v1-7/resnet18-v1-7.onnx";
     std::basic_string<ORTCHAR_T> model = std::basic_string<ORTCHAR_T>(model_s.begin(), model_s.end());
     std::cout << model.c_str();
     // onnxruntime setup
     Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "batch-model-explorer");
     Ort::SessionOptions session_options;

     OrtSessionOptionsAppendExecutionProvider_DML(session_options, 0);
     Ort::Session session = Ort::Session(env, model.c_str(), session_options);

     std::cout << "number of model input:" << session.GetInputCount() << std::endl;
     std::cout << "number of model Output:" << session.GetOutputCount() << std::endl;

     Ort::AllocatorWithDefaultOptions allocator;

     auto val = session.GetInputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape().size();
     auto val1 = session.GetOutputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape().size();
     std::cout << "number of model input:" << val << std::endl;
     std::cout << "number of model Output:" << val1 << std::endl;

     auto input_names = session.GetInputNameAllocated(0, allocator);
     auto output_names = session.GetOutputNameAllocated(0, allocator);
     std::cout << "Val:" << input_names << std::endl;
     std::cout << "Val:" << output_names << std::endl;


     std::vector<int64_t> input_node_dims;
     int i = 0;
     input_node_dims[0] = session.GetInputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape();

     for (int j = 0; j < input_node_dims[i].size(); j++)
         printf("Input %d : dim %d=%jd\n", i, j, input_node_dims[i][j]);

     int x = 0, y = 0;
     std::string sVal = "C:/Desktop/Image.png";
     std::vector<float> vecVal = load_image_and_preprocess(sVal, x, y);
     std::cout << vecVal.size() << std::endl;
     //for (int j = 0; j < vecVal.size(); j++)
      //   std::cout << vecVal[j] << std::endl;
     
     constexpr size_t input_tensor_size = 224 * 224 * 3;
     auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);

      auto input_tensor = Ort::Value::CreateTensor<float>(memory_info, vecVal.data(), vecVal.size(), input_node_dims.data(), 4);


     return 0;
     }

its gets exited with code 3 and if I comment the below line it compiles properly

      auto input_tensor = Ort::Value::CreateTensor<float>(memory_info, vecVal.data(), vecVal.size(), input_node_dims.data(), 4);

**Comment by Maniron28** [comment]
certain functionality are not getting listed or not available as a part the code which I am trying to run,
      #include <experimental_onnxruntime_cxx_api.h>
the above header file is not available
and 
      session.GetInputNames();
is also not available

**Comment by pranavsharma** [comment]
Do not use experimental_onnxruntime_cxx_api.h as it's not actively maintained. Use onnxruntime_cxx_api.h instead as it's the official one.

**Comment by Maniron28** [comment]
If I use the onnxruntime_cxx_api.h still I am facing the issue as it couldnt determine the "GetInputNames" function

**Comment by Maniron28** [comment]
> Do not use experimental_onnxruntime_cxx_api.h as it's not actively maintained. Use onnxruntime_cxx_api.h instead as it's the official one.

If I use the onnxruntime_cxx_api.h still I am facing the issue as it couldnt determine the "GetInputNames" function

**Comment by pranavsharma** [comment]
GetShape() returns a vector as seen [here](https://github.com/microsoft/onnxruntime/blob/8d87fdcfa19a6b5932c88137b9cd6a43a658c7f3/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L853. Hence, this statement ``` input_node_dims[0] = session.GetInputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape();``` is wrong. Please consider reading the API docs and examples.

**Comment by Maniron28** [comment]
> GetShape() returns a vector as seen [here](
> 
> https://github.com/microsoft/onnxruntime/blob/8d87fdcfa19a6b5932c88137b9cd6a43a658c7f3/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L853
> 
> . Hence, this statement ` input_node_dims[0] = session.GetInputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape();` is wrong. GetNames is not supported in the session API. You don't even need it. Please consider reading the API docs and examples.

https://github.com/microsoft/onnxruntime/issues/15120#issuecomment-1475770423 - I have pasted the updated code , can you check this

**Comment by Maniron28** [comment]
> GetShape() returns a vector as seen [here](
> 
> https://github.com/microsoft/onnxruntime/blob/8d87fdcfa19a6b5932c88137b9cd6a43a658c7f3/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L853
> 
> . Hence, this statement ` input_node_dims[0] = session.GetInputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape();` is wrong. GetNames is not supported in the session API. You don't even need it. Please consider reading the API docs and examples.

      const std::string model_s = "C:/Downloads/resnet18-v1-7.tar/resnet18-v1-7/resnet18-v1-7.onnx";
    std::basic_string<ORTCHAR_T> model = std::basic_string<ORTCHAR_T>(model_s.begin(), model_s.end());
    std::cout << model.c_str();
    // onnxruntime setup
    Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "batch-model-explorer");
    Ort::SessionOptions session_options;
    OrtSessionOptionsAppendExecutionProvider_DML(session_options, 0);
    Ort::Session session = Ort::Session(env, model.c_str(), session_options);

    std::cout << "number of model input:" << session.GetInputCount() << std::endl;
    std::cout << "number of model Output:" << session.GetOutputCount() << std::endl;

    Ort::AllocatorWithDefaultOptions allocator;

    auto val = session.GetInputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape().size();
    auto val1 = session.GetOutputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape().size();
    std::cout << "number of model input:" << val << std::endl;
    std::cout << "number of model Output:" << val1 << std::endl;

    auto input_names = session.GetInputNameAllocated(0, allocator);
    auto output_names = session.GetOutputNameAllocated(0, allocator);
    std::cout << "Val:" << input_names << std::endl;
    std::cout << "Val:" << output_names << std::endl;


    std::vector<int64_t> input_node_dims;
    int i = 0;
    input_node_dims = session.GetInputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape();

    for (int j = 0; j < input_node_dims.size(); j++)
        printf("Input %d : dim %d=%jd\n", i, j, input_node_dims[j]);
    
    int x = 0, y = 0;
    std::string sVal = "C:/Desktop/Image.png";
    std::vector<float> vecVal = load_image_and_preprocess(sVal, x, y);
    std::cout << vecVal.size() << std::endl;
    //for (int j = 0; j < vecVal.size(); j++)
     //   std::cout << vecVal[j] << std::endl;
    
    constexpr size_t input_tensor_size = 224 * 224 * 3;
    auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);

    std::cout << "input_node_dims.data()" << typeid(input_node_dims.data()).name() << std::endl;
    
    auto input_tensor = Ort::Value::CreateTensor<float>(memory_info, vecVal.data(), vecVal.size(),input_node_dims.data(), 4);

 
    return 0;
