### ISSUE TITLE
[Build] Compiliation failed on Xilinx Zynq 

### ISSUE THREAD

**Issue by BoarQing** [microsoft/onnxruntime#15155]
### Describe the issue

onnxruntime_mlas.cmake failed to compile on Xilinx's Zynq. 

It seems like fp16 is not supported on Zynq.

### Urgency

It would stall the verification process of Vitis-AI, a provider for onnxruntime.

### Target platform

Xilinx Zynq(aarch640)

### Build script

None

### Error / output

cc1plus: error: switch ‘-mcpu=cortex-a72.cortex-a53’ conflicts with ‘-march=armv8.2-a+fp16’ switch [-Werror]

**Comment by chenfucn** [comment]
Please take a look at the following PR. This PR is aimed at fixing compilation errors caused by older compilers or assemblers not supporting fp16.
https://github.com/microsoft/onnxruntime/pull/15055

**Comment by BoarQing** [comment]
> 

it does not fix the error. It is not beacuase older compilers or assemblers. It is because the hardware(-mcpu=cortex-a72.cortex-a53) does not support fp16.

**Comment by BoarQing** [comment]
We are using pentalinux which compile arm binary on a x86 machine. Thus, the flag is added. But, I checked on wiki. Isn't fp16 supported after armv8.2? Would that cause error even if we compile it natively and without the flag on an aritecture older than v8.2?

**Comment by chenfucn** [comment]
Sorry I am not sure I understand how those flags are added in your case. I used an x86 machine for cross compilation arm64, and I checked, those flags were not added.

**Comment by BoarQing** [comment]
It is not really about the flag. Could you check if your code can compile and run on an aritecture older than v8.2? https://en.wikipedia.org/wiki/ARM_Cortex-A72

**Comment by frdasah** [comment]
Hi,
I am facing the same issue. I am compiling for linux environment for arm v8.0 processor (-mcpu=cortex-a53).

The flags that cause the issue are set in file cmake/onnxruntime_mlas.cmake (around line 360) for the case NOT APPLE.
For example on 1.15.1:
          set_source_files_properties(${MLAS_SRC_DIR}/aarch64/HalfGemmKernelNeon.S PROPERTIES COMPILE_FLAGS " -march=armv8.2-a+fp16 ")
          set_source_files_properties(${MLAS_SRC_DIR}/activate_fp16.cpp PROPERTIES COMPILE_FLAGS " -march=armv8.2-a+fp16 ")
          set_source_files_properties(${MLAS_SRC_DIR}/dwconv.cpp PROPERTIES COMPILE_FLAGS " -march=armv8.2-a+fp16 ")
          set_source_files_properties(${MLAS_SRC_DIR}/pooling_fp16.cpp PROPERTIES COMPILE_FLAGS " -march=armv8.2-a+fp16 ")

Is there any way to compile for armv8.0 processors for linux ?

**Comment by BoarQing** [comment]
> Hi, I am facing the same issue. I am compiling for linux environment for arm v8.0 processor (-mcpu=cortex-a53).
> 
> The flags that cause the issue are set in file cmake/onnxruntime_mlas.cmake (around line 360) for the case NOT APPLE. For example on 1.15.1: set_source_files_properties(${MLAS_SRC_DIR}/aarch64/HalfGemmKernelNeon.S PROPERTIES COMPILE_FLAGS " -march=armv8.2-a+fp16 ") set_source_files_properties(${MLAS_SRC_DIR}/activate_fp16.cpp PROPERTIES COMPILE_FLAGS " -march=armv8.2-a+fp16 ") set_source_files_properties(${MLAS_SRC_DIR}/dwconv.cpp PROPERTIES COMPILE_FLAGS " -march=armv8.2-a+fp16 ") set_source_files_properties(${MLAS_SRC_DIR}/pooling_fp16.cpp PROPERTIES COMPILE_FLAGS " -march=armv8.2-a+fp16 ")
> 
> Is there any way to compile for armv8.0 processors for linux ?

We used a custom patch to skip compiling these file.

**Comment by frdasah** [comment]
Thank you for your answer. I also did a patch on my side.
