### ISSUE TITLE
No output in console after OrtCreateSession

### ISSUE THREAD

**Issue by ivannp** [microsoft/onnxruntime#1515]
**Describe the bug**
My Windows console application doesn't produce output when I run it from the command line. After some debugging it seems than any:

    cout << "something " << endl;

statement doesn't have any effect after the first call to *OrtCreateSession*. Before the output shows as expected.

Strangely enough, if I run the program from visual studio, I see the output.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 0.40
- Visual Studio version (if applicable): 2017

**To Reproduce**
Build a small sample, run it from the command line.

**Expected behavior**
I expect all the output to show.

**Comment by RyanUnderhill** [comment]
I tried to reproduce the bug but cout still works fine after the call to OrtCreateSession. Can you reproduce the problem when compiling the C_Api_Sample.cpp file? (inside onnxrt\csharp\test\Microsoft.ML.OnnxRuntime.EndToEndTests.Capi)

I wonder if it's being run with different options in the console vs visual studio?

**Comment by faxu** [comment]
@ivanp do you still need assistance on this issue?
