### ISSUE TITLE
[Training] Does OnnxRuntime op supoort 0D Tensor?

### ISSUE THREAD

**Issue by zhouwei25** [microsoft/onnxruntime#15177]
### Describe the issue

For 0D Tensor, first describe its concept from a mathematical point of view: 
* 0D Tensor represents a scalar Tensor, which corresponds to Numpy's 0D array, which can be expressed as np.array (10.), with shape of [], dimension of 0, and size of 1.
* 1D Tensor represents a vector Tensor, which corresponds to the Numpy's 1D array. If there is only one element, it can be expressed as np.array ([10.]), with shape of [1], dimension of 1, and size of 1.

### To reproduce

If the model have been converted to `.onnx`  file. The op may input 0D Tensor, such as `torch.Tensor(1.)` , whether it can work normally?

For many unary OPs, 0D Tensor should be supported; `op(0D) -> 0D`
For many binary OPs, 0D Tensor and broadcast should be supported; `op(0D, 0D) -> 0D`、`op(0D, ND) -> ND`、`op(ND, 0D) -> 0D`

I want to know whether it's supported now?  If not, as a suggestion, it should be fully supported.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

v1.14.1

### PyTorch Version

v2.0.0

### Execution Provider

CUDA

**Comment by wschin** [comment]
It should work as you expect.

**Comment by wschin** [comment]
Please feel free to reopen if anything goes wrong. Thanks.
