### ISSUE TITLE
c++ opencv Error: Assertion failed (!ssize.empty())

### ISSUE THREAD

**Issue by Maniron28** [microsoft/onnxruntime#15171]
### Describe the issue

I have been trying to run an onnxmodel in C++, I have been trying to read an image and pass it as input to the model, But I am facing an issue 

      cv::Mat imageBGR = cv::imread("C:/Desktop/Untitled_sample.png", cv::ImreadModes::IMREAD_COLOR);
      cv::Mat resizedImageBGR, resizedImageRGB, resizedImage, preprocessedImage;
      std::cout << "VALUESSSJB DS" << inputDims.at(3) << "SEC" << inputDims.at(2);
      cv::resize(imageBGR, resizedImageBGR,cv::Size(inputDims.at(3), inputDims.at(2)),cv::InterpolationFlags::INTER_CUBIC);

I am getting Assertion failed (!ssize.empty()) error, help me out in solving this issue

### To reproduce

      #include<GLFW/glfw3.h>
      #define STB_IMAGE_IMPLEMENTATION
      #include "stb_image.h"
      #include <iostream>
      #include <onnxruntime_cxx_api.h>
       #include<dml_provider_factory.h>
      #include <vector>
      #include <typeinfo>
      
      #include <opencv2/dnn/dnn.hpp>
      #include <opencv2/imgcodecs.hpp>
      #include <opencv2/imgproc.hpp>
      #include <opencv2/opencv.hpp>
      
      
      
      #include <chrono>
      #include <cmath>
      #include <exception>
      #include <fstream>
      #include <iostream>
      #include <limits>
      #include <numeric>
      #include <string>
      #include <vector>
      #include <stdexcept> // To use runtime_error
      #include <Windows.h>
      #include <psapi.h>
      
      using namespace cv;
      
      
      std::vector<float> load_image_and_preprocess(std::string& filename, int& x, int& y);
      
      template <typename T>
      T vectorProduct(const std::vector<T>& v)
      {
          return accumulate(v.begin(), v.end(), 1, std::multiplies<T>());
      }
      
      
      std::vector<float> load_image_and_preprocess(std::string& filename, int& x, int& y) 
      {
          std::cout << x<<y<<filename<<std::endl;
          x = 0;
          y = 0;
          std::vector<float> ret;
          int n;
          unsigned char* data = stbi_load(filename.c_str(), &x, &y, &n, 3);
          ret.resize(x * y * 3);
          float* rptr = &ret[0 * x * y], * gptr = &ret[1 * x * y], * bptr = &ret[2 * x * y];
          for (int i = 0; i < x * y; i++) {
              *rptr++ = (float(data[3 * i + 0]) / 255 - 0.485) / 0.229;
              *gptr++ = (float(data[3 * i + 1]) / 255 - 0.456) / 0.224;
              *bptr++ = (float(data[3 * i + 2]) / 255 - 0.406) / 0.225;
          }
          stbi_image_free(data);
          return ret;
      }
      int main()
      {
          const std::string model_s = "C:/Downloads/resnet18-v1-7.tar/resnet18-v1-7/resnet18-v1-7.onnx";
          std::basic_string<ORTCHAR_T> model = std::basic_string<ORTCHAR_T>(model_s.begin(), model_s.end());
          std::cout << model.c_str();
          // onnxruntime setup
          Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "batch-model-explorer");
          Ort::SessionOptions session_options;
          OrtSessionOptionsAppendExecutionProvider_DML(session_options, 0);
          Ort::Session session = Ort::Session(env, model.c_str(), session_options);
      
          Ort::AllocatorWithDefaultOptions allocator;
      
          size_t numInputNodes = session.GetInputCount();
          size_t numOutputNodes = session.GetOutputCount();
      
          std::cout << "Number of Input Nodes: " << numInputNodes << std::endl;
          std::cout << "Number of Output Nodes: " << numOutputNodes << std::endl;
      
          auto inputNodeName = session.GetInputNameAllocated(0, allocator);
          const char* inputName = inputNodeName.get();
          std::cout << "Input Name: " << inputName << std::endl;
      
          Ort::TypeInfo inputTypeInfo = session.GetInputTypeInfo(0);
          auto inputTensorInfo = inputTypeInfo.GetTensorTypeAndShapeInfo();
      
          ONNXTensorElementDataType inputType = inputTensorInfo.GetElementType();
          std::cout << "Input Type: " << inputType << std::endl;
      
          std::vector<int64_t> inputDims = inputTensorInfo.GetShape();
          std::cout << "Input Dimensions: " << inputDims[0] << std::endl;
      
          auto outputNodeName = session.GetOutputNameAllocated(0, allocator);
          const char* outputName = outputNodeName.get();
          std::cout << "Output Name: " << outputName << std::endl;
      
          Ort::TypeInfo outputTypeInfo = session.GetOutputTypeInfo(0);
          auto outputTensorInfo = outputTypeInfo.GetTensorTypeAndShapeInfo();
      
          ONNXTensorElementDataType outputType = outputTensorInfo.GetElementType();
          std::cout << "Output Type: " << outputType << std::endl;
      
          std::vector<int64_t> outputDims = outputTensorInfo.GetShape();
          std::cout << "Output Dimensions: " << outputDims[0] << std::endl;
          inputDims.data(), inputDims.size());
      
          cv::Mat imageBGR = cv::imread("C:/Desktop/Untitled_sample.png", cv::ImreadModes::IMREAD_COLOR);
          
          cv::Mat resizedImageBGR, resizedImageRGB, resizedImage, preprocessedImage;
          std::cout << "VALUESSSJB DS" << inputDims.at(3) << "SEC" << inputDims.at(2);
          cv::resize(imageBGR, resizedImageBGR,cv::Size(inputDims.at(3), inputDims.at(2)),cv::InterpolationFlags::INTER_CUBIC);
          
      }

This is the above code I am trying to run

### Platform

Windows

### OS Version

Windows 10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

DirectML

**Comment by fdwr** [comment]
Do you get the same issue with `OrtSessionOptionsAppendExecutionProvider_DML` removed?

**Comment by Maniron28** [comment]
yes, and I found out that the error was because the 

sFilename = "C:\\Users\\Desktop\\Image.png";

       cv::Mat imageBGR = cv::imread(sFilename);

         if (imageBGR.empty())
       {
            std::cout << "Could not open or find the image" << std::endl;
             return -1;
       }

couldnt access the path of the image I am providing and throws the error as mentioned below
       
       error : cv::findDecoder imread_('Could not open or find the image')

**Comment by fdwr** [comment]
> yes, and I found out that the error

Is the issue closeable now then?

**Comment by Maniron28** [comment]
> > yes, and I found out that the error
> 
> Good that you found it. Is the issue closeable now then?

Not yet, Now I am facing a issue in which I have mentioned in the https://github.com/microsoft/onnxruntime/issues/15171#issuecomment-1480723930

**Comment by nums11** [comment]
Closing as stale.
