### ISSUE TITLE
I want to confirm: Tensor's elem_type MUST be present and MUST NOT be UNDEFINED?

### ISSUE THREAD

**Issue by hawkwm** [microsoft/onnxruntime#15201]
### Describe the documentation issue

Hello,

From the definition of Tensor as following, Tensor's elem_type MUST be present and MUST NOT be UNDEFINED, is right? but why elem_type is optional?
https://github.com/onnx/onnx/blob/9b7bca2a723ff94edcd007d93b5d0cf1838591dc/onnx/onnx-ml.proto#L669-L675
```
  message Tensor {
    // This field MUST NOT have the value of UNDEFINED
    // This field MUST have a valid TensorProto.DataType value
    // This field MUST be present for this version of the IR.
    optional int32 elem_type = 1;
    optional TensorShapeProto shape = 2;
  }
```
From the Constructor of NodeArg, it seems elem_type can be absent, I'm confused. could you help me confirm does Tensor's elem_type MUST be present and MUST NOT be UNDEFINED? and show me the related documents or codes? Thank you!
https://github.com/microsoft/onnxruntime/blob/3a4c895765c7a917279f9ace442ae9f5119258ea/include/onnxruntime/core/graph/node_arg.h#L37-L43

https://github.com/microsoft/onnxruntime/blob/3a4c895765c7a917279f9ace442ae9f5119258ea/onnxruntime/core/graph/graph.cc#L182-L186

**Comment by pranavsharma** [comment]
As the comments say, element type is *not* optional. We use optional in protobuf to preserve backward compatibility in case we want to change the spec for whatever reasons. Required fields break backward compat as it's 'forever'.
