### ISSUE TITLE
[Performance] Run ONNXRuntime 2 Model meantime on GPU caused slower Speed than sequential

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#15202]
### Describe the issue

Run ONNXRuntime 2 Model meantime on GPU caused slower Speed than sequential

### To reproduce

Run ONNXRuntime 2 Model meantime on GPU caused slower Speed than sequential

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

### Is this a quantized model?

No

**Comment by wangyems** [comment]
Please provide more information so we can help you.

**Comment by jinfagang** [comment]
@wangyems I think this is a common problem, for example, on 1080TI, running on CUDA with onnxruntime, if 2 or more models running in parallel, every model will slower than run alone.

This actually is normal since we don;t have vGPU support, but is there a way to make it less impact on the slower rate? Currently 2 models parallel is much more slower than run 1 single alone. ( 30ms vs 10ms)

**Comment by pranavsharma** [comment]
First let's see if we've the basics. I assume you've 2 sessions, one for each model and for each model all nodes are placed on the GPU [1]. This can be determined by turning on verbose mode when creating the env and grepping for "Node placement" in the output. The expectation is that all nodes be placed on the GPU. Next step: We made some changes w.r.t multi-stream in 1.14 release. Do you see better results with an earlier release of ORT?

**Comment by jinfagang** [comment]
@pranavsharma yes, am runing 2 sessions at the same time. for each model, both runs on same GPU 1.

This is currrently ort version:
![image](https://user-images.githubusercontent.com/21303438/228444017-7c68d702-e3fe-4691-ae87-4581fd2ebc0b.png)

Will 1.14 changed 2 models in parallel behaviour on gpu? By how

**Comment by pranavsharma** [comment]
You can't tie both sessions to the same device id. Each session should be associated with a different device id.

**Comment by jinfagang** [comment]
@pranavsharma I have only 1 card, and I have 6 over all to run, what should I now?

**Comment by pranavsharma** [comment]
I'm sorry, in that case you can't run them in parallel.

**Comment by jinfagang** [comment]
@pranavsharma Hi, why can I run 2 models in parallel if 1 model using just 400M GPU mem, and my GPU mem is enough, what do you mean by can't?

I think run 2 models on a same card is very common use scenario?

**Comment by pranavsharma** [comment]
ORT is designed to have 1 session associated with 1 model and 1 device id only. You can run your models sequentially if you've only 1 card (slow but will work) or get a multi-GPU machine.

**Comment by jinfagang** [comment]
@pranavsharma  thanks for your right but useless answer.

**Comment by jinfagang** [comment]
@pranavsharma Different thread in one process. 2 models using 2 sessions but in 2 threads
