### ISSUE TITLE
Slice Symbolic Shape Inference Crashes Due to Missing Start/End With Sympy

### ISSUE THREAD

**Issue by iherdgoats** [microsoft/onnxruntime#15210]
### Describe the issue

With a model exported from pytorch I'm seeing a crash in the symbolic shape inference code due to sympy and a missing slice start / end value.

```
File ~/venv/lib/python3.10/site-packages/onnxruntime/tools/symbolic_shape_infer.py:1780, in SymbolicShapeInference._infer_Slice(self, node)
   1768 vi.CopyFrom(
   1769     helper.make_tensor_value_info(
   1770         node.output[0],
   (...)
   1773     )
   1774 )
   1776 # handle sympy_data if needed, for slice in shape computation
   1777 if (
   1778     node.input[0] in self.sympy_data_
   1779     and [0] == axes
-> 1780     and len(starts) == 1
   1781     and len(ends) == 1
   1782     and len(steps) == 1
   1783 ):
   1784     input_sympy_data = self.sympy_data_[node.input[0]]
   1785     if type(input_sympy_data) == list or (
   1786         type(input_sympy_data) == np.array and len(input_sympy_data.shape) == 1
   1787     ):

TypeError: object of type 'NoneType' has no len()
```

### To reproduce

https://drive.google.com/file/d/1WTFBQs00Q3qtV0YKnJUlBdTXqSyp1pHS/view?usp=share_link

### Platform

Linux

### OS Version

Ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by yf711** [comment]
Hi @iherdgoats I got this error below when running the model. It seems the model you shared doesn't come with weight:
`FileNotFoundError: [Errno 2] No such file or directory: 'tok_embeddings.weight'`

Could you share all files which are necessary to repro the issue if the issue is still there? Thanks!
