### ISSUE TITLE
Stable Diffusion UNet optimization does not fuse attention

### ISSUE THREAD

**Issue by sudo-carson** [microsoft/onnxruntime#15225]
### Describe the issue

I am trying to use the CUDA optimizations for the Stable Diffusion UNet described [here](https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/python/tools/transformers/models/stable_diffusion). I found that most optimizations work, though it does not fuse attention - `model.get_fused_operator_statistics()` always returns:
```
Optimized operators:{'Attention': 0, 'MultiHeadAttention': 0, 'LayerNormalization': 16, 'SkipLayerNormalization': 32, 'BiasSplitGelu': 16, 'GroupNorm': 61, 'NhwcConv': 98, 'BiasAdd': 0}
```

It appears the fusion script cannot find the QKV nodes ([here in `fusion_attention_unet.py`](https://github.com/microsoft/onnxruntime/blob/750747d8c9f1a96bda182b9a8810f3f6a75d6bdc/onnxruntime/python/tools/transformers/fusion_attention_unet.py#L369-L376)).

### To reproduce

The converted (non-optimized) UNet is [here on Google Drive](https://drive.google.com/file/d/1ESSsBRm9NnwRh6ZMCuthyWk7yZKJD3hm/view?usp=sharing). The code I used to convert the UNet is [here](https://github.com/pykeio/diffusers/blob/9b0fe38e166747c6cc1a6ce5a9ee5f731a089170/scripts/sd2pyke.py#L168-L232).

I modified the original optimization script to only convert the UNet:

```py
import os.path
from pathlib import Path
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '_optimizer'))
# _optimizer is copied from onnxruntime/python/tools/transformers at d834ec895af8c2dd6e718c21b575697c01b8ec4f

from fusion_options import FusionOptions
from optimizer import optimize_by_onnxruntime, optimize_model

in_path = Path('./model')

fusion_options = FusionOptions('unet')
fusion_options.use_multi_head_attention = True

m = optimize_model(
	str(in_path / 'unet.onnx'),
	model_type='unet',
	num_heads=0,
	hidden_size=0,
	opt_level=0,
	optimization_options=fusion_options,
	use_gpu=True
)

m.get_fused_operator_statistics()
m.save_model_to_file(in_path / 'unet.opt.onnx', use_external_data_format=False)
```

### Platform

Windows

### OS Version

11 25314.1010

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

onnxruntime-gpu 1.14.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by tianleiwu** [comment]
The optimization was tested with the following packages (see [requirements.txt](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/models/stable_diffusion/requirements.txt)):
```
diffusers==0.13.0        # 0.14.0 might also work
transformers==4.26.0
torch==1.13.1+cu117
```

The export script is like the following: https://github.com/huggingface/diffusers/blob/b2c1e0d6d4ffbd93fc0c381e5b9cdf316ca4f99f/scripts/convert_stable_diffusion_checkpoint_to_onnx.py#L107-L128

If you use different version of package or uses different export script, onnx graph might be different.
