### ISSUE TITLE
[Build] Can I use DML with EXTENDED_MINIMAL_BUILD compilation mode？

### ISSUE THREAD

**Issue by DaiShaoJie77** [microsoft/onnxruntime#15233]
### Describe the issue

 Can I use DML with EXTENDED_MINIMAL_BUILD compilation mode？

### Urgency

In a hurry

### Target platform

Windwos X64

### Build script

build.py

### Error / output

build error

**Comment by pranavsharma** [comment]
Have you tried it? Can you paste the error here?

**Comment by SJDai-375** [comment]
> Have you tried it? Can you paste the error here?

He suggested some errors such as InferenceContext could no longer be found in onnx::

**Comment by skottmckay** [comment]
The DML EP is not currently supported in a minimal build as it would require significant refactoring to do so. 

What's the use-case where you require a minimal build and DML to be used?

**Comment by SJDai-375** [comment]
> The DML EP is not currently supported in a minimal build as it would require significant refactoring to do so.
> 
> What's the use-case where you require a minimal build and DML to be used?

I want to reduce the library size as much as possible

**Comment by SJDai-375** [comment]
> The DML EP is not currently supported in a minimal build as it would require significant refactoring to do so.
> 
> What's the use-case where you require a minimal build and DML to be used?

Is the same with EXTENDED_MINIMAL ？

**Comment by skottmckay** [comment]
Can you please elaborate on why you want to reduce the size and whether this is for a production scenario?

DML is not supported in any style of minimal build. You can still however do a regular build with just the types/operators your model needs to achieve a lot of the savings. If you [run the script](https://onnxruntime.ai/docs/performance/model-optimizations/ort-format-models.html#convert-onnx-models-to-ort-format-script-usage) to convert a model to ORT format it will produce a configuration file that can used with a regular build to reduce the operators and types (if type reduction is enabled). 

e.g. these params would provide a lot of the reduction
`--disable_rtti --disable_exceptions --disable_ml_ops --skip_tests --cmake_extra_defines onnxruntime_DISABLE_SPARSE_TENSORS=ON onnxruntime_DISABLE_OPTIONAL_TYPE=ON onnxruntime_BUILD_UNIT_TESTS=OFF --include_ops_by_config <config from model conversion>`

**Comment by SJDai-375** [comment]
My scene is not just a model. There is also an issue with the ort model in onnxruntimeV1.11 in the dml back end where the tryassignsingleNode is not supported?
 

> Can you please elaborate on why you want to reduce the size and whether this is for a production scenario?
> 
> DML is not supported in any style of minimal build. You can still however do a regular build with just the types/operators your model needs to achieve a lot of the savings. If you [run the script](https://onnxruntime.ai/docs/performance/model-optimizations/ort-format-models.html#convert-onnx-models-to-ort-format-script-usage) to convert a model to ORT format it will produce a configuration file that can used with a regular build to reduce the operators and types (if type reduction is enabled).
> 
> e.g. these params would provide a lot of the reduction `--disable_rtti --disable_exceptions --disable_ml_ops --skip_tests --cmake_extra_defines onnxruntime_DISABLE_SPARSE_TENSORS=ON onnxruntime_DISABLE_OPTIONAL_TYPE=ON onnxruntime_BUILD_UNIT_TESTS=OFF --include_ops_by_config <config from model conversion>`

My scene is not just a model. There is also an issue with the ort model in onnxruntimeV1.11 in the dml back end where the tryassignsingleNode is not supported?

**Comment by SJDai-375** [comment]
> Can you please elaborate on why you want to reduce the size and whether this is for a production scenario?
> 
> DML is not supported in any style of minimal build. You can still however do a regular build with just the types/operators your model needs to achieve a lot of the savings. If you [run the script](https://onnxruntime.ai/docs/performance/model-optimizations/ort-format-models.html#convert-onnx-models-to-ort-format-script-usage) to convert a model to ORT format it will produce a configuration file that can used with a regular build to reduce the operators and types (if type reduction is enabled).
> 
> e.g. these params would provide a lot of the reduction `--disable_rtti --disable_exceptions --disable_ml_ops --skip_tests --cmake_extra_defines onnxruntime_DISABLE_SPARSE_TENSORS=ON onnxruntime_DISABLE_OPTIONAL_TYPE=ON onnxruntime_BUILD_UNIT_TESTS=OFF --include_ops_by_config <config from model conversion>`

I'm sorry. I think I found this switch

**Comment by nums11** [comment]
Closing as stale.
