### ISSUE TITLE
[Build] Windows 10 + CUDA 12.1

### ISSUE THREAD

**Issue by tanmayv25** [microsoft/onnxruntime#15242]
### Describe the issue

We are facing following errors when trying to build onnxruntime on windows with cuda 12.1.

Build command:
```
 RUN build.bat --cmake_generator "Visual Studio 16 2019" --config Release --cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES=52;60;61;70;75;80;86" --skip_submodule_sync --parallel --build_shared_lib --update --build --build_dir /workspace/build --use_cuda --cuda_version "12.1" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1" --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1" --use_tensorrt --tensorrt_home "/tensorrt"
```

Errors:
```
"C:\tmp\tritonbuild\onnxruntime\build\install.vcxproj" (default target) (1) ->
       "C:\tmp\tritonbuild\onnxruntime\build\ALL_BUILD.vcxproj" (default target) (3) ->
       "C:\tmp\tritonbuild\onnxruntime\build\triton-onnxruntime-backend.vcxproj" (default target) (12) ->
       "C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj" (default target) (13) ->
       (CustomBuild target) -> 
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : "cuda" is ambiguous [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : expected an expression [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : "cuda" is ambiguous [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : expected an expression [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : "cuda" is ambiguous [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : expected an expression [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : "cuda" is ambiguous [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : expected an expression [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
```

Similar namespacing errors on linux build with cuda 12.1 was resolved by [this](https://github.com/microsoft/onnxruntime/commit/12d91173c4478e0975771c06fd9d062a33c46339) commit. 

### Target platform

Windows 10

### Build script

build.bat --cmake_generator "Visual Studio 16 2019" --config Release --cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES=52;60;61;70;75;80;86" --skip_submodule_sync --parallel --build_shared_lib --update --build --build_dir /workspace/build --use_cuda --cuda_version "12.1" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1" --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1" --use_tensorrt --tensorrt_home "/tensorrt"

### Error / output

C:\tmp\tritonbuild\onnxruntime\build\install.vcxproj" (default target) (1) ->
       "C:\tmp\tritonbuild\onnxruntime\build\ALL_BUILD.vcxproj" (default target) (3) ->
       "C:\tmp\tritonbuild\onnxruntime\build\triton-onnxruntime-backend.vcxproj" (default target) (12) ->
       "C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj" (default target) (13) ->
       (CustomBuild target) -> 
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : "cuda" is ambiguous [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : expected an expression [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : "cuda" is ambiguous [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : expected an expression [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : "cuda" is ambiguous [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : expected an expression [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : "cuda" is ambiguous [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include\cuda\std\detail/libcxx/include/type_traits(2101): error : expected an expression [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\BuildTools\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 12.1.targets(799,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\nvcc.exe"  --use-local-env -ccbin "C:\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64" -x cu   -IC:\workspace\onnxruntime\include\onnxruntime -IC:\workspace\onnxruntime\include\onnxruntime\core\session -I"C:\workspace\build\Release\_deps\pytorch_cpuinfo-src\include" -IC:\workspace\build\Release -IC:\workspace\onnxruntime\onnxruntime -I"C:\workspace\build\Release\_deps\abseil_cpp-src" -I"C:\workspace\build\Release\_deps\safeint-src" -I"C:\workspace\build\Release\_deps\gsl-src\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include" -I"C:\workspace\build\Release\_deps\onnx-src" -I"C:\workspace\build\Release\_deps\onnx-build" -I"C:\workspace\build\Release\_deps\protobuf-src\src" -I"C:\workspace\build\Release\_deps\flatbuffers-src\include" -I"C:\workspace\build\Release\_deps\cutlass-src\include" -I"C:\workspace\build\Release\_deps\cutlass-src\examples" -I"C:\workspace\build\Release\_deps\eigen-src" -I"C:\workspace\build\Release\_deps\onnx_tensorrt-src" -I\TensorRT\include -I"C:\workspace\build\Release\_deps\mp11-src\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\include"     --keep-dir x64\Release  -maxrregcount=0   --machine 64 --compile -cudart shared --expt-relaxed-constexpr --Werror default-stream-launch -Xcudafe --diag_suppress=bad_friend_decl -Xcudafe --diag_suppress=unsigned_compare_with_zero -Xcudafe --diag_suppress=expr_has_no_effect --generate-code=arch=compute_52,code=[compute_52,sm_52] --generate-code=arch=compute_60,code=[compute_60,sm_60] --generate-code=arch=compute_61,code=[compute_61,sm_61] --generate-code=arch=compute_70,code=[compute_70,sm_70] --generate-code=arch=compute_75,code=[compute_75,sm_75] --generate-code=arch=compute_80,code=[compute_80,sm_80] --generate-code=arch=compute_86,code=[compute_86,sm_86] --diag-suppress 554 --threads 0 -std=c++17 -Werror all-warnings -Xcompiler="/EHsc -Ob2 /utf-8 /sdl /wd4251 /wd4201 /wd5054 /w15038 /guard:cf /wd4251 /wd4201 /wd5054 /w15038 /wd4834 /wd4127"   -D_WINDOWS -DNDEBUG -DCPUINFO_SUPPORTED_PLATFORM=1 -DEIGEN_USE_THREADS -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -DUSE_CUDA=1 -DUSE_FLASH_ATTENTION=1 -DUSE_TENSORRT=1 -DONNX_NAMESPACE=onnx -DONNX_ML=1 -DWIN32_LEAN_AND_MEAN -DORT_ENABLE_STREAM -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CONSTEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES -DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11_ATOMIC -DEIGEN_STRONG_INLINE=inline -DWINAPI_FAMILY=100 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DNTDDI_VERSION=0x06010000 -D_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING=1 -D"CMAKE_INTDIR=\"Release\"" -Donnxruntime_providers_cuda_EXPORTS -D_WINDLL -D_MBCS -DWIN32 -D_WINDOWS -DEIGEN_HAS_C99_MATH -DCPUINFO_SUPPORTED -DNDEBUG -DCPUINFO_SUPPORTED_PLATFORM=1 -DEIGEN_USE_THREADS -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -DUSE_CUDA=1 -DUSE_FLASH_ATTENTION=1 -DUSE_TENSORRT=1 -DONNX_NAMESPACE=onnx -DONNX_ML=1 -DWIN32_LEAN_AND_MEAN -DORT_ENABLE_STREAM -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CONSTEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES -DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11_ATOMIC -DEIGEN_STRONG_INLINE=inline -DWINAPI_FAMILY=100 -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -DNTDDI_VERSION=0x06010000 -D_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING=1 -D"CMAKE_INTDIR=\"Release\"" -Donnxruntime_providers_cuda_EXPORTS -Xcompiler "/EHsc /W3 /nologo /O2 /FS   /MD /GR" -Xcompiler "/Fdonnxruntime_providers_cuda.dir\Release\vc142.pdb" -o onnxruntime_providers_cuda.dir\Release\attention_impl.obj "C:\workspace\onnxruntime\onnxruntime\contrib_ops\cuda\bert\attention_impl.cu"" exited with code -1. [C:\workspace\build\Release\onnxruntime_providers_cuda.vcxproj] [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]
         C:\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\tmp\tritonbuild\onnxruntime\build\CMakeFiles\1391fbda87be57075fb5bba7a38c2954\onnxruntime.rule;C:\tmp\tritonbuild\onnxruntime\build\CMakeFiles\c0b7ec8ce4dc22ca22ac8622f7a49e15\ort_target.rule;C:\tmp\tritonbuild\onnxruntime\CMakeLists.txt' exited with code 1. [C:\tmp\tritonbuild\onnxruntime\build\ort_target.vcxproj]

### Visual Studio Version

Visual Studio 16 2019

### GCC / Compiler Version

 MSVC 19.29.30147.0

**Comment by tanmayv25** [comment]
Based upon yesterday's meeting with Pranav, I believe the plan was for Microsoft to fix ORT build for cuda 12 and possibly have a CI.
@pranavsharma for more clarification.

**Comment by snnn** [comment]
Right now our situation is each ORT build is bound to one specific CUDA minor version. For example, CUDA 11.6. All other versions do not work. Even CUDA 11.8 or any other version does not work. We can have more pipelines to test more configurations, however, more pipelines mean more resources required.  I will try to apply more GPUs, but please know not only I want more GPUs, everybody wants more.

**Comment by junwang-wish** [comment]
Is there a timeline for supporting Onnxruntime-gpu CUDAExecutioner for CUDA 12.1? I tried nightly build 
```
pip3.8 install -U ort-nightly-gpu==1.15.0.dev20230330002 -i https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/
```

and can get correct devices and executioners
```
import onnxruntime as ort
ort.__version__, ort.get_device()
('1.15.0', 'GPU')
ort.get_available_providers()
['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
```
but still getting error when actually running an inference
```
session = ort.InferenceSession(
    '/workspaces/model.onnx',
    providers=['CUDAExecutionProvider']
)

2023-03-31 16:24:26.783840208 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:546 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.

session._providers
['CPUExecutionProvider']
```
Triton inference server which also uses Onnx seems to work well with CUDA 12.1, wonder why Onnxruntime-gpu cannot support it?

**Comment by yuslepukhin** [comment]
> 2023-03-31 16:24:26.783840208 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:546 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.

CUDA is notorious for changing the set of DLLs that needs to load and the places where to look for them. Check your DLL search order and their location.

**Comment by yuslepukhin** [comment]
See https://github.com/microsoft/onnxruntime/issues/13658 first

**Comment by pranavsharma** [comment]
@junwang-wish ORT does *not* officially support CUDA 12 yet. In the case of Triton, they build ORT from source and made it work with CUDA 12 on Linux (see [this](https://github.com/microsoft/onnxruntime/pull/14659) and [this](https://github.com/microsoft/onnxruntime/pull/15135)), but the windows build still fails which is why this issue was filed. Feel free to contribute fixes for the Windows build.

**Comment by pranavsharma** [comment]
We're *not* producing nightly builds for cuda 12. You'll need to build it yourself. We only support CUDA 11.x for all nightlies and release pks. As I said Triton is completely different; they don't use any pkgs.

**Comment by junwang-wish** [comment]
Gotcha thanks, I will downgrade to CUDA 11.x for now.

**Comment by pranavsharma** [comment]
Just spoke to the customer. Deadline for this is May 5th.

**Comment by snnn** [comment]
@pranavsharma, now we are bound to one specific CUDA minor version. For example, the 1.14 release uses CUDA 11.6, then the binary doesn't work with CUDA 11.8. This one if we upgrade CUDA 11.8, all our existing customers need to do the same. When [junwang-wish](https://github.com/junwang-wish) needs CUDA 12, he will hit the same problem: the CUDA version provided by us might not the exactly the same as he wanted.  Do you plan to make it not so strict?

**Comment by snnn** [comment]
I just checked again, our prebuilt binaries should work fine with any CUDA version from 11.0 to 11.8(both inclusive). Though in the upcoming release we will build our code with CUDA 11.8, the binaries should continue work fine with CUDA 11.6 or below.

**Comment by pranavsharma** [comment]
@snnn there is no expectation to release CUDA 12.x binaries in the upcoming release (1.15). The only ask is to ensure that ORT builds with CUDA 12.x.

**Comment by tianleiwu** [comment]
@tanmayv25, please try out the fix.

**Comment by tanmayv25** [comment]
@tianleiwu  Thanks a lot for all the assistance. I can confirm that I was able to successfully build onnxruntime with cuda 12.1.

**Comment by tanmayv25** [comment]
@tianleiwu @pranavsharma  Can you share when the fix will be available in a release branch?

**Comment by pranavsharma** [comment]
23rd May. That's the tentative release date.

**Comment by junwang-wish** [comment]
@pranavsharma so I can use onnxruntime on any machines with CUDA12.1 tentatively on 23rd May 2023?

**Comment by pranavsharma** [comment]
> @pranavsharma so I can use onnxruntime on any machines with CUDA12.1 tentatively on 23rd May 2023?

Yes.

**Comment by snnn** [comment]
I have a PR that is related to this: https://github.com/microsoft/onnxruntime/pull/15781 . In the PR I updated one of our docker files to use CUDA 12.1, and it works fine.  Therefore I believe our code is compatible with CUDA 12.1. However,  the upcoming release ORT release, 1.15, will use CUDA 11.8 for all prebuilt packages. If you'd like to use CUDA 12.1 instead, please build it from source. And you can try it now. We have created the rel-1.15.0 release branch. Though the release tag is not created yet, most things are already ready.

**Comment by vadimkantorov** [comment]
@snnn By chance, are nightly now built against CUDA 12?

**Comment by snnn** [comment]
No. They are not.

**Comment by j4ro** [comment]
@snnn Is it planned to use cuda 12 in the next release and any estimate when we can expect next release? [Upcoming release roadmap](https://github.com/microsoft/onnxruntime/wiki/Upcoming-Release-Roadmap) is outdated.

**Comment by snnn** [comment]
No, the next release's official packages will be still built with CUDA 11.x.  However, you can build it from source with CUDA 12.x.
