### ISSUE TITLE
[Build] eigen patch: build error with --use_acl

### ISSUE THREAD

**Issue by moore-ch** [microsoft/onnxruntime#15248]
### Describe the issue

when cross compilation, patch error in cmake configure for eigen.

error message:
        /usr/bin/patch: unrecognized option '--ignore-space-change'

if I remove this option, the error message is:
        can't find file to patch at input line 4
        Perhaps you should have used the -p or --strip option?

so my question is:
1. my linux patch version is GNU patch 2.7.6, is higher version needed for option '--ignore-space-change'?
2. is the patch file under /workspace/features/onnxruntime/cmake/patches/eigen/Fix_Eigen_Build_Break.patch valid? I found the patch source file is under git_org/cmake/external/eigen/Eigen/src rather than build/_deps/eigen-src/Eigen/src

Thanks

### Target platform

Armv8a

### Build script

I refer to https://fs-eire.github.io/onnxruntime/docs/build/eps.html#arm-compute-library 
source cross compilation and configure ONNX Runtime with ACL support:

cmake ../onnxruntime-arm-upstream/cmake -DONNX_CUSTOM_PROTOC_EXECUTABLE=/usr/bin/protoc -Donnxruntime_RUN_ONNX_TESTS=OFF -Donnxruntime_GENERATE_TEST_REPORTS=ON -Donnxruntime_DEV_MODE=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 -Donnxruntime_USE_CUDA=OFF -Donnxruntime_USE_NSYNC=OFF -Donnxruntime_CUDNN_HOME= -Donnxruntime_USE_JEMALLOC=OFF -Donnxruntime_ENABLE_PYTHON=OFF -Donnxruntime_BUILD_CSHARP=OFF -Donnxruntime_BUILD_SHARED_LIB=ON -Donnxruntime_USE_EIGEN_FOR_BLAS=ON -Donnxruntime_USE_OPENBLAS=OFF -Donnxruntime_USE_ACL=ON -Donnxruntime_USE_DNNL=OFF -Donnxruntime_USE_MKLML=OFF -Donnxruntime_USE_OPENMP=ON -Donnxruntime_USE_TVM=OFF -Donnxruntime_USE_LLVM=OFF -Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF -Donnxruntime_USE_BRAINSLICE=OFF -Donnxruntime_USE_NUPHAR=OFF -Donnxruntime_USE_EIGEN_THREADPOOL=OFF -Donnxruntime_BUILD_UNIT_TESTS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo

### Error / output

cmake error message:
        /usr/bin/patch: unrecognized option '--ignore-space-change'

if I remove this option, the error message is:
        can't find file to patch at input line 4
        Perhaps you should have used the -p or --strip option?

**Comment by moore-ch** [comment]
any update?

thanks

**Comment by eltimen** [comment]
I have found a workaround: replace `${Patch_EXECUTABLE}` with `git apply` in the line
https://github.com/microsoft/onnxruntime/blob/698e9f71cd72ed6176938ff093b40e57f92cd681/cmake/external/eigen.cmake#L11
