### ISSUE TITLE
[Build] Issue installing onnxruntime in python 3.7 on mac M1

### ISSUE THREAD

**Issue by gracemcgrath** [microsoft/onnxruntime#15251]
### Issue installing onnxruntime in python 3.7 on mac M1

I am trying to install onnxruntime in pyenv virtual environment - Python 3.7.16 using `pip install onnxruntime` or `pip3 install onnxrutnime` 

I am using  macOS Moneterey on M1 chip. Was able to install onnx in this environment, and I was able to install onnxrutnime in my regular python environment (no virtual environment - Python 3.9) on the same computer. 

### Target platform

macOS M1 

### Build script

`pip install onnxruntime` or `pip3 install onnxrutnime` 

### Error / output

``` 
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime
```

**Comment by hariharans29** [comment]
https://github.com/microsoft/onnxruntime/pull/11591/: In the PR supporting Python wheels for apple silicon Macs, there was no support for Py 3.7 probably because Python 3.7 was due to stop getting security updates in June 2023.

CC: @snnn

**Comment by snnn** [comment]
See: "https://cibuildwheel.readthedocs.io/en/stable/faq/#apple-silicon"

Only CPython 3.8 and newer support universal2 and arm64 wheels.

**Comment by gracemcgrath** [comment]
Thank you, @snnn @hariharans29 this clears it up.
