### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.Fail when doing inference on a temp file?

### ISSUE THREAD

**Issue by lovettchris** [microsoft/onnxruntime#15295]
### Describe the issue

Weird error to do with running onnx inference on a tempfile:

```python
import tempfile
import onnxruntime as rt
import torch
from shutil import copyfile

device = 'cpu'
input_shape = (1, 3, 256, 256)
input_shapes = [input_shape]
rand_min, rand_max = (0.0, 1.0)
export_kwargs = {'opset_version': 11}

sample_inputs = tuple(
    [
        ((rand_max - rand_min) * torch.rand(*input_shape) + rand_min).type('torch.FloatTensor')
        for input_shape in input_shapes
    ]
)

sample_input = {f"input_{i}": inp.numpy() for i, inp in enumerate(sample_inputs)}

with tempfile.NamedTemporaryFile(delete=False) as tmp_file:
    copyfile('model.onnx', tmp_file.name)
    onnx_session = rt.InferenceSession(tmp_file.name)
    results = onnx_session.run(None, input_feed=sample_input)
    print(results[0].shape)
```
[model.zip](https://github.com/microsoft/onnxruntime/files/11117511/model.zip)

### To reproduce

See above code, if instead I operate on the `model.onnx` file it works fine, so there is some strange interplace between `rt.InferenceSession` and `tempfile.NamedTemporaryFile` ?

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

 1.14.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Execution Provider Library Version

CUDA 11.8

**Comment by pranavsharma** [comment]
This has nothing to do with onnxruntime. This is a quirk of Python and Windows. See this note from here https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile
```Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows).```

Following modification will make your script work just fine.
```
my_tmpfile_name = ""
with tempfile.NamedTemporaryFile(delete=False) as tmp_file:
    copyfile('model.onnx', tmp_file.name)
    my_tmpfile_name = tmp_file.name
    print("Temp file name: [",my_tmp_file.name,"]")

onnx_session = rt.InferenceSession(my_tmpfile_name)
results = onnx_session.run(None, input_feed=sample_input)
print(results)
```

**Comment by lovettchris** [comment]
I see, thanks, guess I'm creating my own os safe wrapper then:

```python
class TemporaryFiles
    """ Windows has a weird quirk where the tempfile.NamedTemporaryFile cannot be opened a second time. """
    def __init__(self):
        self.files_to_delete = []

    def get_temp_file(self) -> str:
        result = None
        with tempfile.NamedTemporaryFile(delete=False) as tmp:
            result = tmp.name
        self.files_to_delete += [result]
        return result

    def __enter__(self) -> TemporaryFiles:
        return self

    def __exit__(self, exc_type: type[BaseException], exc_val: BaseException, exc_tb: TracebackType) -> None:
        for name in self.files_to_delete:
            os.unlink(name)
        self.files_to_delete = []
```

I wonder how many billions of these exist out there now... pity python never fixed this.
