### ISSUE TITLE
[Feature Request] ORT web API to use WebGL texture as model input

### ISSUE THREAD

**Issue by erikvdplas** [microsoft/onnxruntime#15312]
### Describe the feature request
I would like to be able to run models directly on WebGL textures as input. Right now, the only possibility is to first render such a WebGL texture to bitmap, then copying it to a Float32Array which can then be used to initialize an ORT Tensor object, which internally is again copied back to a WebGL texture when used with the WebGL execution backend. All this copying adds quite some overhead, which cannot be neglected, especially in real-time applications. 

### Describe scenario use case
It is not uncommon for image models to work on webcam/streams/video feeds or in general WebGL data. In the case of video feeds, they can efficiently be copied to a WebGL buffer using the `texImage2D` method in a WebGL rendering context (by directly the HTMLVideoElement as the source).

If someone is willing to guide me through the process of correctly building the onnxruntime-web package from source locally, I could try to implement this feature myself... but maybe someone more skilled and familiar with the project could help out as well.

**Comment by hariharans29** [comment]
@fs-eire - Can tou please take a look ?

**Comment by fs-eire** [comment]
feature request: IO binding (webGL)

**Comment by erikvdplas** [comment]
@fs-eire any I was wondering if this issue is actively being worked on? I am also interested in contributing myself, but I'd need some guidance to dive into the project. If you'd be willing to help out that'd be great! :)

**Comment by fs-eire** [comment]
I am thinking about the API design for this feature. To generalize the requirement, I think it can be expand to:
- [API] add interfaces with type `Tensor` for enabling:
    - creating tensor instance from non CPU memory source
    - checking the data location/status ( is it on CPU/texture/GPUBuffer )
    - getting the data as-is, instead of always downloading to CPU
    - resource life-cycle management ( may with `SessionOptions` or `RunOptions` as well)

- Implementations for:
    - allow passing gpu data directly to executor (input, api, backend, inference session)
    - create correct mapping between the API tensor and internal tensor type.
    - pass through gpu data for (output, backend, inference session, texture manager)
    - [optional] possible webgl kernels for image pre-processing

I can start with a branch for the API part and share it out later

**Comment by fs-eire** [comment]
@erikvdplas I created a new PR for this issue. the PR is now in design reviewing. please feel free to comments on it
