### ISSUE TITLE
[Performance] Constant Folding not applied

### ISSUE THREAD

**Issue by tianleiwu** [microsoft/onnxruntime#15318]
### Describe the issue

In Beit model, constant folding are not applied to some branch like the following:

![image](https://user-images.githubusercontent.com/30328909/229252197-016df0d4-5737-4867-804b-1082bd088c02.png)

The branch of Resize does not depend on graph input, so constant-folding shall be applied but not.

### To reproduce

Use that attached model file (external data is not attached), and save optimized model using session option.

### Platform

Windows

### OS Version

windows 11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Model File

[model_opt_v3.zip](https://github.com/microsoft/onnxruntime/files/11127946/model_opt_v3.zip)

### Is this a quantized model?

No

**Comment by hariharans29** [comment]
Will take a look at this.
