### ISSUE TITLE
Type InferenceSession in the Python API

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxruntime#15334]
### Describe the issue

InferenceSession is untyped. To make it easier for users to understand we should add type annotations to it. 

### To reproduce

N/A

### Platform

Linux

### OS Version

NA

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

NA

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by hariharans29** [comment]
@justinchuby - Thanks. Would you be able to contribute the type annotations ?
