### ISSUE TITLE
Gather doesn't seem to support negative indexing

### ISSUE THREAD

**Issue by julien-c** [microsoft/onnxruntime#1533]
**Describe the bug**
Gather doesn't seem to support negative indexing, even though the [ONNX spec](https://github.com/onnx/onnx/blob/master/docs/Operators.md#gather) seems to allow it.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac os
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 0.4.0
- Python version: 3.7
- GPU model and memory: None

**To Reproduce**
```
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Node:  Status Message: indices element out of data bounds, idx=-1 data_dim=2
```

**Comment by hariharans29** [comment]
Hi @julien-c,

This was resolved by #1380. The upcoming release (coming in a day or two) should have this fix.

Thanks

**Comment by duli2012** [comment]
yes, at this point, we're not plan to support negative indexing for Gather.

**Comment by julien-c** [comment]
Ok, thanks for the clarification.

I think it might make it hard for PyTorch exports to run reliably (without
too much model specific work) because they typically use a lot of Gathers.

**Comment by skottmckay** [comment]
Can we push for an ONNX spec update? If this makes exporting from PyTorch easier that seems like a good reason to add support for negative indices, especially given the code change to support it is fairly trivial?

**Comment by fdwr** [comment]
Yeah, this feels more like a fundamental operator update (Gather-11), as my reading of the spec implies that only the `axis` may be negative [-r, r-1], whereas indices must be within the bounds of the tensor ("All index values are expected to be within bounds. It is an error if any of the index values are out of bounds").

**Comment by hariharans29** [comment]
Given this spec clarification in onnx - https://github.com/onnx/onnx/commit/36dc71107de25ccbaa02bf859a826bc9cd28595d, is it worthwhile to close this issue in ORT as the implementation is per spec ? If there is a requirement to support negative indices in Gather op, the requirement should be raised in ONNX and if there is consensus to support it, the op must be versioned as it is breaking change.

**Comment by hariharans29** [comment]
Closing this as ORT implements the op as per spec. 

Please open an issue in ONNX if you feel negative indexing support is required for the op. 

Please re-open this issue if you have more comments/require more clarifications.

Thanks!

CC: @faxu

**Comment by mxdilln** [comment]
Hi @julien-c 

What is the index referring to here (ie where does the -1 originate in the code)? I am getting the same error when trying to run inference, but can't trace the root of the -1.

Thanks
