### ISSUE TITLE
[Documentation] How to deal output of dynamic shape? (onnxruntime c++)

### ISSUE THREAD

**Issue by ly19940318** [microsoft/onnxruntime#15346]
### Describe the documentation issue

i have a model like this:
![image](https://user-images.githubusercontent.com/51161472/229712050-e8e6f0e4-cb5f-4421-a250-bb1d4b010b0b.png)

Both the input and output shape are dynamic.
The same model, in python I can get the correct predict result.
Use c++, I get the intput and output shape use API is :
```
	std::vector<int64_t> input_dims;
	std::vector<int64_t> output_dims;
	input_dims = session.GetInputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape();
	output_dims = session.GetOutputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape();
```
input_dims : (-1,3,-1,-1)
output_dims :(-1,-1,8)

Now the input shape has been modified :(1,3,1024,1024)

But code runs to` session.Run` crash:
```
        auto memory_info = Ort::MemoryInfo::CreateCpu(OrtAllocatorType::OrtArenaAllocator, \
									OrtMemType::OrtMemTypeDefault);
	std::vector<Ort::Value> input_tensors;
	input_tensors.emplace_back(Ort::Value::CreateTensor<float>(memory_info, blob.ptr<float>(), \
							blob.total(), input_dims.data(), input_dims.size()));
	assert(input_tensor.IsTensor());
	startTime = clock();
	auto output_tensors = session.Run(Ort::RunOptions{ nullptr }, input_node_names.data(), \
				input_tensors.data(), input_names.size(), output_names.data(), output_names.size());
	endTime = clock();
```
 How to solve this problem?
 Thanks for help.

**Comment by hariharans29** [comment]
`Now the input shape has been modified :(1,3,1024,1024)` - Did you modify the input shape of the model's input ?

For the **same** model, are you running identically shaped inputs in C++ and Python but getting different behavior ? If so, can you share minimal but complete repro code (instead of just the c++ snippet) for both Python and C++ ?

**Comment by ly19940318** [comment]
> `Now the input shape has been modified :(1,3,1024,1024)` - Did you modify the input shape of the model's input in the model ? Can you elaborate on this ?
> 
> For the **same** model, are you running identically shaped inputs in C++ and Python but getting different behavior ? If so, can you share minimal but complete repro code (instead of just the c++ snippet) for both Python and C++ ?

sorry,  my bad.
The model should give two inputs but i only give one in c++.
