### ISSUE TITLE
Can you support GCC4.8?

### ISSUE THREAD

**Issue by XSeanLiu** [microsoft/onnxruntime#1535]
Hi, I know that you do not support GCC 4.x and below version, also I have built onnxruntime with gcc6.5.
We have the plan to push onnxruntime to production environment, but we supply the plugins to other projects. In this way we cannot upgrade the production environment to gcc5+.
So do you have plan to support gcc4.8? It would be very helpful for us to use onnxruntime.

**Comment by snnn** [comment]
It should be safe to mix them together.

**Comment by XSeanLiu** [comment]
> It should be safe to mix them together.

Yep, we can compile the onnxruntime with gcc4.8 but we find that opencv static lib is releated to gcc compiler, which does not work when we use opencv built with gcc4.8.
If we use opencv built with gcc6.5, it may not work because we just supply plugins to other projects.

**Comment by linkerzhang** [comment]
ORT is built based on c++14. It uses some c++14 features. how much efforts will it take for you guys to upgrading to c++14 please?

**Comment by XSeanLiu** [comment]
> ORT is built based on c++14. It uses some c++14 features. how much efforts will it take for you guys to upgrading to c++14 please?
