### ISSUE TITLE
Get all layers (conv, max pool etc...) feature maps

### ISSUE THREAD

**Issue by JurajJakubov** [microsoft/onnxruntime#15376]
### Describe the issue

I am unable to find a way how to get all feature maps meaning feature maps for all possible layers like convolution, pooling layer. 

### To reproduce

This is my code

```
                var session = new InferenceSession(modelPath);

                var inputTensor = LoadImage(imagePath);

                var inputs = new List<NamedOnnxValue>
                {
                    NamedOnnxValue.CreateFromTensor("input.29", inputTensor)
                };

                var outputs = session.Run(inputs);
```

Is there any way how to get feature maps for conv, pooling layers?

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

Other / Unknown

**Comment by baijumeswani** [comment]
The intention here is to make each node output a graph output? Depending on your model, this might be too many outputs.

If this is the intention, you should make changes to the onnx model first before instantiating the `InferenceSession` with the model.

If you're building onnxruntime from source, you could enable some debug flags to dump the intermediate activations in the graph.

**Comment by baijumeswani** [comment]
> And according to your answer of i want to do that i need to edit model and add all for example convolution layers to output?

Yes, you will need to edit the model such that each feature map that you're interested in is a graph output. 

Here is untested python code that you can use to edit the model.

```py
model = onnx.load(model_path)
original_output_names = {output.name for output in model.graph.output}
outputs = model.graph.output
name_value_info_mapping = {value_info.name: value_info for value_info in model.graph.value_info}

op_types_of_interest = {"Conv": [0]} # map from op_type to list of indices of outputs to keep


for node in model.graph.node:
    if node.op_type in op_types_of_interest:
        for output_idx in op_types_of_interest[node.op_type]:
            if node[output_idx] not in original_output_names:
                if not node[output_idx] in name_value_info_mapping:
                    raise ValueError(f"Output {node[output_idx]} shape not found in value_info")
                
                outputs.append(name_value_info_mapping[node[output_idx]])


model.graph.output[:] = outputs

onnx.save(model, model_path)

...
session = InferenceSession(model_path,  ...)
```

Note that for graph outputs, shape information is needed. So, hopefully the model shape inference is done, or you have knowledge of the shape of the node output.

**Comment by JurajJakubov** [comment]
> > And according to your answer of i want to do that i need to edit model and add all for example convolution layers to output?
> 
> Yes, you will need to edit the model such that each feature map that you're interested in is a graph output.
> 
> Here is untested python code that you can use to edit the model.
> 
> ```python
> model = onnx.load(model_path)
> original_output_names = {output.name for output in model.graph.output}
> outputs = model.graph.output
> name_value_info_mapping = {value_info.name: value_info for value_info in model.graph.value_info}
> 
> op_types_of_interest = {"Conv": [0]} # map from op_type to list of indices of outputs to keep
> 
> 
> for node in model.graph.node:
>     if node.op_type in op_types_of_interest:
>         for output_idx in op_types_of_interest[node.op_type]:
>             if node[output_idx] not in original_output_names:
>                 if not node[output_idx] in name_value_info_mapping:
>                     raise ValueError(f"Output {node[output_idx]} shape not found in value_info")
>                 
>                 outputs.append(name_value_info_mapping[node[output_idx]])
> 
> 
> model.graph.output[:] = outputs
> 
> onnx.save(model, model_path)
> 
> ...
> session = InferenceSession(model_path,  ...)
> ```
> 
> Note that for graph outputs, shape information is needed. So, hopefully the model shape inference is done, or you have knowledge of the shape of the node output.

Thank you it seems to work. I done it earlier too but with all layers and i ended up with error. Now i tried only one layer (conv) and it worked and converted tensor to bitmap and saved to disk. Everythings works. Thank you. You saved my diploma thesis :D
