### ISSUE TITLE
Can't get the values out of bound output in c#???

### ISSUE THREAD

**Issue by pauldog** [microsoft/onnxruntime#15381]
### Describe the issue

Here is my code in c#:

```
OrtMemoryInfo memInfo = new OrtMemoryInfo("DML", OrtAllocatorType.DeviceAllocator, 0, OrtMemType.Default);
using (FixedBufferOnnxValue fixedValue = FixedBufferOnnxValue.CreateFromTensor(input_ids))
  {
      binding.BindInput("input_ids", fixedValue);
  }
  
  binding.BindOutputToDevice("output", memInfo);

  
  RunOptions options = new RunOptions { };

  session.RunWithBinding(options, binding);

  var ortValue = binding.GetOutputValues().First();
```

I'm stuck on how do I get the tensor values from ortValue? the OrtValue class doesn't seem to have any members.

In other words I just want to copy the outputs from the GPU to the CPU to read them.

In the examples such as [this.](https://gist.github.com/pranavsharma/939d93fc7291c5a1638bfa3b190d72e3) It doesn't show how they get the data out at the end! What's the point of running a session really fast if you can't get any data out?

Actually [here](https://fs-eire.github.io/onnxruntime/docs/performance/tune-performance.html) it says "c# will be supported in future releases". Does this mean it's impossible at the moment? 

### To reproduce

As above

### Platform

Windows

### OS Version

Windows 10

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.14

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

DirectML

**Comment by fdwr** [comment]
>In other words I just want to copy the outputs from the GPU to the CPU to read them.

I'm not that familiar with C# (mainly a C++ dev), but can you just the output returned from `Run` and read the first tensor rather than rather than using the `IOBinding`? e.g.

```
namespace OrtTestApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Begin...");

            SessionOptions sessionOptions = new SessionOptions();
            sessionOptions.LogSeverityLevel = OrtLoggingLevel.ORT_LOGGING_LEVEL_INFO;
            sessionOptions.GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_ALL; //  ORT_DISABLE_ALL;

            sessionOptions.AppendExecutionProvider_DML(0);
            sessionOptions.EnableMemoryPattern = false;
            InferenceSession onnxSession = new InferenceSession("squeezenet1.1-7.onnx", sessionOptions);

            //NamedOnnxValue
            var tensor = new DenseTensor<float>(new int[] {1,3,224,224});
            var inputs = new List<NamedOnnxValue> { NamedOnnxValue.CreateFromTensor<float>("data", tensor) };
            var output = onnxSession.Run(inputs);

            Console.WriteLine("Done");
            Console.WriteLine(output);
            var values = (output.ToList().First().Value as IEnumerable<float>).ToArray();
            foreach (var item in values)
            {
                Console.Write(item.ToString() + ",");
            }
        }
    }
}
```

**Comment by pauldog** [comment]
Yes that is what I had before, but I am trying to speed up my code. [And the documentation says](https://fs-eire.github.io/onnxruntime/docs/performance/tune-performance.html), if you are running on GPU, it is best to map the inputs and outputs to GPU memory. Especially if I'm running the session recursively. 

But then at the end I want to get the outputs back from the GPU.

[ In C++ there ](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/test/shared_lib/test_inference.cc)is a method or OrtValue called `GetTensorData<float>()` which gets the data from the ortvalue. But in C# it doesn't seem this has been implemented?

**Comment by baijumeswani** [comment]
I guess you could use the `AsTensor<float>()` method. [Here](https://github.com/microsoft/onnxruntime/blob/a7d321e9dc8eded098d8267162d84f24b14a7dad/csharp/test/Microsoft.ML.OnnxRuntime.Tests.Common/InferenceTest.cs#L1707-L1715) is an example usage from our C# tests.

**Comment by baijumeswani** [comment]
Here is the fixed link to that test file: https://github.com/microsoft/onnxruntime/blob/main/csharp/test/Microsoft.ML.OnnxRuntime.Tests.Common/OrtIoBindingAllocationTest.cs

**Comment by pauldog** [comment]
I solved my bottleneck a different way.

I just modified the LLM by adding output=output[:,-1,:], so now the output is truncated on the GPU. Any it only has to send the last token to the CPU.

This has sped things up considerably.

**Comment by yuslepukhin** [comment]
When you bind output on top of your memory, you are expected to have access to your memory.

**Comment by pauldog** [comment]
I don't think this binding will help speed up my inferences... but maybe it will help someone else.

**Comment by yuslepukhin** [comment]
binding does not help speeding up the inference. It helps to avoid copies when the data is already on device, so one does not have to copy it to a separate piece of memory.

Another scenario is a circular feeding of data. This when someone wants to feed output to input, they would quickly rebound output buffer to input buffer and vice versa.

If you just want to run inference on GPU and then get results on CPU, onnxruntime would copy both inputs and outputs as appropriate, no need for any special actions.

**Comment by pauldog** [comment]
Thanks yes, I realised that for a language model because I need the tokens on the CPU at each step, binding wouldn't give me any speed up. But for other cases I would like to keep the result on the GPU.

BTW are there any samples/documentation for taking the output of one model (bound to the GPU) and feeding it to the input of a second model? In c#?

**Comment by yuslepukhin** [comment]
> BTW are there any samples/documentation for taking the output of one model (bound to the GPU) and feeding it to the input of a second model? In c#?
> 

I do not think there is a documentation. The original use case dictated that both inputs and outputs shapes are known. Thus, both input and output memory are pre-allocated and the user have native (GPU in this case) pointers in their possession. So using output pointers, one can create a binding for another model and feed it as input.

Your use case, when the output shape is not known (you only specify the device), and you cannot pre-allocate is not covered at the moment, but it should be.

Our C# API needs work and classes with the name starting with `Ort*` represent an effort to make it at least as usable as other APIs. So far, there was no good reason to expose `OrtValue` although in our other APis it the first class citizen.

**Comment by yuslepukhin** [comment]
I will be adding some new API, that is `bound` to address the issue.

**Comment by nums11** [comment]
Closing as resolved.
