### ISSUE TITLE
[Performance] Necessary to call OrtApi::ReleaseSession ? 

### ISSUE THREAD

**Issue by cyrusbehr** [microsoft/onnxruntime#15384]
### Describe the issue

I have created a class which adds abstraction to onnxruntime capabilities and makes it easy to dynamical run inference on various models. The constructor loads the model, then there is an inference API method which can be called as many times as required, and then finally there is the destructor. 

I have defined my destroctor as follows:

```
OnnxruntimeEngine::~OnnxruntimeEngine() {
    m_ortApi.ReleaseSession(m_sessionPtr->release());
    m_ortApi.ReleaseEnv(m_envPtr->release());
    m_ortApi.ReleaseSessionOptions(m_sessionOptsPtr->release());
}
```

Where `m_ortApi` is of type `const OrtApi&`, `m_sessionPtr` if of type `std::unique_ptr<Ort::Session>`, `m_envPtr` is of type `std::unique_ptr<Ort::Env>`, and finally `m_sessionOptsPtr` is of type `std::unique_ptr<Ort::SessionOptions>`.

My question: Do I need to manually call the `OrtApi::ReleaseSession`, `OrtApi::ReleaseEnv`, and `OrtApi::ReleaseSessionOptions` methods like I am doing above? Or should I omit this? 

### To reproduce

See above

### Platform

Linux

### OS Version

Ubuntu 20.04.5 LTS

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

v1.13.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

### Is this a quantized model?

No

**Comment by cyrusbehr** [comment]
And just to add to the above, what is the proper way to release all CPU memory and pools? It seems that even after the above destuctor is called for all instances, there is still some memory retained.

**Comment by baijumeswani** [comment]
I see you're using the C++ api.

In that case, the `Release*` is managed by the class destructor (in this case `~Ort::Session` destructor will release the session, `~Ort::Env` will manage the release of the env and so on).

So, you don't need to call the release methods explicitly in your code.

**Comment by baijumeswani** [comment]
> And just to add to the above, what is the proper way to release all CPU memory and pools?

Any memory owned by the session will be released when the session is destructed.

> It seems that even after the above destuctor is called for all instances, there is still some memory retained.

If you could share your findings and analysis, we can investigate this further. But this should not be the case.

**Comment by snnn** [comment]
If you do not that, you might see crashes. You call the functions to ensure the related object will be released before your program's global objects start to destruct. If you don't call the functions, the destruction order may be wrong. However, if you decide to use  https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-terminateprocess to abort your process, you don't need to have this concern and you do not need to worry about memory leak at exit.

**Comment by cyrusbehr** [comment]
Great, thank you for the answers!
