### ISSUE TITLE
DirectML fails on model containing SequenceEmpty

### ISSUE THREAD

**Issue by yqzhishen** [microsoft/onnxruntime#15380]
### Describe the issue

I recently exported a model from PyTorch to ONNX where there is a `SequenceEmpty` node in it. It runs well on CPU, but it fails with DML.

### To reproduce

The original model that I exported is large and complicated, but I managed to reproduce the error with a minimum demo.

Here is the model: [model.zip](https://github.com/microsoft/onnxruntime/files/11160389/model.zip)

Here is the code that I exported and run the model:
```python
from typing import List

import numpy as np
import onnxruntime as ort
import torch.nn as nn
import torch.onnx
from torch import Tensor


class SequenceLoop(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Linear(32, 32)

    def forward(self, x: Tensor, loop: int) -> Tensor:
        seq: List[Tensor] = []
        for i in range(loop):
            x = self.net(x)
            seq.append(x)
        return torch.stack(seq).sum(0)


# export the model
dummy_inputs = (torch.randn(1, 32, dtype=torch.float32), 5)
torch.onnx.export(
    torch.jit.script(
        SequenceLoop(),
        example_inputs=[dummy_inputs]
    ),
    dummy_inputs,
    'sequence.onnx',
    input_names=['x', 'loop'],
    output_names=['y'],
    opset_version=15
)

# run the model
x = np.random.rand(1, 32).astype(np.float32)
loop = np.array(8).astype(np.int64)
session_cpu = ort.InferenceSession('sequence.onnx', providers=['CPUExecutionProvider'])
y_cpu = session_cpu.run(['y'], {'x': x, 'loop': loop})[0]  # <== ok
print(y_cpu.shape)
session_dml = ort.InferenceSession('sequence.onnx', providers=['DmlExecutionProvider'])
y_dml = session_dml.run(['y'], {'x': x, 'loop': loop})[0]  # <== fails
print(y_dml.shape)
```

The above code will raise an error with this message:
```text
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Loop node. Name:'/Loop' Status Message: Unsupported OrtValue type.
```

I guess the reason causing this error is that the sequence is empty at beginning, so TorchScript was unable to infer shapes of its elements, and just left a type information of `sequence<float32[?,?]>` in the graph. If I replace the list creation line with one element in it, like
```python
seq: List[Tensor] = [x]
```
the error is gone immediately.

However, as other EPs like CPU and CUDA works just fine on this model, I wonder if this is by design or is a bug of the DML ep.

### Platform

Windows 10

### OS Version

22H2 (19045.2728)

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

DirectML

**Comment by smk2007** [comment]
Hello, this issue should be resolved with this PR: https://github.com/microsoft/onnxruntime/pull/15239
