### ISSUE TITLE
[Web] ONNX model: TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by rbavery** [microsoft/onnxruntime#15388]
### Describe the issue

I'm trying to run inference with my own ONNX model that works when used from python. I have an index.html that opens an image, converts to ort.Tensor, moves the 4th channel of that tensor following [this example](https://onnxruntime.ai/docs/tutorials/web/classify-images-nextjs-github-template.html#imagehelperts), and then runs inference on the 3 channel Tensor

I get this error during `const results = await session.run(feeds);`

`failed to inference ONNX model: TypeError: Cannot read properties of undefined (reading 'data').`

This looks related to this, but I'm not using onnx runtime from node, I'm loading it with a script tag. It's also a different undefined variable, I'm able to create the inference session.
https://github.com/microsoft/onnxruntime/issues/10516

I've confirmed that the tensor that I pass in does have a data property defined

```
feeds.images
p {dims: Array(4), type: 'float32', data: Float32Array(3686400), size: 3686400}
```

```
feeds.images.data
Float32Array(3686400) [0.00027681663050316274, 0.00016916570893954486, 0.00007689350604778156, 0.0000922722028917633, 0.0001845444057835266, 0.00019992310262750834, 0.00015378701209556311, 0.0001845444057835266, 0.00023068051086738706, 0.0000922722028917633, 0.0002921953273471445, 0.00013840831525158137, ....
```

```
feeds.images.dims
(4) [1, 3, 960, 1280]
```

### To reproduce

1. clone https://github.com/rbavery/animl-onnx/tree/main
2. follow readme instructions to copy model weights, clone yolov5, and run export script
3. move model file to root of repo and name 'md_v5a.0.0.960.1280.onnx'
4. test index.html by opening 'input/sample-img-fox.jpg' in the repo

### Urgency

Any help is appreciated since I'm looking to demo this to a client, sooner is better, but no deadline

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

v1.14.0

### Execution Provider

Other / Unknown

**Comment by hariharans29** [comment]
Hi @fs-eire @guschmue - Can you please take a look at this ?

**Comment by shalvamist** [comment]
Hi @rbavery & @hariharans29,

This issue looks similar to [#15006](https://github.com/microsoft/onnxruntime/issues/15006).
Let me take a look at it, maybe the last fix didn't make it to the onnxruntime-web package yet.

I will update the thread with my progress in the coming days.

**Comment by fs-eire** [comment]
Does the console output the stacktrace when getting to the error: `failed to inference ONNX model: TypeError: Cannot read properties of undefined (reading 'data').` ?

**Comment by shalvamist** [comment]
Hi @rbavery,

I tried the steps described in the [repo](https://github.com/rbavery/animl-onnx/tree/main).
I am having issues with the model generation - after running the export script for yolo5 I get the error - 
"export.py: error: argument --imgsz/--img/--img-size: invalid int value: '(960,1280)'"

Is the input size critical to generate the issue ? 
can you share the onnx model that generates the error ?

Thanks

**Comment by rbavery** [comment]
Sorry I forgot that I updated the export script to accept non-square shapes and to include that script. I don't think it is critical to generating the issue. 

Here is the model @shalvamist: https://drive.google.com/file/d/1EPOofFTJx8ffZl6ARHnMbTJAAkGecoWT/view?usp=sharing

**Comment by rbavery** [comment]
> Does the console output the stacktrace when getting to the error: failed to inference ONNX model: TypeError: Cannot read properties of undefined (reading 'data'). ? It will be helpful to understand the root cause

I tried to get info on this, but I can't run the debugger now because of this issue. Did something possible update on the onnx package side?: https://github.com/microsoft/vscode/issues/179734

**Comment by shalvamist** [comment]
Hi @rbavery,

Thanks for sharing the model.
I tried it on my end using this script - 
```
<!DOCTYPE html>
<html>
    <header>
        <title>ONNX Runtime JavaScript examples: Quick Start - Web (using script tag)</title>
    </header>
    <body>
        <!-- import ONNXRuntime Web from CDN -->
        <script src="https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.min.js"></script>
        <script>
            // use an async context to call onnxruntime functions.
            async function main() {
                try {
                    // create a new session and load the specific model.
                    const options = { executionProviders: ['wasm'], graphOptimizationLevel: 'all' };   
                    const session = await ort.InferenceSession.create('./md_model.onnx', options);

                    // // prepare inputs. a tensor need its corresponding TypedArray as data
                    const dataA = Float32Array.from({length: 3686400}, () => Math.floor(Math.random() * 100));
                    const tensorA = new ort.Tensor('float32', dataA, [1,3,960,1280]);

                    // // prepare feeds. use model input names as keys.
                    const feeds = { images: tensorA };

                    // // feed inputs and run
                    const results = await session.run(feeds);

                } catch (e) {
                    document.write(`failed to inference ONNX model: ${e}.`);
                }
            }

            main();
        </script>
    </body>
</html>
```
I was able to run one inference using wasm (webgl - might have an issue. I am looking into it).
I think the update to the npm package might helped. Please let me know if you can see the same on your end.

**Comment by fs-eire** [comment]
> > Does the console output the stacktrace when getting to the error: failed to inference ONNX model: TypeError: Cannot read properties of undefined (reading 'data'). ? It will be helpful to understand the root cause
> 
> I tried to get info on this, but I can't run the debugger now because of this issue. Did something possible update on the onnx package side?: [microsoft/vscode#179734](https://github.com/microsoft/vscode/issues/179734)

If it is a VSCode issue, you can use browser's devtool to debug. it is less powerful than VSCode but should be able to identify the issue as long as you have the source map available in your debug server.

**Comment by rbavery** [comment]
Thanks for the tips! I think I found the issue.

I tried the cpu excecution provider and I still get the same error. the stacktrace from the dev console is here:

```
Failed to load resource: the server responded with a status of 404 (File not found)
```

however I think the breakpoint is actually happenin after inference. it happens after inference runs successfully
on this line `const dataC = results.c.data;`

I think this example is out of date then
```
https://github.com/microsoft/onnxruntime/blob/56ad68120e9beddd7c1b7a159dab59e75b6242fe/samples/nodejs/01_basic-usage/index.js#L27
```

for the wasm provider I also get the same error.

using `const dataC = results.output.data;` fixes the issue

**Comment by rbavery** [comment]
I'm actually getting the error when I make the assignment

` const dataC = results.c.data; `

even though I can access

`results.c.data`

Any ideas on why this assignment in the example and in this index.html isn't working?

**Comment by fs-eire** [comment]
I think I got where it went wrong.

So in the code snippet from https://github.com/rbavery/animl-onnx/blob/main/index.html,

```js
 const results = await session.run(feeds);

 // read from results
 const dataC = results.output.data;
```

here `output` in `results.output.data` is actually the model's output name (md_v5a.0.0.960.1280.onnx), and `results` is a JS object with model's output as keys and the tensor object as values.

In example code we use `const dataC = results.c.data;`, it's because the example model uses `a`, `b` as input names and `c` as output names.

**Comment by rbavery** [comment]
Got it, thank you! sounds like this was my misunderstanding, thank you for the help and clear explanation.
