### ISSUE TITLE
Model failed to load with error `InvalidArgument` & vector size check

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxruntime#15404]
### Describe the issue

When loading a valid model according to ONNX model checker, I get `onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)`

### To reproduce

```python
import onnx
import onnxruntime as ort
import numpy as np

input = """
   <
      ir_version: 8,
      opset_import: ["" : 18, "onnxscript.atenlib" : 1],
      producer_name: "pytorch",
      producer_version: "2.0.0"
   >
   torch_jit (float[2,3,4,4] input_0, int64[2] input_1) => (float[2,3,5,5] output) {
      output = onnxscript.atenlib.aten_upsample_bilinear2d <align_corners = 1> (input_0, input_1)
   }
   <
   domain: "onnxscript.atenlib",
   opset_import: ["" : 18]
   >
   aten_upsample_bilinear2d (self, output_size) => (return_val)
   {
      self_shape = Shape (self)
      starts = Constant <value_ints = [0]> ()
      ends = Constant <value_ints = [2]> ()
      batch_channel = Slice (self_shape, starts, ends)
      output_size_0 = Concat <axis = 0> (batch_channel, output_size)
      return_val = Resize <coordinate_transformation_mode = "align_corners", mode = "linear"> (self, , , output_size_0)
   }
"""

model = onnx.parser.parse_model(input)

model = onnx.shape_inference.infer_shapes(model)
onnx.checker.check_model(model, full_check=True)

serialized = model.SerializeToString()
session = ort.InferenceSession(serialized, providers=['CPUExecutionProvider'])
print("done")
```

### Platform

Linux

### OS Version

Ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.0.dev20230405002

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by gramalingam** [comment]
It looks like a bug [here](https://github.com/microsoft/onnxruntime/blob/d0cca91cfb1b4737efb2f198429439f91d2c2ee7/onnxruntime/core/graph/function_utils.cc#L162) ... this statement should be outside the enclosing if-statement.

**Comment by baijumeswani** [comment]
[gramalingam](https://github.com/gramalingam) I came to the same conclusion. Seems like that part of the code is not handling the variadic inputs for `Concat` well.

Would you be able to submit a PR to address this issue?

**Comment by yuslepukhin** [comment]
I think `std::vector::at()` is throwing as expected.

**Comment by gramalingam** [comment]
Created PR for the fix: https://github.com/microsoft/onnxruntime/pull/15409
