### ISSUE TITLE
onnxruntime::IExecutionFrame::GetOrCreateNodeOutputMLValue shape && tensor.Shape() == *shape was false. OrtValue shape verification failed. Current shape:{1,100} Requested shape:{1,96}

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#15402]
### Describe the issue

I have a model with nms output, the final output is dynamic.

Using python onnxruntime inference get dynamic output OK, but C++ get error:

```
onnxruntime::IExecutionFrame::GetOrCreateNodeOutputMLValue shape && tensor.Shape() == *shape was false. OrtValue shape verification failed. Current shape:{1,100} Requested shape:{1,96}
```

I can get the output tensor shape: `:ORTInferencer::infer:196] out: 0 shape: [1,100,5,]`

it was looks like normal, but why (where) there pops up a [1, 96] request shape?

How can I deal with it?

the C++ inference code essentially:

```
 Ort::MemoryInfo out_memory_info("Cpu", OrtDeviceAllocator, 0,
                                    OrtMemTypeDefault);
    binding_->BindOutput(outputNames[j], out_memory_info);

...

session.Run({}, *(binding_.get()));
    std::vector<Ort::Value> ort_outputs = binding_->GetOutputValues();
```

### To reproduce

C++ infer like:

```
 Ort::MemoryInfo out_memory_info("Cpu", OrtDeviceAllocator, 0,
                                    OrtMemTypeDefault);
    binding_->BindOutput(outputNames[j], out_memory_info);

...

session.Run({}, *(binding_.get()));
    std::vector<Ort::Value> ort_outputs = binding_->GetOutputValues();
```

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.14

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by jinfagang** [comment]
[rtmperson_nano.zip](https://github.com/microsoft/onnxruntime/files/11171529/rtmperson_nano.zip)
this is the model.

**Comment by hariharans29** [comment]
Do you use IOBinding in Python as well ? It is strange that a bug repros in C++ but not Python unless there is something specific to the API layers. FWIW- Do you mind sharing a minimal but complete C++ repro code (along with the working Python code) - the snippet you pasted makes sense but it would be nice to see what kind of inputs you were passing through.

**Comment by jinfagang** [comment]
@hariharans29 hello, I can share the python, actually **I dont know a formal way to infer in c++ for ort, there are at least 10 different written ways**, I pasted my python infer code here, can you try helpe me on your side with c++, to see if you can infer the model in c++ or not? 

```
import onnxruntime as ort

import cv2
import numpy as np
import sys


a = 'human-pose.jpg'
aa = cv2.imread(a)
aa = cv2.resize(aa, (320, 320))
aaa = np.array(aa).astype(np.float32) / 255.
aaa = np.transpose(aaa, [2, 1, 0])[None]

sess = ort.InferenceSession(sys.argv[1])

o = sess.run(None, {'input':aaa})
print(o)
print(o[0].shape)

```

can u give me a standared c++ calling way which can successfully infer above model I shared?

![human-pose](https://user-images.githubusercontent.com/21303438/230528215-91609e60-af87-43d0-972e-e8d33e653eff.jpg)

**Comment by hariharans29** [comment]
Can you expand on : "dont know a formal way to infer in c++ for ort, there are at least 10 different written ways" ?

There are samples here: https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx and there are unit tests [here](https://github.com/microsoft/onnxruntime/blob/9bb4e4bef4f472de29effe8e700c5c066815b42c/onnxruntime/test/shared_lib/test_inference.cc#L230) demonstrating use of the C++ API.

There have been multiple instances of people reporting that their image models run correctly with Python but not with C++. Such issues have almost always ended up with the cause being a quirk of the image pre-processing library they use in C++. You can search for similar issues in this repro and see if there are solutions. Unfortunately, we cannot help with the usage of the image pre-processing library in C++. What I would suggest is to ensure that the raw inputs being fed in via Python and C++ are **exactly the same** and if the outputs then look different, please share your C++ code for us to take a further look.

**Comment by jinfagang** [comment]
I have solved it, but I am not gonna post solution here. thank u!
