### ISSUE TITLE
import paddle.fluid & import onnxruntime  will be core_dump

### ISSUE THREAD

**Issue by wawltor** [microsoft/onnxruntime#1541]
We have a problem, we want to use paddle, and when import onnxruntime and paddle.fluid, it will be core_dump directly, how to work out this problem?

**Comment by snnn** [comment]
Are you saying this package: https://pypi.org/project/paddle/?

**Comment by snnn** [comment]
I guess adding "-Bsymbolic" to https://github.com/microsoft/onnxruntime/blob/master/cmake/onnxruntime.cmake could solve your problem.

**Comment by wawltor** [comment]
> I guess adding "-Bsymbolic" to https://github.com/microsoft/onnxruntime/blob/master/cmake/onnxruntime.cmake could solve your problem.

OK，is there some versions have make with adding "-Bsymbolic" ?

**Comment by snnn** [comment]
That's interesting. I can reproduce the bug but I don't know why it crashed.  If Paddle can hide their C++ symbols(like what onnxruntime and onnx does) then the problem will be most likely gone. 

It should related to https://github.com/pybind/pybind11/issues/1262

I'll downgrade our compiler version to match with Paddle. Let's see what would happen after that.

**Comment by snnn** [comment]
@faxu,  downgrade to C++11 may solve this.
