### ISSUE TITLE
[Build] fatal error: numpy/arrayobject.h: No such file or directory

### ISSUE THREAD

**Issue by jeyblu** [microsoft/onnxruntime#15423]
### Describe the issue

An error was encountered building the main branch. Error occurred with --build_wheel. Error didn't occur if this build option wasn't used.
commit 9bb4e4bef4f472de29effe8e700c5c066815b42c

### Target platform

Ubuntu 22.04

### Build script

./build.sh --config RelWithDebInfo --build_shared_lib --build_wheel --parallel --build_dir "build" --skip_tests

### Error / output

/home/user/onnxruntime/onnxruntime/python/onnxruntime_pybind_ortvalue.cc:11:10: fatal error: numpy/arrayobject.h: No such file or directory
   11 | #include <numpy/arrayobject.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/onnxruntime_pybind11_state.dir/build.make:132: CMakeFiles/onnxruntime_pybind11_state.dir/home/user/onnxruntime/onnxruntime/python/onnxruntime_pybind_ortvalue.cc.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
[ 93%] Building CXX object CMakeFiles/onnxruntime_test_all.dir/home/user/onnxruntime/onnxruntime/test/providers/cpu/nn/lrn_op_test.cc.o
[ 93%] Building CXX object CMakeFiles/onnxruntime_test_all.dir/home/user/onnxruntime/onnxruntime/test/providers/cpu/nn/max_roi_pool_op_test.cc.o
/home/user/onnxruntime/onnxruntime/python/onnxruntime_pybind_mlvalue.cc:11:10: fatal error: numpy/arrayobject.h: No such file or directory
   11 | #include <numpy/arrayobject.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/user/onnxruntime/onnxruntime/python/onnxruntime_pybind_state.cc:10:10: fatal error: numpy/arrayobject.h: No such file or directory
   10 | #include <numpy/arrayobject.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/onnxruntime_pybind11_state.dir/build.make:104: CMakeFiles/onnxruntime_pybind11_state.dir/home/user/onnxruntime/onnxruntime/python/onnxruntime_pybind_mlvalue.cc.o] Error 1
gmake[2]: *** [CMakeFiles/onnxruntime_pybind11_state.dir/build.make:160: CMakeFiles/onnxruntime_pybind11_state.dir/home/user/onnxruntime/onnxruntime/python/onnxruntime_pybind_state.cc.o] Error 1
[ 93%] Building CXX object CMakeFiles/onnxruntime_test_all.dir/home/user/onnxruntime/onnxruntime/test/providers/cpu/nn/pool_op_test.cc.o
/home/user/onnxruntime/onnxruntime/python/onnxruntime_pybind_iobinding.cc:11:10: fatal error: numpy/arrayobject.h: No such file or directory
   11 | #include <numpy/arrayobject.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[ 93%] Building CXX object CMakeFiles/onnxruntime_test_all.dir/home/user/onnxruntime/onnxruntime/test/providers/cpu/nn/qlinearconv_op_test.cc.o
gmake[2]: *** [CMakeFiles/onnxruntime_pybind11_state.dir/build.make:90: CMakeFiles/onnxruntime_pybind11_state.dir/home/user/onnxruntime/onnxruntime/python/onnxruntime_pybind_iobinding.cc.o] Error 1
[ 94%] Building CXX object CMakeFiles/onnxruntime_test_all.dir/home/user/onnxruntime/onnxruntime/test/providers/cpu/nn/shrink_test.cc.o
/home/user/onnxruntime/onnxruntime/python/onnxruntime_pybind_sparse_tensor.cc:11:10: fatal error: numpy/arrayobject.h: No such file or directory
   11 | #include <numpy/arrayobject.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/onnxruntime_pybind11_state.dir/build.make:146: CMakeFiles/onnxruntime_pybind11_state.dir/home/user/onnxruntime/onnxruntime/python/onnxruntime_pybind_sparse_tensor.cc.o] Error 1

### GCC / Compiler Version

gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

**Comment by jeyblu** [comment]
Issue resolved after `sudo apt install python3-numpy`

**Comment by danny1222** [comment]
I meet the issue when compiling in windows, can you give any suggestion?

**Comment by jeyblu** [comment]
Install numpy if it's not installed.

**Comment by bluejack** [comment]
Do you need to symlink the numpy headers somehow? installing this via sudo apt install did not resolve this issue...
