### ISSUE TITLE
iobinding question

### ISSUE THREAD

**Issue by hanzz2007** [microsoft/onnxruntime#15438]
@dashesy If you've inputs on the CPU and want them to be on the GPU prior to calling Run, you need to bind each input and then call SynchronizeBoundInputs. BindInput only queues the copy operation. As stated in the C API doc, SynchronizeBoundInputs may be a no-op for some providers, but for CUDA it waits until all the input cross-device copies have been completed; it's a blocking call. So, you must call it if you intend the copies to be completed prior to Run. If you change the bound input value after Sync has been called, well, you won't see the changed value on the GPU. As for your last question, the answer is yes for now.

_Originally posted by @pranavsharma in https://github.com/microsoft/onnxruntime/issues/11133#issuecomment-1335999268_
 
Hi  @pranavsharma, I have 2 questions,  When I use CUDA ep with iobinding:
Q1: If I called iobinding.bind_input(<ortvalue_on_cpu>) before session.run without iobinding.sync_inputs be called,  the  H2D copy is queued.  The first cuda kernel will always see the right data,  because both H2D copy and the kernel is on same stream, is that true?
Q2: If I called iobinding.bind_output(<cuda_device>), and when after the session.run do I need call iobinding.sync_outputs to make sure the output data on device is ready to access(since the last kernel been called async)?
If the answer is YES, I see the sync_outputs use `cudaDeviceSync`, it seems a heavy cost operation, because it waits for the whole device not just the cuda stream being used.

**Comment by hanzz2007** [comment]
Here is my understanding of the advantages of iobinding( all based on cuda ep): 
U1: If my input ortvalue is on CPU device,  bindinput(ortvalue) will copy input to gpu immediatly and no copy operation in session.run. Without iobinding the input is copied in session.run so the run time is longer. 
That is the only difference between iobinding with no iobinding
U2: If my input ortvalue is on the same GPU device, there is no difference between them.

U3: If my output ortvalue is on the same GPU device, even without iobinding still no copy here, there is no difference between with them. Because session.run will always use user's output ortvalue as graph output buffer if device match. The only disadvantage is  I need to calculate the output shape and allocate device memory myself before session.run called.

**Comment by pranavsharma** [comment]
> Q1: If I called iobinding.bind_input(<ortvalue_on_cpu>) before session.run without iobinding.sync_inputs be called, the H2D copy is queued. The first cuda kernel will always see the right data, because both H2D copy and the kernel is on same stream, is that true?

No. Queued doesn't necessarily mean copied. Sync ensures that it's copied.

> Q2: If I called iobinding.bind_output(<cuda_device>), and when after the session.run do I need call iobinding.sync_outputs to make sure the output data on device is ready to access(since the last kernel been called async)?

Yes, currently we're calling cudaDeviceSynchronize as seen [here](https://github.com/microsoft/onnxruntime/blob/71a4e7eb97e842e1dfc419d75ffef811f721e5ad/onnxruntime/core/providers/cuda/cuda_execution_provider.cc#L381-L384)

Your understanding in [this comment](https://github.com/microsoft/onnxruntime/issues/15438#issuecomment-1501350607) is correct.

**Comment by hanzz2007** [comment]
> > Q1: If I called iobinding.bind_input(<ortvalue_on_cpu>) before session.run without iobinding.sync_inputs be called, the H2D copy is queued. The first cuda kernel will always see the right data, because both H2D copy and the kernel is on same stream, is that true?
> 
> No. Queued doesn't necessarily mean copied. Sync ensures that it's copied. Since DataTransfer use the same compute stream with cuda ep, it is should be safe to skip sync

I recheck the newest repo,  in 1.13.x  `datatransfer.copy_tensor` use the same compute stream (use the kDefaultStream) with cuda ep, so data should be ready before kernel launch.  While in in 1.14.x there comes in `datatransfer.copy_tensor_async` and iobinding.bindinput use the async one, as you said `Queued doesn't necessarily mean copied` may happen
