### ISSUE TITLE
[Build] 

### ISSUE THREAD

**Issue by PengPeng-JunJun** [microsoft/onnxruntime#15447]
### Describe the issue

My system is Win10,.When I used VS2015 build project, the system build error.I used version is cpu and make sure set right.I think the reason maybe coding error.Please help me.

### Urgency

yes

### Target platform

windows 10 64bit Microsoft Windows 

### Build script

I download the release from github.The version is onnxruntime-win-x64-1.14.1.
when I include the head file onnxruntime_cxx_api.h, system say error.

### Error / output

>E:\VC_Projects_V15\onnxruntime-win-x64-1.14.1\include\onnxruntime_cxx_api.h(412): error C2059: 语法错误:“{”
1>E:\VC_Projects_V15\onnxruntime-win-x64-1.14.1\include\onnxruntime_cxx_api.h(412): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>E:\VC_Projects_V15\onnxruntime-win-x64-1.14.1\include\onnxruntime_cxx_api.h(425): error C2612: 基/成员初始值设定项列表中的非法后缀“<class-head>”
1>E:\VC_Projects_V15\onnxruntime-win-x64-1.14.1\include\onnxruntime_cxx_api.h(1805): warning C4081: 应输入“)”；找到“字符串”
1>e:\vc_projects_v15\onnxruntime-win-x64-1.14.1\include\onnxruntime_cxx_inline.h(13): fatal error C1903: 无法从以前的错误中恢复；正在停止编译
1>  “C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe”中的内部编译器错误

### Visual Studio Version

VS2015

**Comment by snnn** [comment]
We no longer support VS2015.

**Comment by PengPeng-JunJun** [comment]
OK I know that. Please tell me which version support vs2015, I can download.
And I want to download onnxruntime-1.8.0, but can not ,can you help me?

**Comment by snnn** [comment]
You can find onnxruntime-1.8.0 from https://github.com/microsoft/onnxruntime/releases . There is no onnx runtime version that can support VS2015. The ONNX project was started in 2017. At that time VS 2017 was already available, so we chose VS2017 as the starting point.

**Comment by pankovnazar** [comment]
@snnn Is there any way to build onnxruntime with VS2017 and use it in VS2015 project through onnxruntime_c_api.h? I mean with static linking
