### ISSUE TITLE
Examples and support custom ops in C#

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#1545]
**Is your feature request related to a problem? Please describe.**
I would like to register a custom kernel in C#

**System information**
- ONNX Runtime version (you are using): 0.4.0

**Describe the solution you'd like**
Support custom ops in C#: the kernel will be compiled C++ dll but the runtime will be C#

**Describe alternatives you've considered**
Recompile ORT

**Comment by faxu** [comment]
Thanks for the suggestion. This is not supported at the moment and will be considered for future releases.

**Comment by faxu** [comment]
This should now be available.
