### ISSUE TITLE
[Build] I am getting an error for building onxxruntime for old project

### ISSUE THREAD

**Issue by xiaotiane33** [microsoft/onnxruntime#15457]
### Describe the issue

cmake version 3.20.0
cuda 10.2
cudnn 8.0.3
onnxruntime 1.5.2
nvidia 1080ti

### Urgency

it is very urgent.

### Target platform

centos 7.6

### Build script

./build.sh --skip_tests --build_dir /onnxruntime/onnxruntime-v1.5.2/build/Linux/CPU/static --config MinSizeRel --parallel

### Error / output

[ 60%] Building CXX object CMakeFiles/onnxruntime_providers.dir/onnxruntime/onnxruntime-v1.5.2/onnxruntime/core/providers/cpu/controlflow/utils.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_providers.dir/onnxruntime/onnxruntime-v1.5.2/onnxruntime/core/providers/cpu/cpu_execution_provider.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_providers.dir/onnxruntime/onnxruntime-v1.5.2/onnxruntime/core/providers/cpu/cpu_provider_factory.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_providers.dir/onnxruntime/onnxruntime-v1.5.2/onnxruntime/core/providers/cpu/generator/constant_of_shape.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_providers.dir/onnxruntime/onnxruntime-v1.5.2/onnxruntime/core/providers/cpu/generator/random.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_providers.dir/onnxruntime/onnxruntime-v1.5.2/onnxruntime/core/providers/cpu/generator/range.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_providers.dir/onnxruntime/onnxruntime-v1.5.2/onnxruntime/core/providers/cpu/math/clip.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_providers.dir/onnxruntime/onnxruntime-v1.5.2/onnxruntime/core/providers/cpu/math/cumsum.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_providers.dir/onnxruntime/onnxruntime-v1.5.2/onnxruntime/core/providers/cpu/math/det.cc.o
[ 60%] Building CXX object CMakeFiles/onnxruntime_providers.dir/onnxruntime/onnxruntime-v1.5.2/onnxruntime/core/providers/cpu/math/einsum.cc.o
[ 61%] Building CXX object CMakeFiles/onnxruntime_providers.dir/onnxruntime/onnxruntime-v1.5.2/onnxruntime/core/providers/cpu/math/einsum_utils/einsum_auxiliary_ops.cc.o
/onnxruntime/onnxruntime-v1.5.2/onnxruntime/core/providers/cpu/generator/random.cc: In function ‘onnxruntime::common::Status onnxruntime::RandomNormalCompute(float, float, std::default_random_engine&, onnx::TensorProto::DataType, onnxruntime::Tensor&)’:
/onnxruntime/onnxruntime-v1.5.2/onnxruntime/core/providers/cpu/generator/random.cc:275:15: error: ‘*((void*)& distribution +16)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
 static Status RandomNormalCompute(float mean, float scale,
               ^
cc1plus: all warnings being treated as errors
gmake[2]: *** [CMakeFiles/onnxruntime_providers.dir/onnxruntime/onnxruntime-v1.5.2/onnxruntime/core/providers/cpu/generator/random.cc.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/onnxruntime_providers.dir/all] Error 2
gmake: *** [all] Error 2
Traceback (most recent call last):
  File "/onnxruntime/onnxruntime-v1.5.2/tools/ci_build/build.py", line 1794, in <module>
    sys.exit(main())
  File "/onnxruntime/onnxruntime-v1.5.2/tools/ci_build/build.py", line 1732, in main
    build_targets(args, cmake_path, build_dir, configs, args.parallel, args.target)
  File "/onnxruntime/onnxruntime-v1.5.2/tools/ci_build/build.py", line 943, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/onnxruntime/onnxruntime-v1.5.2/tools/ci_build/build.py", line 434, in run_subprocess
    env=my_env, shell=shell)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/cmake-3.24.4/bin/cmake', '--build', '/onnxruntime/onnxruntime-v1.5.2/build/Linux/CPU/static/MinSizeRel', '--config', 'MinSizeRel', '--', '-j6']' returned non-zero exit status 2.

### GCC / Compiler Version

gcc4.8.5

**Comment by wschin** [comment]
It's a compiler warning. You can turn it off or modify `onnxruntime/core/providers/cpu/generator/random.cc` to avoid uninitialized variables.
