### ISSUE TITLE
Official c api build dll and lib do not include function of OrtGetDimensions

### ISSUE THREAD

**Issue by qw2208** [microsoft/onnxruntime#1550]
**Describe the bug**
The official build of c lib and dll do not have ortgetdimensions. I do not find the function after running `dumpbin.exe onnxruntime.lib`. Is the official build correct? Or if I have to use capi, I have to build by myself?

**Comment by snnn** [comment]
Please check https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/symbols.txt

Is the symbol there? If not, it's a bug

**Comment by qw2208** [comment]
I just downloaded the zip package from [link](https://github.com/microsoft/onnxruntime/releases/download/v0.4.0/onnxruntime-win-x64-0.4.0.zip). Run the command: `dumpbin.exe /EXPORTS (Path)\onnxruntime.lib`.

Got the following results:
![WeChat Screenshot_20190802133558](https://user-images.githubusercontent.com/24438413/62346918-79e7d080-b52a-11e9-9033-a9cc6e6f8f41.png)

Seems it does NOT have the function of OrtGetDimensionsCount, which differs from your link.

**Comment by snnn** [comment]
Would you try our latest release instead?https://github.com/microsoft/onnxruntime/releases/download/v0.5.0/onnxruntime-win-x64-0.5.0.zip

**Comment by qw2208** [comment]
Then the link from the main page is not the newest. Thanks.

**Comment by hoaquocphan** [comment]
Hello All,
CC @qw2208  @snnn 
currently I have the same issue as you.

`my_code.cpp:220:3: error: 'OrtCreateEnv' was not declared in this scope
   OrtCreateEnv(ORT_LOGGING_LEVEL_WARNING, "test", &env);
   ^~~~~~~~~~~~
my_code.cpp:220:3: note: suggested alternative: 'OrtEnv'
   OrtCreateEnv(ORT_LOGGING_LEVEL_WARNING, "test", &env);
   ^~~~~~~~~~~~
   OrtEnv
my_code.cpp:224:37: error: 'OrtCreateSessionOptions' was not declared in this scope
  OrtSessionOptions* session_options=OrtCreateSessionOptions();
`
source code info:
+ repo: https://github.com/microsoft/onnxruntime.git
+ branch: rel-1.0.0
I have searched these functions/structs in the source code and there are no any define for these function/structs.
I don't know which file define them.

So anyone know this issue, Please help me.

Thanks all.

**Comment by snnn** [comment]
The API was changed.  Please refer https://github.com/microsoft/onnxruntime/pull/3050 as an example of how to update your existing code.

**Comment by hoaquocphan** [comment]
Hi @snnn 

Thank you very much for your support, 
I can fix many issue such as **OrtGetErrorMessage => g_ort->GetErrorMessage**
But there are some function/struct related to **Allocator** doesn't have the alternative:
```
OrtSetSessionThreadPoolSize
OrtCreateDefaultAllocator
OrtReleaseAllocator
OrtAllocatorInfo
OrtCreateCpuAllocatorInfo
OrtReleaseAllocatorInfo
```
So could you please help me for this remain issue.
Thank again.

**Comment by snnn** [comment]
OrtCreateDefaultAllocator -> GetAllocatorWithDefaultOptions
OrtSetSessionThreadPoolSize -> SetIntraOpNumThreads and SetInterOpNumThreads

**Comment by hoaquocphan** [comment]
Hi @snnn 

Thank you very much for your support.
I fixed all these issues.
