### ISSUE TITLE
[Build] Unable to use Ubuntu Server 20.04 LTS AMD64 custom build android

### ISSUE THREAD

**Issue by ZTMIDGO** [microsoft/onnxruntime#15528]
### Describe the issue

I tried using Ubuntu Server 20.04 LTS AMD64 custom build android, here's my code：

Docker version 23.0.3, build 3e7cbfd

git clone --recursive https://github.com/microsoft/onnxruntime
cd onnxruntime
git checkout v1.14.1

python ./tools/android_custom_build/build_custom_android_package.py \
   --onnxruntime_branch_or_tag v1.14.1 \
   --include_ops_by_config /home/ubuntu/project/required_operators.config \
   --build_settings ./tools/ci_build/github/android/default_mobile_aar_build_settings.json \
   /home/ubuntu/project/out

Fail:
CMake Error at CMakeLists.txt:5 (cmake_minimum_required):
CMake 3.24 or higher is required.  You are running version 3.21.0

### Target platform

v1.14.1

### Build script

git clone --recursive https://github.com/microsoft/onnxruntime
cd onnxruntime
git checkout v1.14.1

python ./tools/android_custom_build/build_custom_android_package.py \
   --onnxruntime_branch_or_tag v1.14.1 \
   --include_ops_by_config /home/ubuntu/project/required_operators.config \
   --build_settings ./tools/ci_build/github/android/default_mobile_aar_build_settings.json \
   /home/ubuntu/project/out

### Error / output

[174/174] Creating executable symlink protoc
2023-04-15 15:53:58,528 util.run [DEBUG] - Subprocess completed. Return code: 0
2023-04-15 15:53:58,529 build [INFO] - Generating CMake build tree
2023-04-15 15:53:58,529 util.run [INFO] - Running subprocess in '/workspace/shared/output/intermediates/armeabi-v7a/Release'
  /usr/bin/cmake /workspace/onnxruntime/cmake -Donnxruntime_RUN_ONNX_TESTS=OFF -Donnxruntime_GENERATE_TEST_REPORTS=ON -DPython_EXECUTABLE=/usr/bin/python3 -DPYTHON_EXECUTABLE=/usr/bin/python3 -Donnxruntime_USE_MIMALLOC=OFF -Donnxruntime_ENABLE_PYTHON=OFF -Donnxruntime_BUILD_CSHARP=OFF -Donnxruntime_BUILD_JAVA=ON -Donnxruntime_BUILD_NODEJS=OFF -Donnxruntime_BUILD_OBJC=OFF -Donnxruntime_BUILD_SHARED_LIB=ON -Donnxruntime_BUILD_APPLE_FRAMEWORK=OFF -Donnxruntime_USE_DNNL=OFF -Donnxruntime_USE_NNAPI_BUILTIN=ON -Donnxruntime_USE_RKNPU=OFF -Donnxruntime_USE_LLVM=OFF -Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF -Donnxruntime_USE_VITISAI=OFF -Donnxruntime_USE_TENSORRT=OFF -Donnxruntime_SKIP_AND_PERFORM_FILTERED_TENSORRT_TESTS=ON -Donnxruntime_USE_TENSORRT_BUILTIN_PARSER=OFF -Donnxruntime_TENSORRT_PLACEHOLDER_BUILDER=OFF -Donnxruntime_USE_TVM=OFF -Donnxruntime_TVM_CUDA_RUNTIME=OFF -Donnxruntime_TVM_USE_HASH=OFF -Donnxruntime_USE_MIGRAPHX=OFF -Donnxruntime_CROSS_COMPILING=OFF -Donnxruntime_DISABLE_CONTRIB_OPS=OFF -Donnxruntime_DISABLE_ML_OPS=ON -Donnxruntime_DISABLE_RTTI=ON -Donnxruntime_DISABLE_EXCEPTIONS=ON -Donnxruntime_MINIMAL_BUILD=ON -Donnxruntime_EXTENDED_MINIMAL_BUILD=ON -Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF -Donnxruntime_REDUCED_OPS_BUILD=ON -Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF -Donnxruntime_USE_DML=OFF -Donnxruntime_USE_WINML=OFF -Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF -Donnxruntime_USE_TELEMETRY=OFF -Donnxruntime_ENABLE_LTO=OFF -Donnxruntime_USE_ACL=OFF -Donnxruntime_USE_ACL_1902=OFF -Donnxruntime_USE_ACL_1905=OFF -Donnxruntime_USE_ACL_1908=OFF -Donnxruntime_USE_ACL_2002=OFF -Donnxruntime_USE_ARMNN=OFF -Donnxruntime_ARMNN_RELU_USE_CPU=ON -Donnxruntime_ARMNN_BN_USE_CPU=ON -Donnxruntime_ENABLE_NVTX_PROFILE=OFF -Donnxruntime_ENABLE_TRAINING=OFF -Donnxruntime_ENABLE_TRAINING_OPS=OFF -Donnxruntime_ENABLE_TRAINING_APIS=OFF -Donnxruntime_ENABLE_CPU_FP16_OPS=OFF -Donnxruntime_USE_NCCL=OFF -Donnxruntime_BUILD_BENCHMARKS=OFF -Donnxruntime_USE_ROCM=OFF -DOnnxruntime_GCOV_COVERAGE=OFF -Donnxruntime_USE_MPI=ON -Donnxruntime_ENABLE_MEMORY_PROFILE=OFF -Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF -Donnxruntime_BUILD_WEBASSEMBLY=OFF -Donnxruntime_BUILD_WEBASSEMBLY_STATIC_LIB=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING=ON -Donnxruntime_ENABLE_WEBASSEMBLY_API_EXCEPTION_CATCHING=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_THROWING=ON -Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_PROFILING=OFF -Donnxruntime_ENABLE_EAGER_MODE=OFF -Donnxruntime_ENABLE_LAZY_TENSOR=OFF -Donnxruntime_ENABLE_EXTERNAL_CUSTOM_OP_SCHEMAS=OFF -Donnxruntime_ENABLE_CUDA_PROFILING=OFF -Donnxruntime_ENABLE_ROCM_PROFILING=OFF -Donnxruntime_USE_XNNPACK=OFF -Donnxruntime_USE_CANN=OFF -DCMAKE_TOOLCHAIN_FILE=/opt/android-sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-21 -DANDROID_ABI=armeabi-v7a -DANDROID_MIN_SDK=21 -DONNX_CUSTOM_PROTOC_EXECUTABLE=/workspace/shared/output/intermediates/armeabi-v7a/host_protoc/protoc -DCMAKE_TLS_VERIFY=ON -DFETCHCONTENT_QUIET=OFF -Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF -G Ninja -Donnxruntime_ENABLE_MEMLEAK_CHECKER=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/workspace/shared/output/intermediates/armeabi-v7a/Release/installed

CMake Error at CMakeLists.txt:5 (cmake_minimum_required):
CMake 3.24 or higher is required.  You are running version 3.21.0

-- Configuring incomplete, errors occurred!
See also "/workspace/shared/output/intermediates/armeabi-v7a/Release/CMakeFiles/CMakeOutput.log".
See also "/workspace/shared/output/intermediates/armeabi-v7a/Release/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 2737, in <module>
    sys.exit(main())
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 2621, in main
    cmake_extra_args,
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 1350, in generate_build_tree
    cuda_home=cuda_home,
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 764, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/workspace/onnxruntime/tools/python/util/run.py", line 57, in run
    shell=shell,
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '/workspace/onnxruntime/cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-DPython_EXECUTABLE=/usr/bin/python3', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-Donnxruntime_USE_MIMALLOC=OFF', '-Donnxruntime_ENABLE_PYTHON=OFF', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_JAVA=ON', '-Donnxruntime_BUILD_NODEJS=OFF', '-Donnxruntime_BUILD_OBJC=OFF', '-Donnxruntime_BUILD_SHARED_LIB=ON', '-Donnxruntime_BUILD_APPLE_FRAMEWORK=OFF', '-Donnxruntime_USE_DNNL=OFF', '-Donnxruntime_USE_NNAPI_BUILTIN=ON', '-Donnxruntime_USE_RKNPU=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_VITISAI=OFF', '-Donnxruntime_USE_TENSORRT=OFF', '-Donnxruntime_SKIP_AND_PERFORM_FILTERED_TENSORRT_TESTS=ON', '-Donnxruntime_USE_TENSORRT_BUILTIN_PARSER=OFF', '-Donnxruntime_TENSORRT_PLACEHOLDER_BUILDER=OFF', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_TVM_CUDA_RUNTIME=OFF', '-Donnxruntime_TVM_USE_HASH=OFF', '-Donnxruntime_USE_MIGRAPHX=OFF', '-Donnxruntime_CROSS_COMPILING=OFF', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_DISABLE_ML_OPS=ON', '-Donnxruntime_DISABLE_RTTI=ON', '-Donnxruntime_DISABLE_EXCEPTIONS=ON', '-Donnxruntime_MINIMAL_BUILD=ON', '-Donnxruntime_EXTENDED_MINIMAL_BUILD=ON', '-Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF', '-Donnxruntime_REDUCED_OPS_BUILD=ON', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=OFF', '-Donnxruntime_USE_WINML=OFF', '-Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxruntime_USE_ACL=OFF', '-Donnxruntime_USE_ACL_1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_USE_ACL_2002=OFF', '-Donnxruntime_USE_ARMNN=OFF', '-Donnxruntime_ARMNN_RELU_USE_CPU=ON', '-Donnxruntime_ARMNN_BN_USE_CPU=ON', '-Donnxruntime_ENABLE_NVTX_PROFILE=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_ENABLE_TRAINING_OPS=OFF', '-Donnxruntime_ENABLE_TRAINING_APIS=OFF', '-Donnxruntime_ENABLE_CPU_FP16_OPS=OFF', '-Donnxruntime_USE_NCCL=OFF', '-Donnxruntime_BUILD_BENCHMARKS=OFF', '-Donnxruntime_USE_ROCM=OFF', '-DOnnxruntime_GCOV_COVERAGE=OFF', '-Donnxruntime_USE_MPI=ON', '-Donnxruntime_ENABLE_MEMORY_PROFILE=OFF', '-Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF', '-Donnxruntime_BUILD_WEBASSEMBLY=OFF', '-Donnxruntime_BUILD_WEBASSEMBLY_STATIC_LIB=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING=ON', '-Donnxruntime_ENABLE_WEBASSEMBLY_API_EXCEPTION_CATCHING=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_THROWING=ON', '-Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_PROFILING=OFF', '-Donnxruntime_ENABLE_EAGER_MODE=OFF', '-Donnxruntime_ENABLE_LAZY_TENSOR=OFF', '-Donnxruntime_ENABLE_EXTERNAL_CUSTOM_OP_SCHEMAS=OFF', '-Donnxruntime_ENABLE_CUDA_PROFILING=OFF', '-Donnxruntime_ENABLE_ROCM_PROFILING=OFF', '-Donnxruntime_USE_XNNPACK=OFF', '-Donnxruntime_USE_CANN=OFF', '-DCMAKE_TOOLCHAIN_FILE=/opt/android-sdk/ndk/24.0.8215888/build/cmake/android.toolchain.cmake', '-DANDROID_PLATFORM=android-21', '-DANDROID_ABI=armeabi-v7a', '-DANDROID_MIN_SDK=21', '-DONNX_CUSTOM_PROTOC_EXECUTABLE=/workspace/shared/output/intermediates/armeabi-v7a/host_protoc/protoc', '-DCMAKE_TLS_VERIFY=ON', '-DFETCHCONTENT_QUIET=OFF', '-Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF', '-G', 'Ninja', '-Donnxruntime_ENABLE_MEMLEAK_CHECKER=OFF', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_PREFIX_PATH=/workspace/shared/output/intermediates/armeabi-v7a/Release/installed']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/workspace/onnxruntime/tools/ci_build/github/android/build_aar_package.py", line 220, in <module>
    main()
  File "/workspace/onnxruntime/tools/ci_build/github/android/build_aar_package.py", line 216, in main
    _build_aar(args)
  File "/workspace/onnxruntime/tools/ci_build/github/android/build_aar_package.py", line 107, in _build_aar
    subprocess.run(abi_build_command, env=temp_env, shell=False, check=True, cwd=REPO_DIR)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/workspace/onnxruntime/tools/ci_build/build.py', '--android', '--parallel', '--cmake_generator=Ninja', '--build_java', '--build_shared_lib', '--minimal_build=extended', '--disable_rtti', '--disable_ml_ops', '--disable_exceptions', '--enable_reduced_operator_type_support', '--use_nnapi', '--skip_tests', '--android_api=21', '--config=Release', '--android_abi=armeabi-v7a', '--build_dir=/workspace/shared/output/intermediates/armeabi-v7a', '--include_ops_by_config=/workspace/shared/input/required_operators.config']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/ubuntu/project/onnxruntime/./tools/android_custom_build/build_custom_android_package.py", line 157, in <module>
    main()
  File "/home/ubuntu/project/onnxruntime/./tools/android_custom_build/build_custom_android_package.py", line 151, in main
    subprocess.run(docker_run_cmd, check=True)
  File "/root/miniconda3/envs/ai/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/docker', 'run', '--rm', '-it', '--volume=/home/ubuntu/project/out:/workspace/shared', 'onnxruntime-android-custom-build:latest', '/usr/bin/env', 'python3', '/workspace/onnxruntime/tools/ci_build/github/android/build_aar_package.py', '--build_dir=/workspace/shared/output', '--config=Release', '--include_ops_by_config=/workspace/shared/input/required_operators.config', '/workspace/shared/input/default_mobile_aar_build_settings.json']' returned non-zero exit status 1.

**Comment by skottmckay** [comment]
As per the error message you need to install a newer version of cmake.

> CMake Error at CMakeLists.txt:5 (cmake_minimum_required):
CMake 3.24 or higher is required. You are running version 3.21.0

https://cmake.org/install/

**Comment by edgchen1** [comment]
Try using a copy of the [android_custom_build directory](https://github.com/microsoft/onnxruntime/tree/main/tools/android_custom_build) from main. 
The Dockerfile was updated to install a newer version of CMake (https://github.com/microsoft/onnxruntime/commit/7cc9aed314cb32d4e12b44186074e5c52e29f6b3) but that change didn't make it into the 1.14 release. You can still build from `v1.14.1` by using `--onnxruntime_branch_or_tag v1.14.1`. The build script will check out a copy of the source at that tag.

**Comment by ZTMIDGO** [comment]
> Try using a copy of the [android_custom_build directory](https://github.com/microsoft/onnxruntime/tree/main/tools/android_custom_build) from main. The Dockerfile was updated to install a newer version of CMake ([7cc9aed](https://github.com/microsoft/onnxruntime/commit/7cc9aed314cb32d4e12b44186074e5c52e29f6b3)) but that change didn't make it into the 1.14 release. You can still build from `v1.14.1` by using `--onnxruntime_branch_or_tag v1.14.1`. The build script will check out a copy of the source at that tag.

Thanks, I tried it and still can't build 1.14.1 but I replaced the code with your way, can build 1.14.0, but can't build 1.14.1：

# cmakeRUN CMAKE_VERSION=3.21.0 && \ aria2c -q -d /tmp -o cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz \ --checksum=sha-256=d54ef6909f519740bc85cec07ff54574cd1e061f9f17357d9ace69f61c6291ce \ https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz && \ tar -zxf /tmp/cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz --strip=1 -C /usr

replace to：

# cmakeRUN CMAKE_VERSION=3.25.2 && \ aria2c -q -d /tmp -o cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz \ --checksum=sha-256=783da74f132fd1fea91b8236d267efa4df5b91c5eec1dea0a87f0cf233748d99 \ https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz && \ tar -zxf /tmp/cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz --strip=1 -C /usr

I was then able to build 1.14.0 successfully, but not 1.14.1

**Comment by edgchen1** [comment]
Ok, if 1.14.0 is fine that works. Otherwise, feel free to paste the error output and we can troubleshoot further.

**Comment by edgchen1** [comment]
Closing this now, but feel free to reopen if you need help with building 1.14.1.
