### ISSUE TITLE
Symbolic shape inference replacing/sharing dim_params incorrectly (as part of transformer optimization)

### ISSUE THREAD

**Issue by jstoecker** [microsoft/onnxruntime#15521]
### Describe the issue

I am converting the PyTorch Stable Diffusion models (runwayml/stable-diffusion-v1-5) to ONNX, and then optimizing the pipeline using [onnxruntime.transformers.optimizer](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/optimizer.py) to optimize the Stable Diffusion models for GPU inference in float16. The conversion to float16 requires [running symbolic shape inference](https://github.com/microsoft/onnxruntime/blob/5ebe700a9b7514bb6dfa951df34cffb4548196c0/onnxruntime/python/tools/transformers/onnx_model.py#L621) just before conversion, and this is where the issue occurs: symbolic shape inference is renaming various symbol names in the graph input/output tensors such that they are no longer distinct.

Before symbolic shape inference:
![image](https://user-images.githubusercontent.com/3835701/232169606-29770b08-c069-4a6f-8b57-0f6b365c8fcf.png)

After symbolic shape inference:
![image](https://user-images.githubusercontent.com/3835701/232169641-9c5fcd1f-8a59-4401-b39b-7a01820772f6.png)

It might appear like this is not an issue in this example, since batch dimensions are typically all the same size for inputs, but in Stable Diffusion inference it's common to have the `sample` and `encoder_hidden_states` [double the batch size for classifier free guidance](https://github.com/huggingface/diffusers/blob/46c52f9b9607e6ecb29c782c052aea313e6487b7/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L672). In other words, you might see `sample=[2,4,64,64]`, `timestep=[1]`, and `encoder_hidden_states=[2,77,768]`.

The actual renaming is not deterministic (see repro steps below), and sometimes all three inputs share some names. Having unique symbolic dimension names for the inputs is important, since it is desirable for runtime performance to override these dimensions with fixed values (e.g. using free dimension name overrides).

### To reproduce

Torch 1.13.1 is required to avoid [conversion issue](https://github.com/pytorch/pytorch/issues/97262).
```
pip install torch==1.13.1 transformers diffusers onnx onnxruntime
```

The following code will download the U-Net model from Stable Diffusion v1.5, convert it, and then show the input/output shapes before and after symbolic shape inference.

```python
import onnx
from pathlib import Path
from onnxruntime.transformers.shape_infer_helper import SymbolicShapeInferenceHelper

def print_tensor(tensor):
    name = tensor.name
    tensor_type = tensor.type.tensor_type
    data_type = onnx.TensorProto.DataType.keys()[tensor_type.elem_type]
    shape = [
        dim.dim_param if dim.dim_param else dim.dim_value
        for dim in tensor_type.shape.dim
    ]
    print(f"{name} = {data_type} {shape}")


def print_io(model):
    for tensor in model.graph.input:
        print_tensor(tensor)
    for tensor in model.graph.output:
        print_tensor(tensor)


def convert_sd_model(model_type, output_onnx_path):
    from diffusers import UNet2DConditionModel
    import torch

    pytorch_model = UNet2DConditionModel.from_pretrained(
        "runwayml/stable-diffusion-v1-5", subfolder=model_type
    )

    inputs = {
        "sample": torch.rand((1, 4, 64, 64), dtype=torch.float32),
        "timestep": torch.rand((1,), dtype=torch.float32),
        "encoder_hidden_states": torch.rand((1, 77, 768), dtype=torch.float32),
        "return_dict": False,
    }

    torch.onnx.export(
        pytorch_model,
        inputs,
        str(output_onnx_path),
        export_params=True,
        opset_version=14,
        input_names=["sample", "timestep", "encoder_hidden_states", "return_dict"],
        output_names=["out_sample"],
        dynamic_axes={
            "sample": {0: "sample_n", 1: "sample_c", 2: "sample_h", 3: "sample_w"},
            "timestep": {0: "timestep_n"},
            "encoder_hidden_states": {0: "hidden_n", 1: "hidden_seq"},
        },
    )


# Convert SD U-Net to ONNX if it already doesn't exist
onnx_file_path = Path("unet.onnx")
if not onnx_file_path.exists():
    convert_sd_model("unet", onnx_file_path)

# Print input/output shapes
print("\n*** BEFORE ***")
onnx_model = onnx.load(onnx_file_path, load_external_data=False)
print_io(onnx_model)

# Run symbolic shape inference
shape_infer_helper = SymbolicShapeInferenceHelper(onnx_model, verbose=0)
onnx_model = shape_infer_helper.infer_shapes(
    onnx_model, auto_merge=True, guess_output_rank=False
)

# Print input/output shapes again
print("\n\n*** AFTER ***")
print_io(onnx_model)
```

Example output:
```
*** BEFORE ***
sample = FLOAT ['sample_n', 'sample_c', 'sample_h', 'sample_w']
timestep = FLOAT ['timestep_n']
encoder_hidden_states = FLOAT ['hidden_n', 'hidden_seq', 768]
out_sample = FLOAT ['Convout_sample_dim_0', 4, 'Convout_sample_dim_2', 'Convout_sample_dim_3']


*** AFTER ***
sample = FLOAT ['sample_n', 'sample_c', 'sample_h', 'sample_w']
timestep = FLOAT ['sample_n']
encoder_hidden_states = FLOAT ['hidden_n', 'hidden_seq', 768]
out_sample = FLOAT ['sample_n', 4, 'sample_h', 'sample_w']
```

Note how `timestep` now shares a batch dimension name with `sample`! Furthermore, the behavior seems nondeterministic. On another run of the same script all inputs somehow have `hidden_n` for batch dimension:

```
*** BEFORE ***
sample = FLOAT ['sample_n', 'sample_c', 'sample_h', 'sample_w']
timestep = FLOAT ['timestep_n']
encoder_hidden_states = FLOAT ['hidden_n', 'hidden_seq', 768]
out_sample = FLOAT ['Convout_sample_dim_0', 4, 'Convout_sample_dim_2', 'Convout_sample_dim_3']


*** AFTER ***
sample = FLOAT ['hidden_n', 'sample_c', 'sample_h', 'sample_w']
timestep = FLOAT ['hidden_n']
encoder_hidden_states = FLOAT ['hidden_n', 'hidden_seq', 768]
out_sample = FLOAT ['hidden_n', 4, 'sample_h', 'sample_w']
```

### Urgency

There is some urgency in this issue. Please e-mail my Microsoft alias (justoeck) for details.

### Platform

Windows

### OS Version

Windows 11 - irrelevant

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14 and 1.15 (main)

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA, DirectML

### Execution Provider Library Version

irrelevant

**Comment by jstoecker** [comment]
@PatriceVignola FYI

**Comment by tianleiwu** [comment]
It is a known issue. see comments in the code:
https://github.com/microsoft/onnxruntime/blob/698e9f71cd72ed6176938ff093b40e57f92cd681/onnxruntime/python/tools/symbolic_shape_infer.py#L362-L363

Example of walkaround is to merge type information back to original model like the following:
```
shape_infer_helper = SymbolicShapeInferenceHelper(model)
model_with_shape = shape_infer_helper.infer_shapes(model, auto_merge=True, guess_output_rank=False)

# we only merge data type but not shape information back to the original onnx model
if model_with_shape is not None:
    tensor_type = {}
    for value_info in model_with_shape.graph.value_info:
        tensor_type[value_info.name] = value_info.type.tensor_type.elem_type
    for value_info in model.graph.value_info:
        if value_info.name in tensor_type:
            del tensor_type[value_info.name]
    for name, type in tensor_type.items():
        vi = helper.make_tensor_value_info(name, type, None)
        model.graph.value_info.append(vi)
```

**Comment by jstoecker** [comment]
> It is a known issue. see comments in the code:
> 
> https://github.com/microsoft/onnxruntime/blob/698e9f71cd72ed6176938ff093b40e57f92cd681/onnxruntime/python/tools/symbolic_shape_infer.py#L362-L363
> 
> Example of walkaround is to merge type information back to original model like the following:

Thanks @tianleiwu. Would it be possible to make the workaround an optional feature of the transformer optimizer API (e.g. a parameter that gets propagated to the float16 conversion helper and copies type but not shape data)? Ultimately, symbolic shape inference is buried a few levels below the surface of what users will typically interact with.

For context, Olive has an [optimization pass](https://github.com/microsoft/Olive/blob/main/olive/passes/onnx/transformer_optimization.py#L187) that layers on top of onnxruntime.
