### ISSUE TITLE
[Build] Get ImportError after install onnxruntime-gpu/onnxruntime

### ISSUE THREAD

**Issue by ann-lab52** [microsoft/onnxruntime#15551]
### Describe the issue

Packages information:
- onnxruntime-training==1.13.1+cu116
- onnx==1.12.0
- ninja==1.11.1
- protobuf==3.20.2
- torch==1.13.1+cu116
- torch-ort==1.13.1

After setup those packages for my container, I did command `python -m torch_ort.configure`  and it's run successfully.

However when I'm trying to install `onnxruntime-gpu`,  it's will raise

> `ImportError: cannot import name 'PropagateCastOpsStrategy' from 'onnxruntime.capi._pybind_state' (/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/_pybind_state.py)`

and keep up that error even I uninstalled the package. 

I tried some solution like installed the `libgomp1` packages by `sudo apt install libgomp1`  but it still not working.

### Target platform

Ubuntu 20.04 - CUDA Version: 11.6 - Python 3.8.10

### Build script

`python -m torch_ort.configure`

### Error / output

> ImportError: cannot import name 'PropagateCastOpsStrategy' from 'onnxruntime.capi._pybind_state' (/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/_pybind_state.py)

**Comment by ann-lab52** [comment]
So I decided to create a new container (with the same packages ans system information) and instead of install `onnxruntime-gpu` or `onnxruntime` or optimum[<specific onnruntime type>], I install fully `optimum` package and now it work perfectly. Hope this will help for anyone have the same issue. 

 I will close this issue then. Please feel free to reopen it if you need. Thanks

**Comment by orangetin** [comment]
I'm running into the same issue. @ann-lab52 , how did you fix it? I've installed optimum but the error persists.

**Comment by ann-lab52** [comment]
@orangetin You can try my previous solution. Sorry for my late reply.

> So I decided to create a new container (with the same packages ans system information) and instead of install `onnxruntime-gpu` or `onnxruntime` or `optimum[<specific_onnxruntime_type>]`, I install fully `optimum` package and now it work perfectly. Hope this will help for anyone have the same issue.
> 
> I will close this issue then. Please feel free to reopen it if you need. Thanks
