### ISSUE TITLE
[Feature Request] Support Pad opset 19

### ISSUE THREAD

**Issue by liqunfu** [microsoft/onnxruntime#15576]
### Describe the feature request

Pad has been updated in opset 19
https://github.com/onnx/onnx/blob/main/docs/Operators.md#Pad

### Describe scenario use case

Ort shall pass updated Pad test cases.

**Comment by flip1995** [comment]
This feature didn't make it into release `v1.15.*` AFAICT. So the opset 19 support claimed in the [compatibility documentation](https://onnxruntime.ai/docs/reference/compatibility.html) is not fully met IIUC. Was this left out intentionally or just missed?

Without this fix, graphs generated with ONNX 1.14 cannot be run with ORT 1.15. Cherry-picking onto the `v1.15.1` tag and then running the ONNX 1.14 graph works.

Any chance that this can get into a `v1.15.2` point release? I would really appreciate that. Thanks for implementing it! :)
