### ISSUE TITLE
[Feature Request] Support Cast opset 19

### ISSUE THREAD

**Issue by liqunfu** [microsoft/onnxruntime#15570]
### Describe the feature request

Cast has been updated in opset 1.14
https://github.com/onnx/onnx/blob/main/docs/Operators.md#Cast

### Describe scenario use case

ORT shall pass updated Cast test cases. this PR will be fixed in https://github.com/microsoft/onnxruntime/pull/14731

**Comment by xadupre** [comment]
Fixed in #14731.
