### ISSUE TITLE
use onnxruntime by pypi

### ISSUE THREAD

**Issue by raccoonliukai** [microsoft/onnxruntime#1558]
**Describe the bug**
I use pip install onnxruntime-gpu. I find onnx0.5.0 use cuda-10.1 and cudnn-v7(whose def in _ld_preload.py). But onnx docs said used cuda-10.0 with onnx0.5.0. So which cuda version is right?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version: 0.5.0
- Python version:3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by faxu** [comment]
The published 0.5.0 version uses CUDA 10.1 for the linux build. All others use 10.0. Do you have any issues/dependencies on either 10.0 or 10.1?
