### ISSUE TITLE
[Mobile]  report error "Unable to find version of Microsoft.AI.DirectML and  Microsoft.Windows.CppWinRT  in Ubuntu system

### ISSUE THREAD

**Issue by Havelet** [microsoft/onnxruntime#15595]
### Describe the issue

I use below command to build onnx android verson, but get error reported, I guess which is dependent on  three external package, but in my view Microsoft.AI.DirectML and  'Microsoft.Windows.CppWinRT can't be installed in Ubuntu, so how to proceed , could you please help out?
"Unable to find version '1.10.1' of package 'Microsoft.AI.DirectML'.
Unable to find version '2.0.201201.7' of package 'Microsoft.Windows.CppWinRT'.
Unable to find version '3.21.12' of package 'google.protobuf.tools'.

 ./build.sh --android --android_sdk_path=~/android_sdk --android_n dk_path=~/android_sdk/ndk --android_abi arm64-v8a --android_api 29
2023-04-20 11:36:31,998 tools_python_utils [INFO] - flatbuffers module is not installed. parse_config will not be available
2023-04-20 11:36:32,001 build [DEBUG] - Command line arguments:
  --build_dir /home/hanbo.zhang/workspace/onnxruntime/build/Android --android '--android_sdk_path=~/android_sdk' '--android_ndk_path=~/android_sdk/ndk' --android_abi arm64-v8a --android_api 29
2023-04-20 11:36:32,007 build [DEBUG] - Defaulting to running update, build [and test for native builds].
2023-04-20 11:36:32,007 build [INFO] - Build started
2023-04-20 11:36:32,007 util.run [INFO] - Running subprocess in '/home/hanbo.zhang/workspace/onnxruntime'
  git submodule sync --recursive
Synchronizing submodule url for 'cmake/external/eigen'
Synchronizing submodule url for 'cmake/external/emsdk'
Synchronizing submodule url for 'cmake/external/libprotobuf-mutator'
Synchronizing submodule url for 'cmake/external/onnx'
Synchronizing submodule url for 'cmake/external/onnx/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/onnx/third_party/pybind11'
Synchronizing submodule url for 'cmake/external/onnxruntime-extensions'
2023-04-20 11:36:32,057 util.run [DEBUG] - Subprocess completed. Return code: 0
2023-04-20 11:36:32,057 util.run [INFO] - Running subprocess in '/home/hanbo.zhang/workspace/onnxruntime'
  git submodule update --init --recursive
2023-04-20 11:36:32,159 util.run [DEBUG] - Subprocess completed. Return code: 0
2023-04-20 11:36:32,164 util.run [INFO] - Running subprocess in '/home/hanbo.zhang/workspace/onnxruntime'
  nuget restore /home/hanbo.zhang/workspace/onnxruntime/packages.config -ConfigFile /home/hanbo.zhang/workspace/onnxruntime/NuGet.config -PackagesDirectory /home/hanbo.zhang/workspace/onnxruntime/build/Android
Unable to find version '1.10.1' of package 'Microsoft.AI.DirectML'.
Unable to find version '2.0.201201.7' of package 'Microsoft.Windows.CppWinRT'.
Unable to find version '3.21.12' of package 'google.protobuf.tools'.
Traceback (most recent call last):
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 2688, in <module>
    sys.exit(main())
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 2527, in main
    path_to_protoc_exe = build_protoc_for_host(cmake_path, source_dir, build_dir, args)
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 2198, in build_protoc_for_host
    run_subprocess(
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 782, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nuget', 'restore', '/home/hanbo.zhang/workspace/onnxruntime/packages.config', '-ConfigFile', '/home/hanbo.zhang/workspace/onnxruntime/NuGet.config', '-PackagesDirectory', '/home/hanbo.zhang/workspace/onnxruntime/build/Android']' returned non-zero exit status 1.

### To reproduce

step 1 : git clone  https://github.com/microsoft/onnxruntime.git
step 2: ./build.sh --android --android_sdk_path=~/android_sdk --android_n dk_path=~/android_sdk/ndk --android_abi arm64-v8a --android_api 29
this command is got refered to https://onnxruntime.ai/docs/build/android.html

### Platform

Android

### OS Version

Android 10.0

### ONNX Runtime Installation

Built from Source

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

5b6f79e79b68912cc0b1a7f38b2e935027e98bd0

### ONNX Runtime API

C++/C

### Architecture

X64

### Execution Provider

Default CPU

**Comment by snnn** [comment]
Good point! I will fix it in the next a few days. Meanwhile, you can download a prebuilt protoc from https://github.com/protocolbuffers/protobuf/releases and pass it to build.sh as:
```
--path_to_protoc_exe /usr/bin/protoc
```

**Comment by Havelet** [comment]
Thanks for your guide! I tried the above tips but got new error message.  I checked protoc version which reported as 
 below, do you have any idea how to fix this?
ubuntu1:~$ protoc --version
libprotoc 3.7.1




-- Build files have been written to: /home/hanbo.zhang/workspace/onnxruntime/build/Android/Debug
2023-04-21 18:26:58,940 util.run [DEBUG] - Subprocess completed. Return code: 0
2023-04-21 18:26:58,940 build [INFO] - Building targets for Debug configuration
2023-04-21 18:26:58,940 util.run [INFO] - Running subprocess in '/home/hanbo.zhang/workspace/onnxruntime'
  /usr/local/bin/cmake --build /home/hanbo.zhang/workspace/onnxruntime/build/Android/Debug --config Debug
[  1%] Built target gen_onnx_proto
[  1%] Built target gen_onnx_data_proto
[  3%] Built target libprotobuf-lite
[  3%] Built target gen_onnx_operators_proto
[  3%] Building CXX object _deps/onnx-build/CMakeFiles/onnx_proto.dir/onnx/onnx-ml.pb.cc.o
In file included from /home/hanbo.zhang/workspace/onnxruntime/build/Android/Debug/_deps/onnx-build/onnx/onnx-ml.pb.cc:4:
/home/hanbo.zhang/workspace/onnxruntime/build/Android/Debug/_deps/onnx-build/onnx/onnx-ml.pb.h:17:2: error: This file was generated by an older version of protoc which is
#error This file was generated by an older version of protoc which is
 ^
/home/hanbo.zhang/workspace/onnxruntime/build/Android/Debug/_deps/onnx-build/onnx/onnx-ml.pb.h:18:2: error: incompatible with your Protocol Buffer headers. Please
#error incompatible with your Protocol Buffer headers. Please
 ^
/home/hanbo.zhang/workspace/onnxruntime/build/Android/Debug/_deps/onnx-build/onnx/onnx-ml.pb.h:19:2: error: regenerate this file with a newer version of protoc.
#error regenerate this file with a newer version of protoc.
 ^
/home/hanbo.zhang/workspace/onnxruntime/build/Android/Debug/_deps/onnx-build/onnx/onnx-ml.pb.h:26:10: fatal error: 'google/protobuf/generated_message_table_driven.h' file not found
#include <google/protobuf/generated_message_table_driven.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 errors generated.
make[2]: *** [_deps/onnx-build/CMakeFiles/onnx_proto.dir/build.make:109: _deps/onnx-build/CMakeFiles/onnx_proto.dir/onnx/onnx-ml.pb.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:5123: _deps/onnx-build/CMakeFiles/onnx_proto.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
Traceback (most recent call last):
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 2688, in <module>
    sys.exit(main())
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 2585, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 1441, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 782, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/hanbo.zhang/workspace/onnxruntime/build/Android/Debug', '--config', 'Debug']' returned non-zero exit status 2.

**Comment by snnn** [comment]
Please use this version's protoc: 
https://github.com/protocolbuffers/protobuf/releases/tag/v21.12

**Comment by Havelet** [comment]
I upgraded protoc to v21.12 as you suggested, but same error reported .
protoc --version
libprotoc 3.21.12

**Comment by Havelet** [comment]
Does anyone has any idea to fix this?

**Comment by snnn** [comment]
Did you delete the build folder before retried?

**Comment by Havelet** [comment]
I'm not sure about this, but anyway I will try this and feed back!

**Comment by Havelet** [comment]
the error is gone, but new error reported, it might related to ndk.

[ 36%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/hanbo.zhang/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/einsum.cc.o      
[ 36%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/hanbo.zhang/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/einsum_utils/eins
um_auxiliary_ops.cc.o                                                                                                                                       
[ 36%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/hanbo.zhang/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/einsum_utils/eins
um_compute_preprocessor.cc.o                                                                                                                                
[ 36%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/hanbo.zhang/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/einsum_utils/eins
um_typed_compute_processor.cc.o                                                                                                                             
[ 36%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/hanbo.zhang/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.
cc.o                                                                                                                                                        
clang++: error: unable to execute command: Killed                                                                                                           
clang++: error: clang frontend command failed due to signal (use -v to see invocation)                                                                      
Android (6317467 based on r365631c1) clang version 9.0.8 (https://android.googlesource.com/toolchain/llvm-project e0caee08e5f09b374a27a676d04978c81fcb1928) 
(based on LLVM 9.0.8svn)                                                                                                                                    
Target: aarch64-none-linux-android29                                                                                                                        
Thread model: posix                                                                                                                                         
InstalledDir: /home/hanbo.zhang/android_sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin                                                      
clang++: note: diagnostic msg: PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source,
 and associated run script.                                                                                                                                 
clang++: note: diagnostic msg:                                                                                                                              
********************                                                                                                                                        
                                                                                                                                                            
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:                                                                                                        
Preprocessed source(s) and associated run script(s) are located at:                                                                                         
clang++: note: diagnostic msg: /tmp/element_wise_ops-fe5e35.cpp                                                                                             
clang++: note: diagnostic msg: /tmp/element_wise_ops-fe5e35.sh                                                                                              
clang++: note: diagnostic msg:                                                                                                                              
                                                                                                                                                            
********************                                                                                                                                        
make[2]: *** [CMakeFiles/onnxruntime_providers.dir/build.make:412: CMakeFiles/onnxruntime_providers.dir/home/hanbo.zhang/workspace/onnxruntime/onnxruntime/c
ore/providers/cpu/math/element_wise_ops.cc.o] Error 254                                                                                                     
make[1]: *** [CMakeFiles/Makefile2:1814: CMakeFiles/onnxruntime_providers.dir/all] Error 2                                                                  
make: *** [Makefile:166: all] Error 2                                                                                                                       
Traceback (most recent call last):                                                                                                                          
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 2688, in <module>                                                            
    sys.exit(main())                                                                                                                                        
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 2585, in main                                                                
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)                                                                     
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 1441, in build_targets                                                       
    run_subprocess(cmd_args, env=env)                                                                                                                       
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 782, in run_subprocess                                                       
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)                                                                      
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/python/util/run.py", line 49, in run                                                                  
    completed_process = subprocess.run(                                                                                                                     
  File "/usr/lib/python3.8/subprocess.py", line 516, in run                                                                                                 
    raise CalledProcessError(retcode, process.args,                                                                                                         
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/hanbo.zhang/workspace/onnxruntime/build/Android/Debug', '--config', 'Debu
g']' returned non-zero exit status 2.

**Comment by snnn** [comment]
Please try a newer version of NDK .clang version 9 is too old.

**Comment by Havelet** [comment]
sure, I will try latest versions

**Comment by Havelet** [comment]
I tried ndk  23.2.8568313 and api 31, still got error, I'm trying latest ndk 25.2.9519653 and api 33, later will feed back
n1:~/workspace/onnxruntime$ ./build.sh --android --android_sdk_path=~/android_sdk --android_n dk_path=~/android_sdk/ndk/23.2.8568313 --android_abi arm64-v8a --android_api 31 --path_to_protoc_exe /usr/local/bin/ protoc

[ 36%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/hanbo.zhang/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/einsum_utils/einsum_auxiliary_ops.cc.o
[ 36%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/hanbo.zhang/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/einsum_utils/einsum_compute_preprocessor.cc.o
[ 36%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/hanbo.zhang/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/einsum_utils/einsum_typed_compute_processor.cc.o
[ 36%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/hanbo.zhang/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.cc.o
make[2]: *** [CMakeFiles/onnxruntime_providers.dir/build.make:412: CMakeFiles/onnxruntime_providers.dir/home/hanbo.zhang/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.cc.o] Killed
make[1]: *** [CMakeFiles/Makefile2:1814: CMakeFiles/onnxruntime_providers.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
Traceback (most recent call last):
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 2688, in <module>
    sys.exit(main())
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 2585, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 1441, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 782, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/hanbo.zhang/workspace/onnxruntime/build/Android/Debug', '--config', 'Debug']' returned non-zero exit status 2.

**Comment by Havelet** [comment]
tried latest ndk 25.2.9519653 and api 33, still got error, sorry for this!

n1:~/workspace/onnxruntime$ ./build.sh --android --android_sdk_path=~/android_sdk --android_n dk_path=~/android_sdk/ndk/25.2.9519653 --android_abi arm64-v8a --android_api 33 --path_to_protoc_exe /usr/local/bin/ protoc

[ 36%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/hanbo.zhang/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/einsum_utils/einsum_compute_preprocessor.cc.o
[ 36%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/hanbo.zhang/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/einsum_utils/einsum_typed_compute_processor.cc.o
[ 36%] Building CXX object CMakeFiles/onnxruntime_providers.dir/home/hanbo.zhang/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.cc.o
make[2]: *** [CMakeFiles/onnxruntime_providers.dir/build.make:412: CMakeFiles/onnxruntime_providers.dir/home/hanbo.zhang/workspace/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.cc.o] Killed
make[1]: *** [CMakeFiles/Makefile2:1814: CMakeFiles/onnxruntime_providers.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
Traceback (most recent call last):
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 2688, in <module>
    sys.exit(main())
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 2585, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 1441, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 782, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/hanbo.zhang/workspace/onnxruntime/build/Android/Debug', '--config', 'Debug']' returned non-zero exit status 2.

**Comment by snnn** [comment]
Go to "/home/hanbo.zhang/workspace/onnxruntime/build/Android/Debug" and run 
```
make VERBOSE=1 >& 1.log
```
Then "grep error:" in the log or upload the log here.

**Comment by Havelet** [comment]
Sorry for the late reply due to the Labor holiday! after extend the memory and disk space, it seems build successfully as i didn't find any error: info in the log file and got below info after relaunching the build, is this mean I need a emulator to run the build or just copy the libs out in Debug folder?

[100%] Built target custom_op_get_const_input_test_library
2023-05-04 11:43:17,756 util.run [DEBUG] - Subprocess completed. Return code: 0
2023-05-04 11:43:17,756 build [INFO] - Running tests for Debug configuration
Traceback (most recent call last):
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 2688, in <module>
    sys.exit(main())
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 2592, in main
    run_onnxruntime_tests(args, source_dir, ctest_path, build_dir, configs)
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 1724, in run_onnxruntime_tests
    run_android_tests(args, source_dir, build_dir, config, cwd)
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 1574, in run_android_tests
    sdk_tool_paths = android.get_sdk_tool_paths(args.android_sdk_path)
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/python/util/android/android.py", line 41, in get_sdk_tool_paths
    emulator=resolve_path([os.path.join(sdk_root, "emulator")], filename("emulator", "exe")),
  File "/home/hanbo.zhang/workspace/onnxruntime/tools/python/util/android/android.py", line 38, in resolve_path
    raise FileNotFoundError(f"Failed to resolve path for {basename}")
FileNotFoundError: Failed to resolve path for emulator[](url)

**Comment by June1124** [comment]
> Sorry for the late reply due to the Labor holiday! after extend the memory and disk space, it seems build successfully as i didn't find any error: info in the log file and got below info after relaunching the build, is this mean I need a emulator to run the build or just copy the libs out in Debug folder?
> 
> [100%] Built target custom_op_get_const_input_test_library 2023-05-04 11:43:17,756 util.run [DEBUG] - Subprocess completed. Return code: 0 2023-05-04 11:43:17,756 build [INFO] - Running tests for Debug configuration Traceback (most recent call last): File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 2688, in sys.exit(main()) File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 2592, in main run_onnxruntime_tests(args, source_dir, ctest_path, build_dir, configs) File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 1724, in run_onnxruntime_tests run_android_tests(args, source_dir, build_dir, config, cwd) File "/home/hanbo.zhang/workspace/onnxruntime/tools/ci_build/build.py", line 1574, in run_android_tests sdk_tool_paths = android.get_sdk_tool_paths(args.android_sdk_path) File "/home/hanbo.zhang/workspace/onnxruntime/tools/python/util/android/android.py", line 41, in get_sdk_tool_paths emulator=resolve_path([os.path.join(sdk_root, "emulator")], filename("emulator", "exe")), File "/home/hanbo.zhang/workspace/onnxruntime/tools/python/util/android/android.py", line 38, in resolve_path raise FileNotFoundError(f"Failed to resolve path for {basename}") FileNotFoundError: Failed to resolve path for emulator

Same question. Is this problem solved? 
![image](https://github.com/microsoft/onnxruntime/assets/52447302/917b3e5c-822c-4d14-a90c-6ffe41ced502)

**Comment by snnn** [comment]
@June1124, please open a new issue provide us more logs. The screenshot above shows it cannot find sdkmanager.bat. Do you have this file?
