### ISSUE TITLE
with reference to #1542 

### ISSUE THREAD

**Issue by ajaysg** [microsoft/onnxruntime#1559]
@snnn its a bug with onnxrt. before exporting the pytorch model to onnx, i have converted the model to float using the command

`model1=model.float()`

now all the tensors in the model1 is float.

`mel_extra=torch.tensor(np.full((1,80,222),-10.0)).float()`
`dummy_input=torch.autograd.Variable(mel_extra).cuda().float()`
`audio = torch.tensor(np.full((1,222), -0.5)).float()`
`audio_input = torch.autograd.Variable(audio).cuda().float()`
`torch.onnx.export(model1, ((dummy_input, audio_input),), "./waveglow.onnx")`

Then i passed the float tensors as mentioned above and traced the onnx graph. Onnx export was successful. When i try to use it in onnxrt by starting the session 

`sess = rt.InferenceSession("../waveglow.onnx")`

it throws the error referenced in the issue.

**Comment by snnn** [comment]
#1542 #310

**Comment by ajaysg** [comment]
onnx runtime not supporting float

**Comment by faxu** [comment]
Hi @ajaysg, 
After further investigation, it appears this is a PyTorch export issue and is tracked by this: https://github.com/pytorch/pytorch/pull/24378
