### ISSUE TITLE
OnnxRuntime C# library - add support for Sequence and Map model output types

### ISSUE THREAD

**Issue by jignparm** [Microsoft/onnxruntime#156]
Add support in C# OnnxRuntime Library for sequences and maps (complex types). Tensors are the only supported type currently.

**Comment by jignparm** [comment]
There's a model that a user converted to Onnx (see https://github.com/dotnet/machinelearning/issues/1323), which produces a Sequence<Map<int,float>> as an output.  It seems like a valid ONNX model, and therefore should able to run inference on it. Is there a non C API which is running this inference currently?

**Comment by snnn** [comment]
The python binding is using the C++ API, but C# is using the C API, because it is not possible to access C++ functions through P/Invoke.

**Comment by derdanielb** [comment]
Any progress to this? @jignparm 

Loading a model which outputs `Sequence<Map<int,float>>` does not work using the latest C# onnxruntime nuget package (v 0.2.1).
However loading the model using python onnxruntime works fine.

I could really use an implementation of this in the C# onnxruntime.

**Comment by jignparm** [comment]
This functionality is in progress (i.e. the C API supports it now),  and surfacing it in C# is in progress. Should be available next week.

**Comment by jignparm** [comment]
@derdanielb  - please look at the example below, for a model which produces seq<map<int,float>> type.

https://github.com/Microsoft/onnxruntime/blob/3a2f6c69646df66fe82c919cd956a2034a418a0e/csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs#L528
