### ISSUE TITLE
[js/webgl] feature request: support latest opset for operator `Resize`

### ISSUE THREAD

**Issue by mrdrprofuroboros** [microsoft/onnxruntime#15636]
### Describe the issue

I'm trying to run meta's segment-anything onnx model inference with webgl and get:
```
Uncaught (in promise) Error: unrecognized input '' for node: /Resize
    at p.buildGraphFromOnnxFormat (graph.ts:340:1)
    at p.buildGraph (graph.ts:187:1)
    at new p (graph.ts:152:1)
    at Object.from (graph.ts:82:1)
    at e.Model.loadFromOnnxFormat (model.ts:42:1)
    at e.Model.load (model.ts:23:1)
    at session.ts:93:1
    at e.Profiler.event (instrument.ts:337:1)
    at e.Session.initialize (session.ts:89:1)
    at session.ts:71:1
```

a little debugging in chrome shows this:
<img width="920" alt="Снимок экрана 2023-04-21 в 15 47 47" src="https://user-images.githubusercontent.com/21140507/233731991-2181907f-ed18-4ccc-8abb-646d1139d949.png">

works fine on `wasm`, but I wanted to try `webgl` support

### To reproduce

the model is exported with https://github.com/facebookresearch/segment-anything/blob/main/notebooks/onnx_model_example.ipynb

and loaded on frontend with the following:
```typescript
     model = await InferenceSession.create(
        VITB_DECODER_URL,
        {
          executionProviders: ['webgl'],
          graphOptimizationLevel: 'all',
        },
      );
```

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.0

### Execution Provider

WebGL

**Comment by fs-eire** [comment]
feature request: support latest opset for operator `Resize`

**Comment by KevinSchiener** [comment]
I have the same issue. Is there any way we can modify the model or export to work around this? (Sorry, I have a limited grasp on the underlying issue here.)

**Comment by zimond** [comment]
I don't think so, the model need to be exported under opset 11 to resolve Resize problem, but this leads to other ops being invalid.
