### ISSUE TITLE
Question about the onnx model output 

### ISSUE THREAD

**Issue by SiR0N** [microsoft/onnxruntime#1568]
I am working with C ONNX runtime API and there is one thing that is not clear to me. 

In the example there is just one output so the values are load in an array ("pointer to array"),  I wonder what happens when there are more outputs, would it be a pointers to array pointers? or would it be just one large array and I should take care of dividing the output?

For example: 
There are 2 outputs, A of shape (1,15) and B of shape (1,10), would I get C[25] or C[2] with 2 pointers to A[15] and B[10] values. 

This is the code of the C API example: [https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp#L152](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp#L152)

**Comment by RyanUnderhill** [comment]
Yes, the C example isn't clear for multiple outputs as it was just a simple example with a single output.

The second to last parameter of OrtRun is the # of outputs you expect it to return (and also the size of the OrtValue* array you're passing as the last parameter. If you want two outputs you need to pass an array of two pointers, and pass a 2 for the output_names_len parameter.

So yes, it's a pointer to an array of pointers as you suggested above.

The C++ example makes it more clear in that the return value from Session::Run is plural but only contains a single element:

https://github.com/microsoft/onnxruntime/blob/9e926fef1cf7c0ed9ccde5e88453fd91266f3c9b/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp#L111

Did that help to get it to work?

**Comment by SiR0N** [comment]
Yes, it helps to me. 

So if I want 2 output (or more) it should be something like:

```
OrtValue** output = nullptr; //if I want 3, should it be OrtValue***?
    ost = OrtRun( ort_ses, nullptr,
            input_node_names.data(),
            input_tensor_list.data(),
            num_input_nodes,
            output_node_names.data(),
            2,
            output);

float** data = nullptr;
    ost = OrtGetTensorMutableData(output, reinterpret_cast<void **>(data));
```
or maybe

```
float* data1 = nullptr;
    ost = OrtGetTensorMutableData(output[0], reinterpret_cast<void **>(&data1));
float* data2 = nullptr;
    ost = OrtGetTensorMutableData(output[1], reinterpret_cast<void **>(&data2));
```

I will try to put the output in vector<vector<>> "matrix". I wonder how I should do, I am not so familiar with C pointers but I guess that the easiest way is to a loop over the array of pointers (output, in my example), any suggestions? 

for the OrtValue***comment in the code, could I create a vector<OrtValue*> vectorOV with size of 3 and feed OrtRun with vectorOV.data()?

**Comment by RyanUnderhill** [comment]
If you have two outputs, you'd do something like this:

    OrtValue *output_values[2]; // Array of 2 pointers
    status = OrtRun( ... same as you listed until...., 2 /* number of outputs */, output_values);

Saying just 'outputs' in the parameter to OrtRun passes the address of the array of two pointers, which is of type OrtValue**.

Or using std::vector

    std::vector<OrtValue*> output_values(2, nullptr);
    status = OrtRun( ...same as above... output_values.size(), output_values.data());

In both the above example and the std::vector one, to iterate is easy. There are multiple options, but this is probably easy to understand (though I wouldn't hardcode the 2 in the loop, it's just for the example):

    for(int i=0;i<2;i++)
      // Do something with output_values[i]

I recommend using the C++ wrapper API since it simplifies the pointer work you'd have to do.

Did you get it to work?

**Comment by SiR0N** [comment]
Yes I made it running! 

This is my code:
```
std::vector<OrtValue*> ortOutput(num_output_nodes);
    ost = OrtRun(...
                  num_output_nodes,
                  ortOutput.data());

 for (int i =0; i< ortOutput.size(); i++){
        float* data = nullptr;
        ost = OrtGetTensorMutableData(ortOutput[i], reinterpret_cast<void **>(&data));
        OrtReleaseValue(ortOutput[i]);
       for(int r = 0; r < outputM[i].size(); r++){
            outputM[i][r] = data[r];

        }
```

Anyway I will try with the C++ API, thanks for your help

**Comment by RyanUnderhill** [comment]
Cool, happy to help!

**Comment by SiR0N** [comment]
Hi again!

I have another question. 

I want to inference the [faster-rcnn](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/faster-rcnn)

But I have an error and I think it is because all the shapes are undefined in the file. I get the shape with the [official site](https://github.com/microsoft/onnxruntime/blob/9e926fef1cf7c0ed9ccde5e88453fd91266f3c9b/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp#L96) or my method:
```
size_t input_tensor_size = 1;
        for (size_t j = 0; j < num_dims; j++) {
            input_tensor_size = input_tensor_size * input_node_dims[j];
            __android_log_print(android_LogPriority::ANDROID_LOG_ERROR,
                                logid,
                                "Input %zu : dim %zu = %jd\n", i, j, input_node_dims[j]);


        }
```
None of them worked.

I got this error:
`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8 in tid 15948`
in this line:
```
std::vector<OrtValue*> ortOutput(num_output_nodes);
    ost = OrtRun( ort_ses, nullptr,
            input_node_names.data(),
            input_tensor_list.data(),
            num_input_nodes,
            output_node_names.data(),
            num_output_nodes,
                  ortOutput.data());
```

I create the tensors in this way: 
```
OrtValue* input_tensor = nullptr;
        ost = OrtCreateTensorWithDataAsOrtValue(
                ort_info,
                img,//1 dimention array 
                input_tensor_size * sizeof(type),
                reinterpret_cast<const int64_t *>(input_node_dims.data()),
                input_node_dims.size(), 
                type,
                &input_tensor);
input_tensor_list[i] = input_tensor;
```

should I create a new issue?

**Comment by addisonklinke** [comment]
@SiR0N I found your code sample below helpful, but could you clarify what how the `outputM` variable is initialized? It seems like you would have to hard-code a vector based on known output shapes in order to use the `size()` method in the loop

@RyanUnderhill is there any way to get the output shape from directly inspecting `OrtOutput[i]`?

```
std::vector<OrtValue*> ortOutput(num_output_nodes);
ost = OrtRun(..., num_output_nodes, ortOutput.data());

for (int i =0; i< ortOutput.size(); i++) {
    float* data = nullptr;
    ost = OrtGetTensorMutableData(ortOutput[i], reinterpret_cast<void **>(&data));
    OrtReleaseValue(ortOutput[i]);
    for(int r = 0; r < outputM[i].size(); r++){  // Determine size from ortOutput[i]
        outputM[i][r] = data[r];
    }
```

**Comment by SiR0N** [comment]
Hi @addisonklinke,
