### ISSUE TITLE
Question about load sklearn converted onnx model

### ISSUE THREAD

**Issue by qw2208** [microsoft/onnxruntime#1569]
I converted the sklearn model following the [tutorial](http://onnx.ai/sklearn-onnx/auto_examples/plot_tfidfvectorizer.html) and tried to load the model with the onnxruntime_cxx_api.

It run properly for `GetOutputName(output i, allocator)`. However, when I tried to run `typeinfo.GetTensorTypeAndShapeInfo()` for the second output, the program crashed throwing "allocation failure".

The program screen shot is like the following:
![WeChat Screenshot_20190806220804](https://user-images.githubusercontent.com/24438413/62546777-b1da7500-b896-11e9-913d-111d4978adcb.png)

I'm not sure if I'm using the `GetTensorTypeAndShapeInfo` properly. Any suggestions?

**Comment by RyanUnderhill** [comment]
Is the error happening on line 199? I'm curious if it's hitting this error handler in the C++ API:

https://github.com/microsoft/onnxruntime/blob/9e926fef1cf7c0ed9ccde5e88453fd91266f3c9b/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L61

**Comment by qw2208** [comment]
Yes, you're correct. Seems p is not allocated:
![WeChat Screenshot_20190807110624](https://user-images.githubusercontent.com/24438413/62591834-80e45980-b903-11e9-9c55-51ca597fba88.png)
Is the output format of [tutorial](http://onnx.ai/sklearn-onnx/auto_examples/plot_tfidfvectorizer.html) not supported by `GetTensorTypeAndShapeInfo`? `InferenceSession` (python runtime api) of the pre-trained onnx model gives the correct outcome.

**Comment by RyanUnderhill** [comment]
Hmm, I tried stepping through multiple codepaths of Session::GetOutputTypeInfo but I don't see how it can ever return a nullptr TypeInfo. Is it possible for you to share more of your source code or debug into that function to see what codepath it takes?

**Comment by RyanUnderhill** [comment]
I found the problem. It does happen inside of the GetTensorTypeAndShapeInfo() function. Since the output type is not a tensor, getting the tensor info fails and returns a nullptr. Instead of returning an error, the calling code sees it as an allocation failure.

So we should change our code to report a better error here, but a workaround in your code would be to just do this first:

    auto type=type_info.GetONNXType();
    if(type==ONNX_TYPE_TENSOR)
        // Get the tensor info.

In your model, the type is ONNX_TYPE_SEQUENCE. So getting the tensor info fails.
