### ISSUE TITLE
Onnxruntime-gpu 1.8.0[Build] 

### ISSUE THREAD

**Issue by adamgeddon1686** [microsoft/onnxruntime#15729]
### Describe the issue

I can no longer install version 1.8.0 using pip to install this dependency on a colab juypter notebook. I am a neophyte to coding so I am not really sure how to fix this as there was a rather major change from 1.8.0 to 1.9 that would require me to rewrite stuff I don't think I am equipped to rewrite. Is there some other way to install this version in colab beside !pip install?

### Urgency

This isn't urgent but I feel like it is a simple fix, I am just not equipped to handle it.

### Target platform

Google Colab, Linux Juypter Notebook Python Enviornment

### Build script

Not sure 

### Error / output

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.8.0 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1)
ERROR: No matching distribution found for onnxruntime-gpu==1.8.0

**Comment by snnn** [comment]
Sorry I don't know what is "colab-wheels". I cannot help.  If you are interested in getting onnxruntime 1.8.0, you can find it at https://pypi.org.
