### ISSUE TITLE
[Dev Build] How can the saved runtime format .onnx file be saved in an official supported compatible format?

### ISSUE THREAD

**Issue by ivberg** [microsoft/onnxruntime#15721]
[Dev Build] How can the saved runtime format .onnx file be saved in an official supported compatible opset format (v17?) ?
The original model file does not have this issue

I am using a [dev build](https://onnxruntime.ai/docs/build/custom.html) of onnx.
I checked out the latest release - >
git checkout v1.14.1

I am saving the partially optimized output using optimized_model_filepath in [sessions options](https://onnxruntime.ai/docs/performance/model-optimizations/graph-optimizations.html#offline-mode). The issue persists even if using GraphOptimizationLevel::ORT_DISABLE_ALL 

The problem seems to be the "com.ms.internal.nhwc v18" import in the resulting .onnx output file.
   Note: When I use an official onnx build I see "com.ms.internal.nhwc v17"

When I try to read the .onnx file using the python lib from say [onnx_opcounter](https://github.com/gmalivenko/onnx-opcounter) I get this error.

>onnx_opcounter --calculate-macs model.onnx
Traceback (most recent call last):
  File "C:\Program Files\Python310\Scripts\onnx_opcounter-script.py", line 33, in <module>
    sys.exit(load_entry_point('onnx-opcounter==0.0.3', 'console_scripts', 'onnx_opcounter')())
  File "C:\Program Files\Python310\lib\site-packages\onnx_opcounter\cli.py", line 17, in main
    print('Number of MACs in the model: {}'.format(calculate_macs(model)))
  File "C:\Program Files\Python310\lib\site-packages\onnx_opcounter\onnx_opcounter.py", line 90, in calculate_macs
    sess = rt.InferenceSession('+all-intermediate.onnx')
  File "C:\Users\ivberg\AppData\Roaming\Python\Python310\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\ivberg\AppData\Roaming\Python\Python310\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 384, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from +all-intermediate.onnx failed:D:\a\_work\1\s\onnxruntime\core/graph/model_load_utils.h:57 **onnxruntime::model_load_utils::ValidateOpsetForDomain ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 18 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain com.ms.internal.nhwc is till opset 17.**

I tried the following with no luck
1. I did look at [enable_reduced_operator_type_support](https://onnxruntime.ai/docs/build/custom.html#build-option-to-reduce-build-to-required-operator-kernels) but it was confusing how to only enable only up to the official version support

**Comment by pranavsharma** [comment]
> When I use an official onnx build I see "com.ms.internal.nhwc v17"

Which version of the official build you're using? I assume you're building from source the same version?
Irrespective, you can always edit the onnx model file and update the opset version. It's just a protobuf file.

**Comment by ivberg** [comment]
Thanks @pranavsharma. I will try your suggestions.
