### ISSUE TITLE
Load onnx failed(segmentation fault) with version 1.14.1

### ISSUE THREAD

**Issue by w-okada** [microsoft/onnxruntime#15742]
### Describe the issue

When I load a onnx file with onnxruntime==1.13.1, loading succeeded. However, with 1.14.1, failed(segmentation fault)

### To reproduce

1. clone https://github.com/w-okada/issue-001-onnx-1.14.1-freeze
2. pip install onnxruntime==1.13.1 
3. python python test_metadata.py -> success
4. pip install onnxruntime==!.14.1
5. python python test_metadata.py -> fail

### Platform

Linux

### OS Version

Debian GNU/Linux 11 (bullseye)

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU, CUDA, DirectML

**Comment by snnn** [comment]
Not reproducible. Though the model loading process was unusually slow, it didn't crash.
