### ISSUE TITLE
ARM32v7 Cross Compile Broken due to protobuf Bug

### ISSUE THREAD

**Issue by shawncal** [microsoft/onnxruntime#1574]
Protobuf introduced a bug which causes the following error on ARM32v7 builds of onnxruntime (via [dockerfile](https://github.com/Microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.arm32v7)):

`libprotobuf.a(arena.cc.o): in function google::protobuf::internal::ArenaImpl::Init():
arena.cc:(.text+0x24): undefined reference to __atomic_fetch_add_8`

The following commit fixes the above problem:
[https://github.com/protocolbuffers/protobuf/commit/55ed1d427ccc0d200927746329ac9b811dee77b9](https://github.com/protocolbuffers/protobuf/commit/55ed1d427ccc0d200927746329ac9b811dee77b9)

Request: please bump onnxruntime's protobuf submodule to a newer version that includes the above fix.

**Comment by snnn** [comment]
#1433

**Comment by RyanUnderhill** [comment]
As @snnn linked, we'll bump to the next version once it's released.

**Comment by shawncal** [comment]
Thanks!
