### ISSUE TITLE
Convert ONNX to ORT - invalid ORT format

### ISSUE THREAD

**Issue by nezaBacar** [microsoft/onnxruntime#15756]
### Describe the issue

Hi, I am trying to run stable diffusion inference in the browser. I tested the pipeline with the smaller model and realised that I had to convert the unet to ORT model (check out this issue: https://github.com/microsoft/onnxruntime/issues/14583). The smaller version of stable diffusion converted fine but while trying to convert stable diffusion v1.4 I get an error: file does not appear to be a valid ORT format model.

### To reproduce

Load the unet model from unet folder:
https://drive.google.com/drive/u/0/folders/16zlJ4ePE-vhg1YEOcXQJzvna2sQmLSzZ
Try to convert it with this command:
`python -m onnxruntime.tools.convert_onnx_models_to_ort model.onnx --optimization_style Fixed`

An issue occurs: 
`Converted 1/1 models successfully.
Generating config file from ORT format models with optimization style 'Fixed' and level 'all'
Traceback (most recent call last):
  File "D:\Miniconda\envs\onnx\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Miniconda\envs\onnx\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Miniconda\envs\onnx\lib\site-packages\onnxruntime\tools\convert_onnx_models_to_ort.py", line 363, in <module>    convert_onnx_models_to_ort()
  File "D:\Miniconda\envs\onnx\lib\site-packages\onnxruntime\tools\convert_onnx_models_to_ort.py", line 359, in convert_onnx_models_to_ort
    create_config_from_models(converted_models, config_file, args.enable_type_reduction)
  File "D:\Miniconda\envs\onnx\lib\site-packages\onnxruntime\tools\ort_format_model\utils.py", line 37, in create_config_from_models
    required_ops, op_type_processors = _extract_ops_and_types_from_ort_models(model_files, enable_type_reduction)
  File "D:\Miniconda\envs\onnx\lib\site-packages\onnxruntime\tools\ort_format_model\utils.py", line 21, in _extract_ops_and_types_from_ort_models
    model_processor = OrtFormatModelProcessor(str(model_file), required_ops, op_type_usage_manager)
  File "D:\Miniconda\envs\onnx\lib\site-packages\onnxruntime\tools\ort_format_model\ort_model_processor.py", line 23, in __init__
    raise RuntimeError("File does not appear to be a valid ORT format model: '{}'".format(model_path))
RuntimeError: File does not appear to be a valid ORT format model: 'C:\Users\Desktop\mag\stable-diffusion\stable_diffusion_onnx_\unet\model.ort'`

### Urgency

It's somewhat urgent. Working on my masters thesis.

### Platform

Windows

### OS Version

/

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

/

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

/

**Comment by edgchen1** [comment]
Tried with ORT 1.14.1. I was unable to reproduce the same issue with `model.onnx`. It appears to have external data in a `weights.pb` file which I did not have in the same directory, so I got a different error about not being able to open that file.

If you can provide all the referenced external data files I can try again.

**Comment by nezaBacar** [comment]
Oops, I forgot to attach it. It's in the folder now.

**Comment by edgchen1** [comment]
Ok, I can reproduce it now. It looks like the ORT format model is not getting converted correctly as it is empty. This explains the later error message but ideally it would have failed earlier.

The ORT format is a FlatBuffers schema and I think we may be hitting a FlatBuffers size limit here. The answer [here](https://stackoverflow.com/questions/59185516/do-flatbuffers-have-size-limits) says the largest a single FlatBuffer can be is 2GB, but the `weights.pb` file itself is >3GB.

**Comment by nezaBacar** [comment]
Okay, thank you for your answer. So there is no way to convert the model to ORT? 
I wanted to do that since onnxruntime-web does not support the onnx external data format yet and ORT puts the files into one. Do you think there is any other way that I could run an inference with this model on web?

**Comment by edgchen1** [comment]
> So there is no way to convert the model to ORT?

Not at the moment, with the 2GB size limit of the ORT format.

> Do you think there is any other way that I could run an inference with this model on web?

@guschmue Any suggestions?

**Comment by guschmue** [comment]
Although we understand the desire to run stable diffusion in the browser, it seems that for now it is out of reach for onnxruntime-web. There are a couple of reasons for this. 
Firstly, wasm is 32-bit and limited to 4GB which is not enough to load/run all models from a sd pipeline. 
Secondly, the fp16 onnx models for sd require around 6-8GB gpu memory and there is no fast fp16 implementation for onnxruntime-web. This means that you would need to use fp32 which makes the memory issue even worse. 
Thirdly, running sd on a cpu is not ideal and wasm would be slower than native cpu. Webgl isn’t that much faster and is missing a bunch of ops for sd.

Upcoming webgpu might enable sd. We enable this in ort-1.15 but it is brand new and experimental. 
We need to implement more ops and much optimization has to happen. 
And we need to find a way of dealing with the 32 bit wasm limitation (ie. memory64).

So hopefully in a couple of months that becomes a possibility.

**Comment by nezaBacar** [comment]
Okay, thank you so much for the response!
