### ISSUE TITLE
[Build]  how to build it in jetson nx 4.6  ?

### ISSUE THREAD

**Issue by Cats-eat-peppercorns** [microsoft/onnxruntime#15784]
### Describe the issue

系统版本是ubuntu18.04,aarch64的。我的cuda版本为10.2所以我要装onnxruntime1.6版本。但是官方没有对应的包，所以我只能尝试从源码编译，我使用./build.sh --config Release --update --build --parallel --build_wheel  --use_tensorrt --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu  --tensorrt_home /usr/lib/aarch64-linux-gnu但是报错了。我不知道该从哪里寻找相关资料。请问哪里可以找到在这个系统上从源码编译的教程呢？

### Target platform

。

### Build script

。

### Error / output

。

**Comment by Cats-eat-peppercorns** [comment]
The system version is ubuntu 18.04, aarch64. My cuda version is 10.2 so I have to install onnxruntime 1.6. But there is no official package for it, so I have to try to build it from source, I use . /build.sh --config Release --update --build --parallel --build_wheel --use_tensorrt --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64 -linux-gnu --tensorrt_home /usr/lib/aarch64-linux-gnu but it reports an error. I don't know where to look for information about it. Where can I find a tutorial for compiling from source on this system?

**Comment by Cats-eat-peppercorns** [comment]
this is the wrong


Use gtest from submodule
CMake Error at CMakeLists.txt:478 (add_subdirectory):
  The source directory

    /home/robo/onnxruntime-v1.6.0/cmake/external/googletest

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:479 (set_target_properties):
  set_target_properties Can not find target to add properties to: gmock


CMake Error at CMakeLists.txt:480 (set_target_properties):
  set_target_properties Can not find target to add properties to: gmock_main


CMake Error at CMakeLists.txt:481 (set_target_properties):
  set_target_properties Can not find target to add properties to: gtest


CMake Error at CMakeLists.txt:482 (set_target_properties):
  set_target_properties Can not find target to add properties to: gtest_main


CMake Error at CMakeLists.txt:483 (add_library):
  add_library cannot create ALIAS target "GTest::gmock" because target
  "gmock" does not already exist.


CMake Error at CMakeLists.txt:484 (add_library):
  add_library cannot create ALIAS target "GTest::gmock_main" because target
  "gmock_main" does not already exist.


CMake Error at CMakeLists.txt:485 (add_library):
  add_library cannot create ALIAS target "GTest::gtest" because target
  "gtest" does not already exist.


CMake Error at CMakeLists.txt:486 (add_library):
  add_library cannot create ALIAS target "GTest::gtest_main" because target
  "gtest_main" does not already exist.


CMake Error at CMakeLists.txt:526 (add_subdirectory):
  The source directory

    /home/robo/onnxruntime-v1.6.0/cmake/external/nsync

  does not contain a CMakeLists.txt file.


Use protobuf from submodule
CMake Error at CMakeLists.txt:565 (add_subdirectory):
  add_subdirectory given source
  "/home/robo/onnxruntime-v1.6.0/cmake/external/protobuf/cmake" which is not
  an existing directory.


CMake Error at CMakeLists.txt:574 (add_library):
  add_library cannot create ALIAS target "protobuf::libprotobuf" because
  target "libprotobuf" does not already exist.


CMake Error at CMakeLists.txt:626 (add_subdirectory):
  The source directory

    /home/robo/onnxruntime-v1.6.0/cmake/external/date

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:642 (add_subdirectory):
  The source directory

    /home/robo/onnxruntime-v1.6.0/cmake/external/re2

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:643 (set_target_properties):
  set_target_properties Can not find target to add properties to: re2


CMake Error at CMakeLists.txt:644 (add_library):
  add_library cannot create ALIAS target "re2::re2" because target "re2" does
  not already exist.


CMake Error at CMakeLists.txt:837 (add_subdirectory):
  The source directory

    /home/robo/onnxruntime-v1.6.0/cmake/external/onnx

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:842 (target_compile_definitions):
  Cannot specify compile definitions for target "onnx" which is not built by
  this project.


CMake Error at CMakeLists.txt:846 (set_target_properties):
  set_target_properties Can not find target to add properties to: onnx


CMake Error at CMakeLists.txt:847 (set_target_properties):
  set_target_properties Can not find target to add properties to: onnx_proto


CMake Error at CMakeLists.txt:885 (add_subdirectory):
  The source directory

    /home/robo/onnxruntime-v1.6.0/cmake/external/flatbuffers

  does not contain a CMakeLists.txt file.


-- CMAKE_CUDA_COMPILER_VERSION: 10.2.300
CMake Error at onnxruntime_providers.cmake:415 (add_subdirectory):
  The source directory

    /home/robo/onnxruntime-v1.6.0/cmake/external/onnx-tensorrt

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:1371 (include)

**Comment by HEIseYOUmolc** [comment]
do you resolve，or give up？
