### ISSUE TITLE
[Build] Successful but throws error while importing 

### ISSUE THREAD

**Issue by shub-kris** [microsoft/onnxruntime#15783]
### Describe the issue

Hi, I followed the instructions to install the ONNXRuntime as mentioned here:
https://onnxruntime.ai/docs/build/inferencing.html

The build is successful but, when I am trying to use:
```
import onnxruntime
```

It throws this error:

```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jupyter/onnxruntime/onnxruntime/__init__.py", line 52, in <module>
    from onnxruntime.capi import onnxruntime_validation
ModuleNotFoundError: No module named 'onnxruntime.capi

```

### Urgency

Urgent

### Target platform

"Ubuntu 20.04.5 LTS"

### Build script

./build.sh --config RelWithDebInfo --build_shared_lib --parallel

### Error / output

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jupyter/onnxruntime/onnxruntime/__init__.py", line 52, in <module>
    from onnxruntime.capi import onnxruntime_validation
ModuleNotFoundError: No module named 'onnxruntime.capi

**Comment by satyajandhyala** [comment]
Please try running python from any directory other then onnxruntime root directory.

**Comment by satyajandhyala** [comment]
This is well known issue that trying to import onnxruntime in python in the onnxruntime root directory. It will confuse python interpreter and tries to load current directory as a python module and fails.

**Comment by shub-kris** [comment]
Anywhere else, I couldn't import. I downloaded the nightly whl file and installed it using pip
