### ISSUE TITLE
How to use batch predict using v0.5

### ISSUE THREAD

**Issue by bitnick10** [microsoft/onnxruntime#1579]
Since v0.5, the C++ API can return a `std::vector<Value>` but the Session::Run API is not using the `std::vector<Value>` as input (it uses the `Value*` as input). How to wrap the API like below?
```
std::vector<std::array<float, 5>> Predict(const std::vector<std::array<float, 224 * 224 * 3>>& ins) {
	
}
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- ONNX Runtime installed from (source or binary): nuget
- ONNX Runtime version: 0.5
- Visual Studio version (if applicable): 2017

**Comment by RyanUnderhill** [comment]
The Session::Run method doesn't take std::vector<Value> as input since that would require all users to store their inputs into vectors. It's fairly easy to use .data() and .size() to pass a vector in through it. Of course, if this is a common request we'll probably add a method that does this for convenience!

To wrap that API you'll need to create an Ort::Value out of the input data. You should be able to do something like this (typed directly, so might have some mistakes):

    std::vector<std::array<float, 5>> Predict(const std::vector<std::array<float, 224 * 224 * 3>>& ins) {
    {
    Ort::AllocatorInfo allocator_Info = Ort::AllocatorInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
    std::vector<int64_t> ins_shape{ 224, 224, 3};
    Ort::Value input_tensor = Ort::Value::CreateTensor(allocator_info, ins.data(), ins.size(), ins_shape.data(), ins_shape.size());
   // Now pass input_tensor into Run()...

You can't pass any memory directly into Run() but you can create a tensor out of the memory directly.

Were you able to get it to work using that?

**Comment by bitnick10** [comment]
Can't run. CreateTensor doesn't support std::vector<std::array<float, 224 * 224 * 3>> as parameter.

**Comment by bitnick10** [comment]
Can't run. CreateTensor doesn't support std::vector<std::array<float, 224 * 224 * 3>> as parameter.
The `TypeToTensorType<T>::type` doesn't support std::array<float, 224 * 224 * 3>.

**Comment by RyanUnderhill** [comment]
Ah, well 'ins' is a vector of the arrays, so you'll need to pass in one of them:

    std::vector<std::array<float, 5>> Predict(std::vector<std::array<float, 224 * 224 * 3>>& ins) {
    {
        Ort::AllocatorInfo allocator_Info = Ort::AllocatorInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
        std::vector<int64_t> ins_shape{ 224, 224, 3};
        Ort::Value input_tensor = Ort::Value::CreateTensor(allocator_info, ins[0].data(), ins[0].size(), ins_shape.data(), ins_shape.size());

Does that help clarify it?

**Comment by bitnick10** [comment]
That can run. but I want predict ins, not ins[0].It seems this API doesn't the support that.Should I follow the https://github.com/microsoft/onnxruntime/issues/1568

**Comment by RyanUnderhill** [comment]
I'm not sure what you mean by 'predict ins'. But that was just meant to be an example of how to create a tensor given a shape (and using existing data). What is the error you are getting now?

**Comment by bitnick10** [comment]
```
std::vector<std::array<float, 5>> Predict(const std::vector<std::array<float, 224 * 224 * 3>>& ins) {
	std::vector<std::array<float, 224 * 224 * 3>> ret;
	Ort::AllocatorInfo allocator_Info = Ort::AllocatorInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
	std::vector<int64_t> ins_shape{ 224, 224, 3 };
	for (int i = 0; i < ins.size(); i++) {
		Ort::Value input_tensor = Ort::Value::CreateTensor(allocator_info, ins[i].data(), ins[i].size(), ins_shape.data(), ins_shape.size());
		auto output_tensors = session.Run(Ort::RunOptions{ nullptr }, input_node_names.data(), &input_tensor, 1, output_node_names.data(), 1);
		std::array<float, 224 * 224 * 3> t = SomeTransform(output_tensors);
		ret.push_back(t);
	}
	return ret;
}
```
Use this API like this?

**Comment by RyanUnderhill** [comment]
That will work, though you probably don't want to be making copies of the output_tensors data if you can help it. You also probably don't want to be copying std::array<float, 224*224*3> sized objects by value.

Otherwise, it should work!

**Comment by bitnick10** [comment]
Previous code is not batch predict,it's predict one by one. Why `session.Run` return a` std::vector` of `Value` instead of return a `Value`? I thought `session.Run` can predict a lot once a time.

**Comment by RyanUnderhill** [comment]
A model can have multiple outputs, the return value of Run() is simply these multiple outputs. If the model has only one output, it's a vector of one item.

**Comment by bitnick10** [comment]
onnxruntime(C/C++) doesn't support like keras's [predict](https://keras.io/models/model/#predict) ? @RyanUnderhill

**Comment by RyanUnderhill** [comment]
@bitnick10 I'm not familiar with Keras's predict. Sorry about the delay, did you already figure this out or do you still have an unresolved question?

**Comment by bitnick10** [comment]
@RyanUnderhill ,I can batch predict now,first change symbolic dimension which can check issue 2174 out.

**Comment by RyanUnderhill** [comment]
Cool, closing this issue then
