### ISSUE TITLE
"Less" op does not support int64 input type

### ISSUE THREAD

**Issue by neginraoof** [microsoft/onnxruntime#1583]
**Describe the bug**
When running the GNMT onnx model, I see:
RuntimeError: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Less(9)

ORT "Less" op does not support long input type.
ONNX spec for "Less" op has support for this: https://github.com/onnx/onnx/blob/master/docs/Operators.md#less

**Urgency**
GNMT onnx model should be executed out of the box.
https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Translation/GNMT

**To Reproduce**
This is the exported ONNX model:
https://drive.google.com/open?id=1cWYUg1V1FFgFo8dF-W0hR2tyezCzY_UV

This is the line in the model which causes this issue:
https://github.com/NVIDIA/DeepLearningExamples/blob/b728d42771e0861f7f90e963c3c80b9a44df62a5/PyTorch/Translation/GNMT/seq2seq/models/attention.py#L81

**Comment by pranavsharma** [comment]
Would you like to contribute? Should be a simple change.

**Comment by RyanUnderhill** [comment]
I asked around a bit and it seems that double shouldn't be needed here, only float. Is there an option in the model export to only use float?

**Comment by neginraoof** [comment]
Thanks @RyanUnderhill, my bad. This is regarding int64 input type not supported. From this line in the model: https://github.com/NVIDIA/DeepLearningExamples/blob/b728d42771e0861f7f90e963c3c80b9a44df62a5/PyTorch/Translation/GNMT/seq2seq/models/attention.py#L81

**Comment by linkerzhang** [comment]
#1604 is adding the support.

**Comment by RanACohen** [comment]
I just compiled the master and I still get this error on GNMT:
runtimeError: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Less(9)

**Comment by RanACohen** [comment]
What is ORT and how do I verify it?

**Comment by RanACohen** [comment]
It says 0.5.0, but as I said, I used the latest master and built it myself.

**Comment by RanACohen** [comment]
FYI, I created a new issue: #1700
Let's move the discussion there.
