### ISSUE TITLE
[Build]  Build with cuda11.3,  identifier "__hmul2_rn" is undefined 

### ISSUE THREAD

**Issue by 181802969** [microsoft/onnxruntime#15840]
### Describe the issue

identifier "__hmul2_rn" is undefined

### Target platform

aarch64, cuda11.3

### Build script

./build.sh  --use_cuda --cudnn_home /PATH/TO/CUDNN_HOME  --cuda_home /PATH/TO/CUDA_HOME --build_shared_lib --enable_pybind  --build_wheel --update --build --compile_no_warning_as_error --skip_tests

### Error / output

/home/share/cimc/home/lizhongxin/softwares/onnx/onnxruntime/onnxruntime/contrib_ops/cuda/bert/relative_attn_bias_impl.cu(159): 
error: identifier "__hmul2_rn" is undefined

I modified  the file "relative_attn_bias_impl.cu", and change "__hmul2_rn" to "__huml2_sat" , it seems that this problem is solved。

### GCC / Compiler Version

GCC 9.3.0, cuda11.3.0

**Comment by wangyems** [comment]
Thanks for reporting the issue. The reason is that __hmul2_rn is introduced since cuda 11.6. We can instead use __hmul2 for cuda version coverages.
