### ISSUE TITLE
[Mobile] Unexpected input data type. Actual: (tensor(uint8)) , expected: (tensor(float))

### ISSUE THREAD

**Issue by lmq5294249** [microsoft/onnxruntime#15861]
### Describe the issue

Unexpected input data type. Actual: (tensor(uint8)) , expected: (tensor(float))" UserInfo={NSLocalizedDescription=Unexpected input data type. Actual: (tensor(uint8)) , expected: (tensor(float))}: file ORTObjectDetection/ViewController.swift, line 141

### To reproduce

let interval: TimeInterval
        
        let inputName = "images"
        
        guard let rgbData = rgbDataFromBuffer(
            scaledPixelBuffer,
            byteCount: batchSize * inputWidth * inputHeight * inputChannels
        ) else {
            print("Failed to convert the image buffer to RGB data.")
            return nil
        }
        
        let inputShape: [NSNumber] = [batchSize as NSNumber,
                                      inputHeight as NSNumber,
                                      inputWidth as NSNumber,
                                      inputChannels as NSNumber]
        
        let inputTensor = try ORTValue(tensorData: NSMutableData(data: rgbData),
                                       elementType: ORTTensorElementDataType.uInt8,
                                       shape: inputShape)
        
        // Run ORT InferenceSession
        let startDate = Date()
        let outputs = try session.run(withInputs: [inputName: inputTensor],
                                      outputNames: ["output"],
                                      runOptions: nil)
        interval = Date().timeIntervalSince(startDate) * 1000
        
        guard let rawOutputValue = outputs["TFLite_Detection_PostProcess"] else {
            throw OrtModelError.error("failed to get model output_0")
        }
        let rawOutputData = try rawOutputValue.tensorData() as Data
        guard let outputArr: [Float32] = Array(unsafeData: rawOutputData) else {
            return nil
        }
打印报错信息
2023-05-09 10:06:35.026325+0800 ORTObjectDetection[9085:566869] 2023-05-09 10:06:35.026289 [I:onnxruntime:, inference_session.cc:1521 Initialize] Session successfully initialized.
Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=onnxruntime Code=2 "Unexpected input data type. Actual: (tensor(uint8)) , expected: (tensor(float))" UserInfo={NSLocalizedDescription=Unexpected input data type. Actual: (tensor(uint8)) , expected: (tensor(float))}: file ORTObjectDetection/ViewController.swift, line 141
2023-05-09 10:06:35.766127+0800 ORTObjectDetection[9085:566994] Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=onnxruntime Code=2 "Unexpected input data type. Actual: (tensor(uint8)) , expected: (tensor(float))" UserInfo={NSLocalizedDescription=Unexpected input data type. Actual: (tensor(uint8)) , expected: (tensor(float))}: file ORTObjectDetection/ViewController.swift, line 141

### Platform

iOS

### OS Version

IOS14

### ONNX Runtime Installation

Built from Source

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

V1.14.1

### ONNX Runtime API

Objective-C/Swift

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
Your model is expecting float input but you're providing uint8 data. 

>     let inputTensor = try ORTValue(tensorData: NSMutableData(data: rgbData), elementType: ORTTensorElementDataType.uInt8, shape: inputShape)

What model are you trying to run? Typically an image processing model expects the image data to be converted to float and normalized (after it's resized and cropped or letterboxed to match the model input height and width). If the model came from tensorflow the normalization would usually be to convert to float values in the range -1 to 1.

**Comment by lmq5294249** [comment]
I want to test this model in the IOS project using onnxruntime.
[osnet_x0_75_msmt17_combineall.ort.zip](https://github.com/microsoft/onnxruntime/files/11427957/osnet_x0_75_msmt17_combineall.ort.zip)
https://github.com/KaiyangZhou/deep-person-reid

On macos I can converted data to float like this  
img = cv2.imread("/Users/lin/Desktop/deep-person-reid/Data/other005.png")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img = cv2.resize(img, (128, 256))
img = img.astype(np.float32)
img = (img / 255.0 - [0.485, 0.456, 0.406]) / [0.229, 0.224, 0.225]  # 图像归一化
input_data = img.transpose((2, 0, 1)).reshape(1, 3, 256, 128)
input_data = input_data.astype(np.float32)
outputs = onnx_model.run(None, {"images": input_data})
outputs = np.squeeze(outputs)

but in the IOS project, I can't find a way to converted data to float.
This is the first time to use onnxtuntime on the mobile device.

**Comment by YUNQIUGUO** [comment]
Not sure if it fits actually your case, here's some sample code that might help:

```
// Step 1: Load PNG image data
guard let imagePath = Bundle.main.path(forResource: "your_image", ofType: "png") else {
    fatalError("Failed to find the PNG image")
}

guard let imageData = NSData(contentsOfFile: imagePath) else {
    fatalError("Failed to load PNG image data")
}

// Step 2: Convert image data to UIImage
guard let image = UIImage(data: imageData as Data) else {
    fatalError("Failed to create UIImage from image data")
}

// Step 3: Convert image from BGR to RGB
guard let cgImage = image.cgImage else {
    fatalError("Failed to convert UIImage to CGImage")
}

let colorSpace = CGColorSpaceCreateDeviceRGB()

let bitmapInfo: CGBitmapInfo = [
        CGBitmapInfo(rawValue: CGImageAlphaInfo.noneSkipLast.rawValue),
        CGBitmapInfo(rawValue: CGBitmapInfo.byteOrder32Little.rawValue)
]
    
guard let context = CGContext(data: nil, width: cgImage.width, height: cgImage.height, bitsPerComponent: 8, bytesPerRow: 4 * cgImage.width, space: colorSpace, bitmapInfo: bitmapInfo.rawValue) else {
    fatalError("Failed to create CGContext")
}

context.draw(cgImage, in: CGRect(x: 0, y: 0, width: cgImage.width, height: cgImage.height))

// Step 4: Resize the image
let desiredSize = CGSize(width: 500, height: 500) // Set your desired dimensions
let renderer = UIGraphicsImageRenderer(size: desiredSize)
let resizedImage = renderer.image { context in
    let cgImage = context.cgContext.makeImage()
    context.cgContext.draw(cgImage!, in: CGRect(origin: .zero, size: desiredSize))
}

// Step 5: Convert the resized image to a float buffer
guard let resizedCGImage = resizedImage.cgImage else {
    fatalError("Failed to convert UIImage to CGImage")
}
// repeat to create context for resized image again
let width = resizedCGImage.width
let height = resizedCGImage.height
let bytesPerPixel = 4 // Assuming 32 bits per pixel (8 bits per channel for RGB + 8-bit alpha)
let bytesPerRow = bytesPerPixel * width

guard let resizedContext = CGContext(data: nil, width: width, height: height, bitsPerComponent: 8, bytesPerRow: bytesPerRow, space: colorSpace, bitmapInfo: bitmapInfo.rawValue) else {
    fatalError("Failed to create CGContext")
}

resizedContext.draw(resizedCGImage, in: CGRect(x: 0, y: 0, width: width, height: height))

guard let pixelData = resizedContext.data

let floatData = NSMutableData(bytes: pixelData, length: bytesPerRow * height)

// Use this NSData to make ORTTensor value
let inputTensor = try ORTValue(tensorData: floatData,
                                                     elementType: ORTTensorElementDataType.float,
                                                      shape: inputShape)
```

also, after we include ort extensions support for pre/post-processing it would be much easier and direct to do this in the ios swift app for object detection scenario.

**Comment by skottmckay** [comment]
It would be recommended to use the new tools to add pre-processing (and potentially post-processing) to the model so you have consistent behavior on all platforms. 

For object-detection see https://github.com/microsoft/onnxruntime-extensions/blob/main/tutorials/yolo_e2e.py for an end-to-end example of augmenting the model. The onnxruntime-extensions package would then be used to provide any custom operators required (in this case conversion from png to RGB).

Example app using this: https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/object_detection/android
