### ISSUE TITLE
[Web] WebGPU backend error on npm nightly package

### ISSUE THREAD

**Issue by gegogi** [microsoft/onnxruntime#15860]
### Describe the issue

Hi!
I am trying to test WebGPU backend using npm nightly ( 1.15.0-dev.20230502-abdd4f518a ) but hitting the following error.

![image](https://user-images.githubusercontent.com/639708/236977062-332e3022-302c-4059-8a0e-bd72afbd35c8.png)

### To reproduce

Install the npm package onnxruntime-web@1.15.0-dev.20230502-abdd4f518a.
And run the following code:
```
const ort = require('onnxruntime-web');

// use an async context to call onnxruntime functions.
async function main() {
    try {
        // create a new session and load the specific model.
        //
        // the model in this example contains a single MatMul node
        // it has 2 inputs: 'a'(float32, 3x4) and 'b'(float32, 4x3)
        // it has 1 output: 'c'(float32, 3x3)
        const session = await ort.InferenceSession.create('./model.onnx', {executionProviders: ['webgpu']});

        // prepare inputs. a tensor need its corresponding TypedArray as data
        const dataA = Float32Array.from([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]);
        const dataB = Float32Array.from([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]);
        const tensorA = new ort.Tensor('float32', dataA, [3, 4]);
        const tensorB = new ort.Tensor('float32', dataB, [4, 3]);

        // prepare feeds. use model input names as keys.
        const feeds = { a: tensorA, b: tensorB };

        // feed inputs and run
        const results = await session.run(feeds);

        // read from results
        const dataC = results.c.data;
        document.write(`data of result tensor 'c': ${dataC}`);

    } catch (e) {
        document.write(`failed to inference ONNX model: ${e}.`);
    }
}

main();
```

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.0-dev.20230502-abdd4f518a

### Execution Provider

Other / Unknown

**Comment by fs-eire** [comment]
looks like that build is too old. a fix to this issue is not included. let me trigger a new nightly publish.

**Comment by fs-eire** [comment]
also ,
`const ort = require('onnxruntime-web');`
--->
`const ort = require('onnxruntime-web/webgpu');

**Comment by gegogi** [comment]
I'm glad to tell you it's working.

![image](https://user-images.githubusercontent.com/639708/237024593-6b47db69-597f-467b-9d90-44b7dbf67bbb.png)
