### ISSUE TITLE
[Web]  Error: Can't access output tensor data. error code = 1 running session with a logistic regression model

### ISSUE THREAD

**Issue by pedrovgs** [microsoft/onnxruntime#15918]
### Describe the issue

I've exported a logistic regression model from my python code using the following code:

```python
model = LogisticRegression(n_jobs = os.cpu_count(), verbose = True)
model.fit(data_train, labels_train)

input_type = FloatTensorType([None, (100*100)])
input_name = 'float_input'
initial_type = [(input_name, input_type)]
onx = convert_sklearn(model, initial_types = initial_type, verbose = 1)
file_name = "./output/hwemoji.onnx"
with open(file_name, "wb") as f:
    f.write(onx.SerializeToString())
```

as you can see, is just a sklearn logistic regression using an array of 100 * 100 floats as input representing points in the space.

The file is exported as expected and when I use the Python runtime to evaluate the model, prediction is obtained as you would expect. However, when I load the model using the web runtime I execute it I get this error ``Error: Can't access output tensor data. error code = 1 running session with a logistic regression model``.

This is the typescript code:

```typescript
xport async function predict(points: Points): Promise<PredictionResult> {
    const session = await InferenceSession.create("./hwemoji.onnx");
    const inputName = session.inputNames[0];
    const outputName = session.outputNames[0];
    const inputData = transformPointsIntoData(points);
    const inputTensor = new Tensor('float32', inputData, [1, inputData.length]);
    const feeds = { float_input: inputTensor };
    const outputMap = await session.run(feeds);
    const outputTensor = outputMap[outputName];
    return [];
}

function transformPointsIntoData(points: Points): Float32Array {
    const result = Float32Array.from({ length: 100 * 100 }, () => 0.0);
    return result
}
```
as you can see, the input I use as a tensor is another array with the same shape the model generated from the python code has. The library and the model are loaded as expected, but when I execute ``session.run(feeds)`` an exception is thrown and the only message I get is this: `` Error: Can't access output tensor data. error code = 1 running session with a logistic regression model``.

<img width="606" alt="Screenshot 2023-05-12 at 02 25 20" src="https://github.com/microsoft/onnxruntime/assets/4030704/f40b3ba7-2b90-4555-ba87-c270c1642a4d">

### To reproduce

I can't provide a working example right now, but please let me know if there is something else I can do in order to give you more information.

### Urgency

Not urgent at all. I'm just trying to get a model running from a website and I don't know why Onnx is not working.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.0

### Execution Provider

WASM

**Comment by fs-eire** [comment]
I don't see your model and don't know the detail of the model. But since you use `convert_sklearn` to generate onnx model , I guess this is the same problem to #15511. Easiest way to validate is check the model output type using [Netron](https://netron.app/).

**Comment by pedrovgs** [comment]
This is the model and the analysis generated by Netro. I hope it helps 😃 

<img width="373" alt="Screenshot 2023-05-12 at 09 27 59" src="https://github.com/microsoft/onnxruntime/assets/4030704/764e09ab-69b6-46b4-b6b9-b906d140ec57">

[model.onnx.zip](https://github.com/microsoft/onnxruntime/files/11460503/model.onnx.zip)

**Comment by fs-eire** [comment]
According to the document (https://onnx.ai/sklearn-onnx/parameterized.html#classifiers), you can disable the converter to output `ZipMap` operator using `options={type(model): {'zipmap': False}}`. I didn't use that before but it looks may work.

**Comment by pedrovgs** [comment]
It woks @fs-eire 👏 . I've changed how we export the model and used this config you suggested:

```python
onx = convert_sklearn(model, initial_types = initial_type, verbose = 1, options = {type(model): {'zipmap': False}})
```

now the model works. Thank you so much, closing the issue now 😃
