### ISSUE TITLE
[Build] Please publish full PDBs to symbols server

### ISSUE THREAD

**Issue by davidmatson** [microsoft/onnxruntime#15932]
### Describe the issue

We get failures from internal security analysis when PDBs aren't available and had to add this DLL to an exception list. Per a previous comment, this could be done but hasn't happened yet:
https://github.com/microsoft/onnxruntime/issues/11243#issuecomment-1101621684

### Target platform

n/a

### Build script

n/a

### Error / output

n/a

**Comment by snnn** [comment]
I will do it. But, for your information, now there are 138 open issues under this "build" tag.

**Comment by snnn** [comment]
Symbols for ONNX Runtime 1.15.1 release has been published to [Microsoft symbol server](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/microsoft-public-symbols). Please check.

**Comment by davidmatson** [comment]
Thanks!
