### ISSUE TITLE
Softmax returning 1's when running under NNAPI execution provider

### ISSUE THREAD

**Issue by JoshPPrieto** [microsoft/onnxruntime#15949]
### Describe the issue

When running [SqueezeNet (opset 9 and 12)](https://github.com/onnx/models/tree/6ab957a2fe61f34a76c670946f7cbd806d2cacca/vision/classification/squeezenet) using nnapi in our platform, we are getting wrong outputs (a vector containing 1's). So far, we think it's related to the axis selection. 

We tried to force the proper axis under the hood (in lower levels of the stack, below the nnapi provider), and we obtain the correct results. While investigating this, we found that in `onnxruntime/core/optimizer/transpose_optimizer/transpose_optimizer.cc`, `HandleSoftHardMax` function contains a 2D coercion for Softmax with opset <13. So we updated SqueezeNet to contain Softmax opset 13 and we found that the inference outputs correct values.

Long story short, we'd like to know if this behavior can be reproduced, and if I'm missing some other optimization pass which modifies the axis of the operator (or if I'm missing the point). The issue might be in lower levels, but I'd like to discard this part as the flawed one.

PD: For more context, using SqueezeNet opset 9 and 12, Softmax consumes and provides tensors with shape 1x100x1x1. After transpose optimizations (or some other passes) the shape is converted to 1x1x1x1000. With opset 13, the Softmax is wrapped by a Flatten and Reshape(4) operations, so the dimension is 1x1000 (and no coercion).

### To reproduce

We reproduce it using the [SqueezeNet models](https://github.com/onnx/models/tree/6ab957a2fe61f34a76c670946f7cbd806d2cacca/vision/classification/squeezenet) and using `onnx_test_runner -c 1 -r 1 -e nnapi -v <model_dir>` and also using `NNRT_LOG_LEVEL=5 ORT_DEBUG_NODE_IO_DUMP_OUTPUT_DATA=1 ./onnxruntime_perf_test -e nnapi <path-to-model.onnx> -v`

### Urgency

Moderate

### Platform

Linux

### OS Version

Yocto based, Kernel 6.1

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

C++

### Architecture

ARM64

### Execution Provider

NNAPI

**Comment by skottmckay** [comment]
Thanks for the detailed repro instructions. PR should hopefully address the issue.

**Comment by JoshPPrieto** [comment]
Thank you for the response and work! I'll try it (hopefully soon) and share the outcome.
