### ISSUE TITLE
Unable to find CUDA or DirectML in ORT packages via C#

### ISSUE THREAD

**Issue by mans0987** [microsoft/onnxruntime#15953]
### Describe the issue

getting error when trying to use CUDA or DirectML provider:

When trying to use CUDA, I am getting this error:
`"Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in DLL 'onnxruntime'`

and when trying to use DirectML, I am getting this error:

`Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_DML' in DLL 'onnxruntime'.`

The code that I am using is as follows:

`var sessionOptions = new SessionOptions();

            switch (this.ExecutionProviderTarget)
            {
                case ExecutionProvider.DirectML:
                    sessionOptions.GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_ALL;
                    sessionOptions.EnableMemoryPattern = false;
                    sessionOptions.AppendExecutionProvider_DML(this.DeviceId);
                    sessionOptions.AppendExecutionProvider_CPU();
                    return sessionOptions;
                case ExecutionProvider.Cpu:
                    sessionOptions.AppendExecutionProvider_CPU();
                    return sessionOptions;
                default:
                case ExecutionProvider.Cuda:
                    sessionOptions.GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_ALL;
                    //default to CUDA, fall back on CPU if CUDA is not available.
                    sessionOptions.AppendExecutionProvider_CUDA(this.DeviceId);
                    sessionOptions.AppendExecutionProvider_CPU();
                    //sessionOptions = SessionOptions.MakeSessionOptionWithCudaProvider(cudaProviderOptions);
                    return sessionOptions;

            }`

The code is running on a laptop that has two GPUs in it:
1- Integrated GPU: Intel UHD Graphics 630:
![image](https://github.com/microsoft/onnxruntime/assets/87241557/e1b95a35-ac4f-48dc-bb19-1ca361f4bcfb)

2- NVIDIA GeForce GTX 1050
![image](https://github.com/microsoft/onnxruntime/assets/87241557/482def7b-877d-495a-9544-299813e34405)

when looking at the bin directory for files that are copied to the output, I can see that there are no such things as microsoft.ml.onnxruntime.DirectMl or microsoft.ml.onnxruntime.gpu.

![image](https://github.com/microsoft/onnxruntime/assets/87241557/c32212ac-54d6-487e-b2af-5e46724ca897)

The nuget packages are installed for the project.

![image](https://github.com/microsoft/onnxruntime/assets/87241557/5230d7c7-6153-42fe-86e1-bdf2d990e2f0)

The application work properly with CPU. Why I can not use DirectML or CUDA in my application?

### Urgency

The application works with CPU, but not with GPU, so it is good for development but can not for release as the system is very slow for any type of application.

### Target platform

windows 10 (64)

### Build script

I am suing Visual Studio 2022using

### Error / output

see above description

### Visual Studio Version

2022

**Comment by skottmckay** [comment]
I don't believe the setup currently supports using multiple native packages as they're all trying to provide an onnxruntime.dll. 

i.e. you would need to choose either the Microsoft.ML.OnnxRuntime.Gpu package for CUDA or the Microsoft.ML.OnnxRuntime.DirectML package for DirectML. Both contain onnxruntime.dll (which always includes the CPU EP) so you don't need Microsoft.ML.OnnxRuntime.

**Comment by fdwr** [comment]
Do you have all those packages installed simultaneously? I'm not sure what would happen if you install multiple conflicting packages, because it might pick one and ignore the others, which is probably what's happening - it's picking the CPU package only.

**Comment by mans0987** [comment]
I removed the reference to all other packages and has the only reference to 

![image](https://github.com/microsoft/onnxruntime/assets/87241557/328eb9f3-eeed-4193-900a-1b4c15132d86)

The generated code has these packages:

![image](https://github.com/microsoft/onnxruntime/assets/87241557/6c362792-3efb-450d-a0b4-0561ae8c07f4)

The error I am getting when trying to use DirectML is:
`The specified device interface or feature level is not supported on this system.`

It should be noted that if I use a CPU, it works properly.

Why I can not use DirectML on my laptop which has Intel Integrated GPU and NVIDIA GPU?

**Comment by fdwr** [comment]
Can you confirm that the newer DirectML.dll is being loaded by your executable? (e.g. in the Visual Studio debugger Modules window). If the DLL is copied alongside your exe, then the new DLL should be found. Otherwise ORT is likely trying to load DirectML.dll from the OS in C:\Windows\System32* (which is older).

**Comment by mans0987** [comment]
I can not see any DLL with a DirectML in its name in the output directory. (see above that shows DLLsthat copied to the output directory.

What is the exact name of DLL? I will try to find it and copied to output manually to see if the problem solves.

**Comment by mszhanyi** [comment]
@mans0987 
I came acroos the "Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in DLL 'onnxruntime'.
From my experience, I removed the Microsoft.ML.onnxruntime package and kept Microsoft.ML.onnxruntime.GPU package
![image](https://github.com/microsoft/onnxruntime/assets/16190118/0e685921-9e94-4ae3-bbc9-8fab2af6b6ee)

**Comment by mans0987** [comment]
after removing .gpu and changing the target CPU to x64 from any CPU, the directML execution works and I can see that GPU becomes busy processing, but it is slower than CPU :(  on my system.

**Comment by fdwr** [comment]
> but it is slower than CPU :( on my system

@mans0987: For both the `Integrated GPU: Intel UHD Graphics 630` and `NVIDIA GeForce GTX 1050`? It is possible for models run slower on GPU than CPU, especially small models with few nodes or small tensors, where just the time needed to upload/download data and initiate the machinery costs more than the computation time. Throwing lots of data with large tensors is where GPU's shine. Another possibility is that CPU fallback is happening, causing stalls between GPU and CPU. Do you see any logging (if you enable it or run it from a command line) warning that some nodes could not be assigned to the preferred execution provider?

**Comment by mans0987** [comment]
I can not run it on NVIDIA as that GPU doesn't have enough memory. For Integrated GPU, I believe the behavior should be expected as I am monitoring the newer and transferring data between GPU and CPU during processing, which makes the system slow.
