### ISSUE TITLE
[Web] WebGPU supported operator tracking

### ISSUE THREAD

**Issue by fs-eire** [microsoft/onnxruntime#15952]
This issue is for tracking WebGPU operators. It includes the following info:
- a list of supported operators
- a list of WIP operator implementations
- info about problems/correctness/performance specific to a certain oprator.

## Supported operators

https://github.com/microsoft/onnxruntime/blob/main/js/web/docs/webgpu-operators.md

## Currently work in progress operators

ops needed for segment anything:

| OpType | Assigned To | Comments | PR |
|:-----:|:-----:|----|----|
|[ArgMax.float](https://github.com/onnx/onnx/blob/main/docs/Operators.md#ArgMax)|@guschmue|   |  https://github.com/microsoft/onnxruntime/pull/16882 |
|[Cast.bool](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Cast)|@fs-eire|   |   |
|[Equal.float](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Equal)|@fs-eire|   |   |
|[Einsum.float](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Einsum)|@sajandhy|   |   |
|[Gather.float](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Gather)|@dakenf |   |   https://github.com/microsoft/onnxruntime/pull/16855|
|[LayerNormalization.float](https://github.com/onnx/onnx/blob/main/docs/Operators.md#LayerNormalization)|@dakenf|   | https://github.com/microsoft/onnxruntime/pull/16830  |
|[Not.bool](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Not)|@jchen351|   |  https://github.com/microsoft/onnxruntime/pull/16891 |
|[Softmax.float](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Softmax)|@guschmue|   |   https://github.com/microsoft/onnxruntime/pull/16882 |

assuming above ops are implemented, ops missing for segment anything encoder:
(offline script would replace int64 that is not supported in webgpu with int32)

| OpType | Assigned To | Comments | PR |
|:-----:|:-----:|----|----|
|[Concat.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Concat)||   |   |
|[Einsum.float](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Einsum)||   |   |
|[Gather.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Gather)||   |   |
|[Pad.float](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Pad)||   |   |
|[Slice.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Slice)||   |   |
|[Sub.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Sub)||   |   |
|[Transpose.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Transpose)||   |   |

assuming above ops are implemented, ops missing for t5 encoder:
(offline script would replace int64 that is not supported in webgpu with int32)

| OpType | Assigned To | Comments | PR |
|:-----:|:-----:|----|----|
|[Abs.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Abs)||   |   |
|[Add.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Add)||   |   |
|[ConstantOfShape.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#ConstantOfShape)||   |   |
|[Greater.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Greater)||   |   |
|[Less.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Less)||   |   |
|[Log.float](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Log)||   |   |
|[Min.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Min)||   |   |
|[Mul.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Max)||   |   |
|[Range.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Range)||   |   |
|[Reshape.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Reshape)||   |   |
|[Shape.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Shape)||   |   |
|[Sub.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Sub)||   |   |
|[Where.bool](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Where)||   |   |

assuming above ops are implemented, ops missing for t5 decoder:
(offline script would replace int64 that is not supported in webgpu with int32)

| OpType | Assigned To | Comments | PR |
|:-----:|:-----:|----|----|
|[If.bool](https://github.com/onnx/onnx/blob/main/docs/Operators.md#If)||   |   |
|[LessOrEqual.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#LessOrEqual)||   |   |
|[Tile.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Tile)||   |   |

assuming above ops are implemented, ops missing for dolly-v2-3b:
(offline script would replace int64 that is not supported in webgpu with int32, assumes fp32 for now which is not going to work)

| OpType | Assigned To | Comments | PR |
|:-----:|:-----:|----|----|
|[Div.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Div)||   |   |
|[GatherElements.float](https://github.com/onnx/onnx/blob/main/docs/Operators.md#GatherElements)||   |   |
|[Mul.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Mul)||   |   |
|[Neg.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Neg)||   |   |
|[Slice.bool](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Slice)||   |   |
|[Slice.int32](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Slice)||   |   |
|[Tile.float](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Tile)||   |   |
|[Transpose.float](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Transpose)||   |   |

## Operators that need to be optimized

| OpType | Assgined To | Comments |
|:-----:|:-----:|----|
|FusedConv|  @guschmue | need to fuse conv and activation |
|Conv|  TBD  | optimize the 1 time filter transpose at init |
|FusedMatmul|  TBD  |  |
|FusedGemm|  TBD  | |

**Comment by gabrielgrant** [comment]
@guschmue is there a public link we can use to stay appraised of the status of these operations?

**Comment by gabrielgrant** [comment]
This is great news, thanks for the update @fs-eire 

If others are curious about the implementation of these (as I was), they're here: https://github.com/microsoft/onnxruntime/tree/main/js/web/lib/wasm/jsep/webgpu/ops
