### ISSUE TITLE
Official build version 5.0 for Linux does not include cxx_api.h and cxx_inline.h?

### ISSUE THREAD

**Issue by qw2208** [microsoft/onnxruntime#1596]
Official build version 5.0 for Linux does not include cxx_api.h and cxx_inline.h?

**Comment by pranavsharma** [comment]
@qw2208 which official build? Nuget or zip/tarballs? 
@RyanUnderhill I remember this was added. Wasn't it?

**Comment by qw2208** [comment]
[build](https://github.com/microsoft/onnxruntime/releases/download/v0.5.0/onnxruntime-linux-x64-0.5.0.tgz)

**Comment by qw2208** [comment]
It's the zip/tar links.

**Comment by qw2208** [comment]
So did you put it in the official builds or should I wait for the release.
