### ISSUE TITLE
ORT 1.15.0 segfault when inferencing on model loaded on GPU 1

### ISSUE THREAD

**Issue by GuanLuo** [microsoft/onnxruntime#15968]
### Describe the issue

Custom build of ORT 1.15.0 encounter segfault when running a model on GPU 1, whereas the program runs to completion if the model is on GPU 0.

### To reproduce

See attachment for files used in repro steps
1. Build container image with ORT 1.15.0 `docker build  -t ort_cuda11 -f ./Dockerfile.cuda11.ort .`
2. Compile the example `gcc -I /opt/onnxruntime/include/ -std=c++17 ort_example.cc -o ort_c_api -L /opt/onnxruntime/lib/ -lonnxruntime -lstdc++`
3. Run the example with following command to deploy and run model on GPU 1 `LD_LIBRARY_PATH=/opt/onnxruntime/lib:$LD_LIBRARY_PATH ./ort_c_api model.onnx 1`

The model is a string model that convert input strings to number, perform element-wise addition / subtraction, and covert the results back to output strings. `Segmentation fault (core dumped)` will be observed. Whereas if deployed on GPU 0, the program runs to completion.
[ort_gpu1_bug.zip](https://github.com/microsoft/onnxruntime/files/11492303/ort_gpu1_bug.zip)

### Platform

Linux

### OS Version

ubuntu 22.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.15.0

### ONNX Runtime API

C

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.8

**Comment by askhade** [comment]
Looks similar to the one which this PR fixed: https://github.com/microsoft/onnxruntime/pull/15823

@GuanLuo: can you try with the nightly build as the nightly will include this PR.

**Comment by askhade** [comment]
PR#15823 does fix this issue. Closing the issue.

**Comment by pakresi** [comment]
same problem sometimes **onnxruntime** working from GPU i dont know how? sometimes its working on CPU google colab notebook:


Python 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0]
CPU: 2
RAM GB: 12.7
PyTorch version: 2.0.1+cu118
CUDA version: 11.8
cuDNN version: 8700
device: cuda
onnxruntime CPU 1.15.0


how can i force onnxruntime GPU??
