### ISSUE TITLE
Possible memory leak when using CPU execution provider with multiple threads

### ISSUE THREAD

**Issue by icetube23** [microsoft/onnxruntime#15962]
### Describe the issue

I want to run an ONNX model on a CPU only machine using the C++ API. While limited to CPU only, I at least wanted to make use of parallelization/multi threading as well as possible. My code works and also produces the expected results. However, when checking my program with Valgrind, I stumbled across some "possible lost bytes" that seemingly originate from within onnxruntime. I've looked through some other issues related to memory leaks in the C++ API but haven't found anything that solves my issue.

I can not share my original code but I can reproduce the problem using this MWE:
```cpp
// main.cpp
#include <onnxruntime_cxx_api.h>

int main(int argc, char *argv[]) {
    Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "mwe");
    Ort::AllocatorWithDefaultOptions allocator;

    Ort::SessionOptions sessionOptions;

    // no leaks when using only a single thread
    // sessionOptions.SetIntraOpNumThreads(1);
    // sessionOptions.SetInterOpNumThreads(1);

    std::string modelFile = "net.onnx";
    auto session = Ort::Session(env, modelFile.c_str(), sessionOptions);

    const char* inputName = "input";
    const char* outputName = "output";
    std::vector<int64_t> shape = { 1, 3, 16, 16 };
    std::vector<float> input(1 * 3 * 16 * 16);
    auto inputTensor = Ort::Value::CreateTensor<float>(
        allocator.GetInfo(),
        input.data(),
        input.size(),
        shape.data(),
        shape.size()
    );

    auto outputs = session.Run(Ort::RunOptions(), &inputName, &inputTensor, 1, &outputName, 1);
    printf("Success\n");
}
```

The corresponding Valgrind report:

<details>
  <summary>Valgrind report</summary>

```
==7504== Memcheck, a memory error detector
==7504== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==7504== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==7504== Command: ./main
==7504== 
Success
==7504== 
==7504== HEAP SUMMARY:
==7504==     in use at exit: 5,392 bytes in 18 blocks
==7504==   total heap usage: 138,371 allocs, 138,353 frees, 9,133,822 bytes allocated
==7504== 
==7504== 2,400 bytes in 6 blocks are possibly lost in loss record 13 of 13
==7504==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==7504==    by 0x5510424: ??? (in ~/mwe/onnxruntime-linux-x64-1.14.1/lib/libonnxruntime.so.1.14.1)
==7504==    by 0x550EB29: ??? (in ~/mwe/onnxruntime-linux-x64-1.14.1/lib/libonnxruntime.so.1.14.1)
==7504==    by 0x550F112: ??? (in ~/mwe/onnxruntime-linux-x64-1.14.1/lib/libonnxruntime.so.1.14.1)
==7504==    by 0x538979A: ??? (in ~/mwe/onnxruntime-linux-x64-1.14.1/lib/libonnxruntime.so.1.14.1)
==7504==    by 0x538A135: ??? (in ~/mwe/onnxruntime-linux-x64-1.14.1/lib/libonnxruntime.so.1.14.1)
==7504==    by 0x5392B9B: ??? (in ~/mwe/onnxruntime-linux-x64-1.14.1/lib/libonnxruntime.so.1.14.1)
==7504==    by 0x5BF4608: start_thread (pthread_create.c:477)
==7504==    by 0x5B07132: clone (clone.S:95)
==7504== 
==7504== LEAK SUMMARY:
==7504==    definitely lost: 0 bytes in 0 blocks
==7504==    indirectly lost: 0 bytes in 0 blocks
==7504==      possibly lost: 2,400 bytes in 6 blocks
==7504==    still reachable: 2,992 bytes in 12 blocks
==7504==         suppressed: 0 bytes in 0 blocks
==7504== Reachable blocks (those to which a pointer was found) are not shown.
==7504== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==7504== 
==7504== For lists of detected and suppressed errors, rerun with: -s
==7504== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```
</details>

When I manually configure the session options to use only a single thread (see the commented out code in main.cpp), the problem is gone. Combined with the fact that Valgrind points to a function called `start_thread`, I guess this is some kind of multi threading problem (maybe related to this https://github.com/microsoft/onnxruntime/issues/7084?). I also suspect that the number of blocks of the possibly lost bytes seems to correspond (or at least is proportional) to the actual number of threads used during execution. When testing my original code (which used a larger, probably more parallelizable, model) on a machine with 16 threads, the number of blocks was 14 whereas on a different machine with 32 threads there were 30 blocks with possibly lost bytes.

Most-likely, this is plain user error from my side. However, after googling for a while now, I have run out of things to try. So far nothing worked.

Edit: Provided a bit more information about the relation of possibly lost bytes and the number of threads.

### To reproduce

I've bundled my MWE in this [zip folder](https://github.com/microsoft/onnxruntime/files/11486527/mwe.zip) which also includes the model file and a Makefile with the respective commands I used to compile my program and run Valgrind.

My g++ version is 9.4.0 and my Valgrind version is 3.15.0.

### Urgency

I would like to finish this project as soon as possible but don't have a strict dead line.

### Platform

Linux

### OS Version

Ubuntu 20.04.5 LTS

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by satyajandhyala** [comment]
I ran this test and dumped valgrind verbose report.
Please check a very detailed explanation to the exact same problem. It appears that there is no clean way to free this memory created by nsync library.
https://github.com/tensorflow/tensorflow/issues/21582

The memory is allocated here 
==29640== 800 bytes in 2 blocks are possibly lost in loss record 13 of 13
==29640==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==29640==    by 0x5A97417: nsync::nsync_waiter_new_() (common.c:189)
==29640==    by 0x5A94D33: nsync::nsync_cv_wait_with_deadline_generic(nsync::nsync_cv_s_*, void*, void (*)(void*), void (*)(void*), timespec, nsync::nsync_note_s_*) (cv.c:195)
==29640==    by 0x5A95518: nsync::nsync_cv_wait_with_deadline(nsync::nsync_cv_s_*, nsync::nsync_mu_s_*, timespec, nsync::nsync_note_s_*) (cv.c:438)
==29640==    by 0x5A95559: nsync::nsync_cv_wait(nsync::nsync_cv_s_*, nsync::nsync_mu_s_*) (cv.c:450)
==29640==    by 0x586C595: onnxruntime::OrtCondVar::wait(std::unique_lock<onnxruntime::OrtMutex>&) (ort_mutex.cc:39)
==29640==    by 0x585E407: onnxruntime::concurrency::ThreadPoolTempl<onnxruntime::Env>::WorkerData::SetBlocked(std::function<bool ()>, std::function<void ()>) (EigenNonBlockingThreadPool.h:1451)
==29640==    by 0x585CA85: onnxruntime::concurrency::ThreadPoolTempl<onnxruntime::Env>::WorkerLoop(int) (EigenNonBlockingThreadPool.h:1534)
==29640==    by 0x585B5DD: onnxruntime::concurrency::ThreadPoolTempl<onnxruntime::Env>::WorkerLoop(int, Eigen::ThreadPoolInterface*) (EigenNonBlockingThreadPool.h:678)
==29640==    by 0x58671C5: onnxruntime::(anonymous namespace)::PosixThread::ThreadMain(void*) (env.cc:280)
==29640==    by 0x68C4B42: start_thread (pthread_create.c:442)
==29640==    by 0x6955BB3: clone (clone.S:100)

**Comment by satyajandhyala** [comment]
@icetube23 Please check my reply and let me know if you have any questions.

**Comment by icetube23** [comment]
Thanks a lot for your help! This solves all questions I had related to this issue.

I'll quickly summarize what I take away from the link you provided:
- There is no obvious (multi-threading related) user error in the code example I provided
- The possibly lost blocks Valgrind complains about are coming from the nsync library, this memory is not actually leaked but only reused with in nsync in a way that Valgrind does not like (using interior pointers)
