### ISSUE TITLE
I run the onnx model , the program is coredump directly, is there is some flags to open, then I could see more detail

### ISSUE THREAD

**Issue by wawltor** [microsoft/onnxruntime#1597]

**Comment by snnn** [comment]
Please run it with gdb, it will stop at the incorrect instruction.

**Comment by pranavsharma** [comment]
@wawltor do you've any information that'll help us debug? Please follow the issue filing template that shows up when you file a new issue; those are the kinds of details that'll help us help you. Thanks!
