### ISSUE TITLE
[Web] input 'input' is missing in 'feeds'.

### ISSUE THREAD

**Issue by bhomaidan1990** [microsoft/onnxruntime#16002]
### Describe the issue

I can't run my inference session due to the Error: `input 'input' is missing in 'feeds'.`:
```js
const img_arr = new Float32Array(imgData.data); //560 x 560 = 313600
const dims = [1, 1, 560, 560];
const input_tensor = new ort.Tensor("float32", img_arr, dims);

const feeds = { a: input_tensor };
const outputMap = await this.sess.run(feeds);
```

`run inference-session-impl.js:81`

### To reproduce

I have created [this repository](https://github.com/bhomaidan1990/onnx_vue) to reproduce the problem.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14

### Execution Provider

'webgl' (WebGL)

**Comment by fs-eire** [comment]
The error message suggests that one the model's input name is "input", so you need to do this:
```js
// const feeds = { a: input_tensor }; // NO
const feeds = { "input": input_tensor };
```

**Comment by bhomaidan1990** [comment]
Thanks for your kind support.
