### ISSUE TITLE
Bidirectional RNN with initial hidden state does not return the expected results

### ISSUE THREAD

**Issue by neginraoof** [microsoft/onnxruntime#1607]
**Describe the bug**
ORT results for the bidirectional RNN with initial hidden state model does not match pytorch results. Comparing the output tensors, results corresponding to the backwards direction do not match.

**Urgency**
Models using bidirectional RNN with initial hidden state could have an unexpected behavior.

**To Reproduce**
A simple test for RNN model:

```python
def test_rnn():
    input = torch.randn(3, 2, 2, requires_grad=True)
    h0 = torch.randn(2, 3, 2)
    input = (input, h0)
    model = torch.nn.RNN(input_size=2, hidden_size=2, num_layers=1, nonlinearity='relu',
                             bidirectional=True, dropout=0.2, batch_first=True)
    model.eval()
    output = model(*input)
    f = io.BytesIO()
    torch.onnx.export(model, tuple(input), f, verbose=True)
    def to_numpy(tensor):
        if tensor.requires_grad:
            return tensor.detach().cpu().numpy()
        else:
            return tensor.cpu().numpy()

    inputs = list(map(to_numpy, input))
    outputs = list(map(to_numpy, output))
    ort_sess = onnxruntime.InferenceSession(f.getvalue())
    ort_inputs = dict((ort_sess.get_inputs()[i].name, input) for i, input in enumerate(inputs))
    ort_outs = ort_sess.run(None, ort_inputs)

    # compare onnxruntime and PyTorch results
    [np.testing.assert_allclose(out, ort_out, rtol=0.01, atol=0.01) for out, ort_out in zip(outputs, ort_outs)]
```

Assertion fails due to the mismatch in outputs.

**Additional context**
Here is a link to the ONNX model:
https://drive.google.com/drive/folders/1NLjgFFz6An2a_fJy2zwpsj-n9B_RyZvH?usp=sharing

I don't see this issue with LSTM or GRU models. The issue is only for basic RNN, bidirectional, with initial hidden state provided.

I don't see this issue when using a tensor filled with a constant value as initial hidden state:
```python
h0 = torch.ones(2, 3, 2)
```
Looks like this is because a wrong subspan of the initial hidden tensor is used in the backwards direction for the basic RNN model.

**Comment by HectorSVC** [comment]
The RNN node is fallback to CPU since the activations is Relu, Relu which is not supported by cudnn. Actually, all nodes are fallback to CPU for this model.

**Comment by hariharans29** [comment]
@neginraoof - Thanks for the thorough diagnosis of the issue !
