### ISSUE TITLE
90% CPU Usage when running ONNX GPU release

### ISSUE THREAD

**Issue by yijiew** [microsoft/onnxruntime#1608]
**Describe the bug**
The Azure Kinect Body Tracking SDK depends on the latest ONNX runtime GPU version. One of our customers observed that in the latest version, the CPU usage is increased to 90% instead of only 15% in the previous private version. There might be a regression in the latest 0.5.0 release.

**Urgency**
We are going to have another release on early September. We hope to get this issue fixed by then. We don't necessarily need to link to the official release. Any private fix will be good enough. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): Nuget Package
- ONNX Runtime version: 0.5.0
- Python version: None
- Visual Studio version (if applicable): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: CUDA 10.0 / cuDNN 7+
- GPU model and memory: GTX 1070

**To Reproduce**
Describe steps/code to reproduce the behavior:
Private repro project shared through email.

**Comment by duli2012** [comment]
This cpu usage is caused by openmp active wait policy. We have multiple options to address this issue such as change the wait policy to passive or disable openmp in gpu build.
