### ISSUE TITLE
[Training] ImportError: cannot import name 'PropagateCastOpsStrategy' from 'onnxruntime.capi._pybind_state'

### ISSUE THREAD

**Issue by zjc664656505** [microsoft/onnxruntime#16092]
### Describe the issue

I have installed the onnx, onnxruntime, onnxruntime-training, onnxruntime-gpu with pip.
`pip install onnx onnxruntime onnxruntime-gpu onnxruntime-training`

However, when I try to import `onnxblock` from `onnxruntime.training`, I always receive the error message like this `ImportError: cannot import name 'PropagateCastOpsStrategy' from 'onnxruntime.capi._pybind_state' (/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/_pybind_state.py)`

The full error message is shown below:

> ---------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> [<ipython-input-7-d1644a0d42fc>](https://localhost:8080/#) in <cell line: 2>()
>       1 import onnx
> ----> 2 import onnxruntime.training.onnxblock as onnxblock
> 
> [/usr/local/lib/python3.10/dist-packages/onnxruntime/training/__init__.py](https://localhost:8080/#) in <module>
>       4 # --------------------------------------------------------------------------
>       5 # isort: skip_file
> ----> 6 from onnxruntime.capi._pybind_state import PropagateCastOpsStrategy, TrainingParameters  # noqa: F401
>       7 from onnxruntime.capi.training.training_session import TrainingSession  # noqa: F401
>       8 
> 
> ImportError: cannot import name 'PropagateCastOpsStrategy' from 'onnxruntime.capi._pybind_state' (/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/_pybind_state.py)

Currently, I have met this error on both my ubuntu-20.04 PC and my google colab notebook. 

Could anyone help me with solve this issue?

### To reproduce
1.  `pip install onnx onnxruntime onnxruntime-gpu onnxruntime-training`.
2.  `import onnxruntime.training.onnxblock as onnxblock`

### Urgency

This issue is urgent. 

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.0

### PyTorch Version

2.1.0

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.4

**Comment by baijumeswani** [comment]
Could you only try with `onnxruntime-training`. Unfortunately the `onnxruntime-training` and `onnxruntime` python packages cannot be installed at the same time.

Once you install the `onnxruntime-training` python package, you can create the training artifacts using the high level function ```onnxruntime.training.artifacts.generate_artifacts` like this:

```python
from onnxruntime.training import artifacts

artifacts.generate_artifacts(forward_only_onnx_model,
                                           loss=artifacts.LossType.CrossEntropyLoss 
                                           optimizer=artifacts.OptimType.AdamW,
                                           requires_grad=[params, requiring, grad],
                                           frozen_params=[frozen, params])
```

This will generate all the training artifacts in your current working directory.

**Comment by baijumeswani** [comment]
Please refer [this function](https://github.com/microsoft/onnxruntime/blob/76fd9aa745db596d5a1a8053fa76a1f0c92cd1b7/orttraining/orttraining/python/training/artifacts.py#L36) for more details.

**Comment by zjc664656505** [comment]
Thanks for your quick reply!

Currently, I'm trying to reproduce the work shown in [onnxruntime-on-device-training-example](https://github.com/microsoft/onnxruntime-training-examples/blob/master/on_device_training/mobile/android/c-cpp/prepare_for_training.ipynb)

If we should use `artifacts` method to generate the onnx model, then, shouldn't this notebook be updated? since it's creating model using the onnxblock method. 

Also, I have tested this work by removing the `onnxruntime` and `onnxruntime-gpu`, only keeping the `onnxruntime-training` on my local machine. If I stick with how the notebook works, shown below:

```
import onnx
import onnxruntime.training.onnxblock as onnxblock

# Define how the training model should look like.
# In this case, we stack the loss function on top of the original model.
class MobileNetV2BlockWithLoss(onnxblock.TrainingModel):
    def __init__(self):
        super().__init__()
        self.loss = onnxblock.loss.CrossEntropyLoss()

    def build(self, loss_node_input_name):
        return self.loss(loss_node_input_name)

training_block = MobileNetV2BlockWithLoss()

# This task is a transfer learning task. We want to only train the last layer of the model.
# So, we mark parameters associated with other layers as non-trainable.
for name, param in model.named_parameters():
    if not (name == "classifier.1.weight" or name == "classifier.1.bias"):
        training_block.requires_grad(name, False)

# Load the model from the exported inference ONNX file.
onnx_model = onnx.load(f"training_artifacts/{model_name}.onnx")
eval_model = None
optimizer_model = None

inference_model_output_name = "output"
with onnxblock.onnx_model(onnx_model) as model_accessor:
    loss_output_name = training_block(inference_model_output_name)
    eval_model = model_accessor.eval_model

optimizer_block = onnxblock.optim.AdamW()
with onnxblock.onnx_model() as model_accessor:
    optimizer_outputs = optimizer_block(training_block.parameters())
    optimizer_model = model_accessor.model
```

Then, I would get error message like this:

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> Cell In[3], line 2
>       1 import onnx
> ----> 2 import onnxruntime.training.onnxblock as onnxblock
>       4 # Define how the training model should look like.
>       5 # In this case, we stack the loss function on top of the original model.
>       6 class MobileNetV2BlockWithLoss(onnxblock.TrainingModel):
> 
> File ~/miniconda3/envs/onnx/lib/python3.10/site-packages/onnxruntime/training/__init__.py:6
>       1 # -------------------------------------------------------------------------
>       2 # Copyright (c) Microsoft Corporation. All rights reserved.
>       3 # Licensed under the MIT License.
>       4 # --------------------------------------------------------------------------
>       5 # isort: skip_file
> ----> 6 from onnxruntime.capi._pybind_state import PropagateCastOpsStrategy, TrainingParameters  # noqa: F401
>       7 from onnxruntime.capi.training.training_session import TrainingSession  # noqa: F401
>      10 # Options need to be imported before `ORTTrainer`.
> 
> ModuleNotFoundError: No module named 'onnxruntime.capi._pybind_state'

Could you let me know whether I should use the `artifacts` method you provided in the previous answer to generate the model or I should follow what's shown on the official example notebook code?

Thanks a lot!

**Comment by baijumeswani** [comment]
> ModuleNotFoundError: No module named 'onnxruntime.capi._pybind_state'

`onnxruntime-training` and `onnxruntime` python packages cannot be installed together. If they are installed together, it might lead to the package getting corrupted. I would suggest uninstall `onnxruntime-training` and reinstall `onnxruntime-training` package again.

> Could you let me know whether I should use the artifacts method you provided in the previous answer to generate the model or I should follow what's shown on the official example notebook code?

Sorry for the confusion, I will be soon updating the `onnxruntime-training-examples` repo to use `artifacts.generate_artifacts` method.

To generate the mobilenetv2 training artifacts using this high level api, you can run this snippet:

```python

import onnx
from onnxruntime.training import artifacts

import torch
import torchvision

model = torchvision.models.mobilenet_v2(
   weights=torchvision.models.MobileNet_V2_Weights.IMAGENET1K_V2)

# The original model is trained on imagenet which has 1000 classes.
# For our image classification scenario, we need to classify among 4 categories.
# So we need to change the last layer of the model to have 4 outputs.
model.classifier[1] = torch.nn.Linear(1280, 4)

# Export the model to ONNX.
model_name = "mobilenetv2"
torch.onnx.export(model, torch.randn(1, 3, 224, 224),
                  f"training_artifacts/{model_name}.onnx",
                  input_names=["input"], output_names=["output"],
                  dynamic_axes={"input": {0: "batch"}, "output": {0: "batch"}})

# Load the onnx model.
onnx_model = onnx.load(f"training_artifacts/{model_name}.onnx")

requires_grad = ["classifier.1.weight", "classifier.1.bias"]
frozen_params = [
   param.name
   for param in onnx_model.graph.initializer
   if param.name not in requires_grad
]


# Generate the training artifacts.
artifacts.generate_artifacts(
   onnx_model,
   requires_grad=requires_grad,
   frozen_params=frozen_params,
   loss=artifacts.LossType.CrossEntropyLoss,
   optimizer=artifacts.OptimType.AdamW,
   artifact_directory="training_artifacts"
)
```

I will make updates to that example as soon as possible. Thanks for pointing it out.

**Comment by zjc664656505** [comment]
Sorry for sending the inquiry again.

I have tried the code your mentioned:
```

import onnx
from onnxruntime.training import artifacts

import torch
import torchvision

model = torchvision.models.mobilenet_v2(
   weights=torchvision.models.MobileNet_V2_Weights.IMAGENET1K_V2)

# The original model is trained on imagenet which has 1000 classes.
# For our image classification scenario, we need to classify among 4 categories.
# So we need to change the last layer of the model to have 4 outputs.
model.classifier[1] = torch.nn.Linear(1280, 4)

# Export the model to ONNX.
model_name = "mobilenetv2"
torch.onnx.export(model, torch.randn(1, 3, 224, 224),
                  f"training_artifacts/{model_name}.onnx",
                  input_names=["input"], output_names=["output"],
                  dynamic_axes={"input": {0: "batch"}, "output": {0: "batch"}})

# Load the onnx model.
onnx_model = onnx.load(f"training_artifacts/{model_name}.onnx")

requires_grad = ["classifier.1.weight", "classifier.1.bias"]
frozen_params = [
   param.name
   for param in onnx_model.graph.initializer
   if param.name not in requires_grad
]


# Generate the training artifacts.
artifacts.generate_artifacts(
   onnx_model,
   requires_grad=requires_grad,
   frozen_params=frozen_params,
   loss=artifacts.LossType.CrossEntropyLoss,
   optimizer=artifacts.OptimType.AdamW,
   artifact_directory="training_artifacts"
)
```

However, new error shows again like this:

> 
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Cell In[5], line 2
>       1 import onnx
> ----> 2 from onnxruntime.training import artifacts
>       4 import torch
>       5 import torchvision
> 
> File ~/miniconda3/envs/onnx/lib/python3.10/site-packages/onnxruntime/training/__init__.py:11
>       7 from onnxruntime.capi.training.training_session import TrainingSession  # noqa: F401
>      10 # Options need to be imported before `ORTTrainer`.
> ---> 11 from .orttrainer_options import ORTTrainerOptions  # noqa: F401
>      12 from .orttrainer import ORTTrainer, TrainStepInfo  # noqa: F401
>      13 from . import amp, artifacts, checkpoint, model_desc_validation, optim  # noqa: F401
> 
> File ~/miniconda3/envs/onnx/lib/python3.10/site-packages/onnxruntime/training/orttrainer_options.py:516
>     512         for k, v in dict(options).items():
>     513             setattr(self, k, self._wrap(v))
> --> 516 class ORTTrainerOptionsValidator(cerberus.Validator):
>     517     _LR_SCHEDULER = cerberus.TypeDefinition("lr_scheduler", (lr_scheduler._LRScheduler,), ())
>     518     _LOSS_SCALER = cerberus.TypeDefinition("loss_scaler", (loss_scaler.LossScaler,), ())
> 
> File ~/miniconda3/envs/onnx/lib/python3.10/site-packages/onnxruntime/training/orttrainer_options.py:520, in ORTTrainerOptionsValidator()
>     517 _LR_SCHEDULER = cerberus.TypeDefinition("lr_scheduler", (lr_scheduler._LRScheduler,), ())
>     518 _LOSS_SCALER = cerberus.TypeDefinition("loss_scaler", (loss_scaler.LossScaler,), ())
> --> 520 _SESSION_OPTIONS = cerberus.TypeDefinition("session_options", (ort.SessionOptions,), ())
>     522 _PROPAGATE_CAST_OPS_STRATEGY = cerberus.TypeDefinition(
>     523     "propagate_cast_ops_strategy", (PropagateCastOpsStrategy,), ()
>     524 )
>     526 types_mapping = cerberus.Validator.types_mapping.copy()
> 
> AttributeError: module 'onnxruntime' has no attribute 'SessionOptions'

I have uninstall all onnx related packages and only installed `onnx` and `onnxruntime-training`. The version of `onnxruntime-training` I'm using is 1.15.0. 

I'm not sure why this error keeps happening.

**Comment by baijumeswani** [comment]
> AttributeError: module 'onnxruntime' has no attribute 'SessionOptions'

This is the first time I am seeing this error. I tried to replicate your steps locally but could not reproduce your error.

I did:

```bash
pip uninstall onnxruntime-training
pip install onnxruntime-training
```

And execute the above script. For me, it did not show the error you're seeing. The version of `onnxruntime-training` I have is this:

```bash
$ pip list | grep onnxruntime-training
onnxruntime-training          1.15.0
```

I am trying to think of what the reason behind your error is but have nothing so far.

**Comment by zjc664656505** [comment]
Thanks for your quick reply. I. have tested the code on colab, and it works perfectly! I think it might be the issue with my PC. I will double check it tomorrow.

**Comment by Andrewymd** [comment]
> Could you only try with `onnxruntime-training`. Unfortunately the `onnxruntime-training` and `onnxruntime` python packages cannot be installed at the same time. You will need to uninstall `onnxruntime` and `onnxruntime_gpu`.
> 
> Once you install the `onnxruntime-training` python package, you can create the training artifacts using the high level function ```onnxruntime.training.artifacts.generate_artifacts` like this:
> 
> from onnxruntime.training import artifacts
> 
> artifacts.generate_artifacts(forward_only_onnx_model,
>                              loss=artifacts.LossType.CrossEntropyLoss 
>                              optimizer=artifacts.OptimType.AdamW,
>                              requires_grad=[params, requiring, grad],
>                              frozen_params=[frozen, params])
> This will generate all the training artifacts in your current working directory.

Hi @baijumeswani, Does this mean that the current ONNX Runtime Training can only use the CPU for training?
