### ISSUE TITLE
[Build] /usr/bin/ld: cannot find -lonnxruntime when running with rocm build. Also cannot find libonnxruntime.so under build folder.

### ISSUE THREAD

**Issue by Frozenmad** [microsoft/onnxruntime#16099]
### Describe the issue

I cannot successfully run the code below after compiling with rocm support.

```c++

// main.cpp
#include <assert.h>
#include <onnxruntime_cxx_api.h>

#include <iostream>
#include <vector>

void run() {
  Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");
  const auto& api = Ort::GetApi();
  Ort::SessionOptions session_options;
  session_options.SetIntraOpNumThreads(1);
  session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);

  OrtROCMProviderOptions rocm_options;

  Ort::ThrowOnError(api.SessionOptionsAppendExecutionProvider_ROCM(session_options, &rocm_options));
  std::cout << "Running ORT ROCM EP with default provider options" << std::endl;
}

int main(int /*argc*/, char*[]) {
  run();
  return 0;
}
```

with command:
```cmd
g++ main.cpp -I/code/onnxruntime/include/onnxruntime/core/session -lonnxruntime
```

I have searched the issues and some of them told me that I need to have `libonnxruntime.so` in my LD_LIBRARY_PATH. But I cannot find any `libonnxruntime.so` under the `build/Linux/RelWithDebugInfo` folder.

How can I solve the problem?

### Urgency

I cannot run any code using rocm through c++ API. I think it is very urgent for me.

### Target platform

rocm,migraphx

### Build script

I have following the instructions in the dockerfile.rocm.
The build script is:
```cmd
./build.sh --config RelWithDebInfo --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=$(cat ./VERSION_NUMBER) --use_rocm --rocm_home=/opt/rocm
```

Using rocm 5.2.3

### Error / output

/usr/bin/ld: cannot find -lonnxruntime

**Comment by Frozenmad** [comment]
Thanks for answering! I tried again using `--build_shared_lib` and get the following error when compiling:
```log
CMake Error at onnxruntime.cmake:209 (target_link_libraries):
  Target "onnxruntime_providers_rocm" of type MODULE_LIBRARY may not be
  linked into another target.  One may link only to INTERFACE, OBJECT, STATIC
  or SHARED libraries, or to executables with the ENABLE_EXPORTS property
  set.
Call Stack (most recent call first):
  CMakeLists.txt:2107 (include)
```

My build command is:
```
./build.sh --config Release --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=$(cat ./VERSION_NUMBER) --use_rocm --rocm_home=/opt/rocm
```
Seems that rocm ep cannot build shared lib?

**Comment by snnn** [comment]
Which onnxruntime version you were using when building it from source? I checked onnxruntime.cmake line 209 in the latest code, it doesn't seem to match the error message.

**Comment by Frozenmad** [comment]
I am using v1.13.1 branch. Thanks!

**Comment by Frozenmad** [comment]
I also find a pull request trying to solve this issue #11598 . But haven't been merged yet... Are there any hotfix method I can take?

**Comment by snnn** [comment]
Could you try the latest code or the 1.15.0 release? We no longer maintain the 1.13.1 branch, and will not publish any patch release for 1.13.x.
