### ISSUE TITLE
Unknown exception during execution with c++ io buffering example

### ISSUE THREAD

**Issue by kristoftunner** [microsoft/onnxruntime#16093]
### Describe the issue

This is a duplicate issue for this: https://github.com/intel/onnxruntime/issues/299.

While running the io buffering OpenVino example from here: https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/OpenVINO_EP/Windows/squeezenet_classification_io_buffer I got an unknown exception possibly coming from openvino dll, which is caught by the ThrowOnOrtError message with the error_message: Encountered unknown exception in Run()

### To reproduce

Compile the mentioned inference example with v4.3 onnxruntime openvino EP release and run it with an example picture

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

14.1(v4.3 Openvino EP)

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

OpenVINO

### Execution Provider Library Version

2022.3

**Comment by sfatimar** [comment]
We found the bug on C++IO Buffer example and have fixed it on ORT Master branch
