### ISSUE TITLE
[Build] ORT 1.15 is not clear which bits have support for QC QNN EP - QNN execution provider is not supported in this build

### ISSUE THREAD

**Issue by ivberg** [microsoft/onnxruntime#16106]
### Describe the issue

ORT 1.15 claims to have QC QNN EP support - https://github.com/microsoft/onnxruntime/releases/tag/v1.15.0

Release Note Snippet:
Execution Providers
Two new execution providers: JS EP and QNN EP.

However, it doesn't seem to be compiled with this support. Instead, you receive this error at runtime
"QNN execution provider is not supported in this build"

### Repro steps;
Download the drop
https://github.com/microsoft/onnxruntime/releases/download/v1.15.0/onnxruntime-win-arm64-1.15.0.zip

Then per https://onnxruntime.ai/docs/execution-providers/QNN-ExecutionProvider.html
combine binaries with the Qualcomm AI Engine Direct SDK (QNN SDK) from https://qpm.qualcomm.com/main/tools/details/qualcomm_ai_engine_direct

and try out sample https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/QNN_EP/mobilenetv2_classification

You will get the error "QNN execution provider is not supported in this build"

This error does not happen when compiling with QNN support from source per https://onnxruntime.ai/docs/build/eps.html#qnn

### Urgency

Semi-Urgent. QC QNN EP was a large focus of BUILD 2023 and the 1.15 release was supposed to include QNN support. Devs trying out AI scenarios using QNN EP after BUILD will hit multiple roadblocks

### Target platform

windows arm64

### Build script

N/A

### Error / output

N/A

### Visual Studio Version

Visual Studio 2022

**Comment by ivberg** [comment]
FYI @snnn @HectorSVC @jywu-msft @jeffmend

**Comment by jeffmend** [comment]
@ivberg per sample app instrucitons: 
Prerequisites
Windows 11
Visual Studio 2022
**OnnxRuntime ARM Build with QNN support
      Compiled from onnxruntime source - https://onnxruntime.ai/docs/build/eps.html#qnn**

**Comment by HectorSVC** [comment]
We published nuget package for QNN EP:
https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.QNN/#release-body-tab
We will update the release note to make it clear.

**Comment by ivberg** [comment]
Thanks @HectorSVC. The release notes does not mention the NuGet pkg nor does https://onnxruntime.ai/docs/build/eps.html#qnn

Can those both be updated?

**Comment by jywu-msft** [comment]
> We published nuget package for QNN EP: https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.QNN/#release-body-tab
> 
> https://github.com/microsoft/onnxruntime/releases/download/v1.15.0/onnxruntime-win-arm64-1.15.0.zip this one is for Ort CPU EP only.
> 
> We will update the release note to make it clear.

yes, we will clarify.  that's an existing naming convention. we have an arm64 cpu package and x64 cpu package. QNN has its own nuget (since not all arm64 is Qualcomm/QNN enabled)
we will update release note and also the build docs.

**Comment by ivberg** [comment]
Closing. QNN page and release notes have been updated.
