### ISSUE TITLE
releases Assets libs redundancy

### ISSUE THREAD

**Issue by Amousx** [microsoft/onnxruntime#16115]
### Describe the issue

In our business, we try to load the so file of ort on the linux side. 
We downloaded the assets of 1.13.1 in the releases and found that there are two so files, and the binary of the two so is the same. 
In order to reduce storage, we try to delete libonnxruntime.so.1.13.1 and only keep libonnxruntime.so. There is no problem in compiling, but it cannot work in runtime, and libonnxruntime.so.1.13.1 will still be loaded.
![image](https://github.com/microsoft/onnxruntime/assets/13633635/1b852b4e-d6d2-42ea-b3b4-c48f7dc60b54)
releases Assets libs redundancy

### To reproduce

After checking, we found that the SONAME of the two so libraries both point to libonnxruntime.so.1.13.1, 
![image](https://github.com/microsoft/onnxruntime/assets/13633635/b6109ee7-eb51-432b-ae12-080808f7cae1)
![image](https://github.com/microsoft/onnxruntime/assets/13633635/ad65a035-5ce4-4ead-9c05-b1923808fe68)

so we used `patchelf --set-soname libonnxruntime.so libonnxruntime.so ` command to modify the SONAME, everything is ok
![image](https://github.com/microsoft/onnxruntime/assets/13633635/74274a9d-c359-4406-a014-6426102fc847)

### Platform

Linux

### OS Version

fedora 7.2

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CoreML

```[tasklist]
### Tasks
```

**Comment by snnn** [comment]
One of them is a symbolic link.

**Comment by snnn** [comment]
See this: https://www.usenix.org/legacy/publications/library/proceedings/als00/2000papers/papers/full_papers/browndavid/browndavid_html/index.html

In general, on Linux every shared library that is installed to a standard location with a file name ends with ".so" should be a symbolic link.  If libonnxruntime.so is not a symbolic link, it should not be installed to locations like /usr/lib64 or /usr/lib.

**Comment by Amousx** [comment]
Thank you for your reply, I also think that libonnxruntime.so assumes the function of soft link, but it should not have the same size and the same binary content as libonnxruntime.so.1.13.1.

**Comment by snnn** [comment]
Does the latest release, 1.15.0, have the problem?
