### ISSUE TITLE
[Build] ORT with Memory Profiling feature results in broken build

### ISSUE THREAD

**Issue by ivberg** [microsoft/onnxruntime#16124]
### Describe the issue

Dev build with onnxruntime_ENABLE_MEMORY_PROFILE results in broken build

### Urgency

Needed to investigate memory usage of ONNX and models used in AI inferencing

### Target platform

Windows amd64 cpu

### Build script

build.bat --config RelWithDebInfo --build_shared_lib --parallel --cmake_generator "Visual Studio 17 2022" --skip_tests --cmake_extra_defines onnxruntime_ENABLE_MEMORY_PROFILE=ON

### Error / output

E:\src\onnxruntime\onnxruntime\core\framework\execution_frame.cc(423,15): error C2039: 'name': is not a member of 'OrtDevice' [E:\src\onnxruntime\build\Windows\Re
E:\src\onnxruntime\onnxruntime\core\framework\execution_frame.cc(423,15): error C2672: 'std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Ke
E:\src\onnxruntime\onnxruntime\core\framework\execution_frame.cc(431,64): error C2039: 'name': is not a member of 'OrtDevice' [E:\src\onnxruntime\build\Windows\Re
E:\src\onnxruntime\onnxruntime\core\framework\execution_frame.cc(612,55): error C2039: 'name': is not a member of 'OrtDevice' [E:\src\onnxruntime\build\Windows\Re
E:\src\onnxruntime\onnxruntime\core\framework\memory_info.cc(44,13): error C2679: binary '=': no operator found which takes a right-hand operand of type 'const Or
E:\src\onnxruntime\onnxruntime\core\framework\memory_info.cc(58,31): error C2665: 'std::map<OrtMemoryInfo,std::map<onnxruntime::MemoryInfo::MapType,onnxruntime::M

### Visual Studio Version

Visual Studio 2022

**Comment by ivberg** [comment]
FYI @wezuo

**Comment by ivberg** [comment]
Closing. Memory Profiling now works again with the fix. We tested on GPU since that is what is there by default, but in code it can be changed to CPU and that works as well.

**Comment by snnn** [comment]
Fixed in ONNX Runtime 1.15.1 release.
