### ISSUE TITLE
onnruntime_gpu python lib need libcudart.so.10.1

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#1612]
Most of dl lib such as master pytorch and tensorflow, it supports CUDA10.0.

while install onnxruntime it says:

```
  import onnxruntime as rt
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/__init__.py", line 20, in <module>
    from onnxruntime.capi.session import InferenceSession
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/capi/session.py", line 9, in <module>
    from onnxruntime.capi import _pybind_state as C
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/capi/_pybind_state.py", line 8, in <module>
    import onnxruntime.capi._ld_preload
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/capi/_ld_preload.py", line 14, in <module>
    _libcudart = CDLL("libcudart.so.10.1", mode=RTLD_GLOBAL)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.1: cannot open shared object file: No such file or directory

```

Howver, I have only CUDA10 installed, not CUDA10.1. how to solve this problem?

If I reinstall CUDA10.1, my other deep learning lib will broken, and also my tensorrt will broken.....

**Comment by jinfagang** [comment]
Totally missed in the usage of GPU version onnxruntime python lib:


```
/usr/local/lib/python3.5/dist-packages/onnxruntime/capi/_pybind_state.py:13: UserWarning: Cannot load onnxruntime.capi. Error: '/usr/local/cuda/lib64/libcublas.so.10: version `libcublas.so.10' not found (required by /usr/local/lib/python3.5/dist-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-35m-x86_64-linux-gnu.so)'
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'".format(str(e)))
Traceback (most recent call last):
  File "demo_tinyyolo.py", line 2, in <module>
    import onnxruntime as rt
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/__init__.py", line 21, in <module>
    from onnxruntime.capi._pybind_state import RunOptions, SessionOptions, set_default_logger_severity, get_device, NodeArg, ModelMetadata
ImportError: cannot import name 'RunOptions'

```

**Comment by jinfagang** [comment]
Don't know it needs cuda10 or cuda10.1.........

**Comment by snnn** [comment]
> If I reinstall CUDA10.1, my other deep learning lib will broken, and also my tensorrt will broken.....
It shouldn't happen. 

First, you could install multiple CUDA versions on the same computer, but in different directories.
Second,  Linux search shared lib by using major+minor versions. So, the executable program should depends on libcudart.so.10.1 or libcudart.so.10.0, not libcudart.so.10. If that, libcudart.so.10.1 and libcudart.so.10.0 could co-coexist on your machine, in the same dir, without introducing any extra problem.

**Comment by jinfagang** [comment]
@snnn I believe most users environment are CUDA10.0 not CUDA10.1. Back to the question, what exactly need to run onnxruntime python?

Besides, I don't think `libculas.so.10.0` and `libculas.so.10.1` can co-exist in a same folder. They all will link to `libculas.so.10` and `libculas.so` which conflicts.

**Comment by snnn** [comment]
1. It need Cuda 10.1 on Linux 
2. They can coexist.  libculas.so can point to any of them.

**Comment by jinfagang** [comment]
Theorically, it is.  But, it's not possible to manually all cuda lib switch between 10.0 and 10.1. I think I have to switch them in case pytorch and tensorflow needs cuda10.0, and everytime I need onnxruntime I should switch it to cuda10.1, why not just keep same with most DL libs?

**Comment by snnn** [comment]
There are two separated things: building and running.
For building these software, the problem can be solved by docker, or chroot. AFAIK, Every big company is using such things for manage their dev and build env. Google rely on bazel, it's similar. If you don't use docker, Cuda is just one of the problems you may meet. Later on you may found protobuf's version is also different. Then maybe mkldnn/mkl/ngraph/...

For deloying and running the software, as I pointed, it's not a problem.

**Comment by faxu** [comment]
Thanks for your feedback. We're looking into updating the CUDA versions for consistency. For now, can you build ONNX Runtime with 10.0?

**Comment by jinfagang** [comment]
@faxu I'll try this solution.
