### ISSUE TITLE
[Web] Cannot instantiate Ort::Session using Emscripten.

### ISSUE THREAD

**Issue by GLivshits** [microsoft/onnxruntime#16132]
### Describe the issue

Hi. I am trying to port a neural network to web browser for first time. For this purpose, I've chosen WASM and Emscripten.
I have the following C++ code:

```
#include <onnxruntime_cxx_api.h>
#include <utility>
#include <iterator>
#include <iostream>
#include <emscripten/emscripten.h>
#include <emscripten/bind.h>
int main(){
    std::cout << Flag 1" << std::endl;
    Ort::Env env = Ort::Env(OrtLoggingLevel::ORT_LOGGING_LEVEL_ERROR, "detection");
    std::cout << "Flag 2" << std::endl;
    Ort::SessionOptions sessionOptions = Ort::SessionOptions();
    std::cout << "Flag 3" << std::endl;
    const std::string modelpath = "model.onnx";
    Ort:: Session session = Ort::Session(env, modelpath.c_str(), sessionOptions);
    std::cout << "Flag 4" << std::endl;
    return 0;
}
```

However, when I compile it using emcmake, running "node main.js" does fails with the following error (and corresponding "Flag" logs):

> Flag 1
> Flag 2
> Flag 3
> {PROJECT_DIR}/build/main.js:148
>       throw ex;
>       ^
> 8659104
> (Use `node --trace-uncaught ...` to show where the exception was thrown)

I cloned ONNXRuntime repository and have built it for web with the following command: "./build.sh --config Release --build_wasm_static_lib --skip_tests --disable_wasm_exception_catching --disable_rtti".

### To reproduce

1) Copy-paste aforementioned code (call file main.cpp).
2) Compile ONNXRuntime.
3) Enable Emscripten: cd {ONNXRuntime_DIR}/cmake/external/emsdk && source emsdk_env.sh
4) Create CMakeLists.txt:
cmake_minimum_required(VERSION 3.25.0)
project(main)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
option(ONNXRuntime_DIR "Path to built ONNX Runtime directory." STRING)
add_executable(main
                           main.cpp)
target_include_directories(main PRIVATE "${ONNXRuntime_DIR}/include/onnxruntime/core/session")
target_include_directories(main PUBLIC ${CMAKE_CURRENT_BINARY_DIR}/include)
target_link_libraries(main "${ONNXRuntime_DIR}/build/Linux/Debug/libonnxruntime_webassembly.a")
set_target_properties(main PROPERTIES COMPILE_FLAGS "-sNO_DISABLE_EXCEPTION_CATCHING")
set_target_properties(main PROPERTIES LINK_FLAGS "-sNO_DISABLE_EXCEPTION_CATCHING --bind")
5) Run the following inside folder with code and CMakeLists:
mkdir build && cd build && emcmake cmake ../ -DONNXRuntime_DIR={ONNXRuntime_DIR} && emmake make
6) Put any onnx model inside build directory. It should be named "model.onnx"
7) Run node main.js

Node version: 20.2.0
gcc version: 1.13.0
cmake version: 3.26.3
emcc version: 3.1.19

### Urgency

It is not extremely urgent, but I've spent about a week debugging it (this is example code, actual project does not work, too)

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.14.1

### Execution Provider

'wasm'/'cpu' (WebAssembly CPU), Other / Unknown

**Comment by fs-eire** [comment]
The information is not efficient to figure out where the problem is. could you try build onnxruntime for web assembly static lib in debug:
```
./build.sh --config Debug --build_wasm_static_lib --skip_tests
```

**Comment by GLivshits** [comment]
I have already tried Debug build. It throws the same error without explanation (but the number is different). As I understand, a pointer is throwed as error.

**Comment by fs-eire** [comment]
if you don't build with flag `--disable_wasm_exception_catching --disable_rtti`, you should be able to see what is the exception instead of just a number

**Comment by GLivshits** [comment]
I just have compiled it with your command, it throws the same error (as I said before)

**Comment by GLivshits** [comment]
I've cloned latest version of ONNXRuntime (1.16.0) and built again. Now it works and shows errors.

**Comment by TongMeng-AI** [comment]
Hello, I encountered a similar issue as yours. When I use session.run(), an "Uncaught (in promise) 50741520" error occurs. However, everything runs fine when I comment out this function. I can successfully output information about the model. Do you have any suggestions?

**Comment by fs-eire** [comment]
@TongMeng-AI I need more info to understand the problem. Could you create a new issue and share more details so that I can take a look? A full reproduce step is great.
