### ISSUE TITLE
[Performance] Inference speed drops when I introduce delays between run calls.

### ISSUE THREAD

**Issue by juliandewit** [microsoft/onnxruntime#16135]
### Describe the issue

Inference speed drops when I introduce delays between run calls. 4ms -> avg 60ms.
Nothing changes.. Only I call onnx less times.. It seems like the GPU flushes a cache when it gets the time.
Note I constructed this example from a very complex project but this is the essense. I cannot explain it. I hope you guys and girls can.. 
This model is an example. It also happens to completely different models.

// This loop, runtensor is 4 ms per call
for (var i = 0; i < 100; i++)
{
    runner.RunTensor(tensor);
}

// Same loop only 200ms delay after runtensor,  will slowly go up to 20-100 ms per call
for (var i = 0; i < 100; i++)
{
    runner.RunTensor(tensor);
    Thread.Sleep(200);
}

// Back to normal loop, runtensor is 4 ms per call
for (var i = 0; i < 100; i++)
{
    runner.RunTensor(tensor);
}

First loop ca. 4ms per RunTensor..

Run: 4ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 4ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, 
Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, 
Run: 3ms, Run: 3ms, Run: 4ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 4ms, 
Run: 3ms, Run: 3ms, Run: 4ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 4ms, Run: 3ms, Run: 3ms, 
Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 4ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, 
Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms,
Run: 3ms, Run: 4ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, 
Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 4ms, Run: 3ms, Run: 3ms, 
Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 4ms, Run: 4ms, Run: 3ms, Run: 3ms, Run: 3ms, 

Introduce a Thread sleep between RunTensor calls, after while ca. 15ms - 100ms per RunTensor.. WHYYYY ??

Run: 3ms, Run: 3ms, Run: 3ms, Run: 4ms, Run: 4ms, Run: 3ms, Run: 3ms, Run: 4ms, Run: 3ms, Run: 4ms, Run: 4ms, 
Run: 4ms, Run: 4ms, Run: 4ms, Run: 4ms, Run: 4ms, Run: 4ms, Run: 4ms, Run: 4ms, Run: 4ms, Run: 10ms, Run: 11ms, 
Run: 16ms, Run: 17ms, Run: 18ms, Run: 18ms, Run: 25ms, Run: 20ms, Run: 24ms, Run: 24ms, Run: 36ms, Run: 31ms, 
Run: 32ms, Run: 31ms, Run: 36ms, Run: 45ms, Run: 36ms, Run: 31ms, Run: 32ms, Run: 32ms, Run: 31ms, Run: 80ms, 
Run: 41ms, Run: 32ms, Run: 31ms, Run: 39ms, Run: 37ms, Run: 59ms, Run: 37ms, Run: 32ms, Run: 40ms, Run: 54ms, 
Run: 33ms, Run: 32ms, Run: 32ms, Run: 32ms, Run: 39ms, Run: 54ms, Run: 32ms, Run: 32ms, Run: 32ms, Run: 32ms, 
Run: 36ms, Run: 46ms, Run: 36ms, Run: 32ms, Run: 35ms, Run: 31ms, Run: 37ms, Run: 83ms, Run: 34ms, Run: 33ms, 
Run: 31ms, Run: 33ms, Run: 50ms, Run: 41ms, Run: 31ms, Run: 36ms, Run: 32ms, Run: 31ms, Run: 66ms, Run: 31ms, 
Run: 31ms, Run: 31ms, Run: 32ms, Run: 37ms, Run: 35ms, Run: 35ms, Run: 34ms, Run: 31ms, Run: 31ms, Run: 37ms, 
Run: 41ms, Run: 35ms, Run: 34ms, Run: 32ms, Run: 37ms, Run: 43ms, Run: 35ms, Run: 35ms,

Reomve thread sleep between RunTensor calls, after while ca. 4ms per RunTensor.. WHYYYY ??

Run: 32ms, Run: 36ms, Run: 37ms, Run: 66ms, Run: 85ms, Run: 30ms, Run: 23ms, Run: 4ms, Run: 3ms, Run: 3ms, 
Run: 3ms, Run: 3ms, Run: 4ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, 
Run: 4ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 4ms, Run: 3ms, Run: 3ms, 
Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 4ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, 
Run: 3ms, Run: 3ms, Run: 3ms, Run: 4ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, 
Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 4ms, Run: 4ms, Run: 3ms, 
Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 4ms, Run: 3ms, Run: 3ms, Run: 3ms, 
Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 4ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, 
Run: 3ms, Run: 3ms, Run: 4ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, Run: 3ms, 

### To reproduce

Run the attached console application + model.
[OnnxRiddle.zip](https://github.com/microsoft/onnxruntime/files/11584689/OnnxRiddle.zip)

### Urgency

This seems like a big problem.

### Platform

Windows

### OS Version

Windows 10.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.11.0 - 1.15.0

### ONNX Runtime API

C#, Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

Cuda 11.4 

### Is this a quantized model?

No

**Comment by juliandewit** [comment]
The problem also manifests itself when using the pyton runtime.

import numpy
import onnxruntime as ort
import datetime
import time

ort_sess = ort.InferenceSession('testnet.onnx', providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
print("Device: ", ort.get_device())
x = numpy.zeros((2, 3, 384, 512), dtype=numpy.float32)

print("Warmup")
ms_list = []
for i in range(5):
    start_time = datetime.datetime.now()
    outputs = ort_sess.run(None, {'images': x})
    ms_list.append(int(round((datetime.datetime.now() - start_time).total_seconds() * 1000, 2)))
print("Ms per run: ", ms_list)

print("Fast 4 ms per run")
ms_list = []
for i in range(100):
    start_time = datetime.datetime.now()
    outputs = ort_sess.run(None, {'images': x})
    end_time = datetime.datetime.now()
    ms_list.append(int(round((datetime.datetime.now() - start_time).total_seconds() * 1000, 2)))
print("Ms per run: ", ms_list)


print("Delay between runs,  20-100 ms per run")
ms_list = []
for i in range(100):
    start_time = datetime.datetime.now()
    outputs = ort_sess.run(None, {'images': x})
    end_time = datetime.datetime.now()
    ms_list.append(int(round((datetime.datetime.now() - start_time).total_seconds() * 1000, 2)))
    time.sleep(0.2)
print("ms per run: ", ms_list)

print("No delay anymore fast again")
ms_list = []
for i in range(100):
    start_time = datetime.datetime.now()
    outputs = ort_sess.run(None, {'images': x})
    end_time = datetime.datetime.now()
    ms_list.append(int(round((datetime.datetime.now() - start_time).total_seconds() * 1000, 2)))

print("ms per run: ", ms_list)

**Comment by simonjub** [comment]
I've seen similar behavior and I believe it is the GPU entering a lower power state (and lower clock speed) when it is seeing lower usage.

**Comment by juliandewit** [comment]
Yes that was it.. In the GPU config settings we could turn it off and the test worked fine.
