### ISSUE TITLE
Ort::GetApi(...) returned nullptr

### ISSUE THREAD

**Issue by EXQ364** [microsoft/onnxruntime#16133]
### Describe the issue

Hi. I trying create After Effects plugin using SDK. When i trying create `Ort::Env ` i receive exception:

![image](https://github.com/microsoft/onnxruntime/assets/99953893/9b55b5a8-30c7-4315-ad8c-a16ef241581d)

I tried place Ort:Env in global scope, in main function, but it not worked for me. 
In few issues i found that `onnxruntime ` should place in build directory, that not my situation, because `onnxruntime.dll ` already in directory and have right version of build.
![image](https://github.com/microsoft/onnxruntime/assets/99953893/3ff05759-a049-4964-8940-f6cf6b419c44)

`OrtGetApiBase()` worked and return dll, but method `GetApi(ORT_API_VERSION);` returned null.
![image](https://github.com/microsoft/onnxruntime/assets/99953893/8de2f220-421b-4071-b5f7-3714fa14c163)

What i need to do?

### To reproduce

I used vcpkg for download onnxruntime, then just replace .lib, .dll, .pdb files in **vcpkg\installed\x64-windows** by artefacts on github onnxruntime 15 version. 

- Install Adobe After Effects SDK from https://developer.adobe.com/console/servicesandapis
- Build Skeleton template from path **AfterEffectsSDK\Examples\Template\Skeleton\Win\**
- Use debug version and change **project settings > vcpkg > vcpkg configuration: debug**. Then
- Just can't use Ort::Env env;
- Build plug-in and apply this to some layer. 
- Plugin throw exception

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.23.523

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by EXQ364** [comment]
I found that After Effects use own onnxruntime then load.
`'AfterFX.exe' (Win32): Loaded 'T:\Programs\Adobe\Adobe After Effects 2023\Support Files\onnxruntime.dll'. `
and
`'AfterFX.exe' (Win32): Loaded 'C:\Program Files\Common Files\Adobe\Plug-Ins\CC\File Formats\onnxruntime.dll'. `

This onnxruntime.dll is version 13. How can i use onnxruntime version 15 for my own pluging?

**Comment by snnn** [comment]
Put the dll to the same dir where the *.exe file of the process lives.

**Comment by EXQ364** [comment]
> Put the dll to the same dir where the *.exe file of the process lives.

But After Effects use own version of OnnxRuntime - 13. I can't just remove this. However, I solved the problem with LoadLibrary function.

**Comment by snnn** [comment]
Thank you!

**Comment by EXQ364** [comment]
**Update:** 
This problem easy solve by defining `#define ORT_MANUAL_INIT`, use LoadLibrary for s`earching onnxruntime.dll`, then get adress of func `GetApi()` and push this to `Ort::InitApi()` function

**Comment by sinall** [comment]
> LoadLibrary

How did you do that? Could you please share the piece of code?

**Comment by EXQ364** [comment]
> > LoadLibrary
> 
> How did you do that? Could you please share the piece of code?

Hi. Before all i'm paste this define at start of code 
![image](https://github.com/microsoft/onnxruntime/assets/99953893/16487eb3-f1d8-469d-97e2-698a0f75f19d)

Then i use [dll Load library](https://github.com/Xoronic/dll_loader) for easy loading dll. 
![image](https://github.com/microsoft/onnxruntime/assets/99953893/fbb23b90-b903-446c-862f-96777ea9a3e9)

And inside main function i use this code
![image](https://github.com/microsoft/onnxruntime/assets/99953893/99333976-32d8-4a41-8e75-d5ea8379cf7b)

`SetDllDirectoryA(GetPluginFolder());` is Windows system function for searching paths, i use this for correct loading Cuda libraries, because i copy all needed cuda libs inside project folder
![image](https://github.com/microsoft/onnxruntime/assets/99953893/12917210-3208-4a29-ac93-4a0af8a8d78b)
