### ISSUE TITLE
How can I get all gpus I can choose with onnxruntme-directml

### ISSUE THREAD

**Issue by qyw233** [microsoft/onnxruntime#16149]
### Describe the issue

I have code with onnxruntme-directml：
options = onnxruntime.SessionOptions()
        options.enable_mem_pattern = False
        options.execution_mode = onnxruntime.ExecutionMode.ORT_SEQUENTIAL
        providers = [
            ('DmlExecutionProvider', {
                'device_id': 1,
            }),
            'CPUExecutionProvider',
        ]
        session = onnxruntime.InferenceSession(
            model_path, options, providers=providers)
How can I get the device_id of all GPUs, and which device_id can I choose?

### To reproduce

options = onnxruntime.SessionOptions()
        options.enable_mem_pattern = False
        options.execution_mode = onnxruntime.ExecutionMode.ORT_SEQUENTIAL
        providers = [
            ('DmlExecutionProvider', {
                'device_id': 1,
            }),
            'CPUExecutionProvider',
        ]
        session = onnxruntime.InferenceSession(
            model_path, options, providers=providers)

### Platform

Windows

### OS Version

windows 11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.13.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

DirectML

**Comment by nums11** [comment]
Thanks for posting. There is currently no way to get a list of all gpus that can be chosen. You can either

1. Enumerate your devices via DXGI and pass a device id to [this API](https://github.com/microsoft/onnxruntime/blob/a3a12372705c585240313d65916ab4a128caa4e3/include/onnxruntime/core/providers/dml/dml_provider_factory.h#L71).

2. Create a DML device and command queue and pass those into [this API](https://github.com/microsoft/onnxruntime/blob/a3a12372705c585240313d65916ab4a128caa4e3/include/onnxruntime/core/providers/dml/dml_provider_factory.h#L82).
