### ISSUE TITLE
load onnx model error

### ISSUE THREAD

**Issue by feng-1985** [microsoft/onnxruntime#16153]
### Describe the issue

the tensorflow model (tensorflow-gpu 1.12) work well in cuda 9.0, and use tf2onnx.convert to onnx, then use the onnx model in cuda 10.2 with onnxruntime-gpu 1.6, but failed loading, raise the error: onnxruntime.capi.onnxruntime_pybind11_state.Fail -- Unknown model file format version.

### To reproduce

no

### Platform

Linux

### OS Version

ubuntu 18

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.6

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by tianleiwu** [comment]
see https://onnxruntime.ai/docs/reference/compatibility.html#onnx-opset-support for compatible ONNX version.
ONNX Runtime 1.6 supports ONNX opset version 13 or older.

**Comment by feng-1985** [comment]
so I should convert the tf model use the opset 13, then load runtime 1.6. 
I will try it.

**Comment by feng-1985** [comment]
Thanks, it solved my problem.
