### ISSUE TITLE
[Mobile] Difference in Inference time in Android+ARM platform

### ISSUE THREAD

**Issue by ashissamal** [microsoft/onnxruntime#16159]
### Describe the issue

The inference time on the ONNX created server (x86_64, 16 core, 2.40GHz, Linux) is <60ms and the target inference platform(Android + ARM 64 v8, 4 core, 1.6GHz) is 10sec, hugely different. Is there anything to be done differently to improve the latency in the target platform.

P.S. Both servers are running the inference in CPU.

### To reproduce

Step -1: Created ONNX from Pytorch model with static input dimension in a platform (x86_64, 16 core, 2.40GHz, Linux)
Step -2:  Took inference time on the ONNX created server (x86_64, 16 core, 2.40GHz, Linux), which is < 60ms
 Step -3: Ported the model to an Android based application with ARM 64 v8, 4 core, 1.6GHz) platform, where inference time is > 10sec

### Urgency

Yes, this is urgent since we have an important use case development in a critical phase.

### Platform

Android

### OS Version

11

### ONNX Runtime Installation

Built from Source

### Compiler Version (if 'Built from Source')

1.15.0

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

NA

### ONNX Runtime API

Java/Kotlin

### Architecture

X64

### Execution Provider

Default CPU

**Comment by Craigacp** [comment]
Are you running approximately the same code on both the server and the Android device? Are they both using the Java API, or is the server using another language interface?

**Comment by ashissamal** [comment]
Server code runs on python and Android device code runs on Java interfaces. However both of them loads the same ONNX model.

**Comment by Craigacp** [comment]
How are you feeding inputs into the Android code? Multidimensional arrays in Java are very slow and you should use a byte buffer to create the inputs and access the outputs.

**Comment by Craigacp** [comment]
The buffer should be created like this - https://github.com/microsoft/onnxruntime/blob/main/java/src/test/java/ai/onnxruntime/InferenceTest.java#L888. I'm working on a better example which does everything the right way but it's not public yet.

Additionally the scale of the slowdown suggests that you're not using NNAPI or that the model isn't appropriate for running on that chip. The server likely has wide SIMD registers and the ARM chip likely does not, so the amount of floating point computation it can do is probably substantially less.

**Comment by ashissamal** [comment]
Thanks for the response. I have changed the ONNX runtime by updating to below dependency.
**`implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.15.0'`** . This has given us good improvement in latency in simulator. However, when we use the same onnx dependency in the target device(shared earlier), it get stuck and gives below error while creating the environment(`OrtEnvironment.getEnvironment()`)

`No implementation found for long ai.onnxruntime.OnnxRuntime.initialiseTrainingAPIBase(long, int) (tried Java_ai_onnxruntime_OnnxRuntime_initialiseTrainingAPIBase and Java_ai_onnxruntime_OnnxRuntime_initialiseTrainingAPIBase__JI)`

**Comment by Craigacp** [comment]
@baijumeswani how is the Android build packaged? That entry point (https://github.com/microsoft/onnxruntime/blob/main/java/src/main/native/ai_onnxruntime_OnnxRuntime.c#L27) isn't conditionally hidden in the source so it should be present in all forms of the compiled library.

**Comment by baijumeswani** [comment]
I just downloaded the [onnxruntime-android-1.15.0.aar](https://repo1.maven.org/maven2/com/microsoft/onnxruntime/onnxruntime-android/1.15.0/onnxruntime-android-1.15.0.aar) package from [Maven Central](https://central.sonatype.com/artifact/com.microsoft.onnxruntime/onnxruntime-android/1.15.0/overview) and tried to query the `libonnxruntime4j_jni.so` library there and was able to find the symbol definition there:

```bash
$ nm -D libonnxruntime4j_jni.so  | grep "Java_ai_onnxruntime_OnnxRuntime_initialiseTrainingAPIBase"
000000000000a5ec T Java_ai_onnxruntime_OnnxRuntime_initialiseTrainingAPIBase
```

Seems like the package does indeed contain the symbol definition. Not sure what would cause this error.

@edgchen1 do you know what might be causing the error the [ashissamal](https://github.com/ashissamal) is seeing?

**Comment by edgchen1** [comment]
hm, I'm not sure. I just verified that this [example](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/image_classification/android) builds and runs with onnxruntime-android:1.15.0 on an Android arm64 device.

would it be possible to provide a reproducible example that shows this error?

**Comment by ashissamal** [comment]
Thanks for the response. We have tried the below .
### **Not Working Configuration**
defaultConfig {
        applicationId "com.example.onnxsampleapp"
        minSdk 27
        targetSdk 32
        versionCode 1
        versionName "1.0"
    }

### **Working Configuration**
defaultConfig {
        applicationId "com.example.onnxsampleapp"
        minSdk 27
        targetSdk 32
        versionCode 1
        versionName "1.0"
        ndk {
            _abiFilters 'armeabi-v7a'_
        }
    }

**Note:**
Only change is  _abiFilters 'armeabi-v7a'_, which works. 
**abiFilters 'armeabi-v8a'** does not work.

**Comment by ashissamal** [comment]
Thank for the support. 
By updating the compileSdk & targetSdk to 33 and gradle JDK version to 11, issue was resolved.
