### ISSUE TITLE
[Build] different outputs when using Concat op with different inputs sequence.

### ISSUE THREAD

**Issue by Eddie-Wang1120** [microsoft/onnxruntime#16160]
### Describe the issue

I write two tesor_value_info A/B, with shape [8, 16, 1, 64] and [8, 16, 45, 64], and use them for the inputs of a Concat op. However, the result is not same. When Concat op's inputs is [B.name, A.name], the output is right, but when inputs is [A.name, B.name], the output is slightly different with the other sequence, and is wrong.

### Target platform

liunx ubuntu18.04 onnxruntime-gpu==1.12.0 onnx==1.10.0

### Build script

import onnx
from onnx import TensorProto, helper

def generate_encoder_model():
    weight_list = []
    operation_list = []
    output_list = []
    
    cat1 = helper.make_tensor_value_info(
        'cat1',
        TensorProto.FLOAT,
        [8, 16, 1, 64]
    )
    
    cat2 = helper.make_tensor_value_info(
        'cat2',
        TensorProto.FLOAT,
        [8, 16, 45, 64]
    )
    
    cat_out = helper.make_tensor_value_info(
        'cat2_out',
        TensorProto.FLOAT,
        [8, 16, 46, 64]
    )
    
    output_list += [cat_out]
    
    operation_list.append(
        helper.make_node(
            "Concat",
            inputs = [cat1.name, cat2.name],
            outputs = [cat_out.name],
            axis=2
        )
    )

    encoder_layers_graph = helper.make_graph(
        operation_list,
        'unimo_encoder_layers',
        [cat1, cat2],
        output_list,
        initializer=weight_list
    )
    
    encoder_layers_model = onnx.shape_inference.infer_shapes(
        helper.make_model(
            encoder_layers_graph,
            opset_imports = [ onnx.helper.make_opsetid("", 12) ]
        )
    )
    onnx.checker.check_model(encoder_layers_model)
    return encoder_layers_model

if __name__ == "__main__":
    encoder_model = generate_encoder_model()
    onnx.save(encoder_model, 'concat_cache.onnx')

### Error / output

import numpy as np

np_k = np.load("modi_k.npy")
np_cache = np.load("cache.npy")
import onnxruntime as ort

providers = [("CUDAExecutionProvider")]
ort_sess = ort.InferenceSession('concat_cache.onnx', providers=providers)

outputs = ort_sess.run(None, {
            'cat1': np_k.astype(np.float32), 
            'cat2': np_cache.astype(np.float32)
            })
print(outputs[0][0][0][0][1])

Concat inputs -> [8, 16, 1, 64] , [8, 16, 45, 64]
terminal output -> -1.572966 (wrong)

Concat inputs -> [8, 16, 45, 64] , [8, 16, 1, 64]
terminal output -> -1.5729795 (right)

**Comment by tianleiwu** [comment]
Concat A + B is expected to be different from B + A. For example, that we concatenate single element tensor [1] and [2], the result [1, 2] and [2, 1] is different.

**Comment by Eddie-Wang1120** [comment]
sry, i made a msitake.
