### ISSUE TITLE
Segfaults when loading model with local functions, works fine if model is inlined by ONNX

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnxruntime#16170]
### Describe the issue

As title, here is the [example model](https://microsoft-my.sharepoint.com/:u:/p/bowbao/ERhg5Of2NedOnQx8YRH8AhMBq4FbtKlK-YSWWYkWy7d0mQ?e=Kp3vQm).

### To reproduce

Download model from link above. Install onnx from source (for inliner, this step is not necessary to repro the segfault), onnxruntime from nightly. 

`pip install --index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/ ort-nightly==1.16.0.dev20230528001`

```python
import onnxruntime

# Segfaults
sess = onnxruntime.InferenceSession("segfault.onnx", providers=["CPUExecutionProvider"])

# Works if model is inlined first.
# Needs onnx main branch for inliner.
import onnx
import onnx.inliner
model_proto = onnx.load("segfault.onnx")
inlined_model_proto = onnx.inliner.inline_local_functions(model_proto)
sess = onnxruntime.InferenceSession(inlined_model_proto.SerializeToString(), providers=["CPUExecutionProvider"])
```

### Platform

Linux

### OS Version

20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.16.0.dev20230528001

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by BowenBao** [comment]
gdb shows this is likely the same issue as https://github.com/onnx/onnx/issues/5212, so should be resolvable by bumping onnx submodule commit to https://github.com/onnx/onnx/commit/213b525a51ead28961d9b4f2764b08c7e336bf2c

```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
onnx::shape_inference::ShapeInferenceImplBase::process (this=this@entry=0x7fffffff9e50, func_proto=..., ctx=...)
    at /home/bowbao/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-src/onnx/shape_inference/implementation.cc:591
591           if (type->value_case() == TypeProto::kTensorType && ctx.getInputData(i) != nullptr) {
```

**Comment by snnn** [comment]
@pranavsharma , how should we proceed? 
@liqunfu , will ONNX have a patch release for this bug? Or will they cherry-pick the fix to a release branch?

**Comment by pranavsharma** [comment]
As discussed we've an [internal work item](https://aiinfra.visualstudio.com/ONNX%20Runtime/_workitems/edit/18084) to add a cmake option to allow build ORT with a different ONNX Commit.

**Comment by BowenBao** [comment]
@pranavsharma thanks for info, is there an eta for this item?

**Comment by thiagocrepaldi** [comment]
FYI Onnx 1.14.1 is coming by the end of August (https://github.com/onnx/onnx/issues/5468)

**Comment by pranavsharma** [comment]
> @pranavsharma thanks for info, is there an eta for this item?

Check with @snnn
