### ISSUE TITLE
Use the op ReduceMax error

### ISSUE THREAD

**Issue by wawltor** [microsoft/onnxruntime#1618]
[ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node ReduceMax(1)

**Comment by hariharans29** [comment]
Hi @wawltor,

Can you please share your model for debugging ? Most likely it just needs a type to be supported. Currently, ReduceMax only supports float and int32.

**Comment by wawltor** [comment]
> Hi @wawltor,
> 
> Can you please share your model for debugging ? Most likely it just needs a type to be supported. Currently, ReduceMax only supports float and int32.

Yes, I find the problem that the  ReduceMax do not support the int64.

**Comment by hariharans29** [comment]
Added the requested type support.
