### ISSUE TITLE
[Mobile] Unsupported ops: ai.onnx:ReduceMean

### ISSUE THREAD

**Issue by cmelody999** [microsoft/onnxruntime#16194]
### Unsupported ops: ai.onnx:ReduceMean

We converted the Pytorch model of ResNet-50 to a ONNX model, run check_onnx_model_mobile_usability to check if the operators in the model are supported by ORT’s NNAPI Execution Provider (EP) and reported an error: "Unsupported ops: ai.onnx:ReduceMean". How can we solve this problem? Is there a way to get around it? Thank you very much!
![image](https://github.com/microsoft/onnxruntime/assets/5425469/b3fb4099-9e5a-47d9-b25a-4b9d54d5f634)

__

### To reproduce

python -m check_onnx_model_mobile_usability --log_level debug D:\data\onnx\rn50.img.fp32.onnx

### Platform

Android

### OS Version

android 12

### ONNX Runtime Installation

Built from Source

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

1.14.0

### ONNX Runtime API

Java/Kotlin

### Architecture

X64

### Execution Provider

NNAPI

**Comment by edgchen1** [comment]
It should still be possible to run the model with this ReduceMean falling back to the CPU execution provider. You can test if the performance is acceptable.

We can look into adding support for ReduceMean in the NNAPI EP. [ANEURALNETWORKS_MEAN](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a047fe95a35b27f45c05432b6ca18eb6c) looks like the analogous NNAPI operation.

PRs are also welcome. :)

**Comment by YUNQIUGUO** [comment]
yeah, we can look into adding the ReduceMean op support for NNAPI. 

Would you mind sharing what's your use case/ is there a production scenario for this?

**Comment by cmelody999** [comment]
We use clip(https://github.com/OFA-Sys/Chinese-CLIP) to search images with text keywords. Now is there a way around using NNAPI? Also, when will ReduceMean op be supported?

The java code on Android phone uses version 1.14.0 of ONNX Runtime to enable NNAPI via ortOption.addNnapi() and reports the following error:
     Caused by: ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: model_builder.cc:457 AddOperandFromPersistMemoryBuffer ResultCode: ANEURALNETWORKS_BAD_DATA
![image](https://github.com/microsoft/onnxruntime/assets/5425469/937e479b-0f27-434a-81f4-ed97496b49d1)

Is the crash caused by not supporting ReduceMean op? Thank you very much!

**Comment by edgchen1** [comment]
> Now is there a way around using NNAPI?

> The java code on Android phone uses version 1.14.0 of ONNX Runtime to enable NNAPI via ortOption.addNnapi()

you can just skip calling `addNnapi()` to not add the NNAPI EP.

> Also, when will ReduceMean op be supported?

hopefully in the next release.

> Is the crash caused by not supporting ReduceMean op?

it's hard to say without more information. as this may be a separate problem, with a different model than what was in the original issue, would you mind opening a separate issue for it? providing the model if possible would be helpful.

**Comment by cmelody999** [comment]
When will the next release be released？I opened a new issue about the crash：https://github.com/microsoft/onnxruntime/issues/16224

**Comment by edgchen1** [comment]
> When will the next release be released?

The releases are quarterly and 1.15 just went out, so probably in 3 months or so.

> I opened a new issue about the crash：#16224

Thanks.
