### ISSUE TITLE
onnx model 50x slower than in pytorch

### ISSUE THREAD

**Issue by drapado** [microsoft/onnxruntime#1620]
**Describe the bug**
Hi, I exported my deep learning model from pytorch with an inference time of 2 ms. When I run it on onnx (doesn't matter onnx, onnx runtime python or C#) the inference time goes to 100 ms.

I also notice the GPU usage not going more than 30% when processing images.

Is this normal?

**System information**
- OS Platform and Distribution: Windows 10 and C#
- ONNX Runtime installed from (source or binary): NuGet
- ONNX Runtime version: 0.5
- Visual Studio version (if applicable): 2017
- CUDA/cuDNN version: 10 and 7.3
- GPU model and memory: RTX 2060

**Comment by faxu** [comment]
Are you able to share your model?

**Comment by drapado** [comment]
Hi, thanks a lot for your help.
Yes, this is the link to download it from my drive: https://drive.google.com/open?id=19zok790bCQjbM4enXF7ic0DmEU1peaAp

The input should be a float tensor of dimensions (1,3,1024,1024) with name actual_input_1
Example: NamedOnnxValue.CreateFromTensor<float>("actual_input_1", t1)

**Comment by YanYas** [comment]
@drapado, I'm having a similar issue. I haven't looked at your code yet, but are you using System.Numerics.Tensor.ToTensor() to convert your image floats into a tensor before you use NamedOnnxValue.CreateFromTensor()?

The ToTensor(), step, copying a flattened 720x720x3 array of floats to a Tensor, adds 80ms to my inference, while the CreateFromTensor() is very light and Inference.Session.Run() is seems around 2ms (GTX1070ti, Cuda). 

Perhaps Python has a more efficient way to transfer collections of floats/Numpy into a session.

Hi @faxu, any update on this issue?

**Comment by drapado** [comment]
Hi @YanYas,

are you getting 2 ms in session.run() with the model I uploaded in this issue? If so could you share the code you are using it to run it?

Thanks a lot!

**Comment by YanYas** [comment]
Hi @drapado,

Sorry, I didn't test with your model before, but I can understand you being dissatisfied with the inference time. After learning to create the Tensor from new Memory<Float>(Array<float32> I got a decent speed up. But I still only managed 72ms with your model using c#/[Gamma](https://vvvv.org/blog/vvvv-gamma-2019.1-preview).
The GPU usage peaked and trothed between 36% and 85% (tested with GPUShark). I can make the code available if you want it, and you don;t mind doing some setup. It isn't a strictly c# project

**Comment by faxu** [comment]
@drapado @YanYas - have you tried the lastest 1.0 release of ORT and does this issue still persist? A few additional CUDA kernels have been added, and there are more in the master branch that'll be in the next release or you can build from source.
