### ISSUE TITLE
Revised: Unable to run inference on onnx model of converted "albert-base-v2" transformer after using torch.onnx.export

### ISSUE THREAD

**Issue by LearrningLukeLondon** [microsoft/onnxruntime#16204]
### Describe the issue

Resubmitting this question as I have taken another method to resolving but still experiencing issues.

I finetuned an [albert-base-v2](https://huggingface.co/albert-base-v2) transformer model to complete a sentiment-analysis task, and after confirming I am able to run inference on the model using pytorch, I can't seem to run the inference on the onnx conversion of the model.

Running inference on the model using pytorch follows the basic steps below:

![image](https://github.com/microsoft/onnxruntime/assets/135020113/9457f989-00d2-4cbe-a81d-411e87148573)

However, after converting the model to onnx using the following step:
<img width="760" alt="image" src="https://github.com/microsoft/onnxruntime/assets/135020113/49fc7859-83ca-427d-a3c5-c6e6c4f40bff">

I am unable to run inference successfully with the same input data:
<img width="656" alt="image" src="https://github.com/microsoft/onnxruntime/assets/135020113/9fb38f7f-5173-4068-b0c8-5160b13875f0">

and am unable to understand how I should resolve the error above or do it correctly. I have already tried changing the input but not sure why its not working.

### To reproduce

N/A. 

### Urgency

I am blocked and can't continue my experiment.

### Platform

Windows

### OS Version

Windows 11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.15.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by tianleiwu** [comment]
Try the following:
```
inputs=tokenizer(text, return_tensors="pt")
ort_inputs = {k:v.detach().numpy() for k,v in inputs.items()}
outputs = ort_session.run(None, ort_inputs)
```
OR
```
ort_inputs=tokenizer(text, return_tensors="np")
outputs = ort_session.run(None, ort_inputs)
```

**Comment by LearrningLukeLondon** [comment]
Perfect, the first solution worked. Thank you you @tianleiwu!
