### ISSUE TITLE
Question about putting inputs / outputs in GPU memory

### ISSUE THREAD

**Issue by GuanLuo** [microsoft/onnxruntime#1621]
Hi, I am using the C API for ONNX Runtime, and as mentioned [here](https://github.com/microsoft/onnxruntime/blob/master/docs/C_API.md#features), "these inputs must be in CPU memory, not GPU". Are there plans to support providing inputs in GPU memory? As I am running the whole pipeline, including the ONNX model, on GPU, and it will be helpful if all the data transfer can be done in GPU instead of "GPU -> CPU -> GPU -> ..."

Similarly, can I specify outputs to be in GPU memory? Or currently it has the same limitation as for the inputs?

**Comment by xgirones** [comment]
This feature would be great for recursive-iterative models where the intermediate outputs are used as the input of the next iteration.

**Comment by linkerzhang** [comment]
I think allowing inputs (from GPU memory) is supported already. @pranavsharma

**Comment by pranavsharma** [comment]
Yes, you should be able to allocate inputs/outputs in GPU memory before calling Run(). The C API exposes a function called OrtCreateTensorWithDataAsOrtValue that creates a tensor with a pre-allocated buffer. It's up to you where you allocate this buffer as long as the correct OrtAllocatorInfo object is passed to this function.

**Comment by GuanLuo** [comment]
Sweet, thanks for clarifying that. I also wonder if there is existing example for doing that? If not, I will just do some trial and error to figure it out.

Also, since GPU memory can be used for inputs and outputs, do you mind to update the [C API doc](https://github.com/microsoft/onnxruntime/blob/master/docs/C_API.md#features) to remove the part about input can't be on GPU memory?

**Comment by xgirones** [comment]
What about the outputs? Is it possible to specify that some of the returned outputs should not be transferred to CPU?

**Comment by pranavsharma** [comment]
You can pre-allocate both inputs and outputs on the GPU. Sorry, we don't have example code.

**Comment by GuanLuo** [comment]
If outputs also need to be pre-allocated, then it is not possible to put variable-shape outputs into GPU directly, right? Since the size for outputs can only be determined after model run.

**Comment by pranavsharma** [comment]
> If outputs also need to be pre-allocated, then it is not possible to put variable-shape outputs into GPU directly, right? Since the size for outputs can only be determined after model run.

yeah, you'll need to know the output shape apriori if you want to pre-allocate memory for them.

**Comment by xgirones** [comment]
Could the GPU->CPU transfer be deferred until a call to _GetTensorMutableData_ is issued? Avoiding unnecessary transfers of intermediate results is critical for an efficient implementation of adaptive inference.

**Comment by pranavsharma** [comment]
OrtGetTensorMutableData does not make any copies of the data. It simply returns a pointer to the underlying raw buffer in the tensor.

**Comment by xgirones** [comment]
Yes, I am aware that _OrtGetTensorMutableData_ currently returns a pointer to the underlying buffer. 

I suggested delaying the GPU->CPU transfer until the output data is actually requested as a way of dealing with variable-shaped outputs whose layout cannot be determined beforehand. It has the advantage that it would not require changes in the interface, but any other alternative would be acceptable in order to have this feature.

**Comment by xgirones** [comment]
In the cases where the output tensors can be pre-allocated because their shapes can be determined beforehand they are still being transferred to CPU once the _OrtRun_ function finishes. Am I right? Is it possible to prevent this?

**Comment by pranavsharma** [comment]
If the output OrtValue is created with a cuda allocator and the last node in the graph runs on the GPU, no copy to CPU will take place; the output will be placed on the GPU.

**Comment by xgirones** [comment]
Great! This will save unnecessary GPU-CPU round trips when doing adaptive inference. Please let us know when the sample code is available. Thanks!

**Comment by pranavsharma** [comment]
@xgirones sorry, i missed one thing. Even though we've the API to create a tensor using any allocator (CreateTensorAsOrtValue), currently we don't have a public API to expose the allocator instance of the execution provider you're using as part of the session (in this case cuda). The only allocator we expose is the default CPU allocator. We'll add this to our roadmap.

**Comment by GuanLuo** [comment]
@pranavsharma thanks for the information, can I conclude that currently GPU I/O is not public accessible because the C API hasn't exposed the GPU memory allocator / allocator info?

**Comment by pranavsharma** [comment]
> @pranavsharma thanks for the information, can I conclude that currently GPU I/O is not public accessible because the C API hasn't exposed the GPU memory allocator / allocator info?

Yeah.

**Comment by xgirones** [comment]
Thanks. Will it be possible to access the underlying device memory (pointer, strides) in case we need to run some CUDA kernels on it?

**Comment by pranavsharma** [comment]
> Thanks. Will it be possible to access the underlying device memory (pointer, strides) in case we need to run some CUDA kernels on it?

The C API doesn't expose access to any specific device memory. Didn't fully understand your question though.

**Comment by xgirones** [comment]
I would like to take advantage of the fact that the output is already in device memory to do further processing on the device without doing unnecessary GPU-CPU-GPU round trips.

**Comment by solarflarefx** [comment]
How would this same concept translate to the C# API?

I am interested in passing data already in the GPU into a DL network with the output still residing in the GPU to be passed to the next element in a pipeline. If possible I’d like to do this without having to perform CPU/GPU copies. Is this possible at the moment?

**Comment by kitterive** [comment]
I also need this features,      Will the next version be available？ thanks.

**Comment by Armin234** [comment]
I need this feature too ... preferably mapping the Input/Output to a OpenCL Memory

**Comment by jgbradley1** [comment]
Please open this issue back up. It's still a highly-desired feature and will be a performance bottleneck for some models until appropriate additions have been made to the API.

**Comment by kitterive** [comment]
Does this feature supported?

**Comment by kitterive** [comment]
Is there sample code to use IOBindings get input from cuda buffers?

**Comment by pranavsharma** [comment]
> Is there sample code to use IOBindings get input from cuda buffers?

https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_inference.cc#L610

**Comment by GuanLuo** [comment]
Is there plan to expose GPU memory type in C APIs? The available types in C APIs are all CPU types... https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h#L252-L261

**Comment by pranavsharma** [comment]
@GuanLuo  you can simply use OrtMemTypeDefault which will be the cuda specific one if you create the mem info using this line ```  Ort::MemoryInfo info_cuda("Cuda", OrtAllocatorType::OrtArenaAllocator, 0, OrtMemTypeDefault);```.

**Comment by kitterive** [comment]
@pranavsharma When use OrtSessionOptionsAppendExecutionProvider_CUDA ,  succeed with  Ort::MemoryInfo info_cuda("Cuda", OrtAllocatorType::OrtArenaAllocator, 0, OrtMemTypeDefault);  But when use  OrtSessionOptionsAppendExecutionProvider_Tensorrt , failed!

**Comment by pranavsharma** [comment]
> @pranavsharma When use OrtSessionOptionsAppendExecutionProvider_CUDA , succeed with Ort::MemoryInfo info_cuda("Cuda", OrtAllocatorType::OrtArenaAllocator, 0, OrtMemTypeDefault); But when use OrtSessionOptionsAppendExecutionProvider_Tensorrt , failed!

Can you specify the exact repro steps? Also, this looks like a new issue. Can you please open a new one referencing this issue?

**Comment by nocti64** [comment]
Does this features support now? Really need this.
