### ISSUE TITLE
Segmentation fault with larger batch size using c++ API

### ISSUE THREAD

**Issue by osayes** [microsoft/onnxruntime#16222]
### Describe the issue

Using identical inference code, two models lead to segmentation fault error when batch size is larger than some value, the critical value is 7 for the smaller model and 1 for the larger model

Everything works fine with python

When debug, the error occured in the line:
`ThrowOnError(GetApi().Run(this->p_, run_options, input_names, ort_input_values, input_count, output_names, output_count, ort_output_values));`

In addition to `segmentation fault`, is there any way to output more useful information?

### To reproduce

...

### Platform

Linux

### OS Version

Ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by snnn** [comment]
build the source code from source, in Debug mode.  You can find the instructions at: https://onnxruntime.ai/docs/build/inferencing.html

Then run your application with the new binary. You can use gdb to get full stacktrace.

**Comment by osayes** [comment]
Thanks for your reply, it sounds a little cumbersome, but it seems to be the standard approach

I simplified the inference code and model, and used a official inference example code for comparison, finally I found the problem may be that I used a local `Ort::Env` variable to create session, when defining the `Ort::Env` at the same level as `Ort::Session`, the error disappeared
