### ISSUE TITLE
 Cast float32 to Ort::Float16_t to inference FP16 model

### ISSUE THREAD

**Issue by DennisJcy** [microsoft/onnxruntime#16262]
### Describe the issue

Hi!
I want to convert float32 (cv::Mat) to Ort::Float16_t to feed to my half-precision model.But firstly i need to normalize the input tensor.So when i used Ort::Float16_t()to cast the float to Float16_t, all data cast to zero
```c++
template<typename T>
char* BlobFromImage(cv::Mat& iImg, T& iBlob)
{
	int channels = iImg.channels();
	int imgHeight = iImg.rows;
	int imgWidth = iImg.cols;
#pragma omp parallel for
	for (int c = 0; c < channels; c++)
	{
		for (int h = 0; h < imgHeight; h++)
		{
			for (int w = 0; w < imgWidth; w++)
			{
				iBlob[c * imgWidth * imgHeight + h * imgWidth + w] = (std::remove_pointer<T>::type)(((float)iImg.at<cv::Vec3b>(h, w)[c]) / 255.0f);
				std::cout << (Ort::Float16_t)(((float)iImg.at<cv::Vec3b>(h, w)[c]) / 255.0f) << std::endl;
                                std::cout << (((float)iImg.at<cv::Vec3b>(h, w)[c]) / 255.0f) << std::endl;
			}
		}
	}
	return RET_OK;
}
```

After that,it seems like that Ort::Float16_t only support for uint16 datatype.So i used `half` which include in <cuda_fp16.h>,and used 
```c++	
Ort::Value input_tensor = Ort::Value::CreateTensor(Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU), blob, 3 * imgSize.at(0) * imgSize.at(1), YOLO_input_node_dims.data(), YOLO_input_node_dims.size(), ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT16);
```
like your example,but it get wrongs with:
`not enough space: expected 2457600, got 1228800`

**Could  you give me some suggestions?**

### To reproduce

as above

### Platform

Windows

### OS Version

win11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

onnxruntime-win-x64-gpu-1.14.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.3

**Comment by edgchen1** [comment]
note that this overload of Ort::Value::CreateTensor that specifies the data type as the last argument takes a data size in bytes, not number of elements.

https://github.com/microsoft/onnxruntime/blob/dc1312cfb150e4eaf138b30e5c7fc85a6346a246/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L1319-L1329

if you want to pass a buffer of n `half`s, pass `n * sizeof(half)` as `p_data_byte_count`.

**Comment by edgchen1** [comment]
```c++
std::cout << (Ort::Float16_t)(((float)iImg.at<cv::Vec3b>(h, w)[c]) / 255.0f) << std::endl;
```

regarding this, it's not a supported use of Ort::Float16_t, but I believe it is going through uint16_t because there are implicit conversions between Ort::Float16_t and uint16_t. casting a float between 0.0f and 1.0f to uint16_t would result in a 0.

**Comment by DennisJcy** [comment]
Update
I used 

> note that this overload of Ort::Value::CreateTensor that specifies the data type as the last argument takes a data size in bytes, not number of elements.
> 
> https://github.com/microsoft/onnxruntime/blob/dc1312cfb150e4eaf138b30e5c7fc85a6346a246/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L1319-L1329
> 
> if you want to pass a buffer of n `half`s, pass `n * sizeof(half)` as `p_data_byte_count`.

Thank you for your careful correction,It's my default.The function of using template is different from the inline function.

**Comment by DennisJcy** [comment]
> ```c++
> std::cout << (Ort::Float16_t)(((float)iImg.at<cv::Vec3b>(h, w)[c]) / 255.0f) << std::endl;
> ```
> 
> regarding this, it's not a supported use of Ort::Float16_t, but I believe it is going through uint16_t because there are implicit conversions between Ort::Float16_t and uint16_t. casting a float between 0.0f and 1.0f to uint16_t would result in a 0.

I changed to use `half` ,which could convert my normalization data from float32 to half by my template function above.
But i still have a question :why the `Ort::Float16_t` could not do the same thing like `half` because i think they are a same dataType?Maybe its my default.

**Comment by yuslepukhin** [comment]
We do not provide conversion functionality at this time. It requires to write actual logic to convert. Conversion and casting are not the same.

**Comment by DennisJcy** [comment]
thank you for your reply

**Comment by lsewcx** [comment]
@DennisJcy half 数据类型是哪里来的
