### ISSUE TITLE
[Build] 

### ISSUE THREAD

**Issue by dschwarz-tripp** [microsoft/onnxruntime#16269]
### Describe the issue

Is it possible to build an ONNX Runtime library for PlayStation 5 (.prx)? We are trying to deploy a model that is cross platform but hitting the problem where we don't have an adequate native plugin for PS4/PS5. Do you guys have a build configuration internally that I might be able to use to build it myself? Thanks!

### Target platform

PlayStation

### Build script

N/A

### Error / output

N/A

**Comment by snnn** [comment]
Sorry I don't know. But you may check this: https://github.com/microsoft/OnnxRuntime-UnrealEngine. If Unreal supports it, there must be a way.
