### ISSUE TITLE
Question about multiple dimension string tensor using CXX api

### ISSUE THREAD

**Issue by qw2208** [microsoft/onnxruntime#1627]
I'm creating a string tensor of two dimensions:
![WeChat Screenshot_20190815152341](https://user-images.githubusercontent.com/24438413/63079342-ae1eb080-bf70-11e9-9792-a515a81bfeaa.png)
Since my onnx model requires one input of dimension [1,2] type ONNX_TENSOR_ELEMENT_DATA_TYPE_STRING.

For one string tensor input, I could validate the results as [this link](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_inference.cc#L266) suggests. I'm wondering how I could get the created tensor and see the string value of each dimension? In other words, how could I use the api `GetStringTensorContent` for multiple dimension?

**Comment by RyanUnderhill** [comment]
I'm not sure what you mean by each dimension. Calling GetStringTensorContent will return all elements of a string tensor. So for example, one with shape { 2, 3, 4 } will return 24 elements (with the same order as other basic type tensors).

Or are you trying to get a subset of the tensor?

**Comment by qw2208** [comment]
Yes. You just answered my question. I'd like to make sure with the tensor I created:
![WeChat Screenshot_20190815152341](https://user-images.githubusercontent.com/24438413/63079342-ae1eb080-bf70-11e9-9792-a515a81bfeaa.png)
I can get the tensor by running the codes below?
![WeChat Screenshot_20190816104009](https://user-images.githubusercontent.com/24438413/63139823-3dc86b80-c012-11e9-9d3e-120349af6f93.png)
The string tensor will be returned in `result`?

**Comment by RyanUnderhill** [comment]
Yes, in this case results will be a single concatenated string in `result` and the `offsets` vector holds the starts of each string (the length is just the start of one until the start of the next one).
