### ISSUE TITLE
[Build] 

### ISSUE THREAD

**Issue by giovanniguasti** [microsoft/onnxruntime#16283]
### Describe the issue

I am building ONNX Runtime for DirectML EP
I am using this command:
`build.bat --config RelWithDebInfo --build_shared_lib --parallel --cmake_generator "Visual Studio 17 2022" --use_dml --build_wheel --skip_tests --cmake_extra_defines CMAKE_OSX_ARCHITECTURES=x86_64`

my python is 64 bits
my Windows OS is 64 bits

the generated wheel is named onnxruntime_directml-1.16.0-cp310-cp310-**win32**.whl
and I get this error when I pip install it:

`>pip install C:\data\lavoro\MachineLearning\onnx\test2\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\dist\onnxruntime_directml-1.16.0-cp310-cp310-win32.whl
ERROR: onnxruntime_directml-1.16.0-cp310-cp310-win32.whl is not a supported wheel on this platform.`

also tried with the following option
--cmake_extra_defines CMAKE_OSX_ARCHITECTURES=x86_64
but nothing changes

### Urgency

yes unfortunately this is urgent

### Target platform

Windows 64 bits, Python 3.10 64 bits

### Build script

`build.bat --config RelWithDebInfo --build_shared_lib --parallel --cmake_generator "Visual Studio 17 2022" --use_dml --build_wheel --skip_tests --cmake_extra_defines CMAKE_OSX_ARCHITECTURES=x86_64`

### Error / output

`ERROR: onnxruntime_directml-1.16.0-cp310-cp310-win32.whl is not a supported wheel on this platform.`

### Visual Studio Version

Visual Studio 17 2022

**Comment by snnn** [comment]
If you want a 64-bit Windows build, please make sure you have installed a 64-bit python and it is the only python in PATH.

**Comment by giovanniguasti** [comment]
Hi, I have also tried without this option but the result is the same. Please have you tried to reproduce the issue?
Thanks
Giovanni

Il giorno 8 giu 2023, alle ore 18:48, Changming Sun ***@***.***> ha scritto:

﻿
Caution: This message originated from an External Source. Use proper caution when opening attachments, clicking links, or responding.


CMAKE_OSX_ARCHITECTURES is for macOS/iOS/tvOS/... . Do not use it on other platforms. See https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_ARCHITECTURES.html

**Comment by giovanniguasti** [comment]
Yes, I have python 64 bits and windows 64 bits.
I will check if any other python is in the path. This is a good hint. Thanks

Il giorno 8 giu 2023, alle ore 20:09, Changming Sun ***@***.***> ha scritto:

﻿
Caution: This message originated from an External Source. Use proper caution when opening attachments, clicking links, or responding.


If you want a 64-bit Windows build, please make sure you have installed a 64-bit python and it is the only python in PATH.

**Comment by giovanniguasti** [comment]
Hi @snnn
I have double checked: this is the only python in PATH:
and in anaconda I only have 64 bits python:
(base) C:\Users\gguasti>python
Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import struct
>>> print(struct.calcsize("P") * 8)
64
>>>
(base) C:\Users\gguasti>wmic os get osarchitecture
OSArchitecture
64-bit

but when I build using the command 
build.bat --config RelWithDebInfo --build_shared_lib --parallel --cmake_generator "Visual Studio 17 2022" --use_dml --build_wheel --skip_tests

the generated wheel is named
onnxruntime_directml-1.16.0-cp310-cp310-win32.whl

and if I try to install it using pip I get the error message
ERROR: onnxruntime_directml-1.16.0-cp310-cp310-win32.whl is not a supported wheel on this platform.

I suspect there is a bug. Have you tried to reproduce the issue? how to force the build of a win64 wheel?
thanks

**Comment by omasoud** [comment]
[This](https://github.com/microsoft/onnxruntime/issues/17842#issuecomment-1902545957) worked for me.

**Comment by lishixlnx** [comment]
omasoud's comment is the only correct answer;

To make it easy, I just test : 
setting below 3 variable in shell window will stop the "win32.whl" producing and let "win64.whl" producing.

set Platform=x64
set VSCMD_ARG_HOST_ARCH=x64
set VSCMD_ARG_TGT_ARCH=x64
