### ISSUE TITLE
[Need Info][ONNXRUNTIME-SERVER] - Input JSON format for onnxruntime server

### ISSUE THREAD

**Issue by ac4922** [microsoft/onnxruntime#1628]
I am using onnx-runtime server and provided the model.onnx.

Now when to trying to get the inference, I am struggling with the I/P JSON payload format which should be given to get the inference.

Could you please help out with an example request playload (in json) for onnxruntime server api?

We are trying to achieve this : 
```
a = [ 889., 1614.,    0.,    0.,    0.,    0.,    0.,    0.,    0., 0.,    0.,    5.,    3.,    0.,    0.,    0.,    0.,    0.,3.,    0.]
sess.run(None ,{"features": np.array(a).astype(numpy.float32)})
```

Any help would be appreciated.

Thank you :)

**Comment by NonStatic2014** [comment]
The input json schema is defined in the [proto file](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/server/protobuf/predict.proto#L9).

If you are looking for a real sample, please refer to this [integration test data](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/testdata/server/mnist_test_data_set_0_input.json)

**Comment by faxu** [comment]
@ac4922 does this resolve your question? If so, please close the issue.
