### ISSUE TITLE
Request to add output for model load from protobuf

### ISSUE THREAD

**Issue by maxwillzq** [microsoft/onnxruntime#1629]
**Describe the bug**

Currently if I give different output tensor name to the model output, job will abort.
I check the code about this error message "This API is not supported when model is loaded from proto file right now"

```
void Graph::SetOutputs(const std::vector<const NodeArg*>& outputs) {
  if (GraphLoadedFromModelFile(graph_proto_)) {
    // TODO: add this support.
    ORT_THROW("This API is not supported when model is loaded from proto file right now.");
  }
  graph_outputs_ = outputs;
  graph_outputs_manually_set_ = true;
}
``` 

**Urgency**

This is a very usefult function
 
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by snnn** [comment]
Is your request similar to #1455 ?

**Comment by linkerzhang** [comment]
yes, same request.

@maxwillzq  please follow the #1455 to update the model as needed for now.

ORT will also make and expose a graph API to allow users to set graph/model outputs programmatically (in c++).
