### ISSUE TITLE
SequenceMap: Duplicate definition of name (_inline_SequenceMaprank).

### ISSUE THREAD

**Issue by titaiwangms** [microsoft/onnxruntime#16296]
### Describe the issue

The bug is caused by constant-propagation optimization within the subgraph. A workaround is to turn off graph-optimizations in session options.

Error: [onnxruntime] SequenceMap: Duplicate definition of name (_inline_SequenceMaprank).

cc @justinchuby @gramalingam 

### To reproduce

```python
@torch_op("aten::vstack")
def aten_vstack(tensors: Sequence[TTensor]) -> TTensor:
    """vstack(Tensor[] tensors) -> Tensor"""

    # TODO: This is exactly from aten_atleast_2d
    @graph()
    def reshape_to_2dd(tensor):
        shape = op.Shape(tensor)
        rank = op.Size(shape)
        if rank <= 1:
            tensor = op.Reshape(tensor, op.Constant(value_ints=[1, -1]))
        return tensor

    new_tensors = op.SequenceMap(tensors, body=reshape_to_2dd)

    return op.ConcatFromSequence(new_tensors, axis=0)
```
[model_vstack.zip](https://github.com/microsoft/onnxruntime/files/11693126/model_vstack.zip)

### Platform

Linux

### OS Version

20.04.5

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

Nightly

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by justinchuby** [comment]
Could you share the error?
