### ISSUE TITLE
how to set the cuda_mem_limit ? It's not effect

### ISSUE THREAD

**Issue by feng-1985** [microsoft/onnxruntime#16303]
### Describe the issue

onnxruntime=1.6
I want limit the gpu memory of onnx model, but it's not effect

### To reproduce

sess = onnxrt.InferenceSession(xxx, providers=["CUDAExecutionProvider"])

options = sess.get_provider_options()
option = options["CUDAExecutionProvider"]
ori_mem_limit = option["cuda_mem_limit"]
option["cuda_mem_limit"] = 900 * 1024 * 1024

### Platform

Linux

### OS Version

ubuntu 18

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.6

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by tianleiwu** [comment]
Look at `gpu_mem_limit` in the https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#samples:
```
import onnxruntime as ort

model_path = '<path to model>'

providers = [
    ('CUDAExecutionProvider', {
        'device_id': 0,
        'arena_extend_strategy': 'kNextPowerOfTwo',
        'gpu_mem_limit': 2 * 1024 * 1024 * 1024,
        'cudnn_conv_algo_search': 'EXHAUSTIVE',
        'do_copy_in_default_stream': True,
    }),
    'CPUExecutionProvider',
]

session = ort.InferenceSession(model_path, providers=providers)
```

**Comment by feng-1985** [comment]
`import onnxruntime as ort

model_path = '<path to model>'

providers = [
    ('CUDAExecutionProvider', {
        'gpu_mem_limit': 2 * 1024 * 1024 * 1024
    }),
    'CPUExecutionProvider',
]

session = ort.InferenceSession(model_path, providers=providers)`

raise the error:
TypeError: initialize_session(): incompatible function arguments. The following argument types are supported:
  1. (self: onnxrumtime.capi.onnxruntime_pybind11_state.InferenceSession, arg0: List[str], arg1: List[Dict[str, str]]) -> None

Invoked with:<onnnxruntime.capi.onnxruntime_pybind11_state.InferenceSession object at 0x7f062e395a70>, [('CUDAExecutionProvider', {'gpu_mem_limit': 2 * 1024 * 1024 * 1024}), 'CPUExecutionProvider'], []

**Comment by tianleiwu** [comment]
@feng-1985, you need specify a correct model path (like `model_path="./model.onnx"` instead of empty string).

**Comment by feng-1985** [comment]
Thanks for response! I have used the true model_path, the previous code just for example.

**Comment by tianleiwu** [comment]
#[feng-1985](https://github.com/feng-1985), the example script of gpu_mem_limit works in ORT 1.15. 

I noticed that you are using ORT 1.6. Please follow example to set the limit:
https://github.com/microsoft/onnxruntime/blob/718ca7f92085bef4b19b1acc71c1e1f3daccde94/onnxruntime/test/python/onnxruntime_test_python.py#L86-L96

**Comment by hariharans29** [comment]
If I recall correctly, the memory limit in the CUDA EP config is only for the CUDA memory arena used by the CUDA EP and hence limits ORT's memory allocation based on this value. But it doesn't limit memory allocation in other CUDA EP dependencies - like CuBlas, CuDNN. It is possible that there are memory allocations there that take it past the limit.

**Comment by feng-1985** [comment]
The relate [issue](https://github.com/microsoft/onnxruntime/issues/16264).  What I want is to reduce the cuda memory. 
As @hariharans29 said, it seems this parameter (cuda_mem_limit) cann't reduce cuda memory.
When should i use this parameters ? Is there any reference ?

**Comment by tianleiwu** [comment]
ok, then it is by design. Let's track it in that issue instead.
