### ISSUE TITLE
Error converting whisper model to ORT

### ISSUE THREAD

**Issue by jwanga** [microsoft/onnxruntime#16316]
### Describe the issue

I can successfully convert whisper to onnx with the following However when I attempt to convert the onnx model to ORT I get the following error:

```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /Users/username/Development/Olive/examples/whisper/models/whisper_cpu_int8_cpu-cpu_model.onnx failed:Fatal error: ai.onnx.contrib:BpeDecoder(-1) is not a registered function/op
```

### To reproduce

```
python prepare_whisper_configs.py
python -m olive.workflows.run --config whisper_cpu_int8.json --setup
python -m olive.workflows.run --config whisper_cpu_int8.json 2> /dev/null
python -m onnxruntime.tools.convert_onnx_models_to_ort models/whisper_cpu_int8_cpu-cpu_model.onnx
```

### Platform

Mac

### OS Version

13.4

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.0

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by kunal-vaishnavi** [comment]
The `BpeDecoder` op is a custom op created by [ONNX Runtime extensions](https://github.com/microsoft/onnxruntime-extensions) for Whisper. You will need to provide the library path for ONNX Runtime extensions in order to convert from ONNX to ORT.

You can get the library path as follows:
```
from onnxruntime_extensions import get_library_path

print(get_library_path())
```

Then you can pass the library path to `convert_onnx_models_to_ort` as follows:

```
$ python -m onnxruntime.tools.convert_onnx_models_to_ort --custom_op_library <output from get_library_path> models/whisper_cpu_int8_cpu-cpu_model.onnx
```

**Comment by kunal-vaishnavi** [comment]
Closed because solution was provided
