### ISSUE TITLE
Questions on Batch sizes and how onnxruntime treats them

### ISSUE THREAD

**Issue by minus-one** [microsoft/onnxruntime#1632]
I understand that onnxruntime does not care about batch-size itself, and that batch-size can be set as the first dimension of the model and you can use the first dimension as the batch-size.

To do batch inference, we just create an input_tensor OrtValue of appropriate size (based on input dimensions and the batch-size) and send it to OrtRun. (C-API)

I have couple of generic questions surrounding this:
1) Lets say the outermost dim of the model is 1. Does this mean, it will only support a batch-size of 1 ? 
2) For every batch-size, do I need to tweak the model-shape (outermost dim) to reflect the batch-size ?
2) It would not be non-trivial to Run the inference with different batch sizes across invocations (OrtRun C-api) as you would have to load different models in memory ?

Specifically, lets say we take the resnet50v2 from the onnx-zoo,
the inputname: data, has a shape: {1,3,224,224}. 
When I call OrtRun, with a OrtValue of dimension {2,3,224,224}, it shows an error in CheckShapes (inference_session.c) "Got invalid dimensions for input:"
Is this an expected error because the model shape's outermost dim is 1.

Weird observation: Here is the kicker, Batch inference worked in "some" older version of onnxruntime on the same resnet50v2 model, with shape as {1,3,224,224}. It didn't care about the outer most dim, and it just did batch inference for all the inputs happily.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary):
0.5.0 source

**Comment by snnn** [comment]
1. Yes
2. No. Set it a random string. Please search symbolic shape in the onnx repo.
3. Don't worry. It's easy.

We have an example for such use case: 
https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx/imagenet

But, onnxruntime also has some limitation and drawbacks on this approach. As you can see, in the example, when batch size changed, I choose to delete the session and re-create it. Through it is not necessary, but, practically speaking, in this special scenario (doing inference on a large dataset on GPU), it must be the best performant way.

**Comment by minus-one** [comment]
Awesome! Thanks for the reply.

Yes, as you say, batch-works. 
If I by-pass the CheckShapes for the outermost dim, it worked fine.

So, if I change the resnet50v2's outermost dimension to a random string, it would pass-through the CheckShapes check as well.
Maybe, the onnx-model-zoo should be updated to reflect this ? 

One last question,
> Through it is not necessary, but, practically speaking, in this special scenario (doing inference on a large dataset on GPU), it must be the best performant way.
Why is it performant to recreate the session ? I would presume session creation takes time. Is this to clear off unnecessary internal structures onnxruntime has ?

**Comment by snnn** [comment]
> Is this to clear off unnecessary internal structures onnxruntime has ?
Yes. To avoid running out of memory.

**Comment by snnn** [comment]
> Maybe, the onnx-model-zoo should be updated to reflect this ?

@faxu If it is needed, I can help.

**Comment by snnn** [comment]
@minus-one If you need any further help, please let me know.

**Comment by dharma135** [comment]
> 
> 
>     1. Yes
> 
>     2. No. Set it a random string. Please search symbolic shape in the onnx repo.
> 
>     3. Don't worry. It's easy.
> 
> 
> We have an example for such use case:
> https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx/imagenet
> 
> But, onnxruntime also has some limitation and drawbacks on this approach. As you can see, in the example, when batch size changed, I choose to delete the session and re-create it. Through it is not necessary, but, practically speaking, in this special scenario (doing inference on a large dataset on GPU), it must be the best performant way.

Hello, 
I am trying to run inference calls in a for loop with variable batch size.
for (int bs=1; bs <32; bs++) {
    1. Set input_dim[0] = bs; // or set input_dim[0] = 5;
     2. Create input tensor
     3. Call session_.run()
     4. Gather results from output_tensor
}
I see Memory consumption keeps increasing as the for loop progresses that if after step 4, if i do not recreate the session like it is done in Line 236 in the code below
https://github.com/microsoft/onnxruntime/blob/master/samples/c_cxx/imagenet/async_ring_buffer.h
Leak happens even if i set batch size to same value but i repeatedly call session.run with new input tensor. 
What actually happens when we call
session_ = Ort::Session(env_, model_path_.c_str(), session_options);

**Comment by Karnav123** [comment]
> I understand that onnxruntime does not care about batch-size itself, and that batch-size can be set as the first dimension of the model and you can use the first dimension as the batch-size.
> 
> To do batch inference, we just create an input_tensor OrtValue of appropriate size (based on input dimensions and the batch-size) and send it to OrtRun. (C-API)
> 
> I have couple of generic questions surrounding this:
> 
> 1. Lets say the outermost dim of the model is 1. Does this mean, it will only support a batch-size of 1 ?
> 2. For every batch-size, do I need to tweak the model-shape (outermost dim) to reflect the batch-size ?
> 3. It would not be non-trivial to Run the inference with different batch sizes across invocations (OrtRun C-api) as you would have to load different models in memory ?
> 
> Specifically, lets say we take the resnet50v2 from the onnx-zoo,
> the inputname: data, has a shape: {1,3,224,224}.
> When I call OrtRun, with a OrtValue of dimension {2,3,224,224}, it shows an error in CheckShapes (inference_session.c) "Got invalid dimensions for input:"
> Is this an expected error because the model shape's outermost dim is 1.
> 
> Weird observation: Here is the kicker, Batch inference worked in "some" older version of onnxruntime on the same resnet50v2 model, with shape as {1,3,224,224}. It didn't care about the outer most dim, and it just did batch inference for all the inputs happily.
> 
> **Urgency**
> none
> 
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
>   Linux Ubuntu 18.04
> * ONNX Runtime installed from (source or binary):
>   0.5.0 source

I am facing a similar issue. Could you please elaborate on the solution that fixed the issue for you.

**Comment by minus-one** [comment]
A quick answer is in this unrelated issue: https://github.com/microsoft/onnxruntime/issues/1467#issuecomment-514322927
Basically the model's input shape has to be tweaked to ensure it has a dim_param set.
