### ISSUE TITLE
[Dml] Errors in using Float16 in DirectML

### ISSUE THREAD

**Issue by DaiShaoJie77** [microsoft/onnxruntime#16384]
### Describe the issue

I found that converting the onnx model to the onnx float16 model requires a large amount of temporary memory to run the conv operator using DirectML, while the float32 model conv is not required. The result of convtransfer under float16 is still incorrect. I discovered this error by whether to convert these two types of operators when converting the model

### To reproduce

no

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

targe V1.14.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

DirectML

### Is this a quantized model?

No
```[tasklist]
### Tasks
```

**Comment by fdwr** [comment]
> I need your help

I'll need more info to be able to help, such as what error you're getting or a stack or actual output vs expected output.

**Comment by SJDai-375** [comment]
I use conv and close TransformGraph and Add an operator to the calculation queue without graph fusion,  use fp16 to getinitBindingProps.TemporaryResourceSize more than memory ,buf But how do I use fp32 he needs to be 0, But he didn't affect the outcome。ConvTranspose  results in errors The following is the normal output for F32 and the error output for Fp16。
this right：
![image](https://github.com/microsoft/onnxruntime/assets/98135989/c27391e1-ed16-423b-86cc-eefee0a31505)
this error：
![image](https://github.com/microsoft/onnxruntime/assets/98135989/e7b2adf0-cbac-4e64-b3e4-168bb7d6c5ca)

**Comment by SJDai-375** [comment]
The reason I use the layer-by-layer workflow is because I need to create a specific memory pool for the intermediate memory

**Comment by SJDai-375** [comment]
Layer-by-layer and graph-based workflows in DirectML are they executed in the same order?

**Comment by SJDai-375** [comment]
Can I use graph-based workflows in DirectML and control the in-between Tensor memory myself?

**Comment by SJDai-375** [comment]
You can create a model with only one transposed convolution to verify this problem

**Comment by SJDai-375** [comment]
But not all of them reproduce this problem

**Comment by SJDai-375** [comment]
@fdwr

**Comment by SJDai-375** [comment]
> > I need your help
> 
> I'll need more info to be able to help, such as what error you're getting or a stack or actual output vs expected output.

What's wrong here @fdwr

**Comment by fdwr** [comment]
- By "error", do you mean "numeric difference"? (I'm not seeing an error code or exception above?) 
- What other GPU's have you tried on? Have you tried newer versions of the driver?
- Do you get numeric differences if you run the attached .onnx file between CPU and GPU?

I tried this locally (which should match your attributes above), and my CPU and GPU (NVidia Quadro P620) with ORT 1.14 and produced the same values:

```
    {
      "graph_name": "Repro github onnxruntime issue 16384",
      "op_type": "ConvTranspose",
      "strides": [2,2],
      "kernel_shape": [4, 4],
      "output_shape": [1, 64, 20, 24],
      "pads": [1,1, 1,1],
      "X": {"dims": [1,128,10,12], "function": "iota", "should_embed_constant": true},
      "W": {"dims": [128, 64, 4, 4], "function": "iota", "should_embed_constant": true},
      "B": {"dims": [64]},
      "Y": {"dims": [1, 64, 20, 24]},
      "T": "float32",
    },
```

[ConvTranspose16384.zip](https://github.com/microsoft/onnxruntime/files/11872936/ConvTranspose16384.zip)

**Comment by SJDai-375** [comment]
> * “错误”是指“数字差异”吗？（我没有看到上面的错误代码或异常？）
> * 您还尝试过其他哪些 GPU？您是否尝试过更新版本的驱动程序？
> * 如果在 CPU 和 GPU 之间运行附加的 .onnx 文件，您会得到数字差异吗？
> 
> 我在本地尝试了这个（应该与您上面的属性匹配），我的 CPU 和 GPU (NVidia Quadro P620) 与 ORT 1.14 并产生了相同的值：
> 
> ```
>     {
>       "graph_name": "Repro github onnxruntime issue 16384",
>       "op_type": "ConvTranspose",
>       "strides": [2,2],
>       "kernel_shape": [4, 4],
>       "output_shape": [1, 64, 20, 24],
>       "pads": [1,1, 1,1],
>       "X": {"dims": [1,128,10,12], "function": "iota", "should_embed_constant": true},
>       "W": {"dims": [128, 64, 4, 4], "function": "iota", "should_embed_constant": true},
>       "B": {"dims": [64]},
>       "Y": {"dims": [1, 64, 20, 24]},
>       "T": "float32",
>     },
> ```
> 
> [ConvTranspose16384.zip](https://github.com/microsoft/onnxruntime/files/11872936/ConvTranspose16384.zip)

An error in the output. I only used 2050; Under F32, any result is normal, but under F16, most of the sizes will lead to a wrong result. I used the old onnx file, and I generated a simple model to try whether it is normal
[ConvTranspose.onnx.zip](https://github.com/microsoft/onnxruntime/files/11877105/ConvTranspose.onnx.zip)

**Comment by SJDai-375** [comment]
> * By "error", do you mean "numeric difference"? (I'm not seeing an error code or exception above?)
> * What other GPU's have you tried on? Have you tried newer versions of the driver?
> * Do you get numeric differences if you run the attached .onnx file between CPU and GPU?
> 
> I tried this locally (which should match your attributes above), and my CPU and GPU (NVidia Quadro P620) with ORT 1.14 and produced the same values:
> 
> ```
>     {
>       "graph_name": "Repro github onnxruntime issue 16384",
>       "op_type": "ConvTranspose",
>       "strides": [2,2],
>       "kernel_shape": [4, 4],
>       "output_shape": [1, 64, 20, 24],
>       "pads": [1,1, 1,1],
>       "X": {"dims": [1,128,10,12], "function": "iota", "should_embed_constant": true},
>       "W": {"dims": [128, 64, 4, 4], "function": "iota", "should_embed_constant": true},
>       "B": {"dims": [64]},
>       "Y": {"dims": [1, 64, 20, 24]},
>       "T": "float32",
>     },
> ```
> 
> [ConvTranspose16384.zip](https://github.com/microsoft/onnxruntime/files/11872936/ConvTranspose16384.zip)

An error in the output. I only used 2050; Use F32, any result is normal, but Use F16, most of the sizes will lead to a wrong result. I used the old onnx file, and I generated a simple model to try whether it is normal
[ConvTranspose.onnx.zip](https://github.com/microsoft/onnxruntime/files/11877121/ConvTranspose.onnx.zip)

**Comment by SJDai-375** [comment]
I found that I updated the latest driver transposed convolution and the results are fine, but how can I get every one of my customers to update the driver? Another problem I have with DirectML is that the convolutions in F16 run in layerwise mode require a lot of temporary memory and I don't seem to have a solution for this bug

**Comment by fdwr** [comment]
> but Use F16, most of the sizes will lead to a wrong result

🤔 I'm getting the exact same output between CPU vs GPU, even for float16: [ConvTranspose16384Float16.zip](https://github.com/microsoft/onnxruntime/files/11877420/ConvTranspose16384Float16.zip)

> I found that I updated the latest driver transposed convolution and the results are fine

That's great - seems the bug was fixed. \*For comparison, my local GPU is a NVidia Quadro P620 and driver is from 2023-02-02.

> the convolutions in F16 run in layerwise mode

"layerwise mode"? Please elaborate. DirectML supports `DML_CONVOLUTION_MODE_CONVOLUTION` and `DML_CONVOLUTION_MODE_CROSS_CORRELATION` modes.

**Comment by SJDai-375** [comment]
> > 但是使用F16，大多数尺寸都会导致错误的结果
> 
> 🤔即使对于 float16，我在 CPU 与 GPU 之间得到完全相同的输出：[ConvTranspose16384Float16.zip](https://github.com/microsoft/onnxruntime/files/11877420/ConvTranspose16384Float16.zip)
> 
> > 我发现我更新了最新的驱动转置卷积，结果还好
> 
> 太棒了 - 看来 bug 已经修复了。*作为比较，我的本地 GPU 是 NVidia Quadro P620，驱动程序来自 2023 年 2 月 2 日。
> 
> > F16 中的卷积以分层模式运行
> 
> “分层模式”？请详细说明。DirectML 支持`DML_CONVOLUTION_MODE_CONVOLUTION`和`DML_CONVOLUTION_MODE_CROSS_CORRELATION`模式。



> > but Use F16, most of the sizes will lead to a wrong result
> 
> 🤔 I'm getting the exact same output between CPU vs GPU, even for float16: [ConvTranspose16384Float16.zip](https://github.com/microsoft/onnxruntime/files/11877420/ConvTranspose16384Float16.zip)
> 
> > I found that I updated the latest driver transposed convolution and the results are fine
> 
> That's great - seems the bug was fixed. *For comparison, my local GPU is a NVidia Quadro P620 and driver is from 2023-02-02.
> 
> > the convolutions in F16 run in layerwise mode
> 
> "layerwise mode"? Please elaborate. DirectML supports `DML_CONVOLUTION_MODE_CONVOLUTION` and `DML_CONVOLUTION_MODE_CROSS_CORRELATION` modes.

https://learn.microsoft.com/en-us/windows/ai/directml/dml-intro；
Layer-by-layer and graph-based workflows in DirectML；
Generally, if the model with the onnx suffix will use the fusion graph pattern and the model with the ort suffix will use the Layer-by-layer pattern, but I forced him to use the Layer-by-layer pattern for both the onnx model and the ort model so that I could optimize its memory performance

**Comment by SJDai-375** [comment]
https://github.com/microsoft/onnxruntime/blob/ae6da03438970f25ea7a555a20522faca18762ee/onnxruntime/core/session/inference_session.cc#L1513
I changed this to if (0).

**Comment by SJDai-375** [comment]
> Sorry I didn't describe it well, I should have said that the execution mode of my Direml is not convolutional mode；
> 
> [https://learn.microsoft.com/en-us/windows/ai/directml/dml-intro；](https://learn.microsoft.com/en-us/windows/ai/directml/dml-intro%EF%BC%9B) Layer-by-layer and graph-based workflows in DirectML； Generally, if the model with the onnx suffix will use the fusion graph pattern and the model with the ort suffix will use the Layer-by-layer pattern, but I forced him to use the Layer-by-layer pattern for both the onnx model and the ort model so that I could optimize its memory performance

Sorry I didn't describe it well, I should have said that the execution mode of my Direml is not convolutional mode；

[https://learn.microsoft.com/en-us/windows/ai/directml/dml-intro；](https://learn.microsoft.com/en-us/windows/ai/directml/dml-intro%EF%BC%9B)
Layer-by-layer and graph-based workflows in DirectML；
Generally, if the model with the onnx suffix will use the fusion graph pattern and the model with the ort suffix will use the Layer-by-layer pattern, but I forced him to use the Layer-by-layer pattern for both the onnx model and the ort model so that I could optimize its memory performance

**Comment by SJDai-375** [comment]
> > but Use F16, most of the sizes will lead to a wrong result
> 
> 🤔 I'm getting the exact same output between CPU vs GPU, even for float16: [ConvTranspose16384Float16.zip](https://github.com/microsoft/onnxruntime/files/11877420/ConvTranspose16384Float16.zip)
> 
> > I found that I updated the latest driver transposed convolution and the results are fine
> 
> That's great - seems the bug was fixed. *For comparison, my local GPU is a NVidia Quadro P620 and driver is from 2023-02-02.
> 
> > the convolutions in F16 run in layerwise mode
> 
> "layerwise mode"? Please elaborate. DirectML supports `DML_CONVOLUTION_MODE_CONVOLUTION` and `DML_CONVOLUTION_MODE_CROSS_CORRELATION` modes.

Sorry I didn't describe it well, I should have said that the execution mode of my Direml is not convolutional mode；

[https://learn.microsoft.com/en-us/windows/ai/directml/dml-intro；](https://learn.microsoft.com/en-us/windows/ai/directml/dml-intro%EF%BC%9B)
Layer-by-layer and graph-based workflows in DirectML；
Generally, if the model with the onnx suffix will use the fusion graph pattern and the model with the ort suffix will use the Layer-by-layer pattern, but I forced him to use the Layer-by-layer pattern for both the onnx model and the ort model so that I could optimize its memory performance

**Comment by SJDai-375** [comment]
> > but Use F16, most of the sizes will lead to a wrong result
> 
> 🤔 I'm getting the exact same output between CPU vs GPU, even for float16: [ConvTranspose16384Float16.zip](https://github.com/microsoft/onnxruntime/files/11877420/ConvTranspose16384Float16.zip)
> 
> > I found that I updated the latest driver transposed convolution and the results are fine
> 
> That's great - seems the bug was fixed. *For comparison, my local GPU is a NVidia Quadro P620 and driver is from 2023-02-02.
> 
> > the convolutions in F16 run in layerwise mode
> 
> "layerwise mode"? Please elaborate. DirectML supports `DML_CONVOLUTION_MODE_CONVOLUTION` and `DML_CONVOLUTION_MODE_CROSS_CORRELATION` modes.

https://github.com/microsoft/onnxruntime/blob/ae6da03438970f25ea7a555a20522faca18762ee/onnxruntime/core/session/inference_session.cc#L1513

I changed this to if(0).

**Comment by DaiShaoJie-XiaMen** [comment]
> > but Use F16, most of the sizes will lead to a wrong result
> 
> 🤔 I'm getting the exact same output between CPU vs GPU, even for float16: [ConvTranspose16384Float16.zip](https://github.com/microsoft/onnxruntime/files/11877420/ConvTranspose16384Float16.zip)
> 
> > I found that I updated the latest driver transposed convolution and the results are fine
> 
> That's great - seems the bug was fixed. *For comparison, my local GPU is a NVidia Quadro P620 and driver is from 2023-02-02.
> 
> > the convolutions in F16 run in layerwise mode
> 
> "layerwise mode"? Please elaborate. DirectML supports `DML_CONVOLUTION_MODE_CONVOLUTION` and `DML_CONVOLUTION_MODE_CROSS_CORRELATION` modes.

Do you know how the amount of temporary memory needed to initialize an operator is calculated?
DirectML would be better if it were open source

**Comment by DaiShaoJie-XiaMen** [comment]
> > but Use F16, most of the sizes will lead to a wrong result
> 
> 🤔 I'm getting the exact same output between CPU vs GPU, even for float16: [ConvTranspose16384Float16.zip](https://github.com/microsoft/onnxruntime/files/11877420/ConvTranspose16384Float16.zip)
> 
> > I found that I updated the latest driver transposed convolution and the results are fine
> 
> That's great - seems the bug was fixed. *For comparison, my local GPU is a NVidia Quadro P620 and driver is from 2023-02-02.
> 
> > the convolutions in F16 run in layerwise mode
> 
> "layerwise mode"? Please elaborate. DirectML supports `DML_CONVOLUTION_MODE_CONVOLUTION` and `DML_CONVOLUTION_MODE_CROSS_CORRELATION` modes.

This is the convolution F32 that I tested only needs 25M TemporaryResourceSize, but F16 needs 318M
[dml_conv.onnx.zip](https://github.com/microsoft/onnxruntime/files/11882047/dml_conv.onnx.zip)

**Comment by DaiShaoJie-XiaMen** [comment]
@fdwr

**Comment by DaiShaoJie-XiaMen** [comment]
@fdwr can you help me?

**Comment by DaiShaoJie-XiaMen** [comment]
@skottmckay

**Comment by DaiShaoJie-XiaMen** [comment]
@skottmckay @fdwr

**Comment by DaiShaoJie77** [comment]
I have a solution to the problem
