### ISSUE TITLE
java onnxruntime_gpu does support cuda 12.x

### ISSUE THREAD

**Issue by umi-soft** [microsoft/onnxruntime#16386]
### Describe the feature request

I use onnxruntime_gpu with version 1.13 or 1.14 or 1.15，but I found it does not support cuda 12.x。Here is the error message：

```
failed to load libonnxruntime_providers_cuda.so with error: libcublaLt.so.11: cannot open shared file: No such file or directory.
```

in my linux system, I use cude 12.1，only has file `libcublaLt.so.12`

### Describe scenario use case

java onnxruntime_gpu support cuda for 12.x

**Comment by umi-soft** [comment]
I try create link by `ln -s /usr/local/cuda/lib64/libcublaLt.so.12 libcublaLt.so.11`， also has error message：
failed to load libonnxruntime_providers_cuda.so with error: `libcublas.so.11`: cannot open shared file: No such file or directory.

and then, create link by `ln -s /usr/local/cuda/lib64/libcublas.so.12 libcublas.so.11`,  also has error message：
failed to load libonnxruntime_providers_cuda.so with error: `libcufft.so.10`: cannot open shared file: No such file or directory.

**Comment by snnn** [comment]
You need to build it from source. Our prebuilt packages can only support one CUDA major version: either 11.x or 12.x.
