### ISSUE TITLE
OrtTensorProtoToOrtValue deleter

### ISSUE THREAD

**Issue by RandyGaul** [microsoft/onnxruntime#1640]
What is `deleter` in the function `OrtTensorProtoToOrtValue`? I don't really want a deleter, whatever it is. I tried setting the parameter `deleter` to NULL, but this caused a crash.

Why is this needed, if resources from `OrtTensorProtoToOrtValue` can be released with `OrtReleaseValue` (the `OrtValue** out` is already released with `OrtReleaseValue`)?

It seems like extra API baggage. Sadly, the docs just randomly stop when explaining what `out` is, and do not document `out` or `deleter`.

I noticed in my use case `deleter` is simply set to NULL... So why not allow me to pass in NULL to begin with? This seems like a very leaky API, unless I am misunderstanding something.

```cpp
/**
 * Create an OrtValue in CPU memory from a serialized TensorProto
 * @param input           serialized TensorProto object
 * @param input_len       length of 'input'.
 * @param input_file_path A local file path of where the input was loaded from. Can be NULL if the tensor proto doesn't
 *                        have any external data or it was loaded from current working dir. This path could be either a
 *                        relative path or an absolute path.
 * @param preallocated A preallocated buffer for the tensor. It should be allocated from CPU memory
 * @param preallocated_size Length of the preallocated buffer in bytes, can be computed from
 *          the OrtGetTensorMemSizeInBytesFromTensorProto function. This function will return an error if the
 *          preallocated_size is not enough.
 * @param out
 * @return
 */
ORT_API_STATUS(OrtTensorProtoToOrtValue, _In_ const void* input, int input_len,
               _In_opt_ const ORTCHAR_T* input_file_path, _Inout_ void* preallocated, size_t preallocated_size,
               _Outptr_ OrtValue** out, _Outptr_ OrtCallback** deleter);
```

**Comment by RandyGaul** [comment]
I actually can't find `OrtTensorProtoToOrtValue` in master anymore... How are we supposed to load up serialized proto tensors?

**Comment by snnn** [comment]
```c++
OrtCallback* callback;
OrtTensorProtoToOrtValue(...., &callback);
```

When the tensor is not needed anymore, you need to call OrtRunCallback(callback).

We deleted this API in the latest release because we thought nobody uses it.  

Would you let me know why do you need it? Where did you get the protobuf data from ?

**Comment by snnn** [comment]
If any input parameter, if it's a pointer and not marked with \_opt\_, then it can't be NULL.

**Comment by RandyGaul** [comment]
Yes I see when to run the callback, the question is why the `deleter` is exposed to the user at all. The user already has to call a cleanup function, why two? This is leaking your implementation details out to the user for no benefit to the user.

I had created an array of serialized proto tensors in Python with `numpy_helper.from_array(data)` and `file.write(tensor.SerializeToString())`, for testing the C API out. But in production we wouldn't be serializing to proto tensor format, and would use `OrtCreateTensorWithDataAsOrtValue`.

Thanks for clarifying, but since you removed this function altogether I suppose the issue can just be closed :)
