### ISSUE TITLE
[Mobile]  Slow Inference Time on Android armeabi-v7a with Conformer quantized Model Using Onnxruntime

### ISSUE THREAD

**Issue by xiaoqiang306** [microsoft/onnxruntime#16426]
### Describe the issue

When deploying a Conformer model using Onnxruntime, both static and dynamic quantization models have an inference time that is nearly 4 times slower on Android armeabi-v7a compared to Android arm64-v8a. I have enabled profiling and the trace results are shown below. From the inference time, almost all ops are significantly slower. What could be the possible reasons for this, and are there any other optimization methods available?

### To reproduce

1、Export the Conformer model in fp32 and dquant using PyTorch.
2、Follow run_qdq.py to obtain a static quantization model using calibration_dataset.
3、Deploy using Onnxruntime C++ API and compare the inference time between Android armeabi-v7a and Android arm64-v8a under the same conditions.

Android arm64-v8a  inference time 491ms
![截屏2023-06-20 下午5 26 52](https://github.com/microsoft/onnxruntime/assets/22621411/b949bb79-f3ea-43a0-9a36-684687e38117)

Android armeabi-v7a inference time 1925ms
![截屏2023-06-20 下午5 26 43](https://github.com/microsoft/onnxruntime/assets/22621411/41fade55-5696-42a4-badd-9f6e1d5c5298)

### Platform

Android

### OS Version

Android 10，huawei mate 20 pro

### ONNX Runtime Installation

Built from Source

### Compiler Version (if 'Built from Source')

cmake version 3.24, Android NDK 21.3.6528147

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

version:1.16, commit id: e139ae238bbce6772be76fcb7ea13fb402adc483

### ONNX Runtime API

C++/C

### Architecture

ARM32

### Execution Provider

Default CPU

**Comment by chenfucn** [comment]
We simply don't have optimized compute kernels for ARM 32:
https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/core/mlas/lib/aarch32

comparing with ARM 64 kernels:
https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/core/mlas/lib/aarch64

The reason is limited human resources. Contributions are welcome. You can also try using XNNPACK EP, which delegate the computation to xnnpack.

**Comment by skottmckay** [comment]
For an fp32 model definitely try XNNPACK. I would expect far better performance with that.
