### ISSUE TITLE
[Mobile][Android] No Implementation SessionOptions.createOptions(long)

### ISSUE THREAD

**Issue by ChthonicOne** [microsoft/onnxruntime#16434]
### Describe the issue

During creation of an ORT session, I run the following line in preparation to set the NNAPI flag:
`OrtSession.SessionOptions sessionOptions = new OrtSession.SessionOptions();`

This calls the SessionOptions.<init> at OrtSession.java:530:
`public SessionOptions() {`
`      nativeHandle = createOptions(OnnxRuntime.ortApiHandle); //<--`
`      customLibraryHandles = new ArrayList<>();`
`      configEntries = new LinkedHashMap<String, String>();`
`}`
Where I mark it calls the native code, and throws an exception when it cannot find an implementation for it.

### To reproduce

Place the following in your build.gradle (Module :app) dependencies:
`implementation 'com.microsoft.onnxruntime:onnxruntime-android:latest.release'`

Place the following in your build.gradle (Project: foo) repositories:
`maven()`

Write a piece of code to start an ORT session like so:
`        this.modelFileName = modelFilename;`
`        OrtSession.SessionOptions sessionOptions = new OrtSession.SessionOptions();`
`        sessionOptions.addNnapi();`
`        ortEnv = OrtEnvironment.getEnvironment();`
`        ortSession = ortEnv.createSession(readModel(assetManager, modelFilename), sessionOptions);`

It will throw an exception when creating a SessionOptions object.

### Urgency

Yes, we have been trying to use your framework for almost 2 months as evidenced here: https://github.com/microsoft/onnxruntime/discussions/15856 We have now tried to use your Java implementation hoping that we could get that one working when the C++ one would not work.

### Platform

Android

### OS Version

11

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

onnxruntime-android

### ONNX Runtime Version or Commit ID

Latest (1.15.0)

### ONNX Runtime API

Java/Kotlin

### Architecture

ARM64

### Execution Provider

Default CPU, NNAPI

**Comment by Craigacp** [comment]
I think that's because you're creating the `SessionOptions` before instantiating the `OrtEnvironment`, and so it's not loading the native library. Try creating the environment first, and I'll add a static init block to `SessionOptions` to ensure you at least get an ORT error if you do it.

**Comment by ChthonicOne** [comment]
But OrtEnv.createSession takes in a session object as part of it's parameters. How am I supposed to give it one if I'm supposed to run it first and I can't create one before I run it? This is a chicken and egg scenario.

**Comment by Craigacp** [comment]
No, you need to create an environment first, then you can create a session options and a session. The environment is separate from the session as you can have multiple sessions.

**Comment by ChthonicOne** [comment]
Oh, ok. Let me try that. So what you're saying is move the call

`ortEnv = OrtEnvironment.getEnvironment();` to the beginning. I wasn't aware that this would load the entire library. Never had a library I use work this way.

Anyways, after changing the ordering, I'm getting a new UnsatisfiedLinkError on this line now:
`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "OrtGetApiBase" referenced by ...`

**Comment by Craigacp** [comment]
Most classes in ORT do trigger the static initializer to load the library, the fact that `SessionOptions` doesn't is an oversight I'll fix. Making the environment be created is the quickest way of ensuring that happens, and as I mentioned it's necessary for things like logging to work so you get mysterious errors if you call ORT functions without creating the environment first.

The linker error is due to something in your build not packaging the native library correctly, but unfortunately I don't know anything about how Android packages native libraries so someone else will have to help you with that.

**Comment by ChthonicOne** [comment]
Do I have to manually download and package the native libraries myself, or are they part of the .aar that is downloaded by the build.gradle. I assumed the latter, but I had done the former at one point when working with the C++, and then cleaned that out when switching to Java since the Java instructions did not mention this at all.

From everything I know, the native libraries should be found in the `onnxruntime-android-1.15.0.aar` file in the `jni/arm64-v8a/libonnxruntime4j_jni.so` location within it. This is not where it is looking for some reason though. It is looking in `/base.apk!/lib/arm64-v8a/libonnxruntime4j_jni.so` location, suggesting that it should be in a lib directory, not jni directory.

This almost feels like the library is mispackaged for Android.

**Comment by edgchen1** [comment]
The native libraries are included in the .aar.

We have some Android examples, e.g.:
https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/image_classification/android

They should work with the latest release.

If that doesn't help, can you provide a reproducible example?

**Comment by ChthonicOne** [comment]
Ok, I just unpackaged the native libraries again like when I was working with the C++, and now it works. Is there a reason why I have to do this manually rather than just using the library AAR directly through gradle like your instructions say to for Java builds? If not, the instructions should be more clear about the need to unpackage them for all builds.

**Comment by edgchen1** [comment]
> Is there a reason why I have to do this manually rather than just using the library AAR directly through gradle like your instructions say to for Java builds?

I think it shouldn't be necessary - the Android examples just use the package directly. It could be that your build setup is different though.

**Comment by ChthonicOne** [comment]
> 

Could it be that we have some C++ modules in our code base, and this makes our project look there for .so files specifically?

**Comment by ChthonicOne** [comment]
Since I have managed to move past this error, even with the issues with not being able to just load the native source files directly from the .aar, I'm going to close this issue.

**Comment by zjc664656505** [comment]
> Ok, I just unpackaged the native libraries again like when I was working with the C++, and now it works. Is there a reason why I have to do this manually rather than just using the library AAR directly through gradle like your instructions say to for Java builds? If not, the instructions should be more clear about the need to unpackage them for all builds.

May I know which directory you put the libonnxruntime4j_jni.so under? I'm also facing the same issue now. Thanks!

**Comment by ChthonicOne** [comment]
> > Ok, I just unpackaged the native libraries again like when I was working with the C++, and now it works. Is there a reason why I have to do this manually rather than just using the library AAR directly through gradle like your instructions say to for Java builds? If not, the instructions should be more clear about the need to unpackage them for all builds.
> 
> May I know which directory you put the libonnxruntime4j_jni.so under? I'm also facing the same issue now. Thanks!
Sure. In your src folder use the following directory structure:
> main
>>jniLibs
>>>arm64-v8a
>>>armeabi-v7a
>>>v86
>>>v86_64
