### ISSUE TITLE
[Build] Building with TensorRT failed on Windows 10

### ISSUE THREAD

**Issue by wrd920** [microsoft/onnxruntime#16448]
### Describe the issue

Hi there,

I was trying to build onnxruntime with TensorRT on Windows 10 but has the failed. Could someone help with this issue?

I was using the main branch (as of 06/21/2023). I was using CUDA 11.6.0, CUDNN 8.5.0.96 and TensorRT 8.5.1.7

Thanks!

### Target platform

Windows 10

### Build script

.\build.bat --use_tensorrt --cuda_home="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6" --cudnn_home="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6" --tensorrt_home="E:\workspace\TensorRT-8.5.1.7" --cmake_generator="Visual Studio 17 2022"

### Error / output

-- Populating gsl
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.
-- Configuring done (0.5s)
-- Generating done (0.0s)
-- Build files have been written to: E:/workspace/onnxruntime_github/onnxruntime/build/Windows/Debug/_deps/gsl-subbuild
MSBuild version 17.6.3+07e294721 for .NET Framework

  Checking Build System
  Creating directories for 'gsl-populate'
  Building Custom Rule E:/workspace/onnxruntime_github/onnxruntime/build/Windows/Debug/_deps/gsl-subbuild/CMakeLists.txt
  Performing download step (download, verify and extract) for 'gsl-populate'
  -- Downloading...
     dst='E:/workspace/onnxruntime_github/onnxruntime/build/Windows/Debug/_deps/gsl-subbuild/gsl-populate-prefix/src/v4.0.0.zip'
     timeout='none'
     inactivity timeout='none'
  -- Using src='https://github.com/microsoft/GSL/archive/refs/tags/v4.0.0.zip'
  -- [download 8% complete]
  -- [download 34% complete]
  -- [download 44% complete]
  -- [download 65% complete]
  -- [download 71% complete]
  -- [download 78% complete]
  -- [download 84% complete]
  -- [download 88% complete]
  -- [download 100% complete]
  -- verifying file...
         file='E:/workspace/onnxruntime_github/onnxruntime/build/Windows/Debug/_deps/gsl-subbuild/gsl-populate-prefix/src/v4.0.0.zip'
  -- Downloading... done
  -- extracting...
       src='E:/workspace/onnxruntime_github/onnxruntime/build/Windows/Debug/_deps/gsl-subbuild/gsl-populate-prefix/src/v4.0.0.zip'
       dst='E:/workspace/onnxruntime_github/onnxruntime/build/Windows/Debug/_deps/gsl-src'
  -- extracting... [tar xfz]
  -- extracting... [analysis]
  -- extracting... [rename]
  -- extracting... [clean up]
  -- extracting... done
  No update step for 'gsl-populate'
  Performing patch step for 'gsl-populate'
  'Patch_EXECUTABLE-NOTFOUND' is not recognized as an internal or external command,
  operable program or batch file.
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(248,5): error MSB8066: Custom build for 'E:\workspace\onnxruntime_github\onnxruntime\build\Windows\Debug\_deps\gsl-subbuild\CMakeFiles\54add7b4a0c634fbeb474b7a57105c0f\gsl-populate-mkdir.rule;E:\workspace\onnxruntime_github\onnxruntime\build\Windows\Debug\_deps\gsl-subbuild\CMakeFiles\54add7b4a0c634fbeb474b7a57105c0f\gsl-populate-download.rule;E:\workspace\onnxruntime_github\onnxruntime\build\Windows\Debug\_deps\gsl-subbuild\CMakeFiles\54add7b4a0c634fbeb474b7a57105c0f\gsl-populate-update.rule;E:\workspace\onnxruntime_github\onnxruntime\build\Windows\Debug\_deps\gsl-subbuild\CMakeFiles\54add7b4a0c634fbeb474b7a57105c0f\gsl-populate-patch.rule;E:\workspace\onnxruntime_github\onnxruntime\build\Windows\Debug\_deps\gsl-subbuild\CMakeFiles\54add7b4a0c634fbeb474b7a57105c0f\gsl-populate-configure.rule;E:\workspace\onnxruntime_github\onnxruntime\build\Windows\Debug\_deps\gsl-subbuild\CMakeFiles\54add7b4a0c634fbeb474b7a57105c0f\gsl-populate-build.rule;E:\workspace\onnxruntime_github\onnxruntime\build\Windows\Debug\_deps\gsl-subbuild\CMakeFiles\54add7b4a0c634fbeb474b7a57105c0f\gsl-populate-install.rule;E:\workspace\onnxruntime_github\onnxruntime\build\Windows\Debug\_deps\gsl-subbuild\CMakeFiles\54add7b4a0c634fbeb474b7a57105c0f\gsl-populate-test.rule;E:\workspace\onnxruntime_github\onnxruntime\build\Windows\Debug\_deps\gsl-subbuild\CMakeFiles\73d35d2e82746a1f0c7f649ba3186745\gsl-populate-complete.rule;E:\workspace\onnxruntime_github\onnxruntime\build\Windows\Debug\_deps\gsl-subbuild\CMakeFiles\acaccf222455ba78904f4ea8f3c2fd62\gsl-populate.rule;E:\workspace\onnxruntime_github\onnxruntime\build\Windows\Debug\_deps\gsl-subbuild\CMakeLists.txt' exited with code 9009. [E:\workspace\onnxruntime_github\onnxruntime\build\Windows\Debug\_deps\gsl-subbuild\gsl-populate.vcxproj]
CMake Error at C:/Program Files/CMake/share/cmake-3.26/Modules/FetchContent.cmake:1622 (message):
  Build step for gsl failed: 1
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.26/Modules/FetchContent.cmake:1762:EVAL:2 (__FetchContent_directPopulate)
  C:/Program Files/CMake/share/cmake-3.26/Modules/FetchContent.cmake:1762 (cmake_language)
  external/helper_functions.cmake:139 (FetchContent_Populate)
  external/onnxruntime_external_deps.cmake:312 (onnxruntime_fetchcontent_makeavailable)
  CMakeLists.txt:514 (include)

-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "E:\workspace\onnxruntime_github\onnxruntime\\tools\ci_build\build.py", line 2640, in <module>
    sys.exit(main())
             ^^^^^^
  File "E:\workspace\onnxruntime_github\onnxruntime\\tools\ci_build\build.py", line 2498, in main
    generate_build_tree(
  File "E:\workspace\onnxruntime_github\onnxruntime\\tools\ci_build\build.py", line 1390, in generate_build_tree
    run_subprocess(
  File "E:\workspace\onnxruntime_github\onnxruntime\\tools\ci_build\build.py", line 792, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\workspace\onnxruntime_github\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "C:\Users\rw\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', 'E:\\workspace\\onnxruntime_github\\onnxruntime\\cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-DPython_EXECUTABLE=C:\\Users\\rw\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-DPYTHON_EXECUTABLE=C:\\Users\\rw\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-Donnxruntime_USE_MIMALLOC=OFF', '-Donnxruntime_ENABLE_PYTHON=OFF', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_JAVA=OFF', '-Donnxruntime_BUILD_NODEJS=OFF', '-Donnxruntime_BUILD_OBJC=OFF', '-Donnxruntime_BUILD_SHARED_LIB=OFF', '-Donnxruntime_BUILD_APPLE_FRAMEWORK=OFF', '-Donnxruntime_USE_DNNL=OFF', '-Donnxruntime_USE_NNAPI_BUILTIN=OFF', '-Donnxruntime_USE_RKNPU=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_VITISAI=OFF', '-Donnxruntime_USE_TENSORRT=ON', '-Donnxruntime_USE_TENSORRT_BUILTIN_PARSER=ON', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_TVM_CUDA_RUNTIME=OFF', '-Donnxruntime_TVM_USE_HASH=OFF', '-Donnxruntime_USE_MIGRAPHX=OFF', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_DISABLE_ML_OPS=OFF', '-Donnxruntime_DISABLE_RTTI=OFF', '-Donnxruntime_DISABLE_EXCEPTIONS=OFF', '-Donnxruntime_MINIMAL_BUILD=OFF', '-Donnxruntime_EXTENDED_MINIMAL_BUILD=OFF', '-Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF', '-Donnxruntime_REDUCED_OPS_BUILD=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=OFF', '-Donnxruntime_USE_WINML=OFF', '-Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxruntime_USE_ACL=OFF', '-Donnxruntime_USE_ACL_1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_USE_ACL_2002=OFF', '-Donnxruntime_USE_ARMNN=OFF', '-Donnxruntime_ARMNN_RELU_USE_CPU=ON', '-Donnxruntime_ARMNN_BN_USE_CPU=ON', '-Donnxruntime_USE_JSEP=OFF', '-Donnxruntime_ENABLE_NVTX_PROFILE=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_ENABLE_TRAINING_OPS=OFF', '-Donnxruntime_ENABLE_TRAINING_APIS=OFF', '-Donnxruntime_ENABLE_CPU_FP16_OPS=OFF', '-Donnxruntime_USE_NCCL=OFF', '-Donnxruntime_BUILD_BENCHMARKS=OFF', '-Donnxruntime_USE_ROCM=OFF', '-DOnnxruntime_GCOV_COVERAGE=OFF', '-Donnxruntime_USE_MPI=OFF', '-Donnxruntime_ENABLE_MEMORY_PROFILE=OFF', '-Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF', '-Donnxruntime_BUILD_WEBASSEMBLY_STATIC_LIB=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING=ON', '-Donnxruntime_ENABLE_WEBASSEMBLY_API_EXCEPTION_CATCHING=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_THROWING=ON', '-Donnxruntime_WEBASSEMBLY_RUN_TESTS_IN_BROWSER=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_PROFILING=OFF', '-Donnxruntime_ENABLE_LAZY_TENSOR=OFF', '-Donnxruntime_ENABLE_EXTERNAL_CUSTOM_OP_SCHEMAS=OFF', '-Donnxruntime_ENABLE_CUDA_PROFILING=OFF', '-Donnxruntime_ENABLE_ROCM_PROFILING=OFF', '-Donnxruntime_USE_XNNPACK=OFF', '-Donnxruntime_USE_WEBNN=OFF', '-Donnxruntime_USE_CANN=OFF', '-Donnxruntime_USE_TRITON_KERNEL=OFF', '-Donnxruntime_DISABLE_FLOAT8_TYPES=OFF', '-Donnxruntime_NVCC_THREADS=1', '-Donnxruntime_TENSORRT_HOME=E:\\workspace\\TensorRT-8.5.1.7', '-Donnxruntime_USE_FULL_PROTOBUF=ON', '-DProtobuf_USE_STATIC_LIBS=ON', '-DCMAKE_TLS_VERIFY=ON', '-DFETCHCONTENT_QUIET=OFF', '-Donnxruntime_USE_CUDA=ON', '-Donnxruntime_CUDA_HOME=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6', '-Donnxruntime_CUDNN_HOME=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6', '-DONNX_USE_MSVC_STATIC_RUNTIME=OFF', '-Dprotobuf_MSVC_STATIC_RUNTIME=OFF', '-Dgtest_force_shared_crt=ON', '-A', 'x64', '-T', 'host=x64,cuda=C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6', '-G', 'Visual Studio 17 2022', '-Donnxruntime_ENABLE_MEMLEAK_CHECKER=ON', '-DCMAKE_BUILD_TYPE=Debug', '-DCMAKE_PREFIX_PATH=E:\\workspace\\onnxruntime_github\\onnxruntime\\\\build\\Windows/Debug/installed']' returned non-zero exit status 1.

### Visual Studio Version

Visual Studio 17 2022

**Comment by tianleiwu** [comment]
Did you try install `pip install -r requirements-dev.txt` under python 3.8~3.11 before the build?

In my machine, I used the following script:
```
call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64 -vcvars_ver=14.36.32532

build.bat --cmake_generator "Visual Studio 17 2022" --config Release --cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES=61;70;75;80;86" --parallel --build_shared_lib --build_dir .\build\trt_2022 --use_cuda --cuda_version "12.1" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1" --cudnn_home "C:\CuDNN\8.8.1.3_cuda12" --use_tensorrt --tensorrt_home "E:\TensorRT-8.6.0.12.Windows10.x86_64.cuda-12.0\TensorRT-8.6.0.12"
```

**Comment by wrd920** [comment]
> Did you try install `pip install -r requirements-dev.txt` under python 3.8~3.11 before the build?
> 
> In my machine, I used the following script:
> 
> ```
> call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64 -vcvars_ver=14.36.32532
> 
> build.bat --cmake_generator "Visual Studio 17 2022" --config Release --cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES=61;70;75;80;86" --parallel --build_shared_lib --build_dir .\build\trt_2022 --use_cuda --cuda_version "12.1" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1" --cudnn_home "C:\CuDNN\8.8.1.3_cuda12" --use_tensorrt --tensorrt_home "E:\TensorRT-8.6.0.12.Windows10.x86_64.cuda-12.0\TensorRT-8.6.0.12"
> ```

Thank you for your reply! Unfortunately it still does not work on my end. 

I tried installing the same version of CUDA, CUDNN, TensorRT and Visual Studio as in your command, ran the "pip install -r requirements-dev.txt" with Python 3.11.4 and then ran the exact same command as in your reply (except for the paths that CUDA, CUDNN and TensorRT were installed). But I still got the same error "Patch_EXECUTABLE_NOTFOUND" when "Performing patch step for gsl-populate". When I do not include "--use_tensorrt" and build with CPU provider or "--use_dml", there is no such issue and the gsl-populate step was suscessful without performing patch.

How is your TensorRT installed? I downloaded TensorRT from the following link, unzip it and directly used the path including "bin" and "lib" as tensorrt_home. Is there any extra step I need to do for TensorRT? https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/secure/8.6.0/zip/TensorRT-8.6.0.12.Windows10.x86_64.cuda-12.0.zip

**Comment by tianleiwu** [comment]
@wrd920, your job failed due to Patch_EXECUTABLE-NOTFOUND. It is likely because patch.exe is not found in path. In my machine, it is installed in "C:\Program Files\Git\usr\bin\patch.exe". I suggest to reinstall Git for Windows from https://git-scm.com/download/win, and let installer updating PATH. You can run "patch.exe" in console to verify that it can be found.

For TensorRT installation, you can follow https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-zip

**Comment by wrd920** [comment]
> @wrd920, your job failed due to Patch_EXECUTABLE-NOTFOUND. It is likely because patch.exe is not found in path. In my machine, it can be found in "C:\Program Files\Git\usr\bin\patch.exe" or "C:\Users\USERNAME\AppData\Local\anaconda3\Library\usr\bin\patch.exe"
> 
> You can install [AnaConda](https://www.anaconda.com/download/) which contains patch.exe. After installing AnaConda, create a python environment to build like the following (TensorRT is updated to 8.6.1 GA here, need disable building unit tests to avoid build error):
> 
> ```
> conda create -n py310 python=3.10
> conda activate py310
> pip install -r requirements-dev.txt
> pip install cmake
> call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
> build.bat --cmake_generator "Visual Studio 17 2022" --config Release --parallel --build_shared_lib --use_cuda --cuda_version "12.1" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1" --cudnn_home "C:\CuDNN\8.9.2.26_cuda12" --use_tensorrt --tensorrt_home "E:\TensorRT-8.6.1.6.Windows10.x86_64.cuda-12.0\TensorRT-8.6.1.6"  --skip_tests --cmake_extra_defines onnxruntime_BUILD_UNIT_TESTS=OFF
> ```
> 
> During building, you can see output like:
> 
> ```
> Building ONNX Runtime for Windows 10 and newer
> Patch found: C:/Users/USERNAME/AppData/Local/anaconda3/Library/usr/bin/patch.exe
> ```
> 
> For TensorRT installation, you can follow https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-zip. Unzip the cuDNN and TensorRT installation zip files downloaded from Nvidia are enough for building onnxruntime. To run TensorRT, you will need add them to PATH etc.

Reinstalling git and adding it to PATH solves the issue. A lot of thanks!
