### ISSUE TITLE
[Mobile] Xamarin iOS native linking failed

### ISSUE THREAD

**Issue by SuperCD** [microsoft/onnxruntime#16444]
### Describe the issue

When building my project I get this error.
The ONNX runtime is referenced in a library project (that builds ok) that is then referenced in the main project which contains the iOS application that fails the build process with this message: 

MTOUCH: Error MT5214: Native linking failed, undefined symbol: _RegisterCustomOps. This symbol was referenced by the managed member Microsoft.ML.OnnxRuntime.OrtExtensionsNativeMethods.RegisterCustomOps. Please verify that all the necessary frameworks have been referenced and native libraries linked. (MT5214)

### To reproduce

Just add the library to a project, try to load a model and then use this project in a Xamarin Forms ios application

### Platform

Xamarin

### OS Version

iOS

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

Microsoft.ML.OnnxRuntime

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

C#

### Architecture

ARM64

### Execution Provider

Other / Unknown

**Comment by SuperCD** [comment]
I am silly... i forgot to import also the "ortextensions" nuget package. This is not a bug.

**Comment by gsgou** [comment]
@SuperCD  which package is the one you refere, stumbled on the same erro. Tks a lot for figuring it out.

**Comment by gsgou** [comment]
So in iOS project we need this one:
https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.Extensions
