### ISSUE TITLE
[Web] Error: no available backend found (works fine in 1.14.0, not in 1.15.x)

### ISSUE THREAD

**Issue by ericsvendsen** [microsoft/onnxruntime#16456]
### Describe the issue

When trying to create a new model using `InferenceSession.create`, the following error is thrown:
```
Error: no available backend found. ERR: [wasm] RuntimeError: Aborted(LinkError: WebAssembly.instantiate(): Import #41 module="a" function="P" error: function import requires a callable). Build with -sASSERTIONS for more info., [cpu] Error: previous call to 'initializeWebAssembly()' failed., [xnnpack] Error: previous call to 'initializeWebAssembly()' failed.
```
This only started when I upgraded from v1.14.0 to v1.15.1. Downgrading back to v1.14.0 (without changing anything else about my application) resolves the problem.

*.wasm files are served properly; 200 OK responses are returned. This is within an application bootstrapped using create-react-app.

### To reproduce

* Use create-react-app to instantiate a new project
* Import onnxruntime-web: `import * as ort from 'onnxruntime-web';`
* Import InferenceSession: `import { InferenceSession } from 'onnxruntime-web';`
* Configure ort env:
```
// onnxruntime
ort.env.debug = false;
ort.env.wasm.simd = true;

// set global logging level
ort.env.logLevel = 'verbose';

// override path of wasm files - for each file
ort.env.wasm.wasmPaths = {
    'ort-wasm.wasm': '/ort-wasm.wasm',
    'ort-wasm-simd.wasm': '/ort-wasm-simd.wasm',
    'ort-wasm-threaded.wasm': '/ort-wasm-threaded.wasm',
    'ort-wasm-simd-threaded.wasm': '/ort-wasm-simd-threaded.wasm',
};
```
* Try to create an inference session:
```
useEffect(() => {
    const initModel = async () => {
        const newModel = await InferenceSession.create('./path/to/file.onnx');
        // do stuff
    };
    initModel();
}, []);
```

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### Execution Provider

'wasm'/'cpu' (WebAssembly CPU)

**Comment by fs-eire** [comment]
> Import #41 module="a" function="P" error: function import requires a callable

The *.wasm files need to be the same version to the corresponding javascript files.

If you use the file ort-wasm.wasm from onnxruntime-web@1.14.0, it does not work with onnxruntime-web@1.15.x

if you replace the .wasm files to make them consistent with the javascript version, it will work.

**Comment by ericsvendsen** [comment]
Argh, of course. Thank you!
