### ISSUE TITLE
[Mobile] [Android] Computer Vision model works in Pytorch and NCNN but not in ONNX

### ISSUE THREAD

**Issue by ChthonicOne** [microsoft/onnxruntime#16466]
### Describe the issue

We are developing a computer vision object recognition model, and it works in Pytorch and NCNN, but it does not seem to work in ONNX despite the fact that we need to convert the Pytorch model into ONNX first in order to convert the ONNX model into NCNN. Since the NCNN model obviously works fine, the conversion to ONNX should work fine as well.

The model in question is based on WongKinYiu's Yolov7 model and uses that conversion method.

I have looked at the output of the model, and it appears that the output of the model does in fact look correctly formatted, being [1, 3, 80, 80, k] for the "output" layer, [1, 3, 40, 40, k] for the "292" layer, and [1, 3, 20, 20, k] for the "306" layer with the first 5 entries in k being the bounding box and the confidence. The issue is that it doesn't seem to find anything in the images like it should when I use `OrtSession.Result output = ortSession.run(Collections.singletonMap("images", inputTensor), outputs);`

Nothing in the log indicates that there is an issue either. Attached is the logcat from after the command is run. It does appear that the model is being loaded and run properly, though there is something going on at the start that might be involved, but I think it might be unrelated to this problem and related to the OS on the device.
[logcat.txt](https://github.com/microsoft/onnxruntime/files/11851011/logcat.txt)

The same code to convert and normalize images to float tensor array for input is being used as well.

### To reproduce

Build a model in Yolov7 and train it to the point that it can recognize objects. Then verify that the trained model can recognize objects in an image. Convert model to ONNX and load it into a Java ORT session. Have it try to recognize objects in same image. It will not recognize objects in this image.

### Platform

Android

### OS Version

11

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

onnxruntime-android

### ONNX Runtime Version or Commit ID

Latest (1.15.1)

### ONNX Runtime API

Java/Kotlin

### Architecture

ARM64

### Execution Provider

NNAPI

**Comment by ChthonicOne** [comment]
I also would like to add that I have tried our models in both NNAPI and CPU modes to make sure that it wasn't the NNAPI that was causing issues.

**Comment by ChthonicOne** [comment]
Another thing we've tried is an older version of the onnx-runtime. Specifically 1.12.1 which matched what was in the model according to netron.

**Comment by Craigacp** [comment]
How are you preparing the image data and passing that into the model?

**Comment by ChthonicOne** [comment]
`
Bitmap resizedInput = Bitmap.createScaledBitmap(bitmap, inputSize, inputSize, false);
resizedInput.getPixels(intValues, 0, resizedInput.getWidth(), 0, 0, resizedInput.getWidth(), resizedInput.getHeight());

for (int i = 0; i < intValues.length; ++i) {
            floatValues[i * 3 + 2] = (float) (( intValues[i]        & 0xFF) - MEAN ) * NORM;
            floatValues[i * 3 + 1] = (float) (((intValues[i] >> 8)  & 0xFF) - MEAN ) * NORM;
            floatValues[i * 3    ] = (float) (((intValues[i] >> 16) & 0xFF) - MEAN ) * NORM;
}
OnnxTensor inputTensor = OnnxTensor.createTensor(ortEnv, FloatBuffer.wrap(floatValues), shape);
OrtSession.Result output = ortSession.run(Collections.singletonMap("images", inputTensor), outputs);`

**Comment by Craigacp** [comment]
Isn't that writing the data in [W,H,C] rather than [C,W,H]?

**Comment by ChthonicOne** [comment]
I'll take a look at it, but it is the same way we wrote it for the other interface. I assumed it was correct as a result, but you might be right.

**Comment by ChthonicOne** [comment]
Yes, that's exactly it. For some reason, converting to NCNN seems to swap the input axes. There's no explanation for it as far as I can tell. I took it for granted that they were the same since it was the same model. Thank you for your help again. It's good to have some agnostic eyes on a problem sometime.
