### ISSUE TITLE
Experimental headers are no longer exposed, is it by design or by accident?

### ISSUE THREAD

**Issue by BoarQing** [microsoft/onnxruntime#16477]
### Describe the issue

After this PR https://github.com/microsoft/onnxruntime/pull/8919
Comparing to the debug install directory which has older commits, We can see my release install directory has less header files. Particularly, all the experimental APIs are gone.
Is it by design or accident? If it is by design, please reply because we need to change the demo code. If not, just close this issue.
![image](https://github.com/microsoft/onnxruntime/assets/21248762/ce337736-f761-4f86-a4be-73c9601bba57)

### Target platform

Xilinx Zynq(aarch640)

### Build script

None

### Error / output

header file missing

**Comment by BoarQing** [comment]
@prateek9623 @snnn @tianleiwu

**Comment by BoarQing** [comment]
> With that PR, I targeted similar cmake export as in the 1.15.1 release. If we want, we can add experimental headers also by adding the cmake option to enable its installation.



> Are you referring to https://github.com/microsoft/onnxruntime/blob/main/include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h? We don't really intend to expose these. Do you find anything missing in the official C++ headers (https://github.com/microsoft/onnxruntime/blob/main/include/onnxruntime/core/session/onnxruntime_cxx_api.h)?

Yes. I am referring to that file which we are using. But it was accidentally exposed, so would you keep the compatibility by adding those experimental headers back?
No I do not find offcial C++ headers missing.

**Comment by BoarQing** [comment]
> With that PR, I targeted similar cmake export as in the 1.15.1 release. If we want, we can add experimental headers also by adding the cmake option to enable its installation.

Could you tell me when can I expect the CMake Option for those experimental header files?

**Comment by pranavsharma** [comment]
The experimental headers are not officially supported. If nothing is missing in the official C++ headers, I would encourage you to take this opportunity to migrate to using them. As such we won't be releasing anything for another 3 months (we just had a release). Any fix will be in the main branch only.
