### ISSUE TITLE
[Build] Failed to build onnxruntime shared library in Jetson Xavier(CUDA EP)

### ISSUE THREAD

**Issue by seungtaek94** [microsoft/onnxruntime#16493]
### Describe the issue

I try to build onnxruntime shared library in Jetson Xavier with `CUDA`.

I succeed to build onnxruntime runtime version `1.12.1` in Jetson Xavier with `CUDA`.

But failed to build version `1.14.1` and `1.15.1` with below message.

My environment:
![image](https://github.com/microsoft/onnxruntime/assets/56434476/4c9fdbd2-dcda-464e-9709-aa6b02830816)

### Target platform

Jetson Xavier

### Build script

```
export CUDACXX="/usr/local/cuda/bin/nvcc"

./build.sh --config Release --update --build --parallel --build_shared_lib \
 --use_cuda --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu
```

### Error / output

```
[ 12%] Building CUDA object CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/home/seungtaek/onnxruntime/onnxruntime/test/shared_lib/cuda_ops.cu.o
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/build.make:75: recipe for target 'CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/home/seungtaek/onnxruntime/onnxruntime/test/shared_lib/cuda_ops.cu.o' failed
make[2]: *** [CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/home/seungtaek/onnxruntime/onnxruntime/test/shared_lib/cuda_ops.cu.o] Error 1
CMakeFiles/Makefile2:2163: recipe for target 'CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 12%] Building CXX object _deps/re2-build/CMakeFiles/re2.dir/re2/filtered_re2.cc.o
```

### Visual Studio Version

None

### GCC / Compiler Version

gcc (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by tianleiwu** [comment]
@seungtaek94, CUDA 10.2 is not supported in ORT 1.15.1. You can use CUDA 11.4 or later (11.7 or 11.8 is recommended for v1.15.1).

Since your build failed in test code, you can try add ` --skip_tests --cmake_extra_defines onnxruntime_BUILD_UNIT_TESTS=OFF`.

**Comment by seungtaek94** [comment]
@tianleiwu Thanks for reply :)
