### ISSUE TITLE
[Documentation] Need update CUDA EP documents for 1.15

### ISSUE THREAD

**Issue by tianleiwu** [microsoft/onnxruntime#16501]
### Describe the documentation issue

https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html
![image](https://github.com/microsoft/onnxruntime/assets/30328909/5ba4df52-2406-450d-bb7c-b36e8bae360c)

No information about 1.15.*

**Comment by natke** [comment]
The document was updated by #17081
