### ISSUE TITLE
[Feature Request] Add support for Python on Android (via termux)

### ISSUE THREAD

**Issue by nl255** [microsoft/onnxruntime#16514]
### Describe the feature request

I noticed that there is no support for the python API on Android even though thanks to termux most python software works just fine.  However onnx runtime can't be installed either via "pip install onnxruntime" (which says it doesn't exist) or by downloading the aarc64 "manylinux" wheel file and trying to install it manually (which says it is incompatible with this platform).  Aside from being a "prefixed" environment there are a few other differences from a standard Linux environment but they should be fairly minimal. https://wiki.termux.com/wiki/Differences_from_Linux

### Describe scenario use case

It would be nice to be able to run command line software that depends on onnxruntime via termux on Android especially since termux is currently the most popular way of running regular linux software, including python based software, on android mostly as-is.  This includes software such as rembg which can remove the background from images locally, without having to send the image to a remote server.

**Comment by skottmckay** [comment]
A terminal emulator that runs on Android seems like a fairly niche usage. Is there a production use-case?

The existing onnxruntime python package has aarch64 binaries. See https://pypi.org/project/onnxruntime/#files and search for aarch64 on the page. Should those be able to be used or does an Android specific build need to be created?

**Comment by nl255** [comment]
Unfortunately not, that is the first thing I tried and it said that it was not a valid wheel on this platform.  Perhaps because the only aarch64 linux build I see is for "manylinux" which does not work.  Here is a list of compatible tags.

`Compatible tags: 39
  cp311-cp311-linux_aarch64
  cp311-abi3-linux_aarch64
  cp311-none-linux_aarch64
  cp310-abi3-linux_aarch64
  cp39-abi3-linux_aarch64
  cp38-abi3-linux_aarch64
  cp37-abi3-linux_aarch64
  cp36-abi3-linux_aarch64
  cp35-abi3-linux_aarch64
  cp34-abi3-linux_aarch64
  cp33-abi3-linux_aarch64
  cp32-abi3-linux_aarch64
  py311-none-linux_aarch64
  py3-none-linux_aarch64
  py310-none-linux_aarch64
  py39-none-linux_aarch64
  py38-none-linux_aarch64
  py37-none-linux_aarch64
  py36-none-linux_aarch64
  py35-none-linux_aarch64
  py34-none-linux_aarch64
  py33-none-linux_aarch64
  py32-none-linux_aarch64
  py31-none-linux_aarch64
  py30-none-linux_aarch64
  cp311-none-any
  py311-none-any
  py3-none-any
  py310-none-any
  py39-none-any
  py38-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any
`

**Comment by skottmckay** [comment]
Do any pypi packages work on termux? Based on this conversation pypi requires a manylinux build: https://discuss.python.org/t/package-for-termux/26920/2

**Comment by nl255** [comment]
This package is the only one I have come across that doesn't work so far.  Others such as yt-dlp work fine.
