### ISSUE TITLE
[Feature Request] support for intel macos with amd gpu for leverage coreml

### ISSUE THREAD

**Issue by sukualam** [microsoft/onnxruntime#16526]
### Describe the feature request

i cant get gpu acceleration, i cant use onnxruntime-silicon because it seem for arm , i just want use coreml acceleration with my amd gpu

i have no idea why onnxruntime devs wont support coreml with amd gpu since it is actually supported when i using stable diffusion webui on macos with amd gpu.

my gpu: amd rx 560 (it can use coreml on stable diffusion macos)
macos: ventura 13.4

### Describe scenario use case

i cant get gpu acceleration, i cant use onnxruntime-silicon because it seem for arm , i just want use coreml acceleration with my amd gpu

i have no idea why onnxruntime devs wont support coreml with amd gpu since it is actually supported when i using stable diffusion webui on macos with amd gpu.

my gpu: amd rx 560 (it can use coreml on stable diffusion macos)
macos: ventura 13.4

**Comment by skottmckay** [comment]
We support CoreML on macOS and iOS. We don't tell CoreML what GPU it can or can't use.

As you haven't provided any details of the onnxruntime package you're using or how you're using it it's hard to say why it's not working for you. e.g. are you registering the CoreML execution provider in the session options before loading the model?

**Comment by sukualam** [comment]
i think i install wrong python (i use python 3.10) , cos i cant install related package in pip,, maybe i will test using python 3.9

**Comment by skottmckay** [comment]
Version 1.15 has a python 3.10 build.

Also note you need to explicitly enable the CoreML execution provider. https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html

**Comment by DaiShaoJie-XiaMen** [comment]
> 贡献



> 版本 1.15 有 python 3.10 构建。
> 
> 另请注意，您需要显式启用 CoreML 执行提供程序。https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html



> Version 1.15 has a python 3.10 build.
> 
> Also note you need to explicitly enable the CoreML execution provider. https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html

I use C++ to call onnxruntime CoreML it does not use GPU, my device is an AMD GPU,onnxruntime website also shows that, but your discussion makes me feel that I can use this AMD GPU

**Comment by DaiShaoJie-XiaMen** [comment]
> Version 1.15 has a python 3.10 build.
> 
> Also note you need to explicitly enable the CoreML execution provider. https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html

I use C++ to call onnxruntime CoreML it does not use GPU, my device is an AMD GPU,onnxruntime website also shows that, but your discussion makes me feel that I can use this AMD GPU

**Comment by skottmckay** [comment]
You can check the node assignment by setting the logging severity to VERBOSE (SessionOptions::SetLogSeverityLevel to 0) and seeing which nodes are assigned to CoreML. Look for 'Node placements' in the output.

**Comment by majaabal** [comment]
I have the same problem, It was working before updating the macOS, I am using macOS Sonoma 14.1
I remember before updating the mac it was working for me.
