### ISSUE TITLE
Unique op implementation missing input data types

### ISSUE THREAD

**Issue by f-salvetti** [microsoft/onnxruntime#16546]
### Describe the issue

According to [Onnx opset documentation](https://onnx.ai/onnx/operators/onnx__Unique.html#unique), Uniqe operator should support all input data types. Hower ORT only supports INT64, INT8, FLOAT, STRING, giving the following error otherwise when creating the session: 

```python
NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for Unique(11) node with name 'Unique'
```

### To reproduce

```python
from onnx import TensorProto, save
from onnx.helper import (
    make_model, make_node, make_graph,
    make_tensor_value_info)
from onnx.checker import check_model

import onnxruntime as rt

dtype = TensorProto.INT32

X = make_tensor_value_info('X', dtype, [None])
Y = make_tensor_value_info('Y', dtype, [None])

unique_node = make_node('Unique', ['X'], ['Y'], 'Unique')

graph = make_graph([unique_node], 'test', [X], [Y])
onnx_model = make_model(graph)
onnx.save(onnx_model, "test_model/model.onnx")
sess = rt.InferenceSession("test_model/model.onnx", session_options)

---------------------------------------------------------------------------
NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for Unique(11) node with name 'Unique'
```

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by baijumeswani** [comment]
Type support is generally added as necessary for production scenarios. Here is a thread that uncovers the reasoning behind this claim: https://github.com/microsoft/onnxruntime/issues/15397

If there is a need for this typed kernel (int32) for your production scenario, we welcome the contribution to ort.

**Comment by baijumeswani** [comment]
You could refer to https://github.com/microsoft/onnxruntime/pull/16359 in case you want to add the int32 support.
