### ISSUE TITLE
ReduceSum node not implemented

### ISSUE THREAD

**Issue by tanguycdls** [microsoft/onnxruntime#1657]
**Describe the bug**
To create a test to check an inference wrapper around OnnxRuntime I created a really simple model adding the inputs and expanding dims as so:
```
class model(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        return x.sum(dim=1).reshape(-1, 1).expand(-1, 10)

```
**System information**
- Linux Debian
- binary pip
- 0.5 and tested on 0.4
- 3.7 and tested 3.6
- Visual Studio version na
- GCC/Compiler version  na
- CUDA/cuDNN version: na
- GPU model and memory: na

**To Reproduce**
Export the model from Pytorch using 
```
from torch import onnx
a = model()
onnx.export(a, torch.from_numpy(np.array([1, 2, 3, 4])), 'model.onnx')
b = InferenceSession('model.onnx')
```
**Expected behavior**
We should be able to load since ReduceSum is implemented in the list of operators. 
'''
RuntimeError: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node ReduceSum(1)
'''

**Comment by faxu** [comment]
See this page for the list of supported ops and types: https://github.com/microsoft/onnxruntime/blob/master/docs/OperatorKernels.md

What is the datatype for the ReduceSum op in your model? Current support types in ORT are: 
T = tensor(int32), tensor(float), tensor(double)

**Comment by tanguycdls** [comment]
Hi thanks for the answer !
it's indeed int64 type (Long in Pytorch) I checked and its compatible with ONNX itself (int64). Maybe it would worth having a more verbose explanation when getting ReduceSum not implemented and adds the dtype for which it's not implemented ? 

Thanks for the help,
