### ISSUE TITLE
[Feature Request] Provide access to model node meta data

### ISSUE THREAD

**Issue by boxerab** [microsoft/onnxruntime#16588]
### Describe the feature request

Currently it is possible to only query model meta data, not meta data attached to a particular node.

### Describe scenario use case

In particular, it would be helpful to query meta data for each output layer, in GStreamer, so that a downstream element that knows nothing of ONNX can parse the meta data and interpret the context of a particular output layer.

**Comment by xadupre** [comment]
Can you be more specific about the language you are using? Is it a feature requet for onnx or onnxruntime?

**Comment by boxerab** [comment]
you're right, this is not an onnxruntime issue.
