### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by yxlwfds** [microsoft/onnxruntime#16585]
### Describe the issue

Is it a bug:: https://github.com/s0md3v/roop/issues/682

### Target platform

linux

### Build script

ss

### Error / output

sss

**Comment by tianleiwu** [comment]
It's by design. Just follow the logging to change your code:
```
Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(onnx_path, providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'])
```
