### ISSUE TITLE
Troubleshooting about high cpu usage and high latency.

### ISSUE THREAD

**Issue by qianshuangbei** [microsoft/onnxruntime#16590]
Hi,

I saw 100% cpu usage when call onnxruntime, and sometimes it take very long time to excute one inference. I saw some solutions in troubleshooting, but i don't know how to set in C#. 
1. Can you tell me how Can I enable sess_options.add_session_config_entry('session.dynamic_block_base', '4') in C# onnxruntime?

2. The lock-free task queue could be enabled by building onnxruntime from source with following flag: --use_lock_free_queue. Does this flag set during model conversion? or other place?

---
#### Document Details
* Title: Troubleshooting
* Page: [https://onnxruntime.ai/docs/performance/tune-performance/troubleshooting.html](https://onnxruntime.ai/docs/performance/tune-performance/troubleshooting.html)
* Page Source: troubleshooting.md

**Comment by baijumeswani** [comment]
> 1. Can you tell me how Can I enable sess_options.add_session_config_entry('session.dynamic_block_base', '4') in C# onnxruntime?

You can simply do:
`sess_options.AddSessionConfigEntry("session.dynamic_block_base", "4")`.

Please refer to the [C# API docs](https://onnxruntime.ai/docs/api/csharp/api/Microsoft.ML.OnnxRuntime.SessionOptions.html#Microsoft_ML_OnnxRuntime_SessionOptions_AddSessionConfigEntry_System_String_System_String_)  for more details.

> 2. The lock-free task queue could be enabled by building onnxruntime from source with following flag: --use_lock_free_queue. Does this flag set during model conversion? or other place?

The flag `--use_lock_free_queue` is an ONNX Runtime build argument. What that means is that you could need to build ONNX Runtime from source and pass in `--use_lock_free_queue` to `build.bat`/`build.sh` when compiling ONNX Runtime. You will need to build ONNX Runtime from source for this.

**Comment by baijumeswani** [comment]
I am going to close this issue. Please reopen if you need more help.
