### ISSUE TITLE
[Feature Request] Half datatype for InferenceSession.Run() (C#)

### ISSUE THREAD

**Issue by Kayzwer** [microsoft/onnxruntime#16607]
### Describe the feature request

Half datatype for InferenceSession.Run()

### Describe scenario use case

I want to speed up the inference time of RTDETR on C#

**Comment by baijumeswani** [comment]
Have you looked at: https://github.com/microsoft/onnxruntime/issues/1173#issuecomment-501088662

As for doing it in C#, please look at this test:

https://github.com/microsoft/onnxruntime/blob/d13f3153d7a1e87d81095ef5961887c1086f4b73/csharp/test/Microsoft.ML.OnnxRuntime.Tests.Common/InferenceTest.cs#L1318

**Comment by xadupre** [comment]
PR #16506 should address your request.
