### ISSUE TITLE
[Web] Unsupported model IR version: 9, max supported IR version: 8

### ISSUE THREAD

**Issue by xenova** [microsoft/onnxruntime#16638]
### Describe the issue

Unlike the `onnxruntime` python library, the web version does not yet support model IR version 9. I believe this is due to the [`onnx-proto`](https://www.npmjs.com/package/onnx-proto) dependency being quite out-of-date (last update published over a year ago).

Looking at their distributed "onnx.js" file (https://www.npmjs.com/package/onnx-proto?activeTab=code), IR_VERSION=8 is the latest entry into the version object. On the other hand, [netron](https://github.com/lutzroeder/netron) supports IR_VERSION=9, and this is the onnx-proto.js file that they use: https://github.com/lutzroeder/netron/blob/main/source/onnx-proto.js

Logs:
![image](https://github.com/microsoft/onnxruntime/assets/26504141/b3b9704a-6348-4c47-b927-30e99ac4d295)

### To reproduce

Load a model exported with `onnx>=1.14.0`

### Urgency

I am able to work around it by exporting models with `onnx==1.13.1`, however, the web version should ideally match the python version (which is able to run IR_VERSION=9).

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### Execution Provider

'wasm'/'cpu' (WebAssembly CPU)

**Comment by xenova** [comment]
cc @fs-eire, @guschmue

**Comment by fs-eire** [comment]
will make a change to upgrade IR version support

**Comment by fs-eire** [comment]
Submitted a PR for the upstream package 'onnx-proto': https://github.com/chaosmail/onnx-proto/pull/7

Once it's get merged and released a new version, I can upgrade onnxruntime-web to consume it

**Comment by Luckre** [comment]
Any updates?

**Comment by fs-eire** [comment]
> Any updates?

I think this issue should have been fixed in #16722.

**Comment by lix19937** [comment]
similar  `Unsupported model IR version: 10, max supported IR version: 9`

**Comment by fs-eire** [comment]
> similar `Unsupported model IR version: 10, max supported IR version: 9`

Which execution provider and which version are you using?

**Comment by lix19937** [comment]
@fs-eire   provider  is cpu 
onnx 1.16
onnxruntime 1.17.1  

after downscale the version of onnx to 1.15, the error is missed.

**Comment by fs-eire** [comment]
I see. Onnxruntime 1.17.1 is relatively outdated and latest dev channel should support IR v10

**Comment by Binozo** [comment]
> I see. Onnxruntime 1.17.1 is relatively outdated and latest dev channel should support IR v10

Using `1.20.1` I still get `Unsupported model IR version: 10, max supported IR version: 9` 😕
I am trying to use [jina's jina-embeddings-v3](https://huggingface.co/jinaai/jina-embeddings-v3/blob/main/onnx/model.onnx) model

**Comment by Binozo** [comment]
Nevermind had to include `onnxruntime.dll`
