### ISSUE TITLE
Implementations missing for INT64

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxruntime#16654]
- [ ] ArgMax
- [ ] ArgMin
- [ ] Erf
- [ ] Relu
- [ ] ReduceMax
- [ ] ReduceMin

**Comment by skottmckay** [comment]
We don't try and support every single type in the onnx spec for an operator as that would lead to unnecessary binary size growth for types that have no or only rare production usage. 

Is there a production use case where supporting these types is required?

**Comment by justinchuby** [comment]
Not that I am aware of. Just listing them as reference as we develop the conversion library for PyTorch where int64 is be supported.
