### ISSUE TITLE
[Build]  Fail building OnnxRuntime with Cuda 11.2 and docker

### ISSUE THREAD

**Issue by IzanCatalan** [microsoft/onnxruntime#16650]
### Describe the issue

Hi everyone, I'm trying to build onnxruntime for On-Device Training. To do so, I'm following the guidelines written in the tutorial: https://onnxruntime.ai/docs/build/training.html . I also cloned the main branch of the GitHub repo yesterday, so it is recent and the build script it is the one currently saved in the GitHub Repo. 

However, my environment is not equal. I'm building onnxruntime inside a docker container with ubuntu 20.04 together with cuda 11.2 and cudnn 8. Cmake version is 3.26 and python version is 3.8. 
Apparently, all the build finishes correctly, but it crashes when running the test as it is shown below. I'm still trying to figure out the errors. I am curious to know if it is a compilation error or a software test error. In both cases, I'm trying to figure out how to proceed. 

The shell command I use  is:  ./build.sh --config Release --build_shared_lib --parallel --enable_training_apis --allow_running_as_root --build_wheel --use_cuda --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ --cuda_version=11.2

Any help would be appreciated. Thanks,

### Target platform

Ubuntu 20.04

### Build script

#!/bin/bash
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Get directory this script is in
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
OS=$(uname -s)

if [ "$OS" = "Darwin" ]; then
    DIR_OS="MacOS"
else
    DIR_OS="Linux"
fi

if [[ "$*" == *"--ios"* ]]; then
    DIR_OS="iOS"
elif [[ "$*" == *"--android"* ]]; then
    DIR_OS="Android"
fi

#requires python3.6 or higher
python3 $DIR/tools/ci_build/build.py --build_dir $DIR/build/$DIR_OS "$@"

### Error / output

This is the error:

75% tests passed, 2 tests failed out of 8

Total Test time (real) = 359.53 sec

The following tests FAILED:
          1 - onnxruntime_test_all (Failed)
          5 - onnxruntime_global_thread_pools_test (Failed)
Errors while running CTest
Output from these tests are in: /home/onnxruntime/build/Linux/Release/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
Traceback (most recent call last):
  File "/home/onnxruntime/tools/ci_build/build.py", line 2621, in <module>
    sys.exit(main())
  File "/home/onnxruntime/tools/ci_build/build.py", line 2521, in main
    run_onnxruntime_tests(args, source_dir, ctest_path, build_dir, configs)
  File "/home/onnxruntime/tools/ci_build/build.py", line 1750, in run_onnxruntime_tests
    run_subprocess(ctest_cmd, cwd=cwd, dll_path=dll_path)
  File "/home/onnxruntime/tools/ci_build/build.py", line 786, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/ctest', '--build-config', 'Release', '--verbose', '--timeout', '10800']' returned non-zero exit status 8.

### GCC / Compiler Version

9.4.0

**Comment by baijumeswani** [comment]
I cannot tell what the test error is since the log you shared does not contain that information (from what I can tell).

If the binary was compiled fine, I think you should be good to start testing with the generated binary.

I would suggest adding the `--skip_tests` build arg to skip running all the unit tests if they continue to fail.

**Comment by IzanCatalan** [comment]
@baijumeswani I tried to reproduce the build, adding --skip_test  and now seems to finish, however, fails with the following error without generating the binary:

creating build/lib/onnxruntime/transformers/models/whisper
copying onnxruntime/transformers/models/whisper/convert_to_onnx.py -> build/lib/onnxruntime/transformers/models/whisper
copying onnxruntime/transformers/models/whisper/whisper_chain.py -> build/lib/onnxruntime/transformers/models/whisper
copying onnxruntime/transformers/models/whisper/whisper_encoder_decoder_init.py -> build/lib/onnxruntime/transformers/models/whisper
copying onnxruntime/transformers/models/whisper/whisper_decoder.py -> build/lib/onnxruntime/transformers/models/whisper
copying onnxruntime/transformers/models/whisper/whisper_helper.py -> build/lib/onnxruntime/transformers/models/whisper
copying onnxruntime/transformers/models/whisper/__init__.py -> build/lib/onnxruntime/transformers/models/whisper
copying onnxruntime/transformers/models/whisper/whisper_encoder.py -> build/lib/onnxruntime/transformers/models/whisper
error: package directory 'onnxruntime/training' does not exist
Traceback (most recent call last):
  File "/home/onnxruntime/tools/ci_build/build.py", line 2623, in <module>
    sys.exit(main())
  File "/home/onnxruntime/tools/ci_build/build.py", line 2544, in main
    build_python_wheel(
  File "/home/onnxruntime/tools/ci_build/build.py", line 1961, in build_python_wheel
    run_subprocess(args, cwd=cwd)
  File "/home/onnxruntime/tools/ci_build/build.py", line 789, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/home/onnxruntime/setup.py', 'bdist_wheel', '--enable_training_apis', '--wheel_name_suffix=gpu', '--cuda_version=11.2']' returned non-zero exit status 1.

Seems like it does not recognize onnxruntime training directory or it is changed and perhaps it is unable to create the Python Wheel.

**Comment by baijumeswani** [comment]
Are you intending to build for python (I see you have the --build_wheel argument)?

If yes, I might suggest you change the argument `--enable_training_apis` to `--enable_training`.

`--enable_training_apis` might be useful for on device training in particular for creating a share library, but it seems like it currently fails to build the python wheel.

**Comment by IzanCatalan** [comment]
@baijumeswani Yes, I intend to build for python because, for me, it is easier to import onnxruntime in my script and use it instead of linking with a shared library for C#. But also, I wanted to use On Device Training by using the methods and functions from https://onnxruntime.ai/docs/api/python/on_device_training/training_api.html 

If I use, as you said, --enable_training, it means that when creating a Python wheel and importing it later inside my python script, I won't be able to use those methods and functions? If that is the case, is there a way of building onnxruntime for on device training and later importing the binary in  python scripts?

**Comment by baijumeswani** [comment]
When passing in the `--enable_training` flag, all of ort training will be built (including on-device training apis, offline artifact generation apis and large model training functionality). It is a super set of `--enable_training_apis`.

I will try to fix the build error in the meantime. Apologies for the inconvenience.

**Comment by IzanCatalan** [comment]
Thanks for your help, @baijumeswani . I successfully compiled and created the Python wheel.
