### ISSUE TITLE
[Documentation] out of date URL

### ISSUE THREAD

**Issue by ola-ableton** [microsoft/onnxruntime#16678]
### Describe the documentation issue

https://onnxruntime.ai/docs/performance/graph-optimizations.html

this URL is used in four places: https://github.com/search?q=repo%3Amicrosoft%2Fonnxruntime+graph-optimizations.html&type=code

I believe it should be replaced with

https://onnxruntime.ai/docs/performance/model-optimizations/graph-optimizations.html

### Page / URL

https://github.com/microsoft/onnxruntime/blob/2449ded20f3b48bfbb8a58d161562f61d3129647/include/onnxruntime/core/session/onnxruntime_c_api.h#L328

**Comment by xadupre** [comment]
PR #16770 should fix it.
