### ISSUE TITLE
OrtSessionOptionsAppendExecutionProvider_CUDA Exception

### ISSUE THREAD

**Issue by swapnilbaadStM** [microsoft/onnxruntime#16677]
### Describe the issue

I am trying to run the inference on my Nvidia GPU. I have installed Microsoft.ML.OnnxRuntime.Gpu version 1.12.0 in Visual Studio 2019 using NuGet package manager.

Cuda Version 11.3.

I get exception: Exception thrown at 0x00007FFF94A23A48 (cudnn_cnn_infer64_8.dll)
`session.Run(runOptions, inputNames.data(), &inputTensor, 1, outputNames.data(), &outputTensor, 1);`

When I run the inference on CPU it works fine.

### To reproduce

// Use CUDA GPU
Ort::SessionOptions ort_session_options;
OrtCUDAProviderOptions options;
options.device_id = 0;
OrtSessionOptionsAppendExecutionProvider_CUDA(ort_session_options, options.device_id);
.
.
.
.
session.Run(runOptions, inputNames.data(), &inputTensor, 1, outputNames.data(), &outputTensor, 1);

### Urgency

Urgent

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Other / Unknown

### ONNX Runtime Version or Commit ID

1.12

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.3

**Comment by bc-arl** [comment]
Any luck on solving this? I'm having the same error. Also on windows.

**Comment by swapnilbaadStM** [comment]
Yes, I solved the above issue. 

I had not installed cuDNN properly. 

I followed the steps from here:
https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html
