### ISSUE TITLE
CUDA Version and graphic card driver Version

### ISSUE THREAD

**Issue by haobo724** [microsoft/onnxruntime#16675]
### Describe the issue

Hello everyone,

 I have a computer with a graphics card RTX3060 using the NV536.40 driver, which corresponds to CUDA version 12.2. However, I've also downloaded and installed the CUDA 11.6 toolkit and the corresponding cuDNN from the official NVIDIA site.

Here's my dilemma: I'm not certain which CUDA version I'm currently using or supposed to use, or if I need to downgrade my graphics card driver to match the CUDA 11.6 toolkit. This has been bothering me for a while now.

The results from the nvidia-smi 
Wed Jul 12 11:38:06 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.40                 Driver Version: 536.40       CUDA Version: 12.2     |

and nvcc -V commands 

**nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Fri_Dec_17_18:28:54_Pacific_Standard_Time_2021
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0**

They show different. I noticed that onnxruntime not officially support CUDA 12.x . But I could using 'pip install onnxruntime-gpu' to build onnxruntime in pure CUDA 12.2 enviroment (I tested once in CUDA 12.2 toolkit and uninstall it afterwards) . so I am so confused..

### To reproduce

pip install onnxruntime-gpu

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.6 CUDA12.2

**Comment by wschin** [comment]
Ideally, GPU driver should be backward compatible to previousl CUDA version. E.g, if you install driver which supports CUDA 12, then CUDA 11.6 should also work. There is probably one situation you have to match GPU driver version and CUDA version --- it happens when you want to profile your GPU program because [Nvidia's profiler](https://developer.nvidia.com/nsight-systems) doesn't maintain backward or forward compatibility.
