### ISSUE TITLE
Misleading error on TensorRT batching 

### ISSUE THREAD

**Issue by 24hours** [microsoft/onnxruntime#1669]
**Describe the bug**
When predicting with batch size > 1, an error with message : 
TRT enqueue failed: Set ORT_TRT_MAX_BATCH_SIZE environment variable to at least 16 is shown, 
However, setting `export ORT_TRT_MAX_BATCH_SIZE=16` will not fixed the issue and erorr continue to prompt. 

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 
- Python version: 3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda 10, cudnn 7.3
- GPU model and memory: GTX 1080

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**
According to this line:
https://github.com/microsoft/onnxruntime/blob/24d17f43533c0e15ec267d52c6b2f995aa5de65b/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc#L338

user should run `export ORT_TENSORRT_MAX_BATCH_SIZE=16` instead

**Comment by jywu-msft** [comment]
To confirm, you're saying the error message is wrong (TRT should be TENSORRT) but if you set ORT_TENSORRT_MAX_BATCH_SIZE, it does work?

**Comment by 24hours** [comment]
yes.

**Comment by jywu-msft** [comment]
Thanks.
https://github.com/microsoft/onnxruntime/pull/1687 will fix it.

**Comment by jywu-msft** [comment]
This is fixed.
