### ISSUE TITLE
[Feature Request] onnx -> tensorrt cache file custom name

### ISSUE THREAD

**Issue by juntaosun** [microsoft/onnxruntime#16708]
### Describe the feature request

Can you add the function of onnxruntime to convert tensorrt engine files, 
the current version can set trt_engine_cache_path, 
but the file it generates is a hash name, 
onnxruntime.InferenceSession：

cache/TensorrtExecutionProvider_TRTKernel_graph_torch_jit_12001107777560643811_0_0.engine. 
cache/TensorrtExecutionProvider_TRTKernel_graph_torch_jit_xxxxx_0_0.engine. 
cache/TensorrtExecutionProvider_TRTKernel_graph_torch_jit_xxxxx_0_0.engine. 

Will future versions be able to customize cache file names?

such as: "trt_engine_cache_filename "  : " abc.engine " , （example）

like this：
cache/abc.engine

even if it is rebuilt, the old file can be overwritten directly. 
This facilitates cache management for different onnx models.

### Describe scenario use case

It is convenient for the management of multi-model cache files. Under multiple different onnx models, it is difficult to distinguish and clean up the cache

**Comment by jywu-msft** [comment]
the hash encodes information about the subgraph, software version etc. (TRT engine files are not portable across gpu archs) to ensure that we load the correct and usable engine. so we need the hashid component.  but maybe we can allow the user to customize a prefix? would that work? 
+@yf711

**Comment by juntaosun** [comment]
That's great  @yf711

**Comment by yf711** [comment]
@juntaosun please check ort 1.17 which supports engine cache prefix. Thanks!
