### ISSUE TITLE
[Web] how to use it in offline application

### ISSUE THREAD

**Issue by zooeyking** [microsoft/onnxruntime#16729]
### Describe the issue

my application used in an offline environment, i try it by document like this
![image](https://github.com/microsoft/onnxruntime/assets/16650705/282c0c42-9f4c-45cc-ac08-d6e4c2480ac2)
![image](https://github.com/microsoft/onnxruntime/assets/16650705/c8b8da51-bb7a-4e5c-9380-84d8f51f1cb3)
it work well in dev environment, by i start server by "npm run start" to boot an local serve. 
while i need my application worked in offline environment. after i build it, i click index.html open it by chrome, something is wrong.
![image](https://github.com/microsoft/onnxruntime/assets/16650705/5e5f471f-a35c-4ceb-9ecc-5956d625f15f)
i try to solve it, i fond that the code need to fetch the model.onnx or some other xxx.wams file. but the fetch need local serve, otherwise the chrome's cors policy will forbidden this file.
i don't know how to make it work without local serve.
maybe i need a webpack-loader to read these file, but it is too hard for me. can you give me some tips to solve it.

### To reproduce

![image](https://github.com/microsoft/onnxruntime/assets/16650705/63c78b11-7a71-4149-83d4-731e74499976)
open index.html with chrome whitout local serve.

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

v1.15.1

### Execution Provider

'wasm'/'cpu' (WebAssembly CPU)

**Comment by fs-eire** [comment]
could you share me the code and/or the reproducing steps, so I can try to debug? The actual model file is not need.

**Comment by zooeyking** [comment]
> could you share me the code and/or the reproducing steps, so I can try to debug? The actual model file is not need.

https://github.com/microsoft/onnxruntime-inference-examples/tree/main/js/quick-start_onnxruntime-web-bundler
this link show a simple demo, but i con't boot up an local serve，i just drop index.html in chome to open it. 
![image](https://github.com/microsoft/onnxruntime/assets/16650705/0064ed89-6b3a-4466-adac-30db410442e0)

**Comment by guschmue** [comment]
I assume this is fixed.
