### ISSUE TITLE
[Build] PhaseScriptExecution Generate\ _deps/onnx-build/onnx/onnx-ml.pb.cc

### ISSUE THREAD

**Issue by JxuHenry** [microsoft/onnxruntime#16728]
### Describe the issue

I reported an error while compiling the onnx library for ios：
The following build commands failed:
        PhaseScriptExecution Generate\ _deps/onnx-build/onnx/onnx-ml.pb.cc /Users/jxu/work/onnxruntime/build/iOS/MinSizeRel/build/onnxruntime.build/MinSizeRel-iphoneos/gen_onnx_proto.build/Script-4B89B8E8968FC58B082D70E4.sh (in target 'gen_onnx_proto' from project 'onnxruntime')

### Target platform

ios

### Build script

./build.sh --config MinSizeRel --use_xcode --ios --ios_sysroot iphoneos --osx_arch arm64 --apple_deploy_target 12.0 --skip_tests --skip_submodule_sync --path_to_protoc_exe /Users/jxu/work/onnxruntime/protoc

### Error / output

The following build commands failed:
        PhaseScriptExecution Generate\ _deps/onnx-build/onnx/onnx-ml.pb.cc /Users/jxu/work/onnxruntime/build/iOS/MinSizeRel/build/onnxruntime.build/MinSizeRel-iphoneos/gen_onnx_proto.build/Script-4B89B8E8968FC58B082D70E4.sh (in target 'gen_onnx_proto' from project 'onnxruntime')
(1 failure)
Traceback (most recent call last):
  File "/Users/jxu/work/onnxruntime/tools/ci_build/build.py", line 2599, in <module>
    sys.exit(main())
  File "/Users/jxu/work/onnxruntime/tools/ci_build/build.py", line 2495, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/Users/jxu/work/onnxruntime/tools/ci_build/build.py", line 1434, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/Users/jxu/work/onnxruntime/tools/ci_build/build.py", line 781, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/Users/jxu/work/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/Users/jxu/anaconda3/envs/onnx/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/Users/jxu/work/onnxruntime/build/iOS/MinSizeRel', '--config', 'MinSizeRel']' returned non-zero exit status 65.

**Comment by xadupre** [comment]
Which version of protobuf are you using?

**Comment by JxuHenry** [comment]
> Which version of protobuf are you using?

Maybe v21.12 and how can i sure it ？I build in onnx 1.15.1 codes.
![image](https://github.com/microsoft/onnxruntime/assets/48616523/f74df13f-c1eb-4e89-9143-85e3fd6ab462)

**Comment by skottmckay** [comment]
What is in ` /Users/jxu/work/onnxruntime/protoc` and how was it created?

**Comment by JxuHenry** [comment]
> What is in ` /Users/jxu/work/onnxruntime/protoc` and how was it created? I believe that needs to point to the protoc binary and it would need to be executable. I can recreate the error by specifying an empty directory as `--path_to_protoc_exe`.

` /Users/jxu/work/onnxruntime/protoc` were the protoc of version osx 3.18.1 `https://github.com/protocolbuffers/protobuf/releases?page=6` 

![image](https://github.com/microsoft/onnxruntime/assets/48616523/52730c6b-9e62-4614-b966-8b1d6b4d07bb)

if I don't use `--path_to_protoc_exe` will got another  error ！

**Comment by JxuHenry** [comment]
> ./tools/ci_build/github/linux/docker/inference/x64/python/cpu/scripts/install_protobuf.sh -p /Users/jxu/work/onnxruntime/protobuf/ -d ./cmake/deps.txt

Thank you very much, but when I  run "sudo ./tools/ci_build/github/linux/docker/inference/x64/python/cpu/scripts/install_protobuf.sh -p /Users/jxu/work/onnxruntime/protobuf/ -d ./cmake/deps.txt" will got an new error: 

![image](https://github.com/microsoft/onnxruntime/assets/48616523/3a1de832-0815-43d4-bcaf-fa130fb43c93)

if I run "sudo ./tools/ci_build/github/linux/docker/inference/x64/python/cpu/scripts/install_protobuf.sh -d ./cmake/deps.txt" will got another error :

![image](https://github.com/microsoft/onnxruntime/assets/48616523/af3d9f8a-35c9-4a06-8a5a-ff62c873f8a4)

**Comment by skottmckay** [comment]
Why are you running the script with sudo? If it's 'installing' localling so shouldn't need to run as root.

Make sure there's no 'protobuf' directory in the root of your onnxruntime repo. You may have created on earlier. That should fix the 'File exists' error as install_protobuf.sh is hardcoded to expect that directory to not exist.

**Comment by JxuHenry** [comment]
> Why are you running the script with sudo? If it's 'installing' localling so shouldn't need to run as root.
> 
> Make sure there's no 'protobuf' directory in the root of your onnxruntime repo. You may have created on earlier. That should fix the 'File exists' error as install_protobuf.sh is hardcoded to expect that directory to not exist.

If I do not use sudo to execute the script, I will get the same error as above, how can I solve it

**Comment by skottmckay** [comment]
You can't set the install path with `-p` to the directory it's trying to build in. i.e. ` -p /Users/jxu/work/onnxruntime/protobuf/` is telling it to build and install in the same place.

**Comment by JxuHenry** [comment]
> You can't set the install path with `-p` to the directory it's trying to build in. i.e. ` -p /Users/jxu/work/onnxruntime/protobuf/` is telling it to build and install in the same place.

Thank you, I change  ` -p /Users/jxu/work/onnxruntime/protoc/` path sove the above error, then I running `./build.sh --config Release --use_xcode --ios --ios_sysroot iphoneos --osx_arch arm64 --apple_deploy_target 11.0 --skip_tests --path_to_protoc_exe /Users/jxu/work/onnxruntime/protoc/bin/protoc` got new error :

![image](https://github.com/microsoft/onnxruntime/assets/48616523/5d452d1b-65c7-479a-b4a7-3167f42f740a)

**Comment by skottmckay** [comment]
Build output should be in build/iOS/MinSizeRel/MinSizeRel-iphoneos but with the params you specified there may only be dylib for onnxruntime and you might need to specify `--build_apple_framework` if that's what you want it to produce. 

You can see the build settings we use when creating iOS packages [here](https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/github/apple/default_full_ios_framework_build_settings.json) which is run by this [script](https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/github/apple/build_and_assemble_ios_pods.py) that is mentioned in the [iOS build documentation](https://onnxruntime.ai/docs/build/ios.html#building-a-custom-ios-package).

**Comment by JxuHenry** [comment]
> --path_to_protoc_exe /Users/jxu/work/onnxruntime/protoc/bin/protoc



> Build output should be in build/iOS/MinSizeRel/MinSizeRel-iphoneos but with the params you specified there may only be dylib for onnxruntime and you might need to specify `--build_apple_framework` if that's what you want it to produce.
> 
> You can see the build settings we use when creating iOS packages [here](https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/github/apple/default_full_ios_framework_build_settings.json) which is run by this [script](https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/github/apple/build_and_assemble_ios_pods.py) that is mentioned in the [iOS build documentation](https://onnxruntime.ai/docs/build/ios.html#building-a-custom-ios-package).

OK，I build successed ，thank you very much
