### ISSUE TITLE
[Build] "nsync_cpp" is not in any export set

### ISSUE THREAD

**Issue by cnd** [microsoft/onnxruntime#16747]
### Describe the issue

getting:

CMake Error: install(EXPORT "onnxruntimeTargets" ...) includes target "onnxruntime" which requires target "nsync_cpp" that is not in any export set.

I have nsync_cpp installed in system and seems like without onnxruntime_SHARED_LIB cmake flag I don't get the error, but I need shared library

### Urgency

can't build shared library for onnxruntime using cmake

### Target platform

Linux

### Build script

cmake 

      -DBUILD_SHARED_LIBS=1
      -Donnxruntime_ENABLE_TRAINING=FALSE
      -Donnxruntime_BUILD_UNIT_TESTS=OFF
      -Donnxruntime_RUN_ONNX_TESTS=OFF
      -DFLATBUFFERS_BUILD_SHAREDLIB=ON
      -DFLATBUFFERS_INSTALL=ON
      -DABSL_ENABLE_INSTALL=ON
      -DCMAKE_INSTALL_LIBDIR=lib
      -Donnxruntime_ENABLE_CPUINFO=OFF

..

make

### Error / output

CMake Error: install(EXPORT "onnxruntimeTargets" ...) includes target "onnxruntime" which requires target "nsync_cpp" that is not in any export set.

### GCC / Compiler Version

12.3.1 20230623

**Comment by snnn** [comment]
Welcome to help us fix it.

**Comment by meerfrau** [comment]
@snnn Same issue, https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-onnxruntime doesn't fix it.

**Comment by gedoensmax** [comment]
Do you really require:
```
  -DBUILD_SHARED_LIBS=1
  -DFLATBUFFERS_BUILD_SHAREDLIB=ON
  -DFLATBUFFERS_INSTALL=ON
  -DABSL_ENABLE_INSTALL=ON
```
We saw that this less to failing the build with the above error. I would try reducing as much as possible.

**Comment by snnn** [comment]
BUILD_SHARED_LIBS is a standard cmake flag but I'm sorry we do not support it.  Most open source libraries are not that flexible that can be built as a static or dynamic library without extra code change. Protobuf is a great example.  Protobuf  itself is not stateless, if you build it as a shared library, the components who use this shared library will share states, which will cause conflicts. And, namely abseil, a library that most Google's open source libraries use, has very poor support for dynamic linking.  These issues cannot be solved at cmake level.

**Comment by snnn** [comment]
BUILD_SHARED_LIBS is a standard cmake flag but I'm sorry we do not support.  Most open source libraries are not that flexible that can be built as a static or dynamic library without extra code change. Protobuf is a great example.  Protobuf  itself is not stateless, if you build it as a shared library, the components who use this shared library will share states, which will cause conflicts. And, namely abseil, a library that most Google's open source libraries use, has very poor support for dynamic linking.  These issues cannot be solved at cmake level.

**Comment by KottV** [comment]
Afaik there is `-Donnxruntime_BUILD_SHARED_LIB=ON`  for build ibonnxruntime.so.1.*

**Comment by snnn** [comment]
#20413
