### ISSUE TITLE
ONNX model gets much slower on rel-0.5.0 compared to rel-0.4.0

### ISSUE THREAD

**Issue by GuanLuo** [microsoft/onnxruntime#1675]
**Describe the bug**
The same model takes much longer to run on ONNX Runtime rel-0.5.0 compares to running on rel-0.4.0

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 0.5.0
- Python version: 3.6.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
- CUDA/cuDNN version: 10
- GPU model and memory: TITAN V

**To Reproduce**
- Run in docker image built from [Dockerfile.cuda](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.cuda) in proper release version branch
- After unzipping the file from link in "additional context", run `perf_client_decoder_onnx_runtime.py` script, and latency will be printed once the script is finished

**Expected behavior**
The latency should be the same as running on rel-0.4.0, but it is more than 10x slower:
rel-0.5.0
```
5.224515144220607
Latency average (seconds) = 5.2252
Latency cl 50 (seconds) = 5.2356
Latency cl 90 (seconds) = 5.3368
Latency cl 95 (seconds) = 5.3922
Latency cl 99 (seconds) = 5.6429
Latency cl 100 (seconds) = 6.1242
```
rel-0.4.0
```
0.2804932994043042
Latency average (seconds) = 0.2805
Latency cl 50 (seconds) = 0.2762
Latency cl 90 (seconds) = 0.2947
Latency cl 95 (seconds) = 0.2999
Latency cl 99 (seconds) = 0.3504
Latency cl 100 (seconds) = 0.5494
```
**Screenshots**

**Additional context**
Link to the model and client:
https://drive.google.com/file/d/1r_3nHM-bBR_lyiezfsJhPsoOSdN29Afb/view?usp=sharing

**Comment by GuanLuo** [comment]
#1620 may also be relevant, the mode in rel-0.4.0 is already 2x slower than pytorch. Multiplying with the slow down mentioned here, the multiplier seems to be consistent

**Comment by HectorSVC** [comment]
The fix is merged to master, are you able to build it from source and test it? I tested it at my end, it's good.

**Comment by GuanLuo** [comment]
@HectorSVC Yes, the build from latest master produced good latency result similar to rel-0.4.0 release. Unfortunately, my project can't advance to that commit as it is still breaking on some simple use cases (#1592).

**Comment by HectorSVC** [comment]
@GuanLuo do you mind to close this one? we'll take a look for issue #1592

**Comment by GuanLuo** [comment]
Sure, I will close it now.
