### ISSUE TITLE
Usage of deprecated `torch.norm`

### ISSUE THREAD

**Issue by kit1980** [microsoft/onnxruntime#16751]
`torch.norm` is deprecated and may be removed in a future PyTorch release. Its documentation and behavior may be incorrect, and it is no longer actively maintained.

Please follow https://pytorch.org/docs/stable/generated/torch.norm.html to update.

orttraining/orttraining/python/training/optim/_modifier.py:140

**Comment by xadupre** [comment]
PR #16758 should fix it.
