### ISSUE TITLE
build requirements for CUDA EP are out of date

### ISSUE THREAD

**Issue by diablodale** [microsoft/onnxruntime#16771]
### Describe the documentation issue

Another part of build docs is out of date. This seems to be an ongoing issue. I recommend your project mgr look into automating it or making it part of the release process.

https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements does not have requirements for ORT 1.15 and newer. I suspect it needs CUDA 11.8, but cuDNN I'll need to poke though the source tree to find a version somewhere.

### Page / URL

https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements

**Comment by faxu** [comment]
Addressed by #17081
