### ISSUE TITLE
[Build] How to compile an ios static library that supports both arm64 and x86_64？

### ISSUE THREAD

**Issue by JxuHenry** [microsoft/onnxruntime#16783]
### Describe the issue

We need to compile an ios static library that supports both arm64 and x86_64, but we use the following two scirpts can only compile one type.

### Target platform

ios

### Build script

./build.sh \
--config Release \
--use_xcode \
--ios \
--ios_sysroot iphoneos \
--parallel \
--use_coreml \
--use_xnnpack \
--cmake_extra_defines=onnxruntime_BUILD_UNIT_TESTS=OFF \
--osx_arch arm64e \
--apple_deploy_target 12.0 \
--skip_tests \
--build_apple_framework \
or
./build.sh \
--config Release \
--use_xcode \
--ios \
--ios_sysroot iphonesimulator \
--parallel \
--use_coreml \
--use_xnnpack \
--cmake_extra_defines=onnxruntime_BUILD_UNIT_TESTS=OFF \
--osx_arch x86_64 \
--apple_deploy_target 12.0 \
--skip_tests \
--build_apple_framework \

### Error / output

None error

**Comment by skottmckay** [comment]
See https://github.com/microsoft/onnxruntime/issues/16728#issuecomment-1643522925. 

The script mentioned there uses a settings file that builds multiple architectures by default.

Additional documentation: https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/github/apple/use_ios_pods_with_custom_build.md

**Comment by JxuHenry** [comment]
> See [#16728 (comment)](https://github.com/microsoft/onnxruntime/issues/16728#issuecomment-1643522925).
> 
> The script mentioned there uses a settings file that builds multiple architectures by default.
> 
> Additional documentation: https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/github/apple/use_ios_pods_with_custom_build.md

Thank you very much. Let me try it first

**Comment by snnn** [comment]
add `--cmake_extra_defines CMAKE_OSX_ARCHITECTURES="arm64;x86_64"` to your build command.

**Comment by JxuHenry** [comment]
> If it is for macOS, you may add `--cmake_extra_defines CMAKE_OSX_ARCHITECTURES="arm64;x86_64"` to your build command. But I'm not sure if it also for iOS. Feel free to reopen this issue if you need more information.

OK，thanks a lot

**Comment by zxj329** [comment]
do u know how to compile static library on ios, i can not find the libonnxruntime.a
