### ISSUE TITLE
[Mobile] 

### ISSUE THREAD

**Issue by taocheng** [microsoft/onnxruntime#16792]
### Describe the issue

when I use onnxruntime-objc,
            env = try ORTEnv(loggingLevel: ORTLoggingLevel.warning)
            let options = try ORTSessionOptions()
            try options.setLogSeverityLevel(ORTLoggingLevel.warning)
            try options.setIntraOpNumThreads(threadCount)
            try options.appendExecutionProvider("xnnpack",providerOptions: ["intra_op_num_threads" : "2"])
            let session = try ORTSession(env: env, modelPath: modelPath, sessionOptions: options)
the session get error,i have no idea ,why this happen, how can I use func appendExecutionProvider?

### To reproduce

when I use onnxruntime-objc,
            env = try ORTEnv(loggingLevel: ORTLoggingLevel.warning)
            let options = try ORTSessionOptions()
            try options.setLogSeverityLevel(ORTLoggingLevel.warning)
            try options.setIntraOpNumThreads(threadCount)
            try options.appendExecutionProvider("xnnpack",providerOptions: ["intra_op_num_threads" : "2"])
            let session = try ORTSession(env: env, modelPath: modelPath, sessionOptions: options)
the session get error,i have no idea ,why this happen, how can I use func appendExecutionProvider?

### Platform

iOS

### OS Version

iOS 14.4

### ONNX Runtime Installation

Other / Unknown

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

onnxruntime-objc 1.5.0

### ONNX Runtime API

Objective-C/Swift

### Architecture

Other / Unknown

### Execution Provider

Default CPU

### Execution Provider Library Version

onnxruntime-objc 1.5.0

**Comment by edgchen1** [comment]
What's the error message?

**Comment by taocheng** [comment]
sorry the parameters "xnnpack" should be"XNNPACK",that is my fault, another question I want switch cpu to gpu, it can be achieve?

**Comment by skottmckay** [comment]
On iOS you could try the CoreML execution provider to use the Apple Neural Engine. We don't have an execution provider that uses Metal unfortunately. Will depend on the model as to how much of it CoreML can run.
