### ISSUE TITLE
[Feature Request] Ability to delete an ORT Web/Node.js session

### ISSUE THREAD

**Issue by josephrocca** [microsoft/onnxruntime#16796]
### Describe the feature request

This issue should perhaps be tagged with [Docs] because it may already exist, but I just can't seem to find anything about it.

I tried removing all references to the session (i.e. setting the `session` variable to `null`), but that didn't work. I can't see any session method when inspecting the properties/methods of the session object.

### Describe scenario use case

I have a server that only needs to run a model at startup. After that I want to free up the RAM by deleting the session.

**Comment by fs-eire** [comment]
I think `session.release()` should be manually called to release.

**Comment by josephrocca** [comment]
@fs-eire `session.release()` doesn't seem to exist as a method, but `await session.handler.dispose()` does - no sure if that is what you meant? However, that `dispose` method doesn't seem to free the memory. To test this you can open this page:

https://josephrocca.github.io/openai-clip-js/onnx-image-demo.html

Then open the console and then click the "start" button on the page. Wait for the model to load (it's ~350mb, you can see it downloading in the network tab), and then look at Chrome's Task Manager. For me it takes up about 1.3GB of memory. Now run `await session.handler.dispose()` in the console, and notice that the tab still takes up 1.3GB of memory.

**Comment by fs-eire** [comment]
Fixed by #18655.

**Comment by josephrocca** [comment]
@fs-eire Does the above pull request fix ORT Web too?

**Comment by fs-eire** [comment]
> @fs-eire Does the above pull request fix ORT Web too?

Web should have already support this. However, the web assembly memory can not shrink, so you may not observe it.
