### ISSUE TITLE
Career opportunities?

### ISSUE THREAD

**Issue by pauldog** [microsoft/onnxruntime#16802]
### Describe the issue

Hi, I have been using ONNX runtime (c#/directml ) for a while now and consider it the best option for running neural networks in game engines and such like. I was just wondering whether there may be opportunities contract/career for writing tutorials and such like for running ONNX models. I have got many models to run with onnxruntime including Stable Diffusion, Cerebras LLM, jets text-to-speech and much more.
For example. Here is a video I made of a frog turning into a cat running Stable Diffusion with ONNX runtime in the Unity 3D game engine:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/FSFrIl3MKjE/0.jpg)](https://www.youtube.com/watch?v=FSFrIl3MKjE) 

The video was generated about 0.8 seconds per frame then it is saved and played back.

I am great at writing tutorials and people are always impressed by my clear writing style.

Is there a contact address I could contact you at?

### To reproduce

n/a

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Other / Unknown

### ONNX Runtime Version or Commit ID

15

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

DirectML

**Comment by HectorSVC** [comment]
That's a great idea!
You can contribute your tutorials here: https://github.com/microsoft/onnxruntime-inference-examples/tree/main

**Comment by modjasperty** [comment]
awesome example
