### ISSUE TITLE
Reenable skipped test `test_training_and_eval_dropout`

### ISSUE THREAD

**Issue by justinchuby** [microsoft/onnxruntime#16801]
Test `test_training_and_eval_dropout` in `onnxruntime/test/python/onnxruntime_test_training_unit_tests.py` is disabled due to "The graph below will trigger ORT to sort backward graph before forward graph which gives incorrect result."

**Comment by baijumeswani** [comment]
`ORTTrainer` has been deprecated. We no longer use ORTTrainer for training. That file will be removed as part of the bigger ORTTrainer cleanup.

**Comment by justinchuby** [comment]
Thanks! Feel free to close at your discretion.
