### ISSUE TITLE
Runtime Exception for TensorRT 

### ISSUE THREAD

**Issue by xonobo** [microsoft/onnxruntime#1681]
I get this output 

> 2019-08-23 05:43:18.390194783 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer2.0.1.bn1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390215323 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer2.0.5.bn2.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390240777 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer2.0.0.downsample.1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390246288 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.5.1.bn2.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390253741 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.5.1.bn1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390277798 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer2.0.0.bn2.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390284752 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.4.2.bn2.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390290124 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390298307 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.4.1.bn2.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390316960 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer2.0.5.bn1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390339736 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.5.0.bn2.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390345472 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer2.0.4.bn2.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390355053 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.5.3.bn2.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390366523 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.4.0.bn2.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390384483 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer2.0.1.bn2.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390388974 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.4.0.bn1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390407052 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.5.0.bn1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390411636 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.4.1.bn1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390436824 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.5.0.downsample.1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390461372 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.5.3.bn1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390466234 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer2.0.0.bn1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390471136 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer2.0.2.bn1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390476556 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer2.0.2.bn2.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390483571 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer2.0.3.bn1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390490461 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.5.2.bn2.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390515410 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer2.0.4.bn1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390524281 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.5.2.bn1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390562507 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer1.4.2.bn1.num_batches_tracked'. It is not used by any node and should be removed from the model.
> 2019-08-23 05:43:18.390574316 [W:onnxruntime:Default, graph.cc:2269 CleanUnusedInitializers] Removing initializer 'backbone.model.layer2.0.3.bn2.num_batches_tracked'. It is not used by any node and should be removed from the model.
> Found unsupport node: 3
> Found unsupport node: 129
> Found unsupport node: 16
> Found unsupport node: 0
> Unsupported ONNX data type: INT64 (7)
> Found unsupported input: NonMaxSuppression_683
> Found unsupport node: 0
> Unsupported ONNX data type: INT64 (7)
> Found unsupported input: Slice_695
> Unsupported ONNX data type: INT64 (7)
> Found unsupported input: Slice_688
> Unsupported ONNX data type: INT64 (7)
> Found unsupported input: Gather_690
> Unsupported ONNX data type: INT64 (7)
> Found unsupported input: Mul_703
> Unsupported ONNX data type: INT64 (7)
> Found unsupported input: Add_704
> Unsupported ONNX data type: INT64 (7)
> Found unsupported input: Cast_705
> Found unsupported input: Gather_706
> Unsupported ONNX data type: INT64 (7)
> Found unsupported input: Gather_729
> Found unsupported input: Gather_706
> Found unsupported input: Gather_733
> Unsupported ONNX data type: INT64 (7)
> Found unsupported input: Unsqueeze_730
> 2019-08-23 05:43:18.965886560 [E:onnxruntime:Default, inference_session.cc:551 Initialize] Exception during initialization: /onnxruntime/onnxruntime/core/optimizer/transformer_memcpy.cc:333 bool onnxruntime::TransformerMemcpyImpl::ProcessInitializers(const onnxruntime::KernelRegistryManager&, const InitializedTensorSet&) status.IsOK() was false. Failed to find kernel for MemcpyFromHost (node Memcpy_1)
> Stacktrace:
> 
> Traceback (most recent call last):
>   File "ort_ssd_example.py", line 32, in <module>
>     session = onnxruntime.InferenceSession('ssd.onnx', None)
>   File "/usr/local/lib/python3.6/dist-packages/onnxruntime-0.5.0-py3.6.egg/onnxruntime/capi/session.py", line 29, in __init__
>     self._sess.load_model(path_or_bytes)
> RuntimeError: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime/onnxruntime/core/optimizer/transformer_memcpy.cc:333 bool onnxruntime::TransformerMemcpyImpl::ProcessInitializers(const onnxruntime::KernelRegistryManager&, const InitializedTensorSet&) status.IsOK() was false. Failed to find kernel for MemcpyFromHost (node Memcpy_1)
> Stacktrace:
> 
> 
> 

when tried to apply sample SSD object detection model.
Here is the code for object detection.

```
import numpy as np
import onnxruntime    # to inference ONNX models, we use the ONNX Runtime
import onnx
from onnx import numpy_helper
from PIL import Image

# Load the raw image
input_shape = (1, 3, 1200, 1200)
img = Image.open("blueangels.png")  
img = img.resize((1200, 1200), Image.BILINEAR)

# Preprocess and normalize the image
img_data = np.array(img)
img_data = np.transpose(img_data, [2, 0, 1])
img_data = np.expand_dims(img_data, 0)
mean_vec = np.array([0.485, 0.456, 0.406])
stddev_vec = np.array([0.229, 0.224, 0.225])
norm_img_data = np.zeros(img_data.shape).astype('float32')
for i in range(img_data.shape[1]):
    norm_img_data[:,i,:,:] = (img_data[:,i,:,:]/255 - mean_vec[i]) / stddev_vec[i]

## Run the model on the backend
session = onnxruntime.InferenceSession('ssd.onnx', None)

# get the name of the first input of the model
input_name = session.get_inputs()[0].name
bboxes, labels, scores = session.run([], {input_name: norm_img_data})
```

Here is the [ssd.onnx](https://onnxzoo.blob.core.windows.net/models/opset_10/ssd/ssd.onnx) and blueangels image is grabbed from [here](https://github.com/onnx/tutorials/blob/master/tutorials/OnnxRuntimeServerSSDModel.ipynb).

Here is the [docker](https://github.com/xonobo/onnxrt/blob/master/Dockerfile_cuda-10.0_trt) I used that builds onnxruntime and TensorRT on cuda-10.0 image.

**Comment by jywu-msft** [comment]
@stevenlix, FYI.

**Comment by xonobo** [comment]
According to this [note](https://github.com/microsoft/onnxruntime/issues/1452#issuecomment-513851172), I expect onnxruntime to handle opset10 layers smoothly on GPU-CPU. Do you suggest any work arounds for int64 and gather with axis 0?

**Comment by jinfagang** [comment]
@xonobo  Do u have any thoughts on how to inference with SSd model? these models inside onnx official model zoo all can not inference through TensorRT.

such as fasterrcnn. maskrcnn, ssd etc........... with same error there

**Comment by Nioolek** [comment]
I also got this issue,did any one solve this problem
