### ISSUE TITLE
Runtime failure after QDQ quantization of model containing Slice operator

### ISSUE THREAD

**Issue by kristoftunner** [microsoft/onnxruntime#16815]
### Describe the issue

I was using Ultraface model from Model Zoo (https://github.com/onnx/models/tree/main/vision/body_analysis/ultraface) with [Microsoft Volterra machine](https://learn.microsoft.com/en-us/windows/arm/dev-kit/) that has a snapdragon SoC with NPU in it and tried to work with QNN backend using that NPU. For that I quantized the model with qdq static quantization, but I have this exception for the Slice operations in the model: 
`This is an invalid model. In Node, ("Slice_0", Slice, "", -1) : ("460_DequantizeLinear_Output": tensor(float),) -> ("462": tensor(float),) , Error Node (Slice_0) has input size 1 not in range [min=3, max=5].`

### To reproduce

Quantize the model and try to use it on the Volterra machine with QNN backend.

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

2735e0d031b80b66b3d90d0580a14e2e2058da23

### ONNX Runtime API

C++

### Architecture

ARM64

### Execution Provider

Other / Unknown

### Execution Provider Library Version

QNN SDK v2.8.0

**Comment by xadupre** [comment]
It looks like an issue with the model opset. Could you check the opset version before and after quantization? A quantized model was uploaded 2 weeks ago.

**Comment by yufenglee** [comment]
Quantization tool supports opset >=10. It upgrades model for opset <10 but doesn't guarantee it will work. There should be a warning on this.

**Comment by kristoftunner** [comment]
Thx for the help, I will close this issue
