### ISSUE TITLE
Support for Winograd Conv with MKLDNN

### ISSUE THREAD

**Issue by peterjc123** [microsoft/onnxruntime#1683]
**Describe the bug**

I tried to replace `mkldnn::convolution_direct` with `mkldnn::convolution_winograd` in `onnxruntime/core/providers/mkldnn/nn/conv.cc` and `onnxruntime/core/providers/mkldnn/subgraph/mkldnn_conv.h`. But then an error is thrown during runtime: `could not create primitive descriptor iterator`.
I also tried setting the value to `mkldnn::convolution_auto` but even if I forced all the occurences of `is_winograd_faster_than_direct` to be `true` in MKL-DNN, it wasn't used because it did't appear in the log when I specify `MKLDNN_VERBOSE=2`.

**Comment by jywu-msft** [comment]
@sreekanth-yalachigere , any ideas?

**Comment by peterjc123** [comment]
@sreekanth-yalachigere Yes, I tested all the convs generated by `mkldnn-verbose=1` with benchdnn and found out that there is one layer that doesn't fit in the size requirements.

**Comment by peterjc123** [comment]
After adding some if conditions before applying the Winograd algorithm, I managed to run the whole graph. But now the problem is that the runtime performance is not so good. My graph has dynamic input dimensions so the computation graph will be constructed every time I feed in new input. At the same time, the weights are transformed into the Winograd format multiple times, too. How can I reuse the weights and avoid these reshaping?

**Comment by peterjc123** [comment]
Actually, when I tried something like VGG16 in the ONNX model zoo, it crashed with the message `Segementation fault (core dumped)`. My changes in the code are available here: https://github.com/microsoft/onnxruntime/compare/master...peterjc123:winograd Could you please take a look?

**Comment by peterjc123** [comment]
> We are already saving reordered [weights](https://github.com/microsoft/onnxruntime/blob/938200de9b800e436349ff64a57898d4139f932e/onnxruntime/core/providers/mkldnn/subgraph/mkldnn_conv.h#L382).

As for the performance of the model, looks like it is taking up much time in `wino_reshape` for the first run. The running time after that is much faster. Looks like you are correct.

**Comment by sreekanth-yalachigere** [comment]
@peterjc123, I've added Winograd support to my task list. I will update you soon. 
Thanks

**Comment by durson** [comment]
Hi all, what is the progress on this as a matter of fact quite important feature?
