### ISSUE TITLE
Run onnxruntime in wasm runtime

### ISSUE THREAD

**Issue by chris-void-777** [microsoft/onnxruntime#16857]
### Discussed in https://github.com/microsoft/onnxruntime/discussions/16849

<div type='discussions-op-text'>

<sup>Originally posted by **chris-void-777** July 26, 2023</sup>
After reading the ONNX Runtime documentation, I learned that ONNX Runtime can run in the browser and can interact with JavaScript.Now, I want to run ONNX Runtime within a WebAssembly runtime embedded in C++. How can I interact with the code inside ort-wasm.wasm? Specifically, I want to konw how the JavaScript API calls the code inside WebAssembly. So that  I can write code to achieve the implementation I desire.
I have inspected the export section of ort-wasm.wasm:
```
wasm-tools print ort-wasm.wasm | grep export | head
  (export "N" (memory 0))
  (export "O" (func 2856))
  (export "P" (func 7114))
  (export "Q" (func 7343))
  (export "R" (func 7913))
  (export "S" (func 8130))
  (export "T" (func 8178))
  (export "U" (func 6918))
  (export "V" (func 7978))
  (export "W" (func 7005))
 ...
```
I don't know which functions to call.

Thanks for your time and assistance.

 </div>

**Comment by xadupre** [comment]
You should find some useful information on this page: https://onnxruntime.ai/docs/tutorials/web/.

**Comment by chris-void-777** [comment]
> You should find some useful information on this page: https://onnxruntime.ai/docs/tutorials/web/.

First of all, thank you for your response. I hava read this page but did not find the information I was looking 
for. Perheps it's beacause I didn't express my self clearly. If using the image below to illustrate, I want to understand how the JavaScript API interacts with Wasm to write my own code to achieve the following: embed WasmEdge into my c++ project, where the native layer(black year) uses the Wasmedge runtime, and the Wasm layer utilizes the Wasm(ort-wasm.wasm) compiled from the Onnxruntime project. Then, I aim to interact with this Wasm in C++ and call the Onnxruntime APIs.

![Figure](https://github.com/microsoft/onnxruntime/assets/42626462/807cea44-3c8e-46b0-975b-29b5778da543)

**Comment by chris-void-777** [comment]
> You should find some useful information on this page: https://onnxruntime.ai/docs/tutorials/web/.

I'm very sorry, I didn't see your response in the discussion earlier. 

> I assume you read this page https://onnxruntime.ai/docs/tutorials/web/ but you did not find the information you need. Otherwise, the code you are looking for should be here: https://github.com/microsoft/onnxruntime/tree/main/js/web.
This is what I wanted, thank you.
