### ISSUE TITLE
[Performance] How can I forcefully assign nodes to DML EP

### ISSUE THREAD

**Issue by han-minhee** [microsoft/onnxruntime#16863]
### Describe the issue

I have a model with shape related operators including "Reshape" and trying to run it using Dml EP, with .Net.
When the session is run, it gives the warning:

> [W:onnxruntime:, session_state.cc:1169 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.

When I add the CPU EP, the warning is gone, but I can see that the ops are run on CPU and the copy to host takes too much time in the performance profile. I want to see the performance when the nodes are assigned to DML EP. Would it be possible?

### To reproduce

I'm using a model from:
https://huggingface.co/JunkyByte/easy_ViTPose/tree/main

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

DirectML

### Is this a quantized model?

No

**Comment by xadupre** [comment]
There are more than one onnx model in the linked repository, which one did you try?

**Comment by han-minhee** [comment]
> There are more than one onnx model in the linked repository, which one did you try?
https://huggingface.co/JunkyByte/easy_ViTPose/blob/main/onnx/vitpose-25-b.onnx
I using this one right now

**Comment by fdwr** [comment]
> When I add the CPU EP ... copy to host takes too much time in the performance profile

- Do you add the CPU EP before the DML EP? The EP's are in priority order, and so ORT will try to assign a node to the DML EP first if the DML EP is added first. Note, the CPU EP is *implicitly* anyway added even if you don't explicitly add it (after the DML EP).
- Were you able to see which nodes are assigned to the CPU EP if you run with ORT_LOGGING_LEVEL_VERBOSE?

**Comment by nums11** [comment]
Closing as stale.
