### ISSUE TITLE
Unable to build onnxruntime v1.9.0 for C++ from source

### ISSUE THREAD

**Issue by ElisonSherton** [microsoft/onnxruntime#16864]
### Describe the issue

I am trying to build onnx from the official onnxruntime repo on my VM. 

**Steps that I followed**
1. Cloned [this repo](https://github.com/microsoft/onnxruntime)
2. change directory to this cloned repo i.e. `cd onnxruntime`
3. Modified the version in the `VERSION_NUMBER` file from `1.16.0` to `1.9.0`
4. Ran the build command with AVX flags set to be on. Output as follows
```shell
/build.sh --config RelWithDebInfo --parallel --cmake_extra_defines onnxruntime_USE_AVX=ON onnxruntime_USE_AVX2=ON onnxruntime_USE_AVX512=ON
``` 

However when I run this shell script, Cmake starts creating makefiles for version 1.14.0; why would this be? Also it doesn't run to completion, the compilation stops at 59% as the python process running this code i.e. build.py exists with status code 2

### Urgency

It would be great to have a quick resolution since I have a project submission deadline due in 2 weeks time.

### Target platform

Ubuntu 20.04.6 LTS (Focal Fossa)

### Build script

Followed the instructions [provided here](https://onnxruntime.ai/docs/build/inferencing.html#build-instructions) to do the same. Command used was as follows

```shell
/build.sh --config RelWithDebInfo --parallel --cmake_extra_defines onnxruntime_USE_AVX=ON onnxruntime_USE_AVX2=ON onnxruntime_USE_AVX512=ON
```

### Error / output

The complete debug log is pretty big. 

[Gistified it here](https://gist.github.com/ElisonSherton/f6f626e96a51b280be057ec192d4731e#file-build_log-sh)

Kindly look at [line number 561](https://gist.github.com/ElisonSherton/f6f626e96a51b280be057ec192d4731e#file-build_log-sh-L549) in the above gist. It is picking up the version of ORT to be 1.14.0 on it's own.

Thanks & Regards,
Vinayak Nayak.

### Visual Studio Version

1.80.1

### GCC / Compiler Version

9.4.0

**Comment by xadupre** [comment]
You need to checkout the sources for this specific version: https://github.com/microsoft/onnxruntime/tree/v1.9.0 or download the source from the release page.

**Comment by snnn** [comment]
You mean
```
 --   ONNX version              : 1.14.0
```
?

After switching to different branch, you need to run:
```
git submodule sync
git submodule update --init --recursive.
```

**Comment by ElisonSherton** [comment]
Thanks, was able to build it with this fix provided above.
