### ISSUE TITLE
Shape inference fails in per channel quantize model

### ISSUE THREAD

**Issue by take-cheeze** [microsoft/onnxruntime#1689]
**Describe the bug**
In the scale back of the ConvInteger/MatMulInteger with per channel quantization by the [quantization script](https://github.com/microsoft/onnxruntime/blob/5873bdbb3f66fb761e4846893579c803b608eba2/onnxruntime/python/tools/quantization/quantize.py) shape inference fails.
Seems shape of `scales_mul_op_output` can't be broadcasted in element wise multiplication to output of the quantized operator output in per channel quantization since it's shape is (C,).
It needs to be reshaped before `Mul` to `(C, 1, 1)` (in normal image Conv).

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.10
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 0.5
- Python version: 3.7.3
- CUDA/cuDNN version:10.1/7.5.0
- GPU model and memory: RTX 2060

**To Reproduce**
By using tool scripts in chainer-compiler I get the following shape inference error
https://github.com/pfnet-research/chainer-compiler/blob/f5f3d8726e313e87d9a58c71e6f3c814418048ab/utils/quantize.sh
https://github.com/pfnet-research/chainer-compiler/blob/f5f3d8726e313e87d9a58c71e6f3c814418048ab/scripts/quantize_model.py
https://github.com/pfnet-research/chainer-compiler/blob/f5f3d8726e313e87d9a58c71e6f3c814418048ab/utils/run_onnx_onnxruntime.py
```bash
~/dev/chainer-compiler$ ./utils/quantize.sh ./data/mnist/model.onnx ./data/mnist/q_model.onnx && python ./utils/run_onnx_onnxruntime.py --model_file q_model.onnx ./data/mnist
Quantize config: {'nbits': 8, 'quantization_mode': 0, 'static': False, 'asymmetric_input_types': False, 'input_quantization_params': None, 'output_quantization_params': None, 'per_channel': True}
Saving "./data/mnist/model.onnx" to "./data/mnist/q_model.onnx"
Traceback (most recent call last):
  File "./utils/run_onnx_onnxruntime.py", line 116, in <module>
    main()
  File "./utils/run_onnx_onnxruntime.py", line 112, in main
    run(args)
  File "./utils/run_onnx_onnxruntime.py", line 76, in run
    sess = rt.InferenceSession(onnx_filename)
  File "/home/takeshi/.pyenv/versions/3.7.3/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 29, in __init__
    self._sess.load_model(path_or_bytes)
RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from ./data/mnist/q_model.onnx failed:[ShapeInferenceError] Incompatible dimensions
```

**Expected behavior**
Quantized model's shape inference shouldn't fail.

**Screenshots**

**Additional context**
Fixed in chainer-compiler quantizer port by reshaping the scales: https://github.com/pfnet-research/chainer-compiler/pull/613

**Comment by ggeor84** [comment]
@askhade @faxu has per_channel quantization been added or not yet? per_channel quantization is great to boost accuracy, so I was curious to see if there are plans to support it.
