### ISSUE TITLE
Regression for If operator in opset version 19

### ISSUE THREAD

**Issue by cbourjau** [microsoft/onnxruntime#16904]
### Describe the issue

The `If` operator appears to have a regression in opset 19. I attached two models, one for opset version 18 the other for
 opset version 19. `onnxruntime` 1.15.1 fails to create an `InferenceSession` for the latter with the following error message:
 ```
 onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for If(19) node with name 'If_0'
 ```

 It worked as expected for opset version 18.

The issue has been observed on MacOS and Linux.

[models.zip](https://github.com/microsoft/onnxruntime/files/12196600/models.zip)

### To reproduce

Test cases for the regression (using [Spox](https://github.com/Quantco/spox)):
```python
from spox import argument, build, Tensor
import onnx
import onnxruntime as ort
import numpy as np

def test_regression_opset_19():
    import spox.opset.ai.onnx.v19 as op19

    a = argument(Tensor(np.float32, ("N", 1)))
    (c,) = op19.if_(op19.const(True), then_branch=lambda: [a], else_branch=lambda: [a])
    model = build(inputs={"a": a}, outputs={"c": c})

    onnx.save_model(model, "regression_if_opset_19.onnx")

    ort.InferenceSession(model.SerializeToString())  # Fails


def test_opset_18():
    import spox.opset.ai.onnx.v18 as op18

    a = argument(Tensor(np.float32, ("N", 1)))
    (c,) = op18.if_(op18.const(True), then_branch=lambda: [a], else_branch=lambda: [a])
    model = build(inputs={"a": a}, outputs={"c": c})

    onnx.save_model(model, "if_opset_18.onnx")

    ort.InferenceSession(model.SerializeToString())  # Works as expected

```

### Urgency

This bug makes it impossible to use a model with the current opset and an `If` node in the current release of `onnxruntime`. 

### Platform

Mac

### OS Version

12.3.1

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by snnn** [comment]
This is why this document exists: https://github.com/microsoft/onnxruntime/blob/rel-1.15.1/docs/OperatorKernels.md ...
Try the latest code.
The support will be added in next release.

**Comment by cbourjau** [comment]
Sorry, it is unclear to me what I should see in that document. If I read it correctly, it states that `If` is supported for version `16+` with the currently released version and the types that I am using. 

I have now realized that `onnxruntime` does not support opset version 19 at all, yet, but IMHO neither the linked document nor the error message make that fact obvious.

**Comment by snnn** [comment]
You are right. The "16+" is actually very misleading. It should not have the plus sign.  For example, now the opset 20 is not released yet, the if operator in opset20 could be anything. Any part of it could be changed, except the name. It's like: after a reincarnation, who will be I? nobody knows. Therefore, an onnx runtime release cannot claim it will support an opset that is not known at the time when the onnx runtime version is released.  See this comment: https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/framework/kernel_registry.cc#L128 In ONNX Runtime's source, when a kernel is registered, either it is registered to a specific version, or it is registered to a version range but the right side of the range cannot be open ended.

**Comment by snnn** [comment]
So, the document says the If operator is implemented for opset: [1, 10] and [11, 12] a nd [13, 15] and 16+ , so actually it means [1,16].
