### ISSUE TITLE
[Python Interface] How to dump every node shape info.(including input and output )

### ISSUE THREAD

**Issue by xqch1983** [microsoft/onnxruntime#1691]
what options should I set in Python enviroment if i want to dump every node input and output shape informantions? thanks.

**Comment by jywu-msft** [comment]
With https://github.com/microsoft/onnxruntime/pull/1202 , you need to enable it by building from source. It just writes the shape info to stdout so it should work from python as well.
e.g. in Linux env, build python wheel using build.sh (build.bat in Windows)
./build.sh --config Release --cmake_extra_defines onnxruntime_DEBUG_NODE_INPUTS_OUTPUTS=ON --build_wheel --update --build

**Comment by faxu** [comment]
@xqch1983 does this answer your question?

**Comment by dashesy** [comment]
Is this build option tested?
I get this error:

 
```text
/home/ehazar/repos/onnxruntime/onnxruntime/core/framework/utils.cc: In instantiation of ‘void onnxruntime::utils::DumpTensor(const onnxruntime::Tensor&, const onnxruntime::TensorShape&) [with T = int]’:
/home/ehazar/repos/onnxruntime/onnxruntime/core/framework/utils.cc:638:13:   required from here
/home/ehazar/repos/onnxruntime/onnxruntime/core/framework/utils.cc:566:25: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   for (int row = 0; row < num_rows; ++row) {
```

**Comment by jywu-msft** [comment]
@skottmckay fyi

**Comment by skottmckay** [comment]
It's a rarely used feature which is tested on Windows and currently builds without error. It adds a huge amount of overhead so most likely will never be tested via a CI build. 

What environment are you building in? std::is_floating_point_v is somewhat new and we recently downgraded to C++11 which may not have that feature. I can update the code to use std::is_floating_point<T>::value instead if that helps.
