### ISSUE TITLE
Tag ORT server images with version_number

### ISSUE THREAD

**Issue by rakelkar** [microsoft/onnxruntime#1696]
**Is your feature request related to a problem? Please describe.**
Users of KFServing would like to refer to a well-known runtime version. However this is not possible as the current integration has no way of pointing to a version other than "latest"
https://github.com/kubeflow/kfserving/pull/258

**Describe the solution you'd like**
CI builds should tag ORT server containers pushed to mcr.microsoft.com with ORT version using the VERSION_NUMBER file 

```
VERSION_NUMBER=$(cat $SOURCE_ROOT/VERSION_NUMBER)
````

**Comment by vinitra** [comment]
Hi @rakelkar! The onnxruntime server docker image has been refreshed on MCR. You can now pull the following images:

`mcr.microsoft.com/onnxruntime/server:v0.4.0`
`mcr.microsoft.com/onnxruntime/server:v0.5.0`

and the latest image, which currently points to v0.5.0.

`mcr.microsoft.com/onnxruntime/server:latest`

**Comment by rakelkar** [comment]
Awesome thanks!
