### ISSUE TITLE
[Documentation]  The version of CUDA and other libraries for onnxruntime1.15.1

### ISSUE THREAD

**Issue by developer0hye** [microsoft/onnxruntime#16967]
### Describe the documentation issue

It seems that we need to write a version of CUDA and other libraries for version 1.15.1.

![image](https://github.com/microsoft/onnxruntime/assets/35001605/b2fdadda-f3b8-42d0-b946-c4077ef82729)

### Page / URL

https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements

**Comment by snnn** [comment]
Thanks. I will add it.
