### ISSUE TITLE
[Build] Windows 11 : No CUDA toolset found

### ISSUE THREAD

**Issue by davesworking** [microsoft/onnxruntime#16973]
### Describe the issue

Build is working on Linux for CPU/GPU.

Windows build: **No CUDA toolset found**.

Cuda/Cudnn is extracted to C:\Build\Windows-x86-64\GPU\Cuda and C:\Build\Windows-x86-64\GPU\Cudnn

**...\Cuda**
bin
compute-sanitizer
extras
include
lib
libnvvp
nvml
nvvm
src
tools

**...\Cudnn**
bin
include
lib

### Target platform

Windows

### Build script

```
set cuda_dir=c:\Build\Cuda
set cudnn_dir=c:\Build\Cudnn

cmake ^
...
 -Donnxruntime_USE_CUDA=ON ^
 -Donnxruntime_CUDA_HOME=%cuda_dir% ^
 -Donnxruntime_CUDNN_HOME=%cudnn_dir% ^ 
 -DCMAKE_CUDA_ARCHITECTURES="37-real;50-real;60-real;70-real;80-real;80-virtual" ^
 -DCMAKE_CUDA_COMPILER=%cuda_dir%\bin\nvcc.exe ^
 -DCUDA_CUDA_LIBRARY=%cuda_dir%\lib\x64 ^
...
```

### Error / output

CMake Error at C:/Build/Windows-x86-64/GPU/cmake-3.26.5/Modules/CMakeDetermineCompilerId.cmake:501 (message):
  No CUDA toolset found.
Call Stack (most recent call first):
  C:/Build/Windows-x86-64/GPU/cmake-3.26.5/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  C:/Build/Windows-x86-64/GPU/cmake-3.26.5/Modules/CMakeDetermineCompilerId.cmake:53 (__determine_compiler_id_test)
  C:/Build/Windows-x86-64/GPU/cmake-3.26.5/Modules/CMakeDetermineCUDACompiler.cmake:307 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:620 (enable_language)

### Visual Studio Version

2022

**Comment by snnn** [comment]
Read this: https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_TOOLSET.html

Specify toolset when invoking cmake and configure cuda there.
