### ISSUE TITLE
[Feature Request] Support CoreML EP usage via the Python API

### ISSUE THREAD

**Issue by vladiliescu** [microsoft/onnxruntime#16989]
### Describe the feature request

- Currently, the CoreML EP is only usable via the C or C++ APIs as per [the docs](https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html#usage).
- This means that users running the Python API on a Mac Silicon can either run the models on CPU, or rely on a runtime version built by a third party (https://pypi.org/project/onnxruntime-silicon/). 
- Running on CPU is slow, while relying on a third party can lead to issues (see the mismatch b/w versions `1.15.1` of the official runtime and `1.15` of the third party library)

Please add the CoreML EP to the official onnxruntime Python package.

### Describe scenario use case

Running ONNX models on a Mac Silicon using the CoreML Execution Provider.

**Comment by skottmckay** [comment]
@pranavsharma any objection to this?

**Comment by pranavsharma** [comment]
> @pranavsharma any objection to this?

No objections.

**Comment by bfan1256** [comment]
I am running this on an m1 mac and I am not seeing this as an available provider? Unless this has not been added in the latest runtime release?

**Comment by skottmckay** [comment]
Will be in the 1.17 release
