### ISSUE TITLE
Onnxruntime.dll not copied to build output directory when project is a class library

### ISSUE THREAD

**Issue by Zuhaib-SB** [microsoft/onnxruntime#1699]
Description: This issue occurs for me when trying to use the Microsoft.ML.Onnxruntime nuget package within a C# project, targeting .NET Framework 4.7.2 with the platform target set to x64. I'm using visual studio 2017.

When referencing Microsoft.Onnxruntime nuget package, if you try to build the project when it's output type is not an exe the onnxruntime.dll (native x64 library) file will not be copied to the build output directory. However if you set your project type as a console app it will be copied.

Urgency: Means an imported model cannot be used in a test project properly.

**System information**
- OS Platform and Distribution: Windows 10
- ONNX Runtime installed from (source or binary): Microsoft.ML.OnnxRuntime nuget package
- ONNX Runtime version: 0.4.0
- Visual Studio version (if applicable): Professional 2017 - 15.9.14

**To Reproduce**
Create a new project, set type as class library. Install Microsoft.ML.OnnxRuntime (version: 0.4.0) package. Build project. onnxruntime.dll will NOT be copied. 

Set output type as console app for the project. Build again. It will be copied.

**Expected behavior**
Expect the onnxruntime.dll to be copied to the build output directory even if the C# project type is a class library.

**Comment by jignparm** [comment]
Using VS2017 v 15.9.6 (community edition) , and the following:

* Microsoft.ML.OnnxRuntime  version 0.4.0
* Target set to **x64**, 
* Both .NET Framework **4.6.1** as well as **4.7.1** separately

I see that the  onnxruntime.dll native library gets copied to the output folder correctly, for both **class library** as well as **console application** output types.

Is there some other configuration that you may have that's causing this behavior?

![image](https://user-images.githubusercontent.com/13698702/63907284-b1ce2080-c9cf-11e9-9072-1c6bad9e8ef0.png)


![image](https://user-images.githubusercontent.com/13698702/63907392-1a1d0200-c9d0-11e9-8e27-13f5c1648c17.png)

**Comment by Zuhaib-SB** [comment]
Hi, another thing I didn't mention is that I'm using the new csproj format for this project. I used a migration tool convert from old project format to the new one. https://github.com/hvanbakel/CsprojToVs2017

the csproj format looks fairly standard.

The issue occurs when
<OutputType>Library</OutputType>

as opposed to:
<OutputType>Exe</OutputType>

**Comment by jignparm** [comment]
How did u generate the new csproj project file? If you're not using the one from visual studio, or manually edited the csproj, that can affect properties and their values in the project. Is there a reliable way to reproduce the error?

**Comment by Zuhaib-SB** [comment]
-> Create a new project. Choose "class library .net standard" to force VS to create the project in the new csproj format.

-> Edit the csproj. Set the "TargetFramework" xml attribute to "net472".

-> Install the Microsoft.ML.OnnxRuntime version 0.4.0

-> Check bin directory and there will be no onnxruntime.dll copied. Even if you set project target platform to x64

**Comment by Zuhaib-SB** [comment]
Any update on this?

**Comment by jignparm** [comment]
@Zuhaib-SB,

>-> Create a new project. Choose "class library .net standard" to force VS to create the project in the new csproj format.

I was able to reproduce the behavior. If you specify the RuntimeIdentifier as below in the project file, it will copy the onnxruntime.dll to the output folder.

From the verbose build system log debugging information, it seems like when the RID is missing (as seems to be the case of class libraries), the native DLLs copy list is not populated, hence the native onnxruntime.dll is not copied to the output folder. 

Setting the RID should resolve this. In case you are auto-generating the project files, you can set this an an environment variable as well.

__CSPROJ file__
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="0.5.0" />
  </ItemGroup>

</Project>
```
