### ISSUE TITLE
Random outputs in models only containing Cast -> AllToAll -> Cast

### ISSUE THREAD

**Issue by wschin** [microsoft/onnxruntime#16990]
### Describe the issue

In https://github.com/microsoft/onnxruntime/pull/16941, tests are modified to test AllGather and AllToAll for boolean tensors ([search for TODO to see which lines to uncomment to enable the failing case](https://github.com/microsoft/onnxruntime/blob/e6c9ed06066916d622df6a1b1bd415a4dbf829c3/onnxruntime/test/python/onnxruntime_test_collective.py#L230)). Several graph patterns are tried for tests. 
- Constant -> bool_tensor -> AllToAll -> bool_tensor -> Cast -> int64_tensor
- int64_tensor -> Cast -> bool_tensor -> AllToAll -> bool_tensor -> Cast -> int64_tensor

The second pattern always generate random results. My guess is that AllToAll needs to synchronize all GPUs before calling ncclSend and ncclRecv since AllGather doesn't hit this problem.

### To reproduce

Uncomment this line https://github.com/microsoft/onnxruntime/blob/e6c9ed06066916d622df6a1b1bd415a4dbf829c3/onnxruntime/test/python/onnxruntime_test_collective.py#L230 and run the test file using `mpiexec -n 4 python -m mpi4py onnxruntime_test_collective.py`

### Platform

Linux

### OS Version

20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

e6c9ed06066916d622df6a1b1bd415a4dbf829c3

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.8, NCCL 2.18

**Comment by shaahji** [comment]
Fixed by #17075
