### ISSUE TITLE
Run error with tensorrt + multi gpu

### ISSUE THREAD

**Issue by BobDLA** [microsoft/onnxruntime#17001]
### Describe the issue

when run on muti gpu 
* it's good for both **cuda, tensorrt** as provider,  when use the device **0** for inference, 
  trtOptions.device_id = 0;
* it's good for **cuda**, when use the device **1** 
* but's it's error when use tensorrt and device **1**
get error as below

2023-08-04 07:09:02.412143768 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running TRTKernel_graph_squeezenet_old_14539887041853260096_0 node. Name:'TensorrtExecutionProvider_TRTKernel_graph_squeezenet_old_14539887041853260096_0_0' Status Message: No requested allocator available
terminate called after throwing an instance of 'Ort::Exception'
  what():  Non-zero status code returned while running TRTKernel_graph_squeezenet_old_14539887041853260096_0 node. Name:'TensorrtExecutionProvider_TRTKernel_graph_squeezenet_old_14539887041853260096_0_0' Status Message: No requested allocator available
  
  

### To reproduce

1. Environment, build a docker refer below dockfile

```
FROM nvcr.io/nvidia/tensorrt:23.06-py3 AS builder
ARG ONNXRUNTIME_REPO=https://github.com/Microsoft/onnxruntime
ARG ONNXRUNTIME_BRANCH=main
ARG CMAKE_CUDA_ARCHITECTURES=37;50;52;60;61;70;75;80

RUN apt-get update &&\
    apt-get install -y sudo git bash unattended-upgrades
RUN unattended-upgrade

WORKDIR /code
ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:/code/cmake-3.26.3-linux-x86_64/bin:${PATH}

# Prepare onnxruntime repository & build onnxruntime with TensorRT
RUN git clone --single-branch --branch ${ONNXRUNTIME_BRANCH} --recursive ${ONNXRUNTIME_REPO} onnxruntime &&\
    /bin/sh onnxruntime/dockerfiles/scripts/install_common_deps.sh &&\
    trt_version=${TRT_VERSION:0:3} &&\
    /bin/sh onnxruntime/dockerfiles/scripts/checkout_submodules.sh ${trt_version} &&\
    cd onnxruntime &&\
    /bin/sh build.sh --allow_running_as_root --parallel --build_shared_lib --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ --use_tensorrt --tensorrt_home /usr/lib/x86_64-linux-gnu/ --config Release --build_wheel --skip_tests --skip_submodule_sync --cmake_extra_defines '"CMAKE_CUDA_ARCHITECTURES='${CMAKE_CUDA_ARCHITECTURES}'"' &&\
    pip install /code/onnxruntime/build/Linux/Release/dist/*.whl &&\
    mkdir -p /code/onnxruntime_lib/ &&\
    cd /code/onnxruntime/build/Linux/Release/ && make install DESTDIR=/code/onnxruntime_lib/

``` 

2. build below demo code to repeat the error
```c++
#include <vector>
#include <string>
#include <iostream>
#include <onnxruntime_cxx_api.h>

int main(int argc, const char *argv[])
{
  //print help if argc is not = 3
  if (argc != 4)
  {
    std::cout << "Usage: " << argv[0] << " gpuId useCuda useTensorrt" << std::endl;
    return 0;
  }

  //get the first param to int
  int gpuId = atoi(argv[1]);
  //get  the 2nd param for use cuda or not as bool
  bool useCuda = atoi(argv[2]);
  //get the 3rd param as use tensorrt or not as bool
  bool useTensorrt = atoi(argv[3]);



  Ort::Env env(ORT_LOGGING_LEVEL_VERBOSE);
  Ort::SessionOptions sessionOption;

  if (useTensorrt)
  {
  OrtTensorRTProviderOptions trtOptions{};
  trtOptions.device_id = gpuId;
  trtOptions.trt_force_sequential_engine_build = true;
    sessionOption.AppendExecutionProvider_TensorRT(trtOptions);
  }
  if(useCuda)
  {
        OrtCUDAProviderOptions opCuda{};
    opCuda.device_id = gpuId;

    sessionOption.AppendExecutionProvider_CUDA(opCuda);


  }



  std::string modelpath = "squeezenet.onnx";
  std::cout << "onnx phone init model path is " << modelpath << std::endl;

  Ort::Session session(env, modelpath.c_str(), sessionOption);


  std::vector<int64_t> inputNodeDims = {1, 3, 224, 224};

  std::vector<const char *> inputNodeNames;
  Ort::AllocatorWithDefaultOptions allocator;
  Ort::AllocatedStringPtr inputNodeName = session.GetInputNameAllocated(0, allocator);
  char *tempBuf = new char[50];
  strcpy(tempBuf, inputNodeName.get());
  std::cout << "get input name is " << tempBuf << std::endl;
  inputNodeNames.push_back(tempBuf);


  std::vector<const char *> outputNodeNames;
  size_t outputNodesNum = session.GetOutputCount();
  Ort::AllocatedStringPtr outputNodeName = session.GetOutputNameAllocated(0, allocator);
  char *tempBuf2 = new char[100];
  strcpy(tempBuf2, outputNodeName.get());
  std::cout << "get output name is " << tempBuf << std::endl;
  outputNodeNames.push_back(tempBuf2);
  float img [224*224*3*sizeof(float)];

  Ort::MemoryInfo memory("Cpu", OrtAllocatorType::OrtArenaAllocator, 0, OrtMemTypeDefault);

  Ort::Value inputTensor = Ort::Value::CreateTensor(memory, img,
                                                    3 * 224 * 224 * sizeof(float),
                                                    inputNodeDims.data(), inputNodeDims.size(),
                                                    ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT);
  auto options = Ort::RunOptions{nullptr};

  auto outputTensor = session.Run(options, inputNodeNames.data(), &inputTensor, 1, outputNodeNames.data(), outputNodeNames.size());

  std::cout<<"finish"<<std::endl;
  return 0;
}
``` 

3.  compile the code and run with different param on a multi gpu systm
./demo 0 0 1
will be good
./demo 1 1 0 
will be good
./demo 1 0 1
will throw error as above

### Urgency

it's urgent because the project has verified on single gpu system and wait for deploy on a multi gpu system, but meet this issue

### Platform

Linux

### OS Version

22.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.16.0

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

TensorRT

### Execution Provider Library Version

based on nvcr.io/nvidia/tensorrt:23.06-py3

**Comment by chilo-ms** [comment]
Thanks for raising this issue.
It seems we had a bug [here](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc#L2275) where device id is always 0. Will have a fix.

**Comment by chilo-ms** [comment]
https://github.com/microsoft/onnxruntime/pull/17036 should fix the issue.

**Comment by BobDLA** [comment]
> Thanks for raising this issue. It seems we had a bug [here](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc#L2275) where device id is always 0. Will have a fix.

Got it, thanks

**Comment by jax11235** [comment]
The bug is still there(1.16.3，1.17.0), is there a workaround?
