### ISSUE TITLE
[Build] error LNK2038: mismatch detected for 'RuntimeLibrary'

### ISSUE THREAD

**Issue by davesworking** [microsoft/onnxruntime#17004]
### Describe the issue

/MT or /MD both result in linker errors

### Target platform

Windows

### Build script

cmake -G"Visual Studio 17 2022" -T "cuda=%cuda_dir%" -A x64 ^
 -DCMAKE_INSTALL_PREFIX=%output_dir% ^
 -DCMAKE_BUILD_TYPE=Release ^
 -DCMAKE_SKIP_BUILD_RPATH=On ^
 -DCMAKE_C_FLAGS_RELEASE="-DNDEBUG /MD" ^
 -DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG /MD" ^
 -Donnxruntime_PREFER_SYSTEM_LIB=OFF ^
 -Donnxruntime_BUILD_SHARED_LIB=ON ^
 -Donnxruntime_USE_TELEMETRY=OFF ^
 -Donnxruntime_ENABLE_CPU_FP16_OPS=OFF ^
 -Donnxruntime_BUILD_UNIT_TESTS=OFF ^
 -Donnxruntime_USE_CUDA=ON ^
 -Donnxruntime_CUDA_HOME=%cuda_dir% ^
 -Donnxruntime_CUDNN_HOME=%cudnn_dir% ^
 -DCMAKE_CUDA_ARCHITECTURES="37-real;50-real;60-real;70-real;80-real;80-virtual" ^
 -DCMAKE_CUDA_COMPILER=%cuda_dir%\bin\nvcc.exe ^
 -DCUDA_CUDA_LIBRARY=%cuda_dir%\lib\x64 ^
 -DZLIB_DIR=%home_dir%ZLIB ^
 -DZLIB_INCLUDE_DIR=%home_dir%ZLIB ^
 -DZLIB_LIBRARY=%home_dir%ZLIB\zlib.lib ^
 %onnxruntime_dir%\cmake

cmake --build . --config Release --target install

### Error / output

libprotobuf-lite.lib(message_lite.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in dllmain.obj [C:\Build\Windows-x86-64\GPU\BuildDir\onnxruntime.vcxproj]

### Visual Studio Version

2022

**Comment by mjay2016** [comment]
similar issue.

**Comment by snnn** [comment]
ONNX Runtime's build system is based on CMake, and CMake doesn't know how the preinstalled libraries were built. For example, it finds libprotobuf.lib, but cmake has no way to know whether it was built in Debug mode or Release Mode, whether it was linked to static CRT or dynamic. You have to tell this information to cmake by setting cmake variables like Protobuf_USE_STATIC_LIBS. Therefore, if the preinstalled libs work, they work. If not, you can avoid this trouble by uninstalling them.

**Comment by genbattle** [comment]
I'm getting this issue when building ONNX Runtime on Github's Windows Actions Runners from what's been said so far it sounds like it could be due to a conflicting natively installed copy of protobuf, which we can't easily remove from the runners. This seemed to work fine with ONNX Runtime v1.12.1, the previous version we were using. Presumably something has changed in the build system, maybe link path ordering?

**Comment by genbattle** [comment]
I'm able to repro this even on my dev machine when building v1.15.1, but had no such issue with v1.12.1.

**Comment by genbattle** [comment]
From what I've gathered so far, building ONNX runtime using `BUILD_SHARED_LIB=ON` seems to be what triggers this linking issue for me. Here's how I'm invoking the ONNX Runtime build:
```python
subprocess.run(
    [
        cmake_path,
        '-DCMAKE_BUILD_TYPE=Release',
        '-DCMAKE_INSTALL_PREFIX=dist',
        '-Donnxruntime_BUILD_SHARED_LIB=ON',
        '-Donnxruntime_DISABLE_EXCEPTIONS=ON',
        '-Donnxruntime_BUILD_UNIT_TESTS=OFF',
        '-Donnxruntime_DISABLE_RTTI=ON',
        f'-DPython_EXECUTABLE={sys.executable}',
        f'-DPYTHON_EXECUTABLE={sys.executable}',
        '../onnxruntime/cmake'],
    check=True)
subprocess.run([cmake_path, '--build', '.', '--config=Release', f'--parallel={num_jobs}', '--target=install'], check=True)
```

**Comment by davesworking** [comment]
Same here. If I set `-Donnxruntime_BUILD_SHARED_LIB=OFF` then it will build.

**Comment by snnn** [comment]
Sorry we don't support BUILD_SHARED_LIB. I think the cmake variable is terrible idea. There should be a way to provide lower granularity control instead of building every component into a shared library. Not every library supports dynamic linking.

**Comment by snnn** [comment]
In most of cases, you can set FETCHCONTENT_TRY_FIND_PACKAGE_MODE to never to bypass such issues. 

And if you invoke cmake directly instead of using our build.py, you need to manually setup some important cmake variables. For example, set CMAKE_MSVC_RUNTIME_LIBRARY to `MultiThreaded$<$<CONFIG:Debug>:Debug>`. You can find more details in https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/build.py .

**Comment by snnn** [comment]
Feel free to create a new issue if you have tried the above solutions but it still didn't work.

**Comment by matteosal** [comment]
> In most of cases, you can set FETCHCONTENT_TRY_FIND_PACKAGE_MODE to never to bypass such issues.
> 
> And if you invoke cmake directly instead of using our build.py, you need to manually setup some important cmake variables. For example, set CMAKE_MSVC_RUNTIME_LIBRARY to `MultiThreaded$<$<CONFIG:Debug>:Debug>`. You can find more details in https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/build.py .

Following this suggestion I have managed to produce a shared library build that links statically to the MSVC runtime using these settings:
```
 -DCMAKE_C_FLAGS_RELEASE="/MT -DNDEBUG -DORT_DLL_IMPORT" ^
 -DCMAKE_CXX_FLAGS_RELEASE="/MT -DNDEBUG -DORT_DLL_IMPORT" ^
 -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreaded$<$<CONFIG:Debug>:Debug>" ^
 -Donnxruntime_BUILD_SHARED_LIB=ON ^
 -DONNX_USE_MSVC_STATIC_RUNTIME=ON ^
 -Dprotobuf_MSVC_STATIC_RUNTIME=ON ^
```
My understanding is that linking to the MSVC runtime has to be consistent between ONNXRuntime and its ONNX and Protobuf dependencies. `/MT` sets static linking to it , hence `ONNX_USE_MSVC_STATIC_RUNTIME` and `protobuf_MSVC_STATIC_RUNTIME` should both be on
