### ISSUE TITLE
Add support for Less in GNMT

### ISSUE THREAD

**Issue by RanACohen** [microsoft/onnxruntime#1700]
When I use GNMT from https://drive.google.com/drive/folders/1cWYUg1V1FFgFo8dF-W0hR2tyezCzY_UV

I get: 
runtimeError: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Less(9)

**Comment by RanACohen** [comment]
I am using the latest master from today: commit f25847bccde222eacc3a5f8d515997d01631a428

**Comment by RanACohen** [comment]
This is for float64 input, I will create a MR for this. 
I implemented it locally.

**Comment by RanACohen** [comment]
@snnn How do I create a MR? I don't seem to have permission

**Comment by RanACohen** [comment]
this model have double (float 64)
just added Less with double support.

**Comment by RanACohen** [comment]
@neginraoof In the GNMT I posted in the drive link above (made by NVidia I think) there is a casting to float64 (double) and then Less.

**Comment by snnn** [comment]
Where did you get the model? How did you convert it? Is it the same one in mlperf https://github.com/mlperf/inference ?

Welcome to submit your change. I can help review.

**Comment by RanACohen** [comment]
@snnn same source as in https://github.com/microsoft/onnxruntime/issues/1583

**Comment by RanACohen** [comment]
@snnn Thank you Sun, please review https://github.com/microsoft/onnxruntime/pull/1722

**Comment by neginraoof** [comment]
@RanACohen The onnx model you are trying to run in the Google Drive is created by me. This is the onnx model exported from a fork of GNMT model as a workaround. Now that 'int64' is supported for 'Less' op, you should be able to run the model with no issues. I exported the onnx model from GNMT master branch and uploaded it again. You can try running that one. There's no need to use double for 'Less' op in this model. Sorry if the onnx model confused you.

**Comment by RanACohen** [comment]
@neginraoof Thanks a lot! Does not hurt to extend the runtime with Less(double) in any case 😃 
I will use the updated one.
