### ISSUE TITLE
[Performance] Slowdown from multiple inference sessions in serial. 

### ISSUE THREAD

**Issue by cyrusbehr** [microsoft/onnxruntime#17011]
### Describe the issue

I am running multiple models as part of a pipeline (first head orientation detection, then face detection, and finally face recognition). I create a `Ort::Session` for each one of my models. 

If I benchmark each of the models alone, then I get the following inference latency:
```
Average time head orientation detection: 35.28ms 
Average time face detection: 6.8 ms
Average time face recognition: 32.25 ms
```

However, in a real deployment, the models need to be run in serial, first the head orientation detection model, then the face detection model, and finally the output passed to the face recognition model. This pipeline is repeated for every input. 

If I then benchmark the models running in serial in a loop, I get the following total latency.
```
Average time head orientation detection + face detection + recognition: 160.825 ms
```

I would expect the total latency to be a combination of head orientation latency + face detection latency + face recognition latency ~ 77 ms (allowing for some increase in latency due to less efficient caching). However, the actual combined latency is significantly more than what I'm expecting. 

Why is the actual combined latency so much higher? I think it has to do with threading. 
I am using the following options sessions:

```
m_sessionOptsPtr->SetIntraOpNumThreads(8);
m_sessionOptsPtr->SetInterOpNumThreads(8);

m_sessionOptsPtr->SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);

m_sessionOptsPtr->AddConfigEntry(kOrtSessionOptionsConfigSetDenormalAsZero, "1"); // See this issue: https://github.com/microsoft/onnxruntime/issues/15630

```

What I have noticed is that each session, when running inference, uses up the 8 threads as expected. However, I'd expect the threads to be released once inference is complete so that the threads can be used by the next session which is to run inference in the pipeline. 

Instead, it appears that each session is holding on to their threads in their threadpool (even when not actually running inference), and it is saturating my entire CPU (even though there is only one session running inference at a time). How do I resolve this issue? Is there some way I can get the threads to be released after inference is complete? 

![image](https://github.com/microsoft/onnxruntime/assets/17056751/1f606d5b-20c6-4aac-a019-eedb3b958942)
Since I'm running inference in serial, I'd expect the CPU usage to remain at 800% since each session only can use 8 threads and there is only 1 session running inference at a time. The above image shows what is actually happening. 

Benchmarks run on i9 11th gen (16 cores)

### To reproduce

Create multiple inference sessions and benchmark separately, and then benchmark in serial

### Urgency

Somewhat more urgent. In use as part of commercial product. 

### Platform

Linux

### OS Version

Ubuntu 20.04.5 LTS

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

v1.15.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

### Is this a quantized model?

No

**Comment by cyrusbehr** [comment]
I set the following:

```
    m_sessionOptsPtr->AddConfigEntry(kOrtSessionOptionsConfigAllowInterOpSpinning, "0");
    m_sessionOptsPtr->AddConfigEntry(kOrtSessionOptionsConfigAllowIntraOpSpinning, "0");
```

And it has reduced the total combined inference time from 160 ms to 101 ms 

Is setting these options the correct solution? Or is there something better I should be doing (ex. global thread pool). 

I tried reading the docs for these options, but am a little confused by what thread spinning is.

**Comment by RyanUnderhill** [comment]
Thread spinning is just using spinlocks to wait for work on the thread pool:: https://en.wikipedia.org/wiki/Spinlock they can reduce thread latency in some cases but if you're not keeping the threads busy with work then they will tie up resources instead.

It sounds like you have one thread per model? In that case the spinlocks are probably counter productive as each session is optimizing for a continuous stream of work and stealing CPU time from the other threads, though the difference you show is a bit excessive.

**Comment by cyrusbehr** [comment]
Ok, so from your description does sound like the spinlocks are the issues here.

As explained in my description, I allow each session to use 8 threads for inference. 
The main application itself only uses a single thread to drive the inference (runs face orientation detection, face detection, face recognition, repeat...).

**Comment by cyrusbehr** [comment]
Performance seems to be variable, and not constant. 
@snnn what is the best configuration for running multiple sessions in serial, like described above?

**Comment by RyanUnderhill** [comment]
Hopefully snnn will have more insights, but this could be a bug if the thread pool is spinning and starving the next run call from scheduling more work for that same thread pool. I'm curious if anything changes if you change the # of threads used. Is that CPU 16 physical cores, or 8 physical + 8 hyperthreaded?

**Comment by pranavsharma** [comment]
@cyrusbehr Each session creates its own threadpool. When you benchmarked the models all by themselves (i.e.  created a session for model 1, ran the test, destructed the session, then created another session for model 2, etc...), there was only one threadpool in memory at any point of time. In the second experiment you've 3 session objects in memory all the time, which means 3 threadpools each containing N threads where N = # of physical cores. This is a huge waste if each session is exercised sequentially (meaning only one session is running at any point of time) and you're not pipelining the execution of your requests. In this scenario, your best bet is to use a global threadpool of N threads (available only via C/C++ APIs) and register that with the ORT environment so that only 1 threadpool exists for all the sessions. This is documented here https://onnxruntime.ai/docs/get-started/with-c.html. Let me know how this goes.

**Comment by cyrusbehr** [comment]
Thank you for your response @pranavsharma 

> and you're not pipelining the execution of your requests.

Can you explain what this would look like? All the models should be run in parallel, with the output of one being queued as the input to the next? What if we have 8 or so models in the pipeline? Unless we have a CPU with a massive number of cores, I don't imagine this would be very efficient, unless of course we limit each session to using 1-2 threads.

> This is documented here https://onnxruntime.ai/docs/get-started/with-c.html. Let me know how this goes.

The only information I see on the page you linked is this, which to be honest isn't incredibly helpful.
![image](https://github.com/microsoft/onnxruntime/assets/17056751/c8805f53-6463-435b-83b3-dae7ca372684)


Are you able to point me to a C++ working example please?

**Comment by pranavsharma** [comment]
Files in this folder have a full working example: https://github.com/microsoft/onnxruntime/tree/cf19c3697d126982acf45c040729269e53b5d9f4/onnxruntime/test/global_thread_pools.

**Comment by cyrusbehr** [comment]
Great thank you for sharing. Can you also answer my first question? If running inference on sessions in sequence is highly inefficient, what is a preferred design when there are multiple models for which inference needs to be run on a single device?

**Comment by pranavsharma** [comment]
You can do it in a couple of ways.
1. Use multiple sessions but 1 global threadpool shared by all the sessions. This assumes only one request is being inferenced at any point of time.
2. If you're doing pipelining, you may create multiple sessions each with its own threadpool but ensure that all threads are assigned to different cores (via thread affinity). This requires configuring each session appropriately.
3. If combining all the models in one big model works for your use case, then you can get by with just one session.

**Comment by cyrusbehr** [comment]
Thanks for all the info. I'm going to run some experiments with a global threadpool and see if that works better for my use case. Once I have confirmed this, I will close the issue.

**Comment by cyrusbehr** [comment]
Hi @pranavsharma I implemented a global thread pool and confirmed it works better for the sequential inference use case. For anyone else visiting this thread wondering how it can be done: 

```c++

#include <iostream>
#include "onnxruntime_cxx_api.h"
#include <memory>
#include <opencv2/opencv.hpp>
#include "onnxruntime_session_options_config_keys.h"

// Stopwatch Utility
template <typename Clock = std::chrono::high_resolution_clock>
class Stopwatch
{
    typename Clock::time_point start_point;
public:
    Stopwatch() :start_point(Clock::now()){}

    // Returns elapsed time
    template <typename Rep = typename Clock::duration::rep, typename Units = typename Clock::duration>
    Rep elapsedTime() const {
        std::atomic_thread_fence(std::memory_order_relaxed);
        auto counted_time = std::chrono::duration_cast<Units>(Clock::now() - start_point).count();
        std::atomic_thread_fence(std::memory_order_relaxed);
        return static_cast<Rep>(counted_time);
    }
};

using preciseStopwatch = Stopwatch<>;
using systemStopwatch = Stopwatch<std::chrono::system_clock>;
using monotonicStopwatch = Stopwatch<std::chrono::steady_clock>;

std::vector<float> hwcToChw(const cv::Mat& rgbImage, const std::array<float, 3>& subVals = {0.f, 0.f, 0.f},
                            const std::array<float, 3>& divVals = {1.f, 1.f, 1.f}, bool normalize = true) {
    float normFactor = 255.f;
    if (!normalize) {
        normFactor = 1.f;
    }
    std::vector<float> dataBuffer;
    dataBuffer.resize(rgbImage.cols * rgbImage.rows * rgbImage.channels());
    int insertIdx = 0;
    // hwc to chw conversion
    for (int c = 0; c < 3; ++c) {
        for (int i = 0; i < rgbImage.rows; ++i) {
            for (int j = 0; j < rgbImage.cols; ++j) {
                const auto retrievalIdx = (i * rgbImage.cols + j) * 3 + c;
                const auto transformIdx = retrievalIdx % 3;
                dataBuffer[insertIdx++] =  (static_cast<float>(rgbImage.data[retrievalIdx]) - (subVals[transformIdx] * normFactor)) / (divVals[transformIdx] * normFactor);

            }
        }
    }
    return dataBuffer;
}

class OnnxRunner {
public:
    OnnxRunner(const std::string& modelPath, int numThreads) {
        const OrtApi* g_ort = OrtGetApiBase()->GetApi(ORT_API_VERSION);
        OrtThreadingOptions* tp_options;
        g_ort->CreateThreadingOptions(&tp_options);
        g_ort->SetGlobalIntraOpNumThreads(tp_options, numThreads);
        g_ort->SetGlobalDenormalAsZero(tp_options);
        m_ortEnvPtr = std::make_unique<Ort::Env>(tp_options, ORT_LOGGING_LEVEL_WARNING, "Default");
        g_ort->ReleaseThreadingOptions(tp_options);

        Ort::SessionOptions session_options;
        session_options.DisablePerSessionThreads();
        m_sessionPtr = std::make_unique<Ort::Session>(*m_ortEnvPtr, modelPath.c_str(), session_options);

        Ort::AllocatorWithDefaultOptions allocator;
        m_numInputs = m_sessionPtr->GetInputCount();
        m_inputNodeNames.resize(m_numInputs);
        for (int i = 0; i < m_numInputs; ++i) {
            m_inputNodeNames[i] = strdup(m_sessionPtr->GetInputNameAllocated(i, allocator).get());
            auto typeInfo = m_sessionPtr->GetInputTypeInfo(i);
            auto tensorInfo = typeInfo.GetTensorTypeAndShapeInfo();
            auto inputDims = tensorInfo.GetShape();
            size_t tensorSize = 1;
            for (auto & inputDim : inputDims) {
                if (inputDim == -1) {
                    inputDim = 1;
                }
                tensorSize *= inputDim;
            }

            m_inputNodeDims.push_back(inputDims);
            m_inputTensorSize.push_back(tensorSize);
        }
        m_numOutputs = m_sessionPtr->GetOutputCount();
        m_outputNodeNames.resize(m_numOutputs);
        for (int i = 0; i < m_numOutputs; ++i) {
            m_outputNodeNames[i] = strdup(m_sessionPtr->GetOutputNameAllocated(i, allocator).get());
            auto outputTypeInfo = m_sessionPtr->GetOutputTypeInfo(i);
            auto outputTensorInfo = outputTypeInfo.GetTensorTypeAndShapeInfo();
            auto outputDims = outputTensorInfo.GetShape();
            m_outputNodeDims.push_back(outputDims);
        }
    }

    std::vector<Ort::Value> runInference(const cv::Mat& inputRGB) {
        std::vector<std::vector<float>> inputFloatTensors(1);
        std::vector<Ort::Value> inputTensors;

        auto floatArray = hwcToChw(inputRGB);
        inputFloatTensors[0] = std::move(floatArray);
        inputTensors.emplace_back(Ort::Value::CreateTensor<float>(m_memoryInfoHandler, inputFloatTensors[0].data(),
                                                                  m_inputTensorSize[0], m_inputNodeDims[0].data(), m_inputNodeDims[0].size()));

        if (!inputTensors[0].IsTensor()) {
            throw std::invalid_argument("Unable to create tensor from provided input at idx " + std::to_string(0));
        }

        return m_sessionPtr->Run(Ort::RunOptions{nullptr}, m_inputNodeNames.data(), inputTensors.data(), inputTensors.size(),
                                 m_outputNodeNames.data(), m_numOutputs);
    }
private:
    std::unique_ptr<Ort::Env> m_ortEnvPtr = nullptr;
    std::unique_ptr<Ort::Session> m_sessionPtr = nullptr;

    // Model information
    std::vector<const char*> m_inputNodeNames;
    std::vector<std::vector<int64_t>> m_inputNodeDims;
    std::vector<size_t> m_inputTensorSize;
    Ort::MemoryInfo m_memoryInfoHandler = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
    std::vector<const char*> m_outputNodeNames;
    std::vector<std::vector<int64_t>> m_outputNodeDims;

    int m_numInputs = 1;
    int m_numOutputs = 1;
};

int main() {
    OnnxRunner runner1("../models/yolov8n.onnx", 8);
    OnnxRunner runner2("../models/yolov8n.onnx", 8);

    auto input = cv::imread("/home/cyrus/work/YOLOv8-TensorRT-CPP/images/640_640.jpg");
    cv::resize(input, input, cv::Size(640, 640));
    cv::cvtColor(input, input, cv::COLOR_BGR2RGB);

    int numIts = 100;
    {
        preciseStopwatch s;
        for (int i = 0; i < numIts; ++i) {
            auto ret = runner1.runInference(input);
        }

        auto totalTime = s.elapsedTime<float, std::chrono::milliseconds>();
        std::cout << "Runner 1: " << totalTime / numIts << "ms" << std::endl;
    }

    {
        preciseStopwatch s;
        for (int i = 0; i < numIts; ++i) {
            auto ret = runner2.runInference(input);
        }

        auto totalTime = s.elapsedTime<float, std::chrono::milliseconds>();
        std::cout << "Runner 2: " << totalTime / numIts << "ms" << std::endl;
    }

    {
        preciseStopwatch s;
        for (int i = 0; i < numIts; ++i) {
            auto ret = runner1.runInference(input);
            ret = runner2.runInference(input);
        }

        auto totalTime = s.elapsedTime<float, std::chrono::milliseconds>();
        std::cout << "Runner 1 & 2: " << totalTime / numIts << "ms" << std::endl;
    }

    return 0;
}


```

**Comment by cyrusbehr** [comment]
@pranavsharma one final question for you, and I'll try to phrase this as best I can.
So for my use case, I have a class, let's say `foo`, which is going to own multiple inference sessions for the various models in my pipeline which will be run sequentially. I will therefore implement a global thread pool for this scenario. I have found through testing that 8 threads in the pool is the sweet spot based on the size of the models.

Now let's say the application is to be run on a CPU with 32 threads. I'd like to make use of all of the resources. Ideally I'd therefore like to create 4 instances of `foo` to run their pipelines in parallel. Each instance of `foo` would have it's own global threadpool using 8 threads (therefore 4 instances * 8 threads = 32 threads used in total). How could I implement this? From my understanding, if I used the traditional threadpool setup like in my code above, all 4 instances of `foo` would end up sharing the same threadpool. How can I have each instance of `foo` use it's own threadpool? Is this something possible to implement?

**Comment by pranavsharma** [comment]
@cyrusbehr If you expect all sessions (that are part of a pipeline) to be running in parallel, you don't need a global threadpool because in that case all sessions will compete for the same threads. You just need to ensure each of your 4 sessions is configured to use 8 threads (on a 32-core machine) that are assigned to separate cores using the thread affinity feature.

Also, in your code each OnnxRunner instance creates a new env instance. You need **only one** env instance in the whole process irrespective of whether you're a global threadpool or not.

**Comment by cyrusbehr** [comment]
@pranavsharma thank you for the feedback, I've implemented the changes. 
That being said, I identified a large slowdown when using global thread pool with certain models. I tested with Ultralytics YoloV8n, and using a session threadpools has the same inference speed as using a global threadpool. 

However, I then tested with this resnet 100 model, which is an adaptation of one of our production models, and the inference time when using a global thread pool is massively slower than when using a session threadpool. 

Here is the model: https://drive.google.com/file/d/1gP1512xaFvS82kQDPHek9cpYqdt638V-/view?usp=drive_link

With my code below, you can comment this line out to toggle between global thread pool and session thread pool: `#define USE_GLOBAL_THREADPOOL`

With a session threadpool, the inference time is `45.93ms`. With global threadpool, the inference time is: `130.22ms`. 

Note, this model does have subnormal values, described in [this[(https://github.com/microsoft/onnxruntime/issues/15630) issue, which is why the `SetGlobalDenormalAsZero` / `kOrtSessionOptionsConfigSetDenormalAsZero` flags are used.

Can you please have a look and test on your end, and explain if this is a bug or an issue with my implementation? 

```c++
#include <iostream>
#include "onnxruntime_cxx_api.h"
#include <memory>
#include <opencv2/opencv.hpp>
#include "onnxruntime_session_options_config_keys.h"

#define USE_GLOBAL_THREADPOOL

// Stopwatch Utility
template <typename Clock = std::chrono::high_resolution_clock>
class Stopwatch
{
    typename Clock::time_point start_point;
public:
    Stopwatch() :start_point(Clock::now()){}

    // Returns elapsed time
    template <typename Rep = typename Clock::duration::rep, typename Units = typename Clock::duration>
    Rep elapsedTime() const {
        std::atomic_thread_fence(std::memory_order_relaxed);
        auto counted_time = std::chrono::duration_cast<Units>(Clock::now() - start_point).count();
        std::atomic_thread_fence(std::memory_order_relaxed);
        return static_cast<Rep>(counted_time);
    }
};

using preciseStopwatch = Stopwatch<>;
using systemStopwatch = Stopwatch<std::chrono::system_clock>;
using monotonicStopwatch = Stopwatch<std::chrono::steady_clock>;

std::vector<float> hwcToChw(const cv::Mat& rgbImage, const std::array<float, 3>& subVals = {0.f, 0.f, 0.f},
                            const std::array<float, 3>& divVals = {1.f, 1.f, 1.f}, bool normalize = true) {
    float normFactor = 255.f;
    if (!normalize) {
        normFactor = 1.f;
    }
    std::vector<float> dataBuffer;
    dataBuffer.resize(rgbImage.cols * rgbImage.rows * rgbImage.channels());
    int insertIdx = 0;
    // hwc to chw conversion
    for (int c = 0; c < 3; ++c) {
        for (int i = 0; i < rgbImage.rows; ++i) {
            for (int j = 0; j < rgbImage.cols; ++j) {
                const auto retrievalIdx = (i * rgbImage.cols + j) * 3 + c;
                const auto transformIdx = retrievalIdx % 3;
                dataBuffer[insertIdx++] =  (static_cast<float>(rgbImage.data[retrievalIdx]) - (subVals[transformIdx] * normFactor)) / (divVals[transformIdx] * normFactor);

            }
        }
    }
    return dataBuffer;
}

class OnnxRunner {
public:
    OnnxRunner(const std::string& modelPath, int numThreads, Ort::Env& ortEnv) {
        Ort::SessionOptions session_options;
        session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);

#ifdef USE_GLOBAL_THREADPOOL
        session_options.DisablePerSessionThreads();
        std::cout << "Using global thread pool" << std::endl;
#else
        std::cout << "NOT using global thread pool" << std::endl;
        session_options.SetIntraOpNumThreads(numThreads);
        session_options.AddConfigEntry(kOrtSessionOptionsConfigSetDenormalAsZero, "1");
//        session_options.AddConfigEntry(kOrtSessionOptionsConfigAllowIntraOpSpinning, "0");
#endif

        m_sessionPtr = std::make_unique<Ort::Session>(ortEnv, modelPath.c_str(), session_options);

        Ort::AllocatorWithDefaultOptions allocator;
        m_numInputs = m_sessionPtr->GetInputCount();
        m_inputNodeNames.resize(m_numInputs);
        for (int i = 0; i < m_numInputs; ++i) {
            m_inputNodeNames[i] = strdup(m_sessionPtr->GetInputNameAllocated(i, allocator).get());
            auto typeInfo = m_sessionPtr->GetInputTypeInfo(i);
            auto tensorInfo = typeInfo.GetTensorTypeAndShapeInfo();
            auto inputDims = tensorInfo.GetShape();
            size_t tensorSize = 1;
            for (auto & inputDim : inputDims) {
                if (inputDim == -1) {
                    inputDim = 1;
                }
                tensorSize *= inputDim;
            }

            m_inputNodeDims.push_back(inputDims);
            m_inputTensorSize.push_back(tensorSize);
        }
        m_numOutputs = m_sessionPtr->GetOutputCount();
        m_outputNodeNames.resize(m_numOutputs);
        for (int i = 0; i < m_numOutputs; ++i) {
            m_outputNodeNames[i] = strdup(m_sessionPtr->GetOutputNameAllocated(i, allocator).get());
            auto outputTypeInfo = m_sessionPtr->GetOutputTypeInfo(i);
            auto outputTensorInfo = outputTypeInfo.GetTensorTypeAndShapeInfo();
            auto outputDims = outputTensorInfo.GetShape();
            m_outputNodeDims.push_back(outputDims);
        }
    }

    std::vector<Ort::Value> runInference(const cv::Mat& inputRGB) {
        std::vector<std::vector<float>> inputFloatTensors(1);
        std::vector<Ort::Value> inputTensors;

        auto floatArray = hwcToChw(inputRGB);
        inputFloatTensors[0] = std::move(floatArray);
        inputTensors.emplace_back(Ort::Value::CreateTensor<float>(m_memoryInfoHandler, inputFloatTensors[0].data(),
                                                                  m_inputTensorSize[0], m_inputNodeDims[0].data(), m_inputNodeDims[0].size()));

        if (!inputTensors[0].IsTensor()) {
            throw std::invalid_argument("Unable to create tensor from provided input at idx " + std::to_string(0));
        }

        return m_sessionPtr->Run(Ort::RunOptions{nullptr}, m_inputNodeNames.data(), inputTensors.data(), inputTensors.size(),
                                 m_outputNodeNames.data(), m_numOutputs);
    }
private:
    std::unique_ptr<Ort::Session> m_sessionPtr = nullptr;

    // Model information
    std::vector<const char*> m_inputNodeNames;
    std::vector<std::vector<int64_t>> m_inputNodeDims;
    std::vector<size_t> m_inputTensorSize;
    Ort::MemoryInfo m_memoryInfoHandler = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
    std::vector<const char*> m_outputNodeNames;
    std::vector<std::vector<int64_t>> m_outputNodeDims;

    int m_numInputs = 1;
    int m_numOutputs = 1;
};

int main() {
    const int numInferenceThreads = 8;
    cv::setNumThreads(numInferenceThreads);

#ifdef USE_GLOBAL_THREADPOOL
    const OrtApi* g_ort = OrtGetApiBase()->GetApi(ORT_API_VERSION);
        OrtThreadingOptions* tp_options;
        g_ort->CreateThreadingOptions(&tp_options);
        g_ort->SetGlobalIntraOpNumThreads(tp_options, numInferenceThreads);
        g_ort->SetGlobalDenormalAsZero(tp_options);
        Ort::Env ortEnv(tp_options, ORT_LOGGING_LEVEL_WARNING, "Default");
        g_ort->ReleaseThreadingOptions(tp_options);
#else
    Ort::Env ortEnv(ORT_LOGGING_LEVEL_WARNING, "Default");
#endif

    OnnxRunner runner1("/home/cyrus/Downloads/r100_v1.onnx", numInferenceThreads, ortEnv);

    auto input = cv::imread("/home/cyrus/work/YOLOv8-TensorRT-CPP/images/640_640.jpg");
    cv::resize(input, input, cv::Size(640, 640));
    cv::cvtColor(input, input, cv::COLOR_BGR2RGB);

    int numParallelThreads = 1;

    // Discard first 10 inferences
    runner1.runInference(input);

    int numIts = 100;
    {
        preciseStopwatch s;
#pragma omp parallel for num_threads(numParallelThreads)
        for (int i = 0; i < numIts; ++i) {
            auto ret = runner1.runInference(input);
        }

        auto totalTime = s.elapsedTime<float, std::chrono::milliseconds>();
        std::cout << "Runner 1: " << totalTime / numIts << "ms" << std::endl;
    }
    return 0;
}

```

**Comment by cyrusbehr** [comment]
I did some further testing, and seems I need to set `session_options.AddConfigEntry(kOrtSessionOptionsConfigSetDenormalAsZero, "1");` even when using the global threadpool. If that's the case, what is the point of `g_ort->SetGlobalDenormalAsZero(tp_options);`?

**Comment by pranavsharma** [comment]
> I did some further testing, and seems I need to set `session_options.AddConfigEntry(kOrtSessionOptionsConfigSetDenormalAsZero, "1");` even when using the global threadpool. If that's the case, what is the point of `g_ort->SetGlobalDenormalAsZero(tp_options);`?

Ok, this might be a bit confusing but bear with me here. We've a threadpool (global or otherwise) that consists of N threads (configured via intra_op_num_threads). The thread invoking Run() is part of this pool. The session option applies to this invoking thread and the call to SetGlobalDenormalAsZero applies to the remaining N-1 threads. Hence, you need both _if you're using global threadpool_. For regular threadpool, only setting the session options is enough.

**Comment by cyrusbehr** [comment]
I see, that makes sense. 
Thank you for the Grade A support, much appreciated.
