### ISSUE TITLE
[Mobile] Failed to load onnx model on real iPhone device (but works on both Android and iOS simulator)

### ISSUE THREAD

**Issue by l3utterfly** [microsoft/onnxruntime#17017]
### Describe the issue

Loading an model with `Inference.create` does not work when running on real iOS devices.

It fails with the error: "Can't load a model: failed to load model from buffer"

The same code works on Android emulator, real Android device, and iOS emulator. It only fails on a real iPhone. Tested with iPhone 12,13,14

### To reproduce

Export a model from python. Load using:

```
let assetPath: string;
let base64Str: string;

if (Platform.OS === 'android') {
    assetPath = `models/${TFIDF_MODEL_FILENAME}`;
    base64Str = await RNFS.readFileAssets(assetPath, 'base64');
} else {
    assetPath = `${RNFS.MainBundlePath}/${TFIDF_MODEL_FILENAME}`;
    base64Str = await RNFS.readFile(assetPath, 'base64');
}

const bytes = base64.toByteArray(base64Str);
const array = new Uint8Array(bytes);

let buf = array.buffer as ArrayBufferLike;

// load a model
this.session = await InferenceSession.create(buf);
```

### Platform

iOS

### OS Version

16.2

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

onnxruntime-react-native

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

JavaScript

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by yufenglee** [comment]
@skottmckay

**Comment by skottmckay** [comment]
@YUNQIUGUO could you please take a look?

**Comment by l3utterfly** [comment]
[tfidf_v2.zip](https://github.com/microsoft/onnxruntime/files/12321127/tfidf_v2.zip)

This is the model in question if it helps. It's a TF-IDF classifier.

**Comment by YUNQIUGUO** [comment]
> [tfidf_v2.zip](https://github.com/microsoft/onnxruntime/files/12321127/tfidf_v2.zip)
> 
> This is the model in question if it helps. It's a TF-IDF classifier.

thanks for providing the model. that will be helpful. will try to see if I can reproduce the error locally. 

And fyi, I just tested a simple mnist.ort (https://github.com/microsoft/onnxruntime/blob/main/js/react_native/e2e/src/mnist.ort) model on iphone (12) device with the same release version 1.15.1 ort react native package in an Expo app. it successfully loads the model and is able to create an ort inference session. etc.

could be model specific issues. will update if I have more findings.

**Comment by YUNQIUGUO** [comment]
looks like the issue actually comes from the locale configurations when loading the `StringNormalizer` op in your model.

The explicit message:
```
[E:onnxruntime:, inference_session.cc:1644 operator()] Exception during initialization: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/nn/string_normalizer.cc:90 auto onnxruntime::string_normalizer::Locale::Locale(const std::string &)::(anonymous class)::operator()() const Failed to construct locale with name:en_US.UTF-8:collate_byname<char>::collate_byname failed to construct for en_US.UTF-8:Please, install necessary language-pack-XX and configure locales
```

and sorry - we should probably make it more clearer and dump more info other than the JS level console log message.

couple ways to try:
1. If you are running the react native iOS app in Xcode, try to go to `Product-Edit Scheme-Run-Argument Passed on Launch` and pass in the specific language locale argument.
2. Also in `Run->Options`, you can specify application region/application language too.

https://developer.apple.com/forums/thread/40116
https://developer.apple.com/documentation/xcode/testing-localizations-when-running-your-app/
https://stackoverflow.com/questions/3910244/getting-current-device-language-in-ios

Also, what's your test device preferred language? 

Not an expert in locale stuff though. cc @yuslepukhin

**Comment by l3utterfly** [comment]
I have tested on devices with en_GB, and zh_CN.

Is there a general workaround/fix for this? I can't expect my users to always use the same language or ask them to change their device language.

Or can there be a parameter i pass to onnxruntime which fixes the language (I'm ok with only supporting en_US string input).

**Comment by l3utterfly** [comment]
Thanks for the tip. I'm converting the model from an sklearn TF-IDF pipeline, like so:

```
model_onnx = convert_sklearn(
    pipeline,
    "tfidf_pipeline",
    initial_types=[("input", StringTensorType([1, 1]))],
    # https://github.com/triton-inference-server/onnxruntime_backend/issues/94#issuecomment-1142065156
    options={LogisticRegression: {"zipmap": False}},
    target_opset=12,
)
```

Is this something I need to change within the `convert_sklearn` conversion process? Or can I use a tool to read the converted onnx model and adjust the locale?

**Comment by l3utterfly** [comment]
Also, I changed my phone's primary language to en_US, it still shows the same error.

**Comment by l3utterfly** [comment]
Upon further testing, I don't believe the locale is the root issue. I changed my simulator to en-GB, and printed out my language setting using: `[NSLocale preferredLanguages]`. It return "en-GB". My model file still works.

It only stops working on a real device for some reason. On my real device, I made sure my locale was en-US, and it still does not work.

**Comment by l3utterfly** [comment]
Upon some further research, it appears iOS doesn't ship with standard locales: https://stackoverflow.com/questions/51949128/c-stdlocaleen-throws-exception-on-ios

Is there a work around for this? Or is onnx unable to support string normalisers in iOS?

**Comment by YUNQIUGUO** [comment]
ok I see. thanks for the response.

I think the issue should still be with the locale though. looks like currently, ORT StringNormalizer op's implementation works as: if not set (meaning not setting the attribute field in the model which is your case), it will use a `default_locale`. The issue is currently we set the default_locale as `en_US.` for all non-MSVC. See below the implementation:

https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/cpu/nn/string_normalizer.cc#L289
https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/cpu/nn/string_normalizer.cc#L204

but iOS language code uses `en` for English and if for specifying a region such as UK, uses `en-GB` (using `-` but not underscore `_`). So the default_locale is not working here. https://developer.apple.com/documentation/xcode/choosing-localization-regions-and-scripts

One solution is that we could look into modify the implementation of onnx StringNormalizer, and change the default_locale when building for `#if defined(__APPLE__)`. 

Another solution is you can still configure the `locale` attribute (to be `en`) in your model. but looks like on Android, it commonly uses an `_` underscore for seperator though.

**Comment by l3utterfly** [comment]
Thanks, I will try using just "en". I will have to ship different modesl for iphone/android which is undesirable.

If we can change the default locale using `#if defined(__APPLE__)` that would be great.
