### ISSUE TITLE
[Build] onnxruntime_cxx_api.h is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]

### ISSUE THREAD

**Issue by LuWei6896** [microsoft/onnxruntime#17027]
### Describe the issue

I am using clang for compilation, and I encountered an error when referencing onnxruntime.

### Target platform

Clang V9.0 OS:windows/ubuntu

### Build script

"buildtools\win\gn.exe" gen out/Release --args="is_debug=false is_clang=false target_os=\"win\" target_cpu=\"x86\"" --ide=vs2017
"%DEPOT_TOOLS%\ninja.exe" -C out/Release

### Error / output

ERROR:

onnxruntime_cxx_api.h:174:96: error: extra ';' after member function definition [-Werror,-Wextra-semi]
  constexpr bool operator==(const Float16_t& rhs) const noexcept { return value == rhs.value; };
                                                                                               ^
../../../third_party/mylibs/onnxruntime/include/onnxruntime/core/session/onnxruntime_cxx_api.h:175:96: error: extra ';' after member function definition [-Werror,-Wextra-semi]
  constexpr bool operator!=(const Float16_t& rhs) const noexcept { return value != rhs.value; };
                                                                                               ^
../../../third_party/mylibs/onnxruntime/include/onnxruntime/core/session/onnxruntime_cxx_api.h:193:97: error: extra ';' after member function definition [-Werror,-Wextra-semi]
  constexpr bool operator==(const BFloat16_t& rhs) const noexcept { return value == rhs.value; };
                                                                                                ^
../../../third_party/mylibs/onnxruntime/include/onnxruntime/core/session/onnxruntime_cxx_api.h:194:97: error: extra ';' after member function definition [-Werror,-Wextra-semi]
  constexpr bool operator!=(const BFloat16_t& rhs) const noexcept { return value != rhs.value; };
                                                                                                ^
../../../third_party/mylibs/onnxruntime/include/onnxruntime/core/session/onnxruntime_cxx_api.h:205:30: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
ORT_DEFINE_RELEASE(Allocator);
                             ^
../../../third_party/mylibs/onnxruntime/include/onnxruntime/core/session/onnxruntime_cxx_api.h:206:31: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
ORT_DEFINE_RELEASE(MemoryInfo);
                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
..........
onnxruntime_c_api.h:257:28: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
ORT_RUNTIME_CLASS(TypeInfo);
                           ^
../../../third_party/mylibs/onnxruntime/include/onnxruntime/core/session/onnxruntime_c_api.h:258:42: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
ORT_RUNTIME_CLASS(TensorTypeAndShapeInfo);
                                         ^
../../../third_party/mylibs/onnxruntime/include/onnxruntime/core/session/onnxruntime_c_api.h:259:34: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
ORT_RUNTIME_CLASS(SessionOptions);
                                 ^
../../../third_party/mylibs/onnxruntime/include/onnxruntime/core/session/onnxruntime_c_api.h:260:34: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
ORT_RUNTIME_CLASS(CustomOpDomain);
                                 ^
../../../third_party/mylibs/onnxruntime/include/onnxruntime/core/session/onnxruntime_c_api.h:261:31: error: extra ';' outside of a function is incompatible with C++98 [-Werror,-Wc++98-compat-extra-semi]
ORT_RUNTIME_CLASS(MapTypeInfo);

...........

### Visual Studio Version

2017

### GCC / Compiler Version

Clang 9.0

**Comment by LuWei6896** [comment]
However, when I used clang version 12.0, the error disappeared.

**Comment by yuslepukhin** [comment]
We do not recommend using C interfaces from C++ code due to exception safety issues.

**Comment by pranavsharma** [comment]
> C++98 is too old. @pranavsharma , what's the minimum C++ version we support for onnxruntime_cxx_api.h ?
> 
C++14
