### ISSUE TITLE
[Performance] Execution time very slow in FP16 using the `CoreMLExecutionProvider`

### ISSUE THREAD

**Issue by laclouis5** [microsoft/onnxruntime#17033]
### Describe the issue

The inference speed of a model converted to FP16 using the `onnxconverter-common` package is very slow compared to the FP32 version when using the `CoreMLExecutionProvider` execution provider.

### To reproduce

Here is a code snippet to reproduce the issue (this requires `onnruntime` compiled with CoreML support, for instance using the package `onnxruntime-silicon`):

```python
import torch
from torch.utils import data as torch_data
from torchvision.models import resnet50
import onnx
import onnxconverter_common as onc
import onnxruntime as ort
from tqdm import tqdm


class Dataset(torch_data.Dataset):
    def __len__(self):
        return 100
    
    def __getitem__(self, _: int):
        return torch.randn(3, 512, 512)


def main():
    model = resnet50()
    input = torch.randn(1, 3, 512, 512)
    
    torch.onnx.export(
        model=model,
        args=input,
        f="model.onnx",
        input_names=["input"], 
        output_names=["output"],
    )
    
    onnx_model = onc.convert_float_to_float16_model_path(
        "model.onnx", 
        keep_io_types=True,
    )
    
    onnx.save(onnx_model, "model_fp16.onnx")
    
    dataset = Dataset()
    dataloader = torch_data.DataLoader(
        dataset, 
        batch_size=1, 
        shuffle=False, 
        num_workers=6, 
        persistent_workers=True,
        multiprocessing_context="forkserver",
    )
    
    providers = ["CoreMLExecutionProvider"]
    onnx_model = ort.InferenceSession("model.onnx", providers=providers)
    
    for _ in range(10):
        _ = onnx_model.run(None, {"input": input.numpy()})
    
    for input in tqdm(dataloader, desc="FP32"):
        _ = onnx_model.run(None, {"input": input.numpy()})
        
    onnx_model = ort.InferenceSession("model_fp16.onnx", providers=providers)
    
    for _ in range(10):
        _ = onnx_model.run(None, {"input": input.numpy()})
    
    for input in tqdm(dataloader, desc="FP16"):
        _ = onnx_model.run(None, {"input": input.numpy()})


if __name__ == "__main__":
    main()
```

The FP16 version is 8 times slower than the FP32 version on my MacBook Pro M1 Pro.

### Urgency

This issue is non blocking but could be very surprising since people generally expect FP16 to be faster than FP32 execution. I think that the CoreML and the ANE support FP16 execution so this may be fixable.

### Platform

Mac

### OS Version

Ventura

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

v1.15.0 with CoreML support

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

CoreML

### Model File

The provided code should generate the model files.

### Is this a quantized model?

No

**Comment by edgchen1** [comment]
FYI, the CoreML EP does not support fp16 yet. You should be able to see what nodes are actually assigned to the CoreML EP in the logs (with verbose log level).

https://github.com/microsoft/onnxruntime/blob/8a335b8347f4a93d55e2fd5a090b3bf9dabb1376/onnxruntime/core/providers/coreml/builders/impl/base_op_builder.cc#L115-L120

**Comment by laclouis5** [comment]
Thanks for the rapid update. Wound't it be a good patch meanwhile the feature is developed to automatically cast those nodes to FP32 for execution on the CoreML execution provider?
