### ISSUE TITLE
How to determine if VitisAI EP is available?

### ISSUE THREAD

**Issue by Liuqh12** [microsoft/onnxruntime#17073]
### Describe the issue

My work based on: https://onnxruntime.ai/docs/execution-providers/Vitis-AI-ExecutionProvider.html

After finish all steps. My conda env packages list as follow:
```text
coloredlogs         15.0.1
flatbuffers         23.5.26
glog                0.3.1
humanfriendly       10.0
imageio             2.31.1
mpmath              1.3.0
numpy               1.25.2
onnxruntime         1.15.1
onnxruntime-vitisai 1.15.1
opencv-python       4.8.0.74
packaging           23.1
Pillow              10.0.0
pip                 23.2.1
protobuf            4.23.4
pyreadline3         3.4.1
python-gflags       3.1.2
setuptools          68.0.0
six                 1.16.0
sympy               1.12
voe                 0.1.0
wheel               0.38.4
```

Then:
```python
python resnet_classification.py
```
Result:
```text
============ Top 5 labels are: ============================
n01917289 brain coral 0.9997817873954773
n01496331 electric ray, crampfish, numbfish, torpedo 0.00015842675929889083
n09256479 coral reef 3.534978532115929e-05
n02655020 puffer, pufferfish, blowfish, globefish 1.012788197840564e-05
n07754684 jackfruit, jak, jack 4.784073098562658e-06
===========================================================
```
However, when i want to check EPs :
```python
import onnxruntime as rt

print(rt.get_available_providers())
```
result:
```text
['CPUExecutionProvider']
```
I think is NOT OK! Due to:
```text 
pip install onnxruntime-directml
 ```
i can get:
```text 
['DmlExecutionProvider', 'CPUExecutionProvider']
 ```
Besides:
when i running  ***installer.py*** in .zip file, i got:
```text
2023-08-09 16:46:50,737 - INFO - copying C:\Windows\System32\AMD\xrt_core.dll to C:\Users\Slim7\.conda\envs\new_vai\lib\site-packages\onnxruntime\capi
2023-08-09 16:46:50,737 - INFO - copying C:\Windows\System32\AMD\xrt_coreutil.dll to C:\Users\Slim7\.conda\envs\new_vai\lib\site-packages\onnxruntime\capi
2023-08-09 16:46:50,742 - CRITICAL - C:\Windows\System32\AMD\xrt_phxcore.dll does not exist.
2023-08-09 16:46:50,742 - INFO - copying C:\voe-3.5-win_amd64\voe-0.1.0-cp39-cp39-win_amd64\onnxruntime.dll to C:\Users\Slim7\.conda\envs\new_vai\lib\site-packages\onnxruntime\capi
```
if i create conda environment from .whl file  in url: https://github.com/amd/RyzenAI-cloud-to-client-demo/tree/main/wheels
running print as follow:
```text
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20230809 17:05:35.257613  6004 vitisai_compile_model.cpp:210] Vitis AI EP Load ONNX Model Success
I20230809 17:05:35.257613  6004 vitisai_compile_model.cpp:211] Graph Input Node Name/Shape (1)
I20230809 17:05:35.257613  6004 vitisai_compile_model.cpp:215]   blob.1 : [1x3x224x224]
I20230809 17:05:35.257613  6004 vitisai_compile_model.cpp:221] Graph Output Node Name/Shape (1)
I20230809 17:05:35.257613  6004 vitisai_compile_model.cpp:225]   1327 : [1x1000]
I20230809 17:05:35.257613  6004 tool_function.cpp:46] [UNILOG][DEBUG-INFO][C:\Users\Test\workspace\xir\src\xir\util\tool_function.cpp:46] Read all data from C:\voe-3.5-win_amd64\Examples\resnet50_python\models\ResNet\ResNet_int.onnx to calculate the md5sum.
I20230809 17:05:35.853539  6004 tool_function.cpp:61] [UNILOG][DEBUG-INFO][C:\Users\Test\workspace\xir\src\xir\util\tool_function.cpp:61] md5sum(C:\voe-3.5-win_amd64\Examples\resnet50_python\models\ResNet\ResNet_int.onnx) = 3f97582a85b8ae1be41127f326bbf9b2.
============ Top 5 labels are: ============================
n01917289 brain coral 0.9997947812080383
n01496331 electric ray, crampfish, numbfish, torpedo 0.00012338446686044335
n09256479 coral reef 4.5390606828732416e-05
n02655020 puffer, pufferfish, blowfish, globefish 2.1441006538225338e-05
n02526121 eel 4.784134944202378e-06
===========================================================
```

### To reproduce

Just follow the steps in: https://onnxruntime.ai/docs/execution-providers/Vitis-AI-ExecutionProvider.html
My device IPU driver version is ：10.105.5.42
Python: 3.9.17
other infor:
```text
GPU Controller: AMD Radeon(TM) 780M
  Date: 27/06/2023 00:00:00 -000
  Version: 31.0.14003.46013


XCLBIN: "C:\\Windows\\System32\\AMD\\1x4.xclbin"
XCLBIN MD5: 20ea884e144ec5c97a5f2d852ca7e3b1
WARNING: xmodel not found in compiled_xmodel_generator.xmodel. Skipping VART and RML tests.

No ISP driver found

IPU Firmware: "C:\\Windows\\System32\\AMD\\ipu.sbin"
IPU Firmware Version: 0.0.16.17

IPU driver info:
  Version: 10.105.5.42

XRT Version: 2.14.0

VART info:
  XIR Version: xir.2.5.0
  Xilinx vart-mem-manager Version: 2.0.0-4b0b89b68d7a82ba283f7a8749e8f59a94ca97ec 42 2023-04-19
  Xilinx vart-runner Version: 2.0.0-4b0b89b68d7a82ba283f7a8749e8f59a94ca97ec 42 2023-04-19
  Xilinx vart-util Version: 2.0.0-4b0b89b68d7a82ba283f7a8749e8f59a94ca97ec 42 2023-04-19

aks Version: 2.5.0-bd87a5f08fbdb2dbba66b5c8400b8303dd33ef37 42 2023-04-19

RadeonML Version: 0.10.0.0-c0f2212188a5bdf0efc57c0b0922f42ea221d5d6 42 2023-04-19

Running IPU Test ... Pass.
Running XRT Test ... Pass.
Success
```

### Platform

Windows

### OS Version

Windows 11 Version 22H2(OS Build 22621.2134)

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Vitis AI

### Execution Provider Library Version

voe 0.1.0 , onnxruntime-vitisai 1.15.1

**Comment by pranavsharma** [comment]
Uninstall _all_ onnxruntime pkgs on your machine. Then install only the vitisAI EP related pkg. Then check. Also, I assume you built with --use_vitisai. The full list comes from [here](https://github.com/microsoft/onnxruntime/blob/00b1e79e048e36e404d5b6516238d347aa5ba81f/onnxruntime/core/providers/get_execution_providers.cc#L79-L86), so there's no reason to believe this won't be populated correctly if the build was done correctly to begin with.

**Comment by quentonh** [comment]
@Liuqh12 There appear to be several issues with this documentation.  We will update this ASAP, but in the meantime, I will point you here:  https://ryzenai.docs.amd.com/en/latest/inst.html

**Comment by Liuqh12** [comment]
> Uninstall _all_ onnxruntime pkgs on your machine. Then install only the vitisAI EP related pkg. Then check. Also, I assume you built with --use_vitisai. The full list comes from [here](https://github.com/microsoft/onnxruntime/blob/00b1e79e048e36e404d5b6516238d347aa5ba81f/onnxruntime/core/providers/get_execution_providers.cc#L79-L86), so there's no reason to believe this won't be populated correctly if the build was done correctly to begin with.

Thanks for you replay. 
At first, i tried  compiling with:
```text
.\build.bat --use_vitisai --build_shared_lib --parallel --config Release --build_wheel
```
However:
```text
C:\ProgramData\miniconda3\Library\include\gmock/gmock-matchers.h(2312,33): error C2039: 'const_iterator': is not a member of 'gsl::span<const float,18
446744073709551615>'
```
So, install from  .zip  can help me quickly verify the App.

**Comment by Liuqh12** [comment]
> @Liuqh12 There appear to be several issues with this documentation. We will update this ASAP, but in the meantime, I will point you here: https://ryzenai.docs.amd.com/en/latest/inst.html

The information you provide is crucial. Thank you very much.

**Comment by Liuqh12** [comment]
Summary as follow:
- IPU driver must be signed. Same as [this Fig](https://ryzenai.docs.amd.com/en/latest/_images/ipu_device_properties.png).
- Running installer.py and without and error. 
- Do not install any other onnxruntime* pkgs. For example, install vai_q_onnx to a new conda env.

**Comment by quentonh** [comment]
@Liuqh12 Great work!  We will update the ORT.ai documentation.  Thanks for your patience with this.

**Comment by fxmarty** [comment]
It appears that the ResNet example in the 4.5 package has a `warnings.filterwarnings('ignore')` which makes it hard to realize that the installation is faulty. This example is unfortunately removed from `voe-4.0-win_amd64`.
