### ISSUE TITLE
Model optimization during shape inferencing fails due to protobuf 2GB limit

### ISSUE THREAD

**Issue by shaahji** [microsoft/onnxruntime#17098]
### Describe the issue

Model optimization for large models fail during optimization with error related to protobuf 2GB limit. The logic has an option for saving using external data i.e. _save_as_external_data_ but is ignored.

https://github.com/microsoft/onnxruntime/blob/b4e0fc87ea746cf0bcb024e8f60c4d1e610bb2ae/onnxruntime/python/tools/quantization/shape_inference.py#L24-L38

https://github.com/microsoft/onnxruntime/blob/b4e0fc87ea746cf0bcb024e8f60c4d1e610bb2ae/onnxruntime/python/tools/quantization/shape_inference.py#L81-L85

### To reproduce

Export Llama model specifically, Red Pajama and quantize the model.

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

c3f04251c74c296da982caf683a16e06af2722d4

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.8

**Comment by yufenglee** [comment]
@chenfucn , could you please take a look?

**Comment by shaahji** [comment]
Fixed by #17100
