### ISSUE TITLE
[Build] sha1 hash mismatch

### ISSUE THREAD

**Issue by jeyblu** [microsoft/onnxruntime#17119]
### Describe the issue

Error building onnxruntime on Ubuntu 22.04 at e7e974b23f

> ./build.sh --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync
> 
> -- Using src='https://github.com/onnx/onnx/archive/refs/heads/rel-1.14.1.zip'
> -- [download 100% complete]
> -- verifying file...
>        file='onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-subbuild/onnx-populate-prefix/src/rel-1.14.1.zip'
> -- SHA1 hash of
>     onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-subbuild/onnx-populate-prefix/src/rel-1.14.1.zip
>   does not match expected value
>     expected: '5d2e5421f522d93c783c9bd523c2776927bcff5b'
>       actual: 'de77bfb36afe23d4dbd39e719d0acfa6b19d7f18'
> -- Hash mismatch, removing...
> -- Using src='https://github.com/onnx/onnx/archive/refs/heads/rel-1.14.1.zip'
> 
>   Build step for onnx failed: 2

Root caused to 6986981482. Building prior commit 6dffd1a890 did not have this error.

6986981482 (2023-08-10) noreply@github.com Bump ONNX version (#16325)
6dffd1a890 (2023-08-10) noreply@github.com Update model_tests.cc: avoid auto adding new tests from new opsets (#17084)

### Target platform

Ubuntu 22.04

### Build script

./build.sh --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync

### Error / output

./build.sh --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync

-- Using src='https://github.com/onnx/onnx/archive/refs/heads/rel-1.14.1.zip'
-- [download 100% complete]
-- verifying file...
       file='onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-subbuild/onnx-populate-prefix/src/rel-1.14.1.zip'
-- SHA1 hash of
    onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-subbuild/onnx-populate-prefix/src/rel-1.14.1.zip
  does not match expected value
    expected: '5d2e5421f522d93c783c9bd523c2776927bcff5b'
      actual: 'de77bfb36afe23d4dbd39e719d0acfa6b19d7f18'
-- Hash mismatch, removing...
-- Using src='https://github.com/onnx/onnx/archive/refs/heads/rel-1.14.1.zip'

  Build step for onnx failed: 2

**Comment by ytaous** [comment]
dup of https://github.com/microsoft/onnxruntime/issues/17114
