### ISSUE TITLE
[Build] Build vitisai EP Fail on the main branch

### ISSUE THREAD

**Issue by lingchingteng** [microsoft/onnxruntime#17139]
### Describe the issue

I downloaded the latest main branch, and encountered an error while building the Vitis-AI Execution Provider (EP). The error message is: "error C2660: 'onnxruntime::Model::ToGraphProtoWithExternalInitializers': function does not take 2 arguments". 

It appears that this issue might be related to a specific [commit](https://github.com/microsoft/onnxruntime/commit/b7176f98266924053204fe25c3f2e701615c2585) which doesn't seem to address the usage of the Vitis provider.

### Target platform

AMD

### Build script

.\build.bat --config Release --build_shared_lib --use_vitisai --build_wheel --enable_pybind --parallel --skip_tests

### Error / output

error C2660: 'onnxruntime::Model::ToGraphProtoWithExternalInitializers': function does not take 2 arguments

### Visual Studio Version

VS2022

**Comment by pranavsharma** [comment]
@jywu-msft can you assign this to the right person?

**Comment by jywu-msft** [comment]
@BoarQing , have you encountered this before?

**Comment by BoarQing** [comment]
> @BoarQing , have you encountered this before?

We will try to reproduce the problem at our end.

**Comment by BoarQing** [comment]
https://github.com/microsoft/onnxruntime/issues/17252 fixes this
