### ISSUE TITLE
How do I do training with DirectML?

### ISSUE THREAD

**Issue by pauldog** [microsoft/onnxruntime#17132]
### Describe the issue

In nuget for c# there is:

onnxruntime.managed
onnxruntime.directml
onnxruntime.training

So I can train only on CPU. How do I do training with DirectML? I can do inference with DML but no training.

### To reproduce

Use latest nuget packages

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

15.1

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

DirectML

**Comment by fdwr** [comment]
> I can do inference with DML but no training.

Correct, the DirectML EP has always focused on inference. Typically training occurs in other higher level ML libraries like PyTorch or Tensorflow, emitting the final ONNX model for ORT. I'm curious about your scenario - is this for reinforcement learning (e.g NPC's in a game) where the model inputs wouldn't be pretrainable?

**Comment by pauldog** [comment]
> 

It is just for training models in Unity 3D. I like using the graphical interface of unity so it would make it easier to train models using c# and DirectML in there. 

It would also make it easier to share my projects without people having to worry about installing the correct versions of python etc.

Just a fun project. So no big deal.

**Comment by nums11** [comment]
Closing as resolved.

**Comment by fdwr** [comment]
> without people having to worry about installing the correct versions of python etc.

Quite understandable, not needing all those gigabytes of transitive dependencies and correctly matching versions. No promises, but local training is on the list of things we've considered. ⏳...
