### ISSUE TITLE
[Web/js/webgpu] `error: cannot assign to value expression of type 'u32'`

### ISSUE THREAD

**Issue by xenova** [microsoft/onnxruntime#17167]
### Describe the issue

I modified the [transformers.js demo site](https://xenova.github.io/transformers.js/) to test the webgpu backend and it just logged many warnings and errors. I've removed duplicates and sent them below:

```
Tint WGSL reader failure: :69:14 error: cannot assign to value expression of type 'u32'
      indices[2] -= sizeInConcatAxis[inputIndex - 1u];
             ^

:69:7 note: 'let' variables are immutable
      indices[2] -= sizeInConcatAxis[inputIndex - 1u];
      ^^^^^^^

:65:9 note: let 'indices' declared here
    let indices = o2i_output(global_idx);
        ^^^^^^^


 - While validating [ShaderModuleDescriptor]
 - While calling [Device].CreateShaderModule([ShaderModuleDescriptor]).
```

```
[Invalid ShaderModule] is invalid.
 - While validating compute stage ([Invalid ShaderModule], entryPoint: main).
 - While calling [Device].CreateComputePipeline([ComputePipelineDescriptor]).
```

```
[Invalid ComputePipeline] is invalid.
 - While Validating GetBindGroupLayout (0) on [Invalid ComputePipeline]
```

```
Tint WGSL reader failure: :74:14 error: cannot assign to value expression of type 'u32'
      indices[1] -= sizeInConcatAxis[inputIndex - 1u];
             ^

:74:7 note: 'let' variables are immutable
      indices[1] -= sizeInConcatAxis[inputIndex - 1u];
      ^^^^^^^

:70:9 note: let 'indices' declared here
    let indices = o2i_output(global_idx);
        ^^^^^^^


 - While validating [ShaderModuleDescriptor]
 - While calling [Device].CreateShaderModule([ShaderModuleDescriptor]).
```

```
An uncaught WebGPU validation error was raised: [Invalid BindGroupLayout] is invalid.
 - While validating [BindGroupDescriptor] against [Invalid BindGroupLayout]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).
```

```
An uncaught WebGPU validation error was raised: [Invalid CommandBuffer] is invalid.
 - While calling [Queue].Submit([[Invalid CommandBuffer]])
```

The output is also incorrect: "Hello, how are you?" -> "Bonjour, comment :", should be "Bonjour, comment êtes-vous?" (which actually is quite close, so, not bad!)

### To reproduce

1. Using yesterday's CI build: https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=1104462&view=artifacts&pathAsName=false&type=publishedArtifacts

2. You can replace the import in the demo site (source code available [here](https://github.com/xenova/transformers.js/tree/main/examples/demo-site)), but it should be thrown when running any example app.

3. Models tested: [t5-small](https://huggingface.co/Xenova/t5-small/tree/main/onnx) and [whisper.tiny.en](https://huggingface.co/Xenova/whisper-tiny.en/tree/main/onnx)

### Urgency

blocks webgpu release

### ONNX Runtime Installation

Other / Unknown

### ONNX Runtime Version or Commit ID

https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=1104462&view=artifacts&pathAsName=false&type=publishedArtifacts

### Execution Provider

'webgpu' (WebGPU)

**Comment by xenova** [comment]
cc @guschmue @fs-eire for visibility

**Comment by dakenf** [comment]
Yes. It can be fixed if you change 'let indices' to 'var indices' in concat.ts (I forgot to make a pr for that)

**Comment by dakenf** [comment]
There's also a small issue with expand.ts, a simple fix too. You can check it in my wasm64-dev2 branch (I don't think I can find it and link properly from mobile)
However I think I saw a PR to fix that too

**Comment by guschmue** [comment]
yeap, can take a look. There was some larger change in the index helper which might have resulted in some regression. I can run a good amount of the transformers.js models automated ... just running it to see if there is more.

**Comment by fs-eire** [comment]
merged https://github.com/microsoft/onnxruntime/pull/17171 to main. not sure if there are still errors. please let me know if there are any.

**Comment by guschmue** [comment]
there is a fix for expand. 
https://github.com/microsoft/onnxruntime/pull/17137
I had the expand issue too with clip-vit and the fix works for me.

**Comment by xenova** [comment]
Good news! No errors - and the output is correct :) The only problem is speed (both [t5-small](https://huggingface.co/Xenova/t5-small/tree/main/onnx) and [whisper-tiny.en](https://huggingface.co/Xenova/whisper-tiny.en) tested; both quantized and unquantized) are much slower than the WASM version.

```
Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance.
e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
```

**Comment by guschmue** [comment]
hm, I see both t5-small and whisper.tiny much faster but I test encoder and decoder separate and use fp32 models. Let me take a look.

**Comment by guschmue** [comment]
My log looks similar to yours but perf is good in my case. I think on my laptop it wasn't that good. 
Let me see if we can get rid of that concat/unsqueeze stuff.

**Comment by xenova** [comment]
If possible, could you share your generation code? Perhaps there is something I am missing in my [`generate` function](https://github.com/xenova/transformers.js/blob/main/src/models.js#L871). It might be the case that the output `Tensor`s are being brought back to the CPU after each generation step for some reason.

**Comment by guschmue** [comment]
I bulk test models and feed them manual with hand crafted data. 
So on my laptop webgpu was similar to wasm performance but it was using the integrated gpu. Once I switched to the nvidia gpu it was 4-6 times faster.
I see about the same amount of ops on cpu as in your log. cpu is not necessarily bad (ie when shapes get calculated). It just gets bad if there are cross device copies that are really slow. 
Room for improvement there of course (which we'll work on) but not that bad either.

What hardware do you use? Maybe check if you have some integrated gpu too. 
I find some time today to test with transformers.js and see how this works for me.

To figure what ops runs where: I like using the ort trace for this 
(session_options..enableProfiling = true)
with some tool that analyze the trace, easy to see what gets copied around. Can share the tool.

What operations do you need on the tensor? 

For transformers.js - @fs-eire has been working on io-bindings which might help in transformers.js with the kv caches I think.

**Comment by fs-eire** [comment]
If the shader error is fixed and we need to discuss about running ops, we can close this issue and open a new one for less confusing

**Comment by xenova** [comment]
Sounds good! 🚀
