### ISSUE TITLE
Question about Onnx model input

### ISSUE THREAD

**Issue by qw2208** [microsoft/onnxruntime#1717]
I'm wondering if the onnx model input could be "sequence/map" instead of tensor?
Since we could get the sequence output by ort::value::getValue(i,...), how could we construct the input sequence?

**Comment by snnn** [comment]
Yes. We have examples at:
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/onnx/TestCase.cc#L94

https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/onnx/TestCase.cc#L124

**Comment by qw2208** [comment]
So, is there any method to hold the tensor created when sometimes the data pointer passed to the tensor constructor has to be destroyed?

**Comment by snnn** [comment]
You won't be able to transfer the ownership of a buffer created by your application to onnxruntime, because they may use different heaps.

If you want to simplify data buffer's life-time management, you may use onnxruntime's allocators:
see: https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h#L313

**Comment by qw2208** [comment]
So I think this api just creates an empty tensor?
Is there a way to fill the tensor with different data types (float, int ...) like `OrtFillStringTensor` do?

**Comment by snnn** [comment]
Use https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h#L328 

To get the data pointer

**Comment by qw2208** [comment]
No. I may not get your point.
I need to create the tensor with api: `ORT_API_STATUS(OrtCreateTensorAsOrtValue, _Inout_ OrtAllocator* allocator,
               _In_ const int64_t* shape, size_t shape_len, ONNXTensorElementDataType type,
               _Outptr_ OrtValue** out);`

I'm wondering how I could fill this tensor?

**Comment by snnn** [comment]
step 1. create an allocator
step 2.  create an ortvalue from the allocator OrtCreateTensorAsOrtValue
step 3: get the data pointer: OrtGetTensorMutableData
step 4: fill in the data: memcpy(....)
