### ISSUE TITLE
[Build] CPU + CUDA build installing pip python wheel from source extremelly slow during the inference 

### ISSUE THREAD

**Issue by Apisteftos** [microsoft/onnxruntime#17186]
### Describe the issue

I built the CPU and CUDA from source and they are behaving not normal. During the inference CPU takes 10 time more time to run and CUDA takes the 2 or 3 times more. Is something I missing from the commands? The `requirements.txt` is also ok.

### Target platform

CUDA, CPU

### Build script

I am using the command 

CPU:
===

```
./build.sh --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --enable_pybind --build_wheel --update --build
````

GPU:
===

```
./build.sh --use_cuda --cudnn_home /usr/local/cuda/lib64/ --cuda_home /usr/local/cuda --enable_pybind --build_wheel  --update --build --parallel --skip_tests
```

Onnxruntime Version
==============

1.16.0

### Error / output

I am not getting any error, it compiles normally the files.

### Visual Studio Version

1.81.0

### GCC / Compiler Version

9.4.0

**Comment by snnn** [comment]
It looks all good to me.

**Comment by snnn** [comment]
You may upgrade your GCC to a newer version. Our official packages were built with GCC  11.  And we will drop the support for GCC 9 soon. However, I cannot anticipate how much perf gain it will bring.

**Comment by Apisteftos** [comment]
> You may upgrade your GCC to a newer version. Our official packages were built with GCC 11. And we will drop the support for GCC 9 soon. However, I cannot anticipate how much perf gain it will bring.

I did some modifications on the [qlinearconv.cc](https://github.com/microsoft/onnxruntime/blob/66df11769c127565dcd17a715b2e08b3bffd9eee/onnxruntime/core/providers/cpu/quantization/qlinearconv.cc#L364) file for the CPU to get the  `kernel filter`, the `weight` from the profiling data to measure the performance of the QLinearConv. I am doing my thesis and it's the only layer that I can not measure the Performance - MACS and throughput TFLOPs layerwise. There is no other option to get the weight data from the layer. I made this flag  ` is_packed = false;` true but it seems It packs the data to the layer and then an error occured. So I did some other modifications which seems to had an influence on the performance.

You cannot measure the performance of the layer if you don't have any profiling data. Is anyhow to get the weights from the profiling data?

**Comment by snnn** [comment]
ONNX Runtime is open source. As you already know how to build it from source, please feel free to modify it. You can add a few lines of code in qlinearconv.cc to dump the data out.

**Comment by snnn** [comment]
Also, we have a benchmark framework. You can add your benchmark in https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/test/onnx/microbenchmark. Be sure to run your test enough times to get a more stable result.

**Comment by Apisteftos** [comment]
> Also, we have a benchmark framework. You can add your benchmark in https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/test/onnx/microbenchmark. Be sure to run your test enough times to get a more stable result.

The problem is that my work is in python language and I have to do benchmarking using the profiling data, to estimate the MACS, throughput per layer, runtime, etc. The framework does not need to profile unused events like this: 

- main_thread
- thread_pool_name
- thread_id
- WaitRevoke
- num_run
- core
- etc

Important for profiling and benchmarking are input - output data, node_index (which has a really big problem), duration and op_name and that's it.

I tried to modify the code in `qlinearconv.cc` which worked but it yields more runtime as it should, but how can I debug it and find something?

**Comment by snnn** [comment]
If I know how to make it code run faster, I wouldn't stop trying to make a PR.  Sorry it is beyond of what I can help.
