### ISSUE TITLE
[Build] NETSDK1206 warning when running on .NET 8 preview 7

### ISSUE THREAD

**Issue by timmydo** [microsoft/onnxruntime#17180]
### Describe the issue

Building with:

```
<PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.15.1" />
```

### Urgency

Ideally, we don't have to disable this warning to ship the latest .NET preview version, because these warnings cover up other issues and oftentimes people forget to remove the ignored warnings.

### Target platform

windows/linux

### Build script

msbuild

### Error / output

```
1>C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(267,5): warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): osx.10.14-arm64, osx.10.14-x64. Affected libraries: Microsoft.ML.OnnxRuntime. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.
```

### Visual Studio Version

17.8

### GCC / Compiler Version

n/a

**Comment by snnn** [comment]
Do you know what rid should we use?

**Comment by agocke** [comment]
Just `osx-x64` and `osx-arm64`. Basically, drop the version numbers from your OS specifiers and everything will be fine.
