### ISSUE TITLE
[Build] Cross Compiling on Linux to Android: CMake Error at download-onnx-populate.cmake:170

### ISSUE THREAD

**Issue by Erica-Liu** [microsoft/onnxruntime#17181]
### Describe the issue

I am cross compiling on Linux to Android target, reference: https://onnxruntime.ai/docs/build/android.html#android-build-instructions.
During the execution of `build.sh`,  when
 ```
[ 11%] Creating directories for 'onnx-populate'
[ 22%] Performing download step (download, verify and extract) for 'onnx-populate'
```

the download of `https://github.com/onnx/onnx/archive/refs/heads/rel-1.14.1.zip` failed in a row with error `SHA1 hash does not match expected value`.

**version configuration:**
Android NDK: 21.1.6352462
Android SDK: 33.0.0
Android API: 34
Cmake: 3.27.0

### Urgency

Urgent

### Target platform

android arm64-v8a

### Build script

./build.sh --android --android_sdk_path /usr/local/google/home/ericaliuuu/Android/Sdk --android_ndk_path /usr/local/google/home/ericaliuuu/Android/Sdk/ndk/21.1.6352462 --android_abi arm64-v8a --android_api 27

### Error / output

......
-- Build files have been written to: /usr/local/google/home/ericaliuuu/Repo/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-subbuild
[ 11%] Creating directories for 'onnx-populate'
[ 22%] Performing download step (download, verify and extract) for 'onnx-populate'
-- Downloading...
   dst='/usr/local/google/home/ericaliuuu/Repo/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-subbuild/onnx-populate-prefix/src/rel-1.14.1.zip'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/onnx/onnx/archive/refs/heads/rel-1.14.1.zip'
-- verifying file...
       file='/usr/local/google/home/ericaliuuu/Repo/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-subbuild/onnx-populate-prefix/src/rel-1.14.1.zip'
-- SHA1 hash of
    /usr/local/google/home/ericaliuuu/Repo/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-subbuild/onnx-populate-prefix/src/rel-1.14.1.zip
  does not match expected value
    expected: '5d2e5421f522d93c783c9bd523c2776927bcff5b'
      actual: 'de77bfb36afe23d4dbd39e719d0acfa6b19d7f18'
-- Hash mismatch, removing...
-- Using src='https://github.com/onnx/onnx/archive/refs/heads/rel-1.14.1.zip'
-- verifying file...
       file='/usr/local/google/home/ericaliuuu/Repo/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-subbuild/onnx-populate-prefix/src/rel-1.14.1.zip'
-- SHA1 hash of
    /usr/local/google/home/ericaliuuu/Repo/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-subbuild/onnx-populate-prefix/src/rel-1.14.1.zip
  does not match expected value
    expected: '5d2e5421f522d93c783c9bd523c2776927bcff5b'
      actual: 'de77bfb36afe23d4dbd39e719d0acfa6b19d7f18'
-- Hash mismatch, removing...
-- Using src='https://github.com/onnx/onnx/archive/refs/heads/rel-1.14.1.zip'
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 10% complete]
-- [download 21% complete]
-- [download 32% complete]
-- [download 38% complete]
-- [download 49% complete]
-- [download 59% complete]
-- [download 68% complete]
-- [download 77% complete]
-- [download 86% complete]
-- [download 98% complete]
-- [download 100% complete]
-- verifying file...
       file='/usr/local/google/home/ericaliuuu/Repo/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-subbuild/onnx-populate-prefix/src/rel-1.14.1.zip'
-- SHA1 hash of
    /usr/local/google/home/ericaliuuu/Repo/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-subbuild/onnx-populate-prefix/src/rel-1.14.1.zip
  does not match expected value
    expected: '5d2e5421f522d93c783c9bd523c2776927bcff5b'
      actual: 'de77bfb36afe23d4dbd39e719d0acfa6b19d7f18'
-- Hash mismatch, removing...
- Using src='https://github.com/onnx/onnx/archive/refs/heads/rel-1.14.1.zip'
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 11% complete]
-- [download 21% complete]
-- [download 33% complete]
-- [download 35% complete]
-- [download 46% complete]
-- [download 50% complete]
-- [download 61% complete]
-- [download 71% complete]
-- [download 73% complete]
-- [download 77% complete]
-- [download 89% complete]
-- [download 96% complete]
-- [download 100% complete]
-- verifying file...
       file='/usr/local/google/home/ericaliuuu/Repo/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-subbuild/onnx-populate-prefix/src/rel-1.14.1.zip'
-- SHA1 hash of
    /usr/local/google/home/ericaliuuu/Repo/onnxruntime/build/Linux/RelWithDebInfo/_deps/onnx-subbuild/onnx-populate-prefix/src/rel-1.14.1.zip
  does not match expected value
    expected: '5d2e5421f522d93c783c9bd523c2776927bcff5b'
      actual: 'de77bfb36afe23d4dbd39e719d0acfa6b19d7f18'
-- Hash mismatch, removing...
CMake Error at onnx-subbuild/onnx-populate-prefix/src/onnx-populate-stamp/download-onnx-populate.cmake:170 (message):
  Each download failed!

    
    

gmake[2]: *** [CMakeFiles/onnx-populate.dir/build.make:100: onnx-populate-prefix/src/onnx-populate-stamp/onnx-populate-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/onnx-populate.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
CMake Error at /usr/local/share/cmake-3.27/Modules/FetchContent.cmake:1662 (message):
  Build step for onnx failed: 2
Call Stack (most recent call first):
  /usr/local/share/cmake-3.27/Modules/FetchContent.cmake:1802:EVAL:2 (__FetchContent_directPopulate)
  /usr/local/share/cmake-3.27/Modules/FetchContent.cmake:1802 (cmake_language)
  external/helper_functions.cmake:139 (FetchContent_Populate)
  external/onnxruntime_external_deps.cmake:432 (onnxruntime_fetchcontent_makeavailable)
  CMakeLists.txt:559 (include)

-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/usr/local/google/home/ericaliuuu/Repo/onnxruntime/tools/ci_build/build.py", line 2636, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/google/home/ericaliuuu/Repo/onnxruntime/tools/ci_build/build.py", line 2494, in main
    generate_build_tree(
  File "/usr/local/google/home/ericaliuuu/Repo/onnxruntime/tools/ci_build/build.py", line 1375, in generate_build_tree
    run_subprocess(
  File "/usr/local/google/home/ericaliuuu/Repo/onnxruntime/tools/ci_build/build.py", line 789, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/ericaliuuu/Repo/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '/usr/local/google/home/ericaliuuu/Repo/onnxruntime/cmake', '--compile-no-warning-as-error', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-DPython_EXECUTABLE=/usr/bin/python3', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-Donnxruntime_USE_MIMALLOC=OFF', '-Donnxruntime_ENABLE_PYTHON=OFF', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_JAVA=OFF', '-Donnxruntime_BUILD_NODEJS=OFF', '-Donnxruntime_BUILD_OBJC=OFF', '-Donnxruntime_BUILD_SHARED_LIB=ON', '-Donnxruntime_BUILD_APPLE_FRAMEWORK=OFF', '-Donnxruntime_USE_DNNL=OFF', '-Donnxruntime_USE_NNAPI_BUILTIN=OFF', '-Donnxruntime_USE_RKNPU=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_VITISAI=OFF', '-Donnxruntime_USE_TENSORRT=OFF', '-Donnxruntime_USE_TENSORRT_BUILTIN_PARSER=ON', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_TVM_CUDA_RUNTIME=OFF', '-Donnxruntime_TVM_USE_HASH=OFF', '-Donnxruntime_USE_MIGRAPHX=OFF', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_DISABLE_ML_OPS=OFF', '-Donnxruntime_DISABLE_RTTI=OFF', '-Donnxruntime_DISABLE_EXCEPTIONS=OFF', '-Donnxruntime_MINIMAL_BUILD=OFF', '-Donnxruntime_EXTENDED_MINIMAL_BUILD=OFF', '-Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF', '-Donnxruntime_REDUCED_OPS_BUILD=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=OFF', '-Donnxruntime_USE_WINML=OFF', '-Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxruntime_USE_ACL=OFF', '-Donnxruntime_USE_ACL_1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_USE_ACL_2002=OFF', '-Donnxruntime_USE_ARMNN=OFF', '-Donnxruntime_ARMNN_RELU_USE_CPU=ON', '-Donnxruntime_ARMNN_BN_USE_CPU=ON', '-Donnxruntime_USE_JSEP=OFF', '-Donnxruntime_ENABLE_NVTX_PROFILE=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_ENABLE_TRAINING_OPS=OFF', '-Donnxruntime_ENABLE_TRAINING_APIS=OFF', '-Donnxruntime_ENABLE_CPU_FP16_OPS=OFF', '-Donnxruntime_USE_NCCL=OFF', '-Donnxruntime_BUILD_BENCHMARKS=OFF', '-Donnxruntime_USE_ROCM=OFF', '-DOnnxruntime_GCOV_COVERAGE=OFF', '-Donnxruntime_USE_MPI=OFF', '-Donnxruntime_ENABLE_MEMORY_PROFILE=OFF', '-Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF', '-Donnxruntime_BUILD_WEBASSEMBLY_STATIC_LIB=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING=ON', '-Donnxruntime_ENABLE_WEBASSEMBLY_API_EXCEPTION_CATCHING=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_THROWING=ON', '-Donnxruntime_WEBASSEMBLY_RUN_TESTS_IN_BROWSER=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_PROFILING=OFF', '-Donnxruntime_ENABLE_LAZY_TENSOR=OFF', '-Donnxruntime_ENABLE_EXTERNAL_CUSTOM_OP_SCHEMAS=OFF', '-Donnxruntime_ENABLE_CUDA_PROFILING=OFF', '-Donnxruntime_ENABLE_ROCM_PROFILING=OFF', '-Donnxruntime_USE_XNNPACK=OFF', '-Donnxruntime_USE_WEBNN=OFF', '-Donnxruntime_USE_CANN=OFF', '-Donnxruntime_USE_TRITON_KERNEL=OFF', '-Donnxruntime_DISABLE_FLOAT8_TYPES=OFF', '-DCMAKE_TLS_VERIFY=ON', '-DFETCHCONTENT_QUIET=OFF', '-Donnxruntime_ENABLE_MEMLEAK_CHECKER=OFF', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_PREFIX_PATH=/usr/local/google/home/ericaliuuu/Repo/onnxruntime/build/Linux/RelWithDebInfo/installed']' returned non-zero exit status 1.

### GCC / Compiler Version

CMAKE 3.27.0

**Comment by snnn** [comment]
We should have fixed it.

**Comment by snnn** [comment]
Feel free to reopen it if the problem still exist.
