### ISSUE TITLE
Output shape of resize op is not correct.

### ISSUE THREAD

**Issue by linkerzhang** [microsoft/onnxruntime#1719]
refer to issue reported in ONNX https://github.com/onnx/onnx/issues/2267.

**Comment by hariharans29** [comment]
Hi @cjt222,

1) Can you attach your py script from the original issue? It is hard to re-write the script from a  screenshot. And I need to script to try and repro.

2) Also, this is a vanilla test case for Resize op. I am surprised it is failing. I think there must be some other issue that isn't easily visible. Please provide these details to investigate further - 
   Which version of ORT are you using? 
   Is it the CPU or GPU package? 
   And which platform are you running the script ? 

Thanks

**Comment by hariharans29** [comment]
Hi @cjt222,

Were you able to resolve this ?

Thanks!

**Comment by hariharans29** [comment]
Closing this as this seems to be an artifact of local environment issue. 

This is a vanilla use-case for the Resize op and there are unit tests covering a very similar case (the only change is the raw data involved) - https://github.com/microsoft/onnxruntime/blob/6a5b11756b85c3324f4bae47be3dcb61167a6a06/onnxruntime/test/providers/cpu/tensor/resize_op_test.cc#L50.

If you haven't resolved this, please re-open with the *.py script attached that we can use to re-pro.

Thanks!
