### ISSUE TITLE
[Build] downloaded dependancies during build process

### ISSUE THREAD

**Issue by dandlake** [microsoft/onnxruntime#17199]
### Describe the issue

I am trying to build onnxruntime in an isolated environment. The build failed when trying to download some external dependancies, like eigen. 

Is there a list of such dependancies? and is there a way we can build with these dependancies pre-downloaded/installed? 

On a centos8 machine with normal internet access, I can build.

### Target platform

centos8

### Build script

./build.sh --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync

### Error / output

[ 33%] No update step for 'pytorch_cpuinfo-populate'
[ 44%] No patch step for 'pytorch_cpuinfo-populate'
[ 55%] No configure step for 'pytorch_cpuinfo-populate'
[ 66%] No build step for 'pytorch_cpuinfo-populate'
[ 77%] No install step for 'pytorch_cpuinfo-populate'
[ 88%] No test step for 'pytorch_cpuinfo-populate'
[100%] Completed 'pytorch_cpuinfo-populate'
[100%] Built target pytorch_cpuinfo-populate
gmake[1]: warning:  Clock skew detected.  Your build may be incomplete.
CMake Deprecation Warning at /usr/src/redhat/onnxruntime/build/Linux/RelWithDebInfo/_deps/pytorch_cpuinfo-src/deps/clog/CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Populating eigen
-- Configuring done (0.2s)
-- Generating done (0.1s)
-- Build files have been written to: /usr/src/redhat/onnxruntime/build/Linux/RelWithDebInfo/_deps/eigen-subbuild
[ 11%] Creating directories for 'eigen-populate'
[ 22%] Performing download step (download, verify and extract) for 'eigen-populate'
-- Downloading...
   dst='/usr/src/redhat/onnxruntime/build/Linux/RelWithDebInfo/_deps/eigen-subbuild/eigen-populate-prefix/src/eigen-d10b27fe37736d2944630ecd7557cefa95cf87c9.zip'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://gitlab.com/libeigen/eigen/-/archive/d10b27fe37736d2944630ecd7557cefa95cf87c9/eigen-d10b27fe37736d2944630ecd7557cefa95cf87c9.zip'
CMake Error at eigen-subbuild/eigen-populate-prefix/src/eigen-populate-stamp/download-eigen-populate.cmake:170 (message):
  Each download failed!

**Comment by snnn** [comment]
Download all the artifacts in cmake/deps.txt to somewhere, then use https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/replace_urls_in_deps.py to update the file.

**Comment by dandlake** [comment]
Thanks, @snnn . I tried this. Mostly working, but the build failed at the same place. This "eigen" is not listed in cmake/deps.txt. Any idea why? And how can I instruct the build to use it from a pre-downloaded file?

**Comment by dandlake** [comment]
Never mind. I am working on 1.15.1 code. Just saw that in the latest code, eigen is in the deps.txt. For 1.15.1 code, I modified cmake/external/eigen.cmake and it worked the same way.
