### ISSUE TITLE
Allow 64 bit floating point number types

### ISSUE THREAD

**Issue by Zuhaib-SB** [microsoft/onnxruntime#1720]
**Is your feature request related to a problem? Please describe.**
I've been using the onnx format to load in a model and generate predictions. One of the models given to me had "large" weight values with a lot of digits. This means that as the model performs calculations, the floating point rounding errors add up and can lead to outputs that differ from what is initially expected pre-export to onnx.

**Describe the solution you'd like**
Allow onnxruntime to support models which work with 64bit floats

**Describe alternatives you've considered**
Producing equivalent models with reduced weights. Reducing the size of weights reduces the rounding errors and is acceptable as a workaround.

**Comment by snnn** [comment]
Does the original one use float64 ?

**Comment by Zuhaib-SB** [comment]
That's correct, the original model is using float64. I was given some inputs and outputs from the original model and given an exported onnx version of the model. When I ran a test for the inputs and outputs I saw some deviations. From some trial and error investigations we discovered that the large weights of the model were probably the cause as they would probably contribute to rounding errors. As mentioned, reducing the weights of the model reduced the difference between onnxruntime output and the original model predictions generated in scikit. I believe supporting float64 would eliminate the rounding errors because it would be the same data type as supported with other model frameworks.

**Comment by snnn** [comment]
Would you please share me the converted model or give me a full list of ONNX operators it contains?

**Comment by Zuhaib-SB** [comment]
Hi, here's the chain of ONNX operators it contains in order.

-> float_input 1 x 19
-> Cast
-> MatMul 19 x 5
-> Add 1 x 5
-> Relu
-> MatMul 5 x 1
-> Add 1 x 1
-> Identity
-> Reshape
-> Variable 1 x 1 (output)

**Comment by Zuhaib-SB** [comment]
-> Cast
-> MatMul 19 x 5
-> Add 1 x 5
-> Relu
-> MatMul 5 x 1
-> Add 1 x 1
-> Identity
-> Reshape

Are all ONNX listed in the link you gave me. I think there was some confusion as the first and last elements in the prior list I gave you were just the names of the input and output variables. They're not operators and can be ignored.

So basically I need all of the operators listed in this post.
