### ISSUE TITLE
ONNX export for Pytorch ScriptModule including for loop and mixed types cannot be loaded in onnxruntime

### ISSUE THREAD

**Issue by julioasotodv** [microsoft/onnxruntime#1721]
**Describe the bug**
I'm posting this also here, as it comes from pytorch/pytorch#25251

Basically, it looks like if we want to export a Pytorch ScriptModule to onnx and the module includes both:

1. A for loop
2. More than one tensor data type (eg. float and long)

The exported ONNX file cannot be loaded with the ONNX runtime.

**System information**
- Both Mac OS 10.13 and Ubuntu 16.04
- ONNX Runtime installed from binary (conda install -c conda-forge onnx)
- ONNX Runtime version: 1.5.0
- Python version: 3.7.1
- CUDA/cuDNN version: None
- GPU model and memory: CPU

**To Reproduce**
```python
import torch

class DummyModule(torch.nn.Module):
    def __init__(self):
        super(DummyModule, self).__init__()
        
    def forward(self, x, y):
        for i in range(y.size(0)):
            x = x + i
        return x

# Instantiation and scripting
model_scripted = torch.jit.script(DummyModule())
dummy_input_one = torch.Tensor([1,2,3]).float()
dummy_input_two = torch.Tensor([4,5,6]).long()

# Check if the forward pass works:
output = model_scripted(dummy_input_one, dummy_input_two)
print(output)

# Export to onnx:
torch.onnx.export(model_scripted, 
                  (dummy_input_one, dummy_input_two), 
                  'loop.onnx', 
                  verbose=True,
                  input_names=['input_data', 'input_data_2'], 
                  example_outputs=output
                 )

# Load the model in onnx runtime:
import onnxruntime as rt

sess = rt.InferenceSession("loop.onnx")
```
Fails with:
```python
RuntimeError                              Traceback (most recent call last)
<ipython-input-145-2a18677141bc> in <module>
      1 import numpy as np
      2 import onnxruntime as rt
----> 3 sess = rt.InferenceSession("loop.onnx")
      4 
      5 input_ = sess.get_inputs()[0].name

~/anaconda3/envs/pytorch/lib/python3.6/site-packages/onnxruntime/capi/session.py in __init__(self, path_or_bytes, sess_options)
     27 
     28         if isinstance(path_or_bytes, str):
---> 29             self._sess.load_model(path_or_bytes)
     30         elif isinstance(path_or_bytes, bytes):
     31             self._sess.read_bytes(path_or_bytes)

RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from loop.onnx failed:[TypeInferenceError] Graph attribute inferencing failed: Type Error: Type parameter (T) bound to different types (tensor(float) and tensor(int64) in node ().
```

It turns out that this only occurs if the module uses more than one tensor data type. For instance: if everything inside the module (including arguments received by the forward pass) were torch.long, the exported onnx file is read just fine.

This means that in the example above, if we change the definition of `dummy_input_one` to:
```python
dummy_input_one = torch.Tensor([1,2,3]).long()
```
Everything works as expected.

**Expected behavior**
The ONNX runtime should allow for loops and mixed tensor types.

**Comment by TMVector** [comment]
*(I'm not an ONNX/ORT expert)*

You are adding the loop index (int64) to a float tensor, which in ONNX is not allowed, since both operands must be of the same type for the [Add](https://github.com/onnx/onnx/blob/master/docs/Operators.md#add) operator. I would expect you to get the same error without the loop, just adding an int64 to a float tensor -- is this the case?

I suspect that PyTorch should be inserting a [Cast](https://github.com/onnx/onnx/blob/master/docs/Operators.md#cast) node to make the operation valid, so perhaps raise an issue on the PyTorch repo.

**Comment by julioasotodv** [comment]
@TMVector Indeed, you are right. Torch jit should be the one raising an error when trying to add two tensors of different type.

It does work when I force input data types to be compatible in required operations.

We can close this issue.
