### ISSUE TITLE
GENERAL ERROR : Load model from tagger.onnx failed:Model input (data) does not have type information.

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#1726]
**Describe the bug**
Exported with PyTorch 1.2 and cannot load it in ORT 0.4

**Urgency**
Cannot export the new onnx model.
All current ORT runtimes are 0.4 so I would rather export something I can use in 0.4

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu16
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 0.4
- Python version: 3

**To Reproduce**

```python
sess = rt.InferenceSession(onnxfile)
```

**Expected behavior**
Load the model, or better error message

**Additional context**
Do I need to use ORT 0.5, or a way to export that I can use in 0.4?
All current ORT runtimes are 0.4 so I would rather export something I can use in 0.4

**Comment by dashesy** [comment]
This is the start of graph when exporting, clearly it is Byte:

```text
graph(%data : Byte(*, *, *, *)
```

**Comment by dashesy** [comment]
When I try ORT 0.5 I get slightly better error:

> RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from output/gr/hybrid_model_v2/tagger.onnx failed:This is an invalid model. Model input (data) does not have type information.


But that means PyTorch exporter has exported an invalid model, with an input that does not have type information!

**Comment by dashesy** [comment]
This is certainly a regression. Model exported with PyTorch 1.0 works and has correct type, but both PyTorch 1.1 and 1.2 export without type information and loading the model generated by 1.1 segfaults ORT

**Comment by faxu** [comment]
@spandantiwari @BowenBao  can you guys take a look at whether this is a pytorch issue?

**Comment by dashesy** [comment]
This is still an issue

```text
----> 1 sess = rt.InferenceSession(onnxfile)
      2 t0 = time.time()
      3 pred = sess.run(targets, {'data': blob})[0]
      4 print(time.time() - t0)

~/miniconda3/envs/py3/lib/python3.6/site-packages/onnxruntime/capi/session.py in __init__(self, path_or_bytes, sess_options)
     27
     28         if isinstance(path_or_bytes, str):
---> 29             self._sess.load_model(path_or_bytes)
     30         elif isinstance(path_or_bytes, bytes):
     31             self._sess.read_bytes(path_or_bytes)

RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from /mnt/output/gr/tagging/Tagging12K/Tagging12K.onnx failed:This is an invalid model. Model input (data) does not have type information.
```

I cannot export models that I used to be able to export
