### ISSUE TITLE
[Training] [On-device-training] Accuracy drop after retraining the model on device

### ISSUE THREAD

**Issue by ahlzouao** [microsoft/onnxruntime#17282]
### Describe the issue

Hello I'm noticing an accuracy drop after retraining the model on a Embedded Linux based aarch64 device. The model is the following: Input [batchx28x28] -> Reshape -> Linear(784, 128) -> ReLu -> Linear(128, 10) -> Output[batchx10]
I'm defining and training the model initially using PyTorch framework for 5 epochs and it reaches an accuracy around 87% which is enough for 5 Epochs. I'm using the AdamW optimizer, a learning rate of 0.001 and the FashionMNIST dataset for the training (trainset and testset for eval). Once the model is exported and the training artifacts are generated and deployed on the target, I'm retraining the model on the same dataset (trainset and testset) using the C++ Training API. After retraining the model on the device for 5 epochs, I notice some weird and suspicious values from the loss function (which is a **SoftmaxCrossEntropyLoss** as can be seen on Netron)
```
Batch # : 0 - Loss: 2.1988
Batch # : 1 - Loss: 0.0348519
Batch # : 2 - Loss: 0.00343899
Batch # : 3 - Loss: 0.00114358
Batch # : 4 - Loss: 0.000514077
Batch # : 5 - Loss: 0.000268483
Batch # : 6 - Loss: 0.00015353
Batch # : 7 - Loss: 9.41113e-05
Batch # : 8 - Loss: 6.10929e-05
Batch # : 9 - Loss: 4.17224e-05
Batch # : 10 - Loss: 2.95635e-05
Batch # : 11 - Loss: 2.17555e-05
...
Batch # : 59 - Loss: 9.53674e-07
Batch # : 60 - Loss: 12.2571       <------
Batch # : 61 - Loss: 1.13249e-06
Batch # : 62 - Loss: 1.3113e-06
...                                                     _Values of Loss around 3e-06_
Batch # : 99 - Loss: 4.17232e-06
Batch # : 100 - Loss: 8.5833         <-------
Batch # : 101 - Loss: 4.52994e-06
Batch # : 102 - Loss: 4.88757e-06
...                                                      _Values of Loss around 5e-06_
Batch # : 108 - Loss: 6.19886e-06
Batch # : 109 - Loss: 6.37768e-06
Batch # : 110 - Loss: 6.5529          <-----
Batch # : 111 - Loss: 7.51016e-06
...
...
Batch # : 2907 - Loss: 1.85369e-05
Batch # : 2908 - Loss: 2.60137      <------
Batch # : 2909 - Loss: 1.4305e-05
Batch # : 2911 - Loss: 1.30533e-05
...
Batch # : 2998 - Loss: 9.95393e-06
Batch # : 2999 - Loss: 9.83472e-06
```
Besides, I notice a hug accuracy drop after the end of the training on device and while evaluating the model. The final accuracy is around 11%. I have several questions:
1. Do you think the low values of the loss functions are normal ? Can you explain why we are observing Loss around e-06 ?
2. How do you interpret having a high loss value from time to time during the same epoch ? Is this really the loss value that should be taken into account ?
3. How do you explain the accuracy drop between the Offline and the Online phases ? I made sure to have the exact same preprocessing between the 2 phases and even compared the values of the first batch images since I am using the same dataset.  

## 1. Offline Phase:
For defining the model and training it initially on the host and then export it along with the training artifacts as the offline phase please use the following [Google Colab Notebook.](https://colab.research.google.com/drive/1IlHfFRghFNNBTfOPGZ1q1XJjii8UVZ5T?usp=sharing)

## 2. Online phase (On-device-training) using C++ API:
For the online training, the same learning rate as previously (0.001), the same loss function (SoftmaxCrossEntory) and the same Optimizer (AdamW) has been used.
```

int RunTraining(const TrainingParams& params) {

    //Initializing training_dataset
	auto train_dataset = MNISTDataset(NUM_TRAIN_SAMPLES,
                           params.train_data_dir + "train-images-idx3-ubyte",
                           params.train_data_dir + "train-labels-idx1-ubyte");


	auto test_dataset = MNISTDataset(NUM_TEST_SAMPLES,
                           params.test_data_dir + "t10k-images-idx3-ubyte",
                           params.test_data_dir + "t10k-labels-idx1-ubyte");

    // Create Env
    OrtThreadingOptions* threading_options = nullptr;
    Ort::Env env(threading_options, ORT_LOGGING_LEVEL_WARNING, "log");

    // Load Checkpoint state
    Ort::CheckpointState checkpoint_state = Ort::CheckpointState::LoadCheckpoint("./training_artifacts/checkpoint/");

    // Create TrainingSession
    Ort::SessionOptions session_options;
    Ort::TrainingSession session(env, session_options, checkpoint_state,
                                "./training_artifacts/training_model.onnx",
                                "./training_artifacts/eval_model.onnx",
                                "./training_artifacts/optimizer_model.onnx");

    session.SetLearningRate(params.learning_rate);

    unsigned int train_sample_count = train_dataset.num_samples;
    unsigned int test_sample_count = test_dataset.num_samples;
    int64_t num_test_batches = test_sample_count / params.eval_batch_size;

    std::cout << "Initialization of training session completed." << std::endl;
    const std::vector<int64_t> x_train_shape({params.train_batch_size, train_dataset.num_rows, train_dataset.num_cols});
    const std::vector<int64_t> y_train_shape({params.train_batch_size});

    const std::vector<int64_t> x_eval_shape({params.eval_batch_size, train_dataset.num_rows, train_dataset.num_cols});
    const std::vector<int64_t> y_eval_shape({params.eval_batch_size});

    size_t input_size{1};
    size_t label_size{1};
    for (auto i : x_train_shape) {
        input_size *= i;
    }
    for (auto l : y_train_shape) {
        label_size *= l;
    }

    // Starting the Training loop by iterating over the epoch and then over the batches
    auto end_to_end_start = std::chrono::high_resolution_clock::now();

    for (int64_t epoch = 0, batch_idx = 0; epoch < params.num_train_epochs; ++epoch) {
        for (size_t step_in_cur_epoch = 0; step_in_cur_epoch < num_train_batches; ++step_in_cur_epoch) {
            float loss = 0.0;

            float *x_data{ new float[input_size]{}};
            int64_t *y_data{ new int64_t[label_size]{}};

            unsigned int current_idx = train_dataset.idxes.at(train_dataset.count);
            train_dataset.count++;
            train_dataset.ReadData(x_data, y_data, current_idx, params.train_batch_size);

            //auto loss = Train(session, x_data, y_data, x_train_shape, y_train_shape);
            Ort::MemoryInfo memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);

            std::vector<Ort::Value> train_inputs; // {inputs, labels}

            // Inputs batch
            for (int i = 0; i < input_size; i++){
                x_data[i] =float(float(x_data[i] - 0.1307f) / 0.3081f);
            }
            train_inputs.emplace_back(Ort::Value::CreateTensor(memory_info, x_data, input_size * sizeof(float),
                                                                x_train_shape.data(), x_train_shape.size(),
                                                                ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT));
            // Labels batch
            train_inputs.emplace_back(Ort::Value::CreateTensor(memory_info, y_data, label_size * sizeof(int64_t),
                                                                y_train_shape.data(), y_train_shape.size(),
                                                                ONNX_TENSOR_ELEMENT_DATA_TYPE_INT64));


            // Run the train step and execute the forward + loss + backward.
            loss = *(session.TrainStep(train_inputs).front().GetTensorMutableData<float>());
            std::cout << "Batch # : " << batch_idx << " - Loss: " << loss << std::endl;

            // Gradient accumulation steps completed.
            if ((batch_idx + 1) % params.grad_accu_steps == 0) {
                // Update the model parameters by taking a step in the direction of the gradients computed above.
                session.OptimizerStep();
                // Reset the gradients now that the parameters have been updated.
                // New set of gradients can then be computed for the next round of inputs.
                session.LazyResetGrad();
            }

            if ((batch_idx + 1) % params.checkpoint_interval == 0){
                std::ostringstream oss;
                oss << "ckpt_" << params.model_name << "_" << std::to_string(batch_idx);
                std::string ckpt_file = oss.str();
                Ort::CheckpointState::SaveCheckpoint(checkpoint_state, ckpt_file);
            }

            if ((batch_idx + 1) % params.eval_interval == 0){
                std::cout << "Batch # : " << batch_idx << " ----- Model evaluation ..." << std::endl;
                for (size_t step_in_cur_epoch = 0; step_in_cur_epoch < num_test_batches; ++step_in_cur_epoch) {
                    float eval_loss = 0.0;
                    float *x_data_val{ new float[input_size]{}};
                    int64_t *y_data_val{ new int64_t[label_size]{}};

                    unsigned int current_idx = test_dataset.idxes.at(test_dataset.count);
                    test_dataset.count++;
                    test_dataset.ReadData(x_data_val, y_data_val, current_idx, params.eval_batch_size);

                    //auto loss = Train(session, x_data, y_data, x_train_shape, y_train_shape);
                    Ort::MemoryInfo memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
                    std::vector<Ort::Value> eval_inputs; // {inputs, labels}

                    //float*  in_val{ new float[input_size]{}};
                    /*if (floating_point) { */
                    for (int i = 0; i < input_size; i++){
                        x_data_val[i] =float(float(x_data_val[i] - params.input_mean) / params.input_std);
                    }

                    // Inputs batch
                    eval_inputs.emplace_back(Ort::Value::CreateTensor(memory_info, x_data_val, input_size * sizeof(float),
                                                                        x_eval_shape.data(), x_eval_shape.size(),
                                                                        ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT));

                    // Labels batch
                    eval_inputs.emplace_back(Ort::Value::CreateTensor(memory_info, y_data_val, label_size * sizeof(int64_t),
                                                                        y_eval_shape.data(), y_eval_shape.size(),
                                                                        ONNX_TENSOR_ELEMENT_DATA_TYPE_INT64));

                    // Run the train step and execute the forward + loss + backward.
                    eval_loss = *(session.EvalStep(eval_inputs).front().GetTensorMutableData<float>());
                    std::cout << " ------- Evaluating Model # Loss: " << eval_loss << " ------- " <<std::endl;
                    delete[] x_data_val;
                    delete[] y_data_val;
                    //delete[] in_val;
                }
            }
            delete[] x_data;
            delete[] y_data;
            //delete[] in;
            batch_idx++;
        }

        train_dataset.ResetIterateIndex();
        test_dataset.ResetIterateIndex();
    }
    // Save trained weights
    std::ostringstream oss;
    oss << "ckpt_" << params.model_name;
    std::string ckpt_file = oss.str();
    Ort::CheckpointState::SaveCheckpoint(checkpoint_state, ckpt_file);

    auto end = std::chrono::high_resolution_clock::now();
    std::chrono::duration<double> duration_seconds = end - end_to_end_start;
    double stabilized_total_end_to_end_time = duration_seconds.count();

    std::cout << "Training completed - end to end latency: " << stabilized_total_end_to_end_time << "(s)" << std::endl;
    std::vector<std::string> graph_output_names({"output"});

    session.ExportModelForInferencing(params.output_model, graph_output_names);

    return 0;
}

int main(int argc, char* argv[]){
    TrainingParams params;
    ProcessArguments(argc, argv, params);
    RunTraining(params);
}
```

### Urgency

I have been blocked on this issue for weeks, I have checked every single parameters and even used a minimalist model to investigate this accuracy drop. Any help or guidance would be so much appreciated.

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

fd6ecc3909ab1a371cf4d8c94e16957e3fcc0f84

### PyTorch Version

2.0.1+cu118

### Execution Provider

Default CPU

**Comment by baijumeswani** [comment]
@ahlzouao thanks for opening this issue. I tried to reproduce this issue by using our python api first. Unfortunately, I was not able to reproduce this yet.

My python code tried to recreate the pytorch training script line by line: https://gist.github.com/baijumeswani/a2f441f52160bbae03fe3eee4f8eefdf

The result is very similar with PyTorch:

```
Epoch1:
Test set: Average loss: 0.0004, Accuracy: 8484/10000 (85%)
Epoch2:
Test set: Average loss: 0.0004, Accuracy: 8564/10000 (86%)
Epoch3:
Test set: Average loss: 0.0004, Accuracy: 8639/10000 (86%)
Epoch4:
Test set: Average loss: 0.0004, Accuracy: 8684/10000 (87%)
Epoch5:
Test set: Average loss: 0.0004, Accuracy: 8697/10000 (87%)
```

A few things to note:

1. Try to export the model before you being training in PyTorch. Otherwise the exported model will already be trained. And retraining with ORT may not add value (unless it is for personalization).
2. The loss in the `train` function applies `softmax` and then applies `cross_entropy`. As can be noted in the [PyTorch documentation](https://pytorch.org/docs/stable/generated/torch.nn.CrossEntropyLoss.html), the `F.cross_entropy` is a combination of LogSoftmax and NLLLoss. You probably do not need the softmax here. Removing the softmax there, will result in similar loss values compared to onnx runtime.
3. The loss in the test method is using `reduction="sum"`. While this is fine, it is not the exact same as compared to onnx runtime which uses `reduction="mean"` by default.

The values you do look a little weird to me and I am not sure what the root cause of the problem is yet.

Next, I will try to run this set up in C++ to see if this is something that could be due to language bindings (unlikely, but worth a shot). Let me know if there are any other questions in the mean time.

**Comment by ahlzouao** [comment]
Hello @baijumeswani,
Thank you for your support, the example you provided on python seems to be working smoothly with the onnxruntime-training python module. 
Did you find anytime to dig a little bit deeper in C++ APIs ? Have you found anything that might go wrong ?

**Comment by baijumeswani** [comment]
I tried writing the fashion mnist example in C++. You can find the code [here](https://gist.github.com/baijumeswani/287baec9e3689572bf07efbcc2d55946). Please pardon the unclean code and hard coded values, I wrote this fairly quickly.

I used the mnist reader so I wouldn't need to write code to read the data (https://github.com/wichtounet/mnist).

I did not find anything out of the normal. My results:

```
Epoch: 0 Training Loss: 0.462639 Test Accuracy: 84.48
Epoch: 1 Training Loss: 0.347511 Test Accuracy: 85.27
Epoch: 2 Training Loss: 0.311706 Test Accuracy: 86.37
Epoch: 3 Training Loss: 0.288171 Test Accuracy: 86.52
Epoch: 4 Training Loss: 0.271634 Test Accuracy: 87.01
```

**Comment by ahlzouao** [comment]
Hello  @baijumeswani,
I tried reproducing the fashion mnist example with the [code](https://gist.github.com/baijumeswani/33132b100d3a33ef8356b907a6198c12) you provided, with the same model artifacts generated from this google colab and it gave me different output: 
```
terminate called after throwing an instance of 'Ort::Exception'
  what():  /usr/src/debug/onnxruntime/1.15.0+gitAUTOINC+638146b79e-r0/orttraining/orttraining/training_api/module.cc:469 onnxruntime::common::Status onnxruntime::training::api::Module::EvalStep(const std::vector<OrtValue>&, std::vector<OrtValue>&) [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Output vector incorrectly sized: output_names.size(): 2p_fetches->size(): 1
```
I assume it is because of the following lines while saving the eval_model.onnx
```
eval_model = onnx.load(f"training_artifacts/eval_model.onnx")
eval_model.graph.output.append(onnx_model.graph.output[0])
onnx.save(eval_model, f"training_artifacts/eval_model.onnx")
```
So after removing that additional output node from the eval graph, the training runs effectively but the accuracy is not good, the output is the following:
```
Epoch: 0 Training Loss: 0.462883 Test Accuracy: 10.16
Epoch: 1 Training Loss: 0.347774 Test Accuracy: 10.18
Epoch: 2 Training Loss: 0.31059 Test Accuracy: 10.09
Epoch: 3 Training Loss: 0.286103 Test Accuracy: 10.22
Epoch: 4 Training Loss: 0.266529 Test Accuracy: 10.2
```

Do you have any hints ?
Thank you for your help,

**Comment by baijumeswani** [comment]
The second output is needed to get the logits to compute the accuracy. How do you compute the accuracy without the second output in the eval model?

**Comment by ahlzouao** [comment]
Hello @baijumeswani

In my interpretation is that in the second output of the eval model, is it using the loss values as outputs of the model, and since it is always below 1, it is rounding up to the same value (probably 0) which explains the 10% accuracy out of 10 classes. 

Do you have any ideas about the `INVALID_ARGUMENT : Output vector incorrectly sized: output_names.size(): 2p_fetches->size(): 1` error ? 

Thank you,

**Comment by baijumeswani** [comment]
> Hello @baijumeswani
> 
> In my interpretation is that in the second output of the eval model, is it using the loss values as outputs of the model, and since it is always below 1, it is rounding up to the same value (probably 0) which explains the 10% accuracy out of 10 classes.
> 
> Do you have any ideas about the `INVALID_ARGUMENT : Output vector incorrectly sized: output_names.size(): 2p_fetches->size(): 1` error ?
> 
> Thank you,

Hi, sorry for this. There was a bug that was identified and addressed in this PR: https://github.com/microsoft/onnxruntime/pull/17331

Are you able to either build from source, or update that one line in that file locally on your end?

**Comment by ahlzouao** [comment]
Hello @baijumeswani,
Yes I have been able to build from source and apply the patch locally on my end, it is solving my problem. Concerning the training, I'm getting the same results as you on my device. Your help has been so much appreciated, thank you so much !

**Comment by zirid** [comment]
Hello  @baijumeswani ,

I tried your code using the files generated by the google colab file provided by  @ahlzouao  . But since I am on windows, I had to make a small modification: 

`void test_trainer() {
    Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");

    std::wstring checkpoint_path =    L"D:\\data\\checkpoint";
    std::string  training_model =      "D:\\data\\training_model.onnx";
    std::string  eval_model =             "D:\\data\\eval_model.onnx";
    std::string  optimizer_model =     "D:\\data\\optimizer_model.onnx";

    Ort::CheckpointState checkpoint = Ort::CheckpointState::LoadCheckpoint(checkpoint_path);

    /*Create Enference session using model path*/
#ifdef _WIN32
    std::wstring w_train_modelPath = charToWstring(training_model.c_str());
    std::wstring w_eval_modelPath = charToWstring(eval_model.c_str());
    std::wstring w_optimzer_modelPath = charToWstring(optimizer_model.c_str());
    Ort::TrainingSession session(env, Ort::SessionOptions(), checkpoint, w_train_modelPath, w_eval_modelPath, w_optimzer_modelPath);
#else
    Ort::TrainingSession session(env, Ort::SessionOptions(), checkpoint, training_model, eval_model, optimizer_model);
#endif

    mnist::MNIST_dataset<std::vector, std::vector<uint8_t>, uint8_t> dataset =mnist::read_dataset<std::vector, std::vector, uint8_t, uint8_t>("D:\\data\\f_minst_dataset");

    const size_t batch_size = 4;
    const size_t test_batch_size = 100;
    auto training_dataset = batchify(dataset.training_images, batch_size, dataset.training_labels);
    auto test_dataset = batchify(dataset.test_images, test_batch_size, dataset.test_labels);

    const size_t num_epochs = 5;

    for (size_t epoch = 0; epoch < num_epochs; ++epoch) {
        const auto training_loss = train(session, training_dataset, batch_size);
        const auto accuracy = test(session, test_dataset, test_batch_size);
        std::cout << "Epoch: " << epoch << " Training Loss: " << training_loss
            << " Test Accuracy: " << accuracy * 100 << std::endl;
    }
}`

I am getting ORT_RUNTIME_EXCEPTION error when initializing the session (  Ort::TrainingSession session( ....) ) .

Do you have any hints?

Thank you.
