### ISSUE TITLE
[ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for AveragePool(19)

### ISSUE THREAD

**Issue by arielpodlubne** [microsoft/onnxruntime#17299]
### Describe the issue

Hi, 

I am trying to run inference on every node of a large model. I already have each node as a .onnx. To test the issue here, I generate one with random but when I run the code code, I get the following error:
`onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for AveragePool(19) node with name 'average_pool_node'`

Is this an issue with my .onnx model or it is really not implemented for AveragePool? The same happens with Reshape.

Thanks

### To reproduce

```
import onnx
from onnx import helper
import onnxruntime

# Create input tensor shape
input_shape = [1, 3, 224, 224]  # Assuming 1 batch, 3 channels, 224x224 input

# Create input value info
input_value_info = helper.make_tensor_value_info("input", onnx.TensorProto.FLOAT, input_shape)

# Create AveragePool node with a name
node = helper.make_node(
    "AveragePool",                # Node type
    inputs=["input"],             # Input name
    outputs=["output"],           # Output name
    kernel_shape=[3, 3],          # Kernel size
    strides=[2, 2],               # Strides
    pads=[1, 1, 1, 1],            # Padding (assuming "same" padding)
    name="average_pool_node"      # Node name
)

# Create graph with the node
graph_def = helper.make_graph(
    [node],                       # Nodes
    "test_graph",                 # Graph name
    [input_value_info],           # Inputs
    [helper.make_tensor_value_info("output", onnx.TensorProto.FLOAT, None)],  # Outputs
)

# Create model with the graph
model_def = helper.make_model(graph_def, producer_name="average_pool_model")

# Save the model
onnx.save(model_def, "average_pool_model.onnx")

# Inference Session
ort_session = onnxruntime.InferenceSession("average_pool_model.onnx")
```

### Platform

Linux

### OS Version

Ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

ONNX Runtime version: 1.15.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by mszhanyi** [comment]
Did you install the latest onnx (1.14).

Please use onnx 1.13.  `pip install onnx=1.13`

In my mind, onnxruntime 1.15.1 doesn't support onnx 1.14 (opset 18).
The upcoming onnxruntime 1.16 will do.

**Comment by arielpodlubne** [comment]
Hi @mszhanyi mszhanyi 

```
$ pip3 list | grep onnx
onnx                   1.14.0
onnxruntime            1.15.1
```
I would rather not downgrade to onnix 1.13.
Can you explain what `, opset_imports=[helper.make_opsetid("", 18)]` does? What is that 18? I assume that changes based on other op_types ? I ask this because that was the one that failed, but if I have a "Conv" layer, my code worked but if i now add `, opset_imports=[helper.make_opsetid("", 18)]` I guess I need the proper ID for "Conv", right?

Thanks for the help

**Comment by mszhanyi** [comment]
helper.make_model: https://onnx.ai/onnx/_modules/onnx/helper.html#make_model
18 is the opset version that onnxruntime 1.15 supports.
https://github.com/onnx/onnx/blob/main/docs/Versioning.md#released-versions

**Comment by lix19937** [comment]
I think upgrade the version of onnxruntime can be help.
