### ISSUE TITLE
[Web/webgpu] ConvTranspose2D exposes errors when running segment anything model 

### ISSUE THREAD

**Issue by qjia7** [microsoft/onnxruntime#17295]
### Describe the issue

When running the [segment anything](https://github.com/fdwr/segment-anything/tree/main/demo/model) model, many errors about `ConvTranspose2D` are thrown like below:
```
Tint WGSL reader failure: :12:5 error: return statement type must match its function return type, returned 'vec4<f32>', expected 'f32'
    return W[i2o_W(indices)];
    ^^^^^^

 - While validating [ShaderModuleDescriptor]
 - While calling [Device].CreateShaderModule([ShaderModuleDescriptor]).
 ```
It seems there are some errors in the shader so that the shader can't be correctly compiled.

### To reproduce

Run [segment anything](https://github.com/fdwr/segment-anything/tree/main/demo/model) model with webgpu backend. Then above errors will be thrown.

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

93ae17d1bb9eb81e781f626a7f07dde8529a761c

### Execution Provider

'webgpu' (WebGPU)

**Comment by qjia7** [comment]
@fs-eire @guschmue If no one else is looking at this issue, I will look at it. Thanks.

**Comment by satyajandhyala** [comment]
Errors have been fixed.

**Comment by qjia7** [comment]
@satyajandhyala Thanks for the info. Have closed my PR. Will you continue to look at the convTranspose vec4 support?

**Comment by satyajandhyala** [comment]
> @satyajandhyala Thanks for the info. Have closed my PR. Will you continue to look at the convTranspose vec4 support?

Yes. Currently focusing on increasing coverage. Will take it up next.
