### ISSUE TITLE
Softmax node error with AMD gpu in C# api

### ISSUE THREAD

**Issue by thnak** [microsoft/onnxruntime#17307]
### Describe the issue

Could not init new session with DML execution provider in C# api

### To reproduce

the error only occur if in the model calculation graph there is a Softmax node + AMD gpu directml. other cases it will work fine.
![image](https://github.com/microsoft/onnxruntime/assets/117495750/4eecf186-02b8-4972-93b2-ec32aec40840)

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

DirectML

### Execution Provider Library Version

1.15.1

**Comment by mszhanyi** [comment]
So far, our tests don't cover directML+AMD GPU

**Comment by fdwr** [comment]
@thnak: This issue sounds familiar, like #16564 where the project tries to use an older version of DirectML.dll 🤔. Does copying the new version of DirectML.dll beside your .exe (like divideconcept did) work?

**Comment by thnak** [comment]
> @thnak: This issue sounds familiar, like #16564 where the project tries to use an older version of DirectML.dll 🤔. Does copying the new version of DirectML.dll beside your .exe (like divideconcept did) work?

i followed [this step](https://github.com/microsoft/onnxruntime/issues/13429#issuecomment-1293896464) and everything everything works. thanks

**Comment by GeorgeS2019** [comment]
Please add the label for csharp
https://github.com/microsoft/onnxruntime/labels/api%3ACSharp
