### ISSUE TITLE
Unrecognized attribute: axes for operator ReduceMean

### ISSUE THREAD

**Issue by ajithkumarmcw** [microsoft/onnxruntime#17350]
### Describe the issue

I am trying to convert demucs model to onnx , Generally demucs onnx is not supported as of now i have written all preprocessing and postprocessing steps like stft outside model. While converting demucs to onnx i am facing below issue
```
Traceback (most recent call last):
  File "/../lib/python3.9/site-packages/torch/onnx/utils.py", line 1686, in _export
    _C._check_onnx_proto(proto)
RuntimeError: Unrecognized attribute: axes for operator ReduceMean

==> Context: Bad node spec for node. Name: /ReduceMean OpType: ReduceMean

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/../demucs/onnxfile_create_script.py", line 67, in <module>
    torch.onnx.export(model, args=(mix, x), f="htdemucs_ft_onnx.onnx", opset_version=18, do_constant_folding=False)
  File "/home/../lib/python3.9/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/home/../demucs/lib/python3.9/site-packages/torch/onnx/utils.py", line 1688, in _export
    raise errors.CheckerError(e) from e
torch.onnx.errors.CheckerError: Unrecognized attribute: axes for operator ReduceMean

==> Context: Bad node spec for node. Name: /ReduceMean OpType: ReduceMean
```
### To reproduce

You need to clone demucs repo and do certain changes in model. if you really need the code let me know i will push in my git repo

### Urgency

Ya its urgent

### Platform

Linux

### OS Version

20.04.5 LTS

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by justinchuby** [comment]
Please consider using opset version 17 as opset 18 is not yet supported by the torch.onnx exporter.

**Comment by ajithkumarmcw** [comment]
thanks

**Comment by asasas234** [comment]
Hello, I'm interested in how to convert demucs to onnx. Have you been successful? Can you briefly describe the implementation steps?

**Comment by ajithkumarmcw** [comment]
I did to check whether we can convert for a simple demucs model or not . However i didnt check whether is completely gives proper output 100%
I formed the inference script by removing stft and istft codes and was converting only the model but even then i faced error for /ReduceMean  as it is not implemented. May be now it could have been added in latest opset u can check

**Comment by summelon** [comment]
Note that only opset version 17 worked in nvcr.io/nvidia/pytorch:23.05~24.04.
However on nvcr.io/nvidia/pytorch:24.05, this issue solved for opset version 17~20.
