### ISSUE TITLE
Can not quantize ORT model[Build] 

### ISSUE THREAD

**Issue by duany049** [microsoft/onnxruntime#17370]
### Describe the issue

I can't quantize ORT model, I tried both ways but failed, below are the two ways: 
1. I try to convert quantized onnx model to ORT model, but fail！
2. I try to quantized ORT model that converted from non quantitative onnx model, but fail！

Although I am able to convert non quantitative models into ORT models, the size of the ORT model is larger than that of the quantitative model and cannot achieve the effect of further compressing the model

How to accurately quantify the ORT model ?   thx!

### Target platform

ubuntu18

### Build script

python -m onnxruntime.tools.convert_onnx_models_to_ort head_pack_quantize.onnx

### Error / output

Converting models with optimization style 'Fixed' and level 'all'
Converting optimized ONNX model /dfs/data/workspace/project/Mask2Former/convert/head_pack.onnx to ORT format model /dfs/data/workspace/project/Mask2Former/convert/head_pack.ort
Converted 1/1 models successfully.
Generating config file from ORT format models with optimization style 'Fixed' and level 'all'
2023-08-31 19:08:01,995 ort_format_model.utils [INFO] - Created config in /dfs/data/workspace/project/Mask2Former/convert/head_pack.required_operators.config
Converting models with optimization style 'Runtime' and level 'all'
Converting optimized ONNX model /dfs/data/workspace/project/Mask2Former/convert/head_pack.onnx to ORT format model /dfs/data/workspace/project/Mask2Former/convert/head_pack.with_runtime_opt.ort
Converted 1/1 models successfully.
Converting models again without runtime optimizations to generate a complete config file. These converted models are temporary and will be deleted.
Converting optimized ONNX model /dfs/data/workspace/project/Mask2Former/convert/head_pack.onnx to ORT format model /dfs/data/workspace/project/Mask2Former/convert/tmp55s86_ir.without_runtime_opt/head_pack.ort
Converted 1/1 models successfully.
Generating config file from ORT format models with optimization style 'Runtime' and level 'all'
2023-08-31 19:08:05,571 ort_format_model.utils [INFO] - Created config in /dfs/data/workspace/project/Mask2Former/convert/head_pack.required_operators.with_runtime_opt.config

### GCC / Compiler Version

cmake 3.27.4

**Comment by duany049** [comment]
I fixed the problem

**Comment by gcunhase** [comment]
@duany049 can you please explain what the issue was and how you fixed it? Thanks.
