### ISSUE TITLE
error: package directory 'onnxruntime/backend' does not exist on Jetson TX2 when installing from source

### ISSUE THREAD

**Issue by johannesgensheimer** [microsoft/onnxruntime#1737]
**Describe the bug**
When I clone the onnxruntime git repository and install it from source with the command
"sudo python setup.py  install" I get the following error.

running install
running bdist_egg
running egg_info
creating onnxruntime.egg-info
writing top-level names to onnxruntime.egg-info/top_level.txt
writing requirements to onnxruntime.egg-info/requires.txt
writing dependency_links to onnxruntime.egg-info/dependency_links.txt
writing onnxruntime.egg-info/PKG-INFO
writing entry points to onnxruntime.egg-info/entry_points.txt
writing manifest file 'onnxruntime.egg-info/SOURCES.txt'
error: package directory 'onnxruntime/backend' does not exist

So this basically says that a directory is missing but i just cloned the master branch and did not edit anything.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master branch and other releases
- Python version: Python 2.7 or Python 3.5 (both the same error)
- GCC/Compiler version (if compiling from source): GCC version 5.4.0
- CUDA/cuDNN version: CUDA 9.0
- GPU model and memory: NVIDIA Pascal (Jetson TX2 board)

**To Reproduce**
Describe steps/code to reproduce the behavior:
git clone https://github.com/microsoft/onnxruntime.git
cd onnxruntime
export ONNX_ML=1
sudo python setup.py install

Also doesn't work with git clone -b rel-0.2.0 https://github.com/microsoft/onnxruntime.git and other releases which support e.g. CUDA 9.1.
sudo python setup.py bdist_wheel gives the same error.

**Expected behavior**
The expected behavior would be that onnxruntime is installed from source with the setup.py script.

**Additional context**
The error appeared on a Jetson TX2 board.

**Comment by jywu-msft** [comment]
python setup.py install doesn't build from source. (it's not set up to build in that way)

https://github.com/microsoft/onnxruntime/issues/995#issuecomment-490701207
and
https://github.com/microsoft/onnxruntime/issues/995#issuecomment-510584477
may be useful. 
Can you try building the python wheel from source using build.sh script?

**Comment by faxu** [comment]
@johannesgensheimer were you able to resolve the issue or do you need further assistance?
