### ISSUE TITLE
[Build] Multi-lingual support is only supported in ORT >= 1.16.0

### ISSUE THREAD

**Issue by jsoto-gladia** [microsoft/onnxruntime#17393]
### Describe the issue

Hello,
Thanks for all the great work you are all doing here.
I would like to test the whisper transcription. 
Therefore, on a v100s machine, I prepare my pyenv with :
```bash
jsoto@v100s:/$ git clone https://github.com/microsoft/Olive.git
jsoto@v100s:/Olive$ cd Olive/
jsoto@v100s:/Olive$ pyenv virtualenv 3.9 aceituna
jsoto@v100s:/Olive$ pyenv shell aceituna
```

When in aceituna pyenv, I install all the necessary packages with:
```bash
(aceituna) jsoto@v100s:/Olive$ cd examples/whisper
(aceituna) jsoto@v100s:/Olive/examples/whisper$ python -m pip install -r requirements.txt
(aceituna) jsoto@v100s:/Olive/examples/whisper$ python -m pip uninstall -y onnxruntime ort-nightly
(aceituna) jsoto@v100s:/Olive/examples/whisper$ python -m pip install ort-nightly --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/
```

When running the configuration preparation, I do:
```bash
(aceituna) jsoto@v100s:/Olive/examples/whisper$ python prepare_whisper_configs.py --model_name openai/whisper-tiny --multilingual
```
and I get the following error:
```bash
Traceback (most recent call last):
  File "/home/jsoto/code/Olive/examples/whisper/prepare_whisper_configs.py", line 143, in <module>
    main()
  File "/home/jsoto/code/Olive/examples/whisper/prepare_whisper_configs.py", line 60, in main
    raise ValueError("Multi-lingual support is only supported in ORT >= 1.16.0")
ValueError: Multi-lingual support is only supported in ORT >= 1.16.0
```
Any help is greatly appreciated. Thanks

P.S.1 when running 'pip freeze | grep onnx' , I get:
```bash
onnx==1.14.0
onnxruntime-extensions==0.8.0
onnxruntime-gpu==1.15.1
```
P.S.2 when running 'pip freeze | grep ort' , I get:
```bash
ort-nightly==1.16.0.dev20230901001
```

### Urgency

none

### Target platform

v100s

### Build script

none

### Error / output

Traceback (most recent call last):
  File "/home/jsoto/code/Olive/examples/whisper/prepare_whisper_configs.py", line 143, in <module>
    main()
  File "/home/jsoto/code/Olive/examples/whisper/prepare_whisper_configs.py", line 60, in main
    raise ValueError("Multi-lingual support is only supported in ORT >= 1.16.0")
ValueError: Multi-lingual support is only supported in ORT >= 1.16.0

**Comment by kunal-vaishnavi** [comment]
To run Whisper on a GPU, you can install `ort-nightly-gpu` instead of `ort-nightly`. The version error is occurring because you have both `onnxruntime-gpu` (stable version of ORT) and `ort-nightly` (nightly version of ORT) installed. You should uninstall `onnxruntime-gpu` if you are installing `ort-nightly-gpu`.

**Comment by jsoto-gladia** [comment]
however, when I have the following dependencies installed:
```
onnx==1.14.0
onnxruntime-extensions==0.8.0
importlib-resources==6.0.1
ort-nightly-gpu==1.16.0.dev20230903001
ort-nightly==1.16.0.dev20230903001
```

when running 
`python prepare_whisper_configs.py --model_name openai/whisper-tiny --multilingual`
I see the following log:
```
[2023-09-05 12:52:45,046] [INFO] [run.py:112:dependency_setup] The following packages are required in the local environment: ['onnxruntime-gpu']
[2023-09-05 12:52:45,047] [INFO] [run.py:118:dependency_setup] Installing onnxruntime-gpu...
Collecting onnxruntime-gpu
  Using cached onnxruntime_gpu-1.15.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (121.6 MB)
```

it does take into account that I have ort-nightly-gpu already installed...

**Comment by kunal-vaishnavi** [comment]
> ```
> Traceback (most recent call last):
>   File "/home/jsoto/code/Olive/examples/whisper/prepare_whisper_configs.py", line 11, in <module>
>     from onnxruntime import __version__ as OrtVersion
> ImportError: cannot import name '__version__' from 'onnxruntime' (unknown location)
> ```

This can happen if ONNX Runtime builds are installed/uninstalled in a mixed order. For example:
1. Nightly build is installed (`ort-nightly` or `ort-nightly-gpu`)
2. Stable build is installed (`onnxruntime` or `onnxruntime-gpu`)
3. Stable build is uninstalled (`onnxruntime` or `onnxruntime-gpu`)

To fix this import error, uninstall all ONNX Runtime builds
```
# Note: `onnxruntime` = stable CPU build, `onnxruntime-gpu` = stable GPU build, `ort-nightly` = nightly CPU build, `ort-nightly-gpu` = nightly GPU build
$ pip uninstall -y onnxruntime onnxruntime-gpu ort-nightly ort-nightly-gpu
```
and then install only one build.

## Generate Whisper configs

I was able to generate the Whisper configs in a new virtual environment as follows.

### Create new environment
```
(base) $ conda create --name olive-repro python=3.9 anaconda
(base) $ conda activate olive-repro
(olive-repro) $ python --version
Python 3.9.13

# Check that no ONNX/ONNX Runtime/ONNX Runtime Extensions packages are installed
# Each command should print `WARNING: Package(s) not found: package-name`
(olive-repro) $ pip show onnx
WARNING: Package(s) not found: onnx
(olive-repro) $ pip show onnxruntime
WARNING: Package(s) not found: onnxruntime
(olive-repro) $ pip show onnxruntime-gpu
WARNING: Package(s) not found: onnxruntime-gpu
(olive-repro) $ pip show ort-nightly
WARNING: Package(s) not found: ort-nightly
(olive-repro) $ pip show ort-nightly-gpu
WARNING: Package(s) not found: ort-nightly-gpu
(olive-repro) $ pip show onnxruntime-extensions
WARNING: Package(s) not found: onnxruntime-extensions

# Check that python/python3/pip/pip3 are all pointing to the virtual environment
# Each command should print a path that includes your virtual environment
(olive-repro) $ which python
/home/myusername/anaconda3/envs/olive-repro/bin/python
(olive-repro) $ which python3
/home/myusername/anaconda3/envs/olive-repro/bin/python3
(olive-repro) $ which pip
/home/myusername/anaconda3/envs/olive-repro/bin/pip
(olive-repro) $ which pip3
/home/myusername/anaconda3/envs/olive-repro/bin/pip3
```

### Install Olive
```
$ git clone https://github.com/microsoft/olive.git
$ cd olive
$ python -m pip install .

# Check that only ONNX was installed
(olive-repro) $ pip show onnx
Name: onnx
Version: 1.14.1
...
(olive-repro) $ pip show onnxruntime
WARNING: Package(s) not found: onnxruntime
(olive-repro) $ pip show onnxruntime-gpu
WARNING: Package(s) not found: onnxruntime-gpu
(olive-repro) $ pip show ort-nightly
WARNING: Package(s) not found: ort-nightly
(olive-repro) $ pip show ort-nightly-gpu
WARNING: Package(s) not found: ort-nightly-gpu
(olive-repro) $ pip show onnxruntime-extensions
WARNING: Package(s) not found: onnxruntime-extensions
```

### Install additional packages for Olive
```
(olive-repro) $ cd examples/whisper/
(olive-repro) $ python -m pip install -r requirements.txt

# Check that stable versions of ONNX, ONNX Runtime, and ONNX Runtime Extensions are installed
(olive-repro) $ pip show onnx
Name: onnx
Version: 1.14.0
...
(olive-repro) $ pip show onnxruntime
Name: onnxruntime
Version: 1.15.1
...
(olive-repro) $ pip show onnxruntime-gpu
WARNING: Package(s) not found: onnxruntime-gpu
(olive-repro) $ pip show ort-nightly
WARNING: Package(s) not found: ort-nightly
(olive-repro) $ pip show ort-nightly-gpu
WARNING: Package(s) not found: ort-nightly-gpu
(olive-repro) $ pip show onnxruntime-extensions
Name: onnxruntime-extensions
Version: 0.8.0
...

# Uninstall all ONNX Runtime builds
(olive-repro) $ pip uninstall -y onnxruntime onnxruntime-gpu ort-nightly ort-nightly-gpu

# Install nightly build for ONNX Runtime
# Note: You should specify a version number when installing the nightly builds. The version number is typically in the format YYYYMMDD001 where YYYYMMDD is the current date or any previous date.
(olive-repro) $ python -m pip install ort-nightly-gpu==1.16.0.dev20230901001 --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/

# Check that stable versions of ONNX and ONNX Runtime Extensions + nightly version of ONNX Runtime are installed
(olive-repro) $ pip show onnx
Name: onnx
Version: 1.14.0
...
(olive-repro) $ pip show onnxruntime
WARNING: Package(s) not found: onnxruntime
(olive-repro) $ pip show onnxruntime-gpu
WARNING: Package(s) not found: onnxruntime-gpu
(olive-repro) $ pip show ort-nightly
WARNING: Package(s) not found: ort-nightly
(olive-repro) $ pip show ort-nightly-gpu
Name: ort-nightly-gpu
Version: 1.16.0.dev20230901001
...
(olive-repro) $ pip show onnxruntime-extensions
Name: onnxruntime-extensions
Version: 0.8.0
...

# Test if __version__ can be imported
(olive-repro) $ python
Python 3.9.13
>>> from onnxruntime import __version__ as OrtVersion
>>> exit()
```

### Create Whisper configs
```
# Use Olive to prepare Whisper configs
# You can `ls` to see multiple JSON files in the format `whisper_{device}_{precision}.json` (e.g. `whisper_cpu_int8.json`, `whisper_gpu_fp16.json`)
(olive-repro) $ python prepare_whisper_configs.py --model_name openai/whisper-tiny --multilingual
(olive-repro) $ ls
README  data                        requirements.txt       whisper_cpu_fp32.json      whisper_cpu_int8.json  whisper_gpu_fp32.json  whisper_template.json
code    prepare_whisper_configs.py  test_transcription.py  whisper_cpu_inc_int8.json  whisper_gpu_fp16.json  whisper_gpu_int8.json
```

**Comment by jsoto-gladia** [comment]
hello, thanks for your help. I have thortougly followed your tutorial with no success.
When I run: 
`python -m olive.workflows.run --config whisper_gpu_fp32.json `
I get
`
[2023-09-12 20:27:44,600] [DEBUG] [resource_path.py:151:create_resource_path] Resource path code is inferred to be of type folder.
[2023-09-12 20:27:44,602] [DEBUG] [resource_path.py:151:create_resource_path] Resource path code/user_script.py is inferred to be of type file.
[2023-09-12 20:27:44,606] [WARNING] [engine.py:140:__init__] The following execution provider is not supported: AzureExecutionProvider. Please consider installing an onnxruntime build that contains the relevant execution providers. 
[2023-09-12 20:27:44,606] [INFO] [run.py:112:dependency_setup] The following packages are required in the local environment: ['onnxruntime-gpu']
[2023-09-12 20:27:44,606] [INFO] [run.py:118:dependency_setup] Installing onnxruntime-gpu...
Collecting onnxruntime-gpu
  Obtaining dependency information for onnxruntime-gpu from https://files.pythonhosted.org/packages/5c/0c/70575b46df32de18d99872c11ec17dc589a48095d6828892241e434d0adc/onnxruntime_gpu-1.15.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading onnxruntime_gpu-1.15.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.0 kB)
Requirement already satisfied: coloredlogs in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from onnxruntime-gpu) (15.0.1)
Requirement already satisfied: flatbuffers in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from onnxruntime-gpu) (23.5.26)
Requirement already satisfied: numpy>=1.21.6 in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from onnxruntime-gpu) (1.24.3)
Requirement already satisfied: packaging in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from onnxruntime-gpu) (23.1)
Requirement already satisfied: protobuf in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from onnxruntime-gpu) (3.20.3)
Requirement already satisfied: sympy in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from onnxruntime-gpu) (1.11.1)
Requirement already satisfied: humanfriendly>=9.1 in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from coloredlogs->onnxruntime-gpu) (10.0)
Requirement already satisfied: mpmath>=0.19 in /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages (from sympy->onnxruntime-gpu) (1.3.0)
Downloading onnxruntime_gpu-1.15.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (121.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 16.8 MB/s eta 0:00:00
Installing collected packages: onnxruntime-gpu
Successfully installed onnxruntime-gpu-1.15.1`

and then `pip show onnxruntime-gpu` gives me:
`Name: onnxruntime-gpu
Version: 1.15.1
Summary: ONNX Runtime is a runtime accelerator for Machine Learning models
Home-page: https://onnxruntime.ai
Author: Microsoft Corporation
Author-email: onnxruntime@microsoft.com
License: MIT License
Location: /home/jsoto/miniconda3/envs/olive-repro/lib/python3.9/site-packages
Requires: coloredlogs, flatbuffers, numpy, packaging, protobuf, sympy
Required-by: `

**Comment by jsoto-gladia** [comment]
can you test the command on your side ? thanks

**Comment by kunal-vaishnavi** [comment]
The above tutorial covers all of the steps needed to create the JSON config files before running them with the `olive.workflows.run` command. Since you were trying to run one of the JSON config files that was created (`whisper_gpu_fp32.json`), the above tutorial steps are working.

I also see the same logs when running the workflow with your command:
```
python -m olive.workflows.run --config whisper_gpu_fp32.json
```
It appears Olive installs the stable GPU version of ORT even though the nightly GPU version of ORT is already installed. This is a bug with Olive instead of ORT. Can you file this issue with [Olive](https://github.com/microsoft/Olive/) so it can be fixed?

**Comment by jsoto-gladia** [comment]
thanks will do
