### ISSUE TITLE
[Performance] When TensorrtExecutionProvider fails, falls back to CUDA instead of next listed

### ISSUE THREAD

**Issue by dhorkel** [microsoft/onnxruntime#17394]
### Describe the issue

I have a model that I run sometimes on a machine with a GPU with TensorRT installed, other times on a CPU.

When I specify `providers` to `InferenceSession()` I specify `["TensorrtExecutionProvider", "CPUExecutionProvider"]` as I expect it to fall back to CPU execution when GPU or appropriate DLLs are not available. Instead it tries to fall back to CUDAExecutionProvider and then throws an exception.

Exception:
```
EP Error D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\path\to\my\repo\.venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"
 when using ['TensorrtExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
2023-09-01 15:53:53.7046886 [E:onnxruntime:Default, provider_bridge_ort.cc:1351 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\path\to\my\repo\.venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

Traceback (most recent call last):
  File "C:\path\to\my\repo\.venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\path\to\my\repo\.venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1131 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\path\to\my\repo\.venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\path\to\my\repo\script.py", line 86, in load_model
    self.session = rt.InferenceSession(
  File "C:\path\to\my\repo\.venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 394, in __init__
    raise fallback_error from e
  File "C:\path\to\my\repo\.venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 389, in __init__
    self._create_inference_session(self._fallback_providers, None)
  File "C:\path\to\my\repo\.venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.
```

### To reproduce

Call: `InferenceSession(path, providers=["TensorrtExecutionProvider", "CPUExecutionProvider"])` when TensorRT is not installed and CUDA has the wrong version.

### Platform

Windows

### OS Version

Windows 10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Is this a quantized model?

Unknown

**Comment by skottmckay** [comment]
@jywu-msft should the fallback mechanism check if the CUDA EP was explicitly specified before falling back to it?

**Comment by jywu-msft** [comment]
> @jywu-msft should the fallback mechanism check if the CUDA EP was explicitly specified before falling back to it?

From my read of the issue, this seems like a pathological corner case where version dependencies are not met or some error prevents both TensorRT and CUDA EP's from executing.
Under normal circumstances, I think a user who wants to use TensorRT EP but hits a fatal error would prefer to fall back to CUDA EP and still leverage Nvidia GPU rather than completely falling back to CPU.
I think we can handle this case where both TensorRT and CUDA EP have issues and fall back to CPU.
+@yf711 FYI

**Comment by dhorkel** [comment]
> @jywu-msft should the fallback mechanism check if the CUDA EP was explicitly specified before falling back to it?

As a relatively naive new user, this was my assumed behavior.

I assumed the providers list is "if option 1 fails, try option 2 in the list, followed by option 3", not "if option 1 fails, try the option most similar even if it isn't listed and ignore other listed options".

**Comment by skottmckay** [comment]
> Under normal circumstances, I think a user who wants to use TensorRT EP but hits a fatal error would prefer to fall back to CUDA EP and still leverage Nvidia GPU rather than completely falling back to CPU.
> I think we can handle this case where both TensorRT and CUDA EP have issues and fall back to CPU.

I agree someone trying to use TRT would most likely prefer fallback to CUDA, however I also believe we will get GH Issues about 'performance is slow' if we fall back to CPU when TRT/CUDA wasn't available/working and the user didn't notice/expect the fallback. If we limit it to explicitly specified EPs they control the fallback options, and it doesn't involve implicit relationships like the one between TRT and CUDA.

**Comment by hariharans29** [comment]
Closing as fix was merged
