### ISSUE TITLE
Requiring Float16_t::FromBits() in c++ for conversion from uint16_t is not backward compatible

### ISSUE THREAD

**Issue by borg323** [microsoft/onnxruntime#17400]
### Describe the issue

Using onnxruntime master I can no longer do something like `Ort::Float16_t val = (uint16_t) v;` which worked just fine up to 1.15.1:
`error: no match for ‘operator=’ (operand types are ‘Ort::Float16_t’ and ‘uint16_t’ {aka ‘short unsigned int’})`
This started happening with commit 853c4ff0a581e8e27bae3d3c82cf984930a0c5f7.
I can replace it with `FromBits()` but this breaks builds with the released onnxruntime, so I need to do
```c++
#if ORT_API_VERSION >= 16
 y = Ort::Float16_t::FromBits(FP32toFP16(x));
#else
 y = FP32toFP16(x);
#endif
```
where `FP32toFP16()` returns `uint16_t`.
I get more compilation errors with master due to implicit conversions, but I can address them in a backward compatible way without the version check.

### To reproduce

Trying to compile `Ort::Float16_t val = (uint16_t) v;` should be enough.

### Urgency

Not urgent for me as I already have workarounds, but I expect it will break lots of code when released.

### Platform

Other / Unknown

### OS Version

Every

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

8b98ecad70c0f26d4cd43e41c5d96adad9cf2251

### ONNX Runtime API

C++

### Architecture

Other / Unknown

### Execution Provider

Other / Unknown

**Comment by yuslepukhin** [comment]
> Trying to compile Ort::Float16_t val = (uint16_t) v; should be enough.

The change made the public API consistent with our internal implementation where the user defined conversion in the form of the constructor was not considered a good thing. 

Primarily because it is not consistent with the behavior of the constructor from `float` and because `uint16_t` is convertible to `float`, and `float` can also be cast to `uint16_t`. From the history of GH requests to introduce fp16 support people tend to have wrong expectations of the API.

In the above example if `v` is a `float`, the code would not do what is expected of it.

**Comment by borg323** [comment]
I'm not arguing against the change. I'm just looking for a way to avoid onnxruntime version checks. What about renaming `val` in https://github.com/microsoft/onnxruntime/blob/main/include/onnxruntime/core/session/onnxruntime_float16.h#L84 to `value` (as it was in previous releases) so that it can be used for direct assignment in all versions?

**Comment by yuslepukhin** [comment]
I realize this is painful. The implementation is now shared between the API and the ORT code base, as we wanted to reduce code duplication as much as possible. However, the internal code used `val`. 

If I understood you right, you would simply need to change the implementation of `FP32toFP16` and put that ifdef inside of it.
The `#ifdef and #else` are not identical in the example though.

Cc: @edgchen1

**Comment by borg323** [comment]
In our case `FP32toFP16` is generic code shared by several backends. I can hide the version check elsewhere, I'm just checking if there is a cleaner way to have a backward compatible version as I need to support older onnxruntime releases. Since this is not easy, feel free to close the PR.

**Comment by yuslepukhin** [comment]
Generic code should make it easy to adapt. I will give it a thought, feel free to ask for more help. There is still a chance to add a reasonable last-minute change to the upcoming release.

**Comment by edgchen1** [comment]
> I'm not arguing against the change. I'm just looking for a way to avoid onnxruntime version checks. What about renaming `val` in https://github.com/microsoft/onnxruntime/blob/main/include/onnxruntime/core/session/onnxruntime_float16.h#L84 to `value` (as it was in previous releases) so that it can be used for direct assignment in all versions?

@yuslepukhin I believe renaming the data member should be simple enough. Then we can consistently say `y.value = <some uint16_t>;` in the old and new ORT versions.

**Comment by skottmckay** [comment]
I agree. Is there any reason why the internal class using `val` should limit what we use in the public class, especially if using `value` in the latter means code can be made to work with both old and new ORT implementations without using an `#if` on the ORT version?

**Comment by pranavsharma** [comment]
@yuslepukhin Renaming val to value seems like an easy win that satisfies both backward compatibility and preserves the new semantics.
cc @natke

**Comment by pranavsharma** [comment]
We won't be fixing this.
1. These conversions are provided as helpful utilities for users and not part of the core inferencing APIs. We try our best to not break old client code but please note that we provide backward compatibility guarantees for the core inferencing APIs only.
2. It has limited scope as it affects float 16 use cases only.
