### ISSUE TITLE
[Feature Request] Access to SessionOptions::use_deterministic_compute from the C API

### ISSUE THREAD

**Issue by coffinmatician** [microsoft/onnxruntime#17416]
### Describe the feature request

As far as I can tell the flag `SessionOptions::use_deterministic_compute` is accessible from many of the language bindings including Python ( https://onnxruntime.ai/docs/api/python/api_summary.html#onnxruntime.SessionOptions.use_deterministic_compute ), but after looking for 15 minutes I cannot seem to find how to influence this value from C. I apologize if I missed the function that provides access to this, but I went looking all through the codebase for various search terms I could think of, but I couldn't find it. If I had to guess I would expect that it should be added to `include/onnxruntime/core/session/onnxruntime_c_api.h`, or possibly `include/onnxruntime/core/session/onnxruntime_session_options_config_keys.h`.

I hope you are having a great day :)

### Describe scenario use case

Wanting to use features exposed to Python from C.

**Comment by skottmckay** [comment]
Doesn't look like it's currently exposed and needs to be added to onnxruntime_c_api.h

**Comment by skottmckay** [comment]
Will be available in the 1.17 release
