### ISSUE TITLE
[Feature Request] Tool to fuse Stable Diffusion from multiple models into single model

### ISSUE THREAD

**Issue by philipwan** [microsoft/onnxruntime#17430]
### Describe the feature request

<img width="1104" alt="image" src="https://github.com/microsoft/onnxruntime/assets/18528611/16c6179b-bd58-4380-9fd4-9c5088bb6cd7">
I noticed that there is a todo in the document, which can change Stable Diffusion from multiple models into  single model, which will help improve memory performance, etc. When will this function be completed? I am looking forward to it

Or Is there any tool here that can accomplish this function？(**optimum**'s parameter: monolith doesn‘t effect to Stable Diffusion)

Current State：
<img width="822" alt="image" src="https://github.com/microsoft/onnxruntime/assets/18528611/6d4da3e6-1617-439d-9b17-4501bdcf513e">

Thank You！

### Describe scenario use case

https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/models/stable_diffusion/README.md
follow onnxruntime doc

```[tasklist]
### Tasks
```

**Comment by skottmckay** [comment]
@tianleiwu are there any updates on the future works status?

You can share thread pools across sessions with CreateEnvWithGlobalThreadPools 
https://onnxruntime.ai/docs/api/c/struct_ort_api.html#a43a1a757582469f88421a9ef9d63f192

You can also share allocators across sessions with CreateAndRegisterAllocator[V2]
https://onnxruntime.ai/docs/api/c/struct_ort_api.html#a6a0ca4d136819eafea7d87e7f87a82db
https://onnxruntime.ai/docs/api/c/struct_ort_api.html#a12c97c7471565c34f99dac7e574d12cf

**Comment by tianleiwu** [comment]
@stottmckay, that work item is deprioritized due to: (1) other higher priority works (like SDXL model optimization, control-net integration etc), (2) ROI: estimated performance gain is small while the cost of implementation is high.

However, the work might be essential for mobile application so it is still kept in the list. 

BTW, there is related but not finished works in huggingface optimum: https://github.com/huggingface/optimum/pull/730 that tried to export the pipeline to one ONNX model. 

Another related open-source project:
https://github.com/axodox/axodox-machinelearning is C++ implementation of stable diffusion using ONNX model and ONNX Runtime. Just apply the APIs mentioned by @skottmckay to improve on that could be a good start point.

**Comment by Craigacp** [comment]
Would this require porting the scheduling algorithms over to be ONNX graphs, and then fusing the scheduler into the model itself?

**Comment by philipwan** [comment]
> @stottmckay, that work item is deprioritized due to: (1) other higher priority works (like SDXL model optimization, control-net integration etc), (2) ROI: estimated performance gain is small while the cost of implementation is high.
> 
> However, the work might be essential for mobile application so it is still kept in the list.
> 
> BTW, there is related but not finished works in huggingface optimum: [huggingface/optimum#730](https://github.com/huggingface/optimum/pull/730) that tried to export the pipeline to one ONNX model. If anyone want to go in similar route, try wrap each component (like unet etc) as a custom op to export, then replace the custom op by actual onnx graph of optimized unet model (could add a prefix to avoid naming confliction in initializer or edge etc.).
> 
> Another related open-source project: https://github.com/axodox/axodox-machinelearning is C++ implementation of stable diffusion using ONNX model and ONNX Runtime. Just apply the APIs mentioned by @skottmckay to improve on that could be a good start point.

Thank you for your suggestion, it is a good option to load a custom operation during the optimization process, I will try it.
BTW, my destination is also to load the model at the C++ level, maybe there are more optimization methods.

**Comment by philipwan** [comment]
> @tianleiwu are there any updates on the future works status?
> 
> You can share thread pools across sessions with CreateEnvWithGlobalThreadPools https://onnxruntime.ai/docs/api/c/struct_ort_api.html#a43a1a757582469f88421a9ef9d63f192
> 
> You can also share allocators across sessions with CreateAndRegisterAllocator[V2] https://onnxruntime.ai/docs/api/c/struct_ort_api.html#a6a0ca4d136819eafea7d87e7f87a82db https://onnxruntime.ai/docs/api/c/struct_ort_api.html#a12c97c7471565c34f99dac7e574d12cf

I don't know about these APIs yet, I'm going to take a closer look

**Comment by philipwan** [comment]
When I run the code of this branch, https://github.com/huggingface/optimum/pull/73.  I can generate single pt, onnx files, but using the same input to run onnx model multiple times, the output results are different. Why is this, are there any random parameters that need to be set fixed?  @fxmarty

**Comment by tianleiwu** [comment]
@philipwan, you can take a look at onnx graph to find whether there is RandomNormalLike. The operator has an attribute named `seed`. Try use an initializer to pass the random seed.
