### ISSUE TITLE
View Activations during Inferencing

### ISSUE THREAD

**Issue by RandyGaul** [microsoft/onnxruntime#1744]
Is it in any way possible to view the activations for a single inference? It would be nice to be able to record this data offline to generate debug visualizations of the activation patterns for a given model.

It looks like the internal data structures of the runtime are not at all accessible through the public API. Would it be feasible to optionally record and expose internal values, so users can visualize their inference patterns?

**Comment by jywu-msft** [comment]
One could add intermediate outputs to the onnx model outputs so that you could fetch them.
see https://github.com/microsoft/onnxruntime/pull/1588 as a potential example.

**Comment by faxu** [comment]
@RandyGaul - thoughts on the suggestion? Would that suffice for your use case?

**Comment by RandyGaul** [comment]
Yes, thank you! :)
