### ISSUE TITLE
This method is not thread safe!

### ISSUE THREAD

**Issue by DaiShaoJie77** [microsoft/onnxruntime#17462]
### Describe the issue

“ExecutionFrame::AllocateAsPerAllocationPlan”
Is there anything good ways to make his thread safe？

### To reproduce

.

### Platform

Windows

### OS Version

12.4

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.16

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by pranavsharma** [comment]
What's your use case? What are some reasons you need this to be thread safe?

**Comment by hariharans29** [comment]
Please re-open with more context of your usage scenario
