### ISSUE TITLE
Question about sequence/map input onnx type from model

### ISSUE THREAD

**Issue by qw2208** [microsoft/onnxruntime#1747]
1. Is there a way to get the non-tensor types from the onnx model?
For example, if the model input is of type: std::vector<std::map<int64_t, float>>, I could get the input type of `ONNX_TYPE_SEQUENCE` by running `session->GetInputTypeInfo(i).GetONNXType();`
However, I'm confused how I could continue to get the type of the map while creating Ort::Value using the CXX api?
2. Another question is when loading the Bert model from [Bert_model](https://github.com/onnx/models/tree/master/text/machine_comprehension/bert-squad/model), one of the input shapes is [-1, 256] (Actually this model converted from Tensorflow and the inputs shape all starts with -1). Is the negative index supported when calling session run function? I'm getting the error of out of data bound.
![image](https://user-images.githubusercontent.com/24438413/64190361-c7988580-cea8-11e9-8edf-694d515b4b89.png)

**Comment by snnn** [comment]
I'll take a look at the second one. It shouldn't be [-1].

**Comment by snnn** [comment]
For you question two: here the -1 means unknown. You can replace it with any non-zero positive value.

**Comment by qw2208** [comment]
Yes, I did replace the -1 with 1 to all of the four inputs while getting the element out-of-bound exception as shown in the screen shot.

**Comment by snnn** [comment]
We'll update the model.

**Comment by RyanUnderhill** [comment]
For 1. I'm not sure what you mean by continuing to get the type of the map. If you have an Ort::Value you can still call GetTypeInfo() on it and then call GetONNXType() the same as before?

**Comment by qw2208** [comment]
@RyanUnderhill  Thanks Ryan. However, for inputs, I will not get it in Ort::Value and the GetTypeInfo() could only get the type of the outer type.

**Comment by RyanUnderhill** [comment]
@qw2208 Ah, I see what you're looking for. Yeah, currently we have no way to query subtype information of a type. I'm marking this as an enhancement as we'd need some extra interface functions like this:

OrtStatus* *GetType(const OrtTypeInfo* type, int index, OrtTypeInfo** out)
OrtStatus* *GetTypeCount(const OrtTypeInfo* type, int index, size_t* out);

**Comment by faxu** [comment]
First issue is resolved - available in ORT 1.2. 

@vinitra can you take a look at #2 and see if the model zoo model still needs updates?
