### ISSUE TITLE
Level of reproducibility between different runtimes (python vs java)

### ISSUE THREAD

**Issue by Dizzy2510** [microsoft/onnxruntime#17475]
### Describe the issue

I am using a sklearn RandomForestClassifier and have successfully converted it into onnx.
After some research (CastTransformer, float32 vs double) i made it to the point that the sklearn model and the onnx model called with python runtime produce the same scores (predict proba) up to 7 decimals.

Now i tried to run the converted onnxmodel with the java runtime and realized the following issue.
When i compare the predict proba scores between python runtime vs java runtime (same onnx model), they are the same (up to 7 decimals) when i use a sample that the model has been trained with.

When i try out a new sample (which was not trained) i get get deviations up to like 5%, e.g.:
- python runtime score for class0: 0.78
- java runtime score for class0: 0.82

Is this something that is to be expected? I feel like this difference is quite big.
Especially when sklearn scores vs onnx scores are identical..

Librarys:
skl2onnx==1.15.0
onnxruntime==1.15.1
Python: 3.9.7
Java 8

### To reproduce

-

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Other / Unknown

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

Java

### Architecture

Other / Unknown

### Execution Provider

Default CPU

**Comment by snnn** [comment]
There is a big difference, though not intentional, between them: the python one is built with pytorch's cpuinfo library. The other one doesn't.  It is because the Java one use the same DLL that we ship in nuget packages. The DLL is designed to be portable across all Windows 10/11 Editions. It has broader platform support than the python one(I assume you doesn't have a need to run python in Hololens). The people who added cpuinfo to onnxruntime didn't make the lib work in this setting. It means we have to disable some performance optimization features in this setting.  So, you may try to build the DLL from source by yourself. The instructions are at: https://onnxruntime.ai/docs/build/inferencing.html .  
cpuinfo is one difference. There could be other differences too.  ONNX Runtime has over 100 build options. So often there are some tiny differences between different packages.

**Comment by Craigacp** [comment]
The same output for some inputs and different output for others is very odd. How are the test inputs prepared in both Python & Java?

**Comment by Dizzy2510** [comment]
Thanks for both of your quick answers!

@snnn: I will give it a try within the next few days i guess. Thanks for your explanation!

@Craigacp: Yea, for me this was very odd as well. The only difference was as i explained that same scores were generated for data that the model has been trained with. Different scores between them for samples that has not been trained.

My sklearn pipeline goes like this:

```
def create_pipeline(classifier,cat_features,num_features):
    numeric_transformer = Pipeline(steps=[
        ('cast32', CastTransformer(dtype=np.float32)),
        ('imputer', SimpleImputer(strategy="median")),
        ('cast64', CastTransformer(dtype=np.float64)),
    ])
    categorical_transformer = Pipeline(steps=[
         ("ordinal", OrdinalEncoder(handle_unknown="use_encoded_value",unknown_value  =-1)),
    ])
    preprocessor = ColumnTransformer(
        transformers=[
            ('cat', categorical_transformer, categorical_features),
            ('num', numeric_transformer, numeric_features)
        ])
    model = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('cast64', CastTransformer(dtype=np.float64))
        ('classifier', classifier)
    ])
    return model
```

All my numeric features in pandas dataframe are dtype np.float32, my string features are stringtype.
Model is trained with: 
`model.fit(df[features],d[ftarget])`

Onnx Conversion:

```
model_onnx = to_onnx(model, df[features][:1], 
                target_opset=get_latest_tested_opset_version(),\
                options={
                         id(model): {'raw_scores': True}
                        })
```

Java side looks like the following. I tried to extract the crucial parts and hope im not missing anything (collegue implemented it):

```
public abstract class InputData {

    private float[][] feat1;
    private String[][] feat2;
    private float[][] feat3;

public class InputData2 extends InputData {

        public Long[] setInputData(List<V> input) {
            Long[] Arr = new Long[input.size()];
        
            this.feat1(new float[input.size()][1]);
            this.feat2(new String[input.size()][1]);
            this.feat3(new float[input.size()][1]);

public Map<String, OnnxTensor> getInputMap(OrtEnvironment environment) throws OrtException {
        Map<String, OnnxTensor> inputMap = new LinkedMap<>();
        inputMap.put("feat1", OnnxTensor.createTensor(environment, this.feat1));
        inputMap.put("feat2", OnnxTensor.createTensor(environment, this.feat2));
        inputMap.put("feat3", OnnxTensor.createTensor(environment, this.feat3));

OrtEnvironment environment = OrtEnvironment.getEnvironment();
OrtSession session = environment.createSession("onnxModelPath")
inputData.getInputMap(environment);
Map<String, OnnxTensor> inputMap = inputData.getInputMap(environment);
session.run(inputMap);
```

**Comment by Craigacp** [comment]
The Java code there looks a little truncated. 

Is the data loaded in from a file in both the training & testing cases? Also are the strings ASCII, or using a wider range of characters. I would expect the ONNX Runtime bits to behave the same, the Java code converts UTF-16 Java strings into UTF-8 strings suitable for ONNX Runtime, but if there's a character encoding issues getting the data into Java that could account for some differences (e.g. on Windows in Java 8 the default charset is a Windows specific one, but on Java 18 and newer the default charset for all platforms is UTF-8, and in Python 3 the default charset is UTF-8).

One thing to check is just round tripping the data into an `OnnxTensor` and back out into Java to make sure nothing funny is going on. I'm pretty sure we have tests which do that for all inputs, but we don't cover all of unicode in those String tests.

**Comment by Dizzy2510** [comment]
Sorry for the truncated code.
Indeed, for the test case i created a json in python with the expected onnx scores and the features.
Java reads that json, takes the features and compare the onnx score generated from java runtime vs. the one provided in json that i created with the python runtime.

For testing purposes, i just created a new onnx model just with numeric features and called that model from java. And indeed, the score for a sample (that has not been trained) is identical with the score generated with python runtime.
So i guess, you had the right intention. It seems like this indeed has something to do with the encoding...

I will try to talk to the java collegues to investigate this. But this looks like a reference point to start with!

Thank you so much for your help!
I will post the results here later if i can make it work with stringtype features.

**Comment by Craigacp** [comment]
It depends what charset the file is written out in, but presumably it should be UTF-8 if it came from Python without any specific options. Java's internal representation is UTF-16, but the default charset for reading in files is version and platform dependent (though the charset can be specified on all methods that read things in, and it's good practice to set it to the expected charset of the data).

**Comment by Craigacp** [comment]
Does enabling the java or python build trigger more flags? If not then building a basic version of both of them should build the same core runtime and it would narrow down where the issue is.

I agree if there is different hardware or floating point support you can get very different outputs.

**Comment by Dizzy2510** [comment]
Hello again,

after several investigations it turned out that the Input Parameter were different on one runtime. One of the stringtype features have been incorrectly set as Input, i didnt run it through the entire processing of the feature and i missed an important Detail by defining the input. 
Scores are the same now. 
Thanks for your help and the Information you provided, it helped me. This Issue can be closed.
