### ISSUE TITLE
[Build] how to build C library into RPM?

### ISSUE THREAD

**Issue by dandlake** [microsoft/onnxruntime#17486]
### Describe the issue

Hi, I need to bulid onnxruntime C library into an RPM. Is there any steps/instructions? I see there is package/rpm/onnxruntime.spec file, but not sure how to use it. For example, where is(or how to create) onnxruntime.tar file? Thanks.

### Target platform

Linux

### Build script

N/A

### Error / output

N/A

**Comment by snnn** [comment]
You can use the following commands to build the RPM:
```
dnf install rpm-build gcc-toolset-12-gcc-c++
git clone https://src.fedoraproject.org/rpms/onnxruntime.git
cd onnxruntime
copy * ~/rpmbuild/SOURCES
rpmbuild  --undefine=_disable_source_fetch -bb onnxruntime.spec 
```

The rpm spec file is provided by the Fedora project.  As @skottmckay said, you may need to contact the maintainer of that for more information.

**Comment by snnn** [comment]
I will close this issue because we cannot provide further support to it.
