### ISSUE TITLE
[Web] Is there any garbage generated inside onnxruntime

### ISSUE THREAD

**Issue by grazder** [microsoft/onnxruntime#17495]
### Describe the issue

Does ONNX Runtime Web generate any garbage during inference? Is a caching allocator being used?

### To reproduce

-

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

onnxruntime-web@1.14.0

### Execution Provider

'wasm'/'cpu' (WebAssembly CPU)

**Comment by guschmue** [comment]
not that we know about. A little more detail would help.

**Comment by hariharans29** [comment]
Closing as there are no specific issue details or repro steps. Please fill in the issue template completely and re-open.
