### ISSUE TITLE
Could not locate zlibwapi.dll, cuda11.8, cuDNN8.5.0.96 (Windows)

### ISSUE THREAD

**Issue by nistarlwc** [microsoft/onnxruntime#17510]
### Describe the issue

Install cuda11.8, cuDNN8.5.0.96, and onnxruntime-gpu==1.15.
But could not locate zlibwapi.dll

### To reproduce

`Could not locate zlibwapi.dll. Please make sure it is in your library path!`

### Platform

Windows

### OS Version

win10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

onnxruntime-gpu==1.15

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.8

**Comment by snnn** [comment]
You need to manually download the DLL and install it. Please refer CUDA 11.8's installation document from Nvidia's official website.

**Comment by rodrigovimieiro** [comment]
Followed this [tutorial](https://linuxhint.com/install-zlib-windows-10-11/) and worked for me.
