### ISSUE TITLE
[Documentation] C/C++ API docs cannot be viewed

### ISSUE THREAD

**Issue by snunez1** [microsoft/onnxruntime#17511]
### Describe the documentation issue

Cannot read any of the API docs in the URL below.  Tried on Chrome, Edge and Firefox.  Each time a link is clicked, there's a brief flash, and the table of contents remains displayed.

### Page / URL

https://onnxruntime.ai/docs/api/c/c_cpp_api.html

**Comment by natke** [comment]
Hi @snunez1 Thank you for pointing this out. The docs are still there on the page if you scroll down but there is definitely a rendering issue, which we will look into.

**Comment by natke** [comment]
Actually the fix was made in https://github.com/microsoft/onnxruntime/pull/17558
