### ISSUE TITLE
[Build] CMake Error: Unknown argument -c

### ISSUE THREAD

**Issue by BentiGorlich** [microsoft/onnxruntime#17517]
### Describe the issue

When trying to build I get the error that CMake doesn't know the argument `-c` and can therefore not compile the project. My `cmake --version`: 
```
cmake --version
cmake version 3.27.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

> The C++ compiler
> "/home/benni/.local/bin/cmake"
> is not able to compile a simple test program.

### Urgency

not urgent

### Target platform

linux x86/64

### Build script

./build.sh --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync

### Error / output

2023-09-12 15:56:05,111 build [DEBUG] - Command line arguments:
  --build_dir /home/benni/Dokumente/git/onnxruntime/build/Linux --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync
2023-09-12 15:56:05,114 build [DEBUG] - Defaulting to running update, build [and test for native builds].
2023-09-12 15:56:05,114 build [INFO] - Build started
2023-09-12 15:56:05,115 build [INFO] - Generating CMake build tree
2023-09-12 15:56:05,115 util.run [INFO] - Running subprocess in '/home/benni/Dokumente/git/onnxruntime/build/Linux/RelWithDebInfo'
  /home/benni/.local/bin/cmake /home/benni/Dokumente/git/onnxruntime/cmake --compile-no-warning-as-error -Donnxruntime_RUN_ONNX_TESTS=OFF -Donnxruntime_GENERATE_TEST_REPORTS=ON -DPython_EXECUTABLE=/usr/bin/python3 -DPYTHON_EXECUTABLE=/usr/bin/python3 -Donnxruntime_USE_MIMALLOC=OFF -Donnxruntime_ENABLE_PYTHON=OFF -Donnxruntime_BUILD_CSHARP=OFF -Donnxruntime_BUILD_JAVA=OFF -Donnxruntime_BUILD_NODEJS=OFF -Donnxruntime_BUILD_OBJC=OFF -Donnxruntime_BUILD_SHARED_LIB=ON -Donnxruntime_BUILD_APPLE_FRAMEWORK=OFF -Donnxruntime_USE_DNNL=OFF -Donnxruntime_USE_NNAPI_BUILTIN=OFF -Donnxruntime_USE_RKNPU=OFF -Donnxruntime_USE_LLVM=OFF -Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF -Donnxruntime_USE_VITISAI=OFF -Donnxruntime_USE_TENSORRT=OFF -Donnxruntime_USE_TENSORRT_BUILTIN_PARSER=ON -Donnxruntime_USE_TVM=OFF -Donnxruntime_TVM_CUDA_RUNTIME=OFF -Donnxruntime_TVM_USE_HASH=OFF -Donnxruntime_USE_MIGRAPHX=OFF -Donnxruntime_DISABLE_CONTRIB_OPS=OFF -Donnxruntime_DISABLE_ML_OPS=OFF -Donnxruntime_DISABLE_RTTI=OFF -Donnxruntime_DISABLE_EXCEPTIONS=OFF -Donnxruntime_MINIMAL_BUILD=OFF -Donnxruntime_EXTENDED_MINIMAL_BUILD=OFF -Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF -Donnxruntime_REDUCED_OPS_BUILD=OFF -Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF -Donnxruntime_USE_DML=OFF -Donnxruntime_USE_WINML=OFF -Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF -Donnxruntime_USE_TELEMETRY=OFF -Donnxruntime_ENABLE_LTO=OFF -Donnxruntime_USE_ACL=OFF -Donnxruntime_USE_ACL_1902=OFF -Donnxruntime_USE_ACL_1905=OFF -Donnxruntime_USE_ACL_1908=OFF -Donnxruntime_USE_ACL_2002=OFF -Donnxruntime_USE_ARMNN=OFF -Donnxruntime_ARMNN_RELU_USE_CPU=ON -Donnxruntime_ARMNN_BN_USE_CPU=ON -Donnxruntime_USE_JSEP=OFF -Donnxruntime_ENABLE_NVTX_PROFILE=OFF -Donnxruntime_ENABLE_TRAINING=OFF -Donnxruntime_ENABLE_TRAINING_OPS=OFF -Donnxruntime_ENABLE_TRAINING_APIS=OFF -Donnxruntime_ENABLE_CPU_FP16_OPS=OFF -Donnxruntime_USE_NCCL=OFF -Donnxruntime_BUILD_BENCHMARKS=OFF -Donnxruntime_USE_ROCM=OFF -DOnnxruntime_GCOV_COVERAGE=OFF -Donnxruntime_USE_MPI=OFF -Donnxruntime_ENABLE_MEMORY_PROFILE=OFF -Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF -Donnxruntime_BUILD_WEBASSEMBLY=OFF -Donnxruntime_BUILD_WEBASSEMBLY_STATIC_LIB=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING=ON -Donnxruntime_ENABLE_WEBASSEMBLY_API_EXCEPTION_CATCHING=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_THROWING=ON -Donnxruntime_WEBASSEMBLY_RUN_TESTS_IN_BROWSER=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_PROFILING=OFF -Donnxruntime_ENABLE_LAZY_TENSOR=OFF -Donnxruntime_ENABLE_EXTERNAL_CUSTOM_OP_SCHEMAS=OFF -Donnxruntime_ENABLE_CUDA_PROFILING=OFF -Donnxruntime_ENABLE_ROCM_PROFILING=OFF -Donnxruntime_USE_XNNPACK=OFF -Donnxruntime_USE_CANN=OFF -DCMAKE_TLS_VERIFY=ON -DFETCHCONTENT_QUIET=OFF -Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF -Donnxruntime_ENABLE_MEMLEAK_CHECKER=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH=/home/benni/Dokumente/git/onnxruntime/build/Linux/RelWithDebInfo/installed
Ignoring COMPILE_WARNING_AS_ERROR target property and CMAKE_COMPILE_WARNING_AS_ERROR variable.
CMake Deprecation Warning at CMakeLists.txt:21 (cmake_policy):
  The OLD behavior for policy CMP0104 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- The CXX compiler identification is unknown
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /home/benni/.local/bin/cmake
-- Check for working CXX compiler: /home/benni/.local/bin/cmake - broken
CMake Error at /home/benni/.local/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeTestCXXCompiler.cmake:60 (message):
  The C++ compiler

    "/home/benni/.local/bin/cmake"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/home/benni/Dokumente/git/onnxruntime/build/Linux/RelWithDebInfo/CMakeFiles/CMakeScratch/TryCompile-5esrrt'
    
    Run Build Command(s): /home/benni/.local/lib/python3.11/site-packages/cmake/data/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_ee9ed/fast
    /usr/bin/gmake  -f CMakeFiles/cmTC_ee9ed.dir/build.make CMakeFiles/cmTC_ee9ed.dir/build
    gmake[1]: Verzeichnis „/home/benni/Dokumente/git/onnxruntime/build/Linux/RelWithDebInfo/CMakeFiles/CMakeScratch/TryCompile-5esrrt“ wird betreten
    Building CXX object CMakeFiles/cmTC_ee9ed.dir/testCXXCompiler.cxx.o
    /home/benni/.local/bin/cmake    -o CMakeFiles/cmTC_ee9ed.dir/testCXXCompiler.cxx.o -c /home/benni/Dokumente/git/onnxruntime/build/Linux/RelWithDebInfo/CMakeFiles/CMakeScratch/TryCompile-5esrrt/testCXXCompiler.cxx
    CMake Warning:
      Ignoring extra path from command line:
    
       "/home/benni/Dokumente/git/onnxruntime/build/Linux/RelWithDebInfo/CMakeFiles/CMakeScratch/TryCompile-5esrrt/testCXXCompiler.cxx"
    
    
    CMake Error: Unknown argument -c
    CMake Error: Run 'cmake --help' for all supported options.
    gmake[1]: *** [CMakeFiles/cmTC_ee9ed.dir/build.make:78: CMakeFiles/cmTC_ee9ed.dir/testCXXCompiler.cxx.o] Fehler 1
    gmake[1]: Verzeichnis „/home/benni/Dokumente/git/onnxruntime/build/Linux/RelWithDebInfo/CMakeFiles/CMakeScratch/TryCompile-5esrrt“ wird verlassen
    gmake: *** [Makefile:127: cmTC_ee9ed/fast] Fehler 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:33 (project)

-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/home/benni/Dokumente/git/onnxruntime/tools/ci_build/build.py", line 2599, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/benni/Dokumente/git/onnxruntime/tools/ci_build/build.py", line 2460, in main
    generate_build_tree(
  File "/home/benni/Dokumente/git/onnxruntime/tools/ci_build/build.py", line 1369, in generate_build_tree
    run_subprocess(
  File "/home/benni/Dokumente/git/onnxruntime/tools/ci_build/build.py", line 781, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benni/Dokumente/git/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/benni/.local/bin/cmake', '/home/benni/Dokumente/git/onnxruntime/cmake', '--compile-no-warning-as-error', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-DPython_EXECUTABLE=/usr/bin/python3', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-Donnxruntime_USE_MIMALLOC=OFF', '-Donnxruntime_ENABLE_PYTHON=OFF', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_JAVA=OFF', '-Donnxruntime_BUILD_NODEJS=OFF', '-Donnxruntime_BUILD_OBJC=OFF', '-Donnxruntime_BUILD_SHARED_LIB=ON', '-Donnxruntime_BUILD_APPLE_FRAMEWORK=OFF', '-Donnxruntime_USE_DNNL=OFF', '-Donnxruntime_USE_NNAPI_BUILTIN=OFF', '-Donnxruntime_USE_RKNPU=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_VITISAI=OFF', '-Donnxruntime_USE_TENSORRT=OFF', '-Donnxruntime_USE_TENSORRT_BUILTIN_PARSER=ON', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_TVM_CUDA_RUNTIME=OFF', '-Donnxruntime_TVM_USE_HASH=OFF', '-Donnxruntime_USE_MIGRAPHX=OFF', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_DISABLE_ML_OPS=OFF', '-Donnxruntime_DISABLE_RTTI=OFF', '-Donnxruntime_DISABLE_EXCEPTIONS=OFF', '-Donnxruntime_MINIMAL_BUILD=OFF', '-Donnxruntime_EXTENDED_MINIMAL_BUILD=OFF', '-Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF', '-Donnxruntime_REDUCED_OPS_BUILD=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=OFF', '-Donnxruntime_USE_WINML=OFF', '-Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxruntime_USE_ACL=OFF', '-Donnxruntime_USE_ACL_1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_USE_ACL_2002=OFF', '-Donnxruntime_USE_ARMNN=OFF', '-Donnxruntime_ARMNN_RELU_USE_CPU=ON', '-Donnxruntime_ARMNN_BN_USE_CPU=ON', '-Donnxruntime_USE_JSEP=OFF', '-Donnxruntime_ENABLE_NVTX_PROFILE=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_ENABLE_TRAINING_OPS=OFF', '-Donnxruntime_ENABLE_TRAINING_APIS=OFF', '-Donnxruntime_ENABLE_CPU_FP16_OPS=OFF', '-Donnxruntime_USE_NCCL=OFF', '-Donnxruntime_BUILD_BENCHMARKS=OFF', '-Donnxruntime_USE_ROCM=OFF', '-DOnnxruntime_GCOV_COVERAGE=OFF', '-Donnxruntime_USE_MPI=OFF', '-Donnxruntime_ENABLE_MEMORY_PROFILE=OFF', '-Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF', '-Donnxruntime_BUILD_WEBASSEMBLY=OFF', '-Donnxruntime_BUILD_WEBASSEMBLY_STATIC_LIB=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING=ON', '-Donnxruntime_ENABLE_WEBASSEMBLY_API_EXCEPTION_CATCHING=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_THROWING=ON', '-Donnxruntime_WEBASSEMBLY_RUN_TESTS_IN_BROWSER=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF', '-Donnxruntime_ENABLE_WEBASSEMBLY_PROFILING=OFF', '-Donnxruntime_ENABLE_LAZY_TENSOR=OFF', '-Donnxruntime_ENABLE_EXTERNAL_CUSTOM_OP_SCHEMAS=OFF', '-Donnxruntime_ENABLE_CUDA_PROFILING=OFF', '-Donnxruntime_ENABLE_ROCM_PROFILING=OFF', '-Donnxruntime_USE_XNNPACK=OFF', '-Donnxruntime_USE_CANN=OFF', '-DCMAKE_TLS_VERIFY=ON', '-DFETCHCONTENT_QUIET=OFF', '-Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF', '-Donnxruntime_ENABLE_MEMLEAK_CHECKER=OFF', '-DCMAKE_BUILD_TYPE=RelWithDebInfo', '-DCMAKE_PREFIX_PATH=/home/benni/Dokumente/git/onnxruntime/build/Linux/RelWithDebInfo/installed']' returned non-zero exit status 1.

### Visual Studio Version

-

### GCC / Compiler Version

cmake version 3.27.4

**Comment by tianleiwu** [comment]
Try older version of cmake like 3.27.1

**Comment by snnn** [comment]
Check your environment variables. cmake is not a C/C++ compiler, but the log shows it was used as a C/C++ compiler

```
-- Check for working CXX compiler: /home/benni/.local/bin/cmake
-- Check for working CXX compiler: /home/benni/.local/bin/cmake - broken
```

**Comment by BentiGorlich** [comment]
well that would be a shame if I completely messed that up :sweat_smile: 
gonna tell you tomorrow if gcc is the solution

**Comment by BentiGorlich** [comment]
Well that took a while...
I downloaded bot `aarch64-linux-gnu-gcc` and `aarch64-linux-gnu-g++`. Still the same problem. What environment variable do I have to set for the build script to use these?

**Comment by snnn** [comment]
But you said your Target platform is linux x86/64? Then you should not use an aarch64 compiler.

**Comment by BentiGorlich** [comment]
Because I don't have a clue how to build this thing and the documentation for it is not very in depth. The aarch64 compiler was mentioned in the doc somewhere that is why I used it... My target platform is basically a python package that can be build for chaqupy (android studio plugin) so I can run Mimic3 locally on my phone

**Comment by snnn** [comment]
Sorry I don't know how to build a python package for Android. The use is not supported yet.  We have an Android package, but it is not for Java.  And we have Linux python packages that you can use on Linux(not including Android).

**Comment by BentiGorlich** [comment]
So I can't build a python package for android with your build script?

**Comment by snnn** [comment]
It is beyond of my knowledge.
