### ISSUE TITLE
[Web] Failed to load model because protobuf parsing failed NextJS and Vercel

### ISSUE THREAD

**Issue by arnabtarwani** [microsoft/onnxruntime#17513]
Hi, I have been trying to solve this issue in Vercel however, the issue is persistent https://github.com/xenova/transformers.js/issues/295 
Can someone help me out with this please?

_Originally posted by @arnabtarwani in https://github.com/microsoft/onnxruntime/issues/13117#issuecomment-1715656371_

**Comment by xenova** [comment]
Update: https://github.com/xenova/transformers.js/issues/295#issuecomment-1715816214

Looks like the deployment environment was cutting off the larger model (to to memory/bandwidth constraints), leading to the above error.

So, this doesn't appear to be a bug with onnxruntime itself.
