### ISSUE TITLE
Unable to convert function return value to a Python type after creating inference session

### ISSUE THREAD

**Issue by jeffsaremi** [microsoft/onnxruntime#1754]
The last line in below snippet returns this error.
```
import onnxruntime as rt
sess = rt.InferenceSession("pipeline_vectorize.onnx")

import numpy
inp, out = sess.get_inputs()[0], sess.get_outputs()[0]
print("input name='{}' and shape={} and type={}".format(inp.name, inp.shape, inp.type))
print("output name='{}' and shape={} and type={}".format(out.name, out.shape, out.type))
```
The complete error is:
```
  File "onnx_example5.py", line 45, in <module>
    print("output name='{}' and shape={} and type={}".format(out.name, out.shape, out.type))
TypeError: Unable to convert function return value to a Python type! The signature was
        (arg0: onnxruntime.capi.onnxruntime_pybind11_state.NodeArg) -> List[object]
```

I will try uploading the model file. If I'm not successful just ask me for it

Here's the environment:
ubuntu 16.04
Python 3.5.2
Package              Version
-------------------- ----------------------
certifi              2019.6.16
chardet              3.0.4
cloudpickle          1.2.1
cycler               0.10.0
grpcio               1.19.0
idna                 2.8
keras2onnx           1.5.1
kiwisolver           1.1.0
matplotlib           3.0.3
mleap                0.11.0.dev0
nose                 1.3.7
nose-exclude         0.5.0
numpy                1.16.2
onnx                 1.4.1
onnxconverter-common 1.5.3
onnxmltools          1.4.1
onnxruntime          0.4.0
pandas               0.24.2
pip                  19.2.3
protobuf             3.9.1
pyarrow              0.13.0
pycurl               7.43.0
pygobject            3.20.0
pymssql              2.1.4
pyparsing            2.4.2
python-apt           1.1.0b1+ubuntu0.16.4.5
python-dateutil      2.8.0
pytz                 2019.2
pyviz                0.9.1
PyYAML               5.1.2
requests             2.22.0
retrying             1.3.3
scikit-learn         0.20.3
scipy                1.2.1
setuptools           20.7.0
six                  1.12.0
skl2onnx             1.5.1
ssh-import-id        5.5
tf2onnx              1.4.1
typing               3.7.4.1
typing-extensions    3.7.4
urllib3              1.25.3
wheel                0.33.6
winmltools           1.4.1

**Comment by jeffsaremi** [comment]
I'm not able to attach any files here. Just ping me if you need to see pipeline_vectorize.onnx
thanks

**Comment by skottmckay** [comment]
@jeffsaremi If you send me the model I'll take a look

**Comment by faxu** [comment]
@jeffsaremi is this still an active issue?

**Comment by faxu** [comment]
please reopen if further assistance is needed.
