### ISSUE TITLE
Custom logger is ignored by CreateEnvWithCustomLogger

### ISSUE THREAD

**Issue by samwebster** [microsoft/onnxruntime#17548]
### Describe the issue

CreateEnvWithCustomLogger(..) allows calling it multiple times, however its arguments are ignored after the first call. Specifically, supplying a custom logger doesn't work as the first supplied one is kept forever, even if it was destroyed. This can cause crashes, for example, when param is used after it has been deallocated.

Can the logger be moved to OrtSession instead?

### To reproduce

See OrtEnv::GetInstance - https://github.com/microsoft/onnxruntime/blob/5af6279440a0db698b0afbfc3de655400562831f/onnxruntime/core/session/ort_env.cc#L45

### Urgency

We've had to disable our custom logger to stop crashes which is far from ideal

### Platform

Other / Unknown

### OS Version

Any

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by snnn** [comment]
We cannot move it to session. If you search "LOGS_DEFAULT" in our code, there are a lot of matches. These code do not get the logger from a session.

**Comment by snnn** [comment]
When possible,  avoid creating OrtEnv multiple times in the same process.

**Comment by pranavsharma** [comment]
The env is supposed to be created only once in the entire process lifecycle. Trying to create it again will simply return the same old instance. This is not the correct usage of the env.

**Comment by ms-gavinkinsey** [comment]
If only one env is supposed to exist then subsequent calls to create another should fail.  There is absolutely no indication in the API documentation that it behaves like this.  All the CreateEnv* functions that take parameters ignore those parameters without any indication that they could do so.

Why not just allow multiple environments to be created?  I've written a quick PR that implements this.

**Comment by ms-gavinkinsey** [comment]
Original PR had some bugs, updated version has been tested and resolves this issue in my test environment.
