### ISSUE TITLE
Inference result is bad with a batched input

### ISSUE THREAD

**Issue by matovitch** [microsoft/onnxruntime#17566]
### Describe the issue

Hello,

The result of the model attached below **can be** (depending on the list of samples) wrong if I evaluate my samples in a "batch". If I infer the samples individually the results are always good.

Note that if the input vector is a list of zeros, the output of the model should be 0 and this is not the case in the example I provide to reproduce (but I have similar issue with non zero samples as well I thought it would be easier to investigate with 0 let me know if you want more examples).

The model was exported from PyTorch 1.13.1 and tested with OnnxRuntime 1.15.1 (and older) on multiple machines (CPU only).

Thank you for your support.

### To reproduce

Here is the model gzipped (onnx extension not supported): [torch.onnx.gz](https://github.com/microsoft/onnxruntime/files/12620813/torch.onnx.gz)

```python
import onnxruntime as ort

ort_torch = ort.InferenceSession('torch.onnx')

feat1 = [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]
feat2 = [ 6.99974684e-01,  2.61339078e+00,  2.11713195e-04,  2.19242897e-01, 
         -1.59346503e+00, -7.97099937e-01,  8.17811434e-01, -9.68987343e-01,
         -6.63136759e-01, -1.57733404e+00, -2.18476110e+00, -1.08287783e+00,
         -7.56763529e-01, -1.74636045e+00,  2.72836652e+00, -1.14533894e+00,
          5.20856497e-01,  4.87593694e-01,  2.22096981e-01, -8.26711131e-01,
         -2.12783208e+00,  1.27690800e+00,  3.68661603e-01, -6.38655839e-01,
          8.38186126e-01,  1.82472849e+00,  9.43643416e-01,  2.30010935e+00, -1.69257460e-01]

print(ort_torch.run(None, {'input_batch': [[feat1]], 'mask': [[1]]}))
print(ort_torch.run(None, {'input_batch': [[feat2]], 'mask': [[1]]}))
print(ort_torch.run(None, {'input_batch': [[feat1, feat2]], 'mask': [[1,1]]}))
```
Will produce the following result:
```python
[array([[0.]], dtype=float32)]
[array([[788.83374]], dtype=float32)]
[array([[ -1.3571774, 788.83374  ]], dtype=float32)]
```

### Urgency

This is in fact sadly urgent, we are using similar models at my company and we need to use ONNX to infer an increasing amount of samples but we also need our results to be accurate.

### Platform

Windows

### OS Version

WSL2 (Ubuntu18.04)

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by matovitch** [comment]
Ok, so we (I have some help) have a suspicion related to the clip operation which is taking a result depending on the batch given as input. So this is probably not related to onnxruntime but you can have a look if you want.

**Comment by matovitch** [comment]
This was indeed related to the clip. You can close this issue (I don't think I can do it).

**Comment by wangyems** [comment]
Do you mean there is discrepancy between "clip's definition and implementation?

**Comment by matovitch** [comment]
No, in the definition of my pytorch model the torch.clip was using a max bound that was dependent on the full tensor of input while it should have been dependent on the two first dimension of my input tensor such that the inference of feat1 and feat2 should have been independent.

Pytorch exporter is correct and so is the OnnxRuntime. I assumed a property of my model but it wasn't defined properly and so my assumption was broken.

I will close this issue. Thank you for your time. :)
