### ISSUE TITLE
ORT 1.16 Release Candidate Available for Testing

### ISSUE THREAD

**Issue by er3x3** [microsoft/onnxruntime#17560]
ORT 1.16 will be released in late September. Release candidate builds are available now for testing. If you encounter issues, please report them by responding in this issue.

Release branch: [rel-1.16.0](https://github.com/microsoft/onnxruntime/tree/rel-1.16.0)
Release manager: @er3x3

Pypi | Nuget | npm | Maven (Java)| iOS
--- | --- | --- | --- | ---
CPU: [1.16.0.dev20230908001](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/PyPI/ort-nightly/overview/1.16.0.dev20230908001)<br/>GPU: [1.16.0.dev20230908001](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/PyPI/ort-nightly-gpu/overview/1.16.0.dev20230908001) | CPU: [1.16.0-dev-20230908-1240-a9df3aea72](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/NuGet/Microsoft.ML.OnnxRuntime/overview/1.16.0-dev-20230908-1240-a9df3aea72)<br/>GPU (CUDA/TRT): [1.16.0-dev-20230908-1001-a9df3aea72](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/NuGet/Microsoft.ML.OnnxRuntime.Gpu/overview/1.16.0-dev-20230908-1001-a9df3aea72)<br/>DirectML: [1.16.0-dev-20230908-1021-a9df3aea72](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/NuGet/Microsoft.ML.OnnxRuntime.DirectML/overview/1.16.0-dev-20230908-1021-a9df3aea72)<br/>WindowsAI: [1.16.0-dev-20230908-0848-a9df3aea](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/NuGet/Microsoft.AI.MachineLearning/overview/1.16.0-dev-20230908-0848-a9df3aea) | onnxruntime-node: [1.16.0-dev.20230908-a9df3aea72](https://www.npmjs.com/package/onnxruntime-node/v/1.16.0-dev.20230908-a9df3aea72)<br/>onnxruntime-react-native [1.16.0-dev.20230908-a9df3aea72](https://www.npmjs.com/package/onnxruntime-react-native/v/1.16.0-dev.20230908-a9df3aea72)<br/>onnxruntime-web [1.16.0-dev.20230908-a9df3aea72](https://www.npmjs.com/package/onnxruntime-web/v/1.16.0-dev.20230908-a9df3aea72)|CPU: [1.16.0-rc2](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fonnxruntime/overview/1.16.0-rc2)<br/>GPU: [1.16.0-rc2](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fonnxruntime_gpu/overview/1.16.0-rc2) | [1.16.0-dev+20230908001.a9df3ae](https://github.com/CocoaPods/Specs/tree/master/Specs/3/a/a/onnxruntime-c/1.16.0-dev%2B20230908001.a9df3ae)

**Comment by lunixbochs** [comment]
I filed #17547 about lite custom ops in rel-1.16.0

**Comment by cbourjau** [comment]
> ORT 1.16 will be released in early February.

I think/hope this is meant to read "early October"?

**Comment by tianleiwu** [comment]
1.16 is available in [pypi](https://pypi.org/project/onnxruntime-gpu/) but release notes is a dead link: https://pypi.org/project/onnxruntime-gpu/

**Comment by faxu** [comment]
> 1.16 is available in [pypi](https://pypi.org/project/onnxruntime-gpu/) but the release notes is a dead link

Release notes are published now and were slightly delayed from pkg publishing.

**Comment by hariharans29** [comment]
Closing as ORT 1.16 release is done
