### ISSUE TITLE
Add compute kernel for Gelu (optional)

### ISSUE THREAD

**Issue by liqunfu** [microsoft/onnxruntime#17597]
### Describe the feature request

Gelu has been added to ONNX 1.15.0 (https://github.com/onnx/onnx/pull/5277). Need to implement compute kernel once ONNX 1.15.0 is in ORT (https://github.com/microsoft/onnxruntime/pull/17125).
 
Gelu is a function op. It is acceptable not to implement the op in ORT.

### Describe scenario use case

NA

**Comment by pengwa** [comment]
Merged in https://github.com/microsoft/onnxruntime/pull/19560
