### ISSUE TITLE
Add compute kernel for AffineGrid (optional)

### ISSUE THREAD

**Issue by liqunfu** [microsoft/onnxruntime#17598]
### Describe the feature request

AffineGrid has been added to ONNX 1.15.0 (https://github.com/onnx/onnx/pull/5225). Need to implement compute kernel once ONNX 1.15.0 is in ORT (https://github.com/microsoft/onnxruntime/pull/17125).

AffineGrid is a function op. It is acceptable not to implement the op in ORT.

### Describe scenario use case

NA

**Comment by snnn** [comment]
#17777
