### ISSUE TITLE
Update compute kernel for GridSample

### ISSUE THREAD

**Issue by liqunfu** [microsoft/onnxruntime#17600]
### Describe the feature request

GridSample has been updated in ONNX 1.15.0 (https://github.com/onnx/onnx/pull/5010). Need to implement compute kernel once ONNX 1.15.0 is in ORT (https://github.com/microsoft/onnxruntime/pull/17125).

This issue shall include re-enable test of GridSample op at
onnxruntime/test/testdata/onnx_backend_test_series_filters.jsonc (line 236)

### Describe scenario use case

onnx_test_runner shal pass ONNX test cases for the op

**Comment by tianlinzx** [comment]
@liqunfu Do you have any plan to impment GirdSample with 5 dimension input for Onnx-GPU ?
