### ISSUE TITLE
 Inference Time Error ([ONNXRuntimeError] : 10 : INVALID_GRAPH )

### ISSUE THREAD

**Issue by jaemjaem** [microsoft/onnxruntime#1760]
RuntimeError: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from new_yolo3_one_dimension.onnx failed:This is an invalid model. Type Error: Type 'tensor(float16)' of input parameter (Resize_scales) of operator (Resize) in node (Resize) is invalid.

I converted the onnx model to float 16 using winmltools. 

At the reference time, there is an RuntimeError. How do I fix it??

**Comment by snnn** [comment]
It's a converter issue. The model is invalid. Resize op can't take float16 input. @wenbingl

**Comment by snnn** [comment]
Please report the bug to winmltools.
