### ISSUE TITLE
[Documentation Request]

### ISSUE THREAD

**Issue by mincheHuang** [microsoft/onnxruntime#17607]
I can't find previous build commands and related explanation for various platform(windows, Linux, macOS, Android...) on this web page.

Thanks.

---
#### Document Details
* Title: Build from source
* Page: [https://onnxruntime.ai/docs/build/](https://onnxruntime.ai/docs/build/)
* Page Source: index.md

**Comment by skottmckay** [comment]
@faxu Documentation generation looks like it is broken.
