### ISSUE TITLE
Inference fails with `libc++abi terminating` error

### ISSUE THREAD

**Issue by pjjajal** [microsoft/onnxruntime#17616]
### Describe the issue

Inference with an ONNX model results in `libc++abi terminating` message and my shell terminating the process. Screenshot:
<img width="485" alt="image" src="https://github.com/microsoft/onnxruntime/assets/61586397/5c052a96-ecf1-4e68-9c25-17119d16e5ef">

When attempting this on a *different machine* we get the following error:
```
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
fish: Job 1, 'python test.py' terminated by signal SIGABRT (Abort)
```

And upon setting the environment variable we get the following error:
```
libc++abi: terminating
fish: Job 1, 'python test.py' terminated by signal SIGABRT (Abort)
```

The ONNX model used was originally a TensorFlow model that was converted to ONNX using the tensorflow-onnx model converter (tf2onnx). The [original model](https://drive.google.com/file/d/1UXXynBzgecqG5F_d3RARtBYnXl21El-7/view?usp=drive_link) (TensorFlow) was created using the [nnsmith](https://github.com/ise-uiuc/nnsmith) model generator. The TensorFlow model was converted as follows `python -m tf2onnx.convert --saved-model <path to tfnet> --output ./model.onnx --opset 16`

### To reproduce

Install Dependencies:
`pip install onnxruntime`
`pip install torch`

Steps: 
1. Download the [ONNX model](https://drive.google.com/file/d/1B_s1EZfxWKMqzj3yvYqlIT6z4r4epwER/view?usp=drive_link).
2. Download the [inputs](https://drive.google.com/file/d/1lulh2lMsrvOkk9wTzZE3tfKFYheGFGaw/view?usp=drive_link) and the [output names](https://drive.google.com/file/d/1DpOc7-eE735m78T4eaUm9NGezzLM1Oiw/view?usp=drive_link) (download to the same directory as the onnx model).
3. Run [test.py](https://drive.google.com/file/d/1SlwanNnf3Lboggp2m-NqQzTf1Wu7YoyJ/view?usp=drive_link) from the same directory as the files.

Test file: 
```
import onnxruntime as ort
import numpy as np
import torch

ort_inputs = torch.load("./ort_inputs.pt")
output_names = torch.load("./output_names.pt")
print(ort.get_available_providers())
sess = ort.InferenceSession("./model.onnx")
ort_outputs = sess.run(output_names=output_names, input_feed=ort_inputs)
```

### Platform

MacOS

### OS Version

13.5.2 (22G91)

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by pjjajal** [comment]
I made a mistake in the original issue. The platform is macOS.

**Comment by snnn** [comment]
The error comes from libiomp5 but we don't use openmp at all.

**Comment by pjjajal** [comment]
> The error comes from libiomp5 but we don't use openmp at all.

The error message referring to openmp comes from a co-worker who attempted to reproduce it. When I run the same script I get the following:

<img width="485" alt="image" src="https://github.com/microsoft/onnxruntime/assets/61586397/5e682b8d-e7dd-432d-85d1-70d710d4f410">

**Comment by snnn** [comment]
Could you please build ONNX Runtime from source in debug mode and give me a stacktrace ?  Here is the instructions: https://onnxruntime.ai/docs/build/inferencing.html

After that, you just install the newly built package and run
```bash
lldb -- python test.py
```
It will give us everything.

**Comment by pjjajal** [comment]
I built the latest ONNX Runtime from source and attempted this again.  I am not getting the error on the latest build, but it still occurs with v1.15.1.

**Comment by snnn** [comment]
We just published 1.16.0. Can you try that one instead?

**Comment by yuslepukhin** [comment]
We have not shipped with openmp for some time.

**Comment by pjjajal** [comment]
The model works fine with 1.16.0. 

What originally caused in 1.15.1?

**Comment by snnn** [comment]
Sorry I don't know. Without a stack trace I cannot tell what the issue is. And even if we know, we cannot go back to patch it. We only provide bug fixes to the latest release.
