### ISSUE TITLE
[ABSL] 

### ISSUE THREAD

**Issue by sodmlx2** [microsoft/onnxruntime#17633]
### Describe the issue

Hi!

Im using VCPKG for deps..

### Target platform

Windows 11

### Build script

When i compile onnxruntime with this parameters:

.\build.bat --config=Debug `
--enable_msvc_static_runtime `
--minimal_build `
--disable_ml_ops `
--disable_exceptions `
--disable_rtti `
--skip_tests `

### Error / output

This error:
C:\dev\vcpkg\installed\x64-windows\include\absl/container/internal/raw_hash_set.h(2362,30): error C2665: 'absl::lts_20230802::container_internal::StringHas
h::operator ()': nenhuma função sobrecarregada pode converter todos os tipos de argumento (compilando arquivo de origem C:\Users\marco.silva\onnxruntime\on
nxruntime\core\providers\cpu\math\cumsum.cc) [C:\Users\marco.silva\onnxruntime\build\Windows\Debug\onnxruntime_providers.vcxproj]

**Comment by snnn** [comment]
Do not use the absl from vcpkg.

**Comment by snnn** [comment]
Please try to build it in an environment without vcpkg.

**Comment by sodmlx2** [comment]
It is working fine!
thanks!

**Comment by snnn** [comment]
#20962
