### ISSUE TITLE
[Bug][Build]  include/onnxruntime_cxx_api.h:27:10: fatal error: onnxruntime_float16.h: No such file or directory  

### ISSUE THREAD

**Issue by csukuangfj** [microsoft/onnxruntime#17645]
### Describe the issue

I am integrating onnxruntime 1.16.0 into [sherpa-onnx](https://github.com/k2-fsa/sherpa-onnx).

However, I am getting the following [error](https://github.com/k2-fsa/sherpa-onnx/actions/runs/6257997702/job/16991224452#step:5:234):

https://github.com/k2-fsa/sherpa-onnx/actions/runs/6257997702/job/16991224452#step:5:234

```
  [ 19%] Building CXX object sherpa-onnx/csrc/CMakeFiles/sherpa-onnx-core.dir/context-graph.cc.o
  In file included from /home/runner/work/sherpa-onnx/sherpa-onnx/sherpa-onnx/csrc/cat.h:9,
                   from /home/runner/work/sherpa-onnx/sherpa-onnx/sherpa-onnx/csrc/cat.cc:5:
  /home/runner/work/sherpa-onnx/sherpa-onnx/build/temp.linux-x86_64-cpython-37/_deps/onnxruntime-src/include/onnxruntime_cxx_api.h:27:10: fatal error: onnxruntime_float16.h: No such file or directory
     27 | #include "onnxruntime_float16.h"
        |          ^~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  make[2]: *** [sherpa-onnx/csrc/CMakeFiles/sherpa-onnx-core.dir/build.make:90: sherpa-onnx/csrc/CMakeFiles/sherpa-onnx-core.dir/cat.cc.o] Error 1
```

I have checked the downloaded [onnxruntime lib](https://github.com/microsoft/onnxruntime/releases/download/v1.16.0/onnxruntime-linux-x64-1.16.0.tgz):

```
onnxruntime-linux-x64-1.16.0 fangjun$ tree .
.
├── GIT_COMMIT_ID
├── LICENSE
├── Privacy.md
├── README.md
├── ThirdPartyNotices.txt
├── VERSION_NUMBER
├── include
│   ├── cpu_provider_factory.h
│   ├── onnxruntime_c_api.h
│   ├── onnxruntime_cxx_api.h
│   ├── onnxruntime_cxx_inline.h
│   ├── onnxruntime_run_options_config_keys.h
│   ├── onnxruntime_session_options_config_keys.h
│   ├── onnxruntime_training_c_api.h
│   ├── onnxruntime_training_cxx_api.h
│   ├── onnxruntime_training_cxx_inline.h
│   └── provider_options.h
└── lib
    ├── libonnxruntime.so -> libonnxruntime.so.1.16.0
    └── libonnxruntime.so.1.16.0

2 directories, 18 files
```

You can see that `onnxruntime_float16.h` is not included in the released file.

### Urgency

It is very urgent as it shows the released files cannot be used to compile a project.

### Target platform

Linux

**Comment by csukuangfj** [comment]
@er3x3 Please have a look at this issue. Thanks!

**Comment by er3x3** [comment]
> @er3x3 Please have a look at this issue. Thanks!

https://github.com/microsoft/onnxruntime/pull/17637 This is the fix. Maybe you can try cherry-pick this commit if you want to build from source.

**Comment by csukuangfj** [comment]
Thank you for the reply.

I don't want to build onnxruntime from source. I only want to download the provided pre-built onnxruntime lib.

Could you fix the already released files?

**Comment by pranavsharma** [comment]
Just copy this file from the source tree. It doesn't need to be compiled into the ORT binary. It's a header only C++ internal file.

**Comment by csukuangfj** [comment]
Yes, I know how to fix it locally.

The question is that I am using github actions to download the file from the release page of
https://github.com/microsoft/onnxruntime

IMHO,  the released files should work as they are without any modification.

**Comment by csukuangfj** [comment]
I believe I am not the only one having this issue.

If it is not fixed in the released files, more and more people will have this issue once they download them and try to use them in their own projects.

**Comment by csukuangfj** [comment]
If you don't want to modify the released files, please release a new version, e.g., V1.16.1

**Comment by mszhanyi** [comment]
We need to add a test to cover this issue.

**Comment by csukuangfj** [comment]
> We need to add a test to cover this issue.

Yes, I agree. It is a surprise that there has been no such test to cover the released files.

**Comment by eshack94** [comment]
I am also seeing this issue. I'm on MacOS arm64.

**Comment by mastash3ff** [comment]
Can confirm this issue exists as well. The onnxruntime_float16.h is not included in the build releases 1.15 and higher.

**Comment by RamilDautov** [comment]
Ran into the same problem on Debian 11, x64

**Comment by pranavsharma** [comment]
Addressed in the main branch. Patch release with this fix coming up next week.

**Comment by LightSun** [comment]
same problem

**Comment by ForestWang** [comment]
same too

**Comment by Matthew-CN** [comment]
In2025,I also stepped into a pitfall and came to check in.hahaha
