### ISSUE TITLE
[CoreML] Adapt to `MLMultiArray.dataPointer` being deprecated

### ISSUE THREAD

**Issue by NickLucche** [microsoft/onnxruntime#17652]
### Describe the issue

Hey, 

I've seen we're using this `MLMultiArray.dataPointer` method here https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/providers/coreml/model/model.mm#L327 to access the underlying memory before moving that to a C lifetime-managed location.

I noticed this method appears to be deprecated on [Apple docs](https://developer.apple.com/documentation/coreml/mlmultiarray/2881220-datapointer?language=objc). I am merely speculating, but maybe is it because they support non-contiguously stored `MLMultiArray`s..?
My question is should we do something about this, like using some of the other non-deprecated element access methods (although it may decrease performance compared to `memcpy`), or are we sure this won't ever cause issues going forward? 

### To reproduce

-

### Platform

iOS

### OS Version

/

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

1.16.0

### ONNX Runtime API

C++/C

### Architecture

ARM64

### Execution Provider

CoreML

**Comment by edgchen1** [comment]
Good point. It's probably a good idea to move away from the deprecated API in case it gets removed later.

I think maybe we can use [getBytesWithHandler:](https://developer.apple.com/documentation/coreml/mlmultiarray/3929554-getbyteswithhandler?language=objc) and verify that we have a contiguous layout by checking [strides](https://developer.apple.com/documentation/coreml/mlmultiarray/2879222-strides?language=objc).

**Comment by NickLucche** [comment]
Sounds like a plan, if it's not contiguous we just copy each block into `output_buffer` right? Or should we like panic as unsupported? I am not sure what was the original intent in moving to non-contiguous by Apple to be honest..
Anyways, will you accept PR on the issue or do you have it covered?

**Comment by edgchen1** [comment]
Sorry for the delayed response. I think either approach is fine. It may be simpler to just treat a non-contiguous buffer as unsupported initially and we can see if we actually do run into such a case.

PRs are welcome. :)

Otherwise, we can get to it eventually.

**Comment by NickLucche** [comment]
Sure I am on it :)

**Comment by edgchen1** [comment]
Update: PR #17726 is open, waiting for input about minimum MacOS version to support.
