### ISSUE TITLE
[Documentation Request]

### ISSUE THREAD

**Issue by jamjamjon** [microsoft/onnxruntime#17662]
[Enter feedback here]

I want Rust.

---
#### Document Details
* Title: Get Started
* Page: [https://onnxruntime.ai/docs/get-started/](https://onnxruntime.ai/docs/get-started/)
* Page Source: index.md

**Comment by natke** [comment]
Thank you @jamjamjon. We have rust docs in progress. Will keep you posted

**Comment by jamjamjon** [comment]
When will you guys release rust version?  Now I am using ort crate which is rust binding of onnxruntime.  Will official version be better than that? What are the features will have in onnxruntime-rust?

**Comment by wujian752** [comment]
I want Rust too
