### ISSUE TITLE
[Performance] 

### ISSUE THREAD

**Issue by Riofd** [microsoft/onnxruntime#17699]
### Describe the issue

I tried to reproduce the code in this [repository](https://github.com/Clarmy/pangu-weather-verify/tree/main) (the model and onnx model are in this [repository](https://github.com/198808xc/Pangu-Weather/tree/main#global-weather-forecasting-inference-using-the-trained-models)), but in the original paper, the author claimed that it could take 1.4 seconds to complete inference on a single V100, while I took about 240 seconds to complete it on RTX3090. 

### To reproduce

The packages related to onnx in my conda environment are as follows:
```
onnx 1.13.1
onnxruntime gpu 1.9.0
```
I confirm that my GPU can be used normally in Pytorch, but when I completed this 240 second inference using onnx, nvidia smi showed that my GPU was not used, onnx_ The code related to the session is as follows:
```
if gpu:
        cuda_provider_options = {
            "arena_extend_strategy": "kSameAsRequested",
            "device_id": 0,
        }

        ort_session = ort.InferenceSession(
            modelfp,
            sess_options=options,
            providers=[("CUDAExecutionProvider", cuda_provider_options)],
        )
        print("Using gpu for inference.")
else:
        ort_session = ort.InferenceSession(
            modelfp, sess_options=options, providers=["CPUExecutionProvider"]
        )
```

### Platform

Linux

### OS Version

20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.9.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.2

### Is this a quantized model?

Yes

**Comment by tianleiwu** [comment]
@Riofd, if GPU is not used, it is likely the code used CPUExecutionProvider.
  Could you try `pip install onnxruntime-gpu` instead of building from source, and remove the code using CPUExecutionProvider in test?

**Comment by Riofd** [comment]
> @Riofd, if GPU is not used, it is likely the code used CPUExecutionProvider. Could you try `pip uninstall onnxruntime` and `pip install onnxruntime-gpu` instead of building from source, and remove the code using CPUExecutionProvider in test?
Thanks for your help, but when I remove the code using CPUExecutionProvider, the inference speed is still very slow. I wonder if the version of onnx would influence the inference speed since the author said it should run on cuda==11.6 and the cudnn==8.2.4 for Linux.

**Comment by tianleiwu** [comment]
@Riofd,
I tested with onnxruntime-gpu 1.16, and the latency in my machine (RTX 4090) is 1 seconds per inference:
<img width="369" alt="image" src="https://github.com/microsoft/onnxruntime/assets/30328909/f1ff9b95-b6a8-41c4-8dda-ba3827718a42">

It is likely caused by your environment setup. Could you remove old cuda and cudnn, and reinstall CUDA 11.8, cuDNN 8.5~8.9, and onnxruntime-gpu 11.6, and try again?
