### ISSUE TITLE
read model output from c++

### ISSUE THREAD

**Issue by nlyf** [microsoft/onnxruntime#1769]
Hi, I have a simple scikit-learn model. as in [example](http://onnx.ai/sklearn-onnx/auto_examples/plot_tfidfvectorizer.html) 

With python is everything fine, but I'd like to use model from C API.
For that purpose i used [example](https://github.com/microsoft/onnxruntime/blob/master/docs/C_API.md).
 Everything is fine but I can not get results from my model because of type convertion. 
```c++
/onnxruntime_src/include/onnxruntime/core/framework/ml_value.h:42 T* OrtValue::GetMutable() [with T = onnxruntime::Tensor] onnxruntime::DataTypeImpl::GetType<T>() == type_ was false. N11onnxruntime14TensorTypeBaseE != N11onnxruntime12SequenceTypeISt6vectorISt3mapIlfSt4lessIlESaISt4pairIKlfEEESaIS9_EEEE
```
But I know that onnx supports [Sequence<Map<int,float>>](https://github.com/Microsoft/onnxruntime/issues/156#issuecomment-466512284)
My c++ code looks like this:
```c++
CHECK_STATUS(OrtRun(session, NULL, input_node_names.data(), (const OrtValue* const*)&input_tensor, 1, output_node_names.data(), 1, &output_tensor));
  void ** data;
  CHECK_STATUS(OrtGetTensorMutableData(output_tensor, data));
```
I've seen simmiar [issues](https://github.com/microsoft/onnxruntime/issues/1568) but there was no hint. Can anyone help?

**Comment by snnn** [comment]
Hi @pranavsharma, could you help?

**Comment by nlyf** [comment]
@snnn, @pranavsharma can I have any help?

Thanks in advance

**Comment by pranavsharma** [comment]
@nlyf OrtGetTensorMutableData works for tensors only. For maps/sequences, you should use OrtGetValue to fetch the outputs. Pasting the relevant API docs form the C header files. There are also examples of doing this in C++ [here](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_nontensor_types.cc). Let me know if any of this is not clear. Thanks!

```
/**
   * If input OrtValue represents a map, you need to retrieve the keys and values
   * separately. Use index=0 to retrieve keys and index=1 to retrieve values.
   * If input OrtValue represents a sequence, use index to retrieve the index'th element
   * of the sequence.
   */
ORT_API_STATUS(OrtGetValue, _In_ const OrtValue* value, int index, _Inout_ OrtAllocator* allocator, _Outptr_ OrtValue** out);

/**
   * Returns 2 for type map and N for sequence where N is the number of elements
   * in the sequence.
   */
ORT_API_STATUS(OrtGetValueCount, _In_ const OrtValue* value, _Out_ size_t* out);
```

**Comment by hariharans29** [comment]
Do you still need help with this @nlyf or does @pranavsharma 's answer help ?
