### ISSUE TITLE
lib missing in onnxruntime-osx-arm64-1.16.0 package

### ISSUE THREAD

**Issue by miniTsl** [microsoft/onnxruntime#17702]
### Describe the issue

<img width="1524" alt="image" src="https://github.com/microsoft/onnxruntime/assets/65892960/604e5026-ccdc-4606-8b84-9be41cdf9e6b">
where is the header "onnxruntime_float16.h"?

### To reproduce

just include onnxruntime_cxx_api.h in c++ code and there is a header missing in it ...

### Platform

Mac

### OS Version

13.5.2

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

e7a0495

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

CoreML

### Execution Provider Library Version

release 1.16.0

**Comment by snnn** [comment]
Dup
