### ISSUE TITLE
Slow inference speed when latency is added between inference iterations [Performance] 

### ISSUE THREAD

**Issue by minyeo** [microsoft/onnxruntime#17711]
### Describe the issue

Adding latency between inference iterations slows inference speed.
Why is it slowing down?
And how do you struggle to maintain the speed as fast as when there is no latency?

**Repeat 100 times without latency:**

run time :  1.3255867958068848
run time :  0.020943641662597656
run time :  0.02097320556640625
run time :  0.02194070816040039
run time :  0.02191329002380371
run time :  0.020945072174072266
run time :  0.020943880081176758
run time :  0.020972013473510742
run time :  0.02094435691833496
run time :  0.021912813186645508
run time :  0.020943641662597656
run time :  0.020972251892089844
run time :  0.020943403244018555
run time :  0.021941423416137695
run time :  0.021941184997558594
run time :  0.020943880081176758
run time :  0.020944833755493164
run time :  0.021965503692626953
run time :  0.02191638946533203
run time :  0.020945072174072266
run time :  0.02096867561340332
run time :  0.020917892456054688
run time :  0.02094435691833496
run time :  0.021941423416137695
run time :  0.02094268798828125
run time :  0.021970033645629883
run time :  0.021914005279541016
run time :  0.02096867561340332
run time :  0.021916627883911133
run time :  0.021965503692626953
run time :  0.021917104721069336
run time :  0.020972251892089844
run time :  0.02093982696533203
run time :  0.021945714950561523
run time :  0.021912813186645508
run time :  0.021941661834716797
run time :  0.020972013473510742
run time :  0.02191329002380371
run time :  0.020943641662597656
run time :  0.020972490310668945
run time :  0.0219118595123291
run time :  0.020943880081176758
run time :  0.020943880081176758
run time :  0.020971298217773438
run time :  0.020943880081176758
run time :  0.021942138671875
run time :  0.022938013076782227
run time :  0.02094292640686035
run time :  0.021942138671875
run time :  0.020972251892089844
run time :  0.02191329002380371
run time :  0.021941184997558594
run time :  0.02094292640686035
run time :  0.020943880081176758
run time :  0.02094554901123047
run time :  0.021939992904663086
run time :  0.021942615509033203
run time :  0.021941184997558594
run time :  0.02094292640686035
run time :  0.020944595336914062
run time :  0.020972013473510742
run time :  0.021913528442382812
run time :  0.020943880081176758
run time :  0.0219419002532959
run time :  0.02094411849975586
run time :  0.020946741104125977
run time :  0.020940303802490234
run time :  0.022938013076782227
run time :  0.020945072174072266
run time :  0.020967721939086914
run time :  0.021916627883911133
run time :  0.021942615509033203
run time :  0.020942211151123047
run time :  0.0219423770904541
run time :  0.020972013473510742
run time :  0.021912813186645508
run time :  0.020944595336914062
run time :  0.021941184997558594
run time :  0.02194070816040039
run time :  0.021941184997558594
run time :  0.020944833755493164
run time :  0.02094292640686035
run time :  0.020943641662597656
run time :  0.021941661834716797
run time :  0.02094411849975586
run time :  0.020971059799194336
run time :  0.02191305160522461
run time :  0.02097320556640625
run time :  0.021912097930908203
run time :  0.021940946578979492
run time :  0.020975112915039062
run time :  0.021910429000854492
run time :  0.020943880081176758
run time :  0.0219423770904541
run time :  0.020943880081176758
run time :  0.021941184997558594
run time :  0.020943880081176758
run time :  0.020943164825439453
run time :  0.021942138671875
run time :  0.020968914031982422

**Repeat 100 times, adding 1 second of latency for each iteration:**

run time :  1.2544493675231934
run time :  0.021942138671875
run time :  0.022940397262573242
run time :  0.022910594940185547
run time :  0.10660862922668457
run time :  0.10172891616821289
run time :  0.1735377311706543
run time :  0.022940397262573242
run time :  0.05585169792175293
run time :  0.07668614387512207
run time :  0.15158629417419434
run time :  0.11369776725769043
run time :  0.10970902442932129
run time :  0.10671591758728027
.....

### To reproduce

```
import os
from config import get_config

import time
from datetime import datetime

import cv2
import numpy as np

import mmap

import onnx
import onnxruntime as ort


# define input/output schema --
model_dict = {0 : '../weight/yolov5_l_mavin.onnx'} # 검사 Program에서 던지는 model의 idx 값

# Use GPU
providers = ['CUDAExecutionProvider','CPUExecutionProvider']

bytes_list = cv2.imread("E:/edge_onnx/inference_edge/YOLOv5/data/sample/test.jpg")
img_file = [cv2.resize(bytes_list, dsize=(640, 640))]
img_norm = np.array(img_file, dtype=np.float32) / 255.0

# ort.set_default_logger_severity(0)
#
# so = ort.SessionOptions()
#
# so.inter_op_num_threads = 1
# so.intra_op_num_threads = 1
# so.enable_mem_pattern = False   # default is True
#
# print(so.inter_op_num_threads)
# print(so.intra_op_num_threads)

model = ort.InferenceSession(model_dict[0], providers=providers)

for i in range(100):
    tic = time.time()
    boxes, scores, labels = model.run(['boxes', 'scores', 'labels'], {'x': img_norm})
    print("run time : ", time.time() - tic)
    time.sleep(1)
# print(labels)
```

### Urgency

by mid-October

### Platform

Windows

### OS Version

Windows10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

python onnxruntime-gpu 1.13.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU, CUDA

### Execution Provider Library Version

CUDA 11.2 

### Model File

I can't upload it because of security issues
Using yolov5 model

### Is this a quantized model?

Yes

**Comment by hariharans29** [comment]
Dupe of https://github.com/microsoft/onnxruntime/issues/7449 and https://github.com/microsoft/onnxruntime/issues/10226 ?

**Comment by minyeo** [comment]
It worked!!! 
You saved my life
Thank you!!!
