### ISSUE TITLE
RUNTIME_EXCEPTION occurs when running a per-channel quantized model in QDQ format 

### ISSUE THREAD

**Issue by feihongfiona** [microsoft/onnxruntime#17718]
### Describe the issue

I have a per-channel quantized model in QDQ format. Running the model gets the following terminal interrupt :

_onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running DequantizeLinear node. Name:'W_DequantizeLinear/duplicated' Status Message: /private/var/folders/nz/j6p8yfhx1mv_0grj5xl4650h0000gp/T/abs_a92wmqsrpo/croot/onnxruntime_1689679134480/work/onnxruntime/core/providers/cpu/quantization/quantize_linear.cc:36 void onnxruntime::PrepareForQDQ(const onnxruntime::TensorShape &, const onnxruntime::Tensor &, const onnxruntime::Tensor *, int64_t, int64_t &, int64_t &, int64_t &) scale.Shape().NumDimensions() == 1 && scale.Shape()[0] == broadcast_dim was false. scale must be 1D tensor with size 525_

I trace the source code bellow:
```
template <typename T>
class DequantizeLinear final : public OpKernel {
 public:
  DequantizeLinear(const OpKernelInfo& info) : OpKernel(info) {
    if (!info.GetAttr<int64_t>("axis", &axis_).IsOK()) {
      axis_ = 1;   
    }
  }

  Status Compute(OpKernelContext* context) const override;

 private:
  int64_t axis_;
};
```

I think the _axis__ should default to 0

### To reproduce

[Conv_layer_quant_U8U8_perch_sym01_QDQ.onnx.zip](https://github.com/microsoft/onnxruntime/files/12737417/Conv_layer_quant_U8U8_perch_sym01_QDQ.onnx.zip)

### Platform

Mac

### OS Version

13.5

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by wschin** [comment]
Default is 1 per [ONNX standard](https://github.com/onnx/onnx/blob/main/docs/Operators.md#attributes-25).
