### ISSUE TITLE
iOS static library build from source code , symbol visibility issue

### ISSUE THREAD

**Issue by sarojlo** [microsoft/onnxruntime#17722]
### Describe the issue

- We have built static onnxruntime lib from source code for iOS . THis creates many static library like libonnxruntime_session.a , onnxruntime_optimizer.a , onnxruntime_providers.a ... libabsl.a all of them have all symbols in global namespace.
- As we are building a static library for end customer from our code we then used libtool to create a single library using our code and all the onnxruntime libraries
- now issue is custome also using libabsl.a may be diffrent version and as all symbols are in global namespace its causing symbol collision.

Libraries which we combined from onnxruntime are 

libclog.a libcpuinfo.a libonnxruntime_optimizer.a  libonnxruntime_util.a libonnxruntime_common.a libonnxruntime_flatbuffers.a libonnxruntime_framework.a libonnxruntime_graph.a  libonnxruntime_mlas.a libonnxruntime_providers.a libflatbuffers.a libonnx.a libonnxruntime_session.a libonnx_proto.a libprotobuf-lite.a libre2.a libnsync_cpp.a libabsl.a

### To reproduce

Use static build

### Urgency

Yes. Customer issue

### Platform

iOS

### OS Version

iosx64 build compiled on MAC

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Execution Provider Library Version

default

**Comment by snnn** [comment]
I believe static libraries have no visibility control.  This is called: diamond dependency problem.  There is no Silver Bullet for this problem. On the other hand, if the operating system can support dynamic libraries(e.g. DLL, shared libraries), they can help.
