### ISSUE TITLE
quantize_static not quantizing Conv bias to int8 but int32

### ISSUE THREAD

**Issue by ChickenTarm** [microsoft/onnxruntime#17738]
### Describe the issue

I have quantized my model with these settings
```
"quant_format": QuantFormat.QDQ,
            "calibrate_method": CalibrationMethod.MinMax,
            "per_channel": True,
            "activation_type": QuantType.QInt8,
            "weight_type": QuantType.QInt8,
            "nodes_to_exclude": nodes_to_exclude[config.MODEL.node.node_function],
            "extra_options": {
                "ActivationSymmetric": True,
                "WeightSymmetric": True,
            },
```

however for every single convolution, the weights are quantized correctly to int8; bias is not quantized to be int8 but int32 as seen by the screenshots. What would be causing this issue? I suspect this is the issue that causes my conversion to trt engine to fail. It fails when reaching the conv bias node

![Screenshot 2023-09-28 at 10 42 48 PM](https://github.com/microsoft/onnxruntime/assets/13770222/7d66c492-3db6-45a9-ac38-c3416dc08680)
![Screenshot 2023-09-28 at 10 43 05 PM](https://github.com/microsoft/onnxruntime/assets/13770222/95fdaf34-8913-4c0d-9b79-10baaa439a7c)

### To reproduce

I run quantize_static on a yolor model.

### Platform

Linux

### OS Version

Ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16

### ONNX Runtime API

Python

### Architecture

X86

### Execution Provider

Default CPU

**Comment by yufenglee** [comment]
This is by design for better performance. For the TRT engine, are you talking about trt itself or trt ep? If trt ep, please take a look at this example here: https://github.com/microsoft/onnxruntime-inference-examples/tree/980def0d59147b6117523cc756c89a10079ff8e4/quantization/object_detection/trt/yolov3. If trt itself, you may need to use their toolchain.

**Comment by ShuaiShao93** [comment]
I see a similar issue, did you fix this? @ChickenTarm

**Comment by bilalsoomro** [comment]
I've found that setting the "QuantizeBias" option to False solves the issue and enables the quantized model to run with TRT.

```
quantize_static(input_model_path,
    output_model_path,
    dr,
    activation_type=QuantType.QInt8,
    weight_type=QuantType.QInt8,
    quant_format=QuantFormat.QDQ,
    extra_options={
        "ActivationSymmetric" : True, # symmetrize calibration data for activations (default is False).
        "WeightSymmetric" : True # symmetrize calibration data for weights (default is True).
        "QuantizeBias": False
    },
    per_channel=True
)
```
