### ISSUE TITLE
RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from xxxxxxxxx.onnx failed:Type Error: Type parameter (T) bound to different types (tensor(float16) and tensor(float) in node ().

### ISSUE THREAD

**Issue by z00389191** [microsoft/onnxruntime#1774]
**Describe the bug**
I want to convert the onnx model from float32 to float16, convert is successful ,but load model failed, I find the pad layer dont be converted  completely, the attribute of value datatype still is float, not my expect float16.
RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from xxxxxxxxxxx.onnx failed:Type Error: Type parameter (T) bound to different types (tensor(float16) and tensor(float) in node ().

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary):binary
- ONNX Runtime version:0.3.0
- Python version:3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by skottmckay** [comment]
Can you clarify 'attribute of valuedate'? There's a 'value' attribute which is of type 'float' regardless of the input data type, and a 'data' input. Not sure which one you're referring to. Did the conversion incorrectly convert the 'value' attribute to float16?

**Comment by z00389191** [comment]
> Can you clarify 'attribute of valuedate'? There's a 'value' attribute which is of type 'float' regardless of the input data type, and a 'data' input. Not sure which one you're referring to. Did the conversion incorrectly convert the 'value' attribute to float16?
The Pad layer 'value' attribute is float，the  'data' input is float16

**Comment by z00389191** [comment]
> > Can you clarify 'attribute of valuedate'? There's a 'value' attribute which is of type 'float' regardless of the input data type, and a 'data' input. Not sure which one you're referring to. Did the conversion incorrectly convert the 'value' attribute to float16?
> > The Pad layer 'value' attribute is float，the  'data' input is float16

@skottmckay, Hi, do you know how to solve the problem? Thank you!

**Comment by skottmckay** [comment]
The 'output' will also need to be float16.

**Comment by z00389191** [comment]
> The 'output' will also need to be float16.

![image](https://user-images.githubusercontent.com/45361817/64509570-9b4e9000-d312-11e9-90aa-485365592da1.png)
this layer is ok？ but loadding the onnx model is failed，the error info is “ [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from xxxxxxxxx.onnx failed:Type Error: Type parameter (T) bound to different types (tensor(float16) and tensor(float) in node ().” do you know why?

**Comment by skottmckay** [comment]
That node looks ok and most likely a different one is the issue. Are you able to share the model? 

FWIW it's generally good to give each node a name so that it's easier to debug any issues.

**Comment by z00389191** [comment]
what is "FWIW"?

**Comment by skottmckay** [comment]
'for what it's worth'

**Comment by hariharans29** [comment]
Just like #1764, this is likely because of an invalid ONNX model. Please upload your model (if you can share it) and I will help you identify the node/layer where the problem lies. You can open a bug against the project that helped you get the model with that information.

**Comment by hariharans29** [comment]
Closing this issue as this is not an ORT issue, rather the ONNX model is invalid as it deviates from spec. 

@z00389191 - Please share your model and I will help you identify the exact issue which you can use to file a bug in the appropriate project. Thanks!
