### ISSUE TITLE
AttributeError: FLOAT8E4M3FN while Quantizing T5

### ISSUE THREAD

**Issue by SuperSecureHuman** [microsoft/onnxruntime#17754]
### Describe the issue

While trying to use quantize_dynamic on onnx model, I get the error `AttributeError: FLOAT8E4M3FN` 

### To reproduce

Check this notebook

https://github.com/SuperSecureHuman/fastT5/blob/master/sample.ipynb

### Urgency

Low

### Platform

Linux

### OS Version

Arch, Linux 6.5.3-zen1-1-zen

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU, OpenVINO

**Comment by askhade** [comment]
@xadupre FYI

**Comment by xadupre** [comment]
Which version of onnx are you using? Is it possible to use the latest one?

**Comment by SuperSecureHuman** [comment]
I would have to go with a new env then, gimme some time

**Comment by SuperSecureHuman** [comment]
New env works well, but not in my current env. I am not really sure if something crept into my env.

I am closing this for now, will reopen if I find anything weird
