### ISSUE TITLE
Can't find OrtSessionOptionsAppendExecutionProvider_Tensorrt

### ISSUE THREAD

**Issue by GentBinaku** [microsoft/onnxruntime#17753]
### Describe the issue

<img width="470" alt="image" src="https://github.com/microsoft/onnxruntime/assets/5422055/b1a68392-8f26-456f-8a97-cd3d2c4a1b6e">

```
PS C:\onnxruntime> ./build.bat --config RelWithDebInfo `y
>>   --build_shared_lib --parallel `
>>   --use_cuda --cuda_version 11.8 --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8" `
>>   --cudnn_home "C:\nvidia\cudnn-windows-x86_64-8.9.5.29_cuda11-archive" `
>>   --use_tensorrt --tensorrt_home "C:\nvidia\TensorRT-8.6.1.6" `
>>   --use_dnnl --use_dml --cmake_generator "Visual Studio 17 2022" --skip_tests
```

### To reproduce

1. Build latest main
2.  Try to use OrtSessionOptionsAppendExecutionProvider_Tensorrt

### Platform

Windows

### OS Version

22621.2283

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.16.0

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

TensorRT

### Execution Provider Library Version

CUDA 11.8 Tensorrt 8.6.16

**Comment by GentBinaku** [comment]
Solved please include 
```
#include <onnxruntime/core/providers/tensorrt/tensorrt_provider_factory.h>
#include <onnxruntime/core/providers/tensorrt/tensorrt_provider_options.h>
```

**Comment by jywu-msft** [comment]
it's better to include onnxruntime_c_api.h and use the updated api SessionOptionsAppendExecutionProvider_TensorRT_V2

**Comment by GentBinaku** [comment]
> SessionOptionsAppendExecutionProvider_TensorRT_V2

I can't find it?

**Comment by jywu-msft** [comment]
> > SessionOptionsAppendExecutionProvider_TensorRT_V2
> 
> I can't find it?

https://onnxruntime.ai/docs/api/c/struct_ort_api.html#a56e18c1d27b7ed78dcfc82998a550885
https://github.com/microsoft/onnxruntime/blob/e7a0495a874251e9747b2ce0683e0580282c54df/include/onnxruntime/core/session/onnxruntime_c_api.h#L2889
