### ISSUE TITLE
[Build] Execution Provider header files are not included in dynamic onnxruntime.framework (Apple build)

### ISSUE THREAD

**Issue by john-dance** [microsoft/onnxruntime#17767]
### Describe the issue

While building from source, and execution providers are specified in the build, their headers (such as cpu_provider_factory.h) are included in static_framework/onnxruntime.framework, but not in the dynamic version.

They were included in the v1.15.1 build.

### Target platform

iOS, MacOS

### Build script

    python3 tools/ci_build/build.py \
        --cmake_extra_defines "CMAKE_VERBOSE_MAKEFILE=ON" \
        --cmake_extra_defines "CMAKE_C_FLAGS=$extra_flags" \
        --cmake_extra_defines "CMAKE_CXX_FLAGS=$extra_flags" \
        --build_dir "$build_dir" \
        --cmake_path $(xcrun -f cmake) \
        --config $build_type \
        --build_apple_framework \
        --parallel \
        --use_xcode \
        --use_cache \
        --osx_arch $build_target \
        --ios_sysroot $build_sdk \
        --apple_deploy_target $build_deploy_target \
        --use_xnnpack \
        --use_coreml \
        --skip_tests \
        --path_to_protoc_exe "$PROTOC" \

### Error / output

When building against the dynamic onnxruntime.framework, the header file is not found.

**Comment by snnn** [comment]
All the APIs you need should be in https://github.com/microsoft/onnxruntime/blob/main/include/onnxruntime/core/session/onnxruntime_c_api.h.  Like SessionOptionsAppendExecutionProvider_CUDA_V2 . Correct me if I was wrong.

**Comment by john-dance** [comment]
We use COREMLFlags for the options to OrtSessionOptionsAppendExecutionProvider_CoreML. They are only defined in coreml_provider_factory.h.

**Comment by edgchen1** [comment]
I think I know what the issue is. Regarding where the fix should go, can you build from main or should we try to get the fix in a patch release?

**Comment by john-dance** [comment]
Thank you @edgchen1. We build from a specified release. But meanwhile, I can grab your PR and patch locally.
