### ISSUE TITLE
python3 setup.py bdist_wheel  running bdist_wheel running build running build_py error: package directory 'onnxruntime/backend' does not exist

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#1776]
python3 setup.py bdist_wheel

running bdist_wheel
running build
running build_py
error: package directory 'onnxruntime/backend' does not exist

**Comment by skottmckay** [comment]
Please use build.sh/build.bat with --build_wheel instead of calling setup.py directly.

**Comment by jinfagang** [comment]
@skottmckay  I think the INSTALL doc should be update. it indicates users to build like `python3 setup.py bdist_wheel` way.

**Comment by skottmckay** [comment]
Where is the INSTALL document you're referring to?

**Comment by jinfagang** [comment]
![image](https://user-images.githubusercontent.com/21303438/64509938-71499d80-d313-11e9-87e6-e1a9b5bbad36.png)

**Comment by skottmckay** [comment]
#4 are instructions to install onnx not onnxruntime.
