### ISSUE TITLE
how to use the runtime-release

### ISSUE THREAD

**Issue by gkUwen** [microsoft/onnxruntime#1780]

**Comment by skottmckay** [comment]
Not sure exactly what you're asking. Have you looked at the examples and tutorials? https://github.com/microsoft/onnxruntime#examples-and-tutorials

**Comment by faxu** [comment]
please reopen if you need additional assistance and provide the details by following the github issue template. https://github.com/microsoft/onnxruntime/tree/master/.github/ISSUE_TEMPLATE
