### ISSUE TITLE
how to run fp16 model using ort c api?

### ISSUE THREAD

**Issue by pango99** [microsoft/onnxruntime#1782]
I use the script from https://github.com/onnx/onnx-docker/blob/master/onnx-ecosystem/converter_scripts/float32_float16_onnx.ipynb to convert a DeepLabV3 fp32 model to fp16,and then use ort c api to load the fp16 model,but OrtCreateSession() call failed, and report below error:
Load model from deeplabv3_xception_tf_dim_ordering_tf_kernels_all_fp16.onnx failed:This is an invalid model. Type Error: Type 'tensor(float16)' of input parameter (scales__14) of operator (Resize) in node (Resize__17) is invalid.

so, what's the problem of my model? how can I run the fp16 model on ort?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10 Pro
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 0.5.0
- Python version: 3.0
- Visual Studio version (if applicable): VS2017
- CUDA/cuDNN version: CUDA10 + CUDNN7.5
- GPU model and memory: RTX2070 + 6G

**Comment by skottmckay** [comment]
The 'scales' input parameter only supports 'float' as a type. https://github.com/onnx/onnx/blob/master/docs/Operators.md#Resize

@vinitra do you know who owns the conversion logic? Possibly it's not handling Resize correctly.

**Comment by pango99** [comment]
> 
> 
> The 'scales' input parameter only supports 'float' as a type. https://github.com/onnx/onnx/blob/master/docs/Operators.md#Resize
> 
> @vinitra do you know who owns the conversion logic? Possibly it's not handling Resize correctly.


So is it means I cant run my fp16 model on current version ort ?

**Comment by skottmckay** [comment]
The model is currently invalid as it's using an unsupported type for the 'scales' input to the Resize operator. Due to that it's an invalid ONNX model, which is why ORT is not running it.
