### ISSUE TITLE
 29873 floating point exception  python3 demo_onnxrt_maskrcnn.py

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#1783]
I try to inference on maskrcnn model which from onnx model zoo. the model link is:

https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/mask-rcnn

The inference code is simple:

```
"""

Try inference on MaskRCNN using onnx

"""
import os
import sys
import numpy as np
from PIL import Image
import math
import onnxruntime as rt


def preprocess(image):
    # Resize
    ratio = 800.0 / min(image.size[0], image.size[1])
    image = image.resize((int(ratio * image.size[0]), int(ratio * image.size[1])), Image.BILINEAR)
    # Convert to BGR
    image = np.array(image)[:, :, [2, 1, 0]].astype('float32')
    # HWC -> CHW
    image = np.transpose(image, [2, 0, 1])
    # Normalize
    mean_vec = np.array([102.9801, 115.9465, 122.7717])
    for i in range(image.shape[0]):
        image[i, :, :] = image[i, :, :] - mean_vec[i]
    # Pad to be divisible of 32
    padded_h = int(math.ceil(image.shape[1] / 32) * 32)
    padded_w = int(math.ceil(image.shape[2] / 32) * 32)
    padded_image = np.zeros((3, padded_h, padded_w), dtype=np.float32)
    padded_image[:, :image.shape[1], :image.shape[2]] = image
    image = padded_image
    return image


img_f = 'images/horses.jpg'
if len(sys.argv) > 1:
    img_f = sys.argv[1]
    print('predicting image: {}'.format(sys.argv[1]))
img = Image.open(img_f)
img_data = preprocess(img)
img_data = np.array(img_data, dtype=np.float32)
print(img_data)

sess = rt.InferenceSession("models/mask_rcnn/mask_rcnn_R_50_FPN_1x.onnx")
print('model input: {}'.format(sess.get_inputs()[0]))
input_name = sess.get_inputs()[0].name
print(input_name)
out = sess.run(None, {input_name: img_data})
print('out: {}'.format(out))

```

The error output:

```
INFO 09-09 16:01:45 demo_onnxrt_maskrcnn.py:48 - image
[1]    29873 floating point exception  python3 demo_onnxrt_maskrcnn.py

```

Why got this exception? Does there any unsupported op inside that model?? But it's able export to onnx means it must have all supported opset of onnx.  Then it should be a bug or something wrong inside onnxruntime???

**Comment by skottmckay** [comment]
Is this any different to #1767? If not please close.

**Comment by jinfagang** [comment]
@skottmckay  I closed another one. I have tested on several different images, some can infer, some can not, I will post some not right image here tomorrow.

**Comment by hariharans29** [comment]
Hi @jinfagang,

1) Please provide more details - Which package are you using (CPU or GPU) ? Which platform - Windows or Linux ? If Linux, which flavor ?

2) If you are using the GPU package, does the image that cause the floating point exception, also cause the same exception in the CPU package as well ? 

3) Just FYI - Mask RCNN has an issue where the model is unable to handle 0 detections - https://github.com/onnx/models/issues/203. There is an issue tracking this - but this seems diferent as the error seems to manifest differently...

Please provide details for (1) and (2) when you upload the sample non working image.

CC: @BowenBao

**Comment by jinfagang** [comment]
![24274813513_0cfd2ce6d0_k](https://user-images.githubusercontent.com/21303438/64578850-44e55e00-d3b3-11e9-9882-d1fe0fac85df.jpg)


this image will cause:

```
[1]    11000 floating point exception  python3 demo_onnxrt_maskrcnn.py images/24274813513_0cfd2ce6d0_k.jpg

```


![33887522274_eebd074106_k](https://user-images.githubusercontent.com/21303438/64578871-5dee0f00-d3b3-11e9-92b2-6ee79dd980f2.jpg)

this image also.

But anyway, doesn't there any objects inside?

**Comment by jinfagang** [comment]
My enviroment is on CPU onnxruntime.

**Comment by hariharans29** [comment]
Thanks @nieyan  for the comment in the dupelicate issue #1767 

@jinfagang - this maybe an environment issue as stated by nieyan.
