### ISSUE TITLE
[Mobile] 

### ISSUE THREAD

**Issue by paldineshdexbytes** [microsoft/onnxruntime#17847]
### Describe the issue

I have implemented ONNX in android native by using 
    implementation 'com.microsoft.onnxruntime:onnxruntime-android:latest.release'
    implementation 'com.microsoft.onnxruntime:onnxruntime-extensions-android:latest.release'
and it working fine in debug mode but app is crashing on release mode.

Getting Error :
     
 JNI DETECTED ERROR IN APPLICATION: java_class == null
 in call to GetMethodID
from ai.onnxruntime.OnnxValue[] ai.onnxruntime.OrtSession.run(long, long, long, java.lang.String[], long[], long, java.lang.String[], long, long)

### To reproduce

I have implemented ONNX in android native by using 
    implementation 'com.microsoft.onnxruntime:onnxruntime-android:latest.release'
    implementation 'com.microsoft.onnxruntime:onnxruntime-extensions-android:latest.release'
and it working fine in debug mode but app is crashing on release mode.

Getting Error :
     
 JNI DETECTED ERROR IN APPLICATION: java_class == null
 in call to GetMethodID
from ai.onnxruntime.OnnxValue[] ai.onnxruntime.OrtSession.run(long, long, long, java.lang.String[], long[], long, java.lang.String[], long, long)

### Urgency

I need to fix it ASAP because i have to publish build on google play store

### Platform

Android

### OS Version

11+

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

onnxruntime-android

### ONNX Runtime Version or Commit ID

latest.release

### ONNX Runtime API

Java/Kotlin

### Architecture

Other / Unknown

### Execution Provider

Default CPU

### Execution Provider Library Version

latest.release

**Comment by Craigacp** [comment]
Those methods are called to lookup method handles for `ai.onnxruntime.TensorInfo` and `ai.onnxruntime.OnnxTensor`. Both of those should be available for lookup, otherwise you wouldn't be able to get into the run method. What changes by turning on release mode in your build?

**Comment by skottmckay** [comment]
Is R8 Minimization enabled?

https://onnxruntime.ai/docs/build/android.html#note-proguard-rules-for-r8-minimization-android-app-builds-to-work

**Comment by paldineshdexbytes** [comment]
> Is R8 Minimization enabled?
> 
> https://onnxruntime.ai/docs/build/android.html#note-proguard-rules-for-r8-minimization-android-app-builds-to-work

Thank you this works for me, now app is not crashing in release mode, but now the app camera works very slowly after applying progard in release mode. Could you please help me with it?

I have reviewed my code and noted this run method taking time to return output 
        try {
            Set<String> set = new HashSet<>();
            // Adding elements to the set
            set.add("det_bboxes"); // 0
            set.add("det_scores");  // 1
            set.add("det_classes");  // 2
            set.add("det_keypoints"); // 4
            set.add("num_dets");  // 3
            outputMap =  ortSession.run(inputMap,set);
        } catch (OrtException e) {
            System.out.println("wowwowwow Android object detection error 2 "+e );
            e.printStackTrace();
        }
![image](https://github.com/microsoft/onnxruntime/assets/97021986/9d3831a8-e255-424e-9ffe-701ab3543961)

**Comment by paldineshdexbytes** [comment]
> Those methods are called to lookup method handles for `ai.onnxruntime.TensorInfo` and `ai.onnxruntime.OnnxTensor`. Both of those should be available for lookup, otherwise you wouldn't be able to get into the run method. What changes by turning on release mode in your build?

Thank you

**Comment by skottmckay** [comment]
The proguard rules change ensures the onnxruntime symbols don't get thrown away. That should have no impact on how fast or slow the camera is so I'm afraid there's not much we can do to help there. 

How long the `run` call takes depends on how complex the model is and how powerful the device is. You could try enabling the NNAPI EP but that could be worse depending on the device (NNAPI is pretty fickle). 
https://onnxruntime.ai/docs/execution-providers/NNAPI-ExecutionProvider

If the model input is 32-bit float data you could also try enabling the XNNPACK EP. 
https://onnxruntime.ai/docs/execution-providers/Xnnpack-ExecutionProvider.html
