### ISSUE TITLE
[Feature Request] Python 3.12 support

### ISSUE THREAD

**Issue by tonybaloney** [microsoft/onnxruntime#17842]
### Describe the feature request

this package cannot be installed using Python 3.12 and is only publishing wheels, so cannot be compiled from source/

### Describe scenario use case

Please publish Python 3.12 wheels

**Comment by tonybaloney** [comment]
Side note, if the maintainers haven't already checked out cibuildwheel, I think this project could use it and remove a lot of the scripts that have been written to accomplish the same thing (building lots of wheels and doing manylinux linking from a CMake project) https://github.com/pypa/cibuildwheel

**Comment by timbodeit** [comment]
> [...] so cannot be compiled from source

Until [ORT 1.17](https://github.com/microsoft/onnxruntime/wiki/Upcoming-Release-Roadmap) is released, you can compile from source by following the [build instructions](https://onnxruntime.ai/docs/build/inferencing.html).

To build for my arm-based Mac, I added a `--build_wheel` argument to the `./build.sh` call, to build python wheels directly.
Afterwards you can find the .whl file under `build/[...]/dist/`.

Commands I used inside my 3.12 conda env on M3 Pro Mac:
```
./build.sh --config Release --build_shared_lib --parallel --enable_pybind --skip_tests --build_wheel  --update --build --cmake_extra_defines CMAKE_OSX_ARCHITECTURES=arm64
pip3 install --upgrade /Users/tim.bodeit/repos/onnxruntime/build/MacOS/Release/dist/onnxruntime-1.17.0-cp312-cp312-macosx_14_0_arm64.whl
```

**Comment by manuelseeger** [comment]
Thanks @timbodeit. Took me a while to get the build environment working under windows and had to build with --skip_tests (like you did) but in the end I could build 1.17 wheels.

**Comment by omasoud** [comment]
I tried to build for windows but it was building only `onnxruntime-1.17.0-cp312-cp312-win32.whl` until I added `call "%VCINSTALLDIR%\Auxiliary\Build\vcvarsall.bat" amd64` just before the python call in `build.bat`. Then it generated `onnxruntime-1.17.0-cp312-cp312-win_amd64.whl`

**Comment by snnn** [comment]
> I tried to build for windows but it was building only `onnxruntime-1.17.0-cp312-cp312-win32.whl` until I added `call "%VCINSTALLDIR%\Auxiliary\Build\vcvarsall.bat" amd64` just before the python call in `build.bat`. Then it generated `onnxruntime-1.17.0-cp312-cp312-win_amd64.whl`

You might have two Pythons in your system. If you run the build with a 32-bit python, you will have a 32-bit wheel. If you run the build with a 64-bit python, you will have a 64-bit wheel.

**Comment by omasoud** [comment]
I only have one 64-bit python in my path (the [Microsoft app](https://www.microsoft.com/store/productId/9NCVDN91XZQP?ocid=pdpshare) one, which states "Architecture: x64")

`vcvarsall.bat amd64` performs a lot of environment setup, some of which probably did the trick. Here's a diff of environment variable changes that occur after running it:
<img width="952" alt="image" src="https://github.com/microsoft/onnxruntime/assets/16273458/eace442d-22be-4cd2-9c6b-700e057db3d2">

**Comment by snnn** [comment]
No. MacOS doesn't support CUDA.

**Comment by ConnorBP** [comment]
> No. MacOS doesn't support CUDA.

I am building for windows

**Comment by snnn** [comment]
ONNX Runtime 1.17.0 is released with this new feature.

**Comment by MonolithFoundation** [comment]
pip install onnxruntime
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime
python
Python 3.12.8 | packaged by conda-forge | (main, Dec  5 2024, 14:24:40) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
