### ISSUE TITLE
How to convert the format when using relative paths

### ISSUE THREAD

**Issue by yulinhuyang** [microsoft/onnxruntime#1785]
windows x86，
How to convert the format when using relative paths? I tried a lot of methods,but is not ok.

![image](https://user-images.githubusercontent.com/13074332/64529077-a6b6b100-d33c-11e9-9c94-6a9aa91e5cc1.png)

**Comment by skottmckay** [comment]
What specifically did you try and what were the errors?

onnx_test_runner is able to handle relative paths so it is possible. 

```
D:\src\github\onnxruntime\build\Windows\Debug\Debug> .\onnx_test_runner.exe test_models\test_size_float\                           
result:                                                                                                                                                                                     Models: 1
        Total test cases: 1
                Succeeded: 1
                Not implemented: 0
                Failed: 0
        Stats by Operator type:
                Not implemented(0):
                Failed:
```

**Comment by faxu** [comment]
@yulinhuyang Do you still need assistance on this issue? If so, please provide more details as requested, thanks!
