### ISSUE TITLE
YOLOv8 using OnnxRuntime CPP with CUDA on Windows giving cudaErrorNoKernelImageForDevice for QuickGelu

### ISSUE THREAD

**Issue by VIGO42** [microsoft/onnxruntime#17861]
### Describe the issue

Hi guys,
I have successfully tested inference with OpenCV DNN but I needed faster approach with OnnxRuntime. It is working on CPU directly from [ultralytics example](https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-ONNXRuntime-CPP). But when switching to USE_CUDA I didn't manage to make it working.

**Configuration**
Windows 10 Pro
Visual Studio 2019 Pro
OpenCV 4.8.0
CUDA 11.8
cuDNN 8.7.0
OnnxRuntime, OnnxRuntime.Gpu nuget 1.16.0
NVIDIA Quadro M620 compute capability 5.0 (notebook)
Model exported in Colab using: model.export(format="onnx", opset=12, simplify=True, dynamic=False, imgsz=640)

**Symptoms**
DCSP_CORE::CreateSession always throws exception in WarmUpSession on line with session->Run
With FP32 configuration it gives:
[E:onnxruntime:, sequential_executor.cc:514 onnxruntime::ExecuteKernel] Non-zero status code returned while running QuickGelu node. Name:'QuickGelu' Status Message: CUDA error cudaErrorNoKernelImageForDevice:no kernel image is available for execution on the device
With FP16 configuration it gives:
[DCSP_ONNX]:Unexpected input data type. Actual: (tensor(float16)) , expected: (tensor(float))

I have tested other versions of cuDNN, OnnxRuntime nugets and export opsets. It didn't help.
I have tested standalone cuDNN example to run simple tensor and it was working.
Could you please suggest what could be wrong in my case? The NVIDIA card I am using is maybe old but it is listed as supported Maxwell architecture.

### To reproduce

Use ultralytics example:
https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-ONNXRuntime-CPP
With exported yolov8s.onnx model

### Urgency

Normal
- because I can still fallback to CPU implementation for testing
- but we would definitelly need GPU acceleration in our application

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.0 (nuget)

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.8,  cuDNN 8.7.0

**Comment by tianleiwu** [comment]
@VIGO42
For 1.16 nuget need GPU with cuda compacity of 6.0 or above. (see commit https://github.com/microsoft/onnxruntime/commit/a9df3aea72e23e1a08098084d22e997df91cb519).

You can try use older version of ORT like 1.15.1 for Maxwell.

**Comment by VIGO42** [comment]
Thank you for your suggestion. I thought that it was probably a problem with my HW. But I was not sure if QuickGelu node is not required by the yolov8 onnx model itself.
Do you have any recommendation for combination of CUDA and cuDNN versions for ORT 1.15.1 since it is not listed in compatability tables I have found?

**Comment by VIGO42** [comment]
@tianleiwu 
I have tested ORT down to version 1.7 (and cuDNN 8.0.2) but the error message remains the same.
I am wondering which part is trying to use QuickGelu kernel - CUDA, cuDNN, ORT or the exported yolov8 onnx model itself?
Meanwhile I managed at least to use DirectML for acceleration but I assume CUDA will be much faster.

**Comment by tianleiwu** [comment]
Since your GPU is NVIDIA Quadro M620 with compute capability **5.0**, you might need ORT 1.14 for CUDA EP. (1.14 supports 3.5 or above 1.15 supports 5.2  or above, 1.16 supports 6.0 or above). Note that even using ORT 1.14, there is still limitation: it cannot run FP16 in your GPU, you have to convert to FP32 model to run in CUDA EP.

The root cause of the error you used float16 in your model, but FP16 need compute capability **5.3** or above. That's the reason you saw the error since there is no FP16 kernel for your GPU.

Even DirectML can run y our model, it probably convert it to FP32 before running the model. That will be slower than running FP32 model directly.

If you would like to try cuda EP, my suggestion is to export FP32 onnx model directly and use ORT 1.14.

**Comment by VIGO42** [comment]
@tianleiwu
I think that my model is FP32 but thank you for your time and help. I need a better HW to play faster with the latest DNN models.
