### ISSUE TITLE
cast to string not implemented in onnxruntime

### ISSUE THREAD

**Issue by prabhat00155** [microsoft/onnxruntime#1791]
**Is your feature request related to a problem? Please describe.**
 Cast(https://github.com/onnx/onnx/blob/master/docs/Operators.md#Cast) op defined in the onnx spec describes conversion of numeric tensors to string tensors, whereas onnxruntime doesn't seem to implement this(See https://github.com/microsoft/onnxruntime/blob/a324ad7b96a831c5ed83e873d9429da05bf887be/onnxruntime/core/providers/cpu/tensor/cast_op.cc#L355).
This is needed to support multiple types of input in Scikit's OneHotEncoder converter.

**System information**
- ONNX Runtime version (you are using): 0.5.0

**Describe the solution you'd like**
Cast to support conversion of numeric tensors to string tensors. For example:
[[1, 2, 3], [3, 4, 5]] -> [['1', '2', '3'], ['3', '4', '5']]

**Describe alternatives you've considered**
Currently, we just support multiple inputs of same type.

**Comment by hariharans29** [comment]
Hi @prabhat00155,

I think that specific error message is mis-leading. If you look closely, that comes under the 'MLFLoat16' section. I think what they meant to write was "Casting to strings from float16 is not supported yet."

Casting to/from strings is supported (atleast looking at the code)- 

https://github.com/microsoft/onnxruntime/blob/75f241d02c4cf6b35b326d72267364948bc4f8af/onnxruntime/core/providers/cpu/tensor/cast_op.cc#L93

https://github.com/microsoft/onnxruntime/blob/75f241d02c4cf6b35b326d72267364948bc4f8af/onnxruntime/core/providers/cpu/tensor/cast_op.cc#L72

Does this help ?

**Comment by prabhat00155** [comment]
Do you mean to say casting from int to string is supported? I was getting error when I tried to do that.

**Comment by hariharans29** [comment]
It does seem to be. (I didn't implement Cast - just answering based on what I see in the code). What is the error you are getting ?

**Comment by prabhat00155** [comment]
I had a loop where I was converting all the inputs to string. The input were of types string and int, and on further debugging I found out that it was string inputs that caused the error, not int.

RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : /Users/vsts/agent/2.155.1/work/1/s/onnxruntime/core/providers/cpu/tensor/cast_op.cc:413 virtual onnxruntime::common::Status onnxruntime::Cast<std::__1::basic_string<char> >::Compute(onnxruntime::OpKernelContext *) const [T = std::__1::basic_string<char>] Unexpected 'to' argument value: 8
Stacktrace:

I think I should put a check for input type and type-cast only int inputs. Thanks for your help.

**Comment by hariharans29** [comment]
No problem. Thanks for pointing out the incorrect error message.
