### ISSUE TITLE
How to calling the ONNX Runtime model in QT (C++) with a GPU 4080

### ISSUE THREAD

**Issue by jts250** [microsoft/onnxruntime#17910]
### Describe the issue

Hello, I am using a GPU 4080 with CUDA 11.8, cuDNN 8.5, and ONNX Runtime 1.15.1. However, when calling the ONNX Runtime model in QT (C++), the system always uses the CPU instead of the GPU. Previously, both a machine with GPU 3080, CUDA 11.3, cuDNN 8.2, ONNX Runtime 1.15.1 and another one with GPU 3070, CUDA 11.1, cuDNN 8.2, ONNX Runtime 1.15.1 could use CUDA for the task. Is there anything worthy of attention or is this issue caused by the version differences?

### To reproduce

Hello, I am using a GPU 4080 with CUDA 11.8, cuDNN 8.5, and ONNX Runtime 1.15.1. However, when calling the ONNX Runtime model in QT (C++), the system always uses the CPU instead of the GPU. Previously, both a machine with GPU 3080, CUDA 11.3, cuDNN 8.2, ONNX Runtime 1.15.1 and another one with GPU 3070, CUDA 11.1, cuDNN 8.2, ONNX Runtime 1.15.1 could use CUDA for the task. Is there anything worthy of attention or is this issue caused by the version differences?

### Urgency

Urgent

### Platform

Windows

### OS Version

windows11 x64

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.8

**Comment by c1aude** [comment]
The Released Package has Architects for the RTX 40 Series, which is expected to be unbuilt.
When you proceed with the build from Source and run build.bat --cmake_extra_defines "CMAKE_CUDA_ARCHITEURES=89"
I think CUDA will be available if you build and use options.

**Comment by jts250** [comment]
Thank you. However, I use QMAKE instead of CMAKE. Do you have any idea about it?
Should I  change cuda version such as 11.3?

**Comment by c1aude** [comment]
RTX 40 Series need CUDA version should be 11.8 or higher
QMAKE is didn't help you because I've never used it before.

**Comment by jts250** [comment]
Thanks, and I have solved the problem with CUDNN8.7 and cuda 11.8!
