### ISSUE TITLE
CUDA10.1 build error

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#1795]
Previously post a issue but now I think it's mainly about CUDA10.1. 

After reading this:

https://gitlab.kitware.com/cmake/cmake/issues/19029

The conclusion is:
On CUDA10.1, onnxruntime will not able to build since it will hit this error when run cmake:

```
-- The CUDA compiler identification is unknown
CMake Error at CMakeLists.txt:579 (enable_language):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!

```

I encourage community have a test on CUDA10.1 to verify it. the root reason for this may be somewhat 32 bit compiling and 64 bit compling confict inside onnxruntime cmake test. Better onnxruntime maintainers have a tiny investigate on this issue. I am not able to build onnxruntime with CUDA10.1 and successfully with CUDA10.

**Comment by snnn** [comment]
What's your OS? Is it Windows or Linux?

**Comment by jinfagang** [comment]
Ubuntu 16.04

**Comment by snnn** [comment]
How could I reproduce your error?

**Comment by jinfagang** [comment]
@snnn Thanks for interesting on this issue. 

I just pulled the newest code from master branch. and rerun:

```
 ./build.sh \ 
        --use_cuda \
        --cuda_version=10.1 \
        --cuda_home=/usr/local/cuda-10.1 \
        --cudnn_home=/usr/local/cuda-10.1 \
        --use_tensorrt --tensorrt_home=$HOME/tensorrt5.1.5 \
        --build_shared_lib --enable_pybind --build_wheel

```

it start to build now............................... I didn't do anything just pull and remove the `sudo` as I previously did.


Now that this is no longer an issue will close this.
