### ISSUE TITLE
[Build]  Vitis-AI build failed due to flatbuffers/flatbuffers.h missing 

### ISSUE THREAD

**Issue by gatoruu** [microsoft/onnxruntime#17969]
### Describe the issue

when building vitis-ai ep, it has errors complaining fatal error: flatbuffers/flatbuffers.h: No such file or directory 
like below:

In file included from/tmp/onnxruntime/onnxruntime/core/providers/vitisai/imp/global_api.cc:11:
/tmp/onnxruntime/onnxruntime/core/graph/model.h:11:10: fatal error: flatbuffers/flatbuffers.h: No such file or directory

In file included from /tmp/onnxruntime/onnxruntime/core/providers/vitisai/include/vaip/graph.h:4,
                 from /tmp/onnxruntime/onnxruntime/core/providers/vitisai/imp/graph.cc:3:
/tmp/onnxruntime/include/onnxruntime/core/graph/graph.h:23:10: fatal error: flatbuffers/flatbuffers.h: No such file or directory
   23 | #include "flatbuffers/flatbuffers.h"

vitis ai ep use core/graph/model.h and core/graph/graph.h  which  include flatbuffers/flatbuffers.h.  However flatbuffer.h is missing in the repo. 

### Target platform

Linux and Windows

### Build script

./build.sh --use_vitisai --build_shared_lib --parallel --config Release  

### Error / output

In file included from/tmp/onnxruntime/onnxruntime/core/providers/vitisai/imp/global_api.cc:11:
/tmp/onnxruntime/onnxruntime/core/graph/model.h:11:10: fatal error: flatbuffers/flatbuffers.h: No such file or directory

In file included from /tmp/onnxruntime/onnxruntime/core/providers/vitisai/include/vaip/graph.h:4,
                 from /tmp/onnxruntime/onnxruntime/core/providers/vitisai/imp/graph.cc:3:
/tmp/onnxruntime/include/onnxruntime/core/graph/graph.h:23:10: fatal error: flatbuffers/flatbuffers.h: No such file or directory
   23 | #include "flatbuffers/flatbuffers.h"

**Comment by tianleiwu** [comment]
pip install flatbuffers?

It is listed in requirements: https://github.com/microsoft/onnxruntime/blob/83547d30672ca1fa11327420037a1be2a6448950/requirements-dev.txt#L3

**Comment by jywu-msft** [comment]
i think it's missing flatbuffers::flatbuffers in https://github.com/microsoft/onnxruntime/blob/35ecce45496ee752bc3f85618eba713bb50e6069/cmake/onnxruntime_providers_vitisai.cmake#L21

reference cuda ep as example
https://github.com/microsoft/onnxruntime/blob/35ecce45496ee752bc3f85618eba713bb50e6069/cmake/onnxruntime_providers_cuda.cmake#L140

can you try making the change and rebuild to see if it works?
