### ISSUE TITLE
Core dump issue

### ISSUE THREAD

**Issue by agapebondservant** [microsoft/onnxruntime#17976]
### Describe the issue

Getting a core dump error while attempting to perform inference with the attached model on MacOs with Java API (works with Python API)

### To reproduce

Run the following code:

        ```
        OrtEnvironment env = OrtEnvironment.getEnvironment();

        Map<String, OnnxTensor> container = new HashMap<>();

        String modelPath = getResourcePath("./my_model").toString();

        double[][] inferenceData = {{7, 200.57, -39.5, 100.3}}; 

        OnnxTensor inferenceTensor = OnnxTensor.createTensor(env, inferenceData);

        OrtSession.SessionOptions options = new SessionOptions();

        options.setIntraOpNumThreads( 8 );

        try (OrtSession session = env.createSession(modelPath, options)) {

            NodeInfo inputMetaData = session.getInputInfo().values().iterator().next();

            container.put(inputMetaData.getName(), inferenceTensor);

            Map<String, NodeInfo> outputInfo = session.getOutputInfo();

            for (Map.Entry<String, NodeInfo> entry : outputInfo.entrySet()){

                try {

                    OrtSession.Result results = session.run(container);
                } catch (Exception ex) {
                     ex.printStackTrace();
                }
           }
      } finally {
              inferenceTensor.close();
      }
```

Onnx model file:
https://file.io/xTwgKdZzjOk8

### Urgency

Urgent blocker (required for a paid prototype
0

### Platform

Mac

### OS Version

13.5.2

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by yuslepukhin** [comment]
Cc: @Craigacp

**Comment by Craigacp** [comment]
Could you attach the hotspot log file and specify the Java version you're using? The file link didn't contain a model so I'm not quite sure what's going on.

**Comment by agapebondservant** [comment]
Log file: 
[hs_err_pid41519.log](https://github.com/microsoft/onnxruntime/files/12924930/hs_err_pid41519.log)
JDK version: 
OpenJDK 13.0.2+8_2

**Comment by Craigacp** [comment]
Well the for loop around the outputInfo isn't necessary, it'll return all outputs the way you're calling it, so you can call it the same way you call the Python one. Can you recompile it with debug flags? The hotspot trace says it's dying in the C++ Run call, after JNI called into the library and it really should be throwing an exception from there rather than crashing.

**Comment by Craigacp** [comment]
Ok. I'm a little worried that that caused it to dump core, I'd strongly prefer it not to be possible to make the JVM crash when using ORT, so I'll try to run that down a little further.

As to compiling it with debug symbols, if you can build ORT then this should do it (on Linux/macOS) - `./build.sh --update --config Debug --build --build_java --parallel`.
