### ISSUE TITLE
[Training] More Documentation on HOW to do ONNXRuntime training using c# [CSharp] 

### ISSUE THREAD

**Issue by GeorgeS2019** [microsoft/onnxruntime#17984]
### Describe the issue

Please [add **Csharp topic** and see the impact to c# users](https://github.com/microsoft/onnxruntime/issues/17584#issuecomment-1760270672)

# Summary
I would like to take an Onnx model exported to e.g. HuggingPlace and do further training on it using OnnxRuntime using C# for all the workflow without needing PyTorch.

============================
With the new release, there are more information on 
- OnDevice training
- Large Model training

Since these topics are listed as separates from e.g. C#
I wonder **where** I could learn more on using c# to do training using ONNXRuntime.

![image](https://github.com/microsoft/onnxruntime/assets/49812372/236335e5-7af0-4061-a029-bebd0c3d78aa)

### To reproduce

Onnxruntime using c# lacks information on training

See the picture above and information listed under the c#

### Urgency

We are currently working out a workflow where we would like to do deep reinforcement training and save the model for inference ALL in C# in Godot 3D engine environment. 

We could do inference using ONNXRUntime.

However, we would really like to START doing real time training using the ONNXRuntime framework within Godot 3D engine (.NET6 csharp)

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.0

### PyTorch Version

Compatible

### Execution Provider

CUDA

**Comment by GeorgeS2019** [comment]
Please add Csharp topic


Possible example doing [OnDevice training](https://github.com/microsoft/onnxruntime-training-examples/blob/master/on_device_training/desktop/csharp/image_classification/mobilevit_console/mobilevit_console/Program.cs) using c#


Even the latest Bing's ChatGPT4 fails to answer this simple question if it is possible to do ONNXRuntime training using c# 

Perhaps we need a restructuring of the documentation structure => to not just assisting c# users but also ChatGPT4

**Comment by GeorgeS2019** [comment]
# [ONNX Runtime Training Examples](https://github.com/microsoft/onnxruntime-training-examples/tree/master#onnx-runtime-training-examples)

It seems there is possibly ONE example.

This does not help me to see the overview what is the decision to support Onnxruntime training using c#

**Comment by GeorgeS2019** [comment]
By searching using https://github.com/microsoft/onnxruntime/issues?q=label%3Aapi%3ACSharp, found relevant issues
- https://github.com/microsoft/onnxruntime/issues/17584

**Comment by GeorgeS2019** [comment]
@baijumeswani 
@peratrepic 

Before I go further, kindly summarize if Onnxruntime training using csharp is working at all??

When will this be fixed?

We definitely need documentation on this issue!

**Comment by GeorgeS2019** [comment]
I wonder if this is possible or relevant to csharp users?
https://github.com/microsoft/onnxruntime/wiki/Model-Training-Domain-Knowledge

**Comment by baijumeswani** [comment]
@GeorgeS2019 please look at the API docs https://onnxruntime.ai/docs/api/csharp/api/Microsoft.ML.OnnxRuntime.TrainingSession.html

The overview can be found here: https://onnxruntime.ai/docs/get-started/training-on-device.html

Let me know if there are more questions.

**Comment by GeorgeS2019** [comment]
@baijumeswani 

Thanks! I will create more separate issues that I hope will cover the different implications of having this training now feasible using c#

Please kindly support me by labelling them to 
![image](https://github.com/microsoft/onnxruntime/assets/49812372/f97deeaf-0f8b-4c12-b8c3-121a62210d50)

**Comment by baijumeswani** [comment]
Marking as complete and closing the issue. Please reopen in case needed.
