### ISSUE TITLE
n issue with running model on CUDA.

### ISSUE THREAD

**Issue by ahmasoum** [microsoft/onnxruntime#17985]
### Describe the issue

hello, I have an issue with running my model on CUDA. it returns this error:
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running FusedConv node. Name:'/encoder/encoder/encoder.1/res.0.0/conv/Conv' Status Message: CUDNN failure 3: CUDNN_STATUS_BAD_PARAM ; GPU=0 ; hostname=b79d2eef8c40 ; file=/code/onnxruntime/contrib_ops/cuda/fused_conv.cc ; line=85 ; expr=cudnnAddTensor(cudnnHandle, &alpha, Base::s_.z_tensor, Base::s_.z_data, &alpha, Base::s_.y_tensor, Base::s_.y_data); ```
but when I run it on the CPU version, there is no issue. what should I do?

### To reproduce

.

### Urgency

_No response_

### Platform

Linux

### OS Version

22.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.16.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 12.1

**Comment by tianleiwu** [comment]
@ahmasoum, It might be caused by graph fusion for FusedConv. Could you try disable graph optimization using session options to see whether it is good.

You can also share the onnx graph (If you do not want to share weights, you can save onnx model with exernal data format and share us the .onnx file but not the weights) to reproduce the issue.

**Comment by ahmasoum** [comment]
> @ahmasoum, It might be caused by graph fusion for FusedConv. Could you try disable graph optimization using session options to see whether it is good.
> 
> You can also share the onnx graph (If you do not want to share weights, you can save onnx model with exernal data format and share us the .onnx file but not the weights) to reproduce the issue.

@tianleiwu , thank you very much. that was correct.

**Comment by ahmasoum** [comment]
@tianleiwu, 
I have a problem with speed, at first step of inference, the speed is very slow, but after some iterations, it works faster. i use this config:     model_path = cfg.backend.cosine_similarity.model_path
    batch_size = cfg.backend.cosine_similarity.batch_size
    options = SessionOptions()
    options.enable_mem_pattern = True
    options.enable_cpu_mem_arena = True
    options.intra_op_num_threads = 16
    options.execution_mode = ort.ExecutionMode.ORT_SEQUENTIAL
    options.execution_mode = ort.ExecutionMode.ORT_PARALLEL
    #options.execution_mode = ort.ExecutionMode.ORT_PARALLEL_DP
    options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_BASIC #ORT_DISABLE_ALL
    sess = InferenceSession(model_path,
      providers = [
    ('CUDAExecutionProvider')],
      sess_options=options)
    input0_name = sess.get_inputs()[0].name
    input1_name = sess.get_inputs()[1].name
    emb1_name = sess.get_outputs()[0].name
    emb2_name = sess.get_outputs()[1].name. 
is there any way to speedup?

**Comment by hariharans29** [comment]
@ahmasoum - Can you share a minimal repro model for the FusedConv issue while trying to use CUDA ?
