### ISSUE TITLE
C# ONNX batch prediction only returns a single prediction

### ISSUE THREAD

**Issue by nicnhus22** [microsoft/onnxruntime#1798]
**Bug description**
Batch prediction only returns a single prediction.

**System information**
- OS Platform and Distribution: MacOS Mojave 10.14.6
- ONNX Runtime installed from latest [release](https://github.com/microsoft/onnxruntime/releases)
- ONNX Runtime version: Microsoft.ML.OnnxRuntime (0.5.0
- Visual Studio version: 8.2.5 (build 5)

**To Reproduce**
```csharp
float width = 1.0;
float height = 2.0;

float[] sourceData = { width, height };
int[] dimensions = { 1, 2 };

Tensor<float> t1 = new DenseTensor<float>(sourceData, dimensions);
var inputs = new List<NamedOnnxValue>(){
    NamedOnnxValue.CreateFromTensor<float>("float_input", t1),
    NamedOnnxValue.CreateFromTensor<float>("float_input", t1),
    NamedOnnxValue.CreateFromTensor<float>("float_input", t1)
};

using (InferenceSession session = new InferenceSession(modelPath)) {
    using (var results = session.Run(inputs)) {
        // results only contain 1 prediction
        foreach (var r in results) {
            if(r.Name == "label") {
                log.LogInformation($"{r.AsTensor<Int64>().GetValue(0)}");
            }
        }
    }
}
```
**Expected behavior**
Expected `results` to contain 3 predictions. I went into the debugger to make sure I was parsing right : 
<img width="1094" alt="Screenshot 2019-09-10 at 22 56 46" src="https://user-images.githubusercontent.com/3611896/64650013-6b8cae80-d41e-11e9-8099-6aa0e7418d0b.png">

**Additional context**
The kmeans model I am doing predictions for was trained with `scikit-learn` then exported to ONNX. Querying the same model with python's `onnxruntime` library behaves as expected.

**Comment by jignparm** [comment]
The Run() method only scores 1 example at a time. The inputs variable in the your code above should contain a list of inputs that the model expects for that 1 example being scored, not a list of examples to construct a batch.

The notion of batch size (if a model can handle batches) is captured by the tensor shapes  For example, if the shape of a tensor is [N, C, H, W], N is the number of images (batch size), C is number of channels, H is height of the image, W is the width of the model.
