### ISSUE TITLE
[Build] build with cmake (makefile or ninja generator) spawns zillons of cuda process filling 128Gb ram and gets OOM killer

### ISSUE THREAD

**Issue by sl1pkn07** [microsoft/onnxruntime#17993]
### Describe the issue

build onxxruntime in dual xeon E5-2687W-V4 and 128Gb ram gets OOM killer all the system

### Target platform

linux

### Build script

cmake -S onnxruntime/cmake -B build \
    -DCMAKE_BUILD_TYPE=Debug
    -DCMAKE_INSTALL_PREFIX=/usr
    -DCMAKE_SKIP_INSTALL_RPATH=OFF
    -DCMAKE_SKIP_RPATH=OFF
    -Donnxruntime_ENABLE_PYTHON=ON
    -Donnxruntime_BUILD_SHARED_LIB=ON
    -Donnxruntime_BUILD_UNIT_TESTS=OFF
    -Donnxruntime_ENABLE_TRAINING=ON
    -Donnxruntime_ENABLE_LAZY_TENSOR=OFF
    -Donnxruntime_USE_MPI=ON
    -Donnxruntime_USE_DNNL=ON
    -Donnxruntime_USE_PREINSTALLED_EIGEN=ON
    -Deigen_SOURCE_PATH="$(pkg-config --cflags eigen3 | sed 's|-I||g')"
    -DCMAKE_CXX_STANDARD=17
    -DCMAKE_IGNORE_PATH=/usr/lib/cmake/flatbuffers/\;/lib/cmake/flatbuffers/\;/usr/lib/cmake/protobuf/\;/lib/cmake/protobuf/
    -DBUILD_TESTING=OFF
      -DCMAKE_CUDA_ARCHITECTURES="52-real;53-real;60-real;61-real;62-real;70-real;72-real;75-real;80-real;86-real;87-real;89-real;90-real;90-virtual"
      -DCMAKE_CUDA_STANDARD_REQUIRED=ON
      -DCMAKE_CXX_STANDARD_REQUIRED=ON
      -Donnxruntime_USE_CUDA=ON
      -Donnxruntime_CUDA_HOME=/opt/cuda
      -Donnxruntime_CUDNN_HOME=/usr
      -Donnxruntime_USE_NCCL=ON

same if add -GNinja

### Error / output

![image](https://github.com/microsoft/onnxruntime/assets/462213/bb4e228d-b654-49c2-929e-2cc5481d8f17)

need stop and do the build in batches and reduced the threading to only one -j1. some time OMMK, some time build sucess

this start from release 1.16.x branch. with older version only can do a sucess build with -j18, leadeing free only 5Gb ram

### GCC / Compiler Version

gcc 12.3.0

**Comment by sl1pkn07** [comment]
just found settings -j8 (for example rigth now, spawn 8 nvcc process with 13 sh -c foo subproces each ncvv process

so, set -j not limit the number of the subprocess released by nvcc


setting -Donnxruntime_NVCC_THREADS= do nothing

**Comment by snnn** [comment]
Yeah.. I guess it was because #17748 came in in that release. How about setting onnxruntime_NVCC_THREADS to 1? You said you undefined it.

**Comment by tianleiwu** [comment]
Or you can cherry-pick this https://github.com/microsoft/onnxruntime/commit/74a8acf4057902f15b574046b2c6b0e3a0b11e49.

**Comment by sl1pkn07** [comment]
> You said you undefined it.

i missundertanding what parameter i need fill in  -Donnxruntime_NVCC_THREADS= (i fill with the desired cpu threads, not leave undefined), because i belive is the limit number of nvcc total process (one eacth thread cpu), not the number of the subprocess created by nvcc (24 subprocess for each nvcc command)

setting to 1 do the trick. is slower, but is a good safe. now keep the ram +/- 30Gb

@tianleiwu tnx

greetings. closed
