### ISSUE TITLE
Track Memory Consumption

### ISSUE THREAD

**Issue by RandyGaul** [microsoft/onnxruntime#1800]
What is the easiest way to track all heap memory consumption from ORT via the C API?

I had the idea to create my own allocator that simply feeds calls straight into the default allocator (created with `OrtCreateDefaultAllocator`).

However, there is no `void* userdata` on the allocator functions. See here:

```cpp
typedef struct OrtAllocator {
  uint32_t version;  // Initialize to ORT_API_VERSION
  void*(ORT_API_CALL* Alloc)(struct OrtAllocator* this_, size_t size);
  void(ORT_API_CALL* Free)(struct OrtAllocator* this_, void* p);
  const struct OrtAllocatorInfo*(ORT_API_CALL* Info)(const struct OrtAllocator* this_);
} OrtAllocator;
```

How is one supposed to create a default allocator if the `Alloc` and `Free` functions do not even have a proper userdata parameter?

For now I've had to typecast `this_` to my own internal type, which is quite awkward and leads to me ask this question.

Additionally, the free function does not have the size of the allocation. So knowing the size of free'd memory is non-trivial. If we look at the implementation of the default alloc, we can see it's aligning to some run-time value as decided by MLAS.

```cpp
void* DefaultAlloc(size_t size) {
  if (size <= 0) return nullptr;
  void* p;
  size_t alignment = MlasGetPreferredBufferAlignment();
#if _MSC_VER
  p = _aligned_malloc(size, alignment);
  if (p == nullptr) throw std::bad_alloc();
#elif defined(_LIBCPP_SGX_CONFIG)
  p = memalign(alignment, size);
  if (p == nullptr) throw std::bad_alloc();
#else
  int ret = posix_memalign(&p, alignment, size);
  if (ret != 0) throw std::bad_alloc();
#endif
  return p;
}
```

Usually alloc functions have alignment passed to them as a parameter. This way higher level allocators can call into lower level allocators with extra padding information (to store bookkeeping, like the allocation size).

It seems to me not possible to track memory consumption due to way the `OrtAllocator` API is designed.

**Comment by AndreyOrb** [comment]
I'm not sure if this is still relevant, but you can use custom allocator:
https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/test/util/include/test_allocator.h
https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/test/util/test_allocator.cc

Example of how to use it:
https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/test/shared_lib/test_inference.cc#L323
