### ISSUE TITLE
[Training] We need ContribOperatorsSamples in the c# csharp folder

### ISSUE THREAD

**Issue by GeorgeS2019** [microsoft/onnxruntime#18001]
### Describe the issue

Currently we only have InferenceSamples folder in the csharp folder. See the picture below

A [feedback ](https://github.com/microsoft/onnxruntime/issues/17999)to have TrainingSamples has been written

Currently, it is anticipated that, I could be wrong, not all ONNX available e.g. from HuggingFace could easily be downloaded and be used for further c# Onnx API training due to the fact that it is unclear if the needed [ContribOperators](https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md) needed to run the downloaded ONNX are available to c# users.

### To reproduce

![image](https://github.com/microsoft/onnxruntime/assets/49812372/42e27048-9d8d-4346-975e-0f7406ccca7c)

### Urgency

Having csharp support for onnx training is disruptive and more users need to test and give feedback to address the potential lack of coverage that is available in e.g. pytorch approach to training.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.0

### PyTorch Version

Compatible

### Execution Provider

CUDA

**Comment by GeorgeS2019** [comment]
@baijumeswani 

Please kindly support me by labelling them to 
![image](https://github.com/microsoft/onnxruntime/assets/49812372/f97deeaf-0f8b-4c12-b8c3-121a62210d50)

**Comment by askhade** [comment]
@GeorgeS2019 : Have you checked onnxruntime-training-examples repo?  https://github.com/microsoft/onnxruntime-training-examples/tree/master/on_device_training/desktop/csharp 

Is my understanding right that you want to try an E2E example of training using c# bindings?

Please note: the onnxruntime training apis are meant for on-device training. They are not meant for large model training. For large model training we have ORTModule which is an accelerates training for PyTorch models.

**Comment by GeorgeS2019** [comment]
@askhade 

What options and how many steps changes need to be made to make Large Model Training available to c#?
