### ISSUE TITLE
[Build]try to build docker image, failed at 81% and the whole system crashed thrice. Have to push the power button every time to force restart

### ISSUE THREAD

**Issue by yongjer** [microsoft/onnxruntime#18010]
### Describe the issue

![20231018_101027](https://github.com/microsoft/onnxruntime/assets/54315206/be22ebe4-779e-4a21-8c6e-afac855dcc3b)

### Target platform

host: ubuntu20.04.6 cuda:12.2 driver version:535.104.12

### Build script

official tensorrt dockerfile at 
https://github.com/microsoft/onnxruntime/blob/main/dockerfiles/Dockerfile.tensorrt

### Error / output

 [81] Building CUDA object CMakeFiles/onnxruntime providers cuda.dir/
 code/onnruntime/onnxruntime/contrib_ops/cuda/bert/flash_attention/fla
 sh_fwd_split_hdim224_fp16_sm80. cu. o

### Visual Studio Version

vscode: 1.83.1

### GCC / Compiler Version

gcc: Ubuntu 9.4.0-1ubuntu1~20.04.2

**Comment by snnn** [comment]
It might have run out of memory. Please try to get a more powerful machine. Like, a machine with 64GB memory. Also, you may add "--nvcc_threads=1" to args of build.sh in https://github.com/microsoft/onnxruntime/blob/main/dockerfiles/Dockerfile.tensorrt, it might help.
