### ISSUE TITLE
[Build] Unable to specify msvc_toolset during Windows build

### ISSUE THREAD

**Issue by toothache** [microsoft/onnxruntime#18014]
### Describe the issue

I have installed VS2022 with both v143 (14.37) and v142 (14.29). However, CMake config will fail when passing `--msvc_toolset` to specify v142 toolset.

### Target platform

Windows

### Build script

.\build.bat --msvc_toolset 14.29

### Error / output

....
-- Detecting C compiler ABI info
CMake Error at D:/source/cognition/onnxruntime/build/Windows/Debug/CMakeFiles/CMakeScratch/TryCompile-farpjc/CMakeLists.txt:4 (project):
  Generator

    Visual Studio 17 2022

  given toolset and version specification

    v143,version=14.29

  contains an invalid version specification.

### Visual Studio Version

2022

**Comment by tianleiwu** [comment]
In my machine, I have to use `.\build.bat --msvc_toolset v143`. It seems that `--msvc_toolset 14.37` does not work.

**Comment by skottmckay** [comment]
I tried with `--msvc_toolset 14.37` which is a version I have installed and it worked fine with cmake 3.26.4.
Also tested with a `--msvc_toolset 14.33` which I do not have installed and got the expected error about it not being installed. It had no issue with the version specification.

```
  given toolset and version specification

    v143,version=14.33

  does not seem to be installed at

    C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/14.33/Microsoft.VCToolsVersion.14.33.props
```

Alternatively you should be able to set the toolset in the environment using the vcvars_ver parameter of vcvarsall.bat prior to running build.bat. 

```
"%VCINSTALLDIR%\Auxiliary\Build\vcvarsall.bat"
[ERROR:vcvarsall.bat] Error in script usage. The correct usage is:
Syntax:
    vcvarsall.bat [arch] [platform_type] [winsdk_version] [-vcvars_ver=vc_version] [-vcvars_spectre_libs=spectre_mode]
where :
    [arch]: x86 | amd64 | x86_amd64 | x86_arm | x86_arm64 | amd64_x86 | amd64_arm | amd64_arm64
    [platform_type]: {empty} | store | uwp
    [winsdk_version] : full Windows 10 SDK number (e.g. 10.0.10240.0) or "8.1" to use the Windows 8.1 SDK.
    [vc_version] : {none} for latest installed VC++ compiler toolset |
                   "14.0" for VC++ 2015 Compiler Toolset |
                   "14.xx" for the latest 14.xx.yyyyy toolset installed (e.g. "14.11") |
                   "14.xx.yyyyy" for a specific full version number (e.g. "14.11.25503")
    [spectre_mode] : {none} for libraries without spectre mitigations |
                     "spectre" for libraries with spectre mitigations
```

e.g. 
https://github.com/microsoft/onnxruntime/blob/0d9030e79888d1d5828730b254fedc53c7b640c1/build.amd64.1411.bat#L8C1-L9C76

**Comment by toothache** [comment]
Both 14.37 and 14.33 belong to v143. The error happens if you specify a toolset version, e.g., 14.29, which does not belong to v143. 

![image](https://github.com/microsoft/onnxruntime/assets/2187096/461dcd91-907c-487b-94ec-3e2af036068e)

**Comment by snnn** [comment]
Now I know, it is a compatibility issue between cmake and VS. 

See #20993
