### ISSUE TITLE
Is TensorRT EP not included in rel-0.4.0?

### ISSUE THREAD

**Issue by GuanLuo** [microsoft/onnxruntime#1803]
I tried to build ONNX Runtime C library with TensorRT Execution provider from source, it built and I compiled my simple example successfully, but it failed to execute with the following error:
```
./ort_c_api: relocation error: ./ort_c_api: symbol OrtSessionOptionsAppendExecutionProvider_Tensorrt version VERS_0.4.0 not defined in file libonnxruntime.so.0.4.0 with link time reference
```

I build the library using the following script (modified from [Dockerfile.tensorrt](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.tensorrt)). Note that I actually use a specific commit that is between rel-0.4.0 and rel-0.5.0, and everything is fine if I build on latest master by uncommenting `git reset` (i.e. my example code can run without the above error). But unfortunately I couldn't use latest master in my project as #1592 is still ongoing. I wonder if I am doing something wrong as the release note said TensorRT EP is in rel-0.4.0

```Dockerfile
FROM nvcr.io/nvidia/tensorrt:19.08-py3
MAINTAINER Vinitra Swamy "viswamy@microsoft.com"

ARG ONNXRUNTIME_REPO=https://github.com/Microsoft/onnxruntime
ARG ONNXRUNTIME_SERVER_BRANCH=master

RUN apt-get update &&\
    apt-get install -y sudo git bash

WORKDIR /code
ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:/code/cmake-3.14.3-Linux-x86_64/bin:/opt/miniconda/bin:${PATH}

# Prepare onnxruntime repository & build onnxruntime with TensorRT
RUN git clone --recursive ${ONNXRUNTIME_REPO} onnxruntime &&\
    cp onnxruntime/dockerfiles/scripts/install_common_deps.sh /code/. &&\
    cp onnxruntime/dockerfiles/LICENSE-IMAGE.txt /code/LICENSE-IMAGE.txt &&\
    cp onnxruntime/ThirdPartyNotices.txt /code/ThirdPartyNotices.txt

# reset hard seems dumb, but checkout fails as some files shown "modified"
# due to CRLF line endings
RUN /bin/sh /code/install_common_deps.sh
ARG COMMON_BUILD_ARGS="--parallel --build_shared_lib --use_openmp"
RUN cd onnxruntime &&\
    git reset --hard 2f698bd54b713bb87dbd0bbb913e94bcf7fd480c && \
    git submodule update --init --recursive && \
    /bin/sh ./build.sh --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ --use_tensorrt --tensorrt_home /workspace/tensorrt --config Release $COMMON_BUILD_ARGS --build_wheel --update --build --cmake_extra_defines ONNXRUNTIME_VERSION=$(cat ./VERSION_NUMBER) &&\
    pip install /code/onnxruntime/build/Linux/Release/dist/*.whl

```

**Comment by jywu-msft** [comment]
@GuanLuo 
sounds like we may be able to close issue, now that https://github.com/microsoft/onnxruntime/issues/1592 is fixed?

**Comment by GuanLuo** [comment]
I don't mind closing this issue as now I can use a later version after #1592 is fixed. But just to point out that the release note says TRT EP is supported in rel-0.4.0 while it seems not to be the case.

**Comment by jywu-msft** [comment]
> I don't mind closing this issue as now I can use a later version after #1592 is fixed. But just to point out that the release note says TRT EP is supported in rel-0.4.0 while it seems not to be the case.

It should be supported. The code does exist in the 0.4.0 release. I wonder if it's an issue specific to C api. We can take a closer look.

**Comment by jywu-msft** [comment]
closing issue.
