### ISSUE TITLE
RuntimeError: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from output/gr/logo/logo.onnx failed:Type Error: Type 'tensor(bool)' of input parameter (253) of operator (Gather) in node () is invalid.

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#1807]
**Describe the bug**

Cannot export this:

```python
idx = a > 0.5
w[idx] = b[idx]
```

In 0.4 I get

> RuntimeError: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from output/gr/logo/logo.onnx failed:Type Error: Type 'tensor(bool)' of input parameter (253) of operator (Gather) in node () is invalid.

In 0.5 I get

> RuntimeError: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from output/gr/logo/logo.onnx failed:This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (253) of operator (Gather) in node () is invalid.

**Urgency**
Need this to export models

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 0.4
- Python version: 3.5.2

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**
Export tensor ops, please better error messages!

**Comment by dashesy** [comment]
Even this seems to be an issue

```python
idx = a > 0.5
c = b[idx]
```

**Comment by hariharans29** [comment]
Hi @dashey,

Attaching the ONNX odel will help, but this seems like an invalid ONNX model to me. As the error message says, it seems to have bound bool type to indices input which deviates from spec - https://github.com/onnx/onnx/blob/master/docs/Operators.md#Gather. Hence, this is an invalid model/graph (present in the error status). The model seems to be missing node names and hence the name section in the error message is empty - `in node () is invalid`.

If you upload the model, I ll help you find the specific problematic node and then you can use the info to open a bug against the base framework/converter you are using to obtain the model. As such this doesn't seem to be an ORT issue.

Thanks!

**Comment by hariharans29** [comment]
Can you try making indices int32 or int64 type ? Only that is supported per ONNX spec. 

I am happy to take a look at the model to make sure it really is a model issue, but unfortunately exporting it to an ONNX complaint format is not something I can help with. You need to get this help from the base project/ converter...

**Comment by dashesy** [comment]
I can use `torch.where` to convert to absolute indices. But lack of support for masked selection (and boolean indices) seems like a big deficiency

**Comment by hariharans29** [comment]
Spoke offline with @dashesy and pointed out the exact issue in the model he shared offline. Since this is not an ORT issue (the ONNX model was invalid per spec), closing this issue.

**Comment by dashesy** [comment]
Added issues [here](https://github.com/pytorch/pytorch/issues/26034) and [here](https://github.com/onnx/onnx/issues/2302). Also added [this issue](https://github.com/pytorch/pytorch/issues/26035) to attach a random name in the exporter for better debugging

**Comment by wangguojun2018** [comment]
> I can use `torch.where` to convert to absolute indices. But lack of support for masked selection (and boolean indices) seems like a big deficiency

when I use 'torch.where', the following errors are  shown.
TypeError: where() missing 2 required positional arguments: 'self' and 'other' (occurred when trans lating where)
my code is 
```
        x=self.linear(inputs)
        x = self.norm(x.permute(0, 2, 1).contiguous()).permute(0, 2,
                                                               1).contiguous()
        x = F.relu(x)

        x_max = torch.max(x, dim=1, keepdim=True)[0]

        x_repeat = x_max.repeat(1, inputs.shape[1], 1)
        x_concatenated = torch.cat([x, x_repeat], dim=2)
        # idx=torch.where(x_concatenated>5)[0]
        idx=torch.nonzero(x_concatenated>5,as_tuple=True)[0]
        x_concatenated=x_concatenated[idx]
        return x_concatenated
```

**Comment by wangguojun2018** [comment]
__

> I can use `torch.where` to convert to absolute indices. But lack of support for masked selection (and boolean indices) seems like a big deficiency

when I use 'torch.where', the following errors are shown.
TypeError: where() missing 2 required positional arguments: 'self' and 'other' (occurred when trans lating where)
my code is
```
        x=self.linear(inputs)
        x = self.norm(x.permute(0, 2, 1).contiguous()).permute(0, 2,
                                                               1).contiguous()
        x = F.relu(x)

        x_max = torch.max(x, dim=1, keepdim=True)[0]

        x_repeat = x_max.repeat(1, inputs.shape[1], 1)
        x_concatenated = torch.cat([x, x_repeat], dim=2)
        idx=torch.where(x_concatenated>5)[0]
        #idx=torch.nonzero(x_concatenated>5,as_tuple=True)[0]
        x_concatenated=x_concatenated[idx]
        return x_concatenated
```

**Comment by dashesy** [comment]
@wangguojun2018 `torch.where` semantics is different from `np.where`, you have to specify 2 more tensors for True and False elements. Please refer to the `torch.where` docs
