### ISSUE TITLE
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Node:  Status Message: 'axes' has an out of range axis

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#1810]
**Describe the bug**
After adding random names to exported model and checking the node the issue is with exported `unsqueeze` with axes of -1. The node is not added in my code

**Urgency**
Workaround is to use non-negative axis number

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 0.4
- Python version: 3.5

**To Reproduce**

```python
torch.stack((bbs0, bbs1, bbs2, bbs3), dim=-1)
```

**Expected behavior**
Run unsqueeze  with axis -1

**Additional context**
Sent the model

**Comment by dashesy** [comment]
`torch.stack` was adding the unsqueeze, changed to `dim=4` as workaround but -1 is valid axis

**Comment by hariharans29** [comment]
that is true. will fix, thanks for the info.

**Comment by hariharans29** [comment]
Hi @dashey,

Actually ONNX opset-10 Unsqueeze doesn't support negative axes. 
Please see here - https://github.com/onnx/onnx/blob/rel-1.5.0/docs/Operators.md#Unsqueeze

Only in current master, it is supported - https://github.com/onnx/onnx/blob/master/docs/Operators.md#Unsqueeze. So when ORT supports opset-11, we will make sure to adhere per spec for Unsqueeze-11. 

Closing this ORT currently adheres to spec for Unsqueeze-10. (opset 11 is not yet supported in ORT)

**Comment by WilliamZhaoz** [comment]
hi @hariharans29 
I hit the same problem. I use python, how can I fix it since if the pip installed version is not latest and the custom builded is for c++.
What I can do is only change all -1 index to a positive index?

**Comment by dashesy** [comment]
@WilliamZhaoz or wait for opset11 in ORT. I looked at each case and found the positive index that would have same results, and changed all -1 to positive index equivalent. -1 is more elegant, but this should work

**Comment by Boodhayana** [comment]
> **Describe the bug** After adding random names to exported model and checking the node the issue is with exported `unsqueeze` with axes of -1. The node is not added in my code
> 
> **Urgency** Workaround is to use non-negative axis number
> 
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
> * ONNX Runtime installed from (source or binary): pip
> * ONNX Runtime version: 0.4
> * Python version: 3.5
> 
> **To Reproduce**
> 
> ```python
> torch.stack((bbs0, bbs1, bbs2, bbs3), dim=-1)
> ```
> 
> **Expected behavior** Run unsqueeze with axis -1
> 
> **Additional context** Sent the model

how to check the bad node?
