### ISSUE TITLE
[Performance] How to close this "Begin execution" log

### ISSUE THREAD

**Issue by ttandqq** [microsoft/onnxruntime#18110]
### Describe the issue

I find that when I call ORT::session::Run function,  the log "Begin execution" always be reported. I have call SetRunLogSeverityLevel and SetRunLogVerbosityLevel to set the level to ORT_LOGGING_LEVEL_WARNING,but still can not close the log report.

I think too many logs can affect the performance of predict.

### To reproduce

 Ort::RunOptions runOptions{};
runOptions.SetRunLogSeverityLevel(ORT_LOGGING_LEVEL_WARNING);
runOptions.SetRunLogVerbosityLevel(ORT_LOGGING_LEVEL_WARNING);

m_session.Run(runOptions, xx);

### Platform

Linux

### OS Version

Ret Hat

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

the newest version

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

### Is this a quantized model?

Yes

**Comment by ttandqq** [comment]
![image](https://github.com/microsoft/onnxruntime/assets/44218229/339893ca-0680-4b9d-9fc0-d00920f813fd)

**Comment by ttandqq** [comment]
ONNX Runtime Versionn is 14.1

**Comment by pranavsharma** [comment]
That line is [logged](https://github.com/microsoft/onnxruntime/blob/cf19c3697d126982acf45c040729269e53b5d9f4/onnxruntime/core/framework/sequential_executor.cc#L184) under verbose mode. You don't need to set any log level as the default is warning.

**Comment by ttandqq** [comment]
> That line is [logged](https://github.com/microsoft/onnxruntime/blob/cf19c3697d126982acf45c040729269e53b5d9f4/onnxruntime/core/framework/sequential_executor.cc#L184) under verbose mode. You don't need to set any log level as the default is warning.

But  If I do not set any log level, thest logs still be reported. I do not think these are Warning or Error level. 
![image](https://github.com/microsoft/onnxruntime/assets/44218229/bdb27da5-074a-40dd-8c63-40a768e5ed32)
