### ISSUE TITLE
Adding an extra Custom Attribute to an existing operator

### ISSUE THREAD

**Issue by adityat77** [microsoft/onnxruntime#18111]
### Describe the issue

I want to latch an extra attribute to each node of a simple MNIST ONNX model.
I'm able to add custom attributes and save the model. However, while loading the model for Inference, I'm getting this: 
`**Error Unrecognized attribute: CustomAttr for operator Conv**` 

 I've attached a link for the model for reference. 
 
 https://drive.google.com/file/d/1votf5NdwU2YHamhCsyrEDi3nkSCBPBjZ/view?usp=sharing

### To reproduce

Load the model using this: 

onnxruntime.InferenceSession("model.onnx")

### Platform

Linux

### OS Version

4.18.0

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.16.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by adityat77** [comment]
is there a better way to do this / any suggestions are appreciated

**Comment by hariharans29** [comment]
The short answer is this can't be done as it violates the ONNX spec/interface for the operators found in the MNIST model. The spec/interface for each operator may be found [here](https://github.com/onnx/onnx/blob/main/docs/Operators.md). The error you see while loading the mutated model is exactly complaining about this - it doesn't recognize the ne attribute as it isn't supported by the spec. Is there any reason why you need to add a custom attribute to every node in the model ?

**Comment by adityat77** [comment]
i'm trying to write an e2e application with onnxruntime ir. 
will explore alternatives, thanks.

**Comment by pranavsharma** [comment]
What do you plan to do with the custom attribute? What's your use case?

**Comment by hariharans29** [comment]
Please re-open the issue with more details
