### ISSUE TITLE
ONNXRuntimerServer PredictionServiceImplTests.HappyPath unittest SegFaults

### ISSUE THREAD

**Issue by yuslepukhin** [microsoft/onnxruntime#1813]
**Describe the bug**
As an unrelated PR kicked off CI builds HappyPath unit tests started segfauilting.

**Urgency**
This CI build is not mandatory but we want it to pass we can detect other issues.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from - part of CI build
- ONNX Runtime version: tip of the master

**To Reproduce**
This PR prompts the issue https://github.com/microsoft/onnxruntime/pull/1714
**Expected behavior**
Pass

**Additional context**
Turns out InferenceSession object is not properly initialized. The test is written in a way that some shared state presence depends on the order of test execution. While what needs to be done to fix it is clear, it is not not clear how it's been working until now.

See attached file
[ONNXServerSegFault.txt](https://github.com/microsoft/onnxruntime/files/3602789/ONNXServerSegFault.txt)

**Comment by yuslepukhin** [comment]
@csteegz Just a friendly reminder. One of our CI builds fails on it now.

**Comment by csteegz** [comment]
Yup. I have a sketch for a first PR on my fork, but I haven't tested it. Hope to open something today or the weekend.

**Comment by csteegz** [comment]
eek - this slipped, but I do really, really intend to get to it this week.
