### ISSUE TITLE
[Performance] Does onnxruntime support batch inference?

### ISSUE THREAD

**Issue by ttandqq** [microsoft/onnxruntime#18157]
### Describe the issue

It is much slower if inference like this.
for (int i=0; i< 10000; i++) {
  session.run(xx,xx,xx);
}

Does onnxruntime support batch inference? If yes, where can I get the details  or some examples? Thanks.

### To reproduce

batch inference

### Platform

Linux

### OS Version

Ret Hat

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

14.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

### Is this a quantized model?

Yes

**Comment by yufenglee** [comment]
Yes, ORT supports batch inference as long as your model support batch. You may refer to this as an example: https://github.com/microsoft/onnxruntime-inference-examples/blob/07aaa43bfc69f84a90c4a2a94a11ff4bbf7f0091/c_cxx/model-explorer/batch-model-explorer.cpp#L5

**Comment by ttandqq** [comment]
> Yes, ORT supports batch inference as long as your model support batch. You may refer to this as an example: https://github.com/microsoft/onnxruntime-inference-examples/blob/07aaa43bfc69f84a90c4a2a94a11ff4bbf7f0091/c_cxx/model-explorer/batch-model-explorer.cpp#L5

Thanks.Still have one question, I did some test and if the inference data is too small  (less than 10 rows)or too big(more than 1000 rows), performance of batch inference is worse than single row inference, is the test result correct?
