### ISSUE TITLE
[Build] 

### ISSUE THREAD

**Issue by palaniappankvignesh** [microsoft/onnxruntime#18186]
### Describe the issue

requirement.txt added as requirement.txt.in.

I observed this in both 1.16.1 and 1.13.1 versions

### Urgency

No

### Target platform

Windows

### Build script

setup.py

### Error / output

![image](https://github.com/microsoft/onnxruntime/assets/121725395/6aa7e70d-ea74-4697-89c9-f4a466adad34)

**Comment by snnn** [comment]
It is intentional. The *.in file is a template. We generate the final content during a build by running cmake.
