### ISSUE TITLE
[Build] Linux arm build error CompressedStorage.h:93:80: error: overflow

### ISSUE THREAD

**Issue by sarojlo** [microsoft/onnxruntime#18195]
### Describe the issue

Compiling on linux arm with cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=armv7-a -DCMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabihf-gcc-9   result in below error

/__w/1/s/onnxruntime/cmake/build/_deps/eigen-src/Eigen/src/Core/Assign.h:66:28:   required from 'Derived& Eigen::MatrixBase<Derived>::operator=(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Product<Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<float, float>, const Eigen::Transpose<const Eigen::Map<const Eigen::SparseMatrix<float, 1, long long int>, 0, Eigen::Stride<0, 0> > >, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Matrix<float, -1, -1> > >, Eigen::Map<const Eigen::Matrix<float, -1, -1, 1, -1, -1>, 0, Eigen::Stride<0, 0> >, 0>; Derived = Eigen::Map<Eigen::Matrix<float, -1, -1, 1, -1, -1>, 0, Eigen::Stride<0, 0> >]'
/__w/1/s/onnxruntime/onnxruntime/contrib_ops/cpu/math/sparse_dense_matmul.cc:71:50:   required from here
/__w/1/s/onnxruntime/cmake/build/_deps/eigen-src/Eigen/src/SparseCore/CompressedStorage.h:93:80: error: overflow in conversion from 'long long int' to 'int' changes value from '9223372036854775807' to '-1' [-Werror=overflow]
   93 |         Index realloc_size = (std::min<Index>)(NumTraits<StorageIndex>::highest(),  size + Index(reserveSizeFactor*double(size)));
      |                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /__w/1/s/onnxruntime/include/onnxruntime/core/framework/sparse_tensor.h:9,
                 from /__w/1/s/onnxruntime/onnxruntime/contrib_ops/cpu/math/sparse_dense_matmul.cc:6:
/__w/1/s/onnxruntime/include/onnxruntime/core/framework/tensor_shape.h: In member function 'virtual onnxruntime::common::Status onnxruntime::contrib::SparseToDenseMatMul::Compute(onnxruntime::OpKernelContext*) const':
/__w/1/s/onnxruntime/include/onnxruntime/core/framework/tensor_shape.h:86:106: note: parameter passing for argument of type 'gsl::span<const long long int>' changed in GCC 7.1
   86 |   TensorShape(std::initializer_list<int64_t> dims) : TensorShape(gsl::make_span(dims.begin(), dims.end())) {}
      |                                                                                                          ^
cc1plus: all warnings being treated as errors
CMakeFiles/onnxruntime_providers.dir/build.make:2259: recipe for target 'CMakeFiles/onnxruntime_providers.dir/__w/1/s/onnxruntime/onnxruntime/contrib_ops/cpu/math/sparse_dense_matmul.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_providers.dir/__w/1/s/onnxruntime/onnxruntime/contrib_ops/cpu/math/sparse_dense_matmul.cc.o] Error 1
CMakeFiles/Makefile2:1901: recipe for target 'CMakeFiles/onnxruntime_providers.dir/all' failed

### Urgency

Yes we are Microsft services and due to some recent fixes and features available need to move to upgrade onnxruntime version to 161

### Target platform

Linux

### Build script

picking this from build log

cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=armv7-a -DCMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabihf-gcc-9 -DCMAKE_CXX_COMPILER=/usr/bin/arm-linux-gnueabihf-g++-9 -Donnxruntime_GCC_STATIC_CPP_RUNTIME=ON -DCMAKE_BUILD_TYPE=MinSizeRel -Dprotobuf_WITH_ZLIB=OFF -Donnxruntime_BUILD_SHARED_LIB=ON -DPYTHON_EXECUTABLE=/usr/bin/python3

### Error / output

/__w/1/s/onnxruntime/cmake/build/_deps/eigen-src/Eigen/src/Core/Assign.h:66:28:   required from 'Derived& Eigen::MatrixBase<Derived>::operator=(const Eigen::DenseBase<OtherDerived>&) [with OtherDerived = Eigen::Product<Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<float, float>, const Eigen::Transpose<const Eigen::Map<const Eigen::SparseMatrix<float, 1, long long int>, 0, Eigen::Stride<0, 0> > >, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Matrix<float, -1, -1> > >, Eigen::Map<const Eigen::Matrix<float, -1, -1, 1, -1, -1>, 0, Eigen::Stride<0, 0> >, 0>; Derived = Eigen::Map<Eigen::Matrix<float, -1, -1, 1, -1, -1>, 0, Eigen::Stride<0, 0> >]'
/__w/1/s/onnxruntime/onnxruntime/contrib_ops/cpu/math/sparse_dense_matmul.cc:71:50:   required from here
/__w/1/s/onnxruntime/cmake/build/_deps/eigen-src/Eigen/src/SparseCore/CompressedStorage.h:93:80: error: overflow in conversion from 'long long int' to 'int' changes value from '9223372036854775807' to '-1' [-Werror=overflow]
   93 |         Index realloc_size = (std::min<Index>)(NumTraits<StorageIndex>::highest(),  size + Index(reserveSizeFactor*double(size)));
      |                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /__w/1/s/onnxruntime/include/onnxruntime/core/framework/sparse_tensor.h:9,
                 from /__w/1/s/onnxruntime/onnxruntime/contrib_ops/cpu/math/sparse_dense_matmul.cc:6:
/__w/1/s/onnxruntime/include/onnxruntime/core/framework/tensor_shape.h: In member function 'virtual onnxruntime::common::Status onnxruntime::contrib::SparseToDenseMatMul::Compute(onnxruntime::OpKernelContext*) const':
/__w/1/s/onnxruntime/include/onnxruntime/core/framework/tensor_shape.h:86:106: note: parameter passing for argument of type 'gsl::span<const long long int>' changed in GCC 7.1
   86 |   TensorShape(std::initializer_list<int64_t> dims) : TensorShape(gsl::make_span(dims.begin(), dims.end())) {}
      |                                                                                                          ^
cc1plus: all warnings being treated as errors
CMakeFiles/onnxruntime_providers.dir/build.make:2259: recipe for target 'CMakeFiles/onnxruntime_providers.dir/__w/1/s/onnxruntime/onnxruntime/contrib_ops/cpu/math/sparse_dense_matmul.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_providers.dir/__w/1/s/onnxruntime/onnxruntime/contrib_ops/cpu/math/sparse_dense_matmul.cc.o] Error 1
CMakeFiles/Makefile2:1901: recipe for target 'CMakeFiles/onnxruntime_providers.dir/all' failed

### GCC / Compiler Version

gcc-9

**Comment by snnn** [comment]
If you are a Microsoft employee, please open https://github.com/microsoft and there is a link for "guidance, policies, and tips". Please read them and link your account so that I can know how to contact you via a non-public channel.

**Comment by snnn** [comment]
Can you try the main branch instead?

**Comment by snnn** [comment]
The last release misses a fix that is in #13891

**Comment by sarojlo** [comment]
[Windows_error.txt](https://github.com/microsoft/onnxruntime/files/13221969/Windows_error.txt)
[linux_error.txt](https://github.com/microsoft/onnxruntime/files/13221970/linux_error.txt)
Yes even on latest i get error for Linux arm and windows arm.  windows UWP arm. Error is clear for linux , but i am not sure about windows and windows UWP arm if it is same error

**Comment by snnn** [comment]
Yes, I can reproduce it.

**Comment by sarojlo** [comment]
Looking at log can you confirm if its same for windows? I think yes

**Comment by snnn** [comment]
I am having an internal discussion with the dev regarding to this compiler warning.

**Comment by sarojlo** [comment]
Any progress over here , We still see issue in 1.16.3

**Comment by snnn** [comment]
Should have been fixed.
