### ISSUE TITLE
Gather the common statistics from the ONNX models

### ISSUE THREAD

**Issue by aliimani** [microsoft/onnxruntime#1820]
hi
I want to gather the common statistics from the ONNX models, like the number of each layer/operator and the kernel-size, stride, input/output tensor size of CONV operators.
Does anyone know how can I do it in python with ONNX Runtime API? 
thanks in advance.

**Comment by skottmckay** [comment]
The ONNX python API is probably simplest for analyzing static model properties. https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md

I would suggest looking at some of the python code in the ONNX repository for usage such as iterating the nodes in the graph. Weight data would be in the initializers. Start with printable_graph in helper.py
https://github.com/onnx/onnx/blob/adf9c7a381e200f0e79dcdc5a43c9a9bb75cd593/onnx/helper.py#L540

**Comment by faxu** [comment]
@aliimani Do those resources help or do you have additional questions?

**Comment by kartikpodugu** [comment]
Is there any tool or utility than can tell onnx model details like ?

1. no. of nodes
2. type of operators
3. no. of nodes of each operator
4. unique operator based on sizes
5. no. of inputs
6. no. of outputs

and more.
