### ISSUE TITLE
Building onnxruntime from source and run .onnx model in c++ using onnx c++ api

### ISSUE THREAD

**Issue by Debottam** [microsoft/onnxruntime#1822]
Hi @faxu ,
I got some success in building from onnxruntime from the source 
I was doing following steps to build onnxruntime from source
step1:
git clone --recursive https://github.com/Microsoft/onnxruntime
cd onnxruntime
step2:
Install cmake-3.13 or better from https://cmake.org/download/.
step3:
./build.sh --config RelWithDebInfo --build_shared_lib --parallel

This onnx runtime runs in python successfully (I have written a code here https://github.com/UTA-HEP-Computing/TensorFlowToOnnx/blob/master/tfToOnnx.ipynb)

but one thing, this seems not for x86_64
https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/build.py#L776

but I went ahead and compile my C++ code which is the squeezenet example (https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp)

g++ -L /home/debo/onnxruntime/build/Linux/RelWithDebInfo/ -o Capi_sample C_Api_Sample.cpp -I ./include -lonnxruntime -std=c++14

it creates the executable and when I run it

./Capi_sample
it complains
./Capi_sample: error while loading shared libraries: libonnxruntime.so.0.5.0: cannot open shared object file: No such file or directory

*******Another trial build from source with --x86 flag on *******
according to https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/build.py if I build onnxruntime with x86 flag it will build specific to x86, so I did following

./build.sh --config RelWithDebInfo --build_shared_lib --parallel --x86

but I get following errors
....
CMakeFiles/Makefile2:490: recipe for target 'CMakeFiles/onnxruntime_mlas.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_mlas.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
....
[ 21%] Linking CXX static library libprotobuf.a
[ 21%] Built target libprotobuf
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
File "/home/debo/onnxruntime/tools/ci_build/build.py", line 978, in
sys.exit(main())
File "/home/debo/onnxruntime/tools/ci_build/build.py", line 927, in main
build_targets(cmake_path, build_dir, configs, args.parallel)
File "/home/debo/onnxruntime/tools/ci_build/build.py", line 446, in build_targets
run_subprocess(cmd_args)
File "/home/debo/onnxruntime/tools/ci_build/build.py", line 192, in run_subprocess
return subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
File "/usr/lib/python3.5/subprocess.py", line 708, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/debo/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '-j48']' returned non-zero exit status 2
....
etc.

Need suggestions.
Thanks,
Debottam.

**Comment by Debottam** [comment]
Hi Developers,

I have technically resolved this issue,
1st: I was worried that the build from the source was building for amd64 architecture and my machine is x86-64 but as looked in details it seems x86-64 and amd64 are similar architecture.

2nd: I was getting a linking error
>> g++ -L /home/debo/onnxruntime/build/Linux/RelWithDebInfo/ -o Capi_sample C_Api_Sample.cpp -I ./include -lonnxruntime -std=c++14
>> ./Capi_sample 
./Capi_sample: error while loading shared libraries: libonnxruntime.so.0.5.0: cannot open shared object file: No such file or directory

so I figured out I need to also a copy of libonnxruntime.so.0.5.0 in my machine's /usr/lib/x86_64-linux-gnu/  and codes are running successfully.

well I still like to keep the issue open for some time since in the code I ran I was only loading and printing of a .onnx model. All I want to do right now is to load some test sample on that code and score/predict using that .onnx model. The .onnx inference I have, was generated from MNIST data, I want to test some MNIST test data to match the prediction using the c++ api.

Thanks,
Debo.

**Comment by faxu** [comment]
glad to hear you were able to get it working. if you have any suggestions for improving documentation on this, feel free to contribute. :)

let us know if you run into further issues.

**Comment by snnn** [comment]
Glad to see your problem is solved. 
amd64 and x86_64 are exactly the same thing. 
And, Linux has its own rule of locating the shared libraries, you need to follow that. Please run "man ld.so" , the document provides several different solutions to your problem.

**Comment by Debottam** [comment]
Hi @faxu and @snnn 
Thanks a lot for your reply and support.
Debottam

**Comment by Debottam** [comment]
Hi @faxu , @snnn ,

I will need another clarification please advice if I need to open a different issue for this. So I am currently able to load a model using c++ api and print its structure. Now I need to test my model by loading a test dataset. How do I do that ?? 
e.g. I have a mnist.onnx trained model which takes input of shape 1x28x28 and gives a 1x10 softmax output (handwritten digits) I have loaded this model using c++ api (very similar to this https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp) end I have mnist test sample ; now how do I load that test sample and check prediction using onnx runtime c/c++ api.

Thanks,
Debottam.

**Comment by snnn** [comment]
Hi @Debottam, see : https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx/MNIST

**Comment by Debottam** [comment]
Hi @snnn 

Thanks, I see this but its not for linux environment right? I will try to do similar in my linux platform.. if I got stuck there I will ask you here. I hope thats ok with you.
Thanks a lot,
Debottam

**Comment by snnn** [comment]
A key part is you need to know what's the preprocessing step of your model.  You can't directly feed an image file into an ONNX model.

**Comment by Debottam** [comment]
Hi @snnn 
I have documented some current issues regarding onnx runtime c/c++ API which I am having during scoring (https://github.com/UTA-HEP-Computing/TensorFlowToOnnx/tree/master ), I am guessing main issue is coming from 'None' in model dimension which allows to have multiple inputs I have more details in the README of the github page.

Thanks,
Debottam

**Comment by Debottam** [comment]
Hi @snnn 

Please let me if I need to open a different issue for this situation?

Thanks,
Debottam.

**Comment by snnn** [comment]
> My concern is None dimention of the model is being converted to -1 Do we need to fix it ? 

You need to change the -1 to an actual value, for example, one, before feed the shape info into OrtCreateTensorWithDataAsOrtValue.

**Comment by Debottam** [comment]
Hi @snnn ,
Thanks, this issue has  been resolved now I can predict mnist handwritten digits with c/c++ API https://github.com/UTA-HEP-Computing/TensorFlowToOnnx 
Thanks,
Debottam.
