### ISSUE TITLE
[Build] When will onnxruntime.training be updated? 

### ISSUE THREAD

**Issue by pauldog** [microsoft/onnxruntime#18261]
### Describe the issue

When I do `pip install onnxruntime.training` it is still on version 1.15.1 

When is the new version being released?

### Target platform

Windows 10

### Build script

n/a

### Error / output

n/a

**Comment by snnn** [comment]
The latest version is 1.16.0

https://pypi.org/project/onnxruntime-training/

Please update your pip. Like

$ python3 -m pip install --upgrade pip

**Comment by askhade** [comment]
Installation instructions:
python -m pip install cerberus flatbuffers h5py numpy>=1.16.6 onnx packaging protobuf sympy setuptools>=41.4.0
pip install -i https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT/pypi/simple/ onnxruntime-training-cpu

You can find all the different combinations here: https://onnxruntime.ai/getting-started
