### ISSUE TITLE
MeanVarianceNormalization v9 CPU kernel doesn't honor axes attribute

### ISSUE THREAD

**Issue by fdwr** [microsoft/onnxruntime#1828]
**Describe the bug**
The MeanVarianceNormalization v9 CPU kernel doesn't honor the `axes` attribute, which supports arbitrary axes. It just tries to map them into the *older* operator kernel's parameters (the `cross_channel` attribute, which supported only NCHW and NHW). However, the mapping doesn't do any error checking to see whether the `axes` are actually mappable (e.g. HW gets blindly mapped to NHW, or NC gets mapped to NCHW, which isn't correct). So the core issue is that v9 isn't fully implemented for reduction along arbitrary axes, but a bigger issue is that it silently returns the wrong result - it should return a failing error message for incompatible parameters.

https://github.com/microsoft/onnxruntime/blob/8712a523a4cda4500256aafae378558e64d1f672/onnxruntime/core/providers/cpu/tensor/mean_variance_normalization.h#L108

**Urgency**
When able. We haven't found any models locally that actually use MVN (scanning 1381 in the WinML model collection), excluding our ONNX conformance tests.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Vibranium
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 0.5
- Python version: NA
- Visual Studio version (if applicable): 2017
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**To Reproduce**
Pass `axes` with [2,3] to MVN v9:

    {
      "op_type": "MeanVarianceNormalization",
      "version": 9,
      "axes": [2,3], // Only height, width (no normalization across batch dimension)
      "X": {"value": [ [[[1, 2], [3, 4]]], [[[1, 2], [3, 4]]] ]},
      "Y": {"value": [ [[[-1.34164, -0.447214], [0.447214, 1.34164]]], [[[-1.34164, -0.447214], [0.447214, 1.34164]]] ]},
      "T": "float32"
    }

**Expected behavior**
Mean reduction occurs along `axes` passed.

Until then, report an error:

    constexpr int64_t cross_channel_axes[] = { 0,1,2,3 };
    constexpr int64_t batch_spatial_axes[] = { 0,2,3 };

    if (std::equal(std::begin(axes), std::end(axes), std::begin(cross_channel_axes), std::end(cross_channel_axes)))
    {
        this->across_channels_ = true;

    }
    else if (std::equal(std::begin(axes), std::end(axes), std::begin(batch_spatial_axes), std::end(batch_spatial_axes)))
    {
        this->across_channels_ = false;
    }
    else
    {
        ORT_THROW("MeanVarianceNormalization axes parameter only supports NHW and NCHW reduction.");
    }

**Additional context**
This was found during ONNX conformance test testing for WinML.

**Comment by fdwr** [comment]
Added validation. The operator still doesn't support `axes` fully, but at least it won't return the wrong result silently now.

**Comment by motikad** [comment]
Using onnxruntime-openvino==1.14.0

We are getting the following error when loading an ORT session on a specific model with the `CPUExecutionProvider`-
`[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /home/onnxruntimedev/onnxruntime/onnxruntime/core/providers/cpu/tensor/mean_variance_normalization.h:116 onnxruntime::MeanVarianceNormalization_1<T>::MeanVarianceNormalization_1(const onnxruntime::OpKernelInfo&) [with T = float] MeanVarianceNormalization CPU EP only supports NHW and NCHW reduction for axes attribute.`

The same model works well with `OpenVINOExecutionProvider` provider.
We need this op supported in the standard CPU provider, so we can also run inference on AMD CPUs on AZURE for example.
@faxu can you help with that? Thanks!

**Comment by fdwr** [comment]
@motikad Seems we have a real model now finally that hits this. Want to reopen the issue? It's interesting to hear that OpenVINO also supports axes along with the DML EP, because typically the CPU provider is more complete and compliant to the ONNX spec than the secondary EP's. Being unfamiliar with the code, I made the minimal change last year to at least warn the user of incorrect results, but hopefully someone on ORT who is familiar with Eigen can update this. 👍
