### ISSUE TITLE
[Web] WebGPU has conformance regression due to introduction of FusedConv

### ISSUE THREAD

**Issue by gyagp** [microsoft/onnxruntime#18297]
### Describe the issue

Due to PR below, some models (like mobilenetv2-12 and detr-resnet-50) have conformance regression

commit a2e9ba72d5a5f61e1324ffc2a80d748d01be9120 (HEAD -> main)
Author: satyajandhyala <satya.k.jandhyala@gmail.com>
Date:   Wed Nov 1 15:34:51 2023 -0700

    [JS/Web]Added FusedConv. (#17766)

### To reproduce

* Build the latest ONNX Runtime WebGPU
* Visit below url and point <local_build> to your local build. For example: ortUrl=https://abc.com/onnxruntime
https://webatintel.github.io/ort-toolkit/?tasks=conformance&ep=webgpu&modelName=mobilenetv2-12&modelUrl=hf&ortUrl=<local_build>
* You may see {"result":false} in "Test Results" section.

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

a2e9ba72d5a5f61e1324ffc2a80d748d01be9120

### Execution Provider

'webgpu' (WebGPU)

**Comment by gyagp** [comment]
@satyajandhyala, could you please take a look?

**Comment by qjia7** [comment]
Provide a fix here #18388.
