### ISSUE TITLE
How to get the model structure and parameters

### ISSUE THREAD

**Issue by gkUwen** [microsoft/onnxruntime#1832]
I want to get the model structure (for example, input->conv->max_pooling->...) and the corresponding parameters by using the C++ API.  However, I did not find the API in "onnxruntime_cxx_api.h". It only can get the input size.

Could anyone tell me how to get these parameters by C++?
Thank you very much!

**Comment by hariharans29** [comment]
Hi, 

I think this request is similar to #1820 in that it is a question regarding model structure. Please check if the answers there help.

Thanks.
