### ISSUE TITLE
QNN EP: Non quantized models do not run on the HTP

### ISSUE THREAD

**Issue by john-dance** [microsoft/onnxruntime#18351]
### Describe the issue

The QNN Execution Provider requires QDQ, yet with other environments (TfLite + QNN Delegate) the HTP will run the non-quantized model.

Android Samsung Galaxy S23 + onnxruntime + QNN Execution Provider + libQnnHtp.so backend with a simple cnn model:

```
Non-QDQ Conv operators are not supported on HTP or DSP backends. Conv node `/conv5/Conv will not be assigned to QNN EP.
Node supported: [0] index: [7] name: [/conv5/Conv] Operator type: [Conv] as part of the NodeUnit type: [Conv] index: [7] name: [/conv5/Conv]
Non-QDQ Relu operators are not supported on HTP or DSP backends. Relu node `/Relu_3 will not be assigned to QNN EP.
Node supported: [0] index: [8] name: [/Relu_3] Operator type: [Relu] as part of the NodeUnit type: [Relu] index: [8] name: [/Relu_3]
Non-QDQ Reshape operators are not supported on HTP or DSP backends. Reshape node `/Reshape will not be assigned to QNN EP.
Node supported: [0] index: [9] name: [/Reshape] Operator type: [Reshape] as part of the NodeUnit type: [Reshape] index: [9] name: [/Reshape]
Non-QDQ Gemm operators are not supported on HTP or DSP backends. Gemm node `/fc1/Gemm will not be assigned to QNN EP.
Node supported: [0] index: [10] name: [/fc1/Gemm] Operator type: [Gemm
[onnx_simple_cnn.ort.zip](https://github.com/microsoft/onnxruntime/files/13300189/onnx_simple_cnn.ort.zip)
] as part of the NodeUnit type: [Gemm] index: [10] name: [/fc1/Gemm]
Number of partitions supported by QNN EP: 0
```

### To reproduce

Run the attached .ort model with the QNN Execution Provider + libQnnHtp.so backend.
```
    qnnOptions["backend_path"] = "<path>/libQnnHtp.so";
    qnnOptions["profiling_level"] = "basic";
    qnnOptions["htp_performance_mode"] = "burst";
    onnxSessionOptions.AppendExecutionProvider("QNN", qnnOptions);

```

### Platform

Android

### OS Version

34

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.16

### ONNX Runtime API

C++

### Architecture

ARM64

### Execution Provider

Other / Unknown

### Execution Provider Library Version

QNN: 1.16

**Comment by HectorSVC** [comment]
Samsung Galaxy S23 has Qualcomm SM8550-AC Snapdragon 8 Gen 2 (4 nm) which support FP16 mode. I suppose your run with TfLite + QNN Delegate is using FP16 mode. Could you double check? For Ort QNN EP we do not support FP16 mode for now.

**Comment by john-dance** [comment]
Yes, on TfLite + QNN it implicitly using the FP16 mode. It implicitly uses FP16 even though we gave it an FP32 model.

Is there a timeline to support FP16 mode in Ort QNN EP?

**Comment by HectorSVC** [comment]
I merged the PR to support inference float32 model with fp16 precision: https://github.com/microsoft/onnxruntime/pull/19863
Actually, you can also convert the float32 model to fp16 model (https://onnxruntime.ai/docs/performance/model-optimizations/float16.html), then inference with QNN EP. It has better performance from my testing.

**Comment by john-dance** [comment]
Thank you @HectorSVC, in the latest main, these models now run.
