### ISSUE TITLE
Errors Encountered After Program Termination (C# OnnxRuntimeGpu)

### ISSUE THREAD

**Issue by Double-Quotes** [microsoft/onnxruntime#18359]
```
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Diagnostics;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            var gpuSessionOptoins = SessionOptions.MakeSessionOptionWithCudaProvider(0);
            string modelFilePath1 = @"unet.onnx";
            var session1 = new InferenceSession(modelFilePath1, gpuSessionOptoins);
        }
    }
}
```
After my program **ENDs**, an error occurred!
`System.AccessViolationException:“尝试读取或写入受保护的内存。这通常指示其他内存已损坏。”`
`此异常最初是在此调用堆栈中引发的: 
    Microsoft.ML.OnnxRuntime.SessionOptions.ReleaseHandle() - 位于 SessionOptions.shared.cs
    [外部代码]
`

`System.AccessViolationException: "An attempt was made to read or write to protected memory. This usually indicates that other memory is corrupted."`
`This exception was originally raised on this call stack:. 
    Microsoft.ML.OnnxRuntime.SessionOptions.ReleaseHandle() - located at SessionOptions.shared.cs
    [external code]`

System information

OS Platform and Distribution: win10
ONNX Runtime version: 1.14.1
Visual Studio version (if applicable): vs2019
CUDA/cuDNN version: 11.6
GPU model and memory: Quadro RTX 4000

I'm guessing it might be because of the GPU model?
Thank you!

**Comment by yuslepukhin** [comment]
https://onnxruntime.ai/docs/tutorials/csharp/basic_csharp.html

**Comment by Double-Quotes** [comment]
> https://onnxruntime.ai/docs/tutorials/csharp/basic_csharp.html

Thank you! @yuslepukhin
