### ISSUE TITLE
[Feature Request] Android public getNativeHandler

### ISSUE THREAD

**Issue by dizcza** [microsoft/onnxruntime#18369]
### Describe the feature request

I'd like to pass OrtSession to C++ code running on Android just like I pass `cv::Mat` or `cv::dnn::Net` objects to C++.

There is a `getNativeHandler()` function but it's not public. Please make it so.

### Describe scenario use case

Reusing C++ ONNX code on Android.

**Comment by Craigacp** [comment]
You'd like to pass the native pointer to the OrtSession out of Java and into native code? Why not just use it directly from C++?

**Comment by dizcza** [comment]
> You'd like to pass the native pointer to the OrtSession out of Java and into native code?

Yes

> Why not just use it directly from C++?

Because I cannot read a model from Android raw resources in C++ once compiled in an archive (apk file) - there is no notion of a model path (or any other object path placed in the `raw` directory of an Android project). This is the same reason why Android developers instantiate a `cv::dnn::Net` in Java and pass it as the reference to native C++.

Alternatively, I could work out `Session(const Env& env, const void* model_data, size_t model_data_length, const SessionOptions& options);` given that I supply four pointers (one per argument) instead of one but again, `OrtEnv` & `SessionOptions` do not have a public `getNativeHandle()` function. Even if they had, why not provide the same functionality, `getNativeHandle()`, for `OrtSession` in the first place?

**Comment by Craigacp** [comment]
Those methods aren't public to ensure that the Java code is in complete control of the lifetime of the session and other native objects. Otherwise it could be closed in native code which could crash the JVM if it's accessed from Java again.

**Comment by Craigacp** [comment]
The fields are readable from JNI anyway as it doesn't have the same access protections, so you can pass the Java session object down into your JNI code and either call the method or do a direct field read to get the handle out

**Comment by dizcza** [comment]
> Those methods aren't public to ensure that the Java code is in complete control of the lifetime of the session and other native objects. Otherwise it could be closed in native code which could crash the JVM if it's accessed from Java again.

Yes, and OpenCV maintainers do mention this: if the user is up to broadcasting the pointers back and forth between Java and C++, he or she becomes responsible for the correct lifetime of the shared objects. Typically, instances are created in JVM and passed to C++, and never deallocated in C++, and therefore automatically handled by the garbage collector.

> The fields are readable from JNI anyway as it doesn't have the same access protections, so you can pass the Java session object down into your JNI code and either call the method or do a direct field read to get the handle out.

But how? I ain't get your message. The getNativeHandle() function isn't public. "The fields are readable from JNI anyway" - how?

**Comment by dizcza** [comment]
This discussion has been split in two, and I figured out a way to achieve what I want: pass model bytes from JVM to C++ and create an Ort session in C++, and deallocate in C++ when done. Since I won't be needing an Ort session on the Java side, this approach will do the job. Still, making the pointers of Ort session/env/options accessible for the users will not do any harm... if they know what they're doing.

**Comment by Craigacp** [comment]
> > The fields are readable from JNI anyway as it doesn't have the same access protections, so you can pass the Java session object down into your JNI code and either call the method or do a direct field read to get the handle out.
> 
> But how? I ain't get your message. The getNativeHandle() function isn't public. "The fields are readable from JNI anyway" - how?

If you have the `jobject` which refers to the Java `OrtSession` then you can call `GetFieldID` on the object with the name `nativeHandle` & the signature `J` for a long, then call `GetLongField` with the id returned from `GetFieldID` (https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#Get_type_Field_routines). JNI doesn't respect the Java language access privileges so it can read private fields, it's one of the reasons that it's considered unsafe as compared to the new FFM API which doesn't allow that kind of access into Java objects.

> This discussion has been split in two, and I figured out a way to achieve what I want: pass model bytes from JVM to C++ and create an Ort session in C++, and deallocate in C++ when done. Since I won't be needing an Ort session on the Java side, this approach will do the job. Still, making the pointers of Ort session/env/options accessible for the users will not do any harm... if they know what they're doing.

My strong preference is the API doesn't expose any methods which are unsafe, and advanced users can always use JNI to break into the API anyway to get the native pointers.

**Comment by dizcza** [comment]
> If you have the jobject which refers to the Java OrtSession then you can call GetFieldID on the object with the name nativeHandle & the signature J for a long, then call GetLongField with the id returned from GetFieldID (https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#Get_type_Field_routines). JNI doesn't respect the Java language access privileges so it can read private fields, it's one of the reasons that it's considered unsafe as compared to the new FFM API which doesn't allow that kind of access into Java objects.

This is veeery hacky. Forever I'll be damned by my colleagues if I stick to such an approach! But thanks for the insight - I actually didn't know about it.

I'll choose either passing model bytes pointer to C++ or porting my forward inference code from C++ to Java. So yeah, considering that I'm the only one who has asked for such a request, and others get around such an issue by some other means, the "Android devs typically don't write in C" claim holds true indeed!

Closing as kinda not worth the trouble.
