### ISSUE TITLE
[Feature Request] take model as Request or Promise<ArrayBuffer> in InferenceSessionFactory.create

### ISSUE THREAD

**Issue by mrdomino** [microsoft/onnxruntime#18364]
### Describe the feature request

In addition to taking an ArrayBuffer or URL, it'd be nice if `create` could take a Promise<ArrayBuffer> that it awaits, or a [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) that can be further customized.

### Describe scenario use case

I'd like to load a model from a URL that requires an Authorization header. I could just fetch it myself and pass the `ArrayBuffer`, but then I would have to wait to call `create` until the full model has been downloaded. I want to call `create` as early as possible so that the wasm file can be downloaded, and the backend initialized, as early as possible.

Either the Request or Promise option would work equally well for my case. The Promise is probably slightly more generally useful.

**Comment by mrdomino** [comment]
I'm looking at getting started on a PR for this, and I'm wondering how it ought to work. There seem to be overloads of `create` for `ArrayBufferLike`, `ArrayBufferLike` plus `byteOffset` and `byteLength`, and `Uint8Array`. To Promise-ify all three would create three more method signatures. This could either be fine or excessive — I'm not sure which.

At a certain point it seems like it'd be expedient to wrap the non-Promise methods in `Promise.resolve` to keep a single API at a lower level, and I'm wondering if/where to do that as well.

**Comment by mrdomino** [comment]
This is probably the wrong sort of motivation, but this consideration has me leaning in the direction of using Requests rather than Promises...

**Comment by mrdomino** [comment]
Hmm, and since the API is shared by `web/` and `node/`, it seems like the Node implementation also needs to be considered. Is it at all desirable to support fetching from Node? Otherwise there is little reason to expose a `Request` API there.

**Comment by fs-eire** [comment]
> I'd like to load a model from a URL that requires an Authorization header. I could just fetch it myself and pass the ArrayBuffer, but then I would have to wait to call create until the full model has been downloaded. I want to call create as early as possible so that the wasm file can be downloaded, and the backend initialized, as early as possible.

The current ort-web implementation does not have the capability to get any "real" benefits from initializing the model earlier. You may assume that the model downloading takes time, and session initialization takes time as well, and if possible - do the 2 tasks at the same time. This is a great idea, but unfortunately, ONNX Runtime does not really have a stream-loading support for the model, so there is not too many thing we can do to accept a stream instead of array buffer. As you may see from the source code, ORT API need the whole buffer ready to do the next step.

**Comment by mrdomino** [comment]
The task that my current PR (which adds `Promise<ArrayBufferLike|Uint8Array>` options to `InferenceSessionFactory.create`) allows to parallelize is initializing the library — specifically, downloading the appropriate wasm file, which otherwise has to happen strictly after the model is downloaded, if a custom Request needs to be used.

This seems like a win? Am I missing something?

**Comment by mrdomino** [comment]
I took another look at this, and I now see that I can accomplish what I wanted by just preloading the appropriate wasm file and passing the model via `ArrayBuffer`. Otherwise you're right, there's not much to be gained here. Closing.
