### ISSUE TITLE
How can I get the data from OrtValue without casting Numpy which copies it on CPU?

### ISSUE THREAD

**Issue by TolgaOzdmir** [microsoft/onnxruntime#18361]
### Discussed in https://github.com/microsoft/onnxruntime/discussions/18324

<div type='discussions-op-text'>

<sup>Originally posted by **TolgaOzdmir** November  7, 2023</sup>
I wanted to use ONNX Runtime with IOBİndings on Python. I did that. However, session.get_outputs() returns OrtValues and I cannot get their data without casting Numpy which copies it to CPU. SO, is there anyway to get the data from OrtValue without changing device and memory address? Thank you</div>

**Comment by tianleiwu** [comment]
OrtValue points to a memory buffer. If the buffer is pre-allocated and you bind it to output. You can get the data in that buffer directly without casting.

An example to bind to a torch tensor buffer:
https://github.com/microsoft/onnxruntime/blob/d9558857913b32a9d701d217362017b892a2769c/onnxruntime/python/tools/transformers/io_binding_helper.py#L265-L277

**Comment by TolgaOzdmir** [comment]
thank you for the response. The thing is I get the data which is OrtValue, but I cannot get the data inside of the OrtValue. For example, there is no code that I know for getting data like ortvalue.get_tensor(). I have just found OrtValue.numpy() command, when I did this casting, I can see the output values. The problem with that is the method copied the data to CPU when doing numpy casting. So, I want to see some values however when I print OrtValue it prints some object text with data adress. Sample code is as follows:


`
   providers = [('CUDAExecutionProvider', {'device_id': 0, 'cudnn_conv_algo_search': 'EXHAUSTIVE', 'do_copy_in_default_stream': True,  'cudnn_conv1d_pad_to_nc1d': 0, 'enable_cuda_graph': 0, "cudnn_conv_use_max_workspace": 1}), 'CPUExecutionProvider']
    sess_options = ort.SessionOptions()
    sess_options.enable_profiling = True
   
 ort_session = ort.InferenceSession(model_path, sess_options=sess_options, providers=providers)
    
    input_data_info = ort_session.get_inputs()[0]
    io_binding = ort_session.io_binding()
    input_data_numpy = np.random.randint(0, 255, input_data_info.shape).astype(np.float32)
    X_ortvalue = ort.OrtValue.ortvalue_from_numpy(input_data_numpy, 'cuda', 0)
    io_binding.bind_input(name=input_data_info.name,
                          device_type=X_ortvalue.device_name(),
                          device_id=0,
                          element_type=np.float32,
                          shape=X_ortvalue.shape(),
                          buffer_ptr=X_ortvalue.data_ptr())

    
    output_data = ort_session.get_outputs()
    for tensor in output_data:
        io_binding.bind_output(tensor.name, 'cuda')
    
    ort_session.run_with_iobinding(io_binding)


    ort_output = io_binding.get_outputs()
    for tensor in ort_output:
        print(tensor.numpy(), tensor.numpy().shape) # in this part, I want to get the data without casting numpy from OrtValue
`

result of print OrtValue:
![image](https://github.com/microsoft/onnxruntime/assets/45563852/4411c4ef-af41-4491-8efe-5682e07c3d69)

result of print Numpy (that I want without casting Numpy):
![image](https://github.com/microsoft/onnxruntime/assets/45563852/947d525b-b679-4243-9b50-d3276301d819)

**Comment by tianleiwu** [comment]
In the example code I shared, the torch tensor will have the data after run_with_iobinding. See the inference code:
https://github.com/microsoft/onnxruntime/blob/d9558857913b32a9d701d217362017b892a2769c/onnxruntime/python/tools/transformers/io_binding_helper.py#L308-L310

It is not required to call get_outputs() if you have set output buffer in io binding. Note that the torch tensor is still in GPU memory. I think that could fit your requirement.

**Comment by TolgaOzdmir** [comment]
I get it now but I have a condition that I should have mentioned before. I use 4 outputs ('num_det', 'bbox', 'conf_score', 'label') and these must be dynamic-sized since I can't predict how many bounding boxes will the model find, etc. That's why I can't create a static-sized tensor and I can't give its data_ptr(). Also, because of this, I have another problem I have to clear output bindings and bind output again for each inference.

**Comment by xadupre** [comment]
onnxruntime implements DLPack protocol but does not enable it by default. Would that answer your need if onnxruntime would enable it for all versions?

**Comment by TolgaOzdmir** [comment]
thank you both @xadupre @Numeri. @Numeri suggested me the exact code that I need. In this link, the to_pytorch function is an answer to my question. However, it uses DLPack so @xadupre is right too. Thank you again. I think the answer to this issue that I have encountered should be in the [Python API link](https://onnxruntime.ai/docs/api/python/api_summary.html) since everyone needs to access the data from the cuda without copying it to the CPU when they use dynamic-sized data. Also, I have an issue with the inference time but I will create a new issue for this and I will close this one.

**Comment by Stonesjtu** [comment]
> onnxruntime implements DLPack protocol but does not enable it by default. Would that answer your need if onnxruntime would enable it for all versions?

@xadupre  Could you give an example how to turn on the dlpack support/
