### ISSUE TITLE
1.16.2 missing wheels

### ISSUE THREAD

**Issue by damonallison** [microsoft/onnxruntime#18378]
### Describe the issue

The latest `1.16.2` release only has a single `osx` `x86_64` wheel on pypi.org, causing us to pin to `1.16.1`. Are there plans to publish wheels for all platforms / archs?

https://pypi.org/project/onnxruntime/#files

### To reproduce

https://pypi.org/project/onnxruntime/#files

### Urgency

No blockers / inconvenience only

### Platform

Mac

### OS Version

Darwin Kernel Version 22.6.0

### ONNX Runtime Installation

Other / Unknown

### ONNX Runtime Version or Commit ID

1.16.2

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by snnn** [comment]
Thanks for reporting the issue to us. We hit an internal error during the publishing . I will create an internal ticket to ask for support.

**Comment by snnn** [comment]
Resolved.
