### ISSUE TITLE
[Mobile] Fatal error: ai.onnx.contrib:BpeDecoder(-1) is not a registered function/op

### ISSUE THREAD

**Issue by sirramin** [microsoft/onnxruntime#18403]
### Describe the issue

When I want to run whisper_cpu_int8_model.onnx model in react native I get this error:

> Error: Can't load a model: Error code - ORT_FAIL - message: Fatal error: ai.onnx.contrib:BpeDecoder(-1) is not a registered function/op

### To reproduce

```
const assets = await Asset.loadAsync(require("./assets/whisper_cpu_int8_model.onnx"));
const modelUri = assets[0].localUri;
Session = await InferenceSession.create(modelUri);
```

### Platform

React Native

### OS Version

11

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

onnxruntime-react-native

### ONNX Runtime Version or Commit ID

1.16.1

### ONNX Runtime API

JavaScript

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
BpeDecoder is not currently included in the mobile onnxruntime-extensions package. We can look at adding it in the next release.

**Comment by sirramin** [comment]
find the solution. should add this to package.json:
`  "onnxruntimeExtensionsEnabled": "true"`

**Comment by skottmckay** [comment]
Excellent. It is documented but a little hard to find. We could probably update the basic react native example to include this info. 

https://onnxruntime.ai/docs/get-started/with-javascript.html#enable-onnx-runtime-extensions-for-react-native
