### ISSUE TITLE
Memory leak backend rep.run(input_data)

### ISSUE THREAD

**Issue by fgadaleta** [microsoft/onnxruntime#1844]
**Describe the bug**

When executing inference with 

```
rep = backend.prepare(onnx_model, 'CPU')
probs = self.rep.run(input_data)
```

memory requirements explode if input_data is as large as 10000 records.
 

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- Mac OS 10.14.16 Mojave 
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 0.1.4
- Python version: 3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
setup backend and run inference with input data shape=10000 x ..
**Expected behavior**
Inference on the same amount of input data with keras model doesn't require a lot of memory

**Comment by skottmckay** [comment]
Can you please share the model and the input data, as well as any non-default configuration settings you used? 

What does 'explode' equate to? Is the memory usage growth linear with the batch size?

Are you running Keras with the same batch size?

**Comment by fgadaleta** [comment]
At this point I can believe I am passing a huge batch that fills in the memory. 
Is there a way to define the batch_size in the runtime?

**Comment by fgadaleta** [comment]
With this I consistently reduce the memory footprint. But still in the order of 10GB (!!) and when `sess.run` returns it never frees memory. I need to `del sess` to free.

```
import onnxruntime as rt
import numpy as np

sess = rt.InferenceSession('my_model.onnx')
x_train, y_train, x_test, y_test = load_data()

input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name

pred_onx = sess.run([label_name], {input_name: x_test.astype(np.float32)})[0]
print(pred_onx)
```

Do I need to batch predictions myself?

**Comment by skottmckay** [comment]
> Do I need to batch predictions myself?

Yes. You're passing data that's already loaded into memory into the 'run' call, and ORT is processing that. If you want to consume less memory you'd lead to load smaller chunks and call 'run' more times with those.

ORT does free memory before it returns from the inferencing though. Are you sure ORT is holding memory, or are things like the session inputs and outputs consuming 10GB?

**Comment by fgadaleta** [comment]
Ok tuning the batch manually and calling run multiple times (after creating the session) reduces the memory footprint. Still much higher than the memory footprint of the same model in keras (for instance). But does the job.
We can close this issue
