### ISSUE TITLE
How can I get the graph after subgraph fusion stage (graph transformer)?

### ISSUE THREAD

**Issue by fengyuentau** [microsoft/onnxruntime#18451]
### Describe the issue

I want to get the graph after [graph transformers](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/core/optimizer/graph_transformer_utils.cc) are applied. How can I do that?

### To reproduce

N/A

### Platform

Mac

### OS Version

Ventura 13.5.1

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.1

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by satyajandhyala** [comment]
Can you try specifying optimized_model_filepath in SessionOption ? 
https://onnxruntime.ai/docs/api/python/api_summary.html#:~:text=property-,optimized_model_filepath,-%23

**Comment by fengyuentau** [comment]
Could you also give an example how to use these options?

**Comment by justinchuby** [comment]
In the documentation linked above there is

```python
options = onnxruntime.SessionOptions(
    optimized_model_filepath="optimized.onnx"
)
options.enable_profiling=True
session = onnxruntime.InferenceSession(
    'model.onnx',
    sess_options=options,
    providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
)
```

**Comment by fengyuentau** [comment]
Thank you all for the help.

---

@justinchuby There is an extra parenthesis ")" in the end of your example.

Also worth mentioning that default `options.graph_optimization_level` is `ort.GraphOptimizationLevel.ORT_ENABLE_ALL`.
