### ISSUE TITLE
[Feature Request] Objective-C Support for Mac

### ISSUE THREAD

**Issue by AppTyrant** [microsoft/onnxruntime#18458]
### Describe the feature request

According to the official page here: https://onnxruntime.ai/getting-started the Objective-C API is supported for iOS but if you change the platform to Mac it says the combination is not supported. 

It looks like the macOS builds of the onnx runtime don't include the Objective-C API (https://github.com/microsoft/onnxruntime/releases). Reusing the code from the onnxruntime-objc CocoaPod on Mac should be possible without many code changes (if any). And it would be nicer to work with the ObjC API when deploying on Mac.

Thanks for your time and consideration.

### Describe scenario use case

Deploying a macOS app that uses the ONNX Runtime

**Comment by skottmckay** [comment]
We're looking at adding a macOS build to the cocoapod in the next release.

**Comment by skottmckay** [comment]
Added in 1.17
