### ISSUE TITLE
Is tensor_info.GetShape() return -1 a bug?

### ISSUE THREAD

**Issue by bitnick10** [microsoft/onnxruntime#1845]
```
input_node_dims = tensor_info.GetShape(); // this will return {-1,*}
// when input_node_dims[0]==-1 ,this will cause size overflow
Ort::Value input_tensor = Ort::Value::CreateTensor<float>(allocator_info, input_tensor_values.data(), input_tensor_size, input_node_dims.data(), 2);
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary):nuget
- ONNX Runtime version:0.5

**Comment by skottmckay** [comment]
No. 

A shape can have a symbolic dimension that isn't known until runtime. e.g. the batch size dimension may change each time. That dimension has a value of -1 in ORT.
