### ISSUE TITLE
The input of ONNX Runtime Server

### ISSUE THREAD

**Issue by xs233** [microsoft/onnxruntime#1848]
I am using ONNX Runtime Server to load a model. When I call the GRPC endpoint, I got an error.

`code = InvalidArgument desc = ONNX Runtime Status Code: 2. Invalid Feed Input Name:xy`

I tried to use some other input name, unfortunately, it's all wrong. How can I get the true name for inputs? I have no idea for this.
```
// PredictRequest specifies how inputs are mapped to tensors
// and how outputs are filtered before returning to user.
message PredictRequest {
  reserved 1;

  // Input Tensors.
  // This is a mapping between output name and tensor.
  map<string, onnx.TensorProto> inputs = 2;

  // Output Filters.
  // This field is to specify which output fields need to be returned.
  // If the list is empty, all outputs will be included.
  repeated string output_filter = 3;
}
```

**Comment by csteegz** [comment]
I think this is more a question then an issue report.

ORT server is looking for the ID field of the input. 

I'd suggest using something like [Netron](https://github.com/lutzroeder/netron) to visualize your onnx graph. You can then click on the graph, and you'll get the inputs, including the ID. An example of locating the input in `test\testdata\mul_1.onnx`, where the input is "X".

![image](https://user-images.githubusercontent.com/5024543/65168813-29ed9c00-d9fa-11e9-808c-b9be20200b2a.png)

**Comment by TMVector** [comment]
+1 for using Netron :smile: 

You can also use the [onnx](https://pypi.org/project/onnx/) python library to inspect the model file (the protobuf definition is [here](https://github.com/onnx/onnx/blob/master/onnx/onnx.in.proto) FYI).

```python
import onnx
model = onnx.load('path/to/model.onnx')
print([input.name for input in model.graph.input])
print([output.name for output in model.graph.output])
```
```
['x']
['y']
```

Be aware that you may not want to feed values for every input -- some of them may really be initializers (constants which you can override if they are also listed as inputs). If you want to exclude initializers from the list:
```python
initializer_names = {initializer.name for initializer in model.graph.initializer}
input_names = [input.name for input in model.graph.input if input.name not in initializer_names]
```

**Comment by Stefan-1313** [comment]
I know this question is closed for a long time but posting this as it may be useful for others.

Netron is a great tool indeed! But if you desire more automation, you can also get the input names from the `session.InputMetadata.Keys` property (and the output names using `session.OutputMetadata.Keys`)

So the full example would look like:
```
// Create inference session.
string modelPath = "C:\Your\Path\File.onnx";
InferenceSession session = new(modelPath); 

// Get the model input and output names.
IEnumerable<string> inputNames = session.InputMetadata.Keys;
IEnumerable<string> outputNames = session.OutputMetadata.Keys;

// In case you have a single input, you can use:
string InputName = inputMeta.First().Key;
```

Good luck!
