### ISSUE TITLE
Ways to verify what execution provider is used

### ISSUE THREAD

**Issue by GuanLuo** [microsoft/onnxruntime#1850]
**Is your feature request related to a problem? Please describe.**
After a model session is loaded, is there way to check the actual graph so that I can tell what is the execution provider that the ops end up using? Currently I can only know the opposite, an op can not use some execution providers, from the fallback log.

**System information**
- ONNX Runtime version (you are using): post rel-0.5.0 (a0ba25f98f210fa506300bb5040695e2b7a636a8)

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
See above

**Comment by jywu-msft** [comment]
yes, we should enhance this area. (contributions welcome!)
The closest thing we have to what you are asking is in the chrometrace profile data output.
When tracing is enabled, it will indicate what EP a node was assigned to. (but this will be on graph post graph rewrite/transformations so the ops may show up as fused ops) 

see: https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/perftest/ort_test_session.cc#L98
and 
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/python/onnxruntime_test_python.py#L388

as examples for enabling.

**Comment by pranavsharma** [comment]
@GuanLuo this [commit](https://github.com/microsoft/onnxruntime/pull/2221) logs the graph placement in verbose logging mode. This is available in the latest 1.0 release. Does this help?

**Comment by GuanLuo** [comment]
@pranavsharma Sorry for the late reply. Our software have tried out the verbose logging mode and the logging for graph placement is really helpful. Thanks.
