### ISSUE TITLE
Add NonZero() to CUDA

### ISSUE THREAD

**Issue by d-colwell** [microsoft/onnxruntime#1857]
**Reason**
Binary masking in Gather operations is not supported in ONNX. 
In a circumstance where you want to get all values matching a criteria (For example, all values greater than zero) then the way to do it is:
`Perform Mask ->
NonZero ->
Gather`

Since NonZero is on the CPU, it involves cuda memory copy and CPU operations every time a binary mask is needed. For larger arrays this is time consuming

**Comment by jinfagang** [comment]
Should this written in cuda or tensorrt plugin?

**Comment by d-colwell** [comment]
afaik the priority order is CPU -> CUDA -> TensorRT. Could be wrong

**Comment by jinfagang** [comment]
I think you mainly want CUDA implementation which is also I want. These operators especially logic operation is not supported in onnx-tensorrt so also not supported on onnx-runtime. (not either CUDA).
But since one can using CUDA, why not directly using TensorRT because it's more faster for well to known reason.

**Comment by faxu** [comment]
@ybrnathan is this in the works already for CUDA?

**Comment by ybrnathan** [comment]
Cuda implementation is in progress.

**Comment by hariharans29** [comment]
Will be resolved by #2056

**Comment by jinfagang** [comment]
Awesome, would it going to add this op also in TensorRT?

**Comment by faxu** [comment]
@jywu-msft - are there plans to add support for this op in tensorRT?

**Comment by hariharans29** [comment]
NonZero op added as a CUDA op via #2056

**Comment by jinfagang** [comment]
@hariharans29  Will there also tensorrt support for that op?
