### ISSUE TITLE
[Build] Onnxruntime cuda execution provider build failure : nvcc error : 'cicc' died due to signal 9 (Kill signal)

### ISSUE THREAD

**Issue by datinje** [microsoft/onnxruntime#18579]
### Describe the issue

when attempting to rebuild onnxruntime 1.16.0 with tensorRt execution provider the config that used to work failed because of https://github.com/microsoft/onnxruntime/issues/18286. 
So I upgraded to onnxruntime 1.16.2 and now I am getting the following issue during build :

CMakeFiles/onnxruntime_providers_cuda_obj.dir/tmp/onnxruntime/onnxruntime/contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim192_fp16_sm80.cu.o
nvcc error   : 'cicc' died due to signal 9 (Kill signal)

I am using cuda 12.2 but issue is same with Cuda 12.3 and  ORT 1.16.3
TRT version = 8.6.1
cudnn = 8.9

note : the server on which I build has an RTX8000 (turing architecture)

### Urgency

yes : need to upgrade my docker image with cuda nsight tools and rebuild onnxruntime 

### Target platform

sles15 SP4

### Build script

RUN CC=gcc-11 CXX=g++-11 ./build.sh --config RelWithDebInfo --use_cuda --cudnn_home /usr/local/cuda/lib64 --cuda_home /usr/local/cuda/ --use_tensorrt --use_tensorrt_builtin_parser --tensorrt_home /usr/local/TensorRT --build_shared_lib --parallel --skip_tests --allow_running_as_root

### Error / output

[ 78%] Building CUDA object CMakeFiles/onnxruntime_providers_cuda_obj.dir/tmp/onnxruntime/onnxruntime/contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim192_fp16_sm80.cu.o
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
gmake[2]: *** [CMakeFiles/onnxruntime_providers_cuda_obj.dir/build.make:5608: CMakeFiles/onnxruntime_providers_cuda_obj.dir/tmp/onnxruntime/onnxruntime/contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim128_fp16_sm80.cu.o] Error 9
gmake[2]: *** Waiting for unfinished jobs....

### GCC / Compiler Version

gcc11

**Comment by jywu-msft** [comment]
i think it's getting killed due to OOM?
See https://github.com/microsoft/onnxruntime/issues/17991#issuecomment-1779652464 for suggestions.
do you have psutil installed? if not, pip install psutil so it can do better estimation of nvcc_threads setting
read comment at https://github.com/microsoft/onnxruntime/blob/2f608338cb46398fc3806cb6d1fd3ba7961b1a9f/tools/ci_build/build.py#L905C3-L905C3

**Comment by datinje** [comment]
I have installed psutil successfully in my build env so now the onnxruntime build shouw estimate properly the nvcc_threads as of https://github.com/microsoft/onnxruntime/blob/2f608338cb46398fc3806cb6d1fd3ba7961b1a9f/tools/ci_build/build.py#L905C3-L905C3 . But it is still failing the same .

nvcc error   : 'cicc' died due to signal 9 (Kill signal)
gmake[2]: *** [CMakeFiles/onnxruntime_providers_cuda_obj.dir/build.make:5623: CMakeFiles/onnxruntime_providers_cuda_obj.dir/tmp/onnxruntime/onnxruntime/contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim160_fp16_sm80.cu.o] Error 9

**Comment by jywu-msft** [comment]
how many nvcc_threads does it calculate? Can you force it to 1?
And how much memory is being allocated to your container?  Can you assign 32GB or more?

**Comment by datinje** [comment]
do you know a way to force nvcc_threads to 1 ? I m just calling the onnxruntime build script :
RUN CC=gcc-11 CXX=g++-11 ./build.sh --config RelWithDebInfo --use_cuda --cudnn_home /usr/local/cuda/lib64 --cuda_home /usr/local/cuda/ --use_tensorrt --use_tensorrt_builtin_parser --tensorrt_home /usr/local/TensorRT --build_shared_lib --parallel --skip_tests --allow_running_as_root

Checking how much memeory used . What I don't understand is why thi si not working anymores used to work for me for a newr a year on the same machine (a VM) without any change in memory.

**Comment by jywu-msft** [comment]
> do you know a way to force nvcc_threads to 1 ? I m just calling the onnxruntime build script : RUN CC=gcc-11 CXX=g++-11 ./build.sh --config RelWithDebInfo --use_cuda --cudnn_home /usr/local/cuda/lib64 --cuda_home /usr/local/cuda/ --use_tensorrt --use_tensorrt_builtin_parser --tensorrt_home /usr/local/TensorRT --build_shared_lib --parallel --skip_tests --allow_running_as_root
> 
> Checking how much memeory used . What I don't understand is why thi si not working anymores used to work for me for a newr a year on the same machine (a VM) without any change in memory.

i don't know what variables changed since last time you tested. new CUDA version?
+@tianleiwu for advice on the matter.

**Comment by jywu-msft** [comment]
> do you know a way to force nvcc_threads to 1 ? I m just calling the onnxruntime build script : RUN CC=gcc-11 CXX=g++-11 ./build.sh --config RelWithDebInfo --use_cuda --cudnn_home /usr/local/cuda/lib64 --cuda_home /usr/local/cuda/ --use_tensorrt --use_tensorrt_builtin_parser --tensorrt_home /usr/local/TensorRT --build_shared_lib --parallel --skip_tests --allow_running_as_root
> 

add --nvcc_threads 1
https://github.com/microsoft/onnxruntime/blob/d2dfbf41795e72911643e2ffcadac069b72580bd/tools/ci_build/build.py#L177

**Comment by datinje** [comment]
same issue with modifying command with --nvcc_threads 1
RUN CC=gcc-11 CXX=g++-11 ./build.sh --config RelWithDebInfo  --nvcc_threads 1 --use_cuda --cudnn_home /usr/local/cuda/lib64 --cuda_home /usr/local/cuda/ --use_tensorrt --use_tensorrt_builtin_parser --tensorrt_home /usr/local/TensorRT --build_shared_lib --parallel --skip_tests --allow_running_as_root

[ 79%] Building CUDA object CMakeFiles/onnxruntime_providers_cuda_obj.dir/tmp/onnxruntime/onnxruntime/contrib_ops/cuda/bert/flash_attention/flash_fwd_split_hdim192_fp16_sm80.cu.o
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
gmake[2]: *** [CMakeFiles/onnxruntime_providers_cuda_obj.dir/build.make:5608: CMakeFiles/onnxruntime_providers_cuda_obj.dir/tmp/onnxruntime/onnxruntime/contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim128_fp16_sm80.cu.o] Error 9
gmake[2]: *** Waiting for unfinished jobs....

but I notice this : cmake is using -j16 flag , maybe this is interfering with nvcc ?
subprocess.CalledProcessError: Command '['/tmp/cmake-3.26.3-linux-x86_64/bin/cmake', '--build', '/tmp/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '-j16']' returned non-zero exit status 2.

So I tried build flag --parallel 1 and still got the same issue

**Comment by datinje** [comment]
not sure flag --parallel 1 did any effect : looks like some // compilation still happen, see 
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
gmake[2]: *** [CMakeFiles/onnxruntime_providers_cuda_obj.dir/build.make:5623: CMakeFiles/onnxruntime_providers_cuda_obj.dir/tmp/onnxruntime/onnxruntime/contrib_op       s/cuda/bert/flash_attention/flash_fwd_hdim160_fp16_sm80.cu.o] Error 9
gmake[2]: *** Waiting for unfinished jobs....
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
gmake[2]: *** [CMakeFiles/onnxruntime_providers_cuda_obj.dir/build.make:5608: CMakeFiles/onnxruntime_providers_cuda_obj.dir/tmp/onnxruntime/onnxruntime/contrib_op       s/cuda/bert/flash_attention/flash_fwd_hdim128_fp16_sm80.cu.o] Error 9

**Comment by datinje** [comment]
@tianleiwu : checked memory of my RTX8000 build VM : it never reach more thna half its max memeory : 15GB vs 32 GB

@jywu-msft : tried flag --cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES=75" . Now build works. 
However I am trying to build a docker image to be used on top on different GPU targets (Nvidia Ampere and Nvidia ADA) . This used to work previously (with ORT 1.16.0 before issue https://github.com/microsoft/onnxruntime/issues/18286). What will this change on my docker image : will I still be able to use my docker image on ampere and ada GPUs with Onnxrutime and TRT EP ? (I will test and if its works will close the case : but you better instruct builders of Onnxrt to set extra flag to match the build server architecture)

**Comment by datinje** [comment]
I can still use the generated application on different Nvidia target (Turing, Ampre and ADA). 
I did not check if I can build on build server with different Nvidia Architecture (Ampere - sm_86 or ADA sm_89)
Anyway closing the case .

**Comment by Greg7000** [comment]
Using https://github.com/triton-inference-server/server/releases/tag/v2.60.0 when trying to activate onnx.

 (At first I wanted to use `build.py -v --enable-gpu --enable-all` but it seems  it does not include onnx so finally I  manually added required flags to get onnx)

I am facing the

```
2025.8 /usr/local/cuda/targets/x86_64-linux/include/vector_types.h:559:104: note: declared here
2025.8   559 | typedef __device_builtin__ struct double4 __VECTOR_TYPE_DEPRECATED__("use double4_16a or double4_32a") double4;
2025.8       |                                                                                                        ^~~~~~~
2027.9 gmake[1]: *** [CMakeFiles/Makefile2:1821: CMakeFiles/onnxruntime_providers_cuda.dir/all] Error 2
2027.9 gmake: *** [Makefile:146: all] Error 2
2028.2 Namespace(build_dir='/workspace/build', config=['Release'], update=True, build=True, clean=False, parallel=0, target=None, compile_no_warning_as_error=True, build_shared_lib=True, build_apple_framework=False, enable_lto=False, use_cache=False, use_binskim_compliant_compile_flags=False, cmake_extra_defines=[["CMAKE_CUDA_ARCHITECTURES='75-real;80-real;86-real;90-real;100-real;120'"], ['CMAKE_POLICY_VERSION_MINIMUM=3.5']], cmake_path='cmake', cmake_generator=None, use_vcpkg=False, use_vcpkg_ms_internal_asset_cache=False, skip_submodule_sync=True, test=False, skip_tests=False, ctest_path='ctest', enable_onnx_tests=False, path_to_protoc_exe=None, fuzz_testing=False, enable_symbolic_shape_infer_tests=False, skip_onnx_tests=False, skip_winml_tests=False, skip_nodejs_tests=False, test_all_timeout='10800', enable_transformers_tool_test=False, build_micro_benchmarks=False, code_coverage=False, enable_training=False, enable_training_apis=False, enable_training_ops=False, enable_nccl=False, nccl_home=None, enable_memory_profile=False, enable_address_sanitizer=False, gen_doc=None, rv64=False, riscv_toolchain_root='', riscv_qemu_path='', android=False, android_abi='arm64-v8a', android_api=27, android_sdk_path='', android_ndk_path='', android_cpp_shared=False, android_run_emulator=False, build_wasm=False, build_wasm_static_lib=False, emsdk_version='4.0.8', enable_wasm_simd=False, enable_wasm_relaxed_simd=False, enable_wasm_threads=False, disable_wasm_exception_catching=False, enable_wasm_api_exception_catching=False, enable_wasm_exception_throwing_override=True, wasm_run_tests_in_browser=False, enable_wasm_profiling=False, enable_wasm_debug_info=False, wasm_malloc=None, emscripten_settings=None, use_full_protobuf=False, use_mimalloc=False, external_graph_transformer_path=None, use_extensions=False, extensions_overridden_path=None, minimal_build=None, include_ops_by_config=None, enable_reduced_operator_type_support=False, disable_contrib_ops=False, disable_ml_ops=False, disable_rtti=False, disable_types=[], disable_exceptions=False, client_package_build=False, enable_pybind=False, build_wheel=False, wheel_name_suffix=None, skip_keras_test=False, build_csharp=False, build_nuget=False, msbuild_extra_options=None, build_java=False, build_nodejs=False, build_objc=False, use_cuda=True, cuda_version=None, cuda_home='/usr/local/cuda', cudnn_home='/usr', enable_cuda_line_info=False, enable_cuda_nhwc_ops=False, disable_cuda_nhwc_ops=False, enable_cuda_minimal_build=False, nvcc_threads=-1, enable_nvtx_profile=False, enable_cuda_profiling=False, use_dnnl=False, dnnl_gpu_runtime='', dnnl_opencl_root='', dnnl_aarch64_runtime='', dnnl_acl_root='', use_openvino='CPU', use_tensorrt=False, use_tensorrt_builtin_parser=True, use_tensorrt_oss_parser=False, tensorrt_home=None, tensorrt_rtx_home=None, use_nv_tensorrt_rtx=False, use_dml=False, dml_path='', dml_external_project=False, use_nnapi=False, nnapi_min_api=None, use_coreml=False, use_qnn=None, qnn_home=None, use_snpe=False, snpe_root=None, use_vitisai=False, use_armnn=False, armnn_relu=False, armnn_bn=False, armnn_home=None, armnn_libs=None, use_acl=False, acl_home=None, acl_libs=None, no_kleidiai=False, use_rknpu=False, use_cann=False, cann_home=None, use_migraphx=False, migraphx_home=None, use_rocm=False, rocm_version=None, rocm_home=None, use_webnn=False, use_jsep=False, use_webgpu=False, use_external_dawn=False, wgsl_template='static', use_xnnpack=False, use_vsinpu=False, use_azure=False, enable_lazy_tensor=False, ms_experimental=False, enable_msinternal=False, use_lock_free_queue=False, enable_generic_interface=False, allow_running_as_root=True, enable_external_custom_op_schemas=False)
2028.2 Failed to import psutil. Please `pip install psutil` for better estimation of nvcc threads. Use nvcc_threads=1
2028.2 Traceback (most recent call last):
2028.2   File "/workspace/onnxruntime/tools/ci_build/build.py", line 2670, in <module>
2028.2     sys.exit(main())
2028.2              ^^^^^^
2028.2   File "/workspace/onnxruntime/tools/ci_build/build.py", line 2571, in main
2028.2     build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
2028.2   File "/workspace/onnxruntime/tools/ci_build/build.py", line 1363, in build_targets
2028.2     run_subprocess(cmd_args, env=env)
2028.2   File "/workspace/onnxruntime/tools/ci_build/build.py", line 148, in run_subprocess
2028.2     return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
2028.2            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2028.2   File "/workspace/onnxruntime/tools/python/util/run.py", line 50, in run
2028.2     completed_process = subprocess.run(
2028.2                         ^^^^^^^^^^^^^^^
2028.2   File "/usr/lib/python3.12/subprocess.py", line 571, in run
2028.2     raise CalledProcessError(retcode, process.args,
2028.2 subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/workspace/build/Release', '--config', 'Release', '--', '-j24']' returned non-zero exit status 2.
------
ERROR: failed to build: failed to solve: executor failed running [/bin/sh -c ./build.sh ${COMMON_BUILD_ARGS} --update --build --use_cuda --cuda_home "/usr/local/cuda" --cudnn_home "/usr" --allow_running_as_root --use_openvino CPU]: exit code: 1
gmake[2]: *** [CMakeFiles/ort_target.dir/build.make:74: onnxruntime/lib/libonnxruntime.so] Error 1
gmake[2]: Leaving directory '/tmp/tritonbuild/onnxruntime/build'
gmake[1]: *** [CMakeFiles/Makefile2:337: CMakeFiles/ort_target.dir/all] Error 2
gmake[1]: Leaving directory '/tmp/tritonbuild/onnxruntime/build'
gmake: *** [Makefile:136: all] Error 2
``` 

I am a bit surprised, I thought the goal of using the docker install was to avoid these kind of issues. In my view a release tag should ensure that `build.py -v --enable-gpu --enable-all` include all and work.

Or at least the most complete build cmd should be provided with the release.
