### ISSUE TITLE
core/providers/tensorrt/tensorrt_provider_factory.h:4:31: fatal error: onnxruntime_c_api.h: No such file or directory  #include "onnxruntime_c_api.h"

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#1858]
afaik, there were only some c_pi documentations but without any standalone C++ example out there indicates user how to written a complete project.

I got this issue when I try written some C++ example:

```
onnx_deploy/cc/test.cc:11:0:

onnxruntime/include/onnxruntime/core/providers/tensorrt/tensorrt_provider_factory.h:4:31: fatal error: onnxruntime_c_api.h: No such file or directory
 #include "onnxruntime_c_api.h"

```

Here is my include style:

```
#include <assert.h>

#include "onnxruntime/core/session/onnxruntime_c_api.h"
#include "onnxruntime/core/providers/tensorrt/tensorrt_provider_factory.h"
#include "onnxruntime/core/providers/cuda/cuda_provider_factory.h"

#include <stdio.h>
#include <stdlib.h>
#include <fstream>
#include <future>
#include <iostream>
#include <map>
#include <thread>
#include <vector>
```

It seems the file I included which comes from onnxruntime can not found that file relatively.

Does there any standard include path for users to correct include C++ APIs? (how to write a CMakeLists to found it)

**Comment by pranavsharma** [comment]
Make sure you specify ```-I<path where onnxruntime_c_api.h is present>``` when compiling and simply have ```#include "onnxruntime_c_api.h"```  in your cc file.

**Comment by jinfagang** [comment]
it works. thanks!
