### ISSUE TITLE
TensorrtExecutionProvider not working 

### ISSUE THREAD

**Issue by HeChengHui** [microsoft/onnxruntime#18597]
### Describe the issue

EP Error /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1193 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libnvinfer.so.8: cannot open shared object file: No such file or directory
 when using ['TensorrtExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.

### To reproduce

I am trying to do [this ](https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#python) in WSL2.

> Name                    Version                   Build  Channel
> onnx                      1.15.0                   pypi_0    pypi
> onnxruntime-gpu           1.16.3                   pypi_0    pypi
> torch                     2.2.0.dev20231102+cu118          pypi_0    pypi
> torchaudio                2.2.0.dev20231102+cu118          pypi_0    pypi
> torchvision               0.17.0.dev20231102+cu118          pypi_0    pypi
> tensorrt                  8.6.1.post1              pypi_0    pypi
> tensorrt-bindings         8.6.1                    pypi_0    pypi
> tensorrt-libs             8.6.1                    pypi_0    pypi
> nvidia-tensorrt           99.0.0                   pypi_0    pypi

---

verify tensorrt
```
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorrt
>>> print(tensorrt.__version__)
8.6.1
>>> assert tensorrt.Builder(tensorrt.Logger())
[11/28/2023-12:35:05] [TRT] [W] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
```
---

Following steps from [this](https://github.com/microsoft/onnxruntime/issues/9986#issuecomment-1043170366)

```
>>> show tensorrt
Name: tensorrt
Version: 8.6.1.post1
Summary: A high performance deep learning inference library
Home-page: https://developer.nvidia.com/tensorrt
Author: NVIDIA Corporation
Author-email: 
License: Proprietary
Location: /home/default/anaconda3/envs/driverstate/lib/python3.10/site-packages
Requires: 
Required-by: nvidia-tensorrt
```
`>>>export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/default/anaconda3/envs/driverstate/lib/python3.10/site-packages/tensorrt/`

### Urgency

As soon as possible. Thank you.

### Platform

Linux

### OS Version

Ubuntu 20.04.6 LTS

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.3

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

TensorRT

**Comment by jywu-msft** [comment]
tensorrt libraries are installed under tensorrt_libs , not tensorrt  
you can confirm by checking the contents of /home/default/anaconda3/envs/driverstate/lib/python3.10/site-packages/tensorrt and /home/default/anaconda3/envs/driverstate/lib/python3.10/site-packages/tensorrt-libs
therefore you need to set LD_LIBRARY_PATH to the latter.

**Comment by HeChengHui** [comment]
@jywu-msft 

i can confirm that tensorrt_libs is in my conda env and the existence of libnvinfer.so.8 file.
![image](https://github.com/microsoft/onnxruntime/assets/84503515/ee4e26f7-b96d-4322-8c00-e533c1e46635)
```
>>>echo $LD_LIBRARY_PATH
:/home/default/anaconda3/envs/driverstate/lib/python3.10/site-packages/tensorrt-libs/
```

However, the same error still persist.



could it be a WSL thing? because the LD_LIBRARY_PATH return empty after i restart my computer.

**Comment by rmccorm4** [comment]
@HeChengHui just an observation - looks like you're using `tensorrt-libs` and not `tensorrt_libs` in your paths above.

**Comment by HeChengHui** [comment]
@rmccorm4 
don't mind me as I erase myself from existence.
