### ISSUE TITLE
CMake Error at CMakeLists.txt:582 (enable_language):   No CMAKE_CUDA_COMPILER could be found.

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#1859]
environment:

- CUDA 10.1
- Ubuntu 16.04
- TensorRT 5.1.5

I pulled the code today and try build, this error got again:

```
-- The CUDA compiler identification is unknown
CMake Error at CMakeLists.txt:582 (enable_language):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.

```

with this command:

```
sudo ./build.sh \
	--use_cuda \
	--cuda_version=10.1 \
	--cuda_home=/usr/local/cuda \
	--cudnn_home=/usr/local/cuda \
	--use_tensorrt --tensorrt_home=$HOME/tensorrt5.1.5 \
	--x86 --update \
	--build_shared_lib --enable_pybind --build_wheel

```
I solved this issue few days ago, today I pulled the newest codes and try build got this error again.

**Comment by snnn** [comment]
Please remove the --x86 arg

**Comment by jinfagang** [comment]
thanks for advice:

```
sudo ./build.sh \
	--use_cuda \
	--cuda_version=10.1 \
	--cuda_home=/usr/local/cuda \
	--cudnn_home=/usr/local/cuda \
	--use_tensorrt --tensorrt_home=$HOME/tensorrt5.1.5 \
	--update \
	--build_shared_lib --enable_pybind --build_wheel

```

I removed it still gets error:

```
-- The CUDA compiler identification is unknown
CMake Error at CMakeLists.txt:582 (enable_language):
  No CMAKE_CUDA_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CUDACXX" or the CMake cache entry CMAKE_CUDA_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!

```

**Comment by snnn** [comment]
Did you delete the build dir before retrying

**Comment by faxu** [comment]
@jinfagang - do you still need assistance with this issue?

**Comment by jinfagang** [comment]
WTH..... I got this issue everytime on a new machine try build onnxruntime...

next time I should log solution here....... otherwise I always forgot it.....

**Comment by jinfagang** [comment]
Just remove `sudo`....

Why it does matter in finding cuda???

**Comment by BraunPhilipp** [comment]
Your environment variables are not the same running sudo.

https://unix.stackexchange.com/questions/8646/why-are-path-variables-different-when-running-via-sudo-and-su

**Comment by snnn** [comment]
Please try to avoid running the build script as root.

**Comment by nietras** [comment]
I am seeing this issue when specifying version `10.2`
```
-- The CUDA compiler identification is unknown
CMake Error at CMakeLists.txt:642 (enable_language):
  No CMAKE_CUDA_COMPILER could be found.
```
I do not know what I am doing wrong? E.g. using following parameters for `build.bat`
```
--use_cuda --cuda_version 10.2 --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2"
```

**Comment by snnn** [comment]
Please reinstall your CUDA SDK and be sure that you have visual_studio_integration_10.2 installed.

**Comment by nietras** [comment]
@snnn thanks! That helped :)
