### ISSUE TITLE
GTest submodule conflicts

### ISSUE THREAD

**Issue by xkszltl** [microsoft/onnxruntime#186]
**Describe the bug**

Custom build gtest 1.8.1 installed under `/usr/local`.
This causes conflicts (undefined symbols) with the gtest submodule.
A better way is to have cmake referencing system gtest first using `find_package`, and fallback to embedded gtest only when it's not found.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master
- Python version: 3.6 (rh-python36)
- GCC/Compiler version (if compiling from source): 7.3.1 (devtoolset-7)
- CUDA/cuDNN version: 10
- GPU model and memory: Volta

**Comment by xkszltl** [comment]
Refer to [https://cmake.org/cmake/help/latest/module/FindGTest.html](https://cmake.org/cmake/help/latest/module/FindGTest.html) for more details.

**Comment by snnn** [comment]
In this special case, I can remember in gtest's document, it suggests you should always build it from source  instead of using a prebuilt binary. Therefore, I wonder if there is a way to set the preference in cmake.

**Comment by xkszltl** [comment]
You may add a cmake option to choose the preference.

The fundamental bug here is:
    ORT took headers and libs from different sources (system installed vs. ort embedded), causing linking error due to the missing functions.

I think if you want to use embedded gtest, you may need to provide `-isystem` so that compiler can pick the proper header.

Refer to `SYSTEM` in [https://cmake.org/cmake/help/latest/command/target_include_directories.html#command:target_include_directories](https://cmake.org/cmake/help/latest/command/target_include_directories.html#command:target_include_directories) for more details.

**Comment by snnn** [comment]
By default, the folder in gcc args ("-Ixxxx") always has higher precedence than /usr/include and /usr/local/include. So, even you installed gtest, it won't interfere.  But it would some chance when find_package is in use, and it added some folder into include path, which is "/usr/include", then things are totally different. If that, we should adjust our CMakeLists.txt, correct the order.

**Comment by xkszltl** [comment]
I do notice the inconsistency of referencing gtest.
For most files it's `"gtest/gtest.h"` but for there're some exceptions like:
https://github.com/Microsoft/onnxruntime/blob/b7cc611563cfd1bafdff14e38fb50ec9c48c3d68/onnxruntime/test/framework/math_test.cc#L19

**Comment by pranavsharma** [comment]
You're welcome to add the cmake option to add the preference. Currently this is not on the top of our priority list.

**Comment by snnn** [comment]
find_package has a drawback that:
If you have a gtest and eigen in /usr/include
When you do find_package(gtest), it will locate it and add /usr/include into the include dirs, which also introduces another eigen. And it's almost impossible to control which eigen should be used, the builtin one or the system one.
