### ISSUE TITLE
Graph resolve function was fail at vgg19 model

### ISSUE THREAD

**Issue by maxwillzq** [microsoft/onnxruntime#1860]
**Describe the bug**
Model is from onnx model zoo: vgg https://github.com/onnx/models/tree/master/vision/classification/vgg
The op set version is 7. 

I want to use onnxruntime c++ api to do shape inference on this model.  I try 2 ways, both fails

method 1: use resolve function
```c++
  string model_path = "./vgg19/model.onnx";  
  std::shared_ptr<onnxruntime::Model> p_model;
  onnxruntime::Model::Load(model_path.c_str(), p_model); 
  auto status = p_model->MainGraph().Resolve();  	
  if(!status.IsOK()) {
    LOG(ERROR) << "Graph resolve failed: " << status.ErrorMessage();
    std::abort();
  }
```

It will give me error message:

```
Graph resolve failed: This is an invalid model. Error in Node: : No Op registered for Relu with domain_version of 9
```

method 2:
I directly to call those functions from onnx lib 
```c++
  onnx::ModelProto proto = p_model->ToProto();
  onnx::shape_inference::InferShapes(proto);
```

It can run through, but no valueInfoProto was generated in modelProto.  Where I can get the generated value info ?

 
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentoOS
- ONNX Runtime installed from (source or binary):  source
- ONNX Runtime version:  0.4
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): gcc 5.4
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by hariharans29** [comment]
Hi,

Can you please try with ORT 0.5.0 ? I don't see why 0.4.0 wouldn't work, but better to try with the latest version.

Based on your info, I downloada the opset 7 version of the model from here (https://github.com/onnx/models/tree/master/vision/classification/vgg/vgg19)-

![image](https://user-images.githubusercontent.com/9969784/65360554-2eaa7f80-dbb5-11e9-8347-219e8d591782.png)

I was able to load the model fine using the Python package -

```
import onnxruntime as rt
model = rt.InferenceSession(r'F:\downloads\vgg19\vgg19\model.onnx')
print ("Model loaded successfully")
```

**Comment by hariharans29** [comment]
Btw - This was on Windows 10. I don't believe ORT is supported on CentOS. For supported Build platforms/environments, you may please take a look here - https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#supported-architectures-and-build-environments

**Comment by maxwillzq** [comment]
Have you try c++ version api?

**Comment by hariharans29** [comment]
I believe the Resolve() method is part of the internal class. They are not part of the public API.

Have you tried using the C++ public APIs to load and score the model ?

You may find samples here - https://github.com/microsoft/onnxruntime/#cc

**Comment by faxu** [comment]
@maxwillzq do you still need assistance with this issue?

**Comment by hariharans29** [comment]
Closing this out. Please reopen in case you need more clarification, the link shared above contains the sample c++ code needed to load a model.

**Comment by maxwillzq** [comment]
> https://github.com/microsoft/onnxruntime/#cc

Could you point which c++ api we can use for shape inference?
