### ISSUE TITLE
Performance log file overriding by same name 

### ISSUE THREAD

**Issue by Jay19751103** [microsoft/onnxruntime#18611]
### Describe the issue

1. The default prefix is onnxruntime_profile_ with time format %Y-%m-%d_%H-%M-%S
I try this to run stable diffusion, it will launch five models, I need to change the diffuser python package to
change the different prefix to avoid performance log overriding.

Here is logging files to change prefix naming of running model with pip installed package python source.
The time format with three logging files are same value 2023-10-16_16-36-46. if prefix keep same.

10/16/2023  04:37 PM         7,112,953 safety_checker_2023-10-16_16-36-45.json
10/16/2023  04:37 PM         8,427,269 text_encoder_2023-10-16_16-36-46.json
10/16/2023  04:37 PM       348,763,699 unet_2023-10-16_16-36-43.json
10/16/2023  04:37 PM           675,370 vae_decoder_2023-10-16_16-36-46.json
10/16/2023  04:37 PM               254 vae_encoder_2023-10-16_16-36-46.json

2. Is it possible change the time measurement from us to ns ?

### To reproduce

Patch following in Olive

diff --git a/examples/directml/stable_diffusion/stable_diffusion.py b/examples/directml/stable_diffusion/stable_diffusion.py
index ea6c2ff0..8a663908 100644
--- a/examples/directml/stable_diffusion/stable_diffusion.py
+++ b/examples/directml/stable_diffusion/stable_diffusion.py
@@ -138,6 +138,7 @@ def run_inference(
     print("Loading models into ORT session...")
     sess_options = ort.SessionOptions()
     sess_options.enable_mem_pattern = False
+    sess_options.enable_profiling = True

then run python stable_diffusion.py --num_images 1

### Platform

Windows

### OS Version

Windows 11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

dfafcb58aa5fb262b4ff964ccdcc3271672032c0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

DirectML

**Comment by edgchen1** [comment]
The ORT API provides a way to set a profile file prefix per session. Perhaps you can file an issue with Olive or diffusers to support profiling better.

> Is it possible change the time measurement from us to ns ?

I assume you are referring to the measurements in the profile file. It might be possible but we'd need a good reason to do so. Others (e.g., existing scripts) are possibly depending on the units being microseconds now.

**Comment by Jay19751103** [comment]
OK
