### ISSUE TITLE
OpenVINO EP ignore GNA device

### ISSUE THREAD

**Issue by comphilip** [microsoft/onnxruntime#18641]
### Describe the issue

set openvino device_id to `GNA` with intel CPU has `GNA` suppported.  onnxruntime reports **Device ID not found**

### To reproduce

on `GNA` supported devices like i9-13900K, with openvino setting

```c++
            OrtOpenVINOProviderOptions opt;
            opt.device_id = "GNA";
            opt.num_of_threads = 1;
            session_option.AppendExecutionProvider_OpenVINO(opt);
```

Run with exception:
```
terminate called after throwing an instance of 'Ort::Exception'
  what():  /build/onnxruntime-src/onnxruntime/core/providers/openvino/openvino_execution_provider.cc:94 onnxruntime::OpenVINOExecutionProvider::OpenVINOExecutionProvider(const onnxruntime::OpenVINOExecutionProviderInfo&) Device ID not found : GNA
Choose one of:
CPU
GNA

```

### Platform

Linux

### OS Version

ubuntu 22.04.3

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

v1.16.3

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU, OpenVINO

### Execution Provider Library Version

openvino_2022.3.1

**Comment by jywu-msft** [comment]
GNA device is not supported by OpenVINO EP.  see list of supported devices: https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html#summary-of-options
+@sfatimar to comment on whether adding GNA support is in the roadmap.

**Comment by ilya-lavrenov** [comment]
OpenVINO has dropped GNA support in 2024.0
Last release supporting GNA is 2023.3

Ticket can be closed as "won't fix"

**Comment by comphilip** [comment]
agreed
