### ISSUE TITLE
[Performance] Incorrect quantization of Gemm layer when weights are in Reshape

### ISSUE THREAD

**Issue by gcunhase** [microsoft/onnxruntime#18668]
### Describe the issue

Gemm quantization doesn't occur as expected when the weights are stored in Reshape layer.

| Expected* | Observed |
| ---------- | ----------- |
| <img src="https://github.com/microsoft/onnxruntime/assets/4861122/5e735205-521b-4949-a0c6-80c325232a08" alt="gemm_reshape_issue_correct" height="250"/> | <img src="https://github.com/microsoft/onnxruntime/assets/4861122/d7b36331-d452-4cbd-9cb2-dfec78cfa5d0" alt="gemm_reshape_issue_incorrect" height="250"/> |

*Another way that the weights could be quantized would be to keep the Reshape layer but add `Q` between Reshape and Gemm: `Reshape->Q->Gemm`.

### To reproduce

1. Download inception-v1-12.onnx model from the [ONNX Model Zoo](https://github.com/onnx/models/blob/main/vision/classification/inception_and_googlenet/inception_v1/model/inception-v1-12.onnx).
2. Quantize model with `onnxruntime.quantization.quantize_static()`:
```python
from onnxruntime.quantization import quantize_static
quantize_static(
    onnx_path,
    output_onnx_path,
    random_calibration_data_reader,
    per_channel=True,
    extra_options={"QuantizeBias": False}
)
```

### Platform

Linux

### OS Version

18.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

11.4

### Model File

https://github.com/onnx/models/blob/main/vision/classification/inception_and_googlenet/inception_v1/model/inception-v1-12.onnx

### Is this a quantized model?

No

**Comment by yufenglee** [comment]
You need to run the pre-process to const-folding the Reshape: https://onnxruntime.ai/docs/performance/model-optimizations/quantization.html#pre-processing. Or the quantization tool won't quantize Reshape node.
