### ISSUE TITLE
There is probably a misprint in '1.4142099618911743f' constant. Consider using the M_SQRT2 constant from <math.h>. gelu_fusion.cc 67

### ISSUE THREAD

**Issue by mqsoft** [microsoft/onnxruntime#18680]
### Describe the issue

Please check onnx-runtime\core\optimizer\gelu_fusion.cc:67

float approximated_sqrt_two = 1.4142099618911743f;

### To reproduce

PVS Studio warning

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

latest HEAD

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by tianleiwu** [comment]
It is fine for graph fusion. 
Some BERT model use approximate value for sqrt 2, and the graph fusion need to check whether it is approximated value of sqrt(2).
A better way might be just use a threshold to compare the difference between M_SQRT2 and the value.
