### ISSUE TITLE
[Regression] Exception during initialization: trigger_point_it != node_to_trigger_points.end() was false

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnxruntime#18693]
`[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/framework/allocation_planner.cc:1956 onnxruntime::common::Status onnxruntime::PlannerImpl::BuildExecutionPlan(const onnxruntime::ExecutionProviders&, const onnxruntime::IStreamCommandHandleRegistry&) trigger_point_it != node_to_trigger_points.end() was false.`

This was newly discovered in the [benchmark ](https://github.com/microsoft/onnx-converters-private/issues/166)(12/4) that affected 50+ models. It has been validated that the bug starts from `ort-nightly-1.17.0.dev20231130007` and not present in  `ort-nightly-1.17.0.dev20231129002`.

Example model to repro: [mobilenet_v2](https://artprodcus3.artifacts.visualstudio.com/Afe2ea789-dbe5-406d-9a7a-9f167e7a04c0/5bcb244e-27fa-4c54-a682-fcc18d36922d/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL29ubnhjb252ZXJ0ZXIvcHJvamVjdElkLzViY2IyNDRlLTI3ZmEtNGM1NC1hNjgyLWZjYzE4ZDM2OTIyZC9idWlsZElkLzM5NS9hcnRpZmFjdE5hbWUvb25ueF9tb2RlbHNfZHluYW1vLW9ubnhfdG9yY2hiZW5jaA2/content?format=zip&subPath=%2Fmobilenet_v2)

**Comment by yuslepukhin** [comment]
The error is introduced by https://github.com/microsoft/onnxruntime/pull/18410

Cc: @er3x3
