### ISSUE TITLE
segmentation fault when Tile's repeat contains 0

### ISSUE THREAD

**Issue by lucienwang1009** [Microsoft/onnxruntime#187]
**Describe the bug**
When the input `repeats` of op `Tile` contains 0, onnxruntime will throws segmentation fault.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 0.1.3
- Python version: 3.6
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: None
- GPU model and memory: None

**To Reproduce**
Describe steps/code to reproduce the behavior:

[test.zip](https://github.com/Microsoft/onnxruntime/files/2684879/test.zip)

m = onnxruntime.InferenceSession('./test.pb')
x = np.array([0,1,2,3], np.float32)
y = np.array([0], np.int64)
m.run('z', inputs)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pengwa** [comment]
any update on this? I got segement fault as well, having 0 in the repeats list, in a real model.

**Comment by ashku-ms** [comment]
A fix was checked in

**Comment by lucienwang1009** [comment]
Thank @ashku-ms
