### ISSUE TITLE
[Performance] Failed to get higher CPU utilization than 1200%

### ISSUE THREAD

**Issue by ColainCYY** [microsoft/onnxruntime#18726]
### Describe the issue

I have initialized an OrtSession object by the java api，and the intraOp threadpool and the interOp theadpool are disabled by
```
opts.setInterOpNumThreads(1);
opts.setIntraOpNumThreads(1);
```
In this way, the OrtSession should run in a **Single Thread Mode**.

Besides, I have a global threadpool with **N** threads. Each thread in the pool would conduct inference through **OrtSession.run()**. In theory, these threads are independently of each other. So, no conflicts come out.

With N increased from 1 to 10, the cup utilization grow synchronously from 100% to 960%. But when the number of threads continues to increase, the CPU utilization can only reach **a maximum of 1200%**. As a result, the speed of single-threaded computation decreases significantly.

I'm rather confused. Only when the CPU utilization increases with the number of threads can stable single-threaded performance be guaranteed.

So, how could I achieve the goal?

### To reproduce

My initialization:

```
    public void init_onnx(String model_file) {
        env = OrtEnvironment.getEnvironment();
        opts = new OrtSession.SessionOptions();
        try {
            opts.setOptimizationLevel(OrtSession.SessionOptions.OptLevel.ALL_OPT);
            opts.setExecutionMode(OrtSession.SessionOptions.ExecutionMode.SEQUENTIAL);
            opts.setInterOpNumThreads(1);
            opts.setIntraOpNumThreads(1);
        } catch (OrtException e) {
            logger.error("Error in new SessionOptions(). ", e);
        }
}
```

My single thread function:

```
 public double inference_pt_onnx(int[][] token_ids) {
        try {
            OnnxTensor input_x = OnnxTensor.createTensor(env, token_ids);
            Map<String, OnnxTensor> paras = new HashMap<>();
            paras.put("input_ids", input_x);
            OrtSession.Result outs = session.run(paras);
            float[][] logit = (float[][]) outs.get("probs").get().getValue();
            input_x.close();
            outs.close();
            paras.clear();
            return logit[0][1];
        } catch (OrtException e) {
            e.printStackTrace();
            return 0.0;
        }
    }
```

My thread pool:

```
        ExecutorService executor = Executors.newFixedThreadPool(thread_num);

        for (int i = 0; i < thread_num; ++i) {
            int[][] ids = tokens[i];
            executor.submit(
                () -> {
                    for (int c = 0; c < 100000; ++c) {
                        double res = inference_pt_onnx(ids);
                    }
                }
            );
        }

        executor.shutdown();

```

### Platform

Linux

### OS Version

Ubuntu

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

Java

### Architecture

X64

### Execution Provider

Default CPU

### Is this a quantized model?

No

**Comment by Craigacp** [comment]
How many threads/cores are available on your machine? Is your machine NUMA?

**Comment by ColainCYY** [comment]
> How many threads/cores are available on your machine? Is your machine NUMA?
Yes，there are two NUMA nodes：
```
NUMA node0 CPU(s):   0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46
NUMA node1 CPU(s):   1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47
```
I have replaced onnx-runtime with tensorflow-native-api，which could get higher CPU utilization, about 100% * thread_num.

**Comment by Craigacp** [comment]
TensorFlow-Java isn't too great at controlling the thread placement either, but I'm glad it's working for you (I help run TF-Java).

It's worth pointing out that using Java multidimensional arrays is the slow way of using ONNX Runtime, as it involves a bunch of copying and pointer chasing to get data in and out of the native code. That's unlikely to be the cause of all of the issue, but it won't help. If you have fixed size inputs and outputs then you can preallocate those tensors which should remove a lot of the allocations from the loop.

**Comment by ColainCYY** [comment]
> TensorFlow-Java isn't too great at controlling the thread placement either, but I'm glad it's working for you (I help run TF-Java).
> 
> It's worth pointing out that using Java multidimensional arrays is the slow way of using ONNX Runtime, as it involves a bunch of copying and pointer chasing to get data in and out of the native code. That's unlikely to be the cause of all of the issue, but it won't help. If you have fixed size inputs and outputs then you can preallocate those tensors which should remove a lot of the allocations from the loop.

Thanks for your relpy! I have tried to allocate a fixed OnnxTensor as input, and run all threads on it. But it just made no difference. So. I guess, maybe the limited CPU utilizaion is not a result of java-api.
