### ISSUE TITLE
`memory_info` is not clearly defined in the document

### ISSUE THREAD

**Issue by oneengineer** [microsoft/onnxruntime#18739]
`memory_info` is not clearly defined in the document
Should I declare it a CPU memory info or a device one?

---
#### Document Details
* Title: I/O Binding
* Page: [https://onnxruntime.ai/docs/performance/tune-performance/iobinding.html](https://onnxruntime.ai/docs/performance/tune-performance/iobinding.html)
* Page Source: iobinding.md

**Comment by pranavsharma** [comment]
If you want to bind to a CPU device, you use CPU mem info. If you want to bind to a GPU device, you use CUDA mem info.
