### ISSUE TITLE
"MKL-DNN is supported in this build"?

### ISSUE THREAD

**Issue by xkszltl** [Microsoft/onnxruntime#188]
**Describe the bug**

Just curious, is this a typo?
Looks like it's "not supported" instead of "supported".

https://github.com/Microsoft/onnxruntime/blob/11b369a8641d9dc8989739f3c530a8cf330d7f8b/onnxruntime/test/onnx/main.cc#L230

Similarly for other arch.

**Comment by snnn** [comment]
Will fix it. Thanks.
