### ISSUE TITLE
[Web] WebGPU batch inference only the first set of data is correct

### ISSUE THREAD

**Issue by sunpeng222** [microsoft/onnxruntime#18804]
### Describe the issue

I encountered a problem when using WebGPU.  When I use batch inference, the results of the second set of data are completely incorrect.  The model is not the problem, as my inference using wasm was completely fine.What is the cause of this?My model loading and inference are all placed in the webworker

### To reproduce

```
importScripts("./ort/ort.webgpu.min.js")
let session
init()
async function init() {
    ort.env.wasm.simd = true;
    ort.env.wasm.wasmPaths = "./ort/"
    session = await ort.InferenceSession.create('./end2end_normalized_N.onnx', {
        executionProviders: [{
            name: "webgpu"
        }],
        logSeverityLevel: 3,
        logVerbosityLevel: 3,
    });
    self.postMessage({
        type: "ready",
        data: null
    })
}
self.addEventListener('message', async e => {
    if (e.data.type === "upload") {
        if (!session) {
            self.postMessage({
                type: "noSession",
                data: null
            })
            return
        }
        const tensorA = new ort.Tensor('float32', e.data.data, [2, 224, 224, 3]);
        const feeds = { input_1: tensorA };
        const start = performance.now();
        const results = await session.run(feeds);
        const end = performance.now();

        self.postMessage({
            type: "end",
            data: {
                time: end - start,
                results: results
            }
        })
    }
});
```

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.3

### Execution Provider

'webgpu' (WebGPU)

**Comment by gyagp** [comment]
Can you give a try on dev release ("https://cdn.jsdelivr.net/npm/onnxruntime-web@dev/dist/ort.webgpu.min.js")?
If the issue still persists, can you share the model?

**Comment by sunpeng222** [comment]
> Can you give a try on dev release ("https://cdn.jsdelivr.net/npm/onnxruntime-web@dev/dist/ort.webgpu.min.js")? If the issue still persists, can you share the model?

Thank you, the development version has no problem.

**Comment by MountainAndMorning** [comment]
Is there any timeline for version 1.17.0?
