### ISSUE TITLE
INT16 input parameter for QuantizeLinear is invalid

### ISSUE THREAD

**Issue by suyash-narain** [microsoft/onnxruntime#18811]
### Describe the issue

I converted lstm.tflite model available on https://chromium.googlesource.com/chromiumos/platform2/+/main/ml_benchmark/model_zoo/README.md#audio-models
to lstm.onnx model using tf2onnx v1.15. The model got converted easily without issues.
But when i ran inference using onnxrutime, i get the below error:

>   File "/usr/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 452, in _create_inference_session
>     sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
> onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from lstm.onnx failed:This is an invalid model. Type Error: Type 'tensor(int16)' of input parameter (zero_point__438) of operator (QuantizeLinear) in node (fetch_audio_state__core_lstm_rnn_4_c__00_quantize) is invalid.

i was going through the PR https://github.com/microsoft/onnxruntime/pull/17015 and it states that these ops have 16bit support. so why am i getting the invalid model error?
If the model was invalid, tf2onnx should also not have worked right? 

### To reproduce

[lstm.zip](https://github.com/microsoft/onnxruntime/files/13665689/lstm.zip)
the onnx file is attached as a zip file.
Running inference on this model using onnxruntime InferenceSession leads to failure since apparently the model has invalid ops? 
is there a way this model can be executed? the tflite version works well

### Platform

Linux

### OS Version

22.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.16.3

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

Default CPU

```[tasklist]
### Tasks
```

**Comment by adrianlizarraga** [comment]
Hi @suyash-narain

The latest released version of ONNX does **not yet** support 16-bit integer quantization. The onnxruntime PR you referenced (https://github.com/microsoft/onnxruntime/pull/17015) added this support only to QuantizeLinear/DequantizeLinear operators that use the `com.microsoft` domain, which is a domain specifically implemented by onnxruntime.

However, this support was recently merged into ONNX's main branch (https://github.com/onnx/onnx/pull/5737) and should be available in the next official ONNX release.
