### ISSUE TITLE
[Feature Request] Support CUDA 12 ?

### ISSUE THREAD

**Issue by Bagashidayat1** [microsoft/onnxruntime#18850]
### Describe the feature request

Is ONNXRUNTIME support CUDA 12 ?

### Describe scenario use case

i got error on google colab using onnxruntime but it  doesnt want to use T4 GPU

**Comment by karayakar** [comment]
I believe it is not supporting CUDA 12, I have tried 12.2 and getting below error.

'[ErrorCode:RuntimeException] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load

**Comment by henryruhs** [comment]
```
2023-12-19 07:23:15.717360679 [E:onnxruntime:Default, provider_bridge_ort.cc:1498 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1195 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory
```
Using the nightly builds via

```
pip install ort-nightly-gpu==1.17.0.dev20231215001 --pre --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple
```

**Comment by Bagashidayat1** [comment]
> Does anyone know how many days need to support CUDA12?

no idea

**Comment by phineas-pta** [comment]
current version 1.16.x support cuda 12, but must build it from source

**Comment by m1337v** [comment]
> ```
> Using the nightly builds via
> pip install ort-nightly-gpu==1.17.0.dev20231215001 --pre --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple
> ```

In my case it didn't help to use the latest nightly (...002). It's still looking for cuda11/libcublasLt.so.11 while cuda12 has libcublasLt.so.12.
I'm already trying to build from source for 2 days but with Google Collab limitations that seems like an impossible endeavor.

`[E:onnxruntime:Default, provider_bridge_ort.cc:1498 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1195 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory`

**Comment by phineas-pta** [comment]
here my instructions to build onnxruntime with cuda 12 on colab
```
!apt-get install tensorrt-dev
!git clone \
    --branch=rel-1.16.3 \
    --single-branch \
    --depth=1 \
    --recurse-submodules \
    --shallow-submodules \
    https://github.com/microsoft/onnxruntime
%cd onnxruntime
!python tools/ci_build/build.py \
    --build_dir=build \
    --build \
    --update \
    --parallel \
    --skip_tests \
    --build_wheel \
    --enable_pybind \
    --config=Release \
    --skip_submodule_sync \
    --allow_running_as_root \
    --compile_no_warning_as_error \
    --use_cuda \
    --use_tensorrt \
    --cuda_home=/usr/local/cuda \
    --cudnn_home=/usr/lib/x86_64-linux-gnu \
    --tensorrt_home=/usr/lib/x86_64-linux-gnu \
    --cmake_extra_defines='CMAKE_CUDA_ARCHITECTURES=70' \
    --numpy_version="$(python -c 'import numpy; print(numpy.__version__)')"
```
take ~2h, **no need gpu session** (remove tensorrt if not needed)

wheel file created: `onnxruntime/build/Release/dist/onnxruntime_gpu-1.16.3-cp310-cp310-linux_x86_64.whl` save it elsewhere to use in gpu session

**Comment by phineas-pta** [comment]
easier solution but temporary: https://github.com/googlecolab/colabtools/issues/4214#issuecomment-1859155789

**Comment by phineas-pta** [comment]
here my instructions to build onnxruntime with cuda 12 on colab
```
!apt-get install tensorrt-dev
!git clone \
    --branch=rel-1.16.3 \
    --single-branch \
    --depth=1 \
    --recurse-submodules \
    --shallow-submodules \
    https://github.com/microsoft/onnxruntime
%cd onnxruntime
!python tools/ci_build/build.py \
    --build_dir=build \
    --build \
    --update \
    --parallel \
    --skip_tests \
    --build_wheel \
    --enable_pybind \
    --config=Release \
    --skip_submodule_sync \
    --allow_running_as_root \
    --compile_no_warning_as_error \
    --use_cuda \
    --use_tensorrt \
    --cuda_home=/usr/local/cuda \
    --cudnn_home=/usr/lib/x86_64-linux-gnu \
    --tensorrt_home=/usr/lib/x86_64-linux-gnu \
    --cmake_extra_defines='CMAKE_CUDA_ARCHITECTURES=70' \
    --numpy_version="$(python -c 'import numpy; print(numpy.__version__)')"
```
take ~2h, **no need gpu session** (remove tensorrt if not needed)

wheel file created: `onnxruntime/build/Release/dist/onnxruntime_gpu-1.16.3-cp310-cp310-linux_x86_64.whl` save it elsewhere to use in gpu session

*easier solution but only temporary*: https://github.com/googlecolab/colabtools/issues/4214#issuecomment-1859155789

**Comment by RoM4iK** [comment]
For people who will come after me, you can download whl here
https://dev.azure.com/onnxruntime/onnxruntime/_artifacts/feed/onnxruntime-cuda-12/PyPI/onnxruntime-gpu/overview/1.17.0

**Comment by henryruhs** [comment]
Nice to see you Oleksandr.

What is the actual difference between both packages? I assume the one on azure is from the onnxruntime team and based on the latest build. The other by one of the onnxruntime devs and locked to a version?

**Comment by henryruhs** [comment]
Kinda offtopic, but is it possible that Microsoft blocked Google Colab from downloading the nightlies?

**Comment by jindameias** [comment]
Thank you so much for addressing and fixing the existing defects in onnxruntime-gpu. Your efforts are truly appreciated!

**Comment by AndreyOrb** [comment]
So the nightly onnxruntime-gpu (v 1.17) should work?
@netrunner-exe Oleksandr, what CUDA and cuDNN versions (12.? and 8.9.6?) did you manage to compile with?

**Comment by henryruhs** [comment]
@netrunner-exe I can report have issues with [`occluder.onnx`](https://github.com/facefusion/facefusion-assets/releases/download/models/face_occluder.onnx) on google colab using `ort-nightly-gpu==1.17.0.dev20231205004`.

**Comment by AndreyOrb** [comment]
@netrunner-exe Thanks for sharing the details.
Windows version has compiled and worked with my ONNX graphs with this command:
.\build.bat --config Release --build_shared_lib --parallel --use_cuda --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2" --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\cuDNN\cudnn-windows-x86_64-8.9.6.50_cuda12-archive" --cuda_version 12.2 --skip_tests --use_mimalloc --use_tensorrt --tensorrt_home "C:\Program Files\NVIDIA GPU Computing Toolkit\TensorRT\TensorRT-8.6.1.6.Windows10.x86_64.cuda-12.0\TensorRT-8.
6.1.6" --use_tensorrt_oss_parser

**Comment by jchen351** [comment]
The CUDA 12 support will be official in upcoming Onnxrtime 1.17 realase, in a week. Official instruction on how to download it will be provided then.

**Comment by chay688** [comment]
> > 对于关注我的人，您可以在这里下载 whl https://dev.azure.com/onnxruntime/onnxruntime/_artifacts/feed/onnxruntime-cuda-12/PyPI/onnxruntime-gpu/overview/1.17.0
> 
> 谢谢你！或者，您可以通过 pip 安装该软件包： `pip install onnxruntime-gpu==1.17.0 --index-url=https://pkgs.dev.azure.com/onnxruntime/onnxruntime/_packaging/onnxruntime-cuda-12/pypi/simple`
> 
> 之前，我使用了一个稍微不同的包，也许有人会发现它也很有用： `pip install ort-nightly-gpu==1.17.0.dev20231205004 --index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ort-cuda-12-nightly/pypi/simple/`

`INFO: pip is looking at multiple versions of onnxruntime-gpu to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement coloredlogs (from onnxruntime-gpu) (from versions: none)
ERROR: No matching distribution found for coloredlogs`

**Comment by barshag** [comment]
Any updates? (Looking for support 12.3 on local machine(ubuntu))

**Comment by arcosx** [comment]
solution from https://onnxruntime.ai/docs/install/

```
pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
```
