### ISSUE TITLE
[Web] Added fused-conv related test case

### ISSUE THREAD

**Issue by axinging** [microsoft/onnxruntime#18855]
### Describe the issue

When run 'npm test -- suite1 -b=webgpu --debug  --wasm-number-threads 1 --log-verbose --debug', the attributes activation is alwas empty of null.  The only case attributes activation is not empty is fused-conv.jsonc, however, this case is not included in npm test -- suite1.
In ort.test.js, fused-conv.jsonc doesn't include any test items:
```
{ name: "fused-conv.jsonc", tests: [] }, { name: "gather-elements.jsonc", tests: [{ name: "GatherElements float32 data + int32 indices-1", operator: "GatherElements", attributes: [{ name: "axis", data: 1, type: "int" }], cases: [{ name: "float32 data + int32 indices-1", inputs: [{ data: [1, 2, 3, 4], dims: [2, 2], type: "float32" }, { data: [0, 0, 1, 0], dims: [2, 2], type: "int32" }], outputs: [{ data: [1, 1, 4, 3], dims: [2, 2], type: "float32" }] }],
```

### To reproduce

Run, check attributes activation: 
```
npm test -- suite1 -b=webgpu --debug  --wasm-number-threads 1 --log-verbose --debug
```

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

ad476d5a1fb63a4cad74899873ccbf61e9487a23

### Execution Provider

'webgpu' (WebGPU)

**Comment by axinging** [comment]
I will look into this.

**Comment by fs-eire** [comment]
@github-actions this issue is still active.

**Comment by fs-eire** [comment]
#19581 is merged and this issue should be resolved.
