### ISSUE TITLE
[Training] incorrect input for ReluGrad layer

### ISSUE THREAD

**Issue by sunejas** [microsoft/onnxruntime#18873]
### Describe the issue

Hi, I have a simple linear model with 3 fc layers and 3 relu layers - ![original onnx](https://github.com/microsoft/onnxruntime/assets/15884722/1f2836b7-40f9-4a8a-922d-85e3c2c4ef5c)

and the corresponding training model is generated by onnxruntime  - ![training_model onnx](https://github.com/microsoft/onnxruntime/assets/15884722/ad578fb4-ade9-498f-a46d-a338960dde14)

As highlighted in the red circle,  instead of output of the last Relu layer, the output of last Gemm layer is going to the ReluGrad.

Although, the behavior of the other two intermediate relu/grad layers seems ok, i.e. the Relu Outputs become inputs of ReluGrad, 
But the last layer looks buggy.

Please advise how to fix this.

### To reproduce

Code for generating training artifacts:

```
model = onnx.load("orig.onnx")
artifacts.generate_artifacts(model,
                             requires_grad = ["fc1.weight","fc2.weight","fc3.weight"],
                             loss = artifacts.LossType.CrossEntropyLoss,
                             optimizer = artifacts.OptimType.AdamW,
                             artifact_directory = "./")
```

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.15.1

### PyTorch Version

2.0.1+cu117

### Execution Provider

Default CPU

**Comment by baijumeswani** [comment]
Upon looking at our [function definition for ReluGrad](https://github.com/microsoft/onnxruntime/blob/c5f3952b68872ac80d8b9a45a57d46262a455ffd/orttraining/orttraining/core/graph/gradient_builder.cc#L828-L833), the generated ONNX graph looks correct.

To give more context, it does not matter whether the input to the ReluGrad operator is the output of the Relu operator or the input to it. To illustrate this:

x is input to Relu and y is the output of Relu

y = Relu(x)
y = 0 when (x <= 0)
y = x when (x > 0)
dy/dx =  0 when (x <= 0)
dy/dx = 1 when (x > 0)
Alternatively,
dy/dx = 0 when (y <= 0)
dy/dx = 1 when (y > 0)

So whether the input to ReluGrad is x or y does not matter. Hope this helped. Closing this as it is working as designed. Please reopen if you have any further questions.
