### ISSUE TITLE
[Performance] Concat should be a no-op for less than 2 tensor inputs

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [microsoft/onnxruntime#18918]
### Describe the issue

If `Concat` operator is only supplied with a single input, the output will always be the same as the input, but currently it is doing an unnecessary copy which may be very expensive for larger tensors.

![image](https://github.com/microsoft/onnxruntime/assets/860874/b8e8fb82-857e-4c20-b96e-262856311992)

### To reproduce

N/A

### Platform

Other / Unknown

### OS Version

N/A

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.3

### ONNX Runtime API

Other / Unknown

### Architecture

Other / Unknown

### Execution Provider

Other / Unknown

### Is this a quantized model?

Unknown

**Comment by xadupre** [comment]
This will be fixed in sklearn-onnx.
