### ISSUE TITLE
cuda 12.2 support

### ISSUE THREAD

**Issue by akac97** [microsoft/onnxruntime#18916]
### Describe the feature request

Google colab updated thier cuda from 12 to 12.2

### Describe scenario use case

Google colab updated thier cuda from 12 to 12.2

**Comment by tianleiwu** [comment]
You may try ort-nightly-gpu like the following:
```
python -m pip install coloredlogs flatbuffers numpy packaging protobuf sympy
python -m pip install ort-nightly-gpu --index-url=https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ort-cuda-12-nightly/pypi/simple/
```

**Comment by akac97** [comment]
Thanks it workd

**Comment by RoM4iK** [comment]
For people who will come after me, you can download whl here
https://dev.azure.com/onnxruntime/onnxruntime/_artifacts/feed/onnxruntime-cuda-12/PyPI/onnxruntime-gpu/overview/1.17.0
