### ISSUE TITLE
Expo prebuild issues

### ISSUE THREAD

**Issue by Cosmorider** [microsoft/onnxruntime#18935]
### Describe the issue

When I run:
`npx expo prebuild`

I get the following output (asterisks are sensitive info), note that there is more, but the source lies in app.plugin.js:
`✔ Created native projects | /android, /ios already created | gitignore skipped
✔ Updated package.json and added index.js entry point for iOS and Android
› Installing using npm
> npm install
✖ Config sync failed
Error: [ios.dangerous]: withIosDangerousBaseMod: ENOENT: no such file or directory, open '/home/***/***/ios/PodFile'
Error: [ios.dangerous]: withIosDangerousBaseMod: ENOENT: no such file or directory, open '/home/***/***/ios/PodFile'
    at Object.openSync (node:fs:593:3)
    at Object.readFileSync (node:fs:461:35)
    at /home/***/***/node_modules/onnxruntime-react-native/app.plugin.js:33:27`

I went into the file, and I changed line 32 so that it was "Podfile" instead of "PodFile":
`const podFilePath = path.join(config.modRequest.platformProjectRoot, 'Podfile');`

Then the command worked. Just letting you guys know.

### To reproduce

Install onnxruntime-react-native in an expo project. Then use npx expo prebuild.

### Urgency

This causes issues since every one of my team members needs to deal with this issue and I assume a lot of other people will as well. It's not terribly urgent, but an annoying hassle.

### Platform

Linux

### OS Version

Ubuntu 22.04.3 LTS

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.16.3

### ONNX Runtime API

JavaScript

### Architecture

X86

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
Thanks for the info. Should be fixed in the next release by #18861
