### ISSUE TITLE
Can't install on Jetson with Jetpack 5.1.2

### ISSUE THREAD

**Issue by aurelien-m** [microsoft/onnxruntime#18951]
### Describe the issue

I downloaded the latest version of onnxruntime from Jetson Zoo but I'm getting this when installing:

```
ERROR: onnxruntime_gpu-1.16.0-cp38-cp38m-linux_aarch64.whl is not a supported wheel on this platform.
```

I tried both 1.15.1 and 1.16.0. Here's the Jetson information:

```
$ sudo apt-cache show nvidia-jetpack
Package: nvidia-jetpack
Version: 5.1.2-b104
Architecture: arm64
Maintainer: NVIDIA Corporation
Installed-Size: 194
Depends: nvidia-jetpack-runtime (= 5.1.2-b104), nvidia-jetpack-dev (= 5.1.2-b104)
Homepage: http://developer.nvidia.com/jetson
Priority: standard
Section: metapackages
Filename: pool/main/n/nvidia-jetpack/nvidia-jetpack_5.1.2-b104_arm64.deb
Size: 29304
SHA256: fda2eed24747319ccd9fee9a8548c0e5dd52812363877ebe90e223b5a6e7e827
SHA1: 78c7d9e02490f96f8fbd5a091c8bef280b03ae84
MD5sum: 6be522b5542ab2af5dcf62837b34a5f0
Description: NVIDIA Jetpack Meta Package
Description-md5: ad1462289bdbc54909ae109d1d32c0a8
```

### To reproduce

```
$ wget https://nvidia.box.com/shared/static/iizg3ggrtdkqawkmebbfixo7sce6j365.whl -O onnxruntime_gpu-1.16.0-cp38-cp38m-linux_aarch64.whl
$ pip install onnxruntime_gpu-1.16.0-cp38-cp38m-linux_aarch64.whl 
ERROR: onnxruntime_gpu-1.16.0-cp38-cp38m-linux_aarch64.whl is not a supported wheel on this platform.
```

### Platform

Other / Unknown

### OS Version

Jetson Jetpack 5.1.2

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.0

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

CUDA, TensorRT

**Comment by jywu-msft** [comment]
which pip version are you using? 
pip --version

**Comment by aurelien-m** [comment]
```
$ pip --version
pip 20.0.2 from .../py38-venv/lib/python3.8/site-packages/pip (python 3.8)
```

Strangely enough, it actually works with Python 3.10 (the installation went fine)!

```
(py310-venv) ... $ pip --version
pip 23.0.1 from .../py310-venv/lib/python3.10/site-packages/pip (python 3.10)
(py310-venv) ... $ python
Python 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime
>>> 
```

By the way, I also tried updating pip for Python 3.8:

```
(py38-venv) ... $ pip install pip -U
Collecting pip
  Using cached pip-23.3.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-23.3.2
(py38-venv) ... $ pip install wheels/onnxruntime_gpu-1.16.0-cp38-cp38m-linux_aarch64.whl 
ERROR: onnxruntime_gpu-1.16.0-cp38-cp38m-linux_aarch64.whl is not a supported wheel on this platform.
```

**Comment by aurelien-m** [comment]
I guess I'll stick with Python 3.10 for now

**Comment by jywu-msft** [comment]
> I guess I'll stick with Python 3.10 for now

I think likely there's something wrong with the python 3.8 package. +@yf711 to investigate.
I suspect it's related to the m abi flag being removed for python 3.8 
https://docs.python.org/3/whatsnew/3.8.html#build-and-c-api-changes
but yet our package still has cp38m

**Comment by aurelien-m** [comment]
So I found my issue, it's just in the name of the file. I have to rename it `onnxruntime_gpu-1.16.0-cp38-cp38-linux_aarch64.whl` and **not** `onnxruntime_gpu-1.16.0-cp38-cp38m-linux_aarch64.whl`. Notice the extra `m`. I followed the installation procedure [here](https://elinux.org/Jetson_Zoo), so it could be nice to change that :) Thanks anyways
