### ISSUE TITLE
LayerNormalization without bias throws segfault

### ISSUE THREAD

**Issue by ex3ndr** [microsoft/onnxruntime#18967]
### Describe the issue

LayerNormalization without bias throws segfault after exporting from PyTorch, all tools report correct graphs and it looks like the bug is in runtime

### To reproduce

```
import torch
from torch import nn
class ONNXBug(nn.Module):
    def __init__(self):
        super().__init__()
        self.ln = nn.LayerNorm(10, bias=False)
    def forward(self, x):
        return self.ln(x)
model = ONNXBug()
dummy = torch.zeros(10).unsqueeze(0)
torch.onnx.export(model, dummy, "test.onnx", export_params=True, input_names = ['input'], output_names = ['output'])
import onnxruntime as rt
sess = rt.InferenceSession("./test.onnx")
```

### Platform

Mac

### OS Version

14.2.1

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

I have tried most recent versions starting from 1.15

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU, CUDA, TensorRT

### Execution Provider Library Version

12.1

**Comment by wschin** [comment]
This should have fixed in latest main commit. I run you script and hit no error. Please install nightly from https://onnxruntime.ai/docs/install/. Please feel free to re-open if the error still exists.
