### ISSUE TITLE
[Documentation] Please describe which version onnx supported of each release

### ISSUE THREAD

**Issue by evolcano** [microsoft/onnxruntime#18968]
### Describe the documentation issue

The version of onnx supported is importent for ML.NET to install correct CUDA tools and cuDNN.

I cann't find the onnx version supported in the last release of 1.16.0 - 1.16.3. 

After many times try,  cuda_11.6.2 & cnDNN 8.9.6 can works ,so I guess the current onnx version may be onnx 1.3-1.14.

### Page / URL

https://github.com/microsoft/onnxruntime/releases

**Comment by thiagocrepaldi** [comment]
https://onnxruntime.ai/docs/reference/compatibility.html#onnx-opset-support

**Comment by natke** [comment]
Hi @evolcano, does the above link address your issue? Let us know!

**Comment by evolcano** [comment]
Sure. Thanks!
