### ISSUE TITLE
Removing initializer warning when using converted pytorch models

### ISSUE THREAD

**Issue by martin-91x** [microsoft/onnxruntime#1899]
Hi,

im using an exported Pytorch model together with the onnxruntime. On startup (when the model is loaded) I get a bunch of warnings like the following:
```
2019-09-24 10:46:05.7348377 [W:onnxruntime:Default, graph.cc:2269 onnxruntime::Graph::CleanUnusedInitializers] Removing initializer 'rpn_head.rpn2.cls.conv_kernel.1.num_batches_tracked'. It is not used by any node and should be removed from the model.
2019-09-24 10:46:05.7348643 [W:onnxruntime:Default, graph.cc:2269 onnxruntime::Graph::CleanUnusedInitializers] Removing initializer 'rpn_head.rpn2.cls.conv_kernel.1.running_var'. It is not used by any node and should be removed from the model.
```

I've tried running the onnx model optimizer (and the `polish_model` function) but the warnings still exist.

Can I safely ignor them or should I try to get rid of them (how)?

**Comment by dashesy** [comment]
Or you can use optimizer to get rid of them:

```python
import onnx

onnx_model = onnx.load(onnxfile)
passes = ["extract_constant_to_initializer", "eliminate_unused_initializer"]
from onnx import optimizer
optimized_model = optimizer.optimize(onnx_model, passes)

onnx.save(optimized_model, onnxfile)
```

**Comment by martin-91x** [comment]
Ah, ok. 
Thanks a lot. Missed those optimization passes when looking over all available ones.

**Comment by mijalapenos** [comment]
For anyone exploring this issue two or more years later: the optimizer part of onnx moved to a separate packate, therefore you have to `$ pip install onnxoptimizer` and then update the code mentioned here accordingly.
```python
import onnx
import onnxoptimizer

onnx_model = onnx.load(onnxfile)
passes = ["extract_constant_to_initializer", "eliminate_unused_initializer"]
optimized_model = onnxoptimizer.optimize(onnx_model, passes)

onnx.save(optimized_model, onnxfile)
```

Or at least that's what worked for me.

**Comment by mibrahimy** [comment]
I was able to optimize the model using this [method](https://www.onnxruntime.ai/docs/resources/graph-optimizations.html#python-api-example)

**Comment by zhanghanweii** [comment]
Is it possible to add the above part of the code directly in the program?

**Comment by SolomidHero** [comment]
> I was able to optimize the model using this [method](https://www.onnxruntime.ai/docs/resources/graph-optimizations.html#python-api-example)

I guess link to that resource is updated:
[new link](https://onnxruntime.ai/docs/performance/model-optimizations/graph-optimizations.html#python-api-example)
