### ISSUE TITLE
[Training] [On-device-training] Is it possible to build an onnxruntime-training Python module without onnx and torch deps

### ISSUE THREAD

**Issue by ahlzouao** [microsoft/onnxruntime#18991]
### Describe the issue

Hello,
This isn't really an issue, it is more of a general wondering and maybe a feature request. I'm trying to install onnxruntime-training python module on an arm64 based hardware for on-device-training purposes and I have noticed that it is requiring onnx and torch modules to be installed manually. We are a little bit limited in memory and are not willing to support onnx not torch on our hardware, so we were wondering if it is possible to build a light library of the **onnxruntime-training** module that enables **on-device-training without onnx and torch dependencies** ? 
Thank you for your support and help, 

### To reproduce

No steps to reproduce.

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.15.0

### PyTorch Version

2.1.2

### Execution Provider

Default CPU

**Comment by wschin** [comment]
@baijumeswani, I assume on-device training doesn't need PyTorch. Could you please provide some guidance here?

**Comment by baijumeswani** [comment]
[ahlzouao](https://github.com/ahlzouao) PyTorch is not a required dependency for On-Device Training with ONNX Runtime. Could you share more details on the problem you encountered when PyTorch was not installed? Could you also share your installation command?

**Comment by ahlzouao** [comment]
Hello @baijumeswani,
I am working on a Linux environment where I cannot install python modules manually. What I did is that I built onnxruntime-training python along with libonnxruntime.so library using CMake (build from source using v1.15.0). For that purpose I used the following CMake options:
```
-Donnxruntime_ENABLE_TRAINING=ON \
-Donnxruntime_ENABLE_LAZY_TENSOR=OFF \
```
I managed to have an onnxruntime-training module that I integrated to my Linux image. When I launch any training script I got the following error:

```
>>> import onnxruntime.training.api as orttraining
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/onnxruntime/training/__init__.py", line 11, in <module>
    from .orttrainer_options import ORTTrainerOptions  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/onnxruntime/training/orttrainer_options.py", line 7, in <module>
    from .optim import lr_scheduler
  File "/usr/lib/python3.11/site-packages/onnxruntime/training/optim/__init__.py", line 2, in <module>
    from .fp16_optimizer import FP16_Optimizer  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/onnxruntime/training/optim/fp16_optimizer.py", line 8, in <module>
    from ._modifier_registry import OptimizerModifierTypeRegistry
  File "/usr/lib/python3.11/site-packages/onnxruntime/training/optim/_modifier_registry.py", line 6, in <module>
    from ._apex_amp_modifier import ApexAMPModifier
  File "/usr/lib/python3.11/site-packages/onnxruntime/training/optim/_apex_amp_modifier.py", line 12, in <module>
    from ._modifier import FP16OptimizerModifier
  File "/usr/lib/python3.11/site-packages/onnxruntime/training/optim/_modifier.py", line 13, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```
For me this means that torch is a dependency for onnxruntime-training module. 
NB: I got no dependency issue to pytorch or onnx while using the libonnxruntime C++ library for training models on device.

**Comment by baijumeswani** [comment]
Thanks for the information.

The onnxruntime-training python module is shared between large model training and on-device training. It means that dependencies for both these will be the same from a module level.

Having said that, from the code perspective, there is no dependency on torch for on-device training. If this is a blocker, I would suggest commenting out the lines from the training/__init__.py file in onnxruntime that are trying to import ORTModule (large model training class).

We can evaluate if it is possible to create a standalone on-device training onnxruntime-training python module if the above work around is a no go.

**Comment by ahlzouao** [comment]
Hello @baijumeswani, 
Thank you for your answer, your workaround is really helpful, I managed to get onnxruntime-training module running without installing onnx or torch dependencies. I'm closing this issue, but I think it would be an interesting feature to make it as a light version of onnxruntime-training module.
