### ISSUE TITLE
[Training] [On-device training] ONNX training custom loss | build() method Error

### ISSUE THREAD

**Issue by Marouan-st** [microsoft/onnxruntime#19008]
### Describe the issue

Hi,

I want to define a custom loss in order to train an object detection model (YOLO v4 in onnx format) on device.
In order to do that, part of the offline phase, while generating the training artifacts, I sum 3 losses:
- Bounding box loss
- Objectness loss
- Classification loss
```python 
# Define a custom loss block for yolo v4 model
class YoloV4Loss(onnxblock.Block):
    def __init__(self):
        self._loss1 = onnxblock.loss.MSELoss()
        self._loss2 = onnxblock.loss.BCEWithLogitsLoss()
        self._loss3 = onnxblock.loss.CrossEntropyLoss()
        self._add = onnxblock.blocks.Add()

    def build(self, loss_input_name1, loss_input_name2, loss_input_name3):
        # Returns sum of the three losses
        return self._add(
            self._loss1(loss_input_name1, target_name="target1"),
            self._loss2(loss_input_name2, target_name="target2"),
            self._loss3(loss_input_name3))
```

I get the following error when generating the training artifacts using the Python tool:

TypeError: YoloV4Loss.build() missing 1 required positional argument: 'loss_input_name3'

The onnx model used has been generated following instructions from this repository: https://github.com/Tianxiaomo/pytorch-YOLOv4/tree/master

I tried using different versions of onnxruntime-training: 1.15.1 and the latest at this time 1.16.3.

### To reproduce

Here's the notebook to reproduce the issue:
https://colab.research.google.com/drive/1koOqSwc-OwRhHlnyikDw_dcyLoSj3Dtn?usp=sharing

You'll find the onnx model attached here (20.8 MB):
[yolov4_tiny_training.zip](https://github.com/microsoft/onnxruntime/files/13832087/yolov4_tiny_training.zip)

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.3

### PyTorch Version

2.1.2

### Execution Provider

Default CPU

**Comment by baijumeswani** [comment]
The model you shared has only two outputs: 

![image](https://github.com/microsoft/onnxruntime/assets/12852605/9d3ecd6b-4bd6-47fa-9cd9-719f371ddc0b)


As a result, the tool only passes these two model output names to your custom loss function. What is the expected third loss_input_name for this model?

**Comment by Marouan-st** [comment]
I changed the code in order to sum only two losses:
```python
# Define a custom loss block for yolo v4 model
class YoloV4Loss(onnxblock.Block):
    def __init__(self):
        self._loss1 = onnxblock.loss.MSELoss()
        self._loss2 = onnxblock.loss.BCEWithLogitsLoss()
        self._add = onnxblock.blocks.Add()
        

    def build(self, boxes, confs):
        # Returns sum of the tow losses
        return self._add(
            self._loss1(boxes, target_name="target1"),
            self._loss2(confs, target_name="target2"))
```

Now I get the following error when trying to generate the artifacts:
```
RuntimeError: [/onnxruntime_src/orttraining/orttraining/python/orttraining_pybind_state.cc:841](https://file+.vscode-resource.vscode-cdn.net/onnxruntime_src/orttraining/orttraining/python/orttraining_pybind_state.cc:841) onnxruntime::python::addObjectMethodsForTraining(pybind11::module&, onnxruntime::python::ExecutionProviderRegistrationFn)::<lambda(onnxruntime::python::PyGradientGraphBuilder*)> [ONNXRuntimeError] : 1 : FAIL : Node (onnx::Add::476_Grad/ReduceSum_1) Op (ReduceSum) [ShapeInferenceError] axis must be in [-rank, rank-1]. input rank was 0
```

Do you know what's going on?

Thank you

**Comment by baijumeswani** [comment]
Addressing this in https://github.com/microsoft/onnxruntime/pull/19027
