### ISSUE TITLE
How to transform Ort::Value (int64) into cv::Mat (or cv::cuda::Mat) in C++ cuda? 

### ISSUE THREAD

**Issue by Koruvika** [microsoft/onnxruntime#19029]
### Describe the issue

I need to use my ONNX model in C++, but its output has type int64 so I can't transform it to cv::Mat because OpenCV does not support Mat with type int64.

### To reproduce

as above

### Platform

Windows

### OS Version

Window 10

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.11.0

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.6
```[tasklist]
### Tasks
```

**Comment by xadupre** [comment]
I would probably add a node to your onnx model to cast your output into the type you need. You can use onnx package for that.

**Comment by hariharans29** [comment]
Could you please move this into the discussions forum as there isn't a ORT issue to discuss here ?
