### ISSUE TITLE
[Performance] Inference session creation takes too long

### ISSUE THREAD

**Issue by neNasko1** [microsoft/onnxruntime#19022]
### Describe the issue

I am currently working on a project that involves frequent creation and destruction of `InferenceSession`-s. During this process, I've noticed that the initialization of these sessions can be quite time-consuming, which significantly slows down the overall experimentation process. This led me to question if there's an existing mechanism to prioritize the creation times of inferences.

While I understand that ONNX Runtime is primarily designed to optimize inference speed over initialization speed, I am convinced that there's room for improvement in the latter. To address this, I propose the introduction of a configurable flag or setting that allows users to prioritize initialization speed when required.

This proposed feature could use a range of different strategies, including but not limited to:

- Disabling certain [checks](https://github.com/microsoft/onnxruntime/pull/18791#event-11386319353)
- Turning off various types of optimizations

The introduction of this feature would offer a more adaptable tool for users like myself who frequently create and destroy sessions. Importantly, it would do so without compromising the overall performance for users who prioritize inference speed.

### To reproduce

Models, containing large attributes and nested subgraphs, like this one:
```python
import onnx
import numpy as np
from spox import argument, build, Tensor, Var
from spox.opset.ai.onnx import v17 as op
from spox.opset.ai.onnx.ml.v3 import label_encoder

a = argument(Tensor(np.int64, ('N',)))
c = a

for x in range(100):
    all_strings = list("random_string" + str(i) for i in range(100000))
    all_ints = list(range(len(all_strings)))
    c = op.if_(
        op.const(True),
        then_branch=lambda: [
            label_encoder(
                c,
                keys_int64s=all_ints,
                values_strings=all_strings
            )
        ],
        else_branch=lambda: [
            label_encoder(
                c,
                keys_int64s=all_ints,
                values_strings=all_strings
            )
        ]
    )[0]
    c = label_encoder(c, keys_strings=all_strings, values_int64s=all_ints)

model: onnx.ModelProto = build(inputs={'a': a}, outputs={'c': c})
```
 may be of interest.
Creating a session out of the model takes ~5s.

### Platform

Mac

### OS Version

14.1 (23B2073)

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

upstream

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

Default CPU

### Is this a quantized model?

No

**Comment by adityagoel4512** [comment]
This is a great idea. Such a mode would enable interactive analytics use cases where you might want to make one-time predictions through onnxruntime. An example might be where you take an existing trained model, plot a graph and throw away the runtime.
