### ISSUE TITLE
[Documentation] LLaMa2 tutorial runs into ONNX opset version error

### ISSUE THREAD

**Issue by Tabrizian** [microsoft/onnxruntime#19051]
### Describe the documentation issue

I was trying to follow the tutorial [here](https://github.com/microsoft/onnxruntime/tree/main/onnxruntime/python/tools/transformers/models/llama) for deploying the llama2 model but I ran into the ONNX opset version error:
```
Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 13 is not supported. Support for this operator was added in version 14, try exporting with this version.
```

I double checked the version of the libraries and they seem to be according to what's specified in the tutorial.

To reproduce:

1. `pip3 install onnxruntime-gpu`
2.  `python3 -m onnxruntime.transformers.models.llama.convert_to_onnx -m meta-llama/Llama-2-7b-hf --output llama2-7b`

Observe the error:

```
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 13 is not supported. Support for this operator was added in version 14, try exporting with this version.
```

Library versions:

1. torch==2.3.0.dev20240108
2. transformers== 4.36.2
3. optimum==1.17.0.dev0
4. onnxruntime-gpu==1.16.3
5. onnx==1.15.0
6. protobuf==3.20.2

The libraries were installed in a clean Python environment.

Would appreciate any guidance on what I could be doing wrong. Thanks!

**Comment by kunal-vaishnavi** [comment]
There was a recent update to `transformers` that causes this. The opset error that results from this has been fixed [here](https://github.com/microsoft/onnxruntime/pull/19015#discussion_r1442432173). You can use the "from source" commands to export.

**Comment by kunal-vaishnavi** [comment]
There was a recent update to `transformers` that causes this. The opset error that occurs has been fixed [here](https://github.com/microsoft/onnxruntime/pull/19015#discussion_r1442432173). You can use the "from source" commands to export.

**Comment by Tabrizian** [comment]
Thanks @kunal-vaishnavi. I was able to get it working after trying the nightly onnxruntime wheels. Closing the issue.
