### ISSUE TITLE
`CleanUnusedInitializersAndNodeArgs` warning seems to be redundant

### ISSUE THREAD

**Issue by neNasko1** [microsoft/onnxruntime#19141]
### Describe the issue

When a model with a constant in a subgraph is created, it generates the following warnings:
```
2024-01-15 06:38:44.474 test[87515:8919669] 2024-01-15 06:38:44.474063 [W:onnxruntime:, graph.cc:3572 CleanUnusedInitializersAndNodeArgs] Removing initializer 'If_0_else_branch__Constant_0_output'. It is not used by any node and should be removed from the model.
2024-01-15 06:38:44.474 test[87515:8919669] 2024-01-15 06:38:44.474718 [W:onnxruntime:, graph.cc:3572 CleanUnusedInitializersAndNodeArgs] Removing initializer 'If_0_then_branch__Constant_0_output'. It is not used by any node and should be removed from the model.
```
However, this current behavior doesn't seem to offer any value to the end-user. While there may be a reason for these warnings, the "problematic" nodes they refer to are removed in the same step.

This is demonstrated by the following Python code:
```python
import onnxruntime

# Produces the warning
options = onnxruntime.SessionOptions()
options.optimized_model_filepath="model.onnx"
session = onnxruntime.InferenceSession('model.onnx', sess_options=options)

# Now model.onnx is the optimised model

# Doesn't produce the warning
options = onnxruntime.SessionOptions()
options.optimized_model_filepath="model.onnx"
session = onnxruntime.InferenceSession('model.onnx', sess_options=options)
```
The first session creation triggers the warning, but the second one, which uses the optimized model, does not. This suggests that the warning might not be necessary. Could we consider revising this behavior to improve the user experience?

### To reproduce

Simple graph using spot:
``` python
import onnx
import numpy as np
from spox import argument, build, Tensor, Var
from spox.opset.ai.onnx import v17 as op
from spox.opset.ai.onnx.ml.v3 import label_encoder

a = argument(Tensor(np.int64, tuple()))
c = op.if_(
    op.equal(a, op.const(1))
    ,
    then_branch=lambda: [
        op.const([1])
    ],
    else_branch=lambda: [
        op.const([2])
    ]
)[0]

model: onnx.ModelProto = build(inputs={'a': a}, outputs={'c': c})
onnx.save(model, "model.onnx")
```

### Platform

Mac

### OS Version

14.1

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

upstream

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
Until the model is updated to remove the unused initializers (by saving the model via ORT or running some other cleanup tool) they will waste time and memory during model loading. Depending on your scenario that may or may not be critical. 

Without the warning the user would have no signal that they could benefit from removing these initializers.

**Comment by neNasko1** [comment]
Isn't that a fact that applies to every type of optimization. Do you recon that the warning should be more general and look something like: "Warning: optimisations were performed on the model, export it to benefit from the exported model".

**Comment by cbourjau** [comment]
@skottmckay The issue is not that anything could be removed, though. Onnxruntime replaces constants with initializers which appear to be faster to load, but that seems to be an implementation detail. IMHO, the warning message is misleading in the way that it is worded. Secondly, I think the importance of that information does not justify the `warning` level. If onnxruntime wants to inform users about potential optimizations of an otherwise perfectly valid graph, I believe an info rather than a warning should be logged.

**Comment by neNasko1** [comment]
It's crucial to highlight that, despite the occasional relevance of this warning, it is currently associated with a bug:

The [check](https://github.com/microsoft/onnxruntime/blob/28a16c223cb7a8707fb90340c8aecdc46eec3f2f/onnxruntime/core/graph/graph.cc#L3571) in question presents an issue as it verifies if we are in the initial Graph::Resolve. However, if graph->GraphResolveNeeded() returns false for a specific graph during initialization, then num_resolves_ will not [increment](https://github.com/microsoft/onnxruntime/blob/28a16c223cb7a8707fb90340c8aecdc46eec3f2f/onnxruntime/core/graph/graph.cc#L2805C5-L2805C18) prior to executing optimizations. Consequently, this means that each constant returned from a subgraph will trigger the aforementioned warning.

#19143 tries to resolve this by running `CleanUnusedInitializersAndNodeArgs` on all subgraphs in the beginning of the graph transformations.

**Comment by neNasko1** [comment]
@skottmckay can you take a look as you are also the person that pops up in the gitblame.

**Comment by skottmckay** [comment]
I'm not aware of a path where we do not call Graph::Resolve after loading a model. It's required to populate operator schema information that the optimizers require.

The real problem is we're only incrementing num_resolves_ for the main graph, so the subgraph reporting is incorrect as it's always stuck at 0. 

#19341 should address that.

**Comment by neNasko1** [comment]
Thank you, this simpler change seems to target the issue in the provided samples as well.
