### ISSUE TITLE
Build from source, cannot past test

### ISSUE THREAD

**Issue by CoinCheung** [microsoft/onnxruntime#1915]
**Describe the bug**
The build is successful, but some of the test cases are failed.

**System information**
Linux Ubuntu 16.04, build from source. python3.6.8, gcc=5.4.0, cuda10.0-cudnn7,  gpu is 2080ti.

**To Reproduce**
My command is like this: 
```
PATH=~/build/cmake-3.15.3-Linux-x86_64/bin/:$PATH ./build.sh --config RelWithDebInfo --skip_onnx_tests --use_cuda  --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ --build_wheel
```

I have copied the log messages during the compile process, hope this would explain my problem: 

link is [here](https://github.com/CoinCheung/eewee/blob/master/screenlog.0)

**Comment by snnn** [comment]
"Failed to construct locale with name:en_US.UTF-8"

You misses the locale data. 

Please run this script as root before build:
https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/docker/scripts/install_ubuntu.sh

**Comment by snnn** [comment]
https://github.com/microsoft/onnxruntime/blob/master/README.md :

Certain operators makes use of system locales. Installation of the **English language package** and configuring `en_US.UTF-8 locale` is required.
  * For Ubuntu install [language-pack-en package](https://packages.ubuntu.com/search?keywords=language-pack-en)
  * Run the following commands:
    `locale-gen en_US.UTF-8`
    `update-locale LANG=en_US.UTF-8`
  * Follow similar procedure to configure other locales on other platforms.
