### ISSUE TITLE
Log which node caused dimension error

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#1916]
recently I try to using onnxruntime judge if onnx model right or not. But I just got some messages :

```
2019-09-25 16:08:23.097933163 [E:onnxruntime:, sequential_executor.cc:127 Execute] Non-zero status code returned while running Node:  Status Message: Not satsified: inputs_n_dims[axis_index] == inputs_0_dims[axis_index]
concat.cc:47 PrepareForComputeNon concat axis dimensions must match: Axis 0 has mismatched dimensions of 58 and 85
Traceback (most recent call last):
  File "demo_ort_maskrcnn.py", line 155, in <module>
    out = sess.run(None, {input_name: img_data})
  File "/usr/local/lib/python3.5/dist-packages/onnxruntime/capi/session.py", line 72, in run
    return self._sess.run(output_names, input_feed, run_options)
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : Non-zero status code returned while running Node:  Status Message: Not satsified: inputs_n_dims[axis_index] == inputs_0_dims[axis_index]
concat.cc:47 PrepareForComputeNon concat axis dimensions must match: Axis 0 has mismatched dimensions of 58 and 85
```

It gives me error that some node which maybe Concate, caused dimension error.

Could it possible location which node exactly caused this issue?

**Comment by snnn** [comment]
In ONNX spec, node doesn't have a unique id. So there is no way to point you which node caused the error.

**Comment by pranavsharma** [comment]
If you run with the latest master, it'll print the node name as well. See https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/framework/sequential_executor.cc#L162

**Comment by jinfagang** [comment]
@pranavsharma  Thank u. I installed from pip, would that work too?

**Comment by jywu-msft** [comment]
> If you run with the latest master, it'll print the node name as well. See https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/framework/sequential_executor.cc#L162

it's already printing the node name, which happens to be an empty string.
2019-09-25 16:08:23.097933163 [E:onnxruntime:, sequential_executor.cc:127 Execute] Non-zero status code returned while running Node:  Status Message: Not satsified: inputs_n_dims[axis_index] == inputs_0_dims[axis_index]

but it's pretty clear the error is coming from Concat.

building from source and enabling onnxruntime_DEBUG_NODE_INPUTS_OUTPUTS might be helpful?
https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L82

**Comment by jinfagang** [comment]
@jywu-msft Thank u. Would try it, why not make it default open since this is a good feature?

**Comment by dashesy** [comment]
If we build with `--config Debug` there should be a way to get all those verbose information (increasing the verbosity in session or run options)?

**Comment by jywu-msft** [comment]
> @jywu-msft Thank u. Would try it, why not make it default open since this is a good feature?

it outputs too much. you wouldn't want it on normally. 
that's why it's a build option.

**Comment by jinfagang** [comment]
@dashesy @jywu-msft Thanks you guys. Now I see.
