### ISSUE TITLE
[Performance] Detection model exported from TensorFlow very slow on GPU

### ISSUE THREAD

**Issue by Rayndell** [microsoft/onnxruntime#19206]
### Describe the issue

I have converted to ONNX (sung tf2onnx) a detection model that have been trained with TensorFlow object detection module (https://github.com/tensorflow/models/tree/master/research/object_detection). I know this module have been deprecated, but this model have been trained a while ago and work really well in the TensorFlow C++ API that we use in my company. While the model performance is good in CPU with the ONNX runtime (less than 0.5 seconds per image), it is very slow (up to 2 seconds per image) when using the GPU. It is the same in C++ and Python versions. I already tried to use I/O bindings and modify CUDA provider options to make it faster, without success.

It surely comes from my model, since the model provided here (https://github.com/onnx/models/tree/main/validated/vision/object_detection_segmentation/faster-rcnn) works well and fast as expected. When enabling profiling I can see that many operations are performed on the CPU provider instead of the GPU, so my guess is that the runtime is continuously copying data between GPU and CPU, hence the drop in performance. Am I guessing right here? If yes, is there any means to prevent this?

An example image is provided below, and the model is available here: https://evolucare-my.sharepoint.com/:u:/p/a_ducournau/ETufzCteZplCjU-ODydjq9QBI9vdXQ-MIE8FthiJdxR2rA?e=pkqAAM

### To reproduce

`import onnxruntime as ort
import cv2 as cv
import nnumpy as np

sess = ort.InferenceSession("rfcn_WIDERFACE.onnx", providers=["CUDAExecutionProvider"])

image = cv.imread("0_Parade_marchingband_1_20.jpg")
image = cv.cvtColor(image, cv.COLOR_BGR2RGB)
input = np.expand_dims(image, axis=0)

results_ort = sess.run(["num_detections:0", "detection_scores:0", "detection_classes:0", "detection_boxes:0"], 
			{"image_tensor:0": input})

`
![0_Parade_marchingband_1_20](https://github.com/microsoft/onnxruntime/assets/40670939/6a3c63ce-3478-4b16-8876-e6c78cc915d4)

### Platform

Windows

### OS Version

Server 2016

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.3

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.8

### Model File

https://evolucare-my.sharepoint.com/:u:/p/a_ducournau/ETufzCteZplCjU-ODydjq9QBI9vdXQ-MIE8FthiJdxR2rA?e=pkqAAM

### Is this a quantized model?

Unknown

**Comment by tianleiwu** [comment]
The code to reproduce does not have I/O binding so there is memory copy for graph inputs and outputs, and you will need skip first run during benchmarking or profiling since first run has cuDNN convolution algorithm search.

You can change log verbose level to see which operator is placed on CPU instead of CUDA.

**Comment by Rayndell** [comment]
Thanks for your answer. I already tried I/O binding with the following code:

`ortvalue = ort.OrtValue.ortvalue_from_numpy(input, 'cuda', 0)
			io_binding = sess.io_binding()
			
io_binding.bind_input("image_tensor:0", device_type=ortvalue.device_name(), device_id=0, element_type=np.uint8, shape=ortvalue.shape(), buffer_ptr=ortvalue.data_ptr())
io_binding.bind_output("num_detections:0", "cuda")
io_binding.bind_output("detection_scores:0", "cuda")
io_binding.bind_output("detection_classes:0", "cuda")
io_binding.bind_output("detection_boxes:0", "cuda")

sess.run_with_iobinding(io_binding)
results_ort = io_binding.copy_outputs_to_cpu()`

It did not help. And of course, the computation time I reported is for all runs after the first warmup, and without profiling. With the profiling I saw that a lot of operations are placed on the CPU, and generally the network alternates frequently between CPU and CUDA operations. This might be the cause of the slowness, but it works well with the TensorFlow C++ API (less than 0.2 seconds per image).

**Comment by tianleiwu** [comment]
I saw many subgraph like Loop etc in the model:
![image](https://github.com/microsoft/onnxruntime/assets/30328909/02959b58-2437-478f-b883-5bfccb63ce6c)

Could you raise an issue in https://github.com/onnx/tensorflow-onnx/issues? It seems that the root cause is tf2onnx generates an onnx graph that is not good for performance.

**Comment by Rayndell** [comment]
Many thanks! How do you produce such a graph? It really helps at understanding what happens. The profiling only gave me a really huge json file with a lot of operators listed, which was somehow difficult to understand. I will open an issue related to this.

**Comment by yf711** [comment]
@Rayndell try [netron](https://netron.app/)
