### ISSUE TITLE
We need to be able to set precision on TensorRT layers before optimization.

### ISSUE THREAD

**Issue by BengtGustafsson** [microsoft/onnxruntime#19260]
### Describe the feature request

Allow fine tuning of layer precision in the TensorRT provider. See use case below.

We are struggling with finding a suitable solution to propose for this. We see a few rather unattractive solutions:

- Add a map of layer type name -> precision, output_type included as a member of the struct. This is rather cumbersome as all of this must boil down to C data structures.
- Add a function pointer for a callback which is called with the TRT builder object or network object before optimization begins. This is highly expert and needs more TensorRT knowledge.
- Allow replacing the .engine file, preferably after a "nop" optimization. However this would require us to interface directly to TensorRT which we use onnx Runtime just to avoid!*
- Use TensorRT verion 9.2 which may allow this to be specified in the onnx data (we haven't tried this yet).

* Note: We don't know which hardware end users have, so the entire optimization process has to be done automatically on each system, or at least system type.

### Describe scenario use case

We can't set 16 bit precision all over using the available member OrtTensorRTProviderOptions::trt_fp16_enable as the output will be filled by NaN values despite our best efforts to adjust the onnx file contents to avoid this.

Using TensorRT directly we can set 16 bit on selected layer types and it works. This possibility is however not available via the OrtTensorRTProviderOptions struct (even in its V2 version).

For reference, here is what we  do in the TRT python bindings:
``` python
def set_precision(self):
        for i in range(self.network.num_layers):
            l = self.network.get_layer(i)
            if l.type in [trt.LayerType.CONVOLUTION, trt.LayerType.ACTIVATION, 
                          trt.LayerType.MATRIX_MULTIPLY, trt.LayerType.POOLING, 
                          trt.LayerType.FULLY_CONNECTED, trt.LayerType.REDUCE, 
                          trt.LayerType.RESIZE, trt.LayerType.SELECT, 
                          trt.LayerType.UNARY]:
                l.precision = trt.DataType.HALF
                l.set_output_type(0, trt.DataType.HALF)
            elif l.type in [trt.LayerType.SHUFFLE, trt.LayerType.CONCATENATION, 
                            trt.LayerType.SLICE, trt.LayerType.GATHER, 
                            trt.LayerType.CONSTANT, trt.LayerType.SHAPE, 
                            trt.LayerType.ELEMENTWISE]:
                l.precision = l.get_output_type(0)
```

**Comment by gedoensmax** [comment]
> Use TensorRT verion 9.2 which may allow this to be specified in the onnx data (we haven't tried this yet).

In current main TRT 10 should already be working which is the preferred version to use over TRT 9.X. Furthermore the current main will build your networks with strict precision as specified by the ONNX file if the precision is not overwritten by using fp16 or int8: https://github.com/microsoft/onnxruntime/blob/a7a49189e8840c77d2333a07cfdf5e04f9faa733/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc#L2175

To make your engine more hardware compatible there is a new option as well: https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#trt_engine_hw_compatible

**Comment by BengtGustafsson** [comment]
In 1.19.2 we can now provide an ONNX blob that specifies the required operations as 16 bits while others retain 32 bits, so this solves this issue.
