### ISSUE TITLE
Cannot run batch inference with GRU layer, even though the model was exported with dynamic axes

### ISSUE THREAD

**Issue by StMarou** [microsoft/onnxruntime#19270]
### Describe the issue

When I export a model with a GRU layer in it, I can only run inference with the same batch size it was exported with. Even though I use dynamic axes on the first index (starting from 0), which according to the Pytorch docs it's the batch size (for the GRU layer). Here's a depiction of the model, where it correctly configures the batch size: 
![image](https://github.com/microsoft/onnxruntime/assets/103185266/5ba4d9ff-36ec-40ea-b52b-d4021002f6c2)

### To reproduce

```
import torch
import onnxruntime


class DummyGRU(torch.nn.Module):

    def __init__(self):
        super(DummyGRU, self).__init__()
        self.gru = torch.nn.GRU(20, 20)

    def forward(self, input_data, hidden_state):
        return self.gru(input_data, hidden_state)


if __name__ == '__main__':
    gru = DummyGRU()

    input_data = torch.randn(10, 1, 20)  # batch_size=1
    h_0_data = torch.randn(1, 1, 20)  # batch_size=1

    with torch.no_grad():
        torch.onnx.export(
            model=gru,
            args=(input_data, h_0_data),
            f="onnx_gru.onnx",
            input_names=["input_data", "hidden_state"],
            output_names=["output"],  
            dynamic_axes={
                "input_data": {1: "batch_size"},
                "attention_mask": {1: "batch_size"}
            }
        )

    session = onnxruntime.InferenceSession(path_or_bytes="onnx_gru.onnx")
    out = session.run(
        output_names=None,
        input_feed={
            "input_data": torch.randn(10, 5, 20).detach().numpy(),
            "hidden_state": torch.randn(1, 5, 20).detach().numpy()
        }
    )
```

### Platform

Mac

### OS Version

13.2.1 

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.3

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by xadupre** [comment]
Can you copy paste the error you get? And also the output of the following python code:

```python
import onnx
onx = onnx.load("onnx_gru.onnx")
print(onx.graph.input)
```

**Comment by StMarou** [comment]
There was a mistake from me, it actually works fine, sorry about that!!
