### ISSUE TITLE
Does onnruntime-gpu support CUDA12.1？

### ISSUE THREAD

**Issue by zhongqiu1245** [microsoft/onnxruntime#19292]
### Describe the issue

Hello!
I use onnxruntime to run ptq(quant, static), but my cpu threads are always be killed.
So, I want to use gpu.
But, when I set provider=['CUDAExecutionProvider'], the error 'Failed to create cuda provider' was coming.
Does onnxruntime-gpu support CUDA12.1(pip install onnxrumtime)？
And pardon my poor english.

### To reproduce

sess = ort.InferenceSession('xxxxxx.onnx', providers=['CUDAExecutionProvider'])

'Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.'

### Urgency

Not really

### Platform

Linux

### OS Version

ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

onnxrumtime 1.16.2

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA12.1

**Comment by tianleiwu** [comment]
You will need wait for 1.17 release, which will have cuda 12 release package. 

You can test release candidate build here:
ort-nightly-gpu : [1.17.0.dev20240118002](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ort-cuda-12-nightly/PyPI/ort-nightly-gpu/overview/1.17.0.dev20240118002)

**Comment by snnn** [comment]
See also: #19137

**Comment by zhongqiu1245** [comment]
Thank you， guys！

**Comment by tianleiwu** [comment]
See https://onnxruntime.ai/docs/install/#requirements if you encountered issue with CUDA 12.*

**Comment by JohnHerry** [comment]
Which version can support CUDA12.1+cuDNN8.9?

**Comment by tianleiwu** [comment]
@JohnHerry, You can install latest version like
```
pip install onnxruntime-gpu==1.19.2 --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-11/pypi/simple/
```
If you use PyTorch, you can install torch 2.3.1 for cuda 12.x. Note that torch 2.4.* use cuDNN 9.x so it is not compatible.

**Comment by JohnHerry** [comment]
> https://aiinfra.pkgs.visualstudio.com/PublicPackages/_p

Thank you very much for the help. by the way, I need to install with local package. where can I download this package?

**Comment by tianleiwu** [comment]
> > https://aiinfra.pkgs.visualstudio.com/PublicPackages/_p
> 
> Thank you very much for the help. by the way, I need to install with local package. where can I download this package?

Yes, you can download the whl file (See https://onnxruntime.ai/docs/install/#python-installs for wheel loculation), then `pip install *.whl`
