### ISSUE TITLE
[Build] build for iOS fails

### ISSUE THREAD

**Issue by wtholliday** [microsoft/onnxruntime#19304]
### Describe the issue

Failing to build on macOS with command from [here](https://onnxruntime.ai/docs/build/ios.html#build-instructions)

Using revision [82c1cb4](https://github.com/microsoft/onnxruntime/commit/82c1cb416b8054f67fe1f73928ad4c276d80afdb)

### Target platform

iOS

### Build script

./build.sh --config Release --use_xcode --ios --apple_sysroot iphoneos --osx_arch arm64 --apple_deploy_target 17.2

### Error / output

Traceback (most recent call last):
  File "/Users/holliday/tmp/onnxruntime/tools/ci_build/github/apple/get_simulator_device_info.py", line 154, in <module>
    main()
  File "/Users/holliday/tmp/onnxruntime/tools/ci_build/github/apple/get_simulator_device_info.py", line 143, in main
    info = get_simulator_device_info(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/holliday/tmp/onnxruntime/tools/ci_build/github/apple/get_simulator_device_info.py", line 121, in get_simulator_device_info
    selected_runtime_id, selected_device = max(runtime_id_and_device_pairs, key=runtime_id_and_device_pair_key)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by skottmckay** [comment]
What output does `xcrun simctl list` give you?

**Comment by wtholliday** [comment]
@skottmckay   
[simctl_list.txt](https://github.com/microsoft/onnxruntime/files/14088001/simctl_list.txt)

**Comment by YUNQIUGUO** [comment]
I run the commands locally and can repro the error.

got more info:
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 17.2, but the range of supported deployment target versions is 12.0 to 17.0.99. (in target 'absl_bad_variant_access' from project 'onnxruntime')

looks like the deployment target version is newer than the latest set range. @skottmckay @edgchen1 do we know where we set this limit / can we extend the range to accommodate latest ios versions?

**Comment by edgchen1** [comment]
I think #19396 might fix it. if not, please reopen and share more error output.
