### ISSUE TITLE
Please clarify the default CUDA support of onnxruntime 1.17.0

### ISSUE THREAD

**Issue by henryruhs** [microsoft/onnxruntime#19356]
### Describe the issue

I do not fully understand if `onnxruntime-gpu 1.17.0` supports both CUDA 11.8 and CUDA 12.1 or if CUDA 12.1 needs a certain `--extra-index-url` to a stable channel.

If that is the case, why is this not easy to find in your docs?

### To reproduce

I used `--extra-index-url https://pkgs.dev.azure.com/onnxruntime/onnxruntime/_packaging/onnxruntime-cuda-12/pypi/simple` for CUDA 12.1 support but it does not seem stable and kinda broken some of my fp16 model inferences (black boxes).

### Platform

Linux

### OS Version

Ubuntu 22

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 12.1

**Comment by tianleiwu** [comment]
Try  
```
python -m pip install coloredlogs flatbuffers numpy packaging protobuf sympy
pip install onnxruntime-gpu --index-url https://pkgs.dev.azure.com/onnxruntime/onnxruntime/_packaging/onnxruntime-cuda-12/pypi/simple --no-cache-dir
```

**Comment by henryruhs** [comment]
Thanks for the clarification. So I made it correct already.
