### ISSUE TITLE
Flag to skip all tests in build

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#1938]
**Describe the bug**
I would like to have a debug build, without running tests:
I have to wait for tests to finish to get the wheel file.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 0.5.0
- Python version: 3.6

**To Reproduce**
Describe steps/code to reproduce the behavior:
```
./build.sh --config Debug --build_shared_lib --skip_onnx_tests --enable_pybind --build_wheel --parallel
```
**Expected behavior**
A flag to skip all tests

**Additional context**
Is there a way to do `pip install -e .` or `python setup.py develop` to avoid wheel?

**Comment by jywu-msft** [comment]
you can already do this by explicitly leaving out the --test build step.
just do ./build.sh --update --build --build_wheel
internally build.sh sets --update --build --test  by default.

**Comment by dashesy** [comment]
That will do, thanks! how about things like `--build_shared_lib`? can I pass them as before? just adding `--update --build` like:

```bash
./build.sh --config Debug --update --build --build_shared_lib --enable_pybind --build_wheel --parallel
```
?

**Comment by jywu-msft** [comment]
Yes. That should work fine.

**Comment by dashesy** [comment]
thanks, will close this issue
1. just to be certain would adding `--update` work even on a fresh clone? 
2. is there any plans to document in more details for running from source? debug flags, ...
