### ISSUE TITLE
[Documentation] Latest Supported Onnx Runtime for TensorRT mentioned as 12.2

### ISSUE THREAD

**Issue by Samiii777** [microsoft/onnxruntime#19399]
### Describe the documentation issue

Not sure if I am correct or not, but I realized onnx runtime for tensorrt recently has been added for CUDA 12.2 in here:
docs/execution-providers/TensorRT-ExecutionProvider.md
https://github.com/microsoft/onnxruntime/blob/gh-pages/docs/execution-providers/CUDA-ExecutionProvider.md#requirements

according to Nvidia's documentation TensorRT 8.6 GA is only supported by CUDA 12.1 and not 12.2
https://developer.nvidia.com/nvidia-tensorrt-8x-download
am I missing something ?

### Page / URL

https://github.com/microsoft/onnxruntime/blob/gh-pages/docs/execution-providers/CUDA-ExecutionProvider.md#requirements

**Comment by tianleiwu** [comment]
Because of CUDA Minor Version Compatibility, Onnx Runtime built with CUDA 12.2 shall be compatible with CUDA 12.1 and 12.3.

For example, Nvidia docker `nvcr.io/nvidia/pytorch:24.01-py3` has CUDA 12.3 and TRT 8.6. They work well with Onnx Runtime 1.17 in my tests.

**Comment by Samiii777** [comment]
thanks for clarifying
