### ISSUE TITLE
How to inference only use cpu

### ISSUE THREAD

**Issue by WilliamZhaoz** [microsoft/onnxruntime#1942]
I inference my model in onnxruntime on a cpu + gpu device, I hope it only use cpu for inference to test the performance, but it always use gpu automaticly. How can I use only cpu.

**Comment by snnn** [comment]
Are you using the python API or C/C++ API?

**Comment by WilliamZhaoz** [comment]
I use python api

**Comment by snnn** [comment]
Please build onnxruntime from source code without enabling CUDA.

https://github.com/microsoft/onnxruntime/blob/master/BUILD.md

**Comment by WilliamZhaoz** [comment]
In this way, can I use python api since I use python API now.
After I build from source, how can I use python API?

Thanks.


Changming Sun <notifications@github.com> 于2019年9月28日周六 上午5:24写道：

**Comment by jywu-msft** [comment]
you can build a python wheel from source (use the --build_wheel option when invoking build.sh) and install it.

in master, there's a new python api to force cpu execution even if gpu is enabled.

sess = ort.InferenceSession('model.onnx')
# if gpu enabled, get_providers() should return ['CUDAExecutionProvider', 'CPUExecutionProvider']
sess.get_providers()
# force cpu execution
sess.set_providers(['CPUExecutionProvider'])
sess.run(...)

**Comment by faxu** [comment]
any reason to not just use the CPU-only package? https://pypi.org/project/onnxruntime/

**Comment by jywu-msft** [comment]
> any reason to not just use the CPU-only package? https://pypi.org/project/onnxruntime/

there are multiple options. depends on what the OP is trying to accomplish.
if they just want to test CPU, yes, perhaps installing CPU-only package from pypi is easiest.

if OP wanted to test CPU vs GPU using a single package, one can use the runtime api's described above to select between them.
Another option would be to install both CUDA and CPU packages from pypi under different conda environments and switching between them.

**Comment by WilliamZhaoz** [comment]
Thank you @Geroge Wu and Faith Xu,

I'll try your solution @Geroge Wu, thanks.
BTW, I just install from the pypi install link you share with me @Faith Xu,
but when I inference my model on a cpu+gpu device, I can see the model run
on both cpu and gpu, I do not know why.
I only want to inference my model in cpu.

Thanks.

George Wu <notifications@github.com> 于2019年10月1日周二 上午12:43写道：

**Comment by jywu-msft** [comment]
that doesn't sound right re: installing cpu package from pypi but seeing the model run on gpu.
can you share the output of the following commands:

import onnxruntime
onnxruntime.__file__
onnxruntime.get_device()


> Thank you @geroge Wu and Faith Xu, I'll try your solution @geroge Wu, thanks. BTW, I just install from the pypi install link you share with me @Faith Xu, but when I inference my model on a cpu+gpu device, I can see the model run on both cpu and gpu, I do not know why. I only want to inference my model in cpu.

**Comment by WilliamZhaoz** [comment]
Hi George,
I got following:
[image: Screen Shot 2019-10-04 at 1.08.43 AM.png]
but when I inference my model in onnxruntime, I can see my gpu is working.
thanks.


George Wu <notifications@github.com> 于2019年10月2日周三 下午11:38写道：

**Comment by jywu-msft** [comment]
i can't see your screenshot, can you paste it as text?
are you using nvidia-smi to monitor gpu usage?

**Comment by WilliamZhaoz** [comment]
the out is:
"
Python 3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime
>>> onnxruntime.file
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'onnxruntime' has no attribute 'file'
>>> onnxruntime.get_device()
'CPU'
>>> onnxruntime.file()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'onnxruntime' has no attribute 'file'
>>>
"
yes, I using nvidis-smi, when I inference the model, I find gpu is working,
and when the inference process is done, the gpu is also idle

George Wu <notifications@github.com> 于2019年10月4日周五 上午1:17写道：

**Comment by jywu-msft** [comment]
`onnxruntime.__file__`
not
`onnxruntime.file`

**Comment by jywu-msft** [comment]
and nvidia-smi is showing gpu utilization from the onnxruntime python process, not something else?

**Comment by WilliamZhaoz** [comment]
Hi George Wu,
sorry for late reply due to national day vocation.
following are outputs:
"
>>> onnxruntime.get_device()
'CPU'
>>> onnxruntime.__file__
'/home/zhiyuan/anaconda3/envs/psnet/lib/python3.7/site-packages/onnxruntime/__init__.py'
>>>
"
and, yes, nvidia-smi show my gpu is working only when I run the onnxruntime
python process, not something else.

George Wu <notifications@github.com> 于2019年10月4日周五 上午1:24写道：

**Comment by WilliamZhaoz** [comment]
Hi George Wu,
I double checked my code, I found it is a data preprocess used GPU, sorry
for the confusion.
Thanks for your patient.

Zhiyuan Zhao <zhiyuan.zhaochn@gmail.com> 于2019年10月8日周二 上午10:36写道：

**Comment by jywu-msft** [comment]
Thanks for confirming there's no problem.
Will close this issue now.
