### ISSUE TITLE
onnxruntime 1.17.0 - fp16 model of inswapper causing render issues

### ISSUE THREAD

**Issue by henryruhs** [microsoft/onnxruntime#19437]
### Describe the issue

Since we updated to `onnxruntime==1.17.0` the `float16` version of the inswapper model stopped working and causes broken results depending in the integration.

Falling back to `onnxruntime==1.16.3` resolves the issue. It seems to be broken for CPU and CUDA but works for TensorRT.

## Distorted face (cuda)

![Broken1](https://raw.githubusercontent.com/henryruhs/onnxruntime-fp16-issue/master/examples/output-broken1.jpg?sanitize=true)

## Face box being black (cpu)

![Broken2](https://raw.githubusercontent.com/henryruhs/onnxruntime-fp16-issue/master/examples/output-broken2.jpg?sanitize=true)

### To reproduce

I created a dedicated repository to reproduce the issue and convert the model.

https://github.com/henryruhs/onnxruntime-fp16-issue

### Urgency

Not sure how to define urgency, but this effects thousand of users as our project (FaceFusion) is kinda popular.

### Platform

Linux

### OS Version

Ubuntu 22 LTS

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU, CUDA

**Comment by tianleiwu** [comment]
I can reproduce the issue. Let me try dump node inputs/outputs and see which operator might cause result change.

**Comment by tianleiwu** [comment]
The issue is caused by https://github.com/microsoft/onnxruntime/pull/17953. Some Cast node is no longer removed in ORT 1.17.0, and there is overflow.

For example:
![image](https://github.com/microsoft/onnxruntime/assets/30328909/86a9e977-15cd-461a-8099-b56f20579bd6)

A walkaround is to remove those extra Cast nodes from fp16 model. A simple way is to use onnxruntime 1.16.0 to create a session and specify a path in session option to save the optimized onnx model like the following:
https://github.com/microsoft/onnxruntime/blob/df5c6718bd67bdc59fb77fbd4a6ccdcaf902145c/tools/python/util/onnx_model_utils.py#L111
Extra Cast nodes will be removed by ORT 1.16.   Then you can use the optimized fp16 model to run in ORT 1.17.

**Comment by tianleiwu** [comment]
For CPU execution provider, it is better to run fp32 model. It is because CPU cannot run fp16 in most computation operators, and need to convert to fp32 to run those operators (You can save the optimized model from CPU provider, and you can understand that).

**Comment by henryruhs** [comment]
Do you suggest waiting for a fix or should we re-convert the model with suggested tweaks?

**Comment by tianleiwu** [comment]
@henryruhs, please re-convert the model. That's the fastest way to walkaround the issue.

The fix I mentioned shall be done in onnxconverter-common, and you can track the status of (https://github.com/microsoft/onnxconverter-common/issues/271).

**Comment by henryruhs** [comment]
@tianleiwu We tried `onnx_model.remove_cascaded_cast_nodes()` but it does not work. Therefore we need to wait for a fix on your side. What about a compat mode for the time being?

**Comment by tianleiwu** [comment]
@henryruhs, I verified that the issue was resolved using the code snippet I provided above. Note that the list of initializer might changed so you might need use name to find initializer for INSWAPPER_MATRIX.

**Comment by henryruhs** [comment]
@tianleiwu Are you using the CUDA 12.2 version of onnxruntime 1.17.x ???

**Comment by tianleiwu** [comment]
> @tianleiwu Are you using the CUDA 12.2 version of onnxruntime 1.17.x ???
Yes. I think it shall be good with CUDA 11.8 version of ORT 1.17.x too when extra Cast nodes are removed from onnx model.

**Comment by henryruhs** [comment]
@tianleiwu First, thanks for your patience. I revisited the issue again and figured out that the "fixed" version does indeed work when using the original / pre-fixed model initializer.

That being said, it seems to mess up the shape or internals once the cascaded_cast_nodes have been removed.
```
source_embedding = numpy.dot(source_embedding, model_initializer) / numpy.linalg.norm(source_embedding)
ValueError: shapes (1,512) and (1,) not aligned: 512 (dim 1) != 1 (dim 0)
```

I can verify the report with this code - it works under CUDA 12:
```
MODEL_INITIALIZER = numpy.load('./MODEL_INITIALIZER.npy')
```

Not sure what we can do from here, I wish you can undo the changes from https://github.com/microsoft/onnxruntime/pull/17953.

**Comment by tianleiwu** [comment]
You can get the initializer by name (assume that the initializer name does not change).

For #17953, we will keep it. Maybe we can add an option to remove cascaded cast nodes as a native optimizer so that user can use it (without using python script).

**Comment by henryruhs** [comment]
I fixed it be adding the initializer back afterwards:

```python
import onnx
from onnx import numpy_helper
from onnxruntime.transformers.onnx_model import OnnxModel

import numpy as np

PATH = '.assets/models/'
SWAPPER_MODEL_PATH = PATH + 'inswapper_128_fp16.onnx'

model = onnx.load(SWAPPER_MODEL_PATH)

onnx_model = OnnxModel(model)
onnx_model.remove_cascaded_cast_nodes()

onnx_initializer = model.graph.initializer[-1]
INSWAPPER_INITIALIZER = np.load("initializer.npy")

new_initializer_array = np.array(INSWAPPER_INITIALIZER)

model.graph.initializer.append(numpy_helper.from_array(new_initializer_array, name="initializer"))

onnx_model.save_model_to_file(PATH + "inswapper_128_fp16_v2.onnx", use_external_data_format=False, all_tensors_to_one_file=True)
```

**Comment by henryruhs** [comment]
Thanks again for the support

**Comment by 5RJ** [comment]
> I fixed it be adding the initializer back afterwards:我修复了它，之后添加了初始化器：
> 
> import onnx
> from onnx import numpy_helper
> from onnxruntime.transformers.onnx_model import OnnxModel
> 
> import numpy as np
> 
> PATH = '.assets/models/'
> SWAPPER_MODEL_PATH = PATH + 'inswapper_128_fp16.onnx'
> 
> model = onnx.load(SWAPPER_MODEL_PATH)
> 
> onnx_model = OnnxModel(model)
> onnx_model.remove_cascaded_cast_nodes()
> 
> onnx_initializer = model.graph.initializer[-1]
> INSWAPPER_INITIALIZER = np.load("initializer.npy")
> 
> new_initializer_array = np.array(INSWAPPER_INITIALIZER)
> 
> model.graph.initializer.append(numpy_helper.from_array(new_initializer_array, name="initializer"))
> 
> onnx_model.save_model_to_file(PATH + "inswapper_128_fp16_v2.onnx", use_external_data_format=False, all_tensors_to_one_file=True)

Hello, could you please share the initializer.npy? or how do you generate it?

**Comment by henryruhs** [comment]
this is not stackoverflow and you actual quoted the answer...

**Comment by 5RJ** [comment]
> stackoverflow

Sorry, I can't get it. I mean this line: INSWAPPER_INITIALIZER = np.load("initializer.npy"). what is the initializer.npy?
