### ISSUE TITLE
【BUG】TypeError: expected str, bytes or os.PathLike object, not TemporaryDirectory

### ISSUE THREAD

**Issue by duanshengliu** [microsoft/onnxruntime#19430]
### Describe the issue

The code at https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/quantization/quantize.py#L482 will trigger the `TypeError`:

**TypeError: expected str, bytes or os.PathLike object, not TemporaryDirectory**

We can fix this issue by replacing `sq_path` with `sq_path.name`, like this:
```
model_input = Path(sq_path.name).joinpath("sq_model.onnx").as_posix()
```
Because the type of `sq_path` is `<class 'tempfile.TemporaryDirectory'>` while the type of `sq_path.name` is `<class 'str'>`.

### To reproduce

A simple reproducible code is as follows:
```
import tempfile
from pathlib import Path

sq_path = tempfile.TemporaryDirectory(prefix="ort.quant.")
model_input = Path(sq_path).joinpath("sq_model.onnx").as_posix()
```

### Urgency

No

### Platform

Linux

### OS Version

Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-200-generic x86_64)

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by fs-eire** [comment]
Thank you for the bug report. would you like to submit a PR for a fix?

**Comment by duanshengliu** [comment]
Sure, I created a PR here: [#19459]( https://github.com/microsoft/onnxruntime/pull/19459)

**Comment by yufenglee** [comment]
Thanks for your contribution!
