### ISSUE TITLE
[Performance]  onnx creating in the main thread and prediction in other thread

### ISSUE THREAD

**Issue by youlxs** [microsoft/onnxruntime#19432]
### Describe the issue

I created the onnx env and session in the main thread (A) and set both infra and infer OpNumThreads to 1.  And I will predict in another thread (B) binding to another CPU core.  My question is on which thread the prediction will be executed. 
The execution will be switched to the main thread A or just in thread B.

### To reproduce

please refer to my question

### Platform

Linux

### OS Version

centos 7.9

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.17.0

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

### Is this a quantized model?

No

**Comment by snnn** [comment]
Just in thread B

**Comment by youlxs** [comment]
> Just in thread B

thanks
