### ISSUE TITLE
[Documentation] ORT 1.17.0 contributions list is incomplete

### ISSUE THREAD

**Issue by sophies927** [microsoft/onnxruntime#19444]
### Describe the documentation issue

**The current list of contributions from the recent ORT 1.17.0 release is incomplete** (e.g., it does not include contributions made via forked repos). [Here](https://github.com/microsoft/onnxruntime/commits?since=2023-08-18&until=2024-01-16) is the complete list of commits from this release period, and [here](https://github.com/microsoft/onnxruntime/graphs/contributors?from=2023-08-18&to=2024-01-16&type=c) is the incomplete list of contributors used to generate the contributions section. For example, I (@sophies927) made [4 contributions](https://github.com/microsoft/onnxruntime/commits?since=2023-08-18&until=2024-01-16&author=sophies927) during the release period but do not show up on [this list](https://github.com/microsoft/onnxruntime/graphs/contributors?from=2023-08-18&to=2024-01-16&type=c) b/c they were made via a forked repo.

**Other reasons why your contributions may not be reflected:** https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#commits

We are currently working on resolving this issue, but in the meantime, **please let us know if you made a contribution that is not reflected in the contributions list**, and we will update to make sure all ONNX Runtime contributors are getting credit for their hard work on the ORT 1.17 release!

### Page / URL

https://github.com/microsoft/onnxruntime/releases/tag/v1.17.0

**Comment by sophies927** [comment]
> Hey, I contributed to this merged PR #17726, also from a forked repo. Not sure if this should appear in the contributions, my apologies if that's not the case!

Thanks so much for your contribution - your name should definitely appear in the list! Just updated https://github.com/microsoft/onnxruntime/releases/tag/v1.17.0 to include you

**Comment by tianleiwu** [comment]
@sophies927,  A simple way is to like the following:
 git log --since 08/20/2023 --until 01/16/2024 > commits.txt
Then have a script to do statistics of author and co-author. Note that cherry-picks are ignored. The range could be more accurate with commit ID range instead of date range.

**Comment by sophies927** [comment]
> @sophies927, A simple way is to like the following: git log --since 08/20/2023 --until 01/16/2024 > commits.txt
> 
> Then have a script to do statistics of author and co-author. Note that cherry-picks are ignored (May need adjust if needed). The dates are for the day that cut the branches of 1.16 and 1.17 (You may change it to commit ID range to be more accurate like [this](https://stackoverflow.com/questions/18679870/list-commits-between-2-commit-hashes-in-git)).

Thanks @tianleiwu I'll try that out!

**Comment by sophies927** [comment]
I fixed the issue, so the contributors list for the 1.17.0 release should be complete, and I am going to close this issue.
