### ISSUE TITLE
[Build] Build as pure CMake project with bitbake in yocto

### ISSUE THREAD

**Issue by molysgaard** [microsoft/onnxruntime#19456]
### Describe the issue

We want to use onnxruntime for a project at work.

The platform we are running on has a custom embedded Linux distribution compiled using yocto/bitbake.

Bitbake is able to cross-compile cmake projects out of the box, if they are pure and self-contained cmake projects.
With onnxruntime, I have not been able to do the usual

```
cd onnxruntime
mkdir build
cd build
cmake ../cmake PASS_YOUR_CMAKE_ARGUMENTS_HERE
```

This hinders onnxruntime from being compiled, at least easily, using bitbake/yocto.

Questions:
1. How would you approach building onxxruntime with the standard cmake way?
2. To get reproducible builds, yocto disables network requests during configure and compile time. git submodules are fine as they are checked out when you clone the repository, but downloading things from the internet during configure or compilation is not possible. The onnxruntime build system does a lot of downloads etc. during configure/compile. Is it possible to disable this some way and instead rely on pre-downloaded packages? This is a relatively general pattern. Distro managers usually do not allow packages to download stuff "on their own", as that will make it impossible to properly cache downloaded content and also hard to validate the reproducibility of the build.

I would be very happy for any insight into either of these two questions.

### Target platform

linux arm64, nvidia jetson

### Build script

N/A

### Error / output

N/A

**Comment by snnn** [comment]
1. Yes, that's fine. You do not have to use build.py. 
2. Open cmake/deps.txt and replace the paths to local paths. ONNX Runtime also supports standard cmake find_package calls.
