### ISSUE TITLE
[Performance] Transformer model inference time increase when NNAPI enabled 

### ISSUE THREAD

**Issue by arseniymerkulov** [microsoft/onnxruntime#19452]
### Describe the issue

I followed this [thread](https://github.com/microsoft/onnxruntime/issues/9054) to enable NNAPI support for my vision transformer model. After using static inputs/outputs and converting the model to ort format, its inference time increased from 2s on cpu to 4s using NNAPI. After applying static quantization, the inference time increased to 47s. It is also worth noting that the execution time of the converted models on the CPU remained the same, aproximetly 2s. Models were tested on Samsung S23 and Xiaomi Mi9 lite.

My prediction is that model have some layers that is incomatible with mobile hardware to which NNAPI delegates computing or demand constant transferring between cpu/gpu. Can vit model be used with NNAPI efficiently?

Also, i have a question about batches in onnxruntime. In pytorch, using batches for vit models (1 image batch size vs 64 image batch size) will reduce inference time by ~1.2x. When i use 64 batches for similair onnx models on the same hardware, they have slightly slower inference time compared to 1 batch size. At the same time, onnx models already run ~3x faster than pytorch models. 
Can batches in ort help reduce inference time?

### To reproduce

Attaching model in .onnx format
[model.zip](https://github.com/microsoft/onnxruntime/files/14192751/model.zip)

### Platform

Windows

### OS Version

22H2

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.3

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

NNAPI

### Is this a quantized model?

Yes

**Comment by skottmckay** [comment]
Most likely your model contains operator/s that are not supported. 

Set the log severity level to verbose in the session options and look for 'Node placements' in the output. That will provide info on which nodes are assigned to NNAPI and which ones aren't, and how many partitions (a 'partition' is a group of connected nodes that is converted into a single NNAPI model) there are. Going back and forth between the CPU EP and NNAPI EP for different partitions is expensive. Ideally you want only one or two partitions. 

It's also possible for NNAPI to be assigned the node but use a 'reference' implementation of the operation if the underlying hardware does not implement the operation. This is an extremely slow basic implementation that has no optimizations. IIRC there's info in the log if it does use a reference implementation. 

Alternatively you can run the model checker tool from the onnxruntime python package to see which operators might not be supported. Not quite as precise as checking the actual assignments, but a quick way to get info.

`python D:\src\github\ort\tools\python\check_onnx_model_mobile_usability.py --log_level debug <model.onnx>`

**Comment by arseniymerkulov** [comment]
Thank you, tool provided info on ops support. It seems unsupported operators are found in large numbers in the transformer part of the model when searching with netron. Are there conversion paths for transformers that will not contain unsupported operations in the onnx format?
```
INFO:  Checking model.fixed.onnx for usability with ORT Mobile.
INFO:  Checking NNAPI
INFO:  13 partitions with a total of 592/604 nodes can be handled by the NNAPI EP.
INFO:  Partition sizes: [47, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 17]
INFO:  Unsupported nodes due to operator=12
INFO:  Unsupported ops: ai.onnx:Erf
DEBUG:  Caveats that have not been checked and may result in a node not being supported:
     ai.onnx:Conv:Only 2D Conv is supported. Weights and bias should be constant.
     ai.onnx:Gather:Input indices should be constant if not int32 type.
     ai.onnx:Gemm:If input B is not constant, transB should be 1.
INFO:  NNAPI is not recommended with this model as there are 13 partitions covering 98.0% of the nodes in the model. This will most likely result in worse performance than just using the CPU EP.
INFO:  Model should perform well with NNAPI as is: NO
```

**Comment by arseniymerkulov** [comment]
Ok, thank you, seems like i should stick with CPU. Can you also answer a question about batches from my first post?

**Comment by skottmckay** [comment]
Batches can help but the batch size might be a factor. e.g. if the batch size is too large the memory required to execute the model may exceed what is free, leading to paging, costing performance. 

Internally there's no special handling of batches - the model executes once and there's just more data passing through the model. c.f. the alternative would be to split the batches into chunks and executes the model in parallel for each chunk and merge the results at the end.

Also note that using a mix of batch sizes at runtime might impact memory usage if memory pattern planning is enabled. When it is, on the first request for a given input size we trace how much memory is required to execute the model. On the next request with matching input sizes we allocate a block of that size and use offsets into that block to avoid allocating/freeing smaller chunks. The arena does not shrink though, so if there's a lot of different batch sizes that's a lot of different large chunks. It will re-use a chunk where possible (splitting/coalescing free chunks when needed/possible), but it's not going to be as optimal as a limited set of batch sizes. 

If you set the log severity level to INFO there should be output from bfc_arena about the memory allocations it does.
