### ISSUE TITLE
[Build] Java custom build issue

### ISSUE THREAD

**Issue by Akash005Vengai** [microsoft/onnxruntime#19466]
### Describe the issue

I was tried custom build for ORT model config file.
```
# Generated from model/s:
# - rf.ort
ai.onnx.ml;5;TreeEnsembleClassifier
```

### Urgency

We need this to be resolved urgently.

### Target platform

Linux

### Build script

./build.sh --config=MinSizeRel --build_shared_lib --build_java --disable_ml_ops --disable_exceptions --disable_rtti --include_ops_by_config rf.required_operators.config --enable_reduced_operator_type_support --skip_tests --minimal_build

### Error / output

Exception in thread "main" ai.onnxruntime.OrtException: Error code - ORT_NOT_IMPLEMENTED - message: Could not find an implementation for TreeEnsembleClassifier(1) node with name 'TreeEnsembleClassifier'

**Comment by edgchen1** [comment]
`ai.onnx.ml;5;TreeEnsembleClassifier`
This is a ML op, but you've passed the `--disable_ml_ops` option. Try removing that.

**Comment by Akash005Vengai** [comment]
Thank you @edgchen1
