### ISSUE TITLE
YOLO-6D-Pose model returning empty output

### ISSUE THREAD

**Issue by tv-gc** [microsoft/onnxruntime#19468]
### Describe the issue

Hi!

I am trying to run this github [https://github.com/TexasInstruments/edgeai-yolox/blob/main/README_6d_pose.md](https://github.com/TexasInstruments/edgeai-yolox/blob/main/README_6d_pose.md) onnx model (yolo_s_object_pose.onnx) but i am struggling to find the problem for the empty output result. (i am super green to onnxruntime)

![302986480-e627ed6e-d611-4785-8227-10bec16a8cca](https://github.com/microsoft/onnxruntime/assets/90689163/7013431b-401e-4523-bf40-7ee5ac205389)

The code is being tested and running in c# inside Unity (should not be the problem).

https://github.com/asus4/onnxruntime-unity-examples

A inference example for simple object detection works, the inference returns proper values and bounding boxes can be created and placed, but as soon as i switch the onnx model to the one present in the github, it no longer works.
I have adapted the above repo to work with dynamic shapes but even then the output is empty.

I would like to kindly request help for this matter, what am i doing wrong?

My run code is as follow

   ```
 public virtual void Run(Texture texture)
    {
        // Pre process
        preprocessPerfMarker.Begin();

        textureToTensor.Transform(texture, imageOptions.aspectMode);
        
        var inputSpan = inputs[0].GetTensorMutableDataAsSpan<T>();
        
        textureToTensor.TensorData.CopyTo(inputSpan);

        preprocessPerfMarker.End();

        // Run inference
        runPerfMarker.Begin();

        var outputs = session.Run(new RunOptions(), session.InputNames, inputs, session.OutputNames);
        var data = outputs[0].GetTensorDataAsSpan<float>();

        runPerfMarker.End();

        // Post process
        postprocessPerfMarker.Begin();
        //PostProcess();
        postprocessPerfMarker.End();
    }
```

Cheers!

### To reproduce

.

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

latest

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

TensorRT

**Comment by tianleiwu** [comment]
please refer this C# example:
https://github.com/microsoft/onnxruntime/blob/gh-pages/docs/tutorials/csharp/resnet50_csharp.md

I saw there is python demo for the model:
https://github.com/TexasInstruments/edgeai-yolox/blob/main/demo/ONNXRuntime/onnx_inference_object_pose.py
You may port it to C#, and make sure each intermediate output is same between C# and python.

**Comment by tv-gc** [comment]
Hi @tianleiwu 

I was aware of both those repos/examples but even then i am not able to make it work.
The inference works great with a "regular" object detection onnx file but this one with the 6d pose info always returns empty results.

May i ask for further assistance with this problem?

Thanks in advance
