### ISSUE TITLE
quantized model can not be loaded.

### ISSUE THREAD

**Issue by WilliamZhaoz** [microsoft/onnxruntime#1950]
I convert my pytorch model to a onnx model useing pytorch.onnx, then I can inference it in onnxruntime well, however then I quantized the onnx model to a quantized onnx model using onnxruntime, then I can not inference it with a error: Load model from xxx.onnx faild: This is an invalid model, Error in Node : : Node () has input size 1 not in range[min  =3, max=5]. I did not change anything, only quantized it. 
I use this tool quantized my model:
https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization
help my, how can I fix it.
Thanks.

**Comment by askhade** [comment]
Before using the tool make sure your model's opset version is set to 10. This is because when we quantize the model we need to update the opset version to 10 as the quantization ops were introduced in this version. 
You are seeing this error because your model has some other op which was also updated for version 10. 
I will submit a change to error check this case and report this... but this wont fix your problem... you will still need to update your model to opset 10 and then use the quantization tool

**Comment by WilliamZhaoz** [comment]
Hi Ashwini Khade,
Thank you, I converted my pytorch model to get the onnx model, so please
tell me how can I know which ops in pytorch is opset version 10?
thanks.

Ashwini Khade <notifications@github.com> 于2019年10月1日周二 上午3:38写道：

**Comment by faxu** [comment]
Re: Pytorch version - see their documentation ONNX export for setting opset_version - https://pytorch.org/docs/stable/onnx.html

You can also verify opsets by loading your ONNX model using a visualizer like Netron.

**Comment by WilliamZhaoz** [comment]
okay, thank you Faith,
BTW, can I  get inference acceleration when I inference quantized model
than before quantized?

Faith Xu <notifications@github.com> 于2019年10月4日周五 上午1:12写道：

**Comment by faxu** [comment]
Could you clarify your question? Quantization may result in some performance improvements at the expense of precision, though the current level of quantization support is still limited to just a few operators.

**Comment by WilliamZhaoz** [comment]
Yes, my question is: after I quantized my model, can I speed up my
inference process even though at the expense of precision, a faster
inference speed is more important than accuracy for me.
I guess the answer is yes as you said.

**Comment by WilliamZhaoz** [comment]
Hi Faith Xu,

you told me for Pytorch version: - see their documentation ONNX export for
setting opset_version - https://pytorch.org/docs/stable/onnx.html

Are the ops in this link is opset10? but I can converted my pytorch model
to onnx model using torch.onnx successfully, only for quantized model,
there are something wrong, so maybe my modle are already meeting the ops in
the link, but not for quantization tools.

please tell me how can I found the op in pytorch that quantization tools do
not support.

thanks.



Zhiyuan Zhao <zhiyuan.zhaochn@gmail.com> 于2019年10月8日周二 上午10:19写道：

> Yes, my question is: after I quantized my model, can I speed up my
> inference process even though at the expense of precision, a faster
> inference speed is more important than accuracy for me.
> I guess the answer is yes as you said.
>

**Comment by WilliamZhaoz** [comment]
Hi Faith Xu,
I saw the quantized model in Netron, there are many extra ops, e.g.
reduceMax/reduceMin/Sub/Div/Floor/Cast/QuantizeLinear, with those ops, I
can speed up my model inference process?
thanks.

Zhiyuan Zhao <zhiyuan.zhaochn@gmail.com> 于2019年10月8日周二 上午11:20写道：

> Hi Faith Xu,
>
> you told me for Pytorch version: - see their documentation ONNX export for
> setting opset_version - https://pytorch.org/docs/stable/onnx.html
>
> Are the ops in this link is opset10? but I can converted my pytorch model
> to onnx model using torch.onnx successfully, only for quantized model,
> there are something wrong, so maybe my modle are already meeting the ops in
> the link, but not for quantization tools.
>
> please tell me how can I found the op in pytorch that quantization tools
> do not support.
>
> thanks.
>
>
>
> Zhiyuan Zhao <zhiyuan.zhaochn@gmail.com> 于2019年10月8日周二 上午10:19写道：
>
>> Yes, my question is: after I quantized my model, can I speed up my
>> inference process even though at the expense of precision, a faster
>> inference speed is more important than accuracy for me.
>> I guess the answer is yes as you said.
>>
>

**Comment by askhade** [comment]
@WilliamZhaoz : These ops are added for dynamic quantization .i.e converting the input from FP32 to 8 bit during inference. In opset 11 we have added onnx functions to fuse these ops into 1 op "DynamicQuantizeLinear" This is a newly added function in opset 11 and you will need to covert your model to opset 11 first and then quantize it...

**Comment by askhade** [comment]
Currently the only way is to reconvert your model from original framework...

**Comment by faxu** [comment]
@WilliamZhaoz any other questions on this?
