### ISSUE TITLE
[Build] MAC static library 1.17.0 : very big in size

### ISSUE THREAD

**Issue by sarojlo** [microsoft/onnxruntime#19513]
### Describe the issue

- Compiled the code for MAC arm64/x64 , need static library , buildType minSizeRel
- Used libtool to stich all libraries 
 a. libtool -static -o libabsl.a libabsl_*.a
 b. libtool -static -o libonnxruntime_static.a libclog.a libcpuinfo.a libonnxruntime_optimizer.a libonnxruntime_util.a libonnxruntime_common.a libonnxruntime_flatbuffers.a libonnxruntime_framework.a libonnxruntime_graph.a libonnxruntime_mlas.a libonnxruntime_providers.a libflatbuffers.a libonnx.a libonnxruntime_session.a libonnx_proto.a libprotobuf-lite.a libre2.a libnsync_cpp.a libabsl.a

3. Resulted library is 1+GB

### Target platform

MAC

### Build script

python3 $(Build.SourcesDirectory)/onnxruntime/tools/ci_build/build.py --config MinSizeRel --skip_tests --build_dir MacOS --osx_arch $(platform) --use_xcode --parallel --apple_deploy_target 11.0

### Error / output

Built library are big

**Comment by sarojlo** [comment]
![image](https://github.com/microsoft/onnxruntime/assets/128089276/4b0bdcd1-88f4-489b-a10c-856710ae9efe)


i see liboonxruntime_providers is causing most of it

**Comment by skottmckay** [comment]
Guessing all the debug symbols are still there and you might need to use `strip` to remove them.

**Comment by sarojlo** [comment]
let me try that , but still overall size were not that big without striping in 1.14

**Comment by skottmckay** [comment]
You could use [bloaty](https://github.com/google/bloaty) to investigate further (requires the symbols though).

**Comment by skottmckay** [comment]
Assuming it was due to debug symbols. Re-open if further investigation is needed.
