### ISSUE TITLE
[Feature Request] limitation of coreml

### ISSUE THREAD

**Issue by x4080** [microsoft/onnxruntime#19543]
### Describe the feature request

I was using bge-m3 and when trying to use coreml, is returns "CoreML does not support input dim > 16384". Is it the limitation of my m2 (using m2pro) or coreml as general

I wondered if this will be supported in future (if not hardware limited)

Thanks

### Describe scenario use case

using bge-m3 onnx

**Comment by skottmckay** [comment]
I believe it's CoreML in general. 

https://github.com/apple/coremltools/issues/1003#issuecomment-1383236197

**Comment by x4080** [comment]
@skottmckay I see, thanks
