### ISSUE TITLE
[Mobile]  Android load native onnxruntime library failure, error message:   library "libdl.so.2" not found

### ISSUE THREAD

**Issue by Consulting4J** [microsoft/onnxruntime#19549]
### Describe the issue

Developing an Android kaldi based speech recognition application , onnxruntime is needed.
Kaldi is compiled with ndk, onnxruntime is packaged by Gradle, settings:

implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.17.0'

while loading  libonnxruntime.so, got a strange error:

  java.lang.UnsatisfiedLinkError: dlopen failed: library "libdl.so.2" not found: needed by /data/app/~~M97AqPToZDDX4w2dlXmVEw==bQ==/base.apk!/lib/arm64-v8a/libonnxruntime.so in namespace classloader-namespace

### To reproduce

loading libonnxruntime.so from Java layer
        System.loadLibrary("onnxruntime")
        System.loadLibrary("onnxruntime4j_jni")

got the following errors
 

 java.lang.UnsatisfiedLinkError: dlopen failed: library "libdl.so.2" not found: needed by /data/app/~~M97AqPToZDDX4w2dlXmVEw==bQ==/base.apk!/lib/arm64-v8a/libonnxruntime.so in namespace classloader-namespace
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)

### Platform

Android

### OS Version

13

### ONNX Runtime Installation

Other / Unknown

### Package Name (if 'Released Package')

onnxruntime-android

### ONNX Runtime Version or Commit ID

1.17.0 or 1.16.3

### ONNX Runtime API

C++/C

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by Consulting4J** [comment]
Process: com.xxx, PID: 5639
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: library "ld-linux-aarch64.so.1" not found: needed by /data/app/~~VGKItbtbwzeDAO5AYrmtTw==/com.xinteract-eaL9qsmdac4iht0Z99Z0WA==/base.apk!/lib/arm64-v8a/libonnxruntime.so in namespace classloader-namespace
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)

**Comment by skottmckay** [comment]
Not a Java expert, but if you're manually loading ORT instead of linking against it by adding the AAR to your app I assume you need to manually ensure that all dependencies are satisfied. 

Typical usage is to add a dependency on onnxruntime-android, which would show up in your build.gradle/build.gradle.kts like this

https://github.com/microsoft/onnxruntime-inference-examples/blob/33c9f0fab885c0ebbb220e3ef04b3dc4dd49402c/mobile/examples/object_detection/android/app/build.gradle#L48
```gradle
    implementation 'com.microsoft.onnxruntime:onnxruntime-android:latest.release'
```

**Comment by Craigacp** [comment]
The error is saying that the native library couldn't load some of the other native libraries it depends on. What version of Android are you running on, and is it different in some way from the standard one?

**Comment by snnn** [comment]
The library, "ld-linux-aarch64.so.1", is for Linux, not for Android.

**Comment by snnn** [comment]
It means the library "lib/arm64-v8a/libonnxruntime.so" was built for Linux, not Android.
