### ISSUE TITLE
I want to accelerate inference process using onnxruntime.

### ISSUE THREAD

**Issue by WilliamZhaoz** [microsoft/onnxruntime#1955]
I know there is a tool in onnxruntime can quantize a onnx model: 

https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization

But after quantization, I got the error as: 

https://github.com/microsoft/onnxruntime/issues/1950

Also, I wonder if I can get inference acceleration after quantization since there are some issues indicate that the inference can not be accelerated:
https://github.com/microsoft/onnxruntime/issues/1830
https://github.com/microsoft/onnxruntime/issues/1620

I’ll appreciate it if you can help me.

Thanks,

**Comment by faxu** [comment]
Quantization still has limited support, but can follow up on #1950 for your specific issue. 
Outside of that, please see this for guidance on perf tuning: https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Perf_Tuning.md

**Comment by WilliamZhaoz** [comment]
thank you Faith,
yep, the #1950 is also from me. ~~#
thanks for your perf tuning docs~


Faith Xu <notifications@github.com> 于2019年10月2日周三 上午12:56写道：
