### ISSUE TITLE
[Build] How to combine OPS config files to build aar package that supports multiple models?

### ISSUE THREAD

**Issue by shadowofsoul** [microsoft/onnxruntime#19572]
### Describe the issue

In cases as mine, where i need to use differents models in the same mobile app, i need to compile an unique `.aar` packagre for it, how i can combine 2 or more ops.config files (that are generated by the ort converter) and generate a valid packagre? Tried to combine them manually, adding missing ops from one file to another, but i'm getting errors at runtime as `ORT_NOT_IMPLEMENTED` when if i just compile a single `ops.config` file whiteout the extra ops, the model that was throwing the error works.

 i haven't found documentation about the config file structure generated by the ORT converter to be able to figure out this myself, so if anyone can point any hint about it, i'll appreciate.

### Target platform

Android

### Build script

python3 onnxruntime/tools/ci_build/github/android/build_aar_package.py --build_dir=/home/onnx/build --config=Release --allow_running_as_root --include_ops_by_config=/home/onnx/merged-ops.config /home/onnx/onnx-build-settings.json

### Error / output

ORT_NOT_IMPLEMENTED

**Comment by Eldow** [comment]
I'm interested in doing the same thing with 2 ops files generated from two different `.ort` models, did you achieve to merge two configuration files ?

**Comment by shadowofsoul** [comment]
> I'm interested in doing the same thing with 2 ops files generated from two different `.ort` models, did you achieve to merge two configuration files ?

Yep, pretty easy, just put X amount of ops file generated by the conversion script in a folder and run:

`onnxruntime/tools/python/create_reduced_build_config.py -f ORT FolderWithTheOPS NameOfFinal.ops.config`'

then you run the `build_aar_package.py` with that generated config file and that's it

**Comment by Eldow** [comment]
Thanks a lot, I just noticed it was in fact in [the documentation](https://onnxruntime.ai/docs/reference/operators/reduced-operator-config-file.html) 🤦
