### ISSUE TITLE
[Build]  macOS how to use cmke in clion

### ISSUE THREAD

**Issue by laogonggong847** [microsoft/onnxruntime#19598]
### Describe the issue

Hi, my Mac's CPU is Inter. I downloaded the corresponding file ([onnxruntime-osx-x86_64-1.17.0.tgz](https://github.com/microsoft/onnxruntime/releases/download/v1.17.0/onnxruntime-osx-x86_64-1.17.0.tgz)) from the official website.

The version I'm using is 1.16.3 and I unzipped it in the ```"/Users/Desktop/ORT1_16_3"``` path. The file structure is shown in the picture:

![f1ee4788394883320c8f8997a3384843](https://github.com/microsoft/onnxruntime/assets/81297486/0d937b1b-bd4b-45c8-9673-d2e391ca1bf0)

Now I want to use my onnxruntime in clion, how should I write the corresponding cmake file in clion so that I can make sure that I can use ort correctly in clion, I tried many times and found that all of them failed.

### Urgency

None

### Target platform

MacOS （CPU：Inter）

### Build script

cmake_minimum_required(VERSION 3.24)
project(OrtTest)

set(CMAKE_CXX_STANDARD 17)

set(ORT_DIR /Users/Desktop/ORT1_16_3)

set(SOURCE_FILES main.cpp)

add_executable(OrtTest main.cpp)
find_package(onnxruntime REQUIRED)
target_link_libraries(OrtTest ${onnxruntime_LIBS})
include_directories(${onnxruntime_INCLUDE_DIRS})

### Error / output

CMake Error at CMakeLists.txt:11 (find_package):
  By not providing "Findonnxruntime.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "onnxruntime", but CMake did not find one.

  Could not find a package configuration file provided by "onnxruntime" with
  any of the following names:

    onnxruntimeConfig.cmake
    onnxruntime-config.cmake

  Add the installation prefix of "onnxruntime" to CMAKE_PREFIX_PATH or set
  "onnxruntime_DIR" to a directory containing one of the above files.  If
  "onnxruntime" provides a separate development package or SDK, be sure it
  has been installed.

**Comment by skottmckay** [comment]
As we don't develop directly in CLion I'd suggest doing a search for some general documentation on either CMake, or alternatively using CLion with CMake to add dependencies on shared libraries. 

e.g.
https://cmake.org/cmake/help/latest/command/find_package.html
https://cmake.org/cmake/help/latest/guide/using-dependencies/index.html#guide:Using%20Dependencies%20Guide
