### ISSUE TITLE
[Documentation]  Wrong example for TensorRT Provider

### ISSUE THREAD

**Issue by developer0hye** [microsoft/onnxruntime#19641]
### Describe the documentation issue

![image](https://github.com/microsoft/onnxruntime/assets/35001605/4b75a525-d715-48d8-833d-c17b81b34294)

# Error

![image](https://github.com/microsoft/onnxruntime/assets/35001605/53652585-560a-4da3-92ac-3cb426d0963b)

# Solution

The example contains an error and should be corrected. Please change it to `session_options.AppendExecutionProvider_TensorRT_V2(*tensorrt_options);`.

### Page / URL

[execution-providers/TensorRT-ExecutionProvider.html](https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html)

**Comment by wangyems** [comment]
Thanks for the contribution!
