### ISSUE TITLE
[Documentation] Outdated doc for using xnnpackage 

### ISSUE THREAD

**Issue by csukuangfj** [microsoft/onnxruntime#19662]
### Describe the documentation issue

The following [link](https://onnxruntime.ai/docs/execution-providers/Xnnpack-ExecutionProvider.html#usage) says
```
Ort::Env env = Ort::Env{ORT_LOGGING_LEVEL_ERROR, "Default"};
Ort::SessionOptions so;
so.AppendExecutionProvider("XNNPACK", intra_op_num_threads);
Ort::Session session(env, model_path, so);
```

However, 
```
so.AppendExecutionProvider("XNNPACK", intra_op_num_threads);

```
is not valid anymore.

The latest code is
https://github.com/microsoft/onnxruntime/blob/5bb58a10e739f8720e9867d19c4313081b12d948/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L890-L892

The second argument is of type `const std::unordered_map<std::string, std::string>& `, not an `integer`.

### Page / URL

https://onnxruntime.ai/docs/execution-providers/Xnnpack-ExecutionProvider.html#usage

**Comment by wejoncy** [comment]
Thanks for your catching.

Could you please issue a PR for this?

**Comment by csukuangfj** [comment]
I find that
https://github.com/microsoft/onnxruntime/blob/gh-pages/docs/execution-providers/Xnnpack-ExecutionProvider.md
has already updated it.

However, the page at https://onnxruntime.ai/docs/execution-providers/Xnnpack-ExecutionProvider.html
does not show the latest change from `gh-pages`.

**Comment by wejoncy** [comment]
Hi @natke  Could you please have a look at it?

**Comment by natke** [comment]
Really weird. I did a manual rebuild and the same thing was published. I made a small change to the doc to trigger an automatic re-build, if you could review @wejoncy #19685

**Comment by natke** [comment]
Fixed by #19685

**Comment by wejoncy** [comment]
> Fixed the rendering of the snippet, if you could review @wejoncy #19685

Thanks

**Comment by wejoncy** [comment]
Closed as issue has been fixed.
