### ISSUE TITLE
FP16 model run failed

### ISSUE THREAD

**Issue by xiaowuhu** [microsoft/onnxruntime#19689]
### Describe the issue

One test case in OnnxConverter-Common was failed with ort 1.17. It works for ort 1.15.

The original model is here:
```python
        @onnx_function(outputs=['z'],
                       input_types=(_Ty.F([1, 1, 6, 1])),
                       output_types=[_Ty.f])
        def transpose_n_matmul(x):
            ox = x.ox  # type: OnnxOperatorBuilderX
            wm = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).astype(np.float32).reshape([2, 6])
            b = ox.constant(value=wm)
            a = ox.transpose(x, perm=[0, 1, 3, 2])
            c = ox.transpose(b, perm=[1, 0])
            m = ox.matmul([a, c])
            m_large = ox.mul([m, ox.constant(value=np.array(100, np.float32))])
            m_xlarge = ox.mul([m_large, ox.constant(value=np.array(10, np.float32))])
            mr = ox.reshape([m_xlarge], desired_shape=[2])
            mr = ox.reshape([mr], desired_shape=[2])
            m_normal = ox.div([mr, ox.constant(value=np.array(999, np.float32))])
            return m_normal 
```
```python
model = transpose_n_matmul.to_model()
onnx.save_model(model, "test32.onnx")
```
It can be run by using CPU execution provider.  The expected result is `array([112.112114, 2...e=float32)`.
In the test case, we assume every operators **cannot** handle float16 data, so we insert two cast operators between them: cast to 16, then cast back to 32. Bu the fp16 model return `[inf, inf]`.

### To reproduce

[test32to16.zip](https://github.com/microsoft/onnxruntime/files/14430664/test32to16.zip)

This zip file include both original fp32 model and fp16 model. You can use below data as input to test them.
```python
m1 = np.array([[2, 3], [4, 5], [6, 7]]).astype(np.float32).reshape([1, 1, 6, 1])
input_feed={'x': m1}
```

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by tianleiwu** [comment]
ORT 1.17 no longer removes Cast from high precision to lower precision data type (like fp32 to fp16 Cast). So, if fp32 value is beyond fp16 limit [-65504,66504] , it will become infinite.

Related issue: https://github.com/microsoft/onnxconverter-common/issues/271

**Comment by xiaowuhu** [comment]
This PR https://github.com/microsoft/onnxconverter-common/pull/286 resolve this issue.
