### ISSUE TITLE
[Web] Failed to load external data file "./model.onnx_data", error: File not found in preloaded files.

### ISSUE THREAD

**Issue by m4a1carbin4** [microsoft/onnxruntime#19739]
I'm currently working on [https://github.com/dakenf/diffusers.js](url) this repo to work with onnxruntime-web(especially for wasm)environment.

and I think external data load function needed to load SD 1.5~ SDXL models (over 2GB models) but when I load my onnx_data from indexedDB as a Uint8Array and create session with this options

```
externalData: [
        {
          data: new Uint8Array(weightsPathOrBuffer), 
          path: './' + weightsFilename, 
        },
      ],

```

but I always see 

```
Error: Can't create a session. ERROR_CODE: 1, ERROR_MESSAGE: Deserialize tensor onnx::MatMul_9307 failed.Failed to load external data file "./model.onnx_data", error: File not found in preloaded files.
```

this error in browser(chrome) (OS : Linux)

I don't have that specialized knowledge in this area so I'll be conducting further research and learning, but if anyone knows what's going to be the problem, could you please help...

**Comment by guschmue** [comment]
dakenf uses a custom build for onnxruntime as far I know and his app might not work with onnxruntime release or main. But it should be close. 
While sd-v1.5 needs 3.5GB or so the largest model is 1.7GB so external data is actually not needed.
sd-v1.5 should work with ort-1.17 or ort main but you might need to make a few changes to diffusers.js or the models he uses.
We have a super simple example for sd-turbo here:
https://github.com/microsoft/onnxruntime-inference-examples/tree/main/js/sd-turbo

**Comment by m4a1carbin4** [comment]
Well... but my ultimate goal is to use a merged model of my personal Lora, which I used on Python before, and when this model converted onnx through the optimum package, it had a model capacity of around 3.4G, so I needed an external data load method. 

However, if what I know is correct, it is clear that the model.onnx_data file was delivered to the external Data option in the form of Uint8Array through huggingface and checked through debugging, but it is very difficult to check why an error occurs in the session creation stage that the file cannot be found in the preloaded file.

So first of all, I'm trying to move away from the existing diffuser.js and start by writing a reproducible script.

Anyway, thank you for your answer and I will also check the example you gave me. Thank you.
