### ISSUE TITLE
C#: Add new InferenceSession(byte[] modelData, SessionOptions options) ctors

### ISSUE THREAD

**Issue by nietras** [microsoft/onnxruntime#1973]
C# API lacks the ability to create an `InferenceSession` from an array it seems. It only has two ctors:
```csharp
public InferenceSession(string modelPath);
public InferenceSession(string modelPath, SessionOptions options);
```
the C API has support for creating a session from an array:
```c
OrtStatus*(ORT_API_CALL* CreateSessionFromArray)(
    _In_ const OrtEnv* env, _In_ const void* model_data, size_t model_data_length,
    _In_ const OrtSessionOptions* options, _Outptr_ OrtSession** out)NO_EXCEPTION;
```
**System information**
- ONNX Runtime version (you are using): 0.5.0

**Describe the solution you'd like**
Add constructors:
```csharp
public InferenceSession(byte[] modelData);
public InferenceSession(byte[] modelData, SessionOptions options);
```

**Describe alternatives you've considered**
Saving byte array to file, but this is inefficient and cumbersome.

I would be happy to contribute this myself.

**Comment by nietras** [comment]
It appears this has been added to master :) 8 days ago in #1883, when will this be release?

https://github.com/microsoft/onnxruntime/blob/622ea4248df1531eb527a12818743395474c47c1/csharp/src/Microsoft.ML.OnnxRuntime/InferenceSession.cs#L49-L67

**Comment by faxu** [comment]
The next release should be in about a month.

**Comment by nietras** [comment]
Is there a CI nuget feed with pre-releases? A month is a long time.

**Comment by faxu** [comment]
we don't have a nuget feed with pre-releases at this time but will keep this request in mind. You'll have to build from the master branch branch for now.
