### ISSUE TITLE
Including ONNX file  in windows form application c#

### ISSUE THREAD

**Issue by amuthalingeswaranbose** [microsoft/onnxruntime#1974]
**Is your feature request related to a problem? Please describe.**
I have trained a deep learning model of Mask RCNN in Keras and have derived  a OnnX model (weight matrix) which is able to run and test images in Python successfully. I need to use the same ONNX model in Windows form Application, C# through visual studio.
**System information**
- ONNX Runtime version (you are using):
Mask RCNN, in ONNX Runtime v0.5.0

**Describe the solution you'd like**
I should be use the model and test images in Windows form application, C#.

**Describe alternatives you've considered**

**Additional context**

**Comment by faxu** [comment]
See https://github.com/microsoft/onnxruntime/blob/master/docs/CSharp_API.md#getting-started

Alternatively, if you're running on newer versions of Windows 10 and your model does not use the most recent opsets, you can try: https://docs.microsoft.com/en-us/windows/ai/windows-ml/index

**Comment by amuthalingeswaranbose** [comment]
I have two queries
**Number - 1.**
I referred the link  https://github.com/microsoft/onnxruntime/blob/master/docs/CSharp_API.md#getting-started as you mentioned. I tried using the code sample mentioned there.

I initialized the inference session with below statement . 
var session = new InferenceSession("model.onnx");

following that i used the below code. 

Tensor<float> t1, t2;  // let's say data is fed into the Tensor objects
var inputs = new List<NamedOnnxValue>()
             {
                NamedOnnxValue.CreateFromTensor<float>("name1", t1),
                NamedOnnxValue.CreateFromTensor<float>("name2", t2)
             };
using (var results = session.Run(inputs))
{
    // manipulate the results
}

but  it throws an error in the below line
NamedOnnxValue.CreateFromTensor<float>("name1", t1) 
saying use of unassigned values t1.

**Number - 2.**

my input is image. 
how do I give it as a input in the above scenario?

thank in advance you help.

**Comment by jignparm** [comment]
@amuthalingeswaranbose ,  have a look at the [full example here](https://github.com/microsoft/onnxruntime/tree/master/csharp/sample/Microsoft.ML.OnnxRuntime.InferenceSample) and also the [unit tests here](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs#L159).

Images need to be converted to integer RGB values, stored in tensor objects. See the `LoadTensorFromFile()` and `LoadTensorFromFilePb()` functions as examples of how to populate tensors from  file sources. You can use the `BitMap` class to populate the tensor from an image instead.

**Comment by jignparm** [comment]
Closing out -- please reopen if you have additional questions.
