### ISSUE TITLE
Segmentation fault(core dumped)

### ISSUE THREAD

**Issue by pzy2000** [microsoft/onnxruntime#19798]
### Describe the issue

when loading a resnet50_based model with ort.InferenceSession(path), it crashed.

### To reproduce

import onnxruntime as ort
model_path = "resnet50-imagenet_origin-Edge2-NLAll4-MDtype12-LMerg27-MDtype87.onnx"
session = ort.InferenceSession(model_path)

the onnx file is here:https://drive.google.com/file/d/1mJyINggxDdFLEPl-ExOk1h2agIg8C1cK/view?usp=sharing

### Platform

Linux

### OS Version

ubuntu 20.04.4

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.14.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by pranavsharma** [comment]
Have you tried the latest version of ORT?

**Comment by pzy2000** [comment]
I just tried in ORT latest version, it's okay now, thank u!
