### ISSUE TITLE
[Web] model output is incorrect with webgpu

### ISSUE THREAD

**Issue by nagadomi** [microsoft/onnxruntime#19816]
### Describe the issue

I have various denoising/super-resolution models and they all work fine with wasm, but not with webgpu.
With webgpu, the output value seems to be very large and clipped at the last Clip node.

### To reproduce

[webgpu_denoise_test.zip](https://github.com/microsoft/onnxruntime/files/14519546/webgpu_denoise_test.zip)
The zip file contains two small onnx models, test image, and the html and javascript to run them.

Screenshots of the results
![vgg7_wasm](https://github.com/microsoft/onnxruntime/assets/287255/1a102dee-4124-4587-ac99-8b0972681686)
![vgg7_webgpu](https://github.com/microsoft/onnxruntime/assets/287255/ba432095-0c02-4947-8483-734cea44dd49)
![cunet_wasm](https://github.com/microsoft/onnxruntime/assets/287255/227356c2-e5ad-4bb8-962c-b89996cd7503)
![cunet_webgpu](https://github.com/microsoft/onnxruntime/assets/287255/b5b0b6d4-7d72-48e9-b0c7-be0f0e47146e)

vgg7_noise0.onnx is a simple model, using only Conv2d, LeakyReLU, and Clip.
Also, I am testing with google-chrome on Linux. If the issue is not reproduced, that may be the cause.

### Urgency

I am not in a hurry to solve the problem. I am currently using wasm.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.1

### Execution Provider

'webgpu' (WebGPU)

**Comment by fs-eire** [comment]
This issue is fixed in latest @dev package.

Please get this fix by replacing the URL
"//cdn.jsdelivr.net/npm/onnxruntime-web@1.17.1/dist/ort.webgpu.min.js"
to
"//cdn.jsdelivr.net/npm/onnxruntime-web@dev/dist/ort.webgpu.min.js"

**Comment by nagadomi** [comment]
Thank you for the fix.
I confirmed that the difference between wasm and webgpu results is practically the same.
