### ISSUE TITLE
Set device_id by UpdateCUDAProviderOptionsWithValue not working

### ISSUE THREAD

**Issue by Colysia** [microsoft/onnxruntime#19827]
### Describe the issue

There are two gpus in my machine:
  0: RTX 3080
  1: A4000
When I set device_id by `UpdateCUDAProviderOptionsWithValue`(Method 1), it always run on GPU 0 whether I set device = 0 or 1, or I use `UpdateCUDAProviderOptionsWithValue(cudaOption, "device_id", deviceId.data())` or `UpdateCUDAProviderOptionsWithValue(cudaOption, "device_id", &device)`.
While The `UpdateCUDAProviderOptions`(Method 2) and set `OrtCUDAProviderOptions.device_id`(Method 3) work well.

How should I set up the GPU correctly using Method 1

### To reproduce

```
auto env = Ort::Env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING, "Default");
Ort::SessionOptions sessionOptions;
int device = 1;
std::vector<std::string> providers = Ort::GetAvailableProviders();
std::string deviceId = std::to_string(device);
if (device >= 0 && std::count(providers.begin(), providers.end(), "CUDAExecutionProvider")) {
#if ORT_API_VERSION >= 16
  // Method 1
  OrtCUDAProviderOptionsV2* cudaOption = nullptr;
  Ort::ThrowOnError(Ort::GetApi().CreateCUDAProviderOptions(&cudaOption));
  Ort::ThrowOnError(Ort::GetApi().UpdateCUDAProviderOptionsWithValue(cudaOption, "device_id", deviceId.data()));
  // Ort::ThrowOnError(Ort::GetApi().UpdateCUDAProviderOptionsWithValue(cudaOption, "device_id", &device));
  sessionOptions.AppendExecutionProvider_CUDA_V2(*cudaOption);
  Ort::GetApi().ReleaseCUDAProviderOptions(cudaOption);
#elif ORT_API_VERSION >= 12
  // Method 2
  OrtCUDAProviderOptionsV2* cudaOption = nullptr;
  Ort::ThrowOnError(Ort::GetApi().CreateCUDAProviderOptions(&cudaOption));
  std::vector<const char*> keys{"device_id"};
  std::vector<const char*> values{deviceId.data()};
  Ort::ThrowOnError(Ort::GetApi().UpdateCUDAProviderOptions(cudaOption, keys.data(), values.data(), keys.size()));
  sessionOptions.AppendExecutionProvider_CUDA_V2(*cudaOption);
  Ort::GetApi().ReleaseCUDAProviderOptions(cudaOption);
#else
  // Method 3
  OrtCUDAProviderOptions cudaOption;
  cudaOption.device_id = device;
  sessionOptions.AppendExecutionProvider_CUDA(cudaOption);
#endif
}
```

### Platform

Windows

### OS Version

Windows 11 23H2 22631.3235

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 12.1

**Comment by tianleiwu** [comment]
Please look at example in doc:
https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#cc

**Comment by Colysia** [comment]
> Please look at example in doc:请看文档中的示例： https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#cc

Thanks, based on the examples in this document and past issues, I found that the method `UpdateCUDAProviderOptionsWithValue` seems to be an interface designed specifically for setting compute stream. Does this mean that other parameters cannot be set through it?

**Comment by Colysia** [comment]
> @Colysia, your understanding is correct. UpdateCUDAProviderOptionsWithValue only handles user_compute_stream for now.
> 
> See related code:
> 
> https://github.com/microsoft/onnxruntime/blob/efad5bbc5aed1717200d3e8f6ddd253394af4b99/onnxruntime/core/session/provider_bridge_ort.cc#L2332-L2350
> 
> In UpdateCUDAProviderOptionsWithValue, the value is a pointer.
> 
> In UpdateCUDAProviderOptions, the value of each option is a string. UpdateCUDAProviderOptions can handle all options including device_id and user_compute_stream: user_compute_stream need to cast pointer to unsigned long, then convert the address to a string.

Thanks a lot, I will close this issue.
