### ISSUE TITLE
Can't import onnx gradle dependencies in android 

### ISSUE THREAD

**Issue by Asalerm** [microsoft/onnxruntime#19828]
Good day guyss!!!

I have added this in my project as a dependency 
```
implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.11.0'
```

But the problem is I cant access it using the below code
```
from jnius import autoclass

# Importing the necessary classes
OnnxRuntime = autoclass('com.microsoft.onnxruntime.OnnxRuntime')
```

When i tried to asses it, it says class not found

Please help

**Comment by Asalerm** [comment]
It says class not found.

All i am trying to do is to asses it from pyjnius.

I did the same with other dependencies and they work. 

But for Onnx i couldn't find it class path or name.

**Comment by Asalerm** [comment]
> `com.microsoft.onnxruntime.OnnxRuntime` is package private, so you shouldn't be able to import it if pyjnius is respecting the Java language rules. Can you import `OrtEnvironment` or `OrtSession`?

I have to assess it first

**Comment by Craigacp** [comment]
Oh wait. The package name is `ai.onnxruntime.OnnxRuntime`, try that.

**Comment by Asalerm** [comment]
> Oh wait. The package name is `ai.onnxruntime.OnnxRuntime`, try that.

Thanks Allot bro. 

May God help you as well

**Comment by Asalerm** [comment]
```
from jnius import autoclass 

# Load necessary classes using JNI 

OnnxRuntime = autoclass('ai.onnxruntime.OnnxRuntime') 

# Access the InferenceSession class 


InferenceSession = OnnxRuntime.InferenceSession 


# Access the capi._pybind_state class pybind_state = OnnxRuntime.capi._pybind_state 
```



I can import InferenceSesseion and capi._pybind_state in macos or windows or ubuntu but dont know how to import them in android
All i am trying to do is to load model.onnx in android and use it.
The way I use the model was i only use onnxruntime.InferenceSession and capi._pybind_state

**Comment by Craigacp** [comment]
The Java API is not the same as the Python API due to differences in language idioms and resource management. There are examples of the Java API  https://onnxruntime.ai/docs/get-started/with-java.html and https://github.com/Oracle/sd4j.

**Comment by Asalerm** [comment]
The problem is that, I uses opencv-python  and numpy all for this model.onnx calculations so I don't know how to integrate it with onnxruntime of android, it will be confusing.

But if you can suggest to me how can I compile it to java to execute in android I will really appreciate so.

**Comment by Craigacp** [comment]
OpenCV has a Java API too, and depending what you're doing you might be able to push the openCV computations down into the ONNX graph. But I don't know much about python development on Android, nor pyjnius. I would guess that if you need it to work on Android it would be easier to write the computation in Java/Kotlin or C++ (using the Android NDK), rather than have a Python VM running next to the Android runtime.

**Comment by Asalerm** [comment]
The problem is that, I uses opencv-python  and numpy all for this model.onnx calculations so I don't know how to integrate it with onnxruntime of android, it will be confusing.

But if you can suggest to me how can I compile it to java to execute in android I will really appreciate so.

**Comment by Asalerm** [comment]
Also why cant i import OrtSession but I can only import 

```

from jnius import autoclass

OrtErrorCode = autoclass('ai.onnxruntime.OnnxRuntime$OrtSession')

```

**Comment by Craigacp** [comment]
Did you try `ai.onnxruntime.OrtSession` etc? The classes need to be prefixed with the package name just like in Python.

**Comment by Asalerm** [comment]
Thanks allot bro!!!

I am grabbing things now. I am understanding how the dependency works. I will ask you again when I get stuck again.
