### ISSUE TITLE
[Bug] onnx shape inference result in an infinite loop

### ISSUE THREAD

**Issue by inisis** [microsoft/onnxruntime#19870]
### Describe the issue

described as title

### To reproduce

model is provided [here](http://lyg.blockelite.cn:15030/aifarm/onnx/pnasnet5large.onnx)

import onnxruntime.tools.symbolic_shape_infer as onnxrt_symbolic_shape_inference

model = onnx.load('pnasnet5large.onnx')
model = (onnxrt_symbolic_shape_inference.SymbolicShapeInference.infer_shapes(model, auto_merge=True))

### Platform

Linux

### OS Version

ubuntu 1804

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by tianleiwu** [comment]
@ inisis, the model you uploaded does not have symbolic inputs. 
There is no issue in onnx shape inference:
```python
import onnx
onnx.shape_inference.infer_shapes_path('pnasnet5large.onnx', 'pnasnet5large_shape.onnx')
```

I can also run symbolic shape inference successfully:
```console
python -m onnxruntime.tools.symbolic_shape_infer --input pnasnet5large.onnx --output pnasnet5large_sym_shape.onnx --auto_merge
```

**Comment by inisis** [comment]
> @inisis the model you uploaded does not have symbolic inputs. There is no issue in onnx shape inference:
> 
> ```python
> import onnx
> onnx.shape_inference.infer_shapes_path('pnasnet5large.onnx', 'pnasnet5large_shape.onnx')
> ```
> 
> I can also run symbolic shape inference successfully (using a build from the main branch):
> 
> ```
> python -m onnxruntime.tools.symbolic_shape_infer --input pnasnet5large.onnx --output pnasnet5large_sym_shape.onnx --auto_merge
> ```

Hi, the uploaded model is incorrect, could you please redownload it, I have checked it myself. Thanks

**Comment by inisis** [comment]
close as merged
