### ISSUE TITLE
./onnxruntime_server: No such file or directory

### ISSUE THREAD

**Issue by ajinkya933** [microsoft/onnxruntime#1989]
**Describe the bug**
1) I installed go

2) In the ONNX Runtime root folder, run ./build.sh --config RelWithDebInfo --build_server --use_openmp --parallel

From the root folder when I type 

```
~/Documents/onnxruntime$ ./onnxruntime_server

I get an error:

bash: ./onnxruntime_server: No such file or directory
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 0.5.0
- Python version: 3.6
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**To Reproduce**
1) I installed go

2) In the ONNX Runtime root folder, run ./build.sh --config RelWithDebInfo --build_server --use_openmp --parallel

From the root folder  type 

```
$ ./onnxruntime_server
```

**Expected behavior**
```
$ ./onnxruntime_server
Version: <Build number>
Commit ID: <The latest commit ID>

the option '--model_path' is required but missing
Allowed options:
  -h [ --help ]                Shows a help message and exits
  --log_level arg (=info)      Logging level. Allowed options (case sensitive):
                               verbose, info, warning, error, fatal
  --model_path arg             Path to ONNX model
  --address arg (=0.0.0.0)     The base HTTP address
  --http_port arg (=8001)      HTTP port to listen to requests
  --num_http_threads arg (=<# of your cpu cores>) Number of http threads
  --grpc_port arg (=50051)     GRPC port to listen to requests
```

**Comment by NonStatic2014** [comment]
Would you mind double check if `onnxruntime_server` is under `build/Linux/RelWithDebInfo` folder? If the build succeeded, you should be able to run it in that folder.

**Comment by csteegz** [comment]
You should be able to run the server with
```
 ~/src/onnxruntime$ ./build/Linux/RelWithDebInfo/onnxruntime_server
```

Is there a document that made you expect the server to be published in the root directory that we can update?

**Comment by ajinkya933** [comment]
@csteegz  your solution solves the issue,as a first time user I coudn't locate this file
