### ISSUE TITLE
Wrong OrtApi size for v1.17.0/v1.17.1 ?

### ISSUE THREAD

**Issue by Hopobcn** [microsoft/onnxruntime#19893]
### Describe the issue

Hi, first of all sorry if this is already tracked.

I was scanning `onnxruntime_c_api.cc` for v1.17.0 and I have noticed that the protection against `OrtApi` modifications:

```
static_assert(offsetof(OrtApi, SetUserLoggingFunction) / sizeof(void*) == 266, "Size of version 17 API cannot change");
```

looks wrong for v1.17.0

https://github.com/microsoft/onnxruntime/blob/v1.17.0/onnxruntime/core/session/onnxruntime_c_api.cc#L2717

```
    &OrtApis::SetUserLoggingFunction,                            <-- it's pointing here
    &OrtApis::ShapeInferContext_GetInputCount,
    &OrtApis::ShapeInferContext_GetInputTypeShape,
    &OrtApis::ShapeInferContext_GetAttribute,
    &OrtApis::ShapeInferContext_SetOutputTypeShape,
    &OrtApis::SetSymbolicDimensions,
    &OrtApis::ReadOpAttr,
    &OrtApis::SetDeterministicCompute,
    &OrtApis::KernelContext_ParallelFor,
    &OrtApis::SessionOptionsAppendExecutionProvider_OpenVINO_V2, <-- should point here
    // End of Version 17                                         <-- comment is missing?
};
```

v1.17.1 looks to be the same.

### To reproduce

No sepecific step. Just compare last function in OrtApi https://github.com/microsoft/onnxruntime/blob/v1.17.0/onnxruntime/core/session/onnxruntime_c_api.cc#L2726 with the static_assert https://github.com/microsoft/onnxruntime/blob/v1.17.1/onnxruntime/core/session/onnxruntime_c_api.cc#L2756

### Platform

Windows

### OS Version

any

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

v1.17.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by YUNQIUGUO** [comment]
Looks like a bunch of new C OrtApis are introduced in 1.17.0 time frame, however the static assert sanity check has not been updated along the prs. 

Got a fix pr.
