### ISSUE TITLE
Could not build solution.!!

### ISSUE THREAD

**Issue by hy846130226** [microsoft/onnxruntime#19890]
### Describe the issue

I pull the V1.6.3 code.
and use the following command: **.\build.bat --cudnn_home  "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8" --use_tensorrt --tensorrt_home “C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\TensorRT-8.6.1.6” --cmake_generator "Visual Studio 17 2022"**

but when I got the solution, I COULD NOT build the **nvonnxparser_static** project

![image](https://github.com/microsoft/onnxruntime/assets/67405690/a627bc94-d899-4fc7-8288-bf62713705a8)

### Target platform

C++

### Build script

.\build.bat --cudnn_home  "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8" --use_tensorrt --tensorrt_home “C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\TensorRT-8.6.1.6” --cmake_generator "Visual Studio 17 2022"

### Error / output

C2664	“bool google::protobuf::TextFormat::Parse(google::protobuf::io::ZeroCopyInputStream *,google::protobuf::Message *)”: could not transfrom “onnx::ModelProto *” into “google::protobuf::Message *”	nvonnxparser_static	D:\onnxruntime\onnxruntime\build\Windows\Debug\_deps\onnx_tensorrt-src\ModelImporter.cpp	358

**Comment by jywu-msft** [comment]
please build RelWithDebInfo or Release flavor.

**Comment by jywu-msft** [comment]
@yf711 can you check if Debug build has new issues?

**Comment by hy846130226** [comment]
Thanks for your help @jywu-msft !
The release version build successful.
But I also have a question:

I use the nuget package to load the onnxruntime-gpu version 1.16.3, and I could see the folder like:
![image](https://github.com/microsoft/onnxruntime/assets/67405690/78f9854e-d9ca-4a72-b8b5-9d8708466dd5)

My question is: 
How could I build the 1.16.3 onnxruntime.dll&onnxruntime.lib?

**Comment by hy846130226** [comment]
> @hy846130226 You can build ORT with `--build_shared_lib` to generate onnxruntime.dll/lib
> 
> Actually, I tried your command to build ORT in debug mode and it passed on my side. One thing to call out, if you would like to use open-sourced onnx-tensorrt parser, please add `--use_tensorrt_oss_parser` to your ORT build command. The default behavior without this arg will be using built-in parser from your tensorrt 8.6 binary

Hi @yf711,

I do not know "You can build ORT with --build_shared_lib to generate onnxruntime.dll/lib", could you please tell me more details or what should I do?

thank you very much!

**Comment by hy846130226** [comment]
> @hy846130226 You can build ORT with `--build_shared_lib` to generate onnxruntime.dll/lib
> 
> Actually, I tried your command to build ORT in debug mode and it passed on my side. One thing to call out, if you would like to use open-sourced onnx-tensorrt parser, please add `--use_tensorrt_oss_parser` to your ORT build command. The default behavior without this arg will be using built-in parser from your tensorrt 8.6 binary

Hi @yf711,
thank you very much!

I do not know "You can build ORT with --build_shared_lib to generate onnxruntime.dll/lib", could you please tell me more details or what should I do?

.\build.bat --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8" --use_tensorrt --tensorrt_home “C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\TensorRT-8.6.1.6” --cmake_generator "Visual Studio 17 2022" --buildshared_lib

Is this your means?

**Comment by hy846130226** [comment]
> @hy846130226 You can build ORT with `--build_shared_lib` to generate onnxruntime.dll/lib
> 
> Actually, I tried your command to build ORT in debug mode and it passed on my side. One thing to call out, if you would like to use open-sourced onnx-tensorrt parser, please add `--use_tensorrt_oss_parser` to your ORT build command. The default behavior without this arg will be using built-in parser from your tensorrt 8.6 binary

And my tensorrt version is 8.6.1.6, according to the official onnxruntime website, "The TensorRT execution provider for ONNX Runtime is built and tested with TensorRT 8.6.".

So I don't think I should use the "--use_tensorrt_oss_parser" command

**Comment by hy846130226** [comment]
> @hy846130226 You can build ORT with `--build_shared_lib` to generate onnxruntime.dll/lib
> 
> Actually, I tried your command to build ORT in debug mode and it passed on my side. One thing to call out, if you would like to use open-sourced onnx-tensorrt parser, please add `--use_tensorrt_oss_parser` to your ORT build command. The default behavior without this arg will be using built-in parser from your tensorrt 8.6 binary

And my tensorrt version is 8.6.1.6, according to the official onnxruntime website, "The TensorRT execution provider for ONNX Runtime is built and tested with TensorRT 8.6.".

So I don't think I should use the "--use_tensorrt_oss_parser" command

**Comment by hy846130226** [comment]
Here is the folder snapshot after I build ALL_BUILD:
![image](https://github.com/microsoft/onnxruntime/assets/67405690/0eab5cc3-44d5-4432-a9d5-f4eaeadc0932)
**There is no onnxruntime.dll&onnxruntime.lib?**

**Comment by hy846130226** [comment]
Hi @yf711,

Thanks for your help.
I have resolved this problem according to your words!
