### ISSUE TITLE
Nuphar tutorial - minimize the amount of steps needed to compare a users RNN/LSTM model with Nuphar and CPU EP

### ISSUE THREAD

**Issue by RagingBull630** [microsoft/onnxruntime#1994]
Currently, there are too many steps for a user to go through to compare their model with Nuphar and default EP. 

Goal = to reduce the burden/steps to get to the necessary data points for a user to make a decision on which EP performs best for their given model.

**Comment by KeDengMS** [comment]
Please take a look at the updated [Nuphar tutorial notebook](https://github.com/microsoft/onnxruntime/blob/master/docs/python/notebooks/onnxruntime-nuphar-tutorial.ipynb), which includes examples of BERT squad and GPT-2 to show how to use Nuphar step-by-step. Quantization is optional, both BERT and GPT-2 do not have that while still get benefit from Nuphar.

**Comment by faxu** [comment]
Closing this issue. Please reopen if there are still changes needed or issues.
