### ISSUE TITLE
Invalid rank for input,Got: 1 Expected: 4

### ISSUE THREAD

**Issue by w1005444804** [microsoft/onnxruntime#19953]
### Describe the issue

"Invalid rank for input: image_embeddings Got: 1 Expected: 4 Please fix either the inputs/outputs or the model". however the image_embeddings dims is 1 256 64 64.and print it out as it should be。the onnx model come from SAM(segment anthing), actually it belong to the decoder model.and 5 inputs。dynamic reshape.

print out as below:
has_mask_input dims: 1
tensor dims: 1
image_embeddings dims: 1 256 64 64
tensor dims: 1 256 64 64
mask_input dims: 1 1 256 256
tensor dims: 1 1 256 256
point_coords dims: 32 2 2
tensor dims: 32 2 2
point_labels dims: 32 2
tensor dims: 32 2
Invalid rank for input: image_embeddings Got: 1 Expected: 4 Please fix either the inputs/outputs or the model.

### To reproduce

std::vector<OrtValue *> input_tensors;
		std::vector<OrtValue *> output_tensors;
		output_tensors.resize(m_output_node_names.size());
		for (auto it : m_inputs)
		{
			OrtValue *input_tensor = nullptr;
			OrtValue *output_tensor = nullptr;
			OrtMemoryInfo *memory_info;
			if (!CheckStatus(m_engine->CreateCpuMemoryInfo(OrtArenaAllocator, OrtMemTypeDefault, &memory_info)))
			{
				std::cerr << "EROOR: CreateCpuMemoryInfo failed" << std::endl;
				return false;
			}
			std::shared_ptr<Datum> &datumptr = it.second.datumptr;
			void *input_data = datumptr->get_mutable_data();
			size_t data_len = datumptr->get_shape().count() * datumptr->get_ele_bytes();
			int64_t *pshape = it.second.dims.data();
			size_t shape_len = it.second.num_dims;
			if (!CheckStatus(m_engine->CreateTensorWithDataAsOrtValue(memory_info, input_data,
																	  data_len, pshape, shape_len, it.second.type, &input_tensor)))
			{
				std::cerr << "EROOR: CreateTensorWithDataAsOrtValue failed" << std::endl;
				return false;
			}
			int is_tensor;
			if (!CheckStatus(m_engine->IsTensor(input_tensor, &is_tensor)))
			{
				std::cerr << "EROOR: IsTensor failed" << std::endl;
				return false;
			}
			std::cout << it.first << " dims: ";
			for (size_t k = 0; k < it.second.num_dims; k++)
			{
				std::cout << it.second.dims[k] << " ";
			}
			std::cout << std::endl;
			printTensorInfo(input_tensor);

			input_tensors.push_back(input_tensor);
			m_engine->ReleaseMemoryInfo(memory_info);
		}
		/*--------------------------------------------------------------------------------*/
		
		if (!CheckStatus(m_engine->Run(m_session, NULL,
									   m_input_node_names.data(), input_tensors.data(), input_tensors.size(),
									   m_output_node_names.data(), m_output_node_names.size(), output_tensors.data())))
		{
			std::cerr << "EROOR: Run failed" << std::endl;
			return false;
		}

### Platform

Windows

### OS Version

win10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

onnxruntime-win-x64-gpu-1.17.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA11.3

**Comment by yuslepukhin** [comment]
Without the model, there is nothing to go with. I speculate that you have a model with dynamic shapes input, and those dynamic shapes propagate down the stream until it hits a node that is not capable of handling certain dynamic shapes.

**Comment by w1005444804** [comment]
@yuslepukhin This is the onnx model I'm using. Can you help me take a look? This model has been successfully tested on both Tensorrt and OpenVino。
https://1drv.ms/u/s!AiUWQdHY2o7gh4hWGti_dM9Sn_9oJg?e=HzXJ3U

**Comment by w1005444804** [comment]
![1711019225788](https://github.com/microsoft/onnxruntime/assets/6340026/9026be05-b3e5-4eb1-a37d-4862c7c59fb4)
![1711019681065](https://github.com/microsoft/onnxruntime/assets/6340026/bddbb27d-b77d-49f8-a52e-9b6bd7b22a4d)

**Comment by w1005444804** [comment]
bool ORT::doInference()
	{
		std::vector<OrtValue *> input_tensors;
		std::vector<OrtValue *> output_tensors;
		output_tensors.resize(m_output_node_names.size());
		for (auto it : m_inputs)
		{
			OrtValue *input_tensor = nullptr;
			OrtValue *output_tensor = nullptr;
			OrtMemoryInfo *memory_info;
			if (!CheckStatus(m_engine->CreateCpuMemoryInfo(OrtArenaAllocator, OrtMemTypeDefault, &memory_info)))
			{
				std::cerr << "EROOR: CreateCpuMemoryInfo failed" << std::endl;
				return false;
			}
			std::shared_ptr<Datum> &datumptr = it.second.datumptr;
			void *input_data = datumptr->get_mutable_data();
			size_t data_len = datumptr->get_shape().count() * datumptr->get_ele_bytes();
			int64_t *pshape = it.second.dims.data();
			size_t shape_len = it.second.num_dims;
			if (!CheckStatus(m_engine->CreateTensorWithDataAsOrtValue(memory_info, input_data,
																	  data_len, pshape, shape_len, it.second.type, &input_tensor)))
			{
				std::cerr << "EROOR: CreateTensorWithDataAsOrtValue failed" << std::endl;
				return false;
			}
			int is_tensor;
			if (!CheckStatus(m_engine->IsTensor(input_tensor, &is_tensor)))
			{
				std::cerr << "EROOR: IsTensor failed" << std::endl;
				return false;
			}
			std::cout << it.first << " dims: ";
			for (size_t k = 0; k < it.second.num_dims; k++)
			{
				std::cout << it.second.dims[k] << " ";
			}
			std::cout << std::endl;
			printTensorInfo(input_tensor);

			input_tensors.push_back(input_tensor);
			m_engine->ReleaseMemoryInfo(memory_info);
		}
		/*--------------------------------------------------------------------------------*/
		
		if (!CheckStatus(m_engine->Run(m_session, NULL,
									   m_input_node_names.data(), input_tensors.data(), input_tensors.size(),
									   m_output_node_names.data(), m_output_node_names.size(), output_tensors.data())))
		{
			std::cerr << "EROOR: Run failed" << std::endl;
			return false;
		}
		/*--------------------------------------------------------------------------------*/
		for (size_t i = 0; i < m_output_node_names.size(); i++)
		{
			OrtValue *output_tensor = output_tensors[i];
			int is_tensor;
			if (!CheckStatus(m_engine->IsTensor(output_tensors[i], &is_tensor)))
			{
				std::cerr << "EROOR: IsTensor failed" << std::endl;
				return false;
			}
			if (!is_tensor)
			{
				return false;
			}
			void *outputdata;
			if (!CheckStatus(m_engine->GetTensorMutableData(output_tensors[i], &outputdata)))
			{
				std::cerr << "EROOR: GetTensorMutableData failed" << std::endl;
				return false;
			}
			// 获取模型输出的shape
			OrtTypeInfo *typeinfo;
			m_engine->GetTypeInfo(output_tensor, &typeinfo);

			const OrtTensorTypeAndShapeInfo *tensor_info;
			CheckStatus(m_engine->CastTypeInfoToTensorInfo(typeinfo, &tensor_info));
			ONNXTensorElementDataType type;
			CheckStatus(m_engine->GetTensorElementType(tensor_info, &type));
			int bytes = 4;
			if (type == ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT)
			{
				bytes = 4;
			}
			else if (type == ONNX_TENSOR_ELEMENT_DATA_TYPE_UINT8)
			{
				bytes = 1;
			}
			else
			{
				std::cerr << "EROOR: Unkown data type: " << type << std::endl;
				return false;
			}
			// printf("Input %zu : type=%d\n", 0, type);
			size_t num_dims;
			CheckStatus(m_engine->GetDimensionsCount(tensor_info, &num_dims));
			// printf("Output %zu : num_dims=%zu\n", 0, num_dims);
			m_outputs[m_output_node_names[i]].num_dims = num_dims;
			m_outputs[m_output_node_names[i]].dims.resize(num_dims);
			m_engine->GetDimensions(tensor_info, (int64_t *)(m_outputs[m_output_node_names[i]].dims.data()), num_dims);
			Shape output_shape;
			dims2shape(m_outputs[m_output_node_names[i]].dims, output_shape);
			bool isok = m_outputs[m_output_node_names[i]].datumptr->reshape(output_shape);
			if (!isok)
			{
				m_outputs[m_output_node_names[i]].datumptr->create(output_shape, type);
			}
			memcpy(m_outputs[m_output_node_names[i]].datumptr->get_mutable_data(), outputdata, output_shape.count() * bytes);

			m_engine->ReleaseValue(output_tensor);
		}
		return true;
	}
