### ISSUE TITLE
Windows 11 Runtime Issue

### ISSUE THREAD

**Issue by CyberBearSec** [microsoft/onnxruntime#20001]
### Describe the issue

I have Windows 10/11 (Windows 10 Pro that I upgraded to Windows 11 Pro).  When I run my python code, using langchain to query ChatGPT based on passed in documents, I keep getting the warning:

`onnxruntime_validation.py:26: UserWarning: Unsupported Windows version (11). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn(
`

I don't really care about that, per se, but I am now getting a circular reference error that makes absolutely zero sense.

`An error occurred: Circular reference detected on line <traceback object at 0x0000027FDC728440>
Error in tracing queue
Traceback (most recent call last):
  File "I:\My Drive\AI\Moss Masher\venv\Lib\site-packages\langsmith\client.py", line 4112, in _tracing_thread_handle_batch
    client.batch_ingest_runs(create=create, update=update, pre_sampled=True)
  File "I:\My Drive\AI\Moss Masher\venv\Lib\site-packages\langsmith\client.py", line 1220, in batch_ingest_runs
    "post": [_dumps_json(run) for run in raw_body["post"]],
[MossMasher.zip](https://github.com/microsoft/onnxruntime/files/14672678/MossMasher.zip)

             ^^^^^^^^^^^^^^^^
  File "I:\My Drive\AI\Moss Masher\venv\Lib\site-packages\langsmith\client.py", line 236, in _dumps_json
    return _dumps_json_single(obj, functools.partial(_serialize_json, depth=depth))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\My Drive\AI\Moss Masher\venv\Lib\site-packages\langsmith\client.py", line 211, in _dumps_json_single
    return orjson.dumps(
           ^^^^^^^^^^^^^
`
I have attached the script which is dumb simple but still not working.  This might have nothing to do with onnxruntime and, if not, I apologize for the entry.

### To reproduce

run python -m streamlit MossMasher.py wherever you download the file.

### Platform

Windows

### OS Version

Windows 11 Pro 21H2

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.17.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by mszhanyi** [comment]
There is a PR fixed it.
https://github.com/microsoft/onnxruntime/pull/19845.
We'll add it in the next release.
Sorry for your inconvenience, could you build ORT from source.

**Comment by CyberBearSec** [comment]
No worries – thank you for responding!

**Comment by BatuhanKostik** [comment]
Is there no workaround to use ONNX Runtime in windows 11?

**Comment by snnn** [comment]
It is just a warning, does not impact use.
