### ISSUE TITLE
[Build] add_library cannot create ALIAS target "nsync::nsync_cpp" because target   "nsync_cpp" does not already exist

### ISSUE THREAD

**Issue by yurivict** [microsoft/onnxruntime#20031]
### Describe the issue

This is because nsync-1.26.0 doesn't install any cmake scripts.

### Target platform

FreeBSD 14.0

### Build script

cmake .

### Error / output

```
CMake Error at external/onnxruntime_external_deps.cmake:327 (add_library):
  add_library cannot create ALIAS target "nsync::nsync_cpp" because target
  "nsync_cpp" does not already exist.
Call Stack (most recent call first):
  CMakeLists.txt:575 (include)


CMake Error at external/onnxruntime_external_deps.cmake:328 (target_include_directories):
  Cannot specify include directories for target "nsync_cpp" which is not
  built by this project.
Call Stack (most recent call first):
  CMakeLists.txt:575 (include)
```

### GCC / Compiler Version

clang-16

**Comment by snnn** [comment]
@pranavsharma , can we consider deprecating this library? We may use [absl](https://abseil.io/docs/cpp/guides/synchronization) instead.

**Comment by pranavsharma** [comment]
> @pranavsharma , can we consider deprecating this library? We may use [absl](https://abseil.io/docs/cpp/guides/synchronization) instead. So that one less thing to maintain.

sure, yeah, one less headache.

**Comment by snnn** [comment]
Thanks. I will make a PR.

**Comment by snnn** [comment]
I am working on it.

**Comment by snnn** [comment]
#20413

**Comment by snnn** [comment]
nsync is removed.
