### ISSUE TITLE
[Build] Build ORT ON Centos7.6 for CPU EP is Error

### ISSUE THREAD

**Issue by KnightYao** [microsoft/onnxruntime#20055]
### Describe the issue

build on centos and use gcc 10.2, build cpu ep, is error

### Target platform

Centos 7.6

### Build script

sh build.sh --config Release --parallel 48 --skip_submodule_sync --minimal_build

### Error / output

![微信截图_20240325103417](https://github.com/microsoft/onnxruntime/assets/9350796/a9de7548-7b86-47c1-951f-583d683c1ce8)

### GCC / Compiler Version

gcc 10.2.0

**Comment by mszhanyi** [comment]
Since [End dates are coming in 2024 for CentOS Stream 8 and CentOS Linux 7.](https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/),  Could you try building it on Ubuntu 2022 or [Redhat UBI](https://catalog.redhat.com/software/base-images).

**Comment by csukuangfj** [comment]
@KnightYao 

I suggest that you have a look at
https://github.com/csukuangfj/onnxruntime-libs/releases

We provide pre-built onnxruntime libraries for CentOS 7

For instance, the following ones:

- https://github.com/csukuangfj/onnxruntime-libs/releases/download/v1.19.0/onnxruntime-linux-x64-glibc2_17-Release-1.19.0.zip

- https://github.com/csukuangfj/onnxruntime-libs/releases/download/v1.19.2/onnxruntime-linux-aarch64-glibc2_17-Release-1.19.2.zip

**Comment by joey9503** [comment]
> [@KnightYao](https://github.com/KnightYao)
> 
> I suggest that you have a look at https://github.com/csukuangfj/onnxruntime-libs/releases
> 
> We provide pre-built onnxruntime libraries for CentOS 7
> 
> For instance, the following ones:
> 
> * https://github.com/csukuangfj/onnxruntime-libs/releases/download/v1.19.0/onnxruntime-linux-x64-glibc2_17-Release-1.19.0.zip
> * https://github.com/csukuangfj/onnxruntime-libs/releases/download/v1.19.2/onnxruntime-linux-aarch64-glibc2_17-Release-1.19.2.zip

@csukuangfj hi, my requirement is to import onnxruntime in Python code and perform inference. So, I need a .whl package to use with pip install onnxruntime. I have already downloaded the centos7 pre-built onnxruntime. What should I do next?
