### ISSUE TITLE
RandomUniformLike produces non-deterministic behavior everytime InferenceSession().run is called

### ISSUE THREAD

**Issue by waelrabah11** [microsoft/onnxruntime#20054]
### Describe the issue

Some context behind this:
We have a quantum machine learning library inspired from scikit-learn. We implement custom algorithms and then we recently decided to use `skl2onnx` to export our trained models as onnx models. We provide the onnx model to our clients, and they can use an `InferenceSession` for predictions.

I am trying to reproduce this numpy code: 
```
    rng = np.random.default_rng(0)
    choice=rng.choice([-1, 1])
```
using onnx operators and I landed on this:
```
        container.add_node(
            "RandomUniformLike",
            inputs=[zero_label_elements],
            outputs=[random_var],
            name=scope.get_unique_operator_name("random"),
            low=-1.0,
            high=1.0,
            seed=float(random_state),
        )
``` 
I get the desired effect of sampling random numbers that are in the discrete set: {-1, 1}
I am using an inference session to make predictions:
```
p = inference_session.run(None, {"X": x.astype(np.float32)})
```

However, if I call `inference_session.run` multiple times in a row then I get different results:
```
p1 = inference_session.run(None, {"X": x.astype(np.float32)})
p2 = inference_session.run(None, {"X": x.astype(np.float32)})
p3= inference_session.run(None, {"X": x.astype(np.float32)})

# p1, p2, p3 will all be different
```

The problem is that the random number generator doesn't reset with every time the `run` method is called. 
Is it possible to force a manual reseed every time `run` is called ?

We found this helpful for obfuscation of how our algorithms and training protocols work.

### To reproduce

Unfortunately, I can't share the complete code due to intellectual property restrictions.

### Urgency

It's not urgent. I want to understand if this an expected behaviour or is this a limitation of the product ??

### Platform

Linux

### OS Version

ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.0

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by tianleiwu** [comment]
I agree. It looks like bug - the result shall be deterministic when seed is provided. The cause is the random generator is created in constructor: https://github.com/microsoft/onnxruntime/blob/7d976cf72098639b0c8427629bef797861497ea9/onnxruntime/core/providers/cpu/generator/random.h#L148
To fix it, the generator shall be seeded in Compute function. Feel free to contribute a fix.

**Comment by waelrabah11** [comment]
> Some users expect the result to be deterministic when seed is provided. The cause of current behavior is the seed of random generator is used in constructor instead of Compute function:
> 
> https://github.com/microsoft/onnxruntime/blob/7d976cf72098639b0c8427629bef797861497ea9/onnxruntime/core/providers/cpu/generator/random.h#L148
> 
> @liqunfu, @skottmckay, I saw your PR #477. Any comment on this issue?

Thanks @tianleiwu for your input! Based on [the GitHub pull request](https://github.com/microsoft/onnxruntime/pull/477), it seems your team aims for the Compute function to generate different random values on each call, rather than always returning the same deterministic output. To be honest, I'm not sure if this is a desired behavior in a production machine learning model. We usually want the model to be a blackbox that takes input `x`and returns the same output `y` every time.

**Comment by skottmckay** [comment]
It doesn't quite make sense to me to set the seed in Compute. I believe that would make the node return the same set of values every single time it's used. It seems like using an initializer might be better for this behavior instead of a Random* node.

**Comment by waelrabah11** [comment]
Thank you guys for the responses and the suggestions. We decided to remove the use of `RandomUniformLike` from our onnx converter. It doesn't seem that this is a bug on your side so I'm gonna go ahead and close this issue. 
Thanks !
