### ISSUE TITLE
OpenVINO: Encountered unknown exception in Run()

### ISSUE THREAD

**Issue by mertalev** [microsoft/onnxruntime#20069]
### Describe the issue

When using OpenVINO, the session can be created, but calling `run` leads to the error: `RuntimeException: [ONNXRuntimeError] RUNTIME_EXCEPTION: Encountered unknown exception`. Based on reports in [this](https://github.com/immich-app/immich/issues/8226) issue, there seems to be a pattern with the N100 CPU in particular.

This seems to be a regression as this error only appears after upgrading to 1.17.1 of onnxruntime-openvino with OpenVINO 2023.3.0. This model worked when using 1.15.0 and OpenVINO 2023.1.0.

After enabling the following environmental variables:
```
ORT_OPENVINO_ENABLE_CI_LOG=1
ORT_OPENVINO_ENABLE_DEBUG=1
OPENVINO_LOG_LEVEL=5
```
There are a few additional logs, but none that seem pertinent:
```
In the OpenVINO EP
Model is fully supported on OpenVINO
CreateNgraphFunc
```

### To reproduce

With onnxruntime-openvino 1.17.1 and OpenVINO 2023.3.0, create a session including the following providers:
```python
['OpenVINOExecutionProvider', 'CPUExecutionProvider']
```
And the following provider options:
```python
[{'device_type': 'GPU_FP32', 'cache_dir': '/tmp/facial-recognition/buffalo_l/openvino'}, {'arena_extend_strategy': 'kSameAsRequested'}] 
```
Then attempt to run inference with [this](https://huggingface.co/immich-app/buffalo_l/resolve/main/detection/model.onnx) model. It may or may not work depending on the CPU.

You may use this image to have the exact software environment producing the issue: `ghcr.io/immich-app/immich-machine-learning@sha256:01799596c7f40495887d4027df1c0f4c144c7cd6ab34937ef2cc14d246470095`

### Platform

Linux

### OS Version

Ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

OpenVINO

### Execution Provider Library Version

2023.3.0

**Comment by jywu-msft** [comment]
+@sfatimar , @preetha-intel

**Comment by Disty0** [comment]
Having the same error using this model: https://huggingface.co/SmilingWolf/wd-swinv2-tagger-v3
Other variants of this model (convnext and vit)  runs fine but swinv2 fails with the following log:

Only execution provider options is `{'device_type': 'GPU_FP32'}`

```
2024-03-29 20:30:00,068 - __main__ - INFO - loading onnx model: /mnt/DataSSD/AI/models/wd14_tagger_model/SmilingWolf_wd-swinv2-tagger-v3/model.onnx
In the OpenVINO EP
CreateNgraphFunc
CreateNgraphFunc
CreateNgraphFunc
CreateNgraphFunc
CreateNgraphFunc
2024-03-29 20:30:01.866096452 [W:onnxruntime:, session_state.cc:1166 VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2024-03-29 20:30:01.866111062 [W:onnxruntime:, session_state.cc:1168 VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
2024-03-29 20:30:02,360 - __main__ - INFO - found 151 images.
  0%|                                                                                                                                                                                                                 | 0/151 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/DataSSD/AI/Apps/rocm/kohya_ss/sd-scripts/finetune/tag_images_by_wd14_tagger.py", line 448, in <module>
    main(args)
  File "/mnt/DataSSD/AI/Apps/rocm/kohya_ss/sd-scripts/finetune/tag_images_by_wd14_tagger.py", line 321, in main
    run_batch(b_imgs)
  File "/mnt/DataSSD/AI/Apps/rocm/kohya_ss/sd-scripts/finetune/tag_images_by_wd14_tagger.py", line 199, in run_batch
    probs = ort_sess.run(None, {input_name: imgs})[0]  # onnx output numpy
  File "/mnt/DataSSD/AI/Apps/ipex/kohya_ss/venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Encountered unknown exception in Run()
```

**Comment by sfatimar** [comment]
Yes there is a regression Binary DLL uploaded in github.com/intel/onnxruntime for  1.17.1  onnxruntime-openvino is compatible only with OpenVINO 2023.3.0.
There was a change in  Exception API on OpenVINO which was not handled properly so backward compatibility was broken. But it is possible to build 1.17.1 code with OpenVINO 2023.1.0 and execute ...

**Comment by Disty0** [comment]
I tried buıilding from the main branch (commit id: a2998e5d425d48f83f817f6503c6bd196e2cb3ae) and it runs fine now.

Had to use OpenVINO 2023.3 since building with 2024.0 segfaulted on import.
Ran into the same issue as https://github.com/intel/neural-speed/issues/188 and had to add `--compile_no_warning_as_error` arg to build.sh.

**Comment by mertalev** [comment]
> Yes there is a regression Binary DLL uploaded in github.com/intel/onnxruntime for  1.17.1  onnxruntime-openvino is compatible only with OpenVINO 2023.3.0.
> 
> There was a change in  Exception API on OpenVINO which was not handled properly so backward compatibility was broken. But it is possible to build 1.17.1 code with OpenVINO 2023.1.0 and execute ...

To clarify, the issue is occurring with 2023.3.0. The pattern I'm seeing is that it works on CPUs with Iris Xe graphics, but not on CPUs with UHD graphics.

**Comment by Snuupy** [comment]
> there seems to be a pattern with the N100 CPU in particular.

It's also broken on my N5095, so likely broken on N5105, N95, N97, etc., any cpu with UHD graphics

**Comment by shummo** [comment]
Is it possible to DOWNGRADE to  1.15.0 onnxruntime-openvino with OpenVINO 2023.1.0? If yes, how (sorry but I"m not an expert) Thanks

**Comment by henryruhs** [comment]
I have to confirm, that this is an existing issue that breaks OpenVINO using Intel Arc (770) under Windows.

@shummo A downgrade to `onnxruntime==1.15.0` and `openvino=2023.1.0` solved it

**Comment by ankitm3k** [comment]
> ### Describe the issue
> When using OpenVINO, the session can be created, but calling `run` leads to the error: `RuntimeException: [ONNXRuntimeError] RUNTIME_EXCEPTION: Encountered unknown exception`. Based on reports in [this](https://github.com/immich-app/immich/issues/8226) issue, there seems to be a pattern with the N100 CPU in particular.
> 
> This seems to be a regression as this error only appears after upgrading to 1.17.1 of onnxruntime-openvino with OpenVINO 2023.3.0. This model worked when using 1.15.0 and OpenVINO 2023.1.0.
> 
> After enabling the following environmental variables:
> 
> ```
> ORT_OPENVINO_ENABLE_CI_LOG=1
> ORT_OPENVINO_ENABLE_DEBUG=1
> OPENVINO_LOG_LEVEL=5
> ```
> 
> There are a few additional logs, but none that seem pertinent:
> 
> ```
> In the OpenVINO EP
> Model is fully supported on OpenVINO
> CreateNgraphFunc
> ```
> 
> ### To reproduce
> With onnxruntime-openvino 1.17.1 and OpenVINO 2023.3.0, create a session including the following providers:
> 
> ```python
> ['OpenVINOExecutionProvider', 'CPUExecutionProvider']
> ```
> 
> And the following provider options:
> 
> ```python
> [{'device_type': 'GPU_FP32', 'cache_dir': '/tmp/facial-recognition/buffalo_l/openvino'}, {'arena_extend_strategy': 'kSameAsRequested'}] 
> ```
> 
> Then attempt to run inference with [this](https://huggingface.co/immich-app/buffalo_l/resolve/main/detection/model.onnx) model. It may or may not work depending on the CPU.
> 
> You may use this image to have the exact software environment producing the issue: `ghcr.io/immich-app/immich-machine-learning@sha256:01799596c7f40495887d4027df1c0f4c144c7cd6ab34937ef2cc14d246470095`
> 
> ### Urgency
> _No response_
> 
> ### Platform
> Linux
> 
> ### OS Version
> Ubuntu 22.04
> 
> ### ONNX Runtime Installation
> Released Package
> 
> ### ONNX Runtime Version or Commit ID
> 1.17.1
> 
> ### ONNX Runtime API
> Python
> 
> ### Architecture
> X64
> 
> ### Execution Provider
> OpenVINO
> 
> ### Execution Provider Library Version
> 2023.3.0

Hi @mertalev, I have tested your model  [this](https://huggingface.co/immich-app/buffalo_l/resolve/main/detection/model.onnx) and it's inferencing successfully on both Windows 11 and Ubuntu 22.04 for CPU and GPU. I would recommend you and community towards using latest OpenVINO Toolkit [v2024.1](https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html?VERSION=v_2024_1_0&OP_SYSTEM=WINDOWS&DISTRIBUTION=ARCHIVE) and OpenVINO EP v1.18.0 which will be available soon in the upcoming ONNXRuntime release. You can also build and find OpenVINO EP from source for the same.

**Comment by mertalev** [comment]
Thanks for the testing and update! We'll upgrade to 1.18.0 and 2024.1.0 once the former is available.

When you mention that it works on GPU, can you clarify if you tested with an iGPU like UHD Graphics, or a dGPU like Arc (and I believe Iris Xe is also counted as a dGPU). iGPUs struggle, but I haven't seen anyone with a dGPU have an issue with this model.

**Comment by ankitm3k** [comment]
> Thanks for the testing and update! We'll upgrade to 1.18.0 and 2024.1.0 once the former is available.
> 
> When you mention that it works on GPU, can you clarify if you tested with an iGPU like UHD Graphics, or a dGPU like Arc (and I believe Iris Xe is also counted as a dGPU). iGPUs struggle, but I haven't seen anyone with a dGPU have an issue with this model.

It's tested on a Meteor Lake architecture processor CPU (Intel Core Ultra 7 1003H) comprising of iGPU (Intel Arc Graphics). I'd recommend you to try your application on multiple platforms. As suggested above, you can also use the main branch of this repository to build OpenVINO EP to get the latest wheels for your work environment and reproduce the same.

**Comment by Snuupy** [comment]
Thanks for the update! 

> It's tested on a Meteor Lake architecture processor CPU (Intel Core Ultra 7 1003H) comprising of iGPU (Intel Arc Graphics).

Hi, could you please add Intel UHD graphics to your list of test cases/testing setup because it is currently broken on that (but not XE graphics, so if it works on your testing setup, this may still be broken)

**Comment by henryruhs** [comment]
@ankitm3k No, onnxruntime-openvino does not work with latest OpenVino 2024.1 ... stop claiming it does

**Comment by ankitm3k** [comment]
> Thanks for the testing and update! We'll upgrade to 1.18.0 and 2024.1.0 once the former is available.
> 
> When you mention that it works on GPU, can you clarify if you tested with an iGPU like UHD Graphics, or a dGPU like Arc (and I believe Iris Xe is also counted as a dGPU). iGPUs struggle, but I haven't seen anyone with a dGPU have an issue with this model.

Hi @mertalev @Snuupy 

I have tested you model with our C++ onnxruntime_perf_test app built from source and it runs inference successfully with below machine configurations -
Machine 1 -
OS: Windows 11
CPU: Raptor Lake arch
iGPU: Intel UHD Graphics 770
dGPU: Intel Arc A380 Graphics

Machine 2 -
OS: Windows 11
CPU: i7-1270P
iGPU: Intel Iris Xe Graphics 

I'd recommend you to use either intel's repo master  or rel-1.18.0 (https://github.com/intel/onnxruntime.git) or directly from Microsoft's master branch (https://github.com/microsoft/onnxruntime.git) or rel-1.18.0 (https://github.com/microsoft/onnxruntime/commits/rel-1.18.0/) for building the wheels using below command -

![image](https://github.com/microsoft/onnxruntime/assets/76202494/1a980aef-2d28-410d-a86d-b139e802af74)

Discover the wheel in below example path and install using pip -
pip install ${CWD}\onnxruntime\build\Windows\Debug\Debug\dist\onnxruntime_openvino-1.19.0-cp310-cp310-win_amd64.whl

**Comment by Snuupy** [comment]
@ankitm3k

> I have tested your model with our C++ onnxruntime_perf_test app built from source and it runs inference successfully with below machine configurations - Machine 1 - OS: Windows 11 CPU: Raptor Lake arch iGPU: Intel UHD Graphics 770 dGPU: Intel Arc A380 Graphics

Doesn't onnxruntime default to the dgpu if one is provided? So it will run on the A380 and not the UHD 770 igpu that is broken.

I can try substituting 1.18 to see if that fixes anything regardless.

**Comment by ankitm3k** [comment]
> @ankitm3k
> 
> > I have tested your model with our C++ onnxruntime_perf_test app built from source and it runs inference successfully with below machine configurations - Machine 1 - OS: Windows 11 CPU: Raptor Lake arch iGPU: Intel UHD Graphics 770 dGPU: Intel Arc A380 Graphics
> 
> Doesn't onnxruntime default to the dgpu if one is provided? So it will run on the A380 (working) instead of the UHD 770 igpu (not working)
> 
> I can try substituting 1.18 to see if that fixes anything regardless.

The onnxruntime default device_type for GPU is iGPU (GPU.0) and if you want to explicitly use dGPU (GPU.1) then set your device _type as GPU.1 during your inference provider options.

**Comment by mertalev** [comment]
This particular issue has been fixed as far as I can tell.
