### ISSUE TITLE
error undefined reference to `OrtGetApi' in C++ when run on g++

### ISSUE THREAD

**Issue by luan1412167** [microsoft/onnxruntime#2007]
**Describe the bug**
Hi, I'm using onnx runtime to load onnx in C++. I have installed docker from source. However, when i run CXX_Api_Sample.cpp file by g++ then facing the following error:
`/onnxruntime/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp: In function 'int main(int, char**)':
/onnxruntime/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp:60:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (signed int i = 0; i < num_input_nodes; i++) {
                            ^
/onnxruntime/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp:76:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for ( int j = 0; j < input_node_dims.size(); j++)
                        ^
/tmp/cccNgi5D.o: In function __static_initialization_and_destruction_0(int, int)':
CXX_Api_Sample.cpp:(.text+0x892): undefined reference to OrtGetApi'
collect2: error: ld returned 1 exit status
`

I'm new, because I don't know this error is from where. I think that this line give out this error. But i'm not sure.
https://github.com/microsoft/onnxruntime/blob/74517bb7425b52fd15fef5cf4d4f476c1987e764/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp#L9

Help me solve it , thanks so much.

**Comment by hariharans29** [comment]
Can you take a look at https://github.com/microsoft/onnxruntime/issues/2081 and https://github.com/microsoft/onnxruntime/issues/1897 ? Please close this issue if that solves your issue. Thanks.

**Comment by SergeyJames** [comment]
The solution for me was **make install all**.
