### ISSUE TITLE
[Build] Latest release v1.17.1 code not building for Android 

### ISSUE THREAD

**Issue by harshakhmk** [microsoft/onnxruntime#20099]
### Describe the issue

I am trying to build the latest release v1.17.1 of onnxruntime for Android, but I was getting an error below
```
  /home/usr/onnxruntime/onnxruntime/core/mlas/lib/mlasi.h/366:11
Error unknown type name bfloat16_t did you mean float16_t
const bfloat16_t* B,

/home/usr/Android/Sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/14.0.1/include/arm_neon.h:43:16 note float16_t declared here
typedef __fp16 float16_t;

1 error generated
```

### Target platform

Android 

### Build script

./build.sh --android --android_sdk_path <> --android_ndk_path <> -- android_abi arm64-v8a --android_api 24

### Error / output

```
  /home/usr/onnxruntime/onnxruntime/core/mlas/lib/mlasi.h/366:11
Error unknown type name bfloat16_t did you mean float16_t
const bfloat16_t* B,

/home/usr/Android/Sdk/ndk/24.0.8215888/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/14.0.1/include/arm_neon.h:43:16 note float16_t declared here
typedef __fp16 float16_t;

1 error generated
```

**Comment by skottmckay** [comment]
Please use NDK 26 as it has a version of clang that handles the bfloat16 type.

**Comment by harshakhmk** [comment]
Thanks for the fix, I have built from source, build is successful
However I didn't see onnxruntime.so file being generated, but there are many other . So & .a files generated
libonnxruntime_graph.a
libonnxruntime_mlas.a
libonnxruntime. pc

**Comment by skottmckay** [comment]
`--build_shared_lib`

**Comment by harshakhmk** [comment]
Thanks it worked
