### ISSUE TITLE
[Build] ExternalProject failure in CMake

### ISSUE THREAD

**Issue by waarmond** [microsoft/onnxruntime#20129]
### Describe the issue

CMake configuration fails, an external project hash is not accepted by CMake (3.29.0)

### Target platform

ArchLinux

### Build script

`cmake -S onnxruntime/cmake -B build `
see https://gitlab.archlinux.org/archlinux/packaging/packages/onnxruntime/-/blob/main/PKGBUILD?ref_type=heads for full details

### Error / output

```
CMake Error at /usr/share/cmake/Modules/ExternalProject.cmake:3069 (message):
  URL_HASH is set to

    SHA1=85da3caa60eb2b148613b443fbc2bfdc30689965;add_library;(;nsync::nsync_cpp;ALIAS;nsync_cpp;)

  but must be ALGO=value where ALGO is

    MD5|SHA1|SHA224|SHA256|SHA384|SHA512|SHA3_224|SHA3_256|SHA3_384|SHA3_512

  and value is a hex string.
```

### GCC / Compiler Version

13.2.1

**Comment by edgchen1** [comment]
I noticed that this sed command has some of the same text that shows up in the bad URL_HASH value:
https://gitlab.archlinux.org/archlinux/packaging/packages/onnxruntime/-/blob/main/PKGBUILD?ref_type=heads#L72-75

Can you verify that the patched cmake/external/onnxruntime_external_deps.cmake file looks valid?

**Comment by snnn** [comment]
#20413

**Comment by snnn** [comment]
nsync is removed.
