### ISSUE TITLE
[Documentation] Misleading quantization information about dynamic quantization and QDQ

### ISSUE THREAD

**Issue by manickavela29** [microsoft/onnxruntime#20125]
### Describe the documentation issue

Quantization Representation Format [In Doc](https://github.com/microsoft/onnxruntime/blob/gh-pages/docs/performance/model-optimizations/quantization.md#static-quantization)

This section is not updated for the past 2 years,

Static quantization supports QDQ and QOperator format and Dynamic quantization only QOperator 
Also verified here https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/quantization/quantize.py

From what I have seen maybe a couple of years back there was support for dynamic and static quantization also but not anymore.

It is very misleading from doc point of view, when someone is trying to try quantization.
Please confirm if I am right, I will make the appropriate changes.

Thank you

https://github.com/microsoft/onnxruntime/blob/gh-pages/docs/performance/model-optimizations/quantization.md#onnx-quantization-representation-format

**Comment by yufenglee** [comment]
Static quantization supports both QDQ and QOperator. Dynamic quantization only supports QOperator.

**Comment by manickavela29** [comment]
yes, I typed it wrongly but rectified it,

under Tensor-Oriented,
below line is mentioned which is misleading.

> Models generated in the following ways are in the QDQ format:
> - Models quantized by quantize_static or **_quantize_dynamic API,_** explained below, with quant_format=QuantFormat.QDQ.
> - Quantization-Aware training (QAT) models converted from Tensorflow or exported from PyTorch.
> - Quantized models converted from TFLite and other frameworks.

**Comment by manickavela29** [comment]
Thank you!

**Comment by manickavela29** [comment]
Thank you!
