### ISSUE TITLE
Incompatability in C# with NuGet packages OnnxRuntime.GPU and OnnxTransformer 

### ISSUE THREAD

**Issue by mingzhao03** [microsoft/onnxruntime#2013]
**Describe the bug**
I am trying to run an onnx model in C# on GPU. I found that if I install NuGet packages Microsoft.ML.OnnxRuntime.Gpu (0.5.0) and Microsoft.ML.OnnxTransformer (1.3.1) together, I get the following exception:

System.EntryPointNotFoundException: 'Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in DLL 'onnxruntime'.'

when I try to create a `SessionOption`:

`var option = SessionOptions.MakeSessionOptionWithCudaProvider(); `

I tried this on two separate computers and both had the same error.

If I only have Microsoft.ML.OnnxRuntime.Gpu installed, the one line of code works fine creating the `SessionOptions` object. But once I add in the Microsoft.ML.OnnxTransformer package, I get the exception above.

**Urgency**
This prevents us from using ML.NET in our application. I am using Transforms.ApplyOnnxModel to consume our model, so I need to be able to reference Microsoft.ML.OnnxTransformer. At the moment my model works on the CPU with Microsoft.ML.OnnxRuntime, but inference on CPU is way too slow to be of any use.

**System information**  (First computer / second computer when applicable)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7 professional / Windows 10 professional
- ONNX Runtime installed from (source or binary): NuGet packages
- ONNX Runtime version: v0.5.0 Microsoft.ML.OnnxRuntime.Gpu, v1.3.1 Microsoft.ML.OnnxTransformer
- Python version: 3.6.5 / 3.7.3 Anaconda distribution
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA 10.0.130, cuDNN 7.3.0.29
- GPU model and memory: NVidia Quadro K620 / NVidia Quadro P2000

**To Reproduce**
1. Create new C# console app targeting .Net core 3.0. 
2. Use NuGet Package Manager to install Microsoft.ML, Microsoft.ML.OnnxRuntime.Gpu and Microsoft.ML.OnnxTransformer.
3. Add the following line to the main method.
`            var option = SessionOptions.MakeSessionOptionWithCudaProvider();`
4. Start debugging. => "System.EntryPointNotFoundException".

**Expected behavior**
Microsoft.ML.OnnxRuntime.Gpu and Microsoft.ML.OnnxTransformer should be able to function properly together.

**Screenshots**
![ml_onnx](https://user-images.githubusercontent.com/43101410/66233737-a5657380-e6b1-11e9-87e3-cc965bd9d686.png)

**Additional context**

**Comment by jignparm** [comment]
Installing Microsoft.ML.OnnxTransformer 1.3.1, will install the  Microsoft.ML.OnnxRuntime package as a dependency, which only contains the CPU API(no GPU API).

This is why you're seeing the error message "System.EntryPointNotFoundException".

The Microsoft.ML.OnnxRuntime.Gpu package provides access to CUDA GPUs,  but there's no Microsoft.ML.OnnxTransformer package which relies on it.

ML.NET will need to publish a GPU version of OnnxTransformer which pulls in the relevant OnnxRuntime package. 

As a workaround, can you the OnnxRuntime package directly for your application? Or do you need to use ML.NET for other functionality?

Microsoft.ML.Onnx
![image](https://user-images.githubusercontent.com/13698702/66248644-2d617280-e6de-11e9-93e5-bfce27a30c0e.png)

**Comment by mingzhao03** [comment]
@jignparm Thanks a lot for the reply. That makes sense. I will try to see if I can get around having to use the OnnxTransformer module. Since this is caused by the coupling of the module with a single runtime, would this be a problem with the MKL backend as well? 

So I guess this issue would turn into a feature request. Please make the OnnxTransformer module support GPU runtime, otherwise the module becomes borderline useless for any deep learning models that takes too long to run on CPUs.

**Comment by jignparm** [comment]
>Since this is caused by the coupling of the module with a single runtime, would this be a problem with the MKL backend as well?

The Microsoft.ML.OnnxRuntime.MKLML package would have the same issue as the Microsoft.ML.OnnxRuntime package.

>Please make the OnnxTransformer module support GPU runtime, otherwise the module becomes borderline useless for any deep learning models that takes too long to run on CPUs.

Another option, if you want to try out OnnxTransformer with GPU capabilities, is to build a local ML.NET OnnxTransformer  package from source which depends on the OnnxRuntime.Gpu package. Modify the package name and versions below, and rebuild. This may not be sufficient for production scenarios, but would let you test out GPU performance via ML.NET.

```
$ find . -type f -not -name \*.cs | xargs git grep -i onnxruntime
build/Dependencies.props:    <MicrosoftMLOnnxRuntimePackageVersion>0.4.0</MicrosoftMLOnnxRuntimePackageVersion>
pkg/Microsoft.ML.OnnxTransformer/Microsoft.ML.OnnxTransformer.nupkgproj:    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="$(MicrosoftMLOnnxRuntimePackageVersion)"/>
src/Microsoft.ML.OnnxTransformer/Microsoft.ML.OnnxTransformer.csproj:    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="$(MicrosoftMLOnnxRuntimePackageVersion)" />



```

**Comment by mingzhao03** [comment]
@jignparm Thanks a lot for your help. I got my model working with OnnxRuntime.GPU through InferenceSession.Run instead of using OnnxTransformer. The inference speed is similar (maybe a little bit slower) to what I get with Tensorflow/Keras so that's good enough for my application at the moment. 

Still, it would be nice if some future version of OnnxTransformer can use GPU right out of the box. Since I didn't directly resolve this problem but just found a workaround, I don't think I should close this issue. Moderators please feel free to change the status as you see fit.

**Comment by jignparm** [comment]
>Still, it would be nice if some future version of OnnxTransformer can use GPU

The OnnxTransformer package is generated from the ML.NET repository here https://github.com/dotnet/machinelearning.

Please open up a new feature request/issue for ML.NET for tracking purposes.

I'll close out this particular issue for OnnxRuntime since it's not a bug. Reopen if you have any questions.

**Comment by donaldhessing** [comment]
I'm having exactly the same issue when trying Microsoft.ML.OnnxTransformer 1.4.0. I tried to run the OnnxObjectDetection sample with GPU support by using ApplyOnnxModel(onnxModel.ModelOutput, onnxModel.ModelInput, onnxModel.ModelPath, 1, true));.

I'm supprised this is marked as feature request while Microsoft.ML.OnnxTransformer 1.4.0 containS an overload method for GPU and CPU fallback. 

public static Microsoft.ML.Transforms.Onnx.OnnxScoringEstimator ApplyOnnxModel (this Microsoft.ML.TransformsCatalog catalog, string modelFile, Nullable<int> gpuDeviceId = null, bool fallbackToCpu = false);

Enviroment:
OS Platform: Windows 10 professional build 1809
ONNX Runtime: 1.4.0
Visual Studio version (if applicable): 2019
CUDA/cuDNN version: CUDA 10.0.130, cuDNN 7.6.0.34
GPU model and memory: NVidia Quadro P1000

**Failing code:**
var pipeline = mlContext.Transforms.ResizeImages(resizing: ImageResizingEstimator.ResizingKind.Fill, outputColumnName: onnxModel.ModelInput, imageWidth: ImageSettings.imageWidth, imageHeight: ImageSettings.imageHeight, inputColumnName: nameof(ImageInputData.Image))
                            .Append(mlContext.Transforms.ExtractPixels(outputColumnName: onnxModel.ModelInput))
                            .Append(mlContext.Transforms.ApplyOnnxModel(onnxModel.ModelOutput, onnxModel.ModelInput, onnxModel.ModelPath, 1, true));

**Exception:** 
System.EntryPointNotFoundException: 'Unable to find an entry point named 'OrtSessionOptionsAppendExecutionProvider_CUDA' in DLL 'onnxruntime'.'

I noticed that ML.OnnxTransformer still has a dependency with ML.OnnxRuntime 0.5.1 while ML.OnnxRuntime 1.0.0 is already available.

@mingzhao03 : Any sameple code you can share to get this working with InferenceSession.Run and the OnnxRuntime.GPU? I'm basically trying to run an exported Custom Vision Model (ONNX) for Object Detection locally on a Windows 10 build 1809 with GPU support.

**Comment by mingzhao03** [comment]
@donaldhessing I am using a custom ONNX model on 1D data. For my use case I don't need a pipeline to preprocess data, so my code was fairly simple like this:
`
this.inferenceSession = new InferenceSession(this.modelLocation, SessionOptions.MakeSessionOptionWithCudaProvider(deviceId: 0));
var namedOnnxValues = new List<NamedOnnxValue>
        {
            NamedOnnxValue.CreateFromTensor<float>(name:, new DenseTensor<float>(...))
        }
IDisposableReadOnlyCollection<DisposableNamedOnnxValue> output = this.inferenceSession.Run(namedOnnxValues);
`
