### ISSUE TITLE
[Mobile] operator com.ms.internal.nhwc:Resize:19 is loss in xnnpack

### ISSUE THREAD

**Issue by deahhh** [microsoft/onnxruntime#20162]
### Describe the issue

I built an onnx model and converted it to ort model with 
       ```        python -m onnxruntime.tools.convert_onnx_models_to_ort /data/work/cardDec/deploy/onnx_models --target_platform amd64 --optimization_style Runtime```. 
Then run it in local onnxruntime built with 
       ```       ./build.sh --config MinSizeRel --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --use_xnnpack```
command.

To be sure it works fine without using xnnpack session-options, of cause with another libonnxruntime which build without `--use_xnnpack`.

From [document](https://onnxruntime.ai/docs/execution-providers/Xnnpack-ExecutionProvider.html#supported-ops), we know Resize op is supported since 1.14.  So I think It's my code is wrong.
My Code for load model is as follows:
```C++
    env_ = std::make_unique<Ort::Env>(ORT_LOGGING_LEVEL_ERROR, "Default");
    session_options_ = std::make_unique<Ort::SessionOptions>();
    session_options_->SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
    session_options_->AddConfigEntry(kOrtSessionOptionsConfigAllowIntraOpSpinning, "0");

    int intra_op_num_threads{1};
    std::unordered_map<std::string,std::string> threads_cfg;
    threads_cfg.insert(std::make_pair("intra_op_num_threads", std::to_string(intra_op_num_threads)));
    session_options_->AppendExecutionProvider("XNNPACK", threads_cfg);
    session_options_->SetIntraOpNumThreads(1);

    session_ = std::make_unique<Ort::Session>(*env_, model_file, *session_options_);
```
One thing I noticed is that the error reporting that it was not found was `com.ms.internal.nhwc:Resize:19`, while the documentation describes the name of Resize as `ai.onnx:Resize`. Again, from required_operators.with_runtime.ort: `ai.onnx;19;Cast,Reshape,Resize,Shape`.

### To reproduce

The working link is a bit long and I haven't found a suitable reproduction to show here.

### Platform

React Native

### OS Version

Ubuntu 22.04

### ONNX Runtime Installation

Built from Source

### Compiler Version (if 'Built from Source')

gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

1.17.1

### ONNX Runtime API

C++/C

### Architecture

X64

### Execution Provider

NNAPI

**Comment by edgchen1** [comment]
Could you include the full error message and the model?

Also, what's the reason for using an ORT format model? It looks like you are not doing a minimal build - with a full build you can run an ONNX model directly which would probably be simpler.

**Comment by deahhh** [comment]
> Also, what's the reason for using an O

The full error message is:
```bash
/data/work/cardDec/deploy/build$ ./decoder_test 
2024-04-02 23:26:40.603743743 [E:onnxruntime:, inference_session.cc:1980 operator()] Exception during initialization: /home/han/aarch64v8/onnxruntime/onnxruntime/core/framework/kernel_registry.cc:69 bool onnxruntime::{anonymous}::MatchKernelDefTypes(const onnxruntime::Node&, const std::unordered_map<std::__cxx11::basic_string<char>, std::vector<const onnxruntime::DataTypeImpl*> >&, const onnxruntime::IKernelTypeStrResolver&, std::string&) [ONNXRuntimeError] : 1 : FAIL : kernel_type_str_resolver.cc:20 ResolveKernelTypeStr Failed to find op_id: com.ms.internal.nhwc:Resize:19

terminate called after throwing an instance of 'Ort::Exception'
  what():  Exception during initialization: /home/han/aarch64v8/onnxruntime/onnxruntime/core/framework/kernel_registry.cc:69 bool onnxruntime::{anonymous}::MatchKernelDefTypes(const onnxruntime::Node&, const std::unordered_map<std::__cxx11::basic_string<char>, std::vector<const onnxruntime::DataTypeImpl*> >&, const onnxruntime::IKernelTypeStrResolver&, std::string&) [ONNXRuntimeError] : 1 : FAIL : kernel_type_str_resolver.cc:20 ResolveKernelTypeStr Failed to find op_id: com.ms.internal.nhwc:Resize:19
```

**Comment by deahhh** [comment]
```bash
  --target_platform {arm,amd64}
                        Specify the target platform where the exported model will be used. This parameter can be used to choose between platform-specific options, such as QDQIsInt8Allowed(arm), NCHWc (amd64) and
                        NHWC (arm/amd64) format, different optimizer level options, etc.
```

Does it mean you can convert models with dimensions order NHWC or NCHWc for amd64 plant-form, while could only convert models with dimension-order NHWC or QDQIsInt8Allowed for arm?

**Comment by edgchen1** [comment]
> Does it mean you can convert models with dimensions order NHWC or NCHWc for amd64 plant-form, while could only convert models with dimension-order NHWC or QDQIsInt8Allowed for arm?

It shouldn't limit what models can be converted, but it controls how the model may be optimized. E.g., the NCHWc graph transformer is not applicable to ARM devices.

**Comment by edgchen1** [comment]
BTW, I'm able to reproduce the issue. We'll look into it.

**Comment by skottmckay** [comment]
Why is a minimal build needed? It's an option that provides a few less MB of binary size, which in most use cases isn't overly important. A non-minimal build will work perfectly well on all mobile platforms. 

The majority of the binary size saving comes from reducing the ops/types included in the build via the `--include_ops_by_config required_operators_and_types.config` and `--enable_reduced_operator_type_support` params. This uses the config file generated during model conversion, but it's not necessary to use the ORT format model.

**Comment by deahhh** [comment]
> > Does it mean you can convert models with dimensions order NHWC or NCHWc for amd64 plant-form, while could only convert models with dimension-order NHWC or QDQIsInt8Allowed for arm?
> 
> It shouldn't limit what models can be converted, but it controls how the model may be optimized. E.g., the NCHWc graph transformer is not applicable to ARM devices.

Thank you very much for your answer!
I still don't get it, the onnx model I generated from pytorch is in NCHWc format, and it looks the same from netron, so can it reason with the arm64 platform. can it do it on nnapi or xnnpack?

**Comment by deahhh** [comment]
> Why is a minimal build needed? It's an option that provides a few less MB of binary size, which in most use cases isn't overly important. A non-minimal build will work perfectly well on all mobile platforms.
> 
> The majority of the binary size saving comes from reducing the ops/types included in the build via the `--include_ops_by_config required_operators_and_types.config` and `--enable_reduced_operator_type_support` params. This uses the config file generated during model conversion, but it's not necessary to use the ORT format model.

Thanks you very much！
For your advice，
As a junior developer, you can imagine that he would first test the development on his work computer and use commands that are as consistent as possible with what he will officially use in the future. But then he realizes that it didn't run through development, and he can't imagine how it could have been used directly.

**Comment by deahhh** [comment]
> > > Does it mean you can convert models with dimensions order NHWC or NCHWc for amd64 plant-form, while could only convert models with dimension-order NHWC or QDQIsInt8Allowed for arm?
> > 
> > 
> > It shouldn't limit what models can be converted, but it controls how the model may be optimized. E.g., the NCHWc graph transformer is not applicable to ARM devices.
> 
> Thank you very much for your answer! I still don't get it, the onnx model I generated from pytorch is in NCHWc format, and it looks the same from netron, so can it reason with the arm64 platform. can it do it on nnapi or xnnpack?

OH, I [see](https://github.com/microsoft/onnxruntime/issues/20218)!
Thanks you all, again!
