### ISSUE TITLE
Identity convolution to produce same output for the given input

### ISSUE THREAD

**Issue by Praneeth723** [microsoft/onnxruntime#20174]
### Describe the issue

When I run onnxruntime session for same input for multiple times for every iteration it has been producing different output with the same input. Convolution weights and bias padding and everything are perfectly correct

### To reproduce

Take any input shape and assign random values iterate the onnxrun time session for same input values for various time and compare the input and output , I was obtaining different 'nan' or 'inf' in the output where I was expected to get the same input

### Urgency

urgent I am stuck in between of project (I am new to onnx)

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.3

### PyTorch Version

I am using onnx 1.16.0

### Execution Provider

Default CPU

**Comment by Praneeth723** [comment]
def idenity(shape):
    input_tensor = onnx.helper.make_tensor_value_info('input_tensor',onnx.TensorProto.FLOAT,input_shape)
    output = onnx.helper.make_tensor_value_info('output',onnx.TensorProto.FLOAT,['N','C','H','W'])
    kernel1_val = (np.eye(input_shape[1]).astype(np.float32)).flatten()
    kernel = onnx.helper.make_tensor('kernel',onnx.TensorProto.FLOAT,[input_shape[1],input_shape[1],1,1],kernel1_val)
    bias = onnx.helper.make_tensor('bias',onnx.TensorProto.FLOAT,[1],[0.0])
    iden_node = onnx.helper.make_node('Conv',inputs=["input_tensor","kernel","bias"],outputs=["output"],kernel_shape = [1,1],pads = [0,0,0,0],strides=[1,1],group=1,name="identity_conv")
    graph = onnx.helper.make_graph(nodes=[iden_node],name='identity',inputs=[input_tensor],outputs=[output],initializer=[kernel,bias])
    return graph
   **#this is a identity convolution which I used instead of direct identity node** 
   **I have taken a more than 500+ sample of input tensors with different channels and dimensions  and random values when I compare the input and output after each iteration during the start the tensors are equal after 5 to 10 iterations the output tensors where giving "nan"**

**Comment by Praneeth723** [comment]
Any update on the above bug or issue

**Comment by prathikr** [comment]
@Praneeth723 reassigning to core runtime as this does not appear to be a training issue.

**Comment by Praneeth723** [comment]
I have taken same tensor let (1,40,280,160) run multiple times iterating in a loop by giving to the above function and mae(mean average error) between the tensor some times it is crossing more than 1*e+30
