### ISSUE TITLE
[Documentation] Content Headers has placeholder

### ISSUE THREAD

**Issue by tianleiwu** [microsoft/onnxruntime#20249]
### Describe the documentation issue

![image](https://github.com/microsoft/onnxruntime/assets/30328909/e914d2bb-5742-4d37-8c80-f3fabd91107b)

### Page / URL

https://onnxruntime.ai/docs/install/

**Comment by sophies927** [comment]
PR with fix: https://github.com/microsoft/onnxruntime/pull/20441
