### ISSUE TITLE
 Fatal error: com.microsoft.nchwc:Conv(1) is not a registered function/op

### ISSUE THREAD

**Issue by feff2** [microsoft/onnxruntime#20247]
### Describe the issue

When I try started code on my device I met error: ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: Fatal error: com.microsoft.nchwc:Conv(1) is not a registered function/op. When running on the emulator, there is no such error
I added custom layter from onnxruntime-extensions to model.
Model, which i use, is Mobile ViT XS 
### To reproduce

I tried to transfer Mobile ViT to .ort format.  

### Platform

Android

### OS Version

11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.17.0.

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

NNAPI

**Comment by ashok-arora** [comment]
@feff2 How did you solve it?

**Comment by DeepakSaini119** [comment]
Facing similar issue. How did you resolve it?
