### ISSUE TITLE
Failed to run contrib ops like MurmurHash3 with python

### ISSUE THREAD

**Issue by axinging** [microsoft/onnxruntime#20252]
### Describe the issue

If comment out "model_def.ir_version = 9": complains:
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from test_model.onnx
failed:C:\ort\onnxruntime\onnxruntime\core\graph\model.cc:180 onnxruntime::Model::Model Unsupported model IR version: 10, 
max supported IR version: 9
```

If add  "model_def.ir_version = 9": complains:"
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from test_model.onnx 
failed:C:\ort\onnxruntime\onnxruntime\core/graph/model_load_utils.h:56 onnxruntime::model_load_utils::ValidateOpsetForDomain 
ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 21 is under 
development and support for this is limited. The operator schemas and or other functionality may change before next ONNX 
release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain ai.onnx is till 
opset 20.
```

This issue is based on https://github.com/microsoft/onnxruntime/discussions/6665.

### To reproduce

```
import onnxruntime as ort
import onnx
from onnx import helper as helper
from onnx import TensorProto# as tp
import numpy as np
from onnxruntime_extensions import get_library_path as _lib_path

X = helper.make_tensor_value_info('X', TensorProto.STRING, [1])
Y = helper.make_tensor_value_info('Y', TensorProto.UINT32, [1])

node_def = helper.make_node(
    'MurmurHash3', # node name
    ['X'], # inputs
    ['Y'], # outputs
    domain="com.microsoft",
)

graph_def = helper.make_graph(
    [node_def],
    "test-model",
    [X],
    [Y],
)

model_def = helper.make_model(graph_def,
                              producer_name='onnx-example')
#model_def.ir_version = 9
#onnx.checker.check_model(model_def)
# Save the model
MODEL_NAME = "test_model.onnx"
onnx.save(model_def, MODEL_NAME)

so = ort.SessionOptions()
so.register_custom_ops_library(_lib_path())
#sess = rt.InferenceSession("test_model.onnx", sess_options=so)

onnx.save(model_def, MODEL_NAME)
ort_sess = ort.InferenceSession(MODEL_NAME, sess_options=so)
t1 = np.random.randn(1, 1).astype(np.float32)
outputs = ort_sess.run(None, {'X': t1})
```

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

22a61a3cf513c4beffb59dbc55a4cbe6ac278835

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by axinging** [comment]
This can be fixed with: export ALLOW_RELEASED_ONNX_OPSET_ONLY=1

**Comment by bg51717** [comment]
I've encountered the same bug, but it still hasn't been resolved after trying your method. And the test code is exactly the same as the one you provided.Do you have any other thoughts on this? Thanks!

**Comment by bg51717** [comment]
> This can be fixed with: export ALLOW_RELEASED_ONNX_OPSET_ONLY=1


I've encountered the same bug, but it still hasn't been resolved after trying your method. And the test code is exactly the same as the one you provided.Do you have any other thoughts on this? Thanks!

**Comment by lix19937** [comment]
> This can be fixed with: export ALLOW_RELEASED_ONNX_OPSET_ONLY=1

not work.

**Comment by axinging** [comment]
@bg51717 @lix19937 
Sorry for the typo, should be : export ALLOW_RELEASED_ONNX_OPSET_ONLY=0

**Comment by lix19937** [comment]
@axinging  thanks, I downgrade my onnx version(from v1.16 to v1.15) to solve this problem.

**Comment by bg51717** [comment]
> @axinging thanks, I downgrade my onnx version(from v1.16 to v1.15) to solve this problem.

I also used this method and worked well.
