### ISSUE TITLE
Ensures <img> elements have alternate text or a role of none or presentation (img): A11y_WCP URLs - ONNX Runtime_AI4W

### ISSUE THREAD

**Issue by aniketr99** [microsoft/onnxruntime#20259]
## GitHub Tags:
#A11ySev2; #A11yTCS; #DesktopWeb; #SH_ONNX Runtime & Ecosystem_Web_Mar2024; #ONNX Runtime & Ecosystem; #WCP; #Win11; #Benchmark; #FTP; #P3_WCP; #ONNX Runtime; #ChromiumEdge; #A11yMAS; #WCAG1.1.1; #A11yAuto; #image-alt; #Accessibility; #Non-text Content;

**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver".**

## Environment Details:
Application Name: WCP URLs - ONNX Runtime
URL: https://onnxruntime.ai/blogs
Edge version: 124.0.0.0 (Official build) (64-bit)
OS: Windows 11 version 23H2

## Issue: 
Ensures <img> elements have alternate text or a role of none or presentation (image-alt - https://accessibilityinsights.io/info-examples/web/image-alt)

## Target application: 
ONNX Runtime | Blogs - https://onnxruntime.ai/blogs

## Element path: 
article:nth-child(1) > a > .h-full.card > .card-body > img

## Snippet: 
<img src="/_app/immutable/assets/webgpu_blog_thumbnail.67d2363e.jpg">

### Fix any of the following:
  Element does not have an alt attribute
  aria-label attribute does not exist or is empty
  aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
  Element has no title attribute
  Element's default semantics were not overridden with role="none" or role="presentation"

## Environment: 
Microsoft Edge version 124.0.0.0

====

This accessibility issue was found using Accessibility Insights for Web 2.41.0 (axe-core 4.7.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

Attachment:
![image](https://github.com/microsoft/onnxruntime/assets/100269580/cea49564-7d62-4d4c-87f8-018b081b5001)

**Comment by v-jagansai** [comment]
Verified the issue in below environment.
Application Name: WCP URLs - ONNX Runtime
URl: https://onnxruntime.ai/
Edge version: 123.0.2420.97 (Official build) (64-bit)
OS: Windows 11 version 23H2

Issue is fixed. Hence the bug is closed.
#Regressed:04-18-24; #Closed;

For reference attachment is added.
![image](https://github.com/microsoft/onnxruntime/assets/109065315/0a5a4e60-41c5-484f-87fb-dc17255c052b)
