### ISSUE TITLE
Ensures lang attributes have valid values (pre[lang="bash"]): A11y_WCP URLs - ONNX Runtime_AI4W

### ISSUE THREAD

**Issue by aniketr99** [microsoft/onnxruntime#20262]
## GitHub Tags: 
#A11ySev2; #A11yTCS; #DesktopWeb; #SH_ONNX Runtime & Ecosystem_Web_Mar2024; #ONNX Runtime & Ecosystem; #WCP; #Win11; #Benchmark; #FTP; #P3_WCP; #ONNX Runtime; #ChromiumEdge; #A11yMAS; #WCAG3.1.2; #A11yAuto; #valid-lang; #Accessibility; #Language of Parts; 

**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver".** 

## Environment Details: 
Application Name: WCP URLs - ONNX Runtime 
URL: https://onnxruntime.ai/docs/install/
Edge version: 124.0.0.0 (Official build) (64-bit) 
OS: Windows 11 version 23H2

## Issue: 
Ensures lang attributes have valid values (valid-lang - https://accessibilityinsights.io/info-examples/web/valid-lang)

## Target application: 
Install ONNX Runtime | onnxruntime - https://onnxruntime.ai/docs/install/

## Element path: 
tr:nth-child(2) > td:nth-child(4) > pre[lang="bash"]

## Snippet: 
< pre lang="bash">dotnet add package Microsoft.ML.OnnxRuntime.Training</pre>

### Fix all of the following:
  Value of lang attribute not included in the list of valid languages

## Environment: 
Microsoft Edge version 124.0.0.0

====

This accessibility issue was found using Accessibility Insights for Web 2.41.0 (axe-core 4.7.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

## Attachment:
![image](https://github.com/microsoft/onnxruntime/assets/100269580/7c3961a5-065d-4a1d-842c-dcccae6b45e6)

**Comment by MaanavD** [comment]
Closing as not planned. Languages shown are correct programming languages, and while they are not english they are correctly labelled for the associated. language.
