### ISSUE TITLE
Ensures all ARIA attributes have valid values (#OI_tab): A11y_WCP URLs - ONNX Runtime_AI4W

### ISSUE THREAD

**Issue by aniketr99** [microsoft/onnxruntime#20264]
## GitHub Tags: 
#A11ySev2; #A11yTCS; #DesktopWeb; #SH_ONNX Runtime & Ecosystem_Web_Mar2024; #ONNX Runtime & Ecosystem; #WCP; #Win11; #Benchmark; #FTP; #P3_WCP; #ONNX Runtime; #ChromiumEdge; #A11yMAS; #WCAG4.1.2; #A11yAuto; #aria-valid-attr-value; #Accessibility; #Name, Role, Value;

**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver".** 

## Environment Details: 
Application Name: WCP URLs - ONNX Runtime 
URL: https://onnxruntime.ai/getting-started
Edge version: 124.0.0.0 (Official build) (64-bit) 
OS: Windows 11 version 23H2

## Issue: 
Ensures all ARIA attributes have valid values (aria-valid-attr-value - https://accessibilityinsights.io/info-examples/web/aria-valid-attr-value)

## Target application: 
ONNX Runtime | Getting-started - https://onnxruntime.ai/getting-started

## Element path: 
#OI_tab

## Snippet: 
< li class="nav-item tab tab-lg tab-active" id="OI_tab" data-toggle="pill" aria-controls="panel0" tabindex="0" role="tab">Optimize Inferencing </li>

### Fix all of the following:
  Invalid ARIA attribute value: aria-controls="panel0"

## Environment: 
Microsoft Edge version 124.0.0.0

====

This accessibility issue was found using Accessibility Insights for Web 2.41.0 (axe-core 4.7.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

## Attachment:
![image](https://github.com/microsoft/onnxruntime/assets/100269580/11033f9f-2233-45cf-b37b-20f70cf5d16c)

**Comment by v-jagansai** [comment]
Verified the issue in below environment.
Application Name: WCP URLs - ONNX Runtime
URl: https://onnxruntime.ai/
Edge version: 123.0.2420.97 (Official build) (64-bit)
OS: Windows 11 version 23H2

Issue is fixed. Hence the bug is closed.
#Regressed:04-18-24; #Closed;

For reference attachment is added.
![image](https://github.com/microsoft/onnxruntime/assets/109065315/f5944be8-95b8-44de-814d-86d75b70d479)
