### ISSUE TITLE
Ensures elements with an ARIA role that require parent roles are contained by them (#OI_tab): A11y_WCP URLs - ONNX Runtime_AI4W

### ISSUE THREAD

**Issue by aniketr99** [microsoft/onnxruntime#20263]
## GitHub Tags: 
#A11ySev2; #A11yTCS; #DesktopWeb; #SH_ONNX Runtime & Ecosystem_Web_Mar2024; #ONNX Runtime & Ecosystem; #WCP; #Win11; #Benchmark; #FTP; #P3_WCP; #ONNX Runtime; #ChromiumEdge; #A11yMAS; #WCAG1.3.1; #A11yAuto; #Info and relationships; #Accessibility; #aria-required-parent;

**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver".**

 ## Environment Details: 
Application Name: WCP URLs - ONNX Runtime 
URL: https://onnxruntime.ai/getting-started
Edge version: 124.0.0.0 (Official build) (64-bit) 
OS: Windows 11 version 23H2

## Issue: 
Ensures elements with an ARIA role that require parent roles are contained by them (aria-required-parent - https://accessibilityinsights.io/info-examples/web/aria-required-parent)

## Target application: 
ONNX Runtime | Getting-started - https://onnxruntime.ai/getting-started

## Element path: 
#OI_tab

## Snippet: 
< li class="nav-item tab tab-lg tab-active" id="OI_tab" data-toggle="pill" aria-controls="panel0" tabindex="0" role="tab">Optimize Inferencing </li>

### Fix any of the following:
  Required ARIA parent role not present: tablist

## Environment: 
Microsoft Edge version 124.0.0.0

====

This accessibility issue was found using Accessibility Insights for Web 2.41.0 (axe-core 4.7.2), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

## Attachment:
![image](https://github.com/microsoft/onnxruntime/assets/100269580/3a70a192-ba0f-4be7-8379-9709dacbe2c3)

**Comment by yuslepukhin** [comment]
Why these issues are filed here for ONNXRuntime? Is there an action point for ORT development team? I am not seeing any.

**Comment by v-jagansai** [comment]
Verified the issue in below environment.
Application Name: WCP URLs - ONNX Runtime
URl: https://onnxruntime.ai/
Edge version: 123.0.2420.97 (Official build) (64-bit)
OS: Windows 11 version 23H2

Issue is fixed. Hence the bug is closed.
#Regressed:04-18-24; #Closed;

For reference attachment is added.
![image](https://github.com/microsoft/onnxruntime/assets/109065315/4ae8dfaa-9ebf-45f1-8ed4-94002221864b)
