### ISSUE TITLE
onnxruntime c++ 1.16.3, how to get human readable input name

### ISSUE THREAD

**Issue by soyoapp** [microsoft/onnxruntime#20339]
### Describe the issue

when use onnxruntime-1.16.3 and I use following code

    #include <iostream>
    #include <onnxruntime_cxx_api.h>
    
    int main() {
        // Path to the ONNX model
        const char *model_path = "/home/roroco/Downloads/mix/test_ai/resnet18-v1-7.onnx";
    
        // Create an ONNX Runtime environment
        Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "ONNXExample");
    
        // Create a session options object
        Ort::SessionOptions session_options;
    
        // Create an ONNX Runtime session
        Ort::Session session(env, model_path, session_options);
    
        // Get the input count of the model
        size_t input_count = session.GetInputCount();
    
        Ort::AllocatorWithDefaultOptions allocator;
    
        // Print the input names
        for (size_t i = 0; i < input_count; ++i) {
    //        char *input_name = session.GetInputName(i, allocator);
            char *input_name = session.GetInputNameAllocated(i, allocator).get();
            std::cout << "Input name " << i << ": " << input_name << std::endl;
        }
    
        return 0;
    }

it out Input name 0: ���UUU

when I switch to onnxruntime 1.12 and use `session.GetInputName(i, allocator)`, it get can real input name "data"

in new onnxruntime, how to get human-readable input name

### To reproduce

Just run above code

### Platform

Linux

### OS Version

ubuntu 18.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.16.3

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by yuslepukhin** [comment]
`char *input_name = session.GetInputNameAllocated(i, allocator).get();`

This is not a C++ support group, but I will have to do it. The API returns a smart pointer, which is a temporary object. The lifespan of the temp objects in C++ is limited to the statement where they are produced. So you obtain the pointer to the buffer, which is then is promptly deallocated once the statement finishes execution.

I agree that the API needs improvement.

**Comment by tianleiwu** [comment]
See example code:
https://github.com/microsoft/onnxruntime/blob/4d2b98155f0bcc7cc4231397be92db2adbf6cfbd/onnxruntime/python/tools/tensorrt/perf/mem_test/main.cpp#L51-L52
