### ISSUE TITLE
onnx source code compiled armeabi-v7a so

### ISSUE THREAD

**Issue by tuzi-maker** [microsoft/onnxruntime#20348]
### Describe the issue

onnx source code compiled armeabi-v7a so,  ./build.sh --android_abi  :subprocess.CalledProcessError: Command '['git', 'submodule', 'sync', '--recursive']' returned non-zero exit status 128

### Target platform

armeabi-v7a

### Build script

 ./build.sh --android_abi

### Error / output

subprocess.CalledProcessError: Command '['git', 'submodule', 'sync', '--recursive']' returned non-zero exit status 128

**Comment by tuzi-maker** [comment]
Thank you for your reply, the problem was solved after modification

**Comment by keepfoolisher** [comment]
> Thank you for your reply, the problem was solved after modification

hello, I have same question, how do you solve the question? thank you
