### ISSUE TITLE
invalid converting fp32 to fp16

### ISSUE THREAD

**Issue by Macsim2** [microsoft/onnxruntime#20346]
### Describe the issue

fp32 onnx model is works well. 
But when I convert fp32 model to fp16 model, the fp16 model output strange results
Is there anyone who know this problem..?

here is my environment
onnx == 1.15.0
onnxconverter_common == 1.14.0
onnxruntime == 1.17.1

### To reproduce

```python
import onnx
from onnxconverter_common import float16

model = onnx.load("path/to/model.onnx")
model_fp16 = float16.convert_float_to_float16(model)
onnx.save(model_fp16, "path/to/model_fp16.onnx")
```

### Platform

Linux

### OS Version

ubuntu20.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.1

### ONNX Runtime API

Python

### Architecture

X86

### Execution Provider

Default CPU, CUDA

**Comment by tianleiwu** [comment]
A possible cause: https://github.com/microsoft/onnxconverter-common/issues/271

If you find two Cast nodes linked like:
![image](https://github.com/microsoft/onnxruntime/assets/30328909/dec3f71b-2432-48dc-9f6c-082d7df12c58)

A walkaround is to remove extra Cast nodes like
```
import onnx
from onnxruntime.transformers.onnx_model import OnnxModel
onnx_model=OnnxModel(onnx.load("path/to/model_fp16.onnx"))
onnx_model.remove_cascaded_cast_nodes()
onnx_model.save_model_to_file("path/to/model_fp16_v2.onnx", use_external_data_format=False, all_tensors_to_one_file=True)
```

**Comment by Macsim2** [comment]
@tianleiwu Thank you that comments me 
I checked the cast nodes through netron app

This is "model_fp16.onnx"
![Screenshot from 2024-04-17 16-14-51](https://github.com/microsoft/onnxruntime/assets/47729187/90dca1a7-84fe-4947-bf48-7b67b66ca907)


and then I just executed what you said 
However, It doesn't works for me sadly 
this is "model_fp16_v2.onnx"
![Screenshot from 2024-04-17 16-15-22](https://github.com/microsoft/onnxruntime/assets/47729187/aff72709-f0ee-4487-b5c5-8a3768e6572d)

For reference, I think that onnxruntime or onnxconverter_common are not invalid.
Because other models are works well. except for the probelm models (the problem model is bigger than other models)
Do you have any hint can I do by anychance?

**Comment by tianleiwu** [comment]
Not every model can run in fp16. Sometime, some nodes need to upcast to fp32 to avoid overflow.

You can add `--cmake_extra_defines onnxruntime_DEBUG_NODE_INPUTS_OUTPUTS=1` in build command line to build a package from source code. Set environment variable `ORT_DEBUG_NODE_IO_DUMP_OUTPUT_DATA` to be 1 before running your application. In this way, you can see of output of each node. Compare the stdout of two runs (fp32 model vs fp16 model) can find out the root cause. See https://onnxruntime.ai/docs/build/eps.html#cuda for more information.

**Comment by Macsim2** [comment]
okay Thank you reply @tianleiwu 
I'll keep in track this problem and I will share with you if I found the reason why the model had didn't work
