### ISSUE TITLE
[Build] Debug build is broken with TensorRT EP

### ISSUE THREAD

**Issue by JulienTheron** [microsoft/onnxruntime#20369]
### Describe the issue

Building the ONNX Runtime in Debug with TensorRT is broken with 1.17.3. Release build is fine.

### Target platform

Windows

### Build script

build.bat --build_dir "Output" --config Debug --parallel --skip_tests --disable_memleak_checker --compile_no_warning_as_error --use_dml --use_tensorrt --cuda_home "%CUDA_PATH_V11_8%" --cuda_version 11.8 --cudnn_home "%CUDNN_PATH_V8_9_0%" --tensorrt_home "%TENSORRT_PATH_V8_6_1%" --cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES='60;75;86;89'"

### Error / output

```
C:\Dev\onnx-runtime-build\Output\Debug\_deps\onnx_tensorrt-src\ModelImporter.cpp(336,9): error C2664: 'bool google::protobuf::TextFormat::Parse(google::protobuf::io::ZeroCopyInpu
tStream *,google::protobuf::Message *)': cannot convert argument 2 from 'onnx::ModelProto *' to 'google::protobuf::Message *' [C:\Dev\onnx-runtime-build\Output\Debug\_deps\onnx_t
ensorrt-build\nvonnxparser_static.vcxproj]
  C:\Dev\onnx-runtime-build\Output\Debug\_deps\onnx_tensorrt-src\ModelImporter.cpp(336,9):
  Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
  C:\Dev\onnx-runtime-build\Output\Debug\_deps\protobuf-src\src\google\protobuf\text_format.h(477,15):
  see declaration of 'google::protobuf::TextFormat::Parse'
  C:\Dev\onnx-runtime-build\Output\Debug\_deps\onnx_tensorrt-src\ModelImporter.cpp(336,9):
  while trying to match the argument list '(google::protobuf::io::ArrayInputStream *, onnx::ModelProto *)'

C:\Dev\onnx-runtime-build\Output\Debug\_deps\onnx_tensorrt-src\ModelImporter.cpp(358,9): error C2664: 'bool google::protobuf::TextFormat::Parse(google::protobuf::io::ZeroCopyInpu
tStream *,google::protobuf::Message *)': cannot convert argument 2 from 'onnx::ModelProto *' to 'google::protobuf::Message *' [C:\Dev\onnx-runtime-build\Output\Debug\_deps\onnx_t
ensorrt-build\nvonnxparser_static.vcxproj]
  C:\Dev\onnx-runtime-build\Output\Debug\_deps\onnx_tensorrt-src\ModelImporter.cpp(358,9):
  Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or parenthesized function-style cast
  C:\Dev\onnx-runtime-build\Output\Debug\_deps\protobuf-src\src\google\protobuf\text_format.h(477,15):
  see declaration of 'google::protobuf::TextFormat::Parse'
  C:\Dev\onnx-runtime-build\Output\Debug\_deps\onnx_tensorrt-src\ModelImporter.cpp(358,9):
  while trying to match the argument list '(google::protobuf::io::FileInputStream *, onnx::ModelProto *)'
```

### Visual Studio Version

Visual Studio 2022 17.9.5

**Comment by chilo-ms** [comment]
@JulienTheron
Could you help change the build script [here ](https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/build.py#L1250)?
-`or (args.use_tensorrt and args.use_tensorrt_oss_parser)`
+`or args.use_tensorrt`
to use protobuf?

The issue is because when building Debug on Windows, ORT will implicitly use oss onnx-tensorrt parser rather than built-in parser due to known issue of msvc. And oss onnx-tensorrt requires protobuf not protobuf-lite.

**Comment by JulienTheron** [comment]
Thanks for the quick response. I think the issue is linked to #20368. I will try to build the correct tag and will get back to you.

**Comment by JulienTheron** [comment]
It seems QSpectre is enabled by default now, unless `--enable_address_sanitizer` is set.
I'm not sure if this is by design, but I updated my build script to replace `--disable_memleak_checker` with `--enable_address_sanitizer` and the build succeeded!
Thanks.

**Comment by JulienTheron** [comment]
I just figured that enabling the address sanitizer is not a good solution for us as it relies on the presense of clang_rt.asan_dynamic-x86_64.dll at runtime, which is not a good idea when you ship a DLL to your users.
So currently, we're stuck with being forced to enable QSpectre when building ORT v1.17.3, which breaks the build as those prerequisites are not installed with Visual Studio by default.
Any idea if this can be fixed before 1.18?

**Comment by chilo-ms** [comment]
>Could you help change the build script [here ](https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/build.py#L1250)?
-or (args.use_tensorrt and args.use_tensorrt_oss_parser)
+or args.use_tensorrt

just wondering did you try above?

i can repro from my side and this issue is because of using protobuf-lite when building the onnx-tensorrt parser.

**Comment by JulienTheron** [comment]
Yes I did try your fix and it works fine on the main branch, but it's not applicable for 1.17.3 as the build script is different.
The issue now is that QSpectre is always enabled when building 1.17.3. I think I'll open a new issue for that.
Thanks.
