### ISSUE TITLE
[Build] Incorrect version number in the released file (1.17.3)

### ISSUE THREAD

**Issue by csukuangfj** [microsoft/onnxruntime#20368]
### Describe the issue

```
wget https://github.com/microsoft/onnxruntime/archive/refs/tags/v1.17.3.tar.gz
tar xf v1.17.3.tar.gz

cat onnxruntime-1.17.3/VERSION_NUMBER
```
and it outputs
```
1.18.0
```

which should be `1.17.3`.

**Comment by snnn** [comment]
Sorry we generated a wrong tag.

**Comment by csukuangfj** [comment]
Not only the tag is wrong, but the following line
https://github.com/microsoft/onnxruntime/blob/56b660f36940a919295e6f1e18ad3a9a93a10bf7/onnxruntime/core/session/onnxruntime_c_api.cc#L2760
in the file
is also
`1.18.0`.


---

Could you change the released file and upload a new one?


Not sure why it is closed even if nothing has been proposed to fix it.

**Comment by shoeffner** [comment]
@csukuangfj, the tag moved to the commit you referenced, so this should be fixed now?

```console
$ git log v1.17.3 | head -n3
commit 54f91ea65aa6874b8edbcf159479104f49f50c8c
Author: Yifan Li <109183385+yf711@users.noreply.github.com>
Date:   Tue Apr 16 12:49:29 2024 -0700
$ git pull --tags
...
 ! [rejected]              v1.17.3                 -> v1.17.3  (would clobber existing tag)
$ git pull --tags --force
...
$ git log v1.17.3 | head -n3
commit 56b660f36940a919295e6f1e18ad3a9a93a10bf7
Author: Jian Chen <cjian@microsoft.com>
Date:   Fri Apr 12 15:34:38 2024 -0400
```

**Comment by csukuangfj** [comment]
Thank you!
