### ISSUE TITLE
[Build] D:\Source\onnxruntime\onnxruntime\test\optimizer\graph_transform_test.cc(1,1): error C1128: number of sections exceeded  object file format limit: compile with /bigobj [D:\build\Windows\Release\onnxruntime_test_all.vcxproj]

### ISSUE THREAD

**Issue by acube3** [microsoft/onnxruntime#20406]
### Describe the issue

Getting the following error while building on ARM64 system:
D:\Source\onnxruntime\onnxruntime\test\optimizer\graph_transform_test.cc(1,1): error C1128: number of sections exceeded
 object file format limit: compile with /bigobj [D:\build\Windows\Release\onnxruntime_test_all.vcxproj]
 

### Urgency

I would like to resolve this as soon as possible.

### Target platform

Windows

### Build script

build.bat --arm64 --use_qnn --qnn_home=C:\Qualcomm\AIStack\QAIRT\2.21.0.240401 --build_shared_lib --cmake_generator "Visual Studio 17 2022" --skip_submodule_sync --config Release --build_dir \build\Windows

### Error / output

.
.
.
.
 rule_based_graph_transformer_test.cc
D:\Source\onnxruntime\onnxruntime\test\optimizer\graph_transform_test.cc(1,1): error C1128: number of sections exceeded
 object file format limit: compile with /bigobj [D:\build\Windows\Release\onnxruntime_test_all.vcxproj]
  graph_runtime_optimization_test.cc
  allocation_planner_test.cc
  copy_test.cc
  bfc_arena_test.cc
  allocator_test.cc
  distance_test.cc
  execution_frame_test.cc
  data_types_test.cc
  endian_test.cc
  execution_provider_test.cc
  float_16_test.cc
  float_8_test.cc
Traceback (most recent call last):
  File "D:\Source\onnxruntime\\tools\ci_build\build.py", line 2945, in <module>
    sys.exit(main())
             ^^^^^^
  File "D:\Source\onnxruntime\\tools\ci_build\build.py", line 2837, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "D:\Source\onnxruntime\\tools\ci_build\build.py", line 1726, in build_targets
    run_subprocess(cmd_args, env=env)
  File "D:\Source\onnxruntime\\tools\ci_build\build.py", line 855, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Source\onnxruntime\tools\python\util\run.py", line 49, in run
    completed_process = subprocess.run(
                        ^^^^^^^^^^^^^^^
  File "C:\Users\amolamb\AppData\Local\Programs\Python\Python311-arm64\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin\\cmake.EXE', '--build', '\\build\\Windows\\Release', '--config', 'Release']' returned non-zero exit status 1.

### Visual Studio Version

VS 2022

**Comment by HectorSVC** [comment]
--arm64 is for cross build on x64, not required if you build on Windows Arm64 platform.

**Comment by HectorSVC** [comment]
try with --cmake_extra_defines CMAKE_CXX_FLAGS="/bigobj" if it still fails

**Comment by HectorSVC** [comment]
seems it cross build for arm64 on x64 worked.  and it only happens to Release build.

**Comment by HectorSVC** [comment]
Fix merged. Please give it a try with the latest main branch.
