### ISSUE TITLE
CUDA failure 304: OS call failed or operation not supported on this OS 

### ISSUE THREAD

**Issue by verigle** [microsoft/onnxruntime#20421]
### Describe the issue

*************** EP Error ***************
*************** EP Error ***************
EP Error /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:114 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 304: OS call failed or operation not supported on this OS ; GPU=32694 ; hostname=a49836633c38 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider.cc ; line=245 ; expr=cudaSetDevice(info_.device_id); 

### To reproduce

host :
OS centos 7
Driver Version: 550.54.14
driver: Driver Version: 550.54.14

docker: 
base image: nvidia/cuda:12.2.2-cudnn8-runtime-ubuntu20.04
onnxtunrime install cmd : pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/

### Urgency

test package: [insightface](https://github.com/deepinsight/insightface/tree/master/python-package)

test code: 
```python
import cv2
import numpy as np
import insightface
from insightface.app import FaceAnalysis
from insightface.data import get_image as ins_get_image

app = FaceAnalysis(providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
app.prepare(ctx_id=0, det_size=(640, 640))
img = ins_get_image('t1')
faces = app.get(img)
rimg = app.draw_on(img, faces)
cv2.imwrite("./t1_output.jpg", rimg)
```

### Platform

Linux

### OS Version

centos 7 for Host OS （ubuntu20.04 for docker image）

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17	

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

12.2

**Comment by snnn** [comment]
You need to upgrade your host OS, because ubuntu20.04 is newer than CentOS7
