### ISSUE TITLE
build with --build_wheel but still I cannot use it.

### ISSUE THREAD

**Issue by WilliamZhaoz** [microsoft/onnxruntime#2046]
I run sudo ./build.sh --config RelWithDebInfo --use_mkldnn --build_wheel --parallel
succeed.
but I can not import onnxruntime in python
then I change the python path in build.sh
still does not work,
then I change my python version
and then I copy the onnxruntime/build/Linux/RelWithDebInfo/onnxruntime folder into /home/username/anaconda3/envs/envname/lib/python3.5/site-packages/onnxruntime/
finally I can import onnxruntime in my python
but when I run my python script.
I got another error.:
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Non-zero status code returned while running MkldnnCustomOp15 node. Name:'MKLDNNExecutionProvider_MkldnnCustomOp15_14' Status Message: BatchNorm: Please call default CPU kernel.
you can find the whole log in attached file.
[log.log](https://github.com/microsoft/onnxruntime/files/3703328/log.log)

**Comment by jywu-msft** [comment]
btw, the python whl is created and placed under the build/Linux/RelWithDebInfo/dist 
you should install it.

the whl doesn't get created if there are any errors/test errors during the build process.
you can skip tests by adding --update --build options to your build.sh commandline.

**Comment by WilliamZhaoz** [comment]
after I adding --update --build options, I can not import onnxruntime
directory.
should I have to build and then install and then move the python lib into
the python sys path?


George Wu <notifications@github.com> 于2019年10月9日周三 上午12:03写道：

**Comment by skottmckay** [comment]
Did you install the wheel from the build output? 

e.g. something like `pip install ./build/Linux/RelWithDebInfo/dist/onnxruntime-0.5.0-cp36-cp36m-linux_x86_64.whl 
`

The whl filename may differ slightly depending on your configuration.

**Comment by WilliamZhaoz** [comment]
I tryed to use pip install and to copy the folder, the result is same, I
can not use it with some bugs.
and
@George Wu, I checked my model code, there is no batchnorm3d, only 1d and
2d, so onnxruntime with mkldnn cannot support batchnorm?

Scott McKay <notifications@github.com> 于2019年10月9日周三 上午11:59写道：

**Comment by WilliamZhaoz** [comment]
https://github.com/microsoft/onnxruntime/issues/2058

**Comment by jywu-msft** [comment]
sorry i meant 1d batchnorm.  you're encountering this limitation of mkldnn: https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/mkldnn/subgraph/mkldnn_batchnorm.h#L135


> I tryed to use pip install and to copy the folder, the result is same, I
> can not use it with some bugs.
> and
> @george Wu, I checked my model code, there is no batchnorm3d, only 1d and
> 2d, so onnxruntime with mkldnn cannot support batchnorm?
> 
> Scott McKay <notifications@github.com> 于2019年10月9日周三 上午11:59写道：
> …

**Comment by faxu** [comment]
@WilliamZhaoz is assistance still needed for this issue?

**Comment by verigle** [comment]
Python 3.7.5 (default, Oct 25 2019, 15:51:11) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime
/home/verigle/miniconda3/envs/pytorch/lib/python3.7/site-packages/onnxruntime/capi/_pybind_state.py:13: UserWarning: Cannot load onnxruntime.capi. Error: 'Python version mismatch: module was compiled for Python 3.6, but the interpreter version is incompatible: 3.7.5 (default, Oct 25 2019, 15:51:11) 
[GCC 7.3.0].'
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'".format(str(e)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/verigle/miniconda3/envs/pytorch/lib/python3.7/site-packages/onnxruntime/__init__.py", line 12, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, RunOptions, SessionOptions, set_default_logger_severity, NodeArg, ModelMetadata, GraphOptimizationLevel, ExecutionMode
ImportError: cannot import name 'get_all_providers' from 'onnxruntime.capi._pybind_state' (/home/verigle/miniconda3/envs/pytorch/lib/python3.7/site-packages/onnxruntime/capi/_pybind_state.py)

**Comment by wwbnjsace** [comment]
> btw, the python whl is created and placed under the build/Linux/RelWithDebInfo/dist
> you should install it.
> 
> the whl doesn't get created if there are any errors/test errors during the build process.
> you can skip tests by adding --update --build options to your build.sh commandline.

my command is"  sudo ./build.sh --config RelWithDebInfo --build_wheel --use_openvino CPU_FP32 --parallel --skip_tests --update --build". but it does not generate any *.whl file in any location .
