### ISSUE TITLE
[Documentation Request] The web "Get started" document and the "js" folder contradict to each other

### ISSUE THREAD

**Issue by tibortakacs** [microsoft/onnxruntime#20465]
[Enter feedback here]
https://github.com/microsoft/onnxruntime/blob/main/js/web/README.md
This is the one, detailed documentation about web, it writes the WebGPU is still in experimental, the the supported platforms table seems to be different to the one which is written in the "Get started" document. This can confuse the developers whether they can commit to WebGPU or not.

---
#### Document Details
* Title: Web
* Page: [https://onnxruntime.ai/docs/get-started/with-javascript/web.html](https://onnxruntime.ai/docs/get-started/with-javascript/web.html)
* Page Source: web.md

**Comment by fs-eire** [comment]
Thank you for the feedback. The support table is out of dated and should be updated.

WebGPU is still considered experimental features but we are keeping working on it with both stability and performance improvement. We are expecting to make it official at v1.19.0 release

**Comment by fs-eire** [comment]
#20492 updated the README with latest info about support table.
