### ISSUE TITLE
Uncaught (in promise) Error: no available backend found. ERR: [wasm] TypeError: Cannot read properties of undefined (reading 'buffer'), [cpu] Error: previous call to 'initializeWebAssembly()' failed., [xnnpack] Error: previous call to 'initializeWebAssembly()' failed.[Web] 

### ISSUE THREAD

**Issue by dongxingwangna** [microsoft/onnxruntime#20463]
### Describe the issue

import { Models } from '../type';
import Editor from '../Editor';
import { env, InferenceSession } from 'onnxruntime-web';
import SAM from '@/model/modelFiles/sam_quantized.onnx?url';
import ortWasm from '@/model/modelWasm/ort-wasm.wasm?url';
import ortWasmSimd from '@/model/modelWasm/ort-wasm-simd.wasm?url';
import ortWasmThreaded from '@/model/modelWasm/ort-wasm-threaded.wasm?url';
import ortWasmSimdThreaded from '@/model/modelWasm/ort-wasm-simd-threaded.wasm?url';

env.debug = true;
// log level
env.logLevel = 'info';
// wasm
env.wasm.numThreads = 2;
env.wasm.simd = true;
env.wasm.wasmPaths = {
    'ort-wasm.wasm': ortWasm,
    'ort-wasm-simd.wasm': ortWasmSimd,
    'ort-wasm-threaded.wasm': ortWasmThreaded,
    'ort-wasm-simd-threaded.wasm': ortWasmSimdThreaded,
};

export default class ModelManager {
    editor: Editor;
    modelMap: Map<Models, InferenceSession> = new Map();
    modelPath: Record<Models, string> = {
        [Models.SAM]: SAM,
    };

    constructor(editor: Editor) {
        this.editor = editor;
    }

    async getModel(name: Models) {
        let model = this.modelMap.get(name);
        if (!model) {
            this.editor.showLoading(true);
            console.log('ModelManager.ts:44 ==> this.modelPath[name]-->', this.modelPath[name]);
            model = await InferenceSession.create(this.modelPath[name]);
            this.modelMap.set(name, model);
            this.editor.showLoading(false);
        }
        return model;
    }

    async runModel(name: Models) {
        let model = await this.getModel(name);
        console.log('ModelManager.ts:49 ==> model-->', model);
    }
}
When I run the run model here, the program gets an error and the version I'm using is 1.17.3.

### To reproduce

vite + vue3+onnxruntime-web1.17.3

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.17.3

### Execution Provider

'wasm'/'cpu' (WebAssembly CPU)

**Comment by fs-eire** [comment]
The error message `TypeError: Cannot read properties of undefined (reading 'buffer')` is probably because of the web assembly artifact file is not served correctly in the server. could you check that browser downloads the corresponding .wasm files successfully?

**Comment by gcrois** [comment]
Just did some debugging here -- in my environment, it looks like `onnxruntime-web` sends a request for `/ort-wasm-simd.wasm` which isn't included by the bundler. If I put the required files in `/public`, it works fine.
