### ISSUE TITLE
[Build] Request for instructions to cross compile for aarch64

### ISSUE THREAD

**Issue by chiru091096** [microsoft/onnxruntime#20460]
### Describe the issue

I'm trying to cross compile onnxruntime for aarch64 on x86 machine. I used the command `./build.sh --build_shared_lib --config MinSizeRel --arm64 --update --build`. However, this command generated .so for x86. libonnxruntime.so is generated in _build/Linux/MinSizeRel/_ folder. I used the `file` command in ubuntu to check the architecture and it printed
`ELF 64 bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked `
What are the correct steps to cross-compile for aarch64?

### Target platform

Aarch64

### Build script

./build.sh --build_shared_lib --config MinSizeRel --arm64 --update --build

### Error / output

ELF 64 bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked

**Comment by jay11ca39** [comment]
@chiru091096 are you able to resolve it.. 
Even I am facing the same error for aarch64
Used same build command as yours ..

**Comment by snnn** [comment]
See: https://onnxruntime.ai/docs/build/inferencing.html
