### ISSUE TITLE
Quantized model show different results between x86_64 and aarch64 (CPU)

### ISSUE THREAD

**Issue by oewi** [microsoft/onnxruntime#20479]
### Describe the issue

I tried both dynamic quantization and static quantization from onnxruntime
Quantization process is successful.

When I compared the results of inference on linux x86_64 and linux aarch64 machines with the same input, they were different. Please verify if it's correct that the results differ depending on the architecture when quantization is applied. If there's a way to obtain the same results by turning off specific ONNXRuntime build options, I would appreciate any advice.

Thank you in advance.

### To reproduce

version:  v1.16.3

build option: ./build.sh --config=Release --build_shared_lib --minimal_build --disable_ml_ops --disable_exceptions --disable_rtti --skip_tests

quantization : 
from onnxruntime.quantization import quantize_dynamic, quantize_static
op_types_to_quantize=["MatMul"],
 weight_type=QuantType.QInt8,

### Platform

Linux

### OS Version

ubuntu 20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.16.3

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by yufenglee** [comment]
How much different do you see? It is expected that they are not exactly same.

**Comment by oewi** [comment]
log-softmax score difference (upper bound)

dynamic quantization -  1e-1
static quantization - 1e-2

When applying dynamic quantization, I anticipated there would be some degree of difference. However, with static quantization, shouldn't all values be fixed, yielding the same results regardless of cpu architecture? Is it possible to eliminate differences by adjusting the calibration data or the ONNX Runtime quantization options?
