### ISSUE TITLE
Error Installing ONNX Runtime GPU with CUDA 12.0: The project does not support adding package references through the add package command.

### ISSUE THREAD

**Issue by jpower10** [microsoft/onnxruntime#20523]
Followed instructions to install ONNX Runtime GPU with CUDA 12.x

Created a C++ console app using Visual Studio 2019. cd'd into path with .vcxproj and nuget.config files.

The error occurs when executing: dotnet add package Microsoft.ML.OnnxRuntime.Gpu

Error trace:   Determining projects to restore...
  Writing C:\Users\joshp\AppData\Local\Temp\tmpABC7.tmp
  info : X.509 certificate chain validation will use the default trust store selected by .NET.
  info : X.509 certificate chain validation will use the default trust store selected by .NET.
  info : Adding PackageReference for package 'Microsoft.ML.OnnxRuntime.Gpu' into project 'C:\Users\joshp\source\repos\MobileNetCUDA12\MobileNetCUDA12\MobileNetCUDA12.vcxproj'.
  error: Error while adding package 'Microsoft.ML.OnnxRuntime.Gpu' to project 'C:\Users\joshp\source\repos\MobileNetCUDA12\MobileNetCUDA12\MobileNetCUDA12.vcxproj'. The project does not support adding package references through the add package command.
  
  
  Usage: NuGet.CommandLine.XPlat.dll package add [options]
  
  Options:
    -h|--help               Show help information
    --force-english-output  Forces the application to run using an invariant, English-based culture.
    --package               Id of the package to be added.
    --version               Version of the package to be added.
    -d|--dg-file            Path to the dependency graph file to be used to restore preview and compatibility check.
    -p|--project            Path to the project file.
    -f|--framework          Frameworks for which the package reference should be added.
    -n|--no-restore         Do not perform restore preview and compatibility check. The added package reference will be unconditional.
    -s|--source             Specifies NuGet package sources to use during the restore.
    --package-directory     Directory to restore packages in.
    --interactive           Allow the command to block and require manual action for operations like authentication.
    --prerelease            Allows prerelease packages to be installed.

dotnet version: 6.0.421
CUDA: 12.0.1 
OS: Windows 10

---
#### Document Details
* Title: Error Installing ONNX Runtime GPU with CUDA 12.0: The project does not support adding package references through the add package command.
* Page: [https://onnxruntime.ai/docs/install/](https://onnxruntime.ai/docs/install/)
* Page Source: index.md

**Comment by yuslepukhin** [comment]
This might be helpful. https://github.com/obfuscar/example/issues/1#issuecomment-1071671373
We install it all the time.

**Comment by yuslepukhin** [comment]
The error message can be improved. I suggest filing an issue with dot net team.

**Comment by jpower10** [comment]
> This might be helpful. [obfuscar/example#1 (comment)](https://github.com/obfuscar/example/issues/1#issuecomment-1071671373) We install it all the time.

I suppose in my case I would need to inspect the .vcxproj file since I'm using C++. Upon inspecting this file there is no TargetFrameworkVersion field. Is this expected?

**Comment by yuslepukhin** [comment]
We are not VS Studio team.
From my experience, even though the IDE supposed to make things right for you, I found that one needs to open the project file and write many things manually. In particular, `TargetFrameworkVersion `.
I strongly suggest reading all about it, its monikers and setting the Language Version in the project (default is recommended).
The above would include reading about NETSTANDARD, NetCore, .NET Framework and .NET.
I know it is a lot, but that is the way things are. Until I digested that, I did not really understand how to create projects.
See [this](https://github.com/microsoft/onnxruntime/blob/main/csharp/src/Microsoft.ML.OnnxRuntime/Microsoft.ML.OnnxRuntime.csproj#L50) to get some ideas.

The other way to add dependencies via a separate config file.

**Comment by jpower10** [comment]
It might be helpful to add some instructions [here](https://onnxruntime.ai/docs/install/#install-onnx-runtime-gpu-cuda-12x-1) with regards to manually editing project files for CUDA 12.0 setups, or adding relevant details to the config file that's already populated.
