### ISSUE TITLE
[Mobile] Using flatDir should be avoided because it doesn't support any meta-data formats.

### ISSUE THREAD

**Issue by sirramin** [microsoft/onnxruntime#20535]
### Describe the issue

When I try to build react native for android with android studio I got following error:
 Using flatDir should be avoided because it doesn't support any meta-data formats.
I think the error comes from this line in package's build.gradle file:
`flatDir {
    dir 'libs'
  }`

### To reproduce

Build an app containing onnxruntime-react-native module in a react native android project with android studio

### Platform

Android

### OS Version

12

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

onnxruntime-react-native

### ONNX Runtime Version or Commit ID

1.16.3

### ONNX Runtime API

JavaScript

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
Error or warning?
