### ISSUE TITLE
 Unsupported model IR version: 10, max supported IR version: 9

### ISSUE THREAD

**Issue by lix19937** [microsoft/onnxruntime#20559]
### Describe the issue

sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from positional_encoding_poly.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model.cc:179 onnxruntime::Model::Model(onnx::ModelProto&&, const onnxruntime::PathString&, const onnxruntime::IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, const onnxruntime::ModelOptions&) Unsupported model IR version: 10, max supported IR version: 9

### To reproduce

onnx                      1.16.0      
onnx-graphsurgeon         0.3.21     
onnx-simplifier           0.4.36      
onnxruntime               1.17.1      

### Platform

Linux

### OS Version

ubuntu20.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by lix19937** [comment]
https://discuss.pytorch.org/t/runtimeerror-unexpected-tensor-scalar-type/124031  it works.

**Comment by lix19937** [comment]
downgrade the version of onnx to v1.15.0

**Comment by cheyue** [comment]
升级 onnxruntime 到最新版本即可

**Comment by scalaboy** [comment]
this error is raise from  onnxruntime 。
pip need upgrade。any way,cannot install  onnxruntime==1.19.1。
1）first  pip install --upgrade pip
2）then.  pip install onnxruntime==1.19.1 
bug fixed

**Comment by abagh0703** [comment]
> 2）then. pip install onnxruntime==1.19.1

@scalaboy's solution worked for me, just had to change it to 1.19.2 since [1.19.1 doesn't seem to exist](https://pypi.org/project/onnxruntime/#history)

**Comment by snnn** [comment]
The latest version is 1.20.1.  Welcome to upgrade.

**Comment by TurcanVeli** [comment]
There is no properly solution about this problem. I have down and up versions and tried everything. But Can old .dll file be problem?

**Comment by snnn** [comment]
Which onnxruntime python package version do you have?

**Comment by TurcanVeli** [comment]
I fix the solution for me. I just reduced op count of the onnx model from 19 to 13
onnxruntime python package version = 15.0.0
