### ISSUE TITLE
LLama2 convert_to_onnx.py does not fuse GQA

### ISSUE THREAD

**Issue by turneram** [microsoft/onnxruntime#20552]
### Describe the issue

Using `onnxruntime.transformers.models.llama.convert_to_onnx` with `--use_gqa` does not produce a model with GroupQueryAttention nodes.

### To reproduce

`python3 -m onnxruntime.transformers.models.llama.convert_to_onnx -m meta-llama/Llama-2-7b-hf --output llama2-7b-fp16 --precision fp16 --execution_provider cuda --use_gqa` 
The only fusions reported are SimplifiedLayernormalization and SkipSimplifiedLayernormalization, and the final model only contains attention in the un-fused format pictured below:
![image](https://github.com/microsoft/onnxruntime/assets/71655887/3502577c-00cc-4bac-ae4a-5a887b9178ef)

### Platform

Linux

### OS Version

22.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

030a9611c240ca838fca0f0d789bb2105604166d

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 12.1.1

**Comment by kunal-vaishnavi** [comment]
What does your environment look like? Do you have all of the [prerequisite packages and their versions](https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/models/llama/README.md#prerequisites) installed?
