### ISSUE TITLE
yolov8 onnxruntime error -1073740791 (0xC0000409)

### ISSUE THREAD

**Issue by LuminaDevelopment** [microsoft/onnxruntime#20566]
### Describe the issue

I receive the error -1073740791 (0xC0000409) whenever I try to test the onnxruntime object detection, i was trying to test the differences between running a native YOLOv8 object detection model (.pt) versus the same model converted to ONNX Runtime, and ran using only onnxruntime. I've attempted multiple ONNX Runtime projects from GitHub, including coding my own, but consistently encounter the same error. Most recently, I tried the project at https://github.com/ibaiGorordo/ONNX-YOLOv8-Object-Detection, but it also failed.

specs:

CPU: AMD Ryzen 7 5800X3D 8-Core Processor
memory:  (64 gb)
GPU: NVIDIA GeForce RTX 4090 - 24GB memory

### To reproduce

im not sure how i can explain how to reproduce other than git clone https://github.com/ibaiGorordo/ONNX-YOLOv8-Object-Detection and then run one of the detection scripts

### Urgency

I'm a student and i don't have much free time so its a bit urgent ;)

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

v1.17.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 11.8

**Comment by LuminaDevelopment** [comment]
i think it might be my cuda setup thats messed up, does anyone have an docker container or something for cuda?

**Comment by tianleiwu** [comment]
@LuminaDevelopment,

Try nvidia container like
`
docker run --rm -it --gpus all -v $PWD:/workspace nvcr.io/nvidia/pytorch:23.10-py3 /bin/bash
`
Then install onnxruntime-gpu for CUDA 12.

**Comment by LuminaDevelopment** [comment]
i dont really know how i fixed the problem, all i did was recoded the entire program and it worked, no idea how it got fixed lol.
