### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: /tmp/onnxruntime-java8147263448488960156/libonnxruntime.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/onnxruntime-java8147263448488960156/libonnxruntime.so)

### ISSUE THREAD

**Issue by wangkd0** [microsoft/onnxruntime#20588]
### Describe the issue

我使用Java+opencv+onnxruntime进行模型的推理，并打算使用docker进行部署该springboot项目，下面是我的dockerfile文件内容：

FROM openjdk:8u212-jre

COPY lib/ /photo/lib

ENV LD_LIBRARY_PATH=/photo/lib

COPY boot-server-1.0.0.jar  /boot-photo/boot-photo-1.0.0.jar

ENTRYPOINT ["java","-jar","-Dfile.encoding=utf-8","/boot-photo/boot-photo-1.0.0.jar"]

当我启动时，报错：
Caused by: java.lang.UnsatisfiedLinkError: /tmp/onnxruntime-java8147263448488960156/libonnxruntime.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/onnxruntime-java8147263448488960156/libonnxruntime.so)

请问应该怎么在docker中部署使用呢？

### To reproduce

如上所述

### Platform

Other / Unknown

### OS Version

docker

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.17.1

### ONNX Runtime API

Java

### Architecture

Other / Unknown

### Execution Provider

Other / Unknown

**Comment by Craigacp** [comment]
What's the base image of the dockerfile? The error comes is because the image is not using a new enough glibc which can typically be caused by using RHEL7, an old Ubuntu, or by basing on a distro which uses musl rather than glibc. If you need to use that exact image then you might be able to compile ORT from source inside the container.

**Comment by albertoandreottiATgmail** [comment]
Can we please have a table somewhere so we don't have to guess or do trial an error when we want to find pout if a onnxruntime is gonna run in some OS?

**Comment by Craigacp** [comment]
The Python wheels currently baselined on manylinux 2.27 for glibc 2.27, and I think the build pipelines are sufficiently similar that that should be true for Java.

**Comment by albertoandreottiATgmail** [comment]
Thank for the answer so we're on 2.27 for the moment. Good.
