### ISSUE TITLE
[Build] LoadLibrary failed with error 126

### ISSUE THREAD

**Issue by johnny857** [microsoft/onnxruntime#20589]
### Describe the issue

![image](https://github.com/microsoft/onnxruntime/assets/21231884/598a6985-4967-4a4d-8104-bf407137bb3d)

### Urgency

Microsoft.ML.OnnxRuntime.OnnxRuntimeException:“[ErrorCode:RuntimeException] D:\a_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\Projects\Yolov8.Net\Yolo.Net.FromTest\bin\Debug\net6.0-windows\runtimes\win-x64\native\onnxruntime_providers_cuda.dll

### Target platform

Windows 10

### Build script

if (useCuda) 
_inferenceSession = new InferenceSession(modelPath, SessionOptions.MakeSessionOptionWithCudaProvider()); 
else
 _inferenceSession = new InferenceSession(modelPath);

### Error / output

Microsoft.ML.OnnxRuntime.OnnxRuntimeException:“[ErrorCode:RuntimeException] D:\a_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1193 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\Projects\Yolov8.Net\Yolo.Net.FromTest\bin\Debug\net6.0-windows\runtimes\win-x64\native\onnxruntime_providers_cuda.dll

### Visual Studio Version

17.7

### GCC / Compiler Version
I am using the following content: Microsoft.ML.OnnxRuntime.GPU (nuget package VERSION 1.16.0)
NVIDIA CUDA Tool Kit (VERSION 11.3)
CUDNN (VERSION 8.2)
_No response_

**Comment by matmatos** [comment]
I had a similar issue, take a look at this: #20597
