### ISSUE TITLE
[Build] Cross compilation for Nvidia Jetson fails at compiler check due to -fcf-protection flag

### ISSUE THREAD

**Issue by ReneNijhuis** [microsoft/onnxruntime#20596]
### Describe the issue

I am using the Nvidia cross compilation container, [from here](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/jetpack-linux-aarch64-crosscompile-x86), to try to build ORT for Jetson Orin Nano. We need the C++ bindings so the Jetson Zoo Python package will not work. Furthermore, compiling on the device itself takes forever since it runs out of memory when using multiple threads so cross compilation is a must. 

The container has the cross compilation environment completely setup but using the `build.sh` script fails. It adds the `-fcf-protection` compiler flag asuming that a build on x86_64-linux will be a native build. Adding the `--arm64` flag has no effect. 
For the CMake toolchain file we use the one Nvidia provides in the container with the VPI3 samples.

### Urgency

Low. 
We can work around this by manually patching the `tools/ci_build/build.py` file to not add the flag or modifying the toolchain file to replace `"-fcf-protection"` with `""` in all `CMAKE_<LANG>_FLAGS` strings.

While a workaround exists, a much better way would be to have `build.py` respect the --arm flags and not assume native compilation under linux as well.

### Target platform

amd64 -> aarch64

### Build script

```shell
export PATH=/usr/local/cuda-12.2/bin:$PATH
./build.sh --allow_running_as_root --config Release --update --build --skip_tests --parallel --build_shared_lib --compile_no_warning_as_error --use_tensorrt --cuda_home /usr/local/cuda-12.2 --cudnn_home /usr/lib/aarch64-linux-gnu --tensorrt_home /usr/lib/aarch64-linux-gnu --cmake_extra_defines CMAKE_TOOLCHAIN_FILE=/opt/nvidia/vpi3/samples/08-cross_aarch64_l4t/Toolchain_aarch64_l4t.cmake CMAKE_SYSROOT=/l4t/targetfs
```

### Error / output

... Snip compiler detection output
> -- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc
> -- Check for working C compiler: /usr/bin/aarch64-linux-gnu-gcc - broken
> CMake Error at /usr/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:67 (message):
>   The C compiler
> 
>     "/usr/bin/aarch64-linux-gnu-gcc"
> 
>   is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>     Change Dir: '/l4t/ws/onnxruntime/build/Linux/Release/CMakeFiles/CMakeScratch/TryCompile-0m4hHd'
> 
>     Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_baa6a/fast
>     /usr/bin/gmake  -f CMakeFiles/cmTC_baa6a.dir/build.make CMakeFiles/cmTC_baa6a.dir/build
>     gmake[1]: Entering directory '/l4t/ws/onnxruntime/build/Linux/Release/CMakeFiles/CMakeScratch/TryCompile-0m4hHd'
>     Building C object CMakeFiles/cmTC_baa6a.dir/testCCompiler.c.o
>     /usr/bin/aarch64-linux-gnu-gcc --sysroot=/l4t/targetfs   -DNDEBUG -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -O3 -pipe -fstack-clash-protection -fcf-protection  -o CMakeFiles/cmTC_baa6a.dir/testCCompiler.c.o -c /l4t/ws/onnxruntime/build/Linux/Release/CMakeFiles/CMakeScratch/TryCompile-0m4hHd/testCCompiler.c
>     cc1: error: ‘-fcf-protection=full’ is not supported for this target
>     gmake[1]: *** [CMakeFiles/cmTC_baa6a.dir/build.make:78: CMakeFiles/cmTC_baa6a.dir/testCCompiler.c.o] Error 1
>     gmake[1]: Leaving directory '/l4t/ws/onnxruntime/build/Linux/Release/CMakeFiles/CMakeScratch/TryCompile-0m4hHd'
>     gmake: *** [Makefile:127: cmTC_baa6a/fast] Error 2
> 
> 
> 
> 
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:20 (project)
> 
> 
> -- Configuring incomplete, errors occurred!

... Snip python reporting cmake failed

### GCC / Compiler Version

aarch64-linux-gnu-gcc cross compiler, gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

**Comment by snnn** [comment]
The latest code in the main branch should not have this problem. Or you manually set CFLAGS and CXXFLAGS environment variables to something.
