### ISSUE TITLE
Load  External Data with AddExternalInitializers and output nan

### ISSUE THREAD

**Issue by TalkUHulk** [microsoft/onnxruntime#20594]
### Describe the issue

I convert  [stable-diffusion-inpainting](https://huggingface.co/runwayml/stable-diffusion-inpainting) according to [optimum](https://huggingface.co/docs/diffusers/optimization/onnx). The model is larger than 2GB, so it was generated model.onnx_data(External Data). This is my first time encountering this format and I load models with AddExternalInitializers. But the model always output nan.  

I also converting an vae decoder to External Data according [ExternalData](https://github.com/onnx/onnx/blob/main/docs/ExternalData.md), The result is also nan.

And I random check initializer_data with corresponding parameters in pytorch.  The first few decimal places are the same.

![iShot_2024-05-07_18 03 41](https://github.com/microsoft/onnxruntime/assets/18474163/4afee3ad-2965-45ba-9cbb-c0bb6a500bc6)

### To reproduce

This is my test demo: [example.cpp.txt](https://github.com/microsoft/onnxruntime/files/15233863/example.cpp.txt)
Unet Model from:  [stable-diffusion-inpainting](https://huggingface.co/runwayml/stable-diffusion-inpainting) 
Convert CMD: `optimum-cli export onnx --task stable-diffusion  --model stable-diffusion-inpainting stable-diffusion-inpainting-onnx`

### Platform

Mac

### OS Version

14.4.1

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.3

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by lxp3** [comment]
"std::vector<float> data(size, 0); " An empty vector was initialized, but forgot to fill it with the values from raw_data (offset, offset + length).

**Comment by TalkUHulk** [comment]
> "std::vector data(size, 0); " An empty vector was initialized, but forgot to fill it with the values from raw_data (offset, offset + length).

[example.cpp.txt](https://github.com/microsoft/onnxruntime/files/15242598/example.cpp.txt)


I'm sorry I lost  `raw_data.read ` when copying.  The model still outputs nan. Can you check where there is a problem with my code. Thanks😊

**Comment by TalkUHulk** [comment]
And I random check initializer_data with corresponding parameters in pytorch. The first few decimal places are the same.

<img width="584" alt="iShot_2024-05-08_09 19 44" src="https://github.com/microsoft/onnxruntime/assets/18474163/74debc1f-bbbf-4ff5-8178-2af677eb7479">

**Comment by TalkUHulk** [comment]
When I comment out the line: `session_options.AddExternalInitializers(init_names, initializer_data);`,  The parameters may be randomly initialized？ And  model does not output nan.
<img width="876" alt="iShot_2024-05-08_09 49 49" src="https://github.com/microsoft/onnxruntime/assets/18474163/e7582463-8ba7-4263-b6a2-fd9087f8cca6">

**Comment by tianleiwu** [comment]
@TalkUHulk, you do not need AddExternalInitializers unless you want to overwrite the weights (like using LoRA weights).

Just put the *.onnx model and external data file in same folder, and create a session using the path of .onnx file. Then you can run inference on the model.

**Comment by TalkUHulk** [comment]
> @TalkUHulk, you do not need AddExternalInitializers unless you want to overwrite the weights (like using LoRA weights).
> 
> Just put the *.onnx model and external data files in same folder, and create a session using the path of .onnx file. Then you can run inference on the model.

Thanks,I found that it will automatically load weights.  I would like to know if I can manually load it (like using LoRA weights).🌹

**Comment by tianleiwu** [comment]
> Thanks,I found that it will automatically load weights. I would like to know if I can manually load it (like using LoRA weights).🌹

Yes, you can manually overwrite the weights.

Follow the example:
https://github.com/microsoft/onnxruntime/blob/69cfcba38a60d65498f94cde30cb9c2030f7255b/onnxruntime/test/shared_lib/test_model_loading.cc#L101-L119

For example, you can overwrite some weights to ones, and save the optimized model, and verify the weights have been updated (using onnx API to read initializer data).
