### ISSUE TITLE
build from source but hit a core dump error

### ISSUE THREAD

**Issue by WilliamZhaoz** [microsoft/onnxruntime#2060]
when I run 
./build.sh --config RelWithDebInfo --use_mklml --build_wheel --parallel
I got a core dump, 
2019-10-09 02:30:59,398 Build [INFO] - Build started
2019-10-09 02:30:59,398 Build [INFO] - Building targets for RelWithDebInfo configuration
2019-10-09 02:30:59,398 Build [DEBUG] - Running subprocess in '/data/home/zhiyzh/workspace/onnxruntime'
['/usr/local/bin/cmake', '--build', '/data/home/zhiyzh/workspace/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '-j6']
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
/bin/sh: line 1: 29510 Aborted                 (core dumped) ../external/protobuf/cmake/protoc --cpp_out lite:/data/home/zhiyzh/workspace/onnxruntime/build/Linux/RelWithDebInfo/onnx -I /data/home/zhiyzh/workspace/onnxruntime/onnxruntime/core/protobuf /data/home/zhiyzh/workspace/onnxruntime/onnxruntime/core/protobuf/onnx-operators-ml.proto
make[2]: *** [onnx/onnx-operators-ml.pb.h] Error 134
make[2]: *** Waiting for unfinished jobs....
/bin/sh: line 1: 29511 Aborted                 (core dumped) ../external/protobuf/cmake/protoc --cpp_out lite:/data/home/zhiyzh/workspace/onnxruntime/build/Linux/RelWithDebInfo/onnx -I /data/home/zhiyzh/workspace/onnxruntime/onnxruntime/core/protobuf /data/home/zhiyzh/workspace/onnxruntime/onnxruntime/core/protobuf/onnx-ml.proto
make[2]: *** [onnx/onnx-ml.pb.h] Error 134
make[1]: *** [onnx/CMakeFiles/onnx_proto.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "/data/home/zhiyzh/workspace/onnxruntime/tools/ci_build/build.py", line 1018, in <module>
    sys.exit(main())
  File "/data/home/zhiyzh/workspace/onnxruntime/tools/ci_build/build.py", line 959, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "/data/home/zhiyzh/workspace/onnxruntime/tools/ci_build/build.py", line 452, in build_targets
    run_subprocess(cmd_args)
  File "/data/home/zhiyzh/workspace/onnxruntime/tools/ci_build/build.py", line 194, in run_subprocess
    return subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/home/zhiyzh/anaconda3/envs/psnet/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/data/home/zhiyzh/workspace/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '-j6']' returned non-zero exit status 2

[log.log](https://github.com/microsoft/onnxruntime/files/3705324/log.log)

**Comment by snnn** [comment]
Could you please find the 'external/protobuf/cmake/protoc' and run 
```
ldd external/protobuf/cmake/protoc
```
, and give me the output.

**Comment by WilliamZhaoz** [comment]
the output is:
        linux-vdso.so.1 =>  (0x00007fff763a2000)                                           
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f76a15d9000)      
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f76a13c3000)              
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f76a0ff9000)                     
        /lib64/ld-linux-x86-64.so.2 (0x00007f76a195b000)                                     
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f76a0cf0000)

**Comment by snnn** [comment]
It's a compiler bug. libpthread should be there but it isn't.
What's your compiler version? Are you using the system compiler or gcc from anaconda?

**Comment by snnn** [comment]
https://github.com/protocolbuffers/protobuf/issues/5923

**Comment by WilliamZhaoz** [comment]
just system compiler /usr/bin/gcc
gcc version is 5.4.0

**Comment by WilliamZhaoz** [comment]
Hi snnn,
you said,
Need to insert '--no-as-needed' before the '-pthread' arg in the link command args of protoc.
how can I do in onnxruntime.

**Comment by snnn** [comment]
It need be done in protobuf.

**Comment by WilliamZhaoz** [comment]
so I have to rebuild my profobut?

**Comment by snnn** [comment]
Google need to fix the problem in protobuf first, then we'll pick up the fix. But Google may not do it because this is more like a compiler bug.  If you upgrade your operating system and compiler to a newer version, the problem will be gone.  

I'll close this bug because there isn't anything we can do.
