### ISSUE TITLE
[Build] Jetson orin nano unknown cmake error

### ISSUE THREAD

**Issue by av-happydroid** [microsoft/onnxruntime#20613]
### Describe the issue

I'm trying to build onnxruntime v1.16 on jetson orin nano which is running jetpack 5.1.1, by following the jetson-specific instructions [here](https://onnxruntime.ai/docs/build/eps.html#nvidia-jetson-tx1tx2nanoxavierorin). At ~79% through the build when it looks to be building 'onnxruntime_providers_cuda', CMake lists an 'Error 137' without any error description. I've tried to search through the source files for a list of build error codes as well as searching previous github issues for similar build errors, but have had no luck in any relevant solutions. Can anyone elaborate on where to search for relevant build error codes, and give any pointers in tracking down this vague error?

### Urgency

Moderate

### Target platform

Jetson Orin Nano (jetpack 5.1.1, cuda 11.8.89, cudnn 8.6.0.166)

### Build script

./build.sh --config Release --update --build --parallel --build_wheel \--use_tensorrt --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu \--tensorrt_home /usr/lib/aarch64-linux-gnu

### Error / output

[ 79%] Building CUDA object CMakeFiles/onnxruntime_providers_cuda.dir/home/robot/onnxruntime/onnxruntime/contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim128_bf16_sm80.cu.o
[ 79%] Building CUDA object CMakeFiles/onnxruntime_providers_cuda.dir/home/robot/onnxruntime/onnxruntime/contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim128_fp16_sm80.cu.o
Killed
make[2]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/build.make:6114: CMakeFiles/onnxruntime_providers_cuda.dir/home/robot/onnxruntime/onnxruntime/contrib_ops/cuda/bert/flash_attention/flash_fwd_hdim128_bf16_sm80.cu.o] Error 137
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:2117: CMakeFiles/onnxruntime_providers_cuda.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
Traceback (most recent call last):
  File "/home/robot/onnxruntime/tools/ci_build/build.py", line 2950, in <module>
    sys.exit(main())
  File "/home/robot/onnxruntime/tools/ci_build/build.py", line 2842, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/robot/onnxruntime/tools/ci_build/build.py", line 1731, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/robot/onnxruntime/tools/ci_build/build.py", line 861, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/robot/onnxruntime/tools/python/util/run.py", line 49, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/robot/.local/bin/cmake', '--build', '/home/robot/onnxruntime/build/Linux/Release', '--config', 'Release', '--', '-j6']' returned non-zero exit status 2.

### GCC / Compiler Version

10.5.0

**Comment by snnn** [comment]
$ sudo dmesg

Check if it ran of out memory.

**Comment by av-happydroid** [comment]
Hey thanks for the response. I have successfully built onnxruntime by removing the `--parallel` flag, though the build was very slow with one core. Are there any steps or diagnostics you can recommend to start to track down the memory issue? Is this a common issue building on the Jetson platform?

**Comment by snnn** [comment]
In general there is no good solution.  Almost every large project has this problem.  You need to monitor your system's logs to see if there anything related to "OOM killer".  If yes, get more memory or reduce your workload.

**Comment by snnn** [comment]
We cannot predict how much memory compilers need.

**Comment by av-happydroid** [comment]
Okay, thank you.
