### ISSUE TITLE
[Documentation] Model test link is outdated

### ISSUE THREAD

**Issue by gedoensmax** [microsoft/onnxruntime#20639]
### Describe the documentation issue

The link found here: https://github.com/microsoft/onnxruntime/blob/main/docs/Model_Test.md#get-more-models is outdated and no longer works. 

### Page / URL

https://github.com/microsoft/onnxruntime/blob/main/docs/Model_Test.md#get-more-models

**Comment by tianleiwu** [comment]
@snnn, could you take a look?
