### ISSUE TITLE
ONNXRuntimeError with a model that passes onnx.checker and was supported on previous ort versions

### ISSUE THREAD

**Issue by cestpasphoto** [microsoft/onnxruntime#20641]
### Describe the issue

I have a model exported by pytorch which was supported until ort 1.16.3 but now fails with ort 1.17.0:
`onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (MatMulBnFusion_Gemm) Op (Gemm) [ShapeInferenceError] First input does not have rank 2`

I have tried several versions of pytorch, several config of torch.onnx.export but always fail. As soon as I downgrade to 1.16.3, it works whatever the pytorch version is, so that makes me think that ort is the culprit.
Plus I've run `onnx.checker.check_model(mymodel, full_check=True)` and raised no issue.
It happens even with pure CPU environment.

The following code passes with ort 1.16.3 but returns an error with 1.17.0

### To reproduce

```
import onnx
import onnxruntime as ort

file = 'example_onnx_file.onnx'
mymodel = onnx.load(file)
onnx.checker.check_model(mymodel, full_check=True) # No error

ort.InferenceSession(file, providers=['CPUExecutionProvider']) # Raise an error
```

### Platform

Linux

### OS Version

Debian stable

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by cestpasphoto** [comment]
Please use the following file: https://github.com/cestpasphoto/alpha-zero-general/blob/master/splendor/example_onnx_file.onnx

To answer the auto-label, **CUDA is NOT involved** here, it happens with CPU-only environment.

**Comment by csukuangfj** [comment]
I get a similar error after switching from onnxruntime 1.17.1 to 1.18.0.

The error log can be found at
https://github.com/csukuangfj/sherpa-onnx/actions/runs/9204107994/job/25316940778#step:15:53

```
terminate called after throwing an instance of 'Ort::Exception'
  what():  Node (Loop_5471) Op (Loop) [TypeInferenceError] Graph attribute inferencing failed: Node (Concat_5490) Op (Concat) [ShapeInferenceError] All inputs to Concat must have same rank. Input 1 has rank 2 != 1
```

(Note that the only change is to use a newer version of onnxruntime. All other things are kept the same.)

**Comment by lumi-a** [comment]
Looks like it might be related to #20808

**Comment by cestpasphoto** [comment]
Correct. When using this snippet, I could convert the current ONNX to latest opset and onnxruntime can load such updated file.

The problem is that pytorch can export into ONNX up to opset 17:

https://pytorch.org/docs/stable/onnx_torchscript.html#torch.onnx.export

> opset_version ([int](https://docs.python.org/3/library/functions.html#int), default 17) – The version of the [default (ai.onnx) opset](https://github.com/onnx/onnx/blob/master/docs/Operators.md) to target. Must be >= 7 and <= 17.

So the easiest way to make a pytorch export works with onnxruntime is to: export with pytorch + convert to opset 21 with onnx + load updated onnx with onnxruntime.
