### ISSUE TITLE
[Web]  vue3+vite  wasm streaming compile failed: LinkError: WebAssembly.instantiate()

### ISSUE THREAD

**Issue by Mirror-Yu** [microsoft/onnxruntime#20653]
### Describe the issue

 I use Vue3+Vite to load onnxruntime-web;
 I get error :wasm streaming compile failed: LinkError: WebAssembly.instantiate()

### To reproduce

Here is a screenshot of my code and error:
home.vue:
import { env, InferenceSession } from 'onnxruntime-web';
env.wasm.wasmPaths = 'http://192.168.2.67:8085/sam/onnxruntime-web/dist/';
const model = await InferenceSession.create('http://192.168.2.67:8085/sam/sam_onnx_example.onnx');
error:
![image](https://github.com/microsoft/onnxruntime/assets/52779170/0ff28eb6-efcd-47e5-8eca-5a84d1169863)

### Urgency

Urgency!

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.1

### Execution Provider

Other / Unknown

**Comment by elite174** [comment]
@Mirror-Yu what was the issue? I faced the same thing for 1.18.0
