### ISSUE TITLE
[onnxruntime server] multiple models in a single container

### ISSUE THREAD

**Issue by nkennek** [microsoft/onnxruntime#2066]
**Is your feature request related to a problem? Please describe.**
No, it is just a request for enhancement

**Describe the solution you'd like**
I want to deal with multiple models on onnxruntime server like the way tensorflow serving already offers:

https://www.tensorflow.org/tfx/serving/serving_config
```
model_config_list {
  config {
    name: 'my_first_model'
    base_path: '/tmp/my_first_model/'
  }
  config {
    name: 'my_second_model'
    base_path: '/tmp/my_second_model/'
  }
}
```

Is there any perspective or actual progress on that?

**Comment by jywu-msft** [comment]
@NonStatic2014 @csteegz , FYI
