### ISSUE TITLE
Type Error: Type 'tensor(int64)' of input parameter (16586) of operator (Clip) in node (Clip_13292) is invalid.

### ISSUE THREAD

**Issue by lix19937** [microsoft/onnxruntime#20674]
### Describe the issue

Use ort to infer, then raise error: 
```
Type Error: Type 'tensor(int64)' of input parameter (16586) of operator (Clip) in node (Clip_13292) is invalid.
```

### To reproduce

```
onnx                      1.15.0
onnx-graphsurgeon         0.3.21
onnx-simplifier           0.4.36
onnxruntime               1.17.1
```

### Platform

Linux

### OS Version

ubuntu20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.15.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by lix19937** [comment]
onnxruntime not support torch.clamp ?

**Comment by lix19937** [comment]
https://github.com/microsoft/onnxruntime/issues/10399#issuecomment-1024588996    
https://github.com/microsoft/onnxruntime/issues/15167#issuecomment-1480631287

**Comment by edgchen1** [comment]
Clip should be supported with int64 input.
https://github.com/microsoft/onnxruntime/blob/v1.17.1/docs/OperatorKernels.md#cpuexecutionprovider

What ONNX opset version is the model using?

**Comment by lix19937** [comment]
> What ONNX opset version is the model using?   

opset_version in `torch.onnx.export` is 11, when I update to 13, no error.

**Comment by lix19937** [comment]
Thanks, closed.
