### ISSUE TITLE
AttributeError: module 'onnxruntime' has no attribute 'InferenceSession'

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#2068]
Build onnxruntime from source via:

```
./build.sh \
        --use_cuda \
        --cuda_version=10.1 \
        --cuda_home=/usr/local/cuda-10.1 \
        --cudnn_home=/usr/local/cuda-10.1 \
        --use_tensorrt --tensorrt_home=$HOME/TensorRT \
        --build_shared_lib --enable_pybind --build_wheel

```

It build finished and test passed, but when using python:

```
python3
Python 3.5.2 (default, Jul 10 2019, 11:58:48) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime
>>> sess = onnxruntime.InferenceSession()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'onnxruntime' has no attribute 'InferenceSession'
>>> 

```

What's wrong???

**Comment by jywu-msft** [comment]
what is your current working directory?
I suspect you are starting python from the onnxruntime source directory? 
if your current working directory has a subdirectory named onnxruntime, python will try to import that subdirectory as a module , which obviously won't work.

**Comment by jinfagang** [comment]
No, if in `onnxruntime` dir, it will can not import onnxruntime since it does a python package.
I cd to another dir to test.

My question is, the onnxruntime seems installed, the tests can pass, but can not using InferenceSession , and I can not found any wheel under `build`.

**Comment by jywu-msft** [comment]
can you share your build logs?
after the build/tests succeeds, the last thing it does is create the whl package. you should see something like below. (it was run on windows, but is similar on Linux)

running bdist_wheel
running build
running build_py
copying onnxruntime\__init__.py -> build\lib\onnxruntime
copying onnxruntime\backend\backend.py -> build\lib\onnxruntime\backend
copying onnxruntime\backend\backend_rep.py -> build\lib\onnxruntime\backend
copying onnxruntime\backend\__init__.py -> build\lib\onnxruntime\backend
copying onnxruntime\capi\onnxruntime_validation.py -> build\lib\onnxruntime\capi
copying onnxruntime\capi\session.py -> build\lib\onnxruntime\capi
copying onnxruntime\capi\_ld_preload.py -> build\lib\onnxruntime\capi
copying onnxruntime\capi\_pybind_state.py -> build\lib\onnxruntime\capi
copying onnxruntime\capi\__init__.py -> build\lib\onnxruntime\capi
copying onnxruntime\datasets\__init__.py -> build\lib\onnxruntime\datasets
copying onnxruntime\tools\onnxruntime_test.py -> build\lib\onnxruntime\tools
copying onnxruntime\tools\__init__.py -> build\lib\onnxruntime\tools
copying onnxruntime\capi\onnxruntime_pybind11_state.pyd -> build\lib\onnxruntime\capi
copying onnxruntime\datasets\mul_1.onnx -> build\lib\onnxruntime\datasets
copying onnxruntime\datasets\logreg_iris.onnx -> build\lib\onnxruntime\datasets
copying onnxruntime\datasets\sigmoid.onnx -> build\lib\onnxruntime\datasets
copying onnxruntime\LICENSE -> build\lib\onnxruntime
copying onnxruntime\ThirdPartyNotices.txt -> build\lib\onnxruntime
installing to build\bdist.win-amd64\wheel
running install
running install_lib
creating build\bdist.win-amd64\wheel
creating build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data
creating build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib
creating build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime
creating build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\backend
copying build\lib\onnxruntime\backend\backend.py -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\backend
copying build\lib\onnxruntime\backend\backend_rep.py -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\backend
copying build\lib\onnxruntime\backend\__init__.py -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\backend
creating build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\capi
copying build\lib\onnxruntime\capi\onnxruntime_pybind11_state.pyd -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\capi
copying build\lib\onnxruntime\capi\onnxruntime_validation.py -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\capi
copying build\lib\onnxruntime\capi\session.py -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\capi
copying build\lib\onnxruntime\capi\_ld_preload.py -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\capi
copying build\lib\onnxruntime\capi\_pybind_state.py -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\capi
copying build\lib\onnxruntime\capi\__init__.py -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\capi
creating build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\datasets
copying build\lib\onnxruntime\datasets\logreg_iris.onnx -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\datasets
copying build\lib\onnxruntime\datasets\mul_1.onnx -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\datasets
copying build\lib\onnxruntime\datasets\sigmoid.onnx -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\datasets
copying build\lib\onnxruntime\datasets\__init__.py -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\datasets
copying build\lib\onnxruntime\LICENSE -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime
copying build\lib\onnxruntime\ThirdPartyNotices.txt -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime
creating build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\tools
copying build\lib\onnxruntime\tools\onnxruntime_test.py -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\tools
copying build\lib\onnxruntime\tools\__init__.py -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime\tools
copying build\lib\onnxruntime\__init__.py -> build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime
running install_egg_info
running egg_info
writing top-level names to onnxruntime_gpu_tensorrt.egg-info\top_level.txt
writing dependency_links to onnxruntime_gpu_tensorrt.egg-info\dependency_links.txt
writing requirements to onnxruntime_gpu_tensorrt.egg-info\requires.txt
writing onnxruntime_gpu_tensorrt.egg-info\PKG-INFO
writing entry points to onnxruntime_gpu_tensorrt.egg-info\entry_points.txt
warning: manifest_maker: standard file 'setup.py' not found

reading manifest file 'onnxruntime_gpu_tensorrt.egg-info\SOURCES.txt'
writing manifest file 'onnxruntime_gpu_tensorrt.egg-info\SOURCES.txt'
Copying onnxruntime_gpu_tensorrt.egg-info to build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.data\purelib\onnxruntime_gpu_tensorrt-0.5.0-py3.5.egg-info
running install_scripts
C:\Users\jywu\AppData\Local\Continuum\Anaconda3\lib\site-packages\wheel\pep425tags.py:77: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
C:\Users\jywu\AppData\Local\Continuum\Anaconda3\lib\site-packages\wheel\pep425tags.py:81: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
creating build\bdist.win-amd64\wheel\onnxruntime_gpu_tensorrt-0.5.0.dist-info\WHEEL
2019-10-09 09:00:21,101 Build [INFO] - Build complete

**Comment by jinfagang** [comment]
Oh, yes, that is the question, it seens test failed at only 1 test (rest pass) so it return -1 code and all the rest thing does not actually executed. (the failed case maybe about tensorrt)

How to skip the test  anyway?

**Comment by jywu-msft** [comment]
add --update --build to your build.sh command
i.e. 
./build.sh \
        --cuda_version=10.1 \
        --cuda_home=/usr/local/cuda-10.1 \
        --cudnn_home=/usr/local/cuda-10.1 \
        --use_tensorrt --tensorrt_home=$HOME/TensorRT \
        --build_wheel --update --build

the default option set internally is --update --build --test 
you can disable tests by explicitly setting the options and leaving off --test

**Comment by jywu-msft** [comment]
btw, what is the failed test case?

**Comment by jinfagang** [comment]
```
5: 
5: [----------] Global test environment tear-down
5: [==========] 19 tests from 2 test cases ran. (1890 ms total)
5: [  PASSED  ] 19 tests.
5/5 Test #5: onnxruntime_shared_lib_test ......   Passed    2.56 sec

80% tests passed, 1 tests failed out of 5

Total Test time (real) = 145.22 sec

The following tests FAILED:
	  1 - onnxruntime_test_all (Failed)

```

Above is last output, fail cases seems a lot such as :

```
1: [----------] Global test environment tear-down
1: [==========] 1346 tests from 148 test cases ran. (139059 ms total)
1: [  PASSED  ] 1229 tests.
1: [  FAILED  ] 117 tests, listed below:
1: [  FAILED  ] TensorrtExecutionProviderTest.FunctionTest
1: [  FAILED  ] ActivationContribOpTest.ThresholdedRelu_version_1_to_9
1: [  FAILED  ] ActivationContribOpTest.ScaledTanh
1: [  FAILED  ] ActivationContribOpTest.ParametricSoftplus
1: [  FAILED  ] MathOpTest.Clip_6
1: [  FAILED  ] MathOpTest.Clip_Default
1: [  FAILED  ] MathOpTest.Add_float
1: [  FAILED  ] MathOpTest.Add_Broadcast_Axis
1: [  FAILED  ] MathOpTest.Add_Broadcast_3x2_3x1
1: [  FAILED  ] MathOpTest.Sub
1: [  FAILED  ] MathOpTest.Mul
1: [  FAILED  ] MathOpTest.Div
1: [  FAILED  ] MathOpTest.Abs
1: [  FAILED  ] MathOpTest.Neg
1: [  FAILED  ] MathOpTest.Floor
1: [  FAILED  ] MathOpTest.Ceil
1: [  FAILED  ] MathOpTest.Reciprocal
1: [  FAILED  ] MathOpTest.Sqrt_Float
1: [  FAILED  ] MathOpTest.Pow_Float
1: [  FAILED  ] MathOpTest.Log
1: [  FAILED  ] MathOpTest.Sum_6
1: [  FAILED  ] MathOpTest.Min_6
1: [  FAILED  ] MathOpTest.Min_8
1: [  FAILED  ] MathOpTest.Max_6
1: [  FAILED  ] MathOpTest.Mean_6
1: [  FAILED  ] MathOpTest.SinFloat
1: [  FAILED  ] MathOpTest.Cos
1: [  FAILED  ] MathOpTest.Tan
1: [  FAILED  ] MathOpTest.Asin
1: [  FAILED  ] MathOpTest.Acos
1: [  FAILED  ] MathOpTest.Atan
1: [  FAILED  ] MathOpTest.Sinh
1: [  FAILED  ] MathOpTest.Cosh
1: [  FAILED  ] MathOpTest.Asinh
1: [  FAILED  ] MathOpTest.Acosh
1: [  FAILED  ] MathOpTest.Atanh
1: [  FAILED  ] ImageScalerContribOpTest.ImageScalerTest
1: [  FAILED  ] ActivationOpTest.Sigmoid
1: [  FAILED  ] ActivationOpTest.HardSigmoid
1: [  FAILED  ] ActivationOpTest.Tanh
1: [  FAILED  ] ActivationOpTest.Relu
1: [  FAILED  ] ActivationOpTest.Elu
1: [  FAILED  ] ActivationOpTest.LeakyRelu
1: [  FAILED  ] ActivationOpTest.ThresholdedRelu
1: [  FAILED  ] ActivationOpTest.Selu
1: [  FAILED  ] ActivationOpTest.Selu_Attributes
1: [  FAILED  ] ActivationOpTest.Softplus
1: [  FAILED  ] GemmOpTest.GemmNoBiasOpset11
1: [  FAILED  ] LogSoftmaxOperator.Simple
1: [  FAILED  ] LogSoftmaxOperator.LargeNumber
1: [  FAILED  ] LogSoftmaxOperator.ThreeDimsAxis2
1: [  FAILED  ] LogSoftmaxOperator.ThreeDimsNegativeAxis
1: [  FAILED  ] SoftmaxOperator.Simple
1: [  FAILED  ] SoftmaxOperator.LargeNumber
1: [  FAILED  ] SoftmaxOperator.ThreeDimsAxis2
1: [  FAILED  ] SoftmaxOperator.ThreeDimsNegativeAxis
1: [  FAILED  ] Dropout.Opset7
1: [  FAILED  ] FlattenOpTest.Flatten_default_axis
1: [  FAILED  ] FlattenOpTest.Flatten_neg_axis3
1: [  FAILED  ] LRNTest.LRN_1
1: [  FAILED  ] LRNTest.LRN_2
1: [  FAILED  ] PoolTest.GlobalMaxPool
1: [  FAILED  ] PoolTest.GlobalAveragePool
1: [  FAILED  ] ReductionOpTest.ReduceL1_keepdims
1: [  FAILED  ] ReductionOpTest.ReduceL2_keepdims
1: [  FAILED  ] ReductionOpTest.ReduceLogSum
1: [  FAILED  ] ReductionOpTest.ReduceLogSum_samesize
1: [  FAILED  ] ReductionOpTest.ReduceLogSumExp_keepdims
1: [  FAILED  ] ReductionOpTest.ReduceMax_do_not_keepdims
1: [  FAILED  ] ReductionOpTest.ReduceMax_keepdims
1: [  FAILED  ] ReductionOpTest.ReduceMax
1: [  FAILED  ] ReductionOpTest.ReduceMean_do_not_keepdims
1: [  FAILED  ] ReductionOpTest.ReduceMean_keepdims
1: [  FAILED  ] ReductionOpTest.ReduceMin_do_not_keepdims
1: [  FAILED  ] ReductionOpTest.ReduceMin_keepdims
1: [  FAILED  ] ReductionOpTest.ReduceSum_axes01
1: [  FAILED  ] ReductionOpTest.ReduceSum_axes02
1: [  FAILED  ] ReductionOpTest.ReduceSum_do_not_keepdims
1: [  FAILED  ] ReductionOpTest.ReduceSum_keepdims
1: [  FAILED  ] ReductionOpTest.ReduceSumSquare_do_not_keepdims
1: [  FAILED  ] ReductionOpTest.ReduceSumSquare_keepdims
1: [  FAILED  ] ReductionOpTest.ReduceProd_do_not_keepdims
1: [  FAILED  ] ReductionOpTest.ReduceProd_keepdims
1: [  FAILED  ] SequenceOpsTest.SequenceLengthPositiveFloat
1: [  FAILED  ] SequenceOpsTest.SequenceLengthPositiveInt64
1: [  FAILED  ] SequenceOpsTest.SequenceAtPositiveIdx
1: [  FAILED  ] SequenceOpsTest.SequenceAtNegativeIdx
1: [  FAILED  ] SequenceOpsTest.SequenceAtInvalidPositiveIdx
1: [  FAILED  ] SequenceOpsTest.SequenceAtInvalidNegativeIdx
1: [  FAILED  ] CompressTest.Compress_3dims_neg_axis
1: [  FAILED  ] ConcatOpTest.Concat2D_2
1: [  FAILED  ] ConcatOpTest.Concat3D_2
1: [  FAILED  ] ConcatOpTest.Concat3D_3
1: [  FAILED  ] Identity.FloatType
1: [  FAILED  ] TensorOpTest.Pad_Spec_Example
1: [  FAILED  ] TensorOpTest.Pad_Constant_1D
1: [  FAILED  ] TensorOpTest.Pad_Constant_1D_Zero
1: [  FAILED  ] TensorOpTest.Pad_Constant_2D
1: [  FAILED  ] TensorOpTest.Pad_Constant_2D_negative
1: [  FAILED  ] TensorOpTest.Pad_3D_complex
1: [  FAILED  ] TensorOpTest.Pad_Edge_2D
1: [  FAILED  ] TensorOpTest.Pad_Edge_3D
1: [  FAILED  ] TensorOpTest.Pad_Reflect_2D
1: [  FAILED  ] TensorOpTest.SpaceToDepthTest_1
1: [  FAILED  ] TensorOpTest.SpaceToDepthTest_2
1: [  FAILED  ] TensorOpTest.DepthToSpaceTest_1
1: [  FAILED  ] TensorOpTest.DepthToSpaceTest_2
1: [  FAILED  ] TensorOpTest.DepthToSpaceTest_3
1: [  FAILED  ] TensorOpTest.DepthToSpaceTest_4
1: [  FAILED  ] TensorOpTest.DepthToSpaceTest_5
1: [  FAILED  ] TensorOpTest.UnsqueezeNegAxis_3
1: [  FAILED  ] UpsampleOpTest.UpsampleOpNearestTest
1: [  FAILED  ] UpsampleOpTest.UpsampleOpNearest2XTest
1: [  FAILED  ] UpsampleOpTest.UpsampleOpNearest15XTest
1: [  FAILED  ] UpsampleOpTest.UpsampleOpNearestTest_NoScale
1: [  FAILED  ] SqueezeOpTest.SqueezeNegAxis_2
1: [  FAILED  ] Unique.InvalidAxis
1: 
1: 117 FAILED TESTS
1:   YOU HAVE 1 DISABLED TEST
1: 
1/5 Test #1: onnxruntime_test_all .............***Failed  140.16 sec
test 2
    Start 2: onnx_test_pytorch_converted

```

What are these fail cases?

**Comment by jywu-msft** [comment]
can you provide the full log?
The summary only shows the tests that failed, but the log output during test execution should provide more details on why it failed.

**Comment by jinfagang** [comment]
```
onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:185 void onnxruntime::test::Check(const onnxruntime::test::OpTester::Data&, const onnxruntime::Tensor&, const string&) expected_data.data_.Get<Tensor>().Shape() == output_tensor.Shape() was false. Expected output shape [{3,3,3}] did not match run output shape [{3,3}] for concat_result
1: Stacktrace:
1: " thrown in the test body.
1: [  FAILED  ] ConcatOpTest.Concat3D_2 (84 ms)
1: [ RUN      ] ConcatOpTest.Concat3D_3
1: 2019-10-10 10:37:18.931084727 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2019-10-10 02:37:18 WARNING] TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.2
1: 2019-10-10 10:37:18.978230026 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2019-10-10 02:37:18 WARNING] TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.2
1: 2019-10-10 10:37:18.979928707 [W:onnxruntime:Default, tensorrt_execution_provider.h:28 log] [2019-10-10 02:37:18 WARNING] TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.2
1: /onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:185 void onnxruntime::test::Check(const onnxruntime::test::OpTester::Data&, const onnxruntime::Tensor&, const string&) expected_data.data_.Get<Tensor>().Shape() == output_tensor.Shape() was false. Expected output shape [{2,4,2}] did not match run output shape [{4,2}] for concat_result
1: Stacktrace:
1: unknown file: Failure
1: C++ exception with description "/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:185 void onnxruntime::test::Check(const onnxruntime::test::OpTester::Data&, const onnxruntime::Tensor&, const string&) expected_data.data_.Get<Tensor>().Shape() == output_tensor.Shape() was false. Expected output shape [{2,4,2}] did not match run output shape [{4,2}] for concat_result
1: Stacktrace:
1: " thrown in the test body.
1: [  FAILED  ] ConcatOpTest.Concat3D_3 (82 ms)

```

Does this because of tensorrt?

**Comment by jywu-msft** [comment]
Can you provide the full logs? we would like to see what the other test failures are as well.
It's strange that you are seeing so many test failures. I haven't seen this before.
@stevenlix ,have you seen this before?

**Comment by jinfagang** [comment]
Full log is quite long and too many dir information. It's almost like this, with tensorrt test error. I don't know am I link again tensorrt right or not since I test onnxruntime-gp-tensorrt compares with force CPU, it faster than CPU but not fast as I expected on tensorrt, much more slower than pytorch GPU compares on maskrcnn.onnx model.

**Comment by Ahwar** [comment]
In the present working directory, you can not have a file whose name is the same as the module name.  
In easy words the module you are importing is `onnxruntime` and if there is a file name in your working directory as `onnxruntime.py` then the import will be failed because the compiler is confused about what it should load, file, or a module.  
### What can you do?
either change your working directory where you are executing the code (recommended), or rename `onnxruntime.py` to another name.  
### How did I solve it?
In my case, I created a file with the name of `onnxruntime.py` and in the `onnxruntime.py` I imported `import onnxruntime as nxrun` and it gave the error when I renamed the `onnxruntime.py` to `runonnxmodel.py` it did not give that error.

**Comment by gitskystar** [comment]
> what is your current working directory? I suspect you are starting python from the onnxruntime source directory? if so, change to any other directory and start python again. if your current working directory has a subdirectory named onnxruntime, python will try to import that subdirectory as a module , which obviously won't work.

wonderful answer，solve my question👍
