### ISSUE TITLE
npm install provides error on onnxruntime: 404 URL not found.

### ISSUE THREAD

**Issue by jordyvanraalte** [microsoft/onnxruntime#20727]
### Describe the issue

Hey!

Our deployment with Github Actions is failing several times now due to the following error:

 .../node_modules/onnxruntime-node postinstall: Downloading "https://github.com/microsoft/onnxruntime/releases/download/v1.18.0/onnxruntime-linux-x64-gpu-1.18.0.tgz".

.../node_modules/onnxruntime-node postinstall: /home/runner/work/***/***/node_modules/.pnpm/onnxruntime-node@1.18.0/node_modules/onnxruntime-node/script/install.js:69

.../node_modules/onnxruntime-node postinstall:     throw new Error(`Failed to download the binaries: ${res.status} ${res.statusText}.
.../node_modules/onnxruntime-node postinstall:           ^
.../node_modules/onnxruntime-node postinstall: Error: Failed to download the binaries: 404 Not Found.

*** = left out for confidential reasons.

Version we use: onnxruntime-node: "^1.17.0"

Issue on our project seems to occur the last three days, before that no issues. Only small HTML changes in the commit we try to deploy. 

### To reproduce

I can't seem to reproduce outside of our project. However it seems the download URL is broken (https://github.com/microsoft/onnxruntime/releases/download/v1.18.0/onnxruntime-linux-x64-gpu-1.18.0.tgz). I also cannot find a release regarding v1.18.0.

### Platform

Linux

### OS Version

Ubuntu latest

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.0 / 1.18.0

### ONNX Runtime API

C

### Architecture

X64

### Execution Provider

Default CPU

**Comment by fs-eire** [comment]
it should work now.

The reason is that the release steps publish the onnxruntime-node package first and then upload the binary. When you see that error, the NPM package is published but the binary is not ready yet. Now the binary file is available and you should not see that error message any more.

The release process maybe need to update.

**Comment by jordyvanraalte** [comment]
> it should work now.
> 
> The reason is that the release steps publish the onnxruntime-node package first and then upload the binary. When you see that error, the NPM package is published but the binary is not ready yet. Now the binary file is available and you should not see that error message any more.
> 
> The release process maybe need to update.

Yes seems to work. Thanks!
