### ISSUE TITLE
pip install failure for onnxruntime-gpu==1.9.0

### ISSUE THREAD

**Issue by keshav2211** [microsoft/onnxruntime#20737]
### Describe the issue

We are encountering failure while trying to install onnxruntime-gpu==1.9.0 on python 3.8 on linux platform.
This version was available up until 19-May-2024 2300 hrs UTC.

`ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.9.0 (from versions: 1.10.0, 1.11.0, 1.11.1, 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.17.0, 1.17.1, 1.18.0)`

### To reproduce

switch to python3.8 virtual env
pip install onnxruntime-gpu==1.9.0

pip index versions onnxruntime-gpu

### Platform

Linux

### OS Version

Any

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.9.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by parinitarahi** [comment]
Could you expand on why you need to build an older version of install onnxruntime-gpu==1.9.0 ,  we recommend you use  onnxruntime-gpu==1.10.0 and above with Python 3.8.

**Comment by keshav2211** [comment]
Some of our models are running using this dependency and they can't be started anymore. Working on upgrading the dependency to onnxruntime-gpu==1.10.0.
But 1.9.0 suddenly missing from pypi index caused outage at our end.

**Comment by yuslepukhin** [comment]
PyPi has a limit of 10Gb and some older versions are being removed.

**Comment by keshav2211** [comment]
@yuslepukhin Should we expect v1.10.0(the oldest available version now) to be deprecated after next release ?

**Comment by yuslepukhin** [comment]
AFAIK, there is not a definite schedule. Once PyPi starts complaining we have to free some space.

**Comment by wukongbuku** [comment]
> AFAIK, there is not a definite schedule. Once PyPi starts complaining we have to free some space. It is not a must to remove old releases with every new release.

Excuse me, I want to ask if centos 7does not support 1.18.0 and higher

pip install onnxruntime==1.18.1
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.18.1 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.18.1
