### ISSUE TITLE
[Build] Support CUDA 12 onnxruntime-gpu pypi package

### ISSUE THREAD

**Issue by circuluspibo** [microsoft/onnxruntime#20745]
### Describe the issue

It seems to support cuda 12 at py3.9 but 3.10 and 3.11 seems to be cuda 11.8

### Target platform

ubuntu2204

### Build script

.

### Error / output

.

**Comment by tianleiwu** [comment]
@circuluspibo, could you try install cuda 12 package according to https://onnxruntime.ai/docs/install/

**Comment by aashaypm** [comment]
Jumping in, @tianleiwu I don't see version 1.18 on [here](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/onnxruntime-cuda-12). Anyway, I did follow the method mentioned on the install page, and I get the following error when trying to use the library:
```
2024-05-22 16:59:06.850388755 [E:onnxruntime:Default, provider_bridge_ort.cc:1744 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/cor
e/session/provider_bridge_ort.cc:1426 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to 
load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.11: cannot open shared object file: No such file or directory  
```
Which makes me think the CUDA 11 compatible version was installed even after running `pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/`

**Comment by snnn** [comment]
@yihonglyu , please help publish CUDA 12 python & nuget packages there.

**Comment by circuluspibo** [comment]
@tianleiwu as aashaypm mentioned, only installed 1.18 with cuda 11.8 only....

**Comment by NarutoUA** [comment]
https://github.com/microsoft/onnxruntime/issues/20409

**Comment by dbuades** [comment]
Same issue here. 1.18 package is missing from https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/onnxruntime-cuda-12

**Comment by typon** [comment]
Running into the same issue.

For people Googling a fix:

1. ```
pip install onnxruntime-gpu --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple
```

Will install `onnxruntime-gpu==1.18.0` which has libraries built for CUDA 11!

2. To fix this, please install like this:

```
 pip install --no-cache-dir onnxruntime-gpu==1.17.1 --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple
 ```
 
 This will allow use with CUDA 12

**Comment by snnn** [comment]
Should be "-i" instead of "--extra-index-url". You should not have the "extra" there.
```
python -m pip install  -i https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/ onnxruntime-gpu
```

**Comment by dbuades** [comment]
**Update**

[1.18.0](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/onnxruntime-cuda-12/PyPI/onnxruntime-gpu/overview/1.18.0) is now available. Thank you!

**Comment by yihonglyu** [comment]
> Update
[1.18.0](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/onnxruntime-cuda-12/PyPI/onnxruntime-gpu/overview/1.18.0) is now available. Thank you!

Close the issue as it is solved
