### ISSUE TITLE
[Build] Missing code from builds v1.17+

### ISSUE THREAD

**Issue by gcunhase** [microsoft/onnxruntime#20774]
### Describe the issue

Code that should be in the build is missing (see [code](https://github.com/microsoft/onnxruntime/blob/5f0b62cde54f59bdeac7978c9f9c12d0a4bc56db/onnxruntime/python/onnxruntime_inference_collection.py#L469)):
```python
self._register_ep_custom_ops(session_options, providers, provider_options, available_providers)
```

Related [PR](https://github.com/microsoft/onnxruntime/pull/17617) (already merged) and [issue](https://github.com/microsoft/onnxruntime/issues/16121).

### Urgency

Urgent, blocked trying to run an ONNX model with a TRT plugin.

### Target platform

Ubuntu

### Build script

```sh
pip install onnxruntime-gpu==1.17.0
```

### Error / output

Not able to use claimed feature.

**Comment by chilo-ms** [comment]
That's wired, the code should be in onnxruntime-gpu 1.17.0.
How do you know that the code is not there in your system?

Could you help check the onnxruntime-gpu package version in your system?
```sh
python -c "import onnxruntime; print(onnxruntime.__version__)"
```

**Comment by gcunhase** [comment]
Sorry about the confusion, I've reinstalled the package and it seems to be working now. Closing this issue.
