### ISSUE TITLE
[Build] Failed build on Linux

### ISSUE THREAD

**Issue by andyzhaozhenyu** [microsoft/onnxruntime#20777]
### Describe the issue

Here is the command I used:
`python build.py --build_dir ./build --config Release --update --build --skip_submodule_sync --parallel --use_binskim_compliant_compiler_flags --build_wheel -enable_lto`
And here is the error message I got
`CMake Error at onnxruntime_common.cmake:138 (target_link_libraries):

 Target "onnxruntime_common" links to:
  absl::low_level_hash
 but the target was not found. Possible reasons include:
  \* There is a typo in the target name.
  \* A find_package call is missing for an IMPORTED target.
  \* An ALIAS target is missing.
Call Stack (most recent call first):
 CMakeLists.txt:1759 (include)
`

Also, do you have the manual to show how to build onnxruntime on Linux? May I get the links plz?

### Target platform

Linux

### Build script

python build.py --build_dir ./build --config Release --update --build --skip_submodule_sync --parallel --use_binskim_compliant_compiler_flags --build_wheel -enable_lto

### Error / output

CMake Error at onnxruntime_common.cmake:138 (target_link_libraries):

 Target "onnxruntime_common" links to:
  absl::low_level_hash
 but the target was not found. Possible reasons include:
  \* There is a typo in the target name.
  \* A find_package call is missing for an IMPORTED target.
  \* An ALIAS target is missing.
Call Stack (most recent call first):
 CMakeLists.txt:1759 (include)

### GCC / Compiler Version

gcc 10/12

**Comment by snnn** [comment]
Please check your abseil's version. The one that is installed to /usr/local/include/absl. It should match the one in cmake/deps.txt.

**Comment by lxy-mini** [comment]
I found that during the process of compiling the abseil-cpp file, if the compilation method is wrong, there will be similar errors.
Correct installation method
git clone https://github.com/abseil/abseil-cpp.git
mkdir build && cd build
cmake -DABSL_BUILD_TESTING=ON -DABSL_USE_GOOGLETEST_HEAD=ON -DCMAKE_CXX_STANDARD=14 -DCMAKE_CXX_FLAGS="-fPIC" ..
cmake --build . --target all
sudo make install
