### ISSUE TITLE
[Build] Same questions as #20777

### ISSUE THREAD

**Issue by andyzhaozhenyu** [microsoft/onnxruntime#20799]
### Describe the issue

Here is the command I used:
python build.py --build_dir ./build --config Release --update --build --skip_submodule_sync --parallel --use_binskim_compliant_compiler_flags --build_wheel -enable_lto
And here is the error message I got
`CMake Error at onnxruntime_common.cmake:138 (target_link_libraries):

Target "onnxruntime_common" links to:
absl::low_level_hash
but the target was not found. Possible reasons include:
* There is a typo in the target name.
* A find_package call is missing for an IMPORTED target.
* An ALIAS target is missing.
Call Stack (most recent call first):
CMakeLists.txt:1759 (include)
`

Here is the abseil I used, https://github.com/abseil/abseil-cpp/archive/refs/tags/20240116.

### Target platform

Linux aarch64

### Build script

python build.py --build_dir ./build --config Release --update --build --skip_submodule_sync --parallel --use_binskim_compliant_compiler_flags --build_wheel -enable_lto

### Error / output

CMake Error at onnxruntime_common.cmake:138 (target_link_libraries):

Target "onnxruntime_common" links to:
absl::low_level_hash
but the target was not found. Possible reasons include:
* There is a typo in the target name.
* A find_package call is missing for an IMPORTED target.
* An ALIAS target is missing.
Call Stack (most recent call first):
CMakeLists.txt:1759 (include)

**Comment by andyzhaozhenyu** [comment]
update error info 
In file included from /usr/local/include/absl/container/flat_hash_set.h:39,
                 from /home/zzy/aicompiler/onnxruntime/include/onnxruntime/core/common/inlined_containers.h:21,
                 from /home/zzy/aicompiler/onnxruntime/onnxruntime/core/graph/graph.cc:15:
/usr/local/include/absl/container/internal/raw_hash_set.h: In instantiation of ‘absl::lts_20240116::container_internal::raw_hash_set<Policy, Hash, Eq, Alloc>::const_iterator absl::lts_20240116::container_internal::raw_hash_set<Policy, Hash, Eq, Alloc>::find(absl::lts_20240116::container_internal::raw_hash_set<Policy, Hash, Eq, Alloc>::key_arg<K>&) const [with K = std::basic_string_view<char>; Policy = absl::lts_20240116::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char>, int>; Hash = absl::lts_20240116::container_internal::StringHash; Eq = absl::lts_20240116::container_internal::StringEq; Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, int> >; absl::lts_20240116::container_internal::raw_hash_set<Policy, Hash, Eq, Alloc>::key_arg<K> = std::basic_string_view<char>]’:
/home/zzy/aicompiler/onnxruntime/onnxruntime/core/framework/ort_value_name_idx_map.h:39:29:   required from here
/usr/local/include/absl/container/internal/raw_hash_set.h:2720:32: 错误：对‘(const hasher {aka const absl::lts_20240116::container_internal::StringHash}) (absl::lts_20240116::container_internal::raw_hash_set<absl::lts_20240116::container_internal::FlatHashMapPolicy<std::__cxx11::basic_string<char>, int>, absl::lts_20240116::container_internal::StringHash, absl::lts_20240116::container_internal::StringEq, std::allocator<std::pair<const std::__cxx11::basic_string<char>, int> > >::key_arg<std::basic_string_view<char> >&)’的调用没有匹配

**Comment by snnn** [comment]
Please delete the /usr/local/include/absl folder, or use an absl version that is compatible with onnxruntime code. You can find ORT's ABSL version from cmake/deps.txt.
