### ISSUE TITLE
[Documentation] Dead Links

### ISSUE THREAD

**Issue by tianleiwu** [microsoft/onnxruntime#20790]
### Describe the documentation issue

- ./_site/blogs/accelerating-llama-2.html
  *  External link https://github.com/microsoft/onnxruntime-inference-examples/blob/main/python/models/llama2/LLaMA-2%20E2E%20Notebook.ipynb failed: 404 No error

- ./_site/docs/ecosystem/index.html
  *  External link https://github.com/Azure/MachineLearningNotebooks/blob/master/how-to-use-azureml/deployment/onnx/onnx-modelzoo-aml-deploy-resnet50.ipynb failed: 404 No error

### Page / URL

https://onnxruntime.ai/blogs/accelerating-llama-2.html

**Comment by fs-eire** [comment]
This should have been fixed by #20831
