### ISSUE TITLE
Error in c_cxx samples: unresolved external symbol "struct OrtApi const * const Ort::g_api"

### ISSUE THREAD

**Issue by kai06046** [microsoft/onnxruntime#2081]
I followed [this](https://github.com/microsoft/onnxruntime/blob/master/samples/c_cxx/README.md) to build onnxruntime from source and passed all tests. But when I tried building samples with C++ but got below error. 
Had same error message with official release here https://github.com/microsoft/onnxruntime/releases/download/v0.5.0/onnxruntime-win-x64-0.5.0.zip

> 1>------ Build started: Project: mnist, Configuration: Debug x64 ------
2>------ Build started: Project: fns_candy_style_transfer, Configuration: Debug x64 ------
3>------ Build started: Project: image_classifier, Configuration: Debug x64 ------
2>fns_candy_style_transfer.c
3>main.cc
1>MNIST.obj : error LNK2001: unresolved external symbol "struct OrtApi const * const Ort::g_api" (?g_api@Ort@@3PEBUOrtApi@@EB)
1>C:\onnxruntime\samples\c_cxx\build\MNIST\Debug\mnist.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "mnist.vcxproj" -- FAILED.
2>C:\onnxruntime\samples\c_cxx\fns_candy_style_transfer\fns_candy_style_transfer.c(13): error C2099: initializer is not a constant
2>C:\onnxruntime\samples\c_cxx\fns_candy_style_transfer\fns_candy_style_transfer.c(123): warning C4244: '=': conversion from 'int64_t' to 'png_uint_32', possible loss of data
2>C:\onnxruntime\samples\c_cxx\fns_candy_style_transfer\fns_candy_style_transfer.c(124): warning C4244: '=': conversion from 'int64_t' to 'png_uint_32', possible loss of data
2>C:\onnxruntime\samples\c_cxx\fns_candy_style_transfer\fns_candy_style_transfer.c(191): warning C4013: 'OrtRun' undefined; assuming extern returning int
2>C:\onnxruntime\samples\c_cxx\fns_candy_style_transfer\fns_candy_style_transfer.c(199): warning C4013: 'OrtReleaseValue' undefined; assuming extern returning int
2>C:\onnxruntime\samples\c_cxx\fns_candy_style_transfer\fns_candy_style_transfer.c(190): warning C4047: 'initializing': 'OrtStatus *' differs in levels of indirection from 'int'
2>Done building project "fns_candy_style_transfer.vcxproj" -- FAILED.
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(70): error C3861: 'OrtSessionGetInputCount': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(72): error C3861: 'OrtSessionGetOutputCount': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(97): error C3861: 'OrtReleaseSession': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(106): error C3861: 'OrtReleaseSession': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(112): error C3861: 'OrtCreateSessionOptions': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(116): error C3861: 'OrtCreateSession': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(117): error C3861: 'OrtReleaseSessionOptions': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(131): error C3861: 'OrtGetAllocatorWithDefaultOptions': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(134): error C3861: 'OrtSessionGetInputName': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(136): error C3861: 'OrtAllocatorFree': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(137): error C3861: 'OrtSessionGetOutputName': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(139): error C3861: 'OrtAllocatorFree': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(143): error C3861: 'OrtSessionGetInputTypeInfo': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(145): error C3861: 'OrtCastTypeInfoToTensorInfo': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(147): error C3861: 'OrtGetDimensionsCount': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(150): error C3861: 'OrtGetDimensions': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(164): error C3861: 'OrtRun': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(166): error C3861: 'OrtGetTensorMutableData': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\main.cc(185): error C3861: 'OrtReleaseValue': identifier not found
3>image_loader_wic.cc
3>C:\onnxruntime\samples\c_cxx\imagenet\image_loader_wic.cc(52): error C3861: 'OrtCreateStatus': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\image_loader_wic.cc(99): error C3861: 'OrtCreateStatus': identifier not found
3>C:\onnxruntime\samples\c_cxx\imagenet\image_loader_wic.cc(104): error C3861: 'OrtCreateStatus': identifier not found
3>Generating Code...
3>Done building project "image_classifier.vcxproj" -- FAILED.
========== Build: 0 succeeded, 3 failed, 3 up-to-date, 0 skipped ==========

Here is my cmake log
> -- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.16.27032.1
-- The CXX compiler identification is MSVC 19.16.27032.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/onnxruntime/samples/c_cxx/build

I only modified onnxruntime path in CMakeLists.txt like below:
` include_directories("C:\\onnxruntime\\include" "C:\\onnxruntime\\include\\onnxruntime" "C:\\onnxruntime\\include\\onnxruntime\\core\\session")`
` link_directories("C:\\onnxruntime\\build\\Windows\\Release\\Release")`

Can anyone help solve this?

**Comment by j-bo** [comment]
Had the same issue trying to run this sample : https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp

Looks like APIs were changed without sample update of the contrary.

I solved my issue using the code from [0.5.0 tag](https://github.com/microsoft/onnxruntime/blob/v0.5.0/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp)

Maybe you could try to do the same and use https://github.com/microsoft/onnxruntime/tree/v0.5.0/samples/c_cxx

**Comment by Godricly** [comment]
#1897  check if this helps.

**Comment by kai06046** [comment]
> #1897 check if this helps.
Build succeeded after adding these codes, thanks.
```
const OrtApi* g_ort = OrtGetApi(ORT_API_VERSION);
const OrtApi* Ort::g_api = OrtGetApi(ORT_API_VERSION);
```

**Comment by xxtsxxts** [comment]
Successfully build MNIST after adding these codes into MNIST.cpp, thanks.
const OrtApi* Ort::g_api = OrtGetApiBase()->GetApi(ORT_API_VERSION);
