### ISSUE TITLE
[Feature Request] prebuilt package with cudnn 9 support

### ISSUE THREAD

**Issue by LSC527** [microsoft/onnxruntime#20829]
### Describe the feature request

NVIDIA released tensorrt 10 and cudnn 9, but onnxruntime's prebuilt package only support cudnn 8 by now.

### Describe scenario use case

more convenient for users to install if using cudnn 9

**Comment by jywu-msft** [comment]
we plan to publish 1.18.1 gpu packages built against CUDA 12.x and CuDNN 9.x later this month. 
(in addition to the default gpu packages built against CUDA 11.8 + CuDNN 8.x)

**Comment by jywu-msft** [comment]
Can you help test out these Release Candidate Packages which support CUDA 12.x , TensorRT 10 and CuDNN 9.x?
https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/onnxruntime-cuda-12/NuGet/Microsoft.ML.OnnxRuntime.Gpu.Linux/overview/1.18.1-rc
https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/onnxruntime-cuda-12/NuGet/Microsoft.ML.OnnxRuntime.Gpu.Windows/overview/1.18.1-rc

**Comment by LSC527** [comment]
@jywu-msft Not so sure how to use this package. Is there a pypi whl package？

**Comment by jywu-msft** [comment]
no, those were nuget packages. 
here are whl's
https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/onnxruntime-cuda-12/PyPI/ort-nightly-gpu/overview/1.18.1.dev20240624003

**Comment by LSC527** [comment]
@jywu-msft Thx. 
Everything went great when I test this whl in a docker env [nvcr.io/nvidia/pytorch:24.05-py3](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html) (cuda12.4, tensorrt 10.0.1, cudnn 9.1), using some simple models from torchvision. 
Will report isssues if encountered.

**Comment by jywu-msft** [comment]
> @jywu-msft Thx. Everything went great when I test this whl in a docker env [nvcr.io/nvidia/pytorch:24.05-py3](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html) (cuda12.4, tensorrt 10.0.1, cudnn 9.1), using some simple models from torchvision. Will report isssues if encountered.

Thank you!
