### ISSUE TITLE
[Build] wheels of 1.17/1.18 not found installing with uv

### ISSUE THREAD

**Issue by rbtcollins** [microsoft/onnxruntime#20825]
### Describe the issue

In https://github.com/Microsoft/onnxruntime/releases/tag/v1.17.0 it was mentioned that pytorch doesn't support 3.12, but that is no longer the case - https://pypi.org/project/torch/ has 3.12 support.

### Urgency

Not super urgent, but it is very nice to keep on top of upgrades.

### Target platform

linux amd64 python 3.12

### Build script

NA

### Error / output

NA

**Comment by snnn** [comment]
See: https://pypi.org/project/onnxruntime/#files

Search "312" in the page.

**Comment by rbtcollins** [comment]
Oh interesting, I see 1.18 does have some artifacts, but I still see 

```
No solution found when resolving dependencies:
  ╰─▶ Because onnxruntime==1.18.0 has no wheels are available with a matching Python ABI and only the following versions of onnxruntime
      are available:
          onnxruntime<=1.18.0
          onnxruntime>=2.0.0
      we can conclude that onnxruntime>=1.18.0 cannot be used.
````

I'll look deeper into why that is

**Comment by rbtcollins** [comment]
ok, so its the uv platform.

suceeds:

```
uv pip compile     --generate-hashes     --emit-index-url     --no-strip-extras   --python-platform x86_64-manylinux_2_28     --python-version="3.12"     -o ./requirements.txt requirements.in
```

fails:

```
uv pip compile     --generate-hashes     --emit-index-url     --no-strip-extras   --python-platform x86_64-unknown-linux-gnu     --python-version="3.12"     -o ./requirements.txt requirements.in
```

I think this should be considered a uv bug, and will take it there for now.
