### ISSUE TITLE
Empty MobileNet Inference

### ISSUE THREAD

**Issue by jji2019** [microsoft/onnxruntime#2084]
**Describe the bug**
https://github.com/onnx/keras-onnx/blob/master/README.md describes how to do the inference using resent onnx model. Using the sample scripts, the prediction from onnxruntime is same to what python model predicts. After replacing the Resnet with Mobilenet, the prediction from onnxruntime is empty.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OSX 10.15 (19A583)
- ONNX Runtime installed from (source or binary): pip install onnxruntime (pip 19.2.3 from ./.virtualenvs/dl4cv/lib/python3.7/site-packages/pip (python 3.7))
- ONNX Runtime version: 0.5.0
- Python version: 3.7.4

**To Reproduce**
Please check the linked notebook file 'Resnet vs Mobilenet.ipynb'
https://www.dropbox.com/s/yu8ra42blj4n03w/Resnet%20vs%20Mobilenet.ipynb
and linked image file 'image.png'
https://www.dropbox.com/s/fn62ofxpg6dqu6w/image.png

**Expected behavior**
The prediction from python model should be the same to the prediction from onnxruntime.

**Comment by hariharans29** [comment]
Hi @jji2019,

Can you expand on what you mean by "empty" ? Also, can you directly share the onnx file that you get after you use keras2onnx to convert the MobileNet keras model to onnx ? From the notebook, it seems like we may need some intermediate files to facilitate the conversion to onnx, and it would be easier to take a look at the generated onnx file on your machine directly. (You can zip the file and attach it here.)

**Comment by hariharans29** [comment]
Hello @jji2019,

Any update on this ? Could you please share the requested converted ONNX file ? Thanks!

**Comment by hariharans29** [comment]
Please re-open if this issue is still relevant with the converted ONNX file from keras2onnx. Thanks!
