### ISSUE TITLE
pip install failure for onnxruntime==1.17.3

### ISSUE THREAD

**Issue by MichaelYang1995** [microsoft/onnxruntime#20852]
### Describe the issue

I want to `pip3 install -v onnxruntime==1.17.3`
but it's show 
`Using pip 23.0.1 from /home/shared/apps/tutor-livekit-speech/.venv/lib/python3.10/site-packages/pip (python 3.10)`
`ERROR: Could not find a version that satisfies the requirement onnxruntime==1.17.3 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)`
`ERROR: No matching distribution found for onnxruntime==1.17.3`

### To reproduce

pip3 install -v onnxruntime==1.17.3

### Urgency

If I can't install onnxruntime >= 1.17.0, I can't start my project.

### Platform

Linux

### OS Version

CentOS Linux release 7.6.1810 (Core) 

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.17.3

### ONNX Runtime API

Python

### Architecture

X86

### Execution Provider

Default CPU

**Comment by snnn** [comment]
Sorry we no longer support CentOS 7.
