### ISSUE TITLE
can't install on Python

### ISSUE THREAD

**Issue by prescriptionlifeline** [microsoft/onnxruntime#20866]
### Describe the issue

```
pip3 install onnxruntime
```

### To reproduce

I get this error:

```
pip3 install onnxruntime
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime
```

### Urgency

not urgent

### Platform

Linux

### OS Version

Debian GNU/Linux 9.9 (stretch)

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

not sure

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by snnn** [comment]
Debian 9 is too old. Please use a newer version.
