### ISSUE TITLE
Could onnxruntime add  VSINPU execution provider?

### ISSUE THREAD

**Issue by chenfeiyue-cfy** [microsoft/onnxruntime#20880]
Our company aims to deploy its own backend execution provider（VSINPU exexcution provider） on ONNX Runtime and has achieved initial results. We hope to officially add our deployment code to this repository.

Is it possible for us to do this? If so, what materials do I need to prepare? Looking forward to and thank you for your reply！

**Comment by tianleiwu** [comment]
There are a few community maintained execution providers like tvm, rknpu and cann etc. 

You can look at first commit of those providers in a sub-directory as example to prepare a pull request: https://github.com/microsoft/onnxruntime/tree/217b66fd8540e62154e088b6f214af3ca9f51d7c/onnxruntime/core/providers

Related document: https://onnxruntime.ai/docs/execution-providers/add-execution-provider.html

You can add some documents in gh-pages branch and submit a pull request:
https://github.com/microsoft/onnxruntime/tree/gh-pages/docs/execution-providers

**Comment by chenfeiyue-cfy** [comment]
Thanks for your information!I have made PR for our VSINPU and will close this issue^_^
