### ISSUE TITLE
ReduceMin NOT_IMPLEMENTED 

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#2090]
**Describe the bug**

> RuntimeError: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node __ReduceMin_606:ReduceMin(1)

**Urgency**

Need this is FasterRCNN model conversion

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 0.5.0
- Python version: 3.6

**To Reproduce**
Call `torch.min()`

**Expected behavior**
Support `ReduceMin`

**Additional context**
When I run against master branch I do not see this error, so maybe this is fixed in master, in which case please close this

**Comment by dashesy** [comment]
It seems this is not implemented for `int` types. In which case, the error should tell that.

**Comment by hariharans29** [comment]
Yes, the int types are in master and the next release will have it. We will fix the error message to be more verbose post-release.
