### ISSUE TITLE
How to output the middle layer in ONNXRUNTIME for C++?

### ISSUE THREAD

**Issue by ShiinoMashiro** [microsoft/onnxruntime#20902]
### Describe the issue

I want to output the middle layer ,but cant find any api related .

### To reproduce

no need

### Platform

Linux

### OS Version

ubuntu 20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.18.0

### ONNX Runtime API

C++

### Architecture

X86

### Execution Provider

Default CPU

**Comment by ShiinoMashiro** [comment]
Sorry, my description might have been a bit misleading. What I meant was whether the C++ version of the library can extend outputs like Python ONNXRUNTIME，just like the code below：
![image](https://github.com/microsoft/onnxruntime/assets/64900339/f625c640-b3bf-4352-8c1a-f88961f8c632)

**Comment by Craigacp** [comment]
If you add the name of the middle layer's output to the output list in the ONNX model using the ONNX API (or by directly modifiying the protobuf) then ORT will emit it along with the rest of the outputs. ORT's APIs don't manipulate the ONNX models themselves, you need to use the ONNX library to do that.

**Comment by ShiinoMashiro** [comment]
Ok，i understand now that the output is extended by onnx library, not onnxruntime. Thank you for your answer.
