### ISSUE TITLE
[Build] Fail to build onnxruntime on Nvidia Jetson Xavier with Jetpack 4.6 (rev3)

### ISSUE THREAD

**Issue by akatzi77** [microsoft/onnxruntime#20918]
### Describe the issue

When building Onnxruntime either (v1.11.1, v1.11.0, v1.10) build fails on account of internal ccplus1 error.
Some of the files that fail are convert.cc

### Target platform

Jetson Xavier

### Build script

./build.sh --config Release --update --build --build_shared_lib --parallel --build_wheel --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu --tensorrt_home /usr/lib/aarch64-linux-gnu

### Error / output

Example1:
c++: internal compiler error: Segmentation fault signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
external/onnx/CMakeFiles/onnx.dir/build.make:691: recipe for target 'external/onnx/CMakeFiles/onnx.dir/onnx/version_converter/convert.cc.o' failed

Example2:
c++: internal compiler error: Segmentation fault signal terminated program cc1plus
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
CMakeFiles/onnxruntime_util.dir/build.make:75: recipe for target 'CMakeFiles/onnxruntime_util.dir/home/nvidia/Downloads/onnxruntime/onnxruntime/core/util/math_cpu.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_util.dir/home/nvidia/Downloads/onnxruntime/onnxruntime/core/util/math_cpu.cc.o] Error 4

### GCC / Compiler Version

8.4

**Comment by snnn** [comment]
It is an "internal compiler error". Sorry we cannot help. Please try to upgrade your C++ compiler, or report the bug to https://gcc.gnu.org/bugs/

**Comment by akatzi77** [comment]
Hello @snnn ,

I'm using the same gcc-8.4 compiler on another Xavier device with Jetpack 4.6.3 and can compile libonnxruntime successfully.
But my product is uses Jetpack 4.6.

Gcc 9.x is not supported on CUDA 10.2 used by both Jetpack 4.6 .. 4.6.4, so I can't ugrade to GCC 9.x.

Can you kindly let me know whether libonnxruntime CAPI can be compiled on Jetson Xavier Jetpack 4.6?
Which compiler are you using?

**Comment by snnn** [comment]
Have you checked this: https://elinux.org/Jetson_Zoo#ONNX_Runtime?
