### ISSUE TITLE
[Build] 

### ISSUE THREAD

**Issue by nikolai3d** [microsoft/onnxruntime#20928]
### Describe the issue

I had a case when I had main CUDA installed, and it was a version 11.8. 

I wanted to build against 12.5, so I downloaded and unpacked it into a separate directory and passed it as a `--cuda-home` parameter, however the ONNX builder was still picking the NVCC compiler from 11.8.

### Urgency

Not urgent, workaroundable.

### Target platform

linux

### Build script

 `./build.sh --cudnn_home <CUDNN_PATH> --cuda_home <CUDA_12_5_PATH> --tensorrt_home <TRT_FOLDER>--config Release --build_shared_lib --skip_tests --cmake_extra_defines CMAKE_INSTALL_PREFIX=<TARGET_INSTALL_FOLDER> --compile_no_warning_as_error `

### Error / output

Bunch of failures with .cu files.

**Comment by snnn** [comment]
Add --cuda_version=xxx to your command

**Comment by nikolai3d** [comment]
> You need to manually add nvcc to PATH env.

That works as a workaround, thank you! 🙇

**Comment by nikolai3d** [comment]
Closing as fixed, fixed in https://github.com/microsoft/onnxruntime/pull/20987
