### ISSUE TITLE
How QLinearConv layer absorb the Relu function

### ISSUE THREAD

**Issue by zhongpanwu** [microsoft/onnxruntime#20975]
### Describe the issue

I am implementing my own Onnxruntime code in C. In order to do it, I have built a simple Conv+ReLU based model (quantized in ONNX using QOperation (int8)), and then I have built the equivalent C code. So far, without the Relu, my output is matched to the QLinearConv output. However, when I add the Relu, the output seems too weird.  for example:
This is the output from the ONNX:
![image](https://github.com/microsoft/onnxruntime/assets/20134067/ef35c6eb-c7c2-4d2b-8082-f69cb609cf8b)

and this is the output from my C:
![image](https://github.com/microsoft/onnxruntime/assets/20134067/69086e26-735f-463c-ae5c-8367539fd599)

As you might see here, all the positive values in C's outputs are replaced with -128. I assume this is how the ONNX's Relu works, but Relu should cut off all negative part, but why the ONNX's relu does revers and shifting, I dont fully understand. Please let me know any thoughts and welcome any reply.

### To reproduce

I attached the model and dummy input.

### Platform

Linux

### OS Version

Ubuntu

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.17.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

### Execution Provider Library Version

CUDA12

### Model File

![conv1d_model_quantized onnx](https://github.com/microsoft/onnxruntime/assets/20134067/f1768567-f8cd-4f0d-aac4-7e159e7da7ce)
![dummy_input byte](https://github.com/microsoft/onnxruntime/assets/20134067/b18a635b-2218-479a-a041-b7791e829178)

### Is this a quantized model?

Yes

**Comment by yufenglee** [comment]
The Relu in the ONNX model is removed by quantization tool: https://github.com/microsoft/onnxruntime/blob/981893c318f2deab32ba4aaac0d8ed25dc9398a2/onnxruntime/python/tools/quantization/quantize.py#L189

do you mind to share the onnx model(both quantized and non-quantized)?

**Comment by zhongpanwu** [comment]
> The Relu in the ONNX model is removed by quantization tool:
> 
> https://github.com/microsoft/onnxruntime/blob/981893c318f2deab32ba4aaac0d8ed25dc9398a2/onnxruntime/python/tools/quantization/quantize.py#L189
> 
> do you mind to share the onnx model(both quantized and non-quantized)?
![conv1d_model onnx](https://github.com/microsoft/onnxruntime/assets/20134067/4e06db45-1d29-4545-9106-05791c058bb2)

yes, but where these -128 are from? The answer is still unfindable. the model I provided are quantized, here I attatched the unquantized model. This model is pretty simple and only for test use.

**Comment by zhongpanwu** [comment]
Could you explain how the Relu is handled in QLinearConv? I cannot find anything related to "QuantReLU".

**Comment by zhongpanwu** [comment]
Sorry, the problem is solved, the place where I put ReLU is the key, the Relu is part of requantization.
