### ISSUE TITLE
v1.17.0 + requires macOS deployment target >= than 13.3 due to C++ 20

### ISSUE THREAD

**Issue by ola-ableton** [microsoft/onnxruntime#21033]
### Describe the issue

It seems that moving to C++20 for macOS builds has bumped the minimum macOS that the library can run on. I didn't see this mentioned in the release notes. macOS 13.3 is not that old.

https://stackoverflow.com/questions/76932735/unable-to-use-to-chars-with-clang-on-macos

```
In file included from /onnxruntime/onnxruntime/include/onnxruntime/core/common/common.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/chrono:800:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__chrono/formatter.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__chrono/ostream.h:30:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__format/format_functions.h:29:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/__format/formatter_floating_point.h:73:32: error: 'to_chars' is unavailable: introduced in macOS 13.3
  to_chars_result __r = _VSTD::to_chars(__first, __last, __value, __fmt, __precision);
  ```

### To reproduce

try and compile explicitly setting a lower deployment target with --apple_deploy_target

### Platform

Mac

### OS Version

11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.17.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by ola-ableton** [comment]
https://github.com/microsoft/onnxruntime/commit/0141e27ca1e9954da2630f817709e2eebcd88dde

**Comment by snnn** [comment]
So, you were not using our official packages, you built the binaries from source by yourself and you didn't use the "--apple_deploy_target" flag?

**Comment by ola-ableton** [comment]
I am building a custom build but I did use the -apple_deploy_target.

We need to support macOS 11 or higher but if you specify

-apple_deploy_target=11.0

the build will fail with the above error

It's necessary to set at least 

-apple_deploy_target=13.3

for the C++ 20 code to compile.

This will be a problem for many other users I imagine. Fortunately we can stay on version 1.16.3 which is the last release that didn't require C++ 20 on macOS.

**Comment by snnn** [comment]
As long as you need to deploy the code to a different machine, you always need to set the deploy target's OS version. No matter what ONNX Runtime version you use, or no matter the target OS is Windows or MacOS.  Because there is no other way to get this information.

**Comment by snnn** [comment]
Interesting ..  I thought it works fine with macOS 11. Because in our pipeline we set     MACOSX_DEPLOYMENT_TARGET to '11.0'. 
See: https://github.com/microsoft/onnxruntime/blob/main/tools/ci_build/github/azure-pipelines/templates/mac-cpu-packing-jobs.yml#L34

**Comment by snnn** [comment]
Our binaries were built on macOS 12 with XCode 14.2.
https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md 
If it doesn't support macOS 12, we wouldn't be able to run the tests.

**Comment by snnn** [comment]
Could it because your macOS SDK version is too new?

**Comment by ola-ableton** [comment]
It's possible. I will try and get an older SDK tomorrow and see if compiling against that makes any difference

**Comment by skottmckay** [comment]
Two things are required to make this work.

This condition needs to be tighter about usage of std::chrono for macOS. The SDK version must be > 14.4 as per the current check, but the min version must also be >= 13.3.

https://github.com/microsoft/onnxruntime/blob/904b850b445ccfb3dc935e39b96cfb3dbfb52673/include/onnxruntime/core/common/logging/logging.h#L61-L68

Something like this might work for a macOS build. Not sure if additional conditions are required for iOS/mac-catalyst. 

```c++
// Xcode added support for C++20's std::chrono::operator<< in SDK version 14.4, but the target macOS version must be
// >= 13.3 for it to be used.
#if __cplusplus >= 202002L && \
  (!TARGET_OS_MAC || \
   (__MAC_OS_X_VERSION_MAX_ALLOWED >= 140400L && __MAC_OS_X_VERSION_MIN_ALLOWED >= 130300L))
namespace timestamp_ns = std::chrono;
#else
namespace timestamp_ns = ::date;
#endif
```

Additionally there needs to be disambiguation of `date::operator<<` and `std::chrono::operator<<` [here](https://github.com/microsoft/onnxruntime/blob/904b850b445ccfb3dc935e39b96cfb3dbfb52673/onnxruntime/core/platform/apple/logging/apple_log_sink.mm#L18) and [here](https://github.com/microsoft/onnxruntime/blob/904b850b445ccfb3dc935e39b96cfb3dbfb52673/onnxruntime/core/common/logging/sinks/ostream_sink.cc#L48) for a macOS build when C++20 is enabled but we're not using std::chrono. 

That can be done by explicitly outputting the timestamp as a first step like this:

```c++
  timestamp_ns::operator<<(msg, timestamp);
  msg << " [" << message.SeverityPrefix() << ":" << message.Category() << ":" << logger_id << ", "
      << message.Location().ToString() << "] " << message.Message();
```

**Comment by skottmckay** [comment]
It got a little bit more complicated to handle mac-catalyst as well, but hopefully #22138 fixes this completely.
