### ISSUE TITLE
[Web] [Webnn] Can't seem to use the WebNN. Getting "WEBNN execution provider is not supported in this build."

### ISSUE THREAD

**Issue by RafayAK** [microsoft/onnxruntime#21119]
### Describe the issue

Hi, when providing `webnn` as one of the executors I get this error:

```
error: Can't append execution provider: WEBNN. ERROR_CODE: 2, ERROR_MESSAGE: WEBNN execution provider is not supported in this build. 
    at t.checkLastError (ort.min.js:9:306896)
    at eval (ort.min.js:9:296280)
    at t.setSessionOptions (ort.min.js:9:296325)
    at t.createSessionFinalize (ort.min.js:9:299274)
    at t.createSessionFinalize (ort.min.js:9:290097)
    at t.OnnxruntimeWebAssemblySessionHandler.loadModel (ort.min.js:9:292999)
    at async Object.createSessionHandler (ort.min.js:9:1034)
    at async i.create (ort.min.js:9:538248)
```

There is very little documentation around `webnn` use in the Onnxweb-runtime documentation (https://onnxruntime.ai/docs/tutorials/web/env-flags-and-session-options.html#executionproviders).
I really appreciate the help :+1: 

### To reproduce

```
import { InferenceSession, Tensor, env } from "onnxruntime-web";
const options = {
    executionProviders: ["webnn"], // Use WebNN for inference
};

const session = await InferenceSession.create(MODEL_URL, options);
```

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.16.1

### Execution Provider

Other / Unknown

**Comment by RafayAK** [comment]
I updated the onnx-web runtime package to the latest `onnxruntime-web@1.18.0` still can't get it to work (code is same as above)

```
 Failed to load model: Error: no available backend found. ERR: [webnn] backend not found.
    at Dn (ort.min.js:20:1787)
    at async a.create (ort.min.js:20:18248)
```

**Comment by guschmue** [comment]
ort.min does not include webgpu or webnn EP. 
Use
import { InferenceSession, Tensor, env } from 'onnxruntime-web/webgpu';
