### ISSUE TITLE
[Announcement] Onnxruntime available on Nixpkgs

### ISSUE THREAD

**Issue by jonringer** [microsoft/onnxruntime#2111]
I packaged a basic/vanilla cpu version of the onnxruntime for nixpkgs, thought the onnxruntime team would like to know :).

If I have a reason to use the more advanced features at work (E.g cuda, mkl-dnn, etc) then I'll update it; but for now, it's a start :).

Original PR: https://github.com/NixOS/nixpkgs/pull/67542

```
$ nix-build -A onnxruntime.all
these paths will be fetched (0.06 MiB download, 0.29 MiB unpacked):
  /nix/store/6l3dkanqa6cfidsh2fdr8z7z47wqnlrb-onnxruntime-0.5.0-dev
copying path '/nix/store/6l3dkanqa6cfidsh2fdr8z7z47wqnlrb-onnxruntime-0.5.0-dev' from 'https://cache.nixos.org'...
/nix/store/s1dxih4cfngd6xdlvjj75zfziwvyx5ik-onnxruntime-0.5.0
/nix/store/6l3dkanqa6cfidsh2fdr8z7z47wqnlrb-onnxruntime-0.5.0-dev
```
runtime closure:
```
$ tree ./result
./result
└── lib
    ├── libonnxruntime.so -> libonnxruntime.so.0.5.0
    └── libonnxruntime.so.0.5.0
```
dev closure:
```
$ tree -L 4 ./result-dev # limit all the files listed (59 total)
./result-dev
├── include
│   └── onnxruntime
│       └── core
│           ├── common
│           ├── framework
│           ├── graph
│           ├── optimizer
│           ├── providers
│           └── session
├── lib
│   └── cmake
│       └── protobuf
│           ├── protobuf-config.cmake
│           ├── protobuf-config-version.cmake
│           ├── protobuf-module.cmake
│           ├── protobuf-options.cmake
│           └── protobuf-targets.cmake
└── nix-support
    └── propagated-build-inputs
```

**Comment by faxu** [comment]
Thanks for sharing! Do you plan on keeping this up to date with each release? 

We may want to capture this info somewhere on the readme for people to discover as well (outside of github issue :))

**Comment by jonringer** [comment]
I do, and as long as you the build options and toolchain don't change too much, it shouldn't be too difficult to update.

**Comment by jonringer** [comment]
already a PR bump to 1.0.0: https://github.com/NixOS/nixpkgs/pull/72315

**Comment by snnn** [comment]
Thank you for helping us!
