### ISSUE TITLE
[Performance] Call a error when running on windows 7.detail:System.TypeInitializationException at Microsoft.ML.OnnxRuntime.SessionOptions..ctor() 

### ISSUE THREAD

**Issue by Zhx-Chenailuoding** [microsoft/onnxruntime#21116]
### Describe the issue

I run an application on my own computer is ok,because my operation is window11,but i run it on an operation is windows7,it call an error :"System.TypeInitializationException at Microsoft.ML.OnnxRuntime.SessionOptions..ctor()". Why make it?Because windows 7 's kernelBase.dll lose something?what should i do?

### To reproduce

var session = new InferenceSession(modelPath);

            Bitmap bitmap = ResizeAndCenterImageByBitmap(bitmapss, 640, 640);
            var inputTensor = FastToOnnxTensor_13hw(bitmap);
            // 进行预测
            var container = new List<NamedOnnxValue>();
            container.Add(NamedOnnxValue.CreateFromTensor("images", inputTensor));
            IDisposableReadOnlyCollection<DisposableNamedOnnxValue> unresolve = session.Run(container);
            // 解析预测结果
            var resultsArray = unresolve.ToArray();
            Tensor<float> tensors = resultsArray[0].AsTensor<float>();var session = new InferenceSession(modelPath);

            Bitmap bitmap = ResizeAndCenterImageByBitmap(bitmapss, 640, 640);
            var inputTensor = FastToOnnxTensor_13hw(bitmap);
                        var container = new List<NamedOnnxValue>();
            container.Add(NamedOnnxValue.CreateFromTensor("images", inputTensor));
            IDisposableReadOnlyCollection<DisposableNamedOnnxValue> unresolve = session.Run(container);
            var resultsArray = unresolve.ToArray();
            Tensor<float> tensors = resultsArray[0].AsTensor<float>();

### Platform

Windows

### OS Version

7

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.15.0

### ONNX Runtime API

C#

### Architecture

X86

### Execution Provider

Default CPU

### Is this a quantized model?

Yes

**Comment by snnn** [comment]
We no longer support Windows 7 and 8.

**Comment by Zhx-Chenailuoding** [comment]
so,i should make win7 to win10?

**Comment by snnn** [comment]
Yes
