### ISSUE TITLE
How to convert quantized ONNX model from Tensor-Oriented format to Operator-Oriented format?

### ISSUE THREAD

**Issue by hoangtv2000** [microsoft/onnxruntime#21137]
### Describe the issue

I have the quantized model represented as the graph below and I want to convert all of QDQ operators in this model to QOperator operators, what should I do?
![image](https://github.com/microsoft/onnxruntime/assets/58163069/b443934e-dd32-4238-b413-660e187b6e38)

### To reproduce

have not repoduced yet.

### Platform

Linux

### OS Version

Ubuntu 22.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.15.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

```[tasklist]
### Tasks
```

**Comment by UsingtcNower** [comment]
I have the same question.

**Comment by yufenglee** [comment]
@UsingtcNower and @hoangtv2000, you can run the onnxruntime offline-mode to optimize the model to Operator oriented: https://onnxruntime.ai/docs/performance/model-optimizations/graph-optimizations.html#offline-mode. BTW, why do you want to do this?

**Comment by hoangtv2000** [comment]
> @UsingtcNower and @hoangtv2000, you can run the onnxruntime offline-mode to optimize the model to Operator oriented: https://onnxruntime.ai/docs/performance/model-optimizations/graph-optimizations.html#offline-mode. BTW, why do you want to do this?

I want to use your method to run on our self-designed chip which runs efficiently by integer arithmetic-only format.

**Comment by hoangtv2000** [comment]
> I have the same question. Hi @hoangtv2000 do you find the solution?

You should use built-in static post-training quantization function of onnxruntime library [quantize_static](https://github.com/microsoft/onnxruntime/blob/d79e3c5791cf1b9481c8d2d64917dc5270658446/onnxruntime/python/tools/quantization/quantize.py#L292), remember to set quant_format to `QuantFormat.QOperator` if you want your ouput model has only QOperator, set `per_channel` to `False` if you want per-tensor quantization and `activation_type` & `weight_type` to `QuantType.QUInt8` if you want your weight and activation tensors in uint8 format.

**Comment by ashwingopinath** [comment]
Hi @hoangtv2000 Did you find a succesful way to convert QDQ operators to the QOperator format in ONNX? I understand that we can use the quantize_static function in the onnxruntime library when you are doing post-training quantization on a float model. But I want to export a pre quantized model from Pytorch (Which exports the ONNX model only in the QDQ format) and express it in the QOperator format.
