### ISSUE TITLE
[Build] build python wheel fails

### ISSUE THREAD

**Issue by DaniAffCH** [microsoft/onnxruntime#21145]
### Describe the issue

Building the wheel from source fails on Ubuntu 22, but it builds successfully when using the tagged release v1.18.0.

### Target platform

linux-x86_64

### Build script

`./build.sh --config Debug --enable_pybind --build_wheel --build_shared_lib`

### Error / output

```
error: no matching function for call to ‘pybind11::dtype::dtype(NPY_TYPES)’
  173 |   py::array result(py::dtype(NPY_OBJECT), tensor.Shape().GetDims());

[...]
: error: no matching function for call to ‘pybind11::dtype::dtype(const int&)’
  197 |   pybind11::array result(py::dtype(numpy_type), tensor.Shape().GetDims(),
[...]
/home/daniaffch/Desktop/gsoc/onnxruntime/onnxruntime/python/onnxruntime_pybind_state.cc:197:36: error: invalid conversion from ‘int’ to ‘const char*’ [-fpermissive]
  197 |   pybind11::array result(py::dtype(numpy_type), tensor.Shape().GetDims(),

```

### GCC / Compiler Version

11.4.0

**Comment by tianleiwu** [comment]
@DaniAffCH, It seems to be related to numpy version. Could you try different numpy version (1.26 vs 2.0) with main branch as well?

**Comment by DaniAffCH** [comment]
@tianleiwu thank you for the support. I tried both versions of numpy but the same issue persists.

**Comment by LeehanLee** [comment]
> [@tianleiwu](https://github.com/tianleiwu) thank you for the support. I tried both versions of numpy but the same issue persists.

@DaniAffCH Hello, I was wondering if you solved this issue?  I met the same issue,
