### ISSUE TITLE
[Training] Cannot export model for inferencing from session created from buffers

### ISSUE THREAD

**Issue by riccardopinosio** [microsoft/onnxruntime#21152]
### Describe the issue

Currently, if you create a training session with the C api using `CreateTrainingSessionFromBuffer()` there is no way to export the final model using `ExportModelForInferencing()`, because the latter complains that no eval path has been provided.

It should be possible I believe to allow for the export of the final model even if the session has been created from buffers.

### To reproduce

Just initialize any training session with any model from buffers and try to export the model.

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

v2.18.0

### PyTorch Version

2.3.1

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
We will get a fix into the next release.

**Comment by carzh** [comment]
Was not able to squeeze into the next release -- will have to do a build from latest source to be able to export for inference from buffer. [This page](https://onnxruntime.ai/docs/build/training.html) should have instructions on building from source. 

The change should also be available in the nightly packages soon.
