### ISSUE TITLE
QDQ removal optimization from around MaxPool changes results with negative scale

### ISSUE THREAD

**Issue by mcollinswisc** [microsoft/onnxruntime#21176]
### Describe the issue

The optimization in
https://github.com/microsoft/onnxruntime/blob/4743803944d6f6333bf93b89a62d8083d4466710/onnxruntime/core/optimizer/qdq_transformer/selectors_actions/qdq_selector_action_transformer.cc#L57
will remove the QuantizeLinear/DequantizeLinear ops from DequantizeLinear ∘ MaxPool ∘ QuantizeLinear. This produces the same result with/without the quantization iff the quantization scale is non-negative. With a negative quantization scale (admittedly a strange/uncommon case), though, the result of this subgraph will change.

### To reproduce

Run the script in
https://gist.github.com/mcollinswisc/e0017b837fb744296658e6463f53f74b
with different `onnxruntime.GraphOptimizationLevel` choices.

### Platform

Linux

### OS Version

Ubuntu Mantic

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.18.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by yihonglyu** [comment]
@mcollinswisc Given https://github.com/microsoft/onnxruntime/pull/21182 is merged, please close the issue if it is solved.
