### ISSUE TITLE
[Build] "utf8_range::utf8_validity" does not exist

### ISSUE THREAD

**Issue by srijanie03** [microsoft/onnxruntime#21174]
### Describe the issue

I am trying to build the ONNX Runtime Training for CUDA 12.4 following the instructions here:
https://onnxruntime.ai/docs/build/training.html#gpu--cuda

The error occurs at the end of the build with the Cmake unable to find the utf8_range::utf8_validity file. 

I checked the utf8_range folder and it only contains :
utf8_range-config.cmake  
utf8_range-targets-release.cmake  
utf8_range-targets.cmake

Cmake version : 3.29.2

### Urgency

Very urgent

### Target platform

CUDA 12.4

### Build script

./build.sh --config=RelWithDebInfo --enable_training --build_wheel --use_cuda --cuda_home /usr/local/cuda  --cudnn_home /usr/local/cuda --cuda_version=12.4 --allow_running_as_root 

### Error / output

![image](https://github.com/microsoft/onnxruntime/assets/34174706/2b969295-5a80-4b33-84ef-c4ddb2b3acfb)

### GCC / Compiler Version

11.4.0

**Comment by snnn** [comment]
Run 
```
rm -rf /usr/lib/cmake/utf8-range
```
Then try it again.

**Comment by snnn** [comment]
The system environment was broken. It was not an onnxruntime issue.

**Comment by srijanie03** [comment]
It still yields the same issue.

**Comment by snnn** [comment]
Then try this command instead:
```
rm -rf /usr/lib/cmake/utf8_range
```

**Comment by srijanie03** [comment]
The build completed till 96% and then popped up new errors.

![image](https://github.com/microsoft/onnxruntime/assets/34174706/b5b44b90-1129-49e7-9eb0-cb7bf1b42c95)


![image](https://github.com/microsoft/onnxruntime/assets/34174706/50dc38d1-b31c-4744-8f87-f8496c3314cb)


![image](https://github.com/microsoft/onnxruntime/assets/34174706/f5b3c680-4c58-43d7-ac05-ae213878023f)
