### ISSUE TITLE
[Mobile] Cocoapods release archive zips are missing 

### ISSUE THREAD

**Issue by gazadge** [microsoft/onnxruntime#21181]
### Describe the issue

When installing **onnxruntime-objc** either via Cocoapods or Swift Package manager the referred release archives are not found - I'm getting a 404 error.

None of the following urls are working:
https://download.onnxruntime.ai/pod-archive-onnxruntime-objc-1.18.0.zip
https://download.onnxruntime.ai/pod-archive-onnxruntime-extensions-c-0.11.0.zip
https://onnxruntimepackages.z14.web.core.windows.net/pod-archive-onnxruntime-objc-1.16.0.zip

### To reproduce

Try to download:
https://download.onnxruntime.ai/pod-archive-onnxruntime-objc-1.18.0.zip
https://download.onnxruntime.ai/pod-archive-onnxruntime-extensions-c-0.11.0.zip

### Urgency

This is blocking building iOS/MacOS apps depending on **onnxruntime-objc**.

### Platform

iOS

### OS Version

All

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

onnxruntime-objc/onnxruntime-c

### ONNX Runtime Version or Commit ID

1.18.0

### ONNX Runtime API

Objective-C/Swift

### Architecture

ARM64

### Execution Provider

CoreML

**Comment by caglar09** [comment]
Please help me. I cannot install the onnxruntime-c package for ios project installation with pod install because it returns 404 on the server. 

I get the following error
```
[!] Error installing onnxruntime-c
[!] /usr/bin/curl -f -L -o /var/folders/hl/9z317kz51qb0yg2b93bz3d680000gn/T/d20240626-85563-bemf90/file.zip https://download.onnxruntime.ai/pod-archive-onnxruntime-c-1.18.0.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.15.2 cocoapods-downloader/2.1'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   321    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
```

**Comment by frymanofer** [comment]
Does not work here as well!!!
Stopped working for me as well seems like https://download.onnxruntime.ai/ is completely down and all other links do not work.
Pod install fails on all onnx types

**Comment by gazadge** [comment]
Okay, this seems to be resolved now - https://download.onnxruntime.ai is up and running again 👍
