### ISSUE TITLE
python API to get intermediate layer output

### ISSUE THREAD

**Issue by vera121** [microsoft/onnxruntime#2119]
I found it inconvenient that onnxruntime can't display the intermediate results during model inference. 
I checked the similar issue #1455, but found it couldn't solve the question for model such as [yolov3](https://onnxzoo.blob.core.windows.net/models/opset_10/yolov3/yolov3.onnx) from ONNX model zoo.

I tried the code mentioned at https://github.com/microsoft/onnxruntime/issues/1455#issuecomment-514805365 and also this:
```
model = onnx.load(model_path)
for w in model.graph.value_info:
    model.graph.output.extend([w])
print(model.graph.output)
```
But the results show still the original 3 outputs. The intermediate layers can't be added and displayed.

Can you add some APIs to show these results? 
It is not easy to analyze some large models only with the last outputs.

**System information**
- ONNX Runtime version: 0.5.0

**Comment by hariharans29** [comment]
You need to know the `name` of the intermediate tensor from the model and you need to put the exact name here `intermediate_tensor_name` and re-load the saved model in OnnxRuntime. Unless the required intermediate output is part of the graph outputs, currently OnnxRuntime, does not support fetching the results. 

model = onnx.load(model_path)
intermediate_layer_value_info = helper.ValueInfoProto()
intermediate_layer_value_info.name = intermediate_tensor_name
model.graph.output.append(intermediate_layer_value_info)
onnx.save(model, model_path)

**Comment by vera121** [comment]
Thanks @hariharans29 . I found it work when I change the code to:
```
model = onnx.load(model_path)
intermediate_tensor_name = "convolution_output74"
intermediate_layer_value_info = helper.ValueInfoProto()
intermediate_layer_value_info.name = intermediate_tensor_name
model.graph.output.extend([intermediate_layer_value_info])
onnx.save(model, model_path)
```
And then reload the modified model.

**Comment by ranc** [comment]
The solution does not work anymore, there is a type check for the dtype of the output tensor...
ORT should have a proper API to fetch it

**Comment by yaoyuannnn** [comment]
Is there a way to get intermediate output tensors of a subgraph (e.g., the body graph of a `Loop` operator)?

**Comment by zhonhel** [comment]
I found a solution at here, can any one try this ?  [link](http://onnx.ai/sklearn-onnx/auto_examples/plot_intermediate_outputs.html#compute-intermediate-outputs)

**Comment by zhijun** [comment]
For those who are still looking for a working solution, please refer to http://onnx.ai/sklearn-onnx/auto_examples/plot_intermediate_outputs.html#compute-intermediate-outputs

**Comment by Tily777** [comment]
> I found a solution at here, can any one try this ? [link](http://onnx.ai/sklearn-onnx/auto_examples/plot_intermediate_outputs.html#compute-intermediate-outputs)

page not found anymore

**Comment by JapinderSandhu** [comment]
> For those who are still looking for a working solution, please refer to http://onnx.ai/sklearn-onnx/auto_examples/plot_intermediate_outputs.html#compute-intermediate-outputs

does this work for pytorch

**Comment by RReverser** [comment]
> ```
> model = onnx.load(model_path)
> for w in model.graph.value_info:
>     model.graph.output.extend([w])
> print(model.graph.output)
> ```
> 
> 
>     
>   
> 
> But the results show still the original 3 outputs. The intermediate layers can't be added and displayed.

I found this variation to work for my purposes:

```py
# Infer missing shapes
model = onnx.shape_inference.infer_shapes(
    model, check_type=True, strict_mode=True, data_prop=True
)

# Dedupe value info
# (looks like inference adds duplicate entries for value as output of the previous node & input of the next one).
outputs = {
    v.SerializeToString(deterministic=True): v for v in model.graph.value_info
}

# Add all the value into to the outputs
model.graph.output.extend(outputs.values())
```

![](https://github.com/user-attachments/assets/3247d555-53b3-43b6-97ff-268e1bf6a75c)
