### ISSUE TITLE
[TensorRT EP] OOM (RAM) when loading ONNX model

### ISSUE THREAD

**Issue by MiroPsota** [microsoft/onnxruntime#21219]
### Describe the issue

OOM (RAM) when loading the model - 50GiB is not enough.

### To reproduce

The model is RTMDet from [here](https://github.com/open-mmlab/mmdetection/tree/main/configs/rtmdet).
ONNX exported model has TensorRT specific NonMaximumSuppression node from [here](https://github.com/NVIDIA/TensorRT/tree/master/plugin/batchedNMSPlugin) (probably slightly changed).

mmdetection model without the specific NMS op for TensorRT can be run without problems in CPU EP, CUDA EP and OpenVINO EP (OV tested with 1.17.0 Pypi package).

CUDA from https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda_11.8.0_520.61.05_linux.run
CUDNN from
https://developer.nvidia.com/downloads/compute/cudnn/secure/8.9.2/local_installers/11.x/cudnn-linux-x86_64-8.9.2.26_cuda11-archive.tar.xz/
TensorRT from
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/10.0.1/tars/TensorRT-10.0.1.6.Linux.x86_64-gnu.cuda-11.8.tar.gz

Code and model are included in the [zip](https://drive.google.com/file/d/1OwT_ar7gbgAaCCIOKY59zNvHXiP4p4UD/view?usp=drive_link) file, with compiled custom op (Ubuntu 24.04, GCC 11.4). Tested with Python 3.10. 
Runnable from `run.py` with `LD_LIBRARY_PATH` set to correct paths (can use `ld_library.py` script as a help).

If needed, I could try to make a docker image that reproduces the bug.

### Platform

Linux

### OS Version

Ubuntu 24.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.18.1

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

TensorRT

### Execution Provider Library Version

CUDA 11.8.0, CUDNN 8.9.2.26, TensorRT 10.0.1.6

**Comment by yf711** [comment]
Hi @MiroPsota Thanks for bringing up this issue!
Does the model with NMS op could run on previous version of ORT+TRT ?
Also could you share the standard model (without nms) that you tested on CPU/GPU/OpenVINO?

**Comment by MiroPsota** [comment]
I think the problem is with TensorRT 10.0, probably the same as mentioned [here](https://github.com/microsoft/onnxruntime/issues/17434#issuecomment-2153189152).

I solved it with compiling ORT 1.18.1 with TRT 8.6.1 and `--use_tensorrt_oss_parser`. More info [here](https://github.com/microsoft/onnxruntime/issues/17434#issuecomment-2212470819).

**Comment by chilo-ms** [comment]
@MiroPsota
 
What your tests with following combinations are expected:

- ORT 1.18.1 + TRT 10.0 (use built-in parser by default) ---> OOM
- ORT 1.17.1 + TRT 8.6 (use built-in parser by default) ---> TRTBatchedNMS can't be recognized by TRT
- ORT 1.18.1 + TRT 8.6 + TRT OSS parser ---> **Can successfully run the inference**

For TRT 10.0, i tested with trtexec and got following error, but i didn't see the error with TRT 8.6 trtexec:
(It seems TRT 10 has some issues and i'm reporting this to Nvidia. )
````
...
[07/09/2024-17:06:31] [I] [TRT] ----------------------------------------------------------------
[07/09/2024-17:06:31] [I] [TRT] No checker registered for op: TRTBatchedNMS. Attempting to check as plugin.
[07/09/2024-17:06:31] [I] [TRT] No importer registered for op: TRTBatchedNMS. Attempting to import as plugin.
[07/09/2024-17:06:31] [I] [TRT] Searching for plugin: TRTBatchedNMS, plugin_version: 1, plugin_namespace:
[07/09/2024-17:06:31] [I] [TRT] Successfully created plugin: TRTBatchedNMS
[07/09/2024-17:06:31] [W] [TRT] IElementWiseLayer with inputs /TRTBatchedNMS_output_2 and /Mul_output_0: first input has type Int32 but second input has type Int64.
[07/09/2024-17:06:31] [E] Error[4]: ITensor::getDimensions: Error Code 4: Internal Error (/Add_2: IElementWiseLayer with SUM operation has incompatible input types Int32 and Int64 type.)
[07/09/2024-17:06:31] [E] [TRT] ModelImporter.cpp:949: While parsing node number 434 [Add -> "/Add_2_output_0"]:
[07/09/2024-17:06:31] [E] [TRT] ModelImporter.cpp:950: --- Begin node ---
input: "/TRTBatchedNMS_output_2"
input: "/Mul_output_0"
output: "/Add_2_output_0"
name: "/Add_2"
op_type: "Add"

[07/09/2024-17:06:31] [E] [TRT] ModelImporter.cpp:951: --- End node ---
[07/09/2024-17:06:31] [E] [TRT] ModelImporter.cpp:954: ERROR: ModelImporter.cpp:195 In function parseNode:
[6] Invalid Node - /Add_2
ITensor::getDimensions: Error Code 4: Internal Error (/Add_2: IElementWiseLayer with SUM operation has incompatible input types Int32 and Int64 type.)
...
````
As for TRT 8.6, user can only use ORT TRT with TRT OSS parser to successfully register and run the customed TRT plugins (in this case, the TRTBatchedNMS op). But for TRT 10, ORT + both built-in parser and OSS parser can successfully register the customed TRT plugins.

**Comment by chilo-ms** [comment]
> it adds not wanted copy operations to a host and back. See the [log](https://github.com/user-attachments/files/16064998/log.txt). I will investigate further.

The copy ops being added is expected. It's because, TRTBatchedNMS op is not recognized by TRT and ORT will try to put TRTBatchedNMS op on other EPs which will result in the copy ops being added. But still, no other EPs can run TRTBatchedNMS ops, so it end up with the error you saw

**Comment by chilo-ms** [comment]
The OOM you saw with TRT 10 is because TRT EP is calling TRT parser to check the TRT eligible nodes in the model where onnxruntime::TensorrtExecutionProvider::GetSupportedList() is being called recursively and hit OOM.
I'm also checking with Nvidia regarding this.

**Comment by chilo-ms** [comment]
@MiroPsota 

Nvidia helped identify the issue.
TRT 10.0 added support for INT64 types, whereas TensorRT 8.6 treated all INT64-typed tensors as INT32. The TRTBatchedNMS plugin internally always produces INT32 output tensors, even though in the ONNX graph they’re marked as INT64:
![image](https://github.com/user-attachments/assets/cb47de41-6134-46b4-90b5-b8d4cc6cc26a)
This causes the build issues in standalone TensorRT 10, as the subsequent operations (i.e. the Add) assumes INT64-typed operands when in reality there is a INT32 + INT64 mix. This issue doesn’t exist in TensorRT 8.6 as everything is casted to INT32, and the types match.

Update the TRTBatchedNMS  plugin ( inlibmmdeploy_op.so) to produce proper INT64 output tensors should fix the issue.

**Comment by MiroPsota** [comment]
It can run with ORT 1.18.1, TRT 10.2 (both with and without `--use_tensorrt_oss_parser`), and edited custom op with INT64 outputs.

**Comment by arpit15** [comment]
@chilo-ms what was the change required in `libmmdeploy_op.so` ? It would be helpful if you can kindly give reference to your branch or change in code required for correctly building with TensorR 10.
