### ISSUE TITLE
How to use IOBinding with torch_directml and onnxruntime in Python API?

### ISSUE THREAD

**Issue by deiteris** [microsoft/onnxruntime#21239]
### Describe the issue

I would like to avoid data transfer between CPU and GPU when using DirectML backend with PyTorch and onnxruntime. 
The Python API documentation mentions a way that I was able to utilize with CUDA successfully: https://onnxruntime.ai/docs/api/python/api_summary.html#data-on-device

However, the same method does not work with DirectML due to https://github.com/microsoft/DirectML/issues/425. `torch_directml` does not implement `data_ptr()` method to access the tensor data pointer, so it's impossible to pass it to IOBinding. Is there a way around this or am I stuck with intermediate transfer?

### To reproduce

Here's a simple code example that creates an upscaler model using DmlExecutionProvider and runs session with IOBinding using a torch tensor:
```py
import torch
import torch_directml
from onnxruntime import InferenceSession
from onnx import TensorProto
from onnx.helper import (
    make_model, make_node, make_graph,
    make_tensor_value_info
)
import numpy as np

dev = torch_directml.device(0)

def make_upscaler() -> InferenceSession:
    # Inputs
    input = make_tensor_value_info('in', TensorProto.FLOAT, [1, 768, None])
    scales = make_tensor_value_info('scales', TensorProto.FLOAT, [None])
    # Outputs
    output = make_tensor_value_info('out', TensorProto.FLOAT, [1, 768, None])

    resize_node = make_node(
        "Resize",
        inputs=["in", "", "scales"],
        outputs=["out"],
        mode="nearest",
        axes=[2]
    )

    graph = make_graph([resize_node], 'upscaler', [input, scales], [output])

    onnx_model = make_model(graph)

    return InferenceSession(onnx_model.SerializeToString(), providers=["DmlExecutionProvider"], provider_options=[{'device_id': 0}])

t = torch.zeros((1, 768, 256), device=dev, dtype=torch.float32)

session = make_upscaler()
iobinding = session.io_binding()
iobinding.bind_input('in', buffer_ptr=t.data_ptr(), shape=tuple(t.shape), device_id=0, element_type=np.float32)
# iobinding.bind_cpu_input('in', t.detach().cpu().numpy())
iobinding.bind_cpu_input('scales', np.array([2], dtype=np.float32))
iobinding.bind_output('out')

session.run_with_iobinding(iobinding)
print(iobinding.get_outputs()[0].numpy())
```

This would result in the following error:
```
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    iobinding.bind_input('in', buffer_ptr=t.data_ptr(), shape=tuple(t.shape), device_id=0, element_type=np.float32)
                                          ^^^^^^^^^^^^
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
```

### Platform

Windows

### OS Version

Windows 10 22H2

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.18.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

DirectML

### Execution Provider Library Version

1.18.0

**Comment by zhangxiang1993** [comment]
onnxruntime DML tensor and pytorch DML tensor are not transferable across platform. And as explained in the other issue, pytorch DML tensor cannot be access by index as explained in https://github.com/microsoft/DirectML/issues/425.

This issue will be marked as closed.
