### ISSUE TITLE
[Mobile] Pixel 7a (Google edge tpu) NNAPI runtime exception unordered_map::at: key not found when setting USE_FP16

### ISSUE THREAD

**Issue by kapsyst** [microsoft/onnxruntime#21230]
### Describe the issue

I'm running a face landmark model via NNAPI. The model will be used in a real time camera application, so performance is critical, and would like run it on the devices dedicated NPU, where available.
On my Pixel 7a, when I run with the following session options:
```
val nnapiFlags = EnumSet.of(NNAPIFlags.CPU_DISABLED, NNAPIFlags.USE_FP16)
sessionOptions.addNnapi(nnapiFlags)
```
I run into the following error:
```
FATAL EXCEPTION: main
Process: ai.onnxruntime.example.imageclassifier, PID: 21726
ai.onnxruntime.OrtException: Error code - ORT_RUNTIME_EXCEPTION - message: Exception during initialization: unordered_map::at: key not found
	at ai.onnxruntime.OrtSession.createSession(Native Method)
	at ai.onnxruntime.OrtSession.<init>(OrtSession.java:91)
```
If I don't set any NNAPI flags, the model runs fine, although rather slowly.
Other information relating to this issue:
- Using ONNX version 1.18.0
- Opsets 12 and 15 gave the above error
- Opset 10 worked, and was very fast, but gave odd output (signed 16 bit ints _as_ floats, and generally incorrect results, compared with running on the CPU)
- All opsets work fine running on the CPU without NNAPI flags
- Unfortunately I can't share the model, but I'll see if I can provide an untrained version
- I have seen [this issue](https://github.com/microsoft/onnxruntime/issues/11488), but it is still occurring using 1.18.0
- The entire verbose log output is here: [nnapi_use_fp16_issue.log](https://github.com/user-attachments/files/16063993/nnapi_use_fp16_issue.log)
- Output of `onnxruntime.tools.check_onnx_model_mobile_usability` on opset 15 model:
```
INFO:  Checking model_opset15.onnx for usability with ORT Mobile.
INFO:  Checking NNAPI
INFO:  Model should perform well with NNAPI as is: YES
INFO:  Checking CoreML
INFO:  Model should perform well with CoreML as is: YES
INFO:  ---------------
INFO:  Checking if pre-built ORT Mobile package can be used with model_opset15.onnx once model is converted from ONNX to ORT format using onnxruntime.tools.convert_onnx_models_to_ort...
INFO:  Model should work with the pre-built package.
```
- Confirmed that `mobilenetv2_fp32.onnx` created with the [Android image classification sample](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/image_classification/android) works fine with `USE_FP16` (and does indeed use the Google edge tpu on the Pixel 7a).

Any help with this issue is much appreciated.

### To reproduce

- Clone and run the [Android image classification sample application](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/image_classification/android)
- Import model into project and replace the model name in the `readModel` function
- Enable ONNX verbose debug logging (`OrtLoggingLevel.ORT_LOGGING_LEVEL_VERBOSE`)
- Set NNAPI session options `CPU_DISABLED` and `USE_FP16`
- Run on a Google Pixel 7a

### Urgency

Not critical, but it is urgent in that running inference on the CPU has a significant impact on  performance. 

### Platform

Android

### OS Version

14

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

onnxruntime-android

### ONNX Runtime Version or Commit ID

1.18.0

### ONNX Runtime API

Java/Kotlin

### Architecture

ARM64

### Execution Provider

NNAPI

**Comment by edgchen1** [comment]
Thanks for providing the details and the output.

> Unfortunately I can't share the model, but I'll see if I can provide an untrained version

Any model that can be used to reproduce the issue would be helpful.

**Comment by kapsyst** [comment]
Thanks @edgchen1 I've confirmed with our team that unfortunately we can't share the untrained model either, so I'll see if I can find a public model that gives an equivalent error.

In the mean time, is there any way we can discern the cause of the error from the logs? I couldn't see anything that really stood out, but I'm wondering if the following message is related:
```
 [V:onnxruntime:ort-java, op_builder_helpers.cc:235 IsSupportedBatchMatMul] Unsupported op type: Gemm
```

**Comment by edgchen1** [comment]
> In the mean time, is there any way we can discern the cause of the error from the logs? I couldn't see anything that really stood out, but I'm wondering if the following message is related:
> 
> ```
>  [V:onnxruntime:ort-java, op_builder_helpers.cc:235 IsSupportedBatchMatMul] Unsupported op type: Gemm
> ```

Possibly. I don't see anything obvious from the logs.

```
 [V:onnxruntime:ort-java, model_builder.cc:442 AddOperations] Adding node [5]
 [E:onnxruntime:, inference_session.cc:2044 operator()] Exception during initialization: unordered_map::at: key not found
```

This indicates that it attempts to add the node with index 5 prior to hitting that exception. Unfortunately, the unordered_map::at error message is generic and there are multiple places where that might come from.

If you're up for building from source, you could try modifying this to also log the node name (`node->Name()`):
https://github.com/microsoft/onnxruntime/blob/f39ee14b46f7977e43c6cae3b8e8c56b968a7d98/onnxruntime/core/providers/nnapi/nnapi_builtin/builders/model_builder.cc#L442-L443

If you can narrow down the node it's failing at it might be easier to come up with a reproducible example model.

**Comment by kapsyst** [comment]
Thanks once again @edgchen1, I'll attempt to build from source and see if I can figure out which node it's failing at.

FYI I've still yet to find a model that gives an equivalent error. I'll keep looking.

**Comment by kapsyst** [comment]
@edgchen1 our team was able to come up with an untrained model that reproduces the issue [here](https://github.com/kapsyst/onnx_nnapi_init_issue/blob/main/landmark_only_dirty.onnx) (I had to add it to a public repository as a Git LFS file as it was too big to upload to this thread directly).

Let me know if this is sufficient or if there's anything else you require.

**Comment by edgchen1** [comment]
Thanks for providing the model. FYI, I can also reproduce the `unordered_map::at: key not found` exception with just the NNAPI EP added to the session options (no flag values set) and on an emulator.

We'll look into it.

**Comment by kapsyst** [comment]
@edgchen1 Thanks very much!

**Comment by edgchen1** [comment]
The issue is that the NNAPI EP wasn't correctly handling initializers that are shared between nodes. In particular, one node (Clip, in this case) reports that it doesn't require an initializer to be added to the NNAPI model but another node (Div) uses that same initializer as its input. The incorrect behavior was that the initializer would not be added, which eventually caused the `unordered_map::at` call to fail.

The original model doesn't share initializers between these two nodes, but after graph optimizations the distinct initializers with the same values got coalesced.

#21286 should fix this particular issue.

**Comment by kapsyst** [comment]
Thank you very much for the quick response @edgchen1! Will give it a try sometime today.

**Comment by edgchen1** [comment]
You can try the aar generated by the nightly packaging pipeline build.
https://aiinfra.visualstudio.com/Lotus/_build/results?buildId=506530&view=artifacts&pathAsName=false&type=publishedArtifacts
onnxruntime-android-full-aar/onnxruntime-android-1.19.0.aar

**Comment by kapsyst** [comment]
FYI, I'm encountering a build error here (seems unrelated to fix): https://github.com/microsoft/onnxruntime/issues/21494
