### ISSUE TITLE
Does ONNXRuntime support creating a tensor with shape [1, 4, 0] ?

### ISSUE THREAD

**Issue by starlitsky2010** [microsoft/onnxruntime#21248]
### Describe the issue

As I'm developing an audio model with a dynamic input size:
First inference time, it needs to create the cache tensor with shape [1, 4, 0]. After that, it needs to create it with shape [1, 4, 128].
Does ONNXRuntime support this condition?
I've search the following API documents without any result.
https://onnxruntime.ai/docs/api/c/struct_ort_1_1_value.html

```
        Ort::Value onnx_input = Ort::Value::CreateTensor(
            memory_info,
            in->data(),
            buf_len * grapSize(in->type()),
            l_shape.data(),   // --> l_shape is a shape vactor with value [1, 4, 0]
            l_shape.size(), grapTypeD2O(in->type()));
```

Comparing between C++ inference result  and python inference result, the cosine similarity of output tensors are zero.
So is there any special requirements about the shape input value in the API Ort::Value::CreateTensor ?

### To reproduce

A brief query. I may change may model to static shape to avoid this problem. But I wonder if ONNXRuntime supports this condition.

### Platform

Linux

### OS Version

Ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

v1.16.3

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by tianleiwu** [comment]
Yes. It is common that kv cache is empty for LLM, and ORT can handle nicely.

@starlitsky2010, You can have a try and report back if there is issue.

**Comment by starlitsky2010** [comment]
> ommon that kv cache is empty at the

Yes, you are right. It could handle a tensor with shape [1, 4, 0] nicely.
Some other mistake I made caused my cosine similarity problem.

Thank you for your quick response!
