### ISSUE TITLE
[Documentation] Do intra_op_num_threads and inter_op_num_threads not correspond to thread_pool_size?

### ISSUE THREAD

**Issue by hotstone1993** [microsoft/onnxruntime#21252]
### Describe the documentation issue

In thread_utils.h, the default value is 0, and if it is 0, all physical cores are used.
<img width="609" alt="image" src="https://github.com/microsoft/onnxruntime/assets/171539484/b4f6eec9-1be2-4041-a4dd-28900baf05cf">

The document below explains that if intra_op_num_threads=0, it only runs on the main thread. Are they different?
https://onnxruntime.ai/docs/performance/tune-performance/threading.html#set-number-of-intra-op-threads

**Comment by xadupre** [comment]
The documentation is not very clear. By default, onnxruntime uses all the cores (0 value).

**Comment by hotstone1993** [comment]
Thank you for answer!
I think the document needs to be updated.
