### ISSUE TITLE
Opset 11 support?

### ISSUE THREAD

**Issue by conjam** [microsoft/onnxruntime#2125]
**Describe the bug**
The Equal ONNX op does not support tensors of type float32. This appears to be against spec according to https://github.com/onnx/onnx/blob/master/docs/Operators.md. 

When trying to run an `onnxruntime.InferenceSession()` the following error is raised: 

`RuntimeError: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from eq_sanity.onnx failed:This is an invalid model. Type Error: Type 'tensor(float)' of input parameter (1) of operator (Equal) in node () is invalid.`

**Urgency**
This issue will block forward progress for me if not resolved by 18/10/2019

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.14 (Mojave)
- ONNX Runtime installed from (source or binary): binary, from conda-forge

- ONNX Runtime version: 0.5.0
- Python version: 3.7.4
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
run: 

`import onnxruntime`
`sess = onnxruntime.InferenceSession( 'eq_sanity.onnx')`

with the provided model: 
[eq_sanity.zip](https://github.com/microsoft/onnxruntime/files/3726537/eq_sanity.zip)

**Expected behavior**
No runtime error is thrown.

**Additional context**
The model that causes this issue was created via the pytorch exporter, with pytorch version 1.2 (binary from conda-forge).  I can provide the script to generate this model if it would be helpful. 

Also can confirm that this model fails in the same way on Ubuntu 18.04, with onnxruntime built from source.

**Comment by conjam** [comment]
After going through closed PRs, it became clear that the functionality I'm looking for was introduced in opset11; could a contributor give any insight towards about when opset 11 will be supported? I'll close this in 24 hours.

Cheers.

**Comment by hariharans29** [comment]
Hi @conjam,

You are right - float type was supported in the Equal op only from Opset-11. You can build OnnxRuntime from source and leverage the functionality. (You need to upgrade your model first to opset-11). The official release should be available soon.

Thanks!
