### ISSUE TITLE
[Performance] How does onnxruntime run in parallel mode?

### ISSUE THREAD

**Issue by zwyao** [microsoft/onnxruntime#21258]
### Describe the issue

In ONNX Runtime v1.18.1, it can set option with ExecutionMode::ORT_PARALLEL, it means ops will run in parallel mode, but i cant find any executors about multi-thread, **it only have one sequential executor**, am i wrong? How done onnxruntime run in parallel mode?

thanks a lot.

### To reproduce

1. no step

### Platform

Windows

### OS Version

1.18.1

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

master released 

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Other / Unknown

### Is this a quantized model?

Yes
```[tasklist]
### Tasks
```

**Comment by RaviTejaUOH** [comment]
I have the same question. Where is the source code for the parallel executor located? I can only find the source for the sequential_executor.
