### ISSUE TITLE
C++ library SONAME without full version number

### ISSUE THREAD

**Issue by anandvsr** [microsoft/onnxruntime#21281]
### Describe the issue

In onnxruntime native so file, the SONAME is with version name.
![image](https://github.com/microsoft/onnxruntime/assets/66105422/74650b96-e1ff-47be-858b-617a18bd37f3)
why don't we maintain library version as like 
```
libonnxruntime.so        # is called the linker-name used for linking.
libonnxruntime.so.1      # is called the soname used by the operating system loader.
libonnxruntime.so.1.18.1    # is called the real-name which is updated by the library maintainer.
```
Refer: [baeldung.com/linux/shared-object-filenames](https://www.baeldung.com/linux/shared-object-filenames)

It required a scenario where I build a library/executable, which is used to compile with certain version, say v1.17.3. It become the user of the library/executable also must stay with v1.17.3 I they update the library to 1.18.1 it couldn't find the library libonnxruntime.so.1.17.3.

### To reproduce

Download a native library tarball [v1.17.3](https://github.com/microsoft/onnxruntime/releases/download/v1.17.3/onnxruntime-linux-x64-1.17.3.tgz).

Create a simple cpp file with create a empty session.
```cpp
// sample.cc
#include <onnxruntime_cxx_api.h>
#include <iostream>

int main(){
  Ort::Session session(nullptr);
  std::cout << "Session created successfully!\n";
  return 0;
}
```
compile it using g++
```bash
g++ -o sample sample.cc \
    -Ionnxruntime-linux-x64-1.17.3/include \
    -Lonnxruntime-linux-x64-1.17.3/lib \
    -lonnxruntime
```
Use LD_LIBRARY_PATH to add the library in search path
```
LD_LIBRARY_PATH=onnxruntime-linux-x64-1.17.3/lib ./sample
```
Got output
```
Session created successfully!
```

If I run it with v1.18.1 in LD_LIBRARY_PATH, it doesn't work.
Download a tarball [v1.18.1](https://github.com/microsoft/onnxruntime/releases/download/v1.18.1/onnxruntime-linux-x64-1.18.1.tgz)

```
LD_LIBRARY_PATH=onnxruntime-linux-x64-1.18.1/lib ./sample
```
Got error like
```
./sample: error while loading shared libraries: libonnxruntime.so.1.17.3: cannot open shared object file: No such file or directory
```

### Platform

Linux

### OS Version

Ubuntu 

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

all version (tried v1.17.3, 1.15.1 and 1.18.1)

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by snnn** [comment]
```
$ readelf -d libonnxruntime.so | grep SONAME
 0x000000000000000e (SONAME)             Library soname: [libonnxruntime.so.1.19.0]
```

I will change it.
