### ISSUE TITLE
Help needed to export in ONNX

### ISSUE THREAD

**Issue by ladanisavan** [microsoft/onnxruntime#21282]
### Describe the issue

Hi there,

I'm seeking guidance on exporting a custom fine-tuned Phi-3 Vision model to ONNX. I've followed the ONNX build model guide from [this link](https://onnxruntime.ai/docs/genai/howto/build-model.html).

The build command I used was:
`python3 -m onnxruntime_genai.models.builder -i ep_2_grad_32_lr_3e-5/ -o onnx_output/ -p int4 -e cuda --extra_options int4_block_size=32 int4_accuracy_level=4`

The build process was successful and generated the following files:

- genai_config.json
- model.onnx
- model.onnx.data
- special_tokens_map.json
- tokenizer.json
- tokenizer_config.json

However, the number of files generated doesn't match the file count in the official HF repo for ONNX `microsoft/Phi-3-vision-128k-instruct-onnx-cuda`

Files highlighted in red below are missing:
<img width="1196" alt="Screenshot 2024-07-05 at 5 56 00 PM" src="https://github.com/microsoft/Phi-3CookBook/assets/14819841/dba377ac-ed7c-4036-b268-c4df8a08a4db">

Additionally, while loading the model using ONNX Runtime, the following error occurs:
`OrtException: Load model from onnx_output failed: Protobuf parsing failed.`

I have also noticed that sections for "embedding" and "vision" are missing from the `genai_config.json`

Can someone help me identify if I'm missing anything? Thanks

### To reproduce

follow the steps provided above

### Platform

Linux

### OS Version

Ubuntu 24.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

0.3.0

### ONNX Runtime API

Python

### Architecture

X86

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 12.1

**Comment by yuslepukhin** [comment]
You should probably file this issue with GenAI library.

**Comment by kunal-vaishnavi** [comment]
We can close this issue since it is already filed in ONNX Runtime GenAI [here](https://github.com/microsoft/onnxruntime-genai/issues/685).
