### ISSUE TITLE
[Mobile] Pre-built 1.18.1 lib is missing for onnxruntime-android

### ISSUE THREAD

**Issue by csukuangfj** [microsoft/onnxruntime#21305]
### Describe the issue

Please see
https://mvnrepository.com/artifact/com.microsoft.onnxruntime/onnxruntime-android

![Screenshot 2024-07-10 at 15 56 08](https://github.com/microsoft/onnxruntime/assets/5284924/2e53327b-031d-46ca-a306-5caf63e65f82)

### To reproduce

Please visit
https://mvnrepository.com/artifact/com.microsoft.onnxruntime/onnxruntime-android

and you will find 1.18.1 is not there.

### Urgency

It is very urgent.

### Platform

Android

### OS Version

any

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

1.18.1

### ONNX Runtime API

C++/C

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by snnn** [comment]
In the last patch release, we didn't publish all packages. The patch was specific for some users.
