### ISSUE TITLE
mklml python wheel - No module named 'onnxruntime.capi'

### ISSUE THREAD

**Issue by lei-Qiao** [microsoft/onnxruntime#2133]
When I build ort 0.4.0 wheel for mklml with python3.6, it can be built successfully, but when I import, it shows error. 

onnxruntime-0.4.0-cp36-cp36m-linux_x86_64.whl
Python 3.6.9 (default, Jul 13 2019, 14:51:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/onnxruntime/onnxruntime/__init__.py", line 18, in <module>
    from onnxruntime.capi import onnxruntime_validation
ModuleNotFoundError: No module named 'onnxruntime.capi'

**Comment by jywu-msft** [comment]
I assume you installed the built wheel?
Looks like you are running python from the source directory so it's trying to import onnxruntime module frim onnxruntime subdirectory rather than the installed package location.
Please change to a different directory and try again.

**Comment by faxu** [comment]
@lei-Qiao - do you still need assistance on this?

**Comment by lei-Qiao** [comment]
Thanks for your help. This issue can be closed.

**Comment by wwbnjsace** [comment]
> When I build ort 0.4.0 wheel for mklml with python3.6, it can be built successfully, but when I import, it shows error.
> 
> onnxruntime-0.4.0-cp36-cp36m-linux_x86_64.whl
> Python 3.6.9 (default, Jul 13 2019, 14:51:44)
> [GCC 8.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import onnxruntime
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/onnxruntime/onnxruntime/**init**.py", line 18, in 
> > > > from onnxruntime.capi import onnxruntime_validation
> > > > ModuleNotFoundError: No module named 'onnxruntime.capi'

how to generate your mklml .whl file ?
