### ISSUE TITLE
An error occurred when I installed onnxruntime-qnn in an Arm environment

### ISSUE THREAD

**Issue by goxia** [microsoft/onnxruntime#21356]
### Describe the issue

python -m pip install onnxruntime-qnn      
ERROR: Could not find a version that satisfies the requirement onnxruntime-qnn (from versions: none)
ERROR: No matching distribution found for onnxruntime-qnn

python -m pip install --pre onnxruntime-qnn
ERROR: Could not find a version that satisfies the requirement onnxruntime-qnn (from versions: none)
ERROR: No matching distribution found for onnxruntime-qnn

### To reproduce

1. Install python 3.12.4 (Arm)
2. Install Visual Studio 2022 (c++ workload and related components
3. Install VSCode
4. Create .venv
5. pip install numpy
6. pip install onnxruntime-qnn or use the --pre parameter

### Platform

Windows

### OS Version

Windows 11 26100.1150

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

current

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

Other / Unknown

### Execution Provider Library Version

pip install onnxruntime-qnn

**Comment by Misaka17032** [comment]
Make sure you did use python version of 3.11.x. (According to the [doc here](https://onnxruntime.ai/docs/execution-providers/QNN-ExecutionProvider.html#:~:text=quantized%20model\)-,Python%203.11.x,-Numpy%201.25.2%20or))

**Comment by goxia** [comment]
Okey, my current version is 3.12.x and I'm going to try 3.11.x.

**Comment by goxia** [comment]
> Make sure you did use python version of 3.11.x. (According to the [doc here](https://onnxruntime.ai/docs/execution-providers/QNN-ExecutionProvider.html#:~:text=quantized%20model)-,Python%203.11.x,-Numpy%201.25.2%20or))

Thank you! It was resolved.
