### ISSUE TITLE
[Build] Cross compilation of the library for ARMv7 32bit target with gcc 8.3 

### ISSUE THREAD

**Issue by saad-koukous** [microsoft/onnxruntime#21353]
### Describe the issue

can't cross compile the library to use it on my target which is a beagleBone Black rev3 armv7 gcc 8.3 and the host machine is Ubuntu 22.04.4 LTS , toolchain used to cross compile : gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf

### Target platform

beagleBone Black rev3 armv7 gcc 8.3

### Build script

cmake $(Build.SourcesDirectory)/cmake -DCMAKE_TOOLCHAIN_FILE=$(Build.SourcesDirectory)/cmake/linux_arm32_crosscompile_toolchain.cmake -DBUILD_SHARED_LIBS=ON

### Error / output

[ 27%] Linking C shared library libcpuinfo.so
/home/saad/toolchains/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.3.0/../../../../arm-linux-gnueabihf/bin/ld: CMakeFiles/cpuinfo.dir/src/init.c.o: in function `cpuinfo_initialize':
init.c:(.text.cpuinfo_initialize+0x38): undefined reference to `cpuinfo_arm_linux_init'
/home/saad/toolchains/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.3.0/../../../../arm-linux-gnueabihf/bin/ld: libcpuinfo.so: hidden symbol `cpuinfo_arm_linux_init' isn't defined
/home/saad/toolchains/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.3.0/../../../../arm-linux-gnueabihf/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [_deps/pytorch_cpuinfo-build/CMakeFiles/cpuinfo.dir/build.make:145: _deps/pytorch_cpuinfo-build/libcpuinfo.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:6328: _deps/pytorch_cpuinfo-build/CMakeFiles/cpuinfo.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by snnn** [comment]
By default, the "onnxruntime_ENABLE_CPUINFO" cmake option is ON.  You may turn it OFF. 

Usage of "BUILD_SHARED_LIBS" is not supported.

**Comment by snnn** [comment]
"BUILD_SHARED_LIBS" is not flexible enough. It either build all libs to static libraries , or build them all to shared libraries. The former one is support. The other one is not.

**Comment by saad-koukous** [comment]
I succesfully build the library  but when i execute my c code in the target i had this error
Error in cpuinfo: failed to parse file /sys/devices/system/cpu/kernel_max: "-1" is not an unsigned number

**Comment by snnn** [comment]
@saad-koukous , would you please submit an issue to https://github.com/pytorch/cpuinfo with more detailed information about what hardware and operating system was used when you hit the error?  The problem needs be fixed there.

Meanwhile, you can build ONNX Runtime without cpuinfo by setting onnxruntime_ENABLE_CPUINFO to OFF.
