### ISSUE TITLE
Latest Release Java Artifacts Unavailable

### ISSUE THREAD

**Issue by contrebande-labs** [microsoft/onnxruntime#21350]
### Describe the issue

The java maven artifacts are stuck at 1.18.0 and the 1.18.1 do not show up anywhere and it's been more than 2 weeks.

### To reproduce

Go here: https://mvnrepository.com/artifact/com.microsoft.onnxruntime/onnxruntime

And here: https://mvnrepository.com/artifact/com.microsoft.onnxruntime/onnxruntime_gpu

Look for 1.18.1 artifacts.

### Urgency

Building a CUDA 12.x Docker image on 1.18.0 is a mess because of the dependency against cudnn8. I'm hoping 1.18.1 can fix that.

### Platform

Linux

### OS Version

Ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.18.1

### ONNX Runtime API

Java

### Architecture

X64

### Execution Provider

Default CPU, CUDA

### Execution Provider Library Version

CUDA 12.4.1

**Comment by snnn** [comment]
Sorry it not was included in the last release which was a partial release that only published some packages. We will do another release(1.19.0) soon and your concern will be addresses there.
