### ISSUE TITLE
[Build] long paths in NuGet package breaking build on Windows

### ISSUE THREAD

**Issue by thoemmi** [microsoft/onnxruntime#21369]
### Describe the issue

The files in the _runtimes_ folder of the NuGet package result in quite long path, e.g. _runtimes/ios/native/onxxrumtime.xcframework/ios-arm64_x86_64-simulator/onnxrumtime.framework/Headers/onnxruntime_session_options_config_keys.h_ has 142 characters.
This can be problematic if the project referencing that package is at a (still reasonable) subdirectory.

This issue was originally reported in https://github.com/dotnet-smartcomponents/smartcomponents/issues/16

### Target platform

Windows

### Build script

n/a

### Error / output

> C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5034,5): error MSB3027: Could not copy "C:\Users\Thomas\.nuget\packages\microsoft.ml.onnxruntime\1.18.0\runtimes\ios\native\onnxruntime.xcframework\ios-arm64_x86_64-simulator\onnxruntime.framework\Headers\onnxruntime_session_options_config_keys.h" to "bin\Debug\net8.0\runtimes\ios\native\onnxruntime.xcframework\ios-arm64_x86_64-simulator\onnxruntime.framework\Headers\onnxruntime_session_options_config_keys.h". Exceeded retry count of 10. Failed.

### Visual Studio Version

Visual Studio 2022 Preview (17.11.0 Preview 3.0)

**Comment by skottmckay** [comment]
That is the required directory structure for a Nuget native package (the `runtimes/<platform>/native` prefix) with an Apple xcframework (the `onnxruntime.xcframework\ios-arm64_x86_64-simulator\onnxruntime.framework\Headers` part) so I'm not sure what we can change. 

Do you have long paths enabled? 

https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell

**Comment by thoemmi** [comment]
Enabling long paths by settings the registry key as documented in https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#registry-setting-to-enable-long-paths did the trick, I can now compile successfully.

Thanks for the hint!
