### ISSUE TITLE
Missing onnxruntime_perf_test.exe in Release Assets (or what actually is "Build Drop"?)

### ISSUE THREAD

**Issue by antoninononooono** [microsoft/onnxruntime#21378]
### Describe the issue

I have been looking to download the onnxruntime_perf_test.exe from the releases on the GitHub repository, but I was unable to find it in any of the release assets. I am particularly interested in using this tool to conduct performance testing with the DirectML execution provider on my Windows system.

Could you please clarify if the onnxruntime_perf_test.exe is included in any of the current releases? If not, could you advise on where I can find this executable or how I can compile it from the source if necessary?

### To reproduce

See this page: https://onnxruntime.ai/docs/performance/tune-performance/profiling-tools.html

It mentions:

In-code performance profiling
The onnxruntime_perf_test.exe tool (available from the build drop) can be used to test various knobs. Please find the usage instructions using onnxruntime_perf_test.exe -h. The [perf_view tool](https://github.com/microsoft/onnxruntime/tree/main/tools/perf_view) can also be used to render the statistics as a summarized view in the browser.

### Urgency

Yes, it's urgent.

### Platform

Windows

### OS Version

Windows 10 Pro

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.18.1

### ONNX Runtime API

C++

### Architecture

X86

### Execution Provider

DirectML

**Comment by snnn** [comment]
Sorry, it is not.  Please build it from source.

**Comment by snnn** [comment]
You may also consider the tools in [MLPerf]( https://github.com/mlcommons/inference/tree/master/vision/classification_and_detection), which I think is more neutral and professional.
