### ISSUE TITLE
Error Instantiating EmbeddingModel with ONNX Model intfloat/multilingual-e5-large

### ISSUE THREAD

**Issue by zelhaddioui** [microsoft/onnxruntime#21388]
### Describe the issue

I am encountering an error while trying to instantiate the EmbeddingModel using the ONNX model intfloat/multilingual-e5-large. The error message is as follows:

Failed to instantiate [org.springframework.ai.embedding.EmbeddingModel]: Factory method 'embeddingClient' threw exception with message: data did not match any variant of untagged enum PreTokenizerWrapper at line 69 column 3

I am unsure why this error is occurring. Below are the relevant details and configuration:
Configuration

-  Model: intfloat/multilingual-e5-large
- Format: ONNX
-    Spring Configuration: Using TransformersEmbeddingModel from Spring AI

### To reproduce

1. Export the intfloat/multilingual-e5-large model to ONNX format.
2. Configure Spring AI to use the exported ONNX model and tokenizer.
3. Attempt to instantiate the EmbeddingModel.

### Urgency

High

Could someone provide guidance on resolving this issue or point out what might be wrong with the configuration?

### Platform

Linux

### OS Version

Ubuntu 20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

pip install onnxruntime

### ONNX Runtime API

Python

### Architecture

X86

### Execution Provider

Default CPU

### Execution Provider Library Version

N/A

**Comment by Craigacp** [comment]
Please report this to Spring AI. When you do, you should put the full stack trace in as it's hard to tell where the error is without it.
