### ISSUE TITLE
[Build]: cmake', '--build', '/temp/liz/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '-j64']

### ISSUE THREAD

**Issue by rohanjuneja** [microsoft/onnxruntime#21381]
### Describe the issue

I am getting this issue while building onnxruntime from scratch. Searched from the internet, compiled cmake, glibc, and protobuf from scratch, updating all the tools. Still couldn't figure out this issue.
![image](https://github.com/user-attachments/assets/8150338a-7c06-420b-adce-004e8c425aba)
Could anyone help me out with this?

Thanks!

### Target platform

Linux leo 6.5.0-15-generic #15~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 12 18:54:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Build script

Build command: ./build.sh --config RelWithDebInfo --build_shared_lib --parallel

### Error / output

subprocess.CalledProcessError: Command '['/temp/liz/cmake-3.26.5-linux-x86_64/bin/cmake', '--build', '/temp/liz/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '-j64']' returned non-zero exit status 2>

Have attached a picture for the same.

### GCC / Compiler Version

Gcc/G++ version: 11.4.0

**Comment by snnn** [comment]
Please create a new env without protobuf c++ library, or use a vanlilla CPython from python.org to build the code. 
Add "--cmake_extra_defines FETCHCONTENT_TRY_FIND_PACKAGE_MODE=NEVER" to the build flags may also help.
