### ISSUE TITLE
TensorRT EP failed to create engine from network.

### ISSUE THREAD

**Issue by xlg-go** [microsoft/onnxruntime#21415]
### Describe the issue

I have a YOLOv8 detection model deployed using .NET with TensorRT as the provider. However, when I execute it, I encounter an error. Previously, when using TensorRT version 8, there were no issues. 

`[ErrorCode:ShapeInferenceNotRegistered] Non-zero status code returned while running TRTKernel_graph_torch_jit_4528351051880633562_0 node. Name:'TensorrtExecutionProvider_TRTKernel_graph_torch_jit_4528351051880633562_0_0' Status Message: TensorRT EP failed to create engine from network.`

### To reproduce

1. build onnxruntime from src code [branch main]
2. build nuget
3. install nuget
4. publish .net to unbuntu20.04

### Urgency

I am very anxious. 

### Platform

Linux

### OS Version

Ubuntu20.04

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

Microsoft.ML.OnnxRuntime.TensorRT.1.19.0-dev-20240719-0951-9140d9b1ff.nupkg

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

TensorRT

### Execution Provider Library Version

cuda12.5.1, cudnn9.2.1.18, tensorrt10.2.0.19

### GPU
NVIDIA Quadro P6000 (Pascal)

**Comment by xlg-go** [comment]
@yf711

Could you please help me?

**Comment by yf711** [comment]
Hi @xlg-go 
could you share a minimal repro case? Including the model you are using and sample code/input/output.
also, could you share the parameter you used to build ort nuget pkg from source?

**Comment by xlg-go** [comment]
> Hi @xlg-go could you share a minimal repro case? Including the model you are using and sample code/input/output. also, could you share the parameter you used to build ort nuget pkg from source?

`
./build.sh --parallel --build_shared_lib  --skip_submodule_sync --allow_running_as_root --skip_tests --config Release --update --build  --cmake_extra_defines "CMAKE_CUDA_ARCHITECTURES='50;52;53;60;61;62;70;72;75;80;86;87;89;90'"  --use_cuda --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu --use_tensorrt --tensorrt_home /usr/lib/x86_64-linux-gnu --build_nuget
`

A demo will be provided later. 

thank you very much~

**Comment by xlg-go** [comment]
> Hi @xlg-go could you share a minimal repro case? Including the model you are using and sample code/input/output. also, could you share the parameter you used to build ort nuget pkg from source?

Hi @yf711 

here is src demo, thanks a lot! The *.so file is very large, would it be convenient to use yours? 

[ML.OnnxRuntime.Test.zip](https://github.com/user-attachments/files/16329383/ML.OnnxRuntime.Test.zip)

**Comment by yf711** [comment]
Quick question, are you using pascal GPU, such as GTX 1080? Pascal GPU architecture is deprecated on TRT8.6

**Comment by xlg-go** [comment]
> Quick question, are you using pascal GPU, such as GTX 1080? Pascal GPU architecture is deprecated on TRT8.6
> 
> [NVIDIA/TensorRT#3826](https://github.com/NVIDIA/TensorRT/issues/3826) this issue matched your error code `Unsupported SM: 0x601`



The GPU in question is indeed a Quadro P6000, which utilises the Pascal architecture.
