### ISSUE TITLE
using TensorRT EP by nuget

### ISSUE THREAD

**Issue by alikad** [microsoft/onnxruntime#21428]
### Describe the issue

Hi
i want to use TensorRT EP but don't know how.
first is i used custom build with windows 10 and vs2019 but i get some errors at building mu project.
now I'm using nuget but i get same errors.
827 unresolved externals errors!
![image](https://github.com/user-attachments/assets/dec21f9d-eea7-4e1d-bb26-9248199b01c0)

the onnxRuntime config is this:
![image](https://github.com/user-attachments/assets/9463dc4d-0d02-4fe5-8949-5b2c23a6945e)

and the enviroment variable is this:
![image](https://github.com/user-attachments/assets/1b515601-bc15-406a-9f6c-7b0dfcd0d116)

### To reproduce
```c++
#include <iostream>
#include <assert.h>
#include <cmath>
#include <stdlib.h>
#include <stdio.h>
#include <vector>
#include "onnxruntime_c_api.h"
#include "cuda_provider_factory.h"
#include "onnxruntime_cxx_api.h"

int main() {
	Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");
	Ort::SessionOptions session_options;

#ifdef _WIN32
	const wchar_t* model_path = L"squeezenet.onnx";
#else
	const char* model_path = "squeezenet.onnx";
#endif

	OrtStatus* status = OrtSessionOptionsAppendExecutionProvider_Tensorrt(session_options, 0);
	if (status != nullptr) {
		return -1;
	}
	// Create the session
	Ort::Session session(env, model_path, session_options);

	return 0;
}
```
Please Help.

### Platform

Windows

### OS Version

10

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.18.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

TensorRT

### Execution Provider Library Version

CUDA 11.8

**Comment by tianleiwu** [comment]
For 1.18.1, since you use cuda 11.8, you need **cuDNN 8.9** and TRT 10.
See https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements. Note that it also applies to TensorRT EP.

If you want to use cuDNN 9, you will need install package for cuda 12: https://onnxruntime.ai/docs/install/#install-onnx-runtime-gpu-cuda-12x-1

**Comment by alikad** [comment]
thanks, i will test and send the result.

**Comment by alikad** [comment]
now i added "TensorRT-10.2.0.19.Windows.win10.cuda-11.8",  "cudnn-windows-x86_64-8.9.0.131_cuda11", "Microsoft.ML.OnnxRuntime 1.18.1", "Microsoft.ML.OnnxRuntime.Gpu 1.18.1" and cuda 11.8.
but same error.
Code:
![image](https://github.com/user-attachments/assets/42053b54-8c0a-411f-b158-21a3218f8d9d)

error:
![image](https://github.com/user-attachments/assets/ea6e534c-fcbc-495b-a88a-184cc6fcb363)

includes:
![image](https://github.com/user-attachments/assets/bf037035-059d-4d77-8c42-098fc992d53b)

linker libraries:
![image](https://github.com/user-attachments/assets/3c4bca45-dcb8-4c42-9208-4ced09bf4ae3)

linker inputs:
![image](https://github.com/user-attachments/assets/3a169cc2-cb03-4b3d-b460-ffdc16d161e8)


is there any error at my sample code or is it from the libraries?

**Comment by tianleiwu** [comment]
@alikad,

Could you follow the example code here:
https://github.com/microsoft/onnxruntime-inference-examples/blob/0de2e66e03981714e5308c457b72d785e98d0fe2/c_cxx/squeezenet/main.cpp

**Comment by alikad** [comment]
with little changes, it worked. i removed the " Ort::ThrowOnError" parts and the final results are achieved
thnks a lot.

**Comment by jywu-msft** [comment]
issue seems to be resolved. closing.
