### ISSUE TITLE
how to get multi output layers when run once?

### ISSUE THREAD

**Issue by luan1412167** [microsoft/onnxruntime#2143]
**Describe the bug**
I have a retinaface model with multi output layers. How to get those layers?.
![Screenshot from 2019-10-16 18-44-37](https://user-images.githubusercontent.com/37315746/66916384-499dd180-f045-11e9-9847-c9595b93eefb.png)
Whether I can get those layers in session.run() function?
`auto output_tensors = session.Run(Ort::RunOptions{nullptr}, input_names, &input_tensor_, 1, output_names, 1);`

**Urgency**
I must to implement retinaface and arcface on C++ for my thesis at university.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source 
- ONNX Runtime version: 0.5
- Python version: 
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by luan1412167** [comment]
@snnn  @hariharans29 can you help me? thanks

**Comment by luan1412167** [comment]
`   const char* input_names[] = { "data" };
    const char* output_names[] = { "face_rpn_cls_prob_reshape_stride32", "face_rpn_bbox_pred_stride32", "face_rpn_landmark_pred_stride32",
                                   "face_rpn_cls_prob_reshape_stride16", "face_rpn_bbox_pred_stride16", "face_rpn_landmark_pred_stride16",
                                   "face_rpn_cls_prob_reshape_stride8", "face_rpn_bbox_pred_stride8", "face_rpn_landmark_pred_stride8"};`

`    auto output_tensors = session.Run(Ort::RunOptions{nullptr}, input_names, &input_tensor_, 1, output_names, 9);
    float* cls[3];
    float* reg[3];
    float* pts[3];
    for (int k=0; k < output_tensors.size(); k+=3)
    {
        int i = k/3;
        reg[i] = output_tensors[k + 0].GetTensorMutableData<float>();
        pts[i] = output_tensors[k + 1].GetTensorMutableData<float>();
        cls[i] = output_tensors[k + 2].GetTensorMutableData<float>();
    }
`
Is my code right?

**Comment by hariharans29** [comment]
Can you please check #979 and see if that helps?

**Comment by hariharans29** [comment]
Also #1323

**Comment by luan1412167** [comment]
@hariharans29 thanks, I got it.
