### ISSUE TITLE
[Web] Conv_token_460" failed. Error: Unsupported activation Tanh

### ISSUE THREAD

**Issue by elephantpanda** [microsoft/onnxruntime#21467]
### Describe the issue

Getting the error: `Conv_token_460" failed. Error: Unsupported activation Tanh`
from [this model](https://huggingface.co/unity/sentis-jets-text-to-speech/blob/main/jets-text-to-speech.onnx): 

### To reproduce

Trying to run inference using the library:

https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.webgpu.min.js

(I have got it to work find with other models and this also works with the wasm provider).

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

webgpu

### Execution Provider

'webgpu' (WebGPU)

**Comment by skottmckay** [comment]
What version of ORT are you using? Tanh is listed as a supported operator for the WebGPU EP. 

https://github.com/microsoft/onnxruntime/blob/main/js/web/docs/webgpu-operators.md and it was added in August last year.

https://github.com/microsoft/onnxruntime/pull/17124

Possible that it's related to an attempted fusion and this helper needs updating: https://github.com/microsoft/onnxruntime/blob/ae3ec2e9ac1f1a1dde23407051d409fc8b52e639/js/web/lib/wasm/jsep/webgpu/ops/fuse-utils.ts#L18

@fs-eire or @guschmue would know better.

**Comment by elephantpanda** [comment]
The model says it's version 8. Yes, it sounds like it's a problem with  a fusion. A notice Tanh is not in that link you gave.

I tested it again and it works fine with wasm but not with webgpu. But I want to use webgpu because it's much faster.

**Comment by guschmue** [comment]
this should be fixed in ort-1.19.
