### ISSUE TITLE
[Feature Request] onnxruntime-node support for FreeBSD.

### ISSUE THREAD

**Issue by TByte007** [microsoft/onnxruntime#21508]
### Describe the feature request

Official or at least semi-official support for FreeBSD even if it's only CPU based for onnxruntime-node.

### Describe scenario use case

Any use on FreeBSD systems using nodejs.
Currently I get :
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for onnxruntime-node@1.18.0: wanted {"os":"win32,darwin,linux"} (current: {"os":"freebsd"})
npm ERR! notsup Valid os:  win32,darwin,linux
npm ERR! notsup Actual os: freebsd

**Comment by snnn** [comment]
Sorry  we don't have a build environment for FreeBSD. We do not have plan to publish FreeBSD binaries due to limited engineering resource available.

**Comment by yonas** [comment]
> We do not have plan to publish FreeBSD binaries due to limited engineering resource available.

@snnn Can you talk to your manager about this? When participating in the open source community, I don't understand how FreeBSD isn't fully supported in 2025 for such a large corporation as Microsoft.

**Comment by TByte007** [comment]
> > We do not have plan to publish FreeBSD binaries due to limited engineering resource available.
> 
> [@snnn](https://github.com/snnn) Can you talk to your manager about this? When participating in the open source community, I don't understand how FreeBSD isn't fully supported in 2025 for such a large corporation as Microsoft.

I guess $3.545 Trillion dollar market cap is not enough to add 2-3 lines of code fixes to support FreeBSD. The poor company like Microsoft can't sustain the expense of actually good developers.
