### ISSUE TITLE
When will NMS and RoIAlign op TensorRT version will be support?

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#2151]
When will NMS and RoIAlign op will be supported inference via TensorRT provider?

This is trivial in current SOTA detection and instance segmentation models.

**Comment by jinfagang** [comment]
Any walkaround on this issue? When would our circle will support them?

**Comment by jywu-msft** [comment]
It's up to Nvidia to implement that support in TensorRT.

That said, we do have Cuda implementations in ORT.
NMS is pending: https://github.com/microsoft/onnxruntime/pull/2082
RoiAlign is already checked in: https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/core/providers/cuda/object_detection

When using TensorRT provider, if it's not available in TensorRT ,it should fall back to ORT Cuda implementations.

**Comment by jinfagang** [comment]
@jywu-msft Thanks for reply. It's that means onnx-tensorrt adding RoIAlign plugin?

**Comment by jywu-msft** [comment]
according to https://github.com/onnx/onnx-tensorrt/blob/master/operators.md  , it's not supported.
we can ask nvidia whether they plan to support it.
For now, we have the [CUDA kernel implementation ](https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/core/providers/cuda/object_detection)in Onnxruntime

**Comment by jinfagang** [comment]
@jywu-msft  Thanks, I really hope there would be an implementation whether by nvidia or onnx-tensorrt repo contributors or onnxruntime.

As I post previously, when runing maskrcnn, there are some ops runing on CPU, does they can using CUDA at least now? such as Gather, TopK, NoneZero etc.

**Comment by ybrnathan** [comment]
TopK and NoneZero have been implemented and PR is pending. With all Ops implemented in Cuda, the Mask-RCNN latency drop to ~126ms on 1080-Ti GPU. We still have some CPU and GPU sync, that's mainly because tensor shape is always on CPU. Those pending PRs will be merged shortly.

**Comment by jinfagang** [comment]
@ybrnathan  Does these op supported now?

**Comment by faxu** [comment]
@jinfagang - please check the 1.1 release which includes several new CUDA ops.
