### ISSUE TITLE
qmath.cc error when building from source on Raspberry

### ISSUE THREAD

**Issue by snippler** [microsoft/onnxruntime#2152]
**Describe the bug**
Building process stops with following error
In file included from /home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/Core:201,
                 from /home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/ThreadPool:13,
                 from /home/pi/code/onnxruntime/include/onnxruntime/core/platform/threadpool.h:17,
                 from /home/pi/code/onnxruntime/onnxruntime/core/util/qmath.h:6,
                 from /home/pi/code/onnxruntime/onnxruntime/core/util/qmath.cc:4:
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/NEON/PacketMath.h: In function 'typename Eigen::internal::unpacket_traits<T>::type Eigen::internal::pfirst(const Packet&) [with Packet = __vector(4) float; typename Eigen::internal::unpacket_traits<T>::type = float]':
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/NEON/PacketMath.h:378:103: warning: requested alignment 16 is larger than 8 [-Wattributes]
 template<> EIGEN_STRONG_INLINE float   pfirst<Packet4f>(const Packet4f& a) { EIGEN_ALIGN16 float   x[4]; vst1q_f32(x, a); return x[0]; }
                                                                                                       ^
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/NEON/PacketMath.h: In function 'typename Eigen::internal::unpacket_traits<T>::type Eigen::internal::pfirst(const Packet&) [with Packet = __vector(4) int; typename Eigen::internal::unpacket_traits<T>::type = int]':
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/NEON/PacketMath.h:379:103: warning: requested alignment 16 is larger than 8 [-Wattributes]
 template<> EIGEN_STRONG_INLINE int32_t pfirst<Packet4i>(const Packet4i& a) { EIGEN_ALIGN16 int32_t x[4]; vst1q_s32(x, a); return x[0]; }
                                                                                                       ^
In file included from /home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/Core:204,
                 from /home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/ThreadPool:13,
                 from /home/pi/code/onnxruntime/include/onnxruntime/core/platform/threadpool.h:17,
                 from /home/pi/code/onnxruntime/onnxruntime/core/util/qmath.h:6,
                 from /home/pi/code/onnxruntime/onnxruntime/core/util/qmath.cc:4:
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/NEON/Complex.h: In function 'typename Eigen::internal::unpacket_traits<T>::type Eigen::internal::pfirst(const Packet&) [with Packet = Eigen::internal::Packet2cf; typename Eigen::internal::unpacket_traits<T>::type = std::complex<float>]':
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/NEON/Complex.h:161:40: warning: requested alignment 16 is larger than 8 [-Wattributes]
   EIGEN_ALIGN16 std::complex<float> x[2];
                                        ^
/home/pi/code/onnxruntime/onnxruntime/core/util/qmath.cc: In function 'void onnxruntime::QGemmu8s8_s32(int, int, int, const uint8_t*, int, uint8_t, const int8_t*, int, int8_t, int32_t*, int, onnxruntime::concurrency::ThreadPool*)':
/home/pi/code/onnxruntime/onnxruntime/core/util/qmath.cc:36:30: error: unused parameter 'thread_pool' [-Werror=unused-parameter]
     concurrency::ThreadPool* thread_pool) {
     ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
In file included from /home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/Core:233,
                 from /home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/ThreadPool:13,
                 from /home/pi/code/onnxruntime/include/onnxruntime/core/platform/threadpool.h:17,
                 from /home/pi/code/onnxruntime/onnxruntime/core/util/qmath.h:6,
                 from /home/pi/code/onnxruntime/onnxruntime/core/util/qmath.cc:4:
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h: In instantiation of 'Packet Eigen::internal::psincos_float(const Packet&) [with bool ComputeSine = true; Packet = __vector(4) float]':
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h:507:29:   required from 'Packet Eigen::internal::psin_float(const Packet&) [with Packet = __vector(4) float]'
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/NEON/MathFunctions.h:30:22:   required from here
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h:442:51: warning: requested alignment 16 is larger than 8 [-Wattributes]
     EIGEN_ALIGN_TO_BOUNDARY(sizeof(Packet)) float vals[PacketSize];
                                                   ^~~~
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h:443:51: warning: requested alignment 16 is larger than 8 [-Wattributes]
     EIGEN_ALIGN_TO_BOUNDARY(sizeof(Packet)) float x_cpy[PacketSize];
                                                   ^~~~~
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h:444:49: warning: requested alignment 16 is larger than 8 [-Wattributes]
     EIGEN_ALIGN_TO_BOUNDARY(sizeof(Packet)) int y_int2[PacketSize];
                                                 ^~~~~~
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h: In instantiation of 'Packet Eigen::internal::psincos_float(const Packet&) [with bool ComputeSine = false; Packet = __vector(4) float]':
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h:515:30:   required from 'Packet Eigen::internal::pcos_float(const Packet&) [with Packet = __vector(4) float]'
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/NEON/MathFunctions.h:36:22:   required from here
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h:442:51: warning: requested alignment 16 is larger than 8 [-Wattributes]
     EIGEN_ALIGN_TO_BOUNDARY(sizeof(Packet)) float vals[PacketSize];
                                                   ^~~~
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h:443:51: warning: requested alignment 16 is larger than 8 [-Wattributes]
     EIGEN_ALIGN_TO_BOUNDARY(sizeof(Packet)) float x_cpy[PacketSize];
                                                   ^~~~~
/home/pi/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h:444:49: warning: requested alignment 16 is larger than 8 [-Wattributes]
     EIGEN_ALIGN_TO_BOUNDARY(sizeof(Packet)) int y_int2[PacketSize];
                                                 ^~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/onnxruntime_util.dir/build.make:102: CMakeFiles/onnxruntime_util.dir/home/pi/code/onnxruntime/onnxruntime/core/util/qmath.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:189: CMakeFiles/onnxruntime_util.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Traceback (most recent call last):
  File "/home/pi/code/onnxruntime/tools/ci_build/build.py", line 1042, in <module>
    sys.exit(main())
  File "/home/pi/code/onnxruntime/tools/ci_build/build.py", line 980, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "/home/pi/code/onnxruntime/tools/ci_build/build.py", line 456, in build_targets
    run_subprocess(cmd_args)
  File "/home/pi/code/onnxruntime/tools/ci_build/build.py", line 196, in run_subprocess
    return subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/pi/code/onnxruntime/build/Linux/MinSizeRel', '--config', 'MinSizeRel']' returned non-zero exit status 2.

**Urgency**
Cannot build the software.

**System information**
- OS Platform and Distribution (Raspbian Buster):
- ONNX Runtime installed from (source):
- ONNX Runtime version: tried 3.13 and 3.15
- Python version: 3.7.3

**To Reproduce**
Describe steps/code to reproduce the behavior: I followed the instructions from here:
https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#ARM (native compiling on ARM device)

**Expected behavior**
Build process to finish

**Comment by jywu-msft** [comment]
@snnn FYI.

As a workaround, try removing this [line from build.py](https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/build.py#L329) and re-build.

**Comment by snippler** [comment]
It worked, thank you!

**Comment by chrisranderson** [comment]
@jywu-msft It looks like that line number has changed? Do you have a permalink or an updated line number?

**Comment by chrisranderson** [comment]
Nevermind. Here is the permalink. This will not go out of date. 

https://github.com/microsoft/onnxruntime/blob/f487f6be2577d8b69a1378ff79f71b87c270f3eb/tools/ci_build/build.py#L657
