### ISSUE TITLE
Is it possible to install onnxruntime for Python2?

### ISSUE THREAD

**Issue by snippler** [microsoft/onnxruntime#2153]
**Is your feature request related to a problem? Please describe.**
All functionalities of Python3 but for Python2

**System information**
- ONNX Runtime version (you are using): any

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by faxu** [comment]
No, only support 3.5-3.7.

**Comment by snippler** [comment]
Do you think it is difficult to change, if I wanted to do it myself?

**Comment by jywu-msft** [comment]
We don't plan on supporting python2.
All of our python code/tests are based on python3 so you'd need to convert it all to python2. There is a 3to2 project but I don't know how well it would work with our codebase.
