### ISSUE TITLE
[Mobile] build error: unknown type name 'bfloat16_t'; did you mean 'float16_t'

### ISSUE THREAD

**Issue by h122skite** [microsoft/onnxruntime#21538]
### Describe the issue

Building onnx from souce code under Windows for Android.
I use MINGW(GIT BASH) in Windows
build commnd :` ./build.bat  --android --android_sdk_path 'C:\Users\Jayho\AppData\Local\Android\Sdk' --android_ndk_path 'C:\Users\Jayho\AppData\Local\Android\Sdk\ndk\27.0.12077973' --android_abi arm64-v8a --android_api 27 --cmake_generator Ninja
`
```
-- ******** Summary ********
--   CMake version                     : 3.30.1
--   CMake command                     : C:/Users/Jayho/AppData/Local/Programs/Python/Python312/Lib/site-packages/cmake/data/bin/cmake.exe
--   System                            : Android
--   C++ compiler                      : C:/Users/Jayho/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
--   C++ compiler version              : 12.0.8
--   CXX flags                         : -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions -frtti -stdlib=libc++ -ffunction-sections -fdata-sections -DCPUINFO_SUPPORTED -Wnon-virtual-dtor
--   Build type                        : Debug
--   Compile definitions               : ORT_ENABLE_STREAM;EIGEN_MPL2_ONLY;__STDC_FORMAT_MACROS
--   CMAKE_PREFIX_PATH                 : C:\Users\Jayho\source\onnxruntime\onnxruntime\\build\Windows/Debug/installed
--   CMAKE_INSTALL_PREFIX              : C:/Program Files (x86)/onnxruntime
--   CMAKE_MODULE_PATH                 : C:/Users/Jayho/source/onnxruntime/onnxruntime/cmake/external
--
--   ONNX version                      : 1.16.1
--   ONNX NAMESPACE                    : onnx
--   ONNX_USE_LITE_PROTO               : ON
--   USE_PROTOBUF_SHARED_LIBS          : OFF
--   Protobuf_USE_STATIC_LIBS          : ON
--   ONNX_DISABLE_EXCEPTIONS           : OFF
--   ONNX_DISABLE_STATIC_REGISTRATION  : OFF
--   ONNX_WERROR                       : OFF
--   ONNX_BUILD_TESTS                  : OFF
--   ONNX_BUILD_BENCHMARKS             : OFF
--   ONNX_BUILD_SHARED_LIBS            :
--   BUILD_SHARED_LIBS                 : OFF
--
--   Protobuf compiler                 :
--   Protobuf includes                 :
--   Protobuf libraries                :
--   BUILD_ONNX_PYTHON                 : OFF
```

I've already check the answer(https://github.com/microsoft/onnxruntime/issues/20099) and try bNDK 27 but it doesn't work.

### To reproduce

Follow the instructions of https://onnxruntime.ai/docs/build/android.html.

### Platform

Android

### OS Version

Android NDK27 API 27

### ONNX Runtime Installation

Built from Source

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

1.16.1

### ONNX Runtime API

C++/C

### Architecture

X64

### Execution Provider

NNAPI

**Comment by skottmckay** [comment]
I can build on Windows and Linux (WSL) without a problem.

This line would indicate you're not building with NDK 6+

> --   C++ compiler                      : C:/Users/Jayho/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe

**Comment by h122skite** [comment]
> I can build on Windows and Linux (WSL) without a problem.
> 
> This line would indicate you're not building with NDK 26+
> 
> > --   C++ compiler                      : C:/Users/Jayho/AppData/Local/Android/Sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe

Oops, I found that I hardcoded the NDK path in some scripts so that it resulted in preventting the build command from overwriting it. This issue was gone after I remove the hardcode snippet.
