### ISSUE TITLE
Runtime issue with onnxruntime-win-x64-1.18.1

### ISSUE THREAD

**Issue by M3nxudo** [microsoft/onnxruntime#21543]
### Describe the issue

With the latest version of the prebuilt release files downloaded from https://github.com/microsoft/onnxruntime/releases?page=1 , this specific download [onnxruntime-win-x64-1.18.1.zip](https://github.com/microsoft/onnxruntime/releases/download/v1.18.1/onnxruntime-win-x64-1.18.1.zip)
I can correctly link the libraries and compile the project (i have stripped it down to the minimum dependencies) but whenever i execute it I get a runtime error before any code executes.
`Exception thrown at 0x00007FFFBCA03080 (msvcp140.dll) in CoreORTwVS.exe: 0xC0000005: Access violation reading location 0x0000000000000000.`
![image](https://github.com/user-attachments/assets/d00bec30-7cca-499f-a28f-cd1d776223c3)

![image](https://github.com/user-attachments/assets/86fbcadd-01ee-45e6-882d-856b9f3c7726)

I have double checked the configuration of the project, have tested with both a cmake project and a Visual Studio project, made sure dlls are in the execution directory but still can't fix the issue.

Additionally, if i change the include and library files to the 1.12.1 release, I can load the dependencies and perform tests with different models with no issues at all.

### To reproduce

```
#include <iostream>
#include <onnxruntime_cxx_api.h>

int main() {
    try {
        std::cout << "Initializing ONNX Runtime..." << std::endl;
        Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");
        std::cout << "ONNX Runtime initialized successfully." << std::endl;
    }
    catch (const Ort::Exception& e) {
        std::cerr << "ONNX Runtime error: " << e.what() << std::endl;
    }
    catch (const std::exception& e) {
        std::cerr << "Standard exception: " << e.what() << std::endl;
    }
    catch (...) {
        std::cerr << "Unknown exception occurred" << std::endl;
    }
    return 0;
}

```

### Urgency

We are trying to migrate our application to the new releases of Onnxruntime, to use some new operators that our models need that are not found on older versions of the runtime

### Platform

Windows

### OS Version

Version 10.0.17763 Build 17763

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.18.1

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by M3nxudo** [comment]
Tested all other release versions 1.12 - 1.18.0 and could load the library without the issue.

**Comment by CarlNobody** [comment]
**Describe the issue**
MNIST.cpp showed the same error 0xc0000142 either.

**Platform**
Windows

**OS Version**
21H2  19044.3803

**ONNX Runtime Installation**
Released Package

**ONNX Runtime Version or Commit ID**
onnxruntime-win-x64-1.18.1, copied all the dlls including onnxruntime.dll and onnxruntime_providers_shared.dll to compiled output executable file directory.

**ONNX Runtime API**
C++, onnxruntime-win-x64-1.18.1

**Architecture**
X64

**Execution Provider**
GPU


**Notes**
Tested with GPU version with cuda_12.4.0_551.61_windows displayed the same error.

**Comment by CarlNobody** [comment]
It's obviously that we missed a DLL called msvcp140.dll in our system, so download the Microsoft Visual C++ 2015 - 2022 Redistributable according to [https://answers.microsoft.com/en-us/windows/forum/all/vcruntime140dll-and-msvcp140dll-missing-in-windows/220f1caf-8eb9-413d-a7fe-1b13df1bfa5d](url) and install it, now the issue got fixed.

**Comment by charlescao460** [comment]
I encountered the same issue with `onnxruntime-win-x64-gpu-cuda12-1.18.1.zip` from the release, and I confirmed that Visual C++ Redistributable v14.40.33810 was installed. The issue remains.

The error is the same:
```
Exception thrown at 0x00007FFBCAE22F58 (msvcp140.dll) in Maplestory-Autopilot.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
```  

Call stack with PDB loaded:
![image](https://github.com/user-attachments/assets/6f3b0c19-0201-4864-aef0-604b391776c7)

**Comment by snnn** [comment]
> I confirmed that Visual C++ Redistributable v14.40.33810 was installed.

It is not enough. You need check what DLL was actually loaded. Because you may have multiple msvcp140.dll on the same machine.

See: https://github.com/microsoft/onnxruntime/issues/21102#issuecomment-2179395831

**Comment by charlescao460** [comment]
> > I confirmed that Visual C++ Redistributable v14.40.33810 was installed.
> 
> It is not enough. You need check what DLL was actually loaded. Because you may have multiple msvcp140.dll on the same machine.
> 
> See: [#21102 (comment)](https://github.com/microsoft/onnxruntime/issues/21102#issuecomment-2179395831)

I can confirm that the `msvcp140.dll` is indeed loaded. (And you can see it from the call stacks in my screenshot)

**Comment by ispysoftware** [comment]
Updated our nuget packages to use this latest version in our deployed clients can confirm it's throwing access violation exceptions on all deployments. Rolled back to 1.16.3 and it's fine.

**Comment by KeyurBhuva** [comment]
i run on 1.16.3 but same error.

**Comment by snnn** [comment]
Not a bug of ONNX Runtime.  Please use a debugger to check which  msvcp140.dll was loaded into the process and check the DLL's version.
