### ISSUE TITLE
[Build] Fail to build onnxruntime-web NPM package

### ISSUE THREAD

**Issue by JianxiaoLuIntel** [microsoft/onnxruntime#21542]
### Describe the issue

I am following the instruction(https://onnxruntime.ai/docs/build/web.html#install-npm-packages) to build ort-web npm package. But there are some errors.

### Target platform

Ubuntu22.04

### Build script

in <ORT_ROOT>/js/, run npm ci.
in <ORT_ROOT>/js/common/, run npm ci.
in <ORT_ROOT>/js/web/, run npm ci.

### Error / output

Get error in  <ORT_ROOT>/js/web/, run npm ci.

```
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
npm verb stack     at ChildProcess.emit (node:events:519:28)
npm verb stack     at maybeClose (node:internal/child_process:1105:16)
npm verb stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm verb pkgid electron@28.1.4
npm verb cwd /home/test/onnxruntime/js/web
npm verb Linux 5.15.0-116-generic
npm verb node v20.16.0
npm verb npm  v8.19.2
npm ERR! code 1
npm ERR! path /home/test/onnxruntime/js/web/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm verb exit 1
npm timing npm Completed in 132176ms
npm verb unfinished npm timer reify 1722246699851
npm verb unfinished npm timer reify:build 1722246700607
npm verb unfinished npm timer build 1722246700607
npm verb unfinished npm timer build:deps 1722246700607
npm verb unfinished npm timer build:run:postinstall 1722246700618
npm verb unfinished npm timer build:run:postinstall:node_modules/electron 1722246700618
npm verb code 1
```

**Comment by gyagp** [comment]
Do you have election in /home/test/onnxruntime/js/web/node_modules/? If no, it seems you have problem to download it. Within Intel, we use command "npx cross-env ELECTRON_GET_USE_PROXY=true GLOBAL_AGENT_HTTPS_PROXY=http(s)://<address>:<port> npm install electron" to solve the issue.

**Comment by JianxiaoLuIntel** [comment]
> Do you have election in /home/test/onnxruntime/js/web/node_modules/? If no, it seems you have problem to download it. Within Intel, we use command "npx cross-env ELECTRON_GET_USE_PROXY=true GLOBAL_AGENT_HTTPS_PROXY=http(s)://address:port npm install electron" to solve the issue.

It works, thank you !
