### ISSUE TITLE
Recommendation to improve MNIST example

### ISSUE THREAD

**Issue by xxtsxxts** [microsoft/onnxruntime#2157]
Hey, 
I'm a new user to ONNXRuntime, I got some suggestion to improve MNIST sample.
1.Add Python as a prerequisite for building OnnxRuntime at https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx
2.fix bug
Please add "const OrtApi* Ort::g_api = OrtGetApiBase()->GetApi(ORT_API_VERSION);" to MNIST.cpp
https://github.com/microsoft/onnxruntime/blob/master/samples/c_cxx/MNIST/MNIST.cpp
3.Please add step "Explictly copy model.onnx into the MNIST folder to run MNIST.exe" into readme file
https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx

Thanks.

**Comment by snnn** [comment]
The second will not be needed, when ONNX Runtime 1.0 is released.
