### ISSUE TITLE
[Mobile] Android Xperia 10 III no log output when setting ORT_LOGGING_LEVEL_VERBOSE

### ISSUE THREAD

**Issue by kapsyst** [microsoft/onnxruntime#21594]
### Describe the issue

When running the [ORT image classifier example](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/image_classification/android) on an Xperia 10 III (Sony SO-52B - Android 13), and setting the logging level to `ORT_LOGGING_LEVEL_VERBOSE`, with no other changes, log output is greatly reduced, only showing the following repeating message:
```
 [V:onnxruntime:ort-java, model.cc:181 SetOutputBuffer] Model::SetOutputBuffer, output shape [ 1 106 2 ]
 [V:onnxruntime:ort-java, model.cc:181 SetOutputBuffer] Model::SetOutputBuffer, output shape [ 1 106 2 ]
 [V:onnxruntime:ort-java, model.cc:181 SetOutputBuffer] Model::SetOutputBuffer, output shape [ 1 106 2 ]
 [V:onnxruntime:ort-java, model.cc:181 SetOutputBuffer] Model::SetOutputBuffer, output shape [ 1 106 2 ]
```
When I remove verbose logging (leaving the project in it's original state), I get the following output:
[ort_xperia_10_iii_no_verbose_logcat_output.log](https://github.com/user-attachments/files/16469597/ort_xperia_10_iii_no_verbose_logcat_output.log)
Which appears to be normal, minus the verbose logging.

I would like to enable Verbose logging as I'm having issues with model inference on this device, and are unable to diagnose without some more detailed logging.

I have confirmed this issue on two separate Xperia 10 III's, and have also confirmed that the same verbose logging works fine on a Google Pixel 7.

### To reproduce

1. Download and run the [ORT image classifier example for Android](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/image_classification/android).
2. Change line 40 of the [MainActivity.kt](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/mobile/examples/image_classification/android/app/src/main/java/ai/onnxruntime/example/imageclassifier/MainActivity.kt) from:
```
ortEnv = OrtEnvironment.getEnvironment()
```
To:
```
ortEnv = OrtEnvironment.getEnvironment(OrtLoggingLevel.ORT_LOGGING_LEVEL_VERBOSE)
```
3. Run on an Xperia 10 III (Sony SO-52B or equivalent)

### Urgency

We are experiencing incorrect output on this device only and are unsure as to what the cause is, and are unable to figure it out without verbose logging. Since a large proportion of our users use this device it would greatly appreciated if we could find the cause here.

### Platform

Android

### OS Version

13

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

1.18.0

### ONNX Runtime API

Java/Kotlin

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by edgchen1** [comment]
It is odd that it only shows those logs. So if you run `logcat -d '*:S onnxruntime:V'` you only see lines like this?
`[V:onnxruntime:ort-java, model.cc:181 SetOutputBuffer] Model::SetOutputBuffer, output shape [ 1 106 2 ]`

That looks to be coming from here:
https://github.com/microsoft/onnxruntime/blob/b87e8edb98ed85640ccf369625267786e91db920/onnxruntime/core/providers/nnapi/nnapi_builtin/model.cc#L181-L182

If that is displayed, it should mean verbose logging is enabled on the environment-wide logger. Would also expect to see other logs too.

>When I remove verbose logging (leaving the project in it's original state), I get the following output:
[ort_xperia_10_iii_no_verbose_logcat_output.log](https://github.com/user-attachments/files/16469597/ort_xperia_10_iii_no_verbose_logcat_output.log)
Which appears to be normal, minus the verbose logging.

I didn't see onnxruntime logs in the attached file. Are there any in the normal case?

**Comment by kapsyst** [comment]
@edgchen1 Thanks for your quick reply.

I'm not sure of the exact cause, but logging now appears to be working for these devices. Running `adb logcat` seemed to be a factor in getting the logs going again. Apologies for logging an issue before figuring this out. I'll close it.
