### ISSUE TITLE
Was there a 1.19.0 release?

### ISSUE THREAD

**Issue by cbourjau** [microsoft/onnxruntime#21617]
### Describe the issue

This may be a silly question, but was there a 1.19.0 release? A respective [tag](https://github.com/microsoft/onnxruntime/releases/tag/v1.19.0) was set last week which triggered a PR for the [conda-feedstock](https://github.com/conda-forge/onnxruntime-feedstock/pull/126). However, there was no proper release on github nor on [PyPI](https://pypi.org/project/onnxruntime/). Was there an intentional release or was this an accident? 

### To reproduce

NA

### Platform

Windows

### OS Version

NA

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.19.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by pranavsharma** [comment]
No, there was no 1.19 release.

**Comment by cbourjau** [comment]
Thanks for the clarification!

**Comment by duanqn** [comment]
Hi @pranavsharma, will the 1.19.0 be released soon? Can you share the schedule of it? Thanks!
