### ISSUE TITLE
 [Build]  Report an error while using comfyui  “CUDA_PATH is set but CUDA wasnt able to be loaded” 

### ISSUE THREAD

**Issue by XGCoder** [microsoft/onnxruntime#21610]
### Describe the issue

  Hello, comfyui is reporting an error while using it

Error occurred when executing Image Rembg (Remove Background):

`D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:891 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasnt able to be loaded. Please install the correct version of CUDA andcuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.`

My Cuda current environment：

> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2024 NVIDIA Corporation
> Built on Wed_Apr_17_19:36:51_Pacific_Daylight_Time_2024
> Cuda compilation tools, release 12.5, V12.5.40
> Build cuda_12.5.r12.5/compiler.34177558_0

My ComfyUI Version is the latest version

What I tried after this problem occurred：

Refer to [this link](https://github.com/microsoft/onnxruntime/issues/13576#issuecomment-2222821961)  to perform some necessary installation, but it did not take effect after restarting the computer

```
0.  conda avtivate stable 
1.  conda install pytorch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 pytorch-cuda=11.8 -c pytorch -c nvidia
2.  pip install torch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 --index-url https://download.pytorch.org/whl/cu118
3.  Download cuDNN   [Download cuDNN v8.9.7 (December 5th, 2023), for CUDA 12.x] [Windows build](https://developer.nvidia.com/downloads/compute/cudnn/secure/8.9.7/local_installers/12.x/cudnn-windows-x86_64-8.9.7.29_cuda12-archive.zip/) 
4.  Copy and paste it in the local CUDA/v12.5 corresponding directory

```

### Target platform

Windows11

### Build script

.

### Error / output

![image](https://github.com/user-attachments/assets/1c86bc4e-d49b-4a96-a906-ac125e2c4e3d)

**Comment by tianleiwu** [comment]
I saw that you install pytorch for cuda **11.8**, but use cudnn for cuda **12.x**, they are not compatible.
You can use same cuda and cudnn version in PyTorch and Onnxruntime.

For example, you can choose one of the following:

CUDA 11.x
-    Pytorch 2.2 up to 2.3.1 for cuda 11.8
-    CUDA 11.8
-    cuDNN 8.9 for cuda 11
-    onnxruntime built with cuda 11.8 and cudnn 8.9, like `pip install onnxruntime-gpu==1.18.1`

CUDA 12.x
-   Pytorch 2.4.0 for cuda 12.1 or 12.4
-   cuDNN 9.2 for cuda 12
-   onnxruntime built with cuda 12.x and cudnn 9.x, like `pip install onnxruntime-gpu==1.18.1 --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/`

For Windows, you will need install latest [VC Runtime](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) as well.

See https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements for more info.

**Comment by alivelee** [comment]
i encounter the same error, indeed the torch version is incompatible for cuda

**Comment by XGCoder** [comment]
> I saw that you install pytorch for cuda **11.8**, but use cudnn for cuda **12.x**, they are not compatible. You can use same cuda and cudnn major version in PyTorch and Onnxruntime.
> 
> For example, you can choose one of the following:
> 
> CUDA 11.x
> 
> * Pytorch 2.2 up to 2.3.1 for cuda 11.8 (cuDNN 8.9 is used in torch < 2.4).
> * CUDA 11.8
> * cuDNN 8.9 for cuda 11
> * onnxruntime built with cuda 11.8 and cudnn 8.9, like `pip install onnxruntime-gpu==1.18.1`
> 
> CUDA 12.x
> 
> * Pytorch 2.4.0 for cuda 12.1 or 12.4 (cuDNN 9.x is compatible with torch >= 2.4).
> * CUDA 12.x
> * cuDNN 9.x for cuda 12
> * onnxruntime built with cuda 12.x and cudnn 9.x, like `pip install onnxruntime-gpu==1.18.1 --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/`
> 
> For Windows, you will need install latest [VC Runtime](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170) as well.
> 
> See https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements for more info.

@tianleiwu  Hello, I have tried it but it does not solve my problem. How can I troubleshoot the version mismatch problem? What commands do I need to execute?

**Comment by XGCoder** [comment]
My problem was solved. My original configuration was installed in the stable environment of conda, but my comfyui was not running, so I had installed the correct version but still had problems.

If you still have problems locally, you can refer to [this link](https://www.cnblogs.com/io-T-T/p/18304208)
