### ISSUE TITLE
[Web] Wav2vec2 slower on WebGPU than WASM

### ISSUE THREAD

**Issue by gianlourbano** [microsoft/onnxruntime#21618]
### Describe the issue

Converted the [Wav2Vec2](https://huggingface.co/facebook/wav2vec2-base-960h) model from torch to onnx with following script
```py
import torch
import torch.onnx
from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC

model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

model.eval()

audio_length=16000
input = torch.ones([1, audio_length])

onnx_filename="wav2vec2.onnx"
torch.onnx.export(model,
                  input,
                  onnx_filename, 
                  export_params=True,
                  do_constant_folding=True,
                  opset_version=20,
                  input_names = ['input'],
                  output_names = ['output'],
                  dynamic_axes = {
                        'input': {1: 'audio_length'},
                        'output': {1: 'audio_length'}
                        # The second dimension (index 1) is variable
                    }
)
```

After splitting the audio in 10s chunks, i run the model first in wasm then in webgpu, noticing that the latter is much slower than bare wasm. This doesn't happen in onnxruntime python or even torch, where using the gpu has significative improvements.
 
For example, on a ~21s audio, I get the following timings where each step runs the InferenceSession on a 10s chunk of audio:

```
webgpu
step onnx 0: 6231 ms
step onnx 1: 5424 ms
step onnx 2: 882 ms
onnx: 17171 ms
total: 17238 ms

wasm
step onnx 0: 3381 ms
step onnx 1: 3222 ms
step onnx 2: 580 ms
onnx: 9365 ms
total: 9448 ms
```
from the webgpu profiling i see that Conv layers are the ones taking up most of the time. I tried binding the inputs to the gpu, but it didn't improve anything.

### To reproduce

Here's a link to a [sample repo](https://github.com/gianlourbano/w2v2_onnx_webgpu), instructions in README.

### Urgency

Urgent, as this project is related to my thesis

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.18.0

### Execution Provider

'wasm'/'cpu' (WebAssembly CPU), 'webgpu' (WebGPU)

**Comment by xenova** [comment]
Does this also happen with https://huggingface.co/Xenova/wav2vec2-base-960h?

raw link to model: https://huggingface.co/Xenova/wav2vec2-base-960h/resolve/main/onnx/model.onnx?download=true

I get a different error (fixed on main afaik):
```
An error occurred during model execution: "Error: [WebGPU] Kernel "[Conv] /wav2vec2/feature_extractor/conv_layers.2/conv/Conv" failed. Error: currently only support conv 1D and 2D".
```

Maybe you will see an improvement in speed with this model.

**Comment by gianlourbano** [comment]
Still gives me that error on @latest, trying with @dev (1.19.0-dev.20240804-ee2fe87e2d) it gives me still another error

```
Error: [WebGPU] Kernel "[Conv] /wav2vec2/feature_extractor/conv_layers.2/conv/Conv" failed. Error: filter does not have same dimension as input
```

**Comment by guschmue** [comment]
we can take a profile. Maybe a cross device copy because of an op we don't have on webgpu

**Comment by guschmue** [comment]
Hm, looks it runs Gelu on cpu what results in a costly cross device copy. We should support Gelu for webgpu, need to take a look why it is running on cpu.

![image](https://github.com/user-attachments/assets/d06fbda0-165a-4d1c-8511-ea9ab785924e)

**Comment by guschmue** [comment]
Gelu moved from custom op to onnx/opset-20 and we had not registered it in the onnx namespace.
Will send a PR. In the meantime you can speed it up by using opset-19. 

wasm 1200ms
wasm/4 threads: 524ms
webgpu main: 513ms
webgpu main + opset-19: 312ms
webgpu with Gelu fix: 325ms

There is still a pretty large time going to cross device copies because of a Reshape. Trying to understand that one.

**Comment by gianlourbano** [comment]
I have tried the model with opset-19 on my setup (ryzen 5 2600, RX 580 8GB) and a M1 macbook pro without seeing any improvements.

**Comment by gianlourbano** [comment]
I have also tried  the model with the latest release (1.19.0) and the dev branch, without any improvements. My times don't match with yours (even with 4 threads wasm is faster than webgpu); did you modify anything from the sample repo or did you use as it is?

**Comment by guschmue** [comment]
let me measure again - the Gelu issue should be fixed but there is still a cross device copy. We know why this cross device copy happen, just more work to fix that one.
In session options you can turn on the profiler with 
opt.enableProfiling = true;
and if you want the results you get them dumped to console with:
sess.endProfiling();

If you care about webgpu profiling you can set
ort.env.webgpu.profiling = {}
ort.env.webgpu.profiling.mode = 'default';

The formats are not very user friendly, and I have a bunch of tools on github to deal with that. But I need to badly document those or integrate it directly into ort-web.

**Comment by loretoparisi** [comment]
@guschmue If it can help I can see the reshape impl in [webgpu-torch](https://praeclarum.org/webgpu-torch/docs/functions/reshape.html)

Code [here](https://github.com/praeclarum/webgpu-torch/blob/920ceea/src/ops_artisanal.ts#L561)

**Comment by qjia7** [comment]
@gianlourbano #21871 should resolve too many gpu->cpu copying issue during the execution in your model. With that PR, I see that webgpu is already much faster than wasm on dGPUs for your model.  

For iGPUs, the gpu becomes bottleneck, one op `Conv` with shape `input[0]: [1,502,768] | float32, input[1]: [768,48,128] | float32, input[2]: [768] | float32, output[0]: [1,503,768] | float32` goes to a very slow path, which need to be further optimized. Will do that in a separate PR. Thanks.

**Comment by gianlourbano** [comment]
Thank you everyone for the help! With onnxruntime-web@1.20.0-dev.20240827-1d059b8702 i now get the following timings for a ~4min song:
wasm w/ 4 threads: ~60s
wgpu: ~16s

**Comment by gyagp** [comment]
Thanks for the update! But we're still waiting for the second enhancement (https://github.com/microsoft/onnxruntime/pull/21892) to be merged, and you're going to see another big perf improvement.

**Comment by qjia7** [comment]
@gianlourbano  All optimizations have been merged. Please verify and feel free to close this issue if it meets your requirement. If you still have any concerns, please let me know. Thanks.

**Comment by gianlourbano** [comment]
Yes, with all the optimizations i'd say my requirements are met :) We went from 20s steps to just ~800ms steps on my ryzen. Thank you for your help
