### ISSUE TITLE
Ensure links are distinguished from surrounding text in a way that does not rely on color (.text-blue-700)

### ISSUE THREAD

**Issue by Govardhani-T** [microsoft/onnxruntime#21637]
### GitHub Tags:
#A11ySev3; #A11yTCS; #DesktopWeb; #SH_ONNX Runtime & Ecosystem_Web_Mar2024; #ONNX Runtime & Ecosystem; #WCP; #Win11; #FTP; #P3_WCP; #ONNX Runtime; #ChromiumEdge; A11yWCAG2.1; #A11yMAS; #link-in-text-block; #WCAG1.4.1; #A11yAuto #use of color;
**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver".**
### Environment Details:
Application Name: WCP URLs - ONNX Runtime
URL: https://onnxruntime.ai/
Edge version: 123.0.2420.53 (Official build) (64-bit)
OS: Windows 11 version 23H2
### Steps to Reproduce
1. Hit the URL "https://onnxruntime.ai/blogs/accelerating-llama-2".
2. Run Accessibility Insights for web.
3. Now check that Ensure links are distinguished from surrounding text in a way that does not rely on color.
### Issue: 
Ensure links are distinguished from surrounding text in a way that does not rely on color (link-in-text-block - https://dequeuniversity.com/rules/axe/4.9/link-in-text-block?application=msftAI)
### Target application: 
ONNX Runtime | Blogs/accelerating-llama-2 - https://onnxruntime.ai/blogs/accelerating-llama-2
### Element path: 
p:nth-child(4) > .text-blue-700
### Snippet: 
<a href="https://blogs.microsoft.com/blog/2023/07/18/microsoft-and-meta-expand-their-ai-partnership-with-llama-2-on-azure-and-windows/" class="text-blue-700">announced</a>
### Related paths: 
  p:nth-child(4)
### How to fix: 
Fix any of the following:
  The link has insufficient color contrast of 2.74:1 with the surrounding text. (Minimum contrast is 3:1, link text: #1d4ed8, surrounding text: #141415)
  The link has no styling (such as underline) to distinguish it from the surrounding text

Environment: Microsoft Edge version 127.0.0.0

====

This accessibility issue was found using Accessibility Insights for Web 2.44.0 (axe-core 4.9.1), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.
### Attachment:
![image](https://github.com/user-attachments/assets/e64d0518-4451-46a8-979d-985e6be9cf5f)
![image](https://github.com/user-attachments/assets/3f33a929-764c-437f-86fa-9560893d1b76)

**Comment by Samhitha66** [comment]
#Rev:samhithaks;

**Comment by MaanavD** [comment]
Hey @Govardhani-T this should be addressed :)
