### ISSUE TITLE
Ensures lang attributes have valid values (pre[lang="bash"])

### ISSUE THREAD

**Issue by Govardhani-T** [microsoft/onnxruntime#21638]
### GitHub Tags:
#A11ySev2; #A11yTCS; #DesktopWeb; #SH_ONNX Runtime & Ecosystem_Web_Mar2024; #ONNX Runtime & Ecosystem; #WCP; #Win11; #FTP; #P3_WCP; #ONNX Runtime; #ChromiumEdge; A11yWCAG2.1; #A11yMAS; #valid-lang; #WCAG3.1.2; #A11yAuto #language of parts;
**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver".**
### Environment Details:
Application Name: WCP URLs - ONNX Runtime
URL: https://onnxruntime.ai/
Edge version: 123.0.2420.53 (Official build) (64-bit)
OS: Windows 11 version 23H2
### Steps to Reproduce
1. Hit the URL "https://onnxruntime.ai/docs/install/".
2. "ONNX Runtime" AMD ROC-m page appeared.
3. Run Accessibility Insights for web.
4. Observe that Ensures lang attributes have valid values (pre[lang="bash"])
### Issue: 
Ensures lang attributes have valid values (valid-lang - https://accessibilityinsights.io/info-examples/web/valid-lang)
### Target application: 
Install ONNX Runtime | onnxruntime - https://onnxruntime.ai/docs/install/
### Element path: 
tr:nth-child(2) > td:nth-child(4) > pre[lang="bash"]
### Snippet: 
<pre lang="bash">dotnet add package Microsoft.ML.OnnxRuntime.Training</pre>
### How to fix: 
Fix all of the following:
  Value of lang attribute not included in the list of valid languages

Environment: Microsoft Edge version 127.0.0.0

====

This accessibility issue was found using Accessibility Insights for Web 2.44.0 (axe-core 4.9.1), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.
### Attachment:
![image](https://github.com/user-attachments/assets/ee361ae7-eeb6-4ea2-89e6-77822f147146)

**Comment by Samhitha66** [comment]
#Rev:samhithaks;

**Comment by v-jagansai** [comment]
Verified the issue in the environment.:https://onnxruntime.ai/docs/install/
issue is not fixed.PFA
![Image](https://github.com/user-attachments/assets/46e4a189-1696-4e17-b34a-9196085e1f84)

**Comment by Govardhani-T** [comment]
Verified the issue in the environment. Issue is not reproing. hence closing the bug. PFA for reference.![Image](https://github.com/user-attachments/assets/e36b0dd9-7606-4701-a5ed-b314f9d4da00)

**Comment by Govardhani-T** [comment]
#Closed;
