### ISSUE TITLE
Need Maven Archive 1.18.1

### ISSUE THREAD

**Issue by ukhack** [microsoft/onnxruntime#21653]
### Describe the issue

stil 1.18.0
https://mvnrepository.com/artifact/com.microsoft.onnxruntime/onnxruntime_gpu

### To reproduce

wait for months

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.18.1

### ONNX Runtime API

Java

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 12.4

**Comment by snnn** [comment]
It was not planned. 
The package will be included in 1.19.0 release
