### ISSUE TITLE
[Mobile] .NET MAUI and OnnxRuntime integration on iPhone 11 -  iOS 17.5.1 with Hot Restart deployment/debugging - Loading InferenceSession results in 'The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.'

### ISSUE THREAD

**Issue by codingzerotohero** [microsoft/onnxruntime#21668]
### Describe the issue

LOGS:
03:44:52.253 Xamarin.PreBuilt.iOS[1812:349659] The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.

3:44:52.253 Xamarin.PreBuilt.iOS[1812:349659]    at Microsoft.ML.OnnxRuntime.SessionOptions..ctor()
   at CalorieLAST.AI.DishClassifyer..ctor(Byte[] modelStream) in D:\repos\CalorieLAST\CalorieLAST\CalorieLAST\AI\DishClassifyer.cs:line 24
03:44:52.253 Xamarin.PreBuilt.iOS[1812:349659] __Internal

03:44:52.253 Xamarin.PreBuilt.iOS[1812:349659]    at Microsoft.ML.OnnxRuntime.NativeMethods..cctor()

Code snippet:
![image](https://github.com/user-attachments/assets/7825f32b-5fe6-4dde-b37b-214faad534ef)

Verified with .NET Console App project with exact same code (minus the .NET MAUI parts) where I build up the classes and load the .onnx model in the exact same way that it works, with no problems. This only occurs on .NET MAUI project. I have also verified that the byte[] _modelStream is not null with break point and logging the size (this is removed from the picture to make it cleaner for you guys). The model is retrieved just fine from the location in which is exists:
![image](https://github.com/user-attachments/assets/e3c5bf8d-f361-4dad-a3a4-2ccc75e0e835)

As you can see I confirmed that it's possible to retrieve the .onnx model by logging all available files from the location first in the foreach loop.

!! Possibly important !!
When building the project, at the very beginning the build output says this:
C:/xxx/.nuget/packages/microsoft.ml.onnxruntime/1.18.1/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/onnxruntime : warning MT7091: The framework C:\xxx\.nuget\packages\microsoft.ml.onnxruntime\1.18.1\runtimes\ios\native\onnxruntime.xcframework\ios-arm64\onnxruntime.framework is a framework of static libraries, and will not be copied to the app.
1>C:/xxx/.nuget/packages/microsoft.ml.onnxruntime/1.18.1/buildTransitive/net8.0-ios15.4/../../runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/onnxruntime : warning MT7091: The framework C:\xxx\.nuget\packages\microsoft.ml.onnxruntime\1.18.1\buildTransitive\net8.0-ios15.4\..\..\runtimes\ios\native\onnxruntime.xcframework\ios-arm64\onnxruntime.framework is a framework of static libraries, and will not be copied to the app.
1>C:/xxx/.nuget/packages/microsoft.ml.onnxruntime/1.18.1/runtimes/ios/native/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/onnxruntime : warning MT7091: The framework C:\xxx\.nuget\packages\microsoft.ml.onnxruntime\1.18.1\runtimes\ios\native\onnxruntime.xcframework\ios-arm64\onnxruntime.framework is a framework of static libraries, and will not be copied to the app

^ which could be concerning, so I added this to the .csproj file:
![image](https://github.com/user-attachments/assets/5d08ff1e-6e15-4782-8b64-86ca6488dd49)

- and in the output, onnxruntime native library files are there:
- 
![image](https://github.com/user-attachments/assets/87eeaf51-9496-43c3-a8fc-177792d59bff)

### To reproduce

Clone this repo -> https://github.com/codingzerotohero/temp
Make a .NET MAUI project and just replace the relevant files with those from the repo. I develop for iOS using Hot Restart and my own Apple developer user, so I can't provide that. But that shouldn't matter here.

### Urgency

Completely blocked, would like to proceed but not urgent.

### Platform

MAUI

### OS Version

iOS 17.5.1

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

Microsoft.ML.OnnxRuntime

### ONNX Runtime Version or Commit ID

1.18.1

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
You can reference the structure of /csharp/tools/MauiModelTester.

The model must be in the raw resources.

We load it from there with a helper

https://github.com/microsoft/onnxruntime/blob/d616025884da05368c38270338b1ab3698e0ecb6/csharp/tools/MauiModelTester/Utils.cs#L10-L16

Usage: https://github.com/microsoft/onnxruntime/blob/d616025884da05368c38270338b1ab3698e0ecb6/csharp/tools/MauiModelTester/OrtInferenceSession.cs#L46

For iOS you'll also need to reference this package to resolve a symbol that is used for optional pre/post processing extensions:
https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.Extensions.Dummy

**Comment by codingzerotohero** [comment]
I did as you suggested and I am using the Utils.LoadResource method, but it doesn't seem to make any difference as far as I can tell:
![image](https://github.com/user-attachments/assets/73b700d1-e078-4595-9762-5093ec14c90d)

Breakpoint shows it loads the .onnx file successfully (built with PyTorch and converted to .onnx, by the way)

I added the package also, and it is referenced in the .csproj file, although I did remove SessionOptions for simplicity for testing, as it is optional, after all. Still, getting an exception.

![image](https://github.com/user-attachments/assets/e2258d0b-a3f1-4f98-bba6-9e220bbb5203)

It does give an exception for SessionOptions as well, though.

Please let me know if there's other things I can try to do.

**Comment by codingzerotohero** [comment]
![image](https://github.com/user-attachments/assets/19efe720-14db-4251-bbfe-66afa48c55d4)

Added OnnxRuntime.Managed as well, but it made no difference.

**Comment by codingzerotohero** [comment]
As far as I can tell, nobody has actually been able to get it to work, using .NET MAUI and OnnxRuntime on an actual iOS iPhone device. Only simulators. I see other people having the same issue, when trying to run on real device instead of simulator.

**Comment by skottmckay** [comment]
After adding the reference to Microsoft.ML.OnnxRuntime.Extensions.Dummy did you try removing your changes to the csproj? There's no csproj checked into your example repo so I can't tell.

Another thing you could try is explicitly creating the OrtEnv at startup. This could be done in CreateMauiApp with something like this at the end of that function:

`System.Diagnostics.Debug.WriteLine(OrtEnv.Instance().GetVersionString());`

**Comment by codingzerotohero** [comment]
@skottmckay - I put the whole thing here: https://github.com/codingzerotohero/temp/tree/master - including .csproj and solution (minus apple dev credentials)

I have tried removing the changes I have made where I attempt to add the onnxruntime.framework explicitly, yes.
I have also done as you suggested to explicitly create the OrtEnv at startup, in the CreateMauiApp function.

![image](https://github.com/user-attachments/assets/fd3e9717-dfd3-4ac6-b444-c17ed7285402)

- which results in this:
-[0:] The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.
[0:]    at Microsoft.ML.OnnxRuntime.OrtEnv.CreateDefaultEnv(OrtLoggingLevel logLevel, Byte[] logIdUtf8)
   at Microsoft.ML.OnnxRuntime.OrtEnv.CreateInstance()
   at System.Lazy`1[[Microsoft.ML.OnnxRuntime.OrtEnv, Microsoft.ML.OnnxRuntime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=f27f157f0a5b7bb6]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[Microsoft.ML.OnnxRuntime.OrtEnv, Microsoft.ML.OnnxRuntime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=f27f157f0a5b7bb6]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[Microsoft.ML.OnnxRuntime.OrtEnv, Microsoft.ML.OnnxRuntime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=f27f157f0a5b7bb6]].CreateValue()
   at System.Lazy`1[[Microsoft.ML.OnnxRuntime.OrtEnv, Microsoft.ML.OnnxRuntime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=f27f157f0a5b7bb6]].get_Value()
   at Microsoft.ML.OnnxRuntime.OrtEnv.Instance()
   at CalorieLAST.MauiProgram.CreateMauiApp() in D:\repos\CalorieLAST\CalorieLAST\CalorieLAST\MauiProgram.cs:line 24
[0:] __Internal
[0:]    at Microsoft.ML.OnnxRuntime.NativeMethods..cctor()

**Comment by edgchen1** [comment]
Unfortunately, this appears to be a limitation of the hot restart feature:
https://learn.microsoft.com/en-us/dotnet/maui/ios/hot-restart?view=net-maui-8.0#limitations

In particular:
"Static iOS libraries and frameworks aren't supported and you may see runtime errors or crashes if your app attempts to load these."

Currently, the Nuget package includes static frameworks for iOS.

**Comment by codingzerotohero** [comment]
I see. That is unfortunate... Guess I'll have to acquire a Mac, then.

Thanks for the input. Closing the issue as solved.
