### ISSUE TITLE
[DO NOT UNPIN] ORT 1.19 release candidates available for testing

### ISSUE THREAD

**Issue by MaanavD** [microsoft/onnxruntime#21678]
[ORT 1.19](https://github.com/microsoft/onnxruntime/wiki/Upcoming-Release-Roadmap) will be released soon, and release candidate builds are now available for testing. If you encounter issues, please report them ASAP by responding to this issue and tagging myself and @prathikr.

Release branch: [rel-1.19.0](https://github.com/microsoft/onnxruntime/tree/rel-1.19.0)
Release manager: @prathikr 

Here's the updated table with the entries shortened to just the build number and relevant descriptors added:

| Python Whls | Nuget | NPM | CocoaPods | Maven (Java) |
| --- | --- | --- | --- | --- |
| CPU: [1.19.0.dev20240805002](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/PyPI/ort-nightly/overview/1.19.0.dev20240805002) | Managed: [1.19.0-dev-20240805-1630](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/NuGet/Microsoft.ML.OnnxRuntime.Managed/overview/1.19.0-dev-20240805-1630-ee2fe87e2d) | Node: [1.19.0-dev.20240804](https://www.npmjs.com/package/onnxruntime-node/v/1.19.0-dev.20240804-ee2fe87e2d) | `pod 'onnxruntime-c', '1.19.0-dev+20240805002.ee2fe87'` | CPU: [1.19.0-rc1](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fonnxruntime/overview/1.19.0-rc1) |
| GPU: [1.19.0.dev20240731002](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/PyPI/ort-nightly-gpu/overview/1.19.0.dev20240731002) | CPU: [1.19.0-dev-20240805-1630](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/NuGet/Microsoft.ML.OnnxRuntime/overview/1.19.0-dev-20240805-1630-ee2fe87e2d) | React Native: [1.19.0-dev.20240804](https://www.npmjs.com/package/onnxruntime-react-native/v/1.19.0-dev.20240804-ee2fe87e2d) | `pod 'onnxruntime-objc', '1.19.0-dev+20240805002.ee2fe87'` | GPU: [1.19.0-rc1](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/maven/com.microsoft.onnxruntime%2Fonnxruntime_gpu/overview/1.19.0-rc1) |
| DirectML: [1.19.0.dev20240805002](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/PyPI/ort-nightly-directml/overview/1.19.0.dev20240805002) | GPU: [1.19.0-dev-20240805-0337](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/NuGet/Microsoft.ML.OnnxRuntime.Gpu/overview/1.19.0-dev-20240805-0337-88c811b638) | Web: [1.19.0-dev.20240804](https://www.npmjs.com/package/onnxruntime-web/v/1.19.0-dev.20240804-ee2fe87e2d) | `pod 'onnxruntime-training-c', '1.19.0-dev+20240805002.ee2fe87'` |  |
|  | WindowsAI: [1.19.0-dev-20240805-0131](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/NuGet/Microsoft.AI.MachineLearning/overview/1.19.0-dev-20240805-0131-88c811b) |  | `pod 'onnxruntime-training-objc', '1.19.0-dev+20240805002.ee2fe87'` |  |
|  | DirectML: [1.19.0-dev-20240805-1630](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/NuGet/Microsoft.ML.OnnxRuntime.DirectML/overview/1.19.0-dev-20240805-1630-ee2fe87e2d) |  |  |  |
|  | Training: [1.19.0-dev-20240805-0942](https://aiinfra.visualstudio.com/PublicPackages/_artifacts/feed/ORT-Nightly/NuGet/Microsoft.ML.OnnxRuntime.Training/overview/1.19.0-dev-20240805-0942-ee2fe87e2d) |  |  |  |

**Comment by Djdefrag** [comment]
#20713 

Hi, this issue has been fixed? 
It was introduced with version 1.18 and seems to affect both C++ and Python

**Comment by MaanavD** [comment]
@Djdefrag currently looking into it :) Will let you know soon! If it hasn't been, we can discuss a patch release as I see this has been around for a while and I'd hate to see it not being addressed for you

**Comment by henryruhs** [comment]
DirectML (and probably ROCm) multi threading still being broken in that release is a stopper (in my opinion).

https://github.com/microsoft/onnxruntime/issues/20713

**Comment by Djdefrag** [comment]
@henryruhs 

For me too. I am staying on 1.17.3 for now.

Have you also noticed a slowdown in inference speed with 1.19 compared to 1.17.3?
Using DirectML (and only 1 thread) I noticed a regression in speed of 10%.
