### ISSUE TITLE
1.18.1 regression: not working with Emgu.CV <= 4.8.0

### ISSUE THREAD

**Issue by KeterSCP** [microsoft/onnxruntime#21705]
### Describe the issue

Latest (as of today) version 1.18.1 of `Microsoft.ML.OnnxRuntime` nuget package is not working when project contains reference to the `Emgu.CV.runtime.windows Version="4.7.0.5276"` (or any version that is lower than 4.9.0.5494) nuget package.

### To reproduce

Program.csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Emgu.CV.runtime.windows" Version="4.7.0.5276" />
      <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.18.1" />
    </ItemGroup>

</Project>
```

Program.cs:

```csharp
using Microsoft.ML.OnnxRuntime;

using var options = new SessionOptions(); // this will trigger cctor on NativeMethods
Console.WriteLine("It works!");
```

1. Run the application
2. Observe exception:

```
The given version [14] is not supported, only version 1 to 10 is supported in this build.
Unhandled exception. System.TypeInitializationException: The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.ML.OnnxRuntime.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.ML.OnnxRuntime.SessionOptions..ctor()
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
```

Known workarounds:

- Rollback to `Microsoft.ML.OnnxRuntime Version="1.18.0"`
- Use `Emgu.CV.runtime.windows Version="4.9.0.5494"` (which I cannot afford, as my project depends on the specific version of EmguCV (4.7.0))

### Urgency

Issue is not urgent, but it is a regression from the 1.8.0 release.

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.8.1

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
I tried to repro locally but couldn't.

Based on the output it's finding a different version of onnxruntime.dll which is older. Sometimes there can be one at the system level. Check the loaded modules when debugging and/or the build output directory. The onnxruntime.dll should be version 1.18.x.

Not clear how 1.18.0 vs 1.18.1 would affect that though.

**Comment by KeterSCP** [comment]
Hi, @skottmckay! Thanks for your reply.

I tried to reproduce this on a completely clean laptop:

- Installed .NET 8 SDK
- Copied .csproj content from the above repro steps
- Used slightly reduced .cs repro code, as it only needs to call static ctor on NativeMethods:

```csharp
using Microsoft.ML.OnnxRuntime;

using var options = new SessionOptions(); // this will trigger cctor on NativeMethods
Console.WriteLine("It works!");
```

I built this with Debug config, and under `bin/Debug/net8.0/runtimes/win-x64/native` folder there is an `onnxruntime.dll` file with following properties:

![image](https://github.com/user-attachments/assets/c319a2f0-3e66-40f4-ae6e-11b81e51cb5a)

- Then I use `dotnet run` command from the powershell/cmd to run the application
- The exception still occurs.

And here is an interesting part:

If I change my command to `dotnet run -r win-x64`, I'm getting DLL initialization exception (which is not a case with 1.18.0):

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'onnxruntime' or one of its dependencies: A dynamic link library (DLL) initialization routine failed. (0x8007045A)
   at Microsoft.ML.OnnxRuntime.NativeMethods.OrtGetApiBase()
   at Microsoft.ML.OnnxRuntime.NativeMethods..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.ML.OnnxRuntime.SessionOptions..ctor()
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath)
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
```

When using 1.18.0 it is clearly visible that `onnxruntime.dll` is correctly loaded:

![image](https://github.com/user-attachments/assets/41a3cc27-1e11-4fd5-89ea-8bd1a7ebee18)

But with 1.18.1 it fails on load, hence cannot be shown in the application modules.

**Comment by KeterSCP** [comment]
Hi, @skottmckay! Were you able to reproduce the issue using the provided information above?

**Comment by KeterSCP** [comment]
Okay, I tried newer version of the NuGet package, and it works starting from 1.19.0, so there was some bug which was silently fixed. Closing this then
