### ISSUE TITLE
Why is CoreMLExecution an Objective-C class

### ISSUE THREAD

**Issue by 1enn0** [microsoft/onnxruntime#21708]
### Describe the issue

In my company, we build Digital Audio Workstations that allow loading external plugins at runtime. We have noticed the following issue with the implementation of the CoreML execution provider.

When the host application loads multiple plugins that depend on the ONNX Runtime (via a shared library that is shipped with the plugin bundle), we get the following warning:

    objc[2980]: Class CoreMLExecution is implemented in both /path/to/plugin-a.vst3/Contents/Frameworks/libonnxruntime.1.16.3.dylib (0x374be0cb8) and /path/to/plugin-b.vst3/Contents/Frameworks/libonnxruntime.1.15.1.dylib (0x372034ea8). One of the two will be used. Which one is undefined.

This could potentially lead to crashes!

I had a look at the implementation of the [CoreMLExecution](https://github.com/microsoft/onnxruntime/blob/154084efaa1a9d01f12825b7274410aa69dce0de/onnxruntime/core/providers/coreml/model/model.mm#L256) class and did not see a particular reason for it to be an Objective-C class. Especially since there already is the internal C++ bridge class [Execution](https://github.com/microsoft/onnxruntime/blob/154084efaa1a9d01f12825b7274410aa69dce0de/onnxruntime/core/providers/coreml/model/model.mm#L502). All code of the CoreMLExecution class could just be moved to the C++ Execution class, which would solve the above issue.

Is there a specific reason why it was implemented this way? 

I have successfully tested this change locally on my side and will attach a PR later. Unless there is a better way of solving this, I would be very happy if this would get accepted :)

### To reproduce

Outline for minimal working example to reproduce this issue:
- create two shared libs `a` and `b` that both depend on `libonnxruntime`
- create an executable `main` that links against `a` and `b`
- build `main`
- pretend both libs are shipping their own local version of `libonnxruntime` by copying the library to their corresponding build dir and using `install_name_tool` to make them use their local versions, e.g.:
  ```    
  install_name_tool -change @rpath/libonnxruntime.1.18.1.dylib @loader_path/libonnxruntime.1.18.1.dylib path/to/liba.dylib
  ```
- run `main`
  ```
   objc[8531]: Class CoreMLExecution is implemented in both [...]/onnxruntime-obcj-minimal-example/build/b/libonnxruntime.1.18.1.dylib (0x104608d30) and [...]/onnxruntime-obcj-minimal-example/build/a/libonnxruntime.1.18.1.dylib (0x102e4cd30). One of the two will be used. Which one is undefined.
  ```

### Urgency

It would be solve this problem as soon as possible, as more and more third party developers are integrating ONNX runtime in their plugins and most of them ship their own version of the ONNX runtime.

### Platform

Mac

### OS Version

macOS 14.4.1

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1d4b161145

### ONNX Runtime API

C++

### Architecture

ARM64

### Execution Provider

CoreML

**Comment by edgchen1** [comment]
AFAIK, it should be fine to not use an Objective-C class. Feel free to submit a PR.
