### ISSUE TITLE
[Build] ERROR: No matching distribution found for onnxruntime 

### ISSUE THREAD

**Issue by chinesejunzai12** [microsoft/onnxruntime#21749]
### Describe the issue

在使用pip install onnxruntime的时候, 报下面问题:
Using pip 24.2 from /home/deploy/anaconda3/envs/langchain_env/lib/python3.12/site-packages/pip (python 3.12)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime
请问同样的命令, 在python==3.11中尝试安装可以成功, 但是在3.12中不可以, 是因为目前还不知道python3.12版本么?

### Target platform

Linux

### Build script

pip install onnxruntime

### Error / output

ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime

**Comment by tianleiwu** [comment]
I saw python 3.12 wheels for Windows, Linux and Mac OS:
https://pypi.org/project/onnxruntime/#files

**Comment by chinesejunzai12** [comment]
ERROR: onnxruntime-1.19.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl is not a supported wheel on this platform.

**Comment by chinesejunzai12** [comment]
> ERROR: onnxruntime-1.19.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl is not a supported wheel on this platform.

目前还不支持

**Comment by tianleiwu** [comment]
> > ERROR: onnxruntime-1.19.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl is not a supported wheel on this platform.
> 
> 目前还不支持

What Linux are you using?
I just tried in Azure Linux and it is good. You can try Ubuntu in WSL (Windows Subsystem for Linux).

**Comment by chinesejunzai12** [comment]
操作系统如下:
LSB Version: :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description: CentOS Linux release 7.9.2009 (Core)
Release: 7.9.2009
Codename: Core
操作安装的结果是: 
ERROR: onnxruntime-1.19.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl is not a supported wheel on this platform.
------------------------------------------------------------------
发件人：Tianlei Wu ***@***.***>
发送时间：2024年8月17日(星期六) 01:28
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [microsoft/onnxruntime] [Build] ERROR: No matching distribution found for onnxruntime (Issue #21749)
ERROR: onnxruntime-1.19.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl is not a supported wheel on this platform.
目前还不支持
What Linux are you using?
 I just tried in Azure Linux and it is good. You can try Ubuntu in WSL (Windows Subsystem for Linux).

**Comment by chinesejunzai12** [comment]
目前使用的系统如下:
LSB Version: :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description: CentOS Linux release 7.9.2009 (Core)
Release: 7.9.2009
Codename: Core
------------------------------------------------------------------
发件人：Tianlei Wu ***@***.***>
发送时间：2024年8月17日(星期六) 01:28
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [microsoft/onnxruntime] [Build] ERROR: No matching distribution found for onnxruntime (Issue #21749)
ERROR: onnxruntime-1.19.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl is not a supported wheel on this platform.
目前还不支持
What Linux are you using?
 I just tried in Azure Linux and it is good. You can try Ubuntu in WSL (Windows Subsystem for Linux).

**Comment by wukongbuku** [comment]
> > ERROR: onnxruntime-1.19.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl is not a supported wheel on this platform.
> 
> 目前还不支持

是不是centos  7  连  1.8都不支持

——————————————————————————————————————
 pip install onnxruntime==1.18.1
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.18.1 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.18.1

**Comment by tianleiwu** [comment]
CentOS Linux 7 reached end of life (EOL) on June 30, 2024 so we no longer support it since 1.17.
You can still use onnxruntime version<= 1.16.3 on CentOS.

**Comment by alanwilter** [comment]
I use docker `Amazon Linux release 2 (Karoo)`:

```dockefile
FROM public.ecr.aws/lambda/python:3.10
```
Do you have a suggestion to replace it?

**Comment by alanwilter** [comment]
Nevermind, using `FROM public.ecr.aws/lambda/python:3.12` seems to have solved my problem.
