### ISSUE TITLE
[C++] How to change symbolic dimension?

### ISSUE THREAD

**Issue by bitnick10** [microsoft/onnxruntime#2174]
Is there a way to change symbolic dimension using C++ euqals python code below:
```
import onnx
mp = onnx.load_model('model.onnx')
mp.graph.input[0].type.tensor_type.shape.dim[0].dim_param = 'None'
```

**Comment by pranavsharma** [comment]
The onnx model is just a protobuf file and you can use the protobuf C++ APIs to load the model and change it as per your need.

**Comment by bitnick10** [comment]
Yes, I did it.
`pb.mutable_graph()->mutable_input()->at(0).mutable_type()->mutable_tensor_type()->mutable_shape()->mutable_dim()->at(0).set_dim_param("None");`
Thanks @pranavsharma
