### ISSUE TITLE
[Build] Android build issue on windows 

### ISSUE THREAD

**Issue by soham24** [microsoft/onnxruntime#21754]
### Issue Description

I am trying to build ONNX with training enabled for Android on my Windows system using the following command:

```bash
./build.bat --android --android_sdk_path C:/myfiles/cvdl/onnx_local/onnxruntime/Android --android_ndk_path C:/Users/Soham/AppData/Local/Android/Sdk/ndk/26.0.10792818 --android_abi arm64-v8a --android_api 29 --enable_training_apis --enable_training --enable_lto --build_shared_lib --build_java --use_xnnpack --skip_tests --config RelWithDebInfo --cmake_generator Ninja
```

I have the necessary C++ packages installed via Visual Studio Installer. However, I am encountering an error during the build process. The error appears to be related to the Pybind11 build, even though I am targeting Android. I am unsure why Pybind11 is being built as part of this process. Am I missing something?

### Target Platform

Android

### Build Script

```bash
./build.bat --android --android_sdk_path C:/myfiles/cvdl/onnx_local/onnxruntime/Android --android_ndk_path C:/Users/Soham/AppData/Local/Android/Sdk/ndk/26.0.10792818 --android_abi arm64-v8a --android_api 29 --enable_training_apis --enable_training --enable_lto --build_shared_lib --build_java --use_xnnpack --skip_tests --config RelWithDebInfo --cmake_generator Ninja
```

### Error Output

```
In file included from C:/myfiles/cvdl/onnx_local/onnxruntime/build/Windows/RelWithDebInfo/_deps/pybind11_project-src/include/pybind11/detail/../attr.h:13:
In file included from C:/myfiles/cvdl/onnx_local/onnxruntime/build/Windows/RelWithDebInfo/_deps/pybind11_project-src/include/pybind11/detail/common.h:208:
In file included from C:/Users/Soham/AppData/Local/Programs/Python/Python312/Include/Python.h:12:
C:/Users/Soham/AppData/Local/Programs/Python/Python312/Include/pyconfig.h:59:10: fatal error: 'io.h' file not found
#include <io.h>
```

### Visual Studio Version

2022

**Comment by edgchen1** [comment]
`--enable_training` implies `--enable_pybind`.
https://github.com/microsoft/onnxruntime/blob/b9f3a5d5b62d12fb3d90b3e98bf7d05aa8a560d6/tools/ci_build/build.py#L2588-L2589

Try only using `--enable_training_apis`. See https://onnxruntime.ai/docs/get-started/training-on-device.html for more information about on-device training.

**Comment by soham24** [comment]
@edgchen1 thank you so much. it worked
