### ISSUE TITLE
Can  release onnxruntime-gpu on Cuda 9?

### ISSUE THREAD

**Issue by MrRace** [microsoft/onnxruntime#2176]
I want to use the `onnxruntime-gpu` in Python.  If using `onnxruntime` （CPU version） it do inference a bit slow.  As most of my projects are based on CUDA 9, to advoid potential risk I can not update the GPU driver from CUDA 9 to CUDA 10. Could you release a onnxruntime-gpu version on CUDA 9?
Is there some other solutions ? It seems that I can not install two kinds of GPU driver CUDA 9 and CUDA 10 in the same GPU even if using the Docker!

Thanks a lot!

**Comment by pranavsharma** [comment]
We don't plan to use cuda 9 in our releases any more. You'll have to build the binary yourself from the source.

**Comment by pranavsharma** [comment]
Closing as per previous comment.
