### ISSUE TITLE
[Mobile] Pre-built 1.19.0 lib is missing for onnxruntime-android

### ISSUE THREAD

**Issue by csukuangfj** [microsoft/onnxruntime#21788]
### Describe the issue

Please see
https://mvnrepository.com/artifact/com.microsoft.onnxruntime/onnxruntime-android

<img width="1020" alt="Screenshot 2024-08-19 at 17 53 56" src="https://github.com/user-attachments/assets/870f59cd-b532-46ba-9021-525848366c78">

### To reproduce

Please visit
https://mvnrepository.com/artifact/com.microsoft.onnxruntime/onnxruntime-android

and you will find 1.19.0 is not there.

### Urgency

It is very urgent.

### Platform

Android

### OS Version

any

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

1.19.0

### ONNX Runtime API

C++/C

### Architecture

X64

### Execution Provider

Default CPU

### Execution Provider Library Version

1.19.0

**Comment by edgchen1** [comment]
It should be available soon. We are working through some publishing issues. See the release notes page for updates.
https://github.com/microsoft/onnxruntime/releases/tag/v1.19.0

**Comment by edgchen1** [comment]
It is up now.
https://mvnrepository.com/artifact/com.microsoft.onnxruntime/onnxruntime-android/1.19.0
