### ISSUE TITLE
[Web] [SD 1.5][SD Turbo][Whipser Base] Browser page out of memory - WebGPU and WebNN GPU EP

### ISSUE THREAD

**Issue by ibelem** [microsoft/onnxruntime#21810]
### Describe the issue

Aw, Snap! Out of memory when ORT session create started.

### Environment
Chrome Canary: 129.0.6666.0
Edge Canary: 129.0.2781.0 (Chromium Version: 129.0.6655.0)
GPU Driver: 32.0.101.5768

This issue can also be reproduced with WebGPU EP:
https://microsoft.github.io/webnn-developer-preview/demos/whisper-base/?ort=1.20.0-dev.20240815-8a59b4dc4b&provider=webgpu

### Tested ORT versions
- 1.20.0-dev.20240818-417aa00406	Fail
- 1.20.0-dev.20240815-8a59b4dc4b	Fail
- 1.19.0	Fail
- 1.20.0-dev.20240814-a0708a0d96	Pass
- 1.20.0-dev.20240811-154084efaa	Pass

### To reproduce

1. Launch latest Chrome Canary on Windows 11
"C:\Users\AppData\Local\Google\Chrome SxS\Application\chrome.exe" --enable-features=WebMachineLearningNeuralNetwork

2. Visit following links

- https://microsoft.github.io/webnn-developer-preview/demos/whisper-base/?ort=1.20.0-dev.20240815-8a59b4dc4b
- https://microsoft.github.io/webnn-developer-preview/demos/sd-turbo/?ort=1.20.0-dev.20240815-8a59b4dc4b -> Click "Load" button

3. If no OOM, refresh page and repeat step 2

### Urgency

High

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.19.0, 1.20.0-dev.20240815-8a59b4dc4b 

### Execution Provider

'webgpu' (WebGPU), Other / Unknown

**Comment by guschmue** [comment]
looking

**Comment by guschmue** [comment]
we've tried 3.1.64 as well and it still has some issues - reverting to 3.1.59

**Comment by guschmue** [comment]
fixed. Latest dev package should have the change.
