### ISSUE TITLE
[Build] Use Protobuf External Problem

### ISSUE THREAD

**Issue by moondayyy** [microsoft/onnxruntime#21828]
### Describe the issue

I am compiling the onnxruntime library with cmake, but I do not want to compile the thirdparty protobuf dependent library. 
I compiled externally, I can't do it with cmake  -DProtobuf_DIR.
How can I do?
Please help me, thanks.

### Target platform

Android

### Build script

mkdir -p /out/builds/onnxruntime/android/arm64/"$2"/lib && mkdir -p /out/builds/onnxruntime/android/arm64/"$2"/include && \
"$1"/build.sh --allow_running_as_root --config "$2" --android --android_sdk_path ../../"$3" --android_ndk_path "$3" --android_abi arm64-v8a \
--android_api "$4" --parallel --cmake_extra_defines BUILD_SHARED_LIBS=OFF --cmake_extra_defines CMAKE_TOOLCHAIN_FILE="$3"/build/cmake/android.toolchain.cmake \
--cmake_extra_defines utf8_range_DIR=/out/builds/protobuf/android/arm64/"$2"/lib/cmake/utf8_range --cmake_extra_defines Protobuf_DIR=/out/builds/protobuf/android/arm64/"$2"/lib/cmake/protobuf \
--cmake_extra_defines onnxruntime_USE_FULL_PROTOBUF=ON \
--cmake_extra_defines ANDROID_TOOLCHAIN=clang++ --cmake_extra_defines ANDROID_STL=c++_static --cmake_extra_defines CMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -g0" --cmake_extra_defines ANDROID_ABI=arm64-v8a || true && \
cd "$1"/build/Android/"$2" && cp -rf /utils/sc_android.mri ./ && ar -M < sc_android.mri && \
cp libonnxruntime.a /out/builds/onnxruntime/android/arm64/"$2"/lib && cp -r "$1"/include/* /out/builds/onnxruntime/android/arm64/"$2"/include
rm  -rf /"$1"/build/* || true

### Error / output

ld: error: undefined symbol: google::protobuf::internal::ArenaStringPtr::Set(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, google::protobuf::Arena*)
>>> referenced by provider_bridge_ort.cc
>>>               provider_bridge_ort.cc.o:(onnxruntime::ProviderHostImpl::AttributeProto__set_s(onnx::AttributeProto*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by provider_bridge_ort.cc
>>>               provider_bridge_ort.cc.o:(onnxruntime::ProviderHostImpl::AttributeProto__set_name(onnx::AttributeProto*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by graph.cc
>>>               graph.cc.o:(onnxruntime::NodeArg::NodeArg(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, onnx::TypeProto const*)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 226 more times

ld: error: undefined symbol: google::protobuf::MessageLite::ParseFromString(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)
>>> referenced by provider_bridge_ort.cc
>>>               provider_bridge_ort.cc.o:(onnxruntime::ProviderHostImpl::ModelProto__ParseFromString(onnx::ModelProto*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a

ld: error: undefined symbol: google::protobuf::internal::RepeatedPtrFieldBase::AddOutOfLineHelper(void*)
>>> referenced by provider_bridge_ort.cc
>>>               provider_bridge_ort.cc.o:(google::protobuf::RepeatedPtrField<onnx::TensorProto>::TypeHandler::Type* google::protobuf::internal::RepeatedPtrFieldBase::Add<google::protobuf::RepeatedPtrField<onnx::TensorProto>::TypeHandler>(google::protobuf::RepeatedPtrField<onnx::TensorProto>::TypeHandler::Type const*)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by provider_bridge_ort.cc
>>>               provider_bridge_ort.cc.o:(google::protobuf::RepeatedPtrField<onnx::NodeProto>::TypeHandler::Type* google::protobuf::internal::RepeatedPtrFieldBase::Add<google::protobuf::RepeatedPtrField<onnx::NodeProto>::TypeHandler>(google::protobuf::RepeatedPtrField<onnx::NodeProto>::TypeHandler::Type const*)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by provider_bridge_ort.cc
>>>               provider_bridge_ort.cc.o:(google::protobuf::RepeatedPtrField<onnx::TensorShapeProto_Dimension>::TypeHandler::Type* google::protobuf::internal::RepeatedPtrFieldBase::Add<google::protobuf::RepeatedPtrField<onnx::TensorShapeProto_Dimension>::TypeHandler>(google::protobuf::RepeatedPtrField<onnx::TensorShapeProto_Dimension>::TypeHandler::Type const*)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 14 more times

ld: error: undefined symbol: google::protobuf::RepeatedField<long>::Reserve(int)
>>> referenced by graph.cc
>>>               graph.cc.o:(onnxruntime::Graph::ToGraphProtoWithExternalInitializers(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, unsigned long) const) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto::AttributeProto(onnx::AttributeProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto::_InternalParse(char const*, google::protobuf::internal::ParseContext*)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 80 more times

ld: error: undefined symbol: google::protobuf::Arena::AllocateAlignedWithCleanup(unsigned long, std::type_info const*)
>>> referenced by graph.cc
>>>               graph.cc.o:(google::protobuf::RepeatedPtrField<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >::TypeHandler::Type* google::protobuf::internal::RepeatedPtrFieldBase::Add<google::protobuf::RepeatedPtrField<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >::TypeHandler>(google::protobuf::RepeatedPtrField<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >::TypeHandler::Type const*)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(void google::protobuf::internal::RepeatedPtrFieldBase::MergeFromInnerLoop<google::protobuf::RepeatedPtrField<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >::TypeHandler>(void**, void**, int, int)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by graph_flatbuffers_utils.cc
>>>               graph_flatbuffers_utils.cc.o:(onnxruntime::fbs::utils::LoadInitializerOrtFormat(onnxruntime::fbs::Tensor const&, onnx::TensorProto&, onnxruntime::OrtFormatLoadOptions const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 4 more times

ld: error: undefined symbol: google::protobuf::internal::AssignDescriptors(google::protobuf::internal::DescriptorTable const*, bool)
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto_AttributeType_descriptor()) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto_DataType_descriptor()) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto_DataLocation_descriptor()) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 4 more times

ld: error: undefined symbol: google::protobuf::RepeatedField<float>::Reserve(int)
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto::AttributeProto(onnx::AttributeProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto::_InternalParse(char const*, google::protobuf::internal::ParseContext*)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto::MergeImpl(google::protobuf::Message&, google::protobuf::Message const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 17 more times

ld: error: undefined symbol: google::protobuf::RepeatedPtrField<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > >::~RepeatedPtrField()
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto::AttributeProto(onnx::AttributeProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto::SharedDtor()) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::NodeProto::NodeProto(onnx::NodeProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 12 more times

ld: error: undefined symbol: google::protobuf::RepeatedField<long>::~RepeatedField()
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto::AttributeProto(onnx::AttributeProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto::SharedDtor()) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::TensorProto(onnx::TensorProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 6 more times

ld: error: undefined symbol: google::protobuf::RepeatedField<float>::~RepeatedField()
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto::AttributeProto(onnx::AttributeProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto::SharedDtor()) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::TensorProto(onnx::TensorProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 1 more times

ld: error: undefined symbol: vtable for google::protobuf::MessageLite
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto::AttributeProto(onnx::AttributeProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto::AttributeProto(onnx::AttributeProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto::~AttributeProto()) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 97 more times
>>> the vtable symbol may be undefined because the class is missing its key function (see https://lld.llvm.org/missingkeyfunction)

ld: error: undefined symbol: google::protobuf::internal::AssignDescriptors(google::protobuf::internal::DescriptorTable const* (*)(), std::__ndk1::once_flag*, google::protobuf::Metadata const&)
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto::GetMetadata() const) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::ValueInfoProto::GetMetadata() const) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::NodeProto::GetMetadata() const) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 22 more times

ld: error: undefined symbol: google::protobuf::RepeatedField<int>::Reserve(int)
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::TensorProto(onnx::TensorProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::_internal_add_int32_data(int)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::MergeImpl(google::protobuf::Message&, google::protobuf::Message const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 18 more times

ld: error: undefined symbol: google::protobuf::RepeatedField<double>::Reserve(int)
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::TensorProto(onnx::TensorProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::_internal_add_double_data(double)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::MergeImpl(google::protobuf::Message&, google::protobuf::Message const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 4 more times

ld: error: undefined symbol: google::protobuf::RepeatedField<unsigned long>::Reserve(int)
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::TensorProto(onnx::TensorProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::_internal_add_uint64_data(unsigned long)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::MergeImpl(google::protobuf::Message&, google::protobuf::Message const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 3 more times

ld: error: undefined symbol: google::protobuf::RepeatedField<unsigned long>::~RepeatedField()
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::TensorProto(onnx::TensorProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::SharedDtor()) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a

ld: error: undefined symbol: google::protobuf::RepeatedField<double>::~RepeatedField()
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::TensorProto(onnx::TensorProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::SharedDtor()) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a

ld: error: undefined symbol: google::protobuf::RepeatedField<int>::~RepeatedField()
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::TensorProto(onnx::TensorProto const&)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::TensorProto::SharedDtor()) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a

ld: error: undefined symbol: google::protobuf::Arena::AllocateAlignedWithHook(unsigned long, std::type_info const*)
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::AttributeProto* google::protobuf::Arena::CreateMaybeMessage<onnx::AttributeProto>(google::protobuf::Arena*)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::ValueInfoProto* google::protobuf::Arena::CreateMaybeMessage<onnx::ValueInfoProto>(google::protobuf::Arena*)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(onnx::NodeProto* google::protobuf::Arena::CreateMaybeMessage<onnx::NodeProto>(google::protobuf::Arena*)) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 22 more times

ld: error: undefined symbol: google::protobuf::Message::GetTypeName() const
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(vtable for onnx::AttributeProto) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(vtable for onnx::ValueInfoProto) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced by onnx-ml.pb.cc
>>>               onnx-ml.pb.cc.o:(vtable for onnx::NodeProto) in archive ../../../../thirdparty/onnxruntime/builds/Android/aarch64/MinSizeRel/lib/libonnxruntime.a
>>> referenced 22 more times

ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[3]: *** [CMakeFiles/as_vad_face_detection.dir/build.make:433: ../../../../builds/Android/aarch64/libas_vad_face_detection.so] Error 1

### GCC / Compiler Version

clang 14.0.6

**Comment by skottmckay** [comment]
I don't think it's possible currently.

We support specifying a custom protoc for use when cross-compiling, but the protobuf library used is always fetched and built directly to ensure it's the correct version. 

https://github.com/microsoft/onnxruntime/blob/983c4d57a4f1e35568545ab3b9971e83c26ecb7c/cmake/external/onnxruntime_external_deps.cmake#L204-L207

https://github.com/microsoft/onnxruntime/blob/983c4d57a4f1e35568545ab3b9971e83c26ecb7c/cmake/external/onnxruntime_external_deps.cmake#L215-L221

You could manually edit /cmake/external/onnxruntime_external_deps.cmake to try and use a pre-built protobuf.

**Comment by moondayyy** [comment]
> I don't think it's possible currently.
> 
> We support specifying a custom protoc for use when cross-compiling, but the protobuf library used is always fetched and built directly to ensure it's the correct version.
> 
> https://github.com/microsoft/onnxruntime/blob/983c4d57a4f1e35568545ab3b9971e83c26ecb7c/cmake/external/onnxruntime_external_deps.cmake#L204-L207
> 
> https://github.com/microsoft/onnxruntime/blob/983c4d57a4f1e35568545ab3b9971e83c26ecb7c/cmake/external/onnxruntime_external_deps.cmake#L215-L221
> 
> You could manually edit /cmake/external/onnxruntime_external_deps.cmake to try and use a pre-built protobuf.


Thanks for your answer. That's what I did anyway, after much effort.

**Comment by mudream4869** [comment]
You may provide your protobuf's `CMAKE_PREFIX_PATH`.  FetchContent_Declare's default behavior will first try
`find_package` if argument includes `FIND_PACKAGE_ARGS`.

```shell
CMAKE_PREFIX_PATH=(where your protobuf install) \
cmake ...
```

REF: https://cmake.org/cmake/help/latest/module/FetchContent.html#integrating-with-find-package
