### ISSUE TITLE
[Documentation] the example does not define test_data variable

### ISSUE THREAD

**Issue by R4ZZ3** [microsoft/onnxruntime#21822]
### Describe the documentation issue

Please provide definition of test_data on this page
h

This part:
from onnxconverter_common import auto_mixed_precision
import onnx

model = onnx.load("path/to/model.onnx")
model_fp16 = auto_convert_mixed_precision(model, test_data, rtol=0.01, atol=0.001, keep_io_types=True)
onnx.save(model_fp16, "path/to/model_fp16.onnx")

### Page / URL

https://onnxruntime.ai/docs/performance/model-optimizations/float16.html

**Comment by MaanavD** [comment]
Closed with #22250
