### ISSUE TITLE
[Build] 

### ISSUE THREAD

**Issue by MNOWAK1234** [microsoft/onnxruntime#21831]
### Describe the issue

I want to use this code in my native c++ android app. So according to this:
https://onnxruntime.ai/getting-started (I click Android C++ ARM64 Default CPU)
I need to build this on my own:
https://onnxruntime.ai/docs/build/android.html
And I'm using this command:
./build.bat --android --android_sdk_path <android sdk path> --android_ndk_path <android ndk path> --android_abi <android abi, e.g., arm64-v8a (default) or armeabi-v7a> --android_api <android api level, e.g., 27 (default)> --cmake_generator Ninja

### Target platform

Android

### Build script

./build.bat --android --android_sdk_path <android sdk path> --android_ndk_path <android ndk path> --android_abi <android abi, e.g., arm64-v8a (default) or armeabi-v7a> --android_api <android api level, e.g., 27 (default)> --cmake_generator Ninja

### Error / output

There is no error, but bin directory is empty and there is no include directory as well

### Visual Studio Version

unrelated

### GCC / Compiler Version

Clang 18.0.1

**Comment by edgchen1** [comment]
`libonnxruntime.so` should be in `<build directory>/<build config>`. E.g., under `./build/RelWithDebInfo` for build directory `./build` and config `RelWithDebInfo`.

An easier way may be to just grab the relevant files from the released .aar package.
E.g., the 1.19.0 .aar is [here](https://repo1.maven.org/maven2/com/microsoft/onnxruntime/onnxruntime-android/1.19.0/onnxruntime-android-1.19.0.aar). Unzip the .aar and find the headers in `headers/` and the `libonnxruntime.so` in `jni/<Android ABI>/`.
