### ISSUE TITLE
It isn't possible for a .NET package to use OnnxRuntime and have the application pick CPU or GPU

### ISSUE THREAD

**Issue by eerhardt** [microsoft/onnxruntime#2184]
Today, ML.NET builds an [Microsoft.ML.OnnxTransformer NuGet package](https://www.nuget.org/packages/Microsoft.ML.OnnxTransformer/) that depends on [Microsoft.ML.OnnxRuntime](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/). This ML.NET package allows users to bring in pre-built onnx models into their ML.NET pipeline.

ML.NET users will reference `Microsoft.ML.OnnxTransformer`, and write their C# code to use their onnx model as necessary.

Everything works great, until the ML.NET user says "I want to execute that onnx model on a GPU in my ML.NET pipeline". Currently this isn't possible because of the way the OnnxRuntime NuGet packages are structured.

* `Microsoft.ML.OnnxRuntime`
    - Contains the C++ assemblies that are used to compute on a CPU
    - Contains the .NET managed assemblies containing the .NET APIs
* `Microsoft.ML.OnnxRuntime.GPU`
    - Contains the C++ assemblies that are used to compute on a GPU
    - Contains the .NET managed assemblies containing the .NET APIs

Because the ".NET managed assemblies" are in both packages, this causes issues when another .NET package wants to depend on the OnnxRuntime. That package (ML.NET in our case) needs to pick one of these in order to compile against the .NET API. However, once you pick one of these, the consumers of ML.NET are no longer able to change to the other package (CPU to GPU in our case).

Instead, we should really split the OnnxRuntime up into 3 packages:

* Managed APIs package
* Native CPU package
* Native GPU package

This would allow for ML.NET to reference the `Managed APIs package` all the time. But then allow for the user to pick the `Native CPU package` or the `Native GPU package` package, depending on their needs. This is the pattern followed by TF.NET - 

* Managed APIs package - https://www.nuget.org/packages/TensorFlow.NET/
* Native CPU package - https://www.nuget.org/packages/SciSharp.TensorFlow.Redist/
* Native GPU package - https://www.nuget.org/packages/SciSharp.TensorFlow.Redist-Windows-GPU/

## Alternative 
An common alternate approach to this that isn't feasible is to tell ML.NET to split the `Microsoft.ML.OnnxTransformer` into 2 packages: CPU and GPU. The reason this isn't feasible is because there are other packages that depend on `Microsoft.ML.OnnxTransformer`.
* https://www.nuget.org/packages/Microsoft.ML.DnnImageFeaturizer.AlexNet
* https://www.nuget.org/packages/Microsoft.ML.DnnImageFeaturizer.ResNet101
* https://www.nuget.org/packages/Microsoft.ML.DnnImageFeaturizer.ResNet50
* https://www.nuget.org/packages/Microsoft.ML.DnnImageFeaturizer.ResNet18

If we split `Microsoft.ML.OnnxTransformer` into 2 packages, each of the above would need to be split into 2. Then we would have 10 packages instead of 5, which just doesn't scale.

**Comment by LuckyMallari** [comment]
@eerhardt do u have a proposed workaround for the moment? I also need to differentiate GU vs non GU references

**Comment by eerhardt** [comment]
Unfortunately no. I was hoping someone from the OnnxRuntime team would weigh in with their thoughts on this.

**Comment by jignparm** [comment]
@eerhardt, if ORT is split up into 3 packages (`managed C#`, `cpu-native` and `gpu-native`), ML.NET would need to take a dependency of the either the `cpu-native` or `gpu-native` package (taking a dependency on the `managed C#` is not sufficient to run)-- so you would still end up with 2 packages for each for 4 DnnImageFeaturizer packages (4 for DnnImageFeaturizer + `cpu-native` and 4 for DnnImageFeaturizer + `gpu-native`) if you need to support CPU and GPU scoring.

Is there an elegant way for the DnnImageFeaturizer package to dynamically install either the `cpu-native` or `gpu-native` packages based on user input? -- in the 3-package proposal, it seems like the native binaries would never be installed unless the user takes some explicit action.

**Comment by eerhardt** [comment]
> ML.NET would need to take a dependency of the either the cpu-native or gpu-native package

This is not true. ML.NET is not an application - it is a library. The end-user application would have to power to choose between the cpu-native or gpu-native package. ML.NET just needs to build against the managed APIs. Only when it comes time to run the application does the native assemblies need to come into play.

> Is there an elegant way for the DnnImageFeaturizer package to dynamically install either the cpu-native or gpu-native packages based on user input?

Yes, the user (in this case the application developer) picks which native package they want to use.

**Comment by LuckyMallari** [comment]
I agree. It should be in the same way others can be compiled. For example, you can compile darknet's yolo as gpu enabled or not, then you pick in you .Net application which to reference.

**Comment by jignparm** [comment]
>Yes, the user (in this case the application developer) picks which native package they want to use.

One downside with this approach is that when  users install the DnnImageFeaturizer package, and if it downloads only the `managed C#`  package as a dependency and not the `cpu-native` package, the installation may seem broken to the user. Their project would compile, but not run...  unless the user happens to know the name of the missing package (either the`cpu-native`  or `gpu-native` package).

The 3-package approach ensures that projects will compile successfully, but may not run (requires users to installing missing native packages). 

The 2-package approach ensures that projects will compile and run as well, but now lead to many duplicate packages (scaling issue).


>you can compile darknet's yolo as gpu enabled or not

Does darknet's yolo work for Linux as well? If it's GPU enabled, the app will not load without CUDA (i.e. there's a tax). The user most likely cannot run on CPU even, unless CUDA is present.

**Comment by pranavsharma** [comment]
@martinb35 FYI - we plan to work on this for our next release.

**Comment by yousiftouma** [comment]
Is this documented somewhere? That using `Microsoft.ML.OnnxTransformer` requires bringing in `Microsoft.ML.OnnxRuntime(.GPU)`? And are the GPU natives sufficient if one wants to use the "fallback to CPU" mode in `ApplyOnnxModel`?

**Comment by MagnusGabell** [comment]
I know this is closed but I hope you reopen cause the issue does not seem to be resolved. VS2022 and using GPU does not work. CPU is no problem but adding opts.AppendExecutionProvider_CUDA(1); results in Error: 

Microsoft.ML.OnnxRuntime.OnnxRuntimeException
  HResult=0x80131500
  Message=[ErrorCode:Fail] OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library
  Source=Microsoft.ML.OnnxRuntime
  StackTrace:
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.SessionOptions.AppendExecutionProvider_CUDA(Int32 deviceId)
   at Yolov5Net.App.Program.Main(String[] args) in Program.cs:line 22
   
   I have tested all combinations of OnnxRuntime. With and without GPU.
