### ISSUE TITLE
[Build] 

### ISSUE THREAD

**Issue by Waitday** [microsoft/onnxruntime#21877]
### Describe the issue

CUDA 12.2 cannot install onnxruntime-gpu==1.19.0

### Urgency

Extremely urgent

### Target platform

centos

### Build script

pip install onnxruntime==1.17.1

### Error / output

ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu==1.19.0 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime-gpu==1.19.0

**Comment by tianleiwu** [comment]
No python package built for centos. Tracked in https://github.com/microsoft/onnxruntime/issues/21678

**Comment by tianleiwu** [comment]
See https://github.com/microsoft/onnxruntime/issues/21912.

Centos is EOL.
