### ISSUE TITLE
[Build] The Control Flow Guard flag is not set in the binaries unless  the --use_binskim_compliant_compile_flags argument is used for build

### ISSUE THREAD

**Issue by vthaniel** [microsoft/onnxruntime#21870]
### Describe the issue

The Control Flow Guard flag is not set in the binaries unless  the --use_binskim_compliant_compile_flags argument is used for build
This argument was not required to be set(for the above flag) in older releases (prior to 1.18)

### Target platform

Windows 11

### Build script

build.bat --config RelWithDebInfo --parallel  --update --build --build_wheel --build_shared_lib

### Error / output

Upon Running the "Winchecksec" tool on the built binaries, the status of the flag "CFG" is "NotPresent"

### Visual Studio Version

Visual Studio 17 2022

**Comment by snnn** [comment]
You may set CFLAGS and CXXFLAGS by yourself. see https://cmake.org/cmake/help/latest/envvar/CXXFLAGS.html. You may add any flag there. In this way it gives us the best flexibility.
