### ISSUE TITLE
[Mobile] Test Application Reveals Multiple Failures in QnnHTPBackendTests Suite on Device

### ISSUE THREAD

**Issue by edmond-zhu** [microsoft/onnxruntime#21887]
### Describe the issue

During the verification of the onnxruntime library on the mobile devices, numerous failed test cases were identified after running onnxruntime_test_all. All the failures originated from the QnnHTPBackendTests test suite.

But QnnCPUBackendTests all pass.

### Test Environments
 * Xiaomi 11 (Qualcomm Snapdragon888 SM8350), Android11
 * Sony XPRIA 10 V (Qualcomm Snapdragon695 SM6375), Android14

### Versions
onnxruntime 1.18.0 + qnn sdk 2.22.6
onnxruntime 1.19.0 + qnn sdk 2.25.0

### Logs
~~~
......
[==========] 307 tests from 1 test suite ran. (5860 ms total)
[  PASSED  ] 33 tests.
[  FAILED  ] 274 tests, listed below:
[  FAILED  ] QnnHTPBackendTests.ArgMaxMinU8_DefaultAttrs
......
[  FAILED  ] QnnHTPBackendTests.WhereLargeDataBroadcastTransformedU8

274 FAILED TESTS
  YOU HAVE 21 DISABLED TESTS
~~~
pieces of error print, and other issues are in similar:
~~~
[ RUN      ] QnnHTPBackendTests.Split_Equal_Axis0_Opset18_U16
/works/AI/onnxruntime/onnxruntime/test/providers/qnn/qnn_test_utils.cc:160: Failure
Expected equality of these values:
  ep_nodes
    Which is: 0
  graph.NumberOfNodes()
    Which is: 4
Not all nodes were assigned to QNNExecutionProvider
Google Test trace:
/works/AI/onnxruntime/onnxruntime/test/common/random_generator.h:49: ORT test random seed: 2345
/works/AI/onnxruntime/onnxruntime/test/common/random_generator.h:49: ORT test random seed: 2345

/works/AI/onnxruntime/onnxruntime/test/providers/qnn/qnn_test_utils.h:495: Failure
Expected equality of these values:
  qnn_qdq_outputs.size()
    Which is: 0
  num_outputs
    Which is: 2
Google Test trace:
/works/AI/onnxruntime/onnxruntime/test/common/random_generator.h:49: ORT test random seed: 2345
/works/AI/onnxruntime/onnxruntime/test/common/random_generator.h:49: ORT test random seed: 2345

/works/AI/onnxruntime/onnxruntime/test/providers/qnn/qnn_test_utils.cc:160: Failure
Expected equality of these values:
  ep_nodes
    Which is: 0
  graph.NumberOfNodes()
    Which is: 4
Not all nodes were assigned to QNNExecutionProvider
Google Test trace:
/works/AI/onnxruntime/onnxruntime/test/common/random_generator.h:49: ORT test random seed: 2345
/works/AI/onnxruntime/onnxruntime/test/common/random_generator.h:49: ORT test random seed: 2345

/works/AI/onnxruntime/onnxruntime/test/providers/qnn/qnn_test_utils.h:495: Failure
Expected equality of these values:
  qnn_qdq_outputs.size()
    Which is: 0
  num_outputs
    Which is: 2
Google Test trace:
/works/AI/onnxruntime/onnxruntime/test/common/random_generator.h:49: ORT test random seed: 2345
/works/AI/onnxruntime/onnxruntime/test/common/random_generator.h:49: ORT test random seed: 2345

[  FAILED  ] QnnHTPBackendTests.Split_Equal_Axis0_Opset18_U16 (17 ms)
~~~

Full log:

[ort_test_failed_695.log](https://github.com/user-attachments/files/16775494/ort_test_failed_695.log)

### To reproduce

1. download and install qnn sdk from qualcomm
2. fully build onnxruntime in cli:
~~~
./build.sh --android --android_sdk_path ${ANDROID_SDK_ROOT} --android_ndk_path ${ANDROID_NDK_HOME} --android_abi arm64-v8a --android_api 29 --allow_running_as_root --build_shared_lib --config Release --parallel 10 --use_qnn --qnn_home /opt/qcom/aistack/qairt/2.25.0.240728
~~~
3. adb push onnxruntime_test_all, testdata folder and libraries from qnn (libraries under aarch64-android and hexagon-v68/hexagon-v66)
4. set environment by:
~~~
export LD_LIBRARY_PATH=<path_to_copied_libs>
~~~
6. run test under root permission:
~~~
onnxruntime_test_all --gtest_filter=QnnHtp*
~~~

### Platform

Android

### OS Version

11/14

### ONNX Runtime Installation

Built from Source

### Compiler Version (if 'Built from Source')

Clang 17.0.2, CMake 3.29.4, NDK r26d

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

tag 1.18.0/1.19.0

### ONNX Runtime API

C++/C

### Architecture

ARM64

### Execution Provider

Other / Unknown

### Execution Provider Library Version

QNN 2.22.6/2.25.0

**Comment by HectorSVC** [comment]
The log doesn't include the details why tests failed. You need to enable verbose log for more details.
I suggest you run make sure you can run pass one HTP test first, for example --gtest_filter=QnnHTPBackendTests.ConvU16U8S32_StaticBias. Enable verbose log to see what happened. Feels like some environment or dependency lib missing issue.

**Comment by edmond-zhu** [comment]
> The log doesn't include the details why tests failed. You need to enable verbose log for more details. I suggest you run make sure you can run pass one HTP test first, for example --gtest_filter=QnnHTPBackendTests.ConvU16U8S32_StaticBias. Enable verbose log to see what happened. Feels like some environment or dependency lib missing issue.

Thanks for the advice! 
Out of the tests related to QnnHTP, 33 passed, but the rest failed. 
I also tried setting the log level to verbose (in both the release and debug versions), but no additional information was printed as expected:
~~~
1|venus:/data/test/ort_test_1.18.0 # ORT_UNIT_TEST_MAIN_LOG_LEVEL=0 ./onnxruntime_test_all --gtest_filter=QnnHTPBackendTests.GlobalMaxPool_Large_Input_u8 
Setting log level to 0
Note: Google Test filter = QnnHTPBackendTests.GlobalMaxPool_Large_Input_u8
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from QnnHTPBackendTests
[ RUN      ] QnnHTPBackendTests.GlobalMaxPool_Large_Input_u8
/works/AI/onnxruntime/onnxruntime/test/providers/qnn/qnn_test_utils.cc:160: Failure
Expected equality of these values:
  ep_nodes
    Which is: 0
  graph.NumberOfNodes()
    Which is: 5
Not all nodes were assigned to QNNExecutionProvider
Google Test trace:
/works/AI/onnxruntime/onnxruntime/test/common/random_generator.h:49: ORT test random seed: 2345
/works/AI/onnxruntime/onnxruntime/test/common/random_generator.h:49: ORT test random seed: 2345

/works/AI/onnxruntime/onnxruntime/test/providers/qnn/qnn_test_utils.h:495: Failure
Expected equality of these values:
  qnn_qdq_outputs.size()
    Which is: 0
  num_outputs
    Which is: 1
Google Test trace:
/works/AI/onnxruntime/onnxruntime/test/common/random_generator.h:49: ORT test random seed: 2345
/works/AI/onnxruntime/onnxruntime/test/common/random_generator.h:49: ORT test random seed: 2345

[  FAILED  ] QnnHTPBackendTests.GlobalMaxPool_Large_Input_u8 (83 ms)
[----------] 1 test from QnnHTPBackendTests (83 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (83 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] QnnHTPBackendTests.GlobalMaxPool_Large_Input_u8

 1 FAILED TEST
~~~

I agree that the issue might be related to the environment and dependencies. Below are the files in my test folder. Could you help check if there are any hints or missing items that might be causing the problem?
![img](https://github.com/user-attachments/assets/a801c5e8-c3fa-4d71-9950-1d9eb8d3712d)

Thank you for kindly help!

**Comment by HectorSVC** [comment]
https://github.com/microsoft/onnxruntime/blob/924259617d86b91d481eba5a9a920b19d2a07d8f/onnxruntime/test/unittest_main/test_main.cc#L36
change ORT_LOGGING_LEVEL_WARNING to ORT_LOGGING_LEVEL_VERBOSE. I guess it failed to setup QNN backend.
you can try:
export LD_LIBRARY_PATH=/data/local/tmp/qnn/v225:/vendor/dsp/cdsp:/vendor/lib64/

**Comment by edmond-zhu** [comment]
Thank you @HectorSVC! after setup LD_LIBRARY_PATH, most test cases pass. the libraries under /vendor/lib64/ are the keys.

**Comment by zhangw864680355** [comment]
version：onnxruntime 1.19.0 + qnn sdk 2.25.0
devices: Snapdragon 8888 (SM8350 phone: realme gt), Android14

 build onnxruntime reference as follow：
./build.sh --build_shared_lib --skip_submodule_sync \
--android --config Release \
--parallel 10 \
--use_qnn --qnn_home /opt/qnn-2.25.0.240728 \
--android_sdk_path /opt/android-sdk-linux-r24.4.1 \
--android_ndk_path /opt/android-ndk-r26d \
--android_abi arm64-v8a \
--android_api 24 \
--cmake_generator Ninja \
--build_dir build/Android \
--allow_running_as_root

i use onnxruntime_test_all about htp，some tests are failed.
It's magical, executing the same command, sometimes successful, sometimes unsuccessful.

![image](https://github.com/user-attachments/assets/d1a1cfd9-4eb0-4269-af8b-979f408c901c)

**Comment by HectorSVC** [comment]
> version：onnxruntime 1.19.0 + qnn sdk 2.25.0 devices: Snapdragon 8888 (SM8350 phone: realme gt), Android14
> 
> build onnxruntime reference as follow： ./build.sh --build_shared_lib --skip_submodule_sync --android --config Release --parallel 10 --use_qnn --qnn_home /opt/qnn-2.25.0.240728 --android_sdk_path /opt/android-sdk-linux-r24.4.1 --android_ndk_path /opt/android-ndk-r26d --android_abi arm64-v8a --android_api 24 --cmake_generator Ninja --build_dir build/Android --allow_running_as_root
> 
> i use onnxruntime_test_all about htp，some tests are failed. It's magical, executing the same command, sometimes successful, sometimes unsuccessful.
> 
> ![image](https://private-user-images.githubusercontent.com/35286451/369592847-d1a1cfd9-4eb0-4269-af8b-979f408c901c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MTk4NDMsIm5iZiI6MTcyNzgxOTU0MywicGF0aCI6Ii8zNTI4NjQ1MS8zNjk1OTI4NDctZDFhMWNmZDktNGViMC00MjY5LWFmOGItOTc5ZjQwOGM5MDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDIxNTIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMTk2YjllN2U3MTQwZDAwZGEzYzlkOGMzNzE5ZDVhOTZjM2Q4N2M5ZDM5YThkZGFjZjZiNjhlMzBiNDJmZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1PtLGVcuBi7PU69QOJaE_M8usmA-I_ib_-HULQfAFD0)

Please try with our latest code and latest QNN if possible.
Please create separate issue since this one is closed.
