### ISSUE TITLE
[Build] I want to ask if centos 7 does not support 1.18.0 and higher

### ISSUE THREAD

**Issue by wukongbuku** [microsoft/onnxruntime#21912]
### Describe the issue

Excuse me, I want to ask if centos 7 does not support 1.18.0 and higher

pip install onnxruntime==1.18.1
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.18.1 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.18.1

### Target platform

centos 7

### Build script

*

### Error / output

pip install onnxruntime==1.18.1
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.18.1 (from versions: 1.12.0, 1.12.1, 1.13.1, 1.14.0, 1.14.1, 1.15.0, 1.15.1, 1.16.0, 1.16.1, 1.16.2, 1.16.3)
ERROR: No matching distribution found for onnxruntime==1.18.1

### Visual Studio Version

python 3.10.0

### GCC / Compiler Version

cuda 12.4

**Comment by tianleiwu** [comment]
We no longer support CentOS 7 since it is EOL.

**Comment by tzhang2014** [comment]
> CentOS Linux 7 reached end of life (EOL) on June 30, 2024 so we no longer support it since 1.17. You can still use onnxruntime version<= 1.16.3 on CentOS.

hello, my env is centos 7.6, gcc-10.2, cmake-3.27, onnxruntime==1.16.3， but I got an error during compilation,as follow,

![Image](https://github.com/user-attachments/assets/7bd61a2c-3ab2-4e2a-88ee-6de0bea49a61)

**Comment by tzhang2014** [comment]
> > CentOS Linux 7 reached end of life (EOL) on June 30, 2024 so we no longer support it since 1.17. You can still use onnxruntime version<= 1.16.3 on CentOS.
> 
> hello, my env is centos 7.6, gcc-10.2, cmake-3.27, onnxruntime==1.16.3， but I got an error during compilation,as follow,
> 
> ![Image](https://github.com/user-attachments/assets/7bd61a2c-3ab2-4e2a-88ee-6de0bea49a61)

./build.sh --config RelWithDebInfo --build_shared_lib --parallel 36 --compile_no_warning_as_error --skip_submodule_sync
