### ISSUE TITLE
Python ORT latest is available in 1.19.0 whereas NuGet package is 1.19.1

### ISSUE THREAD

**Issue by claeyzre** [microsoft/onnxruntime#21953]
### Describe the issue

Hello,
We used ORT both in C# and in Python and we need to maintain perfect alignement.
In the recent 1.19 release there is a discrepancy:
- The release in github goes up to 1.19.0
- The NuGet package is 1.19.1 (Was there a fix not published in the github release ?)
- The Pypi package is 1.19.0

Why is there a 1.19.1 package on Nuget ? 

Thanks,

### To reproduce

None

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.1.9.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by tianleiwu** [comment]
There are not going to be 1.19.1 python package.

Please try [1.19.2](https://github.com/Microsoft/onnxruntime/releases/tag/v1.19.2) instead.
