### ISSUE TITLE
[Build] 1.19.0 still depends on CUDA 11.x

### ISSUE THREAD

**Issue by tibortakacs** [microsoft/onnxruntime#21965]
### Describe the issue

Although the description of the 1.19.0 release writes that "Default GPU packages use CUDA 12.x and Cudnn 9.x", the 1.19.0 build still depends on CUDA 11.x.

<img width="751" alt="Screenshot 2024-09-03 115432" src="https://github.com/user-attachments/assets/a6a9a461-a98d-4282-bd4a-3736086d4388">

### Target platform

Windows

### Build script

n/a

### Error / output

n/a

**Comment by Alarmod** [comment]
Work normal with CUDA 12.4.0 (with GPU) and don't work with CUDA 12.4.1 (dll files changed in CUDA 12.4.1)

**Comment by tianleiwu** [comment]
It's true that both onnxruntime-win-x64-gpu-1.19.0.zip and onnxruntime-win-x64-cuda-1.19.0.zip depends on cuda 11.x and cudnn8.x.  A walkaround is to copy the dll files from onnxruntime-gpu 1.19.0 python package, which supports cuda 12.

The coming 1.19.2 release shall support cuda 12 in onnxruntime-win-x64-gpu-1.19.2.zip.

**Comment by tianleiwu** [comment]
@tibortakacs, Please try onnxruntime-win-x64-gpu-1.19.2.zip in https://github.com/microsoft/onnxruntime/releases/tag/v1.19.2

**Comment by Alarmod** [comment]
> @tibortakacs, Please try onnxruntime-win-x64-gpu-1.19.2.zip in https://github.com/microsoft/onnxruntime/releases/tag/v1.19.2
Tested with CUDA 12.4.0 + CUDNN 9.2.0 and 9.2.1 - working OK

**Comment by tibortakacs** [comment]
Thank you, all, for hard work and fixing this. Fantastic.

**Comment by tianleiwu** [comment]
@juntaosun, you can install python package for cuda 11.8 version like 
```
pip install onnxruntime-gpu==1.19.2 --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-11/pypi/simple/
```
