### ISSUE TITLE
Has there been a 1.19.2 release (tag was set)

### ISSUE THREAD

**Issue by cbourjau** [microsoft/onnxruntime#21977]
### Describe the issue

Has there been a 1.19.2 release? It doesn't look like it to me but a [tag](https://github.com/microsoft/onnxruntime/releases/tag/v1.19.2) was. If it indeed was erroneous ([again](https://github.com/microsoft/onnxruntime/issues/21617)), I'd like to draw attention to the fact that these tags trigger downstream packaging bots (e.g. [here](https://github.com/conda-forge/onnxruntime-feedstock/pull/128) for conda forge). Unless there actually was a 1.19.2 release, we are now going to close that PR, but will not get notified about the actual release of 1.19.2 at a later point; presumably with the tag pointing to a different commit. This is also the reason why there is no 1.19.0 on conda-forge yet. 

Please consider not placing version tags and then force-pushing(?) them to different commits if it can be avoided. It creates additional work for downstream package maintainers. 

### To reproduce

NA

### Platform

Windows

### OS Version

NA

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

NA

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by tianleiwu** [comment]
Yes, it is a patch release. See https://pypi.org/project/onnxruntime-gpu/#history.

**Comment by cbourjau** [comment]
Thanks! May I ask what happened to 1.19.1 and will there be a release note?

**Comment by tianleiwu** [comment]
There will not be a release note for 1.19.1. @prathikr may explain it.
