### ISSUE TITLE
[Build] CMake Fails to Find Non-LTS Abseil Library (Download Triggered)

### ISSUE THREAD

**Issue by mudream4869** [microsoft/onnxruntime#21976]
### Describe the issue

CMake cannot locate a locally installed Abseil library that is not an LTS (Long-Term Support) version. As a result, the build process proceeds to download the Abseil library automatically.

Ref: [Abseil will only give a version in lts branch.
](https://github.com/abseil/abseil-cpp/commit/ebdba5af75fab91ebe9bc4daa0077f9c57c36692)

### Urgency

Not Urgent - Workaround in Place:

Currently, the issue of CMake downloading Abseil despite a local installation is not considered urgent. A temporary workaround has been implemented by removing the version check from the FetchContent_Declare command. This allows CMake to use the locally installed Abseil library without triggering the download.

### Target platform

ubuntu 24.04

### Build script

```bash
cmake -GNinja \
      -DCMAKE_BUILD_TYPE=Release \
      -Donnxruntime_BUILD_UNIT_TESTS=ON \
      -Donnxruntime_USE_AVX=ON \
      -Donnxruntime_BUILD_SHARED_LIB=ON \
      -DPYTHON_EXECUTABLE=$(which python3) \
      -DFETCHCONTENT_TRY_FIND_PACKAGE_MODE=ALWAYS \
      -DONNX_USE_PROTOBUF_SHARED_LIBS=ON \
      ../onnxruntime-1.19.0/cmake
```

### Error / output

The provided output lists the contents of the CMake dependency download folder (build/_deps).

```
$ ls -al build/_deps | grep abs
drwxr-xr-x  4 mudream mudream 4096 Sep  4 04:33 abseil_cpp-build
drwxr-xr-x  6 mudream mudream 4096 Sep  4 04:33 abseil_cpp-src
drwxr-xr-x  4 mudream mudream 4096 Sep  4 04:33 abseil_cpp-subbuild
```

This indicates that CMake has successfully downloaded the Abseil library.

**Comment by RyanUnderhill** [comment]
@yuslepukhin, in case you have any ideas on this?

**Comment by snnn** [comment]
So, the easiest fix would be upgrading ABSL to a released version?

**Comment by mudream4869** [comment]
> So, the easiest fix would be upgrading ABSL to a released version?

Applying to the latest abseil LTS version seems to work. Unittest pass on ubuntu 24.04.

**Comment by snnn** [comment]
Thanks. I will make a PR.

**Comment by Manamama** [comment]
A related problem: 
absl::demangle_rust error in ONNX Runtime build on Droid, Termux. 
Only compiling and installing newest abseil from:
https://github.com/abseil/abseil-cpp/ worked. 

Ref: 
`~/downloads/onnxruntime $ apt list | grep abseil                                                                            WARNING: apt does not have a stable CLI interface. Use with caution in scripts.                                                                                                           abseil-cpp/stable,now 20240116.2-1 aarch64 [installed,automatic]                                                            ~/downloads/onnxruntime $
`

Operating System:
- Name: Android 11 aarch64, Linux, 4.14.186+ (Termux)
- Kernel: 4.14.186+
- Shell: /data/data/com.termux/files/usr/bin/bashso 
uname -a
Linux localhost 4.14.186+ #1 SMP PREEMPT arch64 Android                
(Termux)

**Comment by Manamama** [comment]
Update: many other updates are needed for Termux now:

`apt install boost-headers'
[Eigen](https://github.com/PX4/eigen) needs to be cloned and hand compiled to get:
`eigen/stable,now 3.4.0 aarch64 [installed]`

`export BUILD_MLAS_NO_ONNXRUNTIME=ON`
A newish gcc...
