### ISSUE TITLE
Extra Memory Usage due to 'CreateSessionFromArray' copying the model again 

### ISSUE THREAD

**Issue by mingyueliuh** [microsoft/onnxruntime#21992]
### Describe the issue

When creating sessions using two different interfaces, [CreateSession](https://github.com/microsoft/onnxruntime/blob/main/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L1120) and [CreateSessionFromArray](https://github.com/microsoft/onnxruntime/blob/main/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L1123) , it was found that using **CreateSessionFromArray** results in an increase in peak working set memory by an amount equivalent to the size of the model.

### To reproduce

1. Use  [CreateSession](https://github.com/microsoft/onnxruntime/blob/main/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L1120) API to create a session with CPU EP.
2. Use [CreateSessionFromArray](https://github.com/microsoft/onnxruntime/blob/main/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L1123) API to create a session with CPU EP.
3. Monitor and compare the peak working set memory usage during the creation of each session.

Here is  test code :  
```
#include <filesystem>
#include <fstream>
#include <iostream>
#include <onnxruntime_cxx_api.h>
#include <sstream>
#include <vector>

#ifdef _WIN32
#  include <Windows.h>
#  include <psapi.h>
size_t GetPeakWorkingSetSize() {
  PROCESS_MEMORY_COUNTERS pmc;
  if (GetProcessMemoryInfo(GetCurrentProcess(), &pmc, sizeof(pmc))) {
    return pmc.PeakWorkingSetSize;
  }
  return 0;
}
#else
size_t GetPeakWorkingSetSize() { return 0; } // todo
#endif

std::vector<uint8_t> ReadBinaryFile(const std::string& file_path) {
  std::ifstream file(file_path, std::ios::binary | std::ios::ate);
  std::streamsize size = file.tellg();
  file.seekg(0, std::ios::beg);

  std::vector<uint8_t> buffer(size);
  if (file.read(reinterpret_cast<char*>(buffer.data()), size)) {
    return buffer;
  } else {
    throw std::runtime_error("Failed to read model file");
  }
}

int main(int argc, char* argv[]) {
  auto model_name = std::string(argv[1]);
  auto mode = std::stoi(argv[2]);

  auto model_path = std::filesystem::path(model_name);

  Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test_ort_mem");
  auto session_options = Ort::SessionOptions();
  std::unique_ptr<Ort::Session> p_session = nullptr;
  if (mode == 1) { // file base mode
#if _WIN32
    p_session = std::make_unique<Ort::Session>(env, model_path.wstring().data(),
                                               session_options);
#else
    p_session = std::make_unique<Ort::Session>(
        env, model_path.u8string().data(), session_options);
#endif
  } else if (mode == 2) { // in mem mode
    auto model_data = ReadBinaryFile(model_path.string());
    p_session = std::make_unique<Ort::Session>(
        env, model_data.data(), model_data.size(), session_options);
  }
  auto& session = *p_session;
  auto input_count = session.GetInputCount();
  std::cout << " input_count is " << input_count << " ";

  auto peak_working_set_size =
      (float)GetPeakWorkingSetSize() / 1024 / 1024; // MB
  if (mode == 1) {
    std::cout
        << "File base mode create ort session with CPU EP, peak working size : "
        << peak_working_set_size << "MB" << std::endl;
  } else if (mode == 2) {
    std::cout
        << "In-memory mode create ort session with CPU EP, peak working size : "
        << peak_working_set_size << "MB" << std::endl;
  }

  return 0;
}
```
The size of the test model is 835M， the results of testing using two interfaces ：
```
bin>ort_mem_test.exe .\test.onnx 1
 input_count is 3file base mode create ort session , peak working size : 1070MB

bin>ort_mem_test.exe .\test.onnx 2
 input_count is 3In-memory mode create ort session , peak working size : 1903.1MB
 ```

### Platform

Windows

### OS Version

Windows 11 Pro

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

8c5336449d2279c0394cc4a742d336d7f3bd4124

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

Default CPU

**Comment by skottmckay** [comment]
As expected. We have to parse the serialized protobuf data to create ORT Model model instance using ParseFromArray. If it's a file we can use ParseFromZeroCopyStream.

https://protobuf.dev/reference/cpp/api-docs/google.protobuf.message_lite/

If peak memory usage is an issue you can use and ORT format model (created from the ONNX model (see [here](https://onnxruntime.ai/docs/performance/model-optimizations/ort-format-models.html#convert-onnx-models-to-ort-format)), and set some session options as per [here](https://onnxruntime.ai/docs/performance/model-optimizations/ort-format-models.html#load-ort-format-model-from-an-in-memory-byte-array).

**Comment by mingyueliuh** [comment]
Thanks @skottmckay !

 I converted the ONNX to ORT format locally.  And run by ORT format model , The peak memory usage for `CreateSession` and `CreateSessionFromArray` is the same.  

But the peak working set is still higher than expected , closer to ' ONNX format + CreateSessionFromArray' rather than the lower value seen in 'ONNX format + CreateSession ' .
 
Here is my test results :
<img width="415" alt="image" src="https://github.com/user-attachments/assets/3a924b93-34ff-4bfa-8507-dbd181864c3d">



Test steps:
1. convert onnx to xrt format 
```
pip install onnx
pip install flatbuffers
python  <ort_source>/tools//tools/python/convert_onnx_models_to_ort.py test.onnx
```
![image](https://github.com/user-attachments/assets/c0635e5a-76a2-47c9-9e3b-964910e9def3)
Got two ORT format models :  **test.ort** (Fixed) and **test.with_runtime_opt.ort**(Runtime)

2.  set session options (load_mode_format and use_ort_model_bytes_directly)  
```
session_options.AddConfigEntry("session.load_model_format", "ORT");
session_options.AddConfigEntry("session.use_ort_model_bytes_directly", "1");
```
3.  Run '.ort' models
```
bin>ort_mem_test.exe ..\test\test.onnx 1 0
 input_count is 3 File base mode create ort session , load_model_format : 'ONNX'  peak working size : 1069.49MB
bin>ort_mem_test.exe ..\test\test.onnx 2 0
 input_count is 3 In-memory mode create ort session , load_model_format : 'ONNX' peak working size : 1908.43MB

bin>ort_mem_test.exe ..\test\test.ort 1 1
 input_count is 3 File base mode create ort session , load_model_format : 'ORT'  peak working size : 1867.05MB
bin>ort_mem_test.exe ..\test\test.ort 2 1
 input_count is 3 In-memory mode create ort session , load_model_format : 'ORT' peak working size : 1865.13MB
```
Running two ORT models resulted in the same peak working set.

**Comment by skottmckay** [comment]
Can you try setting `session.use_ort_model_bytes_for_initializers` to 1 as well?

**Comment by mingyueliuh** [comment]
Thanks  @skottmckay ， After setting the session option `use_ort_model_bytes_for_initializers `, the expected result was achieved.
