### ISSUE TITLE
How to dump the intermediate result of the onnxruntime operator operation?

### ISSUE THREAD

**Issue by maidouxiaozi** [microsoft/onnxruntime#2205]
**Is your feature request related to a problem? Please describe.**

**System information**
- ONNX Runtime version (you are using):

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by faxu** [comment]
See https://github.com/microsoft/onnxruntime/issues/1455 and related

**Comment by hariharans29** [comment]
Hi @maidouxiaozi - Please re-open the issue if #1455 and related don't help you. Others were able to resolve using the instructions there.

> How does Python call the underlying single operator of onnxruntime?

The Python APIs call into onnxruntime's internal C++ APIs. It calls the underlying operator corresponding to the node in the sequence of topologically sorted nodes in the model graph.
