### ISSUE TITLE
BitShift Not Implemented for uint8

### ISSUE THREAD

**Issue by lara-hdr** [microsoft/onnxruntime#2207]
ONNX BitShift https://github.com/onnx/onnx/blob/master/docs/Operators.md#BitShift only supports unsigned input types (uint64, uint32, uint16, uint8).
PyTorch only has one unsigned type : uint8, but BitShift is not implemented in ONNX Runtime for uint8 type.
Would it be possible to add uint8 support, in order to use the BitShift operator in the PyTorch exporter, without the use of a subgraph?

**Comment by pranavsharma** [comment]
@skottmckay
