### ISSUE TITLE
[Web] Rename WebNN EP MLOperandDescriptor's "dimensions" key to "shape"

### ISSUE THREAD

**Issue by huningxin** [microsoft/onnxruntime#22120]
### Describe the issue

Align with spec and Chromium implementation change: 

https://chromium-review.googlesource.com/c/chromium/src/+/5502631

https://github.com/webmachinelearning/webnn/pull/676

/cc @Honry @fdwr 

### To reproduce

See the spec PR

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

Latest

### Execution Provider

WebNN EP

**Comment by fdwr** [comment]
For now we can declare `MLOperandDescs` with *both* fields (shape is an alias of dimensions), so that we have some transitional overlap across Chromium versions without worrying about exactly matching. e.g.:

```
const someOperandDesc = {
    dataType: "float32",
    dimensions: listOfDimensions
    shape: listOfDimensions
}
```
