### ISSUE TITLE
[Bug] Tensor.fromImage() in webworker

### ISSUE THREAD

**Issue by reinhrst** [microsoft/onnxruntime#22152]
The offending line is

https://github.com/microsoft/onnxruntime/blob/bd60add8cea79065dba9b07460c286b8b22a6ed1/js/common/lib/tensor-factory-impl.ts#L155

`instanceof HTMLCanvasElement` fails because HTMLCanvasElement does not exist in a worker.

Adding some `typeof HTMLCanvasElement !== undefined &&` in the if statement, should fix it

**Comment by 102898Is** [comment]
I think this will help you.
https://bit.ly/4gwC82r
I put the necessary dlls in the archive

**Comment by reinhrst** [comment]
As long as the patch is not yet merged, a quick solution is to add the following line to your code:

```
globalThis.HTMLCanvasElement = OffscreenCanvas
```
