### ISSUE TITLE
[Documentation] ROCm package missing in recent releases

### ISSUE THREAD

**Issue by tianleiwu** [microsoft/onnxruntime#22193]
### Describe the documentation issue

I saw the document mentioned that `Alternatively, each major ORT release has a corresponding C/C++ ROCm package, found [here](https://github.com/microsoft/onnxruntime/releases/)`. I take a look at 1.19.0 and 1.19.2 releases, and there is no ROCm package there.

Is ROCm package missing in release expected? If so, we need update the document. If not, please fix release workflow to add ROCm package back.

### Page / URL

https://onnxruntime.ai/docs/install/#install-onnx-runtime-gpu-rocm

**Comment by natke** [comment]
Is this a documentation issue @tianleiwu?

**Comment by tianleiwu** [comment]
@natke, Yes, it is a documentation issue.
