### ISSUE TITLE
[Mobile] Use ONNX Runtime to deploy YOLO-v8 pose estimation  on Android Studio

### ISSUE THREAD

**Issue by zhanxuejie** [microsoft/onnxruntime#22216]
### Describe the issue

I would like to use ONNX Runtime to deploy YOLO-v8 pose estimation  on Android Studio. Are there any relevant examples available? Thanks very much!

### To reproduce

I haven't managed to run it successfully.

### Platform

Android

### OS Version

7.3.1

### ONNX Runtime Installation

Built from Source

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

v1.19.2

### ONNX Runtime API

Java/Kotlin

### Architecture

X64

### Execution Provider

Other / Unknown

**Comment by skottmckay** [comment]
https://onnxruntime.ai/docs/tutorials/mobile/pose-detection.html
