### ISSUE TITLE
[WebNN EP] Support reshape and expand with 0d input and 0d output

### ISSUE THREAD

**Issue by mingmingtasd** [microsoft/onnxruntime#22215]
### Describe the issue

A scalar input to a scalar output should be valid nop for reshape and expand.

### To reproduce

Run onnx model with reshape or expand, the input and output are both 0d scalar on WebNN EP.

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

a47254eaef87a4572078d3165f4b9d1c4b4c52b1

### Execution Provider

Other / Unknown

**Comment by mingmingtasd** [comment]
@fdwr @honry

**Comment by fdwr** [comment]
Related Chromium issue: https://issues.chromium.org/issues/369432531
