### ISSUE TITLE
[Feature Request] Detect TensorRT cache creation

### ISSUE THREAD

**Issue by henryruhs** [microsoft/onnxruntime#22244]
### Describe the feature request

We have the problem that creating the `.engine` and `.profile` files for TensorRT take too much time and there is no feedback for the user what is actual happening.

Therefore I suggest adding a general "get_state" to `onnxruntime.InferenceSession` in order to figure out why it is currently blocked. Like is_processing, is_caching etc.

I would be happy with any other solution to detect the "cache creation" for now

### Describe scenario use case

Give the user better feedback while creating caches for TensorRT.

**Comment by henryruhs** [comment]
There seems to be no logic to invalidate cache, I experience exceptions after updating the version of TensorRT.

**Comment by chilo-ms** [comment]
Thanks for the feedback.

TRT does require amount of time when building the engine if the model is complex.
You can enable TRT EP's provider option `trt_detailed_build_log` which gives you more verbose logging and it keeps printing out information when TRT is doing kernels profiling/selection for building the engine.

Caching/serialize the engine is quick and same as deserializing the engine cache. So, as long as there is a corresponding engine file on the disk, TRT EP will deserialize the engine without rebuilding it, only if the input shape changes.

**Comment by henryruhs** [comment]
Okay, it sounds like there is not too much you can do about both topics. I give `trt_detailed_build_log` a shot and close this issue in meanwhile. Thanks
