### ISSUE TITLE
[Feature Request] Add support for building the iOS simulator arm64 version

### ISSUE THREAD

**Issue by cyanic-selkie** [microsoft/onnxruntime#22257]
### Describe the feature request

Currently, the build script only supports the x86_64 architecture for the iOS simulator. Since the M series Macbooks are arm64, this doesn't work.

### Describe scenario use case

Adding this would make development on an M series Macbook easier and more straightforward.

**Comment by cyanic-selkie** [comment]
My apologies, apparently this is already supported. This should've been a bug report.

The issue I was facing was the fact that building for the simulator after building for the iOS target without deleting the build directory first (or vice versa), it would try to link to the wrong dylib (built for the other target).

**Comment by skottmckay** [comment]
Depending on how the cmake files are written some values may be 'sticky' across builds (e.g. we set a value inside a branch but don't have a matching branch that unsets it). If you're changing a significant aspect of the build it's generally better to use a clean build directory.
