### ISSUE TITLE
1.19.2 Support for CUDA 12.6 and CUDNN 9.4

### ISSUE THREAD

**Issue by K4HVH** [microsoft/onnxruntime#22276]
### Describe the issue

Hello all, 

I'm currently having issues getting CUDA 12.6 (Update 1) and CUDNN 9.4.0 to load. I'm getting crashes on a `sessionOptions.AppendExecutionProvider_CUDA(cudaOption);` call. Are these latest versions of CUDA and CUDNN supported, I have previously used 1.18 with CUDA 11 and it worked a charm, only since attempting to upgrade to 1.19.2 am I getting these issues.

'focus.exe' (Win32): Loaded 'C:\Users\brone\Documents\Programming\Focus\focus-cpp\x64\Debug\onnxruntime_providers_shared.dll'. 
'focus.exe' (Win32): Loaded 'C:\Users\brone\Documents\Programming\Focus\focus-cpp\x64\Debug\onnxruntime_providers_cuda.dll'. 
'focus.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin\cublas64_12.dll'. Module was built without symbols.
'focus.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin\cufft64_11.dll'. Module was built without symbols.
'focus.exe' (Win32): Loaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin\cublasLt64_12.dll'. Module was built without symbols.
'focus.exe' (Win32): Unloaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin\cublasLt64_12.dll'
'focus.exe' (Win32): Unloaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin\cublas64_12.dll'
'focus.exe' (Win32): Unloaded 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\bin\cufft64_11.dll'
'focus.exe' (Win32): Unloaded 'C:\Users\brone\Documents\Programming\Focus\focus-cpp\x64\Debug\onnxruntime_providers_cuda.dll'
Exception thrown at 0x00007FFCC7B0FABC in focus.exe: Microsoft C++ exception: onnxruntime::OnnxRuntimeException at memory location 0x000000C99B31DD20.
Exception thrown at 0x00007FFCC7B0FABC in focus.exe: Microsoft C++ exception: [rethrow] at memory location 0x0000000000000000.
Exception thrown at 0x00007FFCC7B0FABC in focus.exe: Microsoft C++ exception: onnxruntime::OnnxRuntimeException at memory location 0x000000C99B31DD20.
Exception thrown at 0x00007FFCC7B0FABC in focus.exe: Microsoft C++ exception: Ort::Exception at memory location 0x000000C99B31DEA0.
Debug Error!

Above is part of the debug log, it seems to be loading 12.6 fine. I can provide a full log if needed

### To reproduce

You can use my ONNXRuntime YOLO inferencer library to test ([https://github.com/K4HVH/YOLOv8-ONNXRuntime-CPP](https://github.com/K4HVH/YOLOv8-ONNXRuntime-CPP))

Install the latest CUDA and CUDNN from [https://developer.nvidia.com/](https://developer.nvidia.com/cudnn-downloads)

Compile against ONNXRuntime 1.19.2 libs

Program crashes when attempting to switch to CUDA execution provider

### Platform

Windows

### OS Version

Windows 11 Pro - 10.0.22631 Build 22631

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.19.2

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

CUDA

### Execution Provider Library Version

CUDA 12.6 - CUDNN 9.4

**Comment by tianleiwu** [comment]
@K4HVH, I tried to build [YOLOv8-ONNXRuntime-CPP](https://github.com/K4HVH/YOLOv8-ONNXRuntime-CPP)), but failed since opencv not found in my machine. What's the steps to add OpenCV?

**Comment by K4HVH** [comment]
> @K4HVH, I tried to build [YOLOv8-ONNXRuntime-CPP](https://github.com/K4HVH/YOLOv8-ONNXRuntime-CPP)), but failed since opencv not found in my machine. What's the steps to add OpenCV? 

Hi, I'm so sorry, I meant to update this thread last night haha

The issue lies in the fact that the next CUDNN installer (Official from Nvidia) doesn't actually install CUDNN to the CUDA folder. It instead installs it elsewhere and encourages the use of an Environmental variable to access the libs ect.

Here are the steps to fix it:

1. Download and Install NVIDIA's CUDA 12 Drivers 
2. Download and Install NVIDIA's CUDNN 9 Drivers *(Make sure to have CUDA installed first)*

***IMPORTANT***
After installing CUDNN, You must manually copy over the files into your CUDA Install

3. Navigate to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA` and select the latest version of CUDA (For example, `v12.6`) This is your "CUDA Folder"
4. In a seperate file explorer window, navigate to `C:\Program Files\NVIDIA\CUDNN` and select the latest version of CUDNN (For example, `v9.4`) This is your "CUDNN Folder"
5. Copy the contents of the `"CUDNN Folder"\bin\"CUDA Version"` -> `"CUDA Folder"\bin`
6. Copy the contents of the `"CUDNN Folder"\include\"CUDA Version"` -> `"CUDA Folder"\include`
7. Copy the contents of the `"CUDNN Folder"\lib\"CUDA Version"\x64` -> `"CUDA Folder"\lib\x64`
(https://i.imgur.com/uKs3mHa.png)
