### ISSUE TITLE
[Feature Request] Confirm build against Ubuntu 24.04 and CUDA 12.6

### ISSUE THREAD

**Issue by mc-nv** [microsoft/onnxruntime#22335]
### Describe the feature request

Could you please validate build against Ubuntu 24.04 and CUDA 12.6. 
Create patch release if needed to include: https://github.com/microsoft/onnxruntime/pull/22316

### Describe scenario use case

Compile product with Ubuntu 24.04. 
Include changes: https://github.com/microsoft/onnxruntime/pull/22316

> [!NOTE] 
> Target date is November 10th

**Comment by mc-nv** [comment]
cc: @pranavsharma , @snnn

**Comment by tianleiwu** [comment]
In Azure Linux, the build of main branch is good with cuda 12.6.2 and cudnn 9.4.0.58.

@snnn, do you have ubuntu 24.04 to verify the build?

**Comment by snnn** [comment]
Ubuntu is not free. For example, python3-pip is a commonly used package in Ubuntu. But it is not in Ubuntu's base repo. It is in universe, which means Ubuntu charges money for anyone who wants to get security update for such packages.  I don't have this budget.

**Comment by tianleiwu** [comment]
@mc-nv, you can try the docker file in https://github.com/microsoft/onnxruntime/pull/22339.
It is working well in my test.

**Comment by tianleiwu** [comment]
Please follow https://github.com/microsoft/onnxruntime/blob/main/dockerfiles/README.md#cuda
