### ISSUE TITLE
QNN Execution Provider - Failed to finalize QNN graph. at location qnn_model.cc:152 FinalizeGraphs

### ISSUE THREAD

**Issue by john-dance** [microsoft/onnxruntime#22369]
### Describe the issue

Various models result in the error:
Failed to finalize QNN graph. at location qnn_model.cc:152 FinalizeGraphs 

### To reproduce

The following AI Hub jobs results in Failed to finalized. (Note that these jobs are only visible to members of the QNN Execution Provider team) 

In some cases, the log includes more details.

https://app.aihub.qualcomm.com/jobs/j1p8vz6x5/ - line 152
https://app.aihub.qualcomm.com/jobs/joprm4l9g - line 181

https://app.aihub.qualcomm.com/jobs/jnp1moe8p - line 181
[onnxruntime] Pad node `/activation_post/downsample/lowpass/Pad` is not supported: base_op_builder.cc:162 ProcessOutputs Failed to add node.
[onnxruntime] Failed to finalize QNN graph. at location qnn_model.cc:181 FinalizeGraphs 

### Platform

Android

### OS Version

12-14

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.19.2

### ONNX Runtime API

C++

### Architecture

ARM64

### Execution Provider

Other / Unknown

### Execution Provider Library Version

QNN 2.26

**Comment by john-dance** [comment]
The first example now succeeds with QNN 2.27, but the second example still fails.

**Comment by HectorSVC** [comment]
For the QNN graph finalize error, it's something wrong with QNN. Need to create case to QNN team to ask them to investigate more on this.

**Comment by john-dance** [comment]
Will follow up with QNN.
