### ISSUE TITLE
[Build]how to obtain python wheel package from pre-build files?

### ISSUE THREAD

**Issue by joey9503** [microsoft/onnxruntime#22399]
### Describe the issue

I want to obtain a Python wheel that supports CentOS 7 and glibc 2.17. I have already downloaded the pre-built files from the link https://github.com/csukuangfj/onnxruntime-libs/releases. What should I do next?

my glibc version:
$ ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### Urgency

Urgent

### Target platform

centos7

### Build script

none

### Error / output

none

**Comment by snnn** [comment]
It's not our package.

**Comment by snnn** [comment]
Please consider contacting the author directly.
