### ISSUE TITLE
[Build] how to build onnxruntime==1.18.1 from source on an offline machine?

### ISSUE THREAD

**Issue by joey9503** [microsoft/onnxruntime#22402]
### Describe the issue

when i build from source, it requires downloading 3rd party dependencies, but my machine is offline, what can i do?
 i checked this link: https://github.com/microsoft/onnxruntime/issues/14117
but i run the command failed:
fatal: not a git repository (or any of the parent directories): .git

### Urgency

Urgent

### Target platform

centos7

### Build script

./build.sh --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --allow_running_as_root --build_wheel

### Error / output

fatal: not a git repository (or any of the parent directories): .git

**Comment by joey9503** [comment]
i ran this command to checkout to v1.18.1:
```shell
git clone --branch v1.18.1 --single-branch https://github.com/microsoft/onnxruntime.git
```

and then i ran these 2 commands:
```shell
git submodule sync --recursive
git submodule update --init --recursive
```

then i copied the whole directory to my offline machine, ran this build command:
```shell
./build.sh --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --allow_running_as_root --build_wheel
```

but it still need to download 3rd dependency:
```shell
[ 22%] Performing download step (download, verify and extract) for 'abseil_cpp-populate'
-- Downloading...
   dst='/root/onnxruntime/build/Linux/RelWithDebInfo/_deps/abseil_cpp-subbuild/abseil_cpp-populate-prefix/src/20240116.0.zip'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/abseil/abseil-cpp/archive/refs/tags/20240116.0.zip'
-- Retrying...
```

what should i do?

**Comment by joey9503** [comment]
> i ran this command to checkout to v1.18.1:
> 
> git clone --branch v1.18.1 --single-branch https://github.com/microsoft/onnxruntime.git
> and then i ran these 2 commands:
> 
> git submodule sync --recursive
> git submodule update --init --recursive
> then i copied the whole directory to my offline machine, ran this build command:
> 
> ./build.sh --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --allow_running_as_root --build_wheel
> but it still need to download 3rd dependency:
> 
> [ 22%] Performing download step (download, verify and extract) for 'abseil_cpp-populate'
> -- Downloading...
>    dst='/root/onnxruntime/build/Linux/RelWithDebInfo/_deps/abseil_cpp-subbuild/abseil_cpp-populate-prefix/src/20240116.0.zip'
>    timeout='none'
>    inactivity timeout='none'
> -- Using src='https://github.com/abseil/abseil-cpp/archive/refs/tags/20240116.0.zip'
> -- Retrying...
> what should i do?

after check this issue https://github.com/microsoft/onnxruntime/discussions/16071, i downloaded all the files, and i can process to build.
but i ran into another question:
```shell
/tmp/ccQYl4qP.s: Assembler messages:
/tmp/ccQYl4qP.s:15797: Error: no such instruction: `vpdpbusd %ymm2,%ymm15,%ymm17'
/tmp/ccQYl4qP.s:15870: Error: no such instruction: `vpdpbusd %ymm1,%ymm2,%ymm15'
/tmp/ccQYl4qP.s:15923: Error: no such instruction: `vpdpbusd %ymm0,%ymm1,%ymm15'
/tmp/ccQYl4qP.s:15983: Error: no such instruction: `vpdpbusd %ymm0,%ymm3,%ymm5'
/tmp/ccQYl4qP.s:16850: Error: no such instruction: `vpdpbusd %ymm0,%ymm2,%ymm4'
/tmp/ccQYl4qP.s:17852: Error: no such instruction: `vpdpbusd %ymm2,%ymm18,%ymm12'
```

Does anyone knows how to slove this problem?

**Comment by snnn** [comment]
Your GCC toolchain is too old.

**Comment by snnn** [comment]
Try GCC 11.
