### ISSUE TITLE
[Documentation] WCAG AA standards not met for all docs pages

### ISSUE THREAD

**Issue by MaanavD** [microsoft/onnxruntime#22453]
### Describe the documentation issue

https://webcompliance.trafficmanager.net/ScanResultsApi/GetAccessibilityScanConsolidatedReport?siteId=ee4cf6e9-d133-44ac-08df-08dc29611169

^According to this dashboard, almost all our docs pages have accessibility issues related to code snippets and other sections. WIP, self-assigned. 

### Page / URL

https://onnxruntime.ai/docs

**Comment by natke** [comment]
@MaanavD we can look at upgrading or changing the theme

**Comment by MaanavD** [comment]
@natke Yeah that's the plan, just writing it here as slated work :)

**Comment by natke** [comment]
Nice!
