### ISSUE TITLE
[Build] onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "

### ISSUE THREAD

**Issue by wydxry** [microsoft/onnxruntime#22491]
### Describe the issue

```C++
    try {
        session_options.AppendExecutionProvider_CUDA(cuda_option);
    }
    catch (const std::exception& e) {
        std::cout << e.what() << std::endl;
    }
```

D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\WINDOWS\SYSTEM32\onnxruntime_providers_cuda.dll" 

after copy xxx.dll to the path system32, it stil has this problem...

### Target platform

Win11 

### Build script

```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|Win32">
      <Configuration>Debug</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Win32">
      <Configuration>Release</Configuration>
      <Platform>Win32</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|x64">
      <Configuration>Debug</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|x64">
      <Configuration>Release</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <VCProjectVersion>17.0</VCProjectVersion>
    <Keyword>Win32Proj</Keyword>
    <ProjectGuid>{21860e31-cdd1-4351-be79-ff2f63587086}</ProjectGuid>
    <RootNamespace>ConsoleApplication2</RootNamespace>
    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
    <PlatformToolset>v143</PlatformToolset>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseDebugLibraries>false</UseDebugLibraries>
    <PlatformToolset>v143</PlatformToolset>
    <WholeProgramOptimization>true</WholeProgramOptimization>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseDebugLibraries>true</UseDebugLibraries>
    <PlatformToolset>v143</PlatformToolset>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseDebugLibraries>false</UseDebugLibraries>
    <PlatformToolset>v143</PlatformToolset>
    <WholeProgramOptimization>true</WholeProgramOptimization>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings">
  </ImportGroup>
  <ImportGroup Label="Shared">
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <Import Project="$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <SDLCheck>true</SDLCheck>
      <PreprocessorDefinitions>WIN32;_DEBUG;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ConformanceMode>true</ConformanceMode>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
      <GenerateDebugInformation>true</GenerateDebugInformation>
    </Link>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <FunctionLevelLinking>true</FunctionLevelLinking>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <SDLCheck>true</SDLCheck>
      <PreprocessorDefinitions>WIN32;NDEBUG;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ConformanceMode>true</ConformanceMode>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
      <EnableCOMDATFolding>true</EnableCOMDATFolding>
      <OptimizeReferences>true</OptimizeReferences>
      <GenerateDebugInformation>true</GenerateDebugInformation>
    </Link>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <SDLCheck>true</SDLCheck>
      <PreprocessorDefinitions>_DEBUG;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ConformanceMode>true</ConformanceMode>
      <AdditionalIncludeDirectories>C:\Users\zeng%27li\Downloads\cudnn-windows-x86_64-8.9.7.29_cuda12-archive\cudnn-windows-x86_64-8.9.7.29_cuda12-archive\include;C:\Users\zeng%27li\Downloads\TensorRT-10.5.0.18.Windows.win10.cuda-12.6\TensorRT-10.5.0.18\include;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <AdditionalLibraryDirectories>C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\lib\x64;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\lib;C:\Users\zeng%27li\Downloads\TensorRT-10.5.0.18.Windows.win10.cuda-12.6\TensorRT-10.5.0.18\lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>C:\Users\zeng'li\Downloads\TensorRT-10.5.0.18.Windows.win10.cuda-12.6\TensorRT-10.5.0.18\lib\*.lib;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\lib\x64\*.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <FunctionLevelLinking>true</FunctionLevelLinking>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <SDLCheck>true</SDLCheck>
      <PreprocessorDefinitions>NDEBUG;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ConformanceMode>true</ConformanceMode>
      <AdditionalIncludeDirectories>C:\Users\zeng%27li\Downloads\onnxruntime-win-x64-gpu-1.19.2\onnxruntime-win-x64-gpu-1.19.2\include;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\include;C:\Users\zeng'li\Downloads\cudnn-windows-x86_64-8.9.7.29_cuda12-archive\cudnn-windows-x86_64-8.9.7.29_cuda12-archive\include;C:\Users\zeng%27li\Downloads\TensorRT-10.5.0.18.Windows.win10.cuda-12.6\TensorRT-10.5.0.18\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
      <EnableCOMDATFolding>true</EnableCOMDATFolding>
      <OptimizeReferences>true</OptimizeReferences>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <AdditionalLibraryDirectories>C:\Users\zeng%27li\Downloads\onnxruntime-win-x64-gpu-1.19.2\onnxruntime-win-x64-gpu-1.19.2\lib;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.6\lib\x64;C:\Users\zeng%27li\Downloads\TensorRT-10.5.0.18.Windows.win10.cuda-12.6\TensorRT-10.5.0.18\lib;C:\Users\zeng%27li\Downloads\cudnn-windows-x86_64-8.9.7.29_cuda12-archive\cudnn-windows-x86_64-8.9.7.29_cuda12-archive\lib\x64;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>nvinfer_10.lib;nvinfer_plugin_10.lib;nvonnxparser_10.lib;onnxruntime.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="ConsoleApplication2.cpp" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
  </ImportGroup>
</Project>
```

### Error / output

D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1637 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\WINDOWS\SYSTEM32\onnxruntime_providers_cuda.dll"

### Visual Studio Version

2022

### GCC / Compiler Version

onnxruntime-win-x64-gpu-1.19.2

**Comment by wydxry** [comment]
it works after change version 1.18.0 from 1.19.x, cause my cuDnn is 8.9.7.

**Comment by petercham** [comment]
> it works after change version 1.18.0 from 1.19.x, cause my cuDnn is 8.9.7.

HJH Check Python Ver.3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
HJH Check CUDA Ver.12.1
HJH Check Torch Ver.2.3.1+cu121
HJH Check cuDNN Ver. 8907
HJH Check ONNXRuntime Ver. 1.19.2

2024-10-26 20:47:00.5657450 [E:onnxruntime:Default, [provider_bridge_ort.cc:1992](http://provider_bridge_ort.cc:1992/) onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\[provider_bridge_ort.cc:1637](http://provider_bridge_ort.cc:1637/) onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

I'm having the same problem.Have you solved it?

**Comment by wydxry** [comment]
> > it works after change version 1.18.0 from 1.19.x, cause my cuDnn is 8.9.7.
> 
> HJH Check Python Ver.3.11.8 (tags/v3.11.8:db85d51, Feb 6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)] HJH Check CUDA Ver.12.1 HJH Check Torch Ver.2.3.1+cu121 HJH Check cuDNN Ver. 8907 HJH Check ONNXRuntime Ver. 1.19.2
> 
> 2024-10-26 20:47:00.5657450 [E:onnxruntime:Default, [provider_bridge_ort.cc:1992](http://provider_bridge_ort.cc:1992/) onnxruntime::TryGetProviderInfo_CUDA] D:\a_work\1\s\onnxruntime\core\session[provider_bridge_ort.cc:1637](http://provider_bridge_ort.cc:1637/) onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"
> 
> I'm having the same problem.Have you solved it?

yes i solved it. You can check in some ways: 1.Are the related libraries compatible? 2.Have the environments of the related libraries been added to the system environment variables? 3.The lib and dll files of the related libraries (xxx.lib xxx.dll) can be copied to the CUDA directory.

**Comment by fhqmwy** [comment]
> > > it works after change version 1.18.0 from 1.19.x, cause my cuDnn is 8.9.7.
> > 
> > 
> > HJH Check Python Ver.3.11.8 (tags/v3.11.8:db85d51, Feb 6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)] HJH Check CUDA Ver.12.1 HJH Check Torch Ver.2.3.1+cu121 HJH Check cuDNN Ver. 8907 HJH Check ONNXRuntime Ver. 1.19.2
> > 2024-10-26 20:47:00.5657450 [E:onnxruntime:Default, [provider_bridge_ort.cc:1992](http://provider_bridge_ort.cc:1992/) onnxruntime::TryGetProviderInfo_CUDA] D:\a_work\1\s\onnxruntime\core\session[provider_bridge_ort.cc:1637](http://provider_bridge_ort.cc:1637/) onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"
> > I'm having the same problem.Have you solved it?
> 
> yes i solved it. You can check in some ways: 1.Are the related libraries compatible? 2.Have the environments of the related libraries been added to the system environment variables? 3.The lib and dll files of the related libraries (xxx.lib xxx.dll) can be copied to the CUDA directory.
> 
> This is my lib's version: Windows 11 GPU 4090 CUDA 12.6 cuDnn 8.9.7.29 TensorRT 10.5.0.18 PyTorch 2.4.1 Python 3.10 onnx 1.17.0 onnxruntime-gpu 1.19.2 (Python) onnxruntime-gpu 1.18.0 (C++)

I changed it to 1.18.0 and still got the same error

**Comment by fhqmwy** [comment]
> > > > it works after change version 1.18.0 from 1.19.x, cause my cuDnn is 8.9.7.
> > > 
> > > 
> > > HJH Check Python Ver.3.11.8 (tags/v3.11.8:db85d51, Feb 6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)] HJH Check CUDA Ver.12.1 HJH Check Torch Ver.2.3.1+cu121 HJH Check cuDNN Ver. 8907 HJH Check ONNXRuntime Ver. 1.19.2
> > > 2024-10-26 20:47:00.5657450 [E:onnxruntime:Default, [provider_bridge_ort.cc:1992](http://provider_bridge_ort.cc:1992/) onnxruntime::TryGetProviderInfo_CUDA] D:\a_work\1\s\onnxruntime\core\session[provider_bridge_ort.cc:1637](http://provider_bridge_ort.cc:1637/) onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Work\SD-ComfyUI\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"
> > > I'm having the same problem.Have you solved it?
> > 
> > 
> > yes i solved it. You can check in some ways: 1.Are the related libraries compatible? 2.Have the environments of the related libraries been added to the system environment variables? 3.The lib and dll files of the related libraries (xxx.lib xxx.dll) can be copied to the CUDA directory.
> > This is my lib's version: Windows 11 GPU 4090 CUDA 12.6 cuDnn 8.9.7.29 TensorRT 10.5.0.18 PyTorch 2.4.1 Python 3.10 onnx 1.17.0 onnxruntime-gpu 1.19.2 (Python) onnxruntime-gpu 1.18.0 (C++)
> 
> I changed it to 1.18.0 and still got the same error

GPU 4070s
cuda 12.4
cudnn 8.9.7
onnxruntime-gpu-1.18.0
