### ISSUE TITLE
[C++ API] How to do onnxruntime inference with multi input?

### ISSUE THREAD

**Issue by kai06046** [microsoft/onnxruntime#2250]
I saw an example in c# [here](https://github.com/microsoft/onnxruntime/blob/master/docs/CSharp_API.md), but cannot find an example that shows how to do this in c++. Can anyone kindly provide some advice?

**Comment by hariharans29** [comment]
Could you take a look at the following and close the issue if it helps ?

https://github.com/microsoft/onnxruntime/issues/1323 https://github.com/microsoft/onnxruntime/issues/2143

Thanks.

**Comment by hariharans29** [comment]
Closing as this is a duplicated issue. Please use the answers in the referenced issues above. Re-open this issue if it doesn't help you.

**Comment by kai06046** [comment]
I actually got 2 input nodes that have bool and float type.
```
Number of inputs = 2
Input 0 : name=flag:0
Input 0 : type=9
Input 0 : num_dims=0
Input 1 : name=images:0
Input 1 : type=1
Input 1 : num_dims=4
Input 1 : dim 0=-1
Input 1 : dim 1=120
Input 1 : dim 2=120
Input 1 : dim 3=3
```
Refer to this [comment](https://github.com/microsoft/onnxruntime/issues/1323#issuecomment-530350620), I was able to create input tensors with multi input and different types, below is the related code:
```
bool* input_bool_tensor_values = {false};
Ort::Value input_bool = Ort::Value::CreateTensor<bool>(memory_info, input_bool_tensor_values, 1, input_1_node_dims.data(), 0);
Ort::Value input_tensor = Ort::Value::CreateTensor<float>(memory_info, input_tensor_values.data(), input_tensor_values.size(), input_node_dims.data(), 4);
Ort::Value* input_tensors[2];
input_tensors[0] = &input_bool;
input_tensors[1] = &input_tensor;

auto output_tensors = session.Run(Ort::RunOptions{nullptr},
   input_node_names.data(), 
  // (const Ort::Value*)&input_tensors, 
   &input_tensors, 
   2, 
   output_node_names.data(),
   1);

```
An error `C2664: 'void Ort::Ses
sion::Run(const Ort::RunOptions &,const char *const *,const Ort::Value *,size_t,const char *const *,Ort::Value *,size_t
)': cannot convert argument 3 from 'Ort::Value *(*)[2]' to 'const Ort::Value *'` came out, I am not very familiar with C++, any advice?

**Comment by kai06046** [comment]
I also tried `Ort::Value *input_tensors = new(Ort::Value) * 2;` but got this error `C2512: 'Ort::Value':
no appropriate default constructor available`.

**Comment by kai06046** [comment]
Found this [example](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_inference.cc#L405) and it work.

**Comment by suman-v** [comment]
https://github.com/microsoft/onnxruntime-inference-examples/issues/139

**Comment by jie-chen** [comment]
> Found this [example](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_inference.cc#L405) and it work.

It seems this is the only correct one update to today. Is there a formal documentation to explain this further?

**Comment by TAIBIAchraf** [comment]
You can create an object std::vector<Ort::Value> inputs, then using std::move(t1),std::move(t2) ... etc move all Ort::Value tensors t1, t2 ... that you have into it . 
Then you call:
std::vector<Ort::Value> outputs= session.Run(
    Ort::RunOptions{nullptr},
    input_names,
    inputs.data(),
    inputs.size(),
    output_name,
    1
);
