### ISSUE TITLE
[Build] can't build it version 1.19.2 on android arm64

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/onnxruntime#22500]
### Describe the issue

build error with unknown type name 'bfloat16_t'

### Target platform

android arm64

### Build script

.\build.bat --config RelWithDebInfo --android --skip_tests --android_sdk_path "C:\Users\dell\AppData\Local\Android\Sdk" --android_ndk_path "C:\Users\dell\AppData\Local\Android\Sdk\ndk\25.2.9519653" --android_abi arm64-v8a --android_api 27 --cmake_generator Ninja --use_nnapi

### Error / output

[onnxruntime_android_arm64_build.zip](https://github.com/user-attachments/files/17431666/onnxruntime_android_arm64_build.zip)

**Comment by skottmckay** [comment]
If you search for the error you'll see a number of issues where the recommendation is to use a newer NDK version to fix it.
