### ISSUE TITLE
CPU provider uses 0 as default when Clip operator doesn't have max field set

### ISSUE THREAD

**Issue by indygit** [microsoft/onnxruntime#22585]
### Describe the issue

Per ONNX spec, when Clip operator doesn't have max field set, maximal value of operator's data type should be used as default.

Because of this issue, when CPU provider runs Clip operator, it outputs 0 and subsequently causes inference error.

### To reproduce

I hit this problem when running Stable Diffusion 1.5 Safety Checker on GPU through DirectML provider.
For this case, CPU provider is used in constant folding.

For Safety Checker, Clip's output is the divisor of Elementwise Divide, so divide by zero error happens.

I attached the SD 1.5 WebNN demo's Safety Checker, but this issue should repro with any model with Clip operator that doesn't set max field.

![Image](https://github.com/user-attachments/assets/6190940d-371d-4d32-b914-316fef1e2511)

You can find the Safety Checker model at: https://huggingface.co/microsoft/stable-diffusion-v1.5-webnn/blob/main/safety_checker_int32_reduceSum.onnx

It is better to use a simpler model for repro. Also we will update the model to work around this issue until a fix in ORT becomes available.

### Urgency

This issue affects all models with Clip operator that doesn't set max field when running on CPU provider.

### Platform

Windows

### OS Version

26100

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.20

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

Default CPU

**Comment by fdwr** [comment]
Is this fixed in ORT 1.20, per https://github.com/microsoft/onnxruntime/issues/21957?

**Comment by indygit** [comment]
Sorry I was testing 1.19.2. With 1.20, this issue is fixed (for the native ORT).

This is a dup of [21957](https://github.com/microsoft/onnxruntime/issues/21957)
