### ISSUE TITLE
[Web/JSEP] Update operator registrations for latest onnx opset

### ISSUE THREAD

**Issue by prathikr** [microsoft/onnxruntime#22592]
### Describe the issue

JSEP Ops that need updating

- [ ] Cast
- [ ] ReduceMax
- [ ] ReduceMin
- [ ] Squeeze
- [ ] Unsqueeze
- [ ] Transpose
- [ ] AveragePool
- [ ] Flatten
- [ ] Pad
- [ ] If 

### To reproduce

n/a

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.19.2

### Execution Provider

'webgpu' (WebGPU)

**Comment by fs-eire** [comment]
References:
- scripts that generates the diff: #21989 
- the diff results: https://github.com/microsoft/onnxruntime/pull/21871#issuecomment-2313124737
