### ISSUE TITLE
0.5.1 fails to build: error: package directory 'onnxruntime/backend' does not exist

### ISSUE THREAD

**Issue by yurivict** [microsoft/onnxruntime#2263]
python-3.6
distutils
FreeBSD 12

**Comment by snnn** [comment]
Could you please provide more information? How did you build it?

**Comment by yurivict** [comment]
I build it in the FreeBSD ports framework, in an attempt to create the FreeBSD port.
The framework calls setup.py to configure and build it.

**Comment by snnn** [comment]
It won't work. Try the following please
https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#linux

**Comment by snnn** [comment]
Hi @yurivict 

Thanks you for helping us put onnxruntime into FreeBSD ports tree. As a long time FreeBSD user(From 4.x), I'm looking forward to seeing it. 

To build onnxruntime python package, you need three steps:
1. Run cmake
2. Run make
3. Run setup.py in the build dir. 

The build.py script in tools/ci_build dir encapsulated them together, it's easier to use but less customizable. You may choose which way you want to go.
