### ISSUE TITLE
The repository is mislabeled: git describes the master branch as v0.1.4-1400-gc7599d07 while the releases page shows that the latest release is 0.5.1

### ISSUE THREAD

**Issue by yurivict** [microsoft/onnxruntime#2265]
git describe should return a tag after the last release.

**Comment by snnn** [comment]
Do you know how can I fix it?

**Comment by yurivict** [comment]
Make a release with the next version number from the master branch, and later only release from master.

**Comment by snnn** [comment]
But it's not our dev model. We always create a new release branch for each each. Similar to the ONNX project.
