### ISSUE TITLE
CUDA Dependency files

### ISSUE THREAD

**Issue by namtr92** [microsoft/onnxruntime#22668]
### Describe the issue

Hi, I want to package all these CUDA dependency files in to 1 installer so it easier for install, may I know the list of all file require to run ONNXRuntime in each library:
 - CUDA
 - CUDNN
 - TensorRT
I want to build in smallest size possible so I only need files that are require to run ONNXRuntime.

### To reproduce

N/A

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.19

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

CUDA

**Comment by tianleiwu** [comment]
To get a full list of DLLs, you can use Process Monitor to trace file system of your test application: https://learn.microsoft.com/en-us/sysinternals/downloads/procmon.

**Comment by namtr92** [comment]
> To get a full list of DLLs, you can use Process Monitor to trace file system of your test application: https://learn.microsoft.com/en-us/sysinternals/downloads/procmon.
> 
> Another tool is dependency walker. Example: ![Image](https://github.com/user-attachments/assets/1022812e-9861-47d5-a118-d7ac82ce77ea) ![Image](https://github.com/user-attachments/assets/52ab7597-6997-479f-9867-c060d36578c2)

Thanks, that help a lot!
