### ISSUE TITLE
Trying to add a domain to DomainToVersion map, but the domain is already exist with version range (1, 1000). domain: "trt.plugins"

### ISSUE THREAD

**Issue by jax11235** [microsoft/onnxruntime#22663]
### Describe the issue

I tested a onnxruntime inference program with `TensorRT` backend, the program work correctly under single thread and multiple processes, but failed under multiple threads, and exception throwed:
```
terminate called after throwing an instance of 'Ort::Exception'
  what():  Trying to add a domain to DomainToVersion map, but the domain is already exist with version range (1, 1000). domain: "trt.plugins"
```

### To reproduce

Temporarily unavailable

### Platform

Linux

### OS Version

ubuntu 22.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.19.2

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

TensorRT

### Execution Provider Library Version

CUDA 12.2, CUDNN 9, TensorRT 10.2

**Comment by jax11235** [comment]
It seems that session initialization of different threads will affect each other.

**Comment by xlg-go** [comment]
> It seems that session initialization of different threads will affect each other.

+1
have you fix it？

**Comment by maaft** [comment]
@jax11235  can you elaborate on why you closed this? I also get this error.
