### ISSUE TITLE
[Build]  Eigen 3.4 build failure with ONNXRuntime 1.9.2

### ISSUE THREAD

**Issue by dalekchef** [microsoft/onnxruntime#22679]
### Describe the issue

When running the build.sh command on a NVIDIA Jetson I receive numerous errors related to Eigen but caused by ONNX code:

I confirmed that I have Eigen 3.4 installed, but even if there was some minor version issue shouldn't the build script install based on cmake/deps.txt rather than my system version of Eigen

### Urgency

Yes

### Target platform

ARM NVIDIA Jetson

### Build script

<code>
./build.sh --config Release --update --parallel --build --build_wheel --build_shared_lib --skip_tests --use_tensorrt --tensorrt_home /usr/lib/$(uname -m)-linux-gnu  --cuda_home /usr/local/cuda --cudnn_home /usr/lib/$(uname -m)-linux-gnu 
</code>

### Error / output

<code>
/mnt/nova_ssd/local_workspace/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.cc: In member function ‘onnxruntime::common::Status onnxruntime::Min_6<T>::Compute(onnxruntime::OpKernelContext*) const [with T = float]’:
/mnt/nova_ssd/local_workspace/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.cc:708:56: error: no matching function for call to ‘Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<float, -1, 1>, 0, Eigen::Stride<0, 0> > >::min<Eigen::PropagateNaN>(Eigen::ArrayWrapper<Eigen::Map<const Eigen::Matrix<float, -1, 1>, 0, Eigen::Stride<0, 0> > >)’
  708 |     min = min.array().template min<Eigen::PropagateNaN>(EigenMap<float>(data_n).array());
</code>
<code>
/mnt/nova_ssd/local_workspace/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.cc:708:56: error: type/value mismatch at argument 1 in template parameter list for ‘template<class OtherDerived> const Eigen::CwiseBinaryOp<Eigen::internal::scalar_min_op<typename Eigen::internal::traits<T>::Scalar, typename Eigen::internal::traits<OtherDerived>::Scalar>, const Derived, const OtherDerived> Eigen::ArrayBase<Derived>::min(const Eigen::ArrayBase<OtherDerived>&) const [with OtherDerived = OtherDerived; Derived = Eigen::ArrayWrapper<Eigen::Map<Eigen::Matrix<float, -1, 1>, 0, Eigen::Stride<0, 0> > >]’
  708 |     min = min.array().template min<Eigen::PropagateNaN>(EigenMap<float>(data_n).array());
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/nova_ssd/local_workspace/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.cc:708:56: note:   expected a type, got ‘Eigen::PropagateNaN’
</code>

<code>
/mnt/nova_ssd/local_workspace/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.cc:855:85: error: type/value mismatch at argument 1 in template parameter list for ‘template<class OtherDerived> const Eigen::CwiseBinaryOp<Eigen::internal::scalar_max_op<typename Eigen::internal::traits<T>::Scalar, typename Eigen::internal::traits<OtherDerived>::Scalar>, const Derived, const OtherDerived> Eigen::ArrayBase<Derived>::max(const Eigen::ArrayBase<OtherDerived>&) const [with OtherDerived = OtherDerived; Derived = Eigen::ArrayWrapper<Eigen::Map<const Eigen::Matrix<long unsigned int, -1, 1, 0, -1, 1>, 0, Eigen::Stride<0, 0> > >]’
  855 |               per_iter_bh.EigenInput0<T>().array().template max<Eigen::PropagateNaN>(per_iter_bh.ScalarInput1<T>());
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

</code>
<code>
/mnt/nova_ssd/local_workspace/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.cc:855:85: note:   expected a type, got ‘Eigen::PropagateNaN’
/mnt/nova_ssd/local_workspace/onnxruntime/onnxruntime/core/providers/cpu/math/element_wise_ops.cc:859:85: error: no matching function for call to ‘Eigen::ArrayWrapper<Eigen::Map<const Eigen::Matrix<long unsigned int, -1, 1, 0, -1, 1>, 0, Eigen::Stride<0, 0> > >::max<Eigen::PropagateNaN>(Eigen::ArrayWrapper<Eigen::Map<const Eigen::Matrix<long unsigned int, -1, 1, 0, -1, 1>, 0, Eigen::Stride<0, 0> > >)’
  859 |               per_iter_bh.EigenInput0<T>().array().template max<Eigen::PropagateNaN>(
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  860 |                   per_iter_bh.EigenInput1<T>().array());
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~        

</code>

### GCC / Compiler Version

11.4.0

**Comment by jywu-msft** [comment]
it shouldn't use your system eigen unless you explicitly set the option https://github.com/microsoft/onnxruntime/blob/1b60209938fb62cd067d1e7105bf1eef08b083a6/tools/ci_build/build.py#L578

can you provide more info about your build environment?  OnnxRuntime commit,  JetPack version,  what type of Jetson device etc. 
Are you building your own primarily to build libonnxruntime.so ? I see you have --build_wheel in your build option so if you are ok with python, you can use the python packages hosted on Jetson Zoo https://elinux.org/Jetson_Zoo#ONNX_Runtime

**Comment by dalekchef** [comment]
Thanks very much, I actually need to build the full onnxruntime. I am running Jetpack 6.0.  My best guess at this point is that maybe there is some problem due to ROS2-Humble being installed?

**Comment by dalekchef** [comment]
I tried with v1.18.2 and everything worked fine. I think I will probably close the ticket for now. 

Thanks very much for your help it is greatly appreciated.

**Comment by janakg** [comment]
I guess the problem still exists, 

we have not provided the `--use_preinstalled_eigen` or eigen path

Latest versions are picking from system Eigen. How to force not to take from system paths like` /usr/include`

**Comment by janakg** [comment]
is it possible, eigen is not getting downloaded to _deps due to mismtach in hash?

**Comment by janakg** [comment]
I guess found a work around.
`onnxruntime-1.20.1/cmake/external/onnxruntime_external_deps.cmake`

In this file commenting off the find package, downloads the deps
```
# find_package(Eigen3 CONFIG)
if(Eigen3_FOUND)
  get_target_property(eigen_INCLUDE_DIRS Eigen3::Eigen INTERFACE_INCLUDE_DIRECTORIES)
else()
  include(eigen) # FetchContent
endif()
```

**Comment by geraldinedeeplearning** [comment]
Hi,

Can you confirm that by forcing `include(eigen)` in that `.cmake` file, you force eigen to be fetched ? 
I tried, and I still don't see any eigen in the `_deps`. I tried on a fresh 1.20.1 tarball, and I still have problems during compilation.

Thank you for the messages.

> I guess found a work around. `onnxruntime-1.20.1/cmake/external/onnxruntime_external_deps.cmake`
> 
> In this file commenting off the find package, downloads the deps
> 
> ```
> # find_package(Eigen3 CONFIG)
> if(Eigen3_FOUND)
>   get_target_property(eigen_INCLUDE_DIRS Eigen3::Eigen INTERFACE_INCLUDE_DIRECTORIES)
> else()
>   include(eigen) # FetchContent
> endif()
> ```
