### ISSUE TITLE
import onnxruntime fails: "Error: 'dynamic module does not define init function"

### ISSUE THREAD

**Issue by snippler** [microsoft/onnxruntime#2267]
**Describe the bug**
I have build onnxruntime from source for Python2. I made some changes in the code. Compiling and installation were succesful. But now when I import onnxruntime this error comes

>>> import onnxruntime
/home/pi/.local/lib/python2.7/site-packages/onnxruntime/capi/_pybind_state.py:13: UserWarning: Cannot load onnxruntime.capi. Error: 'dynamic module does not define init function (initonnxruntime_pybind11_state)'
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'".format(str(e)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python2.7/site-packages/onnxruntime/__init__.py", line 18, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, RunOptions, SessionOptions, set_default_logger_severity, NodeArg, ModelMetadata, GraphOptimizationLevel, ExecutionMode
ImportError: cannot import name get_all_providers

**System information**
- OS: Raspbian
- ONNX Runtime installed from source:
- ONNX Runtime version: 0.5.0
- Python version: 2.7

**Expected behavior**
There is no problem in Python3. When I search I find this kind of error in context of Python2 vs 3 but no solution.

**Comment by hariharans29** [comment]
Hi,

I believe we currently do not support Python2...

**Comment by snippler** [comment]
Yes, but maybe it can work nevertheless. For installing I had to change <10 lines of code.

**Comment by pranavsharma** [comment]
We don't plan to support Python 2. Even if it works with < 10 lines of code, we don't want to keep maintaining it. Thanks!

**Comment by snippler** [comment]
I didn't ask for maintanance, I asked for advice. Whats the problem keeping this issue open for a day or two in case somebody knows how to fix it?

**Comment by pranavsharma** [comment]
Sure, I was just setting the right expectations. Also, reproducing and debugging unsupported scenarios takes away resources from addressing issues relating to supported scenarios. Please feel free to re-open and we'll be more than happy to help as time permits.

**Comment by snippler** [comment]
I think I cannot reopen because have no permissions.

**Comment by hariharans29** [comment]
Re-opened as per comment.

**Comment by jywu-msft** [comment]
I experimented with this a bit.
The error you are encountering can be addressed by changing
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/version_script.lds#L4
from
PyInit_onnxruntime_pybind11_state;
to
initonnxruntime_pybind11_state;

I assume you made some other minor modifications to build onnxruntime_pybind11_state.so using python 2.7

I didn't test extensively, but I was able to import onnxruntime , load resnet50 model and run an inference successfully with python2.7

**Comment by jywu-msft** [comment]
adding a reference to https://github.com/microsoft/onnxruntime/issues/2153 in case someone else comes across it.

**Comment by faxu** [comment]
Marking this as closed. We do not officially support python 2 but you can try the suggested fix above.
