### ISSUE TITLE
Cannot parse constant nodes in local functions whose values reference function attributes

### ISSUE THREAD

**Issue by yuanyao-nv** [microsoft/onnxruntime#22687]
### Describe the issue

In the model below, the `LocalFunction` node has an attribute  that is referenced by the `Constant` node inside the local function.
![Image](https://github.com/user-attachments/assets/4066651f-499a-417a-8ef7-2f473acb2e20)
![Image](https://github.com/user-attachments/assets/0d90be83-c39a-496f-bf3a-0fbf46f0ca38)

Onnxruntime v1.19.0 gives the following error:
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /workspace/test_clean_local_function_opset20.onnx failed:Node () Op (LocalFunction) [ShapeInferenceError] Inference error(s): (op_type:Constant, node name: onnx_graphsurgeon_node_1): [ShapeInferenceError] One and only one of the attributes 'value', 'value_*' or 'sparse_value' must be specified for a Constant node.
```
Is there anything illegal about this construction? The same model can run with TensorRT.
I can attach or email the model if necessary.

### To reproduce

Run the usual inference procedure with this model. Random input will do. I can attach or email the model if needed.

### Platform

Linux

### OS Version

Ubuntu 24.06

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.19.0

### ONNX Runtime API

Python

### Architecture

X86

### Execution Provider

Default CPU

**Comment by yuanyao-nv** [comment]
maybe @justinchuby or @gramalingam have some thoughts? 🙏

**Comment by justinchuby** [comment]
Can you print the model out as a textproto string?

**Comment by justinchuby** [comment]
Looks like the attribute needs to be declared on the function: https://github.com/onnx/onnx/blob/97f01ed7a2ac9588d78cc25c236f3c453befdb22/onnx/onnx.proto#L829-L837

**Comment by gramalingam** [comment]
Yes. Specifically, "axis" needs to be declared as an attribute parameter of "LocalFunction"
