### ISSUE TITLE
crashing onnx runtime

### ISSUE THREAD

**Issue by xalteropsx** [microsoft/onnxruntime#22700]
### Describe the issue

[ONNXRuntimeError] : 1 : FAIL : D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\ExecutionProvider.cpp(962)\onnxruntime_pybind11_state.pyd!00007FFABA30B0B1: (caller: 00007FFABA30B740) Exception(3) tid(5a68) 887A0005 The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

faileoon
cannot unpack non-iterable NoneType object

### To reproduce

buffalow_l from insightface crashing if call quickly at 0.04 threshold

### Urgency

crashing whole application 

### Platform

Windows

### OS Version

11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.20.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

DirectML

**Comment by mszhanyi** [comment]
Could you check if there's another GPU application running?
