### ISSUE TITLE
[Web] 1.20.0 breaks SkipSimplifiedLayerNormalization backwards compatibility. Missing Input: model.layers.0.input_layernorm.weight

### ISSUE THREAD

**Issue by xenova** [microsoft/onnxruntime#22704]
### Describe the issue

After upgrading to onnxruntime-node 1.20.0, I obtain the following error when trying to run models which were previously exported (and working) with earlier versions of onnx/onnxruntime:

```
Non-zero status code returned while running SkipSimplifiedLayerNormalization node. Name:'/model/layers.0/post_attention_layernorm/SkipLayerNorm' Status Message: /onnxruntime_src/include/onnxruntime/core/framework/op_kernel_context.h:42 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: model.layers.0.input_layernorm.weight
```

### To reproduce

Attempt to run one of the following models:

- (BREAKS) https://huggingface.co/onnx-community/tiny-random-LlamaForCausalLM-ONNX/resolve/main/onnx/model_fp16.onnx
- (BREAKS) https://huggingface.co/onnx-community/tiny-random-LlamaForCausalLM-ONNX/resolve/main/onnx/model_q4f16.onnx
- (WORKS) https://huggingface.co/onnx-community/tiny-random-LlamaForCausalLM-ONNX/resolve/main/onnx/model.onnx

### Urgency

Blocks upgrading transformers.js to use onnxruntime-node v1.20.0

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.20.0

### Execution Provider

'wasm'/'cpu' (WebAssembly CPU)

**Comment by xenova** [comment]
It also breaks for WASM EP (WebGPU still works): https://jsfiddle.net/9v4fa3gw/

**Comment by fs-eire** [comment]
@xenova Thank you for the issue report! I did some investigation and identified the issue is in the CPU implementation of f16 `[Skip][Simplified]LayerNormalizaion`.

This issue is not web specific. All language binding may run into this issue if using CPU/f16 on any of the 4 operators.

We will do the fix ASAP and will publish a nightly build once it's done. Will also work on a patch release to include the fix.

**Comment by xenova** [comment]
@fs-eire Amazing - thanks so much! 🥳 I'll upgrade the build when you're ready 👍 Will this include a dev version of `onnxruntime-node` too?

**Comment by oyazdanb** [comment]
> [@xenova](https://github.com/xenova) Thank you for the issue report! I did some investigation and identified the issue is in the CPU implementation of f16 `[Skip][Simplified]LayerNormalizaion`.
> 
> This issue is not web specific. All language binding may run into this issue if using CPU/f16 on any of the 4 operators.
> 
> We will do the fix ASAP and will publish a dev build of onnxruntime-web once it's done. Will also work on a patch release to include the fix.

I see this issue in Onnxruntime-DirectML as well; Does this fix help with ort-dml?

**Comment by fs-eire** [comment]
Will investigate this issue. It looks like the problem is in CPU EP and 

> [@fs-eire](https://github.com/fs-eire) Amazing - thanks so much! 🥳 I'll upgrade the build when you're ready 👍 Will this include a dev version of `onnxruntime-node` too?

Currently the pipeline does not support this but I can do a manual publish if necessary.

**Comment by fs-eire** [comment]
> > [@xenova](https://github.com/xenova) Thank you for the issue report! I did some investigation and identified the issue is in the CPU implementation of f16 `[Skip][Simplified]LayerNormalizaion`.
> > This issue is not web specific. All language binding may run into this issue if using CPU/f16 on any of the 4 operators.
> > We will do the fix ASAP and will publish a dev build of onnxruntime-web once it's done. Will also work on a patch release to include the fix.
> 
> I see this issue in Onnxruntime-DirectML as well; Does this fix help with ort-dml?

I am not sure if the problem that you saw is exactly caused by this. If it is, the fix should help.

**Comment by xenova** [comment]
> Currently the pipeline does not support this but I can do a manual publish if necessary.

Yes please! 😇 Transformers.js v3.1.0 will include this fix

**Comment by xenova** [comment]
Hi! Here is the new error message I get now:
> failed to inference ONNX model: Error: failed to call OrtRun(). ERROR_CODE: 2, ERROR_MESSAGE: Non-zero status code returned while running SkipSimplifiedLayerNormalization node. Name:'/model/layers.0/post_attention_layernorm/SkipLayerNorm' Status Message: gamma is expected to have 1 dimension, got 0.

**Comment by fs-eire** [comment]
Did some update and this is the latest fix -> [dist.zip](https://github.com/user-attachments/files/17672399/dist.zip)

**Comment by xenova** [comment]
Great! That fixed it @fs-eire 🥳 Please let me know when you put a dev build out 👍

**Comment by xenova** [comment]
@fs-eire Could you merge and/or put out a dev build? 😇

**Comment by jywu-msft** [comment]
> [@fs-eire](https://github.com/fs-eire) I see it was merged in [f0ac5e0](https://github.com/microsoft/onnxruntime/commit/f0ac5e0d3dc07d519f4476682c03f33fc79e0eb5). could you put out a dev build for onnxruntime-node? 😇

+@guschmue

**Comment by ulgens** [comment]
👀

**Comment by fs-eire** [comment]
onnxruntime-node 1.20.1 is released and should have included the fixes.

**Comment by xenova** [comment]
I can confirm that fixes it. Thanks!
