### ISSUE TITLE
Slice test for reverse

### ISSUE THREAD

**Issue by KeDengMS** [microsoft/onnxruntime#2272]
**Describe the bug**
ONNX spec inconsistency in Slice op for opset 10.

In Slice_op.test.cc, there are some tests for [reversing](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/providers/cpu/tensor/slice_op.test.cc#L420-L433). In the test, INT_MAX is used for end, while -1 for start, with -1 for step. The test verifies the output to reversing the specified axis. However, this behavior is not clarified in ONNX spec for [Slice](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Slice). Moreover, when changing the test to use [start/end/axes/step as initializer](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/providers/cpu/tensor/slice_op.test.cc#L38-L43) by using AddInput(..., true), the test crashes in ONNX shape inference, as the computed shape is 0 from ONNX shape inference. When start/end/axes/step are not initializers, ONNX shape inference bypasses the Slice node, so this bug is not triggered.

**Urgency**

If there are models relying on this behavior, it will not work if the input for start/end/axes/step changed from dynamic input to initializers. This may also cause confusion to other providers implementing Slice op.

**System information**
Any

**To Reproduce**
Change slice_op.test.cc to use [start/end/axes/step as initializer](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/providers/cpu/tensor/slice_op.test.cc#L38-L43) by using AddInput(..., true)

**Expected behavior**
The Slice for Reversing tests should pass with proper shape inference fixes in ONNX, and doc clarifications. Otherwise, those tests should be removed to avoid inconsistency with spec.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by hariharans29** [comment]
You are right - It probably *would* make more sense if the ONNX spec said use `INT_MAX` for postive steps and `INT_MIN` for negative steps. This makes logical sense. The spec is ambiguous when it says - "For slicing to the end of a dimension with unknown size, it is recommended to pass in INT_MAX". 
Numpy supports a single "special index" - `None`, which works for positive and negative stepping. I just treated `INT_MAX` to be the `None` equivalent of Numpy while implementing. 

https://github.com/microsoft/onnxruntime/blob/aa041026e362f0728232b4aeec3a23a48ed3d70f/onnxruntime/core/providers/cpu/tensor/slice.cc#L188

But we do need to be consistent with the shape inference logic as well. 

I think we can fix this easily - by clarifying the spec in ONNX and then remove the special casing in ONNX Runtime. The `else` equivalent of the same `if` block does the clamping which will handle the `INT_MAX` and `INT_MIN` special indexing.

https://github.com/microsoft/onnxruntime/blob/aa041026e362f0728232b4aeec3a23a48ed3d70f/onnxruntime/core/providers/cpu/tensor/slice.cc#L199

**Comment by KeDengMS** [comment]
Agreed, and the shape inference logic in ONNX needs to be fixed for the reverse cases.

**Comment by hariharans29** [comment]
Well, if the spec is clarified to make `INT_MIN` the "special end of the dimension index" while reverse stepping, I think the shape inference logic in ONNX can remain as such. The shape inferencing logic already does clamping in case the `ends` are out of bounds and this clamping logic will handle `INT_MAX` while forward stepping and `INT_MIN` while negative stepping. In case `INT_MAX` is provided while negative stepping the shape should be empty as what it is doing right now (if my understanding is correct)...

**Comment by KeDengMS** [comment]
Please try the repro to change the Slice reverse test cases to use initializer. You'll find out ONNX inference incorrectly generate output shape of [0] for start=-1, end=-INT_MAX, step=-1, because it clamps end to -1, so start-end = 0...

**Comment by hariharans29** [comment]
In theory, that should not happen. The logic is there to handle this case (I think!). Let me try reproing via shape inference tests.

Let's assume the you have 1D input of shape [10]. For start = -1, end = -INT_MAX, step = -1.

The code snippets are from the shape inferencing logic n ONNX - 

```
            // process start
            auto start = starts[axis_index];
            if (start < 0)
              start += input_dim_value;
            if (step < 0)
              start = clamp(start, 0, input_dim_value - 1);
            else
              start = clamp(start, 0, input_dim_value);
```
 start should now be *corrected* to 9 (-1 + 10 = 9)
 
```
            // process end
            auto end = ends[axis_index];
            if (end < 0)
              end += input_dim_value;
            if (step < 0)
              end = clamp(end, -1, input_dim_value);
            else
              end = clamp(end, 0, input_dim_value);
```
end will now be clamped to -1 (step is negative).

(end - start) / step = (-1 - 9)/ -1 = 10.

The logic (even in current state) should handle this. Let me take a look.

**Comment by hariharans29** [comment]
I added a test as suggested by you to try and repro your suggested case in the previous comment: start = -1, end = -INT_MAX, step = -1 with initializers and it works as expected - 

```
TEST(SliceTest, Slice1D_ReverseAllAxes_WithInitializers_ToTriggerShapeInferencing) {
  OpTester testv10("Slice", 10);
  testv10.AddInput<float>("data", {4}, {1.0f, 2.0f, 3.0f, 4.0f});
  testv10.AddInput<int64_t>("starts", {1}, {-1}, true);                           // make 'starts' an initializer
  testv10.AddInput<int64_t>("ends", {1}, {-std::numeric_limits<int32_t>::max()}, true);  // make 'ends' an initializer
  testv10.AddInput<int64_t>("axes", {1}, {0}, true);                              // make 'axes' an initializer
  testv10.AddInput<int64_t>("steps", {1}, {-1}, true);                           // make 'steps' an initializer
  testv10.AddOutput<float>("output", {4}, {4.0f, 3.0f, 2.0f, 1.0f});
  testv10.Run(OpTester::ExpectResult::kExpectSuccess, "", {kTensorrtExecutionProvider});
}
```

To me the only divergence between ORT and ONNX shape inference will be the case you described in  the issue description - "INT_MAX is used for end, while -1 for start, with -1 for step". ORT special cases INT_MAX and handles this for `step = -1` (superfluously maybe as this is not explicitly mentioned in the spec), whereas ONNX doesn't special-case INT_MAX at all. This should be the only divergence and if spec is clarified appropriately, we don't need to change anything in the ONNX shape inference. Please correct me if I am wrong.

**Comment by KeDengMS** [comment]
The test passes now because of [relaxed shape check](https://github.com/microsoft/onnxruntime/commit/3cda9f717bb780e2af9a0057c8d90db06869927c). You'll still notice warnings when running the test:

2019-10-31 00:28:49.398331981 [W:onnxruntime:Default, graph.cc:73 MergeShapeInfo] Error merging shape info for output. 'output' source:{0} target:{4}. Falling back to lenient merge.

**Comment by hariharans29** [comment]
Actually I don't see the warnings. I even stepped through the test in VS to see if it fails the shape inference and falls back into the relaxed shape check code, and it doesn't and it merges the source and target shapes which seem to have the same values. Maybe, we can sync via a call tomorrow.

**Comment by KeDengMS** [comment]
Just found that existing tests uses INT_MAX for end when step < 0, and that's why I still saw the error. Yes you are right that if INT_MIN is used for reverse in the test case, it would be OK.

**Comment by hariharans29** [comment]
Thanks for confirming.

**Comment by hariharans29** [comment]
Hi @KeDengMS ,

I created an issue in ONNX for tracking this - https://github.com/onnx/onnx/issues/2433. Since the spec is currently ambiguous, I don't think we have anything to change in ORT at this moment. So closing this out. Please re-open if you have further comments. Thanks!
