### ISSUE TITLE
QNN EP removes needed names from graph - leading to crash in QnnHtpPrepare

### ISSUE THREAD

**Issue by john-dance** [microsoft/onnxruntime#22765]
### Describe the issue

When running the model, there are initializers and NodeArgs that are removed because they are no longer used. For example:
Removing initializer 'onnx_Mul_818'. It is no longer used by any node.
Removing NodeArg 'Transpose_token_428_out0'. It is no longer used by any node.

However, the QNN EP seems to remove some needed inputs. This results in some error messages like this:
Input name not exist: network_0_network_0_0_mlp_fc1_Conv.weight_dq at location qnn_model_wrapper.cc:138 onnxruntime::qnn::QnnModelWrapper::CreateQnnInputOutputTensors 
nput name not exist: network_0_network_0_1_mlp_fc1_Conv.weight_dq at location qnn_model_wrapper.cc:138 onnxruntime::qnn::QnnModelWrapper::CreateQnnInputOutputTensors 

And that leads to a crash in QNNHtpPrepare.

If I run the same model on the CPU, it works.
If I run the same model with DirectML EP it works. I also noticed the following messages when using DML EP:
Add MemcpyFromHost after network_0_network_0_0_mlp_fc1_Conv.weight_dq for DmlExecutionProvider
Notice that this is one of the names that does not exist when running with the QNN EP.

### To reproduce

Run the model found in this AI Hub job: https://app.aihub.qualcomm.com/jobs/jgdxeoy6p with the QNN EP.
(Notice that this will only be available to members of the MSFT QNN EP team.)

### Platform

Windows

### OS Version

Windows 11

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

1.19.2

### ONNX Runtime API

C++

### Architecture

ARM64

### Execution Provider

Other / Unknown

### Execution Provider Library Version

QNN EP

**Comment by ashumish-QCOM** [comment]
Hi @john-dance  

Could you please provide the following details:

The specific model you are using (if different from the one linked).
Any modifications made to the model before running it with the QNN EP.
The complete log output when the error occurs.

**Comment by john-dance** [comment]
The model used is attached. No modifications were made to this model. The complete log is in the linked job above. Select the Runtime Log tab.

[job_jg9ljw7mg_optimized_onnx_mqkk1zxwq.onnx.zip](https://github.com/user-attachments/files/17852840/job_jg9ljw7mg_optimized_onnx_mqkk1zxwq.onnx.zip)

**Comment by ashumish-QCOM** [comment]
Hi @john-dance 

I am not able to access this.
 https://app.aihub.qualcomm.com/jobs/jgdxeoy6p

**Comment by john-dance** [comment]
Log is attached:
[jgdxeoy6p_runtime.log](https://github.com/user-attachments/files/17876016/jgdxeoy6p_runtime.log)

**Comment by HectorSVC** [comment]
There are some Conv nodes do not have Q,DQ pairs for activation. for example,
![Image](https://github.com/user-attachments/assets/e5262bec-ab2d-46ac-b33a-9fd3018608d5)
It will cause those Conv nodes run with fp32 mode. That should be the reason cause the crash in QnnHtpPrepare.
And I tried with latest Onnxruntime + QNN 2.28. It successfully generated the context binary and run without any problems.
So, suggest updating to latest Onnxruntime + QNN 2.28. And fix the model to make all Conv nodes run with quantized mode.
