### ISSUE TITLE
[Documentation] CoreML python support and how to switch to MLProgram

### ISSUE THREAD

**Issue by Rikyf3** [microsoft/onnxruntime#22792]
### Describe the documentation issue

Hi.

First of all thank you for the incredible work you do :D

I was looking at the [Apple - CoreML page ](https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html) for help on how to fully support a production model in CoreML EP. As the model contains ConvTranspose I have to enable MLProgram. The production code is in python. The documentation does not state neither that python API is supported or how to enable COREML_FLAG_ONLY_ENABLE_DEVICE_WITH_ANE.

Can this two information be added to the documentation?

Thanks,
Riccardo

### Page / URL

https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html

**Comment by wejoncy** [comment]
Thanks for filing the issue. 

A more general path to enable ML_Program is implementing by this [PR](https://github.com/microsoft/onnxruntime/pull/22675)

After that, I will make the doc more clear and detail.

**Comment by Rikyf3** [comment]
Thank you very much :)
Is there any way in which I can enable it already in 1.19.0 to make the model fully compatible?

**Comment by wejoncy** [comment]
```
providers = [
    ('CoreMLExecutionProvider', {
        'flags': "COREML_FLAG_CREATE_MLPROGRAM",
    }),
    'CPUExecutionProvider',
]

session = ort.InferenceSession(model_path, providers=providers)
```
