### ISSUE TITLE
FillStringTensor() should also require length of each string element

### ISSUE THREAD

**Issue by GuanLuo** [microsoft/onnxruntime#2284]
**Describe the bug**
The function doesn't behave properly if there is null character within the string element. For example, if the element is C-string "abc\0def\0", the internal assignment will only set the part until first null character as the value, which becomes "abc".

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: c24d7a8a0a95002cfde70db8ffdac1a1d95b3ca7
- Python version: 3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Load the identity model from attachment and run it with input element "abc\0def\0" using the C library

**Expected behavior**
The output should be the same as input.

[identity.zip](https://github.com/microsoft/onnxruntime/files/3786431/identity.zip)

**Comment by snnn** [comment]
There was a debate of "Could the strings in onnx string tensor contain '\0' in the middle or not?". I don't have a clear answer. And the API assumes "no" for that question.

**Comment by GuanLuo** [comment]
Okay, is there a chance that the API will be changed? The example I show is the simplified version of sending a serialized protobuf to a model. But if ONNX is not intended to handle this kind of use cases, then I am not going to bother.

**Comment by GuanLuo** [comment]
Another case that I will use to advocate for allowing passing size of string is that the data may come in the form of non C-string (i.e. bytes representing string size appended by the actual string with no terminator).
Currently my workaround is to make a copy of the raw data so that I can modify the string to be C-string, then pass it to ORT C API. If I can specify size of string, I can just use position in the raw data to avoid the extra copy.
