### ISSUE TITLE
[Build] linking against header-only library cudnn_frontend

### ISSUE THREAD

**Issue by ConnorBaker** [microsoft/onnxruntime#22855]
### Describe the issue

I'm packaging `onnxruntime` for the Nixpkgs CUDA ecosystem (https://github.com/connorbaker/cuda-packages).

When building with `nix`, I ran into errors while linking because the linker was unable to find `-lcudnn_frontend`.

My understanding was that `cudnn-frontend` was a header-only library (https://github.com/NVIDIA/cudnn-frontend) -- why does `onnxruntime` try to link against a library?

https://github.com/microsoft/onnxruntime/blob/ac9c135b9543ad0374fe335bc3dc5feb0f24f010/cmake/onnxruntime_unittests.cmake#L70

https://github.com/microsoft/onnxruntime/blob/ac9c135b9543ad0374fe335bc3dc5feb0f24f010/cmake/onnxruntime_providers_cuda.cmake#L208

### Target platform

x86_64-linux with TensorRT

### Build script

```console
nix build -L --builders '' --no-link github:connorbaker/cuda-packages/fabe15378f8cf5a0870d6189115170a042a802f5#pkgsCuda.sm_89.cudaPackages_12.onnxruntime
```

### Error / output

```console
cuda12.6-onnxruntime> /nix/store/va7kw1i822h95im4jacci19v0cqajfyf-binutils-2.43.1/bin/ld: cannot find -lcudnn_frontend: No such file or directory
cuda12.6-onnxruntime> collect2: error: ld returned 1 exit status
cuda12.6-onnxruntime> ninja: build stopped: subcommand failed.
```

### GCC / Compiler Version

13.3.0

**Comment by tianleiwu** [comment]
See https://github.com/microsoft/onnxruntime/blob/bbe7c8773837aa7573e202aefd2c633a06be2c23/cmake/onnxruntime_providers_cuda.cmake#L200-L210

**Comment by snnn** [comment]
cudnn_frontend is a cmake target. It's ok to do so, because the `target_link_libraries` command will add extra compile flags for the target.  In this case, for example, CUDNN_FRONTEND_SKIP_JSON_LIB.  But, we may also change it to onnxruntime_add_include_to_target.
```
onnxruntime_add_include_to_target(${target} cudnn_frontend)
```
Let me know if it would solve the problem.

**Comment by ConnorBaker** [comment]
This is largely the result of the way I was bringing in `cudnn-frontend`.

With Nixpkgs, I was including the result of `cudnn-frontend`'s installation, which is essentially an `include` directory. `cudnn-frontend` doesn't provide a CMake configuration, so while my patched build was able to find the header files, it was failing during the linking phase because CMake didn't know it was an interface library.

The dependency fetching setup you've got in-repo will fetch the `cudnn-frontend` repo and unpack it and include it directly. I believe that means the `cudnn_frontend` target is created as an interface library (since it uses the repo's `CMakeLists.txt`).

In terms of my packaging, I've vendored a replacement for `cudnn-frontend`'s CMakeLists.txt which creates a CMake configuration file so other projects can find it. I then patch `onnxruntime` by replacing `cmake/external/cudnn_frontend.cmake` with:

```console
find_package(cudnn_frontend REQUIRED)
```

and all works again.

I would like it if NVIDIA projects which are built and installed by CMake provide CMake configurations, but not all of them do. As such, I'm closing this issue since it's not a problem caused by `onnxruntime`.
