### ISSUE TITLE
Segmentation fault when following the Phi-3 tutorial for DirectML

### ISSUE THREAD

**Issue by matt200-ok** [microsoft/onnxruntime#22910]
### Describe the issue

When following the [Phi-3 Tutorial](https://onnxruntime.ai/docs/genai/tutorials/phi3-python.html) using DirectML the phi3-qa.py script causes a segmentation fault after entering the input.

This issue occurs a laptop with a 13th Gen Intel(R) Core(TM) i7-1360P and a laptop with an AMD Ryzen™ AI 9 HX 370.

### To reproduce

* Follow the [Phi-3 Tutorial](https://onnxruntime.ai/docs/genai/tutorials/phi3-python.html)s **Run With DirectML** section.
  * `huggingface-cli download microsoft/Phi-3-mini-4k-instruct-onnx --include directml/* --local-dir .`
  * `pip install numpy`
  * `pip install --pre onnxruntime-genai-directml`
  * `curl https://raw.githubusercontent.com/microsoft/onnxruntime-genai/main/examples/python/phi3-qa.py -o phi3-qa.py`
  * `python phi3-qa.py -m directml\directml-int4-awq-block-128`
    * Ask question such as `Tell me a joke about GPUs`
* Segmentation Fault.

### Platform

Windows

### OS Version

Windows 11 Home 22631.4460

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.20.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

DirectML

### Execution Provider Library Version

0.5.1

**Comment by natke** [comment]
Hi @matt200-ok, we discovered an issue with the 0.5.1 patch and have released another patch to fix it. Can you please try upgrading to 0.5.2, and then run the sample again?

**Comment by matt200-ok** [comment]
Hi @natke, the sample runs correctly now. Thank you for the help.
