### ISSUE TITLE
[Build] v1.20.1 windows x64 artifact in GitHub release

### ISSUE THREAD

**Issue by yuzawa-san** [microsoft/onnxruntime#22925]
### Describe the issue

I have a script which downloads all of the artifacts from the release that I need. An artifact from today is inconsistently named 

https://github.com/microsoft/onnxruntime/releases/download/v1.20.1/onnxruntime-win-x64.zip -> should be onnxruntime-win-x64-1.20.1.zip 

and that artifact is just ZIP which contains another ZIP. That inner zip follows the correct naming convention and is probably what should be on the outside.

Would it be possible to fix the GitHub release?

### Target platform

windows x64

### Build script

its in the github release

### Error / output

its improperly named and packaged

**Comment by yf711** [comment]
Thanks for the report! Please try https://github.com/microsoft/onnxruntime/releases/download/v1.20.1/onnxruntime-win-x64-1.20.1.zip

**Comment by yuzawa-san** [comment]
This is looking good now. Thank you!
