### ISSUE TITLE
[Build] [WSL2] CPU Provider Test Failed

### ISSUE THREAD

**Issue by lehoang318** [microsoft/onnxruntime#22934]
### Describe the issue

Failed to build ONNX Runtime v1.9.1 on WSL2.

### Target platform

5.15.167.4-microsoft-standard-WSL2 (x86_64 GNU/Linux)

### Build script

./build.sh --config Release --parallel --skip_submodule_sync --build_shared_lib

### Error / output

* Build Log: `83% tests passed, 1 tests failed out of 6`

* LastTest.log
  ```
  [ RUN      ] MatmulIntegerOpTest.MatMulInteger_Uint8_Int8_GEMV
    onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:83: Failure
    Expected equality of these values:
      expected[i]
        Which is: 64955
      output[i]
        Which is: -193062
    i:16, provider_type: CPUExecutionProvider
    ...
  [  FAILED  ] MatmulIntegerOpTest.MatMulInteger_Uint8_Int8_GEMV
  ```

### GCC / Compiler Version

gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

**Comment by skottmckay** [comment]
That test hasn't changed in 3 years and unit tests pass in all our Linux CIs. Does it fail every time? Are you building with the release tag or the latest `main`? Not sure if `Runtime v1.9.1` is meant to be 1.19.1.

**Comment by lehoang318** [comment]
> That test hasn't changed in 3 years and unit tests pass in all our Linux CIs. Does it fail every time? Are you building with the release tag or the latest `main`? Not sure if `Runtime v1.9.1` is meant to be 1.19.1.

Hi @skottmckay ,

The tag is indeed `1.9.1`, I have no idea why I did chose a tag from 2021.
I'll try the newer version of OnnxRuntime.
Thank you for the quick response.
