### ISSUE TITLE
[Build] "error: package directory 'onnxruntime/backend' does not exist" on MacOS/arm64

### ISSUE THREAD

**Issue by bluejack** [microsoft/onnxruntime#22942]
### Describe the issue

Using the documentation here:

https://onnxruntime.ai/docs/build/inferencing.html

I want to build a python wheel with custom code.

I run the macos build process without problem; all tests succeed.

I install protobufs, as directed.

I execute:

```
export ONNX_ML=1
python3 setup.py bdist_wheel
```

And then it fails with:

**error: package directory 'onnxruntime/backend' does not exist**

Which it does not.

That directory structure:

```
ReformatSource.ps1         lora
ReformatSourcePython.bat   python
VSCodeCoverage.runsettings test
__init__.py                tool
contrib_ops                wasm
core
```

### Target platform

MacOs ARM

### Build script

./build.sh --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --cmake_extra_defines CMAKE_OSX_ARCHITECTURES=arm64

Followed by:

```
export ONNX_ML=1
python3 setup.py bdist_wheel
```

### Error / output

```
running bdist_wheel
running build
running build_py
copying onnxruntime/__init__.py -> build/lib/onnxruntime
error: package directory 'onnxruntime/backend' does not exist
```

### GCC / Compiler Version

Apple clang version 15.0.0 (clang-1500.3.9.4) Target: arm64-apple-darwin23.6.0 Thread model: posix InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by bluejack** [comment]
I am trying a similar build on linux to see if the problem is me being stupid or osmething about the macos build process.

**Comment by skottmckay** [comment]
`--build_wheel` will build the wheel. It will be in the `dist` directory under the build output directory. 

I'd also suggest using `--arm64` instead of doing that via CMAKE_OSX_ARCHITECTURES.

**Comment by bluejack** [comment]
> `--build_wheel` will build the wheel. It will be in the `dist` directory under the build output directory.
> 
> I'd also suggest using `--arm64` instead of doing that via CMAKE_OSX_ARCHITECTURES.

Thanks Skott.

Note that --build_wheel fails all the python tests, but DOES build a successful wheel for RelWithDebInfo ; but does not build a successful wheel for Release 

I *guess* that's progress?
