### ISSUE TITLE
Tests fail on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [microsoft/onnxruntime#2295]
https://people.freebsd.org/~yuri/py36-onnxruntime-0.5.1.20191030.log

**Comment by snnn** [comment]
What's the locale when you run the tests?

**Comment by yurivict** [comment]
en_US.UTF-8

**Comment by snnn** [comment]
Failed tests are:

1.  ContribOpTest.StringNormalizerTest
2.  Random.MultinomialGoodCase
3.  Random.MultinomialDefaultDType

@pranavsharma  @yuslepukhin  Could you please help take a look?

**Comment by yurivict** [comment]
Is there a way to disable tests during build, and to run them separately?

**Comment by snnn** [comment]
If you have a broken test that you cannot fix right away, you can add the DISABLED_ prefix to its name. This will exclude it from execution. This is better than commenting out the code or using #if 0, as disabled tests are still compiled (and thus won't rot).

To include disabled tests in test execution,  invoke the test program with the --gtest_also_run_disabled_tests flag.

**Comment by snnn** [comment]
I'm working on it.

**Comment by snnn** [comment]
We can temp disable the failure by:
```
#ifdef __FreeBSD__
TEST(ContribOpTest, DISABLED_StringNormalizerTest) {
#else
TEST(ContribOpTest, StringNormalizerTest) {
#endif
```

What do you think?

**Comment by yurivict** [comment]
I've disabled them using the DISABLED_ prefix in the port. IMO, no need to disable them, you should rather fix them.
