### ISSUE TITLE
Initialization crash using different onnx model and different project

### ISSUE THREAD

**Issue by ChenHackerGit** [microsoft/onnxruntime#22961]
### Describe the issue

I realized it step by step according to this tutorial, and he worked very well, so I can use directml for reasoning.[https://learn.microsoft.com/en-au/windows/ai/models/get-started-onnx-winui](url)But I created a new console program and imitated this process, and there was an error when loading the model.
```Microsoft.ML.OnnxRuntime.OnnxRuntimeException
  HResult=0x80131500
  Message=[ErrorCode:RuntimeException] Exception during initialization: 
  Source=Microsoft.ML.OnnxRuntime
  StackTrace:
   在 Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   在 Microsoft.ML.OnnxRuntime.InferenceSession.Init(String modelPath, SessionOptions options, PrePackedWeightsContainer prepackedWeightsContainer)
   在 Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath, SessionOptions options)
   在 YoloParser.YoloV8Parser.InitModel() 在 D:\Cznorth\Documents\code\net\dml_test\dml_test\YoloParser\YoloV8Parser.cs 中: 第 50 行
   在 YoloParser.YoloV8Parser.Parse(Image`1 image) 在 D:\Cznorth\Documents\code\net\dml_test\dml_test\YoloParser\YoloV8Parser.cs 中: 第 73 行
   在 Program.<Main>$(String[] args) 在 D:\Cznorth\Documents\code\net\dml_test\dml_test\Program.cs 中: 第 14 行
```
Then I put the model of the original tutorial of the onnx model, and it can be imported normally, or I use cpu to reason, and it can also be imported normally, so I suspect that it is a problem with my model. What is puzzling is that when I put the model that I reported the error before into the winui project that I imitated the tutorial, it can also be imported normally.

I use the latest and the same version for all packages, but why is this problem?

reference information

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.20.1" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.6" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="model\" />
    <Folder Include="assets\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="assets\1.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="model\yolov8.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="model\resnet50-v2-7.onnx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

```

### Target platform

windows x64

### Build script

no

### Error / output

Microsoft.ML.OnnxRuntime.OnnxRuntimeException
  HResult=0x80131500
  Message=[ErrorCode:RuntimeException] Exception during initialization: 
  Source=Microsoft.ML.OnnxRuntime
  StackTrace:
   在 Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   在 Microsoft.ML.OnnxRuntime.InferenceSession.Init(String modelPath, SessionOptions options, PrePackedWeightsContainer prepackedWeightsContainer)
   在 Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath, SessionOptions options)
   在 YoloParser.YoloV8Parser.InitModel() 在 D:\Cznorth\Documents\code\net\dml_test\dml_test\YoloParser\YoloV8Parser.cs 中: 第 50 行
   在 YoloParser.YoloV8Parser.Parse(Image`1 image) 在 D:\Cznorth\Documents\code\net\dml_test\dml_test\YoloParser\YoloV8Parser.cs 中: 第 73 行
   在 Program.<Main>$(String[] args) 在 D:\Cznorth\Documents\code\net\dml_test\dml_test\Program.cs 中: 第 14 行

**Comment by skottmckay** [comment]
You could try setting the log severity to VERBOSE in the SessionOptions prior to creating the inference session. Maybe that will provide a hint.
