### ISSUE TITLE
Global<void>::api_ was nullptr

### ISSUE THREAD

**Issue by bitnick10** [microsoft/onnxruntime#2297]
When I run this code in version 0.5 it's ok,but in 1.0
`Ort::Env envmine(ORT_LOGGING_LEVEL_WARNING, "test");`
it throws
`Global<void>::api_ was nullptr`

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows10
- ONNX Runtime installed from (source or binary):nuget
- ONNX Runtime version:1.0

**Comment by pranavsharma** [comment]
I just tried and it works fine. Can add more details to repro this?

**Comment by snnn** [comment]
Is envmine a global variable?

**Comment by bitnick10** [comment]
yes, like this.@snnn 
```
class Model {
public:
    std::unique_ptr<Ort::Session> session_;
    void Load(const wchar_t* model_path = L"model.onnx") {
        static std::unique_ptr<Ort::Env> env;
        if (env.get() == nullptr) {
            env = std::make_unique<Ort::Env>(ORT_LOGGING_LEVEL_WARNING, "test");
        }
    }
}
```

**Comment by snnn** [comment]
You can't use any onnxruntime API before your main function is entered.

**Comment by bitnick10** [comment]
Yes, global Env can not work.Thanks @snnn

**Comment by binzhang** [comment]
"You can't use any onnxruntime API before your main function is entered."
why?
https://github.com/microsoft/onnxruntime/blob/521dc757984fbf9770d0051997178fbb9565cd52/samples/c_cxx/MNIST/MNIST.cpp#L12
example use global env

**Comment by snnn** [comment]
Thank you @binzhang. We should fix the sample.
