### ISSUE TITLE
Specified device is not supported. - CUDA memory info

### ISSUE THREAD

**Issue by arvindsouza** [microsoft/onnxruntime#22976]
I'm running onnx with GPU acceleration

I've confirmed that cuda provider works fine (as well as CUDA acceleration):

  OrtCUDAProviderOptions cuda_options;
  cuda_options.device_id = 0;

  session_options.AppendExecutionProvider_CUDA(cuda_options);

But, when I add the following lines:

Ort::MemoryInfo memory_info("Cuda", OrtAllocatorType::OrtArenaAllocator, 0, OrtMemTypeDefault);

Value::CreateTensor<float>(memory_info, inputTensorValues.data(), inputTensorValues.size(), inputDims.data(), inputDims.size())

I get an exception: "Specified device is not supported." [this line of code](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/framework/allocator.cc#L140)

I'm using an NVIDIA 4090 GPU with Windows Server 2019

This issue is a duplicate of #12104 however, I couldn't find a solution in that thread

I am using the ONNXRUNTIME-GPU library for C++

**Comment by skottmckay** [comment]
I tried to reproduce but couldn't. To hit the line of code that returns "Specified device is not supported" the memory name would have to not match `onnxruntime::CUDA`, but your example code, which I cut-and-pasted, matches as expected.

https://github.com/microsoft/onnxruntime/blob/49a80df77fc15493d7d233ceba4959000182eca6/include/onnxruntime/core/framework/allocator.h#L44

**Comment by arvindsouza** [comment]
I was able to resolve this. Is the name parameter case sensitive?

Turns out I was testing with name set to "cuda", changing this to "Cuda" appears to have resolved the issue
