### ISSUE TITLE
session.set_providers failed to call 'OpenVINOExecutionProvider'

### ISSUE THREAD

**Issue by JohnnyLing** [microsoft/onnxruntime#2298]
**Describe the bug**
failed to run session.set_providers(['OpenVINOExecutionProvider']) on my ubuntu machine with intel PCIe MYRIAD VPU.

get_providers() returns only CPUExecutionProvider. Below output logs:
>>> session.get_providers()
['CPUExecutionProvider']
>>> session.set_providers(['CPUExecutionProvider'])
>>> session.set_providers(['OpenVINOExecutionProvider'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/uzel/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 97, in set_providers
    raise ValueError("{} does not contain a subset of available providers {}".format(providers, C.get_available_providers()))
ValueError: ['OpenVINOExecutionProvider'] does not contain a subset of available providers ['CPUExecutionProvider']
>>> 

I can run the OpenVINO R1.1 demo on both CPU and MYRIAD. Suppose the OpenVINO setup works.
I built out onnxruntime python wheel by running the command ./build.sh --config RelWithDebInfo --use_openvino VAD-M_FP16 --build_wheel
And the new build onnxruntime was successfully installed since new method get_providers/set_providers is available.

From the source code, it looks onnxruntime will register execution provider after session initialization. Any known issue when registering OpenVINO execution provider? How can debug into the C++ pybind_state code?

Thanks

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- ONNX Runtime installed from (source or binary): source code to build python wheel
- ONNX Runtime version: 0.5.0 with support execution provider from release notes
- Python version: 3.6.8
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version:
- GPU model and memory: 8GB RAM

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by jywu-msft** [comment]
can you share output of
'''
import onnxruntime
onnxruntime.get_device()
'''

**Comment by JohnnyLing** [comment]
Thank you George for the quick response. get_device returns only 'CPU'.

>>> import onnxruntime
>>> onnxruntime.get_device()
'CPU'
>>>

The OpenVINO demo works on my ubuntu machine by running ./demo_security_barrier_camera.sh -d MYRIAD
Also the PCI-e MYRIAD device exists.

              *-pci:0
                   description: PCI bridge
                   product: Pericom Semiconductor
                   vendor: Pericom Semiconductor
                   physical id: 1
                   bus info: pci@0000:02:01.0
                   version: 00
                   width: 32 bits
                   clock: 33MHz
                   capabilities: pci pm msi pciexpress normal_decode bus_master cap_list
                   configuration: driver=pcieport
                   resources: irq:125 memory:df300000-df3fffff
                 *-usb
                      description: USB controller
                      product: ASM1042A USB 3.0 Host Controller
                      vendor: ASMedia Technology Inc.
                      physical id: 0
                      bus info: pci@0000:03:00.0
                      version: 00
                      width: 64 bits
                      clock: 33MHz
                      capabilities: msi msix pm pciexpress xhci bus_master cap_list
                      configuration: driver=xhci_hcd latency=0
                      resources: irq:17 memory:df300000-df307fff
                    *-usbhost:0
                         product: xHCI Host Controller
                         vendor: Linux 5.0.0-32-generic xhci-hcd
                         physical id: 0
                         bus info: usb@3
                         logical name: usb3
                         version: 5.00
                         capabilities: usb-2.00
                         configuration: driver=hub slots=2 speed=480Mbit/s
                       *-usb:0 UNCLAIMED
                            description: Generic USB device
                            product: Movidius MyriadX
                            vendor: Movidius Ltd.
                            physical id: 1
                            bus info: usb@3:1
                            version: 0.01
                            serial: 03e72485
                            capabilities: usb-2.00
                            configuration: maxpower=500mA speed=480Mbit/s
                       *-usb:1 UNCLAIMED
                            description: Generic USB device
                            product: Movidius MyriadX
                            vendor: Movidius Ltd.
                            physical id: 2
                            bus info: usb@3:2
                            version: 0.01
                            serial: 03e72485
                            capabilities: usb-2.00
                            configuration: maxpower=500mA speed=480Mbit/s
                    *-usbhost:1
                         product: xHCI Host Controller
                         vendor: Linux 5.0.0-32-generic xhci-hcd
                         physical id: 1
                         bus info: usb@4
                         logical name: usb4
                         version: 5.00
                         capabilities: usb-3.00
                         configuration: driver=hub slots=2 speed=5000Mbit/s

Regards

________________________________

**Comment by jywu-msft** [comment]
can you also share output of

```
import onnxruntime
print(onnxruntime.__file__)
```

it looks like the onnxruntime you are using wasn't built with openvino execution provider.
so it's possible you have multiple versions of onnxruntime installed?

**Comment by JohnnyLing** [comment]
The ubuntu machine is not accessiable. I may check onnxruntime.__file__ on next Monday.

From the testing log, calling OpenVINOExecutionProvider::GetCapability failed. I believe openvino execution provider was already built into onnxruntime, but somehow failed when calling the EP. This is frustrating since openvino demo works with myriad by calling ./demo_security_barrier_camera.sh -d MYRIAD. Any suggestion?

Below part of the log output:
1: [----------] 2 tests from ParallelExecutor
1: [ RUN      ] ParallelExecutor.TestStatusPropagation
1: 2019-11-01 15:51:52.922115323 [W:onnxruntime:Default, openvino_execution_provider.cc:481 GetCapability] [OpenVINO-EP] Rejecting as graph has unsupported operations.Operation is not supported by OpenVINO
1: 2019-11-01 15:51:52.922802114 [E:onnxruntime:Default, parallel_executor.cc:204 RunNodeAsync] Non-zero status code returned while running TestOp node. Name:'node1' Status Message: Action was 1
1: 2019-11-01 15:51:52.922820862 [E:onnxruntime:Default, parallel_executor.cc:75 Execute] [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running TestOp node. Name:'node1' Status Message: Action was 1
1: 2019-11-01 15:51:52.925144196 [W:onnxruntime:Default, openvino_execution_provider.cc:481 GetCapability] [OpenVINO-EP] Rejecting as graph has unsupported operations.Operation is not supported by OpenVINO
1: 2019-11-01 15:51:52.925178728 [E:onnxruntime:Default, parallel_executor.cc:204 RunNodeAsync] Non-zero status code returned while running TestOp node. Name:'node1' Status Message: Action was 1
1: 2019-11-01 15:51:52.925196998 [E:onnxruntime:Default, parallel_executor.cc:75 Execute] [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running TestOp node. Name:'node1' Status Message: Action was 1
1: 2019-11-01 15:51:52.925851483 [E:onnxruntime:Default, parallel_executor.cc:204 RunNodeAsync] Non-zero status code returned while running TestOp node. Name:'node1' Status Message: /home/uzel/onnxruntime/onnxruntime/test/framework/parallel_executor_test.cc:59 virtual onnxruntime::common::Status onnxruntime::test::TestOp::OpKernelImpl::Compute(onnxruntime::OpKernelContext*) const Throwing as action was 2
1: Stacktrace:
1: 
1: 2019-11-01 15:51:52.925867788 [E:onnxruntime:Default, parallel_executor.cc:75 Execute] [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running TestOp node. Name:'node1' Status Message: /home/uzel/onnxruntime/onnxruntime/test/framework/parallel_executor_test.cc:59 virtual onnxruntime::common::Status onnxruntime::test::TestOp::OpKernelImpl::Compute(onnxruntime::OpKernelContext*) const Throwing as action was 2
1: Stacktrace:
1: 
1: 2019-11-01 15:51:52.928102388 [W:onnxruntime:Default, openvino_execution_provider.cc:481 GetCapability] [OpenVINO-EP] Rejecting as graph has unsupported operations.Operation is not supported by OpenVINO
1: 2019-11-01 15:51:52.928150895 [E:onnxruntime:Default, parallel_executor.cc:204 RunNodeAsync] Non-zero status code returned while running TestOp node. Name:'node1' Status Message: /home/uzel/onnxruntime/onnxruntime/test/framework/parallel_executor_test.cc:59 virtual onnxruntime::common::Status onnxruntime::test::TestOp::OpKernelImpl::Compute(onnxruntime::OpKernelContext*) const Throwing as action was 2
1: Stacktrace:
1: 
1: 2019-11-01 15:51:52.928164513 [E:onnxruntime:Default, parallel_executor.cc:75 Execute] [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running TestOp node. Name:'node1' Status Message: /home/uzel/onnxruntime/onnxruntime/test/framework/parallel_executor_test.cc:59 virtual onnxruntime::common::Status onnxruntime::test::TestOp::OpKernelImpl::Compute(onnxruntime::OpKernelContext*) const Throwing as action was 2
1: Stacktrace:
1: 
1: [       OK ] ParallelExecutor.TestStatusPropagation (9 ms)
1: [ RUN      ] ParallelExecutor.TestNullInterOpThreadPool
1: 2019-11-01 15:51:52.928844709 [W:onnxruntime:Default, utils.cc:444 ExecuteGraphImpl] Only one thread was configured for parallel execution. Hence will use sequential execution.
1: 2019-11-01 15:51:52.929908436 [W:onnxruntime:Default, openvino_execution_provider.cc:481 GetCapability] [OpenVINO-EP] Rejecting as graph has unsupported operations.Operation is not supported by OpenVINO
1: 2019-11-01 15:51:52.929936408 [W:onnxruntime:Default, utils.cc:444 ExecuteGraphImpl] Only one thread was configured for parallel execution. Hence will use sequential execution.
1: [       OK ] ParallelExecutor.TestNullInterOpThreadPool (2 ms)

**Comment by JohnnyLing** [comment]
I install old version onnx/onnxruntime by calling pip3 install onnx/onnxruntime. Everything works well on CPU execution. But this is too old version without openvino EP support, like the method get_providers() or set_providers(). Then I built onnxruntime source code and install the python wheel. I think my onnxruntime was already built with openvino EP, but failed to run it.

**Comment by JohnnyLing** [comment]
>>> print(onnxruntime.__file__)
/home/uzel/.local/lib/python3.6/site-packages/onnxruntime/__init__.py

# -------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
# --------------------------------------------------------------------------
"""
ONNX Runtime is a performance-focused scoring engine for Open Neural Network Exchange (ONNX) models.
For more information on ONNX Runtime, please see `aka.ms/onnxruntime <https://aka.ms/onnxruntime/>`_ or the `Github project <https://github.com/microsoft/onnxruntime/>`_.
"""
__version__ = "1.0.0"
__author__ = "Microsoft"

from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, RunOptions, SessionOptions, set_default_logger_severity, NodeArg, ModelMetadata, GraphOptimizationLevel, ExecutionMode
from onnxruntime.capi.session import InferenceSession
from onnxruntime.capi import onnxruntime_validation
onnxruntime_validation.check_distro_info()

**Comment by jywu-msft** [comment]
Hi, this means that you installed onnxruntime 1.0 python package from pypi.
please uninstall that one first 

when building onnxruntime with openvino from source, please add --update --build arguments to skip tests. then please install the *.whl file that gets created.

./build.sh --config RelWithDebInfo --use_openvino VAD-M_FP16 --build_wheel --update --build

**Comment by JohnnyLing** [comment]
thank you. the OpenVINOExecutionProvider is now available. I am running the resnet50 sample from https://github.com/onnx/onnx-docker/tree/master/onnx-ecosystem/inference_demos, but failed to set openvino execution provider. any suggestions?


>>> onnxruntime.get_device()
'CPU-OPENVINO_VAD_M'
>>> session.get_providers()
['OpenVINOExecutionProvider', 'CPUExecutionProvider']
>>> session.set_providers(['OpenVINOExecutionProvider'])
2019-11-04 16:56:39.068719676 [W:onnxruntime:Default, openvino_execution_provider.cc:495 GetCapability] [OpenVINO-EP] Rejecting as Model Optimizer cannot convert this model.Python function call failure

**Comment by jywu-msft** [comment]
You don't need to call set_providers()
OpenVINOExecutionProvider is already registered by default. Your get_providers() call shows that.
Just call sess.run(...)

**Comment by jywu-msft** [comment]
@smkarlap @suryasidd for ideas on why the MO conversion failed.

**Comment by suryasidd** [comment]
Hi, Are you getting the error when you run the command session.set_proivders?

**Comment by jywu-msft** [comment]
@JohnnyLing can you provide full logs? Are there more details on why Model Optimizer fails?

openvino_execution_provider.cc:495 GetCapability] [OpenVINO-EP] Rejecting as Model Optimizer cannot convert this model.Python function call failure

**Comment by JohnnyLing** [comment]
Yes, below complete python log to run resnet50 model.

>>> import numpy as np    # we're going to use numpy to process input and output data
>>> import onnxruntime    # to inference ONNX models, we use the ONNX Runtime
>>> import onnx
>>> from onnx import numpy_helper
>>> import urllib.request
>>> import json
>>> import time
>>> import matplotlib.pyplot as plt
>>> from PIL import Image, ImageDraw, ImageFont
>>>
>>> # onnx_model_url = "https://s3.amazonaws.com/onnx-model-zoo/resnet/resnet50v2/resnet50v2.tar.gz"
... # imagenet_labels_url = "https://raw.githubusercontent.com/anishathalye/imagenet-simple-labels/master/imagenet-simple-labels.json"
... # urllib.request.urlretrieve(onnx_model_url, filename="resnet50v2.tar.gz")
... # urllib.request.urlretrieve(imagenet_labels_url, filename="imagenet-simple-labels.json")
...
>>>
>>> test_data_dir = 'resnet50v2/test_data_set'
>>> test_data_num = 3
>>>
>>> import glob
>>> import os
>>>
>>> inputs = []
>>> for i in range(test_data_num):
...     input_file = os.path.join(test_data_dir + '_{}'.format(i), 'input_0.pb')
...     tensor = onnx.TensorProto()
...     with open(input_file, 'rb') as f:
...         tensor.ParseFromString(f.read())
...         inputs.append(numpy_helper.to_array(tensor))
...
602128
602128
602128
>>>
>>> print('Loaded {} inputs successfully.'.format(test_data_num))
Loaded 3 inputs successfully.
>>>
... # Load reference outputs
...
>>>
>>> ref_outputs = []
>>> for i in range(test_data_num):
...     output_file = os.path.join(test_data_dir + '_{}'.format(i), 'output_0.pb')
...     tensor = onnx.TensorProto()
...     with open(output_file, 'rb') as f:
...         tensor.ParseFromString(f.read())
...         ref_outputs.append(numpy_helper.to_array(tensor))
...
...
4010
4010
4010
>>> print('Loaded {} reference outputs successfully.'.format(test_data_num))
Loaded 3 reference outputs successfully.
>>>
>>>
>>> session = onnxruntime.InferenceSession('resnet50v2/resnet50v2.onnx', None)
2019-11-05 10:12:25.994244006 [W:onnxruntime:Default, openvino_execution_provider.cc:495 GetCapability] [OpenVINO-EP] Rejecting as Model Optimizer cannot convert this model.Python function call failure
>>> input_name = session.get_inputs()[0].name
>>> print('Input Name:', input_name)
Input Name: data
>>>
>>> outputs = [session.run([], {input_name: inputs[i]})[0] for i in range(test_data_num)]

>>>
>>> print('Predicted {} results.'.format(len(outputs)))
Predicted 3 results.
>>> for ref_o, o in zip(ref_outputs, outputs):
...     np.testing.assert_almost_equal(ref_o, o, 4)
...
...
>>> print('ONNX Runtime outputs are similar to reference outputs!')
ONNX Runtime outputs are similar to reference outputs!
>>>
>>>
>>> def load_labels(path):
...     with open(path) as f:
...         data = json.load(f)
...     return np.asarray(data)
...
>>>
>>> def preprocess(input_data):
...     img_data = input_data.astype('float32')
...     img_data = img_data.reshape(1, 3, 224, 224)
...     mean_vec = np.array([0.485, 0.456, 0.406])
...     stddev_vec = np.array([0.229, 0.224, 0.225])
...     norm_img_data = np.zeros(img_data.shape).astype('float32')
...     for i in range(img_data.shape[0]):
...         norm_img_data[i,:,:] = (img_data[i,:,:]/255 - mean_vec[i]) / stddev_vec[i]
...     return norm_img_data
...
>>>
>>> def softmax(x):
...     x = x.reshape(-1)
...     e_x = np.exp(x - np.max(x))
...     return e_x / e_x.sum(axis=0)
...
>>>
>>> def postprocess(result):
...     return softmax(np.array(result)).tolist()
...
>>>
>>> labels = load_labels('imagenet-simple-labels.json')
>>> image = Image.open('images/dog.jpg')
>>> print("Image size: ", image.size)
Image size:  (224, 224)
>>> plt.axis('off')
(0.0, 1.0, 0.0, 1.0)
>>> display_image = plt.imshow(image)
>>> image_data = np.array(image).transpose(2, 0, 1)
>>> input_data = preprocess(image_data)
>>>
>>>
>>> start = time.time()
>>> raw_result = session.run([], {input_name: input_data})
>>> end = time.time()
>>> res = postprocess(raw_result)
>>>
>>> inference_time = np.round((end - start) * 1000, 2)
>>> idx = np.argmax(res)
>>>
>>> print('========================================')
========================================
>>> print('Final top prediction is: ' + labels[idx])
Final top prediction is: Golden Retriever
>>> print('========================================')
========================================
>>>
>>> print('========================================')
========================================
>>> print('Inference time: ' + str(inference_time) + " ms")
Inference time: 79.76 ms
>>> print('========================================')
========================================
>>>
>>> sort_idx = np.flip(np.squeeze(np.argsort(res)))
>>> print('============ Top 5 labels are: ============================')
============ Top 5 labels are: ============================
>>> print(labels[sort_idx[:5]])
['Golden Retriever' 'Labrador Retriever' 'Otterhound' 'Vizsla'
 'Sussex Spaniel']
>>> print('===========================================================')
===========================================================
>>>
>>> plt.axis('off')
(-0.5, 223.5, 223.5, -0.5)
>>> display_image = plt.imshow(image)
>>>
>>> session.get_providers()
['OpenVINOExecutionProvider', 'CPUExecutionProvider']
>>> session.set_providers(['CPUExecutionProvider'])
>>> session.get_providers()
['CPUExecutionProvider']
>>> session.set_providers(['OpenVINOExecutionProvider'])
2019-11-05 10:13:44.313459223 [W:onnxruntime:Default, openvino_execution_provider.cc:495 GetCapability] [OpenVINO-EP] Rejecting as Model Optimizer cannot convert this model.Python function call failure
>>> onnxruntime.get_device()
'CPU-OPENVINO_VAD_M'


To build onnxruntime and run the test cases, I used the command "./build.sh --config RelWithDebInfo --use_openvino VAD-M_FP16 --build_wheel --update --build --test". The log shows some errors to test openvino, but I am not sure if this is the root cause. Attached the complete log file(build_log_VAD-M_FP16_test.txt)

1: [ RUN      ] InferenceSessionTests.TestLenientShapeInferencing
1: 2019-11-05 10:13:39.981613268 [W:onnxruntime:Default, graph.cc:73 MergeShapeInfo] Error merging shape info for output. 'shape_output' source:{2} target:{1,2}. Falling back to lenient merge.
1: 2019-11-05 10:13:39.983224424 [W:onnxruntime:Default, openvino_execution_provider.cc:481 GetCapability] [OpenVINO-EP] Rejecting as graph has unsupported operations.Operation is not supported by OpenVINO

1: [ RUN      ] ParallelExecutor.TestStatusPropagation
1: 2019-11-05 10:13:39.990032890 [W:onnxruntime:Default, openvino_execution_provider.cc:481 GetCapability] [OpenVINO-EP] Rejecting as graph has unsupported operations.Operation is not supported by OpenVINO
1: 2019-11-05 10:13:39.991041217 [E:onnxruntime:Default, parallel_executor.cc:204 RunNodeAsync] Non-zero status code returned while running TestOp node. Name:'node1' Status Message: Action was 1
1: 2019-11-05 10:13:39.991061234 [E:onnxruntime:Default, parallel_executor.cc:75 Execute] [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running TestOp node. Name:'node1' Status Message: Action was 1

1: [ RUN      ] MathOpTest.Add_int32
1: 2019-11-05 10:13:51.167624553 [W:onnxruntime:Default, openvino_execution_provider.cc:495 GetCapability] [OpenVINO-EP] Rejecting as Model Optimizer cannot convert this model.Python function call failure
1: [       OK ] MathOpTest.Add_int32 (1063 ms)
1: [ RUN      ] MathOpTest.Add_int64

The last log is how I run intel openvino demo on MYRIAD successfully.

uzel@uzel-US-E1300:/opt/intel/openvino/deployment_tools/demo$ ./demo_security_barrier_camera.sh -MYRIAD
Run sudo -E apt -y install build-essential python3-pip virtualenv cmake libcairo2-dev libpango1.0-dev libglib2.0-dev libgtk2.0-dev libswscale-dev libavcodec-dev libavformat-dev libgstreamer1.0-0 gstreamer1.0-plugins-base
[sudo] password for uzel:
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://cn.archive.ubuntu.com/ubuntu bionic InRelease
Hit:3 http://cn.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:4 http://cn.archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
250 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
libgtk2.0-dev is already the newest version (2.24.32-1ubuntu1).
virtualenv is already the newest version (15.1.0+ds-1.1).
cmake is already the newest version (3.10.2-1ubuntu2.18.04.1).
gstreamer1.0-plugins-base is already the newest version (1.14.5-0ubuntu1~18.04.1).
libcairo2-dev is already the newest version (1.15.10-2ubuntu0.1).
libglib2.0-dev is already the newest version (2.56.4-0ubuntu0.18.04.4).
libgstreamer1.0-0 is already the newest version (1.14.5-0ubuntu1~18.04.1).
libpango1.0-dev is already the newest version (1.40.14-1ubuntu0.1).
libavcodec-dev is already the newest version (7:3.4.6-0ubuntu0.18.04.1).
libavformat-dev is already the newest version (7:3.4.6-0ubuntu0.18.04.1).
libswscale-dev is already the newest version (7:3.4.6-0ubuntu0.18.04.1).
python3-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 250 not upgraded.
Reading package lists... Done
Building dependency tree
Reading state information... Done
libpng-dev is already the newest version (1.6.34-1ubuntu0.18.04.2).
0 upgraded, 0 newly installed, 0 to remove and 250 not upgraded.
The directory '/home/uzel/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/uzel/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests)
[setupvars.sh] OpenVINO environment initialized


###################################################

Downloading Intel models

target_precision = FP32

vehicle-license-plate-detection-barrier-0106 have been loaded previously, skip loading model step.
vehicle-attributes-recognition-barrier-0039 have been loaded previously, skip loading model step.
license-plate-recognition-barrier-0001 have been loaded previously, skip loading model step.


###################################################

Build Inference Engine samples

-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include fnmatch.h
-- Looking for C++ include fnmatch.h - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Looking for strtoll
-- Looking for strtoll - found
-- Found InferenceEngine: /opt/intel/openvino_2019.1.144/deployment_tools/inference_engine/lib/intel64/libinference_engine.so (Required is at least version "1.6")
-- Performing Test HAVE_CPUID_INFO
-- Performing Test HAVE_CPUID_INFO - Success
-- Host CPU features:
--   3DNOW not supported
--   3DNOWEXT not supported
--   ABM not supported
--   ADX supported
--   AES supported
--   AVX supported
--   AVX2 supported
--   AVX512CD not supported
--   AVX512F not supported
--   AVX512ER not supported
--   AVX512PF not supported
--   BMI1 supported
--   BMI2 supported
--   CLFSH supported
--   CMPXCHG16B supported
--   CX8 supported
--   ERMS supported
--   F16C supported
--   FMA supported
--   FSGSBASE supported
--   FXSR supported
--   HLE supported
--   INVPCID supported
--   LAHF supported
--   LZCNT supported
--   MMX supported
--   MMXEXT not supported
--   MONITOR supported
--   MOVBE supported
--   MSR supported
--   OSXSAVE supported
--   PCLMULQDQ supported
--   POPCNT supported
--   PREFETCHWT1 not supported
--   RDRAND supported
--   RDSEED supported
--   RDTSCP supported
--   RTM supported
--   SEP supported
--   SHA not supported
--   SSE supported
--   SSE2 supported
--   SSE3 supported
--   SSE4.1 supported
--   SSE4.2 supported
--   SSE4a not supported
--   SSSE3 supported
--   SYSCALL supported
--   TBM not supported
--   XOP not supported
--   XSAVE supported
-- TBB include: /opt/intel/openvino_2019.1.144/deployment_tools/inference_engine/external/tbb/include
-- TBB Release lib: /opt/intel/openvino_2019.1.144/deployment_tools/inference_engine/external/tbb/lib/libtbb.so
-- TBB Debug lib: /opt/intel/openvino_2019.1.144/deployment_tools/inference_engine/external/tbb/lib/libtbb_debug.so
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/uzel/inference_engine_samples_build
[ 11%] Built target gflags_nothreads_static
[ 96%] Built target ie_cpu_extension
[100%] Built target security_barrier_camera_demo


###################################################

Run Inference Engine security_barrier_camera demo

Run ./security_barrier_camera_demo -d CPU -d_va CPU -d_lpr CPU -i /opt/intel/openvino/deployment_tools/demo/car_1.bmp -m /home/uzel/openvino_models/ir/FP32/Security/object_detection/barrier/0106/dldt/vehicle-license-plate-detection-barrier-0106.xml -m_va /home/uzel/openvino_models/ir/FP32/Security/object_attributes/vehicle/resnet10_update_1/dldt/vehicle-attributes-recognition-barrier-0039.xml -m_lpr /home/uzel/openvino_models/ir/FP32/Security/optical_character_recognition/license_plate/dldt/license-plate-recognition-barrier-0001.xml

[ INFO ] InferenceEngine:
API version ............ 1.6
Build .................. custom_releases/2019/R1.1_28dfbfdd28954c4dfd2f94403dd8dfc1f411038b
[ INFO ] Parsing input parameters
[ INFO ] Capturing video streams from the video files or loading images
[ INFO ] Files were added: 1
[ INFO ]     /opt/intel/openvino/deployment_tools/demo/car_1.bmp
[ INFO ] Number of input image files: 1
[ INFO ] Number of input video files: 0
[ INFO ] Number of input channels: 1
[ INFO ] Display resolution: 1920x1080
[ INFO ] Loading plugin CPU

API version ............ 1.6
Build .................. 23780
Description ....... MKLDNNPlugin
[ INFO ] Loading network files for VehicleDetection
[ INFO ] Batch size is forced to  1
[ INFO ] Checking Vehicle Detection inputs
[ INFO ] Checking Vehicle Detection outputs
[ INFO ] Loading Vehicle Detection model to the CPU plugin
[ INFO ] Loading network files for VehicleAttribs
[ INFO ] Batch size is forced to 1 for Vehicle Attribs
[ INFO ] Checking VehicleAttribs inputs
[ INFO ] Checking Vehicle Attribs outputs
[ INFO ] Loading Vehicle Attribs model to the CPU plugin
[ INFO ] Loading network files for Licence Plate Recognition (LPR)
[ INFO ] Batch size is forced to  1 for LPR Network
[ INFO ] Checking LPR Network inputs
[ INFO ] Checking LPR Network outputs
[ INFO ] Loading LPR model to the CPU plugin
[ INFO ] Start inference
To close the application, press 'CTRL+C' or any key with focus on the output window


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by suryasidd** [comment]
Can you please provide the version of the python library "networkx" that's installed on the system?

**Comment by JohnnyLing** [comment]
networkx version number 2.4. any suggestion? Thanks

**Comment by suryasidd** [comment]
OpenVINO R1.1 doesn't work with networkx 2.3 version. This has been fixed in R3.1. As a workaround can you uninstall networkx and install networkx 2.3 by using `pip3 install networkx==2.3`

**Comment by JohnnyLing** [comment]
thank you. it works by installing networkx 2.3

**Comment by wwbnjsace** [comment]
> Hi, this means that you installed onnxruntime 1.0 python package from pypi. that only use cpu provider available.
> please uninstall that one first using pip uninstall onnxruntime
> 
> when building onnxruntime with openvino from source, please add --update --build arguments to skip tests. then please install the *.whl file that gets created.
> 
> ./build.sh --config RelWithDebInfo --use_openvino VAD-M_FP16 --build_wheel --update --build

my command is " sudo ./build.sh --config RelWithDebInfo --build_wheel --use_openvino CPU_FP32 --parallel --skip_tests --update --build" .but in the end it does not generate any *.whl file in any location
who can tell me why?

**Comment by mesakh123** [comment]
> > Hi, this means that you installed onnxruntime 1.0 python package from pypi. that only use cpu provider available.
> > please uninstall that one first using pip uninstall onnxruntime
> > when building onnxruntime with openvino from source, please add --update --build arguments to skip tests. then please install the *.whl file that gets created.
> > ./build.sh --config RelWithDebInfo --use_openvino VAD-M_FP16 --build_wheel --update --build
> 
> my command is " sudo ./build.sh --config RelWithDebInfo --build_wheel --use_openvino CPU_FP32 --parallel --skip_tests --update --build" .but in the end it does not generate any *.whl file in any location who can tell me why?

I'm trying this repo now, maybe it can help
https://github.com/yas-sim/openvino-ep-enabled-onnxruntime
