### ISSUE TITLE
Lack of reproducibility

### ISSUE THREAD

**Issue by notogawa** [Microsoft/onnxruntime#230]
**Describe the bug**

[This](https://circleci.com/gh/notogawa/test-onnxruntime/7) CircleCI job executes [shufflenet.onnx](https://s3.amazonaws.com/download.onnx/models/opset_8/shufflenet.tar.gz) 2 times with same input, and check differences of these 2 outputs. The job failed by differences. It means the lack of reproducibility.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

Linux (CircleCI, debian stretch container)

- ONNX Runtime installed from (source or binary):

````
pip3 install onnxruntime
Collecting onnxruntime
  Downloading https://files.pythonhosted.org/packages/e6/97/39c630134268a29a7c26f5f1c8fd2f7ff089ccee567cb076087ddf1cb6e0/onnxruntime-0.1.4-cp35-cp35m-manylinux1_x86_64.whl (4.6MB)
    100% |################################| 4.6MB 389kB/s 
Installing collected packages: onnxruntime
Successfully installed onnxruntime-0.1.4
````

- ONNX Runtime version:

0.1.4

- Python version:

3.5.3

- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**

Clone https://github.com/notogawa/test-onnxruntime and register it to CircleCI

**Expected behavior**

Every execution output the same result.

When execute on MacBook Pro (OSX, debian stretch container) and desktop machine (Ubuntu, debian stretch container), it works as i expect.

**Screenshots**

see https://circleci.com/gh/notogawa/test-onnxruntime/7

**Additional context**

**Comment by snnn** [comment]
It's not about reproducibility, the result is totally wrong. Do you mean it works fine on your desktop machine? For me, it is. It always generates the same result.

**Comment by faxu** [comment]
@notogawa are you still able to reproduce this issue with the latest release of onnxruntime?

**Comment by faxu** [comment]
Please reopen if you still need assistance based on the latest release version.
