### ISSUE TITLE
[Build] Can't build python package

### ISSUE THREAD

**Issue by jspkay** [microsoft/onnxruntime#23054]
### Describe the issue

I was unable to build the project as it is. 
I followed [the documentation](https://onnxruntime.ai/docs/extensions/build.html) I exectude `pip instal -e .`
I managed to build the shared library, but not the python package.

Here's the log:

### Target platform

Linux x64

### Build script

I used the python pip build system.

### Error / output

``` > pip install -e .
Obtaining file:///home/spappalardo%40inl34.ec-lyon.fr/builds/onnxruntime
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running egg_info
      writing onnxruntime.egg-info/PKG-INFO
      writing dependency_links to onnxruntime.egg-info/dependency_links.txt
      writing entry points to onnxruntime.egg-info/entry_points.txt
      writing requirements to onnxruntime.egg-info/requires.txt
      writing top-level names to onnxruntime.egg-info/top_level.txt
      error: package directory 'onnxruntime/backend' does not exist
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.```

### Visual Studio Version

_No response_

### GCC / Compiler Version

_No response_

**Comment by tianleiwu** [comment]
See https://onnxruntime.ai/docs/build/ for documentation.

**Comment by jspkay** [comment]
Thank you so much! I manage to solve the building problem! 

But then I have another question: can I install the wheel in a debug mode ? As far as I know, it's impossible to do it with a .whl file

**Comment by tianleiwu** [comment]
> But then I have another question: can I install the wheel in a debug mode ? As far as I know, it's impossible to do it with a .whl file
Yes, you can install debug whl using `pip install onnxruntime*.whl` in the dist folder.
