### ISSUE TITLE
FAIL : LoadLibrary failed with error 126 "" when trying to load "onnxruntime_providers_openvino.dll"

### ISSUE THREAD

**Issue by zyzhang60** [microsoft/onnxruntime#23062]
### Describe the issue

# OS
```
Windows 10 Professional
```

# Visual Studio 17 2022
```
Visual Studio 17 2022
```

# cpp code
```
std::string model_path = "D:/zyzhang60/c++project/yolov8_segment_onnx_in_cpp-master/yolo11l-seg_320x320.onnx";
Env env(OrtLoggingLevel::ORT_LOGGING_LEVEL_ERROR, "yolov8");

Ort::SessionOptions sessionOptions;

OrtOpenVINOProviderOptions openVINOOptions;
openVINOOptions.device_type = "GPU_FP32";
sessionOptions.AppendExecutionProvider_OpenVINO(openVINOOptions);
``` 

# Microsoft.ML.OnnxRuntime.OpenVino.1.20.0
[download from https://github.com/intel/onnxruntime/releases](https://github.com/intel/onnxruntime/releases)
```
$ ls include/
cpu_provider_factory.h  onnxruntime_cxx_api.h     onnxruntime_float16.h         onnxruntime_run_options_config_keys.h      openvino_provider_factory.h
onnxruntime_c_api.h     onnxruntime_cxx_inline.h  onnxruntime_lite_custom_op.h  onnxruntime_session_options_config_keys.h  provider_options.h

$ ls lib/
onnxruntime.dll*  onnxruntime.lib  onnxruntime_providers_openvino.dll*  onnxruntime_providers_shared.dll*
```

# cmake 
```
D:\zyzhang60\c++project\yolov8_segment_onnx_in_cpp-master\build>cmake -DCMAKE_BUILD_TYPE=Release .. -G "Visual Studio 17 2022"
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
--
-- OpenCV_DIR: D:/opencv/build/install
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc17
-- OpenCV STATIC: ON
-- Found OpenCV 4.10.0 in D:/opencv/build/install/x64/vc17/lib
-- You might need to add D:\opencv\build\install\x64\vc17\bin to your PATH to be able to run your applications.
-- OpenCV found: 4.10.0
--
-- Configuring ONNX Runtime
CMake Warning at CMakeLists.txt:93 (message):
  ONNX Runtime version file not found!


-- ONNX Runtime library found: D:/zyzhang60/c++/lib/Microsoft.ML.OnnxRuntime.OpenVino.1.20.0/lib/onnxruntime.lib
-- Configuring done (0.1s)
-- Generating done (0.2s)
-- Build files have been written to: D:/zyzhang60/c++project/yolov8_segment_onnx_in_cpp-master/build
```

# output
```
D:\zyzhang60\c++project\yolov8_segment_onnx_in_cpp-master\build>cmake --build . --config Release && Release\main.exe
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 17.2.1+52cd2da31
版权所有(C) Microsoft Corporation。保留所有权利。

  dnn.vcxproj -> D:\zyzhang60\c++project\yolov8_segment_onnx_in_cpp-master\build\Release\dnn.exe
  main.vcxproj -> D:\zyzhang60\c++project\yolov8_segment_onnx_in_cpp-master\build\Release\main.exe
Exception: C:\Users\Administrator\Documents\jatin_nuget_packages\onnxruntime\onnxruntime\core\session\provider_bridge_ort.cc:1539 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\zyzhang60\c++project\yolov8_segment_onnx_in_cpp-master\build\Release\onnxruntime_providers_openvino.dll"
```

### To reproduce

nothing

### Platform

Windows

### OS Version

windows 10 professional

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.20.0

### ONNX Runtime API

C++

### Architecture

X64

### Execution Provider

OpenVINO

### Execution Provider Library Version

1.20.0

### Is this a quantized model?

Yes

**Comment by RyanUnderhill** [comment]
What version of OpenVino did you install? Unfortunately Windows doesn't easily tell you which DLL dependency couldn't be found, but my guess is that one of the dependencies of onnxruntime_providers_openvino.dll couldn't be loaded. You can try running the 'depends' tool on it to verify what it needs is what you have installed.

**Comment by zyzhang60** [comment]
I've got it covered myself.

**Comment by Lyuye** [comment]
@zyzhang60 Hello, I got same error message when I am trying openvino nuget package and yolo3 sample code, could you please share how you fix your problem?

**Comment by zyzhang60** [comment]
> [@zyzhang60](https://github.com/zyzhang60) Hello, I got same error message when I am trying openvino nuget package and yolo3 sample code, could you please share how you fix your problem?

Of course, no problem. Here's how I fixed it. Please refer to the official websites:

https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html
https://docs.openvino.ai/2024/get-started/configurations/configurations-intel-gpu.html#windows

Follow the steps carefully, and here's the key point: Check your Intel GPU driver and CPU model. You're welcome to take it. You will succeed. Good luck!
