### ISSUE TITLE
[Performance] GPU Clock and Memory Clock become incredibly large when doing inference

### ISSUE THREAD

**Issue by davave1693** [microsoft/onnxruntime#23101]
### Describe the issue

I am writing an application in which several cameras stream are collected and object detection is performed against the frames coming from each stream.

I am working with an onnx model which takes an input batch of (N, 3, 416,416) images, where N is the number of camera streams and return two outputs: an array of bounding boxes (to be postprocessed) and an array of classes for each detected bbox.

I am working with an [NVIDIA GeForce RTX 3070](https://www.nvidia.com/it-it/geforce/graphics-cards/30-series/rtx-3070-3070ti/). Below the specs recorded using [GreenWithEnvy](https://gitlab.com/leinardi/gwe) are recorded:

![Image](https://github.com/user-attachments/assets/d34bcc65-4126-48a4-8e29-9a80575bb019)

When I run inference, everything seems ok, except from the fact that, regardless of the batch size, both the GPU clock and the memory clock saturate. 
For example making inference just once raises the value of gpu clock speed to 1725MHz/2100MHz, while the value of memory clock becomes 6800MHz/7100MHz. moreover, this increase remains for several seconds after inference has actually occurred (about 18 seconds)

Attached below you can find a simulation where a single inference occurs every 20 seconds. You can see the drop in the GPU CLOCK and MEM CLOCK after the 18 seconds I mentioned earlier (again I used [GreenWithEnvy](https://gitlab.com/leinardi/gwe), but i got same results with NVTOP):

![Image](https://github.com/user-attachments/assets/5598f786-d585-4e74-9e18-4697cca676b6)

I am wondering why this occurs, how this behaviour affects the performance, and what can i do to resolve this issue.

Thank You!
Davide!

### To reproduce

```
import onnxruntime as ort
import time

providers += [('TensorrtExecutionProvider',
         {
            'trt_engine_cache_enable' : True,
            'trt_engine_cache_path' : './trt_cache/'
         })]

session = ort.InferenceSession(model.onnx,providers=providers)

while True:

  time.sleep(20)
  
  images = .... numpy array
  
  inputs = {session.get_inputs()[0].name  :images}
  
  result = session.run(inputs)
```

### Urgency

I have to choose the right hardware for a huge project: to optimize costs, I need to choose the GPU that best meets my company needs.

### Platform

Linux

### OS Version

Ubuntu 24.04

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.20.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

TensorRT

### Execution Provider Library Version

10.6.0.26

### Is this a quantized model?

Yes

**Comment by RyanUnderhill** [comment]
The GPU driver is trying to optimize for performance and power usage by dynamically adjusting the clock speeds. This will vary based on the driver settings/GPU BIOS/current temperature/etc. You can override this behavior through the nvidia-smi utility if you want to experiment. It has options like --lock-gpu-clocks and --lock-memory-clocks, plus other options like limiting the max wattage with --power-limit.

https://[docs.nvidia.com/deploy/nvidia-smi/index.html](https://docs.nvidia.com/deploy/nvidia-smi/index.html)

You can try running other cuda apps to see that the behavior is similar, it's not a special onnxruntime behavior.

**Comment by davave1693** [comment]
Thank you @RyanUnderhill ! I'll try to play with GPU options.
