### ISSUE TITLE
[C#] CUDA kernel not supported for some conv2d layers

### ISSUE THREAD

**Issue by BarkenBark** [microsoft/onnxruntime#2313]
**Describe the bug**
When instantiating an InferenceSession using the YoloV3 model obtained from the ONNX Model Zoo ([source](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3)), and using a CUDA provider, I obtain the following warnings:

> 2019-11-04 08:51:18.0946732 [W:onnxruntime:CSharpOnnxRuntime, cuda_execution_provider.cc:1112 onnxruntime::CUDAExecutionProvider::GetCapability] CUDA kernel not supported. Fallback to CPU execution provider for Op type: Conv node name: conv2d_2_0                                                                                                                  2019-11-04 08:51:18.0949392 [W:onnxruntime:CSharpOnnxRuntime, cuda_execution_provider.cc:1112 onnxruntime::CUDAExecutionProvider::GetCapability] CUDA kernel not supported. Fallback to CPU execution provider for Op type: Conv node name: conv2d_5_0                                                                                                                  2019-11-04 08:51:18.0959455 [W:onnxruntime:CSharpOnnxRuntime, cuda_execution_provider.cc:1112 onnxruntime::CUDAExecutionProvider::GetCapability] CUDA kernel not supported. Fallback to CPU execution provider for Op type: Conv node name: conv2d_10_0                                                                                                                 2019-11-04 08:51:18.0962491 [W:onnxruntime:CSharpOnnxRuntime, cuda_execution_provider.cc:1112 onnxruntime::CUDAExecutionProvider::GetCapability] CUDA kernel not supported. Fallback to CPU execution provider for Op type: Conv node name: conv2d_27_0                                                                                                                 2019-11-04 08:51:18.0965944 [W:onnxruntime:CSharpOnnxRuntime, cuda_execution_provider.cc:1112 onnxruntime::CUDAExecutionProvider::GetCapability] CUDA kernel not supported. Fallback to CPU execution provider for Op type: Conv node name: conv2d_44_0

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): Latest NuGet release (1.0.0)
- ONNX Runtime version: 1.0.0
- Python version: -
- Visual Studio version (if applicable): Visual Studio 2019 16.3.6
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: CUDA=10.0, cuDNN=7.6 for 10.0
- GPU model and memory: Nvidia GeForce 940MX 2GB

**To Reproduce**
```C#
int gpuIndex = 0;
var modelPath = "yolov3.onnx";
var session = new InferenceSession(modelPath, SessionOptions.MakeSessionOptionWithCudaProvider(gpuIndex));
```

**Expected behavior**
I do not expect the runtime to fallback to CPU for these convolutional layers.

**Screenshots**
Screenshots of Task Manager showing high CPU utilization and some GPU utilization during repeated inference on the same data. This along with the warnings makes me think that CUDA is used for some layers in the network, but not for the onex listed in the warning messages.
![CpuUtil](https://user-images.githubusercontent.com/23279510/68107378-f81a9100-fee4-11e9-881b-2801dc39cbc1.PNG)
![GpuUtil](https://user-images.githubusercontent.com/23279510/68107452-3d3ec300-fee5-11e9-94d2-bd382675f586.PNG)

**Additional context**
On inspection of the YoloV3 Model in [Netron](https://lutzroeder.github.io/netron/), I can see no real difference between the conv2d layers for which CUDA support fails and the conv2d layers for which it succeeds, other than the property AUTO_PAD being NOTSET for the failing layers (and they have a property "pads" specifying the padding). Furthermore, the failing layers end with an additional "_0" in the names.

**Comment by jywu-msft** [comment]
This is due to asymmetric padding not supported by cudnn.
see
https://github.com/microsoft/onnxruntime/blob/d5c36bfff285eba4a0ef7c6b7dabb5b3bf6c5c2e/onnxruntime/core/providers/cuda/cuda_execution_provider.cc#L1020

**Comment by jywu-msft** [comment]
dup of https://github.com/microsoft/onnxruntime/issues/1961

**Comment by BarkenBark** [comment]
I see. Thank you for the reply
