### ISSUE TITLE
String variable in onnx model built in python are interpreted as bytes in C# onnxruntime

### ISSUE THREAD

**Issue by bball3212** [microsoft/onnxruntime#2315]
Issue: When a onnx model is built in Python with string variables (which are one hot encoded within the onnx pipeline in Python), the outputted model has string tensor types. However, when this model is then imported to run in the onnxruntime in C#, the variable types show up as bytes.

Expected result: Onnxruntime would read the variable as string 

Outputted from python, with fareclass as string:
![image001](https://user-images.githubusercontent.com/46941037/68141203-b1cc2e80-fef2-11e9-85b8-9c1a275b6f5a.png)

Same model read in c#, with inputtype showing up as byte
![image004](https://user-images.githubusercontent.com/46941037/68141231-bbee2d00-fef2-11e9-95aa-708823ec0ec8.jpg)

**Comment by jignparm** [comment]
Thanks for posting the type mismatch. The ElementType should be string, not byte[]. Fixed by  #2348.
