### ISSUE TITLE
[C#] cannot convert from 'System.Numerics.Tensors.Tensor<T>' to 'Microsoft.ML.OnnxRuntime.Tensors.Tensor<T>'

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#2318]
**Describe the bug**
Cannot pass a created tensor to create named onnx value

**Urgency**
Need to upgrade current models, but simple upgrade of ORT is not enough

**To Reproduce**

```C#
        private NamedOnnxValue[] ToInput<T>(TensorArray<T> image)
        {
            var tensor = new DenseTensor<T>(new Memory<T>(image.Data), new int[] { image.Data.Length });
            return new NamedOnnxValue[] { NamedOnnxValue.CreateFromTensor<T>(_inputName, tensor.Reshape(image.Dimension)) };
        }
```

**Expected behavior**
Should be able to convert tensors

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

`System.Numerics.Tensor` version is `v0.1.0` and there is no update for it

**Comment by dashesy** [comment]
I changed

```C#
using System.Numerics.Tensors;
```

To 

```C#
using Microsoft.ML.OnnxRuntime.Tensors;
```

And this error was fixed. No idea what is the correct pattern and why

**Comment by jignparm** [comment]
@dashesy `Microsoft.ML.OnnxRuntime.Tensors` is the correct namespace to use going forward.

 It's the same code as `System.Numerics.Tensors`, but due to release timelines (and to stabilize the API for ORT v1.0), the Tensor code was moved to the Microsoft.ML.OnnxRuntime  namespace.

**Comment by vpenades** [comment]
Maybe Microsoft.ML.OnnxRuntime.Tensors should have an implicit conversion from System.Numerics.Tensors?
