### ISSUE TITLE
[Documentation] CoreML API does not match latest release

### ISSUE THREAD

**Issue by henryruhs** [microsoft/onnxruntime#23228]
### Describe the documentation issue

From my observation, the new API is partial working (ModelCacheDirectory seems not present) using the **nightly builds**.

When using **onnxruntime==1.20.1** it does not even report invalid options.

Side node: I could not install the nightly builds as it requested a password for peer-dependencies that seem not to be hosted on your registry. Only worked using `--no-deps`.

### Page / URL

https://onnxruntime.ai/docs/execution-providers/CoreML-ExecutionProvider.html#configuration-options-new-api

**Comment by wejoncy** [comment]
Please build onnxruntime package by yourself for now to make it work if it's urgent.

This commit includes ModelCaching.
https://github.com/microsoft/onnxruntime/commit/86870114eb14c459533034a1dd6f9b722cea0f9f

**Comment by henryruhs** [comment]
I understand your desire to minimize new issues, given the workload you already have. However, the problem remains unresolved unless the documentation is explicitly marked as "nightly."

Thanks for working on the CoreML EP.
