### ISSUE TITLE
Python documentation doesn't load style

### ISSUE THREAD

**Issue by HarryVancao** [microsoft/onnxruntime#2323]
**Describe the bug**
When ONNX Runtime 1.0 was released, it seems that the documentation page for the python API is replaced by this page: https://microsoft.github.io/onnxruntime/

I found the updated documentation location to be here: https://microsoft.github.io/onnxruntime/python/index.html

However, this page doesn't have any styling and looks like plaintext with links. This makes the API reference harder to use. 

**Urgency**
The documentation is still usable, just not easy on the eyes at all

**Comment by pranavsharma** [comment]
Yes, the team is aware of this issue. cc @faxu @xadupre

**Comment by jywu-msft** [comment]
The issue has been fixed.

**Comment by HarryVancao** [comment]
The documentation looks like it is back. I will close this issue.
