### ISSUE TITLE
Are there any plans to support mobile GPU? 

### ISSUE THREAD

**Issue by suphy2009** [microsoft/onnxruntime#2331]
Currently, onnxruntime has little support for mobile GPU. Are there any plans to support Arm GPU and Qualcomm GPU by accelerating engine (such as Arm NN or SNPE) or OpenCL?

**Comment by pranavsharma** [comment]
cc @manashgoswami @jywu-msft

**Comment by jywu-msft** [comment]
Yes, this is being considered. Will update once there are more concrete plans to share.

**Comment by suphy2009** [comment]
@jywu-msft Thank you for your reply.
Can you share how it will be supported? By accelerating engine (such as Arm NN or SNPE) or implement OpenCL op，or something else?

**Comment by daquexian** [comment]
If you are using Android you can try NNAPI EP
