### ISSUE TITLE
ORT -  segmentation fault on Linux, when using Cast(to=string) operator

### ISSUE THREAD

**Issue by jignparm** [microsoft/onnxruntime#2338]
**Describe the bug**
The same model scores fine in windows, but fails on Linux.

**Urgency**
Should work

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): Official package from Pypi
- ONNX Runtime version: V 1.0
- Python version: 3.7

- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**

Run the code snippet below using this tiny model [test_cast_back_to_back_non_const_mixed_types_origin.zip](https://github.com/microsoft/onnxruntime/files/3817508/test_cast_back_to_back_non_const_mixed_types_origin.zip)

``` python

import onnxruntime as rt
import numpy as np



model_path="test_cast_back_to_back_non_const_mixed_types_origin.onnx"

inputs = {'u': np.array([ 1.6, -0.6, -0.5, -1.0, 0.8, -2.3], dtype=np.float32).reshape((1,2,3))}
outputs = ['res', 'res2', 'res3']
m = rt.InferenceSession(model_path)
results = m.run(outputs, inputs)
print(results)
```

**Expected behavior**
Should print the following

``` python
[array([[[ 1,  0,  0],
        [-1,  0, -2]]], dtype=int64), array([[[ 1,  0,  0],
        [-1,  0, -2]]], dtype=int64), array([[[1, 0, 0],
        [1, 0, 1]]], dtype=int64)]

```

**Screenshots**
N/A

**Additional context**
N/A

**Comment by pranavsharma** [comment]
This is weird. I built a release binary (on Linux) based on the 1.0 branch and could not repro the issue. However the binary that was shipped exhibits the issue.
