### ISSUE TITLE
expand Matmulinteger and ConvInteger to support int8*int8

### ISSUE THREAD

**Issue by litaozijin** [microsoft/onnxruntime#2339]
Onnx official protocal claims that ‘MatMulInter’(https://github.com/onnx/onnx/blob/master/docs/Operators.md#MatMulInteger) 
And ‘ConvInteger’(https://github.com/onnx/onnx/blob/master/docs/Operators.md#ConvInteger) operator support that  input is uint8 or int8 and output is int32.However i find that onnxruntime(version 1.0.0) only supplies uint8* uint8 and uint8* int8 ‘MatMulInteger’ in ‘core/provider/cpu/math/matmul_integer.cc’. Meanwhile, ‘ConvInteger’ only supplies uint8* uint8 in ‘core/provider/cpu/nn/conv_integer.cc’
In my application, we have implemented ‘MatMulInteger’ quantization of int8* int8 and serialized this model to onnx with opset=11. But it does not work and it thorws an error after load and run this model in onnxruntime. We find the reason leading to this error is that int8* int8 ‘MatMulInteger’ is not implemented.
I wonder why the popular schema of int8* int8 ‘MatMulInteger’ is not implemented?
Is there a plan to expand Matmulinteger and ConvInteger to support int8* int8?Whether can I commit an implement code of int8*int8 of these which work accurately but not enough efficiently ?

**Comment by askhade** [comment]
@litaozijin : onnxruntime only implements uint8 * uint8 and uint8 * int8 as these 2 are supported by ARM and VNNI based x86 architectures respectively. What is your reason for using int8 * int8? Which hardware do you intend to run this model on?

Right now we are finishing optimized kernel implementations for uint8*uint8 and uint8*int8. ConvInteger uint8 * int8 is still in progress and will be added soon. However there is no immediate  plan add int8*int8 kernels as we do not have a strong scenario to support this case.

**Comment by litaozijin** [comment]
There is a comand named 'vmulq_s8' whose input args are  int8 and int8 on ARM,.In my scenario we usually use the command with zero-point =0 and input-type = int8  to reduce the computation quantity  in quantize and dequantize phase.

**Comment by askhade** [comment]
@litaozijin : right now we are prioritizing supporting uint8, uint8 for ARM and uint8, int8 for x86 in ORT CPU execution provider. I need to check whether there are any other EPs (execution providers) which support the combination you are interested in. 
ONNX is an open platform and supports variety of backends. These different combinations were added in ONNX to make sure different backends have the flexibility to enable the scenarios which make most sense to them. 
ORT does best effort to enable as many data types as it can from the onnx spec. In this particular case it is more complicated to enable all combinations. Right now the focus is to first enable uint8, int8 for convolutions and then based on user demand enable int8, int8

**Comment by mayeut** [comment]
@askhade,

TensorRT only supports int8 (with 0 zero-point, i.e symmetric) for now (https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html#layers-precision-matrix). That's at least one other EP that supports this combination.

**Comment by bxing-groq** [comment]
We'd like to test the accuracy of `int8` quantization on the CPU with ONNX Runtime vs. on our custom hardware. With the state we're currently in, we can't really measure the accuracy on the CPU...is that correct? Do we know any deficiency with our `int8` quantization that might result in very low accuracy? Running U8S8 (unsigned activation, signed weight) quantization on the CPU seems fine.
