### ISSUE TITLE
expand to support ‘gemm’ quantization

### ISSUE THREAD

**Issue by litaozijin** [microsoft/onnxruntime#2340]
quantize.py under the tool directory has supported quantization of operators such as matmul and conv, whether there is a plan to support ‘gemm’?

**Comment by jywu-msft** [comment]
the script supports the quantized operators that are defined in [ONNX operator spec](https://github.com/onnx/onnx/blob/master/docs/Operators.md). 
see also: https://github.com/onnx/onnx/wiki/Quantization-Support-In-ONNX
currently ONNX only supports a small number of quantized operators.
please file an issue under https://github.com/onnx/onnx
