### ISSUE TITLE
How do I input a variable sequence feature into the LSTM network in c++ onnxruntime?

### ISSUE THREAD

**Issue by cuixing158** [microsoft/onnxruntime#2341]
I'm always frustrated how to correctly input a two-dimensional variable feature matrix to an LSTM/bidirectional LSTM network in c++, but I successfully ran my lstm onnx model in python-onnxruntime, the input is [seq_length, batch_size, input_size].

**System information**
- ONNX Runtime version (you are using):python-onnxruntime:0.5 c++: onnxruntime-gpu 0.5
-OS: win10 x64
-ONNX Runtime installed from (source or binary): binary
visual studio2015

**Describe the solution you'd like**
My LSTM model input should be [varargin,1,1024] variable size matrix, and when I randomly designed a matrix to be passed into the network, it crashed, my code is like :
```c++
int sz[] = { 16, 1, 1024 };
inputblob = Mat(3, sz, CV_32FC1, Scalar::all(1)); // randomly designed a matrix
// create input tensor object from data values
Ort::AllocatorInfo allocator_info = Ort::AllocatorInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
Ort::Value input_tensor = Ort::Value::CreateTensor<float>(allocator_info, inputblob.ptr<float>(), input_tensor_size, input_node_dims.data(), 3);
assert(input_tensor.IsTensor());

// score model & input tensor, get back output tensor
auto output_tensors = session.Run(Ort::RunOptions{ nullptr }, input_node_names.data(), &input_tensor, 1, output_node_names.data(), 1); // crash !!!
```
![微信截图_20191107173641](https://user-images.githubusercontent.com/22857777/68377526-86ad3d80-0185-11ea-8acb-cfd63adf422e.png)
![onnx](https://user-images.githubusercontent.com/22857777/68377664-c7a55200-0185-11ea-88df-ca83946cb8c1.png)

**Describe alternatives you've considered**
My python-onnxruntime similar code is as follows:
```python
sess = rt.InferenceSession(LSTMmodel)
input_name = sess.get_inputs()[0].name
inputFeature = np.ones((16,1,1024),dtype=np.float32) #验证与matlab结果一致！耗时50ms左右也一致
pred_onnx = sess.run(None, {input_name: inputFeature}) // ok!
```

How can I use lstm correctly in C++?
Thank you

**Additional context**
reference:https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp

**Comment by skottmckay** [comment]
Are you able to share the model?

**Comment by cuixing158** [comment]
Sorry, I will reply to the information until now, my model is [here]( https://drive.google.com/open?id=1Jo0MbSfUIjkqkhU2Pj2GdVdSsgpXMUiT).

**Comment by skottmckay** [comment]
The model in the first link has a concrete shape for the graph input as the dimensions are [1, 1, 1024]. i.e. the first dimension has a set value of 1, and not the symbolic name of 'varagin' that you said it should.

How was the model created?

**Comment by skottmckay** [comment]
FYI: the latest onnxruntime version checks input validity and fails with your python:

```
[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: sequence for the following indices
index: 0 Got: 16 Expected: 1
Please fix either the inputs or the model.
```

**Comment by cuixing158** [comment]
Thank you very much for your reply, my first linked onnx model is the second link model exported in matlab. The export converter can be found at [here](https://ww2.mathworks.cn/matlabcentral/fileexchange/67296-deep-learning-toolbox-converter-for-onnx -model-format)
