### ISSUE TITLE
Does the Nuphar Execution Provider support arm or aarch64 cpu?

### ISSUE THREAD

**Issue by suphy2009** [microsoft/onnxruntime#2342]
**Describe the bug**
I enabled nuphar EP to compile onnxrumtime on tx2，and the complied command:
`./build.sh --use_tvm --use_llvm --llvm_path=/usr/local/lib/llvm/lib/cmake/llvm --use_nuphar --build_shared_lib --config=RelWithDebInfo --parallel --use_tensorrt --use_cuda --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu --tensorrt_home /usr/lib/aarch64-linux-gnu`

However, I encountered the following compile error message：
[  8%] Building CXX object external/tvm/CMakeFiles/tvm.dir/src/arithmetic/bound_deducer.cc.o
[  8%] Built target gtest
Scanning dependencies of target onnxruntime_nuphar_extern
[  8%] Building CXX object CMakeFiles/onnxruntime_nuphar_extern.dir/home/nvidia/Work/onnxruntime/onnxruntime/core/providers/nuphar/extern/igemv_avx2.cc.o
cc1plus: error: unknown value ‘broadwell’ for -march
CMakeFiles/onnxruntime_nuphar_extern.dir/build.make:62: recipe for target 'CMakeFiles/onnxruntime_nuphar_extern.dir/home/nvidia/Work/onnxruntime/onnxruntime/core/providers/nuphar/extern/igemv_avx2.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_nuphar_extern.dir/home/nvidia/Work/onnxruntime/onnxruntime/core/providers/nuphar/extern/igemv_avx2.cc.o] Error 1
CMakeFiles/Makefile2:1008: recipe for target 'CMakeFiles/onnxruntime_nuphar_extern.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_nuphar_extern.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**System information**
- TX2 Ubuntu 18.02:
- ONNX Runtime source tag: v1.0.0 
- GCC/Compiler version (if compiling from source): 7.4.0
- LLVM version: 9.0.0
- CUDA/cuDNN version: cuda-10.0

**To Reproduce**
N/A

**Expected behavior**
Compile successfully

**Screenshots**
N/A

**Additional context**
N/A

**Comment by jywu-msft** [comment]
nuphar is for x86 platform, not arm. (the errors you see are related to enabling optimizations for avx2 instruction set on x86_64)

**Comment by KeDengMS** [comment]
It is in our plan to expand nuphar to support more hardware platforms including ARM. Please stay tuned for our updates, and any contributions are welcome.

**Comment by suphy2009** [comment]
@KeDengMS Thank you for your reply. Look forward to AE can support more hardware platforms.
