### ISSUE TITLE
Help: dealing with uint8 and int64 types in java for inference

### ISSUE THREAD

**Issue by SiR0N** [microsoft/onnxruntime#2343]
Hello, 
I just want some support to inference my model.

I transformed one model I found on the internet to ONNX  and I want to use the  0.4 runtime by a C API (I already tested the model with python and it works). I compiled the runtime for Android so I use JNI in between and I have to take care of variables types. 

My wondering is how to feed and get the result of the model, the input is an image represented as: `type: uint8[1024,2048,3]` and output is another image: `type: int64[1,1024,2048,1] `  

Looking at the java and C primitives, I think I should use long (64 bits) to fetch the data and byte (8 bits) to feed the model.
 
The output format would fit nice but I wonder if the input would work as it expects an integer and not a byte. 

Any tips to inference this model?  
[ICNET_0.5.onnx.zip](https://github.com/microsoft/onnxruntime/files/3819517/ICNET_0.5.onnx.zip)

**Comment by pranavsharma** [comment]
You can use OrtCreateTensorWithDataAsOrtValue to feed the data. The input size would be ```3*1024*2048*sizeof(uint8_t)```. Here's an [example](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/InferenceTestCapi.cpp#L52)

**Comment by sgreene** [comment]
Have you checked out this #2215 ? It's a full Java API for onnxruntime and uses JNI. It's also based on 1.0.0.
