### ISSUE TITLE
How to output the middle layer?

### ISSUE THREAD

**Issue by zhoujinhai** [microsoft/onnxruntime#2344]
My model have 106 layers, I want to check the outputs of every layer,  How to get the model middle layer outputs when I predict . the code just get the last outputs.
```python
pred_onnx = sess.run(None, {input_name: img_data})
```

**Comment by hariharans29** [comment]
Can you please check these  - 

https://github.com/microsoft/onnxruntime/issues/2205

https://github.com/microsoft/onnxruntime/issues/2119

**Comment by zhoujinhai** [comment]
@hariharans29 thanks
