### ISSUE TITLE
resnet50 sample over openvino VPU caused numpy assertion error

### ISSUE THREAD

**Issue by JohnnyLing** [microsoft/onnxruntime#2353]
**Describe the bug**
run resnet50 python sample code. by default onnxruntime over openvino VPU execution provider, it hits numpy assertion error. I don't hit this problem by setting onnexruntime over CPU execution provider(session.set_providers(['CPUExecutionProvider'])). BTW, the openvino version is 2019.3.376.

Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> # cd /git/onnx-docker/onnx-ecosystem/inference_demos
... 
>>> import numpy as np    # we're going to use numpy to process input and output data
>>> import onnxruntime    # to inference ONNX models, we use the ONNX Runtime
>>> import onnx
>>> from onnx import numpy_helper
>>> import urllib.request
>>> import json
>>> import time
>>> import matplotlib.pyplot as plt
>>> from PIL import Image, ImageDraw, ImageFont
>>> 
>>> # onnx_model_url = "https://s3.amazonaws.com/onnx-model-zoo/resnet/resnet50v2/resnet50v2.tar.gz"
... # imagenet_labels_url = "https://raw.githubusercontent.com/anishathalye/imagenet-simple-labels/master/imagenet-simple-labels.json"
... # urllib.request.urlretrieve(onnx_model_url, filename="resnet50v2.tar.gz")
... # urllib.request.urlretrieve(imagenet_labels_url, filename="imagenet-simple-labels.json")
... 
>>> 
>>> test_data_dir = 'resnet50v2/test_data_set'
>>> test_data_num = 3
>>> 
>>> import glob
>>> import os
>>> 
>>> inputs = []
>>> for i in range(test_data_num):
...     input_file = os.path.join(test_data_dir + '_{}'.format(i), 'input_0.pb')
...     tensor = onnx.TensorProto()
...     with open(input_file, 'rb') as f:
...         tensor.ParseFromString(f.read())
...         inputs.append(numpy_helper.to_array(tensor))
... 
602128
602128
602128
>>> 
>>> print('Loaded {} inputs successfully.'.format(test_data_num))
Loaded 3 inputs successfully.
>>>         
... # Load reference outputs
... 
>>> 
>>> ref_outputs = []
>>> for i in range(test_data_num):
...     output_file = os.path.join(test_data_dir + '_{}'.format(i), 'output_0.pb')
...     tensor = onnx.TensorProto()
...     with open(output_file, 'rb') as f:
...         tensor.ParseFromString(f.read())    
...         ref_outputs.append(numpy_helper.to_array(tensor))
...         
... 
4010
4010
4010
>>> print('Loaded {} reference outputs successfully.'.format(test_data_num))
Loaded 3 reference outputs successfully.
>>> 
>>> 
>>> session = onnxruntime.InferenceSession('resnet50v2/resnet50v2.onnx', None)
mo_path = /opt/intel/openvino_2019.3.376/deployment_tools/model_optimizer
[17:08:39.1890][2794]I[ClientManager.cpp:159] client(id:14) registered: clientName=HDDLPlugin socket=2
[17:08:42.2504][2795]I[GraphManager.cpp:490] Load graph success, graphId=13 graphName=optimized_model
>>> session.get_providers()
['OpenVINOExecutionProvider', 'CPUExecutionProvider']
>>> 
>>> # session.set_providers(['CPUExecutionProvider'])
... # session.set_providers(['OpenVINOExecutionProvider'])
... 
>>> input_name = session.get_inputs()[0].name  
>>> print('Input Name:', input_name)
Input Name: data
>>> 
>>> outputs = [session.run([], {input_name: inputs[i]})[0] for i in range(test_data_num)]
>>> 
>>> print('Predicted {} results.'.format(len(outputs)))
Predicted 3 results.
>>> for ref_o, o in zip(ref_outputs, outputs):
...     np.testing.assert_almost_equal(ref_o, o, 4)
...     
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 584, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 1029, in assert_array_almost_equal
    precision=decimal)
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 841, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 4 decimals

Mismatch: 100%
Max absolute difference: 0.7852783
Max relative difference: 10.759511
 x: array([[-2.2073e+01, -8.3846e+00, -1.0673e+01, -1.2551e+01, -1.1905e+00,
        -9.7782e+00, -4.1260e+00,  7.0238e+00,  8.3684e+00, -3.9406e+00,
        -2.3944e+01, -1.6561e+01, -1.3669e+01, -1.0238e+01, -2.3566e+01,...
 y: array([[-2.1938e+01, -8.3594e+00, -1.0617e+01, -1.2359e+01, -9.9023e-01,
        -9.6797e+00, -4.1680e+00,  7.0820e+00,  8.4922e+00, -3.9688e+00,
        -2.3797e+01, -1.6625e+01, -1.3742e+01, -1.0195e+01, -2.3438e+01,...
>>> print('ONNX Runtime outputs are similar to reference outputs!')
ONNX Runtime outputs are similar to reference outputs!
>>> 
>>> 
>>> def load_labels(path):
...     with open(path) as f:
...         data = json.load(f)
...     return np.asarray(data)
... 
>>> 
>>> def preprocess(input_data):
...     img_data = input_data.astype('float32')
...     img_data = img_data.reshape(1, 3, 224, 224)
...     mean_vec = np.array([0.485, 0.456, 0.406])
...     stddev_vec = np.array([0.229, 0.224, 0.225])
...     norm_img_data = np.zeros(img_data.shape).astype('float32')
...     for i in range(img_data.shape[0]):
...         norm_img_data[i,:,:] = (img_data[i,:,:]/255 - mean_vec[i]) / stddev_vec[i]
...     return norm_img_data
... 
>>> 
>>> def softmax(x):
...     x = x.reshape(-1)
...     e_x = np.exp(x - np.max(x))
...     return e_x / e_x.sum(axis=0)
... 
>>> 
>>> def postprocess(result):
...     return softmax(np.array(result)).tolist()
... 
>>> 
>>> labels = load_labels('imagenet-simple-labels.json')
>>> image = Image.open('images/dog.jpg')
>>> print("Image size: ", image.size)
Image size:  (224, 224)
>>> plt.axis('off')
(0.0, 1.0, 0.0, 1.0)
>>> display_image = plt.imshow(image)
>>> image_data = np.array(image).transpose(2, 0, 1)
>>> input_data = preprocess(image_data)
>>> 
>>> 
>>> start = time.time()
>>> raw_result = session.run([], {input_name: input_data})
>>> end = time.time()
>>> res = postprocess(raw_result)
>>> 
>>> inference_time = np.round((end - start) * 1000, 2)
>>> idx = np.argmax(res)
>>> 
>>> print('========================================')
========================================
>>> print('Final top prediction is: ' + labels[idx])
Final top prediction is: Golden Retriever
>>> print('========================================')
========================================
>>> 
>>> print('========================================')
========================================
>>> print('Inference time: ' + str(inference_time) + " ms")
Inference time: 66.02 ms
>>> print('========================================')
========================================
>>> 
>>> sort_idx = np.flip(np.squeeze(np.argsort(res)))
>>> print('============ Top 5 labels are: ============================')
============ Top 5 labels are: ============================
>>> print(labels[sort_idx[:5]])
['Golden Retriever' 'Labrador Retriever' 'Otterhound' 'Vizsla'
 'Standard Poodle']
>>> print('===========================================================')
===========================================================
>>> 
>>> plt.axis('off')
(-0.5, 223.5, 223.5, -0.5)
>>> display_image = plt.imshow(image)
>>>

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: latest code build from github branch
- Python version: 3.6.8
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by jywu-msft** [comment]
@suryasidd , @smkarlap can you guys take a look? thanks.

**Comment by suryasidd** [comment]
We are looking into it. Once we are able to reproduce this, I will respond with comments here.

**Comment by suryasidd** [comment]
Hey @JohnnyLing we were able to reproduce this bug and debug it. As you are running the model on HDDL, openvino internally converts the input from FP32 to FP16, does the computation and when producing the output it will convert it back to FP32. Because of this, we cannot compare the expected FP32 values directly as there will be some accuracy loss. We are going to add model tests for FP16 in the future but for now i suggest we look at the labels and see if the output is correct instead of the raw output numbers themselves.

**Comment by JohnnyLing** [comment]
@suryasidd do you mean the output is still correct if just ignoring the assertion error? If so, I think we can close this question.

**Comment by suryasidd** [comment]
Yes the output is correct. Because in that assertion, exact values are being checked it is failing. But the output of the model is correct. Classification is being done properly.
