### ISSUE TITLE
Mac OSX build in PyPi targets OSX 10.14

### ISSUE THREAD

**Issue by kkaehler** [microsoft/onnxruntime#2354]
**Describe the bug**
Prior versions targeted 10.6+ (e..g `onnxruntime-0.5.0-cp36-cp36m-macosx_10_7_x86_64.whl`) but the for _1.0_ only 10.14 is targeted (e.g. `onnxruntime-1.0.0-cp36-cp36m-macosx_10_14_x86_64.whl`). Some of us aren't that cutting edge - is there any way to push a build similar to the prior releases? Building from source is a bit of a pain, but an ok workaround.

[0.5.0 Build](https://pypi.org/project/onnxruntime/0.5.0/#files)
[1.0 Build](https://pypi.org/project/onnxruntime/1.0/#files)

**Urgency**
Low.

**System information**
- Mac OSX 10.13.6
- Python 3.6.5

**Comment by snnn** [comment]
We built it on 10.14.
We got the machine from:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops

@kkaehler  Is it possible to target 10.6 even the build was running on 10.14?

**Comment by jywu-msft** [comment]
https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html

**Comment by cchung100m** [comment]
Hi @snnn @jywu-msft 

I second that and it would be great if we can use `pip3 install onnxruntime==1.0` for `macOS 10.6+`

many thanks,

### System information
```
Mac OSX 10.12.6
Python 3.6.5
```
