### ISSUE TITLE
[DirectML] Access violation writing location

### ISSUE THREAD

**Issue by stefanpantic** [microsoft/onnxruntime#2378]
**Describe the bug**
I'm trying to create a `Ort::Session` that uses the DML provider but I keep getting this error every time:
```
Exception thrown at 0x00007FF98C667E50 (directml.dll) in ONNXPlayground.exe: 0xC0000005: Access violation writing location 0x00007FF971E74950.
```
I build the `onnxruntime` from source with DML support using the provided guide.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: latest (1.0.0)
- Python version: N/A
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source): `Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x64`
- CUDA/cuDNN version: N/A
- GPU model and memory: GTX 1080Ti

**To Reproduce**
```
Ort::SessionOptions ort_session_options;
OrtSessionOptionsAppendExecutionProvider_DML(ort_session_options, id);
m_session = Ort::Session(m_env, L"densenet121.onnx", ort_session_options);
```

**Expected behavior**
I should be able to create a session that runs with the DML provider

**Screenshots**
N/A

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by pranavsharma** [comment]
cc @fdwr @adtsai

**Comment by fdwr** [comment]
@stefanpantic : Which version of the densenet file are you using? (opset 3, 6, 7, 8, 9?) https://github.com/onnx/models/tree/master/vision/classification/densenet-121

I tried a quick local repro via WinMLRunner.exe (https://github.com/microsoft/Windows-Machine-Learning/releases) using "WinMLRunner.exe -gpu -model densenet121.onnx" on my AMD Radeon R7 200 Series, which passed. So I want to be user to use the same exact model file. Thanks.

**Comment by stefanpantic** [comment]
Hi, I'm using opset 8

**Comment by fdwr** [comment]
@stefanpantic : Will look into it. 👍

**Comment by stefanpantic** [comment]
Have you tried doing a repro without using the WinMLRunner?

**Comment by patlevin** [comment]
Maybe this helps: I got the same error when not copying the DirectML.dll from the ONNX runtime build directory to the app's binary folder.
The version doesn't seem to be compatible with the version installed by the OS.
Copying the DirectML.dll from the ONNX runtime's build output solved the issue for me.

**Comment by stefanpantic** [comment]
@nikola-j @dulex123

**Comment by fdwr** [comment]
@stefanpantic : Does patlevin's advice solve the AV, copying ORT's version of DML.dll to your application folder? The DML version that comes with ORT is a preview and has more functionality than the OS version (granted, I would not expect a read AV, but I also don't expect it to work).

**Comment by goloskokovic** [comment]
@fdwr : when running  WinMLRunner.exe -gpu -model candy.onnx with model from fns_candy_style_transfer I get error:
Creating session [FAILED]
onecoreuap\windows\windowsai\engine\dmlexecutionprovider\src\executionprovider.cpp(123)\Windows.AI.MachineLearning.dll!00007FF9DEB1ED0D: (caller: 00007FF9DEB21002) Exception(1) tid(5304) 8007007F The specified procedure could not be found.

**Comment by goloskokovic** [comment]
it works if I add directml.dll in the same folder as WinMLRunner.exe

**Comment by goloskokovic** [comment]
is there prebuilt onnxruntime.dll with DML provider ? Running WinMLRunner.exe skips onnxruntime.dll as it calls directly DirectML.dll

**Comment by goloskokovic** [comment]
@fdwr : I had to copy custom_op_library.dll (with directml.dll) into the folder. Also you you must call DisableMemPattern and SetSessionExecutionMode functions:

`Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_DML(session_options, 0));`
`session_options.DisableMemPattern();`
`session_options.SetExecutionMode(ExecutionMode::ORT_SEQUENTIAL);`
`session_ = Ort::Session(env, L"model.onnx", session_options);`
