### ISSUE TITLE
Invalid ORT_ENFORCE check in nn pool op provider

### ISSUE THREAD

**Issue by atp798** [microsoft/onnxruntime#2384]
**Describe the bug**
There is an invalid ORT_ENFORCE check in
onnxruntime/onnxruntime/core/providers/cpu/nn/pool_attributes.h:
SetOutputSize: Line 93~94
The code is:
```c++
std::vector<int64_t> SetOutputSize(const TensorShape& input_shape,
                                     int64_t output_channel,
                                     std::vector<int64_t>* actual_pads) const {
    ORT_ENFORCE(input_shape.Size() > 0 || input_shape[0] == 0,
                "Invalid input shape. Only N can be zero. Got:", input_shape);
```
According to the implementation of TensorShape,
```cpp
class TensorShape : private std::vector<int64_t> ;

/**
 * Return the total number of elements. Returns 1 for an empty (rank 0) TensorShape.
 */
int64_t TensorShape::Size() const {
  size_t arraySize = size();
  int64_t size = SizeHelper(0, arraySize);
  //should we cache the size? as multiple operation may be expensive.
  return size;
}

int64_t TensorShape::SizeHelper(size_t start, size_t end) const {
  // Must return 1 for an empty sequence
  int64_t size = 1;
  for (size_t i = start; i < end; i++) {
    if ((*this)[i] < 0) return -1;
    size *= (*this)[i];
  }
  return size;
}
```
 it's member func Size() will always return a number no less than 1 even through it is empty, 
thus condition judgement will always return true. 
Even when the check of input_shape.Size()>0 failed, 
the access of input_shape[0] would cause segment fault.

The remark is also confusing, 'Only N can be zero', does it mean 'Only N can not be zero'?

**Comment by yuslepukhin** [comment]
The problem seems to be benign at present because in all of the places where the function is used there are incoming Tensor ORT_ENFORCE where it checks that the number of dimensions is greater than zero. I will fix this though.
@atp798 Do you have a specific example where this causes a crash?

**Comment by yuslepukhin** [comment]
The problem seems to be widespread due to https://github.com/microsoft/onnxruntime/pull/2217

**Comment by pranavsharma** [comment]
input_shape.Size() can return -1 as well to represent symbolic shapes. Check tensor_shape.cc.

**Comment by skottmckay** [comment]
Size() returns 1 if there are no dims. It only returns 0 if one or more dims have a value of 0.

**Comment by atp798** [comment]
> The problem seems to be benign at present because in all of the places where the function is used there are incoming Tensor ORT_ENFORCE where it checks that the number of dimensions is greater than zero. I will fix this though.
> @atp798 Do you have a specific example where this causes a crash?

Sorry, I haven't got one yet. I just read the code and find this.

**Comment by skottmckay** [comment]
> input_shape.Size() can return -1 as well to represent symbolic shapes. Check tensor_shape.cc.

Although in this case it's calculating an output size, so the shape would be concrete with no symbolic dimensions.

**Comment by skottmckay** [comment]
@atp798 do you still think there's an issue?

If there are no dims in the shape it represents a scalar, so Size() returns 1.
If there are dims, at this point in execution there will be no symbolic dimensions so the value returned by Size() will not be negative, and generally will be > 0. 
The edge case this check is handling is when a dimension has a value of 0, leading to Size() returning zero. This can happen for example if the first dimension represents the number of matches from a NonZero node. If that happens we know there are dimensions though, so accessing input_shape[0] is safe.

**Comment by atp798** [comment]
> @atp798 do you still think there's an issue?
> 
> If there are no dims in the shape it represents a scalar, so Size() returns 1.
> If there are dims, at this point in execution there will be no symbolic dimensions so the value returned by Size() will not be negative, and generally will be > 0.
> The edge case this check is handling is when a dimension has a value of 0, leading to Size() returning zero. This can happen for example if the first dimension represents the number of matches from a NonZero node. If that happens we know there are dimensions though, so accessing input_shape[0] is safe.

No, I've got it.  Thank you & sorry for my carelessness.
