### ISSUE TITLE
Support non-tensor output type in onnxruntime server

### ISSUE THREAD

**Issue by Joldnine** [microsoft/onnxruntime#2385]
**Is your feature request related to a problem? Please describe.**
When we host a converted lightgbm onnx model in server, it will have the issue `ONNX Runtime Status Code: 9. Don't support Non-Tensor values`. But an ONNX model converted from lightgbm always has non-tensor type OUTPUT as by default converted lightgbm onnx models produce the output in sequence type.

**System information**
- onnxruntime==1.0.0
- onnxruntime server (Beta)

**Describe the solution you'd like**
Non-tensor type of output should be supported in onnxruntime server.

**Describe alternatives you've considered**
Convertion of lightgbm onnx models in onnxmltools provides the option that the output can be tensor type.

**Additional context**
OUTPUTS format of a sample ONNX model converted from lightgbm which is not tensor type but in sequence:
![image](https://user-images.githubusercontent.com/33798862/68733527-eab28480-0611-11ea-9876-46d9494eeaf8.png)

**Comment by FrozenLi** [comment]
Hi is there any update regarding to this? I also met this problem when I use sklearn gbdt classifier model. Don't know if it is solved in onnxruntime newer version?

**Comment by abgoswam** [comment]
check https://github.com/onnx/onnxmltools/issues/451 for a fix. thanks to @xadupre
