### ISSUE TITLE
ConvTranspose does not support input rank other than 4

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnxruntime#2394]
**Describe the bug**
ConvTranspose does not support input rank other than 4. This is also commented in the code 
https://github.com/microsoft/onnxruntime/blob/a5a57a49c42d97434923d2603dfe50e8ed5fe723/onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h#L61
and the two related tests are disabled today.

**Urgency**
This is blocking Waveglow model (1d ConvTranspose). . https://drive.google.com/file/d/1rHTmCwZfyhrz-bRx6kzPHb9YJTpokoBO/view?usp=sharing

> 2019-11-13 17:10:46.641685893 [E:onnxruntime:Default, runner.cc:342 RunTask] waveglow:Non-zero status code returned while running ConvTranspose node. Name:'' Status Message: Input X must be 4-dimensional. X: {1,80,222}

**To Reproduce**
Run the above waveglow model. Or the unittest case from onnx `test_convtranspose_1d_cpu`.

**Comment by yuslepukhin** [comment]
I think it is a feature request.

**Comment by askhade** [comment]
https://github.com/microsoft/onnxruntime/pull/2578 implements Conv1DTranspose
