### ISSUE TITLE
[C++, Linux] Segmentation fault when creating Ort::Session

### ISSUE THREAD

**Issue by stefanpantic** [microsoft/onnxruntime#2397]
**Describe the bug**
I get a Segmentation Fault when I try to create an `Ort::Session` object from C++ on Linux.

**Urgency**
N/A

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): binary `onnxruntime-linux-x64-gpu-1.0.0.tgz`
- ONNX Runtime version: v1.0.0
- Python version: N/A
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.1/7.4
- GPU model and memory: GTX 1080Ti 11GB

**To Reproduce**
Code example for reproduction:
```
#include <string>
#include "onnxruntime/onnxruntime_cxx_api.h"


int main(void)
{
	Ort::Env env{nullptr};
	Ort::SessionOptions options{nullptr};
	std::string model_path{"./densenet121.onnx"};
	Ort::Session session(env, model_path.c_str(), options);

	return 0;
}
```
Compilation command:
`g++ --std=c++17 -O0 -ggdb  -o 01 01.cpp -lonnxruntime `

**Expected behavior**
The `Ort::Session` gets created and can be used for inference.

**Screenshots**
Output from `gdb`:
```
#0  0x00007ffff6488270 in OrtStatus* (anonymous namespace)::CreateSessionImpl<OrtApis::CreateSession(OrtEnv const*, char const*, OrtSessionOptions const*, OrtSession**)::{lambda(onnxruntime::InferenceSession&)#1}>(OrtEnv const*, OrtSessionOptions const*, OrtApis::CreateSession(OrtEnv const*, char const*, OrtSessionOptions const*, OrtSession**)::{lambda(onnxruntime::InferenceSession&)#1}, OrtSession**) ()
   from /usr/local/lib/libonnxruntime.so.1.0.0
#1  0x00007ffff64886c2 in OrtApis::CreateSession(OrtEnv const*, char const*, OrtSessionOptions const*, OrtSession**) () from /usr/local/lib/libonnxruntime.so.1.0.0
#2  0x0000555555555f87 in Ort::Session::Session (this=0x7fffffffdb98, env=..., model_path=0x5555559d6b50 "./densenet121.onnx", options=...) at onnxruntime/onnxruntime_cxx_inline.h:221
#3  0x0000555555555a7c in main () at 01.cpp:10
```

**Additional context**
- Output from `g++ --version`:
```
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
- I tried using the CPU only version but keep getting the same error.
- I'm using opset 8 of densenet121.

**Comment by snnn** [comment]
I can reproduce the error. Investigating.

**Comment by snnn** [comment]
The line:
```c++
	Ort::Env env{nullptr};
```
Should be
```c++
   Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "");
```

**Comment by stefanpantic** [comment]
It works now, thanks!
