### ISSUE TITLE
OrtRun infer time not stable

### ISSUE THREAD

**Issue by smilexin** [microsoft/onnxruntime#2419]
Cpu version lib,
In my user case, most of time the per frame OrtRun spend 2ms, but there are some frame, the infer time spend such as 10ms suddenly.  I cannt figure out  why.

My CPU session option is as following, is there some reason can cause issue?
    session_options = OrtCreateSessionOptions();
    OrtSetSessionThreadPoolSize(session_options, 1); // 2 or 4, little difference
    OrtSetSessionGraphOptimizationLevel(session_options, 2);
    OrtEnableMemPattern(session_options);
    OrtEnableCpuMemArena(session_options);

Thanks for your help.

**Comment by faxu** [comment]
Can you share some more information on your model?

**Comment by skottmckay** [comment]
And lots more of the details from the performance issue template like the following would be helpful:

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Comment by smilexin** [comment]
It maybe happen only in my user case. Thanks for your help, I'll find the root cause.

**Comment by smilexin** [comment]
Maybe my user case is not the general scenario, close temporarily. Thanks all~
