### ISSUE TITLE
Question about faster-rcnn inference of Onnx model with undefined input and output size

### ISSUE THREAD

**Issue by Timonsc** [microsoft/onnxruntime#2421]
Hello

I have another question. 

I want to inference the [faster-rcnn](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/faster-rcnn)

But I have an error and I think it is because all the shapes are undefined in the file. I get the shape with the [official size](https://github.com/microsoft/onnxruntime/blob/9e926fef1cf7c0ed9ccde5e88453fd91266f3c9b/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp#L96) or my method:
```
size_t input_tensor_size = 1;
        for (size_t j = 0; j < num_dims; j++) {
            input_tensor_size = input_tensor_size * input_node_dims[j];
        }
```
None of them worked. 

I got this error:
`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8 in tid 15948`
in this line:
```
std::vector<OrtValue*> ortOutput(num_output_nodes);
    ost = OrtRun( ort_ses, nullptr,
            input_node_names.data(),
            input_tensor_list.data(),
            num_input_nodes,
            output_node_names.data(),
            num_output_nodes,
            ortOutput.data());
```
The input_tensor_list is in this case a list of just one float array that comes from an INDArray using Dl4j package in java (android):
```
INDArray bgr = Nd4j.concat(0, b, g, r);           // shape = [3, 800, 1088]
float[] inputData = bgr.ravel().toFloatVector();
```

I create the tensors in this way: 
```
OrtValue* input_tensor = nullptr;
        ost = OrtCreateTensorWithDataAsOrtValue(
                ort_info,
                img,//1 dimention array 
                input_tensor_size * sizeof(type),
                reinterpret_cast<const int64_t *>(input_node_dims.data()),
                input_node_dims.size(), 
                type,
                &input_tensor);
input_tensor_list[i] = input_tensor;
```
Can you give me some advice on how to set the size of the input tensor?

**Comment by pranavsharma** [comment]
The API expects the number of bytes contained in the input ptr. In your case, it should be 3*800*1088*sizeof(float). You can also see [this](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/InferenceTestCapi.cpp#L52) as an example.

**Comment by Timonsc** [comment]
Thank you for your reply and the example. It did not solve the problem. I think it might have something to do with the undefined shape of the output values. Does anybody have an idea?

**Comment by Li-chunming** [comment]
I want to know ...can u run the fasterrcnn.onnx model download form the model-zoo  directly??

**Comment by Li-chunming** [comment]
Do you see the same [problem](https://github.com/microsoft/onnxruntime/issues/3168) like me?
