### ISSUE TITLE
 fatal error: Eigen/src/Core/arch/Default/Half.h: No such file or directory  #include "Eigen/src/Core/arch/Default/Half.h"                                               ^

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#2428]
Just pulled the master code and got this issue:

```
 fatal error: Eigen/src/Core/arch/Default/Half.h: No such file or directory
 #include "Eigen/src/Core/arch/Default/Half.h"
                                              ^

```

I believe onnxruntime have a Eigen lib as third dependencies inside `cmake/thirdparty`, so why it still try find eigen from system path?

When I installed Eigen to my system, it will got a multi-definition error again related to eigen.

I am confused about this error, which eigen exactly it trying to find and how should I solve this problem?

**Comment by jywu-msft** [comment]
don't use preinstalled eigen option. i think that only works for a specific version of eigen (which is probably not the one you are using)

it should be using the eigen from https://github.com/microsoft/onnxruntime/blob/master/cmake/external/eigen.cmake#L11

run make with VERBOSE=1 and try to see what directories are in the include path.

**Comment by GithubMingEnter** [comment]
或许你可以切换到1.20.0版本

**Comment by sergiomsilva** [comment]
Had the same issue with 1.20.1, downgrading to 1.19.2 worked for me.
