### ISSUE TITLE
performance question: how multiple inference on execution provider(MyriadX VPU)

### ISSUE THREAD

**Issue by JohnnyLing** [microsoft/onnxruntime#2432]
**Describe the bug**
MyriadX VPU has 16 SHAVE cores. https://www.movidius.com/myriadx
How can I run all hardware resources? multiple thread inference, with each thread running on the same core number? Can I customize one or some cores to run specific inference, while other cores for different inference?

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: latest build from github branch
- Python version: 3.6.8
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by jywu-msft** [comment]
@suryasidd , @smkarlap

**Comment by smkarlap** [comment]
Hi,
Currently, the application can only specify the model that it wants to execute on a single MyriadX chip.  The underlying Myriad toolchain automatically distributes individual computations from a model on to the various parallel SHAVE cores and collects the results back. It is not currently possible for an application to control execution on specific SHAVE cores within a single MyriadX chip.
 The only way to parallellize application at this stage is at a more coarse granular level by having multiple MyriadX cores (such as a VAD-M accelerator https://software.intel.com/en-us/iot/hardware/vision-accelerator-movidius-vpu )

**Comment by JohnnyLing** [comment]
@smkarlap if I am using 8 MyriadX VPU, any guideline how to run parallel computing? I want to check all hardware resources are fully running.

**Comment by smkarlap** [comment]
When using onnxruntime API's, one would first need to create a 'session' object that binds a model to a hardware backend. To execute inference on that session, one would call session.run() with the input data.

 When we create a session with a model for a VPU, we automatically choose one VPU to run the model on, and a corresponding session.run() would run inference on that device. One way to parallelize execution on multiple VPUs is to create multiple session objects that would cause each to bind to a different VPU (done automatically by OpenVINO EP) and call session.run() on each of them independently.

 Alternately, if you are using the multiple VPU's specifially from the VAD-M hardware mentioned above, parallel execution can be done via a single session object. To run multiple inference on multiple data blobs parallelly, simply batch all the blobs and pass the batched blob as input data to session.run(). The OpenVINO EP internally would unbatch the blobs and schedule parallel execution on the VPU units on the VAD-M hardware and return their results in a batched way. Sample application code to achieve this is available here: (https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/OpenVINO-ExecutionProvider.md#application-code-changes-for-vad-m-performance-scaling). However, this functionality is currently only available with the VAD-M hardware. With single VPUs you would need to use the multiple sessions approach.
