### ISSUE TITLE
Pad operator: Negative pads value not supported.

### ISSUE THREAD

**Issue by FlorentGuinier** [microsoft/onnxruntime#2433]
**Describe the bug**
Pad operator: Negative pads value not supported (shape is correct values look like garbage memory).

**Urgency**
Pad node with a negative pad amount are usefull to perform crop. As negative pad is relative to the size of the input while, a slice operation is hard-coded, meaning a network cannot change input resolution later. ONNX specs support negative pad amount, having ONNX runtime support it as well is a must have for us.

**System information**
- OS: Windows 10
- ONNX Runtime installed from (source or binary): From binary (pip)
- ONNX Runtime version: tryed both 0.5 and 1.0 (ie same problem with both)
- ONNX version : 1.2.2
- Python version: Python 3.6.8
- Visual Studio version (if applicable): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**To Reproduce**
Run the attached python script  [negative_pad_onnxruntime_repro_bug.py.txt](https://github.com/microsoft/onnxruntime/files/3862682/negative_pad_onnxruntime_repro_bug.py.txt)
Look at output tensor values.

**Expected behavior**
According to ONNX Negative Padding should be supported: 
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Pad

Running the script attached shows that it is not the case, ie the output tensor shape is correct while values look like uninitialized memory.

**Screenshots**
![image](https://user-images.githubusercontent.com/20201082/69129083-fdafd380-0aad-11ea-8d9b-1300f4fea262.png)

**Additional context**

**Comment by jywu-msft** [comment]
@hariharans29 FYI

**Comment by hariharans29** [comment]
Negative pad values have been supported since an earlier version of Pad. Opset-11 only had an interface change for Pad (a couple of attributes were made inputs). I only coded up the logic to handle the old and the new interface. The code already had logic to handle negative pads. This might be a bug that has always existed then. Nonetheless, let me take a look..

**Comment by FlorentGuinier** [comment]
Thanks for looking into it @hariharans29 let me know if I can help.

**Comment by hariharans29** [comment]
Sorry @FlorentGuinier - I haven't been able to get to this yet. I plan to take a look at this next week after the holidays. Thanks for checking back!

**Comment by FlorentGuinier** [comment]
@hariharans29 thanks for letting me know :). Have good vacation!

**Comment by hariharans29** [comment]
Could repro this. Investigating the pad logic to handle negative pad values.

**Comment by hariharans29** [comment]
> Negative pad values have been supported since an earlier version of Pad. Opset-11 only had an interface change for Pad (a couple of attributes were made inputs). I only coded up the logic to handle the old and the new interface. The code already had logic to handle negative pads. This might be a bug that has always existed then. Nonetheless, let me take a look..

Looks like this was a bug that always existed. There was a bug handling negative `begin` pad values - the pointer was being offset in the wrong direction resulting in it pointing to garbage which was then copied over to the output.

**Comment by hariharans29** [comment]
@FlorentGuinier  - I added your example as a test case. Please take a look. Thanks for reporting this.

**Comment by FlorentGuinier** [comment]
@hariharans29 Thanks!
