### ISSUE TITLE
Transpose CPU performance is very poor

### ISSUE THREAD

**Issue by mika-fischer** [microsoft/onnxruntime#2435]
**Describe the bug**
The CPUProvider Transpose operation is insanely slow

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux + Windows
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.0.0
- Visual Studio version (if applicable): 2017
- GCC/Compiler version (if compiling from source): 8.3

**To Reproduce**
I generated this model (also attached):
```python
import onnx
packed = onnx.helper.make_tensor_value_info(name='packed', elem_type=onnx.TensorProto.UINT8, shape=['N', 'H', 'W', 3])
planar = onnx.helper.make_tensor_value_info(name='planar', elem_type=onnx.TensorProto.UINT8, shape=['N', 3, 'H', 'W'])
node  = onnx.helper.make_node(op_type='Transpose', inputs=['packed'], outputs=['planar'], perm=[0, 3, 1, 2])
graph = onnx.helper.make_graph(nodes=[node], name='transpose-test', inputs=[packed], outputs=[planar])
model = onnx.helper.make_model(graph=graph)
onnx.save(model, "transpose.onnx")
```
[transpose.zip](https://github.com/microsoft/onnxruntime/files/3863850/transpose.zip)

**Expected behavior**
Naive C++ code for this transpose:
```cpp
    template<typename T>
    void convert_rgb24_packed_to_planar(size_t width, size_t height, size_t step, const void* data,
                                        T* r_plane, T* g_plane, T* b_plane) {
        const uint8_t* src = static_cast<const uint8_t*>(data);
        step -= 3 * width;
        for (size_t y = 0; y < height; ++y) {
            for (size_t x = 0; x < width; ++x) {
                *r_plane++ = T(*src++);
                *g_plane++ = T(*src++);
                *b_plane++ = T(*src++);
            }
            src += step;
        }
    }
```
This executes in about 130 us on my machine. I understand that there are overheads but I would have expected that running the graph would be at most 10 times as slow.

However the graph takes about 24 ms on Linux and about 15 ms on Windows.

Both are unacceptably slow...

**Comment by skottmckay** [comment]
How are you measuring performance? Is there a warmup request or not? How many times are you calling Run to determine the average?

Are you using a Debug (the default when building from source) or Release (--config Release) build?

**Comment by skottmckay** [comment]
The implementation of Transpose needs to handle any re-ordering of the axes, and any number of axes. Your implementation is highly optimized for one specific use case where you can simply do forward iteration of the input and directly write to a fixed number of output locations.

The generic handling requires calculating both the input offset and output location for every write by calling both ComputeOffset (for the input) and IncrementIndex (for the output). That's massively more expensive than the two pointer increments per write in your implementation. 

https://github.com/microsoft/onnxruntime/blob/6bcf95477eca78e283a1282f545bcc4c34e4e82c/onnxruntime/core/providers/cpu/tensor/transpose.cc#L17-L33

The Transpose implementation is optimized if larger blocks can be moved at a time, but in this case as the last axis is moving the block size is 1. 

A specialized Transpose implementation could possibly be added for handling NHWC -> NCHW transpose operations, but alternatively the ONNX model could be completely NCHW based (as that's the layout ONNX supports) and a more optimal transpose could be done in pre-processing.

**Comment by skottmckay** [comment]
FWIW a quickly hacked up optimization for when the last axis is moving forward makes it ~5x faster (release build, uint8_t input of shape {1, 1024, 1024, 3}). Could probably generalize the optimization further to handle when a single axis moves either forward or backwards, but there are pros/cons/risks to be considered.

e.g. if the axis being moved is of size 1024 do you really want 1024 pointers to write locations being used concurrently?

**Comment by mika-fischer** [comment]
> How are you measuring performance?

Running the graph several times, and measuring the wall clock time.

> Is there a warmup request or not?

Yes

> How many times are you calling Run to determine the average?

I'm using 2 runs for warmup and then 100 runs to measure.

> Are you using a Debug (the default when building from source) or Release (--config Release) build?

Release

> The implementation of Transpose needs to handle any re-ordering of the axes, and any number of axes. Your implementation is highly optimized for one specific use case where you can simply do forward iteration of the input and directly write to a fixed number of output locations.

Sure, I get that this is not trivial. But still, I think NCHW -> NHWC and the reverse deserve some special treatment (IIRC tf2onnx builds these into the graph by default, or at least used to).

And for the generic case, it might make sense to have a look at how numpy or Eigen do this. Presumably a lot of thought has gone into their implementations.

> The generic handling requires calculating the input offset for every write by calling both ComputeOffset and IncrementIndex. That's massively more expensive than the two pointer increments per write in your implementation.

I wouldn't agree that it *requires* this, this is just a side-effect of the staight-forward way Transpose is currently implemented in onnxruntime. But I agree that a generic *and* performant solution is not trivial.

> A specialized Transpose implementation could possibly be added for handling NHWC -> NCHW transpose operations

That would be great!

> but alternatively the ONNX model could be completely NCHW based (as that's the layout ONNX supports) and a more optimal transpose could be done in pre-processing.

This is what we did in the meantime. So solving this is not that urgent from our side, we now just avoid Transpose ops...

**Comment by skottmckay** [comment]
Added a new optimized path for when a single axis is moving.
