### ISSUE TITLE
onnx runtime server docker 

### ISSUE THREAD

**Issue by sevenold** [microsoft/onnxruntime#2442]
#### {"error_code": 400, "error_message": "ONNX Runtime Status Code: 4. No model loaded of that name."}

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): deepin 15.11
- ONNX Runtime installed from (source or binary): docker
- ONNX Runtime version: 0.5
- Python version: 3.6

docker.sh
*********************
docker run --runtime=nvidia -it --rm \
-v $(pwd)/onnx_model:/models/ \
-p 8501:8001 mcr.microsoft.com/onnxruntime/server:latest \
--num_http_threads=8 \
--model_path /models/model.onnx
*********************
client.py
*********************
ENDPOINT = 'http://localhost:8501/v1/models/mymodel/versions/1:predict'
json_request_headers = {
    'Content-Type': 'application/json',
    'Accept': 'application/json'
}
pb_request_headers = {
    'Content-Type': 'application/octet-stream',
    'Accept': 'application/octet-stream'
}

input_array = np.load('deploy/up.npy')
input_array = input_array.astype(np.float32)
tensor_proto = numpy_helper.from_array(input_array)

json_str = MessageToJson(tensor_proto, use_integers_for_enums=True)
data = json.loads(json_str)

inputs = {'model_input_input': data}
output_filters = ['model_output']

payload = {"inputs": inputs, "outputFilter": output_filters}
res = requests.post(ENDPOINT, headers=json_request_headers, data=json.dumps(payload))
print(res.text)
raw_data = json.loads(res.text)['outputs']['model_output']['rawData']
outputs = np.frombuffer(base64.b64decode(raw_data), dtype=np.float32)
print(outputs)
*********************
and i use docker image:**lain21/onnxruntime-serving:0.4.0** is all right.

**Comment by jywu-msft** [comment]
if the model filename is model.onnx , shouldn't the ENDPOINT be http://localhost:8501/v1/models/model/versions/1:predict , not  http://localhost:8501/v1/models/mymodel/versions/1:predict ?

**Comment by nopeiyu** [comment]
I read the source code, this problem should be solved in this way.
http://localhost:8501/v1/models/default/versions/1:predict

**Comment by faxu** [comment]
@sevenold is your issue resolved? if so, can you please close this?

**Comment by adriantorrie** [comment]
[These docs](https://github.com/microsoft/onnxruntime/tree/master/dockerfiles#onnx-runtime-server) need updating to reflect the need to use `default`.

There's also an open issue in the ONNX runtime tutorials that needs referencing:
https://github.com/onnx/tutorials/issues/155
