### ISSUE TITLE
[ONNXModelZoo] Arcface model fails during ONNX runtime session run

### ISSUE THREAD

**Issue by tmoreau89** [microsoft/onnxruntime#2447]
**Symptom**

[Arcface](https://github.com/onnx/models/tree/master/vision/body_analysis/arcface) model from onnx model zoo doesn't run properly in ONNX runtime session run (tested in 1.0.0).

The following error message gets printed out:
```
2019-11-20 17:24:29.510729 [E:onnxruntime:, sequential_executor.cc:165 Execute] Non-zero status code returned while running BatchNormalization node. Name:'stage1_unit1_bn1' Status Message: Invalid input scale: NumDimensions() != 3
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    ort_sess.run(None, ort_data)
  File "/Users/moreau/.pyenv/versions/3.7.0/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 136, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running BatchNormalization node. Name:'stage1_unit1_bn1' Status Message: Invalid input scale: NumDimensions() != 3
```

**Reproducing the error**

Environment:
* ubuntu: 18.04
* python: 3.7.0
* onnx: 1.6.0
* onnxruntime: 1.0.0
* numpy: 1.17.4

Dockerfile to reproduce error:
```dockerfile
FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install -y python3-dev python3-pip git vim
RUN pip3 install --upgrade pip

RUN pip3 install numpy==1.17.4
RUN pip3 install onnx==1.6.0
RUN pip3 install onnxruntime==1.0.0
```

Model: 
* URL: https://s3.amazonaws.com/onnx-model-zoo/arcface/resnet100/resnet100.onnx
* SHA: 66074b860f905295aab5a842be57f37d

Minimal python script:
```python
import numpy as np
import urllib.request
import onnxruntime
import os

MODEL_FILE = "resnet100.onnx"
URL = "https://s3.amazonaws.com/onnx-model-zoo/arcface/resnet100/resnet100.onnx"

# Download model file
if not os.path.exists(MODEL_FILE):
    urllib.request.urlretrieve(URL, MODEL_FILE)

# Create ONNX runtime session
ort_sess = onnxruntime.InferenceSession(MODEL_FILE)
# Print information on model input
for idx, inp in enumerate(ort_sess.get_inputs()):
    print("Input info: {}".format(inp))
# Init data
ort_data = {"data": np.random.rand(1,3,112,112).astype("float32")}
# Run
ort_sess.run(None, ort_data)
```

**Comment by tmoreau89** [comment]
Issue reference in ONNXModelZoo repo: https://github.com/onnx/models/issues/242

**Comment by hariharans29** [comment]
Please see my comment on Oct 10 here - https://github.com/onnx/models/issues/156.

Closing this out, as this has already been established as a model issue (not an ORT issue)

**Comment by hariharans29** [comment]
Comment on Oct 11 shows how to fix the model to be able to run it in ORT...

**Comment by tmoreau89** [comment]
Thanks for the quick response @harihans29; this will be tracked as a model issue in the onnxmodelzoo repo.

**Comment by hariharans29** [comment]
FWIW - the "fix" to the model should just be 4-5 lines of Python away (see comment on Oct 11). 

Also to be fair - the contributor of the model hasn't yet acknowledged the problem. The "fix" is what we discovered is logical to how the model is structured (and it passes the accompanying tests for the model.)

You can try to see if the "fix" works for you. Any pending issues need not block your usage. :)
