### ISSUE TITLE
When installing onnxruntime

### ISSUE THREAD

**Issue by sicccs** [microsoft/onnxruntime#2462]
-- Found PythonInterp: /home/si/.virtualenvs/onnx2/bin/python3 (found suitable version "3.7.5", minimum required is "3.5") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.7m.so (found suitable version "3.5.2", minimum required is "3.5") 

As shown above, when compiling the python version of onnxruntime, libpython3.7m.so was found, but the prompt is still python3.5

Ubuntu16.04
Python3.7.5(Python 3.5 under the system)

**Comment by sicccs** [comment]
Total Test time (real) =  52.85 sec
2019-11-22 16:59:22,563 Build [DEBUG] - Running subprocess in '/home/si/work/onnxruntime/build/Linux/RelWithDebInfo'
['/home/si/.virtualenvs/onnx2/bin/python3', 'onnxruntime_test_python.py']
/home/si/work/onnxruntime/build/Linux/RelWithDebInfo/onnxruntime/capi/_pybind_state.py:13: UserWarning: Cannot load onnxruntime.capi. Error: 'Python version mismatch: module was compiled for Python 3.5, but the interpreter version is incompatible: 3.7.5 (default, Oct 21 2019, 11:39:23)

**Comment by leimao** [comment]
Did you install Python 3.5 or 3.7?

**Comment by sicccs** [comment]
> 您安装了Python 3.5或3.7吗？

Python 3.7, but the compiled version is related to Python 3.5

**Comment by snnn** [comment]
Please remove /home/si/.virtualenvs/onnx2/bin from your PATH

**Comment by sicccs** [comment]
> 请从您的PATH中删除/home/si/.virtualenvs/onnx2/bin。您不应该从那里获取python。

I know. It seems that I have to use Python 3.5 of the system. 
I just want to use other versions of Python

**Comment by snnn** [comment]
You can choose.
How did you build onnxruntime?

**Comment by sicccs** [comment]
> You can choose.
> How did you build onnxruntime?

I'm passing this order：
./build.sh --config RelWithDebInfo ----build_wheel --parallel

Thank you for your reply.

**Comment by snnn** [comment]
Run
```
cat build.sh 
```

You'll see how it works. 

You may bypass this script, run build.py directly, with the full path of your python interpreter. like:
```sh
/usr/bin/python tools/ci_build/build.py --use_openmp --build_dir /tmp/build --config RelWithDebInfo ----build_wheel --parallel
```

**Comment by sicccs** [comment]
> You can choose.
> How did you build onnxruntime?



> Run
> 
> ```
> cat build.sh 
> ```
> 
> You'll see how it works.
> 
> You may bypass this script, run build.py directly, with the full path of your python interpreter. like:
> 
> ```shell
> /usr/bin/python tools/ci_build/build.py --use_openmp --build_dir /tmp/build --config RelWithDebInfo ----build_wheel --parallel
> ```

It can't be solved, but I solved the problem through anaconda.

Thank you very much.

> Run
> 
> ```
> cat build.sh 
> ```
> 
> You'll see how it works.
> 
> You may bypass this script, run build.py directly, with the full path of your python interpreter. like:
> 
> ```shell
> /usr/bin/python tools/ci_build/build.py --use_openmp --build_dir /tmp/build --config RelWithDebInfo ----build_wheel --parallel
> ```



> Run
> 
> ```
> cat build.sh 
> ```
> 
> You'll see how it works.
> 
> You may bypass this script, run build.py directly, with the full path of your python interpreter. like:
> 
> ```shell
> /usr/bin/python tools/ci_build/build.py --use_openmp --build_dir /tmp/build --config RelWithDebInfo ----build_wheel --parallel
> ```

This can't be solved, but I solved the problem through anaconda.
Thank you very much.
