### ISSUE TITLE
An ONNX model that worked in 0.5.1 now fails in 1.0.0

### ISSUE THREAD

**Issue by Mut1nyJD** [microsoft/onnxruntime#2474]
**Describe the bug**

I recently upgraded my ONNX Runtime from 0.5.1 to 1.0.0 after changing my C code to adapt to the new API I then found out that my previous ONNX model does no longer run in 1.0.0. My ONNX model uses OpSet-Level 9. It is a PyTorch1.3 ONNX export of a HRNet-backbone landmark detection model. 

When loading the ONNX model in ONNXRuntime 1.0 I'll get an Exception:

op_kernel.cc:21 onnxruntime::OpKernelContext::OpKernelContext kernel != nullptr was false. OpKernel was null

it loaded fine in 0.5.1

**Comment by skottmckay** [comment]
If I attempt to export that model with opset 9 I see the following error:

> python\python37\lib\site-packages\torch\onnx\symbolic_helper.py:198: UserWarning: You are trying to export the model with onnx:Upsample for ONNX opset version 9. This operator might cause results to not match the expected results by PyTorch.
> ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
> We recommend using opset 11 and above for models using this operator.

Exporting with opset 11 produces a model that loads successfully. Is that an option? I used the export instructions from this pytorch issue: https://github.com/pytorch/pytorch/issues/23474

**Comment by skottmckay** [comment]
I also exported using opset 9 and the model produced loads successfully. Could you please share your model as well a the requested system info:

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by Mut1nyJD** [comment]
Sure please find here a download link to the ONNX model

https://mut1nyjd.stackstorage.com/s/ZwctHMbvHJM1bhf

> **System information**
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

Windows 10

> * ONNX Runtime installed from (source or binary):

Binary NuGet package version

> * ONNX Runtime version:
0.51 and 1.0.0

> * Python version:
No Python using C Backend

> * Visual Studio version (if applicable):
15.9.8 

> * CUDA/cuDNN version:
10.1/7.1

> * GPU model and memory:

GTX1060ti 6GB VRAM

**Comment by Mut1nyJD** [comment]
Forgot to say the output I'll get from ONNX Runtime 0.5.1 on this model on a test image is pretty close to what I'll get from the PyTorch model, so the model itself does not seem to be the problem

**Comment by skottmckay** [comment]
I have not been able to reproduce on either linux or windows with CUDA 10.1. The cuDNN version I have is a bit newer on each (7.6) though but I don't expect that would matter.

Can you try completely uninstalling ONNX Runtime and reinstalling? There are only a few places we create OpKernelContext and I can't see how any of those would have a nullptr for the kernel.

**Comment by Mut1nyJD** [comment]
Hmm I tried a complete fresh install of ONNXRuntime with a new project also tried it with VS2015. 
I installed latest CuDNN 7.6.5 for 10.1 but still seeing the same error. 
I've installed the MKL-DNN version of ONNXRuntime 1.0.0 that works fine with the model.
I will try a different GPU and/with other driver and see if that makes a difference.

**Comment by skottmckay** [comment]
Could you share the C code you're using? I tested using python so that's one other difference.

**Comment by Mut1nyJD** [comment]
Sure no problem, please find here my minimum test code

`// ONNXRuntime
#include "onnxruntime_c_api.h"
// CUDA ONNXRuntime
#include "cuda_provider_factory.h"

const OrtApi* g_ort = OrtGetApiBase()->GetApi(ORT_API_VERSION);

void CheckStatus(OrtStatus* status)
{
	if (status != NULL) {
		const char* msg = g_ort->GetErrorMessage(status);
		fprintf(stderr, "%s\n", msg);
		g_ort->ReleaseStatus(status);
		exit(1);
	}
}


int main()
{
	OrtEnv* env = NULL;
	CheckStatus(g_ort->CreateEnv(ORT_LOGGING_LEVEL_WARNING, "test", &env));
	// initialize session options if needed
	OrtSessionOptions* session_options;
	g_ort->CreateSessionOptions(&session_options);
	// If you have CUDA ONNXRuntime installed otherwise don't use this line
	OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0);
	g_ort->SetIntraOpNumThreads(session_options, 8);
	g_ort->SetInterOpNumThreads(session_options, 8);
	g_ort->SetSessionGraphOptimizationLevel(session_options, ORT_ENABLE_BASIC);
	OrtSession* session = NULL;
	CheckStatus(g_ort->CreateSession(env, L"hrnet_w18_landmarks.onnx", session_options, &session));
	std::cout << "ONNX model loaded succesfull\n"; 
}
`

**Comment by Mut1nyJD** [comment]
If you need a full .vcproj + code I can upload that as well

**Comment by skottmckay** [comment]
Not sure how your original setup was working. According to https://developer.nvidia.com/rdp/cudnn-archive the first cudnn version to support cuda 10.1 was 7.5 but you said you were using cuda 10.1 and cudnn 7.1.

After you installed cudnn 7.6.5 did you rebuild ONNX Runtime and point it to the 7.6.5 files (either via the CUDNN_HOME environment variable or --cudnn_home parameter)?

**Comment by skottmckay** [comment]
I can reproduce the issue. Should have a fix later today.

**Comment by Mut1nyJD** [comment]
@skottmckay 
Great excellent! Happy you manage to reproduce it and yes sorry I misreported my setup it was CUDA 10.1/CuDNN 7.5 before I have so many CUDA/CuDNN variants installed I loose track from time to time.

**Comment by skottmckay** [comment]
Two short term options if needed:
  - disable all optimizations so constant folding doesn't run
    - simple but has a performance cost
    - `g_ort->SetSessionGraphOptimizationLevel(session_options, ORT_DISABLE_ALL);`

  - run the optimizations with just the CPU execution provider enabled, save the model, and use that model with the CUDA execution provider. this is a one time step.
    - `g_ort->SetOptimizedModelFilePath(session_options, L"hrnet_w18_landmarks.optimized.onnx");`
    - comment out the line that adds the CUDA execution provider, set the optimized model file path, create a session and release it (no need to call Run). following that you should be able to use the CUDA execution provider with the optimized model
