### ISSUE TITLE
Slow Inference onnx runtime?

### ISSUE THREAD

**Issue by kunalgoyal9** [microsoft/onnxruntime#2482]
**Describe the bug**
Inference Speed for a sample image of "ssd_mobilenet_v1_coco_2018_01_28" on Tensorflow took around only 0.034 secs(29.4 FPS) while after conversion to onnx through the mentioned [notebook](https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/ConvertingSSDMobilenetToONNX.ipynb) took 0.19 secs(5 FPS)

**Urgency**
High

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- Tensorflow Version: 2.0.0
- Python version: 3.6

**To Reproduce**
1) ran [notebook](https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/ConvertingSSDMobilenetToONNX.ipynb)
2) Through time.time() calculated sess.run() time.
![image](https://user-images.githubusercontent.com/21281457/69574641-b0bc8780-0fee-11ea-8186-a514d138587b.png)

**Expected behavior**
I expected similar to Tensorflow API results i.e. (29.4 FPS)

**Screenshots**
Tensorflow API Screenshot
![image](https://user-images.githubusercontent.com/21281457/69575276-eca41c80-0fef-11ea-98f9-066f8de6f659.png)

Can anyone tell what things I am missing or did wrong?

**Comment by hariharans29** [comment]
Hi @kunalgoyal9,

Can you please fill out the github issue template ?

Which version of ORT are you running ? 

(If built from source) In which mode did you build it - Debug or Release ?

**Comment by faxu** [comment]
@kunalgoyal9 Do you still require assistance to troubleshoot this issue? If so, please share more details above and please try the latest version of ORT.
