### ISSUE TITLE
CPU with MKLDNN using OpenMP cause CPU loading high, maybe OMP_WAIT_POLICY is ACTIVE by default.

### ISSUE THREAD

**Issue by smilexin** [microsoft/onnxruntime#2494]
**Describe the bug**
CPU + MKLDNN or CPU+MKLDNN+MKLML version using OpenMP,  whatever official release or self build, both cause CPU high loading when  enable MKLDNN provider.

**Urgency**
None.
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): both
- ONNX Runtime version: newly release v1.0, or v0.4
- Python version: 3.7
- Visual Studio version (if applicable): vs 2017
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: No
- GPU model and memory: No

**To Reproduce**
User case that doing continuous inference, maybe  reproduce.

**Expected behavior**
Cpu behave normal

**Additional context**
Code slice:
    CheckStatus(g_ort->CreateSessionOptions(&session_options));
    // MKLDNN enabeld
    CheckStatus(g_ort->SetSessionExecutionMode(session_options, ORT_PARALLEL)); // Paralel
    g_ort->SetInterOpNumThreads(session_options, 2);
    g_ort->EnableCpuMemArena(session_options);
    g_ort->SetSessionGraphOptimizationLevel(session_options, ORT_ENABLE_BASIC);
    OrtSessionOptionsAppendExecutionProvider_Mkldnn(session_options, 1);

**Comment by smilexin** [comment]
I use env to set  OMP_WAIT_POLICY to PASSIVE, the cpu behaves normal, but the infer time become a little longer.

**Comment by snnn** [comment]
Close it because there isn't any actionable items for us.

**Comment by snnn** [comment]
https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Perf_Tuning.md#mkl_dnnngraphmkl_ml-execution-provider
