### ISSUE TITLE
Building from source fails with python 3.8 and 3.9

### ISSUE THREAD

**Issue by sgreene** [microsoft/onnxruntime#2498]
**Describe the bug**
Running build.sh fails with the following error:

> AttributeError: module 'platform' has no attribute 'linux_distribution'

The error is coming from:
> "tools/ci_build/build.py", line 178, in is_ubuntu_1604

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): RHEL 7
- ONNX Runtime installed from (source or binary): source (master branch)
- ONNX Runtime version: 1.0.0
- Python version: 3.9.0a0
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A (CPU only)

**To Reproduce**
Describe steps/code to reproduce the behavior:

1. Download and install python 3.9. (I built from source)
2. Run build.sh with the required flags. I used:
`./build.sh --config RelWithDebInfo --build_shared_lib --parallel --use_mkldnn`

**Expected behavior**
I expected a clean build since a minimum of python 3.6 is required and I met that requirement. I can workaround the problem by editing tools/ci_build/build.py and changing the problematic function from 

`def is_ubuntu_1604():
    return platform.linux_distribution()[0] == 'Ubuntu' and platform.linux_distribution()[1] == '16.04'`

To return a hardcoded value:

`def is_ubuntu_1604():
    return False`

Everything works after doing this.

**Screenshots**
N/A

**Additional context**
I realized while filing this issue that the python3 I'm using is a pre-release version. However I believe platform.linux_distribution was removed in 3.8 (https://github.com/pymssql/pymssql/issues/586). I also realize that RHEL is not supported however this should affect users with python3.8 on Ubuntu as well.

**Comment by snnn** [comment]
Yes.  We should fix this.
And we do support RHEL.

**Comment by Exlsunshine** [comment]
> Yes. We should fix this.
> And we do support RHEL.

I am facing the same issue, but I build ONNXRUNTIME through dockerfiles/Dockerfile.server, python in my local machine is 3.5.2 and the python in the Dockerfile.server is 3.5, why is this issue relevant with python3.8/9?

content of Dockerfile.server:
```
FROM ubuntu:16.04 AS minimal
MAINTAINER Harry Yang "huayang@microsoft.com"

FROM ubuntu:16.04 AS build
ARG PYTHON_VERSION=3.5
ARG ONNXRUNTIME_REPO=https://github.com/Microsoft/onnxruntime
ARG ONNXRUNTIME_SERVER_BRANCH=master
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y sudo git bash

ENV PATH="/opt/cmake/bin:${PATH}"
RUN git clone --single-branch --branch ${ONNXRUNTIME_SERVER_BRANCH} --recursive ${ONNXRUNTIME_REPO} onnxruntime
RUN /onnxruntime/tools/ci_build/github/linux/docker/scripts/install_ubuntu.sh -p ${PYTHON_VERSION} && \
    /onnxruntime/tools/ci_build/github/linux/docker/scripts/install_deps.sh -p ${PYTHON_VERSION} && \
    /onnxruntime/tools/ci_build/github/linux/docker/scripts/install_server_deps.sh

ENV PATH="/usr/local/go/bin:${PATH}"

WORKDIR /
RUN mkdir -p /onnxruntime/build && \
    python3 /onnxruntime/tools/ci_build/build.py --build_dir /onnxruntime/build --config Release --build_server --parallel --cmake_extra_defines ONN

FROM minimal AS final
WORKDIR /onnxruntime/server/
COPY --from=build /onnxruntime/build/Release/onnxruntime_server /onnxruntime/server/
COPY --from=build /onnxruntime/build/Release/libonnxruntime.so.* /lib/
RUN apt-get update \
    && apt-get install -y libgomp1
ENTRYPOINT ["/onnxruntime/server/onnxruntime_server"]
```

**Comment by jungin500** [comment]
I found out after searching, it turns out that [Python 3.7+ has been deprecated `platform.linux_distribution()` API](https://stackoverflow.com/questions/49554443/platform-linux-distribution-deprecated-what-are-the-alternatives), and I couldn't find simplest solution compared to below one. Please comment If you found somthing simpler than this.

I successfully built onnxruntime with Dockerfile, from branch master, with bunch of supported tools - **just add following two lines before final build command `./build.sh`**. Or if you're building within command line, execute those commands from `onnxruntime` directory (where `./build.sh` file exists), and after it'd be good to go.

```
pip install distro &&\
sed -i "s/import\ platform/import\ platform\nimport\ distro/g" tools/ci_build/build.py &&\
sed -i "s/platform.linux_distribution()/distro.linux_distribution()/g" tools/ci_build/build.py
```

**Comment by snnn** [comment]
#2747
