### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by Exlsunshine** [Microsoft/onnxruntime#250]
**Describe the bug**
```
exlsunshine@exlsunshine:~/downloads $ pip install onnxruntime
Collecting onnxruntime
  Could not find a version that satisfies the requirement onnxruntime (from versions: )
No matching distribution found for onnxruntime
```

**System information**
```
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

- ONNX Runtime installed from (source or binary):
```pip install```

- ONNX Runtime version:
```0.1.4```

- Python version:
```
exlsunshine@exlsunshine:~/downloads $ python -V
Python 2.7.15rc1
exlsunshine@exlsunshine:~/downloads $ python3 -V
Python 3.6.7
```

- GCC/Compiler version (if compiling from source):
```
exlsunshine@exlsunshine:~/downloads $ gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

- CUDA/cuDNN version:

**To Reproduce**
```pip install onnxruntime```

**Expected behavior**
```install package```

**Screenshots**

**Additional context**

**Comment by snnn** [comment]
onnxruntime only supports python 3.x. If your 'pip' command is from python 2.x, then it won't work.

**Comment by Exlsunshine** [comment]
> onnxruntime only supports python 3.x. If your 'pip' command is from python 2.x, then it won't work. Please run:
> 
> ```
> pip3 install onnxruntime
> ```

Thank you, I have figured it out, ```pip3``` works.

**Comment by hardiknahata** [comment]
I am facing the same error even with "pip3 install onnxruntime".
Any suggestions?

**Comment by snnn** [comment]
> I am facing the same error even with "pip3 install onnxruntime".
> Any suggestions?

Could you please open a new issue and provide us more information? For example, your operating system version, python version.

**Comment by CzKerwin** [comment]
linux nano python3.6.9 
"Collecting onnxruntime
  Could not find a version that satisfies the requirement onnxruntime (from versions: )
No matching distribution found for onnxruntime"

**Comment by pawannane** [comment]
I am facing the same error even with "pip3 install onnxruntime". 
Using Windows 10 machine(x64) with python installed version 3.10.2

**Comment by gimmi** [comment]
Same issue for me, runnin in a docker container on `amd64` architecture:

```
docker run --rm -it python:3 pip install onnxruntime

ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime
```

**Comment by davidatorres** [comment]
I'm have an issue on MacOS and Windows 11.

`pip3 install onnxruntime`

_**No matching distribution found for onnxruntime**_

Any known workarounds?

**Comment by ShomyLiu** [comment]
Same issue on MacOS with python3.9
```
pip3 install onnxruntime
```

**Comment by snnn** [comment]
Everyone in this thread please read https://peps.python.org/pep-0425/ .  onnxruntime python package includes these tag in its filenames. When pip says 

```
No matching distribution found for onnxruntime
```

It means pip tried to find an onnxruntime wheel file from  https://pypi.org/project/onnxruntime/#files with specific tags,  but couldn't find it.

So, what tags it wanted?  Your python version determined the "python tag". Your operating system and CPU arch of your python executable determined the "platform tag".  So please open the link https://pypi.org/project/onnxruntime/#files  , see if the file is there. 

1. cp38 means python 3.8. cp39 means python 3.9 .What is your python version?
2. macosx_10_15 means macosx >=10.15. manylinux_2_17 means a Linux distro with glibc version >=2.17. So, what is your operating system version?
3. x86_64 means Intel x86 CPU with 64-bit extension, is it what you have?

If the type of package you are looking for is not provided by us yet,  **please create a new issue with the information above**. Then our product team will review your request and make plans, hopefully we will be able to provide it in the next onnxruntime release.  You can view our plans at https://github.com/microsoft/onnxruntime/projects .

**Comment by ivanstepanovftw** [comment]
Python 3.11.2
Fedora 37 Workstation

**Comment by kshabahang** [comment]
Python 3.11.2
Ditto

**Comment by wangjia184** [comment]
Python 3.11.0
WSL(Ubuntu) in WIndows 11 x64

**Comment by getorca** [comment]
ditto on Python 3.11.3

**Comment by rubychilds** [comment]
same is on Python 3.11.3, MacOSX M2

**Comment by BryanHorow** [comment]
It will not work for Python 3.11, it's only until Python 3.10. I have Python 3.9 and Python 3.11, I installed the package with
`pip3.9 install onnxruntime --user`
You can install it with pip3.x where x is less than 11 depending on your Python version, it does not support Python 3.11 as seen here https://pypi.org/project/onnxruntime/#files mentioned by @snnn

**Comment by snnn** [comment]
For python 3.11 support please see #13482

**Comment by CarrotLiu** [comment]
Hi! Is there any package for Python 3.12 (win-64)? Thx!

**Comment by archive-r** [comment]
python 3.12
macos 14 sonoma

**Comment by snnn** [comment]
> Hi! Is there any package for Python 3.12 (win-64)? Thx!

Not yet.

**Comment by fvisticot** [comment]
any update, I'm using python 3.12 and have the same issue

**Comment by zaccee** [comment]
Any update on this? Also having the issue with python 3.12
