### ISSUE TITLE
The performance of multithreading parallel inference deteriorates rapidly as the number of threads increases

### ISSUE THREAD

**Issue by wizardk** [microsoft/onnxruntime#2512]
**Describe the bug**
The performance of multithreading parallel inference deteriorates rapidly as the number of threads increases.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): Official builds CPU (MLAS+Eigen) [https://github.com/microsoft/onnxruntime/releases/download/v1.0.0/onnxruntime-linux-x64-1.0.0.tgz](url) and CPU (MKL-ML) [https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.MKLML/](url)
- ONNX Runtime version: v1.0.0
- CPU info: Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz 48 cores

**To Reproduce**
export OMP_NUM_THREADS=1
```
#include <pthread.h>
#include <iostream>
#include <vector>
#include <chrono>
#include <numeric>
#include <onnxruntime_cxx_api.h>

typedef struct t_s_param {
    Ort::Session * sess;
    int loop_cnt;
    int * ms;
} s_param;

void * working_thread(void * param)
{
    std::vector<float> x_val(1 * 80 * 100);
    for (int i = 0; i < x_val.size(); ++i) { x_val[i] = (float)i / (x_val.size() - 1); } // [0.0, 1.0]
    auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
    std::vector<int64_t> x_dim = { 1, 80, 100 };
    Ort::Value x = Ort::Value::CreateTensor<float>(memory_info, x_val.data(), x_val.size(), x_dim.data(), 3);
    std::vector<const char*> x_name = { "x" };
    std::vector<const char*> y_name = { "y" };

    int * ms = ((s_param *)param)->ms;
    for (int idx = 0; idx < ((s_param *)param)->loop_cnt; ++idx) {
        std::chrono::system_clock::time_point start = std::chrono::system_clock::now();
        std::vector<Ort::Value> y = ((s_param *)param)->sess->Run(Ort::RunOptions{ nullptr }, x_name.data(), &x, 1, y_name.data(), 1);
        std::chrono::milliseconds elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now() - start);
        *ms += elapsed.count();
    }
    *ms /= ((s_param *)param)->loop_cnt;
    std::cout << "thread quit" << std::endl;
    return 0;
}

int main(int argc, char ** argv)
{
    if (argc != 4) { return 0; }
    int thread_cnt = atoi(argv[1]);
    int loop_cnt = atoi(argv[2]);
    int op_thread_cnt = atoi(argv[3]);

    // load model
    Ort::Env env(ORT_LOGGING_LEVEL_ERROR, "test");
    Ort::SessionOptions session_options;
    if (op_thread_cnt > 0) {
        session_options.SetInterOpNumThreads(op_thread_cnt);
        session_options.SetIntraOpNumThreads(op_thread_cnt);
    }
    session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
    Ort::Session sess(env, "model.onnx", session_options);

    // create thread
    std::vector<int> ms(thread_cnt, 0);
    std::vector<s_param> param(thread_cnt);
    std::vector<pthread_t> thread_handle;
    for (int idx = 0; idx < thread_cnt; ++idx) {
        param[idx].sess = &sess;
        param[idx].loop_cnt = loop_cnt;
        param[idx].ms = &ms[idx];
        pthread_t sub_handle;
        pthread_create(&sub_handle, 0, working_thread, &param[idx]);
        thread_handle.push_back(sub_handle);
    }
    for (int idx = 0; idx < thread_cnt; ++idx) {
        pthread_join(thread_handle[idx], 0);
    }
    std::cout << std::accumulate(ms.begin(), ms.end(), 0) / ms.size() << std::endl;

    return 0;
}
```

**Expected behavior**
The average inference speed will not decline significantly, and the proportional relationship between CPU usage and speed should stay the same.

**Actual behavior**
CPU (MLAS+Eigen)
1 thread, loop 100 times, set op number threads 1: CPU usage 100%, average elapsed 552ms.
10 threads, loop 100 times, set op number threads 1: CPU usage 1000%, average elapsed 1745ms.
20 threads, loop 100 times, set op number threads 1: CPU usage 2000%, average elapsed 4912ms.

CPU (MKL-ML)
1 thread, loop 100 times, set op number threads 1: CPU usage 100%, average elapsed 582ms.
10 threads, loop 100 times, set op number threads 1: CPU usage 1000%, average elapsed 1765ms.
20 threads, loop 100 times, set op number threads 1: CPU usage 2000%, average elapsed 4789ms.

**Comment by bitnick10** [comment]
How about 2 threads or 4 threads

**Comment by wizardk** [comment]
@bitnick10 

CPU (MLAS+Eigen)
1 thread, loop 100 times, set op number threads 1: CPU usage 100%, average elapsed 552ms.
**2 threads, loop 100 times, set op number threads 1: CPU usage 200%, average elapsed 573ms.
4 threads, loop 100 times, set op number threads 1: CPU usage 400%, average elapsed 683ms.
6 threads, loop 100 times, set op number threads 1: CPU usage 600%, average elapsed 880ms.
8 threads, loop 100 times, set op number threads 1: CPU usage 800%, average elapsed 1304ms.**
10 threads, loop 100 times, set op number threads 1: CPU usage 1000%, average elapsed 1745ms.
20 threads, loop 100 times, set op number threads 1: CPU usage 2000%, average elapsed 4912ms.

This is really rapid deteriorations of performance.

**Comment by bitnick10** [comment]
yes I'm using keras for training, and I also used dlib to train,same result.My CPU is 8 core 16 threads and 3-4 threads is the best I can use,it's should be the RAM bandwidth bottleneck.

**Comment by wizardk** [comment]
@bitnick10 I have tested a simple code based on SIMD and it works well in parallel mode. It means there is no significantly deterioration of performance. I just cann't believe this degree of deterioration is only caused by RAM bandwidth bottleneck.

**Comment by snnn** [comment]
When you enabled OPENMP, by default it will try to utilize all your cpu cores, so if you set SetInterOpNumThreads to something other than 1, your cpu will be oversubscribed and the performance will be super bad. So, please
1. Either enable openmp and SetInterOpNumThreads/SetIntraOpNumThreads to 1
2. Or disable openmp and SetInterOpNumThreads/SetIntraOpNumThreads to number of cpu cores minus 1.

**Comment by wizardk** [comment]
@snnn dude, please see my post seriously.

I have set OMP_NUM_THREADS and XXXOpNumThreads to be 1 to ensure one thread uses one core. There are 48 cores and CPU usage looks normal.

**Comment by wizardk** [comment]
@snnn It's all about RAM bandwidth. You can see this [https://github.com/pytorch/pytorch/issues/26948](url).
