### ISSUE TITLE
OrtCustomOp for CUDA Execution provider ?

### ISSUE THREAD

**Issue by tbfd** [microsoft/onnxruntime#2513]
Hi,

I have a very specific operator that needs to be executed with CUDA for performance reasons. All the options for implementing it are not clear for me.
I've tried the OrtCustomOp API with CPU EP and I found it very convenient. Is there a way to use it with CUDA EP ?

Thanks for your assistance!

**Comment by skottmckay** [comment]
Have you tried using kCudaExecutionProvider as the value in the Provider call of the KernelDefBuilder?

https://github.com/microsoft/onnxruntime/blob/bbe32f0990c4bbc8b0dc5a2221ee24b705e2a4ee/onnxruntime/test/framework/local_kernel_registry_test.cc#L87-L95

**Comment by faxu** [comment]
@tbfd do you still require further assistance on this issue?

**Comment by pranavsharma** [comment]
@tbfd have you gone through [this](https://github.com/microsoft/onnxruntime/blob/master/docs/AddingCustomOp.md#1-using-the-experimental-custom-op-api-in-the-c-api-onnxruntime_c_apih)? Here's an [example](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_inference.cc#L257).

**Comment by pranavsharma** [comment]
Looks like this has been resolved already and there's a separate issue.
