### ISSUE TITLE
No such flag DNNL_PRODUCT_BUILD_MODE in dnnl v1.1.0

### ISSUE THREAD

**Issue by zealerww** [microsoft/onnxruntime#2537]
https://github.com/microsoft/onnxruntime/blob/master/cmake/external/dnnl.cmake#L80

in commit 05441242f8ab5b4846a382ac7902edb3c8cd5d90,  "build: add MKLDNN_WERROR and remove MKLDNN_PRODUCT_BUILD_MODE"

maybe we should use -DDNNL_WERROR=OFF，which is default.

**Comment by jywu-msft** [comment]
@sreekanth-yalachigere  , any comment?

**Comment by sreekanth-yalachigere** [comment]
yes. We don't need MKLDNN_PRODUCT_BUILD_MODE.
MKL_ROOT is also not used. We now have the following.

`CMAKE_ARGS -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_INSTALL_PREFIX=${DNNL_INSTALL}
`

Working on new PR. I will also delete unused patch.
https://github.com/microsoft/onnxruntime/blob/master/cmake/patches/mkldnn/constexpr.patch

@zealerww thank you.
