### ISSUE TITLE
set session_thread_pool_size failed.

### ISSUE THREAD

**Issue by YueshangGu** [Microsoft/onnxruntime#254]
According the [API](https://docs.microsoft.com/en-us/python/api/overview/azure/onnx/api-summary?view=azure-onnx-py#load-and-run-a-model). Class onnxruntime.SessionOptions should have attribute enable_sequential_execution and session_thread_pool_size. But when I can set the thread_pool_size, I got this error.
```
>>> import onnxruntime
>>> options = onnxruntime.SessionOptions()
>>> options.enable_sequential_execution = False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'onnxruntime.capi.onnxruntime_pybind11_state.SessionOptions' object has no attribute 'enable_sequential_execution'
>>> options.session_thread_pool_size = 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'onnxruntime.capi.onnxruntime_pybind11_state.SessionOptions' object has no attribute 'session_thread_pool_size'
```

**Comment by jywu-msft** [comment]
looks like these options are not in the 0.1.4 python package. 
the documentation reflect what's in master, and they do exist there.
https://github.com/Microsoft/onnxruntime/blob/master/onnxruntime/python/onnxruntime_pybind_state.cc#L253

**Comment by YueshangGu** [comment]
Got it! Thanks @jywu-msft 
So I need build onnxruntime from source to solve this question?

**Comment by pranavsharma** [comment]
> Got it! Thanks @jywu-msft
> So I need build onnxruntime from source to solve this question?

Correct.
