### ISSUE TITLE
error of /usr/bin/ld: can not find -ltinfo when building

### ISSUE THREAD

**Issue by verigle** [microsoft/onnxruntime#2541]
**Describe the bug**

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 18.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version:1.0
- Python version:3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):7
- CUDA/cuDNN version:10.1 / 7.5
- GPU model and memory: 4GB

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

[ 17%] Completed 'project_mkldnn'
[ 17%] Built target project_mkldnn
[ 21%] Built target onnx
[ 21%] Performing update step for 'project_ngraph'
[ 21%] Performing configure step for 'project_ngraph'
-- Current hash 7f5ad2435b48b296eb8798d9aacedc7fb706e477
-- NGRAPH_VERSION 0.26.0+7f5ad24
-- NGRAPH_VERSION_SHORT 0.26.0
-- NGRAPH_WHEEL_VERSION 0.26.0
-- NGRAPH_API_VERSION 0.26
-- NGRAPH_FORWARD_CMAKE_ARGS -DCMAKE_C_COMPILER=/usr/bin/cc;-DCMAKE_CXX_COMPILER=/usr/bin/c++;-DCMAKE_CXX_STANDARD:STRING=11;-DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON;-DCMAKE_CXX_EXTENSIONS:BOOL=OFF;-DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=ON;-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON;-DCMAKE_BUILD_TYPE=RelWithDebInfo
-- NGRAPH_CXX_STANDARD:                  11
-- NGRAPH_UNIT_TEST_ENABLE:              OFF
-- NGRAPH_TOOLS_ENABLE:                  OFF
-- NGRAPH_CPU_ENABLE:                    ON
-- NGRAPH_USE_LEGACY_MKLDNN:             OFF
-- NGRAPH_MLIR_ENABLE:                   OFF
-- NGRAPH_INTELGPU_ENABLE:               OFF
-- NGRAPH_INTERPRETER_ENABLE:            OFF
-- NGRAPH_NOP_ENABLE:                    ON
-- NGRAPH_GENERIC_CPU_ENABLE:            OFF
-- NGRAPH_DEBUG_ENABLE:                  OFF
-- NGRAPH_DEPRECATED_ENABLE:             OFF
-- NGRAPH_ONNX_IMPORT_ENABLE:            ON
-- NGRAPH_DEX_ONLY:                      OFF
-- NGRAPH_ENABLE_CPU_CONV_AUTO:          ON
-- NGRAPH_CODE_COVERAGE_ENABLE:          OFF
-- NGRAPH_LIB_VERSIONING_ENABLE:         OFF
-- NGRAPH_PYTHON_BUILD_ENABLE:           OFF
-- NGRAPH_USE_PREBUILT_LLVM:             ON
-- NGRAPH_PLAIDML_ENABLE:                OFF
-- NGRAPH_DISTRIBUTED_ENABLE:            OFF
-- NGRAPH_JSON_ENABLE:                   ON
-- NGRAPH_STATIC_LIB_ENABLE:             OFF
-- NGRAPH_INTERPRETER_STATIC_LIB_ENABLE: OFF
-- NGRAPH_CPU_STATIC_LIB_ENABLE:         OFF
-- NGRAPH_DYNAMIC_COMPONENTS_ENABLE:     ON
-- Installation directory: /media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/build/Linux/RelWithDebInfo/external/ngraph
-- CMAKE_BUILD_RPATH   $ORIGIN:/usr/lib/x86_64-linux-gnu/openmpi4/lib
-- CMAKE_INSTALL_RPATH $ORIGIN:/usr/lib/x86_64-linux-gnu/openmpi4/lib
-- Compile Flags:  -DEIGEN_MPL2_ONLY -DTBB_USE_THREADING_TOOLS -O2 -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong -march=native -DNGRAPH_CPU_ENABLE -DNGRAPH_DYNAMIC_COMPONENTS_ENABLE
-- Shared Link Flags:  -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now
-- CMAKE_CXX_FLAGS_RELEASE -O3 -DNDEBUG
-- CMAKE_CXX_FLAGS_DEBUG -O0 -g
-- Ubuntu version: 18.04 detected.
-- Configuring done
-- Generating done
-- Build files have been written to: /media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/build/Linux/RelWithDebInfo/ngraph/src/project_ngraph-build/tbb
make[3]: 进入目录“/media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/build/Linux/RelWithDebInfo/ngraph/src/project_ngraph-build/tbb”
make[4]: 进入目录“/media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/build/Linux/RelWithDebInfo/ngraph/src/project_ngraph-build/tbb”
make[5]: 进入目录“/media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/build/Linux/RelWithDebInfo/ngraph/src/project_ngraph-build/tbb”
make[5]: 离开目录“/media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/build/Linux/RelWithDebInfo/ngraph/src/project_ngraph-build/tbb”
[100%] Built target ext_tbb
make[4]: 离开目录“/media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/build/Linux/RelWithDebInfo/ngraph/src/project_ngraph-build/tbb”
make[3]: 离开目录“/media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/build/Linux/RelWithDebInfo/ngraph/src/project_ngraph-build/tbb”
-- Building Intel TBB: /usr/bin/make -j4 compiler=gcc tbb_build_dir=/media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/build/Linux/RelWithDebInfo/ngraph/src/project_ngraph-build/tbb_build tbb_build_prefix=tbb stdver=c++11
CMake Warning (dev) at cmake/external_tbb.cmake:36 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable TBB_ROOT is set to:

    /media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/build/Linux/RelWithDebInfo/ngraph/src/project_ngraph-build/tbb/tbb-src

  For compatibility, CMake is ignoring the variable.
Call Stack (most recent call first):
  CMakeLists.txt:600 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found TBB and imported target TBB::tbb
-- TBB so version: 2
-- tools disabled
-- unit tests disabled
-- Configuring done
-- Generating done
-- Build files have been written to: /media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/build/Linux/RelWithDebInfo/ngraph/src/project_ngraph-build
[ 21%] Performing build step for 'project_ngraph'
[  2%] Built target ext_protobuf
[  3%] Built target onnx_import_interface
[ 17%] Built target onnx_import
[ 19%] Built target ext_json
[ 69%] Built target ngraph
[ 70%] Built target ext_llvm
[ 72%] Built target ext_eigen
[ 74%] Built target ext_mkl
[ 76%] Built target ext_mkldnn
[ 77%] Built target resource_generator
[ 77%] Built target header_resource
[ 77%] Linking CXX shared library ../libcodegen.so
/usr/bin/ld: 找不到 -ltinfo
collect2: error: ld returned 1 exit status
src/ngraph/codegen/CMakeFiles/codegen.dir/build.make:170: recipe for target 'src/ngraph/libcodegen.so' failed
make[5]: *** [src/ngraph/libcodegen.so] Error 1
CMakeFiles/Makefile2:740: recipe for target 'src/ngraph/codegen/CMakeFiles/codegen.dir/all' failed
make[4]: *** [src/ngraph/codegen/CMakeFiles/codegen.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/project_ngraph.dir/build.make:114: recipe for target 'ngraph/src/project_ngraph-stamp/project_ngraph-build' failed
make[2]: *** [ngraph/src/project_ngraph-stamp/project_ngraph-build] Error 2
CMakeFiles/Makefile2:794: recipe for target 'CMakeFiles/project_ngraph.dir/all' failed
make[1]: *** [CMakeFiles/project_ngraph.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/tools/ci_build/build.py", line 995, in <module>
    sys.exit(main())
  File "/media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/tools/ci_build/build.py", line 929, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "/media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/tools/ci_build/build.py", line 407, in build_targets
    run_subprocess(cmd_args)
  File "/media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/tools/ci_build/build.py", line 193, in run_subprocess
    return subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/verigle/softwares/cmake-3.16.0-Linux-x86_64/bin/cmake', '--build', '/media/verigle/4C58EFCE58EFB53C/Projects/Github/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo']' returned non-zero exit status 2.

**Comment by jywu-msft** [comment]
sudo apt-get install libtinfo-dev

**Comment by jywu-msft** [comment]
I assume this solved your issue. re-open if not the case. thanks.
