### ISSUE TITLE
exception when Loop input "M" "cond" are empty strings

### ISSUE THREAD

**Issue by pengwa** [Microsoft/onnxruntime#255]
**Describe the bug**
In ONNX Loop spec, "M" and "cond" input can be empty strings, if we don't need them. 

Running the Loop, we will have following error:

> RuntimeError: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Node:Loop__5 Node (Loop__5)'s input 1 is marked single but has an empty string in the graph

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master
- Python version: 3.5
- GCC/Compiler version (if compiling from source): VS2017
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Define a Loop having empty strings for M or cond input, run it.

**Expected behavior**
should run without errors.

**Screenshots**

**Additional context**

**Comment by pengwa** [comment]
Happy new year!

**Comment by skottmckay** [comment]
This is an ONNX level issue.

https://github.com/onnx/onnx/pull/1587
