### ISSUE TITLE
ONNX on Windows x86

### ISSUE THREAD

**Issue by konabuta** [microsoft/onnxruntime#2555]
**Is your feature request related to a problem? Please describe.**
There are many x86 applications and Windows machines in Manufacturing industry. It is impossible or very complex to ship ONNX model on ML.NET C# application.

**System information**
- ONNX Runtime version (you are using): 1.0

**Describe the solution you'd like**
My customers in Manufacturing want to deploy ONNX models on their current running Windows x86 machines.

**Describe alternatives you've considered**
n/a

**Additional context**
I thinks onnxruntime on Windows x86 is under testing phase.  Any ETA for production ?

**Comment by faxu** [comment]
Can you clarify what you need? The Nuget package supports windows x86  https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime Also uploaded in github release assets - https://github.com/microsoft/onnxruntime/releases/download/v1.0.0/onnxruntime-win-x86-1.0.0.zip

Are your customers using ORT through ML.NET or directly?

**Comment by konabuta** [comment]
Thanks @faxu . We want onnxruntime on windows 32bit for ML.NET.  Is this officially supported ? 

I'm asking because I'm confusing because the combination matrix is not stable as below (see _Installation Instructions_).

It says C# on Windows 32bit is not tested.
![image](https://user-images.githubusercontent.com/3815677/70366822-b747da80-18dd-11ea-89b7-f52bd391b8ab.png)

It says C# on Windows 32bit already available as NuGet package.
![image](https://user-images.githubusercontent.com/3815677/70366829-c75fba00-18dd-11ea-890a-ed9ea456066b.png)

Which one is really correct ?

**Comment by faxu** [comment]
The 2nd, which mentions the Nuget package. 

Re: the matrix - that's weird; i'm not able to repro that first screen. Are you able to consistently repro it and what OS and browser are you using?
