### ISSUE TITLE
What's the difference between ORT with TensorRT execution provider and onnx with Tensor RT backend?

### ISSUE THREAD

**Issue by sw6y15** [microsoft/onnxruntime#2571]
Hi, I would like to know the difference between the two inference method of [onnxruntime-tensorrt](https://github.com/Azure-Samples/onnxruntime-iot-edge/blob/267362ab0306c5f97365c372adf06f9604314fef/modules/InferenceModule/main.py#L47) and [onnx-tensorrt](https://github.com/onnx/onnx-tensorrt#onnx-python-backend-usage). Could you explain a little to help to choose which method to use?

**Comment by jywu-msft** [comment]
see another thread on this: https://github.com/microsoft/onnxruntime/issues/1452 
The short answer is that onnxruntime aims to have the most complete implementation of the ONNX standard. onnxruntime can delegate subgraph execution to tensorrt if it can support it. but in cases where tensorrt can't, onnxruntime can execute on CUDA or CPU.

**Comment by sw6y15** [comment]
Many thanks for your answer. And I think this feature are also in other EP such as openvino. I've found if the model has the op not support in the EP, it will totally roll back to use basic cpu one.
