### ISSUE TITLE
Can't inference model that has input with dynamic axises using DirectML provider

### ISSUE THREAD

**Issue by thebatua** [microsoft/onnxruntime#2573]
Can't inference model that has input with dynamic axises using DirectML provider.
Exception is thrown with message:

> Non-zero status code returned while running Add node. Name:'' Status Message: D:\test\onnxruntime\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(1682)\onnxruntime.dll!00007FF89589A72A: (caller: 00007FF89589A488) Exception(2) tid(3b44) 80070057 The parameter is incorrect.

Looks like issue with add layer where one of the inputs has dynamic axis.
In my case this input has shape [1,3,dynamic,dynamic]

Inference on CPU works well.

**System information**
- OS - Windows 10 1903
- ONNX Runtime installed from source with DML provider:
- ONNX Runtime version 1.0.0:
- Python version: 3.6
- Visual Studio version : 2019
- GPU model and memory: NVidia GT1070, AMD Radeon RX560

**Comment by jeffbloo** [comment]
Thanks for reporting the failure.  

We are unable to reproduce the problem with an isolated test.  This suggests the problem has one of two root causes.   First, a faulty kernel used to compute an upstream operator, which results in tensors of incompatible shapes reaching Add.   Second, a faulty model which results in incompatible tensor shapes, which only fails on the GPU due to extra validation in that path.

Would you be able to share more about the model to help locate the root cause?  It may also help to narrow down the problem by disabling specific registrations within this file:
core\providers\dml\DmlExecutionProvider\src\Operators\OperatorRegistration.cpp

**Comment by thebatua** [comment]
Thanks for answer and my apollogises for late answer.
I spent some time on investigting this issue, a bit debugged onnxruntime library... and seems like issue is not with "Add" node.
A bit history. Currently we use on the project onnxruntime v0.5.0 and run ONNX models converted 
from PyTorch. Now we are trying new version. To convert pytorch model to the ONNX we had to specify size of the input image(in our case 512x512). But in fact our model might work with any  size of input image. Since v1.0.0 onnxruntime throws exception if size of input layer is different 
from size of input image we have to mark shape of the input layer as dynamic. The latest pytorch converter supports dynamic axes. So I used new converter and mark W and H as dynamic. As result some models work well but some have issues.

So debugged onnxruntime and found place where exception was thrown:
   `Dml/OperatorAutherHelper\OperatorHelper.cpp::BroadcastTensorShape()`
on line :
   `ML_CHECK_VALID_ARGUMENT((inDimension0 == inDimension1) || (inDimension0 == 1) || (inDimension1 == 1));`

Shapes of inputs of "Add" node are different and differ by 1 px.
First input is Conv layer second is Upsample layer.

In the next step I investigated difference between two models ... There is an "Resize" layer instead of "Upsample" layer in the model we currently use and that was converted by older pytoch converter. And looks like "Resize" and "Upsample" layers works in the different way and produces different output shapes.

**Comment by Li-chunming** [comment]
> Thanks for answer and my apollogises for late answer.
> I spent some time on investigting this issue, a bit debugged onnxruntime library... and seems like issue is not with "Add" node.
> A bit history. Currently we use on the project onnxruntime v0.5.0 and run ONNX models converted
> from PyTorch. Now we are trying new version. To convert pytorch model to the ONNX we had to specify size of the input image(in our case 512x512). But in fact our model might work with any  size of input image. Since v1.0.0 onnxruntime throws exception if size of input layer is different
> from size of input image we have to mark shape of the input layer as dynamic. The latest pytorch converter supports dynamic axes. So I used new converter and mark W and H as dynamic. As result some models work well but some have issues.
> So debugged onnxruntime and found place where exception was thrown:
> Dml/OperatorAutherHelper\OperatorHelper.cpp::BroadcastTensorShape()
> on line :
> ML_CHECK_VALID_ARGUMENT((inDimension0 == inDimension1) || (inDimension0 == 1) || (inDimension1 == 1));
> Shapes of inputs of "Add" node are different and differ by 1 px.
> First input is "Conv" layer second is "Upsample" layer.
> In the next step I investigated difference between two models ... There is an "Resize" layer instead of "Upsample" layer in the model we currently use and that was converted by older pytoch converter. And looks like "Resize" and "Upsample" layers works in the different way and produces different output shapes.

Hi,I got a familiar [problem](https://github.com/microsoft/onnxruntime/issues/3168),the model I used is Maskrcnn(Pytorch),and when I run the onnxruntime to do inference,  it happened:
![image](https://user-images.githubusercontent.com/59553759/76166337-b3577d00-6198-11ea-81da-ee22af2adf76.png)
Then I have checked my model , and found the '451' Add node:
![image](https://user-images.githubusercontent.com/59553759/76166475-c9197200-6199-11ea-994d-8b5239c6edc2.png)

It shows the Add node is connected with Resize, and I guess it has the same reason as yours. Can you give me some suggestions?
