### ISSUE TITLE
Unable to build onnxruntime with docker build for ARM32

### ISSUE THREAD

**Issue by Saj1234** [microsoft/onnxruntime#2585]
**Describe the bug**
I am trying to build onnxruntime by following the instruction [here](https://github.com/microsoft/onnxruntime/tree/master/dockerfiles#arm-32v7) for ARM32.
When it runs the **RUN ./build.sh ${BUILDARGS} --update --build** step in the docker file, it completes about 39% of the build and fails with the errors listed below. I tried running the same build on Ubantu and MacOs but fails at the same point. Tried my luck with updating the CMake version to 3.16.0 but didn't help. 
Error seem to be an unused parameter. Not sure if this should be a warning instead.
`error: unused parameter ‘info’ [-Werror=unused-parameter]
   explicit CPUExecutionProvider(const CPUExecutionProviderInfo& info)`
Please see the full error log below.

**Urgency**
Medium to high as I am trying to get tiny YOLO-V3 running on a container as a module in an edge device for a demo.

**System information**
- Tried building on Linux Ubuntu 16.x
- Tried building on macOS Mojave 10.14.6
- Docker CE version: 19.03.1, build 74b1e89

**To Reproduce**
Download the docker file for ARM32 [here](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.arm32v7) into a directory called onnx-build
Run docker build: `docker build -t onnxruntime-arm32v7 -f Dockerfile.arm32v7 .`

**Expected behavior**
build should complete successfully to extract the wheel file.
I have tried numerous workarounds to get this working but haven't had much luck so far. 
Would be great if you guys can look into this.
Thanks!

Error logs:
`[ 39%] Building CXX object CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/controlflow/scan_utils.cc.o
In file included from /code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/ThreadPool:64:0,
                 from /code/onnxruntime/include/onnxruntime/core/platform/threadpool.h:17,
                 from /code/onnxruntime/onnxruntime/core/framework/session_state.h:28,
                 from /code/onnxruntime/onnxruntime/core/framework/op_kernel_context_internal.h:8,
                 from /code/onnxruntime/onnxruntime/core/providers/cpu/controlflow/scan_utils.cc:17:
/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/src/ThreadPool/EventCount.h:171:56: warning: requested alignment 128 is larger than 64 [-Wattributes]
     EIGEN_ALIGN_TO_BOUNDARY(128) std::atomic<uint64_t> next;
                                                        ^~~~
[ 39%] Building CXX object CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/controlflow/utils.cc.o
In file included from /code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/ThreadPool:64:0,
                 from /code/onnxruntime/include/onnxruntime/core/platform/threadpool.h:17,
                 from /code/onnxruntime/onnxruntime/core/framework/session_state.h:28,
                 from /code/onnxruntime/onnxruntime/core/providers/cpu/controlflow/utils.cc:9:
/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/src/ThreadPool/EventCount.h:171:56: warning: requested alignment 128 is larger than 64 [-Wattributes]
     EIGEN_ALIGN_TO_BOUNDARY(128) std::atomic<uint64_t> next;
                                                        ^~~~
[ 39%] Building CXX object CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.cc.o
In file included from /code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.cc:4:0:
/code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.h: In constructor ‘onnxruntime::CPUExecutionProvider::CPUExecutionProvider(const onnxruntime::CPUExecutionProviderInfo&)’:
/code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.h:28:65: error: unused parameter ‘info’ [-Werror=unused-parameter]
   explicit CPUExecutionProvider(const CPUExecutionProviderInfo& info)
                                                                 ^~~~
cc1plus: all warnings being treated as errors
CMakeFiles/onnxruntime_providers.dir/build.make:153: recipe for target 'CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.cc.o] Error 1
CMakeFiles/Makefile2:420: recipe for target 'CMakeFiles/onnxruntime_providers.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_providers.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/code/onnxruntime/tools/ci_build/build.py", line 1042, in <module>
    sys.exit(main())
  File "/code/onnxruntime/tools/ci_build/build.py", line 974, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "/code/onnxruntime/tools/ci_build/build.py", line 414, in build_targets
    run_subprocess(cmd_args)
  File "/code/onnxruntime/tools/ci_build/build.py", line 197, in run_subprocess
    completed_process = subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/code/onnxruntime/build/Linux/MinSizeRel', '--config', 'MinSizeRel']' returned non-zero exit status 2
The command '/bin/sh -c ./build.sh ${BUILDARGS} --update --build' returned a non-zero code: 1`

**Comment by jywu-msft** [comment]
looks like there are build warnings on arm32.
try https://github.com/microsoft/onnxruntime/issues/2152#issuecomment-543915936
as a workaround

**Comment by Saj1234** [comment]
> looks like there are build warnings on arm32.
> try [#2152 (comment)](https://github.com/microsoft/onnxruntime/issues/2152#issuecomment-543915936)
> as a workaround
I am using the docker file to build instead from source. Let me change it and try building from source. 
Will let you know soon. 
thanks.

**Comment by Saj1234** [comment]
@jywu-msft I commented out the line specified in the issue you pointed out and ran the build but still getting the same error.
I used **balenalib/raspberrypi3-python:latest-stretch-build** image for native compilation on ARM32 by following the instructions in [https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#ARM](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#ARM)
After cloning latest onnnxruntime repo in the container, i removed [this line in build.py](https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/build.py#L329) and ran the build. Still got the same error. 
**_error: unused parameter ‘info’ [-Werror=unused-parameter]_**
 
As an alternative, I tried the docker file build for ARM 32 by forking the latest onnxruntime repo and deleting the line in build.py on the forked repo. Then updated the docker file to point to the  forked repo and tried building. Still got the same error.

 Error:
`[ 39%] Building CXX object CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/controlflow/scan_utils.cc.o
In file included from /code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/ThreadPool:64:0,
                 from /code/onnxruntime/include/onnxruntime/core/platform/threadpool.h:17,
                 from /code/onnxruntime/onnxruntime/core/framework/session_state.h:28,
                 from /code/onnxruntime/onnxruntime/core/framework/op_kernel_context_internal.h:8,
                 from /code/onnxruntime/onnxruntime/core/providers/cpu/controlflow/scan_utils.cc:17:
/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/src/ThreadPool/EventCount.h:171:56: warning: requested alignment 128 is larger than 64 [-Wattributes]
     EIGEN_ALIGN_TO_BOUNDARY(128) std::atomic<uint64_t> next;
                                                        ^~~~
[ 39%] Building CXX object CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/controlflow/utils.cc.o
In file included from /code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/ThreadPool:64:0,
                 from /code/onnxruntime/include/onnxruntime/core/platform/threadpool.h:17,
                 from /code/onnxruntime/onnxruntime/core/framework/session_state.h:28,
                 from /code/onnxruntime/onnxruntime/core/providers/cpu/controlflow/utils.cc:9:
/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/src/ThreadPool/EventCount.h:171:56: warning: requested alignment 128 is larger than 64 [-Wattributes]
     EIGEN_ALIGN_TO_BOUNDARY(128) std::atomic<uint64_t> next;
                                                        ^~~~
[ 39%] Building CXX object CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.cc.o
In file included from /code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.cc:4:0:
/code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.h: In constructor ‘onnxruntime::CPUExecutionProvider::CPUExecutionProvider(const onnxruntime::CPUExecutionProviderInfo&)’:
/code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.h:28:65: error: unused parameter ‘info’ [-Werror=unused-parameter]
   explicit CPUExecutionProvider(const CPUExecutionProviderInfo& info)
                                                                 ^~~~
cc1plus: all warnings being treated as errors
CMakeFiles/onnxruntime_providers.dir/build.make:153: recipe for target 'CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.cc.o] Error 1
CMakeFiles/Makefile2:420: recipe for target 'CMakeFiles/onnxruntime_providers.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_providers.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/code/onnxruntime/tools/ci_build/build.py", line 1042, in <module>
    sys.exit(main())
  File "/code/onnxruntime/tools/ci_build/build.py", line 974, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "/code/onnxruntime/tools/ci_build/build.py", line 414, in build_targets
    run_subprocess(cmd_args)
  File "/code/onnxruntime/tools/ci_build/build.py", line 197, in run_subprocess
    completed_process = subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/code/onnxruntime/build/Linux/MinSizeRel', '--config', 'MinSizeRel']' returned non-zero exit status 2
root@460bfec04c21:/code/onnxruntime# 
`

**Comment by jywu-msft** [comment]
> @jywu-msft I commented out the line specified in the issue you pointed out and ran the build but still getting the same error.
> I used **balenalib/raspberrypi3-python:latest-stretch-build** image for native compilation on ARM32 by following the instructions in https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#ARM
> After cloning latest onnnxruntime repo in the container, i removed [this line in build.py](https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/build.py#L329) and ran the build. Still got the same error.
> **_error: unused parameter ‘info’ [-Werror=unused-parameter]_**
> 
> As an alternative, I tried the docker file build for ARM 32 by forking the latest onnxruntime repo and deleting the line in build.py on the forked repo. Then updated the docker file to point to the forked repo and tried building. Still got the same error.
> 
> Error:
> 
> ```
> In file included from /code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/ThreadPool:64:0,
>                  from /code/onnxruntime/include/onnxruntime/core/platform/threadpool.h:17,
>                  from /code/onnxruntime/onnxruntime/core/framework/session_state.h:28,
>                  from /code/onnxruntime/onnxruntime/core/framework/op_kernel_context_internal.h:8,
>                  from /code/onnxruntime/onnxruntime/core/providers/cpu/controlflow/scan_utils.cc:17:
> /code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/src/ThreadPool/EventCount.h:171:56: warning: requested alignment 128 is larger than 64 [-Wattributes]
>      EIGEN_ALIGN_TO_BOUNDARY(128) std::atomic<uint64_t> next;
>                                                         ^~~~
> [ 39%] Building CXX object CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/controlflow/utils.cc.o
> In file included from /code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/ThreadPool:64:0,
>                  from /code/onnxruntime/include/onnxruntime/core/platform/threadpool.h:17,
>                  from /code/onnxruntime/onnxruntime/core/framework/session_state.h:28,
>                  from /code/onnxruntime/onnxruntime/core/providers/cpu/controlflow/utils.cc:9:
> /code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/src/ThreadPool/EventCount.h:171:56: warning: requested alignment 128 is larger than 64 [-Wattributes]
>      EIGEN_ALIGN_TO_BOUNDARY(128) std::atomic<uint64_t> next;
>                                                         ^~~~
> [ 39%] Building CXX object CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.cc.o
> In file included from /code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.cc:4:0:
> /code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.h: In constructor ‘onnxruntime::CPUExecutionProvider::CPUExecutionProvider(const onnxruntime::CPUExecutionProviderInfo&)’:
> /code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.h:28:65: error: unused parameter ‘info’ [-Werror=unused-parameter]
>    explicit CPUExecutionProvider(const CPUExecutionProviderInfo& info)
>                                                                  ^~~~
> cc1plus: all warnings being treated as errors
> CMakeFiles/onnxruntime_providers.dir/build.make:153: recipe for target 'CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.cc.o' failed
> make[2]: *** [CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.cc.o] Error 1
> CMakeFiles/Makefile2:420: recipe for target 'CMakeFiles/onnxruntime_providers.dir/all' failed
> make[1]: *** [CMakeFiles/onnxruntime_providers.dir/all] Error 2
> Makefile:140: recipe for target 'all' failed
> make: *** [all] Error 2
> Traceback (most recent call last):
>   File "/code/onnxruntime/tools/ci_build/build.py", line 1042, in <module>
>     sys.exit(main())
>   File "/code/onnxruntime/tools/ci_build/build.py", line 974, in main
>     build_targets(cmake_path, build_dir, configs, args.parallel)
>   File "/code/onnxruntime/tools/ci_build/build.py", line 414, in build_targets
>     run_subprocess(cmd_args)
>   File "/code/onnxruntime/tools/ci_build/build.py", line 197, in run_subprocess
>     completed_process = subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
>   File "/usr/lib/python3.5/subprocess.py", line 398, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/code/onnxruntime/build/Linux/MinSizeRel', '--config', 'MinSizeRel']' returned non-zero exit status 2
> root@460bfec04c21:/code/onnxruntime# 
> ```

It should be this line to comment out:
https://github.com/microsoft/onnxruntime/blob/1ee250def883d2630c8ab18019509668dbdda6e3/tools/ci_build/build.py#L288

**Comment by jywu-msft** [comment]
Sorry. It should have been this line:
Dev mode option. The file changed since the last issue so the line number is different now.

https://github.com/microsoft/onnxruntime/blob/1ee250def883d2630c8ab18019509668dbdda6e3/tools/ci_build/build.py#L288

**Comment by Saj1234** [comment]
It was the incorrect line indeed!. Removed the correct line and I was able to successfully build it.
Thanks for your help 👍
