### ISSUE TITLE
Missing assembly when using "Produce single file"

### ISSUE THREAD

**Issue by Telavian** [microsoft/onnxruntime#2591]
**Description**
Not sure if this is a VS issue or a onnx runtime issue.

I have a WPF application (.net core 3.1) which references a common library which has a reference to Microsoft.ML.OnnxRuntime.

When publishing the WPF application in VS and using the "Produce single file" option it appears something is not included or not referenced correctly.

**To Reproduce**
1. Create a .net core 3.1 WPF application which references Microsoft.ML.OnnxRuntime.
2. Publish application using option: Product single file

**Expected behavior**
Application should load referenced assemblies and open correctly.

**Error**
```
Description: A .NET Core application failed.
Application: App.exe
Path: C:\App.exe
Message: Error:
  An assembly specified in the application dependencies manifest (App.deps.json) was not found:
    package: 'Microsoft.ML.OnnxRuntime', version: '0.5.1'
    path: 'runtimes/win-x64/native/onnxruntime.pdb'
```

**Comment by Telavian** [comment]
Jumped the gun a little.
Seems related to the fact that the pdb is included.
https://github.com/dotnet/core/issues/3455

Is the pdb needed for an end user?

**Comment by jignparm** [comment]
Based on the link you posted above, it seems like a dotnet CLI issue. 

When publishing an app using `/p:PublishSingleFile=true`, if a pdb file is encountered, it seems to throw an exception.

The pdb file is useful for debugging purposes -- it is strictly not required for running the app, but is good to have in case any exceptions are encountered and require detailed debugging.

**Comment by Telavian** [comment]
True. However as others have mentioned [here](https://github.com/microsoft/onnxruntime/issues/102), it would be nice if the pdb was included separately because it is large and it is not needed in general.

It would also fix this issue.

**Comment by jignparm** [comment]
Based on the thread here https://github.com/dotnet/cli/issues/12723, does adding `IncludeSymbolsInSingleFile` work for your application? How about `ExcludeSymbolsFromSingleFile` property as an alternative?

```csproj
<PropertyGroup>
    <IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile>
</PropertyGroup>
```

Another option might be to write a custom function to remove the pdb file after restoring NuGet packages.

Even if pdb files are not used in general (debugging is usually a rare case), NuGet packages are allowed to contain them. If there's an easy work around for WPF applications, by using the property tags above or else auto-deleting the pdb files after installation, it would be a better route than dropping the symbols files entirely (or shipping them in different packages).

**Comment by Telavian** [comment]
I have been using IncludeSymbolsInSingleFile which does work. I did not know about ExcludeSymbolsFromSingleFile however I can test that which will probably work also.

Therefore there really is no issue with these additional settings.
