### ISSUE TITLE
Unsupported onnx data type uint8?

### ISSUE THREAD

**Issue by zealerww** [microsoft/onnxruntime#2603]
when i ran a model with a dynamic shape uint8 input in trt, i got this error?
it mean trt not support uint8 onnx model or something else ?

**Comment by askhade** [comment]
Which operator in your model is using uint8 data type?

**Comment by aif2017** [comment]
----------------------------------------------------------------                                                                                                Input filename:   model.onnx                                                                                                                                    ONNX IR version:  0.0.6                                                                                                                                         Opset version:    11                                                                                                                                            Producer name:    tf2onnx                                                                                                                                       Producer version: 1.5.5                                                                                                                                         Domain:                                                                                                                                                         Model version:    0                                                                                                                                             Doc string:                                                                                                                                                     ----------------------------------------------------------------                                                                                                Writing ONNX model (without weights) as text to my_engine.txt                                                                                                   Parsing model                                                                                                                                                   Unsupported ONNX data type: UINT8 (2)                                                                                                                           ERROR: image_tensor:0:190 In function importInput:                                                                                                              [8] Assertion failed: convertDtype(onnxDtype.elem_type(), &trtDtype)
