### ISSUE TITLE
Is there a ok onnxruntime_perf_test demo  there?

### ISSUE THREAD

**Issue by smilexin** [microsoft/onnxruntime#2618]
I use the onnxruntime_perf_test.exe to run testdata/aqueezenet/ or any other models in testdata dir, but it always can't parse the input data, Is there some sample code to demonstrate how to construct the format of input and model? Thanks~  

$ ./onnxruntime_perf_test.exe -m times -e cuda -s -v ./testdata/squeezenet/model.onnx ./testdata/squeezenet/
==>
**there is no test input data for input data_0 and model .
Run failed:failed to initialize.**

I have also try onnx_run_test, only the transform\matmul_add_fusion\2Input can run successfully.

**Comment by yufenglee** [comment]
@smilexin, the model and input need to follow the same folder structure as onnx_test_runner: https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/test/perftest

**Comment by snnn** [comment]
```
onnxruntime_perf_test -o 99 -t 120 -x 3 C:\lotus_data\resnet_v2_50\model.onnx  1.csv
```

You may get the model and test data from onnx model zoo. For example. download https://s3.amazonaws.com/onnx-model-zoo/squeezenet/squeezenet1.1/squeezenet1.1.tar.gz and extract the whole zip.

**Comment by smilexin** [comment]
@yufenglee Thanks~
@snnn Thanks very much, I followe your guide, download the model and execute  command as you do, I'm on windows platform git bash MINGWIN64 terminal , but it still can't find the model and input data path, command:
./onnxruntime_perf_test.exe -x 3 -s -v C:/squeezenet1.1/squeezenet1.1.onnx 1.csv
 I print out  detailed message, find that:
in PerformanceRunner::Initialize()，
 ToMBString(test_case_dir) => "."
ToMBString(model_name) =>  "."
in OnnxTestCase::LoadTestData:
ToMBString(test_data_dirs_[id]) => .\testdata
ToMBString(test_data_pb) => .\testdata\inputs.pb

It always find the testdata dir in the RelWithDebInfo(Release) dir, seems bug exist in path parse logic. looking forward for your further help.  :)

**Comment by snnn** [comment]
Where does the "testdata" string come from? We didn't hardcode such a string at anywhere.

**Comment by snnn** [comment]
Windows uses '\\' as path separator, not '/'
```
.\onnxruntime_perf_test.exe -x 3 -s -v C:\squeezenet1.1\squeezenet1.1.onnx 1.csv
```
