### ISSUE TITLE
In quantization tool there is one module quantize i am not able to install

### ISSUE THREAD

**Issue by paragikjain** [microsoft/onnxruntime#2619]
When I am trying to install module Quantize i am getting error :

<pre>$ sudo pip install quantize
<font color="#C4A000">WARNING: The directory &apos;/home/parag.j/.cache/pip/http&apos; or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo&apos;s -H flag.</font>
<font color="#C4A000">WARNING: The directory &apos;/home/parag.j/.cache/pip&apos; or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo&apos;s -H flag.</font>
Processing ./.cache/pip/wheels/0f/40/31/0ad84e035a9d2e8b0277c518d8edab90a37a019ccb918b1d8e/quantize-0.0.4-cp36-none-any.whl
Requirement already satisfied: greenlet==0.4.5 in /usr/local/lib/python3.6/dist-packages (from quantize) (0.4.5)
Processing ./.cache/pip/wheels/28/fa/34/c268d72ff66056dedfc2aaba618b71f474fa2bac2e3bf2516a/gevent-1.0.1-cp36-cp36m-linux_x86_64.whl
Collecting python-rtmidi==0.5b1
  Downloading https://files.pythonhosted.org/packages/8b/ea/791c3c72b21c87ca84c5ba65e33db27edfbdebc2ed8df59ef2561be2ab47/python-rtmidi-0.5b1.tar.bz2 (152kB)
     |████████████████████████████████| 153kB 1.6MB/s 
Requirement already satisfied: mido==1.1.12 in /usr/local/lib/python3.6/dist-packages (from quantize) (1.1.12)
Building wheels for collected packages: python-rtmidi
  Building wheel for python-rtmidi (setup.py) ... error
<font color="#CC0000">  ERROR: Command errored out with exit status 1:</font>
<font color="#CC0000">   command: /usr/bin/python3 -u -c &apos;import sys, setuptools, tokenize; sys.argv[0] = &apos;&quot;&apos;&quot;&apos;/tmp/pip-install-xv53kyh1/python-rtmidi/setup.py&apos;&quot;&apos;&quot;&apos;; __file__=&apos;&quot;&apos;&quot;&apos;/tmp/pip-install-xv53kyh1/python-rtmidi/setup.py&apos;&quot;&apos;&quot;&apos;;f=getattr(tokenize, &apos;&quot;&apos;&quot;&apos;open&apos;&quot;&apos;&quot;&apos;, open)(__file__);code=f.read().replace(&apos;&quot;&apos;&quot;&apos;\r\n&apos;&quot;&apos;&quot;&apos;, &apos;&quot;&apos;&quot;&apos;\n&apos;&quot;&apos;&quot;&apos;);f.close();exec(compile(code, __file__, &apos;&quot;&apos;&quot;&apos;exec&apos;&quot;&apos;&quot;&apos;))&apos; bdist_wheel -d /tmp/pip-wheel-6hm21jj4 --python-tag cp36</font>
<font color="#CC0000">       cwd: /tmp/pip-install-xv53kyh1/python-rtmidi/</font>
<font color="#CC0000">  Complete output (29 lines):</font>
<font color="#CC0000">  running bdist_wheel</font>
<font color="#CC0000">  running build</font>
<font color="#CC0000">  running build_py</font>
<font color="#CC0000">  creating build</font>
<font color="#CC0000">  creating build/lib.linux-x86_64-3.6</font>
<font color="#CC0000">  creating build/lib.linux-x86_64-3.6/rtmidi</font>
<font color="#CC0000">  copying rtmidi/midiconstants.py -&gt; build/lib.linux-x86_64-3.6/rtmidi</font>
<font color="#CC0000">  copying rtmidi/midiutil.py -&gt; build/lib.linux-x86_64-3.6/rtmidi</font>
<font color="#CC0000">  copying rtmidi/__init__.py -&gt; build/lib.linux-x86_64-3.6/rtmidi</font>
<font color="#CC0000">  copying rtmidi/release.py -&gt; build/lib.linux-x86_64-3.6/rtmidi</font>
<font color="#CC0000">  creating build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">  copying examples/osc2midi/midievents.py -&gt; build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">  copying examples/osc2midi/__init__.py -&gt; build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">  copying examples/osc2midi/oscdispatcher.py -&gt; build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">  copying examples/osc2midi/device.py -&gt; build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">  copying examples/osc2midi/midiio.py -&gt; build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">  copying examples/osc2midi/lru_cache.py -&gt; build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">  copying examples/osc2midi/main.py -&gt; build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">  running build_ext</font>
<font color="#CC0000">  building &apos;rtmidi._rtmidi&apos; extension</font>
<font color="#CC0000">  creating build/temp.linux-x86_64-3.6</font>
<font color="#CC0000">  creating build/temp.linux-x86_64-3.6/src</font>
<font color="#CC0000">  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D__PYX_FORCE_INIT_THREADS -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc -I/usr/include/python3.6m -c src/_rtmidi.cpp -o build/temp.linux-x86_64-3.6/src/_rtmidi.o</font>
<font color="#CC0000">  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D__PYX_FORCE_INIT_THREADS -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc -I/usr/include/python3.6m -c src/RtMidi.cpp -o build/temp.linux-x86_64-3.6/src/RtMidi.o</font>
<font color="#CC0000">  src/RtMidi.cpp:1111:10: fatal error: alsa/asoundlib.h: No such file or directory</font>
<font color="#CC0000">   #include &lt;alsa/asoundlib.h&gt;</font>
<font color="#CC0000">            ^~~~~~~~~~~~~~~~~~</font>
<font color="#CC0000">  compilation terminated.</font>
<font color="#CC0000">  error: command &apos;x86_64-linux-gnu-gcc&apos; failed with exit status 1</font>
<font color="#CC0000">  ----------------------------------------</font>
<font color="#CC0000">  ERROR: Failed building wheel for python-rtmidi</font>
  Running setup.py clean for python-rtmidi
Failed to build python-rtmidi
Installing collected packages: gevent, python-rtmidi, quantize
    Running setup.py install for python-rtmidi ... error
<font color="#CC0000">    ERROR: Command errored out with exit status 1:</font>
<font color="#CC0000">     command: /usr/bin/python3 -u -c &apos;import sys, setuptools, tokenize; sys.argv[0] = &apos;&quot;&apos;&quot;&apos;/tmp/pip-install-xv53kyh1/python-rtmidi/setup.py&apos;&quot;&apos;&quot;&apos;; __file__=&apos;&quot;&apos;&quot;&apos;/tmp/pip-install-xv53kyh1/python-rtmidi/setup.py&apos;&quot;&apos;&quot;&apos;;f=getattr(tokenize, &apos;&quot;&apos;&quot;&apos;open&apos;&quot;&apos;&quot;&apos;, open)(__file__);code=f.read().replace(&apos;&quot;&apos;&quot;&apos;\r\n&apos;&quot;&apos;&quot;&apos;, &apos;&quot;&apos;&quot;&apos;\n&apos;&quot;&apos;&quot;&apos;);f.close();exec(compile(code, __file__, &apos;&quot;&apos;&quot;&apos;exec&apos;&quot;&apos;&quot;&apos;))&apos; install --record /tmp/pip-record-6geralxb/install-record.txt --single-version-externally-managed --compile</font>
<font color="#CC0000">         cwd: /tmp/pip-install-xv53kyh1/python-rtmidi/</font>
<font color="#CC0000">    Complete output (29 lines):</font>
<font color="#CC0000">    running install</font>
<font color="#CC0000">    running build</font>
<font color="#CC0000">    running build_py</font>
<font color="#CC0000">    creating build</font>
<font color="#CC0000">    creating build/lib.linux-x86_64-3.6</font>
<font color="#CC0000">    creating build/lib.linux-x86_64-3.6/rtmidi</font>
<font color="#CC0000">    copying rtmidi/midiconstants.py -&gt; build/lib.linux-x86_64-3.6/rtmidi</font>
<font color="#CC0000">    copying rtmidi/midiutil.py -&gt; build/lib.linux-x86_64-3.6/rtmidi</font>
<font color="#CC0000">    copying rtmidi/__init__.py -&gt; build/lib.linux-x86_64-3.6/rtmidi</font>
<font color="#CC0000">    copying rtmidi/release.py -&gt; build/lib.linux-x86_64-3.6/rtmidi</font>
<font color="#CC0000">    creating build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">    copying examples/osc2midi/midievents.py -&gt; build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">    copying examples/osc2midi/__init__.py -&gt; build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">    copying examples/osc2midi/oscdispatcher.py -&gt; build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">    copying examples/osc2midi/device.py -&gt; build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">    copying examples/osc2midi/midiio.py -&gt; build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">    copying examples/osc2midi/lru_cache.py -&gt; build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">    copying examples/osc2midi/main.py -&gt; build/lib.linux-x86_64-3.6/osc2midi</font>
<font color="#CC0000">    running build_ext</font>
<font color="#CC0000">    building &apos;rtmidi._rtmidi&apos; extension</font>
<font color="#CC0000">    creating build/temp.linux-x86_64-3.6</font>
<font color="#CC0000">    creating build/temp.linux-x86_64-3.6/src</font>
<font color="#CC0000">    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D__PYX_FORCE_INIT_THREADS -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc -I/usr/include/python3.6m -c src/_rtmidi.cpp -o build/temp.linux-x86_64-3.6/src/_rtmidi.o</font>
<font color="#CC0000">    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D__PYX_FORCE_INIT_THREADS -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc -I/usr/include/python3.6m -c src/RtMidi.cpp -o build/temp.linux-x86_64-3.6/src/RtMidi.o</font>
<font color="#CC0000">    src/RtMidi.cpp:1111:10: fatal error: alsa/asoundlib.h: No such file or directory</font>
<font color="#CC0000">     #include &lt;alsa/asoundlib.h&gt;</font>
<font color="#CC0000">              ^~~~~~~~~~~~~~~~~~</font>
<font color="#CC0000">    compilation terminated.</font>
<font color="#CC0000">    error: command &apos;x86_64-linux-gnu-gcc&apos; failed with exit status 1</font>
<font color="#CC0000">    ----------------------------------------</font>
<font color="#CC0000">ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c &apos;import sys, setuptools, tokenize; sys.argv[0] = &apos;&quot;&apos;&quot;&apos;/tmp/pip-install-xv53kyh1/python-rtmidi/setup.py&apos;&quot;&apos;&quot;&apos;; __file__=&apos;&quot;&apos;&quot;&apos;/tmp/pip-install-xv53kyh1/python-rtmidi/setup.py&apos;&quot;&apos;&quot;&apos;;f=getattr(tokenize, &apos;&quot;&apos;&quot;&apos;open&apos;&quot;&apos;&quot;&apos;, open)(__file__);code=f.read().replace(&apos;&quot;&apos;&quot;&apos;\r\n&apos;&quot;&apos;&quot;&apos;, &apos;&quot;&apos;&quot;&apos;\n&apos;&quot;&apos;&quot;&apos;);f.close();exec(compile(code, __file__, &apos;&quot;&apos;&quot;&apos;exec&apos;&quot;&apos;&quot;&apos;))&apos; install --record /tmp/pip-record-6geralxb/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.</font>
</pre>

**Comment by YIQIHYM** [comment]
same question?

**Comment by yufenglee** [comment]
@YIQIHYM , quantization is submodule of onnxruntime. Please use 'pip install onnxruntime'.

**Comment by YIQIHYM** [comment]
have  the  code?
