### ISSUE TITLE
During Quantization output model has 0 dimesion

### ISSUE THREAD

**Issue by paragikjain** [microsoft/onnxruntime#2620]
Hi i am trying to quantize onxx model using quantization tool.

My code is below for quantization:
    
    import onnx
    from quantize import quantize, QuantizationMode

    # Load the onnx model     
    model = onnx.load('3ddfa_optimized_withoutflatten.onnx')
    # Quantize
    quantized_model = quantize(model, quantization_mode=QuantizationMode.IntegerOps)
 
    # Save the quantized model
    onnx.save(quantized_model, 'quantized_model.onnx')

After this method the model i am getting has 0 dimensional model can anyone please tell me what all argument i have to pass in quantize function so i can get a proper model

**Comment by yuslepukhin** [comment]
Would it possible for you to share the model? There are no magic arguments to fix a model.

**Comment by askhade** [comment]
What do you mean by 0 dimensional model? Can you share your model?

**Comment by paragikjain** [comment]
**https://drive.google.com/open?id=1tm_o1oWFldMkxVEqD5nmqICzeiFGpnsd**

hi this is link of my model which has to be quantize
