### ISSUE TITLE
question: package directory 'onnxruntime\backend' does not exist

### ISSUE THREAD

**Issue by yangze01** [microsoft/onnxruntime#2649]
I encounter some errors when I install onnxruntime-gpu. could you help me take a look?

**system**: windows 10
**cuda** version: 10.1
**python** version: 3.7.5

I build onnxruntime from source code (github repo). I think I success build the source code. When I install onnxruntime from the source code, a directory does not exists. The installation folder is same as the build folder.

![image](https://user-images.githubusercontent.com/11796873/70780050-a86e9580-1dbf-11ea-8204-dd1bdf827661.png)

**Comment by jywu-msft** [comment]
add the --build_wheel option when calling build.bat to build a python wheel.
you can install the resulting python whl that gets built.

alternatively, i think the setup.py is expecting onnxruntime\backend to be in your current working directory.
so you can try cd to the build directory where onnxruntime\backend exists
and call python d:\onnxruntime\setup.py install

**Comment by yangze01** [comment]
> add the --build_wheel option when calling build.bat to build a python wheel.
> you can install the resulting python whl that gets built.
> 
> alternatively, i think the setup.py is expecting onnxruntime\backend to be in your current working directory.
> so you can try cd to the build directory where onnxruntime\backend exists
> and call python d:\onnxruntime\setup.py install

Thanks for your quick reply. I found that the compilation mode in the documentation only supports cpu mode. Acutally, I need a gpu mode (onnxruntime-gpu) to support online inference. I tried a different way to install onnxruntime-gpu. but it still can not work. Is there another way to install onnxruntime-gpu in windows.
![image](https://user-images.githubusercontent.com/11796873/70846100-04551f00-1e91-11ea-9f9e-1f6d4f4ad2ef.png)

**Comment by skottmckay** [comment]
If you specify '--use_cuda' as a build parameter it will build the gpu package. 

You may also need to specify the cuda_home and cudnn_home paths via either the command line or environment variables.

**Comment by yangze01** [comment]
Thanks for all your help! I build the source code using gpu mode. but there are still some errors. onnxruntime-cpu is easy to follow and helpful for me. I think it is too time consuming for me to set up the enviroment of **onnxruntime-gpu**. I decided to give up temporarily. If there is a gpu based docker image, it will be easier for beginners and users.

![image](https://user-images.githubusercontent.com/11796873/70876225-bf95c900-1ff3-11ea-81b1-c80af807206e.png)

**Comment by faxu** [comment]
There are dockerfiles available here to create images for various build flavors - https://github.com/microsoft/onnxruntime/tree/master/dockerfiles

**Comment by yangze01** [comment]
thanks @faxu 's reply. 😊 I will take a try on windows.

**Comment by jywu-msft** [comment]
> thanks @faxu 's reply. 😊 I will take a try on windows.

sorry, those dockerfiles are for Linux.

**Comment by yangze01** [comment]
Thanks George. Is there a statistic between **onnxruntime-GPU** and original version using different models? If the perf improvement is satified, I can take effort to build some dockerfiles for windows, otherwise, I will think of some other ways to improve perf. Almost all of our online services are running on windows. I did some exp on windows, the perf improvement using **onnxruntime-CPU** is about 10% in terms of QPS (query per second) compared to original version.
