### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by MaxNoe** [microsoft/onnxruntime#2664]
Could you also publish wheels for 3.8?

Is there a reason why you don't publish a `sdist` to PyPI? That way, people could rely on that until a 3.8 wheel is avaiable.

**Comment by snnn** [comment]
We need to patch https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/build.py a little bit. Some of the code isn't compatible with python 3.8

**Comment by snnn** [comment]
Will close it when the wheels are published.

**Comment by snnn** [comment]
Just checked in one more change, however, there is an on-going issue in our nightly build pipeline,  the new packages are still not available for downloading.  I'll update this thread when the issue is fixed.

**Comment by 9dogs** [comment]
Any updates?

**Comment by snnn** [comment]
It's in our nightly build in testpypi. 
1. https://test.pypi.org/project/ort-gpu-nightly/
2. https://test.pypi.org/project/ort-nightly/

However, Windows gpu for 3.8 is still missing.

**Comment by stonebig** [comment]
There are wheels for Python-3.8 now. the issue should be closed.
A wheel for Python-3.9beta 5 would be appreciated

**Comment by snnn** [comment]
We should finish the 3.8 support and add 3.9beta there.

**Comment by snnn** [comment]
#5697

**Comment by olokobayusuf** [comment]
Hey @snnn, I wanted to ask about this. I'm on macOS Big Sur with Python 3.8, but I can't install `onnxruntime`:
```sh
$ python3 --version
Python 3.8.5
$ pip3 --version
pip 20.1.1 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
$ pip3 install onnxruntime
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime
```

**Comment by snnn** [comment]
That's strange. 
Please see:
https://pypi.org/project/onnxruntime/#files

There is a file with name of "onnxruntime-1.5.2-cp38-cp38-macosx_10_12_x86_64.whl"

Could you please manually download the file and let me know if it can be installed?


```bash
pip3 install onnxruntime-1.5.2-cp38-cp38-macosx_10_12_x86_64.whl
```

**Comment by olokobayusuf** [comment]
It seems that the wheel has to be build for macOS Big Sur (11.0.1):
```sh
$ pip3 install onnxruntime-1.5.2-cp38-cp38-macosx_10_12_x86_64.whl
ERROR: onnxruntime-1.5.2-cp38-cp38-macosx_10_12_x86_64.whl is not a supported wheel on this platform.
```
Seems that `pip` doesn't think there's backwards compatibility between macOS 10.x and macOS 11.

**Comment by snnn** [comment]
@olokobayusuf Please upgrade your pip to 20.3. 
```
python3 -m pip install --upgrade pip
```

I think it will solve the issue. see: https://github.com/pypa/pip/pull/9170

**Comment by olokobayusuf** [comment]
> @olokobayusuf Please upgrade your pip to 20.3.
> 
> ```
> python3 -m pip install --upgrade pip
> ```
> 
> I think it will solve the issue. see: [pypa/pip#9170](https://github.com/pypa/pip/pull/9170)

Yup, that fixed it. Thank you!

**Comment by leifwalsh** [comment]
It would still be helpful if you could publish a buildable sdist to PyPI.
