### ISSUE TITLE
is there any performance comparison between mlas, dnnl, openvino ?

### ISSUE THREAD

**Issue by zealerww** [microsoft/onnxruntime#2667]
in my own test, the performance of onnxruntime-mlas is better than onnxruntime-dnnl

**Comment by snnn** [comment]
We don't publish such numbers. There are too many factors that can influence the result. Please measure it by yourself and trust your judgment. You may re-use our perf test tool at  : https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/test/perftest
