### ISSUE TITLE
At compile time, the subprocess.run function reports an error.

### ISSUE THREAD

**Issue by huang229** [microsoft/onnxruntime#2668]
vs2017 cuda10.0 python3.6.7 cudnn7.6
Error is as follows：

:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_providers_cuda.vcxproj]
  cuda_pch.cc
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include\cuda_fp16.h : error C2220: The warning is treated as an error - no "object" file was generated. [F
:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_providers_cuda.vcxproj]
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include\cuda_fp16.h : warning C4819: This file contains characters that cannot be represented in the current code page (936).
Save the file as Unicode to prevent data loss.[F:\onnxruntime\build\Windows\RelWithDebInfo\onnxruntime_providers_cuda.vcxproj]
Traceback (most recent call last):
  File "F:\onnxruntime\\tools\ci_build\build.py", line 1043, in <module>
    sys.exit(main())
  File "F:\onnxruntime\\tools\ci_build\build.py", line 980, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "F:\onnxruntime\\tools\ci_build\build.py", line 415, in build_targets
    run_subprocess(cmd_args)
  File "F:\onnxruntime\\tools\ci_build\build.py", line 197, in run_subprocess
    completed_process = subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "D:\python3.6.7\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['D:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', 'F:\\onnxruntime\\\\build\\Windows\\RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '/maxcpucount:12']' returned non-zero exit status 1.

**Comment by snnn** [comment]
That's a common issue. 

There are multiple solutions:
1. Open the 'cuda_fp16.h' and add 'BOM' at the beginning of the file. https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8

2. Change your operating system's locale to English, in Settings>Time & Language>Region & language

3. Cherry-pick this change: https://github.com/microsoft/onnxruntime/commit/42fa73f7a3da4b8a6bdabdad63074f0920462f50

**Comment by huang229** [comment]
@snnn I have compiled successfully according to your method.Thank you very much for your help.
