### ISSUE TITLE
How to build/create Python module from source?

### ISSUE THREAD

**Issue by radusebastianmarinescu** [microsoft/onnxruntime#2669]
Hi there.
Is it possible to build/generate from source the onnxruntime Python module, similar to the one installed by the following pip command:
`pip install onnxruntime` ?

I tried using build.sh with --build-wheel option, but I did not find the onnxruntime.py module.

Please let me know how can I generate/build the onnxruntime Python module from source.

**Comment by snnn** [comment]
```bash
find . -name \*.whl
```

**Comment by radusebastianmarinescu** [comment]
Thank you @snnn
