### ISSUE TITLE
Memory initialization of CreateTensorAsOrtValue

### ISSUE THREAD

**Issue by elslooo** [microsoft/onnxruntime#2683]
I'm writing a Rust wrapper around the onnxruntime [C API](https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h) and I have a question regarding the initial values of newly created tensor values. If I'm not mistaken, ```CreateTensorAsOrtValue``` does not zero the memory of the newly created tensor. Specifically, assume that we write something like this (pseudocode):

```rust
let value = api.CreateTensorAsOrtValue(GetAllocatorWithDefaultOptions(), ...);
let mut data = api.GetTensorMutableData(value);
// Can we make any assumptions as to what data[0..] is?
```

I've briefly tested this and it seems that occasionally the data is not zeroed, so I assume it's actually never zeroed and just occasionally zero.

It probably also depends on the chosen memory allocator, so let me narrow down this question to include only the default allocator (```GetAllocatorWithDefaultOptions()```).

**Q:** Are there any guarantees w.r.t. the initial values of the data array? Would it be worth to specifically mention those guarantees in the docs (even / especially if there aren't any)?

PS. I'm aware of ```CreateTensorWithDataAsOrtValue```, but I'm interested specifically in the guarantees of ```CreateTensorWithData```.

**Comment by snnn** [comment]
It won't touch the memory. The function is designed as multiple tensors can share the same underlying buffer.

**Comment by elslooo** [comment]
Just to clarify, I'm specifically interested in what happens when I _don't_ pass an existing buffer (i.e. no sharing).

```c
OrtStatus*(ORT_API_CALL* CreateTensorAsOrtValue)(_Inout_ OrtAllocator* allocator,
                                                 _In_ const int64_t* shape, size_t shape_len, ONNXTensorElementDataType type,
                                                 _Outptr_ OrtValue** out)NO_EXCEPTION;
```

I assume this will call:

```c
OrtStatus*(ORT_API_CALL* AllocatorAlloc)(_Inout_ OrtAllocator* ptr, size_t size, _Outptr_ void** out)NO_EXCEPTION;
```

And if I understand correctly, ```CreateTensorAsOrtValue``` won't touch the newly allocated memory of ```void **out```? So summing up: the initial value of a newly created tensor depends on the chosen allocator? Can we conclude that the default allocator does not zero memory before it returns (i.e. ```malloc``` instead of ```calloc```)?

**Comment by snnn** [comment]
Sorry I gave you wrong answer.
CreateTensorWithDataAsOrtValue need an existing buffer.
CreateTensorAsOrtValue doesn't, and it will allocate the buffer on behalf of you.
CreateTensorAsOrtValue won't touch the newly allocated memory if the elements in it are primitive types like int/float/double. However, if it contains std::string, onnxruntime must initialize the buffer for you, because the caller has no way to do it.

**Comment by elslooo** [comment]
Thanks! That makes sense!
