### ISSUE TITLE
deploy on ARM device(Android) 

### ISSUE THREAD

**Issue by carl1314** [microsoft/onnxruntime#271]
**Is your feature request related to a problem? Please describe.**
         I want to deploy onnxruntime on android device, but I can't make progress because of the lack of 
   related guide from github, only find "Cross compiling on Linux" ,but this is not enough for me, would 
   you please update the ARM build guide in more detail?
**System information**
- ONNX Runtime version (you are using):
   0.1.5
**Describe the solution you'd like**
   an ARM build guide(Linux) in detail 

**Describe alternatives you've considered**
   N/A

**Additional context**
   NA

**Comment by carl1314** [comment]
This is  in hurry, It would be better if I get the reply in a few days.

**Comment by snnn** [comment]
Android is not supported yet. Contributions are welcome.

**Comment by pranavsharma** [comment]
@carl1314 what problems are you facing while following the ARM build instructions? may be we can start from there.

**Comment by snnn** [comment]
Hi @carl1314 , could you help us verify this PR: #715 ?

**Comment by linkerzhang** [comment]
@daquexian

**Comment by daquexian** [comment]
I'll make a PR to update the documentation for the compilation for android soon.

**Comment by faxu** [comment]
https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#android-builds
