### ISSUE TITLE
Dead link in ONNX Runtime Samples and Tutorials

### ISSUE THREAD

**Issue by ftrojan** [microsoft/onnxruntime#2724]
**Describe the bug**
Links "SKL Pipeline: Train, Convert, and Inference" and "Keras: Convert and Inference" in [ONNX Runtime Samples and Tutorials](https://github.com/microsoft/onnxruntime/tree/master/samples)

**Urgency**
Low

**To Reproduce**
Open https://github.com/microsoft/onnxruntime/tree/master/samples in your browser and follow the links labeled "SKL Pipeline: Train, Convert, and Inference" and "Keras: Convert and Inference"

**Expected behavior**
The links will lead to an existing sample.

**Comment by snnn** [comment]
@xadupre  could you please help take a look?
