### ISSUE TITLE
Batch processing support for Inference

### ISSUE THREAD

**Issue by zeryx** [microsoft/onnxruntime#2725]
Hey Folks; I've been using onnxruntime (python API) for a little while and I'm planning to make a comparison in runtime performance with a few benchmarking frameworks such as pytorch, and tensorRT. And so far I've been successful in making 1 - off inference programs for all, including onnxruntime (which has been one of the easiest!)

I'm struggling now however, to figure out how to get onnx to process a stream of inputs (for simplicity, a fixed batch) in a performant way. Right now it seems like I need to load the onnx context for each input, which has some significant performance issues when the batch size >> 1. 
Do you happen to have any suggestions or potential code examples ( python/C# APIs would be ideal) that could help me give onnxruntime a more fair chance against some of the competing frameworks?

**Comment by snnn** [comment]
Please let me know if this example helps:
https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx/imagenet

**Comment by hariharans29** [comment]
Linking to some other similar issues for some context. Please see the replies on how to use ORT for batch inferencing **if** the model supports batching inherently.

https://github.com/microsoft/onnxruntime/issues/2118
https://github.com/microsoft/onnxruntime/issues/1944

**Comment by hariharans29** [comment]
Closing this out as this is not an ORT issue per-se. Please re-open if you have further questions. Thanks.
