### ISSUE TITLE
Passing a python scalar list throws off `input_def_list`

### ISSUE THREAD

**Issue by nfishe** [microsoft/onnxruntime#2733]
**Describe the bug**
Passing a python scalar list as a value in the input feed throws:

```
RuntimeError                              Traceback (most recent call last)
 in 
----> 1 sess.run([output.name for output in sess.get_outputs()], {"float_input": [[0.0, 1.5], [3.0, 4.5], [6.0, 7.5]]})

/usr/local/lib/python3.7/site-packages/onnxruntime/capi/session.py in run(self, output_names, input_feed, run_options)
    140             output_names = [output.name for output in self._outputs_meta]
    141         try:
--> 142             return self._sess.run(output_names, input_feed, run_options)
    143         except C.EPFail as err:
    144             if self._enable_fallback:

RuntimeError: Either type_proto was null or it was not of sequence type
```

**Urgency**
None.  Attemping to remove NumPy from base for experimental reasons

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  `Linux 89b988bab19b 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 GNU/Linux` (running in a container)
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.1.0
- Python version:  Python 3.7.5
- Visual Studio version (if applicable): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Describe steps/code to reproduce the behavior:
Was attempting to experiment with memoryviews using logreg_iris:

```python
...

buf = struct.pack("f"*6, *[1.5*x for x in range(6)])
x = memoryview(buf)
y = x.cast("f", shape=[3,2])

sess.run([output.name for output in sess.get_outputs()], {"float_input": y.tolist()})
```

This will occur for `ndarray.tolist()` and passing plain jane python list

**Expected behavior**
Taken from [onnxruntime/test/providers/cpu/ml/linearregressor_test.cc](https://github.com/microsoft/onnxruntime/blob/71ce0b8e0a35a2f762a397fbb4d54f02dc8d64de/onnxruntime/test/providers/cpu/ml/linearregressor_test.cc#L20)

```python
 from sklearn import linear_model
X = [[0., 0.5], [1., 1.5], [2., 2.9], [3., 13.3]]
Z = [[41.], [32.], [23.], [14.]]
model = linear_model.LinearRegression()
r3 =model.fit(X, Z)
r4 =model.predict (y.tolist())
```

Passing `y.tolist()` to predict yields 
```
array([[ 41.],
       [ 14.],
       [-13.]])
```

**Comment by hariharans29** [comment]
It seems like the input feed as a list misguides some existing logic into thinking that we are trying to create a sequence tensor and finally runs into this error message : "Either type_proto was null or it was not of sequence type" while performing some sanity check. 

@jywu-msft - Do we plan to support lists (and nested lists for multi-dimensional inputs) for the feeds in Python ?

**Comment by jywu-msft** [comment]
> It seems like the input feed as a list misguides some existing logic into thinking that we are trying to create a sequence tensor and finally runs into this error message : "Either type_proto was null or it was not of sequence type" while performing some sanity check.
> 
> @jywu-msft - Do we plan to support lists (and nested lists for multi-dimensional inputs) for the feeds in Python ?

no, 
there are no plans to interpret python lists as anything other than onnx sequence.

python lists represent onnx sequences
python dicts to represent onnx maps. 
and onnx tensors are represented as numpy arrays.

**Comment by hariharans29** [comment]
@jywu-msft : Thanks for confirming. I actually already had the change to support the requested scenario. The PR can be disregarded if you feel the support is not required. It may help the OP or someone looking for similar support. Thanks.

**Comment by jywu-msft** [comment]
> @jywu-msft : Thanks for confirming. I actually already had the change to support the requested scenario. The PR can be disregarded if you feel the support is not required. It may help the OP or someone looking for similar support. Thanks.

Thanks for the PR. I wasn't aware of any plans or requirements to support that scenario. We can re-consider it if there is a strong use-case.
My hesitation is mapping python list to multiple data types doesn't feel clean.

**Comment by hariharans29** [comment]
@jywu-msft: Thanks. There wasn't any plan or requirement. I just thought I would try and address this open issue which basically asks for this feature. I had the same apprehension because numpy array comes bound to a specific type whereas python list objects may basically contain anything and need to be handled with care. The logic in the PR basically tries to parse the provided list based on the type specified by the TypeProto for the specific input failing which, it throws. I see both sides to this - it does seem reasonable o support it especially if other popular frameworks like scikit support it, whereas numpy arrays do seem safer to handle for regular tensors (especially when ONNX supports an inherent sequence tensor type). Anyway, I ll keep the PR open in case, someone wants to use the logic. Thanks!
