### ISSUE TITLE
Build error in CentOS

### ISSUE THREAD

**Issue by yueyihua** [microsoft/onnxruntime#2735]
Build Error in CentOS：
['/usr/bin/cmake3', '--build', '/home/yyh/3rdparty/onnxruntime/build/Linux/Debug', '--config', 'Debug']
[  8%] Built target libprotobuf
[ 18%] Built target libprotoc
[ 18%] Built target protoc
[ 18%] Built target onnx_proto
[ 20%] Built target re2
[ 21%] Built target onnxruntime_session
[ 25%] Built target onnxruntime_optimizer
[ 26%] Building CUDA object CMakeFiles/onnxruntime_providers_cuda.dir/home/yyh/3rdparty/onnxruntime/onnxruntime/core/providers/cuda/activation/activations_impl.cu.o
/home/yyh/3rdparty/onnxruntime/onnxruntime/core/framework/data_transfer.h(22): warning: overloaded virtual function "onnxruntime::IDataTransfer::CopyTensor" is only partially overridden in class "onnxruntime::CPUDataTransfer"

/home/yyh/3rdparty/onnxruntime/include/onnxruntime/core/graph/graph.h(827): error: no default constructor exists for class "std::unordered_map<std::string, const onnx::FunctionProto *, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<const std::string, const onnx::FunctionProto *>>>"

/home/yyh/3rdparty/onnxruntime/include/onnxruntime/core/graph/graph.h(837): error: no default constructor exists for class "std::unordered_map<std::string, const onnx::FunctionProto *, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<const std::string, const onnx::FunctionProto *>>>"

/home/yyh/3rdparty/onnxruntime/onnxruntime/core/providers/cuda/gpu_data_transfer.h(18): warning: overloaded virtual function "onnxruntime::IDataTransfer::CopyTensor" is only partially overridden in class "onnxruntime::GPUDataTransfer"

2 errors detected in the compilation of "/tmp/tmpxft_000070e7_00000000-9_activations_impl.compute_70.cpp1.ii".
gmake[2]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/home/yyh/3rdparty/onnxruntime/onnxruntime/core/providers/cuda/activation/activations_impl.cu.o] Error 1

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
CentOS Linux release 7.1.1503 (Core) 
- ONNX Runtime installed from (source or binary):
source
- ONNX Runtime version:
1.1.0
- Python version:
python-3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
- CUDA/cuDNN version:
CUDA-10.1
- GPU model and memory:

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by zemofreedom** [comment]
I have the same Error in CentOS too

**Comment by KnightYao** [comment]
> Build Error in CentOS：
> ['/usr/bin/cmake3', '--build', '/home/yyh/3rdparty/onnxruntime/build/Linux/Debug', '--config', 'Debug']
> [ 8%] Built target libprotobuf
> [ 18%] Built target libprotoc
> [ 18%] Built target protoc
> [ 18%] Built target onnx_proto
> [ 20%] Built target re2
> [ 21%] Built target onnxruntime_session
> [ 25%] Built target onnxruntime_optimizer
> [ 26%] Building CUDA object CMakeFiles/onnxruntime_providers_cuda.dir/home/yyh/3rdparty/onnxruntime/onnxruntime/core/providers/cuda/activation/activations_impl.cu.o
> /home/yyh/3rdparty/onnxruntime/onnxruntime/core/framework/data_transfer.h(22): warning: overloaded virtual function "onnxruntime::IDataTransfer::CopyTensor" is only partially overridden in class "onnxruntime::CPUDataTransfer"
> 
> /home/yyh/3rdparty/onnxruntime/include/onnxruntime/core/graph/graph.h(827): error: no default constructor exists for class "std::unordered_map<std::string, const onnx::FunctionProto *, std::hashstd::string, std::equal_tostd::string, std::allocator<std::pair<const std::string, const onnx::FunctionProto *>>>"
> 
> /home/yyh/3rdparty/onnxruntime/include/onnxruntime/core/graph/graph.h(837): error: no default constructor exists for class "std::unordered_map<std::string, const onnx::FunctionProto *, std::hashstd::string, std::equal_tostd::string, std::allocator<std::pair<const std::string, const onnx::FunctionProto *>>>"
> 
> /home/yyh/3rdparty/onnxruntime/onnxruntime/core/providers/cuda/gpu_data_transfer.h(18): warning: overloaded virtual function "onnxruntime::IDataTransfer::CopyTensor" is only partially overridden in class "onnxruntime::GPUDataTransfer"
> 
> 2 errors detected in the compilation of "/tmp/tmpxft_000070e7_00000000-9_activations_impl.compute_70.cpp1.ii".
> gmake[2]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/home/yyh/3rdparty/onnxruntime/onnxruntime/core/providers/cuda/activation/activations_impl.cu.o] Error 1
> 
> A clear and concise description of what the bug is.
> 
> **Urgency**
> If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.
> 
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
>   CentOS Linux release 7.1.1503 (Core)
> * ONNX Runtime installed from (source or binary):
>   source
> * ONNX Runtime version:
>   1.1.0
> * Python version:
>   python-3.6
> * Visual Studio version (if applicable):
> * GCC/Compiler version (if compiling from source):
>   gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
> * CUDA/cuDNN version:
>   CUDA-10.1
> * GPU model and memory:
> 
> **To Reproduce**
> Describe steps/code to reproduce the behavior:
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Additional context**
> Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

did you fix that compiler bug, now i have same error

**Comment by sunhmy** [comment]
having the same issue. Any known fix for it?

**Comment by sdnusqy-art** [comment]
I have the same issue, Any known fix for it?

**Comment by sunhmy** [comment]
> I have the same issue, Any known fix for it?

I solved it on my end by upgrading gcc to version 7 or +

**Comment by sdnusqy-art** [comment]
> > I have the same issue, Any known fix for it?
> 
> I solved it on my end by upgrading gcc to version 7 or +

I have tried your suggestion, it's ok. Thanks!
