### ISSUE TITLE
Abnormal performance of SetIntraOpNumThreads(1)

### ISSUE THREAD

**Issue by JustLuoyu** [microsoft/onnxruntime#2741]
**Describe the bug**
After adding "sessionops.SetIntraOpNumThreads(1);" the CPU usage of my onnxruntime application went up to 100%. On the contrary, the default threads number only occupies 15% CPU.
What's going on? BTW 100% usage is slower than 15%. Is onnx wasting my CPU time? 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10 64
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.1.0
- Python version: null
- Visual Studio version (if applicable): VS2019
- GCC/Compiler version (if compiling from source): null
- CUDA/cuDNN version: null
- GPU model and memory: null

**Expected behavior**
Single-thread or Multi-thread? I'm confused.

**Comment by snnn** [comment]
The  default binary on openmp for parallization. For those execution providers, we need to use the openmp enviroment variable to tune the performance.

The most widely used enviroment variables are:

OMP_NUM_THREADS=n 
Controls the thread pool size


OMP_WAIT_POLICY=PASSIVE/ACTIVE
Controls whether thread spinning is enabled
PASSIVE is also called throughput mode and will yield CPU after finishing current task
ACTIVE will not yield CPU, instead it will have a while loop to check whether the next task is ready
Use PASSIVE if your CPU usage already high, and use ACTIVE when you want to trade CPU with latency

You could also build from source and disable openmp.

**Comment by JustLuoyu** [comment]
Ok, I can see why now. But yielding all my cores of CPU, I can't agree with this behavior. 

And the OpenMP environment variables are used in runtime or build from source?

**Comment by snnn** [comment]
By default openmp works in such a way.  You could build onnxruntime from source without the "--use_openmp" flag, the it will be gone.

**Comment by JustLuoyu** [comment]
In fact, I do want to use OpenMP to tune the calculation performance. The problem is that I couldn't see the difference while increasing the threads number. My CPU has 12 cores and 24 threads. Increasing the threads number from 2 to 24, the processing time and CPU usage seem the same to me, nothing changed. Only when the threads number equals to 1, the processing time doubles and CPU usage becomes 100%. I'm also an OpenMP-programmer, these totally confuse me. I really don't know how to improve my application performance on CPU now.

**Comment by snnn** [comment]
See: https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/platform/threadpool.h#L66

When you SetIntraOpNumThreads to 1 , the tp parameter for that function will be always NULL. Then it will go to the lower part and use OpenMP for parallelism.

**Comment by addisonklinke** [comment]
@JustLuoyu I had a similar issue forcing OpenMP to run on a single thread, and resolved it by setting the appropriate environmental variable _before_ importing ONNX Runtime. Perhaps the discussion on https://github.com/microsoft/onnxruntime/issues/3233 is helpful
