### ISSUE TITLE
Unable to perform inference with converted Insightface resnet 100 model. 

### ISSUE THREAD

**Issue by cyrusbehr** [microsoft/onnxruntime#2743]
I am trying to convert the Insightface resnet 100 model (` LResNet100E-IR,ArcFace@ms1m-refine-v2`) which can be found [here](https://github.com/deepinsight/insightface/wiki/Model-Zoo) to work with onnxruntime. 

I use the following conversion python script to convert the model. The model converts successfully.

```
import mxnet as mx
import numpy as np
from mxnet.contrib import onnx as onnx_mxnet
import logging
logging.basicConfig(level=logging.INFO)

sym = 'model-symbol.json'
params = 'model-0000.params'

input_shape = (1,3,112,112)

# Path of the output file
onnx_file = './insightface_resnet100.onnx'
converted_model_path = onnx_mxnet.export_model(sym, params, [input_shape], np.float32, onnx_file)

from onnx import checker
import onnx

model_proto = onnx.load_model(converted_model_path)

# Check if converted ONNX protobuf is valid
checker.check_graph(model_proto.graph)
```

Next, I try to load the model in C++ using the following code. Note, I am following the example found [here](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp) : 
```
int main(int argc, char* argv[]) {
    Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");
    Ort::SessionOptions session_options;
    session_options.SetIntraOpNumThreads(1);

    session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
    const char* model_path = "../models/insightface_resnet100.onnx";

    Ort::Session session(env, model_path, session_options);

    return 0;
}
```

When I run this code, I get the following error:
```
terminate called after throwing an instance of 'Ort::Exception'
  what():  Type Error: Type parameter (T) bound to different types (tensor(float) and tensor(double) in node (_minusscalar0).
Aborted

```

I am using `libonnxruntime.so.1.1.0`

**Comment by hariharans29** [comment]
Hello,

It looks like there has been MxNet to ONNX conversion issues. 

The error message basically means there is an operator in the computation graph that has inputs/attributes bound to different types (float and double in this case), when it is supposed to be the same type. I don't know which specific operator is affected, but as an illustrative example - let's take the And op (https://github.com/onnx/onnx/blob/master/docs/Operators.md#and). And has 2 inputs A and B bound to type T (which means the types of A and B need to be the same and one of the supported types for T). I would recommend opening an issue in the relevant MxNet-ONNX coverter project with the converted ONNX model.

As an aside, do you have the latest ONNX release ? This commit in ONNX - https://github.com/onnx/onnx/commit/ca1d5b7e0a3290a1419cb2020511df07d11287fe, should have checks for exactly this scenario (types not being homogeneous) and should have failed at the onnx model checking stage.

**Comment by cyrusbehr** [comment]
Hi @hariharans29 
Thank you I can open an issue with the MXNET team.

I was using onnx v1.2.1, as specified by this tutorial: https://mxnet.apache.org/api/python/docs/tutorials/deploy/export/onnx.html

**Comment by hariharans29** [comment]
I see. Perhaps onnx v.16 should have caught this invalid model as the commit I mentioned is fairly recent and should have gone out with the latest release.

**Comment by cyrusbehr** [comment]
I was able to solve this issue. Solution can be found [here](https://github.com/apache/incubator-mxnet/issues/17195)
