### ISSUE TITLE
C API Features

### ISSUE THREAD

**Issue by ankane** [microsoft/onnxruntime#2746]
Hi, I'm hoping to bring the [Ruby API](https://github.com/ankane/onnxruntime) to feature parity with the [Python API](https://microsoft.github.io/onnxruntime/python/api_summary.html), but there are a few features that I'm having trouble finding in the C API.

1. Device - `onnxruntime.get_device()`
2. Model metadata - `onnxruntime.ModelMetadata` class
3. File path for profiling - the return value of `model.end_profiling()`

Are these currently possible with the C API, and if not, what are your thoughts on adding them?

**Comment by hariharans29** [comment]
Hi @ankane,

Thanks for the feature request. I think get_device() might be the only thing that needs to be given some thought. As I see it, get_device() in python returns a macro that is formed when the Py package is built (the macro is constructed based on the build options). We could have a similar logic for the C/C++ interface.

I don't see why the other 2 (Model metadata struct and the end_profiling() API) cannot be exposed right now either.

Thoughts @snnn @pranavsharma  ?

**Comment by yuzawa-san** [comment]
What about moving the GetAllProviders and GetAvailableProviders functions https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/onnxruntime_pybind_state.cc#L272
 into the main C API? That way the logic won't be duplicated between the different bindings (Ruby and python). This functionality does not exist in the Java API yet, but I think it would be useful. If this is a separate ticket, I can make one.

**Comment by snnn** [comment]
One idea was: people can add new execution provider without changing onnxruntime's existing code. So we can't provide functions like "GetAvailableProviders()" in our C API.

**Comment by hariharans29** [comment]
Hi @ankane 

Fetching the `ModelMetadata` and `end_profiling()`are supported via #2794 . I spoke to some folks and they say that the global method `get_device()` was apparently added only to support the onnx backend API (https://github.com/onnx/onnx/blob/master/onnx/backend/base.py) and is Python only. I think what you may have bee interested in is something along the lines of the `GetAvailableProviders()` in the C API and as @snnn mentions there are plans to support adding new execution provider with changing onnxruntime's existing code and hence supporting that API may not be the right way forward now. 

Please let me know if I can close this issue after the PR is merged. Thanks!

**Comment by ankane** [comment]
Thanks @hariharans29, #2794 looks great!

Re `get_device()`: thanks for the context. It sounds like `GetAvailableProviders()` will return similar info, and it's also used to determine fallback providers in Python. There's also `GetRegisteredProviderTypes()` which is used to implement the `get_providers()` method on `onnxruntime.InferenceSession`.

Totally understand if there are concerns with exposing provider APIs. Happy that model metadata and the profiling path are available.

**Comment by hariharans29** [comment]
Closed via #2794

**Comment by ankane** [comment]
Thanks @hariharans29! Is there a way to get the keys for `ModelMetadataLookupCustomMetadataMap`?

**Comment by ankane** [comment]
Also, fwiw, the Ruby library has been updated with these changes, as well as the other C API changes

**Comment by hariharans29** [comment]
Thanks @ankane. 

Whoops - maybe the API to get the keys should have been added along with mu change :(. My bad. 

I can add the API in the next version if the API.

**Comment by ankane** [comment]
Sounds good! I should have caught it as well :) Thanks for this last round of C API additions - was super helpful at getting non-Python libraries to feature parity.
