### ISSUE TITLE
Is python onnxruntime-gpu  slower than pytorch cuda ?

### ISSUE THREAD

**Issue by byfate** [microsoft/onnxruntime#2750]
**Describe the bug**
I export pytorch alexnet onnx example ,and run it using onnxruntime,and I found that onnxruntime-gpuis 10x slower than pytorch-gpu

**Urgency**
```python
import torch
import onnx
import time
import numpy as np
import torchvision


if __name__ == '__main__':
    
    # alexNet spend time
    dummy_input = torch.randn(10, 3, 224, 224, device='cuda')
    model = torchvision.models.alexnet(pretrained=True).cuda()
    input_names = ["actual_input_1"] + ["learned_%d" % i for i in range(16)]
    output_names = ["output1"]
    start = time.time()
    out = model(dummy_input)
    print("time", time.time() - start)
    torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True, input_names=input_names,
                      output_names=output_names)

    # Load the ONNX model
    model = onnx.load("alexnet.onnx")
    # Check that the IR is well formed
    onnx.checker.check_model(model)

    # onnx spend time
    print(ort.get_device())
    ort_session = ort.InferenceSession('alexnet.onnx')
    start = time.time()
    outputs = ort_session.run(None, {'actual_input_1': np.random.randn(10, 3, 224, 224).astype(np.float32)})
    print("time", time.time() - start)
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary):onnxruntime-gpu 1.0.0
- ONNX Runtime version:1.5.0
- Python version:3.5
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):5.4.0
- CUDA/cuDNN version:10.0
- GPU model and memory:2080ti,11GB

**To Reproduce**
code above

**Expected behavior**
 I wonder if it is normal for onnxruntime is actually slower than pytorch,or it is slower in python api

**Screenshots**
![微信图片_20191227172354](https://user-images.githubusercontent.com/33271371/71511537-b0edc280-28cd-11ea-96a0-e49832da82d3.png)
I would be apprecaited if you could help,3q you

**Comment by 24hours** [comment]
you have preallocated input into gpu memory 
```dummy_input = torch.randn(10, 3, 224, 224, device='cuda')```

``` ort_session.run``` need to allocate into input gpu before running, resulting in slower performance. 

as a comparison, I got 
I have same speed ( 1ms )  for onnxruntime and torch for Alexnet on Quadro RTX 6000.
However, 
Resnet50 torch ( 6 ms ) , onnxruntime ( 3 ms )

batch size = 1, image = 224x224.

**Comment by pranavsharma** [comment]
@24hours has already addressed the issue. The input was preallocated on the GPU in the case of torch. Closing this.

**Comment by smartcat2010** [comment]
> you have preallocated input into gpu memory
> `dummy_input = torch.randn(10, 3, 224, 224, device='cuda')`
> 
> ` ort_session.run` need to allocate into input gpu before running, resulting in slower performance.
> 
> as a comparison, I got
> I have same speed ( 1ms ) for onnxruntime and torch for Alexnet on Quadro RTX 6000.
> However,
> Resnet50 torch ( 6 ms ) , onnxruntime ( 3 ms )
> 
> batch size = 1, image = 224x224.

How could I allocate input to GPU? (which GPU data type do "ort_session.run" "inputs" argument accept?) I also need to compare the inference performance of onnx runtime with other frameworks, but didn't find any code example or API doc to show this.

**Comment by pranavsharma** [comment]
Follow the example here https://github.com/microsoft/onnxruntime/blob/master/orttraining/orttraining/python/ort_trainer.py#L92. The key idea is to use iobinding.

**Comment by fengyuentau** [comment]
Example for iobinding: https://www.onnxruntime.ai/python/api_summary.html#id2. This one is more informative and easier than @pranavsharma 's.

**Comment by FrancescoSaverioZuppichini** [comment]
Same here, even if I time the execution of both runtime to include the tensor creation on GPU, vanilla pytorch is 3x faster than onnx
