### ISSUE TITLE
C# API Direct GPU transfer

### ISSUE THREAD

**Issue by solarflarefx** [microsoft/onnxruntime#2754]
**Is your feature request related to a problem? Please describe.**
It would be very beneficial if there were a way to feed in data to a deep learning model directly from the GPU.  I work within a pipeline where large data is already on the GPU and I want to avoid host copies.

I am working within MS Visual Studio and .NET (in particular C#).

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-bit
- ONNX Runtime version: 1.1.0, C# API
- Visual Studio version (if applicable): 2019
- CUDA/cuDNN version: 10.1, 7

**Describe the solution you'd like**
I am interested in passing data already in the GPU into a DL network with the output still residing in the GPU to be passed to the next element in a pipeline. If possible I’d like to do this without having to perform CPU/GPU copies.  Essentially this would involve passing a cuda array to a model.  Is this possible at the moment?

**Describe alternatives you've considered**

**Additional context**

**Comment by pranavsharma** [comment]
We don't support this currently. See https://github.com/microsoft/onnxruntime/issues/1621.

**Comment by solarflarefx** [comment]
@pranav-prakash Is this functionality included in the [latest release](https://github.com/microsoft/onnxruntime/releases/tag/v1.3.0)? 

It looks like the Python API is explicitly mentioned but that's all.  What about the C# API or the C++ API?

**Comment by pranav-prakash** [comment]
@solarflarefx I think you meant to ping pranavsharma instead?

**Comment by solarflarefx** [comment]
Sorry, please forgive me for the mistake.

@pranavsharma In the latest release can one specify GPU memory locations for the input and output tensors?  As I said, looking at the release notes it appears as though this can be done in Python but what about C# and C++?
