### ISSUE TITLE
Using onnxruntime perf test

### ISSUE THREAD

**Issue by tmannen** [microsoft/onnxruntime#2762]
I'm trying to use a custom model and test it with perftest. I used PyTorch to create the model (it's a pretrained ResNet50) and import it to onnx. I tested the model with onnxruntime in python and it works. I created random data by using onnx.numpy_helper and numpy like this:

```
from onnx import numpy_helper
import numpy as np
import onnx

numpy_array = np.random.randn(1, 3, 224, 224)
tensor = numpy_helper.from_array(numpy_array)
with open('/home/models/resnet50/test_data_set_0/input0.pb', 'wb') as f:
    f.write(tensor.SerializeToString())
```

The folder structure is like this:

```
--/home/models/resnet50/
  --model.onnx
  --test_data_set_0
     --input0.pb
```

and then I ran the command (I'm using tensorrt and it works normally):

```
./onnxruntime_perf_test -e tensorrt /home/models/resnet50/model.onnx result
```

But I get an error:

```
there is no test input data for input input.1 and model resnet50
Run failed:failed to initialize.
```

Is there some kind of demo on how to use perftest for your own models? I'm planning to use the perftest somewhat extensively in my studies and it would be very helpful.

I'm on linux, ubuntu 18.04 with an NVIDIA Quadro GPU.

**Comment by snnn** [comment]
Please rename "input0.pb" to "input_0.pb"

**Comment by tmannen** [comment]
Ahh, I'm an idiot. I'll try it out next time I'm at my work computer.

**Comment by snnn** [comment]
It's our fault. We should document it better.
