### ISSUE TITLE
Huge amount of managed allocations in C# API

### ISSUE THREAD

**Issue by nietras** [microsoft/onnxruntime#2763]
**Describe the bug**
This is a performance issue. The C# API is unfortunately poorly designed and implemented when it comes to managed allocations for each `InferenceSession.Run`. There is no zero managed allocations path, this is sorely needed for high performance/latency sensitive scenarios.

**Urgency**
We need this within a month. It is likely we will have to do our own C# P/Invoke around the C API to achieve our goals. Long term we would very much like this in here of course :).

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-bit
- ONNX Runtime installed from (source or binary): Source since we needed TensorRT support
- ONNX Runtime version: 1.1.0
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source): MSVC 2019
- CUDA/cuDNN version: 10.1, 7
- GPU model and memory: 2060 Super

**To Reproduce**
Simply run a an inference loop in say BDN and measure number of managed allocations.

**Expected behavior**
A zero allocation path for `Run` e.g. by reusing instances and outputting into existing instances.

**Screenshots**
Profiling in VS2019 clearly shows the problem. Of about 1.3M allocations 1.1M are from OnnxRuntime, hence we have about 6-7x more allocations due to OnnxRuntime. This causes GC pauses above our budget. All the below allocations are from calling `Run` which is not great.

![image](https://user-images.githubusercontent.com/10798831/71622894-26f96e80-2bd9-11ea-88cf-e92ccd36936e.png)

**Additional context**
Looking at the source for the C# API there seems to be a lot of opportunity to improve this, but the ideal here is to have an API design that allows a zero managed allocation path. Additionally, it would be and is generally advisable that for these kinds of "wrappers" that the underlying C API is exposed in it's raw form, not hidden from advanced users. C API is stable, there is no reason to hide it as such, other than a hand-holding philosophy. :)

Anyone using OnnxRuntime from C# will benefit from this. In a broader context this would relate to how an API can be designed and implemented for high performance scenarios incl. #2754 

Additionally, a proper release for TensorRT is needed too. In many ways a more modular plug-in based model for distribution and packaging seems relevant. 

cc: @tannergooding

**Comment by nietras** [comment]
A `BenchmarkDotNet` example running a simple MNIST is shown below. Note we try to "cache" as much as possible.

```csharp
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Diagnostics.Windows.Configs;
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;

namespace OnnxRuntimeBenchmark
{
    [NativeMemoryProfiler]
    [MemoryDiagnoser]
    public class Bench
    {
        readonly InferenceSession _session;
        readonly Dictionary<string, NamedOnnxValue> _inputNameToNamedOnnxValue;

        public Bench()
        {
            var modelData = Helper.GetBytes(() => new FileStream("model.onnx",
                FileMode.Open, FileAccess.Read));
            var options = new SessionOptions();
            _session = new InferenceSession(modelData, options);

            var inputMetadata = _session.InputMetadata;
            var outputMetadata = _session.OutputMetadata;

            var inputNameToTensor = inputMetadata.ToDictionary(p => p.Key, p =>
            {
                // There are 3 leading dims, [-1,1,1]
                var dimensions = p.Value.Dimensions;
                dimensions[0] = 1; // Batch-size 1
                var tensor = new DenseTensor<float>(dimensions);
                var buffer = tensor.Buffer;
                return tensor;
            });

            _inputNameToNamedOnnxValue = inputNameToTensor.ToDictionary(p => p.Key,
                p => NamedOnnxValue.CreateFromTensor(p.Key, p.Value));
        }

        [Benchmark]
        public float Run()
        {
            using (var outputs = _session.Run(_inputNameToNamedOnnxValue.Values))
            {
                // Should be IReadOnlyList to allow indexing
                var output = outputs.Single();
                var outputTensor = output.AsTensor<float>();
                Span<int> index = stackalloc int[outputTensor.Rank];
                return outputTensor[index];
            }
        }
    }
}
```
Note you should be able to run this with any `onnx` model, as an example and since main issue here is allocs per `Run` one can use the simple MNIST model as in https://github.com/onnx/models/tree/master/vision/classification/mnist

A quick run of this gives using Microsoft.ML.OnnxRuntime.MKLML 1.1.0.

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.17763.864 (1809/October2018Update/Redstone5)
Intel Core i7-8700 CPU 3.20GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4042.0), X64 RyuJIT
  DefaultJob : .NET Framework 4.8 (4.8.4042.0), X64 RyuJIT
```
| Method |     Mean |    Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated | Allocated native memory | Native memory leak |
|------- |---------:|---------:|---------:|------:|------:|------:|----------:|------------------------:|-------------------:|
|    Run | 63.68 us | 0.146 us | 0.137 us |     - |     - |     - |     723 B |                  4820 B |                  - |

We don't care about the native memory allocs, these are just included for completeness. The main point here is not so much the `723` bytes per call but the huge amount of instances per call, and also when running models with more than one input this gets worse e.g. multiply by number of inputs.

And yes this is on .NET Framework which we have to run on. Using the OnnxRuntime package with that has some issues, excessive package references being one.

**Comment by jignparm** [comment]
>This causes GC pauses above our budget.

The C# API running time performance should be quite close to native C /C++ API.  Since there's no native memory leak in the table above (running on CPU, and excluding TensorRT), how do the GC pauses manifest? Are they causing slowdown, compared to native C++/C? 

The number of allocations may seem high, but it's not clear if they are higher than necessary (i.e. what are they being compared to?) -- but if they are impacting running time and causing C# to be substantially slower than native C/C++, it requires investigation.

**Comment by nietras** [comment]
> The C# API running time performance should be quite close to native C /C++ API. Since there's no native memory leak in the table above (running on CPU, and excluding TensorRT), how do the GC pauses manifest? Are they causing slowdown, compared to native C++/C?

@jignparm running time and native memory leak are of no concern with regards to managed allocations. Managed allocations cause a build up of garbage that the GC has to collect. This causes GC pauses. Of the entire application. Way above our budget. There is no need for all these allocations in the C# code for the OnnxRuntime. 

> if they are impacting running time and causing C# to be substantially slower than native C/C++, it requires investigation.

@jignparm in my view this is wrong, the problem here is not whether C# is "substantially slower" than native C/C++, that is comparing apples with oranges. .NET has a garbage collector, this is fundamentally different from C++ and cannot be compared. GC pauses are a real concern for latency sensitive applications. You will not see them in micro-benchmarks with regards to running time. ASP.NET Core is the poster example for how reducing allocations improved overall performance of it and worst case latency.

**Comment by jignparm** [comment]
Another question --  is the concern mostly about overall app health (i.e. other portions of the application are being negatively impacted due to allocations), or is the primary concern that GC kicks in during inference runs? 

Regarding reducing managed allocations -- blittable types are already pinned in memory to avoid data copies. In some cases, like string tensor types, the additional allocations are unavoidable (each string has to be converted to UTF-8).  It may be possible to slightly reduce the number of overall allocations (besides the ones due to tensor operations), but some concrete data points regarding impact would help quantify the negative effects of the allocations.

**Comment by nietras** [comment]
> the standard deviation of 0.137us coupled with a mean of 63.68us in the table above is implying that the vast majority of inference runs are completed in expected time, with very little variance.

@jignparm as I mentioned, :), you cannot use BDN results as a measurement for GC pauses, especially since no GC occurred during the run.

> What's the budget

The budget I am talking about are the GC pauses, not inference times. Inference times have nothing to do with this issue. It is the after effects of running `Run` and the many allocations this does and the many built up allocations over time that causes too long GC pauses for us.

> the primary concern that GC kicks in during inference runs?

No, it doesn't matter if it kicks in during inference runs, but it matters for other parts of our application that control real world hardware in soft real time.

> blittable types are already pinned in memory to avoid data copies

Yes, this is great! And why ONNX Runtime has much less overhead that other libs.

> may be possible to slightly reduce the number of overall allocations

I forked ONNX Runtime and have reduced it to **zero** for our case, this involved making a new overload to `Run` and some admittedly ugly hacks. In my view the API should allow advanced users to pick a zero allocation path, this is why the native C API should not be internal/private, it should be public, the C API is public for C/C++ users, but for some reason it is hidden for C# users, this implies C# do not know how to handle the C API, we do. :)

Having a easy to use API is of course great, I am not saying remove that, but great APIs are built in levels. Low level for advanced users, high level for ease of use. Both should be available.

> concrete data points regarding impact would help quantify the negative effects of the allocations.

We run long running tests +24 hours to evaluate performance of our industrial application, within that we measure GC pauses using `perfview`. Our maximum budget could be say 10ms, with the code in ONNX Runtime for C#, this rises to 30ms for example. I do understand that GC pauses have variance here, and our average GC pause is ~2ms, it is the worst case that matters to us though.

**Comment by jignparm** [comment]
>...but it matters for other parts of our application that control real world hardware in soft real time.

>...Low level for advanced users, high level for ease of use. Both should be available.

Using C#  a real time environment is a bit of an odd choice because you cannot control GC to any reasonable degree. 

As you mentioned above, having a lower-level C# API  to mitigate the number of manage allocations  and avoid GC entirely would be one way to enable real-time scenarios in C#. The current C# API was designed primarily for ease-of-use and for quick adoption, while keeping the average latency/throughput as close to native API speed as possible.

>I forked ONNX Runtime and have reduced it to zero for our case,

Glad to hear that you have a solution that works for you in the interim. I'll keep this issue open for tracking purposes as a "good-to-have" feature.
