### ISSUE TITLE
Raspberry Pi Zero W

### ISSUE THREAD

**Issue by luto65** [microsoft/onnxruntime#2764]
**Is your feature request related to a problem? Please describe.**
I need to build the ONNX runtime for a Raspberry Pi Zero W.
cpuinfo:
```
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 997.08
Features	: half thumb fastmult vfp edsp java tls
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7
Hardware	: BCM2835
Revision	: 9000c1
```
512 MB memory

**System information**
- ONNX Runtime version (you are using): none working yet

**Describe the solution you'd like**
I would like to be able to run the inference with an onnx model on the raspberry pi zero w

**Describe alternatives you've considered**
I've tried to build tvm but it crashed in built several times.
I've succeeded now in building tensorflow-lite.

**Comment by luto65** [comment]
Following the BUILD.md I have installed cmake 3.12.3 however I get the error 
CMake 3.13 or higher is required.  You are running version 3.12.3

Could you please specify how to build using version 3.12.3 ?

**Comment by luto65** [comment]
The change happened between April 3 and April 21: 
In rel-0.3.1 (April 3)  the Cmake specified was version 3.11, 
in the following release rel-0.4.0 of April 21 was already specified version 3.13
Can you please update the BUILD.md accordingly ?
Thanks

**Comment by hariharans29** [comment]
Hello - Thanks for the suggestion. 

But isn't Build.md already stating that CMake 3.13 or higher is required here - https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#getting-started-build-the-baseline-cpu-version-of-onnx-runtime-from-source ?

**Comment by hariharans29** [comment]
You are right.

**Comment by snnn** [comment]
> Could you please specify how to build using version 3.12.3 ?

Sorry, it's not supported. Please try to get a newer version of cmake.  If your Linux distro didn't provide it, you may need to download cmake source from [https://cmake.org/download/](https://cmake.org/download/) then build it by yourself.

**Comment by freder** [comment]
@luto65 did you manage to successfully build it in the end and would like to share your `Dockerfile`? I'm also trying to get it to work on the pi zero, but I'm not quite there yet (getting "Illegal instruction" error on the device).

**Comment by tabisio** [comment]
Did you managed to build it? Could you share the wheel?
