### ISSUE TITLE
Packaging with 1.1.0 Releases

### ISSUE THREAD

**Issue by ankane** [microsoft/onnxruntime#2767]
Hi, it looks there were some changes with packaging for the 1.1.0 [release](https://github.com/microsoft/onnxruntime/releases).

1. Linux - was packaged as `zip` wrapping a `tgz`, but has since been changed to `tgz`
2. Mac - packaged as `zip` wrapping a `tgz`
3. Windows - packaged as `zip` wrapping a `zip`

Previous releases didn't have the extra `zip` wrapper, which seems redundant.

It looks like the Linux release was updated, but this broke downloads. I'm not sure the best approach to solve this, but updating the existing assets will likely break more downloads, so it may make sense to put out a new release with updated packaging.

**Comment by hariharans29** [comment]
FYI @RyanUnderhill

**Comment by snnn** [comment]
I updated the Linux release.

**Comment by snnn** [comment]
We're sorry. Due to limited resource available, we'll fix it in the next release.  FYI @faxu

**Comment by ankane** [comment]
fwiw, 1.1.1 packaging is back to normal. Thanks!

**Comment by snnn** [comment]
@RyanUnderhill fixed it.
