### ISSUE TITLE
static library

### ISSUE THREAD

**Issue by Armin234** [microsoft/onnxruntime#2769]
Hi,

what are the parameter for build.bat to build the static library ?

Running build.bat without --build_shared_lib like
build.bat --config RelWithDebInfo --parallel --build_csharp

is generating a DLL.

**Comment by snnn** [comment]
No. Not supported yet.

**Comment by snnn** [comment]
If you need it now, you can checkout our source code and integrate your code into our build system(the CMakeLists.txt and the others).

**Comment by mjwall** [comment]
@snnn is it on the road map?  Any idea what it would take?  Seems to build just fine but there are linking errors.
