### ISSUE TITLE
Native memory leak in `OrtRun` using TensorRT

### ISSUE THREAD

**Issue by nietras** [microsoft/onnxruntime#2773]
**Describe the bug**
It appears there is a bug causing a consistent native memory leak when calling `Run` using the TensorRT execution provider.

**Urgency**
High. This is blocking any production use of OnnxRuntime for us. We need TensorRT to be able to run our models real-time and the memory leak is quickly causing us to run into memory issues.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-bit
- ONNX Runtime installed from (source or binary): Source since we needed TensorRT support
- ONNX Runtime version: 1.1.0
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source): MSVC 2019
- CUDA/cuDNN version: 10.1, 7
- GPU model and memory: 2060 Super, 8GB

**To Reproduce**
 * Run the following `BenchmarkDotNet` code using OnnxRuntime built with TensorRT support:
```csharp
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Diagnostics.Windows.Configs;
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;

namespace OnnxRuntimeBenchmark
{
    [NativeMemoryProfiler]
    [MemoryDiagnoser]
    public class Bench
    {
        readonly InferenceSession _session;
        readonly Dictionary<string, NamedOnnxValue> _inputNameToNamedOnnxValue;

        public Bench()
        {
            var modelData = Helper.GetBytes(() => new FileStream("model.onnx",
                FileMode.Open, FileAccess.Read));
            var options = new SessionOptions();
            options.GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_ALL;
            options.AppendExecutionProvider_Tensorrt(0);
            _session = new InferenceSession(modelData, options);

            var inputMetadata = _session.InputMetadata;
            var outputMetadata = _session.OutputMetadata;

            var inputNameToTensor = inputMetadata.ToDictionary(p => p.Key, p =>
            {
                // There are 3 leading dims, [-1,1,1]
                var dimensions = p.Value.Dimensions;
                dimensions[0] = 1; // Batch-size 1
                var tensor = new DenseTensor<float>(dimensions);
                var buffer = tensor.Buffer;
                return tensor;
            });

            _inputNameToNamedOnnxValue = inputNameToTensor.ToDictionary(p => p.Key,
                p => NamedOnnxValue.CreateFromTensor(p.Key, p.Value));
        }

        [Benchmark]
        public float Run()
        {
            using (var outputs = _session.Run(_inputNameToNamedOnnxValue.Values))
            {
                // Should be IReadOnlyList to allow indexing
                var output = outputs.Single();
                var outputTensor = output.AsTensor<float>();
                Span<int> index = stackalloc int[outputTensor.Rank];
                return outputTensor[index];
            }
        }
    }
}
```
 * I have an `onnx` file that quickly shows this, but cannot share it right now. If interested I have a solution I can share.
 * To run using TensorRT we copy native dlls next to the `exe` i.e.
```
OnnxRuntimeBenchmark\bin\x64\Release\cublas64_10.dll
OnnxRuntimeBenchmark\bin\x64\Release\cublasLt64_10.dll
OnnxRuntimeBenchmark\bin\x64\Release\cudart64_101.dll
OnnxRuntimeBenchmark\bin\x64\Release\cudnn64_7.dll
OnnxRuntimeBenchmark\bin\x64\Release\nvinfer.dll
OnnxRuntimeBenchmark\bin\x64\Release\nvinfer_plugin.dll
OnnxRuntimeBenchmark\bin\x64\Release\onnxruntime.dll
```

**Expected behavior**
No memory leak, instead BDN clearly shows the native memory leak:

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.17763.864 (1809/October2018Update/Redstone5)
Intel Core i7-8700 CPU 3.20GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4042.0), X64 RyuJIT
  DefaultJob : .NET Framework 4.8 (4.8.4042.0), X64 RyuJIT


```
| Method |     Mean |   Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated | Allocated native memory | Native memory leak |
|------- |---------:|--------:|---------:|------:|------:|------:|----------:|------------------------:|-------------------:|
|    Run | 404.5 us | 8.58 us | 12.31 us |     - |     - |     - |     916 B |                  9018 B |              800 B |

**Additional context**
Also see #2763 as these memory issues are stopping us from using OnnxRuntime.

**Comment by nietras** [comment]
Running with:
```csharp
            options.AppendExecutionProvider_CUDA(0);
            //options.AppendExecutionProvider_Tensorrt(0);
```
That is with CUDA instead of TensorRT shows that CUDA version also has a memory leak. While ~2 bytes is small this does accumulate in production too. 

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.17763.864 (1809/October2018Update/Redstone5)
Intel Core i7-8700 CPU 3.20GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4042.0), X64 RyuJIT
  DefaultJob : .NET Framework 4.8 (4.8.4042.0), X64 RyuJIT

```
| Method |     Mean |    Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated | Allocated native memory | Native memory leak |
|------- |---------:|---------:|---------:|------:|------:|------:|----------:|------------------------:|-------------------:|
|    Run | 567.6 us | 11.03 us | 11.32 us |     - |     - |     - |     920 B |                 21730 B |                2 B |

**Comment by nietras** [comment]
Running with none of these providers:
```csharp
            //options.AppendExecutionProvider_CUDA(0);
            //options.AppendExecutionProvider_Tensorrt(0);
```
that is with default execution provider when built with cuda, cudnn, tensorrt support (I do not know which path/execution provider is used then). Then the native memory leak disappears. However, the execution time is way above our limits.

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.17763.864 (1809/October2018Update/Redstone5)
Intel Core i7-8700 CPU 3.20GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4042.0), X64 RyuJIT
  DefaultJob : .NET Framework 4.8 (4.8.4042.0), X64 RyuJIT


```
| Method |     Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated | Allocated native memory | Native memory leak |
|------- |---------:|----------:|----------:|------:|------:|------:|----------:|------------------------:|-------------------:|
|    Run | 2.598 ms | 0.0159 ms | 0.0149 ms |     - |     - |     - |     928 B |                 20638 B |                  - |

**Comment by snnn** [comment]
Do you know which thread the test function "public float Run()" will be in? It's always the same thread or it could be a new thread created by the benchmark framework?

**Comment by nietras** [comment]
@snnn if you run a simple loop around the run this will still leak. And I am pretty sure this occurs on a single thread in BDN. No mattter what calling `OrtRun` repeatedly on a single thread leaks.

**Comment by nietras** [comment]
CUDA isn't a real memory leak, it appears to be a false positive in BDNs NativeMemoryProfiler, probably due to some startup allocations .

**Comment by jywu-msft** [comment]
@stevenlix , can you take a look?

**Comment by nietras** [comment]
@stevenlix it looks to me and I am not 100% sure but that the leak is in the lines:

https://github.com/microsoft/onnxruntime/blob/293b15480be468529cbd05e0c150fad23b08f186/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc#L523

https://github.com/microsoft/onnxruntime/blob/293b15480be468529cbd05e0c150fad23b08f186/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc#L679

which creates an optimization profile as a raw pointer:
```cpp
    virtual nvinfer1::IOptimizationProfile* createOptimizationProfile() noexcept = 0;
```
now the documentation says you must not delete this, since the `IBuilder` retains ownership, but it looks to me it was not intended that one creates one every time no matter if needed or not. 

At least basedon profiling using PerfView and a Debug build of onnxruntime together with the benchmark code detailed earlier one can see that this leaks memory for every time this is called.

![image](https://user-images.githubusercontent.com/10798831/72058662-c18c3880-32d0-11ea-9d4c-7295923fc2a0.png)

To fix this I changed the code to only create the optimization profile if needed in case of shape changes. This is a quick fix though, I think the handling of shape changes needs to be handled differently. We do not have shape changes so we can live with the quick fix. It's better than nothing.

The fix can be seen in #2805

**Comment by nietras** [comment]
After this fix BDN also shows there no longer is a native memory leak:

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.17763.864 (1809/October2018Update/Redstone5)
Intel Core i7-8700 CPU 3.20GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
  [Host]     : .NET Framework 4.8 (4.8.4042.0), X64 RyuJIT
  DefaultJob : .NET Framework 4.8 (4.8.4042.0), X64 RyuJIT


```
| Method |     Mean |   Error |   StdDev |   Median | Gen 0 | Gen 1 | Gen 2 | Allocated | Allocated native memory | Native memory leak |
|------- |---------:|--------:|---------:|---------:|------:|------:|------:|----------:|------------------------:|-------------------:|
|    Run | 417.3 us | 8.26 us | 21.16 us | 406.2 us |     - |     - |     - |     916 B |                  8490 B |                  - |

**Comment by jywu-msft** [comment]
> @stevenlix it looks to me and I am not 100% sure but that the leak is in the lines:
> 
> https://github.com/microsoft/onnxruntime/blob/293b15480be468529cbd05e0c150fad23b08f186/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc#L523
> 
> https://github.com/microsoft/onnxruntime/blob/293b15480be468529cbd05e0c150fad23b08f186/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc#L679
> 
> which creates an optimization profile as a raw pointer:
> 
> ```c++
>     virtual nvinfer1::IOptimizationProfile* createOptimizationProfile() noexcept = 0;
> ```
> 
> now the documentation says you must not delete this, since the `IBuilder` retains ownership, but it looks to me it was not intended that one creates one every time no matter if needed or not.
> 
> At least basedon profiling using PerfView and a Debug build of onnxruntime together with the benchmark code detailed earlier one can see that this leaks memory for every time this is called.
> 
> ![image](https://user-images.githubusercontent.com/10798831/72058662-c18c3880-32d0-11ea-9d4c-7295923fc2a0.png)
> 
> To fix this I changed the code to only create the optimization profile if needed in case of shape changes. This is a quick fix though, I think the handling of shape changes needs to be handled differently. We do not have shape changes so we can live with the quick fix. It's better than nothing.
> 
> The fix can be seen in #2805


Thanks for debugging and root causing it!
I think we'll need to refactor the code to not always create an optimization profile.
probably we can just re-use the one initially created in TensorrtExecutionProvider::Compile()
and update it as needed.
@stevenlix is working on a fix and we'll probably ask you to help us validate it.
Thanks again!

**Comment by stevenlix** [comment]
@jywu-msft, after looking at the code, I think @nietras 's fix is good for now. Usually trt_profile is not needed in the compute unless shape range is changed, and it's better to keep it in local.

**Comment by nietras** [comment]
appears to be fixed

**Comment by solarflarefx** [comment]
@nietras After you built from source, how did you use this build in your C# project?  I built from source and got three DLLs: 
- custom_op_library.dll
- dnnl.dll
- onnxruntime.dll

I tried adding these DLLs by right clicking and adding as a reference, but it seems like these DLLs can't be added as COM components.  Was I supposed to get other files after the build?
