### ISSUE TITLE
The input tensor cannot be reshaped to the requested shape

### ISSUE THREAD

**Issue by 972461099** [microsoft/onnxruntime#2779]
I set 'dynamic_axes': 
```
input = torch.randn(1, 1, 244, 204, requires_grad=True)
torch.onnx.export(torch_model,
                  input,
                  'super_resolution.onnx',
                  export_params=True,
                  opset_version=10,
                  verbose=True, 
                  training=False,
                  do_constant_folding=True,
                  input_names = ['input'],
                  output_names = ['output'],
                  dynamic_axes={'input':{2:'width', 3:'height'},
                                'output':{2:'width', 3:'height'}})
```
If the input data is [1,1,244,204], the result is OK
When I use data of different sizes, 

```
ort_session = onnxruntime.InferenceSession ('super_resolution.onnx')
ort_outs1 = ort_session.run(None, {'input':np.random.randn(1,1,444,204).astype(np.float32)})

```

I get this error:
`RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:38 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,9,444,204}, requested shape:{-1,1,3,3,244,204}
Stacktrace:`

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary):pip
- ONNX Runtime version:1.1.0
- Python version:3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.0/7.6
- GPU model and memory:

**Comment by hariharans29** [comment]
Hi @972461099 ,

This seems like a PyTorch-ONNX exporter issue wherein the 'dynamic_axes' is not being honored by the exporter.

I think, the requested shape is always: {-1,1,3,3,244,204}. This would mean that the shape to be reshaped when the graph input is {1,1,244,204} would probably be (going based on the pattern) {1,9,244,204} and this reshape request can be executed. 

When the graph input shape is {1,1,444,204} and if the reshape request in the exported ONNX graph is still {-1,1,3,3,244,204} (which is what I think is happening), it would fail on the error message shown above.

Could you please open a bug in the PyTorch repo with these findings ? It seems like the 'dynamic_axis' aspect is not being honored, but rather the exporter seems to be working for fixed input shapes.

**Comment by 972461099** [comment]
I set the parameter e in d to 11

> Hi @972461099 ,
> 
> This seems like a PyTorch-ONNX exporter issue wherein the 'dynamic_axes' is not being honored by the exporter.
> 
> I think, the requested shape is always: {-1,1,3,3,244,204}. This would mean that the shape to be reshaped when the graph input is {1,1,244,204} would probably be (going based on the pattern) {1,9,244,204} and this reshape request can be executed.
> 
> When the graph input shape is {1,1,444,204} and if the reshape request in the exported ONNX graph is still {-1,1,3,3,244,204} (which is what I think is happening), it would fail on the error message shown above.
> 
> Could you please open a bug in the PyTorch repo with these findings ? It seems like the 'dynamic_axis' aspect is not being honored, but rather the exporter seems to be working for fixed input shapes.

You are right, thank you very much.
I changed the parameter opset_version=10 to opset_version=11. that can work

**Comment by 972461099** [comment]
> Hi @972461099 ,
> 
> This seems like a PyTorch-ONNX exporter issue wherein the 'dynamic_axes' is not being honored by the exporter.
> 
> I think, the requested shape is always: {-1,1,3,3,244,204}. This would mean that the shape to be reshaped when the graph input is {1,1,244,204} would probably be (going based on the pattern) {1,9,244,204} and this reshape request can be executed.
> 
> When the graph input shape is {1,1,444,204} and if the reshape request in the exported ONNX graph is still {-1,1,3,3,244,204} (which is what I think is happening), it would fail on the error message shown above.
> 
> Could you please open a bug in the PyTorch repo with these findings ? It seems like the 'dynamic_axis' aspect is not being honored, but rather the exporter seems to be working for fixed input shapes.

You are right, thank you very much.
I changed the parameter opset_version=10 to opset_version=11. that can work

**Comment by hariharans29** [comment]
Thanks for confirming. Closing.
