### ISSUE TITLE
build error in MacOS with OpenVINO 2019R3.1

### ISSUE THREAD

**Issue by Hsintao** [microsoft/onnxruntime#2788]
System: MacOS mojave 10.14.6
i run`./build.sh --config RelWithDebInfo --use_openvino CPU_FP32`

and then
`ie_cpu_extension/CMakeFiles/ie_cpu_extension.dir/build.make:773: *** target pattern contains no %.  Stop.`

does building with openvino support macos?  
the doc only have the instruction in Windows and Linux.
[https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#openvino](url)

**Comment by jywu-msft** [comment]
Onnxruntime integration with OpenVINO doesn't support MacOS.
@smkarlap and @suryasidd can comment on whether it will ever be supported.

**Comment by smkarlap** [comment]
Builds for MacOS devices are not currently supported, and won't likely be for at least for the next couple of months. Please check back then. Will update on this issue if anything changes meanwhile.

**Comment by jim-meyer** [comment]
Any update on MacOS support for `onnxruntime-openvino`? After reading https://blog.roboflow.com/accelerate-pytorch-openvino-torch-ort/ I was trying to get my Pytorch models on my Mac to use my Intel Neural Compute Stick ("GPU on a stick") via the simple two line change mentioned in that blog. But without a version of `onnxruntime-openvino` that supports Mac one can't do this.
