### ISSUE TITLE
How to enumerate the tensors and operators in the onnx model from C++?

### ISSUE THREAD

**Issue by tensorbuffer** [microsoft/onnxruntime#2793]
**Is your feature request related to a problem? Please describe.**
Trying to run the onnx model on our customized accelerator chip, so need to enumerate all the tensors and operators (together with its input and output tensors) in the model and then send to our chip for execution.
I checked the onnxruntime_c_api.h and does not see any such APIs for tensors or operators.

**System information**
- ONNX Runtime version (you are using):
mainline

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snnn** [comment]
onnxruntime doesn't expose such feature.  Please use google protobuf instead.

See: 
1. [https://developers.google.com/protocol-buffers/docs/cpptutorial](https://developers.google.com/protocol-buffers/docs/cpptutorial)
2. [https://github.com/onnx/onnx/blob/master/onnx/onnx.proto](https://github.com/onnx/onnx/blob/master/onnx/onnx.proto)

**Comment by tensorbuffer** [comment]
Thanks!
Another approach I am thinking, might be to write our own execution provider. There are two APIs I need to do:
- GetCapability(): for us, we will need to support all operators (e.g. if there's not supported one we will add them into our chip firmware to support them), so our GetCapability() implementation is just to add all nodes to sub_graph.
-  Compile(): this is where I am not clear about. There are 3 functions in compute_info that I need to do.
The most important thing for us is to find out where to pass the nodes and their inputs/outputs to our chip so our firmware can construct the graph there. Should I do it in the GetCapability(), or the compute_info.create_state_func()?
I am not sure which approach is better, using onnx.proto as you suggested, or doing the execution provider.
I think in our case, it's very straightfoward (everything needs to be on our chip), so the multi-platform support and parallel execution in onnxruntime are not applicable. But there might be something like execution provider independent graph optimization is useful to us?
