### ISSUE TITLE
Transpose Utility Layer

### ISSUE THREAD

**Issue by YanYas** [microsoft/onnxruntime#2799]
**Is your feature request related to a problem? Please describe.**
With OnnxRuntime 0.5 c# I had a helper model 
[Transposer10.zip](https://github.com/microsoft/onnxruntime/files/4036730/Transposer10.zip)
 I would run this utility model just to transpose/permute image data so it could be read correctly by a _target_ model. In OnnxRuntime  0.5 The InferenceSession.Run accepted any input so long as the array length matched the products of the dimensions. This is no longer the case so I have to save the model pre-transposed, or create and load a Transpose model on the fly. In the first case, if using models from elsewhere, this isn't an option. The second solution is difficult from c#.

**System information**
- ONNX Runtime version 1.1, 
- Windows 10 64bit, 
- Nvidia 1070Ti

**Describe the solution you'd like**
I would like an function to Transpose the NamedOnnxValue, or a function that adds a transpose layer as the top layer of the model as part of the inference session, allowing you to either put in the Axes to be swapped with an `int[]`. In either case the transposition happens on the device.

**Describe alternatives you've considered**
The other possibility is that the the previous functionality is returned, but I'm under the impression maybe it isn't possible anymore. I suspect that the extra hardware and the interest of performance have come at the cost of this convenience.

**Comment by jignparm** [comment]
>The other possibility is that the the previous functionality is returned, 

The tensor API has not changed. Can you share an API example of  what was possible before, that is different  (not possible) now?

Adding data wrangling operations (e.g. transpose, slice, concat) in the C# API seems like a stretch (!)

**Comment by skottmckay** [comment]
Your transposer model has fixed dimension sizes. Are you getting an error about the input not matching what the model requires?

Possibly the fix would be to use symbolic dimensions (set the dim_param instead of dim_value). 

e.g. instead of Input98 being [1, 10, 10, 3], set dim_param names to something like [ 'batch', 'H', 'W', C']. 

That way the values are flexible and based on the input when the model is run.

**Comment by faxu** [comment]
@YanYas if this is still an issue for you, can you provide more details?

**Comment by YanYas** [comment]
Hi @faxu, I'll need to test this weekend, but I suspect it still will be. 
Thanks

**Comment by snnn** [comment]
I'll close it as it is stale.
