### ISSUE TITLE
Adding execution providers as shared library?

### ISSUE THREAD

**Issue by tensorbuffer** [microsoft/onnxruntime#2818]
**Is your feature request related to a problem? Please describe.**

Hello, from this link it says "Build it as a static lib."
https://github.com/microsoft/onnxruntime/blob/master/docs/AddingExecutionProvider.md

I added my own execution provider ("X"), and I see libonnxruntime_providers_x.a is built.
However I would like it to be a shared .so, just like libonnxruntime.so

For test I compile and link CXXapi_sample.cc with libonnxruntime.so and currently the new provider is not there (e.g. the number of providers is 1).

Would like to know why it needs to be static and if possible to be shared so?

**System information**
- ONNX Runtime version (you are using): Mainline
building on ubuntu for cpu and also my customized execution provider.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pranavsharma** [comment]
As of now execution providers can be linked only statically. We're working on dynamic linking as we speak. fyi @RyanUnderhill

**Comment by tensorbuffer** [comment]
ok thanks. How to use the added provider? Do I need to copy the libonnxruntime_providers.a and libonnxruntime_providers_x.a to the release folder? Do I need to modify the app code (CXXapi_sample.cc)? How to build the app (since there's dynamic link with libonnxruntime.so and static link with providers)?

**Comment by snnn** [comment]
https://github.com/microsoft/onnxruntime/blob/master/docs/AddingExecutionProvider.md

**Comment by tensorbuffer** [comment]
Ok I see, the 'Using the execution provider' section. Looks like I need to modify the CXXapi_sample.cc. This looks weird to me, which execution provider to use should be decided by onnxruntime, not by application.

**Comment by vigsterkr** [comment]
@pranavsharma any roadmap/project or possibly branch publicly available of this... i.e. potentially help out with the effort?

**Comment by pranavsharma** [comment]
This feature is being worked on in a private branch and not at a stage where it can be opened up for community contributions due to multiple conflicting internal pieces. Once we've achieved this for one execution provider, we can open it up to the community. Stay tuned!

**Comment by snnn** [comment]
@RyanUnderhill is working on this. 
Now he has made the DNNL EP as a shared library.
