### ISSUE TITLE
How to properly add execution provider and use it?

### ISSUE THREAD

**Issue by tensorbuffer** [microsoft/onnxruntime#2825]
**Describe the bug**
This is related to https://github.com/microsoft/onnxruntime/issues/2818
I have followed the steps (https://github.com/microsoft/onnxruntime/blob/master/docs/AddingExecutionProvider.md) to add my provider (denoted "X" here). BTW the doc needs update:  OrtCreateCUDAExecutionProviderFactory() should be CreateExecutionProviderFactory_CUDA() I think.

My problem is that I generated the provider static lib, but I can't link it with either C_Api_Sample.cpp or CXX_Api_Sample.cpp. They have the same problem: undefined reference to `OrtSessionOptionsAppendExecutionProvider_X'

I do see this function as a mangled function in the static lib:
$ nm --demangle ~/onnxruntime/rel/lib/libonnxruntime_providers_x.a | grep OrtSessionOptionsAppendExecutionProvider_X
0000000000000000 T OrtSessionOptionsAppendExecutionProvider_X(OrtSessionOptions*)
If I don't use the demangle option:
0000000000000000 T _Z48OrtSessionOptionsAppendExecutionProvider_XP17OrtSessionOptions

For C_Api_Sample.cpp, I added this:
#include <x_provider_factory.h>
...
auto res = (OrtSessionOptionsAppendExecutionProvider_X(session_options));

I compile it with:
g++ -o Capi_sample C_Api_Sample.cpp -I ~/onnxruntime/rel/include -std=c++11 -L ~/onnxruntime/rel/lib -Wl,-Bstatic -lonnxruntime_providers_x -Wl,-Bdynamic -lonnxruntime
got error:
C_Api_Sample.cpp:(.text+0x109): undefined reference to `OrtSessionOptionsAppendExecutionProvider_X'

For CXX_Api_Sample.cpp I added this:
Ort::SessionOptions \*session_options;
Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_X((OrtSessionOptions*)session_options));
And got the same error:
CXX_Api_Sample.cpp:(.text+0x50): undefined reference to `OrtSessionOptionsAppendExecutionProvider_X'

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: mainline
- Python version: 3.5
- Visual Studio version (if applicable): NA
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by snnn** [comment]
run "nm -C -g --defined libonnxruntime_providers_x.so", I guess it doesn't have OrtSessionOptionsAppendExecutionProvider_X

**Comment by jywu-msft** [comment]
> run "nm -C -g --defined libonnxruntime_providers_x.so", I guess it doesn't have OrtSessionOptionsAppendExecutionProvider_X

shouldn't it be libonnxruntime.so ?

**Comment by snnn** [comment]
> > run "nm -C -g --defined libonnxruntime_providers_x.so", I guess it doesn't have OrtSessionOptionsAppendExecutionProvider_X
> 
> shouldn't it be libonnxruntime.so ?

You're right.

**Comment by jywu-msft** [comment]
the key thing here is you should only need to link libonnxruntime.so 
which will contain all the providers you built. 

the last 2 steps of https://github.com/microsoft/onnxruntime/blob/master/docs/AddingExecutionProvider.md
are 

- Add your provider in onnxruntime_providers.cmake. Build it as a static lib.
- Add one line in cmake/onnxruntime.cmake, to the 'target_link_libraries' function call. Put your provider there.

you should add to 
https://github.com/microsoft/onnxruntime/blob/cc75e5a16243f031d6160d576417ae1999a4ab87/cmake/onnxruntime.cmake#L57

confirm the missing symbol is in libonnxruntime.so and then afterwards link to your test application.

**Comment by tensorbuffer** [comment]
Yes I did both steps. The symbol is not in libonnxruntime.so
I think adding to cmake/onnxruntime_providers.cmake might be wrong, I copied the ACL to my 'X':
https://github.com/microsoft/onnxruntime/blob/cc75e5a16243f031d6160d576417ae1999a4ab87/cmake/onnxruntime_providers.cmake#L451
https://github.com/microsoft/onnxruntime/blob/cc75e5a16243f031d6160d576417ae1999a4ab87/cmake/onnxruntime_providers.cmake#L72
Is this a good example to use?

**Comment by snnn** [comment]
Please delete your build folder and rebuild it. Redirect the build log to a file and search something like
```
         Generating symbol file for ['cpu', 'X']
```

**Comment by tensorbuffer** [comment]
Ok it's good now, thanks! I think my .so was not updated (need to copy to release folder), as I was focusing on the provider .a
So the execution providers code are part of libonnxruntime.so, this is different from the answer from https://github.com/microsoft/onnxruntime/issues/2818 ?

**Comment by snnn** [comment]
Now it must be part of libonnxruntime.so.

For #2818,  it's in our plan with high priority. @RyanUnderhill will work on it.
