### ISSUE TITLE
How to properly format OpenCV Mat data (image) to work with onnxruntime inference? 

### ISSUE THREAD

**Issue by cyrusbehr** [microsoft/onnxruntime#2832]
I am trying to use the onnxruntime c++ api to perform inference using the onnx model zoo `arcface LResNet100E-IR` model found [here](https://github.com/onnx/models/tree/master/vision/body_analysis/arcface).

The input specs for the onnx model are as follows:
```
Number of inputs = 1
Input 0 : name=data
Input 0 : type=1
Input 0 : num_dims=4
Input 0 : dim 0=1
Input 0 : dim 1=3
Input 0 : dim 2=112
Input 0 : dim 3=112
```

I am wondering how to properly format `OpenCV Mat` data for the model. Right now, I am doing it as follows in this function:

```
bool OnnxruntimeInferenceEngine::runInference(const cv::Mat& imgRGB) {
    size_t input_tensor_size = 112 * 112 * 3;

    std::vector<const char*> output_node_names = {"fc1"};

    cv::Mat imgRGBFloat;
    imgRGB.convertTo(imgRGBFloat, CV_32F);

    auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
    Ort::Value input_tensor = Ort::Value::CreateTensor<float>(memory_info, reinterpret_cast<float*>(imgRGBFloat.data), input_tensor_size, m_inputNodeDims.data(), 4);
    assert(input_tensor.IsTensor());

    // score model & input tensor, get back output tensor
    auto output_tensors = m_sessionPtr->Run(Ort::RunOptions{nullptr}, m_nodeNames.data(), &input_tensor, 1, output_node_names.data(), 1);

    assert(output_tensors.size() == 1 && output_tensors.front().IsTensor());

    auto* floatarr = output_tensors.front().GetTensorMutableData<float>();
    return true;
}
```

The output (in `floatarr`) is not correct - I have performed inference using the same model with different frameworks such as `mxnet` and `ncnn` and found that they are producing a different output.

When using other frameworks such as `ncnn`, I can keep the input data as `uint8_t`, such as the following:
```
bool NcnnInferenceEngine::runInference(const cv::Mat& imgRGB) {
    ncnn::Mat in = ncnn::Mat::from_pixels(imgRGB.data, ncnn::Mat::PIXEL_RGB, imgRGB.cols, imgRGB.rows);
    ncnn::Extractor ex = m_net.create_extractor();
    ex.input("data", in);
    ncnn::Mat out;
    ex.extract("fc1", out);

    return out.data != nullptr;
}
```

However, with onnxruntime, it looks like the input needs to be formatted as `float`. Thus, I am not sure if I am doing it correctly, and in particular this line: ` Ort::Value input_tensor = Ort::Value::CreateTensor<float>(memory_info, reinterpret_cast<float*>(imgRGBFloat.data), input_tensor_size, m_inputNodeDims.data(), 4);
    assert(input_tensor.IsTensor());
` 

Note `m_inputNodeDims` contains `{1, 3, 112, 112}` and is populated in class constructor which I have not included in above code.

**Comment by snnn** [comment]
The model doesn't work. Amazon agreed to fix it.
