### ISSUE TITLE
Which framework can export quantization model to onnx?

### ISSUE THREAD

**Issue by zealerww** [microsoft/onnxruntime#2839]
I use post-training or training-aware quantization methods in pytorch, but those models cannot be exported to onnx format. Any frameworks support that? I want to make inference using onnxruntime.

**Comment by tianleiwu** [comment]
@zealerww, you might post an issue to PyTorch to ask for supporting quantization in onnx exporter.

For post-training quantization, you could try our [quantization tool](https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization). There is a calibration tool is still in pull request. Let us know if you encountered problem using these tools.

**Comment by zealerww** [comment]
@tianleiwu hi ,i try thee quantization tool. 
However, the quantaization model is slower than fp32 model，and the cpu usage is only 100%(fp32 model is 500%), does it only support single thread?

**Comment by zealerww** [comment]
I got answer in https://github.com/microsoft/onnxruntime/issues/2871. Thanks.
