### ISSUE TITLE
 Type Error: Type 'tensor(bool)' of input parameter (1203) of operator (ReduceSum) in node () is invalid.

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#2848]
```
 Type Error: Type 'tensor(bool)' of input parameter (1203) of operator (ReduceSum) in node () is invalid.
```

And the code reproduce onnx is:

```
    candidate_inds = box_cls > self.pre_nms_thresh
        # [fgj] potential relate to this bug: ype Error: Type 'tensor(bool)' of input parameter (1203) of operator (ReduceSum) in node () is invalid
        # which invalid in ONNXRuntime
        pre_nms_top_n = candidate_inds.view(N, -1).sum(1)
        pre_nms_top_n = pre_nms_top_n.clamp(max=self.pre_nms_top_n)
```

Here is my attached onnx model:

https://drive.google.com/open?id=1CegIKH7PF_HzGpzXuTkQ4r38cMyKIG5H

I can make this model go through onnx.checker, but how can not forward in onnxruntime.

Any body knows how should I change something to make it forward?

**Comment by jinfagang** [comment]
I believe this is bug or somthing in onnxruntime? Since model can be checked on onnx.checker. Also I chagned to this still got that error:


```
 a = candidate_inds.view(N, -1)
        logging.info(a)
        pre_nms_top_n = torch.sum(a, dim=1)
        logging.info('prenms: {}'.format(pre_nms_top_n))
```

**Comment by skottmckay** [comment]
The model is invalid. ReduceSum does not support tensor(bool) as per the ONNX spec. Ideally the ONNX checker should catch that - not sure why it doesn't. 

https://github.com/onnx/onnx/blob/master/docs/Operators.md#reducesum

> Type Constraints
> T : tensor(uint32), tensor(uint64), tensor(int32), tensor(int64), tensor(float16), tensor(float), tensor(double)
> Constrain input and output types to high-precision numeric tensors.

**Comment by faxu** [comment]
Closing this issue since it's a model issue. CC @vinitra as FYI for onnx checker issue.

**Comment by Manojbhat09** [comment]
A banter of a frustrated user:

Its very frustrating when I export the model, pass the checker and face this error when running on device for onnxruntime. Please reopen this issue. 
I think many people in future too will face his and will be equally frustrated with the ReduceSum problem. 

I suggest to fix ONNX checker accordingly. 

Hopefully this will help reducing time in debugging and banging head to understand what is going on, eventually doing good for the future ONNX community. 
I plead again to fix this.

**Comment by Kamilbentounes** [comment]
Hello @Manojbhat09,

Im facing the same issue.. Have you fix it ? 

Thank's
