### ISSUE TITLE
No performance improvement using fp16 model

### ISSUE THREAD

**Issue by zealerww** [microsoft/onnxruntime#2871]
**Describe the bug**
I follow https://github.com/onnx/onnx-docker/blob/master/onnx-ecosystem/converter_scripts/float32_float16_onnx.ipynb to covert a resnet50 model to fp16，but I got no performance improvement when I using onnxruntime to test.

**System information**
- OS Platform and Distribution : Debian 9.9
- ONNX Runtime installed from: binary
- ONNX Runtime version: 1.1.0
- Python version:3.5

**Comment by zealerww** [comment]
More:
I test fp16 and int8 model in cpu (Intel(R) Xeon(R) CPU E5-2650 v4)
f16 model converted using https://github.com/onnx/onnx-docker/blob/master/onnx-ecosystem/converter_scripts/float32_float16_onnx.ipynb
int8 model converted using https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization

* fp32: time 1s; cpu usage 600%
* fp16: time 1s; cpu usage 600%
* int8: time 4s; cpu usage 100%

It seems that fp16 and int8 model has no improvement in cpu.

**Comment by tracysh** [comment]
The int8 GEMM in the last release was still single-threaded. A multi-threaded int8 GEMM was just turned on in master with PR#2844.

For the CPU, FP16 currently is handled by casting all operations to FP32. The GPU path does support FP16 natively.

**Comment by zealerww** [comment]
@tracysh 
I use the latest onnxruntime in master branch, but I also got similar result.

* fp32 model: time 40ms; cpu usage 450%
* int8 model: time 65ms; cpu usage  300%

Also cannot get performance improvement

I use resnet50 model in https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization/E2E_example_model

test code
```
import numpy as np
import onnxruntime as rt
import time

so = rt.SessionOptions()
so.intra_op_num_threads = 4
so.execution_mode = rt.ExecutionMode.ORT_SEQUENTIAL
so.graph_optimization_level = rt.GraphOptimizationLevel.ORT_DISABLE_ALL
sess = rt.InferenceSession('resnet50_int8.onnx', providers=['CPUExecutionProvider'], sess_options=so)

input_name = sess.get_inputs()[0].name
image = np.random.rand(1, 224, 224, 3).astype('float32')

for i in range(1000):
    t1 = time.time()
    output = sess.run(None, {input_name: image})
    t2 = time.time()
    print('time', t2 - t1)
```

quantization code
```
import onnx
from quantize import quantize, QuantizationMode

# Load the onnx model
model = onnx.load('resnet50_v1.onnx')
# Quantize
quantized_model = quantize(model, quantization_mode=QuantizationMode.IntegerOps, static=False)
# Save the quantized model
onnx.save(quantized_model, 'resnet50_int8.onnx')
```
Any idea?

**Comment by tracysh** [comment]
@zealerww There's still work in progress to improve quantized models. The change for the multi-threaded GEMM fixed half of the performance for ConvInteger. There's still a significant cost from the im2col step in the current implementation: for some of the early 3x3 kernel nodes, the im2col time is twice that of the GEMM. 

The float implementation of convolution that you get with ORT_DISABLE_ALL does better by threading the im2col step with the GEMM operation. The implementation also tiles the im2col operation to avoid needing to instantiate the entire buffer in memory. This has not been done for the integer convolution path.

If you enable ORT_ENABLE_ALL, the float convolution goes down a different path that does layout optimizations (the fp32 number above would be closer to 25ms I suspect). The equivalent also needs to be done for quantized convolution to avoid im2col completely.
