### ISSUE TITLE
Reshape 's requested shape is incorrect

### ISSUE THREAD

**Issue by lxl910915** [microsoft/onnxruntime#2872]
**Description**
Our model is [EAST](https://github.com/argman/EAST/blob/dca414de39a3a4915a019c9a02c1832a31cdd0ca/model.py#L76) of tensorflow. And we convert tensorflow saved_model to onnx. When we use onnxruntime.InferenceSession to run this model, we get the following error:
`2020-01-20 03:35:56.003457877 [E:onnxruntime:, sequential_executor.cc:183 Execute] Non-zero status code returned while running Reshape node. Name:'feature_fusion/Conv_9/Conv2D__260' Status Message: /tmp/onnxruntime/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:43 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{1,1,64,64}, requested shape:{139965333768264,139965333768264,139958748113104,139958748113104}`

**ONNX Information**
onnx version = 1.1.0
onnx opset = 10

**Comment by skottmckay** [comment]
This doesn't seem to be related to the open PR[s] around clarifying how Reshape treats a 0 in the requested shape. Based on your output the model is attempting to reshape to {139965333768264,139965333768264,139958748113104,139958748113104}, which looks completely incorrect. Where are the values for the target shape coming from? Can you share the onnx model?

**Comment by lxl910915** [comment]
Rebuild TRTIS, solved my problem. Thanks.

**Comment by skottmckay** [comment]
ONNX and onnxruntime support dynamic shapes. 

https://github.com/onnx/onnx/blob/master/docs/IR.md#static-tensor-shapes

> Each size in the list MAY be expressed as an integral value or as a "dimension variable," a string denoting that the actual size of the dimension is not statically constrained to a particular number. This is useful for declaring interfaces that care about the number of dimensions, but not the exact size of each dimension. A dimension MAY have neither dim_value nor dim_param set. Such a dimension represents an unknown dimension unrelated to other unknown dimensions.

**Comment by lxl910915** [comment]
> static-tensor-shapes

Can you provide an example how to using it. We want to convert tensorflow saved_model to onnx. If we do not fix the input shape when generating tensorflow saved_model, we get this error  https://github.com/microsoft/onnxruntime/issues/2872#issue-552121100

**Comment by skottmckay** [comment]
Based on the converstation on https://github.com/onnx/tensorflow-onnx/issues/784 it appears this is due to a TensorRT issue that is captured on https://github.com/microsoft/onnxruntime/issues/3034.

Please re-open if that's not the case.
