### ISSUE TITLE
Runtime error on Inference session 

### ISSUE THREAD

**Issue by patmaasridharan** [microsoft/onnxruntime#2875]
I have a custom UNet in pytorch and exported it to onnx model. That worked fine. On calling inference , there is problem with the optimizer. Below is the output.

ort_session = onnxruntime.InferenceSession("saved_model/seg_R.onnx")
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up1.trans_conv.bias'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up1.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up2.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down3.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down3.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up3.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up4.trans_conv.weight'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down1.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up1.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up4.trans_conv.bias'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up2.trans_conv.weight'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up1.trans_conv.weight'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down4.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'center.0.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down2.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down1.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up2.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down4.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'center.1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up2.trans_conv.bias'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up3.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up3.trans_conv.bias'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up3.trans_conv.weight'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'down2.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up4.convr2.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[W:onnxruntime:, graph.cc:2412 CleanUnusedInitializers] Removing initializer 'up4.convr1.bn.num_batches_tracked'. It is not used by any node and should be removed from the model.
[E:onnxruntime:, inference_session.cc:847 Initialize] Exception during initialization: /onnxruntime_src/onnxruntime/core/optimizer/optimizer_execution_frame.cc:73 onnxruntime::OptimizerExecutionFrame::Info::Info(const std::vector<const onnxruntime::Node*>&, const InitializedTensorSet&) [ONNXRuntimeError] : 1 : FAIL : Failed to find kernel for Neg
Stacktrace:

/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 25, in __init__self._load_model(providers)
/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 43, in _load_model self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /onnxruntime_src/onnxruntime/core/optimizer/optimizer_execution_frame.cc:73 onnxruntime::OptimizerExecutionFrame::Info::Info(const std::vector<const onnxruntime::Node*>&, const InitializedTensorSet&) [ONNXRuntimeError] : 1 : FAIL : Failed to find kernel for Neg

Does anyone has idea, why onnx inference fails though the model check doesn't show any error? Any leads will be appreciable :)

Thank you.

**Comment by skottmckay** [comment]
Are you using the CUDA execution provider? If so, this fix may be needed: https://github.com/microsoft/onnxruntime/pull/2510

**Comment by patmaasridharan** [comment]
No I dont have cuda for now.
I use onnxruntime=1.1.0 which has the "Fix constant folding of node assigned to CUDA" this commit merged already i believe. I tried to build onnxruntime from source. Still the same error. 

I also use optset version 11 when exporting the model to solve the upsampling issue.

**Comment by yufenglee** [comment]
What's the input type of the Neg node? Is it int64?

**Comment by patmaasridharan** [comment]
Its float32[1,1,256,256] both input and output of the network .

**Comment by skottmckay** [comment]
Are you able to share the model?

**Comment by patmaasridharan** [comment]
yes i can share it. 
https://www.dropbox.com/s/1wypohlqp9mj41f/Unet.onnx?dl=0

**Comment by skottmckay** [comment]
The inputs to the Neg nodes in that model are int64, which ORT currently doesn't support (but the ONNX spec says is allowed). The output from Shape is a int64 tensor, and that output goes -> Gather -> Sub -> Div -> Neg, and none of those operations is going to change the type. 

Are there any pytorch export options to avoid using int64 for Neg?

**Comment by patmaasridharan** [comment]
can i ask how do you find that output from Shape is a int64 tensor.
When i try to print model.graph i can only see the input type till ReLu 
![Outputonnxmodel](https://user-images.githubusercontent.com/54295010/73442448-24fc0a00-4355-11ea-803e-f0ac5bd4af37.PNG)

**Comment by hariharans29** [comment]
The output from a `Shape` node has to be an INT64 tensor according to the spec - https://github.com/onnx/onnx/blob/master/docs/Operators.md#Shape.
