### ISSUE TITLE
How to set provider in python api

### ISSUE THREAD

**Issue by zealerww** [microsoft/onnxruntime#2876]
I build onnxruntime with mlas and dnnl，but when I use python api, it seems that dnnl always be used. How can I use mlas in python api?

**Comment by KeDengMS** [comment]
Please use [providers in InferenceSession.__init__()](https://github.com/microsoft/onnxruntime/blob/87297846352a148c7b08b08a9998098a98ebcb20/onnxruntime/python/session.py#L16).

Example usage could be found [here](https://github.com/microsoft/onnxruntime/blob/b21576eeb0d8ca59b70ba39dee93eb6149f84195/onnxruntime/test/python/onnxruntime_test_python.py#L72-L73).

**Comment by zealerww** [comment]
thanks，I see. mlas corresponds to CPUExecutionProvider, dnnl corresponds to DnnlExecutionProvider
