### ISSUE TITLE
 building ONNXruntime with DNNL cause an error

### ISSUE THREAD

**Issue by mariamrahmaani** [microsoft/onnxruntime#2899]
**Describe the bug**
When building Onnxruntime with DNNL in Windows, I see the error below:

build.sh --use_dnnl

 Checking File Globs
  Performing update step for 'project_dnnl'
  custom_op_library.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\Debug\custom_op_library.dll
  libprotobuf.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\external\protobuf\cmake\Debug\libprotobufd.lib
  libprotoc.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\external\protobuf\cmake\Debug\libprotocd.lib
  protoc.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\external\protobuf\cmake\Debug\protoc.exe
  onnx_proto.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\onnx\Debug\onnx_proto.lib
  onnx.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\onnx\Debug\onnx.lib
  re2.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\external\re2\Debug\re2.lib
  onnx_test_data_proto.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\Debug\onnx_test_data_proto.lib
  libprotobuf-lite.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\external\protobuf\cmake\Debug\libprotobuf-lited.
  lib
  onnx_test_runner_common.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\Debug\onnx_test_runner_common.lib
  onnxruntime_common.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\Debug\onnxruntime_common.lib
  onnxruntime_framework.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\Debug\onnxruntime_framework.lib
  onnxruntime_graph.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\Debug\onnxruntime_graph.lib
  onnxruntime_mlas.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\Debug\onnxruntime_mlas.lib
  onnxruntime_optimizer.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\Debug\onnxruntime_optimizer.lib
  sign.cc
  shrink.cc
  deep_cpu_gru.cc
  sequence_ops.cc
  isinf.cc
  scatter.cc
  scatter_nd.cc
  slice.cc
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include\xutility(2483): error
C2220: warning treated as error - no 'object' file generated (compiling source file C:\repos\onnxruntime\onnxruntime\co
re\providers\cpu\tensor\scatter_nd.cc) [C:\repos\onnxruntime\build\Windows\Debug\onnxruntime_providers.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include\xutility(2483): warnin
g C4996: 'std::copy::_Unchecked_iterators::_Deprecate': Call to 'std::copy' with parameters that may be unsafe - this c
all relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WAR
NINGS. See documentation on how to use Visual C++ 'Checked Iterators' (compiling source file C:\repos\onnxruntime\onnxr
untime\core\providers\cpu\tensor\scatter_nd.cc) [C:\repos\onnxruntime\build\Windows\Debug\onnxruntime_providers.vcxproj
]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include\xutility(2483): note
  : see declaration of 'std::copy::_Unchecked_iterators::_Deprecate' (compiling source file C:\repos\onnxruntime\onnxru
  ntime\core\providers\cpu\tensor\scatter_nd.cc)
  C:\repos\onnxruntime\onnxruntime\core\providers\cpu\tensor\scatter_nd.cc(78): note: see reference to function templat
  e instantiation '_OutIt std::copy<const T*,T*>(_InIt,_InIt,_OutIt)' being compiled
          with
          [
              _OutIt=std::string *,
              T=std::string,
              _InIt=const std::string *
          ]
  C:\repos\onnxruntime\onnxruntime\core\providers\cpu\tensor\scatter_nd.cc(125): note: see reference to function templa
  te instantiation 'onnxruntime::common::Status onnxruntime::ScatterNDBase::PrepareForCompute<int64_t>(onnxruntime::OpK
  ernelContext *,onnxruntime::ScatterNDBase::Prepare &) const' being compiled
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include\xutility(2483): error
C2220: warning treated as error - no 'object' file generated (compiling source file C:\repos\onnxruntime\onnxruntime\co
re\providers\cpu\tensor\scatter.cc) [C:\repos\onnxruntime\build\Windows\Debug\onnxruntime_providers.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include\xutility(2483): warnin
g C4996: 'std::copy::_Unchecked_iterators::_Deprecate': Call to 'std::copy' with parameters that may be unsafe - this c
all relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WAR
NINGS. See documentation on how to use Visual C++ 'Checked Iterators' (compiling source file C:\repos\onnxruntime\onnxr
untime\core\providers\cpu\tensor\scatter.cc) [C:\repos\onnxruntime\build\Windows\Debug\onnxruntime_providers.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\include\xutility(2483): note
  : see declaration of 'std::copy::_Unchecked_iterators::_Deprecate' (compiling source file C:\repos\onnxruntime\onnxru
  ntime\core\providers\cpu\tensor\scatter.cc)
  C:\repos\onnxruntime\onnxruntime\core\providers\cpu\tensor\scatter.cc(82): note: see reference to function template i
  nstantiation '_OutIt std::copy<const T*,T*>(_InIt,_InIt,_OutIt)' being compiled
          with
          [
              _OutIt=std::string *,
              T=std::string,
              _InIt=const std::string *
          ]
  C:\repos\onnxruntime\onnxruntime\core\providers\cpu\tensor\scatter.cc(174): note: see reference to function template
  instantiation 'onnxruntime::common::Status onnxruntime::CopyScatterData<int32_t,T>(const onnxruntime::Tensor *,const
  onnxruntime::Tensor *,const onnxruntime::Tensor *,const int64_t,onnxruntime::Tensor *)' being compiled
          with
          [
              T=float
          ]
  C:\repos\onnxruntime\onnxruntime\core\providers\cpu\tensor\scatter.cc(229): note: see reference to function template
  instantiation 'onnxruntime::common::Status onnxruntime::CopyInt32Index<float,const T*&,const T*&,const T*&,const int6
  4_t&,onnxruntime::Tensor*&>(const T *&,const T *&,const T *&,const int64_t &,onnxruntime::Tensor *&)' being compiled
          with
          [
              T=onnxruntime::Tensor
          ]

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): after cloning source
- ONNX Runtime version: latest code
- Python version:  Python 3.6.1 :: Anaconda 4.4.0 (64-bit)
- Visual Studio version (if applicable): VS 2017
- GCC/Compiler version (if compiling from source):cmake version 3.16.2
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
Describe steps/code to reproduce the behavior:

git clone https://github.com/microsoft/onnxruntime.git
build.bat --use_dnnl

**Expected behavior**
 onnxruntime_providers_dnnl.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\Debug\onnxruntime_providers_dnnl.lib
  onnxruntime_session.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\Debug\onnxruntime_session.lib
  onnxruntime_test_utils.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\Debug\onnxruntime_test_utils.lib
  onnxruntime_util.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\Debug\onnxruntime_util.lib
  win_getopt_wide.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\Debug\win_getopt_wide.lib
  onnxruntime_mlas_test.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\Debug\onnxruntime_mlas_test.exe
  gmock.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\external\googletest\googlemock\Debug\gmockd.lib
  gtest.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\external\googletest\googlemock\gtest\Debug\gtestd.lib
  onnxruntime_test_utils_for_framework.vcxproj -> C:\repos\onnxruntime\build\Windows\Debug\Debug\onnxruntime_test_utils
  _for_framework.lib
Traceback (most recent call last):
  File "C:\repos\onnxruntime\\tools\ci_build\build.py", line 983, in <module>
    sys.exit(main())
  File "C:\repos\onnxruntime\\tools\ci_build\build.py", line 922, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "C:\repos\onnxruntime\\tools\ci_build\build.py", line 415, in build_targets
    run_subprocess(cmd_args)
  File "C:\repos\onnxruntime\\tools\ci_build\build.py", line 200, in run_subprocess
    completed_process = subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "C:\Anaconda3\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', 'C:\\repos\\onnxruntime\\\\build\\Windows\\Debug', '--config', 'Debug']' returned non-zero exit status 1.

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by jywu-msft** [comment]
noticed you have an older version of VS2017. (15.7)
can you update to 15.9?

**Comment by mariamrahmaani** [comment]
yes, it worked.
Thanks
