### ISSUE TITLE
Alpine Linux support

### ISSUE THREAD

**Issue by Pavel-Konarik** [microsoft/onnxruntime#2909]
**Is your feature request related to a problem? Please describe.**
onnxruntime-1.1.1-cp36-cp36m-manylinux1_x86_64.whl is not supported on Alpine 3.11

**System information**
- ONNX Runtime version (you are using):
1.1.1

**Describe the solution you'd like**
Include support for Alpine Linux in manylinux wheel so `pip install onnxruntime` works

**Describe alternatives you've considered**
Building from source

**Additional context**
`ERROR: onnxruntime-1.1.1-cp36-cp36m-manylinux1_x86_64.whl is not a supported wheel on this platform.`

**Comment by snnn** [comment]
Any hint what we should do?

**Comment by Pavel-Konarik** [comment]
Sadly I am not sure why manylinux for onnxruntime does not include support for Alpine Linux, but here are steps to quickly reproduce the error and some additional info. 

**Why Alpine Linux?**
I am building a simple and **small** predictor in Docker, and alpine has much smaller image than Ubuntu
**Does installing onnx give the same error?**
No, `pip install onnx` works as intended
**Steps to replicate**
`#Dockerfile
FROM python:3.6.10-alpine3.11

RUN apk --no-cache add wget build-base gcc git cmake gfortran musl-dev bash bash-doc bash-completion freetype-dev &&\
    apk --no-cache add jpeg-dev zlib-dev make && pip --version && pip install --upgrade pip

RUN pip install onnx==1.6.0 onnxruntime==1.1.1`
Build Docker image using 
`docker build -t onnximage -f <Dockerfile path> .`

**Python version**
Python 3.6.10

I am happy to provide/try anything. At the moment I am trying to compile from source.

**Comment by shaharv** [comment]
Unfortunately, `manylinux` wheels are not compatible with Alpine Linux. In fact, Alpine Linux and musl based distros are not currently not supported by python wheels:
https://github.com/pypa/manylinux/issues/37

Alpine is based on [musl libc][1], as opposed [glibc][2], the GNU standard C library, which is used by most Linux distros and supported by `manylinux`. musl is a minimalistic and novel libc implementation, and as such misses many glibc features. In addition, there are subtle functional differences (such as smaller default thread stack size, dynamic linking behavior, locales implementation, etc.).

Detailed musl/glibc comparisons could be found here:

- [Comparison of C/POSIX standard library implementations for Linux (ETA Labs)][3]
- [Functional differences from glibc (musl-libc.org, archived)][4]

Until Alpine Linux wheel support is added, installing wheels on Alpine will have to fall back to building the wheel from source, which will probably require support in the `onnxruntime` wheel build script.

FYI, I created a docker image for building onnxruntime from source on Alpine 3.11 (python 3.8.2, gcc 9.2.0) - perhaps it could be useful: [Dockerfile][5]. Some minor tweaking was required to overcome some build and dependency issues, but besides that the C++ build itself was very smooth.

[1]: https://musl.libc.org
[2]: https://www.gnu.org/software/libc
[3]: https://www.etalabs.net/compare_libcs.html
[4]: https://web.archive.org/web/20191222035852/https://wiki.musl-libc.org/functional-differences-from-glibc.html
[5]: https://github.com/shaharv/docker/blob/master/alpine/onnxruntime/Dockerfile

**Comment by Pavel-Konarik** [comment]
@shaharv Thanks for the amazing explanation and the Dockerfile! You rock!

**Comment by sanmai-NL** [comment]
@Pavel-Konarik: May I suggest you reopen this issue, and take a look at https://github.com/pypa/manylinux/issues/37#issuecomment-864510694?

**Comment by svenha** [comment]
auditwheel 5.0.0 added musl support on 2021-09-18 (also manylinux), cibuildwheel 2.2.0 did so on 2021-10-22.

**Comment by 29x10** [comment]
any update on this? still failed

**Comment by snnn** [comment]
Sorry the work is not started yet.

**Comment by sunjingsong** [comment]
Hello, any update on this? I met similar problem on Alpine Linux to deploy ML on java server

**Comment by esandoval30** [comment]
+ 1. Facing exactly this same issue in alpine docker image running my java server app

**Comment by svenha** [comment]
> See [testing/onnxruntime](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/onnxruntime), testing/onnxruntime-dev and testing/py3-onnxruntime are now available.

Excellent news. I installed these packages on a postmarketOS phone, added Larynx and get very good speech output from this text-to-speech system.

Maybe someone can close this issue?

**Comment by pxpy** [comment]
> Hello, any update on this? I met similar problem on Alpine Linux to deploy ML on java server

+1

**Comment by ell1e** [comment]
There seems to be some problem with onnxruntime's Alpine support, and current Alpine Edge:

https://github.com/microsoft/onnxruntime/issues/14102#issuecomment-5335991163

```
$ pip3 install --break-system-packages --user onnxruntime
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime
$ pip3 debug --verbose
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 26.1.2 from /usr/lib/python3.14/site-packages/pip (python 3.14)
sys.version: 3.14.7 (main, Aug 16 2026, 00:26:39) [GCC 15.2.0]
sys.executable: /usr/bin/python3
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: UTF-8
sys.platform: linux
sys.implementation:
  name: cpython
'cert' config value: global
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): /etc/ssl/certs/ca-certificates.crt
pip._vendor.DEBUNDLED: False
vendored library versions:
  CacheControl==0.14.4 (Unable to locate actual module version, using vendor.txt specified version)
  distlib==0.4.0
  distro==1.9.0
  msgpack==1.1.2
  packaging==26.2
  platformdirs==4.5.1
  pyproject-hooks==1.2.0
  requests==2.33.1
  certifi==2026.02.25
  idna==3.11
  urllib3==2.6.3
  rich==14.2.0 (Unable to locate actual module version, using vendor.txt specified version)
  pygments==2.19.2
  resolvelib==1.2.1
  setuptools==70.3.0 (Unable to locate actual module version, using vendor.txt specified version)
  tomli==2.3.1
  tomli-w==1.2.0
  truststore==0.10.4
Compatible tags: 141
  cp314-cp314-musllinux_1_2_x86_64
  cp314-cp314-musllinux_1_1_x86_64
  cp314-cp314-musllinux_1_0_x86_64
  cp314-cp314-linux_x86_64
  cp314-abi3-musllinux_1_2_x86_64
  cp314-abi3-musllinux_1_1_x86_64
  cp314-abi3-musllinux_1_0_x86_64
  cp314-abi3-linux_x86_64
  cp314-none-musllinux_1_2_x86_64
  cp314-none-musllinux_1_1_x86_64
  cp314-none-musllinux_1_0_x86_64
  cp314-none-linux_x86_64
  cp313-abi3-musllinux_1_2_x86_64
  cp313-abi3-musllinux_1_1_x86_64
  cp313-abi3-musllinux_1_0_x86_64
  cp313-abi3-linux_x86_64
  cp312-abi3-musllinux_1_2_x86_64
  cp312-abi3-musllinux_1_1_x86_64
  cp312-abi3-musllinux_1_0_x86_64
  cp312-abi3-linux_x86_64
  cp311-abi3-musllinux_1_2_x86_64
  cp311-abi3-musllinux_1_1_x86_64
  cp311-abi3-musllinux_1_0_x86_64
  cp311-abi3-linux_x86_64
  cp310-abi3-musllinux_1_2_x86_64
  cp310-abi3-musllinux_1_1_x86_64
  cp310-abi3-musllinux_1_0_x86_64
  cp310-abi3-linux_x86_64
  cp39-abi3-musllinux_1_2_x86_64
  cp39-abi3-musllinux_1_1_x86_64
  cp39-abi3-musllinux_1_0_x86_64
  cp39-abi3-linux_x86_64
  cp38-abi3-musllinux_1_2_x86_64
  cp38-abi3-musllinux_1_1_x86_64
  cp38-abi3-musllinux_1_0_x86_64
  cp38-abi3-linux_x86_64
  cp37-abi3-musllinux_1_2_x86_64
  cp37-abi3-musllinux_1_1_x86_64
  cp37-abi3-musllinux_1_0_x86_64
  cp37-abi3-linux_x86_64
  cp36-abi3-musllinux_1_2_x86_64
  cp36-abi3-musllinux_1_1_x86_64
  cp36-abi3-musllinux_1_0_x86_64
  cp36-abi3-linux_x86_64
  cp35-abi3-musllinux_1_2_x86_64
  cp35-abi3-musllinux_1_1_x86_64
  cp35-abi3-musllinux_1_0_x86_64
  cp35-abi3-linux_x86_64
  cp34-abi3-musllinux_1_2_x86_64
  cp34-abi3-musllinux_1_1_x86_64
  cp34-abi3-musllinux_1_0_x86_64
  cp34-abi3-linux_x86_64
  cp33-abi3-musllinux_1_2_x86_64
  cp33-abi3-musllinux_1_1_x86_64
  cp33-abi3-musllinux_1_0_x86_64
  cp33-abi3-linux_x86_64
  cp32-abi3-musllinux_1_2_x86_64
  cp32-abi3-musllinux_1_1_x86_64
  cp32-abi3-musllinux_1_0_x86_64
  cp32-abi3-linux_x86_64
  py314-none-musllinux_1_2_x86_64
  py314-none-musllinux_1_1_x86_64
  py314-none-musllinux_1_0_x86_64
  py314-none-linux_x86_64
  py3-none-musllinux_1_2_x86_64
  py3-none-musllinux_1_1_x86_64
  py3-none-musllinux_1_0_x86_64
  py3-none-linux_x86_64
  py313-none-musllinux_1_2_x86_64
  py313-none-musllinux_1_1_x86_64
  py313-none-musllinux_1_0_x86_64
  py313-none-linux_x86_64
  py312-none-musllinux_1_2_x86_64
  py312-none-musllinux_1_1_x86_64
  py312-none-musllinux_1_0_x86_64
  py312-none-linux_x86_64
  py311-none-musllinux_1_2_x86_64
  py311-none-musllinux_1_1_x86_64
  py311-none-musllinux_1_0_x86_64
  py311-none-linux_x86_64
  py310-none-musllinux_1_2_x86_64
  py310-none-musllinux_1_1_x86_64
  py310-none-musllinux_1_0_x86_64
  py310-none-linux_x86_64
  py39-none-musllinux_1_2_x86_64
  py39-none-musllinux_1_1_x86_64
  py39-none-musllinux_1_0_x86_64
  py39-none-linux_x86_64
  py38-none-musllinux_1_2_x86_64
  py38-none-musllinux_1_1_x86_64
  py38-none-musllinux_1_0_x86_64
  py38-none-linux_x86_64
  py37-none-musllinux_1_2_x86_64
  py37-none-musllinux_1_1_x86_64
  py37-none-musllinux_1_0_x86_64
  py37-none-linux_x86_64
  py36-none-musllinux_1_2_x86_64
  py36-none-musllinux_1_1_x86_64
  py36-none-musllinux_1_0_x86_64
  py36-none-linux_x86_64
  py35-none-musllinux_1_2_x86_64
  py35-none-musllinux_1_1_x86_64
  py35-none-musllinux_1_0_x86_64
  py35-none-linux_x86_64
  py34-none-musllinux_1_2_x86_64
  py34-none-musllinux_1_1_x86_64
  py34-none-musllinux_1_0_x86_64
  py34-none-linux_x86_64
  py33-none-musllinux_1_2_x86_64
  py33-none-musllinux_1_1_x86_64
  py33-none-musllinux_1_0_x86_64
  py33-none-linux_x86_64
  py32-none-musllinux_1_2_x86_64
  py32-none-musllinux_1_1_x86_64
  py32-none-musllinux_1_0_x86_64
  py32-none-linux_x86_64
  py31-none-musllinux_1_2_x86_64
  py31-none-musllinux_1_1_x86_64
  py31-none-musllinux_1_0_x86_64
  py31-none-linux_x86_64
  py30-none-musllinux_1_2_x86_64
  py30-none-musllinux_1_1_x86_64
  py30-none-musllinux_1_0_x86_64
  py30-none-linux_x86_64
  cp314-none-any
  py314-none-any
  py3-none-any
  py313-none-any
  py312-none-any
  py311-none-any
  py310-none-any
  py39-none-any
  py38-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any
```
