### ISSUE TITLE
multiple Output  C-Api 

### ISSUE THREAD

**Issue by Armin234** [microsoft/onnxruntime#2923]
My Onnx has two Outputs, but when I call 

const char* input_names[] = { "Input","Input_2" };
const char* output_names[] = { "Affine" ,"Affine_2" };
lStat = g_ort->Run(session, NULL, input_names, (const OrtValue* const*)&input_tensor[0], **2,** output_names, 2, &output_tensor[0]);

I get a memory access Violation.

Asking only the first Output
 lStat = g_ort->Run(session, NULL, input_names, (const OrtValue* const*)&input_tensor[0], 1, output_names, **1,** &output_tensor[0]);
 is working.

 I get the error with cpu provider and also with the cuda provider

**System information**
- Win 10 Pro
- ONNX Runtime installed from (source or binary): binary / GPU
- ONNX Runtime version: 1.1.1
- Visual Studio version (if applicable): Visual Studio 2015 
- CUDA/cuDNN version: 10 / 7.6.5.32
- GPU model and memory:  RTX 2070 Super 8GB

 ONNX-File
[schrott.zip](https://github.com/microsoft/onnxruntime/files/4122560/schrott.zip)

**Comment by pranavsharma** [comment]
Are you sure input_tensor and output_tensor are arrays of 2 elements each?

**Comment by hariharans29** [comment]
Not sure how 
`lStat = g_ort->Run(session, NULL, input_names, (const OrtValue* const*)&input_tensor[0], **1**, output_names, 1, &output_tensor[0]);`
would run successfully end to end.

The model has 2 inputs and both the inputs need to provided (even to get the first output alone).
I fed it random data and could get the model to score successfully (the results are not right given the input data is garbage) with this (after creating all the `OrtValue`s) - 

OrtValue* input_tensors[2];
// fill in each OrtValue

OrtValue* output_tensors[2];
output_tensors[0] = NULL;
output_tensors[1] = NULL;

CheckStatus(g_ort->Run(session, NULL, input_node_names.data(), (const OrtValue* const*)&input_tensors, 2, output_node_names.data(), 2, (OrtValue**)&output_tensors));

**Comment by Armin234** [comment]
Hi Hariharans,

adding the two lines
output_tensors[0] = NULL;
output_tensors[1] = NULL;

solved  my problem.

Thanks,
Armin
