### ISSUE TITLE
[LSTM] C# saving internal states for scoring and usage of tensor sequences as inputs

### ISSUE THREAD

**Issue by Mar-Mo** [microsoft/onnxruntime#2960]
**Describe the bug**
When scoring a previously trained LSTM network it loses its internal states. Basically if the same Tensor is used as input multiple times the output stays the same.

Additionally i'm not sure how to pass a sequence of Tensors as input to the model and if it is supported right now.

**Urgency**
Normal
(i want to use it within my masters thesis as additional possibility to run exported onnx models from matlab)

**System information**
Win 10
ONNX Runtime v 1.1.1 (via NuGet)
Visual Studio 2017 V 15.9.19 (C#)

**To Reproduce**
I have exported a Matlab LSTM Network combined with fully connected layers to onnx. It was trained on PT1 (first order system) behaviour. But if the same input tensor is given multiple times to the model the output value is always the same.
I can gladly provide sample code if needed.
[ONNX_PT1.zip](https://github.com/microsoft/onnxruntime/files/4139668/ONNX_PT1.zip)

**Expected behavior**
My goal is to run it in a kind of "real-time" environment to mimic the behaviour of a control system. The trained model behaves like a PT1 element (first oder lag). 
When a sequence of multiple zeros and multiple time steps with the same value are given as input (e.g. 0, 0, 0, 0, 2, 2, 2, 2, ... ) then the output should reach the value of the input, but the network seems to forget it's internal states each time ".Run(inputs)" is called on an InferenceSession.

This issue is closely related to #1659

For testing purposes i would also like to use a sequence of tensors to see if the ONNXRuntime behaviour is the same as in Matlab, but this becomes obsolete for me if the models internal state could be preserved.

Is there an option to keep the internal state or save it after each "Run" and apply it to the InferenceSession before running?

**Comment by pavelgorev** [comment]
I'm trying the same thing! I imported the example Matlab model from here https://www.mathworks.com/help/deeplearning/examples/time-series-forecasting-using-deep-learning.html into ONNX. Here is my code (this is a modification of this sample: https://github.com/microsoft/onnxruntime/blob/master/csharp/sample/Microsoft.ML.OnnxRuntime.InferenceSample/Program.cs and this one: https://github.com/microsoft/onnxruntime/blob/master/docs/CSharp_API.md#getting-started):

```
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;
using System;
using System.Collections;
using System.Collections.Generic;

namespace NetworkTest
{
    public sealed class Sample
    {
        private const string modelPath = @"E:\Documents\MATLAB\NeuralNetworkExport\onnx_lstm_medic.onnx";

        public void Infere()
        {
            using (var session = new InferenceSession(modelPath))
            {
                // Works ok with a single value:
                float[] inputData = new float[] { 0.258881980200294f };
                // I don't even know how to input the sequence of two values, 
                // the net always forgets its state, no matter what I try to do:
                // float[] inputData = new float[] { 0.258881980200294f, 1.35414790405090f };

                int[] dimensions = new int[] { 1, 1, 1 };

                var tensor = new DenseTensor<float>(inputData, dimensions);

                var input = NamedOnnxValue.CreateFromTensor("sequenceinput", tensor);

                var container = new List<NamedOnnxValue> { input };

                //Run the inference
                using (var results = session.Run(container))  // results is an IDisposableReadOnlyCollection<DisposableNamedOnnxValue> container
                {
                    // dump the results
                    foreach (var r in results)
                    {
                        Console.WriteLine("Output for {0}", r.Name);
                        Console.WriteLine(r.AsTensor<float>().GetArrayString());
                    }
                }

            }
        }
    }
}
```
