### ISSUE TITLE
 docker build fails when pip installing on onnx:   Protobuf compiler not found   

### ISSUE THREAD

**Issue by lefromage** [microsoft/onnxruntime#2965]
**Describe the bug**
 build failed from source for docker 

command fails to build from generic Dockerfile.source

**Expected behavior**
docker should build for CPU

**Urgency**
important 

**System information**
Docker 
Ubuntu 16.04

**To Reproduce**
time docker build -t onnxruntime-source -f Dockerfile.source .

Processing ./build/Linux/Release/dist/onnxruntime-1.1.0-cp38-cp38-linux_x86_64.whl
Requirement already satisfied: numpy>=1.18.0 in /opt/miniconda/lib/python3.8/site-packages (from onnxruntime==1.1.0) (1.18.1)
Collecting onnx>=1.2.3
  Downloading onnx-1.6.0.tar.gz (3.1 MB)
Collecting protobuf
  Downloading protobuf-3.11.2-cp38-cp38-manylinux1_x86_64.whl (1.3 MB)
Requirement already satisfied: six in /opt/miniconda/lib/python3.8/site-packages (from onnx>=1.2.3->onnxruntime==1.1.0) (1.14.0)
Collecting typing-extensions>=3.6.2.1
  Downloading typing_extensions-3.7.4.1-py3-none-any.whl (20 kB)
Requirement already satisfied: setuptools in /opt/miniconda/lib/python3.8/site-packages (from protobuf->onnx>=1.2.3->onnxruntime==1.1.0) (45.1.0.post20200127)
Building wheels for collected packages: onnx
  Building wheel for onnx (setup.py): started
  Building wheel for onnx (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/miniconda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bgua_zk4/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bgua_zk4/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-f_i4ii9s
       cwd: /tmp/pip-install-bgua_zk4/onnx/
  Complete output (64 lines):
  fatal: Not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  -- The C compiler identification is GNU 5.4.0
  -- The CXX compiler identification is GNU 5.4.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  Generated: /tmp/pip-install-bgua_zk4/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  CMake Error at CMakeLists.txt:248 (message):
    Protobuf compiler not found
  Call Stack (most recent call first):
    CMakeLists.txt:279 (relative_protobuf_generate_cpp)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-bgua_zk4/onnx/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-bgua_zk4/onnx/setup.py", line 315, in <module>
      setuptools.setup(
    File "/opt/miniconda/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/opt/miniconda/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/miniconda/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/miniconda/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/miniconda/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/opt/miniconda/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/miniconda/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/miniconda/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/miniconda/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/miniconda/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-bgua_zk4/onnx/setup.py", line 209, in run
      self.run_command('cmake_build')
    File "/opt/miniconda/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/miniconda/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-bgua_zk4/onnx/setup.py", line 195, in run
      subprocess.check_call(cmake_args)
    File "/opt/miniconda/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/code/cmake-3.14.3-Linux-x86_64/bin/cmake', '-DPYTHON_INCLUDE_DIR=/opt/miniconda/include/python3.8', '-DPYTHON_EXECUTABLE=/opt/miniconda/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-38-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-bgua_zk4/onnx']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for onnx
  Running setup.py clean for onnx
Failed to build onnx

**Comment by snnn** [comment]
Please report it to https://github.com/onnx/onnx

**Comment by snnn** [comment]
Thank you for reporting this. It is due to my recent change in : https://github.com/microsoft/onnxruntime/commit/fd334aff44b5e5dfe698716a31808c9d002586b3#diff-2eeaed663bd0d25b7e608891384b7298

We'll update the docker file and fix the issue.

**Comment by nhiem2000** [comment]
Has this been fixed yet?  or is there any work around in the mean time?
I am seeing similar error with the Dockerfile.cuda build.
``2020-02-13 22:03:14,770 Build [DEBUG] - Subprocess completed. Return code=0
2020-02-13 22:03:14,771 Build [INFO] - Build complete
Processing ./build/Linux/Release/dist/onnxruntime_gpu-1.1.0-cp38-cp38-linux_x86_64.whl
Requirement already satisfied: numpy>=1.18.0 in /opt/miniconda/lib/python3.8/site-packages (from onnxruntime-gpu==1.1.0) (1.18.1)
Collecting onnx>=1.2.3
  Downloading onnx-1.6.0.tar.gz (3.1 MB)
Collecting protobuf
  Downloading protobuf-3.11.3-cp38-cp38-manylinux1_x86_64.whl (1.3 MB)
Requirement already satisfied: six in /opt/miniconda/lib/python3.8/site-packages (from onnx>=1.2.3->onnxruntime-gpu==1.1.0) (1.14.0)
Collecting typing-extensions>=3.6.2.1
  Downloading typing_extensions-3.7.4.1-py3-none-any.whl (20 kB)
Requirement already satisfied: setuptools in /opt/miniconda/lib/python3.8/site-packages (from protobuf->onnx>=1.2.3->onnxruntime-gpu==1.1.0) (45.2.0.post20200210)
Building wheels for collected packages: onnx
  Building wheel for onnx (setup.py): started
  Building wheel for onnx (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/miniconda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ddta3u1j/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ddta3u1j/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-0xoe58g8
       cwd: /tmp/pip-install-ddta3u1j/onnx/
  Complete output (64 lines):
  fatal: not a git repository (or any of the parent directories): .git
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  -- The C compiler identification is GNU 7.4.0
  -- The CXX compiler identification is GNU 7.4.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  Generated: /tmp/pip-install-ddta3u1j/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
  CMake Error at CMakeLists.txt:248 (message):
    Protobuf compiler not found
  Call Stack (most recent call first):
    CMakeLists.txt:279 (relative_protobuf_generate_cpp)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-install-ddta3u1j/onnx/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-ddta3u1j/onnx/setup.py", line 315, in <module>
      setuptools.setup(
    File "/opt/miniconda/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/opt/miniconda/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/miniconda/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/miniconda/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/miniconda/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/opt/miniconda/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/miniconda/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/miniconda/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/miniconda/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/miniconda/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-ddta3u1j/onnx/setup.py", line 209, in run
      self.run_command('cmake_build')
    File "/opt/miniconda/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/miniconda/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-ddta3u1j/onnx/setup.py", line 195, in run
      subprocess.check_call(cmake_args)
    File "/opt/miniconda/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/code/cmake-3.14.3-Linux-x86_64/bin/cmake', '-DPYTHON_INCLUDE_DIR=/opt/miniconda/include/python3.8', '-DPYTHON_EXECUTABLE=/opt/miniconda/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-38-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-ddta3u1j/onnx']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for onnx

**Comment by vinitra** [comment]
Resolved in #3016 by building onnx dependency from source. #3023 has additional details.
