### ISSUE TITLE
Using TensorRT at fp16 precision

### ISSUE THREAD

**Issue by Drugbird** [microsoft/onnxruntime#2967]
**Is your feature request related to a problem? Please describe.**

No

**System information**
- ONNX Runtime version (you are using): 1.1.0

**Describe the solution you'd like**

I'd like to be able to infer networks using onnxruntime with the TensorRT backend using fp16 precision. The TensorRT backend already supports this, so it would be nice if this were accessible from within the onnxruntime framework.

**Describe alternatives you've considered**

Alternative solution at the moment is to directly use TensorRT rather than onnxruntime.

**Additional context**

trtexec supports this feature with the --fp16 flag. In C API you can check wether fp16 is supported with "builder->platformHasFastFp16", and enable it with "config->setFlag(BuilderFlag::kFP16);" (see https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#mixed_precision). 

As I can see it, the OpenVINO backend also supports selecting your inference precision by specifying "--use_openvino <hardware_option>" during build-time, where (hardware options) is one of [CPU_FP32, GPU_FP32, GPU_FP16, MYRIAD_FP16, VAD-M_FP16, VAD-M_FP32]. A similar option for TensorRT would solve this issue.

**Comment by jywu-msft** [comment]
yes, we should be supporting this in the next release.
@stevenlix FYI

**Comment by vinitra** [comment]
Support for TensorRT FP16 mode has been added to the master branch in PR https://github.com/microsoft/onnxruntime/pull/2973. 

You can enable ORT TensorRT FP16 mode by setting the environment variable `ORT_TENSORRT_FP16_ENABLE=1`. For more details, take a look at the [ORT TensorRT EP documentation](https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/TensorRT-ExecutionProvider.md#configuring-environment-variables).
