### ISSUE TITLE
Quantized model runs slower

### ISSUE THREAD

**Issue by ggeor84** [microsoft/onnxruntime#2969]
**Describe the bug**
I used the calibrate.py tool to quantize resnet-50. Quantized resnet-50 runs approximately 10x slower than baseline. Measurements made by mlperf tool. onnxruntime cpu.

**Urgency**
04/2020 deadline

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.1.0
- Python version: 3.6.9
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.2/
- GPU model and memory: TITAN RTX

**To Reproduce**
Describe steps/code to reproduce the behavior:
resnet model downloaded from https://github.com/mlperf/inference/tree/master/v0.5/classification_and_detection#prerequisites-and-installation
Specifically: https://zenodo.org/record/2592612/files/resnet50_v1.onnx

timed it using:
./run_local.sh \
onnxruntime \
resnet50 \
cpu \
--count 1000 \
--accuracy

then, I quantized it using the calibrate.py tool:
python calibrate.py \
--model_path=resnet50_v1.onnx \
--output_model_path=./models/calibrated_quantized_model.onnx \
--dataset_path=./calibration_dataset \
--data_preprocess=preprocess_method2

and then timed it using the same tool as above (run_local.sh)
Note: size of model that indeed reduce ~4x.

**Expected behavior**
Quantized model should run 2-4x faster

**Screenshots**
None

**Additional context**
Timings on cpu

**Comment by ggeor84** [comment]
Here is the report for the baseline (full precision model):
TestScenario.SingleStream qps=35.79, mean=0.0277, time=13.971, acc=76.000%, queries=500, tiles=50.0:0.0272,80.0:0.0307,90.0:0.0334,95.0:0.0350,99.0:0.0436,99.9:0.0491
accuracy=76.000%, good=380, total=500

Here is the report for the quantized one:
TestScenario.SingleStream qps=3.89, mean=0.2567, time=128.457, acc=74.400%, queries=500, tiles=50.0:0.2560,80.0:0.2609,90.0:0.2647,95.0:0.2715,99.0:0.2869,99.9:0.30

**Comment by yufenglee** [comment]
@ggeor84 Quantization in ONNXRuntime 1.1.0 only supports single thread. We enabled multi-thread for quantification in PR #2844 . Could you please try our latest master and see if you can get an on-par performance?

**Comment by faxu** [comment]
@ggeor84 were you able to retry this with the newest version? let us know if continued support is needed

**Comment by ggeor84** [comment]
@faxu I did and still saw no improvement. I shared with @yufenglee via email my repos to reproduce results. do you want to continue the discussion here or via email?

**Comment by xserraalza** [comment]
Is there any update on this? Using the latest master I experience the same problem. Thanks!

**Comment by yufenglee** [comment]
@xserraalza, the performance issue should be resolved with #3196 and #3283. It should be expected to get an on-par performance. Let us know if you still see quantized model is much slower than baseline.

**Comment by Kyuuki93** [comment]
@yufenglee , I have met same issue described here.  I also tried resnet50_v1.onnx which provider above, with "CUDAExecutionProvider" resnet50_v1.onnx got 174FPS and resnet50_v1_quantized.onnx got 3FPS.

quantizied model was created by run 
`python3 calibrate.py --model_path resnet50_v1.onnx --dataset_path images/ --dataset_size 1000 --data_preprocess preprocess_methond2`

System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
ONNX Runtime installed from (source or binary): source （master up to date 2020/06/17）
ONNX Runtime version: 1.3.1 
Python version: 3.6.9
Visual Studio version (if applicable): N/A
GCC/Compiler version (if compiling from source): 8.4.0
CUDA/cuDNN version: 10.2/
GPU model and memory:  GTX 1080Ti

**Comment by FrancescoSaverioZuppichini** [comment]
same, my quantized model is about 2x slower than the original one
