### ISSUE TITLE
Upload torch model in C#

### ISSUE THREAD

**Issue by natank1** [microsoft/onnxruntime#2990]
**Describe the bug**
I try to upload a model that has been trained in Pytorch in GPU and exported to ONNX in CPU.
When I try to upload it in C#  
var session = new InferenceSession(Model_file_path.onnx);
I get this message 

"Microsoft.ML.OnnxRuntime.OnnxRuntimeException: '[ErrorCode:Fail] Node () Op (Conv) [ShapeInferenceError] Attribute dilations has incorrect size'
" 
Help

**Comment by hariharans29** [comment]
Is the model shareable ? These errors are usually an artifact of something in the model that triggers these errors. So, it cannot be debugged without the model...

**Comment by natank1** [comment]
Do you need both the pth and the onnx?

**Comment by natank1** [comment]
Which one is required the onnx or the torch model (pth)?

**Comment by natank1** [comment]
That's the code

model = prod_spec_CNN(yaml_data,, 'cpu').to('cpu')
model.load_state_dict(torch.load('model_test.pth', map_location='cpu'))
xx = torch.randn( 1,1,150, 1025)
torch.onnx.export(model, xx, "model_a1_for_study.onnx", input_names="features", output_names=[ "output1" ], verbose=True)

These are the files
[
[blablaaa.zip](https://github.com/microsoft/onnxruntime/files/4174948/blablaaa.zip)
](url)

**Comment by natank1** [comment]
Can you use the models or do I have to provide additional files ?

נשלח מה-iPhone שלי

**Comment by spandantiwari** [comment]
@natank1 - what version of PyTorch are you using for exporting your model?

**Comment by natank1** [comment]
1.1.0

**Comment by natank1** [comment]
To be more precise, I train in 1,2,0 and export to onnx in 1.1.0

**Comment by natank1** [comment]
Does it help?
I will really appreciate some help in this issue
