### ISSUE TITLE
ResNet-50 has unsupported operations with OpenVino

### ISSUE THREAD

**Issue by ggeor84** [microsoft/onnxruntime#2994]
**Describe the bug**
When attempting to run ResNet-50 with OpenVino as an Execution Provider, I get the following message:

2020-02-07 16:28:06.147212540 [W:onnxruntime:Default, openvino_execution_provider.cc:546 GetCapability] [OpenVINO-EP] Rejecting as graph has unsupported operations.Operation is not supported by OpenVINO

Instead it reverts back to CPU

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.10
- Python version: 3.6.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: 10.2
- GPU model and memory: TITAN RTX

**To Reproduce**
Describe steps/code to reproduce the behavior:
Model was downloaded from mlperf, https://github.com/mlperf/inference/tree/master/v0.5/classification_and_detection
https://zenodo.org/record/2592612/files/resnet50_v1.onnx

I am running their tool to time the model

**Expected behavior**
I am expecting ResNet-50 to run using OpenVino

**Comment by jywu-msft** [comment]
@smkarlap @suryasidd  , is this expected?

**Comment by suryasidd** [comment]
There are some operations that are not supported by OpenVINO EP right now in this model like Argmax, ReduceMean and Squeeze. That's the reason it's falling back to the default CPU. However, OpenVINO EP can run the resnet50v1 model from onnx model zoo. https://github.com/onnx/models/tree/master/vision/classification/resnet

**Comment by ggeor84** [comment]
@suryasidd Thanks for the quick response. Are there any current plans to expand the op coverage to include these?

**Comment by suryasidd** [comment]
We are working on adding new ops in the next release coming soon. Will let you know once its out?
