### ISSUE TITLE
Is static quantization working?

### ISSUE THREAD

**Issue by deeplearningfromscratch** [microsoft/onnxruntime#2996]
**Describe the bug**
It seems static quantization is not working.
I tried static quantization with a very simple neural net: input -> conv.

![image](https://user-images.githubusercontent.com/36693407/74141641-a64b7a80-4c3a-11ea-8b38-59570e9da608.png)

```model = onnx.load('onnx_examples/test_model.onnx')
is_static = True
quantized_model = quantize(model, quantization_mode=QuantizationMode.IntegerOps,
                           per_channel=False,
                           static=is_static,
                           quantization_params={'input.1:0': [np.uint8(0), np.float32(0.05)]},
                           asymmetric_input_types=False)
```

I manually gave input quantization params(following sample com), but it outputs key map error.

`ValueError: Quantization parameters are not specified for param input.
In static mode quantization params for inputs and outputs of odes to be quantized are required.`

Can you assure me that static quantization is not implemented yet?
Or, if it is working, can you provide a valid onnx model or any instructions for me?

Thanks.

**Comment by yufenglee** [comment]
@deeplearningfromscratch the input of conv is 'input' instead of 'input.1:0', from your description. Please try setting "quantization_params={**'input'**: [np.uint8(0), np.float32(0.05)]},".
