### ISSUE TITLE
Proto field is not repeating, cannot start list.

### ISSUE THREAD

**Issue by gargayush792** [microsoft/onnxruntime#2997]
**Describe the bug**
ONNX runtime server gives error saying 
```
{
    "error_code": 400,
    "error_message": "inputs[1].value: Proto field is not repeating, cannot start list."
}
```

**To Reproduce**
Created Sklearn pipeline using LightGBM. Pipeline inference is working fine on local python onnx runtime. Inference from the same pipeline on the server fails.

The below code for creating pipeline and inference gives correct output for probability values. - 

```
clf = Pipeline(steps=[('preprocessor', preprocessor),
                      ('train', LGBMClassifier(num_leaves = 31, objective ='binary', max_depth = 6, n_estimators = 200))])

clf.fit(X_train, y_train)

update_registered_converter(LGBMClassifier, 'LightGbmLGBMClassifier',
                            calculate_linear_classifier_output_shapes,
                            convert_lightgbm, options={'nocl': [True, False], 'zipmap': [True, False]})

model_onnx = convert_sklearn(clf, 'pipeline', [('input1', StringTensorType(shape=[None, 8])),('input2', FloatTensorType(shape=[None, 19]))])

pred_onx = sess.run(None, {"input1": numpy.array([['string1', 'string2', 'string3', 'string4', 'string5', 'string6', 'string7', 'string8']], dtype = numpy.object), 
                           "input2": numpy.array([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]], dtype=numpy.float32)
                          }
                   )
```
However when sending a HTTP request to the runtime server, it gives the above mentioned error. Request format - 

```
{
  "inputs": {
    "input1": {
      "dims": [
        "1",
        "8"
      ],
      "dataType": 8,
      "rawData": [['string1', 'string2', 'string3', 'string4', 'string5', 'string6', 'string7', 'string8']]
    },
    "input2": {
      "dims": [
        "1",
        "19"
      ],
      "dataType": 1,
      "rawData": [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
    }
  }
}
```

**Comment by csteegz** [comment]
Hi, 
You're not using the rawData field correctly in that example. RawData expects a base64 encoded version of the raw data in the input. 
You should use float_data and string_data respectively for your inputs.

In addition, the input fields expect 'flattened' versions of the tensor.

We should probably improve the examples of using the JSON API.

**Comment by gargayush792** [comment]
> Hi,
> You're not using the rawData field correctly in that example. RawData expects a base64 encoded version of the raw data in the input.
> You should use float_data and string_data respectively for your inputs.
> 
> In addition, the input fields expect 'flattened' versions of the tensor.
> 
> We should probably improve the examples of using the JSON API.

Tried doing this but now it gives me a different error - 
```
{
  "inputs": {
    "input1": {
      "dims": [
        "1",
        "8"
      ],
      "dataType": 8,
      "string_data": ['string1', 'string2', 'string3', 'string4', 'string5', 'string6', 'string7', 'string8']
    },
    "input2": {
      "dims": [
        "1",
        "19"
      ],
      "dataType": 1,
      "float_data": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    }
  }
 }
```

Error:

```
{
    "error_code": 400,
    "error_message": "inputs[0].value.string_data[7]: invalid value \"local\" for type TYPE_BYTES"
}
```

**Comment by gargayush792** [comment]
Got it working. Encoding the strings to Byte worked. Is there a way I can pass the Strings as is?

**Comment by csteegz** [comment]
The JSON handling is in https://github.com/microsoft/onnxruntime/blob/master/server/http/json_handling.cc
and is using the protobuf json handler (https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.util.json_util)

It's possible there's some options that could be changed in the server to make that work - I'm not super familiar with the protobuf parser's options.
