### ISSUE TITLE
Cannot build onnxruntime with python 3.8

### ISSUE THREAD

**Issue by xadupre** [microsoft/onnxruntime#2998]
**Describe the bug**
I compile onnxruntime for python 3.7 and python 3.8 on the same machine (linux debian), 3.7 works, 3.8 fails (both CPU)

```
[…]
[ 98%] Building CXX object CMakeFiles/onnxruntime_pybind11_state.dir/var/lib/jenkins/workspace/_automation/_automation_FORK_onnxruntime-jenkins_38_std/onnxruntime/onnxruntime/python/onnxruntime_pybind_state.cc.o
Linking CXX shared module onnxruntime_pybind11_state.so
/usr/bin/ld: /usr/local/lib/libpython3.8.a(object.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
```

**System information**
- OS Platform and Distribution, Debian GNU/Linux 9.6 (stretch)
- ONNX Runtime installed from source (master branch)
- Python version: 3.8
- GCC/Compiler version: gcc version 6.3.0 20170516)

**To Reproduce**
Build onnxruntime with option --build_wheel

**Comment by snnn** [comment]
We have nightly build for python 3.8, so it should work. 
Please see [https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=111958](https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=111958)

**Comment by snnn** [comment]
Probably we should avoid linking to python libraries on Linux, in all the build configs.

**Comment by jywu-msft** [comment]
is this a python lib that you built yourself? why is it finding static lib?

**Comment by xadupre** [comment]
I saw the nightly build for python 3.8 is working fine. Yes I build python myself so maybe it is due to the way I build python.

**Comment by kcy1019** [comment]
It seems like you've missed `--enable-shared` option building the python

**Comment by snnn** [comment]
Please try it with the latest master again.  It won't link to libpython3.8.a so you won't see the same error.

**Comment by snnn** [comment]
Hi @xadupre , could you please try it again?

**Comment by xadupre** [comment]
It works now. Unit tests are still failing because tensorflow is not available on python3.8 but the compilation works.

**Comment by snnn** [comment]
Thank you
