### ISSUE TITLE
Build Test "failed", "bidirectional simple weights no bias" test from GRUTest takes too much time

### ISSUE THREAD

**Issue by LexXia** [Microsoft/onnxruntime#300]
**Describe the bug**
I am building onnx runtime (master branch) in ubuntu 16.04 virtual machine. The build progress has finished, followed with test phases. However, the test phase stopped at GRUTest.BidirectionalDefaultActivationsSimpleWeightNoBiasTwoRows. I have waited for more than 4 hours in this step, so I think there is something wrong. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary): building
- ONNX Runtime version: master branch
- Python version: 3.7.1
- GCC/Compiler version (if compiling from source):  gcc 5.4.0
- CUDA/cuDNN version: -
- GPU model and memory: -

**To Reproduce**
Describe steps/code to reproduce the behavior:
git clone
./build.sh --config RelWithDebInfo --build\_wheel
or
./build.sh --build\_wheel

**Expected behavior**
Build and test successful

**Screenshots**
![image](https://user-images.githubusercontent.com/42466682/50885516-dff2f600-1428-11e9-8448-2a56f9490c40.png)

**Additional context**

**Comment by snnn** [comment]
How much memory does the VM have?

**Comment by faxu** [comment]
@LexXia Have you resolved this issue or do you still need help troubleshooting?

**Comment by faxu** [comment]
Marking the issue as closed. Please reopen if you still require assistance.
