### ISSUE TITLE
after using the BertOnnxModelTF.py to optimize the onnx bert model, only support batch_size==1? 

### ISSUE THREAD

**Issue by rigorosyang** [microsoft/onnxruntime#3004]
I use the BertOnnxModelTF to optimize the onnx bert model ,but running the inference occur below exception using batch_size > 1.

onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running SkipLayerNormalization node. Name:'SkipLayerNorm1' Status Message: skip is expected to have same shape as input

anyone can help me? Thanks in advance!

**Comment by tianleiwu** [comment]
@rigorosyang, could you share your model?

If your model is trained by Tensorflow Keras and exported by keras2onnx, we will have a new [PR 3014](https://github.com/microsoft/onnxruntime/pull/3014) which might help.

**Comment by faxu** [comment]
@rigorosyang Are you still experiencing this? If so, please share more info so we can help troubleshoot.
