### ISSUE TITLE
Onnxruntime build with TensorRT faillure on Jetson Nano.

### ISSUE THREAD

**Issue by MarcoCBA** [microsoft/onnxruntime#3007]
Im trying to build onnxruntime natively on a Jetson Nano with ARM64 architecture with TensorRT as an execution provider.
After reading the installation scripts and instructions, I ended up using the following one, combining a few things, which builds the lastest cmake first.
```
mkdir ./code
cd ./code
wget https://cmake.org/files/v3.16/cmake-3.16.0.tar.gz;
tar zxf cmake-3.16.0.tar.gz

cd ./cmake-3.16.0
./configure --system-curl
make
sudo make install

cd
git clone --recursive --branch v1.1.1 https://github.com/microsoft/onnxruntime.git
cd onnxruntime/

# Build lib with TensorRT for ARM64
./build.sh --config MinSizeRel --arm64 --update --build --cudnn_home /usr/lib/aarch64-linux-gnu --cuda_home /usr/local/cuda --use_tensorrt --tensorrt_home /usr/src/tensorrt
```

I do have CUDA and CudNN and TensorRT installed, as nvidia-jetpack apt package for jetson nano includes those three.
I have also met the requirements specified for TRT in particular:

**Install CUDA and cuDNN**
- The path to the CUDA installation must be provided via the CUDA_PATH environment variable, or the --cuda_home parameter. The CUDA path should contain bin, include and lib directories.
**Done:** Added symlink called "lib" pointing "lib64".

- The path to the CUDA bin directory must be added to the PATH environment variable so that nvcc is found.
**Done:** echo 'PATH="/usr/local/cuda/bin:$PATH"' >> .profile

- The path to the cuDNN installation (path to folder that contains libcudnn.so) must be provided via the cuDNN_PATH environment variable, or --cudnn_home parameter.
**Done:** Check the build command above.

**Install TensorRT**
- The path to TensorRT installation must be provided via the --tensorrt_home parameter.
**Done:** Check the build command above.

At 37% I got the following traceback:

```
[ 37%] Building CXX object CMakeFiles/onnxruntime_providers_tensorrt.dir/home/meli/onnxruntime/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc.o
In file included from /home/meli/onnxruntime/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc:13:0:
/home/meli/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.h: In constructor ‘onnxruntime::CPUExecutionProvider::CPUExecutionProvider(const onnxruntime::CPUExecutionProviderInfo&)’:
/home/meli/onnxruntime/onnxruntime/core/providers/cpu/cpu_execution_provider.h:28:65: error: unused parameter ‘info’ [-Werror=unused-parameter]
   explicit CPUExecutionProvider(const CPUExecutionProviderInfo& info)
                                                                 ^~~~
cc1plus: all warnings being treated as errors
CMakeFiles/onnxruntime_providers_tensorrt.dir/build.make:62: recipe for target 'CMakeFiles/onnxruntime_providers_tensorrt.dir/home/meli/onnxruntime/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_providers_tensorrt.dir/home/meli/onnxruntime/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc.o] Error 1
CMakeFiles/Makefile2:668: recipe for target 'CMakeFiles/onnxruntime_providers_tensorrt.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_providers_tensorrt.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/meli/onnxruntime/tools/ci_build/build.py", line 1043, in <module>
    sys.exit(main())
  File "/home/meli/onnxruntime/tools/ci_build/build.py", line 975, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "/home/meli/onnxruntime/tools/ci_build/build.py", line 415, in build_targets
    run_subprocess(cmd_args)
  File "/home/meli/onnxruntime/tools/ci_build/build.py", line 197, in run_subprocess
    completed_process = subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/meli/onnxruntime/build/Linux/MinSizeRel', '--config', 'MinSizeRel']' returned non-zero exit status 2.
```

Any ideas for debugging will be much apreciated.
Thanks in advance.
Marco

**Comment by jywu-msft** [comment]
don't use --arm64 option. that is for cross compile. 
for native build, follow https://github.com/microsoft/onnxruntime/issues/2684#issuecomment-568548387

**Comment by MarcoCBA** [comment]
Why then BUILD.md includes the --arm flag in the steps for building it natively?
I followed the instructions hossein1387 wrote.
The wheel builds with a LOT of warnings in the process (they are all from eigen).
I tried running inference with a mobilenet in onnx format, but the process gets killed everytime.
I used these versions (Jetpack 4.3):
# cmake 3.16.0
# CUDA 10.0.326
# TensorRT 6.0.1
# cuDNN 7.6.3
# onnxruntime v1.1.1

**Comment by jywu-msft** [comment]
> Why then BUILD.md includes the --arm flag in the steps for building it natively?
> I followed the instructions hossein1387 wrote.
> The wheel builds with a LOT of warnings in the process (they are all from eigen).
> I tried running inference with a mobilenet in onnx format, but the process gets killed everytime.
> I used these versions (Jetpack 4.3):
> 
> * cmake 3.16.0
> * CUDA 10.0.326
> * TensorRT 6.0.1
> * cuDNN 7.6.3
> * onnxruntime v1.1.1

re: --arm flag, that is a mistake. we will correct it.

re: process getting killed, I suspect if you run dmesg you'll see that the process is killed by OOM killer. 
TRT consumes a lot of memory.
Note the last step in @hossein1387 's instructions to free up more memory on the system.

"You can make a swap file to make sure you have enough RAM. You can disable GUI and desktop at boot time to free up space."

**Comment by MarcoCBA** [comment]
Indeed, thats what happens.
It already has no GUI and Desktop.
```
XXX@XXX-XXX:~/Desktop$ free -h
              total        used        free      shared  buff/cache   available
Mem:           3,9G        457M        3,4G        1,8M         71M        3,6G
Swap:          1,9G         80M        1,9G
```

**Comment by MarcoCBA** [comment]
Tried increasing swap up to 8G, and now the inference script hangs.
```
                     total        used        free      shared  buff/cache   available
Mem:           3,9G        3,8G         51M        1,4M         61M        2,0M
Swap:          8,0G        4,8G        3,2G
```
I guess jetson nano its not powerful enough.

**Comment by jywu-msft** [comment]
> Tried increasing swap up to 8G, and now the inference script hangs.
> 
> ```
>               total        used        free      shared  buff/cache   available
> Mem:           3,9G        3,8G         51M        1,4M         61M        2,0M
> Swap:          8,0G        4,8G        3,2G
> ```
> 
> I guess jetson nano its not powerful enough.

which mobilenet model? is it from the onnx model zoo?

in the meantime, can you try CUDA provider instead? the memory requirements will be less.
follow the same build instructions, but replace --use_tensorrt with --use_cuda 
and remove --tensorrt_home option

**Comment by MarcoCBA** [comment]
After some time loading the model, i ran some inferences with it on a (224x224), and got 30ms per frame ~33fps, which i find kind of slow comparing to NVIDIA benchmarks.
Is there any way to check which provider is being used?

**Comment by jywu-msft** [comment]
> After some time loading the model, i ran some inferences with it on a (224x224), and got 30ms per frame ~33fps, which i find kind of slow comparing to NVIDIA benchmarks.
> Is there any way to check which provider is being used?

if you turn on verbose logging, you will see some log messages pertaining to node placements.
e.g.
see [example](https://github.com/microsoft/onnxruntime/issues/2404#issuecomment-554276559)

re: Nvidia benchmarks, is it [this](https://developer.nvidia.com/embedded/jetson-nano-dl-inference-benchmarks) ?
I believe those benchmarks are using FP16 precision.
ORT + TRT EP is FP32 precision by default.
