### ISSUE TITLE
Problem building onnxruntime with OpenVino on Windows

### ISSUE THREAD

**Issue by SimonKoppers** [microsoft/onnxruntime#3032]
**Describe the bug**
Building with --use_openvino results in errors due to warnings as warning level is set to W4. If it is reduced to W3, building completes without errors, but has linking problems, which is why only 75% of all unittests pass.

building without --use_openvino works fine.

**Urgency**
not urgent

**System information**
- OS Platform and Distribution: Windows 10
- ONNX Runtime installed from (source or binary): github source
- ONNX Runtime version: 1.1.1
- Python version: 3.6.5; 3.7.6
- Visual Studio version (if applicable): VS2017 
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- CPU model: Intel i7 9700
- GPU model and memory:  Intel Movidius / Interal GPU
- CMake version: 3.16.4

**To Reproduce**
Describe steps/code to reproduce the behavior:
I've tried three different computers for now.
The last system I used was a fresh Win 10, with Visual Studio 2017, Python 3.6.5, openvino toolbox.
All OpenVino examples work well in the same cmd for CPU, GPU and Intel Movidus.

Steps:
1. run <openvino_install_dir>/deployment_tools/model_optimizer/install_prerequisites/install_prerequisites_onnx.bat
2. run <openvino_install_dir>/bin/setupvars.bat
3. git clone --recursive https://github.com/Microsoft/onnxruntime
4. run build.bat --config RelWithDebInfo --use_openvino CPU_FP32

**Expected behavior**

Runs normal till:

> WARNING: Target "onnxruntime_providers_openvino" requests linking to directory "XX/AppData/Local/Programs/Python/Python36/libs".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "onnxruntime_test_all" requests linking to directory "/AppData/Local/Programs/Python/Python36/libs".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "onnx_test_runner" requests linking to directory "XX/AppData/Local/Programs/Python/Python36/libs".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "onnxruntime_perf_test" requests linking to directory "XX/AppData/Local/Programs/Python/Python36/libs".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done

> CMake Warning:
  Manually-specified variables were not used by the project:
    onnxruntime_BUILD_WINML_TESTS
    onnxruntime_CUDA_HOME
    onnxruntime_PYBIND_EXPORT_OPSCHEMA
    onnxruntime_TENSORRT_HOME

[...]

> onnx_test_data_proto.vcxproj -> C:\onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\onnx_test_data_proto.lib
  Building Custom Rule C:/Program Files (x86)/IntelSWTools/openvino_2019.3.379/deployment_tools/inference_engine/src/extension/CMakeLists.txt
  simple_copy.cpp
  ext_argmax.cpp
  ext_base.cpp
  ext_broadcast.cpp
  ext_ctc_greedy.cpp
  ext_depth_to_space.cpp
  ext_detectionoutput.cpp
  ext_detectionoutput_onnx.cpp
  ext_fill.cpp
C:\Program Files (x86)\IntelSWTools\openvino_2019.3.379\deployment_tools\inference_engine\src\extension\ext_base.cpp(34): error C2220: warning treated as error - no object file generated. [C:\onnxruntime\build\Windows\RelWithDebInfo\ie_cpu_extension\ie_cpu_extension.vcxproj]

and this goes on for a long, long time.

**Additional context**
If the warning level is set to W3 (CMakeList.txt, line 528), everything builds fine. However, testing fails in 25% of all tests.

Furthermore, I tried to step through the onnxruntime_providers.cmake and saw that "PYTHON_LIB" is empty after "find_package(InferenceEngine 2.1 REQUIRED)" is run

I changed (onnxruntime_providers.cmake, line 333)
from
`find_package(InferenceEngine 2.1 REQUIRED)`
to 
`set(_PYTHON_LIB ${PYTHON_LIB})`
`  find_package(InferenceEngine 2.1 REQUIRED)`
`set(PYTHON_LIBRARIES ${_PYTHON_LIB})`
which fixed the CMake link warning from above. However, this also leads to a bad result.

I guess some openvino lib is missing, but I can't figure out what to do about that.. 
Did this problem occure to someone else, too? Or does anyone know, how to fix it?

**Comment by TerisGH** [comment]
I encountered the same issue.

**Comment by jywu-msft** [comment]
@suryasidd , @smkarlap FYI

**Comment by SimonKoppers** [comment]
after some testing, recompiling and investigating using the DependencyWalker, I could make it compile and run, by setting the warning level down to W3 and ignoring the failed test's.

In order to use the created shared lib, I had to copy my "python3.dll", my "python36.dll" and the "tbb.dll" in addition to the "tbbmalloc.dll" into my "onnxruntime/bin/" folder.

Furthermore, I had to copy the "inference_engine.dll" and the "plugins.xml" file from "openvino_2019.3.379\deployment_tools\inference_engine\bin\intel64\Release" into my working folder that contains my program.exe, which includes the onnxruntime folder.

Is there maybe a way to have only one onnxruntime.dll including all openvino dll's in addition to the python3.dll/python36.dll? 
Or at least have only one bin folder that contains all dll's that are required?

**Comment by ping28198** [comment]
open the file "ext_base.cpp" with notepad, and change the format to "utf-8 with bom" when save as a file. Done!

**Comment by SimonKoppers** [comment]
unfortunately, it didn'lt change anything.

`C:\Program Files (x86)\IntelSWTools\openvino_2019.3.379\deployment_tools\inference_engine\src\extension\ext_base.cpp(34): error C2220: warning treated as error - no object file generated.
C:\Program Files (x86)\IntelSWTools\openvino_2019.3.379\deployment_tools\inference_engine\src\extension\ext_base.cpp(34): warning C4100: "resp": The formal parameter is not referenced in the body of the function. The unreferenced parameter is ignored.`

the function that is compiled has the input argument resp, but doesn't use it. That's why the error gets thrown.. 

Any other suggestions?

**Comment by SimonKoppers** [comment]
Hello all,
I just compiled the latest version of onnxruntime with openvino 2020.2 without any problems. I don't know exactly what caused the problem, but it's gone now.
