### ISSUE TITLE
OpenVINO Execution Provider samples C++ and python

### ISSUE THREAD

**Issue by danielecazzari** [microsoft/onnxruntime#3036]
Hi,
there is any chance to include a sample application that shows how to score an ONNX file leveraging OpenVINO Execution Provider both in C++ and Python?

Thanks

Daniele

**Comment by faxu** [comment]
We have this reference implementation: https://github.com/Azure-Samples/onnxruntime-iot-edge/blob/master/README-ONNXRUNTIME-OpenVINO.md

Do you have some specific questions?

**Comment by danielecazzari** [comment]
Hi Faith,
Thanks for pointing me out to the reference implementation but this covers only the python portion of my question. I'm still not able to find a comprehensive C++ sample for OpenVINO and other execution providers. I just noticed some code snippets on TensorRT documentation.

Another thing that I noticed is that python runtime seems to be bound to a specific Execution Provider but I would like to be able to deploy a runtime with multiple Execution Provider to make easier to Inference on a different hardware solution. 
As an addition, I noticed that you have to build OpenVINO EP for a specific device/precision (e.g. GPU_FP16) and you can't select this at runtime as you could do with the OpenVINO framework.

With C++ API it seems possible to select a specific EP, but it is not clear how to build and distribute multiple EP together.

**Comment by shivSD** [comment]
@danielecazzari 

were you able to find any sample code for openvino in c++  ? please can you share link incase if you found something.
