### ISSUE TITLE
Source ZIPs/tarballs are missing submodules

### ISSUE THREAD

**Issue by mika-fischer** [microsoft/onnxruntime#3055]
The current source tarballs are pretty useless, since the code for all git submodules is missing.

For CI builds, and also for normal users, it would be very beneficial to have an archive of the source code, that can be used to actually build the software.

**Comment by snnn** [comment]
It's auto-generated by github, we can't change it.  ONNX has the similar issue.

**Comment by mika-fischer** [comment]
You're obviously already attaching assets to the github releases (the binaries). It's simply a matter of generating a tarball with the complete sources and attaching that as well. That the original github tarball is also there is not a big deal, but maybe it can even be prevented...

Maybe check how the mxnet guys are doing it, they also have a lot of submodules: https://github.com/apache/incubator-mxnet/releases

**Comment by snnn** [comment]
@faxu @yufenglee What do you think?

**Comment by mika-fischer** [comment]
Here's the process they use: https://cwiki.apache.org/confluence/display/MXNET/Release+Process#ReleaseProcess-Step1.10.Createartifactsforthereleaseandpushtothedistfolder

I don't know github enough to say how to attach assets to releases. But you're already doing that, so you probably know :-)

**Comment by faxu** [comment]
Suggest to the use the git archive command for history.
