### ISSUE TITLE
Could not reproduce the inference time results of tutorial "Inference-PyTorch-Bert-Model-for-High-Performance-in-ONNX-Runtime"

### ISSUE THREAD

**Issue by msobroza** [microsoft/onnxruntime#3063]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04.5 LTS xenial
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.1.1
- Python version: 3.7.1
- Pytorch version: 1.3.1
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: only CPU
- Processor: Intel(R) Xeon(R) Gold 6161 CPU @ 2.20GHz 16 cores

**To Reproduce**
Followed and executed exactly the same code as [this tutorial](https://github.com/onnx/tutorials/blob/master/tutorials/Inference-PyTorch-Bert-Model-for-High-Performance-in-ONNX-Runtime.ipynb)

**Expected behavior**
Faster inference time using the optimized onnx model version than Pytorch model on CPU runtime

**Screenshots**
**Graph of operations of BERT base onnx model obtained using netron framework**
![Graph of operations in BERT base onnx model](https://user-images.githubusercontent.com/15339805/75040106-59796680-54ba-11ea-8207-8a1d07f54be7.png)
**Graph of operations of optimized BERT onnx model obtained using netron framework**
![Graph of operations in Bert optimized onnx model](https://user-images.githubusercontent.com/15339805/75040239-98a7b780-54ba-11ea-9dac-9d0c9239502b.png)

**Describe the bug**
Inference time is faster using the pytorch BERT model than using the optimized onnx based model version.

``` # To enable model serialization and store the optimized graph to desired location.
sess_options.optimized_model_filepath = os.path.join(output_dir, "optimized_model.onnx")
session = rt.InferenceSession(output_model_path, sess_options)

# evaluate the model
start = time.time()
res = session.run(None, {
          'input_ids': inputs['input_ids'].cpu().numpy(),
          'input_mask': inputs['attention_mask'].cpu().numpy(),
          'segment_ids': inputs['token_type_ids'].cpu().numpy()
        })
end = time.time()
print("ONNX Runtime inference time: ", end - start)

ONNX Runtime inference time:  8.736282587051392

start = time.time()
outputs = model(**inputs)
end = time.time()
print("PyTorch Inference time = ", end - start)

print("***** Verifying correctness *****")
import numpy as np
for i in range(2):
    print('PyTorch and ORT matching numbers:', np.allclose(res[i], outputs[i].cpu().detach().numpy(), rtol=1e-04, atol=1e-05))

PyTorch Inference time =  0.13680338859558105
***** Verifying correctness *****
PyTorch and ORT matching numbers: True
PyTorch and ORT matching numbers: True ```

**Comment by msobroza** [comment]
Related to [this issue](https://github.com/microsoft/onnxruntime/issues/3076) (uses also Intel(R) Xeon(R) Gold architecture)

**Comment by tianleiwu** [comment]
@msobroza, 

The optimized graph is good.

I am working on update the notebook, please have a try:
https://github.com/tianleiwu/tutorials/blob/master/tutorials/Inference-PyTorch-Bert-Model-for-High-Performance-in-ONNX-Runtime.ipynb

Please also try the performance test tool at the bottom of notebook to see whether the number is aligned with the result in notebook.

**Comment by minderx** [comment]
@tianleiwu the link is dead.
