### ISSUE TITLE
Rel-1.1.1 C++ API unable to run Op Set 11 on GPU

### ISSUE THREAD

**Issue by CoderHam** [microsoft/onnxruntime#3067]
**Describe the bug**

I use the `tools/ci_build/build.py` script to build onnxruntime **rel-1.1.1** and use the C++ API to load and run a model that contains ops from Op Set 11. For some reason this runs _only on my CPU_ with a very small spike in volatile GPU memory.

When I use the python API for onnxruntime-gpu the model runs as expected for v1.1.1.
 
There must be a build issue that does not build GPU support for Op Set 11. 
 
**Urgency**
Unable to run BERT and other models with Op Set 11 on [TensorRT Inference Server](https://github.com/NVIDIA/tensorrt-inference-server).

**System information**
- Linux Ubuntu 18.04:
- ONNX Runtime built from source
- ONNX Runtime version: 1.1.1
- Python version: 3.6
- CUDA/cuDNN version: 10.0
- GPU model and memory: TITAN V 12GB

**To Reproduce**
Build using the following command:
```
ARG COMMON_BUILD_ARGS="--skip_submodule_sync --parallel --build_shared_lib --use_openmp"
RUN mkdir -p /workspace/build
RUN python3 /workspace/onnxruntime/tools/ci_build/build.py --build_dir /workspace/build \
            --config Release $COMMON_BUILD_ARGS \
            --use_cuda \
            --cuda_home /usr/local/cuda \
            --cudnn_home /usr/local/cudnn-$(echo $CUDNN_VERSION | cut -d. -f1-2)/cuda \
            --use_tensorrt \
            --tensorrt_home /usr/src/tensorrt \
            --use_openvino CPU_FP32 \
            --update \
            --build
```

Load and run any model with Op Set 11

**Expected behavior**
[This](https://github.com/microsoft/onnxruntime/blob/master/docs/Versioning.md
) shows that onnxruntime 1.1.0 onward should support Opset 11. 

**Additional context**
Experienced with BERT

**Comment by snnn** [comment]
Do you have such code in your application:
```C++
  OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0);
```

**Comment by snnn** [comment]
Due to limited resources available, we didn't implement all the opset11 ops on GPU.

**Comment by CoderHam** [comment]
Yes I do

> Do you have such code in your application:
> 
> ```c++
>   OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0);
> ```

**Comment by CoderHam** [comment]
It's odd that it would work with python and not C++. Is this intentional or expected behavior?
> Due to limited resources available, we didn't implement all the opset11 ops on GPU.

**Comment by snnn** [comment]
> It's odd that it would work with python and not C++. Is this intentional or expected behavior?

No, it shouldn't be the case.

**Comment by pranavsharma** [comment]
If you configure the log severity level to VERBOSE, you should be able to see in the logs the placement map (which nodes got assigned to which provider). That should give a hint.

**Comment by CoderHam** [comment]
On Python the model runs significantly faster and has very low CPU consumption (Mostly GPU). As explained earlier the slowdown is seen on the C++ side. 

I can try the same logging approach in C++ to see which layers get assigned to CPU as compared to the GPU in python.

**Comment by faxu** [comment]
@CoderHam any findings on this issue regarding the discrepancy?

**Comment by CoderHam** [comment]
@faxu Here are the logs: [log_py.txt](https://github.com/microsoft/onnxruntime/files/4252885/log_py.txt) and [log_c.txt](https://github.com/microsoft/onnxruntime/files/4252887/log_c.txt)

On using python only these 4 ops are loaded on CPU. While in C a large number of Gather() and Unsqueeze() are loaded on CPU as well. 
```
2020-02-25 16:34:58.611470538 [I:onnxruntime:Default, cuda_execution_provider.cc:1339 GetCapability] Force fallback to CPU execution provider for Op type: Gather node name: 
2020-02-25 16:34:58.611589162 [I:onnxruntime:Default, cuda_execution_provider.cc:1339 GetCapability] Force fallback to CPU execution provider for Op type: Cast node name: 
2020-02-25 16:34:58.611614429 [I:onnxruntime:Default, cuda_execution_provider.cc:1339 GetCapability] Force fallback to CPU execution provider for Op type: Range node name: 
2020-02-25 16:34:58.611633737 [I:onnxruntime:Default, cuda_execution_provider.cc:1339 GetCapability] Force fallback to CPU execution provider for Op type: Unsqueeze node name: 
2020-02-25 16:34:58.992312977 [V:onnxruntime:, inference_session.cc:647 TransformGraph]  Provider: [CPUExecutionProvider]: [Gather (), Cast (), Range (), Unsqueeze (), ]
```

Note: I used the above script mentioned in the issue description to build the Onnx that was used for preparing log_c.txt
However the python version (same i.e. 1.1.1) was installed using pip and not built from source.

**Comment by CoderHam** [comment]
@faxu @pranavsharma Could you have a look at the log and verify is this is indeed a bug in the build process?

**Comment by pranavsharma** [comment]
From the logs, it's clear that the python version runs a bunch of optimizations (fusions) while the C one doesn't. What optimization level did you set when using the C API? Try with ORT_ENABLE_ALL. (It should've been the default starting v1.1.1, but that's a different issue). Please post your C and Python programs here. Also, when you're building you don't need openvino and tensorrt if you just want to use CPU and CUDA execution providers.

**Comment by CoderHam** [comment]
Thanks @pranavsharma setting the optimization level to **ENABLE_ALL** worked. I was setting **DISABLE_ALL** earlier and wasn't aware that disabled some GPU ops and forced them to run on CPU. Closing this issue.

**Comment by CoderHam** [comment]
Can you help me understand the significance of 
ORT_DISABLE_ALL -> Disables all optimizations (**Does this disable some GPU ops?**)
ORT_ENABLE_BASIC -> Enables basic optimizations (**Which ops on also run on GPU if this is enabled?**) 
ORT_ENABLE_EXTENDED -> Enables basic and extended optimizations 
ORT_ENABLE_ALL -> Enables all available optimizations including layout optimizations

You mentioned ORT_ENABLE_ALL is default. Does this mean that a minimal onnxruntime built without TRT and openvino but _with_ CUDA should support this profile?
