### ISSUE TITLE
Using Java library with DNNL 

### ISSUE THREAD

**Issue by slevental** [microsoft/onnxruntime#3071]
**Describe the bug**
I've compiled java jar with options:
`./build.sh --use_dnnl --use_openmp  --build_java --parallel --config RelWithDebInfo`

At the end, I've used `onnxruntime4j-1.1.0-with-binaries.jar` in my java application; but after trying some of the benchmarks and analyzing model exec with profiler I've noticed that DNNL is not in the call stack and MLAS is used instead;

I've found an option:
```
var opts = new OrtSession.SessionOptions()
opts.addDnnl(true);
```

which gives me an error: 
```
ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: This binary was not compiled with DNNL support.
	at ai.onnxruntime.OrtSession$SessionOptions.addDnnl(Native Method)
```

Is this the way of turning DNNL in java env or I'm doing something wrong?

**Urgency**
Actually this blocks an integration of ONNX runtime into one of our production services;

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.1.0
- Python version: 3.7
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): clang Apple LLVM version 10.0.1 (clang-1001.0.46.4)
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**To Reproduce**
see above

**Comment by snnn** [comment]
It's a bug.

```
if (onnxruntime_USE_DNNL)
  target_compile_definitions(onnxruntime_pybind11_state PRIVATE USE_DNNL=1)
endif()
```

We need to have the similar thing on the jni project.

**Comment by tracysh** [comment]
@slevental As the developer on MLAS, I'm curious about the model architecture used here where DNNL is faster than the out of box experience with MLAS. Let me know if you'd be willing to share any info about the model to help improve MLAS.

**Comment by slevental** [comment]
@tracysh model that we are using is Seq2Seq with LSTM encoder/decoder; I'm not sure that DNNL is faster - I'm trying to conduct a comparison using java but it seems that DNNL doesn't work there; If you have any benchmarks on MLAS vs DNNL for LSTM-RNN - I would appreciate it; also interesting to hear what CPU optimizations are possible for these model architectures; I was thinking about quantization to INT8 for instance

**Comment by Craigacp** [comment]
@slevental if you checkout the branch referenced in my PR (#3082) you can build the Java package with DNNL support.

**Comment by slevental** [comment]
@snnn now when I'm doing the same build using the most recent master (as well as using the PR you had sent) I'm constantly getting an error on a linking stage:

```
Undefined symbols for architecture x86_64:
  "onnxruntime::CreateExecutionProviderFactory_Dnnl(int)", referenced from:
      onnxruntime::test::DefaultDnnlExecutionProvider(bool) in libonnxruntime_test_utils.a(default_providers.cc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [onnxruntime_test_all] Error 1
```

Not sure what's the reason. It seems that CI is working, but I'm curious if CI contains --build_java  with --use_dnnl

**Comment by slevental** [comment]
I've upgraded cmake and re-cloned everything; and the problem went away - not sure what was the reason; I had to do this first, before submitting a comment, sorry for bothering;

**Comment by snnn** [comment]
Thank you for confirming.

**Comment by EmergentOrder** [comment]
I'm also getting a link error:
```
java.lang.UnsatisfiedLinkError at InferenceTest.java:1295
```
when using both --build_java and --use_dnnl, building from master on Ubuntu 20.04 / gcc-9.
@Craigacp would you mind looking into it?

**Comment by Craigacp** [comment]
What library is the link error coming out of? And what does `ldd` output for the two so files that should be packaged into the jar?

**Comment by EmergentOrder** [comment]
Full error is: 
```
  <failure message="java.lang.UnsatisfiedLinkError: /tmp/onnxruntime-java4622990253883325212/libonnxruntime.so: /snap/core18/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/onnxruntime-java4622990253883325212/libonnxruntime.so)" type="java.lang.UnsatisfiedLinkError">java.lang.UnsatisfiedLinkError: /tmp/onnxruntime-java4622990253883325212/libonnxruntime.so: /snap/core18/current/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/onnxruntime-java4622990253883325212/libonnxruntime.so)
```

My glibc version is 2.31. Should be ok, no?

**Comment by EmergentOrder** [comment]
ldd output:
```
$ ldd libonnxruntime.so 
	linux-vdso.so.1 (0x00007ffc37f07000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5e75e8e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5e75e6b000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5e75c8a000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5e75b3b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5e75b20000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5e7592c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5e7687e000)
```
and
```
$ ldd libonnxruntime4j_jni.so 
	linux-vdso.so.1 (0x00007fff3aff9000)
	libonnxruntime.so.1.5.2 => /home/selvelrel/dev/onnxruntime/build/Linux/RelWithDebInfo/libonnxruntime.so.1.5.2 (0x00007f15ae204000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f15adffb000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f15adff5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f15adfd2000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f15addf1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f15adca0000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f15adc85000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f15aebe5000)
```

**Comment by Craigacp** [comment]
Why is ldd pulling things out of /lib/ and the libm failure is happening inside a snap? Do you have a custom library path (or is the onnx runtime being packaged inside a snap)?

I'll try to replicate this tomorrow.

**Comment by EmergentOrder** [comment]
ahh, I see. No need to try to replicate, thanks.
I'm not usually a gradle user, nor snap. The standard version in the Ubuntu repos didn't meet your recommended version, so I tried snapping it, thought it would be smart enough to jive with apt, guess not. Clearly there is a version conflict going on, I'll clean things up.

**Comment by Craigacp** [comment]
Ok. We can look into it if it turns out to be an issue somewhere in ORT.

**Comment by EmergentOrder** [comment]
build & test works now. Noticed the dnnl lib is still not packed in, but with some path magic I was able to test the DNNL provider, thanks.

**Comment by Craigacp** [comment]
Yeah, nobody checked the Java packaging when they broke DNNL out into a separate shared library. I only noticed that had happened yesterday when I started to dig into this. @faxu is there a way we can get the Java API added to the list of things that people check when they make shared library packaging changes? I noticed that Python and nuget got updated, but I didn't know about it and no-one in MS checked that the Java packaging would include the necessary extra shared library to make DNNL work.

**Comment by EmergentOrder** [comment]
@Craigacp just a heads up, tried this again now and the dnnl and dnnl EP shared libs (`libdnnl.so` and `libonnxruntime_providers_dnnl.so`) are still not getting packed in to the release jar. 
Also when I `gradle publishToMavenLocal` the (different) jar it publishes doesn't even contain `libonnxruntime.so` or `libonnxruntime4j_jni.so`.
Could you see that these get fixed, and if possible, please publish a working `_dnnl` variant to public maven repos (like the `_gpu` variant is currently)? Thanks!

**Comment by EmergentOrder** [comment]
@faxu an assist here would be much appreciated

**Comment by Craigacp** [comment]
I've not had chance to fix it yet. I started work on it last week along with a bunch of other provider changes but I'm not done yet.

The publishing pipeline doesn't work with publishToMavenLocal you need to use one of the other options. 

I'm not in control of what gets pushed to maven central, you'd have to ask @faxu or @yuslepukhin.

**Comment by Craigacp** [comment]
Looking into this more I think it might not be possible to fix on the Java side. I've opened #6553 to track fixing it.
