### ISSUE TITLE
Can not open the website in ONNX Tutorial page

### ISSUE THREAD

**Issue by littlecaiji** [microsoft/onnxruntime#3077]
Here is the website : https://microsoft.github.io/onnxruntime/auto_examples/plot_load_and_predict.html#sphx-glr-auto-examples-plot-load-and-predict-py

**Comment by faxu** [comment]
Where was that linked from?
Here is the correct url: https://microsoft.github.io/onnxruntime/python/auto_examples/plot_load_and_predict.html#sphx-glr-auto-examples-plot-load-and-predict-py

**Comment by littlecaiji** [comment]
Thanks for you answer!
The link is from :
https://github.com/onnx/tutorials

**Comment by faxu** [comment]
Thanks!

https://github.com/onnx/tutorials/pull/177
