### ISSUE TITLE
building ONNX fail with error "undefined"

### ISSUE THREAD

**Issue by hoaquocphan** [microsoft/onnxruntime#3087]
Hello All,

I would like to report the issue when building the ONNX application to run some models supported by ONNX. 

**Error**

>/data2/hoaphan/onnxruntime/sdk/sysroots/cortexa15hf-neon-poky-linux-gnueabi/usr/lib/libonnxruntime_providers.a(datetime_transformer.cc.o): In function `Microsoft::Featurizer::DateTimeFeaturizer::SystemToDPTimePoint(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> > > const&)':
/usr/src/debug/onnxruntime/1.0.0-r0/git/onnxruntime/core/automl/featurizers/src/FeaturizerPrep/Featurizers/DateTimeFeaturizer.h:72: undefined reference to `Microsoft::Featurizer::DateTimeFeaturizer::TimePoint::TimePoint(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> > > const&)'
collect2: error: ld returned 1 exit status
Makefile:7: recipe for target 'onnxruntime' failed
make: *** [onnxruntime] Error 1`

So if there are anyone known this issue, Please help me to fix it.
Thank

**Comment by jywu-msft** [comment]
can you provide more details?
How are you building onnxruntime? What build options? From which branch/commit?
from the above it looks like you're building on ARM and featurizers are enabled (which I don't think was tested on ARM)

**Comment by hoaquocphan** [comment]
Hi @jywu-msft 
Thanks for your reply.

I would like to provide more details.

I will explain more about my procedure.
+ I use onnxruntime with branch rel-1.0.0
+ I build SDK with Onnxruntime (the SDK is OK when build hello world app)
+ I use this SDK to build the .cpp file to run onnx models and the error appears as previous post.

full error log:

> arm-poky-linux-gnueabi-g++ -march=armv7ve -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a15 --sysroot=/data2/hoaphan/onnxruntime/sdk/sysroots/cortexa15hf-neon-poky-linux-gnueabi -std=c++14 onnxruntime_inference_example.cpp
-DONNX_ML
-I /data2/hoaphan/onnxruntime/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/onnxruntime/1.0.0-r0/git/onnxruntime/core/session
-I /data2/hoaphan/onnxruntime/build/tmp/work/cortexa15hf-neon-poky-linux-gnueabi/onnxruntime/1.0.0-r0/git/cmake/external/onnx
-L /data2/hoaphan/onnxruntime/sdk/sysroots/cortexa15hf-neon-poky-linux-gnueabi/usr/lib/onnx/
-L /data2/hoaphan/onnxruntime/sdk/sysroots/cortexa15hf-neon-poky-linux-gnueabi/usr/lib/external/protobuf/cmake/
-L /data2/hoaphan/onnxruntime/sdk/sysroots/cortexa15hf-neon-poky-linux-gnueabi/usr/lib/external/re2/
-I /data2/hoaphan/onnxruntime/build/tmp/sysroots-components/aarch64/stb/usr/include/
-I /data2/hoaphan/onnxruntime/tiny_yolo2/TinyYOLOv2Script/src/
-I /data2/hoaphan/onnxruntime/tiny_yolo2/TinyYOLOv2Script/add/
-lonnxruntime_session
-lonnxruntime_providers
-lonnxruntime_framework
-lonnxruntime_optimizer
-lonnxruntime_graph
-lonnxruntime_common
-lonnx_proto
-lprotobuf
-lre2
-lonnxruntime_util
-lonnxruntime_mlas
-lonnx
-ljpeg
-lpthread -O2 -fopenmp -ldl -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -o tiny_yolo_inference_sample
/data2/hoaphan/onnxruntime/sdk/sysroots/cortexa15hf-neon-poky-linux-gnueabi/usr/lib/libonnxruntime_providers.a(datetime_transformer.cc.o): In function Microsoft::Featurizer::DateTimeFeaturizer::SystemToDPTimePoint(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> > > const&)': /usr/src/debug/onnxruntime/1.0.0-r0/git/onnxruntime/core/automl/featurizers/src/FeaturizerPrep/Featurizers/DateTimeFeaturizer.h:72: undefined reference to Microsoft::Featurizer::DateTimeFeaturizer::TimePoint::TimePoint(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> > > const&)'
collect2: error: ld returned 1 exit status
Makefile:7: recipe for target 'onnxruntime' failed
make: *** [onnxruntime] Error 1

so, if there are any unclear point, please ask me.

**Comment by jywu-msft** [comment]
did you follow https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#cross-compiling-on-linux-without-docker 
to cross compile onnxruntime?

can you try to rebuild it? but this time,
change line 59 https://github.com/microsoft/onnxruntime/blob/b783805f957c88f97b2b4398e2ace138fbdf831b/cmake/CMakeLists.txt#L59
to OFF ?

**Comment by hoaquocphan** [comment]
Hi @jywu-msft 

I didn't use Cmake to compile onnxruntime as the guide. so can not try your method.
I compiled onnxruntime by yocto to create the SDK, 
Then using SDK to compile my source code (.cpp file)

**Comment by hoaquocphan** [comment]
Hi @jywu-msft  
I would like to add some information:

Using the SDK to build the hello.cpp successfully with below code:

> #include <assert.h>
> #include "onnxruntime_c_api.h"
> #include <stdlib.h>
> #include <stdio.h>
> #include <vector>
> #include <map>
> #include <fstream>
> #define STB_IMAGE_IMPLEMENTATION
> #include "stb_image.h"
> #include <stdio.h>
> int main() {
>     printf("Hello, world!\n");
>     return 0;
> }

but when I insert below line to code, it will lead to the error in above post.
> const OrtApi* g_ort = OrtGetApiBase()->GetApi(ORT_API_VERSION);

**Comment by jywu-msft** [comment]
i think the issue is datetime_transformer.cc.o has a dependency on libautoml_featurizers.a which it doesn't look like you built. see: https://github.com/microsoft/onnxruntime/blob/v1.0.0/cmake/onnxruntime_automl_featurizers.cmake#L13

but for your purposes (tinyyolov2) you don't need featurizers at all.
so you shouldn't build datetime_transformer.cc etc. 

in other words,
when building libonnxruntime_providers.a  , make sure you don't include any source files from 
https://github.com/microsoft/onnxruntime/tree/v1.0.0/onnxruntime/automl_ops

**Comment by hoaquocphan** [comment]
Hi @jywu-msft 

Thank you very much for your support.
As your comment, I just found that my Makefile lack of  libautoml_featurizers.a
after add line **-lautoml_featurizers** to Makefile, the compiling was built successfully.

so Thank again for your support.  You are so handsome!

**Comment by hoaquocphan** [comment]
Hi @jywu-msft 

I re-build the onnxruntime on linux Ubuntu and enable the libautoml_featurizers.a  as below.
option(onnxruntime_USE_AUTOML "Build AutoML support" ON)

But I cannot see this lib on the build output.
Could you help me this issue?
Thanks

**Comment by hoaquocphan** [comment]
Hi @jywu-msft 
I clone the onnxruntime v1.4.0, after build it, it does not have automl_featurizers library? and it does not have in CMakeList.txt file
so how to build automl_featurizers library in onnxruntime v1.4.0?
if onnxruntime v1.4.0 does not support  automl_featurizers library, please confirm with me.
Thanks.

**Comment by jywu-msft** [comment]
sorry i missed this. this issue was already closed. in the future, please file new issues instead of commenting on closed ones.
i think automl_featurizers was renamed to featurizers.
see https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L59

**Comment by hoaquocphan** [comment]
Hi @jywu-msft 
OK, thanks for your reply
