### ISSUE TITLE
Inconsistency of ONNX proto

### ISSUE THREAD

**Issue by xkszltl** [Microsoft/onnxruntime#309]
**Describe the bug**

https://github.com/Microsoft/onnxruntime/blob/dc8b37f4c491872f75d4fe1963525f98fdb9974b/onnxruntime/core/protobuf/onnx-ml.proto#L524-L563

This part of code shadows the missing `#include <onnx/onnx-operators_pb.h>`.
When a library links to both official onnx and ort, we get compile errors like "OperatorStatus is not a member of onnx".

Maybe add `onnx-operators_pb.h` here will help?
https://github.com/Microsoft/onnxruntime/blob/b7cc611563cfd1bafdff14e38fb50ec9c48c3d68/include/onnxruntime/core/graph/onnx_protobuf.h#L29

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master
- Python version: 3.7.2
- GCC/Compiler version (if compiling from source): VS 2017 15.9

**Comment by snnn** [comment]
It's not an issue.

**Comment by snnn** [comment]
Please use our C API and the dynamic lib(onnxruntime.dll).  You won't see any c++ code(including onnx, protobuf) in the C API. Therefore, there won't be any conflict or inconsistency.

**Comment by xkszltl** [comment]
This issue is reported by someone who's implementing custom ops.

**Comment by snnn** [comment]
Custom ops must statically link to onnxruntime, and they must use the C++ API, not C API. And they must the onnx header files generated from onnxruntime, not the upstream one. For all the third party dependencies(e.g.protobuf), it must use exact the version as it in onnxruntime.
