### ISSUE TITLE
2020 year topK still not support?

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#3092]
```
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node TopK_1435:TopK(11)

```

this is a really common used op in onnx...

**Comment by faxu** [comment]
See https://github.com/microsoft/onnxruntime/issues/2849

Is this the same model you shared before? What is the type?

**Comment by pranavsharma** [comment]
@jinfagang please provide the model file to be able to do any meaningful investigation. Thanks!

**Comment by jinfagang** [comment]
Of course. what I wanna convert (actually wanna simplify a model using onnx-simplify), it's a onnx model exported from CenterMask.

the model actually generated but with TopK (it may have bool value) inside it make it unable to check pass in onnxruntime. Not sure it's type issue or not.

I paste the model download link here hope you guys take a quick look at it:

链接: https://pan.baidu.com/s/1cwtyIMyvXqeVOW65PMigbw 提取码: 5ehq

**Comment by pranavsharma** [comment]
Sorry, the link takes me to a page which is not in the English language. Can you upload the model here?

**Comment by jinfagang** [comment]
Sorry, how about this one: https://letsupload.co/P91b/centermask_bn.onnx

**Comment by pranavsharma** [comment]
What version of onnxruntime are you using? Works for me in the master branch. FYI: We'll be releasing 1.2.0 soon (next 1-2 weeks).

**Comment by jinfagang** [comment]
can you try using onnx-simplifier simplify it? (onnx-simplifier will run onnxruntime check in model first)
Also I think I am using the lastest one from pip

**Comment by pranavsharma** [comment]
Support for type int64 in topk was added only [after 1.1.2 release](https://github.com/microsoft/onnxruntime/compare/rel-1.1.2...rel-1.2.0). Please try the 1.2.0 release once it's available. Please reopen if it still doesn't work. Thanks!

**Comment by jinfagang** [comment]
I doesn't found 1.2.0 on pip, when will it release on pypi?

**Comment by pranavsharma** [comment]
Should be available in a week. You can always build from the source if it’s urgent.

**Comment by yangshao** [comment]
> Should be available in a week. You can always build from the source if it’s urgent.

Hi, I'm using the 1.2.0, but still get the error: 
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(int64)' of input parameter (21) of operator (TopK) in node () is invalid.

**Comment by kudo19021997** [comment]
Hi, i'am u sing 1.4.0 but i still get error:
[ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(int64)' of input parameter (656) of operator (TopK) in node (TopK_335) is invalid.
