### ISSUE TITLE
undefined reference to `OrtGetApiBase' collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by jorditg** [microsoft/onnxruntime#3095]
**Describe the bug**
Trying to compile squeezenet derived C++ inference sample with onnxruntime 1.1.2 I get undefined reference to `OrtGetApiBase'

**Urgency**
none

**System information**
- Linux Ubuntu 18.04
- ONNX Runtime installed from binary
- ONNX Runtime version: 1.1.2

**To Reproduce**
Code:
```cpp
// Copyright(c) Microsoft Corporation.All rights reserved.
// Licensed under the MIT License.
//

#include <iostream>
#include <assert.h>
#include <vector>
#include <onnxruntime_cxx_api.h>

int main(int argc, char* argv[]) {
  std::cout << "Begin main" << std::endl;

  //*************************************************************************
  // initialize  enviroment...one enviroment per process
  // enviroment maintains thread pools and other state info
  Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");

  std::cout << "Environment created" << std::endl;

  // initialize session options if needed
  Ort::SessionOptions session_options;
  session_options.SetIntraOpNumThreads(1);

  // If onnxruntime.dll is built with CUDA enabled, we can uncomment out this line to use CUDA for this
  // session (we also need to include cuda_provider_factory.h above which defines it)
  // #include "cuda_provider_factory.h"
  // OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 1);

  // Sets graph optimization level
  // Available levels are
  // ORT_DISABLE_ALL -> To disable all optimizations
  // ORT_ENABLE_BASIC -> To enable basic optimizations (Such as redundant node removals)
  // ORT_ENABLE_EXTENDED -> To enable extended optimizations (Includes level 1 + more complex optimizations like node fusions)
  // ORT_ENABLE_ALL -> To Enable All possible opitmizations
  session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);

  //*************************************************************************
  // create session and load model into memory
  // using squeezenet version 1.3
  // URL = https://github.com/onnx/models/tree/master/squeezenet
#ifdef _WIN32
  const wchar_t* model_path = L"squeezenet.onnx";
#else
  const char* model_path = "../model_0/model0.onnx";
#endif

  printf("Using Onnxruntime C++ API\n");
  Ort::Session session(env, model_path, session_options);

  //*************************************************************************
  // print model input layer (node names, types, shape etc.)
  Ort::AllocatorWithDefaultOptions allocator;

  // print number of model input nodes
  size_t num_input_nodes = session.GetInputCount();
  std::vector<const char*> input_node_names(num_input_nodes);
  std::vector<int64_t> input_node_dims;  // simplify... this model has only 1 input node {1, 3, 224, 224}.
                                         // Otherwise need vector<vector<>>

  printf("Number of inputs = %zu\n", num_input_nodes);

  // iterate over all input nodes
  for (int i = 0; i < num_input_nodes; i++) {
    // print input node names
    char* input_name = session.GetInputName(i, allocator);
    printf("Input %d : name=%s\n", i, input_name);
    input_node_names[i] = input_name;

    // print input node types
    Ort::TypeInfo type_info = session.GetInputTypeInfo(i);
    auto tensor_info = type_info.GetTensorTypeAndShapeInfo();

    ONNXTensorElementDataType type = tensor_info.GetElementType();
    printf("Input %d : type=%d\n", i, type);

    // print input shapes/dims
    input_node_dims = tensor_info.GetShape();
    printf("Input %d : num_dims=%zu\n", i, input_node_dims.size());
    for (int j = 0; j < input_node_dims.size(); j++)
      printf("Input %d : dim %d=%jd\n", i, j, input_node_dims[j]);
  }

  // Results should be...
  // Number of inputs = 1
  // Input 0 : name = data_0
  // Input 0 : type = 1
  // Input 0 : num_dims = 4
  // Input 0 : dim 0 = 1
  // Input 0 : dim 1 = 3
  // Input 0 : dim 2 = 224
  // Input 0 : dim 3 = 224

  //*************************************************************************
  // Similar operations to get output node information.
  // Use OrtSessionGetOutputCount(), OrtSessionGetOutputName()
  // OrtSessionGetOutputTypeInfo() as shown above.

  //*************************************************************************
  // Score the model using sample data, and inspect values

  size_t input_tensor_size = 224 * 224 * 3;  // simplify ... using known dim values to calculate size
                                             // use OrtGetTensorShapeElementCount() to get official size!

  std::vector<float> input_tensor_values(input_tensor_size);
  std::vector<const char*> output_node_names = {"output"};

  // initialize input data with values in [0.0, 1.0]
  for (unsigned int i = 0; i < input_tensor_size; i++)
    input_tensor_values[i] = (float)i / (input_tensor_size + 1);

  // create input tensor object from data values
  auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
  Ort::Value input_tensor = Ort::Value::CreateTensor<float>(memory_info, input_tensor_values.data(), input_tensor_size, input_node_dims.data(), 4);
  assert(input_tensor.IsTensor());

  // score model & input tensor, get back output tensor
  auto output_tensors = session.Run(Ort::RunOptions{nullptr}, input_node_names.data(), &input_tensor, 1, output_node_names.data(), 1);
  assert(output_tensors.size() == 1 && output_tensors.front().IsTensor());

  // Get pointer to output tensor float values
  float* floatarr = output_tensors.front().GetTensorMutableData<float>();
  assert(abs(floatarr[0] - 0.000045) < 1e-6);

  // score the model, and print scores for first 5 classes
  for (int i = 0; i < 9; i++)
    printf("Score for class [%d] =  %f\n", i, floatarr[i]);

  // Results should be as below...
  // Score for class[0] = 0.000045
  // Score for class[1] = 0.003846
  // Score for class[2] = 0.000125
  // Score for class[3] = 0.001180
  // Score for class[4] = 0.001317
  printf("Done!\n");
  return 0;
}
```
Libraries installed:
```console
$ sudo ldconfig -p | grep onnxsh: 0: getcwd() failed: No such file or directory
	libonnxruntime.so.1.1.2 (libc6,x86-64) => /usr/local/lib/libonnxruntime.so.1.1.2
	libonnxruntime.so (libc6,x86-64) => /usr/local/lib/libonnxruntime.so
```

Compilation:
```console
$ g++ -lonnxruntime isic_onnx_model_run.cpp
/tmp/ccg8qUqO.o: In function `__static_initialization_and_destruction_0(int, int)':
isic_onnx_model_run.cpp:(.text+0x954): undefined reference to `OrtGetApiBase'
collect2: error: ld returned 1 exit status
```

**Expected behavior**
Compilation without errors

**Comment by pranavsharma** [comment]
I can't reproduce the issue. See below.

![image](https://user-images.githubusercontent.com/2732907/75410296-4d354500-58d0-11ea-8b2a-2095cfa983d9.png)

**Comment by jywu-msft** [comment]
> I can't reproduce the issue. See below. (The exception in the screenshot is expected since I don't have the model file).
> 
> ![image](https://user-images.githubusercontent.com/2732907/75410296-4d354500-58d0-11ea-8b2a-2095cfa983d9.png)

link order matters.



> **Describe the bug**
> Trying to compile squeezenet derived C++ inference sample with onnxruntime 1.1.2 I get undefined reference to `OrtGetApiBase'
> 
> **Urgency**
> none
> 
> **System information**
> 
> * Linux Ubuntu 18.04
> * ONNX Runtime installed from binary
> * ONNX Runtime version: 1.1.2
> 
> **To Reproduce**
> Code:
> 
> ```c++
> // Copyright(c) Microsoft Corporation.All rights reserved.
> // Licensed under the MIT License.
> //
> 
> #include <iostream>
> #include <assert.h>
> #include <vector>
> #include <onnxruntime_cxx_api.h>
> 
> int main(int argc, char* argv[]) {
>   std::cout << "Begin main" << std::endl;
> 
>   //*************************************************************************
>   // initialize  enviroment...one enviroment per process
>   // enviroment maintains thread pools and other state info
>   Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");
> 
>   std::cout << "Environment created" << std::endl;
> 
>   // initialize session options if needed
>   Ort::SessionOptions session_options;
>   session_options.SetIntraOpNumThreads(1);
> 
>   // If onnxruntime.dll is built with CUDA enabled, we can uncomment out this line to use CUDA for this
>   // session (we also need to include cuda_provider_factory.h above which defines it)
>   // #include "cuda_provider_factory.h"
>   // OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 1);
> 
>   // Sets graph optimization level
>   // Available levels are
>   // ORT_DISABLE_ALL -> To disable all optimizations
>   // ORT_ENABLE_BASIC -> To enable basic optimizations (Such as redundant node removals)
>   // ORT_ENABLE_EXTENDED -> To enable extended optimizations (Includes level 1 + more complex optimizations like node fusions)
>   // ORT_ENABLE_ALL -> To Enable All possible opitmizations
>   session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
> 
>   //*************************************************************************
>   // create session and load model into memory
>   // using squeezenet version 1.3
>   // URL = https://github.com/onnx/models/tree/master/squeezenet
> #ifdef _WIN32
>   const wchar_t* model_path = L"squeezenet.onnx";
> #else
>   const char* model_path = "../model_0/model0.onnx";
> #endif
> 
>   printf("Using Onnxruntime C++ API\n");
>   Ort::Session session(env, model_path, session_options);
> 
>   //*************************************************************************
>   // print model input layer (node names, types, shape etc.)
>   Ort::AllocatorWithDefaultOptions allocator;
> 
>   // print number of model input nodes
>   size_t num_input_nodes = session.GetInputCount();
>   std::vector<const char*> input_node_names(num_input_nodes);
>   std::vector<int64_t> input_node_dims;  // simplify... this model has only 1 input node {1, 3, 224, 224}.
>                                          // Otherwise need vector<vector<>>
> 
>   printf("Number of inputs = %zu\n", num_input_nodes);
> 
>   // iterate over all input nodes
>   for (int i = 0; i < num_input_nodes; i++) {
>     // print input node names
>     char* input_name = session.GetInputName(i, allocator);
>     printf("Input %d : name=%s\n", i, input_name);
>     input_node_names[i] = input_name;
> 
>     // print input node types
>     Ort::TypeInfo type_info = session.GetInputTypeInfo(i);
>     auto tensor_info = type_info.GetTensorTypeAndShapeInfo();
> 
>     ONNXTensorElementDataType type = tensor_info.GetElementType();
>     printf("Input %d : type=%d\n", i, type);
> 
>     // print input shapes/dims
>     input_node_dims = tensor_info.GetShape();
>     printf("Input %d : num_dims=%zu\n", i, input_node_dims.size());
>     for (int j = 0; j < input_node_dims.size(); j++)
>       printf("Input %d : dim %d=%jd\n", i, j, input_node_dims[j]);
>   }
> 
>   // Results should be...
>   // Number of inputs = 1
>   // Input 0 : name = data_0
>   // Input 0 : type = 1
>   // Input 0 : num_dims = 4
>   // Input 0 : dim 0 = 1
>   // Input 0 : dim 1 = 3
>   // Input 0 : dim 2 = 224
>   // Input 0 : dim 3 = 224
> 
>   //*************************************************************************
>   // Similar operations to get output node information.
>   // Use OrtSessionGetOutputCount(), OrtSessionGetOutputName()
>   // OrtSessionGetOutputTypeInfo() as shown above.
> 
>   //*************************************************************************
>   // Score the model using sample data, and inspect values
> 
>   size_t input_tensor_size = 224 * 224 * 3;  // simplify ... using known dim values to calculate size
>                                              // use OrtGetTensorShapeElementCount() to get official size!
> 
>   std::vector<float> input_tensor_values(input_tensor_size);
>   std::vector<const char*> output_node_names = {"output"};
> 
>   // initialize input data with values in [0.0, 1.0]
>   for (unsigned int i = 0; i < input_tensor_size; i++)
>     input_tensor_values[i] = (float)i / (input_tensor_size + 1);
> 
>   // create input tensor object from data values
>   auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
>   Ort::Value input_tensor = Ort::Value::CreateTensor<float>(memory_info, input_tensor_values.data(), input_tensor_size, input_node_dims.data(), 4);
>   assert(input_tensor.IsTensor());
> 
>   // score model & input tensor, get back output tensor
>   auto output_tensors = session.Run(Ort::RunOptions{nullptr}, input_node_names.data(), &input_tensor, 1, output_node_names.data(), 1);
>   assert(output_tensors.size() == 1 && output_tensors.front().IsTensor());
> 
>   // Get pointer to output tensor float values
>   float* floatarr = output_tensors.front().GetTensorMutableData<float>();
>   assert(abs(floatarr[0] - 0.000045) < 1e-6);
> 
>   // score the model, and print scores for first 5 classes
>   for (int i = 0; i < 9; i++)
>     printf("Score for class [%d] =  %f\n", i, floatarr[i]);
> 
>   // Results should be as below...
>   // Score for class[0] = 0.000045
>   // Score for class[1] = 0.003846
>   // Score for class[2] = 0.000125
>   // Score for class[3] = 0.001180
>   // Score for class[4] = 0.001317
>   printf("Done!\n");
>   return 0;
> }
> ```
> 
> Libraries installed:
> 
> ```
> $ sudo ldconfig -p | grep onnxsh: 0: getcwd() failed: No such file or directory
> 	libonnxruntime.so.1.1.2 (libc6,x86-64) => /usr/local/lib/libonnxruntime.so.1.1.2
> 	libonnxruntime.so (libc6,x86-64) => /usr/local/lib/libonnxruntime.so
> ```
> 
> Compilation:
> 
> ```
> $ g++ -lonnxruntime isic_onnx_model_run.cpp
> /tmp/ccg8qUqO.o: In function `__static_initialization_and_destruction_0(int, int)':
> isic_onnx_model_run.cpp:(.text+0x954): undefined reference to `OrtGetApiBase'
> collect2: error: ld returned 1 exit status
> ```
> 
> **Expected behavior**
> Compilation without errors

link order matters. linker searches from left to right. you should have -lonnxruntime after isic_onnx_model_run.cpp because libonnxruntime will resolve the missing symbols needed by your program.
see the build command in @pranavsharma 's example above where he built your sample program successfully.

**Comment by jorditg** [comment]
Thank you @jywu-msft. Issue solved, just changing library order.

```console
$ g++ isic_onnx_model_run.cpp -lonnxruntime
$ ldd a.out
	linux-vdso.so.1 (0x00007ffe4c139000)
	libonnxruntime.so.1.1.2 => /usr/local/lib/libonnxruntime.so.1.1.2 (0x00007f486806e000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4867ce5000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4867acd000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f48676dc000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f48674d8000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f48672d0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4866f32000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f4866d03000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4866ae4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4868c12000)
```
library correctly linked and working. 
Sorry for the question. Not using g++ for a long time.
Thanks!

**Comment by ashwinjoseph95** [comment]
I had to create a symbolic link in the lib folder of onnxruntime so as to get rid off the error. 
Command:` ln -s libonnxruntime.so.1.10.0 libonnxruntime.so`

**Comment by jin1258804025** [comment]
将onnxruntime加入到target_link_libraries，这样可以解决为的问题

**Comment by iamstarlee** [comment]
> 将onnxruntime加入到target_link_libraries，这样可以解决我的问题

请问如何将onnxruntime加入到target_link_libraries，烦请赐教

**Comment by jin1258804025** [comment]
> > 将onnxruntime加入到target_link_libraries，这样可以解决我的问题
> 
> 请问如何将onnxruntime加入到target_link_libraries，烦请赐教

在CMake文件中有target_link_libraries配置，将onnxruntime添加到里面应该就可以，你试试！

**Comment by iamstarlee** [comment]
> > > 将onnxruntime加入到target_link_libraries，这样可以解决我的问题
> > 
> > 
> > 请问如何将onnxruntime加入到target_link_libraries，烦请赐教
> 
> 在CMake文件中有target_link_libraries配置，将onnxruntime添加到里面应该就可以，你试试！
好的，感谢！

**Comment by iamstarlee** [comment]
> > > 将onnxruntime加入到target_link_libraries，这样可以解决我的问题
> > 
> > 
> > 请问如何将onnxruntime加入到target_link_libraries，烦请赐教
> 
> 在CMake文件中有target_link_libraries配置，将onnxruntime添加到里面应该就可以，你试试！

您好！再打扰一下，为何我不论是添加onnxruntime的下载目录或者是包含‘libonnxruntime.so’的目录都还是不行呢？

**Comment by jin1258804025** [comment]
换一下onnxruntime的版本试试



发自我的iPhone


------------------ Original ------------------
From: Xinxin Li ***@***.***&gt;
Date: Fri,Jun 14,2024 4:41 PM
To: microsoft/onnxruntime ***@***.***&gt;
Cc: 我的AI世界 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [microsoft/onnxruntime] undefined reference to `OrtGetApiBase'collect2: error: ld returned 1 exit status (#3095)





    
将onnxruntime加入到target_link_libraries，这样可以解决我的问题
  
请问如何将onnxruntime加入到target_link_libraries，烦请赐教
  
在CMake文件中有target_link_libraries配置，将onnxruntime添加到里面应该就可以，你试试！
  
您好！再打扰一下，为何我不论是添加onnxruntime的下载目录或者是包含‘libonnxruntime.so’的目录都还是不行呢？

**Comment by iamstarlee** [comment]
> 换一下onnxruntime的版本试试 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Xinxin Li ***@***.***&gt; Date: Fri,Jun 14,2024 4:41 PM To: microsoft/onnxruntime ***@***.***&gt; Cc: 我的AI世界 ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [microsoft/onnxruntime] undefined reference to `OrtGetApiBase'collect2: error: ld returned 1 exit status (#3095) 将onnxruntime加入到target_link_libraries，这样可以解决我的问题 请问如何将onnxruntime加入到target_link_libraries，烦请赐教 在CMake文件中有target_link_libraries配置，将onnxruntime添加到里面应该就可以，你试试！ 您好！再打扰一下，为何我不论是添加onnxruntime的下载目录或者是包含‘libonnxruntime.so’的目录都还是不行呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

路径变量不小心赋值了两次
