### ISSUE TITLE
About the threads used

### ISSUE THREAD

**Issue by truemanlee** [microsoft/onnxruntime#3099]
Hi,
I am using the python api with cpu version to inference. But somethings confuse me. If I start only one process, the inference speed is very fast. However, if I start 2 or more processes, all processes inference very slowly, even stuck. I got the clue in the file "onnxruntime/core/util/thread_utils.cc", so I let inter_op_num_threads=2 and intra_op_num_threads=2, and export OMP_NUM_THREADS=1. 

From "onnxruntime/core/util/thread_utils.cc", it seems that the each onnxruntime process use at least 2 threads (when setting inter_op_num_threads=1, the programme use half of cores automatically), thus it causes the competition.

After setting inter_op_num_threads, intra_op_num_threads and OMP_NUM_THREADS, all processes could work well, at least they do not stuck. But the inference speed still become slower, compared with single process. So, I use the command "top -Hp sid" to check the process, I found that the process still opens multi threads. What should I do to make it possible to start multi processes without inference speed loss.

Thanks!
 
![TIM截图20200227180632](https://user-images.githubusercontent.com/10486524/75434041-e6756180-598b-11ea-8ed3-c4a9813addc7.png)

**Comment by snnn** [comment]
Threads can't be shared between processes. In your case, please set inter_op_num_threads=1 and intra_op_num_threads=1 and disable openmp to make onnxruntime run a single thread mode. You may control your CPU usage by controling the number of python processes active.

**Comment by truemanlee** [comment]
@snnn Thanks! So I need to build onnxruntime from source to disable the OpenMP. I am curios about the file "onnxruntime/core/util/thread_utils.cc" and the function
`return thread_pool_size == 1 ? nullptr : onnxruntime::make_unique<concurrency::ThreadPool>(name, thread_pool_size);`
What it actually acts when I disable the OpenMP and set inter_op_num_threads=1 and intra_op_num_threads=1? I mean, will it open multi threads?

**Comment by truemanlee** [comment]
I compiled the onnxruntime from source and disabled the OpenMP option. The quantity of threads that each process creates is equal to the quantity of cpu core. So it seems that onnxruntime does not limit the quantity of threads, which may cause the competition. The setting of inter_op_num_threads and intra_op_num_threads actually controls the quantity of activated threads.

**Comment by snnn** [comment]
If OpenMP is disabled and thread_pool_size == 1, as you can see in the code, onnxruntime shouldn't create extra threads, it must run in single thread mode, unless your model has RNN kernels.

**Comment by truemanlee** [comment]
Yes, I use the RNN kernels. So it means that there are no solutions to prevent the competition.

**Comment by truemanlee** [comment]
I rewrite the lstm code in tensorflow using while_loop and convert it to onxx format, it no longer creates multi threads. Thus there are no competitions between processes. I suggests that adding an option to disable the multi threads even using the RNN kernels. Thanks!

**Comment by snnn** [comment]
Sure, I'll fix it.

**Comment by cjermain** [comment]
@snnn, any update on the RNN kernels when trying to limit to 1 thread? Was this fixed in a recent release?

**Comment by snnn** [comment]
If you fetch the latest master, it should work. But the change isn't in the latest release. It will be in onnxruntime 1.3.

**Comment by cjermain** [comment]
Thanks @snnn! I've tested the latest nightly build and can confirm that it is resolved. 
```
pip install -i https://test.pypi.org/simple/ ort-nightly
```
Any word on when 1.3 is planned for release?

**Comment by snnn** [comment]
> Any word on when 1.3 is planned for release?

Sorry, currently it is not scheduled yet, at least we won't do it in Apr or May.

**Comment by cjermain** [comment]
Ok, thanks for the update.

**Comment by nietras** [comment]
> If OpenMP is disabled and thread_pool_size == 1, as you can see in the code, onnxruntime shouldn't create extra threads, it must run in single thread mode, unless your model has RNN kernels.

@snnn related to this, I saw that in the 1.7.0 release that:

> all ONNX Runtime CPU packages are now built without OpenMP

so does this mean that you can now simply set:
```
inter_op_num_threads=1
intra_op_num_threads=1 
```
and **ONNX runtime will not create it's own internal threads?**

We are having some serious performance degradation issues in an app that appears to be related to this, e.g. load increases non-linearly due to thread contention it seems. With very high CPI.

**Comment by snnn** [comment]
> ONNX runtime will not create it's own internal threads?

Yes, you are right. You can use your debugger to verify.

>  if you build ONNX runtime from source will it default to no OpenMP for CPU?

Yes.

**Comment by nietras** [comment]
@snnn thank you! 👍
