### ISSUE TITLE
c# api depends on cuda 10.0 but documentation lists 10.1 as requirement

### ISSUE THREAD

**Issue by erikbrntsn** [microsoft/onnxruntime#3100]
The README.md in the root of the project states:

"The default GPU build requires CUDA runtime libraries being installed on the system:
    Version: CUDA 10.1 and cuDNN 7.6.5
"

However the newest c# nuget package ~~(1.2)~~ (1.1.2) expects cuda 10.0.
Specifically SessionOptions.cs includes the following line
```
private static string[] cudaDelayLoadedLibs = { "cublas64_100.dll", "cudnn64_7.dll" };
```
cublas64_100.dll is contained in cuda 10.0 wheres cuda 10.1 and 10.2 contains cublas64_10.dll

CSharp_API.md does not mention requirements to cuda version.

Should the documentation be corrected or should the c# code be updated?

**Comment by jywu-msft** [comment]
latest nuget package is 1.1.2
1.2 release is coming soon and does require cuda 10.1
the release branch was just created from master yesterday. 
master branch documentation reflects the updated cuda requirement.

Thanks for noticing the issue in SessionOptions.cs ,if the cublas library was renamed for CUDA 10.1, 10.2, the code needs to get updated.
@yufenglee, @faxu FYI

**Comment by erikbrntsn** [comment]
Sorry, 1.2 was i typo on my side. I did mean 1.1.2
