### ISSUE TITLE
When using another package manager than NuGet (like paket), onnxruntime.dll is not copied to build directory

### ISSUE THREAD

**Issue by sacha-c** [microsoft/onnxruntime#3101]
**Describe the bug**
When using another package manager than VS (like paket), onnxruntime.dll is not copied to build directory. 
The consequence is an exception when using OnnxRuntime: [same as in this issue](https://github.com/Microsoft/onnxruntime/issues/116)
 `Unable to load DLL 'onnxruntime.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

**System information**
- OS Platform and Distribution: **Windows 10**
- ONNX Runtime installed from (source or binary): **Installed from paket using nuget as source**
- ONNX Runtime version: **1.1.2**
- Visual Studio version (if applicable): **VS 2019**

**To Reproduce**
Create a project in visual studio & install OnnxRuntime package using paket

**Expected behavior**
Should work the same as with NuGet package manager

**Additional context**
Paket doesn't generate a packages.config file to list installed packages. Instead it has a paket.references file.

However, in props.xml, one of the conditions to copy native dlls like onnxruntime.dll, is that there exists a file called `packages.config` (which doesn't exist when using paket):
line 25:
  `<ItemGroup Condition="Exists('packages.config') OR
                        Exists('$(MSBuildProjectName).packages.config') OR
                        Exists('packages.$(MSBuildProjectName).config')">`

**Comment by pranavsharma** [comment]
We don't test or support paket. Contributions are welcome.

**Comment by 6bee** [comment]
@pranavsharma Exact same issue with .NET SDK style projects any any other project using [`PackageReference`-style](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) project files!
Issue is in file `\build\netstandard1.1\Microsoft.ML.OnnxRuntime.Gpu.props`, I belief: 
```
  <ItemGroup Condition="Exists('packages.config') OR
                        Exists('$(MSBuildProjectName).packages.config') OR
                        Exists('packages.$(MSBuildProjectName).config')">
```
I'm not sure why you would need any condition here anyway.
It's definitely a bug in your nuget package.

**Comment by 6bee** [comment]
Not sure about your strategy here. Doesn't appear logical having a 'status:contributions-welcome' label on the issue while ignoring the according pull request #3527 or worse, marking the PR as 'status:wontfix' cause no one dares to review or take a decision.
At least you have bots in place making things obvious by letting contributors know you don't care.

**Comment by natke** [comment]
Dear @6bee, firstly please accept our apologies for this sequence of missteps in your engagement with this project. We are working on improving our customer responsiveness and open source processes, but we do not always get it right and we definitely dropped the ball on this one.

We're testing the changes in your PR now and will let you know when those have been validated.

We do appreciate your engagement with this onnxruntime and hope you will return with more contributions.

**Comment by natke** [comment]
Dear @6bee, this issue has been fixed and merged into master, so you should be unlocked now. Please let us know how you go.

**Comment by 6bee** [comment]
It's appreciated someone eventually took care of this.
