### ISSUE TITLE
Question: how to build/test opset 12 / ir_version v7

### ISSUE THREAD

**Issue by Gra55h0pper** [microsoft/onnxruntime#3107]
As I have a use-case for the to-be-released 'Inverse' operator (**opset version 12**, to be released in a few weeks from now), I built onnx and onnxruntime from source (using Python).
Upon loading my model, I get: 

```InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: Unknown model file format version.``` 

(Note that my model refers to: **ir_version: 7**).

How can I build onnxruntime (Python wheel) for this model file format version?
(I've currently built from branch *master*. Is that the one I should be using?)

**Comment by snnn** [comment]
Sorry, we haven't support it yet.

**Comment by Gra55h0pper** [comment]
@snnn, Ok, thanks. Are you by any chance aware of a branch where the soon-to-be-released opset 12 / ir_version 7 features are being tested?

**Comment by snnn** [comment]
ONNX 1.7 will be released in March, then onnxruntime team will start to implement the new ops.

**Comment by snnn** [comment]
Hi @Gra55h0pper ,

ONNX 1.7 and ONNX Runtime 1.4 have been released. They should have opset 12 now.  Please let me know if you more support. 

Thanks.
