### ISSUE TITLE
RUNTIME_EXCEPTION : Non-zero status code returned while running ReorderInput node.

### ISSUE THREAD

**Issue by qraleq** [microsoft/onnxruntime#3114]
**Describe the bug**
After successfully converting a tensorflow SSD object detection model with MobilenetV2 FPN backbone to .onnx format using tf2onnx optimizer, I get the following error when trying to run it using onnxruntime in Python:

> RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running ReorderInput node. Name:'ReorderInput_217' Status Message: /onnxruntime_src/onnxruntime/contrib_ops/cpu/nchwc_ops.cc:76 onnxruntime::common::Status onnxruntime::contrib::ReorderInput<T>::Compute(onnxruntime::OpKernelContext*) const [with T = float] (X_shape[1] % MlasNchwcGetBlockSize()) == 0 was false. 

Can you help me debug this issue? I have tried converting similar models straight from the tensorflow OD API model zoo, and this error doesn't occur (I froze the models using the same version of tensorflow 1.14 and using the same version of OD API).

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.1.12
- Python version: 3.6.9
- CUDA/cuDNN version: 10.1 
- GPU model and memory: GeForce 940MX / 4GB

**Expected behavior**
After successfully converting the model to .onnx without any errors, the onnxruntime throws the aforementioned error. I expected that onnxruntime will run the converted model without any problems.

**Comment by tracysh** [comment]
@qraleq Can you share the ONNX file to help debug this layout optimizer problem? Thanks!

Does the model run with the optimizations turned down? Try ORT_ENABLE_EXTENDED to disable the layout optimizer.

https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Graph_Optimizations.md

**Comment by qraleq** [comment]
@tracysh What's the best way to share the ONNX file with you? 

I did try ORT_ENABLE_EXTENDED, it results in a different error:

> Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running FusedConv node. Name:'fused Conv__1363_1' Status Message: Input channels C is not equal to kernel channels * group. C: 34 kernel channels: 1 group: 32

**Comment by tracysh** [comment]
@qraleq The new error message indicates a problem with the model. There is a depthwise convolution in the model where the input channel count is 34 but the filter count is only 32. The node is named Conv__1363. Can you check the original model?

**Comment by qraleq** [comment]
@tracysh I think that I located the problem, but I'm not sure how to fix it. As I mentioned we're using `ssd_mobilenet_v2_fpn` backbone. We have set `use_explicit_padding: true` in the pipeline.config and it's a prerequisite for our model to work as we want.

If I set `use_explicit_padding` to `false`, the model runs with onnx runtime, but the results aren't good. Can you help me resolve this issue?

**Comment by tracysh** [comment]
@qraleq Hmm, it's getting past my areas of expertise, maybe others can step in. If this is a model conversion issue, then maybe also try https://github.com/onnx/tensorflow-onnx.

**Comment by qraleq** [comment]
@tracysh Although there are no errors thrown while creating the model, you're right that this might be a conversion issue, but I'm not sure.

If anyone here knows how to resolve this, help is more than welcome!

**Comment by jignparm** [comment]
@qraleq, can you share a link to the original model file (frozen-model or saved_model format is fine)? 

The  SSD object detection model with MobilenetV2 FPN doesn't show up as one of  the zoo models : https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md

**Comment by qraleq** [comment]
@jignparm We've replaced the backbone to MobilenetV2_FPN instead of the MobilenetV1_FPN which is available in the model zoo. I will send you the frozen model a bit later, but you can reproduce this issue by adding `use_explicit_padding: true` to the config file of the model in the `feature_extractor` part and freezing the model again. This should result in the same behavior that we observe using our model.

**Comment by qraleq** [comment]
@jignparm Here is the link to the frozen pb model file: https://drive.google.com/file/d/1SU-pEb93eLQoRMxaK5z80jyjemZ0YuIn/view?usp=sharing.

**Comment by jignparm** [comment]
The TF loader (v 1.14) shows this error when loading the graph_def file. What version of TF are you using to load (or generate) this model? TF2.0 support in the TF2ONNX convertor is not fully active at this time.

>"NodeDef mentions attr 'incompatible_shape_error' not in Op<name=Equal;"

###Log
```
Traceback (most recent call last):
  File "D:\anaconda37\lib\site-packages\tensorflow\python\framework\importer.py", line 427, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'incompatible_shape_error' not in Op<name=Equal; signature=x:T, y:T -> z:bool; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_UINT8, ..., DT_QINT8, DT_QINT32, DT_STRING, DT_BOOL, DT_COMPLEX128]; is_commutative=true>; NodeDef: {{node FlexibleGridAnchorGenerator/assert_equal_1/Equal}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

```

**Comment by qraleq** [comment]
@jignparm I shared a model that is frozen using `export_inference_graph.py` from the OD API and using TF v1.14. Can you give it a try?

**Comment by jignparm** [comment]
Thanks for resharing the TF 1.14 version of the model

The Pad node just prior to the Conv node name= `FeatureExtractor/MobilenetV2/expanded_conv/depthwise/depthwise` seems to be altering the dimensions to (1,34, 258, 256) - we end up with 2 additional channels which are not needed. Most likely it's a issue in handling DepthwiseConv2DNative operator. 

I've created a issue against TF2ONNX to track this:  https://github.com/onnx/tensorflow-onnx/issues/824 t

```
-----------
Pad node: FeatureExtractor/MobilenetV2/expanded_conv/Pad
Input 0 Name: FeatureExtractor/MobilenetV2/Conv/Relu6:0 Shape: {1,32,256,256}
Input 1 Name: FeatureExtractor/MobilenetV2/fpn/top_down/Pad_1__2579:0 Shape: {8}
~~~ calling :FeatureExtractor/MobilenetV2/expanded_conv/Pad
-----------
Output 0 Name: FeatureExtractor/MobilenetV2/expanded_conv/Pad:0 Shape: {1,34,258,256}
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0


-----------
Conv node: FeatureExtractor/MobilenetV2/expanded_conv/depthwise/depthwise
Input 0 Name: FeatureExtractor/MobilenetV2/expanded_conv/Pad:0 Shape: {1,34,258,256}
Input 1 Name: ConvBnFusion_W_const_fold_opt__3771_2 Shape: {32,1,3,3}
Input 2 Name: ConvBnFusion_BN_B_FeatureExtractor/MobilenetV2/expanded_conv/depthwise/BatchNorm/beta:0_3 Shape: {32}
```

**Comment by qraleq** [comment]
Thank you very much for your effort! 
One off-topic question, how did you get the log that you attached?

**Comment by jignparm** [comment]
To generate the log, you'll need  to compile ORT from source, using this additional parameter `--cmake_extra_defines onnxruntime_DEBUG_NODE_INPUTS_OUTPUTS=10`.

Here is the full command line used.
```
build.bat  --enable_pybind --use_openmp --build_shared_lib  --config Debug --skip_submodule_sync --build_wheel --cmake_extra_defines onnxruntime_DEBUG_NODE_INPUTS_OUTPUTS=10
```

Additionally, you'll need to uninstall the OnnxRuntime  package in your Python environment, and use the one generated from the custom build above.
