### ISSUE TITLE
InferenceSession from I/O Stream

### ISSUE THREAD

**Issue by msteijaert** [microsoft/onnxruntime#3118]
I would like to be able to create an InferenceSession from a Python I/O Stream (`_io.BufferedReader` or  `_io.FileIO` as provided by the `os` module).

For example:
```
import onnxruntime
# example file downloaded from
# https://s3.amazonaws.com/onnx-model-zoo/mobilenet/mobilenetv2-1.0/mobilenetv2-1.0.onnx
with open("/home/user/mobilenetv2-1.0.onnx", mode = "rb",  buffering=0) as infile:
  res = onnxruntime.InferenceSession(infile)

```

However, this is not supported. As far as I can see, the only type of stream that is supported is the C++ `std::istream` and I am not aware of any way to create such a stream from python.

**Comment by msteijaert** [comment]
Update: I found out that `InferenceSession` accepts bytes, so the above can be achieved using:

```
import onnxruntime
# example file downloaded from
# https://s3.amazonaws.com/onnx-model-zoo/mobilenet/mobilenetv2-1.0/mobilenetv2-1.0.onnx
with open("/home/user/mobilenetv2-1.0.onnx", mode = "rb",  buffering=0) as infile:
  res = onnxruntime.InferenceSession(infile.read())
```

**Comment by leimao** [comment]
Here is a more comprehensive solution:
https://leimao.github.io/blog/ONNX-IO-Stream/
