### ISSUE TITLE
MissingMethodException during Predict

### ISSUE THREAD

**Issue by herrvonregen** [microsoft/onnxruntime#3119]
**Describe the bug**
I just trained a very basic CNN with Keras (https://keras.io/examples/mnist_cnn/) and converted it into an ONNX model to try out the loading and inference mechanisms. Reloading and inference of the ONNX model works perfectly fine. Than a adapted the "Object Detection - ASP.NET Core Web & WPF Desktop Sample" to fit for the keras model. Loading here works as aspected but during prediction I get an MissingMethodException and I have no clue why. I added the model and a testimage.

Has somebody encountered a similar problem? 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): Nuget
- ONNX Runtime version: 1.1.2
- Visual Studio version (if applicable): VS 2019

[TestModelImage.zip](https://github.com/microsoft/onnxruntime/files/4276284/TestModelImage.zip)

**Comment by hariharans29** [comment]
Hi @herrvonregen ,

Are you using the CPU Nuget (Microsoft.ML.OnnxRuntime) or the GPU nuget (Microsoft.ML.OnnxRuntime.Gpu) ?

**Comment by hariharans29** [comment]
Hi @herrvonregen ,

Any update on this ? Which .NET framework version is your server running ? Can you share your code ?  Please give us some more information to help repro.

Thanks!

**Comment by hariharans29** [comment]
Closing this for now. Please re-open with requested info.
