### ISSUE TITLE
"This is an invalid model" error related to float type and Equal operator

### ISSUE THREAD

**Issue by jbmaxwell** [microsoft/onnxruntime#3122]
I've converted the Huggingface DistilBert model to CoreML, via ONNX, and I noticed that the predictions between PyTorch and CoreML were different. Using onnxruntime to validate the ONNX converted model, I get this error: 
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(float)' of input parameter (115) of operator (Equal) in node () is invalid.
```
The model does pass `onnx.checker.check_model()`.

This is a model we're trying to put into production as quickly as possible, so the priority is fairly high (at least for us!).

Ubuntu 18.04
ONNX Runtime 1.1.2 (pip)
Python 3.7
VS Code 1.42.1 (remote debug from macOS)
GCC 7.4.0
Cuda 9.1.85 (upgraded to 10.1, but same problem)
RTX 2070 (8GB)

**Comment by snnn** [comment]
onnx.checker.check_model doesn't run shape and type inference. The error says: one of the input has wrong type.

**Comment by jbmaxwell** [comment]
Okay, good to know @snnn. Thanks.

**Comment by jbmaxwell** [comment]
Curious, @snnn, when I look at the GitHub docs for `Equal` it appears to accept floats. However, when I click the "?" in Netron, the documentation for the `Equal` node indicates only integer types. The latter would explain the error. Do you know how I might go about changing the type?

**Comment by tracysh** [comment]
What opset is the model using? Opset 11 added support for float and other types, but the older opset 7 version only supported integer types. The opset version is shown in the "imports" section of the model properties of Netron.

**Comment by jbmaxwell** [comment]
The info in Model Properties is: `ONNX v4, Pytorch 1.3, ai.onnx v9`.

**Comment by snnn** [comment]
So, your model asks for opset 9, not 11.

**Comment by jbmaxwell** [comment]
Yes, that seems pretty clear! ;-) 
How do I rectify the situation though? `pip install --upgrade onnx` indicates I'm up-to-date.... or is it a PyTorch upgrade?

**Comment by snnn** [comment]
It need be fixed in PyTorch side.

**Comment by faxu** [comment]
Can you try Pytorch 1.4? If resolved, please close this issue; if not, let us know and we can help look into PT export. CC @spandantiwari as fyi

**Comment by jbmaxwell** [comment]
Training in Pytorch 1.4 (cuda 10.1) and specifying `opset_version=11` in my conversion script allows the model to build and verify correctly under `onnxruntime`. However, the converted model reports Pytorch 1.3 (in Netron)... ?? Also, when using Opset v11, the resulting model contains a `Range` function, which fails on `onnx-coreml` conversion with: `NotImplementedError: Unsupported ONNX ops of type: Range`. Strange.

**Comment by hariharans29** [comment]
Do you know which onnx opset is supported by the latest onnx-coreml converter ? If I remember correctly, Range was introduced in ONNX in opset 11 (the latest) and probably the onnx-coreml converter just hasn’t caught up yet (going based on the error message). If so, this is a gap in the converter. Please close this issue if the latest exported ONNX model works as expected in onnxruntume. Thanks.
