### ISSUE TITLE
wrong dimensions from yolov3

### ISSUE THREAD

**Issue by hoaquocphan** [microsoft/onnxruntime#3127]
Hello All,

currently I import the yolov3.onnx model to onnx v1.1.0 but it have below issues:

there are 2 input, and the dimensions 2 and 3 of 2 inputs is always -1
input 1:
dim 2=-1
dim 3=-1
input 2:
dim 2=-1
dim 3=-1

when importing  yolov2.onnx model to onnx v1.1.0, the dimensions is always as below:
dim 2=416
dim 3=416

I don't know what is "-1" mean, and how to show correct dimensions.
so Please help me to detect the issue with my problem

Thanks

**Comment by hoaquocphan** [comment]
So could anyone please help me.

**Comment by hariharans29** [comment]
-1 corresponds to "not being tied to a specific value" (i.e.) in this case the input shape requirement is "dynamic" and "not fixed". 

From the model zoo models:

Yolo v3:

![image](https://user-images.githubusercontent.com/9969784/76015735-79ecec00-5ed0-11ea-838b-bd347f57b7bc.png)

Yolo v2:

![image](https://user-images.githubusercontent.com/9969784/76015875-b9b3d380-5ed0-11ea-8bbd-5ebc3d85dfa6.png)

-1 from ORT APIs would correspond to the dimension values specified with non-numeric values (i.e.) 
[dim_param](https://github.com/onnx/onnx/blob/4cd2538df044d7637492ec5635bf47a3057749e9/onnx/onnx.proto#L618). 

However, when a dimension value is -1, it doesn't mean that the model will accept any arbitrary shapes. There could be some ops in the model that implicitly impose some constraints. For example, the [Mask R-CNN model](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/mask-rcnn)
has dynamic input shapes :

![image](https://user-images.githubusercontent.com/9969784/76016642-11067380-5ed2-11ea-94d6-4fe08676347f.png)

But the model contributors impose a constraint that the height and width both need to be divisible by 32. "...then pad the image with zeros such that both height and width are divisible by 32" in the README. So it is important to check if the "dynamic shapes" have some constraints before running the model. 

Please re-open if you have further questions.

**Comment by hoaquocphan** [comment]
Dear @hariharans29 

Thanks you very much for your help, 
now I understand about this, but I'm not really understand the preprocessing step of yolov3, So could you explain more about it.
As I understanding, this step will resize the freestyle image to 416x416, If I cannot find function to resize the image in CPP, could I fix the image input to 416x416 and skip the preprocessing step?

**Comment by hariharans29** [comment]
1) OnnxRuntime doesn't support utility functions to resize an image to the specified dimensions. It expects a raw buffer containing data of the size prescribed by the model. You can check out OpenCV (C++) / Pillow (Python) or other image processing libraries that can resize raw images to the prescribed size.

2) https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3#input-to-model Please pay attention to all the details in the README of the model contributed to the model zoo. As such ORT does not have anything to do with the ONNX model zoo, it only helps run them. You will have to check with the individual model contributors for specific questions about the pre-trained and exported/converted ONNX model.

**Comment by hoaquocphan** [comment]
Hi @hariharans29

Thank you very much for your reply.
I just start the new AI task from last week, so there are many new thing with me
So I will investigate more by myself.

Thanks again.

**Comment by hoaquocphan** [comment]
Hi @ @hariharans29 

Could you help me this issue https://github.com/onnx/models/issues/268
I think this is from ORT, not from the model.

Thanks
