### ISSUE TITLE
cublas64_100.dll  got  exception after return from main

### ISSUE THREAD

**Issue by xinyu391** [microsoft/onnxruntime#3129]
**Describe the bug**
got exception after  main() return.

**Urgency**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.1.2
- Python version: not used
- Visual Studio version (if applicable): VS2019(cmake project)
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA10.0, cuDNN7.6.5.32
- GPU model and memory: MX150， 2GMem

**To Reproduce**
compile and run in X64_Debug mode.

**Expected behavior**
normally return .no exception.

**Screenshots**
![批注 2020-03-04 122521](https://user-images.githubusercontent.com/1401364/75845169-46985780-5e13-11ea-8399-c82f5c5e858b.png)

**Additional context**
```c++


#include <iostream>
#include "onnxruntime_cxx_api.h"
#ifdef GPU_CUDA
#include "cuda_provider_factory.h"
#endif

void test()
{
    static Ort::Env env_(ORT_LOGGING_LEVEL_ERROR, "ocrgt");
    Ort::SessionOptions session_options;
    session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
    session_options.SetExecutionMode(ExecutionMode::ORT_SEQUENTIAL); //ORT_PARALLEL  ORT_SEQUENTIAL
    auto status = OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0);
 
    std::wstring wpath = L"c:\\work\\ocr-gt\\resnet50v2.onnx";
    Ort::Session session(env_, wpath.c_str(), session_options);
    size_t in_count = session.GetInputCount();
    size_t out_count = session.GetOutputCount();
    std::cout << "ok tolaoad model"<< in_count<<","<<out_count<<std::endl;
}
int main(int argc, char* argv[]) {
    std::cout << "Hello "<<argv[0]<<std::endl;
    test();
    std::cout << "ok:结束" << std::endl;
    return 0;
}

```

**Comment by snnn** [comment]
It's a NULL pointer exception. Is your program multiple threaded or single threaded?

**Comment by snnn** [comment]
Could you please help us reproduce the error? We need more information to debug it.

**Comment by xinyu391** [comment]
**Describe the bug**
got exception after  main() return.

**Urgency**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.1.2
- Python version: not used
- Visual Studio version (if applicable): VS2019(cmake project)
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA10.0, cuDNN7.6.5.32
- GPU model and memory: MX150， 2GMem

**To Reproduce**
compile and run in X64_Debug mode.

**Expected behavior**
normally return .no exception.

**Screenshots**
![批注 2020-03-04 122521](https://user-images.githubusercontent.com/1401364/75845169-46985780-5e13-11ea-8399-c82f5c5e858b.png)


**Additional context**
```c++


#include <iostream>
#include "onnxruntime_cxx_api.h"
#ifdef GPU_CUDA
#include "cuda_provider_factory.h"
#endif

void test()
{
    static Ort::Env env_(ORT_LOGGING_LEVEL_ERROR, "ocrgt");
    Ort::SessionOptions session_options;
    session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
    session_options.SetExecutionMode(ExecutionMode::ORT_SEQUENTIAL); //ORT_PARALLEL  ORT_SEQUENTIAL
    auto status = OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0);
 
    std::wstring wpath = L"c:\\work\\ocr-gt\\resnet50v2.onnx";
    Ort::Session session(env_, wpath.c_str(), session_options);
    size_t in_count = session.GetInputCount();
    size_t out_count = session.GetOutputCount();
    std::cout << "ok tolaoad model"<< in_count<<","<<out_count<<std::endl;
}
int main(int argc, char* argv[]) {
    std::cout << "Hello "<<argv[0]<<std::endl;
    test();
    std::cout << "ok:结束" << std::endl;
    return 0;
}

```

**Comment by snnn** [comment]
Please do not put Ort::Env or Ort Session into a static variable. 
Please free/destroy any ort variables when the main function ends.

**Comment by xinyu391** [comment]
@snnn
ok remove static .
But how to free/destroy  ort variables?  use  release()?
this is my code, still get this error
```c++
void test()
{
    Ort::Env env_(ORT_LOGGING_LEVEL_ERROR, "ocrgt");
    Ort::SessionOptions session_options;
    session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
    session_options.SetExecutionMode(ExecutionMode::ORT_SEQUENTIAL); //ORT_PARALLEL  ORT_SEQUENTIAL
    auto status = OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0);

    std::wstring wpath = L"c:\\work\\ocr-gt\\resnet50v2.onnx";
    Ort::Session session(env_, wpath.c_str(), session_options);
    size_t in_count = session.GetInputCount();
    size_t out_count = session.GetOutputCount();
    std::cout << "ok tolaoad model" << in_count << "," << out_count << std::endl;
    session.release();
    session_options.release();
    env_.release();
}
```

**Comment by snnn** [comment]
If you're using pure C, then you have to call functions like ReleaseSession manually.
As you are using C++, the destructor of the objects will do the job for you.

Did removing 'static' solve the issue?

**Comment by xinyu391** [comment]
no, still got this error

**Comment by snnn** [comment]
I tried the code with the latest onnxruntime 1.2 binary(to be released), it works fine. 
Please make sure you have CUDA and CUDNN DLLs in your path. 
For onnxruntime 1.2, it requires CUDA Runtime 10.1.243, CUDNN 7.6.5.32 for CUDA 10.1.
You can get the new 1.2 binary from: 
https://dev.azure.com/onnxruntime/_apis/resources/Containers/4893695?itemPath=drop-onnxruntime-win-x64-gpu-1.2.0%2Fonnxruntime-win-x64-gpu-1.2.0.zip

The error is mostly because DLLs were missing, however, if that's the case, the error should be thrown before the main function returns. Please put onnxruntime.dll and onnxruntime.pdb in the same directory of your demo.exe, you'll be able to see a more detailed call stack when the error happens.

**Comment by snnn** [comment]
Sorry, it's a bug, we'll fix it.
