### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node ConvInteger(10)

### ISSUE THREAD

**Issue by ggeor84** [microsoft/onnxruntime#3130]
**Describe the bug**
I quantized an fp32 and used the flag asymmetric input types (dynamic quantization). I got the following error when I tried to run the model:
 onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node ConvInteger(10)

**Urgency**
Medium urgency

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): from source
- ONNX Runtime version: 1.1.0
- Python version: 3.6
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source):  7.4.0
- CUDA/cuDNN version: 10.2/
- GPU model and memory: TITAN RTX 24GB

**Comment by AlZuev** [comment]
I have the same problem. I created model with Conviteger, it looks like quntized model, created by ONNXRUNTIME,but inference doesn't run with error:
onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node ConvInteger(10)

**Comment by shairoz-deci** [comment]
Same here, create an 8bit quantization model following 
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/notebooks/Bert-GLUE_OnnxRuntime_quantization.ipynb
and got
`onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Conv_0_quant:ConvInteger(10)`
upon trying to run inference session.

**Comment by AlZuev** [comment]
I thought I have answer. You need weight and input, x_offset, w_offset in type uint8 (for int8 you will get this error)

**Comment by katirasole** [comment]
I have the same issues in Inference step. May I ask you  if you have find a solution to overcome the  problem. I really appreciate if anyone can help me. Thank you so much.

**Comment by ashu5644** [comment]
@AlZuev, I am having similar issue in my model. can you please elaborate and provide sample code of how did you resolved the issue ?

**Comment by katirasole** [comment]
> @AlZuev, I am having similar issue in my model. can you please elaborate and provide sample code of how did you resolved the issue ?

I solved issue by just changing QInt8 to QUInt8 in weight_type. 

def quantize_onnx_model(onnx_model_path, quantized_model_path):
    from onnxruntime.quantization import quantize_dynamic, QuantType
    import onnx
    onnx_opt_model = onnx.load(onnx_model_path)
    quantize_dynamic(onnx_model_path,
                     quantized_model_path,
                     weight_type=QuantType.QUInt8)    #chnage QInt8 to QUInt8

**Comment by MrRace** [comment]
> > @AlZuev, I am having similar issue in my model. can you please elaborate and provide sample code of how did you resolved the issue ?
> 
> I solved issue by just changing QInt8 to QUInt8 in weight_type.
> 
> def quantize_onnx_model(onnx_model_path, quantized_model_path): from onnxruntime.quantization import quantize_dynamic, QuantType import onnx onnx_opt_model = onnx.load(onnx_model_path) quantize_dynamic(onnx_model_path, quantized_model_path, weight_type=QuantType.QUInt8) #chnage QInt8 to QUInt8

@katirasole  However use `weight_type=QuantType.QUInt8` seems make model  infer slower? Have you test the performance for the `quantize_dynamic` model?

**Comment by wangyunxiaa** [comment]
> > > @AlZuev, I am having similar issue in my model. can you please elaborate and provide sample code of how did you resolved the issue ?
> > 
> > 
> > I solved issue by just changing QInt8 to QUInt8 in weight_type.
> > def quantize_onnx_model(onnx_model_path, quantized_model_path): from onnxruntime.quantization import quantize_dynamic, QuantType import onnx onnx_opt_model = onnx.load(onnx_model_path) quantize_dynamic(onnx_model_path, quantized_model_path, weight_type=QuantType.QUInt8) #chnage QInt8 to QUInt8
> 
> @katirasole However use `weight_type=QuantType.QUInt8` seems make model infer slower? Have you test the performance for the `quantize_dynamic` model?

I have also got the result, the float onnx model inference time is  53.57ms
however I quant all ops with,
```
prefix = ["MatMul", "Add", "Relu"]
linear_names = [v for v in names if v.split("_")[0] in prefix]

quantize_dynamic(onnx_model, onnx_model+".quantall", weight_type=QuantType.QUInt8)
quantize_dynamic(onnx_model, onnx_model+".int8.quant", weight_type=QuantType.QInt8, nodes_to_quantize=linear_names, extra_options={"MatMulConstBOnly":True})
quantize_dynamic(onnx_model, onnx_model+".uint8.quant", weight_type=QuantType.QUInt8, nodes_to_quantize=linear_names, extra_options={"MatMulConstBOnly":True})
```
 the inference time `.quantall` model is 94.91ms , `.uint8.quant` model is 40.31ms, but the `.int8.quant` is 37.87ms

it seems that quant with conv is slower, and unit8 quant is slower than int8

**Comment by yufenglee** [comment]
> > > > @AlZuev, I am having similar issue in my model. can you please elaborate and provide sample code of how did you resolved the issue ?
> > > 
> > > 
> > > I solved issue by just changing QInt8 to QUInt8 in weight_type.
> > > def quantize_onnx_model(onnx_model_path, quantized_model_path): from onnxruntime.quantization import quantize_dynamic, QuantType import onnx onnx_opt_model = onnx.load(onnx_model_path) quantize_dynamic(onnx_model_path, quantized_model_path, weight_type=QuantType.QUInt8) #chnage QInt8 to QUInt8
> > 
> > 
> > @katirasole However use `weight_type=QuantType.QUInt8` seems make model infer slower? Have you test the performance for the `quantize_dynamic` model?
> 
> I have also got the result, the float onnx model inference time is 53.57ms however I quant all ops with,
> 
> ```
> prefix = ["MatMul", "Add", "Relu"]
> linear_names = [v for v in names if v.split("_")[0] in prefix]
> 
> quantize_dynamic(onnx_model, onnx_model+".quantall", weight_type=QuantType.QUInt8)
> quantize_dynamic(onnx_model, onnx_model+".int8.quant", weight_type=QuantType.QInt8, nodes_to_quantize=linear_names, extra_options={"MatMulConstBOnly":True})
> quantize_dynamic(onnx_model, onnx_model+".uint8.quant", weight_type=QuantType.QUInt8, nodes_to_quantize=linear_names, extra_options={"MatMulConstBOnly":True})
> ```
> 
> the inference time `.quantall` model is 94.91ms , `.uint8.quant` model is 40.31ms, but the `.int8.quant` is 37.87ms
> 
> it seems that quant with conv is slower, and unit8 quant is slower than int8

Does your model have Conv? If so, could you please refer to the recommendataion here and try static quantization?
https://onnxruntime.ai/docs/performance/quantization.html#method-selection

**Comment by fxmarty** [comment]
Why can we use `weight_type=QuantType.QInt8` with models with only linear layers, but not with models with conv layers? At the end of the day it's pretty much the same?

**Comment by FrancescoSaverioZuppichini** [comment]
news?

**Comment by luvwinnie** [comment]
is there any news for this?I hope to dynamic quantize my CNN based model too. What is the best solution to speed up the inference speed?

**Comment by pauldog** [comment]
I can get the quantized models to work on CPU with Quint8 but they crash on GPU (CUDA or DirectML)

**Comment by erictsai1224tw** [comment]
> 

What is names?

**Comment by srikar242** [comment]
@wangyunxiaa What is the names variable you are referring to in list comprehension to get linear names. I tried to use your code and getting the below error. Your help is appreciated.

```
Traceback (most recent call last):
  File "/Users/srikar/test_model_results/dynamic_quant.py", line 9, in <module>
    linear_names = [v for v in names if v.split("_")[0] in prefix]
NameError: name 'names' is not defined
```

**Comment by hu8813** [comment]
NOT_IMPLEMENTED : Could not find an implementation for ConvInteger(10) node with name '/model.0/conv/Conv_quant'

have the same Error for an INT8 quantized model

**Comment by MotiHamoGBG** [comment]
> @wangyunxiaa What is the names variable you are referring to in list comprehension to get linear names. I tried to use your code and getting the below error. Your help is appreciated.
> 
> ```
> Traceback (most recent call last):
>   File "/Users/srikar/test_model_results/dynamic_quant.py", line 9, in <module>
>     linear_names = [v for v in names if v.split("_")[0] in prefix]
> NameError: name 'names' is not defined
> ```

        model = onnx.load(src)
        names = {node.name for node in model.graph.node}
