### ISSUE TITLE
GetTensorShapeElementCount return wrong result if tensor shape has unknown

### ISSUE THREAD

**Issue by harrysummer** [microsoft/onnxruntime#3132]
According to the inline comment, C API `GetTensorShapeElementCount` returns the number of elements specified by the tensor shape. And if any dimension is negative, it returns a negative value. However, the return type is `size_t` and it's not possible to return negative values.

Related source code: https://github.com/microsoft/onnxruntime/blob/6cdd2b4934ef42518f80d5b0938c08285100d22e/include/onnxruntime/core/session/onnxruntime_c_api.h#L499

**Comment by snnn** [comment]
The size_t is the length of the array(dimensions).

**Comment by harrysummer** [comment]
> The size_t is the length of the array(dimensions).

I don't think it is the length of an array. According to the inline comments:
```
 * Return the number of elements specified by the tensor shape.
 * Return a negative value if unknown (i.e., any dimension is negative.)
 * e.g.
 * [] -> 1
 * [1,3,4] -> 12
 * [2,0,4] -> 0
 * [-1,3,4] -> -1
```

So, in my understanding, `size_t *out` is a pointer to a integer which will hold the number of elements for the tensor after calling the API.

**Comment by harrysummer** [comment]
Note that `GetTensorShapeElementCount` will call `TensorShape::Size()` internally. The return type of `TensorShape::Size()` is `int64_t` which is signed integer and can be set to `-1`.

**Comment by snnn** [comment]
You're right, it's a bug. How urgent is it?

**Comment by snnn** [comment]
Sorry, you confused me.

https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/framework/tensor_type_and_shape.cc#L55

It didn't call the Size() function. I guess it calls "size()" not "Size()".

**Comment by snnn** [comment]
I see. The bug was introduced in #1194.

**Comment by harrysummer** [comment]
> You're right, it's a bug. How urgent is it?

Not urgent. I have applied a workaround in my code to provide the API with a reinterpret_cast'ed int64 number.

> It didn't call the Size() function. I guess it calls "size()" not "Size()".
I think you are looking at wrong place. Should be here: https://github.com/microsoft/onnxruntime/blob/c32cedc6c9011f3e4069d686c6062fc7bfb55dcc/onnxruntime/core/framework/tensor_type_and_shape.cc#L73-L76

**Comment by snnn** [comment]
Thank you. We'll fix it in onnxruntime 1.3.

**Comment by harrysummer** [comment]
> Thank you. We'll fix it in onnxruntime 1.3.

Thanks for the quick response! I guess you mean v1.1.3?

**Comment by snnn** [comment]
> Thanks for the quick response! I guess you mean v1.1.3?

Sorry, no. :-(  I mean 1.3.

**Comment by harrysummer** [comment]
> > Thanks for the quick response! I guess you mean v1.1.3?
> 
> Sorry, no. :-( I mean 1.3. Please let Faith know if it is not OK for you.

OK. I am good with 1.3 :) . Just feel some doubt because there is not a 1.2 at the moment when we are talking 1.3....
