### ISSUE TITLE
CUDAExecutionProvider doesn't respect kernels defined in custom op C API

### ISSUE THREAD

**Issue by harrysummer** [microsoft/onnxruntime#3138]
**Describe the bug**
ONNX Runtime cannot find custom op kernel defined and registered with CUDA execution provider. This will cause an error when loading the model which complains about no available execution provider for the operator. The reason is the incorrect implementation in `CUDAExecutionProvider::GetCapability`:

https://github.com/microsoft/onnxruntime/blob/a2eeb126b9553827cce4a401b8a857df78d4a49e/onnxruntime/core/providers/cuda/cuda_execution_provider.cc#L1299-L1300

The function doesn't even use the `KernelRegistry` passed to it on the second parameter. Instead, it uses the registry returned by `CUDAExecutionProvider::GetKernelRegistry()` which only contains core ops and contrib ops, but not custom ops.

**Urgency**
It's a blocking issue of my project but I applied some fix to the code somehow and built a working binary on my local which is ready to use. I am glad to share it if you need.

**System information**
- OS Platform and Distribution: Windows
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: v1.1.2
- Python version: N/A
- Visual Studio version (if applicable): 2017
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 9.0 / 7.4.2
- GPU model and memory: NVIDIA Quadro M2000 / 4GB

**To Reproduce**
1. Write a custom op and register it with CUDA execution provider
2. Build a model that uses the custom op
3. Load the model into a CUDA provider enabled session

**Expected behavior**
The model should load correct without failure.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by pranavsharma** [comment]
You're right. We haven't added support for CUDA custom ops yet. Is this something you've a requirement for? What scenario are you targeting? Feel free to email me at prs@. Thanks!
cc @RyanUnderhill
