### ISSUE TITLE
Adding sparse matrix support (or failing them)

### ISSUE THREAD

**Issue by victornoel** [microsoft/onnxruntime#3144]
**Is your feature request related to a problem? Please describe.**

I am creating models with sklearn + xgboost and in particular using the `OneHotEncoder` of sklearn and generating onnx models using sklearn-onnx. 

One hot encoding using sparse matrix as output results in much 10x faster training with `XGBRegressor`.

Currently, if I let the encoder output sparse matrix, onnxruntime gives incorrect values (see https://github.com/onnx/onnxmltools/issues/371 for details).

If it doesn't use sparse matrix, then everything work as expected.

**System information**
- ONNX Runtime version (you are using): v1.1.2

**Describe the solution you'd like**

I see two incremental solutions:
- first onnxruntime should fail when using sparse matrix since it doesn't support them.
- second onnxruntime should support sparse matrix so that we can have more efficient training and predicting

**Describe alternatives you've considered**

Not using sparse matrix, but as I said it is incredibly slow compared to using them.

**Additional context**

I'm not 100% sure sparse tensor are meant to be supported or not by onnx, see https://github.com/onnx/onnx/issues/2008.

**Comment by victornoel** [comment]
Can we get some feedback on this?

@pranavsharma @prabhat00155 or @skottmckay maybe? 

thanks :)

**Comment by ag-tcm** [comment]
Did this ever get fixed?

**Comment by victornoel** [comment]
@ag-tcm I would recommend testing it now with the latest version of onnx and co, you can look at the repro I wrote in the past: https://github.com/onnx/onnxmltools/issues/371

I don't use onnx anymore so I won't do it :)
