### ISSUE TITLE
ONNXRUNTIME C++ API ROI-Align Sampling Ratio < 0 Support

### ISSUE THREAD

**Issue by John-HW-Cao** [microsoft/onnxruntime#3156]
Hello, I am trying to deploy a pytorch model in the format of ONNX and there is ROI-Align module in my model. 

During the training process, the sampling ratio is set to be default in pytorch, which is -1 and means adaptive sampling. Then when I run the trained model in C++, the following error comes out

`Exception during initialization: /onnxruntime_src/onnxruntime/core/providers/cpu/object_detection/roialign.h:48 onnxruntime::RoiAlignBase<T>::RoiAlignBase(const onnxruntime::OpKernelInfo&) [with T = float] sampling_ratio_ >= 0 was false. Sampling ratio should be >=0, but it was -1`

**System information**
- ONNX Runtime version 1.1.2 C++ lib release 

**Describe the solution you'd like**
I hope the negative sampling ratio can be supported in the future, where the sampling ratio is adaptive and automatically calculated for width and height.

**Comment by pranavsharma** [comment]
As per the ONNX spec
```sampling_ratio : int (default is 0)
Number of sampling points in the interpolation grid used to compute the output value of each pooled output bin. If > 0, then exactly sampling_ratio x sampling_ratio grid points are used. If == 0, then an adaptive number of grid points are used (computed as ceil(roi_width / output_width), and likewise for height). Default is 0.```

Not sure if the number of sampling points should be negative. cc @spandantiwari

**Comment by John-HW-Cao** [comment]
Thank you very much for the response. 

I see. So now the adaptive ratio is realized in ONNX by **sampling_ratio = 0** and in pytorch by **sampling_ratio = -1**.
