### ISSUE TITLE
OnnxTensor.createTensor should support Nd4j Objects

### ISSUE THREAD

**Issue by jomach** [microsoft/onnxruntime#3157]
Currently to create a tensor we need to reshape the image. A common way to do this in Java is to use the Nd4j Lib (http://nd4j.org/index.html). This Lib uses c libs in the background to perform the calculations which of course moves the data away from the JVM. As the function OnnxTensor.createTensor(OnnxInferencer.getEnvironment, array) does kind the same we could have a performance improvement if read Nd4j objects directly that is already in the c stack let's say so. 

As an example: 

       val ndArray = Nd4j.create(data) <--- Copies data into C stack
        val indexW = row.getAs[Int](config.widthField)
        val indexH = row.getAs[Int](config.heightField)
        val reshaped = ndArray.reshape(indexH, indexW, 3)
        val normalizationArray = Array(102.9801, 115.9465, 122.7717)
        val normNd4j = Nd4j.create(normalizationArray)
        val normalized = reshaped.sub(normNd4j)
        //This is very expensive as it copies
        val backToHeap = normalized.ravel.toDoubleVector <-- Copies data from C Stack into JVM
        val tensor = OnnxTensor.createTensor(OnnxInferencer.getEnvironment, backToHeap) <-- Copies the JVM data back to C stack but for Onnx.
 
How it could be: 

        val ndArray = Nd4j.create(data) <--- Copies data into C stack
        val indexW = row.getAs[Int](config.widthField)
        val indexH = row.getAs[Int](config.heightField)
        val reshaped = ndArray.reshape(indexH, indexW, 3)
        val normalizationArray = Array(102.9801, 115.9465, 122.7717)
        val normNd4j = Nd4j.create(normalizationArray)
        val normalized = reshaped.sub(normNd4j)
        val tensor = OnnxTensor.createTensor(OnnxInferencer.getEnvironment, normalized)  <-- No Copies to JVM

**Comment by Craigacp** [comment]
You should be able to call `normalized.data().asNioFloat()` to get a `java.nio.FloatBuffer` back, which you can then pass into `OnnxTensor.createTensor(OrtEnvironment,FloatBuffer,long[])`. You'll need to supply the shape again. That shouldn't do any copying, assuming Nd4j is creating the FloatBuffer view appropriately. Actually if all you need to do is reshape it, then you can probably just have the data in a `java.nio.FloatBuffer` to begin with, and just change the shape by supplying a different one to the `createTensor` method. That assumes that your data is represented in n-dimensional row-major order (i.e. C order).

**Comment by jomach** [comment]
@crahrig  this seems to work. Thanks ! From the performance seems that it is reading via nio
