### ISSUE TITLE
ShapeInferenceError on a very simple network with resize only

### ISSUE THREAD

**Issue by ycchanau** [microsoft/onnxruntime#3167]
**Describe the bug**
I am testing on a very simple onnx model as below.
![model](https://user-images.githubusercontent.com/43056995/76150227-07a02580-60e3-11ea-8d62-5a7bb1f27a53.png)

The model is exported from PyTorch. When I tried to use the exported onnx model in onnxruntime, I got this error. I totally have no idea why I got this error. The onnx.checker didn't give me any warning or error but onnxruntime.InferenceSession failed.

> Traceback (most recent call last):
>   File "resize_test.py", line 53, in <module>
>     main()
>   File "resize_test.py", line 47, in main
>     ort_session = onnxruntime.InferenceSession("model.onnx")
>   File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 25, in __init__
>     self._load_model(providers)
>   File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 43, in _load_model
>     self._sess.load_model(providers)
> onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node: Output:output [ShapeInferenceError] Can't merge shape info. Both source and target dimension have values but they differ. Source=1 Target=3 Dimension=1

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: onnxruntime-gpu 1.1.2 
- Python version:3.6.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: Cuda 10.0
- GPU model and memory: T4
- Pytorch: 1.3.1
- Onnx: 1.6

**To Reproduce**
```
def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

class Resize_Test(nn.Module):
    def __init__(self):
        super(Resize_Test, self).__init__()


    def forward(self, x):
        x = F.interpolate(x, size=(128, 128), mode='bilinear', align_corners=True)
        return x

def main():
    model = Resize_Test()
    batch_size=1
    dummy_input = torch.randn(batch_size, 3, 32, 32, device="cuda")
    print("exporting model")
    # Export the model
    torch.onnx.export(model,           # model being run
                      dummy_input,                         # model input (or a tuple for multiple inputs)
                      "model.onnx",   # where to save the model (can be a file or file-like object)
                      export_params=True,        # store the trained parameter weights inside the model file
                      do_constant_folding=True,  # whether to execute constant folding for optimization
                      input_names = ['input'],   # the model's input names
                      output_names = ['output'], # the model's output names
                      dynamic_axes={'input' : {0 : 'batch_size'}, 'output' : {0 : 'batch_size'}},    # variable lenght axes
                      verbose=True,
                      opset_version=11,
                      keep_initializers_as_inputs=True)

    #####################################################################
    print("checking onnx model")
    onnx_model = onnx.load("model.onnx")
    onnx.checker.check_model(onnx_model)
    onnx.checker.check_graph(onnx_model.graph)
    print("onnx model is checked")

    ort_session = onnxruntime.InferenceSession("model.onnx")
    ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(dummy_input)}
    ort_outs = ort_session.run(None, ort_inputs)
    ort_prediction = ort_outs[0]

if __name__ == '__main__':
    main()

```

**Comment by hariharans29** [comment]
The onnx checker doesn’t run shape inference bu default. Please try manually running shape inference - https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md

**Comment by ycchanau** [comment]
I fixed this problem without making any change to the code but just upgrade PyTorch to 1.4.0. The model now looks like that. 
![model](https://user-images.githubusercontent.com/43056995/76158877-8d5cb900-6155-11ea-95a8-a08764777fa3.png)
