### ISSUE TITLE
Inference Maskrcnn model via Onnxruntime(c++) and got bugs

### ISSUE THREAD

**Issue by Li-chunming** [microsoft/onnxruntime#3168]
**Describe the bug**
Recently I have tried to do inference about model Maskrcnn by using Onnxruntime, but when I use the `auto output_tensors = session.Run(Ort::RunOptions{ nullptr }, input_node_names.data(),&input_tensor_,1,output_names,1);`  it got the promblem like 
![image](https://user-images.githubusercontent.com/59553759/76158981-b9c50500-6156-11ea-9685-7d5d72efffac.png)

Actually I used the onnx model in the [model-zoo](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/mask-rcnn), I want to ask if anyone has used it successfully? 
I have done the inference successfully by using  python, but I really can't understand the problems in C++.Anyone can help me?

**System information**
- Windows 10:
- ONNX Runtime installed from [onnxruntime-win-x64-gpu-1.1.2.zip](https://github.com/microsoft/onnxruntime/releases)
- ONNX Runtime version:1.1.2
- Visual Studio version :2019
- CUDA/cuDNN version:CUDA10.0
- GPU model and memory:GTX 2070

**To Reproduce**

the [codes](https://github.com/Li-chunming/onnxruntime-maskrcnn/blob/master/c%2B%2B) have been upload in my [files](https://github.com/Li-chunming/onnxruntime-maskrcnn), the sucessful python file is also in there. 
Actually my C++ codes are only suitable for the example image in the files.

I have tried to use another function
 `OrtRun(session_, nullptr, input_names, &input_tensor_1, 1, output_names, 1, &output_tensor_1);` 
but it got another problem:
![image](https://user-images.githubusercontent.com/59553759/76159677-dd3f7e00-615d-11ea-976b-d747c67f1ff8.png)

It means the model's input is dynamic.

Who can help me?

**Comment by Li-chunming** [comment]
emm I got wrong input_shape lol .

**Comment by zr526799544** [comment]
> emm I got wrong input_shape lol .

From the c++ I want to know how can I get the Full output from the Maskrcnn？ because I can‘t assert the outputshape. could you give some advise?

**Comment by Li-chunming** [comment]
@zr526799544  You can browse our discussions in this [issue](https://github.com/microsoft/onnxruntime/issues/3170), hope this can help you .
