### ISSUE TITLE
Cannot build ORT with Visual Studio 2017 Version 15.9.20 and CUDA 10.1

### ISSUE THREAD

**Issue by xgirones** [microsoft/onnxruntime#3169]
**Describe the bug**
Build errors appear when trying to build ORT (commit a59243090a7c71732c1d7e681c2aeffe9e10c8ec) for Windows using Visual Studio 2017 Version 15.9.20 and CUDA Toolkit 10.1.

**Urgency**
I was experiencing spurious crashes on GPU with ORT built from commit cd876720d930fcea33c2c3f3bb9717ae115c007c. I would like to try the latest ORT code in master to see if the problem has improved but now I am unable to build the library.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 7
- ONNX Runtime installed from (source or binary): Source
- ONNX Runtime version: (commit a59243090a7c71732c1d7e681c2aeffe9e10c8ec)
- Python version: 3.6
- Visual Studio version (if applicable): Visual Studio 2017 version 15.9.20
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 

```
CUDA version: 10.1.168
cuDNN  version: cudnn-10.1-windows7-x64-v7.6.1.34
```

- GPU model and memory: GeForce RTX 2080 Ti
- CMake version: 3.16.5

**To Reproduce**
-Clone ORT commit a59243090a7c71732c1d7e681c2aeffe9e10c8ec.
-Open an Anaconda Prompt and activate a Python 3.6 environment.
-Set VS2017 environment vars and context. I tried both

`"%VS2017INSTALLDIR%\VC\Auxiliary\Build\vcvars64.bat" `

and

`"%VS2017INSTALLDIR%\Common7\Tools\VsDevCmd.bat" ` 

but it does not make any difference which option I use.

-Run the build script under the _onnxruntime_ folder

`build.bat --cmake_path "C:\Program Files\CMake\bin\cmake.exe" --config RelWithDebInfo --parallel --use_dnnl --use_cuda --cuda_version 10.1 --build_shared_lib  --cudnn_home %CUDNN_PATH% --cuda_home "%CUDA_PATH%" --skip_tests`

%CUDA_PATH% --> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
%CUDNN_PATH% --> D:\ThirdPartyLib\cudann\cudnn-10.1-windows7-x64-v7.6.1.34\

The build process fails with many instances of the following errors when compiling the CUDA provider:

```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\corecrt_malloc.h(63): error : unknown attribute "guard" [E:\repo\ort\build\Windows\RelWithDebInfo onnxruntime_providers_cuda.vcxproj]
```

```
  topk_impl.cu
  
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.1.targets(762,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" -gencode=arch=compute_50,code=\"sm_50,compute_50\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_70,code=\"sm_70,compute_70\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64" -x cu  -IE:\repo\ort\include\onnxruntime -IE:\repo\ort\include\onnxruntime\core\session -IE:\repo\ort\cmake\external\nsync\public -IE:\repo\ort\cmake\external\eigen -IE:\repo\ort\build\Windows\RelWithDebInfo -IE:\repo\ort\cmake\external\onnx -IE:\repo\ort\cmake\external\protobuf\src -IE:\repo\ort\build\Windows\RelWithDebInfo\onnx\.. -IE:\repo\ort\onnxruntime -IE:\repo\ort\cmake\external\cub -I"D:\ThirdPartyLib\cudann\cudnn-10.1-windows7-x64-v7.6.1.34\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include"     --keep-dir x64\RelWithDebInfo -maxrregcount=0  --machine 64 --compile -cudart shared --expt-relaxed-constexpr --default-stream legacy --compiler-options /utf-8 --compiler-options /sdl -Xcompiler="-Zi -Ob1 /d2FH4-"    -DNDEBUG -DEIGEN_USE_THREADS -DONNX_ML -DONNX_NAMESPACE=onnx -DONNX_USE_LITE_PROTO -D__ONNX_NO_DOC_STRINGS -DEIGEN_MPL2_ONLY -DUSE_EIGEN_FOR_BLAS -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -DUSE_CUDA=1 -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -DWIN32 -D_WINDOWS -Dgsl_CONFIG_CONTRACT_VIOLATION_THROWS -DEIGEN_HAS_C99_MATH -DNDEBUG -DGSL_UNENFORCED_ON_CONTRACT_VIOLATION -DEIGEN_USE_THREADS -DONNX_ML -DONNX_NAMESPACE=onnx -DONNX_USE_LITE_PROTO -D__ONNX_NO_DOC_STRINGS -DEIGEN_MPL2_ONLY -DUSE_EIGEN_FOR_BLAS -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -DUSE_CUDA=1 -D"CMAKE_INTDIR=\"RelWithDebInfo\"" -D_MBCS -Xcompiler "/EHsc /W4 /nologo /O2 /Fdonnxruntime_providers_cuda.dir\RelWithDebInfo\onnxruntime_providers_cuda.pdb /FS /Zi  /MD /GR" -o onnxruntime_providers_cuda.dir\RelWithDebInfo\topk_impl.obj "E:\repo\ort\onnxruntime\core\providers\cuda\math\topk_impl.cu"" exited with code 2. [E:\repo\ort\build\Windows\RelWithDebInfo\onnxruntime_providers_cuda.vcxproj]
```

**Expected behavior**
The library should compile without errors.

**Comment by Li-chunming** [comment]
I used the [release version ](https://github.com/microsoft/onnxruntime/releases) v1.1.2-gpu , and CUDAToolkit version==10.1, but it got some error. So I changed to 10.0, and it can run sucessful now.
Maybe you can try to change your CUDAToolkit version, they may  do not match.

**Comment by xgirones** [comment]
Thanks for your answer but unfortunately I can't go back to CUDA 10.0. Besides, I was successfully building ORT with CUDA 10.1 just one month ago. I'd like to know what has changed since then.

**Comment by xgirones** [comment]
Any idea please? Has there been any recent change in the build process for CUDA?

**Comment by lixwy** [comment]
change you -gencode=arch=compute_xx,code=\"sm_xx,compute_xx\", which need match your nvidia-gpu

**Comment by lixwy** [comment]
Change your -gencode=arch=compute_xx,code="sm_xx,compute_xx",  xx  need match your nvidia-gpu

**Comment by xgirones** [comment]
Thanks, it seems that I also had to specify the Windows SDK version:

--cmake_extra_defines CMAKE_SYSTEM_VERSION=10.0.17763.0

**Comment by qumasaike** [comment]
> Change your -gencode=arch=compute_xx,code="sm_xx,compute_xx", xx need match your nvidia-gpu

thanks, it works
