### ISSUE TITLE
Snap package support

### ISSUE THREAD

**Issue by mikeroyal** [Microsoft/onnxruntime#317]
I was thinking the install and setup could be improved for Ubuntu and other Linux distros by having a [snap package](https://snapcraft.io/) version. If it's not a priority would you mind if I made the snap as a contribution?

[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Build and test snap](https://snapcraft.io/build)

[Getting Started snap template](https://github.com/snapcrafters/fork-and-rename-me)

**Comment by pranavsharma** [comment]
Thanks for your suggestion. At this time for the sake of simplicity we plan on supporting tarballs only for all Linux distros. Installation of tarballs doesn't depend on the usage of any thirdparty tools and other popular frameworks like tensorflow also do the same. If there is sufficient demand for snap pkgs we can consider it as part of our roadmap.
