### ISSUE TITLE
Delay-loading of onnxruntime.dll fails

### ISSUE THREAD

**Issue by JohannesBrx** [microsoft/onnxruntime#3172]
**Describe the bug**
Since v1.1.0 it is not possible any more to delay-load `onnxruntime.dll`. This is due to the following code lines in `onnxruntime_cxx_api.h` which are embedded in all modules using the API header: They call a function in the DLL during the static initialization of the implementing module and thus require `onnxruntime.dll` to be already loaded:
```
template <typename T>
const OrtApi& Global<T>::api_ = *OrtGetApiBase()->GetApi(ORT_API_VERSION);
```

In our application we only want to load `onnxruntime.dll` when it is really required.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.1.2
- Python version: 3.7
- Visual Studio version (if applicable): Visual Studio 2015

**To Reproduce**

- Create a minimalistic command line project (see code below)
- Use onnxruntime as a dynamic library (set linker _additional dependencies_ `onnxruntime.lib` and _additional library directories_)
- Add `onnxruntime.dll` under Linker | Input | Delay Loaded Dlls
- Run the executable **without** providing onnxruntime.dll and with no command line arguments.
- The program will crash at the following line in `onnxruntime_cxx_api.h` although the onnxruntime API is not used.
  `const OrtApi& Global<T>::api_ = *OrtGetApiBase()->GetApi(ORT_API_VERSION);`

```
#include "stdafx.h"
#include "onnxruntime_cxx_api.h"

int main(int argc, char** argv)
{
	if (argc > 1)
	{
		volatile const OrtApiBase* baseApi = OrtGetApiBase();
	}
    return 0;
}
```

**Expected behavior**
I would expect the executable not trying to load `onnxruntime.dll` because there are not API functions being called when `argc == 1`.

This could be achieved by implementing an explicit library initialization method which has to be called by the user of onnxruntime.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8805876/76295179-72ed2180-62b4-11ea-9ef6-ae4ab636b42e.png)

**Additional context**
I think pull request #2228 has broken the ability to delay-load `onnxruntime.dll` because it performs calls to the API during static initialization of each implementing module.

The pre-processor define `EXCLUDE_REFERENCE_TO_ORT_DLL` does not much improve the situation because it would only allow **one** compilation unit to include `onnxruntime_cxx_api.h`. If included by multiple compilation units, the linker will issue an error LNK4006 (_symbol already defined in object_).

**Comment by pranavsharma** [comment]
One workaround is to use the C APIs instead.

**Comment by RyanUnderhill** [comment]
Yeah, I will figure out a better solution for the next version as it has caused multiple problems and isn't worth keeping anymore.

**Comment by RyanUnderhill** [comment]
@JohannesBrx Just wanted to let you know that we did add fix for this: ORT_API_MANUAL_INIT
Just #define this before including the onnxruntime_cxx_api.h header and call Ort::InitApi() before using any of the functions.
