### ISSUE TITLE
onnxruntime.dll is built differently for the releases page compared to the nuget.org version

### ISSUE THREAD

**Issue by martinb35** [microsoft/onnxruntime#3179]
**Describe the bug**
You can download onnxruntime.dll either from the github releases pages or from nuget.org. The files should be the same, but they are not (size is different and looks like one gets built with use_featurizers and the other doesn't). 

**Urgency**
Should fix this for the next release (1.3).

**Expected behavior**
The binaries should be the same no matter where they are downloaded from. Also, now that windows.ai.machinelearning.dll is available in the nuget package, that binary and supporting files should also be in the releases zip file.

**Comment by yuslepukhin** [comment]
We no longer build any packages with featurizers. Please, indicate which one is built with them.

**Comment by pranavsharma** [comment]
> We no longer build any packages with featurizers. Please, indicate which one is built with them.

I've not verified this, but it was reported that the nuget one had featurizers in it.
