### ISSUE TITLE
How to put more than one inputs using onnxruntime?

### ISSUE THREAD

**Issue by hoaquocphan** [microsoft/onnxruntime#3184]
Hi All,

Currently, I'm porting TinyYolov3 on Onnxruntime by C++

this model have 2 inputs as below:
```
Current Model is yolov3-tiny.onnx
Number of inputs = 2
Input 0 : name=input_1
Input 0 : type=1
Input 0 : num_dims=4
Input 0 : dim 0=1
Input 0 : dim 1=3
Input 0 : dim 2=416
Input 0 : dim 3=416
Input 1 : name=image_shape
Input 1 : type=1
Input 1 : num_dims=2
Input 1 : dim 0=1
Input 1 : dim 1=2
```

I can put the **input_1** to Onnx as below line:
```
g_ort->CreateTensorWithDataAsOrtValue(memory_info, input_tensor_values.data(), input_tensor_size*sizeof(float), input_node_dims.data(), 4, ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT, &input_tensor)
```

So how to put 2 input: **input_1** and **image_shape** to Onnx?

**Comment by hoaquocphan** [comment]
Hi All.

As the sample code:
https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp#L52
using vector<vector<>> for more than 1 input. 
but the function CreateTensorWithDataAsOrtValue accept only 1 dimension vector.

**Comment by hoaquocphan** [comment]
Hi All,
I found the solution here: https://github.com/microsoft/onnxruntime/issues/2250

**Comment by joe-zxh** [comment]
thx bro
