### ISSUE TITLE
PyPy support

### ISSUE THREAD

**Issue by kuk** [microsoft/onnxruntime#3185]
What are your thoughts on supporting PyPy? Currently, I am not able to install ONNX Runtime under PyPy 3.6:

```
root@8bcec4489595:/# pypy3 --version
Python 3.6.9 (1608da62bfc7, Dec 23 2019, 10:50:04)
[PyPy 7.3.0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
root@8bcec4489595:/# pypy3 -m pip install onnxruntime
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime

```

ONNX Runtime itself may not benefit from using PyPy but Runtime may be used as a part of larger system that relies on PyPy performance boost. For example data preprocessing before inference may benefit from using PyPy.

**Comment by pranavsharma** [comment]
We don't have any plans for supporting PyPy. Contributions are welcome.

**Comment by Algortex** [comment]
I would like pypy support too.

**Comment by santoshmahto7** [comment]
enabling pypy support will be great
