### ISSUE TITLE
quantize.py error(s) static quantization

### ISSUE THREAD

**Issue by jeandebleau** [microsoft/onnxruntime#3188]
Hi, 

I am currently debugging the quantization tool. There is a least one error in the function def _get_quantize_input_nodes(self, node, input_index, qType), line 623.

lines 623-624: return [qlinear_node] should be added ; this specific conditional branch does not return a value.

**Comment by yufenglee** [comment]
Thanks for reporting the bug. Let's know if you found more issues.
