### ISSUE TITLE
No Op registered

### ISSUE THREAD

**Issue by lixiepeng** [microsoft/onnxruntime#3191]
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node: : No Op registered for Einsum with domain_version of 11
```
As the model can be exported by torch.onnx.export with `opset_version=11`, How can we manully add the support for Einsum operator in onnxruntime?

**Comment by hariharans29** [comment]
EInsum is only going to be part of the ONNX spec since opset 12 - https://github.com/onnx/onnx/blob/master/docs/Operators.md#Einsum. An opset 11 ONNX model cannot have the EinSum op. 

As a side note, ORT will implement opset 12 after the ONNX release.

**Comment by woaixiaojiaa** [comment]
hello , @hariharans29  like this op , Bucketize ,when i load .onnx model, some error has occured, No Op registered for Bucketize with domain_version of 11  ??  are there solutions?
