### ISSUE TITLE
Is runtime CPU and GPU support available from one lib in C++?

### ISSUE THREAD

**Issue by calebwherry** [microsoft/onnxruntime#3195]
Releases of the ONNX runtime come in 2 flavors: CPU and GPU. It is not clear to be from the documentation if selecting which to run (and it working for both) at runtime is supported in C++?

Stated another way: can one single dll/so fully handle both CPU and GPU usage? 

My gut feeling is no since the CPU libs have an OpenMP depends and the GPU don't but have CUDA. So I'd expect you can't actually run both CPU and GPU operations using a single dll/so in C++.

If that is that case, then I suppose the normal plugin strategy is in order with LoadLibrary/dlopen to select CPU vs GPU libs at runtime. Just wanted to make sure I didn't miss something in the documentation somewhere!

**Comment by calebwherry** [comment]
I suppose a logical follow-up would be: if I built from source, could I turn both CPU and GPU on for a single dll/so build or do I still have to go the plugin route?

**Comment by pranavsharma** [comment]
If you use the GPU (cuda) package, any op that is not implemented by us in cuda will fallback to the CPU implementation. You need to have the cuda dependencies installed and in the path in order to use the GPU pkg. Does this answer your question?

**Comment by calebwherry** [comment]
No, not really. I am asking can you programmatically select to use CPU vs GPU in C++ and have them both work (no fallbacks) while using a single package?

Maybe stated another way: can you use the CPU/MKL-DNN/CUDA execution providers from the same package and have them all work at runtime?

Or, depending on which package you use, are you restricted to specific execution providers?

**Comment by pranavsharma** [comment]
Feel free to build from the source to have all or any combination of execution providers built in the same package. Currently you're restricted based on the package and we've only 2 - CPU and GPU. Thanks!
