### ISSUE TITLE
Segfault when reducing a 0D Tensor

### ISSUE THREAD

**Issue by pranav-prakash** [microsoft/onnxruntime#3208]
**Describe the bug**
As a self-contained example, consider the following case where we attempt to reduce a 0D tensor:

```
TEST(ReductionOpTest, Reduce0DTensor) {
  OpTester test("ReduceMin");
  test.AddInput<float>("data", {}, {2});
  test.AddOutput<float>("reduced", {}, {2});
  test.Run();
}
```

This seems to result in a segmentation fault at `PrepareForReduce` in `reduction_ops.cc`. Within that function, because `ndim == 0` and `axes.size() == 0`, when the following conditions are evaluated 

```
  if (axes.size() <= ndim &&
      axes.front() == static_cast<int64_t>(ndim - axes.size()) &&
      axes.back() == static_cast<int64_t>(ndim) - 1) {
    need_copy = false;
  }
```

we will attempt to dereference `axes.front()` which will segfault. Assuming this is the issue, it should be straightforward to add a check for the case for `ndim == 0` and skip reduction entirely.

**Urgency**
Severity is probably P2. We ran into this issue trying to perform post-training quantization on a BERT network; there is no a hard deadline though.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04 
- ONNX Runtime installed from (source or binary): Exists in both binary installed from pypi and from source
- ONNX Runtime version: Pypi version 1.20, source built from HEAD
- Python version: 3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 9.2.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
The aforementioned test case should demonstrate the issue. A segfault is observed at the line where `axes.front()` is dereferenced.

**Expected behavior**
Reduction on a 0D tensor should just return that single scalar untouched when applicable.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by yuslepukhin** [comment]
@KeDengMS  for TensorRT and TVM
