### ISSUE TITLE
How to run a onnx model on GPU in c++?

### ISSUE THREAD

**Issue by ping28198** [microsoft/onnxruntime#3218]
**Is your feature request related to a problem? Please describe.**
I want run a ONNX model on GPU, but I can not switch to GPU, and there is not example about this. The lib is GPU version, but I have not find any API to use GPU in the header, c++. Other, There is not any  tutors about using onnxruntime tensorrt back-end. 

**System information**
1.2.0

**Describe the solution you'd like**
An example or other 

**Describe alternatives you've considered**

**Additional context**

**Comment by hariharans29** [comment]
Does this help - https://github.com/microsoft/onnxruntime/blob/0fceb33288ce35472d1cbab24fd7d95d5d3c9b07/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp#L22 ?

**Comment by hariharans29** [comment]
For TensorRT - pls check here - https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/TensorRT-ExecutionProvider.md
