### ISSUE TITLE
CPUExecutionProvider and CUDAExecutionProvider switching during runtime

### ISSUE THREAD

**Issue by qraleq** [microsoft/onnxruntime#3221]
**Describe the bug**

I tried to run one OD model that is converted from tensorflow to onnx using CUDA onnxruntime. One warning pops up in the terminal:
`2020-03-15 12:34:54.824837445 [W:onnxruntime:Default, cuda_execution_provider.cc:1400 GetCapability] CUDA kernel not supported. Fallback to CPU execution provider for Op type: Conv node name: FeatureExtractor/MobilenetV2/fpn/bottom_up_Conv2d_21/separable_conv2d/depthwise`

Then I tried to profile the onnx session (file attached) and noticed that there are many switches between CPUExecutionProvider and CUDAExecutionProvider during the runtime. This for sure impacts the performance of the model in the inference.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.2.0
- Python version: 3.6
- GCC/Compiler version (if compiling from source): gcc version 6.5.0 20181026 (Ubuntu 6.5.0-2ubuntu1~18.04) 
- CUDA/cuDNN version: 10.0/7
- GPU model and memory: GeForce 940MX 4GB

**Expected behavior**
I expect that the number of switches between CPUExecutionProvider and CUDAExecutionProvider  should be lower than it currently is. 

[onnxruntime_profile__2020-03-15_12-34-54.txt](https://github.com/microsoft/onnxruntime/files/4334131/onnxruntime_profile__2020-03-15_12-34-54.txt)

**Comment by hariharans29** [comment]
Not all ops have CUDA implementations and so the gap is filled in by using CPU kernels. With every release, the number of CUDA kernels supported does increase.

In some cases, for example - Conv ops, CUDA kernels are not supported by design. Please see - https://github.com/microsoft/onnxruntime/issues/2313
