### ISSUE TITLE
Create Session fails....

### ISSUE THREAD

**Issue by JohnCraigPublic** [microsoft/onnxruntime#3222]
**Describe the bug**
I have an ONNX model, output from CNTK, which I would like to run with ORT.   But creating a session fails.  How to debug it?

**System information**
Windows 10 version 1909.   Using C++ via VS2017.   Inference in CPU.

**To Reproduce**
int TestCall()
 {
// initialize  environment...one environment per process
Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");

// initialize session options if needed
Ort::SessionOptions session_options;
session_options.SetIntraOpNumThreads(1);
session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);

// create session and load model into memory
Ort::Session session(env, L"GMU.onnx", session_options);   // CRASHES HERE

    // Crashes in the above statement - can't even create the session... so... maybe
    // the ONNX model is no good somehow?

  }

**Expected behavior**
I thought creating the session would be the easy part -- if that were to succeed, I'd then have to figure out how to properly format an input to the network.

**Additional context**
My ORT test code is so simple, that I think its fine.  I have tried it on an ONNX model that I downloaded from the ZOO, and all was OK.  So, perhaps something wrong with the model.
But its a functioning model in CNTK.  It is AlexNet just modified in two ways:   1) expects a
grayscale image, so one input dimension is 1 instead of 3, and 2) the output stage has been
modified to do regression and output a 12x1 set of reals.   I can look at the model in Netron
and it looks fine.  It runs in a CNTK inference code -- but I can't get it to run with ORT.

**Comment by pranavsharma** [comment]
Set the severity of the logger to ORT_LOGGING_LEVEL_VERBOSE and paste the logs here.

**Comment by JohnCraigPublic** [comment]
pranavsharma - I did that, but where is the log file?  I don't see any log file created - but not sure where to look for it....

**Comment by pranavsharma** [comment]
1. Where does it crash? Can you paste the stack trace?
2. You should've seen the logs on the console. Can you paste your full program and model here?

**Comment by JohnCraigPublic** [comment]
Program is C++ so no "console" -- is there a way for a C++ program to cause the log file to be viewable?

**Comment by JohnCraigPublic** [comment]
![Exception](https://user-images.githubusercontent.com/14355377/76881542-86f5cd80-6836-11ea-82c6-4d372c0b46a3.jpg)

**Comment by JohnCraigPublic** [comment]
![CallStack](https://user-images.githubusercontent.com/14355377/76881563-907f3580-6836-11ea-882c-11ceee2f3e21.jpg)

**Comment by JohnCraigPublic** [comment]
Here is the model.   Big thanks if you can try to see why Create Session fails...

https://drive.google.com/open?id=1JhuMZrXwaR-CPKxFUtVydRCrWdligb2j

**Comment by pranavsharma** [comment]
Looking into this...

**Comment by JohnCraigPublic** [comment]
Since the original model worked in CNTK, might this then be a bug in the ONNX output of CNTK?

**Comment by JohnCraigPublic** [comment]
Of course, the CNTK guys pointed me to you at Onnx Runtime.....

**Comment by pranavsharma** [comment]
This looks like a CNTK conversion issue as the strides dims (2) doesn't match that of input dims (3). CNTK is deprecated. Can you create your model using pytorch? 

```
  auto input_shape = ctx.getInputType(input1Idx)->tensor_type().shape();
  if (input_shape.dim_size() < 2) {
    fail_shape_inference("Input tensor must have atleast 2 dimensions");
  }

  // first dim is the batch axis and the next is the number of channels.
  size_t n_input_dims = static_cast<size_t>(input_shape.dim_size() - 2);

  // Only MaxPool and Conv support dilation. For
  // simplicity of the code, we just treat the rest of them as having all-1s
  // dilation.
  std::vector<int64_t> dilations;
  if (use_dilation && getRepeatedAttribute(ctx, "dilations", dilations)) {
    if (dilations.size() != n_input_dims) {
      fail_shape_inference("Attribute dilations has incorrect size");
    }
  } else {
    dilations.assign(n_input_dims, 1);
  }

  std::vector<int64_t> strides;
  if (getRepeatedAttribute(ctx, "strides", strides)) {
    if (strides.size() != n_input_dims) {
      fail_shape_inference("Attribute strides has incorrect size");
    }
```

**Comment by JohnCraigPublic** [comment]
You're saying that the dream of ONNX is 'fake news' ?  Microsoft certainly suggests that CNTK models can be brought to ONNX.    Yes, going forward, we will have to adopt another training system, but we have dozens of existing models from CNTK (years of work) that we thought we'd bring via ONNX to ORT.    Hmmmm...

**Comment by ebarsoum** [comment]
Hi @JohnCraigPublic, which version of CNTK are you using?

**Comment by JohnCraigPublic** [comment]
ebarsoum - I'm now using CNTK 2.7 and 2.8rc to inference the networks.  Some may have been trained back on 2.5 and 2.6.    But I just recently re-trained one on 2.7, and it fails when converted to ONNX and attempted with ORT.

**Comment by spandantiwari** [comment]
From a quick look at the MaxPool node in the model, I am not clear on what is the issue with the ONNX model. This model is opset 9. If I am right, [this](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#MaxPool-10) is the spec for MaxPool for opset 9 (let me know if I am looking at the wrong spec). The spec says that `strides` should be `Stride along each spatial axis`. The input is standard 4D, i.e. `[Batch, Num_Channel, W, H]`, which suggests that there are two spatial axes. The length of `strides` attribute is two. 

@pranavsharma  - Could there be issue with something else in the model?

**Comment by spandantiwari** [comment]
Actually I see the issue now that @pranavsharma raised. The input to MaxPool op is actually 5-D with the first axis being marked `Sequence` axis. 

@JohnCraigPublic - I want to check if your model is intentionally using a Sequence of images in your model. Also, would it possible for you to share your CNTK model code, or possibly a shorter repro?

**Comment by JohnCraigPublic** [comment]
The model is AlexNet, just changed in 2 ways: 1) 1-channel images (grayscale) instead of 3, and 2) output stage changed to do regression and output a 12x1 vector.    The model was created with Brainscript -- do you want to see the Brainscript that created it?  I've posted the model (link above)

**Comment by liqunfu** [comment]
Hi @JohnCraigPublic, would you please share us your CNTK model file first? Not the Brainscript code.

**Comment by JohnCraigPublic** [comment]
Here is the link to the CNTK model.   

https://drive.google.com/open?id=1tSDrGqmIIXkuOAASm2k69vtMp0n3f7_Q

It would be fantastic if you could figure this out.  Thanks.

**Comment by liqunfu** [comment]
@JohnCraigPublic I have created a PR to fix this issue:
https://github.com/microsoft/CNTK/pull/3806
We are working on creating python wheels so you can use with your model.
Thanks

**Comment by JohnCraigPublic** [comment]
liqunfu -- Great!  So, is this fix available now?  How do I get it?   I'm using C++, so is it available via NuGet?

**Comment by JohnCraigPublic** [comment]
liqunfu -- Sorry, but I'm a bit new to this -- so does your PR#3806 mean that there is a new version I can test?    I use NuGet packages with C++.    Give me a hint -- or an estimate of when it might be available.  Thanks!

**Comment by liqunfu** [comment]
@JohnCraigPublic 
please use binary at: https://cntk.ai/nightly-windows.html. please choose binaries dated:
2.8-rc0.dev20200331
Thanks

**Comment by JohnCraigPublic** [comment]
liqunfu - Sorry but I don't see how to download and install for windows binaries from the Nightly build page.  Can you give me a hint.   I guess the "Nuget" mechanism doesn't see the new Nightly build yet?

**Comment by liqunfu** [comment]
@JohnCraigPublic  please use this link to download the nuget:
https://cntk.ai/Nuget/CNTK-Nuget-2.8.0-rc0.dev20200331.zip
and follow this to install the package:
https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio

Alternatively, you may download the 20200331 python wheel from https://cntk.ai/nightly-windows.html and convert your CNTK model with python script:
import cntk as C
model = C.Function.load("C:/cntk/GMU.model")
model.save("C:/cntk/GMU.onnx", C.ModelFormat.ONNX)

Cheers

**Comment by JohnCraigPublic** [comment]
Liqunfu - thank you, I was able to update to rc0.dev20200331
Now when I convert the original CNTL model to ONNX, I am able to CreateSession in ORT.  So that is progress!   I didn't yet try to figure out the input and try to inference it.  But I have a question:  I look at the ONNX model with Netron and I see that there is a "Sequence" dimension all the way thru the model -- in the input shape and also the output shape.  Remember, this model is a small modification to AlexNet and used on images.  So why is there a "sequence" involved?  The original CNTL model shows no "Sequence" in Netron.   Is this normal and OK that in ONNX a "sequence" dimension gets added?  Here is part of the display in Netron....

![Modified AlexNet to ONNX](https://user-images.githubusercontent.com/14355377/78463620-d855e780-7693-11ea-8eec-293cf4f2abcf.JPG)

**Comment by JohnCraigPublic** [comment]
I was abke to run the ONNX model in ORT!   For the sequence input the dim read as -1 and I set it to 1 to get things to work -- is that proper?   It seems to be working...  though I don't understand what the 'sequence' stuff is about....

**Comment by JohnCraigPublic** [comment]
Although the model runs and returns numbers, it seems to be gibberish.   Perhaps I'm feeding the input image in in correctly, but I've tried several permutations.  So, I'm getting worried that actually the model did *not* convert to ONNX properly.....
