### ISSUE TITLE
Lack of Output Data when running Tiny Yolo v3

### ISSUE THREAD

**Issue by hoaquocphan** [microsoft/onnxruntime#3227]
Hi All,

Currently, I'm porting TinyYolov3 on onnxruntime by CPP. https://github.com/hoaquocphan/Tiny_Yolo_v3
TinyYolov3 have input and output as below:
Input: **input_1**; **image_shape**
Output: **yolonms_layer_1**; **yolonms_layer_1:1**; **yolonms_layer_1:2**

This model have 2 inputs, so I create the two dimensions vector to 
```
std::vector<OrtValue *> input_tensor(input_node_names.size());
```
create tensor data as below:
```
CheckStatus(g_ort->CreateTensorWithDataAsOrtValue(memory_info, input_tensor_values.data(), input_tensor_size*sizeof(float), input_node_dims_input.data(), 4, ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT, &input_tensor[0]));
CheckStatus(g_ort->CreateTensorWithDataAsOrtValue(memory_info, input_tensor_values_shape.data(), 2*sizeof(float), input_node_dims_shape.data(), 2, ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT, &input_tensor[1]));
```
this model have 3 output,  so I create three dimensions vector
```
std::vector<OrtValue *> output_tensor(output_node_names.size());
```
the run command as below:
```
CheckStatus(g_ort->Run(session, NULL, input_node_names.data(), (const OrtValue* const*)input_tensor.data(), 2, output_node_names.data(), 3, output_tensor.data()));
```
when checking data of 3 outputs:
```
g_ort->GetTensorMutableData(output_tensor[0], (void**)&output1);
g_ort->GetTensorMutableData(output_tensor[1], (void**)&output2);
g_ort->GetTensorMutableData(output_tensor[2], (void**)&output3);
```

the output1 have 10211 values
```
 i: 0 output: 318.289368
...
 i: 10208 output: 0.000000
 i: 10210 output: 0.000001
```

output2 have 35 values
output 3 have no values.

the detail source code [here](https://github.com/hoaquocphan/Tiny_Yolo_v3)

there are 2 cases can lead to the wrong output
1/ the input value  is not right format
2/ the usage of **CreateTensorWithDataAsOrtValue**; **Run** is wrong.

So what wrong with my code? could anyone teach me?

**Comment by Li-chunming** [comment]
According to my understanding，you didn't feed the right input value.
1.For each input ,you need give a vector to describe the shape,like this:
`std::vector<int64_t> images_dim = { 1, 512, 512, 3 };`
2.Then you need create an array to store this input data ,make sure it has the correct size:
`std::array<float, 1 * 512 * 512 * 3> input_images_{};`
3.Then define a ORT Value(don't need to define fixed size here) and  create the tensor:
`Ort::Value images_input_tensor_{ nullptr };`
`images_input_tensor_ = Ort::Value::CreateTensor<float>(allocator_info, input_images_.data(), input_images_.size(), images_dim.data(), images_dim.size());`
4.As you can see ,each input requires the above operation, you have two inputs, so you should prepare two **Ort::Value** ,and put them to a global vector:
`std::vector<Ort::Value> ort_inputs;`
`ort_inputs.push_back(std::move(images_input_tensor_));
 ort_inputs.push_back(std::move(metas_input_tensor_));`
The **ort_inputs** is your correct input.

**Comment by Li-chunming** [comment]
Here is how I get the output:
1.Define the output vector,pass the results into it:
`std::vector<Ort::Value> ort_outputs = session.Run(Ort::RunOptions{ nullptr }, input_names.data(),
	ort_inputs.data(), ort_inputs.size(),
	output_names, 3);`
2.Then use `GetTensorMutableData`to get each output.
`float* detection_output_data = ort_outputs[0].GetTensorMutableData<float>();`
3.You can check the shape and type of each output:
`auto type_info = ort_outputs[0].GetTensorTypeAndShapeInfo();`
`std::vector<int64_t> shape = type_info.GetShape();`

**Comment by hoaquocphan** [comment]
Hi @Li-chunming 

I understand your explain, but My code use onnx version rel-1.0.0 so cannot reuse your code.

the model have 7 outputs, but you use only 2 outputs: ort_outputs[0] and ort_outputs[3], how about other output?
When check your code, I see that it have 3 Inputs and 7 Outputs, but the Mask R-CNN model have only 1 input and 4 output. so which model the code support to? I want to try to run to understand more.

Thank for your support

**Comment by hoaquocphan** [comment]
Hi @Li-chunming 

My [TinyYolo V2](https://github.com/hoaquocphan/Tiny_Yolo_v2) code can run successfully

but when I create the [TinyYolo V3](https://github.com/hoaquocphan/Tiny_Yolo_v3) code, it have the below error:
`Segmentation fault (core dumped) `
the erro because of checking output tensor from the vector
[tiny_yolo_v3.cpp#L467](https://github.com/hoaquocphan/Tiny_Yolo_v3/blob/3d715cc832fb3becb4ff167c87b90975221f7c4a/tiny_yolo_v3.cpp#L467)

So could you check and give me your comments (I use onnxruntime branch: **rel-1.0.0**)

**Comment by hoaquocphan** [comment]
Got solutions
