### ISSUE TITLE
Error running inference on converted tensorflow model

### ISSUE THREAD

**Issue by solarflarefx** [microsoft/onnxruntime#3229]
**Describe the bug**
I have created an ONNX model from a frozen graph in TensorFlow.  As a test I have run inference on this model by loading the pb file in python and tensorflow.  This works fine but when I try to feed the same input to the onnx model, I get an error:

Message=run(): incompatible function arguments. The following argument types are supported:
    1. (self: onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession, arg0: List[str], arg1: Dict[str, object], arg2: onnxruntime.capi.onnxruntime_pybind11_state.RunOptions) -> List[object]

Invoked with: <onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession object

**System information**
- OS Platform: Windows 10
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version: 1.2.0
- Python version: 3.7
- Visual Studio version (if applicable): 2019
- CUDA/cuDNN version: 10.1
- Tool to convert pb to onnx: tf2onnx 1.5.5
- Version of onnx: 1.6.0
- Version of TensorFlow: 1.14.0, gpu version

**To Reproduce**
I converted the model by using this link as a reference for converting my own model: https://github.com/onnx/tensorflow-onnx/blob/master/tutorials/ConvertingSSDMobilenetToONNX.ipynb

I was able to generate an onnx model for my own pb file, but when I run the sess.run command, I get the error that I have written above.

**Additional context**
Note that I was successfully able to run the example code and model in onnxruntime using the example link I have provided above, but my model does not seem to work properly.

I am wondering if this has anything to do with versions of everything matching properly: tensorflow, onnx, tf2onnx, onnxruntime.

I also used opset 11 for my export command.  Is there a guideline for which opset should be used?  My understanding is that you can use the latest opset if the runtime environment supports it.  Onnx Runtime 1.2.0 supports opset 11.

**Comment by jignparm** [comment]
The error message above seems to indicate that you are passing the arguments to the session.run() function incorrectly  -- could you  provide the code snippet you are using to run the model?

in case there's a problem with model conversion, could you also provide a link to the converted onnx model?

**Comment by jignparm** [comment]
@solarflarefx , as mentioned in https://github.com/onnx/tensorflow-onnx/issues/846, please see the code example below, which works fine to load your model and produce probabilities of 10 classes.

Feel free to close this issue.

###log
```
$ cat ort_load_model.py
import sys
import onnx
import onnxruntime as rt
import numpy as np
myfile = sys.argv[1]

sess = rt.InferenceSession(myfile)
input_name = sess.get_inputs()[0].name
output_name = sess.get_outputs()[0].name
scores = sess.run([output_name], {input_name: np.random.random((1,28,28,1)).astype(np.float32)})[0]
print (scores[0])


$ python ort_load_model.py Mnist_model.onnx
[4.25312319e-05 3.26818408e-04 4.42015764e-04 2.62277611e-02
 3.19961682e-02 2.90869642e-03 7.56456575e-06 1.19115185e-07
 9.37749505e-01 2.98845756e-04]
```

**Comment by solarflarefx** [comment]
Thank you :)

**Comment by tm-topnet** [comment]
Which is the code for 2 inputs ?
