### ISSUE TITLE
Cannot force to single threaded execution

### ISSUE THREAD

**Issue by addisonklinke** [microsoft/onnxruntime#3233]
**Describe the bug**
By default, `session.run()` uses all my computer's cores. I have tried unsuccessfully to modify the session options according to the Python API [documentation](https://microsoft.github.io/onnxruntime/python/api_summary.html#onnxruntime.SessionOptions) to limit use to a single thread only. Having control over the number of threads will allow easier integration with the rest of my application code 

**Urgency**
None

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source with DNNL provider
- ONNX Runtime version: 1.2.0
- Python version: 3.6.10
- Visual Studio version (if applicable): NA
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: CUDA 10.2 / cuDNN 7.3.1
- GPU model and memory: Nvidia GeForce GTX 1060 mobile (6 GB)

**To Reproduce**
Build with DNNL support from commit a02638eb

```
./build.sh --parallel --use_dnnl --enable_pybind --build_wheel 
```

Install the Python wheel

```
pip install build/Linux/Debug/dist/onnxruntime_dnnl-1.2.0-cp36-cp36m-linux_x86_64.whl
```

Run several iterations of a session with the Python API
```
import os
import onnxruntime

# Adjust session options
opts = onnxruntime.SessionOptions()
opts.intra_op_num_threads = 1
opts.inter_op_num_threads = 1
opts.execution_mode = onnxruntime.ExecutionMode.ORT_SEQUENTIAL

# Check environmental variables just in case
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OMP_WAIT_POLICY"] = "PASSIVE"

# Create and run session
ort_session = onnxruntime.InferenceSession('/path/to/model.onnx', sess_options=opts)
ort_session.set_providers(['DnnlExecutionProvider'])
ort_inputs = {ort_session.get_inputs()[0].name: ... }  # Add dummy tensor
for _ in range(1000):
    ort_outs = ort_session.run(None, ort_inputs)  # Monitor CPU with htop
```

**Expected behavior**
Only one thread should be engaged when monitoring CPU usage via `htop`

**Screenshots**
Proof of all threads running from `htop` output

![image](https://user-images.githubusercontent.com/39926682/76796578-fe6d2380-6788-11ea-9897-4bcf969674c8.png)

**Additional context**
I have the same issue when installing binaries from `pip` and using the default CPU execution provider. There seems to be no reason this behavior would be specific to my particular ONNX model

**Comment by pranavsharma** [comment]
This should've worked. Can you make sure the ```OMP_NUM_THREADS``` env variable is getting set correctly?

**Comment by pranavsharma** [comment]
Are you still seeing this issue? Did you verify the value of the env variable?

**Comment by addisonklinke** [comment]
I figured out that the env variable needs to be set _before_ the `onnxruntime` import. For instance,

```
import os
os.environ["OMP_NUM_THREADS"] = "1"
import onnxruntime

... rest of the code
```

Is it possible to have this behavior built into the `onnxruntime` package, so that intra/inter thread session options would have the expected effect? I think that would be less confusing for end users

**Comment by pranavsharma** [comment]
Glad your issue is resolved. We could possibly use omp_set_num_threads/omp_get_num_threads to set the number of openmp threads. However, this is not the only variable that impacts performance. The wait policy also matters significantly which cannot be changed programatically. Besides we're trying to get rid of openmp usage in ORT. Please re-open if you've any further questions.

**Comment by snnn** [comment]
https://github.com/microsoft/onnxruntime/issues/3099#issuecomment-610668766

**Comment by addisonklinke** [comment]
@pranavsharma I'm working on another project with ORT - this time I `pip installed` version 1.5.1. Monitoring via `htop`, it seems that the default thread behavior has changed since `v1.2.0` from all threads to half of available threads (in my case 6 of 12). 

By setting the `OMP_NUM_THREADS` environment variable to 1 before `import onnxruntime` like I mentioned before, I am able to throttle the engine back to just one core - which is good. However, if I set the environment variable to my max threads (12) and adjust the session options `intra/inter_op_num_threads` to match, I still only get 6 of 12 threads activated. Is there a new built-in limit that is preventing me from using 100% of my cores?

**Comment by snnn** [comment]
@addisonklinke Would you mind opening a new issue? I believe it's a new bug. We'll look into it.

**Comment by snnn** [comment]
@addisonklinke could you please provide more information? We can't reproduce the problem you described.  BTW, could you leave intra/inter_op_num_threads options to their default value? The official build was built with openmp, setting intra_op_num_threads doesn't help.

**Comment by addisonklinke** [comment]
@snnn I've installed the CPU Python binding from PyPI and setup my session with the following code

```python
import os
os.environ['OMP_NUM_THREADS'] = '12'
import onnxruntime

opts = onnxruntime.SessionOptions()
opts.inter_op_num_threads = 12
opts.intra_op_num_threads = 12
ort_session = onnxruntime.InferenceSession('model.onnx', sess_options=opts)
```

If I skip creating the `opts` object and setting `iter/intra_op_num_threads`, I am still stuck at the default half thread count of 6 even though I specified 12 with `OMP_NUM_THREADS`. Could you try reproducing with a model from the zoo? That way I could test the same one on my machine if the issue does not occur for you

**Comment by snnn** [comment]
Hi @addisonklinke 
I wonder if you would like try the following package instead:

https://pypi.org/project/onnxruntime-noopenmp/

It was built without openmp, so things would be simpler.  Please manually uninstall your existing onnxruntime package before installing the new one.

Then all you need to do is just creating an SessionOptions object and set intra_op_num_threads to the number you want. like:

```
opts = onnxruntime.SessionOptions()
opts.intra_op_num_threads = 12
ort_session = onnxruntime.InferenceSession('model.onnx', sess_options=opts)
```
It is simpler, so it will give us less surprise.

**Comment by Brightchu** [comment]
> I figured out that the env variable needs to be set _before_ the `onnxruntime` import. For instance,
> 
> ```
> import os
> os.environ["OMP_NUM_THREADS"] = "1"
> import onnxruntime
> 
> ... rest of the code
> ```
> 
> Is it possible to have this behavior built into the `onnxruntime` package, so that intra/inter thread session options would have the expected effect? I think that would be less confusing for end users

Thanks a lot. it works perfectly. this correlated problem has haunted me for a whole week. damn, thanks a lot.

**Comment by xor-xor** [comment]
> I am still stuck at the default half thread count of 6 even though I specified 12 with OMP_NUM_THREADS.

@addisonklinke are you by a chance on CPUs with hyper threading?
```
In [1]: import psutil

In [2]: psutil.cpu_count()
Out[2]: 64

In [3]: psutil.cpu_count(logical=False)
Out[3]: 32
```
I'm asking because I think that `htop` shows the former (i.e. logical ones) on its CPU meters, while OMP uses the latter (i.e. physical ones).
