### ISSUE TITLE
topK error

### ISSUE THREAD

**Issue by yangshao** [microsoft/onnxruntime#3239]
Hi, I'm using the following environment:

- pytorch 1.3.0
- opset 10
- onnxruntime 1.2.0
I'm trying to build an InferenceSession with an exported onnx model, but get the following error:
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(int64)' of input parameter (21) of operator (TopK) in node () is invalid.

I see some issues show that the 1.2.0 seems solve this problem, not sure why the error still happens. Thanks

**Comment by yangshao** [comment]
It seems that topK is supported in opset 11, when i switch to opset 11, the exportation complains following error:

RuntimeError: ONNX export failed on sort, which is not implemented for opset 11. Try exporting with other opset versions.

**Comment by pranavsharma** [comment]
int64 support in topk was added in opset 11. Hence your model will definitely not work if it is stamped with opset 10. 
CC'ing @spandantiwari for the export issue.

**Comment by spandantiwari** [comment]
@yangshao - Yes, exporting to opset 11 is the right thing to do. Sort should supported in opset 11. Here's the link: 
https://github.com/pytorch/pytorch/blob/6d488714a7f53fab16e34d7fdc00ab143d41ff33/torch/onnx/symbolic_opset11.py#L332

I am not sure why you are seeing an issue with sort. If you keep seeing this error can you share a small repro and your export code.
