### ISSUE TITLE
How can I run an LSTM model with negative shape for batch size?

### ISSUE THREAD

**Issue by anmour90** [microsoft/onnxruntime#3242]
Hi, I am pretty new to ONNX runtime and was trying to run inference on an LSTM model using the C APIs. I was able to run the [sample](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp) code with squeeze net. Then I replaced that model with my own LSTM model converted from Pytorch and it failed
```
/Users/runner/runners/2.165.0/work/1/s/onnxruntime/core/framework/tensor.cc:52 void onnxruntime::Tensor::Init(onnxruntime::MLDataType, const onnxruntime::TensorShape &, void *, onnxruntime::AllocatorPtr, ptrdiff_t) shape.Size() must >=0
```
I looked at my input and apparently the batch size is negative:
```
Number of inputs = 1
Input 0 : name=input
Input 0 : type=1
Input 0 : num_dims=3
Input 0 : dim 0=10
Input 0 : dim 1=-1
Input 0 : dim 2=64
```
If I manually changed the batch size to 1 in input, it gave me another error
```
not enough space: expected 1441151880758789120, got 2560
```
Any ideas that how I can resolve this issue are highly appreciated. Sorry I won't be able to share the model.

**Comment by anmour90** [comment]
I tried with my own LSTM model converted from Pytorch: 
[mylstm.onnx.zip](https://github.com/microsoft/onnxruntime/files/4345723/mylstm.onnx.zip)
and made some changes in `sharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp`:
```diff
diff --git a/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp b/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp
index 93aec5d0..de6c2aa0 100644
--- a/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp
+++ b/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp
@@ -50,7 +50,7 @@ int main(int argc, char* argv[]) {
 #ifdef _WIN32
   const wchar_t* model_path = L"squeezenet.onnx";
 #else
-  const char* model_path = "squeezenet.onnx";
+  const char* model_path = "mylstm.onnx";
 #endif
 
   printf("Using Onnxruntime C API\n");
@@ -118,11 +118,11 @@ int main(int argc, char* argv[]) {
   //*************************************************************************
   // Score the model using sample data, and inspect values
 
-  size_t input_tensor_size = 224 * 224 * 3;  // simplify ... using known dim values to calculate size
+  size_t input_tensor_size = 28 * 28;  // simplify ... using known dim values to calculate size
                                              // use OrtGetTensorShapeElementCount() to get official size!
 
   std::vector<float> input_tensor_values(input_tensor_size);
-  std::vector<const char*> output_node_names = {"softmaxout_1"};
+  std::vector<const char*> output_node_names = {"output"};
 
   // initialize input data with values in [0.0, 1.0]
   for (size_t i = 0; i < input_tensor_size; i++)
@@ -147,11 +147,11 @@ int main(int argc, char* argv[]) {
   // Get pointer to output tensor float values
   float* floatarr;
   CheckStatus(g_ort->GetTensorMutableData(output_tensor, (void**)&floatarr));
-  assert(std::abs(floatarr[0] - 0.000045) < 1e-6);
+  // assert(std::abs(floatarr[0] - 0.000045) < 1e-6);
 
   // score the model, and print scores for first 5 classes
-  for (int i = 0; i < 5; i++)
-    printf("Score for class [%d] =  %f\n", i, floatarr[i]);
+  // for (int i = 0; i < 5; i++)
+  //   printf("Score for class [%d] =  %f\n", i, floatarr[i]);
 
   // Results should be as below...
   // Score for class[0] = 0.000045
```
But had the same error:
```
Number of inputs = 1
Input 0 : name=input
Input 0 : type=1
Input 0 : num_dims=3
Input 0 : dim 0=1
Input 0 : dim 1=28
Input 0 : dim 2=28
not enough space: expected 2159856865918044160, got 3136
```

**Comment by skottmckay** [comment]
-1 isn't a valid dim_value for a dimension. If you want to have a dynamic value you either need to leave the dimension unset, or use a dim_param with a name. There may be a pytorch setting or approach you need to take to export a dynamic dimension correctly.

You could possibly manually fix the model if that's an option. Example python from hint on  https://github.com/onnx/onnx/issues/654 (may also be info on exporting correctly from pytorch in that issue) to make the first dimension dynamic.

```
import onnx
model = onnx.load_model(<path to model>)
model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = '?'
# m.graph.input[0].type.tensor_type.shape.dim[0].Clear() should also work
onnx.save_model(<path to updated model>)
```

I'm guessing the 'not enough space' error is because you're trying to create a tensor (probably a call to CreateTensorAsOrtValue or CreateTensorWithDataAsOrtValue) with input shape info that is invalid because it either has negative values in the shape, or you're providing an invalid length for the shape (length should be number of dimensions). The latter seems more likely given the 'expected' value seems fairly random.

**Comment by anmour90** [comment]
@skottmckay Thank you for the suggestion. When looking into the sample code, I found the input shape for my model is invalid. After changing the input shape, I was able to run the inference on my LSTM model. Closing now.

**Comment by jobpasin** [comment]
> @anmour90 Thank you for the suggestion. When looking into the sample code, I found the input shape for my model is invalid. After changing the input shape, I was able to run the inference on my LSTM model. Closing now.

I also facing a similar problem to yours. Could you clarify how you change the input shape and how does the input shape invalid (is it because the dynamic axes has a dimension size of -1)? Did you change it during exporting PyTorch model process or did you set a new input shape in c++ onnxruntime?

I tried the approach by @skottmckay but the dimension size still is -1 when loading in c++.

**Comment by skottmckay** [comment]
> I tried the approach by @skottmckay but the dimension size still is -1 when loading in c++.

Can you clarify what 'when loading in c++' means? Where did you see the -1 value? In something returned from onnxruntime or in something you were going to pass in to onnxruntime?

**Comment by jobpasin** [comment]
@skottmckay

Using the code from [this example](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp), and change the model to mine instead. 

The part where the code prints dimensions of input are shown as follows:
```
Number of inputs = 1
Input 0 : name=input
Input 0 : type=1
Input 0 : num_dims=3
Input 0 : dim 0=-1
Input 0 : dim 1=1
Input 0 : dim 2=161
```

I tried using a model with and without your code but the result is the same, dim 0 is still -1.
```
import onnx
model = onnx.load_model(<path to model>)
model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = '?'
# m.graph.input[0].type.tensor_type.shape.dim[0].Clear() should also work
onnx.save_model(<path to updated model>)
```

Note that the way I export onnx model is using `torch.onnx.export` as follows:

```
torch.onnx.export(model,  
                          dummy_input, 
                          export_name,
                          opset_version=10,  
                          input_names=input_names, 
                          output_names=output_names,  
                          dynamic_axes={'input': {0: 'sequential'},  # Set dynamic axes here
                                        'output': {0: 'sequential'}},
                          )
```

**Comment by skottmckay** [comment]
There are two different representations, and in the original issue (IIRC) the issue I mentioned was with the value set for the dimension in the model.

The value in the model can be one of 3 things. A dim_value (int), a dim_param (symbolic name) or unknown (neither dim_value nor dim_param). -1 is not a valid value for dim_value. In the model a symbolic dimension should either have a name in dim_param (e.g. 'batch') or be unknown.

Internally in ORT we process the model and handle cases where there is not a dim_value. We internally represent the dim_value as -1 in some data structures. That is what you're seeing returned in the example code as input_node_dims is a vector of int64.

If you were to look at the model in Netron you should be able to see the original values. Or you could print them out using python

```
for input in model.graph.input:
    print(input.name)
    for dim in input.type.tensor_type.shape.dim:
        if dim.HasField('dim_param'):
            print(dim.dim_param)
        elif dim.HasField('dim_value'):
            print(dim.dim_value)
        else:
            print('unknown')

```

**Comment by jobpasin** [comment]
Thanks for the info. I used the code you provide in python and the dimension I got is (sequential, 1, 161). 'sequential' is the name given in the dynamic axes parameter while exporting the model, which should be symbolic name I suppose? 

In c++, however, the dimension is shown as (-1, 1, 161) regardless (as shown in the comment above). Is this normal? If so, maybe the problem might be somewhere else instead.

**Comment by skottmckay** [comment]
It is normal for ORT to report that as the input shape. When creating the input you need to replace the -1 with a valid value though. 

In the example the dimensions are all concrete values, so the values in input_node_dims can be passed in directly.

https://github.com/microsoft/onnxruntime/blob/9a73c8f448612ca7c5f0635f3f128c3809f63b86/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp#L108

With a symbolic dimension you can't do that. ORT needs to know the actual dimensions to know how much data it is being given.

**Comment by DuckJ** [comment]
Have you solved this problem？ I also set the dynamic dimensions (width and height) when pytorch model into onnx, when I run [this sample](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp), the error is `terminate called after throwing an instance of 'Ort::Exception,
what()   tried creating tensor with negative value in shape
Aborted (core dumped)`
The input is 
`Number of inputs = 1
Input 0 : name=input
Input 0 : type=1
Input 0 : num_dims=4
Input 0 : dim 0=-1
Input 0 : dim 1=3
Input 0 : dim 2=-1
Input 0 : dim 3=-1`
So, I used the code below to change the shape in onnx, Netron seems shape has changed, but in [this sample](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp), input dims still is -1. I cannot modify the onnx by pytorch exporting, is there any other way? Anyone can help me,thanks.
 `import onnx
model = onnx.load_model(<path to model>)
model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = '?'
# m.graph.input[0].type.tensor_type.shape.dim[0].Clear() should also work
onnx.save_model(<path to updated model>)`

**Comment by skottmckay** [comment]
The error is from attempting to create input with a negative value for a dimension. When you create the input tensor you have to provide the actual values for all dimensions - i.e. dims 0, 2 and 3 need real values when calling the create tensor API so we know how big it is. This is separate to the model supporting symbolic values for those dimensions.

**Comment by DuckJ** [comment]
if I set the dynamic dimension in onnx, is there any way to run the sample in c++?
if i add the code before [this](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp#L108)， is it work?
```
input_node_dims[0] = 1
input_node_dims[1] = 3
input_node_dims[2] =1120
input_node_dims[3] =860
```

**Comment by skottmckay** [comment]
Yes.

In the example you referenced it's asking the model what the expected dimensions are for an input that does **not** have dynamic dimensions, so there are no -1 values in input_node_dims from this call: https://github.com/microsoft/onnxruntime/blob/0fa04bdc50a0dfbd3a3c99ced03aa824457516ae/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp#L72

If the input has dynamic dimensions like in your case you will get -1 when asking the **model** what dimensions the input has. You can attempt to execute the model with any non-zero value for those dimensions.

When you create the actual data for the input, it needs to have a concrete size, so any -1 value in input_node_dims needs to be replaced with the real value. We don't know how much memory to allocate for the input data without this information.

**Comment by DuckJ** [comment]
thanks，the problem has sloved
