### ISSUE TITLE
ONNX instability output on onnxruntime

### ISSUE THREAD

**Issue by briliantnugraha** [microsoft/onnxruntime#3247]
Hi guys, great job in making an engine to run the .onnx model. Btw, I want to ask a question about the ONNX inference.

I have encountered a serious problem where I try to compare both pytorch prediction output and ONNXRuntime output with my custom model, and I get different prediction outputs.
After that, I also tried to use a simple model provided by torchvision, and I find out that **even using a simple model for classification also produce dissimilar prediction outputs**.

Here is the script for the simple model:

```
import onnxruntime as rt
import numpy as np
import torch
import torchvision.models as models

pathmodel = "mobilenetv2.onnx"

print('f. Define mobilenet pytorch...')
model = models.mobilenet_v2(pretrained=True)
input_dummy = torch.randn(1, 3, 224, 224, requires_grad=True)
torch_out = model(input_dummy)#.cpu().numpy()
torch_out = torch_out.cpu().detach().numpy()

# Export the model
torch.onnx.export(model, input_dummy, pathmodel, verbose=False, 
                  input_names = ['input'],   # the model's input names
                  output_names = ['output'],
                  do_constant_folding=True, opset_version=10)


print('g. Define session onnxruntime...')
sess = rt.InferenceSession(pathmodel)


print('h. Define session input name...')
input1 = sess.get_inputs()[0].name


print('i. Run sess.run...')
onnxrt_out = sess.run(None, {input1: input_dummy.cpu().detach().numpy().astype(np.float32)})[0]


compare_out = np.allclose(torch_out, onnxrt_out)
print('compare_out: ', compare_out )
```
![image](https://tinyurl.com/yxxz6yoc)

You could see that the comparison output, and even the array output from the  first array (i.e. array[0]) is already different. 

Do you know why it is happening? How do we solve the problem?
Thanks in advance.

**System information**
- OS Platform and Distribution: Windows 10
- ONNX Runtime installed from: binary
- ONNX Runtime version: 1.6.0
- Python version: 3.6.5
- Visual Studio version: 2017
- CUDA/cuDNN version: 10.2/7.6
- GPU model and memory: GTX 1080 with 8GB of VRAM
@chiehpower

**Comment by briliantnugraha** [comment]
Hi, I solved this by _**adding model.eval() before input_dummy and relative tolerance 1e-3 on np.allclose**_

it will look like this
```
import onnxruntime as rt
import numpy as np
import torch
import torchvision.models as models

pathmodel = "mobilenetv2.onnx"

print('f. Define mobilenet pytorch...')
model = models.mobilenet_v2(pretrained=True)
model.eval()
input_dummy = torch.randn(1, 3, 224, 224, requires_grad=True)
torch_out = model(input_dummy)#.cpu().numpy()
torch_out = torch_out.cpu().detach().numpy()

# Export the model
torch.onnx.export(model, input_dummy, pathmodel, verbose=False, 
                  input_names = ['input'],   # the model's input names
                  output_names = ['output'],
                  do_constant_folding=True, opset_version=10)


print('g. Define session onnxruntime...')
sess = rt.InferenceSession(pathmodel)


print('h. Define session input name...')
input1 = sess.get_inputs()[0].name


print('i. Run sess.run...')
onnxrt_out = sess.run(None, {input1: input_dummy.cpu().detach().numpy().astype(np.float32)})[0]


compare_out = np.allclose(torch_out, onnxrt_out,  rtol=1e-03)
print('compare_out: ', compare_out )
```
and the opset_version needs to be 11 (to solve resize): [Dissimilar ONNX converted result](https://github.com/pytorch/pytorch/issues/22906)

Thank you~

**Comment by faxu** [comment]
@briliantnugraha Glad you were able to solve it. If you don't have any more questions, please go ahead and close the issue. Thanks!
