### ISSUE TITLE
num_dims does not match for input

### ISSUE THREAD

**Issue by FloP93** [microsoft/onnxruntime#3248]
**Describe the bug**
I have an input image Size 256x256 and a Model with the Input of my model being 1x3x256x256 (also in the session.InputMetadata)
But i get follwoing error:
Microsoft.ML.OnnxRuntime.OnnxRuntimeException: "[ErrorCode:Fail] Non-zero status code returned while running Node:  Status Message: X num_dims does not match W num_dims. X: {256,256,3} W: {64,3,7,7}"

64,3,7,7 is the layout of the second layer after 
![image](https://user-images.githubusercontent.com/34069654/76949668-31d6bc00-6909-11ea-8bb1-66697266c8fc.png)

I would be glad for every hint on sheding light on my problem.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): Nuget
- ONNX Runtime version: 0.5.1
- Python version: 3.6
- Visual Studio version (if applicable): 2017
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: 

**To Reproduce**
Describe steps/code to reproduce the behavior:
```
const string onnxModelPath = @"..\..\..\..\models\Stage4.onnx";
            using (var session = new InferenceSession(onnxModelPath))
            {
                List<double> scores = new List<double>();
                Tensor<float> t1 = ConvertImageToFloatData(bitmapImage);
                List<float> fl = new List<float>();

                //for(int x = 0; x< bitmapImage.)
                //var inputMeta = onnxSession.InputMetadata;
                var inputMeta = session.InputMetadata;
                var inputs = new List<NamedOnnxValue>()
                {
                NamedOnnxValue.CreateFromTensor<float>("input_1", t1)
                };
                using (var results = session.Run(inputs)) // Here the Error occures.
                {

                }
                return scores;
            }

        public static Tensor<float> ConvertImageToFloatData(Bitmap image)
        {
            Tensor<float> data = new DenseTensor<float>(new[] { image.Width, image.Height, 3 });
            for (int x = 0; x < image.Width; x++)
            {
                for (int y = 0; y < image.Height; y++)
                {
                    Color color = image.GetPixel(x, y);
                    data[x, y, 0] = color.B;
                    data[x, y, 1] = color.G;
                    data[x, y, 2] = color.R;
                }
            }
            return data;
        }
```

**Expected behavior**
Run a prediction on the Image

**Screenshots**

**Additional context**
The model was created with python 3.6 and FastAI using the Resnet34 Model for transfer-learning

**Comment by pranavsharma** [comment]
Your input X has a rank of 3, while W has a rank of 4. Just make sure the ranks are the same. See here https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/nn/conv_attributes.h#L134.

**Comment by FloP93** [comment]
Ok, thank you i changed the ConvertImageToFloatData Method to 
```
        public static Tensor<float> ConvertImageToFloatData(Bitmap image, double[] means, double[] std)
        {
            Tensor<float> data = new DenseTensor<float>(new[] { 1, 3, image.Width, image.Height });
            for (int x = 0; x < image.Width; x++)
            {
                for (int y = 0; y < image.Height; y++)
                {
                    Color color = image.GetPixel(x, y);
                    var red = (color.R - (float)means[0] * 255) / ((float)std[0] * 255);
                    var gre = (color.G - (float)means[1] * 255) / ((float)std[1] * 255);
                    var blu = (color.B - (float)means[2] * 255) / ((float)std[2] * 255);
                    data[0, 0, x, y] = red;
                    data[0, 1, x, y] = gre;
                    data[0, 2, x, y] = blu;
                }
            }
            return data;
        }
```

I was just really confused by the errormessage showing a problem with the second layer.
