### ISSUE TITLE
ios support

### ISSUE THREAD

**Issue by radikalliberal** [microsoft/onnxruntime#3250]
Hi, 
is it possible to now compile ORT for ios with arm? I have seen that the folder "build_ios" is on the gitignore list.
If not, can you make an estimation when it will be possible?

thanks

**Comment by pranavsharma** [comment]
We don't have any immediate plans for ios support. cc @faxu

**Comment by faxu** [comment]
This is on the backlog for something we'd like to have in the future, but no ETA. If you have a need, please feel free to make code or idea contributions based on your investigations. ORT does support Mac, so getting it to build for iOS may not be too difficult. However, getting it to run performantly on iOS would probably require more investigations and likely a new Execution Provider utilizing CoreML. We're unable to provide any ETAs on that support at this time, but if you share some more information on your use case, that can help us better understand the problem space for prioritization.

**Comment by radikalliberal** [comment]
thank you for the swift response. At my company, we are currently developing with onnxruntime and would like to deploy part of our software to ios. 
I suppose it might be more time-efficient for us to go directly with another framework, like core-ml.
Do you recommend trying to build ORT for ios beforehand? How much do you estimate the time expenditure for this task?

We, unfortunately, do not have the capacity to develop a new execution provider.

**Comment by pranavsharma** [comment]
> Do you recommend trying to build ORT for ios beforehand? How much do you estimate the time expenditure for this task?
Yes, if you can get a head start on making ORT build on ios, that would be great since then the only delta would be developing the core-ml execution provider. We've not worked on ios before, but given that ORT builds and runs on OSX, I would assume the effort won't be more than 2 weeks.

**Comment by faxu** [comment]
If using CoreML, I imagine you may still be using ONNX as the intermediary format for your model?Apple's converter is here: https://pypi.org/project/onnx-coreml/

**Comment by radikalliberal** [comment]
I'm going to try to compile for iOS. The problem is, I'm not familiar with development on Mac. I saw that you build native inside a Mac VM. My first attempt will be to crosscompile on linux. I'm not sure how useful this will be for your effort.
I will get back to you when I succeed.

**Comment by radikalliberal** [comment]
made a [pull request](https://github.com/microsoft/onnxruntime/pull/3298)

**Comment by gwang-msft** [comment]
iOS cross build on MacOS is enabled by https://github.com/microsoft/onnxruntime/pull/3699
