### ISSUE TITLE
Reproducing the release builds

### ISSUE THREAD

**Issue by smstec** [microsoft/onnxruntime#3251]
- ONNX Runtime version (you are using): N/A

The build instructions in BUILD.md only provide instructions for building a debug version of the library.  Are there instructions for reproducing the libraries provided in the release tgz files for Linux or the NuGet packages for Windows?

The instructions work great for the debug library.

**Comment by pranavsharma** [comment]
For CPU NuGet packages start [here](https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/azure-pipelines/nuget/cpu-esrp-pipeline.yml). This builds all flavors - Windows, Linux and Mac. For GPU start [here](https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/azure-pipelines/nuget/gpu-esrp-pipeline.yml).

**Comment by pranavsharma** [comment]
Feel free to re-open if this doesn't work. Thanks!
