### ISSUE TITLE
Inference speed ONNX vs. PB

### ISSUE THREAD

**Issue by solarflarefx** [microsoft/onnxruntime#3254]
**Describe the bug**
I am experimenting with a few models and platforms, and it seems that I am seeing variation on inference speed depending on the model format.  In both cases I am performing inference on the GPU, and inserting a python timer before and after the sess.run inferencing method.  

In one case, I am seeing that the ONNX model inferences 60-70 ms slower than the .pb model.

**System information**
- OS Platform: Windows 10
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version: 1.2.0, gpu version
- Python version: 3.7
- Visual Studio version (if applicable): 2019
- CUDA/cuDNN version: 10.1
- Tool to convert pb to onnx: tf2onnx 1.5.5
- Version of onnx: 1.6.0
- Version of TensorFlow: 1.14.0, gpu version

**Additional context**
I used the following command to create an ONNX model from a tensorflow frozen graph model (.pb).

python -m tf2onnx.convert --graphdef frozengraph.pb --output model.onnx --opset 11 --inputs input_layer:0 --outputs output_layer:0

**Additional Insight**
So I ran the performance profiler on different models and I am noticing some differences among the models I have been experimenting with.

The case I would expect is that "model_run" takes up the most time, but only a little more time than the SequentialExecutor, and finally followed by the layers themselves.

For example:
![Model1](https://user-images.githubusercontent.com/45402633/76991272-addbfe80-691f-11ea-981f-8383825a1273.PNG)

You can see in the above picture that: model_run > SequentialExecutor > network layers
However, there isn't much difference among them.

On the other hand, it seems that in some of the profiles, the model_run lasts much longer than both the SequentialExecute and network layers.  

For example:
![Model2](https://user-images.githubusercontent.com/45402633/76991287-b3394900-691f-11ea-87aa-b0e4c6c77b44.PNG)

Is this expected?  What would cause this to be the case?

**Additional Questions**
- Are there additional optimization commands I would need to specify?
- If I use the tool Netron to view the model graphs, I do notice that the onnx model seems to add a lot of transposes throughout.  I feel that this could be the source of the speed slowdown.
- Perhaps associated with the transposes, I am noticing that the dimensions listed for layers in the onnx model are reversed compared to the dimensions listed in the pb model.  Is this something inherently different between the two formats?

**Comment by pranavsharma** [comment]
Difficult to say without looking at the model. ORT doesn't implement all ops for GPU; we fallback to CPU implementations for them. That's one possible reason. Make sure you've turned on all optimizations (ORT_ENABLE_ALL). Also, have you looked at our [perf tuning guide](https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Perf_Tuning.md)?

**Comment by solarflarefx** [comment]
I took a quick look at the performance tuning, but I will go through it in more detail.

Does the profiler indicate the CPU vs GPU implementations?  I followed the Python API example on your performance tuning link:

-------------------------------
import onnxruntime as rt
so = rt.SessionOptions()
so.graph_optimization_level = rt.GraphOptimizationLevel.ORT_ENABLE_ALL
session = rt.InferenceSession(model, sess_options=so)
session.set_providers(['CUDAExecutionProvider'])
-------------------------------

Regarding my second screenshot, I am a bit confused about the model_run running for so long beyond the SequentialExecutor and the the network ops.  Could this be because there is a GPU/CPU copy going on?  Could something like this be happening after the last operation?

With the NHWC versus the NCHW, would this be only one change at the input level or could this affect a larger network with many more transposes added around various ops?

Regarding: 

> Also, the python API of ORT doesn't allow inputs to be copied to the GPU prior to execution, so ORT copies them on the fly as part of execution.

What would this translate into?  Additional overhead that would skew performance metrics?  Or would the profiler start when the elements are already in the GPU?

Finally, if converting from another model could the conversion tool make a difference?  For example I used tf2onnx, but I am wondering what would happen if I used another tool for conversion like keras2onnx?  Or perhaps use the OLive tool?

Would it be useful to use another tool like TensorRT to further optimize the network?

**Comment by yufenglee** [comment]
ORT GPU is asynchronous. That's why your second screenshot looks like that. You need to set env variable cuda_launch_blocking to 1 before profiling on GPU.

ORT supports NCHW. The converter convert your NHWC format to NCHW by adding transpose. It will leads bad performance.  keras2onnx actually can optimize most of the transpose out. You can try it out if you model can be converted with keras2onnx.

For TensorRT, you can try building with TensorRT from source

Our Python API and C# API introduces a little overhead, but it is should be expected small.

**Comment by solarflarefx** [comment]
Thanks for the reply.  Ok I will experiment a bit with keras2onnx and TensorRT.

Just so I am comparing apples with apples, is there a way to profile inference on .pb files?  I realize this is sort of out of scope of onnx runtime, but at the same time my issue is that I am seeing a performance difference.

**Comment by yufenglee** [comment]
@solarflarefx you can use TensorBoard to profile inference of TensorFlow.
