### ISSUE TITLE
DLL version number of current release is 0.0.0.0

### ISSUE THREAD

**Issue by JohannesBrx** [microsoft/onnxruntime#3264]
**Describe the bug**
In the currently released Windows x64 build `onnxruntime-win-x64-1.2.0.zip`, the DLL version number of `onnxruntime.dll` is set to 0.0.0.0 instead to 1.2.x.x.

In addition to that, the version number of local builds of onnxruntime.dll is also set to 0.0.0.0.

**To Reproduce**
Download https://github.com/microsoft/onnxruntime/releases/download/v1.2.0/onnxruntime-win-x64-1.2.0.zip. Extract `onnxruntime.dll` and view the Windows Explorer properties. The file version number will be 0.0.0.0.

In local builds, open `onnxruntime.dll` and view the Windows Explorer properties of that file.

**Expected behavior**
I would expect the version number of `onnxruntime.dll` to be something like 1.2.x.x.

Local builds should at least contain the first two version numbers.

**Screenshots**
Sorry, only German screenshot:
![grafik](https://user-images.githubusercontent.com/8805876/77057154-d1608100-69d3-11ea-90c0-b4249cbc1d1d.png)

**Comment by faxu** [comment]
Thanks for reporting. We'll look into fixing this in the next release. Does it impact your usage?

**Comment by pranavsharma** [comment]
@martinb35 @orilevari can one of you take a look? thanks!

**Comment by orilevari** [comment]
This has been resolved with this PR: https://github.com/microsoft/onnxruntime/pull/3187

**Comment by JohannesBrx** [comment]
Ok, thank you!
But how could I set the version number (e.g., 1.2) in local builds?

**Comment by omeyer1969** [comment]
> Ok, thank you! But how could I set the version number (e.g., 1.2) in local builds?

Did you ever found out how to set the version number? For me it doesn't work with version 1.13.1.
