### ISSUE TITLE
add dimension for input_tensor_values

### ISSUE THREAD

**Issue by hoaquocphan** [microsoft/onnxruntime#3266]
Hi All,

I'm porting tiny yolo v3 to onnxruntime by C++. I have some unclear points as below:

+ My code flow:
```
const char* mat_out = "mat_out.jpg";
stbi_uc * img_data_new = stbi_load(mat_out, &img_sizex, &img_sizey, &img_channels, STBI_default);
struct S_Pixel
{
        unsigned char RGBA[3];
};
const S_Pixel * imgPixels(reinterpret_cast<const S_Pixel *>(img_data_new));
std::vector<float> input_tensor_values(input_tensor_size);
size_t offs = 0;
for (size_t  c = 0; c < 3; c++){
        for (size_t  y = 0; y < img_sizey; y++){
            for (size_t  x = 0; x < img_sizex; x++, offs++){
                const int val(imgPixels[y * img_sizex + x].RGBA[c]);
                input_tensor_values[offs] = ((float)val)/255;
            }
       }
 }
CheckStatus(g_ort->CreateTensorWithDataAsOrtValue(memory_info, input_tensor_values.data(), input_tensor_size*sizeof(float), input_node_dims_input.data(), 4, ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT, &input_tensor_image));
```
+ in the preprocessing steps of [tinyYolov3](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny_yolov3)
``` image_data = np.expand_dims(image_data, 0)```
+ As my understanding (from my friend) 
the input image have 3 dimension: **(3x416x416)**
but the required input is  **(1x3x416x416)**
=> so we need to add 1 dimension by the expand_dims function. 

**question:**
1/ is it necessary to add 1 dimension because i think that **(3x416x416)** and **(1x3x416x416)** are the same?
2/ in my code, all image was write to  one dimension vector **input_tensor_values**, so is it necessary to add dimension to the data in one dimension vector **input_tensor_values**?
3/  how does onnx know the  **input_tensor_values** is 1 dimension or 3 dimensions or 4 dimensions?
4/ if necessary, could your give me an example about the add dimension in C++? or if my code is correct (don't need to add dimension) please give me a comment to let me know that.

So please help me to feedback these above questions.
Thanks

**Comment by hariharans29** [comment]
1) It depends on what the model expects. If the model expects, 1x3x416x416, you would have to feed in the tensor with the extra dimension even though "content-wise"  1x3x416x416 and 3x416x416 are still the same.
 
For 2, 3, 4 - I guess the questions boil down to "how to create a tensor (OrtValue) of a specific shape ?". Please take a look at this and follow the flow from there - https://github.com/microsoft/onnxruntime/blob/baa0697982cdda2fbfa107127efbdb4947143e4b/samples/c_cxx/MNIST/MNIST.cpp#L20.

From the above code, it should be clear how to add the extra dimension in c++ (your question 4), you just add it to the shape array the contructed Ortvalue now would have the extra dimension.
