### ISSUE TITLE
Building python binding without enabling unit tests

### ISSUE THREAD

**Issue by smuzaffar** [microsoft/onnxruntime#3279]
**Is your feature request related to a problem? Please describe.**
Looks like python binding are only built if unit tests are enabled ( https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L862-L873 ). Can we build python part without building build unit tests? 

**System information**
- 1.0.0 and above

**Describe the solution you'd like**
Would be nice to get the python part without unit tests.

**Comment by pranavsharma** [comment]
This is an open source project. We encourage contributions. Thanks!
