### ISSUE TITLE
Question about input dimensions using C++ API

### ISSUE THREAD

**Issue by danperazzo** [microsoft/onnxruntime#3289]
Hello, I was trying to load a model and perform inferences with the C++ API. However, my model has some input dimensions that are dynamic (ie., dim i = -1). I checked the C++ examples and they assume a static input. How should I proceed? Thanks for the assistance!

**Comment by hoaquocphan** [comment]
Hi, @danperazzo 
 
I have the same issue as your in the past.
the "-1" mean dynamic value, this mean you should update it.
ex:
```
if (dim[i] == -1)
{
    dim[i] = 416; // this value base on your required input
}
```

**Comment by danperazzo** [comment]
Ok, thanks @hoaquocphan !
