### ISSUE TITLE
[Q] how to run test_file with onnxruntime_exec ?

### ISSUE THREAD

**Issue by chunseoklee** [Microsoft/onnxruntime#329]
commit : 260639c3276719ebfa9ffe05ee04a44c262ed182
I have (cross-)built onnxruntime_exec binary for odroid-xu4(arm ubuntu 16.04).
When I try to run onnx model file(
https://s3.amazonaws.com/download.onnx/models/opset_9/resnet50.tar.gz), it shows the following error. 

```
/onnxruntime_exec -m model.onnx -t ./test_data_2.npz
2019-01-15 04:25:03.793697147 [W:onnxruntime:Default, graph.cc:2178 CleanUnusedInitializers] gpu_0/imagenet1k_blobs_queue_f22e83c9-22cd-4a8b-a66d-113af6b832b4_0 exists in this graph's initializers but it is not used by any node
'model.onnx' loaded successfully.
Done loading model: model.onnx
Execution Status: DATA_LOADING_FAILURE
Exception msg: Not enough features in sample.
```

**Comment by snnn** [comment]
Don't use onnxruntime_exec. Use onnx_test_runner.
[https://github.com/Microsoft/onnxruntime/blob/master/docs/Model_Test.md
](https://github.com/Microsoft/onnxruntime/blob/master/docs/Model_Test.md)

BTW. opset 9 belongs to ONNX 1.4, which is not released yet. You'd better to use opset 8.

**Comment by snnn** [comment]
For cross-building onnx_test_runner, you can follow this:
https://github.com/Microsoft/onnxruntime/blob/master/BUILD.md#cross-compiling-on-linuxfaster

onnxruntime_exec is a deprecated tool.

**Comment by snnn** [comment]
Close this issue as the original problem is gone.  See: #340

Please feel free to open a new one for your new problems.
