### ISSUE TITLE
pytorch Upsampling with align_corners = True

### ISSUE THREAD

**Issue by alekk** [microsoft/onnxruntime#3292]
**Describe the bug**
On MacOS, the pytorch Upsample layer:

`torch.nn.Upsample(scale_factor=2,  mode='bilinear',  align_corners = True)`

does not seem to work well with `onnxruntime`, even if properly exported/tested with `torch.onnx` and `onnx`. The option `align_corners = False` seems to be working fine. I have also tried `opset_version=10`.

**Urgency**
It seems to be working on Windows. We are planning to release a Mac version of your software in May 2020 -- this would be fantastic if this could be fixed.

**System information**
- OS Platform and Distribution: MacOS Sierra 10.12.6
- ONNX Runtime version: 0.5.0
- Python version: 3.6.9
- CUDA/cuDNN version: None
- GPU model and memory: None

**To Reproduce**

```python
#create a simple function
import torch
class simple(torch.nn.Module):
    def __init__(self):
        super(simple, self).__init__()
        self.up = torch.nn.Upsample(scale_factor=2, 
                                    mode='bilinear', 
                                    align_corners = True)
    def forward(self, x):
        output = self.up(x)
        return output

# sanity check
net = simple()
batch_size, channel, dimx, dimy = 2,3,5,7
batch_input = torch.zeros(batch_size, channel, dimx, dimy).float()
output = net(batch_input)


#export the model
import torch.onnx
torch.onnx.export(net,            # model being run
                  batch_input,    # model input (or a tuple for multiple inputs)
                  "model.onnx",   # where to save the model (can be a file or file-like object)
                  export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=11,          # the ONNX version to export the model to
                  do_constant_folding=True,  # whether to execute constant folding for optimization
                  input_names = ['input'],   # the model's input names
                  output_names = ['output'], # the model's output names
                  dynamic_axes={'input' : {0 : 'batch_size'},    # variable lenght axes
                                'output' : {0 : 'batch_size'}})

#test the model
import onnx
onnx_model = onnx.load("model.onnx")
onnx.checker.check_model(onnx_model)

import onnxruntime
ort_session = onnxruntime.InferenceSession("model.onnx")
```
 The above throw an error at the very last step:

> RuntimeError: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from model.onnx failed:This is an invalid model. Error in Node: : Node () has input size 4 not in range [min=2, max=2].

**Expected behavior**
It seems to be working find on Windows 10.

**Comment by emilianavt** [comment]
I remember having some issues exporting networks with Upsample layers for use with onnxruntime on pytorch 1.3.0 and had to patch it a bit. Since 1.4.0, it seems to be working fine. Could that be related to your issue?

**Comment by faxu** [comment]
@alekk can you try the latest version of PyTorch to export your model and let us know if you still see the issue?

**Comment by alekk** [comment]
On MacOS Sierra 10.12.6
=================
1. **latest pytorch stable version:**
python: 3.6.9
numpy: 1.18.1
torch:  1.4.0
onnx:  1.6.0
onnxruntime:  0.5.0

The code reproduced in the first post is failing (for `opset_version=9,10,11,12`)

2. **nightly build**:
torch:  1.6.0.dev20200401
onnx:  1.6.0
onnxruntime:  0.5.0

The code reproduced in the first post is failing (for `opset_version=9,10,11,12`)


Only thing that reliably works on MacOS is Upsampling with the option: `mode='nearest'`

**Comment by hariharans29** [comment]
Have you tried this with one of the latest releases - 1.0+ ?
