### ISSUE TITLE
How to run a quantization model on GPU？

### ISSUE THREAD

**Issue by dongzhen123** [microsoft/onnxruntime#3294]
I use session.set_providers(['CUDAExecutionProvider'])   but run slow and the program not use gpu actually.
the quantization model mainly contain qLinearConv op

**Comment by yufenglee** [comment]
We don't have support of QLinearConv on GPU yet, but we just optimized our CPU implementation of QLinearConv and it gets way faster. Please sync to master and try it. 

What's your model and scenario? And what makes you need to run it on GPU?

**Comment by dongzhen123** [comment]
> @dongzhen123 We don't have support of QLinearConv on GPU yet, but we just optimized our CPU implementation of QLinearConv and it gets way faster. Please sync to master and try it.
> 
> What's your model and scenario? And what makes you need to run it on GPU?
I want to eval the quantization model on imagenet val,so I want to make this process faster with the use of gpu,but thank you all the same.

**Comment by dongzhen123** [comment]
> @dongzhen123 We don't have support of QLinearConv on GPU yet, but we just optimized our CPU implementation of QLinearConv and it gets way faster. Please sync to master and try it.
> 
> What's your model and scenario? And what makes you need to run it on GPU?

I run the quantization model(resnet50)  use QLinearOps with static input quantization on imagenet val,and the acc is much lower than normal.

Normally the acc of quantization model is a litter bit lower than the float model,but use onnxruntime eval the acc,there maybe something wrong happen and the acc much lower.

I take the first conv1 output to have a look carefully,I find some value different with my own calculate
and the difference originated from the way round.

But I still don't know whether the way round cause the acc much lower.

**Comment by dongzhen123** [comment]
I have solved it
