### ISSUE TITLE
Nearest neighbour upsampling very slow with opset11

### ISSUE THREAD

**Issue by emilianavt** [microsoft/onnxruntime#3297]
**Describe the bug**
Nearest neighbour upsampling is very fast (around 5 times faster) compared to bilinear with opset8 when doing inference on CPU. With opset11 it is 5 times slower than bilinear.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.2.0
- Python version: 3.7.3
- Visual Studio version (if applicable): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: running on CPU
- GPU model and memory: running on CPU (AMD Ryzen Threadripper 2950X)

**To Reproduce**
Describe steps/code to reproduce the behavior:

Code:

    from pathlib import Path
    import numpy as np
    import time
    import torch
    import torch.nn as nn
    import onnxruntime

    class UpsampleTest(nn.Module):
        def __init__(self, mode, corners):
            super(UpsampleTest, self).__init__()
            self.upsample = nn.Sequential(
                nn.Upsample(size=(14,14), mode=mode, align_corners=corners),
                nn.Upsample(size=(28,28), mode=mode, align_corners=corners),
                nn.Upsample(size=(56,56), mode=mode, align_corners=corners)
            )
        def forward(self, x):
            return self.upsample(x)

    def run_test(mode, corners, opset, runs=10000):
        print("============================")
        print(f"Testing mode={mode}, align_corners={corners}, opset={opset}, runs={runs}")
        model = UpsampleTest(mode, corners)
        sample = torch.randn(1, 256, 7, 7, requires_grad=True)
        sample_out = model(sample)
        torch.onnx.export(model, sample, f"upsample_test_{mode}_{corners}_{opset}.onnx", example_outputs=sample_out, export_params=True, opset_version=opset, do_constant_folding=True, input_names=['input'], output_names=['output'], dynamic_axes={'input':{0:'batch_size'},'output':{0:'batch_size'}})
        size = Path(f"upsample_test_{mode}_{corners}_{opset}.onnx").stat().st_size
        print(f"Exported ({size} bytes), running test...")

        options = onnxruntime.SessionOptions()
        options.inter_op_num_threads = 1
        options.intra_op_num_threads = 4
        options.execution_mode = onnxruntime.ExecutionMode.ORT_SEQUENTIAL
        options.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_ENABLE_ALL
        session = onnxruntime.InferenceSession(f"upsample_test_{mode}_{corners}_{opset}.onnx", sess_options=options)

        x = torch.randn(1,256,7,7).numpy()

        total_time = 0.
        for i in range(runs):
            start = time.perf_counter()
            y = session.run([], {'input': x})
            total_time += time.perf_counter() - start
        avg_time = 1000. * (total_time / runs)
        print(f"Average duration: {avg_time:.2f}ms")

    print(f"Versions:\n- pytorch: {torch.__version__}\n- numpy: {np.__version__}\n- onnxruntime: {onnxruntime.__version__}")
    run_test("nearest", None, 8)
    run_test("bilinear", False, 8)
    run_test("nearest", None, 11)
    run_test("bilinear", False, 11)
    run_test("bilinear", True, 11)

Output:

    Versions:
    - pytorch: 1.4.0
    - numpy: 1.18.2
    - onnxruntime: 1.2.0
    ============================
    Testing mode=nearest, align_corners=None, opset=8, runs=10000
    env/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py:246: UserWarning: You are trying to export the model with onnx:Upsample for ONNX opset version 8. This operator might cause results to not match the expected results by PyTorch.
    ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
    We recommend using opset 11 and above for models using this operator.
      "" + str(_export_onnx_opset_version) + ". "
    Exported (352 bytes), running test...
    Average duration: 0.56ms
    ============================
    Testing mode=bilinear, align_corners=False, opset=8, runs=10000
    Exported (349 bytes), running test...
    Average duration: 2.62ms
    ============================
    Testing mode=nearest, align_corners=None, opset=11, runs=10000
    Exported (1409 bytes), running test...
    Average duration: 13.41ms
    ============================
    Testing mode=bilinear, align_corners=False, opset=11, runs=10000
    Exported (1430 bytes), running test...
    Average duration: 2.58ms
    ============================
    Testing mode=bilinear, align_corners=True, opset=11, runs=10000
    Exported (1415 bytes), running test...
    Average duration: 2.61ms

**Expected behavior**
Nearest neighbour upsampling should be about as fast with opset11 as with opset8, not overall 23 times slower.

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by skottmckay** [comment]
Based on this output I would have assumed that the opset 8 version wasn't actually doing the interpolation. As such, it would be fast but incorrect. Is that not the case?

> env/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py:246: UserWarning: You are trying to export the model with onnx:Upsample for ONNX opset version 8. This operator might cause results to not match the expected results by PyTorch.
> ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
> We recommend using opset 11 and above for models using this operator.
>

**Comment by tracysh** [comment]
@skottmckay This may be related to the use_nearest_2x_optimization_ path in upsample.h. This isn't enabled in opset 11 because more of the options need to be checked to use the existing fast path. The NCHWc optimizer checks for the needed options to use its fast path.

**Comment by emilianavt** [comment]
> Based on this output I would have assumed that the opset 8 version wasn't actually doing the interpolation. As such, it would be fast but incorrect. Is that not the case?

Even if that case does not work correctly, nearest neighbour would still be more than five times slower than bilinear in opset 11. However, you can confirm that even in the first case the upsampling is working correctly using this modified script:

    from pathlib import Path
    import numpy as np
    import time
    import torch
    import torch.nn as nn
    import onnxruntime

    class UpsampleTest(nn.Module):
        def __init__(self, mode, corners):
            super(UpsampleTest, self).__init__()
            self.upsample = nn.Sequential(
                nn.Upsample(size=(14,14), mode=mode, align_corners=corners),
                nn.Upsample(size=(28,28), mode=mode, align_corners=corners),
                nn.Upsample(size=(56,56), mode=mode, align_corners=corners)
            )   
        def forward(self, x): 
            return self.upsample(x)

    x = torch.randn(1,256,7,7).numpy()
    results = {}

    def run_test(mode, corners, opset, runs=10000):
        global results
        global x
        print("============================")
        print(f"Testing mode={mode}, align_corners={corners}, opset={opset}, runs={runs}")
        model = UpsampleTest(mode, corners)
        sample = torch.randn(1, 256, 7, 7, requires_grad=True)
        sample_out = model(sample)
        torch.onnx.export(model, sample, f"upsample_test_{mode}_{corners}_{opset}.onnx", example_outputs=sample_out, export_params=True, opset_version=opset, do_constant_folding=True, input_names=['input'], output_names=['output'], dynamic_axes={'input':{0:'batch_size'},'output':{0:'batch_size'}})
        size = Path(f"upsample_test_{mode}_{corners}_{opset}.onnx").stat().st_size
        print(f"Exported ({size} bytes), running test...")

        options = onnxruntime.SessionOptions()
        options.inter_op_num_threads = 1 
        options.intra_op_num_threads = 4 
        options.execution_mode = onnxruntime.ExecutionMode.ORT_SEQUENTIAL
        options.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_ENABLE_ALL
        session = onnxruntime.InferenceSession(f"upsample_test_{mode}_{corners}_{opset}.onnx", sess_options=options)

        total_time = 0.
        for i in range(runs):
            start = time.perf_counter()
            y = session.run([], {'input': x}) 
            results[f"upsample_test_{mode}_{corners}_{opset}"] = y 
            total_time += time.perf_counter() - start
        corner = np.array(results[f'upsample_test_{mode}_{corners}_{opset}'][0])
        print(f"Output shape: {corner.shape}")
        corner = corner[0,0,0:16:4,0:16:4]
        print(f"Upper corner (stride=4 for brevity):\n{corner}")
        avg_time = 1000. * (total_time / runs)
        print(f"Average duration: {avg_time:.2f}ms")

    print(f"Versions:\n- pytorch: {torch.__version__}\n- numpy: {np.__version__}\n- onnxruntime: {onnxruntime.__version__}")
    print("============================")
    print(f"Upper corner (x[0,0,0:2,0:2]):\n{x[0,0,0:2,0:2]}")
    run_test("nearest", None, 8)
    run_test("bilinear", False, 8)
    run_test("nearest", None, 11) 
    run_test("bilinear", False, 11) 
    run_test("bilinear", True, 11) 

Here is the output:

    Versions:
    - pytorch: 1.4.0
    - numpy: 1.18.2
    - onnxruntime: 1.2.0
    ============================
    Upper corner (x[0,0,0:2,0:2]):
    [[-0.20079376 -2.0216615 ]
     [-1.6920412   0.6700317 ]]
    ============================
    Testing mode=nearest, align_corners=None, opset=8, runs=10000
    env/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py:246: UserWarning: You are trying to export the model with onnx:Upsample for ONNX opset version 8. This operator might cause results to not match the expected results by PyTorch.
    ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
    We recommend using opset 11 and above for models using this operator. 
      "" + str(_export_onnx_opset_version) + ". "
    Exported (352 bytes), running test...
    Output shape: (1, 256, 56, 56) 
    Upper corner (stride=4 for brevity):
    [[-0.20079376 -0.20079376 -2.0216615  -2.0216615 ]
     [-0.20079376 -0.20079376 -2.0216615  -2.0216615 ]
     [-1.6920412  -1.6920412   0.6700317   0.6700317 ]
     [-1.6920412  -1.6920412   0.6700317   0.6700317 ]]
    Average duration: 0.67ms
    ============================
    Testing mode=bilinear, align_corners=False, opset=8, runs=10000
    Exported (349 bytes), running test...
    Output shape: (1, 256, 56, 56) 
    Upper corner (stride=4 for brevity):
    [[-0.20079376 -1.1112276  -2.0216615   0.48527098]
     [-0.94641745 -0.81111616 -0.67581487  0.04495898]
     [-1.6920412  -0.5110047   0.6700317  -0.39535305]
     [-1.1086332  -0.19004475  0.72854364 -0.2877992 ]]
    Average duration: 3.36ms
    ============================
    Testing mode=nearest, align_corners=None, opset=11, runs=10000
    Exported (1409 bytes), running test...
    Output shape: (1, 256, 56, 56) 
    Upper corner (stride=4 for brevity):
    [[-0.20079376 -0.20079376 -2.0216615  -2.0216615 ]
     [-0.20079376 -0.20079376 -2.0216615  -2.0216615 ]
     [-1.6920412  -1.6920412   0.6700317   0.6700317 ]
     [-1.6920412  -1.6920412   0.6700317   0.6700317 ]]
    Average duration: 16.06ms
    ============================
    Testing mode=bilinear, align_corners=False, opset=11, runs=10000
    Exported (1430 bytes), running test...
    Output shape: (1, 256, 56, 56) 
    Upper corner (stride=4 for brevity):
    [[-0.20079376 -0.48530433 -1.2250319  -1.0675387 ]
     [-0.43380114 -0.6161892  -1.090398   -0.8826648 ]
     [-1.0396204  -0.9564897  -0.74035    -0.40199247]
     [-1.3699216  -1.087751   -0.35410735  0.04318229]]
    Average duration: 3.38ms
    ============================
    Testing mode=bilinear, align_corners=True, opset=11, runs=10000
    Exported (1415 bytes), running test...
    Output shape: (1, 256, 56, 56) 
    Upper corner (stride=4 for brevity):
    [[-0.20079376 -0.9953541  -1.7899147  -0.38588974]
     [-0.85152    -0.8495933  -0.8476664  -0.23719151]
     [-1.502246   -0.7038321   0.09458197 -0.08849339]
     [-1.2979308  -0.43754163  0.4228475   0.01278109]]
    Average duration: 3.39ms

The upsampling is clearly happening as intended even for opset 8 nearest neighbour.

> @skottmckay This may be related to the use_nearest_2x_optimization_ path in upsample.h. This isn't enabled in opset 11 because more of the options need to be checked to use the existing fast path. The NCHWc optimizer checks for the needed options to use its fast path.

Thank you. This sounds like a plausible cause for this behaviour.

**Comment by skottmckay** [comment]
> @skottmckay This may be related to the use_nearest_2x_optimization_ path in upsample.h. This isn't enabled in opset 11 because more of the options need to be checked to use the existing fast path. The NCHWc optimizer checks for the needed options to use its fast path.

You're correct that path isn't being taken. I have changes to do the same check in Upsample, but it still won't help this model as the Resize node has the 'sizes' input (with values of {1, 256, 28 ,28}. 

Is it valid to allow the optimization if we convert sizes to scales and the last two dims in scales are a multiple of 2? In this case input is {1, 256, 7, 7} so scales would be {1, 1, 4, 4}.

**Comment by emilianavt** [comment]
Thank you, with 1.3.0 this issue is solved!

    Versions:
    - pytorch: 1.4.0
    - numpy: 1.18.2
    - onnxruntime: 1.3.0
    ============================
    Testing mode=nearest, align_corners=None, opset=8, runs=500
    env/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py:246: UserWarning: You are trying to export the model with onnx:Upsample for ONNX opset version 8. This operator might cause results to not match the expected results by PyTorch.
    ONNX's Upsample/Resize operator did not match Pytorch's Interpolation until opset 11. Attributes to determine how to transform the input were added in onnx:Resize in opset 11 to support Pytorch's behavior (like coordinate_transformation_mode and nearest_mode).
    We recommend using opset 11 and above for models using this operator.
      "" + str(_export_onnx_opset_version) + ". "
    Exported (352 bytes), running test...
    Average duration: 0.75ms
    ============================
    Testing mode=bilinear, align_corners=None, opset=8, runs=500
    env/lib/python3.7/site-packages/torch/nn/functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
      "See the documentation of nn.Upsample for details.".format(mode))
    Exported (349 bytes), running test...
    Average duration: 3.44ms
    ============================
    Testing mode=bilinear, align_corners=False, opset=8, runs=500
    Exported (349 bytes), running test...
    Average duration: 3.38ms
    ============================
    Testing mode=nearest, align_corners=None, opset=11, runs=500
    Exported (1409 bytes), running test...
    Average duration: 0.63ms
    ============================
    Testing mode=bilinear, align_corners=None, opset=11, runs=500
    Exported (1430 bytes), running test...
    Average duration: 3.35ms
    ============================
    Testing mode=bilinear, align_corners=False, opset=11, runs=500
    Exported (1430 bytes), running test...
    Average duration: 3.36ms
    ============================
    Testing mode=bilinear, align_corners=True, opset=11, runs=500
    Exported (1415 bytes), running test...
    Average duration: 3.32ms
