### ISSUE TITLE
Model with multiple inputs in ONNXRuntime C++

### ISSUE THREAD

**Issue by danperazzo** [microsoft/onnxruntime#3299]
Hello guys, how can I run a model that uses multiple inputs? The ONNX Runtime C++ API has examples only for 1 input ( `auto output_tensors = session.Run(Ort::RunOptions{ nullptr }, input_node_names.data(), &input_tensor, 1, output_node_names.data(), 1);
`) . How can I do this?  Again, thanks for the help!

**Comment by hariharans29** [comment]
Take a look at this - https://github.com/microsoft/onnxruntime/issues/1323

**Comment by danperazzo** [comment]
Thanks!
