### ISSUE TITLE
Differences between mlas/lib/aarch64 and mlas/lib/arm64

### ISSUE THREAD

**Issue by csukuangfj** [microsoft/onnxruntime#3308]
I find that there are two folders inside `mlas/lib`

- `aarch64`: https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/core/mlas/lib/aarch64
- `arm64`: https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/core/mlas/lib/arm64

What are the differences between them? Which one should I use for 64-bit arm?

**Comment by tracysh** [comment]
Hi,

The "arm64" directory is used for the Visual Studio build. This tool chain uses an ARM assembler based on something from ARM itself.

The "aarch64" directory is used for GCC builds (there's a known issue tracked in another PR to fix a LLVM incompatibility).

Most likely you want the "aarch64" directory. Out of curiosity, are you building something outside the existing build scripts?

**Comment by csukuangfj** [comment]
@tracysh 

I see. Thank you.

----

I am using Bazel.
