### ISSUE TITLE
How to choose CPU/GPU as the onnxruntime engine?

### ISSUE THREAD

**Issue by LexXia** [microsoft/onnxruntime#331]
**Is your feature request related to a problem? Please describe.**
I am testing the performance of onnx runtime on a machine with both CPU and GPU. Since I have installed both MKL-DNN and TensorRT, I am confused about whether my model is run on CPU or GPU. I have installed the packages onnxruntime and onnxruntime-gpu form pypi.

**System information**
- ONNX Runtime version (you are using):
onnxruntime 0.1.3 and onnxruntime-gpu 0.1.3

**Describe the solution you'd like**
I want to choose the engine by myself through a python API.

**Comment by LexXia** [comment]
> Not supported yet.

Is there any method to find which device is practically used? Like the "log_device_placement" config in the TF?

**Comment by snnn** [comment]
> > Not supported yet.
> 
> Is there any method to find which device is practically used? Like the "log_device_placement" config in the TF?

No. Usually I set a breakpoint to verify it. 
It's a good suggestion, we should add a visual tool.

**Comment by snnn** [comment]
Close this issue as the original problem is gone. Please feel free to open a new one for your new problems.

**Comment by snnn** [comment]
Hi @xadupre,

get_device() solved the problem partially. For example, even CUDA is enabled, it still possible that some ops(like conv) are still running on CPU.

**Comment by snnn** [comment]
Damn it! I closed the wrong issue.

**Comment by xadupre** [comment]
So you would like to know which device is used for every node of the graph?

**Comment by fumihwh** [comment]
Could onnxruntime choose the fastest provider to run op automatically now?
For example, conv.

**Comment by linkerzhang** [comment]
@fumihwh Thank you Wenhao! That's the goal ONNXRUNTIME wants to achieve. ONNXRUNTIME has a partitioning API designed in-place to be able to try to do a best graph partitioning (node assignment) per each execution provider's capability. However, the current implementation of partitioning is a simple greedy algo based on execution provider preferences customers set. That means, if the execution provider preferences are "TensorRT", "Cuda", "CPU", then nodes will be assigned to TensorRT, Cuda, CPU in order per their capability results returned.

**Comment by faxu** [comment]
Closing this issue. 

- Specifying execution provider via python API is tracked here: https://github.com/microsoft/onnxruntime/issues/486
- "smarter" execution provider selection (beyond greedy algo) may be a future feature
