### ISSUE TITLE
Web tooling for model conversion for newcomers/quick start?

### ISSUE THREAD

**Issue by BillMcCrary** [microsoft/onnxruntime#3335]
Has there ever been a discussion about hosting the conversion tools ([https://github.com/onnx/tutorials#converting-to-onnx-format](url)) online as easy web tooling somewhere on https://microsoft.github.io/onnxruntime/?  

Keep all the github source access for those who want or need it, but to ease the curve for those of us getting started learning we could just have some easy & smart tool to accept an upload and return us an optimized ONNX model (or even tell us what is wrong with our upload in case of an error).

**Comment by hariharans29** [comment]
@wenbingl @spandantiwari  - Here is a question about conversion tools. Is this something you could help with ?
