### ISSUE TITLE
Runtime_Exception with nGraph

### ISSUE THREAD

**Issue by ggeor84** [microsoft/onnxruntime#3340]
**Describe the bug**
A model running with other backends (cpu,mkldnn) trhows a runtime exception with nGraph.

    sess = rt.InferenceSession( self.model.filepath , opt)
  File "/virtualenvs/onnxruntime_ngraph_release/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 25, in __init__
    self._load_model(providers)
  File "/virtualenvs/onnxruntime_ngraph_release/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 43, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /libs/onnxruntime/onnxruntime/core/graph/function.cc:171 onnxruntime::FunctionImpl::FunctionImpl(const onnxruntime::Graph&, std::unique_ptr<onnxruntime::IndexedSubGraph>, const onnxruntime::logging::Logger&) input_arg->Type() != nullptr was false. 

**Urgency**
Medium

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary):  source
- ONNX Runtime version: 1.1.0
- Python version: 3.6.9
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source):7.5.0
- CUDA/cuDNN version:10.2
- GPU model and memory:Titan RTX 24GB

**Expected behavior**
Model expected to run

**Comment by jywu-msft** [comment]
is the model shareable?
unfortunately the Onnxruntime nGraph EP which was developed by Intel is no longer in active development. Development has shifted to the OpenVINO EP, which will have parity (and eventually improve upon) the old nGraph EP.

**Comment by ggeor84** [comment]
@jywu-msft thanks for the reply. I'll DM you internally
