### ISSUE TITLE
Request for C++ API documentation

### ISSUE THREAD

**Issue by csukuangfj** [microsoft/onnxruntime#3342]
The following files are poorly documented 
- https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_cxx_api.h
- https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h

Where can I find documentation about the above APIs?

**Comment by danperazzo** [comment]
I would like to know it too, I am having problems  using the C/C++ API

**Comment by hoaquocphan** [comment]
Hi @hariharans29 

I have the same problems about the referent document,
1/ there are no any example a bout multi input/ multi output for as tiny yolov3.
there is just a simple guide like this: [CXX_Api_Sample.cpp#L53](https://github.com/microsoft/onnxruntime/blob/rel-1.0.0/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp#L53)
2/ there are no any example about the  
`image_data = np.expand_dims(image_data, 0)`  in [yolov3](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3) for C/C++


Please help us ASAP, 
Thanks

**Comment by csukuangfj** [comment]
@hariharans29 

are there any plans to add more documentation to onnxruntime?

**Comment by hoaquocphan** [comment]
Hi @csukuangfj 

He is very busy, I already raised many tickets to  get the help but after that, I solved the problem by myself.   :D

**Comment by KevinHake** [comment]
A bit thin now, but the C API doc is here: https://github.com/microsoft/onnxruntime/blob/master/docs/C_API.md

**Comment by csukuangfj** [comment]
@KevinHake 
thanks for your reply.

I think I have a different view with you for what an API is.

An API is an interface and the doc of an interface should include **at least**
- what the interface does
- what the meanings of the arguments are

What the document https://github.com/microsoft/onnxruntime/blob/master/docs/C_API.md provides is just a link to a sample application, which allows you to **copy and paste** the code
from it. I don't consider it is an API doc.

**Comment by KevinHake** [comment]
Haha I don't consider it a proper/complete API either, and I doubt anyone does. But based on the name, this is where that missing info should/will go, for anyone who discovers some things and cares to document it. I am just bumbling my way through using the examples for now.
