### ISSUE TITLE
Unable to use onnxruntime.dll for GPU

### ISSUE THREAD

**Issue by finsker** [microsoft/onnxruntime#3344]
**Describe the bug**
Hi, 
i can run my custom onnx model and get correct results using CPU-runtime (1.2.0), but if i try to use GPU-Runtime i am getting an error. I tried already to delete NuGet package OnnxRuntime for CPU. I also checked, the onnxruntime.dll file is always copied to the bin folder.
Error:

> Message: System.TypeInitializationException : The type initializer for '
> Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.
>   ----> System.DllNotFoundException : Unable to load DLL 'onnxruntime': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
> Stacktrace:

 >   at Microsoft.ML.OnnxRuntime.SessionOptions..ctor() in D:\4\s\csharp\src\Microsoft.ML.OnnxRuntime\SessionOptions.cs:line 49
>    at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath) in D:\4\s\csharp\src\Microsoft.ML.OnnxRuntime\InferenceSession.cs:line 34
>    at MLWrapper.Models.OnnxModel..ctor(String modelPath) in C:\Projects\MachineLearning\MLWrapper\MLWrapper\Models\ONNX\OnnxModel.cs:line 71

Am i doing something false? Could you explain it? 

**Urgency**
Medium

**System information**
- OS Platform and Distribution : Windows 10
- ONNX Runtime installed from (source or binary): NuGet
- ONNX Runtime version: 1.2.0 (GPU)
- Visual Studio version (if applicable): 15.9.21:
- CUDA/cuDNN version: CUDA 10.0 cuDNN 7.6.5.32
- GPU model and memory: RTX 2080 Ti
- Language: C# 4.7.2

**Expected behavior**
Getting some results as from cpu runtime, but a little bit faster:)

**Comment by hariharans29** [comment]
Install just the Gpu package. It will automatically bring in the managed package and it will be able to resolve the onnxruntime.dll correctly.

**Comment by finsker** [comment]
Hi @hariharans29, thank you for fast reply!
I have already tried to delete all nuget packages and install only onnxruntime.GPU, which installs all necessary dependencies such as onnxruntime.Managed. And it copies too the correct .DLL in the bin folder, which weights about 85 megabytes. But im getting the same Error.

**Comment by hexiangdong2017** [comment]
I'm the same error. Is it a bug?

**Comment by nagymate17** [comment]
I am having the same issue with almost the same environment. CPU version works well and actually the GPU version also works on my development laptop  with GTX 1060. But when I try to run the build on my other PC with GTX 1080, I am getting the same error as mentioned. With a CPU runtime (it is around 5 MB) it works well on both PC. I am pretty sure that this is not related to the type of GPU but I am still confused because I installed the same packages on both PC.

**Comment by Chmielok** [comment]
Same here, is it possible this happens because of CUDA version mismatch?

**Comment by faxu** [comment]
System requirements are listed here: https://github.com/microsoft/onnxruntime#system-requirements

**Comment by captainst** [comment]
Trapped by the same problem. From the comments by @faxu, some guess might be:
for CUDA 10.0 / cuDNN 7.6, try runtime V1.1.0 (I verified this config on win10, vs2019, nuget install)
for CUDA 10.1, try runtime V1.2.0 or V1.3.0 (not verified)
for CUDA 10.2 and upwards, try runtime V1.5.1 and above (not verified)
