### ISSUE TITLE
RUNTIME_EXCEPTION:  Attribute not found: pads

### ISSUE THREAD

**Issue by qraleq** [microsoft/onnxruntime#3353]
**Describe the bug**
I'm trying to use TensorRT onnxruntime to run an object detection graph (SSD MobilenetV2 with FPN). The graph was successfully converted from tensorflow to onnx, and it runs fine using CPU and GPU onnxruntime. The graph uses a fixed input shape of (1, 1280, 720, 3).

I use the symbolic_shape_infer.py script which finishes successfully after #3293 .
When I try to run the output model, I get an another error:
`RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: Attribute not found: pads`

Can you help me with this error?

**Urgency**
Urgent

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.2.0
- Python version: 3.6
- CUDA/cuDNN version: 10.0 / 
- GPU model and memory: GeForce 940MX / 4GB

**To Reproduce**
You can find the optimized model here: https://drive.google.com/open?id=1oMWf1Fh4escoQPsI4AYxv0HU7-M677yT
If you try to run it, you should get the same error!

**Comment by jywu-msft** [comment]
Thanks for reporting. we're aware of the issue.
+@stevenlix

**Comment by qraleq** [comment]
@stevenlix Do you have any update on this issue, or you can provide some insights about the problem?

**Comment by jywu-msft** [comment]
try building the latest master. the issue should be fixed by https://github.com/microsoft/onnxruntime/pull/3369
which updated to latest onnx-tensorrt parser which includes https://github.com/onnx/onnx-tensorrt/commit/c536d726f309376faa407433d0bf5cef75e89ce1

**Comment by qraleq** [comment]
@jywu-msft  Thank you very much for the update! Now the previous error is resolved and the build of TRT engine starts. Unfortunately, I get another error:
`2020-04-01 13:27:24.033733574 [W:onnxruntime:Default, tensorrt_execution_provider.h:35 log] [2020-04-01 12:27:24   ERROR] Layer: (Unnamed Layer* 24)[Select]'s output can not be used as shape tensor.`

`2020-04-01 13:27:24.033755356 [W:onnxruntime:Default, tensorrt_execution_provider.h:35 log] [2020-04-01 12:27:24   ERROR] Network validation failed.` 

Previous error message is shown in the jupyter-notebook terminal, while this error is shown in the notebook:
`EPFail: [ONNXRuntimeError] : 11 : EP_FAIL : TensorRT EP could not build Engine for fused node: TensorrtExecutionProvider_TRTKernel_6_6`.

Do you know what might be the problem?
