### ISSUE TITLE
Python 3.6 not found by FindPythonInterp

### ISSUE THREAD

**Issue by xkszltl** [microsoft/onnxruntime#3354]
**Describe the bug**

When compiling the latest release, I got python >= 3.5 not found error in FindPythonInterp.
System has python 2.7 and 3.6 installed.

A workaround is to add `-DPython_ADDITIONAL_VERSION=3.6`.

**Urgency**

Can be manually worked around but should be fixed ASAP.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: latest release(1.2.0)
- Python version: 3.6
- GCC/Compiler version (if compiling from source): gcc8
- CUDA/cuDNN version: 10.2

**Comment by faxu** [comment]
Can you share more information on the instructions you're using to build this? If you are using 1.2.0, any reason for not using the pre-built official binaries?

**Comment by xkszltl** [comment]
Reason for build-from-source:
Based on our team's experience of switching to ORT, we're frequently asked to use non-release version, and we also want to keep versions of all common dependencies consistent between libs.

Here's the command failed:
https://github.com/xkszltl/Roaster/blob/35a9615414bdc624485d80e88cb30856413bb030/pkgs/ort.sh#L71-L107
```
cmake                                               \
    -DCMAKE_BUILD_TYPE=Release                      \
    -DCMAKE_C_COMPILER="$CC"                        \
    -DCMAKE_CXX_COMPILER="$CXX"                     \
    -DCMAKE_{C,CXX,CUDA}_COMPILER_LAUNCHER=ccache   \
    -DCMAKE_C{,XX}_FLAGS="-fdebug-prefix-map='$SCRATCH'='$INSTALL_PREFIX/src' -g $($TOOLCHAIN_CPU_NATIVE || echo '-march=haswell -mtune=generic')"  \
    -DCMAKE_INSTALL_PREFIX="$INSTALL_ABS"           \
    -DCMAKE_POLICY_DEFAULT_CMP0060=NEW              \
    -DCMAKE_VERBOSE_MAKEFILE=ON                     \
    -DPython_ADDITIONAL_VERSIONS="$(python3 --version | sed -n 's/^Python[[:space:]]*\([0-9]*\.[0-9]*\)\..*/\1/p')" \
    -Deigen_SOURCE_PATH="/usr/local/include/eigen3" \
    -Donnxruntime_BUILD_FOR_NATIVE_MACHINE="$($TOOLCHAIN_CPU_NATIVE && echo 'ON' || echo 'OFF')"    \
    -Donnxruntime_BUILD_SHARED_LIB=ON               \
    -Donnxruntime_CUDNN_HOME='/usr/lib64'           \
    -Donnxruntime_ENABLE_PYTHON=ON                  \
    -Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=ON    \
    -Donnxruntime_ENABLE_LTO=OFF                    \
    -Donnxruntime_RUN_ONNX_TESTS=ON                 \
    -Donnxruntime_USE_BRAINSLICE=OFF                \
    -Donnxruntime_USE_CUDA=ON                       \
    -Donnxruntime_USE_EIGEN_FOR_BLAS=ON             \
    -Donnxruntime_USE_EIGEN_THREADPOOL=OFF          \
    -Donnxruntime_USE_FULL_PROTOBUF=ON              \
    -Donnxruntime_USE_JEMALLOC=OFF                  \
    -Donnxruntime_USE_LLVM=ON                       \
    -Donnxruntime_USE_MKLDNN=ON                     \
    -Donnxruntime_USE_MKLML=ON                      \
    -Donnxruntime_USE_NGRAPH=OFF                    \
    -Donnxruntime_USE_NSYNC=OFF                     \
    -Donnxruntime_USE_NUPHAR=OFF                    \
    -Donnxruntime_USE_OPENBLAS=OFF                  \
    -Donnxruntime_USE_OPENMP=OFF                    \
    -Donnxruntime_USE_PREINSTALLED_EIGEN=OFF        \
    -Donnxruntime_USE_TENSORRT=OFF                  \
    -Donnxruntime_USE_TVM=OFF                       \
    -G"Ninja"                                       \
    ../cmake
```

<img width="734" alt="image" src="https://user-images.githubusercontent.com/5203025/85707715-09cfd380-b716-11ea-9f18-7b2a70473fbb.png">

The reason I think is because FindPythonInterp is not called with version requirement in cmake, so 2.7 is found instead of 3.6, and later failed by a >=3.5 check.
BTW a code path to use FindPython3 in cmake >= 3.12 is recommended, see https://cmake.org/cmake/help/latest/module/FindPythonInterp.html
