### ISSUE TITLE
onnxruntime c/c++ api don't support windows xp

### ISSUE THREAD

**Issue by xinheblue** [microsoft/onnxruntime#3357]
**Is your feature request related to a problem? Please describe.**
We are to develop a system which must support windows xp. I use visual studio 2017 with the option Visual studio 2017 - Windows XP(v141_xp), and the Windows SDK changes to 7.1.

it complains
microsoft.ml.onnxruntime.1.2.0\build\native\include\onnxruntime_c_api.h(645): error C2061: 语法错误: 标识符“_Frees_ptr_opt_”

when I swich Visual studio 2017 - Windows XP(v141_xp) to Visual studio 2017,the error disappears.

**System information**
- ONNX Runtime version (you are using):
1.2.0
**Describe the solution you'd like**
hope the onnxruntime support windows xp

**Comment by PythonCancer** [comment]
I also encountered the same problem. What did you finally solve?
