### ISSUE TITLE
How to use DirectML execution provider from Python?

### ISSUE THREAD

**Issue by RobinKa** [microsoft/onnxruntime#3358]
// Edit: seems like it has not been exposed to Python yet. Created a PR that exposes it.

I'm trying to use DirectML from python because it seems like that is the only one to support all popular GPU vendors (please correct me if I'm wrong). I built it from source (`build.bat --config RelWithDebInfo --build_wheel --parallel --use_dml --cmake_generator "Visual Studio 16 2019"`) which succeeds and I can see that it generates a wheel (`onnxruntime\build\Windows\RelWithDebInfo\RelWithDebInfo\dist\onnxruntime-1.2.0-cp37-cp37m-win_amd64.whl`). I installed that wheel but there is still only the CPU provider available:

```
>>> rt.get_available_providers()
['CPUExecutionProvider']
```

Am I missing something or is it not possible to use it in python as of now?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro 1903
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: '1.2.0'-03-29 15:49:23.4469416
- Python version: 3.7.3
- Visual Studio version (if applicable): 16.6.0 Preview 2
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: GTX 1070 (8gb)

**Comment by Coderx7** [comment]
I have the very same problem. 
@RobinKa did you solve this?

**Comment by fredrickomondi** [comment]
You can now download it via pip from https://pypi.org/project/onnxruntime-directml/
