### ISSUE TITLE
Creating DirectML Device crashes at `DMLCreateDevice1`

### ISSUE THREAD

**Issue by RobinKa** [microsoft/onnxruntime#3360]
**Describe the bug**
When trying to use the DirectML provider a crash happens when calling `DMLCreateDevice1` [here](https://github.com/microsoft/onnxruntime/blob/33b5010e624d0c649e121a323eda29dfa4074e2a/onnxruntime/core/providers/dml/dml_provider_factory.cc#L120-L123). Replacing it with `DMLCreateDevice` works although I don't know if there are any unintended consequences:
```cpp
THROW_IF_FAILED(DMLCreateDevice(d3d12_device.Get(),
                              flags,
                              IID_PPV_ARGS(&dml_device)));
```

**Urgency**
DirectML does not work (for me) without that fix. For me personally not having DML is a big issue as I need my program to run on all GPU vendors' devices.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Pro 1903
- ONNX Runtime installed from (source or binary): source with use_dml, build_wheel
- ONNX Runtime version: 1.2.0 (current master)
- Python version: 3.7.3
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: GTX 1070 (8gb)

**To Reproduce**
Build onnxruntime with `build.bat --config RelWithDebInfo --parallel --use_dml --cmake_generator "Visual Studio 16 2019`. Try adding the DML provider (eg. start with [this sample](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp) and add `OrtSessionOptionsAppendExecutionProvider_DML(session_options, 0);`. The program will crash at this line (although I noticed when using a nonsensical device like 100 it goes through, but seems to use CPU still).
Alternatively, python can be used using [my recent PR](https://github.com/microsoft/onnxruntime/pull/3359) and the following code will crash without a message at `set_providers()`:

```python
import onnxruntime as rt
session_opts = rt.SessionOptions()
session_opts.enable_mem_pattern = False
session = rt.InferenceSession("model.onnx", session_opts)
session.set_providers(["DmlExecutionProvider"])
```

**Expected behavior**
It should not crash and use the DirectML execution provider.

**Comment by fdwr** [comment]
@RobinKa : Does it work calling `DMLCreateDevice1` with `DML_FEATURE_LEVEL_1_0`? (DMLCreateDevice is basically DMLCreateDevice1 except it defaults to feature level 1.0)

**Comment by RobinKa** [comment]
Passing `DML_FEATURE_LEVEL_1_0` produces the same error:
![image](https://user-images.githubusercontent.com/2614101/78171887-0eedf100-744d-11ea-9181-2930822082eb.png). There's also no `DXGI_ERROR_UNSUPPORTED` error in the output.

But I just noticed, when I use the DirectML.dll provided with onnxruntime (in `onnxruntime\build\Windows\packages\DirectML.0.0.1\bin\x64`) it works, previously I was using the dll that comes with Windows.

**Comment by fdwr** [comment]
@RobinKa : Thanks. Oh yes, you must use the preview DirectML.dll that came with this version of the ONNX Runtime package. The older OS version is not compatible with this package because ORT relies on some newer API's in preview DML that don't exist in the OS.
