### ISSUE TITLE
ONNXRUNTIME needs to support Opset version 11 and 12 of the Clip Operation

### ISSUE THREAD

**Issue by dibya001** [microsoft/onnxruntime#3364]
**Is your feature request related to a problem? Please describe.**

**System information**
- ONNX Runtime version (you are using): 1.2.0

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jywu-msft** [comment]
Clip opset 11 should already be supported. https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/math/clip.cc#L17

opset 12 is work in progress.

**Comment by dibya001** [comment]
Its strange, Because I am getting below error
[ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node: : Node () has input size 3 not in range [min=1, max=1].

**Comment by dibya001** [comment]
node_0 = np.random.uniform(-1, 1, (1, 3, 76,76)).astype(np.float32)
 min_0= np.random.randn(1).astype(np.float32)
 max_0= np.random.randn(1).astype(np.float32)
 **node1= helper.make_node('Clip', inputs=['node_0', 'min_0', 'max_0' ], outputs=['node_1'])**
  
inputs_list = [helper.make_tensor_value_info(input_tensors[0][0], TensorProto.FLOAT, input_tensors[0][1]),
    helper.make_tensor_value_info('min_0', TensorProto.FLOAT, (1,)),
    helper.make_tensor_value_info('max_0', TensorProto.FLOAT, (1,)),
    ]

**Comment by dibya001** [comment]
Onnx version: 1.6.0
OnnxRuntime Version: 1.2.0
