### ISSUE TITLE
No support for double Sum

### ISSUE THREAD

**Issue by Lynx1820** [microsoft/onnxruntime#3366]
The error I get when I try to use the Sum operator with doubles: 
System.InvalidOperationException : Error initializing model :Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:RuntimeException] Exception during initialization: D:\1\s\onnxruntime\core\optimizer\optimizer_execution_frame.cc:73 onnxruntime::OptimizerExecutionFrame::Info::Info [ONNXRuntimeError] : 1 : FAIL : Failed to find kernel for Sum

According to the documentation, doubles should be supported.

**Comment by snnn** [comment]
> According to the documentation, doubles should be supported.

Sorry, we do it by request.  Please send your model to @faxu , and tell her why you need double support. She will evaluate the model and follow up with you.
