### ISSUE TITLE
Build onnxruntime-tensorRT  on Jetson Xavier failed

### ISSUE THREAD

**Issue by mi-yang** [microsoft/onnxruntime#3371]
**Describe the bug**
I am trying to build onnxruntime use tensorRT on Jetson Xavier, refer to 
https://github.com/microsoft/onnxruntime/issues/2684#issuecomment-568548387

**Urgency**
Using SDK Manager4.3 to install CUDA,cuDNN and tensorRT

**System information**
    * Linux Ubuntu 18.04):
    * Name:           NVIDIA Jetson Xavier                                                                                                          
    * Jetpack:        4.3 
    * GPU-Arch:       7.5
  - Libraries:
    * CUDA:           10.0.326
    * cuDNN:          7.6.3.28-1+cuda10.0
    * TensorRT:       6.0.1.10-1+cuda10.0
 
**To Reproduce**
- follow the step as https://github.com/microsoft/onnxruntime/issues/2684#issuecomment-568548387
- git clone --recursive https://github.com/Microsoft/onnxruntime
- cd onnxruntime
- git checkout b783805
- export CUDACXX="/usr/local/cuda/bin/nvcc"
- Modify  tools/ci_build/build.py
    - "-Donnxruntime_DEV_MODE=" + ("OFF" if args.android else "ON"),
    + "-Donnxruntime_DEV_MODE=" + ("OFF" if args.android else "OFF"),
- Modify cmake/CMakeLists.txt
    -  set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -gencode=arch=compute_50,code=sm_50") # M series
    +  set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -gencode=arch=compute_75,code=sm_75") # Jetson support
- ./build.sh --config Release --update --build --build_wheel --use_tensorrt --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu --tensorrt_home /usr/lib/aarch64-linux-gnu --parallel

**Logs**
root@montage-desktop:~/sandbox/onnxruntime# ./build.sh --config Release --update --build --build_wheel --use_tensorrt --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu --tensorrt_home /usr/lib/aarch64-linux-gnu --parallel
2020-03-30 23:21:18,041 Build [INFO] - Build started
2020-03-30 23:21:18,042 Build [DEBUG] - Running subprocess in '/root/sandbox/onnxruntime'
['git', 'submodule', 'sync', '--recursive']
Synchronizing submodule url for 'cmake/external/DNNLibrary'
Synchronizing submodule url for 'cmake/external/DNNLibrary/third_party/flatbuffers'
Synchronizing submodule url for 'cmake/external/DNNLibrary/third_party/glog'
Synchronizing submodule url for 'cmake/external/DNNLibrary/third_party/onnx'
Synchronizing submodule url for 'cmake/external/DNNLibrary/third_party/onnx/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/DNNLibrary/third_party/onnx/third_party/pybind11'
Synchronizing submodule url for 'cmake/external/DNNLibrary/third_party/onnx/third_party/pybind11/tools/clang'
Synchronizing submodule url for 'cmake/external/DNNLibrary/third_party/protobuf'
Synchronizing submodule url for 'cmake/external/DNNLibrary/third_party/protobuf/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/DNNLibrary/third_party/protobuf/third_party/googletest'
Synchronizing submodule url for 'cmake/external/DNNLibrary/third_party/pybind11'
Synchronizing submodule url for 'cmake/external/DNNLibrary/third_party/pybind11/tools/clang'
Synchronizing submodule url for 'cmake/external/cub'
Synchronizing submodule url for 'cmake/external/date'
Synchronizing submodule url for 'cmake/external/eigen'
Synchronizing submodule url for 'cmake/external/gemmlowp'
Synchronizing submodule url for 'cmake/external/googletest'
Synchronizing submodule url for 'cmake/external/grpc'
Synchronizing submodule url for 'cmake/external/grpc/third_party/abseil-cpp'
Synchronizing submodule url for 'cmake/external/grpc/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/grpc/third_party/bloaty'
Synchronizing submodule url for 'cmake/external/grpc/third_party/bloaty/third_party/googletest'
Synchronizing submodule url for 'cmake/external/grpc/third_party/bloaty/third_party/libFuzzer'
Synchronizing submodule url for 'cmake/external/grpc/third_party/bloaty/third_party/re2'
Synchronizing submodule url for 'cmake/external/grpc/third_party/boringssl'
Synchronizing submodule url for 'cmake/external/grpc/third_party/boringssl-with-bazel'
Synchronizing submodule url for 'cmake/external/grpc/third_party/cares/cares'
Synchronizing submodule url for 'cmake/external/grpc/third_party/data-plane-api'
Synchronizing submodule url for 'cmake/external/grpc/third_party/gflags'
Synchronizing submodule url for 'cmake/external/grpc/third_party/gflags/doc'
Synchronizing submodule url for 'cmake/external/grpc/third_party/googleapis'
Synchronizing submodule url for 'cmake/external/grpc/third_party/googletest'
Synchronizing submodule url for 'cmake/external/grpc/third_party/libcxx'
Synchronizing submodule url for 'cmake/external/grpc/third_party/libcxxabi'
Synchronizing submodule url for 'cmake/external/grpc/third_party/protobuf'
Synchronizing submodule url for 'cmake/external/grpc/third_party/protobuf/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/grpc/third_party/protobuf/third_party/googletest'
Synchronizing submodule url for 'cmake/external/grpc/third_party/protoc-gen-validate'
Synchronizing submodule url for 'cmake/external/grpc/third_party/upb'
Synchronizing submodule url for 'cmake/external/grpc/third_party/upb/third_party/protobuf'
Synchronizing submodule url for 'cmake/external/grpc/third_party/upb/third_party/protobuf/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/grpc/third_party/upb/third_party/protobuf/third_party/googletest'
Synchronizing submodule url for 'cmake/external/grpc/third_party/zlib'
Synchronizing submodule url for 'cmake/external/mimalloc'
Synchronizing submodule url for 'cmake/external/nsync'
Synchronizing submodule url for 'cmake/external/onnx'
Synchronizing submodule url for 'cmake/external/onnx/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/onnx/third_party/pybind11'
Synchronizing submodule url for 'cmake/external/onnx/third_party/pybind11/tools/clang'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt/third_party/onnx'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt/third_party/onnx/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt/third_party/onnx/third_party/pybind11'
Synchronizing submodule url for 'cmake/external/onnx-tensorrt/third_party/onnx/third_party/pybind11/tools/clang'
Synchronizing submodule url for 'cmake/external/protobuf'
Synchronizing submodule url for 'cmake/external/protobuf/third_party/benchmark'
Synchronizing submodule url for 'cmake/external/protobuf/third_party/googletest'
Synchronizing submodule url for 'cmake/external/re2'
Synchronizing submodule url for 'cmake/external/spdlog'
Synchronizing submodule url for 'cmake/external/tvm'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/HalideIR'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/dlpack'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/dmlc-core'
Synchronizing submodule url for 'cmake/external/tvm/3rdparty/rang'
Synchronizing submodule url for 'cmake/external/wil'
2020-03-30 23:21:19,030 Build [DEBUG] - Running subprocess in '/root/sandbox/onnxruntime'
['git', 'submodule', 'update', '--init', '--recursive']
2020-03-30 23:21:22,265 Build [INFO] - Generating CMake build tree
2020-03-30 23:21:22,268 Build [DEBUG] - Running subprocess in '/root/sandbox/onnxruntime/build/Linux/Release'
['/usr/local/bin/cmake', '/root/sandbox/onnxruntime/cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-Donnxruntime_DEV_MODE=OFF', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-Donnxruntime_USE_CUDA=ON', '-Donnxruntime_USE_NSYNC=OFF', '-Donnxruntime_CUDNN_HOME=/usr/lib/aarch64-linux-gnu', '-Donnxruntime_USE_AUTOML=OFF', '-Donnxruntime_CUDA_HOME=/usr/local/cuda', '-Donnxruntime_USE_JEMALLOC=OFF', '-Donnxruntime_USE_MIMALLOC=OFF', '-Donnxruntime_ENABLE_PYTHON=ON', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_SHARED_LIB=OFF', '-Donnxruntime_USE_EIGEN_FOR_BLAS=ON', '-Donnxruntime_USE_OPENBLAS=OFF', '-Donnxruntime_USE_MKLDNN=OFF', '-Donnxruntime_USE_MKLML=OFF', '-Donnxruntime_USE_GEMMLOWP=OFF', '-Donnxruntime_USE_NGRAPH=OFF', '-Donnxruntime_USE_OPENVINO=OFF', '-Donnxruntime_USE_OPENVINO_BINARY=OFF', '-Donnxruntime_USE_OPENVINO_SOURCE=OFF', '-Donnxruntime_USE_OPENVINO_MYRIAD=OFF', '-Donnxruntime_USE_OPENVINO_GPU_FP32=OFF', '-Donnxruntime_USE_OPENVINO_GPU_FP16=OFF', '-Donnxruntime_USE_OPENVINO_CPU_FP32=OFF', '-Donnxruntime_USE_OPENVINO_VAD_M=OFF', '-Donnxruntime_USE_OPENVINO_VAD_F=OFF', '-Donnxruntime_USE_NNAPI=OFF', '-Donnxruntime_USE_OPENMP=ON', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_BRAINSLICE=OFF', '-Donnxruntime_USE_NUPHAR=OFF', '-Donnxruntime_USE_EIGEN_THREADPOOL=OFF', '-Donnxruntime_USE_TENSORRT=ON', '-Donnxruntime_TENSORRT_HOME=/usr/lib/aarch64-linux-gnu', '-Donnxruntime_CROSS_COMPILING=OFF', '-Donnxruntime_BUILD_SERVER=OFF', '-Donnxruntime_BUILD_x86=OFF', '-Donnxruntime_USE_FULL_PROTOBUF=ON', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_MSVC_STATIC_RUNTIME=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=OFF', '-DCUDA_CUDA_LIBRARY=/usr/local/cuda/lib64/stubs', '-Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF', '-DCMAKE_BUILD_TYPE=Release']
-- Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR) 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9", minimum required is "3.5") 
-- GPU_ARCH is not defined. Generating CUDA code for default SMs.
-- Found TensorRT headers at /usr/include/aarch64-linux-gnu
-- Find TensorRT libs at /usr/lib/aarch64-linux-gnu/libnvinfer.so;/usr/lib/aarch64-linux-gnu/libnvinfer_plugin.so
-- NumPy ver. 1.18.2 found (include: /usr/local/lib/python3.6/dist-packages/numpy/core/include)
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.9") 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/sandbox/onnxruntime/build/Linux/Release
2020-03-30 23:21:26,969 Build [INFO] - Building targets for Release configuration
2020-03-30 23:21:26,973 Build [DEBUG] - Running subprocess in '/root/sandbox/onnxruntime'
['/usr/local/bin/cmake', '--build', '/root/sandbox/onnxruntime/build/Linux/Release', '--config', 'Release', '--', '-j8']
[  0%] Performing update step for 'pybind11'
[  0%] Built target gtest
[  2%] Built target re2
[  2%] Built target gmock
[  2%] No configure step for 'pybind11'
[  4%] Built target onnxruntime_mlas
[  5%] No build step for 'pybind11'
[ 14%] Built target libprotobuf
[ 14%] No install step for 'pybind11'
[ 14%] Completed 'pybind11'
[ 14%] Built target pybind11
[ 24%] Built target libprotoc
[ 25%] Built target protoc
[ 26%] Built target onnx_proto
[ 28%] Built target onnxruntime_common
[ 29%] Built target onnxruntime_test_utils_for_framework
[ 29%] Built target nvonnxparser_static
[ 30%] Built target onnxruntime_test_utils
[ 32%] Built target onnxruntime_graph
[ 38%] Built target onnx
[ 38%] Built target onnx_test_data_proto
[ 39%] Built target nvonnxparser
[ 39%] Linking CXX executable onnx2trt
[ 39%] Built target onnxruntime_util
[ 40%] Built target onnxruntime_session
[ 42%] Built target onnxruntime_optimizer
[ 42%] Linking CXX executable getSupportedAPITest
[ 48%] Built target onnxruntime_framework
[ 48%] Built target onnxruntime_mlas_test
[ 49%] Built target onnxruntime_providers_tensorrt
[ 49%] Built target trt_onnxify
[ 50%] Built target onnx_test_runner_common
[ 61%] Built target onnxruntime_providers_cuda
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libnvinfer.so: undefined reference to `NvMediaDlaDataUnregister'
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libnvinfer.so: undefined reference to `NvMediaDlaLoadableCreate'
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libnvinfer.so: undefined reference to `NvMediaDlaGetMaxOutstandingTasks'
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libnvinfer.so: undefined reference to `NvMediaDlaSubmit'
collect2: error: ld returned 1 exit status
external/onnx-tensorrt/CMakeFiles/onnx2trt.dir/build.make:90: recipe for target 'external/onnx-tensorrt/onnx2trt' failed
make[2]: *** [external/onnx-tensorrt/onnx2trt] Error 1
CMakeFiles/Makefile2:2092: recipe for target 'external/onnx-tensorrt/CMakeFiles/onnx2trt.dir/all' failed
make[1]: *** [external/onnx-tensorrt/CMakeFiles/onnx2trt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libnvinfer.so: undefined reference to `NvMediaDlaDataUnregister'
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libnvinfer.so: undefined reference to `NvMediaDlaLoadableCreate'
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libnvinfer.so: undefined reference to `NvMediaDlaGetMaxOutstandingTasks'
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libnvinfer.so: undefined reference to `NvMediaDlaSubmit'
collect2: error: ld returned 1 exit status
external/onnx-tensorrt/CMakeFiles/getSupportedAPITest.dir/build.make:105: recipe for target 'external/onnx-tensorrt/getSupportedAPITest' failed
make[2]: *** [external/onnx-tensorrt/getSupportedAPITest] Error 1
CMakeFiles/Makefile2:2121: recipe for target 'external/onnx-tensorrt/CMakeFiles/getSupportedAPITest.dir/all' failed
make[1]: *** [external/onnx-tensorrt/CMakeFiles/getSupportedAPITest.dir/all] Error 2
[ 77%] Built target onnxruntime_providers
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/root/sandbox/onnxruntime/tools/ci_build/build.py", line 1043, in <module>
    sys.exit(main())
  File "/root/sandbox/onnxruntime/tools/ci_build/build.py", line 981, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "/root/sandbox/onnxruntime/tools/ci_build/build.py", line 456, in build_targets
    run_subprocess(cmd_args)
  File "/root/sandbox/onnxruntime/tools/ci_build/build.py", line 196, in run_subprocess
    return subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/root/sandbox/onnxruntime/build/Linux/Release', '--config', 'Release', '--', '-j8']' returned non-zero exit status 2.

**Comment by mi-yang** [comment]
Actually I have tried onnxruntime v1.0 and v1.1,  both of them get the same link error.  is my TensorRT problem?  
need to install low version tensorRT ?

**Comment by jywu-msft** [comment]
we don't have jetson xavier available for us to test locally.
recently someone else successfully built on xavier. see https://github.com/microsoft/onnxruntime/issues/3307

from your error above, it looks like there's missing references to NvMedia* functions.
I believe that comes from libnvmedia.so which I think is only available on Xavier. Since we primarily tested on Jetson Nano, that wasn't available. 

also I noticed you have gencode=arch=compute_75,code=sm_75") # Jetson support
I think Xavier is actually compute_72 , sm_72 
btw, we have only tested with gencode=arch=compute_53,code=sm_53 # 
since we've only tested on Jetson Nano. 
can you try compute_53, sm_53 ?

**Comment by mi-yang** [comment]
> we don't have jetson xavier available for us to test locally.
> recently someone else successfully built on xavier. see #3307
> 
> from your error above, it looks like there's missing references to NvMedia* functions.
> I believe that comes from libnvmedia.so which I think is only available on Xavier. Since we primarily tested on Jetson Nano, that wasn't available.
> 
> also I noticed you have gencode=arch=compute_75,code=sm_75") # Jetson support
> I think Xavier is actually compute_72 , sm_72
> btw, we have only tested with gencode=arch=compute_53,code=sm_53 #
> since we've only tested on Jetson Nano.
> can you try compute_53, sm_53 ?

thanks for reply. change to 53 has the same problem.  when I install Target Components using SDK Manager4.3, Mutimedia component failed. is this reason ?

**Comment by jywu-msft** [comment]
linking to other thread in case others encounter this issue.
https://github.com/microsoft/onnxruntime/issues/3307#issuecomment-606552992

**Comment by mi-yang** [comment]
close it.  [https://forums.developer.nvidia.com/t/tensorrt-can-not-work-with-libnvinfer-so/117928](url)

> Please noticed that there are some strong dependencies between OS(GPU driver) and libraries.

So it is required to use the OS and package from the same JetPack version to avoid incompatibility.

**Comment by mi-yang** [comment]
@jywu-msft 
is there a method to know what core we are using ?  
for example jetson xavier has CPU,GPU and DLA , how onnxruntime tell tensorRT choose?

**Comment by mi-yang** [comment]
@jywu-msft 
tensorRT did not setup DLA engine ? 
[https://github.com/microsoft/onnxruntime/issues/3024#issuecomment-591771211](url)

**Comment by jywu-msft** [comment]
> @jywu-msft
> tensorRT did not setup DLA engine ?
> your verbose.log shows
> 2020-02-26 18:13:28.123485238 [V:onnxruntime:, inference_session.cc:642 TransformGraph] All nodes have been placed on [TensorrtExecutionProvider].
> That means all nodes are executing on GPU via TensorRT
> [refer to](https://github.com/microsoft/onnxruntime/issues/3024#issuecomment-591771211)

onnxruntime's TensorRT integration doesn't support DLA cores. Jetson Xavier wasn't a target for us to support. That could change in the future.

**Comment by mi-yang** [comment]
> > @jywu-msft
> > tensorRT did not setup DLA engine ?
> > your verbose.log shows
> > 2020-02-26 18:13:28.123485238 [V:onnxruntime:, inference_session.cc:642 TransformGraph] All nodes have been placed on [TensorrtExecutionProvider].
> > That means all nodes are executing on GPU via TensorRT
> > [refer to](https://github.com/microsoft/onnxruntime/issues/3024#issuecomment-591771211)
> 
> onnxruntime's TensorRT integration doesn't support DLA cores. Jetson Xavier wasn't a target for us to support. That could change in the future.

do you know what target onnxruntime supported with DLA cores?

**Comment by jywu-msft** [comment]
> > > @jywu-msft
> > > tensorRT did not setup DLA engine ?
> > > your verbose.log shows
> > > 2020-02-26 18:13:28.123485238 [V:onnxruntime:, inference_session.cc:642 TransformGraph] All nodes have been placed on [TensorrtExecutionProvider].
> > > That means all nodes are executing on GPU via TensorRT
> > > [refer to](https://github.com/microsoft/onnxruntime/issues/3024#issuecomment-591771211)
> > 
> > 
> > onnxruntime's TensorRT integration doesn't support DLA cores. Jetson Xavier wasn't a target for us to support. That could change in the future.
> 
> do you know what target onnxruntime supported with DLA cores?

I'm not sure I understand your question.
I think only Xavier has DLA cores per http://nvdla.org/
