### ISSUE TITLE
Unable to find an entry point named 'ReleaseOrtAllocatorInfo' in DLL 'onnxruntime.dll

### ISSUE THREAD

**Issue by jignparm** [Microsoft/onnxruntime#338]
**Describe the bug**
The C# library fails with message "System.EntryPointNotFoundException: 'Unable to find an entry point named 'ReleaseOrtAllocatorInfo' in DLL 'onnxruntime.dll'."

**To Reproduce**
See https://github.com/dotnet/machinelearning/issues/2149

**Comment by snnn** [comment]
All the symbols are list in 
https://github.com/Microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/symbols.txt

As you can see, ReleaseOrtAllocatorInfo is not there. But if you view the history,  there was a renaming. 

https://github.com/Microsoft/onnxruntime/commit/6a090985fbbf74c0fa3dda19537f3c5160a506b5#diff-e8cac4d6e6ffaf14374a1d9b2f7b96d3
