### ISSUE TITLE
Custom ops with same name and different Execution Provider

### ISSUE THREAD

**Issue by jonathanclx** [microsoft/onnxruntime#3394]
Hi,
My need is to use custom ops API to implement my custom op both for CPU Execution Provider and CUDA Execution Provider and having these implementations on a single separate shared library.

Thanks to [this fix](https://github.com/microsoft/onnxruntime/pull/3165) I was able to implement and register my custom op with CUDA Execution Provider implementation (i.e. implementing GetExecutionProvider() function returning "CUDAExecutionProvider").
But when I try to register another custom op with the same name but for CPU Execution Provider (i.e. GetExecutionProvider() left default), I run into this error: 

Trying to register schema with name custom_op_one ... but it is already registered ..."  (schema_registry.cc : 66).

I think the problem is because in CreateCustomRegistry() function from custom_ops.cc, a schema is always added for each custom operator.
My workaround was to modify this code and only add the schema if not already added.
Then it is working fine and the good kernel of my operator is called depending on the EP asked for the session (CUDA or CPU)

Does it make sense to you and would you plan adding this feature?

Best Regards  / Thanks.

**Comment by pranavsharma** [comment]
Sure, we'll fix this.
