### ISSUE TITLE
C# Verbose levels not working

### ISSUE THREAD

**Issue by ggeor84** [microsoft/onnxruntime#3409]
**Describe the bug**
For C#, when setting LogVerbosityLevel for SessionOptions, none of the various options seem to produce any output. In addition, it doesn't seem to be documented what each of the options produces.

**Urgency**
Medium

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.2.0
- Python version: N/A
- Visual Studio version (if applicable): VS 2017
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
You can reproduce the behavior by running e.g. C# PerfTool and adding one of the verbose options e.g.:
options.LogVerbosityLevel = LogLevel.Verbose;

**Expected behavior**
Some output expected on the console window. In addition, better documentation for what each of the options is supposed to output

**Screenshots**
N/A

**Additional context**
N/A

**Comment by pranavsharma** [comment]
PR https://github.com/microsoft/onnxruntime/pull/3840 fixes this.
