### ISSUE TITLE
CPUExecutionProvider's Conv1D is 3 times slower than tf.keras

### ISSUE THREAD

**Issue by AStupidBear** [microsoft/onnxruntime#3418]
**Describe the bug**

**Urgency**
High

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.2.0
- Python version: 3.6.5
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
```
import os
import time
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
os.environ['TF_KERAS'] = '1'
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"

import keras
import numpy as np
import onnxmltools
import onnxruntime as ort
import tensorflow as tf
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Conv1D, Dense

config = tf.compat.v1.ConfigProto(intra_op_parallelism_threads=1, inter_op_parallelism_threads=1)
tf.compat.v1.keras.backend.set_session(tf.compat.v1.Session(config=config))

x = np.random.randn(128, 1000, 30).astype('float32')
y = np.random.randn(128, 1000, 1).astype('float32')

o = i = Input((1000, x.shape[-1]), batch_size=128)
for n in range(5):
    o = Conv1D(64, 3, activation='relu', padding='same')(o)
o = Conv1D(1, 3, padding='same')(o)
model = Model(inputs=[i], outputs=[o])
model.compile(loss='mse', optimizer='sgd')

model.fit(x, y, epochs=1, batch_size=128)
onnx_model = onnxmltools.convert_keras(model, target_opset=10)
onnxmltools.utils.save_model(onnx_model, 'rnn.onnx')

model.predict(x, batch_size=128)
ti = time.time()
model.predict(x, batch_size=128)
print('keras time: ', time.time() - ti)

so = ort.SessionOptions()
so.intra_op_num_threads = 1
sess = ort.InferenceSession("rnn.onnx", so)
for provider in sess.get_providers():
    sess.set_providers([provider])
    input_name = sess.get_inputs()[0].name
    sess.run(None, {input_name: x})[0]
    ti = time.time()
    sess.run(None, {input_name: x})[0]
    print('onnx-' + provider, 'time: ', time.time() - ti)
```
- Attach the ONNX model to the issue (where applicable) to expedite investigation.
[model.zip](https://github.com/microsoft/onnxruntime/files/4428155/model.zip)

**Expected behavior**
onnxruntime is much slower than keras

**Screenshots**
```
keras time:  0.3388845920562744
2020-04-06 22:27:08.189025850 [W:onnxruntime:Default, nuphar_execution_provider.cc:154 GetCapability] Model shape inference failed, execution won't use nuphar provider.
onnx-DnnlExecutionProvider time:  0.13048243522644043
onnx-NupharExecutionProvider time:  0.960355281829834
onnx-CPUExecutionProvider time:  0.9651706218719482
```

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by snnn** [comment]
Thank you for the detailed information. I'll take a look now.

**Comment by AStupidBear** [comment]
onnxruntime with dnnl EP is slow for Conv2D

```
import os
import time
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
os.environ['TF_KERAS'] = '1'
os.environ["OMP_NUM_THREADS"] = "1"

import keras
import numpy as np
import onnxmltools
import onnxruntime as ort
import tensorflow as tf
from tensorflow.keras import Input, Model
from tensorflow.keras.layers import Conv2D, Dense

x = np.random.randn(32, 256, 256, 30).astype('float32')
y = np.random.randn(32, 256, 256, 1).astype('float32')

o = i = Input(x.shape[1:], batch_size=32)
for n in range(5):
    o = Conv2D(64, (3, 3), activation='relu', padding='same')(o)
o = Conv2D(1, (3, 3), padding='same')(o)
model = Model(inputs=[i], outputs=[o])
model.compile(loss='mse', optimizer='sgd')

model.fit(x, y, epochs=1, batch_size=32)
onnx_model = onnxmltools.convert_keras(model, target_opset=10)
onnxmltools.utils.save_model(onnx_model, 'rnn.onnx')

model.predict(x, batch_size=32)
ti = time.time()
model.predict(x, batch_size=32)
print('keras time: ', time.time() - ti)

so = ort.SessionOptions()
sess = ort.InferenceSession("rnn.onnx", so)
for provider in sess.get_providers():
    sess.set_providers([provider])
    input_name = sess.get_inputs()[0].name
    sess.run(None, {input_name: x})[0]
    ti = time.time()
    sess.run(None, {input_name: x})[0]
    print('onnx-' + provider, 'time: ', time.time() - ti)

```
![image](https://user-images.githubusercontent.com/16422976/78419430-3ffe3980-7678-11ea-989e-a967044e9273.png)

**Comment by snnn** [comment]
Hi @AStupidBear, does it contain tracy's latest change in #3425 ?

**Comment by snnn** [comment]
Hi @AStupidBear, the baseline runs with multiple CPUs, right? But you restrict onnxruntime to be singlethreaded, so the comparison isn't fair.  
On my machine, if both of them use multilple CPUs, the result is:
keras time:  2.618654727935791
onnxruntime time:2.15998

So onnxruntime is 20% faster.

**Comment by AStupidBear** [comment]
@snnn How can I restrict Keras to a single core? Isn't `OMP_NUM_THREADS=1' enough?

**Comment by AStupidBear** [comment]
@snnn I have updated my script and now it's a fair comparison for the single-core case. We can see `DnnlExecutionProvider` is the fastest for `Conv1D` and `Conv2D`. `CPUExecutionProvider` is still much slower than `keras` for `Conv1D`.

**Comment by tracysh** [comment]
@AStupidBear Have you remeasured the CPU EP performance using the latest master? PR #3425 improved the 1D convolution speed, but it is still a little short of DNNL. You should be able to get equivalent performance to DNNL if you reshape your convolutions as 2D with height=1. That will enable the existing CPU EP optimizer for a faster convolution path. There is additional work to the optimizer to also support 1D shapes, but that's a bigger project to do.

**Comment by AStupidBear** [comment]
@tracysh No, I didn't try it yet but I believe it's much faster than.  May the poor support for 1D is also the root cause of issue #3548 ?

**Comment by snnn** [comment]
I'm taking vacation now.  Will update this when I'm back. (about 10 days later).
