### ISSUE TITLE
Segfault when serializing a model that contains value_info for an edge not present in graph 

### ISSUE THREAD

**Issue by pranav-prakash** [microsoft/onnxruntime#3430]
**Describe the bug**
Consider a model that contains unused value_info entries. When this model is loaded into onnxruntime, the following snippet in graph.cc:2536 will be called

```
    for (auto& graph_value_info : graph_proto_->value_info()) {
      auto& name = graph_value_info.name();
      const auto* node_arg = GetNodeArg(name);
      value_info_.push_back(node_arg);
    }
```
Note that if `name` is never used, `GetNodeArg` will return a `nullptr` which will be pushed into the `value_info_` array. Subsequently, if any graph transform modifies the graph such that a `GraphProtoSync()` is needed (as checked in `ToGraphProto()`), then we call into `ToGraphProtoInternal(ONNX_NAMESPACE::GraphProto& graph_proto)`. In this method we have

```
  for (const auto* value_info : value_info_) {
    *(graph_proto.mutable_value_info()->Add()) = value_info->ToProto();
  }
```
where we will attempt to dereference the `nullptr` we had previously added to the `value_info` array and crash.

Since value_info for an edge that does not exist can be safely removed, I believe a simple null check before adding should guard against this.

**Urgency**
P3 severity.

**Expected behavior**
Extra value_info entries should not crash model serializer.

**Comment by pranavsharma** [comment]
@pranav-prakash  Looks like a simple enough change. Would you like to contribute?
