### ISSUE TITLE
Onnxruntime profiler  produces empty log in C# under certain circumstances

### ISSUE THREAD

**Issue by ggeor84** [microsoft/onnxruntime#3436]
**Describe the bug**
Under certain circumstances, C# API produces an empty profiling log.

**Urgency**
Medium

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.2.0
- Python version: 3.7.6
- Visual Studio version (if applicable): VS 2017
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
This can be reproduced by instantiating the session as follows:
            options.GraphOptimizationLevel = optLevel;
            options.EnableProfiling = true;
            var session = new InferenceSession(modelPath, options);   

if enclosed in using () then a profiling log file is produced. But if instantiated as above, it produces an empty log file. (0 bytes). 
The bug can be reproduced by editing the Microsoft.ML.OnnxRuntime.PerfTool. See attached file.

**Expected behavior**
Produce a complete log file

**Screenshots**
N/A

**Additional context**
N/A
[Program.txt](https://github.com/microsoft/onnxruntime/files/4440491/Program.txt)

**Comment by hariharans29** [comment]
A call to EndProfiling() is required for the events to get written to the profile file - https://github.com/microsoft/onnxruntime/blob/edd5855fb7b7ed9e66c48d6fb2816ea7b4b8e068/onnxruntime/core/session/inference_session.h#L323. The reason why you were seeing events written when you were coding with using() {...} is that `using`  disposes the InferenceSession at the end of the block and the Dispose() method triggers destruction of the native InferenceSession which in its destructor calls EndProfiling() - https://github.com/microsoft/onnxruntime/blob/edd5855fb7b7ed9e66c48d6fb2816ea7b4b8e068/onnxruntime/core/session/inference_session.cc#L297.

Looks like we need to expose `EndProfiling`  as a CSharp API to support the non-using() {...} use-case.
