### ISSUE TITLE
Flatten Op with Negative Axis Not supported?

### ISSUE THREAD

**Issue by dibya001** [microsoft/onnxruntime#3440]
**Describe the bug**

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.2.0
- Python version: 3.5
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by dibya001** [comment]
With Negative value for axis attribute, I am getting below error:-
**[ONNXRuntimeError] : 1 : FAIL : Node () Op (Flatten) [ShapeInferenceError] Invalid value(-2) for attribute 'axis'**


Negative value for axis attribute for Flatten Op is introduced in OpVer 11, As per the docs it should be supported in ONNXRUNTIME(The version I am using is 1.2.0).

**Comment by snnn** [comment]
The exception was throw from this line:
https://github.com/onnx/onnx/blob/rel-1.6.0/onnx/defs/nn/defs.cc#L1754

Please submit the bug to ONNX.
