### ISSUE TITLE
Example for Handling ONNXType other than ONNX_TYPE_TENSOR

### ISSUE THREAD

**Issue by GuanLuo** [microsoft/onnxruntime#3444]
**Is your feature request related to a problem? Please describe.**
I have a program using the C library of ORT, which assumes the ONNX model's I/O are always type Tensor, but I encountered one model converted from sklearn that has output type `sequence<map<int64,float32>>`. I saw that there were APIs regarding sequence and map type, so I wonder if there are examples to handle such I/O? i.e. running the model and retrieving the output.

**Additional context**
The model is a simple logistic regression:
```Python
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression, LogisticRegression
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType
from sklearn.linear_model import LinearRegression, LogisticRegression
import numpy as np

iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y)

logr = LogisticRegression()
fake_y = (X_train[:, 0] > 5.2).astype("int")
logr.fit(X_train, fake_y)

initial_type = [('float_input', FloatTensorType([None, 4]))]
onx = convert_sklearn(logr, initial_types=initial_type)
with open("logr.onnx", "wb") as f:
    f.write(onx.SerializeToString())
```

**Comment by pranavsharma** [comment]
Take a look at this file https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_nontensor_types.cc. It demonstrates the creation and retrieval of non-tensor types. Once you've the OrtValue (containing a non-tensor type) constructed, you just need to call Run() as usual.

**Comment by GuanLuo** [comment]
Thanks. Will take a look
