### ISSUE TITLE
op "Div" not supports double input while double is said to be supported in onnx

### ISSUE THREAD

**Issue by zhijxu-MS** [Microsoft/onnxruntime#345]
also, the output error log "run_onnx FAIL [ONNXRuntimeError] : 1 : GENERAL ERROR : No suitable kernel definition found for op Div(7)" is wrong

the error log seems like to be "run_onnx FAIL [ONNXRuntimeError] : 1 : GENERAL ERROR : No suitable kernel definition found for op **Div(11)**"

**Comment by snnn** [comment]
I wrote the error message. The number is opset number. 
And the behavior is expected. Most kernels in onnxruntime only support float.

**Comment by snnn** [comment]
Do we support every type(e.g. float, double,int32,...)  of every operator?
No.

**Comment by pengwa** [comment]
Is it a long term plan or short term one limited by working resources? 

So perf tuning team would complain why we have so many Cast can Cas (back) in the converted onnx model.

**Comment by snnn** [comment]
Long term. But we can discuss it.

**Comment by pengwa** [comment]
Thanks for the explanation,  while this answer just makes me suspicious about the statement in the project description: 

```
Run any ONNX model

Alignment with ONNX Releases
ONNX Runtime provides comprehensive support of the ONNX spec and can be used to run all models based on ONNX v1.2.1 and higher. See ONNX version release details here.
```

Any way, this is not easy to achieve, I can understand.
