### ISSUE TITLE
Excuse me, is there an example of GPU loading model and testing?

### ISSUE THREAD

**Issue by huang229** [microsoft/onnxruntime#3451]
Excuse me, is there an example of GPU loading model and testing? thank you!!

**Comment by pranavsharma** [comment]
Which API do you plan to use? Python/C/C#/Java?

**Comment by huang229** [comment]
Python

**Comment by pranavsharma** [comment]
I assume you're using the onnxruntime-gpu python pkg. If yes, the example is same as that of CPU. See https://github.com/microsoft/onnxruntime/tree/master/samples#Python.

**Comment by huang229** [comment]
Thank you very much for your help.
