### ISSUE TITLE
the inference speed of onnx model is slower than the pytorch model

### ISSUE THREAD

**Issue by MrCrazyCrab** [microsoft/onnxruntime#3452]
**the inference speed of onnx model is slower than the pytorch model. i transformed of my pytorch model to onnx, but when i run the test code, i found that the inference speed of onnx model is about 20fps while the pytorch model can reach about 50fps. At the meatime, it takes about 1G of GPU for pytorch model while the onnx model spend about 600M. i couldn't understand that why the performace of onnx is more terribel than pytorch,  it should be more efficient**

**System information**
- OS Platform and Distribution (windows10):
- ONNX Runtime installed from (pypi):
- ONNX Runtime version: 1.1.0
- Python version:3.6.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.0/7.6.0
- GPU model and memory:

**Comment by pranavsharma** [comment]
In the case of pytorch you’re setting up your inputs to be on the GPU prior to inferencing your model. Onnxruntime doesn’t provide a way to do so. It copies the inputs from CPU to GPU as part of Run. This takes time. Hence the difference. 

Can you share the model and script you’re using to run the model for both pytorch and onnruntime?

**Comment by MrCrazyCrab** [comment]
@pranavsharma  Thanks for your reply , and i'm so sorry for some reason i can't share the code. I do set up the inputs on the GPU in pytorch. I want to do the same opration, but i couldn't find out a way. could you share some experience of how to accelarate the onnx model for the situation of inputs copied from CPU to GPU?

**Comment by pranavsharma** [comment]
Unfortunately, at this time we don't have this. The capability is in PR though and should be available as soon as the PR is merged.

**Comment by MrCrazyCrab** [comment]
@pranavsharma , thank you. And what is PR, could you give it full name?

**Comment by pranavsharma** [comment]
It's coming in as part of a larger PR - https://github.com/microsoft/onnxruntime/pull/3174.

**Comment by pranavsharma** [comment]
If you want to test the performance before this PR is merged, you can try our internal C++ API. This requires building the code. Here's an example: https://gist.github.com/pranavsharma/11a1468368a80d6b94a4d9f67b506861. This should rule out the cost of copying inputs from cpu to gpu.

The other thing you can try now is to see which nodes in your model are getting assigned to the GPU by setting the verbosity to 0 like ```ort.set_default_logger_severity(0)```.

**Comment by solarflarefx** [comment]
@pranavsharma Are you saying that direct GPU inference will be available when the PR is merged?  Would this reflect all the APIs?  For example, would one be able to perform inference on input tensors already in the GPU using the C# API?

**Comment by xsacha** [comment]
@solarflarefx That is my understanding. I am also waiting for this PR until I integrate with ONNXRuntime.

See: https://github.com/microsoft/onnxruntime/blob/5d99f179b9aad05d6fc5f1fe7565b40788709b21/include/onnxruntime/core/framework/kernel_def_builder.h#L67

The main change is you can now specify what device the input and output will be on. So, for instance, you can pick a device that is *not* a CPU.
