### ISSUE TITLE
Execution error running 3D convolutions with ONNX runtime

### ISSUE THREAD

**Issue by danperazzo** [microsoft/onnxruntime#3453]
**Describe the bug**
I have converted a model from tensorflow into ONNX using tf2onnx. Since I have run into [the problem that tf2onnx does not support 3D convolutions](https://github.com/onnx/tensorflow-onnx/issues/461). Then, I modified the script so that it could perform 3D convolutions. Now I have my model translated to ONNX. However, when I run it on runtime, it works for CPU however it throws an error on GPU exactly on the 3D convolution ops.  The message is this one:

`Status Message: Input channels C is not equal to kernel channels * group. C: 0 kernel channels: 7 group: 1`

Am I the only one that got this error while using 3D convolutions on GPU?

I can also send my script to handle the translation from tensorflow to ONNX.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary):binary
- ONNX Runtime version: 1.2.0
- Python version: ---
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source): --
- CUDA/cuDNN version: 10.1/7.6.5
- GPU model and memory: 1050Ti, 4Gb

**Comment by hariharans29** [comment]
This looks like a converter bug. Number of channels (C) cannot be 0 in the input tensor being fed to the Conv node

**Comment by danperazzo** [comment]
That's what I thought. However, It runs alright on the CPU

**Comment by hariharans29** [comment]
Can you share a very simple version of the model that we can use to repro ?

**Comment by danperazzo** [comment]
Sorry for the delay. Below are some files for reproduction. model.onnx  is the aforementioned toy version of the model. test_rt.py is the example I have been using to perform the inference and see the error. test.py is where I got the model in tensorflow.  And nn.py is an alteration on tf2onnx script so that it can support 3D convnets. I have been getting different results for onnxruntime and onnxruntime-gpu. Again, thanks for the help :))

[test.zip](https://github.com/microsoft/onnxruntime/files/4541370/test.zip)

**Comment by hariharans29** [comment]
I couldn't hit the specific error you are hitting - Please see how I generated the input ( just like your test script) and output - 

```
import numpy as np
import onnx
from onnx import numpy_helper

# Preprocessing: create a Numpy array
numpy_array_input = np.zeros([1,144,578,32,7],dtype=np.float32) + 100
input_tensor = numpy_helper.from_array(numpy_array_input)

# Save the TensorProto
with open(r'repro\test_data_set_0\input_0.pb', 'wb') as f:
    f.write(input_tensor.SerializeToString())

numpy_array_output = np.random.rand(1,144,578,32,32).astype(np.float32)
output_tensor = numpy_helper.from_array(numpy_array_output)

# Save the TensorProto
with open(r'repro\test_data_set_0\output_0.pb', 'wb') as f:
    f.write(output_tensor.SerializeToString())

```

I built from master and used the onnx_test_runner.cc to run the model with the above inputs and I get the result mis-match error which is expected given that we have random inputs but didn't hit the error that you hit. Can you try re-building from master and giving it a shot ?

**Comment by hariharans29** [comment]
![image](https://user-images.githubusercontent.com/9969784/81248224-bae8a600-8fd0-11ea-9338-612e3c3ef38e.png)

**Comment by hariharans29** [comment]
Notice that it doesn't hit the error and only complains about result mis-match

**Comment by hariharans29** [comment]
Closing for now, please re-open if you have more follow-up questions.
