### ISSUE TITLE
How to get objects scores from output in Yolov3

### ISSUE THREAD

**Issue by hoaquocphan** [microsoft/onnxruntime#3464]
Hi All,

I'm porting [Yolo v3](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny_yolov3) on [onnxruntime ](https://github.com/microsoft/onnxruntime/tree/rel-1.0.0) by C code.

The model run successfully and have 3 output as defined in  [Yolo v3](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny_yolov3) 
[My boxes:](https://github.com/hoaquocphan/Tiny_Yolo_v3/blob/master/boxes.txt)
```
-101.76323699951172
-12.98329353332520
.
.
.
216.74037170410156
1.44414448738098
```

[My scores:](https://github.com/hoaquocphan/Tiny_Yolo_v3/blob/master/scores.txt)
```
-0.00000000298391
-0.00000000769582
.
.
.
-0.00000000405639
0.00000001776875
```
[My indices:](https://github.com/hoaquocphan/Tiny_Yolo_v3/blob/master/indices.txt)
```
0
1
251
0
7
108
0
16
319
```
With the [indices:](https://github.com/hoaquocphan/Tiny_Yolo_v3/blob/master/indices.txt), I can detect the bicycle, truck, dog, as below:

```
Result 1
Detected        : bicycle
Bounding Box    : (X, Y, W, H) = (169.03, 203.06, 340.61, 235.45)
Score           : 

Result 2
Detected        : truck
Bounding Box    : (X, Y, W, H) = (332.86, 92.03, 142.98, 61.44)
Score           : 

Result 3
Detected        : dog
Bounding Box    : (X, Y, W, H) = (76.96, 277.38, 128.82, 226.34)
Score           : 
```

but I don't know how to get the objects score  as the guide in  [Yolo v3](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny_yolov3), the guide is too simple. 
So could anyone help me about this?

Thanks

**Comment by hoaquocphan** [comment]
complete by myself

**Comment by goodtogood** [comment]
@hoaquocphan 
Hi, I'v the same problem. would you  like to share your code?
thx!

**Comment by hoaquocphan** [comment]
Hi @goodtogood 

I would like to share a snippet of my code:


```
    // Get pointer to output tensor float values
    float* out1 = NULL;
    g_ort->GetTensorMutableData(output_tensor[0], (void**)&out1);
    float* out2 = NULL;
    g_ort->GetTensorMutableData(output_tensor[1], (void**)&out2);
    int* out3 = NULL;
    g_ort->GetTensorMutableData(output_tensor[2], (void**)&out3);

    if(out3 != NULL)
    {
        for(size_t i = 0; i<10000; i+=3){
            //if((out3[i] < 0) || (out3[i] > 2535)) break; // for tinyyolov3
            if((out3[i] < 0) || (out3[i] > 10647)) break; // for yolov3
            float ymin = out1[out3[i+2]*4];
            float xmin = out1[out3[i+2]*4+1];
            float ymax = out1[out3[i+2]*4+2];
            float xmax = out1[out3[i+2]*4+3];
            Box bb = float_to_box((xmin+xmax)/2, (ymin+ymax)/2, xmax-xmin, ymax-ymin);
            float objectness = 1;
            int detected = out3[i+1];
            float score = out2[10647 * out3[i+1] + out3[i+2]];
            detection d = { bb, objectness , detected,score };
            det.push_back(d);
            count++;
        }
    }
```
Hope that this code will help you.

**Comment by goodtogood** [comment]
@hoaquocphan 
thank you so much!
