### ISSUE TITLE
C# API Convert inference output to array

### ISSUE THREAD

**Issue by solarflarefx** [microsoft/onnxruntime#3467]
I am new to the C# API and am trying to convert my inference output to an array:

`
                    SessionOptions options = new SessionOptions();
                    options.GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_EXTENDED;

                    using (var session = new InferenceSession(modelPath, options))
                    {
                        var inputMeta = session.InputMetadata;
                        var container = new List<NamedOnnxValue>();

                        var inputData = patch.ToArray<float>();

                        foreach (var name in inputMeta.Keys)
                        {
                            var dim = inputMeta[name].Dimensions;
                            dim[0] = 1;
                            var tensor = new DenseTensor<float>(inputData, dim);
                            container.Add(NamedOnnxValue.CreateFromTensor<float>(name, tensor));
                        }

                        // Run the inference
                        using (var results = session.Run(container))  // results is an IDisposableReadOnlyCollection<DisposableNamedOnnxValue> container
                        {
                            // dump the results
                            foreach (var r in results)
                            {
                                var p = r.AsTensor<float>();
                                var q = r.AsEnumerable<float>();
                                Console.WriteLine("Output for {0}", r.Name);
                                Console.WriteLine(r.AsTensor<float>().GetArrayString());
                            }
                        }
                    }
`

I was trying to experiment with converting "r" to different types but was not yet able to convert to an array.

**Comment by solarflarefx** [comment]
I found the following issue: https://github.com/microsoft/onnxruntime/issues/693

In it, the poster gave the following example:

`
            using (var results = _session.Run(inputs))
            {
                return results.First().AsEnumerable<float>().ToArray();
            }
`

However, in my above code if I try:
`
   var p = r.AsEnumerable<float>().ToArray()
`

The ".ToArray()" method does not exist.

It seems I can do the other method, but is it efficient?
`
    r.AsTensor<float>().ToDenseTensor().Buffer.ToArray();
`

Ultimately I am trying to build up a 3D array from 2D elements.  My network outputs 2D elements and I keep iterating to build up a 3D structure.  Is there a better approach to what I am trying to achieve?

**Comment by solarflarefx** [comment]
To be more efficient, can I somehow make use of a [BlockCopy](https://docs.microsoft.com/en-us/dotnet/api/system.buffer.blockcopy?view=netframework-4.8)?
`
     System.Buffer.BlockCopy(outputTensorArray, 0, myArray, dstOffset, outputTensorArray.Length);
`

Is there a way to copy the elements without doing:

`
     r.AsTensor<float>().ToDenseTensor().Buffer.ToArray();
`

**Comment by hoaquocphan** [comment]
Hi @solarflarefx 

I'm new  in the C# API,
I see the example about C# [here](https://github.com/microsoft/onnxruntime/blob/master/docs/CSharp_API.md), I can see the sample source code but I don't know how to run it 
in Python API, I just run it on linux terminal,
in C/C++ API, I build the code and run the execute file on Linux.
but how to build the C# to run the simple onnx model?

Please explain it for me?
Thanks

**Comment by solarflarefx** [comment]
@hoaquocphan 
I am using Windows so in Visual Studio I created a new C# project and added ONNX Runtime through the NuGet package manager.  All the necessary DLLs then get included.  You can then essentially copy/paste the code from the example from there, or include that file in your C# project.

**Comment by digitalmonkey** [comment]
I had the same issues with @solarflarefx , with ToArray(), First() and ToList() are all not defined on the results of the Run().
I'm on Unity on a MacOS machine. I could only use the foreach to enumerate of the results.
