### ISSUE TITLE
QlinearConv  support for per channel and  int8?

### ISSUE THREAD

**Issue by dongzhen123** [microsoft/onnxruntime#3478]
Hi,

When can we expect the implementation/support for INT8 in QLinearConv node and per channel mode?

**Comment by yufenglee** [comment]
@dongzhen123 , we are implementing u8s8 (unsigned int8/signed int8) for QLinearConv. Do you mean s8s8 for 'INT8 in QLinearConv' or u8s8? If s8s8, what makes you prefer this format? 

Per-channel mode is in our backlog.

**Comment by dongzhen123** [comment]
> @dongzhen123 , we are implementing u8s8 (unsigned int8/signed int8) for QLinearConv. Do you mean s8s8 for 'INT8 in QLinearConv' or u8s8? If s8s8, what makes you prefer this format?
> 
> Per-channel mode is in our backlog.

I mean  u8s8 that is uint8 act and int8(sym mode) weight.

**Comment by yufenglee** [comment]
@dongzhen123 , we are still working on u8s8.
