### ISSUE TITLE
SKlearn KNeighborsRegressor ONNX model run problem

### ISSUE THREAD

**Issue by whjdark** [microsoft/onnxruntime#3505]
**Describe the bug**
SKlearn KNeighborsRegressor model run problem:
HINTS:
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:Ar_ArrayFeatureExtractor : No Op registered for ArrayFeatureExtractor with domain_version of 11

**System information**
- OS Platform : windows10
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.2.0
- Python version: 3.7.6
- sklearn version: 0.22.2.post1
- skl2onnx version:1.6.0

**To Reproduce**
Can try to bulid a KNeighborsRegressor model on NEW version sklearn.
It seems that ONNX Runtime do not support new version sklearn KNeighborsRegressor model(0.22.2.post1) , because new version had some changes on KNeighborsRegressor part.

**Comment by snnn** [comment]
@xadupre could you please take a look?
