### ISSUE TITLE
Error in Trying to Use TensorRT Backend with ONNX Model

### ISSUE THREAD

**Issue by caesarnine** [microsoft/onnxruntime#3506]
**Describe the bug**
I've been using Triton Inference Server with an ONNX model that has worked correctly, and continues to work correctly. I tried to switch over to using the TensorRT Execution Provider and received the following error:

```Unsupported ONNX data type: BOOL (9)```

I created an issue in Triton's project as well, but this seems like it may be coming from the runtime and not the inference server itself:

https://github.com/NVIDIA/triton-inference-server/issues/1301

For context - I took a model from the transformers library (XLMRobertaForTokenClassification), converted that into ONNX, and then tried to switch over to using the TensorRT execution provider. 

**Urgency**
No hard deadlines and not urgent.

**System information**
- Triton Inference Server Container - version py3-20.03
- GPU model and memory: T4/16GB

**To Reproduce**
- Convert the XLMRobertaForTokenClassification into ONNX
- Try and run it in Triton using the TensorRT Execution Provider instead of CUDA

**Expected behavior**
I expect it to convert without an error. In general I understand not all operations may be supported, but I was surprised to see an error being thrown on a BOOL datatype.

**Comment by jywu-msft** [comment]
Is it possible to share the model or provide a repro?
