### ISSUE TITLE
C++ API: Missing features in comparison to C API

### ISSUE THREAD

**Issue by Jonas-Heinrich** [microsoft/onnxruntime#3517]
I am currently working on another project that makes use of the `C++` API via `onnxruntime/include/onnxruntime/core/session`.

When comparing the `C++` API to the `C` API, I have found several `C` features that are not exposed in `C++`. For example:

- `SequenceTypeInfo`, `GetSequenceTypeInfo`, `GetSequenceElementType`
- `MapTypeInfo`, `GetMapTypeInfo`, `GetMapKeyType`, `GetMapValueType`

In a private fork, I made these available by changing the `onnxruntime_cxx_api.h` and `onnxruntime_cxx_inline.h`.

Are there plans to make everything available in the `C++` API? Am I missing an obvious reason as to why they are not supported?

**System information**

- ONNX Runtime version (you are using): custom build (master, currently based on 40d80cde8)

**Describe alternatives you've considered**

I could continue maintaining these changes in my local fork - I'd rather not.

If you want me to, I could open a pull request with some of the mentioned functions in the `C++` API.

**Comment by pranavsharma** [comment]
Feel free to create a PR. Contributions are most welcome.

**Comment by Jonas-Heinrich** [comment]
> Feel free to create a PR. Contributions are most welcome.

Nice, if I find the time (and my manager approves it) I'll be sure to open one.
