### ISSUE TITLE
ONNX Runtime Build Issues on Win10 x64 Visual Studio 2019

### ISSUE THREAD

**Issue by solarflarefx** [microsoft/onnxruntime#3521]
**Describe the issue**
Ultimately I am trying to run inference on a model using the C# API.  I am trying to get the inference to be more efficient, so I tried building from source using [these instructions](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md) as a guide.  However, I get some errors described below.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-bit
- ONNX Runtime installed from (source or binary): Source
- ONNX Runtime version: [commit efd9b924824922e9f281e1859fbfecf963e176c1 ](https://github.com/microsoft/onnxruntime/commit/efd9b924824922e9f281e1859fbfecf963e176c1)
- Visual Studio version (if applicable): 2019 Professional
- CUDA/cuDNN version: 10.2/7.6.5
- TensorRT Version: TensorRT-7.0.0.11.Windows10.x86_64.cuda-10.2.cudnn7.6

**To Reproduce**
I took the source code using Git and then ran the following using Developer Command Prompt for VS 2019

build.bat  --cmake_path "C:\Program Files\CMake\bin\cmake.exe" --config RelWithDebInfo --build_shared_lib --build_csharp --parallel --use_cuda --cuda_version 10.2 --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --use_tensorrt --tensorrt_home "C:\TensorRT\TensorRT-7.0.0.11.Windows10.x86_64.cuda-10.2.cudnn7.6\TensorRT-7.0.0.11" --use_dnnl --cmake_generator "Visual Studio 16 2019" --skip_tests

One thing I will note is that in the above my CUDA and cuDNN paths are the same.  That's because I followed [these instructions](https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#installwindows) and copied the bin, include, and lib folders of the cuDNN package into my CUDA 10.2 diectory.

Most of the build seems to have gone through but I also got some errors related to C#.

**Errors**

The following is in my CMakeError.log.  The one that concerns me is: **"The CSharp compiler identification could not be found"**
`
The CSharp compiler identification could not be found in "C:/ONNXRuntime/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/3.16.4/CompilerIdCSharp/CompilerIdCSharp.csproj"

Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/ONNXRuntime/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe cmTC_0bee7.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.25.28612 for x64

  CheckIncludeFile.c

  Copyright (C) Microsoft Corporation.  All rights reserved.

  cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_0bee7.dir\Debug\\" /Fd"cmTC_0bee7.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue  /d2FH4- C:\ONNXRuntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\CheckIncludeFile.c

C:\ONNXRuntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1,10): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\ONNXRuntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\cmTC_0bee7.vcxproj]

Performing C++ SOURCE FILE Test HAS_QSPECTRE failed with the following output:
Change Dir: C:/ONNXRuntime/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe cmTC_72841.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(436,5): error MSB8040: Spectre-mitigated libraries are required for this project. Install them from the Visual Studio installer (Individual components tab) for any toolsets and architectures being used. Learn more: https://aka.ms/Ofhn4c [C:\ONNXRuntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\cmTC_72841.vcxproj]

Source file was:
int main() { return 0; }
Detecting CUDA compiler ABI info failed to compile with the following output:
Change Dir: C:/ONNXRuntime/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe cmTC_5daf4.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Compiling CUDA source file ..\..\..\..\..\..\..\Program Files\CMake\share\cmake-3.16\Modules\CMakeCUDACompilerABI.cu...

  

  C:\ONNXRuntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\nvcc.exe" -gencode=arch=compute_30,code=\"sm_30,compute_30\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.25.28610\bin\HostX64\x64" -x cu   -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include"     --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart shared -Xcompiler="-Zi -Ob0 -v" -g   -D"CMAKE_INTDIR=\"Debug\"" -D"CMAKE_INTDIR=\"Debug\"" -D_MBCS -Xcompiler "/EHsc /W1 /nologo /Od /FdcmTC_5daf4.dir\Debug\vc142.pdb /FS /Zi /RTC1 /MDd " -o cmTC_5daf4.dir\Debug\CMakeCUDACompilerABI.obj "C:\Program Files\CMake\share\cmake-3.16\Modules\CMakeCUDACompilerABI.cu" 

cl : Command line warning D9002: ignoring unknown option '-v' [C:\ONNXRuntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\cmTC_5daf4.vcxproj]

cl : Command line warning D9002: ignoring unknown option '-v' [C:\ONNXRuntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\cmTC_5daf4.vcxproj]

  CMakeCUDACompilerABI.cu

cl : Command line warning D9002: ignoring unknown option '-v' [C:\ONNXRuntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\cmTC_5daf4.vcxproj]

LINK : warning LNK4044: unrecognized option '/v'; ignored [C:\ONNXRuntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\cmTC_5daf4.vcxproj]

LINK : error LNK1218: warning treated as error; no output file generated [C:\ONNXRuntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\cmTC_5daf4.vcxproj]

Checking whether the ASM_MASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
Microsoft (R) Macro Assembler (x64) Version 14.25.28612.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : --version
MASM : fatal error A1017:missing source filename
Checking whether the ASM_MASM compiler is Clang using "--version" did not match "(clang version)":
Microsoft (R) Macro Assembler (x64) Version 14.25.28612.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : --version
MASM : fatal error A1017:missing source filename
Checking whether the ASM_MASM compiler is AppleClang using "--version" did not match "(Apple LLVM version)":
Microsoft (R) Macro Assembler (x64) Version 14.25.28612.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : --version
MASM : fatal error A1017:missing source filename
Checking whether the ASM_MASM compiler is ARMClang using "--version" did not match "armclang":
Microsoft (R) Macro Assembler (x64) Version 14.25.28612.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : --version
MASM : fatal error A1017:missing source filename
Checking whether the ASM_MASM compiler is HP using "-V" did not match "HP C":
Microsoft (R) Macro Assembler (x64) Version 14.25.28612.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : -V
MASM : fatal error A1017:missing source filename
Checking whether the ASM_MASM compiler is Intel using "--version" did not match "(ICC)":
Microsoft (R) Macro Assembler (x64) Version 14.25.28612.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : --version
MASM : fatal error A1017:missing source filename
Checking whether the ASM_MASM compiler is SunPro using "-V" did not match "Sun C":
Microsoft (R) Macro Assembler (x64) Version 14.25.28612.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : -V
MASM : fatal error A1017:missing source filename
Checking whether the ASM_MASM compiler is XL using "-qversion" did not match "XL C":
Microsoft (R) Macro Assembler (x64) Version 14.25.28612.0
Copyright (C) Microsoft Corporation.  All rights reserved.

MASM : warning A4018:invalid command-line option : -qversion
MASM : fatal error A1017:missing source filename

`

**Additional questions**
1. After building my understanding was that I can use the built DLLs in my C# project.  Is that correct?  Which DLLs should be generated?  My build generated the following:
- dnnl.dll
- onnxruntime.dll
- nvonnxparser.dll
- custom_op_library.dll

2. Using [this issue](https://github.com/microsoft/onnxruntime/issues/2773) as a guide, it seems the following DLLs did not get built:
cublas64_10.dll
cublasLt64_10.dll
cudart64_101.dll
cudnn64_7.dll
nvinfer.dll
nvinfer_plugin.dll
onnxruntime.dll

Though it seems as though I have most of the other DLLs from my CUDA, cuDNN, and TensorRT directories.  

Ultimately I just wanted to make sure there is nothing wrong with my build.  

Thanks in advance.

**Comment by solarflarefx** [comment]
So I think those errors are fine as it looks like the build was successful.  However, when I tried to add onnxruntime.dll to my C# project as a reference, it said that it was not a valid COM component.  Was my build output also supposed to include other files that need to be added to my project?

Or am I supposed to use the NuGet ONNX Runtime package and then replace the onnxruntime DLL in the C# executable output directory?

**Comment by skottmckay** [comment]
onnxruntime.dll is a native dll. I would expect you need to reference the C# wrapper dll in a C# library. Building the C# solution (csharp\OnnxRuntime.CSharp.sln) should produce something like csharp\src\Microsoft.ML.OnnxRuntime\bin\Debug\netstandard1.1\Microsoft.ML.OnnxRuntime.dll

Not sure if that is automatically built with the build script. If not it should be if --build_csharp is provided as a flag.

**Comment by solarflarefx** [comment]
@skottmckay Thanks for the reply.

So I had run this command:
build.bat --cmake_path "C:\Program Files\CMake\bin\cmake.exe" --config RelWithDebInfo --build_shared_lib **--build_csharp** --parallel --use_cuda --cuda_version 10.2 --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --use_tensorrt --tensorrt_home "C:\TensorRT\TensorRT-7.0.0.11.Windows10.x86_64.cuda-10.2.cudnn7.6\TensorRT-7.0.0.11" --use_dnnl --cmake_generator "Visual Studio 16 2019" --skip_tests

However, it seems as though a new Microsoft.ML.OnnxRuntime.dll did not get built.

**Comment by skottmckay** [comment]
Can you build it successfully using <root dir>\csharp\OnnxRuntime.CSharp.sln?

**Comment by solarflarefx** [comment]
@skottmckay 

A few things.

So I decided to try to start from a clean directory so I cloned the git repository to that directory  I ran the same build command again using Develop Command Prompt.  

I checked CMakeOutput.log and got:
`
Looking for a CSharp compiler passed with the following output:
-- The CSharp compiler identification is Microsoft unknown 9999
-- The CSharp compiler version is 3.5.0
-- Check for working C# compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/Roslyn/csc.exe
-- Check for working C# compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/Roslyn/csc.exe -- works
-- Configuring done
-- Generating done
-- Build files have been written to: C:/ONNXRuntime/onnxruntime/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CheckCSharp

Compiling the CSharp compiler identification source file "CMakeCSharpCompilerId.cs" succeeded.
Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/Roslyn/csc.exe 
Build flags: 
Id flags:  

The output was:
0
Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Project "C:\ONNXRuntime\onnxruntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\3.16.4\CompilerIdCSharp\CompilerIdCSharp.csproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "obj\x64\Debug\".
GenerateTargetFrameworkMonikerAttribute:
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
  Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Roslyn
CopyFilesToOutputDirectory:
  Copying file from "C:\ONNXRuntime\onnxruntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\3.16.4\CompilerIdCSharp\obj\x64\Debug\CompilerIdCSharp.exe" to "C:\ONNXRuntime\onnxruntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\3.16.4\CompilerIdCSharp\CompilerIdCSharp.exe".
  CompilerIdCSharp -> C:\ONNXRuntime\onnxruntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\3.16.4\CompilerIdCSharp\CompilerIdCSharp.exe
  Copying file from "C:\ONNXRuntime\onnxruntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\3.16.4\CompilerIdCSharp\obj\x64\Debug\CompilerIdCSharp.pdb" to "C:\ONNXRuntime\onnxruntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\3.16.4\CompilerIdCSharp\CompilerIdCSharp.pdb".
PostBuildEvent:
  if not "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Roslyn"=="" if exist "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Roslyn\csc.exe" set _CSC=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Roslyn
  if exist "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\csc.exe" set _CSC=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin
  if "%_CSC%"=="" exit -1
  @echo CMAKE_CSharp_COMPILER=%_CSC%\csc.exe
  CMAKE_CSharp_COMPILER=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Roslyn\csc.exe
Done Building Project "C:\ONNXRuntime\onnxruntime\onnxruntime\build\Windows\RelWithDebInfo\CMakeFiles\3.16.4\CompilerIdCSharp\CompilerIdCSharp.csproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.43

Compilation of the CSharp compiler identification source "CMakeCSharpCompilerId.cs" produced "CompilerIdCSharp.csproj"

Compilation of the CSharp compiler identification source "CMakeCSharpCompilerId.cs" produced "CompilerIdCSharp.exe"

Compilation of the CSharp compiler identification source "CMakeCSharpCompilerId.cs" produced "CompilerIdCSharp.pdb"

The CSharp compiler identification is Microsoft unknown, found in "C:/ONNXRuntime/onnxruntime/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/3.16.4/CompilerIdCSharp/CompilerIdCSharp.exe"

Determining if the C# compiler works passed with the following output:
Change Dir: C:/ONNXRuntime/onnxruntime/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe cmTC_a6d41.csproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.
`

So it appears everything is fine, but I wanted to double check the errors so I opened CMakeError.log:
`
The CSharp compiler identification could not be found in "C:/ONNXRuntime/onnxruntime/onnxruntime/build/Windows/RelWithDebInfo/CMakeFiles/3.16.4/CompilerIdCSharp/CompilerIdCSharp.csproj"
`

I'm not sure if this was just a one time error that then succeeded.

So I tried to open \csharp\OnnxRuntime.CSharp.sln and got the following error:
Detailed Information:
Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.

I looked at my Visual Studio Installer and saw:
![image](https://user-images.githubusercontent.com/45402633/80602264-e2ea6f00-89fc-11ea-9722-494582349211.png)

It looks like I have the .NET Core SDK.  Does this have to do with the error in CMakeError.log?

**Comment by skottmckay** [comment]
If the build succeeds I don't think the output in CMakeFiles\CMakeErrors.log is relevant. CMake runs lots of tests to determine what's available/configured, and some are expected to fail. The output from these ends up in that file. I see the same error about the compiler identification not being found but have no issues loading the C# solution.

I have the same VS 2019 version with similar (fewer) SDKs installed.
> dotnet --list-sdks
2.1.500 [C:\Program Files\dotnet\sdk]
2.1.502 [C:\Program Files\dotnet\sdk]
2.1.503 [C:\Program Files\dotnet\sdk]
2.1.505 [C:\Program Files\dotnet\sdk]
2.1.507 [C:\Program Files\dotnet\sdk]
2.1.508 [C:\Program Files\dotnet\sdk]
2.1.511 [C:\Program Files\dotnet\sdk]
2.1.513 [C:\Program Files\dotnet\sdk]
3.1.201 [C:\Program Files\dotnet\sdk]

We're targeting a very basic .NET version so that should be sufficient.

![image](https://user-images.githubusercontent.com/979079/80658658-0deec480-8aca-11ea-8eb3-c5223e6364da.png)

When you load the solution do the dependencies get restored/resolved, including NETStandard.Library?
 
![image](https://user-images.githubusercontent.com/979079/80658614-e566ca80-8ac9-11ea-8a95-e45dc4164e4e.png)

**Comment by solarflarefx** [comment]
So here is my VS Window:
![image](https://user-images.githubusercontent.com/45402633/80665667-1dd5bc80-8a68-11ea-9a61-df259661591e.png)

I can't even get to the project properties window because the project will not load.

The error in the output window says:
C:\ONNXRuntime\onnxruntime\onnxruntime\csharp\test\Microsoft.ML.OnnxRuntime.Tests\Microsoft.ML.OnnxRuntime.Tests.csproj : error  : The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.

Detailed Information:
Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.

**Comment by skottmckay** [comment]
Can you right-click on one of the projects in Solution Explorer and reload it to see what additional info you get in the Output window? Sometimes that can provide more useful error messages.

**Comment by solarflarefx** [comment]
@scottmckay I tried doing that but unfortunately all I got was:

![image](https://user-images.githubusercontent.com/45402633/80867747-c8fe9580-8c63-11ea-8704-16e1f298004f.png)

![image](https://user-images.githubusercontent.com/45402633/80867778-e3387380-8c63-11ea-8336-e00d00803df3.png)

**Comment by solarflarefx** [comment]
OK I repaired my installation using my VS Installer and the project seems to open.  However, when I try to build the "Microsoft.ML.OnnxRuntime" project, I get an error:
Could not copy the file "C:\ONNXRuntime\onnxruntime\onnxruntime\build\Windows\Debug\Debug\onnxruntime.dll" because it was not found.

I went to "C:\ONNXRuntime\onnxruntime\onnxruntime\build\Windows" to look at the directory structure:
![image](https://user-images.githubusercontent.com/45402633/80923080-3affd900-8d4f-11ea-923a-162943e80f99.png)

I don't have a "Debug" directory in that folder.

If I go into the "RelWithDebInfo" folder:
![image](https://user-images.githubusercontent.com/45402633/80923105-6c78a480-8d4f-11ea-9de0-5ab4665199e0.png)

Did I make a mistake during my CMake build?  I had used the following command in the developer command prompt:
build.bat --cmake_path "C:\Program Files\CMake\bin\cmake.exe" --config RelWithDebInfo --build_shared_lib --build_csharp --parallel --use_cuda --cuda_version 10.2 --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --use_tensorrt --tensorrt_home "C:\TensorRT\TensorRT-7.0.0.11.Windows10.x86_64.cuda-10.2.cudnn7.6\TensorRT-7.0.0.11" --use_dnnl --cmake_generator "Visual Studio 16 2019" --skip_tests

One other important note is that one of the reasons I am building from source is that I want to experiment with TensorRT runtime optimization (which is why I put the --use_tensorrt).

**Comment by skottmckay** [comment]
The target is matched for all projects generated by the build, so you'd need to set the C# solution to the RelWithDebInfo configuration as that was the build config. Visual Studio tends to default to the Debug config. 

Alternatively you could try pointing it to the onnxruntime.dll in build\Windows\RelWithDebInfo\RelWithDebInfo. It should work but isn't tested.

**Comment by solarflarefx** [comment]
@skottmckay Thanks for the reply.  Forgive me for asking, but how do I set the C# solution to RelWithDebInfo config?  Would I add the RelWithDebInfo in the conditional compilation symbols?

**Comment by skottmckay** [comment]
![image](https://user-images.githubusercontent.com/979079/80930278-ed8a7700-8df5-11ea-9209-2d4015b9bf1e.png)

Select the configuration from the dropdown menu in VS.

**Comment by solarflarefx** [comment]
@skottmckay Thanks for the clear instruction.  What's interesting is that when I do that, I get the error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3030	Could not copy the file "C:\ONNXRuntime\onnxruntime\onnxruntime\build\Windows\Release\Release\onnxruntime.dll" because it was not found.

![image](https://user-images.githubusercontent.com/45402633/81122555-19ddea80-8eff-11ea-8d24-4604100606e7.png)

Basically it's looking in the "Release" folder instead of the "RelWithDebInfo" folder.

So alternatively I went back to Debug and moved the onnxruntime.dll file into C:\ONNXRuntime\onnxruntime\onnxruntime\build\Windows\Debug\Debug.  This generated an Microsoft.ML.OnnxRuntime.dll file.  

I tried to use this file in my project, by right clicking add references and then add this DLL.  Unfortunately I got a runtime error:
System.TypeInitializationException: 'The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.'
DllNotFoundException: Unable to load DLL 'onnxruntime': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Now this seems like a simple error -- just put the onnxruntime.dll file inside the same folder as the exe.  I did that but this error is still there.

I also have another project with the exact same code, except in that project I use the NuGet package and that works fine.  So it seems the error is related to my generated Microsoft.ML.OnnxRuntime.dll

**Comment by skottmckay** [comment]
The C# projects needed a RelWithDebInfo configuration defined. There's a PR to address this.

Most likely it's a dependency that's missing. I would expect you need to copy dnnl.dll as well, and the CUDA dlls would need to be in the PATH of the environment Visual Studio is started in for them to be found as well.

**Comment by solarflarefx** [comment]
@skottmckay You were right, it had to do with including dnnl.dll in the output directory.

Now I am having an issue with TensorRT.  I built with TensorRT 7 Cuda 10.2.

When I run with CUDA, everything is fine:
`
            // Create session options and set the graph optimization level for the session
            SessionOptions options = new SessionOptions();
            int gpuDeviceId = 0; // The GPU device ID to execute on
            options.AppendExecutionProvider_CUDA(gpuDeviceId);
            //options.AppendExecutionProvider_Tensorrt(gpuDeviceId);
            options.GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_ALL;

            ...

            using (var session = new InferenceSession(modelPath, options))
            {
                 ....
            }
`

However, I get an error when trying to run using TensorRT:
`
            // Create session options and set the graph optimization level for the session
            SessionOptions options = new SessionOptions();
            int gpuDeviceId = 0; // The GPU device ID to execute on
            //options.AppendExecutionProvider_CUDA(gpuDeviceId);
            options.AppendExecutionProvider_Tensorrt(gpuDeviceId);
            options.GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_ALL;

            ...

            using (var session = new InferenceSession(modelPath, options))
            {
                 ....
            }
`

I've included the following files in the output directory:
- cudart64_102.dll
- cublasLt64_10.dll
- cudnn64_7.dll
- cublas64_10.dll
- dnnl.dll
- nvinfer.dll
- nvinfer_plugin.dll
- onnxruntime.dll

The error I get:
![image](https://user-images.githubusercontent.com/45402633/82586820-30727b80-9b66-11ea-96cd-12a92afbcaf5.png)

This happens in the using statement line.

**Comment by skottmckay** [comment]
Do the exception details say what the error was?

**Comment by solarflarefx** [comment]
Looks like the error code is: -2147467259

![image](https://user-images.githubusercontent.com/45402633/82612359-b1466d00-9b90-11ea-9941-8c2a45571783.png)

**Comment by solarflarefx** [comment]
Actually it looks like I may have had to put one or more of the following files in the Debug directory as well:
- myelin64_1.dll
- nvparsers.dll
- nvserialize.dll
- nvonnxparser.dll

I then got this message: [W:onnxruntime:CSharpOnnxRuntime, tensorrt_execution_provider.h:36 onnxruntime::TensorrtLogger::log] [2020-05-21 22:49:33 WARNING] C:\ONNXRuntime\onnxruntime\onnxruntime\cmake\external\onnx-tensorrt\onnx2trt_utils.cpp:235: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.

What can I do to prevent this cast down?  It seems to have quite a bit of overhead.  It seems that when I load without TensorRT this does not occur.

**Comment by solarflarefx** [comment]
Actually seems like I am delving into another issue, as the build process itself seems fine now.  Thanks for the help @skottmckay !

**Comment by GeorgeS2019** [comment]
fail build with the latest Master. Anyone has similar problem?

`build.bat --cmake_path "C:\Program Files\CMake\bin\cmake.exe" --config RelWithDebInfo --build_shared_lib --build_csharp --parallel --use_cuda --cuda_version 10.2 --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --use_tensorrt --tensorrt_home "C:\TensorRT\TensorRT-7.0.0.11.Windows10.x86_64.cuda-10.2.cudnn7.6\TensorRT-7.0.0.11" --use_dnnl --cmake_generator "Visual Studio 16 2019" --skip_tests`
