### ISSUE TITLE
qmath.cc:24:6: error: unused parameter ‘thread_pool’ [-Werror=unused-parameter](void QGemmu8s8_s32)

### ISSUE THREAD

**Issue by mkwml** [microsoft/onnxruntime#3534]
**Describe the bug**
Build centos7.4 aarch64 from source, got this error.

[ 52%] Building CXX object CMakeFiles/onnxruntime_util.dir/home/wmk/onnxruntime-1.0.0/onnxruntime/core/util/qmath.o
/home/wmk/onnxruntime-1.0.0/onnxruntime/core/util/qmath.cc:24:6: error: unused parameter ‘thread_pool’ [-Werror=unused-parameter]
 void QGemmu8s8_s32(
      ^
cc1plus: all warnings being treated as errors
gmake[2]: *** [CMakeFiles/onnxruntime_util.dir/home/wmk/onnxruntime-1.0.0/onnxruntime/core/util/qmath.o] Error 1
gmake[1]: *** [CMakeFiles/onnxruntime_util.dir/all] Error 2
gmake: *** [all] Error 2
  

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., centos7.4 aarch64):
- ONNX Runtime installed from (source):
- ONNX Runtime version: 1.0.0
- Python version: 3.6.6
-CMake version: 3.14.2 
- GCC/Compiler version (if compiling from source):4.8.5

**Expected behavior**
Build succeed and produce the onnxruntime binding for ARM

**Comment by snnn** [comment]
It should already get fixed in the latest version.

**Comment by mkwml** [comment]
> It should already get fixed in the latest version.

yes, you are right. thanks
