### ISSUE TITLE
Cuda Dependency still required in Windows even when running only the CPU mode

### ISSUE THREAD

**Issue by yijiew** [microsoft/onnxruntime#3537]
**Is your feature request related to a problem? Please describe.**
ONNX runtime GPU version tries to delayload CUDA dependencies on Windows. But it still requires cudart64_*.dll to be there to load the onnxruntime dll.  

**System information**
- ONNX Runtime version (you are using): 1.1.2 and 1.0.0

**Describe the solution you'd like**
ONNX runtime GPU version shouldn't require CUDA dependencies to be there if we only want to use this GPU version dll to run CPU mode. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by snnn** [comment]
You're right. Delay loading won't work.

**Comment by snnn** [comment]
The cuda EP has thread local variables that has non-trival destructor, which need CUDA. So, in current status, we can't delay load CUDA DLLs.Because if we do that, CUDA may get unloaded before onnxruntime.dll.

**Comment by yijiew** [comment]
I see. Thanks for the explanation. Since cudart64_*.dll is actually a small dll, it shouldn't be such a big problem for us.
