### ISSUE TITLE
quantization modes(bert) not work on cpu

### ISSUE THREAD

**Issue by Micy1919** [microsoft/onnxruntime#3552]
**Describe the bug**
I user Quantization tool to quantizate my bert model(pytorch), but it 's seem to be worse on cpu.

pytorch bert: 4842.96 ms a batch
optimized_model: 10456.66 ms a batch

quantization
bert_model_optimization.py --input /data01/transformers/bert.proto --output optimized_model_gpu.onnx --input_int32 --float16
** Code **
model_torch.eval()
model_torch.to(torch.device("cpu"))
with torch.no_grad():
     now = time.time()
     out = model_torch(**batch_data)
    latency.append(time.time() - now)

model_onnx = onnxruntime.InferenceSession(onnx_model, sess_options, providers=['CPUExecutionProvider'])
now = time.time()
model_onnx.run(None, inputs_onnx)
latency_onnx.append(time.time() - now)

**Comment by yufenglee** [comment]
@Micy1919 , our CPU doesn't support float16 directly. Generally, for each node, ORT cast inputs from float16 to float32 and cast outputs back. It introduces a lot of overhead. 
I don't think you meant to run float16 on CPU. If not, please remove the --float16 when you run the bert_model_optimization.py.

**Comment by Micy1919** [comment]
> @Micy1919 , our CPU doesn't support float16 directly. Generally, for each node, ORT cast inputs from float16 to float32 and cast outputs back. It introduces a lot of overhead.
> I don't think you meant to run float16 on CPU. If not, please remove the --float16 when you run the bert_model_optimization.py.

I tried it, but It's still same.

**Comment by yufenglee** [comment]
@Micy1919, you need to do warming up before measuring the performance, and it is better to run multiple times to get the average. 
And actually quantization can not give a you better performance on x86/amd64, unless on a VNNI machine.
