### ISSUE TITLE
Do you have an example of GPU?

### ISSUE THREAD

**Issue by huang229** [microsoft/onnxruntime#3562]
Do you have an example of GPU?  I only found the application instance on the CPU.https://github.com/microsoft/onnxruntime/tree/master/samples#CC

**Comment by snnn** [comment]
Yes we do https://github.com/microsoft/onnxruntime/blob/master/samples/c_cxx/fns_candy_style_transfer/fns_candy_style_transfer.c#L226

**Comment by huang229** [comment]
@snnn Thank you very much for your help!
