### ISSUE TITLE
[ONNXRuntimeError] : 1 : FAIL : This is an invalid model. Error: Duplicate definition of name 

### ISSUE THREAD

**Issue by gbolin** [microsoft/onnxruntime#3563]
hi there, 
**Describe the bug**
firstly I follow the tutorial from [onnx_quantization](https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization)  getting the quantized model. it is ok for me in this step.
secondly, I try to load the quantized model using onnxruntime in Python3, I got the error "onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : This is an invalid model. Error: Duplicate definition of name"

here is my code
```
import onnxruntime as ort
import onnx

model = onnx.load(onnx_model)
q_model = quantize(model, quantization_mode=QuantizationMode.IntegerOps)
onnx.save(q_model, quantized_onnx_model)

ort_session = ort.InferenceSession(quantized_onnx_name)
```

**System information**
- ONNX Runtime installed by using Pip install 
- ONNX Runtime version: 1.6
- Python version:python3.6

**Screenshots**

![11](https://user-images.githubusercontent.com/14962165/79538057-261c1800-80b6-11ea-8a28-3c644c84aae8.png)

**Comment by snnn** [comment]
I don't think it's an onnxruntime issue. Please raise it to https://github.com/onnx/onnx/

**Comment by hariharans29** [comment]
Closing as per comment
