### ISSUE TITLE
how can i use Microsoft.ML.OnnxRuntime.Gpu for onnx gpu inferecne

### ISSUE THREAD

**Issue by MrCrazyCrab** [microsoft/onnxruntime#3566]
how can i use Microsoft.ML.OnnxRuntime.Gpu for onnx gpu inferecne,  is there any developer guide for this?

**Comment by hariharans29** [comment]
Will this sample help - https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp ? Search for "CUDA" within it.

**Comment by hariharans29** [comment]
Closing. Please re-open if you need more assistance.
