### ISSUE TITLE
Release a monolythic static library and header files

### ISSUE THREAD

**Issue by pfeatherstone** [microsoft/onnxruntime#3571]
You provide an SO file in your releases.
Could you provide a monolythic static library as well.
When building from source, you get the following static libraries:
```
libonnxruntime_common.a
libonnxruntime_framework.a
libonnxruntime_graph.a
libonnxruntime_mlas.a
libonnxruntime_optimizer.a
libonnxruntime_providers.a
libonnxruntime_session.a
libonnxruntime_test_utils.a
libonnxruntime_util.a
libonnx_test_data_proto.a
libonnx_test_runner_common.a
lib/libgmock.a
lib/libgtest.a
onnx/libonnx.a
onnx/libonnx_proto.a
```
(there may be more)

These could be combined using a .mri script.
For example, create the file libonnxruntime.mri which contains:
```
create libonnxruntime.a
addlib libonnxruntime_common.a
addlib libonnxruntime_framework.a
addlib libonnxruntime_graph.a
addlib libonnxruntime_mlas.a
addlib libonnxruntime_optimizer.a
addlib libonnxruntime_providers.a
addlib libonnxruntime_session.a
addlib libonnxruntime_test_utils.a
addlib libonnxruntime_util.a
addlib libonnx_test_data_proto.a
addlib libonnx_test_runner_common.a
addlib lib/libgmock.a
addlib lib/libgtest.a
addlib onnx/libonnx.a
addlib onnx/libonnx_proto.a
save
end
```

**Comment by snnn** [comment]
It's intentional. It won't work good if onnxruntime use any submodules at build time.

**Comment by pfeatherstone** [comment]
Ok cool. I'll just do it manually.

**Comment by snnn** [comment]
BTW, seems you missed re2. re2 isn't in your list.

**Comment by pfeatherstone** [comment]
Yeah I’ve probs missed loads

**Comment by snnn** [comment]
In the build dir, you may try this:
```
make onnxruntime
rm libonnxruntime.so
make VERBOSE=1 onnxruntime
```

Then the last step will show you all the libs needed.

**Comment by pfeatherstone** [comment]
Cheers

**Comment by pfeatherstone** [comment]
So the following works for me:

```
create libonnxruntime_mono.a
addlib onnxruntime/build/Linux/Release/libonnxruntime_common.a
addlib onnxruntime/build/Linux/Release/libonnxruntime_framework.a
addlib onnxruntime/build/Linux/Release/libonnxruntime_graph.a
addlib onnxruntime/build/Linux/Release/libonnxruntime_mlas.a
addlib onnxruntime/build/Linux/Release/libonnxruntime_optimizer.a
addlib onnxruntime/build/Linux/Release/libonnxruntime_providers.a
addlib onnxruntime/build/Linux/Release/libonnxruntime_session.a
addlib onnxruntime/build/Linux/Release/libonnxruntime_test_utils.a
addlib onnxruntime/build/Linux/Release/libonnxruntime_util.a
addlib onnxruntime/build/Linux/Release/libonnx_test_data_proto.a
addlib onnxruntime/build/Linux/Release/libonnx_test_runner_common.a
addlib onnxruntime/build/Linux/Release/onnx/libonnx.a
addlib onnxruntime/build/Linux/Release/onnx/libonnx_proto.a
addlib onnxruntime/build/Linux/Release/lib/libgmock.a
addlib onnxruntime/build/Linux/Release/lib/libgtest.a
addlib onnxruntime/build/Linux/Release/external/nsync/libnsync_cpp.a
addlib onnxruntime/build/Linux/Release/external/re2/libre2.a
addlib onnxruntime/build/Linux/Release/external/protobuf/cmake/libprotobuf-lite.a
save
end
```

**Comment by pfeatherstone** [comment]
When running against the library i get the following error:
```
terminate called after throwing an instance of 'Ort::Exception'
  what():  Fatal error: Conv is not a registered function/op
```
Does the library dynamically load operations?

**Comment by pfeatherstone** [comment]
Or is there some global initialisation that somehow doesn't happen when statically linked?

**Comment by pfeatherstone** [comment]
I've tried the following:
```
void* library_handle = nullptr;
Ort::GetApi().RegisterCustomOpsLibrary((OrtSessionOptions*)session_options, "libcustom_op_library.so", &library_handle);
```

and I still get the error :
```
terminate called after throwing an instance of 'Ort::Exception'
  what():  Fatal error: Conv is not a registered function/op
```

Don't understand what's special about the static build

**Comment by pfeatherstone** [comment]
@snnn @hariharans29 I think we should re-open the issue. There is an issue with op registration in the static build

**Comment by pfeatherstone** [comment]
Is there something to be done with the schema_registry when using the static build?

**Comment by pfeatherstone** [comment]
The problem is with ```Ort::Env```.
My program runs several models. If each session has its own ```Ort::Env``` it fails with error:
```
terminate called after throwing an instance of 'Ort::Exception'
  what():  Only one instance of LoggingManager created with InstanceType::Default can exist at any point in time.
```
So I thought i would use a global static instance:
```
static Ort::Env env;
```
then use that everywhere.
Now that works if using the dynamic library, i.e. libonnxruntime.so, but does not if you're using the static libraries.
To get around this I do the following:
```
Ort::Env& default_env()
{
    static Ort::Env INSTANCE(ORT_LOGGING_LEVEL_WARNING, "test");
    return INSTANCE;
}
```
and use default_env(). I guess the difference being that the singleton is created at runtime.

**Comment by snnn** [comment]
You're totally right.

**Comment by pfeatherstone** [comment]
This repository is insanely good! It's so fast. And with an MRI script like the one above, it is a totally dependency free, single file static library (or shared library with no scripting). You guys should be really pushing for this to be the goto inference library. It's much better than OpenCV's DNN library or Tencent's NCNN, or feathercnn, or paddlepaddle, or anything else I've tried.
