### ISSUE TITLE
Non-File Constructor for Session

### ISSUE THREAD

**Issue by JohnCraigPublic** [microsoft/onnxruntime#3576]
I see there are 2 constructors for Session:

 Session(Env& env, const ORTCHAR_T* model_path, const SessionOptions& options);

  Session(Env& env, const void* model_data, size_t model_data_length, const SessionOptions& options);

Can you tell me how I could get 'model_data' for the 2nd constructor?   If I've loaded a model from a file (1st constructor) is there a way to select it's 'data' out?

**System information**
ONNX v5,   Windows 10,  C++, VS2017

**Comment by pranavsharma** [comment]
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_model_loading.cc#L16

**Comment by JohnCraigPublic** [comment]
Perfect.  Thank you!!  Closed...
