### ISSUE TITLE
ONNX Runtime support for NVDLA？

### ISSUE THREAD

**Issue by wxbbuaa2011** [microsoft/onnxruntime#3589]
**Is your feature request related to a problem? Please describe.**

**System information**
- ONNX Runtime version (you are using):

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by manashgoswami** [comment]
What is the HW for your scenario to use with NVDLA?
We typically use the Execution Provider (EP) interface to directly access the platform libraries for executing the model. We do not have an EP to work with NVDLA at this time.

**Comment by wxbbuaa2011** [comment]
Thanks for your reply.
