### ISSUE TITLE
'release' on Ort::Session

### ISSUE THREAD

**Issue by JohnCraigPublic** [microsoft/onnxruntime#3594]
Ort::Session* pSess;

To release the memory used by a model, I have simply been doing this:

delete pSess;
pSess = NULL;

But I see there is a 'release' member defined:

pSess->release();

what does it do?   Should I be calling it?

**System information**
Latest ONNX and ORT, Windows 10, C++, VS2017

**Comment by pranav-prakash** [comment]
If I'm reading their source correctly, release basically just deletes the ptr. It's possible they may add something else in the future, but for now they do the same.

https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/session/onnxruntime_c_api.cc#L1595

```
#define DEFINE_RELEASE_ORT_OBJECT_FUNCTION(INPUT_TYPE, REAL_TYPE)                       \
  ORT_API(void, OrtApis::Release##INPUT_TYPE, _Frees_ptr_opt_ Ort##INPUT_TYPE* value) { \
    delete reinterpret_cast<REAL_TYPE*>(value);                                         \
  }
```

**Comment by JohnCraigPublic** [comment]
OK, thanks
