### ISSUE TITLE
onnxruntime python package conflicts with pytorch

### ISSUE THREAD

**Issue by BruceDone** [Microsoft/onnxruntime#360]
**Describe the bug**
can not successfully import onnxruntime , it raise error 

**System information**
- Docker image of :
    * pytorch/pytorch:1.0-cuda10.0-cudnn7-devel
- Runtime installed from (source or binary)
    * pip install onnxruntime
- ONNX Runtime version:
    * 0.1.4
- Python version:
    * 3.6.7

**To Reproduce**
Describe steps/code to reproduce the behavior:

```
import torch
from onnxruntime import backend
```

**Expected behavior**
success run the code

**Additional context**
```
/opt/conda/lib/python3.6/site-packages/onnxruntime/capi/_pybind_state.py:12: UserWarning: Cannot load onnxruntime.capi. Error: '/opt/conda/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so: undefined symbol: mkldnn_sgemm'
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'".format(str(e)))
Traceback (most recent call last):
  File "info.py", line 2, in <module>
    from onnxruntime import backend
  File "/opt/conda/lib/python3.6/site-packages/onnxruntime/__init__.py", line 21, in <module>
    from onnxruntime.capi._pybind_state import RunOptions, SessionOptions, get_device, NodeArg, ModelMetadata```

**Comment by snnn** [comment]
It's very easy to explain. They(onnxruntime and pytorch) conflict with each other.
Both onnxruntime and pytorch depend on mkldnn, but they need different versions.

To solve this, one proposal is letting  them static link to mkldnn:
#268
#240

**Comment by peterjc123** [comment]
Why is this issue closed? The related PRs are not merged into master.

**Comment by peterjc123** [comment]
Any plan to get these PRs back?
