### ISSUE TITLE
Example of using DirectML with onnxruntime and D3D12 inputs and outputs

### ISSUE THREAD

**Issue by oneengineer** [microsoft/onnxruntime#3611]
**Is your feature request related to a problem? Please describe.**
no

**System information**
- ONNX Runtime version (you are using):
dmldev

**Describe the solution you'd like**
I want to use DML inside a DX12 app, but I don't know how (with onnxruntime APIs)
And I found such function you provided:

```
 OrtStatus* OrtSessionOptionsAppendExecutionProviderEx_DML(
    _In_ OrtSessionOptions* options,
    _In_ IDMLDevice* dml_device,
    _In_ ID3D12CommandQueue* cmd_queue
    );
```
However I still don't know how I can feed a `resource` (a buffer) in DX12 to the inference part of dml onnx.

I have read fns_candy_style_transfer.c example.
However if there a DX12 example using onnxruntime, that will better explain the APIs.

**Comment by wchao1115** [comment]
@oneengineer Thanks for your feedback. Unfortunately binding DX resources to the model through onnxruntime API isn't possible today. We'll be looking into it for our next update.

**Comment by qunliu** [comment]
> @oneengineer Thanks for your feedback. Unfortunately binding DX resources to the model through onnxruntime API isn't possible today. We'll be looking into it for our next update.

@wchao1115 any update on this? Is this possible now?

**Comment by smk2007** [comment]
Hi, this is possible now. Please a look at this sample!

https://github.com/microsoft/Windows-Machine-Learning/tree/master/Samples/WinMLSamplesGallery/WinMLSamplesGallery/Samples/DXResourceBindingORT

**Comment by oneengineer** [comment]
Thanks!

So the key is to providing the resource with normal dx12 APIs and wrap it into `Ort::Value`.
Then feed it into `session::run` API.

Everything here is just standard APIs without modifying the source code onnxruntime?

> Hi, this is possible now. Please a look at this sample!
> 
> https://github.com/microsoft/Windows-Machine-Learning/tree/master/Samples/WinMLSamplesGallery/WinMLSamplesGallery/Samples/DXResourceBindingORT
