### ISSUE TITLE
Depreciated Dockerfile keywords

### ISSUE THREAD

**Issue by mustafakasap** [microsoft/onnxruntime#3624]
MAINTAINER keyword is depreciated in late 2018... Here the ref: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated 

All docker files should be updated here and if it is mandatory to put individual author name, following is the official guidance to use:

LABEL maintainer="Rock star dockerfile builder @contoso.com"

**Comment by jywu-msft** [comment]
Thanks for bringing to our attention. We'll need to clean up the Dockerfiles in the repo.
