### ISSUE TITLE
build doesn't work on windows

### ISSUE THREAD

**Issue by harelfar2** [microsoft/onnxruntime#3630]
**Describe the bug**
I'm trying to build onnxruntime with tensorRT, and I'm getting errors as I will show.

**Urgency**
none

**System information**
- I tried on both windows 10 and windows server 2019.
- ONNX Runtime installed from source
- ONNX Runtime version: master from ~ 15/04/2020, commit 54bbbb78ae3eefe69bd27f71dcc5affa977842c2
- Visual Studio version: 2017
- GCC/Compiler version (if compiling from source): not sure. I did gcc --version and it didn't find
- CUDA/cuDNN version: 10.2, 7.6.5
- GPU model and memory: nvidia gtx 750 ti

**To Reproduce**
from onnx-runtime dir I opened developer command prompt VS 2017 (as admin) typed: `.\build.bat --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --use_tensorrt --tensorrt_home "C:\Users\harelf\Downloads\TensorRT-7.0.0.11" --config Release --build_dir E:\onnx-build2 --build_wheel` (also did it without build wheel and the results are the same).
I tried also:
`.\build.bat --use_cuda --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2"`
and the error was there too.

**Expected behavior**
To finish the build successfully. 

**Screenshots**
![image](https://user-images.githubusercontent.com/17828795/79972832-3c9fe600-849f-11ea-9d41-cd0a4ff61524.png)

Thanks in advance for any help.

**Comment by jywu-msft** [comment]
builds are currently broken on VS2017 due to a recent change exposing a compiler bug.
Either try VS2019 or an older commit such as
https://github.com/microsoft/onnxruntime/commit/f8fa1dde558ce2129ac27ba3bc5bca97866e4a74 from April 8, 2020

**Comment by harelfar2** [comment]
thanks i'll try

**Comment by harelfar2** [comment]
hmm I changed to this commit still didn't work. 
Do you know about another commit? or maybe other solution?

**Comment by jywu-msft** [comment]
please attach full build output log. 
and which version of VS2017 are you using?

**Comment by harelfar2** [comment]
@jywu-msft , I have VS 2017 Enterprise (can I give you more info? if so, how?) 
I took commit a8efa42d6 (the one from tag 1.1.2) from 20.2.2020.
full log: 
[onnx-build.log](https://github.com/microsoft/onnxruntime/files/4520630/onnx-build.log)

here is the log tail, got slightly different error:

onnx_proto.lib(onnx-ml.pb.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
     Creating library E:/onnx-build/Release/external/onnx-tensorrt/Release/trt_onnxify.lib and object E:/onnx-build/Release/external/onnx-tensorrt/Release/trt_onnxify.exp
  Generating code
  Finished generating code
  trt_onnxify.vcxproj -> E:\onnx-build\Release\external\onnx-tensorrt\Release\trt_onnxify.dll
Traceback (most recent call last):
  File "E:\code\onnxruntime\\tools\ci_build\build.py", line 1043, in <module>
    sys.exit(main())
  File "E:\code\onnxruntime\\tools\ci_build\build.py", line 975, in main
    build_targets(cmake_path, build_dir, configs, args.parallel)
  File "E:\code\onnxruntime\\tools\ci_build\build.py", line 415, in build_targets
    run_subprocess(cmd_args)
  File "E:\code\onnxruntime\\tools\ci_build\build.py", line 197, in run_subprocess
    completed_process = subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "C:\Users\harelf\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', 'E:\\onnx-build\\Release', '--config', 'Release']' returned non-zero exit status 1.

**Comment by jywu-msft** [comment]
is that build log for 1.1.2 or for https://github.com/microsoft/onnxruntime/commit/f8fa1dde558ce2129ac27ba3bc5bca97866e4a74 ?

**Comment by jywu-msft** [comment]
I personally have recently built https://github.com/microsoft/onnxruntime/commit/a4fe60c4d3fb082d875b5371e7846f42916ea3b8using VS2017 Enterprise version 15.9.22 successfully.
You can check the version from the GUI pulldown menu.  Help->About Microsoft Visual Studio

**Comment by harelfar2** [comment]
no this is the log from a8efa42. 
I have VS version 15.7.4
I try a4fe60c now. 
Thanks a lot for your attention so far!

**Comment by jywu-msft** [comment]
can you update VS2017 to latest version. Someone else recently reported a different build issue when using an older version of VS2017. 
It went away after they updated to 15.9.x 
So you may hit that issue as well.

**Comment by harelfar2** [comment]
will do!

**Comment by harelfar2** [comment]
@jywu-msft , failed again on VS 15.9.22 and commit a4fe60c4d.
here is the log: 
[onnx.log](https://github.com/microsoft/onnxruntime/files/4522033/onnx.log)

do you have an idea?

**Comment by jywu-msft** [comment]
I took a quick look at the log. I haven't encountered this type of error before.
Seems like there are 2 issues. It's not finding header files for safeint and CUB
see lines in the logfile like:

E:\code\onnxruntime\onnxruntime\core/common/safeint.h(27): fatal error C1083: Cannot open include file: 'safeint/SafeInt.hpp': No such file or directory (compiling source file E:\code\onnxruntime\onnxruntime\test\onnx\tensorprotoutils.cc)

and

E:/code/onnxruntime/onnxruntime/core/providers/cuda/generator/range_impl.cu(4): fatal error C1083: Cannot open include
file: 'cub/cub.cuh': No such file or directory [E:\onnx-build2\Release\onnxruntime_providers_cuda.vcxproj]

at least for the nvcc commandline for range_impl.cu , I see that the correct header location for CUB seems to be added.

search for
-IE:\code\onnxruntime\cmake\external\cub  in log.

Can you confirm that e:\code\onnxruntime\cmake\external\cub\cub\cub.cuh exists ?

**Comment by harelfar2** [comment]
hmm you're right, it wasn't there. I'll clone it again and check. 
Thanks!

**Comment by jywu-msft** [comment]
Are you using git clone --recursive ?

**Comment by harelfar2** [comment]
I didn't use --recursive. should I?
anyways, I managed to complete the build in the windows server 2019. 
Thanks a lot!

**Comment by jywu-msft** [comment]
yes, --recursive will clone the submodules. 

closing this issue as it seems to be resolved.
