### ISSUE TITLE
Have you guys consider another scenario of upsample?

### ISSUE THREAD

**Issue by Charleshzhang** [microsoft/onnxruntime#3631]
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/tensor/upsample.h

In this header, I saw the logic to deal with the tensor "scale"

However i didn't find logic to handle the tensor "size"

in onnx's "Resize" node,  the tensor "size" is an optional one, if "size" has data, "scale" should be set to empty

Any thoughts guys?

**Comment by tracysh** [comment]
@Charleshzhang The logic to handle the "size" is done here:
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/tensor/upsample.cc#L735

The size tensor is internally converted to the scale values based on the input tensor size. The rest of the kernel then only uses the scale values.

**Comment by Charleshzhang** [comment]
> @Charleshzhang The logic to handle the "size" is done here:
> https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/tensor/upsample.cc#L735
> 
> The size tensor is internally converted to the scale values based on the input tensor size. The rest of the kernel then only uses the scale values.

ok thanks, will check it out

**Comment by hariharans29** [comment]
The other case is supported as pointed out. Closing this out. Please re-open if you have further questions.
