### ISSUE TITLE
OSError: libcudnn.so.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jhagege** [microsoft/onnxruntime#3632]
Hi, when running 
`import onnxruntime `, I get the following error: 
`OSError: libcudnn.so.7: cannot open shared object file: No such file or directory`

This is happening with pytorch/pytorch:1.5-cuda10.1-cudnn7-runtime.
I then tried with pytorch/pytorch:1.4-cuda10.1-cudnn7-runtime and it works fine.

Any idea how to fix ?

**Comment by songyouwei** [comment]
Any solutions?

**Comment by marberi** [comment]
Encountered the same problem with PyTorch 1.6.0  (py3.7_cuda10.2.89_cudnn7.6.5_0).

**Comment by marberi** [comment]
Seems to be a missing library problem. Using "conda install cudnn" installs the cudnn package and loading now works (using pytorch=1.4).

**Comment by wangzhanxd** [comment]
conda install cudnn
pytorch/pytorch:1.5-cuda10.1-cudnn7-runtime
