### ISSUE TITLE
Is there a way to save engine like tensorrt?

### ISSUE THREAD

**Issue by zealerww** [microsoft/onnxruntime#3633]
As we know parsing onnx to trt and the firt time inference are time consuming，is there a way to save engine in onnxruntime like tensorrt?

**Comment by jywu-msft** [comment]
this is something we can consider supporting, adding a file cache for serialized TRT engines. 
@stevenlix FYI

**Comment by zealerww** [comment]
cool, look forward to seeing process

**Comment by pgrudzien12** [comment]
any updates on this? running trt content is very slow on a device and as a result starting my soft on robot takes much longer than expected

**Comment by joba01** [comment]
engines can be cached, since > 1year.
See documentation and releasenotes:
https://onnxruntime.ai/docs/reference/execution-providers/TensorRT-ExecutionProvider.html
