### ISSUE TITLE
Problems selecting the cuda version when installing nuget

### ISSUE THREAD

**Issue by sladkehs** [microsoft/onnxruntime#3647]
How do I set the CUDA version to install the package with Nuget to use ONNXRuntime? I have 10.0, 10.1, and 10.2.

If it doesn't matter, what kind of error is this?

> onnxruntime::CudaCall CUBLAS failure 1: CUBLAS_STATUS_NOT_INITIALIZED

**Comment by faxu** [comment]
See https://github.com/microsoft/onnxruntime#system-requirements

ORT 1.3 requires CUDA 10.1.
