### ISSUE TITLE
the inference result of onnx model with onnxruntime is big different with the pytorch model 

### ISSUE THREAD

**Issue by wuqingshan2010** [microsoft/onnxruntime#3654]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): deepin
- ONNX Runtime installed from (source or binary):pip install onnxruntime
- ONNX Runtime version:1.2.0
- Python version:3.7.10

When i use the "torch.onnx.export()" command to export my .pth model, and use the onnxruntime load it; Finally, with the same input, the result is big different!

**Comment by tianleiwu** [comment]
@wuqingshan2010,
Could you verify that the exported model using [Netron](https://github.com/lutzroeder/netron)? Sometime, user might uses the wrong order of input names during export but not realize it.

**Comment by faxu** [comment]
@wuqingshan2010 Do you need any more support on this issue?

**Comment by faxu** [comment]
Please reopen and provide more details if further assistance is needed.
