### ISSUE TITLE
Create Ort::Value from const data pointer

### ISSUE THREAD

**Issue by xyoungli** [microsoft/onnxruntime#3656]
hi, is it able to create an "Ort::Value (Tensor)" from a const data pointer. I have checked the cxx apis, but there seems no such an api?

**Comment by snnn** [comment]
No.

**Comment by snnn** [comment]
The C/C++ API is a thin wrapper around the onnxruntime::Tensor class
https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/framework/tensor.h#L70

The internal implementation doesn't support that, so the API neither.

**Comment by xyoungli** [comment]
> The C/C++ API is a thin wrapper around the onnxruntime::Tensor class
> https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/framework/tensor.h#L70
> 
> The internal implementation doesn't support that, so the API neither.

OK, thanks

**Comment by wbudd** [comment]
This is stupid. Why not provide a variant of `CreateTensor` named `CreateInputTensor` that offers the expected `const` assurances to its consumers—both human and machine?
