### ISSUE TITLE
Missing file version for onnxruntime.dll in C# nuget package

### ISSUE THREAD

**Issue by erikbrntsn** [microsoft/onnxruntime#3685]
I work on a big C# application consisting of several smaller components. These might all separately be using onnxruntime which could lead to version mismatches.

A possible way to check for version mismatches could be to inspect the file version for onnxruntime.dll. This is not set however .

Could you add file version to onnxruntime.dll in the C# nuget packages?

**Comment by pranavsharma** [comment]
This is fixed by https://github.com/microsoft/onnxruntime/pull/3187 and will be available in the 1.3 release. cc @orilevari

**Comment by erikbrntsn** [comment]
Very nice!
