### ISSUE TITLE
Error Creating a bool Tensor using C++ API

### ISSUE THREAD

**Issue by SamG97** [microsoft/onnxruntime#3689]
**Describe the bug**
I was trying to run an ONNX model where one of the inputs is a bool tensor. However, I was unable to use the `Ort::Value::CreateTensor` method to create a boolean tensor and hence call the model with the correct input types. Switching to using other types (e.g. int or float) with this method works correctly.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubutnu 18.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.2.0
- Python version: 3.7
- GCC/Compiler version (if compiling from source): g++ 7.5.0

**To Reproduce**
A minimal example is included below:
```cpp
// test.cpp
#include <onnxruntime_cxx_api.h>
#include <iostream>

class OrtTest {
public:
    OrtTest() {
        std::vector<int> int_data{1, 1, 0, 0};
        std::vector<bool> bool_data{1, 1, 0, 0};
        std::vector<int64_t> shape{4};

        Ort::Value::CreateTensor<int>(memory_info, int_data.data(),
            int_data.size(), shape.data(), shape.size());
        std::cout << "Successfully made int tensor" << std::endl;

        Ort::Value::CreateTensor<bool>(memory_info, bool_data.data(),
            bool_data.size(), shape.data(), shape.size());
        std::cout << "Successfully made bool  tensor" << std::endl;
    }
private:
    Ort::Env env;
    const Ort::MemoryInfo memory_info =
        Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU);
};

int main() {
    OrtTest test;
}
```
Compiling the above code with `g++ test.cpp -l onnxruntime` gives the following error:
```
test.cpp: In constructor ‘OrtTest::OrtTest()’:
test.cpp:16:57: error: invalid use of void expression
             bool_data.size(), shape.data(), shape.size());
```
Commenting out the lines:
```cpp
Ort::Value::CreateTensor<bool>(memory_info, bool_data.data(),
    bool_data.size(), shape.data(), shape.size());
std::cout << "Successfully made bool  tensor" << std::endl;
```
allows the file to compile correctly and output 'Successfully made int tensor' when run.

**Expected behavior**
The creation of the bool tensor should work correctly like it does with the int tensor

**Additional context**
I have also tried creating the bool tensor using:
```cpp
Ort::Value::CreateTensor(memory_info, bool_data.data(),
    bool_data.size(), shape.data(), shape.size(),
    ONNX_TENSOR_ELEMENT_DATA_TYPE_BOOL);
```
but this also fails to compile with a similar error (perhaps as expected since the `Ort::Value::CreateTensor<bool>` method seems to just be a wrapper around this).

**Comment by pranav-prakash** [comment]
I *think* this might be due to a C++ quirk where `vector<bool>` is basically optimized into a bitset and doesn't have a `data()` method that returns a pointer like vector usually does. Maybe try `vector<uint8_t>`?

**Comment by SamG97** [comment]
Thanks, this does seem like a strange quirk indeed. Using `vector<uint8_t>` allows me to create the data I need and then using a `reinterpret_cast<bool*>` on the `uint8_t*` pointer that comes out of calling `bool_data.data()` when passing this into `Ort::Value::CreateTensor<bool>` allows the model to get tensors in the right type.
