### ISSUE TITLE
How is bench.in built?

### ISSUE THREAD

**Issue by dcostea** [microsoft/onnxruntime#3704]
I try to figure out how to convert from Image (byte[]) to tensor like the one existing in [bench.in.](https://github.com/microsoft/onnxruntime/blob/master/csharp/testdata/bench.in)

I can see the tensor has float numbers as it follows:
[[[[1.7640523911,0.4001572132,0.9787380099,2.2408931255,1.8675580025,-0.9772778749,0.9500884414,-0.1513572037,...

I would really appreciate to let me know what is the logic from image to tensor here in bench.in.

**Comment by hariharans29** [comment]
The logic of converting an image to a tensor would be specific to the model that the tensor is being fed into. For example, https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/mask-rcnn#preprocessing-steps describes the image pre-processing steps for the Mask RCNN and hence there is no "generic" logic for conversion and would have to depend on the model itself (how the model was trained). Hope this helps.

**Comment by hariharans29** [comment]
Closing this out for now. Please re-open if you have follow-up questions.
