### ISSUE TITLE
OnnxRuntime multithreading efficiency is poor

### ISSUE THREAD

**Issue by qiangliu7** [microsoft/onnxruntime#3713]
input is 1000 same queries ,the query for each request is the same,50-way multi-threaded concurrency:

onnxruntime cpu is 3000%, every request cost time, tensorflow is 60ms, and onnxruntime is 27ms,onnx is more than 2 times faster than tensorflow,

But the  very strange phenomenon is:

1000 different queries,every query is different,50-way multi-threaded concurrency:
onnxruntime cpu is 1500%,every request cost time, tensorflow is 60ms, and onnxruntime is 90ms,onnx is much slower than tensorflow

1-way concurrency onnxruntime cpu is 100%,and every request cost time is 15ms, tensorflow is 30ms.

My server configuration is 40 cpu cores,and the onnxruntime set up is:
		
	 session_options.SetInterOpNumThreads(1);
     session_options.SetIntraOpNumThreads(1);
	 export OMP_NUM_THREADS=1
	 

	 
I don't know how to explain this phenomenon, why the onnx cpu is very low

**Comment by snnn** [comment]
I assume you are using openmp?

**Comment by qiangliu7** [comment]
my service has 40 cpu cores,expected behavioral is : 50-way multi-threaded, CPU usage can reach 3000%, and  every request cost time  onnxruntime  is  fast then tensorflow .But the result is not !!!!
From the results of my previous experiments，1000 same queries cpu can reach 3000%, onnxruntime is  fast then tensorflow. Next ,the strange question is ,1000 different queries ,the cpu is very low,only 1000%, onnxruntime  cost time is  much slower than tensorflow

**Comment by Liujingxiu23** [comment]
@qiangliu7  Do you know how to control the usage of cpu to below 100%?

**Comment by OlegTheCat** [comment]
I'm currently using a sequential session with intra and inter num threads set to 1. The session is queried from many threads, so basically, this is "single ONNX session for all threads" setup. In my case, the bottleneck was the arena allocator. If I understand correctly, if the single session is used from many-many threads, the arena allocator may run out of memory allocated for itself, which leads to performance degradation. Anyways, disabling the arena allocator has increased the CPU utilization from ~20% to 100% (tested on c5.9xlarge AWS instance). Also, I turned off memory pattern optimizations, as @dashesy suggested, since input sizes in my model are dynamic.

**Comment by ledaiduongvnth** [comment]
> Can you build onnxruntime from source, from the master branch, and disable openmp at build time, then try it again?
> 
> To limit use to a single thread only, please do both of the following:
> 
>     * Build from source with openmp disabled
> 
>     * Set the session options intra_op_num_threads and inter_op_num_threads to 1 each.
> 
> 
> This will be supported in ONNX Runtime v1.3.0+
> 
> **Python example:**
> 
> ```python
> #!/usr/bin/python3
> import onnxruntime
> 
> opts = onnxruntime.SessionOptions()
> opts.intra_op_num_threads = 1
> opts.inter_op_num_threads = 1
> opts.execution_mode = onnxruntime.ExecutionMode.ORT_SEQUENTIAL
> ort_session = onnxruntime.InferenceSession('/path/to/model.onnx', sess_options=opts)
> ```
> 
> **C++ example:**
> 
> ```c++
> // initialize  enviroment...one enviroment per process
> Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");
> 
> // initialize session options if needed
> Ort::SessionOptions session_options;
> session_options.SetIntraOpNumThreads(1);
> session_options.SetInterOpNumThreads(1);
> #ifdef _WIN32
>   const wchar_t* model_path = L"squeezenet.onnx";
> #else
>   const char* model_path = "squeezenet.onnx";
> #endif
> 
> Ort::Session session(env, model_path, session_options);
> ```
> 
> And how many cpu cores do you have? What's the expected behavioral?

@snnn does the instruction for using onnxruntime with single thread work with Openvino accelerator?

**Comment by snnn** [comment]
It's for the default CPU execution provider.
