### ISSUE TITLE
Loading float16 model fails

### ISSUE THREAD

**Issue by katrasnikj** [microsoft/onnxruntime#3735]
When constructing `Ort::Session` with a float16 ONNX model I get the following error
```
Exception during initialization: C:\...\onnxruntime\onnxruntime\core\optimizer\optimizer_execution_frame.cc:73 onnxruntime::OptimizerExecutionFrame::Info::Info [ONNXRuntimeError] : 1 : FAIL : Failed to find kernel for Sub
```

**System information**
- OS: Windows 10
- ONNX Runtime build from source (6b3b4fe43e38c3c3f6f09dcad39988c804310b52)
- Visual Studio version 2019
- CUDA 10.2, cuDNN 7.6.5
- GPU model and memory: NVIDIA GeForce RTX 2080 Ti 11GB

**Comment by donrax** [comment]
Additional note. ONNX model of type float32 works on the aforementioned configuration. 
Both ONNX models are exported using pytorch 1.4.0 and opset version 11.

Might be related to dotnet/machinelearning#4795

**Comment by hariharans29** [comment]
Are you using the CPU binary or the CUDA binary ? We do not yet have a CPU kernel implemented yet for Sub (for float16 type) but the CUDA binary should have it - 

https://github.com/microsoft/onnxruntime/blob/156368b67f46fc6ab12b59ea39fcc93e51730ae7/onnxruntime/core/providers/cuda/cuda_execution_provider.cc#L392

**Comment by katrasnikj** [comment]
We use the CUDA binary. The following code shows how we create the `Ort::Session`
```cpp
  auto memory_info =
    Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU);

  environment_ = std::make_unique<Ort::Env>(ORT_LOGGING_LEVEL_FATAL);
  Ort::SessionOptions options;
  options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
  OrtSessionOptionsAppendExecutionProvider_CUDA(options, 0);
  session_ = std::make_unique<Ort::Session>(*environment_, onnx_model, model_size, options);
```

**Comment by hariharans29** [comment]
Could you share the model or a minimalistic model that can repro it ? CUDA should have a Sub kernel

**Comment by donrax** [comment]
You can find a minimalistic model [here](https://github.com/donrax/onnxbug/blob/master/mfp16.onnx)

**Comment by hariharans29** [comment]
@donrax  - #3836 will get you past the model loading stage

**Comment by donrax** [comment]
@hariharans29 Thank you for the assistance
