### ISSUE TITLE
Trouble running model with float64 input

### ISSUE THREAD

**Issue by Valks** [microsoft/onnxruntime#3736]
**Describe the bug**
I have an onnx model which worked fine when the inputs were float32 but I've changed it to float64 and now I'm getting the following error when I try to load the model file:

```
Microsoft.ML.OnnxRuntime.OnnxRuntimeException: '[ErrorCode:Fail] Type Error: Type parameter (T) bound to different types (tensor(double) and tensor(float) in node (lstm_3).'
```

**Urgency**
This has actually stopped my work. So important to myself :)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 x64 (GPU: Nvidia)
- ONNX Runtime installed from (source or binary): via pip
- ONNX Runtime version:1.6.0
- Python version: 3.7 x64
- Visual Studio version (if applicable): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1 (10.1.243) / 10.1 (v7.6.5.32)
- GPU model and memory: Nvidia 1080 GTX - 8GB

**To Reproduce**
try loading the onnx model:
```
var options = new SessionOptions
{
  GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_EXTENDED
};
options.AppendExecutionProvider_CUDA(0); // GPU: 0 (Note: Need to swap in the GPU nuget package)
using (var session = new InferenceSession(modelPath: _modelPath, options: options))
{
}
```

**Expected behavior**
Successfully load the model.

[model.zip](https://github.com/microsoft/onnxruntime/files/4546540/model.zip)

**Additional context**
I've attached the model giving me trouble. Hopefully it's something I'm doing wrong but I'm at a loss as to the cause and would appreciate some feedback.

**Comment by skottmckay** [comment]
The type of the LSTM weights and biases needs to match the input type so you need to convert those to double as well. 

![image](https://user-images.githubusercontent.com/979079/80568286-1b5c6e00-8a3a-11ea-90ad-b8b6644ae658.png)

**Comment by Valks** [comment]
@skottmckay Thanks for pointing that out. I'll take a look and see if I can figure out my mistake.

Still learning :)

**Comment by hariharans29** [comment]
Closing as the model seems to have incorrectly exported to ONNX. Please re-open if you have more questions.
