### ISSUE TITLE
Build problem with NNAPI Execution Provider 

### ISSUE THREAD

**Issue by Hramchenko** [microsoft/onnxruntime#3737]
**Describe the bug**

Hello. 

I'm trying to use **Android NNAPI Execution Provider**.
I build an onnxruntime with the options listed below:

`./build.sh --android --android_sdk_path /home/user/ML/Android/SDK/ --android_ndk_path /home/user/ML/Android/SDK/ndk/21.0.6113669/ --android_abi armeabi-v7a --android_api 27 --build_shared_lib --use_dnnlibrary`

I added `libonnxruntime.so` to my application, but there is an error when I'm trying to build it `use of undeclared identifier 'OrtSessionOptionsAppendExecutionProvider_Nnapi'`(all other code without this call builds OK). 

Please help me with the correct flags for compilation.

**Urgency**
None

**System information**
- OS Kubuntu 20.04;
- ONNX Runtime installed from source:
- ONNX Runtime version latest from github;
- Android Studio 3.6.1
- Android NDK 27.
- Building system of native code: CMake.

**To Reproduce**
- Install onnxruntime with NNAPI Execution Provider and 
- Include `OrtSessionOptionsAppendExecutionProvider_Nnapi` call to source code:
`Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");
Ort::SessionOptions session_options;
OrtSessionOptions* options_ = (OrtSessionOptions*)session_options;
Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_Nnapi(session_options));
AddNNApi(session_options); `

**Expected behavior**
Success build.

**Comment by j-bo** [comment]
Hi Hramchenko,
I wonder if your issue does not come from the fact that you compile using armeabi-v7a target.

Maybe NNAPI provider only exists on arm64-v8a targets ?

Side question: do you also encounter huge library files (>200mb) when building onnxruntime for android targets ?

**Comment by Hramchenko** [comment]
Hi.
Thank you for your interest in my problem. 
Unfortunately, I don't have a phone with arm64-v8a, so didn't check the build for this arch, but libonnxruntime_providers_nnapi.a was built and according to the compiler messages it was linked together with other libraries of libonnxruntime.so. 
P.S. really libonnxruntime.so it is quite large, its size 450 MB.

**Comment by gwang-msft** [comment]
For the 'use of undeclared identifier 'OrtSessionOptionsAppendExecutionProvider_Nnapi' issue,
You may want to include this header file, https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/providers/nnapi/nnapi_provider_factory.h

For the large binary size, this should be fixed after this PR (#3980) for Release and MinSizeRel flavor, the Debug and RelWithDebInfo will still have large footprint.

**Comment by Hramchenko** [comment]
Thank you very much!
