### ISSUE TITLE
[C# API] InferenceSession throws CUDA exception when used in a different thread

### ISSUE THREAD

**Issue by Chmielok** [microsoft/onnxruntime#3746]
**Describe the bug**
When you reuse the same InferenceSession in different threads (not at the same time of course), CUDA will throw an exception - CUDA error 700, illegal memory access. Digging deeper it turns out NativeMethods.OrtRun causes it.
This may seem like a rare case, but keep in mind just using Task.Run() can cause this exception.

**Urgency**
Low, a workaround is possible (not using .NET ThreadPool).

**System information**
- OS Platform and Distribution: Windows 10
- ONNX Runtime installed from: NuGet
- ONNX Runtime version: 1.2.0 (same thing happens in 1.0.0)
- Visual Studio version: 2019
- CUDA/cuDNN version: 10.2 (same thing happens in 10.0)
- GPU model and memory: GTX 1060 (6GB) + GTX 1070 (8GB)

**To Reproduce**
1. Create an InferenceSession on GPU. Model is irrelevant, but I used SegNet.
2. Create a dummy model input.
3. In a loop try to `var task = Task.Run(() => session.Run(...))` and wait for the task to finish. You can also expand the task function to include thread id logging (`Thread.CurrentThread.ManagedThreadId`).
4. One loop run will always succeed, the success of next runs depend on whether they get the same thread from thread pool. If not, the program crashes.

**Expected behavior**
The method call should proceed as if it was run in a single-threaded environment.

**Comment by PDLGuLu** [comment]
老哥，解决了吗
