### ISSUE TITLE
Implement OnnxRuntime in MagicLeap using Unity

### ISSUE THREAD

**Issue by alexivaner** [microsoft/onnxruntime#3763]
**Describe the bug**
Hi, I tried to run OnnxRuntime in MagicLeap using Unity. When I debugging and played in Windows PC, It is worked, but something goes wrong when I deploy to magic leap. I got some error like this:

**unable to find entry point named OrtGetApiBase in onnxruntime**

**Urgency**
I have to implemented this project before middle of may

**System information**
-Lumin OS 0.98.10
-Lumin SDK 0.24
- ONNX Runtime installed from package manually in unity

**Comment by faxu** [comment]
@alexivaner sorry for the delay. is this still an issue or were you able to figure this out?

**Comment by alexivaner** [comment]
yes, it still an issue to load onnx model with onnx runtime in magic leap. Now I am using unity barracuda to load onnx model, although still not all the onnx operator supported by barracuda.

**Comment by dabc312GitHub** [comment]
@alexivaner HI. Hace you run onnx in magic leap at the end?? I am thinking to put models into magic leap one

**Comment by mattycorbett** [comment]
Try this - https://github.com/pytholic/NugetForUnityTest. Worked for me!
