### ISSUE TITLE
ORT throws GEMM error, but there's no GEMM operator in  model

### ISSUE THREAD

**Issue by jignparm** [microsoft/onnxruntime#3764]
**Describe the bug**

Attached a model with 3 ops: MatMul, Mul and Add. It should run successfully, but ORT errors out with a message, referencing a `gemm_0` op that doesn't exist in the model.

Where is `gemm_0` coming from? Looks like it's generated on the fly, but that's not  correct because Gemm cannot handle these specific tensor shapes (whereas MatMul, Mul and Add should handle the shapes successfully).

[matmul.zip](https://github.com/microsoft/onnxruntime/files/4557884/matmul.zip)

```python
======== GRAPH ===========
graph tf2onnx (
  %input2:0[FLOAT, 1x4]
  %input1:0[FLOAT, 3x1]
  %input:0[FLOAT, 3x3]
) initializers (
  %Const_1:0[FLOAT, scalar]
) {
  %MatMul:0 = MatMul(%input:0, %input1:0)
  %Mul_1:0 = Mul(%Const_1:0, %input2:0)
  %output:0 = Add(%MatMul:0, %Mul_1:0)
  return %output:0
}
```
![image](https://user-images.githubusercontent.com/13698702/80705768-865b8280-8ad6-11ea-98d6-b38521805c26.png)

![image](https://user-images.githubusercontent.com/13698702/80704056-6e363400-8ad3-11ea-89b1-37edbd50a10d.png)

**Urgency**
Bug. A user issue is blocked.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): All OS
- ONNX Runtime installed from (source or binary): 1.2.0 from Pypi
- ONNX Runtime version: 1.2.0
- Python version: 3.7
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
Unzip model, and load it using ORT (see screenshot)

**Expected behavior**
Should be able to add and multiply without error.

**Screenshots**
See above

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by snnn** [comment]
https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Graph_Optimizations.md

GraphOptimizationLevel::ORT_DISABLE_ALL -> Disables all optimizations

Please disable it and try again.

**Comment by jignparm** [comment]
`GraphOptimizationLevel::ORT_DISABLE_ALL` runs OK.

So it sounds like an optimizer error? It probably  needs to check for shapes before fusing ops.

**Comment by snnn** [comment]
Right. We have many many optimizers to be fixed.  Feel free to patch it by yourself.

**Comment by jignparm** [comment]
Thanks @snnn. I'll try a patch in tf2onnx to avoid this condition during model conversion -- to  unblock the user quickly. 

> We have many many optimizers to be fixed

Seems like a trade-off between speed and fix...
