### ISSUE TITLE
Onnxruntime not running on GPU in python environment

### ISSUE THREAD

**Issue by Amirtha1189** [microsoft/onnxruntime#3787]
Hi,

Here are my onnx and onnxruntime versions that i have installed in python 3.5
onnx - 1.6.0
onnxruntime 1.2.0
onnxruntime-gpu  1.2.0
Tensorflow-gpu 1.15.0
CUDA 10.1

I converted a simple Tensorflow model to onnx and ran inference on onnxruntime. But the model runs only on CPU and when i checked using get_device(), i could get only CPUExecutionProvider.

Could you help me with this?

Thanks.

**Comment by pranavsharma** [comment]
If you want to run on GPU, you don't need to install onnxruntime (CPU pkg). Installing onnxruntime-gpu should suffice; it includes CPU execution.

**Comment by hariharans29** [comment]
Closing. Please re-open if that didn't solve it. Thanks.
