### ISSUE TITLE
ONNX runtime takes much time and memory to load model

### ISSUE THREAD

**Issue by do-van-long** [microsoft/onnxruntime#3802]
**Describe the bug**
I tried to run inference with several ONNX models on my Jetson Nano (ARM64 with 04 GB RAM). However, the loading speed is very slow and it takes my whole RAM. The 'model.onnx' could be 7MB (centerface.onnx), 36MB (yolov3-tiny-416.onnx) and 248MB (yolov3-416.onnx). The first two models could be loaded successfully with Swap memory but the last one could not be loaded. The following code consumed my whole RAM.
`import onnxruntime

sess = onnxruntime.InferenceSession('model.onnx')
`
**Urgency**
ASAP

**System information**
- OS Platform and Distribution: 18.04 (flashed from Image for Jetson Nano)
- ONNX Runtime installed from: source
- ONNX Runtime version: 1.0.0
- Python version: 3.6.9
- Visual Studio version (if applicable): None
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.x
- GPU model and memory: 4GB

**Expected behavior**
Is it a bug or functionality? How can I solve the problem? The loaded memory should only be approximated the model size on disk, isn't it?

**Comment by skottmckay** [comment]
There are a few things that happen at load time which will require more memory than the model size. 

Two main ones are:

When model optimization runs to do things like constant folding it may create new initializers to replace nodes. Any redundant initializers will be removed at the end of that process, but memory usage will be higher while it's running. You could try disabling the optimizers to see if that helps.

e.g.
    so = ort.SessionOptions
    so.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL
    sess = ort.InferenceSession(model_path, so)

Additionally the initializers (i.e. weights) from the model file's protobuf format are converted to the ORT in-memory format. After the conversion the original initializers from the protobuf are freed, but until that point you'll have roughly double the size of the initializers in memory.

**Comment by do-van-long** [comment]
Thanks @skottmckay for your clarification. It helps me a bit when initializing an ORT session but it still uses about GB memory (for centerface.onnx model of 7MB). Luckily, the session is initialized successfully without using SWAP memory.

I have also tried to save an optimized version by adding this line:
`so.optimized_model_filepath = optimized_centerface.onnx`

After initializing the session, an optimized version is saved. However, I could not start a session with the optimized model (onnx.checker.check_model call was successful). This line
`sess = ort.InferenceSession('optimized_centerface.onnx')`
produced error "Fatal error: TRTKernel_0 is not a registered function/op".

How can I use the optimized model? Or is there any way to start an ORT session faster?

**Comment by skottmckay** [comment]
TRTKernel_0 is a fused subgraph created by TensorRT. You haven't mentioned building with or enabling the TensorRT execution provider anywhere though, and without doing that there shouldn't (afaik) be a way to get a node like that in the optimized graph. 

Are you actually using the TensorRT execution provider?

**Comment by BharathJaina** [comment]
Hi @skottmckay,

I'm using **resnet50v2** model and optimized with the tensorrt and when I'm loading the same file, it is failing with the following error: 
"**_Fatal error: TRTKernel_graph_resnet50v2_0 is not a registered function/op_**" 
and with **mobilenet**, error:
"**_Fatal error: TRTKernel_graph_mobilenet_1.00_224_0 is not a registered function/op_**"

Below is the script to generat the optimized file:
```
    sess_options = onnxruntime.SessionOptions()
    sess_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL #Varying with all the options
    sess_options.execution_mode = onnxruntime.ExecutionMode.ORT_SEQUENTIAL
    sess_options.optimized_model_filepath = model_file
    sess_options.intra_op_num_threads = 2
    session = onnxruntime.InferenceSession(original_model, sess_options, providers="TensorrtExecutionProvider")

#Loading new session
   session2 = onnxruntime.InferenceSession(model_file, sess_options, providers="TensorrtExecutionProvider")
```

For CPU and CUDA as the execution providers, they are working, but isn't the case with TensorRT

**Comment by skottmckay** [comment]
TensorRT needs to compile nodes at runtime. We probably shouldn't allow saving an optimized model if TensorRT compiled nodes as it won't be able to be loaded (we don't have a mechanism to save the compiled functions - just the node information).

If you want to use an EP that compiles nodes the best you can do is to optimize the model using ORT_ENABLE_BASIC with just the ORT CPU EP enabled. That will do things like constant folding but not use internal operators that may limit the nodes TensorRT could take. At runtime you can load that optimized mode with the TensorRT enabled and optimization set to ORT_ENABLE_ALL.

Whether that helps with memory usage is unknown. I don't know how large the cost of TensorRT compiling nodes is. I would expect it to be significant though

**Comment by BharathJaina** [comment]
Thanks for confirming. The Load time turns around, ~15s. But at the same time, inference time for 1st input set is ~9s, normally[or from second input set in the same session] it is 3/4**ms**.  
Am I missing anything?
