### ISSUE TITLE
value info is not updating

### ISSUE THREAD

**Issue by engdorm** [microsoft/onnxruntime#3808]
**Describe the bug**
When making changes in the graph with the optimization passes, 
even if the Resolve function updates the NodeArgs in the Graph::node_args_
it won't update NodeArgs in value_info_
as a result from this, if you want to look on the optimized graph on netron or some other tool
you can't see the tensors shapes on the graph

**Urgency**
none

**System information**
- .Linux Ubuntu 16.04
- ONNX Runtime installed from source 
- ONNX Runtime version: 1.6
- Python version:3.6,9
- GCC/Compiler version (if compiling from source): 7.5.0

**To Reproduce**
Need a pass that changes the shapes or adds new nodes

**Expected behavior**
In the case of new node with new edge, no new ArgNode will be added to Graph::value_info_
but only to Graph::node_args_ 
So in the python you won't be able to get the new (edge/tensor) shpae
**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by skottmckay** [comment]
Typically (at least in my experience) onnx models have very few items in GraphProto::value_info as it's optional to add values there, and doing so makes a model larger. 

```
  // Information for the values in the graph. The ValueInfoProto.name's
  // must be distinct. It is optional for a value to appear in value_info list.
  repeated ValueInfoProto value_info = 13;

```

Additionally any shape information in the value_info items is likely to be ignored/overwritten anyway as type and shape inferencing is run when the model is loaded.

As we don't want to unnecessarily increase the saved model size I'm not sure that we should arbitrarily add new items to value_info.

Can you clarify what you're wanting to do? You've mentioned internals to the Graph class (the NodeArg instances in Graph::value_info_), Netron (viewing the saved onnx model which would involve onnx GraphProto) and python.

If viewing info in python (assuming you're using the 'onnx' module to look for shapes of internal values) have you tried running the ONNX shape inferencing on the model after loading it? https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#running-shape-inference-on-an-onnx-model

Alternatively the onnxruntime core\providers\nuphar\scripts\symbolic_shape_infer.py script may be able to run more advanced shape inferencing and save the onnx model with GraphProto::value_info more fully populated if it supports the operators in your model.

**Comment by engdorm** [comment]
I'm trying to add new Node, whereas I wrote new scheme for it and filled out TypeAndShapeInferenceFunction,
The new node is added in a new pass (GraphTransformer)
And when I run the OnnxRunTime through python (onnxruntime::InferenceSession)
I get the shapes while cpp is running in the NodeArg
But I can't get them in back in the onnx model, 
And of course, can't present them in Netron

Because I didn't add it to the onnx and rebuild it, 
Even when I try to use onnx::shape_inference
It won't add the shapes

I saw that in graph.cc in [ToGraphProtoInternal](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/graph/graph.cc#L2563)
 you copy back value_info to the graph,
although it didn't change
