### ISSUE TITLE
QuantizeLinear fails without optional zero point input

### ISSUE THREAD

**Issue by pmarcinkiewicz** [microsoft/onnxruntime#3820]
**Describe the bug**
QuantizeLinear operator fails, when optional y_zero_point input is not set. QuantizeLinear takes three inputs: x, y_scale and optional y_zero_point:
https://github.com/onnx/onnx/blob/master/docs/Operators.md#QuantizeLinear

**Urgency**
None

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04:
- ONNX Runtime installed from (source or binary): binary from pip install
- ONNX Runtime version: 1.6.0
- Python version: 3.6.9
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 9.1, V9.1.85
- GPU model and memory: N/A

**To Reproduce**
Pleas use this script to preproduce error
```
import onnx
import onnxruntime
X = onnx.helper.make_tensor_value_info('X', onnx.TensorProto.FLOAT, (2,))
Y = onnx.helper.make_tensor_value_info('Y', onnx.TensorProto.INT8, [2])
qrange_initializer = onnx.helper.make_tensor('qrange_2', onnx.TensorProto.FLOAT, [1], [127.0])
qrange_value_info = onnx.helper.make_tensor_value_info('qrange_2', onnx.TensorProto.FLOAT, [1])
quant_node = onnx.helper.make_node('QuantizeLinear', ['X', 'qrange_2'], ['Y'], name='quantize')
nodes = [quant_node]
graph = onnx.helper.make_graph(nodes = nodes, inputs = [X, qrange_value_info], outputs = [Y], initializer = [qrange_initializer], name = "graph")
model_from_test = onnx.helper.make_model(graph, producer_name='test')
onnx.save(model_from_test, 'model_from_test.onnx')
session_from_test = onnxruntime.InferenceSession("model_from_test.onnx", None)
```

**Expected behavior**
The session should be created and inference possible for this model.

**Screenshots**
Error from console:

```
Fail: [ONNXRuntimeError] : 1 : FAIL : Node (quantize) Op (QuantizeLinear) /onnxruntime_src/include/onnxruntime/core/common/const_pointer_container.h:78 const T* onnxruntime::ConstPointerContainer<Container>::at(size_t) const [with Container = std::vector<onnxruntime::NodeArg*>; onnxruntime::ConstPointerContainer<Container>::T = onnxruntime::NodeArg; size_t = long unsigned int] index < data_.size() was false.
```

**Additional context**
QuantizeLinear works correctly with y_zero_point passed as third input:

```
import onnx 
import onnxruntime
import numpy as np
X = onnx.helper.make_tensor_value_info('X', onnx.TensorProto.FLOAT, (2,))
Y = onnx.helper.make_tensor_value_info('Y', onnx.TensorProto.INT8, [2])
qrange_initializer = onnx.helper.make_tensor('qrange_2', onnx.TensorProto.FLOAT, [], [1.0])
zero_initializer = onnx.helper.make_tensor('zero_point', onnx.TensorProto.INT8, [], [0])
qrange_value_info = onnx.helper.make_tensor_value_info('qrange_2', onnx.TensorProto.FLOAT, [])
zero_point = helper.make_tensor_value_info('zero_point', TensorProto.INT8, [])
quant_node = onnx.helper.make_node('QuantizeLinear', ['X', 'qrange_2', 'zero_point'], ['Y'], name='quantize')
nodes = [quant_node]
graph = onnx.helper.make_graph(nodes = nodes, inputs = [X, qrange_value_info], outputs = [Y], initializer = [qrange_initializer, zero_initializer], name = "graph")
model_from_test = onnx.helper.make_model(graph, producer_name='test')
onnx.save(model_from_test, 'model_from_test.onnx')
session_from_test = onnxruntime.InferenceSession("model_from_test.onnx", None)
x = np.zeros((2), dtype=np.float32)
x[0] = 5
y = session_from_test.run([], {'X': x})
y[0]
```
Output:
```
Out[253]: array([5, 0], dtype=int8)
```

**Comment by pranav-prakash** [comment]
I think this should be a straightforward change where you check `OpKernel::Node().InputDefs().size();` and only dereference `y_zero_point` when this is `3`.
https://github.com/microsoft/onnxruntime/blob/0e59668c1b8974afa9ec8e09e2da7b47dcbbb86b/onnxruntime/core/providers/cpu/tensor/quantize_linear.cc#L100

The same change might have to be done for CUDA and other providers as well.

**Comment by pmarcinkiewicz** [comment]
There is one much bigger problem. This operator infers output type from ZERO POINT. If one passes int8 as zer point tensor, then output is int8.

There are two possible solutions. Documentation should be fixed to reflect real behaviour of operator, or operator must be extended with type parameter.

**Comment by yufenglee** [comment]
@pmarcinkiewicz, thanks for reporting this issue. Will fix it. As for the problem in the type inference, the spec says: "Default value is uint8 typed 0 if it's not specified.". If no zero point is specified, the type will be uint8 and the value will be 0, even though using 0 as default zero-point for type uint8 is not good. 127 is better or default type is int8.

**Comment by pmarcinkiewicz** [comment]
Issue was solved with PR: https://github.com/microsoft/onnxruntime/pull/4065
