### ISSUE TITLE
I am looking for something similar to doing what tensorflow_session.get_tensor_by_name("intermediate_node").shape() does

### ISSUE THREAD

**Issue by amitrokade47** [microsoft/onnxruntime#3865]
**Describe the bug**

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by amitrokade47** [comment]
I am new to onnx. I have created a sample model in onnx using the Python API. I wanted to know if there's any way to get shapes of output edges of intermediate nodes in a model. Since the shape would depend on the inputs provided , I assume this should be somewhere in onnx runtime, but for now I haven’t found anything. I am looking for something similar to doing what tensorflow_session.get_tensor_by_name("intermediate_node").shape() does

**Comment by pranavsharma** [comment]
Will this help? https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#debugnodeinputsoutputs

**Comment by amitrokade47** [comment]
Any python script API present other than CLI?
