### ISSUE TITLE
[ONNXRuntimeError] Fatal error: adaptive_max_pool2d is not a registered function/op

### ISSUE THREAD

**Issue by ShahrearBinAmin** [microsoft/onnxruntime#3878]
**Describe the bug**
I've exported my Pytorch model to onnx but when i try to load this onnx model with onnx runtime 

```
ort_session = ort.InferenceSession(ONNX_MODEL)
x = np.random.randn(1, 1, 48, 240).astype(np.float32)
outputs = ort_session.run(None, {'input': x})
```
but getting this error

```
     41          raise TypeError("Unable to load from type '{0}'".format(type(self._path_or_bytes)))
     42 
---> 43         self._sess.load_model(providers)
     44 
     45         self._session_options = self._sess.session_options

Fail: [ONNXRuntimeError] : 1 : FAIL : Fatal error: adaptive_max_pool2d is not a registered function/op
```

**System information**
- OS Platform and Distribution : Linux Ubuntu 18.04.3 LTS
- ONNX Runtime installed from : binary
- ONNX Runtime version: 1.2.0
- Python version: 3.6.9

**Expected behavior**
Expected to infer with this example without any error

**Additional context**
While converting my model to onnx I'v used following parameters

 ```
x = torch.rand(1, 1, 48, 240)
onnx.export(self.net_,
                          x,
                          "saved_models/anpr.onnx",
                          opset_version=11,
                          operator_export_type=onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK,
                          input_names=["input"],
                          output_names=["output"])
```
I've got an warning but exported an ```.onnx``` file.
```
/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_helper.py:176: UserWarning: ONNX export failed on adaptive_max_pool2d because output size that are not factor of input size not supported
  warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
```

**Comment by hariharans29** [comment]
Please report this to PyTorch as the exported onnx model is not valid because onnx doesn’t support ‘adaptive_max_pool2D’ in any opset version. The PyTorch exporter must convert it to its onnx equivalent. Thanks.

**Comment by ShahrearBinAmin** [comment]
@hariharans29 Maybe I'm wrong but adaptive_max_pool2d is supported from opset version 9, it's mapped to equivalent `MaxPool` of onnx.

```adaptive_max_pool2d = _adaptive_pool('adaptive_max_pool2d', "MaxPool", _pair, max_pool2d_with_indices)```

[https://github.com/pytorch/pytorch/blob/65260d48c838a4d04e0a8e0d097445aab46aaa9f/torch/onnx/symbolic_opset9.py#L787](opset)

**Comment by hariharans29** [comment]
The ONNX graph must have its ONNX equivalent in the ONNX graph. The error message you shared - 
"adaptive_max_pool2d is not a registered function/op" is indicative that the ONNX graph does not have the ONNX equivalent op (i.e.) the PyTorch export to ONNX has failed which aligns with the warning you see at export time - "UserWarning: ONNX export failed on adaptive_max_pool2d because output size that are not factor of input size not supported".
