### ISSUE TITLE
Simplify the C++ samples

### ISSUE THREAD

**Issue by jgbradley1** [microsoft/onnxruntime#3879]
Please consider simplifying the C++ [examples](https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx) and remove all windows-specific headers. As a new user of onnxruntime (in C++), it is extra difficult to run the examples when they rely on a Windows development environment.

A cleaner more succinct example would be an application that runs inference over the MNIST test data from the command line (using linux).

As a suggestion, an alternative tutorial that I found to to be very informative for another framework is what Facebook provides for libTorch [here](https://pytorch.org/tutorials/advanced/cpp_frontend.html). It would be great if there was a similar kind of in-depth tutorial that walked a C++ dev through an onnxruntime example.

**Comment by pranav-prakash** [comment]
Confusingly enough there *is* a pure-cross platform C++ API sample, but it's under the `csharp` folder where no one would think to look:

https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp

**Comment by jywu-msft** [comment]
@RyanUnderhill FYI

**Comment by pranavsharma** [comment]
Samples for all language bindings are linked from this central page - https://github.com/microsoft/onnxruntime/tree/master/samples.

**Comment by tfburns** [comment]
Examples are nice, but documentation is sorely missing.

**Comment by jinfagang** [comment]
After simplified I can only see nodejs and python, where is c++ samples?
