### ISSUE TITLE
Inference for a intermedia tensor. (Python API)

### ISSUE THREAD

**Issue by model-collapse** [microsoft/onnxruntime#3887]
Hi all,
I am currently trying to debug a model translated from another framework to onnx. There are some differences between the two inference results. So I decided to compare the results after conducting each layer. So is there a way to export the result of a specified tensor without the full inference? I tried to set the first argument of InferenceSession.run as the required tensor's name and got the error "Invalid Output Name:XXX".

**Comment by hariharans29** [comment]
Hello,

Right now you can't request for an intermediate tensor's results, but you could add the tensor you are interested in to the output list and check its contents after **full** inference run (ORT doesn't support partial graph execution). Please check https://github.com/microsoft/onnxruntime/issues/2344 and linked issues in the comments for ways to make it happen. 

Please re-open if you have further questions/comments
