### ISSUE TITLE
Privacy / telemetry policy clarification

### ISSUE THREAD

**Issue by hackini** [microsoft/onnxruntime#3898]
As a Python user who is not familiar with `onnxruntime` source code, the [privacy policy](https://github.com/microsoft/onnxruntime/blob/master/docs/Privacy.md) is not very clear.

By using the official python package ( i.e. installed with` pip install onnxruntime`), am I subject to telemetry ?

i.e. by simply running a model as in [the tutorial](https://microsoft.github.io/onnxruntime/python/tutorial.html#step-3-load-and-run-the-model-using-onnx-runtime) : 

```
import onnxruntime as rt
sess = rt.InferenceSession("model.onnx")
prediction = sess.run(...)
```

will those three lines of code send data to Microsoft ? If yes, do I have the option (through the Python API) to disable telemetry ?

Thanks

**Comment by snnn** [comment]
Yes.

> If yes, do I have the option (through the Python API) to disable telemetry ?
You may build onnxruntime from source.  Just make sure 'onnxruntime_USE_TELEMETRY ' option is off. 
https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L92

**Comment by hariharans29** [comment]
@faxu  - Maybe the privacy policy can be part of the FAQ ?

**Comment by hackini** [comment]
Thank you for the answer, I understood telemetry was disabled using custom builds, but my question was about the official package (which is what most people will use and is the easiest way to distribute cross-platform without having to maintain everything yourself).

_Using official packages_, if a window user disables  the _Windows Error Reporting service_, will onnxruntime still send telemetry data ?

What about Mac & Linux ? When telemetry will be enabled there on the official builds (if that's not already the case), will there be a way to disable telemetry (in the official builds) ?

Would you be open to add a function in the (Python) API to let anyone freely choose whereas or not to enable telemetry in the official build ?

**Comment by snnn** [comment]
> Using official packages from the Python API, if a window user disables the Windows Error Reporting service, will onnxruntime still send telemetry data ?

Yes.

> What about Mac & Linux ? When telemetry will be enabled there on the official builds 

No.

**Comment by snnn** [comment]
Please reopen it if you have more questions.

**Comment by snnn** [comment]
I'm so sorry. I think I was wrong. The official python package doesn't have telemetry. The nuget one has.

**Comment by hackini** [comment]
Thank you for the answer

> > Using official packages from the Python API, if a window user disables the Windows Error Reporting service, will onnxruntime still send telemetry data ?
> 
> Yes.
> 
> > What about Mac & Linux ? When telemetry will be enabled there on the official builds
> 
> No.

It would be nice to let people choose whereas they want to send telemetry. Telemetry already lead to VSCode vs. VSCodium. It would be a shame we'd have to maintain a telemetry free "onnxruntium" build in parrallel. 

> The official python package doesn't have telemetry.

That's really great, thanks for the precision. maybe it could be precised in the Privacy policy which packages contain telemetry and which don't

**Comment by snnn** [comment]
Thank you! I'll forward your concerns to our PM.

**Comment by faxu** [comment]
@hackini @snnn

To clarify, the telemetry collection is not done by ONNX Runtime to directly send to any Microsoft or other server. Having telemetry enabled in a build only indicates ONNX Runtime participation in the Windows telemetry program - [Trace Logging](https://docs.microsoft.com/en-us/windows/win32/tracelogging/trace-logging-about). 

Trace Logging is the mechanism for Windows to collect events from various applications (locally). With user consent (configured on their Windows machine), the data will be periodically uploaded to the server, where Microsoft only maintains a sampling of anonymized data compliant with GDPR and other privacy regulations. @walrusmcd to keep me honest. We will update the privacy page to make this more clear; thanks for the feedback.
