### ISSUE TITLE
Wrong result with `If` node

### ISSUE THREAD

**Issue by nomaddo** [microsoft/onnxruntime#3900]
**Describe the bug**
Wrong result is produce with the following ONNX.
https://gist.github.com/nomaddo/965614ac0684e1042850f6d84cc38970

[See how to create](https://gist.github.com/nomaddo/965614ac0684e1042850f6d84cc38970#file-gen_onnx-py-L52-L62)
[See how to run](https://gist.github.com/nomaddo/965614ac0684e1042850f6d84cc38970#file-run-py)

This ONNX graph has one `if` node with very simple sub-graphs (having  one `Constant` node).
The sub-graphs never return `0.`, but got wrong result as follows:

```
$ python3 run.py model.onnx 
[array([[[[0.]]]], dtype=float32)]
```

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 10 (buster) 
- ONNX Runtime installed from (source or binary): binary (via pip)
- ONNX Runtime version: 1.2.0
- Python version: 3.7.3
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.

```
$ sudo docker run -it --rm debian:buster /bin/bash
$ apt update; apt install -y ssh git python3 python3-pip
$ git clone https://gist.github.com/965614ac0684e1042850f6d84cc38970.git bug_report
$ cd bug_report
$ pip3 install onnx onnxruntime
$ pip3 list
Package           Version
----------------- -------
asn1crypto        0.24.0 
cryptography      2.6.1  
entrypoints       0.3    
keyring           17.1.1 
keyrings.alt      3.1.1  
numpy             1.18.4 
onnx              1.7.0  
onnxruntime       1.2.0  
pip               18.1   
protobuf          3.11.3 
pycrypto          2.6.1  
PyGObject         3.30.4 
pyxdg             0.25   
SecretStorage     2.3.1  
setuptools        40.8.0 
six               1.12.0 
typing-extensions 3.7.4.2
wheel             0.32.3 
$ python3 gen_onnx.py  # create model.onnx
$ python3 run.py model.onnx 
[array([[[[0.]]]], dtype=float32)]
```

- Attach the ONNX model to the issue (where applicable) to expedite investigation.
https://gist.github.com/nomaddo/965614ac0684e1042850f6d84cc38970#file-model-onnx

**Expected behavior**
Got the following result:

```
$ python3 run.py model.onnx 
[array([[[[1001.]]]], dtype=float32)]
```

**Screenshots**
None

**Additional context**
None

**Comment by hariharans29** [comment]
I couldn't repro this in current master (I used the `onnx_test_runner` app to run the model)  - 

![image](https://user-images.githubusercontent.com/9969784/81975672-3ef7ea80-95dc-11ea-8acb-446181214661.png)

I tried to trigger both conditional branches - `if`, and `else` and it outputs the expected results in both cases. I ll build the Python wheel and try.

**Comment by hariharans29** [comment]
I could repro it in the 1.2.0 wheel but with the wheel built off lastes master, it seems to go away. So, with the upcoming release, you should be able to use it. Thanks for reporting.

**Comment by hariharans29** [comment]
https://github.com/microsoft/onnxruntime/pull/3912 had the fix for this
