### ISSUE TITLE
Error when trying to build ONNXRuntime in Jetson Nano

### ISSUE THREAD

**Issue by muralikrishnat29** [microsoft/onnxruntime#3913]
**Describe the bug**
Tried to build and install ONNXRuntime-gpu-tensorrt in Nano from source following the below link
[Build Instructions]( https://github.com/microsoft/onnxruntime/issues/2684#issuecomment-568548387 )
, but failed with an error when cmake is trying to build cudnn_rnn_base.cc.o. 

**System information**
- Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): Trying to install from source
- ONNX Runtime version: Latest and upto commit b783805
- GCC/Compiler version (if compiling from source):
- CUDA/TensorRTversion: CUDA 10.2/TensorRT 7.1.0
- Device: Jetson Nano

**To Reproduce**
- Steps to reproduce
   Followed the build instructions given in the following link
  [Build Instructions]( https://github.com/microsoft/onnxruntime/issues/2684#issuecomment-568548387)

**Expected behavior**
ONNXRuntime whl getting built

**Additional context**
   It would be good if we have any dockerfile for onnxruntime with tensorrt backend for ARM64 architecture
   Or is the library compatible only with earlier versions of CUDA and TensorRT?

**Log**
[ 51%] Building CXX object CMakeFiles/onnxruntime_providers_cuda.dir/usr/local/onnxruntime/onnxruntime/core/providers/cuda/rnn/cudnn_rnn_base.cc.o
In file included from /usr/local/onnxruntime/include/onnxruntime/core/framework/tensor.h:12:0,
from /usr/local/onnxruntime/onnxruntime/core/framework/data_transfer.h:7,
from /usr/local/onnxruntime/onnxruntime/core/framework/data_transfer_manager.h:7,
from /usr/local/onnxruntime/onnxruntime/core/providers/cuda/cuda_common.h:7,
from /usr/local/onnxruntime/onnxruntime/core/providers/cuda/cudnn_common.h:5,
from /usr/local/onnxruntime/onnxruntime/core/providers/cuda/rnn/cudnn_rnn_base.h:7,
from /usr/local/onnxruntime/onnxruntime/core/providers/cuda/rnn/cudnn_rnn_base.cc:4:
/usr/local/onnxruntime/onnxruntime/core/providers/cuda/rnn/cudnn_rnn_base.h: In member function ‘onnxruntime::common::Status onnxruntime::cuda::CudnnRNN::Set(cudnnContext* const&, int64_t, int, cudnnDropoutDescriptor_t, cudnnDirectionMode_t, cudnnRNNMode_t, cudnnDataType_t)’:
/usr/local/onnxruntime/onnxruntime/core/providers/cuda/rnn/cudnn_rnn_base.h:45:27: error: ‘cudnnSetRNNDescriptor’ was not declared in this scope
CUDNN_RETURN_IF_ERROR(cudnnSetRNNDescriptor(cudnnHandle,
^
/usr/local/onnxruntime/include/onnxruntime/core/common/common.h:157:21: note: in definition of macro ‘ORT_RETURN_IF_ERROR_SESSIONID’
auto _status = (expr);
^~~~
/usr/local/onnxruntime/onnxruntime/core/providers/cuda/cuda_common.h:40:3: note: in expansion of macro ‘ORT_RETURN_IF_ERROR’
ORT_RETURN_IF_ERROR(CUDNN_CALL(expr)
^~~~~~~~~~~~~~~~~~~
/usr/local/onnxruntime/onnxruntime/core/providers/cuda/cuda_common.h:40:23: note: in expansion of macro ‘CUDNN_CALL’
ORT_RETURN_IF_ERROR(CUDNN_CALL(expr)
^~~~~~~~~~
/usr/local/onnxruntime/onnxruntime/core/providers/cuda/rnn/cudnn_rnn_base.h:45:5: note: in expansion of macro ‘CUDNN_RETURN_IF_ERROR’
CUDNN_RETURN_IF_ERROR(cudnnSetRNNDescriptor(cudnnHandle,
^
/usr/local/onnxruntime/onnxruntime/core/providers/cuda/rnn/cudnn_rnn_base.h:45:27: note: suggested alternative: ‘cudnnSetLRNDescriptor’
CUDNN_RETURN_IF_ERROR(cudnnSetRNNDescriptor(cudnnHandle,
^
/usr/local/onnxruntime/include/onnxruntime/core/common/common.h:157:21: note: in definition of macro ‘ORT_RETURN_IF_ERROR_SESSIONID’
auto _status = (expr);
^~~~
/usr/local/onnxruntime/onnxruntime/core/providers/cuda/cuda_common.h:40:3: note: in expansion of macro ‘ORT_RETURN_IF_ERROR’
ORT_RETURN_IF_ERROR(CUDNN_CALL(expr)
^~~~~~~~~~~~~~~~~~~
/usr/local/onnxruntime/onnxruntime/core/providers/cuda/cuda_common.h:40:23: note: in expansion of macro ‘CUDNN_CALL’
ORT_RETURN_IF_ERROR(CUDNN_CALL(expr)
^~~~~~~~~~
/usr/local/onnxruntime/onnxruntime/core/providers/cuda/rnn/cudnn_rnn_base.h:45:5: note: in expansion of macro ‘CUDNN_RETURN_IF_ERROR’
CUDNN_RETURN_IF_ERROR(cudnnSetRNNDescriptor(cudnnHandle,
^
CMakeFiles/onnxruntime_providers_cuda.dir/build.make:517: recipe for target ‘CMakeFiles/onnxruntime_providers_cuda.dir/usr/local/onnxruntime/onnxruntime/core/providers/cuda/rnn/cudnn_rnn_base.cc.o’ failed
make[2]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/usr/local/onnxruntime/onnxruntime/core/providers/cuda/rnn/cudnn_rnn_base.cc.o] Error 1
CMakeFiles/Makefile2:718: recipe for target ‘CMakeFiles/onnxruntime_providers_cuda.dir/all’ failed
make[1]: *** [CMakeFiles/onnxruntime_providers_cuda.dir/all] Error 2
Makefile:162: recipe for target ‘all’ failed
make: *** [all] Error 2
Traceback (most recent call last):
File “/usr/local/onnxruntime/tools/ci_build/build.py”, line 1731, in
sys.exit(main())
File “/usr/local/onnxruntime/tools/ci_build/build.py”, line 1627, in main
build_targets(args, cmake_path, build_dir, configs, args.parallel)
File “/usr/local/onnxruntime/tools/ci_build/build.py”, line 853, in build_targets
run_subprocess(cmd_args, env=env)
File “/usr/local/onnxruntime/tools/ci_build/build.py”, line 392, in run_subprocess
env=my_env, shell=shell)
File “/usr/lib/python3.6/subprocess.py”, line 438, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command ‘[’/usr/local/bin/cmake’, ‘–build’, ‘/usr/local/onnxruntime/build/Linux/Release’, ‘–config’, ‘Release’]’ returned non-zero exit status 2.

**Comment by jywu-msft** [comment]
please follow these instructions (for JetPack 4.3,  JetPack 4.4 is not yet supported)  https://github.com/microsoft/onnxruntime/blob/89359ba8623bc60ffb5c3cefb69226aadced3272/BUILD.md#jetson-tx1tx2nanoarm64-builds

**Comment by muralikrishnat29** [comment]
Thank you for the instructions. Now, I could build ONNXRuntime from source in Nano using Jetpack 4.3. When I try to run inference on a basic Tiny YOLO v2 model fine tuned using Azure Custom Learning, I face the following issue.

self.session = onnxruntime.InferenceSession(temp)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 25, in __init__
    self._load_model(providers)
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 43, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.EPFail: [ONNXRuntimeError] : 11 : EP_FAIL : TensorRT EP could not build Engine for fused node: TensorrtExecutionProvider_TRTKernel_0_0

**Comment by goloskokovic** [comment]
you can build ONNXRuntime v1.3.0 with JetPack 4.4 if you delete whole RNN folder:
/usr/local/onnxruntime/onnxruntime/core/providers/cuda/rnn
and comment lines [558](https://github.com/microsoft/onnxruntime/blob/v1.3.0/onnxruntime/core/providers/cuda/cuda_execution_provider.cc#L558)-566 and [1085](https://github.com/microsoft/onnxruntime/blob/v1.3.0/onnxruntime/core/providers/cuda/cuda_execution_provider.cc#L1085)-1093 in 
/usr/local/onnxruntime/onnxruntime/core/providers/cuda/cuda_execution_provider.cc 
for testing RNN, GRU and LSTM if you don't plan to use them

**Comment by capriccioo** [comment]
> you can build ONNXRuntime v1.3.0 with JetPack 4.4 if you delete whole RNN folder:
> /usr/local/onnxruntime/onnxruntime/core/providers/cuda/rnn
> and comment lines [558](https://github.com/microsoft/onnxruntime/blob/v1.3.0/onnxruntime/core/providers/cuda/cuda_execution_provider.cc#L558)-566 and [1085](https://github.com/microsoft/onnxruntime/blob/v1.3.0/onnxruntime/core/providers/cuda/cuda_execution_provider.cc#L1085)-1093 in
> /usr/local/onnxruntime/onnxruntime/core/providers/cuda/cuda_execution_provider.cc
> for testing RNN, GRU and LSTM if you don't plan to use them

Then I got these errors:
[ 75%] Linking CXX executable onnxruntime_perf_test
libonnxruntime_providers_cuda.a(cuda_execution_provider.cc.o):(.data.rel.ro._ZZN11onnxruntime4cudaL19RegisterCudaKernelsERNS_14KernelRegistryEE14function_table+0x900): undefined reference to `onnxruntime::KernelCreateInfo onnxruntime::cuda::BuildKernelCreateInfo<onnxruntime::cuda::kCudaExecutionProvider_RNN_kOnnxDomain_ver7_float>()'
libonnxruntime_providers_cuda.a(cuda_execution_provider.cc.o):(.data.rel.ro._ZZN11onnxruntime4cudaL19RegisterCudaKernelsERNS_14KernelRegistryEE14function_table+0x908): undefined reference to `onnxruntime::KernelCreateInfo onnxruntime::cuda::BuildKernelCreateInfo<onnxruntime::cuda::kCudaExecutionProvider_RNN_kOnnxDomain_ver7_double>()'

**Comment by jywu-msft** [comment]
instead of commenting out the RNN code,
to address the original build error,
replace 
cudnnSetRNNDescriptor
with
cudnnSetRNNDescriptor_v6

**Comment by capriccioo** [comment]
> > you can build ONNXRuntime v1.3.0 with JetPack 4.4 if you delete whole RNN folder:
> > /usr/local/onnxruntime/onnxruntime/core/providers/cuda/rnn
> > and comment lines [558](https://github.com/microsoft/onnxruntime/blob/v1.3.0/onnxruntime/core/providers/cuda/cuda_execution_provider.cc#L558)-566 and [1085](https://github.com/microsoft/onnxruntime/blob/v1.3.0/onnxruntime/core/providers/cuda/cuda_execution_provider.cc#L1085)-1093 in
> > /usr/local/onnxruntime/onnxruntime/core/providers/cuda/cuda_execution_provider.cc
> > for testing RNN, GRU and LSTM if you don't plan to use them
> 
> Then I got these errors:
> [ 75%] Linking CXX executable onnxruntime_perf_test
> libonnxruntime_providers_cuda.a(cuda_execution_provider.cc.o):(.data.rel.ro._ZZN11onnxruntime4cudaL19RegisterCudaKernelsERNS_14KernelRegistryEE14function_table+0x900): undefined reference to `onnxruntime::KernelCreateInfo onnxruntime::cuda::BuildKernelCreateInfo<onnxruntime::cuda::kCudaExecutionProvider_RNN_kOnnxDomain_ver7_float>()' libonnxruntime_providers_cuda.a(cuda_execution_provider.cc.o):(.data.rel.ro._ZZN11onnxruntime4cudaL19RegisterCudaKernelsERNS_14KernelRegistryEE14function_table+0x908): undefined reference to `onnxruntime::KernelCreateInfo onnxruntime::cuda::BuildKernelCreateInfoonnxruntime::cuda::kCudaExecutionProvider_RNN_kOnnxDomain_ver7_double()'

I commented line 593~601 and line 1120~1128, and then problems resolved.

**Comment by muralikrishnat29** [comment]
Thanks for the update guys. Since ONNXRuntime was not getting built in Jetson Nano, we were using another approach. I will try this and post the update about this issue in 2/3 days. Thanks, once again.

**Comment by muralikrishnat29** [comment]
> Thank you for the instructions. Now, I could build ONNXRuntime from source in Nano using Jetpack 4.3. When I try to run inference on a basic Tiny YOLO v2 model fine tuned using Azure Custom Learning, I face the following issue.
> 
> self.session = onnxruntime.InferenceSession(temp)
> File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 25, in **init**
> self._load_model(providers)
> File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 43, in _load_model
> self._sess.load_model(providers)
> onnxruntime.capi.onnxruntime_pybind11_state.EPFail: [ONNXRuntimeError] : 11 : EP_FAIL : TensorRT EP could not build Engine for fused node: TensorrtExecutionProvider_TRTKernel_0_0

I am getting the same error again in Jetpack 4.4 after building ONNXRuntime. So, now, the issue is that ONNX Model inference does not happen in Nano using ONNXRuntime

**Comment by goloskokovic** [comment]
Did you use [symbolic_shape_infer.py](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/nuphar/scripts/symbolic_shape_infer.py) script on Tiny YOLO v2 model before running it?
`python symbolic_shape_infer.py --input tinyyolov2-8.onnx --output new_model.onnx --auto_merge`
see: https://github.com/microsoft/onnxruntime/issues/3034#issuecomment-590467505

**Comment by muralikrishnat29** [comment]
I did not do that. I will run that and post the update. Thanks

**Comment by muralikrishnat29** [comment]
I just ran the symbolic_shape_infer.py, new model got generated. But when I run the inference on the newly generated model, again, I am facing the same issue.
