### ISSUE TITLE
How to build custom nuget package on linux

### ISSUE THREAD

**Issue by npuichigo** [microsoft/onnxruntime#3924]
I want to build a custom nuget package with cuda9.0 support on linux, but I can't pass the check_language in cmake even with dotnet core installed. Is there any ci build example for that?

**Comment by hariharans29** [comment]
We don't have linux support yet for building nugets. On windows, please use this command from cpu.yml (invoked after the build process)- 

```
msbuild $(Build.SourcesDirectory)\csharp\OnnxRuntime.CSharp.proj /p:Configuration=RelWithDebInfo /t:CreatePackage
```

**Comment by npuichigo** [comment]
what about build a OnnxRuntime.GPU nuget package?
