### ISSUE TITLE
import onnxruntime Error:cannot import name 'get_all_providers'

### ISSUE THREAD

**Issue by manofmountain** [microsoft/onnxruntime#3943]
**Describe the bug**
Manually build onnxruntime with python wheel and encounter such an issue while launching related python test at the end of the building process.

**Urgency**
M

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.3.0
- Python version: 3.6.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 5.4
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
my source build command is: ./build.sh --config Debug --build_shared_lib --parallel --build_wheel
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
when I import onnxruntime ,Error is follow: (BTW, i definitely activate python 3.6.6 before the source building. 

2020-05-15 00:32:40,450 Build [DEBUG] - Running subprocess in '/home/lshusen/onnxruntime/build/Linux/Debug'
['/home/lshusen/workspace/py36/bin/python3', 'onnxruntime_test_python.py']
/mnt/ssd/lshusen/onnxruntime/build/Linux/Debug/onnxruntime/capi/_pybind_state.py:13: UserWarning: Cannot load onnxruntime.capi. Error: 'Python version 
mismatch: module was compiled for Python 3.5, but the interpreter version is incompatible: 3.6.6 (default, Apr 18 2020, 18:55:01) 
[GCC 5.4.0 20160609].'
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'".format(str(e)))
Traceback (most recent call last):
  File "onnxruntime_test_python.py", line 8, in <module>
    import onnxruntime as onnxrt
  File "/mnt/ssd/lshusen/onnxruntime/build/Linux/Debug/onnxruntime/__init__.py", line 12, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, RunOptions, SessionOptions, set_defaul
t_logger_severity, NodeArg, ModelMetadata, GraphOptimizationLevel, ExecutionMode, OrtDevice, SessionIOBinding
ImportError: cannot import name 'get_all_providers'
Traceback (most recent call last):
  File "/home/lshusen/onnxruntime/tools/ci_build/build.py", line 1740, in <module>
    sys.exit(main())
  File "/home/lshusen/onnxruntime/tools/ci_build/build.py", line 1640, in main
    args.use_tvm, args.use_tensorrt)
  File "/home/lshusen/onnxruntime/tools/ci_build/build.py", line 1102, in run_onnxruntime_tests
    cwd=cwd, dll_path=dll_path)
  File "/home/lshusen/onnxruntime/tools/ci_build/build.py", line 391, in run_subprocess
    env=my_env, shell=shell)
  File "/home/lshusen/bin/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/lshusen/workspace/py36/bin/python3', 'onnxruntime_test_python.py']' returned non-zero exit status 1.
(py36) ➜  /home/lshusen/onnxruntime (rel-1.3.0) vim build.log

**Comment by pranavsharma** [comment]
Can you do this in a clean environment (possibly using conda)? The error seems to be pretty clear - Error: 'Python version
mismatch: module was compiled for Python 3.5, but the interpreter version is incompatible: 3.6.6.

**Comment by manofmountain** [comment]
@pranavsharma  Thank you for your quick reply, really appreciate that.. i'm using a virtualenv environment with python 3.6.6..Do we have some debug methods to check where python 3.5 involved during the building process?

**Comment by manofmountain** [comment]
It's not easy to make my whole project built with conda as it has been done on a py36 virtual env for quite a long time. Through the build log, seems cmake can find my py36 interpreter correctly.

![image](https://user-images.githubusercontent.com/2107559/82006886-65c92600-969b-11ea-93a3-a9ec4e4b6a45.png)

**Comment by pranavsharma** [comment]
I was able to repro this in my py36 venv. Running the following should resolve your issue. I tried it on my machine.

```
./build.sh --build_shared --build_wheel --parallel --cmake_extra_defines PYTHON_LIBRARIES=/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1 PYTHON_EXECUTABLE=/home/pranav/venv/bin/python3 PYTHON_INCLUDE_DIRS=/usr/include/python3.6m/
```
I've Python 3.6.10.

**Comment by jywu-msft** [comment]
> I was able to repro this in my py36 venv. I've 3.5.2 outside the venv and 3.6.10 inside.
> Running the following should resolve your issue. I tried it on my machine.
> 
> ```
> ./build.sh --build_shared --build_wheel --parallel --cmake_extra_defines PYTHON_LIBRARIES=/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1 PYTHON_EXECUTABLE=/home/pranav/venv/bin/python3 PYTHON_INCLUDE_DIRS=/usr/include/python3.6m/
> ```

is this a PATH issue? Is it finding python 3.5 before 3.6?
It's strange, if cmake detects the correct PYTHON version, we should be using the libraries/headers associated with that one. so there must be something wrong with the cmake scripts.

**Comment by pranavsharma** [comment]
> > I was able to repro this in my py36 venv. I've 3.5.2 outside the venv and 3.6.10 inside.
> > Running the following should resolve your issue. I tried it on my machine.
> > ```
> > ./build.sh --build_shared --build_wheel --parallel --cmake_extra_defines PYTHON_LIBRARIES=/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1 PYTHON_EXECUTABLE=/home/pranav/venv/bin/python3 PYTHON_INCLUDE_DIRS=/usr/include/python3.6m/
> > ```
> 
> is this a PATH issue? Is it finding python 3.5 before 3.6?
> It's strange, if cmake detects the correct PYTHON version, we should be using the libraries/headers associated with that one. so there must be something wrong with the cmake scripts.

Yes, it was using 3.5 libs even though both 3.5 and 3.6 libs are present in the same dir (/usr/lib/x86_64-linux-gnu/). I retried in a new terminal window and can't seem to repro it anymore.

**Comment by pranavsharma** [comment]
@manofmountain any more questions? Does this resolve your issue?

**Comment by pranavsharma** [comment]
plz reopen if this doesn't resolve.
