### ISSUE TITLE
Registering Custom via python interface

### ISSUE THREAD

**Issue by saurabh-shandilya** [microsoft/onnxruntime#3958]
I am running the onnxruntime-gpu in my local python environment. I would like to build my own custom op implementation for the tensorflow operators which were not successfully converted during tf2onnx conversion and were converted using --custom-ops options for layers unknown to onnx. 

I'd prefer to not rebuild the onnxruntime but just the dynamic libraries (conforming to some API) for my custom-ops and register it through a python interface in my python code, or just by placing the dlls in some location.  

I found some documentation here https://github.com/microsoft/onnxruntime/blob/master/docs/AddingCustomOp.md,

but I am not sure if I can do what want to achieve. If this has enough information for me to achieve what I want please help me see this. 

**System information**
onnx==1.6.0
onnxruntime-gpu==1.0.0

**Describe the solution you'd like**
A standalone C/C++ example project to build a custom operator dynamic library 
and 
A python API to register the dynamic custom operator library.

I register my custom op dll/so before calling InferenceSession via some python api and then simply follow regular steps for running inference session with a model containing custom ops. 

**Describe alternatives you've considered**

Use of PyOp ( but op-type is different), but I don't want to touch/edit the already converted model, also don't want to rebuild onnxruntime.

**Comment by pranavsharma** [comment]
Currently we don't have a python API to register a custom ops shared lib. We've a [C API](https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h#L371) though. There's a test in https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_inference.cc that exercises this API.

**Comment by saurabh-shandilya** [comment]
@pranavsharma Is it too much effort to add this, or is there a fundamental problem in bringing this feature to a standalone python API? This would be really interesting and helpful addition as onnx-runtime would be totally decoupled from custom ops and developers would be really empowered with quickly trying new custom ops without having to go through the cumbersome build process. 
 
Can you also point to project files for creating a stand-alone custom-op dynamic library on windows?
