### ISSUE TITLE
Expected storage order for Ort tensors

### ISSUE THREAD

**Issue by jgbradley1** [microsoft/onnxruntime#3973]
I am using the C++ API. When calling `ort::Value::CreateTensor` to wrap a data blob that is allocated and owned by another framework (OpenCV for example), what storage order does ORT expect? Row major or column major?

Is ORT implemented in a way that storage order does not even matter when passing data to `Run()`?

I cannot find any documentation that clarifies this question.

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.2.0
- Python version: 3.6

**Additional context**
I would like to pre-process images with opencv and then run inference with ORT directly without using OpenCV’s built-in support for ONNX models. This means converting a cv::Mat to an Ort Tensor. The following issue suggests that ORT expects row major order in all data blobs (opencv stores data in row major order).

https://github.com/microsoft/onnxruntime/issues/2832

I am also interested in passing matrix data structures created by the Eigen library into ORT.

**Comment by TMVector** [comment]
The protobuf definition part of the spec says [row-major](https://github.com/onnx/onnx/blob/master/onnx/onnx.in.proto#L496).


If you'd like to submit a PR to add it to the [markdown documentation](https://github.com/onnx/onnx/blob/master/docs/IR.md) I'm sure it would be gratefully received :)

**Comment by Craigacp** [comment]
The Java API supplies row major tensors and it's behaving as expected. I thought the documentation was updated somewhere after I asked about it.

**Comment by jgbradley1** [comment]
Documentation has not been added yet. Should still keep this issue open.
