### ISSUE TITLE
INVALID_GRAPH after running `optimize_model`

### ISSUE THREAD

**Issue by SantaDiver** [microsoft/onnxruntime#3977]
I'm trying to convert Pytorch BERT model to ONNX format and then optimize it. I'm using [huggingface transformers](https://huggingface.co/transformers/) library. Pytorch model could be downloaded [here](http://files.deeppavlov.ai/deeppavlov_data/bert/ru_conversational_cased_L-12_H-768_A-12_pt.tar.gz).

I exported model using `torch.onnx.export`. Then I ran this code trying to optimize my model:
```
from onnxruntime_tools import optimizer
optimized_model = optimizer.optimize_model(
    "bert.onnx",
    model_type='bert',
    num_heads=12,
    hidden_size=768
)
optimized_model.save_model_to_file("optim_bert.onnx")
```

Then after running:
```
import onnxruntime as ort
session = ort.InferenceSession("optim_bert.onnx")
```

I get:
```
InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:SkipLayerNorm1 : Unrecognized attribute: epsilon for operator SkipLayerNormalization
```

Does anyone know how to fix it?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.3 LTS
- ONNX Runtime installed from (source or binary): pypi
- ONNX Runtime version: 1.2.0
- Python version: 3.6.9
- Torch version: 1.5.0

**Comment by SantaDiver** [comment]
I just downgraded pytorch to 1.4.0 and the error gone. Probably this issue affects only newer version.

**Comment by SantaDiver** [comment]
I just downgraded Pytroch to 1.4.0 and this error is gone. Looks like this problem only affects newer version.

And now I face another strange behavior: ONNX returns all "nan" as prediction on both optimized and raw models. And this new problem appears only when I'm using CUDAExecutionProvider. With CPUExecutionProvider model returns reasonable numbers.

**Comment by faxu** [comment]
@spandantiwari can you take a look at the PyTorch issue in the newer version? Can you share the converted onnx model you see the error with?

**Comment by SantaDiver** [comment]
@faxu Here are my models: [raw](https://drive.google.com/open?id=1krber8QWZX_6VTmyhtbiM2ftkTtPYk9D), [gpu optimized](https://drive.google.com/open?id=1-605zZ38f1YgAz9Erxf_wasQNAsDSB_a)

UPD: the problem only reproduces with pytorch==1.5.0, onnxruntime==1.2.0, onnxruntime-gpu==1.2.0
Newer onnxruntime==1.3.0, onnxruntime-gpu==1.3.0 fixed it.

And about nans. I have multiple CUDA installations on my machine. Maybe ONNX Runtime uses the wrong one therefore producing nans? I have 10.1 installed in my conda environment.

**Comment by tianleiwu** [comment]
@SantaDiver, 

I noticed that your model has switched the input naming of attention_mask and token_type_ids, so token_type_ids (all zeros) are used as attention mask. Then the tensor became all zeros (since mask are all zero), that causes NaNs in softmax (Hari has a fix for this). 

You can follow our benchmkark script (https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/benchmark.py) to export bert model to ONNX.

Transformers has fixed a similar issue 3 days ago in onnx export: https://github.com/huggingface/transformers/blob/master/src/transformers/convert_graph_to_onnx.py
You can have a try as well.

The epsilon attribute of SkipLayerNormalization is added in onnxruntime 1.3.0. Note that onnxruntime-tools version is 1.3.0.*, and the optimized model might not be backward compatible with older version (1.2.0).

**Comment by SantaDiver** [comment]
@tianleiwu,

thank you for the explanation! And sorry for not answering for so long.
I'll try to convert my model in proper way and write back if I'll face problems.

**Comment by tianleiwu** [comment]
Also, the NaN issue has been addressed:
https://github.com/microsoft/onnxruntime/blob/2605faef88714b9e9d5ad0eac7f17c387db4cc1c/onnxruntime/contrib_ops/cuda/bert/attention_impl.cu#L158

Close this issue now. Feel free to reopen it if the issue exists in correctly export model.

**Comment by lintseju** [comment]
Hi @tianleiwu , I encounter the same problem, but I am using model from tf 1.x
It works fine before I do optimization, but after optimized, the program crashed with the same error message.
How can I fix this?

```
from onnx_model_bert import BertOptimizationOptions
optimization_options = BertOptimizationOptions('bert_tf')
optimization_options.enable_gelu_approximation = True
optimized_model = optimizer.optimize_model(OUTPUT_DIR + "bert.onnx", model_type='bert_tf', num_heads=12, hidden_size=768, opt_level=0,
                                           optimization_options=optimization_options,)
# optimized_model.use_dynamic_axes()
optimized_model.save_model_to_file(OUTPUT_DIR + "bert_opt.onnx")
```

```
sess = ort.InferenceSession("../onnx_models/bert_opt.onnx")
def _test_infer_onnx(sess, input_feature, _label_list):
    data = {"in_input_ids:0": np.array([input_feature.input_ids], dtype=np.int64),
          "in_input_mask:0": np.array([input_feature.input_mask], dtype=np.int64),
          "in_segment_ids:0": np.array([input_feature.segment_ids], dtype=np.int64)}
    ts0 = timeit.default_timer()
    result = sess.run(["loss/ArgMax:0", "loss/Max:0"], data)
    ts1 = timeit.default_timer()
    return _label_list[result[0][0]], result[1][0], ts1 - ts0
pred_onnx, pred_proba_onnx, time_onnx = _test_infer_onnx(sess, input_feature, _label_list)
```

Error log:
```
Traceback (most recent call last):
  File "serving.py", line 137, in <module>
    main()
  File "serving.py", line 133, in main
    sess.run(["loss/ArgMax:0", "loss/Max:0"], feed)
  File "/Users/xxx/anaconda3/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 111, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running SkipLayerNormalization node. Name:'SkipLayerNorm1' Status Message: skip is expected to have same shape as input
```

system info:
Generate ONNX model:
Google colab
ONNX Runtime installed from (source or binary): pypi
onnx==1.7.0
onnxruntime==1.3.0
tensorflow==1.15.2
tf2onnx==1.6.2
Python 3.6.9

Inference:
onnx==1.7.0
onnxruntime==1.3.0
tensorflow==1.15.2
Python 3.7.6
