### ISSUE TITLE
Precompiled zip-binaries  1.3

### ISSUE THREAD

**Issue by Armin234** [microsoft/onnxruntime#3984]
Hi,
I'm looking for the precompiled binaries in a ZIp-package, but i didn't found them. 
For older versions there was the possibility to download the Zip-packages.

**Comment by prabhat00155** [comment]
Is this what you are looking for: https://github.com/microsoft/onnxruntime/releases/tag/v1.3.0 (under assets)?

**Comment by Armin234** [comment]
Yes, thanks :-)
