### ISSUE TITLE
Yolov3 quantization model is slower？

### ISSUE THREAD

**Issue by cuixing158** [microsoft/onnxruntime#3987]
**Describe the bug**
When I quantify the [yolov3.onnx](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3) model in onnx model zoo, the speed is slower? yolov3.onnx take 0.4s , yolov3_quantized_model.onnx take 0.48s ??? my quantize model is [here](https://drive.google.com/file/d/18dygHqmmcdUU_vy3-0yxNjejYqIWtY4B/view?usp=sharing).

**Urgency**
none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win 10
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.2
- Python version: 3.7
- Visual Studio version (if applicable): none
- GCC/Compiler version (if compiling from source): none
- CUDA/cuDNN version: 10.1
- GPU model and memory: GTX1060,3GB

**To Reproduce**
```python
# 1. Make session
    session = onnxruntime.InferenceSession('yolov3_quantized_model.onnx') # onnx model zoo下载的yolov3.onnx只适合下面的推理

    # %% 换成用opencv摄像头采集图像，测试在线onnxruntime-cpu速度
    cap = cv2.VideoCapture(0)
    while True:
        isread,img = cap.read()
        tensor_img = mat2tensor(img).unsqueeze(0).numpy() # 1*3*416*416 ,[0,1] range，RGB order
        
        image_size = img.shape[0:2]
        image_size = np.array(image_size).reshape(1,2)
     
          # 2. Get input/output name
        input_name = session.get_inputs()[0].name           # 'image'
        input_name_img_shape = session.get_inputs()[1].name # 'image_shape'
    
        output_name_boxes = session.get_outputs()[0].name   # 'boxes'
        output_name_scores = session.get_outputs()[1].name  # 'scores'
        output_name_indices = session.get_outputs()[2].name # 'indices'
    
        # 3. run
        t1 = time.time()
        outputs_index = session.run([output_name_boxes, output_name_scores, output_name_indices],
                                    {input_name: tensor_img, input_name_img_shape: image_size})
        t2 = time.time()
        print("take time:{:.2f}s".format(t2-t1)) # yolov3.onnx take 0.4s , yolov3_quantized_model.onnx take 0.48s ???
        ...
```

**Expected behavior**
yolov3_quantized_model.onnx should take less than 0.4 second. That is, yolov3_quantized_model.onnx takes less time than yolov3.onnx

**Screenshots**
None

**Additional context**
I refer to [the code](https://github.com/microsoft/onnxruntime/tree/v1.0.0/onnxruntime/python/tools/quantization#quantize-an-onnx-model) here for quantification.  My conversion code is as follows：
```python
import onnx
from quantize import quantize, QuantizationMode

# Load the onnx model
model = onnx.load('yolov3.onnx')
# Quantize
quantized_model = quantize(model, quantization_mode=QuantizationMode.IntegerOps)
# Save the quantized model
onnx.save(quantized_model, 'yolov3_quantized_model.onnx')
```

**Comment by yufenglee** [comment]
@cuixing158, the performance of quantized model is device/hardware and model dependent. We are working on improving the performance of quantized yolo models.
