### ISSUE TITLE
TensorRT Execution Provider - Issue with Tinny yolo v2 and v3 models

### ISSUE THREAD

**Issue by danielecazzari** [microsoft/onnxruntime#3991]
**Describe the bug**
I build OnnxRuntime (version 1.1.2 since it's the last supported by current Jetpack 4.3) on Jetson TX2 with TensorRT Execution Provider. But I'm having issues with running tiny YOLO models from https://github.com/onnx/models.
I'm able to run the tiny-YoloV2 model but with very low performances (no more than 3 FPS). 
With tiny-YoloV3 I got an error "Unsupported ONNX data type: BOOL (9)". See below for the full log.

Note the same models score well on OpenVino Execution Provider on my i7 laptop (CPU_FP32 current master branch). Moreover, I'm able to score the same tiny-YoloV2 model with a different runtime on TX2 with much better performances (more than 15 FPS).

Should I move to Jetpack 4.4 to make those models work?

Thanks a lot

Daniele

**Full Log**
Unsupported ONNX data type: BOOL (9)
Unsupported ONNX data type: BOOL (9)
Unsupported ONNX data type: BOOL (9)
Unsupported ONNX data type: BOOL (9)
2020-05-19 14:29:39.461912016 [E:onnxruntime:, inference_session.cc:847 Initialize] Exception during initialization: /media/sas/SD64/onnx/onnxruntime/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc:308 SubGraphCollection_t onnxruntime::TensorrtExecutionProvider::GetSupportedList(SubGraphCollection_t, int, int, const onnxruntime::GraphViewer&, bool*) const graph_build.Resolve().IsOK() was false.
Stacktrace:

Traceback (most recent call last):
  File "SAS_YoloV3_MSRuntime_OpenVINO_Demo.py", line 593, in <module>
    main_camera()
  File "SAS_YoloV3_MSRuntime_OpenVINO_Demo.py", line 497, in main_camera
    sess = rt.InferenceSession(param['onnx_model_path'])
  File "/home/sas/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 25, in __init__
    self._load_model(providers)
  File "/home/sas/.local/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 43, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /media/sas/SD64/onnx/onnxruntime/onnxruntime/core/providers/tensorrt/tensorrt_execution_provider.cc:308 SubGraphCollection_t onnxruntime::TensorrtExecutionProvider::GetSupportedList(SubGraphCollection_t, int, int, const onnxruntime::GraphViewer&, bool*) const graph_build.Resolve().IsOK() was false.
Stacktrace:

**Comment by jywu-msft** [comment]
Yes, unfortunately JetPack skipped TensorRT 7.0 support which is the latest version OnnxRuntime supports.
JetPack 4.4 is currently preview release. Final Release version won't be until next month.
It uses TensorRT 7.1 which OnnxRuntime does not yet support. We are working on it.

**Comment by goloskokovic** [comment]
@danielecazzari I was able to build OnnxRuntime 1.3.0 with JetPack 4.4
https://github.com/microsoft/onnxruntime/issues/3913#issuecomment-639740698

**Comment by danielecazzari** [comment]
Thanks to @goloskokovic @ jywu-msft suggestions I was able to build OnnxRuntime on Nano with JetPack 4.4. But I'm not able to score neither

**Comment by manashgoswami** [comment]
can you try with updated [ONNX Runtime v1.4 for Jetpack 4.4](https://elinux.org/Jetson_Zoo#ONNX_Runtime)?

**Comment by jywu-msft** [comment]
couple comments.
the 1.4 gpu package that @manashgoswami referred to https://nvidia.box.com/shared/static/8sc6j25orjcpl6vhq3a4ir8v219fglng.whl
is for CUDA EP (Not TensorRT EP). Did you try that package? Both models should run under CUDA EP. 

Re: TensorRT EP,
We recently made some more improvements to TensorRT EP, so another option is to build the latest code from master for use with JetPack 4.4

**Comment by danielecazzari** [comment]
@ jywu-msft my custom build didn't work for CUDA (need to check why) but only for TensorRT. With the suggested package I was able to score all models without issue. 
Next week I will try to compile and test the master to check TensorRT improvements.

Thanks

Daniele
