### ISSUE TITLE
Python has stopped working message pops up when using onnxruntime-gpu

### ISSUE THREAD

**Issue by dasguptar** [microsoft/onnxruntime#3994]
**Describe the bug**
Trying to run inference on a saved ONNX model via onnxruntime-gpu raises a `Python has stopped working` windows, and the program just crashes.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows Server 2016 Datacenter
- ONNX Runtime installed from (source or binary): binary (pip)
- ONNX Runtime version: onnxruntime-gpu==1.2.0
- Python version: 3.6
- Visual Studio version (if applicable): 2019 Community
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1 / 7.6.5
- GPU model and memory: V100

**To Reproduce**
- Load a ONNX model in an InferenceSession, and try to run something like `outputs = session.run(None, batch)` causes the error. Works fine if using `onnxruntime` instead of `onnxruntime-gpu`

**Expected behavior**
The program should not be crashing.

**Screenshots**
![image](https://user-images.githubusercontent.com/1309728/82365987-1a15d400-9a2f-11ea-8a51-75a75904a60e.png)

**Comment by skottmckay** [comment]
I don't see any onnxruntime output in that screenshot. Are you able to share some python and a model that reproduces the issue?

If you have VS2019 installed could you try 'Debug' and see if there's a callstack to provide some more info on where exactly it failed?
