### ISSUE TITLE
orttraining: Is there or will there be a C API? (for C# etc.)

### ISSUE THREAD

**Issue by nietras** [microsoft/onnxruntime#4002]
Couldn't find this, but hoping there will be a C API for using ORT training?

**Comment by pranav-prakash** [comment]
As an additional point, a question I asked [previously](https://github.com/microsoft/onnxruntime/issues/3706) seems to indicate that currently the only C++ API in terms of training is taking an existing inference onnx model and augmenting it for training:

>If you already have an ONNX model. there is an example too (which also uses ORTTrainer). However in this case the ONNX model needs to output loss as well). Please be noted that this approach is only used for testing purpose for now. We will see if there are strong need to really support this use case.

While I'm not sure what OP's use case is, we would like to perform training on embedded/edge devices where we cannot use Python. For this purpose, it would be nice if there was a way to serialize a training model from PyTorch and load this into ORT training.

**Comment by KevinHake** [comment]
I'm using the C API now. The C++ API is based on it.
https://github.com/microsoft/onnxruntime/blob/master/docs/C_API.md

**Comment by nietras** [comment]
C API for `orttraining` not inference.

**Comment by nietras** [comment]
Please reopen as this is still relevant.

**Comment by pranav-prakash** [comment]
@liqunfu Is there any update on whether the C API for `orttraining` will be developed further in the future? Most of the recent effort seems to have gone into the python based pytorch integration, but this is unsuitable for constrained/embedded platforms where we want to do training at the edge.

**Comment by ashbhandare** [comment]
Hi @nietras, we are working on adding support for on-device training and will be adding C APIs as a part of this work

**Comment by nietras** [comment]
@ashbhandare that sounds great we are very interested in this (in particular from C#/.NET side), please feel free to mention me in related issues/discussions/PRs.

**Comment by baijumeswani** [comment]
HI @nietras. We have added C/C++/C# apis for on device training. You can find the C apis [here](https://github.com/microsoft/onnxruntime/blob/86c5c07ea419b935541d0abd2a16bf204e19c6ed/orttraining/orttraining/training_api/include/onnxruntime_training_c_api.h).

Closing this issue now. Please feel free to reach out with any questions about the api or its usage.
