### ISSUE TITLE
python and C++ libs use OpenVino? 

### ISSUE THREAD

**Issue by Liujingxiu23** [microsoft/onnxruntime#4005]
I am a newer and really confused about Openvino, both in python and C++.

1.What is the relationship of Openvino and onnxruntime.
onnxruntime with Openvino is faster?

2.python:
When Use onnxruntime in python (through pip install onnxruntime),  when run get_privider there is only CPUExecutionProvider， no "OpenVINOExecutionProvider" aviable. 
In the discussion in issue https://github.com/microsoft/onnxruntime/issues/2298, someone say onnxruntime have to be build from source code to support OpenVINOExecutionProvider. But I do not konw why? Is there any solution? Why OpenVino is not supported as default.  And I do not have sudo authority to install openvino. How can I installed in  my own path?

3.C++
I downloaded onnxruntime-linux-x64-1.3.0.tgz from this place
https://github.com/Microsoft/onnxruntime/releases/tag/v1.3.0. 

Then take https://github.com/Microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp as an example, I tested my own model.  Everything seems ok.

But I wonder wether the openvino is used?  I want to clearify the speed with and without openvino.

In "onnxruntime_c_api.h"  , there seems only two prividers:
OrtSessionOptionsAppendExecutionProvider_CPU
OrtSessionOptionsAppendExecutionProvider_CUDA OrtSessionOptionsAppendExecutionProvider_<remaining providers...>

But in "https://github.com/Microsoft/onnxruntime/releases/tag/v1.3.0", it seems OpenVINO v2.0 EP is included?

**Comment by faxu** [comment]
1. OpenVINO is an execution provider (aka accelerator) that works with ONNX Runtime. See:
* [Inference High Level Design](https://github.com/microsoft/onnxruntime/blob/master/docs/InferenceHighLevelDesign.md#high-level-system-architecture) Whether it's faster or can fully support your model depends on the specific model and the hardware target. 
* [OpenVINO EP](https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/OpenVINO-ExecutionProvider.md)

2. We currently do not publish an official package with OpenVINO nor do we directly distribute the OpenVINO Toolkit. See build instructions [here](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#openvino) or [the dockerfile](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.openvino)

3. OpenVINO will not used without having a build that supports it. Once you have that, see: [using the execution provider](https://github.com/microsoft/onnxruntime/blob/master/docs/AddingExecutionProvider.md#using-the-execution-provider)

**Comment by Liujingxiu23** [comment]
@faxu Thank you very much for your reply, I know better about how onnxruntime works and what is the EP.

**Comment by Liujingxiu23** [comment]
@faxu I compiled openvino and then tried to build onnxruntime from the code, using the following command:
./build.sh --config RelWithDebInfo --use_openvino VAD-M_FP16 --build_wheel --update --build
everything seems good util the following error:
make[2]: *** No rule to make target '/opt/conda/lib/libpython3.7m.so', needed by 'onnxruntime_test_all'.  Stop.

"'/opt/conda/lib/" is not my python path, my path is "/home/***/software/anaconda3/lib/libpython3.7m.so".

I tried "export LD_LIBRARY_PATH=/home/oppoer/work/liangmin/software/anaconda3/lib/:$LD_LIBRARY_PATH", but it didnot work
How can I change to the right python path?

**Comment by Liujingxiu23** [comment]
@faxu I compiled openvino and onnxruntime from source code. onnxruntime was build with  --use_openvino. Build done successfully and *.so generated.
(when I run command "grep -r "CreateExecutionProviderFactory_OpenVINO" *"in the my libdir, shows: 
Binary file libonnxruntime.so matches
Binary file libonnxruntime.so.1.3.0 matches) 

Then I tested my model using two versions of onnxruntime on cpu(Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz) 
1. onnxruntime-linux-x64-1.3.0.tgz downloaded
2. onnxruntime compiled from source code with openvino.

My model structure is 3 * LSTM(units=768)+Linear, SetIntraOpNumThreads and SetInterOpNumThreads are both called with parameter=1. Input =(10,160,40). 
The speed is both around 370~400ms.

I have some questions:
1. Since the onnxruntime has the capability to select execure providers with higher efficiency , so EP 
   is not needed to specified by code. Is this rigth?
2. Do you think the speed is ok/normal? 
3. For my own model, to speed up in cpu, do you have any suggestion to speed up?

**Comment by Liujingxiu23** [comment]
@faxu Another question, I tried another model with convs, deconv, norm. using C++ code. 

Fatal error: ATen is not a registered function/op.

This not my fault, this will solved in future version?
