### ISSUE TITLE
Java native loader failing on Mac OSX

### ISSUE THREAD

**Issue by mina-asham** [microsoft/onnxruntime#4006]
**Describe the bug**
The ONNXRuntime class fails to load native libraries on Mac OSX

**Urgency**
This makes the library unusable for release 1.3.0 on Mac OSX

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OSX Mojave 10.14.6
- ONNX Runtime installed from (source or binary): 1.3.0
- ONNX Runtime version: 1.3.0

**To Reproduce**
Build the code on Mac OSX, try to use the library to just do `OrtEnvironment.getEnvironment()` and it will fail

**Expected behavior**
For it to work?

**Additional context**
Pretty sure this was introduced in this change: https://github.com/microsoft/onnxruntime/commit/18dc0ec39f867985b15ebe89b8e5f0ced90c4be0

Specifically:
```java
 String arch = System.getProperty("os.arch", "generic").toLowerCase(Locale.ENGLISH);
if (arch.indexOf("amd64") == 0) {
    detectedArch = "x64";
} else if (arch.indexOf("x86") == 0) {
    detectedArch = "x86";
} else {
    throw new IllegalStateException("Unsupported arch:" + arch);
}
```

`os.arch` is set to `x86_64`, so it will build the native libraries under a different directory and then tries to check the `x86` directory which is wrong.

Happy to submit a patch if I am not missing something specific?

**Comment by Craigacp** [comment]
There's a PR to fix that - https://github.com/microsoft/onnxruntime/pull/3985. Not sure how it got past the CI in the first place, but hopefully it'll be merged soon, and it'll be in the point release that adds the maven jars.

**Comment by mina-asham** [comment]
@Craigacp Thanks, I looked into the other issues before I opened this one but forgot to also scan the pull requests! Closing this one.
