### ISSUE TITLE
ONNX runtime nuget package built in release mode

### ISSUE THREAD

**Issue by eloisethuey** [microsoft/onnxruntime#4007]
I've noticed that when building from source with --config Release, I get faster inference in C# than when using the nuget package. 

I can see that --config RelWithDebInfo is used in the nuget pipeline (https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/azure-pipelines/templates/windowsai-nuget-build.yml)

Is there a reason for this, and if not would it be possible to have the nuget build in release?

**Comment by snnn** [comment]
You're right.

**Comment by pranavsharma** [comment]
Other than generating the pdbs, the only [difference](https://www.brianlheim.com/2018/04/09/cmake-cheat-sheet.html#build-types) between Release and RelWithDebInfo is the the /Ob switch. RelWithDebInfo uses /Ob1 while Release uses /Ob2. /Ob1 is less aggressive about inlining; this reduces binary size at the (potential) expense of some speed. Can you quantify the difference in performance?

**Comment by eloisethuey** [comment]
For smaller networks the difference is quite noticeable. For example, in a feed forward network with around 20,000 parameters, I found (using BenchmarkDotNet*) that each evaluation (for a single row) is about 2.5 times slower with the Nuget package. With another model, that has about 1 million parameters, it's not so noticeable.

*Note also that BenchmarkDotNet gives the following warning when using the Nuget package: 
Assembly Evaluators which defines benchmarks references non-optimized Microsoft.ML.OnnxRuntime
        If you own this dependency, please, build it in RELEASE.
        If you don't, you can disable this policy by using 'config.With(ConfigOptions.DisableOptimizationsValidator)'.
