### ISSUE TITLE
Reduce libraries disk footprint on mobile device

### ISSUE THREAD

**Issue by ThomasRetornaz** [microsoft/onnxruntime#4023]
Hi, first off all thank you for this awesome library !
we are very impress of the inference speed of the lib both on desktop and device.

**Describe the bug**
Unfortunately, In mobile case,  ort libraries sizes are a **no go for any industrial deployment** (that's why i don't put this demand as a feature request)
In fact Ort library footprint is near 300 Mo for android case
Of course we can't use linker to reduce the size because the linker couldn't know the symbols it should keep, it will depend on the DNN models.

**Urgency**
We benchmark many different DNN inference library (torch,MNN,TensorFlow,etc...)  and we are happy with ort both on desktop and device
This bug/feature request prevent (on your sides) the choice of ort as a new inner DNN engine in addition of our legacy one
So its important but not critical for the moment

**System information**
- OS Platform and Distribution Debian stretch,we are migrating to debian buster
- ONNX Runtime installed from source
- ONNX Runtime version: 1.2
- Python version: (Not relevant)
- Visual Studio version (if applicable): Visual Studio 15 2017
- GCC/Compiler version (if compiling from source):g++ 6.3.0
- CUDA/cuDNN version:(Not relevant)
- GPU model and memory:(Not relevant)

**To Reproduce**
- follow linux steps of https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#Android

**Expected behavior**
At least an option for building only inference part 
some bonus will be a  prunning tool which regarding the descriptions of NN models (if we don't use CNN no need to build or link this part) prune the library (Similar to pytorch mecanism maybee).

**Screenshots**
Not applicable

**Additional context**

**Comment by snnn** [comment]
@gwang Could you please take a look at this issue? It shouldn't be so large.

**Comment by faxu** [comment]
Thanks for the feedback @ThomasRetornaz. We're working on better mobile support. CC @gwang-msft, @manashgoswami

**Comment by gwang-msft** [comment]
This should be fixed after this PR (https://github.com/microsoft/onnxruntime/pull/3980) for Release and MinSizeRel flavor, the Debug and RelWithDebInfo will still have large footprint.

**Comment by gwang-msft** [comment]
Please close this issue if it is resolved.

**Comment by snnn** [comment]
So it simple because the symbols were not stripped?

**Comment by ThomasRetornaz** [comment]
Its also surprise me. Going from 300mo to let say 10/30mo (size suitable on mobile) just by stripping symbols?
Now i ask my self, i could have finding this ....Anyway if its work :) 
In which release this PR will belong ?
I will try on my side asap
Thanks
Regards
TR

**Comment by gwang-msft** [comment]
Yes, by stripping the symbols will reduce the shared lib size from 300mb+ to less than 10mb.
This PR should be part of V1.4.

**Comment by snnn** [comment]
@gwang-msft Did you enable LTO? It also can reduce binary size about 30%.

**Comment by ThomasRetornaz** [comment]
Sounds great, i will check this on Monday.
Thank you all

**Comment by gwang-msft** [comment]
Android Cross-build LTO will need some tweak, did some experiment before, the size reduction is not significant (<5% using Apple clang)

**Comment by ThomasRetornaz** [comment]
Work like a charm
