### ISSUE TITLE
Convert Python build script to CMake

### ISSUE THREAD

**Issue by jgbradley1** [microsoft/onnxruntime#4027]
**Description**
Perhaps it was a design choice, but why does ORT use a python build script instead of a more formal build system setup like CMake? After reading the [build script](https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/build.py), it seems that most (or all) of the installation logic could be ported over to CMake and would resolve a lot of future integration issues.

**System information**
- ONNX Runtime version (you are using): Github master branch

**Describe the solution you'd like**
A CMake build script that replaces the python script and allows for first-time parallel builds.

**Additional context**
Building ORT the first time is limited to a single process because the parallel logic is not implemented in the python script correctly. A CMake build script would greatly improve the usability and dev experience of ORT in the long-term. It would also allow better integration of ORT into other projects ([related issue](https://github.com/microsoft/onnxruntime/issues/3124)) and CI workflows.

**Comment by snnn** [comment]
The python build script is optional. As a dev in the onnxruntime team, I rarely use it. It is totally fine to do everything without it. The python build script is just thin wrapper around cmake. The core part is the cmake. Onnxruntime's build system is built on CMake.  And CMake is just another layer on top of msbuild/make. 

CMake is good but I don't want to make overuse of it.  For example, bash script has its own value,  cmake isn't a better upgrade/replacement for it.

**Comment by jgbradley1** [comment]
I'll describe my situation for better context. I'm working with a team on a C++ project and we'd like to use onnxruntime. We use cmake to build everything (including dependencies) from source. Since onnxruntime does not have a top-level `CMakeList.txt` (relevant issue [here](https://github.com/microsoft/onnxruntime/issues/3124)), I'm trying to figure out what the best path forward is to integrate onnxruntime into the project.

Currently, we have cmake clone the repo and call the python build script. It's not the cleanest solution, but it works. The [build instructions](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md) recommend using the build.sh script which calls the python script.

If you're not using the python script, can you elaborate on your build workflow? Once third-party dependencies are installed, what cmake script are you calling to build the onnxruntime repo?

**Comment by snnn** [comment]
> If you're not using the python script, can you elaborate on your build workflow? 

e.g.
```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug ../cmake
make
make install
```

**Comment by jgbradley1** [comment]
Closing this issue for now. The comments by @snnn helped a lot. Thanks!

**Comment by pfeatherstone** [comment]
@snnn Is there a complete list of all the cmake options, similar to the `build.sh` options? Like, what are all the options for the different providers like CUDA, TENSORRT, etc...

**Comment by pfeatherstone** [comment]
It would be great if onnxruntime could be built as a dependency using [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html)

**Comment by pfeatherstone** [comment]
> > If you're not using the python script, can you elaborate on your build workflow?
> 
> e.g.
> 
> ```
> mkdir build
> cd build
> cmake -DCMAKE_BUILD_TYPE=Debug ../cmake
> make
> make install
> ```

When you do that you only get the following libraries installed in `CMAKE_INSTALL_PREFIX/lib`
* libonnxruntime_providers_cuda.so
* libonnxruntime_providers_shared.so

**Comment by snnn** [comment]
> It would be great if onnxruntime could be built as a dependency using [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html)

Agree. Welcome to contribute!

**Comment by snnn** [comment]
> @snnn Is there a complete list of all the cmake options, similar to the `build.sh` options? Like, what are all the options for the different providers like CUDA, TENSORRT, etc...

The top of our CMakeLists.txt has most of them.  I don't have a complete list.  Anything that is missing, should be added there. 
Welcome to contribute!
