### ISSUE TITLE
when I install onnxruntime in a virtual  windows system, there is always a "import error"   

### ISSUE THREAD

**Issue by lightfate** [microsoft/onnxruntime#4028]
![webwxgetmsgimg](https://user-images.githubusercontent.com/41222646/82856793-9cc3f500-9f41-11ea-967b-788a8794d00a.jpeg)
**Describe the bug**
when I install onnxruntime in a virtual  windows system, there is always a "import error" .
I have tried many windows system（win10/winserver2012/win server2016）、python version（3.6/3.8）、onnxruntime(1.2.0/1.3.0)、 virsual system(VM virtualBox/VM ware), but when i install it in the virsual system, this problem always appeared, But in Physical Machine ，There is no such problem.

C:\Users\zzx>pip list
Package           Version
----------------- -------
-nnxruntime       1.2.0
numpy             1.18.4
onnx              1.7.0
onnxruntime       1.3.0
pip               19.2.3
protobuf          3.11.3
setuptools        41.2.0
six               1.14.0
typing-extensions 3.7.4.2
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\zzx>python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime
C:\Program Files\Python38\lib\site-packages\onnxruntime\capi\_pybind_state.py:13: UserWarning: Cannot load onnxruntime.capi. Error: 'DLL load failed while importing onnxruntime_pybind11_state: 找不到指定的模块。'
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'".format(str(e)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python38\lib\site-packages\onnxruntime\__init__.py", line 12, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, RunOptions, SessionOptions, set_default_logger_severity, NodeArg, ModelMetadata, GraphOptimizationLevel, ExecutionMode, OrtDevice, SessionIOBinding
ImportError: cannot import name 'get_all_providers' from 'onnxruntime.capi._pybind_state' (C:\Program Files\Python38\lib\site-packages\onnxruntime\capi\_pybind_state.py)

**Urgency**
High, our project is based on onnxruntime, and now it cannot run in virsual windows system

**System information**
- Win10/Win server2012/Win Server2016 (virsual System, use VM virtualBox or VM ware):
- pip insatll onnxruntime:
- onnxruntime 1.3.0:
- python 3.8.2
- use cpu:

**To Reproduce**
when I install onnxruntime in a virtual  windows system(use VM virtualBox or VM ware), there is always a "import error" . But in Physical Machine ，There is no such problem.

**Expected behavior**
no import error

**Screenshots**
![webwxgetmsgimg](https://user-images.githubusercontent.com/41222646/82856813-a8afb700-9f41-11ea-89ad-91f4e5cfb7ad.jpeg)

**Comment by snnn** [comment]
Did you install vs 2019 runtime?

https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by lightfate** [comment]
> Did you install vs 2019 runtime?
> 
> https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads


thanks~
