### ISSUE TITLE
Initializer appears in graph inputs and will not be treated as constant value/weight.

### ISSUE THREAD

**Issue by zr526799544** [microsoft/onnxruntime#4033]
**Describe the bug**
I use pytorch 1.3 onnx 1.6 to export an onnx model with onnx optimizer to optimize passes = ["extract_constant_to_initializer", "eliminate_unused_initializer"]. and run it on onnxruntime 1.1.2 python 3.6.9 with no warnning.but got bunch of warning in c++ with onnxruntime 1.1.2
just like:
Initializer backbone.bn1.bias appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python/remove_initializer_from_input.py.

Initializer 997 appears in graph inputs and will not be treated as constant value/weight. This may fail some of the graph optimizations, like const folding. Move it out of graph inputs if there is no need to override it, by either re-generating the model with latest exporter/converter or with the tool onnxruntime/tools/python

**System information**
- Linux Ubuntu 16.04:
- ONNX Runtime installed from source:
- ONNX Runtime version:1.1.2 cpu

**To Reproduce**
- onnx model url : https://pan.baidu.com/s/1ry3SpsyPNQsO3BVlF6szXw 提取码：czzc

**Expected behavior**

**Screenshots**
If applicable, add screensho
![onnx1](https://user-images.githubusercontent.com/37580152/82887719-fa286800-9f7a-11ea-830a-06029545052f.PNG)
![onnx2](https://user-images.githubusercontent.com/37580152/82887724-fbf22b80-9f7a-11ea-846f-f741185e8dea.PNG)

**Comment by zr526799544** [comment]
follow the hint I use onnxruntime/tools/python/remove_initializer_from_input.py fix it.

**Comment by ShiqiLi047** [comment]
Could u introduce how to use this tools in code to fix this issues? Thanks.

**Comment by zr526799544** [comment]
> Could u introduce how to use this tools in code to fix this issues? Thanks.

just load your model and  use the  remove_initializer_from_input func to remove initializer can fix it.

**Comment by shartoo** [comment]
use code below

```
def remove_initializer_from_input(onnx_path,save_new_path):
    """
        @param onnx_path:           exported onnx model path by pytroch
        @param save_new_path:       clean onnx model path after remove input initialzer
    """
    model = onnx.load(onnx_path)
    if model.ir_version < 4:
        print("Model with ir_version below 4 requires to include initilizer in graph input")
        return
    inputs = model.graph.input
    name_to_input = {}
    for input in inputs:
        name_to_input[input.name] = input
    for initializer in model.graph.initializer:
        if initializer.name in name_to_input:
            inputs.remove(name_to_input[initializer.name])
    onnx.save(model, save_new_path)
```
