### ISSUE TITLE
ONNX RNN op activations attribute not supported.

### ISSUE THREAD

**Issue by arogowie-intel** [microsoft/onnxruntime#4034]
Hi, when I tried to compute output of ONNX model with `RNN` operator it turned out that it always uses `Tanh` activation function, no matter what I pass in `activations` attribute. 

**System information**
- Linux Ubuntu 18.04  4.4.0-165-generic 
- ONNX Runtime installed from PyPI binary 
- ONNX Runtime version: onnxruntime==1.3.0
- Python version: Python 3.6.7
- GCC/Compiler version:  [GCC 8.2.0]

**To Reproduce**
I attach model in `.onnx` and `.prototxt` version as well as python script to run.
[rnn_activations.zip](https://github.com/microsoft/onnxruntime/files/4682072/rnn_activations.zip)
```python


import numpy as np
import onnxruntime as rt
import onnx

seq_length = 4
batch_size = 3
input_size = 2
hiden_size = 5
gates_cnt  = 1
n_direction = 1
np.random.seed(133391)

X = np.random.randn(seq_length, batch_size, input_size).astype(np.float32)
W = np.random.randn(n_direction, gates_cnt * hiden_size, input_size).astype(np.float32)
R = np.random.randn(n_direction, gates_cnt * hiden_size, hiden_size).astype(np.float32)

print('\nX: \n{}'.format(X))
print('\nW: \n{}'.format(W))
print('\nR: \n{}'.format(R))

input_data = [
    X,
    W,
    R,
]

models = [
    'rnn_fwd_activations.onnx',
]

for m in models:
    print('Inference for model: {}'.format(m))
    onnx_model = onnx.load_model(m)
    onnx.checker.check_model(onnx_model)

    sess = rt.InferenceSession(m)
    inputs = sess.get_inputs()

    inputs_name = [n.name for n in sess.get_inputs()]
    outputs_name = [n.name for n in sess.get_outputs()]

    pred_onx = sess.run(outputs_name,
                        dict(zip(inputs_name, input_data)))

    for p in pred_onx:
        print(p)
```

**Expected behavior**
RNN operator use activation function passed in `activations` attribute.

**Comment by hariharans29** [comment]
The activation function found in the node is invalid (literally :)). This should probably have been caught at model load time but there was a minor bug in the validation which meant it went past that stage and then it fell back to using the default activation - Tanh. I ll fix the validation step.

![image](https://user-images.githubusercontent.com/9969784/83059731-3a392a80-a00f-11ea-9247-37aff80ff3c8.png)

**Comment by arogowie-intel** [comment]
@hariharans29 Thanks for your response. The activation function was intentionally invalid in this model. One could pass anything inside and that seemed to be not validated at all. If I pass correct activation function like `sigmoid` then, despite this the `tanh` is used.

**Comment by hariharans29** [comment]
Can you check the casing of the activation provided ? This is the list of all supported activation in ORT for RNN - https://github.com/microsoft/onnxruntime/blob/b3ec8035eef4735cd919d11f5f970ca8a1fcd87b/onnxruntime/core/providers/cpu/rnn/rnn.h#L15 and this matches the ONN X spec - https://github.com/onnx/onnx/blob/master/docs/Operators.md#rnn. 

If you can, you could try buiding with the referenced PR - this should atleast fail at model load time if it finds that the activation is not one of the allowed ones.

**Comment by hariharans29** [comment]
Please try "Sigmoid" instead of "sigmoid". Looks like the current implementation is case sensitive when it maps provided activations to the underlying implementation. Previously, it would have just gone ahead without validating and used the default - Tanh. With the change in the PR, it will fail if you were to provide "sigmoid". Looks like the ONNX spec doesn't explictly state that the provided activations *need* to be case-sensitive but it is just ORT's implementation choice. 

There are some tests covering the non-default activation (for example, https://github.com/microsoft/onnxruntime/blob/da653ccdac344372052025d95cc84e93237f6f84/onnxruntime/test/providers/cpu/rnn/rnn_op_test.cc#L752).
