### ISSUE TITLE
Not able to install onnxruntime_gpu on windows server 2019

### ISSUE THREAD

**Issue by oujiafan** [microsoft/onnxruntime#4035]
**Describe the bug**
I'm not able to install onnxruntime_gpu on windows server 2019

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows server 2019
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:
- Python version: 3.8.3
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
>pip install onnxruntime_gpu-1.3.0-cp38-cp38-manylinux2010_x86_64.whl
ERROR: onnxruntime_gpu-1.3.0-cp38-cp38-manylinux2010_x86_64.whl is not a supported wheel on this platform.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by snnn** [comment]
Please tell us your pip version

pip --version

**Comment by snnn** [comment]
Is your python 32bits or 64bits?

**Comment by oujiafan** [comment]
You're right. Somehow I got 32-bit python... Let me try 64-bit one.

**Comment by oujiafan** [comment]
64-bit python got me the error.
> pip3 install onnxruntime-gpu
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu

> pip install onnxruntime_gpu-1.3.0-cp38-cp38-manylinux2010_x86_64.whl
ERROR: onnxruntime_gpu-1.3.0-cp38-cp38-manylinux2010_x86_64.whl is not a supported wheel on this platform.

**Comment by snnn** [comment]
manylinux2010 is for Linux. You need a Windows one.  But, unfortunately, I'm really sorry, we don't have a Windows GPU package for python 3.8 yet. Could you please downgrade your python to 3.7?

**Comment by oujiafan** [comment]
Python 3.7 works!

**Comment by snnn** [comment]
#5697
