### ISSUE TITLE
Error in c_cxx samples: error: ‘OrtGetApi’ was not declared in this scope

### ISSUE THREAD

**Issue by ChenBoSyun** [microsoft/onnxruntime#4036]
I follow [this](https://github.com/microsoft/onnxruntime/blob/rel-1.3.0/BUILD.md#Build-ONNX-Runtime-Server-on-Linux) to build onnxruntime from source.

After that I compile the CXX_Api_Sample.cpp 

First, I got the error message 

In function __static_initialization_and_destruction_0(int, int)':
CXX_Api_Sample.cpp:(.text+0x8a1): undefined reference to `OrtGetApiBase'
collect2: error: ld returned 1 exit status

I follow #1897 to solve the problem 
add this code 
`const OrtApi* Ort::g_api = OrtGetApi(ORT_API_VERSION);
`

And I got another error message 

CXX_Api_Sample.cpp:10:20: error: ‘Ort::g_api’ should have been declared inside ‘Ort’
 const OrtApi* Ort::g_api = OrtGetApi(ORT_API_VERSION);
                    ^
CXX_Api_Sample.cpp:10:53: error: ‘OrtGetApi’ was not declared in this scope
 const OrtApi* Ort::g_api = OrtGetApi(ORT_API_VERSION);

Could someone help me?

**Comment by ChenBoSyun** [comment]
Hello, could someone help me?

**Comment by seeledu** [comment]
I met the same situation, how do you solve that?
