### ISSUE TITLE
The issue on Cast elimination in fusion

### ISSUE THREAD

**Issue by jiafatom** [microsoft/onnxruntime#4039]
**Describe the bug**
When I run an onnx model with two consecutive Cast node. The first Cast is to cast to integer from float32, followed by the Cast that is cast to float32. It seems that ORT gives a wrong result that the integer Cast does not make effects. I suspect there is Cast fusion going on, but in this case, the fist Cast should not be removed.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10 Version	10.0.18363 Build 18363
- ONNX Runtime installed from (source or binary): pypi
- ONNX Runtime version: 1.3.0
- Python version: 3.7

**Comment by tianleiwu** [comment]
@iK1D, @pengwa please take a look this.

**Comment by hariharans29** [comment]
Hi @jiafatom - Could you share a minimalistic model to repro the issue ?
