### ISSUE TITLE
Wrong model prediction for keras application models NASNetMobile and NASNetLarge

### ISSUE THREAD

**Issue by jiafatom** [Microsoft/onnxruntime#404]
**Describe the bug**
I am converting keras application models https://github.com/onnx/keras-onnx. (1) I use onnx runtime release 0.1.4, it can convert the keras model (NASNetMobile and NASNetLarge) to onnx model, but it gives me the wrong prediction. For NASNetMobile, all predictions are NAN, for NASNetLarge, most of them are 0.0.  (2) I check out the release 0.1.4 and build it locally on my machine using "build.bat --config RelWithDebInfo --build_wheel --enable_pybind", it gives me the correct prediction. So the official release fails on this prediction.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Microsoft Windows 10 Enterprise Version 10.0.17763 Build 17763
- ONNX Runtime installed from (source or binary): both (see above)
- ONNX Runtime version: 0.1.4
- Python version: 3.6
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Describe steps/code to reproduce the behavior:
Put the following code into keras-onnx/tests/test_layer.py, then run unit tests.

    def test_NASNetMobile(self):
        from keras.applications.nasnet import NASNetMobile
        model = NASNetMobile(include_top=True, weights='imagenet')
        self._test_keras_model(model)

    def test_NASNetLarge(self):
        from keras.applications.nasnet import NASNetLarge
        model = NASNetLarge(include_top=True, weights='imagenet')
        self._test_keras_model(model, img_size=331)

**Expected behavior**
Should be a real-value 1*1000 vector which is probability (sum to 1)

**Screenshots**

**Additional context**

**Comment by snnn** [comment]
I have nas models from TF,  they work fine.
nasnet_mobile/nasnet_large/pnasnet_large

**Comment by snnn** [comment]
You can get the test models from: [https://onnxruntimetestdata.blob.core.windows.net/models/20190107.zip](https://onnxruntimetestdata.blob.core.windows.net/models/20190107.zip)

Ref:
https://github.com/Microsoft/onnxruntime/blob/master/tools/ci_build/github/azure-pipelines/templates/set-test-data-variables-step.yml

**Comment by jiafatom** [comment]
Just tested with latest code, it works. Thanks :)
