### ISSUE TITLE
Building a dynamic library without dependency

### ISSUE THREAD

**Issue by xiaoerqi** [microsoft/onnxruntime#4048]
Because our server uses a lower version of GCC(4.8.4),and there are compilation errors when building，I need to build a libonnxruntime.so that does not depend on other dynamic libraries with a higher version of GCC ; I found that the release version of the dynamic library provided by the official does not depend on other dynamic libraries. It can be used in any environment. How can I compile it without relying on other dynamic libraries  , or whether this option is provided in the build option.Thanks！

**Comment by snnn** [comment]
Onnxruntime should support GCC 4.8.4. If you saw any build error, please post it here. We'll fix it.

**Comment by xiaoerqi** [comment]
**Describe the bug**
Error compiling onnxruntime in gcc4.8.4,
The error occurred when compiling the onnx component

**Urgency**
We have to use onnxruntime for our project now, so we hope to solve it in a week

**System information**
- OS Platform and Distribution (Linux Ubuntu 14.04):
- ONNX Runtime installed from (source ./build.sh --config Release --build_shared_lib --parallel --use_dnnl):
- ONNX Runtime version:1.3.0
- Python version:3.6
- GCC version :4.8.4
- Baseline CPU

**To Reproduce**
I compiled according to the official steps, with the following compilation errors:

/res/onnxruntime/cmake/external/onnx/onnx/defs/logical/defs.cc:22:15: error: unterminated raw string
         doc = R"DOC(
               ^
/res/onnxruntime/cmake/external/onnx/onnx/defs/logical/defs.cc:27:5: warning: missing terminating " character [enabled by default]
 )DOC";
     ^
/res/onnxruntime/cmake/external/onnx/onnx/defs/logical/defs.cc:21:5: error: missing terminating " character
     POPULATE_OP_DOC_STR(
     ^
/res/onnxruntime/cmake/external/onnx/onnx/defs/logical/defs.cc: In lambda function:
/res/onnxruntime/cmake/external/onnx/onnx/defs/logical/defs.cc:27:2: error: ‘DOC’ was not declared in this scope
 )DOC";
  ^
/res/onnxruntime/cmake/external/onnx/onnx/defs/logical/defs.cc:28:9: error: expected ‘;’ before ‘ReplaceAll’
         ReplaceAll(doc, "{name}", name);
         ^
/res/onnxruntime/cmake/external/onnx/onnx/defs/logical/defs.cc:30:75: error: expected primary-expression before ‘)’ token
             doc, "{broadcast_doc}", GenerateBroadcastingDocMul().c_str()););
                                                                           ^
/res/onnxruntime/cmake/external/onnx/onnx/defs/logical/defs.cc:30:75: error: expected ‘;’ before ‘)’ token
make[2]: *** [onnx/CMakeFiles/onnx.dir/__/external/onnx/onnx/defs/logical/defs.cc.o] Error 1
make[1]: *** [onnx/CMakeFiles/onnx.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Expected behavior**
I hope to be able to successfully build onnxruntime in Ubuntu 14.04 and gcc4.8.4

**Comment by snnn** [comment]
Oh, yes,  I can confirm it is a problem. CC @pranavsharma 
But I'm sorry, we can't fix it as the code is in another repo, which is out of our control. 

I don't think you can upgrade your GCC to bypass it. CentOS has devtoolset but Ubuntu doesn't have such things. 

You may go to the /res/onnxruntime/cmake/external/onnx submodule and try to revert the 
674438c0c01102dd6f726c9e2a38d6738d61f398 commit.
```
cd onnxruntime/cmake/external/onnx
git revert 674438c0c01102dd6f726c9e2a38d6738d61f398 
```
If there is any conflict during the revert, please fix it.

Then please go back to your top src dir and run build.sh with "--skip_submodule_sync"

```
 ./build.sh --config Release --build_shared_lib --parallel --use_dnnl --skip_submodule_sync
```

**Comment by snnn** [comment]
Hi @Pranav, it is a problem.
