### ISSUE TITLE
onnxruntime.capi_pybind_state on windows exe

### ISSUE THREAD

**Issue by CesMak** [microsoft/onnxruntime#4054]
**Describe the bug**
Hey there, 

I use pyinstaller to convert my python code (which requires onnxruntime) into an exe file.

This exe file runs without problems on my win10 pc with python 3.7 installed and PATH variable set.

However on another win pc without python installed the erro message below pops up :( 
As I have an exe I do not want to install the correct python version on every pc - is there a way to build the correct .dll file etc. that works on every pc?

Any ideas how to solve this issue?

![photo_2020-05-27_18-14-54](https://user-images.githubusercontent.com/20240718/83057104-bdca3a00-a056-11ea-81e9-5b0ca03e6cd8.jpg)

**Comment by snnn** [comment]
It requires [Visual C++ 2019 runtime](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

**Comment by CesMak** [comment]
Thanks that worked! 

Close this issue :)
