### ISSUE TITLE
C and C++ API examples should not be located under csharp dir

### ISSUE THREAD

**Issue by KevinHake** [microsoft/onnxruntime#4060]
Confusingly enough there *is* a pure-cross platform, minimal C++ API sample, but it's under the `csharp` folder where no one would think to look:

https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp

_Originally posted by @pranav-prakash in https://github.com/microsoft/onnxruntime/issues/3879#issuecomment-626068756_

The C API example(s)? also exists under "csharp/test/"
Perhaps all sample files can be moved to the `samples` dir, which already exists and contains docs listing examples.
If we move these, we need to grep the repo for references and make sure docs reference the new locations

**Comment by faxu** [comment]
Please refer to the [Samples page](https://github.com/microsoft/onnxruntime/tree/master/samples) for an aggregated list of links to recommended references. Agree that the way the file structure is set up is a bit confusing but is due to how the build tests are set up.

**Comment by KevinHake** [comment]
Ah, thanks @faxu. Can you point me to the entry point for the build tests? I'm getting familiar with things still.
