### ISSUE TITLE
Not able to build ONNX Runtime Server image

### ISSUE THREAD

**Issue by gaurang002** [microsoft/onnxruntime#4077]
**Describe the bug**
Following https://github.com/microsoft/onnxruntime/tree/master/dockerfiles#onnx-runtime-server, I am not able to build onnxruntime server image. 

I am getting following error:

[ 88%] Building CXX object CMakeFiles/onnxruntime_server_tests.dir/test/unit_tests/prediction_service_impl_test.cc.o
[ 90%] Building CXX object CMakeFiles/onnxruntime_server_tests.dir/test/unit_tests/server_configuration_test.cc.o
[ 92%] Building CXX object CMakeFiles/onnxruntime_server_tests.dir/test/unit_tests/test_main.cc.o
/onnxruntime/server/main.cc:23:44: note: #pragma message: SRV_VERSION=""
 #pragma message(VAR_NAME_VALUE(SRV_VERSION))
                                            ^
/onnxruntime/server/main.cc:29:49: note: #pragma message: LATEST_COMMIT_ID=""
 #pragma message(VAR_NAME_VALUE(LATEST_COMMIT_ID))
                                                 ^
In file included from /usr/include/x86_64-linux-gnu/c++/5/bits/c++allocator.h:33:0,
                 from /usr/include/c++/5/bits/allocator.h:46,
                 from /usr/include/c++/5/memory:63,
                 from /onnxruntime/server/environment.h:6,
                 from /onnxruntime/server/main.cc:4:
/usr/include/c++/5/ext/new_allocator.h: In instantiation of 'void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = spdlog::sinks::syslog_sink<std::mutex>; _Args = {}; _Tp = spdlog::sinks::syslog_sink<std::mutex>]':
/usr/include/c++/5/bits/alloc_traits.h:530:4:   required from 'static void std::allocator_traits<std::allocator<_Tp1> >::construct(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*, _Args&& ...) [with _Up = spdlog::sinks::syslog_sink<std::mutex>; _Args = {}; _Tp = spdlog::sinks::syslog_sink<std::mutex>; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<spdlog::sinks::syslog_sink<std::mutex> >]'
/usr/include/c++/5/bits/shared_ptr_base.h:522:39:   required from 'std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {}; _Tp = spdlog::sinks::syslog_sink<std::mutex>; _Alloc = std::allocator<spdlog::sinks::syslog_sink<std::mutex> >; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]'
/usr/include/c++/5/bits/shared_ptr_base.h:617:4:   required from 'std::__shared_count<_Lp>::__shared_count(std::_Sp_make_shared_tag, _Tp*, const _Alloc&, _Args&& ...) [with _Tp = spdlog::sinks::syslog_sink<std::mutex>; _Alloc = std::allocator<spdlog::sinks::syslog_sink<std::mutex> >; _Args = {}; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]'
/usr/include/c++/5/bits/shared_ptr_base.h:1097:35:   required from 'std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<spdlog::sinks::syslog_sink<std::mutex> >; _Args = {}; _Tp = spdlog::sinks::syslog_sink<std::mutex>; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]'
/usr/include/c++/5/bits/shared_ptr.h:319:64:   required from 'std::shared_ptr<_Tp>::shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<spdlog::sinks::syslog_sink<std::mutex> >; _Args = {}; _Tp = spdlog::sinks::syslog_sink<std::mutex>]'
/usr/include/c++/5/bits/shared_ptr.h:620:39:   required from 'std::shared_ptr<_Tp1> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = spdlog::sinks::syslog_sink<std::mutex>; _Alloc = std::allocator<spdlog::sinks::syslog_sink<std::mutex> >; _Args = {}]'
/usr/include/c++/5/bits/shared_ptr.h:635:39:   required from 'std::shared_ptr<_Tp1> std::make_shared(_Args&& ...) [with _Tp = spdlog::sinks::syslog_sink<std::mutex>; _Args = {}]'
/onnxruntime/server/main.cc:61:209:   required from here
/usr/include/c++/5/ext/new_allocator.h:120:4: error: no matching function for call to 'spdlog::sinks::syslog_sink<std::mutex>::syslog_sink()'
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
In file included from /onnxruntime/server/main.cc:12:0:
/onnxruntime/server/external/spdlog/include/spdlog/sinks/syslog_sink.h:23:5: note: candidate: spdlog::sinks::syslog_sink<Mutex>::syslog_sink(std::__cxx11::string, int, int, bool) [with Mutex = std::mutex; std::__cxx11::string = std::__cxx11::basic_string<char>]
     syslog_sink(std::string ident, int syslog_option, int syslog_facility, bool enable_formatting)
     ^
/onnxruntime/server/external/spdlog/include/spdlog/sinks/syslog_sink.h:23:5: note:   candidate expects 4 arguments, 0 provided
[ 94%] Building CXX object CMakeFiles/onnxruntime_server_tests.dir/test/unit_tests/test_server_environment.cc.o
make[2]: *** [CMakeFiles/onnxruntime_server.dir/main.cc.o] Error 1
CMakeFiles/onnxruntime_server.dir/build.make:62: recipe for target 'CMakeFiles/onnxruntime_server.dir/main.cc.o' failed
CMakeFiles/Makefile2:254: recipe for target 'CMakeFiles/onnxruntime_server.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_server.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Building CXX object CMakeFiles/onnxruntime_server_tests.dir/test/unit_tests/util_tests.cc.o
[ 98%] Linking CXX executable onnxruntime_server_tests
Running /usr/local/bin/grpc_python_plugin on /onnxruntime/server/protobuf/prediction_service.proto
[ 98%] Built target onnxruntime_server_tests
make: *** [all] Error 2
Makefile:83: recipe for target 'all' failed
The command '/bin/sh -c mkdir -p /onnxruntime/build && cd /onnxruntime/build && cmake -DCMAKE_BUILD_TYPE=Release /onnxruntime/server     && make -j$(getconf _NPROCESSORS_ONLN)' returned a non-zero code: 2

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04

**To Reproduce**
Running docker build command as per documentation:
docker build -t {docker_image_name} -f Dockerfile.server .

**Expected behavior**
Successful building of onnxruntime server image.

**Comment by mrry** [comment]
I think I see the issue: the default branch on https://github.com/gabime/spdlog just changed to "v1.x", which has a different interface for `syslog_sink`. I'm preparing a fix.

**Comment by gaurang002** [comment]
@mrry - Thank you for fix but seems like still the same error. I have freshly cloned the repo and tried to build but no success.

Here are the error message, which is same as previous one but just for your information.
[ 88%] Building CXX object CMakeFiles/onnxruntime_server_tests.dir/test/unit_tests/prediction_service_impl_test.cc.o
[ 90%] Building CXX object CMakeFiles/onnxruntime_server_tests.dir/test/unit_tests/server_configuration_test.cc.o
[ 92%] Building CXX object CMakeFiles/onnxruntime_server_tests.dir/test/unit_tests/test_main.cc.o
/onnxruntime/server/main.cc:23:44: note: #pragma message: SRV_VERSION=""
 #pragma message(VAR_NAME_VALUE(SRV_VERSION))
                                            ^
/onnxruntime/server/main.cc:29:49: note: #pragma message: LATEST_COMMIT_ID=""
 #pragma message(VAR_NAME_VALUE(LATEST_COMMIT_ID))
                                                 ^
In file included from /usr/include/x86_64-linux-gnu/c++/5/bits/c++allocator.h:33:0,
                 from /usr/include/c++/5/bits/allocator.h:46,
                 from /usr/include/c++/5/memory:63,
                 from /onnxruntime/server/environment.h:6,
                 from /onnxruntime/server/main.cc:4:
/usr/include/c++/5/ext/new_allocator.h: In instantiation of 'void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = spdlog::sinks::syslog_sink<std::mutex>; _Args = {}; _Tp = spdlog::sinks::syslog_sink<std::mutex>]':
/usr/include/c++/5/bits/alloc_traits.h:530:4:   required from 'static void std::allocator_traits<std::allocator<_Tp1> >::construct(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*, _Args&& ...) [with _Up = spdlog::sinks::syslog_sink<std::mutex>; _Args = {}; _Tp = spdlog::sinks::syslog_sink<std::mutex>; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<spdlog::sinks::syslog_sink<std::mutex> >]'
/usr/include/c++/5/bits/shared_ptr_base.h:522:39:   required from 'std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {}; _Tp = spdlog::sinks::syslog_sink<std::mutex>; _Alloc = std::allocator<spdlog::sinks::syslog_sink<std::mutex> >; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]'
/usr/include/c++/5/bits/shared_ptr_base.h:617:4:   required from 'std::__shared_count<_Lp>::__shared_count(std::_Sp_make_shared_tag, _Tp*, const _Alloc&, _Args&& ...) [with _Tp = spdlog::sinks::syslog_sink<std::mutex>; _Alloc = std::allocator<spdlog::sinks::syslog_sink<std::mutex> >; _Args = {}; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]'
/usr/include/c++/5/bits/shared_ptr_base.h:1097:35:   required from 'std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<spdlog::sinks::syslog_sink<std::mutex> >; _Args = {}; _Tp = spdlog::sinks::syslog_sink<std::mutex>; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2u]'
/usr/include/c++/5/bits/shared_ptr.h:319:64:   required from 'std::shared_ptr<_Tp>::shared_ptr(std::_Sp_make_shared_tag, const _Alloc&, _Args&& ...) [with _Alloc = std::allocator<spdlog::sinks::syslog_sink<std::mutex> >; _Args = {}; _Tp = spdlog::sinks::syslog_sink<std::mutex>]'
/usr/include/c++/5/bits/shared_ptr.h:620:39:   required from 'std::shared_ptr<_Tp1> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = spdlog::sinks::syslog_sink<std::mutex>; _Alloc = std::allocator<spdlog::sinks::syslog_sink<std::mutex> >; _Args = {}]'
/usr/include/c++/5/bits/shared_ptr.h:635:39:   required from 'std::shared_ptr<_Tp1> std::make_shared(_Args&& ...) [with _Tp = spdlog::sinks::syslog_sink<std::mutex>; _Args = {}]'
/onnxruntime/server/main.cc:61:209:   required from here
/usr/include/c++/5/ext/new_allocator.h:120:4: error: no matching function for call to 'spdlog::sinks::syslog_sink<std::mutex>::syslog_sink()'
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
In file included from /onnxruntime/server/main.cc:12:0:
/onnxruntime/server/external/spdlog/include/spdlog/sinks/syslog_sink.h:23:5: note: candidate: spdlog::sinks::syslog_sink<Mutex>::syslog_sink(std::__cxx11::string, int, int, bool) [with Mutex = std::mutex; std::__cxx11::string = std::__cxx11::basic_string<char>]
     syslog_sink(std::string ident, int syslog_option, int syslog_facility, bool enable_formatting)
     ^
/onnxruntime/server/external/spdlog/include/spdlog/sinks/syslog_sink.h:23:5: note:   candidate expects 4 arguments, 0 provided
[ 94%] Building CXX object CMakeFiles/onnxruntime_server_tests.dir/test/unit_tests/test_server_environment.cc.o
CMakeFiles/onnxruntime_server.dir/build.make:62: recipe for target 'CMakeFiles/onnxruntime_server.dir/main.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_server.dir/main.cc.o] Error 1
CMakeFiles/Makefile2:254: recipe for target 'CMakeFiles/onnxruntime_server.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_server.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Building CXX object CMakeFiles/onnxruntime_server_tests.dir/test/unit_tests/util_tests.cc.o
[ 98%] Linking CXX executable onnxruntime_server_tests
Running /usr/local/bin/grpc_python_plugin on /onnxruntime/server/protobuf/prediction_service.proto
[ 98%] Built target onnxruntime_server_tests
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c mkdir -p /onnxruntime/build && cd /onnxruntime/build && cmake -DCMAKE_BUILD_TYPE=Release /onnxruntime/server     && make -j$(getconf _NPROCESSORS_ONLN)' returned a non-zero code: 2

**Comment by mrry** [comment]
Sorry about that! It seems like the submodule configuration is still incorrect, and it's pulling down the wrong version of spdlog. I'm taking a look now....

**Comment by gaurang002** [comment]
Thank you. 
Quick Question, assuming I can build the image, would it work with GPU? Current precompiled image seems only works with CPU even if GPU is available.

**Comment by pranavsharma** [comment]
> Thank you.
> Quick Question, assuming I can build the image, would it work with GPU? Current precompiled image seems only works with CPU even if GPU is available.

onnxruntime server doesn't support GPU yet.

**Comment by gaurang002** [comment]
Ok. Thank you.

**Comment by gaurang002** [comment]
@mrry - still failing but now at different step it seems. Error still seems realted to spdlog.


Step 12/20 : ENV PATH="/usr/local/go/bin:${PATH}"
 ---> Running in 4da04bc3241b
Removing intermediate container 4da04bc3241b
 ---> 3699f4db857e
Step 13/20 : WORKDIR /
 ---> Running in 9c57de71fccf
Removing intermediate container 9c57de71fccf
 ---> 9b2be49e7d10
Step 14/20 : RUN mkdir -p /onnxruntime/build && cd /onnxruntime/build && cmake -DCMAKE_BUILD_TYPE=Release /onnxruntime/server     && make -j$(getconf _NPROCESSORS_ONLN)
 ---> Running in 701281f6ad62
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
-- Found ProtobufWithTargets: TRUE
-- Found Protobuf: optimized;/usr/lib/x86_64-linux-gnu/libprotobuf.a;debug;/usr/lib/x86_64-linux-gnu/libprotobufd.a;-lpthread (found version "3.11.2")
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")
-- Adding Boost components
CMake Warning (dev) at external/spdlog/CMakeLists.txt:27 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'SPDLOG_BUILD_EXAMPLES'.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- ONNX Runtime Server version set to:
-- ONNX Runtime Server latest commit id is:
-- Configuring done
CMake Error at CMakeLists.txt:185 (add_executable):
  Target "onnxruntime_server" links to target "spdlog::spdlog" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?


CMake Error at CMakeLists.txt:241 (add_executable):
  Target "onnxruntime_server_tests" links to target "spdlog::spdlog" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
The command '/bin/sh -c mkdir -p /onnxruntime/build && cd /onnxruntime/build && cmake -DCMAKE_BUILD_TYPE=Release /onnxruntime/server     && make -j$(getconf _NPROCESSORS_ONLN)' returned a non-zero code: 1

**Comment by mrry** [comment]
I'm very sorry about this churn! (I haven't yet been able to reproduce this problem on my local workstation, and was hoping that the submodule fix would get it to build.)

Reopening this while I investigate the underlying problem, although it may take me a few days to reproduce the build failure.
