### ISSUE TITLE
AttributeError: 'InferenceSession' object has no attribute 'get_providers'

### ISSUE THREAD

**Issue by Nfekih** [microsoft/onnxruntime#4081]
**Describe the bug**
After installing onnxruntime-gpu via pip install inside a conda enviornement as recommended, I successfully convert a BERT torch model (Transformres) into .onnx format.
Then, I try this code sample:

`import onnxruntime
print (onnxruntime.get_device ())
model_path = "model.onnx"
session = onnxruntime.InferenceSession (model_path)
print (session.get_providers ())`

I get this error: `AttributeError: 'InferenceSession' object has no attribute 'get_providers'`

**System information**
- OS: Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source 
- ONNX version: 1.7.0
- ONNX Runtime version: 1.3.0
- ONNX Runtime gpu version: 1.2.0
- Python version: Python 3.8 (Anaconda)
- GCC/Compiler version : 7.5.0
- CUDA/cuDNN version: 10.1/7.6
- GPU model and memory:  RTX 2060 8G

Am I mistaken a compatible version between packages or what is wrong?

**Comment by pranavsharma** [comment]
Most likely you don't have the cuda dependencies in your path.

**Comment by Nfekih** [comment]
@pranavsharma  thanks for the quick reply. 
I run from terminal
`export CUDA_HOME=/usr/local/cuda
export PATH=${CUDA_HOME}/bin:${PATH}
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:$LD_LIBRARY_PATH`
I get the same error
assert 'CUDAExecutionProvider' in onnxruntime.get_available_providers()

can you explain more ?

**Comment by Nfekih** [comment]
Yes @pranavsharma, you are right thanks
Also I changed to python3.6 for it to run correctly.

**Comment by ndalton12** [comment]
@Nfekih can you expand on what you did here? I tried defining `CUDA_HOME`, `CUDA_PATH`, `TENSORRT_HOME`, `TENSORRT_PATH`, and adding all of them to `PATH` and `LD_LIBRARY_PATH`. But still getting this same error. Not running on Python 3.6 though.

**Comment by ndalton12** [comment]
Nevermind, I realized I didn't provide --gpus when running `docker run ...`

**Comment by RuchitaTekade** [comment]
I am getting the following error, can anyone help?
AttributeError: 'InferenceSession' object has no attribute 'get_TI_benchmark_data'
