### ISSUE TITLE
rel-1.3.0 Eigen revision is invalid

### ISSUE THREAD

**Issue by neuralwilltor** [microsoft/onnxruntime#4082]
**Describe the bug**
The revision of the Eigen submodule is invalid and doesn't fetch from Github.

**Urgency**
Low for developers, I suspect -- it's just problematic for building ONNX Runtime from source.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Any
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: rel-1.3.0
- Python version: Any
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): Any
- CUDA/cuDNN version: Any
- GPU model and memory: Any

**To Reproduce**
Clone the repository with its submodules.

**Expected behavior**
A successful clone without errors.

**Screenshots**
None.

**Additional context**
None.

**Comment by snnn** [comment]
From Eigen's official website:

Following the decision of Bitbucket.org to delete all mercurial repositories next spring, we decided to migrate to a git repository hosted on gitlab.com. We also decided to take this opportunity to migrate our self hosted bugzilla instance to gitlab.com. Both migrations are scheduled on the 4th of December, starting at 8:00 UTC, and the new project:
https://gitlab.com/libeigen/eigen
will be made public once the migration is completed.
