### ISSUE TITLE
ConvTranspose auto_pad=SAME_UPPER/SAME_LOWER not working properly

### ISSUE THREAD

**Issue by vuzelac-cadence** [microsoft/onnxruntime#4086]
**Describe the bug**
Using ConvTranspose with auto_pad=SAME_UPPER. Program below prints output shape as `(1, 1, 4, 4)` which is different than the input shape. Should have been the same shape.
But also, node is created with the correct shape` (1,1,2,2) `and the checker passed. The actual output values indicate auto_pad=VALID is likely used internally.

**Urgency**
None

**System information**
Windows 10
ONNX Runtime installed from binary:
ONNX Runtime version: 1.3.0
Python version:  3.5.6
CUDA/cuDNN version: None

**To Reproduce**
```
from onnx import helper, checker, AttributeProto, TensorProto, GraphProto
import onnxruntime as rt
import numpy as np

X = helper.make_tensor_value_info('X', TensorProto.FLOAT, [1, 1, 2, 2])
W = helper.make_tensor_value_info('W', TensorProto.FLOAT, [1, 1, 3, 3])
Y = helper.make_tensor_value_info('Y', TensorProto.FLOAT, [1, 1, 2, 2])
node_def = helper.make_node("ConvTranspose", ["X", "W"], ["Y"], auto_pad="SAME_UPPER", strides=[1, 1])
graph_def = helper.make_graph([node_def], 'deconv-model', [X, W], [Y])
model_def = helper.make_model(graph_def, producer_name='')

checker.check_model(model_def)
with open("deconv.onnx", "wb") as f:
    f.write(model_def.SerializeToString())

sess = rt.InferenceSession("deconv.onnx")

X = np.arange(2, 6, 1).reshape(1, 1, 2, 2)
W = np.arange(2, 11, 1).reshape(1, 1, 3, 3)

onnx_pred = sess.run(["Y"], {"X": X.astype(np.float32), "W": W.astype(np.float32)})[0]
print(onnx_pred.shape)
```
**Expected behavior**
should print `(1, 1, 2, 2)`, prints` (1, 1, 4, 4)`

**Comment by jwfromm** [comment]
Have there been any updates into this issue? It would be great to get it resolved.

**Comment by hariharans29** [comment]
Are you able to build from source ? If so, could you please try with changes in the linked PR and let us know if the results are as expected. We can merge the PR with higher confidence then.
