### ISSUE TITLE
Build with TensorRT : onnxruntime_test_all fails

### ISSUE THREAD

**Issue by pfeatherstone** [microsoft/onnxruntime#4098]
**Describe the bug**
Trying to build onnxruntime 1.3.0 with the following command:
```
./build.sh \
        --use_opemp \
        --use_cuda \
        --cuda_version=10.2 \
        --cuda_home=/usr/local/cuda \
        --cudnn_home=/usr/local/cuda \
        --use_tensorrt --tensorrt_home=$HOME/TensorRT \
        --build_shared_lib \
        --config Release
```
The build fails on the following tests:
1: [  FAILED  ] QAttentionTest.AttentionBatch1
1: [  FAILED  ] QAttentionTest.AttentionBatch1_Float16
1: [  FAILED  ] QAttentionTest.AttentionBatch2
1: [  FAILED  ] QAttentionTest.AttentionMaskPartialSequence
1: [  FAILED  ] QAttentionTest.AttentionMaskExceedSequence
1: [  FAILED  ] QAttentionTest.AttentionNoMaskIndex

**System information**
- Ubuntu 18.04
- Onnxruntime 1.3.0 (source)
- CUDA/cuDNN version: 10.2 - 7.65

**Comment by pfeatherstone** [comment]
I get the same error when building from master.

**Comment by snnn** [comment]
@stevenlix   Could you please take a look?

**Comment by yufenglee** [comment]
fixed with #4111

**Comment by pfeatherstone** [comment]
So rebuilding from master, the build fails when trying to link against ```libmyelin.so.1``` even though it can be found in ```/usr/local/cuda/lib```. Maybe the build scripts only uses ```/usr/local/cuda/lib64```.

**Comment by pfeatherstone** [comment]
It can also be found in <Tensorrt-home>/lib. so don't know why the linker fails

**Comment by pfeatherstone** [comment]
@snnn Do you get errors when building from source on Linux due to libmyelin.so.1 not being found despite it being available in both cuda_home and tensorrt_home?
