### ISSUE TITLE
Graph optimization break correctness

### ISSUE THREAD

**Issue by mzmssg** [microsoft/onnxruntime#4110]
**Describe the bug**
Two bugs:
1. Inference session output differently with/without optimization
2. Even we specify an intermediate node in a pattern as graph output, graph optimization still fuse them, then sess fail to find the output.

**Urgency**
None

**To Reproduce**
code:
```python
import onnxruntime as ort
import numpy as np
import onnx

def remove_expand_shape(model):
    expand_node = [n for n in model.graph.node if n.op_type == 'Expand']
    if len(expand_node) != 1:
        raise "cannot find the single expand node in the BERT model."

    for i, v_info in enumerate(model.graph.value_info):
        if v_info.name == expand_node[0].output[0]:
            break    
    del model.graph.value_info[i]

def add_value_to_output(model, intermediate_tensor_name):
    intermediate_layer_value_info = helper.ValueInfoProto()
    intermediate_layer_value_info.name = intermediate_tensor_name
    model.graph.output.extend([intermediate_layer_value_info])

model_name = "bert_for_pretraining_without_loss_optimized.onnx"
model = onnx.load(model_name)
#remove_expand_shape(model)

#n = find_input_node(model, "209")
#print(n)
#add_value_to_output(model, "209")

# We convert model to accept variable-length batch size, so it can be any positive integer.
batch = 3
# This should match --max_seq_length when calling nv_run_pretraining.py.
sq_length = 512
# This should match vocab_size in bert_config.json in DeepLearningExamples/PyTorch/LanguageModeling/BERT.
vocab_size = 30528

# Create a fake data point.
input_ids = np.random.randint(low=0, high=vocab_size, size=(batch, sq_length), dtype=np.int64)
segment_ids = np.random.randint(low=0, high=2, size=(batch, sq_length), dtype=np.int64)
input_mask = np.ones((batch, sq_length), dtype=np.int64)

opt_enable_sess = ort.InferenceSession(model.SerializeToString())
opt_enable_result = opt_enable_sess.run(None, {'input1': input_ids, 'input2': segment_ids, 'input3': input_mask})

so = ort.SessionOptions()
so.graph_optimization_level=ort.GraphOptimizationLevel.ORT_DISABLE_ALL
opt_disable_sess = ort.InferenceSession(model.SerializeToString(), so)
opt_disable_result = opt_disable_sess.run(None, {'input1': input_ids, 'input2': segment_ids, 'input3': input_mask})

print(opt_enable_result[1])
print(opt_disable_result[1])
```

model:
[bert_for_pretraining_without_loss_optimized.onnx](https://github.com/mzmssg/onnx_models/blob/master/bert_for_pretraining_without_loss_optimized.onnx)

output:
![image](https://user-images.githubusercontent.com/11887940/83501514-cdcc9880-a4f2-11ea-8d21-b00aa1ea7a58.png)

**Expected behavior**
sess with/without optimization should have a same result.

**Additional context**
1. It have a corrent result if remove expand shape by uncomment `#remove_expand_shape(model)`.
2. I checked the intermedia value by value, seems it's caused by GELU fusion, because this two session have a same input before gelu part but output differently, but it should be irrelevant to the `Expand` operation.
3. The second bug could be reproduced by uncomment 
```
#n = find_input_node(model, "209")
#print(n)
#add_value_to_output(model, "209")
```

**Comment by askhade** [comment]
@mzmssg : What version of onnxruntime and execution provider are you ?

**Comment by mzmssg** [comment]
@askhade 
The latest master code with cuda.
Build command is `./build.sh --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ --use_cuda --config Release --build_wheel --update --build --parallel --enable_training --skip_tests --cmake_extra_defines ONNXRUNTIME_VERSION=$(cat ./VERSION_NUMBER)`

**Comment by tianleiwu** [comment]
It is a known bug that many fusions check GetOutputEdgesCount() != 1 to see whether a subgraph can be fused but graph output is not counted in output edges. It is in our back log.

**Comment by askhade** [comment]
@tianleiwu : Thanks for adding the PR to add the check for graph outputs

I am debugging the first issue mentioned here : "Inference session output differently with/without optimization"

This is because BiasGelu fusion has a bug... It is not adding correct bias input for this node. In the cpu implementation we have a check to verify the dimension of bias which fails and it errors out... In cuda implementation we do not have this check because of which the inference continues and the end result is wrong.

BiasGelu:
![image](https://user-images.githubusercontent.com/6475296/83716483-e4531c80-a5e4-11ea-8a36-e8ece88db368.png)


CPU Execution Provider error: 
Name:'BiasGelu' Status Message: Input 1 is expected to have 1 dimensions, got 3

I am still debugging why the bias input is wrong. Will update this thread soon.

**Comment by tianleiwu** [comment]
@askhade, thanks for providing the fix.

@mzmssg, the issues shall be resolved. You can try the latest nightly build. 

Close it for now. Feel free to re-open it if it is not as you expected.
