### ISSUE TITLE
Predictions do not match for RandomForestRegressor

### ISSUE THREAD

**Issue by lcmanahan** [microsoft/onnxruntime#4130]
**Describe the bug**
There are inconsistencies between the predictions of the scikit-learn model and the ONNX model.
Here’s an illustration of what the deviations look like with increasing values of the dependent variable. Note that RMSE here is a measure of difference between predictions of the original scikit-learn model and the ONNX model.
![rmse_1](https://user-images.githubusercontent.com/38173800/83720355-7e5da800-a66b-11ea-98b3-29602206aca3.jpg)
Here are the largest differences observed from the predictions of model 9 above.
![diff](https://user-images.githubusercontent.com/38173800/83720460-af3ddd00-a66b-11ea-8704-7786f080983d.jpg)
Here’s an illustration of the error rates with increasing number of trees in the forest.
![rmse_2](https://user-images.githubusercontent.com/38173800/83720491-bebd2600-a66b-11ea-8502-3ee270aca9af.JPG)

**System information**
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.3.0
- Python version: 3.7.0

**To Reproduce**
A script replicating this issue is in the attached zip folder. This folder also includes some test data and the model files.
[sample_model10.zip](https://github.com/microsoft/onnxruntime/files/4727839/sample_model10.zip)

**Comment by xadupre** [comment]
Hi,

I'm not it can be fixed. The skl pipeline goes from ``float --> normalize --> double --> RF --> double``. The onnx pipeline does ``float --> normalize --> float --> RF --> float``. You can get more information about what it is complex here:

http://www.xavierdupre.fr/app/mlprodict/helpsphinx/notebooks/onnx_float_double_skl_decision_trees.html

The onnx spec does not support double coefficient for TreeEnsembleRegressor so I used a runtime supporting double for the node TreeEnsembleRegressor and checked there was discrepencies and reused your script (see below).

One direction I can suggest is to train the normalizer, convert into onnx then compute the output, then train the RandomForestRegressor based on the new output. There should not be any discrepencies. I can write some code if you are interested.

```
import os
import onnx
import pickle
import numpy as np
import pandas as pd
import onnxruntime as rt
from math import sqrt
from onnx import helper
from skl2onnx import convert_sklearn
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from skl2onnx.common.data_types import FloatTensorType

data = pd.read_csv("model10.csv")
data[['SegmentTravelTime',
      'NumberOfPassengers',
      'BookingHour',
      'TripFirstTravelDateHour',
      'SegmentFirstTravelDateHour',
      'TripDays',
      'DaysBetweenLoggedandTripDate',
      'DaysBetweenLoggedandSegmentDate',
      'DaysBetweenLoggedandNextFlight',
      'TotalFare',
      'PredictedValue']] = data[['SegmentTravelTime',
                                 'NumberOfPassengers',
                                 'BookingHour',
                                 'TripFirstTravelDateHour',
                                 'SegmentFirstTravelDateHour',
                                 'TripDays',
                                 'DaysBetweenLoggedandTripDate',
                                 'DaysBetweenLoggedandSegmentDate',
                                 'DaysBetweenLoggedandNextFlight',
                                 'TotalFare',
                                 'PredictedValue']].astype(np.float32)
data_y = data['PredictedValue']
data_x = data[['SegmentTravelTime',
               'NumberOfPassengers',
               'BookingHour',
               'TripFirstTravelDateHour',
               'SegmentFirstTravelDateHour',
               'TripDays',
               'DaysBetweenLoggedandTripDate',
               'DaysBetweenLoggedandSegmentDate',
               'DaysBetweenLoggedandNextFlight',
               'TotalFare']]

model = Pipeline([
    ('numeric', StandardScaler()),
    ('model', RandomForestRegressor(n_estimators=100))
])
model.fit(data_x, data_y)
pkl_filename = "model10.pkl"
with open(pkl_filename, 'wb') as file:
    pickle.dump(model, file)


def predict_onnx(x, dtype=np.float32):
    inputs = {
        'SegmentTravelTime': np.array(x['SegmentTravelTime'], dtype=dtype).reshape(1, 1),
        'NumberOfPassengers': np.array(x['NumberOfPassengers'], dtype=dtype).reshape(1, 1),
        'BookingHour': np.array(x['BookingHour'], dtype=dtype).reshape(1, 1),
        'TripFirstTravelDateHour': np.array(x['TripFirstTravelDateHour'], dtype=dtype).reshape(1, 1),
        'SegmentFirstTravelDateHour': np.array(x['SegmentFirstTravelDateHour'], dtype=dtype).reshape(1, 1),
        'TripDays': np.array(x['TripDays'], dtype=dtype).reshape(1, 1),
        'DaysBetweenLoggedandTripDate': np.array(x['DaysBetweenLoggedandTripDate'], dtype=dtype).reshape(1, 1),
        'DaysBetweenLoggedandSegmentDate': np.array(x['DaysBetweenLoggedandSegmentDate'], dtype=dtype).reshape(1, 1),
        'DaysBetweenLoggedandNextFlight': np.array(x['DaysBetweenLoggedandNextFlight'], dtype=dtype).reshape(1, 1),
        'TotalFare': np.array(x['TotalFare'], dtype=dtype).reshape(1, 1)
    }
    return inputs


# converting to onnx

def get_inputs(dtype):
    inputs = [('SegmentTravelTime', FloatTensorType(shape=[1, 1])),
              ('NumberOfPassengers', FloatTensorType(shape=[1, 1])),
              ('BookingHour', FloatTensorType(shape=[1, 1])),
              ('TripFirstTravelDateHour', FloatTensorType(shape=[1, 1])),
              ('SegmentFirstTravelDateHour', FloatTensorType(shape=[1, 1])),
              ('TripDays', FloatTensorType(shape=[1, 1])),
              ('DaysBetweenLoggedandTripDate', FloatTensorType(shape=[1, 1])),
              ('DaysBetweenLoggedandSegmentDate', FloatTensorType(shape=[1, 1])),
              ('DaysBetweenLoggedandNextFlight', FloatTensorType(shape=[1, 1])),
              ('TotalFare', FloatTensorType(shape=[1, 1]))]
    return inputs

use_64 = True
if use_64:
    from mlprodict.onnx_conv import to_onnx
    from skl2onnx.common.data_types import DoubleTensorType
    inputs = get_inputs(DoubleTensorType)
    dtype = np.float64
    onnx_model = to_onnx(model, initial_types=inputs,
                         rewrite_ops=True, dtype=dtype)
else:
    inputs = get_inputs(FloatTensorType)
    dtype = np.float32
    onnx_model = convert_sklearn(model, 'rf_model', inputs)

for line in str(onnx_model).split('\n'):
    if 'Tree' in line:
        print("ONNX model: '{}'.".format(line))
    
# getting skl predicted values
for c in data_x.columns:
    data_x = data_x.astype(dtype)
print(data_x.dtypes)
skl_PredictedValue = pd.DataFrame(model.predict(data_x),
                                  columns=['skl_PredictedValue'])
data = data.drop(["skl_PredictedValue"], axis=1)
data = pd.concat([data.reset_index(drop=True), skl_PredictedValue], axis=1)

with open("model10.onnx", 'wb') as file:
    file.write(onnx_model.SerializeToString())
with open("model10.txt", 'w') as file:
    file.write(str(onnx_model))


# getting onnx predicted values
use_pyrt = True
if use_pyrt:
    name = ""
    from mlprodict.onnxrt import OnnxInference
    oinf = OnnxInference('model10.onnx')
    name = "variable1"
    fct = lambda x, verbose=0, fLOG=None: oinf.run(
        predict_onnx(x, dtype=dtype), verbose=verbose, fLOG=fLOG)[name][0]
else:
    sess = rt.InferenceSession("model10.onnx")
    inputs, outputs = sess.get_inputs(), sess.get_outputs()
    fct = lambda x, verbose=0, fLOG=None: sess.run(
        [outputs[0].name], predict_onnx(x, dtype=dtype))[0][0][0]


data["onnx_PredictedValue"] = ""
for index, row in data.iterrows():
    data.loc[index, "onnx_PredictedValue"] = fct(row, verbose=0, fLOG=print)
    if data.loc[index, "onnx_PredictedValue"] != data.loc[index, "skl_PredictedValue"]:
        d = data.loc[index, "onnx_PredictedValue"] - data.loc[index, "skl_PredictedValue"]
        if abs(d) > 1e-2:
            print("---", d, ':', data.loc[index, "onnx_PredictedValue"], "<>",
                  data.loc[index, "skl_PredictedValue"])

print('----------', data.shape)
print(data[['skl_PredictedValue', 'onnx_PredictedValue']].head())

rmse = sqrt(mean_squared_error(data["skl_PredictedValue"], data["onnx_PredictedValue"]))
print("rmse: " + str(rmse))
rrmse = (rmse/(sum(data["skl_PredictedValue"])/len(data["skl_PredictedValue"])))
print("rrmse: " + str(rrmse))

data.to_csv(R".\model10.csv", index=False)
```

**Comment by xadupre** [comment]
More information about that… I created a [notebook](http://www.xavierdupre.fr/app/mlprodict/helpsphinx/notebooks/onnx_discrepencies.html) which explains the discrepencies. To summarize: the failing converter is the StandardScaler. scikit-learn does ``(X - mean(X)) / std(X)``, ONNX specifications means ``(X - mean(X)) * (1. / std(X))``. Below a short code measures the maximum difference between the two expressions. The discrepencies can be significant and explain that the path in the decision tree in ONNX and scikit-learn are difference and lead to a different prediction. The probability to observe discrepencies with ONNX depends on  the probability to have significant differences in the two expressions above. The probability is higher is the range of a variable is bigger. I need to see if there exists some float32 *b'* such as ``a / b = a * b'``. The linked notebook proposes three ways to remove discrepencies, two can work with onnxruntime.

```
import numpy
a1 = numpy.random.randn(100, 2) * 10
a2 = a1.copy()
a2[:, 1] *= 1000
a3 = a1.copy()
a3[:, 0] *= 1000

for i, a in enumerate([a1, a2, a3]):
    a = a.astype(numpy.float32)
    max_diff32 = numpy.max([
        numpy.abs(numpy.float32(x[0]) / numpy.float32(x[1]) -
            numpy.float32(x[0]) * (numpy.float32(1) / numpy.float32(x[1])))
        for x in a])
    max_diff64 = numpy.max([
        numpy.abs(numpy.float64(x[0]) / numpy.float64(x[1]) -
            numpy.float64(x[0]) * (numpy.float64(1) / numpy.float64(x[1])))
        for x in a])
    print(i, max_diff32, max_diff64)
```
output:
```
0 1.9073486e-06 1.4210854715202004e-14
1 1.8626451e-09 1.3877787807814457e-17
2 0.0009765625 1.4551915228366852e-11
```

**Comment by lcmanahan** [comment]
Thanks! I want to share more examples I made with and without StandardScaler. This shows behavior of the remaining discrepancies across 3 factors: range of dependent variable (0to1, 0to100, 0to10000), first step in pipeline (StandardScaler, Passthrough) and number of trees (100, 500, 1000)
![standard_scaler](https://user-images.githubusercontent.com/38173800/84329226-c2decb80-abb6-11ea-8bfa-9d4429d18f8a.JPG)

I tried to install mlprodict directly from github to try out the new TreeEnsembleRegressorDouble but I'm getting ModuleNotFoundError: No module named 'mlinsights'.

Here's my code:
`
import os
import onnx
import mlprodict
import numpy as np
import pandas as pd
import onnxruntime as rt
from math import sqrt
from onnx import helper
from mlprodict.onnx_conv import to_onnx
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor


datasets = ["sample_0to1.csv",
            "sample_0to100.csv",
            "sample_0to1000.csv"]
x_cols = [
    'SegmentTravelTime',
    'NumberOfPassengers',
    'BookingHour',
    'TripFirstTravelDateHour',
    'SegmentFirstTravelDateHour',
    'TripDays',
    'DaysBetweenLoggedandTripDate',
    'DaysBetweenLoggedandSegmentDate',
    'DaysBetweenLoggedandNextFlight',
    'TotalFare'
]
y_cols = ['PredictedValue']
ntrees = [100, 500, 1000]

i = datasets[0]
j = ntrees[0]
data = pd.read_csv(i)
data_x = data[x_cols].astype(np.float32)
data_y = data[y_cols]

model = Pipeline([
    ('prep', ColumnTransformer([
        ('prep1', 'passthrough', x_cols)
    ])),
    ('model', RandomForestRegressor(n_estimators=j))
])
model.fit(data_x, data_y)
skl_PredictedValue = pd.DataFrame(model.predict(data_x),
                                  columns=['skl_PredictedValue'])
data_x = pd.concat([data_x.reset_index(drop=True), skl_PredictedValue],
                   axis=1)

onnx64 = to_onnx(model, data_x[x_cols][:1].astype(np.float64),
                 dtype=np.float64,
                 rewrite_ops=True)
`

**Comment by xadupre** [comment]
Sorry for that, pip install mlinsights should work. I'll fix that in the next release. I mostly use this package to investigate issues with converter, so TreeEnsembleRegressorDouble  is only available in mlprodict but not in onnxruntime. That's why I came up with the CastTransformer. The discrepencies with the passthrough are worrying but it seems related to the same kind of issue. To be more specific, scikit-learn uses a mix of float and double in their implementation that's why there exists a way to have only float in the runtime but it means the onnx node have slightly different threshold than the scikit-learn'one (transformed by the function http://www.xavierdupre.fr/app/mlprodict/helpsphinx/notebooks/onnx_float_double_skl_decision_trees.html#good-threshold). Let me know what you get with TreeEnsembleRegressorDouble.

**Comment by lcmanahan** [comment]
Hi again. I was testing the new CastTransformer. I found that I can't use it as part of a ColumnTransformer because it always expects a numpy array as input. Is this behavior expected? Will it be possible to use CastTransformer as part of a ColumnTransformer?

My Code:
i = "sample_0to1000.csv"
x_cols = [
    'SegmentTravelTime',
    'NumberOfPassengers',
    'BookingHour',
    'TripFirstTravelDateHour',
    'SegmentFirstTravelDateHour',
    'TripDays',
    'DaysBetweenLoggedandTripDate',
    'DaysBetweenLoggedandSegmentDate',
    'DaysBetweenLoggedandNextFlight',
    'TotalFare'
]
y_cols = ['PredictedValue']
j = 1000

data = pd.read_csv(i)
data_x = data[x_cols].astype(np.float32)
data_y = data[y_cols]

model = Pipeline([
    ('prep', ColumnTransformer([
        ('prep1', CastTransformer(), x_cols)
    ])),
    ('model', RandomForestRegressor(n_estimators=j))
])
model.fit(data_x, data_y)

The error:
TypeError: X must be a numpy array.

**Comment by lcmanahan** [comment]
I also verified if there are still discrepancies in the predicted values. Unfortunately, I'm still seeing values as high as 0.009179687500363798. I was expecting to see similar results between DecisionTreeRegressor and RandomForestRegressor.

sample_0to1000_CastTransformer_DecisionTreeRegressor
rmse: 3.1518419217296634e-06
rrmse: 6.31035072900452e-10
max(diff): 8.138020848491578e-05

sample_0to1000_CastTransformer_RandomForestRegressor_1000ntrees
rmse: 0.0026359094428438225
rrmse: 5.287744351426407e-07
max(diff): 0.009179687500363798

[CastTransformer_tests.zip](https://github.com/microsoft/onnxruntime/files/4848776/CastTransformer_tests.zip)

**Comment by xadupre** [comment]
I fixed the issue with CastTransformer (see https://github.com/xadupre/sklearn-onnx/commit/97b3711c8b9d1ef6705e57b6a3811a56392d9941). I'm not able to replicate your discrepencies. I summarized what I believe is your issue as an example in a tutorial: http://www.xavierdupre.fr/app/onnxcustom/helpsphinx/auto_examples/plot_ebegin_float_double.html.

**Comment by lcmanahan** [comment]
Thanks for the efforts in fixing this so far. I tried to confirm the effect of adding CastTransformer to the values returned by RandomForestRegressor. Here are the results that I got:

0to1_NoCast.onnx
rmse: 3.339997169102475e-07
rrmse: 6.77481341700119e-07
max(diff_NoCast): 6.461143493563526e-07

0to1_CastTransformer.onnx
rmse: 3.339997169102475e-07
rrmse: 6.77481341700119e-07
max(diff_CastTransformer): 6.461143493563526e-07

0to100_NoCast.onnx
rmse: 2.495720024431452e-05
rrmse: 4.918076198512377e-07
max(diff_NoCast): 0.00011118570962764807

0to100_CastTransformer.onnx
rmse: 2.495720024431452e-05
rrmse: 4.918076198512377e-07
max(diff_CastTransformer): 0.00011118570962764807

0to1000_NoCast.onnx
rmse: 0.002601175999289233
rrmse: 5.198789569426532e-07
max(diff_NoCast): 0.008893229166460515

0to1000_CastTransformer.onnx
rmse: 0.002601175999289233
rrmse: 5.198789569426532e-07
max(diff_CastTransformer): 0.008893229166460515

It looks like there is no change in the discrepancies when i added CastTransformer. I am attaching here my codes and the model pairs.
[Testing CastTransformer.zip](https://github.com/microsoft/onnxruntime/files/5025600/Testing.CastTransformer.zip)

Here are the versions of python packages that i used here:
onnxruntime 1.4.0
skl2onnx 1.7.0
sklearn 0.23.1
All installations were from Pypi.

**Comment by xadupre** [comment]
I fixed a couple of issues while writing the tutorial. The issue you mentioned about dataframes is already merged in master branch: https://github.com/onnx/sklearn-onnx/commit/46496215a03e2d94e402daa468a235ddbdd904bd. In your data, the predictions with ou without CastTransformer are exactly the same and that's expected because scikit-learn internally casts input in float32 before applying the trees. However, scikit-learn produces double predictions while ONNX produces floats predictions. So I would still expect discrepencies with a relative difference under 1e-6 (difference when a double is cast into a float). We checked the converter was producing predictions with this margin of error but not the exact same predictions.

**Comment by lcmanahan** [comment]
Thanks for clarifying where the remaining discrepancies are coming from. Given this limitation, we were wondering if you guys have any recommendations regarding what framework to use to avoid this issue but still be able to use ONNX with Random Forest?

**Comment by xadupre** [comment]
I implemented a class CastRegressor which casts the output of any regressor into the expected type (float32).  It works the same way as CastTransformer. Would that work for you?

```
from skl2onnx.sklapi import CastRegressor

ctree = CastRegressor(DecisionTreeRegressor(max_depth=max_depth), dtype=numpy.float32)
ctree.fit(Xi_train, yi_train)

onx6 = to_onnx(ctree, Xi_train[:1].astype(numpy.float32))

sess6 = InferenceSession(onx6.SerializeToString())

skl6 = ctree.predict(X32)
ort6 = sess6.run(None, {'X': X32})[0]

print(diff(skl6, ort6))  #(0.0, 0.0)
```

**Comment by lcmanahan** [comment]
I tested the CastRegressor but it didn't have an impact to the discrepancies. Here are the results that I got:
0to1_CastRegressor.onnx
rmse: 3.339997169102475e-07
rrmse: 6.77481341700119e-07
max(diff_CastRegressor): 6.461143493563526e-07

0to100_CastRegressor.onnx
rmse: 2.495720024431452e-05
rrmse: 4.918076198512377e-07
max(diff_CastRegressor): 0.00011118570962764807

0to1000_CastRegressor.onnx
rmse: 0.002601175999289233
rrmse: 5.198789569426532e-07
max(diff_CastRegressor): 0.008893229166460515

Attaching all relevant files.
[Testing CastRegressor.zip](https://github.com/microsoft/onnxruntime/files/5102695/Testing.CastRegressor.zip)

**Comment by lcmanahan** [comment]
Yup, I noticed that too. I also looked into what the discrepancies look like in GradientBoostingRegressor. Sharing the results and my codes here for your reference:
0to1_DecisionTree.onnx
rmse: 3.8474632833614055e-10
rrmse: 7.780512200933074e-10
max(diff_DecisionTree): 0.0

0to1_GradientBoosting.onnx
rmse: 2.4511591950441578e-08
rrmse: 4.9568436704634127e-08
max(diff_GradientBoosting): 8.58379602397541e-08

0to1_RandomForest.onnx
rmse: 3.339997169102475e-07
rrmse: 6.77481341700119e-07
max(diff_RandomForest): 6.461143493563526e-07

0to100_DecisionTree.onnx
rmse: 4.924753002702599e-08
rrmse: 9.713995764490555e-10
max(diff_DecisionTree): 0.0

0to100_GradientBoosting.onnx
rmse: 2.4671227669577828e-06
rrmse: 4.8663598145032524e-08
max(diff_GradientBoosting): 9.302958062562539e-06

0to100_RandomForest.onnx
rmse: 2.495720024431452e-05
rrmse: 4.918076198512377e-07
max(diff_RandomForest): 0.00011118570962764807

0to1000_DecisionTree.onnx
rmse: 3.1518419217296634e-06
rrmse: 6.31035072900452e-10
max(diff_DecisionTree): 8.138020848491578e-05

0to1000_GradientBoosting.onnx
rmse: 0.00026993112344467874
rrmse: 5.40433214580562e-08
max(diff_GradientBoosting): 0.0007351141066465061

0to1000_RandomForest.onnx
rmse: 0.002601175999289233
rrmse: 5.198789569426532e-07
max(diff_RandomForest): 0.008893229166460515

[Testing Discrepancies across Use Cases of TreeEnsembleRegressor.zip](https://github.com/microsoft/onnxruntime/files/5115279/Testing.Discrepancies.across.Use.Cases.of.TreeEnsembleRegressor.zip)

As you can see above, there is one DecisionTreeRegressor (the last one, largest range in dependent variable) that still showed some discrepancy. It is very minimal though.

**Comment by xadupre** [comment]
Quick question: what do you ``('prep1', CastTransformer(dtype=np.float64), x_cols)])),`` in your code and not ``('prep1', CastTransformer(dtype=np.float32), x_cols)])),``. It would work better with float32. For the random forest, it is another stories. sklearn does an average of double predictions, onnx does the same average with float predictions. *float32( sum_i x_i ) != sum_i ( float64( x_i))*

**Comment by manuelsilverio** [comment]
When I use a RandomForestClassifier, my onnx model predicts different values. If I go back to a decision tree classifier then it does not happen. Is it a bug or am I missing anything?
