### ISSUE TITLE
Add GetAvailableProviders to the C API

### ISSUE THREAD

**Issue by Craigacp** [microsoft/onnxruntime#4134]
**Is your feature request related to a problem? Please describe.**
The C API doesn't have a way to check what providers were compiled into the onnx-runtime binary. The Python API provides a pybind'd C++ function `GetAvailableProviders` which returns a string for each provider that has been compiled in.

**System information**
- ONNX Runtime version (you are using): 1.3.0

**Describe the solution you'd like**
GetAvailableProviders added to the C API, returning a char** pointing to a char* for each compiled provider. It looks like the Python one is missing a few providers (e.g. DirectML and ARM NN), so I'd like this method to support all the providers that are there, even if they are only preview features.

**Describe alternatives you've considered**
I can write similar code to the python one into the Java JNI binding, but all the language bindings will want this, so it should live in the C API.

**Comment by hariharans29** [comment]
There is some related discussion here: https://github.com/microsoft/onnxruntime/issues/2746
