### ISSUE TITLE
Can we please expose DisposableList as public

### ISSUE THREAD

**Issue by James-Bao** [microsoft/onnxruntime#4138]
**Is your feature request related to a problem? Please describe.**
I'm trying to follow the test code to consume DisposableList of FixedBufferOnnxValue in my service 
 when consuming ONNX runtime. However, I realized the DisposableList class is currently marked as internal. If the pattern used in the test code is the official recommendation for downstream users, why not expose it as public directly? 

**System information**
- ONNX Runtime version (you are using): 1.3.0

**Describe the solution you'd like**
Just simply expose the DisposableList as public.

**Describe alternatives you've considered**

**Additional context**

**Comment by yuslepukhin** [comment]
@James-Bao There is not an official recommendation of what the users should use in their tests code or in their production code. This is a utility class that helps us to run the tests and it is not a part of the official API that we support (I am not sure we should ship it).

If it was public we certainly would not you to link your code to our unit tests. Feel free to create your own class that implements the pattern.
