### ISSUE TITLE
Python issue to use the right Execution Provider for a specific model

### ISSUE THREAD

**Issue by danielecazzari** [microsoft/onnxruntime#4139]
**Describe the bug**
I build OnnxRuntime v1.3.0 with support for both TensorRT and Cuda. I'm currently testing a Model Zoo https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/faster-rcnn that fail to load with TensorRT but works with Cuda. 
Unfortunately, I did not found a solution to force to score it on Cuda with the TensorRt enabled on python. The issue is that you could specify an execution provider only after a session it's created and not before and this result in a session crash since TensorRT has an issue with that model (see log attached). [FastRCNNTest_out.txt](https://github.com/microsoft/onnxruntime/files/4734774/FastRCNNTest_out.txt)
The only way to make the model that I found on python it's to use a Cuda only enabled build but it is not a suitable option for me.
I also tried to check capi._pybind_state API but I only found a method to get the provider not to set them. 
Moreover, since there are more execution providers register I would expect a kind of retry mechanism with the second EP in the list if the first fail.

Could you help me with this issue?

Regards,

Daniele

**Comment by pranavsharma** [comment]
The following should work: ```sess = onnxrt.InferenceSession(get_name("model.onnx"), providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])```

**Comment by jywu-msft** [comment]
re: the TensorRT error, were you able to follow the steps in the error message
and run symbolic shape inference script on the model first?

1 : FAIL : TensorRT input: 867 has no shape specified. Please run shape inference on the onnx model first. Details can be found in https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/TensorRT-ExecutionProvider.md#shape-inference-for-tensorrt-subgraphs

**Comment by danielecazzari** [comment]
Thanks, Pranav as usually I looked everywhere except in the most obvious place :-).

About George's suggestion, this was something I tried with strange results that needed some review that I did today. 
My test tries to score 6 images on a folder, using TensorRT with  Model Zoo. 
Three of those images do not report any detection (while using CUDA the model score also those images). In addition, as you might see in the log attached (cc711673_sdout.log):
1) There are some errors (dimensions not compatible for concatenation, CHECK_BROADCAST, Shape Error in operator) that maybe is the reason not scored imaged.
2) Processing time it's very high for images that get scored 142 seconds against 1.8 max (see also 0a817ca6_sdout.log)
3) There are a lot of warnings

I was able to score on TensorRT with better FPS that on Cuda some Tiny Yolo v2 / v3 models but there are still some errors and warning on model zoo Tiny Yolo V3 (de72f21a_sdout.log) even if performance looks good and output seems consistent.

Logs are available here:
[Onnx_NVIDIA.zip](https://github.com/microsoft/onnxruntime/files/4748270/Onnx_NVIDIA.zip)

Thanks a lot
Daniele

**Comment by jywu-msft** [comment]
Faster RCNN from model zoo is supposed to run with OnnxRuntime + TensorRT EP.  This is why our documentation for running symbolic shape inference script references Faster RCNN from model zoo as example.
@stevenlix can you help look into why some of inputs are not returning detection (where CUDA provider does). @danielecazzari , please share repro case if possible.

re: high processing times, can you confirm whether this happens only for the first inference
and subsequent inferences are fast?
We need to build the TensorRT engine for each subgraph that gets assigned to TensorRT.
If the input shapes to the subgraphs are not known at session creation, then the TensorRT engines may need to be created at inference time. This can make the first inference slow.

**Comment by danielecazzari** [comment]
@jywu-msft my test script excludes already the first scoring for all models to ensure fair performance comparison. About my script, I'm currently working on it but I'm planning to publish them on a private GitHub repository in a couple of weeks. I could then provide access on a need basis.

Thanks a lot

Daniele
