### ISSUE TITLE
How to install cuDNN on Jetson Nano?

### ISSUE THREAD

**Issue by capriccioo** [microsoft/onnxruntime#4154]
From nvidia site page: developer.nvidia.com/rdp/cudnn-download, I can't find a cudnn lib package for arm64.
So, how to install cdDNN on an arm64 platform such as Jetson Nano?

**Comment by goloskokovic** [comment]
it's preinstalled with JetPack: /usr/lib/aarch64-linux-gnu
https://docs.nvidia.com/jetson/jetpack/introduction/index.html#libraries

**Comment by capriccioo** [comment]
> it's preinstalled with JetPack: /usr/lib/aarch64-linux-gnu
> https://docs.nvidia.com/jetson/jetpack/introduction/index.html#libraries

But I need a different version  of cuDNN

**Comment by jywu-msft** [comment]
it's not recommended to stray from the versions of nvidia libraries installed on that JetPack version.
if you really need a different version, you can use a different version of JetPack that supports it. 
what version of cuDNN do you want to use and why?

**Comment by capriccioo** [comment]
For some reason, I have to install  Pytorch1.5.0, then I have to use JetPack4.4. But onnxruntime does not support JetPack4.4 yet. I think it is because onnxruntime need cuDNN7.5 and cuDNN8.0 is installed on JetPack4.4.  
I am trying to build onnxruntime1.3.0 on JetPack4.4 following the discussion in ISSUE#3913.

**Comment by bycmlla** [comment]
> For some reason, I have to install Pytorch1.5.0, then I have to use JetPack4.4. But onnxruntime does not support JetPack4.4 yet. I think it is because onnxruntime need cuDNN7.5 and cuDNN8.0 is installed on JetPack4.4.
> I am trying to build onnxruntime1.3.0 on JetPack4.4 following the discussion in ISSUE#3913.

You know how i can know which version is my jetpack?
