### ISSUE TITLE
[WIP] New PyTorch frontend API

### ISSUE THREAD

**Issue by thiagocrepaldi** [microsoft/onnxruntime#4176]
This issue will track all tasks related to the development of the new PyTorch frontend API. Once this issue is merged, the new frontend will be available on master branch.

Implementation will follow the MS internal design that has been reviewed internally

**Comment by thiagocrepaldi** [comment]
https://github.com/microsoft/onnxruntime/pull/4220 introduces `ORTTrainerOptions`, `optim` and `amp` submodules, CI tests for the new frontend

**Comment by spandantiwari** [comment]
There are multiple PRs in flight for new PyTorch frontend API. Is there an order in which these PRs have to be merged?

**Comment by thiagocrepaldi** [comment]
> There are multiple PRs in flight for new PyTorch frontend API. Is there an order in which these PRs have to be merged?

Yes, from the "Linked pull requests" list on the right side of this issue page, we should merge the first 3 from top to bottom. The last 2 can be merged in any order after that

**Comment by thiagocrepaldi** [comment]
PRs already merged:
https://github.com/microsoft/onnxruntime/pull/4256
https://github.com/microsoft/onnxruntime/pull/4280
https://github.com/microsoft/onnxruntime/pull/4306
https://github.com/microsoft/onnxruntime/pull/4357
https://github.com/microsoft/onnxruntime/pull/4382
https://github.com/microsoft/onnxruntime/pull/4416
https://github.com/microsoft/onnxruntime/pull/4435
https://github.com/microsoft/onnxruntime/pull/4612
