### ISSUE TITLE
onnxruntime-gpu-tensorrt consumes too much memory

### ISSUE THREAD

**Issue by capriccioo** [microsoft/onnxruntime#4184]
**Describe the bug**
When I load a onnx model named version-RFB-320.onnx (about 1MB), it consumes about 5GB memory. The system offen crash because of this.

**System information**
-  Jetson Nano with JetPack4.4
- ONNX Runtime 1.3.0 installed from source:
- Python version: 3.6
- CUDA/cuDNN version: 10.2 , 8.0

**To Reproduce**
run python codes:
import onnxruntime as rt
import numpy as np
import cv2

model_path = './models/onnx/version-RFB-320.onnx'
img_path = '../qlb.jpg'
orig_image = cv2.imread(img_path)

sess = rt.InferenceSession(model_path)

**Expected behavior**
Is the normal? Is there any way to reduce the memory consumption

**Comment by jywu-msft** [comment]
I assume it runs okay with CUDAExecutionProvider ?
i.e.
sess = rt.InferenceSession(model_path, providers=['CUDAExecutionProvider'])

currently TensorRTExecutionProvider consumes more memory and we will need to work on optimizing it, especially for small memory devices.

**Comment by capriccioo** [comment]
> I assume it runs okay with CUDAExecutionProvider ?
> i.e.
> sess = rt.InferenceSession(model_path, providers=['CUDAExecutionProvider'])
> 
> currently TensorRTExecutionProvider consumes more memory and we will need to work on optimizing it, especially for small memory devices.

not okay.
The memory consumed by TensorRTExecutionProvider can be set by environment variable ORT_TENSORRT_MAX_WORKSPACE_SIZE. 
If ORT_TENSORRT_MAX_WORKSPACE_SIZE was set to 256MB or less, CUDA consumes much more memory, about 1GB, and I don't know any way to reduce it.
If I run onnxruntime with CUDAExecutionProvider, it consumes about 1GB memory too.
So, the main problem is CUDA consumes too much memory not TensorRT
