### ISSUE TITLE
Build on RaspberryPi4b failed: requested alignment 16 is larger than 8

### ISSUE THREAD

**Issue by capriccioo** [microsoft/onnxruntime#4189]
**Describe the bug**
When building onnxruntime1.3.0 on RaspberryPi4b, I got many errors like this:
                   
error: requested alignment 16 is larger than 8 [-Werror=attributes]
     EIGEN_ALIGN_TO_BOUNDARY(sizeof(Packet)) float vals[PacketSize];

**System information**

- GCC/Compiler version: Raspbian 8.3.0-6+rpi1

**To Reproduce**
building command：
./build.sh --config Release --update --build --build_wheel 

**Expected behavior**
Does onnxruntime1.3.0 support GCC8.3.0 or 32bit Linux?

**Comment by capriccioo** [comment]
I successfully build it by GCC8.3 with option --arm after add two lines in CMakeFilelist.txt:
string(APPEND CMAKE_CXX_FLAGS " -latomic")
string(APPEND CMAKE_C_FLAGS " -latomic")

Then I tryed to built it by GCC7.3 without option --arm or --arm64 and succeeded after add the above two lines in CMakeFileList.txt

**Comment by danielgoncalvesti** [comment]
I am facing the same issue, so where could I find the CMakeFilelist.txt file? 
That file doesn't exist on the onnxruntime project.

**Comment by snnn** [comment]
> I am facing the same issue, so where could I find the CMakeFilelist.txt file?
> That file doesn't exist on the onnxruntime project.

In the cmake folder
