### ISSUE TITLE
Is there a programmatic way to get max supported ONNX version and opset

### ISSUE THREAD

**Issue by GuanLuo** [microsoft/onnxruntime#4191]
If I build the C shared library from source, I assume that information is somewhere in the build process and I wonder if those information are exposed in the build (or in the library).

**Comment by pranavsharma** [comment]
Curious what's your use to get this info programmatically?

**Comment by GuanLuo** [comment]
We use ORT in our Docker container and we want to set those as environment variables so that user can quickly check if the model failure is due to incompatibility.
