### ISSUE TITLE
When will the new experimental API for customOps be stable?

### ISSUE THREAD

**Issue by CoderHam** [microsoft/onnxruntime#4192]
**Is your feature request related to a problem? Please describe.**
For the last few releases the [docs](https://github.com/microsoft/onnxruntime/blob/v1.3.0/docs/AddingCustomOp.md) for customOps state that:
"These APIs are experimental and will change in the **next** release."

**System information**
- ONNX Runtime version 1.3.0:

**Describe the solution you'd like**
I would love to know when this API will be out of the experimental phase and stable to use. 

**Describe alternatives you've considered**
Will the older RegisterCustomRegistry API be deprecated when this move happens?

**Additional context**
We are asking because we wish to add support for custom ops to the [Triton Inference Server](https://github.com/NVIDIA/triton-inference-server).

**Comment by CoderHam** [comment]
@pranavsharma could you confirm if the C++ ONNXRT API allow loading multiple custom op libraries in the same session via `RegisterCustomOpsLibrary`?

**Comment by pranavsharma** [comment]
You could call RegisterCustomOpsLibrary multiple times to load multiple custom op libs. We've not tested it though.
