### ISSUE TITLE
pytorch to onnx discrepancies

### ISSUE THREAD

**Issue by natangold85** [microsoft/onnxruntime#4202]
**Describe the bug**
Hey, im trying to convert a pytorch model to onnx. i have difficulties in converting part of the model to onnx. i isolated the line that causing the difficulties:

    def forward(self, bev_lut: torch.Tensor) -> torch.Tensor:
        return bev_lut[:, ::2, ::2, :]

There is several issues in this line that made me think that i'm doing something wrong:

1: When export the model using torch.onnx.export the name of output is becoming also the name of the input as its the same variable.

2: When changing the name of the output to be the same name as the input the input change his dimensions to be the same dimensions as the output.

3: When running onnx.checker.check_model on the model the output is:
**UserWarning: ONNX export failed on slice because step!=1 is currently not supported not supported**

**Urgency**
my team needs to present lane detector on our target  in a week which requires a complete onnx model.

**System information**
for converting torch to onnx i'm running python 3.6.8 on linux with pytorch 1.3.0, onnxruntime 1.3.0 and onnx 1.7.0

**To Reproduce**
you can run this code:

    import onnx
    import torch
    import onnxruntime
    import torch.nn as nn

    class BEVLayer_test(nn.Module):
        def __init__(self):
            super().__init__()

        def forward(self, bev_lut: torch.Tensor) -> torch.Tensor:
            return bev_lut[:, ::2, ::2, :]

    bev_lut = torch.rand(1,52,32,2)

    in_key = "bev_lut"
    out_key = "output"

    test_model = BEVLayer_test()
    torch.onnx.export(test_model, (bev_lut), "/tmp/test.onnx", input_names=[in_key], output_names = [out_key])

    model = onnx.load_model("/tmp/test.onnx")
    onnx.checker.check_model(model)

    onnx_module = onnxruntime.InferenceSession("/tmp/test.onnx")

    model_input = {in_key : bev_lut.numpy()}
    out_tmp = onnx_module.run([out_key], model_input)

    out_onnx = torch.from_numpy(out_tmp[0])
    out_torch = test_model.forward( bev_lut)

**Expected behavior**
out_onnx == out_torch

**Comment by tianleiwu** [comment]
@natangold85, please append a parameter during calling torch.onnx.export():`opset_version=12`
The default version is 11.

**Comment by natangold85** [comment]
thanks, thats indeed solved the issue.

**Comment by natangold85** [comment]
thanks, thats indeed solved the issue.
