### ISSUE TITLE
Citing ONNX Runtime in an academic publication

### ISSUE THREAD

**Issue by xgirones** [microsoft/onnxruntime#4203]
What is the proper way to cite ORT in an academic article? Do you have a recommended way?

 In the case of ONNX they propose this

https://github.com/onnx/onnx/issues/1441#issuecomment-508594407

**Comment by hariharans29** [comment]
CC: @faxu @pranavsharma

**Comment by fcakyon** [comment]
@hariharans29 @faxu @pranavsharma how to cite this library in an academic paper?

**Comment by faxu** [comment]
You can use 

@misc{onnxruntime,
  title={ONNX Runtime},
  author={ONNX Runtime developers},
  year={2021},
  howpublished={\url{https://www.onnxruntime.ai}},
  note={Version: x.y.z}
}
