### ISSUE TITLE
Bug in onnxruntime\onnxruntime\core\providers\acl\nn\conv.cc?

### ISSUE THREAD

**Issue by capriccioo** [microsoft/onnxruntime#4209]
**Describe the bug**
arm_compute::NEDepthwiseConvolutionLayer3x3> is used in onnxruntime\onnxruntime\core\providers\acl\nn\conv.cc line 211:
auto layer = std::make_shared<arm_compute::NEDepthwiseConvolutionLayer3x3>();

but I searched the definition of NEDepthwiseConvolutionLayer3x3 in the repository  ARM-software/ComputeLibrary and got nothing.

**System information**
- ONNX Runtime version: 1.3.0
- 

**To Reproduce**
When building onnxruntime with option --use_acl, I got the error below:
/home/test/code/onnxruntime/onnxruntime/core/providers/acl/nn/conv.cc:211:52: error: ‘NEDepthwiseConvolutionLayer3x3’ is not a member of ‘arm_compute’
         auto layer = std::make_shared<arm_compute::NEDepthwiseConvolutionLayer3x3>();

**Expected behavior**
Is this a bug or i had done something wrong?

**Comment by goloskokovic** [comment]
https://github.com/ARM-software/ComputeLibrary/blob/master/arm_compute/core/NEON/kernels/NEDepthwiseConvolutionLayer3x3Kernel.h

**Comment by capriccioo** [comment]
No definition of NEDepthwiseConvolutionLayer3x3 in this file.

**Comment by goloskokovic** [comment]
try using ComputeLibrary v19.08 
https://github.com/ARM-software/ComputeLibrary/blob/v19.08/arm_compute/runtime/NEON/functions/NEDepthwiseConvolutionLayer.h

**Comment by capriccioo** [comment]
Thanks.
I downloaded ComputeLibrary v19.08 and compiled it and then build onnxruntime with option --use_acl almost successfully. I got error at the last step: build_wheel:

Running subprocess in '/home/test/code/onnxruntime/build/Linux/Release'
['/usr/bin/python3', '/home/test/code/onnxruntime/setup.py', 'bdist_wheel', '--use_acl']
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --use_acl not recognized

If the build wheel manually: python3 /home/test/code/onnxruntime/setup.py bdist_wheel,
I got a whl file which is identical to the file build without option "--use_acl". onnxruntime with ACL is not support python?

**Comment by goloskokovic** [comment]
--use_acl is specified in build.py, but not parsed in setup.py
https://github.com/microsoft/onnxruntime/blob/v1.3.0/setup.py#L68

**Comment by capriccioo** [comment]
I know this. 
What confused me is the whl files generated by two ways below are exactly same:
1. ./build.sh --config Release --update --build --build_wheel --use_acl;
    python3 /home/test/code/onnxruntime/setup.py bdist_wheel
2. ./build.sh --config Release --update --build --build_wheel

the output whl files have not only the same filename, but also the same size.
And when I install them and run my python code for performance test , they have the same performance.

So I am wondering:  does onnxruntime with ACL support python?
Also I have the same question on onnxruntime with armnn.

**Comment by goloskokovic** [comment]
easiest way to find out is to print available providers:
https://microsoft.github.io/onnxruntime/python/api_summary.html#onnxruntime.InferenceSession.get_providers

**Comment by capriccioo** [comment]
sess.get_providers() shows thers is only CPUExecutionProvider.
So how to build a whl file which has ACLExecutionProvider?

**Comment by goloskokovic** [comment]
https://github.com/microsoft/onnxruntime/blob/master/cmake/onnxruntime_python.cmake#L82

**Comment by goloskokovic** [comment]
> sess.get_providers() shows thers is only CPUExecutionProvider.
> So how to build a whl file which has ACLExecutionProvider?

also print providers from onnxruntime not session to be sure. as in session are providers you set and in onnxruntime are available from the build

**Comment by capriccioo** [comment]
> > sess.get_providers() shows thers is only CPUExecutionProvider.
> > So how to build a whl file which has ACLExecutionProvider?
> 
> also print providers from onnxruntime not session to be sure. as in session are providers you set and in onnxruntime are available from the build

I still have no idea how to use ACLExecutionProvider in python...

**Comment by goloskokovic** [comment]
@jywu-msft 
https://github.com/microsoft/onnxruntime/pull/3586

**Comment by capriccioo** [comment]
> @jywu-msft
> #3586

I build onnxruntime by command line:
./build.sh --use_acl

An error came out at the last step:

[100%] Linking CXX executable onnxruntime_test_all
[100%] Built target onnxruntime_test_all
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/home/test/code/onnxruntime/tools/ci_build/build.py", line 1805, in <module>
    sys.exit(main())
  File "/home/test/code/onnxruntime/tools/ci_build/build.py", line 1700, in main
    build_targets(args, cmake_path, build_dir, configs, args.parallel)
  File "/home/test/code/onnxruntime/tools/ci_build/build.py", line 868, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/test/code/onnxruntime/tools/ci_build/build.py", line 402, in run_subprocess
    env=my_env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/test/code/onnxruntime/build/Linux/Debug', '--config', 'Debug', '--', '-j4']' returned non-zero exit status 2.

**Comment by jywu-msft** [comment]
which version of ACL are you using?
If you use ACL version 19.08 you need to specify it.
see: https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/build.py#L336
it defaults to ACL_1905
so you would need to use --use_acl=ACL_1908

**Comment by capriccioo** [comment]
Still no whl file generated.
All I want to know is how to use ACLExecutionProvider in python...

**Comment by goloskokovic** [comment]
try adding [here](https://github.com/microsoft/onnxruntime/blob/v1.3.0/setup.py#L68):
`elif '--use_acl' in sys.argv:`
`package_name = 'onnxruntime-acl'`
`sys.argv.remove('--use_acl')`

**Comment by jywu-msft** [comment]
@capriccioo , if you're still encountering issues, can you please provide full logs and details for reproducing?
@prabhat00155 has been testing ACL on onnxruntime and can probably provide some tips and guidance.

**Comment by capriccioo** [comment]
> repeat every step as for [DML](https://github.com/microsoft/onnxruntime/pull/3359/files)
> rename [onnxruntime_pybind_state.txt](https://github.com/microsoft/onnxruntime/files/4778144/onnxruntime_pybind_state.txt) to onnxruntime_pybind_state.cc

I downloaded the master branch of onnxruntime, then build onnxruntime:
 ./build.sh --config Release --update --build --build_wheel --use_acl --parallel --skip_test
After the build finished, I got a whl file:
onnxruntime_ACL_1905-1.3.1-cp36-cp36m-linux_aarch64.whl
I installed it and import onnxruntime in python, I got an error message:

_/home/test/.local/lib/python3.6/site-packages/onnxruntime/capi/_pybind_state.py:14: UserWarning: Cannot load onnxruntime.capi. Error: '/home/test/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so: undefined symbol: _ZN11onnxruntime34CreateExecutionProviderFactory_ACLEi'.
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'.".format(str(e)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/test/.local/lib/python3.6/site-packages/onnxruntime/__init__.py", line 13, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
ImportError: cannot import name 'get_all_providers'_

**Comment by capriccioo** [comment]
I build onnxruntime with option --use_acl=ACL_1908 （I intalled ComputerLibrary19.08）, and I got the same error when import onnxruntime in python.

**Comment by goloskokovic** [comment]
looks like calling [CreateExecutionProviderFactory_ACL](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/acl/acl_provider_factory.cc#L34) is making this problem.
go to onnxruntime_pybind_state.cc#L438 and set: 
onnxruntime::CreateExecutionProviderFactory_ACL(1)

**Comment by capriccioo** [comment]
> kAclExecutionProvider missing in onnxruntime_pybind_state.cc#L276: all_providers
> 
> ~looks like calling [CreateExecutionProviderFactory_ACL](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/acl/acl_provider_factory.cc#L34) is making this problem. go to onnxruntime_pybind_state.cc#L438 and set: onnxruntime::CreateExecutionProviderFactory_ACL(1)~
> 
> also check if you have in onnxruntime_pybind_state.cc#L345:
> } else if (type == kAclExecutionProvider) {

What do you mean?
I checked onnxruntime_pybind_state.cc and found:
	_else if (type == kAclExecutionProvider) {_
_#ifdef USE_ACL_
		_RegisterExecutionProvider(sess, *onnxruntime::CreateExecutionProviderFactory_ACL(0));
#endif
	}_

Should I modify the "0" here to "1"?
Should I modify the "0" in onnxruntime_pybind_state.cc#L438 to "1"?

**Comment by goloskokovic** [comment]
> 
> 
> > kAclExecutionProvider missing in onnxruntime_pybind_state.cc#L276: all_providers
> > ~looks like calling [CreateExecutionProviderFactory_ACL](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/acl/acl_provider_factory.cc#L34) is making this problem. go to onnxruntime_pybind_state.cc#L438 and set: onnxruntime::CreateExecutionProviderFactory_ACL(1)~
> > also check if you have in onnxruntime_pybind_state.cc#L345:
> > } else if (type == kAclExecutionProvider) {
> 
> What do you mean?
> I checked onnxruntime_pybind_state.cc and found:
> _else if (type == kAclExecutionProvider) {_
> _#ifdef USE_ACL_
> _RegisterExecutionProvider(sess, *onnxruntime::CreateExecutionProviderFactory_ACL(0)); #endif }_
> 
> Should I modify the "0" here to "1"?
> Should I modify the "0" in onnxruntime_pybind_state.cc#L438 to "1"?

try first to add kAclExecutionProvider to all_providers in onnxruntime_pybind_state.cc#L276

**Comment by jywu-msft** [comment]
@goloskokovic , thanks a lot for your help and providing the necessary changes.
@capriccioo , python bindings were not yet added for AclExecutionProvider , but @goloskokovic showed the way.
once it's validated to work, you guys should contribute the changes. thanks!

**Comment by capriccioo** [comment]
> kAclExecutionProvider missing in onnxruntime_pybind_state.cc#L276: all_providers
> looks like calling CreateExecutionProviderFactory_ACL is making this problem. go to onnxruntime_pybind_state.cc#L438 and set: onnxruntime::CreateExecutionProviderFactory_ACL(1)
> also check if you have in onnxruntime_pybind_state.cc#L345:
> } else if (type == kAclExecutionProvider) {
> 
> What do you mean?
> I checked onnxruntime_pybind_state.cc and found:
> else if (type == kAclExecutionProvider) {
> #ifdef USE_ACL
> RegisterExecutionProvider(sess, *onnxruntime::CreateExecutionProviderFactory_ACL(0)); #endif }
> Should I modify the "0" here to "1"?
> Should I modify the "0" in onnxruntime_pybind_state.cc#L438 to "1"?
> 
> try first to add kAclExecutionProvider to all_providers in onnxruntime_pybind_state.cc#L276

All the modifications metioned above doesn't work.

**Comment by goloskokovic** [comment]
@jywu-msft
https://github.com/microsoft/onnxruntime/issues/2572

**Comment by jywu-msft** [comment]
> @jywu-msft
> #2572 #4196
> UserWarning: Cannot load onnxruntime.capi. Error: '/home/test/.local/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so: undefined symbol: _ZN11onnxruntime34CreateExecutionProviderFactory_ACLEi'.

those linked issues are unrelated.
issue encountered is missing symbol for CreateExecutionProviderFactory_ACL

I think libproviders_acl.a wasn't linked into onnxruntime_pybind_state.so (you can use nm to confirm the symbol is missing)

check that ${PROVIDERS_ACL} is added to onnxruntime_python.cmake and rebuild.
e.g. see https://github.com/microsoft/onnxruntime/blob/master/cmake/onnxruntime_python.cmake#L95

I think the DML example for adding python support is not a good one as it doesn't seem to have all the required steps.

**Comment by goloskokovic** [comment]
https://github.com/microsoft/onnxruntime/blob/master/cmake/onnxruntime_python.cmake#L82

**Comment by capriccioo** [comment]
Finally I run ACL in python sucessfully.
First, repeat every step as for [DML](https://github.com/microsoft/onnxruntime/pull/3359/files)
Second, add "${PROVIDERS_ACL}" to onnxruntime_python.cmake#L95.
Then build and install and import onnxruntime in python.

I think there is memory leak in ACL.
I run a model again and again , the program consumed more and more memory.
If I choose CPUExecutionProvider, no memory leak.

**Comment by prabhat00155** [comment]
> Finally I run ACL in python sucessfully.
> First, repeat every step as for [DML](https://github.com/microsoft/onnxruntime/pull/3359/files)
> Second, add "${PROVIDERS_ACL}" to onnxruntime_python.cmake#L95.
> Then build and install and import onnxruntime in python.
> 
> I think there is memory leak in ACL.
> I run a model again and again , the program consumed more and more memory.
> If I choose CPUExecutionProvider, no memory leak.

Can you share the steps to reproduce memory leak with ACL?

**Comment by capriccioo** [comment]
import numpy as np
import cv2
import onnxruntime as rt
model_path = './models/onnx/version-RFB-320.onnx'
img_path = 'dh6.jpg'
orig_image = cv2.imread(img_path)
so = rt.SessionOptions()
sess = rt.InferenceSession(model_path, sess_options=so, providers=['ACLExecutionProvider'])
input_name = sess.get_inputs()[0].name
label = sess.get_outputs()[0].name
box = sess.get_outputs()[1].name

image = cv2.cvtColor(orig_image, cv2.COLOR_BGR2RGB)
image = (cv2.resize(image, (320, 240)) - 127.0)/128

image = np.transpose(image, [2, 0, 1])
image = np.expand_dims(image, axis=0)
image = image.astype(np.float32)

for i in range(1000):
    t0=time.time()
    confidences, boxes = sess.run(None, {input_name: image})
    print(time.time()-t0)

I was watching the memory usage when the last four lines was running. The memory usage was going up linearly.
