### ISSUE TITLE
support running inference on CPU machine with lib built on GPU machine?

### ISSUE THREAD

**Issue by ericxsun** [microsoft/onnxruntime#4225]
**Describe the bug**
When starting inference on CPU machine(no cuda, no tensorRT) with package(java side) built with cuda-10.0. An error ` libcublas.so.10.0: cannot open shared object file: No such file or directory` occurred. However, it was all right when run it on a machine with GPU.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.3.0
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by pranavsharma** [comment]
If you’re using the GPU package (binary) you need to ensure it’s dependencies are installed on the machine in a location that can be found by the system while loading. The GPU binary depends on the cuda shared libraries. We don’t have a way today for the GPU binary to work on the CPU without the dependencies pre installed. Hope this helps.

**Comment by ericxsun** [comment]
> If you’re using the GPU package (binary) you need to ensure it’s dependencies are installed on the machine in a location that can be found by the system while loading. The GPU binary depends on the cuda shared libraries. We don’t have a way today for the GPU binary to work on the CPU without the dependencies pre installed. Hope this helps.

I found that there are many `api providers` are implmented in [providers](https://github.com/microsoft/onnxruntime/tree/master/include/onnxruntime/core/providers), e.g., cpu, cuda, tensorrt etc. I'm wondering is that possible to add a env-config or flag to tell the binary-lib which `api provider` should be used? I could try if one can give some valuable clues
