### ISSUE TITLE
Build on Raspberry Pi4 failed 

### ISSUE THREAD

**Issue by danielgoncalvesti** [microsoft/onnxruntime#4226]
**Describe the bug**
I tried to build ARM package on my raspberry Pi 4, following the instruction [Build.md](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#native-compiling-on-linux-arm-device) but I got the following error after this command: `./build.sh --config MinSizeRel --update --build
```/usr/bin/ld: any.cc:(.text.startup+0x4c): undefined reference to std::ios_base::Init::~Init()'
collect2: error: ld returned 1 exit status
make[2]: *** [external/protobuf/cmake/CMakeFiles/protoc.dir/build.make:87: external/protobuf/cmake/protoc-3.11.3.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:1146: external/protobuf/cmake/CMakeFiles/protoc.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Traceback (most recent call last):
  File "/home/pi/devel/code/onnxruntime/tools/ci_build/build.py", line 1826, in <module>
    sys.exit(main())
  File "/home/pi/devel/code/onnxruntime/tools/ci_build/build.py", line 1716, in main
    build_targets(args, cmake_path, build_dir, configs, args.parallel)
  File "/home/pi/devel/code/onnxruntime/tools/ci_build/build.py", line 871, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/pi/devel/code/onnxruntime/tools/ci_build/build.py", line 405, in run_subprocess
    env=my_env, shell=shell)
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/home/pi/devel/code/onnxruntime/build/Linux/MinSizeRel', '--config', 'MinSizeRel']' returned non-zero exit status 2.
```
**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian GNU/Linux 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master (6f4320fb856acb849c22dfccbebf8455305986b1)
- Python version: 3.7
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): gcc version 7.3.0 (Raspbian 7.3.0-19) 
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**To Reproduce**
Docker build runs on a Raspberry Pi 3B with Raspbian Stretch Lite OS (Desktop version will run out memory when linking the .so file) will take 8-9 hours in total.
```bash
sudo apt-get update
sudo apt-get install -y \
    sudo \
    build-essential \
    curl \
    libcurl4-openssl-dev \
    libssl-dev \
    wget \
    python3 \
    python3-pip \
    python3-dev \
    git \
    tar

pip3 install --upgrade pip
pip3 install --upgrade setuptools
pip3 install --upgrade wheel
pip3 install numpy

# Build the latest cmake
mkdir /code
cd /code
wget https://cmake.org/files/v3.13/cmake-3.13.5.tar.gz;
tar zxf cmake-3.13.5.tar.gz

cd /code/cmake-3.13.5
./configure --system-curl
make
sudo make install

# Prepare onnxruntime Repo
cd /code
git clone --recursive https://github.com/Microsoft/onnxruntime

# Start the basic build
cd /code/onnxruntime
./build.sh --config MinSizeRel --update --build
```

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by snnn** [comment]
If you want something faster, see below:
https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#cross-compiling-on-linux-1

It takes no more than 10 minutes

**Comment by Devinml** [comment]
Are there any workarounds available?

**Comment by snnn** [comment]
> Are there any workarounds available?

https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#cross-compiling-on-linux-1

**Comment by Devinml** [comment]
Thanks for the response could you elaborate more?

**Comment by snnn** [comment]
Instead of building onnxruntime on the device, I suggest you do it on a PC, which is usually about 1000x faster than rPi. You can firstly build a package on the PC, then transfer the binary to rPi and install it.

**Comment by Devinml** [comment]
Ah ok. I was trying to use the Docker container for the Rpi 3 but that doesn't seem to work.
