### ISSUE TITLE
How to build C++ api for Nvidia Jetson TX2

### ISSUE THREAD

**Issue by chaitanyarit** [microsoft/onnxruntime#4235]
I want to use the onnx runtime using C++ API in Jetson TX2. What are the exact steps that are to be followed to use the c++ api ( similar to the instructions to build .whl file for python api given [here](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#TensorRT)). Will using --build_csharp flag during build be used to generate these.  Should I follow these [1](https://github.com/microsoft/onnxruntime/blob/master/docs/C_API.md#c-api) and [2](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp) . Any help would be great.

**Comment by pranavsharma** [comment]
Build using --build_shared flag. That should create a shared lib and you can use onnxruntime_cxx_api.h to integrate with ORT.

**Comment by faxu** [comment]
@chaitanyarit Do you need further assistance? If not, please close the issue, thanks!
