### ISSUE TITLE
running a model cause bus error

### ISSUE THREAD

**Issue by natangold85** [microsoft/onnxruntime#4245]
**Describe the bug**
Hey, i'm working with onnxruntime on c++ on qnx operating system.
I already compiled onnxruntime to qnx. i'm now trying to run the model and i get a bus error while running the model.

this is the terminal error message:
start module forward input num = 1, output num = 5
creating a tensor with size = 1440000 shape equal = 1, 3,300,400, name = x
running the model

Process 8433694 (testNNResnet.gtest) terminated SIGBUS code=1 fltno=5 ip=0000676e69737365
Bus error (core dumped)

**Urgency**
my team needs to present running the model on out board tomorow

**System information**
qnx os. onnxruntime build from source with modifications to adjust qnx.
onnxruntime built on latest master.
my compiler is qcc based on gcc 5.4.0.

**Expected behavior**
to run a model without crashing

**Additional context**

**this how i init the memory info that is given in the creation of the input:**
Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU);

**this is my code loading the model:**
Ort::Env env(ORT_LOGGING_LEVEL_VERBOSE, "test");

// initialize session options if needed
Ort::SessionOptions session_options;
session_options.SetIntraOpNumThreads(1);
module = std::make_shared<Ort::Session>(env, path.c_str(), session_options);

**this is my code running the model:**
auto outputs = module->Run(Ort::RunOptions{nullptr}, &input_name, inputTensor4Onnx, 1, 
                                        outputNames.data(), outputNames.size());

**Comment by mrry** [comment]
@natangold85 Can you please share a stack trace showing where the code crashed (e.g. from the core dump)? That will help us to locate the component responsible.

**Comment by natangold85** [comment]
never mind i solved it. apparently Ort::Env env should be exist while the session exist and that can only be one env for the two session i inferred.

**Comment by TomSpeedy** [comment]
> never mind i solved it. apparently Ort::Env env should be exist while the session exist and that can only be one env for the two session i inferred.

Thank you, had the same issue and was completely clueless. You saved my day, fellow programmer. <3
