### ISSUE TITLE
Samples for ORTTraining lack instructions and data

### ISSUE THREAD

**Issue by migueldeicaza** [microsoft/onnxruntime#4249]
The samples in onnxruntime/orttraining/orttraining/models lack instructions on how to use it, and in some cases, the models that are actually required to use them.

I tried the `mnist` sample, and had to get the data on my own, and get the model on my own, just to find that the models that are referenced only exist in internal Microsoft repos.    We should have instructions on how to take these for a spin.

**Comment by suffiank** [comment]
We need to make these more complete by adding basic documentation and working copies of models. 

As an aside, it's worth pointing out there is now an examples repository at [microsoft/onnxruntime-training-examples](https://github.com/microsoft/onnxruntime-training-examples). So far the intent is different as if adapts NVIDIA's BERT PyTorch example and Huggingface's GPT2 PyTorch example to train on the onnxruntime using the PyTorch ONNX graph export feature.
