### ISSUE TITLE
Microsoft.ML.OnnxRuntime libraries fails to load (dotnet-aspnetcore linux container usage)

### ISSUE THREAD

**Issue by sof** [Microsoft/onnxruntime#425]
**Describe the bug**
When attempting to use Microsoft.ML.OnnxRuntime from within an ASP.NET dotnet core runtime docker container (linux), the onnxruntime .so fails to load due to a missing libgomp1.so dependency.

A workaround is described below, but it might be worth considering if the nuget packaging should also include (all of) libgomp also. Or document the potential issue when attempting to use onnxruntime from smaller Docker base images.

(
I couldn't find any issue or documentation on the topic, my apologies if I overlooked something; reported in case it has (time saving) value for anyone else running into this.
)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows10 host OS, linux container (with microsoft/dotnet:2.1.7-aspnetcore-runtime-bionic as base)
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 0.2.1(nuget package, C# usage)
- Python version: n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**To Reproduce**
Create a ASP.NET dotnet core webapi dotnet core Docker container, adding

```
   var session = new InferenceSession("some.onnx");
```

to Main(). Run the docker container from the MSVS debugger and observe the exception triggered.

**Expected behavior**
Instantiation of InferenceSession to succeed, and not fail with a DLL loading failure exception from onnxruntime.dll (or one of its dependent libraries)

**Screenshots**

**Additional context**
If you exec into the container and ldd the .so's of the package, I see the following:

```
root@888c356a3e9c:/app# ldd /root/.nuget/packages/microsoft.ml.onnxruntime/0.2.1/runtimes/linux-x64/native/onnxruntime.so
        linux-vdso.so.1 (0x00007ffe763b2000)
        libmkldnn.so.0 => /root/.nuget/packages/microsoft.ml.onnxruntime/0.2.1/runtimes/linux-x64/native/libmkldnn.so.0 (0x00007efd6aa25000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007efd6a821000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007efd6a498000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efd6a0fa000)
        libgomp.so.1 => not found
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007efd69ee2000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007efd69cc3000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efd698d2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007efd6bc29000)
        libgomp.so.1 => not found
root@888c356a3e9c:/app# 
```

The missing library dependency can be worked around for the base image in question by adding

```
RUN apt-get update && apt-get install -y libgomp1
```

to the Dockerfile.

**Comment by snnn** [comment]
If we put it there, one downside is: all other components in this process can not use OpenMP because the version provided by us may not match theirs. The same rule also applies to MKLDNN.
Thus, in general, I would suggest we shouldn't redistribute third party  dependencies in this way. This is Linux, not Windows. Linux manages shared libraries by using 'ldconfig'. They have a global registration. Usually they don't have "DLL hell".

**Comment by pranavsharma** [comment]
Resolving this as we don't plan to ship openmp as part of our packages. Please install openmp separately. See here for more details: https://github.com/Microsoft/onnxruntime#system-requirements
