### ISSUE TITLE
Unable to compile UWP project using .NET native with OnnxRuntime reference

### ISSUE THREAD

**Issue by joaomelo81** [microsoft/onnxruntime#4252]
**Describe the bug**
I'm unable to compile a UWP project that references the Microsoft.ML.OnnxRuntime (v.1.3.0) package when the "Compile with .NET Native tool chain" option is enabled.
The build fails with the following error: ILT0021: Could not resolve method 'EETypeRva:0x00047188'

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Version 1909 (OS Build 18363.900)
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.3.0
- Visual Studio version (if applicable): Visual Studio Enterprise 2017

**To Reproduce**
- Create an UWP project
- Add the Microsoft.ML.OnnxRuntime v1.3.0 NuGet package:
```
    <PackageReference Include="Microsoft.ML.OnnxRuntime">
      <Version>1.3.0</Version>
    </PackageReference>
```
- In the project's properties, mark the "Compile with .NET Native tool chain" checkbox in the "Build" section.

**Expected behavior**
The project should compile without any issues.

**Additional context**
The project compiles fine with "Compile with .NET Native tool chain" unchecked.

**Comment by rribani** [comment]
I'm facing the same issue.

**Comment by varadha-hp** [comment]
+1
Unable to compile Windows App with OnnxRuntime and .NET Native Compilation Enabled.
ILT0021: Could not resolve method 'EETypeRva:0x00047188

**Comment by joaomelo81** [comment]
Downgrading the ONNXRuntime version from 1.3.1 to 0.5.1 seems to compile fine with .NET native tool chain enabled, however it fails on application startup with the following generic error: "dependent .dll not found"

Any clue on which internal component of ONNXRuntime dependency could cause such issues with .NET native ?

**Comment by d3v1anc3** [comment]
We are also running into .NET native compile problems. We get error:  ILT0005

```
[error]C:\Users\sa_ptfs\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): Error : ILT0005: 'C:\Users\sa_ptfs\.nuget\packages\runtime.win10-x86.microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\x86\ilc\Tools\nutc_driver.exe 
```

**Comment by Alvaromah** [comment]
> We are also running into .NET native compile problems. We get error: ILT0005
> 
> ```
> [error]C:\Users\sa_ptfs\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): Error : ILT0005: 'C:\Users\sa_ptfs\.nuget\packages\runtime.win10-x86.microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\x86\ilc\Tools\nutc_driver.exe 
> ```

Same error ILT0005. There is no way to create a release UWP application using ONNXRuntime.

**Comment by rgsousa88** [comment]
Same issue here... Is there any updates about it?

**Comment by smasonuk** [comment]
I also get this same issue with release build with latest version 1.13.1

**Comment by LancerComet** [comment]
Any idea? No .NET Native support anyhow?

**Comment by songshizhao** [comment]
Same issue
