### ISSUE TITLE
trainning_runner spins up hundreds of threads

### ISSUE THREAD

**Issue by migueldeicaza** [microsoft/onnxruntime#4253]
I tried to force a single thread use, but the core of the training APIs used for things like the `onnxruntime_training_mnist` use the training_runner, which spins up a new thread for doing `RunWithUpdate`.

This should really reuse threads.   Currently it seems like it spawns a new thread per batch, with all the overhead associated with it.

**Comment by mrry** [comment]
@wschin It looks like this came in with the addition of pipeline parallelism support in 0aeb383273ebc261d732a65d02351636f35c6f1c. As a short-term matter, is it possible to avoid the thread creation when pipeline parallelism is disabled (which I think is the case for Miguel's run)?

Longer term, we'll probably want to find a solution that uses fewer threads for the pipeline-parallel case as well, at the very least by reusing existing threads, but possibly also by mapping multiple pipeline stages to the same client thread and ordering the work within the executor.

/cc @tlh20 FYI.

**Comment by wschin** [comment]
> @wschin It looks like this came in with the addition of pipeline parallelism support in [0aeb383](https://github.com/microsoft/onnxruntime/commit/0aeb383273ebc261d732a65d02351636f35c6f1c). As a short-term matter, is it possible to avoid the thread creation when pipeline parallelism is disabled (which I think is the case for Miguel's run)?
> 
> Longer term, we'll probably want to find a solution that uses fewer threads for the pipeline-parallel case as well, at the very least by reusing existing threads, but possibly also by mapping multiple pipeline stages to the same client thread and ordering the work within the executor.
> 
> /cc @tlh20 FYI.

Yes, it's possible to avoid that when pipeline is disabled. Reusing thread should be doable too. I will create two work items for them.
