### ISSUE TITLE
How to reduce the memory usage by CUDA?

### ISSUE THREAD

**Issue by capriccioo** [microsoft/onnxruntime#4259]
**Describe the bug**
There is a document about how to set the parameters of :
[TensorrtExecutionProvider](https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/Tensorrt-ExecutionProvider.md)
The line "export ORT_TENSORRT_MAX_WORKSPACE_SIZE=2147483648" sets the memory size used by tensorrt.
When I use Tensorrt-ExecutionProvider, except the memory used by tensorrt (set by the line above), another about 2GB memory is used by CUDA. It is too large for Jetson Nano (4GB memory) (The OS with graphic interface uses about 1.5GB , then litter memory remain for other part of my software.)

**System information**
- Jetson Nano with Jetpack4.4:
- ONNX Runtime version: 1.3.1
- Python version: 3.6
- CUDA/cuDNN version: 10.2 8.0

**Expected behavior**
Is there anything I can do to reduce the memory used by CUDA?

**Comment by arijitx** [comment]
Hi, you can ssh into jetson and don't login from the UI, I tried that and it reduces the idle memory usage to ~500-300MB.
