### ISSUE TITLE
Memory management overhead in CPU/Inference mode

### ISSUE THREAD

**Issue by migueldeicaza** [microsoft/onnxruntime#4267]
Running onnxruntime_perf_test for 10 seconds with an Mnist model, if I run this under Instruments, I notice that most of the overhead of inferencing is gone into memory management operations, this is the top execution loop, where I have unfolded the `Compute` nodes, and you can see that these operations are taking a lot of time:

<img width="1906" alt="image" src="https://user-images.githubusercontent.com/36863/84976237-653a0a00-b0f5-11ea-9d61-335aaefa9896.png">

If I zoom into a single one of those nodes, the call to `Output` takes about 23% of the running time, and from this, plenty of the time is going into memory management:

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/36863/84976338-9b778980-b0f5-11ea-99ed-9a88d51b6f96.png">

**Comment by skottmckay** [comment]
Can you provide some more details on how ORT was built and how you're running it?

On Windows with a fairly recent build from master compiled with config of RelWithDebInfo OpKernelContext::Output is only 3% according to the Visual Studio Performance Profiler.

**Comment by migueldeicaza** [comment]
I was running with the `Debug` configuration, the defaults for `build.sh`, but I tried `RelWithDebInfo`, and while it does improve overall the performance (5ms goes to 3ms in the call to `Output`),  the percentage of time taken by `Output` is now larger:

<img width="1864" alt="image" src="https://user-images.githubusercontent.com/36863/85037957-06f04400-b154-11ea-88d0-b3b733406dab.png">

This is on macOS, with onnxruntime from 3 days ago, master branch (e0334f177cb3cc5dc7aeabe8a5ef4773cd9ea902)

**Comment by mrry** [comment]
Looking at that profile, are we spending a lot of time getting the allocator here?

https://github.com/microsoft/onnxruntime/blob/478b923e1990f25205565f33244e22ab12667360/onnxruntime/core/framework/execution_frame.cc#L327

...as opposed to doing any allocation? I'm surprised to see STL container methods rather than, say, `malloc()` in allocation-related code! Just sent a small PR to defer that call until we actually need the allocator (which I *think* we don't in this case).

**Comment by skottmckay** [comment]
Over 30% of time to allocate node outputs still doesn't quite make sense, especially given it's 3% on Windows. What's the full command line being used? Wondering if this is running with the parallel executor which disables the memory pattern planner (still wouldn't expect it to be 30% of time though).
