### ISSUE TITLE
pytorch to onnx discrepancies

### ISSUE THREAD

**Issue by natangold85** [microsoft/onnxruntime#4269]
**Describe the bug**
Hey, im running a trained pytorch model converted to onnx on onnxruntime c++. i see some discrepancies in the output of one of the models i am running.
i have two models running. the first, a backbone that his main core is resnet34 and the second, a head that his input is the backbone outputs.
i see that when i check my head alone with recorded backbone outputs i get equal results to pytorch but when i check my backbone i see very different results.

i isolated the resnet34 from the backbone and checked only this module and i see very weird results.
for simplification of testing i created a model that his input is 5x6 image.
when i created a "synthetic" matrix i see equal results between pytorch and ort. when the matrix is loaded from the image i see that pytorch output is not equal to ort.

**Urgency**
my team needs to present lane detector on our target this day which requires an accurate model forwarding.

**System information**
QNX os. onnxruntime build from source with modifications to adjust to qnx.
onnxruntime built on latest master.
my compiler is qcc based on gcc 5.4.0.

**Expected behavior**
a clean converting of pytorch models to ort with no model differences.

**Additional context**
if necessary i can add a dummy onnx model but resnet34 is pretty common model.

**Comment by andrew11221** [comment]
@natangold85 Did you ever resolve this problem? If so, what was the issue/resolution?

**Comment by natangoldgm** [comment]
Hi, 
I don't remember, it was quite long ago.
I think it was related to opset i used to compile the onnx. i found that using opset 11 the model is very limited in the ability to change its values in the forward. compiling with opset 12 is solving this.

**Comment by andrew11221** [comment]
@natangold85  Interesting, thank you! When you were seeing discrepancies, were they just small differences in decimal values, or were the outputs between pytorch and ORT completely different?

**Comment by natangoldgm** [comment]
If my memory is right the values were completely different. 
I think that there was no self assignment in opset 11.
For example if i did something like this:
a += 1 
return a
than the += operator didn't changed at all.
Anyway, our team upgraded to opset 12 long time ago. 
Most of our models were not working right in opset 11.

**Comment by andrew11221** [comment]
Ok thank you for the clarification. Do you recall having to make any changes in MLAS to support the OS?

**Comment by andrew11221** [comment]
Alright, thank you. I don't suppose you still have the modified onnxruntime source code do you?
