### ISSUE TITLE
undefined reference to `onnxruntime::Env::Default()

### ISSUE THREAD

**Issue by capriccioo** [microsoft/onnxruntime#4273]
**Describe the bug**
I build onnxruntime by command line:

./build.sh --config Release --build_shared_lib --use_tensorrt --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu --tensorrt_home /usr/lib/aarch64-linux-gnu --parallel

After the build finished successfully, I tried to build CXX_Api_Sample.cpp by command line:

g++ -I../onnxruntime131/onnxruntime/include/onnxruntime/core/session testonnx.cpp -L./ -lonnxruntime_providers -lonnxruntime_common -lonnxruntime_session -lonnxruntime_framework -lonnxruntime_graph -lonnxruntime_mlas -lonnxruntime_optimizer -lonnxruntime_providers_tensorrt -lonnxruntime_util -lonnxruntime_mocked_allocator -lonnxruntime_providers_cuda -lgmock -lonnx -lonnx_proto -lonnxruntime -lonnx_test_data_proto -lnvonnxparser_static -lonnxruntime_test_utils -lprotoc -lprotobuf -lre2 -lnsync_cpp -lonnxruntime_providers_acl -lonnx_test_runner_common -o to 

but I got many errors like:
undefined reference to `onnxruntime::Env::Default()

I have linked with all lib*.a files I can find in onnxruntime directory. In which file I can find onnxruntime::Env::Default()?

**Comment by jf99** [comment]
@capriccioo I have the same issue. (How) Did you solve it?
