### ISSUE TITLE
Does it support TensorRT in new release 1.3.1-java-gpu

### ISSUE THREAD

**Issue by ericxsun** [microsoft/onnxruntime#4282]
**Is your feature request related to a problem? Please describe.**
A new version had been released: [1.3.1-GPU](https://search.maven.org/artifact/com.microsoft.onnxruntime/onnxruntime_gpu), does it support TensorRT?

**Comment by Craigacp** [comment]
To use TensorRT you'll need to compile it from source. The GPU version only has the CUDA and CPU execution providers compiled in.

**Comment by ericxsun** [comment]
> To use TensorRT you'll need to compile the Java binding from source with something like `./build.sh --config RelWithDebugInfo --update --build --build_java --use_tensorrt --tensorrt_home <path_to_tensorrt>`. The Java GPU binary only has the CUDA and CPU execution providers compiled in.

Okay, thanks a lot
