### ISSUE TITLE
Unable to build, getting error: package directory 'onnxruntime/backend' does not exist

### ISSUE THREAD

**Issue by buddhapuneeth** [microsoft/onnxruntime#4286]
**Describe the bug**
Trying to setup onnxruntime on my mac and I'm getting error: package directory 'onnxruntime/backend' does not exist

**Urgency**
Moderate. Needed for testing.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac Mojave
- ONNX Runtime installed from (source or binary):Source
- ONNX Runtime version: 1.3.0
- Python version: 3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):Apple LLVM version 10.0.1
- CUDA/cuDNN version: No
- GPU model and memory: No, CPU version

**To Reproduce**
git clone --recursive https://github.com/microsoft/onnxruntime.git
cd onnxruntime
mkdir build
cd build
cmake ..
make
cd ..
python setup.py install

**Expected behavior**
Successful installation

Error:
```
> python setup.py install
running install
running bdist_egg
running egg_info
writing onnxruntime.egg-info/PKG-INFO
writing dependency_links to onnxruntime.egg-info/dependency_links.txt
writing entry points to onnxruntime.egg-info/entry_points.txt
writing requirements to onnxruntime.egg-info/requires.txt
writing top-level names to onnxruntime.egg-info/top_level.txt
error: package directory 'onnxruntime/backend' does not exist
```

**Additional context**
Already tried the solutions in the old issues, nothing worked.
Alternatively, if non-wheel pypi is available, that is also helpful. As need to run some tests on python.

**Comment by snnn** [comment]
Don't execute "cd .." before running setup.py

**Comment by buddhapuneeth** [comment]
@snnn 
I tried that.
Ran 'python ../setup.py install' from build directory. But getting below error:
Traceback (most recent call last):
  File "../setup.py", line 278, in <module>
    with open('VERSION_NUMBER') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION_NUMBER'

**Comment by snnn** [comment]
Please append "-Donnxruntime_ENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python3" to the cmake flags.
```
cmake .. -Donnxruntime_ENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python3
```

**Comment by buddhapuneeth** [comment]
@snnn thanks for your reply.
Facing  different issue now:
Command:
```
cd build
cmake ../cmake/ -Donnxruntime_ENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python3
```

Error:
```
Use protobuf from submodule
--
-- 3.11.3.0
-- Could NOT find NumPy (missing: NUMPY_INCLUDE_DIR NUMPY_VERSION)
CMake Error at onnxruntime_python.cmake:27 (message):
  Cannot get NumPy include directory: Is NumPy installed?
Call Stack (most recent call first):
  CMakeLists.txt:1124 (include)


-- Configuring incomplete, errors occurred!
```

If I don't pass '../cmake', it will give error
```
CMake Error: The source directory "/Users/bnandano/Documents/onnxruntime" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by snnn** [comment]
In general you don't need to, usually it works well on Linux and Windows, maybe the paths on Mac are special. Could you please examine the CMakeError.log and CMakeOutput.log files in the build dir to see if they have some detailed information?  Did you set PYTHON_EXECUTABLE properly? Maybe you have multiple python installations but you point PYTHON_EXECUTABLE to one without numpy?

**Comment by buddhapuneeth** [comment]
Yes. I was pointing to wrong python env, where there is no numpy.

**Comment by buddhapuneeth** [comment]
Above steps worked fine in MAC. In CENT OS, I am facing similar issue:
Steps for reference
git clone --recursive https://github.com/microsoft/onnxruntime.git
cd onnxruntime
mkdir build
cd build
cmake ../cmake/ -Donnxruntime_ENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=//anaconda3/envs/py36/bin/python
make

Unable to run:
python../ setup.py install
```
Traceback (most recent call last):
  File "../setup.py", line 278, in <module>
    with open('VERSION_NUMBER') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'VERSION_NUMBER'

```

**Comment by buddhapuneeth** [comment]
It worked after setting unit test arg to ON (which is default)

**Comment by dummydummygithub** [comment]
@buddhapuneeth  @snnn 

Can you please guide me on how to test this repo?
I am able to reach "python ../setup.py install" command successfully, following the above comments, but not sure what to do next. I want to run the test suite.

**Comment by snnn** [comment]
@dummydummygithub 

You can download the following script and run it:
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/python/onnx_backend_test_series.py

However, the depends on a data file onnx_backend_test_series_filters.jsonc. You will need to download that file from this repo as well, and put it in correct location. See:
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/python/onnx_backend_test_series.py#L51

**Comment by a5372935** [comment]
@snnn @buddhapuneeth 
![image](https://user-images.githubusercontent.com/39560035/189062446-7db83c6a-a1d7-44a3-93ba-d7cf5022b1e1.png)
Excuse me I've been using the tutorial to install ONNX and have been unable to resolve these situations
`./build.sh --update --config Release --enable_pybind --build_shared_lib --build --build_wheel --use_tensorrt --tensorrt_home /usr/src/tensorrt --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu`
![image](https://user-images.githubusercontent.com/39560035/189061553-f093ed7a-0e16-4478-abc7-7b596e96a72b.png)
How do I solve this problem?

**Comment by allzero-kwon** [comment]
This works for me ! Thank you @snnn 

```
./build.sh --config RelWithDebInfo --build_shared_lib --parallel --compile_no_warning_as_error --skip_submodule_sync --build_wheel --enable_pybind
cd build/Linux/RelWithDebInf

python3 ../../../setup.py bdist_wheel
python3 ../../../setup.py install
```
