### ISSUE TITLE
How to access multidimensional output in C++?

### ISSUE THREAD

**Issue by ShubhamJain7** [microsoft/onnxruntime#4298]
I am running onnxruntime 1.3.0 (x86) on Windows 10 and run the model as follows:
`auto output_tensors = session.Run(Ort::RunOptions{ nullptr }, input_names, &input_tensor, 1, output_names, 2);`

As you can see from the last parameter, I have 2 outputs of shape 1x100x92 and 1x100x4 respectively. How do I access the values of the output tensors and store them in a 3D float arrays for further processing?

**Comment by pranavsharma** [comment]
See the test 'override_initializer' in onnxruntime/test/shared_lib/test_inference.cc.

**Comment by ShubhamJain7** [comment]
Thanks!

For anyone else looking for a solution, here's how I did it:

    auto scores = output_tensors[0].GetTensorMutableData<float>();

    // Get length of output
    auto typeInfo = output_tensors[0].GetTensorTypeAndShapeInfo();
    size_t len = typeInfo.GetElementCount();

    // store outputs in a 2d array for easier access and processing
    float probs[100][92];
    size_t index = 0;
    while (index < len) {
        for (int i = 0; i < 100; i++) {
            for (int j = 0; j < 92; j++) {
                probs[i][j] = scores[index];
            }
        }
    }
