### ISSUE TITLE
Can't suppress warning when build with OpenMP

### ISSUE THREAD

**Issue by Godricly** [microsoft/onnxruntime#4307]
https://github.com/microsoft/onnxruntime/blob/6c1b2f33b74ad48c3cb08d4ba1f38e1897659c8e/onnxruntime/core/session/abi_session_options.cc#L150

This warning ouput is implemented with std::cout.

**Comment by pranavsharma** [comment]
The warning is intentional. Don't call the SetIntraOpNumThreads() API when openmp is enabled and you'll not see a warning.
