### ISSUE TITLE
Increasing memory usage with TensorRT

### ISSUE THREAD

**Issue by arijitx** [microsoft/onnxruntime#4308]
**Describe the bug**
When I run a model with TensorRTProvider the it starts to fill up whole memory in Jetson Nano and crashes with the message "killed", looks like a possible memory leak. Anything linked with this PR : https://github.com/microsoft/onnxruntime/pull/4227/ ? I'm able to run the non shape infered model with CUDAProvider with ~2GB memory usage.  I have set  
```
ORT_TENSORRT_MAX_WORKSPACE_SIZE=2147483648
ORT_TENSORRT_MAX_PARTITION_ITERATIONS=10
```

When I set ORT_TENSORRT_MAX_PARTITION_ITERATIONS=1 it is running but falling back to CPUProvider. Is it that after each iteration its not clearing memory ? or that is the expected behavior and the optimizer can only run on large memory. 

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Jetpack 4.4
- ONNX Runtime installed from (source or binary): source (commit 9e3b5c62fbb4db01b26ffd0947d2fe4c9ca0376c)
- ONNX Runtime version: 1.3.1
- Python version: 3.6.9
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: CUDA 10.2.89/ CuDNN  8.0.0.145
- GPU model and memory: Tegra210

**To Reproduce**
- https://gist.github.com/arijitx/1400d3d4e07fc517d6c5bfea506c2353#file-benchmark_trt-py
- model path https://drive.google.com/file/d/1unynQuaYgLlksJPkTeo7kdL0KEtcVTFI/view?usp=sharing

**Additional context**

The model is dumped from hugginface/transformers

`python3 convert_graph_to_onnx.py onnx/dbert_squad.onnx --pipeline question-answering --model  distilbert-base-uncased-distilled-squad --tokenizer distilbert-base-uncased-distilled-squad --framework pt
`

Then the shape is inferred 

`python3 /home/arijitx/onnxruntime/onnxruntime/core/providers/nuphar/scripts/symbolic_shape_infer.py --input dbert_squad.onnx --output dbert_squad_trt.onnx
`

**Comment by stevenlix** [comment]
Please pull latest ORT master and run TensorRT again. I've tested your model with synthetic input and it runs successfully with default setting. I didn't try Jetson Nano yet, so please let me know if you still see the issue on Jetson.

**Comment by cbarburescu** [comment]
@stevenlix I have the same issue and it only happens on the Jetson (I work with a TX2). I did not have this problem on beefy vms or workstations.

**Comment by ken012git** [comment]
I have the same issue on my Nvidia Jetson Nano 4G. Is there a solution for this? Setting `ORT_TENSORRT_MAX_WORKSPACE_SIZE` does not work for me...
