### ISSUE TITLE
run(output_names, input_feed, run_options)

### ISSUE THREAD

**Issue by Tony1236** [microsoft/onnxruntime#4310]
File "bert_onnx.py", line 30, in <module>
    res = session.run(output_names, inputs,run_options=None)
  File "/usr/local/anaconda3/envs/nlp/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 111, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_s

 This parameter  “run_options” ?

**Comment by mrry** [comment]
I don't think we have enough information about what the problem is to help you here. Can you please paste in the full error message and stack trace, along with details of how to reproduce the problem?

**Comment by Tony1236** [comment]
> I don't think we have enough information about what the problem is to help you here. Can you please paste in the full error message and stack trace, along with details of how to reproduce the problem?

Thank you very much

Version：
onnx==1.7.0          
onnxruntime-gpu ==1.3.0  
onnxruntime-tools==1.3.0.1009

This is my test code:
sess_options = rt.SessionOptions()
sess_options.graph_optimization_level = rt.GraphOptimizationLevel.ORT_ENABLE_EXTENDED
session = rt.InferenceSession("bert_gpu_fp16.onnx", sess_options)
# evaluate the model
inputs = {
    'input_mask:0':  np.ones(shape=[1, 256], dtype=np.int32),
    'input_ids:0':   np.random.randint(0, 256, size=[1, 256], dtype=np.int32),
    'segment_ids:0': np.ones(shape=[1, 256], dtype=np.int32)
}

start = time.time()
# Run the optimized model with inputs
output_names = ['loss/Softmax:0']
res = session.run(output_names, inputs)
end = time.time()
gpu_time = end - start
print("ONNX GPU Runtime Inference time: ", end - start)

Executing code produced an error:
Traceback (most recent call last):
  File "bert_onnx.py", line 30, in <module>
    res = session.run(output_names, inputs)
  File "/usr/local/anaconda3/envs/nlp/lib/python3.6/site-packages/onnxruntime/capi/session.py", line 111, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running SkipLayerNormalization node. Name:'SkipLayerNorm_AddBias_25' Status Message: input is expected to have 3 dimensions, got 2

I found that the source code has an "run_options" parameter, how to define "run_options" parameter?

**Comment by mrry** [comment]
The documentation for creating an `onnxruntime.RunOptions` object, which can be passed as the `run_options` parameter is here:

https://microsoft.github.io/onnxruntime/python/api_summary.html#onnxruntime.RunOptions

However, I don't think that is the source of your error. This message:

> onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running SkipLayerNormalization node. Name:'SkipLayerNorm_AddBias_25' Status Message: input is expected to have 3 dimensions, got 2

...indicates that there is a shape error somewhere in the model. It is most likely that one of the arrays in `inputs` has the wrong shape.
