### ISSUE TITLE
CMake possible features: making the install an option and modify deprecated Python handling

### ISSUE THREAD

**Issue by strattist** [microsoft/onnxruntime#4326]
**Description**
I started to use the OnnxRuntime in a C++ context and I had some difficulty building it from scratch using the given CMakeLists.txt. Two things bothered me:
- The way PythonInterp and PythonLibs was handled made my configuration crashed at some point. It seems it's a known problem with how CMake was looking for Python. It seems it changed since CMake 3.12 where the `find_package(PythonInterp)` and `find_package(PythonLibs)` became deprecated as stated [here](https://cmake.org/cmake/help/v3.12/module/FindPythonLibs.html) and [here](https://cmake.org/cmake/help/v3.12/module/FindPythonInterp.html)
- The forced installation of the OnnxRuntime. I don't know if there is a specific reason to force the installation of the library and not making it an option and if so I would love to know why. But in my case, I try to avoid any 3rdparty installation related to my work since it's easier to later change versions without system conflicts and deployments with my coworkers. 

I had to write my own CMake with modified paths obviously. I give you below what I changed, in case you want to discuss it.

**Python handling**

Before:

```
if(onnxruntime_BUILD_SHARED_LIB OR onnxruntime_ENABLE_PYTHON)
  if(onnxruntime_ENABLE_PYTHON)
    find_package(PythonInterp 3.5 REQUIRED)
    find_package(PythonLibs 3.5 REQUIRED)
  else()
    find_package(PythonInterp 3.4 REQUIRED)
  endif()
endif()
```

After:

```
if(onnxruntime_BUILD_SHARED_LIB)
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  set(PYTHON_EXECUTABLE ${Python3_EXECUTABLE})
endif()
```

To be clear the `onnxruntime_ENABLE_PYTHON` option will always be False for me so I didn't handle this case further in your CMake since the idea is only to change the minimum part. The `set` call is used only for compatibility with the **onnxruntime.cmake** file.

**Avoid the installation**

It's good to know I forced my CMake builtin install function to not do anything (I know it's not the best idea but it's very efficient to not do any installation from 3rdparties).  Since I didn't change the **onnxruntime.cmake** file I just had to build my own interface at the end to make some parts public:

```
add_library(onnxruntime_public INTERFACE)
target_link_libraries(onnxruntime_public INTERFACE
  onnxruntime
  onnxruntime_session
  onnxruntime_optimizer
  onnxruntime_providers
  onnxruntime_util
  onnxruntime_framework
  onnxruntime_graph
  onnxruntime_common
  onnxruntime_mlas
  ${onnxruntime_EXTERNAL_LIBRARIES}
)
``` 

I'm not sure about the libraries to link to my interface to be able to only use the API but it worked for me and it could be great to consider have this part changed to use onnxruntime without installing. I would also like to point I did that since I had undefined references errors otherwise.

**System information**
- ONNX Runtime version (you are using): v1.3.1

**Describe the solution you'd like**
- Adding a CMake option in the CMakeLists.txt to make the onnxruntime installation (in onnxruntime.cmake) an option
- Update the Python `find_package` to a more robust (and non deprecated) version.

**Quick additions**
Also, while the minimum required CMake is 3.13 it's wrong to me to do such things as 
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Dgsl_CONFIG_CONTRACT_VIOLATION_THROWS")` 
or 
`string(APPEND CMAKE_CXX_FLAGS " -Wall -Wextra -ffunction-sections -fdata-sections")` 
since it will change the configuration and build of every single targets that are configured after Onnxruntime. It could be good to modernize everything by using the powerful target property propagation CMake is offering.

**Comment by snnn** [comment]
Just want to add a remark here: the new one may break our cross-compile setup.

See: https://github.com/Kitware/CMake/blob/master/Modules/FindPython/Support.cmake#L2922

It requires to run python execution to get numpy version, which won't work in cross-compiling scenario.

**Comment by strattist** [comment]
> Just want to add a remark here: the new one may break our cross-compile setup.
> 
> See: https://github.com/Kitware/CMake/blob/master/Modules/FindPython/Support.cmake#L2922
> 
> It requires to run python execution to get numpy version, which won't work in cross-compiling scenario.

Wasn't it the same case even before? From what I understand in the link you sent, the command will only be executed if NumPy is asked as a Python Component in the `find_package` call, which is only possible from CMake 3.14. Surely tests would be needed to ensure compatibility with the `onnxruntime_python.cmake` file at least.

I don't often contribute but if there are facilities to help testing all scenario you might face I would be happy to help. Is there some kind of automatic CI Builds / Tests / Profilings... even for external contributors?

**Comment by snnn** [comment]
Sorry, onnxruntime's CI Builds system isn't fully open to public. If you you have a PR on hands,  welcome to submit it here. I'll help you verify it.

**Comment by strattist** [comment]
Ok I don't have any PR at the moment but I'll try to do something.
