### ISSUE TITLE
when there are few cast connected, the result might be wrong

### ISSUE THREAD

**Issue by pengwa** [Microsoft/onnxruntime#433]
**Describe the bug**

look at the graph below. The input is bool[1, 100], we for example feed it with all True. 

Then Cast (to 1) change it to all 1.0.

Then ReduceSum(axes=1) generate results [100.0]

Then Cast(to 9) change it to [True]

Then Cast(to 1) change it to [100.0]

So the last step should not expected, because user would expect: when they want to cast a True to float, the value should be 1.0. 

I guess this is caused when Cast is computed, the value is not changed actually, maybe just a cast.

![image](https://user-images.githubusercontent.com/10530022/52159919-003f6900-26e6-11e9-9323-85174e926b87.png)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): master
- ONNX Runtime version: master
- Python version: 3.6
- GCC/Compiler version (if compiling from source): VS 2017
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
Describe steps/code to reproduce the behavior: see above

**Expected behavior**

whenever cast a bool True to float,  the value should be 1.0

**Screenshots**

**Additional context**

**Comment by yufenglee** [comment]
@raymondxyang could you fix this issue with your cast update?

**Comment by raymondxyang** [comment]
Just verified the eigen (used in cast op kernel) will not produce the described result, when casting float->bool->float. in other word, 100.0 will be cast into 1.0 in this case. Could u send me the model for more debugging processes?

**Comment by raymondxyang** [comment]
followed up offline. can re-produce the error. looking into it..
