### ISSUE TITLE
Using onnxruntime_perf_test for testdata/squeezenet/model.onnx

### ISSUE THREAD

**Issue by dhunt-ambarella** [microsoft/onnxruntime#4331]
onnxruntime_perf_test /sdcard/testdata/squeezenet/model.onnx result
there is no test input data for input data_0 and model squeezenet
Run failed:failed to initialize.

From test/perftest/performance_runner.cc:
    for (int i = 0; i != input_count; ++i) {
      auto iter = feeds.find(test_model_info->GetInputName(i));
      if (iter == feeds.end()) {
        std::cout << "there is no test input data for input " << test_model_info->GetInputName(i) << " and model "
                  << test_case_->GetTestCaseName() << std::endl;
        return false;
      }
      session_->PreLoadTestData(test_data_id, static_cast<size_t>(i), iter->second);
    }

I cross compiled onnxruntime for Linux on ARM.  I did not use ACL.  I used the latest code from github on 6/18/2020.

I used protoc 3.11.3.

onnxruntime_test_all runs OK.

I moved testdata to my platform.

I am trying to run:
onnxruntime_perf_test /sdcard/testdata/squeezenet/model.onnx result

# ls -l testdata/squeezenet/*
-rwxr-xr-x    1 root     users      4952222 Apr 12 01:48 testdata/squeezenet/model.onnx

testdata/squeezenet/test_data_set_0:
total 1280
-rwxr-xr-x    1 root     users       602134 Apr 12 01:58 input_0.pb
-rwxr-xr-x    1 root     users         4026 Apr 12 01:58 output_0.pb
-rwxr-xr-x    1 root     users       602134 Apr 12 01:48 test_data_0_input.pb
-rwxr-xr-x    1 root     users         4026 Apr 12 01:48 test_data_0_output.pb
#

I copied test_data_0_input.pb to input_0.pb so LoadTestData would find the files.  I added prints to learn that that was necessary:

OnnxTestCase::LoadTestData: LoopDir: inspecting test_data_0_input.pb for input_
OnnxTestCase::LoadTestData: LoopDir: inspecting test_data_0_output.pb for input_
OnnxTestCase::LoadTestData: LoopDir: inspecting input_0.pb for input_
OnnxTestCase::LoadTestData: LoopDir: push_back(/sdcard/testdata/squeezenet/test_data_set_0/input_0.pb)
OnnxTestCase::LoadTestData: LoopDir: inspecting output_0.pb for input_

I used cmake 3.17
cmake -DCMAKE_TOOLCHAIN_FILE=/dump/dump201/dhunt/tool.cmake -Donnxruntime_CROSS_COMPILING=ON -Donnxruntime_RUN_ONNX_TESTS=OFF -Donnxruntime_DEV_MODE=ON -DPYTHON_EXECUTABLE=/opt/amba/cv2_third/tv2/exe/python3 -Donnxruntime_USE_CUDA=OFF -Donnxruntime_USE_NSYNC=OFF -Donnxruntime_CUDNN_HOME= -Donnxruntime_USE_JEMALLOC=OFF -Donnxruntime_ENABLE_PYTHON=OFF -Donnxruntime_BUILD_CSHARP=OFF -Donnxruntime_BUILD_SHARED_LIB=ON -Donnxruntime_USE_EIGEN_FOR_BLAS=ON -Donnxruntime_USE_OPENBLAS=OFF -Donnxruntime_USE_DNNL=OFF -Donnxruntime_USE_MKLML=OFF -Donnxruntime_USE_OPENMP=ON -Donnxruntime_USE_TVM=OFF -Donnxruntime_USE_LLVM=OFF -Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF -Donnxruntime_USE_BRAINSLICE=OFF -Donnxruntime_USE_NUPHAR=OFF -Donnxruntime_USE_EIGEN_THREADPOOL=OFF -Donnxruntime_BUILD_UNIT_TESTS=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -Dprotobuf_WITH_ZLIB=OFF -DONNX_CUSTOM_PROTOC_EXECUTABLE=/dump/dump201/dhunt/protoc_3.11.3/bin/protoc -DCMAKE_VERBOSE_MAKEFILE=ON cmake

cat tool.cmake:
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_C_COMPILER /usr/local/linaro-aarch64-2018.08-gcc8.2/bin/aarch64-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER /usr/local/linaro-aarch64-2018.08-gcc8.2/bin/aarch64-linux-gnu-g++)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by snnn** [comment]
Could you use the model and test data from onnx model zoo?

**Comment by dhunt-ambarella** [comment]
I used a browser version of netron to see the screenshot that is attached.

It showed input to model is 'data_0'.

I got this model:
https://github.com/onnx/models/blob/master/vision/classification/squeezenet/model/squeezenet1.0-8.onnx

It shows the same 'data_0' label for input.

So, the issue I am having is that the input_0.pb doesn't have data_0, it has 'data'.

On my ARM platform:

# onnxruntime_perf_test /sdcard/testdata/squeezenet/model.onnx result

OnnxTestCase::LoadTestData: LoopDir: push_back(/sdcard/testdata/squeezenet/test_data_set_0/input_0.pb)  <-- my own print added to the onnxruntime code

_there is no test input data for input data_0 and model squeezenet
Run failed:failed to initialize._

dhunt@ubu-sw4:/dump/dump201/dhunt/onnxruntime$ cat VERSION_NUMBER
1.3.1

I need some help understanding what input_0.pb is, and why there isn't input labeled 'data_0' in that file.  Is input_0.pb generated during my 'make'?  Using my protoc 3.11.3?  Should I use a newer version of protoc?

As mentioned in the original post, my test_data_set_0 dir originally had a file named test_data_0_input.pb, which I copied to input_0.pb so that LoadTestData could find the file.  I added prints to see how it worked:

OnnxTestCase::LoadTestData: looking for /sdcard/testdata/squeezenet/test_data_set_0/inputs.pb.  st.IsOK=0
OnnxTestCase::LoadTestData: LoopDir: inspecting test_data_0_input.pb for input_
OnnxTestCase::LoadTestData: LoopDir: inspecting test_data_0_output.pb for input_
OnnxTestCase::LoadTestData: LoopDir: inspecting input_0.pb for input_
OnnxTestCase::LoadTestData: LoopDir: push_back(/sdcard/testdata/squeezenet/test_data_set_0/
![netron_squeezenet_model_onnx](https://user-images.githubusercontent.com/67397170/85668805-05eb7500-b674-11ea-88c8-6dcc55e28869.jpg)
input_0.pb)
OnnxTestCase::LoadTestData: LoopDir: inspecting output_0.pb for input_

testdata/squeezenet/test_data_set_0:
total 1280
-rwxr-xr-x    1 root     users       602134 Apr 12 01:58 input_0.pb
-rwxr-xr-x    1 root     users         4026 Apr 12 01:58 output_0.pb
-rwxr-xr-x    1 root     users       602134 Apr 12 01:48 test_data_0_input.pb
-rwxr-xr-x    1 root     users         4026 Apr 12 01:48 test_data_0_output.pb

**Comment by dhunt-ambarella** [comment]
When parsing the input_0.pb file, I added a print and I see the name is 'data' (and maybe it needs to be 'data_0'):

OnnxTestCase::ConvertTestData: feed.insert(make_pair(**data**, v1.release()))

The printf that produced that output is at the end of the following code snip.

From test/onnx/TestCase.cc::OnnxTestCase::ConvertTestData():

  for (size_t input_index = 0; input_index != test_data_pbs.size(); ++input_index) {
    std::string name = var_names[input_index];
    const ONNX_NAMESPACE::TensorProto& input = test_data_pbs[input_index];
    size_t len = 0;

    auto status = onnxruntime::test::GetSizeInBytesFromTensorProto<0>(input, &len);
    if (!status.IsOK()) {
      ORT_THROW(status.ToString());
    }
    void* p = len == 0 ? nullptr : b.AllocMemory(len);
    Ort::Value v1{nullptr};
    auto d = onnxruntime::make_unique<onnxruntime::test::OrtCallback>();
    OrtMemoryInfo cpu_memory_info(onnxruntime::CPU, OrtDeviceAllocator, OrtDevice(), 0, OrtMemTypeDefault);
    status = onnxruntime::test::TensorProtoToMLValue(input, onnxruntime::test::MemBuffer(p, len, cpu_memory_info),
                                                     v1, *d);
    if (!status.IsOK()) {
      ORT_THROW(status.ToString());
    }
    if (d->f) {
      b.AddDeleter(d.release());
    }
    out.insert(std::make_pair(name, v1.release()));
printf("OnnxTestCase::ConvertTestData: feed.insert(make_pair(%s, v1.release()))\n", name.c_str());
  }

**Comment by snnn** [comment]
Could you  try this one instead?
https://github.com/onnx/models/blob/master/vision/classification/squeezenet/model/squeezenet1.0-9.tar.gz

**Comment by dhunt-ambarella** [comment]
Thank you snnn!

This one goes through all the test_data_set_0-12 directories and makes entries in the feed.

Then after 10 minutes, I get the command prompt back:

Session creation time cost:0.133189 s
Total inference time cost:600.051 s
Total inference requests:7160
Average inference time cost:83.8059 ms
Total inference run time:600.102 s
#

That feels like success.  If you think ARMV8 Cortex A should take 10 minutes on that test, then I guess we can close this issue.

I suppose average inference time cost = 83.8059 ms is reasonable.

But testdata/squeezenet in the github seems unrunnable.  Even after changing the names of the input files to input_0.pb.

Finally, I noticed that ConvertTestData invents the name for the feed, instead of finding it in the input_0.pb file.

  for (size_t input_index = 0; input_index != test_data_pbs.size(); ++input_index) {
    std::string name = test_data_pbs[input_index].name();
    if (name.empty()) {
      has_valid_names = false;
      break;
    }
    var_names[input_index] = name;
  }
  if (!has_valid_names) {
    size_t count = static_cast<size_t>(is_input ? model_info_->GetInputCount() : model_info_->GetOutputCount());
    if (count != test_data_pbs.size()) {
      ORT_THROW("data count mismatch, expect ", count, ", got ", test_data_pbs.size());
    }
    for (size_t i = 0; i != count; ++i) {
      var_names[i] = is_input ? model_info_->GetInputName(i) : model_info_->GetOutputName(i);
printf("OnnxTestCase::ConvertTestData: **inventing** var_names[%lu] = %s\n", i, var_names[i].c_str());
    }
  }

Output to my console:

OnnxTestCase::LoadTestData: LoopDir: push_back(/sdcard/testdata/squeezenet1.0-9/test_data_set_0/input_0.pb)

OnnxTestCase::ConvertTestData: **inventing** var_names[0] = data_0
OnnxTestCase::ConvertTestData: feed.insert(make_pair(data_0, v1.release()))

OnnxTestCase::LoadTestData: LoopDir: push_back(/sdcard/testdata/squeezenet1.0-9/test_data_set_1/input_0.pb)

OnnxTestCase::ConvertTestData: inventing var_names[0] = data_0
OnnxTestCase::ConvertTestData: feed.insert(make_pair(data_0, v1.release()))

OnnxTestCase::LoadTestData: LoopDir: push_back(/sdcard/testdata/squeezenet1.0-9/test_data_set_10/input_0.pb)

OnnxTestCase::ConvertTestData: inventing var_names[0] = data_0
OnnxTestCase::ConvertTestData: feed.insert(make_pair(data_0, v1.release()))

OnnxTestCase::LoadTestData: LoopDir: push_back(/sdcard/testdata/squeezenet1.0-9/test_data_set_11/input_0.pb)

OnnxTestCase::ConvertTestData: inventing var_names[0] = data_0
OnnxTestCase::ConvertTestData: feed.insert(make_pair(data_0, v1.release()))

OnnxTestCase::LoadTestData: LoopDir: push_back(/sdcard/testdata/squeezenet1.0-9/test_data_set_2/input_0.pb)

OnnxTestCase::ConvertTestData: inventing var_names[0] = data_0
OnnxTestCase::ConvertTestData: feed.insert(make_pair(data_0, v1.release()))

OnnxTestCase::LoadTestData: LoopDir: push_back(/sdcard/testdata/squeezenet1.0-9/test_data_set_3/input_0.pb)

OnnxTestCase::ConvertTestData: inventing var_names[0] = data_0
OnnxTestCase::ConvertTestData: feed.insert(make_pair(data_0, v1.release()))

OnnxTestCase::LoadTestData: LoopDir: push_back(/sdcard/testdata/squeezenet1.0-9/test_data_set_4/input_0.pb)
OnnxTestCase::LoadTestData: LoopDir: inspecting output_0.pb for input_

OnnxTestCase::ConvertTestData: feed.insert(make_pair(data_0, v1.release()))

OnnxTestCase::LoadTestData: LoopDir: push_back(/sdcard/testdata/squeezenet1.0-9/test_data_set_5/input_0.pb)

OnnxTestCase::ConvertTestData: inventing var_names[0] = data_0
OnnxTestCase::ConvertTestData: feed.insert(make_pair(data_0, v1.release()))

OnnxTestCase::LoadTestData: LoopDir: push_back(/sdcard/testdata/squeezenet1.0-9/test_data_set_6/input_0.pb)

OnnxTestCase::ConvertTestData: inventing var_names[0] = data_0
OnnxTestCase::ConvertTestData: feed.insert(make_pair(data_0, v1.release()))

OnnxTestCase::LoadTestData: LoopDir: push_back(/sdcard/testdata/squeezenet1.0-9/test_data_set_7/input_0.pb)

OnnxTestCase::ConvertTestData: inventing var_names[0] = data_0
OnnxTestCase::ConvertTestData: feed.insert(make_pair(data_0, v1.release()))

OnnxTestCase::LoadTestData: LoopDir: push_back(/sdcard/testdata/squeezenet1.0-9/test_data_set_8/input_0.pb)

OnnxTestCase::ConvertTestData: inventing var_names[0] = data_0
OnnxTestCase::ConvertTestData: feed.insert(make_pair(data_0, v1.release()))

OnnxTestCase::LoadTestData: LoopDir: push_back(/sdcard/testdata/squeezenet1.0-9/test_data_set_9/input_0.pb)

OnnxTestCase::ConvertTestData: inventing var_names[0] = data_0
OnnxTestCase::ConvertTestData: feed.insert(make_pair(data_0, v1.release()))

**Comment by snnn** [comment]
If you feel the name of the test is wrong, you can use the following script to change it:
```python
import onnx
import sys

from onnx import TensorProto
from google.protobuf import text_format

proto = TensorProto()

# Read the existing address book.
with open(sys.argv[1], "rb") as f:
    proto.ParseFromString(f.read())
proto.name = sys.argv[2]

with open(sys.argv[1], "wb") as f:
    f.write(proto.SerializeToString())
```

On my desktop, the model takes about 2ms.
```
onnxruntime_perf_test -o 99 -t 10 model.onnx 1.csv
Session creation time cost:0.0406232 s
Total inference time cost:9.99695 s
Total inference requests:3755
Average inference time cost:2.6623 ms
Total inference run time:10.0524 s
```
I expect on a ARM device, it could be 4-10 times more. but 80ms is a little bit too high.

**Comment by dhunt-ambarella** [comment]
Changming, that script worked.  Thanks for your help!

So, in order to run the squeezenet model, with onnxruntime_perf_test, as currently distributed, I had to change the name of the input from test_data_0_input.pb to input_0.pb, and use your script to change the name of the input Tensor from 'data' to 'data_0'.

On host:
dhunt@ubu-sw4:/dump/dump201/dhunt/onnxruntime/testdata/squeezenet/test_data_set_0$ cp test_data_0_input.pb input_0.pb
dhunt@ubu-sw4:/dump/dump201/dhunt/onnxruntime/testdata/squeezenet/test_data_set_0$ python3 change_name.py input_0.pb data_0

On target:
# onnxruntime_perf_test /sdcard/testdata/squeezenet/model.onnx result.csv
OnnxTestCase::ConvertTestData: feed.insert(make_pair(**data_0**, v1.release()))
Session creation time cost:0.0618331 s
Total inference time cost:600.034 s
Total inference requests:7176
Average inference time cost:83.6167 ms
Total inference run time:600.086 s
