### ISSUE TITLE
arm/arm64 builds are broken

### ISSUE THREAD

**Issue by martinb35** [microsoft/onnxruntime#4339]
building onnxruntime for arm and arm64 is broken after this commit: [Implement MinMax with SIMD
#4285](https://github.com/microsoft/onnxruntime/pull/4285/files):

  E:\BA\375\s\engine\lotus\onnxruntime\core\mlas\lib\mlasi.h(1488): error C3861: 'vminvq_f32': identifier not found (compiling source file E:\BA\375\s\engine\lotus\onnxruntime\core\mlas\lib\platform.cpp) [E:\BA\375\s\build\arm64-win-inbox-release\engine\lotus\onnxruntime_mlas.vcxproj]

**Comment by martinb35** [comment]
FYI @yufenglee

**Comment by snnn** [comment]
Windows ARM only, right?

**Comment by tracysh** [comment]
It's Visual Studio 2017 specific.

**Comment by yufenglee** [comment]
Thanks @tracysh for fixing the issue!
