### ISSUE TITLE
Build error "Could not copy the file ..."

### ISSUE THREAD

**Issue by Victel** [Microsoft/onnxruntime#434]
**Describe the bug**
Build error: “Could not copy the file “project\packages\Microsoft.ML.OnnxRuntime.0.2.1\runtimes\win10-x64\native\mkldnn.dll" because it was not found.”.  Indeed, there’s no “win10-x64” in runtimes but “win-x64” and “linux-x64”, only.
**System information**
- Windows 10, VS 2017, Windows Desktop project
**To Reproduce**
Build project with Microsoft.ML.OnnxRuntime.0.2.1 installed
**Expected behavior**
Build w/o errors
**Screenshots**
**Additional context**

**Comment by shahasad** [comment]
Fixed by
https://github.com/Microsoft/onnxruntime/pull/325

**Comment by shahasad** [comment]
https://github.com/Microsoft/onnxruntime/pull/435
