### ISSUE TITLE
Maven Java Artifacts Performance Degradation Questions

### ISSUE THREAD

**Issue by mina-asham** [microsoft/onnxruntime#4352]
**Describe the bug**
Hi, we've recently tried upgrading to 1.3.1 from 1.2.0, main motivation was:
* performance improvements claimed in 1.3.0
* Maven artifacts availability in 1.3.1, so we don't have to manually build it

We noticed a performance degradation ranging from 3X to 15X depending on the model and batch size. After looking a bit into this I believe this is due to the Maven artifacts being built with openmp while the manual builds we previously did used the default options.

I did see that openmp is not recommended for sequential execution, so I tried setting our session options to parallel execution but that didn't make any difference, likely because our graph might not be that parallelizable (although I haven't looked deeply into this).

I eventually built 1.3.1 manually and the performance went back to normal (no noticeable improvements from 1.2.0 to 1.3.1 on our models).

My main questions here are:
* Is there a specific reason the official Maven artifacts are built with non-default options?
  * If so, should these change to become the default?
* Are there any plans to release different Maven artifcats for different execution providers?
* Any suggestions for a solution that doesn't require me to build from source to use the library?

[Removing all required below information because it's not really useful for the usecase]

**Comment by pranavsharma** [comment]
> * Is there a specific reason the official Maven artifacts are built with non-default options?

All official binaries are built with openmp because it performs well for most of the models we're tracking.

>   
>   * If so, should these change to become the default?

We're working on disabling openmp in future releases, but it might take some time as it requires extensive testing with the [new changes](https://github.com/microsoft/onnxruntime/commit/9e3b5c62fbb4db01b26ffd0947d2fe4c9ca0376c) that bring the perf at parity with openmp.

> * Are there any plans to release different Maven artifcats for different execution providers?

Not at this time.

> * Any suggestions for a solution that doesn't require me to build from source to use the library?

Not at this time.

**Comment by mina-asham** [comment]
Thanks @pranavsharma for the quick reply!

> We're working on disabling openmp in future releases, but it might take some time as it requires extensive testing with the new changes that bring the perf at parity with openmp.

Is there an issue I can subscribe to for this one?

**Comment by pranavsharma** [comment]
> Thanks @pranavsharma for the quick reply!
> 
> > We're working on disabling openmp in future releases, but it might take some time as it requires extensive testing with the new changes that bring the perf at parity with openmp.
> 
> Is there an issue I can subscribe to for this one?

We're tracking this internally. When we do this, it'll be called out explicitly in the release notes. We've a release coming up in mid July (but this change is not necessarily committed for this release yet as it depends on the test runs). The next release is not planned yet.

**Comment by saudet** [comment]
It's probably possible to set the OMP_NUM_THREADS environment variable to 1 to disable OpenMP.
