### ISSUE TITLE
DllNotFound exception on android

### ISSUE THREAD

**Issue by d3v1anc3** [microsoft/onnxruntime#4363]
Hi

We are using OnnxRuntime version 1.3.0 on UWP and Android using Xamarin. While the UWP version works correctly, the android application crashes when creating the InferenceSession. 

```csharp
using (InferenceSession session = new InferenceSession(model))
{
	...
}
```

```
System.TypeInitializationException
  Message=The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.

DllNotFound exception
onnxruntime assembly:<unknown assembly> type:<unknown type> member:(null)
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_generic_class_init(intptr)
  at Microsoft.ML.OnnxRuntime.SessionOptions..ctor () [0x00069] in C:\agent\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\SessionOptions.cs:49 
  at Microsoft.ML.OnnxRuntime.InferenceSession..ctor (System.Byte[] model) [0x00016] in C:\agent\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\InferenceSession.cs:55 
```

I'm not sure if we are doing something wrong or if Android support is not functional yet. The platform is marked  "preview" in the roadmap document. And I also see support for NNAPI Execution Provider. Do we need to do something different when using OnnxRuntime on an Android device?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 9 (kernel 4.4.111-17263988(
- ONNX Runtime installed from (source or binary): Nuget
- ONNX Runtime version: 1.3.0
- Visual Studio version (if applicable): Visual Studio 2019 

**To Reproduce**
- Call new InferenceSession(model) on an Android device

**Comment by gwang-msft** [comment]
Currently the NNAPI does not support c# interface for Android, and it is not distributed through nuget.
For now NNAPI support c/c++ api through Android native library, or Java api through AAR archives.
You would need to build the NNAPI library yourself, using the instruction here, https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/NNAPI-ExecutionProvider.md

**Comment by d3v1anc3** [comment]
That clears things up, thanks! Building OnnxRuntime ourselves might be a bit too much for us right now. Is there a timeline or rough estimate on the general availability of NNAPI support for C#?

**Comment by thiennguyen1007** [comment]
@d3v1anc3 upgrade Xamarin.Android. Xamarin.Android 12, it worked for me

**Comment by MeBadDev** [comment]
Hi, any updates on this?
