### ISSUE TITLE
onnxruntime/cmake/external

### ISSUE THREAD

**Issue by cqray1990** [microsoft/onnxruntime#4365]
the files in onnxruntime/cmake/external needs download one by one ?

**Comment by cqray1990** [comment]
i want to know the files in onnxruntime/cmake/external needs download one by one? the external subdirectory  is empty
when i build onnxruntime,i raise the errors as follows:

Use gtest from submodule
CMake Error at CMakeLists.txt:318 (add_subdirectory):
The source directory

/home/lgx/onnxruntime-master/cmake/external/googletest

does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:319 (set_target_properties):
set_target_properties Can not find target to add properties to: gmock

CMake Error at CMakeLists.txt:320 (set_target_properties):
set_target_properties Can not find target to add properties to: gmock_main

CMake Error at CMakeLists.txt:321 (set_target_properties):
set_target_properties Can not find target to add properties to: gtest

CMake Error at CMakeLists.txt:322 (set_target_properties):
set_target_properties Can not find target to add properties to: gtest_main

CMake Error at CMakeLists.txt:323 (add_library):
add_library cannot create ALIAS target "GTest::gmock" because target
"gmock" does not already exist.

CMake Error at CMakeLists.txt:324 (add_library):
add_library cannot create ALIAS target "GTest::gmock_main" because target
"gmock_main" does not already exist.

CMake Error at CMakeLists.txt:325 (add_library):
add_library cannot create ALIAS target "GTest::gtest" because target
"gtest" does not already exist.

CMake Error at CMakeLists.txt:326 (add_library):
add_library cannot create ALIAS target "GTest::gtest_main" because target
"gtest_main" does not already exist.

CMake Error at CMakeLists.txt:366 (add_subdirectory):
The source directory

/home/lgx/onnxruntime-master/cmake/external/nsync

does not contain a CMakeLists.txt file.

Use protobuf from submodule
CMake Error at CMakeLists.txt:405 (add_subdirectory):
add_subdirectory given source
"/home/lgx/onnxruntime-master/cmake/external/protobuf/cmake" which is not
an existing directory.

CMake Error at CMakeLists.txt:414 (add_library):
add_library cannot create ALIAS target "protobuf::libprotobuf" because
target "libprotobuf" does not already exist.

**Comment by yuslepukhin** [comment]
git clone --recursive

**Comment by sohils** [comment]
What command to run when using tar ball?
