### ISSUE TITLE
onnxruntime fails to compile with c++20 compiler mode (VS2019)

### ISSUE THREAD

**Issue by ankurverma85** [microsoft/onnxruntime#4368]
**Describe the bug**
There are a few compiler errors when compiling in c++20  language mode with VS2019. 
Some of them can be mitigated with compiler definitions but others are blocking

**Urgency**
Most of the errors deal with usage of deprecated features in C++17 that were removed in C++20. 
With c++20 out on most publicly available compilers (VS2019, gcc, clang) this is going to prevent usage of additional features and integration with modern code

**System information**
- OS Platform and Distribution: Windows, Visual Studio 2019 16.6.2 (other compilers with have similiar issues)
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: latest
- Python version: 3.8.1
- Visual Studio version (if applicable): 16.6.2
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:

**To Reproduce**
Onnx runtime compiler as a sub module using add_subdiretory
The following cmake snippet should help reproduce the issue
```
set(CMAKE_CXX_STANDARD 20)
```

**Expected behavior**
Should compile cleanly as with c++17

**Screenshots**

**Additional context**
The following errors are observed

1)  Workaround mentioned below
```
onnxruntime\cmake\external\eigen\Eigen\src\Core\util\Meta.h(426): error C2065: 'type1': undeclared identifier

onnxruntime\cmake\external\eigen\Eigen\src\Core\util\Meta.h: 426
#if EIGEN_HAS_STD_RESULT_OF
template<typename T> struct result_of {
  typedef typename std::result_of<T>::type type1;
  typedef typename remove_all<type1>::type type;
};
#else
```
This can be overcome with adding an additional cmake snippet

```
add_definitions(-DEIGEN_HAS_STD_RESULT_OF=0)
```

2) Unable to find a workaround for this

```
onnxruntime\cmake\external\eigen\Eigen\src\Core\AssignEvaluator.h(860): error C2338: YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY
  onnxruntime\cmake\external\eigen\Eigen\src/Core/AssignEvaluator.h(830): note: see reference to function template instantiation 'void Eigen::internal::call_assignment_no_alias<Dst,Src,Func>(Dst &,const Src &,const Func &)' being compiled
          with
          [
              Dst=Eigen::Map<Eigen::Array<float,-1,1,0,-1,1>,0,Eigen::Stride<0,0>>,
              Src=Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<const float,const float>,Eigen::Map<Lhs,0,Eigen::Stride<0,0>>,Eigen::Map<Lhs,0,Eigen::Stride<0,0>>>,
              Func=Eigen::internal::assign_op<float,const float>
          ]
```

**Comment by sniper0110** [comment]
Were you able to find a workaround for this @ankurvdev ?
