### ISSUE TITLE
ArgumentException: Dimensions must contain elements

### ISSUE THREAD

**Issue by amirebrahimi** [microsoft/onnxruntime#4369]
**Describe the bug**
While debugging a network and splitting it into separate parts I reduced one part down to simply returning the first dimension of the shape. This exception occurs while running the model using the C# InferenceSample project. Exception occurs in Tensor.cs:309.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Build 18363
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: b41fcf1
- Python version: N/A
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source): cl.exe 19.26.28806 for x64
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
- Use the Microsoft.ML.OnnxRuntime.InferenceSample project
- Modify the sample to use the attached .onnx file (see below) and skip using the inputData from "bench.in" (i.e. initialize the input tensors without inputData)
- Run and notice the exception that occurs.

**Expected behavior**
Since the output is a scalar I'd still expect the dimensions to correctly show as 1.

**Screenshots**
![image](https://user-images.githubusercontent.com/904110/86062617-feceb900-ba1d-11ea-967b-079f3e2db665.png)

**Additional context**
[siamese_test_opt.zip](https://github.com/microsoft/onnxruntime/files/4848364/siamese_test_opt.zip)

**Comment by hariharans29** [comment]
Thanks for reporting. Yes, the C# API's Tensor class doesn't like scalars (tensors with zero dimensions) and logic in the c# layer should accommodate scalar creation. Will fix it. If you have a fix, contributions are welcome. :)

**Comment by amirebrahimi** [comment]
I tried some things at the C level like using Size() instead of size(), but that broke tests, so I reverted them. Do you foresee this being a change that is needed only on the C# side?

**Comment by hariharans29** [comment]
Yes, the native layer should handle scalars correctly. The change will be only in c#. Most likely, will be along the lines of modifying the if check that is throwing (and a few other places perhaps) and adding a test. I can make the change if it is too time consuming for you.

**Comment by amirebrahimi** [comment]
I added support as you suggested and added a single test for the use-case I encountered. You're welcome to add additional tests if it needs more coverage.

**Comment by hariharans29** [comment]
Thanks for the contribution., but are you rebased with current master ? It seems like there are changes in 75 files in the PR.

**Comment by amirebrahimi** [comment]
Looks like I started off of the last tagged release version. I'll merge latest master.

**Comment by amirebrahimi** [comment]
Not sure what happened with branches on that one, so I just started fresh off of master.
