### ISSUE TITLE
Windows x86 support CPU (and GPU?)

### ISSUE THREAD

**Issue by nietras** [Microsoft/onnxruntime#438]
We need to be able to execute ONNX models via C#/.NET on Windows 10 32-bit (x86) are there any plans to support this and a time horizon for that?

**Comment by jignparm** [comment]
The next release of OnnxRuntime will  contain x86 runtimes  (for CPU at a minimum), before end of March.

**Comment by mdabros** [comment]
Hi @jignparm,
From the [v0.3.0 release notes](https://github.com/Microsoft/onnxruntime/releases/tag/v0.3.0) it seems that the C#/.NET package is still x64, and that the x86 support is C only. If this is the case, then I don't believe this issue has been fully solved. 
Is the C#/.NET package for x86 also included in the release or does this come later?

**Comment by nietras** [comment]
@jignparm it does indeed look like x86 support has not been built into the .NET package yet:

![image](https://user-images.githubusercontent.com/10798831/54529270-adf99500-497f-11e9-84a5-fabc1b50ce4c.png)

From the `Microsoft.ML.OnnxRuntime.dll` assembly it can be seen this is `ILONLY` and uses PInvoke, so there should be no reason not being able to add the `win-x86` runtime so x86 is supported given that the C API can be compiled and works for x86.

**Comment by nietras** [comment]
We could perhaps open a new issue, given this issue wasn't specific about this being available in the nuget package as well.
