### ISSUE TITLE
Can't load model that converts input to float16, runs inner model in float16, converts output to float32 

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/onnxruntime#4405]
I have a PyTorch model, then I cast it to float16. Then I do a model wrapper that converts input to float16, runs the model, and then converts output to float32. I export this model as ONNX, exports succeeds. Loading this model fails in onnxruntime (version 1.3.0):

fp16 model wrapper code: https://github.com/vadimkantorov/convasr/blob/master/models.py#L12

I uploaded the faulty model to https://1drv.ms/u/s!Apx8USiTtrYmqfdilfB5n2HFqlCtcA?e=vPza5g

```
Traceback (most recent call last):
  File "train.py", line 73, in main
    onnxruntime_session = onnxruntime.InferenceSession(args.onnx)
  File "/miniconda/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers)
  File "/miniconda/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Type Error: Type (tensor(float)) of output arg (CastDef_19) of node () does not match expected type (tensor(float16))
```

**Comment by vadimkantorov** [comment]
Netron graph vis looks okay 
![model onnx](https://user-images.githubusercontent.com/1041752/86360199-51a0ae80-bc72-11ea-8fea-fced934168cb.png)

**Comment by hariharans29** [comment]
I lltake a look, thanks

**Comment by vadimkantorov** [comment]
Putting `x = x.to(torch.float16)` as the first statement of the model code (along with removing the wrapper) also produces this error

**Comment by hariharans29** [comment]
Hi @vadimkantorov - sorry for the delay. I figured out what the issue with this was. Will put in a fix for this soon.
