### ISSUE TITLE
CudaContext changes

### ISSUE THREAD

**Issue by solarflarefx** [microsoft/onnxruntime#4409]
**Describe the bug**
I am running OnnxRuntime with [managedCuda ](https://github.com/kunzmi/managedCuda) and it seems that when I run inference on the network, it changes the CudaContext.  Is there a way to prevent this from happening?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64-bit
- API: C#
- ONNX Runtime installed from (source or binary): From NuGet Package Manager
- ONNX Runtime version: 1.3.0
- Visual Studio version (if applicable): 2019
- CUDA/cuDNN version: 7.6.5

**Comment by askhade** [comment]
Could you add more details here? I don't understand the full context.  What are you trying to accomplish? What do you mean by it changes the CudaContext?

**Comment by faxu** [comment]
Please reopen and provide more details if further assistance is needed.
