### ISSUE TITLE
InferenceSession without ONNX Files

### ISSUE THREAD

**Issue by ardorem** [microsoft/onnxruntime#441]
**Is your feature request related to a problem? Please describe.**

InferenceSession only takes a file path as its input. 

**System information**
- ONNX Runtime version (you are using):
0.1.4

**Describe the solution you'd like**
It would be great if we can pass a Onnx.ModelProto as well. 

**Describe alternatives you've considered**
Export a ModelProto into a file and instantiate InferenceSession, which is not ideal in terms of performance. 

**Additional context**

**Comment by ardorem** [comment]
Thanks for your response! May I ask where and how the external data is read? 

Currently, I am doing the following two steps to define a model using ONNX helper and run inference: 
(1) save(model, onnx_file) and 
(2) rt.InferenceSession(onnx_file)
when the "model" is <class 'onnx.onnx_ONNX_RELEASE_ml_pb2.ModelProto'> and I created the model using helper.make_node, helper.make_tensor, etc.

Without having the requested feature, it's completely functional but I just wondered what the rationale behind this implementation decision is. Thanks once again! :)

**Comment by yufenglee** [comment]
We had a bit of discussion on this. The main reason to not have a public Load(ModelProto) API is that: It may crash ONNXRuntime if ModelProto is created with a different version of protobuf as ONNXRuntime. 
However, we leave a protected C++ API:https://github.com/Microsoft/onnxruntime/blob/7b37dc6105052efb91f02b621b19e5ec9edacec0/onnxruntime/core/session/inference_session.h#L261
If customers uses C++ API and are blocked by this decision, they can derive the InferenceSession and get access to it.

**Comment by snnn** [comment]
Hi @yufenglee, 

I missed the discussion. How could it be different versions?

If you mean the model was created from protobuf 2.6, then it was stored into disk and read by onnxruntime, which has protobuf 3.6.1. It's totally fine!

**Comment by yufenglee** [comment]
@ardorem I thought you were using c++ APIs. Just realized you are using python. Currently, our python API doesn't support to load from ModelProto. 'Export a ModelProto into a file and instantiate InferenceSession' is the way to go. In practice, you create/export model once, and then run InferenceSession for the model file whenever you want. I don't see a performance issue here.

**Comment by ardorem** [comment]
@yufenglee Yes I chose to go with this approach. I've developed several onnx models and been running their inferences using onnx runtime, which work great! Thanks! :)

**Comment by xkszltl** [comment]
It'll be great it there's at least an API for serialized proto in string, instead of going through disk.

**Comment by letmaik** [comment]
Please re-open this issue, I have the same constraint where I cannot rely on the model being accessible as file. I realize ONNX unfortunately has the concept of external files baked in now, but ultimately there should be an abstraction to provide the external parts in a flexible way, not strictly as files.

For now, I would be happy if there was a variant of `OrtCreateSession` (like `OrtCreateSessionWithBuffer`) that accepts a buffer and fails if the model references external data.

**Comment by xkszltl** [comment]
Similarly, there're scenario on our side where we don't want to persist any thing in an easily readable way, and it'll also be nice if we don't need write permission.

**Comment by linkerzhang** [comment]
for  self-contain model (it does not refer to external weight file), https://github.com/microsoft/onnxruntime/pull/718 is merged for fixing this issue.

**Comment by xkszltl** [comment]
If this is ready, would you do a v0.4.1?
Thanks

**Comment by faxu** [comment]
This will be released in the next official release and is in master.

**Comment by dsplabs** [comment]
Is it now possible to use Onnx.ModelProto with InferenceSession directly?

**Comment by JangminSon** [comment]
@dsplabs 
It can be done now with simple codes
``` python3
import onnx
import onnxruntime as ort
onnx_path= 'PATH/TO/YOUR/ONNX'
onnx_model = onnx.load(onnx_path)
onnx_model.SerializeToString()
onnx_session = ort.InferenceSession(onnx_model.SerializeToString())
```

**Comment by ijunejo** [comment]
trying to load a onnx model for inference using the exact code above: getting errors

File "...\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 231, in _create_inference_session
    sess.initialize_session(providers or [], provider_options or [])
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ON
[model.zip](https://github.com/microsoft/onnxruntime/files/13333749/model.zip)
NXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: C:\...../optimizer/initializer.h:88 onnxruntime::Initializer::Initializer size_ == size was false. size is different

**attached file is a zip file, just rename is to .onnx extension.**
