### ISSUE TITLE
Java API documentation has broken links

### ISSUE THREAD

**Issue by pranasblk** [microsoft/onnxruntime#4417]
**Describe the bug**
Java API descrition document: https://github.com/microsoft/onnxruntime/blob/master/docs/Java_API.md refers to broken link: https://github.com/microsoft/onnxruntime/blob/master/java/sample/ScoreMNIST.java

**Urgency**
Not urgent

**Comment by Craigacp** [comment]
This should be fixed when #4395 is merged.
