### ISSUE TITLE
Improve support for tensor element access (C/C++ API)

### ISSUE THREAD

**Issue by jgbradley1** [microsoft/onnxruntime#4422]
Currently after a tensor has been created with one of the `Ort::Value::CreateTensor()` functions, there is no easy way to check individual elements in a multidimensional tensor to verify the data blob has mapped correctly to an ORT tensor. For example, in [this](https://github.com/microsoft/onnxruntime/issues/2832) issue, the user takes it on faith that mapping OpenCV data to an ORT tensor _just works_ (assuming row-major order of the data).

I would like to propose a new helper function be added to the C/C++ API that would improve unit testing and inspection of ORT tensors.

**System information**
- ONNX Runtime version (you are using): master branch

**Describe the solution you'd like**
Perhaps a function called `At()` that could be used in the following manner:

```cpp
auto tensor = Ort::Value::CreateTensor(...)

// allow the user to write unit tests like below
for(size_t row=0; row<row_count; row++) {
  for(size_t col=0; col<col_count; col++) {
    for(size_t channel=0; channel< 3; channel++) {
      assert( tensor.At<float>({row, col, channel}) == imagedata(row, col, channel) ) // element access would probably be declared as an initializer_list
    }
  }
}
```

Obviously `At()` would extend to any multidimensional tensor access. I only used an image example for clarity.

**Comment by askhade** [comment]
@jgbradley1 : Would you like to propose a PR for this?

**Comment by jgbradley1** [comment]
@askhade yes, I'll submit a PR soon.

**Comment by jgbradley1** [comment]
@askhade PR has been submitted. Thanks!
