### ISSUE TITLE
Session load fails with Protobuf serialization failed

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#4424]
**Describe the bug**
Exported a modified BERT model.
When loading the model I get this error in the log:

> [libprotobuf ERROR /onnxruntime_src/cmake/external/protobuf/src/google/protobuf/message_lite.cc:379] onnx.ModelProto exceeded maximum protobuf size of 2GB: 2192699607

And then this is the exception:

> InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Protobuf serialization failed.

**Urgency**
Needed for new captioning model

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.2.0
- Python version: 3.6.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.

```python
    sess_options = rt.SessionOptions()
    sess_options.graph_optimization_level = rt.GraphOptimizationLevel.ORT_ENABLE_BASIC
    sess_options.optimized_model_filepath = onnxfile_optimized
    sess = rt.InferenceSession(onnxfile, sess_options)
```

results in 

> InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Protobuf serialization failed.

Normally loading the session however does not show that error:

```python
sess = rt.InferenceSession(onnxfile)
```

- Attach the ONNX model to the issue (where applicable) to expedite investigation.
Will send the model

**Expected behavior**

**Screenshots**

**Additional context**
This is BERT but with some changes

**Comment by askhade** [comment]
@dashesy : Protobuf messages have a limit of 2GB. For models whose size exceeds 2GB onnx has a provision to store large tensors as external data files. Latest version of pytorch exporter should also have this support.

While exporting set "use_external_data_format=True" for pytorch export call

Then follow this document to load such a model : https://github.com/onnx/onnx/blob/09a4e65bb098164491b021ffe563a559fbc1a808/docs/ExternalData.md

**Comment by dashesy** [comment]
Where does the data size come from? I can export the model from PyTorch (1.4) and the output file size is just 303MB
Does this mean the ONNX file may be corrupted?

**Comment by askhade** [comment]
What changes did you make to this model? I thought you made a legit modification to this model and this size increase is expected. Since after exporting your .onnx file size is 303MB and you are seeing this error it is possible the file is not exported right.

**Comment by dashesy** [comment]
Other features are used in the input. I will try PyTorch 1.5 first to see if exported model is different. I will send the onnx file to take a look, or the export code (internally)

**Comment by dashesy** [comment]
Closing this issue, the fix needs control-flow to avoid creating loops in graph.
