### ISSUE TITLE
Session.Run(inputs) returns null result

### ISSUE THREAD

**Issue by hanzigs** [microsoft/onnxruntime#4425]
I have this code for keras2onnx model prediction
```
var Session = new InferenceSession(modelPath);
float[] data = new float[] { 0.62382546f, -0.37804684f, -0.079906f, -0.45980235f, 0.34740723f, 0.00235355f, -0.29869863f,...};
var dimensions = new int[] { 1, 25 };
Tensor<float> tensorA = new DenseTensor<float>(data, dimensions); 
var inputs = new List<NamedOnnxValue>();
var t1 = NamedOnnxValue.CreateFromTensor<float>("dense_4_input", tensorA);          
inputs.Add(t1);
using (IDisposableReadOnlyCollection<DisposableNamedOnnxValue> results = Session.Run(inputs))
            {
                Console.WriteLine(results);
            }
```
results value should be a float '0.014536', I get null, may I know my issue, Thanks

**Comment by askhade** [comment]
@hanzigs : Can you add more details like ort version, platform etc.
Please follow the bug template :
https://github.com/microsoft/onnxruntime/issues/new?template=bug-performance-issue.md

**Comment by hanzigs** [comment]
![image](https://user-images.githubusercontent.com/30790120/86655554-262f1280-c02a-11ea-8bc3-7fb3b72c5bcf.png)
Windows 10 Pro
Keras model from
![image](https://user-images.githubusercontent.com/30790120/86655821-5c6c9200-c02a-11ea-8fbb-8e8fe3589334.png)
python 3.7.4

**Comment by hanzigs** [comment]
Found it, Thanks, simple steps worked anyway
```
            var results = Session.Run(inputs);
            var prediction = results.First().AsTensor<float>().First();
            Console.WriteLine(prediction);
```
