### ISSUE TITLE
Why is the onnx version down to 1.2 in the document docs/version.md that chapter is compatibility/version matrix?

### ISSUE THREAD

**Issue by zxgm** [microsoft/onnxruntime#4431]
Why is the onnx version down to 1.2 in the document docs/version.md that chapter is compatibility/version matrix?If i have pytorch pt model,i want to convert to onnx model,and use torch.onnx.export interface that set `opset_version=10`, what is the onnx release version ?What is the ONNX Runtime release version?

**Comment by askhade** [comment]
@zxgm : 
"down to" here refers to the lowest version supported for backward compatibility. 
For example ort 1.3.1 release is compatible with onnx release from 1.2 to 1.7

ONNX opset verison 10 corresponds to ONNX release 1.5 and as the table suggests you can use onnxruntime version starting from 0.4.0 with this model. 
![image](https://user-images.githubusercontent.com/6475296/86626324-62f00080-bf7b-11ea-812e-eac1d9fab416.png)

**Comment by zxgm** [comment]
I get the idea,thank you very much!
