### ISSUE TITLE
Porting the controller in C/C++ imagenet example to Linux 

### ISSUE THREAD

**Issue by jinz2014** [microsoft/onnxruntime#4441]
I am not clear how controller.cc and controller.h in the C/C++ Imagenet example can be ported to Linux. Please advise. Thanks.

**Comment by askhade** [comment]
Imagenet sample depends on ATL libraries which are part of the visual studio installation. Not sure if it is trivial to build this sample for Linux.
@Changming for more insights. 

Have you checked Tutorials repo: https://github.com/onnx/tutorials . There are plenty of examples which you can check out.

**Comment by jinz2014** [comment]
Thank  you for your reply. I think controller.cc and controller.h are the main roadblock for Linux.  I will check out onnx's tutorials.  I hope people at Microsoft will be interested in porting the sample to Linux.

**Comment by snnn** [comment]
Hi @jinz2014, the sample depends on Windows Thread Pool API, which is part of Windows Kernel. So it is not available on Linux. 

I suggest you may create a simplified sample reader. Basically, you should have a thread pool, which read and decode image files in multiple threads, and put the results in a queue. The sample reader is the producer of the queue, you should have another thread pool that consumes the queue and invoke ORT functions to run the inference.

**Comment by mikecaraman** [comment]
Hi @snnn, the imagenet example provides posix source code for synchronization and file system. What was the purpose of the posix API, is it still maintained?

**Comment by snnn** [comment]
Sorry I think it is not in active development.
