### ISSUE TITLE
How to import  onnxruntime when I build from source?

### ISSUE THREAD

**Issue by dongzhen123** [microsoft/onnxruntime#4450]
I have build the onnxruntime use "./build.sh --config RelWithDebInfo --build_shared_lib --parallel" successully.

Then how to import onnxruntime? or before I import onnxruntime what else should I do?

**Comment by jcwchen** [comment]
Hi @dongzhen123 
According to the [BUILD.md](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#apis-and-language-bindings), you need to add different flag for different APIs.

Take Python on Linux as an example, you should use something like:
```
# build the Python wheel file from source code
./build.sh --config RelWithDebInfo --build_shared_lib --parallel --build_wheel

# install Python wheel package
pip install build/Linux/RelWithDebInfo/dist/*.whl
```

Then you're all set.

**Comment by askhade** [comment]
Also use 
--enable_pybind along with the other flags mentioned above

**Comment by wwbnjsace** [comment]
> Hi @dongzhen123
> According to the [BUILD.md](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#apis-and-language-bindings), you need to add different flag for different APIs.
> 
> Take Python on Linux as an example, you should use something like:
> 
> ```
> # build the Python wheel file from source code
> ./build.sh --config RelWithDebInfo --build_shared_lib --parallel --build_wheel
> 
> # install Python wheel package
> pip install build/Linux/RelWithDebInfo/dist/*.whl
> ```
> 
> Then you're all set.

my build command is "./build.sh --config Release --build_shared_lib --build_wheel --enable_pybind --use_openvino " .but in the end it dose not generate any *.wh file in any location .
do you know why?
