### ISSUE TITLE
onnxruntime_test_all --gtest_filter=ActivationOpTest.Relu fails, cross-compile onnxruntime v1.3.1 against ACL v19.08

### ISSUE THREAD

**Issue by dhunt-ambarella** [microsoft/onnxruntime#4463]
Note: Google Test filter = ActivationOpTest.Relu
 [==========] Running 1 test from 1 test suite.
 [----------] Global test environment set-up.
 [----------] 1 test from ActivationOpTest
 [ RUN      ] ActivationOpTest.Relu
 free(): invalid pointer
 Aborted (core dumped)

All tests preceding this test (hundreds) are OK.  Some tests after fail also.

Also, but possibly not related:
# onnxruntime_perf_test -e acl testdata/squeezenet/model.onnx result.csv
 free(): invalid pointer
 Aborted (core dumped)
 #

onnxruntime v1.3.1 cross compiled with linaro-gcc8.2.

In onnxruntime, I changed these files:

onnxruntime/core/providers/acl/acl_execution_provider.cc

onnxruntime/core/providers/acl/acl_common.cc

onnxruntime/core/providers/acl/nn/conv.cc

 

In onnxruntime/core/providers/acl/acl_execution_provider.cc, pretend to use the return value from Register():

 

+  Status ret_val;
 +
 +  ret_val =
    kernel_registry.Register(BuildKernelCreateInfo<ONNX_OPERATOR_KERNEL_CLASS_NAME(kAclExecutionProvider, kOnnxDomain, 6, Relu)>());
 +  ret_val =
    kernel_registry.Register(BuildKernelCreateInfo<ONNX_OPERATOR_VERSIONED_KERNEL_CLASS_NAME(kAclExecutionProvider, kOnnxDomain, 7, 9, Gemm)>());

 

In onnxruntime/core/providers/acl/acl_common.cc, fixed an unused-variable warning:

 

--- a/onnxruntime/core/providers/acl/acl_common.cc
 +++ b/onnxruntime/core/providers/acl/acl_common.cc
 @@ -70,7 +70,8 @@ void importDataFromTensor(arm_compute::Tensor* tensor, T* data){
    // copy input tensor into the larger buffer
    arm_compute::execute_window_loop(
        aclInpuWindow,
 -      [&](const arm_compute::Coordinates& co) {
 +//      [&](const arm_compute::Coordinates& co) {
 +      [&](const arm_compute::Coordinates&) {

 

In onnxruntime/core/providers/acl/nn/conv.cc, fixed 'used uninitialized' error:

 

-  arm_compute::ActivationLayerInfo::ActivationFunction acl_activ_func;
 +  arm_compute::ActivationLayerInfo::ActivationFunction acl_activ_func = arm_compute::ActivationLayerInfo::ActivationFunction::RELU;

 

 

Also, to compile and link, there were changes to my environment.

 

In .bashrc, I added ACL include files to CPATH:

export ACL_VER="19.08"

export CPATH="/dump/dump201/dhunt/arm_compute-v${ACL_VER}-bin-linux/include:/dump/dump201/dhunt/arm_compute-v${ACL_VER}-bin-linux:$CPATH"

And for linking, I added this to environment:

export LD_RUN_PATH="/dump/dump201/dhunt/arm_compute-v${ACL_VER}-bin-linux/lib/linux-arm64-v8a-neon/"
 export LD_LIBRARY_PATH="/dump/dump201/dhunt/arm_compute-v${ACL_VER}-bin-linux/lib/linux-arm64-v8a-neon/"

 

I provided soft links to the ACL libraries so onnxruntime could find them.

 

dhunt@ubu-sw4:/dump/dump201/dhunt/onnxruntime$ ln -s /dump/dump201/dhunt/arm_compute-v19.08-bin-linux/lib/linux-arm64-v8a-neon/libarm_compute.so libarm_compute.so

dhunt@ubu-sw4:/dump/dump201/dhunt/onnxruntime$ ln -s /dump/dump201/dhunt/arm_compute-v19.08-bin-linux/lib/linux-arm64-v8a-neon/libarm_compute_core.so libarm_compute_core.so

dhunt@ubu-sw4:/dump/dump201/dhunt/onnxruntime$ ln -s /dump/dump201/dhunt/arm_compute-v19.08-bin-linux/lib/linux-arm64-v8a-neon/libarm_compute_graph.so libarm_compute_graph.so

 

I used this cmake command, and 'make -j 6' to build:

cmake -DCMAKE_TOOLCHAIN_FILE=/dump/dump201/dhunt/tool.cmake -Donnxruntime_CROSS_COMPILING=ON -Donnxruntime_RUN_ONNX_TESTS=OFF -Donnxruntime_DEV_MODE=ON -DPYTHON_EXECUTABLE=/opt/amba/cv2_third/tv2/exe/python3 -Donnxruntime_USE_CUDA=OFF -Donnxruntime_USE_NSYNC=OFF -Donnxruntime_CUDNN_HOME= -Donnxruntime_USE_JEMALLOC=OFF -Donnxruntime_ENABLE_PYTHON=OFF -Donnxruntime_BUILD_CSHARP=OFF -Donnxruntime_BUILD_SHARED_LIB=ON -Donnxruntime_USE_EIGEN_FOR_BLAS=ON -Donnxruntime_USE_OPENBLAS=OFF -Donnxruntime_USE_DNNL=OFF -Donnxruntime_USE_MKLML=OFF -Donnxruntime_USE_OPENMP=ON -Donnxruntime_USE_TVM=OFF -Donnxruntime_USE_LLVM=OFF -Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF -Donnxruntime_USE_BRAINSLICE=OFF -Donnxruntime_USE_NUPHAR=OFF -Donnxruntime_USE_EIGEN_THREADPOOL=OFF -Donnxruntime_BUILD_UNIT_TESTS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -Dprotobuf_WITH_ZLIB=OFF -DONNX_CUSTOM_PROTOC_EXECUTABLE=/dump/dump201/dhunt/protoc_3.11.3/bin/protoc -DCMAKE_VERBOSE_MAKEFILE=ON -Donnxruntime_USE_ACL=ON -Donnxruntime_USE_ACL_1902=OFF -Donnxruntime_USE_ACL_1905=OFF -Donnxruntime_USE_ACL_1908=ON -Donnxruntime_USE_ACL_2005=OFF cmake

 

cat tool.cmake

    SET(CMAKE_SYSTEM_NAME Linux)
     SET(CMAKE_SYSTEM_VERSION 1)
     SET(CMAKE_C_COMPILER /usr/local/linaro-aarch64-2018.08-gcc8.2/bin/aarch64-linux-gnu-gcc)
     SET(CMAKE_CXX_COMPILER /usr/local/linaro-aarch64-2018.08-gcc8.2/bin/aarch64-linux-gnu-g++)

 

 

After all that, the compile and link succeed.

**Comment by prabhat00155** [comment]
Looks like import_memory() https://github.com/microsoft/onnxruntime/blob/ee5ca27ae2b9d3994bc95287facf51d45b9fd180/onnxruntime/core/providers/acl/acl_common.cc#L58 (called from https://github.com/microsoft/onnxruntime/blob/ee5ca27ae2b9d3994bc95287facf51d45b9fd180/onnxruntime/core/providers/acl/activation/activations.cc#L34) is causing this issue.

**Comment by jywu-msft** [comment]
@Andrews548, @mikecaraman any ideas what could be going wrong here?

**Comment by jywu-msft** [comment]
maybe this is the reason? 
https://github.com/ARM-software/ComputeLibrary/issues/744#issuecomment-596609636

are you building ACL from source or using pre-built binaries?

**Comment by prabhat00155** [comment]
This works when ACL is built from source(just tried it). You only run into error when using pre-built binaries.

**Comment by dhunt-ambarella** [comment]
Yes.  Using prebuilt libraries.

I will ask my administrator to install scons.

Any chance someone can share the libraries that will work?

Also, I use v8a-neon libraries.  Not sure how to know which ones I should be using:
dhunt@ubu-sw4:/dump/dump201/dhunt/arm_compute-v19.08-bin-linux/lib$ ls -l
total 168
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-cl
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-cl-asserts
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-cl-debug
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-cl-gles
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-cl-gles-asserts
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-cl-gles-debug
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-gles
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-gles-asserts
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-gles-debug
**drwxrws--- 2 dhunt engr3 4096 Jul  3 12:42 linux-arm64-v8a-neon**
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-neon-asserts
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-neon-cl
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-neon-cl-asserts
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-neon-cl-debug
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-neon-cl-gles
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-neon-cl-gles-asserts
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-neon-cl-gles-debug
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-neon-debug
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-neon-gles
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-neon-gles-asserts
drwxrws--- 2 dhunt engr3 4096 Sep  2  2019 linux-arm64-v8a-neon-gles-debug

**Comment by prabhat00155** [comment]
I did a native build of ACL library, so it may not work on a different type of machine. You can use ACL 19.08 with onnxruntime using the following steps:
1) Download the ACL v19.08 source code from here: https://github.com/ARM-software/ComputeLibrary/releases/tag/v19.08 and extract it:
```
wget https://github.com/ARM-software/ComputeLibrary/archive/v19.08.tar.gz
gunzip v19.08.tar.gz
tar -xvf v19.08.tar 
```

2) Build ACL:
```
cd ComputeLibrary-19.08/
sudo apt install scons
sudo apt install g++-arm-linux-gnueabihf
scons -j8 arch=arm64-v8a  Werror=1 debug=0 asserts=0 neon=1 opencl=1 examples=1 build=native
```
3) Set environment variables(assuming you are under ComputeLibrary-19.08):
```
export CPATH=`pwd`/include/:`pwd`
export LD_LIBRARY_PATH=`pwd`/build/
```
4) Building onnxruntime with ACL 19.08:
```
./build.sh --config Release --use_acl ACL_1908
```
5) Run onnxruntime_perf_test with acl:
```
./onnxruntime_perf_test -x 4 -r times -n 1 -e acl ~/Documents/models/onnx/squeezenet1.1/squeezenet1.1.onnx result
```

**Comment by Dan5002** [comment]
Native build of ACL libraries was the fix.

**Comment by Dan5002** [comment]
Seems I can't close this myself.  It can be closed.
