### ISSUE TITLE
Direct GPU Inference

### ISSUE THREAD

**Issue by solarflarefx** [microsoft/onnxruntime#4464]
So it seems that the latest release of OnnxRuntime has the capability of direct GPU inference (meaning that if the tensors are already in the GPU then they do not need to be copied to the CPU and then passed back into the GPU but can instead be passed into the model directly from the GPU).

My question is which APIs have this capability?  It appears that the Python API has it, but do any of the other APIs have it as well?

**Comment by hariharans29** [comment]
The other language bindings will have them soon.

**Comment by eladior** [comment]
Is there documentation available about direct gpu inference? I'm interested in this capability.
