### ISSUE TITLE
Assertion failed: f.pitches[i] >= s

### ISSUE THREAD

**Issue by GrzegorzKarchNV** [microsoft/onnxruntime#4478]
**Describe the bug**
When loading an ONNX model in python with onnxruntime.InferenceSession(), I get the `Assertion failed: f.pitches[i] >= s`.
The model was generated using `torch.onnx.export`, opset=12, in PyTorch container `nvcr.io/nvidia/pytorch:20.06-py3`
**Urgency**
I have a model in ONNX format that I would like to test.

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04:
- ONNX Runtime installed from docker: https://github.com/microsoft/onnxruntime/blob/v1.3.1/dockerfiles/Dockerfile.tensorrt
- ONNX Runtime version: 1.3.1
- Python version: 3.7
- CUDA version: 10.2.89
- CUDA driver version: 440.33.01
- CUDNN version: 7.6.5.32
- GPU model and memory: NVIDIA TitanV 12gb

**To Reproduce**
Follow instructions to build onnxruntime-trt
https://github.com/microsoft/onnxruntime/tree/master/dockerfiles#tensorrt
In the docker, with accessible ONNX model: https://drive.google.com/file/d/1lPN2iANiI7mjm1V2XkguFPds2Q0KSzb8/view?usp=sharing
```bash
# python3.7
in interpreter:
>>> import onnxruntime as ort
>>> sess = ort.InferenceSession("waveglow.onnx")
```
- ONNX model: 

**Expected behavior**
Successful model loading

**Additional context**
command and full error:
```bash
>import onnxruntime as ort
>sess = ort.InferenceSession("triton_models/waveglow/1/waveglow.onnx")
2020-07-10 09:56:30.231246592 [W:onnxruntime:Default, tensorrt_execution_provider.h:36 log] [2020-07-10 09:56:30 WARNING] /code/onnxruntime/cmake/external/onnx-tensorrt/onnx2trt_utils.cpp:235: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
2020-07-10 09:56:30.231284361 [W:onnxruntime:Default, tensorrt_execution_provider.h:36 log] [2020-07-10 09:56:30 WARNING] /code/onnxruntime/cmake/external/onnx-tensorrt/onnx2trt_utils.cpp:261: One or more weights outside the range of INT32 was clamped
...
2020-07-10 09:56:32.539329200 [W:onnxruntime:Default, tensorrt_execution_provider.h:36 log] [2020-07-10 09:56:32 WARNING] /code/onnxruntime/cmake/external/onnx-tensorrt/onnx2trt_utils.cpp:261: One or more weights outside the range of INT32 was clamped
2020-07-10 09:57:11.654768766 [W:onnxruntime:Default, tensorrt_execution_provider.h:36 log] [2020-07-10 09:57:11     BUG] Assertion failed: f.pitches[i] >= s
../builder/tacticOptimizer.cpp:617
Aborting...

2020-07-10 09:57:11.664716702 [W:onnxruntime:Default, tensorrt_execution_provider.h:36 log] [2020-07-10 09:57:11   ERROR] ../builder/tacticOptimizer.cpp (617) - Assertion Error in shrink: 0 (f.pitches[i] >= s)
---------------------------------------------------------------------------
EPFail                                    Traceback (most recent call last)
<ipython-input-2-9e2b45df1a75> in <module>
----> 1 sess = ort.InferenceSession("triton_models/waveglow/1/waveglow.onnx")

/opt/miniconda/lib/python3.7/site-packages/onnxruntime/capi/session.py in __init__(self, path_or_bytes, sess_options, providers)
    156         self._path_or_bytes = path_or_bytes
    157         self._sess_options = sess_options
--> 158         self._load_model(providers or [])
    159         self._enable_fallback = True
    160         Session.__init__(self, self._sess)

/opt/miniconda/lib/python3.7/site-packages/onnxruntime/capi/session.py in _load_model(self, providers)
    175             raise TypeError("Unable to load from type '{0}'".format(type(self._path_or_bytes)))
    176
--> 177         self._sess.load_model(providers)
    178
    179         self._sess_options = self._sess.session_options

EPFail: [ONNXRuntimeError] : 11 : EP_FAIL : TensorRT EP could not build Engine for fused node: TensorrtExecutionProvider_TRTKernel_graph_torch-jit-export_0_0
```

**Comment by askhade** [comment]
@stevenlix Can you take a look at this? Is this model supported in TensorRT EP?

**Comment by stevenlix** [comment]
For the two inputs, mel and z, can you specify what shapes are you using in your test? I try to generate synthetic data to reproduce the issue.
BTW, current TensorRT release may have limited support to ONNX Opset12. That could be the issue.

**Comment by stevenlix** [comment]
One more thing, since the model has FP16 precision, to run on TRT, you need to set env variable ORT_TENSORRT_FP16_ENABLE to 1 (Details can be found in TRT EP doc, https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/TensorRT-ExecutionProvider.md#configuring-environment-variables)

**Comment by GrzegorzKarchNV** [comment]
Hi @stevenlix, I updated locally TensorRT version in the Dockerfile and I just noticed you did the same in https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.tensorrt . With the updated version loading ONNX model and running inference works as expected. Thanks!
