### ISSUE TITLE
Different Output when Inference on CPU / GPU in some case

### ISSUE THREAD

**Issue by hirokic5** [microsoft/onnxruntime#4488]
**Describe the bug**
The output of onnx model with GPU seems to different from that with CPU in some case(in my case, segmentation! ).

**Urgency**
ASAP

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows10 64bit
- ONNX Runtime installed from (source or binary):binary (by pip install onnxruntime-gpu)
- ONNX Runtime version:1.3.0
- Python version:3.7.2
- Visual Studio version (if applicable):2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:CUDA 10.1 cuDNN 7.6.5
- GPU model and memory:1080Ti 

**To Reproduce**
I trained segmentation model in keras, and using [keras2onnx](https://github.com/onnx/keras-onnx/tree/master/keras2onnx), convert keras model to onnx model.   
But there seems to be non-negligible difference outputs of these models. 
Here is an example. Dog Segmentation. 

![onnx_segmentation_gpu](https://user-images.githubusercontent.com/19792127/87217259-2f99e100-c382-11ea-8bbd-28d93303f5ab.png)

![onnx_segmentation_cpu](https://user-images.githubusercontent.com/19792127/87217293-830c2f00-c382-11ea-95f6-0b0f1b2073a5.png)

The output of onnxruntime on **CPU** is almost same as that of keras, but Output of onnxruntime on GPU seems to be different !!! 

By the way, for classification model , the output of onnxruntime on GPU is almost same as that of keras... 

![onnx_classification_gpu](https://user-images.githubusercontent.com/19792127/87217305-ae8f1980-c382-11ea-8478-3e2e1cbd2957.png)

And [here](https://drive.google.com/drive/folders/1Ph8KC1zj17OUGsxMOEvnAaKf8r0_Hmvv?usp=sharing) is source code & weights & image. 

Did I have mistake when convert keras model , or when inference on GPU ? 

Thank you.

**Expected behavior**
the outputs are almost same in keras / onnxruntime on CPU / onnxruntime on GPU

**Comment by hariharans29** [comment]
Hi @hirokic5,

Which of these 2 models gives the diffs between CPU and GPU ? - 

![image](https://user-images.githubusercontent.com/9969784/87362302-1da37400-c523-11ea-97ff-116b3d9e8336.png)

**Comment by hirokic5** [comment]
thanks for reply!  
sorry for the bad naming...   
- keras_efficientNetB0.onnx : classification
- keras_efficientNetB0_Unet.onnx : segmentation  

so,  **keras_efficientNetB0_Unet.onnx** gives the diffs between CPU and GPU !

**Comment by hariharans29** [comment]
Hi @hirokic5,

1) What is the percentage diff that you see (i.e.) abs(diff) / ground_truth_value ?

2) Could you please provide the raw input tensor (after all relevant pre-processing) in .pb format ? It should be very simple via the onnx python APIs - https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md. Please look for  # Save the TensorProto

**Comment by hariharans29** [comment]
I could repro this and I have the cause for this. I ll update this issue when we finalize on a solution.

**Comment by hirokic5** [comment]
@hariharans29
sorry i missed your message...   

and thank you for your updating!!!

**Comment by dominikabasaj** [comment]
@hariharans29 Hi, should using the onnxruntime with changes merged by this PR: https://github.com/microsoft/onnxruntime/pull/4627 (1.5.1 at least I guess) enough to solve this issue, or should I also use a specific opset?
