### ISSUE TITLE
Aggregate Operators ("functions") should favor primary EP over secondary EP

### ISSUE THREAD

**Issue by fdwr** [microsoft/onnxruntime#4502]
When one executive provider has priority over another (e.g. the DirectML/CUDA EP over the CPU EP), ORT decomposes aggregate operators into their constituent operators, and the graph rightly executes using DML/CUDA EP for each constituent. For example, `DynamicQuantizeLinear` decomposes into multiple operators, and those constituents can all run on the GPU.

Once a lower priority EP registers a kernel for that operator though (e.g. `DynamicQuantizeLinear` being newly registered for CPU, while there is no kernel for DirectML), ORT <i>then</i> favors the lower priority provider instead of the decompositions into the higher priority provider. This sounds like a good thing (a single operator instead of multiple), but it can become a significant perf regression, because GPU <-> CPU synchronization is costly, and executing multiple component operators on the GPU is faster than executing a single operator on the CPU, which stalls the whole pipeline in and out of that node.

**System information**
- ONNX Runtime version: v1.3.1

**Describe the solution you'd like**
Prefer an operator decomposition using a higher priority provider over an atomic kernel definition of a lower priority provider. As an algorithm, it would be...

For each node:
1. If a kernel definition (whether atomic operator or aggregate operator) is found in <s>any provider</s> <i>the current provider</i> (in priority order), use that kernel - goto end.
2. If it’s a decomposable aggregate operator.
    a. If all constituent operators are supported with the current provider, decompose using the current provider. Goto step 1.
    b. If more providers remain, advance to the next current provider and goto step 1.
    c. Decompose the aggregate, and resume at step 1 for all new nodes (restarting from highest priority provider)
4. If more providers remain, advance to the next current provider and goto step 1.
5. If still no kernel found (all providers exhausted), then error.

**Describe alternatives you've considered**
One simpler alternative would be that step 2a ignores whether the decomposed operators are all supported by the current provider. This could lead to some even worse cases though, as some decomposed operators may be on the GPU and others on the CPU, causing even more stalls.

**Additional context**
NA

**Comment by skottmckay** [comment]
Feels like doing this during partitioning is overly complicated and may not be the right place to address the issue as it's unknown whether choosing a single CPU based implementation would always be worse or not. Depending on the device or the complexity of the function the best choice may differ and the EP author may be the only one able to say for sure which should be chosen.

Instead maybe there should be a convenient setup for the EP author to register a kernel that executes the function based operator using the constituent operators. Not sure what would be required to set that up. @codemzs may have a better idea how hard this would be to do.
