### ISSUE TITLE
use shared library for onnx

### ISSUE THREAD

**Issue by mslacken** [microsoft/onnxruntime#4508]
**Problem**
At the moment it is not possible to use system libraries for ONNX and protobuf at the same time. imho this is due to the fact, that ONNXRUNTIME uses sllghtly different `*.proto` files for building its internal ONNX library.

**Workaround**
By removing the FATAL_ERROR in https://github.com/microsoft/onnxruntime/blob/a95ae164f7e21c2f31f4748e127b52c075c6ecb3/cmake/CMakeLists.txt#L421
and making `onnx` and `onnx_proto` shared (but not install them) in
https://raw.githubusercontent.com/microsoft/onnxruntime/master/cmake/onnx/CMakeLists.txt
it is possible to compile a version of onnxruntime which consumes the `libonnx` and `libonnx_proto` found the system . To get this working proto files from ONNX have to replaced by the proto files from ONNXRUNTIME when building ONNX.

**Desired solution**
ONNRUNTIME should be able to use ONNX library when ``onnxruntime_PREFER_SYSTEM_LIB=ON`` is used.

**System information**
- ONNX Runtime version 1.3.1

**Comment by snnn** [comment]
Currently, onnxruntime uses a different version of ONNX with some private patches. So the system ONNX lib won't work.

**Comment by snnn** [comment]
onnxruntime version and ONNX version are highly tightened,  one onnxruntime version can only support one ONNX version. There is no benefit of doing this except it may save a few hundred KBs disk space.

**Comment by mslacken** [comment]
> Currently, onnxruntime uses a different version of ONNX with some private patches. So the system ONNX lib won't work.

I did only see the use of the proto files of ONNXRUNTIME when compiling the ONNX part. Are there also other patches I did not see?

**Comment by mslacken** [comment]
> onnxruntime version and ONNX version are highly tightened, one onnxruntime version can only support one ONNX version. There is no benefit of doing this except it may save a few hundred KBs disk space, but it will create more trouble to you. 
Its not about diskspace, its about packaging and security. When there is an security issue with protobuf for example and the standard static compiled ONNXRUNTIME is used, this security issue:
a)  is not visible for a user and
b) can't be fixed by simply updating protobuf
but ONNXRUNTIME has to be recompiled and reinstalled. 
The same holds true for any issues with ONNX itself.
> Think about this, what if ONNX released a new version, but onnxruntime hasn't? How will you cooperate this?
The common solution for this is using not libonnx.so.${version} so that different versions of the same library can exists on a system. Unfortunately ONNX does not support this.
My question is now, will it be possible to use an unpatched versions of ONNX in the future? So is there a chance that the proto files from ONNXRUNTIME will be used in ONNX?
Or is it possible to rename the ONNX part during the build. I already tried that by changing the namespace in 
https://github.com/microsoft/onnxruntime/blob/cf92497c160b3a72ae663ab4dd9cd818331b62db/cmake/onnx/CMakeLists.txt#L45
and renaming the libraries in that file, but did not succeed. Do you think this is possible?

**Comment by snnn** [comment]
> will it be possible to use an unpatched versions of ONNX in the future? 

Let me try it. So far, technically it is possbile.

**Comment by mslacken** [comment]
> > will it be possible to use an unpatched versions of ONNX in the future?
> 
> Let me try it. So far, technically it is possbile.

Awesome, this would be great.
For the `CmakeList.txt ` needed following change
```
find_package(ONNX)
if(ONNX_FOUND)
  target_include_directories(onnx_proto INTERFACE "${ONNX_INCLUDE_DIRS}/onnx")
  target_include_directories(onnx_proto INTERFACE $<TARGET_PROPERTY:protobuf::libprotobuf,INTERFACE_INCLUDE_DIRECTORIES> "${ONNX_INCLUDE_DIRS}/onnx")
  target_include_directories(onnx INTERFACE "${ONNX_INCLUDE_DIRS}/onnx")
  set_target_properties(onnx PROPERTIES FOLDER "${ONNX_INCLUDE_DIRS}/onnx")
  set_target_properties(onnx_proto PROPERTIES FOLDER "${ONNX_INCLUDE_DIRS}/onnx")
else()
  add_subdirectory(onnx)
endif()
```

**Comment by snnn** [comment]
#4878

**Comment by snnn** [comment]
Hi @mslacken

Welcome to submit your cmake change!
