### ISSUE TITLE
Question about Tensorflow_Keras_Bert-Squad_OnnxRuntime_CPU.ipynb

### ISSUE THREAD

**Issue by 652994331** [microsoft/onnxruntime#4513]
Hi, i am following this tutorial and have 2 questions. The first one is , after i finished this part:
![image](https://user-images.githubusercontent.com/51428350/87481022-1a160700-c661-11ea-8672-c46f595ce21a.png)
the result i got was length 512 = 486ms not 94ms.

The other one is, i have a question, why the average inference time for original tensorflow(100 sentenses) is 94 ms, but the inference time for onnx is 300+ms ~ 600+ms. i thought onnxruntime's a oprimization method so it should have better result right? 
Thank you

**Comment by pranavsharma** [comment]
@tianleiwu can you take a look? thx.

**Comment by tianleiwu** [comment]
@652994331, thanks for the feedback. 

It seems that Tensorflow 2.2 used GPU when running the notebook. After disabling GPU, latency of tensorflow is more than 1000 ms in the test machine. 

I will send a pull request ot update the notebook.

**Comment by tianleiwu** [comment]
Close this issue. Feel free to reopen it or create new one if you encountered issue.
