### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by tanjiarui** [Microsoft/onnxruntime#453]
**Describe the bug**
I tried to build up a demo from [here](https://github.com/onnx/models/tree/master/mnist), onnx version 1.3. Yet, the terminal gave such a feedback.

> interrupted by signal 11: SIGSEGV

Here is my code.

import onnxruntime, numpy as np

input=np.random.randint(0,256,(1,1,28,28)).astype(np.float32)
session = onnxruntime.InferenceSession('model.onnx')
result=session.run(None,{'Input3':input})
print(result)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary):pip
- ONNX Runtime version:0.2.1
- Python version:3.6
- GCC/Compiler version (if compiling from source):no
- CUDA/cuDNN version:no
- GPU model and memory:8G RAM

**Comment by snnn** [comment]
Hi, I can't reproduce your error.

script:
```python3
import onnxruntime, numpy as np

input=np.random.randint(0,256,(1,1,28,28)).astype(np.float32)
session = onnxruntime.InferenceSession('model.onnx')
result=session.run(None,{'Input3':input})
print(result)
```
Model file: 
```bash
curl -O -L 'https://onnxzoo.blob.core.windows.net/models/opset_8/mnist/mnist.tar.gz'
tar -zxvf mnist.tar.gz
cp mnist/model.onnx .
```
env:

```bash
docker run --privileged --security-opt seccomp=unconfined -it  --runtime=nvidia --rm -e DISPLAY ubuntu:16.04 /bin/bash
apt-get install python3 python3-pip curl
pip3 install onnx==1.3
pip3 install onnxruntime
```

**Comment by tanjiarui** [comment]
> Hi, I can't reproduce your error.
> script:
> import onnxruntime, numpy as np
> 
> input=np.random.randint(0,256,(1,1,28,28)).astype(np.float32)
> session = onnxruntime.InferenceSession('model.onnx')
> result=session.run(None,{'Input3':input})
> print(result)
> Model file:
> curl -O -L 'https://onnxzoo.blob.core.windows.net/models/opset_8/mnist/mnist.tar.gz'
> tar -zxvf mnist.tar.gz
> cp mnist/model.onnx .
> env:
> docker run --privileged --security-opt seccomp=unconfined -it  --runtime=nvidia --rm -e DISPLAY ubuntu:16.04 /bin/bash
> apt-get install python3 python3-pip curl
> pip3 install onnx==1.3
> pip3 install onnxruntime

So did the result output something?

**Comment by snnn** [comment]
Yes. And it didn't crash.

**Comment by snnn** [comment]
What's your CPU model?

**Comment by tanjiarui** [comment]
core i5-7200U 2.5GHz by 4

**Comment by faxu** [comment]
@tanjiarui: do you still need assistance with this issue or did you get this working?

**Comment by tanjiarui** [comment]
The problem is still out there. @faxu

**Comment by snnn** [comment]
Hi @tanjiarui 
Could you please run your program with [valgrind](http://valgrind.org/) so that we can get a glue where it crashed ?

**Comment by tanjiarui** [comment]
Hi @snnn, thanks for your advice! This trouble is finally fixed. It turned out an overlooked hint.
No module named 'numpy.core._multiarray_umath'
It was working after I upgraded the numpy. I should have noticed that before. (,,•́ . •̀,,)
