### ISSUE TITLE
A Test Failed Randomly

### ISSUE THREAD

**Issue by wschin** [microsoft/onnxruntime#4534]
**Describe the bug**
A `orttraining-win-gpu-ci-pipeline` CI fails because of the reason below.

NegativeLogLikelihoodLoss_LargeSizeTensor
D:\2\s\onnxruntime\test\providers\compare_provider_test_utils.cc:132
Expected equality of these values:
  ret.first
    Which is: 4-byte object <01-00 00-00>
  COMPARE_RESULT::SUCCESS
    Which is: 4-byte object <00-00 00-00>
expected 983.578 (4475e500), got 983.963 (4475fda0), diff: 0.384766, tol=0.0984578 idx=0. 1 of 1 differ
Google Test trace:
D:\2\s\onnxruntime\test\common\tensor_op_test_utils.cc(12): ORT test random seed: 1669118068

**Urgency**
It doesn't block  anything. Just an opportunity to improve the numerical stability of that loss function.

**System information**
Here it the link to my CI log: https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=184351&view=logs&j=a01f3837-f8bf-5f96-44c7-7d32eb3bcea6

**Comment by pranavsharma** [comment]
@wschin can you assign this to the right person? thx.

**Comment by snnn** [comment]
Sherlock Huang is looking into this.

**Comment by snnn** [comment]
The test is disabled now.
