### ISSUE TITLE
In function __cxx_global_var_init undefined reference to `OrtGetApiBase'

### ISSUE THREAD

**Issue by AliceSchaw** [microsoft/onnxruntime#4539]
**Describe the bug**

I built the static libraries for android, all of things were fine, but failed to link.  In function `__cxx_global_var_init':
/Downloads/onnxruntime/include/onnxruntime/core/session/onnxruntime_cxx_api.h:53: undefined reference to `OrtGetApiBase'

nm -g --defined-only libonnxruntime_session.a  （the function exists）
0000000000000000 T OrtGetApiBase

cmake build command
`cmake -GNinja -Donnxruntime_RUN_ONNX_TESTS=OFF -Donnxruntime_BUILD_WINML_TESTS=OFF -Donnxruntime_GENERATE_TEST_REPORTS=OFF -Donnxruntime_DEV_MODE=OFF -DPYTHON_EXECUTABLE=/usr/local/opt/python/bin/python3.7 -Donnxruntime_USE_CUDA=OFF  -Donnxruntime_USE_FEATURIZERS=OFF -Donnxruntime_USE_JEMALLOC=OFF -Donnxruntime_USE_MIMALLOC_STL_ALLOCATOR=OFF -Donnxruntime_USE_MIMALLOC_ARENA_ALLOCATOR=OFF -Donnxruntime_ENABLE_PYTHON=OFF -Donnxruntime_BUILD_CSHARP=OFF -Donnxruntime_BUILD_JAVA=OFF -Donnxruntime_BUILD_NODEJS=OFF -Donnxruntime_BUILD_SHARED_LIB=OFF -Donnxruntime_USE_EIGEN_FOR_BLAS=ON -Donnxruntime_USE_OPENBLAS=OFF -Donnxruntime_USE_DNNL=OFF -Donnxruntime_USE_MKLML=OFF -Donnxruntime_USE_NGRAPH=OFF -Donnxruntime_USE_OPENVINO=OFF -Donnxruntime_USE_OPENVINO_MYRIAD=OFF -Donnxruntime_USE_OPENVINO_GPU_FP32=OFF -Donnxruntime_USE_OPENVINO_GPU_FP16=OFF -Donnxruntime_USE_OPENVINO_CPU_FP32=OFF -Donnxruntime_USE_OPENVINO_VAD_M=OFF -Donnxruntime_USE_OPENVINO_VAD_F=OFF -Donnxruntime_USE_OPENVINO_BINARY=OFF -Donnxruntime_USE_NNAPI_DNNLIBRARY=ON -Donnxruntime_USE_NNAPI_BUILTIN=OFF -Donnxruntime_USE_RKNPU=OFF -Donnxruntime_USE_OPENMP=OFF -Donnxruntime_USE_TVM=OFF -Donnxruntime_USE_LLVM=OFF -Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF -Donnxruntime_USE_VITISAI=OFF -Donnxruntime_USE_NUPHAR=OFF -Donnxruntime_USE_TENSORRT=OFF -Donnxruntime_TENSORRT_HOME= -Donnxruntime_USE_MIGRAPHX=OFF -Donnxruntime_MIGRAPHX_HOME= -Donnxruntime_CROSS_COMPILING=OFF -Donnxruntime_DISABLE_CONTRIB_OPS=OFF -Donnxruntime_DISABLE_ML_OPS=OFF -Donnxruntime_DISABLE_RTTI=OFF -Donnxruntime_MSVC_STATIC_RUNTIME=OFF -Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF -Donnxruntime_USE_DML=OFF -Donnxruntime_USE_WINML=OFF -Donnxruntime_BUILD_FOR_WINDOWS_STORE=OFF -Donnxruntime_USE_TELEMETRY=OFF -Donnxruntime_ENABLE_LTO=OFF -Donnxruntime_USE_ACL=OFF -Donnxruntime_USE_ACL_1902=OFF -Donnxruntime_USE_ACL_1905=OFF -Donnxruntime_USE_ACL_1908=OFF -Donnxruntime_USE_ARMNN=OFF -Donnxruntime_ARMNN_RELU_USE_CPU=ON -Donnxruntime_ENABLE_NVTX_PROFILE=OFF -Donnxruntime_ENABLE_TRAINING=OFF -Donnxruntime_USE_HOROVOD=OFF -Donnxruntime_BUILD_BENCHMARKS=OFF -DCMAKE_TOOLCHAIN_FILE=android-sdk/ndk/21.3.6528147/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=android-23 -DANDROID_ABI=arm64-v8a -DONNX_CUSTOM_PROTOC_EXECUTABLE=onnxruntime/build/Linux/host_protoc/protoc -Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF -Donnxruntime_ENABLE_MEMLEAK_CHECKER=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_ANDROID_STL_TYPE=c++_shared ..`

```
Build command failed.
Error while executing process  /mytools/android-sdk/cmake/3.10.2.4988404/bin/ninja with arguments {-C  /app/.cxx/cmake/release/arm64-v8a assistence}
ninja: Entering directory ` /app/.cxx/cmake/release/arm64-v8a'
[1/1] Linking CXX shared library  /app/build/intermediates/cmake/release/obj/arm64-v8a/libassistence.so
FAILED:  /app/build/intermediates/cmake/release/obj/arm64-v8a/libassistence.so 
: &&  /mytools/android-sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --target=aarch64-none-linux-android24 --gcc-toolchain= /mytools/android-sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot= /mytools/android-sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -std=c++14 -O2 -DNDEBUG  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libassistence.so -o  /app/build/intermediates/cmake/release/obj/arm64-v8a/libassistence.so CMakeFiles/assistence.dir/helper/JNIHelp.cpp.o CMakeFiles/assistence.dir/helper/JniConstants.cpp.o CMakeFiles/assistence.dir/assistence.cpp.o   /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_calib3d.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_core.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_dnn.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_features2d.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_flann.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_gapi.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_highgui.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_imgcodecs.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_imgproc.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_ml.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_objdetect.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_photo.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_stitching.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_video.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_videoio.a  /Downloads/onnxruntime/cmake/mybuild/libonnxruntime_session.a  /app/src/main/cpp/../../../../dynamiclibs/arm64-v8a/libMNN.so libinference.a -landroid -ljnigraphics  /mytools/OpenCV-android-sdk4.3.0/sdk/native/3rdparty/libs/arm64-v8a/liblibprotobuf.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/3rdparty/libs/arm64-v8a/libade.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_imgcodecs.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/3rdparty/libs/arm64-v8a/liblibjpeg-turbo.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/3rdparty/libs/arm64-v8a/liblibwebp.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/3rdparty/libs/arm64-v8a/liblibpng.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/3rdparty/libs/arm64-v8a/liblibtiff.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/3rdparty/libs/arm64-v8a/liblibjasper.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/3rdparty/libs/arm64-v8a/libIlmImf.a -landroid -llog -lmediandk  /mytools/OpenCV-android-sdk4.3.0/sdk/native/3rdparty/libs/arm64-v8a/libquirc.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_calib3d.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_features2d.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_flann.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_imgproc.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/staticlibs/arm64-v8a/libopencv_core.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/3rdparty/libs/arm64-v8a/libtbb.a -lc -lz  /mytools/OpenCV-android-sdk4.3.0/sdk/native/3rdparty/libs/arm64-v8a/libcpufeatures.a  /mytools/OpenCV-android-sdk4.3.0/sdk/native/3rdparty/libs/arm64-v8a/libittnotify.a -ldl -lm -llog  /mytools/OpenCV-android-sdk4.3.0/sdk/native/3rdparty/libs/arm64-v8a/libtegra_hal.a -latomic -lm && :
libinference.a(OnnxInference.cpp.o): In function `__cxx_global_var_init':
 /Downloads/onnxruntime/include/onnxruntime/core/session/onnxruntime_cxx_api.h:53: undefined reference to `OrtGetApiBase'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**System information**
- OS Platform and Distribution (MAC build for android):
- ONNX Runtime installed from source:
- ONNX Runtime version: 1.3.1
- Python version: python3.7
- Compiler version  android clang

**To Reproduce**
failed to link.

**Comment by snnn** [comment]
Could you change onnxruntime_BUILD_SHARED_LIB to ON and use the shared library libonnxruntime.so ?

**Comment by AliceSchaw** [comment]
Thank you, Using the shared library is fine.
