### ISSUE TITLE
Impossible to Compile an source code to run onnx with Arm Compute Library

### ISSUE THREAD

**Issue by kuroro20** [microsoft/onnxruntime#4540]
OS: Ubuntu 18.04
Target : Cortex A-53
Compiler : gcc version 7.5.0 (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04)
ACL Version 19.08
Onnxruntime: master branch
- ONNX Runtime installed from source:

I'm trying to use onnxruntime on ARM.
Given the sample model-explorer.cpp , i ran sucessfully my model on ARM without ACL.

Then I built Onnx with Arm Compute Library.

Following this README : https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/ACL-ExecutionProvider.md

I tried to run my model with InferenceSession but when i try to include "inference_session.h" I have an error from gcc (attached file) and i don't know if i'm not doing the right includes or if i missed something during the build ?

It looks like a bad include but it looks like the right include file to me.

[log.txt](https://github.com/microsoft/onnxruntime/files/4936981/log.txt)

The error starts with this :
`In file included from ../../cmake/external/onnx/onnx/defs/shape_inference.h:4:0,
                 from ../../cmake/external/onnx/onnx/defs/schema.h:24,
                 from ../../include/onnxruntime/core/graph/onnx_protobuf.h:36,
                 from ../../include/onnxruntime/core/framework/data_types.h:16,
                 from ../../include/onnxruntime/core/framework/tensor.h:16,
                 from ../../include/onnxruntime/core/framework/execution_provider.h:11,
                 from ../../onnxruntime/core/framework/execution_providers.h:12,
                 from ../../onnxruntime/core/session/inference_session.h:13,
                 from model-explorer.cpp:38:
../../cmake/external/onnx/onnx/proto_utils.h: In function ‘std::vector<T> ONNX_NAMESPACE::RetrieveValues(const ONNX_NAMESPACE::AttributeProto&) [with T = long int]’:
../../cmake/external/onnx/onnx/proto_utils.h:40:11: error: invalid use of incomplete type ‘const class ONNX_NAMESPACE::AttributeProto’
   return {attr.ints().begin(), attr.ints().end()};
           ^~~~
In file included from ../../include/onnxruntime/core/framework/fence.h:7:0,
                 from ../../include/onnxruntime/core/framework/allocator.h:15,
                 from ../../include/onnxruntime/core/framework/tensor.h:13,
                 from ../../include/onnxruntime/core/framework/execution_provider.h:11,
                 from ../../onnxruntime/core/framework/execution_providers.h:12,
                 from ../../onnxruntime/core/session/inference_session.h:13,
                 from model-explorer.cpp:38:
../../include/onnxruntime/core/graph/basic_types.h:14:7: note: forward declaration of ‘class ONNX_NAMESPACE::AttributeProto’
 class AttributeProto;`

**Comment by pranavsharma** [comment]
You shouldn't be including "inference_session.h" at all. model-explorer.cpp has no mention of inference_session.h.

**Comment by kuroro20** [comment]
Yes of course, i havn't been clear, 
I told about the model-explorer, to show that eveything runs right, with the basic backend.

I'm now trying to use the ACL, and in the link above it is said that i need to instanciate the class InferenceSession. 
Then i supposed that i should include "inference_session.h" in a new project, but even with a minimalist main (only a return ),
The error occurs.

**Comment by skottmckay** [comment]
The ACL example code would require you to have all the internal libraries and include paths to build. If you're just linking against the onnxruntime library you should use the C or C++ API. When going by those API's the equivalent of the internal InferenceSession class is the Session class (as you likely would have seen in the model-explorer.cpp code).

In order to register a custom execution provider you'll currently need to use the C API and add the execution provider to the session options before constructing the session. Example code that adds the ACL execution provider to the session options: https://github.com/microsoft/onnxruntime/blob/222fd08f20765103e3bfbaf5de07b7f25373d516/onnxruntime/test/onnx/main.cc#L366

**Comment by kuroro20** [comment]
Thx for the answer, i think i have all the libraries compiled and linked, i should be able to use ACL,
I'll try the code you link asap (I've switched to an other project atm )
