### ISSUE TITLE
Unable to build Onnxruntime 1.4.0 with OpenVINO 2020.3 on Windows 10

### ISSUE THREAD

**Issue by danielecazzari** [microsoft/onnxruntime#4554]
**Describe the bug**
I'm trying to build  latest release of Onnxruntime 1.4.0 with OpenVINO EP (2020.3) with the following parameters:
--config Release --build_shared_lib --parallel --cmake_generator "Visual Studio 16 2019" --enable_pybind --build_wheel --use_openvino CPU_FP32 --skip_submodule_sync --skip_tests

During compilation I receive this warning treated as error and compilation end:
```
D:\onnx\onnxruntime-1.4.0\onnxruntime\core\providers\openvino\backends\vadm_backend.cc(67,25): error C2220: the followi
ng warning is treated as an error [D:\onnx\onnxruntime-1.4.0\build\Windows\Release\onnxruntime_providers_openvino.vcxpr
oj]
D:\onnx\onnxruntime-1.4.0\onnxruntime\core\providers\openvino\backends\vadm_backend.cc(67,25): warning C4456: declarati
on of 'i' hides previous local declaration [D:\onnx\onnxruntime-1.4.0\build\Windows\Release\onnxruntime_providers_openv
ino.vcxproj]
```

Could you help me understand what I'm doing wrong?

Regards,

Daniele

**Comment by hariharans29** [comment]
CC: @jywu-msft

**Comment by jywu-msft** [comment]
looks like a build warning on Windows which causes error. 
glancing at the code, I think starting line 67, you can replace
```
    for(size_t i = 0; i < num_inf_reqs_; i++) {
      InferenceEngine::InferRequest::Ptr infRequest;
      try {
        infRequest = exe_networks[i].CreateInferRequestPtr();
```
with
```
    for(size_t k = 0; k < num_inf_reqs_; k++) {
      InferenceEngine::InferRequest::Ptr infRequest;
      try {
        infRequest = exe_networks[k].CreateInferRequestPtr();
```
+@suryasidd , FYI, can you please confirm? 
actually, i wonder if it's possible to restructure the build to not build the VADMBackend unless
we're buildling with VAD-M support. here the OP is encountering this when building CPU_FP32 backend.

**Comment by suryasidd** [comment]
Hey @George, yep that's the error here. We wanted to push a fix for this along with 2020.4 release. About building VAD-M selectively, even though it might not be set at build time, we provide an option to override the device using a parameter so that we can run it for other backends. So this change might affect that and we won't be able to do that.

**Comment by george** [comment]
@jywu-msft ^

**Comment by danielecazzari** [comment]
Thanks a lot, with the above fix I was able to build on Windows. Unfortunately I won't be able to test on VAD-M due to missing hardware.

**Comment by jywu-msft** [comment]
issue was addressed by https://github.com/microsoft/onnxruntime/pull/4587
