### ISSUE TITLE
Unable to Get the StartTime in the Profiler

### ISSUE THREAD

**Issue by yhchang3** [microsoft/onnxruntime#4555]
**Problem**
Hello.
We're using Onnxruntime C++ API in v1.3.1 with profiling enabled. Everything in the saved file looks good after calling `EndProfiling()`. Right now we want to merge this profile into other profiling tools in different levels and put them into a timeline. The problem is that since the timestamps returned from the onnxruntime profiler are referenced from a private member `profiling_start_time_` in [profiler.h](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/common/profiler.h#L120), we can't find an absolute position to insert the profile into our timeline, since this info is not included in the saved file. Is there anyway that we can get `profiling_start_time_` or using a [custom logger](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/common/profiler.cc#L72) so that we have a way to compare the timestamps between onnxruntime profiler and other tools? Thanks.

**Urgency**
None

**System information**
- ONNX Runtime version: v1.3.1

Thanks,
Yen-Hsiang

**Comment by jcwchen** [comment]
Hi @yhchang3,
Will this PR https://github.com/microsoft/onnxruntime/pull/4994 meet your requirement?

**Comment by yhchang3** [comment]
Hi @jcwchen , 
     Thanks for your reply. I don't think we have direct access to the profiler in the inference session. Therefore, in addition to PR #4994 , we also need to add some methods in C/C++ API ( [onnxruntime_cxx_api.h](https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L266) ) that can access the residing profiler from the session and call the function you just added.

**Comment by jcwchen** [comment]
Thank you for clarification. I just added a new function under onnxruntime_cxx_api.h in the same PR. Does the function meet your need?

**Comment by yhchang3** [comment]
@jcwchen Yes these functions indeed meet my need. Thanks a lot for your help, I greatly appreciate it.

**Comment by jcwchen** [comment]
This has been resolved by https://github.com/microsoft/onnxruntime/pull/4994. I will also add Python/C# API for it in another PR. Thanks.
