### ISSUE TITLE
Unknown model file format version with example dataset in Python

### ISSUE THREAD

**Issue by ankane** [microsoft/onnxruntime#4563]
**Describe the bug**

Hi, this is a small one, but the `mul_1.onnx` example dataset in Python looks be broken or outdated. It fails to load with:

```txt
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: Unknown model file format version.
```

**Urgency**

None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac 10.15
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.4.0
- Python version: 3.8.4
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**

```python
import onnxruntime as rt
from onnxruntime import datasets

path = datasets.get_example('mul_1.onnx')
print(path)

sess = rt.InferenceSession(path)
print(sess.get_inputs()[0].name)
```

**Expected behavior**

Model loads

**Comment by jywu-msft** [comment]
Thanks for reporting. yes, it looks like that file is outdated and missing the IR version which triggers the error you observed.
We will fix it.

**Comment by ankane** [comment]
Thanks @jywu-msft!
