### ISSUE TITLE
Access to custom metadata of an .onnx model when creating an InferenceSession in a C# WPF application.

### ISSUE THREAD

**Issue by DanielMemmel** [microsoft/onnxruntime#4568]
**Is your feature request related to a problem? Please describe.**
No.

**System information**
- ONNX Runtime version (you are using): Microsoft.ML.OnnxRuntime Nuget Package v1.4.0
- .Net Framework 4.7.2

**Describe the solution you'd like**
I want to access the custom metadata of my .onnx file in the C# application. It is important for my application to know the model type, which version, numerical range of the input data, etc.

**Describe alternatives you've considered**
If the custom metadata is not accessible from the model file I will be forced to create a separate file that contains the needed information. This would be very annoying to always load two files and harder to keep track of.

**Additional context**
I am working with image segmentation and the user will be able to choose with model to use for his problem. So I need to provide additional info about the different models. 
From the `InputMetadata` of the `InferenceSession` I can get the image size and dtype that is needed but the `ModelMetadata `property is always empty. 

I populate the .onnx model with custom metadata in python with the onnxmltools (version 1.6.1) library:

```
import onnxmltools

model = onnxmltools.load_model("../model.onnx")
meta = model.metadata_props.add()
meta.key = "version"
meta.value = "0.0.1"
onnxmltools.utils.save_model(model, "../model_1.onnx")

```
After saving the model again I can see the custom properties e.g. in [Netron](https://lutzroeder.github.io/netron/) but the C# api does not show them to me. 
Is there a way to have the custom data I put into the .onnx model read when creating an InferenceSession?

Thanks in advance!

Daniel

**Comment by DanielMemmel** [comment]
I found the empty `ModelMetadata` class with a TODO in the InferenceSession.cs:

 ```
   internal class ModelMetadata
    {
        //TODO: placeholder for Model metadata. Currently C-API does not expose this.
    }
```

Is there currently someone working on this?

**Comment by hariharans29** [comment]
You’re welcome to contribute. The C API (now) exposes methods to fetch metadata associated with a model.

**Comment by DanielMemmel** [comment]
> The C API (now) exposes methods to fetch metadata associated with a model.

So the TODO is outdated and it would be possible wrap the C methods in C#?

Digging into the `NativeMethods.cs` class I found that the C# api is using the `OrtApi` version 1.

[NativeMethods.cs](https://github.com/microsoft/onnxruntime/blob/master/csharp/src/Microsoft.ML.OnnxRuntime/NativeMethods.cs#L157)

<img width="745" alt="NativeMethods" src="https://user-images.githubusercontent.com/68106736/88262453-8380c000-ccc8-11ea-8535-631c0ee54d2b.png">

In the C api there are plenty of methods regarding Metadata. But they all have this `ORT_API2_STATUS`:

<img width="698" alt="C_api" src="https://user-images.githubusercontent.com/68106736/88262690-f4c07300-ccc8-11ea-8c1d-16bd54ab98c0.png">

[C api](https://github.com/microsoft/onnxruntime/blob/v1.4.0/include/onnxruntime/core/session/onnxruntime_c_api.h#L766)

Do I need to update the whole C# api to work with this version 2? 
What would happen if I replace this 1 with a 2 in the OrtGetApi call? 
What if I want to import just these few methods, is version 1 and compatible in this regard?
How does the import work? (I am not really good at C...)

Tanks for your help!

**Comment by hariharans29** [comment]
`Digging into the NativeMethods.cs class I found that the C# api is using the OrtApi version 1`:

We have some work to do wrt to C# API versioning, but the good news is we get access to the same Api struct whatever version we request (for now) and so no change required- 

https://github.com/microsoft/onnxruntime/blob/ace41b80647a627805c766ef6b05e78a1e5cd206/onnxruntime/core/session/onnxruntime_c_api.cc#L1625

`Do I need to update the whole C# api to work with this version 2?`

You need to bring in methods (but they don't need delegates) until the metadata methods in the Api struct. You can use this PR for reference - https://github.com/microsoft/onnxruntime/pull/3934

If you are still having issues, I can get to this sometime next week.

**Comment by DanielMemmel** [comment]
Hi! 
I now forked the repository and created a branch regarding this feature.
I was able to write the wrapping functions for C methods. I can get most of the information of the model while debugging one of the unittest. 
[First commit with metadata methods](https://github.com/DanielMemmel/onnxruntime/commit/e521d8f185915447b86cab4f4922309b87406876)

I encountered several problems:
1. The custom key-value pairs are not there or maybe the C methods do not return the right things. More likely is that I am using them wrong.
2. The unittests which tests inference of the squeezenet.onnx fails: The output of the network are all zero.

I also need help with the ModelMetadata class. I want to treat it the same as NodeMetadata but I am not sure if that is the right thing.

**Comment by DanielMemmel** [comment]
I just wanted to check if you had time to look into this problem. I was not able to get any further. 

Thanks for your efforts!

**Comment by hariharans29** [comment]
Hi @DanielMemmel,

Thanks for checking in. Sorry I missed your earlier message. 

I will definitely have this in the next release. Hopefully sooner. 

So just to confirm - you only want what is available via the C API right ?

**Comment by DanielMemmel** [comment]
Hi @hariharans29,

That are some good news! 

Yes. Mainly the access to the `ModelMetadataLookupCustomMetadataMap `and `ModelMetadataGetCustomMetadataMapKeys`. Those I need to provide custom information to the user. 

The rest like `ModelMetadataGetProducerName`, `ModelMetadataGetGraphName`, etc. worked when I was trying this myself.

**Comment by hariharans29** [comment]
ok- I am unable to provide a timeline right now - but I ll make sure it goes into the next release (hopefully will be in master much earlier than that)

**Comment by hariharans29** [comment]
Hi @DanielMemmel  - I have a PR for this now

**Comment by DanielMemmel** [comment]
Great! Thanks a lot man I appreciate the work 👍 

If I want to use this before the next release I have to build it from the master after the PR gets accepted right?
