### ISSUE TITLE
 there is always a "import error" in a new win7 system: "ImportError: cannot import name 'get_all_providers'"

### ISSUE THREAD

**Issue by lightfate** [microsoft/onnxruntime#4570]
webwxgetmsgimg
Describe the bug
when I install onnxruntime in a new  windows 7 sp1 system, there is always a "import error" . I have already installed “vs 2019 runtime” （VC_redist.x64.exe）

Package           Version
----------------- -------
numpy             1.19.0
onnx              1.7.0
onnxruntime       1.4.0
pip               20.1.1
protobuf          3.12.2
setuptools        39.0.1
six               1.15.0
typing-extensions 3.7.4.2
wheel             0.34.2

C:\Users\zhjs>python
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD6
4)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime
C:\Users\zhjs\AppData\Local\Programs\Python\Python36\lib\site-packages\onnxrunti
me\capi\_pybind_state.py:14: UserWarning: Cannot load onnxruntime.capi. Error: '
DLL load failed: 找不到指定的程序。'.
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'.".format(str(e)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\zhjs\AppData\Local\Programs\Python\Python36\lib\site-packages\o
nnxruntime\__init__.py", line 13, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_
providers, get_device, set_seed, \
ImportError: cannot import name 'get_all_providers'
>>>

Urgency
High, our project is based on onnxruntime, and now it cannot run in a new win7 system，and we already installed “VC_redist.x64.exe”，we don‘t know what's missing？

System information

Win7:
pip insatll onnxruntime:
onnxruntime 1.4.0/1.3.0:
python 3.6.6
use cpu:
To Reproduce
 it cannot run in a new win7 system，and we already installed “VC_redist.x64.exe”，we don‘t know what's missing？

Expected behavior
no import error

Screenshots

![error](https://user-images.githubusercontent.com/41222646/88074312-d1eb6d00-cba9-11ea-9d8b-c2d1b935e69b.JPG)

**Comment by snnn** [comment]
To identify the problem:
1. Install [windbg](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools)
2.  Find the gflags.exe in the windbg install folder and start it, 

3. Select the image file tab
![image](https://user-images.githubusercontent.com/856316/74082914-91d96900-4a13-11ea-95eb-d73db8a5cf13.png)

4. Type python.exe then press the "tab" key, check "Show loader snaps" box

![image](https://user-images.githubusercontent.com/856316/74082958-b7667280-4a13-11ea-9eaf-6752695b4904.png)

5.  Put your python commands into a script file, named "test.py"
```
import torch
import onnxruntime
```

6.  Start windbg, run python.exe with arguments of "test.py"
![image](https://user-images.githubusercontent.com/856316/74083043-7d49a080-4a14-11ea-90fa-2960544a3dce.png)

7. in the command windows, type "g", then press the enter key
![image](https://user-images.githubusercontent.com/856316/74083078-d285b200-4a14-11ea-9df4-e86c421c5617.png)

7. You'll see a lot of outputs in the debugging windows.  Please search the lines that have "LdrpProcessWork - ERROR: Unable to load DLL", and put the result here.
e.g.
 "cublas64_100.dll", Parent Module: "C:\intelpython3\lib\site-packages\onnxruntime\capi\onnxruntime_pybind11_state.pyd", Status: 0xc0000135

**Comment by lightfate** [comment]
[windbg_output.txt](https://github.com/microsoft/onnxruntime/files/4958162/windbg_output.txt)




> To identify the problem:
> 
> 1. Install [windbg](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools)
> 2. Find the gflags.exe in the windbg install folder and start it,
> 3. Select the image file tab
>    ![image](https://user-images.githubusercontent.com/856316/74082914-91d96900-4a13-11ea-95eb-d73db8a5cf13.png)
> 4. Type python.exe then press the "tab" key, check "Show loader snaps" box
> 
> ![image](https://user-images.githubusercontent.com/856316/74082958-b7667280-4a13-11ea-9eaf-6752695b4904.png)
> 
> 1. Put your python commands into a script file, named "test.py"
> 
> ```
> import torch
> import onnxruntime
> ```
> 
> 1. Start windbg, run python.exe with arguments of "test.py"
>    ![image](https://user-images.githubusercontent.com/856316/74083043-7d49a080-4a14-11ea-90fa-2960544a3dce.png)
> 2. in the command windows, type "g", then press the enter key
>    ![image](https://user-images.githubusercontent.com/856316/74083078-d285b200-4a14-11ea-9df4-e86c421c5617.png)
> 3. You'll see a lot of outputs in the debugging windows.  Please search the lines that have "LdrpProcessWork - ERROR: Unable to load DLL", and put the result here.
>    e.g.
>    "cublas64_100.dll", Parent Module: "C:\intelpython3\lib\site-packages\onnxruntime\capi\onnxruntime_pybind11_state.pyd", Status: 0xc0000135



> To identify the problem:
> 
> 1. Install [windbg](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools)
> 2. Find the gflags.exe in the windbg install folder and start it,
> 3. Select the image file tab
>    ![image](https://user-images.githubusercontent.com/856316/74082914-91d96900-4a13-11ea-95eb-d73db8a5cf13.png)
> 4. Type python.exe then press the "tab" key, check "Show loader snaps" box
> 
> ![image](https://user-images.githubusercontent.com/856316/74082958-b7667280-4a13-11ea-9eaf-6752695b4904.png)
> 
> 1. Put your python commands into a script file, named "test.py"
> 
> ```
> import torch
> import onnxruntime
> ```
> 
> 1. Start windbg, run python.exe with arguments of "test.py"
>    ![image](https://user-images.githubusercontent.com/856316/74083043-7d49a080-4a14-11ea-90fa-2960544a3dce.png)
> 2. in the command windows, type "g", then press the enter key
>    ![image](https://user-images.githubusercontent.com/856316/74083078-d285b200-4a14-11ea-9df4-e86c421c5617.png)
> 3. You'll see a lot of outputs in the debugging windows.  Please search the lines that have "LdrpProcessWork - ERROR: Unable to load DLL", and put the result here.
>    e.g.
>    "cublas64_100.dll", Parent Module: "C:\intelpython3\lib\site-packages\onnxruntime\capi\onnxruntime_pybind11_state.pyd", Status: 0xc0000135

I can't find any error message like "Unable to load DLL" (the whole output is as follows)

[windbg_output.txt](https://github.com/microsoft/onnxruntime/files/4958182/windbg_output.txt)

**Comment by snnn** [comment]
How about onnxruntime 1.3.1? Is that version ok?

**Comment by snnn** [comment]
Hi @lightfate , I guess it was due to your system missed some important Windows updates. 
Please install the following two and try it again:
  [Update KB3068708](https://support.microsoft.com/en-us/help/3068708/update-for-customer-experience-and-diagnostic-telemetry)      [Update KB3080149](https://support.microsoft.com/en-us/help/3080149/update-for-customer-experience-and-diagnostic-telemetry)

**Comment by lightfate** [comment]
> How about onnxruntime 1.3.1? Does that version work?

I can't find onnxruntime 1.3.1。but I have tried onnxruntime 1.3.0，  the same error occurred 。

Collecting onnxruntime==1.3.1
  Could not find a version that satisfies the requirement onnxruntime==1.3.1 (fr
om versions: 0.1.4, 0.2.1, 0.3.0, 0.4.0, 0.5.0, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.2.
0, 1.3.0, 1.4.0)
No matching distribution found for onnxruntime==1.3.1

**Comment by snnn** [comment]
Do the two Windows updates help?

**Comment by lightfate** [comment]
> Do the two Windows updates help?

Yes, it works! Thank you so much.
Bug there is still a user warning as bellow, I am not sure whether this will affect normal use. 

>>> import onnxruntime
C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnxrun
time\capi\onnxruntime_validation.py:27: UserWarning: Unsupported Windows version
 (7). ONNX Runtime supports Windows 10 and above, only.
  __my_distro_ver__)

**Comment by snnn** [comment]
It's a false alarm. Please ignore it.
