### ISSUE TITLE
Missing opset in the model

### ISSUE THREAD

**Issue by MitchVonk** [Microsoft/onnxruntime#458]
**Describe the bug**
I'm trying to run:
https://github.com/Microsoft/onnxruntime/blob/master/csharp/sample/Microsoft.ML.OnnxRuntime.InferenceSample/Program.cs

but the following error occurs if the InferenceSession classes is created:

Microsoft.ML.OnnxRuntime.OnnxRuntimeException: '[ErrorCode:InvalidProtobuf] Protobuf parsing failed.'

Anyway how I can set the version for the ModelProtos?=

**Comment by dashesy** [comment]
@MitchVonk what was the issue you had here?

**Comment by niuzheng168** [comment]
@MitchVonk did you solve the issue? I hit same exception today

**Comment by georgeblah** [comment]
@MitchVonk @dashesy @niuzheng168  Have you guys had the same issue or found a solution to this yet? I seem to be dealing with the same problem when trying to load a keras model with a custom layer.
