### ISSUE TITLE
Export data preprocessing logic built upon featurizers_ops and PyTorch model into one ONNX file for model serving.

### ISSUE THREAD

**Issue by brightcoder01** [microsoft/onnxruntime#4594]
Feature engineering is important in the end-to-end machine learning pipeline. Keep consistency between training and online inference is very important for model deployment.
There are many useful feature engineering operators in the folder [`featurizers_ops`](https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/featurizers_ops/cpu). **We want to export the data preprocessing logic built upon featurizers_ops and PyTorch model together into an ONNX file for model serving.**

- Can we pip install a python package and use these featurizers_ops in our Python program? 
   We can write python program with this package to preprocessing the data, and then we can execute the model training using the preprocessed data. 
   Or even more, can we write the model definition with this preprocess package and PyTorch. In this way, the data preprocessing is executed in the training loop.

- Can we export the python program built upon featurize_ops into an ONNX file format, just like exporting a TensorFlow Keras Model to the SavedModel format. And then we can export the data preprocessing logic and PyTorch model together into one ONNX file for online inference.

**Comment by workingloong** [comment]
Can you give some examples of `featurizers_ops`? How do we use feature engineering operators in Pytorch and TensorFlow models?

**Comment by pranavsharma** [comment]
Feel free to build the featurizers from the source using '--use_featurizers' flag. We don't publish featurizers pkgs.
