### ISSUE TITLE
Incompatibility Openvino-vadm Model  Error

### ISSUE THREAD

**Issue by Ken-LiuL** [microsoft/onnxruntime#4598]
**Describe the bug**
When I use Openvino-vadm  version onnxruntime to create inference session, there are errors thrown, though the model could run perfectly in standard onnxruntime environment
**Urgency**
None

**System information**
- Ubuntu
- ONNX Runtime installed from (source or binary): mcr.microsoft.com/azureml/onnxruntime:latest-openvino-vadm

**To Reproduce**
- Describe steps/code to reproduce the behavior.
Just use onnxruntime.InferenceSession with onnxruntime.capi._pybind_state.set_openvino_device("VAD-M_FP16")
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

[model.onnx.zip](https://github.com/microsoft/onnxruntime/files/4965380/model.onnx.zip)

**Expected behavior**
I would expect a success instantiation of the inference session.

**Screenshots**
![image](https://user-images.githubusercontent.com/7971987/88278099-6eca1980-cd14-11ea-8c8f-86ef9383799e.png)
![image](https://user-images.githubusercontent.com/7971987/88278140-7c7f9f00-cd14-11ea-971e-7eb13d7ab6a6.png)

**Comment by skottmckay** [comment]
@suryasidd or @smkarlap any idea what could cause this?

**Comment by suryasidd** [comment]
Please follow step 4, Additional configuration step for VAD-M from the build instructions https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#prerequisites-3.

We need to set 8 devices to the by-pass scheduler.

**Comment by Ken-LiuL** [comment]
thanks, it works
