### ISSUE TITLE
Inference on GPU is not deterministic

### ISSUE THREAD

**Issue by erikbrntsn** [microsoft/onnxruntime#4611]
**Describe the bug**
In C#:
Two instances of the same model running on the GPU does not produce the same result.
The results are numerically identical when using the CPU however.

**Urgency**
Some urgency.
We would like to use ORT to run some ML components in a large computer vision application. Non-determinism makes our development more difficult and therefore ORT less appealing.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Build 18362
- ONNX Runtime installed from (source or binary): NuGet
- ONNX Runtime version: Microsoft.ML.OnnxRuntime.Gpu 1.3, Microsoft.ML.OnnxRuntime.Managed 1.3
- Python version: 3.7.3
- Visual Studio version (if applicable): VS2019 Version 16.4.5
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: GeForce 2080 Ti - driver 441.22

**To Reproduce**
A small model that reproduces the problem can be created using the following code:
```
import torch
from torch import nn


class Model(nn.Module):

    def __init__(self):
        super(Model, self).__init__()
        c = 10
        self.relu = torch.nn.ReLU(inplace=True)
        self.conv1 = torch.nn.Conv2d(1, c, kernel_size=3, stride=1, padding=1)
        self.conv2 = torch.nn.Conv2d(c, 1, kernel_size=3, stride=1, padding=1)
        self.batchNorm = torch.nn.BatchNorm2d(c)

    def forward(self, data):
        return self.conv2(self.batchNorm(self.relu(self.conv1(data))))


if __name__ == "__main__":
    import sys

    if len(sys.argv) != 2:
        print("Usage: <path/to/output>")
        exit()

    model = Model()
    model_input = torch.zeros([1, 1, 123, 234])
    input_names = ["input"]

    with open(sys.argv[1], "wb") as fh:
        torch.onnx.export(model,
                          model_input,
                          fh,
                          opset_version=11,
                          do_constant_folding=True,
                          input_names=input_names,
                          output_names=["output"],
                          dynamic_axes={name: {2: "rows", 3: "cols"} for name in input_names})
```
To reproduce the non-deterministic behavior run the following in C# (eg. in a unit test)
```
var modelPath = @"path\to\model";
var options = SessionOptions.MakeSessionOptionWithCudaProvider();
using (var model1 = new InferenceSession(modelPath, options))
using (var model2 = new InferenceSession(modelPath, options))
{
    int rowsIn = 123;
    int colsIn = 234;
    int nChannelsIn = 1;
    var dims = new[] { 1, nChannelsIn, rowsIn, colsIn };
    var rnd = new Random();
    var data = new float[nChannelsIn * colsIn * rowsIn];
    for (int i = 0; i < data.Length; i++)
        data[i] = (float) (rnd.NextDouble() - 0.5);
    var input = new DenseTensor<float>(data, dims);

    var inputORT = new List<NamedOnnxValue> { NamedOnnxValue.CreateFromTensor(model1.InputMetadata.Keys.First(), input) };
    var output1 = model1.Run(inputORT).First().AsTensor<float>();
    var output2 = model2.Run(inputORT).First().AsTensor<float>();

    int rowsOut = 123;
    int colsOut = 234;
    int nChannelsOut = 1;
    for (int c = 0; c < nChannelsOut; c++)
    for (int row = 0; row < rowsOut; row++)
    for (int col = 0; col < colsOut; col++)
        Assert.AreEqual(output1[0, c, row, col], output2[0, c, row, col]);
}
```

**Expected behavior**
The outputs of the two models are identical

**Additional context**
As mentioned, two models created on the CPU produce identical results.
Passing the same input twice to the same model also produces identical results.
Note that you might have to run the test code a few times to reproduce the problem. For me the two results are different roughly every second time I run it.

**Comment by snnn** [comment]
It's a known issue. However, even on CPU we don't expect it can produce identical result. Maybe CUDA/CUDNN can do better but I'm sorry we can't promise it.

**Comment by dguest** [comment]
@erikbrntsn, I'm curious how you worked around this in your application. We're facing similar issues with a network of similar complexity. Were you able to establish some bounds for the lack of reproducability? We're considering truncating the  mantissa in the outputs, but of course this won't really eliminate the problem (just make it less likely).

**Comment by yaohualibin** [comment]
Would you please try to limit the cudnn_conv_algo_search by
    providers = [('CUDAExecutionProvider', {
        'device_id': 0,
        'cudnn_conv_algo_search': 'DEFAULT',
    })]

**Comment by jcdatin** [comment]
on my faster-rcnnn network inference , I fixed my non determinism by replacing GraphOptimizationLevel::ORT_ENABLE_ALL with GraphOptimizationLevel::ORT_DISABLE_ALL (variability was very small though with GraphOptimizationLevel::ORT_ENABLE_ALL : 10e-7 for confidence score and 10-e4 for box coordinates. Got a inference exeution time regression of <5%

I used TRT EP (8.6) with ORT 1.17.1+ : with all nodes on TRT (in particular DNS nodes)

**Comment by jcdatin** [comment]
setDeterministicCompute(true) did nothing
