### ISSUE TITLE
Input and output tensors data info

### ISSUE THREAD

**Issue by TratsiakY** [microsoft/onnxruntime#4620]
Hello to everybody. I've done the C++ class to predicting with my onnx model. My model has two outputs: they are int(0 or 1, label) and map(output with probability). The first output(label) read without any problems. How could I get the data from the second layer (probability, map form)? (The layer with probabilities is described as a map<int, float> in Netron).
I build the output tensor as follows:

> auto output_tensor = ses.Run(RunOptions{ nullptr }, parameters.InputLayerName.data(), input_tensor.data(), parameters.Ninp, parameters.OututLayerName.data(), parameters.NumOfOutputs);

where parameters is the structure with data about model from onnx file. output_tensor is a vector<Value>, where the first element is an int value (label) and the second is a map. 
The model is in [this message](https://github.com/microsoft/onnxruntime/issues/4528#issuecomment-661736788)  

Yet one question. What do mean the int values from the session.GetOutputTypeInfo(layer).GetONNXType()? I mean the link between values and types. In source code is mentioned only
"Return OnnxType from OrtTypeInfo"
Is it true, that 1 only used for sequences and 2  for maps only? Or I misunderstood?

**Comment by skottmckay** [comment]
Not sure if you're specifying all the output names correctly. It may be easier to try the new experimental Run method where you provide those as a vector of strings.

https://github.com/microsoft/onnxruntime/blob/222fd08f20765103e3bfbaf5de07b7f25373d516/include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h#L31-L34

For the second output it's actually a sequence (i.e. vector) of map instances. As such I'd expect GetONNXType to return ONNX_TYPE_SEQUENCE. I don't think there are any operators that return an output of just a map. CastMap and DictVectorizer take a map as input though.

![image](https://user-images.githubusercontent.com/979079/88516007-f3c47400-d02f-11ea-96f6-792a9baf8fb7.png)

The vector returned by Run will be one value per requested output. The first output value (output_label) will be a tensor containing more or more int values (based on the model looks like only one int). The second output value, assuming you provide the output name correctly, will be a sequence containing one or more map<int64, float32> instances. The size of this sequence will match the number of entries in the output_label tensor.

**Comment by TratsiakY** [comment]
@skottmckay the second output is a Value, not a map. GetONNXType() for second layer returns 2.
cout << typeid(output_tensor[1]).name() << endl; returns struct Ort::Value.
I am in a misunderstanding how to extract the output values from the second output.

**Comment by skottmckay** [comment]
Ort::Value is the generic type that wraps the different possibilities (Tensor, Sequence, Map)
If GetONNXType returns 2 that equates to ONNX_TYPE_SEQUENCE, which would match the expected type of `sequence<map<int64,float32>>`.

Usage is sadly a bit obtuse currently. Example code here:
https://github.com/microsoft/onnxruntime/blob/d8f3e46d458397b3fb335477d3efc91e22e160d8/onnxruntime/test/shared_lib/test_nontensor_types.cc#L67-L86

There are a few layers of Ort::Value. 
First is for the sequence. Use Ort::Value::GetCount() to find the number of elements. Call GetValue to extract each entry, which will return another Ort::Value for the map in that slot. 
The map itself has 2 Ort::Value instances - one for the keys, one for the values. You can call GetTensorMutableData to access the data here.

**Comment by TratsiakY** [comment]
@skottmckay, Thanks for reply. The situation becomes clear.
In my case the internal tensor structure was a bit more complex.
The output tensor was:
[ [Value for output layer 1], [ Value [ Value[Value{keys}, Value{data}]]]]
