### ISSUE TITLE
Does onnxruntime use data parallelism or model parallelism?

### ISSUE THREAD

**Issue by Peppa-cs** [microsoft/onnxruntime#4622]
Hi,
I build onnxruntime with ‘openmp’ on Nvidia AGX Xaiver. When i run onnx model (resnet) on cpu with onnxruntime, multiple threads are created to perform code. If I set four cpu cores, four threads will be created. The follow pictures are the result of running ‘pythoncifar10.py’. So I have two questions: 1. Is the num of threads producing by ‘openmp’ equal to cpu cores? 2. When onnxruntime produces multiple threads, whether it uses data parallelism or model parallelism?

Thanks!

 ONNX Runtime version :

  onnxruntime 1.3.0
  onnx 1.7.0

![image](https://user-images.githubusercontent.com/60772185/88475619-4b95a900-cf64-11ea-8837-10be6cfb4063.png)

![image](https://user-images.githubusercontent.com/60772185/88475622-4e909980-cf64-11ea-922f-473a8dfb90d1.png)

**Comment by skottmckay** [comment]
Not sure what you mean by 'set four cpu cores'. Are those equivalent to physical cores? If there are 4 physical cores and no hyperthreading I believe OpenMP would use 4 threads by default. Also configurable via the OMP_NUM_THREADS environment variable.

ORT doesn't break the input data into multiple batches based on the number of threads and run the model concurrently with those batches (assuming that's what you mean by 'model parallelism'). Instead some operators may utilize multiple threads (intra-op threads) to perform work. For example MatMul or GEMM can be split across multiple threads if there's enough work to do, and if OpenMP is enabled that most likely is done via `#pragma omp paralle for`

**Comment by Peppa-cs** [comment]
> Not sure what you mean by 'set four cpu cores'. Are those equivalent to physical cores? If there are 4 physical cores and no hyperthreading I believe OpenMP would use 4 threads by default. Also configurable via the OMP_NUM_THREADS environment variable.
> 
> ORT doesn't break the input data into multiple batches based on the number of threads and run the model concurrently with those batches (assuming that's what you mean by 'model parallelism'). Instead some operators may utilize multiple threads (intra-op threads) to perform work. For example MatMul or GEMM can be split across multiple threads if there's enough work to do, and if OpenMP is enabled that most likely is done via `#pragma omp paralle for`

Thanks for fast reply!  Get it!

**Comment by snnn** [comment]
ORT supports both of them.

**Comment by Peppa-cs** [comment]
> ORT supports both of them.

Thanks for your reply! Can you explain it in more detail? Did 'them' mean data parallelism or model parallelism?

**Comment by snnn** [comment]
Right. 

Data parallelism means onnxruntime can run multiple inference on the same session(model) in parallel. 
model parallelism onnxruntime can run multiple parts of the model in parallel by using the parallel executor, which is not enabled by default. Please reference onnxruntime's document for how to enable it. 

However, these things only applies to the default CPU provider and CUDA provider. Even the CUDA provider supports model parallelism, but it doesn't support multiple GPU card yet, so probably it's not what you want.
