### ISSUE TITLE
Error using output of one model as input for another C#

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#4624]
**Describe the bug**
I would like to use the output of one model as input to another, and avoid data marshaling/copy of large tensors.
Similar to issue #2983, and I get exception

> Exception thrown: 'System.OverflowException' in System.Private.CoreLib.dll

The difference is that I re-create the NamedOnnxValue because I want to give it a different name.

**Urgency**
I am now going to export with a different name and try passing the output as-is without change, hopefully it works otherwise I will update the issue.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- ONNX Runtime installed from (source or binary): nuget
- ONNX Runtime version: 1.4.0

**To Reproduce**
- Describe steps/code to reproduce the behavior.

```C#
NamedOnnxValue inputIds = NamedOnnxValue.CreateFromTensor("input", val.AsTensor<long>());
```

Where `val` is `DisposableNamedOnnxValue` with name "output". I want to change that to "input".

**Expected behavior**
Easy way to work with intermediate tensors. It is also hard to unit test with "DisposableNamedOnnxValue" and I currently wrap everything.

**Comment by hariharans29** [comment]
There is an interface to update the name of the DisposableNamedOnnxValue and you should be able to re-use that directly. Is that what you are looking for ?

**Comment by hariharans29** [comment]
https://github.com/microsoft/onnxruntime/blob/222fd08f20765103e3bfbaf5de07b7f25373d516/csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs#L997

**Comment by dashesy** [comment]
Yes. I already exported with the expected names but this should do too.
Another question: Is there anyway to moq `DisposableNamedOnnxValue`? I want to moq the result of `Run` and test the rest of the code which deals with tensor's `ReadOnlySpan.Buffer` for example.

**Comment by skottmckay** [comment]
Closing this. There's a separate issue with the question about mocking.
