### ISSUE TITLE
C API Error in model input dimensions with yolov4 model

### ISSUE THREAD

**Issue by AmirElAttar** [microsoft/onnxruntime#4635]
**Describe the bug**
using the code in sample: C_Api_Sample.cpp 
with the zoo model Yolov4: https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov4
first input dimension is reported as **(-1)** instead of **(1)** from function: **g_ort->GetDimensions**

**Urgency**
not blocking but good to resolve for my case I already know the model i/p o/p but may not be for others

**System information**
- Linux Ubuntu 16.04
- ONNX Runtime installed from (source ):
- ONNX Runtime version: git status: branch 530117c
- C API

- GCC/Compiler version (if compiling from source):
gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010

**To Reproduce**
-just run C_Api_Sample.cpp  with the listed model above

**Expected behavior**
Number of inputs = 1
Input 0 : name=input_1:0
Input 0 : type=1
Input 0 : num_dims=4
Input 0 : dim 0=**1**
Input 0 : dim 1=416
Input 0 : dim 2=416
Input 0 : dim 3=3

**Screenshots**
![image](https://user-images.githubusercontent.com/30228248/88600523-ba5f2900-d06e-11ea-9d18-25a1149f621c.png)

**Additional context**
none

**Comment by snnn** [comment]
That's expected. -1 means you can put any integer there.

**Comment by AmirElAttar** [comment]
> That's expected. -1 means you can put any integer there.

python version returns expected values (1 416 416 3) 
besides how come the dimension be a negative value?

**Comment by snnn** [comment]
See: https://github.com/onnx/onnx/blob/master/docs/IR.md#static-tensor-shapes

In the spec, A Dimension  object could either have a dim_value field, or a dim_param field, or none of them.  If dim_param  is set, because it is a string, we can't put a string in an integer array, we replace it as "-1".
