### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by cqray1990** [microsoft/onnxruntime#4643]
when i cmake the code as follows:
#include <experimental_onnxruntime_cxx_api.h>
#include <onnxruntime_c_api.h>
#include <opencv2/core/core.hpp>
#include <opencv2/opencv.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <vector>
#include <stdlib.h>
#include <iostream>

using namespace cv;
using namespace std;

std::string print_shape(const std::vector<int64_t>& v) {
  std::stringstream ss("");
  for (size_t i = 0; i < v.size() - 1; i++)
    ss << v[i] << "x";
  ss << v[v.size() - 1];
  return ss.str();
}

int calculate_product(const std::vector<int64_t>& v) {
  int total = 1;
  for (auto& i : v) total *= i;
  return total;
}

void resizeimg(cv::Mat org,cv::Mat dst)
{
    int h = org.rows;
    int w = org.cols;

    float scale;
    int crnn_h = 32;
    int crnn_w_target;
    int crnn_h_target;
    scale = crnn_h*1.0/h;
    crnn_w_target = int(w * scale);

    resize(org,dst,Size(crnn_w_target,crnn_h));
    
}

int main(int argc, const char** argv) 
{

//   if (argc != 2) {
//     cout << "Usage: ./onnx-api-example <onnx_model.onnx>" << endl;
//     return -1;
//   }
  char * modelpath= "/home/lgx/myprj/OCRdetectionreg/crnn_huocepiao/crnn_Rec_done_3_371686.onnx";
  const char * imgpath = "/home/lgx/myprj/OCRdetectionreg/crnn_huocepiao/1.jpg";
  
  cv::Mat img = cv::imread(imgpath);
  cv::Mat dst;
  resizeimg(img,dst);

  

  // onnxruntime setup
  Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "example-model-explorer");
  Ort::SessionOptions session_options;

  Ort::Experimental::Session session = Ort::Experimental::Session(env, modelpath, session_options); 
  std::vector<std::string> input_names = session.GetInputNames();
  std::vector<std::vector<int64_t> > input_shapes = session.GetInputShapes();
  cout << "Input Node Name/Shape (" << input_names.size() << "):" << endl;
  for (size_t i = 0; i < input_names.size(); i++) {
    cout << "\t" << input_names[i] << " : " << print_shape(input_shapes[i]) << endl;
  }

  std::vector<std::string> output_names = session.GetOutputNames();
  std::vector<std::vector<int64_t> > output_shapes = session.GetOutputShapes();
  cout << "Output Node Name/Shape (" << output_names.size() << "):" << endl;
  for (size_t i = 0; i < output_names.size(); i++) {
    cout << "\t" << output_names[i] << " : " << print_shape(output_shapes[i]) << endl;
  }

    assert(input_names.size() == 1 && output_names.size() == 1);
    auto input_shape = input_shapes[0];
    int total_number_elements = calculate_product(input_shape);

     std::vector<float> input_tensor_values(total_number_elements);
  std::generate(input_tensor_values.begin(), input_tensor_values.end(), [&] { return rand() % 255; });  // generate random numbers in the range [0, 255]
  auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
  std::vector<Ort::Value> input_tensors;
  input_tensors.push_back(Ort::Value::CreateTensor<float>(memory_info, input_tensor_values.data(), input_tensor_values.size(), input_shape.data(), input_shape.size()));

  // double-check the dimensions of the input tensor
  assert(input_tensors[0].IsTensor() &&
         input_tensors[0].GetTensorTypeAndShapeInfo().GetShape() == input_shape);
  cout << "\ninput_tensor shape: " << print_shape(input_tensors[0].GetTensorTypeAndShapeInfo().GetShape()) << endl;

  // pass data through model
  cout << "Running model...";
  try {
    auto output_tensors = session.Run(session.GetInputNames(), input_tensors, session.GetOutputNames());
    cout << "done" << endl;

    // double-check the dimensions of the output tensors
    // NOTE: the number of output tensors is equal to the number of output nodes specifed in the Run() call
    assert(output_tensors.size() == session.GetOutputNames().size() &&
           output_tensors[0].IsTensor());
    cout << "output_tensor_shape: " << print_shape(output_tensors[0].GetTensorTypeAndShapeInfo().GetShape()) << endl;

  } catch (const Ort::Exception& exception) {
    cout << "ERROR running model inference: " << exception.what() << endl;
    exit(-1);
  }

    return 0;
}

it got the errors:

/usr/include/c++/5/bits/stl_tree.h:731:7: error: ‘pair’ does not name a type
       pair<_Base_ptr, _Base_ptr>
       ^
/usr/include/c++/5/bits/stl_tree.h:735:7: error: ‘pair’ does not name a type
       pair<_Base_ptr, _Base_ptr>
       ^
/usr/include/c++/5/bits/stl_tree.h:854:32: error: ‘_Node_allocator’ has not been declared
       _Rb_tree(_Rb_tree&& __x, _Node_allocator&& __a);
                                ^
/usr/include/c++/5/bits/stl_tree.h:884:7: error: ‘reverse_iterator’ does not name a type
       reverse_iterator
       ^
/usr/include/c++/5/bits/stl_tree.h:888:7: error: ‘const_reverse_iterator’ does not name a type
       const_reverse_iterator
       ^
/usr/include/c++/5/bits/stl_tree.h:892:7: error: ‘reverse_iterator’ does not name a type
       reverse_iterator
       ^
/usr/include/c++/5/bits/stl_tree.h:896:7: error: ‘const_reverse_iterator’ does not name a type
       const_reverse_iterator
       ^
/usr/include/c++/5/bits/stl_tree.h:914:36: error: ‘_Alloc_traits’ has not been declared
       swap(_Rb_tree& __t) noexcept(_Alloc_traits::_S_nothrow_swap());
                                    ^
/usr/include/c++/5/bits/stl_tree.h:922:9: error: ‘pair’ does not name a type
         pair<iterator, bool>
         ^
/usr/include/c++/5/bits/stl_tree.h:954:2: error: ‘pair’ does not name a type
  pair<iterator, bool>
  ^
/usr/include/c++/5/bits/stl_tree.h:1105:7: error: ‘pair’ does not name a type
       pair<iterator, iterator>
       ^
/usr/include/c++/5/bits/stl_tree.h:1108:7: error: ‘pair’ does not name a type
       pair<const_iterator, const_iterator>
       ^
/usr/include/c++/5/bits/stl_tree.h:1248:38: error: ‘_Alloc_traits’ has not been declared
       operator=(_Rb_tree&&) noexcept(_Alloc_traits::_S_nothrow_move());
                                      ^
/usr/include/c++/5/bits/stl_tree.h:1261:36: error: ‘Ort::Ort::std::true_type’ has not been declared
       _M_move_data(_Rb_tree&, std::true_type);
                                    ^
/usr/include/c++/5/bits/stl_tree.h:1266:36: error: ‘Ort::Ort::std::false_type’ has not been declared
       _M_move_data(_Rb_tree&, std::false_type);
                                    ^
/usr/include/c++/5/bits/stl_tree.h:1266:7: error: ‘void Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_move_data(Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>&, int)’ cannot be overloaded
       _M_move_data(_Rb_tree&, std::false_type);
       ^
/usr/include/c++/5/bits/stl_tree.h:1261:7: error: with ‘void Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_move_data(Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>&, int)’
       _M_move_data(_Rb_tree&, std::true_type);
       ^
In file included from /usr/include/c++/5/bits/stl_pair.h:59:0,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/bits/char_traits.h:39,
                 from /usr/include/c++/5/string:40,
                 from /usr/include/c++/5/stdexcept:39,
                 from /usr/include/c++/5/array:38,
                 from /home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/onnxruntime_cxx_api.h:18,
                 from /home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h:18,
                 from /home/lgx/onnxruntime/onnruntimeprj/src/main.cpp:1:
/usr/include/c++/5/bits/stl_tree.h: In member function ‘Ort::Ort::std::_Rb_tree_node<_Val>* Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Reuse_or_alloc_node::operator()(_Arg&&)’:
/usr/include/c++/5/bits/stl_tree.h:398:34: error: ‘forward’ is not a member of ‘Ort::Ort::std’
   _M_t._M_construct_node(__node, _GLIBCXX_FORWARD(_Arg, __arg));
                                  ^
/usr/include/c++/5/bits/stl_tree.h:398:34: note: suggested alternative:
/usr/include/c++/5/bits/move.h:87:5: note:   ‘std::forward’
     forward(typename std::remove_reference<_Tp>::type&& __t) noexcept
     ^
/usr/include/c++/5/bits/stl_tree.h:398:34: error: expected primary-expression before ‘>’ token
   _M_t._M_construct_node(__node, _GLIBCXX_FORWARD(_Arg, __arg));
                                  ^
/usr/include/c++/5/bits/stl_tree.h:402:33: error: ‘forward’ is not a member of ‘Ort::Ort::std’
      return _M_t._M_create_node(_GLIBCXX_FORWARD(_Arg, __arg));
                                 ^
/usr/include/c++/5/bits/stl_tree.h:402:33: note: suggested alternative:
/usr/include/c++/5/bits/move.h:87:5: note:   ‘std::forward’
     forward(typename std::remove_reference<_Tp>::type&& __t) noexcept
     ^
/usr/include/c++/5/bits/stl_tree.h:402:33: error: expected primary-expression before ‘>’ token
      return _M_t._M_create_node(_GLIBCXX_FORWARD(_Arg, __arg));
                                 ^
/usr/include/c++/5/bits/stl_tree.h: In member function ‘Ort::Ort::std::_Rb_tree_node<_Val>* Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Alloc_node::operator()(_Arg&&) const’:
/usr/include/c++/5/bits/stl_tree.h:459:33: error: ‘forward’ is not a member of ‘Ort::Ort::std’
    { return _M_t._M_create_node(_GLIBCXX_FORWARD(_Arg, __arg)); }
                                 ^
/usr/include/c++/5/bits/stl_tree.h:459:33: note: suggested alternative:
/usr/include/c++/5/bits/move.h:87:5: note:   ‘std::forward’
     forward(typename std::remove_reference<_Tp>::type&& __t) noexcept
     ^
/usr/include/c++/5/bits/stl_tree.h:459:33: error: expected primary-expression before ‘>’ token
    { return _M_t._M_create_node(_GLIBCXX_FORWARD(_Arg, __arg)); }
                                 ^
In file included from /usr/include/c++/5/map:60:0,
                 from /usr/local/include/opencv2/flann/params.h:36,
                 from /usr/local/include/opencv2/flann/flann_base.hpp:40,
                 from /usr/local/include/opencv2/flann.hpp:48,
                 from /usr/local/include/opencv2/opencv.hpp:62,
                 from /home/lgx/onnxruntime/onnruntimeprj/src/main.cpp:4:
/usr/include/c++/5/bits/stl_tree.h: In member function ‘Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::allocator_type Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::get_allocator() const’:
/usr/include/c++/5/bits/stl_tree.h:486:53: error: there are no arguments to ‘_M_get_Node_allocator’ that depend on a template parameter, so a declaration of ‘_M_get_Node_allocator’ must be available [-fpermissive]
       { return allocator_type(_M_get_Node_allocator()); }
                                                     ^
/usr/include/c++/5/bits/stl_tree.h: In member function ‘Ort::Ort::std::_Rb_tree_node<_Val>* Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_get_node()’:
/usr/include/c++/5/bits/stl_tree.h:491:16: error: ‘_Alloc_traits’ has not been declared
       { return _Alloc_traits::allocate(_M_get_Node_allocator(), 1); }
                ^
/usr/include/c++/5/bits/stl_tree.h:491:62: error: there are no arguments to ‘_M_get_Node_allocator’ that depend on a template parameter, so a declaration of ‘_M_get_Node_allocator’ must be available [-fpermissive]
       { return _Alloc_traits::allocate(_M_get_Node_allocator(), 1); }
                                                              ^
/usr/include/c++/5/bits/stl_tree.h: In member function ‘void Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_put_node(Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type)’:
/usr/include/c++/5/bits/stl_tree.h:495:9: error: ‘_Alloc_traits’ has not been declared
       { _Alloc_traits::deallocate(_M_get_Node_allocator(), __p, 1); }
         ^
/usr/include/c++/5/bits/stl_tree.h:495:57: error: there are no arguments to ‘_M_get_Node_allocator’ that depend on a template parameter, so a declaration of ‘_M_get_Node_allocator’ must be available [-fpermissive]
       { _Alloc_traits::deallocate(_M_get_Node_allocator(), __p, 1); }
                                                         ^
/usr/include/c++/5/bits/stl_tree.h: In member function ‘void Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_construct_node(Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type, _Args&& ...)’:
/usr/include/c++/5/bits/stl_tree.h:529:8: error: ‘_Alloc_traits’ has not been declared
        _Alloc_traits::construct(_M_get_Node_allocator(),
        ^
/usr/include/c++/5/bits/stl_tree.h:529:55: error: there are no arguments to ‘_M_get_Node_allocator’ that depend on a template parameter, so a declaration of ‘_M_get_Node_allocator’ must be available [-fpermissive]
        _Alloc_traits::construct(_M_get_Node_allocator(),
                                                       ^
/usr/include/c++/5/bits/stl_tree.h:531:12: error: ‘forward’ is not a member of ‘Ort::Ort::std’
            std::forward<_Args>(__args)...);
            ^
/usr/include/c++/5/bits/stl_tree.h:531:12: note: suggested alternative:
In file included from /usr/include/c++/5/bits/stl_pair.h:59:0,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/bits/char_traits.h:39,
                 from /usr/include/c++/5/string:40,
                 from /usr/include/c++/5/stdexcept:39,
                 from /usr/include/c++/5/array:38,
                 from /home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/onnxruntime_cxx_api.h:18,
                 from /home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h:18,
                 from /home/lgx/onnxruntime/onnruntimeprj/src/main.cpp:1:
/usr/include/c++/5/bits/move.h:87:5: note:   ‘std::forward’
     forward(typename std::remove_reference<_Tp>::type&& __t) noexcept
     ^
In file included from /usr/include/c++/5/map:60:0,
                 from /usr/local/include/opencv2/flann/params.h:36,
                 from /usr/local/include/opencv2/flann/flann_base.hpp:40,
                 from /usr/local/include/opencv2/flann.hpp:48,
                 from /usr/local/include/opencv2/opencv.hpp:62,
                 from /home/lgx/onnxruntime/onnruntimeprj/src/main.cpp:4:
/usr/include/c++/5/bits/stl_tree.h:531:30: error: expected primary-expression before ‘>’ token
            std::forward<_Args>(__args)...);
                              ^
/usr/include/c++/5/bits/stl_tree.h: In member function ‘Ort::Ort::std::_Rb_tree_node<_Val>* Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_create_node(_Args&& ...)’:
/usr/include/c++/5/bits/stl_tree.h:546:29: error: ‘forward’ is not a member of ‘Ort::Ort::std’
    _M_construct_node(__tmp, std::forward<_Args>(__args)...);
                             ^
/usr/include/c++/5/bits/stl_tree.h:546:29: note: suggested alternative:
In file included from /usr/include/c++/5/bits/stl_pair.h:59:0,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/bits/char_traits.h:39,
                 from /usr/include/c++/5/string:40,
                 from /usr/include/c++/5/stdexcept:39,
                 from /usr/include/c++/5/array:38,
                 from /home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/onnxruntime_cxx_api.h:18,
                 from /home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h:18,
                 from /home/lgx/onnxruntime/onnruntimeprj/src/main.cpp:1:
/usr/include/c++/5/bits/move.h:87:5: note:   ‘std::forward’
     forward(typename std::remove_reference<_Tp>::type&& __t) noexcept
     ^
In file included from /usr/include/c++/5/map:60:0,
                 from /usr/local/include/opencv2/flann/params.h:36,
                 from /usr/local/include/opencv2/flann/flann_base.hpp:40,
                 from /usr/local/include/opencv2/flann.hpp:48,
                 from /usr/local/include/opencv2/opencv.hpp:62,
                 from /home/lgx/onnxruntime/onnruntimeprj/src/main.cpp:4:
/usr/include/c++/5/bits/stl_tree.h:546:47: error: expected primary-expression before ‘>’ token
    _M_construct_node(__tmp, std::forward<_Args>(__args)...);
                                               ^
/usr/include/c++/5/bits/stl_tree.h: In member function ‘void Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_destroy_node(Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type)’:
/usr/include/c++/5/bits/stl_tree.h:553:2: error: ‘_Alloc_traits’ has not been declared
  _Alloc_traits::destroy(_M_get_Node_allocator(), __p->_M_valptr());
  ^
/usr/include/c++/5/bits/stl_tree.h:553:47: error: there are no arguments to ‘_M_get_Node_allocator’ that depend on a template parameter, so a declaration of ‘_M_get_Node_allocator’ must be available [-fpermissive]
  _Alloc_traits::destroy(_M_get_Node_allocator(), __p->_M_valptr());
                                               ^
/usr/include/c++/5/bits/stl_tree.h: In constructor ‘Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Rb_tree_impl<_Key_compare, <anonymous> >::_Rb_tree_impl()’:
/usr/include/c++/5/bits/stl_tree.h:587:6: error: class ‘Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Rb_tree_impl<_Key_compare, <anonymous> >’ does not have any field named ‘_Node_allocator’
    : _Node_allocator(), _M_key_compare(), _M_header(),
      ^
/usr/include/c++/5/bits/stl_tree.h: In constructor ‘Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Rb_tree_impl<_Key_compare, <anonymous> >::_Rb_tree_impl(const _Key_compare&, const int&)’:
/usr/include/c++/5/bits/stl_tree.h:592:6: error: class ‘Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Rb_tree_impl<_Key_compare, <anonymous> >’ does not have any field named ‘_Node_allocator’
    : _Node_allocator(__a), _M_key_compare(__comp), _M_header(),
      ^
/usr/include/c++/5/bits/stl_tree.h: In constructor ‘Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Rb_tree_impl<_Key_compare, <anonymous> >::_Rb_tree_impl(const _Key_compare&, int&&)’:
/usr/include/c++/5/bits/stl_tree.h:598:6: error: class ‘Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Rb_tree_impl<_Key_compare, <anonymous> >’ does not have any field named ‘_Node_allocator’
    : _Node_allocator(std::move(__a)), _M_key_compare(__comp),
      ^
/usr/include/c++/5/bits/stl_tree.h:598:22: error: ‘move’ is not a member of ‘Ort::Ort::std’
    : _Node_allocator(std::move(__a)), _M_key_compare(__comp),
                      ^
/usr/include/c++/5/bits/stl_tree.h:598:22: note: suggested alternative:
In file included from /usr/include/c++/5/bits/char_traits.h:39:0,
                 from /usr/include/c++/5/string:40,
                 from /usr/include/c++/5/stdexcept:39,
                 from /usr/include/c++/5/array:38,
                 from /home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/onnxruntime_cxx_api.h:18,
                 from /home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h:18,
                 from /home/lgx/onnxruntime/onnruntimeprj/src/main.cpp:1:
/usr/include/c++/5/bits/stl_algobase.h:495:5: note:   ‘std::move’
     move(_II __first, _II __last, _OI __result)
     ^
In file included from /usr/include/c++/5/map:60:0,
                 from /usr/local/include/opencv2/flann/params.h:36,
                 from /usr/local/include/opencv2/flann/flann_base.hpp:40,
                 from /usr/local/include/opencv2/flann.hpp:48,
                 from /usr/local/include/opencv2/opencv.hpp:62,
                 from /home/lgx/onnxruntime/onnruntimeprj/src/main.cpp:4:
/usr/include/c++/5/bits/stl_tree.h: In copy constructor ‘Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Rb_tree(const Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>&)’:
/usr/include/c++/5/bits/stl_tree.h:815:10: error: ‘_Alloc_traits’ has not been declared
          _Alloc_traits::_S_select_on_copy(__x._M_get_Node_allocator()))
          ^
/usr/include/c++/5/bits/stl_tree.h: In constructor ‘Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Rb_tree(Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>&&)’:
/usr/include/c++/5/bits/stl_tree.h:847:22: error: ‘true_type’ is not a member of ‘Ort::Ort::std’
    _M_move_data(__x, std::true_type());
                      ^
/usr/include/c++/5/bits/stl_tree.h:847:22: note: suggested alternative:
In file included from /usr/include/c++/5/bits/move.h:57:0,
                 from /usr/include/c++/5/bits/stl_pair.h:59,
                 from /usr/include/c++/5/bits/stl_algobase.h:64,
                 from /usr/include/c++/5/bits/char_traits.h:39,
                 from /usr/include/c++/5/string:40,
                 from /usr/include/c++/5/stdexcept:39,
                 from /usr/include/c++/5/array:38,
                 from /home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/onnxruntime_cxx_api.h:18,
                 from /home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h:18,
                 from /home/lgx/onnxruntime/onnruntimeprj/src/main.cpp:1:
/usr/include/c++/5/type_traits:87:45: note:   ‘std::true_type’
   typedef integral_constant<bool, true>     true_type;
                                             ^
In file included from /usr/include/c++/5/map:60:0,
                 from /usr/local/include/opencv2/flann/params.h:36,
                 from /usr/local/include/opencv2/flann/flann_base.hpp:40,
                 from /usr/local/include/opencv2/flann.hpp:48,
                 from /usr/local/include/opencv2/opencv.hpp:62,
                 from /home/lgx/onnxruntime/onnruntimeprj/src/main.cpp:4:
/usr/include/c++/5/bits/stl_tree.h: In constructor ‘Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Rb_tree(Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>&&, const allocator_type&)’:
/usr/include/c++/5/bits/stl_tree.h:851:18: error: ‘move’ is not a member of ‘Ort::Ort::std’
       : _Rb_tree(std::move(__x), _Node_allocator(__a))
                  ^
/usr/include/c++/5/bits/stl_tree.h:851:18: note: suggested alternative:
In file included from /usr/include/c++/5/bits/char_traits.h:39:0,
                 from /usr/include/c++/5/string:40,
                 from /usr/include/c++/5/stdexcept:39,
                 from /usr/include/c++/5/array:38,
                 from /home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/onnxruntime_cxx_api.h:18,
                 from /home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h:18,
                 from /home/lgx/onnxruntime/onnruntimeprj/src/main.cpp:1:
/usr/include/c++/5/bits/stl_algobase.h:495:5: note:   ‘std::move’
     move(_II __first, _II __last, _OI __result)
     ^
In file included from /usr/include/c++/5/map:60:0,
                 from /usr/local/include/opencv2/flann/params.h:36,
                 from /usr/local/include/opencv2/flann/flann_base.hpp:40,
                 from /usr/local/include/opencv2/flann.hpp:48,
                 from /usr/local/include/opencv2/opencv.hpp:62,
                 from /home/lgx/onnxruntime/onnruntimeprj/src/main.cpp:4:
/usr/include/c++/5/bits/stl_tree.h: In member function ‘Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::size_type Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::max_size() const’:
/usr/include/c++/5/bits/stl_tree.h:910:16: error: ‘_Alloc_traits’ has not been declared
       { return _Alloc_traits::max_size(_M_get_Node_allocator()); }
                ^
/usr/include/c++/5/bits/stl_tree.h:910:62: error: there are no arguments to ‘_M_get_Node_allocator’ that depend on a template parameter, so a declaration of ‘_M_get_Node_allocator’ must be available [-fpermissive]
       { return _Alloc_traits::max_size(_M_get_Node_allocator()); }
                                                              ^
/usr/include/c++/5/bits/stl_tree.h: In member function ‘Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::iterator Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_insert_unique_(Ort::Ort::std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Al

i think #include <experimental_onnxruntime_cxx_api.h> is something wrong but i don't know why

**Comment by skottmckay** [comment]
Errors like the below would suggest something is wrong with the namespaces involved as there's no 'std' namespace inside Ort::Ort, and afaik also no nested 'Ort' namespace within a top level 'Ort' namespace (so neither 'Ort::Ort::' or 'Ort::Ort::std' should occur). Instead there should be a std::true_type from the standard library. 

`/usr/include/c++/5/bits/stl_tree.h:1261:36: error: ‘Ort::Ort::std::true_type’ has not been declared`

Can you reduce down to a minimal example with just the ORT headers (exclude the opencv headers) with no 'using namespace' statements and see if it can build?

**Comment by cqray1990** [comment]
@the examplse is in samples of onnxruntime official code,and i build it ,but failed,i didn't understand what you said clearly?

**Comment by cqray1990** [comment]
the code as follows:
#include <experimental_onnxruntime_cxx_api.h>
#include <onnxruntime_c_api.h>

//using namespace cv;
using namespace std;



int main(int argc, const char** argv) {
    return 0;
}
but errors comes:
In file included from /home/lgx/onnxruntime/onnruntimeprj/src/test.cpp:1:0:
/home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h:20:14: error: expected ‘{’ before ‘::’ token
 namespace Ort::Experimental {
              ^
/home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h:20:16: error: ‘Experimental’ in namespace ‘::’ does not name a type
 namespace Ort::Experimental {
                ^
In file included from /home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h:52:0,
                 from /home/lgx/onnxruntime/onnruntimeprj/src/test.cpp:1:
/home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_inline.h:8:14: error: expected ‘{’ before ‘::’ token
 namespace Ort::Experimental {
              ^
/home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_inline.h:8:16: error: ‘Experimental’ in namespace ‘::’ does not name a type
 namespace Ort::Experimental {
                ^
/home/lgx/onnxruntime/onnruntimeprj/src/test.cpp:11:1: error: expected ‘}’ at end of input
 }
 ^
/home/lgx/onnxruntime/onnruntimeprj/src/test.cpp:11:1: error: expected ‘}’ at end of input
CMakeFiles/Textreg.dir/build.make:65: recipe for target 'CMakeFiles/Textreg.dir/src/test.cpp.o' failed
make[2]: *** [CMakeFiles/Textreg.dir/src/test.cpp.o] Error 1
CMakeFiles/Makefile2:78: recipe for target 'CMakeFiles/Textreg.dir/all' failed
make[1]: *** [CMakeFiles/Textreg.dir/all] Error 2
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2

@skottmckay

**Comment by skottmckay** [comment]
What's the full command line are you building with?

**Comment by skottmckay** [comment]
Replaced by #4667
