### ISSUE TITLE
Multinomial float16 is broken since a recent change to the Cast transformer

### ISSUE THREAD

**Issue by PatriceVignola** [microsoft/onnxruntime#4644]
**Describe the bug**
Multinomial float16 throws an exception since a [recent change to the Cast transformer](https://github.com/microsoft/onnxruntime/pull/4523)

**To Reproduce**
Run inference the following model: [multinomial_float16.zip](https://github.com/microsoft/onnxruntime/files/4990832/multinomial_float16.zip)

**Expected behavior**
The model completes inference without throwing an exception

**Additional context**
The change to the Cast transformer sets the output types of nodes who have a "dtype" attribute to float, but Multinomial is a special case that outputs only int32 or int64 tensors. Therefore, an exception is thrown during inference.

**Comment by hariharans29** [comment]
Thanks, I ll take a look at this.
