### ISSUE TITLE
ACL performance with onnxruntime_perf_test

### ISSUE THREAD

**Issue by Dan5002** [microsoft/onnxruntime#4647]
This is a repost of
https://github.com/ARM-software/ComputeLibrary/issues/850

I think I should have posted it here instead of there.

I'm using ACL v19.08 with onnxruntime 1.3.1 (--branch master on July 9, 2020).

I'd like some help interpreting the performance information from onnxruntime_perf_test. The console output from perf_test with and then without acl is shown below.

Is it true that time spent on operations = 'Average inference time cost' - 'Session creation time cost' ?

In other words, is there a session creation time cost per inference time cost?

That is the only way I can see that ACL is outperforming native operations.

For ACL:
144.871 ms - 0.127918 s = 16.95 ms

Non-ACL:
84.3236 ms - 0.06094 s = 23.38 ms

But, why the increased session creation time cost for ACL?

And why the decreased CPU utilization?

result.csv shows there is very little variance, so average inference time is a good proxy for any one of the inferences.

onnxruntime_perf_test -m times -r 10 -e acl /sdcard/testdata/squeezenet1.0-9/model.onnx result.csv
Session creation time cost: 0.127918 s
Total inference time cost: 1.44871 s
Total inference requests: 10
Average inference time cost: 144.871 ms
Total inference run time: 1.44916 s
Avg CPU usage: 68 %
Peak working set size: 158171136 bytes

onnxruntime_perf_test -m times -r 10 /sdcard/testdata/squeezenet1.0-9/model.onnx result.csv
Session creation time cost: 0.06094 s
Total inference time cost: 0.843236 s
Total inference requests: 10
Average inference time cost: 84.3236 ms
Total inference run time: 0.843345 s
Avg CPU usage: 100 %
Peak working set size: 49754112 bytes

**Comment by skottmckay** [comment]
Session creation cost is completely separate from inferencing. It's a one-off cost to load and initialize the model. If ACL is enabled there's going to be whatever setup work it does to register kernels and being asked if it can handle nodes in the graph in addition to the base level of work when it's not enabled. 

As for CPU utilization it may depend on what's in the graph and whether individual nodes are parallelized differently for the CPU execution provider vs. the ACL one. Or there could be unnecessary data copies going on - not sure how the ACL EP handles memory allocations and copies (but I notice peak memory usage is way higher which suggests a potential problem). Possible cause would be if the allocator isn't quite setup properly and it's resulting in a device-to-device copy that isn't necessary if ACL is using CPU memory. 

Based on those numbers ACL is slower.

**Comment by Dan5002** [comment]
Same as:
https://github.com/ARM-software/ComputeLibrary/issues/850

Suggestion is to move forward to ACL 20.08.  Which is another issue.
