### ISSUE TITLE
onnxruntime_perf_test core dumped with rel-1.4.0 

### ISSUE THREAD

**Issue by leqiao-1** [microsoft/onnxruntime#4652]
**Describe the bug**
I built onnxruntime_perf_test binaries for ep dnnl with rel-1.4.0, and it returns core dumped when setting OMP_WAIT_POLICY=active with command: 
```onnxruntime_perf_test -e dnnl -P -y 1 -o 99 -m times -r 20 /data/mnist/mnist.onnx  result```

Setting inter_op_num_threads to 1
Session creation time cost: 0.00756754 s
Total inference time cost: 0.00109572 s
Total inference requests: 20
Average inference time cost: 0.0547861 ms
Total inference run time: 0.00111142 s
Avg CPU usage: 25 %
Peak working set size: 20254720 bytes
Segmentation fault (core dumped)

This problem didn't occur in rel-1.3.0. 

**System information**
- Binaries built in base image ubuntu 16.04 and tested in base image python:3.6
- ONNX Runtime version: 1.4.0
- GCC/Compiler version: gcc version 5.4.0

**To Reproduce**
- onnx model and test data: 
[mnist.zip](https://github.com/microsoft/onnxruntime/files/4993216/mnist.zip)
- other
[core.onnxruntime_per.zip](https://github.com/microsoft/onnxruntime/files/4993284/core.onnxruntime_per.zip)

**Comment by RyanUnderhill** [comment]
Interesting, we had to do a workaround on Windows to keep the OpenMP.dll loaded as it would crash on unload of the dnnl provider otherwise. I wonder if this is related.
