### ISSUE TITLE
loading a model in ort throws error: onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_62' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:43 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{22,256}, requested shape:{56,1,256}

### ISSUE THREAD

**Issue by natangold85** [microsoft/onnxruntime#4653]
i'm converting a pytorch model to onnx this model is exported as onnx model.
when i tried to load it using onnxruntime it returns this error:

onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_62' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:43 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{22,256}, requested shape:{56,1,256}

i isolated the problematic line to a stand alone model. 

`
import torch
import onnx
import onnxruntime

class Test(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x: torch.Tensor, y: torch.Tensor) -> torch.Tensor:
        x[:y.shape[0], 0, :] = y
        return x

x = torch.zeros((56,6,256))
y = torch.rand((22,256))

m = Test()
torch_outputs = m(x, y)

path = "/tmp/m.onnx"
torch.onnx.export(m, (x, y), path,
                    do_constant_folding=False,
                    opset_version=12,
                    input_names=["x", "y"],
                    output_names=["z"])

onnx_model = onnx.load_model(path)
onnx.checker.check_model(onnx_model)
inferred_model = onnx.shape_inference.infer_shapes(onnx_model)
onnx.save(inferred_model, path)

ort_model = onnxruntime.InferenceSession(path)

ort_outputs = ort_model.run(["z"], {"x": x.numpy(), "y": y.numpy()})
`

**System information**
i'm running on Linux Ubuntu 16.04 with python 3.6.8
pytorch: 1.6.0, onnxruntime: 1.4.0, onnx: 1.7.0

**To Reproduce**
run the attached code

**Comment by skottmckay** [comment]
You can't reshape something that's got 56x6x256 elements into something wtih 22x256 elements as the number of elements needs to match. onnxruntime is just reporting the attempted misuse of the Reshape operator.

https://github.com/pytorch/pytorch/issues is probably a better place for your question.

**Comment by natangold85** [comment]
i'm taking a slice of the tensor in this line:
x[:y.shape[0], 0, :] = y
where x shape is 56,1,256 and y shape is 22,256. this line is good i'm not sure why it translated as i didn't take x[:22,0,:].

**Comment by skottmckay** [comment]
I'm not familiar with how the pytorch to onnx converter is implemented. onnxruntime is running the output from that conversion process, an onnx model. We can't really say why the pytorch converter did what it did so I'd suggest creating an Issue in the pytorch github so the folks that work on that converter can look into it for you.

**Comment by d-colwell** [comment]
@natangold85 
try using the following pytorch code instead:
`x[:y.size(0),0,:]=y`

**Comment by natangold85** [comment]
its not solved the problem i will try my luck on pytorch github, thanks

**Comment by ynma-hanvo** [comment]
seem type of error here.    do you have a solution? 
thanks a lot

**Comment by shifujain** [comment]
@natangold85 , were you able to fix this issue. I am facing a similar issue in my code
```
"RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_3797' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:40 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{2,60}, requested shape:{60}"
```

**att_ta[0, :, :] = o_weights**

where,
att_ta.shape = [25,bs,60]
o_weights.shape = [bs, 60]
