### ISSUE TITLE
experimental_onnxruntime_cxx_api.h errors

### ISSUE THREAD

**Issue by cqray1990** [microsoft/onnxruntime#4667]
the code as follows:
#include <experimental_onnxruntime_cxx_api.h>
#include <onnxruntime_c_api.h>

//using namespace cv;
using namespace std;

int main(int argc, const char** argv) {
    return 0;
}
but errors comes:
In file included from /home/lgx/onnxruntime/onnruntimeprj/src/test.cpp:1:0:
/home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h:20:14: error: expected ‘{’ before ‘::’ token
 namespace Ort::Experimental {
              ^
/home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h:20:16: error: ‘Experimental’ in namespace ‘::’ does not name a type
 namespace Ort::Experimental {
                ^
In file included from /home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h:52:0,
                 from /home/lgx/onnxruntime/onnruntimeprj/src/test.cpp:1:
/home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_inline.h:8:14: error: expected ‘{’ before ‘::’ token
 namespace Ort::Experimental {
              ^
/home/lgx/onnxruntime/onnruntimeprj/../include/onnxruntime/core/session/experimental_onnxruntime_cxx_inline.h:8:16: error: ‘Experimental’ in namespace ‘::’ does not name a type
 namespace Ort::Experimental {
                ^
/home/lgx/onnxruntime/onnruntimeprj/src/test.cpp:11:1: error: expected ‘}’ at end of input
 }
 ^
/home/lgx/onnxruntime/onnruntimeprj/src/test.cpp:11:1: error: expected ‘}’ at end of input
CMakeFiles/Textreg.dir/build.make:65: recipe for target 'CMakeFiles/Textreg.dir/src/test.cpp.o' failed
make[2]: *** [CMakeFiles/Textreg.dir/src/test.cpp.o] Error 1
CMakeFiles/Makefile2:78: recipe for target 'CMakeFiles/Textreg.dir/all' failed
make[1]: *** [CMakeFiles/Textreg.dir/all] Error 2
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by skottmckay** [comment]
What's the full command line are you building with? Given the code compiles everywhere else afaik there's probably an issue with how you're trying to build it.

**Comment by pranavsharma** [comment]
@jgbradley1 can you take a look?

**Comment by jgbradley1** [comment]
At first glance, I notice you're trying to include both the `C++` experimental header and `C` headers. You should not have to do this - the experimental header includes the regular `C++` API header and the `C++` API provides direct access to the underlying C API.

You might be experiencing some naming conflicts by including both header files.
