### ISSUE TITLE
C# how to mock Run's result

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#4683]
**Is your feature request related to a problem? Please describe.**
1. In my unit tests I want to mock the result of `Run` from a session, and then test the logic that deals with the results
2. Due to performance I do not want to convert tensors to arrays, and so would rather keep tensors in `IDisposableReadOnlyCollection<DisposableNamedOnnxValue>`
3. I know we should not mock 3rd party, but this is a little different, and my C#-fu is not great

Currently I have to wrap `IDisposableReadOnlyCollection` as well as `DisposableNamedOnnxValue` because I cannot create any of them from normal tensors. 

What is the preferred/suggested way to avoid all these wrapping? Specially because some times I want to pass the result of one model directly to another and thus need to keep  `DisposableNamedOnnxValue` just as-is, to avoid data copy.

**System information**
- ONNX Runtime version (you are using): 1.4.0

**Describe the solution you'd like**
A public constructor for `DisposableNamedOnnxValue`, or a way to convert `NamedOnnxValue` to `DisposableNamedOnnxValue`. Internally it could ignore actually calling `Dispose` if the tensor is created like that.

**Describe alternatives you've considered**
Wrapping

```C#
    internal class TensorCollection : IDisposableReadOnlyCollection<TensorResult>
    {
        private readonly IDisposableReadOnlyCollection<DisposableNamedOnnxValue> _results;
        private readonly List<NamedOnnxValue> _tensorList;
        private bool _disposed; // To detect redundant calls
...
    }

    internal sealed class TensorResult : IDisposable
    {
        private readonly DisposableNamedOnnxValue _disposableOnnxValue;
        private readonly NamedOnnxValue _onnxValue;
        private bool _disposed; // To detect redundant calls

        public string Name { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="TensorResult"/> class.
        /// Wrap external type.
        /// </summary>
        public TensorResult(DisposableNamedOnnxValue disposableOnnxValue)
        {
            Contracts.AssertValue(disposableOnnxValue);

            _disposableOnnxValue = disposableOnnxValue;
            Name = disposableOnnxValue.Name;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TensorResult"/> class.
        /// Internal constructor, for mocking.
        /// </summary>
        internal TensorResult(NamedOnnxValue onnxValue)
        {
            Contracts.AssertValue(onnxValue);

            _disposableOnnxValue = null;
            _onnxValue = onnxValue;
            Name = onnxValue.Name;
        }

        public Tensor<T> AsTensor<T>()
        {
            if (_disposableOnnxValue != null)
            {
                return _disposableOnnxValue.AsTensor<T>();
            }
            return _onnxValue.AsTensor<T>();
        }

        public void Dispose()
        {
            if (!_disposed)
            {
                _disposableOnnxValue?.Dispose();
            }
            _disposed = true;
        }
    }

```

**Additional context**
Is there any suggestions or samples or generic advice?

**Comment by skottmckay** [comment]
Can the code you want to test take `IEnumerable<NamedOnnxValue>` instead of `IDisposableReadOnlyCollection<DisposableNamedOnnxValue>`? If so you may be able to pass in either the results from Run or any collection of NamedOnnxValue instances.

**Comment by dashesy** [comment]
I ended up using this:

```C#
    /// <summary>
    /// Wrap the result of a ONNXRuntime session.
    /// </summary>
    internal interface ISessionResult : IEnumerable<NamedOnnxValue>, IDisposable
    {
    }
```

I had to do an explicit casting because  `IDisposableReadOnlyCollection<DisposableNamedOnnxValue>` cannot be implicitly converted to `ISessionResult` but I still prefer this to the previous wrapping (of both the container as well as the values). 

```C#
return (ISessionResult)_session.Run(tensors);
```


But now I get `System.InvalidCastException` exception in runtime (not for tests)

```text
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.ML.OnnxRuntime.DisposableList`1[Microsoft.ML.OnnxRuntime.DisposableNamed
OnnxValue]' to type 'Microsoft.ComputerVision.Inference.ISessionResult'.
```

**Comment by dashesy** [comment]
It seems, as-is I cannot get the results to be both `IEnumerable<NamedOnnxValue>` and `IDisposable` even though the result `is`/implements both.

Is it possible to have the result also inherit a new public class?

```C#
internal public ISessionResult : IEnumerable<NamedOnnxValue>, IDisposable
``` 

You will not have to change any other code, because they are already implemented, but then we can use this interface to pass the results.

**Comment by skottmckay** [comment]
Not quite understanding the requirement to pass something that must also be an IDisposable to the 'do stuff with the results' code.

This code calls Run and gets the disposable types back
https://github.com/microsoft/onnxruntime/blob/d0297f8d249bc460c6c51b59eed8690853e9bca3/csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs#L205-L208

But uses a validate method that just takes a readonly collection of NamedOnnxValue (no cast required)

https://github.com/microsoft/onnxruntime/blob/d0297f8d249bc460c6c51b59eed8690853e9bca3/csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs#L338-L348

Can you not separate out the 'do stuff with results' code to be in methods that take a collection of NamedOnnxValue? Or is there some requirement that they take over ownership of the results?

**Comment by dashesy** [comment]
This line

```C#
using (var results = session.Run(container))
```
means `results` must be `dispoable`, so `Run`'s result must be disposable.
At the same time `Run`'s result must be a collection of `NamedOnnxValue`, like `IEnumerable` or `IReadOnlyCollection`.

There is no interface for the Run result. `do_stuff` should be able to work with both 
1. the result of actual ORT session's `Run`, for the normal operation
2. as well as the `mock`ed version in the unit test. 

```C#
            var mocOdResult = new Mock<ISessionResult>(MockBehavior.Strict);
            mocOdResult
                .Setup(res => res.GetEnumerator())
                .Returns(new List<NamedOnnxValue>
                {
                        NamedOnnxValue.CreateFromTensor<long>(
                            "input", new long[] { 10, 20 }.ToTensor()),
                        NamedOnnxValue.CreateFromTensor<long>(
                            "input2", new long[] { 1, 1, 1, 0 }.ToTensor().Reshape(new int[] { 1, 4 })),
                }.Select(s => s).GetEnumerator());
            mocOdResult.Setup(res => res.Dispose());
```

And there is no way to consolidate these two (without wrappers), unless there is a public interface that ORT session Run's result implements and we can use for mocking.

**Comment by skottmckay** [comment]
You're not forced to use `using`. You can have code that supports calling something that may return an IDisposable, and conditionally call Dispose() on that based on `x is IDisposable` combined with (x as IDisposable).Dispose().

Given that, is there any other reason why the results 'must' be a disposable?

>`public interface ISessionResult : IEnumerable<NamedOnnxValue>, IDisposable`

From what I can tell you can do covariant things when there is one type involved (e.g. the result can convert to `IReadOnlyCollection<NamedOnnxValue>`) but you can't cast to `ISessionResult` from `IDisposableReadOnlyCollection<DisposableNamedOnnxValue>`.  This error is at the casting location and not the attempted usage in a `using` statement.

FWIW I'd suggest you may want to consider creating an interface instead of using the ORT InferenceSession class directly. Insulates you from any changes to the latter and gives you an interface you control for mocking purposes.

**Comment by dashesy** [comment]
I am using an interface, that also has 'Run'. That returns 'ISessionResult' which is disposable so that I can use with 'using'.
I am going to stick to the wrapper for now.
