### ISSUE TITLE
PyTorch FPN segmentation model differs in inference between C++ in Windows and Python on Linux

### ISSUE THREAD

**Issue by samhodge** [microsoft/onnxruntime#4685]
**Describe the bug**

Inference in C++ in Windows produces a poor result compared to Python on Linux

**Urgency**
I have already started to see if inference is possible with libtorch 

The client is confused why we have a mIOU of 93% but the result is so poor

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.4
- Python version:3.6
- Visual Studio version (if applicable):2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1 7.6
- GPU model and memory: GTX 1060

**To Reproduce**
- Describe steps/code to reproduce the behavior.

Follow the cam vid tutorial here https://github.com/qubvel/segmentation_models.pytorch/blob/master/examples/cars%20segmentation%20(camvid).ipynb

Using a FPN model with Resnext 50 backbone

see:
https://github.com/samhodge/segmentation_models.pytorch/blob/master/examples/cars%20segmentation%20(camvid).ipynb

Export to opset 11

Produce inference in C++ on Windows using onnx runtime
TBA:

Produce inference in Python on Linux using onnx runtime 
see:
https://github.com/samhodge/segmentation_models.pytorch/blob/master/examples/example_PRY_onnx_.0.jpg

- https://github.com/samhodge/segmentation_models.pytorch/blob/master/examples/best_model.onnx.zip

**Expected behavior**

Inference should be identical 

**Screenshots**

https://github.com/samhodge/segmentation_models.pytorch/blob/master/examples/example_PRY_onnx_.0.jpg

**Additional context**
The actual model and data are client sensitive but I will reproduce with CamVid dataset

Under WinML there are errors with MaxPool and ceil attribute missing

**Comment by samhodge** [comment]
This is the output from C++ on Windows 10

![Output0001](https://user-images.githubusercontent.com/86946/89115078-f2c59380-d4c2-11ea-956a-7bac3a3043a0.jpg)


This is the same image in Python on Linux through the code in the notebook above
![example_WINNA_onnx_ 0](https://user-images.githubusercontent.com/86946/89115086-0670fa00-d4c3-11ea-8d38-55b25d6c8a5a.jpg)

Here is the input image from CamVid

![Image0019](https://user-images.githubusercontent.com/86946/89115090-20124180-d4c3-11ea-9268-77ef845aa9a4.png)

**Comment by samhodge** [comment]
C++ inference code is essentially

```
    static constexpr const int width_ = 320;
    static constexpr const int height_ = 320;
    static constexpr const int channels_input_ = 3;
    static constexpr const int channels_result_ = 1;
    static constexpr const int batch_size_ = 1;
    Ort::Env env;
    Ort::SessionOptions session_options = Ort::SessionOptions();
    const int whichCard = 0;
   const  wchar_t* model_path = L"C:\\models\\best_model.onnx";
    OrtStatusPtr cudaOK = OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, whichCard);
    Ort::Session session_= Ort::Session( env, model_path, session_options );

    Ort::Value input_tensor_{ nullptr };
    std::array<int64_t, 4> input_shape_{batch_size_, channels_input_, width_, height_ };

    Ort::Value output_tensor_{ nullptr };
    std::array<int64_t, 4> output_shape_{batch_size_,  channels_result_, width_, height_, };

        auto memory_info = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeDefault);
        input_tensor_ = Ort::Value::CreateTensor<float>(memory_info, input_image_.data(), input_image_.size(), input_shape_.data(), input_shape_.size());
        output_tensor_ = Ort::Value::CreateTensor<float>(memory_info, results_.data(), results_.size(), output_shape_.data(), output_shape_.size());
        const char* input_names[] = { "input/input.1" };
        const char* output_names[] = { "output/output.1" };  
        session_.Run(Ort::RunOptions{ nullptr }, input_names, &input_tensor_, 1, output_names, &output_tensor_, 1);

```

With a for loop for tiling and code to get the data from the image into the tensor.

**Comment by skottmckay** [comment]
Does python output on Windows differ from python output on Linux?

**Comment by hariharans29** [comment]
If the Python outputs in both platforms do match (i.e.) the diffs are platform agnostic and really just “python vs c++” diffs,  in almost all previous cases, diffs between C++ and Python have been attributed to quirks in the pre-processing libraries used. So can you ascertain if the “raw” input tensors being fed into the model are the same for both the c++ and python applications ?

**Comment by samhodge** [comment]
turns out the code for filling the tensor was wrong, but it was a step on the journey to me fixing it was to write up with ticket.

**Comment by gmbonini** [comment]
@samhodge 
Hi Sam, I'm experiencing a very similar issue. My output on c++ even tough is reasonable is not the same as from the python inference. My code seems similar to what you showed on the post. Can you share what exactly you changed to fill the tensor? 
Thank you

**Comment by samhodge** [comment]
Sorry the code belongs to my employer
