### ISSUE TITLE
Hardcoded CPU Allocator in TreeEnsembleCommon

### ISSUE THREAD

**Issue by Dudeldu** [microsoft/onnxruntime#4688]
https://github.com/microsoft/onnxruntime/blob/e70e9e2f6751e3ce14e7aeca1e21af46e5ad6350/onnxruntime/core/providers/cpu/ml/tree_ensemble_common.h#L604

Is there any specific reason for hardcoding the CPUAllocator here?  
As far as I understood the implementation, whouldn't it be more convenient to use the allocator, that is provided from the execution provider? 
For the basic CPU Provider this wouldn't make much of a difference, nevertheless it's a better sample for new providers and enables simpler insertion of custom allocators.

**Comment by skottmckay** [comment]
It would be better if it used `OpKernelContext::GetTempSpaceAllocator`. Would need the OpKernelContext instance to be passed through from the kernel's Compute method though.

**Comment by pranavsharma** [comment]
@xadupre adding a comment to keep the issue alive.
