### ISSUE TITLE
SetOutputs of graph in transformer not working as expected

### ISSUE THREAD

**Issue by Dudeldu** [microsoft/onnxruntime#4689]
I wrote a custom graph transformer, that has to add a new output to a graph. For that, I created new Nodes and tried to set the output of the graph with its `SetOutputs` method.  
Nevertheless the outputs aren't added as expected as seen when using `GetOutputName` via C++ API. **BUT** the optimized model, that gets exported with `SetOptimizedModelFilePath` session option, contains the added nodes and outputs as expected and after loading this one into ORT everything works fine.  
So it seems to me, the graph isn't correctly *rebuilt* after the transformers ran?! Maybe there is another flag, that must be set aside from the `modified` value?

**System information**
- commit: e70e9e2f6751e3ce14e7aeca1e21af46e5ad6350

**To Reproduce**
Basic implementation of transformer, that simply adds an ABS node on top of the first existing output and adds the new output to the graph as well (minimal sample).
```cpp
    const std::vector<const NodeArg*>& graphOutputs = graph.GetOutputs();

    NodeArg* out = new NodeArg(graph.GenerateNodeArgName("NEW OUTPUT"),
                                 &ONNX_NAMESPACE::Utils::DataTypeUtils::ToTypeProto(
                                     ONNX_NAMESPACE::Utils::DataTypeUtils::ToType("tensor(int64)")));
    Node& serializerNode = graph.AddNode(graph.GenerateNodeName("TEST"),
                                                 "Abs",
                                                 "TEST",
                                                 std::vector<NodeArg*>{const_cast<NodeArg*>(graphOutputs[0])},
                                                 std::vector<NodeArg*>{out},
                                                 nullptr,
                                                 kOnnxDomain);
    serializerNode.SetExecutionProviderType(kCpuExecutionProvider);

    std::vector<const NodeArg*> newOutputs{};

    for(const NodeArg* arg: graphOutputs){
        newOutputs.push_back(arg);
    }
    newOutputs.push_back(out);

    graph.SetOutputs(newOutputs);
    modified = true;
```

**Expected behavior**
I would expect to directly apply the changes, and not only after serializing to ONNX and reloading, or, if this behaviour was expected, I would wish to rename/hide the `SetOuputs` function.  
One workaround i'm currently using for just appending a node to an existing output is by mutating the NodeArg the *const* pointer of the graph outputs points towards, which works, but isn't the best way either.

**Comment by liqunfu** [comment]
did you have to call graph.Resolve()?

**Comment by Dudeldu** [comment]
graph.Resolve should be called, when the `modified` value is set to true anyways, as far as I can see. But even with explicitly calling Resolve the problem persits

**Comment by liqunfu** [comment]
Please take a look at this example to see what you may have missed:
[https://github.com/microsoft/onnxruntime/blob/7f5339505e146bfd303b629cd8f7d052ac72b461/onnxruntime/test/ir/graph_test.cc#L1321](url)

**Comment by Dudeldu** [comment]
I went through the test case, but as far as i can see, the main calls are identical (mainly graph.Resolve()). The only difference is the general setup.
For me the `SetOutputs` and the basic graph transformations (as tested in the TestCase inked) work, at least some kind of, as exporting the optimized model right after all transformation results in the expected ONNX model file, **BUT** the runtime session further goes with the old outputs. I would guess it somehow doesn't update the outputs after the transformations, please correct me if i'm wrong?

**Comment by Dudeldu** [comment]
I dug deeper into the onnxruntime inference_session with the following result:
The output names, that can be fetched from the C++ API are served from the private attribute `output_def_list_`of `inference_session`
https://github.com/microsoft/onnxruntime/blob/abbb7f6f5cfa69737c57363788f5ae712d3e1788/onnxruntime/core/session/inference_session.cc#L1333-L1343

The graph transformations are applied in the `Initialize`. Afterwards the graph gets (correctly) resolved, partitioned and finalized etc.
https://github.com/microsoft/onnxruntime/blob/abbb7f6f5cfa69737c57363788f5ae712d3e1788/onnxruntime/core/session/inference_session.cc#L921-L928
**BUT** as far as i can see, the `output_def_list_` is never updated during this whole process and therefore provides wrong information about the ouput definitions e.g.: after rename. Only write access inside the `SaveModelMetadata` function (as well as other attributes like `model_output_names_`) that is only called after the model was loaded https://github.com/microsoft/onnxruntime/blob/abbb7f6f5cfa69737c57363788f5ae712d3e1788/onnxruntime/core/session/inference_session.cc#L1453  
The same problem doesn't occure with inputs, as here the definitions are requested on demand right from the current graph, which might be a fix for this problem as well ???
https://github.com/microsoft/onnxruntime/blob/abbb7f6f5cfa69737c57363788f5ae712d3e1788/onnxruntime/core/session/inference_session.cc#L1317

**Can someone confirm that or correct me?**
