### ISSUE TITLE
Onnxruntimeserver Jupiter notebook has missing dependencies 

### ISSUE THREAD

**Issue by quantum-fusion** [microsoft/onnxruntime#4711]
**Describe the bug**

The OnnxRuntimeServerSSDModel Jupiter notebook requires two dependencies.
https://github.com/onnx/tutorials/blob/master/tutorials/OnnxRuntimeServerSSDModel.ipynb

These dependencies are missing:
import assets.onnx_ml_pb2 as onnx_ml_pb2
import assets.predict_pb2 as predict_pb2

Execute the ipynb script

ModuleNotFoundError: No module named 'onnx_ml_pb2'

**Comment by liqunfu** [comment]
[https://github.com/onnx/tutorials/issues/210](url)

**Comment by liqunfu** [comment]
duplicate to another issue (linked). Close this one.
