### ISSUE TITLE
openvino performance test

### ISSUE THREAD

**Issue by leqiao-1** [microsoft/onnxruntime#4720]
**Describe the bug**
I have tested python wheel 1.4.0 built for execution provider ngraph and openvino with diffierent combinations of OMP_WAIT_POLICY (active, passive), OMP_THREAD_NUM (1, 4, 8), inter thread num (1, 4, 8), intra thread num (1, 4, 8), execution mode (sequential, parallel). 

For ngraph ep, the model inference latency varies from 50ms to 500ms, but for openvino ep, inference latency varies from 50ms to 54ms. For openvino ep, I have tried onnxruntime.GraphOptimizationLevel.ORT_DISABLE_ALL and onnxruntime.GraphOptimizationLevel.ORT_ENABLE_ALL, and I got same result. 

Is that normal, or if there is any other ways to set thread num for openvino ? 

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- ONNX Runtime installed from source
- ONNX Runtime version: 1.4.0
- Python version: 3.6 
- 8 cores machine

**Comment by jywu-msft** [comment]
OpenVINO CPU backend should use DNNL which uses OMP , so I would have thought it has similar behavior to nGraph EP. 
+@smkarlap , @suryasidd  for any thoughts/comments

**Comment by smkarlap** [comment]
OpenVINO uses Thread Building Blocks (TBB) by default. OpenMP can be optionally enabled instead, but is not the default. That's probably why the environment variables are not taking any effect. Please refer to the OpenVINO optimization guide for more information about these settings: https://docs.openvinotoolkit.org/latest/openvino_docs_optimization_guide_dldt_optimization_guide.html
