### ISSUE TITLE
Some output shapes become fixed numbers when using onnxruntime to load the model

### ISSUE THREAD

**Issue by wangzbo** [microsoft/onnxruntime#4724]
I am using pytorch.onnx to export a model and specify the output as dynamic_axes:

dynamic_axes={'input1' : {0:'batch_size'}, 'input2' : {0:'batch_size'}, 'input3':{0:'batch_size'}, 'input4':{0:'batch_size'},
    'output1':[0,1],'output2':[0,1],'output3':[0,1,2],'output4':[0,1],'output5':[0,1],'output6':[0,1,2],'output7':[0,1,2,3],'output8':[0,1]})

The model is successfully exported and I can see the exported onnx model's graph output shape using onnx.load(onnx_model_path):

Shape{
    dim{
        dim_params:"output3_dynamic_axes_1"
    }
    dim{
        dim_params:"output3_dynamic_axes_2"
    }
    dim{
        dim_params:"output3_dynamic_axes_3"
    }
}
That is correct for output3. But when I use:
sess = rt.InferenceSession(onnx_model_path)

And looked into sess.get_outputs(),the shape for output3 is changed to fixed numbers: {name:'output3',shape:[2,4,6],type:'tensor(float)'}.
Not all the output are changed to fixed numbers. Output1,output2,output4,output5,output8 have no problem. Output3, output6 and the first three dimensions in output7 are becoming fixed numbers.

System information:
python: 3.7.6
pytorch: 1.6.0
opset_version: 11
onnx_runtime: 1.4.0
OS: macOS mojave

Is it an issue of onnxruntime when loading the onnx model?

**Comment by liqunfu** [comment]
onnxruntime does shape inference after loading a model. The output shape must be a result after onnruntime shape inference. Are you able to run sess inference?
If you cannot run sess inference, would you please share a minimal repo?

**Comment by wangzbo** [comment]
Yes, I can not run sess inference with the error below:

> File "/usr/local/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 110, in run
>     return self._sess.run(output_names, input_feed, run_options)
> onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_3740' Status Message: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:43 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape &,std::vector<int64_t> &) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{5,100}, requested shape:{1,6,100}

Not sure if it is related to the fixed output shape after loading the onnx model. I can provide the exported onnx model as well as a piece of code for inference with it. The input in the code is random but with the same sizes and types as the real input:

    sess = rt.InferenceSession("nl2sql.onnx")
    output3_name = sess.get_outputs()[2].name
    print("output3 name", output3_name)
    output3_shape = sess.get_outputs()[2].shape
    print("output3 shape", output3_shape)

    input1,input2,input3,input4,input5,input6 = np.random.randn(64,10,300).astype(np.float32),np.ones(64,dtype=np.int64)*10,np.random.randn(320,10,300).astype(np.float32),np.ones(320,dtype=np.int64)*10,np.ones(64,dtype=np.int64)*5,np.ones(64,dtype=np.int64)*5
    score = sess.run(['output1','output2','output3','output4','output5','output6','output7','output8'], {'input1':input1,'input2':input2,'input3':input3,'input4':input4,'input5':input5,'input6':input6})


[nl2sql.onnx.zip](https://github.com/microsoft/onnxruntime/files/5039654/nl2sql.onnx.zip)

Hope this is helpful. Thanks.

**Comment by hariharans29** [comment]
`The fixed shape [2,4,6] is the output3 size when I call torch.onnx.export() with a specific input` - Can you please check with the Torch project if the model is correctly exported to support dynamic shapes ?

**Comment by wangzbo** [comment]
> `The fixed shape [2,4,6] is the output3 size when I call torch.onnx.export() with a specific input` - Can you please check with the Torch project if the model is correctly exported to support dynamic shapes ?

Yes, I checked the model by:
check_model = onnx.load(onnx_model_path)
onnx.checker.check_model(check_model)

and look into the check_model's graph output shape for output3:
Shape{
dim{
dim_params:"output3_dynamic_axes_1"
}
dim{
dim_params:"output3_dynamic_axes_2"
}
dim{
dim_params:"output3_dynamic_axes_3"
}
}
It is not shape [2,4,6].

**Comment by hariharans29** [comment]
Not sure if the output shape should be fixed if exported to be explicitly support dynamic shapes. It feels like a conversion issue.

CC: @spandantwari @neginraoof for the converter aspect

**Comment by wangzbo** [comment]
It may be an export issue. closed.
