### ISSUE TITLE
How to correctly (make) install onnxruntime on a Linux machine?

### ISSUE THREAD

**Issue by jf99** [microsoft/onnxruntime#4725]
I am trying to build and install the library on Linux. This is how I do it:
```
export CUDACXX="/usr/local/cuda-10.0/bin/nvcc"
./build.sh --config Release --parallel --cmake_extra_defines CMAKE_INSTALL_PREFIX=/home/jf99/install/usr/local --use_cuda --cuda_version 10.0 --cuda_home /usr/local/cuda-10.0 --cudnn_home /usr/local/cuda-10.0 --use_tensorrt --tensorrt_home /usr/lib/x86_64-linux-gnu/ --skip_tests
cd build/Linux/Release
make install
# I also tried "cmake -P cmake_install.cmake" instead, same effect
```
This works, however when I look at the contents of the installation directory there is a lot missing and I cannot compile any program using onnxruntime with that. For example have a look at /home/jf99/install/usr/local/libs:
```bash
$ ls -1
libnvonnxparser.so
libnvonnxparser.so.7
libnvonnxparser.so.7.0.0
libnvonnxparser_static.a
```

The build directory has much more to offer:
```bash
$ ls -1
bin
CMakeCache.txt
CMakeFiles
cmake_install.cmake
CPackConfig.cmake
CPackSourceConfig.cmake
CTestTestfile.cmake
external
install_manifest.txt
lib
libcustom_op_library.so
libonnxruntime_common.a
libonnxruntime_framework.a
libonnxruntime_graph.a
libonnxruntime_mlas.a
libonnxruntime_optimizer.a
libonnxruntime_providers.a
libonnxruntime_providers_cuda.a
libonnxruntime_providers_tensorrt.a
libonnxruntime_session.a
libonnxruntime_test_utils.a
libonnxruntime_util.a
libonnx_test_data_proto.a
libonnx_test_runner_common.a
Makefile
onnx
onnxruntime_config.h
onnxruntime_mlas_test
onnxruntime_perf_test
onnxruntime_test_all
onnx_test_runner
testdata
tml.pb.cc
tml.pb.h
```
Look at all the libonnxruntime_*.a files! What can I do to make `make install` copy everything that is in fact needed to compile and link a program with onnxruntime?

**Comment by liqunfu** [comment]
According to:
[https://github.com/microsoft/onnxruntime#binaries](url)
[https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#linuxmac-os-x](url)
You shall install from Nuget(s)

**Comment by Craigacp** [comment]
I think you want `--build_shared_lib` to make the so file you can link against.

**Comment by jf99** [comment]
@liqunfu Correct me if I'm wrong, but isn't nuget Windows-only? Besides, according to your first link (which is broken btw), the prebuilt libraries are built against CUDA 10.1. I would prefer CUDA 10.0.

@Craigacp No, I don't want shared libs. I want .a files which are static libs. I'm in fact surprised that `make install` came up with .so files although I did not specify `--build_shared_lib`.

**Comment by snnn** [comment]
Nuget isn't Windows-only.  You can also get a prebuilt binary in tarball format from https://github.com/microsoft/onnxruntime/releases/tag/v1.4.0

**Comment by liqunfu** [comment]
@jf99 you may build onnxruntime with Cuda 10.0 (seems you already did). The shared library (libonnxruntime.so) is installed so it can be loaded at runtime. If you prefer tighter integration with onnxruntime, you may choose to fork onnxruntion add your project into it. That is one way you make use of libonnxruntime_*.a. You may take a look at how onnx_test_runner is built within the repo.

BTW, libonnxruntime.so is not built if you did not specify --build_shared_lib (at least it was not on my Ubuntu machine)

**Comment by lifa08** [comment]
The copy_strip_binary.sh is used by onnxruntime CI to generate the prebuild Linux packages and publish it [[here]](https://github.com/microsoft/onnxruntime/releases/), so instead of running make install, we can run 
`tools/ci_build/github/linux/copy_strip_binary.sh -r build/Linux -a onnxruntime -l libonnxruntime.so.1.9.1 -c RelWithDebInfo -s . -t 2a96b73a1afa9aaafb51`

The scripts generates onnxruntime diretory under build/Linux, we can copy it to the place we want to install the library.
`cp -r build/Linux/onnxruntime/ ~/install/`
