### ISSUE TITLE
Mem pattern should be disabled when using DML execution provider.

### ISSUE THREAD

**Issue by YunYang1994** [microsoft/onnxruntime#4740]
**Describe the bug**

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by hariharans29** [comment]
Can you please share some context ? Filling out the issue template with a detailed explanation of the requirement will help. Thanks.

**Comment by hariharans29** [comment]
If using the C API, this should disable the mem pattern - 

https://github.com/microsoft/onnxruntime/blob/2e3ccc75187600c10ebdfa5cb62b538c987d1b00/include/onnxruntime/core/session/onnxruntime_c_api.h#L318

**Comment by YunYang1994** [comment]
thank you, I got it
