### ISSUE TITLE
Error when buliding sample MNIST with visual studio 2019

### ISSUE THREAD

**Issue by zhuxiaoxuhit** [microsoft/onnxruntime#4766]
**Describe the bug**
Samle path:     onnxruntime/samples/c_cxx/MNIST

When  building it, got error:
$ build.bat   //this command

//////////////////////////
MNIST.cpp
MNIST.cpp(44): error C2039: "max_element": 不是 "std" 的成员
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\cmath(683): note: 参见 “std”的声明
MNIST.cpp(44): error C3861: “max_element”: 找不到标识符
MNIST.cpp(188): error C2039: "min_element": 不是 "std" 的成员
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\cmath(683): note: 参见 “std”的声明
MNIST.cpp(188): error C3861: “min_element”: 找不到标识符
MNIST.cpp(192): error C3536: “range”: 初始化之前无法使用
/////////////////////////

**System information**
- Windows 10
- ONNX Runtime installed from source
- Python version:  3.8.5
- Visual Studio version (if applicable): Microsoft Visual C++ 2019   16.7.1
- GCC/Compiler version (if compiling from source): Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
- CUDA/cuDNN version: just cpu version
- GPU model and memory: just cpu version

**Expected behavior**
no errors

**Comment by zhuxiaoxuhit** [comment]
Maybe need translate this error message：
//////////////////////////
MNIST.cpp
MNIST.cpp(44): error C2039: "max_element": not member variable  of "std" 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\cmath(683): note: reference to declaration “std” .
MNIST.cpp(44): error C3861: “max_element”:  cannt find this identifier.
MNIST.cpp(188): error C2039: "min_element": not member variables "std" 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\cmath(683): note: reference to declaration “std” .
MNIST.cpp(188): error C3861: “min_element”: cannot find this identifier.
MNIST.cpp(192): error C3536: “range”:  unavailable before initialization
/////////////////////////

**Comment by snnn** [comment]
Hi @zhuxiaoxuhit could you please help me try this fix: #4773 ?

Thanks.

**Comment by zhuxiaoxuhit** [comment]
Hi，@snnn Thanks for your reply. And this error has disappeared. But I got thie new error.........
when I built MNIST, got this message:(told me onnxruntime.lib with 64bit, but sample MNIST need 32bit lib)
/////////////////////////////////////////////////////////////
E:\onnxruntime\samples\c_cxx\MNIST>cl MNIST.cpp /Zi /EHsc /I..\..\..\include\onnxruntime\core\session /link /LIBPATH:..\..\..\build\Windows\Debug\Debug
用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.27.29111 版
版权所有(C) Microsoft Corporation。保留所有权利。

MNIST.cpp
Microsoft (R) Incremental Linker Version 14.27.29111.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:MNIST.exe
/debug
/LIBPATH:..\..\..\build\Windows\Debug\Debug
MNIST.obj
MNIST.obj : error LNK2019: 无法解析的外部符号 _OrtGetApiBase@0，函数 "void __cdecl `dynamic initializer for 'public: static struct OrtApi const * const Ort::Global<void>::api_''(void)" (??__E?api_@?$Global@X@Ort@@2PBUOrtApi@@B@@YAXXZ) 中引用了该符号
..\..\..\build\Windows\Debug\Debug\onnxruntime.lib : warning LNK4272:库计算机类型“x64”与目标 计算机类型“x86”冲突
MNIST.exe : fatal error LNK1120: 1 个无法解析的外部命令
//////////////////////////////////////////////////////////////
