### ISSUE TITLE
FP16 model is not faster than full precision

### ISSUE THREAD

**Issue by tsaizhenling** [microsoft/onnxruntime#4769]
**Describe the bug**
half precision model is not faster than full precision

Urgency
Float16 deployment is blocked

System information

    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
    ONNX Runtime installed from (source or binary): binary
    ONNX Runtime version: tried both 1.3.0 and 1.4.0
    Python version: N/A
    Visual Studio version (if applicable): N/A
    GCC/Compiler version (if compiling from source): N/A
    CUDA/cuDNN version: CUDA Version 10.2.89 cuDNN 7.6.5
    GPU model and memory: GeForce RTX 2070 SUPER 8GB

**To Reproduce**
run both models with c++ API with CUDA provider,
half precision model has casts in the beginning and end of model so u can feed full precision tensors
full precision model: [model_fp32.zip](https://github.com/microsoft/onnxruntime/files/5063252/model_fp32.zip)
half precision model:[model_fp16.zip](https://github.com/microsoft/onnxruntime/files/5063253/model_fp16.zip)

**Expected behavior**
half precision model to be significantly faster

**Comment by hariharans29** [comment]
There could be a few nodes that have dropped down to CPU because they haven't been supported in the CUDA EP. Any such indicators from the logs ?

**Comment by tsaizhenling** [comment]
no, the models loaded without warnings

**Comment by tianleiwu** [comment]
Here is fp32 model:
![image](https://user-images.githubusercontent.com/30328909/92988401-03810600-f480-11ea-8b4a-42688f9a3f42.png)

fp32 model after optimization:
![image](https://user-images.githubusercontent.com/30328909/92988443-6b375100-f480-11ea-9b01-12d892616790.png)

fp16 model after optimization:
![image](https://user-images.githubusercontent.com/30328909/92988459-8bffa680-f480-11ea-8ff0-4cbb11b024c2.png)

It seems there is no corresponding FP16 operators (for Conv and BatchNormalization or fusion) so onnxruntime has to convert float16 back to float32 in computing. That makes it slower
