### ISSUE TITLE
Error when buliding sample MNIST with visual studio 2019

### ISSUE THREAD

**Issue by zhuxiaoxuhit** [microsoft/onnxruntime#4782]
**Describe the bug**
Samle path: onnxruntime/samples/c_cxx/MNIST

When building it, got error:
$ build.bat //this command

when I built MNIST, got this message:(told me onnxruntime.lib with 64bit, but sample MNIST need 32bit lib)
/////////////////////////////////////////////////////////////
E:\onnxruntime\samples\c_cxx\MNIST>cl MNIST.cpp /Zi /EHsc /I......\include\onnxruntime\core\session /link /LIBPATH:......\build\Windows\Debug\Debug
用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.27.29111 版
版权所有(C) Microsoft Corporation。保留所有权利。

MNIST.cpp
Microsoft (R) Incremental Linker Version 14.27.29111.0
Copyright (C) Microsoft Corporation. All rights reserved.

/out:MNIST.exe
/debug
/LIBPATH:......\build\Windows\Debug\Debug
MNIST.obj
MNIST.obj : error LNK2019: 无法解析的外部符号 _OrtGetApiBase@0，函数 "void _cdecl `dynamic initializer for 'public: static struct OrtApi const * const Ort::Global::api''(void)" (??_E?api@?$Global@X@Ort@@2PBUOrtApi@@b@@YAXXZ) 中引用了该符号
......\build\Windows\Debug\Debug\onnxruntime.lib : warning LNK4272:库计算机类型“x64”与目标 计算机类型“x86”冲突
MNIST.exe : fatal error LNK1120: 1 个无法解析的外部命令
//////////////////////////////////////////////////////////////

**System information**
Windows 10
ONNX Runtime installed from source
Python version: 3.8.5
Visual Studio version (if applicable): Microsoft Visual C++ 2019 16.7.1
GCC/Compiler version (if compiling from source): Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
CUDA/cuDNN version: just cpu version
GPU model and memory: just cpu version

**Expected behavior**
no errors

**Comment by zhuxiaoxuhit** [comment]
Maybe i need to use "build.bat --x86" when build the whole project?

**Comment by snnn** [comment]
In your start menu, please look for "x64 Native Tools Command Prompt for VS 2019" and open it. Then run the cl command in that window.

**Comment by zhuxiaoxuhit** [comment]
Hi, @snnn , Thank you for ur help!!! Finally, I got it.

**Comment by zhuxiaoxuhit** [comment]
![image](https://user-images.githubusercontent.com/32813150/90211102-5e442500-de22-11ea-86e8-51eac1aab345.png)
