### ISSUE TITLE
Huge performance difference Intel CPU vs. Ryzen CPU

### ISSUE THREAD

**Issue by marcown** [microsoft/onnxruntime#4785]
**Describe the bug**
I am using onnxruntime 1.4 for python and for C++ and I want to do an inference on the CPU (it is a typical Segmentation CNN).
The Problem is that on intel cpu it takes 40s up to 70s to run it (e.g. intel i7-9700) and on a ryzen cpu it takes 3s ( AMD Ryzen 5 3600 ) both in python and c++.
The model is exported from pytorch and input dimensions are 1x3x10024x1024

What could be the reason? 

**Urgency**
We want to use it onsite.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, 64bit
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.4.0
- Python version: 3.8
- Visual Studio version (if applicable): - 
- GCC/Compiler version (if compiling from source): - 
- CUDA/cuDNN version: - 
- GPU model and memory: -

**To Reproduce**
Run any segmentation CNN on intel and amd ryzen.

**Expected behavior**
Both have similar performance (maybe factor 2)

**Comment by hariharans29** [comment]
Are you able to share the model for someone to take a look ? Also, sharing the model invocation script will help.

**Comment by marcown** [comment]
Hey, thanks for the response.

I can't share the model. However, I will try it with a different one and also share the script.
