### ISSUE TITLE
unclear error message: INVALID_ARGUMENT : Unexpected input data type. Actual: (N11onnxruntime17PrimitiveDataTypeIlEE) , expected: (N11onnxruntime17PrimitiveDataTypeIiEE)

### ISSUE THREAD

**Issue by Zhen-hao** [microsoft/onnxruntime#4787]
Hi, 

I have a fine-tuned BERT model that has the following shape.

```
graph_name: tf_bert_for_multi_classification
domain: onnxmltools
description: 
input 0: "attention_mask" ["N", 7] Int32
input 1: "input_ids" ["N", 7] Int32
input 2: "token_type_ids" ["N", 7] Int32
output 0: "output_1" ["N", 4404, 1] Float
```

when I try to run the model with
```
results = session.run(None, inputs_onnx)
```
where `inputs_onnx` is 
```
{'input_ids': array([ 101,  146, 1169, 1631, 1103, 3974,  117, 1169, 1128,  136,  102]),
 'token_type_ids': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 'attention_mask': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])}
```
I got the following error.

```
>>> results = session.run(None, inputs_onnx)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/xws61xnjc03fjiwfh7ci5cwgg1chmp3l-python3.7-onnxruntime-1.4.0/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 110, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (N11onnxruntime17PrimitiveDataTypeIlEE) , expected: (N11onnxruntime17PrimitiveDataTypeIiEE)
```

It is really hard for me to debug because it is not clear from the error message what's wrong.
I can't find source code covering `N11onnxruntime17PrimitiveDataTypeIiEE` or `N11onnxruntime17PrimitiveDataTypeIlEE`

**Comment by hariharans29** [comment]
Which platform are you on? Trying to figure out why the expected/actual types get printed that way.

The issue is your model (most likely) expects float inputs but you feeding in some other data type. Can you please check if the expected type for inputs to the model and your inputs' type align ?

**Comment by Zhen-hao** [comment]
@hariharans29 
I'm using NixOS which is a Linux x86_64.

The expected data type is `Int32` as shown in 
```
input 0: "attention_mask" ["N", 7] Int32
input 1: "input_ids" ["N", 7] Int32
input 2: "token_type_ids" ["N", 7] Int32
output 0: "output_1" ["N", 4404, 1] Float
```
I printed that info out in some Rust code wrapping the C API.
The error I got is the same with the C API as the Python API. 

What are `N11onnxruntime17PrimitiveDataTypeIlEE` and `N11onnxruntime17PrimitiveDataTypeIiEE`?

**Comment by hariharans29** [comment]
I am not sure - I think they just get printed out this weird way on some platforms. My guess is expected type is Int32 and you are feeding in float. Can you change the type of your numpy object inputs to be np.int32 ?

**Comment by Zhen-hao** [comment]
the input arrays should already have int type. 
how can I force the `np.int32` type? 

if I feed the model
```
{'input_ids': array([ 101,  146, 1169, 1631, 1103, 3974,  117, 1169, 1128,  136,  102],
       dtype=int32),
 'token_type_ids': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 'attention_mask': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)}
```
I got error 
```
  File "/nix/store/xws61xnjc03fjiwfh7ci5cwgg1chmp3l-python3.7-onnxruntime-1.4.0/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 110, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: token_type_ids Got: 1 Expected: 2 Please fix either the inputs or the model.
```

**Comment by Zhen-hao** [comment]
I run the same code on macOS but got a slightly different error

```
~/.pyenv/versions/3.7.8/lib/python3.7/site-packages/onnxruntime/capi/session.py in run(self, output_names, input_feed, run_options)
    108             output_names = [output.name for output in self._outputs_meta]
    109         try:
--> 110             return self._sess.run(output_names, input_feed, run_options)
    111         except C.EPFail as err:
    112             if self._enable_fallback:

InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (N11onnxruntime17PrimitiveDataTypeIxEE) , expected: (N11onnxruntime17PrimitiveDataTypeIiEE)
```

On the previous NixOS, the actual type is `N11onnxruntime17PrimitiveDataTypeIjEE` when I run the inference in Rust (wrapping the C API)

Where is the code determining the actual type?

**Comment by hariharans29** [comment]
1) Yeah, we need to investigate why on some platforms the types get printed like this. on Windows, Ubuntu - it seems to not print this.

2)  `the input arrays should already have int type.` - I don't think they were and hence the complaint by ORT. I think numpy default to float and it says it expects int (atleast that is what the error message was trying to convey). You got it right after this - `dtype = int32`

3) The next error is about invalid rank of the input (it means you crossed the type mismatch issue). What is the expected shape of the inputs to the model ? You are feeding it 1D arrays from what you pasted. But the expected is that it be 2D for some inputs atleast. You can open up the model in Netron and check the expected input shapes of the inputs to the model.

**Comment by Zhen-hao** [comment]
<img width="738" alt="Screenshot 2020-08-17 at 06 31 12" src="https://user-images.githubusercontent.com/10957195/90357453-4c959400-e053-11ea-9f0f-238509fcef37.png">

Netron shows the same shape. 
I thought "N" is a symbolic dimension that could be treated as 1. 
I also don't know where the 7 comes from since it is a BERT model. 
Maybe there is a bug in the model exporting. I'll spend more time there.

**Comment by hariharans29** [comment]
Well - you are right - symbolic dimension could be treated as 1 - and hence the shape of the input will then be [1, 7].
Shape = [1, 7] -> Rank = 2. 

What you are feeding in is - shape = [7] -> Rank = 1. That is the complaint from ORT. 

In Python, the input would look like this -> [[1, 1, 1, 1, 1, 1, 1]] (rank 2) as opposed to [1, 1, 1, 1, 1, 1, 1,] (rank 1).

Hope this helps

**Comment by Zhen-hao** [comment]
@hariharans29 thanks a lot for your guidance! 
I'm closing this one since it is clear that something went wrong in the model.

```python
>>> inputs_onnx
{'input_ids': [array([ 101,  146, 1169, 1631, 1103, 3974,  117, 1169, 1128,  136,  102],
      dtype=int32)], 'token_type_ids': [array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)], 'attention_mask': [array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)]}
>>> results = session.run(None, inputs_onnx)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/xws61xnjc03fjiwfh7ci5cwgg1chmp3l-python3.7-onnxruntime-1.4.0/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 110, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: token_type_ids for the following indices
 index: 1 Got: 11 Expected: 7
 Please fix either the inputs or the model.
```
It doesn't make sense to always ask for 7 tokens in a BERT model.

**Comment by duongkstn** [comment]
I got same issuse @Zhen-hao . Did you solved it ?

**Comment by Zhen-hao** [comment]
> I got same issuse @Zhen-hao . Did you solved it ?

if you mean the type error, you can enforce the int32 type on your data.

**Comment by sentian** [comment]
@Zhen-hao Mine also asked for 7 inputs. How did you solve the problem? Thanks.

**Comment by Zhen-hao** [comment]
for me, the problem was a bug in the transformers library exporting TF BERT models to ONNX. I had to export the model in a different way.

**Comment by Philipduerholt** [comment]
I'm running into similar problems.
> for me, the problem was a bug in the transformers library exporting TF BERT models to ONNX. I had to export the model in a different way.

@Zhen-hao  Can you explain, which different way you exported your model to ONNX, though? 😅

**Comment by Zhen-hao** [comment]
> I'm running into similar problems.
> 
> > for me, the problem was a bug in the transformers library exporting TF BERT models to ONNX. I had to export the model in a different way.
> 
> @Zhen-hao Can you explain, which different way you exported your model to ONNX, though?

I didn't figure out a way to export it to ONNX. I had to export it as a TF model.

**Comment by sentian** [comment]
@Philipduerholt TF relies on fixed input length. You may want to specify a max_length before converting to ONNX, and pad the infererence sequence to the specified max_length.

Another way is to use ONNX-PyTorch rather than ONNX-TF. Based on my understanding, PyTorch allows dynamic input length, so you shouldn't have to specify fixed input length.
