### ISSUE TITLE
Quantized tiny_yolov4 model ,inference speed from 47ms to 83ms.What should I do speed up inference speed? 

### ISSUE THREAD

**Issue by NeekHua** [microsoft/onnxruntime#4796]
**Describe the bug**
If inscribe

**Urgency**
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 Professional edition
- ONNX Runtime installed from (source or binary):source
- ONNX Runtime version:1.4.0
- Python version:3.6.5

**Comment by NeekHua** [comment]
following is quantized code:
 import onnx
from quantize import quantize,QuantizationMode
# import numpy as np
model=onnx.load("E:\\pycharm_project\\test_onnx\\flag_detect_op.onnx")
quantized_model=quantize(model,quantization_mode=QuantizationMode.IntegerOps)
onnx.save(quantized_model,"E:\\pycharm_project\\test_onnx\\test_will_delete.onnx")

**Comment by NeekHua** [comment]
following is quantization code
import onnx
from quantize import quantize,QuantizationMode
model=onnx.load("E:\\pycharm_project\\test_onnx\\flag_detect_op.onnx")
quantized_model=quantize(model,quantization_mode=QuantizationMode.IntegerOps)
onnx.save(quantized_model,"E:\\pycharm_project\\test_onnx\\test_will_delete.onnx")

**Comment by hariharans29** [comment]
CC: @yufenglee - can you please take a look ?

**Comment by tsaizhenling** [comment]
we are experiencing similar issues with a different model.
we quantized https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/models/onnx/version-RFB-640.onnx
to yeild [quantized_model6.zip](https://github.com/microsoft/onnxruntime/files/5087752/quantized_model6.zip)

tested on the cpu on windows 10, in our production application, the quantized model has unstable inference speed, and is between 5x~7x slower than the full precision model

please let me know if a different issue is preferred

**Comment by yufenglee** [comment]
We are improving the performance of CNN models. It is expected to get a performance improvement in our next release 1.5.

**Comment by NeekHua** [comment]
Ok，thanks your reply.
