### ISSUE TITLE
add new op but register test failed

### ISSUE THREAD

**Issue by freedenS** [microsoft/onnxruntime#4798]
**Describe the bug**
I have added a new op following this way(Contributing the op to ONNXRuntime).
modify: 
onnxruntime/contrib_ops/cpu/newop.h 
onnxruntime/contrib_ops/cpu/newop.cc
onnxruntime/contrib_ops/cpu/cpu_contrib_kernels.cc class(newop) BuildKernelCreateInfo(newop) same to SampleOp
onnxruntime/core/graph/contrib_ops/contrib_defs.cc ONNX_CONTRIB_OPERATOR_SCHEMA(newop) same to SampleOp
test with following code in onnxruntime/test/contrib_ops/op_reg_test.cc:
```
auto op1 = OpSchemaRegistry::Schema("newop");
EXPECT_TRUE(nullptr != op);
```
but failed.

**Urgency**
None.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version:
- Python version:
- Visual Studio version (if applicable): 2017
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:

**Comment by freedenS** [comment]
@hariharans29

**Comment by hariharans29** [comment]
Are you trying to implement a contrib op in ORT ?

Please use this PR as a sample if so - https://github.com/microsoft/onnxruntime/pull/2332

**Comment by freedenS** [comment]
Thank you for your reply!
Yes, i want to implement a contrib op in ORT.
i have learned some similar PRs, and modified corresponding files, but still got not register function/op.
i will take more tries.

**Comment by freedenS** [comment]
I tried to test SampleOp with the above code, but it also failed!

**Comment by freedenS** [comment]
I have solved this problem. Thanks!
