### ISSUE TITLE
How to use yolov5 onnx file in C#

### ISSUE THREAD

**Issue by ricklina90** [microsoft/onnxruntime#4801]
Hi,
     According to this sample https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data. I convert training data(.pt) to ONNX file.
(https://github.com/ultralytics/yolov5/issues/412)
If I need to use C# and onnxruntime, is there any sample like https://github.com/microsoft/onnxruntime/tree/master/csharp/sample/Microsoft.ML.OnnxRuntime.FasterRcnnSample I can reference to? THX.

**Comment by hariharans29** [comment]
Well, you can use the same sample for reference isn't it ? That should give you an idea about using C# APIs and ONNXRuntime. We don't have a sample for every model.  But, I would guess it will be very easy to adapt the FasterRCNN sample for the Yolov5 use-case (both are real time object detection models).

**Comment by hariharans29** [comment]
Please re-open if you have follow-up questions.
