### ISSUE TITLE
A question on DispatchOnTensorType()

### ISSUE THREAD

**Issue by antkillerfarm** [microsoft/onnxruntime#4802]
In include/onnxruntime/core/framework/data_types_internal.h: Line 114:

```
case ONNX_NAMESPACE::TensorProto_DataType_UINT8:              \
      function<uint32_t>(__VA_ARGS__);                            \
      break;
```
Why map `ONNX_NAMESPACE::TensorProto_DataType_UINT8` to `uint32_t`?

**Comment by hariharans29** [comment]
Thanks. That looks like a bug to me. Sent out a PR.
