### ISSUE TITLE
onnxruntime-gpu ImportError: cannot import name 'get_all_providers'

### ISSUE THREAD

**Issue by lex3001** [microsoft/onnxruntime#4806]
**Describe the bug**
I am trying to test onnxruntime-gpu.
On "import onnxruntime as rt" I get an error:
(onnx-gpu) C:\Users\l\OneDrive\AF\mut1ny\face_segmentaion_onnx>python test.py
C:\Users\l\.conda\envs\onnx-gpu\lib\site-packages\onnxruntime\capi\_pybind_state.py:14: UserWarning: Cannot load onnxruntime.capi. Error: 'DLL load failed: The specified module could not be found.'.
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'.".format(str(e)))
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    import onnxruntime as rt
  File "C:\Users\l\.conda\envs\onnx-gpu\lib\site-packages\onnxruntime\__init__.py", line 13, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
ImportError: cannot import name 'get_all_providers'

**Urgency**
none

**System information**
- Wndows 10
- pip install onnxruntime-gpu
- ONNX Runtime version: 1.4.0
- Python version: 3.6.10 (Anaconda)
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 10.1
- GPU model and memory: Nvidia GeForce GTX 1660 Ti

**To Reproduce**
import onnxruntime as rt

**Expected behavior**
n/a
load onnx runtime for GPU

**Screenshots**
n/a

**Additional context**
I have successfully used onnxruntime (not "-gpu") so maybe this is something related to my Nvidia drivers and CUDA setup? The error message is hard to understand. My Nvidia system info says NVCUDA64.DLL is an 11.0.208 driver. Maybe I need CUDA 11? Any ideas on how to get this working would be great. The inference I want to use takes about 4 seconds with CPU, should be much faster with GPU.

**Comment by hariharans29** [comment]
Yes, please make sure the CUDA and CuDNN dlls are installed and findable via system PATH.

Various dupes of the same issue - 
https://github.com/microsoft/onnxruntime/issues/3614
https://github.com/microsoft/onnxruntime/issues/4196

This probably needs to go into FAQ.md

**Comment by lex3001** [comment]
Hi thanks for replying.
By "CUDA and CuDNN dlls" do you mean, for CUDA, "cudart64_101.dll"?
Is CuDNN a separate install? What is the name of it's DLL?
I found "cudart64_101.dll" in "C:\Program Files\NVIDIA Corporation\NvStreamSrv" and added that to the PATH, but that didn't change the outcome.

**Comment by hariharans29** [comment]
I ran dumpbin.exe on the onnxruntime.dll from the onnxruntime gpu nuget package. To import the python gpu module, you would need the same dependencies to be installed and findable by system path:

![image](https://user-images.githubusercontent.com/9969784/90299470-0cfc5b80-de4b-11ea-9897-18eb3b50633f.png)

**Comment by hariharans29** [comment]
Sorry - I forgot to add - given that you were able to run onnxruntime (cpu) successfully - I wouldn't worry about anything non-CUDA in the list above (you already have it).  So, please make sure cu*.dll listed from above is in your system path.

**Comment by hariharans29** [comment]
Please re-open if you are having issues after the dependencies are installed.
