### ISSUE TITLE
CUDAExecutionProvider

### ISSUE THREAD

**Issue by TheBigTicket02** [microsoft/onnxruntime#4809]
**Describe the bug**
Hi!. I’ve just started using onnxruntime for DistilBert optimization on GPU. And from `ort.get_available_providers()` only `['CPUExecutionProvider']`.
**Urgency**
Medium

**System information**
- Kaggle and Colab Notebooks

**To Reproduce**
I used this command `!pip install onnxruntime-gpu onnxruntime onnxruntime-tools`, and tried this `os.environ["CUDA_VISIBLE_DEVICES"]="0"`

**Expected behavior**
Can somebody explain how to get 'CUDAExecutionProvider'?

Thanks.

**Comment by TheBigTicket02** [comment]
I found my mistake.

**Comment by dongzhen123** [comment]
> I found my mistake.

How to handle it?
