### ISSUE TITLE
replace onnx model output with all conv node input/output name can not infer once to get all results shape

### ISSUE THREAD

**Issue by pecanjk** [microsoft/onnxruntime#4819]
replace onnx model output with all conv node input/output name can not infer once to get all results shape.

Using resnet50.onnx example. I want to infer to get all the input and output of conv node shape. By replacing the original onnx model output name with all the conv node input/output name, I cannot infer once to get all results

gives Error message like this

anaconda3/lib/python3.7/site-packages/onnxruntime/capi/session.py”, line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (Conv_12) Op (Conv) [ShapeInferenceError] Input tensor must have atleast 2 dimensions

But it works if replace original output name with only one name, and do it one by one. This costs time.

Very interesting and hope if there is another convient way to obtain every conv node input/output feature shape

**Comment by skaarthik** [comment]
@pecanjk can you share your code? It will help us understand the problem better.

**Comment by pecanjk** [comment]
> @pecanjk can you share your code? It will help us understand the problem better.

model=onnx.load('resnet50.onnx')
1. get onnx model input dict.  `input_feed`

2. get all the conv node input/output name which we want to know the shape `conv_input_output_names`
for node_idx in conv_node_idx:
        conv_node=model.graph.node[node_idx]
        attrs = parse_attr(conv_node.attribute)
        for input_name in conv_node.input:
            if input_name not in initializers:
                if node_idx>0: #exclude first node input
                    conv_input_names.append(input_name)  # model input
   
        for output_name in conv_node.output:
            conv_output_names.append(output_name)

conv_input_output_names=list(set(conv_input_names)|set(conv_output_names))

3.  replace original onnx model output with our `conv_input_output_names` and `input_feed`
new_outputs=conv_input_output_names
DUMMY_TENSOR_TYPE = onnx.TensorProto.FLOAT
    while (len(model.graph.output)):
        model.graph.output.pop()
    for output_name in new_outputs:
        output_value_info = onnx.helper.make_tensor_value_info(
            output_name, DUMMY_TENSOR_TYPE, '')
        model.graph.output.extend([output_value_info])

onnx.save(model,'new_model.onnx')

4. obtain `conv_input_output_names` results
sess = onnxruntime.InferenceSession('new_model.onnx')
output_names = [output.name for output in sess.get_outputs()]
print('output_names ',output_names)
output = sess.run(output_names, input_feed)

**Error happened here 4. sess.run()**

But if we just use only one name in new_outputs then save onnx model, everything goes correct. But one by by to obtain output cost time.

**Comment by jywu-msft** [comment]
you may find https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#DebugNodeInputsOutputs useful
this pending [PR#4921](https://github.com/microsoft/onnxruntime/pull/4921) might also be useful.

**Comment by pecanjk** [comment]
> you may find https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#DebugNodeInputsOutputs useful
> this pending [PR#4921](https://github.com/microsoft/onnxruntime/pull/4921) might also be useful.

so, it will support after PR#4921 merged?
