### ISSUE TITLE
Ort::Env cannot be static

### ISSUE THREAD

**Issue by mbelloc** [microsoft/onnxruntime#4820]
**Describe the bug**
It seems Ort::Env cannot be a static member. I want to parallelize inference using a class that handles a static Ort::Env * and non static Ort::Session. When I define the static member like so in the .cpp file:
`Ort::Env* unique_env = new Ort::Env(ORT_LOGGING_LEVEL_WARNING, "onnx_unique_env")`
the compilation is ok but when I run my program it crashes instantly because the .dll could not be open (class that handles Ort::Env and session is exported and used by multiple other libraries).

As a workaround I just initialize the Ort::Env to nullptr in the .cpp file (so it is not constructed) and the class constructor check if the static variable is nullptr in order to initialize it only once. It seems to delay enough the construction of the Ort::Env and solve the dll problem.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.4.0
- Python version:
- Visual Studio version (if applicable): VS 2017
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**

```
// .h

static Ort::Env* _env;
```
```
// .cpp

// outside of any class method
Ort::Env* MyClass::_env = new Ort::Env(ORT_LOGGING_LEVEL_WARNING, "onnx_unique_env")

// Then in some class method
this->_session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
this->_session = new Ort::Session(*OnnxRuntime::_env, "/some/model.onnx", this->_session_options);
```

**Expected behavior**
Ort::Env can be created at the very beginning of the program and thus can be used as a static variable without manually delaying its construction.

**Comment by snnn** [comment]
Yes, it's a known issue.

**Comment by snnn** [comment]
Would #4536 be helpful for you?

**Comment by mbelloc** [comment]
> Would #4536 be helpful for you?

Yes, thanks
