### ISSUE TITLE
"Segmentation fault" (core dumped) 

### ISSUE THREAD

**Issue by zhuxiaoxuhit** [microsoft/onnxruntime#4821]
**Describe the bug**
I convert pb file to onnx , it has two inputs and one output. Then I successful compiled cpp file. 
So far everything is normal，no error or warning. When i execute the out file(using gnu compiler),got this message.
///////////////////////////////////////////
Using Onnxruntime C++ API
Number of inputs = 2
Input 0 : name=text_len:0
Input 0 : type=6
Input 0 : num_dims=1
Input 0 : dim 0=1
Input 1 : name=text:0
Input 1 : type=6
Input 1 : num_dims=2
Input 1 : dim 0=1
Input 1 : dim 1=66
Segmentation fault (core dumped)
//////////////////////////////////////////
using gdb to locate this error,got this:
![image](https://user-images.githubusercontent.com/32813150/90401570-b738e500-e0d0-11ea-95db-aed768dce45e.png)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux release 7.5.1804
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master
- Python version: 3.6

**To Reproduce**
```c++
#include <assert.h>
#include <vector>
#include "onnxruntime_cxx_api.h"

int main(int argc, char* argv[]) { Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test"); 
  Ort::SessionOptions session_options;
  session_options.SetIntraOpNumThreads(1); 
  session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED); const char* model_path = "model.onnx"; printf("Using Onnxruntime C++ API\n");
  Ort::Session session(env, model_path, session_options);
  
  Ort::AllocatorWithDefaultOptions allocator;

  // print model input layer (node names, types, shape etc.) Ort::AllocatorWithDefaultOptions allocator; 
  // print number of model input nodes
  size_t num_input_nodes = session.GetInputCount();
  std::vector<const char*> input_node_names(num_input_nodes);
  std::vector<std::vector<int64_t> > input_node_dims;

  printf("Number of inputs = %zu\n", num_input_nodes);

  // iterate over all input nodes
  for (int i = 0; i < num_input_nodes; i++) {
    // print input node names
    char* input_name = session.GetInputName(i, allocator);
    printf("Input %d : name=%s\n", i, input_name);
    input_node_names[i] = input_name;

    // print input node types
    Ort::TypeInfo type_info = session.GetInputTypeInfo(i);
    auto tensor_info = type_info.GetTensorTypeAndShapeInfo();

    ONNXTensorElementDataType type = tensor_info.GetElementType();
    printf("Input %d : type=%d\n", i, type);

    // print input shapes/dims
    input_node_dims.push_back(tensor_info.GetShape());
    printf("Input %d : num_dims=%zu\n", i, input_node_dims.size());
    for (int j = 0; j < input_node_dims[i].size(); j++)
    ┊ printf("Input %d : dim %d=%jd\n", i, j, input_node_dims[i][j]);
  }
  
  size_t input_tensor_size_0 = 1;  
  size_t input_tensor_size_1 = 66; 
  std::vector<int64_t> input_tensor_values_0 = {66};
  std::vector<int64_t> input_tensor_values_1 = {{3,   89,  75,  11,   4,  74,  62,  12,   7,  94,  82,  12,   4,  66,  62, 13,  5, 115,  60, 13,  4,  98,  82,  10,   5,  87, 78,  12,   4, 98,  92, 11, 4,\ 
                                            ┊   ┊66,  67,  14,   6, 114,  75,  13,   4, 115,  99,  13,   5,  97,  92,  13,  4, 93,  79,  13,  4, 85,  75,  10,   5,  73,  92, 13,   4,  88, 59,  12,  3, 1}};
  std::vector<const char*> output_node_names = {"output_minmax:0"};

  // create input tensor object from data values
  auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
  Ort::Value input_tensor_0 = Ort::Value::CreateTensor<int64_t>(memory_info, input_tensor_values_0.data(), input_tensor_size_0, input_node_dims[0].data(), 1); 
  Ort::Value input_tensor_1 = Ort::Value::CreateTensor<int64_t>(memory_info, input_tensor_values_1.data(), input_tensor_size_1, input_node_dims[1].data(), 2); 
  Ort::Value* input_tensors[input_node_names.size()];
  input_tensors[0] = &input_tensor_0; 
  input_tensors[1] = &input_tensor_1; 

  auto output_tensors = session.Run(Ort::RunOptions{nullptr}, input_node_names.data(), (const Ort::Value*)input_tensors, 2, output_node_names.data(), 1);
  return 0;
}

```

**Expected behavior**
NO ERROR.

**Comment by zhuxiaoxuhit** [comment]
gdb message:
```c++
1066	    auto expected_type = iter->second.ml_data_type;
(gdb) s
1067	    auto& input_ml_value = feeds.at(i);
(gdb) s
at (__n=0, this=0x7fffffffcd10) at /data/zhuxiaoxu/trt/onnxruntime/onnxruntime/core/session/inference_session.cc:1067
1067	    auto& input_ml_value = feeds.at(i);
(gdb) s
_M_range_check (__n=0, this=0x7fffffffcd10) at /data/zhuxiaoxu/trt/onnxruntime/onnxruntime/core/session/inference_session.cc:1067
1067	    auto& input_ml_value = feeds.at(i);
(gdb) s
size (this=<optimized out>, this=<optimized out>) at /usr/include/c++/4.8.2/bits/stl_vector.h:646
646	      { return size_type(this->_M_impl._M_finish - this->_M_impl._M_start); }
(gdb) s
_M_range_check (__n=0, this=0x7fffffffcd10) at /usr/include/c++/4.8.2/bits/stl_vector.h:793
793		if (__n >= this->size())
(gdb) s
at (__n=0, this=0x7fffffffcd10) at /usr/include/c++/4.8.2/bits/stl_vector.h:831
831		return (*this)[__n];
(gdb) s
operator[] (this=<optimized out>, __n=0) at /usr/include/c++/4.8.2/bits/stl_vector.h:786
786	      { return *(this->_M_impl._M_start + __n); }
(gdb) s
onnxruntime::InferenceSession::ValidateInputs (this=this@entry=0x7c4020, feed_names=std::vector of length 2, capacity 2 = {...}, feeds=std::vector of length 2, capacity 2 = {...})
    at /data/zhuxiaoxu/trt/onnxruntime/onnxruntime/core/session/inference_session.cc:1067
1067	    auto& input_ml_value = feeds.at(i);
(gdb) s
1068	    if (input_ml_value.IsTensor()) {
(gdb) s
IsTensor (this=0x961c80) at /data/zhuxiaoxu/trt/onnxruntime/include/onnxruntime/core/framework/ml_value.h:52
52	    return (type_ != nullptr && type_->IsTensorType());

```

**Comment by yuslepukhin** [comment]
I think the need for casting the input argument gives away the problem. You are not feeding the correct argument. Try this:

`Ort::Value input_tensors[] = {input_tensor_0, input_tensor_1};`

`auto output_tensors = session.Run(Ort::RunOptions{nullptr}, input_node_names.data(), input_tensors,  2,  output_node_names.data(), 1);`

**Comment by RyanUnderhill** [comment]
I think your problem is this line:
`auto output_tensors = session.Run(Ort::RunOptions{nullptr}, input_node_names.data(), (const Ort::Value*)input_tensors, 2, output_node_names.data(), 1);
`

You're casting an array of pointers into an array of values (the (const Ort::Value*) part). Try this instead:

`Ort::Value input_tensor_0 = Ort::Value::CreateTensor<int64_t>(memory_info, input_tensor_values_0.data(), input_tensor_size_0, input_node_dims[0].data(), 1);
Ort::Value input_tensor_1 = Ort::Value::CreateTensor<int64_t>(memory_info, input_tensor_values_1.data(), input_tensor_size_1, input_node_dims[1].data(), 2);
Ort::Value input_tensors[2] = {std::move(input_tensor_0), std::move(input_tensor_1)};

auto output_tensors = session.Run(Ort::RunOptions{nullptr}, input_node_names.data(), input_tensors, 2, output_node_names.data(), 1);
`

(I didn't compile it, so it might not be 100% correct, but it should explain the problem)

**Comment by zhuxiaoxuhit** [comment]
> I think the need for casting the input argument gives away the problem. You are not feeding the correct argument. Try this:
> 
> `Ort::Value input_tensors[] = {input_tensor_0, input_tensor_1};`
> 
> `auto output_tensors = session.Run(Ort::RunOptions{nullptr}, input_node_names.data(), input_tensors, 2, output_node_names.data(), 1);`

Hi, @yuslepukhin ,Got error .....

```c++
 In function ‘int main(int, char**)’:
error: use of deleted function ‘Ort::Value::Value(const Ort::Value&)’
Ort::Value input_tensors[] = {input_tensor_0, input_tensor_1}; 
                                                               ^
```

**Comment by zhuxiaoxuhit** [comment]
> I think the need for casting the input argument gives away the problem. You are not feeding the correct argument. Try this:
> 
> `Ort::Value input_tensors[] = {input_tensor_0, input_tensor_1};`
> 
> `auto output_tensors = session.Run(Ort::RunOptions{nullptr}, input_node_names.data(), input_tensors, 2, output_node_names.data(), 1);`

Hi, @RyanUnderhill , thanks for ur reply~
I changed codes and got this error:
```c++
Using Onnxruntime C++ API
Number of inputs = 2
Input 0 : name=text_len:0
Input 0 : type=6
Input 0 : num_dims=1
Input 0 : dim 0=1
Input 1 : name=text:0
Input 1 : type=6
Input 1 : num_dims=2
Input 1 : dim 0=1
Input 1 : dim 1=66
terminate called after throwing an instance of 'Ort::Exception'
  what():  Unexpected input data type. Actual: (N11onnxruntime17PrimitiveDataTypeIlEE) , expected: (N11onnxruntime17PrimitiveDataTypeIiEE)
Aborted (core dumped)
```

**Comment by zhuxiaoxuhit** [comment]
That means need to give int type, not long int?

**Comment by zhuxiaoxuhit** [comment]
OK, I got it. Thanks @RyanUnderhill  @yuslepukhin . Now close issue.
