### ISSUE TITLE
Qunatization and calibration end-to-end example does not work

### ISSUE THREAD

**Issue by mikecaraman** [microsoft/onnxruntime#4824]
**Describe the bug**
Quantization and calibration end-to-end example script does not work

#~/sources/onnxruntime-arm-130+/onnxruntime/python/tools/quantization/E2E_example_model$ python3 e2e_user_example.py

Traceback (most recent call last):
  File "e2e_user_example.py", line 83, in <module>
    main()
  File "e2e_user_example.py", line 73, in main
    quantization_params_dict = calibrate(model_path,dr)
  File "/home/sources/onnxruntime-arm-130+/onnxruntime/python/tools/quantization/calibrate.py", line 246, in calibrate
    dict_for_quantization = calibrater.get_intermediate_outputs()
  File "/home/sources/onnxruntime-arm-130+/onnxruntime/python/tools/quantization/calibrate.py", line 152, in get_intermediate_outputs
    ]) for i in range(0, len(added_node_output_names), 2)
  File "/home/sources/onnxruntime-arm-130+/onnxruntime/python/tools/quantization/calibrate.py", line 152, in <listcomp>
    ]) for i in range(0, len(added_node_output_names), 2)
KeyError: 'resnet_v1_50/block3/unit_3/bottleneck_v1/Relu:0_ReduceMax'

**Urgency**
Quantization functionality

**System information**
- Linux Ubuntu 16.04
- sources
- master (1.3.0+)
- Python version: 3

**To Reproduce**
- See bug description

**Expected behavior**
Generate quantized model with QLinearConv operators for ResNet50_v1

**Comment by YUNQIUGUO** [comment]
@mikecaraman Hi, I tested the e2e example on my end using ResNet50_v1.onnx under ./E2E_example_model/resnet50_v1.onnx. I didn't find the KeyError issue. May I ask for further details?

Also, are you using the most up-to-date calibrate.py script?

Thanks!

**Comment by mikecaraman** [comment]
I am using master branch tip with the improvements from July. I am also able to reproduce the issue with calibrate.py script directly.
The input model is the one provided in the E2E_example_model. Can the issue be caused by the calibration data set?
I am using python 3.5.2 on a x86_64 system with Ubuntu 16.04.

**Comment by YUNQIUGUO** [comment]
> I am using master branch tip with the improvements from July. I am also able to reproduce the issue with calibrate.py script directly.
> The input model is the one provided in the E2E_example_model. Can the issue be caused by the calibration data set?
> I am using python 3.5.2 on a x86_64 system with Ubuntu 16.04.

Okay, I see. Thanks for sharing. Btw, what calibration test data set are you using?
