### ISSUE TITLE
About hyperthreading and openmp on the CPU

### ISSUE THREAD

**Issue by Peppa-cs** [microsoft/onnxruntime#4869]
Hi. I found If you use OpenMP on the CPU, using hyperthreading can hardly bring any improvement. I test a simple vgg16 model on the CPU. The following is a comparison of my experiment.

1. using a single thread, latency is 10.37s.
2. using 48 threads with hyperthreading, latency is 0.47s.
3. using 24 threads without hyperthreading, latency is 0.53s.

It seems that if I use 48 threads with hyperthreading, it only brings 22x improvement. The 22x improvement is half of the num of threads almost. And if I use 24 threads without hyperthreading, it brings 19x improvement. The 19x improvement is not much different from the num of threads.

**System information**
- OS Platform and Distribution  Linux Ubuntu 16.04:
- ONNX Runtime installed from binary
- ONNX Runtime version:1.4.0
- Python version: 3.6.5
- CPU (i have break hyperthreading):
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-27
Off-line CPU(s) list:  28-55
Thread(s) per core:    1
Core(s) per socket:    14
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2683 v3 @ 2.00GHz
Stepping:              2
CPU MHz:               1200.202
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4001.81
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              35840K
NUMA node0 CPU(s):     0-13
NUMA node1 CPU(s):     14-27

**To Reproduce**
use_openmp = True/Flase
if use_openmp:
    os.environ["OMP_NUM_THREADS"] = str(nthreads)
else:
    os.environ["OMP_NUM_THREADS"] = '1'

import onnxruntime
session = onnxruntime.InferenceSession(inputfile)
session.set_providers(['CPUExecutionProvider'])
input_name = session.get_inputs()[0].name  

sessionOptions = onnxruntime.SessionOptions()
if use_openmp == False:
    sessionOptions.intra_op_num_threads = 1
    sessionOptions.inter_op_num_threads = 1
    sessionOptions.execution_mode = onnxruntime.ExecutionMode.ORT_SEQUENTIAL

When use_openmp is True, I use multi-threads by setting "OMP_NUM_THREADS". And a single thread is set by "OMP_NUM_THREADS" =1 and intra_op_num_threads/inter_op_num_threads  =1.

**Comment by kzuiderveld** [comment]
The true performance bottleneck might have become memory bandwidth.

**Comment by snnn** [comment]
It's true.  I observed the same conclusion when I benchmark eigen's matrix multiplication code. It's not onnxruntime specific. So, when you use openmp, please  set the OMP_NUM_THREADS to the number of logical cores, not physical cores. It will give you the best performance.

**Comment by Peppa-cs** [comment]
Thanks! Got it!

**Comment by snnn** [comment]
Probably it's too early to say that. 

I just ran a bunch of model tests on an Azure Standard F16s_v2 (16 vcpus, 32 GiB memory) Windows 2019 VM. and for all the models I've tested, setting OMP_NUM_THREADS to half of the logical cores is significantly better than full cores. 

However, it could be OS related. I'm re-running the same tests on Linux.

**Comment by tianleiwu** [comment]
A general rule is to compare multiple settings of  OMP_NUM_THREADS to find the best one for your applications. Typical values are the following:
- #physical cores
- #logical cores
- when number of logical cores >= 16, also try 16 (due to some limitation in MLAS)
- when it is VM with hyper threading, also try  #vcpus/2 - 1  (in case there is extra overhead in VM).

If you do not have chance to do such comparison, recommended setting (might not be best) for OMP_NUM_THREADS could be `min(16, number_of_physical_cores)`
