### ISSUE TITLE
Performance between onnxruntime vs tensorflow serving.

### ISSUE THREAD

**Issue by githubutilities** [microsoft/onnxruntime#4893]
I recently did an experiment to convert pytorch version bert-base model to ONNX for serving purpose and convert tensorflow version bert-base model to Tensorflow serving. And I compare two models using C++ inferences, I found that ONNXRuntime performance is 50% percent slower than Tensorflow Serving and comsume more gpu memory than TFServing.
Is it a bug or my onnxruntime setup is wrong?

**Comment by tianleiwu** [comment]
@githubutilities, 

Could you try our benchmark on bert-base-cased to see whether the performance is similar to your results:
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/run_benchmark.sh
