### ISSUE TITLE
Unspecified error by using DirectXHighPerformance with Microsoft.AI.MachineLearning package

### ISSUE THREAD

**Issue by piphagor18** [microsoft/onnxruntime#4897]
**Describe the bug**
I have two onnx model in my UWP project (C#). The first model is a keras-based opset 7 custom model. This model works fine with CPU and GPU. The second model is an exported pytorch Yolo tiny v3 opset 11 model. The model works fine with CPU, but throws:

 System.Runtime.InteropServices.COMException: 'Unspecified error

Exception during initialization: D:\5\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\FusedGraphKernel.cpp(285)\onnxruntime.dll!00007FFDF0ECF503: (caller: 00007FFDF0ECD63A) Exception(1) tid(10480) 80070057 The parameter is incorrect.'

with following code:
learningModel.session = new LearningModelSession(learningModel.model, new LearningModelDevice(LearningModelDeviceKind.DirectXHighPerformance));

**Urgency**
This blocks my application performance improving.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Microsoft Windows 10 Pro, 10.0.18363
- ONNX Runtime installed from (source or binary): Microsoft.AI.MachineLearning Nuget package
- ONNX Runtime version: 1.4.0
- Python version: 3.6
- Visual Studio version (if applicable): Microsoft Visual Studio Community 2019 Version 16.7.0
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.2
- GPU model and memory: NVIDIA GeForce RTX 2080, 8Gb

**To Reproduce**
Run this code: var session = new LearningModelSession(learningModel.model, new LearningModelDevice(LearningModelDeviceKind.DirectXHighPerformance));

**Expected behavior**
The model loaded successfully.

**Comment by wchao1115** [comment]
@piphagor18 Is it possible to share the model that repros this problem or if this is publicly available point us to it?

**Comment by piphagor18** [comment]
https://drive.google.com/file/d/1TI1Tq3yVYoZLyHSzQsD1Xc-pqIVxGcol/view?usp=sharing

@wchao1115 This is the model after first 1000 DarkNet iterations.

**Comment by wchao1115** [comment]
Thanks @piphagor18, we'll take a look at it and let you know.

**Comment by nrandell** [comment]
I've just seen the same in C# and I think it's to do with using the wrong DirectML.dll. I had to explicitly load the DirectML.dll included in the C# package, rather than allow it to load the one included in windows.
