### ISSUE TITLE
Optimizer changes dynamic shape to constant

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#4898]
**Describe the bug**
1. We rely heavily on tensors with dynamic shape.
2. We rely on `sess_options.optimized_model_filepath` and `ORT_ENABLE_BASIC` for basic optimizations, that would basically eliminate unused initializers (because onnx optimizer crashes)

Before optimization

![image](https://user-images.githubusercontent.com/873905/91094541-cdcec700-e60f-11ea-81c2-0c9783fdfb8d.png)

After optimization

![image](https://user-images.githubusercontent.com/873905/91094986-72510900-e610-11ea-9aba-1779607484b3.png)

**Urgency**
We have a workaround that avoids this optimizer mistake, but is an ugly hack. Plus, I am not sure if other places in the model might have the same issue.
First we saw issue #4853 related to the exported model

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.4
- Python version: 3.6

**To Reproduce**

- Attach the ONNX model to the issue (where applicable) to expedite investigation.
[test.zip](https://github.com/microsoft/onnxruntime/files/5120158/test.zip)

```python
import onnxruntime as rt
sess_options = rt.SessionOptions()
sess_options.graph_optimization_level = rt.GraphOptimizationLevel.ORT_ENABLE_BASIC
sess_options.optimized_model_filepath = "test_opt.onnx"

sess = rt.InferenceSession("test.onnx", sess_options)
```

outputs this onnx file:
[test_opt.zip](https://github.com/microsoft/onnxruntime/files/5120198/test_opt.zip)

**Expected behavior**
Optimizer should not change dynamic shapes to constants.

**Additional context**
Initially we suspected `torch.full_like` is not generating `ConstantOfShape` and created [this issue](https://github.com/pytorch/pytorch/issues/43283) for exporter.

Here is the code that generates the onnx file (PyTorch 1.6). It is a little piece of code that is part of a bigger model.

```python
import torch
import onnxruntime as rt

def _align_box(im_h, im_w, bbs,
               enlargement_factor, target_size, min_len, align='SHORTEST'):
    zero = torch.as_tensor(0.0).float().to(bbs.device)

    # enlarge the bounding box
    w = (bbs[:, 2] * enlargement_factor).ceil()
    h = (bbs[:, 3] * enlargement_factor).ceil()

    # CXCYWH to XYWH
    input_x = (bbs[:, 0] - w / 2).floor()
    cond = input_x < 0
    idx = torch.nonzero(cond).view(-1)
    # TODO: use scatter_add when fixed: https://github.com/pytorch/pytorch/issues/26472
    w = torch.scatter(w, 0, idx, w[idx] + input_x[idx])  # w[idx] += input_x[idx]
    input_x = torch.where(cond, zero, input_x)  # input_x[idx] = 0
    input_y = (bbs[:, 1] - h / 2).floor()
    cond = input_y < 0
    idx = torch.nonzero(cond).view(-1)
    # TODO: use scatter_add when fixed: https://github.com/pytorch/pytorch/issues/26472
    h = torch.scatter(h, 0, idx, h[idx] + input_y[idx])  # h[idx] += input_y[idx]
    input_y = torch.where(cond, zero, input_y)  # input_y[idx] = 0

    w = w.clamp(min=min_len)  # w[w < min_len] = min_len
    h = h.clamp(min=min_len)  # h[h < min_len] = min_len

    input_width = im_w - input_x
    input_width = torch.where(w < input_width, w, input_width)  # input_width[idx=w < input_width] = w[idx]
    input_height = im_h - input_y
    input_height = torch.where(h < input_height, h, input_height)  # input_height[idx=h < input_height] = h[idx]
    del w, h

    # If too far to the right shift the coordinates
    idx = input_width < min_len
    input_width = torch.where(idx, min_len, input_width)  # input_width[idx] = min_len
    input_x = torch.where(idx, im_w - min_len, input_x)  # input_x[idx] = im_w - min_len
    idx = input_height < min_len
    input_height = torch.where(idx, min_len, input_height)  # input_height[idx] = min_len
    input_y = torch.where(idx, im_h - min_len, input_y)  # input_y[idx] = im_h - min_len

    target_width = torch.full_like(input_width, target_size)
    target_height = torch.full_like(input_height, target_size)

    # align with constraint
    if align == 'SHORTEST':
        # Avoid `<=` because ONNX will export that as `Not` and `>` then we need another `Not`
        #  instead, first compute `>` and use `~` to be exported as `Not`
        nidx = input_width > input_height
        idx = ~nidx  # this requires patch_logical_not_opset9 until bitwise_not for bool is in PyTorch
        idx = torch.nonzero(idx).view(-1)
        target_height = torch.scatter(target_height, 0, idx, target_size * input_height[idx] / input_width[idx])

        idx = torch.nonzero(nidx).view(-1)
        target_width = torch.scatter(target_width, 0, idx, target_size * input_width[idx] / input_height[idx])
    elif align == 'LONGEST':
        idx = input_width > input_height
        nidx = ~idx  # this requires patch_logical_not_opset9 until bitwise_not for bool is in PyTorch
        idx = torch.nonzero(idx).view(-1)
        target_height = torch.scatter(target_height, 0, idx, target_size * input_height[idx] / input_width[idx])

        idx = torch.nonzero(nidx).view(-1)
        target_width = torch.scatter(target_width, 0, idx, target_size * input_width[idx] / input_height[idx])
    else:
        assert align == 'BOTH'

    return input_x, input_y, input_width, input_height, target_width, target_height

class Module(torch.nn.Module):
    def forward(self, img, bbs):
        _, _, height, width = img.shape[0], img.shape[1], img.shape[2], img.shape[3]
        # When tracing (for onnx export this is Tensor)
        if not isinstance(height, torch.Tensor):
            height, width = torch.as_tensor(height).to(img.device), torch.as_tensor(width).to(img.device)

        input_x, input_y, input_width, input_height, target_width, target_height = _align_box(
            height.float(), width.float(), bbs, 1.5, 256, torch.as_tensor(3).float()
        )
        return input_x, input_y, input_width, input_height, target_width, target_height

model = Module()
img = torch.empty((1,3,256,512))
bbs = torch.as_tensor([[0, 0, 100, 100], [0, 0, 500, 100]]).float()

targets = ['input_x', 'input_y', 'input_width', 'input_height', 'target_width', 'target_height']
torch.onnx.export(model, (img, bbs), 'test.onnx',
                  verbose=True,
                  input_names=['img', 'bbs'],
                  output_names=targets,
                  opset_version=11,
                  dynamic_axes={'img': {2: 'h', 3: 'w'}, 'bbs': {0: 'rpn'}})

```

**Comment by ytaous** [comment]
Hi, thanks for reporting the issue. To clarify, are you referring to  https://github.com/pytorch/pytorch/issues/43283, where the input of ScatterElems becomes initializer after optimization, and this is incorrect and unexpected, correct?

**Comment by dashesy** [comment]
Correct. The input should reman a "ConstantOfShape" after optimization. Even though it is a constant, its shape is not constant.

**Comment by askhade** [comment]
@dashesy : 
You mentioned above :  The input should reman a "ConstantOfShape" after optimization. Even though it is a constant, its shape is not constant.
This is not true the shape of the input is not constant and that is the reason it is constant folded.

More details: 
ConstantOfShape is constant folded because the input to this node which is Shape node is constant folded.
Since the shape of the input is known to this node it satisfies the conditions for constant folding

![image](https://user-images.githubusercontent.com/6475296/91605981-31b20200-e926-11ea-8809-86533d8a779c.png)

As you can see the shape of input_width is known "float32[2]"

This is expected.

Take a look at another shape node in this model Shape_0. Here the shape is not known and therefore it is not constant folded. It exists in the optimized graph too.

![image](https://user-images.githubusercontent.com/6475296/91606269-a08f5b00-e926-11ea-97bd-dcb4e5a061b4.png)

**Comment by dashesy** [comment]
If you look at the code that generates the ONNX, it is not a constant shape. 2 is because of this line

```python
bbs = torch.as_tensor([[0, 0, 100, 100], [0, 0, 500, 100]]).float()
```

and you can see `bbs` has first dimension as dynamic shape.

**Comment by askhade** [comment]
From the model clearly Shape node does not have dynamic shape and this is why it is being constant folded.
It depends on how the Shape node is created (in the script) This seems either like exporter issue or an issue with the scirpt which generates the onnx file

**Comment by dashesy** [comment]
I created the issue on PyTorch. I do not know what is the difference between exporter and "script that generates the onnx file". The script is the one above (the repro).
I close this issue because this looks like not related to ORT issue, thanks
