### ISSUE TITLE
Onnx input size

### ISSUE THREAD

**Issue by AD-HO** [microsoft/onnxruntime#4929]
Hi Everyone,
I would like to know how to unfreeze the input size of an exported Onnx model?
Example: https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html

Super-Resolution is an image-to-image translation, i can’t see how i would consume this model without resizing the input to 224 x 224 , and this mean the input quality will decrease
thank you.

**Comment by snnn** [comment]
No, you can't. For most of the image models, input size is fixed. You have to resize the image first.
