### ISSUE TITLE
Official build for Linux

### ISSUE THREAD

**Issue by atraastrum** [Microsoft/onnxruntime#494]
How can I get official build for Linux? The link in Readme points to Nuget package  manager page?

**Comment by jignparm** [comment]
The Linux dynamic libraries are currently available in the NuGet package. The archive can be unzipped to to extract the files if you need the raw libraries.

https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/0.2.1

**Comment by pranavsharma** [comment]
Next release onward we'll provide tarballs as well so that users don't have to download the dotnet stuff when they want to use onnxruntime on Linux.
