### ISSUE TITLE
Build by source, import onnxruntime, ModuleNotFoundError: No module named 'onnxruntime.capi'

### ISSUE THREAD

**Issue by zhuguiqian** [microsoft/onnxruntime#4956]
**Describe the bug**
When i use source code to build onnxruntime, build OK by the command './build.sh --config RelWithDebInfo --build_shared_lib --parallel', but when import onnxruntime, return error "ModuleNotFoundError: No module named 'onnxruntime.capi'", if any action need to do after building?

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source source 
- ONNX Runtime version: 1.3.0
- Python version: Python 3.6.11
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**
build OK
![image](https://user-images.githubusercontent.com/7693110/91533676-df330e80-e942-11ea-85eb-4d3a5a4321f9.png)
import error
![image](https://user-images.githubusercontent.com/7693110/91533702-ea863a00-e942-11ea-83af-9c07d3e7d560.png)

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by hariharans29** [comment]
Please add —build_wheel to the build arguments and install the *.whl file. Or you can run pip install onnxruntime to consume the latest release.

**Comment by wwbnjsace** [comment]
> Please add —build_wheel to the build arguments and install the *.whl file. Or you can run pip install onnxruntime to consume the latest release.

my build command is "./build.sh --config Release --build_shared_lib --build_wheel --enable_pybind --use_openvino " .in the end ,it dose not generate any *.whl file . why
