### ISSUE TITLE
Add support for sessions to share a global threadpool

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#4962]
**Is your feature request related to a problem? Please describe.**
We have to run 2 sessions, but not in parallel.
Does that mean we may also benefit from [this PR](https://github.com/microsoft/onnxruntime/pull/3177)?

**System information**
- ONNX Runtime version (you are using): 1.4

**Describe the solution you'd like**
Expose the threadpool sharing to C#, so we can test

**Describe alternatives you've considered**
Use C++ code

**Additional context**
The design discussion does not explain the rationale, or exactly how it helps OCR. So we do not know if this also benefits us.
Is it possible to discuss this in open and explain the issue?

**Comment by pranavsharma** [comment]
If you don't intend to run the sessions in parallel, there's no reason to share the threadpool between sessions. The global threadpool feature addresses the case where you would be running multiple sessions in parallel in which case you don't want to create a separate threadpool for each session.

**Comment by dashesy** [comment]
what about concurrent requests? would that benefit from shared threadpool? it is same session called by different threads.
