### ISSUE TITLE
NNAPI on Android gives different output from the one that CPU gives

### ISSUE THREAD

**Issue by s94285** [microsoft/onnxruntime#4993]
**Describe the bug**
I added armv7l into initOsArch and rebuild AAR to fix #4976 
I then test [Ultra-Light-Fast-Generic-Face-Detector-1MB](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/models/onnx/version-RFB-320_simplified.onnx).
NNAPI gives different output on every inference with same input data, while CPU gives same output which should be correct.
The first two column of outputs is the score of the box, which was produced by softmax function.
Despite that output changes every time, the sum of the two columns gives 1.
Thus the output part should be correct imo.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.4.0
- Python version: 3.7.5
- GCC/Compiler version (if compiling from source): 6.5.0

**To Reproduce**
Build AAR using following command
`./build.sh --android --android_sdk_path /home/kevin/Android/Sdk --android_ndk_path /home/kevin/Android/Sdk/ndk/21.2.6472646 --android_abi armeabi-v7a --android_api 28 --use_nnapi --build_java`

My testing app, screenshots and output results
https://github.com/s94285/ONNX-Test/tree/nnapiIncorrectOutput

**Expected behavior**
Same outputs for NNAPI and CPU

**Additional context**
outputs
```
scores            boxes
NNAPI
0.000000 1.000000 -9721483286680020000000000000000.000000 37482082545802430000000000000000.000000 106805191827844450000000000000000.000000 27817414541403927000000000000000.000000
0.000000 1.000000 79688540809186700000000000000000.000000 56770527847676790000000000000000.000000 -56594841911867110000000000000000.000000 -67892248860462540000000000000000.000000
0.000000 1.000000 113178561706193770000000000000000.000000 159783570835960630000000000000000.000000 -76747968988369190000000000000000.000000 -14819046546759074000000000000000.000000
1.000000 0.000000 -28403378468319500000000000000000.000000 -12232165317282937000000000000000.000000 25499437099836310000000000000000.000000 -28504855701617950000000000000000.000000
0.000000 1.000000 -31206425305749290000000000000000.000000 23600514450824994000000000000000.000000 -17805072769468274000000000000000.000000 -43845592425166965000000000000000.000000
1.000000 0.000000 -25969718915072960000000000000000.000000 75570189933571110000000000000000.000000 -31958556086570890000000000000000.000000 -17601597255843116000000000000000.000000
0.941594 0.058406 -154.381699 -307.089142 -783.662109 -490.694550
0.939313 0.060687 -204.694305 -49.444698 -198.451538 -41.679722
0.937129 0.062871 -254.715500 -32.978069 -234.318695 -141.584808
1.000000 0.000000 5852403848125322000000000000000.000000 -12818769974882904000000000000000.000000 9270502576616430000000000000000.000000 -33799733184882496000000000000000.000000
0.000000 1.000000 -7184477500817905000000000000000.000000 17264709524468567000000000000000.000000 -52583389092925130000000000000000.000000 -56310517066203585000000000000000.000000
1.000000 0.000000 -10670045774838796000000000000000.000000 83584434826883360000000000000000.000000 -46172112136575980000000000000000.000000 -9066530194479411000000000000000.000000
0.000000 1.000000 -9721483286680020000000000000000.000000 37482082545802430000000000000000.000000 106805191827844450000000000000000.000000 27817414541403927000000000000000.000000
0.000000 1.000000 79688540809186700000000000000000.000000 56770527847676790000000000000000.000000 -56594841911867110000000000000000.000000 -67892248860462540000000000000000.000000
0.000000 1.000000 113178561706193770000000000000000.000000 159783570835960630000000000000000.000000 -76747968988369190000000000000000.000000 -14819046546759074000000000000000.000000
1.000000 0.000000 -28403378468319500000000000000000.000000 -12232165317282937000000000000000.000000 25499437099836310000000000000000.000000 -28504855701617950000000000000000.000000
0.000000 1.000000 -31206425305749290000000000000000.000000 23600514450824994000000000000000.000000 -17805072769468274000000000000000.000000 -43845592425166965000000000000000.000000
1.000000 0.000000 -25969718915072960000000000000000.000000 75570189933571110000000000000000.000000 -31958556086570890000000000000000.000000 -17601597255843116000000000000000.000000
0.948166 0.051835 -63.734016 -387.792114 -569.298767 -460.760010
0.944951 0.055049 19.591267 -98.694290 121.338081 -13.369317
0.941335 0.058665 45.873062 -55.803158 -4.560786 -133.835815
1.000000 0.000000 5852403848125322000000000000000.000000 -12818769974882904000000000000000.000000 9270502576616430000000000000000.000000 -33799733184882496000000000000000.000000

CPU
0.943954 0.056046 546.441895 199.126144 -339.588074 70.642044
0.932864 0.067136 663.946411 813.192017 -67.176483 366.294922
0.924546 0.075454 502.542908 753.034119 -411.762146 140.737015
0.947124 0.052876 -372.240356 111.347778 -456.431305 -54.801693
0.938151 0.061849 -394.491943 723.942993 -219.131943 275.616882
0.931809 0.068191 -264.284424 719.915588 -439.095795 136.958084
0.949984 0.050016 40.844231 46.047665 -1071.941772 -423.784668
0.948004 0.051996 -37.008282 291.401093 -360.245667 -8.781137
0.948927 0.051073 -232.510651 351.550140 -232.721848 25.473518
0.947411 0.052589 -168.603821 -245.925522 -982.257141 -494.832184
0.946205 0.053795 121.196175 136.661102 -411.463470 -61.700977
0.947822 0.052178 145.699097 242.051498 -368.328308 -18.955723
0.950891 0.049109 245.020126 37.207867 -997.234558 -550.028503
0.947889 0.052111 139.870041 282.246582 -330.454407 -30.775051
0.949342 0.050658 18.845734 287.226349 -329.962219 -45.978249
0.948421 0.051579 29.227474 171.604523 -676.300354 -387.206726
0.945300 0.054700 334.688538 437.656189 -120.102249 -13.328161
0.944995 0.055005 320.806396 453.638916 -92.753052 0.245833
0.951835 0.048165 161.016876 -100.445564 -388.817993 -216.044601
0.947542 0.052458 435.896912 352.136108 156.850311 19.001419
0.944383 0.055617 355.845612 599.699097 196.363297 71.831528
0.951963 0.048037 239.960190 117.357056 -320.302155 -112.081520
```

**Comment by gwang-msft** [comment]
Please try to rebuild the ORT by changing this line
https://github.com/microsoft/onnxruntime/blob/7ca8388dc98cbc23c7c165064bca6b3142d28d79/onnxruntime/core/providers/nnapi/nnapi_builtin/builders/model_builder.h#L149
to
TargetDeviceOption target_device_option_{TargetDeviceOption::CPU_ONLY};
And let us know if the output is different than the one that CPU gives.

If we set target_device_option_ to CPU only, the execution is forced to run on NNAPI CPU implementation, if the result is the same as running on ORT CPU, then this may related to the precision of the actual NPU/GPU implementation of Android NNAPI.

**Comment by s94285** [comment]
> Please try to rebuild the ORT by changing this line
> 
> https://github.com/microsoft/onnxruntime/blob/7ca8388dc98cbc23c7c165064bca6b3142d28d79/onnxruntime/core/providers/nnapi/nnapi_builtin/builders/model_builder.h#L149
> 
> to
> `TargetDeviceOption target_device_option_{TargetDeviceOption::CPU_ONLY};`
> And let us know if the output is different than the one that CPU gives.
> 
> If we set target_device_option_ to CPU only, the execution is forced to run on NNAPI CPU implementation, if the result is the same as running on ORT CPU, then the issue you were seeing may be related to the precision of the actual NPU/GPU implementation of Android NNAPI.

I changed the line to `TargetDeviceOption target_device_option_{TargetDeviceOption::CPU_ONLY};`
But it still uses NN HAL instead of CPU since I gets outputs from the npu service process.
How can I get verbose logs of onnxruntime from logcat?

**Comment by s94285** [comment]
By the way, I am using android 9.0 API 28, which does not support GetTargetDevices().
It might be the cause of not using NNAPI CPU.

**Comment by gwang-msft** [comment]
You can try to build the ORT for x86_64 and run your test app on an Android Simulator to see the result by NNAPI CPU implementation.

Please also provide the spec of the device you ran the test App on.

**Comment by s94285** [comment]
The test app was running on an android TV board with armeabi-v7a arch and android 9.
I built arm64-v8a version to test on my Zenfone 5Z running android 9.
It works well and only slight difference between CPU and NNAPI output.
So I guess it might be the TV board's issue or armeabi-v7a version has something different.
I'll try it on other armeabi-v7a devices.
Thanks for the reply :D

**Comment by s94285** [comment]
After turning off NN HAL process on the TV board so that NNAPI can only use CPU, the outputs become stable.
So it happens to be the TV board's problem.
