### ISSUE TITLE
Unable to load model generated by tf2onnx 

### ISSUE THREAD

**Issue by bedapisl** [microsoft/onnxruntime#4997]
**Describe the bug**
When loading model generated by tf2onnx I got following error: 
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (generic_loop_Loop__44) Op (Loop) [TypeInferenceError] Graph attribute inferencing failed: Node (generic_loop_Loop__25) Op (Loop) [TypeInferenceError] Graph attribute inferencing failed: Type Error: Type parameter (T) bound to different types (tensor(int64) and tensor(int32) in node (loop_over_batch/while/loop_over_classes/while/Equal).
```

**System information**
- OS Platform and Distribution: Ubuntu 18.04
- ONNX Runtime installed from (source or binary): binary (pip)
- ONNX Runtime version: 1.4.0
- Python version: 3.6.9

**To Reproduce**
Try loading model this model [decode_detections.onnx.zip](https://github.com/microsoft/onnxruntime/files/5154554/decode_detections.onnx.zip) with 
```
>>> import onnxruntime
>>> onnxruntime.InferenceSession("decode_detections.onnx")
```

Is this a problem of onnxruntime or tf2onnx?

**Comment by hariharans29** [comment]
This seems to be a problem of tf2onnx. There is an 'Equal' node that seems to consume an output of a 'Size' node (which according to the onnx spec produces only int64 output - https://github.com/onnx/onnx/blob/master/docs/Operators.md#Size) and the other input to 'Equal' seems to be int32 which makes it an invalid onnx model as the input types to 'Equal' need to be homogeneous - 

![image](https://user-images.githubusercontent.com/9969784/91826249-2abf1400-ebf2-11ea-98c7-c46ec4c79ded.png)


Most likely a 'Cast' node was missed at the output of 'Size'.
