### ISSUE TITLE
Loading onnx model failed with Fatal error: max_pool2d is not a registered function/op

### ISSUE THREAD

**Issue by eRaul** [microsoft/onnxruntime#4998]
**Describe the bug**
I have exported a pytorch model squeezenet1.1 (which is traced with torch.jit.trace). This model comes from torchvison model zone. Now I want to use it to inference with onnxruntime, but failed:
```
sess = rt.InferenceSession(model)
```
Exception below was throwed:
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Fatal error: max_pool2d is not a registered function/op
```

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): binary (pip3 install onnxruntime==1.2.0)
- ONNX Runtime version: 1.2.0 (1.4.0 also tried)
- Python version: 3.6

**Comment by hariharans29** [comment]
This is an export issue. There is no 'max_pool2d' in the list of supported operators in onnx - https://github.com/onnx/onnx/blob/master/docs/Operators.md.  Please report this to PyTorch.

**Comment by eRaul** [comment]
> This is an export issue. There is no 'max_pool2d' in the list of supported operators in onnx - https://github.com/onnx/onnx/blob/master/docs/Operators.md. Please report this to PyTorch.

OK, Thanks！
