### ISSUE TITLE
tf_inception_v2  result mismatch

### ISSUE THREAD

**Issue by mateusztabaka** [microsoft/onnxruntime#5001]
**Describe the bug**
It's not really a bug, but a question/sighting. I can see that tests on tf_inception_v2 model are disabled on CPU because of result mismatch. I ran the model on OpenVINO and on onnxruntime (CPU) and I'm getting no mismatches (atol==0.001, rtol==1e-6) between those two. I'm getting mismatches when I compare results with reference output (output_0.pb files) so OpenVINO vs. reference or onnxruntime vs. reference.
So I suspect an issue with reference outputs for that model. My question is how are those outputs generated and if you could revise them for correctness.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 464bbd27a939ebc73bfd7fe3eea0eeb93a76e56b
- Python version: 3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 5.4.0
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by snnn** [comment]
It was generated from https://github.com/microsoft/onnxruntime/blob/snnn/master/scripts/gen_output.py

The source model was from: https://github.com/tensorflow/models/tree/master/research/slim

Direct download link: http://download.tensorflow.org/models/inception_v2_2016_08_28.tar.gz

Then converted to onnx by using [tf2onnx](https://github.com/onnx/tensorflow-onnx)

**Comment by mateusztabaka** [comment]
This script fails to import preprocessing_factory on my end. Where can I find this module? Also in gen_output.py I can see references to your local files, like /home/chasun/os/models/research/slim/export_inference_graph.py. Can you also share this file?

**Comment by snnn** [comment]
You can find these files in https://github.com/tensorflow/models/tree/master/research/slim

**Comment by mateusztabaka** [comment]
I used your script to regenerate input and output pb files for inception_v2. With that, I'm getting no mismatches (atol==0.001, rtol==1e-6) in following scenarios: OpenVino vs. new reference and onnxruntime vs. new reference. I believe the references we've had so far are not correct. Could you revise them?

**Comment by snnn** [comment]
> I used your script to regenerate input and output pb files for inception_v2. With that, I'm getting no mismatches (atol==0.001, rtol==1e-6) in following scenarios: OpenVino vs. new reference and onnxruntime vs. new reference. I believe the references we've had so far are not correct. Could you revise them?

Maybe tf2onnx converter fixed the issue. Let me try it. Thank you!

**Comment by mateusztabaka** [comment]
Hi, have you had a chance to try it on your end?

**Comment by snnn** [comment]
Yes. I'll regenerate the test data.

**Comment by mateusztabaka** [comment]
Cool, can you let me know once that's done?

**Comment by snnn** [comment]
Sure.

**Comment by snnn** [comment]
Will be after 1.5 release.

**Comment by mateusztabaka** [comment]
hi, any update on this?

**Comment by mateusztabaka** [comment]
Hi, we're after 1.5 release. Do you have any update on this issue?

**Comment by snnn** [comment]
I've temporarily deleted the model from our test dataset. So it shouldn't be a problem now.

**Comment by mateusztabaka** [comment]
> Yes. I'll regenerate the test data.
is the data already regenerated? If yes, where can I find it?
