### ISSUE TITLE
cpu float16 support

### ISSUE THREAD

**Issue by zhuxiaoxuhit** [microsoft/onnxruntime#5025]
**Is your feature request related to a problem? Please describe.**
Almost all ops support float16 on CUDA, not on cpu.

**System information**
- ONNX Runtime version (you are using):master

**Describe the solution you'd like**
Support float16 ops on cpu.

**Comment by tianleiwu** [comment]
@zhuxiaoxuhit, what model do you want to use float16 on cpu? 

I think people would use int8 quantization if they want faster speed on CPU.

**Comment by yaysummeriscoming** [comment]
x86 CPUs don't support float16, but for ARM this might be interesting. I've had some experience with XNNPACK, that offers very competitive performance with float16

**Comment by MrRace** [comment]
@yaysummeriscoming  x86 CPUs don't support float16 and why？ Could you share some official  materials？

**Comment by tianleiwu** [comment]
See related discussion: https://stackoverflow.com/questions/49995594/half-precision-floating-point-arithmetic-on-intel-chips

**Comment by vadimkantorov** [comment]
float16/bfloat16 on CPU can still be interesting as a relatively safe form of quantization: e.g. you save on memory store/memory load amounts, if your model has a significant memory-bound component...
