### ISSUE TITLE
Missing plugin when building with LTO+CUDA

### ISSUE THREAD

**Issue by xkszltl** [microsoft/onnxruntime#5031]
**Describe the bug**

We found ar/ranlib were used without proper `--plugin` in LTO+CUDA. build and failed with:
```
plugin needed to handle lto object
```

Some work-around I used for now:
1. `-DCMAKE_AR=gcc-ar -DCMAKE_RANLIB=gcc-ranlib`.
2. `-DCMAKE_{C,CXX,CUDA}_COMPILER_{AR,RANLIB}="--plugin=$(gcc --print-file-name=liblto_plugin.so)"`

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master
- GCC/Compiler version (if compiling from source): 8
- CUDA/cuDNN version: 11.0/8

**Comment by snnn** [comment]
CUDA 10.x doesn't have a good LTO support, especially the nvcc.

**Comment by xkszltl** [comment]
@snnn Good to know.
Do you know what's the status in CUDA 11?
I found `-dlto` options in nvcc 11 so I guess at least it can do it in device side, just not sure how it works with `-flto`
