### ISSUE TITLE
Build nuget locally on Linux

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#5034]
**Describe the bug**
I am using this against latest master to build nuget

```bash
./build.sh --update --config RelWithDebInfo --build --build_wheel --use_mklml --build_nuget --skip_tests
```

after installing nuget I first got this error (about license):

> The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd' has invalid child element 'license' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'. List of possible elements expected: 'frameworkAssemblies, licen
seUrl, releaseNotes, requireLicenseAcceptance, developmentDependency, dependencies, summary, language, references, title, projectUrl' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'.
/home/ehazar/repos/onnxruntime/csharp/OnnxRuntime.CSharp.proj(133,5): error MSB3073: The command "nuget pack NativeNuget.nuspec" exited with code 1.

then updated nuget to the latest following [here](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#macoslinux)

```bash
sudo apt install nuget
sudo curl -o /usr/local/bin/nuget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
```

and now get this error

> Unhandled Exception:
> [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'System.AppContext' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

I am not sure if the updated nuget does not have proper mono libraries, or how to get a version that is new enough to understand "version" metadata but not crash with the above error

**Urgency**
need to package for testing latency

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version:
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Expected behavior**
Some instructions on how to install nuget.exe for it to work

**Comment by dashesy** [comment]
Not sure why nuget is needed when dotnet pack shoudl be fine.
However, the traceback shows the error is dotnet, not nuget.

> Traceback (most recent call last):
  File "/home/ehazar/repos/onnxruntime/tools/ci_build/build.py", line 1823, in <module>
    sys.exit(main())
  File "/home/ehazar/repos/onnxruntime/tools/ci_build/build.py", line 1805, in main
    args.use_mklml
  File "/home/ehazar/repos/onnxruntime/tools/ci_build/build.py", line 1458, in build_nuget_package
    run_subprocess(cmd_args, cwd=build_dir)
  File "/home/ehazar/repos/onnxruntime/tools/ci_build/build.py", line 428, in run_subprocess
    env=my_env, shell=shell)
  File "/home/ehazar/miniconda3/envs/py3_night/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['dotnet', 'msbuild', 'OnnxRuntime.CSharp.proj', '/t:CreatePackage', '/p:OrtPackageId="Microsoft.ML.OnnxRuntime.MKLML"', '/p:Configuration="RelWithDebInfo"', '/p:ExecutionProvider="None"', '/p:IsLinuxBuild="true"']' returned non-ze

**Comment by dashesy** [comment]
Found a workaround that now creates nuget:

A search showed [similar issue](https://github.com/NuGet/docs.microsoft.com-nuget/issues/1239) and the solution was to follow [here to update mono](https://www.mono-project.com/download/stable/#download-lin) followed by this:

```bash
sudo apt-get install mono-complete
```

Can you verify if this is correct way, if so might be helpful to add this to a wiki

-----

It is a shame nuget.exe depends on mono instead of dotnet.core

**Comment by askhade** [comment]
@dashesy : We use dotnet pack for creating the onnxruntime managed nuget package however we have to rely on nuget to create the native nuget package as at this moment dotnet pack does not support creating a nuget package from nuspec.
Yes nuget relies on mono instead of dotnet and this is not the most desirable experience as you can tell. 

This page describes how to install mono : https://www.mono-project.com/download/stable/#download-lin (which I believe you ended up following too) I am sending out a PR with more instructions on how to download prerequisites for building nuget packages.

**Comment by dashesy** [comment]
Just for the sale of completeness I am using this to install latest nuget

```bash
apt-get install -y nuget && curl -o /usr/lib/nuget/NuGet.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
```
