### ISSUE TITLE
Doc page with list of supported ops ?

### ISSUE THREAD

**Issue by WilliamTambellini** [Microsoft/onnxruntime#504]
**Is your feature request related to a problem? Please describe.**
Cant find a page/md with the list of supported onnx ops

**System information**
- ONNX Runtime version : 0.2.1

**Describe the solution you'd like**
Just an updated .md page with the list of supported ops

**Describe alternatives you've considered**
Generate the list at runtime (GetListOfSupportedOps() ?)

**Comment by faxu** [comment]
ONNX Runtime is compliant with ONNX 1.2+ and should support [all ONNX ops](https://github.com/onnx/onnx/blob/master/docs/Operators.md) up to opset8. Opset9 support is in progress and will be included in the next release.

**Comment by pranavsharma** [comment]
Closing as per last comment.
