### ISSUE TITLE
segmentation fault when infer with gpu

### ISSUE THREAD

**Issue by siweimaodou** [microsoft/onnxruntime#5046]
**Describe the bug**
use mobilenet_v2 model, when infer with onnxruntime 1.4.0, it worked well, but the code throw segmentation fault when infer with onnxruntime-gpu 1.4.0

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.4.0
- Python version: 3.6.10
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:cuda 10.1 cudnn 7.6.5
- GPU model and memory: gpu0 Telsa P100-PCIE 16G; gpu1 Tesla P100-PCIE 16G; driver version:418.39

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.
wit gdb, i get folling info
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fff5c3f2930 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1

**Comment by siweimaodou** [comment]
[test.zip](https://github.com/microsoft/onnxruntime/files/5166092/test.zip)
here is my code

**Comment by hariharans29** [comment]
Can you try with the latest nightly (details: https://github.com/microsoft/onnxruntime#binaries) ?
