### ISSUE TITLE
Export set provider API in C++

### ISSUE THREAD

**Issue by tkclimb** [microsoft/onnxruntime#5047]
Currently I began to use ort in C++. I expected to use it with Tensorrt provider but I couldn't find the api for enabling the provider from C++ function.
I checked the [doc](https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/TensorRT-ExecutionProvider.md#cc) and it seems to need `onnxruntime::InferenceSession` not 'Ort::Session', which is  exported to users in `onnxruntime_cxx_api.h`.
I think it is thought users normally use this header file to integrate ort into their own project as well as I'm doing.
In this sense, I think `Ort::Session` would be better to have the provider activate function. What do you think??

Current solution seems that only adding the function to `onnxruntime_c_api.cc` and exporting them from the headers (c_api and cxx_api), of course it needs to rebuild ort but it's not user friendly.
Is there another solution ??

**Comment by tkclimb** [comment]
I just want to know more one point.
I thought `Ort::Session` uses `CPUExecutionProvider` originally even if we built the ort with enabling Tensorrt provider. is it correct??

**Comment by pranavsharma** [comment]
To use the tensorrt provider, 
* build ORT as per the instructions [here](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#tensorrt).
* use the OrtSessionOptionsAppendExecutionProvider_Tensorrt C API from include/onnxruntime/core/providers/tensorrt/tensorrt_provider_factory.h to add the provider to session options.
* call CreateSession and Run as usual

CPUExecutionProvider is the default and will always get added to the session irrespective of which other provider you add. By default the CPU provider is the fallback option after all the other providers that you add to the session. The priority is the order in which you add. See https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h#L396.

**Comment by tkclimb** [comment]
@pranavsharma 
it works correctly and Tensorrt provider seems properly used during inference in my environment.
Many thanks.
