### ISSUE TITLE
Does custom_op_library support dynamic input of CustomOp?

### ISSUE THREAD

**Issue by lewisword** [microsoft/onnxruntime#5049]
I have followed the instruction of [AddingCustomOp.md](https://github.com/microsoft/onnxruntime/blob/master/docs/AddingCustomOp.md) to add my CustomOp, but my CustomOp has  dynamic input, which is the number and type of input is uncertained. It can have two or three input, and the type of input could be int or float.

I use the first scheme of [AddingCustomOp.md](https://github.com/microsoft/onnxruntime/blob/master/docs/AddingCustomOp.md), which is "Using the custom op API in the C/C++ APIs (onnxruntime_c_api.h)", but I run into problems quickly. This scheme doesn't seem to support dynamic input. Because the running process is this:
1. Get information of CustomOp, including the input numbers and types, output numbers and types
2. Create CustomOp
3. Load onnx model, and Verify the information of CustomOp(graph.cc: InferAndVerifyTypeMatch)
4. Compute CustomOp

BUT I can only specify One type or count of input, just like the code below.
```cpp
  size_t GetInputTypeCount() const { return 2; };
  ONNXTensorElementDataType GetInputType(size_t /*index*/) const { return ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT; };

  size_t GetOutputTypeCount() const { return 1; };
  ONNXTensorElementDataType GetOutputType(size_t /*index*/) const { return ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT; };
```

HOW can I support dynamic input of CustomOp by custom_op_library?

**Comment by RyanUnderhill** [comment]
@lewisword Yeah, the current custom ops are fairly simple and don't support dynamic inputs. It would require a more complex API, and at a certain point it's better to just add the op using the internal interfaces to get every feature.

But nothing is impossible if this is what people want. It's just not possible currently.

**Comment by zr1161309493** [comment]
@RyanUnderhill 
I need to implement a new relu op (onnx does not have this op), which supports float16 and float32 inputs, but I found that it cannot be done through the onnxruntime C/C++ custom interface, because an error will be reported if the custom_op name is the same.

<img width="488" alt="1" src="https://user-images.githubusercontent.com/33832771/93066934-27755f00-f6ad-11ea-9f1a-b21f6d58e1a8.png">


sincerely thanks.

**Comment by KnightYao** [comment]
I have the same requirement. When can this function be supported

**Comment by dingjie1993** [comment]
I have the same problem, When can this function be added

**Comment by lambdaXliu** [comment]
nothing is impossible if this is what people want, a ha ha.
people do want this!

**Comment by lifangzu1993** [comment]
Need this feature +1

**Comment by pgr2015** [comment]
Need multiple input types，for example float or float16。

**Comment by RandySheriffH** [comment]
Please check [SliceCustomOp](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_inference.cc#L364) for how-to.
