### ISSUE TITLE
browserify difficulty?

### ISSUE THREAD

**Issue by abcdchop** [microsoft/onnxruntime#5058]
Hi all, 

I'm running into some trouble trying to use browserify on a model I'm running on onnxruntime with node.js-- I truly have no idea how to begin to approach this, or whether I should try and find a better bundler?

Anyway, pre-browserify, my code runs fine-- when I bundle it up however, I get the following bug:
Uncaught Error: Cannot find module '../bin/napi-v3/undefined/undefined/onnxruntime_binding.node'

Here is the bundled code that seems to be causing the issue:

<img width="1096" alt="Screen Shot 2020-09-03 at 7 24 39 PM" src="https://user-images.githubusercontent.com/61578753/92183067-48bb8d00-ee1b-11ea-8d91-cd11fab74226.png">

I am quite new to all this, and have no idea really what to think about here.

Any advice you could give would be much appreciated, and thanks in advance!

**Comment by fs-eire** [comment]
ONNXRuntime node.js binding works only on Node.js or Electron.js, it does not work on browsers. You may want to take a look at [ONNX.js](https://github.com/microsoft/onnxjs.git) to see if it fits your requirement.
