### ISSUE TITLE
Inference by C++ GPU

### ISSUE THREAD

**Issue by zsy9512** [microsoft/onnxruntime#5076]
Hi. By referring to your example, I have successfully run my C++ inference demo in CPU mode.But I can't very understand how to run my cuda demo by using onnx model.Could you please  provided me some good examples or told me how to find the API documents to acheive my target? And do you provide the multi-image test on onnx func? I can find these infomation in the web

**Comment by pranavsharma** [comment]
1. Install the GPU pkg.
2. See onnxruntime/samples/c_cxx/imagenet/main.cc for an example.
The key thing is to register the CUDA EP to the session using this API OrtSessionOptionsAppendExecutionProvider_CUDA.

**Comment by zsy9512** [comment]
> 1. Install the GPU pkg.
> 2. See onnxruntime/samples/c_cxx/imagenet/main.cc for an example.
>    The key thing is to register the CUDA EP to the session using this API OrtSessionOptionsAppendExecutionProvider_CUDA.

Thank you,I have finish my work to infer a yolov5 model by onnx format,it is so fast. great work

**Comment by olegggatttor** [comment]
Hey! I looked through the [onnxruntime-inference-examples](https://github.com/microsoft/onnxruntime-inference-examples)/[c_cxx](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx)/[imagenet](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/imagenet)/main.cc and as I understood to use CUDA I have to add provider using Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_CUDA(sessionOptions, 0));. But looking through the docs I saw that this is the old way of giving option to infer models on GPU. What is the new way? Now my model works well on CPU (I do not supply any providers). How to transfer it to GPU?

**Comment by AvalonChang** [comment]
> Hey! I looked through the [onnxruntime-inference-examples](https://github.com/microsoft/onnxruntime-inference-examples)/[c_cxx](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx)/[imagenet](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/imagenet)/main.cc and as I understood to use CUDA I have to add provider using Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_CUDA(sessionOptions, 0));. But looking through the docs I saw that this is the old way of giving option to infer models on GPU. What is the new way? Now my model works well on CPU (I do not supply any providers). How to transfer it to GPU?

in my work (used onnxruntime-win-x64-gpu-1.12.0), I still use OrtSessionOptionsAppendExecutionProvider_CUDA same as c_cxx/imagenet/main.cc.
and the GPU mode is work well.

just remember copy the onnxruntime_providers_cuda.dll & onnxruntime_providers_shared.dll into your output directory

**Comment by AvalonChang** [comment]
> Hey! I looked through the [onnxruntime-inference-examples](https://github.com/microsoft/onnxruntime-inference-examples)/[c_cxx](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx)/[imagenet](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/imagenet)/main.cc and as I understood to use CUDA I have to add provider using Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_CUDA(sessionOptions, 0));. But looking through the docs I saw that this is the old way of giving option to infer models on GPU. What is the new way? Now my model works well on CPU (I do not supply any providers). How to transfer it to GPU?

in my work (used onnxruntime-win-x64-gpu-1.12.0), OrtSessionOptionsAppendExecutionProvider_CUDA still work well.
just remember copy the onnxruntime_providers_cuda.dll & onnxruntime_providers_shared.dll into your output directory.

for the new way, I think in C++ you can use SessionOptions::AppendExecutionProvider_CUDA.
such as below
```
Ort::Env env;
Ort::SessionOptions session_options;
OrtCUDAProviderOptions cuda_options;
cuda_options.device_id = 0;
session_options.AppendExecutionProvider_CUDA(cuda_options);
Ort::Session session = Ort::Session(env, L"model.onnx", session_options);
```
