### ISSUE TITLE
Read Access Violation error and application crash while inference from TreeEnsembleClassifier C++ APIs.

### ISSUE THREAD

**Issue by Karnav123** [microsoft/onnxruntime#5080]
**Describe the bug**
I am getting random Read Access violation error for a xgboostclassifier model. The error message is: 
-Non-zero status code returned while running TreeEnsembleClassifier node. 
`
*** ERROR: Unhandled exception: 0xc0000005 at Tue Sep  8 15:56:03 2020 India Standard Time
*** ERROR: Unhandled exception: 0xc0000005 at Tue Sep  8 15:56:03 2020 India Standard Time
*** ERROR: Unhandled exception: 0xc0000005 at Tue Sep  8 15:56:03 2020 India Standard Time
*** ERROR: Access violation
*** ERROR: Access violation
*** ERROR: Access violation
*** Exception was not in main thread
*** Exception was not in main thread
*** Exception was not in main thread
*** ERROR: Unhandled exception: 0xc0000005 at Tue Sep  8 15:56:03 2020 India Standard Time
*** ERROR: Access violation
*** Exception was not in main thread
*** ERROR: Unhandled exception: 0xc0000005 at Tue Sep  8 15:56:03 2020 India Standard Time
*** ERROR: Unhandled exception: 0xc0000005 at Tue Sep  8 15:56:03 2020 India Standard Time
*** ERROR: Unhandled exception: 0xc0000005 at Tue Sep  8 15:56:03 2020 India Standard Time
*** ERROR: Access violation
*** ERROR: Access violation
*** ERROR: Access violation
*** Exception was not in main thread
*** Exception was not in main thread
*** ERROR: Unhandled exception: 0xc0000005 at Tue Sep  8 15:56:03 2020 India Standard Time
*** Exception was not in main thread
*** ERROR: Access violation
*** Exception was not in main thread
`

**Urgency**
Yes it is urgent.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): Source
- ONNX Runtime version: 1.3.1
- Python version:
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source): 

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**
Run without Read Access Violation.

**Comment by RandySheriffH** [comment]
@Karnav123 
Would u mind share the model along with the inferencing script used?
In the meantime maybe you want to try onnxruntime 1.4.0.

**Comment by Karnav123** [comment]
The model can be accessed from https://github.com/Karnav123/onnx_model/blob/master/Model_XGB.onnx

To infer this Model I am using the following script. Although I can not give the whole script here because it is written in a OOPs way spanning across multiple file. To load the model: 

`
void Model::SetModel(const string& modelPath)
{
    const ORTCHAR_T* onnxModelPath = nullptr;
#ifdef WNT
    onnxModelPath = ToUnicode(modelPath);
#else
    onnxModelPath = modelPath.utf8_str();
#endif
    
    // ONNX runtime specific logging level. Should be static
    static Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "onnx_loader");

    Ort::SessionOptions sessionOptions;
    sessionOptions.SetIntraOpNumThreads(1);

      // Fixed crash when the prediction data is too big
    // Fixed inconsistent behavior in first prediction in session
    sessionOptions.DisableCpuMemArena();
    sessionOptions.DisableMemPattern();

    sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);

    try
    {
        this->m_onnxModel = new Ort::Session(env, onnxModelPath, sessionOptions);
    }
    catch (const Ort::Exception& exception)
    {
      // Print error
    }
}`

To convert the data to tensor:
`
Ort::Value input = Ort::Value::CreateTensor<double>(memoryInfo, inputDataBatch[i].data(),
                inputDataBatch[i].size(), inputBatchDims[i].data(), inputBatchDims[i].size());
            assert(input.IsTensor());
`
To Run the model:
`
auto predictedValues = onnxModel->Run(Ort::RunOptions{ nullptr }, inputNodeNames.data(),
                inputTensorRow, inputNodeNames.size(), outputNodeNames.data(), outputNodeNames.size());
            assert(predictedValues.size() == 2 && predictedValues.front().IsTensor());
`

The error occurs when Run is called.

**Comment by Karnav123** [comment]
@RandySheriffH I tried 1.4.0 but it still has the above-mentioned issue. However, if I set `sessionOptions.SetIntraOpNumThreads(1);`  to one then the frequency of this error is rare. Please, share any suggestions to fix the issue.

**Comment by Karnav123** [comment]
@RandySheriffH Is there any update on this issue?

**Comment by yuslepukhin** [comment]
I will take a look at it

**Comment by yuslepukhin** [comment]
I quickly run it using released version 1.4 and the latest tip of the master using the following script and I have not found any issues. But I will check the C++ API that you are using as well. Can you, please, verify where onnxruntime.dll is being loaded from? I am asking bc there might be one present in the system folder on windows but you probably want the one that comes with a package.

import numpy as np
import timeit
from timeit import default_timer as timer

import onnxruntime as ort
import onnx
import os

n_features = 22
run = 10000
test_data = np.random.rand(run, n_features).astype(np.float64)

sess_options.log_severity_level = 0
iters = 2

sess_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL

onnx_model_path = 'Model_XGB.onnx'
session = ort.InferenceSession(onnx_model_path, sess_options)

fetches_names = [session.get_outputs()[1].name]
feeds = {session.get_inputs()[0].name: test_data}

start = timer()
for i in range(iters):
    session.run(fetches_names, feeds)
end = timer()

print("iterations: {}".format(iters))
print("ORT avg latency: {}".format((end - start)/iters))

**Comment by yuslepukhin** [comment]
> 
> 
> @RandySheriffH I tried 1.4.0 but it still has the above-mentioned issue. However, if I set `sessionOptions.SetIntraOpNumThreads(1);` to one then the frequency of this error is rare. Please, share any suggestions to fix the issue.

How big is your input?

**Comment by yuslepukhin** [comment]
The attached program runs fine to completion on Windows 10. You mentioned something about input size. Please, let me know.

[TreeEn.pdf](https://github.com/microsoft/onnxruntime/files/5264903/TreeEn.pdf)

**Comment by Karnav123** [comment]
> The attached program runs fine to completion on Windows 10. You mentioned something about input size. Please, let me know.
> 
> [TreeEn.pdf](https://github.com/microsoft/onnxruntime/files/5264903/TreeEn.pdf)
> 
> 

Thanks for your response. I get this issue sometimes on input size of 1000 also. The error occurs randomly. I think on a standalone code this is working fine but I am loading this as a third party DLL within another application that I am working. In that case for some dataset I get this error which is random. 
Adding the following 
`
sessionOptions.DisableCpuMemArena();
sessionOptions.DisableMemPattern();
`
code resolved some other issues but this crash still appears.
I am not able to exactly figure out why. Because , if the data has been converted to tensor correctly without any error then why it gives error while run.
Please provide me some insights that I am not able to see.

**Comment by yuslepukhin** [comment]
> I get this issue sometimes on an input size of 1000 also. The error occurs randomly. I think on a standalone code this is working fine but I am loading this as a third party DLL (downloaded from onnxruntime repo) within another application that I am working. In that case for some dataset, I get this error which is random.

It is a long shot to provide insights into some unknown application with 3rd party libraries across the continents. Why don't you just debug it and in the debugger you get all the insights you need including where all the DLLs are loaded from?

> I am not able to exactly figure out why. Because, if the data has been converted to tensor correctly without any error then why it gives error while run.

Sure, my insights are based solely on the information presented on this thread. ReadAccessViolation is a Structure Windows Exception (not to be confused with C++ exceptions) that is raised when you attempt to read memory that is not accessible to you (not even mapped to address space). The reason it is random, is bc we use arenas and when one attempts to go beyond the buffer it often lands into mapped memory that belongs to another allocated buffer. DisablingArena and MemPattern is a good first step in debugging such things because the allocation requests would go straight to the OS. Those calls can be sanitized by memory tools such as Application Verifier. that would tell you which code tries to read unmmaped memory.

The problem may be simple to solve. You say, it converted to Tensor Successfully. There is not a way it can fail. There is not any conversion taking place. It simply wraps the supplied buffer and trusts you that the buffer length matches the supplied shape bc we do not want to copy any data. If the shape indicates that the buffer is bigger than it actually  is, we would attempt to read beyond it and the OS would raise the above exception. For example, for a buffer that contains double with a shape of [10,000, 22] the buffer size should be at least 10,000 * 22 * sizeof(double) bytes. Which on a 64-bit platform comes down to 1,760,000 bytes. The memory allocation for the buffer should be driven off the shape + type.

Another issue that I can see is the use of C++ API. Ort::Session object is designed to hold the native pointer to the actual object returned by C API. Should the Ort::Session object go out of scope it will clean the session object up automatically. However, you defeat that and choose to allocate it dynamically making it a subject of a potential memory leak. Essentially, you allocate memory for a pointer to another dynamic allocation. Even if there is a delete statement downwhere, it is not reached when an exception is thrown after a session object is constructed. This means, that a whole lot of memory along with the threads would leak that the session is holding. You application would be really struggling and would run out of memory pretty soon after just one or two such leaks.

Finally, we have option to use onnxruntime via languages other than C++ and C. That includes Python, Java and C#.

**Comment by Karnav123** [comment]
> > I get this issue sometimes on an input size of 1000 also. The error occurs randomly. I think on a standalone code this is working fine but I am loading this as a third party DLL (downloaded from onnxruntime repo) within another application that I am working. In that case for some dataset, I get this error which is random.
> 
> It is a long shot to provide insights into some unknown application with 3rd party libraries across the continents. Why don't you just debug it and in the debugger you get all the insights you need including where all the DLLs are loaded from?
> 
> > I am not able to exactly figure out why. Because, if the data has been converted to tensor correctly without any error then why it gives error while run.
> 
> Sure, my insights are based solely on the information presented on this thread. ReadAccessViolation is a Structure Windows Exception (not to be confused with C++ exceptions) that is raised when you attempt to read memory that is not accessible to you (not even mapped to address space). The reason it is random, is bc we use arenas and when one attempts to go beyond the buffer it often lands into mapped memory that belongs to another allocated buffer. DisablingArena and MemPattern is a good first step in debugging such things because the allocation requests would go straight to the OS. Those calls can be sanitized by memory tools such as Application Verifier. that would tell you which code tries to read unmmaped memory.
> 
> The problem may be simple to solve. You say, it converted to Tensor Successfully. There is not a way it can fail. There is not any conversion taking place. It simply wraps the supplied buffer and trusts you that the buffer length matches the supplied shape bc we do not want to copy any data. If the shape indicates that the buffer is bigger than it actually  is, we would attempt to read beyond it and the OS would raise the above exception. For example, for a buffer that contains double with a shape of [10,000, 22] the buffer size should be at least 10,000 * 22 * sizeof(double) bytes. Which on a 64-bit platform comes down to 1,760,000 bytes. The memory allocation for the buffer should be driven off the shape + type.
> 
> You may also want to avoid allocating Ort::Session dynamically. It is simply a container for another pointer.
> 

Do you mean that we should not load the model using new().

> Finally, we have option to use onnxruntime via languages other than C++ and C. That includes Python, Java and C#.

**Comment by yuslepukhin** [comment]
Loading of the model has nothing to do with new/delete. It happens in the constructor.
For every new there should be a corresponding delete. Ort::Session was created with a sole purpose to destroy the 
underlying session object from its destructor automatically w/.o explicit calls. Now it has to be deleted itself. I gave you an example how to load a model in the code that I presented. It is exception safe and the cleanup is automatic. Just declare a class member 
Ort::Session session_{nullptr};
Then instantiate another Ort::Session object in a function. After it succeeds, std::move it to the member of the class.

**Comment by Karnav123** [comment]
> Loading of the model has nothing to do with new/delete. It happens in the constructor.
> For every new there should be a corresponding delete. Ort::Session was created with a sole purpose to destroy the
> underlying session object from its destructor automatically w/.o explicit calls. Now it has to be deleted itself. I gave you an example how to load a model in the code that I presented. It is exception safe and the cleanup is automatic. Just declare a class member
> Ort::Session session_{nullptr};
> Then instantiate another Ort::Session object in a function. After it succeeds, std::move it to the member of the class.

@yuslepukhin I did some debugging of the onnxruntime source code to reproduce the issue. This access violation is because of the fact that the x_data variable in the following method 
```
void TreeEnsembleCommon<ITYPE, OTYPE>::ComputeAgg(concurrency::ThreadPool* ttp, const Tensor* X, Tensor* Z,
                                                  Tensor* label, const AGG& agg) const 
{
      int64_t stride = X->Shape().NumDimensions() == 1 ? X->Shape()[0] : X->Shape()[1];
      int64_t N = X->Shape().NumDimensions() == 1 ? 1 : X->Shape()[0];

      const ITYPE* x_data = X->template Data<ITYPE>();   // This is NULL or sometimes all zeros

      // remaining code
}
```
in the file onnxruntime\core\providers\cpu\ml\tree_ensemble_common.h. I think there is some inconsistency in the behaviour is going on there.

This issue is reproducible in latest version also.

I am adding some images of the debug values for more clarity of my explanation.

- Call Stack
![call_stack](https://user-images.githubusercontent.com/36244620/97868313-76e31d80-1d35-11eb-8e63-5b7197937c6b.PNG)

- Code and the value of x_data
![ss](https://user-images.githubusercontent.com/36244620/97868357-87939380-1d35-11eb-93a3-f5b578310570.PNG)

- The disassembly of the related code.
![image](https://user-images.githubusercontent.com/36244620/97868487-c590b780-1d35-11eb-98b7-12542e5fa9b6.png)

Please let me know if more reference is needed.

**Comment by Karnav123** [comment]
@yuslepukhin If you could look into the above observation, it would be helpful.

**Comment by Karnav123** [comment]
@yuslepukhin Any update please.

**Comment by yuslepukhin** [comment]
@Karnav123 Are you able to reproduce the issue using any of the code samples above that I mentioned before, either C++ or Python? If you do not wish to use them, then please, create your own concise example where the issue is reproducible.

Cc: @xadupre

**Comment by Karnav123** [comment]
> @Karnav123 Are you able to reproduce the issue using any of the code samples above that I mentioned before, either C++ or Python? If you do not wish to use them, then please, create your own concise example where the issue is reproducible.
> 
> Cc: @xadupre

I think there was an issue in my code which I corrected and the bug is gone now.
