### ISSUE TITLE
ONNXRuntime java library should include libgomp.so.1

### ISSUE THREAD

**Issue by frankfliu** [microsoft/onnxruntime#5082]
**Describe the bug**
I'm using onnxruntime java 1.4.0 on ubuntu 16.04. My system doesn't have gcc installed.
I got UnsatisfiedLinkError due to missing libgomp.so.1 file. I have to manually install gcc first before I can use onnxruntime.

**Urgency**
This makes it hard to redistribute the jar with onnxruntime. Extra requirement/documentation is required for the project depends on onnxruntime.

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- ONNX Runtime installed from: maven central
- ONNX Runtime version: 1.4.0
- Python version: N/A
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): Not installed
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
On a fresh ubuntu 16.04 machine or use ubuntu:16.04 docker container, create a java project depends on onnxrutime. Runt java project will failed to run: OrtEnvironment.getEnvironment()

**Expected behavior**
The java program should run at any environment without extra installation of GCC

**Comment by pranavsharma** [comment]
The requirement to install libgomp has been documented here for various OSs: https://github.com/microsoft/onnxruntime#system-requirements. We don't distribute dependencies with any of our packages.

**Comment by frankfliu** [comment]
Require end user to install extra package isn't a good user experience, especially for Java user. Please consider to bundle it if possible.
