### ISSUE TITLE
CalibrationDataReader does not have `datasize` field

### ISSUE THREAD

**Issue by vuvko** [microsoft/onnxruntime#5109]
**Describe the bug**
`CalibrationDataReader` class is providing the interface for preparing calibration data. However the calibration [code](https://github.com/microsoft/onnxruntime/blob/3207de276c1868b938358faac4e58a844379134e/onnxruntime/python/tools/quantization/calibrate.py#L128) requires `datasize` filed.

**Urgency**
Not urgent.

**To Reproduce**
You can change the field name in the E2E example from `datasize` to `num_data` for example.

**Expected behavior**

**Comment by yufenglee** [comment]
@vuvko , thanks for the PR: #5110 . Added a comment.
