### ISSUE TITLE
DirectML build from source failed

### ISSUE THREAD

**Issue by eublefar** [microsoft/onnxruntime#5115]
**Describe the bug**
Trying to build onnxruntime with directml support, but it fails during compilation of directml. All the errors appear to happen in d3d12.h 
`.\build.bat --use_dml --cmake_generator "Visual Studio 16 2019"` (2017 fails in the same fashion)

**Urgency**
None

**System information**
- OS: Windows 10
- ONNX Runtime installed from (source or binary): -
- ONNX Runtime version: 1.4.0 

- Python version: 3.6.10
- Visual Studio version (if applicable): 2017/2019
- GCC/Compiler version (if compiling from source): 

**To Reproduce**
I am not sure it is reproducible outside of my system but
- clone onnxruntime
- checkout v1.4.0
- `.\build.bat --parallel --use_dml`

**Expected behavior**
Compilation not failing

**Additional context**
Adding logs from the build
[logs.txt](https://github.com/microsoft/onnxruntime/files/5201797/logs.txt)

**Comment by wchao1115** [comment]
The build errors are due to missing D3D12 types. Notice that all of the spews are from d3d12x.h, which is a helper library that requires the D3D12 header file (d3d12.h). Can you check if you have the proper Windows SDK installed on your build machine? You should see something like this:

    Directory of C:\Program Files (x86)\Windows Kits\10\Include\10.0.XXXXX.0\um

    10/16/2019  04:27 PM           832,795 d3d12.h
    10/16/2019  04:27 PM           217,937 d3d12.idl

**Comment by eublefar** [comment]
Hmm that's weird, I have all the .libs in a different folder
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x64\*.lib

**Comment by eublefar** [comment]
It's there 
![image](https://user-images.githubusercontent.com/10601797/92789534-3c9b7680-f3ab-11ea-8926-3761068943e6.png)

**Comment by wchao1115** [comment]
I would check the includes path to `d3d12.h` to make sure that the right D3D12 header file is used.

**Comment by eublefar** [comment]
I have added path of Include\10.0.19041.0\um to `target_include_directories(onnxruntime_providers_dml ...)` in onnxruntime_providers.cmake 
and error changed to
`...Windows Kits\10\Include\10.0.19041.0\um\fileapifromapp.h(137,1): error C2146: syntax error: missing ';' before identifier 'BOOL'`

Could the problem be with the paths to windows kit?
I just installed it from link in DirectML build doc page, path to it is `C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um`

**Comment by wchao1115** [comment]
Possibly. Normally when you install visual studio, the right version of Windows Kits is also installed with the path to it properly configured. I'm not entirely sure what happens in your configuration.

**Comment by wchao1115** [comment]
Possibly. Normally when you install visual studio, the right version of Windows Kits is also installed with the path to it properly configured. I'm not entirely sure what happens in your configuration.

**Comment by eublefar** [comment]
Reinstalled latest windows sdk with visual studio installer and tried building from clean repo - same result :(

**Comment by wchao1115** [comment]
Can you try installing [Windows SDK 1903](https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/) and use VS2017 to build? That's the default compiler anyway, so don't override the option with `--cmake_generator`.

Delete the `build\windows\packages` folder and let the build script pulls the dependencies again. You should see the folder `build\windows\packages\directml.3.0.0` at the end of the build process. 

You can build faster by just skipping all the test code with `--skip_tests` like this:

`.\build.bat --config Debug --build_shared_lib --parallel --use_dml --skip_tests`

For the subsequent builds, you can also skip pulling all the dependencies with the submodules with `--skip_submodule_sync`.

**Comment by eublefar** [comment]
The issue is fixed, thanks a lot for the help!
Steps that fixed the problem:
- Clean install of VS2017
- Clean install of windows SDK from the link you've provided instead of using Visual Studio Installer 
- Not using conda environments (default python on the machine was 2.7 so I used conda environment with python 3)
