### ISSUE TITLE
unable to use opencv2 with CPU image 

### ISSUE THREAD

**Issue by initmahesh** [microsoft/onnxruntime#5134]
**Describe the bug**
we cannot use opencv as pip install fails with numpy and themn other failures on top of that ...

FROM mcr.microsoft.com/azureml/onnxruntime:latest

**To Reproduce**
FROM mcr.microsoft.com/azureml/onnxruntime:latest
docker run -it mcr.microsoft.com/azureml/onnxruntime:latest bash 
pip install python-opencv

**Expected behavior**
open cv should install 
but seems like the opencv need new version which is not there ,,

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by pranavsharma** [comment]
This is not an onnxruntime issue.
