### ISSUE TITLE
How to load an ML model created in tensorflow model format in onnx java runtime

### ISSUE THREAD

**Issue by bejugamvarun** [microsoft/onnxruntime#5143]
The sample included in the samples folder for the java runtime deals only with the libsvm model format, is there any way we can load a tensorflow model in java and run inference on the java side

I created a simple regression model in tensorflow and converted it into the onnx format using the tf2-onnx converter tool and i couldn't load the model into the java onnxruntime, the sample included here is not clear in case of my problem as it only deals with the libsvm model

**System information**
com.microsoft.onnxruntime:onnxruntime (maven dependency)
version: 1.4.0

**Comment by Craigacp** [comment]
The sample loads libsvm format *data*. The model is a regular onnx model. What error did you get when trying to load the model.

**Comment by bejugamvarun** [comment]
I am confused with performing inference in java api, first error i am getting is the onnxruntime.dll not found even after installing the maven dependency, and is there any way we can load the load the .onnx model in java because i couldn't find any documentation regarding the same, I only found that sample code in the repo

Can you please share any sample code to perform inference onnx java api?

**Comment by Craigacp** [comment]
Are you using the correct binary? The official one (https://search.maven.org/artifact/com.microsoft.onnxruntime/onnxruntime) contains onnx runtime binaries for Windows, macOS and Linux x86_64 systems. There are other compiled versions on maven central which have different things in them, you'll need to take it up with the people who maintain those if you're using a different one.

There are lots of examples of loading and scoring models in the tests for the Java API, along with the supplied sample. The Java API has docs here - https://github.com/microsoft/onnxruntime/blob/master/docs/Java_API.md, which link to the javadocs, the test sources, and has some short examples of loading and running inference on a model.
