### ISSUE TITLE
If I have multiple GPUs, how can I choose any of them

### ISSUE THREAD

**Issue by leaicc** [microsoft/onnxruntime#5149]
not a bug
onnxruntime-gpu runs on the first GPU by default, but I have multiple GPUs. How can I choose to run it on other GPU

**Comment by snnn** [comment]
@HectorSVC  Could you please help answer this question?

**Comment by HectorSVC** [comment]
not sure which API are you using. but check this out
OrtSessionOptionsAppendExecutionProvider_Tensorrt(sf, device_id);
OrtSessionOptionsAppendExecutionProvider_CUDA(sf, device_id);
https://github.com/microsoft/onnxruntime/blob/11c194ce290eb6309c44c1ecf1991a84f26dbf51/onnxruntime/core/providers/cuda/cuda_provider_factory.cc#L48-L50

**Comment by HectorSVC** [comment]
@leaicc Could we close this?
