### ISSUE TITLE
"Resize-11" ops with  "nearest neighbour" mode have unexpected behavior

### ISSUE THREAD

**Issue by chenhu-wang** [microsoft/onnxruntime#5151]
**Describe the bug**
For resize-11 ops, with "nearest neighbour" mode, the [coordinate transformation is applied to batch and channel dimension](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/tensor/upsample.cc#L174), while batch and channel are the same for input and output tensor, leading to data from one batch of input set to another batch of ouput.
Take an example, when inputShape is [B, C H W] == [4, 4, 10, 10], targetShape is [4, 4, 30, 30], "coordinate_transform_mode" is "TF_HALF_PIXEL_FOR_NN", "nearest_mode_name" is "ceil". For batch dimension, the first batch's transformed position is (0 + 0.5) / 1.f = 0.5, after round by "ceil" , it's 1(second batch). That means we set data to first batch with data from second batch. Is this an expected behaviour? 
For [other mode](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/tensor/upsample.cc#L398) or "[nearest neighbour" with scale 2x](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/tensor/upsample.cc#L53). Coordinate transformation is not applied to the batch and channel dimension.

**Urgency**
Urgent

**System information**
- all

**Expected behavior**
Coordinate transformation should not be applied to the batch and channel(scale == 1.0f) dimension. This is a nature behaviour and seemed the behavior of other platform(TF, pytorch...).

**Comment by chenhu-wang** [comment]
@yufenglee @zhanghuanrong @duli2012 could you please help check?
The modification should be simple. In [get_original_coordinate()](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/tensor/upsample.cc#L119), just return dim directly if scales[i] is 1.

**Comment by hariharans29** [comment]
Thank you for the detailed analysis - yes, there seems to be some inconsistency between the "generic" implementation and the "optimized" implementation (where scale for H and W is 2). 

"Coordinate transformation should not be applied to the batch and channel(scale == 1.0f) dimension. This is a nature behaviour and seemed the behavior of other platform(TF, pytorch...) " - I think we probably should skip co-ordinate transformation for ANY dimension (not just batch and scale) when scale for that dimension is 1.0. Does this seem like a good generalization that will address the issue that you raised ?

**Comment by chenhu-wang** [comment]
@hariharans29, Really thanks for investigating. And I agree that coordinate transformation should be skipped for any dimension which have 1.0 as scale or "input_size == output_size". Conduct coordinate map only if we really need a resize, and this is also consistent with pytorch implementation: [linear](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cpu/UpSampleMoreKernel.cpp#L23), [nearest](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cpu/UpSampleKernel.cpp#L42). Our model infer accuracy is correct when return output_index directly as input_index when scale is 1.0.
BTW, for resize with cubic mode, the [implementation only support bicubic](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cpu/UpSampleKernel.cpp#L42) but have no check if input is 2D or 4D. This lead to incorrect result without any exception or warning. The[ same check](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/tensor/upsample.cc#L644) is done for linear mode.

Regards!

**Comment by hariharans29** [comment]
Thank you.

I will try and propose a bug fix for the original issue you have raised here. But it won't make the upcoming release. Will be there in master soon.

Regarding the cubic check, I had the same doubt and checked with the original author  - it is actually done indirectly by validating scales - https://github.com/microsoft/onnxruntime/blob/6ad39819c20c278a4c3ec20ee838373008ed7ec7/onnxruntime/core/providers/cpu/tensor/upsample.h#L280. I will try and streamline the checks so as to not confuse the code reader.

Thanks for raising this.
