### ISSUE TITLE
Ort::Session creates redundant threads when running with DirectML backend

### ISSUE THREAD

**Issue by elad8a** [microsoft/onnxruntime#5153]
It is my understanding that working with DirectML backend mandates sequential execution. However, when creating a session with DirectML, onnxruntime decides it must create 6 additional threads that sit and wait on a condition variable. 

I can see no reason for the existence of these extra threads as all the processing should occur on the GPU asynchronously.
Our app already runs on a tight resource budget and creating so many threads for no reason is a big issue.

Is there a way to prevent this from happening? here is what I tried:

    
```
        sessionOptions = std::make_unique<Ort::SessionOptions>();
        sessionOptions->DisableMemPattern();
        sessionOptions->SetExecutionMode(ExecutionMode::ORT_SEQUENTIAL); // onnxruntime still creates extra threads!
        sessionOptions->SetInterOpNumThreads(1); // has no effect!
        ORT_CHECK(OrtSessionOptionsAppendExecutionProviderEx_DML(
            *sessionOptions,
            runtime->DMLDevice().Get(),
            runtime->D3D12InferenceQueue().Get()
        ));
         session = std::make_unique<Ort::Session>(runtime->ONNXEnv(), modelPath.c_str(), *_sessionOptions);
```

**relevant system information**:
- ONNX Runtime installed from binary (1.4.0)

**Comment by pranavsharma** [comment]
Set         sessionOptions->Set**Intra**OpNumThreads(1);
