### ISSUE TITLE
AliasWithName is not a registered function

### ISSUE THREAD

**Issue by ricklina90** [microsoft/onnxruntime#5187]
Hello,
Accroding https://github.com/facebookresearch/detectron2, I buld my pth file to my project and transfer .pth to .onnx. When I use C# to read onnx file, I meet problem like "{"[ErrorCode:Fail] Fatal error: AliasWithName is not a registered function/op"}". I also find this article https://github.com/facebookresearch/detectron2/issues/1868. Is any way and slove this problem? thank you

**Comment by pranavsharma** [comment]
Looks like a converter issue. @spandantiwari ?

**Comment by spandantiwari** [comment]
I am not sure of this is a ONNX export issue. It is unlikely that the error message is coming from the ONNX exporter. Please take a look at the ONNX doc page and make sure that the export step is indeed happening correctly. If there are some input-dependent control flow (`if` and `loops`) in the model, then you will have to script that part of the model by putting scripting decorators (as shown on the page).

**Comment by ricklina90** [comment]
Hi  
Accord this article https://github.com/facebookresearch/detectron2/issues/629, "AliasWithName" is new export feature. 
Would some one please give me some ideas to deal with it? Thank you.

**Comment by ricklina90** [comment]
Hi
Form this article https://github.com/facebookresearch/detectron2/issues/872, If need to modify the onnx format, please also consider whether Caffe2 has a registration function or other functions that are not included in onnx. Please establish a mechanism. If special definitions are added to "Caffe2" in the future, it can also be processed synchronously with "onnx". Appreciate any help from the community!

**Comment by ricklina90** [comment]
@spandantiwari Sorry to bother you. Is there a solution to provide? thank you.

**Comment by solarflarefx** [comment]
@ricklina90 Were you able to solve this problem?

**Comment by huynhloc04** [comment]
I have the same issue. Any solutions for this? Thks

**Comment by huynhloc04** [comment]
I have the same issue. Any solution for this? Thks

**Comment by ricklina90** [comment]
@solarflarefx @vitorbds @huynhloc04 Accroding https://github.com/microsoft/onnxruntime/issues/7066, Sorry, I have no solution. This issue may need write onnxruntime engineer's help.
