### ISSUE TITLE
For loop bad performance

### ISSUE THREAD

**Issue by zhuxiaoxuhit** [microsoft/onnxruntime#5188]
**Describe the bug**
I try to using onnxruntime to do inference for LPCNet model with c++ api. I transform models using https://github.com/onnx/keras-onnx/blob/master/applications/lpcnet/convert_lpcnet_to_onnx.py . Need to pay attention, there is a for loop in the decoder and its performance is very bad(very slow,using 20s to synthesize 9s audio). 
I think the problem is: we create OrtValue everytime in for loop, and this is a huge time overhead. Is there a better method?

**System information**
- OS Platform and Distribution:CentOS Linux release 7.5.1804
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master
- Visual Studio version (if applicable): None
- GCC/Compiler version: gcc (GCC) 4.8.5 
- CUDA/cuDNN version: None
- GPU model and memory: None

**To Reproduce**
Как это
```c++
// Encoder
Encoder_sess.Run()
// Decoder
for (;i < length;i++)
        for (; j < FRAME_SIZE; j++)
        {
            pred = 0.;    
            for (int k = 0;k < LPC_ORDER; k++) 
                pred -= pcm[i * FRAME_SIZE + j + k - LPC_ORDER] * lpc[i * LPC_ORDER + LPC_ORDER - k -1];
            pred_ulaw = lin2ulaw(pred);
            dec_exc[1] = pred_ulaw; 
    
            // INPUT
            Ort::Value dec_exc_ort = Ort::Value::CreateTensor<int32_t>(memory_info, dec_exc.data(), input_tensor_size_dec[0], input_node_dims_dec[0].data(), 3);    
            Ort::Value dec_feat_ort = Ort::Value::CreateTensor<float>(memory_info, dec_feat.data(), input_tensor_size_dec[1], input_node_dims_dec[1].data(), 3);    
            Ort::Value dec_state1_ort = Ort::Value::CreateTensor<float>(memory_info, dec_state1.data(), input_tensor_size_dec[2], input_node_dims_dec[2].data(), 2);    
            Ort::Value dec_state2_ort = Ort::Value::CreateTensor<float>(memory_info, dec_state2.data(), input_tensor_size_dec[3], input_node_dims_dec[3].data(), 2);    
            Ort::Value dec_input_tensors[4] = {std::move(dec_exc_ort), std::move(dec_feat_ort),std::move(dec_state1_ort), std::move(dec_state2_ort)};
    
            // DECODER SESSION RUN  
            dec_sess.Run(Ort::RunOptions{nullptr},input_node_names_dec.data(),dec_input_tensors,num_input_nodes_dec,outputs_node_names_dec.data(),output_values.data(),num_outputs_nodes_dec);    
```

**Expected behavior**
Better performance.

**Comment by snnn** [comment]
You can reuse the inputs. You don't need to create them every time.

**Comment by zhuxiaoxuhit** [comment]
> You can reuse the inputs. You don't need to create them every time.
@snnn thiank for ur quick reply. I have tried it, got error. Told me i was using value before  declaration. I think after Run() method, onnxruntime will free OrtValue. Is there example of this?

**Comment by snnn** [comment]
It depends on whether the input tensor's shape will change or not , it is constant, 

See:
https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp#L135

IYou may define the OrtValue outside of the loops. And call CreateTensorWithDataAsOrtValue only once. Inside the loop, you just change the pointed memory underneath(input_tensor_values).

**Comment by zhuxiaoxuhit** [comment]
@snnn, OK,I got it finally. But its also very slow.  Baseline LPCNet synthesizes 9s audio using only 3s, and onnxruntime need 20s... Y got this result.

**Comment by RandySheriffH** [comment]
Let's do some debugging to find out...

**Comment by zhuxiaoxuhit** [comment]
Developer of LPCNet manually optimized operations of GRU with c for inference.  It can explain this result.

**Comment by RandySheriffH** [comment]
@zhuxiaoxuhit, meaning LPCNet infers by GPU while Ort in your test is ony by CPU, right?
It the difference is reasonable, shall we close the issue?

**Comment by skottmckay** [comment]
You need to build ORT using CUDA for it to run using GPU. Comparing CPU perf for this model vs GPU is not valid, and the original lpcnet appears to have a hard dependency on running on GPU (e.g. it imports keras.layers.CuDNNGRU which is only available on GPU).

**Comment by zhuxiaoxuhit** [comment]
ALL with CPU. I mean the reason is author of LPCNet did excellent optimization for LPCNet on CPU. He optimized calculations
of Layer Embedding to GRU's  non-recurrent units, this operations are in for loop.  He pre-computed the product
of the embedding matrices with the corresponding submatrices of the GRU’s non-recurrent weights.

**Comment by zhuxiaoxuhit** [comment]
![Uploading image.png…]()

**Comment by zhuxiaoxuhit** [comment]
OK, I will close this issue. If you optimize this situation in the future, I will try it again.
