### ISSUE TITLE
Yolov3 wrong output from C API

### ISSUE THREAD

**Issue by eric-tc** [microsoft/onnxruntime#5192]
**Describe the bug**

Hi i'am trying to use Yolov3.onnx converted from ultralytics repo. I have tested it with python and inference result are fine. But when i try to use it in Cpp the vector of output of classes is always zero while the vector of boxes are ok.

This is the output if can help.

Input 0 : name=images
Input 0 : type=1
Input 0 : num_dims=4
Input 0 : dim 0=1
Input 0 : dim 1=3
Input 0 : dim 2=608
Input 0 : dim 3=608
Output 0 : name=classes
Output 0 : type=1
Output 0 : num_dims=2
Output 0 : dim 0=22743
Output 0 : dim 1=80
Output 1 : name=boxes
Output 1 : type=1
Output 1 : num_dims=2
Output 1 : dim 0=22743
Output 1 : dim 1=4 

// on output i can get tensor dimension. 
22743 80
22743 4

This is my code 

```
std::vector<Ort::Value> output_tensors = session->Run(Ort::RunOptions{nullptr}, input_node_names.data(), &input_tensor, 1, output_node_names.data(), 2);

cout << output_tensors[0].GetTensorTypeAndShapeInfo().GetShape() << endl;
cout << output_tensors[1].GetTensorTypeAndShapeInfo().GetShape() << endl;

//this values are always zero
float *classes=output_tensors[0].GetTensorMutableData<float>();
//this values are fine            
float *boxes=output_tensors[1].GetTensorMutableData<float>();

//print some values
for (int i=0;i<1000;i++){
    cout<< classes[i]<<endl; //this value are always zero while in python not
}

```

Python and Cpp load the same model and same image.
Can someone help me how to further debugging this?

Thanks

**System information**
- onnxruntime 1.4.0 
-Cpu
-Ubuntu 18.04

**Comment by eric-tc** [comment]
I found the problem was in the pre processing of image.

**Comment by MuhammadAsadJaved** [comment]
Hi @eric-tc  
                   I also want to test yolov3.onnx for the inference on image input.  Can you please share the complete c++/python code that I can use for this purpose?  As The yolov3 example (https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3) only describes image pre and post-processing steps.

**Comment by eric-tc** [comment]
Hi @MuhammadAsadJaved i will release the complete code in a few weeks. I have to finish tests for accuracy. I will update you on this thread. Or if you prefer i can update you via email.

**Comment by MuhammadAsadJaved** [comment]
> Hi @MuhammadAsadJaved i will release the complete code in a few weeks. I have to finish tests for accuracy. I will update you on this thread. Or if you prefer i can update you via email.

Waiting for the good news. Thank you so much.

**Comment by eric-tc** [comment]
Hi @MuhammadAsadJaved ,

sorry for the late reply, but if you still need the code i have released it at this link https://github.com/ai4prod/ai4prod
