### ISSUE TITLE
Inference performances decrease with number of cpus used.

### ISSUE THREAD

**Issue by maxime-louis** [microsoft/onnxruntime#5193]
Hey,

I am running inferences on a large 3d Unet. I export the net from pytorch to onnx using
```
    torch.onnx.export(model, x, "model.onnx", export_params=True, opset_version=11, do_constant_folding=True, input_names=['input'], output_names=['output'], dynamic_axes={'input': {0: 'batch_size'}, 'output': {0: 'batch_size'}})
```
and then I'm using it using the syntax
```
ort_session = onnxruntime.InferenceSession("flair_focal_2d.onnx")
def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(x)}
ort_outs = ort_session.run(None, ort_inputs)
```

I installed onnx and onnxruntime using pip, and I have open mp on my ubuntu 18 machine. This machine has 12 cores/24 threads, but **the inference time per image increases with the number of threads** (I measure that using taskset on variable number of cpus).

I was not expecting this behaviour but I'm not fully understanding how this library works. Is this expected ? 

In production, I have 200 predictions to make every time, and I am tempted to run them in a multi-threaded way (24 parallel calls to 'run' on separate threads). Do you recommend this approach other using a single inference session on all cpus (and potentially tuning a batch size) ? How can I make this procedure thread-safe and disable openmp multi-threading ?

Thanks in advance !

**Comment by snnn** [comment]
Depends on how much it increased.  For thread pool, the more threads you have, the higher scheduling cost is.

**Comment by maxime-louis** [comment]
I am doing batched inferences, batch_size=64.

Using plain torch on 12 cpus takes 6s, and this time increases when using less cpus (which is expected)

With onnxruntime, computation takes 5s on a single cpu, but 12s on 12 cpus. If it's overhead I find it strange that torch does not suffer from it.

**Comment by snnn** [comment]
Oh I see, then probably we paralleled some code that shouldn't be paralleled

**Comment by maxime-louis** [comment]
Do you have an update on this ?

**Comment by snnn** [comment]
How many threads do you have in total? It sounds you created many more threads than the CPU cores, you can make 24 parallel calls to 'run' on separate threads, but you need to disable the multiple threading code in onnxruntime first.

**Comment by maxime-louis** [comment]
I have 24 threads on my machine. I am not using any multiprocessing outside of onnx. I am doing a batched inference on a single model using onnxruntime. The odd behaviour is that using taskset to restrict the number of threads used by the python process decreases the inference time ! The less threads, the faster the inference. That is without touching at any point the onnxruntime configuration.

**Comment by snnn** [comment]
Could you please share me information to allow me reproduce your experiment?  For example, the model, a full python script. So that I can debug what happened inside.

**Comment by SaleemAkhtarAngstrom** [comment]
Hi, I'm also noticing that sess.run() is using multiple threads in the python API. Is there any way to disable this? I'd similarly like to call sess.run() in parallel (i.e. call it in different threads as I'm trying to run parallel simulations for monte-carlo analysis)
