### ISSUE TITLE
c api is about 2.3 times slower than python api

### ISSUE THREAD

**Issue by simochen** [microsoft/onnxruntime#5206]
I ran same onnx model in c and python. In C, inference time is 0.18s. In python, inference time is 0.08s. How can I fix this gap?

C code
```C
// initialize  enviroment...one enviroment per process
OrtEnv* env;
CheckStatus(g_ort->CreateEnv(ORT_LOGGING_LEVEL_WARNING, "test", &env));
// initialize session options if needed
OrtSessionOptions* session_options;
CheckStatus(g_ort->CreateSessionOptions(&session_options));
g_ort->SetIntraOpNumThreads(session_options, 1);

// Sets graph optimization level
g_ort->SetSessionGraphOptimizationLevel(session_options, ORT_ENABLE_ALL);

// create session and load model into memory
OrtSession* session;
ret = CheckStatus(g_ort->CreateSession(env, model_path, session_options, &session));

...
// inference
OrtValue* output_tensor[3];
output_tensor[0] = NULL;
output_tensor[1] = NULL;
output_tensor[2] = NULL;
// std::vector<const char*> output_node_names = {"output", "463", "482"};
g_ort->Run(session, NULL, input_node_names.data(), ort_inputs.data(), num_input_nodes, output_node_names.data(), num_output_nodes, (OrtValue**)&output_tensor);
```

python code
```python
# load model
session = ort.InferenceSession(model_path)

# inference
output = session.run(['output','463','482'], {"images": inp})
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.14.3
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.4.0
- Python version: 3.7.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): Apple LLVM version 10.0.0 (clang-1000.11.45.5)
- CUDA/cuDNN version: None
- GPU model and memory:

**Comment by yufenglee** [comment]
You specify C code to use single thread by 'g_ort->SetIntraOpNumThreads(session_options, 1);' , while Python uses multi-thread by default.

**Comment by simochen** [comment]
> You specify C code to use single thread by 'g_ort->SetIntraOpNumThreads(session_options, 1);' , while Python uses multi-thread by default.

I tried to set larger thread number, however, the inference is even slower.

**Comment by yuslepukhin** [comment]
Python spends more than 98% in the same C++ code as C API does. In the past, we had reports like this and the all ended up in nothing. Can you give us your test model?

**Comment by snnn** [comment]
I'll close it as it is stale.
