### ISSUE TITLE
Dangerous naming

### ISSUE THREAD

**Issue by xkszltl** [Microsoft/onnxruntime#521]
**Describe the bug**

This is not a "bug", but a bad design.

There's a `build.bat` file, and there's a output folder called `build`.
When I do Win+R to open output folder with `%TMP%\onnxruntime\build\`, I keep triggering the build script by accident (`%TMP%\onnxruntime\build`)

**Expected behavior**

Something like `build_win.bat`?

**Comment by snnn** [comment]
Would you mind if we change the build directory to a different path?

**Comment by xkszltl** [comment]
Personally I prefer to change `build.bat` since `build` dir almost becomes the default for cmake project

**Comment by harrysummer** [comment]
@xkszltl  To avoid executing `build.bat`, you could add an additional backslash to `build`. I just tried on my Win10 machine. Without the trailing backslash, `build.bat` will be invoked. Add the blackslash would make Win-R open the `build` folder.

**Comment by xkszltl** [comment]
Yes that's exactly what I said and why it is "dangerous" (typo sensitive)

**Comment by pranavsharma** [comment]
Closing this as it's not on our top priority list. If you feel strongly about this, please feel free to raise a PR. Thanks!
