### ISSUE TITLE
INT8 inference with TensorRT provider 

### ISSUE THREAD

**Issue by david-macleod** [microsoft/onnxruntime#5211]
I was just wondering if onnx-runtime currently (or plans to) support INT8 (quantization) using TensorRT as a provider, as this is supported by TensorRT. I noticed there are env variables we can set for FP16 but couldn't see any info on INT8.

Many thanks
David

**Comment by jywu-msft** [comment]
yes, the work to support TensorRT int8 quantization is in progress.

**Comment by david-macleod** [comment]
Great, thank you
