### ISSUE TITLE
TensoRT build.sh fails due to missing CMakeLists.txt

### ISSUE THREAD

**Issue by david-macleod** [microsoft/onnxruntime#5212]
**Describe the bug**
TensorRT build fails due to missing `CMakeLists.txt` file in `onnxruntime/cmake/external/onnx-tensorrt`. I noticed some commits had been added to `onnxruntime_providers.cmake` recently so was wondering if this might be a new issue.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.4
- Python version: 3.7
- GCC/Compiler version (if compiling from source): 7.5
- CUDA/cuDNN version: 10.2
- GPU model and memory: RTX 2080i Ti

**To Reproduce**
1. Clone the repo
2. Follow these instructions https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#tensorrt

**Expected behavior**
A successful build

**Screenshots**
![image](https://user-images.githubusercontent.com/17232877/93520846-08820180-f927-11ea-995d-9b6e9f52681a.png)

**Comment by jywu-msft** [comment]
did you clone onnxruntime repo with git clone --recursive?
onnx-tensorrt is a git submodule

**Comment by david-macleod** [comment]
This was the issue, is fixed now, thanks!
