### ISSUE TITLE
Build Error with OpenVINO build_shared_lib   

### ISSUE THREAD

**Issue by hcgprague** [microsoft/onnxruntime#5221]
**Describe the bug**

build.bat --config Release --build_shared_lib   --use_openvino GPU_FP16  --cmake_generator "Visual Studio 16 2019"
ERROR_LINK_2001

**Urgency**
 none.

**System information**
- OS Platform : Win10Pro
- ONNX Runtime installed from (source or binary):
source  , git clone onnxruntime , 2020.09.17
- ONNX Runtime version:
- Python version: 3.6.5
- Visual Studio version (if applicable): VS2019 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 
- GPU model and memory:     NVDIA 2080TI 11GB

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**
![ERROR_LINK_2001_onnxruntime_openvino202004](https://user-images.githubusercontent.com/19700407/93577834-1f7c2e80-f9cf-11ea-94db-24effd1a2669.PNG)

**Additional context**
Installed OpenVino 2020.04

Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by jywu-msft** [comment]
@smkarlap , @suryasidd FYI

**Comment by MaajidKhan** [comment]
@hcgprague we don't see the same issue on our side. we are able to build it successfully.

Let me share the detailed steps to build the OnnxRT_OpenVINO_ExecutionProvider:

**It's advised to use the VS Native Tools command prompt**

**step 1:** 
Open the terminal and Initialize the openvino_2020.4 binary.
> cd C:\Program Files (x86)\IntelSWTools\openvino_2020.4.287\bin\
> **setupvars.bat**

Now the OpenVINO Environment is Initialized

**step 2:** 
Navigate to the directory or place where you want to clone the repository
> git clone https://github.com/intel/onnxruntime.git
> cd onnxruntime
> git submodule update --init --recursive

**step 3:**
Build the OnnxRuntime UEP Repository
> build.bat --config Release --build_shared_lib --use_openvino GPU_FP16 --cmake_generator "Visual Studio 16 2019"

Here's the screenshot of where the build is complete without any errors:
![image](https://user-images.githubusercontent.com/29036417/94662632-4d923480-0326-11eb-85cb-541deb23c672.png)

on the same note, OnnxRuntime Execution Provider for OpenVINO and for GPU build only works on Intel's Integarted GPU.
To check if your machine has an iGPU, follow the steps given below:
-> Right click on your desktop and select Display Settings and then select Advanced Display settings from the bottom of the page.
-> you should see **Intel(R) UHD Graphics** there in the display information section
![image](https://user-images.githubusercontent.com/29036417/94664018-04db7b00-0328-11eb-9718-6336714e1225.png)

Thanks.
