### ISSUE TITLE
使用onnxruntime_cxx_api.设置了多线程,当同时使用fasterrcnn和yolov3时候会报错.

### ISSUE THREAD

**Issue by pangchao-git** [microsoft/onnxruntime#5234]
1 使用了官方给的onnxruntime_cxx_api.cpp文件做了封装,main函数下使用了四个线程,两个跑yolov3模型,两个跑FasterRcnn模型,当独两线程跑yolov3或者Fasterrcnn模型时候没问题,但是开两个线程,一个跑yolov3,一个跑faster rcnn模型就会报错

terminate called after throwing an instance of 'Ort::Exception'
  what():  Got invalid dimensions for input: 000_net for the following indices
 index: 2 Got: 800 Expected: 416
 index: 3 Got: 1184 Expected: 416
 Please fix either the inputs or the model.
Aborted (core dumped)
可以帮忙看看是哪里的问题么.

**Comment by tianleiwu** [comment]
@pangchao-git, 错误在于输入数据的大小和模型不匹配。能否共享测试代码（不需要模型）让我们可以复现这个问题？

The error indicates that the input for model 000_net does not have correct shape. Could you debug it (like print the shape that used in inference run) to see whether the input  shape is correct.

Did you use one session object per thread, or one session object per model? What version of onnx runtime did you use?

Please share your code snippet that could reproduce the issue.

**Comment by pangchao-git** [comment]
好的,测试代码:链接：https://pan.baidu.com/s/1C61lhDeR8SpKCWorVDX7TQ 密码：hngm

**Comment by pangchao-git** [comment]
已经解决,是我这边业务代码的问题

**Comment by MuhammadAsadJaved** [comment]
I have the same problem while running my own Yolov3 model. My model takes two inputs (visible and infrared image).  Have you resolved the issue ? @pangchao-git
