### ISSUE TITLE
Website not working in China

### ISSUE THREAD

**Issue by xkszltl** [microsoft/onnxruntime#5235]
**Describe the bug**

https://microsoft.github.io/onnxruntime/
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/5203025/93773473-c6bcc800-fc52-11ea-9fb7-51f1f8cfc0b7.png">

This table doesn't work in China.
It's not clickable.
It's fine when visited from US.

It has been like this since the first time I found this page.

**Comment by xkszltl** [comment]
FYI it's because you''re using google apis to get jquery.
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/5203025/94089941-f2a09f00-fe46-11ea-9da5-6db02cf03754.png">

**Comment by tianleiwu** [comment]
@xkszltl, thanks for the information.

**Comment by xkszltl** [comment]
Any news?

**Comment by lenisha** [comment]
need to switch jquery..min.js to be linked from non google CDN:
https://code.jquery.com/
```
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
  crossorigin="anonymous"></script>
  ```

**Comment by lenisha** [comment]
@faxu it looks like pages also include links to load fonts from google - we could further optimize it by hosting at our CDN https://sia.codes/posts/making-google-fonts-faster/

**Comment by faxu** [comment]
@xkszltl please reactivate if there are still issues
