### ISSUE TITLE
Wrong Type for C.InferenceSession()

### ISSUE THREAD

**Issue by wppply** [microsoft/onnxruntime#5243]
**Describe the bug**

In your code, you calling the`C.inferenceSession() ` with this api all the time 
```
/anaconda3/envs/tf115/lib/python3.7/site-packages/onnxruntime/capi/session.py in _create_inference_session(self, providers, provider_options)
    198         session_options = self._sess_options if self._sess_options else C.get_default_session_options()
    199         if self._model_path:
--> 200             sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    201         else:
    202             sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
```

Meanwhile, this func required
```
    1. onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession(arg0: onnxruntime.capi.onnxruntime_pybind11_state.SessionOptions, arg1: str, arg2: bool)

```
**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac os
- ONNX Runtime installed from (source or binary):  `pip install -i https://test.pypi.org/simple/ ort-nightly`
- ONNX Runtime version: nightly 9/21/2020
- Python version: 3.7
- Visual Studio version (if applicable): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by hariharans29** [comment]
Please fill in the issue template. 

How did you build the onnxruntime module ? 

Current master looks fine - https://github.com/microsoft/onnxruntime/blob/038192bdb28d9b6a4012e36546590936f47a652d/onnxruntime/python/onnxruntime_pybind_state.cc#L1291

**Comment by wppply** [comment]
@hariharans29 Thanks for your quick reply.
I build the ort by `pip install -i https://test.pypi.org/simple/ ort-nightly`
I also tried to git clone the repo and `./build.sh --config RelWithDebInfo --build_shared_lib --parallel --build_wheel` 
and I tried `onnxruntime build > Linux > RelWithDebInfo > $  python onnxruntime/setup.py bdist_wheel`. Still getting the same error, though the pybind api seems make sense

**Comment by hariharans29** [comment]
It seems like it is using the latest session.py but loading the stale version of the onnxruntime pybind .so thus causing the mis-match.

**Comment by wppply** [comment]
yes, you are right. fixed by manually deleting the package.
