### ISSUE TITLE
Conv transpose not supported

### ISSUE THREAD

**Issue by maxime-louis** [microsoft/onnxruntime#5249]
Hey,

I'm converting a pytorch 3D unet to onnx using torch.onnx (torch 1.5.1). This network contains convtranspose 3d operations.
The export operation goes fine but then I run into an issue when running inference with onnxruntime 1.3.0:
`2020-09-22 07:42:42.288815707 [E:onnxruntime:, sequential_executor.cc:281 Execute] Non-zero status code returned while running ConvTranspose node. Name:'ConvTranspose_69' Status Message: Only 1D and 2D ConvTranspose is supported. X: {1,128,10,12,10}`

The inference however succeeds for onnxruntime 1.4.0, but I cannot install onnxruntime 1.4.0 using pip on all of my environments (in some contexts, only 1.3 is available).

Do you have a fix for that ?

**Comment by snnn** [comment]
Have you tried 
```bash
python3 -m pip install --upgrade pip
```
Then 
```bash
python3 -m pip install --upgrade onnxruntime
```
?

**Comment by maxime-louis** [comment]
It does fix my issue thanks !
