### ISSUE TITLE
Poor Performance on  bit/m-r101x1 (TF=275ms, ONNX=598ms)

### ISSUE THREAD

**Issue by TomWildenhain-Microsoft** [microsoft/onnxruntime#5253]
**Describe the bug**
On Google's BiT-M R101x1 model ONNX is significantly slower than TF.  The converted model (converted with tf2onnx) takes 598 ms per inference while TF takes 275 ms.  I'm running on CPU.

**Urgency**
Medium.  Required for OKR target.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows**
- ONNX Runtime installed from (source or binary): **Binary (pypi)**
- ONNX Runtime version: **1.4.0**
- Python version: **3.7.8**
- Visual Studio version (if applicable): **2019**

**To Reproduce**
- Download https://www.dropbox.com/s/xfb8dn2le421rk3/perf_test_bit-m-r101x1.zip?dl=1
- Run **perf_test_portable.py**

**Expected behavior**
ONNX is faster than TF

**Comment by xadupre** [comment]
I compiled onnxruntime, release with debug information then used py-spy to profile:

``py-spy record -r 5 -o profile.svg --native -- python perf_test_portable.py``

![image](https://user-images.githubusercontent.com/22452781/94046947-a5ceb100-fdd1-11ea-960e-a3bfa8978cc9.png)

onnxruntime spends some time in PrepareForReduce. It may be optimized.

**Comment by mrry** [comment]
@xadupre Could you also share the full output from the profiler? I'd be curious to see how the 70% of time outside `SequentialExecutor::Execute()` breaks down.

(+1 to it being suspicious that `PrepareForReduce()` is taking a lot of time, but there must be something else to account for the difference between ORT and TF!)

**Comment by TomWildenhain-Microsoft** [comment]
[profile.zip](https://github.com/microsoft/onnxruntime/files/5285410/profile.zip)
Here is the full profile information.  The script runs both TF and ONNX so only 30% of the time is ONNX.  The rest is loading and TF.

**Comment by mrry** [comment]
Thanks! In that case I don't have anything particular to add... it looks like element-by-element transpose in `PrepareForReduce()` is the long pole here (if the line numbers can be trusted).

It's not obvious from the profile whether the operators are intra-op parallelized. I don't see any other threads in the profile, but I do see 2.6% of the total cycles spent on this line:

https://github.com/microsoft/onnxruntime/blob/9cec98ec1bcb6b8a668733fcd00d81af61b44d93/include/onnxruntime/core/platform/EigenNonBlockingThreadPool.h#L619

Perhaps if we're not using intra-op parallelism there's a possible micro-optimization that avoids calling `Wait()` when the work is handled synchronously? (@tlh20 Does that sound likely?)

If we are using intra-op parallelism, it might be necessary to gather a profile with all threads to track down the problem (and then it might also worthwhile to separate out the ORT and TensorFlow execution into different runs and grab a few more samples).

**Comment by tlh20** [comment]
It's unexpected if we see costs there @mrry but no threading.  If we are not parallelising the work then we pull out the special cases earlier and run sequentially https://github.com/microsoft/onnxruntime/blob/9cec98ec1bcb6b8a668733fcd00d81af61b44d93/include/onnxruntime/core/platform/EigenNonBlockingThreadPool.h#L553-L555

**Comment by tlh20** [comment]
Looking into this some more, we don't seem to be spending much time inside parallel sections.  Measuring just the ORT perf section here, I see ~25% of wall-clock time at 4 threads.  I am not sure if that is operators that we are not parallelizing, or some other sequential work outside the basic graph execution.

In more detail:

1. I added some more profiling to the test case to record CPU load via time.process_time() before and after each series of inference requests.  From 
 [tiharr-log-1.txt](https://github.com/microsoft/onnxruntime/files/5305014/tiharr-log-1.txt) I'm seeing load of ~4 in ORT and ~4.8 in PT.  This reflects the ORT default on my desktop machine with 8 h/w threads and 4 cores.  I experimented with increasing the ORT thread count in case we could improve performance via hyperthreading.  I tested with 1..8.  We don't get any further benefit going beyond 4 threads.  We get a slight benefit pulling back to 2 threads (~320ms vs ~350ms).

2. I added some more extra profiling from branch https://github.com/microsoft/onnxruntime/tree/tiharr/threading-test.  This enables collection of extra statistics of how ORT parallelizes loops.  See the lines starting "intra-op" in the log, repeated here:

~~~~
intra-op id: 2 ran_own: 39383 ran_stolen: 0 tried_to_block: 64 blocked: 63 wall_ms: 69636 busy_ms: 8940 spin_ms: 25870 blocked_ms: 34689
intra-op id: 1 ran_own: 39382 ran_stolen: 0 tried_to_block: 70 blocked: 69 wall_ms: 69636 busy_ms: 8991 spin_ms: 25807 blocked_ms: 34708
intra-op id: 0 ran_own: 39371 ran_stolen: 0 tried_to_block: 75 blocked: 74 wall_ms: 69638 busy_ms: 8996 spin_ms: 25790 blocked_ms: 34718
intra-op num_tasks_rejected: 0 stand_alone_tasks: 0 parallel_tasks: 39390 mean_d_o_p: 4 total_scheduled: 118170 total_revoked: 34
intra-op time_pre_ms: 92 time_running_ms: 8721 time_post_ms: 79 time_waiting_ms: 970
~~~~

There is one line for each thread in the pool (0, 1, 2), plus a separate line for overall statistics and work done in the main thread.  The ORT part of the workload is taking 34.7s (ref the main ONNX wall ms result), but we are only spending 8.7s inside parallel sections (time_running_ms).

**Comment by tlh20** [comment]
BTW, I concur with the sequential blocksize=1 case in PrepareForReduce being significant here.  ReduceMean stands out in the edge://tracing/ profiling.  Breaking down the time there via extra rdtsc calls shows ~90% of those operators being in the prepare step for this workload.  I do not have enough context on how the reductions work to know whether we should be parallelizing the PrepareForReduce, or looking to combine the transformation there with the actual reduction, or something else.

**Comment by xadupre** [comment]
I compared to numpy and tensorflow implementation. The ratio is good if the reduction happens on the last axes. When the reduction happens before, the matrix is transposed to move reduced dimensions to the last positions. The reduction is faster when it is done on the last axis but the transposition increases the processing time.

![image](https://user-images.githubusercontent.com/22452781/94874464-5b44d880-0452-11eb-9252-3778a4cf3e77.png)
