### ISSUE TITLE
Error "no kernel image is available for execution on the device" raised on Jetson axvier nx

### ISSUE THREAD

**Issue by ping28198** [microsoft/onnxruntime#5282]
**Describe the bug**
raised error "no kernel image is available for execution on the device" on device jetson axvier nx, when use CUDAExcutationProvider. The onnxruntime library is built using both "--use_cuda" and "--use_tensorrt" cmd.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.14.0
- Python version: 3.6.9
- Visual Studio version (if applicable): none
- GCC/Compiler version (if compiling from source):  7.5
- CUDA/cuDNN version: 10.2
- GPU model and memory: jetson axvier nx

**Comment by tianleiwu** [comment]
It saw a similar issue in NVidia forum:
https://forums.developer.nvidia.com/t/opencv-cuda-no-kernel-image-is-available/139596/3

@ping28198, could you try cuDNN 8.0, and  build with sm_72 (for example, add a line after the following):
https://github.com/microsoft/onnxruntime/blob/3a3f26f38e049eb0e8b9fbb97281a6e5dd82074f/cmake/CMakeLists.txt#L1066

**Comment by stevenlix** [comment]
If you are using JatPack4.4, it already has CuDNN8.0 and TensorRT7.1.3. You mentioned the issue occurs when you run CUDA EP. Can you run TensorRT EP? Could you also try latest ORT master? If the issue persists, it would be better if you could share your model.

**Comment by jywu-msft** [comment]
> There is a similar issue in NVidia forum:
> https://forums.developer.nvidia.com/t/opencv-cuda-no-kernel-image-is-available/139596/3
> 
> @ping28198, could you try cuDNN 8.0, and build with sm_72 (for example, add a line after the following):
> https://github.com/microsoft/onnxruntime/blob/3a3f26f38e049eb0e8b9fbb97281a6e5dd82074f/cmake/CMakeLists.txt#L1066

this should not be required, if you are building latest master on Jetson Xavier NX.
see: https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L1063
