### ISSUE TITLE
Memory increases without limit while in an infference session.

### ISSUE THREAD

**Issue by fco-jle** [microsoft/onnxruntime#5292]
**Describe the bug**
When running an infference session to make predictions on a dataset, the memory usage keeps increasing without limit. 

The model is a LightGBM binary classifier trained in python, converted to onnx and used for inference in C#.

**Urgency**
We would like to deal with this issue as soon as possible, it is currently blocking development, and due to the memory usage it is impossible for us to send the application to production stage. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window 10 64
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.4.0 (Nuget package)
- Python version: 3.6.7 (Onnx version on python is 1.7)
- Visual Studio version (if applicable): VS Proffesional 2019 16.4.11
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**

Using a lightgbm model converted to onnx with path ModelPath and number of features nFeatures, get predictions on nSamples random tensors:

-----------------------------------------------------------------------
           ` var rand = new Random();
            using (var session = new InferenceSession(ModelPath))
            {
                var bufferInput = new float[nFeatures];
                var tensorInput = new DenseTensor<float>(bufferInput, new int[] { 1, nFeatures });

                using (FixedBufferOnnxValue valueInput = FixedBufferOnnxValue.CreateFromTensor(tensorInput))
                {
                    var inputNames = new[] { "input" };
                    var inputValues = new[] { valueInput };

                    for (var i = 0; i < nSamples; i++)
                    {
                        var inputs = Enumerable.Range(0, nFeatures).Select(x => (float)rand.Next(20, 150)).ToArray();
                        inputs.CopyTo(bufferInput, 0);
                        var result = session.Run(inputNames, inputValues);
                    }
                }
            }`

-----------------------------------------------------------------------

**Expected behavior**
Flat memory usage, not increasing over time each time session.Run() is executed.

**Screenshots**
![grow](https://user-images.githubusercontent.com/43389604/94253575-cdcf2900-ff25-11ea-977f-c432dcaf38ad.JPG)

**Additional context**
Due to company restrictions, I can't freely share the trained model. But, the model is a binary classifier with 137 features, and it has been trained in python using lightgbm, model parameters are:

n_estimators=2000, 
num_leaves=6, 
max_depth=-1
min_child_samples=20, 
subsample=0.5, 
subsample_freq=5, 
colsample_bytree=0.75, 
reg_alpha=1, 
reg_lambda=4

I have tried several other models trained with the same data, but different configuration of parameters, and number of features, in case the issue was caused by model complexity. The same effect happens when using any of this models.

**Comment by RandySheriffH** [comment]
The team also noticed the memory issue recently both from internal and external channels.  I am looking at https://github.com/microsoft/onnxruntime/issues/5176. May combine your case along the way.

**Comment by yuslepukhin** [comment]
The result that is returned from Run() call are IDisposables that hold pointers to the natively allocated memory. If you do not dispose them, they will continue to accumulate allocated memory.

**Comment by RandySheriffH** [comment]
@fco-jle: please confirm if or not disposal of the result solve your problem.

**Comment by fco-jle** [comment]
Thank you for your answers. 

We tried the suggested solution, doing something along the lines:

`var result = session.Run(inputNames, inputValues);
{Do something with result}
 result.Dispose();`

But it did not solve the issue, the memory keeps increasing. 

Our team have noticed that the memory increase has to do with the use of Zipmaps, and it seems that, when the model is being converted and saved in python, setting the zipmap option to False has improved performance and solve the memory issue in C#.

So we believe that the memory leak is related to the use of Zipmap. It might be worth mentioning that the regression models that we are using do not cause the memory leak, even with the use of zipmaps, so it might be related only to the classification output.  

We are still testing.

**Comment by RandySheriffH** [comment]
@fco-jle: thanks for confirmation and all the details.

**Comment by vade** [comment]
Hi. New to ONNX runtime and I am also seeing memory increase linearly in a inference session using python.

Is this Zipmap solution part of ONNX model conversion, or a runtime flag I can't seem to find? Looking to not leak :)

**Comment by vade** [comment]
hey @rsomani95 - I'm noticing similar ONNX runtime memory leakage in a Ubuntu docker running CPU inference - will test GPU inference too. Are you aware of this leak, and if so, can you try an ONNX model export from pytorch that doesn't have Zipmap enabled (if possible)? Im not entirely clear if that's a thing we control :)

**Comment by rsomani95** [comment]
Hey @vade, first time I'm hearing of this. I'd never heard of Zipmap until now, and it certainly looks like this is not a part of the conversion process, don't see anything about it in the [PyTorch docs](https://pytorch.org/docs/stable/onnx.html#operator-export-type) either

**Comment by rsomani95** [comment]
@fco-jle what framework did you export the model from? If PyTorch, is there a specific `opset_version` that you used to alleviate the issue, or any other export param? Would appreciate any input, thanks!

**Comment by vade** [comment]
Seems my memory issue was a subtle issue on my end - using multiple threads along with generators seems to act poorly or I'm misunderstanding a subtlety of python (not a python dev). running serial inference shows acceptable, expected memory usage.

**Comment by RandySheriffH** [comment]
@fco-jle: Would u mind either confirm the dispose + GC.collect() approch or somehow share maybe a sample model for further investigation? Like stated in https://github.com/microsoft/onnxruntime/issues/5176, there is unlikely any native leaks from ORT.

**Comment by fco-jle** [comment]
@vade , The zipmap option is used in the sklearn framework.

First, we loaded the booster with lightgbm, then we used the sklearn API of lightgbm to do: 

```
initial_type = initial_types=[('input', FloatTensorType([1, n_cols]))]
options = {id(model): {'zipmap': False}};
onnx = convert_sklearn(model, initial_types=initial_type, options=options)
```

@RandySheriffH, before we tried this zipmap option set to false, we tried to  dispose the result and call gc.collect(). It works and leaves memory flat, but (at least in our case) we cannot use it, since it increases running time of the program by a lot, which we cannot afford.

**Comment by RandySheriffH** [comment]
@fco-jle thanks for confirmation.
Then it again proved that we have no actual leaks to cope with.
And of course you don't need to call GC.collect() in real production, just let it do its job with some patience.
On certain condition for sure it will unleash resources to bring down memory pressure.

**Comment by kbrajwani** [comment]
@RandySheriffH  @rsomani95 Hey i am facing same issue . i am using this repo https://github.com/iiLaurens/CascadeTabNet/tree/mmdet2x model weights. I have converted  model with mmdet liabrary into onnx.
It's increasing gpu memory at every inference time. i tried torch.cuda.empty_cache() and gc.collect() but nothings works.

**Comment by kbrajwani** [comment]
@cqray1990 i had stop using onnxruntime and go back to pytorch where it will only increase the memory when it's doing inference and then it come down.
