### ISSUE TITLE
Onnx GPU runtime fails to fallback to CPU when GPU is not available OR busy.

### ISSUE THREAD

**Issue by vladbph** [microsoft/onnxruntime#5299]
**Describe the bug**
Onnx GPU runtime fails to fallback to CPU when GPU is not available OR busy.
As suggested here: https://github.com/microsoft/onnxruntime/issues/486#issuecomment-698879600 raising an issue.

**Urgency**
This is a showstopper for running models deployed into production serving more than one model. There are multiple reason why GPU may be present but not available. The current implementation of onnx runtime prevents running production models due to the lack of such support(hope it is a bug).

**System information**
- Linux Ubuntu 16.04:
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.4.0
- Python version: 3.7
- CUDA/cuDNN version: any supported
- GPU model and memory: any supported

**To Reproduce**
Run the notebook:
 https://colab.research.google.com/drive/11ISt8zaGOKaLWCdsRcapcM9Cme109Zwq?usp=sharing

NOTE! notebook is configured without GPU to simulate the case when GPU's being busy. Verified locally that in both cases the same exception is raised.

**Expected behavior**
When onnxruntime-gpu is installed, session creation must fallback to CPUExecutionProvider, if/when:
 - GPU is not available at all
 - GPU is busy running other models

**Comment by pranavsharma** [comment]
We don't support this today in the core infra. Based on the order in which the user registers various EPs with ORT and the results obtained from GetCapability, we mark various nodes of the graph with the EPs that will service them. This is done during the initialization stage only once. When Run() is called after this, we expect the EPs to be available. If execution fails due to an exception coming from an EP, you should be able to recreate the session without the cuda EP and call Run() again. This is what we do in the [Python API layer] 
(https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/session.py#L122-L131).

**Comment by vladbph** [comment]
Could you provide an example how to recreate session with CPUExecutionProvider when GPU fails?

**Comment by pranavsharma** [comment]
Calling session.set_providers(['CPUExecutionProvider']) should suffice. See onnxruntime\test\python\onnxruntime_test_python.py for examples.

**Comment by vladbph** [comment]
> Calling session.set_providers(['CPUExecutionProvider']) should suffice. See onnxruntime\test\python\onnxruntime_test_python.py for examples.

well, I don't have session object because InferenceSession throws an exception...

**Comment by pranavsharma** [comment]
Then just re-create the session. 
            import onnxruntime as onnxrt
            sess = onnxrt.InferenceSession("foo.onnx")
            sess.set_providers(['CPUExecutionProvider'])

**Comment by vladbph** [comment]
> Then just re-create the session.
> import onnxruntime as onnxrt
> sess = onnxrt.InferenceSession("foo.onnx")
> sess.set_providers(['CPUExecutionProvider'])

Hmmm...
sess = onnxrt.InferenceSession("foo.onnx") 
throws an exception.....

**Comment by pranavsharma** [comment]
sess = onnxrt.InferenceSession("foo.onnx", providers=['CPUExecutionProvider']) should work.

**Comment by vladbph** [comment]
Good! that works... 
which brings the original question, especially after looking the the code, why don't you do it inside the class implementation?

**Comment by pranavsharma** [comment]
Sure, we could potentially surround [this line](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/session.py#L195) with a try/catch and do the fallback. Would you like to contribute? Thanks!

**Comment by vladbph** [comment]
> Sure, we could potentially surround [this line](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/session.py#L195) with a try/catch and do the fallback. Would you like to contribute? Thanks!

Sure

**Comment by livneros** [comment]
Is there a way to merge those changes into version 1.4.0?
