### ISSUE TITLE
Support linking with full MKL instead of MKLML

### ISSUE THREAD

**Issue by harrysummer** [Microsoft/onnxruntime#530]
I am trying to use ONNX Runtime in different environments, which could be maximize for speed (need multi-thread execution) or running under multi-thread caller (need single-thread execution). Therefore, I want to link with full MKL library (with mkl_rt which could decide the threading layer at runtime) instead of MKL-ML, which only provides a OpenMP-based implementation. 

In detail, I would like to have additional build parameteres `--use_mkl` and `--mkl_path`. `--use_mkl` is mutually exclusive with `--use_mklml`. When `--use_mkl` is defined, the building script will take the value of `--mkl_path` as the root path for MKL library. And the following two things change:

1. MKL-DNN will be linked with MKL instead of MKLML. The library name should be mkl_rt instead of mklml. `MKLDNN_USE_MKL=FULL` should be added to the arguments of cmake configuring step of MKL-DNN.
2. Eigen is linked with MKL. `EIGEN_USE_MKL_ALL` is defined in all compilation flags.

I am currently working on supporting this. Any comment / feedback is welcomed.

UPDATE: After some intial trials and investigation, 2 might not be a good idea. ONNX Runtime already carefully treated the BLAS functions and uses MLAS by default without touching those Eigen BLAS implementations. Besides, there would be a lot of compiling redefinition errors if this macro is introduced.

UPDATE2: Investigate more on the omp threading problem. It turns out that the default build uses MLAS as blas layer, and on my Windows PC, the MLAS uses Windows threading layer instead of OMP. This is the reason that `OMP_NUM_THREADS` didn't work for me. Therefore, I decide to continue using OMP build with `omp_set_num_threads(1)`. So a full MKL build is not required for me anymore. For other guys that are interested in a MKL build, this is the patch I used:
[mkl_patch.txt](https://github.com/Microsoft/onnxruntime/files/2917554/mkl_patch.txt)

**Comment by snnn** [comment]
In which case,  mklml is needed? And why mkl is better than mklml in your scenario?

**Comment by harrysummer** [comment]
I think the main scenario for users to consider MKL instead of MKLML is when they want to link a sequential MKL library instead of an OpenMP one. I am not sure if it is equivalent to use OpenMP build with `OMP_NUM_THREADS=1`. I am using OMP with therad number equals 1 for now.

**Comment by harrysummer** [comment]
Let's close this issue for now, as I worked-around it in another way.

**Comment by snnn** [comment]
I tried, you can choose mkl. No change is needed.

**Comment by harrysummer** [comment]
@snnn How's "choose mkl" been done? Apparently not using `--use_mklml` argument in `build.py`. And from [here](https://github.com/Microsoft/onnxruntime/blob/master/cmake/external/mkldnn.cmake), I don't see any MKL library been linked.

**Comment by snnn** [comment]
Just install mkl. And don't use --use_mklml.

**Comment by whutbd** [comment]
in the url:https://github.com/microsoft/onnxruntime/releases/download/v1.16.0/onnxruntime-osx-x86_64-1.16.0.tgz

the so file not use mkl?

**Comment by whutbd** [comment]
> Just install mkl. And don't use --use_mklml.

in the url:https://github.com/microsoft/onnxruntime/releases/download/v1.16.0/onnxruntime-osx-x86_64-1.16.0.tgz

the so file not use mkl?
