### ISSUE TITLE
Conflicts between "--minimal_build" and "--use_nnapi"

### ISSUE THREAD

**Issue by jokerz0624** [microsoft/onnxruntime#5322]
**Describe the bug**
Since I want to run inference with NNAPI on my android app, I need to build an onnxruntime.so first. To limit the size of my app, I choose the minimal build provided. 
It works when I build with the following instruction:

./build.sh --android --android_sdk_path /Users/joker/Library/Android/sdk --android_ndk_path /Users/joker/Library/Android/ndk/android-ndk-r21b --android_abi arm64-v8a --android_api 28 --parallel --build_shared_lib --config=MinSizeRel --minimal_build --disable_ml_ops --disable_exceptions --android_cpp_shared

However, it does not work when I add "--use_nnapi" in the end:

./build.sh --android --android_sdk_path /Users/joker/Library/Android/sdk --android_ndk_path /Users/joker/Library/Android/ndk/android-ndk-r21b --android_abi arm64-v8a --android_api 28 --parallel --build_shared_lib --config=MinSizeRel --minimal_build --disable_ml_ops --disable_exceptions --android_cpp_shared --use_nnapi

**Urgency**
 none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS 10.15
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.4.0
- Python version: 3.8.2
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:
- Android NDK version: r21b
- Android SDK version: 29

**To Reproduce**
- git clone the source code of this project
- build with the following instruction:
./build.sh --android --android_sdk_path /Users/joker/Library/Android/sdk --android_ndk_path /Users/joker/Library/Android/ndk/android-ndk-r21b --android_abi arm64-v8a --android_api 28 --parallel --build_shared_lib --config=MinSizeRel --minimal_build --disable_ml_ops --disable_exceptions --android_cpp_shared --use_nnapi

**Additional context**
Here is the error info:
[ 86%] Building CXX object CMakeFiles/onnxruntime_providers.dir/Users/joker/Documents/onnx/onnxruntime/onnxruntime/contrib_ops/cpu/trilu.cc.o
[ 86%] Building CXX object CMakeFiles/onnxruntime_providers.dir/Users/joker/Documents/onnx/onnxruntime/onnxruntime/contrib_ops/cpu/unique.cc.o
[ 87%] Building CXX object CMakeFiles/onnxruntime_providers.dir/Users/joker/Documents/onnx/onnxruntime/onnxruntime/contrib_ops/cpu/word_conv_embedding.cc.o
[ 87%] Linking CXX static library libonnxruntime_providers.a
[ 87%] Built target onnxruntime_providers
make: *** [all] Error 2
Traceback (most recent call last):
  File "/Users/joker/Documents/onnx/onnxruntime/tools/ci_build/build.py", line 1866, in <module>
    sys.exit(main())
  File "/Users/joker/Documents/onnx/onnxruntime/tools/ci_build/build.py", line 1804, in main
    build_targets(args, cmake_path, build_dir, configs, args.parallel, args.target)
  File "/Users/joker/Documents/onnx/onnxruntime/tools/ci_build/build.py", line 950, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/Users/joker/Documents/onnx/onnxruntime/tools/ci_build/build.py", line 447, in run_subprocess
    completed_process = subprocess.run(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Applications/CMake.app/Contents/bin/cmake', '--build', '/Users/joker/Documents/onnx/onnxruntime/build/Linux/MinSizeRel', '--config', 'MinSizeRel', '--', '-j8']' returned non-zero exit status 2.

**Comment by gwang-msft** [comment]
For now we do not support NNAPI execution provider in minimal onnxruntime build, see https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_for_Mobile_Platforms.md#limitations

**Comment by jokerz0624** [comment]
> For now we do not support NNAPI execution provider in minimal onnxruntime build, see [limitations](https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_for_Mobile_Platforms.md#limitations)
> 
> For now if you want to use NNAPI execution provider on Android you need to use a full onnxruntime build.

I got it. Thanks!
