### ISSUE TITLE
Error while loading large model (protobug > 2 Gb) in C#

### ISSUE THREAD

**Issue by shuagr** [microsoft/onnxruntime#5329]
**Describe the bug**
[ErrorCode:Fail] Deserialize tensor transformer.h.8.attn.bias failed.GetFileSizeEx C:\Users\shuagr.REDMOND\Desktop\onnx_beam_search\test2\QuestionGeneration\UnitTest\bin\x64\Debug\transformer.h.8.attn.bias fail, errcode = 6
^ it gives the following erro while loading a 48 layer model with protobuf limit > 2Gb ( so the model is saved with its attention weights)
It works correctly in pytorch but gives error in C#
**Urgency**
This is an urgent issue for our team( need it for product shipping) and would appreciate if it could be resolved as soon as possible. 
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): nuget.org
- ONNX Runtime version: 1.4.0
- Python version: 1.6.1
- Visual Studio version (if applicable): 2020
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: testing on CPU

**To Reproduce**
- Describe steps/code to reproduce the behavior.
Try to create an onnx model for large model (1.5B GPT2 style model) using convert_to_onnx.py script here https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/transformers
Then try to run onnx file in C# using a basic inference session and tokens

- Attach the ONNX model to the issue (where applicable) to expedite investigation.
It's a Microsoft internal model. So, can't share details unless you have proper approval. But the process defined above should result in a similar model.

**Expected behavior**
I expect the C# to load the model and run since the onnx model is working in python.

**Comment by snnn** [comment]
The error says "The handle is invalid. ". So onnxruntime failed to open the model file. 

Can you set a break point at :
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/platform/windows/env.cc#L234

And tell me what happened there?

**Comment by shuagr** [comment]
The file path seems to be correct. I manually verified the file path mentioned in the error. I don't know why it isn't able to open the file

**Comment by snnn** [comment]
@tianleiwu, can you help us reproduce the error?

**Comment by shuagr** [comment]
I have messaged @tianleiwu with the steps to reproduce the exact same set up. Hope it helps

**Comment by snnn** [comment]
I'll do a small change now, hope it will be helpful.

**Comment by tianleiwu** [comment]
@shuagr, I cannot reproduce the issue. C# API works well for a model with external data in my machine.

**Comment by shuagr** [comment]
I have shared the exact model and code with you. Are you able to run that model in C#? Preferably with the same the code, otherwise at least the same model

**Comment by tianleiwu** [comment]
See https://github.com/microsoft/onnxruntime/issues/5418 for one possible cause that / is used in path in Windows.
