### ISSUE TITLE
Build error "No Cuda toolset found" on Windows 10

### ISSUE THREAD

**Issue by blgnksy** [microsoft/onnxruntime#5336]
**Describe the bug**
I'm trying to build onnxruntime from source on Windows 10. However I provided the correct cuda and cudnn home folders correctly, build process has finished with "No CUDA toolset found" error.

**System information**
- OS Platform and Distribution: Windows 10 (OS Build 19041.508)
- ONNX Runtime installed from (source or binary): Binary 
- ONNX Runtime version: 1.5.1
- Python version: 3.8.6
- CUDA/cuDNN version: 10.2/8.0.4
- GPU model and memory: Quadro RTX 4000

**To Reproduce**
`build.bat --cmake_generator "Visual Studio 16 2019" --config Release --build_shared_lib --parallel --use_cuda --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2" `

**Comment by snnn** [comment]
Please:
1. uninstall your CUDA SDK and reinstall it with full installation, please double check if "Visual Studio extension" was included in the installation

2. And add "--cuda_version 10.2" to build.bat's arguments.

**Comment by blgnksy** [comment]
@snnn Thank you for your reply. Unfortunately, it didn't solve the problem. I got **a new error** that is "No CMAKE_CUDA_COMPILER could be found." My cuda compiler(nvcc) is accessible from system paths and.

**Comment by snnn** [comment]
Could you please tell us your:
1. Visual Studio version
2. cmake version

Do you have multiple Visual Studio installation?

**Comment by blgnksy** [comment]
Visual Studio version: Community 2018(2)  16.7.5
Cmake version: 3.18.2

I have only one Visual Studio installed on my machine.
