### ISSUE TITLE
onnxruntime runs inference on CPU even though GPU is available

### ISSUE THREAD

**Issue by braaannigan** [microsoft/onnxruntime#5337]
**Describe the bug**
I have built a transformer model from huggingface and can do inference on a CPU. However, when I run the same model with a GPU available the inference runs on CPU.  In particular:

- when I run ```onnxruntime.get_device()``` output is 'GPU'
- ```onnxruntime.get_available_providers()``` output is ['CPUExecutionProvider', 'CUDAExecutionProvider']
but
- ```model.get_providers()``` is ['CPUExecutionProvider']

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): docker image pytorch/pytorch:1.5.1-cuda10.1-cudnn7-devel
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.2.0 (other versions produce cuda errors on import onnxruntime in this container)
- Python version: 3.7.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0
- GPU model and memory: GeForce RTX 208.

**To Reproduce**
Convert model script
```python /opt/venv/lib/python3.7/site-packages/transformers/convert_graph_to_onnx.py --framework pt --model sentence-transformers/distilbert-base-nli-stsb-mean-tokens models/sentence-transformers-onnx/distilbert-base-nli-stsb-mean-tokens.onnx --opset 11
```

**Expected behavior**
Model should run on GPU

**Comment by pranavsharma** [comment]
This should work. How did you create the session? Did you explicitly call set_providers with only cpu EP? Can you try the latest release (1.5.1)?

**Comment by braaannigan** [comment]
Hi @pranavsharma  - sorryt, my fault - I had specified only CPU EP when creating the model. 

Thanks for all your work, great library!

Liam

**Comment by sicklife** [comment]
I got the same isssue.
here is my code:
```python
[root@ip-10-0-137-89 demo]# cat onnx_test.py 

import onnxruntime as ort
print(ort.get_available_providers())     

provider =  ['CUDAExecutionProvider', 'CPUExecutionProvider']
ort_sess = ort.InferenceSession('../inference/det_onnx/model.onnx', providers=provider)
ort_sess.set_providers(provider)
print(ort_sess.get_providers())

ort_sess.set_providers(['CUDAExecutionProvider'],  provider_options=[{'device_id': 1,}])
print(ort_sess.get_providers())
```

here is the output:
```
['CUDAExecutionProvider', 'CPUExecutionProvider']
['CPUExecutionProvider']
['CPUExecutionProvider']

```

**Comment by sizhky** [comment]
> 

Can you throw more light on what needs to change in the code? I'm facing the exact same issue

**Comment by Jerry-zirui** [comment]
Same thing happen like [sicklife](https://github.com/sicklife) [o](https://github.com/microsoft/onnxruntime/issues/5337#issuecomment-1085887114), but I am using openvino
