### ISSUE TITLE
Can no longer import onnxruntime inside of google colab.

### ISSUE THREAD

**Issue by rayhern** [microsoft/onnxruntime#5341]
This has been working, and has stopped very recently. Just want to report it as soon as possible so the onnx team can be aware. Let me know if you think I could be doing anything wrong inside of my notebook, I am a paying customer of google colab so have memory optimized and decent GPU.

import onnxruntime as ort

Thank you in advance for any help.

**Comment by snnn** [comment]
Could you please provide more information to us? For example, what's the error message, which CUDA version do they provide?

**Comment by RicCu** [comment]
I [reported this](https://github.com/googlecolab/colabtools/issues/1614) to the colab team. I believe it's due to cuda/cudnn version incompatibility. If so, it should be fixed once colab [updates cuda/cudnn](https://github.com/googlecolab/colabtools/issues/1574) in its env.

**Comment by snnn** [comment]
Thank you.
