### ISSUE TITLE
Not compiling for arm7 32bit

### ISSUE THREAD

**Issue by colombod** [microsoft/onnxruntime#5347]
I am following the instructions [here](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#native-compiling-on-linux-arm-device) and have encountered issues.

- using ```/code/``` folder keeps asking me to do sudo command all the time
-  the instruction ```wget https://cmake.org/files/v3.13/cmake-3.16.1.tar.gz;``` is not working as the version ```3.13``` and ```3.16.1``` are in different folders on the remote server
- doing the ```Start the basic build``` fails with lots of errors like this one 
```
/code/onnxruntime/cmake/external/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/NEON/Complex.h:277:37: error: requested alignment 16 is larger than 8 [-Werror=attributes]
   EIGEN_ALIGN16 std::complex<float> x;
```
The device I am building for is a [pi-top4](https://www.pi-top.com/products/pi-top-4) which is a pi4

**Comment by snnn** [comment]
No, I think it is a GCC bug. The latest GCC should be fine.

**Comment by snnn** [comment]
#2152

**Comment by colombod** [comment]
@snnn it is also not working using the [docker file](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/README.md#arm-32v7) approach

this is the error
```
Step 6/27 : RUN pip3 install --upgrade pip
 ---> Running in 19e45b9c58a1
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
ModuleNotFoundError: No module named 'pip._vendor.requests'
The command '/bin/sh -c pip3 install --upgrade pip' returned a non-zero code: 1
```

**Comment by snnn** [comment]
No, you don't need to use the docker file. You can try [removing this line](https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/build.py#L587) from build.py and re-build. Line 587 to 589.
