### ISSUE TITLE
Exception error with Tensorrt Execution Provider on Windows

### ISSUE THREAD

**Issue by eric-tc** [microsoft/onnxruntime#5351]
**Describe the bug**

I have build onnxruntime version 1.5.1 from source with this command .\build.bat --config Release--build_shared_lib --parallel --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1" --use_tensorrt --tensorrt_home "C:\tensorrt" --cmake_generator "Visual Studio 15 2017"
everything build without error.

I am trying to run the squeenet sample in c++. If i use the Cpu provider everything works well. But when i use the tensorrt provider the program raise exception when execute the following code

`Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_Tensorrt(session_options, 0));`

with the following error

```
[E:onnxruntime:test, provider_bridge_ort.cc:633 onnxruntime::ProviderLibrary::ProviderLibrary] Failed to load library, error code: 126
OrtSessionOptionsAppendExecutionProvider_Tensorrt: Failed to load shared library
```
I have put all dll library from onnxruntime tensorrt e cuda but i have the same error. 

Could someone provide me some idea on how to solve?

**System information**
windows 10
- onnx 1.5.1 from source

- cpp version:
- Visual Studio 2017:
- Cuda 11.1 Cudnn 8.0.3 Tensorrt 7.1.3.4:
- GPU 2070 :

**Comment by pranavsharma** [comment]
TensorRT EP is now (starting 1.5.1) housed in a separate DLL rather than getting statically linked to ORT DLL. Please make sure you've set the right PATHs.

**Comment by eric-tc** [comment]
Hi @pranavsharma ,

thanks for the hint. I have found the bug. it was my mistake because i have installed cuda 11.1 instead of 11.0 and the tensorrt version is looking for 11.0.

**Comment by KangolHsu** [comment]
putting TensorRT dll files into correct path works fine .
