### ISSUE TITLE
Suggestion: Add note about OpenMP on Mac to 1.5.1 release notes

### ISSUE THREAD

**Issue by ankane** [microsoft/onnxruntime#5355]
Hey, it looks like v1.5.1 enables OpenMP for Mac (#4774). However, if it's not installed, upgrading from 1.4.0 -> 1.5.1 breaks existing code (as reported in #5344). It'd be nice to add a note about this to the release notes.

**Comment by pranavsharma** [comment]
Thanks for the suggestion. Resolved.

**Comment by ankane** [comment]
Fastest update ever. Thanks @pranavsharma!

Also, fwiw, was confused about why there's no 1.5.0 release.

**Comment by pranavsharma** [comment]
> Fastest update ever. Thanks @pranavsharma!
> 
> Also, fwiw, was confused about why there's no 1.5.0 release.

A few issues came up after pushing the python pkg with ver 1.5.0; pypi doesn't allow updating an existing ver for good reasons.

**Comment by ankane** [comment]
Thanks, hopefully others wondering the same will stumble upon this.
