### ISSUE TITLE
New libomp dependency conflicts with other libs

### ISSUE THREAD

**Issue by ppwwyyxx** [microsoft/onnxruntime#5369]
**Describe the bug**
Latest onnxruntime pypi package for mac depends on libomp: https://github.com/microsoft/onnxruntime/pull/4774
However, pytorch's python wheels ships with its own libiomp.dylib.
When pytorch and onnxruntime are used together, it prints:
```
OMP: Error #15: Initializing libomp.dylib, but found libiomp5.dylib already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://openmp.llvm.org/
```

**Urgency**
breaks users' projects

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac
- ONNX Runtime installed from (source or binary):binary
- ONNX Runtime version: latest
- Python version:3.7
- Visual Studio version (if applicable):n/a
- GCC/Compiler version (if compiling from source):n/a
- CUDA/cuDNN version:n/a
- GPU model and memory:n/a

**Expected behavior**
Hope the two projects can find a way to work together.

**Comment by tianleiwu** [comment]
@fs-eire @snnn to see whether it is feasible to add a flag to link with Intel OpenMP.

**Comment by snnn** [comment]
I think the best way is to remove ONNX Runtime's dependency on openmp. Otherwise whatever we choose, it is possible to conflict with some packages else.
