### ISSUE TITLE
Add DirectML support to WinML NuGet package for UWP

### ISSUE THREAD

**Issue by hig-dev** [microsoft/onnxruntime#5389]
I want to use the GPU for inference on an C# UWP app using the latest Windows ML NuGet package 1.5.1.
However, currently only CPU inference is supported. I tried to use the ONNX runtime directly with the DirectML execution provider and it worked. So, it should not be a big problem to include DirectML support for the Windows ML NuGet package for UWP as well.

**System information**
- Microsoft.AI.MachineLearning 1.5.1
- Windows 10 x64 Version 2004
- AMD RX Vega 64

I hope you can give us more insight about the implementation of this feature.
Thanks for your work.

**Comment by pranavsharma** [comment]
cc @martinb35 @jeffbloo

**Comment by smk2007** [comment]
Currently, WinML will run fine in a UWP context. However, currently, the DirectML execution provider binaries are not store compliant and will cause UWP apps to fail the Windows App Certification Kit. This will prevent the app from shipping in the store.

If the goal is to side-load the application and not upload to the windows store, then 1.5.1 or 1.4.0 can be used to create WinML+DML UWP applications.

WinML+CPU was made WACK compliant in 1.5.1 and is the recommended path currently for building apps that target the Store.

**Comment by hig-dev** [comment]
> Currently, WinML will run fine in a UWP context. However, currently, the DirectML execution provider binaries are not store compliant and will cause UWP apps to fail the Windows App Certification Kit. This will prevent the app from shipping in the store.
> 
> If the goal is to side-load the application and not upload to the windows store, then 1.5.1 or 1.4.0 can be used to create WinML+DML UWP applications.
> 
> WinML+CPU was made WACK compliant in 1.5.1 and is the recommended path currently for building apps that target the Store.

Thanks for the clarification.  Are there plans to make the DirectML execution provider binaries store compliant?

**Comment by wchao1115** [comment]
@hig-dev Thanks for the feedback. We'll look into how to appropriately do that in the next update.

**Comment by wchao1115** [comment]
@hig-dev one of the questions I have with regards to your scenario is why do you feel you need to ship your UWP app with a redistributable package of WinML while WinML (and DirectML) is already available as a standard Windows API in the operating system. Is the system version not sufficient for your use case in any way? Most UWP apps in the store using WinML simply call into the underlying Windows API.

**Comment by hig-dev** [comment]
@wchao1115 I am using a ONNX model that is converted from a PyTorch model. If I am using the current PyTorch version for the conversion and the built-in WinML, I am not able to load the converted ONNX model because of a _Failed to load model with error: Unknown model file format version._ error. I can load the same ONNX model with the WinML NuGet. In order to use the built-in WinML, I have to use an old PyTorch version (1.2.0) for the conversion and an old opset version (8).

I would prefer to ship my UWP app with the NuGet package of WinML, so that I can use a higher opset version, the current PyTorch version and support for more Windows 10 versions (see https://docs.microsoft.com/de-de/windows/ai/windows-ml/onnx-versions).

**Comment by wchao1115** [comment]
Hi @hig-dev, we looked into this issue a bit on our end and arrived at a conclusion that started with the Windows SDK 19041 (for the 20H1 update of Win10), you should be able to use and distribute DirectML through the WinML API from the WinML NuGet package with your UWP app without violating the WACK compliant. What makes this possible is the change in the SDK itself along with the related change in the WACK certification rules.

**Comment by hig-dev** [comment]
@wchao1115 I would like to try to use the new WinML NuGet but I am experiencing the following build error:

Build configuration: Debug | x64
```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6140,5): error APPX1111: Payload contains two or more files with the same destination path 'Microsoft.AI.MachineLearning.dll', but they are different sizes. Source files: 
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6140,5): error APPX1111: C:\Users\hig\.nuget\packages\microsoft.ai.machinelearning\1.6.0\build\uap\..\..\runtimes\win-x64\uap\Microsoft.AI.MachineLearning.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6140,5): error APPX1111: C:\Users\hig\.nuget\packages\microsoft.ai.machinelearning\1.6.0\runtimes\win-x64\native\static\microsoft.ai.machinelearning.dll 
```

The target of my app is Build 19041 and I am using the latest Visual Studio 16.8.3. Should I open a new issue?

**Comment by hig-dev** [comment]
I checked the new 1.8.0 release and it works now. Thanks.

**Comment by emaschino** [comment]
May I ask what kind of performances are expected with DirectML EP enabled on UWP? On a HoloLens 2 device, enabling the DirectML EP yields to a considerable drop in performances vs CPU only.
