### ISSUE TITLE
Integrate with the CoreFX Tensor proposal

### ISSUE THREAD

**Issue by tannergooding** [Microsoft/onnxruntime#540]
CoreFX is looking to expose a set of types that allow exchange and interop between the various tensor frameworks.

We now have an API proposal for what these types would look like here: https://github.com/dotnet/corefx/issues/35765

It would be beneficial if Onnx could review the proposal to ensure it matches their expectations and raise any concerns before we take it to API review.

**Comment by tannergooding** [comment]
CC. @shahasad, @jignparm, @eerhardt

**Comment by linkerzhang** [comment]
@gramalingam may check in this sparse tensor API please, so that it aligns with our sparse tensor support later.

**Comment by faxu** [comment]
Closing this issue in this repo; further review can continue here: https://github.com/dotnet/corefx/issues/35765
