### ISSUE TITLE
Can't find the required module in import statement

### ISSUE THREAD

**Issue by wbstanie** [microsoft/onnxruntime#5409]
https://github.com/microsoft/onnxruntime/blob/9684e1b5a8b13bce7a91b00041ab0229ca678c2f/onnxruntime/core/providers/nuphar/scripts/model_editor.py#L10

**Comment by snnn** [comment]
@KeDengMS  , could you please help take a look?

**Comment by wbstanie** [comment]
@snnn @KeDengMS 

I've found where the source code located: onnxruntime/onnxruntime/python/tools/

I guess the import statement should be fixed within onnxruntime/onnxruntime/core/providers/nuphar/scripts/model_editor.py

**Comment by KeDengMS** [comment]
@wbstanie sorry I don't understand the bug. Seems the import is correct? Besides, we have [unit tests](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/python/onnxruntime_test_python_nuphar.py#L344) to run model_editor in CI, and no error was reported since the change.
