### ISSUE TITLE
Model with External Data cannot be loaded in Windows when path has forward slash (/)

### ISSUE THREAD

**Issue by tianleiwu** [microsoft/onnxruntime#5418]
**Describe the bug**

In windows, it cannot create a session for a model with external data with / in path, when the model is not in the current directory.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: any
- Python version: any
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

Put any onnx model with external data to a directory like d:\test\model.onnx, and then create an inference session with "d:/test/model.onnx" as parameter. It will fail to create session since it is looking for external data file in current directory instead of d:\test\.

**Expected behavior**

support both \ and / for path in Windows.

**Screenshots**

**Additional context**

**Comment by snnn** [comment]
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/platform/path_lib.h#L208

We should finish this todo.

**Comment by snnn** [comment]
The PathFindNextComponentA function is windows desktop only, we probably need to consult WinML team how to deal with this.  I would rather not to re-implementing the path functions by our own.

**Comment by smk2007** [comment]
Pathcch.h should be a good alternative. It is not a 1:1 to the shlwapi.h apis, but a lot of apis are there which can be used to reliably duplicate behavior.

It is already used in path_lib.cc:

**Comment by tianleiwu** [comment]
Fixed.
