### ISSUE TITLE
ONNX operator set version: 12 is unsupported. Falling back to: 11

### ISSUE THREAD

**Issue by shivSD** [microsoft/onnxruntime#5422]
**Bug**
Using [ Openvino GPU](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/README.md#openvino-on-gpu) docker to run the model in intel GPU, for some reason the model is using CPU  not GPU (is it falling back CPU ?) and i get following warning 
"**ONNX operator set version: 12 is unsupported. Falling back to: 11**"
What does this mean ?  is it onnx version incompatible ? 
 
About the model : converted model from keras into onnx (it is similar to mobilenetv2 network)  

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary):  docker  
- ONNX Runtime version: 1.5.1
- Python version: 3.6
- Visual Studio version (if applicable): NA
- GCC/Compiler version (if compiling from source): gcc version 7.5.0 
- CUDA/cuDNN version: NA
- GPU model and memory:  Intel® UHD Graphics 630 (Intel® Core™ i9-9880H CPU @ 2.30GHz × 16 )

[mnet.zip](https://github.com/microsoft/onnxruntime/files/5351157/mnet.zip)
**Expected behavior**
Should run on Intel GPU, currently it is running only on CPU with warnings. 

.

**Comment by jywu-msft** [comment]
it means the model has opset 12 operators which is not supported.
note that gpu backend supports a more limited set of operators compared to cpu so it's possible the model cannot be assigned to gpu.
+@suryasidd for any other comments.
