### ISSUE TITLE
Default order of Execution Provider 

### ISSUE THREAD

**Issue by leqiao-1** [microsoft/onnxruntime#5434]
**Describe the bug**
I have built ort wheel with dnnl EP from source. 
However, when I use ```sess_options.enable_profiling = True```, ```trace_file = sess.end_profiling()```, all prividers in result json is CPUExecutionProvider and there isn't DnnlExecutionProvider. 
I added ```sess.get_providers()```, it returned ['DnnlExecutionProvider', 'CPUExecutionProvider'].
I tried ```onnxruntime.ort.get_available_providers()```, it returned ['CPUExecutionProvider', 'DnnlExecutionProvider']. 
Is that normal no DnnlExecutionProvider appears in result json file ?
Thanks

**Comment by pranavsharma** [comment]
cc @jywu-msft

**Comment by jywu-msft** [comment]
It's possible that an Execution Providers can't execute any of the graph. In those cases, nodes would be assigned to default CPU Provider. So this may be normal behavior you're observing.
What model is this?
Can you try the exercise with something like [resnet 50 from onnx model zoo](https://s3.amazonaws.com/download.onnx/models/opset_7/resnet50.tar.gz) just to confirm everything is working as normal?

**Comment by qiaodalei** [comment]
It's a customer model. 
I tried with resnet50 model. Both CPUExecutionProvider and DnnlExecutionProvider appear in profiling result. 
Thanks for your reply.

**Comment by leqiao-1** [comment]
It's a customer model.
I tried with resnet50 model. Both CPUExecutionProvider and DnnlExecutionProvider appear in profiling result.
Thanks for your reply.

**Comment by hariharans29** [comment]
Closing as it seems like there is no issue in ORT (it seems like dnnl just lacks op coverage for the customer model)
