### ISSUE TITLE
What is the best way to allocate cuda buffer in custom op?

### ISSUE THREAD

**Issue by grimoire** [microsoft/onnxruntime#5448]
Hi
I am working on create custom op follow [this example](https://github.com/microsoft/onnxruntime/tree/fdc5c308c4a579bcf96a170cffa3c00e761eb8cd/onnxruntime/test/testdata/custom_op_library). And have some question.
1. How can I get the cuda stream used in onnxruntime?
2. The op need some workspace to store the intermediate results. Use cudaMalloc directly in Kernel::Compute() is slow. Prealloc is also hard because the buffer size I needed depends on the input size. It seems that buildin op use `GetScratchBuffer` to allocate the buffer, but it is not available in release version. Is there some kinds of cuda memory pool that I can use in release version?

Thanks.

**Comment by KnightYao** [comment]
mark, i have same question

**Comment by yuslepukhin** [comment]
CUDA Allocator is using cudaMalloc()

**Comment by grimoire** [comment]
Thanks for the answer. 
What about another question? If the cudastream is not available in custom op this version, will it be available in future?
