### ISSUE TITLE
C#: Unable to load DLL 'onnxruntime' on server without Visual Studio installed

### ISSUE THREAD

**Issue by LazyDevKael** [microsoft/onnxruntime#5449]
**Describe the bug**
I wrote two small console application in C#, installed nuget package Microsoft.ML.OnnxRuntime.MKLML and Microsoft.ML.OnnxRuntime respectively.
I build the applications and run them on Server A and it was working fine. Models are loaded and prediction was successful.
However, after I copied the binaries to Server B (copy the entire **bin** folder), it throws exception when it was trying to load model from .onnx file. It complains about not able to load DLL onnxruntime, which is placed in the same folder as the console application .exe file.
Exception:
Error: System.TypeInitializationException: The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'onnxruntime': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.ML.OnnxRuntime.NativeMethods.OrtGetApiBase()
   at Microsoft.ML.OnnxRuntime.NativeMethods..cctor() in C:\a\2\s\csharp\src\Microsoft.ML.OnnxRuntime\NativeMethods.cs:line 193
   --- End of inner exception stack trace ---
   at Microsoft.ML.OnnxRuntime.SessionOptions..ctor() in C:\a\2\s\csharp\src\Microsoft.ML.OnnxRuntime\SessionOptions.cs:line 49
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath) in C:\a\2\s\csharp\src\Microsoft.ML.OnnxRuntime\InferenceSession.cs:line 34
   at OnnxTest480.Program.Main(String[] args) in C:\Users\kael\dev\C#\ONNXTestsSln\OnnxTest480\Program.cs:line 20
Press enter to abort...

I looked at https://github.com/microsoft/onnxruntime#binaries and it says Visual C++ Runtime (for Windows packages) is required [Requires Visual C++ 2019 runtime], and Server B doesn't have visual studio installed, while Server A does.

Just trying to confirm whether this is the issue, and any server that is to use ONNX runtime has to have Visual Studio 2019 installed?

**Urgency**
None

**System information**
- OS Platform and Distribution: Windows Server 2019
- ONNX Runtime installed from (source or binary): nuget package manager (Microsoft.ML.OnnxRuntime.MKLML or Microsoft.ML.OnnxRuntime).
- ONNX Runtime version: 1.5.1

**To Reproduce**
var session = new InferenceSession(modelFile)

**Expected behavior**
Model can be loaded on both Server A and Server B.

**Comment by LazyDevKael** [comment]
It's working after installed VC++ runtime 2015-2019 (x64).

**Comment by Scxw010516** [comment]
I have a similar problem to you, when my Winform program is packaged and installed to windows server 2012, without Visual Studio installed. Then run the software and pop up the System.DllNotFoundException error, cannot find the Microsoft.ML.OnnxRuntime.dll. Can you provide more information about VC ++ runtime 2015-2019 (x64)

**Comment by harishankar-gopalan** [comment]
@Scxw010516  were you able to fix this issue ? I am also hitting a similar roadblock for onnxruntime on Windows Server 2012.

**Comment by Scxw010516** [comment]
> [@Scxw010516](https://github.com/Scxw010516) were you able to fix this issue ? I am also hitting a similar roadblock for onnxruntime on Windows Server 2012.

Yes, I solved. Actually, because missing the onnx dll. You can try using Dependency Walker to check the missing dependencies. Then download the missing dll, put it in the System32 directory (I forgot exactly where I put it, you can read more blogs). Then, my problem is solved. Good luck.
