### ISSUE TITLE
cannot replicate BERT quantization performance

### ISSUE THREAD

**Issue by boliangz** [microsoft/onnxruntime#5458]
**Describe the bug**
I want to replicate the results of this tutorial "Bert Quantization with ONNX Runtime on CPU" (https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/notebooks/Bert-GLUE_OnnxRuntime_quantization.ipynb). The only change I did is adding "torch.set_num_threads(1)" at the beginning of the code to let the model only use one thread. I did the experiments on Colabl and our server but got different results:

On Colab:
- PyTorch full precision performance:
total time (seconds): 216.6
- PyTorch quantization performance:
total time (seconds): 128.7
- ONNXRuntime full precision performance:
total time (seconds): 155.7
- ONNXRuntime quantization performance:
total time (seconds): 109.6

On our server:
- PyTorch full precision performance:
total time (seconds): 178.9
- PyTorch quantization performance:
total time (seconds): 160.6
- ONNXRuntime full precision performance:
total time (seconds): 156.3
- ONNXRuntime quantization performance:
total time (seconds): 150.1

Both pytorch and onnx quantization work well on the Colab machine but underperforms on our server. I guess the problem should be on our side. After debugging for quite a long time, we still couldn't find the answer. Would that be the problem of our CPU model? Is there a requirement for the cpu in order to let quantization work properly? Does the quantization require some specific modules, e.g. MKL? I list the cpu info of our server and Colab below.

**Urgency**
Medium

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 16.04.6 LTS (Xenial Xerus)
- ONNX Runtime installed from (source or binary):
pip install --upgrade onnxruntime==1.5.1
- ONNX Runtime version:
1.5.1
- Python version:
3.7.8
- Pytorch  
1.6.0+cpu
- transformers version:
3.3.1
- Colab CPU info:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  2
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               79
Model name:          Intel(R) Xeon(R) CPU @ 2.20GHz
Stepping:            0
CPU MHz:             2200.000
BogoMIPS:            4400.00
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            56320K
NUMA node0 CPU(s):   0,1
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities

- Our server cpu info:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                20
On-line CPU(s) list:   0-19
Thread(s) per core:    1
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Stepping:              1
CPU MHz:               2199.865
CPU max MHz:           2200.0000
CPU min MHz:           1200.0000
BogoMIPS:              4411.61
Virtualization:        VT-x
Hypervisor vendor:     vertical
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-9
NUMA node1 CPU(s):     10-19
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm arat pln pts spec_ctrl intel_stibp

**Comment by tianleiwu** [comment]
@boliangz, your server have two CPU sockets. Some setting (like number of threads) in the notebook is designed for machine with single CPU socket.

For your server, it is better to create two inference sections, and each section is limited to use one Numa node to get better throughput. You can set number of (OpenMP) threads to 10 or less for each section.

For example, you can compare PyTorch and OnnxRuntime with only only one Numa node in your server:
```
pip install onnxruntime_tools==1.5.2
numactl -N 0 python -m onnxruntime.transformers.benchmark --models bert-base-cased -e onnxruntime torchscript -p int8 -o -b 1 -s 128 --thread_num 10 -t 1000
```

**Comment by boliangz** [comment]
Thanks for the reply. It seems the latest onnxruntime_tools version on pypi is 1.5.1: https://pypi.org/project/onnxruntime-tools/. Where can I get the 1.5.2 version?

I run the second command with 1.5.1 and got an error:
benchmark.py: error: unrecognized arguments: -n 10

**Comment by yufenglee** [comment]
@boliangz , could you please try smaller sequence length with the benchmark tool, like 64 as below?

numactl -N 0 python -m onnxruntime_tools.transformers.benchmark --models bert-base-cased -e onnxruntime torchscript -p int8 -o -b 1 -s **64** -n 10 -t 1000
