### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 

### ISSUE THREAD

**Issue by skuriyadi** [microsoft/onnxruntime#5460]
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from deep.onnx failed:Load model deep.onnx failed. File doesn't exist

I am getting this error even though file is existing in the provided path.

**Comment by kit1980** [comment]
Can you provide exact code/command you're trying?
Maybe the file is in a different directory, or the program doesn't have permissions to read it?
