### ISSUE TITLE
Poor Performance on imagenet/nasnet_mobile/classification (TF=58ms, ONNX=92ms)

### ISSUE THREAD

**Issue by TomWildenhain-Microsoft** [microsoft/onnxruntime#5473]
**Describe the bug**
On Google's Imagenet (ILSVRC-2012-CLS) model ONNX is significantly slower than TF.  The converted model (converted with tf2onnx) takes 92 ms per inference while TF takes 58 ms.  I'm running on CPU.

**Urgency**
Medium.  Required for OKR target.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows**
- ONNX Runtime installed from (source or binary): **Binary (pypi)**
- ONNX Runtime version: **1.5.1**
- Python version: **3.7.8**
- Visual Studio version (if applicable): **2019**

**To Reproduce**
- Download https://www.dropbox.com/s/9jhngwjcu29rem2/perf_test_imagenet_nasnet_mobile.zip?dl=1
- Run **perf_test_nasnet_portable.py**

**Expected behavior**
ONNX is faster than TF

**Comment by kit1980** [comment]
It's probably just typo in the description, but can you confirm it's actually a typo here (otherwise ORT is actually faster)? 
"The converted model (converted with tf2onnx) takes 58 ms per inference while TF takes 92 ms".

**Comment by TomWildenhain-Microsoft** [comment]
Updated.
