### ISSUE TITLE
win7 use onnxruntime

### ISSUE THREAD

**Issue by eekarot** [microsoft/onnxruntime#5483]
We hope to run onnxruntime on win7, but the official compiled library relies on win10 functions. Locate the point in: advapi32.dll's eventsetinformation function.

**Comment by snnn** [comment]
I throught we fixed it. Which ORT version are you using?

Issue:
#4570

Fix:
#4636

**Comment by eekarot** [comment]
> I throught we fixed it. Which ORT version are you using?
> 
> Issue:
> #4570
> 
> Fix:
> #4636

The version I used is 1.4.0. Is this the latest version that solves this problem?

**Comment by snnn** [comment]
The fix is not in 1.4.0. Please try the latest one.

**Comment by eekarot** [comment]
> The fix is not in 1.4.0. Please try the latest one.

thank you

**Comment by snnn** [comment]
Please reopen this issue if it still exists.

**Comment by eekarot** [comment]
> Please reopen this issue if it still exists.

I have been using it on win7. tks again

**Comment by fdwr** [comment]
> I have been using it on win7. tks again

@eekarot Was [ORT 1.5.1](https://github.com/microsoft/onnxruntime/releases/tag/v1.5.1) the version that worked for you, if you remember? (I have a project I need to work on Win7 too, and old ORT versions are fine because it's a very basic model like mobilenet) Thanks.

**Comment by snnn** [comment]
> I use onnx runtime 1.12.1 in Windows 7 and report an error directly, does this version not support win7?

Please build it from source.

**Comment by hawkhai** [comment]
**You can implement it yourself to support Windows 7. The issue is resolved here:**
**可以自己实现，以支持 win7，这里解决了：<https://github.com/yycmagic/onnxruntime-for-win7>**
