### ISSUE TITLE
Image Tensor conversion

### ISSUE THREAD

**Issue by thhart** [microsoft/onnxruntime#5486]
**Is your feature request related to a problem? Please describe.**

I am looking for a possibility/description of data conversion for a trained network. The network is expecting its input in following format: 

`"NodeInfo(name=images,info=TensorInfo(javaType=FLOAT,onnxType=ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,shape=[1, 3, 608, 608]))"`

**System information**
Java / OnnxRuntime 1.5.1

**Describe the solution you'd like**
Helper/Utility class for image->tensor conversion
 
**Additional context**
The model is a converted YoloV5 model by Ultralytics and contains the input specification as given above.

**Comment by Craigacp** [comment]
The model is requesting that the input is a tensor [batch_size, channels, height, width]. You can write the pixel information to a `FloatBuffer` in row major order (i.e. the last index increments the fastest) and then create an `OnnxTensor` from that supplying the shape information.
