### ISSUE TITLE
ORT Mobile new feature missing in v1.5.1 "convert_onnx_model_to_ort.py"

### ISSUE THREAD

**Issue by MarlNox** [microsoft/onnxruntime#5495]
Ive noticed the new features of this release, but no matter which version I try to download, it seems that convert_onnx_model_to_ort.py is missing, hence i havent been able to try the feature. 

Im basing this on the guide here: https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_for_Mobile_Platforms.md

Any suggestions?

**Comment by pranavsharma** [comment]
It's a typo. The correct file name is ```convert_onnx_models_to_ort.py```.

**Comment by MarlNox** [comment]
> It's a typo. The correct file name is ```convert_onnx_models_to_ort.py```.

Thanks!
Nonetheless, Under tools in the installation folder i dont find that either. FYI im using colab.
Is it available in 1.5.2?
Any steps I have missed to get it?

**Comment by tianleiwu** [comment]
@skottmckay to take a look

**Comment by skottmckay** [comment]
The script is in the full repository not the installation folder as you need to do a custom build to use the ORT format model. 

>You will need a script from the the ONNX Runtime repository, and to also perform a custom build, so you will need to clone the repository locally

**Comment by MarlNox** [comment]
Building the libraries fixed the issue. 
Thanks for the support!
