### ISSUE TITLE
Is there a simple demo of python example about tensorRT as the execution engine of onnxruntime?

### ISSUE THREAD

**Issue by cuixing158** [microsoft/onnxruntime#5497]
In recent months, I noticed that tensorRT has been added to the onnxruntime project. There is very little information about this, and there is fewer [sample codes](https://github.com/microsoft/onnxruntime/blob/master/docs/python/notebooks/onnx-inference-byoc-gpu-cpu-aks.ipynb). I only saw an example of the tensort execution engine deployed to the cloud. I want to deploy it to jetson embedded devices. , I just want to use the onnxruntime-tensorRT API , I don’t want to call tensorRT API, how do I do it, it’s better to have sample code, thank you！

**Comment by faxu** [comment]
Take a look at this: https://github.com/Azure-Samples/onnxruntime-iot-edge/blob/master/README-ONNXRUNTIME-arm64.md

**Comment by cuixing158** [comment]
thanks

**Comment by manashgoswami** [comment]
The `onnxruntime_gpu-1.4.0-cp36-cp36m-linux_aarch64.whl` uses the CUDA execution provider.
If you would like to use the TensorRT libs on the Jetson then you will need to build the package from source. Steps to build TensorRT package for Jetson is [here.](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#nvidia-jetson-tx1tx2nanoxavier).

**Comment by cuixing158** [comment]
@manashgoswami, thank you so much for providing useful answers!
