### ISSUE TITLE
Windows 10 compilation fails, there is a problem with the path?

### ISSUE THREAD

**Issue by cuixing158** [microsoft/onnxruntime#5498]
When I compile onnxruntime on window10 according to [the tutorial](https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#execution-providers), the following error appears, how can I change it?
![build_error](https://user-images.githubusercontent.com/22857777/96105787-0357a880-0f0d-11eb-8440-0de15e36fbfd.png)

**Comment by crisp-snakey** [comment]
You'll need to quote file paths containing spaces or escape the spaces in the path.

So instead use something like `--cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1"`

**Comment by cuixing158** [comment]
thanks!
