### ISSUE TITLE
[C++]In 1.5.1, is there any way to set cuda/cpu?

### ISSUE THREAD

**Issue by zacario-li** [microsoft/onnxruntime#5512]
Hi,
    I'm facing a problem when I use C++, by default, onnxruntime use cpu to inference my model. I want to set cuda to run it. I don't find any way to specify the running device.
    When I use 
```cpp
Ort::GetAvailableProviders()
```
I got two values returned.
```
"CPUExecutionProvider"
"CUDAExecutionProvider"
```
How to use it?

**Comment by hendrik-skubch** [comment]
Try calling `OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0);` before initializing the session. That worked for me. Imo, it is a little unintuitive to have to use the C api for a single call when everything else is C++.

**Comment by zacario-li** [comment]
> OrtSessionOptionsAppendExecutionProvider_CUDA

oh man, how did you find it, thank you.

**Comment by zacario-li** [comment]
@hendrik-skubch 
the function you mentioned is commented by default like below:
[OrtSessionOptionsAppendExecutionProvider_CUDA](https://github.com/microsoft/onnxruntime/blob/v1.5.2/include/onnxruntime/core/session/onnxruntime_c_api.h#L405)
how did you call it?

**Comment by hendrik-skubch** [comment]
It's in https://github.com/microsoft/onnxruntime/blob/v1.5.2/include/onnxruntime/core/providers/cuda/cuda_provider_factory.h
Cheers!
