### ISSUE TITLE
Make numpy version optional not hardcoded

### ISSUE THREAD

**Issue by xadupre** [Microsoft/onnxruntime#553]
**Is your feature request related to a problem? Please describe.**

The build currently takes a dependency on numpy 1.15.0. Version is hardcoded.
https://github.com/Microsoft/onnxruntime/blob/master/tools/ci_build/build.py#L199

**System information**
- ONNX Runtime version (you are using): master branch

**Describe the solution you'd like**
I'd like the build to take the currently installed version or or the change it if by specifying on the command line.

**Comment by pranavsharma** [comment]
@xadupre would you be willing to contribute? thanks.

**Comment by pranavsharma** [comment]
Fixed in this commit https://github.com/Microsoft/onnxruntime/commit/b4ffcf8258cc7bcd4a97303efd53d6e6c01904d0
