### ISSUE TITLE
UpsampleBase const scale >= 1 was false. Scale value should be greater than or equal to 1.

### ISSUE THREAD

**Issue by SystemErrorWang** [microsoft/onnxruntime#5548]
**Describe the bug**

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.5
- ONNX Runtime installed from (source or binary):  pip install
- ONNX Runtime version: 1.5.1
- Python version: 3.6.10
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None
- GPU model and memory: None

**To Reproduce**
I have a model with seveal torch.nn.functional.interpolate layers to downsample feature maps. I can export the model to model.onnx with out any problem, but when I tried to load the model to onnxruntime, I got this errpr message:
```
RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/tensor/upsample.h:271 void onnxruntime::UpsampleBase::ScalesValidation(const std::vector<float> &, const onnxruntime::UpsampleMode) const scale >= 1 was false. Scale value should be greater than or equal to 1.
```

I would like to know if onnxruntime only support interpolation with scale >=1. If so, how can I downsample a feature map to a certain resolution?

**Comment by hariharans29** [comment]
What is the opset version of your model ? If possible, could you share a minimal model to that can repro this ?

**Comment by SystemErrorWang** [comment]
@hariharans29 Thank you for your reply, I re-generated the onnx file. The above mentioned problem happens with opset=9, but when setting opset=10, everything goes on well as expected.

**Comment by hariharans29** [comment]
Thanks - good to know. I expected this because I think downsample was not supported in opset - 9 and below (that is why you hit the assert that scale should be >= 1). I *think* the generic “Resizing” was introduced only in opset-10. 

Can we close this issue ?
