### ISSUE TITLE
Advertized compatibility with Tensorflow, Keras, Caffe, etc

### ISSUE THREAD

**Issue by Honya2000** [microsoft/onnxruntime#5552]
I choosed ONNX runtime for inferencing my models because of advertised compatibility with many existing formats and performance.
Integration was quite long because of lack of any examples.
There is absolutely nothing about image tensors, how to fill them without recreation, etc.
Generally nothing regarding inferencing for C++ developers.

When i started testing/debugging - I just realized that there is no any compatibility at all.
Runtime cannot load .pb, tflite, and any other files directly. Just onnx.
All third party convertors are also useless. I tried mmconvert, tf2onnx. No any convertor works. With any model. Even public ones.
Really frustrated now. Lost so much time...

Do not understand what the purpose of the runtime then? Should i train directly to onnx?

**Comment by faxu** [comment]
I'm sorry to hear your frustration, but if you can provide us with more details on the pain points and points of failures, we can take actionable steps to address this. 

In general, as you mention ONNX Runtime supports models in the onnx format, and conversion or export needs to happen first. 
Examples and tutorials can be found here: https://microsoft.github.io/onnxruntime/docs/tutorials/samples_catalog.html

If there are shortcomings in the converters, please be specific and file issues in the respective Github repositories (our teams at Microsoft monitors the tensorflow-onnx, keras-onnx, sklearn-onnx, onnxmltools, and pytorch onnx export converters). 

If there are questions about usage in specific environments, you can post them here or in Discussions and we can help troubleshoot or advise.

**Comment by Honya2000** [comment]
Of course i checked all tutorials. And googled the issue. There are lot of questions regarding conversion errors, like I have... without answers.
Tomorrow will upload example frozen_inference_graph.pb file (public one) to my drive for test.

mmconvert gives error:
AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

tf2onnx gives error:
TypeError: 'NoneType' object is not iterable

**Comment by snnn** [comment]
I wrote a tensorflow-onnx tutorial, you may take a look:
https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx/imagenet

**Comment by faxu** [comment]
To help with more specific guidance on your case, I suggest to share details of your model and conversion issues on https://github.com/onnx/tensorflow-onnx/issues, as that is the primary place the TF converter team monitors for troubleshooting and most issues there are reviewed/answered.
