### ISSUE TITLE
For weight input

### ISSUE THREAD

**Issue by zsy9512** [microsoft/onnxruntime#5560]
Hello , I have made the option "export_params" to false when exported the onnx model. For this opreation, I need to input the weight at inferring stage. And I have used a dict to include all data and success run the model at python code. However, I need to implement it by C++ code. I don't know what data structure to use in C + + code to input my net weight.Can you give me some suggestions or a code example.

**Comment by RyanUnderhill** [comment]
Have you seen this file? https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp

It has an example of using the C++ API to pass data to a model and get the results.

**Comment by zsy9512** [comment]
> Have you seen this file? https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp
> 
> It has an example of using the C++ API to pass data to a model and get the results.

yes,I have already read it.It give a one node input in the example, but I need a muti-node input. For example, for super_resolution,it need 1 input-image and 8 weights for input.I can not find how to do it.

**Comment by zsy9512** [comment]
I notice these code :
`  Ort::Session session(env, model_path, session_options);
  Ort::AllocatorWithDefaultOptions allocator;
  // print number of model input nodes
  size_t num_input_nodes = session.GetInputCount();
  std::vector<const char*> input_node_names(num_input_nodes);
  std::vector<int64_t> input_node_dims;  // simplify... this model has only 1 input node {1, 3, 224, 224}.
                                         // Otherwise need vector<vector<>>
  printf("Number of inputs = %zu\n", num_input_nodes);`

 *************************************************************************
those mean your code are supported muti-input-node,but when I try to use the "run" function , it's api show that it only suppoort  single ort::vlaue for inputdata。
`inline void Session::Run(const RunOptions& run_options, const char* const* input_names, const Value* input_values, size_t input_count,
                         const char* const* output_names, Value* output_values, size_t output_count) {
  static_assert(sizeof(Value) == sizeof(OrtValue*), "Value is really just an array of OrtValue* in memory, so we can reinterpret_cast safely");
  auto ort_input_values = reinterpret_cast<const OrtValue**>(const_cast<Value*>(input_values));
  auto ort_output_values = reinterpret_cast<OrtValue**>(output_values);
  ThrowOnError(Global<void>::api_.Run(p_, run_options, input_names, ort_input_values, input_count, output_names, output_count, ort_output_values));
}`
This confused me

**Comment by zsy9512** [comment]
the inputdata can be a array of vlaue. And should input the head point of the array.Thank you any way
