### ISSUE TITLE
Android Build Failed

### ISSUE THREAD

**Issue by xuhao1** [microsoft/onnxruntime#5561]
**Describe the bug**
I am trying to build onnxruntime 1.5.2 for android with nnapi and failed.

**System information**
-  Windows10
- Onnxruntime 1.5.2
- VS2015
- 
**To Reproduce**
```
./build.bat --android --android_sdk_path C:\Users\xuhao\AppData\Local\Android\Sdk --android_ndk_path  C:\Users\xuhao\AppData\Local\Android\Sdk\ndk\21.3.6528147 --android_abi arm64-v8a --android_api 27 --use_nnapi --cmake_generator Ninja
```

**Expected behavior**
```
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:20 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:20 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "C:/Users/xuhao/source/onnxruntime/build/Windows/host_protoc/CMakeFiles/CMakeOutput.log".
See also "C:/Users/xuhao/source/onnxruntime/build/Windows/host_protoc/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "C:\Users\xuhao\source\onnxruntime\\tools\ci_build\build.py", line 1794, in <module>
    sys.exit(main())
  File "C:\Users\xuhao\source\onnxruntime\\tools\ci_build\build.py", line 1706, in main
    cmake_path, source_dir, build_dir, args)
  File "C:\Users\xuhao\source\onnxruntime\\tools\ci_build\build.py", line 1485, in build_protoc_for_host
    run_subprocess(cmd_args, cwd=protoc_build_dir)
  File "C:\Users\xuhao\source\onnxruntime\\tools\ci_build\build.py", line 434, in run_subprocess
    env=my_env, shell=shell)
  File "C:\Users\xuhao\Anaconda3\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
```

**Comment by duli2012** [comment]
The build complains that it cannot find c/c++ compiler. Do you have them in your PATH?

**Comment by Jeff-GiJoe** [comment]
I am very new at this. Not sure how how find it. 🤔

**Comment by xuhao1** [comment]
> The build complains that it cannot find c/c++ compiler. Do you have them in your PATH?

Thanks for your reply!
Do I need to install additional cross compiler for arm64? Which compiler is required? I have installed vs2017 android components.
This step is not written in BUILD.md.

**Comment by xuhao1** [comment]
> You will need to start the build from a 'Developer Command Prompt for Visual Studio'
> https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs
> 
> See, https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#windows

Thanks! This solved my issue!

**Comment by chen1399** [comment]
I have a same problem. But I don't have vs2017 android components, how can I do it?

**Comment by chen1399** [comment]
> You will need to start the build from a 'Developer Command Prompt for Visual Studio'
> https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs
> 
> See, https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#windows

I have a same problem. But I don't have VS2017 android components, how can I do it? I used the 'androidndk toolchain llvm clang.exe' as compiler. But it has error because clang.exe doesn't add '--target aarch64-linux-android28-clang'.
