### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from fastwave.onnx failed:Type Error: Type parameter (T) bound to different types (tensor(double) and tensor(float) in node ().

### ISSUE THREAD

**Issue by li-xx-5** [microsoft/onnxruntime#5581]
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from fastwave.onnx failed:Type Error: Type parameter (T) bound to different types (tensor(double) and tensor(float) in node ().

I got this error when I was converting the onNX model.

**System information**
OS Platform and Distribution : Linux Ubuntu 16.04
ONNX Runtime installed from (source or binary): Binary via pip
ONNX Runtime version: onnxruntime==0.4.0 (CPU version)
Python version: 3.6
Visual Studio version (if applicable):No
GCC/Compiler version (if compiling from source): No
CUDA/cuDNN version:CUDA 9/cuDNN 7
GPU model and memory:titan 

To Reproduce
import onnx
import onnxruntime as rt
sess = rt.InferenceSession("fastwave.onnx")

Expected Behavior
After the session creation i should be able to infer with my model.

**Screenshots**
![image](https://user-images.githubusercontent.com/43694664/96965367-99f41d00-153e-11eb-8ad7-b11514dea35a.png)

    text = np.array(text_to_sequence(text, hp.text_cleaners), dtype=np.float64)
    text = np.stack([text])
    src_pos = np.array([i+1 for i in range(text.shape[1])], dtype=np.float64)
    src_pos = np.stack([src_pos])
    sequence = torch.from_numpy(text).cuda().long()
    src_pos = torch.from_numpy(src_pos).cuda().long()
    torch.onnx.export(model.module,(sequence,src_pos), './fastwave.onnx', verbose=True, input_names=['mel'], output_names=['wav_output'])

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by doctor-xiang** [comment]
sorry ,the onnx file is large ,i cannot upload

**Comment by hariharans29** [comment]
Usually such errors point to a model conversion error. What this error means is that there is a node that should have inputs of type T (homogeneous), for example: inputs all of type float or all of type double. In your case, there are inputs of type T: atleast one of which are float and one of which are double. It is is hard to say which node is problematic without the model.  Can you share this data with the project that helped you obtain the ONNX model ? They should be able to help. See very similar discussion here: https://github.com/microsoft/onnxruntime/issues/1764

As an aside: any reason why you are using the 0.4.0 version of ONNXRuntime ?

**Comment by li-xx-5** [comment]
@hariharans29   thank you .i try to convert the input type to float. By the way,which version of ONNXRuntime should i use?thank you.

**Comment by li-xx-5** [comment]
@hariharans29.   0.5 version should i use?

**Comment by hariharans29** [comment]
The problem is not with your input, it is with the model. Two edges in the model graph that need to be of same type are actually of different types. The explanation is almost exact to the one in the linked issue. Please contact the project that helped you get the converted ONNX model.

Please use a later ORT release - 1.5.x

**Comment by hariharans29** [comment]
But upgrading OrT wont solve this issue- you need to fix the model most likely

**Comment by x534045903** [comment]
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (/context_path/layer1/layer1.1/Mul_4) Op (QLinearMul) [TypeInferenceError] inputs are expected to have tensor type.
What happened when I encountered this error while statically quantifying the onnx model?
