### ISSUE TITLE
How to set the input of multi input network？

### ISSUE THREAD

**Issue by eekarot** [microsoft/onnxruntime#5582]
Is there a C + + demo for multiple input networks？

**Comment by pranavsharma** [comment]
Take a look at the 'override_initializer' testcase that uses multiple inputs and outputs. https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_inference.cc.
You can also refer this issue: https://github.com/microsoft/onnxruntime/issues/2250.

**Comment by eekarot** [comment]
> * Take a look at the 'override_initializer' testcase that uses multiple inputs and outputs. https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_inference.cc.
> * You can also refer this issue: #2250.

I have solved this problem, tks
