### ISSUE TITLE
Using DNNL is slower

### ISSUE THREAD

**Issue by lawlict** [microsoft/onnxruntime#5615]
Hi, guys. I find a phenomenon that with the configuration of ORT_ENABLE_ALL, the ResNet34 model without any acceleration runs faster than dnnl acceleration. 

**Setting**
The command I build onnxruntime is: 
```
./build.sh --config Release --build_shared_lib --parallel --use_dnnl
```

**Details**
The model I use is torch.models.resnet34, and inputs are size of [1, 3, 224, 224].
```
import torch
import torchvision

model = torchvision.models.resnet34()
print(model)

x = torch.zeros(1,3,224,224)
torch.onnx.export(
    model, x, 'model.onnx', verbose=False, input_names=['input'], output_names=['output']
)
```
The C++ code for speed testing is:
```
#include <assert.h>
#include <vector>
#include "core/session/onnxruntime_cxx_api.h"
// #include "core/providers/dnnl/dnnl_provider_factory.h"
#include "time.h"
#include <string>
#include <unistd.h>

int main(int argc, char* argv[]){
    const char* model_path = "model.onnx";
    assert(access(model_path, 0) == 0);
    Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");
    Ort::SessionOptions session_options;
    session_options.SetIntraOpNumThreads(1);
    session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
    // OrtSessionOptionsAppendExecutionProvider_Dnnl(session_options, 1);
    Ort::Session session(env, model_path, session_options);

    size_t input_tensor_size = 1 * 3 * 224 * 224;
    std::vector<int64_t> input_node_dims = {1, 3, 224, 224};
    std::vector<float> input_tensor_values(input_tensor_size, 0);
    auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
    Ort::Value input_tensor = Ort::Value::CreateTensor<float>(
        memory_info, input_tensor_values.data(), input_tensor_size,
        input_node_dims.data(), input_node_dims.size()
    );

    std::vector<const char*> input_node_names = {"input"};
    std::vector<const char*> output_node_names = {"output"};
    int ntimes = 100;
    clock_t t1 = clock();
    for(int i = 0; i < ntimes; i++){
        auto output_tensors = session.Run(Ort::RunOptions{nullptr},
            input_node_names.data(), &input_tensor, 1, output_node_names.data(), 1);
    }
    printf("Time cost for %d times: %.2f seconds\n", ntimes, (clock() - t1) * 1.0 / CLOCKS_PER_SEC);
    return 0;
}
```
**Result**
The time costs of no acceleration VS dnnl acceleration (by uncommenting correspoding lines above) are:
```
no acceleration: 19.3s
dnnl acceleration: 21.5s
```

Experiments are carried out on a single core of Intel CPU. So is this a normal phenomenon? Or is there any error in my code?
Thanks!

**Comment by tracysh** [comment]
Hi, @lawlict, your test is fine. The default CPU execution provider also has acceleration to handle CNNs using an intermediate tensor format (NCHWc). The DNNL provider isn't fusing the Add operations to also use this intermediate format, so performance is lowered by repeatedly switching tensor formats. The default CPU provider does this Add fusion.

**Comment by lawlict** [comment]
Hi, @tracysh, thank you for your help. So for other providers, eg. OpenVINO and TensorRT, is there the similar problem like DNNL?

**Comment by tracysh** [comment]
@lawlict, it will depend on what the providers decide to do with the graph. I haven't attempted to build the OpenVINO provider recently to measure how that performs with this model.
