### ISSUE TITLE
  When using onnxruntime to load the ONNX model, the following error is reported:

### ISSUE THREAD

**Issue by lightwithshadow** [microsoft/onnxruntime#5643]
**InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:ConvTranspose_0 : No Op registered for ConvTranspose with domain_version of 12**

I m not sure on why this error occurs,   Looking forward to your reply ！ thx

**Comment by snnn** [comment]
The node has a some thing ONNX Runtime doesn't support yet.

**Comment by snnn** [comment]
If you're interested to get more detailed info, you may set a breakpoint at the  KernelRegistry::VerifyKernelDef
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/framework/kernel_registry.cc#L117

To see why it returned false.
