### ISSUE TITLE
Different results on different computers.

### ISSUE THREAD

**Issue by vanjoe** [microsoft/onnxruntime#5667]
I'm running the same model with the same inputs, on my dev machine and in my CI pipeline I'm seeing slightly different results from onnx runtime. My code to run is basically:

```
 session = onnxruntime.InferenceSession(model_.SerializeToString())
 i0 = session.get_inputs()[0].name
 outputs = session.run([], {i0: input_array})
```
The differences are slight, for instance my dev machine gets `-1.8208287954330444` and the CI pipeline gets `-1.8208290338516235` So my model's accuracy isn't impacted, but I'm trying to get my tests to have reproducible results.

Is there any place obvious I should look to try rectify this?

**Comment by snnn** [comment]
In general, onnx runtime and most of the math libs(like blas, mkl) do not output reproducible results. Because of rounding off errors, in general  (a+b)+c != a + (b+c). Some libs can provide reproducible results but that comes with a very high cost.

**Comment by CapJunkrat** [comment]
I also suffer from this issue. I got different results on different machines. I quantized models on different machines and the evaluation results are off by 1%.  I wonder which lib difference would cause this offset? How can I mitigate this difference?

**Comment by DimitrisSevastakis** [comment]
@snnn From your example it is logical that the order of the operations affects the result. However having a fixed network structure and fixed weights, i would expect the order of operations also to be fixed, thus i would also expect given the same input, the same output to be produced on all machines (at the very least if the two machines in question both have an intel CPU). 
Can you please elaborate why that would not be the case?
