### ISSUE TITLE
Compile error in C++ API header

### ISSUE THREAD

**Issue by xkszltl** [microsoft/onnxruntime#5673]
**Describe the bug**

In our custom ops code, we hit a compile error when using ort master.
gcc build passed but llvm build failed.

```
[INFO] [801] /usr/local/include/onnxruntime/core/session/onnxruntime_cxx_api.h:522:14: error: 'this' argument to member function 'CreateKernel' has type 'const Ort::contrib::XXXXXXOp', but function is not marked const
[INFO] [802]       return static_cast<const TOp*>(this_)->CreateKernel(*api, info); };
[INFO] [803]              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master
- GCC/Compiler version (if compiling from source): llvm 11
- CUDA/cuDNN version: 11.1/8

**Comment by yuslepukhin** [comment]
These are not member functions. We will need to figure out how to tell llvm better.

**Comment by yuslepukhin** [comment]
Does your class/struct that implements CreateKernel() has it marked const?

**Comment by RyanUnderhill** [comment]
@xkszltl Is the CreateKernel member function of your custom op class (const Ort::contrib::XXXXXXOp) not marked as const?

**Comment by xkszltl** [comment]
Will check.
Is there an API change, given it works for released versions?

**Comment by xkszltl** [comment]
It's not.
We'll add that.
Could you help us double confirm if it's gonna work with previous releases as well after adding const?

**Comment by RyanUnderhill** [comment]
@xkszltl Yeah, anything in the C++ headers doesn't affect the ABI at all as it's just a wrapper over the C API. So this will still be backwards compatible. The const change was made just a few days ago to be more correct.
