### ISSUE TITLE
What datatype should be used for float16 in C++?

### ISSUE THREAD

**Issue by isty2e** [microsoft/onnxruntime#5679]
I am testing inference with a fp16 model, which is generated by `convert_float_to_float16()` in onnxmltools. However, even with hours of googling and digging into source code, I am still unsure what is the correct way to do FP16 inference with C++.

I first tried to use `uint16_t`, but obviously it did not match `float16` datatype specified for inputs. There is no mapping from `ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT16` to native C type, and even when I tried mapping `half_float::half` in http://half.sourceforge.net/ to `ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT16` with something like
```
template <>
struct TypeToTensorType<half_float::half> { static constexpr ONNXTensorElementDataType type = ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT16; };
```
, it just did not work. What is the recommended way of using float16 data in C++?

**Comment by tianleiwu** [comment]
You can find an example here:
https://github.com/microsoft/onnxruntime/blob/e00ad83f2b3181eb6e3901fcf78a0d00c0306a04/onnxruntime/test/providers/cpu/tensor/tensor_op_test.cc#L186

**Comment by isty2e** [comment]
Uh, let me elaborate a bit. The definition for `MLFloat16` is nowhere in the header files in distributed binaries, so I wonder what should be done to actually use `MLFloat16`. I'm not experienced in C++, so maybe I am missing a simple thing.

**Comment by tianleiwu** [comment]
You can find the definition in  https://github.com/microsoft/onnxruntime/blob/db9c1308a5c6f159d49f9466e5104c59375eb57c/include/onnxruntime/core/framework/data_types.h#L55-L56

You can include the header file data_types.h in your code.

**Comment by isty2e** [comment]
I am assuming a scenario such that the a user with downloaded onnxruntime binary compiles an application. In that case, he will not have `data_types.h` unless this repository is cloned. Is this inevitable?

**Comment by tianleiwu** [comment]
I looked at the zip file in release binary, and it does not contain data_types.h. I think user might meet such problem using onnxruntime binary.

@pranavsharma to look at support float16 in onnxruntime binary.

**Comment by pranavsharma** [comment]
You can use [this](https://stackoverflow.com/a/60047308/12627730) to convert a float to float16 and then call CreateTensorWithDataAsOrtValue with type=ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT16. I guess we should've an example in our tests to demonstrate it. We'll add one. For now this should work.

**Comment by isty2e** [comment]
I have already tried that before like this:
```
    inputTensors.emplace_back(Ort::Value::CreateTensor(
      memoryInfo,
      inputBuffers->userBinaryInputBufferFP16,
      inputNodeSizes[0],
      inputNodeShape[0].data(),
      inputNodeShape[0].size(),
      ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT16
    ));
```
, however the tensor could be not created and the application terminated in runtime with `abort() has been called` error.

**Comment by yuslepukhin** [comment]
Our API does not provide any conversions. 
The user is assumed to have the input values in the user supplied buffer as we don't want to do any copying as the inputs tend to be very large. The data type in question for float16 (as well as bfloat16) is really expressed in terms of uint16_t and it is possible to use it in C API. However, there is a shortcoming in C++. I am working to have this working along with a working example.

**Comment by yuslepukhin** [comment]
To feed a float16 into the API, you can call a non-templated version of Ort::Value::CreateTensor() and pass a pointer to the buffer. The last argument must have a value of ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT16. Each float16 is assumed to be of size uitn16_t which is two bytes. 
The above referenced PR allows you to use a templated version. You can call CreateTensor<Ort::Float16_t>() which will do the same thing for you as above but will automatically set the last argument.

**Comment by yuslepukhin** [comment]
@isty2e Your idea of feeding the data could have worked. What makes you think it did not work?

**Comment by yufenglee** [comment]
Alternatively, we can add a Cast (float->fp16) node on the model input. In this way, the model takes in float and then cast it to fp16 internally.

**Comment by pranavsharma** [comment]
> Alternatively, we can add a Cast (float->fp16) node on the model input. In this way, the model takes in float and then cast it to fp16 internally.

I would rather choose a solution that doesn't impact the time spent in Run(), even if it's minimal :-).

**Comment by yufenglee** [comment]
> > Alternatively, we can add a Cast (float->fp16) node on the model input. In this way, the model takes in float and then cast it to fp16 internally.
> 
> I would rather choose a solution that doesn't impact the time spent in Run(), even if it's minimal :-).

For most language, like C++, it doesn't have fp16 support natively. And in general, the actual input of model is fp32, so you need to cast fp32 to fp16 anyway.

**Comment by yufenglee** [comment]
> > > Alternatively, we can add a Cast (float->fp16) node on the model input. In this way, the model takes in float and then cast it to fp16 internally.
> > 
> > 
> > I would rather choose a solution that doesn't impact the time spent in Run(), even if it's minimal :-).
> 
> For most language, like C++, it doesn't have fp16 support natively. And in general, the actual input of model is fp32, so you need to cast fp32 to fp16 anyway.

For sure, we need to have API support for fp16. This is an alternative.

**Comment by isty2e** [comment]
> @isty2e Your idea of feeding the data could have worked. What makes you think it did not work? The above PR does essentially what you wanted to do.

I thought so, but the application was terminated at runtime while creating the tensor. FP32 counterpart just worked.

**Comment by yuslepukhin** [comment]
> > > > Alternatively, we can add a Cast (float->fp16) node on the model input. In this way, the model takes in float and then cast it to fp16 internally.
> > > 
> > > 
> > > I would rather choose a solution that doesn't impact the time spent in Run(), even if it's minimal :-).
> > 
> > 
> > For most language, like C++, it doesn't have fp16 support natively. And in general, the actual input of model is fp32, so you need to cast fp32 to fp16 anyway.

The part of the actual input to the model fp32 is not true.

**Comment by yuslepukhin** [comment]
> > @isty2e Your idea of feeding the data could have worked. What makes you think it did not work? The above PR does essentially what you wanted to do.
> 
> I thought so, but the application was terminated at runtime while creating the tensor. FP32 counterpart just worked.
The issue here is that we do not do any validation. If the buffer is shorter than the supplied shape we can read beyond the mapped memory. If you supply fp32 and say it is fp16, no conversion is taking place and we simply interpret fp32 bits as two consecutive fp16 which is garbage. We, of course, read only half of the buffer and do not SEGFAULT but it does not mean it works.

**Comment by isty2e** [comment]
> > The issue here is that we do not do any validation. If the buffer is shorter than the supplied shape we can read beyond the mapped memory. If you supply fp32 and say it is fp16, no conversion is taking place and we simply interpret fp32 bits as two consecutive fp16 which is garbage. We, of course, read only half of the buffer and do not SEGFAULT but it does not mean it works.
The data were exactly sized and converted to `uint16_t` beforehand, where both the aforementioned method and one using `half_float::detail::float2half<std::round_to_nearest>` have been tested. That's why I opened this issue in the first place. For the time being, I am just attaching FP16 <-> FP32 casting nodes in the input/output layers.

**Comment by yuslepukhin** [comment]
What is the library that you use? Where `half_float` comes from?

**Comment by isty2e** [comment]
> What is the library that you use? Where `half_float` comes from? Is it possible for you to share the model or a minimal repro model where experience the crash?

`half_float` is from http://half.sourceforge.net/, but it is a minor detail; I have tested various methods including those two. A sample model is here: [b10_fp16.zip](https://github.com/microsoft/onnxruntime/files/5503264/b10_fp16.zip), which is quantized with onnxmltools. The crash happens exactly at `CreateTensor`.

**Comment by yuslepukhin** [comment]
> inputNodeShape[0].size(),
This must be bytes count not element count.

**Comment by isty2e** [comment]
Oh indeed. Now the model runs without any problem.

**Comment by dlml** [comment]
How to input fp16 format data, can you give a code example ？

**Comment by dlml** [comment]
@isty2e Can you give a code example ？

**Comment by tgeffroyModuleus** [comment]
Is a code sample available now?

So, the only solution is to add a cast layer in the model?

**Comment by yuslepukhin** [comment]
Please, let us know what is missing [here](https://github.com/microsoft/onnxruntime/blob/main/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L123)

**Comment by tgeffroyModuleus** [comment]
Thanks, I'll try that when possible. For now, I have patched my model to force float32 on the output.

**Comment by zx-lhb** [comment]
> To feed a float16 into the API, you can call a non-templated version of Ort::Value::CreateTensor() and pass a pointer to the buffer. The last argument must have a value of ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT16. Each float16 is assumed to be of size uitn16_t which is two bytes. The above referenced PR allows you to use a templated version. You can call CreateTensorOrt::Float16_t() which will do the same thing for you as above but will automatically set the last argument.

hi, I create input tensor this way, but lt does not work, did I missed something? 
```cpp
Ort::Value input_tensor = Ort::Value::CreateTensor(memory_info, input_tensor_values.data(),
					patchSize[0]*patchSize[1]*patchSize[2], input_node_dims.data(), 5,
					ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT16);
```
