### ISSUE TITLE
TRT FP16 compilation fails on SSD model "could not build engine for fused node"

### ISSUE THREAD

**Issue by joba01** [microsoft/onnxruntime#5709]
**Describe the bug**
1) Onnx SSD model (converted from Tensorflow) works with TRT in normal (FP32) mode, but fails when FP16 is activated with:
    sess_onnx = onnx.InferenceSession(model_file, sess_options, providers)
  File "D:\sources\venv\tf\lib\site-packages\onnxruntime\capi\session.py", line 195, in __init__
    self._create_inference_session(providers, provider_options)
  File "D:\sources\venv\tf\lib\site-packages\onnxruntime\capi\session.py", line 205, in _create_inference_session
    sess.initialize_session(providers or [], provider_options or [])
onnxruntime.capi.onnxruntime_pybind11_state.EPFail: [ONNXRuntimeError] : 11 : EP_FAIL : TensorRT EP could not build engine for fused node: TensorrtExecutionProvider_TRTKernel_graph_tf2onnx_1_1

2) TRT compiler seems to fail, without any output from time to time, depending on the model (for the small model ~10% of the time, for the big model 90% of the time), when compilation was succsessful it is stable. This seems to be influenced by the model size, maybe some heuristic for graph partitioning/subgraph creation.

3) Resize Operation is available as TRT operation, but is not converted

Follow up from #3414

**Urgency**
urgend

**System information**
- OS Platform and Distribution:
Windows 10/Server 2019

- ONNX Runtime installed from:
source (Tag 1.5.2)

- ONNX Runtime version:
1.5.2
- Python version:
3.7

- Visual Studio version (if applicable):
2019

- GCC/Compiler version (if compiling from source):
-
- CUDA/cuDNN version:
11.0 Update 1/CuDNN 8
- GPU model and memory:
T4 and Quadro 6000
(on Linux with 1080-TI, here it does not fail, but maybe because it has no FP16 support and is therefore skipped)

**To Reproduce**
- Describe steps/code to reproduce the behavior.
set ORT_TENSORRT_FP16_ENABLE=1
initialize and run model:
python onnxtest.py

- Attach the ONNX model to the issue (where applicable) to expedite investigation.
send me a mail to johannes.bannhofer@gmail.com and you will get a download link to the model

**Expected behavior**
model compiles

**Screenshots**
Node TRTKernel_graph_tfgraph_tfonnx_1 seems to fail
![image](https://user-images.githubusercontent.com/4116408/98218164-bd11ca00-1f4b-11eb-872e-2f12af357778.png)

**Additional context**
From the Release Notes of Nvidia TRT
"Fixed Bugs: For Windows users with CUDA 11.0, some fusions were not enabled. This means there was a performance loss of around 10% - 60% for networks like BERT and YOLO3. The performance loss depends on the precision used and batch size. This issue has been fixed in this release."

sounded promising, tested with latest TRT version same result.

**Comment by joba01** [comment]
Tried to recreate with smaller examples from the official samples/model zoo:
* Mnist -> working
* yolo3 -> working

**Comment by joba01** [comment]
update to 1.)
- I extracted the problematic subgraph, when executing with trtexec, it has a more detailed reason:
[11/06/2020-15:14:34] [E] [TRT] C:\source\builder\cudnnBuilderWeightConverters.cpp (541) - Misc Error in nvinfer1::cudnn::transformWeightsIfFP::<lambda_9def2ea0b858a2ce9a8e2397846e3c27>::operator (): 1 (Weights are outside of fp16 range. A possible fix is to retrain the model with regularization to bring the magnitude of the weights down.)
[11/06/2020-15:14:34] [E] [TRT] C:\source\builder\cudnnBuilderWeightConverters.cpp (541) - Misc Error in nvinfer1::cudnn::transformWeightsIfFP::<lambda_9def2ea0b858a2ce9a8e2397846e3c27>::operator (): 1 (Weights are outside of fp16 range. A possible fix is to retrain the model with regularization to bring the magnitude of the weights down.)
[11/06/2020-15:14:34] [E] Engine creation failed
[11/06/2020-15:14:34] [E] Engine set up failed

Is there a possibility how this logs can be activated in ort?

**Comment by jywu-msft** [comment]
thanks for all the details and your PR this morning.
we'll look into seeing if these errors can be surfaced in ORT for failed TRT engine builds.

**Comment by joba01** [comment]
For 3. Resize:
solved
For others: depending on the opset there are different combinations of 'coordinate_transformation_mode' and 'mode' possible that are not becoming clear from nvidias TRT operators description.

checkout buildin_op_importers.cpp DEFINE_BUILTIN_OP_IMPORTER(Resize)
or build from source with debug information, I just saw in the source, that there are a lot of asserts that would point out what is the problem.

**Comment by joba01** [comment]
follow up question, maybe somebody can confirm this:
When building/adding the TRT opensource plugins, are they automatically used by onxx-runtime? I guess yes, but I couldn't make them compile on the first try and if not I do not bother trying.

**Comment by joba01** [comment]
FP16 is working on the v1.11, no convertation errors, same input
