### ISSUE TITLE
How graph partition based on provider and assign execution to provider implemented in source code?

### ISSUE THREAD

**Issue by cookieli** [microsoft/onnxruntime#5723]
Hi:
   I have read high level design docs and  interested in sub-graph partition  and assigned to execution provider implementation 's details in source code. How can I find it. Thank you all.

**Comment by edgchen1** [comment]
Hi, perhaps you can start here:
https://github.com/microsoft/onnxruntime/blob/2acdc3cd8290c2395c95fcc5f33e719c2abb0fe3/onnxruntime/core/framework/graph_partitioner.cc#L237
https://github.com/microsoft/onnxruntime/blob/2acdc3cd8290c2395c95fcc5f33e719c2abb0fe3/onnxruntime/core/session/inference_session.cc#L826

**Comment by cookieli** [comment]
Than you very much, it's really helpful for me.
