### ISSUE TITLE
coding bug

### ISSUE THREAD

**Issue by cqray1990** [microsoft/onnxruntime#5735]
/onnxruntime_cxx_inline.h:219:69: error: no ‘Ort::SessionOptions& Ort::SessionOptions::SetLogSeverityLevel(int)’ member function declared in class ‘Ort::SessionOptions
i don't why this errors always raise,i find SetLogSeverityLevel in class Ort::SessionOptions,but still raise this errors!,

can you help me,thank you so much

**Comment by edgchen1** [comment]
Hi, can you please provide details about how you are calling the API or an example of how to reproduce the error?
