### ISSUE TITLE
Quantization for LSTM

### ISSUE THREAD

**Issue by slevental** [microsoft/onnxruntime#5747]
**Is your feature request related to a problem? Please describe.**
For mobile platforms is important to preserve as much space as possible, but currently onnx/ort models that use lstm/gru are not quantizable. Also, it’s not clear whether there is an optimization based on Arm neon vectorized int8. 

Currently, Pytorch supports some of these capabilities, but onnx runtimes is so much better in every other way for inference.

**System information**
- ONNX Runtime version (you are using):
1.5.0

**Describe the solution you'd like**
Dynamic quantization for lstm operations (int8) also supported for custom build used at mobile

**Describe alternatives you've considered**
Pytorch uses https://github.com/pytorch/QNNPACK

**Comment by yufenglee** [comment]
It is in progress #5595, and will be available in 1.6.

**Comment by yufenglee** [comment]
#5595 was merged into master. Please have a try.

**Comment by slevental** [comment]
@yufenglee I've tried it, works great, thanks!

**Comment by azraelkuan** [comment]
hi, any update about gru?
