### ISSUE TITLE
C api Package Url invalid. (https://aka.ms/onnxruntime-release)

### ISSUE THREAD

**Issue by Alan-Turing-Ko** [Microsoft/onnxruntime#577]
**Describe the bug**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:
- Python version:
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pranavsharma** [comment]
This will get fixed soon in the next day or two when we release 0.3.0. For now you can also use the NuGet pkg [here](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/).
