### ISSUE TITLE
Building with "--minimal_build" fails

### ISSUE THREAD

**Issue by Linux13524** [microsoft/onnxruntime#5786]
**Describe the bug**
Im trying to build onnxruntime with `--minimal_build` as described in [ONNX Runtime for Mobile Platforms](https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_for_Mobile_Platforms.md), but getting the following error:

```
[ 41%] Building CXX object CMakeFiles/onnx_proto.dir/onnx/onnx-ml.pb.cc.o
In file included from /home/lkloeckner/onnxruntime/cmake/external/protobuf/src/google/protobuf/map_type_handler.h:34,
                 from /home/lkloeckner/onnxruntime/cmake/external/protobuf/src/google/protobuf/map.h:49,
                 from /home/lkloeckner/onnxruntime/cmake/external/protobuf/src/google/protobuf/generated_message_table_driven.h:34,
                 from /home/lkloeckner/onnxruntime/build/Linux/MinSizeRel/onnx/onnx-ml.pb.h:26,
                 from /home/lkloeckner/onnxruntime/build/Linux/MinSizeRel/onnx/onnx-ml.pb.cc:4:
/home/lkloeckner/onnxruntime/cmake/external/protobuf/src/google/protobuf/parse_context.h: In instantiation of ‘bool google::protobuf::internal::ExpectTag(const char*) [with unsigned int tag = 186]’:
/home/lkloeckner//onnxruntime/build/Linux/MinSizeRel/onnx/onnx-ml.pb.cc:1130:73:   required from here
/home/lkloeckner/onnxruntime/cmake/external/protobuf/src/google/protobuf/parse_context.h:397:17: error: comparison is always false due to limited range of data type [-Werror=type-limits]
  397 |     return *ptr == tag;
      |            ~~~~~^~~~~~
/home/lkloeckner/onnxruntime/cmake/external/protobuf/src/google/protobuf/parse_context.h: In instantiation of ‘bool google::protobuf::internal::ExpectTag(const char*) [with unsigned int tag = 162]’:
/home/lkloeckner/onnxruntime/build/Linux/MinSizeRel/onnx/onnx-ml.pb.cc:2768:73:   required from here
/home/lkloeckner/onnxruntime/cmake/external/protobuf/src/google/protobuf/parse_context.h:397:17: error: comparison is always false due to limited range of data type [-Werror=type-limits]
cc1plus: all warnings being treated as errors
```

I tried with `v1.5.1`, `v1.5.3` and latest master (2a87108431b6851f5b453434a3d6ca4f5fbcd8d8).

Normal build without `--minimal_build` does work.

Any idea?

**System information**
- OS Platform and Distribution: Fedora 32
- ONNX Runtime version: 1.5.3
- Python version: 3.8.6
- GCC/Compiler version: 10.2.1

**To Reproduce**
Trying to build with: `./build.sh --config=MinSizeRel --build_shared_lib --minimal_build --disable_ml_ops --disable_exceptions --skip_tests --include_ops_by_config required_operators.config`

`required_operators.config` contains `ai.onnx.ml;1;TreeEnsembleClassifier`

**Expected behavior**
Successful build

**Full Log**

[full_log.txt](https://github.com/microsoft/onnxruntime/files/5530832/full_log.txt)

**Comment by Linux13524** [comment]
Small update: Just tried to build it with gcc-9 and it works fine. Can someone reproduce the error with gcc-10?

**Comment by snnn** [comment]
Yes, I tried gcc 10 and saw this error. It doesn't related to the "--minimal_build" build flag.

**Comment by snnn** [comment]
I will close this PR for now, because it is not an onnnxruntime bug. When protobuf v3.16.0 is released, I will bring it in and the problem will be gone.
