### ISSUE TITLE
Error when Loading with C#

### ISSUE THREAD

**Issue by csharpandpython** [Microsoft/onnxruntime#581]
**Describe the bug**
I was trying to load and run onnx model which was converted from Scikit learn with OnnxMLTools python. But when loading the model, I got "Attempted to read or write protected memory. This is often an indication that other memory is corrupt." Below is stack info.

"at Microsoft.ML.OnnxRuntime.NativeMethods.OrtGetTensorElementType(IntPtr typeAndShapeInfo)\r\n   at Microsoft.ML.OnnxRuntime.InferenceSession.GetMetadataFromTypeInfo(IntPtr typeInfo)\r\n   at Microsoft.ML.OnnxRuntime.InferenceSession.GetOutputMetadata(UInt64 index)\r\n   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath, SessionOptions options)\r\n   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath)\r\n   at TestMLNet.Program.Main(String[] args) in C:\\Users\\Tangram\\source\\repos\\TestSolution\\TestMLNet\\Program.cs:line 20"

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): Nuget
- ONNX Runtime version: 0.2.1
- Python version: 3.6
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Describe steps/code to reproduce the behavior:

**Expected behavior**
Load and run model without any error

**Screenshots**

**Additional context**
Converted model has one tensor_type input, one tensor_type output, and one sequence_type output. You can check below.

name: "RandomForestClassifier"
  input {
    name: "input"
    type {
      tensor_type {
        elem_type: FLOAT
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 743
          }
        }
      }
    }
  }
  output {
    name: "label"
    type {
      tensor_type {
        elem_type: INT64
        shape {
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  output {
    name: "probabilities"
    type {
      sequence_type {
        elem_type {
          map_type {
            key_type: INT64
            value_type {
              tensor_type {
                elem_type: FLOAT
              }
            }
          }
        }
      }
    }
  }

**Comment by jignparm** [comment]
Support for sequence and map type models is available in master branch currently, and will available in the 0.3 release of the packages.

Refer to this example usage : https://github.com/Microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs#L528

**Comment by pranavsharma** [comment]
Please re-open if 0.3.0 release doesn't fix your issue. Thanks!
