### ISSUE TITLE
ONNX model inferencing issue - numpy array vs tensor

### ISSUE THREAD

**Issue by karajend** [microsoft/onnxruntime#5844]
I’m trying to do inferencing using an onnx model and running into issues while passing numpy arrays to it – model output is always 0. Works fine if I convert a tensor to numpy array and then pass let. Please let me know if there anything I’m doing wrong / if this is a known issue. Tried using onnxruntime 1.3/1.6.

```
def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

dummy_input = torch.randn(1, 219)
x = np.random.rand(1, 219)

Works correctly:
ort_inputs = {sess.get_inputs()[0].name: to_numpy(dummy_input)} #to_numpy(dummy_input)
ort_outs = sess.run(None, ort_inputs)
print(ort_outs[0])

Doesn't work:
ort_inputs = {sess.get_inputs()[0].name: x} #to_numpy(dummy_input) #[[0.0]*219]
ort_outs = sess.run(None, ort_inputs)
print(ort_outs[0])
```

**Comment by yuslepukhin** [comment]
Typically, we want to specify the type and the shape since input tensors will need it
`x = np.random.rand(1, 219).astype(float32).reshape([whatever])`

**Comment by karajend** [comment]
Thanks for the suggestion! I actually do do .astype("float32") - fails otherwise; still running into issue.

I've tried converting numpy array->tensor->numpy array but still doesn't work (but tensor->numpy array works).

**Comment by karajend** [comment]
I think this is more to do with numpy arrays that are randomly generated since non-random numpy arrays work as expected - thanks!

**Comment by georgen117** [comment]
@karajend I ran into this same issue using a randomly generated source. Did you find a way to work around random number or did you just use actual input?
