### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Fatal error: adaptive_avg_pool2d is not a registered function/op

### ISSUE THREAD

**Issue by GeneralJing** [microsoft/onnxruntime#5845]
recently, I am working on model transformation deployment.I can change the pytorch model to onnx format and pass through the onnx.checker.check_model() function. But when I using the onnxruntime load the model, it occurs the error. It looks like the op is not supported.

**Comment by hariharans29** [comment]
`adaptive_avg_pool2d` is not part of the ONNX spec: https://github.com/onnx/onnx/blob/master/docs/Operators.md

This is a converter issue (even though the ONNX checker passes). Please raise this issue with PyTorch.
