### ISSUE TITLE
Qauntized distilbert model is not working well on different machines

### ISSUE THREAD

**Issue by customer101** [microsoft/onnxruntime#5849]
**Describe the bug**
I have converted DistilBert model to onnx using [this](https://github.com/huggingface/transformers/blob/master/src/transformers/convert_graph_to_onnx.py) script, with quantization option on. It runs perfectly on my machine, but when my friend tried it on his machine the quantized model returns unexpected results.

**System information**
- Linux Ubuntu 18.04:
- ONNX Runtime installed using pip
- ONNX Runtime version: 1.5.2
- Python version: 3.6.9

**Machine 1(Works Fine)**
```
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Model name: Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
CPU MHz: 2294.608
BogoMIPS: 4589.21
Flags: (same flags as in Machine 2 except avx512_vnni)
```
**Machine 2(Problem in running quantized model)**
```
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Model name: Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz
BogoMIPS: 4589.21
Flags: (same flags as in Machine 1 except md_clear)
```

Based on above description, it's maybe related to not having VNNI in Machine 2, is there a way to ensure that the quantization will work on all machines?

**Comment by zhanghuanrong** [comment]
Thanks for reporting. Onnxruntime does some optimizing to utilizing avx512 vnni. We will investigate it why it has issue without vnni. Could you tell us what is "unexpected results" ?  running exception or value different? how many those different are. If possible, please share us with input that cause such issue.

**Comment by customer101** [comment]
Thanks @zhanghuanrong, I also tried to run the model on another machine, and the result is awful. What I meant by "unexpected results" is that the model gives weird predictions even for easy input examples. Numerically, the accuracy drops significantly from 97.8%(quantized model on vnni machine) to 64.9%.

**Comment by prashantbudania** [comment]
Yeah, I am also encountering something very similar. As per this (https://github.com/microsoft/onnxruntime/issues/5667), I knew that the results weren't going to be exactly reproducible on different hardware but I am seeing a huge difference in the model's predictions on the VNNI and the non-VNNI machines. And I also know that there are a few more optimizations 
(https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Graph_Optimizations.md) done for the VNNI machines but even after disabling all optimizations (ORT_DISABLE_ALL), I was unable to reproduce the results of the quantized models on the VNNI and the non-VNNI machines. Is there any optimization setting for which the results would be reproducible or at least very similar? I am using GCP N1 (non-vnni) and N2 (vnni) machines for my experiments.

**Comment by yufenglee** [comment]
@customer101 and @prashantbudania , we uses [VPMADDUBSW ](https://en.wikichip.org/wiki/x86/avx512_vnni) on non-vnni machine. This instruction uses int16 to hold accumulation of 2 pairs of int8 mul ( C= A0*B0 + A1*B1, C is int16, A,B is in8 and C is int16), so it overflows for large number. For models with weight concentrating around 0 (for example, models with weight subject to Gaussian distribution approximately), the overflow is not an issue, but for models with weight distributes equally or not concentrating away from 0, the overflow becomes a big issue.

We provide an option [reduce_range ](https://github.com/microsoft/onnxruntime/blob/9ec1ed42a809170b87474f5822c4557101812399/onnxruntime/python/tools/quantization/quantize.py#L143) to reduce the quantization range to [-64, 64] for int8 and [0, 127] to avoid the overflow. Please re-quantize your model with this option and I think it can get back most of the accuracy loss.

**Comment by customer101** [comment]
I tried [quantize_dynamic](https://github.com/microsoft/onnxruntime/blob/9ec1ed42a809170b87474f5822c4557101812399/onnxruntime/python/tools/quantization/quantize.py#L190) instead, setting `reduce_range=False`, and the result is as expected; The accuracy didn't drop and the model output is meaningful. I also tries `reduce_range=True` but the accuracy is slightly lower.
Thanks @yufenglee
