### ISSUE TITLE
Performance issue with operator Einsum on CPU

### ISSUE THREAD

**Issue by xadupre** [microsoft/onnxruntime#5897]
**Describe the bug**
Implementation of Einsum is much slower than pytorch or tensorflow for some equations. For equation `bsnh,btnh->bnts`, the Einsum decomposition does 3 transpose, 1 matrix multiplication, 1 final transpose. This last transpose has a huge cost. Transpose is never parallelized on CPU.

![image](https://user-images.githubusercontent.com/22452781/99974560-6278ca80-2da1-11eb-95d9-3874cd4a50ae.png)

First graph is computing time, second graph is the ratio `numpy / tested implementation`. The current onnxruntime implementation is twice faster than numpy, as fast as an implementation which does not transpose.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- ONNX Runtime installed from (source or binary): from github
- ONNX Runtime version:
- Python version: 3.7
- Visual Studio version (if applicable): Community Edition

**Expected behavior**
The operator is much slower than

**Comment by pranavsharma** [comment]
@xadupre - is this still an issue? is it affecting any production models? cc @hariharans29

**Comment by xadupre** [comment]
I wrote a tool to replace einsum by a sequence of standard operators. We can this issue.
