### ISSUE TITLE
x86 Python Wheel shows error message

### ISSUE THREAD

**Issue by OliverUlm** [microsoft/onnxruntime#590]
**Describe the bug**
When building an x86 version of onnxruntime including wheels it will build and at least in cursory testing run fine on a 32 bit Version of Python (as expected given that the C Version supports x86). However a UserWarning is shown, that the 32bit Architecture is unsupported.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 0.3.0
- Python version: 3.6 x86
- GCC/Compiler version (if compiling from source): VS2017

**To Reproduce**
./build.bat --config RelWithDebInfo --build_wheel --x86 => create 32bit wheel
pip install onnxruntime-0.3.0-cp36-cp36m-win32.whl => install wheel
python => start python interactively
import onnxruntime as rt => results in the error

**Expected behavior**
Given that x86-32 in general is supported by onnxruntime the python Version should not show this message.

**Additional context**
I am planning to integrate deep learning models into an existing C/C++ application running on Industry PC Hardware that is only 32 bit capable. Most DeepLearning Frameworks only support 64 bit Scenarios, so it seems like a perfect use case for onnxruntime. The Python Version is used due to preprocessing being done through other Python libraries, so it would be preferrable to trigger the model evaluation from Python as well. All this is running through the embeddable Python Distribution.

**Comment by snnn** [comment]
how did you build it?

**Comment by OliverUlm** [comment]
I followed the build instructions as outlined here [https://github.com/Microsoft/onnxruntime/blob/master/BUILD.md](https://github.com/Microsoft/onnxruntime/blob/master/BUILD.md)

The one difference is that I added --x86 to target 32 bit (it's one of the Parameters documented in build.py) as my development machine is x64 and therefore the build process would otherwise have defaulted to an x64 build.

**Comment by pranavsharma** [comment]
Our list of officially released and supported packages doesn't include python x86. Your contributions are most welcome. Thanks!

**Comment by OliverUlm** [comment]
Oh, I see - I mistakenly assumed that given that the base library supports x86-32 through the C-API it would be supported with Python bindings as well. I have a few more Questions:

1. Are there known technical issues with the x86-32 Python bindings or is it merely not covered by tests and therefore unsupported?
2. Might it be considered to support x86-32 Python officially in the future? If so - how could I help this along through contributions (I'd assume work would center around making sure the Python bindings against the C-API are unit tested, given that the core already supports x86-32).

**Comment by snnn** [comment]
Hi @OliverUlm , 
I got a similar message:

"/home/onnxruntimedev/Release/onnxruntime/capi/onnxruntime_validation.py:22: UserWarning: Unsupported architecture (32bit). ONNX Runtime supports 64bit architecture, only."

Is it the same thing you saw? But I guess it is just a warning. It won't block the execution.

**Comment by pranavsharma** [comment]
> Oh, I see - I mistakenly assumed that given that the base library supports x86-32 through the C-API it would be supported with Python bindings as well. I have a few more Questions:
The python bindings don't use the C API interface. It statically links onnxruntime and uses the internal C++ API.

> 
> 1. Are there known technical issues with the x86-32 Python bindings or is it merely not covered by tests and therefore unsupported?
We've never tried building since we don't have any requirements.

> 2. Might it be considered to support x86-32 Python officially in the future? If so - how could I help this along through contributions (I'd assume work would center around making sure the Python bindings against the C-API are unit tested, given that the core already supports x86-32).
We don't have any such requirements, but you're most welcome to contribute. However we won't be releasing official packages.

**Comment by akavalar** [comment]
There may be additional pybind11 flags needed for the shared object to compile properly on 32-bit architecture. I had to similarly fiddle with the build script when building onnxruntime for Python 2.7 (see here: https://github.com/akavalar/onnxruntime & especially the list of tweaks needed here: https://github.com/Microsoft/onnxruntime/compare/master...akavalar:master), and in the end I got it to work flawlessly.

It does seem what you've described is just a warning as pointed out by @snnn though.

**Comment by shawncal** [comment]
Unsurprisingly, this warning also pops up when importing on ARM build (Raspberry Pi).

**Comment by pranavsharma** [comment]
@OliverUlm would you like to contribute towards fixing the warning message? As I said before, currently, we don't have any plans to support python wheels for x86 arch, but you're more than welcome to contribute. The python bindings use the internal C++ API, not the C API.
