### ISSUE TITLE
Slower than caffe in GPU mode.

### ISSUE THREAD

**Issue by Alan-Turing-Ko** [Microsoft/onnxruntime#591]
**Describe the bug**
Slower than caffe in GPU mode.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 10
- ONNX Runtime installed from (source or binary):
Install Nuget package (Microsoft.ML.OnnxRuntime.Gpu 0.2.1)
- ONNX Runtime version:
- Python version:
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
I've compare inference time with my own model in caffe and onnxruntime.
My model contains conv, slice, eltwise, pool layers.
And caffe always give better inference speed.

Following is the code I used on onnxruntime.
`OrtEnv* env;
	CHECK_STATUS(OrtCreateEnv(ORT_LOGGING_LEVEL_WARNING, "test", &env));
	// initialize session options if needed
	OrtSessionOptions* session_option = OrtCreateSessionOptions();

	OrtSessionOptionsAppendExecutionProvider_CUDA(session_option, 0);
	OrtSetSessionThreadPoolSize(session_option, 1);

	//*************************************************************************
	// create session and load model into memory
	OrtSession* session;
	const wchar_t* model_path = L"d:\\model.onnx";
	CHECK_STATUS(OrtCreateSession(env, model_path, session_option, &session));`

And rest part is same as sampleMnist.
Aren't there any other options to improve performance?
Hope any suggestions.

**Comment by ybrnathan** [comment]
Could you please help share your models so we can repro and take a look?

**Comment by faxu** [comment]
Hi @Alan-Turing-Ko: are you able to share your specific model so we can better advise on options to improve the perf? We have had good results with other models compared to Caffe, but it really depends on the details of the model itself. Thanks.

**Comment by faxu** [comment]
@Alan-Turing-Ko could you please share your model? Otherwise we cannot help troubleshoot the issue. We have had good results with perf with other models in ONNX Runtime compared to Caffe. Thanks!

**Comment by faxu** [comment]
Please reopen the issue with the model or more details if this requires further investigation.
