### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by buxdehude** [microsoft/onnxruntime#5931]
Hey I have a model that was exported from pytorch into the onnx format and i want to use the onnxruntime for inferncing on a Win7 PC. 
But during execution i get the warning that windows 7 isn't supported only Win10 and above. 
Am I missing something or is there support planned in the future since the last roadmap from Sept. states that Win7 will be supported.  
I'm using onnxruntime Version '1.5.2'

Any help would be appreciated.

**Comment by thiagocrepaldi** [comment]
Windows 7 is not supported as it reached end of line in January 2020

**Comment by booksuper** [comment]
I use onnx runtime 1.12.1 in Windows 7 and report an error directly, does this version not support win7?
