### ISSUE TITLE
OrtSessionOptionsAppendExecutionProvider_DML interface is not robust

### ISSUE THREAD

**Issue by deischi** [microsoft/onnxruntime#5933]
**Is your feature request related to a problem? Please describe.**
The OrtSessionOptionsAppendExecutionProvider_DML is using just the enumeration order of the hardware adapter. 
This order number can change (e.g. when devices are added or removed).

**System information**
onnxruntime 1.5.2

**Describe the solution you'd like**
Change (or extend) the interface to pass an ID of the hardware adapter (e.g. the AdapterLuid) instead of the order number.

**Describe alternatives you've considered**
User can do the mapping of ID to enumeration order, just before calling OrtSessionOptionsAppendExecutionProvider_DML.
But this still leaves a small time window when order numbers can change.

**Additional context**
This is most likely only relevant for systems with multiple varying GPUs, e.g. laptops with Hydra, or eGPUs.

**Comment by pranavsharma** [comment]
cc @jeffbloo

**Comment by wchao1115** [comment]
@deischi Thanks for your feedback. The adapter index as defined in the `OrtSessionOptionsAppendExecutionProvider_DML` function is guaranteed to point to the same device until the next adapter change event occurs upon which the DXGIFactory object will need to be recreated with the new set of adapters enumerated. The app should register for the [adapter change event](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_6/nf-dxgi1_6-idxgifactory7-registeradapterschangedevent) and react to the event appropriately. Please take a look at this [sample](https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12xGPU/src/D3D12xGPU.cpp) for more detail.

When an adapter is removed, the subsequent calls to DXGI and Direct3D on the device created from the removed adapter will also fail with DXGI_ERROR_DEVICE_REMOVED failure code. This means that if the chosen adapter is removed during the call to `OrtSessionOptionsAppendExecutionProvider_DML`, the function would likely fail. However, you might still want to double check if the chosen adapter index still maps to the expected Luid after a successful call just to be sure. Take a look at `QueryForAdapterEnumerationChanges` and `ValidateActiveAdapter` method in the sample code for the idea.
