### ISSUE TITLE
ONNX Runtime and Execution Providers

### ISSUE THREAD

**Issue by jay-karan** [microsoft/onnxruntime#5951]
I am further asking the following questions (in a new issue as suggested) with relevance and continuation to the replies in the [comment](https://github.com/microsoft/onnxruntime/issues/232#issuecomment-734060575) by @pranavsharma 

- CPU was provided under Execution Providers in the design document. May I understand the reason?

- How is standalone execution provider different from execution provider along with ONNX Runtime?

- Why is the need of hardware independent optimizations (after converting ONNX model to in-memory graph rep) ?

- How are the sub-graphs after partitioning scheduled on to different EPs? Do we need to write a script defining the priorities for scheduling?

- As few execution providers are not having the implementation of few onnx operators, would it be possible to implement those operators in execution providers? (to avoid the fallback onto cpu and hit bad with performance)

Trying to connect all the dots of understanding. Any support with patience is a great help to me. Thank you.

**Comment by pranavsharma** [comment]
> I am further asking the following questions (in a new issue as suggested) with relevance and continuation to the replies in the [comment](https://github.com/microsoft/onnxruntime/issues/232#issuecomment-734060575) by @pranavsharma
> 
> * CPU was provided under Execution Providers in the design document. May I understand the reason?
ORT ships with a default EP that can run all ONNX ops on the CPU. This is what we call the CPU EP; it is implemented by ORT and is the fallback for all ops. Other EPs like openvino also run on the CPU but may not implement all ONNX ops since they're outside ORT's control. May be our CPU EP should've been called "Default ORT CPU" EP.

> * How is standalone execution provider different from execution provider along with ONNX Runtime?
Already answered this before.

> * Why is the need of hardware independent optimizations (after converting ONNX model to in-memory graph rep) ?
To improve performance. You can read more here https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Graph_Optimizations.md.

> * How are the sub-graphs after partitioning scheduled on to different EPs? Do we need to write a script defining the priorities for scheduling?
No script is needed. The order in which you register EPs with ORT session determines the preference order for partitioning. EPs that are registered earlier are considered first for assigning nodes/sub-graphs to them. Please read the design doc linked earlier.

> * As few execution providers are not having the implementation of few onnx operators, would it be possible to implement those operators in execution providers? (to avoid the fallback onto cpu and hit bad with performance)
Yes. However, many EPs are external to ORT (for e.g. openvino and tensorrt) and not open source. Hence they're outside ORT's control.

> 
> Trying to connect all the dots of understanding. Any support with patience is a great help to me. Thank you.

**Comment by jay-karan** [comment]
- Why haven't few execution providers could not implement few onnx operators? (what could be the possible reasons?)

- ONNX Operators are [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md) and the kernels for these operators are unavailable. So, how are these operators being implemented by ORT for default EP? And also, how are these implemented by other EPs into their packages? 

- 
If I am using TensorRT without ORT. It is fair to assume high-level flow as below: 
**Input Graph->TensortRT IR Representation -> Optimizations -> Inference.**                            (1)

Say now, if I am using TensorRT as EP in ORT.
May I ask to complete/update the below flow: 
**ONNX Graph -> In-Memory -> Optimizations by ORT -> Partitioning -> Scheduling subgraphs -> Subgraph on TensorRT-> ....... -> ....... ->.........**                                     (2)

Does the TensorRT IR (similar to in (1) ) will be formed on the subgraph generated from the partitioning by ORT in (2)?

[The above is asked to validate few conclusions on standalone EPs. Hope it doesn't confuse you]

- Will onnxruntime-gpu package enable CUDAExecutionP?

**Comment by pranavsharma** [comment]
> * Why haven't few execution providers could not implement few onnx operators? (what could be the possible reasons?)
Can't say for sure. One possible reason is that ONNX has many opset versions with variations in the operator specs in new versions. It's not always possible for them to keep up.

> * ONNX Operators are [here](https://github.com/onnx/onnx/blob/master/docs/Operators.md) and the kernels for these operators are unavailable. So, how are these operators being implemented by ORT for default EP?
ONNX defines the spec for the ops. The implementation is done by ORT. You can see them [here](https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/core/providers/cpu).

> And also, how are these implemented by other EPs into their packages?
I can't answer this. You can read about this on documentation pages for the individual EPs.

> 
> If I am using TensorRT without ORT. It is fair to assume high-level flow as below:
> **Input Graph->TensortRT IR Representation -> Optimizations -> Inference.** (1)
> 
> Say now, if I am using TensorRT as EP in ORT.
> May I ask to complete/update the below flow:
> **ONNX Graph -> In-Memory -> Optimizations by ORT -> Partitioning -> Scheduling subgraphs -> Subgraph on TensorRT-> ....... -> ....... ->.........** (2)
> 
> Does the TensorRT IR (similar to in (1) ) will be formed on the subgraph generated from the partitioning by ORT in (2)?
> 
> [The above is asked to validate few conclusions on standalone EPs. Hope it doesn't confuse you]
Please see [this](https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/TensorRT-ExecutionProvider.md).

> 
> * Will onnxruntime-gpu package enable CUDAExecutionP?
Yes.

**Comment by jay-karan** [comment]
- May I ask more about the extensibility options specified in [here](https://github.com/microsoft/onnxruntime/blob/master/docs/InferenceHighLevelDesign.md#extensibility-options). What is the need of adding a new operator?

- The capability of the execution provider if a subgraph can be executed is determined using the GetCapability() API right. How do I use it? Are there any usage examples?

- Is the tuning [here](https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Perf_Tuning.md#tuning-performance-for-specific-execution-providers) only limited to default execution providers or can we extend to openvino, tensorrt, etc also?

**Comment by pranavsharma** [comment]
> * May I ask more about the extensibility options specified in [here](https://github.com/microsoft/onnxruntime/blob/master/docs/InferenceHighLevelDesign.md#extensibility-options). What is the need of adding a new operator?

ONNX supports only a limited set of operators (compared to Tensorflow or Pytorch). There are cases when your use case falls outside this list.

> * The capability of the execution provider if a subgraph can be executed is determined using the GetCapability() API right. How do I use it? Are there any usage examples?

You don't use this API directly. It's called internally during the initialization phase.

> * Is the tuning [here](https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Perf_Tuning.md#tuning-performance-for-specific-execution-providers) only limited to default execution providers or can we extend to openvino, tensorrt, etc also?

Tuning tips for individual EPs can be found on the individual EP pages here https://github.com/microsoft/onnxruntime/tree/master/docs/execution_providers.

**Comment by pranavsharma** [comment]
Reopen if there are more questions.
