### ISSUE TITLE
Hello, how to limit the number of CPU cores to 1

### ISSUE THREAD

**Issue by wuxiaolianggit** [microsoft/onnxruntime#5952]
Hello, how to limit the number of CPU cores to 1

**Comment by wuxiaolianggit** [comment]
Hello, how to limit the number of CPU cores to 1 @mattetti

**Comment by pranavsharma** [comment]
https://github.com/microsoft/onnxruntime/blob/master/docs/FAQ.md#how-do-i-force-single-threaded-execution-mode-in-ort-by-default-sessionrun-uses-all-the-computers-cores

**Comment by wuxiaolianggit** [comment]
Thank you for your reply @mattetti
