### ISSUE TITLE
Does onnxruntime support AMD GPU?

### ISSUE THREAD

**Issue by mathmax12** [microsoft/onnxruntime#5959]
**Describe the bug**
I installed the onnxruntime and my onnx models work as expected on cpu with onnxruntime.
After install the onnxruntime-gpu and run the same code I got:
```
Traceback (most recent call last):
  File "run_onnx.py", line 14, in <module>
    import onnxruntime as rt
  File "/home/xiaosong/anaconda3/lib/python3.7/site-packages/onnxruntime/__init__.py", line 13, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
  File "/home/xiaosong/anaconda3/lib/python3.7/site-packages/onnxruntime/capi/_pybind_state.py", line 9, in <module>
    import onnxruntime.capi._ld_preload  # noqa: F401
  File "/home/xiaosong/anaconda3/lib/python3.7/site-packages/onnxruntime/capi/_ld_preload.py", line 12, in <module>
    _libcublas = CDLL("libcublas.so.10", mode=RTLD_GLOBAL)
  File "/home/xiaosong/anaconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcublas.so.10: cannot open shared object file: No such file or directory
```

**System information**
-  Linux Ubuntu 18.04
- ONNX Runtime installed from   binary: pip install onnxruntime-gpu
- ONNX Runtime version: onnxruntime-gpu-1.4.0
- Python version: 3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: AMD RX580

Does the onnxruntime-gpu doesn't support AMD GPU?

**Comment by j-paulus** [comment]
(Disclaimer: I'm just a user of ORT, not developer.)

The out-of-the-box library versions support only CUDA as GPU under Linux. It should be possible to build your own ORT with MiGraphX / ROCm support for acceleration on some AMD GPUs.

**Comment by thiagocrepaldi** [comment]
I dont think ROCm is supported by ORT yet

**Comment by HectorSVC** [comment]
@weixingzhang

**Comment by weixingzhang** [comment]
MIGraphX: https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/MIGraphX-ExecutionProvider.md
ROCm: a build guide at the bottom of this link: https://github.com/microsoft/onnxruntime/blob/master/BUILD.md. At present, BERT-L training and GPT2 fine tuning can be run on AMD MI100 with data parallel.

**Comment by unexploredtest** [comment]
@weixingzhang The file no longet exists?

**Comment by scxiao** [comment]
I think build instructions for all EPs were moved to other places, no idea who did that. Here is the build instruction for MIGraphX EP: https://www.onnxruntime.ai/docs/how-to/build/eps.html#amd-migraphx

**Comment by yjwong** [comment]
I recently built onnxruntime with ROCm EP support:

```
./build.sh --config Release --build_wheel --update --build --parallel --cmake_extra_defines CMAKE_PREFIX_PATH=/opt/rocm/lib/cmake ONNXRUNTIME_VERSION=$ONNXRUNTIME_VERSION onnxruntime_BUILD_UNIT_TESTS=off --use_rocm --rocm_home=/opt/rocm
```

Unfortunately running an `InferenceSession` on something that works with CPU produces this error:

```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Reshape node. Name:'regression_submodel/pyramid_regression_reshape/Reshape' Status Message: HIP error hipErrorNotReady:hipErrorNotReady
```
