### ISSUE TITLE
scikit-learn,lgbm,xgb model loading in C#?

### ISSUE THREAD

**Issue by hanzigs** [microsoft/onnxruntime#5960]
I dont know C#, working out to do prediction of ONNX model in C#

For the Keras model, i have worked out as below, its working good.
In Python
```
ONNXContent = KerasONNXModel.SerializeToString()
ONNXSess = onnxruntime.InferenceSession(ONNXContent)
OnnxPrediction = ONNXSess.run('dense_5988', {'dense_5985_input': PayLoad})[0]
Output: [array([[0.5043213]], dtype=float32), array([[0.5043213]], dtype=float32)]
```
Same in C#
```
string modelPath = @"Model\KerasONNXModel.onnx";
var Session = new InferenceSession(modelPath);

float[] kerasdata = new float[] { 1.0f, -0.99999341f, -0.33333333f, -0.46923783f, -0.78571429f, 0.20588235f,0.27416429f, -0.09020249f, -0.21286791f, 0.49370467f, 0.03809259f, -0.00608993f,-0.70959487f, 0.08142171f, -0.3643947f, 0.43285425f, -0.14156616f, -0.12051195f,0.00494169f };
var dimensions = new int[] { 1, 19 };
Tensor<float> tensorA = new DenseTensor<float>(kerasdata, dimensions);

var inputs = new List<NamedOnnxValue>();
var t1 = NamedOnnxValue.CreateFromTensor<float>("dense_5985_input", tensorA);
inputs.Add(t1);
var results = Session.Run(inputs);

var prediction = results.First().AsTensor<float>().First();
Console.WriteLine(prediction);
```
Above works Perfect
```
0.5043213
C:\Program Files\dotnet\dotnet.exe (process 19956) exited with code 0.
```

For Scikit_learn, LGBM, and XGB, we have another property to add which is the "sess.get_outputs()[1].name"
In Python
```
ONNXContent = RandomForestONNXModel.SerializeToString()
ONNXSess = onnxruntime.InferenceSession(ONNXContent)
OnnxPrediction = ONNXSess.run(['output_label', 'output_probability'], {'float_input': PayLoad}) 
Output: [array([1], dtype=int64), [{0: 0.48559892177581787, 1: 0.5144010782241821}]]
```
May i know how to work this out in C#, Thanks

**Comment by hariharans29** [comment]
Sorry - I don't understand the question here. Are you asking how to consume multiple outputs in C# from Run() ? What we get back from Run() in C# is a `IDisposableReadOnlyCollection<DisposableNamedOnnxValue>`. You have a collection of DisposableNamedOnnxValue that you can parse as you wish. You consumed the first (and only result) in this line - 

`var prediction = results.First().AsTensor<float>().First();`

You can consume multiple outputs like this line here - https://github.com/microsoft/onnxruntime/blob/2d9dcc4576f86b3eb6705dba1f8699eb52140b4e/csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs#L507

Please also check the execution flow here - https://github.com/microsoft/onnxruntime/blob/2d9dcc4576f86b3eb6705dba1f8699eb52140b4e/csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs#L266

Hope this answers your question or atleast points you in the right direction

**Comment by hanzigs** [comment]
Hi @hariharans29 
Thank for the reply and
sorry my bad I didn't explain the question
For Keras we get one array value, so we do
```
var inputs = new List<NamedOnnxValue>();
var t1 = NamedOnnxValue.CreateFromTensor<float>("dense_5985_input", tensorA);
inputs.Add(t1);
var results = Session.Run(inputs);
```
for other models the format of Run having the output probability as well, we get two value array like [{0: 0.48559892177581787, 1: 0.5144010782241821}]]
```
ONNXSess.run(['output_label', 'output_probability'], {'float_input': PayLoad}) 
```
My question was how to do C# code for that prediction, So now i understood like we have to use foreach to fetch the results, hope i am right
Thanks

**Comment by hariharans29** [comment]
Yes you are right. Just iterate through the output of Run() and consume each one individually.
