### ISSUE TITLE
onnxruntime-gpu built for Python 3.8/Windows doesn't support CUDA versions other than 10.2

### ISSUE THREAD

**Issue by ivanst0** [microsoft/onnxruntime#5962]
**Describe the bug**
Python 3.8+ on Windows currently supports only CUDA 10.2.

**System information**
- OS Platform and Distribution: Windows 10
- ONNX Runtime installed from: source
- Python version: 3.8+
- CUDA version: 10.1, 11.0, 11.1

**To Reproduce**
- Build onnxruntime-gpu package with CUDA 10.1/11.0/11.1.
- Install the resulting wheel into Python environment.
- Try to import onnxruntime while having the corresponding version of CUDA installed on the system.

**Expected behavior**
onnxruntime-gpu on Python 3.8+/Windows should support the same version of CUDA as previous versions of Python.

**Additional context**
PR https://github.com/microsoft/onnxruntime/pull/5956 added support for Python 3.8+ on Windows, but the version of CUDA was hard-coded to 10.2.

**Comment by jywu-msft** [comment]
why did we hardcode CUDA 10.2 instead of just checking CUDA_PATH which gets set after a proper CUDA installation on Windows?

**Comment by ivanst0** [comment]
When multiple versions of CUDA Toolkit are installed on the system CUDA_PATH might point to the wrong version.

This could be solved in a generic way by having a .py file (generated during CMake build) which contains the CUDA version. It could be then imported from onnxruntime/python/_pybind_state.py. This would allow referencing the CUDA version used to build the package.

**Comment by jywu-msft** [comment]
> When multiple versions of CUDA Toolkit are installed on the system CUDA_PATH might point to the wrong version.
> 
> This could be solved in a generic way by having a .py file (generated during CMake build) which contains the CUDA version. It could be then imported from onnxruntime/python/_pybind_state.py. This would allow referencing the CUDA version used to build the package.

Simpler to just respect CUDA_PATH
That is the purpose of CUDA_PATH. you should set CUDA_PATH to the version of CUDA that you want to use if you have multiple versions installed.
e.g. see: https://forums.developer.nvidia.com/t/switch-different-versions-of-cuda-in-win10/54999

your suggestion has merit though, if we want to validate the proper dependencies exists on the deployment target.

**Comment by ivanst0** [comment]
As of version 1.6.0, **onnxruntime-gpu** Python package relies at runtime on PATH (Python 3.7 and earlier) or CUDA_PATH (Python 3.8 and newer), so it is possible to build and use it with either CUDA 10.x or 11.x, assuming the relevant environment variable is set correctly.
