### ISSUE TITLE
onnxruntime-gpu package not available for Python 3.8 on Windows

### ISSUE THREAD

**Issue by ivanst0** [microsoft/onnxruntime#5963]
**Describe the bug**
[PyPI index](https://pypi.org/project/onnxruntime-gpu/1.5.2/#files) offers both Linux and Windows edition of onnxruntime-gpu package for Python 3.5/3.6/3.7, but only Linux edition is available for Python 3.8.

**Urgency**
For many teams this is the only blocker to upgrade to Python 3.8.

**System information**
- OS Platform and Distribution: Windows 10
- ONNX Runtime installed from: PyPI
- ONNX Runtime version: 1.5.2
- Python version: 3.8

**Expected behavior**
If the Linux edition of a package is available for a particular version of Python, Windows edition should be available as well.

**Additional context**
PR https://github.com/microsoft/onnxruntime/pull/5956 enabled building onnxruntime-gpu package for Python 3.8 on Windows.

**Comment by snnn** [comment]
Package published. https://test.pypi.org/project/ort-gpu-nightly/
