### ISSUE TITLE
Python3.5 nightly builds failing

### ISSUE THREAD

**Issue by ganik** [microsoft/onnxruntime#5972]
Nightly builds are failing due to PEP8 validation failure.
![image](https://user-images.githubusercontent.com/18757686/100637508-d0fce180-32e7-11eb-95e5-3af0fee38a30.png)

**Comment by ganik** [comment]
This is caused by this commit: https://github.com/microsoft/onnxruntime/commit/015fbb3dbb8547294171990e1104cdf101be4a7d
Assigning to @ivanst0

**Comment by ivanst0** [comment]
Sorry about that. The issue is fixed in PR https://github.com/microsoft/onnxruntime/pull/5874.
@snnn, when do you expect https://github.com/microsoft/onnxruntime/pull/5874 to go in?

**Comment by snnn** [comment]
Validating
