### ISSUE TITLE
Safe distribution of a source code together with model weights

### ISSUE THREAD

**Issue by izaharkin** [microsoft/onnxruntime#5985]
Hi!

First of all, thanks to all the onnxruntime and Microsoft team for such a cool neural network inference and training accelerator.

I am interested in the commercial distribution of some code I have written in C++ with the use of onnxruntime. The point is if I compile it as an executable, I still need to deliver it with the model weights file. It makes the whole system vulnerable to reverse-engineering (model architecture details, exact model weights, etc.) and hence easily compromisable.

The question is, is there any way to build the system consisting of several .cpp and .onnx files to a binary, library, or any other format for safe distribution and usage? 

Thank you very much!

**Comment by snnn** [comment]
Sure.  You can use the xxd tool  to convert your model file to a C source file.
See: https://unix.stackexchange.com/questions/176111/how-to-dump-a-binary-file-as-a-c-c-string-literal

But avoid reverse-engineering of your C/C++ program is another topic,  sorry I can't provide further advices.

**Comment by izaharkin** [comment]
Thank you so much, will definitely try it.
