### ISSUE TITLE
Support GraphTransformer in C API

### ISSUE THREAD

**Issue by harrysummer** [Microsoft/onnxruntime#599]
I am trying to use ONNX Runtime in my project and I want to enable using GraphTransformer for better speed. I was using the internal structures of ONNX Runtime and I want to switch to C API for a lower maintainance cost. However, I cannot find `GraphTransformer` interfaces in the C API. Are there any plans to add it?

**Comment by linkerzhang** [comment]
It's being planned as "There will be options designed in C API layer to allow customers to specify graph transformation behavior. ", instead of exposing all graph transformation APIs in C API layer.

**Comment by harrysummer** [comment]
@linkerzhang Thanks for the explanation! I don't expect C API to hook any customized transformer. Just enabling exisitng GraphTransfomer's through C API to good for me.

**Comment by askhade** [comment]
@harrysummer graph transformers have been made available through CAPI now. You can enable them via setting the levels. Level1 will turn on all the basic transformers like redundant node eliminations where as level2 will enable all fusions and other complex transformers. Default is set to level 1... 
You can refer to this example:
https://github.com/Microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp
