### ISSUE TITLE
Bug with control flow op in ORT: Graph output does not exist in the graph.

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnxruntime#5991]
ORT does not support values outside of subgraph to be used as subgraph output. A small example graph (%x.1):

```
graph(%x.1 : Float(3, 4, 5, strides=[20, 5, 1], requires_grad=0, device=cpu)):
 …
  %7 : Float(3, 4, 5, strides=[20, 5, 1], requires_grad=0, device=cpu) = onnx::If(%6)
    block0():
      %8 : Float(requires_grad=0, device=cpu) = onnx::Constant[value={10}]()
      %9 : Float(3, 4, 5, strides=[20, 5, 1], device=cpu) = onnx::Add(%x.1, %8)
      -> (%9)
    block1():
      -> (%x.1)
  return (%7)

```

Error message: void onnxruntime::Graph::InitializeStateFromModelFileGraphProto() This is an invalid model. Graph output (x.1) does not exist in the graph.

Repro model: 
[subgraph_output.zip](https://github.com/microsoft/onnxruntime/files/5625886/subgraph_output.zip)

**Comment by npuichigo** [comment]
Any progress here?

**Comment by BowenBao** [comment]
@npuichigo This issue was later resolved with model changes: inserting an identity node. Closing.
