### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by guotong1988** [microsoft/onnxruntime#6021]
**Describe the bug**

Linux-CPU inference

Java code

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 

CentOS 

- ONNX Runtime installed from (source or binary):

I don't know whether onnx is installed in the Linux machine. 

I can not run `yum install libgomp` in the machine.

I put `libgomp.so.1` into the jar-file and use `System.setProperty("java.library.path", ... )`

- ONNX Runtime version:
in `pom.xml` (I think it is the way onnx installed)
```
  <dependency>
            <groupId>com.microsoft.onnxruntime</groupId>
            <artifactId>onnxruntime</artifactId>
            <version>1.5.2</version>
  </dependency>
```

- Python version: 3.6

- GCC/Compiler version (if compiling from source): dont know

**Additional context**
I can run the onnx model inference in my Macbook in java.
I use python to export the onnx-model-file and try to load it by java.

libgomp version: `libgomp-4.8.5-44.el7.x86_64`

The exact error:
`
java.lang.UnsatisfiedLinkError: /path/to/onnxruntime-java7108564327804271519/libonnxruntime.so: /lib64/libc.so.6: version 'GLIBC_2.14' not found (required by /path/to/onnxruntime-java7108564327804271519/libonnxruntime.so)
`
```
at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at ai.onnxruntime.OnnxRuntime.load(OnnxRuntime.java:199)
	at ai.onnxruntime.OnnxRuntime.init(OnnxRuntime.java:87)
	at ai.onnxruntime.OrtEnvironment.<clinit>(OrtEnvironment.java:24)
	at com.mycode.onnx_test.ScoreMNIST.main(ScoreMNIST.java:288)
```

**Comment by guotong1988** [comment]
I guess I should try Building from Source to get the `libonnxruntime.so`

**Comment by Craigacp** [comment]
What version of CentOS? It looks like 7 from the libgomp version.

@yuslepukhin What are the JNI binaries compiled on? This looks like an error with them being compiled against a newer Ubuntu.

**Comment by snnn** [comment]
CentOS 7 is in our support list. The prebuilt binary should work, unless something is wrong.

**Comment by guotong1988** [comment]
Centos6    gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC)

**Comment by guotong1988** [comment]
is it possible to run it in centos6

**Comment by Craigacp** [comment]
Even if it is, and I'll leave that to the MS people, you shouldn't install the el7 version of libgomp as that's for CentOS 7 not CentOS 6.

**Comment by guotong1988** [comment]
oh, I also downloaded a wrong libgomp

**Comment by snnn** [comment]
> is it possible to somehow run onnx in centos6?

The prebuilt binaries doesn't support it. But you can build onnxruntime from source, with the help from https://developers.redhat.com/products/developertoolset/overview

**Comment by guotong1988** [comment]
thank you!
gcc4.4 is ok? 
@snnn

**Comment by snnn** [comment]
Sorry, no. onnxruntime requires  gcc 4.8.5 and above.

**Comment by guotong1988** [comment]
Oh, centos6 is ok, but gcc 4.8.5 and above. Thank you.

**Comment by yuye2133** [comment]
could you use glibc 2.12 ?
