### ISSUE TITLE
OpenVino provider, inference in one cpu thread.

### ISSUE THREAD

**Issue by DenisYarullin** [microsoft/onnxruntime#6022]
**Describe the bug**
I cloned and built the master branch.
Set options for the session:
```
OrtOpenVINOProviderOptions options;
options.device_type = "CPU_FP32";
options.enable_vpu_fast_compile = 0;
options.device_id = "";
options.num_of_threads = 1;
session_options.AppendExecutionProvider_OpenVINO(options);
```
But the inference still occupied several cores.
I looked at the source code and there is nothing like this: `config.insert ({"CPU_THREADS_NUM", "1"});`

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: master
- Python version: 3.7
- Visual Studio version (if applicable): 2017
- CUDA/cuDNN version: 10.2/8.0+
- GPU model and memory: 2080 GTi

**Expected behavior**
Inference in one cpu thread.

**Comment by jywu-msft** [comment]
that option doesn't actually control number of cpu threads used in inferencing.
+@MaajidKhan, @smkarlap 
can we document it better?
And do we need to expose a knob to control cpu inference thread (from TBB?)

**Comment by MaajidKhan** [comment]
@DenisYarullin The option **options.num_of_threads = 1**  doesn't actually control the number of threads to be run.
It is actually setting the number of free infer_request's that would be made available for inferencing.

for example, when you set options.num_of_threads = 7, it means, now there would be 7 free separate infer_requests' available in the pool thus enabling multi threading possible. with this setting, 7 threads can be parallelly ran now.

The number of threads you want to choose should come from application level.

yes @jywu-msft I agree with you. I will add more information about this setting in the documentation just to be more clear.

Usually with Native OpenVINO when using the async inference API, it automatically takes care of number of max parallel infer requests that can be possible on the machine. say, A CPU machine has 4 cores and each core has 2 threads, we will 8 parallel infer requests set by default.

coming to our flow in UEP, we only control the number of threads to be run in parallel from application level.

@DenisYarullin 
If you want to just make use of **config.insert ({"CPU_THREADS_NUM", "1"})** option for CPU explicitly and want to infer.
you can add this option after this line https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/openvino/backends/basic_backend.cc#L47 here and recompile the code.

![image](https://user-images.githubusercontent.com/29036417/101135658-1ac03180-3632-11eb-894c-1fd5ecd0620b.png)

**Comment by DenisYarullin** [comment]
@MaajidKhan, @jywu-msft Thanks.

**Comment by Darshvino** [comment]
Hi @MaajidKhan @jywu-msft,

That line seems to be not available in the current repo. Can you please point me to where I have to change inorder to run openvino with one thread.

Thanks

**Comment by Darshvino** [comment]
I think it should be set here? : https://github.com/microsoft/onnxruntime/blob/7a298c916a4b732b025d9310f59399ab76385b7c/onnxruntime/core/providers/openvino/backends/basic_backend.cc#L134
