### ISSUE TITLE
Support AARCH64 for Java

### ISSUE THREAD

**Issue by mina-asham** [microsoft/onnxruntime#6026]
**Is your feature request related to a problem? Please describe.**
I wanted to try out onnxruntime on AARCH64, and got the following exception:

```
java.lang.IllegalStateException: Unsupported arch:aarch64
ai.onnxruntime.OnnxRuntime.initOsArch(OnnxRuntime.java:65)
ai.onnxruntime.OnnxRuntime.<clinit>(OnnxRuntime.java:36)
```

Reading the the code and checking the JAR, I don't think that this is supported:
* No branch for detection here: https://github.com/microsoft/onnxruntime/blob/v1.5.3/java/src/main/java/ai/onnxruntime/OnnxRuntime.java#L64
* And the JAR doesn't have aarch64 binaries too (Did `jar tf onnxruntime-1.5.2.jar` to check content)

However reading the main README.md and the BUILD.md files, it looks like ARM64 is supported.

**System information**
- ONNX Runtime version (you are using): All versions since Java support

**Describe the solution you'd like**
Supporting aarc64 (not necessarily on all platforms but linux is probably the go to)

**Describe alternatives you've considered**
N/A

**Additional context**
I am happy to contribute the Java loader changes here: https://github.com/microsoft/onnxruntime/blob/v1.5.3/java/src/main/java/ai/onnxruntime/OnnxRuntime.java#L64
But I don't know much about how the Maven output is built, but can take a stab at it with a few pointers?

**Comment by snnn** [comment]
The linux one was built by using the following command:
```bash
python3 /onnxruntime_src/tools/ci_build/build.py --build_dir /build --config Release --skip_submodule_sync  --parallel --build_shared_lib --build_java --use_openmp --enable_onnx_tests && cd /build/Release && make install DESTDIR=/build/linux-x64
```
source: https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/azure-pipelines/java-api-packaging-pipelines.yml

**Comment by Craigacp** [comment]
It should be fixed in main as part of the apple Silicon changes. Test that out and see if it works (as I haven't got a Linux aarch64 machine to check it with).

**Comment by mina-asham** [comment]
@Craigacp Yes, that works fine, sorry I missed the changes on master. I can confirm it built fine on Linux ARM64 (tested on Amazon Linux 2 64-bit ARM AMI).

You commit covered the required changes to build, is there an issue to modify the packaging pipeline referenced above?

**Comment by Craigacp** [comment]
I don't think there is an issue to expand the binaries shipped to maven central.

@faxu @yuslepukhin are there any plans to include ARM binaries in the onnxruntime cpu jar? Or add a different jar with ARM binaries for Linux, macOS and Windows (though I don't know if anyone has checked Java on Windows ARM)?

**Comment by faxu** [comment]
We'll evaluate this for future releases. Closing the topic as the the original issue is resolved.
