### ISSUE TITLE
Linux nightly build for training package fails

### ISSUE THREAD

**Issue by ganik** [microsoft/onnxruntime#6030]
The failure is due to #5874 

![image](https://user-images.githubusercontent.com/18757686/101122831-3ed73080-35a8-11eb-84c8-414b8dca2d84.png)

**Comment by ganik** [comment]
Assigning to @snnn

**Comment by snnn** [comment]
Edward should already fixed it in #6012.

**Comment by ganik** [comment]
Sounds good ! thx
