### ISSUE TITLE
Java CPU inference very slow

### ISSUE THREAD

**Issue by guotong1988** [microsoft/onnxruntime#6031]
**Describe the bug**
I use Linux CentOS to do the inference. The Linux CentOS is driver machine of the Apache Spark cluster.
I test the Linux CentOS use the code:
![image](https://user-images.githubusercontent.com/4702353/101151172-3c361300-365c-11eb-8557-bb78b9450b97.png)

I use 
```
        <dependency>
            <groupId>com.microsoft.onnxruntime</groupId>
            <artifactId>onnxruntime</artifactId>
            <version>1.5.2</version>
        </dependency>
```
and put `libgomp.so.1` at
![image](https://user-images.githubusercontent.com/4702353/101147604-92ed1e00-3657-11eb-95e3-54981b984730.png)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS7
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.5.2
- Python version: 3.6
- GCC/Compiler version (if compiling from source): 4.8.5

**To Reproduce**
I use python to export onnx-model-file and put it into jar.
Then I use `ScoreMnist.java` to load the onnx-model-file and inference.

**Expected behavior**
In my Macbook, It take about 20 second to inference about 10000 mnist pic.
In my Macbook I have run `brew install libgomp`.
But in the Linux CentOS7, It take about 1 second to inference 1 pic.
The code in my Macbook and Linux CentOS are all the same.

**Additional context**
I can not run `yum install libgomp` in the Linux CentOS because it is in the Apache Spark cluster.

I use java code `System.load`  to load the `libgomp.so.1` first

**Comment by guotong1988** [comment]
In my Macbook, `brew uninstall libomp` vs `brew install libomp` do not observer speed difference.

**Comment by guotong1988** [comment]
Increasing the cpu cores accelerates the speed a lot.

**Comment by guotong1988** [comment]
Java code `System.load` the `libgomp.so.1` or not, do not observe speed difference.

**Comment by Craigacp** [comment]
What's the CPU in the server, what's the CPU in the Macbook? What settings are you using on the `OrtSession` in both cases?

Standing up a spark instance inside the same JVM might be causing a bunch of gc pressure and other nonsense that slows down the computation. Are you doing the same thing on your Macbook?

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/101423977-2616a400-3935-11eb-9696-db048dc57c5e.png)

The CPU in the server is better than the Macbook.

**Comment by guotong1988** [comment]
> Increasing the cpu cores accelerates the speed a lot in Spark cluster. But still 4x slower than Macbook.

This experiments' code: 
![image](https://user-images.githubusercontent.com/4702353/101424146-80176980-3935-11eb-8058-a45714004f12.png)
The computation is in worker of Spark.

**Comment by guotong1988** [comment]
So I installed Onnx successfully?

**Comment by Craigacp** [comment]
> ![image](https://user-images.githubusercontent.com/4702353/101423977-2616a400-3935-11eb-9696-db048dc57c5e.png)
> 
> The CPU in the server is better than the Macbook.

Is it faster in a single thread? Does it have AVX-512?



> > Increasing the cpu cores accelerates the speed a lot in Spark cluster. But still 4x slower than Macbook.
> 
> This experiments' code:
> 
> ```
> val df = loadData(hiveContext).limit(1)
> 
> df.repartition(1).map(row=>{
>       ScoreMNIST.main(null)
>       (1)
>     }).show()
> ```
> 
> The computation is in worker of Spark.

So the computation happens on the spark workers or in the head node? If in the workers what resources in terms of RAM and cpu cores are assigned to the workers?

> So I installed Onnx successfully?

It's not installed, the Java version is self contained in the jar that you download from maven central (apart from libgomp, and the c standard library).

**Comment by guotong1988** [comment]
>So the computation happens on the spark workers or in the head node? If in the workers what resources in terms of RAM and cpu cores are assigned to the workers?

I try both. In worker is faster. It is 16 cores and 32G-memory

The Macbook's info:

![image](https://user-images.githubusercontent.com/4702353/101426990-02555d00-3939-11eb-9b68-dd5c368b8a61.png)

**Comment by guotong1988** [comment]
So this jar contains all the things that Onnx need to run.
```
         <dependency>
            <groupId>com.microsoft.onnxruntime</groupId>
            <artifactId>onnxruntime</artifactId>
            <version>1.5.2</version>
        </dependency>
```

**Comment by guotong1988** [comment]
> Is it faster in a single thread? Does it have AVX-512?

I will check it.

**Comment by guotong1988** [comment]
Maybe it is fast enough, I will compare the speed against Without-Onnx.

**Comment by Craigacp** [comment]
> So this jar contains all the things that Onnx need to run?
> 
> ```
>          <dependency>
>             <groupId>com.microsoft.onnxruntime</groupId>
>             <artifactId>onnxruntime</artifactId>
>             <version>1.5.2</version>
>         </dependency>
> ```

Yes, that contains everything needed to run ONNX Runtime on macOS, Linux and Windows x86_64 platforms, using the CPU provider for inference (apart from libgomp, which I'm not clear if the maven central jars are compiled to use). If you want to use a different provider like dnnl or OpenVINO you'll need to compile it from source. The GPU jar supports the CUDA provider and the CPU provider.

**Comment by guotong1988** [comment]
> apart from libgomp, which I'm not clear if the maven central jars are compiled to use

I am not sure I understand this sentence. Thank you.

**Comment by Craigacp** [comment]
> > apart from libgomp, which I'm not clear if the maven central jars are compiled to use
> 
> I am not sure I understand this sentence. Thank you.

I'm not involved in the packaging of the jars for Maven Central, so I don't know what compiler flags are used. So I don't know if OpenMP is turned on in them. I think it's changed over time.

**Comment by guotong1988** [comment]
So the jar do not contain libgomp. 

Without libgomp, the jar may not work in 100 persent?

**Comment by Craigacp** [comment]
> So the jar do not contain libgomp.
> 
> Without libgomp, the jar may not work in 100% speed?

I believe there are some alternative parallelisation mechanisms other than OpenMP, but I don't know what the performance of them is vs OpenMP.

**Comment by guotong1988** [comment]
Could you please just tell me how to turn on OpenMP in my CentOS Linux server? Thank you!

**Comment by guotong1988** [comment]
The readme said:

![image](https://user-images.githubusercontent.com/4702353/101430968-02f1f180-3941-11eb-988c-24ac81be72a6.png)

So I use java code `System.load` to load the libgomp. I think it does not mean that I have turned on OpenMP.

**Comment by Craigacp** [comment]
Looks like the Java packaging pipeline (https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/azure-pipelines/java-api-packaging-pipelines.yml#L30) does turn on OpenMP. I think using System.load to load OpenMP should turn it on, but given how low level a library it is, I'm not sure if that's sufficient (I'm mainly a Java programmer, not a dynamic loading expert). You can add it to the local library path and have it be dynamically loaded when ONNX Runtime is.

Either way, if you're using the demo MNIST model I'd be surprised if the lack of OpenMP was sufficient to slow down inference that much. I've demoed it on 4 core machines and it's much much faster than 0.25s per MNIST image. What model and data are you using?

**Comment by guotong1988** [comment]
The model:
https://github.com/onnx/tutorials/blob/master/tutorials/TensorflowToOnnx-1.ipynb

**Comment by guotong1988** [comment]
The data:
https://github.com/microsoft/onnxruntime/issues/6019

**Comment by guotong1988** [comment]
```
        <dependency>
            <groupId>org.tensorflow</groupId>
            <artifactId>tensorflow</artifactId>
            <version>1.14.0</version>
        </dependency>
```
In Macbook: 15s
In Linux CentOS server 8s


```
        <dependency>
            <groupId>com.microsoft.onnxruntime</groupId>
            <artifactId>onnxruntime</artifactId>
            <version>1.5.2</version>
        </dependency>
```
In Macbook: 10s
In Linux CentOS server 45s

**Comment by guotong1988** [comment]
@pranavsharma Any progress? Thank you!

**Comment by Craigacp** [comment]
Could you post the exact model file you're using, and what modifications you made to the `ScoreMNIST` file (as it would throw an NPE if you call main with the argument `null`)? I ran the ScoreMNIST example from the source tree using the released onnxruntime-1.5.2.jar with mnist.t and the supplied cnn_mnist_pytorch.onnx file we use as test data, on an Oracle Linux 7 machine (equivalent to RHEL/CentOS7) with two Intel Xeon E5-2699 v4 CPUs. That took around 4s.

**Comment by guotong1988** [comment]
https://drive.google.com/file/d/17pJupqlGseFw-n0V92n1t8LeorsT77nl/view?usp=sharing

I edit the code to read the data from jar.

**Comment by Craigacp** [comment]
I don't have access to that link. If it's not too big you can attach it to the issue.

**Comment by guotong1988** [comment]
sorry 
https://drive.google.com/drive/folders/1453O-FmXb2PVryDMv599bMLchC-VnjNJ?usp=sharing

**Comment by guotong1988** [comment]
```
  public static void main(String[] args) throws OrtException, IOException {
        NativeLibLoader.addNativeDir("/my_onnx/");
        NativeLibLoader.addNativeDir("my_onnx/");
        NativeLibLoader.initForOnnx();

        ScoreMNIST tmp = new ScoreMNIST();
        tmp.loadModel();
        String[] argsLocal = new String[2];
        byte[] modelArray = tmp.readAllBytesOrExit();

        System.out.println("java.library.path");
        System.out.println(System.getProperty("java.library.path"));
        for (String libName : libNamesForOnnx) {
//            System.load(tempDirectoryForOnnx + libName);
        }

        if (argsLocal.length < 2 || argsLocal.length > 3) {
            System.out.println("Usage: ScoreMNIST <model-path> <test-data> <optional:scikit-learn-flag>");
            System.out.println("The test data input should be a libsvm format version of MNIST.");
            return;
        }
        Date date = new Date();
        long startTime = date.getTime();


        try (OrtEnvironment env = OrtEnvironment.getEnvironment();
             OrtSession.SessionOptions opts = new SessionOptions()) {

            opts.setOptimizationLevel(OptLevel.BASIC_OPT);
            try (OrtSession session = env.createSession(modelArray, opts)) {

                InputStream inputData = Thread.currentThread().getContextClassLoader().getResourceAsStream("my_onnx/mnist.t");
                System.out.println("Loading data from " + inputData);

                System.out.println("Inputs:");
                for (NodeInfo i : session.getInputInfo().values()) {
                    System.out.println(i.toString());
                }

                System.out.println("Outputs:");
                for (NodeInfo i : session.getOutputInfo().values()) {
                    System.out.println(i.toString());
                }

                SparseData data = load(inputData);

                float[][][][] testData = new float[1][1][28][28];
                float[][] testDataSKL = new float[1][780];

                int correctCount = 0;
                int[][] confusionMatrix = new int[10][10];

                String inputName = session.getInputNames().iterator().next();

                for (int i = 0; i < data.labels.length; i++) {
                    if (argsLocal.length == 3) {
                        writeDataSKL(testDataSKL, data.indices.get(i), data.values.get(i));
                    } else {
                        writeData(testData, data.indices.get(i), data.values.get(i));
                    }

                    float[][] tmpData = new float[1][784];
                    for (int ii = 0; ii < testData[0][0].length; ii++) {
                        for (int iii = 0; iii < testData[0][0][0].length; iii++) {
                            tmpData[0][ii * 28 + iii] = testData[0][0][ii][iii];
                        }
                    }

                    try (OnnxTensor test =
                                 OnnxTensor.createTensor(env, argsLocal.length == 3 ? testDataSKL : tmpData);
                         Result output = session.run(Collections.singletonMap(inputName, test))) {

                        int predLabel;

                        if (argsLocal.length == 3) {
                            long[] labels = (long[]) output.get(0).getValue();
                            predLabel = (int) labels[0];
                        } else {
                            float[][] outputProbs = (float[][]) output.get(0).getValue();
                            predLabel = pred(outputProbs[0]);
                        }
                        if (predLabel == data.labels[i]) {
                            correctCount++;
                        }

                        confusionMatrix[data.labels[i]][predLabel]++;

                        if (i % 1000 == 0) {
                            System.out.println("Cur accuracy = " + ((float) correctCount) / (i + 1));
                            System.out.println("Output type = " + output.get(0).toString());
                            if (argsLocal.length == 3) {
                                System.out.println("Output type = " + output.get(1).toString());
                                System.out.println("Output value = " + output.get(1).getValue().toString());
                            }
                        }
                    }
                }

                System.out.println("Final accuracy = " + ((float) correctCount) / data.labels.length);

                StringBuilder sb = new StringBuilder();
                sb.append("Label");
                for (int i = 0; i < confusionMatrix.length; i++) {
                    sb.append(String.format("%1$5s", "" + i));
                }
                sb.append("\n");

                for (int i = 0; i < confusionMatrix.length; i++) {
                    sb.append(String.format("%1$5s", "" + i));
                    for (int j = 0; j < confusionMatrix[i].length; j++) {
                        sb.append(String.format("%1$5s", "" + confusionMatrix[i][j]));
                    }
                    sb.append("\n");
                }

                System.out.println(sb.toString());
            }
        }
        Date date2 = new Date();
        System.out.println(date2.getTime() - startTime);
        System.out.println("Done!");
    }
```

**Comment by Craigacp** [comment]
It takes 8s to run your model on the test Linux server I've got, using the default ScoreMNIST (with the features adjusted to be 784 and a flat vector). Running the same model on my 2020 15" MBP takes 6s.

I'm not sure what's going on with the setup on your machine, but it doesn't seem to be an issue with ONNX Runtime.

**Comment by guotong1988** [comment]
thank you
