### ISSUE TITLE
libgomp: Thread creation failed error

### ISSUE THREAD

**Issue by thhart** [microsoft/onnxruntime#6040]
**Describe the bug**
From time to time the whole JVM crashes with a thread error during Onnx utilization. It simply terminates, only a short notice in the console:
`libgomp: Thread creation failed: Resource temporarily unavailable`

Unfortunately I can not provide a test here. I use a "simple" network for object detection with standard tensors. The machine running on is a 32 core CPU system.
Before posting lot of environment stuff here please ask me what should be helpful to follow up.

Right now I am testing some setting by limiting OMP threads like this, will inform here how it works:
export MAGICK_THREAD_LIMIT=4
export OMP_NUM_THREADS=4

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): openSUSE Leap 15.2, 5.3.18-lp152.50-preempt, x86_64
- ONNX Runtime installed from (source or binary): com.microsoft.onnxruntime from Maven
- ONNX Runtime version: 1.5.2
- Python version: n/a
- GPU model and memory: n/a (CPU only)
- Java: OpenJDK Runtime Environment Zulu15.28+51-CA

**Comment by Craigacp** [comment]
Are you setting the intra and inter thread parameters on the `OrtSession.SessionOptions` before the session is created? Do you have multiple sessions running? And what's the stack limit set to for the user that's running the process (or the process itself if it's different)?

**Comment by thhart** [comment]
1. No I am not setting these options.
2. Yes there have been multiple sessions run in parallel, I will check to avoid this.
3. I have set the thread limit unlimited now and I am monitoring. I tested with 8192 and 32768 and both were crashing.

IMHO number 2 was not optimal of course.
However what strikes me a bit was the hard way of crashing.

**Comment by Craigacp** [comment]
The JVM can't protect against crashes in the native code, and if the OpenMP runtime is going to call `exit()` when it runs out of threads (as it does here - https://github.com/gcc-mirror/gcc/blob/16e2427f50c208dfe07d07f18009969502c25dc8/libgomp/team.c#L845, which calls https://github.com/gcc-mirror/gcc/blob/16e2427f50c208dfe07d07f18009969502c25dc8/libgomp/error.c#L80) there isn't anything that can be done about that on the Java side. It'll have the same effect on Python, C#, C etc.

Unfortunately I'm not so familiar with how OpenMP is used inside ONNX Runtime. @tlh20 any ideas what could cause this?

**Comment by guotong1988** [comment]
Have you meet the same issue https://github.com/microsoft/onnxruntime/issues/6031 ? Thank you!
What's wrong with https://github.com/microsoft/onnxruntime/issues/6031 ?

**Comment by tlh20** [comment]
When building with OpenMP, the ORT thread pool will map parallel loops onto the corresponding OpenMP constructs, e.g.: https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/platform/threadpool.h#L261-L279.

I think the first question here is whether the thread creation is failing because there are too many threads already created, or failing for some other resource-usage reason (e.g., out-of-memory).

Does the JVM create an error log (https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/felog001.html)?

**Comment by thhart** [comment]
I think it was really related to run too many jobs in parallel, thanks for checking and hints.
