### ISSUE TITLE
Nightly python packaging pipeline build fails 

### ISSUE THREAD

**Issue by ganik** [microsoft/onnxruntime#6051]
Looks like cuDNN version 8 is not installed on test VMs:

![image](https://user-images.githubusercontent.com/18757686/101258144-5d871580-36d5-11eb-8783-950e82c2c162.png)

**Comment by ganik** [comment]
#5990 looks like only possible culprit for this, assigning to @baijumeswani

**Comment by ashbhandare** [comment]
The issue was fixed by #6054
