### ISSUE TITLE
Multiple inputs and multiple outputs of Session.Run

### ISSUE THREAD

**Issue by RicardoY97** [microsoft/onnxruntime#6055]
I tried to use onnxRuntime_C ++ to infer. But my model has two input-values and  two output-values. How can I pass parameters to the Cxx-api Session.Run()?

**Comment by pranavsharma** [comment]
https://github.com/microsoft/onnxruntime/blob/master/docs/FAQ.md#how-do-i-load-and-run-models-that-have-multiple-inputs-and-outputs-using-the-cc-api

**Comment by solarflarefx** [comment]
@pranavsharma What about the equivalent for the C# API?

**Comment by pranavsharma** [comment]
We don't seem to have examples for C#, but the APIs are well documented and it should be easy to figure out. We welcome and encourage contributions. Feel free to contribute an example.
