### ISSUE TITLE
Building on Raspberry Pi 4B with OpenVINO provider does not link correctly

### ISSUE THREAD

**Issue by daves003** [microsoft/onnxruntime#6057]
**Description**
Compiling onnxruntime from source on ARMv7l (Raspberry Pi OS) with the openvino provider fails, because ld cannot find the openvino libraries.
`/usr/bin/ld: cannot find -linference_engine`
`/usr/bin/ld: cannot find -linference_engine_legacy`
I believe the error is in `cmake/onnxruntime_providers.cmake` line 624. https://github.com/microsoft/onnxruntime/blob/a046ef133aa18bda7b7ec9eeedfec4800f452d45/cmake/onnxruntime_providers.cmake#L621-L625
CMake checks to use either the directory "aarch64" or "intel64", but not "armv7l" where the libraries are actually installed. Changing this line seems to fix the issue and the build completes.

**System information**
- Raspberry Pi 4B with Rasberry Pi OS Lite (2020-12-02)
- ONNX Runtime installed from github source.
- ONNX Runtime version: latest master branch (commit a046ef133aa18bda7b7ec9eeedfec4800f452d45)
- Python version: 2.7.16 and 3.7.3
- GCC version: gcc (Raspbian 8.3.0-6+rpi1) 8.3.0
- OpenVINO version: 2021.1

**To Reproduce**
These commands are run directly on the Raspberry Pi (via ssh because it's headless):
```
# opencv and tbb should be installed
# install openvino (according to intel docs)
mkdir -p Downloads && cd Downloads
wget https://download.01.org/opencv/2021/openvinotoolkit/2021.1/l_openvino_toolkit_runtime_raspbian_p_2021.1.110.tgz
sudo mkdir -p /opt/intel/openvino
sudo tar -xf  l_openvino_toolkit_runtime_raspbian_p_2021.1.110.tgz --strip 1 -C /opt/intel/openvino
sudo apt update && sudo apt install -y cmake
source /opt/intel/openvino/bin/setupvars.sh
echo "source /opt/intel/openvino/bin/setupvars.sh" >> ~/.bashrc
sudo usermod -a -G users "$(whoami)"
sh /opt/intel/openvino/install_dependencies/install_NCS_udev_rules.sh

# reboot or logout in order for group changes to take effect

# install onnxruntime
cd ~
git clone --recursive https://github.com/microsoft/onnxruntime.git
cd onnxruntime
./build.sh --update --build --build_shared_lib --arm --config Release --use_openmp --use_openvino MYRIAD_FP16 --parallel
```

**Comment by MaajidKhan** [comment]
We have introduced find_package() changes in cmake from onnxruntime v1.8.0.
This issue of linking OpenVINO Execution Provider with OpenVINO armv7l libraries would be automatically taken care of and the build goes through successfully.

**Issue with onnxrt v1.7.2:**
https://github.com/microsoft/onnxruntime/blob/v1.7.2/cmake/onnxruntime_providers.cmake

**Fix is available from onnxrt v1.8.0:**
https://github.com/microsoft/onnxruntime/blob/v1.8.0/cmake/onnxruntime_providers.cmake

This issue can be closed. Please re-open, if you face the similar problem again.
