### ISSUE TITLE
How to use onnxruntime-tensorrt in python

### ISSUE THREAD

**Issue by ZhuoranLyu** [microsoft/onnxruntime#6062]
**Describe the bug**
Compile from source code with tensorrt, install wheel with pip but cannot import onnxruntime.

```
/data/venv-python3.8/lib/python3.8/site-packages/onnxruntime/capi/_pybind_state.py:14: UserWarning: Cannot load onnxruntime.capi. Error: 'Python version mismatch: module was compiled for Python 3.6, but the interpreter version is incompatible: 3.8.6 (default, Oct  6 2020, 03:22:36) 
[GCC 7.5.0].'.
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'.".format(str(e)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/venv-python3.8/lib/python3.8/site-packages/onnxruntime/__init__.py", line 13, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
ImportError: cannot import name 'get_all_providers' from 'onnxruntime.capi._pybind_state' (/data/venv-python3.8/lib/python3.8/site-packages/onnxruntime/capi/_pybind_state.py)
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.5.2
- Python version: 3.8.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: CUDA11 cudnn8.0
- GPU model and memory: 2080Ti
- Tensorrt: 7.1.3.4

**To Reproduce**
```
./build.sh --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ --use_tensorrt --tensorrt_home /usr/lib/x86_64-linux-gnu/  --build_shared_lib --enable_pybind  --build_wheel --parallel 6 --config Release --use_openmp --build_shared_lib 
```

```
pip install /data/project/onnxruntime/build/Linux/Release/dist/onnxruntime_gpu_tensorrt-1.5.2-cp38-cp38-linux_x86_64.whl
```

```
>>> import onnxruntime
/data/venv-python3.8/lib/python3.8/site-packages/onnxruntime/capi/_pybind_state.py:14: UserWarning: Cannot load onnxruntime.capi. Error: 'Python version mismatch: module was compiled for Python 3.6, but the interpreter version is incompatible: 3.8.6 (default, Oct  6 2020, 03:22:36) 
[GCC 7.5.0].'.
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'.".format(str(e)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/venv-python3.8/lib/python3.8/site-packages/onnxruntime/__init__.py", line 13, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
ImportError: cannot import name 'get_all_providers' from 'onnxruntime.capi._pybind_state' (/data/venv-python3.8/lib/python3.8/site-packages/onnxruntime/capi/_pybind_state.py)

```

**Comment by jywu-msft** [comment]
"/data/venv-python3.8/lib/python3.8/site-packages/onnxruntime/capi/_pybind_state.py:14: UserWarning: Cannot load onnxruntime.capi. Error: 'Python version mismatch: module was compiled for Python 3.6, but the interpreter version is incompatible: 3.8.6 (default, Oct  6 2020, 03:22:36) 
[GCC 7.5.0].'."

that warning tells you the issue. you have multiple versions of python on your system. 
When you built onnxruntime, it found python3.6 libraries, but at runtime, you are using python 3.8
please ensure your python version is consistent for build and runtime (maybe your PATH needs to be adjusted at build time, or if you are using virtual environment, make sure it's activated during build)

**Comment by ZhuoranLyu** [comment]
> "/data/venv-python3.8/lib/python3.8/site-packages/onnxruntime/capi/_pybind_state.py:14: UserWarning: Cannot load onnxruntime.capi. Error: 'Python version mismatch: module was compiled for Python 3.6, but the interpreter version is incompatible: 3.8.6 (default, Oct 6 2020, 03:22:36)
> [GCC 7.5.0].'."
> 
> that warning tells you the issue. you have multiple versions of python on your system.
> When you built onnxruntime, it found python3.6 libraries, but at runtime, you are using python 3.8
> please ensure your python version is consistent for build and runtime (maybe your PATH needs to be adjusted at build time, or if you are using virtual environment, make sure it's activated during build)

Thank you!
