### ISSUE TITLE
ConvTranspose output_shape seems wrong for dynamic input shape when auto_pad='SAME_LOWER'

### ISSUE THREAD

**Issue by jiafatom** [microsoft/onnxruntime#6067]
**Describe the bug**
ConvTranspose output_shape seems wrong for dynamic input shape when auto_pad='SAME_LOWER'

**Urgency**
none

**System information**
master

**To Reproduce**
I have a keras model and convert to ONNX. See attached please remove 'zip' at the end.
[conv_transpose.onnx.zip](https://github.com/microsoft/onnxruntime/files/5654778/conv_transpose.onnx.zip)
The python code running ORT:
```python
import numpy as np
import onnxruntime
sess = onnxruntime.InferenceSession('conv_transpose.onnx')
data1 = np.random.rand(2 * 3 * 4 * 5).astype(np.float32).reshape(2, 3, 4, 5)
data = [data1]
input_names = sess.get_inputs()
feed = zip(sorted(i_.name for i_ in input_names), data)
feed_input = dict(feed)
actual = sess.run(None, feed_input)
```
The output shape is (2,3,6,8), but keras output shape is (2,2,2,8). With some debug, the issue is that `output_shape` in `ComputePadsAndOutputShape()` is unknown for auto_pad='SAME_LOWER'. In this case, it seems wrong to apply `out_size = (in_size - 1) * stride + adj + (kernel - 1) * dilation + 1;` because there is no guarantee that `input_size`=`output_size` which is suggested by `SAME_LOWER`.

**Comment by hariharans29** [comment]
Any chance this will solve it ? - https://github.com/microsoft/onnxruntime/pull/4271

**Comment by jiafatom** [comment]
Yes it does resolve the issue for `stride=1` case. For `stride>1`, need onnx spec change, so raise an issue [there](https://github.com/onnx/onnx/issues/3153).

**Comment by hariharans29** [comment]
Makes sense, thank David. Btw - do all the new 4 keras models need stride > 1 ? Or is there s a model that uses stride == 1 ? If there is a real model that uses stride == 1 and auto_pad attribute, we can run a final verification and merge that fix in.

**Comment by jiafatom** [comment]
These fourmodel  don't use stride=1. They use strides=2 (this is the most common case)
[unet_plusplus](https://github.com/MrGiovanni/UNetPlusPlus/blob/master/keras/segmentation_models/unet/blocks.py#L49)
[unet](https://github.com/yu4u/noise2noise/blob/master/model.py#L107)
[center-net](https://github.com/xuannianz/keras-CenterNet/blob/master/models/resnet.py#L151) (this include actually two models when enable nms or not)

**Comment by hariharans29** [comment]
Quick clarification though - do we need the auto_pad attribute ? Can we use explicit padding or is it because the model consumes dynamic shaped inputs ?

**Comment by jiafatom** [comment]
Yes it is because the model consumes dynamic shaped inputs, so we have to use auto_pad.

**Comment by hariharans29** [comment]
Closing as the ORT change supporting `auto_pad` in ConvTranspose is checked-in
