### ISSUE TITLE
AttributeError: 'BertForPreTraining' object has no attribute 'layers,outputs'

### ISSUE THREAD

**Issue by Igoslow** [microsoft/onnxruntime#6096]
**Describe the bug**
could you help me? The convert of model is failed. could the checkpoint of bert convert to onnx model? I have a bug that 'BertForPreTraining' object has no attribute 'layers, output'.
**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.4.0
- Python version: 3.6.8
- Visual Studio version (if applicable): pycharm 
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: none
- GPU model and memory: cpu model

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**
enable_overwrite = False
total_runs = 100
max_sequence_length = 512
import os
cache_dir = './cache_models'
output_dir = './onnx_models'
for directory in [cache_dir, output_dir]:
if not os.path.exists(directory):
os.makedirs(directory)
from transformers import BertTokenizer
model_name_or_path = "bert-base-cased"

tokenizer = BertTokenizer.from_pretrained(model_name_or_path, do_lower_case=True, cache_dir=cache_dir)
from transformers.modeling_bert import BertForPreTraining#,BertForQuestionAnswering,BertModel
from transformers.modeling_bert import BertConfig
config = BertConfig.from_json_file('./chinese_L-12_H-768_A-12/bert_config.json')
model = BertForPreTraining.from_pretrained('./chinese_L-12_H-768_A-12/bert_model.ckpt.index', config=config, from_tf=True)

model._saved_model_inputs_spec = None

import time
import keras2onnx
output_model_path = os.path.join(output_dir, 'keras_{}.onnx'.format(model_name_or_path))

if enable_overwrite or not os.path.exists(output_model_path):
start = time.time()
onnx_model = keras2onnx.convert_keras(model, 'Bert', target_opset=10) #model.name
keras2onnx.save_model(onnx_model, output_model_path)
print("Keras2onnx run time = {} s".format(format(time.time() - start, '.2f')))

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

keras2onnx\main.py", line 71, in convert_keras
output_names = [n.name for n in model.outputs]
torch\nn\modules\module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'BertForPreTraining' object has no attribute 'outputs'

**Comment by yufenglee** [comment]
duplicated with #6089 .
