### ISSUE TITLE
Docker Image for ONNXRuntime TensorRT

### ISSUE THREAD

**Issue by sapjunior** [microsoft/onnxruntime#6101]
**System information**
- ONNX Runtime version (you are using): 1.5.2

**Describe the solution you'd like**
- These is no prebuild TensorRT integrated docker image for current version

**Comment by faxu** [comment]
We don't have a prebuilt version at this time. The dockerfile for this is available here: https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.tensorrt

Closing for now, but please re-open if there are further questions or cocnerns.
