### ISSUE TITLE
What is the best model to use with the orttraining models MNIST sample?

### ISSUE THREAD

**Issue by ZoroDerVonCodier** [microsoft/onnxruntime#6104]
What is the best model to use with the following sample below?
https://github.com/microsoft/onnxruntime/tree/master/orttraining/orttraining/models/mnist

I am currently trying to get the MNIST model in the zoo working at:
https://github.com/winnerineast/models-onnx/tree/master/vision/classification/mnist

Given that its last output is 'Plus214_Output_0' and the mnist sample seems to expect an output named 'predictions', will this sample work with the onnx model in the zoo, or should I be using a different model for the sample?

**Comment by pranav-prakash** [comment]
See the samples in https://github.com/microsoft/onnxruntime/issues/3706#issuecomment-621372668
Seems the specific training runner was designed to be used with the models generated by `orttraining/tools/mnist_model_builder`.
