### ISSUE TITLE
Offer Nuget package without PDB

### ISSUE THREAD

**Issue by daveta** [microsoft/onnxruntime#6113]
[This is logically a reactivation of https://github.com/microsoft/onnxruntime/issues/2742]

For our scenarios (deploying bots), we would like a slim deployment package so developer experience is good. 

**System information**
- ONNX Runtime version (you are using): 1.4.0

**Describe the solution you'd like**
Offer a additional Nuget package that does not contain the PDB. 

**Describe alternatives you've considered**
We have used the guidance in #2742 to effectively overwrite the PDB.  

As a package publisher, and reading through the concerns in 2742, we completely understand the reasoning behind including the PDB.  (Honestly feels like a miss with tooling in that there should be a method of packaging that can (easily) optionally exclude PDB's.)  Our customers are highly sensitive to package size - we don't currently bundle the model with the package, so the package is logically just code and relatively small.  

@scheyal @taicchoumsft

**Comment by snnn** [comment]
Change has been merged. The issue will be fixed in onnxruntime 1.9 release.
