### ISSUE TITLE
pypi releases for python 3.9

### ISSUE THREAD

**Issue by Borda** [microsoft/onnxruntime#6125]
Hello,
 a few months ago python 3.9 was officially released, last week even PyTorch started supporting with lots version 1.7.1.
On PyPI with the last version is 3.88 the latest - https://pypi.org/project/onnxruntime/#files
An alternative would be releasing also source package so it can be built on the user side...

Related to #5961 and #5697
It seems to be even supported #5874

**Comment by snnn** [comment]
https://test.pypi.org/project/ort-nightly/#files

**Comment by snnn** [comment]
Willl be in the next release.

**Comment by Borda** [comment]
> https://test.pypi.org/project/ort-nightly/#files

that is nice but is not very simple to put a switch to dependency like use `onnxruntime` it does not exit and also from a testing PyPI...

**Comment by snnn** [comment]
Sorry, I'm afraid there isn't an eaiser way.

**Comment by Borda** [comment]
@snnn any update here, any ETA on next release?
I was checking the [milestones](https://github.com/microsoft/onnxruntime/milestones) and there is no even 1.6

**Comment by snnn** [comment]
The next release will be in late Feb. or early March.

**Comment by Borda** [comment]
that is quite late, so is there a guide on how can we build it from the source?

**Comment by snnn** [comment]
See: https://github.com/microsoft/onnxruntime/blob/master/BUILD.md

Invoke build.sh or build.py with "--build_wheel"

**Comment by stonebig** [comment]
Is there still hope for end-february/early  March Python-3.9 wheels ?

**Comment by snnn** [comment]
Yes. It is in progress. It will be released soon.

**Comment by Borda** [comment]
@snnn any ETA? days or weeks... 🐰

**Comment by snnn** [comment]
A few days. We are doing the final validation.

**Comment by faxu** [comment]
It's released now.
