### ISSUE TITLE
Unable to get the output results for Sequence of Map in C++ api

### ISSUE THREAD

**Issue by dhirajnitk** [microsoft/onnxruntime#6127]
**Describe the bug**
Used sklearn-onnx to convert pickle models to .onnx. The python onnxrun is working.
But I am trying to emulate same behavior with c++. 
I used Mnist as code reference but my output tensor is Sequence of Map<Int64,Tensor(Float)>.
```
 std::vector<int64_t>keys{0,0};
 std::vector<float> values{0.0f,0.0f};
 std::vector<int64_t> dims{2};
 auto allocator_info = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeDefault);
 Ort::Value keys_tensor = Ort::Value::CreateTensor(allocator_info, keys.data(), keys.size()* sizeof(int64_t), dims.data(), dims.size()
    ,ONNX_TENSOR_ELEMENT_DATA_TYPE_INT64);
Ort::Value values_tensor = Ort::Value::CreateTensor(allocator_info, values.data(), values.size()* sizeof(float), dims.data(), dims.size(),ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT);
 std::vector<Ort::Value> in;
 in.emplace_back(Ort::Value::CreateMap(keys_tensor, values_tensor));
output_tensor_= Ort::Value::CreateSequence(in);
size_t num_values = output_tensor_.GetCount(); // prints 1
session_.Run(Ort::RunOptions{nullptr}, input_names, &input_tensor_, 1, output_names, &output_tensor_, 1);
```

The names of nodes are rightly pointed to correct c str(I tried changing them to another output node then It threw "Trying to get a Tensor, but got: seq(map(int64,tensor(float))) ). 
The run times throws no errors but the keys & values vectors are not  getting updated by run time. The values should be probability score but I see only 0.0f & 0.0f

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10. 
- ONNX Runtime installed from (source or binary): MS Build from source yesterday.
- ONNX Runtime version: MS Build from source yesterday.
- Python version:
- Visual Studio version (if applicable): 19.0
- GCC/Compiler version (if compiling from source): VS 19.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Expected behavior**
The run times throws no errors but the keys & values vectors are not  getting updated by run time. 
In python, this is how I receive the `output_probability [[{0: 0.39406856894493103, 1: 0.6059314608573914}]]`
The type also shows seq(map(int64,tensor(float))).  I expected keys vector to store{0,1} & values vector to store`{ 0.39406856894493103, 0.6059314608573914}.` The values should be probability score but I see only 0.0f & 0.0f for values and 0,0 for keys.

@pranav-prakash @pranavsharma

**Comment by pranav-prakash** [comment]
Not sure why I'm tagged as I'm not a member of the team. But I think your usage of the api isn't right. Per https://github.com/pranav-prakash/onnxruntime-riscv/blob/49110e5381df2139e40cdecd3978de2445c6568d/include/onnxruntime/core/session/onnxruntime_cxx_inline.h#L515 
the `Run()` the second-to-last arg passed in should be a pointer to an array of `Value`. It's easier if you use the version with signature `inline std::vector<Value> Session::Run` which automatically allocates the proper array for you:

```
 std::vector<Ort::Value> output_values;
  for (size_t i = 0; i < output_names_count; i++)
    output_values.emplace_back(nullptr);
```

See the example in https://github.com/microsoft/onnxruntime/blob/d8f3e46d458397b3fb335477d3efc91e22e160d8/onnxruntime/test/shared_lib/test_nontensor_types.cc#L67-L86 of how to access the elements of the map from there.
