### ISSUE TITLE
NCHWc optimization requirements

### ISSUE THREAD

**Issue by radikalliberal** [microsoft/onnxruntime#6148]
Hello,
I'm currently working on a model (MobileNetv2) under Pytorch. The previous model was trained under Tensorflow and runs fast on CPU because it uses the NCHWc Conv contrib operation. The new model has almost the same architecture but on the highest Optimization level I only get _FusedConv_ operations. Shouldn't these also be possible to be converted to NCHWc Conv?

I looked into onnxruntime/core/optimizer/nchwc_transformer.cc
and saw these requirements:

Convolutions (or FusedConv) must have:
- constant weights
- constant bias
- be float
- has 4 dimensions
- (output_channels % nchwc_block_size) != 0    (I'm not sure whats the blocksize though, is it 8?)

Can you tell me which requirements I'm missing which must be met to make use of NCHWc?
[here](https://drive.google.com/file/d/1avgUbx7rQ4p0_fubOviGZfu7qcBFySkn/view?usp=sharing) is a link to the model after full graph optimization

**Comment by tracysh** [comment]
Hi, I checked the model: the weights and bias tensors are labeled inputs and initializers, so they aren't constant. What parameters were used when converting to an ONNX model? torch.onnx.export should be called with keep_initializers_as_inputs=False.

**Comment by radikalliberal** [comment]
thanks, @tracysh this fixed my issue.
yes, keep_initializers_as_inputs was set on True.

Can you tell me what blocksize AVX512 has, or which multiples I need to take for conv filters?

**Comment by tracysh** [comment]
AVX512 uses a multiple of 16 and AVX2/earlier uses a multiple of 8.

**Comment by radikalliberal** [comment]
Great thanks!
