### ISSUE TITLE
ORT computes min/max incorrectly for negative fp16 values in opsets 12 and 13

### ISSUE THREAD

**Issue by TomWildenhain-Microsoft** [microsoft/onnxruntime#6153]
**Describe the bug**
ORT computes min incorrectly for negative fp16 values in opsets 12 and 13.  It says the min of 2 and -5 is 2.

**Urgency**
Bug is present in production version of ORT.  May cause existing models to fail.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Windows 10**
- ONNX Runtime installed from (source or binary): PyPI
- ONNX Runtime version: **1.6.0**
- Python version: 3.8

**To Reproduce**
```
from onnx import helper
from onnx.onnx_pb import TensorProto
import onnxruntime as ort
import numpy as np

node1 = helper.make_node("Min", ["X", "Y"], ["Z"], name="trans")

graph = helper.make_graph(
    [node1],
    "min_graph",
    [
        helper.make_tensor_value_info("X", TensorProto.FLOAT16, [3]), 
        helper.make_tensor_value_info("Y", TensorProto.FLOAT16, [3])
    ],
    [helper.make_tensor_value_info("Z", TensorProto.FLOAT16, [3])],
)

model_proto = helper.make_model(graph)

sess = ort.InferenceSession(model_proto.SerializeToString())
x_val = [1, 2, -3]
y_val = [4, -5, -6]
res = sess.run(["Z"], {"X": np.array(x_val, dtype=np.float16), "Y": np.array(y_val, dtype=np.float16)})
print(res[0])
# Should be [1, -5, -6] but is [1, 2, -3]
```

**Comment by hariharans29** [comment]
Thanks. It looks like the CPU kernels don't handle the type properly.  Probably not affecting too many prod models though because people requiring float16 for their models usually use the CUDA/ other GPU backends. Worth fixing this though for correctness' sake.
