### ISSUE TITLE
Onnx run time shared library size on linux is 500 mb. 

### ISSUE THREAD

**Issue by dhirajnitk** [microsoft/onnxruntime#6160]
**Describe the bug**

I built the onnx run time on WSL1.0 Ubuntu 20.04 and  memory size for libonnxruntime.so.1.6.0 is  500 mb.

The relwithdebInfo size  for onnxruntime.dll on windows is 6.7 mb in size. Is there something wrong with my build process?
If the size on linux is such humongous, Does onnx support any options to  reduce the shared library size?

**Comment by pranavsharma** [comment]
I downloaded the latest linux binary from the release page (https://github.com/microsoft/onnxruntime/releases/download/v1.6.0/onnxruntime-linux-x64-1.6.0.tgz). The size is 13mb.
The linux binary is built with 'Release' config.

pranav@DESKTOP-EBUL787:/mnt/c/Users/prs/Downloads/onnxruntime-linux-x64-1.6.0/lib$ ls -lh
total 13M
lrwxrwxrwx 1 pranav pranav  23 Dec  9 17:16 libonnxruntime.so -> libonnxruntime.so.1.6.0
-rwxrwxrwx 1 pranav pranav 13M Dec  9 17:16 libonnxruntime.so.1.6.0

**Comment by dhirajnitk** [comment]
@pranavsharma
Sorry this is off topic but I am working on a library that uses onnx runtime(shared/dynamic).
Do we have any script to build emscripten for onnx runtime. I built onnx.js codebase from source. It created wasm/js files but I cant link them to c++ library as It would need onnxruntime.a.
`ci_build/build.py `has no options to build for emscripten.

**Comment by hariharans29** [comment]
Currently, build.py doesn’t support building onnxruntime for emscripten. Please try using this - https://emscripten.org/docs/compiling/Building-Projects.html.

**Comment by dhirajnitk** [comment]
@hariharans29 
Can you please help with the flags for emscripten . 
```
-Donnxruntime_USE_EIGEN_FOR_BLAS  -> ON(by default)
(Eigen has ported the blas fortran code in c ?)
-Donnxruntime_ARMNN_BN_USE_CPU -> ON(By default:batch normalization flag.)
(Is this by default on? probably for code to run on arm devices )
-Donnxruntime_USE_NCCL -> ON(by default: Nickel library for multi gpu). 
(This should be off ?)
```

**Comment by vasanthzoh** [comment]
Hi, @dhirajnitk, were you able to figure it out?

**Comment by dianyo** [comment]
Hi @vasanthzoh,  I've built successfully with emscripten using the instruction here https://onnxruntime.ai/docs/build/web.html#build-onnx-runtime-webassembly-artifacts

You can also find how to build a static library in the QA session

**Comment by frankstien10** [comment]
Hi guys, can we further decrease the size of onnxruntime.so , I am trying to build a SDK for android which uses  libonnxruntime.so ? my current size of the sdk ~40mb i want to downgrade it to ~5 mb
