### ISSUE TITLE
Cuda provider not showing up on Google Colab

### ISSUE THREAD

**Issue by vss96** [microsoft/onnxruntime#6183]
**Describe the bug**
I was trying to run an onnx model on Google collab to run predictions, but when I check the providers only ['CPUExecutionProvider'] is available.

**Urgency**
Have a deadline on this Wednesday

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.6.0
- Python version: 3.6.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory:  Tesla P100, 14 GB

**To Reproduce**
-  I had installed both onnxruntime and onnxruntime-gpu. When I tried creating a session with the model given below, CUDA provider is not being listed.
- Model file: https://github.com/onnx/models/blob/master/vision/classification/vgg/model/vgg16-7.onnx

<img width="690" alt="Screenshot 2020-12-21 at 1 51 24 PM" src="https://user-images.githubusercontent.com/10259922/102754876-a0aedd00-4393-11eb-8814-58999749d8bf.png">

**Comment by hariharans29** [comment]
Can you uninstall the cpu package and try importing again ? Then you should see the import failure because onnxruntime gpu needs CUDA 10.2 installed - https://github.com/microsoft/onnxruntime/issues/5341

**Comment by vss96** [comment]
@hariharans29  Yes, the import error happens when i uninstall the cpu package. I installed CUDA 11.2 (I'm assuming higher version works), but I'm still getting the same error. I added the new cuda library in LD library path.
`export LD_LIBRARY_PATH=/usr/local/cuda-11.2/lib64:$LD_LIBRARY_PATH`
`export PATH=/usr/local/cuda-11.2/bin:$PATH`
<img width="1064" alt="Screenshot 2020-12-21 at 3 53 47 PM" src="https://user-images.githubusercontent.com/10259922/102766818-b8db2800-43a4-11eb-9234-30c5f79387a8.png">

**Comment by hariharans29** [comment]
It needs CUDA 10.2 and CuDNN 8 installed.

Please search for the following line in README.md:

Default GPU (CUDA)

The default GPU build requires CUDA runtime libraries being installed on the system:
Version: CUDA 10.2 and cuDNN 8.0.3

**Comment by hariharans29** [comment]
Closing this for now

**Comment by Ki6an** [comment]
I was facing the same issue, 
if anyone has trouble getting `CPUExecutionProvider`  make sure the `onnxruntime-gpu ` version matches with CUDA and CUDNN version

```
# onnxruntime-gpu version==1.4.0  --> CUDA 10.1.243 and CUDNN 7.6.5.32
# onnxruntime-gpu version==1.5.* ~ 1.6.0 --> CUDA 10.2 and cuDNN 8.0
```
to check which version of Cuda and cudnn is installed follow [this ](https://gist.github.com/Jongbhin/ad9aac8369751dbd84ca6a266a507bc7) guide.
