### ISSUE TITLE
Docker (server) build fails to build libonnxruntime.so.1.2.0

### ISSUE THREAD

**Issue by rauar** [microsoft/onnxruntime#6185]
**Describe the bug**
Dockerfile.server uses Ubuntu 16.04 and triggers a build of the onnxruntime server using cmake. Afterwards one of the last Docker commands tries to copy libonnxruntime.so.1.2.0 and fails as it cannot find that file in inside the build container. It seems that the cmake command being used in the Dockerfile does not build the shared library. When replacing the cmake command by build.sh in the root directory of this repo the build finds the shared library.

**Urgency**
n/a

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Docker (using Ubuntu 16.04)
- ONNX Runtime installed from (source or binary): Dockerfile.server
- ONNX Runtime version: 1.2.0
- Python version: n/a
- Visual Studio version (if applicable):n/a
- GCC/Compiler version (if compiling from source):n/a
- CUDA/cuDNN version:n/a
- GPU model and memory:n/a

**To Reproduce**
Clone onnxruntime repo and start a Docker build using dockerfiles/Dockerfile.server

**Expected behavior**
Build should succeed.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by pranavsharma** [comment]
ORT server is deprecated and we don't support it any more.

**Comment by rauar** [comment]
Just for clarification: are you referring to just Dockerfile.server or is ONNX Runtime server (documented here: https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Server_Usage.md) which seems to be in beta status phased out already ? If yes what is the approach then to serve a model for prediction requests (similar to Tensorflow Serving) ? If it's deprecated it might make sense to clearly document people should not dive into ONNX Runtime server to avoid falling a wrong path.
