### ISSUE TITLE
why onnxruntime inference slow then pytorch model

### ISSUE THREAD

**Issue by DonggeunYu** [microsoft/onnxruntime#6192]
I conducted inference from RTX 5000 to detectron2 model.
pytorch was 1.8~2.0x faster than ONNX.

Below is the result of inference of the ONNX model several times.
For each inference, there is a section where the GPU is not used 3 times.
It seems to be a bottleneck.

Also, I don't know why there are more than 100 python threads.

I want to reduce the ONNX inference time.

![슬라이드1](https://user-images.githubusercontent.com/17740653/102845174-4c1d6780-4450-11eb-8192-0d2acf336ab2.jpeg)

**Comment by Byte247** [comment]
Hi, i know its an old topic but did you find a solution for this? I converted a default detectron2 faster rcnn model to ONNX but while the inference in detectron2 seems fast, its incredibly slow in ONNX:
"time detectron2: 0.0796702549996553
time onnx: 2.84882526399997
