### ISSUE TITLE
Converting Tensorflow model to onnx and running using onnx runtime give totally wrong result comare to orignal model 

### ISSUE THREAD

**Issue by RD191295** [microsoft/onnxruntime#6195]
**Describe the bug**
I convert tensorflow model to onxx using tf2onnx .but after converting model it giving wrong prediction . i used ssd mobile net model. it's custom train model and while testing it giving wrong output everytime. 

**Urgency**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Tested on windows 10 and Ubantu 
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version:1.6.0
- Python version: 3.7
- Visual Studio version (if applicable): no
- GCC/Compiler version (if compiling from source): no
- CUDA/cuDNN version: 
- GPU model and memory: Nvidia Jetson board

**To Reproduce**
- while transfering custom train ssd mobile net model to onnx it give such error. I tried with ssd resnet-50 also
- Please check model at this location : https://drive.google.com/drive/folders/13sc6FAF941KTKHT5A__YgBB6ZDEex0he?usp=sharing.

**Expected behavior**
Giving wrong result on test image . every time it give number of detection same as 100 on any image

**Comment by RD191295** [comment]
Any Update regarding this.. I am waiting for answer. Please help me to solve this issue.

**Comment by hariharans29** [comment]
1) Have you tried using CPU and CUDA EPs ? Do both give the same results ? If both give the same results (and they are incorrect when compared with tf), then most likely the issue is either tf to onnx conversion or pre-processing.

2) Check the pre-processing being applied before feeding the input. The pre-processing needs to be exactly what was applied to the input images while training the model. Please ensure that you are able to verify this with high confidence.

**Comment by RD191295** [comment]
1. I try tensorflow1 model and it giving same output in both the case. but if i use tensorflow2 model it doesn't give same output. I check with per-trained model as well as custom model.
2. I test code on NVIDIA GPU as well as normal CPU both as same issue on TensorFlow 2 model. tensorflow1 model giving same output in both case with onnx as well as TensorFlow.
3. I didn't use any per-processing in both case so that i can compare.

**Comment by RD191295** [comment]
I found solution for this issue so i close this issue now.. Thank you for your best support!!
