### ISSUE TITLE
ValueError: ['OpenVINOExecutionProvider'] does not contain a subset of available providers ['CPUExecutionProvider']

### ISSUE THREAD

**Issue by vgoklani** [microsoft/onnxruntime#6214]
"ValueError: ['OpenVINOExecutionProvider'] does not contain a subset of available providers ['CPUExecutionProvider']"

I am trying to use OpenVINOExecutionProvider in-place of CPUExecutionProvider:

	def create_model_for_provider(model_path: str, provider: str) -> InferenceSession: 
	    assert provider in get_all_providers(), f"provider {provider} not found, {get_all_providers()}"

	    sess_options = SessionOptions()
	    sess_options.graph_optimization_level = GraphOptimizationLevel.ORT_ENABLE_ALL
	    sess_options.intra_op_num_threads = 1
	    
	    session = InferenceSession(model_path, sess_options, providers=[provider])
	    session = InferenceSession(model_path, sess_options)
	    session.set_providers(['OpenVINOExecutionProvider'], [{'device_type' : 'CPU_FP32'}])
	    session.disable_fallback()
	    return session

cpu_model = create_model_for_provider(model_path="model.onnx", provider="OpenVINOExecutionProvider")

The model is a vanilla Roberta-type model from Huggingface, and this example works correctly using the CPUExecutionProvider. 

onnxruntime.__version__ == 1.6.0 

and is installed via pip

Note that OpenVINOExecutionProvider is listed in the list of providers:

['TensorrtExecutionProvider',
 'CUDAExecutionProvider',
 'MIGraphXExecutionProvider',
 'ROCMExecutionProvider',
 'OpenVINOExecutionProvider',
 'DnnlExecutionProvider',
 'NupharExecutionProvider',
 'VitisAIExecutionProvider',
 'NnapiExecutionProvider',
 'ArmNNExecutionProvider',
 'ACLExecutionProvider',
 'DmlExecutionProvider',
 'CPUExecutionProvider']

Not sure how to proceed, thanks!

**Comment by wschin** [comment]
I am not an expert of execution provider. My first naive thought is that the package being used wasn't built with OpenVINO.

**Comment by vgoklani** [comment]
Hey @wschin thanks for the response. I see 'OpenVINOExecutionProvider' in the list of providers, does that imply that it's already installed?

**Comment by MaajidKhan** [comment]
Hi @vgoklani . As  OpenVINOExecutionProvider is shown in the list of providers, you can make use of this.
I hope, you would have already followed the steps for using OpenVINO Execution Provider and have initialized OpenVINO.
https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/OpenVINO-ExecutionProvider.md

**Build steps:**
https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#openvino

**Make sure to Initialize the OpenVINO environment by running the setupvars script as shown below:**
**For Linux run:**
source <openvino_install_directory>/bin/setupvars.sh


Looking at the snippet of code, you posted, the issue looks like you haven't imported onnxruntime.
It should be:
sess_options = onnxruntime.SessionOptions()
sess_options.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_ENABLE_ALL
sess = onnxruntime.InferenceSession(model_path, sess_options, providers=['OpenVINOExecutionProvider'])

Attaching a working python script for your reference as well in .txt format ( **OpenVINO_EP.txt** )
[OpenVINO_EP.txt](https://github.com/microsoft/onnxruntime/files/5746318/OpenVINO_EP.txt)

**Comment by jywu-msft** [comment]
> Hey @wschin thanks for the response. I see 'OpenVINOExecutionProvider' in the list of providers, does that imply that it's already installed?

there are 2 api's get_all_providers() and get_available_providers()
which one are you referring to?
get_all_providers() will list all the possible providers that OnnxRuntime can support 
but get_available_providers() lists the providers that the package you are using was built with.

**Comment by vgoklani** [comment]
thanks @jywu-msft

**Comment by user-ZJ** [comment]
@vgoklani  I meet the same problem,I want to know your solution. Can you share it?

**Comment by jywu-msft** [comment]
> @vgoklani I meet the same problem,I want to know your solution. Can you share it?

you can download python whl with openvino enabled from https://github.com/intel/onnxruntime/releases/tag/v3.1
