### ISSUE TITLE
how to use cuda_mem_limit

### ISSUE THREAD

**Issue by GumpCode** [microsoft/onnxruntime#6215]
**Describe the bug**
hi, I want to limit cuda memory, so I set the inferencession as 
```
self.bert = onnxruntime.InferenceSession(self.model_path)
self.bert.set_providers(["CUDAExecutionProvider"], [{"device_id": 0, "cuda_mem_limit": 1024*1024*1024}])
```
it seems not work, memory will growing up utill out of memory.
And I continue to set 1 for 'cuda_mem_limit‘, I think it will rise error, but model run seccessfully.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- ONNX Runtime installed from (source or binary): pypi
- ONNX Runtime version: 1.5.1
- Python version: 3.8
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cuda 10.2  cudnn 8
- GPU model and memory: 1080ti

**Comment by faxu** [comment]
Please reference updated documentation
