### ISSUE TITLE
[Performance] Any bench marking data or scripts available for ONNXRuntime ?

### ISSUE THREAD

**Issue by srkreddy1238** [Microsoft/onnxruntime#622]

**Comment by faxu** [comment]
This can be used for testing perf of ONNXRuntime: https://github.com/Microsoft/onnxruntime/tree/master/onnxruntime/test/perftest 

We are also participating in the MLPerf effort.

**Comment by faxu** [comment]
@srkreddy1238 Does this address your question? If so, please close the issue. If not, let us know how we can further help. Thanks! :)

**Comment by srkreddy1238** [comment]
@faxu thanks for the info. but perftest need a bit of crafting required for the model and input too.

I used below sample code to keep it common across all my comparisons.

But I see ONNX GPU is quite expensive compared to others.

```
    onnx_file = "./onnx-models/" + name + ".onnx"
    if not os.path.exists(onnx_file):
        onnx_graph = tf2onnx.tfonnx.process_tf_graph(sess.graph, input_names=[input_node], output_names=[output_node])
        model_proto = onnx_graph.make_model("test")
        with open(onnx_file, "wb") as f:
            f.write(model_proto.SerializeToString())

    from onnx import load
    import onnxruntime.backend as backend
    model = load(onnx_file)
    sess = backend.prepare(model, 'GPU')

    X = input_data

    sess.run(X)
    sess.run(X)

    total = 0;
    for ii in range(600):
        start = time.time()
        sess.run(X)
        done = time.time()
        total += (done - start)
    avg =  round(total/600*1000, 4)
    results[name]['ONNX'] = avg

    print("ONNX Avg:", avg)
```

**Comment by snnn** [comment]
Hi @srkreddy1238 ,

Could you try this: https://github.com/mlperf/inference/tree/master/cloud/image_classification

**Comment by srkreddy1238** [comment]
Hi @snnn 
Sure, I will try this and let you know the results.

**Comment by snnn** [comment]
Hi @srkreddy1238 , is your problem solved?

**Comment by srkreddy1238** [comment]
@snnn thanks.
I was a bit occupied these days. I will try it this week some time.
I am closing this case for now.
