### ISSUE TITLE
cannot open file 'onnxruntime.lib'

### ISSUE THREAD

**Issue by freedom9393** [microsoft/onnxruntime#6226]
I'm running the following command:

`cmake .. -A x64 -T host=x64 -DLIBPNG_ROOTDIR=D:\Projects\onnxruntime\libpng -DONNXRUNTIME_ROOTDIR=D:\Projects\onnxruntime -Donnxruntime_USE_DML=ON`
And running onnxruntime_samples.sln file via visual studio. But, I'm getting this error:
`cannot open file 'onnxruntime.lib'`
Why is this happening?

**Comment by snnn** [comment]
Did you install onnxruntime first?

 https://github.com/microsoft/onnxruntime/tree/master/samples/c_cxx#install-onnx-runtime 

ONNXRUNTIME_ROOTDIR should be where it was installed, not the source.

**Comment by freedom9393** [comment]
@snnn, yes I instelled onnxruntime. I solved that problem by including onnxruntime.lib folder on my visual studio. Now it's working :)
