### ISSUE TITLE
build.py ImportError: wrong 'util' imported

### ISSUE THREAD

**Issue by mgoin** [microsoft/onnxruntime#6230]
```
 Traceback (most recent call last):
  File "./tools/ci_build/build.py", line 24, in <module>
    from util import run  # noqa: E402
ImportError: cannot import name 'run' from 'util' (/usr/local/lib/python3.7/site-packages/util.py)
```

**Describe the bug**
The `tools/ci_build/build.py` script can import the wrong `util` library because `sys.path.**append**` can put the util library path after python site-packages path.

On my system, I already have python's site-packages on my path, so after 
`sys.path.append(os.path.join(REPO_DIR, "tools", "python"))`
my `sys.path` is  
`'[/usr/local/lib/python3.7/site-packages', '/home/mgoin/code/onnx-runtime/tools/python']`

**Urgency**
Bug is present in production version of ORT. May cause build and testing environments to fail depending on `sys.path` setup.

**System information**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux 4.19.88-1-MANJARO
ONNX Runtime installed from (source or binary): source
ONNX Runtime version: rel-1.6.0
Python version: 3.7

**Temporary Fix**
You can get past this issue by replacing 
`sys.path.append(os.path.join(REPO_DIR, "tools", "python"))` 
with 
`sys.path.insert(0, os.path.join(REPO_DIR, "tools", "python"))` 

This ensures that onnxruntime's util library will always be first in `sys.path`

https://github.com/microsoft/onnxruntime/blob/111ac299cc26d0b7dfca68e500855e927653c157/tools/ci_build/build.py#L18-L24

**Comment by jywu-msft** [comment]
thanks for reporting this and contributing a fix!
