### ISSUE TITLE
Segmentfault caused by MlasGemmFloatKernel both on Avx512F and Fma3

### ISSUE THREAD

**Issue by dawnranger** [microsoft/onnxruntime#6232]
**Describe the bug**
Onnxruntime service occasionally coredump because of MlasGemmFloatKernel

**Urgency**
None

**System information**
- CentOS 7
- ONNX Runtime installed from source
- ONNX Runtime version: 1.4.0
- GCC/Compiler version : gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
build command:
```
python3 $DIR/tools/ci_build/build.py --build_dir $DIR/build/Linux --config Release --x86 --build_shared_lib --use_openmp --use_dnnl --use_full_protobuf --skip_tests --skip_submodule_sync     --parallel
```
- CUDA/cuDNN version: no cuda, CPU Accelerators with Intel-DNNL support.
AMD CPU
![image](https://user-images.githubusercontent.com/10653991/103342977-d9526300-4ac5-11eb-8cd4-0746efe1268c.png)

**To Reproduce**
occasionally occurs in online inference service

**Screenshots**
AMD CPU debug info:
![image](https://user-images.githubusercontent.com/10653991/103328976-ca53bc80-4a95-11eb-85c4-8598395bbcba.png)

**Additional context**
LSTM-CRF model
- model file: [LSTM-CRF.zip](https://github.com/microsoft/onnxruntime/files/5753017/LSTM-NER.zip)
- model architecture: 
![image](https://user-images.githubusercontent.com/10653991/103329564-1a338300-4a98-11eb-88ff-0d1c765f7aa8.png)

**Comment by dawnranger** [comment]
# @pranavsharma @tracysh

**Comment by dawnranger** [comment]
seems to only occur on AMD CPU

**Comment by dawnranger** [comment]
gdb debug of coredump files on Intel CPU report this:
![image](https://user-images.githubusercontent.com/10653991/103348400-db6fee00-4ad4-11eb-877b-99ce6dd6ca93.png)

CPU info:
![image](https://user-images.githubusercontent.com/10653991/103348426-eaef3700-4ad4-11eb-88c6-169f43b696e3.png)

**Comment by snnn** [comment]
Your system is 32 bits?

**Comment by tracysh** [comment]
@dawnranger: I can reproduce the crash if the model is given an input of [batch_size][seq_length=0]. Is that possible in your case? I'll fix MlasGemm to bail out early if M/N/K is zero. 

After running with that fix though, I hit a problem in the Reshape kernel where it fails to compute that the -1 dimension can be 256 because the shape size is zero. That would be a different problem to resolve. The ONNX shape inferencing code might have better logic to compute the unknown dimension.

While these issues are being worked out, can you avoid calling into the runtime when seq_length=0?

`2020-12-30 13:26:11.2535155 [E:onnxruntime:, sequential_executor.cc:334 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Reshape node. Name:'Reshape_11' Status Message: F:\onnxrt2\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:38 onnxruntime::ReshapeHelper::ReshapeHelper size != 0 && (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{0,1,2,128}, requested shape:{0,1,-1}`

**Comment by dawnranger** [comment]
> Your system is 32 bits?

My System is CentOS x86_64

**Comment by dawnranger** [comment]
> @dawnranger: I can reproduce the crash if the model is given an input of [batch_size][seq_length=0]. Is that possible in your case? I'll fix MlasGemm to bail out early if M/N/K is zero.
> 
> After running with that fix though, I hit a problem in the Reshape kernel where it fails to compute that the -1 dimension can be 256 because the shape size is zero. That would be a different problem to resolve. The ONNX shape inferencing code might have better logic to compute the unknown dimension.
> 
> While these issues are being worked out, can you avoid calling into the runtime when seq_length=0?
> 
> `2020-12-30 13:26:11.2535155 [E:onnxruntime:, sequential_executor.cc:334 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Reshape node. Name:'Reshape_11' Status Message: F:\onnxrt2\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:38 onnxruntime::ReshapeHelper::ReshapeHelper size != 0 && (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{0,1,2,128}, requested shape:{0,1,-1}`

Thanks for you reply, I will try to avoid calling when seq_length=0.

**Comment by snnn** [comment]
> > Your system is 32 bits?
> 
> My System is CentOS x86_64

You should remove the " --x86 " build flag, it is only for x86_32.

**Comment by dawnranger** [comment]
> > > Your system is 32 bits?
> > 
> > 
> > My System is CentOS x86_64
> 
> You should remove the " --x86 " build flag, it is only for x86_32.

Since I have a x86 OS, and the *Architectures* section of the build guide suggest to add `-x86` option:
https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#linux-11
![image](https://user-images.githubusercontent.com/10653991/103399298-60adde00-4b7b-11eb-9ee0-9f92c6c0aeee.png)

I'am a little confused about 
> it is only for x86_32

Did you mean onnxruntime only suport 32 bits?

**Comment by dawnranger** [comment]
> @dawnranger: I can reproduce the crash if the model is given an input of [batch_size][seq_length=0]. Is that possible in your case? I'll fix MlasGemm to bail out early if M/N/K is zero.
> 
> After running with that fix though, I hit a problem in the Reshape kernel where it fails to compute that the -1 dimension can be 256 because the shape size is zero. That would be a different problem to resolve. The ONNX shape inferencing code might have better logic to compute the unknown dimension.
> 
> While these issues are being worked out, can you avoid calling into the runtime when seq_length=0?
> 
> `2020-12-30 13:26:11.2535155 [E:onnxruntime:, sequential_executor.cc:334 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Reshape node. Name:'Reshape_11' Status Message: F:\onnxrt2\onnxruntime\core\providers\cpu\tensor\reshape_helper.h:38 onnxruntime::ReshapeHelper::ReshapeHelper size != 0 && (input_shape.Size() % size) == 0 was false. The input tensor cannot be reshaped to the requested shape. Input shape:{0,1,2,128}, requested shape:{0,1,-1}`

You are totally my world saver. After doing what you suggested, all coredumps are gone! Thanks again!

**Comment by snnn** [comment]
Hi @dawnranger, 

The document means: if your system is 32bits x86, then you should add the "--x86" flag. Otherwise, you don't. By default it is x86_64.

**Comment by dawnranger** [comment]
> Hi @dawnranger,
> 
> The document means: if your system is 32bits x86, then you should add the "--x86" flag. Otherwise, you don't. By default it is x86_64.

Got It, thanks. Since my problem is solved, I'll close this issue.
