### ISSUE TITLE
unit test test_slice_default_axes_cpu from onnx is failing for the python bindings

### ISSUE THREAD

**Issue by xadupre** [Microsoft/onnxruntime#624]
**Describe the bug**

Error is:
RuntimeError: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Node: Node () has input size 3 not in range [min=1, max=1].

unit test to run: onnx_backend_test_series.py

It was passing before.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows and Debian
- ONNX Runtime installed from (source or binary): master branch 03/14
- ONNX Runtime version: master branch 03/14
- Python version: 3.7.2
- CPU

**To Reproduce**
Build the python python and run onnx_backend_test_series.py.

**Expected behavior**
No error.

**Comment by snnn** [comment]
What is your ONNX version?

**Comment by xadupre** [comment]
ONNX from master branch cloned today, this is how I build onnxruntime. The behaviour seems different based on the setting used to compile.

python3.7 ./onnxruntime/tools/ci_build/build.py --build_dir ./onnxruntime/build/linux --config Release --build_wheel --use_mkldnn --use_openmp --use_llvm --numpy_version= --skip-keras-test

**Comment by snnn** [comment]
That's the problem. You must use the same one in onnxruntime's submodule.

**Comment by snnn** [comment]
Hi @xadupre

Please reinstall your onnx python package and let me know if the error is gone.

**Comment by xadupre** [comment]
I did not see any improvment and two others tests were failing:     '^test_averagepool_2d_ceil_cpu.*',
    '^test_maxpool_2d_ceil_cpu.*',. Maybe that's some tests which were renamed. I pull onnx and onnxruntime fomr github this morning.

**Comment by snnn** [comment]
Hi @xadupre , you can't install onnx from your onnx repo, you should install it from onnxruntime's sub folder, so that we can ensure it's the same version used by onnxruntime.

**Comment by xadupre** [comment]
That's not a common scenario, what if onnxruntime requires a specific runtime and torch another one. What's the difference between onnx from onnxruntime and official onnx?

**Comment by snnn** [comment]
@xadupre 

I'm sorry, I have to say. it's not supported.  It won't be supported unless onnxruntime only picks released onnx versions(not a random git commit).

> What's the difference between onnx from onnxruntime and official onnx
We extended the protobuf definition.(aka, model format) . see: https://github.com/Microsoft/onnxruntime/blob/master/onnxruntime/core/protobuf/onnx.in.proto

**Comment by xadupre** [comment]
Ok let's close the issue then. The failure is not tested and out of scope.
