### ISSUE TITLE
Import Issue -  Cannot import 'quantize_dynamic'

### ISSUE THREAD

**Issue by jay-karan** [microsoft/onnxruntime#6277]
Hi,

Platform: Google Colab
ORT Installed through PIP: pip install onnxruntime==1.4.0
Issue: Could not import 'quantize_dynamic'.
Aim: Looking to Quantize an ONNX Model.

Please find the snippet attached along with the error. I was wondering if I need to install ORT from source and then try. 
Please help in finding out the reason and suggest a solution. Thank you.

![image](https://user-images.githubusercontent.com/65300616/103901673-75f8ae80-511f-11eb-8c10-1ff7e74f80fa.png)

**Comment by yufenglee** [comment]
@jay-karan, the quantize_dynamic was added from 1.5. Please upgrade your version to 1.5 or use the old quantize API.

**Comment by jay-karan** [comment]
Thank you @yufenglee, it worked.

I have realized that the quantized are taking more longer inference times than the non-quantized models. May I know possible reasons?

**Comment by jay-karan** [comment]
@yufenglee, I am writing this comment as the follow-up for the previous one.

**Comment by mayank-nference** [comment]
@yufenglee, I am using onnxruntime version 1.7.0, still I am getting this error, 

ImportError: cannot import name 'quantize_dynamic' from 'onnxruntime.quantization' (/onnx_env/lib/python3.7/site-packages/onnxruntime/quantization/__init__.py)

**Comment by yufenglee** [comment]
Could you please check if you have multiple versions of onnxruntime installed and you accidentally used the olde version?
