### ISSUE TITLE
Model-parallel inference with ONNX Runtime + HF transformers

### ISSUE THREAD

**Issue by g-karthik** [microsoft/onnxruntime#6318]
https://github.com/microsoft/onnxruntime/blob/ac5b5e5d1e4f27cd7fa541cc1ca6d16e36db4949/onnxruntime/python/tools/transformers/gpt2_helper.py#L50

The public `GPT2LMHeadModel` class by Hugging Face now allows for basic model-parallelism via spreading of layers across GPUs through a device map, see the `parallelize()` method [here](https://github.com/huggingface/transformers/blob/1bdf42409c452a767ac8e2119bceb8f5c704c8f1/src/transformers/models/gpt2/modeling_gpt2.py#L803).

I want to use ONNX Runtime in **conjunction** with the above `parallelize()` during inference, so as to benefit from both and reduce latency of sequence generation. Does ONNX Runtime allow for spreading layers across GPUs during inference? Are there any special steps to be taken to make this happen?

**Comment by pranavsharma** [comment]
Not yet. We're working on it. Stay tuned!

**Comment by g-karthik** [comment]
@pranavsharma Cool, is there an ETA?

**Comment by pranavsharma** [comment]
No ETA yet. Will keep you posted.

**Comment by ydzhang12345** [comment]
+1, also interested in this feature.

**Comment by switiz** [comment]
+1 also interested in this feature

**Comment by hannan72** [comment]
Hi all,
Hope to reach good achievements. I'm also interested in this feature. Is there any update?
