### ISSUE TITLE
Difference between onnxruntime with TensorRT provider vs TensorRT standalone

### ISSUE THREAD

**Issue by cyrusbehr** [microsoft/onnxruntime#6361]
As the title suggests, what is the difference between running inference using onnxruntime using the [TensorRT provider](https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/TensorRT-ExecutionProvider.md) and simply using the [TensorRT](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html) library on it's own? 

Are there any big differences in performance? Why use one over the other?

**Comment by jywu-msft** [comment]
The primary reason is that standalone TensorRT does not support all ONNX operators/types/spec etc. 
so OnnxRuntime can partition the graph to assign appropriate subgraphs to TensorRT EP or CUDA EP or CPU EP

**Comment by cyrusbehr** [comment]
Ok that makes sense, thank you for clarifying.
