### ISSUE TITLE
Error BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B) 

### ISSUE THREAD

**Issue by mbs220** [microsoft/onnxruntime#6367]
hello everybody
i made a LOBE model as onnx. then i used the sample code in the [main page](https://github.com/lobe/lobe.NET#use-the-model-in-your-own-net-application)
but it shows me an error on runtime:

System.**TypeInitializationException**
HResult=0x80131534
Message=The type initializer for 'Microsoft.ML.OnnxRuntime.**NativeMethods**' threw an exception.
Source=Microsoft.ML.OnnxRuntime
StackTrace:
at Microsoft.ML.OnnxRuntime.SessionOptions..ctor() in C:\a\3\s\csharp\src\Microsoft.ML.OnnxRuntime\SessionOptions.cs:line 50
at lobe.OnnxImageClassifier.InitialiseFromSignature(Signature signature, String modelFileName)
at lobe.ImageClassifier.CreateFromSignature(Signature signature, String modelFileName, String engineType)
at lobe.ImageClassifier.CreateFromSignatureFile(FileInfo signatureFile, String modelFileName, String format)
at AIWebApp.ML.LobeOfficeAppDetection.Main(String signatureFilePath, String imageToClassify) in G:***\LobeDetection.cs:line 26 at *.Tests.MyTests.Test1() in G:*\MyTests.cs:line 21

Inner Exception 1:
BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

i think this is where the exception thrown:
[https://github.com/microsoft/onnxruntime/blob/eab164e1a5cd7760ee653ffe455e7a10cded7cb2/csharp/src/Microsoft.ML.OnnxRuntime/InferenceSession.cs#L693](https://github.com/microsoft/onnxruntime/blob/eab164e1a5cd7760ee653ffe455e7a10cded7cb2/csharp/src/Microsoft.ML.OnnxRuntime/InferenceSession.cs#L693
)
Could you please help me to solve the problem ?

- Windows 7 64Bit
- VS 2017 (15.9.18) Framework 4.7.1

+ [this is my expectation in result](https://elbruno.com/2020/10/29/ai-lobe-exporting-to-onnx-and-running-in-c-csharp-lobe_ai/)

thanks in advanced
regards
mohammad

**Comment by tianleiwu** [comment]
See https://github.com/microsoft/onnxruntime/issues/5532 for installing dependent DLLs.

For example, try install latest VC 2019 Runtime from [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads). If you uses GPU, you will need install CUDA 10.2 and cuDNN 8.0 for onnxruntime 1.5.* or 1.6.*

**Comment by mbs220** [comment]
hi @tianleiwu , i will check it and will say the result
Thanks

**Comment by mbs220** [comment]
hi @tianleiwu again, i did 2 tasks:
1- I run the project in Windows 10 and VS 2019,  same error occurred.
2- I follow #5532 & installed the **x64: vc_redist.x64.exe** but same error again occurred

* i use CPU

and i have a question: 

cublas64_10.dll
cublasLt64_10.dll
cudart64_102.dll
cudnn64_8.dll
cufft64_10.dll
curand64_10.dll
msvcp140.dll
vcruntime140.dll
vcruntime140_1.dll

how can i download these DLL ? in #4009 mentioned that i need these DLL but from where ?

**Comment by snnn** [comment]
The following files are CUDA files. You should install cuda. You can get the installation files from Nvidia website.

1. cublas64_10.dll
2. cublasLt64_10.dll
3. cudart64_102.dll
4. cudnn64_8.dll
5. cufft64_10.dll
6. curand64_10.dll

And, the following 3 files are VC runtime files. After installing  vc_redist.x64.exe, you will have them.

1. msvcp140.dll
2. vcruntime140.dll
3. vcruntime140_1.dll

**Comment by mbs220** [comment]
thanks @snnn 
i thought if i use CPU it's not  necessary to install CUDA.

thanks all

i close this issue and will try this method and will open if needed.
