### ISSUE TITLE
Unable to find onnxruntime.dll via FFI(node js)

### ISSUE THREAD

**Issue by dhirajnitk** [microsoft/onnxruntime#6371]
I am using c++ library which consumes onnxruntime library. Then I used node ffi to call c functions.
I am unable to load the onnxruntime  dll with the error 
`Error: Dynamic Linking Error: Win32 error 193`
The ffi & js functions work for other runtime so  there is no problem of 32/64 bit compatability. The onnxruntime.dll also works fine with native c++ executable.

Is the runtime for nodejs different? Is there any specific portion of configuration needed for onnxruntime to run for node.

**Comment by fs-eire** [comment]
error 193 usually indicates 32/64 bit mismatch... but it looks that you have checked this already.

could you share me steps to reproduce this issue?

**Comment by dhirajnitk** [comment]
I left ffi so Run time is  not crashing with Node js add on but giving completely wrong results on "node-addon"

https://github.com/nodejs/node-addon-examples
