### ISSUE TITLE
Import issues with onnxruntime-gpu

### ISSUE THREAD

**Issue by jay-karan** [microsoft/onnxruntime#6379]
**Platform:** Colab Google
**CUDA:** 10.1
**ONNX Runtime Installation**: pip install onnxruntime-gpu==1.5.1

**_Error_**: **OSError: libcudnn.so.8: cannot open shared object file: No such file or directory** while importing.

**Alternative Try**: The same was tried on CUDA 10.2 as well. Issue persisted.

Please look at the snippet for more info.
![image](https://user-images.githubusercontent.com/65300616/105039268-5ac66100-5a86-11eb-849b-1c46d1fff40b.png)

**Furthermore,**
May I ask about the version requirements of CUDA and cudnn for 
- onnxruntime-gpu==1.4.0?
- onnxruntime-gpu==1.5.0?
- onnxruntime-gpu==1.6.0?

Thank you!

**Comment by tianleiwu** [comment]
1.4.0:  CUDA 10.1.243 and CUDNN 7.6.5.32
1.5.* ~ 1.6.0: CUDA 10.2 and cuDNN 8.0.

**Comment by jay-karan** [comment]
Having right CUDA and CUDNN versions along with path sets worked the trick for me.Thanks!
