### ISSUE TITLE
Memory Increase With Run

### ISSUE THREAD

**Issue by rubyfish** [microsoft/onnxruntime#6397]
Hi, I need to run session on multiple image, but when I call "m_Session->Run()", my memory increase continuously.

System information:
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.4.0
- Visual Studio version: vs2017
- Run on CPU

My code:

```
//
//Load Model
//
![memory](https://user-images.githubusercontent.com/34569240/105358534-42df1080-5c31-11eb-9a1b-3419ea0175fc.PNG)

for(...)
{
//
//read image to tensor...
//

// Create input tensor object from data values
Ort::Value InputTensor = Ort::Value::CreateTensor<uint8_t>(m_ortMemoryInfo, m_vecInputTensorValues.data(), m_sInputTensor * sizeof(uint8_t), m_vecInputNodeDims.data(), 4);
assert(InputTensor.IsTensor());

//Run Session
//memory increase here
std::vector<Ort::Value> m_vecOrtOutputTensor = m_Session->Run(Ort::RunOptions{ nullptr }, (const char* const*)m_vecInputNodeNames.data(), (const Ort::Value*)&InputTensor, m_vecInputNodeNames.size(), (const char* const*)m_vecOutputNodeNames.data(), m_vecOutputNodeNames.size());
assert(m_vecOrtOutputTensor.front().IsTensor());

//
//do something
//
}
```
I want to know how to free this memory correctly, thank you!

P.s. this is my memory screen shot after one image run session
![memory](https://user-images.githubusercontent.com/34569240/105358698-79b52680-5c31-11eb-86c5-4ccc382122c0.PNG)

**Comment by skottmckay** [comment]
How many times are you calling Run and how much does the memory usage increase each time?

Do the input sizes change on each call to Run or not?

In the '// do something' section are any of the OrtValue instances copied elsewhere that would keep them alive for longer?

**Comment by skottmckay** [comment]
Closing due to no response

**Comment by rubyfish** [comment]
Hi skottmckay,

I run this for loop for 1000 time, memory didn't increase each time.
Input sizes didn't change on each call run.
There are some OrtValue instances in //do something, but when I exit this function, the memory didn't release.

What is the right way to release Ort::Value?
