### ISSUE TITLE
Page for python API documentation is broken

### ISSUE THREAD

**Issue by HendrikBoehmer** [microsoft/onnxruntime#6398]
Hi, I wanted to try out model inference with onnxruntime in python, however the Website of the documentation seems broken and the link to that pages source is broken aswell.

Python API Page: https://www.onnxruntime.ai/python/index.html
Supposed location of that pages source: https://www.onnxruntime.ai/python/_sources/index.rst.txt

**Comment by faxu** [comment]
Fixed by https://github.com/microsoft/onnxruntime/pull/6575
