### ISSUE TITLE
C API doc (badly) needs updating

### ISSUE THREAD

**Issue by omatai** [microsoft/onnxruntime#6402]
**Is your feature request related to a problem? Please describe.**
The C API doc is outdated. In particular, the usage overview is inconsistent with working samples (MNIST) and there are several broken links

**System information**
- ONNX Runtime version (you are using): >= 1.6

**Describe the solution you'd like**
It might be best to start from scratch :-) If retaining the same format, perhaps the usage overview would cover the same steps, headlining the "typical" code/functions, but also sketching some common alternatives. Without knowing the alternatives, it's hard to progress beyond the samples. It would be REALLY helpful to specify what kinds of exceptions may be thrown - so far I cannot get past a certain exception that I have not been able to identify.

**Describe alternatives you've considered**
My only alternative is to give up :-(

**Additional context**

**Comment by faxu** [comment]
Thanks for the feedback. We are reworking improving this.

In the meantime, if you have any usage questions or issues, please feel free to post issues here.

**Comment by omatai** [comment]
Documentation on everything to do with neural nets is currently sparse for Windows. But actually, of all the options for implementing neural nets on Windows in C or C++, in my experience, Onnx runtime is the most workable - the examples are solid, easy to follow, and not hard to adapt, leading to my advice here: https://stackoverflow.com/a/66036896/1099237

**Comment by natke** [comment]
Closing after C/C++ API docs update and MNIST example build update
