### ISSUE TITLE
the problem of converting hrnet to onnx

### ISSUE THREAD

**Issue by eekarot** [microsoft/onnxruntime#6408]
I used pytorch to train the segmentation model of hrnet, and the results are very different after turning to onnx. Does anyone have a solution?

**Comment by faxu** [comment]
@eekarot can you share your model and the results you see from PT and ORT? Please also include details on which version of PT Exporter you are using and which version of ORT is used to run.

**Comment by eekarot** [comment]
> @eekarot can you share your model and the results you see from PT and ORT? Please also include details on which version of PT Exporter you are using and which version of ORT is used to run.

I've solved the problem. The previous inconsistency is because the output dimension of hrnet is 80 * 80. I will normalize the result directly and then interpolate it back to the dimension I need. The result is that the final mask is not consistent with what I want. Now I interpolate the result first, then normalize it, and get the expected result.

**Comment by eekarot** [comment]
> @eekarot can you share your model and the results you see from PT and ORT? Please also include details on which version of PT Exporter you are using and which version of ORT is used to run.

tks
