### ISSUE TITLE
raw_data field doesn't exist when trying to quantize transformer

### ISSUE THREAD

**Issue by Octopirate1** [microsoft/onnxruntime#6422]
**Describe the bug**

``ValueError: raw_data field doesn't exist`` when trying to quantize 774M gpt2 huggingface transformer into int8. 

**Urgency**

Yes, this project must be completed by Wednesday the 27th.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source (pip install -e)
- ONNX Runtime version: 1.6.0
- Python version: 3.6.9
- Visual Studio version (if applicable): NA
- GCC/Compiler version (if compiling from source): 7.4.0
- CUDA/cuDNN version: NA (using CPU)
- GPU model and memory: NA (using CPU)

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

Download `gs://tobylarge`, then attempt to run `python3 convert_to_onnx.py -m [modelpath]  -r --output [onnxpath] -o -p int8`.

**Expected behavior**
Conversion should complete as normal.

**Comment by yufenglee** [comment]
The bug was fixed in onnx: https://github.com/onnx/onnx/pull/3171. You can either build onnx from source with master or set use_external_format = false when calling the convert_graph_to_onnx.

**Comment by Octopirate1** [comment]
> The bug was fixed in onnx: [onnx/onnx#3171](https://github.com/onnx/onnx/pull/3171). You can either build onnx from source or set use_external_format = false when calling the convert_graph_to_onnx.

I have no idea how I missed this. Yep, this was the solution.
