### ISSUE TITLE
ONNX runtime fails with "Fatal program exit requested." due to ORT_THROW when AppendExecutionProvider_* in C#

### ISSUE THREAD

**Issue by nietras** [microsoft/onnxruntime#6426]
With execution providers in separate dlls e.g. `onnxruntime_providers_tensorrt.dll` the ONNX runtime fails catastrophically when calling e.g. `AppendExecutionProvider_TensorRT` if the dll is not available when called from C#. We use append to **try** to load any available execution providers that might be present, and this should be handled gracefully and return an error code (in C API, 
 and then throw managed exception in C#) not throw a native exception causing the entire process to be killed.

This is easy to reproduce by simply trying the above.

**Comment by RyanUnderhill** [comment]
Just to be clear, you're saying that the C API function to use a provider (like OrtSessionOptionsAppendExecutionProvider_Tensorrt) is throwing a native C++ exception internally instead of returning an error code?

**Comment by nietras** [comment]
@RyanUnderhill yes that's it. Would very much like this handled with an error code returned instead. :)

**Comment by RyanUnderhill** [comment]
@nietras Looks like we need to wrap all of those C APIs with a try/catch like we do in other cases. I thought there was no way for them to throw an exception but looks like I'm wrong. It'll be safer this way anyways.

I'll get this changed for an upcoming version. How urgent is the issue for you?

**Comment by RyanUnderhill** [comment]
Fixed by https://github.com/microsoft/onnxruntime/pull/7908
