### ISSUE TITLE
How to disable TF32 use on Ampere GPUs using TensorRT

### ISSUE THREAD

**Issue by nietras** [microsoft/onnxruntime#6427]
By default TensorRT will use TF32 floating point format when running on hardware supporting that. Using ONNX runtime and TensorRT how can one disable that?

**Comment by nietras** [comment]
You can disable TF32 by defining an environment variable `NVIDIA_TF32_OVERRIDE=0` as discussed in the link below:

https://docs.nvidia.com/deeplearning/tensorrt/release-notes/tensorrt-7.html

If you want to do that in code in C# (BEFORE calling any ONNX runtime code):
```csharp
const string NVidiaTF32OverrideName = "NVIDIA_TF32_OVERRIDE";
const string NVidiaTF32OverrideDisable = "0";
Environment.SetEnvironmentVariable(NVidiaTF32OverrideName, NVidiaTF32OverrideDisable);
```

**Comment by AnishKumarNayak** [comment]
Hi, I was wondering exactly what would happen if you disabled TF32? Like what are the repercussions of that. Could anyone direct me to the necessary resources? Thanks a lot
