### ISSUE TITLE
python bindings: InferenceSession can't be pickled

### ISSUE THREAD

**Issue by xadupre** [microsoft/onnxruntime#643]
**Describe the bug**
TypeError: can't pickle onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession objects

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian
- ONNX Runtime installed from (source or binary): github
- ONNX Runtime version: 
- Python version: 3.7.2
- GCC/Compiler version (if compiling from source):

**To Reproduce**
pickle a InferenceSession

**Expected behavior**
Pickle by saving the bytes.

**Comment by pranavsharma** [comment]
Did this ever work before? If not, can you describe the motivation for this new feature? Thanks!

**Comment by faxu** [comment]
@xadupre If this is still needed, could you please answer the questions above? Thx!

**Comment by xadupre** [comment]
It is easier to write agnostic benchmarks if it is available. I'll propose a PR for that.

**Comment by faxu** [comment]
@xadupre is this still active or has it been resolved?

**Comment by faxu** [comment]
@xadupre has there been any update on this and whether it is still needed?

**Comment by xadupre** [comment]
@faxu: the discussion about this issue happened in PR #800. I made a fix but it was not approved so I stopped working on it. There exists a workaround but slower.
