### ISSUE TITLE
Dockerfile build failures for CPU and CUDA dockers

### ISSUE THREAD

**Issue by mvermeulen** [microsoft/onnxruntime#6432]
**Describe the bug**
Starting ~2.5 weeks ago, both the CPU and CUDA dockerfiles had changes that cause the following docker builds to now fail:
```
cd onnxruntime; docker build -f dockerfiles/Dockerfile.source .
```
Following is a backtrace of these failures:
```
[ 59%] Linking CXX static library libonnx.a
[ 59%] Built target onnx
make: *** [all] Error 2
Makefile:181: recipe for target 'all' failed
Traceback (most recent call last):
  File "/code/tools/ci_build/build.py", line 2061, in <module>
    sys.exit(main())
  File "/code/tools/ci_build/build.py", line 1997, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/code/tools/ci_build/build.py", line 1020, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/code/tools/ci_build/build.py", line 523, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/code/tools/python/util/run.py", line 44, in run
    env=env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '/code/build/Linux/Release', '--config', 'Release', '--', '-j32']' returned non-zero exit status 2.
The command '/bin/sh -c cd /code && /bin/bash ./build.sh --skip_submodule_sync --use_openmp --config Release --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=$(cat ./VERSION_NUMBER)' returned a non-zero code: 1
```
Is there something else now needed on the docker build command line or other explanation of why this has started failing?

**System information**
- Linux Ubuntu 18.04 and 20.04
- ONNX Runtime built from commit: e1dc268e45f1f37a7b46d37e47d65416832b1db7 but appeared between 2 and 3 weeks ago
- Docker version 19.03.6, build 369ce74a3c (current "docker.io" on Ubuntu)

**To Reproduce**
- Check out onnxruntime
- cd onnxruntime
- docker build -f dockerfiles/Dockerfile.source .

**Expected behavior**
Successful docker build

**Additional information**
Dockerfile.cuda fails with similar signature and started failing at the same time.

**Comment by snnn** [comment]
I just built it by using Azure ACR Tasks,  and it works well. 

The commands I used were:

az acr task create --registry xxxxx.azurecr.io --name ortgpu_master --image public/azureml/onnxruntime:nightly-cuda10.2-cudnn8 --context https://github.com/Microsoft/onnxruntime.git#master --file dockerfiles/Dockerfile.cuda --commit-trigger-enabled false --timeout 10800

az acr task create --registry xxxx.azurecr.io --name ortcpu_master --image public/azureml/onnxruntime:nightly --context https://github.com/Microsoft/onnxruntime.git#master --file dockerfiles/Dockerfile.source --commit-trigger-enabled false

If it doesn't work on your side, please give us more logs.  The above backtrace isn't enough. I can't tell what went wrong.

**Comment by mvermeulen** [comment]
Thanks for the reply.  I believe I understand the cause - letting my submodules get out of date.  I will close this issue.

In more detail: I used to have a job that would go a "git pull" followed by a "docker build" on a periodic basis.  That worked fine because the dockerfiles would go a "git clone --recursive" to fetch all the sources.  After a recent change to the CUDA and CPU dockerfiles to instead "ADD" from the local repository, my "git pull" was no longer sufficient since it wasn't updating the submodules.  Worked for some weeks but at some point something needing later versions of these submodules must have come in and this build broke.

Deleting my original repository and going a "git clone --recursive" afresh made my builds work again.  Will figure out best way to also keep these submodules up to date at the same time that I update with a "git pull".

Thanks @snnn

**Comment by snnn** [comment]
You may try:
"git submodule update --init --recursive" before every time you run "docker build".
