### ISSUE TITLE
Problem in adding custom operator

### ISSUE THREAD

**Issue by SubjectNoi** [microsoft/onnxruntime#6445]
Now I'm trying to add a custom operator named "Comm" under the instruction of https://github.com/microsoft/onnxruntime/blob/master/docs/AddingCustomOp.md, type-3. I want to know some detailed step-by-step in this way.

System Info:
Ubuntu 18.04, ONNX Runtime CPU only

Currently, I have a op named "Comm" to add. I've added following files:
 /onnxruntime/contrib_ops/cpu/comm.h
/onnxruntime/contrib_ops/cpu/comm.cc
And I've modified following files:
/onnxruntime/contrib_ops/cpu/cpu_contrib_kernels.cc [Add 2 line for registation]
/onnxruntime/core/graph/contrib_ops/contarib_defs.cc [Add several line for scheme]

However, when I load an onnx model with "Comm" node in it, the runtime return: 
```
terminate called after throwing an instance of 'Ort::Exception'
  what():  Load model from ../script/splited.onnx failed:This is an invalid model. Error in Node: : No Op registered for Comm with domain_version of 12
```

**I wonder whether I miss some file to add or modify?**

The code I've added:
_/onnxruntime/contrib_ops/cpu/comm.h_
```
#pragma once

#include "core/common/common.h"
#include "core/framework/op_kernel.h"
#include "core/util/math_cpuonly.h"
#include "core/mlas/inc/mlas.h"
#include "core/platform/threadpool.h"
#include <unsupported/Eigen/SpecialFunctions>
#include "core/providers/cpu/element_wise_ranged_transform.h"

namespace onnxruntime {
namespace contrib {
template <typename T>
class Comm : public OpKernel {
public:
    Comm(const OpKernelInfo& info) : OpKernel(info) {
         //...
    }

    Status Compute(OpKernelContext* context) const override {
        // ...
        return Status::OK();
    }
private:
    std::string sub_type;
};
}
}

```

_/onnxruntime/contrib_ops/cpu/comm.cc_
```
#include "contrib_ops/cpu/comm.h"
namespace onnxruntime {
namespace contrib {

ONNX_OPERATOR_KERNEL_EX(
    Comm,
    kMSDomain,
    1,
    kCpuExecutionProvider,
    KernelDefBuilder().TypeConstraint("T", DataTypeImpl::GetTensorType<float>()),
    Comm<float>
);

}
}
```

**Comment by KeDengMS** [comment]
Seems the kernel is registered in kMSDomain, with opset version 1. Could you check if the node in onnx file is also in the same domain and version?

**Comment by SubjectNoi** [comment]
In netron, my model is: ONNX v7 and ai.onnx v12, so I should set the domain to be kOnnxDomain and set opset (By Since()) to 7?

**Comment by KeDengMS** [comment]
You need to add additional domain to the mode. Below is an example in Python:
```
import onnx
#load file
mp = onnx.load('/data/repos/orttrain/onnxruntime/test/testdata/layernorm.onnx')
# add opset for kMSDomain
opset = mp.opset_import.add()
opset.domain = "com.microsoft"
opset.version = 1
# find the node with op_type == Comm, and add domain
for n in mp.graph.node:
  if n.op_type == "Comm":
    n.domain = "com.microsoft"
# save file
onnx.save(mp, '/path/to/file')
```
The string ```com.microsoft``` comes from [kMSDomain](https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/graph/constants.h#L15) declared in your kernel, and the code above adds domain to both model description and node.

**Comment by SubjectNoi** [comment]
Now after I change the domain and version to `kOnnxDomainAlias` and `12` respectively, I got following message:
`Schema error: Trying to register schema with name Comm (domain: ai.onnx version: 12) from file /onnxruntime/core/graph/contrib_ops/contrib_defs.cc line 2208, but it its domain is not known by the checker.`

**Comment by KeDengMS** [comment]
Please check how your op schema is registered. [Here](https://github.com/microsoft/onnxruntime/blob/f3a0344f9a9c8256d114ae9b930eaaa0c1f37592/orttraining/orttraining/core/graph/training_op_defs.cc#L1717-L1718) is an example of registering op schema to kMSDomain.

**Comment by SubjectNoi** [comment]
I‘ve solved this problem by setting the domain to "kOnnxDomain", thanks.
