### ISSUE TITLE
Build failure with --cmake_extra_defines onnxruntime_DEBUG_NODE_INPUTS_OUTPUTS=ON

### ISSUE THREAD

**Issue by wangyems** [microsoft/onnxruntime#6459]
**Describe the bug**
Build the ORT cpu from source(current master) on Linux:
./build.sh --config RelWithDebInfo --build_shared_lib --parallel --skip_tests --enable_pybind --build_wheel --cmake_extra_defines onnxruntime_DEBUG_NODE_INPUTS_OUTPUTS=ON

the error:
/onnxruntime/onnxruntime/test/debug_node_inputs_outputs/debug_node_inputs_outputs_utils_test.cc:30:39: error: no matching function for call to ‘UnpackTensor(onnx::TensorProto&, float*, std::vector<float>::size_type)’
   ASSERT_STATUS_OK(utils::UnpackTensor(tensor_proto, actual_data.data(), actual_data.size()));

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by snnn** [comment]
@wangyems What if you build it from the latest release branch, does it work?

@askhade , is it related to your recent change?

**Comment by hariharans29** [comment]
Was fixed in https://github.com/microsoft/onnxruntime/pull/6466
