### ISSUE TITLE
Does custom_op_library support Multiple dynamic inputs of CustomOp?

### ISSUE THREAD

**Issue by zr1161309493** [microsoft/onnxruntime#6469]
In #5049 ,The problem that the proposed custom op supports dynamic input seems to be solved.

But  in my case, I need to implement a two-input op, but the types of the two inputs are not fixed, there will be problems when using custom_library, it is not possible to set both inputs to Undefined, only when these two are of the same type are supported.
And the output of my custom op is fixed. 

The example is shown below.
![custom](https://user-images.githubusercontent.com/33832771/105934396-0c6b2080-608b-11eb-82b4-7f355941f2cc.jpg)

``` c++
 size_t GetInputTypeCount() const { return 2; };
  ONNXTensorElementDataType GetInputType(size_t /*index*/) const { return ONNX_TENSOR_ELEMENT_DATA_TYPE_UNDEFINED; };

  size_t GetOutputTypeCount() const { return 1; };
  ONNXTensorElementDataType GetOutputType(size_t /*index*/) const { return ONNX_TENSOR_ELEMENT_DATA_TYPE_INT8; };
```

HOW can I support this kind of  CustomOp by custom_op_library?

**Comment by KnightYao** [comment]
same problem...
