### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Type Error: Type parameter (T) bound to different types (tensor(float) and tensor(int64) in node (Mul_11).

### ISSUE THREAD

**Issue by jinfagang** [microsoft/onnxruntime#6470]
This single model export to onnx can not be inference using onnxruntime:

```
class ME(nn.Module):

    def __init__(self):
        super().__init__()

    def forward(self, x):
        idx = torch.randn([17, 1])
        width = idx.shape[0]
        # preds = torch.cat([idx, idx], dim=1).to(torch.float)
        preds = torch.cat([idx, idx], dim=1).to(torch.float)

        preds[:, 0] = (preds[:, 0]) % width
        preds[:, 1] = torch.floor((preds[:, 1]) / width)
        return preds
```

It will araise such error:

```
 sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Type Error: Type parameter (T) bound to different types (tensor(float) and tensor(int64) in node (Mul_11).
```

**Comment by BowenBao** [comment]
hi @jinfagang, what is the PyTorch version you are using? I tried your code and couldn't repro this issue, it is likely this is already resolved. Please give a try with latest PyTorch.

**Comment by syshensyshen** [comment]
i convert constant paramter in module forward formal parameter，error is gone ！
error is： “Type Error: Type parameter (T) bound to different types (tensor(float) and tensor(double) in node (Mul_436)”
because i use variances = [0.1, 0.2] in nn.Module, 0.1,0.2 wil be convert float64 in onnx model
