### ISSUE TITLE
Onnx/ort load model from buffer

### ISSUE THREAD

**Issue by dhirajnitk** [microsoft/onnxruntime#6475]
Tflite support reading model from buffer

`static std::unique_ptr<FlatBufferModel> BuildFromBuffer(const char* buffer, size_t buffer_size, ErrorReporter* error_reporter);`

I am using ort file's on Android but my model is huge, I don't wish to extract & copy them to data folders(of apk)

Is there any feature in onnx session to  read input stream to load model from buffer

**Comment by snnn** [comment]
@gwang-msft  Could you please help?

**Comment by gwang-msft** [comment]
Yes, you can directly create an ort session using the model data byte array, depends on which language you are using.

For example if you are using c++, you can do something similar using c or java,

You may choose to use this to create your session
https://github.com/microsoft/onnxruntime/blob/0100f336d7547486432e6808256d0b4938581a1b/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L348

And you need to set "session.load_model_format" config to "ORT" in your SessionOptions
https://github.com/microsoft/onnxruntime/blob/0100f336d7547486432e6808256d0b4938581a1b/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L324

https://github.com/microsoft/onnxruntime/blob/0100f336d7547486432e6808256d0b4938581a1b/include/onnxruntime/core/session/onnxruntime_session_options_config_keys.h#L27-L29

**Comment by dhirajnitk** [comment]
In c++ 
```
std::ifstream stream("mona.onnx", std::ios::in | std::ios::binary);
std::vector<uint8_t> contents((std::istreambuf_iterator<char>(stream)), std::istreambuf_iterator<char>());
```
Can I pass the char[]  to the above api


session.load_model_format config to ort is default behaviour which I have verified;)  No need to change options

**Comment by gwang-msft** [comment]
Your approach is equivalent to read the input stream into a byte array. 
Also it is better to set the load file format explicitly to "ORT" although we can identify the model format from the byte array.

**Comment by xyh523078979** [comment]
gettimeofday(&startTime, NULL);
 session = new Ort::Experimental::Session(env, content, length, session_options);
 gettimeofday(&endTime, NULL);
 printf("create session  takes:%fs\n", TIMEDIFF(startTime, endTime));

We first load model into a buffer, then we create session using model data bytes.  The model size is 174M ,  the time consumes 0.399875s,  can the time consumption be optimized?
