### ISSUE TITLE
onnxinferencetime

### ISSUE THREAD

**Issue by Pushpalathahareesh** [microsoft/onnxruntime#6499]
Hi, I need help in resolving this error:

When i inference in GPU mode using below code i get the error.

Inference Code:

def create_model_for_provider(model_path: str, provider: str):
assert provider in get_all_providers(), f"provider {provider} not found, {get_all_providers()}"

# Few properties that might have an impact on performances (provided by MS)
options = SessionOptions()#SessionOptions.MakeSessionOptionWithCudaProvider(0)
options.intra_op_num_threads = 1
options.graph_optimization_level = GraphOptimizationLevel.ORT_ENABLE_ALL

# Load the model as a graph and prepare the GPU backend
session = InferenceSession(model_path, options, providers=[provider])
session.disable_fallback()

return session
#run Inference on the onnx model
PROVIDERS = {
#("CPUExecutionProvider", "ONNX CPU"),
#Uncomment this line to enable GPU benchmarking
("CUDAExecutionProvider", "ONNX GPU")
}
for provider, label in PROVIDERS:
# Create the model with the specified provider
model = create_model_for_provider("D:/nlg_albert_optimize/onnx_files/albert_model_512.onnx", provider)

Error:
sess.initialize_session(providers or [], provider_options or [])
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\1\s\onnxruntime\core\providers\cuda\cuda_cal
l.cc:123 onnxruntime::CudaCall D:\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:117 onnxruntime::CudaCall CUDA failure 2: out of memory ; GPU=0 ; hostname=LAPTOP-6EUODJJ7 ; expr=cudaMa
lloc((void**)&p, size);
2021-01-28 18:18:38.4236867 [E:onnxruntime:, inference_session.cc:1268 onnxruntime::InferenceSession::Initialize::<lambda_c608601079ff6a1804107b16babd2631>::operator ()] Exception during
initialization: D:\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:123 onnxruntime::CudaCall D:\1\s\onnxruntime\core\providers\cuda\cuda_call.cc:117 onnxruntime::CudaCall CUDA failure 2:
out of memory ; GPU=0 ; hostname=LAPTOP-6EUODJJ7 ; expr=cudaMalloc((void**)&p, size);

Iam getting the above error when inferencing on onnx file "albert_model_512.onnx".

I got the above onnx file (albert_model_512.onnx)by converting pretrained transformer model ahotrod/albert_xxlargev1_squad2_512 , using below code
torch.onnx.export(model_instance,model_input, "albert_model_512.onnx",opset_version=12,use_external_data_format=True),
but this is not single file i have got. the above torch.onnx.export as generated many external files along with albert_model_512.onn, which are in in same directory( files are 1400,1401,1405.....1604,albert_model_512.onnx,albert.porition.embeddings.....,albert.encoder.albert_layer_groups.0.albert_layers.0.attention.LayerNorm.bias etc)

I wanted to know how the multiple files connected to model file albert_model_512.onnx is processed. Is there a way to do so.Pls let me know possible solutions. iam i following wrong procedure to convert to onnx, iam not sure. pls help me.

framework:pytorch
IDE:pycharm
pretrained transformer model: ahotrod/albert_xxlargev1_squad2_512
transformer version:4.2.0
regards,
pushpalatha M

pls help me to resolve this issue.

**Comment by ashbhandare** [comment]
The problem seems to be an out of memory error on your GPU, can you make sure that your GPU has enough memory to load the model?
The other files that you are seeing after conversion are the model parameters that are stored externally as binary files. You can read more about it here https://pytorch.org/docs/stable/onnx.html#use-external-data-format

**Comment by faxu** [comment]
@Pushpalathahareesh does this resolve your issue? if so, please close. thanks!

**Comment by Pushpalathahareesh** [comment]
> The problem seems to be an out of memory error on your GPU, can you make sure that your GPU has enough memory to load the model?
> The other files that you are seeing after conversion are the model parameters that are stored externally as binary files. You can read more about it here https://pytorch.org/docs/stable/onnx.html#use-external-data-format

**Comment by Pushpalathahareesh** [comment]
> The problem seems to be an out of memory error on your GPU, can you make sure that your GPU has enough memory to load the model?
> The other files that you are seeing after conversion are the model parameters that are stored externally as binary files. You can read more about it here https://pytorch.org/docs/stable/onnx.html#use-external-data-format

Thanks for the input
