### ISSUE TITLE
Graph optimization build options?

### ISSUE THREAD

**Issue by mudream4869** [microsoft/onnxruntime#6500]
The [performance troubleshooting checklist](https://www.onnxruntime.ai/docs/how-to/tune-performance.html#performance-troubleshooting-checklist) said that there are some options for graph optimizations.

> Have you enabled all graph optimizations? The officially published packages do enable all by default, but when building from source, check that these are enabled in your build.

However, I can't find any options for graph optimizations in `tools/ci_build/build.py` or `BUILD.md`.

**Comment by yuslepukhin** [comment]
Graph optimizations are performed at runtime and are controlled via SessionOptions.

**Comment by faxu** [comment]
See https://www.onnxruntime.ai/docs/resources/graph-optimizations.html#usage
