### ISSUE TITLE
onnxruntime_tools.optimizer_cli conversion to fp16 breaks types for adding a constant

### ISSUE THREAD

**Issue by vadimkantorov** [microsoft/onnxruntime#6501]
We have a model exported with PyTorch to ONNX that uses the following function.
```python
def normalize_signal(signal, dim = -1, eps = 1e-5, denom_multiplier  = 1.0):
	signal_max = signal.abs().max(dim = dim, keepdim = True).values + eps
	return signal / (signal_max * denom_multiplier) if signal.numel() > 0 else signal
```

Then we run onnxruntime_tools.optimizer_cli with `--float16` to convert to use fp16. We run into typing problem:
```
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in init
self._create_inference_session(providers, provider_options)
File "/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 226, in _create_inference_session
sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ./JasperNetBig_NovoGrad_lr2e-5_wd1e-3_bs512_slow_fine_tune_after_uncertainty_self_train_checkpoint_epoch268_iter0370000_fp16.pt.onnx failed:Type Error: Type parameter
(T) bound to different types (tensor(float) and tensor(float16) in node (Add_11).
```

Add_11 refers to adding the epsilon: ![image](https://user-images.githubusercontent.com/1041752/106291390-d9bc5600-624b-11eb-8079-272bfaad85c5.png)

It seems that the constant type was not converted. If the constant value is nor preserved by float16, a warning would be warranted, but a silent type mismatch during conversion is confusing

**Comment by tianleiwu** [comment]
@vadimkantorov, 

Could you try 
https://github.com/microsoft/onnxconverter-common/blob/09827b56c0d4f359952aac8e0160ff6290ac37f2/onnxconverter_common/float16.py#L267

It seems that float16.py has no dependency on other files so you can download the file and use it directly.

@wangyems to check whether constant type is converted.

**Comment by wangyems** [comment]
We do convert the constant type https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/onnx_model.py#L420

It's possible that the constant is converted to half but another input remains float

**Comment by vadimkantorov** [comment]
Is there a way to check this is in Netron?

**Comment by wangyems** [comment]
> Is there a way to check this is in Netron?

There is not. The input type is determined during runtime.

**Comment by tianleiwu** [comment]
@vadimkantorov, it is able to check the constant type in Netron. 

From the error message, it seems that the first input is float and the constant is float16. If that is the case, need add a Cast (to float16) before Add node.

**Comment by vadimkantorov** [comment]
Thanks! I guess then the call should be with System.Half.
