### ISSUE TITLE
Is it possible to publish a pypi package without openmp requirement?

### ISSUE THREAD

**Issue by daquexian** [microsoft/onnxruntime#6511]
Reference: https://github.com/ultralytics/yolov5/issues/1597#issuecomment-754782516

I think it is not user-friendly that every user must install openmp before using onnxruntime.

**Comment by snnn** [comment]
https://pypi.org/project/onnxruntime-noopenmp/

**Comment by daquexian** [comment]
@snnn Thanks for your reply. I noticed that there is no onnxruntime-noopenmp for macos. Is it possible to publish the macos version?
