### ISSUE TITLE
optimization in pytorch can not work in onnx

### ISSUE THREAD

**Issue by WilliamZhaoz** [microsoft/onnxruntime#6512]
pleare check the related issue: 
https://github.com/onnx/onnx/issues/3246

I did some optimization in pytorch, it get ~4times speed up, but when I convert the model to onnx, it can not work.
I just re-use some middle result in ConvNet, there are some if else branch to decide re-use or not, I store the middle results in a memory cache, and every inference I update the cache, and use some number in it.
Does anyone have any ideas?

The onnx model actually produce the right output, but not expected speed. My optimization is not complicated at all, it is very simple and straight forward, like, it would process X points, but there are half of X is overlaped in every forward, so I let it just process a half of X, and pad another half of it from a memory cache, of course, I will update the cache every time. In this way, I can feed X point data to model and get X points output with only a half of X data need to be calculated. The model receive X data and the cache, output X points output and updated cache. I expected only a half of the original time is need, and in pytorch it does, but in onnx it still take the same time as processing the X points data. I am thinking that is it possible that onnx fuse or combine some ops and in this process a smaller op is aligned to a bigger op which leads this problem I hit?

**Comment by faxu** [comment]
Which version of the pytorch exporter did you use? would you be able to share the model for investigation? you can also take a look at the profiling tool to see which nodes are taking the most time. https://www.onnxruntime.ai/docs/how-to/tune-performance.html#profiling-and-performance-report

**Comment by MaanavD** [comment]
Closed due to no response. Feel free to open again if relevant.
