### ISSUE TITLE
How do I load and run models that have multiple inputs and multiple  outputs using the C API?

### ISSUE THREAD

**Issue by laizewei** [microsoft/onnxruntime#6515]
How do I load and run models that have multiple inputs and multiple  outputs using the C API?
Can you provide examples?

**Comment by pranavsharma** [comment]
https://github.com/microsoft/onnxruntime/blob/master/docs/FAQ.md#how-do-i-load-and-run-models-that-have-multiple-inputs-and-outputs-using-the-cc-api

**Comment by Koushik667** [comment]
Hello, @pranavsharma is there any support for inference of onnx models in C, i have seen only examples of c++ till now.
