### ISSUE TITLE
How to use default CPU execution provider for math operations on tensors? I can't find any documentation...

### ISSUE THREAD

**Issue by sharonhezy** [microsoft/onnxruntime#6527]
I have a list of tensors which I need to apply on the input data before and after the model itself (normalization, transpose, scaling factors, etc..)
In pytorch (C++ libtorch) - I can use the tensors math operations (such as matmul, add, ...) - to operate on the inference input & output. 
I was able to translate the pytorch model to onnx and run it with onnxruntime, with "fake" random data.
In order to integrate and check onnxruntime in the system - I need the ability to pre-/post-process the data I'm running inference on.
Can you please provide me with a small example how to access tensor operations in the default CPU provider? I saw plenty of code and documentation that shows&explains how to **define** different providers for a session, but I guess this is intended for using the providers internally during the inference. I didn't see any code that shows how to **call**/**use** execution provider's math. functions in user's code.
I believe there should be a possibility to access the execution providers' mathematical functions from the user's code, but I can't find anything on it.

Please help - I'm totally stuck, I need to understand if I must use other libraries / write my own code, or I can use the execution_provider's operations for these tensor operations.

**Urgency**
Urgent - please help.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): latest stable version (1.6), compiled from sources
- ONNX Runtime version: 1.6
- Python version: 3.7.9 (but python is irrelevant - the question is related to C++ only)
- Visual Studio version (if applicable): VS19
- GCC/Compiler version (if compiling from source): default cl.exe coming with VS19
- CUDA/cuDNN version: -
- GPU model and memory: -

Thanks a lot in advance!

**Comment by pranavsharma** [comment]
Kernels are not directly exposed to users. If you're looking to do any pre/post processing logic, you can create a separate onnx model with [custom ops](https://github.com/microsoft/ort-customops) if required or edit your existing model to insert pre/post processing ops.

**Comment by sharonhezy** [comment]
Thank you very much for clarifying and for the relevant documentation link.
