### ISSUE TITLE
per channel sym performance problem?

### ISSUE THREAD

**Issue by dongzhen123** [microsoft/onnxruntime#6545]
when I run the quantization model in per channel sym mode  of resnet18 in imagenet ,I found 

per channel acc is much lower than per layer ,per channel:67.392 per layer :69.434

Is there a bug in per channel mode?

**Comment by yufenglee** [comment]
could you please try enabling reduce_range for per-channel?

**Comment by dongzhen123** [comment]
> could you please try enabling reduce_range for per-channel?

enabling reduce_range  and the acc is even lower Theoretically.

**Comment by yufenglee** [comment]
the reduce_range option is to handle overflow case for avx2 machine. Please refer to the details here: https://github.com/microsoft/onnxruntime/issues/5849#issuecomment-733178450

**Comment by dongzhen123** [comment]
> the reduce_range option is to handle overflow case for avx2 machine. Please refer to the details here: [#5849 (comment)](https://github.com/microsoft/onnxruntime/issues/5849#issuecomment-733178450)

Thx!
