### ISSUE TITLE
[java] load shared library providers

### ISSUE THREAD

**Issue by Craigacp** [microsoft/onnxruntime#6553]
**Is your feature request related to a problem? Please describe.**
The DNNL, TensorRT and OpenVINO providers are now created as shared libraries loaded by ONNX Runtime using the system library loader from a hardcoded path relative to the runtime's path. This conflicts with how Java wants to load the libraries, as they are all bundled into the jar file, extracted at runtime and loaded via the Java `System.loadLibrary` call. As a result these shared providers are currently broken in the Java API and cannot be used. 

**Describe the solution you'd like**
A way to access the provider registration through the C API, and to disable library unloading as the OS will do that for us when the JVM shuts down.

**Describe alternatives you've considered**
We could extract the providers from the jar file when the C API is initialised and write to the current runtime directory so they get picked up by the loader in the C++ code. This will leave files lying around in unexpected directories and they may not get cleaned up properly due to an issue with how `File.deleteOnExit()` works on Windows for dlls.

Alternatively we could add documentation on how to compile the shared library providers and ask users to put them in the right folder before running ORT, which is very unfriendly to the users.

**Additional context**
I think the providers are loaded in this block:

```C++
  Provider* Get() {
    if (provider_)
      return provider_;

    if (!s_library_shared.Ensure())
      return nullptr;

    std::string full_path = Env::Default().GetRuntimePath() + std::string(filename_);
    auto error = Env::Default().LoadDynamicLibrary(full_path, &handle_);
    if (!error.IsOK()) {
      LOGS_DEFAULT(ERROR) << error.ErrorMessage();
      return nullptr;
    }

    Provider* (*PGetProvider)();
    Env::Default().GetSymbolFromLibrary(handle_, "GetProvider", (void**)&PGetProvider);

    provider_ = PGetProvider();
    return provider_;
  }
```
so I think I'd need a method that lets me write the `GetProvider` pointer into the struct, and then add a hook to ignore the unload.

The unload might actually work anyway as it's been loaded by the same process, but until I can get control of the library loading its difficult to test.

**Comment by yuslepukhin** [comment]
@RyanUnderhill FYI

**Comment by RyanUnderhill** [comment]
@Craigacp Do my upcoming shared cuda provider changes help resolve some of this? Or is there still an issue with 'delete on exit' with the shared libraries too?

**Comment by Craigacp** [comment]
Well it'll make everything load properly. Windows' behaviour with `deleteOnExit` is a pain for Java code which unpacks dlls at runtime, but there isn't much to be done about it unless we have direct control of the unloading code. I'll need to make equivalent modifications to the Java loader for the other libraries that have shared providers, and I'm still a little worried about the way it loads things inside the native code because it's not clear to me that it's pulling things in from the right path, but if it's working then presumably the platform dynamic loader is figuring it out.

Did you test the Java/CUDA bits on both Windows & Linux? I guess I'll need to test DNNL on macOS as well, as that could also have different behaviour.

**Comment by RyanUnderhill** [comment]
@Craigacp I ran through all of our pipeline tests, and I thought that includes Java on windows & linux.

As for the path it looks for the shared providers, on Windows it looks for them in the same path as onnxruntime.dll is. On Linux it does a similar thing through RPATH (search for -rpath in onnxruntime_providers.cmake for where it's set). So this should always work (done this way for security and simplicity)
