### ISSUE TITLE
Google colab crashes when trying to load the model (containing a custom operator) for inferencing using ORT.

### ISSUE THREAD

**Issue by MLDLwizard** [microsoft/onnxruntime#6571]
Hi @askhade @pranavsharma 

**Describe the bug**
I have been wanting to test the inference times of a custom operator as described [here](https://github.com/onnx/onnx/issues/3205).
I was asked to chose either of the methods.
1.Make changes to the onnx sub-module in onnxruntime/cmake/external/ so that ORT thinks it as an official operator and continue the registartion and kernel implementation in ORT.
2.Register the custom op as a contrib_op. (Works)

Initially, I tried defining an operator in ONNX named DQL, which is just a copy of the DynamicQuantizeLinear in ONNX and followed its implementation in ORT as shown here,
microsoft/onnxruntime@d84799e . and DQL works fine while inferencing in ORT.

However, when I followed the first approach for implementing my custom op(an activation fn), and tried to inference the graph (built with the help of helper.make_node and helper.make_graph in onnx) google colab crashes while loading the model.

> sess = rt.InferenceSession("Mkcustom.onnx")

I have followed the approach in onnxruntime/onnxruntime/core/providers/cpu/activation/activations.cc , activations.h , and onnxruntime/core/providers/cpu/cpu_execution_provider.cc 
and added the op schema to onnx and onnx submodule in ORT.

**Urgency**
Very Urgent.

**Expected behavior**
The operator is supposed to successfully load into the session and inferencing should be done, but instead google colab crashes.

**Comment by snnn** [comment]
Hi @yufenglee , is it related to DynamicQuantizeLinear ?

**Comment by MLDLwizard** [comment]
> Hi @yufenglee , is it related to DynamicQuantizeLinear ?

Hi @snnn ,
No, It isn't related to DynamicQuantizeLinear. 
I was stating that, I was able to replicate the workflow of DynamicQuantizeLinear and renamed it as DQL , and it was working perfectly fine.

However, when I tried to follow a similar approach with my custom operator, Google Colab crashes while loading the model.

**Comment by MLDLwizard** [comment]
Hi, 
Sorry for the delay in response. 
The issue was because of improper output variable in the operator schema, which resulted in system crash. I had fixed it and the custom operators work like a charm. Thank you!
