### ISSUE TITLE
macOS: Errors when cross compiling for arm64

### ISSUE THREAD

**Issue by JanosGit** [microsoft/onnxruntime#6573]
**Describe the bug**
I want to compile onnxruntime for new arm64 macs to build a universal onnxruntime binary. I do that with this command:
```
python3 onnxruntime/tools/ci_build/build.py --build_dir build_arm64 --build --update --parallel --build_shared_lib --disable_nccl --skip-keras-test  --use_full_protobuf  --include_ops_by_config required_operators.config --skip_tests --disable_ml_ops --minimal_build  --osx_arch arm64 --config Release
```
which is basically the same command as successfully used for our x86_64 mac builds. During compilation it fails with

```
[ 21%] Building CXX object external/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/repeated_field.cc.o
Path/to/onnxruntime/onnxruntime/core/mlas/lib/aarch64/QgemmU8X8KernelNeon.S:86:16: error: brackets expression not supported on this target
        ldr x8,[sp,#.LGemmU8X8KernelFrame_ColumnSumBuffer]
```

The goal is to combine the x86_64 and arm64 build into a universal binary dylib using `lipo`.

**Urgency**
Medium. We are currently working on porting our dependencies to universal binaries to create native M1 optimised versions of our software but this is still work in progress 

**System information**
- OS Platform and Distribution: macOS 10.15.6
- ONNX Runtime installed from (source or binary): Source
- ONNX Runtime version: 1.6.0
- Python version: 3.7.3
- Visual Studio version (if applicable): -
- GCC/Compiler version (if compiling from source): Apple clang 12.0.0

**To Reproduce**
Execute build command as above

**Expected behavior**
Successful compilation of an arm64 library

**Comment by gwang-msft** [comment]
For now, cross build for Apple M1 using x64 Mac is only supported by using XCode as the CMake Generator (by adding `--use_xccode` to your build command, such as 
```
python3 onnxruntime/tools/ci_build/build.py --build_dir build_arm64 --build --update --parallel --build_shared_lib --disable_nccl --skip-keras-test  --use_full_protobuf  --include_ops_by_config required_operators.config --skip_tests --disable_ml_ops --minimal_build  --osx_arch arm64 --config Release --use_xcode
```

**Comment by JanosGit** [comment]
No, I was using the Xcode-supplied CMake 3.18... switching to the home-brew installed CMake 3.19 resolved it  🤦‍♂️ Would it be possible to add a check for the CMake version and aborting the build with a clear error when compiling for macOS/arm64 with CMake < 3.19 for people like me?

**Comment by gwang-msft** [comment]
We do have the CMake version requirements listed here https://github.com/microsoft/onnxruntime/blob/master/BUILD.md#macos, however it will be nice to raise the error in the building script.

**Comment by snnn** [comment]
I will submit a PR and publish a test package tomorrow.

**Comment by snnn** [comment]
https://test.pypi.org/project/onnxruntime/1.8.2.dev20210816004/
To install it:
```
pip3 install --upgrade pip
pip3 install numpy
pip3 install -i https://test.pypi.org/simple/ onnxruntime==1.8.2.dev20210816004
```

**Comment by snnn** [comment]
Once PR #8754 is merged, you can build it in a way like:
```
python3 tools/ci_build/build.py --parallel  --build_dir b --config Debug --skip_submodule_sync --cmake_extra_defines CMAKE_OSX_ARCHITECTURES='arm64'
```

**Comment by faxu** [comment]
Closing this as compiling is now supported. Please reactivate if there are still issues.
