### ISSUE TITLE
InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from Models/onnx_mutate_2.onnx failed:This is an invalid model. Error in Node:c1 : Required attribute 'to' is missing.

### ISSUE THREAD

**Issue by Sarthak-Agrawal** [microsoft/onnxruntime#6600]
**Describe the bug**
Created an Onnx model using helper functions but unable to load the model in Onnxruntime. The model consists of 2 columns that need to be casted from string to float data types.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.6.0
- Python version: 3.7.9

**To Reproduce**
```
I1 = helper.make_tensor_value_info('I1', TensorProto.STRING, [1, 1])
I2 = helper.make_tensor_value_info('I2', TensorProto.STRING, [1, 1])

# Create one output (ValueInfoProto)
X1 = helper.make_tensor_value_info('X1', TensorProto.FLOAT, [1, 1])
X2 = helper.make_tensor_value_info('X2', TensorProto.FLOAT, [1, 1])

node_def = helper.make_node(
    'Cast', # node name
    ['I1'], # inputs
    ['X1'], # outputs
    name='c1'
)

node_def_2 = helper.make_node(
    'Cast', # node name
    ['I2'], # inputs
    ['X2'], # outputs
    name='c2'
)

# Create the graph (GraphProto)
graph_def_2 = helper.make_graph(
    [node_def, node_def_2],
    'test-model',
    [I1, I2],
    [X1, X2],
)
model_def_2 = helper.make_model(graph_def_2, producer_name='onnx-example-2')
onnx.save(model_def_2, 'Models/onnx_mutate_2.onnx')

sess = rt.InferenceSession("Models/onnx_mutate_2.onnx")
```
**Expected behavior**
Expecting the ort to load the model. And the following prediction to run properly.
```
sess = rt.InferenceSession("Models/onnx_mutate_2.onnx")
pred_onx = sess.run(['X1', 'X2'], {'I1': [['6']], 'I2':[['2']]})[0]
print(pred_onx)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/15011367/107130984-c74fb580-68f8-11eb-9650-ceaede5b728d.png)

**Comment by tianleiwu** [comment]
Cast requires an attribute 'to' like 
https://github.com/onnx/onnx/blob/6544dba74a4a0c9d937507b6f8f6a4cb20234701/onnx/backend/test/case/node/cast.py#L91

**Comment by Sarthak-Agrawal** [comment]
Thanks @tianleiwu. This worked.

**Comment by aimen123** [comment]
i have a idea ,too .
i just change
![image](https://user-images.githubusercontent.com/11974962/186855360-7d8e815d-83c7-4f38-9c20-1d3a24d9426c.png)
to 
![8c56af641ec57714ddb05a25fda1369](https://user-images.githubusercontent.com/11974962/186855455-466f704c-2d22-4a64-9b55-7edf4c2c876f.png)


the error is 
![5d5c9e575d359e0d75c218a9af16566](https://user-images.githubusercontent.com/11974962/186855628-ae80d902-2284-42eb-a1f3-1ec3267262eb.png)

i nee a help , thanks

**Comment by tianleiwu** [comment]
@aimen123, see data type constraint of the operator: https://github.com/microsoft/onnxruntime/blob/54360c88d21912f63cc1cc9b01df82cd85dab845/onnxruntime/core/graph/contrib_ops/quantization_defs.cc#L203-L239
