### ISSUE TITLE
How could I set dymanic input size when customizing an operator

### ISSUE THREAD

**Issue by Walstruzz** [microsoft/onnxruntime#6606]
Hello, I am customizing an new operator, like conovlution, which has 2 or 3 inputs.
Following the offical example, function `GetInputTypeCount()` must return a determine number.
https://github.com/microsoft/onnxruntime/blob/1dd920fa7cac2d2ce8a0b497f2f32bd4a2b099fc/onnxruntime/test/shared_lib/test_inference.cc#L323
But sometimes there has `bias` and sometimes not. How could I do?

Thank you.

**Comment by RyanUnderhill** [comment]
Currently the custom ops through this interface can only have fixed inputs & outputs. The way to have different inputs is to create multiple custom ops.

We're thinking about extending things as this has been requested, but does this let you do what you want for now?
