### ISSUE TITLE
Can you provide the OnNXRuntime Windows precompiled libraries based on CUDA11 and CUDNN8

### ISSUE THREAD

**Issue by laizewei** [microsoft/onnxruntime#6607]
Can you provide the OnnXRuntime Windows precompiled libraries based on CUDA11 and CUDNN8?
I tried to compile it myself, but it failed.

**Comment by snnn** [comment]
Yes, the next onnxruntime release will be based on CUDA 11 and CUDNN 8.0.3.33

**Comment by snnn** [comment]
It is ready for testing now:https://test.pypi.org/project/ort-gpu-nightly/

We will publish it to the  official pypi index when testing is done.

**Comment by laizewei** [comment]
Can you provide 64 bit dynamic link library？dll
