### ISSUE TITLE
CUDA 10.1 Linux Build failure: cannot call member function without object

### ISSUE THREAD

**Issue by xkszltl** [Microsoft/onnxruntime#661]
**Describe the bug**

Get error inside STL when compiling with CUDA 10.1 (I remember I saw this on 10.0 as well but not 100% sure) on Linux: `Cannot call member function without object.`

![image](https://user-images.githubusercontent.com/5203025/54683086-fde67200-4acd-11e9-808d-8b8c556c665b.png)

This might be a compiler error that can be worked around:
https://github.com/protocolbuffers/protobuf/issues/5805

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: v0.3.0
- Python version: 3.6 (from rh-python36)
- GCC/Compiler version (if compiling from source): gcc 6.3.1/7.3.1/8.2.1 from devtoolset-6/7/8 (same error)
- CUDA/cuDNN version: 10.1
- GPU model and memory: Volta

**Comment by snnn** [comment]
We don't support CentOS 7.
And, For every Linux release we support, please use the stock compiler that came along with the OS.  I don't think it's a compiler bug, because nobody guarantees GCC 8 can work on CentOS 7.

**Comment by xkszltl** [comment]
gcc 8 is one of the stock compiler, from devtoolset-8:
https://developers.redhat.com/products/developertoolset/

When I say "compiler bug" I'm talking about nvcc.

**Comment by snnn** [comment]
You were talking RHEL, not CentOS. You are using CentOS, not RHEL.  They are different in many ways. One most important thing is: devtoolset is **not free**. 

And, CUDA 10 does not support RHEL with devtoolset-8.  It only supports the **default** compiler on RHEL/CentOS. The CUDA development environment relies on tight integration with the host development environment, including the host compiler and C runtime libraries, and is therefore only supported on distribution versions that have been qualified for this CUDA Toolkit release. It clearly says, on CentOS 7, it only supports gcc 4.8.5. ref: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements

The error you posted here, is a well known CUDA problem. It isn't any related to onnxruntime. There is nothing we can do.

**Comment by xkszltl** [comment]
What exactly do you mean by "devtoolset is not free"? It comes with CentOS

**Comment by snnn** [comment]
> What exactly do you mean by "devtoolset is not free"? It comes with CentOS

evidence?

**Comment by xkszltl** [comment]
I've been using it on CentOS for years.

This is how to get it working:
https://wiki.centos.org/AdditionalResources/Repositories/SCL

**Comment by xkszltl** [comment]
And NV doesn't mention a strict binding of distro / gcc version here:
https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-compiler-new-features

![image](https://user-images.githubusercontent.com/5203025/54776229-e7731000-4bcc-11e9-9402-b223712942f5.png)

Actually in reality it's usually OK to use the highest support version regardless of the distro (gcc is just a compiler, you can build it yourselves)
Haven't touch the gcc4.8.5 for a long time.

**Comment by snnn** [comment]
The link you posted before, was devtoolset, which is not free.  You need a RH subscription to use it.
Now you are talking SCL, it's different.

Whatever, have you ever seen Red Hat build any part of the RHEL/CentOS with the tools you posted? 
Whether it's  on Windows or Linux,  on top most principle for every C/C++ developer is: don't mix compilers together. Either you build the whole program and all its dependencies with GCC 4.8, or you build all of them with GCC 8. But you can't mix them. If we can compile onnxruntime without depending on any existing shared libraries in the operating system, then it's worth to try. Otherwise, we won't pay any time on debugging the system level compatibility issues.

**Comment by xkszltl** [comment]
devtoolset is a toolchain build and ship by SCL.
```
yum install -y centos-release-scl # This enables SCL repo where devtoolset lives
yum install -y devtoolset-8 # This installs devtoolset
```

And it's very common to mix compiler in my experience when I need

- an upgrade version of gcc
- an upgrade version of clang
- gcc on macOS
- llvm on Linux
- icc on any distro

And to answer your question:
- SCL itself is build by RH and shipped as part of RHEL/CentOS.
- Everything relies on a particular SCL is named within the domain. There used to be a lot of non-toolchain components named as devtoolset-4-xxx (FYI devtoolset-4 is for 5.3.1).
- The difference between RHEL/CentOS might be smaller than what you expected. RH sponsors CentOS.

**Comment by snnn** [comment]
You may report this issue to Nvidia or Red Hat. It's not an onnxruntime issue.
