### ISSUE TITLE
Faster way to get MKL

### ISSUE THREAD

**Issue by xkszltl** [microsoft/onnxruntime#662]
Currently MKLML is downloaded from github release (backed by AWS S3) every time we rebuild.
This is very time consuming in some case, especially when build from China where S3 is very slow and unreliable.

Besides, you guys may want to update your hard-coded MKLML version to `2019.0.3.20190220`.

**Describe the solution you'd like**

Support full MKL and get it from local.

**Describe alternatives you've considered**

Allow to use pre-installed mklml.
This may not be a good idea on most Linux where everything goes to `/usr{,/local}/include`.

**Comment by xkszltl** [comment]
IMHO build time network access is generally a bad idea.

**Comment by snnn** [comment]
You can preinstall MKL, and avoiding use MKLML.

**Comment by snnn** [comment]
> IMHO build time network access is generally a bad idea.

I agree.

**Comment by xkszltl** [comment]
But how to use MKL?
I thought there's only MKLML code path in CMake files.

**Comment by snnn** [comment]
Hi @jywu-msft,

What do you think?

**Comment by jywu-msft** [comment]
> Hi @jywu-msft,
> What do you think?

it should be possible to link against the full MKL (but what is the use case? if you just want to use gemm, I think MKLML is sufficient)

to link against full MKL, I think we need to use the MKLDNN_USE_MKL option and set it to either ML (for MKLML) or FULL to link against full MKL. and would also need to set MKLROOT environment variable to path where MKL is installed.

see: https://github.com/intel/mkl-dnn/blob/master/cmake/options.cmake#L66

**Comment by jywu-msft** [comment]
here's the logic https://github.com/intel/mkl-dnn/blob/master/cmake/MKL.cmake#L91
it's using to find full MKL or MKLML

**Comment by xkszltl** [comment]
@jywu-msft 
There're 2 use cases:
  1. When user already have full MKL as part of its dependency
  2. Avoid re-download MKLML every time.

I know how to let MKLDNN uses full MKL.
I'm talking about the case when `-Donnxruntime_USE_MKLML=ON -Donnxruntime_USE_MKLDNN=OFF`.

**Comment by jywu-msft** [comment]
@xkszltl 
Do you have a specific use case for using full MKL vs MKLML ? 
MKLML is already stripped down version of MKL yet is still quite large at 150MB.  
onnxruntime currently can only take advantage of cblas_sgemm from MKLML/MKL 
In the longer term, MKLDNN's gemm should reach performance parity with MKL cblas_sgemm 
Unless we have specific use of other functionality in MKL/MKLML, it seems better to use MKLDNN
(btw, the DNN functionality in the full MKL package is being deprecated. it is advised to use MKLDNN for DNN features)

Re: avoiding re-download MKLML,  maybe you can leverage intel's script for downloading MKLML instead 
see: https://github.com/intel/caffe/blob/master/external/mkl/prepare_mkl.sh

**Comment by xkszltl** [comment]
Correct me if I'm wrong but I think the download is triggered by https://github.com/Microsoft/onnxruntime/blob/a3499083dae79c5737c2d31d9512068f89cb48e1/cmake/external/mkldnn.cmake#L40
And there's no way to word around it without code modification.

**Comment by jywu-msft** [comment]
yes, there needs to be code modification.

**Comment by xkszltl** [comment]
It'll be great if there's a similar mechanism like MKLDNN_USE_MKL for onnxruntime.

**Comment by xkszltl** [comment]
FYI here's also a scenario where mkl can be useful: #530

**Comment by faxu** [comment]
No intention to support.
