### ISSUE TITLE
Android arm64-v8a static libraries 1.11 GB in size

### ISSUE THREAD

**Issue by vltmrkls** [microsoft/onnxruntime#6620]
**cross compiled static libraries for Android are huge -> 1.11GB. (iOS libraries are only 100MB)**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15
- ONNX Runtime installed from (source or binary): source 
- ONNX Runtime version: 1.6.0
- Python version: Python 3.7.6
- GCC/Compiler version (if compiling from source): Apple clang version 11.0.3 (clang-1103.0.32.62)
- GPU model and memory:

**To Reproduce**
- compile for android platform: ./build.sh --config Release --android --android_sdk_path ~/Library/Android/sdk --android_ndk_path ~/Library/Android/sdk/ndk/21.3.6528147 --android_abi armeabi-v7a --android_api 21

**Expected behavior**
static libraries should have a reasonable size when compiled with config release.

**Additional context**
I also tried to compile with -config MinSizeRel --minimal_build --disable_ml_ops --disable_exceptions but the size is still kinda big with about 600MB. Also my model doesn't load anymore with --minimal_build (terminating with uncaught exception of type Ort::Exception: ONNX format model is not supported in this build.)

**Comment by gwang-msft** [comment]
The size of a static library is irrelevant since it isn't a part of an app. When the library gets linked into a shared library or executable, ndk-build runs strip on the output which removes all the debug info.

For your onnx model not loading if onnx runtime is built with `--minimal_build` option, the reason is we only support .ort format in onnx runtime minimal build.
For detail about how to build for Mobile platform and convert your models to .ort format, please see, https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_for_Mobile_Platforms.md

**Comment by mlostekk** [comment]
> The size of a static library is irrelevant though since it isn't a part of an app. When the library gets linked into a shared library or executable, `ndk-build` runs `strip` on the output which removes all the debug info.
> 
> _Originally posted by @DanAlbert in [android/ndk#169 (comment)](https://github.com/android/ndk/issues/169#issuecomment-234482246)_
> 
> For your onnx model not loading if onnx runtime is built with `--minimal_build` option, the reason is we only support .ort format in onnx runtime minimal build.
> For detail about how to build for mobile platform and convert your models to .ort format, please see, https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_for_Mobile_Platforms.md

maybe irrelevant for the source code repository, but its not really irrelevant if you want to provide them in a precompiled way for other repositories. then thinking of CI, git clone times, lfs quota... 

Is there no way to strip it down? I never saw binaries of over 500MB in size.

**Comment by vltmrkls** [comment]
i solved the issue by editing the CMakeLists.txt

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g0")

**Comment by DefTruth** [comment]
> https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_for_Mobile_Platforms.md

solved my problem

**Comment by mlostekk** [comment]
> > https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_for_Mobile_Platforms.md
> 
> solved my problem

The page is not available @DefTruth

**Comment by thelou1s** [comment]
Could you explain what helped you resolve this ? thx @DefTruth
