### ISSUE TITLE
Nuget "Part URI cannot start with two forward slashes."

### ISSUE THREAD

**Issue by dashesy** [Microsoft/onnxruntime#664]
**Describe the bug**
Added Microsoft.ML.OnnxRuntime to the nuget packages

> Part URI cannot start with two forward slashes.

and

> An error occurred while retrieving package metadata for 'Microsoft.ML.OnnxRuntime.0.3.0' from source 'D:\development\EntityRecognition\packages'.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): binary nuget.org
- ONNX Runtime version: 0.3.0

**To Reproduce**
Added Microsoft.ML.OnnxRuntime to the nuget packages, now get this error and cannot list installed nugets

**Additional context**
[This issue](https://github.com/aspnet/AspNetCore/issues/5798) seems related

**Comment by dashesy** [comment]
This is in XML in nuget, may be related

> <Override PartName="//LICENSE" ContentType="application/octet" />

**Comment by jignparm** [comment]
@dashesy, the PR below should resolve the double slashes in the [Content_Types].xml file within the NuGet package. 

https://github.com/Microsoft/onnxruntime/pull/669.

**Comment by dashesy** [comment]
@jignparm thanks. Is there any pre-release package I can try?

**Comment by jignparm** [comment]
@dashesy, I'll follow up offline.

**Comment by dashesy** [comment]
I tried the `dev` nuget and the issue is now resolved, thanks. I also had to remove the 0.3.0 from `packages` directory, to get rid of the error: it seems VS looks at all the packages trying to read metadata and if it cannot read metadata from an older one does not ignore it!

**Comment by jignparm** [comment]
Thanks for confirming it's working after cleaning up the NuGet cache -- looks like stale packages can still have impact.
