### ISSUE TITLE
Java runtime request: Add method that returns underlying map for OrtSession.Result

### ISSUE THREAD

**Issue by ag-tcm** [microsoft/onnxruntime#6655]
**Is your feature request related to a problem? Please describe.**
This is specific to the Java ONNX runtime.
I have two models built with ONNX, model A and model B. I use the ONNX Runtime Java API to load these models and make inferences with them. The workflow is that I need to compute a prediction with model A and then feed the result from model A into model B. When I call resultFromA = A.run(inputs) the API returns a Result. Ideally I'd like to take that result and call B.run(resultFromA) but run only accepts Map<String, OnnxTensor> inputs. Do I really have to iterate over resultFromA and put its contents into a new Map? Or is it possible to add a method in Result that will return a map that I can use to call run on model B?

**System information**
- ONNX Runtime version (you are using):
1.6.0

**Describe the solution you'd like**
Add a method to Result that returns a map like Map<String, OnnxTensor>. Result already has an underlying map so I think you can do this easily.

**Describe alternatives you've considered**
The alternative is to rebuild the map using the available methods in Result like so:
    Map<String, OnnxTensor> modelAMap = new HashMap<String, OnnxTensor>();
    modelAResults.forEach(e -> modelAMap.put(e.getKey(), (OnnxTensor) e.getValue()));

**Additional context**
This request is related to SO question here: [How to most efficiently feed one ONNX model's output into another in java?](https://stackoverflow.com/questions/66073055/how-to-most-efficiently-feed-one-onnx-models-output-into-another-in-java?noredirect=1#comment116959024_66073055)

**Comment by Craigacp** [comment]
It was designed this way to control the lifetime of the output tensors. It intentionally doesn't implement Map because Map has a lot of extra methods and usually implies mutation.

Does model B's inputs have the same names as the outputs of model A?

As to the StackOverflow question, the efficiency isn't really relevant as the extra hash map will be lost in the noise compared to the cost of actually running inference on anything.

**Comment by ag-tcm** [comment]
I had a hunch that it was designed this way to not expose the map because of the AutoCloseable nature of Result.

Yes, in this case model B's input names are the same as model A's output names.

Regardless of code efficiency, the creation of the additional hash map is an extra step that I was hoping wouldn't be necessary.

**Comment by Craigacp** [comment]
Yeah it's to ensure all the views on the outputs are autocloseable so your IDE/linter will remind you to close them.

**Comment by ag-tcm** [comment]
Why did you ask about the inputs/outputs for the models? Is there a better
solution for this specific case?

**Comment by Craigacp** [comment]
Well you could use the ONNX python library to stitch the two models together and allow ORT (or the other onnx optimisers) to optimise the whole model jointly.

**Comment by ag-tcm** [comment]
Thanks for the suggestion, I'll see if I can make that work.
