### ISSUE TITLE
CUDA / TensorRT - Exception during initialization: std::bad_alloc

### ISSUE THREAD

**Issue by xDuck** [microsoft/onnxruntime#6670]
**Describe the bug**
Running onnxruntime w/ TensorRT built from source (master branch at the time of this post). 

My model runs fine on the CPU but when I try to move it to the GPU I get the following error while it is loading the model:

```
2021-02-12 22:13:52.008378106 [E:onnxruntime:, inference_session.cc:1290 operator()] Exception during initialization: std::bad_alloc
terminate called after throwing an instance of 'Ort::Exception'
  what():  Exception during initialization: std::bad_alloc
```

The only change I made was to add the relevant headers and add these few lines to start using TensorRT:

```
    // GPU Settings
    int device_id = 0;

    // Integrate CUDA / TensorRT
    Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_Tensorrt(session_options, device_id));
    Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, device_id));
```

The GPU memory gets to about 240MB of usage before the bad_alloc error happens. I am running a 2070 Super w/ 8GB GPU Memory.

The code I am using is a modified version of this sample, the only changes being to load my model (changing input & output sizes): https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp 

The Dockerfile I used to build the environment was, again modified to build the C++ shared libraries instead of the python wheel: https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.tensorrt

UPDATE - After running the model through `symbolic_shape_infer.py` with `--auto-merge` I now get a different error:

```
2021-02-15 16:21:45.393210344 [E:onnxruntime:, inference_session.cc:1290 operator()] Exception during initialization: Failed to read INT8 calibration table INT8_calibration_table
terminate called after throwing an instance of 'Ort::Exception'
  what():  Exception during initialization: Failed to read INT8 calibration table INT8_calibration_table
```

**Comment by mrljwlm** [comment]
have you solve this problem? @xDuck
