### ISSUE TITLE
Lifetime of the strings inside OrtOpenVINOProviderOptions

### ISSUE THREAD

**Issue by Craigacp** [microsoft/onnxruntime#6676]
The new `OrtOpenVINOProviderOptions` struct has a couple of strings inside it, `device_id` and `device_type`. What's the expected lifetime of those strings? Similarly how long does the struct itself need to live? Is there a reference held to it after the `ORT_API2_STATUS(SessionOptionsAppendExecutionProvider_OpenVINO, _In_ OrtSessionOptions* options, _In_ const OrtOpenVINOProviderOptions* provider_options)` call returns?

My reading of the C++ code underlying the create call is that the pointers are copied rather than the memory they point to, meaning the char arrays need to outlive the provider, in which case I'll need to add some tracking code to the Java API to free them whenever anyone adds an OpenVINO provider (which will be a pain). In python it looks like it pulls out the C string, but I don't know if Python pins memory to make that ok.

In general is there any guidance on the lifetime of memory passed into provider factories? The CUDA and TensorRT ones seem to accept function pointers, so that seems less of an issue.

**Comment by Craigacp** [comment]
@yuslepukhin

**Comment by faxu** [comment]
CC @jywu-msft

**Comment by pranavsharma** [comment]
device_type and device_id are passed to std::string constructor that makes a copy of the char array supplied by the user. The char arrays don't have to outlive the provider. If there is any expectation on the lifetime from the user, it should be mentioned explicitly in the API header/documentation.

**Comment by Craigacp** [comment]
Ok, thanks. I'll add support for OrtOpenVINOProviderOptions and the CUDA one when I get chance in a couple of weeks.
