### ISSUE TITLE
Error in Nonmaxsupression

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [microsoft/onnxruntime#6680]
**Describe the bug**
I have trained custom object detection model using YOLOV3, converted from savedmodel format to onnx and tried to run the inference using onnxruntime. Am getting the below error
**Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running NonMaxSuppression node. Name:'NonMaxSuppression__1600' Status Message: Not satisfied: ret.IsOK()
non_max_suppression.cc:117 ComputeNot satisfied: boxes_dims[1] == scores_dims[2]
non_max_suppression.cc:84 PrepareComputeboxes and scores should have same spatial_dimension.**

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): from binary
- ONNX Runtime version:1.6.0
- Python version:3.8.5
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11.1 / 8
- GPU model and memory: 3090

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**rsess = ort.InferenceSession(reg_onnx_path) # my onnx model
rin_name = rsess.get_inputs()[0].name
rin_shape = rsess.get_inputs()[0].shape
print(rin_name, rin_shape)
print(rsess.get_outputs()[0].name, rsess.get_outputs()[1].name, rsess.get_outputs()[2].name)

outputs = ["Identity:0", "Identity_1:0", "Identity_2:0"]#, "detection_boxes:0", "detection_scores:0", "detection_classes:0"]
result = rsess.run(outputs, {rin_name: image_data})**

**Expected behavior**
should return the predictions from onnx model

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by hariharans29** [comment]
This error states that an assert is failing in ORT that si checked before the execution of `NonMaxSuppression`. 

Please check the documentation here - https://github.com/onnx/onnx/blob/master/docs/Operators.md#NonMaxSuppression. For the inputs - `boxes` and `scores`, the second and third shape dimension values must be the same (designated as `spatial_dimension`). In your model's case, it is not the same.

Could you check if the conversion to onnx has been successful ? If we get incorrect number of boxes and mis-matching number of scores, this points to something going wrong upstream to the node...

**Comment by VeeranjaneyuluToka** [comment]
Hi, Thanks for your reply!

I could solve the above issue, actually there was an issue in tensorflow implementation itselt. After i fixed the issue in tf and convert to onnx, it was working fine. But i am getting class names wrong? any suggestions on that? I have raised an issue on that in onnx as well https://github.com/onnx/tensorflow-onnx/issues/1341.

**Comment by hariharans29** [comment]
You mean - ORT's results don't match with tf's results ? 

In  almost every such case, this has been down to incorrect conversion. Very rarely, we do uncover a bug or two causing the diffs. Usually, I run the model using CPU and CUDA and if both runs produce same (although incorrect when compared with the base framework), the chances are the data mismatch is because of conversion related problems. If CPU and CUDA give differing results, we would have to investigate as it is probably an issue in one of ORT's kernels...

**Comment by VeeranjaneyuluToka** [comment]
Thanks for your reply again!
I have had a relook into my inference implementation and looks like there is some issue in preprocessing step because of which my results differs. I can confirm that my onnx model is as good as tf model. so closing this issue. Thanks again!.

**Comment by KangolHsu** [comment]
same error when converting fcos model.  
convert onnx model succeed, onnxruntime c++ running error:


2021-04-12 18:04:44.7129516 [E:onnxruntime:, sequential_executor.cc:339 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running NonMaxSuppression node. Name:'NonMaxSuppression_1603' Status Message: D:\3rdparty\onnxruntime\onnxruntime\core\framework\bfc_arena.cc:305 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 8539186688

Non-zero status code returned while running NonMaxSuppression node. Name:'NonMaxSuppression_1603' Status Message: D:\3rdparty\onnxruntime\onnxruntime\core\framework\bfc_arena.cc:305 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 8539186688

**Comment by KangolHsu** [comment]
Onnxruntime c++ inference

retinanet_r50_fpn_1x_coco_20200130-c2398f9e.onnx

CPU model works fine。

Error appear in CUDA ，TensorRT  model，


2021-04-12 18:04:44.7129516 [E:onnxruntime:, sequential_executor.cc:339 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running NonMaxSuppression node. Name:'NonMaxSuppression_1603' Status Message: D:\3rdparty\onnxruntime\onnxruntime\core\framework\bfc_arena.cc:305 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 8539186688

Non-zero status code returned while running NonMaxSuppression node. Name:'NonMaxSuppression_1603' Status Message: D:\3rdparty\onnxruntime\onnxruntime\core\framework\bfc_arena.cc:305 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 8539186688

**Comment by geometrikal** [comment]
Same error here with faster RCNN model trained using TF2 obj det api and converted to ONNX with opset 13

**Comment by daoxian** [comment]
> Non-zero status code returned while running NonMaxSuppression node. Name:'NonMaxSuppression_1603' Status Message: D:\3rdparty\onnxruntime\onnxruntime\core\framework\bfc_arena.cc:305 onnxruntime::BFCArena::AllocateRawInternal Failed to allocate memory for requested buffer of size 8539186688

Your GPU Memory is too small...  Check it by nvidia-smi !
