### ISSUE TITLE
Run ML model on GPU of an Android run system

### ISSUE THREAD

**Issue by besartgrabanica** [microsoft/onnxruntime#6694]
Hello,

I would like to know whether ONNX Runtime has GPU support in Android systems. In my particular example, I would need to run the inference of a PyTorch based Deep Learning model which utilizes transformers on the GPU of an Android system.

Thanks in advance!

**Comment by gwang-msft** [comment]
We have an NNAPI execution provider which will use GPU/NPU for model execution.
Please see https://www.onnxruntime.ai/docs/reference/execution-providers/NNAPI-ExecutionProvider.html

**Comment by deephudka005** [comment]
Can you provide some example code to run inference of any model on GPU? I tried using session options and adding NNAPI to it but I am not aware if my method is correct or not.
```
val options = OrtSession.SessionOptions()
options.addNnapi()
ortSession = ortEnv?.createSession(onnxModel, options)
```

**Comment by Uwenisme** [comment]
> assignment
Do you mean we do not need to select specific device(cpu, gpu or npu) and NNAPI EP can use all of them automatically?

**Comment by Uwenisme** [comment]
> 
Do you mean we do not need to select specific device(cpu, gpu or npu) and NNAPI EP can use all of them automatically?

**Comment by Uwenisme** [comment]
> Contributor
Do you mean we do not need to select specific device(cpu, gpu or npu) and NNAPI EP can use all of them automatically?

**Comment by Uwenisme** [comment]
> Contributor
Do you mean we do not need to select specific device(cpu, gpu or npu) and NNAPI EP can use all of them automatically?
