### ISSUE TITLE
Dynamic quantization slow on non-VNNI CPUs

### ISSUE THREAD

**Issue by yaysummeriscoming** [microsoft/onnxruntime#6695]
**Describe the bug**
Transformer dynamic quantization doesn't seem to offer any speed improvement on non-Cascade Lake VNNI CPUs:

FP32 command:
python -m onnxruntime_tools.transformers.benchmark -m bert-base-uncased -e onnxruntime -p fp32 -o -i 2 -t 100 -b 1 -s 128

INT8 command:
python -m onnxruntime_tools.transformers.benchmark -m bert-base-uncased -e onnxruntime -p int8 -o -i 2 -t 100 -b 1 -s 128

8 core Cascade Lake (GCP n2-standard-16)
fp32: 31.46
int8: 19.76

Ryzen 3700X:
fp32: 38.05
int8: 35.08

I tested on a GCP N1 Skylake instance as well, so it's not related to AMD.

**Urgency**
Low

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.6.0
- Python version: 3.8

**Comment by yufenglee** [comment]
@yaysummeriscoming, it is expected to see a 10%-20% performance gain for sequence length 128 on the non-vnni machine. You can see larger performance gain for smaller sequence on the non-vnni machine.

**Comment by yaysummeriscoming** [comment]
@yufenglee thanks I did some tests at sequence length 32 and that checks out. Are there other quantization modes, such as static quantization that will perform better?
