### ISSUE TITLE
ONNX runtime session can't load model with external data outside of current folder.

### ISSUE THREAD

**Issue by pmarcinkiewicz** [microsoft/onnxruntime#6696]
ONNX runtime session can't load model with external data stored in non-current folder.

**Urgency**
Many large models like BART, DLRM require external data because models are bigger than 2GB.

**System information**
- Linux Ubuntu 18.04
- ONNX Runtime installed from binary
- ONNX Runtime version: 1.5.2
- Python version: 3.8.5
- CUDA/cuDNN version: 11.2
- GPU model and memory: GA100

**To Reproduce**

```
mkdir t

#run Python script:

import torch
import torch.nn as nn
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc = nn.Linear(1024, 1024 * 1024)
    def forward(self, x):
        x = self.fc(x)
        return x
model = Net()
input = torch.randn(1024, requires_grad=True)
with torch.no_grad():
    torch.onnx.export(model, (input, ), './t/net.onnx', do_constant_folding=True, opset_version=12,  use_external_data_format=True, enable_onnx_checker=True)
import onnx
import onnxruntime
m = onnx.load("./t/net.onnx", load_external_data=False)
model_payload = m.SerializeToString()
onnxruntime.InferenceSession(model_payload)

```

**Expected behavior**
A model is loaded for inference with external data.

**Screenshots**

```
In [5]: onnxruntime.InferenceSession(model_payload)
---------------------------------------------------------------------------
InvalidArgument                           Traceback (most recent call last)
<ipython-input-5-724a0aa2e95a> in <module>
----> 1 onnxruntime.InferenceSession(model_payload)

/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/session.py in __init__(self, path_or_bytes, sess_options, providers, provider_options)
    193         self._read_config_from_model = os.environ.get('ORT_LOAD_CONFIG_FROM_MODEL') == '1'
    194
--> 195         self._create_inference_session(providers, provider_options)
    196
    197     def _create_inference_session(self, providers, provider_options):

/opt/conda/lib/python3.8/site-packages/onnxruntime/capi/session.py in _create_inference_session(self, providers, provider_options)
    203
    204         # initialize the C++ InferenceSession
--> 205         sess.initialize_session(providers or [], provider_options or [])
    206
    207         self._sess = sess

InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Deserialize tensor fc.bias.1 failed.Invalid fd was supplied: -1
```

**Additional context**

The same code works, when model is stored in current folder not in subfolder t.

**Comment by snnn** [comment]
If it works, would it be a big security risk? What if your http server can read any file in your system?

**Comment by piotrm-nvidia** [comment]
I can load t/model.onnx so it is already security risk here. I expected that, when I pass folder to model, the same path should also be used to load external tensors.

**Comment by snnn** [comment]
We won't change our code because ONNX standard requires it. See: https://github.com/onnx/onnx/blob/master/docs/ExternalData.md  "Up-directory path components such as .. are disallowed and should be stripped when parsing."  I implemented the onnx runtime code but I wasn't involved in making the standard.  If it bothers you much,  please raise the issue to https://github.com/onnx/onnx .

**Comment by liqunfu** [comment]
> I think ONNX standard requires it. See: https://github.com/onnx/onnx/blob/master/docs/ExternalData.md "Up-directory path components such as .. are disallowed and should be stripped when parsing." If it bothers you much, please raise the issue to https://github.com/onnx/onnx . We are just an implementation.

Since release 1.13.0, model and external tensor data can be at different location. So the issue reported here is solved.
