### ISSUE TITLE
NodeJS samples links to 404

### ISSUE THREAD

**Issue by biro-mark** [microsoft/onnxruntime#6698]
**Describe the bug**
https://github.com/microsoft/onnxruntime/tree/master/nodejs says "Refer to [Node.js samples](https://github.com/microsoft/onnxruntime/blob/master/samples/README.md#Nodejs) for samples and tutorials." but the link is dead.

**Urgency**
This is making it difficult to get started with nodejs bindings.

**System information**
n/a 

**To Reproduce**
Go to https://github.com/microsoft/onnxruntime/tree/master/nodejs 
Where it says says "Refer to [Node.js samples](https://github.com/microsoft/onnxruntime/blob/master/samples/README.md#Nodejs) for samples and tutorials." click the link. It goes to a 404 page.

**Expected behavior**
The link should go to a valid page giving samples and tutorials for the NodeJS bindings.

**Comment by biro-mark** [comment]
I found the page from a previous tag
https://github.com/microsoft/onnxruntime/tree/v1.6.0/samples/nodejs

**Comment by snnn** [comment]
@natke @fs-eire  Could you please help?
