### ISSUE TITLE
static quantization issue with Matmul parameters

### ISSUE THREAD

**Issue by ocaff1** [microsoft/onnxruntime#6702]
Hi,

I try static quantization on a basic model with several depthwise layers followed by a final fully-connected layer with 12 outputs.
When calling **quantize_static** method I have this issue regarding the output layer (FC) I can not solved:
_"ValueError: Quantization parameters are not specified for param 96.In static mode quantization params for inputs and outputs of nodes to be quantized are required."_

My model is composed as followed (Netron screenshot)
![Capture](https://user-images.githubusercontent.com/58599750/108038740-7c8e1600-703b-11eb-91db-2e88b857b57c.PNG)

Quantization function call:
_quantize_static(model_path, 
                    quantized_path, 
                    calib_dr, 
                    weight_type=QuantType.QInt8, 
                    activation_type=QuantType.QUInt8)_

It appears that flatten output/Matmul input ['96'] has no quantization parameters computed (scale or zero-point).
Is there any limitation with the sequence flatten/matmul?

Thank you for your help,
Olivier

**System information**
- Linux Ubuntu 18.04:
- torch version: 1.7.1
- onnx version: 1.8.1
- onnxruntime version: 1.6.0
- Python 3.8.5 
- work on CPU

**Comment by ocaff1** [comment]
Hi,

The issue comes from the confusion between Gemm and Matmul. Seen as two different operators.
onnxruntime 1.6.0 does not support Gemm but I see that in currrent dev, an optimisation is added which replaces 'Gemm' by 'MatMul' operator. I guess it will be available in next stable release.

Is there any rule/reason for using MatMul instead of Gemm?

Olivier

**Comment by yufenglee** [comment]
@ocaff1, MatMul supports N-D matrix multiplication while Gemm only supports 2-D in ONNX: https://github.com/onnx/onnx/blob/master/docs/Operators.md#gemm. Gemm supports transpose and accumulation mode while MatMul doesn't.

**Comment by ocaff1** [comment]
Thank you for the answer.
Olivier
