### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by dmedine** [microsoft/onnxruntime#6710]
`python research\slim\export_inference_graph.py --model_name=inception_v4 --output_file=grpah.pb`

should be 
`
python research\slim\export_inference_graph.py --model_name=inception_v4 --output_file=graph.pb`

**Comment by snnn** [comment]
My bad :-(

**Comment by dmedine** [comment]
No worries! Sorry to push the problem onto you, but it is easier for me than making a fork and a PR ;-)
