### ISSUE TITLE
onnxruntime c++ api for getting non Tensor output

### ISSUE THREAD

**Issue by gilboash** [microsoft/onnxruntime#6724]
onnxruntime c++ throws the following error when trying to access outputs of Session.Run, any idea how to access this output?

float* floatarr = output_tensors.front().GetTensorMutableData<float>();

```
C++ exception with description "/home/data/onnxruntime/1.5.3.gm01/qnx.7.0.0.ES5.gnu/profile/build/8dc6da30eeaeb70b60fac4797060718aef04d8a8/source_subfolder/include/onnxruntime/core/framework/ml_value.h:96 T* OrtValue::GetMutable() [with T = onnxruntime::Tensor] IsTensor() was false. Trying to get a Tensor, but got: seq(map(int64,tensor(float)))
" thrown in the test body.


```

Linux C++ onnxruntime library

**Comment by hariharans29** [comment]
What you have is not a tensor but (as the error message says) a sequence of map<int64, float>. So you can't use GetTensorMutableData() against the object you have.

See if code here helps you. It deals with `seq(map(string, float))`. But you should be able to adapt from there: https://github.com/microsoft/onnxruntime/blob/9e67b88c8312e124c3127c6ee0833c110a18fd5a/onnxruntime/test/shared_lib/test_nontensor_types.cc#L97

**Comment by gilboash** [comment]
> What you have is not a tensor but (as the error message says) a sequence of map<int64, float>. So you can't use GetTensorMutableData() against the object you have.
> 
> See if code here helps you. It deals with `seq(map(string, float))`. But you should be able to adapt from there:
> 
> https://github.com/microsoft/onnxruntime/blob/9e67b88c8312e124c3127c6ee0833c110a18fd5a/onnxruntime/test/shared_lib/test_nontensor_types.cc#L97

works! thanks
