### ISSUE TITLE
Support different input types

### ISSUE THREAD

**Issue by dashesy** [microsoft/onnxruntime#673]
**Is your feature request related to a problem? Please describe.**
In order to use the inference session I need to use `ReadOnlySpan` for inputs, but it seems [this type](
https://stackoverflow.com/questions/51942986/types-with-embedded-references-are-not-supported) is not supported in VS2015. We just need to pass an array of float but Tensors rely on Span.

**System information**
- ONNX Runtime version (you are using): 0.3.0

**Describe the solution you'd like**
Support Visual Studio 2015 
1. alternative to Tensor as input
2. accept float[] directly with a dimensions
3. accept Bitmap (to avoid one extra marshaling) (add utility to convert Bitmap to Tensor?)

**Describe alternatives you've considered**

```c#
var t = System.Numerics.Tensors.ArrayTensorExtensions.ToTensor(array).Reshape(new[] { 1, 3, image.Height, image.Width})
```

**Additional context**
Our current code is based on VS2015
More [information](https://devblogs.microsoft.com/dotnet/welcome-to-c-7-2-and-span/). 
[This issue](https://github.com/Microsoft/onnxruntime/issues/540) is related

**Comment by jignparm** [comment]
@dashesy  -- from the link above, it seems like upgrading visual studio to 2017 15.5,  with support for C# 7.2 should solve the error above (you can still target older versions of .NET Core and Framework). Is that possibility?

**Comment by dashesy** [comment]
I can use it in VS2015 too. It would be nice to have utility functions to convert usual C# types to tensor though. I use unsafe code to convert Bitmap to tensor of bytes, if it was part of a utility in onnxruntime that would have been better. Also if we could use the underlying buffer of the bitmap to avoid copying that would have been even better.

**Comment by jignparm** [comment]
Given a float[], it should be straightforward to create a Tensor(). 

Bitmap is an implementation of  System.Drawing.Image class. From a design perspective, implementing a ToTensor() method in the Bitmap class seems like a better route, because the memory layout  (i.e. channels-first/last, ordering of channels, resizing of image etc.) is better controlled from the bitmap class, than by a converter/constructor function in OnnxRuntime.

Are there any particular blockers (or is this mostly for convenience)?

**Comment by dashesy** [comment]
No blockers, thus a feature request not an issue. It is nice to have easy ways to consume, like as easy as the pip version.

**Comment by jignparm** [comment]
Closing this out -- taking in float[] and bitmap structs will probably cause confusion, especially  since Onnxruntime is heavily tensor-centric.
