### ISSUE TITLE
install onnxruntime  compile element_wise_ops.cc failed,error code:C2514

### ISSUE THREAD

**Issue by chinafzc** [microsoft/onnxruntime#6752]
**Describe the bug**
 Open Developer Command Prompt for Visual Studio 2017,  build command:
`build.bat --config RelWithDebInfo --build_shared_lib --parallel `
But failed.
onnxruntime\core\providers\cpu\math\element_wise_ops.cc(997): error C2514: “Eigen::Map<const E
igen::Matrix<T,-1,1,,-1,1>,0,Eigen::Stride<0,0>>”  Classes have no constructors

I guess that the eigen version do not fit.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10
- ONNX Runtime installed from (source or binary): source 
- ONNX Runtime version:
- Python version: 3.8.5
- Visual Studio version (if applicable): 2017
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by yuslepukhin** [comment]
What release are you trying to build or what commit? The issue is likely related to VS 2017 version.

**Comment by chinafzc** [comment]
> What release are you trying to build or what commit? The issue is likely related to VS 2017 version.

I am trying to build, but failed. Yes ,I build by VS 2017. Now, I am testing the version 1.6 dynamic library  you provided,  I wish I could compile it myself. Thanks for your reply!

**Comment by yellowYuga** [comment]
I also have this problem. But can compile it successfully by VS2019.

**Comment by ytaous** [comment]
please try vs2019, contribution on vs2017 build is also more than welcome, thx.
