### ISSUE TITLE
Quantizer does not correctly set QType in quantized_value_map for int8 input

### ISSUE THREAD

**Issue by pranav-prakash** [microsoft/onnxruntime#6759]
**Describe the bug**
In the quantizer, the `QuantizedValue` is constructed like

```
QuantizedValue(node.output[0], node.output[0] + "_quantized",
                                                quantized_input_value.scale_name, quantized_input_value.zp_name,
                                                QuantizedValueType.Input)
```

in most of the operators. However, this sets the `qType` to the default value of `uint8`, which may not actually match the quantized data type (if e.g. we set inputs to be quantized as `int8`). While this works fine if the inputs are going to be quantized to `uint8`, if the inputs are quantized to `int8` then this causes an obvious issue.

Even though I noticed that the quantizer does not officially support `int8` yet, this is a straightforward fix that will not break anything else; and with this change added, `int8` models can be quantized properly.

I submitted a PR for this a month or so back https://github.com/microsoft/onnxruntime/pull/6179/ but it seems to be stuck in review-limbo.

**Urgency**
Not urgent, but having this merged in would remove some of the discrepancy between our fork and upstream.

**Comment by KnightYao** [comment]
mark

**Comment by yufenglee** [comment]
@pranav-prakash , the qtype field in the QuantizedValue is not used in anywhere. It is redundant. Could you please update your PR to remove it?

**Comment by pranav-prakash** [comment]
@yufenglee Ah nice. I've updated the PR so that `qType` is removed from both QuantizedValue and QuantizedInitializer (it seems that `QuantizedInitializer` is itself not used anywhere, but than can be removed in a separate PR).
