### ISSUE TITLE
[ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node LinearRegressor:LinearRegressor(1)

### ISSUE THREAD

**Issue by dalavayi** [microsoft/onnxruntime#6769]
Hi all, getting this error when trying to inferance a linear regression model. PLease help me resolve this.

**Comment by snnn** [comment]
Please let us know the input types of the node.

**Comment by dalavayi** [comment]
Thank you for responding, i was working on wine quality detection use case, which has input features 
fixed acidity	volatile acidity	citric acid	residual sugar	chlorides	free sulfur dioxide	total sulfur dioxide	density	pH	sulphates	alcohol.
which are all float values, example:
0.0	0.0	0.146929	0.0	0.433214	0.0	0.0	0.0	0.0	0.003411	0.0. 

I converted the linear regression model into onnx using model_onx = skl2onnx.to_onnx(model, X) method with model as LinearRegressor and X is [[0.5        0.15135135 0.22891566 0.14877301 0.14836795 0.1953125
  0.29372937 0.18488529 0.33653846 0.29069767 0.27586207]]

when i am trying to inference it using 
onnx_model_str = model_onx.SerializeToString()
sess = rt.InferenceSession(onnx_model_str)

It is throwing this error when initialising the session:

NotImplemented                            Traceback (most recent call last)
<ipython-input-49-e7e300073eff> in <module>
      1 import onnxruntime as rt
      2 onnx_model_str = model_onx.SerializeToString()
----> 3 sess = rt.InferenceSession(onnx_model_str)
      4 input_name = sess.get_inputs()[0].name
      5 label_name = sess.get_outputs()[0].name

~\Anaconda3\envs\tf\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py in __init__(self, path_or_bytes, sess_options, providers, provider_options)
    204 
    205         try:
--> 206             self._create_inference_session(providers, provider_options)
    207         except RuntimeError:
    208             if self._enable_fallback:

~\Anaconda3\envs\tf\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py in _create_inference_session(self, providers, provider_options)
    229 
    230         # initialize the C++ InferenceSession
--> 231         sess.initialize_session(providers or [], provider_options or [])
    232 
    233         self._sess = sess

NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node LinearRegressor:LinearRegressor(1)

**Comment by yuslepukhin** [comment]
Would it be possible to share the model?

**Comment by dalavayi** [comment]
sure @yuslepukhin 
[wine_quality_model.zip](https://github.com/microsoft/onnxruntime/files/6040826/wine_quality_model.zip)

**Comment by snnn** [comment]
Hi @dalavayi 

I opened the model,
![image](https://user-images.githubusercontent.com/856316/112687017-14013880-8e34-11eb-9471-b06a9f7fa8d8.png)

It is because we only implemented it for float32, not float64. But your model needs float64.

See:
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/ml/linearregressor.cc#L16

If it bothers you, welcome to contribute. 

I'll close this issue for now.
