### ISSUE TITLE
How can I deploy, a model with ATen-based custom op, with c++ api

### ISSUE THREAD

**Issue by gsxab** [microsoft/onnxruntime#6779]
**Is your feature request related to a problem? Please describe.**

I'm trying to deploy a python model, namely [yolact++](https://github.com/dbolya/yolact), 
which includes a DCNv2 module from https://github.com/charlesshang/DCNv2.
This module was implemented with some ATen/THCuda c++ calls.
(BTW, I replaced it with a version from https://github.com/lbin/DCNv2 for later pytorch version.)

To export custom ops into models, I found some related topics:

Firstly, some online materials pointed out that they exported it and registered it with a static `symbolic` function, 
or a call to register_custom_op_symbolic , then they deployed them through ORT python api.
I tried both of them, the models exported appeared fine in Netron, despite including a DCNv2 op in it.
But when deploying models in c++ api, an exception occurred with following message:

```plain
terminated called after throwing an instance of 'Ort::Exception':
  what(): Load model from yolact_plus.onnx failed:Fatal error: DCNv2 is not a registered function/op
```

It seemed that registering in python was not enough for c++ api.

Secondly, I read articles at https://www.onnxruntime.ai/docs/how-to/add-custom-op.html and https://www.onnxruntime.ai/docs/how-to/export-pytorch-model.html#export-pytorch-model-with-custom-onnx-operators,
both of which required a new implementation.
I found that values should be attained from a `OrtKernelContent*` in forms of `T*`,
but I don't know how to migrate from ATen methods into an ORT-style implementation.

**System information**
- ONNX Runtime version (you are using): 1.6.0

**Describe the solution you'd like**
**Describe alternatives you've considered**

Maybe one of the following will help me out:
- a way to bridge from an ATen custom op to a c++ custom op.
- a way to register and use an ATen custom op in c++ api.
- an ORT-style c++ implementation for DCNv2.

**Additional context**
In case it should work and I might have made mistakes, please correct my steps.

**Comment by pranavsharma** [comment]
Did you take a look at onnxruntime\test\shared_lib\custom_op_utils.h? There are several examples of writing custom ops. onnxruntime\test\shared_lib\test_inference.cc shows how to register them. You should be able to wrap the ATen functionality in your custom op DLL and register it with ORT.

**Comment by mrljwlm** [comment]
hellow, i want to use yolact++ with onnxruntime too, have you solve you problem??

**Comment by gsxab** [comment]
@mrljwlm
Sorry that I am not working on it these days.

No attempt has been made yet, but I guess the following solution might work as keys to an implementation for the kernel of the customized op.
```c++
const OrtValue* input_##name = ort_.KernelContext_GetInput(context, /* order */);

// this should work for the scalars named xxx_h, xxx_w, and deformable_group
/*type*/ name;
cudaMemcpy(&name, ort_.GetTensorData</*type*/>(input_##name), sizeof(/*type*/), cudaMemcpyDeviceToHost);

// this might wrap the matrices into at::Tensor
at::Tensor ATen_##name = at::from_blob((void*) ort_.GetTensorData<float>(name), ort_.GetTensorTypeAndShape(name)));
```
Then pass them into the function `dcn_v2_forward`.

I haven't got enough spare time to check if this works yet, so maybe I should try it asap to put an end to this issue.

**Comment by gsxab** [comment]
@mrljwlm
I think I 've made it on CUDA. For my implementation, please see:
https://github.com/gsxab/YolactDeploymentORTCpp

**Comment by zengjie617789** [comment]
@gsxab thank you for your advice. I used the register code from you and it can export onnx model successfully but cannot use onnxruntime to inference. 
```
from torch.onnx import register_custom_op_symbolic
register_custom_op_symbolic('yolact::DCNv2', _DCNv2.symbolic, 11)
```

**Comment by gsxab** [comment]
@zengjie617789
I guess the importer/inference program also requires registering to recognize the user-defined operator. Please refer to my comments just above.
https://github.com/microsoft/onnxruntime/issues/6779#issuecomment-846331435
