### ISSUE TITLE
Add Transpose (Permute) operation

### ISSUE THREAD

**Issue by dashesy** [Microsoft/onnxruntime#678]
**Is your feature request related to a problem? Please describe.**
Converter converts but cannot load the session:

In Python the error is 

```text

RuntimeError: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Transpose(1)

```

**System information**
- ONNX Runtime version (you are using): 0.3.0

**Describe the solution you'd like**
Transpose (or Permute) operation

**Describe alternatives you've considered**
Slice + Concat

**Comment by snnn** [comment]
What's the opset version in your model?

**Comment by snnn** [comment]
Could you run this python script again your model?

```python
import onnx
import sys

from onnx import ModelProto
from google.protobuf import text_format

proto = ModelProto()

f = open(sys.argv[1], "rb")
proto.ParseFromString(f.read())
f.close()
print(proto.opset_import)
```

**Comment by dashesy** [comment]
In the converter Python?

```

Traceback (most recent call last):                                                                                                                                                                                                                                                File "/tmp/boz.py", line 9, in                                                                                                                                                                                                                                            f = open(sys.argv[1], "rb")                                                                                                                                                                                                                                                 IndexError: list index out of range

```

It is Python 2

**Comment by snnn** [comment]
Then, what's the input type of this node? I guess it's not float.

**Comment by dashesy** [comment]
Correct. It is a tensor of bytes. One of the operations is to cast to float. For optimization this is better because I won't have to cast and then marshal a bigger data from managed to un-managed code.

**Comment by snnn** [comment]
>  tensor of bytes
Tensor of what?

In the spec, this op supports:

 tensor(uint8), tensor(uint16), tensor(uint32), tensor(uint64), tensor(int8), tensor(int16), tensor(int32), tensor(int64), tensor(float16), tensor(float), tensor(double), tensor(string), tensor(bool), tensor(complex64), tensor(complex128)

But in our code, we didn't implement all of them. 

Please let me know more specifically, which one do you need? Is it  tensor(uint8) or tensor(int8)?

Thanks.

**Comment by yuslepukhin** [comment]
I think our Transpose should support all of them except complex types.

**Comment by snnn** [comment]
Hi @yuslepukhin , but your change is in master branch,  not 0.3.0 release.

**Comment by yuslepukhin** [comment]
@snnn Sure https://github.com/Microsoft/onnxruntime/commit/4c2b1c30186aa00edbd5fcdecef96cba5846b22f

**Comment by dashesy** [comment]
@snnn  We use `tensor(uint8)` i.e. `unsigned char`

**Comment by snnn** [comment]
Hi @dashesy, could you checkout the latest code and build onnxruntime from that, and try it again?

**Comment by yuslepukhin** [comment]
Yes, @dashesy , it would be a world for us!

**Comment by dashesy** [comment]
I compiled from source from master (wish cmake in apt was newer), and ran the network with `Transpose` on bytes, and it works! thanks for the quick fix.
What is the usual plan for the releases? I would like to use this as soon as it is released.

**Comment by snnn** [comment]
Hi @dashesy , glad to see your problem is solved.  I'll close this issue now. For release schedule, please check with Faith Xu.
