### ISSUE TITLE
Broken link in README.md for python quantization tools

### ISSUE THREAD

**Issue by mattroos** [microsoft/onnxruntime#6784]
In ```/onnxruntime/python/tools/quantization/README.md``` it states:

Note: In order to include all tensors from the model for better calibration, please run symbolic_shape_infer.py first. ([see here](https://github.com/microsoft/onnxruntime/blob/master/docs/execution_providers/TensorRT-ExecutionProvider.md#sample))

The link is broken. Does the referenced file, with the use of symbolic_shape_infer.py, still exist? Where is it?

**Comment by yufenglee** [comment]
@mattroos, we are refactoring docs. It is moved to here: https://www.onnxruntime.ai/docs/reference/execution-providers/TensorRT-ExecutionProvider.html but the quant readme is yet to update.

**Comment by natke** [comment]
Fixed by #12808
