### ISSUE TITLE
onnx runtime is running the whole graph

### ISSUE THREAD

**Issue by argman** [microsoft/onnxruntime#6790]
assume we have a input and two output (output_0, output_1) , they are all depend on the input, but we only need to get output_0, so when do running, onnx runtime will run both output_0 and output_1 then fetch out output_0 ? i think running the graph part of getting output_0 is enough ?

**Comment by hariharans29** [comment]
Dupe request of https://github.com/microsoft/onnxruntime/issues/3128. 

This is not supported in ORT yet.

**Comment by hariharans29** [comment]
Actually, the wiring for this seems to exist internally, but it is currently not exposed via the public APIs. Will prioritize this request.

**Comment by argman** [comment]
ok, so i need to modify the model first, is there any c++ library can load onnx model and modify the graph ?

**Comment by argman** [comment]
I use tensorflow at first, its a native feature in tensorflow. Now i am trying to use onnx to modify the model, but onnx does not provide a c++ API yet.

**Comment by askhade** [comment]
There is a newly added python api in onnx to extract a sub model based on inputs and outputs : https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#extracting-sub-model-with-inputs-outputs-tensor-names
Can you give this a try?

**Comment by argman** [comment]
> There is a newly added python api in onnx to extract a sub model based on inputs and outputs : https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#extracting-sub-model-with-inputs-outputs-tensor-names
> Can you give this a try?

I know that, but i am in a c++ environment

**Comment by argman** [comment]
I found its quite easy to follow the python code to implement a c++ version, I leave code below to see if any others meet the same problem

**Comment by argman** [comment]
I find its quite easy to get a c++ version following the python code, i create a gist [https://gist.github.com/argman/f378b5020e2ec7e2b621dcd1bf2f61f7](onnx_util) to help others
usage:
1. you should compile onnx's lib and dll to include onnx_pb.h
2. load model
   `onnx::ModelProto model;
   std::ifstream in(modelPath, std::ios_base::binary);
	model.ParseFromIstream(&in);
	in.close();`
3. extract sub model 
`onnx::ModelProto subModel = Extractor(model).ExtractModel({"input_name"}, {"output_name"});
	std::string subModelString = subModel.SerializeAsString();`
4. runing use onnx-runtime
`Ort::Session session(env, subModelString.data(), subModelString.size(), sessionOptions);`

**Comment by snnn** [comment]
Close as it is duplicated.

**Comment by david-macleod** [comment]
@hariharans29 has there been any progress on this? The route of extracting a subgraph manually has been covered here, but you seem to suggest that native support for partial graph execution may be possible soon?
