### ISSUE TITLE
Onnxruntime fails to load a session (Operator not implemented)

### ISSUE THREAD

**Issue by Nirmal-Neel** [microsoft/onnxruntime#6793]
Hi,

Due to some reason I am using and older version of onnxruntime (1.1.2), which I believe supports onnx version 1.6 and opset version 11. I have an alexnet model from onnx model zoo ([AlexNet-3](https://github.com/onnx/models/blob/master/vision/classification/alexnet/model/bvlcalexnet-3.onnx)) which has ir_version 3 and opset version also 3. But InferenceSession fails to create a session for this model with the following error - 
```python
---> 43         self._sess.load_model(providers)
     44 
     45         self._session_options = self._sess.session_options

NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Relu(1)
```
The error is not expected as Relu is there since opset version 1. My assumption is that when onnxruntime supports an opset_version, it will also support all the operators present in that opset and also from the older versions. In my case it should support both ReLu(1) and ReLu(6). Isn't it true that if runtime supports an opset version, it will support all earlier opset versions too?

**Comment by jcwchen** [comment]
Hi @Nirmal-Neel,
ONNXRuntime supports ONNX opsets all the way back **only to opset version 7**. You can check more info here: https://github.com/microsoft/onnxruntime/blob/master/docs/Versioning.md#backwards-compatibility. In your case, you might need to use model with opset_version>=7. For instance, [AlexNet-7](https://github.com/onnx/models/blob/master/vision/classification/alexnet/model/bvlcalexnet-7.onnx). Thanks.
