### ISSUE TITLE
running onnxruntime on alpine based image

### ISSUE THREAD

**Issue by laramume** [microsoft/onnxruntime#6800]
I tried to run onnxruntime c# library on alpine based image and it threw the following error

Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:RuntimeException] Exception caught: No error information
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.OrtEnv..ctor()
   at Microsoft.ML.OnnxRuntime.OrtEnv.<>c.<.cctor>b__11_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.ML.OnnxRuntime.OrtEnv.get_Handle()
   at Microsoft.ML.OnnxRuntime.InferenceSession.Init(String modelPath, SessionOptions options)
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath)

When I ran ldd libonnxruntime.so it gave the following error

/lib/ld-musl-x86_64.so.1 (0x7f2f2544a000)
        libdl.so.2 => /lib/ld-musl-x86_64.so.1 (0x7f2f2544a000)
        libpthread.so.0 => /lib/ld-musl-x86_64.so.1 (0x7f2f2544a000)
        librt.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f2f2544a000)
        libgomp.so.1 => /usr/lib/libgomp.so.1 (0x7f2f24753000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f2f245ba000)
        libm.so.6 => /lib/ld-musl-x86_64.so.1 (0x7f2f2544a000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f2f245a6000)
        libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7f2f2544a000)
        ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7f2f24573000)
Error relocating libonnxruntime.so: __sprintf_chk: symbol not found
Error relocating libonnxruntime.so: __snprintf_chk: symbol not found
Error relocating libonnxruntime.so: __vsnprintf_chk: symbol not found
Error relocating libonnxruntime.so: __memmove_chk: symbol not found
Error relocating libonnxruntime.so: __fprintf_chk: symbol not found
Error relocating libonnxruntime.so: __memcpy_chk: symbol not found

This is because alpine is based on musl instead of glibc. Does anyone have a solution on how to fix this? I even tried installing glibc but it was of no use

**Comment by snnn** [comment]
I think we may add a new build config just for alpine.

**Comment by snnn** [comment]
See #2909

**Comment by 29x10** [comment]
any update on this?

**Comment by leso-kn** [comment]
See [testing/onnxruntime](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/onnxruntime), testing/onnxruntime-dev and testing/py3-onnxruntime are now available.

**Comment by goldyfruit** [comment]
> See [testing/onnxruntime](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/onnxruntime), testing/onnxruntime-dev and testing/py3-onnxruntime are now available.

Doesn't seem to works with `x86_64`.
```
/ # apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing onnxruntime
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  so:libicuuc.so.72 (no such package):
    required by: re2-2023.03.01-r0[so:libicuuc.so.72]
```

**Comment by pablodz** [comment]
not working properly on amd64

**Comment by pablodz** [comment]
> See [testing/onnxruntime](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/onnxruntime), testing/onnxruntime-dev and testing/py3-onnxruntime are now available.

not working properly on amd64

**Comment by zazola** [comment]
Same issue on armv7

**Comment by bartosz-jarmuz** [comment]
Any updates here...?

**Comment by snnn** [comment]
Sorry, no progress on this task. I will close it now as nobody is working on this task. 
Meanwhile, we recommend using [Mariner2](https://github.com/microsoft/CBL-Mariner)

**Comment by ChristophHornung** [comment]
It works if you copy the files manually. This is what I do in my docker file (app is the folder with my c# app):

```docker
FROM base AS base2

RUN apk add --no-cache onnxruntime --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/ -X http://dl-cdn.alpinelinux.org/alpine/edge/community/ -X http://dl-cdn.alpinelinux.org/alpine/edge/main

FROM base2 AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN cp /usr/lib/libonnxruntime.so.1.16.1 /app/onnxruntime.so
```
