### ISSUE TITLE
tensorflow albert quantized

### ISSUE THREAD

**Issue by Zjq9409** [microsoft/onnxruntime#6823]
**Describe the bug**

firstly，I use transformers albert model to classify，like this：
`
pretrained = './albert_base' #使用small版本Albert
#tokenizer = BertTokenizer.from_pretrained(pretrained)
bert_config = AlbertConfig.from_json_file('./albert_base/config.json')
bert_config.output_hidden_states = True
bert_config.classifier_dropout_prob = 0.2
bert_config.num_labels = 2
#config = BertConfig.from_json_file('./albert_base/config.json')
model = TFAlbertModel.from_pretrained(pretrained)
print(model)
tokenizer = BertTokenizer('./albert_base/vocab.txt')
#tokenizer = BertWordPieceTokenizer("./albert_base/vocab.txt")
max_seq_len=128
sentences = "我爱北京天安门[SEP]天安门上太阳升。"
encode_results = tokenizer.encode_plus(sentences, add_special_tokens = True, # add [CLS], [SEP]
                                 max_length = max_seq_len, # max length of the text that can go to BERT
                                 pad_to_max_length = True, # add [PAD] tokens
                                 return_attention_mask = True, # add attention mask to not focus on pad tokens
                                 return_tensors="tf")
logits = model(encode_results)
weight = np.loadtxt("weight.txt")
bert_output = np.matmul(logits[1], weight)
print(bert_output)

from pathlib import Path
from transformers.convert_graph_to_onnx import convert
from transformers import *
@tf.function()
def my_predict(input_ids, token_type_ids, attention_mask):
   inputs = {
        'input_ids': input_ids,
        'token_type_ids': token_type_ids,
        'attention_mask': attention_mask
   }
   prediction = model(inputs)[1]
   return {"predict": prediction}

batch_size = 1
max_length = None
my_signatures = my_predict.get_concrete_function(
        input_ids=tf.TensorSpec([batch_size,max_length], dtype=tf.dtypes.int32, name="input_ids"),
        token_type_ids=tf.TensorSpec([batch_size,max_length], dtype=tf.dtypes.int32, name="token_type_ids"),
        attention_mask=tf.TensorSpec([batch_size,max_length], dtype=tf.dtypes.int32, name="attention_mask"),
)
print(my_signatures)
export_path="./segment_saved"
# Save the model.
tf.saved_model.save(
    model,
    export_dir=export_path,
    signatures=my_signatures
)
model.save_pretrained('./segment_model/')`

secondly，I use  ‘python -m tf2onnx.convert --saved-model segment_saved --output segment.onnx --opset 12’ to convert saved_model format to onnx.

Thirdly， I optimized and quantized segment.onnx by onnxruntime_tools:
`output_model_path="segment.onnx"
opt_options = BertOptimizationOptions('bert')
opt_options.enable_embed_layer_norm = False

opt_model = optimizer.optimize_model(
    output_model_path,
    'bert_keras',
    num_heads=12,
    hidden_size=768,
    optimization_options=opt_options)
opt_model.save_model_to_file('segment.opt.onnx')`

'import onnx
from onnxruntime.quantization import quantize_dynamic, QuantType

model_fp32 = "segment.opt.onnx"
model_quant = 'segment.quant.onnx'
quantized_model = quantize_dynamic(model_fp32, model_quant, weight_type=QuantType.QUInt8)'

Lastly, I use segemt.onnx, segment.opt.onnx, segment.quant.onnx to inference，but an error occured，
`sess_options = onnxruntime.SessionOptions()
output_model_path="segment.onnx"
session = onnxruntime.InferenceSession(output_model_path, sess_options, providers=['CPUExecutionProvider'])
model_inputs = encode_results
import numpy as np
batch_size=1
inputs_onnx = {k_+":0": np.repeat(v_, batch_size, axis=0) for k_, v_ in model_inputs.items()}
logits = session.run(None, inputs_onnx)
#logits = logits[1]
bert_output = np.matmul(logits,weight)
print(bert_output)
opt_model_path="segment.opt.onnx"
session = onnxruntime.InferenceSession(opt_model_path, sess_options, providers=['CPUExecutionProvider'])
model_inputs = encode_results
import numpy as np
batch_size=1
inputs_onnx = {k_+":0": np.repeat(v_, batch_size, axis=0) for k_, v_ in model_inputs.items()}
logits = session.run(None, inputs_onnx)
#logits = logits[1]
bert_output = np.matmul(logits,weight)
print(bert_output)
quantized_model_path = "segment.quant.onnx"
session = onnxruntime.InferenceSession(quantized_model_path, sess_options, providers=['CPUExecutionProvider'])
import numpy as np
batch_size=1
inputs_onnx = {k_+":0": np.repeat(v_, batch_size, axis=0) for k_, v_ in model_inputs.items()}
logits = session.run(None, inputs_onnx)
bert_output = np.matmul(logits,weight)
print(bert_output)`

The Error as follows，I think optimization step error， so onnxruntime dose not support albert model optimized？but I see official website support.
Traceback (most recent call last):
  File "test_segment.py", line 110, in <module>
    session = onnxruntime.InferenceSession(opt_model_path, sess_options, providers=['CPUExecutionProvider'])
  File "/usr/lib64/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 206, in __init__
    self._create_inference_session(providers, provider_options)
  File "/usr/lib64/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 226, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from segment.opt.onnx failed:This is an invalid model. Node (StatefulPartitionedCall/tf_albert_model/albert/encoder/albert_layer_groups_._0/albert_layers_._0/attention/add) input arg (StatefulPartitionedCall/tf_albert_model/albert/mul:0) does not have type information set by parent node.

**System information**
keras2onnx             1.7.0
onnx                   1.8.1
onnxconverter-common   1.7.0
onnxruntime            1.6.0
onnxruntime-tools      1.6.0
tf2onnx                1.8.3
transformers           3.0.2
tensorflow             2.2.0

**Comment by wangyems** [comment]
hi @jianqianzhou, onnxruntime_tools currently supports hugginface Albert onnx optimization exported from pytorch model. We plan to support tf model in the near future.

**Comment by jianqianzhou** [comment]
> hi @jianqianzhou, onnxruntime_tools currently supports hugginface Albert onnx optimization exported from pytorch model. We plan to support tf model in the near future.
> You may need to disable attention fusion to walk around this issue.
> BTW, opt_options = BertOptimizationOptions('bert_tf') is the right API to setup optimization for tf model from the current implementation.

I modify BertOptimizationOptions ，but the Error is the same：
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from segment.opt.onnx failed:This is an invalid model. Node (StatefulPartitionedCall/tf_albert_model/albert/encoder/albert_layer_groups_._0/albert_layers_._0/attention/add) input arg (StatefulPartitionedCall/tf_albert_model/albert/mul:0) does not have type information set by parent node.

`
output_model_path="segment.onnx"
opt_options = BertOptimizationOptions('bert_tf')
opt_options.enable_embed_layer_norm = False

opt_model = optimizer.optimize_model(
    output_model_path,
    'bert_keras',
    num_heads=12,
    hidden_size=768,
    optimization_options=opt_options)
opt_model.save_model_to_file('segment.opt.onnx')`

**Comment by wangyems** [comment]
> > hi @jianqianzhou, onnxruntime_tools currently supports hugginface Albert onnx optimization exported from pytorch model. We plan to support tf model in the near future.
> > You may need to disable attention fusion to walk around this issue.
> > BTW, opt_options = BertOptimizationOptions('bert_tf') is the right API to setup optimization for tf model from the current implementation.
> 
> I modify BertOptimizationOptions ，but the Error is the same：
> onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from segment.opt.onnx failed:This is an invalid model. Node (StatefulPartitionedCall/tf_albert_model/albert/encoder/albert_layer_groups_._0/albert_layers_._0/attention/add) input arg (StatefulPartitionedCall/tf_albert_model/albert/mul:0) does not have type information set by parent node.
> 
> `
> output_model_path="segment.onnx"
> opt_options = BertOptimizationOptions('bert_tf')
> opt_options.enable_embed_layer_norm = False
> 
> opt_model = optimizer.optimize_model(
> output_model_path,
> 'bert_keras',
> num_heads=12,
> hidden_size=768,
> optimization_options=opt_options)
> opt_model.save_model_to_file('segment.opt.onnx')`

OK. The fix is on our plan.

**Comment by wangyems** [comment]
Closing the issue as this issue should have been fixed

**Comment by danielbellhv** [comment]
Hi, @wangyems :)

>Albert onnx optimization exported from pytorch model.

Is there an equivalent of `BertOptimizationOptions`  for **Albert**?

I've made a [Git Issue](https://github.com/microsoft/onnxruntime/issues/10304#issue-1105816753) asking for this feature.
