### ISSUE TITLE
why do transformer onnx model perform slower than pytorch model for longer sequence length?

### ISSUE THREAD

**Issue by Ki6an** [microsoft/onnxruntime#6835]
hey, I've exported the huggingface's T5 model to onnx, using `torch.onnx.export() ` and ran it on onnxruntime with the following optimization.

```
options = SessionOptions()
options.graph_optimization_level = GraphOptimizationLevel.ORT_ENABLE_ALL
options.execution_mode = ExecutionMode.ORT_PARALLEL 
options.intra_op_num_threads = 1

# options.execution_order = ExecutionOrder.DEFAULT
# options.inter_op_num_threads = 0
# options.enable_profiling = True
# options.use_deterministic_compute = True 
# options.log_severity_level = 0

provider =  'CPUExecutionProvider' 

decoder_sess = InferenceSession(str(path_decoder), options, providers=[provider] )
encoder_sess = InferenceSession(str(path_encoder), options, providers=[provider] ) 
```
the converted t5 onnx model runs 2-2.5 times faster than the PyTorch model for smaller sequence length under (100 tokens) and beam num (<3). 

however, the onnx model runs slower than the PyTorch model for longer sequence length and higher beam-search number.
what might be causing the model to slow down? is it just the t5 model or do all transformer onnx models perform poorly on large batch size and sequence length?

any suggestions on improving the model speed would be appreciated.

**Comment by tianleiwu** [comment]
First thing first, for text generation, you will need past_key_values for longer sequence. Are you able to export T5 model with past_key_values? If so, feel free to contribute your export script to help others.

We have some initial work on T5, which can be found in branch [here](https://github.com/microsoft/onnxruntime/tree/yufeng/benchmark_t5/onnxruntime/python/tools/transformers/t5)
It does not support past_key_values yet but you can try the benchmark_t5 tool.

Actually, we have not started graph optimization (or any optimized kernel) for T5 model yet. We do have plan to improve T5 inference in near future (3~6 months). Please stay tuned.

**Comment by Ki6an** [comment]
hey, @tianleiwu thank you for the response. Yes, the t5 model utilizes `past_key_values`. I've optimized the inference code, now it does not slow down as much as it did before (for long sequence length and large batch size ). I'll be open-sourcing my project soon, please have a look at it.
for me, these following options are giving the best result so far... on Colab.
```
options.graph_optimization_level = GraphOptimizationLevel.ORT_ENABLE_ALL
options.execution_mode = ExecutionMode.ORT_PARALLEL 
options.intra_op_num_threads = 1
```

**Comment by tianleiwu** [comment]
@Ki6an, thanks for sharing. I'm glad that you solved the issue. Looking forward to your solution.

**Comment by Ki6an** [comment]
@tianleiwu I finally open-sourced the [project](https://github.com/Ki6an/fastT5) & it's also available on [PyPI](https://pypi.org/project/fastt5/). Testing and publishing to PyPI took a little time. 

however, before exporting t5 to onnx with `past_key_values`. you need to fix two things :

- exporting has some issues in the transformer library which can be fixed by following the guide in this [notebook](https://colab.research.google.com/drive/1HuH1Ui3pCBS22hW4djIOyUBP5UW93705?usp=sharing). I've created a pull request for this fix [here](https://github.com/huggingface/transformers/pull/10651), hope they merge it with the main branch soon. if you apply this fix you'll be able to use the fastT5 library without any problem.

- exporting has some bugs with` torch 1.8.0`, I've tested it many times, and exporting works fine on `torch 1.7.0 `. reported this bug [here ](https://github.com/pytorch/pytorch/issues/53730)

by making sure of these things, with onnx models, I was able to get the inference speed boost of up to 5x. thanks to you guys for the amazing work on onnxruntime. 

please have look at the [fastT5 ](https://github.com/Ki6an/fastT5)library, I'd love to hear any feedback.

**Comment by tianleiwu** [comment]
@Ki6an, cool! Thanks for your effort in making it possible to export t5 to onnx with past_key_values. That resolved a major issue for onnxruntime users to get faster inference of t5 model. 

A potential improvement for fastT5 in GPU is to use [IO Binding](https://www.onnxruntime.ai/python/api_summary). We'll update benchmark_t5.py with IO Binding for past_key_values later.

**Comment by Ki6an** [comment]
@tianleiwu thank you.  I agree and also the implementation of  `beam search` and `greedy search`  for the onnx model, I went through several iterations until I found the simple solution. 

for GPU, I tried without the `io binding` but was not getting better results so just stuck to the CPU version & `onnxrutime-gpu` does not support quantization. potentially in the future might work on the GPU version of fastt5.

>we have not started graph optimization (or any optimized kernel) for T5 model yet. We do have plan to improve T5 inference in near future (3~6 months)

- how does the graph & kernel optimization work? 
- how can I contribute to onnxruntime for t5?

**Comment by sam-writer** [comment]
Hi @tianleiwu , Sorry to revive an old thread, but I have the same questions as @Ki6an ...

**Comment by tianleiwu** [comment]
Regarding to graph & kernel optimization, there is developer guide:
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/Dev_Guide.md

Currently, there are two operators are related to T5 optimization:
**DecoderAttention**: current logic is for Bart model, need add slight modification for T5.
**BeamSearch**: current logic is for GPT-2 model, need some change for T5.

**Comment by sam-writer** [comment]
Thank you @tianleiwu !

@Ki6an FYI here is an answer to "how does graph & kernel optimization work", and for contributing, I think the answer is to do as @tianleiwu proposes for DecoderAttention and BeamSearch similar to this PR https://github.com/microsoft/onnxruntime/pull/8698

but please correct me if I am wrong @tianleiwu

**Comment by Ki6an** [comment]
@tianleiwu @sam-writer  thanks for the resources
