### ISSUE TITLE
how to build mlas only? I want to use mlas as my BLAS .

### ISSUE THREAD

**Issue by YanqingWu** [microsoft/onnxruntime#6839]

**Comment by yuslepukhin** [comment]
You will just need to extract its build rules from CMake file. It is being built as one of the static libs targets so isolating its build rules should not be too hard.

**Comment by YanqingWu** [comment]
> You will just need to extract its build rules from CMake file. It is being built as one of the static libs targets so isolating its build rules should not be too hard.

thanks a lot.
