### ISSUE TITLE
[JAVA Bindings + ARM64] ONNXRuntime build fail

### ISSUE THREAD

**Issue by jji2019** [microsoft/onnxruntime#6842]
**Describe the bug**
Following the documentation https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/README.md#arm-32v7, I still cannot get a successful build while enable java build with arm64.
- arm64 build is good with argument `--arm64`
- arm64+java is failed with argument `--arm64 --build_java`

**System information (Docker Host)**
- OS Platform and Distribution: `Linux Ubuntu 18.04 on AWS instance`
- QEMU: `qemu-user-static/bionic-updates,bionic-security,now 1:2.11+dfsg-1ubuntu7.36 amd64 [installed]`
- Docker CE:
`docker-ce/bionic,now 5:20.10.3~3-0~ubuntu-bionic amd64 [installed,upgradable to: 5:20.10.4~3-0~ubuntu-bionic]`
`docker-ce-cli/bionic,now 5:20.10.3~3-0~ubuntu-bionic amd64 [installed,upgradable to: 5:20.10.4~3-0~ubuntu-bionic]`

**System information (Docker Image/Container)**
- OS Platform: `FROM Docker image: balenalib/raspberrypi3-python:latest-stretch-build`
- Docker Container:
`root@672b24c38f99:/code# uname -r`
`5.4.0-1038-aws`

- ONNX Runtime installed from: source
- ONNX Runtime version: master branch clone on Feb 26, 2021
`git log last commit:`
`commit d5175795d2b7f2db18b0390f394a49238f814668`
`Author: Pranav Prakash <pranav-prakash@users.noreply.github.com>`
`Date:   Fri Feb 26 10:21:37 2021 -0800`

- Python version: installed by the Dockerfile ([Dockerfile.java.arm64](https://www.dropbox.com/s/iu8vywa0x2d90yf/Dockerfile.java.arm64))
`Python 3.8.5 (default, Jul 21 2020, 14:14:58) `
`[GCC 6.3.0 20170516] on linux`

- CMake: installed by the Dockerfile ([Dockerfile.java.arm64](https://www.dropbox.com/s/iu8vywa0x2d90yf/Dockerfile.java.arm64))
`cmake-3.18.3`

- Gradle: `6.3` installed by the Dockerfile ([Dockerfile.java.arm64](https://www.dropbox.com/s/iu8vywa0x2d90yf/Dockerfile.java.arm64))

- JDK version: installed by the Dockerfile ([Dockerfile.java.arm64](https://www.dropbox.com/s/iu8vywa0x2d90yf/Dockerfile.java.arm64))
`openjdk version "1.8.0_275"`
`OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-1~deb9u1-b01)`
`OpenJDK Client VM (build 25.275-b01, mixed mode)`

**To Reproduce**
- launch a new aws instance using platform Linux 18.04 ubuntu
- install Docker CE
- install ARM emulator
- run docker build command: `docker build -t onnxruntime-java-arm64 Dockerfile.java.arm64 .` using ([Dockerfile.java.arm64](https://www.dropbox.com/s/iu8vywa0x2d90yf/Dockerfile.java.arm64))

**Expected behavior**
successful build

**Error message**
`CMake Error at onnxruntime_java.cmake:135 (message):`
`  Java is currently not supported on 32-bit x86 architecture`
`Call Stack (most recent call first):`
`  CMakeLists.txt:1498 (include)`

**Comment by Craigacp** [comment]
That still seems to be based off a 32-bit image, and as the CMake message says, the Java API isn't supported on 32-bit platforms. We should probably tidy up the message so it doesn't say x86, when it's not supported on either 32-bit ARM or 32-bit x86.

What happens if you try to use a raspberrypi 4 base image?

**Comment by jji2019** [comment]
@Craigacp , Thanks for providing me the information. Do you mean not to use the `balenalib/raspberrypi3-python`? 
Which docker base image do you suggest? Any link to point to? :D Appreciate that.

**Comment by Craigacp** [comment]
Unfortunately I don't really know anything about the docker images used to build it, but there is a note at the top of the Dockerfile you posted saying the base image needs to be changed to use a 64-bit build. My understanding of the raspberrypi OS distributions is that the rpi3 is usually on a 32-bit install, and the rpi4 has a 64-bit option (though both processors support 64-bit ARM).

I've not tried to cross-compile the Java bits, so I'm not sure how well it will work. The Java cmake configuration uses the same platform detection logic as the rest of ORT so I'm not sure why it's not picking up that it's supposed to be doing a 64-bit compile.

**Comment by jji2019** [comment]
Changing the configuration `--arm64` is the documented in this Dockerfile [https://github.com/microsoft/onnxruntime/dockerfiles/Dockerfile.arm32v7](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.arm32v7#L44).

btw, according to your comment, perhaps I can try rpi3_arm32+java and see if the build is good.
In addition, I will try rpi4_arm64+java later.

Thanks! :D

**Comment by Craigacp** [comment]
No, it definitely won't compile the Java bits on 32-bit platforms. The JNI code assumes that pointers are 64-bits and passes them in longs, you're likely to get weird compilation errors if a pointer is less than that length.

**Comment by Craigacp** [comment]
The Java tests pass when built on Ubuntu 20.10 aarch64 (running in a VM on an M1 Mac, I don't have an ARM server to test on). I checked the source out and built it directly without docker, so this isn't a test that the docker build environment works, but at least the code compiles and runs.

**Comment by jji2019** [comment]
Thanks for providing more information. Since I don't have M1 Mac machine, I might still need to try the cross-platform build.

Here is the build result of rpi3_arm32+java. Unfortunately, I still see Cmake error. I don't know if I need to install specific version of gradle or java?

Build command: `docker build -t onnxruntime-arm32-java -f Dockerfile.arm32v7Java .`
Docker file: https://www.dropbox.com/s/abham3qucylym0t/Dockerfile.arm32v7Java?dl=0
Docker build log: https://www.dropbox.com/s/3j58kwhe8575xkc/Dockerfile.arm32v7Java.log.txt?dl=0
Error snippet:
```
-- Java Build is enabled
-- Found Java: /usr/bin/java (found version "1.8.0_275") 
-- Found JNI: /usr/lib/jvm/default-java/jre/lib/arm/libjawt.so  
-- Using gradle: /usr/bin/gradle
CMake Error at onnxruntime_java.cmake:135 (message):
  Java is currently not supported on 32-bit x86 architecture
Call Stack (most recent call first):
  CMakeLists.txt:1498 (include)
```

**Comment by Craigacp** [comment]
I think you're still using a 32-bit ARM environment, and it won't compile there. Try a 64-bit base docker image.

**Comment by jji2019** [comment]
This is the result of `balenalib/raspberrypi4-64-python:latest-stretch-build` which is supposed to support arm64.

Docker file: [Dockerfile.arm64Java](https://www.dropbox.com/s/9v98w1fyjfo4spe/Dockerfile.arm64Java?dl=0)
Docker build command: `docker build -t onnxruntime-arm64-java -f Dockerfile.arm64Java .`
Docker build output: [Dockerfile.arm64Java_out.txt](https://www.dropbox.com/s/wb0msac2gf94b6f/Dockerfile.arm64Java_out.txt?dl=0)

Error snippet:
```
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Java Build is enabled
-- Found Java: /usr/lib/jvm/java-8-openjdk-arm64/bin/java (found version "1.8.0_275") 
CMake Error at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.18/Modules/FindJNI.cmake:374 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  onnxruntime_java.cmake:11 (find_package)
  CMakeLists.txt:1498 (include)
```

**Comment by Craigacp** [comment]
So that's failing to find a library which CMake thinks you need but you don't (and so can be patched around) and one that you do. You don't need `JAVA_AWT_LIBRARY`, so it looks like the workaround for that is to put `set(JAVA_AWT_LIBRARY NotNeeded)` in the onnxruntime_java.cmake file before the call to `findPackage(JNI REQUIRED)`. However we do need `JAVA_JVM_LIBRARY` and it's hard to say why it couldn't find it especially as it was in the other image.

To be honest, I'm not really sure what will fix that as I don't know enough about those images, but `JAVA_AWT_LIBRARY` will appear when you install a desktop environment (or at least it did on Ubuntu Server as I hit the same issue yesterday), and maybe that will fix the missing `JAVA_JVM_LIBRARY` too. This is using a sledgehammer to crack a nut, as you definitely don't need it to build it, but it's hard to say what a more minimal solution is.

Alternatively you could completely specify the path to those libraries before the CMake `FindPackage(JNI REQUIRED)` call. libawt.so should be in `/usr/lib/jvm/java-8-openjdk-aarch64/jre/lib/amd64` and libjvm.so should be in `/usr/lib/jvm/java-8-openjdk-aarch64/jre/lib/amd64/server`.

**Comment by jji2019** [comment]
Thanks for the suggestion. I will update the Cmake path and update you the result once I have it. :D Appreciate that.

**Comment by jji2019** [comment]
Hi, regarding to your earlier comment `The Java tests pass when built on Ubuntu 20.10 aarch64 (running in a VM on an M1 Mac`. I also tried this combination but got the error same to [#5987](https://github.com/microsoft/onnxruntime/issues/5987):

OS Platform: `ubuntu arm64 20.10` ami:`ubuntu/images/hvm-ssd/ubuntu-groovy-20.10-arm64-server-20210224`
Python:
`Python 3.8.6 (default, Jan 27 2021, 15:42:20) `
`[GCC 10.2.0] on linux`
Java: `/usr/lib/jvm/java-8-openjdk-arm64/bin/java`
Cmake: `3.18.3`
Error log file: [20210302_arm64_error.log](https://www.dropbox.com/s/nqzkp8vc6h6ueca/20210302_arm64_error.log?dl=0) , [20210302_arm64_error1.log](https://www.dropbox.com/s/q7iq4u6k4ybbelj/20210302_arm64_error1.log?dl=0)
Error snippet:
```
home/ubuntu/code/onnxruntime/cmake/external/json/single_include/nlohmann/json.hpp:8494:24: error: comparison is always true due to limited range of data type [-Werror=type-limits]
 8494 |             if ('\x00' <= c and c <= '\x1F')
      |                 ~~~~~~~^~~~
```

**Comment by Craigacp** [comment]
Ah, sorry. I installed gcc-8 and set `CC=gcc-8` and `CXX=g++-8` first. I'm not sure when they will fix the compiler errors with gcc 10.

**Comment by jji2019** [comment]
It works with gcc-8 and g++-8. Awesome and appreciate the help 👯

**Comment by Craigacp** [comment]
@faxu should we document something about compiling for ARM 64-bit platforms? The Java API should just work (assuming the rest of ORT compiled), but there seems to be a bit of complexity in choosing a base docker image. Unfortunately I don't really work with docker & arm so I'm not sure what kind of thing it's worthwhile to document.

@jji2019 apart from a documentation fix, is it ok to close this now?

**Comment by jji2019** [comment]
@Craigacp , the build worked two days ago, and today I met another build problem after pulling the latest source from GitHub. Sorry for lasting this issue longer. I will post my log soon.
