### ISSUE TITLE
What is, if any, the relationship between ONNX Runtime and ONNX IFI?

### ISSUE THREAD

**Issue by pliniosilveira** [Microsoft/onnxruntime#685]
ONNX IFI reference: https://github.com/onnx/onnx/blob/master/docs/ONNXIFI.md

I would like to understand similarities and differences between them. 
Are they competitor standards? 
Does Runtime use IFI underneath? 

I have a custom device to run ONNX models. How do I decide whether to implement a new [ONNX Runtime Execution Provider](https://github.com/Microsoft/onnxruntime/blob/master/docs/AddingExecutionProvider.md) or a new [ONNX IFI Implementation](https://github.com/onnx/onnx/blob/master/docs/ONNXIFI.md)?

**Comment by faxu** [comment]
Please see this: https://github.com/Microsoft/onnxruntime/issues/249

You will need to implement an ONNX Runtime Execution Provider for compatibility with ONNX Runtime.

**Comment by pranavsharma** [comment]
closed as per previous comment.
