### ISSUE TITLE
Quantized layers inference error on MacOS

### ISSUE THREAD

**Issue by volcacius** [microsoft/onnxruntime#6852]
Hello,

Inference on MacOS with models containing respectively a QLinearConv and a QLinearMatMul gives an error. The same models are okay on Windows and Ubuntu (attached below). This is from the CI (running on github actions) of a Pytorch quantization-aware training library I maintain, so I don't have access to a real system unfortunately.

**Urgency**
No urgency.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macos-latest on github actions (not sure which version that is)
- ONNX Runtime installed from (source or binary): installed from pip
- ONNX Runtime version: 1.6.0
- Python version: tested with 3.6, 3.7 and 3.8
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: cpu only
- GPU model and memory:

**To Reproduce**
- You can find my CI runs here https://github.com/Xilinx/brevitas/runs/2004964504?check_suite_focus=true . I use nox (a python tox-like library) to wrap tasks and execute them in a virtualenv. The two failing .onnx files are attached, I generated them locally running the same task on my Windows laptop (where it doesn't fail).
[qlinear_layers.zip](https://github.com/microsoft/onnxruntime/files/6062798/qlinear_layers.zip)

**Expected behavior**
Inference shouldn't fail. 

**Additional context**
The issue with QLinearMatMul arises when the layer is exported from versions of Pytorch >= 1.3.0, so for 1.1.0 and 1.2.0 it works (I'm already suppressing errors for pytorch 1.3.0 to 1.6.0 in my CI, so it doesn't show in the logs reported above). The issue with QLinearConv arises only when the layer is exported from Pytorch 1.7.1 (I'm not testing against 1.7.0 so not sure how it behaves with that) but for Pytorch <= 1.6.0 it works fine. 
When I say export I mean defining a custom symbolic layer in Pytorch that maps to QLinearMatMul/QLinearConv. I understand this is probably not a scenario that is really supported by onnxruntime, but I figured reporting the issue wouldn't hurt. If this is a known limitation I'm happy to mark it as such in my library.

**Comment by yufenglee** [comment]
@volcacius , could you help confirm if it happens in 'exporting' stage or running inference stage?

**Comment by volcacius** [comment]
Export is fine, it happens during inference with onnxruntime.

**Comment by volcacius** [comment]
Somehow this solved itself without me doing anything. I guess something changed server side on GHA? Closing.
