### ISSUE TITLE
TFlite model crashes in ONNX runtime

### ISSUE THREAD

**Issue by sniper0110** [microsoft/onnxruntime#6874]
**Describe the bug**
I transformed a tflite model to onnx model using tf2onnx. The conversion process went well but when I use the model in python, the program quits without any warnings or errors. At first, I thought there was a problem with the conversion process so I opened an issue here : [](https://github.com/onnx/tensorflow-onnx/issues/1349)

**Urgency**
I am currently trying to deploy the models in our company to production and ONNX runtime seems like the best option for us. So this is rather urgent. If we succeed in deploying our model, we might expand the use of onnx runtime for the rest of our deep learning tasks.

**System information**
- OS : Windows (64 and 32 bits)
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: '1.6.0'
- Python version: 3.8.5
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: we're not using GPU for inference
- GPU model and memory: we're not using GPU for inference

**To Reproduce**
This is a sample code for loading the model and making a prediction with it:
```
import numpy as np
import onnx 
from onnx import backend 

import onnxruntime as rt
import os
from PIL import Image
import cv2
import time


path_to_model = 'models/ONNXModels/tflite_model_2.onnx'
path_to_img = "path\\to\\image\\000_d1.png"

model_path = os.path.join(path_to_model)

sess = rt.InferenceSession(model_path)
input_name = sess.get_inputs()[0].name
output_names = []
for output in sess.get_outputs():
   output_names.append(output.name)

print("input_name : ", input_name)
print("output_names : ", output_names)

elapsed_time = 0

for i in range(100):
   
   image = cv2.imread(path_to_img)
   image = cv2.resize(image, (128,32), interpolation=cv2.INTER_CUBIC)
   image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

   image = np.expand_dims(image, axis=0)
   image = np.expand_dims(image, axis=3)
   #print('image.shape = ', image.shape)

   image = image.astype(np.float32)
   t1 = time.process_time()

   out = sess.run(output_names, {input_name: image})
   t2 = time.process_time()

   elapsed_time += t2 - t1

print(f"process time = {elapsed_time/100} s")
```

The onnx model that was used : 
[tflite_model_2.zip](https://github.com/microsoft/onnxruntime/files/6075440/tflite_model_2.zip)

**Expected behavior**
I expected the program to run until the end and give me the elapsed_time.

**Additional context**
The original model that I transformed into a onnx model was a tflite model. The tflite model works fine.

**Comment by TomWildenhain-Microsoft** [comment]
The problem with the model is it is missing shape info for the graph inputs of a loop subgraph.  I'll fix it in the converter, but ORT should be updated to not crash in this case.

**Comment by sniper0110** [comment]
@skottmckay does your commit fix the issue? 
How can I test it using the python package?

**Comment by skottmckay** [comment]
No - my change will give an error message instead of crashing silently. 

You need an updated version of the tf2onnx converter to generate a correct model, at which point the model should work with the existing ORT python package.

**Comment by skottmckay** [comment]
Incidentally should the model start with a Reshape node or a Transpose? Looks like it's attempting to convert from NCHW to NHWC, but a Reshape won't do that (it just changes the shape not the data).
