### ISSUE TITLE
How to call `CreateEnvWithGlobalThreadPools` in cpp program?

### ISSUE THREAD

**Issue by ZacheryGuan** [microsoft/onnxruntime#6875]
# Background
I have several ONNX models to run in sequence as a service, and I need to initialize all sessions before running them. As mentioned in [C_API doc - Features - **Global/shared thread pools**](https://github.com/microsoft/onnxruntime/blob/rel-1.3.0/docs/C_API.md#L15), I think it is better to use shared thread pools. 

# Questions
I cannot find a sample of calling this api. Would you please give a sample of `CreateEnvWithGlobalThreadPools` and starting sessions with corresponding session options? Just like:
```cpp
Ort::Env env =  CreateEnvWithGlobalThreadPools();  // something I am asking for
Ort::SessionOptions sesstionOptions;
sessionOptions.DisablePerSessionThreads();
for (auto & modelPath:modelPaths) {
  Ort::Session session(&env, modelPath, sesstionOptions);
  sessionList.push_back(session);
}
```

**Comment by pranavsharma** [comment]
This is the corresponding C++ API: https://github.com/microsoft/onnxruntime/blob/299ace0759192557e97e14d03c08f0334c84e9d5/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L253. After this call https://github.com/microsoft/onnxruntime/blob/299ace0759192557e97e14d03c08f0334c84e9d5/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L322.

**Comment by ZacheryGuan** [comment]
Thank you. But how to initialize an OrtThreadingOptions object?

I write a piece of test code as following
```
OrtThreadingOptions *threadingOptions;
Ort::SessionOptions sessionOptions;
sessionOptions.DisablePerSessionThreads();
Ort::Env env(threadingOptions, ORT_LOGGING_LEVEL_WARNING, "test");

const char *modelPath = "model.onnx";
Ort::Session session(env, modelPath, sessionOptions);
```
and get a RuntimeError 
`libc++abi.dylib: terminating with uncaught exception of type Ort::Exception: onnxruntime/core/session/inference_session.cc:267 void onnxruntime::InferenceSession::ConstructorCommon(const onnxruntime::SessionOptions &, const onnxruntime::Environment &) session_env.EnvCreatedWithGlobalThreadPools() was false. When the session is not configured to use per session threadpools, the env must be created with the the CreateEnvWithGlobalThreadPools API.
`

**Comment by pranavsharma** [comment]
It doesn't look like we wrote a C++ wrapper for OrtThreadingOptions. You can however use the C APIs for now.

  ORT_API2_STATUS(CreateThreadingOptions, _Outptr_ OrtThreadingOptions** out);
  ORT_API2_STATUS(SetGlobalIntraOpNumThreads, _Inout_ OrtThreadingOptions* tp_options, int intra_op_num_threads);
  ORT_API2_STATUS(SetGlobalInterOpNumThreads, _Inout_ OrtThreadingOptions* tp_options, int inter_op_num_threads);
  ORT_API2_STATUS(SetGlobalSpinControl, _Inout_ OrtThreadingOptions* tp_options, int allow_spinning);

**Comment by xiaowenhe** [comment]
@pranavsharma , I have the same error with @jatinsha,.
![image](https://user-images.githubusercontent.com/28335784/157617707-871c2af5-148b-44bd-9166-52caf2c9651f.png)

Can you give me a  example for how to use CreateEnvWithGlobalThreadPools and DisablePerSessionThreads() when use 2 session in same process?

Global/shared threadpools: By default each session creates its own set of threadpools. In situations where multiple sessions need to be created (to infer different models) in the same process, you end up with several threadpools created by each session. In order to address this inefficiency we introduce a new feature called global/shared threadpools. The basic idea here is to share a set of global threadpools across multiple sessions. Typical usage of this feature is as follows
    Populate ThreadingOptions. Use the value of 0 for ORT to pick the defaults.
    Create env using CreateEnvWithGlobalThreadPools()
    Create session and call DisablePerSessionThreads() on the session options object
    Call Run() as usual

**Comment by mmxuan18** [comment]
i test this global thread option, the same model if i use global thread the time cost of model run is much than not use global, the thread intera=2 and inter=1 set the same, why have this performance differents? @[pranavsharma](https://github.com/pranavsharma)

**Comment by smasyutin** [comment]
@pranavsharma I have the same struggles as the original poster. And the same errors when working with C API as @jatinsha . Is there any progress on C++ wrapper for OrtThreadingOptions?
