### ISSUE TITLE
onnxruntime 1.7.0 inference model crashes, but 1.6.0 can

### ISSUE THREAD

**Issue by laizewei** [microsoft/onnxruntime#6876]
The following OnNX model does not reason in 1.7.0, but it does in 1.6.0.It is a Chinese and English character recognition model.It comes from the Baidu PaddleOCR open source model.
[rec_paddle.zip](https://github.com/microsoft/onnxruntime/files/6076591/rec_paddle.zip)

**Comment by jcwchen** [comment]
Hi @laizewei,
Could this model be run (inference) normally with ORT 1.6.0? Actually it cannot pass onnx.shape_inference.infer_shapes either. I am not familiar with OCR models, but the input shape looks not right: 1x3x32x-1. Is it expected? Thanks.

**Comment by laizewei** [comment]
This model is a dynamic input size.Another text detection model is also a dynamic input size that can be inferred successfully. But this text recognition model reasoning is not successful.


#include <iostream>
#include "onnxruntime_cxx_api.h"

int main()
{
    Ort::Env env{ nullptr };
    std::cout << "test0" << std::endl;
    Ort::Session session{ nullptr };
    Ort::SessionOptions sessionOptions{ nullptr };
    std::cout << "test1" << std::endl;
    session = Ort::Session::Session(env, L"C:\\Users\\lwx997302\\source\\repos\\ConsoleApplication1\\ConsoleApplication1\\rec_paddle.onnx", sessionOptions);//error
    std::cout << "test2" << std::endl;
    std::vector<const char*> input_names;
    input_names.push_back("input");
    std::vector<const char*> output_names;
    output_names.push_back("save_infer_model/scale_0.tmp_0");
    auto memoryInfo = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeDefault);
    std::cout << "test3" << std::endl;
    std::vector<Ort::Value> ort_inputs;
    Ort::Value inputTensor{ nullptr };
    std::vector<float> input_tensor_values;
    std::vector<int64_t> input_node_dims{1*3*32*320};
    for (int i = 0; i < 1; i++)
    {
        input_tensor_values.resize(1 * 3 * 32 * 320);

        for (int j = 0; j < 1 * 3 * 32 * 320; j++)
        {
            input_tensor_values[j] = 0.01;
        }
        inputTensor = Ort::Value::CreateTensor<float>(memoryInfo, input_tensor_values.data(), input_tensor_values.size(), input_node_dims.data(), input_node_dims.size());
        ort_inputs.push_back(std::move(inputTensor));
    }
    std::cout << "beginRun" << std::endl;
    std::vector<Ort::Value> ort_outputs = session.Run(Ort::RunOptions{ nullptr }, input_names.data(), ort_inputs.data(), ort_inputs.size(), output_names.data(), output_names.size());//error
    std::cout << ort_outputs.size() << std::endl;
    return 0;
}

**Comment by laizewei** [comment]
2021-03-04 09:37:55.8432945 [E:onnxruntime:, sequential_executor.cc:339 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running ScatterND node. Name:'ScatterND@1' Status Message: updates tensor should have shape equal to indices.shape[:-1] + data.shape[indices.shape[-1]:]. updates shape: {1}, indices shape: {1}, data shape: {3}

**Comment by laizewei** [comment]
model url:
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_en/models_list_en.md
ch_ppocr_mobile_v2.0_rec,Use opset_version 11 to turn the model.
The model was inferred successfully with OnnxRuntime 1.6.0.

**Comment by laizewei** [comment]
The problem is caused by the PADDLEPADDLE conversion to ONNX.

**Comment by SWHL** [comment]
I have met the same problem.
