### ISSUE TITLE
python API: onnxruntime.set_seed does not seem to work

### ISSUE THREAD

**Issue by IceTDrinker** [microsoft/onnxruntime#6877]
**Describe the bug**
I am using the Random* family of onnx nodes and would like to run some reproducible tests

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Build 19042
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.6.0
- Python version: 3.8.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
```python
import numpy
import onnx
import onnxruntime
import onnxruntime.backend as onnxruntime_backend
# import onnxruntime.capi._pybind_state as bind_state

onnxruntime.set_seed(0)

node = onnx.helper.make_node(
    "RandomUniformLike",
    inputs=["x"],
    outputs=["y"],
)

x_value_info = onnx.helper.make_tensor_value_info(
    "x", onnx.TensorProto.FLOAT, [1]
)

y_value_info = onnx.helper.make_tensor_value_info(
    "y", onnx.TensorProto.FLOAT, [1]
)

computation_graph_def = onnx.helper.make_graph(
    [node],
    "test_seed",
    [x_value_info],
    [y_value_info],
)

computation_model_def = onnx.helper.make_model(
    computation_graph_def,
    producer_name="test",
)
computation_model_def.opset_import[0].version = 12

sess = onnxruntime_backend.prepare(computation_model_def, log_severity_level=3, device="CPU")

x = numpy.zeros((1), dtype=numpy.float32)

for __ in range(10):
    y = sess.run(x)
    print(y)
```

Launch the code above several times, the expected results is that the output should be the same every time because we set the seed explicitely. To avoid issues with threading the tensor is a single scalar.

**Expected behavior**
Output should be the same between program runs which is not the case

**Screenshots**
none

**Additional context**

onnx version 1.8.1
numpy version 1.18.5
From onnxruntime_pybind_state.cc:

```cpp
  m.def(
      "set_seed", [](const int64_t seed) { utils::SetRandomSeed(seed); },
      "Sets the seed used for random number generation in Onnxruntime.");
```

**Comment by jcwchen** [comment]
Hi @IceTDrinker,
`onnxruntime.set_seed` is set for ORT utilities. In your case, you need to set the seed for the Random-family operators. For instance:
```
import numpy
import onnx
import onnxruntime
import onnxruntime.backend as onnxruntime_backend
# import onnxruntime.capi._pybind_state as bind_state

node = onnx.helper.make_node(
    "RandomUniformLike",
    inputs=["x"],
    outputs=["y"],
    seed=1.
)

x_value_info = onnx.helper.make_tensor_value_info(
    "x", onnx.TensorProto.FLOAT, [1]
)

y_value_info = onnx.helper.make_tensor_value_info(
    "y", onnx.TensorProto.FLOAT, [1]
)

computation_graph_def = onnx.helper.make_graph(
    [node],
    "test_seed",
    [x_value_info],
    [y_value_info]
)

computation_model_def = onnx.helper.make_model(
    computation_graph_def,
    producer_name="test",
)
computation_model_def.opset_import[0].version = 1

sess = onnxruntime_backend.prepare(computation_model_def, log_severity_level=3, device="CPU")

x = numpy.zeros((1), dtype=numpy.float32)

for __ in range(10):
    y = sess.run(x)
    print(y)
```

**Comment by IceTDrinker** [comment]
Darn, I feel silly now... but I see why it's designed this way. Thank you for the answer.

Is it still recommended to seed onnxruntime if we want reproducible runs ?

**Comment by jcwchen** [comment]
According to this https://github.com/microsoft/onnxruntime/pull/3490, I would say if your usage involves Dropout, then set seed in ORT is needed. Otherwise it should be fine. Thanks.

**Comment by IceTDrinker** [comment]
Using the seed attribute worked. Closing

Cheers
