### ISSUE TITLE
dynamic quantization creating unnecessary parent model with "opt" appended to the model name.

### ISSUE THREAD

**Issue by Ki6an** [microsoft/onnxruntime#6888]
hey, the `quantize_dynamic()` method for quantizing the onnx model is producing the parent model with `opt` appended to its name. The method still works and generates the quantized model but along with the quantized model, it is generating a parent model.
```
models/
├── t5-base-decoder-opt.onnx   <--
├── t5-base-decoder-quantized.onnx
```

In `onnxruntime==1.6.0.` it used to create just the quantized model. but having this issue in version `1.7.0`.

os : Ubuntu 18.04.5 LTS

**Comment by yufenglee** [comment]
The tool optimizes the model before quantizing from 1.7.0. There is a option to control it: https://github.com/microsoft/onnxruntime/blob/8f1786d5d2ac5377b2a887398d9048fd06beeabc/onnxruntime/python/tools/quantization/quantize.py#L237. It is left there to compare with the original file. Other that, it is useless.

**Comment by Ki6an** [comment]
thank you for the replay @yufenglee. I've got a question.  how's this optimized model different from the original model? are there any specific advantages of using opt model over the other?

**Comment by pranav-prakash** [comment]
The optimized model currently consists of the basic optimizations that ORT performs on graphs (see https://www.onnxruntime.ai/docs/resources/graph-optimizations.html ) most relevant of which is Conv BatchNorm Fusion. On top of that there is a custom post-pass to convert gemm into matmul if possible.

**Comment by Ki6an** [comment]
hey, @pranav-prakash  thank you for the valuable information.
