### ISSUE TITLE
iOS build with -fembed-bitcode option

### ISSUE THREAD

**Issue by seungillee** [microsoft/onnxruntime#6900]
**Describe the bug**

To use ios build for production, we need to include the "-fembed-bitcode" option for compiling. So I run the build script as follows;

```
build.sh --config MinSizeRel \
                     --parallel \
                     --minimal_build \
                     --disable_exceptions \
                     --use_xcode \
                     --ios \
                     --ios_sysroot iphoneos \
                     --osx_arch arm64 \
                     --apple_deploy_target 9.0 \
                     --include_ops_by_config required_operators.config \
                     --disable_ml_ops \
                     --skip_tests \
                     --cmake_extra_defines CMAKE_CXX_FLAGS="-fembed-bitcode"
````

However, this results in the following compilation error;

```
clang: error: -ffunction-sections is not supported with -fembed-bitcode
clang: error: -fdata-sections is not supported with -fembed-bitcode
```

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): iOS
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.6.0
- Python version: 3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

--ios option should be able to compile with -fembed-bitcode compile option

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by gwang-msft** [comment]
To enable build with bitcode for iOS, please use `--cmake_extra_defines onnxruntime_ENABLE_BITCODE=ON` with your build command.
