### ISSUE TITLE
Unable to build the docker file for openvino on cpu

### ISSUE THREAD

**Issue by dipendra009** [microsoft/onnxruntime#6902]
**Describe the bug**
Unable to build the docker image for openvino on CPU_FP32 using the provided docker file- dockerfiles/Dockerfile.openvino

**Urgency**
Unable to use the onnxruntime and openvino platform.

**System information**
- Mac OSX

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Screenshots**

![image](https://user-images.githubusercontent.com/7588363/110050281-73be6500-7d08-11eb-97b3-e150ba9b0040.png)

**Additional context**

CMake Error at onnxruntime_providers.cmake:572 (find_package):
  By not providing "Findngraph.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ngraph", but
  CMake did not find one.

  Could not find a package configuration file provided by "ngraph" with any
  of the following names:

    ngraphConfig.cmake
    ngraph-config.cmake

  Add the installation prefix of "ngraph" to CMAKE_PREFIX_PATH or set
  "ngraph_DIR" to a directory containing one of the above files.  If "ngraph"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:1407 (include)

-- Configuring incomplete, errors occurred!
See also "/code/onnxruntime/build/Linux/Release/CMakeFiles/CMakeOutput.log".
See also "/code/onnxruntime/build/Linux/Release/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/code/onnxruntime/tools/ci_build/build.py", line 2003, in <module>
    sys.exit(main())
  File "/code/onnxruntime/tools/ci_build/build.py", line 1926, in main
    path_to_protoc_exe, configs, cmake_extra_defines, args, cmake_extra_args)
  File "/code/onnxruntime/tools/ci_build/build.py", line 970, in generate_build_tree
    cwd=config_build_dir)
  File "/code/onnxruntime/tools/ci_build/build.py", line 536, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/code/onnxruntime/tools/python/util/run.py", line 44, in run
    env=env, shell=shell)
  File "/opt/miniconda/lib/python3.7/subprocess.py", line 468, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/code/cmake-3.14.3-Linux-x86_64/bin/cmake', '/code/onnxruntime/cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_BUILD_WINML_TESTS=ON', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-Donnxruntime_DEV_MODE=ON', '-DPYTHON_EXECUTABLE=/opt/miniconda/bin/python3', '-Donnxruntime_USE_CUDA=OFF', '-Donnxruntime_CUDA_VERSION=', '-Donnxruntime_CUDA_HOME=', '-Donnxruntime_CUDNN_HOME=', '-Donnxruntime_USE_FEATURIZERS=OFF', '-Donnxruntime_USE_MIMALLOC_STL_ALLOCATOR=OFF', '-Donnxruntime_USE_MIMALLOC_ARENA_ALLOCATOR=OFF', '-Donnxruntime_ENABLE_PYTHON=ON', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_JAVA=OFF', '-Donnxruntime_BUILD_NODEJS=OFF', '-Donnxruntime_BUILD_SHARED_LIB=ON', '-Donnxruntime_USE_DNNL=OFF', '-Donnxruntime_DNNL_GPU_RUNTIME=', '-Donnxruntime_DNNL_OPENCL_ROOT=', '-Donnxruntime_USE_NNAPI_BUILTIN=OFF', '-Donnxruntime_USE_RKNPU=OFF', '-Donnxruntime_USE_OPENMP=OFF', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_VITISAI=OFF', '-Donnxruntime_USE_NUPHAR=OFF', '-Donnxruntime_USE_TENSORRT=OFF', '-Donnxruntime_TENSORRT_HOME=', '-Donnxruntime_USE_MIGRAPHX=OFF', '-Donnxruntime_MIGRAPHX_HOME=', '-Donnxruntime_CROSS_COMPILING=OFF', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_DISABLE_ML_OPS=OFF', '-Donnxruntime_DISABLE_RTTI=OFF', '-Donnxruntime_DISABLE_EXCEPTIONS=OFF', '-Donnxruntime_DISABLE_ORT_FORMAT_LOAD=OFF', '-Donnxruntime_MINIMAL_BUILD=OFF', '-Donnxruntime_EXTENDED_MINIMAL_BUILD=OFF', '-Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF', '-Donnxruntime_REDUCED_OPS_BUILD=OFF', '-Donnxruntime_MSVC_STATIC_RUNTIME=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=OFF', '-Donnxruntime_USE_WINML=OFF', '-Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxruntime_USE_ACL=OFF', '-Donnxruntime_USE_ACL_1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_USE_ACL_2002=OFF', '-Donnxruntime_USE_ARMNN=OFF', '-Donnxruntime_ARMNN_RELU_USE_CPU=ON', '-Donnxruntime_ARMNN_BN_USE_CPU=ON', '-Donnxruntime_ENABLE_NVTX_PROFILE=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_ENABLE_TRAINING_OPS=OFF', '-Donnxruntime_ENABLE_CPU_FP16_OPS=OFF', '-Donnxruntime_USE_NCCL=ON', '-Donnxruntime_BUILD_BENCHMARKS=OFF', '-Donnxruntime_USE_ROCM=OFF', '-Donnxruntime_ROCM_HOME=', '-DOnnxruntime_GCOV_COVERAGE=OFF', '-Donnxruntime_USE_MPI=ON', '-Donnxruntime_ENABLE_MEMORY_PROFILE=OFF', '-Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF', '-Donnxruntime_USE_OPENVINO=ON', '-Donnxruntime_USE_OPENVINO_MYRIAD=OFF', '-Donnxruntime_USE_OPENVINO_GPU_FP32=OFF', '-Donnxruntime_USE_OPENVINO_GPU_FP16=OFF', '-Donnxruntime_USE_OPENVINO_CPU_FP32=ON', '-Donnxruntime_USE_OPENVINO_VAD_M=OFF', '-Donnxruntime_USE_OPENVINO_VAD_F=OFF', '-Donnxruntime_USE_OPENVINO_HETERO=OFF', '-Donnxruntime_USE_OPENVINO_DEVICE=CPU_FP32', '-Donnxruntime_USE_OPENVINO_MULTI=OFF', '-Donnxruntime_USE_FULL_PROTOBUF=ON', '-DProtobuf_USE_STATIC_LIBS=ON', '-Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF', '-Donnxruntime_ENABLE_MEMLEAK_CHECKER=OFF', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

**Comment by jywu-msft** [comment]
can you confirm what host system you are trying to build the Docker Image on? 
the issue shows Mac OSX? Is that accurate? The dockerfile was created for and has been tested on systems running Ubuntu Linux.

**Comment by dipendra009** [comment]
Yeah, that's correct. I have not tried to built the latest ones on Ubuntu. Thank you for letting me know.

**Comment by dipendra009** [comment]
Do you guys have the corresponding docker files for Linux machine? I am not able to build the master or v1.7.1 even on CentOS.

**Comment by oliviajain** [comment]
This can be resolved by adding the ngraph_DIR environment variable to the dockerfile. 

Please add this line
`ENV ngraph_DIR=${INTEL_OPENVINO_DIR}/deployment_tools/ngraph/cmake/`
and try building again.

**Comment by dipendra009** [comment]
Thank you, that solves the issue.
