### ISSUE TITLE
Cannot find entry point 'OrtGetApiBase'

### ISSUE THREAD

**Issue by PasIsa5960** [microsoft/onnxruntime#6908]
Hello,
When using ML.OnnxRuntime my code always returns the same error:

However I manage to use ML.OnnxRuntime in a very simple way and it works very well, here is the code that I use and which works:
`
using System;
using System.Collections.Generic;
using System.IO;
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;

namespace TestRN_Python
{
    class Program
    {
        private static InferenceSession session;
        private static IReadOnlyDictionary<string, NodeMetadata> inputMeta;
        private static List<NamedOnnxValue> container;
        static void Main(string[] args)
        {
            string modelPath = @"C:\Data\Test_RN\RN_Test_006.onnx";
            if (!File.Exists(modelPath))
                Console.WriteLine("Probleme : le fichier n'existe pas!");

            float[] inputsF = new float[] { -0.62f, -0.75f, -0.78f, -0.77f, -0.87f, -0.84f, -0.83f, -0.84f, -0.77f, -0.83f };

            //SessionOptions options = new SessionOptions();

            session = new InferenceSession(modelPath);
            inputMeta = session.InputMetadata;
            container = new List<NamedOnnxValue>();

            double[] test = Predicat(inputsF);
            Console.WriteLine(test[0].ToString() + " -  " + test[1].ToString());
            Console.ReadLine();
        }

        public static double[] Predicat(float[] table)
        {
            double[] resultats = new double[2];

            foreach (var name in inputMeta.Keys)
            {
                inputMeta[name].Dimensions[0] = 1;
                var tensor = new DenseTensor<float>(table, inputMeta[name].Dimensions);
                container.Add(NamedOnnxValue.CreateFromTensor<float>(name, tensor));
            }

            // Run the inference
            using (var results = session.Run(container))  // results is an IDisposableReadOnlyCollection<DisposableNamedOnnxValue> container
            {
                foreach (var r in results)
                {
                    for (int a = 0; a < 2; a++)
                    {
                         resultats[a] = Convert.ToDouble(r.AsTensor<float>().GetValue(a));
                    }
                }
            }
            return resultats;
        }
    }
}
`
But when I want to create a class that uses ML.OnnxRuntime, I fail to use it afterwards.
Here is the problematic code:
Class:
`
using System;
using System.Collections.Generic;
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;

namespace ClassManagerV01
{
    public class ManagerRN
    {
        public InferenceSession session1;
        public IReadOnlyDictionary<string, NodeMetadata> inputMeta1;
        public List<NamedOnnxValue> container1;

        public ManagerRN(string file)
        {
            session1 = new InferenceSession(file);
            inputMeta1 = session1.InputMetadata;
            container1 = new List<NamedOnnxValue>();
        }
        public double[] Predicat1(float[] table)
        {
            double[] resultats = new double[2];

            foreach (var name in inputMeta1.Keys)
            {
                inputMeta1[name].Dimensions[0] = 1;
                var tensor = new DenseTensor<float>(table, inputMeta1[name].Dimensions);
                container1.Add(NamedOnnxValue.CreateFromTensor<float>(name, tensor));
            }

            // Run the inference
            // results is an IDisposableReadOnlyCollection<DisposableNamedOnnxValue> container
            using (var results = session1.Run(container1))
            {
                foreach (var r in results)
                {
                    for (int a = 0; a < 2; a++)
                    {
                        resultats[a] = Convert.ToDouble(r.AsTensor<float>().GetValue(a));
                    }
                }
            }
            return resultats;
        }
    }
}
`
and the code that uses this class :

`
using System;
using System.IO;
using System.Threading.Tasks;
using ClassManagerV01;

namespace TestRN_onnx_V003
{
    class Program
    {
        static void Main(string[] args)
        {
            string modelPath = @"C:\Data\Test_RN\RN_Test_006.onnx";
            if (!File.Exists(modelPath))
                Console.WriteLine("Probleme : le fichier n'existe pas!");

            float[] inputsF = new float[] { -0.62f, -0.75f, -0.78f, -0.77f, -0.87f, -0.84f, -0.83f, -0.84f, -0.77f, -0.83f };

            ManagerRN RN = new ManagerRN(modelPath);

            double[] test = RN.Predicat1(inputsF);
            Console.WriteLine(test[0].ToString() + " -  " + test[1].ToString());
        }
    }
}

Error returned  : `
System.TypeInitializationException
  HResult=0x80131534
  Message=An exception was thrown by the type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods'. 
  Source=Microsoft.ML.OnnxRuntime
  Arborescence des appels de procédure :
   à Microsoft.ML.OnnxRuntime.SessionOptions..ctor() dans D:\a\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\SessionOptions.cs :ligne 50
   à Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath) dans D:\a\_work\1\s\csharp\src\Microsoft.ML.OnnxRuntime\InferenceSession.cs :ligne 46
   à ClassManagerV01.ManagerRN..ctor(String file) dans C:\Users\client\source\repos\ClassManagerV01\ClassManagerV01\ManagerRN.cs :ligne 17
   à TestRN_onnx_V003.Program.Main(String[] args) dans C:\Users\client\source\repos\TestRN_onnx_V003\TestRN_onnx_V003\Program.cs :ligne 19

Exception interne 1 :
EntryPointNotFoundException : Cannot find entry point 'OrtGetApiBase' in DLL 'onnxruntime'.

System information :
- OS Platform and Distribution : Windows 10 Professionnel
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.7.1
- Python version: 3.7
- Visual Studio version: Microsoft Visual Studio Community 2019 Version 16.8.5
- CUDA/cuDNN version:
- GPU model and memory: Intel(R) Core(TM) i5-4590 CPU / 16,0 Go ram

Could you help me resolder this problem?
Thank you in advance.

**Comment by hariharans29** [comment]
You have an older onnxruntime.dll possibly in c:\windows\system32 (that shipped with Windows itself) that is being loaded by your app. You need to ensure that the new onnxruntime.dll (in the nuget that you built from source) is loaded by your app (I think this is done by ensuring that the new dll is in the same folder as your .exe and that willensure that the .NET runtime will not have to look in the system paths to resolve its dependent dlls.)

**Comment by PasIsa5960** [comment]
Thank you for your reply.
I figured out the problem and after several tries I ended up installing the package in my app as well.
This way it works...
