### ISSUE TITLE
Tensor indexing issue

### ISSUE THREAD

**Issue by NicolasHug** [microsoft/onnxruntime#6910]
**Describe the bug**
It seems that tensor indexing is not fully supported

**Urgency**
Use case: https://github.com/pytorch/vision/pull/3426

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.7
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.7.0
- Python version: 3.8.8
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: None
- GPU model and memory: None

**To Reproduce**
```py
import io
import torch
from torch import Tensor
import onnxruntime

def f() -> Tensor:
    mask = torch.zeros(100, dtype=torch.bool)
    indices = (torch.rand(25) * mask.shape[0]).to(torch.int64)
    mask[indices] = True  # offending line
    return mask

class Module(torch.nn.Module):
    def forward(self, *args, **kwargs):
        return f()

model = Module()
model.eval()

model()  # works fine

onnx_io = io.BytesIO()
torch.onnx.export(model, [], onnx_io, opset_version=11)

ort_session = onnxruntime.InferenceSession(onnx_io.getvalue())
ort_outs = ort_session.run(None, {})  # errors
```

```
/Users/nicolashug/opt/miniconda3/envs/pt/lib/python3.8/site-packages/torch/onnx/utils.py:347: UserWarning: No input args
  warnings.warn("No input args")
2021-03-05 14:58:13.338019 [E:onnxruntime:, inference_session.cc:1293 operator()] Exception during initialization: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:43 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape &, std::vector<int64_t> &) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{}, requested shape:{25}

Traceback (most recent call last):
  File "lol.py", line 24, in <module>
    ort_session = onnxruntime.InferenceSession(onnx_io.getvalue())
  File "/Users/nicolashug/opt/miniconda3/envs/pt/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 280, in __init__
    self._create_inference_session(providers, provider_options)
  File "/Users/nicolashug/opt/miniconda3/envs/pt/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 312, in _create_inference_session
    sess.initialize_session(providers, provider_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:43 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape &, std::vector<int64_t> &) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{}, requested shape:{25}
```

It seems to work fine when replacing `indices = torch.as_tensor([1, 2, 3]).to(torch.int64)`

**Additional context**

That's not exactly the issue encountered https://github.com/pytorch/vision/pull/3426, I tried to find a minimal reproducing example so the actual error messages differ.

CC @fmassa

**Comment by hariharans29** [comment]
Not sure how the exported models differ with/without the offending line. This seems like something to bring to the attention of the Torch exporter project perhaps. 

"
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:43 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape &, std::vector<int64_t> &) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{}, requested shape:{25}"

All this line is telling you is that somewhere in the broken model there is a request to reshape a scalar (shape: {}) to a 1-D tensor (shape: {25}) which is of course not possible and hence the complaint from ORT when trying to load the model.

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features or fix complex issues.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html)
