### ISSUE TITLE
Error(s) building ORT 1.7.1 with CUDA and TensorRT from source

### ISSUE THREAD

**Issue by erd9** [microsoft/onnxruntime#6927]
**Describe the bug**

Been trying to build ORT with CUDA and TRT but been getting the error below. I think I've followed the build ORT from source instruction and I believe I've met all the prerequisites. I can run the onnxruntime-gpu python module with same config with no issues. 

Traceback (most recent call last):
  File "C:\onnxruntime\\tools\ci_build\build.py", line 2003, in <module>
    sys.exit(main())
  File "C:\onnxruntime\\tools\ci_build\build.py", line 1938, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "C:\onnxruntime\\tools\ci_build\build.py", line 1017, in build_targets
    run_subprocess(cmd_args, env=env)
  File "C:\onnxruntime\\tools\ci_build\build.py", line 536, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\onnxruntime\tools\python\util\run.py", line 44, in run
    env=env, shell=shell)
  File "C:\Users\Laptop1\Anaconda3\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin\\cmake.EXE', '--build', 'C:\\onnxruntime\\\\build\\Windows\\Release', '--config', 'Release', '--', '/maxcpucount:12', '/nodeReuse:False']' returned non-zero exit status 1.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.7.1
- Python version: 3.7.10
- Visual Studio version (if applicable): VS19 - 16.9.0
- GCC/Compiler version (if compiling from source):
- CUDA version: 11.0.2
- cuDNN version: 8.0.5.39
- GPU model and memory: 2070 MaxQ 8GB

**To Reproduce**

.\build.bat --parallel --config Release --build_wheel --cuda_version 11.0 --cudnn_home "C:\cuDNN\cudnn-11.0-windows-x64-v8.0.5.39\cuda" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0" --use_tensorrt --tensorrt_home "C:\TensorRT\TensorRT-7.1.3.4" --cmake_generator "Visual Studio 16 2019" --update --build

**Expected behavior**
Successful build.

**Screenshots**
See attached build log. 
[build log.txt](https://github.com/microsoft/onnxruntime/files/6098215/build.log.txt)

**Additional context**
I've also been getting these error messages during build:

C:/onnxruntime/onnxruntime/core/providers/cuda/object_detection/roialign_impl.cu(131): error : calling a __host__ function("__ceilf") from a __global__ func
tion("onnxruntime::cuda::RoIAlignForward<float> ") is not allowed [C:\onnxruntime\build\Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/object_detection/roialign_impl.cu(131): error : identifier "__ceilf" is undefined in device code [C:\onnxrunt
ime\build\Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/object_detection/roialign_impl.cu(134): error : calling a __host__ function("__ceilf") from a __global__ func
tion("onnxruntime::cuda::RoIAlignForward<float> ") is not allowed [C:\onnxruntime\build\Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/object_detection/roialign_impl.cu(134): error : identifier "__ceilf" is undefined in device code [C:\onnxrunt
ime\build\Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.0.targets(772,9): error MSB3721: The com
mand ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\nvcc.exe" -gencode=arch=compute_37,code=\"sm_37,compute_37\" -gencode=arch=compute_50,co
de=\"sm_50,compute_50\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_70,code=
\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" -gencode=arch=compute_80,code=\"sm_80,compute_80\" --use-local-env -ccbin "C:\Progra
m Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64" -x cu   -IC:\onnxruntime\include\onnxruntime -IC:\onnxruntim
e\include\onnxruntime\core\session -IC:\onnxruntime\cmake\external\SafeInt -I"C:\onnxruntime\cmake\external\optional-lite\include" -IC:\onnxruntime\cmake\ex
ternal\mp11\include -IC:\onnxruntime\build\Windows\Release -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -IC:\onnxruntime\cmake\exter
nal\onnx -IC:\onnxruntime\build\Windows\Release\external\onnx -IC:\onnxruntime\cmake\external\protobuf\src -IC:\onnxruntime\cmake\external\flatbuffers\inclu
de -IC:\onnxruntime\onnxruntime -I"C:\cuDNN\cudnn-11.0-windows-x64-v8.0.5.39\cuda\include" -IC:\onnxruntime\cmake\external\eigen -IC:\onnxruntime\cmake\exte
rnal\protobuf -IC:\onnxruntime\onnxruntime\..\cmake\external\onnx -I"C:\onnxruntime\onnxruntime\..\cmake\external\onnx-tensorrt" -I"C:\TensorRT\TensorRT-7.1
.3.4\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudar
t shared --expt-relaxed-constexpr --Werror default-stream-launch -Xcudafe --diag_suppress=bad_friend_decl -Xcudafe --diag_suppress=unsigned_compare_with_zer
o -Xcudafe --diag_suppress=expr_has_no_effect -std=c++14 -Xcompiler="-Ob2 /guard:cf /Qspectre /wd4127 /wd4251 /wd4201 /WX /wd4834 /wd4127 /utf-8 /sdl"    -D
NDEBUG -DEIGEN_USE_THREADS -DONNX_NAMESPACE=onnx -DONNX_ML=1 -DENABLE_ORT_FORMAT_LOAD -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CONSTEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES
 -DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11_ATOMIC -DEIGEN_STRONG_INLINE=inline -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -DUSE_CUDA=1 -DUSE_T
ENSORRT=1 -D_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING=1 -DWINVER=0x0601 -D"CMAKE_INTDIR=\"Release\"" -DWIN32 -D_WINDOWS -DEIGEN_HAS_C99_MATH -DND
EBUG -DGSL_UNENFORCED_ON_CONTRACT_VIOLATION -DEIGEN_USE_THREADS -DONNX_NAMESPACE=onnx -DONNX_ML=1 -DENABLE_ORT_FORMAT_LOAD -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CON
STEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES -DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11_ATOMIC -DEIGEN_STRONG_INLINE=inline -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_
USE_MATH_DEFINES -DUSE_CUDA=1 -DUSE_TENSORRT=1 -D_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING=1 -DWINVER=0x0601 -D"CMAKE_INTDIR=\"Release\"" -D_MBCS
 -Xcompiler "/EHsc /W3 /nologo /O2 /Fdonnxruntime_providers_cuda.dir\Release\onnxruntime_providers_cuda.pdb /FS /Zi  /MD /GR" -o onnxruntime_providers_cuda.
dir\Release\roialign_impl.obj "C:\onnxruntime\onnxruntime\core\providers\cuda\object_detection\roialign_impl.cu"" exited with code 1. [C:\onnxruntime\build\
Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(538): error : calling a __host__ function("__floorf") from a __global__ function("onnxr
untime::cuda::_ResizeCubicCoordinateMapping<float> ") is not allowed [C:\onnxruntime\build\Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(538): error : identifier "__floorf" is undefined in device code [C:\onnxruntime\build\W
indows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(538): error : calling a __host__ function("__floorf") from a __global__ function("onnxr
untime::cuda::_ResizeCubicCoordinateMapping<double> ") is not allowed [C:\onnxruntime\build\Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(538): error : identifier "__floorf" is undefined in device code [C:\onnxruntime\build\W
indows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(538): error : calling a __host__ function("__floorf") from a __global__ function("onnxr
untime::cuda::_ResizeCubicCoordinateMapping<    ::__half> ") is not allowed [C:\onnxruntime\build\Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(538): error : identifier "__floorf" is undefined in device code [C:\onnxruntime\build\W
indows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(538): error : calling a __host__ function("__floorf") from a __global__ function("onnxr
untime::cuda::_ResizeCubicCoordinateMapping<int> ") is not allowed [C:\onnxruntime\build\Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(538): error : identifier "__floorf" is undefined in device code [C:\onnxruntime\build\W
indows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(538): error : calling a __host__ function("__floorf") from a __global__ function("onnxr
untime::cuda::_ResizeCubicCoordinateMapping<unsigned char> ") is not allowed [C:\onnxruntime\build\Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(538): error : identifier "__floorf" is undefined in device code [C:\onnxruntime\build\W
indows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(13): error : calling a __host__ function("__ceilf") from a __device__ function("onnxrun
time::cuda::NearestPixel_SIMPLE") is not allowed [C:\onnxruntime\build\Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(13): error : identifier "__ceilf" is undefined in device code [C:\onnxruntime\build\Win
dows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(21): error : calling a __host__ function("__floorf") from a __device__ function("onnxru
ntime::cuda::NearestPixel_ROUND_PREFER_FLOOR") is not allowed [C:\onnxruntime\build\Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(21): error : identifier "__floorf" is undefined in device code [C:\onnxruntime\build\Wi
ndows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(23): error : calling a __host__ function("__roundf") from a __device__ function("onnxru
ntime::cuda::NearestPixel_ROUND_PREFER_FLOOR") is not allowed [C:\onnxruntime\build\Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(23): error : identifier "__roundf" is undefined in device code [C:\onnxruntime\build\Wi
ndows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(27): error : calling a __host__ function("__roundf") from a __device__ function("onnxru
ntime::cuda::NearestPixel_ROUND_PREFER_CEIL") is not allowed [C:\onnxruntime\build\Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(27): error : identifier "__roundf" is undefined in device code [C:\onnxruntime\build\Wi
ndows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(31): error : calling a __host__ function("__floorf") from a __device__ function("onnxru
ntime::cuda::NearestPixel_FLOOR") is not allowed [C:\onnxruntime\build\Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(31): error : identifier "__floorf" is undefined in device code [C:\onnxruntime\build\Wi
ndows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(35): error : calling a __host__ function("__ceilf") from a __device__ function("onnxrun
time::cuda::NearestPixel_CEIL") is not allowed [C:\onnxruntime\build\Windows\Release\onnxruntime_providers_cuda.vcxproj]

C:/onnxruntime/onnxruntime/core/providers/cuda/tensor/resize_impl.cu(35): error : identifier "__ceilf" is undefined in device code [C:\onnxruntime\build\Win
dows\Release\onnxruntime_providers_cuda.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.0.targets(772,9): error MSB3721: The com
mand ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\nvcc.exe" -gencode=arch=compute_37,code=\"sm_37,compute_37\" -gencode=arch=compute_50,co
de=\"sm_50,compute_50\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" -gencode=arch=compute_60,code=\"sm_60,compute_60\" -gencode=arch=compute_70,code=
\"sm_70,compute_70\" -gencode=arch=compute_75,code=\"sm_75,compute_75\" -gencode=arch=compute_80,code=\"sm_80,compute_80\" --use-local-env -ccbin "C:\Progra
m Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64" -x cu   -IC:\onnxruntime\include\onnxruntime -IC:\onnxruntim
e\include\onnxruntime\core\session -IC:\onnxruntime\cmake\external\SafeInt -I"C:\onnxruntime\cmake\external\optional-lite\include" -IC:\onnxruntime\cmake\ex
ternal\mp11\include -IC:\onnxruntime\build\Windows\Release -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include" -IC:\onnxruntime\cmake\exter
nal\onnx -IC:\onnxruntime\build\Windows\Release\external\onnx -IC:\onnxruntime\cmake\external\protobuf\src -IC:\onnxruntime\cmake\external\flatbuffers\inclu
de -IC:\onnxruntime\onnxruntime -I"C:\cuDNN\cudnn-11.0-windows-x64-v8.0.5.39\cuda\include" -IC:\onnxruntime\cmake\external\eigen -IC:\onnxruntime\cmake\exte
rnal\protobuf -IC:\onnxruntime\onnxruntime\..\cmake\external\onnx -I"C:\onnxruntime\onnxruntime\..\cmake\external\onnx-tensorrt" -I"C:\TensorRT\TensorRT-7.1
.3.4\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudar
t shared --expt-relaxed-constexpr --Werror default-stream-launch -Xcudafe --diag_suppress=bad_friend_decl -Xcudafe --diag_suppress=unsigned_compare_with_zer
o -Xcudafe --diag_suppress=expr_has_no_effect -std=c++14 -Xcompiler="-Ob2 /guard:cf /Qspectre /wd4127 /wd4251 /wd4201 /WX /wd4834 /wd4127 /utf-8 /sdl"    -D
NDEBUG -DEIGEN_USE_THREADS -DONNX_NAMESPACE=onnx -DONNX_ML=1 -DENABLE_ORT_FORMAT_LOAD -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CONSTEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES
 -DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11_ATOMIC -DEIGEN_STRONG_INLINE=inline -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_USE_MATH_DEFINES -DUSE_CUDA=1 -DUSE_T

ENSORRT=1 -D_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING=1 -DWINVER=0x0601 -D"CMAKE_INTDIR=\"Release\"" -DWIN32 -D_WINDOWS -DEIGEN_HAS_C99_MATH -DND
EBUG -DGSL_UNENFORCED_ON_CONTRACT_VIOLATION -DEIGEN_USE_THREADS -DONNX_NAMESPACE=onnx -DONNX_ML=1 -DENABLE_ORT_FORMAT_LOAD -DEIGEN_MPL2_ONLY -DEIGEN_HAS_CON
STEXPR -DEIGEN_HAS_VARIADIC_TEMPLATES -DEIGEN_HAS_CXX11_MATH -DEIGEN_HAS_CXX11_ATOMIC -DEIGEN_STRONG_INLINE=inline -DPLATFORM_WINDOWS -DNOGDI -DNOMINMAX -D_
USE_MATH_DEFINES -DUSE_CUDA=1 -DUSE_TENSORRT=1 -D_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING=1 -DWINVER=0x0601 -D"CMAKE_INTDIR=\"Release\"" -D_MBCS
 -Xcompiler "/EHsc /W3 /nologo /O2 /Fdonnxruntime_providers_cuda.dir\Release\onnxruntime_providers_cuda.pdb /FS /Zi  /MD /GR" -o onnxruntime_providers_cuda.
dir\Release\resize_impl.obj "C:\onnxruntime\onnxruntime\core\providers\cuda\tensor\resize_impl.cu"" exited with code 1. [C:\onnxruntime\build\Windows\Releas
e\onnxruntime_providers_cuda.vcxproj]

**Comment by stevenlix** [comment]
If you use TRT package TensorRT-7.1.3.4.Windows10.x86_64.**cuda-11.0.cudnn8.0**.zip, please install cudnn8.0. The versions of CUDA/CUDNN must match with TRT package as specified in the package name. If possible, I would suggest to use TRT7.2.2, which has been supported in ORT1.7.

**Comment by chenfucn** [comment]
Facing the same error without compiling tensorrt. build command used:

.\build.bat --config Debug --build_shared_lib --parallel --enable_training --use_cuda --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2" --cmake_generator "Visual Studio 16 2019"

**Comment by erd9** [comment]
I tried it without --use_tensorrt and got the same error.

.\build.bat --parallel --config Release --build_wheel --cuda_version 11.0 --cudnn_home "C:\cuDNN\cudnn-11.0-windows-x64-v8.0.5.39\cuda" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0" --cmake_generator "Visual Studio 16 2019" --update --build

**Comment by chenfucn** [comment]
[resize_impl.cu257113780.deps.txt](https://github.com/microsoft/onnxruntime/files/6104568/resize_impl.cu257113780.deps.txt)
from the deps file I found, it appears that the MSVC header files are on the top, so the ceil() floor() calls are translated to windows SDK functions. But they should be cuda functions. 

is this a build.py script error?

**Comment by HectorSVC** [comment]
1. It worked for me without any issue. I checked my environment. I have VS 16.7 + MSVC toolset v14.27.
2. I upgraded to VS 16.9, and can repo this issue. For VS 16.9 the default VC toolset is 14.28. So I re-installed MSVC V142 - VS 2019 C++ X64/X86 build tools (v14.27). It worked after force the toolset version to 14.27 by setting --msvc_toolset=14.27 in build command.
Please install MSVC toolset v14.27:
in Apps & Features -> find Microsoft Visual Studio Installer -> click Modify -> Choose 2019 Modify if you have multiple version -> Individual Components -> MSVC V142 - VS 2019 C++ X64/X86 build tools (v14.27), check it and install
 in your build command add: --msvc_toolset=14.27
