### ISSUE TITLE
Question: how to query the ONNX opset version from headers ?

### ISSUE THREAD

**Issue by boxerab** [microsoft/onnxruntime#6935]
Hello,
I am using onnxruntime in a C++ application, so I link directly to .so library and include
the header files. Is there a way of querying the `opset` version  ?
Thanks!

**Comment by boxerab** [comment]
Thanks. Yes, the opset version of the model would be perfect.

**Comment by HectorSVC** [comment]
That's part of Onnx spec, in the ModelProto. Please check out some docks:
https://github.com/onnx/onnx/blob/master/docs/VersionConverter.md
https://github.com/onnx/onnx/blob/master/docs/Versioning.md

**Comment by boxerab** [comment]
Thanks, @HectorSVC . I looked at the docs. Can you share an example from the C++ API for how I can query the opset
version from a session ?
