### ISSUE TITLE
Error(s) building ORT 1.7.0 with TensorRT from source component

### ISSUE THREAD

**Issue by KnightYao** [microsoft/onnxruntime#6953]
When I building ORT 1.7.0 with TensorRT from source component, it was error when build,
![image](https://user-images.githubusercontent.com/9350796/110428826-e81c4e00-80e4-11eb-8168-ff0e15528df0.png)
But when I building ORT with CUDA from source, it correct, what should i do for this building error.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CenterOS7
- ONNX Runtime installed from (source or binary):source
- ONNX Runtime version: 1.7.0
- Python version:3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):5.4
- CUDA/cuDNN version:cuda-10.1 cudnn-7.6.5
- GPU model and memory:22G

**Comment by HectorSVC** [comment]
What's the TensorRT version you are using?
We are using TensorRT 7.1.3.4 + CUDA 11.0 now.

**Comment by stevenlix** [comment]
cuda-10.1 cudnn-7.6.5 is probably too old. I don't think TRT support cuda10.1. Please make sure CUDA/CuDNN version matches with TRT package (all the versions are specified in TRT package name). For ORT1.7, better to use TRT7.2.2, CUDA11 and CuDNN8

**Comment by KnightYao** [comment]
Thanks a lot, last time I use Tensorrt is 7.2, now I try to use Tensorrt 7.1.3.4 is well be ok.
