### ISSUE TITLE
Building from source Failed.

### ISSUE THREAD

**Issue by ghostplant** [Microsoft/onnxruntime#697]
Not able to build the onnxruntime from source **correctly** according to the guide from documentation.

```sh
root@localhost:~/onnx_test/onnxruntime# ./build.sh --config RelWithDebInfo --build_wheel
...
...
...

100% tests passed, 0 tests failed out of 4

Total Test time (real) =   8.20 sec
2019-03-23 23:03:30,458 Build [DEBUG] - Running subprocess in '/home/a/onnx_test/onnxruntime/build/Linux/RelWithDebInfo'
['/usr/bin/python3', 'onnxruntime_test_python.py']
......................
----------------------------------------------------------------------
Ran 22 tests in 0.009s

OK
2019-03-23 23:03:30,757 Build [DEBUG] - Running subprocess in '/home/a/onnx_test/onnxruntime/build/Linux/RelWithDebInfo'
['/usr/bin/python3', 'onnxruntime_test_python_backend.py']
..E
======================================================================
ERROR: testRunModelProto (__main__.TestBackend)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "onnxruntime_test_python_backend.py", line 50, in testRunModelProto
    rep = backend.prepare(model)
  File "/home/a/onnx_test/onnxruntime/build/Linux/RelWithDebInfo/onnxruntime/backend/backend.py", line 75, in prepare
    check_model(model)
  File "/usr/local/lib/python3.5/dist-packages/onnx-1.4.1-py3.5-linux-x86_64.egg/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized type value case (value_info name: probabilities): 0

----------------------------------------------------------------------
Ran 3 tests in 0.004s

FAILED (errors=1)
Traceback (most recent call last):
  File "/home/a/onnx_test/onnxruntime/tools/ci_build/build.py", line 721, in <module>
    sys.exit(main())
  File "/home/a/onnx_test/onnxruntime/tools/ci_build/build.py", line 691, in main
    run_onnxruntime_tests(args, source_dir, ctest_path, build_dir, configs, args.enable_pybind, args.use_tvm, args.use_tensorrt)
  File "/home/a/onnx_test/onnxruntime/tools/ci_build/build.py", line 495, in run_onnxruntime_tests
    run_subprocess([sys.executable, 'onnxruntime_test_python_backend.py'], cwd=cwd, dll_path=dll_path)
  File "/home/a/onnx_test/onnxruntime/tools/ci_build/build.py", line 165, in run_subprocess
    return subprocess.run(args, cwd=cwd, check=True, stdout=stdout, stderr=stderr, env=my_env, shell=shell)
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'onnxruntime_test_python_backend.py']' returned non-zero exit status 1
```

**Comment by ghostplant** [comment]
Can you provide a **REPRODUCIBLE** Dockerfile that builds onnxruntime from source?
I got quantities of building errors according the building steps the documentation provides.

**Comment by ghostplant** [comment]
Got a different error for a refresh rebuild on another host, without any configure differences with the above build.

```sh
1:
1: [----------] Global test environment tear-down
1: [==========] 964 tests from 107 test cases ran. (5652 ms total)
1: [  PASSED  ] 963 tests.
1: [  FAILED  ] 1 test, listed below:
1: [  FAILED  ] ContribOpTest.StringNormalizerTest
1:
1:  1 FAILED TEST
1:   YOU HAVE 1 DISABLED TEST
1:
1/4 Test #1: onnxruntime_test_all ................................................***Failed    5.74 sec
test 2
    Start 2: onnxruntime_test_framework_session_without_environment_standalone

2: Test command: /root/onnxruntime/build/Linux/RelWithDebInfo/onnxruntime_test_framework_session_without_environment_standalone "--gtest_output=xml:/root/onnxruntime/build/Linux/RelWit$
DebInfo/onnxruntime_test_framework_session_without_environment_standalone.RelWithDebInfo.results.xml"
```

**Comment by snnn** [comment]
The StringNormalizerTest test failure is a known issue. Please upgrade your visual studio to the latest version.
You didn't get the earlier error may because on this host you didn't install onnx python package.

**Comment by yuslepukhin** [comment]
`ContribOpTest.StringNormalizerTest` is a c++ unit test and the output of it is not included into the above. If you could scroll up and see the actual failure it'd be helpful.

**Comment by skottmckay** [comment]
> `ContribOpTest.StringNormalizerTest` is a c++ unit test and the output of it is not included into the above. If you could scroll up and see the actual failure it'd be helpful.

Alternatively you can run the test more directly

/root/onnxruntime/build/Linux/RelWithDebInfo/onnxruntime_test_framework_session_without_environment_standalone --gtest_filter=ContribOpTest.StringNormalizerTest

**Comment by shawncal** [comment]
I got the same error when cross-compiling for armv7. After running `./ build.sh --update --build`, the tests still ran (though I don't know why, since I didn't request them with the `--test` flag), and the whole build stopped after this test failure:
`: [==========] 955 tests from 105 test cases ran. (6951 ms total)
1: [  PASSED  ] 953 tests.
1: [  FAILED  ] 2 tests, listed below:
1: [  FAILED  ] ContribOpTest.StringNormalizerTest
1: [  FAILED  ] ActivationOpTest.Softsign
1:
1:  2 FAILED TESTS
1/5 Test #1: onnxruntime_test_all ................................................***Failed    7.36 sec`

Apologies -  that's the only part of the log I saved.

I was able to circumvent the tests by passing `--arm` flag, which flips the args.test bit to False.

**Comment by pranavsharma** [comment]
@ghostplant can you provide the full build log? Also, it's been 18 days since you filed this. Can you check if the latest master also has the same issue; I highly doubt it. Plus please include information about the platform/OS/architecture you're building on. Thanks!

**Comment by snnn** [comment]
Hi @pranavsharma , sometimes, the bug is in ONNX, not onnxruntime.  Especially if the model can not pass model checker.

**Comment by steeler18** [comment]
I built from the source and also got StringNormalizerTest failure. I went ahead to disable that test and got the python package, which seems working fine.
