### ISSUE TITLE
in window ,onnxruntime and use_dml build,

### ISSUE THREAD

**Issue by wwbnjsace** [microsoft/onnxruntime#6970]
in window environment,is build onnxruntime with --use_dml,my command is "
.\build.bat --update --build --build_shared_lib --build_wheel --config RelWithDebInfo --use_dml --cmake_generator "Visual Studio 16 2019"  --parallel --skip_tests".
in the end ,the build is successful，the whl file is generated. then pip3 install *.whl .so i can use python to inference.but an error happend.
my code is "session_1 = onnxruntime.InferenceSession(model_path,options)"
the error is 
"2021-03-10 19:03:59.3618026 [W:onnxruntime:, inference_session.cc:411 onnxruntime::InferenceSession::RegisterExecutionProvider] Having memory pattern enabled is not supported while using the DML Execution Provider. So disabling it for this session since it uses the DML Execution Provider."
and the inference time is very long .
who can tell me why?

**Comment by fdwr** [comment]
@wwbnjsace: Did you call DisableMemPattern first? (I'm not sure what the Python call would look like, but in C it would be `g_ort->DisableMemPattern(m_session_opts);`). The documentation mentions it here: https://www.onnxruntime.ai/docs/reference/execution-providers/DirectML-ExecutionProvider.html#onnx-opset-support

**Comment by jszhtian** [comment]
Looks you need disable the memory pattern.
In python, you can set this by using SessionOptions().
This is an example
'''python
so = ort.SessionOptions()
so.enable_mem_pattern=False
sess = ort.InferenceSession("Model_File_Name.onnx",so)
'''
