### ISSUE TITLE
Enable signed int8 activation type in static quantization, add option for not symmetrizing calibration data

### ISSUE THREAD

**Issue by SilvanK4t1qbit** [microsoft/onnxruntime#6972]
**Is your feature request related to a problem? Please describe.**

`onnxruntime.quantization.quantize_static` currently doesn't support signed int8 as activation type. This is an issue for hardware that only supports signed int8 and not uint8. It seems like everything is in place to support int8 though. Enabling int8 seems to be a matter of just removing the following exception:

https://github.com/microsoft/onnxruntime/blob/acfe7ac4cebf313662f396faacd93e2115bad8fb/onnxruntime/python/tools/quantization/quantize.py#L183-L184

Furthermore, it would be great to have the option **not** to symmetrize the input calibration data around zero, which currently happens here:

https://github.com/microsoft/onnxruntime/blob/f723ff2285bdfbcad23f804aba470b8b6d4d1882/onnxruntime/python/tools/quantization/quant_utils.py#L112-L115

In cases where both `rmin` and `rmax` are positive, setting 'scale=(rmax-rmin)/quant_range' and choosing the zero point accordingly would give a full additional bit of precision compared to the current version. I have the alternative version of this function coded up and would be more than happy to contribute it.

**System information**
- ONNX Runtime version (you are using): 1.7.0

**Describe the solution you'd like**

- Enable static quantization with signed int8 activation type
- Provide option to not symmetrize calibration data

**Comment by pranav-prakash** [comment]
Fwiw I've been using int8 quantization for some time, and can confirm that it works with one single caveat that currently Relu doesn't properly handle symmetric int8 types. I'd been using my own Relu type since up until a few weeks ago ONNX didn't have int8 support in the relu schema, but I recently submitted a PR to them to add that.

**Comment by yufenglee** [comment]
@SilvanK4t1qbit , you're very welcome to make to PR and contribute. Thanks!

**Comment by SilvanK4t1qbit** [comment]
@yufenglee , I submitted a pull request for the features requested in this issue. Please let me know if you have any comments and suggestions!
