### ISSUE TITLE
Is TVMKernel working for onnx examples?

### ISSUE THREAD

**Issue by ghostplant** [Microsoft/onnxruntime#698]
There is `--use_tvm` option for building the onnxruntime. However, is it working for ONNX inference now? What is the way to enable it for ONNX apps?

**Comment by snnn** [comment]
Not yet.

**Comment by ghostplant** [comment]
@snnn Also confused about tensorRT, is it possible for onnxruntime to **use cuda/cublas/cudnn only without using tensorRT** to execute DNN graph applications? I don't have tensorRT installed on my CUDA 10.0 host.

**Comment by snnn** [comment]
Sure. it's supported. Please check https://github.com/Microsoft/onnxruntime/blob/master/tools/ci_build/build.py

You should pass in: --use_cuda, --cuda_version,--cuda_home,--cudnn_home
