### ISSUE TITLE
Multiple InferenceSessions lead to unspecified launch Error

### ISSUE THREAD

**Issue by marcown** [microsoft/onnxruntime#6986]
**Describe the bug**

Hi there,

I am running into the following problem when using 18 Models in sequential order but multiple threads (using locks) in c++:

```
2021-03-11 22:40:16.3466051 [E:onnxruntime:Evaluation, cuda_call.cc:119 onnxruntime::CudaCall] CUDA failure 719: unspecified launch failure ; GPU=0 ; hostname=XXXX ; expr=cudaMemcpyAsync(dst_data, src_data, bytes, cudaMemcpyDeviceToHost, GetStream(kCudaStreamDefault));
2021-03-11 22:40:16.3620872 [E:onnxruntime:Evaluation, cuda_call.cc:119 onnxruntime::CudaCall] CUDA failure 719: unspecified launch failure ; GPU=0 ; hostname=XXXX ; expr=cudaEventRecord(current_deferred_release_event, static_cast<cudaStream_t>(GetComputeStream()));
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.7.1
- Python version: 3.8
- CUDA/cuDNN version: 11.0
- GPU model and memory: RTX 3060 TI

**To Reproduce**

It is difficult to reproduce, because it just happens every 2 to 12 hours when using a lot of models.

I copy the data (every model is using the same data as input) using an memory_allocator and cudaMemcpy like this

```c++
input_data[k] = memory_allocator.Alloc(sizeof(float) * input_tensor_size);
cudaMemcpy(input_data[k], reshaped.data, sizeof(float) * input_tensor_size, cudaMemcpyHostToDevice);
```

then there is a for_each(execution::par, active_models.begin(), active_models.end(), [&](auto&& ii) { ... } loop using locks to block parallel execution of onnxruntime sessions but to allow parallel postprocessing (no cuda, everything on cpu)

in the for loop the input tensor is created like this 

```c++
Ort::Value input_tensor = Ort::Value::CreateTensor<float>(memory_allocator.GetInfo(), reinterpret_cast<float*>(input_data[k]), input_tensor_size, input_node_dims.data(), 4);
```

and session run like this

```c++
output_tensors[k] = session_ptr->Run(Ort::RunOptions{nullptr}, input_node_names.data(), &input_tensor, num_input_nodes, output_node_names.data(), num_output_nodes);
```

The models are run every 500ms and have a total inference time of 250ms.

Do you have any idea what is going wrong here?

**Comment by snnn** [comment]
You have multiple inference sessions in the same process?
