### ISSUE TITLE
Error when building for Android armeabi-v7a api level 16: "use of undeclared identifier 'nftw'"

### ISSUE THREAD

**Issue by Linux13524** [microsoft/onnxruntime#6996]
**Describe the bug**
Cannot build latest version for android armeabi-v7a api 16.  For api 21 the build succeeds. The error message is:

```
/work/onnxruntime/core/platform/posix/env.cc:378:25: error: use of undeclared identifier 'nftw'
    const auto result = nftw(
                        ^
1 error generated.
CMakeFiles/onnxruntime_common.dir/build.make:263: recipe for target 'CMakeFiles/onnxruntime_common.dir/work/onnxruntime/core/platform/posix/env.cc.o' failed
```

**System information**
- OS Platform and Distribution: ubuntu:bionic
- ONNX Runtime installed from: source
- ONNX Runtime version: v1.7.1
- Python version: 3.7.5
- GCC/Compiler version: 
Android (5058415 based on r339409) clang version 8.0.2
Target: armv7a-unknown-linux-android16
Thread model: posix
InstalledDir: /android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin

**To Reproduce**
I run the build based on the `conanio/android-clang8-armv7` docker image with pre-installed Android NDK r19c:

```
export CC=""
export CXX=""
./build.sh --parallel --config Release --build_dir build --android --android_abi armeabi-v7a --android_api 16 --android_ndk_path /android-ndk-r19c --android_sdk_path None
```

**Expected behavior**
A succesfull build

**Comment by gwang-msft** [comment]
Unfortunately, the lowest Android API level we support is 21.

**Comment by Linux13524** [comment]
I see. Thanks for clarification!
