### ISSUE TITLE
Failed to build ORT with option '--enable_training' and '--x86' for Windows

### ISSUE THREAD

**Issue by slhack** [microsoft/onnxruntime#7009]
**Describe the bug**
Hi I was trying to build x86 version of Onnxruntime with training. However I got bunch of errors and warnings like C2220, C4224, C4125. Without '--enable_training' everything works fine.
 Here's the command I used: H:\onnxruntime>build.bat --skip_submodule_sync --config RelWithDebInfo --build_shared_lib --parallel --cmake_generator "Visual Studio 16 2019" --enable_training --x86
[log.txt](https://github.com/microsoft/onnxruntime/files/6136327/log.txt)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 1903
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.7.0
- Python version: 3.7.3
- Visual Studio version (if applicable): Visual Studio 16 2019
- GCC/Compiler version (if compiling from source): MSVC v142
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- run this on Win10: build.bat --skip_submodule_sync --config RelWithDebInfo --build_shared_lib --parallel --cmake_generator "Visual Studio 16 2019" --enable_training --x86

**Expected behavior**
A successful build.

**Comment by askhade** [comment]
@slhack: Can you paste the error messages

**Comment by slhack** [comment]
See log.txt above

**Comment by slhack** [comment]
> @slhack: Can you paste the error messages

See log.txt above

**Comment by baijumeswani** [comment]
Closing this since it is quite old now. We should now be able to build for windows. Please try and let me know if you still encounter build failures.
