### ISSUE TITLE
Support for SSE/AVX instructions

### ISSUE THREAD

**Issue by dmirecki** [microsoft/onnxruntime#7010]
Does onnxruntime support SSE4/AVX512 instructions? If yes, does the python package in pip support those instructions? How to build the python package with those instructions? It would be nice to add information about that to onnxruntime documentation.

Thanks in advance for the response!

**Comment by askhade** [comment]
@dmirecki : Can you elaborate your scenario specifically what kind of models are you planning to use vision, nlp and are you targeting fp32 or planning to quantize the models?

ORT does have support for AVX512. The right instructions in ort are chosen based on the hardware you are running on... you don't have to specify any options during build time.

**Comment by dmirecki** [comment]
Thank you for your response!

I'm planning to deploy vision model with fp32 and I'm researching ways to get the best possible performance.

**Comment by LY000001** [comment]
> @dmirecki : Can you elaborate your scenario specifically what kind of models are you planning to use vision, nlp and are you targeting fp32 or planning to quantize the models?
> 
> ORT does have support for AVX512. The right instructions in ort are chosen based on the hardware you are running on... you don't have to specify any options during build time.

@ @askhade : How do I turn this option off in Intel cpu? can this avx512 option be turnd off on a intel cpu that suppport avx512?

**Comment by sikandermukaram** [comment]
> > [@dmirecki](https://github.com/dmirecki) : Can you elaborate your scenario specifically what kind of models are you planning to use vision, nlp and are you targeting fp32 or planning to quantize the models?
> > ORT does have support for AVX512. The right instructions in ort are chosen based on the hardware you are running on... you don't have to specify any options during build time.
> 
> @ [@askhade](https://github.com/askhade) : How do I turn this option off in Intel cpu? can this avx512 option be turnd off on a intel cpu that suppport avx512?

were you able to find a way to turn off avx512 option?
