### ISSUE TITLE
Exception thrown in allocation planner: accessing index -1 of ort_value_info_

### ISSUE THREAD

**Issue by pranav-prakash** [microsoft/onnxruntime#7020]
**Describe the bug**
The following exception gets thrown in the allocation planner when initializing the session to run a quantized mask-rcnn model:
```
Exception during initialization: /home/centos/onnxruntime-riscv/onnxruntime/core/framework/allocation_planner.cc:191 int& onnxruntime::PlannerImpl::UseCount(onnxruntime::OrtValueIndex) n >= 0 && static_cast<size_t>(n) < ort_value_info_.size() was false. 
```

I've attached the model at https://github.com/pranav-prakash/onnxruntime-riscv/releases/download/v0.01/FAULTING_rcnn.onnx (The model was downloaded from the [model zoo](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/mask-rcnn) and post-training quantized)

When I dump out the index that tries to be accessed, it is `-1`. There's a comment explaining this magic value:
```
 This is initialized to -1 to ensure that if ProcessDef is somehow not called, planning will fail more cleanly
```

Backtrace seems to show the caller is line 310
```
            auto input_arg_index = Index(p_input_arg->Name());
            auto original = Buffer(input_arg_index);
            if (1 == UseCount(original)) {
```

A hacky fix is to do ` if (original != -1 && 1 == UseCount(original))` but I don't know if there's a root cause.

Edit: Hm I think this might actually be a broken model. The link between `2799_Add_quant` and Relu `2763` is missing, which I found to be caused by an input model to the quantizer tool that wasn't topologically sorted. But I think this issue still stands since an invalid model should at least error out gracefully, not crash allocation planning. I'd suggest adding an `ORT_ENFORCE(original != -1, "Could not find buffer corresponding to input: " + p_input_arg->Name())`.

**Urgency**
Medium priority.

**System information**
Using a late-feb build from source, built for a risc-v target. But the issue should still occur on normal x64 builds.

**To Reproduce**
- Download the model linked above
- Initialize an inference session with the model

**Comment by askhade** [comment]
@pranav-prakash - how did you generate the faulty model? Apart from the one you pointed out there are other issues with this model too... While we should add more checks during model load to catch them... we need to fix the tool which generated this model too...

**Comment by pranav-prakash** [comment]
@askhade What other issues did you notice with the model? The missing link between `2799_Add_quant` and `Relu 2763` was the only one I could find, and with that fixed the model runs successfully.

I don't think this should be tagged as `quantization` because the model I supplied to the quantizer was not topologically sorted in the first place, which violates onnx spec. As for how I obtained that non-topologically sorted model, I think that was a bug in one of the pre-processing transformation scripts I had written.

**Comment by askhade** [comment]
I checked the model from model zoo and that is topologically sorted. Only onnx checker checks for topologically sorted nodes... ort does not... If you run onnx checker on Faulting_rcnn.onnx you will see the errors...

**Comment by askhade** [comment]
btw I added quantization label because it seemed to me that you were giving a valid onnx model to the quantizer tool and it was producing an invalid onnx model...

**Comment by pranav-prakash** [comment]
I've created a PR to add the check to allocation_planner:
https://github.com/microsoft/onnxruntime/pull/7042

Maybe in addition a PR should be made to quantizer to run the model checker at the start to ensure the model is valid.
