### ISSUE TITLE
version1.7.0 c++ use cuda not use?

### ISSUE THREAD

**Issue by Tomhouxin** [microsoft/onnxruntime#7022]
when I use 	
#include "cuda_provider_factory.h"
OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0);

build error:
![微信截图_20210316160209](https://user-images.githubusercontent.com/23637856/111275357-051ac900-8671-11eb-9cb8-1e2c549b2738.png)

my environment：
RTX 3060， Cuda11.1  vs2017

please help me, thinks

**Comment by snnn** [comment]
Most likely you didn't include the header file right. 
Could you please put your main.cpp here?

**Comment by snnn** [comment]
Doc for C2598: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c2598?view=msvc-160

**Comment by Tomhouxin** [comment]
@snnn You are right, I just put the header file first. thank you
