### ISSUE TITLE
Is batch inference supported now for quantized gpt2 model with onnxruntime 1.7.0?

### ISSUE THREAD

**Issue by carter54** [microsoft/onnxruntime#7037]
Hi~
As this closed issue showed, batch inference would be supported for quantized gpt2 model when onnxruntime 1.7.0 released.

@carter54, batch support requires per-row quantization, which is not supported yet. We are planning to add it in 1.7 release.

_Originally posted by @yufenglee in https://github.com/microsoft/onnxruntime/issues/5672#issuecomment-721521473_

Is it supported now?

**Comment by yufenglee** [comment]
We tried implementing per-row quantization and found it introduces performance regression, so we didn't merge it into 1.7.

**Comment by isgursoy** [comment]
still?

**Comment by rohanshingade** [comment]
@yufenglee is batch inference supported in onnxruntime?

**Comment by yufenglee** [comment]
@isgursoy and @rohanshingade, we tried per-row quantization but were not able to get better performance. We will not support per-row quantization.
