### ISSUE TITLE
No Op registered for Einsum with domain_version of 12 When using onnxruntime_server

### ISSUE THREAD

**Issue by TaylorHere** [microsoft/onnxruntime#7049]
**Describe the bug**
facing this issue when I'm trying to use onnxruntime_server to server my pytorch exported model in opset_version=12
BUT I CAN load and run this model file with a python onnxruntime-gpu api

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04)
- ONNX Runtime installed from (source or binary): mcr.microsoft.com/onnxruntime/server:latest
- ONNX Runtime version: 
- Python version: python3.7.3
- CUDA/cuDNN version: cuda 101, cuDNN7
- GPU model and memory: V100

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

I build my container image as below
~~~Dockerfile
FROM mcr.microsoft.com/onnxruntime/server:latest as builder

FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu16.04

COPY --from=builder /onnxruntime/server/onnxruntime_server /usr/bin/onnxruntime_server
COPY --from=builder /lib/libonnxruntime.so.1.0.0 /lib/libonnxruntime.so.1.0.0

RUN echo " " > /etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian buster main" >> /etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian buster-updates main" >> /etc/apt/sources.list && \
    apt-get update && apt-get install -y --allow-unauthenticated\
        software-properties-common \
        python3-pip \
        htop

RUN pip3 install --upgrade pip

RUN pip3 install onnxruntime-gpu==1.4.0 seldon-core==1.4.0

~~~

**Expected behavior**
it's work when using python api, failed when onnxserver --model_path /xxx/xxx
**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

I export My model like:
~~~python
torch.onnx.export(model, dummy_input, "albert_classifier.onnx", do_constant_folding=True, export_params=True, verbose=True, input_names=input_names, output_names=output_names, opset_version=12)
~~~

the output of onnxruntime_server puts:
~~~shell
Version: local_build
Commit ID: default

[2021-03-18 04:52:04.361] [ServerApp] [info] Model path: /app/albert_classifier.onnx
[2021-03-18 04:52:05.008] [ServerApp] [critical] Initialize Model Failed: 10 ---- Error: [Load model from /app/albert_classifier.onnx failed:This is an invalid model. Error in Node:Einsum_93 : No Op registered for Einsum with domain_version of 12]
~~~

**Comment by snnn** [comment]
You're right. As you can see from
```
COPY --from=builder /lib/libonnxruntime.so.1.0.0 /lib/libonnxruntime.so.1.0.0
```

It is onnxruntime 1.0.0. The latest version is 1.7.x. The docker image is not updated since 10/31/2019.  We stopped providing it in binary forms, you may build it from source. 

Instructions are: https://github.com/microsoft/onnxruntime/blob/master/docs/Server.md
