### ISSUE TITLE
Error when running "onnxruntime_tools.transformers.bert_perf_test" on BERT-derived model

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [microsoft/onnxruntime#7055]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.0.5 LTS
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.7.0
- Python version: 3.8.8
- Visual Studio version (if applicable): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0 (update 1)/8.1
- GPU model and memory: RTX 3090 24 GB

Hi community,

I tried to run the `onnxruntime_tools.transformers.bert_perf_test` script on an ONNX model of a BERT-like transformer (https://huggingface.co/sentence-transformers/stsb-xlm-r-multilingual), with the following command line:

`python -m onnxruntime_tools.transformers.bert_perf_test --model stsb-xlm-r-multilingual.bert.opt.onnx --batch_size 1 --sequence_length 128 --samples 1000 --test_times 1 --inclusive --all --use_gpu`

And got the following error in output:

```
test setting TestSetting(batch_size=1, sequence_length=128, test_cases=1000, test_times=1, contiguous=None, use_gpu=True, warmup=True, omp_num_threads=None, omp_wait_policy=None, intra_op_num_threads=None, seed=3, verbose=False, inclusive=False, extra_latency=True)
Traceback (most recent call last):
  File "/home/matthieu/anaconda3/envs/sts-transformers/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/matthieu/anaconda3/envs/sts-transformers/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/matthieu/anaconda3/envs/sts-transformers/lib/python3.8/site-packages/onnxruntime_tools/transformers/bert_perf_test.py", line 492, in <module>
    main()
  File "/home/matthieu/anaconda3/envs/sts-transformers/lib/python3.8/site-packages/onnxruntime_tools/transformers/bert_perf_test.py", line 457, in main
    run_performance(model_setting, test_setting, perf_results, args.all)
  File "/home/matthieu/anaconda3/envs/sts-transformers/lib/python3.8/site-packages/onnxruntime_tools/transformers/bert_perf_test.py", line 314, in run_performance
    input_ids, segment_ids, input_mask = get_bert_inputs(model_setting.model_path, model_setting.input_ids_name,
  File "/home/matthieu/anaconda3/envs/sts-transformers/lib/python3.8/site-packages/onnxruntime_tools/transformers/bert_test_data.py", line 190, in get_bert_inputs
    raise ValueError("Expect the graph to have 3 inputs. Got {}".format(len(graph_inputs)))
ValueError: Expect the graph to have 3 inputs. Got 2
```
It seems to be related to my model that just has 2 inputs instead of the three required, but I can't figure out how to solve this problem. Isn't there a way to set to null/default values one of the inputs ?

Many thanks in advance for helping !

**Comment by tianleiwu** [comment]
@Matthieu-Tinycoaching, you can see the usage like the following. The last 3 parameters can help you. Below is example output (depending on your onnxruntime-gpu version):
```
python -m onnxruntime.transformers.bert_perf_test --help

usage: bert_perf_test.py [-h] --model MODEL -b BATCH_SIZE [BATCH_SIZE ...] -s
                         SEQUENCE_LENGTH [--samples SAMPLES] [-t TEST_TIMES]
                         [--opt_level {0,1,2,99}] [--seed SEED] [--verbose]
                         [--use_gpu] [-n INTRA_OP_NUM_THREADS]
                         [--input_ids_name INPUT_IDS_NAME]
                         [--segment_ids_name SEGMENT_IDS_NAME]
                         [--input_mask_name INPUT_MASK_NAME]
```

First, use view\properties in Netron to find the input names of your ONNX model. If the model has two inputs, you need specify name of each input (input_ids, token_type_ids or attention_mask). 

Here is an example for models with two inputs:
```
python -m onnxruntime.transformers.bert_perf_test --model stsb-xlm-r-multilingual.bert.opt.onnx --batch_size 1 --sequence_length 128 --samples 1000 --test_times 1 --inclusive --all --use_gpu --input_ids_name input_ids --input_mask_name attention_mask
```

**Comment by Matthieu-Tinycoaching** [comment]
Thanks @tianleiwu it works !
