### ISSUE TITLE
AliasWithName is not a registered function(From 5187)

### ISSUE THREAD

**Issue by ricklina90** [microsoft/onnxruntime#7066]
According this article https://github.com/microsoft/onnxruntime/issues/5187, 
there is no solution, so this issue need reopened.

**Comment by RandySheriffH** [comment]
@ricklina90: would u mind somehow share us with your converted onnx file for looking into the graph?

**Comment by ricklina90** [comment]
@RandySheriffH
Thanks for your attention.
This link https://www.sendspace.com/file/3gh6ty is my onnx file (Convert from Detectron2 Model Zoo) and C# test project.

**Comment by solarflarefx** [comment]
@ricklina90 Did you find a solution?

**Comment by SnowRipple** [comment]
@ricklina90 @solarflarefx did you find the solution?

**Comment by SnowRipple** [comment]
@RandySheriffH any luck with the conversion?

**Comment by ricklina90** [comment]
@SnowRipple  Sorry, I have no solution. This issue may need write onnxruntime engineer's help.

**Comment by thiagocrepaldi** [comment]
This issue (has/has not) been replicated on our end. We believe that it is a viable issue, but we do not plan to address it in the immediate future, due to other more prevalent priorities.

Thanks,
ONNX Converter team
