### ISSUE TITLE
Onnxruntime_server support CUDA backend

### ISSUE THREAD

**Issue by TaylorHere** [microsoft/onnxruntime#7070]
I build the onnxruntime_server binary from master branch  within a container build from [Dockerfile.ubuntu_server](https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/docker/Dockerfile.ubuntu_server)
follow by [Server build Instructions](https://github.com/microsoft/onnxruntime/blob/master/docs/Server.md)
then I deploy the binary as
~~~Dockerfile
FROM nvidia/cuda:10.1-cudnn7-runtime-ubuntu16.04

RUN echo " " > /etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian buster main" >> /etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian buster-updates main" >> /etc/apt/sources.list && \
    apt-get update && apt-get install -y --allow-unauthenticated\
        software-properties-common \
        python3-pip \
        htop

RUN pip3 install --upgrade pip
RUN pip3 install onnxruntime-gpu==1.4.0

ADD onnxruntime_server /usr/local/bin/
ADD libonnxruntime.so.1.7.0 /usr/lib/libonnxruntime.so.1.7.0
ADD libre2.so.1v5 /usr/lib/x86_64-linux-gnu/libre2.so.1v5
ADD libcares.so.2 /usr/local/lib/libcares.so.2
~~~

But I found that there is no GPU memory or GPU-Util usage at all, looks like it's not working with a CUDA environment

Also I tried to use  -DUSE_CUDA=1 flag to build the binary, but I got output like:

~~~shell
CMake Warning:
  Manually-specified variables were not used by the project:

    USE_CUDA
~~~

How can I enable the CUDA support?

I'm so sorry for using issues to ask question
I also open a discussion [here](https://github.com/microsoft/onnxruntime/discussions/7053)

**Comment by RandySheriffH** [comment]
@TaylorHere: we are deprecating the onnxruntime server feature, meaning the doc and building infrastructures might be imprecise or not updated to date any more, is it possible for u to follow build instructions here https://www.onnxruntime.ai/docs/how-to/build.html to get binary/package for your scenario?
