### ISSUE TITLE
Question about cmake settings

### ISSUE THREAD

**Issue by boxerab** [microsoft/onnxruntime#7074]
1. I see there is standard `BUILD_SHARED_LIBS` option and also a `onnxruntime_BUILD_SHARED_LIB` option. What is the second option for?
2. When I set `onnxruntime_USE_CUDA` option, is it possible to read `onnxruntime_CUDNN_HOME` from an environment variable ? Currently I have to manually set it.

In general, are the cmake options documented anywhere ?

Thanks!

**Comment by snnn** [comment]
No, BUILD_SHARED_LIBS  is totally different. It means replaces every "add_library(...)" to "add_library(... SHARED ..)". It won't work.  I insist on one thing: you can't simply convert a static library to a shared library without impacting the library's behavior.  And in many many case it will make the library unusable. So BUILD_SHARED_LIBS  is just a for convenient for some simple cases.

**Comment by boxerab** [comment]
Makes sense, thanks.
