### ISSUE TITLE
ORT crashes if second input to split node is empty string.

### ISSUE THREAD

**Issue by TomWildenhain-Microsoft** [microsoft/onnxruntime#7075]
**Describe the bug**
According to the ONNX spec, an empty string may be used to denote an optional input.  The second input the the Split node is optional.  ORT crashes suddenly while running (not when making an inference session for) models with an empty string as the second input to the split node.  It works fine if the input is simply left out.

ORT version 1.7.0

**Comment by RandySheriffH** [comment]
@TomWildenhain-Microsoft: thanks for reporting! Any scripts, model or even possible stack trace that could shared here?

**Comment by hariharans29** [comment]
Thanks for reporting - I think the way the optional input is being handled in the implementation has a bug (just looking at the code). I ll fix it shortly.
