### ISSUE TITLE
when python calls the sharesd lib, an error occurs in the custom cuda operator

### ISSUE THREAD

**Issue by linchufeng-13138** [microsoft/onnxruntime#7085]
hello, I refer to this code 
https://github.com/microsoft/onnxruntime/blob/v1.6.0/onnxruntime/test/testdata/custom_op_library/custom_op_library.cc, it can be compiled and run on python on cpu, but I want it can be run on  cuda, I refer to test_inferenvce.cc and add code:
`
struct CustomopOne : Ort::CustomOpBase<QuantizeOut, CustomopOne_Compute> {
  explicit CustomopOne(const char* provider, void* compute_stream) : provider_(provider), compute_stream_(compute_stream){}
  void* CreateKernel(OrtApi api, const OrtKernelInfo* info) const {
    return new CustomopOne_Compute(api, info, compute_stream_);
  };
  const char* GetName() const { return "CustomopOne"; };

  const char* GetExecutionProviderType() const { return provider_;};

  size_t GetInputTypeCount() const { return 1; };
  ONNXTensorElementDataType GetInputType(size_t /*index*/) const { return ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT; };

  size_t GetOutputTypeCount() const { return 1; };
  ONNXTensorElementDataType GetOutputType(size_t /*index*/) const { return ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT; };
 private:
  const char* provider_;
  void* compute_stream_;
};
`
`OrtStatus* ORT_API_CALL RegisterCustomOps(OrtSessionOptions* options, const OrtApiBase* api) {
  OrtCustomOpDomain* domain = nullptr;
  const OrtApi* ortApi = api->GetApi(ORT_API_VERSION);

  if (auto status = ortApi->CreateCustomOpDomain(c_OpDomain, &domain)) {
    return status;
  }

  AddOrtCustomOpDomainToContainer(domain, ortApi);

#ifdef USE_CUDA
  cudaStream_t compute_stream = nullptr;
  cudaStreamCreateWithFlags(&compute_stream, cudaStreamNonBlocking);
  CustomopOne c_CustomopOne{onnxruntime::kCudaExecutionProvider, compute_stream};
#else
  CustomopOne c_CustomopOne{onnxruntime::kCpuExecutionProvider, nullptr};
#endif

  if (auto status = ortApi->CustomOpDomain_Add(domain, &c_CustomopOne)) {
    return status;
  }
  return ortApi->AddCustomOpDomain(options, domain);
}`
it can be compiled, but when python calls the shared lib, it will give reportes Segmentation fault (core dumped)

**Comment by wangxiong172086864** [comment]
I came across the same problem recently, can you let me know how did you fix it?

**Comment by ArtyZe** [comment]
> hello, I refer to this code
> https://github.com/microsoft/onnxruntime/blob/v1.6.0/onnxruntime/test/testdata/custom_op_library/custom_op_library.cc, it can be compiled and run on python on cpu, but I want it can be run on cuda, I refer to test_inferenvce.cc and add code:
> `
> struct CustomopOne : Ort::CustomOpBase<QuantizeOut, CustomopOne_Compute> {
> explicit CustomopOne(const char* provider, void* compute_stream) : provider_(provider), compute_stream_(compute_stream){}
> void* CreateKernel(OrtApi api, const OrtKernelInfo* info) const {
> return new CustomopOne_Compute(api, info, compute_stream_);
> };
> const char* GetName() const { return "CustomopOne"; };
> 
> const char* GetExecutionProviderType() const { return provider_;};
> 
> size_t GetInputTypeCount() const { return 1; };
> ONNXTensorElementDataType GetInputType(size_t /_index_/) const { return ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT; };
> 
> size_t GetOutputTypeCount() const { return 1; };
> ONNXTensorElementDataType GetOutputType(size_t /_index_/) const { return ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT; };
> private:
> const char* provider_;
> void* compute_stream_;
> };
> ` `OrtStatus* ORT_API_CALL RegisterCustomOps(OrtSessionOptions* options, const OrtApiBase* api) {
> OrtCustomOpDomain* domain = nullptr;
> const OrtApi* ortApi = api->GetApi(ORT_API_VERSION);
> 
> if (auto status = ortApi->CreateCustomOpDomain(c_OpDomain, &domain)) {
> return status;
> }
> 
> AddOrtCustomOpDomainToContainer(domain, ortApi);
> 
> #ifdef USE_CUDA
> cudaStream_t compute_stream = nullptr;
> cudaStreamCreateWithFlags(&compute_stream, cudaStreamNonBlocking);
> CustomopOne c_CustomopOne{onnxruntime::kCudaExecutionProvider, compute_stream};
> #else
> CustomopOne c_CustomopOne{onnxruntime::kCpuExecutionProvider, nullptr};
> #endif
> 
> if (auto status = ortApi->CustomOpDomain_Add(domain, &c_CustomopOne)) {
> return status;
> }
> return ortApi->AddCustomOpDomain(options, domain);
> }`
> it can be compiled, but when python calls the shared lib, it will give reportes Segmentation fault (core dumped)

@helloworld13138 @wangxiong172086864 hello, same error occurs, have you guys solved this problem ?
