### ISSUE TITLE
How to input/output GPU-based tensors rather than np.array  in python?

### ISSUE THREAD

**Issue by mali19064** [microsoft/onnxruntime#7103]
**Is your feature request related to a problem? Please describe.**
Sometimes, the size of the input/output tensor may be very large, each call to the inference function which transfer the tensor from memory to the GPU will be time consuming, can I directly save the input or output in the GPU?

**System information**
- ONNX Runtime version (you are using): 1.7.0

**Comment by hariharans29** [comment]
We support a feature called `IOBinding` that allows binding buffers on GPUs for inputs/outputs and this extends to the Python Api as well:

1) You can create an `Ortvalue` having its backing data on GPU (an interface is exposed to create an `OrtValue` from a numpy object for convenience). You can use this created `OrtValue` for inferencing should you need to . Please check: https://github.com/microsoft/onnxruntime/blob/6987106bf5580fabb390b28ff6daae3551588395/onnxruntime/test/python/onnxruntime_test_python.py#L776

2) You may also "bind" GPU buffers to inputs/outputs to ask ORT to use them directly and even ask ORT to pre-allocate buffers on GPU for outputs and receive the associated `OrtValue` instance at the end of the call. Check all tests here: https://github.com/microsoft/onnxruntime/blob/6987106bf5580fabb390b28ff6daae3551588395/onnxruntime/test/python/onnxruntime_test_python_iobinding.py#L7

**Comment by hariharans29** [comment]
Please note that this feature is only available for tensors currently - we don't support non-tensors (maps, sequences, etc.)

**Comment by hariharans29** [comment]
Please re-open if you have any follow-ups

**Comment by FrancescoSaverioZuppichini** [comment]
Hey guys, any more docs about how to create a fixed buffer for output? Looking at the tests but I am not 100% where it is, it would also be wonderful if you can explain a little bit how to use this feature with a snippet
