### ISSUE TITLE
Provider OpenVINOExecutionProvider has already been registered

### ISSUE THREAD

**Issue by ledaiduongvnth** [microsoft/onnxruntime#7119]
**Describe the bug**
Using onnxruntime built with Openvino, I get an error `Provider OpenVINOExecutionProvider has already been registered
`
It was difficult for searching an example for using onnxruntime with Openvino. Please provide one!
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary):1.7.0
- ONNX Runtime version: 1.7.0

**To Reproduce**
```
        Ort::Env *env = new Ort::Env(ORT_LOGGING_LEVEL_WARNING, "test");
        Ort::SessionOptions session_options;
        session_options.SetIntraOpNumThreads(1);
        OrtOpenVINOProviderOptions options;
        options.device_type = "CPU_FP32";
        options.enable_vpu_fast_compile = 0;
        options.device_id = "";
        options.num_of_threads = 8;
        session_options.AppendExecutionProvider_OpenVINO(options);
        auto status = OrtSessionOptionsAppendExecutionProvider_OpenVINO(session_options, 0);
        session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
        this->faceRecSes = new Ort::Session(*env, model_path, session_options);
```

**Expected behavior**
Hopefully, running onnxruntime with openvino may speedup model inference on Intel cpu than using pure onnxruntime.

**Comment by jywu-msft** [comment]
have you looked at these docs:
https://www.onnxruntime.ai/docs/reference/execution-providers/OpenVINO-ExecutionProvider.html#cc-api

**Comment by ledaiduongvnth** [comment]
@jywu-msft 
The above documentation gives me a brief piece of code 
```
OrtOpenVINOProviderOptions options;
options.device_type = "CPU_FP32";
options.enable_vpu_fast_compile = 0;
options.device_id = "";
options.num_of_threads = 8;
SessionOptionsAppendExecutionProvider_OpenVINO(session_options, &options);
```
It isn't clear where do I get the function `SessionOptionsAppendExecutionProvider_OpenVINO` and how does it interact with onnxruntime session. I think you had better provide an example that can run independently, not just a small piece of code.
Thank you!

**Comment by jywu-msft** [comment]
> @jywu-msft
> The above documentation gives me a brief piece of code
> 
> ```
> OrtOpenVINOProviderOptions options;
> options.device_type = "CPU_FP32";
> options.enable_vpu_fast_compile = 0;
> options.device_id = "";
> options.num_of_threads = 8;
> SessionOptionsAppendExecutionProvider_OpenVINO(session_options, &options);
> ```
> 
> It isn't clear where do I get the function `SessionOptionsAppendExecutionProvider_OpenVINO` and how does it interact with onnxruntime session. I think you had better provide an example that can run independently, not just a small piece of code.
> Thank you!

you can use the onnxruntime_perf_test tool (which gets built as part of onnxruntime build) as an example:
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/perftest/ort_test_session.cc#L164

**Comment by ledaiduongvnth** [comment]
@jywu-msft With the following configuration, my program was compiled  but getting static while runtime:
```
        Ort::Env *env = new Ort::Env(ORT_LOGGING_LEVEL_WARNING, "test");
        Ort::SessionOptions session_options;
        session_options.SetIntraOpNumThreads(1);
        OrtOpenVINOProviderOptions options;
        options.device_type = "CPU_FP32";
        options.enable_vpu_fast_compile = 0;
        options.device_id = "";
        options.num_of_threads = 8;
        session_options.AppendExecutionProvider_OpenVINO(options);
        session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
        this->faceDetSes = new Ort::Session(*env, model_path, session_options);
```

Probably I don't miss anything from your onnxruntime_perf_test according to `USE_OPENVINO` option.
I am sure that the program provides correct outputs when not using openvino backbone as the following configuration:
```
        Ort::Env *env = new Ort::Env(ORT_LOGGING_LEVEL_WARNING, "test");
        Ort::SessionOptions session_options;
        session_options.SetIntraOpNumThreads(1);
//        OrtOpenVINOProviderOptions options;
//        options.device_type = "CPU_FP32";
//        options.enable_vpu_fast_compile = 0;
//        options.device_id = "";
//        options.num_of_threads = 8;
//        session_options.AppendExecutionProvider_OpenVINO(options);
        session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
        this->faceDetSes = new Ort::Session(*env, model_path, session_options);
```
Searching through GitHub and onnxruntime issues, there are some people who get the same difficulty while using onnxruntime in combination with openvino. Please provide more concrete example if possible. Thank you so much!

**Comment by MaajidKhan** [comment]
@ledaiduongvnth 
First way, you can leverage OpenVINO Execution provider and it's options is by using the **onnxruntime_perf_test** tool which comes built in when you build onnxruntime with OpenVINO. (As george mentioned at the top)

secondly, you can checkout my blog.
https://nmaajidkhan.medium.com/onnx-runtime-openvino-c-inference-e682b075fdaf
This blog talks about a cpp sample and it demonstrates complete end to end inferencing of an image using a squeezenet onnx model using onnxruntime-openvino.

It will also help you understand different runtime options that are available with the API.
code here: https://github.com/MaajidKhan/onnxruntime-openvino-cpp/tree/main/1_ONNXRT_OpenVINO_CPP_sample

**Comment by ledaiduongvnth** [comment]
@MaajidKhan Thank you for your useful example, it helps me a lot!

**Comment by zhu-dq** [comment]
> @ledaiduongvnth First way, you can leverage OpenVINO Execution provider and it's options is by using the **onnxruntime_perf_test** tool which comes built in when you build onnxruntime with OpenVINO. (As george mentioned at the top)
> 
> secondly, you can checkout my blog. https://nmaajidkhan.medium.com/onnx-runtime-openvino-c-inference-e682b075fdaf This blog talks about a cpp sample and it demonstrates complete end to end inferencing of an image using a squeezenet onnx model using onnxruntime-openvino.
> 
> It will also help you understand different runtime options that are available with the API. code here: https://github.com/MaajidKhan/onnxruntime-openvino-cpp/tree/main/1_ONNXRT_OpenVINO_CPP_sample

@MaajidKhan, The code link is lost, can you provide another one.

**Comment by MaajidKhan** [comment]
@zhu-dq sorry the blog and the code link was removed long back. However, we maintain the OVEP CPP samples in the official onnxruntime-samples repository here.
https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/OpenVINO_EP

We will be updating the documentation soon with the latest OV version support. Meanwhile, have a look at this.
