### ISSUE TITLE
Question about "quantize_qat"

### ISSUE THREAD

**Issue by Kentaro-Mikami** [microsoft/onnxruntime#7144]
**Is your feature request related to a problem? Please describe.**
We used "quantize_qat" API for onnx model, but the qat quantized onnx model was same as dynamic quantized model when using "quantize_dynamic". And we felt that the training process did not work. (The quantization time was very short.)
The implementation of "quantize_qat" is work in progress?

**System information**
- ONNX Runtime version (you are using):1.7.0

**Describe the solution you'd like**
If you have plan to implement "quantize_qat", would you tell us the schedule?
Also, we want to get both of activations and weights quantized model as a output of "quantize_qat".
Will it be possible? (Current output model of "quantize_qat" is quantized only weights.)

**Comment by yufenglee** [comment]
The quantization tool does provide QAT ability. It depends on the original framework to do it. Once it is re-trained and converted to ONNX, you can call this quantize_qat API to quantize the model to int8.

**Comment by Kentaro-Mikami** [comment]
Hello, Yufeng. Thank you for your reply.
But I'm a little confusing, would you tell me more?
What is the difference between "quantize_dynamic" and "quantize_qat"?
If we use "quantize_dynamic", we use original framework for training and creating the model. After converting the model to onnx, we use "quantize_dynamic" for converting to int8. I think that this procedure is same as your explanation.

**Comment by yufenglee** [comment]
If you do QAT retraining with either tf/pytorch, those frameworks add fakequant ops to simulate the quantization process. When you convert/export a QAT model to onnx, onnx uses QuantizeLinear/DeQuantizeLinear pair to represent the fakequant ops. If you call the quantize_dynamic directly, those D/DQs will be kept in the quantized model. The quantize_qat extracts the quantization parameter from the Q/DQ and throw them. That's the difference.

We are deprecating the method quantize_qat. [ORT ](https://github.com/microsoft/onnxruntime/pull/7033)is supporting to run model with Q/DQs directly. For QAT models, you don't need to go through the quantization tool anymore once the work is done. Now our latest master already has basic support. You can try it on your QAT model.

**Comment by BeginnerW** [comment]
> If you do QAT retraining with either tf/pytorch, those frameworks add fakequant ops to simulate the quantization process. When you convert/export a QAT model to onnx, onnx uses QuantizeLinear/DeQuantizeLinear pair to represent the fakequant ops. If you call the quantize_dynamic directly, those D/DQs will be kept in the quantized model. The quantize_qat extracts the quantization parameter from the Q/DQ and throw them. That's the difference.
> 
> We are deprecating the method quantize_qat. [ORT ](https://github.com/microsoft/onnxruntime/pull/7033)is supporting to run model with Q/DQs directly. For QAT models, you don't need to go through the quantization tool anymore once the work is done. Now our latest master already has basic support. You can try it on your QAT model.

from what i know, pytorch does not support export a QAT model to onnx。would you give some advice on pytorch QAT model exporting

**Comment by Hrayo712** [comment]
@yufenglee, when you say the ORT master branch has basic support for running Q/DQ models directly, what do you mean exactly. What are the current limitations for running Q/DQ models directly with ORT ? is this only limited to the CPU EP ? or
 is running Q/DQ models supported by other EPs, such as NNAPI for example ?

Thanks in advance for your support

**Comment by Hrayo712** [comment]
@yufenglee thanks for your reply.

Due to project needs, I am interested in the functionality of `quantize_qat()`, that is, to convert a QAT model (exported to ONNX from Pytorch), to its Quantized ops representation (QLinearConv, QLinearMatMul, etc.).

I have the following toy QAT model (borrowed from Pytorch QAT example):
```
class M(torch.nn.Module):
    def __init__(self):
        super(M, self).__init__()
        # QuantStub converts tensors from floating point to quantized
        self.quant = torch.quantization.QuantStub()
        self.conv = torch.nn.Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        self.bn = torch.nn.BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        self.relu = torch.nn.ReLU()
        # DeQuantStub converts tensors from quantized to floating point
        self.dequant = torch.quantization.DeQuantStub()

    def forward(self, x):
        x = self.quant(x)
        x = self.conv(x)
        x = self.bn(x)
        x = self.relu(x)
        x = self.dequant(x)
        return x
```

Then, I export this model to ONNX as follows:
```
qat_model= M().eval()

qat_model.qconfig = torch.quantization.get_default_qat_qconfig('fbgemm')

qat_model= torch.quantization.fuse_modules(qat_model, [["conv", "bn", "relu"]])

quantization.prepare_qat(qat_model, inplace=True)

dummy_input = torch.randn(1, 3, 224, 224)

qat_model.apply(quantization.disable_observer) # observers must be disabled before export

torch.onnx.export(qat_model,
                  dummy_input,
                  "model.onnx",
                  opset_version=13)
```

Inspecting the ONNX model via Netron shows me that the export functionality is correctly converting the QAT model to ONNX via introducing QuantizeLinear/DequantizeLinear (Q/DQ) pairs. Finally, I use the `quantize_qat()` interface as follows:

```
quantize_qat("dummy_model.onnx", "dummy_qdq_to_qop")
```

However, this I am getting the following error from `onnx_quantizer.py`:

`ValueError: Remove fake-quantized node pair Error: Parent node is not found for QuantizeLinear_2.`

Any insight into what might be the problem ?

This is with:
Torch 1.9.0
onnxruntime 1.8.2

**Comment by yufenglee** [comment]
@Hrayo712, OnnxRuntime supports to dump out optimized model with SessionOptions::optimized_model_filepath. Could you please try code like below?

`
def generate_identified_filename(filename: Path, identifier: str) -> Path:
    '''
    Helper function to generate a identifiable filepath by concatenating the given identifier as a suffix.   
    '''
    return filename.parent.joinpath(filename.stem + identifier).with_suffix(filename.suffix)

def dump_optimize_model(model_path: Path):
    '''
        Generate model that applies graph optimization (constant folding,etc.)
        parameter model_path: path to the original onnx model
        return: optimized onnx model
    '''
    opt_model_path = generate_identified_filename(model_path, "-opt")
    sess_option = SessionOptions()
    sess_option.optimized_model_filepath = opt_model_path.as_posix()
    sess_option.graph_optimization_level = GraphOptimizationLevel.ORT_ENABLE_EXTENDED
    _ = InferenceSession(model_path.as_posix(), sess_option, providers=['CPUExecutionProvider'])`

**Comment by Hrayo712** [comment]
@yufenglee , you mean optimizing the graph with this method before feeding it to `quantize_qat()` ? I tried and it didnt work. 

As far as I understand, what you mention will only perform graph optimizations. What I need is to go from a Q/DQ model (which I obtained by exportin from Pytorch to ONNX) to Quantized ops. That is the purpose of the [quantize_qat()](url) interface, right ?
