### ISSUE TITLE
Building from source with DNNL -- but no DnnlExecutionProvider

### ISSUE THREAD

**Issue by Zha0q1** [microsoft/onnxruntime#7155]
Hi I have been trying to build onnxruntime with dnnl provider on several different EC2 instances (all ubuntu 18). I was able to build the python wheel but after I installed it I could not see DnnlExecutionProvider.
```python
>>> import onnxruntime
>>> onnxruntime.get_available_providers()
['CPUExecutionProvider']
```
This is the case across 3 different machines/instances. They also use different CPUs.
I built onnxruntime with this command:
```
./build.sh --parallel --build_shared_lib --config Release --skip_tests --use_openmp --use_dnnl --build_wheel 
```
Would anyone share some insights on this? Thanks!

**Comment by Zha0q1** [comment]
Any help please?

**Comment by jywu-msft** [comment]
share the wheel that you built? can try and see if there's anything wrong with it.

**Comment by Zha0q1** [comment]
@jywu-msft thanks for the reply, here is the wheel
https://drive.google.com/file/d/1UZRgZqZ0Uoglc8YSkK4GvhCpu8e_d0t1/view?usp=sharing

there is a dnnl so file in the capi folder, but in python I cannot see it as an available provider
```shell
ubuntu@ip-172-31-18-236:~/anaconda3/lib/python3.7/site-packages/onnxruntime/capi$ ls
__init__.py  _ld_preload.py    libdnnl.so.1                      libonnxruntime_providers_shared.so   onnxruntime_pybind11_state.so  training
__pycache__  _pybind_state.py  libonnxruntime_providers_dnnl.so  onnxruntime_inference_collection.py  onnxruntime_validation.py
```

**Comment by Zha0q1** [comment]
Here is another wheel (py3.6) generated by my colleague @waytrue17 https://drive.google.com/file/d/1s0P3muAFtdYvBDYAGlWufJ3L3HH5jfQ8/view?usp=sharing

**Comment by Zha0q1** [comment]
You are right! I just checked with `session.get_providers()` and I did have DNNLExecutionProvider.

As a side question: @waytrue17 and I are MXNet developers and we are working on MXNet's onnx export support. Would you suggest any other performance optimization except DNNL? We are targeting cpu and gpu for now
