### ISSUE TITLE
Error when cross-compiling for iOS

### ISSUE THREAD

**Issue by olokobayusuf** [microsoft/onnxruntime#7160]
When cross-compiling for iOS (`arm64`), the build fails with an include error on including `cpuid.h` in `onnxruntime/core/common/threadpool.cc`:
```cpp
#elif defined(__APPLE__)
#include <cpuid.h>
#else
```
As far as I can tell, the header is used here:
```cpp
void ThreadPoolProfiler::LogRun(int thread_idx) {
  if (enabled_) {
    child_thread_stats_[thread_idx].num_run_++;
    auto now = Clock::now();
    if (child_thread_stats_[thread_idx].core_ < 0 ||
        TimeDiffMicroSeconds(child_thread_stats_[thread_idx].last_logged_point_, now) > 10000) {
#ifdef _WIN32
      child_thread_stats_[thread_idx].core_ = GetCurrentProcessorNumber();
#elif defined(__APPLE__)
      uint32_t CPUInfo[4];
      __cpuid_count(1, 0, CPUInfo[0], CPUInfo[1], CPUInfo[2], CPUInfo[3]);
      if ((CPUInfo[3] & (1 << 9)) != 0) {
        child_thread_stats_[thread_idx].core_ = (unsigned)CPUInfo[1] >> 24;
      }
#else
      child_thread_stats_[thread_idx].core_ = sched_getcpu();
#endif
      child_thread_stats_[thread_idx].last_logged_point_ = now;
    }
  }
}
```
and also in `ThreadPoolProfiler::MainThreadStat::LogCore`. From the header in the Xcode default toolchain:
```cpp
#if !(__x86_64__ || __i386__)
#error this header is for x86 only
#endif
```
This doesn't fail CI because as far as I can tell, CI compiles for the simulator, not for the device.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11.0.1, cross-compiling for iOS
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: `master`
- GCC/Compiler version (if compiling from source): Clang 12.0.0

**To Reproduce**
1. Clone ORT `master`
2. Run default iOS cross-compile as specified in `BUILD.md`

**Comment by RandySheriffH** [comment]
@olokobayusuf: https://github.com/microsoft/onnxruntime/tree/FixMacHeader
Will send PR from it after some verification.

**Comment by olokobayusuf** [comment]
> @olokobayusuf: https://github.com/microsoft/onnxruntime/tree/FixMacHeader
> Will send PR from it after some verification.

Perfect, thanks!

**Comment by RandySheriffH** [comment]
@olokobayusuf: let me know if the branch works for u or there are other build breaks. :)

**Comment by olokobayusuf** [comment]
> @olokobayusuf: let me know if the branch works for u or there are other build breaks. :)

@RandySheriffH the build succeeded! I should note though that even when building with `--skip_tests`, I get a build error from the `onnx_test_runner` target:
```
=== BUILD TARGET onnx_test_runner OF PROJECT onnxruntime WITH CONFIGURATION Release ===

Check dependencies
Code Signing Error: Bundle identifier is missing. onnx_test_runner doesn't have a bundle identifier. Add a value for PRODUCT_BUNDLE_IDENTIFIER in the build settings editor.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 14.4'

** BUILD FAILED **
```

**Comment by RandySheriffH** [comment]
Please feel free to open another issue for the code sign failure. Closing this one for building.

**Comment by olokobayusuf** [comment]
> Please feel free to open another issue for the code sign failure. Closing this one for building.

Sounds good. I see your PR has been merged. Thank you so much for getting to this as quickly as you did!
