### ISSUE TITLE
Error while build from source: Failed to find executable path for Cmake

### ISSUE THREAD

**Issue by sumitsays** [microsoft/onnxruntime#7168]
Hi Team,
I am trying to build the ONNXRuntime Repo by following the this link:
https://www.onnxruntime.ai/docs/how-to/build.html

The commands I have tried to run the build is:

- .\build.bat --config Debug --build_shared_lib --parallel --use_dml --skip_tests --skip_submodule_sync
  The error I am getting is:
  
  ![image](https://user-images.githubusercontent.com/11188170/112894034-3b544180-9090-11eb-83a6-a090ca0c3c86.png)

I looked into the build.py file, and found that there is section of code which is trying to find the executable path for cmake:
![image](https://user-images.githubusercontent.com/11188170/112894202-6f2f6700-9090-11eb-9ec4-a42f32ae9fce.png)

So I thought, I should pass the executable path for cmake explicitly. Tried to find out the argument name by which I can pass this path. Saw this again in build.py:
![image](https://user-images.githubusercontent.com/11188170/112894480-c6cdd280-9090-11eb-8f29-f9fad29ad58d.png)

Used below command:

- .\build.bat --config Debug --build_shared_lib --parallel --use_dml --skip_tests --skip_submodule_sync --cmake_path "C:\Program Files\CMake\bin"

  But it is also failing and giving the same error:
  ![image](https://user-images.githubusercontent.com/11188170/112893430-8752b680-908f-11eb-9fa2-af6fac86905a.png)

Could some one please help me in resolving this issue?

**Comment by snnn** [comment]
It should be --cmake_path "C:\Program Files\CMake\bin\cmake.exe"

**Comment by sumitsays** [comment]
Thank you.
