### ISSUE TITLE
Build wheel  with OpenVINO  ERROR: testRegisterCustomOpsLibrary (__main__.TestInferenceSession)

### ISSUE THREAD

**Issue by hcgprague** [microsoft/onnxruntime#7173]
.\build.bat --config Release --build_wheel --use_openvino CPU_FP32 --parallel --cmake_generator "Visual Studio 16 2019"

**Describe the bug**
======================================================================
ERROR: testRegisterCustomOpsLibrary (__main__.TestInferenceSession)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "onnxruntime_test_python.py", line 752, in testRegisterCustomOpsLibrary
    so1.register_custom_ops_library(shared_library)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Failed to load library, error code: 126

----------------------------------------------------------------------
Ran 42 tests in 0.266s

FAILED (errors=1)
Traceback (most recent call last):
  File "C:\onnxruntime\\tools\ci_build\build.py", line 2023, in <module>
    sys.exit(main())
  File "C:\onnxruntime\\tools\ci_build\build.py", line 1955, in main
    run_onnxruntime_tests(args, source_dir, ctest_path, build_dir, configs)
  File "C:\onnxruntime\\tools\ci_build\build.py", line 1380, in run_onnxruntime_tests
    run_subprocess([sys.executable, 'onnxruntime_test_python.py'], cwd=cwd, dll_path=dll_path)
  File "C:\onnxruntime\\tools\ci_build\build.py", line 544, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "C:\onnxruntime\tools\python\util\run.py", line 44, in run
    env=env, shell=shell)
  File "C:\Users\FIT036\.conda\envs\gpu\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\FIT036\\.conda\\envs\\gpu\\python.exe', 'onnxruntime_test_python.py']' returned non-zero exit status 1.

**Urgency**
normal

**System information**
- OPENVINO : 2020.4
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10pro 64bit
- ONNX Runtime installed from (source or binary): py  source package  
- ONNX Runtime version: onnxruntime 1.7.0
- Python version:  python 3.6
- Visual Studio version (if applicable): VS2019    ,  .\build.bat --config Release  --build_wheel --use_openvino CPU_FP32  --parallel  --cmake_generator "Visual Studio 16 2019"
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: NO
- GPU model and memory:
- VC++ 2019

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**
 
**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by pranavsharma** [comment]
@jywu-msft @MaajidKhan can one of you take a look?

**Comment by hcgprague** [comment]
After   update install  OpenVINO 2021.02   the error message become :   

generate_onnx: ./dev_paul/user_config\A\model-02011408-epoch47-7.5464.onnx
2021-03-30 16:13:23.0999880 [E:onnxruntime:Default, provider_bridge_ort.cc:608 onnxruntime::ProviderLibrary::Get] Failed to load library, error code: 126

**Comment by hcgprague** [comment]
1.Yes, I could run  webapi.py  with openvino .   
2.But after using pyinstaller to make webapi.exe   ,  when it run would appear  load dll error as :
![image](https://user-images.githubusercontent.com/19700407/114137357-a5959d80-993e-11eb-87f8-0513e841cad2.png)

**Comment by hcgprague** [comment]
after build:   onnxruntime_shared_lib_test.exe      some errors.

![ERRORTEST](https://user-images.githubusercontent.com/19700407/114492421-2ad4c700-9c4b-11eb-9098-9520ac0e3857.PNG)
![ERROR](https://user-images.githubusercontent.com/19700407/114492430-2dcfb780-9c4b-11eb-89d5-e6f740b00cf8.PNG)

**Comment by hcgprague** [comment]
After I reinstall   OpenVINO 2021.3  , and     before execute onnxruntime_shared_lib_test.exe    ,  I have to    run  setupvars.bat   in C:\Program Files (x86)\Intel\openvino_2021.3.394\bin.

Test would be pass.
![image](https://user-images.githubusercontent.com/19700407/114673940-503ffe80-9d39-11eb-95f7-178e624851fb.png)

And  I could run onnxruntime_openvino prediction  successfully in my project by  pip install   onnxruntime_openvino-1.7.0-cp36-cp36m-win_amd64.whl     from C:\onnxruntime\build\Windows\Release\Release\dist .



![image](https://user-images.githubusercontent.com/19700407/114674886-44a10780-9d3a-11eb-80e8-f618127762b4.png)
But After pyinstaller to package to   webapi.exe  ,  it run start with error as      2021-04-14 16:00:19.1906275 [E:onnxruntime:Default, provider_bridge_ort.cc:564 onnxruntime::ProviderSharedLibrary::Ensure] Failed to load library, error code: 126


![Uploading image.png…]()

**Comment by MaajidKhan** [comment]
Hi @hcgprague .
Glad that you were able to run the tests and infer your python sample.

coming to the last issue, where you trying to convert a .py file to .exe using pyinstaller python library on windows.
I think this issue is different and specific to windows and has to do with use of external python library. can you create a separate ticket for this issue.

And you can close this, if you don't have any other issue using onnxruntime with openvino on windows.
