### ISSUE TITLE
Fix memory leak in TRT due to optimization profile with dynamic shapes

### ISSUE THREAD

**Issue by AhmadZakaria** [microsoft/onnxruntime#7194]
**Describe the bug**
There is a bug causing a consistent native memory leak when calling Run using the TensorRT execution provider.
It is a bug that has been addressed before (#2773, #2815), but then the bug was reintroduced here (#5229). 
According to @stevenlix (here https://github.com/microsoft/onnxruntime/pull/5229#issue-489659573) , we need to update all input profiles when one of them is changed. But currently, we call `createOptimizationProfile()` without any check. I suggest using a single `bool` instead of a `map` and update all of the inputs if one is changed.

**Urgency**
High. This is blocking any production use of OnnxRuntime for us. We need TensorRT to be able to run our models real-time for extended periods of time (weeks), and the memory leak is quickly causing us to run into memory issues.

**System information**
- OS Platform and Distribution: Windows 10 64-bit (20H2)
- ONNX Runtime installed from (source or binary): from source
- ONNX Runtime version: v1.6.0
- Python version: N/A running c++ api
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source): MSVC 2019
- CUDA/cuDNN version: 11.1, 7
- GPU model and memory: tested with Quadro P2000, RTX 3070, Quadro RTX 3000, 

**To Reproduce**
- Same as #2773

**Expected behavior**
No memory leak.

**Comment by jywu-msft** [comment]
PR #7195 was merged into master so I'm closing this issue.
