### ISSUE TITLE
Input device type check has syntax error

### ISSUE THREAD

**Issue by ashari4** [microsoft/onnxruntime#7247]
For non-CUDA EPs, the ORTTrainer API performs a check that the input tensor's device is cpu.

https://github.com/microsoft/onnxruntime/blob/10102c09b67a1f1dd71e035a768fdeb86a1e85f2/orttraining/orttraining/python/training/orttrainer.py#L889

This was introduced in #7112 

The LHS should be input.device.type; otherwise, the assert always fails because a [torch.device](https://pytorch.org/docs/stable/tensor_attributes.html#torch-device) is an object, not a string.

**System information**
OS Platform and Distribution: Windows 10 and Ubuntu 20.04 
ONNX Runtime installed from (source): source
ONNX Runtime version: ba51774a1f73f77948505816d8a57d405d40bd80 (more recent than onnxruntime-1.7.1)
GCC/Compiler version (if compiling from source): cl 19.28.29913 on Windows 10 and Clang 11.1 on Ubuntu 20.04

**Comment by ashari4** [comment]
A fix for this is available in #7248

**Comment by SherlockNoMad** [comment]
Thanks for the fix. Will merge for you.

**Comment by SherlockNoMad** [comment]
PR merged. Closing the issue.
