### ISSUE TITLE
onnxruntime c++ protobuf parsing failed.

### ISSUE THREAD

**Issue by dujtep-airtech** [microsoft/onnxruntime#7256]
I used onnxruntime c++ library. i create session and try to load model zoo but i got error 
"onnx/squeezenet/model/squeezenet1.1-7.onnx failed:Protobuf parsing failed."

**Comment by SherlockNoMad** [comment]
Just to check the model is not broken. Does the "onnx/squeezenet/model/squeezenet1.1-7.onnx" opens with Netron?

**Comment by dujtep-airtech** [comment]
I'm download model form "https://github.com/onnx/models" all model broken when I open with Netron.

**Comment by dujtep-airtech** [comment]
> Just to check the model is not broken. Does the "onnx/squeezenet/model/squeezenet1.1-7.onnx" opens with Netron?

I'm download model form "https://github.com/onnx/models" all model broken when I open with Netron.

**Comment by dujtep-airtech** [comment]
I found it.
[https://github.com/lutzroeder/netron/issues/463](463)
It solved my problem.
