### ISSUE TITLE
Information in deleted BUILD.md left out onnxruntime.ai

### ISSUE THREAD

**Issue by jeyblu** [microsoft/onnxruntime#7277]
**Describe the bug**
Documentation on how to build the dnnl execution provider for gpu that was in BUILD.md, which was deleted in [commit c170061998e1adfb5a37dfe87d2f845b202cd348](https://github.com/microsoft/onnxruntime/commit/c170061998e1adfb5a37dfe87d2f845b202cd348), was left out in the new documentation [page](https://www.onnxruntime.ai/docs/how-to/build.html#dnnl-and-mklml-1)

**Comment by jywu-msft** [comment]
thanks for reporting. we'll get this corrected.

**Comment by jywu-msft** [comment]
can you be more specific about what section is missing?
The build instructions were moved to https://www.onnxruntime.ai/docs/how-to/build.html#dnnl-and-mklml

**Comment by jeyblu** [comment]
It's all there in the link you sent. I was looking in the wrong place. However, there's an 'S' at the end of the linux command line that shouldn't be there.
![image](https://user-images.githubusercontent.com/63478620/113944589-a2bd7000-97b9-11eb-8659-7bb0b4fb5c35.png)

How will developers add or update documentation going forward as it's no longer part of git repo?

Thanks!

**Comment by jywu-msft** [comment]
> It's all there in the link you sent. I was looking in the wrong place. However, there's an 'S' at the end of the linux command line that shouldn't be there.
> ![image](https://user-images.githubusercontent.com/63478620/113944589-a2bd7000-97b9-11eb-8659-7bb0b4fb5c35.png)
> 
> How will developers add or update documentation going forward as it's no longer part of git repo?
> 
> Thanks!

it is part of the onnxruntime repo, just in a branch called gh_pages
see: https://github.com/microsoft/onnxruntime/tree/gh-pages
