### ISSUE TITLE
Question about quantization of Yolo.

### ISSUE THREAD

**Issue by Kentaro-Mikami** [microsoft/onnxruntime#7283]
**Is your feature request related to a problem? Please describe.**
We checked quantization example for Yolo network.
This example show the way by combination TensorRT and Onnx runtime.
https://github.com/microsoft/onnxruntime/tree/master/onnxruntime/python/tools/quantization/E2E_example_model/object_detection/trt/yolov3

Although we can use "quantize_dynamic" or "quantize_static" for classification network,
Do we need to use the combination TensorRT and Onnx runtime?
Or can we use "quantize_dynamic" or "quantize_static" for Yolo network also?

**System information**
- ONNX Runtime version (you are using):1.7.0

**Comment by yufenglee** [comment]
TRT doesn't support the quantized operators, like QLinearConv. Currently, if you want to leverage TRT EP, here are the general steps, just as the E2E example shows: 
- use the calibration tool to get calibration data for your model
- pass the calibration data to TRT EP through environment variables, and set corresponding environment variables, like an [example ](https://github.com/microsoft/onnxruntime/blob/0d49e53985e2494f3b9caf4db9e8646293d1cd6c/onnxruntime/python/tools/quantization/E2E_example_model/object_detection/trt/yolov3/e2e_user_yolov3_example.py#L174)here.
- create OnnxRuntime InferenceSession with TRT EP. 

In the near future, we will use the [QDQ ](https://github.com/microsoft/onnxruntime/blob/0d49e53985e2494f3b9caf4db9e8646293d1cd6c/onnxruntime/python/tools/quantization/quantize.py#L156)format to support the TRT EP. With it, you just need to use the quantize_static to quantize the model and then use the quantized model to create InferenceSession.
