### ISSUE TITLE
can I use the windows_x86 to run with gpu?

### ISSUE THREAD

**Issue by YAwei666** [microsoft/onnxruntime#7296]
![image](https://user-images.githubusercontent.com/34396185/114135133-6285fb00-993b-11eb-99d8-7da1542bf981.png)
I notice that there's only cpu type for windows_x86 version, I just wondering that if a gpu version for windows_x86 supported or can  I build it from the source code,thanks.

**Comment by snnn** [comment]
No, it doesn't work.

**Comment by snnn** [comment]
We don't know if you can build it from source with x86 support. But, if it is for windows, you can try our WindowsAI/DML port. It supports GPU.
