### ISSUE TITLE
Invalid model after quantization with onnxruntime 1.7.0 

### ISSUE THREAD

**Issue by leqiao-1** [microsoft/onnxruntime#7300]
**Describe the bug**
Model quantized successfully with onnxruntime 1.7.0, but can not be inferenced with onnxruntime 1.7.0:
```
Traceback (most recent call last):
  File "test.py", line 127, in <module>
    init()
  File "test.py", line 42, in init
    session = ort.InferenceSession(model)
  File "/opt/miniconda/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 280, in __init__
    self._create_inference_session(providers, provider_options)
  File "/opt/miniconda/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 307, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from ./res_after_quant.onnx failed:This is an invalid model. Error in Node:custom_rnn_scan_Scan__58 : Nodes in a graph must be topologically sorted, however input 'encoder_0/bidirectional_rnn/fw/gated_gru_cell/W/read/_9__cf__9:0' of node:

;encoder_0/bidirectional_rnn/fw/fw/while/TensorArrayReadV3:0
@encoder_0/bidirectional_rnn/fw/gated_gru_cell/W/read/_9__cf__9:0
Bencoder_0/bidirectional_rnn/fw/gated_gru_cell/b/read/_10__cf__10:0
Gemm__12:Gemm__12"Gemm*
transB
```
Quantization finished without error.

Model can be quantized and inferenced with onnxruntime 1.6.0.

**System information**
- OS Platform and Distribution: Linux Ubuntu 16.04
- ONNX Runtime installed from pypi
- ONNX Runtime version: 1.7.0
- Python version: 3.6

**To Reproduce**
quantize.py
```
'''onnx model quantization'''
import logging
import os
import onnx
from shutil import copy
from onnxruntime import quantization

quantization.quantize_dynamic("res.onnx", 'res_after_quant.onnx')
```
model before quantization can be found here.
[res.zip](https://github.com/microsoft/onnxruntime/files/6284436/res.zip)

**Comment by tobigue** [comment]
I'm facing a similar issue. My model can be quantized and used fine with `1.6.0`, but fails with `1.7.0`.

Im quantizing the model succssfully under `1.6.0` like this:
```
quantize_dynamic(
    model_input=model_name,
    model_output=output_model_name,
    per_channel=True,
    activation_type=QuantType.QUInt8,
    weight_type=QuantType.QUInt8,
)
```

When using `1.7.0` I have to set either `optimize_model=False` or `use_external_data_format=True`, as the constant folding optimiziation will result in a model >2GB (because it duplicates the embedding matrix) and a `InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Protobuf serialization failed.`.

However, creating an `InferenceSession` for a model produced under `1.7.0` with either of these options results in this error:

```
env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py in __init__(self, path_or_bytes, sess_options, providers, provider_options)
    278 
    279         try:
--> 280             self._create_inference_session(providers, provider_options)
    281         except RuntimeError:
    282             if self._enable_fallback:

env/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py in _create_inference_session(self, providers, provider_options)
    305         session_options = self._sess_options if self._sess_options else C.get_default_session_options()
    306         if self._model_path:
--> 307             sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    308         else:
    309             sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)

Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from models/mbart-large-en-ro/decoder-quantized/model.onnx failed:This is an invalid model. Error: Duplicate definition of name (decoder.embed_tokens.weight).
```

You can find the model before and after quantization [here](https://drive.google.com/file/d/15a3LTEZEG-QjIFK30iN0vejQg_VgMvQI/view?usp=sharing).

**Comment by goksinan** [comment]
Similar issue here. Trying to quantize a FasterRCNN model exported from PyTorch. Quantized model is generated successfully, and the model size is reduced ~4X. But when I try to create an InferenceSession using onnxruntime, I get the following error:
`onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from faster_rcnn_mobilenet_quantized.onnx failed:This is an invalid model. Error: two nodes with same node name (rpn.head.conv.bias_scale_node).`
I wanted to exclude that node during quantization, but I don't know how to specify node names that `quantize_dynamic()` expects.

**Comment by yufenglee** [comment]
@goksinan , i'm fixing the issue. Could you please also share you model?

**Comment by aescart1** [comment]
> @goksinan , i'm fixing the issue. Could you please also share you model?

@yufenglee  Hi, is it fixed ? As I still reproduce it. I know it's closed but thanks for your feedback

**Comment by nightflight-dk** [comment]
I can reproduce this as well. ORT-GPU 1.13.1  

(Roberta-large)
Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from quantized/model_quantized.onnx failed:This is an invalid model. Error: two nodes with same node name (/roberta/embeddings/LayerNorm/Add_1_output_0_QuantizeLinear).
 
(deberta-large-mnli)
Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from quantized/model_quantized_infs.onnx failed:This is an invalid model. Error: two nodes with same node name (/deberta/encoder/layer.0/attention/self/Div_1_output_0_QuantizeLinear).
