### ISSUE TITLE
how can i use the onnxruntime cpu version and gpu version at the same time? 

### ISSUE THREAD

**Issue by gitcheol** [microsoft/onnxruntime#7313]
**Describe the bug**
Hi there. I`m a newbie in onnxruntime, .net framework.
**I want to run the onnxruntime cpu version and gpu version at the same time.** 
After installing the onnxruntime, onnxruntime gpu in the Nuget package, i built my code on gpu. but i got an error.. onnxruntime could not find the onnxruntime.dll and i checked bin directory and i found it. 
I think there is a issue about the different package but same .dll build file, 
how can i solve this problem? 
(when i build the onnxruntime cpu version i got the onnxruntime.dll  but whin i build the onnxruntime gpu version i also got the onnxruntime.dll )

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 
- ONNX Runtime installed from (source or binary): nuget package  
- ONNX Runtime version: onnxruntime cpu version : 1.7.0 onnxruntime gpu version : 1.7.1 
- Python version: x 
- CUDA/cuDNN version: 11.2
- GPU model and memory: RTX3090 / 24GB

**Expected behavior**
If I use 'cpu' mode, I want to use only cpu, but if I use 'gpu' mode I want to use gpu as well.
(I want to run the onnxruntime cpu version and gpu version at the same time.)

**Comment by pranavsharma** [comment]
Currently, you can simply install the GPU version ensuring all it's dependencies are in the PATH. After installing this if you want to do inferencing using GPU, use MakeSessionOptionWithCudaProvider() to create the session options. If not, just use SessionOptions(). In the upcoming release (mid May) we'll be releasing a feature which doesn't even require you to install the dependencies unless you want to inferencing on the GPU.

**Comment by gitcheol** [comment]
Thank you for replying! may i ask some 2 more question? 
1. After onnxruntime.gpu updated, will it be reflected in previous version like 1.6.0??
(In my other computer with RTX2080 and cuda10.2, there are some error about onnxruntime 1.7.0)

2. Is there any other way to use the cpu version(Microsoft.ML.OnnxRuntime) and gpu version(Micorsoft.ML.OnnxRuntime.Gpu) in the same code ? 

Have a great day!

**Comment by pranavsharma** [comment]
1. No.
2. There's no need to install the CPU pkg since the GPU pkg is able to achieve both.
What issues are you facing with 1.7.0?

**Comment by gitcheol** [comment]
2. We understood that GPU package can use both cpu and gpu, but when it comes to release we need to use both cpu and gpu package. Here is why. He have users who have only cpu. Those users will not be able to use onnxruntime since onnxruntime gpu package is dependent on cuda, etc. That is why we are trying to use both dll files so any users could run onnxruntime inference.

onnxruntime issue in the 1.7.0 is that when i use the computer with RTX2080 and cuda10.2, the onnxruntime couldn`t load the onnxruntime.dll file. but the 1.6.0 version successfully loaded the file. 
Also, RTX3090 and cuda 11.2 was not compatible with 1.6.0 since it was not able to load dll file. but the 1.7.0 version successfully loaded the file. So I assume each onnxruntime version has dependency on cuda version as well? 
Dot net frame work was 4.6.2

**Comment by hariharans29** [comment]
Can your library build against contents in `Microsoft.ML.OnnxRuntime.Managed` nuget ? It has the necessary c# stuff and it is "EP-agnostic" ? Your customers can then install the appropriate EP-specific native nuget `Microsoft.ML.OnnxRuntime` or `Microsoft.ML.OnnxRuntime.Gpu` on their target deployment hardware.

And yes, the cuda version for 1.7.0 has changed which is the issue you are running into when you use 1.7 with cuda 10.2. Please check here - https://www.onnxruntime.ai/docs/get-started/install.html#windows--gpu

**Comment by gitcheol** [comment]
Thank you for replying @hariharans29 ! 
I solved this issue by installing the all the cuda related files to the bin folder. 
Additionally, Microsoft.ML.OnnxRuntime.1.7.1 also available with cuda10.2 by using these updated dll files. 

this 9 files are the GPU related files. 

cublas64_11.dll
cublasLt64_11.dll
cudart64_110.dll
cufft64_10.dll
curand64_10.dll

cudnn64_8.dll
cudnn_adv_infer64_8.dll
cudnn_cnn_infer64_8.dll
cudnn_ops_infer64_8.dll
