### ISSUE TITLE
How to do inference with multi-GPU and multi-machines

### ISSUE THREAD

**Issue by RunningLeon** [microsoft/onnxruntime#7327]
Hi,
I have an ONNX model and want to do inference with multi-GPU and multi-machines using onnxruntime-gpu. Could you provide me a sample code of how to do this? Can we wrapper the ONNX model and run using `torch.nn.parallel.distributed.DistributedDataParallel` ?
Thanks in advance.

**Comment by pranavsharma** [comment]
Can your model fit on a single GPU? If yes, you can simply create multiple sessions each tied to a different device id and call Run on them. It’s up to you to distribute the data to be fed to the individual Run calls.

**Comment by RunningLeon** [comment]
@pranavsharma Thank you for your quick response. My onnx model can run successfully with onnxruntime-gpu on a single GPU in Python. But, I don't understand `simply create multiple sessions`. Could provide a simple sample code to do this with Python API?
Thanks a lot.

**Comment by pranavsharma** [comment]
You can specify the device id when creating the sessions. See here https://github.com/microsoft/onnxruntime/blob/5d759e182b30f152ad87620371af58660e2a8b77/onnxruntime/test/python/onnxruntime_test_python.py#L63-L79.

**Comment by RunningLeon** [comment]
@pranavsharma Thanks again. Your reply helps me a lot.
