### ISSUE TITLE
Python version 1.7.0 crashes without exception for ndarray dtype float64

### ISSUE THREAD

**Issue by tkupek** [microsoft/onnxruntime#7340]
**Describe the bug**
The onnxruntime for Python crashes in version 1.7.0 if a ndarray with dtype float64 is used as an input.
I got no Error just 'process exited with status code -1'.
A downgrade to version 1.6.0 tells me that there is a problem with the dtype.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): Pip
- ONNX Runtime version: 1.7.0
- Python version: 3.8
- CUDA/cuDNN version: none / CPU inference
- GPU model and memory: none / CPU inference

**To Reproduce**
Feed a ndarray with dtype float64 into a inference session.

**Expected behavior**
Exception should be raised with a clear indication that the dtype is wrong.

**Screenshots**
none

**Additional context**
none

**Comment by hariharans29** [comment]
Can you share a minimal model that can help us repro ?

**Comment by tkupek** [comment]
Sorry for the late response, it took me some time to investigate this issue.
Turns out, the onnxruntime behavior is correct and an exception is raised:

`InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(double)) , expected: (tensor(float))`

However, I'm using [streamlit.io](https://streamlit.io/) and this lib fails when the error is raised and onnx is not imported in the main file.
