### ISSUE TITLE
Blog post link to python notebook broken (and no notebooks)

### ISSUE THREAD

**Issue by AlexMikhalev** [microsoft/onnxruntime#7351]
I tried to follow this [link](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/notebooks/Bert-GLUE_OnnxRuntime_quantization.ipynb) to this repo from a blog post which is published in March 2021 and there is no ipython notebook (or python/tools folder) in the whole repo. 
 https://cloudblogs.microsoft.com/opensource/2021/03/01/optimizing-bert-model-for-intel-cpu-cores-using-onnx-runtime-default-execution-provider/

**Comment by jcwchen** [comment]
Hi @AlexMikhalev,
The correct link should be this one: https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/notebooks/bert/Bert-GLUE_OnnxRuntime_quantization.ipynb

**Comment by faxu** [comment]
Thanks for bringing this to our attention. We'll work on fixing the link in the blog post as well.
