### ISSUE TITLE
Unable to build onnxruntime 1.6.0 from source

### ISSUE THREAD

**Issue by shuiyu486** [microsoft/onnxruntime#7355]
**Describe the bug**
Hello there! I am a newbie and want to try to build onnxruntime, but I have encountered a problem and hope to help me, thank you.
Questions are as follows:
I downloaded the onnxruntime1.6.0 source code, and when I used vs2019 Developer Command Prompt for the simplest build, it failed.
![image](https://user-images.githubusercontent.com/38516221/115015661-97b7bd80-9ee6-11eb-9724-e80662e26880.png)

**System information**
- OS Platform :windows 10 1809
- ONNX Runtime version:1.6.0
- Python version:3.9.4(Tried python3.7.0 with the same failure)
- Visual Studio version :vs2019
- CMake :3.20.1
- CPU model: Intel Core i5-8400 @ 2.80GHz

**Comment by hariharans29** [comment]
Did you pull in all submodules ?

**Comment by shuiyu486** [comment]
> Did you pull in all submodules ?
> 
> 你把所有子模块都调出来了吗？

Thank you for replying to my help, do I need any sub-modules for the CPU version of windows? I did not add any sub-modules, just run the official bat script in the source folder.

**Comment by hariharans29** [comment]
I think that you are missing dependencies and yes you need dependencies even if building CPU version for Windows. Try running:
git submodule update --init --recursive and then re-try building.

**Comment by shuiyu486** [comment]
> I think that you are missing dependencies and yes you need dependencies even if building CPU version for Windows. Try running:
> git submodule update --init --recursive and then re-try building.


> 
Thanks, I can continue to build after using "git submodule update --init --recursive", but encountered a new failure (about pthread):：
![1](https://user-images.githubusercontent.com/38516221/115223653-a00a3580-a13e-11eb-9822-d53d673fce3a.PNG)



Check CMakeError.log:
`Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: G:/SourceCode/onnxruntime-1.6.0/onnxruntime-1.6.0/build/Windows/RelWithDebInfo/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_e1e6d.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.9.0+5e4b48a27

版权所有(C) Microsoft Corporation。保留所有权利。



  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.28.29914 版

  版权所有(C) Microsoft Corporation。保留所有权利。

  src.c

  cl /c /I"C:\software\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows\include" /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D CMAKE_HAVE_LIBC_PTHREAD /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_e1e6d.dir\Debug\\" /Fd"cmTC_e1e6d.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue "G:\SourceCode\onnxruntime-1.6.0\onnxruntime-1.6.0\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\src.c"

src.obj : error LNK2019: 无法解析的外部符号 __imp_pthread_create，函数 main 中引用了该符号 [G:\SourceCode\onnxruntime-1.6.0\onnxruntime-1.6.0\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\cmTC_e1e6d.vcxproj]

src.obj : error LNK2019: 无法解析的外部符号 __imp_pthread_detach，函数 main 中引用了该符号 [G:\SourceCode\onnxruntime-1.6.0\onnxruntime-1.6.0\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\cmTC_e1e6d.vcxproj]

src.obj : error LNK2019: 无法解析的外部符号 __imp_pthread_exit，函数 main 中引用了该符号 [G:\SourceCode\onnxruntime-1.6.0\onnxruntime-1.6.0\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp\cmTC_e1e6d.vcxproj]

src.obj : error LNK2019: 无法解析的外部符号 __imp_pthread_join，函数 main 中引用了该符号 [G:\SourceCode\onnxruntime-1.6.0\onnxruntime-1.6.0\build\Windows\RelWithDebInfo\CMakeFiles\CMakeTmp`

I found that it is impossible to link to pthread, but I have put include, dll, and lib in the vs2019 directory ("C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28 .29910\...")
Both x86 and x64 compiled by me can run normally in my test project, and this problem does not occur.
How can I make it load pthreads correctly?

**Comment by liqunfu** [comment]
remove the build folder after 'git submodule update --init --recursive' and rebuild

**Comment by snnn** [comment]
You didn't install git. 

Please get it from: https://git-scm.com/download/win

Then run the build command as usual.
