### ISSUE TITLE
Problem with  symbolic shape inference for "Squeeze"

### ISSUE THREAD

**Issue by thilow** [microsoft/onnxruntime#7356]
For the Squeeze operation the shape-inference ins not working properly ***if no axes are provided***. In this case all the dimensions equal to 1 should be removed from the input-shape (see: [Squeeze](https://github.com/onnx/onnx/blob/master/docs/Operators.md#squeeze)), but currently all dimensions are removed by shape-inference, ndepended of there value. This is due to a bug in the ‘non-symbolic’ shape inference called in _onnx_infer_single_node(…) not working properly in this case.
I already tried a fix (see below), but wasn't able to set up a corresponding pull request.
If someone could look into that or tell me how to set up permissions correctly so that I can create a pr.

Thanks

Sugessted fix:
```python

    def _infer_Squeeze(self, node): 
        input_shape = self._get_shape(node, 0)

        # Depending on op-version 'axes' are provided as attribute or via 2nd input      
        axes = get_attribute(node, 'axes')
        if axes is None:
            axes = self._try_get_value(node, 1)

        if axes == None:
            output_shape = [s for s in input_shape if s != 1]
        else:
            axes = [handle_negative_axis(a, len(input_shape)) for a in axes]
            output_shape = []
            for i in range(len(input_shape)):
                if i not in axes:
                    output_shape.append(input_shape[i])

        vi = self.known_vi_[node.output[0]]
        vi.CopyFrom(
            helper.make_tensor_value_info(node.output[0], self.known_vi_[node.input[0]].type.tensor_type.elem_type,
                                          output_shape))
        self._pass_on_sympy_data(node)
```

**Comment by hariharans29** [comment]
Thank you bringing up the issue.

Is the issue in the shape inference function or in the corresponding ORT kernel ? If it is in the shape inference function, the fix needs to go into the ONNX repo, if the kernel needs a fix then it goes into the ORT repo.

AFAIK- you do not need any special permissions to send out a PR. You' ll most probably have to fork this repo, make your change in a  branch and send out a PR into master of this repo. That should be all to the best of my knowledge.

**Comment by thilow** [comment]
Thanks Hariharan! Pull-request via forking worked.
