### ISSUE TITLE
[JAVA] Cannot create an ONNXTensor of boolean scalar due to exception thrown on reshape

### ISSUE THREAD

**Issue by EmergentOrder** [microsoft/onnxruntime#7358]
I am trying to pass a boolean scalar (for the dropout op, training mode input), into ORT Java.
Because of the lack of BooleanBuffer, in order to do so I first need to use reshape from OrtUtil like so:
```OrtUtil.reshape(arr, shape)```

before passing it into ONNXTensor.createTensor

This works fine in the general case with more dimensions, but in case of a scalar, if I try using shape [], I get:
```
[info]   java.lang.IllegalArgumentException: Arrays with less than 1 and greater than 8 dimensions are not supported.
[info]   at ai.onnxruntime.OrtUtil.transformShape(OrtUtil.java:28)
[info]   at ai.onnxruntime.OrtUtil.newBooleanArray(OrtUtil.java:86)

```
with shape [1] I get:

```
[info]   java.lang.ClassCastException: [Z cannot be cast to [Ljava.lang.Object;
[info]   at ai.onnxruntime.OrtUtil.reshape(OrtUtil.java:284)
[info]   at ai.onnxruntime.OrtUtil.reshape(OrtUtil.java:179)
```

and with shape [1,1] I get:
```
[info]  ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: Node (-531443106) Op (Dropout) [ShapeInferenceError] training_mode of Dropout must be a scalar.
```

**Comment by hariharans29** [comment]
CC: @Craigacp

**Comment by Craigacp** [comment]
You shouldn't need to reshape it for a shape[1] as this works directly:
```java
jshell> var tensor = OnnxTensor.createTensor(env,new boolean[]{true})
tensor ==> OnnxTensor(info=TensorInfo(javaType=BOOL,onnxType ... DATA_TYPE_BOOL,shape=[1]))
```

However I agree the scalar creation is broken, and you should be able to make a scalar as you can get a scalar back out from an `OnnxTensor`. I'll put it on the list of things to fix.
