### ISSUE TITLE
build error: narrowing conversion...

### ISSUE THREAD

**Issue by shawncal** [Microsoft/onnxruntime#738]
**Describe the bug**
When cross-compiling for ARM32v7 following the instructions on build.md, I encounter this blocking warning-treated-as-error (see below).

The workaround is to open "tools/ci_build/build.py", search for `onnxruntime_DEV_MODE`, remove the whole line.

Recommendation:
 - make onnxruntime_DEV_MODE an option flag for build.py (i.e. "--dev_mode")

> [ 52%] Building CXX object CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc.o
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc: In instantiation of 'onnxruntime::common::Status onnxruntime::OneHotOp<in_type, out_type, depth_type>::Compute(onnxruntime::OpKernelContext*) const [with in_type = long long int; out_type = int; depth_type = float]':
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:158:1:   required from here
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:137:90: error: narrowing conversion of 'prefix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
   Eigen::array<Eigen::DenseIndex, 2> indices_dims_e = {{prefix_dim_size, suffix_dim_size}};
                                                                                          ^
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:137:90: error: narrowing conversion of '(int64_t)suffix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of 'prefix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
   Eigen::array<Eigen::DenseIndex, 3> output_dims_e = {{prefix_dim_size, depth_val, suffix_dim_size}};
                                                                                                    ^
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of '(int64_t)depth_val' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of '(int64_t)suffix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc: In instantiation of 'onnxruntime::common::Status onnxruntime::OneHotOp<in_type, out_type, depth_type>::Compute(onnxruntime::OpKernelContext*) const [with in_type = float; out_type = float; depth_type = float]':
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:158:1:   required from here
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:137:90: error: narrowing conversion of 'prefix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
   Eigen::array<Eigen::DenseIndex, 2> indices_dims_e = {{prefix_dim_size, suffix_dim_size}};
                                                                                          ^
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:137:90: error: narrowing conversion of '(int64_t)suffix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of 'prefix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
   Eigen::array<Eigen::DenseIndex, 3> output_dims_e = {{prefix_dim_size, depth_val, suffix_dim_size}};
                                                                                                    ^
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of '(int64_t)depth_val' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of '(int64_t)suffix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc: In instantiation of 'onnxruntime::common::Status onnxruntime::OneHotOp<in_type, out_type, depth_type>::Compute(onnxruntime::OpKernelContext*) const [with in_type = float; out_type = std::__cxx11::basic_string<char>; depth_type = long long int]':
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:158:1:   required from here
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:137:90: error: narrowing conversion of 'prefix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
   Eigen::array<Eigen::DenseIndex, 2> indices_dims_e = {{prefix_dim_size, suffix_dim_size}};
                                                                                          ^
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:137:90: error: narrowing conversion of '(int64_t)suffix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of 'prefix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
   Eigen::array<Eigen::DenseIndex, 3> output_dims_e = {{prefix_dim_size, depth_val, suffix_dim_size}};
                                                                                                    ^
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of '(int64_t)depth_val' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of '(int64_t)suffix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc: In instantiation of 'onnxruntime::common::Status onnxruntime::OneHotOp<in_type, out_type, depth_type>::Compute(onnxruntime::OpKernelContext*) const [with in_type = long long int; out_type = std::__cxx11::basic_string<char>; depth_type = long long int]':
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:158:1:   required from here
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:137:90: error: narrowing conversion of 'prefix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
   Eigen::array<Eigen::DenseIndex, 2> indices_dims_e = {{prefix_dim_size, suffix_dim_size}};
                                                                                          ^
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:137:90: error: narrowing conversion of '(int64_t)suffix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of 'prefix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
   Eigen::array<Eigen::DenseIndex, 3> output_dims_e = {{prefix_dim_size, depth_val, suffix_dim_size}};
                                                                                                    ^
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of '(int64_t)depth_val' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of '(int64_t)suffix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc: In instantiation of 'onnxruntime::common::Status onnxruntime::OneHotOp<in_type, out_type, depth_type>::Compute(onnxruntime::OpKernelContext*) const [with in_type = float; out_type = long long int; depth_type = long long int]':
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:158:1:   required from here
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:137:90: error: narrowing conversion of 'prefix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
   Eigen::array<Eigen::DenseIndex, 2> indices_dims_e = {{prefix_dim_size, suffix_dim_size}};
                                                                                          ^
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:137:90: error: narrowing conversion of '(int64_t)suffix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of 'prefix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
   Eigen::array<Eigen::DenseIndex, 3> output_dims_e = {{prefix_dim_size, depth_val, suffix_dim_size}};
                                                                                                    ^
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of '(int64_t)depth_val' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of '(int64_t)suffix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc: In instantiation of 'onnxruntime::common::Status onnxruntime::OneHotOp<in_type, out_type, depth_type>::Compute(onnxruntime::OpKernelContext*) const [with in_type = long long int; out_type = long long int; depth_type = long long int]':
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:158:1:   required from here
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:137:90: error: narrowing conversion of 'prefix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
   Eigen::array<Eigen::DenseIndex, 2> indices_dims_e = {{prefix_dim_size, suffix_dim_size}};
                                                                                          ^
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:137:90: error: narrowing conversion of '(int64_t)suffix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of 'prefix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
   Eigen::array<Eigen::DenseIndex, 3> output_dims_e = {{prefix_dim_size, depth_val, suffix_dim_size}};
                                                                                                    ^
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of '(int64_t)depth_val' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc:143:100: error: narrowing conversion of '(int64_t)suffix_dim_size' from 'int64_t {aka long long int}' to 'int' inside { } [-Werror=narrowing]
cc1plus: all warnings being treated as errors
CMakeFiles/onnxruntime_providers.dir/build.make:959: recipe for target 'CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc.o' failed
make[2]: *** [CMakeFiles/onnxruntime_providers.dir/code/onnxruntime/onnxruntime/core/providers/cpu/tensor/onehot.cc.o] Error 1
CMakeFiles/Makefile2:227: recipe for target 'CMakeFiles/onnxruntime_providers.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_providers.dir/all] Error 2
Makefile:140: recipe for target 'all' failed

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Building in Windows, on Linux docker
- ONNX Runtime installed from (source or binary): Building from source
- ONNX Runtime version: latest
- Python version: 3.5
- GCC/Compiler version (if compiling from source): unknown
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
Follow instructions here: https://github.com/shawncal/onnxruntime/blob/shawncal/arm7_docker_build/BUILD.md#cross-compiling-for-arm-with-docker-linuxwindows---faster-recommended

**Comment by snnn** [comment]
I know you can fix it :-)

**Comment by pranavsharma** [comment]
I'll fix the warnings.

**Comment by pranavsharma** [comment]
Will be fixed in https://github.com/Microsoft/onnxruntime/pull/870

**Comment by pranavsharma** [comment]
This is fixed now.
