### ISSUE TITLE
Avoid allocations and memory leak in performance critical loop

### ISSUE THREAD

**Issue by PhilippPaetzold** [microsoft/onnxruntime#7381]
Hello,

we have an image processing application using the OpenVino GPU Backend, where we pre-allocate two tensors for our input/output:

```cpp
   OrtOpenVINOProviderOptions options;
   options.device_type = "GPU_FP32";
   options.num_of_threads = 1;
   auto sessionOptions = Ort::SessionOptions();
   sessionOptions.AppendExecutionProvider_OpenVINO (options);

    _pSession = std::make_unique <Ort::Session>(
        Ort::Session{ _env, onnxFilePath.c_str(), sessionOptions });
    _memoryInfo = std::make_unique<Ort::MemoryInfo>(Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU));

    _output = std::make_unique<float[]> (_outputSize * 10);
    _input = std::make_unique<float[]> (_inputSize * 10);
    
    _inputOnnxTensor = Ort::Value::CreateTensor<float>(*_memoryInfo,
                                                       _input.get(), _inputSize,
                                                       _inputShape.data(), _inputShape.size());
    _outputOnnxTensor = Ort::Value::CreateTensor<float>(*_memoryInfo,
                                                        _output.get(), _outputSize,
                                                        _outputShape.data(), _outputShape.size());
```
and then in our processing loop, per camera frame, we run the network:

```cpp
    _pSession->Run(_runOptions,
                   _inputLayerNames.data(), &_inputOnnxTensor, 1,
                   _outputLayerNames.data(), &_outputOnnxTensor, 1);      
```                   
By overloading the new- and delete-operators, we can clearly see, that we get get a huge number of allocations (1551921) and deallocations (1332678) per frame increasing over time while executing the network. Our application timing then suffers over time due to the increasing number of allocations and memory fragmentation. I looked at the documentation, but I could not find a way for using memory-pooling or other techniques to stop the allocations per frame. 

It would be great, If you can point me in the right direction. For our application I try to use memory pooling where possible, to avoid such effects.

Best regards
Philipp

**System information**
- OS Platform and Distribution (Linux Ubuntu 20.04):
- ONNX Runtime installed from (source or binary): From source, build with OpenVino GPU_FP32 (openvino_2021.3.394) added via CMake flags
- ONNX Runtime version: 1.7.0
- Python version: 3.8.5
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): gcc 9.3.0
- CUDA/cuDNN version: -
- GPU model and memory: Intel(R) Gen9 HD Graphics NEO, OpenCL 2.1 NEO

**Comment by yuslepukhin** [comment]
You stack traces for the allocations would be appreciated. One thing to avoid fragmentation is not to allocate in a loop Ort objects such Ort::Session and alike. Those objects are extremely small, and their purpose to act as smart pointers to prevent leaks. So wrapping them again into smart pointers does not make sense. It is not Java.

**Comment by PhilippPaetzold** [comment]
Only run is called in the loop. Session is created during initialization, of course. Why does calling the run fuction allocate heap memory? Btw. I am a C++ and C# guy :)
________________________________

**Comment by skottmckay** [comment]
How many allocations do you see if you use the CPU execution provided (EP)  instead of the OpenVINO EP? The ORT EPs generally use arenas to minimize system calls. Not sure what OpenVINO does internally though. 

Looking at a sample of the stack traces for some of the new/delete allocations you're intercepting would also be helpful to see which library they're coming from.

**Comment by PhilippPaetzold** [comment]
@skottmckay Thanks for your reply. I will switch to CPU execution and get you the numbers and also provide some stack traces.

**Comment by PhilippPaetzold** [comment]
I did some tests with CPU execution and a simple network: [testModel_1_10_c4_w1_0.9.onnx.zip](https://github.com/microsoft/onnxruntime/files/6350161/testModel_1_10_c4_w1_0.9.onnx.zip)

```cpp
#include <iostream>
#include <string>
#include <thread>
#include <onnxruntime/core/session/onnxruntime_cxx_api.h>

bool IsHeapAllocationRecordEnabled      = false;
int NumberOfHeapAllocationsAfterStart   = 0;
int NumberOfHeapDeallocationsAfterStart = 0;

 void* operator new (size_t size)
{
    if (IsHeapAllocationRecordEnabled)
    {
        NumberOfHeapAllocationsAfterStart++;
    }

    void* p = malloc (size);
    return p;
}

 void operator delete (void* p)
{
    if (IsHeapAllocationRecordEnabled)
    {
        NumberOfHeapDeallocationsAfterStart++;
    }

    free (p);
}

int main(int argc, char** argv) {
    const int numberOfRuns{1};

    auto env = Ort::Env();

    auto sessionOptions = Ort::SessionOptions();

    sessionOptions.SetInterOpNumThreads(1);
    sessionOptions.SetIntraOpNumThreads(3);


    auto session = Ort::Session(env, "./testModel_1_10_c4_w1_0.9.onnx", sessionOptions);

    std::array<char *, 4> inputLayerNames{};
    std::array<char *, 4> outputLayerNames{};

    auto allocator = Ort::AllocatorWithDefaultOptions();
    auto inputLayerName = session.GetInputName(0, allocator);
    auto outputLayerName = session.GetOutputName(0, allocator);
    inputLayerNames[0] = inputLayerName;
    outputLayerNames[0] = outputLayerName;

    const int outputSize{4};
    auto output = std::make_unique<float[]>(outputSize);
    std::fill_n(output.get(), outputSize, 0);

    const int inputSize{10};
    auto input = std::make_unique<float[]>(inputSize);
    std::fill_n(input.get(), inputSize, rand());

    auto inputShape = session.GetInputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape();
    auto outputShape = session.GetOutputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape();
    auto memoryInfo = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU);

    inputShape[0] = 1;
    outputShape[0] = 1;
    auto inputOnnxTensor = Ort::Value::CreateTensor<float>(memoryInfo,
                                                           input.get(), inputSize,
                                                           inputShape.data(), inputShape.size());
    auto outputOnnxTensor = Ort::Value::CreateTensor<float>(memoryInfo,
                                                            output.get(), outputSize,
                                                            outputShape.data(), outputShape.size());


    IsHeapAllocationRecordEnabled = true;
    for (int i = 0; i < numberOfRuns; ++i) {
        session.Run(Ort::RunOptions(nullptr),
                    inputLayerNames.data(), &inputOnnxTensor, 1,
                    outputLayerNames.data(), &outputOnnxTensor, 1);
    }
    IsHeapAllocationRecordEnabled = false;

    std::cout << "Number of allocations: " << NumberOfHeapAllocationsAfterStart << std::endl;
    std::cout << "Number of deallocations: " << NumberOfHeapDeallocationsAfterStart << std::endl;
}
```
For the first iteration of ```session.Run(...)``` alone, I have over hundred allocations. By setting a breakpoint in my overloaded new-operator, I can see a lot of allocations from std::vector:

```
// allocation 1
std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::vector stl_vector.h:508
OrtApis::Run onnxruntime_c_api.cc:546
Ort::Session::Run onnxruntime_cxx_inline.h:530
main main.cpp:77

// allocation 2
...
std::vector<OrtValue, std::allocator<OrtValue> >::vector stl_vector.h:508
OrtApis::Run onnxruntime_c_api.cc:547
Ort::Session::Run onnxruntime_cxx_inline.h:530
main main.cpp:77
...

// allocation 3
...
std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::vector stl_vector.h:508
OrtApis::Run onnxruntime_c_api.cc:561
Ort::Session::Run onnxruntime_cxx_inline.h:530
main main.cpp:77
...
// allocation 4
...
operator new main.cpp:14
...
std::vector<OrtValue, std::allocator<OrtValue> >::vector stl_vector.h:508
OrtApis::Run onnxruntime_c_api.cc:569
Ort::Session::Run onnxruntime_cxx_inline.h:530
main main.cpp:77
...
// allocation 5
...
std::vector<onnxruntime::IExecutionProvider*, std::allocator<onnxruntime::IExecutionProvider*> >::reserve vector.tcc:78
onnxruntime::InferenceSession::Run inference_session.cc:1526
OrtApis::Run onnxruntime_c_api.cc:581
Ort::Session::Run onnxruntime_cxx_inline.h:530
main main.cpp:77
...

For some of them I can see they use a special std::allocator. Does this mean they will be using memory pools in consecutive call to ```session.Run(...)```?

**Comment by yuslepukhin** [comment]
`std::allocator` is not special, it is a standard default allocator.
`inputLayer` and `outputLayer` names and output names are supposed to be freed by the caller using the same allocator provided.. Example code has a bug. [doc](https://github.com/microsoft/onnxruntime/blob/09313d9e1f2cb526330369eee88b489b23dd2c4f/include/onnxruntime/core/session/onnxruntime_c_api.h#L494)

However, that it is just a part of the picture.

**Comment by PhilippPaetzold** [comment]
Ok, we will switch to a different framework then. Thank you for your support.

**Comment by skottmckay** [comment]
We use memory pool for all the data allocations (i.e. all the tensors and weights used during model execution), but don't override the std::allocator for things like std::string and std::vector. 

Originally you mentioned way over a million allocations when using the OpenVINO EP though, so given with the CPU EP the number of allocations seems to be much smaller there's a good chance OpenVINO is not using a memory pool (so a different framework that uses OpenVINO may have the same issue).

The 'leaking' allocator could be the allocation of a buffer for the memory pool. It will be freed when the session is freed.
