### ISSUE TITLE
building from source C api

### ISSUE THREAD

**Issue by NonaryR** [Microsoft/onnxruntime#740]
Hello! I want to use C api of onnxruntime (inference session specifically, like in Python api) in Golang and for this purpose, I need to build onnruntime, create a symlink to resulting binary file(?, not so sure in this step), and then include header-file of onnxruntime api in my golang program. I'm not experiencing C-programmer, so can someone give me and maybe some other developers short explanation of how to achieve this?
I will be very grateful!

**Comment by truh** [comment]
Have you tried using the official builds? They contain a library file for the selected platform as well as a C header file.

**Comment by NonaryR** [comment]
@truh yep, this is what I wanted, thx!
