### ISSUE TITLE
Should AllReduce scaling only happen when gradient steps > 1

### ISSUE THREAD

**Issue by ashari4** [microsoft/onnxruntime#7400]
**Is your feature request related to a problem? Please describe.**

The base `OptimizerGraphBuilder` class only adds gradient scaling nodes if the number of gradient accumulation steps is greater than 1, but the `allreduce_optimizer_graph_builder` derived class adds the gradient scaling nodes even if the number of accumulation steps is 1. 

OptimizerGraphBuilder implementation: 

https://github.com/microsoft/onnxruntime/blob/243713c4642b17c65e7561a16b6454601e0b8e38/orttraining/orttraining/core/graph/optimizer_graph_builder.cc#L479-L487

allreduce_optimizer_graph_builder  implementation:

https://github.com/microsoft/onnxruntime/blob/243713c4642b17c65e7561a16b6454601e0b8e38/orttraining/orttraining/core/graph/allreduce_optimizer_graph_builder.cc#L83

What is the reason for doing so? Should the base class implementation be matched here?

**System information**

ONNX Runtime version (you are using): 1.7.2

**Comment by souptc** [comment]
@SherlockNoMad may have a better answer, my understanding is for allreduce case ort will scale it by 1/number of workers, to you will have a scale node even accumulate step is 1.

**Comment by ashari4** [comment]
Alright - thanks. It looks like the scale node is currently applying a 1/N factor for averaging as well as another factor for scaling. Thanks.
