### ISSUE TITLE
Example with Vitis AI execution provider ?

### ISSUE THREAD

**Issue by boxerab** [microsoft/onnxruntime#7405]
I have set up a docker environment use [these](https://www.onnxruntime.ai/docs/reference/execution-providers/Vitis-AI-ExecutionProvider.html) steps. It would be great if there is an example I can use to verify that everything is working correctly with my U250 board.

**Comment by Elonaever** [comment]
the vitis-ai has provided the test example, see https://github.com/Xilinx/Vitis-AI/blob/master/external/onnxruntime/image_classification_DPUCADX8G.py

**Comment by boxerab** [comment]
Thanks @Elonaever , I got that working. For some reason, I had to run
`pip install onnx`
before it would run the script.
