### ISSUE TITLE
Question: can session manage multiple devices ?

### ISSUE THREAD

**Issue by boxerab** [microsoft/onnxruntime#7432]
For the Vitis execution provider, suppose I have two FPGAs on the system.
Can I specify that a session will only run on a specific FPGA ?

**Comment by liqunfu** [comment]
Are the two FPGAs different execution providers? If so, you provide providers to InferenceSession constructor.

**Comment by pranavsharma** [comment]
You can tie one session to a specific FPGA device id using this function. This way you can have multiple sessions each tied to its own device id. 

ORT_API_STATUS(OrtSessionOptionsAppendExecutionProvider_VITISAI, _In_ OrtSessionOptions* options, const char *backend_type, int device_id);

In Python, you can do the following:

                option1 = {'device_id': 0}
                sess.set_providers(['VitisAIExecutionProvider'], [option1])

**Comment by boxerab** [comment]
@pranavsharma thanks!
