### ISSUE TITLE
Question: plans for a Vulkan compute execution provider ?

### ISSUE THREAD

**Issue by boxerab** [microsoft/onnxruntime#7433]

**Comment by liqunfu** [comment]
Is Vulkan mainly for rendering? How much does it support DNN computation?

**Comment by boxerab** [comment]
vulkan also has compute. Here is Vulkan support in a TVM :

https://github.com/apache/tvm/tree/46e0634fb703a611b0e0f7407f10b303ccc6af81/src/runtime/vulkan

**Comment by pranavsharma** [comment]
cc @jywu-msft

**Comment by jywu-msft** [comment]
there are no plans for a vulkan compute EP

**Comment by boxerab** [comment]
@jywu-msft thanks, that's a shame.

**Comment by claforte** [comment]
IMHO anyone interested in this should look instead for https://github.com/iree-org/iree

**Comment by redthing1** [comment]
Still sad that this doesn't exist. Vulkan could be the universal GPGPU API.

**Comment by redthing1** [comment]
Still sad that this doesn't exist. Vulkan could be the universal GPGPU API.

**Comment by TechScribe-Deaf** [comment]
I agree, Iree is the way forward and it offers Vulkan SPIR-V compilation along with ROCm and CUDA compilation. It's a clear path for the future that every ML framework should switch to it.

**Comment by redthing1** [comment]
Thing is, I use some proprietary models that are already ONNX. It looks like IREE wants to support that but does not yet.
