### ISSUE TITLE
Loading onnx models from ModelProto

### ISSUE THREAD

**Issue by ganler** [microsoft/onnxruntime#7441]
**Is your feature request related to a problem? Please describe.**

I'd like to know if it is possible to have the functionality to modify and run onnx models in runtime.

A desired code snippet:

```python
import onnxruntime as ort
import onnx

model = onnx.load(path)
sess = ort.InferenceSession(model)
```

Supporting such pattern may allow applications like doing dynamic analysis for ONNX models with ONNXRuntime.

**Comment by ganler** [comment]
It seems like a "dirty" workaround can be:

```python
import onnxruntime as ort
import onnx

model = onnx.load(args.path)
sess = ort.InferenceSession(onnx._serialize(model))
```

**Comment by liqunfu** [comment]
@ganler , yes that (sess = ort.InferenceSession(onnx._serialize(model))) is the way to load a in-memory model into ORT.

**Comment by skottmckay** [comment]
You may also need to go through the serialization so that you aren't affected by any differences in the protobuf version that onnx and onnxruntime were built with. e.g. the internal in-memory layout could have subtle differences so passing bytes directly could causes crashes or other strange behavior.

**Comment by ganler** [comment]
@liqunfu @skottmckay Thank you for your advice. 

Let me conclude a bit:
1. in-memory model protobuf can be loaded by `onnx._serialize(model)`
2. loading from files/disk is more compatible in some cases (because onnxruntime can help us handle Protobufs from different library versions).
