### ISSUE TITLE
Unable to access onnxruntime testdata

### ISSUE THREAD

**Issue by toothache** [microsoft/onnxruntime#7447]
**Describe the bug**
The following onnxruntime test data links become inaccessible.
- https://onnxruntimetestdata.blob.core.windows.net/models/20191107.zip
- https://onnxruntimetestdata.blob.core.windows.net/models/20190419.zip

**Urgency**
none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10

**To Reproduce**
- Describe steps/code to reproduce the behavior.
  1. Open the browser and paste the above links
  2. Got the following error messages:
```:xml
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:3c717d36-d01e-0088-6a64-3a7c31000000 Time:2021-04-26T06:22:44.7722920Z</Message>
</Error>
```

**Expected behavior**
- Download the test data.

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by snnn** [comment]
I can sent it to you offline. We can discuss it later today.
