### ISSUE TITLE
Poor inference performance on Intel CPU

### ISSUE THREAD

**Issue by lipo5476** [microsoft/onnxruntime#7448]
Hello,

with one of our NN model we are experiencing very poor performance on Intel CPU. One inference takes 2400 ms (load of model in memory is not included) on Intel CPU, which is very slow comparing to AMD CPU - 40 ms and ARM (Jetson Xavier) CPU - 380 ms.
We have also tried different EP (Eigen, BLAS, Intel DNNL) but it has no significant impact on Intel CPU.

The flamegraphs show most of the time is spent in MlasConvNchwcFloatKernelFma3.

Is there any bug, that may be causing this issue? Does anyone else have similar problem?
Please advise.

Thank you in advance for investigation.

**Comment by tracysh** [comment]
Hi, @lipo5476, your issue could be related to #6865 (Intel denormal performance). Can you take a look at that and see if it applies to your model?

**Comment by lipo5476** [comment]
HI, @tracysh,

Great, thank you, with this configuration we the inference takes 70 ms which is significant improvement comparing to 2400 ms.

However, with multiple threads/sessions we see again a performance drop. Could you please explain how to set denormal_as_zero globally?

Thanks in advance

**Comment by tracysh** [comment]
Each session will need to set the session option flag to have any threads created by that session have the denormal_as_zero flag set. 

Updating the model to replace tiny weight values with zeroes may be the easier solution to avoid needing to configure the environment. I don't have any experience with script code to do that though.
