### ISSUE TITLE
onnxruntime==1.7.0 for aarch64

### ISSUE THREAD

**Issue by neso613** [microsoft/onnxruntime#7451]
I am trying to compile onnxruntime ==1.7.0 for aarch64.
stuck with this error.
` The CUDA compiler identification is unknown
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - failed
-- Check for working CUDA compiler: /usr/local/cuda-10.2/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-10.2/bin/nvcc - broken
CMake Error at /usr/local/share/cmake-3.20/Modules/CMakeTestCUDACompiler.cmake:52 (message):
  The CUDA compiler

    "/usr/local/cuda-10.2/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/smartcow/onnxruntime/build/Linux/Release/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_6d34f/fast && /usr/bin/make  -f CMakeFiles/cmTC_6d34f.dir/build.make CMakeFiles/cmTC_6d34f.dir/build
    make[1]: Entering directory '/home/smartcow/onnxruntime/build/Linux/Release/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_6d34f.dir/main.cu.o
    /usr/local/cuda-10.2/bin/nvcc      -c /home/smartcow/onnxruntime/build/Linux/Release/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_6d34f.dir/main.cu.o
    nvcc fatal   : Could not open output file '/tmp/tmpxft_00004b98_00000000'
    CMakeFiles/cmTC_6d34f.dir/build.make:77: recipe for target 'CMakeFiles/cmTC_6d34f.dir/main.cu.o' failed
    make[1]: *** [CMakeFiles/cmTC_6d34f.dir/main.cu.o] Error 1
    make[1]: Leaving directory '/home/smartcow/onnxruntime/build/Linux/Release/CMakeFiles/CMakeTmp'
    Makefile:127: recipe for target 'cmTC_6d34f/fast' failed
    make: *** [cmTC_6d34f/fast] Error 2
    
`
Thanks,

**Comment by jywu-msft** [comment]
provide more details? 
is this on a jetson device?
What cmake version are you using?

**Comment by neso613** [comment]
> provide more details?
> is this on a jetson device?
> What cmake version are you using?

yes, its on jetson device. Cmake version is 3.20

**Comment by jywu-msft** [comment]
let me try to reproduce on our side.
which jetson device is it exactly? and which jetpack version?

**Comment by neso613** [comment]
> let me try to reproduce on our side.
> which jetson device is it exactly? and which jetpack version?

Xavier NX and jetpack is 4.4

**Comment by jywu-msft** [comment]
I tested on a Xavier NX with jetpack 4.4. Building latest onnxruntime master branch seems okay.
It's also able to detect the cuda compiler
-- The CUDA compiler identification is NVIDIA 10.2.89
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- CMAKE_CUDA_COMPILER_VERSION: 10.2.89

Did you set environment variable export CUDACXX="/usr/local/cuda/bin/nvcc"
and follow the build instructions at
https://www.onnxruntime.ai/docs/how-to/build.html#nvidia-jetson-tx1tx2nanoxavier  ?
