### ISSUE TITLE
QDQ Optimization for MaxPool does not check Opset Version

### ISSUE THREAD

**Issue by pranav-prakash** [microsoft/onnxruntime#7460]
**Describe the bug**
As @skottmckay ran into in #7042, loading the following model on latest ORT with optimizations enabled (in particular the QDQ fusion)

https://github.com/pranav-prakash/onnxruntime-riscv/releases/download/v0.01/FAULTING_rcnn.onnx

causes an opset error, since opset 10 does not support quantized input to `MaxPool`.

>[ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(uint8)' of input parameter (7_quantized) of operator (MaxPool) in node (8) is invalid.

Because the model itself does not have a quantized input to the `MaxPool` node, I suspect that this is due to lack of opset check in the QDQ transforms

https://github.com/microsoft/onnxruntime/blob/790fc11e6012c6591a258cea15c56c4c87685b54/onnxruntime/core/optimizer/qdq_transformer/qdq_simple_ops.cc

**Urgency**
None

**To Reproduce**
Model is attached above, run with optimizations enabled

**Expected Behavior**
In the case of opset < 12, QDQ fusion should not be performed on MaxPool. Additionally, perhaps a warning could be emitted (if VLOG is enabled).

**Comment by yufenglee** [comment]
@pranav-prakash, I have a fix for the MaxPool issue, but itself is not a valid model: Node input '2799' is not a graph input, initializer, or output of a previous node. How did you generate this model?

**Comment by pranav-prakash** [comment]
@yufenglee Yes the model itself is indeed invalid (see https://github.com/microsoft/onnxruntime/pull/7042 which provides better errors for such invalid models)
