### ISSUE TITLE
CUDA kernel not found in registries for Op type: Equal

### ISSUE THREAD

**Issue by HoBeom** [microsoft/onnxruntime#7462]
**Describe the bug**
torch.eq() does not support CUDA.
cuda_execution_provider.cc:1885 GetCapability 
CUDA kernel not found in registries for Op type: Equal node name: Equal_179

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.6.0
- Python version: 3.8
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 10.2
- GPU model and memory: 2080ti

**Comment by skottmckay** [comment]
Do you have a model that reproduces the issue? The CUDA EP supports Equal, although the types supported has changed over different ONNX versions. Due to that it could be an issue with the input type to the Equal node for the opset your model is using.

**Comment by hariharans29** [comment]
If the required type is `float16`, it shipped in 1.7.0. You may want to try upgrading and trying first (noticed that you listed 1.6.0 in the issue template).

**Comment by HoBeom** [comment]
thanks. @skottmckay @hariharans29.  😄
