### ISSUE TITLE
Cant run with model.onnx and Microsoft.ML.OnnxRuntime.DirectML.1.7.0

### ISSUE THREAD

**Issue by hjtforrest** [microsoft/onnxruntime#7465]
The onnx model cannot be called normally in unity when using Microsoft.ML.OnnxRuntime.DirectML.1.7.0

use onnx model in Unity. 
move the onnxruntime.dll from Microsoft.ML.OnnxRuntime.DirectML.1.7.0 to plugin
use pytorch to onnx model

==============
System information
==============
- windows 10
- ONNX Runtime installed from (source or binary): negut (from VS2019)
- ONNX Runtime version:  Microsoft.ML.OnnxRuntime.DirectML.1.7.0
- Visual Studio version (if applicable): 2019
- CUDA/cuDNN version: 11.1
- GPU: Nvidia 3070
- (when use 2070, the Unity will crush)
============
the code
============
SessionOptions so = new SessionOptions();
so.GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_BASIC;
so.AppendExecutionProvider_DML(_GpuDeviceId);
so.ExecutionMode=ExecutionMode.ORT_SEQUENTIAL;
_Session = new InferenceSession(ModelPath, so);
==============
error from unity
==============
OnnxRuntimeException: [ErrorCode:RuntimeException] Non-zero status code returned while running Transpose node. Name:'Transpose_0' Status Message: 
Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess (System.IntPtr nativeStatus) (at <******>:0)
Microsoft.ML.OnnxRuntime.InferenceSession.RunImpl (Microsoft.ML.OnnxRuntime.RunOptions options, System.IntPtr[] inputNames, System.IntPtr[] inputValues, System.IntPtr[] outputNames, Microsoft.ML.OnnxRuntime.DisposableList`1[T] cleanupList) (at <******>:0)
Microsoft.ML.OnnxRuntime.InferenceSession.Run (System.Collections.Generic.IReadOnlyCollection`1[T] inputs, System.Collections.Generic.IReadOnlyCollection`1[T] outputNames, Microsoft.ML.OnnxRuntime.RunOptions options) (at <******>:0)
Microsoft.ML.OnnxRuntime.InferenceSession.Run (System.Collections.Generic.IReadOnlyCollection`1[T] inputs, System.Collections.Generic.IReadOnlyCollection`1[T] outputNames) (at <******>:0)
Microsoft.ML.OnnxRuntime.InferenceSession.Run (System.Collections.Generic.IReadOnlyCollection`1[T] inputs) (at <******>:0)
***.***() (at ***/***.cs:189)
***.***() (at ***/***.cs:142)
***.***() (at ***/***.cs:87)
==================
line189:
var output = _Session.Run(input);

**Comment by fdwr** [comment]
@hjtforrest Is the model proprietary, or can it be shared? If proprietary, can you share the subset of the `Transpose_0` node to see all the attributes? (e.g. dump the model to text using [this tool](https://github.com/fdwr/ConvertOnnxModel/releases) - `ConvertOnnxModel.exe yourModel.onnx output.txt`)

**Comment by hjtforrest** [comment]
Sorry, I can't talk about the details. What I can tell you is that the input data used by our network is one-dimensional, so the input data is transposed before the overall network starts, so what you see is Transpose_0. The initial network structure of our network is W1*X_T+B1.
the network start with follow:
 x = torch.transpose(x, 1, 0)

**Comment by nums11** [comment]
Closing as stale
