### ISSUE TITLE
How to get the libonnxruntime.so in tar.gz  on jetson AGX Xavier when i deploy mmdetction on Xavier

### ISSUE THREAD

**Issue by O2andsAnoxia** [microsoft/onnxruntime#7467]
I want to deploy the mmdet-onnx branch to Xavier，but the  libonnxruntime.so is  necessary to build mmcv-full and onnxruntime according to the [guide of mmdet](https://mmcv.readthedocs.io/en/latest/onnxruntime_op.html).

The ONNX Runtime version is 1.5.1 according to mmdet

Can I get the .so file except the wheel by compiling  source code.What should i do？

**Comment by jywu-msft** [comment]
On Jetson, you'll need to build from source.
you can follow these instructions: https://www.onnxruntime.ai/docs/how-to/build.html#nvidia-jetson-tx1tx2nanoxavier
except substitute step 5 with
`./build.sh --config Release --update --build --parallel --build_shared_lib --use_cuda --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu`
 to build the libonnxruntime.so

**Comment by O2andsAnoxia** [comment]
Thanks！ I'll try.
