### ISSUE TITLE
Onnxruntime - Vitis AI EP error 

### ISSUE THREAD

**Issue by HyukjunKwon** [microsoft/onnxruntime#7474]
**Describe the bug**
followed all the steps of https://www.onnxruntime.ai/docs/reference/execution-providers/Vitis-AI-ExecutionProvider.html

but it shows EP error and starts using CPU
![image](https://user-images.githubusercontent.com/36833109/116330747-24c51580-a809-11eb-97cf-9614c5ab82f4.png)

it seems `session = onnxruntime.InferenceSession("./onnx_classify.onnx", None, ["VitisAIExecutionprovider"])` this part does not work.

Other tasks(which does not use ONNXRuntime) works fine, so there is no problem with the alveo card/vitis-ai docker(maybe) 

**System information**
- OS Platform and Distribution : Ubuntu 18.04
- ONNX Runtime version: 1.7.0
- Python version:3.6.9
- Vitis-AI:1.3.4
- ONNX: 1.8.1
- Pyxir:1.6
- Vitis Alveo U200(DPUCADX8G)

**Comment by skottmckay** [comment]
@jtuyls are you able to help with this issue?

**Comment by jtuyls** [comment]
@HyukjunKwon This looks like a typo, the correct execution provider name is "VitisAIExecution**P**rovider". Could you try with that change?

**Comment by HyukjunKwon** [comment]
@jtuyls Problem solved. thanks
