### ISSUE TITLE
Is it possible to disable shape inference?

### ISSUE THREAD

**Issue by yaoyuannnn** [microsoft/onnxruntime#7486]
My ONNX model exported from TensorFlow has some shape inference issue when running it in ORT.

>bash Op (If) [ShapeInferenceError] Can't merge shape info. Both source and target dimension have values but they differ. Source=1 Target=2 Dimension=0

I'm wondering if it's possible to disable shape inference?

**Comment by snnn** [comment]
No, we don't have such an API. Sorry.

**Comment by yaoyuannnn** [comment]
Okay. Then if the shape inference in ORT is incorrect, my ONNX model can't be run. Any workaround? (Can you reopen this?)

**Comment by snnn** [comment]
Indeed it is type and shape inference, they work together.  Type inference is a must for us.  I don't think there is a way to bypass it.  If you know how to make it, welcome to contribute.

**Comment by yaoyuannnn** [comment]
I see. Can you point me to the code where this error comes from? I searched it but was only able to find it in a few test files.

**Comment by yaoyuannnn** [comment]
I guess it's actually coming from ONNX instead ORT, which means ORT uses ONNX's shape inference at some point. Is it correct?

**Comment by snnn** [comment]
Yes.

**Comment by snnn** [comment]
And sometimes it's converter issue: the converted model was wrong.

**Comment by yaoyuannnn** [comment]
Thanks. Can you point me to the code where ORT invokes ONNX's shape inference? And what's the ONNX version ORT uses for shape inference?

**Comment by yaoyuannnn** [comment]
Is this where ORT does shape inference?https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/symbolic_shape_infer.py#L339

**Comment by skottmckay** [comment]
One option is to remove the shape information from node outputs and just let onnx infer it. This can be done with the onnx python package. 

The symbolic_shape_infer.py script may also be able to correct the invalid shape info (not 100% sure but worth a try).

**Comment by skottmckay** [comment]
> Okay. Then if the shape inference in ORT is incorrect, my ONNX model can't be run. Any workaround? (Can you reopen this?)

ORT is using the shape inferencing from the ONNX schema.

The issue is that your model has an explicit value for the shape of a node output, but that shape is invalid according to the ONNX schema (assuming the ONNX - not ORT - shape inferencing logic is correct). The `If` spec hasn't changed for a while, so I believe the ONNX shape inferencing for that is valid.

**Comment by yaoyuannnn** [comment]
> One option is to remove the shape information from node outputs and just let onnx infer it. This can be done with the onnx python package.
> 
> The symbolic_shape_infer.py script may also be able to correct the invalid shape info (not 100% sure but worth a try).

Sorry for late response and thanks for providing this option. I did try this (i.e. let ONNX do the shape inference) but still ORT failed with the same error. One thing I find is the output shape of this `If` node has a dynamic shape instead of any explicit values, but removing the dynamic shapes (so the output `ValueInfoProto` only has `elem_type`) doesn't seem to work.

**Comment by skottmckay** [comment]
I'm guessing the issue is with the output of the subgraphs in the If `then_branch` and `else_branch` attributes being inconsistent, so I'd suggest checking those graph instances.

**Comment by yaoyuannnn** [comment]
Thanks for the quick response! Do you mean inconsistencies in their outputs? The `then_branch` and `else_branch` both have one output:

output {                                                                                                                                                                                                                                                                       name: "sub_graph_ending_node_Identity__110:0"                                                                                                                                                                                                                                type {                                                                                                                                                                                                                                                                         tensor_type {                                                                                                                                                                                                                                                                  elem_type: 6                                                                                                                                                                                                                                                                 shape {
                dim {                                                                                                                                                                                                                                                                          dim_param: "unk__5137"                                                                                                                                                                                                                                                     }                                                                                                                                                                                                                                                                          }                                                                                                                                                                                                                                                                          }                                                                                                                                                                                                                                                                          }                                                                                                                                                                                                                                                                          }

**Comment by yaoyuannnn** [comment]
Thanks for the quick response! Do you mean inconsistencies in their outputs? The then_branch and else_branch both have one output:

output { name: "sub_graph_ending_node_Identity__110:0" type { tensor_type { elem_type: 6 shape {
dim { dim_param: "unk__5137" } } } } }

**Comment by yaoyuannnn** [comment]
Thanks for the quick response! Do you mean inconsistencies in their outputs? The `then_branch` and `else_branch` both have one output:

```console
# Output of then_branch.
output {
  name: "sub_graph_ending_node_Identity__109:0"
  type {
    tensor_type {
      elem_type: 6
      shape {
        dim {
          dim_param: "unk__5136" }
         }
     }
  }
}

# Output of else_branch.
output {
  name: "sub_graph_ending_node_Identity__110:0"
  type {
    tensor_type {
      elem_type: 6
      shape {
        dim {
          dim_param: "unk__5137" }
         }
     }
  }
}
```

The two outputs are the same except for the dynamic shapes and the names.

**Comment by skottmckay** [comment]
What onnx opset is your model importing? The ONNX spec and shape inferencing changed for `If` a little between the original version and opset 11 (original version was stricter about the subgraph branch output shapes matching exactly).

**Comment by yaoyuannnn** [comment]
The `opset_import` in the model says 10. Let me try changing it to 11 and see if that makes any difference,

**Comment by yaoyuannnn** [comment]
Wow, after changing the opset version to 11 does make ORT run without any error.

**Comment by yaoyuannnn** [comment]
I think I may need to re-export the model with a newer opset version. Thanks a lot for the help!

**Comment by skottmckay** [comment]
Re-exporting would be recommended.

So the type/shape inferencing for the subgraphs is inferring a different shape for each. One has a value of 2 in the first dimension, the other has a value of 1. Prior to opset 11 an exact match was required, so that was the issue. 

The If spec was updated in opset 11 to be more flexible about what was allowed in terms of the subgraph outputs. 

https://github.com/onnx/onnx/blob/master/docs/Changelog.md#If-11

**Comment by yaoyuannnn** [comment]
Awesome! Thanks again for the great help!
