### ISSUE TITLE
Very slow load of ONNX model in memory especially using TensorRT EP

### ISSUE THREAD

**Issue by lipo5476** [microsoft/onnxruntime#7499]
Hi ONNX RT team,

We are experiencing very slow load of ONNX model in memory especially when using TensorRT EP on Jetson Xavier NX (50-60 seconds). On PC it takes 16 seconds with TensorRT.
Is there anything we can do to increase the performance when loading ONNX model in memory?
Is there any way of caching the optimized model during the first usage on given platform so next time the load is much faster?

Thank you in advance
Best Regards

**Comment by KyloEntro** [comment]
By using TensorRT EP, TensorRT will optimize the onnx model for your device. If caching is not enabled, it will do this step each time. 
You can force to make a cache by setting an environment variable. export ORT_TENSORRT_ENGINE_CACHE_ENABLE=1

Please read this post : https://www.onnxruntime.ai/docs/reference/execution-providers/TensorRT-ExecutionProvider.html#configuring-environment-variables

**Comment by lipo5476** [comment]
Hi KyloEntro,

That looks great, I was able to save the TensorRT engine file and profile. What is necessary to force ONNXRT to load the cached engine file instead of ONNX model?

Thank you
Marek

**Comment by KyloEntro** [comment]
Because Nvidia TensorRT use its own format to do inference by including many optimisation depends on your device.

TensorRT need to parse your ONNX model to "understand" how your model is built and convert to something it know. This step is very time consuming and optimized version is only compatible with your device, if you move the .engine file to another device, it will not work.

**Comment by lipo5476** [comment]
Thank you, I fully understand that.
I was able to improve the load of model in memory from 50 seconds to 7-10 seconds which is great.
Thanks again

**Comment by lipo5476** [comment]
Hi @KyloEntro,

one question to tensorRT engine file caching, is there version or compatibility check between the ONNX model and tensorRT engine file?
I mean, will it recognize if the ONNX model has changed and the TRT engine file is generated for the old version of ONNX model?

Thanks in advance.
Regards
