### ISSUE TITLE
input_shape in inference_test_capi

### ISSUE THREAD

**Issue by NonaryR** [Microsoft/onnxruntime#754]
Hello! I'm trying to reproduce this [test](https://github.com/Microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/InferenceTestCapi.cpp) in golang.
I create `const size_t input_shape[] = { 1, 3, 224, 224 };` and then try to pass it in [this function](https://github.com/Microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/InferenceTestCapi.cpp#L54) as `input_shape` argument. But I have this error `cannot use inputShape (type *[4]_Ctype_ulong) as type *_Ctype_ulong in assignment`.
Can you help me?

**Comment by NonaryR** [comment]
and in this [test](https://github.com/Microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp#L60)  mentioned that `simplify... this model has only 1 input node {1, 3, 224, 224}.`
But in args [of](https://github.com/Microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h#L301) `OrtCreateTensorWithDataAsOrtValue`  I need to pass a `_In_ const int64_t* shape` - is it vector?

**Comment by NonaryR** [comment]
@jignparm I see you commits in [this test](https://github.com/Microsoft/onnxruntime/commit/acc8ac58d217c1f2d571d35e7b3e947f84431456), maybe you can help me?

**Comment by jignparm** [comment]
@NonaryR - yes, this is a consecutive list of int64_t values. This is a recent API change (the input node dimensions used to be of type **size_t**, but are now **int64_t**). The test file you're referring to is not used (will be removed). 

See the very similar example file below instead, which is updated to use a vector of **int64_t** for the input node dimensions.

    std::vector<int64_t> input_node_dims;  // simplify... this model has only 1 input node {1, 3, 224, 224}.
 https://github.com/Microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp#L124

**Comment by NonaryR** [comment]
@jignparm thx! may you please provide a way to run this test? 
I want to debug it and compare with my implementation
I'm not familiar with cpp at all (

**Comment by jignparm** [comment]
There are a couple of options, assuming Visual Studio is installed  (2017 preferably).

* From command line
  * Setup VS environment variables (E.g. Run "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat")
  * Make sure **NuGet.exe** is on accessible from the command line
  * **set IsReleaseBuild=1**
  * **cd onnxruntime\csharp**
  * run "**test\Microsoft.ML.OnnxRuntime.EndToEndTests.Capi\runtest.bat c:\packagesFolder**", where packagesFolder contains the latest NuGet package https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/

* From Visual Studio directly
  * Open a empty C++ project
  * Install the NuGet package from the link above
  * Copy the sample into Program.cs
  * Make sure **model_path** variable in the sample is pointing to the correct model location
  * Build and run

Closing issue. Please reopen if needed.
