### ISSUE TITLE
Error : convert onnx to ort

### ISSUE THREAD

**Issue by garymmi** [microsoft/onnxruntime#7547]
Describe the bug
dear all,
I followed the[ ONNX_Runtime_for_Mobile_Platforms.md](https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_for_Mobile_Platforms.md) to convert onnx model to ort format, but met the error
no more detail error message
how to fix the bug?
Thanks
```
python -m onnxruntime.tools.convert_onnx_models_to_ort  models/
Converting optimized ONNX model /home/nick/models/model.onnx to ORT format model /home/nick/models/model.all.ort
ORT Telemetry: Ver = 1.7.0; Event = SessionCreation
Error converting /home/nick/models/model.onnx: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : ONNX format model is not supported in this build.
Converted 1 models. 1 failures.
2021-05-02 14:56:45,614 ort_format_model.utils [INFO] - Created config in /home/nick/models/required_operators.config

```
System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
ONNX Runtime installed from (source or binary): source
ONNX Runtime version: 1.7.0
Python version: 3.6.9

To Reproduce
[model.onnx](https://drive.google.com/file/d/1EdOfhjSalGyhQPU49k1EcsJcXPOFGQmR/view?usp=sharing)

**Comment by skottmckay** [comment]
You need to use a 'full' ONNX Runtime build to do the model conversion. Easiest is to install the onnxruntime python package using pip. The minimal build package is only used to run the model.

**Comment by garymmi** [comment]
rebuild the whl file from source without --minimal_build
solved the problem
thank you very much
