### ISSUE TITLE
Support retrieving more attributes types in C API

### ISSUE THREAD

**Issue by harrysummer** [microsoft/onnxruntime#755]
As of writing this issue, the [`OrtCustomOpApi` interface](https://github.com/Microsoft/onnxruntime/blob/06888437dd4270b07531253673460bb26e9630ee/include/onnxruntime/core/session/onnxruntime_c_api.h#L544) can only get the float and int64 argument for the custom op. This forbids user from defining operator arguments of strings and lists. Eventually we should be able to support all ONNX attribute types listed [here](https://github.com/onnx/onnx/blob/a8b45d62de57ab9b25d7764e38e44f5e9e9c027a/onnx/onnx.proto#L95).

**Comment by faxu** [comment]
@harrysummer is there still intention to complete this PR?

**Comment by harrysummer** [comment]
Hello. This is an issue. Not a PR. PR #778 is ready from my side. I can rebase it again if you want but the current build errors are not be caused by the PR as far as I understanding.
