### ISSUE TITLE
fail to load ORT format model

### ISSUE THREAD

**Issue by garymmi** [microsoft/onnxruntime#7553]
**Describe the bug**
follow "ONNX Runtime for Mobile Platforms" to produce the smallest binary size of libonnxruntime.so
$ ./build.sh --config=MinSizeRel --build_shared_lib --minimal_build --disable_ml_ops --disable_exceptions --include_ops_by_config required_operators_and_types.config --skip_tests --parallel

when loading ORT format model, it showed the error message
```
terminate called after throwing an instance of 'Ort::Exception'
  what():  inference_session.cc:1025 LoadOrtModel The ORT format model version [4] is not supported this build 1.7.0
Aborted
```

C++ code
```
      Ort::Env env;

      Ort::SessionOptions session_options;
      session_options.AddConfigEntry("session.load_model_format", "ORT");
      Ort::Session session(env, "model.ort", session_options);
```
any suggestion?
thanks

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.7.0
- Python version: 3.7.8
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):7.5.0
- CUDA/cuDNN version: 
- GPU model and memory:

**Comment by skottmckay** [comment]
There was a recent change to how the kernels are looked up which required updating the ORT format version. Unfortunately this change wasn't backwards compatible. 

If you wish to use the latest source you'll need to generate the ORT format model using that (easiest would be to use the nightly onnxruntime python package `pip install -i https://test.pypi.org/simple/ ort-nightly`). Alternatively, you can use the onnxruntime 1.7 python package if you create a minimal build using the `rel-1.7.0` tag (`git checkout rel-1.7.0`)

**Comment by garymmi** [comment]
thank for your reply
here are my steps to run ort model
after pip install org-nightly, and then converted the onnx model to ort model
```
Converting optimized ONNX model /models/model.onnx to ORT format model /models/model.all.ort
ORT Telemetry: Ver = 1.7.0; Event = SessionCreation                   
2021-05-04 06:27:57.517824212 [W:onnxruntime:, inference_session.cc:1294 Initialize] Serializing optimized model with Graph Optimization level greater than ORT_ENABLE_EXTENDED. The generated model may contain hardware
and execution provider specific optimizations, and should only be used in the same environment the model was optimized for.
Converted 1 models. 0 failures.
```

$ git clone https://github.com/microsoft/onnxruntime.git onnxruntime-night && cd onnxruntime-night
$ git checkout rel-1.7.0
$ ./build.sh --config=MinSizeRel --build_shared_lib --minimal_build --disable_ml_ops --disable_exceptions --include_ops_by_config  /models/required_operators.config --skip_tests --parallel

copy build/Linux/MinSizeRel/libonnxruntime.so.1.7.0 and then link , build test command
but still showed the error message
terminate called after throwing an instance of 'Ort::Exception'
  what():  inference_session.cc:1025 LoadOrtModel The ORT format model version [4] is not supported this build 1.7.0
Aborted (core dumped)

**Comment by skottmckay** [comment]
If you use the nightly pip package you should build with 'master' (the ORT model format version should be '4' in that case). 
If you use the 1.7 release pip package you should build with 'rel-1.7.0' (the ORT model format version should be '3' in that case).

**Comment by garymmi** [comment]
it worked, thank you very much
finally got libonnxruntime.so , only  998K  size

**Comment by BioWar** [comment]
@skottmckay Hi, I have a similar error during the **.ort** model loading in my Java Android application. The model worked perfectly in **.onnx** format with an **opset=13**, but I am unable to load it as **ByteArray** in the Android project from resources. Here is the code which I used for model loading:

```
OrtEnvironment env = OrtEnvironment.getEnvironment();
OrtSession.SessionOptions opts = new SessionOptions();

InputStream inStr = this.getResources().openRawResource(R.raw.model);
byte[] modelOrt = new byte[inStr.available()];

OrtSession session = env.createSession(modelOrt, opts);
```
The error:
```

W/System.err: ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: ONNX format model is not supported in this build.
W/System.err:     at ai.onnxruntime.OrtSession.createSession(Native Method)
        at ai.onnxruntime.OrtSession.<init>(OrtSession.java:89)
        at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:261)
        at ai.onnxruntime.OrtEnvironment.createSession(OrtEnvironment.java:235)
W/System.err:     at com.example.onnxruntimeaartest.MainActivity.onCreate(MainActivity.java:50)
        at android.app.Activity.performCreate(Activity.java:7326)
        at android.app.Activity.performCreate(Activity.java:7317)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3066)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

The model conversion environment packages in "`pip freeze`" output: 

```
flatbuffers==2.0
numpy==1.22.4
onnx==1.9.0
onnxruntime==1.11.1
protobuf==3.20.0
six==1.16.0
typing-extensions==4.2.0
```

Command for model conversion from **onnx to ort**:
`python -m onnxruntime.tools.convert_onnx_models_to_ort model.onnx`

Also, I have built minimal_build for onnxruntime library in aar format with this command:

```
./build.sh --android \
--android_sdk_path /home/pvorotyntse/Android/Sdk/ \
--android_ndk_path /home/pvorotyntse/Android/Sdk/ndk/24.0.8215888/ \
--android_abi arm64-v8a \
--android_api 24 \
--include_ops_by_config model.required_operators.config  \
--minimal_build \
--build_shared_lib \ 
--config=Release \
--skip_tests \
--build_java
```

**onnxruntime-release.aar** package was built successfully, but the model could not be loaded with it.

Latest commit in my onnxruntime git repository is this one:
```
commit e45197fa8cc32310ca4e994d1fdb7304a5bc94b0 (HEAD -> master, origin/master, origin/HEAD)
Author: Adrian Lizarraga <adlizarraga@microsoft.com>
**Date:   Wed May 18 15:36:21 2022 -0700**
```


Where did I make a mistake?

**Comment by skottmckay** [comment]
@BioWar sorry - didn't see this as the issue was closed.

One thing to try is setting a session option to explicitly say it's ORT format.

OrtSessionOptions has an [addConfigEntry](https://github.com/microsoft/onnxruntime/blob/d5a1c01b382768bd7edf7681a7c57667c48282da/java/src/main/java/ai/onnxruntime/OrtSession.java#L727-L734) method.

Call that with a configKey of "session.load_model_format" and configValue of "ORT" to explicitly say it's an ORT format model.

It's a little strange though - we don't need to set that in our example android app to be able to load the model. The ORT code should auto-detect an ORT format model, which has a marker with 'ORTM' at the start of it. Due to that I'm wondering if the raw bytes are not being saved/read correctly.
