### ISSUE TITLE
Build with MPI on Windows

### ISSUE THREAD

**Issue by ashari4** [microsoft/onnxruntime#7554]
**Is your feature request related to a problem? Please describe.**

I would like to use the [MPIContext class](https://github.com/microsoft/onnxruntime/blob/master/orttraining/orttraining/core/framework/communication/mpi/mpi_context.cc) on Windows. 

This requires that onnxruntime be built with MPI, which is only supported on Unix platforms:

https://github.com/microsoft/onnxruntime/blob/79dc7d3e50dce9be46780c64d414e6107c30693c/cmake/CMakeLists.txt#L1492

**System information**
- ONNX Runtime version (you are using): 1.7.2

**Describe the solution you'd like**
I would like the ability to build onnxruntime with MPI on Windows. It seems like adding an else block here may suffice:

https://github.com/microsoft/onnxruntime/blob/79dc7d3e50dce9be46780c64d414e6107c30693c/cmake/CMakeLists.txt#L1492

**Additional context**
I am building the onnxruntime training library 

https://github.com/microsoft/onnxruntime/blob/5bc92dff16b0ddd5063b717fb8522ca2ad023cb0/cmake/onnxruntime_training.cmake#L18

as a static library and then consuming this static library from an external project. 

**Describe alternatives you've considered**

Not using the MPIContext class and instead querying MPI directly in my external project.

**Comment by ashari4** [comment]
It looks like MPIContext is rather Unix-specific. For example, it has a reference to `MPI_Comm_create_group`, which does not exist in Microsoft MPI (MS-MPI)

https://github.com/microsoft/onnxruntime/blob/7079dfb93dc16119b1ec030525b2e4a401942daf/orttraining/orttraining/core/framework/communication/mpi/mpi_context.cc#L158

**Comment by ytaous** [comment]
Hi, @ashari4 - thanks for reaching out.  
For the reason of fast performance, our primary focus is leverage the training speed on linux, thus MPI is only enabled for linux at the moment (as training on Windows will be **slow**). However, I'll tag this with enhancement for future consideration.
