### ISSUE TITLE
Build Broken with cmake option onnxruntime_BUILD_UNIT_TESTS=OFF

### ISSUE THREAD

**Issue by ankurverma85** [microsoft/onnxruntime#7571]
**Describe the bug**
Using the cmake option onnxruntime_BUILD_UNIT_TESTS=OFF results in cmake generate error

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
All

**To Reproduce**
cmake -Donnxruntime_BUILD_UNIT_TESTS=OFF

**Expected behavior**
Generates properly

**Screenshots**

**Additional context**

**Comment by ytaous** [comment]
Hi, more details please.
which part of the instruction you are trying to follow? 
did you try build command (e.h., build.sh) to build instead? If using build cmd, can you try to add --cmake_extra_defines onnxruntime_BUILD_UNIT_TESTS=OFF at the end of the cmd and see?
what's the full error stack you are getting?

**Comment by ankurverma85** [comment]
I'm mostly using custom build instructions but I had a change to dig into that a little more and here's more details (with perhaps a fix)

The problem happens when you say 
-Donnxruntime_BUILD_UNIT_TESTS=OFF 
and
-Donnxruntime_ENABLE_TRAINING=ON

What happens is that because because BUILD_UNIT_TESTS is OFF the cmake file onnxruntime_unittest.cmake doesnt get included which defines the variable TEST_SRC_DIR
https://github.com/microsoft/onnxruntime/blob/94c97ac8c2b2d9459e054a304cdc985ea9499dfa/cmake/onnxruntime_unittests.cmake#L7

The variable is used in onnxruntime_training.cmake here:

https://github.com/microsoft/onnxruntime/blob/94c97ac8c2b2d9459e054a304cdc985ea9499dfa/cmake/onnxruntime_training.cmake#L49

The exact error occurs at
https://github.com/microsoft/onnxruntime/blob/94c97ac8c2b2d9459e054a304cdc985ea9499dfa/cmake/onnxruntime_training.cmake#L93

because TEST_SRC_DIR expands to empty and the paths dont line up.


perhaps the right fix would be to simply not use the variable but 
use ${ONNXRUNTIME_ROOT}/test
A better yet fix would probably be to check if we're building UNITTESTS or not in  onnxruntime_training.cmake and put them under the right IF

**Comment by ytaous** [comment]
@ankurverma85 0 I can repro the issue with:
./build.sh --config RelWithDebInfo --use_cuda --enable_training --skip_tests --parallel --cmake_extra_defines onnxruntime_BUILD_UNIT_TESTS=OFF

wo/ --enable_training, it will build. 

Is there any particular use case for this combination? This sounds like enhancement and welcome to contribute.

**Comment by ytaous** [comment]
close it for now

**Comment by drux007** [comment]
Hi,

I am also trying to build onnxruntime with `-Donnxruntime_BUILD_UNIT_TESTS=OFF` option to speed up the build process and it fails when I try to link onnxruntime against other static libraries in my application.

The error I get:
```bash
/usr/bin/ld: .../lib/libonnxruntime_session.a(ort_env.cc.o): in function `OrtEnv::GetInstance(OrtEnv::LoggingManagerConstructionInfo const&, onnxruntime::common::Status&, OrtThreadingOptions const*) [clone .cold]':
ort_env.cc:(.text.unlikely._ZN6OrtEnv11GetInstanceERKNS_30LoggingManagerConstructionInfoERN11onnxruntime6common6StatusEPK19OrtThreadingOptions+0x49): undefined reference to `nsync::nsync_mu_unlock(nsync::nsync_mu_s_*)'
```
