### ISSUE TITLE
Failed to find kernel for Transpose(1)

### ISSUE THREAD

**Issue by seungillee** [microsoft/onnxruntime#7575]
**Describe the bug**
According to the following document
https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_for_Mobile_Platforms.md
I built onnxruntime binary as following command

```
build.sh --config MinSizeRel --parallel --minimal_build --disable_exceptions --include_ops_by_config required_operators.config --disable_ml_ops --skip_tests
```

The `required_operators.config` was as follows;

```
com.microsoft;1;DynamicQuantizeLSTM,DynamicQuantizeMatMul
ai.onnx;11;Cast,Concat,ConstantOfShape,DequantizeLinear,DynamicQuantizeLinear,Gather,Gemm,LSTM,MatMulInteger,Mul,ReduceSum,Reshape,Shape,Slice,Softmax,Squeeze,Tanh,Transpose,Unsqueeze
com.microsoft;1;DynamicQuantizeMatMul,FusedGemm
ai.onnx;10;Gemm,Softmax,MatMul
ai.onnx;12;Add,Cast,Concat,ConvInteger,DequantizeLinear,Div,DynamicQuantizeLinear,Flatten,Floor,Gather,MaxPool,Mul,Relu,Reshape,Softmax,Transpose
```

However when loading the model it shows the error as follows;

```
Failed to find kernel for Transpose(1) (node TransposeFanIn_succ_0). Op with name (TransposeFanIn_succ_0) and type (Transpose) kernel not found in CPUExecutionProvider. No matching hash for 17836100118787085512
```

I guess the error message means the onnxruntime binary does not have `Transpose` operator, but as you might see in the `required_operators.config`, it has `Transpose` operator, so I don't understand why this happens.

**Urgency**
This did not happen in the version 1.6.0, but after we updated onnxruntime to the most recent version, this error appeared. Until this issue is solved, we cannot update onnxruntime version.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Big Sur (Version 11.3)
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.7.2
- Python version: 3.6
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): Apple clang version 12.0.5 (clang-1205.0.22.9)
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**
The model should be loaded without error.

**Screenshots**
n/a

**Additional context**
n/a

**Comment by seungillee** [comment]
One follow-up question. I was using ort file created with onnxruntime v1.6.0. Could it be possible that it cannot work with onnxruntime v1.7.2?

**Comment by ytaous** [comment]
@skottmckay - any thought?

**Comment by snnn** [comment]
Which opset the model uses?

**Comment by skottmckay** [comment]
For now it's safest to create the ORT format model with the same version of ORT you want to run it with. We're refining a few things in these early versions, and the kernel hashes have changed a couple of times to make them more robust. When that happens, an ORT model created with an older version of ORT won't load with a newer version.

In the near future we expect to be able to offer a backwards compatibility guarantee for ORT format models.

**Comment by skottmckay** [comment]
Note that you just need to re-convert the ONNX model using the ONNX Runtime 1.7.2 python package. You don't need to rebuild ONNX Runtime.

**Comment by seungillee** [comment]
Thanks for the replies. I tried with the re-converted ort file, and it works.
