### ISSUE TITLE
Support for non NCCL implementations 

### ISSUE THREAD

**Issue by ashari4** [microsoft/onnxruntime#7582]
**Is your feature request related to a problem? Please describe.**

I would like to run a data-parallel Python script without using NCCL. At the moment, there does not exist a way to specify that NCCL should not be used in the ORTTrainer API. 

As a hack, the python script can set `allreduce_post_accumulation` to False:

https://github.com/microsoft/onnxruntime/blob/1012535dabedd75e8b29e567e3edcaac64067752/orttraining/orttraining/python/training/orttrainer_options.py#L126

This internally sets a `use_nccl` flag to false:

https://github.com/microsoft/onnxruntime/blob/1012535dabedd75e8b29e567e3edcaac64067752/orttraining/orttraining/python/orttraining_pybind_state.cc#L212

However, in the runtime, there seems to be a requirement to use AdaSum reduction, which I don't want.

https://github.com/microsoft/onnxruntime/blob/6714f2f85d6af8912dd0027d6364b988ad41278e/orttraining/orttraining/core/graph/allreduce_optimizer_graph_builder.cc#L60

**System information**
- ONNX Runtime version (you are using): 1.7.2

**Describe the solution you'd like**
A `use_nccl` key in the distributed schema of the ORTTrainer options object. If this key is set to False, then onnxruntime will not use NCCL. Also, the onnxruntime should permit non-NCCL implementations without requiring the AdaSum reduction.

**Describe alternatives you've considered**

As mentioned in the description, the python script can set `allreduce_post_accumulation` to False.

**Additional context**
I am experimenting with non-NCCL implementations of AllReduce.

**Comment by ytaous** [comment]
@ashari4 - this won't likely be prioritized as enhancement for future release. We are moving toward ORTModule feature (coming soon) - and NCCL symbols won't used anymore.
