### ISSUE TITLE
Build failures with GCC11 and LibStdc++11

### ISSUE THREAD

**Issue by ankurverma85** [microsoft/onnxruntime#7583]
**Describe the bug**
The following failures occur with GCC11 and libstdc++11 (bundled with fedora 34)

1. 
-Werror=maybe-uninitialized 
while compiling 
googletest

Mitigated by
```diff
--- a/cmake/CMakeLists.txt
+++ b/cmake/CMakeLists.txt
@@ -420,6 +420,7 @@ if(onnxruntime_CROSS_COMPILING)
   endif()
 endif()

+string(APPEND CMAKE_CXX_FLAGS " -Wno-maybe-uninitialized")
 # Mark symbols to be invisible, for macOS/iOS target only
 # Due to many dependencies have different symbol visibility settings,
 # set global compile flags here.
 if (${CMAKE_SYSTEM_NAME} MATCHES "Darwin|iOS")
```

2.

```c++
include/onnxruntime/core/graph/graph_nodes.h:103:29: error: expected unqualified-id before ‘const’
  103 |     NodeIterator<TIterator>(const TIterator current, const TIterator end, const NodeFilterFunc& filter_fn) noexcept
      |                             ^~~~~
```
`NodeIterator<TIterator>` needs to change to `NodeIterator`

**Urgency**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Fedora 34
- ONNX Runtime installed from (source or binary): Source
- ONNX Runtime version: master
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 11, libstdc++11
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
Should be obvious

**Expected behavior**
Builds successfully

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by snnn** [comment]
Welcome to contribute your change!

**Comment by ankurverma85** [comment]
am i to believe you're ok supressing  -Wno-maybe-uninitialized throughout the codebase ?
I was quite happy seeing stricter compilation enabled on the onnxruntime repo and i would hate to contribute a change to loosen that.
 -Wno-maybe-uninitialized doesnt seem like a warning that should be ignored however it comes from googltest so i'm not sure what the right fix here is.
perhaps the fix is to get this fixed in googletest and migrate to a newer version but i'd let you decide .
 
 the snippet is something i'm locally unblocking myself with and merely meant to provide a indication of what the issue is.
 
 i dont mind pushing the change if you're ok suppressing that throughout .. but i'm hoping you're not :)

**Comment by snnn** [comment]
It depends whether the warning is from googletest's cc files or header files that are used by onnxruntime source files. 
If it is the first case, then you don't need to suppress it. our build pipelines do not treat them as error.
If it is the second case, it is more complicated.  You need do things like https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/graph/onnx_protobuf.h

**Comment by ankurverma85** [comment]
It is cc files and so it appears this one escaped your suppression list?

**Comment by ankurverma85** [comment]
https://github.com/microsoft/onnxruntime/pull/7599
