### ISSUE TITLE
Fully support adaptive max/avg pooling

### ISSUE THREAD

**Issue by dashesy** [Microsoft/onnxruntime#760]
**Is your feature request related to a problem? Please describe.**
PyTorch has [AdaptiveMaxPool2d](https://pytorch.org/docs/stable/nn.html#adaptivemaxpool2d) but currently the converter only can do a global pooling. Adaptive pooling is necessary when the feature size could vary but the output size is fixed, so I cannot use normal pooling and adjust parameters in `forward` because those parameters will be different for each size of `dummy_input` .
I see you have a `roi_pooling`, can it be generalized to use as adaptive pooling too (single ROI of entire image, with fixed given output size instead of a ratio)?

```python
@parse_args('v', 'is')
def adaptive_max_pool2d(g, input, output_size):
    assert output_size == [1, 1], "Only output_size=[1, 1] is supported"
    return g.op("GlobalMaxPool", input), None
```

**System information**
- ONNX Runtime version (you are using): 0.3.0

**Describe the solution you'd like**
Support adaptive pooling

**Describe alternatives you've considered**
See if I can pass pooling parameters as input (instead of parameter), and thus use normal pooling adaptively.

**Comment by faxu** [comment]
@dashesy : Please check if the updated opset10 maxpool and averagepool updates address this. ONNX Runtime 0.4 will support opset 10 definitions once ONNX 1.5 is released. 

In the future, please file onnx spec operator issues in the onnx github :) https://github.com/onnx/onnx/issues
We align runtime implementation with the onnx spec. Thanks!
