### ISSUE TITLE
CreateTensor() crashing within threaded function c++

### ISSUE THREAD

**Issue by stevenewbold** [microsoft/onnxruntime#7618]
**Describe the bug**
I have an existing plugin that uses a library to perform inference of a Keras model and I'm looking to see if there can be performance gains by instead using ORT instead without a big overhaul and using an ONNX version of the model.

The plugin performs many inferences of small tiles of image data and is currently setup to do inference with individual threads and this worked fine with the exiting inference library but was slow.  I've created a session within a unique::ptr which is accessed by the worker threads.  Everything compiles fine but I'm finding that Ort::Value::CreateTensor crashes when I try to use multiple threads, but works fine when I force the host application to use a single thread.

I'm presuming something I'm doing here isn't thread safe.  I'm storing the data as a std::vector, trying to create the tensor and run the inference all within the same worker thread.

```
Ort::MemoryInfo memory_info = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU);

Ort::Value input0_tensor = Ort::Value::CreateTensor<float>(memory_info, input0_tensor_values.data(), input0_tensor_values.size(), input0_node_dims.data(), 4);
```

Are there any obvious things I'm missing that means this couldn't work?  I've validated the input data is correct so I'm really confused why 'CreateTensor()' specifically is causing the plugin to crash with threading.  Commenting out CreateTensor lets things work fine up to that point with one or many threads.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.7
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.7.1
- GCC/Compiler version (if compiling from source):  Clang 12.0.0

**To Reproduce**
Create a tensor using ort::Value:CreateTensor within a threaded function using multiple threads.

I'm trying to force ORT to run with a single thread using,

```
Ort::SessionOptions session_options;
session_options.SetIntraOpNumThreads(1);
session_options.SetInterOpNumThreads(1);

session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
onnxSession = std::make_unique<Ort::Session>(*onnxEnv.get(), model_path, session_options);
```

**Comment by pranavsharma** [comment]
Can you provide the full repro code?

**Comment by stevenewbold** [comment]
Apologies.  Please ignore this.  I had issues with the dimensions in my model.  Not entirely sure if its a problem with the conversions from Keras model to Onnx model as I'm super new to Onnx.  For some reason if I check the dimensions of my input it says (1, 3, 64, 64) however to successfully create the tensor and run inference I need to change to (1, 64, 64, 3).

Anyway, I can now create the tensors and run inference from my threads.

**Comment by stevenewbold** [comment]
In case it's of interest swapping from Frugally Deep (header only lib for Keras models) to Onnxruntime with a custom model on the same machine and otherwise identical code has resulted in approximately a 300% speed increase which isn't too shoddy.  This is all running on a CPU, so I'm hoping testing this on a Linux machine with a high-end Nvidia GPU will dramatically increase this again.
