### ISSUE TITLE
[ORT] Inconsistency output from Gemm operator

### ISSUE THREAD

**Issue by Distancehe** [microsoft/onnxruntime#7642]
**Describe the bug**
The model is loading by ORT (C#) with GraphOptimizationLevel=ORT_ENABLE_ALL.
Detailed operator property as below,
![image](https://user-images.githubusercontent.com/4394577/117754126-4af8a580-b24c-11eb-892b-e9bcf560b4e9.png)

For inputs B, C, they are const metrix with [64, 512] and [1, 64] dimensions.

For input A, we tried with 2 metrix A1 and A2 and found the operator outputs are different.
The first input A1 has [1, 512] dimension, and the second A2 has [2, 512] dimension, the content from each dimension of A2 is same with A1. For example, A1 is [0.1, 0.2, 0.3] and A2 is [[0.1, 0.2, 0.3], [0.1, 0.2, 0.3]].

The output for A1 is [1, 64] dimension while A2 is [2, 64], but each [1, 64] metrix from A2 output is not exactly same with A1, there are always precision difference as shown below (left: output for A; right: output for B):
![image](https://user-images.githubusercontent.com/4394577/117753964-f9e8b180-b24b-11eb-8c81-76e9b89fc5e6.png)

Is this expected for this operator or any suggestion to get consistency result ?

**Urgency**
Blocked by this issue when evaluating model batch inference.

**System information**
- OS Platform and Distribution : Windows
- ONNX Runtime installed from : binary
- ONNX Runtime version: Latest

**Expected behavior**
Expected to get same output from A and each dimension of B.

**Screenshots**
See above.

**Comment by ytaous** [comment]
@Distancehe - do you have reproducible code and steps to share?

@yuslepukhin - thought?

**Comment by Distancehe** [comment]
@yuslepukhin, the compressed model is about 246 MB, how to sharing for your easy access ?

For the Gemm operator, the const input B, C is from below zip file, and input A is [N * 512] float metrix
[Data.zip](https://github.com/microsoft/onnxruntime/files/6463928/Data.zip)

**Comment by yuslepukhin** [comment]
@Distancehe are you computing this on CPU or CUDA, just to clarify.

**Comment by Distancehe** [comment]
@yuslepukhin , it's CPU computing. For C#, the output is same for single and multiple dimension metrix which is:
foreach (var r in batchResults)
{
                   var resultTensor = r.AsTensor<float>();
                        var resultList = resultTensor?.ToList();
                        var resultStr = resultTensor?.GetArrayString();

                        if (r.Name == "qvec")
                            Console.WriteLine(resultStr);
}

**Comment by yuslepukhin** [comment]
@Distancehe what does the debugger show? GetArrayString() makes use of StringBuilder class that actually does not have an overload for float, so it converts it to double. I assume that the output type is float.

I would look in the debugger first.
Can you simply iterate through the list of values and specify how you want to print it? 

For example:

`foreach( float v in resultList)
{
   Console.WriteLine(value.ToString("0.00000000",
                  CultureInfo.InvariantCulture));
}`

See [Custom specifier](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings#the-0-custom-specifier)

**Comment by yufenglee** [comment]
Add @tracysh for FYI.

@Distancehe , this is expected as long as the difference is smaller than a criteria, e.g., 1e-5. Floating point can not be represented exactly, and computation order can/will introduce difference. The simple code like below introduces difference:

`    float f1 = 1e-9;
    float f2 = 0.f;
    for (int i = 0; i < 1024; i++) {
        f2 += f1;
    }

    float f3 = f1;
    for (int i = 0; i < 10; i++) {
        f3+=f3;
    }

    std::cout<<"f2:" << f2 <<",f3:"<<f3<<",diff:"<<f2-f3<<std::endl;
`

**Comment by yufenglee** [comment]
BTW, there will also be difference for same matrix multiplication on different hardware, e.g., it is expected you get difference results on CPUs with different arch, and CPU vs GPU.

**Comment by hariharans29** [comment]
This is the CPU equivalent of this issue: https://github.com/microsoft/onnxruntime/issues/4611. 

ORT never guarantees the output of a graph run will be deterministic, as already pointed out above it only guarantees that results are "equivalent" or "stable" across runs (i.e.) results differ within some acceptable tolerance range.

**Comment by Distancehe** [comment]
Thanks all for the explanation !

**Comment by jcdatin** [comment]
on my faster-rcnnn network inference , I fixed my non determinism by replacing GraphOptimizationLevel::ORT_ENABLE_ALL with GraphOptimizationLevel::ORT_DISABLE_ALL (variability was very small though with GraphOptimizationLevel::ORT_ENABLE_ALL : 10e-7 for confidence score and 10-e4 for box coordinates. Got a inference exeution time regression of <5%
