### ISSUE TITLE
Non-zero status code returned while running TopK node Name:"" status Message:type not supported for TopK  Operator

### ISSUE THREAD

**Issue by swithmn1** [microsoft/onnxruntime#7646]
while load fp16 onnx model ,it happend below problem..

**Comment by swithmn1** [comment]
onnxruntime support fp16 onnx-model with "TopK"?

**Comment by ytaous** [comment]
@swithmn1 - seems related topic:
https://github.com/microsoft/onnxruntime/issues/4147

CPU doesn't support TopK/fp16:
https://github.com/microsoft/onnxruntime/pull/6082

@duli2012 - any further comments?
