### ISSUE TITLE
Find if an onnx model is already optimized

### ISSUE THREAD

**Issue by abuvaneswari** [microsoft/onnxruntime#7661]
Hi,

Is there a function or a tool that can return whether a given onnx model is already optimized for o1 / o2 / o99? If it does not exist already, what would be the best approach to implementing it?

thanks,
Buvana

**Comment by pranav-prakash** [comment]
Someone who's a member of their team can chime in, but I don't believe that such a tool currently exists. However, it should be conceptually be easy to implement by running the model through a given optimization level and checking if it remains unchanged.

**Comment by ytaous** [comment]
+1 - not that I am aware of either.
