### ISSUE TITLE
Ask a Question

### ISSUE THREAD

**Issue by moonjiaoer** [microsoft/onnxruntime#7667]
Does onnxruntime support inference on a node-by-node  and give the output result of each node?

**Comment by moonjiaoer** [comment]
I found that the output result of each node after an inference can be given through the session.run() function in onnxruntime, but I cannot call the inference process of each node such as the calculation of ‘conv’ .

**Comment by ytaous** [comment]
dup of https://github.com/microsoft/onnxruntime/issues/7668
