### ISSUE TITLE
Does onnxruntime support inference on a node-by-node and give the output result of each node?

### ISSUE THREAD

**Issue by moonjiaoer** [microsoft/onnxruntime#7668]
I found that the output result of each node after an inference can be given through the session.run() function in onnxruntime, but I cannot call the inference process of each node such as the calculation of ‘conv’ .

**Comment by ytaous** [comment]
There might be a cmake flag you can add when building onnxruntime binary:

./build.sh <bunch of build options> --cmake_extra_defines onnxruntime_DEBUG_NODE_INPUTS_OUTPUTS=1

And to dump the input or output for each op, add env variable when running your command
ORT_DEBUG_NODE_IO_DUMP_INPUT_DATA=1 ORT_DEBUG_NODE_IO_DUMP_OUTPUT_DATA=1 python test.py

I've used it for training, inference should go thru the same code path. You can try and see if it works for you.

code ref: onnxruntime/core/framework/debug_node_inputs_outputs_utils.cc
