### ISSUE TITLE
Input shape Python vs C#

### ISSUE THREAD

**Issue by maondra** [Microsoft/onnxruntime#774]
Hi,
 I want to ask about Python and C# client and their different implementation.

In **python** I can use model with first layer: inputs = Input(shape=(None, None, input_channel_num)) //Keras

In **C#** I have to specify exact input shape: e.g.: inputs = Input(shape=(512, 512, input_channel_num))

Why the python client can handle Input(shape=(None, None, input_channel_num)) and C# client not?

Thank you.

**System information**
- Linux Ubuntu 18 / Windows 10:
- ONNX Runtime installed from binary:
- ONNX Runtime version: 0.3.0
- Python version: 3.6
- Visual Studio version : 2017
- CUDA/cuDNN version: 9.1/7
- GPU model and memory: 2080TI/ Q P2000

**Expected behavior**
Same behavior for python and C# client.

**Comment by jignparm** [comment]
@maondra, can you give an example of what is not working in C#? Models with dynamic axes (e.g. None) are handled via -1 in most cases. 

Does your model load successfully, and fails during scoring a tensor? Or does it not load at all?

**Comment by jignparm** [comment]
For example, the model below has input of shape **[-1, 3]**, which would be Python equivalent of **[None, 3]**

The code below creates an input tensor of shape **[1, 3]**,  scores the input tensor, and receives back an output tensor of shape **[1],** that contains the index of the largest value in the input tensor (index= 2).

In case you are still having issues, please attach a sample.

![image](https://user-images.githubusercontent.com/13698702/55659145-2ef4c100-57b5-11e9-8ce0-eeadd8099c32.png)

Sample code:

        static void Main(string[] args)
        {
            var session = new InferenceSession(@"argmax.onnx");
            var tensorIn = new DenseTensor<float>(new float[] { 1, 2, 3 }, new int[] { 1, 3 });
            var listnov = new List<NamedOnnxValue>();
            listnov.Add(NamedOnnxValue.CreateFromTensor<float>("input", tensorIn));
            var results = session.Run(listnov);
            foreach (var nov in results)
            {
                var tensor = nov.AsTensor<Int64>() as DenseTensor<Int64>;
                Console.WriteLine($"Argmax index = {tensor[0]}");
            }
        }

Output is:

       Argmax index = 2

**Comment by maondra** [comment]
Hi, Thank you for fast response. I am sorry, I found the error in my code.

error: `new DenseTensor<float>(input, inputMeta[name].Dimensions);`

correct: `new DenseTensor<float>(input, new int[] { 1, 512, 512, 1 });`

Thank you!
