### ISSUE TITLE
android app crash when use nnapi

### ISSUE THREAD

**Issue by hoozh** [microsoft/onnxruntime#7744]
**Describe the bug**
App crash when use onnxruntime with nnapi

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):build onnxruntime on ubuntu, run on android 
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: clone from repository
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- build onnxruntime on ubuntu 20.04
`./build.sh --config Release --android --use_nnapi --android_sdk_path /home/zh/Android/Sdk --android_ndk_path /home/zh/Android/Sdk/ndk/22.1.7171670/ --android_abi arm64-v8a --android_api 28 `

- call below code before **new Ort::Session**
`uint32_t nnapi_flags = 0;
Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_Nnapi(session_options_, nnapi_flags));`

- Exception occurs

> Timestamp: 2021-05-18 09:57:05+0800
pid: 9831, tid: 9831, name: .freehum.hmeter  >>> com.freehum.hmeter <<<
uid: 10289
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '**terminating with uncaught exception of type Ort::Exception: shaper.cc:312 EltwiseImpl Dimensions are not compatible, dim1: 0dim2: 320**'
    x0  0000000000000000  x1  0000000000002667  x2  0000000000000006  x3  0000007ff70acac0
    x4  fefeff2f31321f39  x5  fefeff2f31321f39  x6  fefeff2f31321f39  x7  7f7f7f7f7f7f7f7f
    x8  00000000000000f0  x9  440682a8997de83e  x10 0000000000000001  x11 0000000000000000
    x12 fffffff0fffffbdf  x13 0000000060a31ef1  x14 000cb5727d99f8e2  x15 00000f11ee354b75
    x16 00000070f181e908  x17 00000070f17fe1b0  x18 0000006ffb83bb88  x19 0000000000002667
    x20 0000000000002667  x21 00000000ffffffff  x22 ffffff80ffffffc8  x23 0000007ff70acd10
    x24 0000007ff70acbf0  x25 0000007ff70acc30  x26 000000706e478cb0  x27 0000000000000002
    x28 0000007ff70ad530  x29 0000007ff70acb60
    sp  0000007ff70acaa0  lr  00000070f17b3040  pc  00000070f17b306c
backtrace:
      #00 pc 000000000006f06c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: 736a6b327ce386a8cddaf85ea68bf6ea)
      #01 pc 0000000000b34ac0  /data/app/com.freehum.hmeter-dBMvA5kR8rI6Z--pW02mAg==/base.apk!libnative-lib.so (offset 0x2386000) (BuildId: 11df0c9cc7859e4b4dee28a27d59fd3ca7aff9f1)
      #02 pc 0000000000b34c18  /data/app/com.freehum.hmeter-dBMvA5kR8rI6Z--pW02mAg==/base.apk!libnative-lib.so (offset 0x2386000) (BuildId: 11df0c9cc7859e4b4dee28a27d59fd3ca7aff9f1)
      #03 pc 0000000000b318c8  /data/app/com.freehum.hmeter-dBMvA5kR8rI6Z--pW02mAg==/base.apk!libnative-lib.so (offset 0x2386000) (BuildId: 11df0c9cc7859e4b4dee28a27d59fd3ca7aff9f1)
      #04 pc 0000000000b30ef4  /data/app/com.freehum.hmeter-dBMvA5kR8rI6Z--pW02mAg==/base.apk!libnative-lib.so (offset 0x2386000) (BuildId: 11df0c9cc7859e4b4dee28a27d59fd3ca7aff9f1)
      #05 pc 0000000000b30e50  /data/app/com.freehum.hmeter-dBMvA5kR8rI6Z--pW02mAg==/base.apk!libnative-lib.so (offset 0x2386000) (__cxa_throw+112) (BuildId: 11df0c9cc7859e4b4dee28a27d59fd3ca7aff9f1)
      #06 pc 00000000003e80fc  /data/app/com.freehum.hmeter-dBMvA5kR8rI6Z--pW02mAg==/base.apk!libnative-lib.so (offset 0x2386000) (Ort::ThrowOnError(OrtApi const&, OrtStatus*)+204) (BuildId: 11df0c9cc7859e4b4dee28a27d59fd3ca7aff9f1)
      #07 pc 00000000003e797c  /data/app/com.freehum.hmeter-dBMvA5kR8rI6Z--pW02mAg==/base.apk!libnative-lib.so (offset 0x2386000) (Ort::ThrowOnError(OrtStatus*)+24) (BuildId: 11df0c9cc7859e4b4dee28a27d59fd3ca7aff9f1)
      #08 pc 00000000003f0454  /data/app/com.freehum.hmeter-dBMvA5kR8rI6Z--pW02mAg==/base.apk!libnative-lib.so (offset 0x2386000) (Ort::Session::Session(Ort::Env&, char const*, Ort::SessionOptions const&)+132) (BuildId: 11df0c9cc7859e4b4dee28a27d59fd3ca7aff9f1)
      #09 pc 00000000003effc4  /data/app/com.freehum.hmeter-dBMvA5kR8rI6Z--pW02mAg==/base.apk!libnative-lib.so (offset 0x2386000) (OnnxruntimeInterpreter::Initial(char const*)+100) (BuildId: 11df0c9cc7859e4b4dee28a27d59fd3ca7aff9f1)
      #10 pc 00000000003e535c  /data/app/com.freehum.hmeter-dBMvA5kR8rI6Z--pW02mAg==/base.apk!libnative-lib.so (offset 0x2386000) (HardDetect::Initial(char const*)+44) (BuildId: 11df0c9cc7859e4b4dee28a27d59fd3ca7aff9f1)
      #11 pc 00000000003dd634  /data/app/com.freehum.hmeter-dBMvA5kR8rI6Z--pW02mAg==/base.apk!libnative-lib.so (offset 0x2386000) (Java_com_freehum_hmeter_MainActivity_initialDetector+136) (BuildId: 11df0c9cc7859e4b4dee28a27d59fd3ca7aff9f1)

- information from addr2line

> D:\Android>d:\Android\sdk\ndk\21.1.6352462\toolchains\x86-4.9\prebuilt\windows-x86_64\bin\i686-linux-android-addr2line.exe -C -f -e D:\Proj\androidprojects\HMeter\app\build\intermediates\cmake\debug\obj\arm64-v8a\libnative-lib.so 0000000000b30e50 00000000003e80fc 00000000003e797c 00000000003f0454 00000000003effc4
__cxa_throw
/buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/cxa_exception.cpp:284
Ort::ThrowOnError(OrtApi const&, OrtStatus*)
E:/wheels\onnxruntime-android-nnapi\include\onnxruntime\core\session/onnxruntime_cxx_inline.h:17
Ort::ThrowOnError(OrtStatus*)
E:/wheels\onnxruntime-android-nnapi\include\onnxruntime\core\session/onnxruntime_cxx_inline.h:22
Session
E:/wheels\onnxruntime-android-nnapi\include\onnxruntime\core\session/onnxruntime_cxx_inline.h:509
OnnxruntimeInterpreter::Initial(char const*)
D:/Proj/androidprojects/HMeter/app/src/main/cpp/ort_core.cpp:12

**Expected behavior**
if without nnapi, the app is work, but crash when using nnapi

**Comment by RyanUnderhill** [comment]
@gwang-msft Potential bug in nnapi?

**Comment by gwang-msft** [comment]
@hoozh, please share more information, for example, onnx runtime version, …
Also please share the model, such that we can take a look.
