### ISSUE TITLE
Does onnxruntime support inference with only one node such as ‘conv’ or ‘clip’ in the onnx model? 

### ISSUE THREAD

**Issue by moonjiaoer** [microsoft/onnxruntime#7782]
I try to execute one node at a time, this node could be ‘conv’ or ‘clip’, etc. for example. And this node not necessarily be the input node of the model. To be more concrete, I put an example model here in Fig 1. Instead of running the whole model (set the input data for the node ‘input’, and expect to get the result of the node ‘clip’), I want to execute the ‘clip’ node (set the input data for the node ‘clip’, and expect to get the result of the node ‘clip’).

![1238456898](https://user-images.githubusercontent.com/25788679/119075072-c0b9f980-ba22-11eb-9447-b58562400b7a.jpg)
 Fig 1.  example model

I tried to achieve this by change the parameters of the function ‘run’, such as: 
res = sess.run([output_name], {'clip': x})

But get an error: onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:clip. 
Seems like this parameter is used for the model with multiple input node, it doesn’t work for the case that you want to choose which node you really want to INPUT the data other than the input node.

Does anyone know how to achieve this? Or if the ORT has such a function?

**Comment by hariharans29** [comment]
This is not possible. ORT only supports running whole graphs and not run granular pieces like individual nodes. The only way it is possible is when that node is forming the whole graph (although I am not sure what purpose that would serve except for testing one operator). hope this helps.

**Comment by mazhongzhong** [comment]
> This is not possible. ORT only supports running whole graphs and not run granular pieces like individual nodes. The only way it is possible is when that node is forming the whole graph (although I am not sure what purpose that would serve except for testing one operator). hope this helps.

Suppose I want to test one operator, then how to do it? Calling the low level API?

**Comment by hariharans29** [comment]
You can create a single node model and test that operator, in that case the entire graph is just one node

**Comment by mazhongzhong** [comment]
I want to add such an function (executing one node at a time) by contribute code (in new branch), could you give me a clue where I can start?
