### ISSUE TITLE
[ORT][C++] How to hold Ort::Session reference as class private membership

### ISSUE THREAD

**Issue by Distancehe** [microsoft/onnxruntime#7790]
**Describe the bug**
Class A has two methods Init() and Eval(), and a private member Ort::Session or Ort::Session pointer to hold the created Ort Session.

The init() will create the session with Ort::Session session_(*m_env, model_path_w.c_str(), m_sessionOption);
The question is how to hold the reference of the created Ort session so it can be used from Eval() method (calll session.run())

Tried to used a pointer to Ort::Session, but there will be exception from Eval() method when calling session.run().

Any sample usage would be appreciated !

**Urgency**
Development blocker.

**System information**
Windows CPU

**Comment by hariharans29** [comment]
Can you share a small code snippet ? What is the error you get in Eval() when you try using a pointer ?

**Comment by Distancehe** [comment]
Hi @hariharans29, I used to approach to hold the session reference by pointer (as operator= is banned for Ort::Session).

Ort::Env env(ORT_LOGGING_LEVEL_WARNING, m_serverName.c_str());
Ort::SessionOptions sessionOptions;
sessionOptions.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);

string model_path = m_config->GetModelDataPath();
wstring model_path_w = wstring(model_path.begin(), model_path.end());

m_session = std::make_shared<Ort::Session>(env, model_path_w.c_str(), sessionOptions);

From Eval(), the exception is: Non-zero status code returned while running Shape node.

Also tried to assign m_session just by &session and it doesn't work in Eval() either.

**Comment by hariharans29** [comment]
"Non-zero status code returned while running Shape node." This means what you intended to do (i.e.) run the model went through just fine. 

The complaint is about a Shape node in the model/graph. It could either be a model issue (converter bug) or a bug in ORT itself. If you could create a simple model and share it to repro, we can investigate further.

**Comment by Distancehe** [comment]
Thanks @hariharans29 ! I tried Unique smart pointer and found it works for this case to hold pointer to Ort::Session instead of shared_ptr.

**Comment by hariharans29** [comment]
Did you use a different model or the same model when you switched to using unique_ptr ? From the earlier error message, it seemed to point to an error while actually running the model...

**Comment by Distancehe** [comment]
@hariharans29 , the same model for unique/share pointer. All the other logic (load/run session, etc...) are not changed.

**Comment by yuslepukhin** [comment]
Why don;t you just hold Ort::Session by value? The object has the only member - a pointer to the underlying structure and exists for automatic cleanup purposes. It itself acts as a smart pointer, there is not a need to wrap it into another smart ptr.

**Comment by Distancehe** [comment]
@yuslepukhin Tried to hold Session by value but Operator= is banned for Ort::Session, could you share a code snip for better understanding your suggestion ?

**Comment by pranavsharma** [comment]
Following should work.

```
#include "onnxruntime_cxx_api.h"
#include <iostream>
#include <vector>

class SessionWrapper {
public:
  SessionWrapper() : env_() {
  }

  void Init(const ORTCHAR_T* model) {
    Ort::SessionOptions so;
    Ort::Session session_tmp(env_, model, so);
    session_ = std::move(session_tmp);
  }

  void Eval() {
    // auto output_tensors = session_.Run(Ort::RunOptions{nullptr}, input_names.data(), ort_inputs.data(), ort_inputs.size(), output_names.data(), output_names.size());
  }

private:
  Ort::Session session_{nullptr};
  Ort::Env env_{nullptr};
};

int main() {
  SessionWrapper sw;
  sw.Init("model.onnx");
  sw.Eval();
  return 0;
}
```

**Comment by snnn** [comment]
Please reopen this issue if you need more help.
