### ISSUE TITLE
ONNX to ORT: Error converting model.onnx: __init__() got an unexpected keyword argument 'disabled_optimizers

### ISSUE THREAD

**Issue by vizakshat** [microsoft/onnxruntime#7809]
**Describe the bug**
I have trained a seesawfacenet in pytorch and exported it to ONNX. I want to use it on a mobile device but ONNX to ORT conversion is showing an error.

**Urgency**
1 week

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 20.04 and onnxruntime docker
- ONNX Runtime installed from (source or binary): pip install onnxruntime
- ONNX Runtime version: 1.7.0
- Python version: 3.8.5
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**To Reproduce**
- Describe steps/code to reproduce the behavior.
```
pip3 install onnxruntime==1.7.0
pip3 install flatbuffers==2.0
python3 ./onnxruntime/tools/python/convert_onnx_models_to_ort.py ./models

```
**ERROR**
```
Converting optimized ONNX model /model.onnx to ORT format model /model.all.ort
Error converting /model.onnx: __init__() got an unexpected keyword argument 'disabled_optimizers'
```

- Attach the ONNX model to the issue (where applicable) to expedite the investigation.
https://drive.google.com/drive/folders/1jQInOOOBEiD6ndTc-f4nas-l0EyA5qR5?usp=sharing 
This link contains two onnx models. simplified-model is after optimizing https://github.com/daquexian/onnx-simplifier

**Expected behavior**
Should have produced ORT model files

**Screenshots**
n/a

**Additional context**
please ask

**Comment by codemzs** [comment]
@skottmckay FYI

**Comment by skottmckay** [comment]
You have a mismatch between the script (master) and the onnxruntime python package (1.7 release). Easiest is to checkout the 1.7 release code (`git checkout rel-1.7.0`).
