### ISSUE TITLE
Pad-13 does not support bool type

### ISSUE THREAD

**Issue by jiafatom** [microsoft/onnxruntime#7811]
**Describe the bug**
I want to export a pytorch transformer model: longformer. The model scripts contains padding on boolean mask [here](https://github.com/huggingface/transformers/blob/469384a777131e8c6d6bf7851ab0f77f2fbe3cb0/src/transformers/models/longformer/modeling_longformer.py#L1562)
Pad-13 spec type constraint supports bool (this is newly introduced in opset 13, not 11)
but it looks onnxruntime does not support bool type for Pad-13, see [here](https://github.com/microsoft/onnxruntime/blob/8d737f977056444a307f1b7f0bcd402fba62d790/onnxruntime/core/providers/cpu/tensor/pad.cc#L98-L105)
Could we add the support for bool? Thanks.

**Urgency**
blocking pytorch transformer model export.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- ONNX Runtime installed from (source or binary): pypi
- ONNX Runtime version: 1.7.0
- Python version: 3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Attach the ONNX model
[pad.zip](https://github.com/microsoft/onnxruntime/files/6534351/pad.zip)

**Comment by mjay2016** [comment]
Here is the details of fix
https://github.com/microsoft/onnxruntime/pull/7813
