### ISSUE TITLE
Batch mode inference for onnxruntime server

### ISSUE THREAD

**Issue by boscotsang** [microsoft/onnxruntime#7821]
**Is your feature request related to a problem? Please describe.**
onnxruntime server doesn't provide batch mode inference which improve performance of large scale inferences

**System information**
- ONNX Runtime version (you are using): master

**Describe the solution you'd like**
Provide batch mode inference like tfserving/torchserve.

**Comment by snnn** [comment]
I'm sorry. onnxruntime server is maintenance mode, we will not add new features to it.
