### ISSUE TITLE
ORT Training: How to postprocess a onnx model to use ORTTrainer

### ISSUE THREAD

**Issue by mengniwang95** [microsoft/onnxruntime#7823]
For a origin onnx model whose output does not contain loss, how to postprocess it to meet the requests of OTRTrainer?
Furthermore, I see https://github.com/microsoft/onnxruntime/blob/78fde2c4cbeaaaf46fa97e1ffaea0fa01cbbcb33/onnxruntime/test/python/onnxruntime_test_ort_trainer.py#L342 do onnx bert training and its input model is "bert_toy_postprocessed.onnx", so where can I get this model or how can I generate this model?

**Comment by codemzs** [comment]
ORT builds the gradient graph and adds the relevant ops when an ONNX model is used for training. Can you please paste the repro steps and the error you are seeing?

**Comment by mengniwang95** [comment]
> ORT builds the gradient graph and adds the relevant ops when an ONNX model is used for training. Can you please paste the repro steps and the error you are seeing?

Could you show me an example of how the ORT build the gradient graph for an onnx model without loss outputs originally?  I can't find relevant codes in python

**Comment by gcunhase** [comment]
Any update on this?

**Comment by baijumeswani** [comment]
closing this since ORTTrainer is being deprecated. Please use ORTModule instead, and let me know if there is anything I can help with.
