### ISSUE TITLE
How to utilize TensorRT fallback

### ISSUE THREAD

**Issue by wm2012011492** [microsoft/onnxruntime#7825]
**Describe the bug**
I want to check the TensorRT EP with fallback, i.e. onnx model with unsupported op by TRT like onehot. However, I got the error below, which seems the fallback mechanism doesn't work.
 [E:onnxruntime:Default, tensorrt_execution_provider.h:51 log] [2021-05-25 09:13:26   ERROR] INVALID_ARGUMENT: getPluginCreator could not find plugin OneHot version 1

**System information**
- Ubuntu 18.04
- build from source code with tensorrt dockerfile
- onnxruntime 1.8.0 (main branch)
- Python 3.7.0
- GCC 9.3.0
- CUDA 11.1 /cuDNN 8.0.5 
- V100
[test_Onehot_onnx_trtEP_inferredShape.zip](https://github.com/microsoft/onnxruntime/files/6538104/test_Onehot_onnx_trtEP_inferredShape.zip)

**Comment by KnightYao** [comment]
with same question

**Comment by jywu-msft** [comment]
+@stevenlix , can you take a look?

**Comment by KnightYao** [comment]
> +@stevenlix , can you take a look?

@jywu-msft  it's crucial to ues TensorRT provider by ORT when the network has TensorRT do not support op. so I hope this issue can be sloved in time.

**Comment by KnightYao** [comment]
@stevenlix we need you help, please.

**Comment by KnightYao** [comment]
@snnn nobody fix this bug？

**Comment by stevenlix** [comment]
Sorry for the late response. Actually the error you saw is not actually a failure. The error message is generated by TensorRT and indicates TensorRT can't run the OneHot operator, but at OnnxRuntime side, the operator will fall back to other execution providers such as CUDA and CPU. Your inference should be able to go through without problem. I run the model at my end and it can run successfully.

**Comment by KnightYao** [comment]
> Sorry for the late response. Actually the error you saw is not a failure. The error message is generated by TensorRT and indicates TensorRT can't run the OneHot operator, but at OnnxRuntime side, the operator will fall back to other execution providers such as CUDA and CPU. Your inference should be able to go through without problem. I run the model at my end and it can run successfully.

I run a model with trt ep, when this modle has one node is can run with trt, then the model will run all node with cuda or cpu?
