### ISSUE TITLE
Not able to export large model

### ISSUE THREAD

**Issue by DeepakSaini119** [microsoft/onnxruntime#7840]
**Describe the bug**
I am trying to export a model(which when dumped on disk as a pt file, is 4GB). The code I use is:

```python
net.eval()
torch.onnx.export(net,               # model being run
                  (doc_embeddings, shortlist),                         # model input (or a tuple for multiple inputs)
                  "/path/to/a/folder/net.onnx",   # where to save the model (can be a file or file-like object)
                  opset_version=11,          # the ONNX version to export the model to
                  input_names = ['doc_embeddings', 'shortlist'],   # the model's input names
                  output_names = ['scores'], # the model's output names
                  dynamic_axes={'doc_embeddings' : {0 : 'batch_size'},    # variable length axes
                                'shortlist' : {0 : 'batch_size', 1: 'num_shortlist'},
                                'scores' : {0 : 'batch_size', 1: 'num_shortlist'}},
                  use_external_data_format=True,
                  verbose=True)
```

But this doesn't work and I get the error: `RuntimeError: Exporting model exceed maximum protobuf size of 2GB. Please call torch.onnx.export with use_external_data_format=True.`. I looked at some other threads here and trying those things doesn't seem to help. TIA.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime version: 1.7.0
- Python version: 3.6.9

**Expected behavior**
Model should be exported with external files after specifying `use_external_data_format=True`

**Comment by codemzs** [comment]
@BowenBao FYI

**Comment by BowenBao** [comment]
hi @DeepakSaini119, what is the PyTorch version? Can you try with latest master (1.8.1) to see if it is resolved?

(this issue should be opened under pytorch/pytorch)

**Comment by snnn** [comment]
@BowenBao, could anyone from your team help transfer the issue there?

![image](https://user-images.githubusercontent.com/856316/119710327-115e9780-be13-11eb-878e-affa2e802c83.png)

**Comment by DeepakSaini119** [comment]
> hi @DeepakSaini119, what is the PyTorch version? Can you try with latest master (1.8.1) to see if it is resolved?
> 
> (this issue should be opened under pytorch/pytorch)

Hi BowenBao, thanks. I tried with 1.8.1, still the same issue.

**Comment by BowenBao** [comment]
@snnn I could not find pytorch in the transfer repo list, guess we don't have permission to transfer to pytorch.

@DeepakSaini119 Please close this one and re-open under pytorch.

**Comment by BowenBao** [comment]
@DeepakSaini119 I couldn't find the issue on PyTorch side, replying it here. I think it can be fixed by https://github.com/pytorch/pytorch/pull/59320
