### ISSUE TITLE
Memory leak in java api

### ISSUE THREAD

**Issue by MankaranSingh** [microsoft/onnxruntime#7842]
**Describe the bug**

I am running model inference in a loop like this:

```
inputImgTensor.createTensor(env, imgTensorData.data().asNioFloat(), imgShape); 
inputOneHotTensor.createTensor(env, oneHot); 
			        
container.put("input_imgs", inputImgTensor);  
container.put("one_hot", inputOneHotTensor); 
			        		
netOutputsTensor = session.run(container);  
```
The java heap memory seems healthy but ubuntu memory minotoring tool shows increase in memory usage all the time. So I think this is related to off heap memory. I am sure that these lines are causing the issue (except the container part) because when i comment them out, the memory usage is constant. 

**System information**
- Linux Ubuntu 20.04
- ONNX Runtime installed from maven
- ONNX Runtime version 1.7.0
- ONNX CPU

**To Reproduce**
Keep running a model in loop and monitor the overall system memory.

**Expected behavior**
memory usage shouldnt increase overtime

**Comment by yuslepukhin** [comment]
Are you taking care of all AutoClosables to make sure native resources are released when objects are no longer needed?

**Comment by MankaranSingh** [comment]
Thanks for your suggestion @yuslepukhin ! I changed the code to following

```java
try (OnnxTensor inputImgTensor = OnnxTensor.createTensor(env, imgTensorData.data().asNioFloat(), imgShape); 
      OnnxTensor inputOneHotTensor = OnnxTensor.createTensor(env, one_hot);){
              container.put("input_imgs", inputImgTensor);  
              container.put("input_one_hot", inputOneHotTensor); 
                             try(OrtSession.Result netOutputsTensor = session.run(container);){			                 
			                     netOutputs = (float[][]) netOutputsTensor.get(0).getValue(); 
			                     outs = parse.parser(netOutputs[0]); 
			                 }  
			             }
```

try-with helped fixing the leak.

**Comment by MankaranSingh** [comment]
would there be a better way to reuse tensors ? just curious

**Comment by Craigacp** [comment]
At the moment it's not possible to reuse output tensors. I'm going to add support for reusing buffers when extracting results from `OnnxTensor` at some point soon.

While it's not supported, if you supply your data as a direct `java.nio.Buffer` and wrap that into an `OnnxTensor` then I believe you should be able to write new values into that buffer to update the values in the tensor. If your inputs are always the same size and shape, this should allow you to repeatedly feed the model with different inputs without allocating. However this is an implementation detail and something that might change in the future without warning.

**Comment by MankaranSingh** [comment]
thanks for the details! Closing this issue.
