### ISSUE TITLE
onnxruntime session with python multiprocessing

### ISSUE THREAD

**Issue by NickNickGo** [microsoft/onnxruntime#7846]
**Describe the bug**
I want to instantiate multiple onnxruntime sessions concurrently. I use python multiprocessing for doing the same. However, session.run() results in error when run inside a process.  The same code works when run normally (without using multiprocessing)

**Urgency**
Yes, our current work is blocked by this. 

**System information**

PyTorch version: 1.5.0a0+8f84ded
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.14.0
Libc version: glibc-2.9

Python version: 3.6 (64-bit runtime)
Python platform: Linux-5.4.0-1031-azure-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: Tesla V100-PCIE-16GB
GPU 1: Tesla V100-PCIE-16GB
GPU 2: Tesla V100-PCIE-16GB
GPU 3: Tesla V100-PCIE-16GB

Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.2
[pip3] numpy==1.18.1
[pip3] pytorch-transformers==1.0.0
[pip3] torch==1.5.0a0+8f84ded
[pip3] torchtext==0.4.0
[pip3] torchvision==0.6.0a0
[conda] magma-cuda101             2.5.1                         1    local
[conda] mkl                       2019.1                      144
[conda] mkl-include               2019.1                      144
[conda] msgpack-numpy             0.4.3.2                  py36_0
[conda] nomkl                     3.0                           0
[conda] numpy                     1.18.1           py36h94c655d_0
[conda] numpy-base                1.18.1           py36h2f8d375_1
[conda] pytorch-transformers      1.0.0                    pypi_0    pypi
[conda] torch                     1.5.0a0+8f84ded          pypi_0    pypi
[conda] torchtext                 0.4.0                    pypi_0    pypi
[conda] torchvision               0.6.0a0                  pypi_0    pypi

**To Reproduce**
1. put following code in test.py and run python test.py. 
```
import onnxruntime as ort
import numpy as np
import torch
from multiprocessing import Process, Queue

EP_list = ['CUDAExecutionProvider', 'CPUExecutionProvider']

#Path to model , attached the onnx model herewith.
optimized_model_path = 'nar_without_init.onnx'

def to_numpy (tensor):
    return tensor.numpy()

class IOProcess (Process):
    def __init__(self):
        super(IOProcess, self).__init__()
        self.sess = ort.InferenceSession(optimized_model_path, providers=EP_list)

    def run(self):

        input_ids = np.array([1]*16)
        inputs = {'src_tokens': np.expand_dims(input_ids,0), 'src_lengths':to_numpy(torch.Tensor([16]).type(torch.int64))}
        output_names = ['tokens', 'token_score']
        outputs = self.sess.run(output_names, inputs)

        #print(self.sess)

io_process = IOProcess()
io_process.start()
io_process.join()
```

**Expected behavior**
No error while creating multiple sessions using multiprocess. 

**Screenshots**
current Output: 
![image](https://user-images.githubusercontent.com/66033489/119736471-9dcc8280-be32-11eb-98d3-ab3e6a3ec5e9.png)

**Additional context**

**Comment by NickNickGo** [comment]
Thanks @pranavsharma 

This mostly works except that execution provider for inference session created inside the process is of the type "CPUExecutionProvider". I'm running this code on a machine with 4 gpus. 
 
You can replicate this using following code:

```
def init_session(model_path):
    EP_list = ['CUDAExecutionProvider', 'CPUExecutionProvider']
    sess = ort.InferenceSession(model_path, providers=EP_list)
    print('EXECUTORS :', sess.get_providers())    
    return sess
 ```

**Comment by pranavsharma** [comment]
If you're using the onnxruntime-gpu pkg and have installed the correct deps required by it, this should work.

**Comment by NickNickGo** [comment]
Thanks this works. Could you suggest an example to implement multiple sessions in c++ multithreading as well? 
This will be super useful.

**Comment by pranavsharma** [comment]
You don't want to create multiple sessions for the same model. Create the session once, share the session instance with multiple threads and call Run() on that session instance. Run() is designed to be called concurrently in multiple threads.

**Comment by AbhijitManepatil** [comment]
`import multiprocessing`
CUDA runtime does not support the fork start method so use spawn like below: Thanks @pranavsharma
`multiprocessing.set_start_method('spawn')`

**Comment by AbhijitManepatil** [comment]
> You don't want to create multiple sessions for the same model. Create the session once, share the session instance with multiple threads and call Run() in the threads on that session instance. Run() is designed to be called concurrently in multiple threads.

Can you share example on this?

**Comment by xinsuinizhuan** [comment]
> 
> 
> You don't want to create multiple sessions for the same model. Create the session once, share the session instance with multiple threads and call Run() in the threads on that session instance. Run() is designed to be called concurrently in multiple threads.

I have three camera, and i create the threes threads, different camera have different models, but they run at same time. How to run thems  at same time?  With one camera, one thread and one model, it is so fast. But when i run three it is so slow ath the same time.

**Comment by sanketshahMS** [comment]
Will this fix [https://github.com/microsoft/onnxruntime/issues/7846#issuecomment-850217402](url) also work for tensorrt EP ?
I see CUDA EP does not crash on multithreading calls to run while tensorrt EP crashes.

**Comment by pranavsharma** [comment]
@stevenlix can you comment on tensorrt?

**Comment by Walstruzz** [comment]
> You don't want to create multiple sessions for the same model. Create the session once, share the session instance with multiple threads and call Run() in the threads on that session instance. Run() is designed to be called concurrently in multiple threads.

Hi, @pranavsharma . Is there any example? And is Run() designed to be called concurrently in multiple processes?

**Comment by pranavsharma** [comment]
@Walstruzz Yes, run is designed to be run concurrently in multiple threads and processes. Have you looked at [this](https://github.com/microsoft/onnxruntime/issues/7846#issuecomment-850217402)?

**Comment by DoctorSlimm** [comment]
Why does Onnxruntime multiprocess really nicely on an IPU? @pranavsharma

**Comment by pranavsharma** [comment]
What is an IPU? Can you give an example?

**Comment by DoctorSlimm** [comment]
@pranavsharma great to hear from you, congratulations on your work in maintaining onnx. IPU is a interesting machine provided by Paperspace Cloud in collaboration with graphcore, basically just machines with large numbers of CPU count from what I understand (great for data pre-processing workloads) but primarily made for ML applications.

**Comment by JohnHerry** [comment]
> IOProcess

Is there a example for loading onnx model [onnxruntime-GPU] in dataloader with workers configable?  I always got every kinds of crash when using onnx pretrained model to extract feature to train another model.
