### ISSUE TITLE
How to add the python API for my custom Execution Provider?

### ISSUE THREAD

**Issue by kjyeon1676** [microsoft/onnxruntime#7877]
**Is your feature request related to a problem? Please describe.**
- I'm trying to add the new execution provider. I refer to this URL - http://www.onnxruntime.ai/docs/how-to/add-execution-provider.html. But, I want to support the python API for user applications. Is there a python API guide for the execution provider? or Should I analyze and modify ORT source code?

**System information**
- ONNX Runtime version (you are using): 1.7.0

**Describe the solution you'd like**
- python API Guide for new execution provider
- A commit id that is implemented so that the python API

**Describe alternatives you've considered**
- analyze and modify ORT source code directly

**Additional context**

**Comment by pranavsharma** [comment]
Start with onnxruntime\onnxruntime\python\onnxruntime_inference_collection.py.

**Comment by kjyeon1676** [comment]
> Start with onnxruntime\onnxruntime\python\onnxruntime_inference_collection.py.

Q. So, there is no other python API binding guide? 

Q2. I analyzed the internal source code and found the CreateExecutionProviderFactory_XXXX(EP Name).
For TensorRT, DNNL, CUDA, OpenVINO, above function(CreateExecutionProviderFactory_xxxx) are defined in core/framework/provider_bridge_ort.cc. So, I'm confused  and I don't know which way to follow. 

1. add function in my EP_factory.cc with CreateExecutionProviderFactory_XXX
2. add function in core/framework/provider_bridge_ort.cc with CreateExecutionPRoviderFactory_XXX

which of the two should I follow? For CPU, DML and CoreML, follow 2.
For DNNL, CUDA, TensorRT, OpenVINO, follow 1.

**Comment by jywu-msft** [comment]
it's best to follow DNNL, CUDA, TensorRT, and OpenVINO as examples.

**Comment by kjyeon1676** [comment]
OK :) got it thank you for your reply
