### ISSUE TITLE
Add support for loading models directly from streams

### ISSUE THREAD

**Issue by Henningsson** [microsoft/onnxruntime#791]
**Current situation**
Models are loaded by specifying a file path

**Desired situation**
Models can be loaded from streams

**Solution proposal**

- A new InfererenceSession constructor taking a Stream
- Changes in the C runtime to allow for using interop with a file already in memory (As opposed to a filepath)

**Comment by faxu** [comment]
Thanks for the suggestion, we've added this to our backlog and will add support soon.

**Comment by lantiga** [comment]
Looking forward to this for RedisAI (https://github.com/RedisAI/RedisAI). We're going to add an ONNXRuntime backend very shortly, we're particularly interested in having support for this in the C API. I'll be happy to help out if need, of course.

https://github.com/RedisAI/RedisAI/issues/33

**Comment by timothyman** [comment]
We would love to have this too, since it will allow us to add the model file to Resources instead of loading it directly from a file.

**Comment by kikoland** [comment]
Same here, we would love to have this as this is something required for cross-platform solutions.  Has someone tried to modify the API code?

**Comment by lantiga** [comment]
Take a look at the API in master, there’s a new function in the C API that supports this.

**Comment by kikoland** [comment]
> Take a look at the API in master, there’s a new function in the C API that supports this.
Totally, many thanks! 

Here is the signature:
`ORT_API_STATUS(OrtCreateSessionFromArray, _In_ OrtEnv* env, _In_ const void* model_data, size_t model_data_length,
               _In_ const OrtSessionOptions* options, _Out_ OrtSession** out);`

**Comment by pranavsharma** [comment]
This API is already supported in the master branch.
