### ISSUE TITLE
Incorrect error message when constructing Ort::Session from array

### ISSUE THREAD

**Issue by TiboDMZ** [microsoft/onnxruntime#7915]
ONNXRuntime version and platform : 

v1.7.2, build from source in a dockerfile, base image is nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04 with 
`
RUN git clone --branch=v1.7.2 https://github.com/microsoft/onnxruntime.git /usr/src/onnxruntime
RUN /bin/bash /usr/src/onnxruntime/tools/ci_build/github/linux/docker/scripts/install_openmpi.sh
RUN cd /usr/src/onnxruntime && ./build.sh \
        --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ \
        --use_cuda --skip_tests --config Release --parallel --build_shared_lib
`

Issue:

When constructing an Ort::Session with an array buffer, I get the error "No graph was found in the protobuf".
The array was generated by xxd -i draco_sub.onnx. 
The error is not raised when constructing the Ort::Session with a path to the file.
The onnx file was generated by :

`
import onnx
import onnx.helper as h
from onnx import TensorProto

subnode = h.make_node('Sub', inputs = ['x', 'y'], outputs=['z'])
graph = h.make_graph([subnode], outputs=[h.make_tensor_value_info('z', TensorProto.DOUBLE, ['N', 'M'])], inputs=[h.make_tensor_value_info('x', TensorProto.DOUBLE, ['N', 'M']), h.make_tensor_value_info('y', TensorProto.DOUBLE, ['N', 'M'])], name='subgraph')
`model = h.make_model(graph, producer_name='draco-tests', opset_imports=[h.make_opsetid('ai.onnx', 13)])`
onnx.save(model, 'draco_sub.onnx')
`

**Comment by pranavsharma** [comment]
Cannot repro. See below.

```
    unsigned char draco_sub_onnx[] = {
      0x08, 0x07, 0x12, 0x0b, 0x64, 0x72, 0x61, 0x63, 0x6f, 0x2d, 0x74, 0x65,
      0x73, 0x74, 0x73, 0x3a, 0x5f, 0x0a, 0x0e, 0x0a, 0x01, 0x78, 0x0a, 0x01,
      0x79, 0x12, 0x01, 0x7a, 0x22, 0x03, 0x53, 0x75, 0x62, 0x12, 0x08, 0x73,
      0x75, 0x62, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5a, 0x15, 0x0a, 0x01, 0x78,
      0x12, 0x10, 0x0a, 0x0e, 0x08, 0x0b, 0x12, 0x0a, 0x0a, 0x03, 0x12, 0x01,
      0x4e, 0x0a, 0x03, 0x12, 0x01, 0x4d, 0x5a, 0x15, 0x0a, 0x01, 0x79, 0x12,
      0x10, 0x0a, 0x0e, 0x08, 0x0b, 0x12, 0x0a, 0x0a, 0x03, 0x12, 0x01, 0x4e,
      0x0a, 0x03, 0x12, 0x01, 0x4d, 0x62, 0x15, 0x0a, 0x01, 0x7a, 0x12, 0x10,
      0x0a, 0x0e, 0x08, 0x0b, 0x12, 0x0a, 0x0a, 0x03, 0x12, 0x01, 0x4e, 0x0a,
      0x03, 0x12, 0x01, 0x4d, 0x42, 0x0b, 0x0a, 0x07, 0x61, 0x69, 0x2e, 0x6f,
      0x6e, 0x6e, 0x78, 0x10, 0x0d
    };
    unsigned int draco_sub_onnx_len = 125;

    Ort::SessionOptions so;
    so.AppendExecutionProvider_CUDA({});
    Ort::Session session_tmp(env_, draco_sub_onnx, draco_sub_onnx_len, so);
```

**Comment by TiboDMZ** [comment]
Thanks @pranavsharma, must have messed up my constructor dispatch code, because that's the same generated char array. Will look into it again.
