### ISSUE TITLE
InferenceSession causes segmentation fault on arm32 device with python 3.7

### ISSUE THREAD

**Issue by Nirmal-Neel** [microsoft/onnxruntime#7920]
Hi,

I have built onnxruntime 1.5.3 for arm32 and python 3.7 by following the steps mentioned in [Dockerfile.arm32v7](https://github.com/microsoft/onnxruntime/blob/v1.5.3/dockerfiles/Dockerfile.arm32v7). But when I try to create an inference session in the target environment, it causes segmentation fault.
```python
import onnxruntime as rt
print("Before session creation..")
sess = rt.InferenceSession("model.onnx")
print("Session is created")
```
When I run the above code, I get the following error - 
```bash
Before session creation..
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
```
With `python3 -Xfaulthandler test.py`, I get the following -
```bash
Before session creation..
Fatal Python error: Segmentation fault

Current thread 0xfe39e000 (most recent call first):
  File "/usr/local/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 205 in _create_inference_session
  File "/usr/local/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 195 in __init__
  File "test.py", line 3 in <module>
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
```
To my surprise, the same works well with python3.5 but fails with python 3.7. I haven't tested with python3.6. Could you please tell whether it is a bug or I am doing any mistake?

**Comment by Nirmal-Neel** [comment]
Hi @faxu, any update on this?

**Comment by snnn** [comment]
Could you try the new docker file in #8686 ?

**Comment by snnn** [comment]
And please tell us what's your target environment. The wheel files built from Dockerfile.arm32v7 is not supposed to be run elsewhere, it is for the docker instance only. 

If you need an arm64 wheel, you can get it from https://pypi.org/project/onnxruntime/#files . But, sorry we don't have an arm32 one. This is because https://github.com/pypa/manylinux hasn't provided such a base image for us yet.

**Comment by maulingajjar** [comment]
I was running into similar Segmentation Fault issues when when working with the onnxruntime 1.5.3 wheels generated for Python 3.7 and 3.8 using instructions provided on [Dockerfile.arm32v7](https://github.com/microsoft/onnxruntime/blob/v1.5.3/dockerfiles/Dockerfile.arm32v7). In my case, I was installing the generated wheels on the following target environment:

> Hardware: Raspberry Pi 2 Model B
> CPU: ARM32v7 Rev 5
> OS: Raspbian 10 Buster
> Kernel: Linux 5.4.51-v7+
> Python: 3.7, 3.8

Is this not supported? Would appreciate if you could provide some clarity on the following:

> The wheel files built from Dockerfile.arm32v7 is not supposed to be run elsewhere, it is for the docker instance only.

**Comment by snnn** [comment]
The base image is "balenalib/raspberrypi3-python:latest-stretch-build". I don't know what it was from, but the name indicates it is for raspberry Pi 3 not 2.  So, please don't hold a high expect.

**Comment by snnn** [comment]
Ubuntu wiki says:
"BCM2837 is the chip used in the Raspberry Pi 3 and in later models of the Raspberry Pi 2 (board revision V1.2). It packages a 64-bit quad-core ARM Cortex A53 (ARMv8) CPU with VideoCore IV GPU."

So, if you have an aarch64 version Raspberry Pi , I suggest you directly download a prebuilt package from https://pypi.org/project/onnxruntime/, that would be the easiest.
```bash
pip3 install --upgrade pip
pip3 install onnxruntime
```

But we don't have a package for the older versions of Raspberry Pi

**Comment by snnn** [comment]
I will close this issue now.  Our support for Linux arm32 is very limited, welcome to contribute.
