### ISSUE TITLE
Request for parameter of max_batch for tensorRT C#

### ISSUE THREAD

**Issue by callbarian** [microsoft/onnxruntime#7925]
**Is your feature request related to a problem? Please describe.**
In python tensorRT library, max batch size can be specified.
However in onnxruntime C#, when i use options.AppendExecutionProvider_Tensorrt(0),
the default batch size seems to be 1, and I don't find a parameter to change the batch size.

When I compare the inference time between cuda and tensorRt, tensorRT with batch size 1 is faster.
Clearly, cuda is faster than tensorRT with batch size >= 1 (ex. batch size 126)

Is this parameter supported, or should be added?

**System information**
- ONNX Runtime version (you are using):

**Describe the solution you'd like**
Specifying max batch size in tensorRT 

**Describe alternatives you've considered**

**Additional context**

**Comment by jywu-msft** [comment]
Batching is model dependent. i.e. if the model supports tensor input with  [ N, 3, 216, 216 ] , where N is a variable batch size dimension. OnnxRuntime doesn't provide a separate parameter for batch size. You just feed the input with the desired batch size, assuming your model supports it.

**Comment by callbarian** [comment]
@jywu-msft thank you for getting back. I appreciate the information provided.
