### ISSUE TITLE
Cannot choose between onnxruntime and onnxruntime-gpu 

### ISSUE THREAD

**Issue by shashwat623** [microsoft/onnxruntime#7930]
**Describe the bug**
I cannot switch between onnxruntime and onnxruntime-gpu. Both of them have the same import name. If both are installed, onnxruntime-gpu is imported by default. I need both dependencies installed in my application's docker image for both CUDA and non CUDA users of the application. This limitation would only import the GPU version every time the application runs and give error for non cuda users as onnxruntime-gpu requires some CUDA dll's... :(

**Urgency**
Kind of urgent, as it is delaying deployment.

**Comment by pranavsharma** [comment]
With 1.8 release (out just yesterday), you can just use the onnxruntime-gpu pkg and it'll work on both GPU and CPU-only machines. Just make sure you call set_providers to CPU only when working on CPU.

**Comment by shashwat623** [comment]
@pranavsharma Thank you for your reply. Yeah, I checked that but I guess it's still not supported for python packages. The release document also mentions  that. Tried it out with the 1.8 release, still the same error :(

**Comment by pranavsharma** [comment]
Sorry, yes, this is a known issue. We'll get back.

**Comment by shashwat623** [comment]
@pranavsharma any updates on this issue :)

**Comment by pranavsharma** [comment]
This has been fixed in 1.8.1 release.
