### ISSUE TITLE
[ORT 1.8/build issues MSVC2017] remaining error C2440 in onnxruntime/core/providers/cpu/reduction/reduction_ops

### ISSUE THREAD

**Issue by ThomasRetornaz** [microsoft/onnxruntime#7943]
**Describe the bug**
We upgrade our repos from ort 1.6 (1.7 have also compiling issues with MSVC2017 #6912) to ort 1.8. Two compilation errors arise in
onnxruntime/core/providers/cpu/reduction/reduction_ops

`
reduction_ops.h(215): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'Eigen::Map<Eigen::Array<T,-1,1,,-1,1>,0,Eigen::Stride<0,0>>'
`

The changelog claims that a C++14 compliance is requested, we think that at least the last MSVC2017 is fully C++14 compliant, and MSVC2017 still the default target in ORT documentation
So is it possible to have a bug fix releases,  

**Urgency**
We are stuck in ort 1.6 and we want to move next month to lastest available version side by side with torch
And more than that the documentation claims MSVC2017 is the default compiler so we think we are not alone with this issue 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Win10
- ONNX Runtime installed from (source or binary):
source
- ONNX Runtime version:
1.8
- Python version:
3.8
- Visual Studio version (if applicable):
Microsoft Visual Studio Professional 2017 
Version 15.9.36
VisualStudio.15.Release/15.9.36+28307.1525

**To Reproduce**
- try building from source with MSVC2017 specified compiler

**Expected behavior**
clean build.

**Additional context**
If you look at the errors we think its just a tiny patch

**Comment by snnn** [comment]
Our CI build pipelines use VS 2019 now, so we didn't catch this issue.

Welcome to contribute your patch!

**Comment by snnn** [comment]
Dup to #7936

**Comment by ThomasRetornaz** [comment]
Hello again and thanks for the quick reply :) Sorry i just look at the issues title and don't check contant so i miss duplication
I will be buzzy the next 2 week but i will try to provide a patch asap
I think you prefer i do a PR right?
And of course thanks for this awesome library 
Regards
TR

**Comment by snnn** [comment]
Take your time. I hope more and more people will be involved to this project. 

Thank you!
