### ISSUE TITLE
Cannot use cuda on linux

### ISSUE THREAD

**Issue by WqyJh** [microsoft/onnxruntime#7948]
**Describe the bug**
When use the following code to enable CUDA, it just cannot compile.

```c++
#include <cuda_provider_factory.h>
#include <onnxruntime_cxx_api.h>

OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 1);
```

Because the `cuda_provider_factory.h` needs the following header, but it cannot be found in `onnxruntime-linux-x64-gpu-1.8.0.tgz` release.

```c++
#include "core/framework/provider_options.h"
```

**Urgency**

Cuda support on linux was broken.

**System information**
- OS Platform and Distribution: Ubuntu 18.04 bionic
- ONNX Runtime installed from (source or binary): onnxruntime-linux-x64-gpu-1.8.0.tgz
- ONNX Runtime version: 1.8.0
- Python version: 3.6.9
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 11.0
- GPU model and memory: NVIDIA RTX 2080 Ti

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by snnn** [comment]
Please use "SessionOptionsAppendExecutionProvider_CUDA" function instead. It can be found in https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h

**Comment by WqyJh** [comment]
This works for me
```c++
OrtCUDAProviderOptions options;
options.device_id = 1;
options.arena_extend_strategy = 1; // use -1 to allow ORT to choose the default, 0 = kNextPowerOfTwo, 1 = kSameAsRequested
options.gpu_mem_limit = 1L * 1024 * 1024 * 1024;
options.cudnn_conv_algo_search = OrtCudnnConvAlgoSearch::EXHAUSTIVE;
options.do_copy_in_default_stream = 1;
options.user_compute_stream = nullptr;
options.default_memory_arena_cfg = nullptr;
session_options.AppendExecutionProvider_CUDA(options);
```

**Comment by oliviajain** [comment]
Great Qiying. Is there any further help needed?

**Comment by WqyJh** [comment]
Thanks, no more question. I think this issue could be closed.

**Comment by Sammul40619** [comment]
> This works for me
> 
> ```c++
> OrtCUDAProviderOptions options;
> options.device_id = 1;
> options.arena_extend_strategy = 1; // use -1 to allow ORT to choose the default, 0 = kNextPowerOfTwo, 1 = kSameAsRequested
> options.gpu_mem_limit = 1L * 1024 * 1024 * 1024;
> options.cudnn_conv_algo_search = OrtCudnnConvAlgoSearch::EXHAUSTIVE;
> options.do_copy_in_default_stream = 1;
> options.user_compute_stream = nullptr;
> options.default_memory_arena_cfg = nullptr;
> session_options.AppendExecutionProvider_CUDA(options);
> ```

Did you change any others? because it does not work for me. This is what my get:

                 from /home/infer/cwork/src/aiocr_main.cpp:2:
/home/infer/cwork/include/CrnnNet.h:28:5: error: ‘options’ does not name a type
     options.device_id = 1;

**Comment by paynowski** [comment]
I have no problems running I followed the advice above and changed to SessionOptionsAppendExecutionProvider_CUDA. Now I get the following runtime error on WIndows 10 using Microsoft.ML.OnnxRuntime.Gpu.1.8.0.

2021-07-26 09:55:52.8265204 [E:onnxruntime:OnnxModel C++, provider_bridge_ort.cc:902 onnxruntime::ProviderSharedLibrary::Ensure] Failed to load library, error code: 126
Exception: OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library

**Comment by roachsinai** [comment]
Hi @snnn I got 

C3861	'SessionOptionsAppendExecutionProvider_CUDA': identifier not found	when using 

#include "onnxruntime_c_api.h"

**Comment by puzzledsky** [comment]
> I have no problems running without CUDA. I followed the advice above and changed to SessionOptionsAppendExecutionProvider_CUDA to use CUDA version. Now I get the following runtime error on WIndows 10 using Microsoft.ML.OnnxRuntime.Gpu.1.8.0.
> 
> 2021-07-26 09:55:52.8265204 [E:onnxruntime:OnnxModel C++, provider_bridge_ort.cc:902 onnxruntime::ProviderSharedLibrary::Ensure] Failed to load library, error code: 126

Hey! Have you solved it ? I encounter the same error as you on Windows10 when using Microsoft.ML.OnnxRuntime.Gpu.1.9.0.

**Comment by paynowski** [comment]
> > I have no problems running without CUDA. I followed the advice above and changed to SessionOptionsAppendExecutionProvider_CUDA to use CUDA version. Now I get the following runtime error on WIndows 10 using Microsoft.ML.OnnxRuntime.Gpu.1.8.0.
> > 2021-07-26 09:55:52.8265204 [E:onnxruntime:OnnxModel C++, provider_bridge_ort.cc:902 onnxruntime::ProviderSharedLibrary::Ensure] Failed to load library, error code: 126
> 
> Hey ! Have you solved it ? I encounter the same error as you when using Microsoft.ML.OnnxRuntime.Gpu.1.9.0 on Windows10.
I made sure I always copy the 3 dlls from the ...\runtimes\win-x64\native folder. Clean build helps sometimes. Really inconsistent error.

**Comment by puzzledsky** [comment]
I changed the onnxruntime version to 1.8.1 and this problem was solved. Thank you for your reply!

**Comment by roachsinai** [comment]
> Please use "SessionOptionsAppendExecutionProvider_CUDA" function instead. It can be found in [https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h](https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h?rgh-link-date=2021-06-04T15%3A30%3A46Z)

Hi, `SessionOptionsAppendExecutionProvider_CUDA` doesn't work either, I have to use code posted by @WqyJh .
