### ISSUE TITLE
Inconsistent Test Data URL in tensorrt pipelines

### ISSUE THREAD

**Issue by xkszltl** [Microsoft/onnxruntime#795]
**Describe the bug**

Found some inconsistency of test data URL.

![image](https://user-images.githubusercontent.com/5203025/55767595-6621d700-5a2e-11e9-92cc-4e4e2a12b303.png)

**Comment by snnn** [comment]
What's the third one? Does it matter?

**Comment by jywu-msft** [comment]
there are comments right above those lines telling us why those specific urls are being used.
e.g.
https://github.com/Microsoft/onnxruntime/blob/d91555f99e563c33be21435f45d9742f8fba7adf/tools/ci_build/github/azure-pipelines/linux-gpu-tensorrt-ci-pipeline.yml#L7

**Comment by xkszltl** [comment]
Thanks for clarification.
