### ISSUE TITLE
Binding GPU Memory as Input and Output

### ISSUE THREAD

**Issue by arjunsurendran24** [microsoft/onnxruntime#7956]
I have a question regarding binding GPU memory to onnxruntime. 

I have a use case where the input to model is produced by and output from model is consumed by DirectX11 resouces. I wanted to know if there is any way I can bind these resources directly to onnxruntime as input and output when I am using DirectML execution provider without making any extra copies using shared buffers. 

In [this](https://github.com/microsoft/onnxruntime/blob/0975e7c9a71a4c4060ba062492799a4f90dfd311/onnxruntime/test/shared_lib/test_inference.cc#L793) testcase I found an example of binding CUDA memory to onnxruntime, but the bound memory is [allocated](https://github.com/microsoft/onnxruntime/blob/0975e7c9a71a4c4060ba062492799a4f90dfd311/onnxruntime/test/shared_lib/test_inference.cc#L821) by ORT. I don't want to allocate extra memory for input if the data from preprocessing stage is already in GPU Memory. 

Any help would be appreciated! Thanks!

**Comment by tianleiwu** [comment]
It is possible since the the binding only need information of memory pointer, data type and shape of a buffer. The memory need not be allocated by ORT.

Here is an example that binds a tensor allocated by PyTorch: https://github.com/microsoft/onnxruntime/blob/429df40f1dfa0cd72b2fc449f80c7945c79a4b07/onnxruntime/python/tools/transformers/gpt2_helper.py#L431-L432

**Comment by arjunsurendran24** [comment]
Hi, Thanks for the response. I forgot to mention in the initial comment that I am using C++ API for inference. Is it possible to use IO Binding the same way in C and C++ APIs also?

**Comment by hariharans29** [comment]
When you say "bound memory is allocated by ORT", it is actually not correct - it is not allocated by ORT, it is allocated by the user in the test by using a CUDA allocator, that's all and not by ORT. It is actually the exact scenario that you need. You can think of `input_data` as your "intermediate" buffer already on GPU and you can create an OrtValue using this user-owned buffer (`bound_x` in the test) and you can continue to bind that OrtValue.

Please keep in mind that you own the buffer wrapped as an OrtValue and you should be careful in managing its lifetime and be careful that you don't delete it when used by ORT.

**Comment by arjunsurendran24** [comment]
Perfect! That solves my use case. Thanks for the response.
