### ISSUE TITLE
cmake error from emscripten toolchain file

### ISSUE THREAD

**Issue by daquexian** [microsoft/onnxruntime#7976]
**Describe the bug**
In https://emscripten.org/docs/compiling/Building-Projects.html?highlight=cmake#integrating-with-a-build-system, the recommended way to integrate cmake with emscripten is to use `emcmake` or `emmake`. However, in onnxruntime build.py, the cmake toolchain file is used directly, leading to an incomplete configuration.

On my side, it caused an error: in cmake/external/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake:88, the ${CMAKE_C_COMPILER} is "/usr/bin/cc" rather than "", so that the following `set` is wrongly skipped, the wrong compiler is used.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: f352d5
- Python version: 3.6

**Comment by snnn** [comment]
If you know how to make it better, welcome to contribute your changes!

**Comment by fs-eire** [comment]
it looks like the setup of CMake is fine. the "emcmake" mentioned above should be a typo which I cannot find it in any document.

I think the real problem is, according to https://emscripten.org/docs/tools_reference/emsdk.html?highlight=activate#emsdk-set-active-tools, we missed the `source ./emsdk_env.sh`, so variables are not populated correctly.

```
./emsdk activate <tool/sdk name>

# On Linux and macOS, also set the environment variables.
source ./emsdk_env.sh
```

However, I didn't see any way inside `build.py` can call the shell command `source ./emsdk_env.sh` and preserve the state. Need help for this part.

**Comment by daquexian** [comment]
> the "emcmake" mentioned above should be a typo which I cannot find it in any document.

This is a correct command, though it is not mentioned in docs :D

**Comment by fs-eire** [comment]
> > the "emcmake" mentioned above should be a typo which I cannot find it in any document.
> 
> [emcmake](https://github.com/emscripten-core/emscripten/blob/main/emcmake) is just the same file with [emconfigure](https://github.com/emscripten-core/emscripten/blob/main/emconfigure) (which is in docs)
> 
> > We recommend you call both emconfigure and emmake scripts in configure- and CMake-based build systems. Whether you actually need to call both tools depends on the build system (some systems will store the environment variables in the configure step, and others will not).

@daquexian thanks for clarification. could you help to verify if this workaround works:

1. start with a clean build
2. use `./build.sh --build_wasm` to build, expect it reports the error
3. in your shell, call `source path-to-emsdk_env.sh` (if you are in ORT source root, this should be `source cmake/external/emsdk/emsdk_env.sh`)
4. use the command in step2 and see if this time it passes the build

**Comment by daquexian** [comment]
@fs-eire I pulled the latest master of ort and try again. This time the build succeeded. Maybe this issue is already fixed?

**Comment by fs-eire** [comment]
> @fs-eire I pulled the latest master of ort and tried again. This time the build succeeded. Maybe this issue is already fixed?

the command `source path-to-emsdk_env.sh` set the environment variables to make it works. unfortunately if you open a new shell window, you have to manually set it again.

I don't have a good way to make this automatic. I am going to make a change to remove emsdk from submodules, make the setup steps manually and put the instructions in doc.

**Comment by guschmue** [comment]
this should be no longer an issue
