### ISSUE TITLE
Quantization issue - ValueError: invalid weight name <weight name> found in the graph

### ISSUE THREAD

**Issue by nilotpal09** [microsoft/onnxruntime#7977]
Hi,

I am trying to quantize an onnx model using the [quantization tool](https://github.com/microsoft/onnxruntime/tree/e26e11b9f7f7b1d153d9ce2ac160cffb241e4ded/onnxruntime/python/tools/quantization), but I am getting the following error 

`ValueError: invalid weight name <weight name> found in the graph`

I converted the model from Pytorch to onnx with opset 11, and I was able to run it with ONNXRuntime (C++) without any issue. 

The onnx model and the the scripts needed to reproduce the error can be found [here](https://github.com/nilotpal09/Quantize)

**Additional Info** - 

onnx version - 1.9.0
torch version - 1.7.1
onxruntime version - 1.7.1

**Error Stack** - 
```
Traceback (most recent call last):
  File "/storage/agrp/nilotpal/quantize/quantize.py", line 320, in _remove_quantized_weights
    weight_input = next(val for val in self.model.graph.input if val.name == weight.name)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quantize_test.py", line 38, in <module>
    quantized_model = quantize(model, quantization_mode=QuantizationMode.IntegerOps)
  File "/storage/agrp/nilotpal/quantize/quantize.py", line 1066, in quantize
    quantizer.quantize_model()
  File "/storage/agrp/nilotpal/quantize/quantize.py", line 275, in quantize_model
    self._remove_quantized_weights()
  File "/storage/agrp/nilotpal/quantize/quantize.py", line 322, in _remove_quantized_weights
    raise ValueError('invalid weight name {} found in the graph '.format(weight.name))
ValueError: invalid weight name 808 found in the graph 
```

Thanks in advance!!

**Comment by yufenglee** [comment]
@nilotpal09, looks like you are not using our official quantization tool. It works with our official package by replacing:
`from quantize import quantize, QuantizationMode`
with
`from onnxruntime.quantization import quantize, QuantizationMode`

**Comment by nilotpal09** [comment]
It works now! Thanks a lot!!
