### ISSUE TITLE
[1.6.0] Compilation error on Visual Studio 2019 16.10.0 / CUDA 11.1

### ISSUE THREAD

**Issue by eldruin** [microsoft/onnxruntime#8009]
**Describe the bug**
Compiling onnxruntime from source with CMake stopped working after an update of Visual Studio 2019.
It compiles fine on the current Visual Studio 2017.
This is not a duplicate of #7562 nor #6927 as we do not build with TensorRT support (the code is not even checked out).

**Urgency**
None

**System information**
- OS Platform and Distribution: Windows Server 2019
- ONNX Runtime installed from: source
- ONNX Runtime version: 1.6.0
- Python version: Not built.
- Visual Studio version (if applicable): Visual Studio 2019 16.10.0
- CUDA/cuDNN version: 11.1.1 / 8.0.5.39

**To Reproduce**
The CMake call looks roughly like this:
```
cmake -G Visual Studio 16 2019 -A x64 -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_TYPE:STRING=Release -DBUILD_EXAMPLES:BOOL=OFF 
-DCMAKE_BACKWARDS_COMPATIBILITY:STRING=2.4 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_TESTS:BOOL=OFF -DBUILD_TESTING:BOOL=OFF -DCMAKE_CXX_STANDARD:STRING=11 
-DBUILD_SHARED_LIBS:BOOL=OFF -Donnxruntime_BUILD_UNIT_TESTS=OFF -Donnxruntime_DEV_MODE=OFF -Donnxruntime_USE_FEATURIZERS=OFF 
-Donnxruntime_ENABLE_PYTHON=OFF -Donnxruntime_USE_OPENBLAS=OFF -Donnxruntime_USE_DNNL=OFF -Donnxruntime_USE_MKLML=OFF -Donnxruntime_USE_NGRAPH=OFF 
-Donnxruntime_USE_OPENVINO=OFF -Donnxruntime_USE_NNAPI_DNNLIBRARY=OFF -Donnxruntime_USE_NNAPI_BUILTIN=OFF -Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF 
-Donnxruntime_DISABLE_CONTRIB_OPS=OFF -Donnxruntime_MSVC_STATIC_RUNTIME=OFF -Donnxruntime_USE_TELEMETRY=OFF -Donnxruntime_ENABLE_LTO=OFF 
-Donnxruntime_BUILD_BENCHMARKS=OFF -Donnxruntime_USE_FULL_PROTOBUF=OFF -Donnxruntime_BUILD_FOR_NATIVE_MACHINE=OFF -Donnxruntime_BUILD_SHARED_LIB=ON 
-Donnxruntime_USE_EIGEN_FOR_BLAS=ON -Donnxruntime_USE_OPENMP=ON -Donnxruntime_ARMNN_RELU_USE_CPU=ON -Donnxruntime_ARMNN_BN_USE_CPU=ON 
-Donnxruntime_ENABLE_TRAINING=OFF -Donnxruntime_PREFER_SYSTEM_LIB=ON -Donnxruntime_USE_CUDA:BOOL=ON
-DCUDA_TOOLKIT_ROOT_DIR:PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1 
-Donnxruntime_CUDA_HOME:PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1 
-Donnxruntime_CUDNN_HOME:PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1 
-T host=x64 H:/dev/Sources/onnxruntime/cmake
```

**Expected behavior**
Compilation should continue to work.

**Additional context**
Compilation errors similar to these now appear:
```
.../onnxruntime/core/providers/cuda/object_detection/roialign_impl.cu(131): error : calling a __host__ function("__ceilf") from a __global__ function("onnxruntime::cuda::RoIAlignForward<float> ") is not allowed
.../onnxruntime/core/providers/cuda/object_detection/roialign_impl.cu(131): error : identifier "__ceilf" is undefined in device code
.../onnxruntime/core/providers/cuda/object_detection/roialign_impl.cu(134): error : calling a __host__ function("__ceilf") from a __global__ function("onnxruntime::cuda::RoIAlignForward<float> ") is not allowed
.../onnxruntime/core/providers/cuda/object_detection/roialign_impl.cu(134): error : identifier "__ceilf" is undefined in device code
.../onnxruntime/core/providers/cuda/tensor/resize_impl.cu(525): error : calling a __host__ function("__floorf") from a __global__ function("onnxruntime::cuda::_ResizeCubicCoordinateMapping<float> ") is not allowed
.../onnxruntime/core/providers/cuda/tensor/resize_impl.cu(525): error : identifier "__floorf" is undefined in device code
.../onnxruntime/core/providers/cuda/tensor/resize_impl.cu(525): error : calling a __host__ function("__floorf") from a __global__ function("onnxruntime::cuda::_ResizeCubicCoordinateMapping<double> ") is not allowed
.../onnxruntime/core/providers/cuda/tensor/resize_impl.cu(525): error : identifier "__floorf" is undefined in device code
.../onnxruntime/core/providers/cuda/tensor/resize_impl.cu(525): error : calling a __host__ function("__floorf") from a __global__ function("onnxruntime::cuda::_ResizeCubicCoordinateMapping<    ::__half> ") is not allowed
.../onnxruntime/core/providers/cuda/tensor/resize_impl.cu(525): error : identifier "__floorf" is undefined in device code
.../onnxruntime/core/providers/cuda/tensor/resize_impl.cu(525): error : calling a __host__ function("__floorf") from a __global__ function("onnxruntime::cuda::_ResizeCubicCoordinateMapping<int> ") is not allowed
```
The list of error goes on for other integral types like `unsigned char` as well as for function `roundf` at least

**Comment by yuslepukhin** [comment]
This is an NVIDIA compiler issue.  We have worked around it in the later versions of the code when we migrated to newer versions of CUDA.

**Comment by snnn** [comment]
The latest code works fine with the latest Visual Studio release.

ONNX Runtime 1.6.0 was released long before Visual Studio 2019 16.10.0,  sorry we don't plan to go back and patch it for such compiler compatibility issues.

**Comment by snnn** [comment]
Probably you can try this fix: #7140

**Comment by eldruin** [comment]
I see. Thank you for your answers.
I assume the released version 1.8.0 also works fine with the latest VS2019.
I will prioritize updating to version 1.8.0 internally since we already planned to do it and reopen this if that does not work.
Thanks again!

**Comment by snnn** [comment]
> I assume the released version 1.8.0 also works fine with the latest VS2019.

Sorry,  it's not. It needs #7883 .

**Comment by eldruin** [comment]
Ah, too bad but thank you for letting me know already.
Since the next release will be in 6 months according to the schedule, I will update to the current master then.
Do you know if the current master breaks compatibility with VS2017?
VS2017 already supports C++17 but I am unsure if all corner cases are included.

**Comment by snnn** [comment]
> if the current master breaks compatibility with VS2017

Likely, yes.

**Comment by eldruin** [comment]
Alright, thanks for the information. I'll see what I can do.
