### ISSUE TITLE
onnxruntime::GetProviderInfo_CUDA CUDA Provider not available, can't get interface for it

### ISSUE THREAD

**Issue by feiyuhuahuo** [microsoft/onnxruntime#8015]
**Describe the bug**
I was using pyinstaller to pack my program. The program can run successfully in PyCharm. And it can be packed successfully in Anaconda Prompt. But when I run the .exe file, I just get the error. 

**Urgency**
None

**System information**
- Windows10
- pip install onnxruntime-gpu
- ONNX Runtime version: 1.8.0
- Python version: 3.9.5
- Visual Studio version (if applicable): None
- CUDA/cuDNN version: 11.3 / 8.x
- GPU model and memory: RTX2080 super with Max-Q Design

**To Reproduce**
The code is simple.
```
import cv2
import onnxruntime as ort
import numpy as np

img = cv2.imread('58.bmp').astype('float32')
img = img / 255.
img = np.transpose(img[..., (2, 1, 0)], (2, 0, 1))  # To RGB, to (C, H, W).
img = img[None, :]

sess = ort.InferenceSession('solar_cell_seg.onnx')
input_name = sess.get_inputs()[0].name

output = sess.run(None, {input_name: img})  # list
pred = np.argmax(output[0], axis=1)[0]
print(pred.sum())
```
Then in Anaconda Prompt, I just type in `pyinstaller ort_deploy.py`. And it succeded.
After I ran the .exe file, I got the following error.
**Screenshots**
![image](https://user-images.githubusercontent.com/32631344/121474996-71e6fa80-c9f7-11eb-99a2-0ff8b7819698.png)

**Comment by pranavsharma** [comment]
We only support cuda 11.0 for the prebuilt pkg. See https://www.onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements.

**Comment by jywu-msft** [comment]
see https://github.com/microsoft/onnxruntime/issues/7346#issuecomment-823790553

**Comment by gwang-msft** [comment]
See https://github.com/microsoft/onnxruntime/issues/7346#issuecomment-1072025570
