### ISSUE TITLE
PrepareForCompute Non concat axis dimensions mismatch

### ISSUE THREAD

**Issue by nefario7** [microsoft/onnxruntime#8020]
**Describe the bug**
Matterport mask RCNN model converted to ONNX with ONNX Runtime gives the following error for both dummy input and actual input for the model. 

```
# Load Model
sess = ort.InferenceSession("../segmentation_model_onnx.onnx")

# Sample input
input1 = np.zeros((1, 66836, 4), np.float32)
input2 = np.zeros((1, 448, 448, 3), np.float32)
input3 = np.zeros((1, 16), np.float32)

# Run Model
results_ort = sess.run([output.name for output in sess._outputs_meta], {"input_anchors": input1, "input_image": input2, "input_image_meta": input3})
```

Error Message:
```
2021-06-10 18:59:13.312242848 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running Concat node. Name:'StatefulPartitionedCall/mask_rcnn/roi_align_classifier/concat' Status Message: concat.cc:84 PrepareForCompute Non concat axis dimensions must match: Axis 1 has mismatched dimensions of 0 and 7
Traceback (most recent call last):
  File "onnx_check.py", line 25, in <module>
    results_ort = sess.run([output.name for output in sess._outputs_meta], {"input_anchors": input1, "input_image": input2, "input_image_meta": input3})
  File "/home/AD/cgarg/segmentation/.onnx/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Concat node. Name:'StatefulPartitionedCall/mask_rcnn/roi_align_classifier/concat' Status Message: concat.cc:84 PrepareForCompute Non concat axis dimensions must match: Axis 1 has mismatched dimensions of 0 and 7
```

The inputs and outputs for the ONNX model are :
```
OUTPUTS
0       ROI     [1, 'unk__4837', 'unk__4838']   tensor(float)
1       mrcnn_bbox      [1, 2000, 4, 4]         tensor(float)
2       mrcnn_class     [1, 2000, 4]    tensor(float)
3       mrcnn_detection         [1, 50, 6]      tensor(float)
4       mrcnn_mask      [1, 50, 28, 28, 4]      tensor(float)
5       rpn_bbox        ['unk__4839', 'unk__4840', 4]   tensor(float)
6       rpn_class       ['unk__4841', 'unk__4842', 2]   tensor(float)

INPUTS
0       input_anchors   ['unk__4831', 'unk__4832', 4]   tensor(float)
1       input_image     ['unk__4833', 'unk__4834', 'unk__4835', 3]      tensor(float)
2       input_image_meta        ['unk__4836', 16]       tensor(float)
```

I have also tried to add SignatureDefs to the saved model before converting to ONNX but still leads to the same error.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.9.0
- Python version: 3.6.9
- Tensorflow version: 2.5.0
- GPU model and memory: RTX 2080

**To Reproduce**
- Model : [Segmentation Model in ONNX Format](https://drive.google.com/file/d/1zh1LkHdlYcMixiMmeCYVv07qtRKvEwH1/view?usp=sharing)

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by hariharans29** [comment]
Can you please share the model ?

**Comment by nefario7** [comment]
> Can you please share the model ?

Yeah, sure. My bad, forgot to share it with the issue.
[Segmentation Model in ONNX Format](https://drive.google.com/file/d/1zh1LkHdlYcMixiMmeCYVv07qtRKvEwH1/view?usp=sharing)

**Comment by nefario7** [comment]
I am really hoping to get this solved quickly for an urgent task.

**Comment by hariharans29** [comment]
Nothing obvious jumps out to indicate it is a runtime bug. 

Did you try inferencing a "real" input (i.e.) an input that works using the base framework model but fails with this ONNX model while using ORT ? If so, please share that. I suspect providing np.zeros() for the image input may not be a very useful repro step as there may not be any region to segment and we have seen in the past that some ONNX object detection models couldn't handle zero object detections in the image. If something similar is the case here, you would have to bring it to the attention of the project that helped you convert the model.

**Comment by nefario7** [comment]
> Nothing obvious jumps out to indicate it is a runtime bug.
> 
> Did you try inferencing a "real" input (i.e.) an input that works using the base framework model but fails with this ONNX model while using ORT ? If so, please share that. I suspect providing np.zeros() for all the inputs may not be a very useful repro step as there may not be any region to segment and we have seen in the past that some ONNX object detection models couldn't handle zero object detections in the image. If something similar is the case here, you would have to bring it to the attention of the project that helped you convert the model.

Yeah, I've tried it with a real input as well, which works in the normal TF model, and also TF Lite. But I got the same error with the real input in the converted ONNX model, and if not exactly the same, it was still about an axis dimension mismatch.

It'll be difficult for me to share a sample image, as the input image goes through a lot of pre-processing before going into the model with appropriate input dimensions. Also, as it's a multi-input model, there are different inputs like the anchors and meta data along with the image.

What if instead of passing zero arrays, you randomly populate the inputs with garbage values?

**Comment by hariharans29** [comment]
Is there a way you can share inputs as serialized numpy arrays (after pre-processing and all that needs to get done before passing it onto the graph) ?

Garbage data isn't really too different from np.zeros() for this exercise, it is hard to really prove that the garbage data had detections/regions of interest like a "real" image. 

I expect to see the same error even for a "valid" input with 0 detections (something crytic about an operator failing a runtime check and one of the dims being 0). We had the exact same scenario a while back with a Mask RCNN model exported from PyTorch that was basically failing a node for inputs that had 0 detections. Unfortunately, ORT can't do too much about these node execution failures if it violates the ONNX spec (like in this case, we are concatenating inputs in which the non-concat axes' dim values differed - this is a direct violation of the ONNX spec for the Concat operator). It is upto the model to handle such cases more gracefully and exit the graph prior to such nodes. When we bought this up to the Torch exporter group, they had acknowledged this and said they will account for this in future.

This is the reason why we strongly feel that we require a "real" image producing (at-least one) detection to even investigate (even then, the issue could still be one of conversion/export but atleast it is more concrete to go on than garbage data/np.zeros()).

**Comment by nefario7** [comment]
> Is there a way you can share inputs as serialized numpy arrays (after pre-processing and all that needs to get done before passing it onto the graph) ?
> 
> Garbage data isn't really too different from np.zeros() for this exercise, it is hard to really prove that the garbage data had detections/regions of interest like a "real" image.
> 
> I expect to see the same error even for a "valid" input with 0 detections (something cryptic about an operator failing a runtime check and one of the dims being 0). We had the exact same scenario a while back with a Mask RCNN model exported from PyTorch that was basically failing a node for inputs that had 0 detections. Unfortunately, ORT can't do too much about these node execution failures if it violates the ONNX spec (like in this case, we are concatenating inputs in which the non-concat axes' dim values differed - this is a direct violation of the ONNX spec for the Concat operator). It is upto the model to handle such cases more gracefully and exit the graph prior to such nodes. When we bought this up to the Torch exporter group at that time, they had acknowledged this and said they will account for this in future.
> 
> This is the reason why we strongly feel that we require a "real" image producing (at-least one) detection to even investigate (even then, the issue could still be one of conversion/export but atleast it is more concrete to go on than garbage data/np.zeros()).

Alright, yeah I guess that makes sense.

I've saved the inputs after preprocessing in the attached zip file. Hope this works.
- image_anchors (shape: (1, 66836, 4))
- image_metas (shape: (1, 16))
- molded_images (shape: (1, 448, 448, 3)) 

[onnx_sample_data.zip](https://github.com/microsoft/onnxruntime/files/6655053/onnx_sample_data.zip)

**Comment by hariharans29** [comment]
Thanks - that was very useful. I have an idea what happened here but I want to validate my theory and fix. Would it be possible to share the expected output for the above test case in the same format (serialized numpy) ?

**Comment by nefario7** [comment]
Yeah, sure. So, I have attached the expected outputs, but I have included only two outputs which I am actually using from the model.    

The outputs gives the following outputs: 
`['ROI', 'mrcnn_bbox', 'mrcnn_class', 'mrcnn_detection', 'mrcnn_mask', 'rpn_bbox', 'rpn_class']`

I have attached `mrcnn_detection` and `mrcnn_mask` in the zip.

[expected_output.zip](https://github.com/microsoft/onnxruntime/files/6661540/expected_output.zip)

**Comment by hariharans29** [comment]
Thanks. With the fix, the model ran to completion and the results for those two outputs matched with the expected outputs.

**Comment by nefario7** [comment]
Oh that's great. Thanks for the help.

I'll try to install the latest changes once they are available in the ort-nightly release.

**Comment by pra-dan** [comment]
Hi @nefario7 
I am using Mask-RCNN too and mainly for the purpose of getting faster inference using TensorRT on NVIDIA embedded systems. 

Are you working on something similar (related to optimisation for faster results) ?

Also, when I convert my frozen graph (`.pb`) to onnx, a `input_image_meta` layer gets automatically appended onto the `input_image` layer. This seems to be somewhat troublesome in my case. Did you suffer something similar ? 

<img width="490" alt="Screenshot 2021-08-11 at 1 57 02 PM" src="https://user-images.githubusercontent.com/46529961/128996112-72bf8205-97e9-4558-aa0f-8ba8ede0b1eb.png">

Thanks and Regards
