### ISSUE TITLE
How to perform Batch inferencing with RoBERTa ONNX quantized model?

### ISSUE THREAD

**Issue by yaminipreethi** [microsoft/onnxruntime#8030]
I have converted RoBERTa PyTorch model to ONNX model and quantized it. I am able to get the scores from ONNX model for single input data point (each sentence). I want to understand how to get batch predictions using ONNX Runtime inference session by passing multiple inputs to the session. Below is the example scenario.

Model : roberta-quant.onnx which is a ONNX quantized version of RoBERTa PyTorch model

Code used to convert RoBERTa to ONNX:

    torch.onnx.export(model,                                            
                          args=tuple(inputs.values()),                      # model input 
                          f=export_model_path,                              # where to save the model 
                          opset_version=11,                                 # the ONNX version to export the model to
                          do_constant_folding=True,                         # whether to execute constant folding for optimization
                          input_names=['input_ids',                         # the model's input names
                                       'attention_mask'],
                          output_names=['output_0'],                    # the model's output names
                          dynamic_axes={'input_ids': symbolic_names,        # variable length axes
                                        'attention_mask' : symbolic_names,
                                        'output_0' : {0: 'batch_size'}})

Input sample to ONNXRuntime inference session:

    {
	     'input_ids': array([[    0, 510, 35, 21071, ....., 1, 1,  1,  1, 1, 1]]),
	     'attention_mask': array([[1, 1, 1, 1, ......., 0, 0, 0, 0, 0, 0]])
    }

Running ONNX model for 400 data samples(sentences) using ONNXRuntime inference session:

    session = onnxruntime.InferenceSession("roberta_quantized.onnx", providers=['CPUExecutionProvider'])
    for i in range(400):
       ort_inputs = {
        'input_ids':  input_ids[i].cpu().reshape(1, max_seq_length).numpy(),  # max_seq_length=128 here
        'input_mask': attention_masks[i].cpu().reshape(1, max_seq_length).numpy()
       }
    
       ort_outputs = session.run(None, ort_inputs)

In the above code I am looping through 400 sentences sequentially to get the scores "`ort_outputs`". Please help me understand **how can I perform batch processing** here using the ONNX model, where I can send the `inputs_ids` and `attention_masks` for multiple sentences and get the scores for all sentences in `ort_outputs`.

Thanks in advance!

**Comment by tianleiwu** [comment]
@yaminipreethi, you need compose inputs for each batch. The shape of input_ids and attention_mask is (batch_size, sequence_length). Your example has batch_size=1. Here is an example of batch_size==2:
```
{
     'input_ids': array([
     [    0, 510, 35, 21071, ....., 1, 1],
     [    4, 31, 3, 8, ....., 15, 14],
     ]),
     'attention_mask': array([
        [1, 1, 1, 1, ......, 0, 0],
        [1, 1, 1, 1, ......, 1, 1]])
}

If different samples have different sequence lengths,  you will need have some padding logic.
```

Here is an example code for batching applies to [mlperf](https://github.com/mlcommons/inference/blob/master/language/bert/onnxruntime_SUT.py):
```
        def issue_queries(self, query_samples):
            num_samples = len(query_samples)
            actual_lengths = []
            for i in range(num_samples):
                eval_features = self.qsl.get_features(query_samples[i].index)
                actual_seq_length = sum(eval_features.input_mask)
                actual_lengths.append(actual_seq_length)
            lengths = np.array(actual_lengths)
            sort_index = np.argsort(lengths)

            total_batches = int((num_samples + self.batch_size - 1) / self.batch_size)
            for j in range(total_batches):
                indices = sort_index[self.batch_size * j:self.batch_size * (j + 1)]
                samples = [self.qsl.get_features(query_samples[i].index) for i in indices]
                sample_ids = [query_samples[i].id for i in indices]
                take_lengths = np.take(lengths, indices)
                max_lengths = np.max(take_lengths)

                input_ids = np.zeros((len(samples), max_lengths), dtype=self.input_dtype)
                input_mask = np.zeros((len(samples), max_lengths), dtype=self.input_dtype)
                segment_ids = np.zeros((len(samples), max_lengths), dtype=self.input_dtype)
                for k, sample in enumerate(samples):
                    length = take_lengths[k]
                    input_ids[k, :length] = sample.input_ids[:length]
                    input_mask[k, :length] = sample.input_mask[:length]
                    segment_ids[k, :length] = sample.segment_ids[:length]

                input = {"input_ids": input_ids, self.input_mask_name: input_mask, self.segment_ids_name: segment_ids}

                scores = self.sess.run(self.output_names, input)
```

**Comment by yaminipreethi** [comment]
Thanks @tianleiwu !

**Comment by rohanshingade** [comment]
@yaminipreethi does batch inference on quantized model gives consistent results? for me prediction changes slightly as batch size changes

**Comment by tianleiwu** [comment]
For dynamic quantization, result changes with input. You can try static quantization to see whether you can get consistent results.

**Comment by yaminipreethi** [comment]
> @yaminipreethi does batch inference on quantized model give consistent results? for me prediction changes slightly as batch size changes

Yes, there would be slight difference in results with batch inferencing using quantized model.
