### ISSUE TITLE
init session failed when using dll

### ISSUE THREAD

**Issue by Newer2019** [microsoft/onnxruntime#8032]
onnxruntimt 1.6.0 cpu version
visual studio 2015

Ort::Session session({ env, onnxModel, Ort::SessionOptions{nullptr} })

when not in dll, inference runs well, but when i put the same code in a dll
initing session will get no response, and memory remains very low,
seems the onnx model not loading correctly.

any hint on this issue, thanks.

**Comment by Newer2019** [comment]
btw， if i set onnxModel = L""   same thing happens, seems something wrong with the model name.

**Comment by pranavsharma** [comment]
> initing session will get no response

What does this mean? Are you getting an exception? Although it might not matter here you can try our latest version 1.8.0.

**Comment by Newer2019** [comment]
no exception received,  in fact, i got no response until timeout (about 2-3 minutes) and exit with -1.

**Comment by Newer2019** [comment]
i changed to 1.8.0, and it works.  but did not find the reason why.
