### ISSUE TITLE
model loading error: inference_session.cc:1043 LoadOrtModel The ORT format model version [3] is not supported this build 1.8.0

### ISSUE THREAD

**Issue by seungillee** [microsoft/onnxruntime#8044]
**Describe the bug**
When I tried to load .ort format model, the following error occurs;

```
model loading error: inference_session.cc:1043 LoadOrtModel The ORT format model version [3] is not supported this build 1.8.0
```

I probably missed something, but I tried to use convert script from onnxruntime repository like `python tools/python/convert_onnx_models_to_ort.py` and also tried to use as `python -m onnxruntime.tools.convert_onnx_models_to_ort` but both give same results. It seems the ort format is always converted to format model version [3], and onnxruntime is only supporting format model version [4]. How can I convert onnx model into format movel version [4] ort file?

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.8.0
- Python version: 3.6
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): Apple clang version 12.0.5 (clang-1205.0.22.9)
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**
It should load ort model file without error.

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by seungillee** [comment]
Found the root cause. Used wrong ort file, apparently new ort file was not used.

**Comment by penut85420** [comment]
@seungillee save my time, thanks!

**Comment by BioWar** [comment]
@seungillee I have a similar problem with an error message: "LoadOrtModel ORT model verification failed." 

How can I check the model.ort version?
