### ISSUE TITLE
recompile error, please help

### ISSUE THREAD

**Issue by Newer2019** [microsoft/onnxruntime#8045]
win 10, vs2019, onnxruntime 1.6, when recompile, i got the following messages, please help...

================

D:\git\onnxruntime-1.6.0\onnxruntime-1.6.0>
D:\git\onnxruntime-1.6.0\onnxruntime-1.6.0>.\build.bat  --cmake_generator "Visual Studio 16 2019"
2021-06-13 17:56:21,357 build [DEBUG] - Defaulting to running update, build [and test for native builds].
2021-06-13 17:56:21,389 build [INFO] - Build started
2021-06-13 17:56:21,390 util.run [INFO] - Running subprocess in 'D:\git\onnxruntime-1.6.0\onnxruntime-1.6.0'
['git', 'submodule', 'sync', '--recursive']
2021-06-13 17:56:30,139 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-06-13 17:56:30,139 util.run [INFO] - Running subprocess in 'D:\git\onnxruntime-1.6.0\onnxruntime-1.6.0'
['git', 'submodule', 'update', '--init', '--recursive']
2021-06-13 17:56:38,066 util.run [DEBUG] - Subprocess completed. Return code: 0
2021-06-13 17:56:38,067 build [INFO] - Generating CMake build tree
2021-06-13 17:56:38,068 util.run [INFO] - Running subprocess in 'D:\git\onnxruntime-1.6.0\onnxruntime-1.6.0\\build\Windows\Debug'
['D:\\Program Files\\CMake\\bin\\cmake.EXE', 'D:\\git\\onnxruntime-1.6.0\\onnxruntime-1.6.0\\cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_BUILD_WINML_TESTS=ON', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-Donnxruntime_DEV_MODE=ON', '-DPYTHON_EXECUTABLE=d:\\ProgramData\\Anaconda3\\python.exe', '-Donnxruntime_USE_CUDA=OFF', '-Donnxruntime_CUDNN_HOME=', '-Donnxruntime_USE_FEATURIZERS=OFF', '-Donnxruntime_CUDA_HOME=', '-Donnxruntime_USE_JEMALLOC=OFF', '-Donnxruntime_USE_MIMALLOC_STL_ALLOCATOR=OFF', '-Donnxruntime_USE_MIMALLOC_ARENA_ALLOCATOR=OFF', '-Donnxruntime_ENABLE_PYTHON=OFF', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_JAVA=OFF', '-Donnxruntime_BUILD_NODEJS=OFF', '-Donnxruntime_BUILD_SHARED_LIB=OFF', '-Donnxruntime_USE_EIGEN_FOR_BLAS=ON', '-Donnxruntime_USE_OPENBLAS=OFF', '-Donnxruntime_USE_DNNL=OFF', '-Donnxruntime_DNNL_GPU_RUNTIME=', '-Donnxruntime_DNNL_OPENCL_ROOT=', '-Donnxruntime_USE_MKLML=OFF', '-Donnxruntime_USE_NNAPI_BUILTIN=OFF', '-Donnxruntime_USE_RKNPU=OFF', '-Donnxruntime_USE_OPENMP=OFF', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_VITISAI=OFF', '-Donnxruntime_USE_NUPHAR=OFF', '-Donnxruntime_USE_TENSORRT=OFF', '-Donnxruntime_TENSORRT_HOME=', '-Donnxruntime_USE_MIGRAPHX=OFF', '-Donnxruntime_MIGRAPHX_HOME=', '-Donnxruntime_CROSS_COMPILING=OFF', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_DISABLE_ML_OPS=OFF', '-Donnxruntime_DISABLE_RTTI=OFF', '-Donnxruntime_DISABLE_EXCEPTIONS=OFF', '-Donnxruntime_DISABLE_ORT_FORMAT_LOAD=OFF', '-Donnxruntime_MINIMAL_BUILD=OFF', '-Donnxruntime_EXTENDED_MINIMAL_BUILD=OFF', '-Donnxruntime_REDUCED_OPS_BUILD=OFF', '-Donnxruntime_MSVC_STATIC_RUNTIME=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=OFF', '-Donnxruntime_USE_WINML=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxruntime_USE_ACL=OFF', '-Donnxruntime_USE_ACL_1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_USE_ACL_2002=OFF', '-Donnxruntime_USE_ARMNN=OFF', '-Donnxruntime_ARMNN_RELU_USE_CPU=ON', '-Donnxruntime_ARMNN_BN_USE_CPU=ON', '-Donnxruntime_ENABLE_NVTX_PROFILE=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_USE_HOROVOD=OFF', '-Donnxruntime_USE_NCCL=ON', '-Donnxruntime_BUILD_BENCHMARKS=OFF', '-Donnxruntime_USE_ROCM=OFF', '-Donnxruntime_ROCM_HOME=', '-Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF', '-A', 'x64', '-T', 'host=x64', '-G', 'Visual Studio 16 2019', '-Donnxruntime_ENABLE_MEMLEAK_CHECKER=ON', '-DCMAKE_BUILD_TYPE=Debug']
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.29.30037.0
-- The CXX compiler identification is MSVC 19.29.30037.0
-- Check for working C compiler: d:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: d:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: d:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: d:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Performing Test HAS_QSPECTRE
-- Performing Test HAS_QSPECTRE - Failed
-- Performing Test HAS_GUARD_CF
-- Performing Test HAS_GUARD_CF - Success
Use gtest from submodule
CMake Error at CMakeLists.txt:478 (add_subdirectory):
  The source directory

    D:/git/onnxruntime-1.6.0/onnxruntime-1.6.0/cmake/external/googletest

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:479 (set_target_properties):
  set_target_properties Can not find target to add properties to: gmock

CMake Error at CMakeLists.txt:480 (set_target_properties):
  set_target_properties Can not find target to add properties to: gmock_main

CMake Error at CMakeLists.txt:481 (set_target_properties):
  set_target_properties Can not find target to add properties to: gtest

CMake Error at CMakeLists.txt:482 (set_target_properties):
  set_target_properties Can not find target to add properties to: gtest_main

CMake Error at CMakeLists.txt:483 (add_library):
  add_library cannot create ALIAS target "GTest::gmock" because target
  "gmock" does not already exist.

CMake Error at CMakeLists.txt:484 (add_library):
  add_library cannot create ALIAS target "GTest::gmock_main" because target
  "gmock_main" does not already exist.

CMake Error at CMakeLists.txt:485 (add_library):
  add_library cannot create ALIAS target "GTest::gtest" because target
  "gtest" does not already exist.

CMake Error at CMakeLists.txt:486 (add_library):
  add_library cannot create ALIAS target "GTest::gtest_main" because target
  "gtest_main" does not already exist.

Use protobuf from submodule
CMake Error at CMakeLists.txt:565 (add_subdirectory):
  add_subdirectory given source
  "D:/git/onnxruntime-1.6.0/onnxruntime-1.6.0/cmake/external/protobuf/cmake"
  which is not an existing directory.

CMake Error at CMakeLists.txt:577 (add_library):
  add_library cannot create ALIAS target "protobuf::libprotobuf" because
  target "libprotobuf-lite" does not already exist.

CMake Error at CMakeLists.txt:626 (add_subdirectory):
  The source directory

    D:/git/onnxruntime-1.6.0/onnxruntime-1.6.0/cmake/external/date

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:642 (add_subdirectory):
  The source directory

    D:/git/onnxruntime-1.6.0/onnxruntime-1.6.0/cmake/external/re2

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:643 (set_target_properties):
  set_target_properties Can not find target to add properties to: re2

CMake Error at CMakeLists.txt:644 (add_library):
  add_library cannot create ALIAS target "re2::re2" because target "re2" does
  not already exist.

CMake Error at CMakeLists.txt:837 (add_subdirectory):
  The source directory

    D:/git/onnxruntime-1.6.0/onnxruntime-1.6.0/cmake/external/onnx

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:842 (target_compile_definitions):
  Cannot specify compile definitions for target "onnx" which is not built by
  this project.

CMake Error at CMakeLists.txt:844 (target_compile_definitions):
  Cannot specify compile definitions for target "onnx" which is not built by
  this project.

CMake Error at CMakeLists.txt:846 (set_target_properties):
  set_target_properties Can not find target to add properties to: onnx

CMake Error at CMakeLists.txt:847 (set_target_properties):
  set_target_properties Can not find target to add properties to: onnx_proto

CMake Error at CMakeLists.txt:885 (add_subdirectory):
  The source directory

    D:/git/onnxruntime-1.6.0/onnxruntime-1.6.0/cmake/external/flatbuffers

  does not contain a CMakeLists.txt file.

-- The ASM_MASM compiler identification is MSVC
-- Found assembler: D:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30037/bin/Hostx64/x64/ml64.exe
-- Configuring incomplete, errors occurred!
See also "D:/git/onnxruntime-1.6.0/onnxruntime-1.6.0/build/Windows/Debug/CMakeFiles/CMakeOutput.log".
See also "D:/git/onnxruntime-1.6.0/onnxruntime-1.6.0/build/Windows/Debug/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "D:\git\onnxruntime-1.6.0\onnxruntime-1.6.0\\tools\ci_build\build.py", line 2088, in <module>
    sys.exit(main())
  File "D:\git\onnxruntime-1.6.0\onnxruntime-1.6.0\\tools\ci_build\build.py", line 2011, in main
    path_to_protoc_exe, configs, cmake_extra_defines, args, cmake_extra_args)
  File "D:\git\onnxruntime-1.6.0\onnxruntime-1.6.0\\tools\ci_build\build.py", line 1013, in generate_build_tree
    cwd=config_build_dir)
  File "D:\git\onnxruntime-1.6.0\onnxruntime-1.6.0\\tools\ci_build\build.py", line 523, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "D:\git\onnxruntime-1.6.0\onnxruntime-1.6.0\tools\python\util\run.py", line 42, in run
    env=env, shell=shell)
  File "d:\ProgramData\Anaconda3\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['D:\\Program Files\\CMake\\bin\\cmake.EXE', 'D:\\git\\onnxruntime-1.6.0\\onnxruntime-1.6.0\\cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_BUILD_WINML_TESTS=ON', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-Donnxruntime_DEV_MODE=ON', '-DPYTHON_EXECUTABLE=d:\\ProgramData\\Anaconda3\\python.exe', '-Donnxruntime_USE_CUDA=OFF', '-Donnxruntime_CUDNN_HOME=', '-Donnxruntime_USE_FEATURIZERS=OFF', '-Donnxruntime_CUDA_HOME=', '-Donnxruntime_USE_JEMALLOC=OFF', '-Donnxruntime_USE_MIMALLOC_STL_ALLOCATOR=OFF', '-Donnxruntime_USE_MIMALLOC_ARENA_ALLOCATOR=OFF', '-Donnxruntime_ENABLE_PYTHON=OFF', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_JAVA=OFF', '-Donnxruntime_BUILD_NODEJS=OFF', '-Donnxruntime_BUILD_SHARED_LIB=OFF', '-Donnxruntime_USE_EIGEN_FOR_BLAS=ON', '-Donnxruntime_USE_OPENBLAS=OFF', '-Donnxruntime_USE_DNNL=OFF', '-Donnxruntime_DNNL_GPU_RUNTIME=', '-Donnxruntime_DNNL_OPENCL_ROOT=', '-Donnxruntime_USE_MKLML=OFF', '-Donnxruntime_USE_NNAPI_BUILTIN=OFF', '-Donnxruntime_USE_RKNPU=OFF', '-Donnxruntime_USE_OPENMP=OFF', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_VITISAI=OFF', '-Donnxruntime_USE_NUPHAR=OFF', '-Donnxruntime_USE_TENSORRT=OFF', '-Donnxruntime_TENSORRT_HOME=', '-Donnxruntime_USE_MIGRAPHX=OFF', '-Donnxruntime_MIGRAPHX_HOME=', '-Donnxruntime_CROSS_COMPILING=OFF', '-Donnxruntime_DISABLE_CONTRIB_OPS=OFF', '-Donnxruntime_DISABLE_ML_OPS=OFF', '-Donnxruntime_DISABLE_RTTI=OFF', '-Donnxruntime_DISABLE_EXCEPTIONS=OFF', '-Donnxruntime_DISABLE_ORT_FORMAT_LOAD=OFF', '-Donnxruntime_MINIMAL_BUILD=OFF', '-Donnxruntime_EXTENDED_MINIMAL_BUILD=OFF', '-Donnxruntime_REDUCED_OPS_BUILD=OFF', '-Donnxruntime_MSVC_STATIC_RUNTIME=OFF', '-Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF', '-Donnxruntime_USE_DML=OFF', '-Donnxruntime_USE_WINML=OFF', '-Donnxruntime_USE_TELEMETRY=OFF', '-Donnxruntime_ENABLE_LTO=OFF', '-Donnxruntime_USE_ACL=OFF', '-Donnxruntime_USE_ACL_1902=OFF', '-Donnxruntime_USE_ACL_1905=OFF', '-Donnxruntime_USE_ACL_1908=OFF', '-Donnxruntime_USE_ACL_2002=OFF', '-Donnxruntime_USE_ARMNN=OFF', '-Donnxruntime_ARMNN_RELU_USE_CPU=ON', '-Donnxruntime_ARMNN_BN_USE_CPU=ON', '-Donnxruntime_ENABLE_NVTX_PROFILE=OFF', '-Donnxruntime_ENABLE_TRAINING=OFF', '-Donnxruntime_USE_HOROVOD=OFF', '-Donnxruntime_USE_NCCL=ON', '-Donnxruntime_BUILD_BENCHMARKS=OFF', '-Donnxruntime_USE_ROCM=OFF', '-Donnxruntime_ROCM_HOME=', '-Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF', '-A', 'x64', '-T', 'host=x64', '-G', 'Visual Studio 16 2019', '-Donnxruntime_ENABLE_MEMLEAK_CHECKER=ON', '-DCMAKE_BUILD_TYPE=Debug']' returned non-zero exit status 1.

D:\git\onnxruntime-1.6.0\onnxruntime-1.6.0>

**Comment by snnn** [comment]
I believe the folder "D:/git/onnxruntime-1.6.0/onnxruntime-1.6.0/cmake/external/googletest" is empty. 

Does "D:/git/onnxruntime-1.6.0/onnxruntime-1.6.0/.git" exist?

**Comment by yuslepukhin** [comment]
git clone --recusrive

**Comment by Newer2019** [comment]
thanks snnn and  yuslepukhin， problem solved.
