### ISSUE TITLE
Is this Memory leak in onnxruntime Python API?

### ISSUE THREAD

**Issue by anandvsr** [microsoft/onnxruntime#8047]
![image](https://user-images.githubusercontent.com/66105422/121869419-a7555600-cd1f-11eb-9d86-4039d0b7af1c.png)

While using faster-rcnn model, which is convert from PyTorch.

PyTorch-version: 1.8.1
OnnxRuntime-version: 1.8.0
Python-version: 3.9.5
Inference-Provider: CPU

**Comment by hanbitmyths** [comment]
@anadvsr, can you check time-based memory usage, i.e. does memory keep increasing every predict() call?

**Comment by anandvsr** [comment]
```127.0.0.1 - - [15/Jun/2021:01:45:56] "POST /detect/ HTTP/1.1" 200 934 "" "curl/7.71.1"
[15/Jun/2021:01:45:56]  
INFO [-36] : Used  memory (before request): 5.65GB
INFO [-39] : Image shape : (4160, 3120, 3)
INFO [-105] : Used  memory (before prediction): 5.69GB
INFO [-114] : Used  memory (after prediction): 6.22GB
INFO [-50] : Detection time - 2.3656 s,
INFO [-51] : Total Object found - 9
INFO [-99] : Total request time - 2.6114 s
INFO [-43] : Used  memory (after request): 6.04GB
127.0.0.1 - - [15/Jun/2021:01:45:58] "POST /detect/ HTTP/1.1" 200 934 "" "curl/7.71.1"
[15/Jun/2021:01:45:58]  
INFO [-36] : Used  memory (before request): 6.04GB
INFO [-39] : Image shape : (4160, 3120, 3)
INFO [-105] : Used  memory (before prediction): 6.08GB
INFO [-114] : Used  memory (after prediction): 6.37GB
INFO [-50] : Detection time - 2.2305 s,
INFO [-51] : Total Object found - 9
INFO [-99] : Total request time - 2.4692 s
INFO [-43] : Used  memory (after request): 6.19GB
```
I have also attached the logs file.

[log.txt](https://github.com/microsoft/onnxruntime/files/6651037/log.txt)

**Comment by hanbitmyths** [comment]
I tried to run a [faster-rcnn model](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/faster-rcnn)  using onnxruntime 1.8.0 python package. But, I couldn't repro memory leak.

![faster-rcnn_memory](https://user-images.githubusercontent.com/35605090/122001929-eefed080-cd65-11eb-925a-1b9773b1a9d3.PNG)

Can you share session options you're using?

**Comment by anandvsr** [comment]
Can it be verified with parallel requests? I could not see the memory problem when it happened one by one. This happens when many requests come to the server. Finally now I got few things from your image too, I think memory  get stable after certain requests.

![Screenshot from 2021-06-15 12-55-18](https://user-images.githubusercontent.com/66105422/122012577-f4e2c900-cdda-11eb-9c29-eab5eccd0395.png)

When the next request is sent after one request is completed
![Screenshot from 2021-06-15 12-40-15](https://user-images.githubusercontent.com/66105422/122014057-6b33fb00-cddc-11eb-9626-c1824c294d11.png)


So now the question are, is this the nature? I have now idea, please clearly!!

```
P.S:
Lastly, I only registered when I started.
In first pic I decrease the request per second, because of getting >5 requests/s, 
memory get 100%, then the program will be killed.
```

**Comment by hanbitmyths** [comment]
It's a normal behavior when it gets more requests at the same time. It can abort due to memory allocation failure when there is no available memory on a system.

If your goal is to reduce memory footprint, you may try session options to disable cpu arena or memory pattern, but this is trade-off over performance.

**Comment by anandvsr** [comment]
Thank you for response @hanbitmyths  😌👍
