### ISSUE TITLE
Microsoft.ML.OnnxRuntime.Gpu 1.8.0: Failed to load library libonnxruntime_providers_shared.so

### ISSUE THREAD

**Issue by asvyazin** [microsoft/onnxruntime#8052]
Hello, I'm using precompiled nuget package Microsoft.ML.OnnxRuntime.Gpu in .Net application on linux

Version 1.7.1 worked fine

Version 1.8.0 started throwing exception:
```
Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:Fail] OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library
   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.SessionOptions.AppendExecutionProvider_CUDA(Int32 deviceId)
```

It also logs this error before the exception:
```
2021-06-15 11:57:25.542258449 [E:onnxruntime:CSharpOnnxRuntime, provider_bridge_ort.cc:902 Ensure] Failed to load library libonnxruntime_providers_shared.so with error: libonnxruntime_providers_shared.so: cannot open shared object file: No such file or directory
```

I downloaded and unpacked nupkg file from nuget.org and it looks to me that libonnxruntime_providers_bridge.so is missing in linux-x64 folder:
<img width="470" alt="Снимок экрана 2021-06-15 в 17 38 29" src="https://user-images.githubusercontent.com/541302/122054469-23739a80-ce01-11eb-9f8b-91783691c76b.png">

Probably I'm missing something, any ideas?

System information

    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Docker Container nvidia/cuda:11.0.3-cudnn8-runtime-ubuntu20.04
    ONNX Runtime installed from (source or binary): binary
    ONNX Runtime version: 1.8.0
    Python version: N/A
    Visual Studio version (if applicable): N/A
    GCC/Compiler version (if compiling from source): N/A
    CUDA/cuDNN version: 11.0.3/8.x.x (not sure about exact cuDNN version)
    GPU model and memory: nvidia A100

**Comment by jywu-msft** [comment]
looks like it is missing the required .so files under linux-x64/native

**Comment by snnn** [comment]
I believe it has been fixed and will be landed in the next patch release.

**Comment by hendrik-skubch** [comment]
I run into the same issue when using the C++ API and call `Ort::SessionOptions::AppendExecutionProvider_CUDA` on linux.

**Comment by snnn** [comment]
Thank you. We are solving it.

**Comment by hariharans29** [comment]
Should be fixed by https://github.com/microsoft/onnxruntime/pull/8066
