### ISSUE TITLE
session.Run() outputs wrong results if CUDA provider is used

### ISSUE THREAD

**Issue by sbugallo** [microsoft/onnxruntime#8072]
**Describe the bug**
When running inference with a video, if we use CUDA provider, only the first frame gets correct results, subsequent frames get wrong output and always the exact same values regardless of the frame's content. If we use the default provider (CPU), every frame gets the expected results (sample images are attached below).

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.7.2
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: CUDA 11.2 / cuDNN 8.1.1
- GPU model and memory: RTX 2070

**To Reproduce**
- Clone the following gist: [link](https://gist.github.com/sbugallo/5f620e2ce22f405285a8871ca22f6319)
- Build binary with:
```bash
mkdir build
cd build
cmake ..
make -j${nproc}
```
- Run:
```bash
./onnx_test <model_path> <model_width> <model_height> <video_path> <use_cuda_provider (1 or 0)>

Examples:
CPU
./onnx_test model.onnx 800 800 video.ts 0

CUDA provider
./onnx_test model.onnx 800 800 video.ts 1
```

**Expected behavior**
`session.Run()` outputs correct data regardless of the used provider.

**Screenshots**

GPU (first and second frame — the next frames get the same results as the second frame)
![frame_0_gpu](https://user-images.githubusercontent.com/6081282/122205679-d21ae800-cea0-11eb-8183-2be3aa615f10.jpg)
![frame_1_gpu](https://user-images.githubusercontent.com/6081282/122205720-da732300-cea0-11eb-9e5f-e81b2877de15.jpg)

CPU (first and second frame)

![frame_0_cpu](https://user-images.githubusercontent.com/6081282/122205774-e6f77b80-cea0-11eb-95d1-2ed10cf510ac.jpg)
![frame_1_cpu](https://user-images.githubusercontent.com/6081282/122205790-ea8b0280-cea0-11eb-9b1a-f76e24c6dd68.jpg)

**Comment by hanbitmyths** [comment]
@sbugallo, can you share a model and a video file for us to repro?

**Comment by sbugallo** [comment]
Hi, due to the policies of my company I cannot share the model. I tried to replicate this problem with other public models and everything works as expected. It looks like an error with some MMDetection models so I would rather create an issue in their repository. Thanks!
