### ISSUE TITLE
[python] [ORTModule] Can't load saved training model.

### ISSUE THREAD

**Issue by juharris** [microsoft/onnxruntime#8074]
**Is your feature request related to a problem? Please describe.**
I'm trying to produce a training graph so that I can compute gradients with an ONNX model.

FYI We were trying to use `ORTTrainer` with some debug options to output the training graphs and had a working solution with Python 3.6 and onnxruntime-training==1.7.0 but it doesn't work in onnxruntime-training==1.8.0 and doesn't work in all Python versions: `onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node MatMul_4_Grad/Gemm_0_transformed:Gemm(11)`.

So now we're trying to use `ORTModule` because it seems like that's more stable for now:
```Python
import os

import onnxruntime
import torch
from torch import nn
from torch_ort import ORTModule


class Net(nn.Module):
    """ A simple example model. """
    def __init__(self, loss_fn):
        super().__init__()
        self.l1 = nn.Linear(10, 5, bias=False)
        self.a1 = nn.Sigmoid()
        self.l2 = nn.Linear(self.l1.out_features, 2, bias=False)

        self.loss_fn = loss_fn

    def forward(self, x, label):
        result = self.l1(x)
        result = self.a1(result)
        result = self.l2(result)
        loss = self.loss_fn(result, label)
        return result, loss


loss_fn = nn.CrossEntropyLoss()
model = Net(loss_fn)
model.train()

module = ORTModule(model)
module._execution_manager._training_manager._save_onnx = True
module._execution_manager._training_manager._save_onnx_prefix = 'models/model'
path = module._execution_manager._training_manager._save_onnx_prefix + '_training.onnx'
# Make sure we get a new model.
if os.path.exists(path):
    os.remove(path)

# Get the graph to be computed.
module.forward(torch.rand(1, 10), torch.tensor([1]))

# Try to run the model and compute gradients.
session = onnxruntime.InferenceSession(path)
run_result = session.run(None, {
    'x': torch.rand(1, 10).numpy(),
    'label': torch.tensor([1]).numpy(),
    '_original_module.l1.weight': torch.rand(5, 10).numpy(),
    '_original_module.l2.weight': torch.rand(2, 5).numpy(),
})
print(run_result)
```

I get:
```
2021-06-16 19:20:16.523872573 [W:onnxruntime:, inference_session.cc:1303 Initialize] Serializing optimized model with Graph Optimization level greater than ORT_ENABLE_EXTENDED and the NchwcTransformer enabled. The generated model may contain hardware specific optimizations, and should only be used in the same environment the model was optimized in.
2021-06-16 19:20:20.543537015 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running YieldOp node. Name:'YieldOp' Status Message: This operator should not be executed.
Traceback (most recent call last):
  File "example.py", line 44, in <module>
    run_result = session.run(None, {
  File "/home/juharri/.conda/envs/python-3.8/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running YieldOp node. Name:'YieldOp' Status Message: This operator should not be executed.
```

**System information**
- ONNX Runtime version (you are using): 1.8.0
Ubuntu 18.04, Python 3.8
Docker image: pytorch/pytorch:1.8.1-cuda10.2-cudnn7-devel
```bash
$ pip freeze | grep -iE 'onnx|torch'
onnx @ file:///home/juharri/.cache/pypoetry/artifacts/87/96/2a/6eef1c75792b16e302fbfc03d1a8daada43987b6faba6a185d81d035be/onnx-1.9.0-cp38-cp38-manylinux2010_x86_64.whl
onnxruntime-training==1.8.0
torch==1.8.1
torch-ort==0.0.10
```

**Describe the solution you'd like**
An easy way to export the training graph so that we can compute gradients.
I would like to contribute this to onnxruntime but I'm trying to get it working for my example first.

**Describe alternatives you've considered**
Using `ORTTrainer` with debug options instead of `ORTModule` but with `ORTTrainer`, the gradients weren't output nodes so I would have to update something to get that working. Also in onnxruntime-training==1.8.0 with `ORTTrainer`, I get: `onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node MatMul_4_Grad/Gemm_0_transformed:Gemm(11)`.

**Additional context**
I would like to be able to run the ONNX training graph using ONNX Runtime Web in a build with training ops enabled.

UPDATE: I attached the exported model (model.onnx.txt to trick GitHub) and the image from https://netron.app/
![model_training onnx](https://user-images.githubusercontent.com/1594505/122281538-5dec3e80-ceb8-11eb-9c3f-a210aaa2d7a7.png)
[model_training.onnx.txt](https://github.com/microsoft/onnxruntime/files/6665416/model_training.onnx.txt)

**Comment by SherlockNoMad** [comment]
The training graph saved by ORTModule is designed to worked together with pytorch. The YieldOp will return the control to pytorch and resume the execution latter, thus this graph will not work with onnxruntime.InfereceSession() API.

**Comment by juharris** [comment]
Thanks for your quick response! Is there any way around this YieldOp behavior? If it's just by design, then feel free to close this issue.

 I'll make another issue to describe the problem we had with `ORTTrainer`.

**Comment by juharris** [comment]
It's by design.
