### ISSUE TITLE
Can the input tensor be created directly with the C sharp API?

### ISSUE THREAD

**Issue by feiyuhuahuo** [microsoft/onnxruntime#8081]
**Is your feature request related to a problem? Please describe.**
In this expample, the input data is modified one by one pixel with for...loop. Would this be slow? Is there a python-like way to pass the whole img data to the input tensor? Or can the tensor support NumSharp (https://github.com/SciSharp/NumSharp), so a new tensor can be created from an array, just like PyTorch, Python does?

https://github.com/microsoft/onnxruntime/blob/96989b83ee2da94e9eae78921d7ef0ee507e40ce/csharp/sample/Microsoft.ML.OnnxRuntime.FasterRcnnSample/Program.cs#L36-L45

And by the way, where can I get the detailed ONNXruntime C sharp documents? I am puzzled about how to use them. I want to know all of the functions, attributes...

**System information**
- ONNX Runtime version (you are using):
Microsoft.ML.OnnxRuntime 1.8.0

**Describe alternatives you've considered**
I think if it can support NumSharp, then it's excellent. It becomes easier for one to do machine learning with C sharp.

**Comment by hanbitmyths** [comment]
@feiyuhuahuo, ONNX Runtime C# APIs are [here](https://www.onnxruntime.ai/docs/reference/api/csharp-api.html).

**Comment by yuslepukhin** [comment]
Would this be helpful? https://github.com/microsoft/onnxruntime/blob/96989b83ee2da94e9eae78921d7ef0ee507e40ce/csharp/src/Microsoft.ML.OnnxRuntime/Tensors/DenseTensor.cs#L79

**Comment by feiyuhuahuo** [comment]
@yuslepukhin， hi，this can create a new tensor for the session input. But still, all the image pixels need to be passed to the tensor one by one element by using for ...loop. I am worrying about the speed. For a machine learning project, the time consumption of data preparing should be really  little.

**Comment by yuslepukhin** [comment]
This would enable you to create a buffer and then create a Tensor on top of the buffer, no copies made. The buffer will be pinned and passed directly to Onnxruntime.

**Comment by feiyuhuahuo** [comment]
Thanks, I know it. I am new to C#.
