### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by ivanov-wai** [microsoft/onnxruntime#8082]
**Describe the bug**
v1.7.2 tag has 1.8.0 version in it

**Urgency**
none

**System information**
n/a

**To Reproduce**
https://github.com/microsoft/onnxruntime/blob/v1.7.2/VERSION_NUMBER

**Expected behavior**
1.7.2 version in v1.7.2 tag

**Screenshots**
n/a

**Additional context**
Previously was fine, only changed recently

**Comment by snnn** [comment]
Thank you for reporting this to us.
