### ISSUE TITLE
How to choose which GPU device to use in a multi gpu system?

### ISSUE THREAD

**Issue by feckpown** [microsoft/onnxruntime#8103]
I installed onnxruntime-gpu with pip to run a model i exported to onnx. I run the model like this:

```
# Load onnx model
onnx_session = onnxruntime.InferenceSession(/path/to/model.onnx)

# Run Inference
prediction = onnx_session.run(None, {onnx_session.get_inputs()[0].name: input_image})
```

It runs, and produces the correct output. But how can i select which GPU to use in the session? I'm on a multi GPU machine, a 3060 for the displays and a 3090 for inference. I'd like to be able to set onnxruntime to use the 3090.

**Comment by hanbitmyths** [comment]
You can set device_id when you create InferenceSession as described [here](https://www.onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#python)
