### ISSUE TITLE
onnxruntime_providers_shared.so missing in wheel

### ISSUE THREAD

**Issue by amathews-amd** [microsoft/onnxruntime#8111]
**Describe the bug**
```
>>> import onnxruntime
2021-06-21 20:40:26.585183276 [E:onnxruntime:Default, provider_bridge_ort.cc:902 Ensure] Failed to load library libonnxruntime_providers_shared.so with error: libonnxruntime_providers_shared.so: cannot open shared object file: No such file or directory
2021-06-21 20:40:26.585217320 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:1615 pybind11_init_onnxruntime_pybind11_state] Init provider bridge failed.
```

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version: 
- Python version: 3.6.13
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: ROCm4.2
- GPU model and memory: MI100

**To Reproduce**
- Describe steps/code to reproduce the behavior.
```
RUN git clone --recursive https://github.com/microsoft/onnxruntime.git --branch v1.8.0 --single-branch \
  && cd onnxruntime \
  && python3 tools/ci_build/build.py \
    --cmake_extra_defines ONNXRUNTIME_VERSION=`cat ./VERSION_NUMBER` \
    --build_dir build \
    --config Release \
    --parallel \
    --skip_tests \
    --build_wheel \
    --use_rocm --rocm_home /opt/rocm \
    --mpi_home $OPENMPI_DIR \
    --nccl_home /opt/rocm \
    --enable_training \
  && test -f $ORT_DIR/build/Release/onnxruntime_training_bert \
  && pip install $ORT_DIR/build/Release/dist/*.whl \
  && ldconfig
```
Seems to be due to: 
https://github.com/microsoft/onnxruntime/blame/master/cmake/onnxruntime_python.cmake#L354
Unresolved conversation at PR : 
https://github.com/microsoft/onnxruntime/pull/7626/files#diff-6ab9762e5938268663204020db08929f339f87add8dfb1617177d6928861b63cR372

**Expected behavior**
import onnxruntime does not print messages about missing library

Removing https://github.com/microsoft/onnxruntime/blame/master/cmake/onnxruntime_python.cmake#L354
fixes issue.

**Comment by amathews-amd** [comment]
@RyanUnderhill

**Comment by znsoftm** [comment]
yes, It's also missed in the package  for windows and cuda.

**Comment by RyanUnderhill** [comment]
https://github.com/microsoft/onnxruntime/pull/8132 should fix this issue, as we shouldn't be trying to load the shared provider library with training (It's loaded automatically with shared providers, but this case was for a non training related feature).
