### ISSUE TITLE
With directML, it claims softmax xxxxx

### ISSUE THREAD

**Issue by znsoftm** [microsoft/onnxruntime#8118]
**Describe the bug**

021-06-22 19:49:46.1056447 [E:onnxruntime:, sequential_executor.cc:339 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Softmax node. Name:'Softmax@0' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(1736)\onnxruntime.dll!00007FFB881EFA73: (caller: 00007FFB881EF7E4) Exception(1) tid(1ec4) 80070057 The parameter is incorrect.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:  1.8 directML
- Python version:
- Visual Studio version (if applicable):  vs2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:  Nvidia 1070 8G

**To Reproduce**
session run , it occurred .
[mobile_ChEng_v2_rec.onnx.zip](https://github.com/microsoft/onnxruntime/files/6694015/mobile_ChEng_v2_rec.onnx.zip)
<img width="1909" alt="Capture" src="https://user-images.githubusercontent.com/15354249/122920624-2e47a580-d394-11eb-81e4-7491af396056.PNG">

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by znsoftm** [comment]
When it is running with CPU, everything is fine.

**Comment by hendrik-skubch** [comment]
Possibly related to https://github.com/microsoft/onnxruntime/issues/6075 (different operator, same error message)

**Comment by Coice** [comment]
I was able to resolve my issue, see: https://github.com/microsoft/onnxruntime/issues/6075#issuecomment-1185069606

**Comment by nums11** [comment]
Closing as resolved.
