### ISSUE TITLE
Unable to run inference on GPU 

### ISSUE THREAD

**Issue by mcicat** [microsoft/onnxruntime#8133]
**Describe the bug**
I successfully use .onnx model for inference via the C# API (CPU). When I try to create session options with cuda provider however it throws an exeption: 
{"[ErrorCode:RuntimeException] D:\\a\\_work\\1\\s\\include\\onnxruntime\\core/common/logging/logging.h:313 onnxruntime::logging::LoggingManager::DefaultLogger Attempt to use DefaultLogger but none has been registered.\n"}

When I run it for a second time (the same code) it throws a different exception: 
{"[ErrorCode:Fail] OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library"}

BTW (it may help) I successfully inferenced the model in Python using OnnxRuntime on GPU.

**System information**
- Windows 10 
- Nuget package ML.OnnxRuntime.GPU
- ONNX Runtime version: 1.8.0
- Python version: NA
- Visual Studio version (if applicable): VS 19 Professional
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: CUDA 11.0 (11.0.3 installer)/cuDNN 8.0 (8.0.2.39 installer)
- GPU model and memory: NVidia Quadro T2000

**To Reproduce**
```
try
{
  var options = new SessionOptions()
  {
    GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_EXTENDED,
  };
  options.AppendExecutionProvider_CUDA(0);

  //I also tried this command but it fails the same way
  //var options = SessionOptions.MakeSessionOptionWithCudaProvider(deviceId: 0);

  _session = new InferenceSession(model, options);
}
catch (OnnxRuntimeException ex)
{
  MyLogger.Error($"Initializing GPU with cuda infernce failed ({ex.Message}). Initializing CPU inference...");

  _session = new InferenceSession(model);
}
```

**Expected behavior**
Model is inferenced on GPU rather than CPU

**Comment by yuslepukhin** [comment]
You will want to instantiate OrtEnv instance before doing anything else, that should take care of logging. Just like most of others Ort C# Classes it is IDisposable, so don't forget to dispose of them (this includes Sessionoptions, InferenceSession and most of other things). 

Helpful examples can be found [here](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.Tests/InferenceTest.cs).

Cuda libraries need to be installed and be in the path so they could be found by the system loader.

**Comment by hariharans29** [comment]
I tried building a nuget using the master branch (using the `build_nuget` option along with regular build flags to build ORT with CUDA) and I couldn't repro this. We have had several minor fixes around missing dlls/bin placing dlls since 1.8.0. Maybe it will just be faster for you to try building from source and checking if this issue still persists for you (for me I was able to append the CUDA Provider to the SessionOptions instance). CC:@RyanUnderHill

**Comment by mcicat** [comment]
Cuda libraries are added to the path. I instantiated OrtEnv as advised and it did help with the logging error. The shared libraries error still occur. I'll try to build the onnx from source.

**Comment by mcicat** [comment]
I built the runtime from source (command: 
`.\build.bat --config Release --build_nuget --build_shared_lib --parallel --use_openmp --cuda_version 11.0 --skip_tests --cmake_generator "Visual Studio 16 2019" --use_cuda --cudnn_home “C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0” --cuda_home “C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0”` ), the problem persists ([ErrorCodeFail] OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library). I also tried different branches (master, v1.8.0, rel-1.8.1)..

**Comment by pranavsharma** [comment]
Are your cuda and cudnn deps in the PATH? We can figure it out using the following:

	1. "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\gflags.exe" -i <your executable name> +sls
	2. "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\windbg.exe" <your executable name>"
	3. When the debugger window opens, type 'g' and press Enter.
Search for the error in the screen.

**Comment by mcicat** [comment]
> Are your cuda and cudnn deps in the PATH? We can figure it out using the following:
> 
> ```
> 1. "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\gflags.exe" -i <your executable name> +sls
> 2. "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\windbg.exe" <your executable name>"
> 3. When the debugger window opens, type 'g' and press Enter.
> ```
> 
> Search for the error in the screen.

1. 
```
C:\Program Files (x86)\Windows Kits\10\Debuggers\x64>gflags.exe -i C:\Users\Michal.Cicatka\Work\Workspace\ColonyPicker\Test\bin\AnyCPU\Debug\Bruker.ColonyPicker.Test.exe +sls
Current Registry Settings for Bruker.ColonyPicker.Test.exe executable are: 00000000
```

(Failed to set registry value). 

2. windbg screenshot attached. 

I also attached screenshot of my environment variables. 
![windbg](https://user-images.githubusercontent.com/45569599/123393005-f744e000-d59d-11eb-9b4f-786262b20163.png)
![variables](https://user-images.githubusercontent.com/45569599/123393007-f7dd7680-d59d-11eb-82fb-9094d20e3dff.png)

**Comment by mcicat** [comment]
Finally I solved the issue by copying some dlls from the onnx nuget library... for some reason Nuget copied only some of the dlls. Sorry for the stupid mistake.

**Comment by rraszewski** [comment]
@mcicat Can you please provide the names of those dlls? I have the same issue as you.

**Comment by PiotrGizaB3D** [comment]
@rraszewski 

The missing dlls in my case were those two files:
onnxruntime_providers_shared.dll
onnxruntime_providers_cuda.dll

It seems that Nuget copied only onnxruntime.dll

@mcicat 
Thank you for help, the shared library error is now gone!

**Comment by mcicat** [comment]
> @rraszewski
> 
> The missing dlls in my case were those two files:
> onnxruntime_providers_shared.dll
> onnxruntime_providers_cuda.dll
> 
> It seems that Nuget copied only onnxruntime.dll
> 
> @mcicat
> Thank you for help, the shared library error is now gone!

Yes, those are the same dlls that were missing in my case as well. They can be found in the folder packages in your solution (e.g. C:\Users\User\YourSolutionFolder\packages\Microsoft.ML.OnnxRuntime.Gpu.1.8.0\runtimes\win-x64\native\*.dll)
