### ISSUE TITLE
Using IObinding with variable outputsize

### ISSUE THREAD

**Issue by AdamGreen424** [microsoft/onnxruntime#8144]
Hi, 

I'm am currently using onnxruntime (Python) io binding. However i have run into some trouble using a model where its output is not a constant size. The reason for using io bindings is due to me using a raw gpu memory pointer as input.
Here is a example (writen for demonstration purposes):
```
import onnxruntime as ort
import torch

session = ort.InferenceSession(model,...)
io_binding = session.io_binding()

embedding = torch.zeros(1 ,10 ,16 ,dtype=torch.float32, device=torch.device('cuda:0'))

io_binding.bind_input(
    name="input:0",
    device_type='cuda',
    device_id=0,
    element_type=np.float32
    shape = example.shape,
    buffer_ptr = example.ptr
)

io_binding.bind_output(
    name="output:0",
    device_type='cuda',
    device_id=0,
    element_type=np.float32
    shape = embedding.shape,
    buffer_ptr = embedding.ptr
)
```
In the above example i have set a torch tensor of a constant size, however the shape of the models output changes dependent on the input. This causes me to get an error when i try to run the model using iobindings as the shape of the output i have binded does not match the size of the output produced by the  model.  Is there anyway around this problem? I.e is there a way to use iobindings where the  output has a changing shape.

**Comment by yuslepukhin** [comment]
A suggested way around this is to bind it to a device instead of a specific piece of memory. This will cause ORT allocated memory on a specific device according the shape that is only known at runtime.

**Comment by pranavsharma** [comment]
See https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/python/onnxruntime_test_python_iobinding.py#L105. This binds the output to the cuda without requiring you to specify the shape.

**Comment by AdamGreen424** [comment]
Problem solved thankyou for your excellent answers

**Comment by arvindsouza** [comment]
I'm getting a memory access violation exception when attempting the below

I'm creating the memory info classes:
```

		MemoryInfo memory_info = Ort::MemoryInfo("Cuda", OrtArenaAllocator, 0, OrtMemTypeDefault);
		MemoryInfo memory_info_cpu = MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
```


I'm attempting to store the input/output tensors on the GPU like so

```
		inputTensors.push_back(Value::CreateTensor<float>(gpu_allocator.GetInfo(), reinterpret_cast<float*>(input_data), inputTensorValues.size(), inputDims.data(), inputDims.size()));

		AllocatedStringPtr inputName = mOrtSession.GetInputNameAllocated(0, ort_alloc);
		AllocatedStringPtr outputName = mOrtSession.GetOutputNameAllocated(0, ort_alloc);

		const std::array<const char*, 1> inputNames = { inputName.get() };
		const std::array<const char*, 1> outputNames = { outputName.get() };

		io_binding.BindInput(inputNames[0], inputTensors[0]);

		io_binding.BindOutput(outputNames[0], memory_info);
```

I'm able to run the session and get output tensor:

```
		mOrtSession.Run(runOptions, io_binding);

		auto output_tensors = io_binding.GetOutputValues();

```
However when trying to get the values like below:

`		std::vector<float> outputTensorValues(output_tensors[0].GetTensorMutableData<float>(), output_tensors[0].GetTensorMutableData<float>() + output_tensors[0].GetTensorTypeAndShapeInfo().GetElementCount());`

the application crashes with a memory access violation exception

When the output is stored on the CPU like below:

`		io_binding.BindOutput(outputNames[0], memory_info_cpu); 
`

the above code works fine

@pranavsharma could you help with this?
