### ISSUE TITLE
A dilemma for cuda

### ISSUE THREAD

**Issue by znsoftm** [microsoft/onnxruntime#8164]
Not a bug, not a new feature.
I met a dilemma:  wanna run my models with cuda, the package of ORT 1.8.0 is lack of necessary files ( about cuda) and the source code can not be compiled by the latest vs 2019.

Windows 10, vs2019, cuda 11.1

So when will you guys ship a new package with cuda support?
**System information**
- ONNX Runtime version (you are using):

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by znsoftm** [comment]
I just get a workaroud: get some necessary files from a nuget package:  https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/

**Comment by pranavsharma** [comment]
Fixed in ORT 1.8.1.
