### ISSUE TITLE
Prebuild binary for Linux arm64

### ISSUE THREAD

**Issue by andreselizondo-adestech** [microsoft/onnxruntime#8176]
**Is your feature request related to a problem? Please describe.**
I want to use ONNXRuntime on my node app. However, this app needs to be compatible with Linux on x64 and arm64.
This is an issue, since there's no prebuilt binary for arm64.
I would build my own binary, but it's unpractical for many reasons, one of them being electron-forge doesn't allow npm dependencies on local files.

**System information**
- ONNX Runtime version (you are using): "onnxruntime-node": "^1.8.0",

**Describe the solution you'd like**
I would like the ONNX releases to include a binary for Linux-arm64 like: `onnxruntime-linux-arm64-1.8.0.tgz`

**Describe alternatives you've considered**
The alternative would be for me to create my own npm bindings for ONNX Runtime with the same `prebuild-install` script as yours, but including the binary that I need from a repository of my own. This is not ideal, since I would have to manage my own builds/releases.

Another alternative would be to fallback to source compile if no binaries were found.
Here's an example of this behavior when installing another package.
```
> lzma-native@6.0.1 install /home/adestech/default-speaker/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-linux-arm64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for lzma-native@6.0.1 and node@12.14.1 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
```

**Additional context**

**Comment by yuzawa-san** [comment]
I would like to have prebuilt aarch64 support in general, but specifically in the java bindings https://github.com/microsoft/onnxruntime/issues/6026 I don't know how everything is packaged, but if it is easy to bundle the aarch64 into things it would be much appreciated.

**Comment by andreselizondo-adestech** [comment]
This is a gentle reminder on this issue.
Anyone knows how we can continue?

**Comment by yuzawa-san** [comment]
At a quick glance, I'm not sure how the release process works, but I'm guessing it involves copying the artifacts from a tagged CI run. I see that there is a matrix of supported environments in the windows CI file: https://github.com/microsoft/onnxruntime/blob/v1.8.2/tools/ci_build/github/azure-pipelines/win-ci-pipeline.yml#L11

so I would guess something similar would need to be done in the linux case. This may be task for the maintainers, since I don't know much about how all of the jobs are supposed to run or the release process.

**Comment by fs-eire** [comment]
`onnxruntime-node` v1.10.0 is released today with ARM64 support on Linux. Please give a try!

**Comment by yuzawa-san** [comment]
If the CI system is building it for node-js could this also be included in the github releases? Like in the assets section of https://github.com/microsoft/onnxruntime/releases/tag/v1.9.0

**Comment by fs-eire** [comment]
We do have those artifacts, but they are not included in the release assets. Instead, they are included in the NPM package tarball: https://registry.npmjs.org/onnxruntime-node/-/onnxruntime-node-1.10.0.tgz
( use `npm info onnxruntime-node` to get link to latest tarball )

you can find the artifacts in it.

**Comment by guschmue** [comment]
```
npm info onnxruntime-node

>.tarball: https://registry.npmjs.org/onnxruntime-node/-/onnxruntime-node-1.14.0.tgz
```

contains the arm64 binaries.
