### ISSUE TITLE
gpt2 greedy search or beam search (auto-regressive decoding) into one onnx graph?

### ISSUE THREAD

**Issue by gyin-ai** [microsoft/onnxruntime#8188]
Can the gpt example with greedy search or beam search auto-regressive decoding on multiple tokens be exported into one onnx graph? So that it can be directly used by onnxruntime triton backend (`libonnxruntime.so`).

**Comment by tianleiwu** [comment]
@gyin-ai, you might try 
https://github.com/microsoft/onnxruntime/pull/7425 and https://github.com/microsoft/onnxruntime-extensions/pull/114
