### ISSUE TITLE
Linker error "ld: 'libonnxruntime_mlas.a(QgemmU8X8KernelNeon.S.o)' does not contain bitcode." with onnxruntime_ENABLE_BITCODE=ON

### ISSUE THREAD

**Issue by fun2techlimbo** [microsoft/onnxruntime#8190]
**Describe the bug**
I use the Macbook Air M1 build the iOS platform library with the "onnxruntime_ENABLE_BITCODE=ON" cmake option,everything is good but got the link time error when linking onnxruntime.framework/onnxruntime.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 11.1 
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.8.0
- Python version: 3.8.2
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):Apple clang version 12.0.5 (clang-1205.0.22.9)
- CUDA/cuDNN version:None
- GPU model and memory:None

**To Reproduce**
I use the conan and darwin-toolchain/1.0.8@theodelrieu/stable as toolchain,which have the c++ flags -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk -mios-version-min=14.0 -fembed-bitcode -arch arm64

**Comment by gwang-msft** [comment]
Unfortunately, the libonnxruntime_mlas.a contains platform specific assembly code which does not have bitcode support, our current document need update. 
Please disable bitcode in your project.

**Comment by fun2techlimbo** [comment]
Got it,thanks.
