### ISSUE TITLE
Provide a context manager to silence PyTorch exporter warning

### ISSUE THREAD

**Issue by dashesy** [Microsoft/onnxruntime#822]
**Is your feature request related to a problem? Please describe.**
The exporter reports a very useful warning, like [this issue](https://github.com/Microsoft/onnxruntime/issues/679). Some times we know that the semantics are correct (for example a constant is a constant always) in which case would be nice to ignore the warning only for that statement. Another example is `assert` statements.
It is better to silence the warning selectively for statements, rather than wholesale, or learn to ignore them!

**System information**
- ONNX Runtime version (you are using): 0.3.0

**Describe the solution you'd like**
As a suggestion, something like this would be nice

```python
with tracer.ignore_warnings():
    assert x.shape[0] > 2, "checking"
```

**Describe alternatives you've considered**
No idea how to silence them

**Additional context**
I was trying to come up with a `CenterCrop` module [here](https://github.com/Microsoft/onnxruntime/issues/679).

This is the final working  solution that exports well, I have one class that can be used only for fixed input size but another than accepts dynamic shape input correctly too.

```python
@torch.jit.script
def center_slice_helper(x, h_offset, w_offset, h_end, w_end):
    return x[:, :, h_offset:h_end, w_offset:w_end]


class CenterCrop(nn.Module):
    def __init__(self, crop_size):
        """Crop from the center of a 4d tensor
        Input shape can be dynamic
        :param crop_size: the center crop size
        """
        super(CenterCrop, self).__init__()
        self.crop_size = crop_size

    def extra_repr(self):
        """Extra information
        """
        return 'crop_size={}'.format(
            self.crop_size
        )

    def forward(self, x):
        h_offset = (x.shape[2] - self.crop_size) / 2
        w_offset = (x.shape[3] - self.crop_size) / 2
        h_end = h_offset + self.crop_size
        w_end = w_offset + self.crop_size
        return center_slice_helper(x, h_offset, w_offset, h_end, w_end)


class CenterCropFixed(nn.Module):
    def __init__(self, crop_size):
        """Crop from the center of a 4d tensor
        Use this only if the input image size is always fixed
        :param crop_size: the center crop size
        """
        super(CenterCropFixed, self).__init__()
        self.crop_size = crop_size

    def extra_repr(self):
        """Extra information
        """
        return 'crop_size={}'.format(
            self.crop_size
        )

    def forward(self, x):
        h_offset = (x.shape[2] - self.crop_size) / 2
        w_offset = (x.shape[3] - self.crop_size) / 2
        return x[:, :, h_offset:h_offset + self.crop_size, w_offset:w_offset + self.crop_size]
```

I still do not know how best to put this assert statement:

```python
assert x.shape[3] > self.crop_size + 2 and x.shape[2] > self.crop_size + 2, \
            "height: {} or width: {} is less than crop_size: {}".format(x.shape[2], x.shape[3], self.crop_size)
```

without getting a tracer warning like

> TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not g eneralize to other inputs!
> return x[:, :, h_offset:h_offset + self.crop_size, w_offset:w_offset + self.crop_size]

And I do not want to ignore the warning, I just know that it is just an assert statement that will not change anything. Same can be said about the second class, I would like to export it with no warning because for this class I know will be used along with constant-sized inputs.

**Comment by androidsercan** [comment]
@dashesy  I applied your suggestion by writing center_slice_helper function. However, at this time, it gives this exception:

```
torch.jit.TracingCheckError: Tracing failed sanity checks!
Encountered an exception while running the Python function with test inputs.
Exception:
	center_slice_helper() expected value of type Tensor for argument 'diff_y' in position 1, but instead got value of type int.
	Value: 0
	Declaration: center_slice_helper(Tensor layer, Tensor diff_y, Tensor diff_x, Tensor h_end, Tensor w_end) -> Tensor
```
I debugged the code and observed that x parameter of forward function has this type:

![x_parameter](https://user-images.githubusercontent.com/6707092/56187389-14c7a800-602b-11e9-850e-39b7df395218.PNG)

How to handle this?

**Comment by dashesy** [comment]
@androidsercan I run this (python 2 just in case) only along with `torch.export`, that somehow assumes `torch.Size` is a tensor, and works.
I cannot run it with normal forward (remove the annotation for it). This is actually another issue I wish is fixed, so we can use the same model for prediction in PyTorch that is exported.

**Comment by androidsercan** [comment]
I removed the @torch.jit.script annotation. My helper function is

```
def center_slice_helper(layer, diff_y, diff_x, h_end, w_end):
    return layer[:, :, diff_y:h_end, diff_x:w_end]
```

Then, I obtained trace file and got this warning :

![Warning2](https://user-images.githubusercontent.com/6707092/56265438-3c357800-60f2-11e9-8f79-adea82ef6f65.PNG)

I tried this trace file in C++. I got different results compared to python outputs.

**Comment by androidsercan** [comment]
@dashesy I have read the related part in documentation: [https://pytorch.org/docs/stable/jit.html#mixing-tracing-and-scripting](https://pytorch.org/docs/stable/jit.html#mixing-tracing-and-scripting)

I understood that I should use My-Py style type annotation. What is your opininon?

**Comment by dashesy** [comment]
Removing the annotation `forward` works but you get that warning (which is actually valid).

The MyPy-style annotation may be the solution if perhaps we can declare `Union[Tensor, int]` . When tracing `x.size()` (or `x.shape` or `x.shape[1])` is a `Tensor` but when forwarding `x.size()` is `torch.Size`

Maybe something like this (not tried yet)

```python
@torch.jit.script
def center_slice_helper(x, h_offset, w_offset, h_end, w_end):
    # type: (Tensor, Union[Tensor, int], Union[Tensor, int], Union[Tensor, int], Union[Tensor, int]) -> Tensor
    return x[:, :, h_offset:h_end, w_offset:w_end]
```

**Comment by androidsercan** [comment]
ngn

**Comment by dashesy** [comment]
@beizhengren use [netron](https://github.com/lutzroeder/netron)
