### ISSUE TITLE
Crashed when running iOS app

### ISSUE THREAD

**Issue by HideOnBushTuT** [microsoft/onnxruntime#8266]
**Describe the bug**
I use `onnxruntime-mobile-c 1.8.0` in iOS App. It crashed when the app was running the model.
> Op with name (Pad_82) and type (Pad) kernel not found in CPUExecutionProvider. No matching hash for 17900876414644757728 

 The config `required_operators.config ` when i convert to ONNX model to ort format. 
```
ai.onnx;1;Conv,Transpose,Unsqueeze
ai.onnx;2;Pad
ai.onnx;4;Concat
ai.onnx;5;Reshape
ai.onnx;6;Clip,Log,Relu,Sigmoid
ai.onnx;7;Add,AveragePool,Div,GRU,Mul,Pow,Sub
ai.onnx;9;BatchNormalization,MatMul
com.microsoft;1;FusedConv
```

**System information**
- Mac OS 11.4
- Xcode Version: 12.5
- ONNX Runtime version: 1.8.0
-  python 3.7.6
- pytorch 1.9.0+cu102
- CUDA/cuDNN version: 10.2

**Screenshots**
![image](https://user-images.githubusercontent.com/16773862/124059180-38853600-da5d-11eb-9847-49a814c132c1.png)

**Additional context**
Train with PyTorch and then convert to the OnNX model using PyTorch's built-in interface:
```python
dummy_input = torch.randn(1, length, device='cpu')
model.eval()
torch.onnx.export(model, dummy_input, out_path, verbose=True, opset_version=9,
input_names=input_names, output_names=output_names)
```
Then use the script to convert to ORT format:
```
python tools/python/convert_onnx_models_to_ort.py onnx_models/
```

**Comment by gwang-msft** [comment]
This is probably caused by your model is converted from pytorch using `opset_version=9`
The onnxruntime-mobile prebuilt framework only supports ONNX opset 12 and 13, please see https://www.onnxruntime.ai/docs/reference/mobile/prebuilt-package/

You may either convert the model from pytorch using `opset_version=12 or 13` or custom build your own onnxruntime-mobile framework, please see https://www.onnxruntime.ai/docs/how-to/mobile/custom-build.html

**Comment by HideOnBushTuT** [comment]
Thank you so much ! Appreciate it !

**Comment by HideOnBushTuT** [comment]
onnxruntime 1.8.0 only supports opset 12 and 13, but opset 12 and 13 do not include GRU operation, my model requires GRU operation. And onnxruntime 1.6.0 is satifying my needs. so i try to compile onnxruntime 1.6.0  by myself, and generate libonnxruntime.1.6.0.dylib, But Apple does not support dynamic libraries, so I converted the library to .framework or .a static library myself, and an error was reported when I tried to use it. 

> Undefined symbols for architecture arm64: "_OrtGetApiBase", referenced from: .....

but i do not know how to solve it  ..... and You do not provide a 1.6.0 version of onnxruntime in Cocoapods. And do you have any plan to provide 1.6.0 version of onnxruntime ? Thanks

**Comment by gwang-msft** [comment]
The **prebuilt** onnxruntime 1.8.0 on CocoapPods only supports a list of operators and opset 12/13, however, you can custom build your own onnxruntime framework which will support all the operators in the `required_operators.config` which is generated when you converted ONNX model to ort format. Please see https://www.onnxruntime.ai/docs/how-to/mobile/custom-build.html

Also you can build the onnxruntime as a framework, you can use `--build_apple_framework` with your build command.

**Comment by HideOnBushTuT** [comment]
Finally .....  thanks for that, I really appreciate it.
