### ISSUE TITLE
Linux CUDA performance with the C++ API

### ISSUE THREAD

**Issue by radu-matei** [microsoft/onnxruntime#8268]
I am trying using the C++ API using the provided sample that runs the SqueezeNet model (https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/C_Api_Sample.cpp), and I am trying to evaulate the latency when using the CUDA provider.

I have already tried with two GPUs (a GTX 1060 and a P100) and two ONNX runtime versions with their supported CUDA versions (ONNX v1.6 with CUDA 10.2, and ONNX v1.8 with CUDA 11) on two different machines (Ubuntu 18.04 and 20.04) and in each case, the performance was significantly worse compared to the CPU provider.

Below are the results obtained with the GTX 1060, using `onnxruntime-linux-x64-gpu-1.8.0`, but they are in line with the observed results from the P100 as well:

```
➜ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0


➜ nvidia-smi dmon
# gpu   pwr gtemp mtemp    sm   mem   enc   dec  mclk  pclk
# Idx     W     C     C     %     %     %     %   MHz   MHz
    0     4    37     -     -     -     0     0   405     0
    0    23    38     -     -     -     0     0  3802     0
    0    23    39     -     -     -     0     0  3802  1415
    0    25    39     -     -     -     0     0  4006  1463
    0    25    40     -     -     -     0     0  4006  1562
    0    25    40     -     -     -     0     0  4006  1563
    0     5    40     -     -     -     0     0   405  1465

➜ time ./gpu_run
Running on the GPU:
Number of inputs = 1
Input 0 : name=data_0
Input 0 : type=1
Input 0 : num_dims=4
Input 0 : dim 0=1
Input 0 : dim 1=3
Input 0 : dim 2=224
Input 0 : dim 3=224
Score for class [0] =  0.000045
Score for class [1] =  0.003846
Score for class [2] =  0.000125
Score for class [3] =  0.001180
Score for class [4] =  0.001317
Done!
./gpu_run  1.37s user 0.85s system 66% cpu 3.356 total
```

The GPU appears to have been used during the execution (see power and clock readings for the GPU), and the right shared objects seem to have been linked for the binary:

```
➜ ldd gpu_run
        linux-vdso.so.1 (0x00007ffc7f191000)
        libonnxruntime.so.1.8.0 => /home/radu/onnx/onnxruntime-linux-x64-gpu-1.8.0/lib/libonnxruntime.so.1.8.0 (0x00007f2f39dd9000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2f39a50000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2f39838000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2f39447000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2f39243000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2f3903b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2f38e1c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2f38a7e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2f3adcf000)
```
Compare this with running the same inference, but using the CPU provider:

```
➜ time ./cpu_run
Running on the CPI:
Number of inputs = 1
Input 0 : name=data_0
Input 0 : type=1
Input 0 : num_dims=4
Input 0 : dim 0=1
Input 0 : dim 1=3
Input 0 : dim 2=224
Input 0 : dim 3=224
Score for class [0] =  0.000045
Score for class [1] =  0.003846
Score for class [2] =  0.000125
Score for class [3] =  0.001180
Score for class [4] =  0.001317
Done!
./cpu_run  0.11s user 0.02s system 293% cpu 0.043 total
```
Is there something I am doing wrong here? Is there a different sample / model / test I can run?

Thanks!

**Comment by pranavsharma** [comment]
The sample is feeding CPU inputs to Run. Since the session was created on CUDA, Run() will copy the CPU inputs to GPU and outputs from GPU to CPU and these cross device copies takes time. Better to use IOBinding. See https://github.com/microsoft/onnxruntime/blob/91075255a768814e0524db196ecc33b5c4e8fb2b/include/onnxruntime/core/session/onnxruntime_c_api.h#L1043.

**Comment by znsoftm** [comment]
Is there a piece of code to demo it?

**Comment by pranavsharma** [comment]
Here's a sample you can use that uses iobinding: https://gist.github.com/pranavsharma/243ce2f6a814c1545ccb9a3fdbe9d00b and here are the elapsed times from the run. Hope this helps!

(pranav_py8) pranav@XXXXX:~$ LD_LIBRARY_PATH=./onnxruntime-linux-x64-gpu-1.8.1/lib/ ./t-ort
Session Creation elapsed time in milliseconds: 6771 ms
BindInput elapsed time in microseconds: 129 us
Run elapsed time in milliseconds: 638 ms
Done!

**Comment by zyandtom** [comment]
> Here's a sample you can use that uses iobinding: https://gist.github.com/pranavsharma/243ce2f6a814c1545ccb9a3fdbe9d00b and here are the elapsed times from the run (using 1.8.1 release + Tesla V100-PCIE-16GB). Hope this helps!
> 
> (pranav_py8) pranav@XXXXX:~$ ./t-ort
> Session Creation elapsed time in milliseconds: 6241 ms
> BindInput elapsed time in microseconds: 125 us
> Warm up ... run elapsed time in milliseconds: 615 ms
> After warm up ... Run elapsed time in milliseconds: 2 ms
> Done!

@pranavsharma  Hi, do you have any cpu version example for c++ API, actually I'm new in onnx, and I tried to load my model in ubuntu c++ :)

**Comment by pranavsharma** [comment]
> > Here's a sample you can use that uses iobinding: https://gist.github.com/pranavsharma/243ce2f6a814c1545ccb9a3fdbe9d00b and here are the elapsed times from the run (using 1.8.1 release + Tesla V100-PCIE-16GB). Hope this helps!
> > (pranav_py8) pranav@XXXXX:~$ ./t-ort
> > Session Creation elapsed time in milliseconds: 6241 ms
> > BindInput elapsed time in microseconds: 125 us
> > Warm up ... run elapsed time in milliseconds: 615 ms
> > After warm up ... Run elapsed time in milliseconds: 2 ms
> > Done!
> 
> @pranavsharma Hi, do you have any cpu version example for c++ API, actually I'm new in onnx, and I tried to load my model in ubuntu c++ :)

Responded here https://github.com/microsoft/onnxruntime/issues/8526.
