### ISSUE TITLE
Can anyone give me an example of OrtIoBinding ?

### ISSUE THREAD

**Issue by znsoftm** [microsoft/onnxruntime#8296]
When we are using cuda , I guess if we use OrtIoBinding will improve the performance of onnxruntime.
So can anybody give me an example of OrtIoBinding in Cpp ?

**Comment by hariharans29** [comment]
https://github.com/microsoft/onnxruntime/blob/62d1458ea8effcf1d82590c0ea738c1ed488bb04/onnxruntime/test/shared_lib/test_inference.cc#L889

**Comment by hariharans29** [comment]
Please re-open if you have more questions
