### ISSUE TITLE
How to build a static link?

### ISSUE THREAD

**Issue by Casablancaaa** [Microsoft/onnxruntime#830]
I needed an onnxruntime static library, so I compiled with version 0.3.1 from source and opened -- --enable_msvc_static_runtime, but I didn't get just one static library.

**Comment by snnn** [comment]
It consists a bunch of static libraries, like onnxruntime_common,onnxruntime_framework,onnxruntime_session. It's not just one single static lib.
Also, it is a lot of dependencies, like protobuf. If you do static link, you must use the protobuf lib under onnxruntime's build dir, not the system dir. 

Therefore, static link is much more complex that dynamic link.

**Comment by Casablancaaa** [comment]
I got it. thanks
