### ISSUE TITLE
Errors when loading FP16 model with resize ops

### ISSUE THREAD

**Issue by mathmax12** [microsoft/onnxruntime#8327]
**Describe the bug**
 FP16 model is converted from FP32 
when loading the FP16 model got the following issue:

` File "tmodels_FP16_test.py", line 268, in test
    onnx_model = rt.InferenceSession(onnx_model_path)
  File "C:\Users\bigtree\.conda\envs\se_demo\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 283, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\bigtree\.conda\envs\se_demo\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 310, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from model_fp16.onnx failed:This is an invalid model. Type Error: Type 'tensor(float16)' of input parameter (1105) of operator (Resize) in node (Resize_288) is invalid.`

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.8.0
- Python version: 3.7.10
 
I check the onnx model file the Resize_288 looks like;
![image](https://user-images.githubusercontent.com/32367611/124847168-2882c000-df4f-11eb-83cc-2afbcf9352a6.png)

Any suggestion about this issue is appreciated?
Thanks

**Comment by kit1980** [comment]
According to the spec https://github.com/onnx/onnx/blob/master/docs/Operators.md#Resize, the `scales` parameter must be `tensor(float)` - 32 bit.

So it looks like the ONNX model is invalid - the `scales` parameter must be kept in float32 during the conversion to float16.

**Comment by SiChuanJay** [comment]
@mathmax12 Have you solved the problem yet? Can you share the code. Thank you very much!
