### ISSUE TITLE
How Can I install onnxruntime==1.8.1 directly

### ISSUE THREAD

**Issue by NCEPUYTL** [microsoft/onnxruntime#8329]
pip install onnxruntime==1.8.1，but now the latest is 1.8.0, thks

**Comment by NCEPUYTL** [comment]
sorry，in linux

**Comment by kit1980** [comment]
The 1.8.1 release just happened, you may need to wait until it propagates through caches.

**Comment by pranavsharma** [comment]
Works for me.

(pranav_py8) pranav@XXXXX:~$ pip install onnxruntime==1.8.1
Collecting onnxruntime==1.8.1
  Downloading onnxruntime-1.8.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
     |████████████████████████████████| 4.5 MB 15.6 MB/s
Requirement already satisfied: numpy>=1.16.6 in /data/anaconda/envs/pranav_py8/lib/python3.8/site-packages (from onnxruntime==1.8.1) (1.20.3)
Requirement already satisfied: flatbuffers in /data/anaconda/envs/pranav_py8/lib/python3.8/site-packages (from onnxruntime==1.8.1) (2.0)
Requirement already satisfied: protobuf in /data/anaconda/envs/pranav_py8/lib/python3.8/site-packages (from onnxruntime==1.8.1) (3.17.3)
Requirement already satisfied: six>=1.9 in /data/anaconda/envs/pranav_py8/lib/python3.8/site-packages (from protobuf->onnxruntime==1.8.1) (1.16.0)
Installing collected packages: onnxruntime
Successfully installed onnxruntime-1.8.1

**Comment by NCEPUYTL** [comment]
okay,works for me now,thanks @kit1980 @pranavsharma
