### ISSUE TITLE
Migration from vesion 1.6.0 to 1.8.1

### ISSUE THREAD

**Issue by ogoun** [microsoft/onnxruntime#8332]
**Describe the bug**
Last stable working version - 1.6.0, any higher version fault with error.
On 1.8.1 i've got error:
[ErrorCode:RuntimeException] D:\a\_work\1\s\include\onnxruntime\core/common/logging/logging.h:313 onnxruntime::logging::LoggingManager::DefaultLogger Attempt to use DefaultLogger but none has been registered.

**System information**
- Windows 10 Pro X64, Windows 7 X64
- ONNX Runtime installed from nuget
- ONNX Runtime version: 1.8.1
- Visual Studio version (if applicable): 2019
- CUDA/cuDNN version: 10.2 / 11
- GPU model and memory: NVIDIA 1080 Ti

**To Reproduce**
.NET 4.8 x64 build
```
var so = SessionOptions.MakeSessionOptionWithCudaProvider(0);
so.GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_ALL;
_session = new InferenceSession(modelPath, so);
```

**Comment by ogoun** [comment]
I tried write as in samples:

```
SessionOptions options = new SessionOptions();
options.GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_EXTENDED;
_session = new InferenceSession(modelPath, options);
```

It works, but the speed of work has dropped 100 times compared to version 1.6.0

**Comment by tianleiwu** [comment]
If the exception happens during MakeSessionOptionWithCudaProvider(), that means there is problem to initialize cuda provider. Maybe some dependent DLLs are missing.

Could you check that onnxruntime_providers_cuda.dll and onnxruntime_providers_shared.dll are in the same folder of your program exe?

**Comment by pranavsharma** [comment]
Works fine for me. Here's a [sample program](https://gist.github.com/pranavsharma/939d93fc7291c5a1638bfa3b190d72e3) I created by importing the latest nuget GPU pkg (1.8.1) inside a Visual Studio C# console app. Here's the output.

![image](https://user-images.githubusercontent.com/2732907/125149159-26a23380-e0ec-11eb-997c-d686823c0f2c.png)
