### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running ReduceMin node. Name:'Transformer-0-MultiHeadSelfAttention-Add/All2_reduce' Status Message:

### ISSUE THREAD

**Issue by tianjialai** [microsoft/onnxruntime#8342]
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running ReduceMin node. Name:'Transformer-0-MultiHeadSelfAttention-Add/All2_reduce' Status Message:

from onnxruntime.transformers import optimizer
optimized_model = optimizer.optimize_model("gpt2.onnx", model_type='gpt2', num_heads=12, hidden_size=768)
optimized_model.convert_model_float32_to_float16()
optimized_model.save_model_to_file("gpt2_fp16.onnx")

When I used f16 to optimize bert, this problem occurred

**Comment by tianjialai** [comment]
onnxruntime-gpu=1.1.2 
cuda 10.1

**Comment by kit1980** [comment]
"onnxruntime-gpu 1.1.2" is very old, the current release is 1.8.1
Can you update?
