### ISSUE TITLE
onnxruntime-gpu 1.2.0

### ISSUE THREAD

**Issue by tianjialai** [microsoft/onnxruntime#8344]
return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running MatMul node. Name:'Transformer-0-MultiHeadSelfAttention/dense_3/MatMul_add' Status Message: CUBLAS error executing cublasGemmHelper( Base::CublasHandle(), transB, transA, static_cast<int>(helper.N()), static_cast<int>(helper.M()), static_cast<int>(helper.K()), &one, reinterpret_cast<const CudaT*>(right_X->template Data<T>()), ldb, reinterpret_cast<const CudaT*>(left_X->template Data<T>()), lda, &zero, reinterpret_cast<CudaT*>(Y->template MutableData<T>()), ldc, device_prop)

When I used f16 to optimize bert, this problem occurred. I changed the hidden layer name of the bert model

**Comment by kit1980** [comment]
"onnxruntime-gpu 1.2.0" is very old, the current release is 1.8.1
Can you update?

**Comment by tianleiwu** [comment]
@tianjialai, The error means Cublas GEMM returns error code. List of possible errors (like out of GPU memory, or fp16 is not supported in your GPU): https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t.

One way is to debug OnnxRuntime code (You need build a debug version of ORT 1.2), and set a break point in https://github.com/microsoft/onnxruntime/blob/rel-1.2.0/onnxruntime/core/providers/cuda/math/matmul.cc

**Comment by faxu** [comment]
Closing this issue. Please reopen if further assistance is needed.
