### ISSUE TITLE
OnnxRuntime Error : sequential_executor.cc:318 Execute] Non-zero status code returned while running Transpose node. && GPU Usage Issue

### ISSUE THREAD

**Issue by JunHyunjae** [microsoft/onnxruntime#8352]
**Error Message **
2021-07-09 02:08:35.365931341 [E:onnxruntime:, sequential_executor.cc:318 Execute] Non-zero status code returned while running Transpose node. Name:'StatefulPartitionedCall/EfficientDet-D0/bifpn/node_05/1_dn_lvl_3/input_0_up_lvl_3/1x1_pre_sample/batchnorm/FusedBatchNormV3__1010' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument
Traceback (most recent call last):
File "tfmodelTest.py", line 13, in
results_ort = sess.run(["num_detections", "detection_boxes", "detection_classes","detection_scores"], {"input_tensor": input1})
File "/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py", line 123, in run
return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Transpose node. Name:'StatefulPartitionedCall/EfficientDet-D0/bifpn/node_05/1_dn_lvl_3/input_0_up_lvl_3/1x1_pre_sample/batchnorm/FusedBatchNormV3__1010' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument

1. Used model : https://tfhub.dev/tensorflow/efficientdet/d0/1

2. Used Command : python -m tf2onnx.convert --saved-model ./ --output model.onnx

3. Environment
Cython 0.29.23
numpy 1.19.1
onnx 1.7.0
onnxruntime-gpu 1.5.2
pycuda 2019.1.2
tensorflow-gpu 2.2.0
tf2onnx 1.10.0
torch 1.7.1
torch2trt 0.2.0

4. Test Code
import onnxruntime as ort

model_path = efficientdet_d0_v12.onnx
input1 = np.ones((1, 512, 512, 3), np.uint8)

#sess = ort.InferenceSession(model_path, providers=["TensorrtExecutionProvider"])
#sess = ort.InferenceSession(model_path, providers=["CPUExecutionProvider"])
sess = ort.InferenceSession(model_path, providers=["CUDAExecutionProvider"])

results_ort = sess.run(["num_detections", "detection_boxes", "detection_classes","detection_scores"], {"input_tensor": input1})

1. sess = ort.InferenceSession(model_path, providers=["TensorrtExecutionProvider"])
2. #sess = ort.InferenceSession(model_path, providers=["CPUExecutionProvider"])
Neither of the above causes an error, but it seems that the GPU is not used at all.
I monitored it with nvidia-smi, but the GPU usage is not increasing at all.

3. sess = ort.InferenceSession(model_path, providers=["CUDAExecutionProvider"])
"CUDAExecutionProvider" increases GPU usage, but results in the error mentioned at the beginning.

I did only the basics, but an error occurred and I can't figure it out.
Attached is the onnx file.

Any help would be appreciated.
[efficientdet_d0_v12.zip](https://github.com/microsoft/onnxruntime/files/6797945/efficientdet_d0_v12.zip)

**Comment by hariharans29** [comment]
Thanks for reporting. 

This was already reported (https://github.com/microsoft/onnxruntime/issues/7316) and a bug fix was shipped in 1.8.

**Comment by TomWildenhain-Microsoft** [comment]
Thanks @hariharans29, sorry should have probably suggested updating ORT first.

**Comment by JunHyunjae** [comment]
@hariharans29, @TomWildenhain-Microsoft

I tested it in onnx==1.8.0 and onnxruntime-gpu==1.8.0, CUDA 11.0, cudnn 8.0.4

CUDAExecutionProvider works without errors but it works much slower than the CPU.

I monitored with nvidia-smi and confirmed that GPU usage increases when using CUDAExecutionProvider.

**CPU Test result**
model time :  0.28381776809692383
model time :  0.3062574863433838
model time :  0.2735309600830078
model time :  0.28269457817077637
model time :  0.2689650058746338
model time :  0.3018655776977539
model time :  0.300079345703125
model time :  0.2846550941467285
model time :  0.2832300662994385
model time :  0.27881503105163574
model time :  0.28023219108581543
model time :  0.27510547637939453
model time :  0.27993083000183105
model time :  0.2918741703033447
model time :  0.34146547317504883
model time :  0.31770992279052734
model time :  0.2876732349395752
model time :  0.2907249927520752
model time :  0.2843780517578125
model time :  0.27753663063049316

**GPU Test result**
model time :  2.9515023231506348
model time :  1.0645315647125244
model time :  1.0450475215911865
model time :  1.045647382736206
model time :  1.0443611145019531
model time :  1.0493566989898682
model time :  1.0513498783111572
model time :  1.0506653785705566
model time :  1.0507018566131592
model time :  1.052443027496338
model time :  1.0558373928070068
model time :  1.049104928970337
model time :  1.0525670051574707
model time :  1.0538661479949951
model time :  1.0582499504089355
model time :  1.0533485412597656
model time :  1.0548732280731201
model time :  1.0565853118896484
model time :  1.0623681545257568
model time :  1.058274269104004

**Comment by zll0000** [comment]
I run  a model with precision float16, some test samples can get rigth result, but some are error as follows
_**self._sess.run_with_iobinding(iobinding._iobinding, run_options)
RuntimeError: Error in execution: Non-zero status code returned while running Transpose node. Name:'Transpose_286' Status Message: CUDA error cudaErrorInvalidConfiguration:invalid configuration argument**_
all the test samples can output right result by the model with precision float32
@hariharans29
