### ISSUE TITLE
No way to install an old version 1.6.0 by pip install onnxruntime==1.6.0 [StressRNN related issue]

### ISSUE THREAD

**Issue by Uzer1** [microsoft/onnxruntime#8365]
Hello. 
I need the old version of **onnxruntime** to run **StressRNN**. **1.6.0** is the latest version accepted by it. 
I tried using the command: 

`pip install onnxruntime==1.6.0`

```
C:\Users\PC>pip install onnxruntime==1.6.0
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.6.
0 (from versions: 1.7.0, 1.8.0, 1.8.1)
ERROR: No matching distribution found for onnxruntime==1.6.0
```
How can one install this old version?

**Comment by snnn** [comment]
What's your pip version and python version?
onnxruntime 1.6.0 supports python 3.5/3.6/3.7/3.8 but it doesn't support 3.9.

**Comment by snnn** [comment]
I tried it in Ubuntu 20.04, it works well.

**Comment by Uzer1** [comment]
> What's your pip version and python version?
> onnxruntime 1.6.0 supports python 3.5/3.6/3.7/3.8 but it doesn't support 3.9.

I used 3.9 when trying this. Indeed, I had to downgrade to 3.8 to install onnxruntime ver. 1.6.0. I write down the method below.

**Comment by Uzer1** [comment]
https://pypi.org/project/onnxruntime/1.6.0/#files
I could install onnxruntime ver. 1.6.0 from a wheel file from this link. 

`onnxruntime-1.6.0-cp38-cp38-win_amd64.whl (4.2 MB)`

This one. 

`Pip install py -m pip install "C:\Users\PC\Desktop\onnxruntime-1.6.0-cp38-cp38-win_amd64.whl"`

It works with Python 3.8 only, it's in the title — CP38. 

I am generating the Silero voice now with it, so it worked. Other modules also were hard to install, however.

**Comment by snnn** [comment]
The author of https://github.com/Desklop/StressRNN said ONNX Runtime 1.7 has a "Segmentation fault (core dumped)" error. Do you know how to reproduce it? We'd love to fix it, so that you can use the latest version.

**Comment by Uzer1** [comment]
I do not know how to reproduce it.

**Comment by snnn** [comment]
Anything else I can help?

**Comment by Uzer1** [comment]
This issue is solved. The version problem is clear now. It must be closed now. Thanks.
