### ISSUE TITLE
FileNotFoundError: Unable to find requirements.txt

### ISSUE THREAD

**Issue by thegwangster** [microsoft/onnxruntime#8370]
**Describe the bug**
When running "pip install git+https://github.com/microsoft/onnxruntime.git", I am given the following error:
FileNotFoundError: Unable to find requirements.txt

**Urgency**
Moderate

**System information**
- WSL: Ubuntu 20.04
- ONNX Runtime version: 1.8.1
- Python version: I have tried this on Python versions 3.7.9 and 3.8.6

**To Reproduce**
- Just run "pip install git+https://github.com/microsoft/onnxruntime.git" in a virtualenv

**Expected behavior**
Python package onnxruntime is installed in the virtual environment.

**Screenshots**
This screenshot is from Pycharm, but the same error message appears when I try on an Ubuntu terminal.
![image](https://user-images.githubusercontent.com/45379073/125483886-a231f7d6-5f7c-4bb9-b2b4-8b766b099039.png)

**Comment by thegwangster** [comment]
The setup.py file looks for a file named "requirements.txt", but that doesn't exist in the repo. There is one called requirements.txt.in though, should I just fork the repo and rename it or something?

**Comment by snnn** [comment]
Sorry it is not supported. If you can make it work, welcome to contribute. 

To build onnxruntime from source, please follow https://www.onnxruntime.ai/docs/how-to/build/inferencing.html#cpu
