### ISSUE TITLE
Ort::Exception of  CUDA failure 3: initialization error 

### ISSUE THREAD

**Issue by yank666** [microsoft/onnxruntime#8381]
**Describe the bug**
I got  release binary of onnxruntime-linux-x64-gpu-1.8.1.tgz  from github,  and run with c++ API , it throwing an  'Ort::Exception'

`what(): /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:115 bool onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*) [with ERRTYPE = cudaError; bool THRW = true] CUDA failure 3: initialization error ; GPU=140341504 ; hostname=TeslaP100 ; expr=cudaSetDevice(info_.device_id); `

this is API if i called： 
![image](https://user-images.githubusercontent.com/79586188/125574657-f9571483-192d-463b-bbbf-3808ba96f1b0.png)

I set my target link with libonnxruntime_providers_cuda.so and  libonnxruntime_providers_shared.so , libonnxruntime.so

**Urgency**
please help me quickly, i need resolve this problem before 07/20 ,

**System information**
- OS Platform :  Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary):  get release binary of onnxruntime-linux-x64-gpu-1.8.1.tgz  from github
- ONNX Runtime version:  onnxrumie 1.8.1 with gpu EP
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by snnn** [comment]
You should link to libonnxruntime.so, not libonnxruntime_providers_cuda.so and libonnxruntime_providers_shared.so

**Comment by yank666** [comment]
what's relationship between onnxruntime.so and libonnxruntime_providers_cuda.so 、 libonnxruntime_providers_shared.so，i exec ldd and don't find the libonnxruntime.so link ohers.  if  I want run onnxruntime on GPU， the target need not link  libonnxruntime_providers_cuda.so and libonnxruntime_providers_shared.so?

**Comment by yuslepukhin** [comment]
You should also check that your NVIDIA driver meets minimum requirements for your CUDA version.

**Comment by yank666** [comment]
thanks you guys, it is may be my environment problem, I change to the another  server with GPU ,it's ok,thx
