### ISSUE TITLE
Tune performance For CUDAExecutionProvider

### ISSUE THREAD

**Issue by Sriharan-Manogaran** [microsoft/onnxruntime#8383]
As the performance tuning and its variables are explained well and clearly for CPU and nGraph in the [Tune performance](https://www.onnxruntime.ai/docs/how-to/tune-performance.html#tuning-performance) documentation. Similarly, can you help me to find out what are the performance tuning options that exist for CUDA EP other than [CUDA EP's Configuration Options](https://www.onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#configuration-options).

Thanks in advance!

---
#### Document Details
* Title: Tune performance
* Page: [https://www.onnxruntime.ai/docs/how-to/tune-performance.html](https://www.onnxruntime.ai/docs/how-to/tune-performance.html)
* Page Source: tune-performance.md

**Comment by Sriharan-Manogaran** [comment]
Hey, any reply here would be appreciated.

**Comment by pranavsharma** [comment]
Look for OrtCUDAProviderOptions in https://github.com/microsoft/onnxruntime/blob/master/include/onnxruntime/core/session/onnxruntime_c_api.h. Those are the only options we've currently to tune the CUDA provider.

**Comment by Sriharan-Manogaran** [comment]
Thanks for your reply
