### ISSUE TITLE
error "NEON intrinsics not available with the soft-float ABI" when building onnxruntime for arm

### ISSUE THREAD

**Issue by drux007** [microsoft/onnxruntime#8384]
**Describe the bug**
When I try to build onnxruntime for arm using `arm-linux-gnueabi-gcc-7` toolchain, **build fails**.

**Urgency**
We use onnxruntime for deploying our models on various different platforms and also we need to add ARM platform as soon as possible.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.8.0
- Python version: 3.6.9
- GCC/Compiler version (if compiling from source):7.5.0

I tried to build it using docker image conanio/gcc7-armv7:
- OS Platform: Linux
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.8.0
- GCC/Compiler version (if compiling from source):7.2.0

**To Reproduce**
The easiest is to simply run it inside the following docker container:
```
docker run -it conanio/gcc7-armv7 /bin/bash
```
Download the source code:
```
git clone --single-branch --branch v1.8.0 --recursive https://github.com/Microsoft/onnxruntime
```
And build it with:
```
cd onnxrutnime
cmake ./cmake
make
```

**Expected behavior**
Expected would be that it builds successfully, but it fails with the following error:
```
error: #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softp or -mfloat-abi=hard"
 #error "NEON intrinsics not available with the soft-float ABI.  Please use -mfloat-abi=softp or -mfloat-abi=hard"
 ```

**Comment by yufenglee** [comment]
Can you switch to arm-linux-gnueabihf-gcc or add the compiling option -mfloat-abi=hard?

**Comment by drux007** [comment]
> Can you switch to arm-linux-gnueabihf-gcc or add the compiling option -mfloat-abi=hard?

Thanks @yufenglee for the quick answer.

I already already tried adding compiling option `-mfloat-abi=hard` as suggested in the error message, but that didn't help.

Actually I tried setting all 3 possible options (from [here](https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html)):
* hard
* soft
* softfp

but the outcome is the same.

I also tried to use a different compiling option name `--with-float` instead of `mfloat-abi`, but that didn't help either.

**Comment by drux007** [comment]
Switching to `arm-linux-gnueabihf-gcc` solved this issue.

I tried out by passing the arguments to build.sh script with `--cmake_extra_defines="CMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabihf-gcc-7" --cmake_extra_defines="CMAKE_CXX_COMPILER=/usr/bin/arm-linux-gnueabihf-g++-7"` and also directly passing to cmake with `-DCMAKE_CXX_COMPILER=/usr/bin/arm-linux-gnueabihf-g++-7 -DCMAKE_C_COMPILER=/usr/bin/arm-linux-gnueabihf-gcc-7`.

Thanks @yufenglee for your help.

**Comment by drux007** [comment]
> Can you switch to arm-linux-gnueabihf-gcc or add the compiling option -mfloat-abi=hard?

Closing issue since this solved it.
