### ISSUE TITLE
C# API come out warning when using OpenVino execution provider 

### ISSUE THREAD

**Issue by mrljwlm** [microsoft/onnxruntime#8403]
I build the c# nupkg with openvino_2021.3.394 using this command:
.\build.bat --config RelWithDebInfo --use_openvino CPU_FP32 --build_shared_lib --build_nuget --parallel --cmake_generator "Visual Studio 16 2019"

then i got these two nupkg in nuget-artifacts:
Microsoft.ML.OnnxRuntime.Managed.1.8.0-dev-20210714-0226-b7c9696ac.nupkg
Microsoft.ML.OnnxRuntime.OpenVino.1.8.0-dev-20210714-0226-b7c9696ac.nupkg

after i install above nupkg in visual studio,i run the following code:

```
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.OnnxRuntime;
using Microsoft.ML.OnnxRuntime.Tensors;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("start testing onnxruntime");
            InferenceSession session;
            string filename = "model.onnx";
            Console.WriteLine(filename);
            SessionOptions options = new SessionOptions();
            options.GraphOptimizationLevel = GraphOptimizationLevel.ORT_ENABLE_ALL;
            options.AppendExecutionProvider_OpenVINO("CPU_FP32");
            session = new InferenceSession(filename, options); // the warning come out in this line
        }
    }
}
```

the following warning will occur:

[WARN] 2021-07-15T23:56:01z frontend\onnx_import\src\core\graph.cpp 118
Could not create an nGraph Constant for initializer '294'.
Constant with a 0 value was created, make sure connected input is optional.
Otherwise verify if the initializer contains a correct number of elements matching the initializer's shape.
Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@2\b\repos\openvino\ngraph\core\include\ngraph/op/constant.hpp:72:
While validating node 'v0::Constant Constant_104 () -> (f32{})' with friendly_name 'Constant_104':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

[WARN] 2021-07-15T23:56:01z frontend\onnx_import\src\core\graph.cpp 118
Could not create an nGraph Constant for initializer '319'.
Constant with a 0 value was created, make sure connected input is optional.
Otherwise verify if the initializer contains a correct number of elements matching the initializer's shape.
Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@2\b\repos\openvino\ngraph\core\include\ngraph/op/constant.hpp:72:
While validating node 'v0::Constant Constant_119 () -> (f32{})' with friendly_name 'Constant_119':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

[WARN] 2021-07-15T23:56:01z frontend\onnx_import\src\core\graph.cpp 118
Could not create an nGraph Constant for initializer '294'.
Constant with a 0 value was created, make sure connected input is optional.
Otherwise verify if the initializer contains a correct number of elements matching the initializer's shape.
Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@2\b\repos\openvino\ngraph\core\include\ngraph/op/constant.hpp:72:
While validating node 'v0::Constant Constant_1243 () -> (f32{})' with friendly_name 'Constant_1243':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

[WARN] 2021-07-15T23:56:01z frontend\onnx_import\src\core\graph.cpp 118
Could not create an nGraph Constant for initializer '319'.
Constant with a 0 value was created, make sure connected input is optional.
Otherwise verify if the initializer contains a correct number of elements matching the initializer's shape.
Detailed error:
Check 'values.size() == 1 || values.size() == shape_size(m_shape)' failed at C:\j\workspace\private-ci\ie\build-windows-vs2019@2\b\repos\openvino\ngraph\core\include\ngraph/op/constant.hpp:72:
While validating node 'v0::Constant Constant_1258 () -> (f32{})' with friendly_name 'Constant_1258':
Did not get the expected number of literals for a constant of shape Shape{} (got 0, expected 1).

**_these warning is normal? or abnormal? will it affect the usage?_**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04) win10:
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version:
- Python version: 3.8.6
- Visual Studio version (if applicable): 2019

**Comment by jywu-msft** [comment]
What is the model.onnx you are trying to load?
+@MaajidKhan for advice.

**Comment by mrljwlm** [comment]
I use the model exported from [yolov5s](https://raw.githubusercontent.com/mrljwlm/hellow-world/master/yolov5s.rar)

**Comment by mrljwlm** [comment]
> What is the model.onnx you are trying to load?
> +@MaajidKhan for advice.

 I use the model exported from [yolov5s](https://raw.githubusercontent.com/mrljwlm/hellow-world/master/yolov5s.rar)

**Comment by MaajidKhan** [comment]
@mrljwlm The warnings that you see are coming from the initial onnx importer stage. Meaning, when the onnx model is imported, we kind of convert the network to a ngraph function and process it further.

The last step is the inferencing  stage where the model is ran for inferencing. This is where your performance numbers get captured/evaluated. so overall, these warnings won't have any impact on your inference timings or the performance as they only show up during the initial stage and not during actual inference.

However, I would bring this up with our OpenVINO engineering team to see how we can suppress these warnings or eliminate them in our future releases.

**Comment by mrljwlm** [comment]
> @mrljwlm The warnings that you see are coming from the initial onnx importer stage. Meaning, when the onnx model is imported, we kind of convert the network to a ngraph function and process it further.
> 
> The last step is the inferencing stage where the model is ran for inferencing. This is where your performance numbers get captured/evaluated. so overall, these warnings won't have any impact on your inference timings or the performance as they only show up during the initial stage and not during actual inference.
> 
> However, I would bring this up with our OpenVINO engineering team to see how we can suppress these warnings or eliminate them in our future releases.

thank you for your advice.
