### ISSUE TITLE
What does libonnxrimtime_provides_cuda.so and onnxrimtime_provides_shared.so do? Is it abandoned  libonnxrimtime.so in --use_cuda compile?

### ISSUE THREAD

**Issue by yank666** [microsoft/onnxruntime#8412]
I Can't find the libonnxrimtime.so in directory of my /build/Linux/Debug/  ,that i use --use_cuda compile source code in release /v1.8.1
![image](https://user-images.githubusercontent.com/79586188/125928707-7a830fec-2908-4e15-8f85-5ae8f065a1d4.png)

**Comment by hariharans29** [comment]
Did you use `--build_shared_lib` ?

**Comment by jywu-msft** [comment]
as mentioned, you need to use the --build_shared_lib build option to build libonnxruntime.so
the other .so files you mentioned are related to execution providers (e.g. cuda execution provider is always built as a shared library and loaded at runtime when a session is created with cuda provider enabled)

**Comment by yank666** [comment]
> as mentioned, you need to use the --build_shared_lib build option to build libonnxruntime.so
> the other .so files you mentioned are related to execution providers (e.g. cuda execution provider is always built as a shared library and loaded at runtime when a session is created with cuda provider enabled)

I will try  --build_shared_lib, thx.  And as your explain， the libonnxrimtime_provides_cuda.so should be target_link_library with my target execution, is that right?

**Comment by yuslepukhin** [comment]
You don't want to measure perf on Debug builds.

**Comment by yank666** [comment]
> You don't want to measure perf on Debug builds.

I build with --config Release , build  exec target alse with CMAKE_BUILD_TYPE=release，The time taken is as follows:
![image](https://user-images.githubusercontent.com/79586188/126284278-d7281ca3-2e50-4c9d-a786-ddcd4285cc71.png)

i think it should  take about 10 ms run finsih squeezenet inference which model is so small.

**Comment by yank666** [comment]
I figure out , that must have warm up before mesure perf of cuda provider
