### ISSUE TITLE
Cross Compile Error: This file was generated by an older version of protoc which is incompatible with your Protocol Buffer headers.

### ISSUE THREAD

**Issue by coltonpeltierSE** [microsoft/onnxruntime#8413]
**Describe the bug**
I'm following the cross compile on linux instructions available [here](https://www.onnxruntime.ai/docs/how-to/build/inferencing.html#cross-compiling-on-linux). When I attempt to do the build I get the error message:

`This file was generated by an older version of protoc which is incompatible with your Protocol Buffer headers. Please regenerate this file with a newer version of protoc.`

I'm surprised by the message since I've followed the instructions on the tutorial for retrieving the onnxruntime code:

`git clone --recursive https://github.com/Microsoft/onnxruntime`

which is version **1.8.0**.

and for the specific version of Protoc:

`Get this from https://github.com/protocolbuffers/protobuf/releases/download/v3.11.2/protoc-3.11.2-linux-x86_64.zip and unzip after downloading. The version must match the one onnxruntime is using. Currently we are using 3.11.2.`

Additional information:

tool.cmake file:
`SET(CMAKE_SYSTEM_NAME Linux)`
`SET(CMAKE_SYSTEM_VERSION 1)`
`SET(CMAKE_C_COMPILER arm-galaxy-linux-gnueabi-gcc -march=armv7ve -mthumb -mfpu=vfpv4-d16 -mfloat-abi=hard --sysroot=/root/sdk/mp/sysroots/armv7vet2hf-vfpv4d16-galaxy-linux-gnueabi)`
`SET(CMAKE_CXX_COMPILER arm-galaxy-linux-gnueabi-g++ -march=armv7ve -mthumb -mfpu=vfpv4-d16 -mfloat-abi=hard --sysroot=/root/sdk/mp/sysroots/armv7vet2hf-vfpv4d16-galaxy-linux-gnueabi)`
`SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)`
`SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)`
`SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)`
`SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)`
`SET(CMAKE_FIND_ROOT_PATH /root/sdk/mp/sysroots/armv7vet2hf-vfpv4d16-galaxy-linux-gnueabi/;/root/sdk/mp/sysroots/armv7vet2hf-vfpv4d16-galaxy-linux-gnueabi/lib/)`

**Urgency**
Low

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS (Bionic Beaver)
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.8.0
- Python version: NA
- Visual Studio version (if applicable): NA
- GCC/Compiler version (if compiling from source): 8.3.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**To Reproduce**
- Git clone as specified in tutorial
- Download protobuf version as specified in tutorial
- execute cmake command (for me: `/home/onnxruntime/cmake/cmake-3.21.0-linux-x86_64/bin/cmake cmake -DONNX_CUSTOM_PROTOC_EXECUTABLE=/home/onnxruntime/protoc/bin/protoc -DCMAKE_TOOLCHAIN_FILE=tool.cmake`)
- execute `make`
- Mismatch version error message appears during build.

**Expected behavior**
Linked protobuf version should not have mismatch with onnxruntime version in cross-compile tutorial.

**Comment by snnn** [comment]
The doc is a  bit outdated.

Which onnx runtime git commit you are using? 
In your local source dir, please go to cmake/external/protobuf, then run `git log`.  What's the commit id and tag name on the top?  Like
![image](https://user-images.githubusercontent.com/856316/126008147-b6877705-a96c-4f8c-9057-77c8451d7dcc.png)

In the above case, it is 3.16.0 and you should get protoc for that version.

**Comment by coltonpeltierSE** [comment]
Looks like that got me past that error (and on to the next one!). Thank you!
