### ISSUE TITLE
Is M1 computer supported? If so, how to install it

### ISSUE THREAD

**Issue by yangqingbin** [microsoft/onnxruntime#8420]
![image](https://user-images.githubusercontent.com/39461869/126033450-bdcba50d-b593-42fc-8d09-34f44db6f216.png)
py：python 3.9
os：mac os 11.2.3

**Comment by snnn** [comment]
Not yet. It is in my backlog.

**Comment by mathieuboudreau** [comment]
+1, this feature is desired.

**Comment by yangqingbin** [comment]
> 还没有。它在我的积压工作中。

I use Anaconda3 environment, can PIP install onnxruntime normally, and can use the library I need normally. I don't know if this information is helpful to you

Py: Anaconda3. python3.8
Macos: 11.2.3. M1 chip

**Comment by mathieuboudreau** [comment]
Hum, I was under the impression that Anaconda wasn't M1-ready yet. I'll check that out – thanks!

**Comment by snnn** [comment]
I will submit a PR and publish a test package tomorrow.

**Comment by snnn** [comment]
https://test.pypi.org/project/onnxruntime/1.8.2.dev20210816004/
To install it:
```
pip3 install --upgrade pip
pip3 install numpy
pip3 install -i https://test.pypi.org/simple/ onnxruntime==1.8.2.dev20210816004
```

**Comment by tholu** [comment]
Any updates on this issue? @snnn

**Comment by snnn** [comment]
Yes. It is supported now.
