### ISSUE TITLE
Cross Compile for ARM: undefined reference to `cpuinfo_arm_linux_init'

### ISSUE THREAD

**Issue by coltonpeltierSE** [microsoft/onnxruntime#8425]
**Describe the bug**
I'm attempting to cross-compile onnxruntime for inference to arm architecture for an edge product. When performing the cross compile, I get the following error output:

```
[ 18%] Linking CXX executable onnxruntime_mlas_test
/root/sdk/mp/sysroots/x86_64-galaxysdk-linux/usr/libexec/arm-galaxy-linux-gnueabi/gcc/arm-galaxy-linux-gnueabi/8.3.0/real-ld: libonnxruntime_common.a(cpuid_info.cc.o): in function `__gnu_cxx::new_allocator<char>::~new_allocator()':
/root/sdk/mp/sysroots/armv7vet2hf-vfpv4d16-galaxy-linux-gnueabi/usr/include/c++/8.3.0/ext/new_allocator.h:86: undefined reference to `cpuinfo_isa'
/root/sdk/mp/sysroots/x86_64-galaxysdk-linux/usr/libexec/arm-galaxy-linux-gnueabi/gcc/arm-galaxy-linux-gnueabi/8.3.0/real-ld: external/pytorch_cpuinfo/libcpuinfo.a(init.c.o): in function `cpuinfo_initialize':
/home/onnxruntime/onnxruntime/)/external/pytorch_cpuinfo/src/init.c:56: undefined reference to `cpuinfo_arm_linux_init'
/root/sdk/mp/sysroots/x86_64-galaxysdk-linux/usr/libexec/arm-galaxy-linux-gnueabi/gcc/arm-galaxy-linux-gnueabi/8.3.0/real-ld: onnxruntime_mlas_test: hidden symbol `cpuinfo_arm_linux_init' isn't defined
/root/sdk/mp/sysroots/x86_64-galaxysdk-linux/usr/libexec/arm-galaxy-linux-gnueabi/gcc/arm-galaxy-linux-gnueabi/8.3.0/real-ld: final link failed: bad value
collect2: error: ld returned 1 exit status
CMakeFiles/onnxruntime_mlas_test.dir/build.make:376: recipe for target 'onnxruntime_mlas_test' failed
make[2]: *** [onnxruntime_mlas_test] Error 1
CMakeFiles/Makefile2:455: recipe for target 'CMakeFiles/onnxruntime_mlas_test.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_mlas_test.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
```

I've attached the full output of `make` here:
[makeOutput.txt](https://github.com/microsoft/onnxruntime/files/6841413/makeOutput.txt)
 and `cmake` here:
[cmakeOutput.txt](https://github.com/microsoft/onnxruntime/files/6841410/cmakeOutput.txt)

My `tool.cmake` file is as follows:
```
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR arm)
SET(CMAKE_C_COMPILER arm-galaxy-linux-gnueabi-gcc -march=armv7ve -mthumb -mfpu=vfpv4-d16 -mfloat-abi=hard --sysroot=/root/sdk/mp/sysroots/armv7vet2hf-vfpv4d16-galaxy-linux-gnueabi)
SET(CMAKE_CXX_COMPILER arm-galaxy-linux-gnueabi-g++ -march=armv7ve -mthumb -mfpu=vfpv4-d16 -mfloat-abi=hard --sysroot=/root/sdk/mp/sysroots/armv7vet2hf-vfpv4d16-galaxy-linux-gnueabi)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
SET(CMAKE_FIND_ROOT_PATH /root/sdk/mp/sysroots/armv7vet2hf-vfpv4d16-galaxy-linux-gnueabi/;/root/sdk/mp/sysroots/armv7vet2hf-vfpv4d16-galaxy-linux-gnueabi/lib/)
```

**Urgency**
Low

**System information**
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS (Bionic Beaver)
ONNX Runtime installed from (source or binary): source
ONNX Runtime version: 1.8.0
Python version: NA
Visual Studio version (if applicable): NA
GCC/Compiler version (if compiling from source): 8.3.0
CUDA/cuDNN version: NA
GPU model and memory: NA

**To Reproduce**
- Clone onnxruntime git repository
- Recreate tool.cmake as specified above
- Run cmake command (`/home/onnxruntime/cmake/cmake-3.21.0-linux-x86_64/bin/cmake cmake -DONNX_CUSTOM_PROTOC_EXECUTABLE=/home/onnxruntime/protoc/bin/protoc -DCMAKE_TOOLCHAIN_FILE=tool.cmake`)
- Run `make`

**Expected behavior**
ARM cross-compile should complete without failure.

**Additional Details**
For Protobuf I am using v3.16.0. I downloaded the x86_64 build from [here](https://github.com/protocolbuffers/protobuf/releases/download/v3.16.0/protoc-3.16.0-linux-x86_64.zip)

Does this need to be ARM?

**Comment by snnn** [comment]
@chenfucn please help take a look.

**Comment by coltonpeltierSE** [comment]
Hi, any update on this issue?

**Comment by snnn** [comment]
I can reproduce the error.

**Comment by snnn** [comment]
Hi @coltonpeltierSE, I'm updating the build instructions in #8710. Could you please help me take a look?

**Comment by snnn** [comment]
The error is because: After pytorch cpuinfo was introduced to onnx runtime, the following line is needed in toolchain.cmake:
```
SET(CMAKE_SYSTEM_PROCESSOR aarch64)
```

**Comment by coltonpeltierSE** [comment]
Hi,

Thank you for looking into this. I've updated my tool.cmake with the following change:

`
SET(CMAKE_SYSTEM_PROCESSOR aarch64)
`

Now when I perform make I get the following errors:
`
[  1%] Building C object external/pytorch_cpuinfo/CMakeFiles/cpuinfo.dir/src/arm/linux/aarch64-isa.c.o
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c: In function 'cpuinfo_arm64_linux_decode_isa_from_proc_cpuinfo':
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:14:17: error: 'CPUINFO_ARM_LINUX_FEATURE_AES' undeclared (first use in this function); did you mean 'CPUINFO_ARM_LINUX_FEATURE2_AES'?
  if (features & CPUINFO_ARM_LINUX_FEATURE_AES) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 CPUINFO_ARM_LINUX_FEATURE2_AES
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:14:17: note: each undeclared identifier is reported only once for each function it appears in
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:17:17: error: 'CPUINFO_ARM_LINUX_FEATURE_PMULL' undeclared (first use in this function); did you mean 'CPUINFO_ARM_LINUX_FEATURE2_PMULL'?
  if (features & CPUINFO_ARM_LINUX_FEATURE_PMULL) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 CPUINFO_ARM_LINUX_FEATURE2_PMULL
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:20:17: error: 'CPUINFO_ARM_LINUX_FEATURE_SHA1' undeclared (first use in this function); did you mean 'CPUINFO_ARM_LINUX_FEATURE2_SHA1'?
  if (features & CPUINFO_ARM_LINUX_FEATURE_SHA1) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 CPUINFO_ARM_LINUX_FEATURE2_SHA1
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:23:17: error: 'CPUINFO_ARM_LINUX_FEATURE_SHA2' undeclared (first use in this function); did you mean 'CPUINFO_ARM_LINUX_FEATURE2_SHA2'?
  if (features & CPUINFO_ARM_LINUX_FEATURE_SHA2) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 CPUINFO_ARM_LINUX_FEATURE2_SHA2
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:26:17: error: 'CPUINFO_ARM_LINUX_FEATURE_CRC32' undeclared (first use in this function); did you mean 'CPUINFO_ARM_LINUX_FEATURE2_CRC32'?
  if (features & CPUINFO_ARM_LINUX_FEATURE_CRC32) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 CPUINFO_ARM_LINUX_FEATURE2_CRC32
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:29:17: error: 'CPUINFO_ARM_LINUX_FEATURE_ATOMICS' undeclared (first use in this function); did you mean 'CPUINFO_ARM_LINUX_FEATURE_TLS'?
  if (features & CPUINFO_ARM_LINUX_FEATURE_ATOMICS) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 CPUINFO_ARM_LINUX_FEATURE_TLS
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:30:6: error: 'struct cpuinfo_arm_isa' has no member named 'atomics'
   isa->atomics = true;
      ^~
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:49:35: error: 'CPUINFO_ARM_LINUX_FEATURE_FPHP' undeclared (first use in this function); did you mean 'CPUINFO_ARM_LINUX_FEATURE_FPA'?
   const uint32_t fp16arith_mask = CPUINFO_ARM_LINUX_FEATURE_FPHP | CPUINFO_ARM_LINUX_FEATURE_ASIMDHP;
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                   CPUINFO_ARM_LINUX_FEATURE_FPA
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:49:68: error: 'CPUINFO_ARM_LINUX_FEATURE_ASIMDHP' undeclared (first use in this function); did you mean 'CPUINFO_ARM_LINUX_FEATURE_SWP'?
   const uint32_t fp16arith_mask = CPUINFO_ARM_LINUX_FEATURE_FPHP | CPUINFO_ARM_LINUX_FEATURE_ASIMDHP;
                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                    CPUINFO_ARM_LINUX_FEATURE_SWP
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:75:20: error: 'CPUINFO_ARM_LINUX_FEATURE_ASIMDRDM' undeclared (first use in this function); did you mean 'CPUINFO_ARM_LINUX_FEATURE_IDIVA'?
     if (features & CPUINFO_ARM_LINUX_FEATURE_ASIMDRDM) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                    CPUINFO_ARM_LINUX_FEATURE_IDIVA
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:107:19: error: 'CPUINFO_ARM_LINUX_FEATURE_ASIMDDP' undeclared (first use in this function); did you mean 'CPUINFO_ARM_LINUX_FEATURE_SWP'?
    if (features & CPUINFO_ARM_LINUX_FEATURE_ASIMDDP) {
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   CPUINFO_ARM_LINUX_FEATURE_SWP
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:112:17: error: 'CPUINFO_ARM_LINUX_FEATURE_JSCVT' undeclared (first use in this function); did you mean 'CPUINFO_ARM_LINUX_FEATURE_JAVA'?
  if (features & CPUINFO_ARM_LINUX_FEATURE_JSCVT) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 CPUINFO_ARM_LINUX_FEATURE_JAVA
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:118:17: error: 'CPUINFO_ARM_LINUX_FEATURE_FCMA' undeclared (first use in this function); did you mean 'CPUINFO_ARM_LINUX_FEATURE_FPA'?
  if (features & CPUINFO_ARM_LINUX_FEATURE_FCMA) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 CPUINFO_ARM_LINUX_FEATURE_FPA
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:121:17: error: 'CPUINFO_ARM_LINUX_FEATURE_SVE' undeclared (first use in this function); did you mean 'CPUINFO_ARM_LINUX_FEATURE_SWP'?
  if (features & CPUINFO_ARM_LINUX_FEATURE_SVE) {
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                 CPUINFO_ARM_LINUX_FEATURE_SWP
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:122:6: error: 'struct cpuinfo_arm_isa' has no member named 'sve'
   isa->sve = true;
      ^~
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:124:18: error: 'CPUINFO_ARM_LINUX_FEATURE2_SVE2' undeclared (first use in this function); did you mean 'CPUINFO_ARM_LINUX_FEATURE2_SHA2'?
  if (features2 & CPUINFO_ARM_LINUX_FEATURE2_SVE2) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  CPUINFO_ARM_LINUX_FEATURE2_SHA2
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/arm/linux/aarch64-isa.c:125:8: error: 'struct cpuinfo_arm_isa' has no member named 'sve2'; did you mean 'sha2'?
   isa->sve2 = true;
        ^~~~
        sha2
external/pytorch_cpuinfo/CMakeFiles/cpuinfo.dir/build.make:229: recipe for target 'external/pytorch_cpuinfo/CMakeFiles/cpuinfo.dir/src/arm/linux/aarch64-isa.c.o' failed
make[2]: *** [external/pytorch_cpuinfo/CMakeFiles/cpuinfo.dir/src/arm/linux/aarch64-isa.c.o] Error 1
CMakeFiles/Makefile2:2015: recipe for target 'external/pytorch_cpuinfo/CMakeFiles/cpuinfo.dir/all' failed
make[1]: *** [external/pytorch_cpuinfo/CMakeFiles/cpuinfo.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by snnn** [comment]
```
SET(CMAKE_SYSTEM_PROCESSOR arm)
```

You are doing it for arm 32, not 64.

**Comment by coltonpeltierSE** [comment]
That's the same value for `CMAKE_SYSTEM_PROCESSOR` I had in my original post, setting it back to `SET(CMAKE_SYSTEM_PROCESSOR arm)` reproduces the error from my original post:

`
[ 17%] Linking CXX executable onnxruntime_mlas_test
/root/sdk/mp/sysroots/x86_64-galaxysdk-linux/usr/libexec/arm-galaxy-linux-gnueabi/gcc/arm-galaxy-linux-gnueabi/8.3.0/real-ld: libonnxruntime_common.a(cpuid_info.cc.o): in function `__gnu_cxx::new_allocator<char>::~new_allocator()':
/root/sdk/mp/sysroots/armv7vet2hf-vfpv4d16-galaxy-linux-gnueabi/usr/include/c++/8.3.0/ext/new_allocator.h:86: undefined reference to `cpuinfo_isa'
/root/sdk/mp/sysroots/x86_64-galaxysdk-linux/usr/libexec/arm-galaxy-linux-gnueabi/gcc/arm-galaxy-linux-gnueabi/8.3.0/real-ld: external/pytorch_cpuinfo/libcpuinfo.a(init.c.o): in function `cpuinfo_initialize':
/home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/init.c:56: undefined reference to `cpuinfo_arm_linux_init'
/root/sdk/mp/sysroots/x86_64-galaxysdk-linux/usr/libexec/arm-galaxy-linux-gnueabi/gcc/arm-galaxy-linux-gnueabi/8.3.0/real-ld: onnxruntime_mlas_test: hidden symbol `cpuinfo_arm_linux_init' isn't defined
/root/sdk/mp/sysroots/x86_64-galaxysdk-linux/usr/libexec/arm-galaxy-linux-gnueabi/gcc/arm-galaxy-linux-gnueabi/8.3.0/real-ld: final link failed: bad value
collect2: error: ld returned 1 exit status
CMakeFiles/onnxruntime_mlas_test.dir/build.make:376: recipe for target 'onnxruntime_mlas_test' failed
make[2]: *** [onnxruntime_mlas_test] Error 1
CMakeFiles/Makefile2:429: recipe for target 'CMakeFiles/onnxruntime_mlas_test.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_mlas_test.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by coltonpeltierSE** [comment]
That did the trick, looks like `armv7` was what I needed instead of just `arm`. Thank you for the help. It could be useful in your updated instructions to highlight this.

**Comment by mlinxiang** [comment]
when i build android armv8a has follow error for 1.10 code:
<img width="838" alt="image" src="https://user-images.githubusercontent.com/6283983/159879139-09b3e3dd-c074-4242-ac1a-de8895029bf8.png">

**Comment by pietermarsman** [comment]
> That's the same value for `CMAKE_SYSTEM_PROCESSOR` I had in my original post, setting it back to `SET(CMAKE_SYSTEM_PROCESSOR arm)` reproduces the error from my original post:
> 
> ```
> [ 17%] Linking CXX executable onnxruntime_mlas_test
> /root/sdk/mp/sysroots/x86_64-galaxysdk-linux/usr/libexec/arm-galaxy-linux-gnueabi/gcc/arm-galaxy-linux-gnueabi/8.3.0/real-ld: libonnxruntime_common.a(cpuid_info.cc.o): in function `__gnu_cxx::new_allocator<char>::~new_allocator()':
> /root/sdk/mp/sysroots/armv7vet2hf-vfpv4d16-galaxy-linux-gnueabi/usr/include/c++/8.3.0/ext/new_allocator.h:86: undefined reference to `cpuinfo_isa'
> /root/sdk/mp/sysroots/x86_64-galaxysdk-linux/usr/libexec/arm-galaxy-linux-gnueabi/gcc/arm-galaxy-linux-gnueabi/8.3.0/real-ld: external/pytorch_cpuinfo/libcpuinfo.a(init.c.o): in function `cpuinfo_initialize':
> /home/onnxruntime/onnxruntime/cmake/external/pytorch_cpuinfo/src/init.c:56: undefined reference to `cpuinfo_arm_linux_init'
> /root/sdk/mp/sysroots/x86_64-galaxysdk-linux/usr/libexec/arm-galaxy-linux-gnueabi/gcc/arm-galaxy-linux-gnueabi/8.3.0/real-ld: onnxruntime_mlas_test: hidden symbol `cpuinfo_arm_linux_init' isn't defined
> /root/sdk/mp/sysroots/x86_64-galaxysdk-linux/usr/libexec/arm-galaxy-linux-gnueabi/gcc/arm-galaxy-linux-gnueabi/8.3.0/real-ld: final link failed: bad value
> collect2: error: ld returned 1 exit status
> CMakeFiles/onnxruntime_mlas_test.dir/build.make:376: recipe for target 'onnxruntime_mlas_test' failed
> make[2]: *** [onnxruntime_mlas_test] Error 1
> CMakeFiles/Makefile2:429: recipe for target 'CMakeFiles/onnxruntime_mlas_test.dir/all' failed
> make[1]: *** [CMakeFiles/onnxruntime_mlas_test.dir/all] Error 2
> Makefile:165: recipe for target 'all' failed
> make: *** [all] Error 2
> ```
> 
> Here's my full `tool.cmake` file:
> 
> ```
> SET(CMAKE_SYSTEM_NAME Linux)
> SET(CMAKE_SYSTEM_VERSION 1)
> SET(CMAKE_SYSTEM_PROCESSOR arm)
> SET(CMAKE_C_COMPILER arm-galaxy-linux-gnueabi-gcc -march=armv7ve -mthumb -mfpu=vfpv4-d16 -mfloat-abi=hard --sysroot=/root/sdk/mp/sysroots/armv7vet2hf-vfpv4d16-galaxy-linux-gnueabi)
> SET(CMAKE_CXX_COMPILER arm-galaxy-linux-gnueabi-g++ -march=armv7ve -mthumb -mfpu=vfpv4-d16 -mfloat-abi=hard --sysroot=/root/sdk/mp/sysroots/armv7vet2hf-vfpv4d16-galaxy-linux-gnueabi)
> SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
> SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
> SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
> SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
> SET(CMAKE_FIND_ROOT_PATH /root/sdk/mp/sysroots/armv7vet2hf-vfpv4d16-galaxy-linux-gnueabi/;/root/sdk/mp/sysroots/armv7vet2hf-vfpv4d16-galaxy-linux-gnueabi/lib/)
> ```

This helped me a lot. The documentation on [onnxruntime.ai](https://onnxruntime.ai/docs/build/inferencing.html#cross-compiling-on-linux) does not mention this. Perhaps the addition of the `SET(CMAKE_SYSTEM_PROCESSOR arm)` line can be added to the instructions  as well.
