### ISSUE TITLE
[BREAKING CHANGE] bert_tf transformers optimizations now fail.

### ISSUE THREAD

**Issue by claeyzre** [microsoft/onnxruntime#8439]
**Describe the bug**
BREAKING CHANGE: bert_tf transformers optimizations now fail.

**Urgency**
none.

**System information**
- Windows 10
- ONNX Runtime installed with pip,
- ONNX Runtime version: 1.8.1
- Python version: 3.7

**To Reproduce**
- Train a dummy classifier model using a BERT Mini as a backbone with Tensorflow 2.5, export it to saved_model
- Use tf2onnx v1.9.1 to export it in onnx.
- Try to apply the "bert_tf" optimizations for this model using the following python code:
```
from onnxruntime.transformers import optimizer
optimizer.optimize_model(
        onnx_model_path,
        model_type="bert_tf",
        num_heads=4,
        hidden_size=256,
        opt_level=0,
        use_gpu=False)
```

which produces the following stacktrace
```
INFO: Fused FastGelu count: 4
INFO: Removed Identity count: 0
INFO: start processing embedding layer...
failed in shape inference <class 'AttributeError'>
Traceback (most recent call last):
  File "...\lib\site-packages\onnxruntime\transformers\optimizer.py", line 312, in optimize_model
    optimizer.optimize(optimization_options)
  File "...\lib\site-packages\onnxruntime\transformers\onnx_model_bert.py", line 282, in optimize
    self.fuse_attention()
  File "...\lib\site-packages\onnxruntime\transformers\onnx_model_bert_tf.py", line 291, in fuse_attention
    graph_name = self.get_graph_by_node(start_nodes[0]).name
IndexError: list index out of range
```

Note that this used to work with version previous to #7701 

**Expected behavior**
The optimizations should work or be skipped when the layers to be optimzed are not present.

**Additional context**
This used to work with previous onnxruntime version.
You can find the model to be downloaded [here ](https://drive.google.com/file/d/1W2r4YeEHFFPqoc2QN-9A5sH4EAQv7Edc/view?usp=sharing) in google drive

**Comment by wangyems** [comment]
Thanks for reporting the issue. Will take a look.

**Comment by wangyems** [comment]
Closing this issue. @claeyzre please try the master branch.
