### ISSUE TITLE
Support for EfficientNMS_TRT plugin in TensorRT execution provider

### ISSUE THREAD

**Issue by flojar** [microsoft/onnxruntime#8461]
**System information**
- ONNX Runtime version (you are using): v1.8.1

**Description of our problem**
We have an object detection model (EfficientDet) that we converted to use it in TensorRT. The needed conversion
changed the NonMaxSuppression operator with the EfficientNMS_TRT TensorRT plugin, introduced in TensorRT 8.
The model is running fine in standalone TensorRT and we are really happy with the performance results.

So now to our problem...

We are using the ONNX Runtime as inference pipeline in all our projects and want to run the object detection model through the TensorRT execution provider.
As a first solution we tried to build the ONNX Runtime against the new TensorRT 8 and onnx-tensorrt release. When running the session with named model it keeps crashing when reaching the onnx checker, because the EfficientNMS_TRT op is not registered. Our tries to register EfficientNMS_TRT manually have failed.

Is there a way to run the inference session with the EfficientNMS_TRT TensorRT plugin?

**Our Model**
https://drive.google.com/file/d/1g-fI-MCS6HtY8MFkLdGEV2PsHYYca-tg/view

**Comment by prashant-dn** [comment]
Yo, open up the issue back y'all
This ain't been resolved

**Comment by gcunhase** [comment]
Has this been resolved? @chilo-ms

**Comment by chilo-ms** [comment]
[EfficientNMS_TRT](https://github.com/NVIDIA/TensorRT/tree/release/10.0/plugin/efficientNMSPlugin) is natively supported by TRT and you can use it with ORT (see [here](https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html#tensorrt-plugins-support)):

- ORT 1.17 + TRT 8.6 or
- ORT 1.18 + TRT 10

If you are using customized TRT plugin, please use ORT 1.18 + TRT 10
