### ISSUE TITLE
Python API summary documentation / docs doesn't include arg descriptions

### ISSUE THREAD

**Issue by garymm** [microsoft/onnxruntime#8465]
Example of what I see on this page:
https://www.onnxruntime.ai/python/api_summary.html#onnxruntime.InferenceSession

```
class onnxruntime.InferenceSession(path_or_bytes, sess_options=None, providers=None, provider_options=None)[source]
This is the main class used to run a model.
```

This is missing the very useful documentation that has been written in the source code.
Example [from here](https://github.com/microsoft/onnxruntime/blob/3a72932c4a4afc2e72c6b3bfc17b3c0a248e6232/onnxruntime/python/onnxruntime_inference_collection.py#L238):

```
def __init__(self, path_or_bytes, sess_options=None, providers=None, provider_options=None, **kwargs):
        """
        :param path_or_bytes: filename or serialized ONNX or ORT format model in a byte string
```

I guess there may be some Sphinx options that can be changed to include the args in the generated documentation. If it makes the API summary page too long, one could also switch to having a single page per class.

**Comment by ytaous** [comment]
closing the issue per description in the PR, thx
