### ISSUE TITLE
compiler warning resulting from pytorch_cpuinfo in x64 and x86 builds of WinML Inbox

### ISSUE THREAD

**Issue by ryanlai2** [microsoft/onnxruntime#8482]
**Describe the bug**
WinML x64 and x86 builds are failing because of compiler warning in pytorch_cpuinfo submodule: 
>E:\BA\225\s\engine\lotus\cmake\external\pytorch_cpuinfo\src\x86\name.c(700,3): warning C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details 

**Urgency**
This is blocking code flow from github into internal repositories for building WinML inbox.

**System information**

Logs are found here : https://microsoft.visualstudio.com/WindowsAI/_build/results?buildId=37088271&view=logs&j=eef0181c-71f0-51de-7de9-2ce9f18a83ff&t=c612bbf5-28be-5a0b-353b-411a3af9bb3e&l=3402

**To Reproduce**
Clone windowsai repo https://microsoft.visualstudio.com/windowsai/_git/WindowsAI , run build script tools/buildall.ps1. 

**Expected behavior**
Build without issues

**Additional context**
How is Onnxruntime handling this warning?

**Comment by snnn** [comment]
What's your suggestion on this? Adding _CRT_SECURE_NO_WARNINGS or ... ?

**Comment by fdwr** [comment]
I wonder what build flags ORT uses such that this error doesn't happen in ORT itself? Does it suppress `[[deprecated]]` or specify `_CRT_NONSTDC_NO_DEPRECATE`? Even if we made changes to the [PyTorch repo](https://github.com/pytorch/cpuinfo), it would take a while to reach us 🤔. Using `_CRT_SECURE_NO_WARNINGS` for now would mitigate it so we can build.

**Comment by snnn** [comment]
I didn't add special flags to pytorch_cpuinfo. It is not built with "/WX". So the warnings show up in every build but they are not treated as errors.

**Comment by fdwr** [comment]
@zhangxiang1993 is trying to work around it on our side, keeping /WX by default for all projects except `TARGET cpuinfo`. If that works, then we'll close this. Though, it's probably still useful for ORT to add an exclusion itself so that people who statically link ORT into their projects can build clean at the highest warning levels with even warnings as errors.

**Comment by chenfucn** [comment]
https://github.com/microsoft/onnxruntime/pull/8716
