### ISSUE TITLE
onnxruntime_eager library does not compile on Windows due to ""

### ISSUE THREAD

**Issue by ashari4** [microsoft/onnxruntime#8486]
**Describe the bug**

`ort_kernel_invoker.cc` does not compile on Windows because `""` is used to initialize an `std::wstring`. 

```
<>\onnxruntime\core\eager\ort_kernel_invoker.cc(21): error C2664: 'onnxruntime::Model::Model(const std::string &,bool,const onnxruntime::ModelMetaData &,const onnxruntime::PathString &,const onnxruntime::IOnnxRuntimeOpSchemaRegistryList &,const std::unordered_map<std::string,int,std::hash<std::string>,std::equal_to<std::string>,std::allocator<std::pair<const std::string,int>>> &,const std::vector<onnx::FunctionProto,std::allocator<onnx::FunctionProto>> &,const onnxruntime::logging::Logger &)': cannot convert argument 4 from 'const char [1]' to 'const onnxruntime::PathString &'
<>\onnxruntime\core\eager\ort_kernel_invoker.cc(28): note: Reason: cannot convert from 'const char [1]' to 'const onnxruntime::PathString'
<>\onnxruntime\core\eager\ort_kernel_invoker.cc(28): note: No constructor could take the source type, or constructor overload resolution was ambiguous
<>\onnxruntime\core/graph/model.h(47): note: see declaration of 'onnxruntime::Model::Model'
```

**Urgency**
This is breaking my team's Windows builds. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.8
- Python version: 3.9
- Visual Studio version (if applicable): 16.10

**To Reproduce**
Build with `-Donnxruntime_ENABLE_EAGER_MODE=ON `

**Expected behavior**

Successful compilation

**Comment by yuslepukhin** [comment]
You can not pass char[] to PathString on Windows. It is wchar_t

**Comment by ashari4** [comment]
@yuslepukhin thanks, yes, see #8487 for a potential fix.
