### ISSUE TITLE
`override_torch_manual_seed` doesn't assure integer seed

### ISSUE THREAD

**Issue by richarddwang** [microsoft/onnxruntime#8489]
**Describe the bug**
```
File "/home/yisiang/miniconda3/envs/dl/lib/python3.9/site-packages/pytorch_lightning/utilities/seed.py", line 114, in pl_worker_init_function
    torch.manual_seed(torch_ss.generate_state(1, dtype=dtype)[0])
File "/home/yisiang/miniconda3/envs/dl/lib/python3.9/site-packages/onnxruntime/training/ortmodule/__init__.py", line 50, in override_torch_manual_seed
    set_seed(seed % sys.maxsize)
TypeError: set_seed(): incompatible function arguments. The following argument types are supported:
    1. (arg0: int) -> None

Invoked with: 8.619664877204371e+18
```
`isinstance(8.619664877204371e+18, int)` is False

**Urgency**
Can't train if manually set seed

**System information**
- OS Platform and Distribution (*e.g. Linux Ubuntu 16.04*): Linux Ubunttu 20.04
- ONNX version (*e.g. 1.7*):  1.9.0
- onnxruntime-training 1.8.1+torch190.cu111
- Python version: 3.9
- torch 1.9.0
- torch-ort 1.8.1
- CUDA/cuDNN version: 11.2

**Fix**
Just need  `set_seed(int(seed % sys.maxsize))` 
https://github.com/microsoft/onnxruntime/blob/83be3759bc939fc0bb5062bc6625d5a1f1312aa0/orttraining/orttraining/python/training/ortmodule/__init__.py#L49-L60

**Comment by SherlockNoMad** [comment]
Thank you for reporting this bug, fix in PR.

**Comment by SherlockNoMad** [comment]
Hi @richarddwang, I am just curious what's your use scenario for using ORTModule?

**Comment by richarddwang** [comment]
I import torch_ort and cast the main model nn module into ORTModule, to make language model pretraining faster.

**Comment by richarddwang** [comment]
I quickly scan the changed code, there is also line 50 need to be casted to int ?

**Comment by ytaous** [comment]
on line#50 - although the torch doc says it's long, but when actually testing it, it's int. 
>>> import torch
>>> a = torch.initial_seed()
>>> type(a)
<class 'int'>
And looks like torch has unified long and int a few version back since python 2.4 - see more discussion here - https://stackoverflow.com/questions/2104884/how-does-python-manage-int-and-long

close it for now - pls let us know if you encounter issue, thx
