### ISSUE TITLE
onnxruntime=1.4 Concat [ShapeInferenceError] axis must be in [-rank, rank-1] when rank=2 and axis=1

### ISSUE THREAD

**Issue by takacsg84** [microsoft/onnxruntime#8496]
We are trying to use our pipeline on Oracle Machine Learning server. Unfortunately they only have onnxruntime 1.4 running on their servers. They are planning to make an update in a few weeks, but it would be urgent for us to get started with our pipeline ASAP.
When trying to use Concat with target opset=12 we get the following error:
`Fail: [ONNXRuntimeError] : 1 : FAIL : Node (Concat) Op (Concat) [ShapeInferenceError] axis must be in [-rank, rank-1].`
The node desciption is the following:
```
  node {
    input: "ENCODED_input_cast"
    input: "ENCODED_input2_cast"
    input: "continuous_inputs_cast"
    output: "transformed_and_continuous"
    name: "Concat"
    op_type: "Concat"
    attribute {
      name: "axis"
      i: 1
      type: INT
    }
    domain: ""
  }
```

**Comment by snnn** [comment]
The error came from ONNX.  Please use onnx model checker to check if the model is valid. I believe it is not.

**Comment by takacsg84** [comment]
Thank you for the advice! I did check the model like this: `onnx.checker.check_model(onnx_model)` and the model is valid. Any other way to debug?

**Comment by snnn** [comment]
Did you run it with the latest onnx checker from onnx 1.9.0 ?

**Comment by takacsg84** [comment]
Yes! But we can close the issue, we managed to get a server update, and it works when onnxruntime >= 1.6

**Comment by takacsg84** [comment]
Thank you for your help!
