### ISSUE TITLE
Segmentation fault when shared_ptr<session> destruct, the shared_ptr<session> is in use of cuda provider

### ISSUE THREAD

**Issue by yank666** [microsoft/onnxruntime#8508]
**Describe the bug**
I use a shared_ptr<session> as a class private value,  before the  shared_ptr<session> is created, i called OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0), it is ok when running, but when it end running, it is Segmentation fault when  destruct, i don't konw what's wrong, need help!

here is frames:

![image](https://user-images.githubusercontent.com/79586188/127149260-d5c3f039-2281-4ac5-861c-cc4928427c4f.png)

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- ONNX Runtime installed from (source or binary):  binary
- ONNX Runtime version: 1.8.1 cuda EP
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by snnn** [comment]
Please don't use any onnx runtime APIs before the main function is started.
And don't clean up all the onnx runtime objects before main is returned.
