### ISSUE TITLE
bidirectional lstm model with sequence_lens RuntimeError: Unexpected input data type

### ISSUE THREAD

**Issue by fjfjfan** [Microsoft/onnxruntime#851]
**Describe the bug**
I want to verify the prediction with ONNX Runtime and onnx-tensorflow.
I used a bidirectional lstm model with 'sequence_lens', 'initial_h', 'initial_c':
[test_lstm_bidirectional_c_simple.onnx.zip](https://github.com/Microsoft/onnxruntime/files/3087774/test_lstm_bidirectional_c_simple.onnx.zip)

But there is an error:
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (N11onnxruntime11NonOnnxTypeIiEE) , expected: (N11onnxruntime11NonOnnxTypeIfEE)

seems it caused by the type of sequence_lens?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac os 10.14
- ONNX Runtime installed from (source or binary):
pip install onnxruntime
- ONNX Runtime version:
0.3.0
- Python version:
python 3.6

**To Reproduce**
```
import onnx
import numpy as np
from onnx_tf.backend import run_node

input = np.array([[[1., 2., 3., 4.], [5., 6., 7., 8.]]]).astype(np.float32)

input_size = 4
hidden_size = 3
weight_scale = 0.1
number_of_gates = 4
number_of_peepholes = 3

# Initializing Inputs
X = input
W = weight_scale * np.ones((2, number_of_gates * hidden_size, input_size)).astype(np.float32)
R = weight_scale * np.ones((2, number_of_gates * hidden_size, hidden_size)).astype(np.float32)
B = np.zeros((2, 2 * number_of_gates * hidden_size)).astype(np.float32)
sequence_lens = np.repeat(input.shape[0], input.shape[1]).astype(np.int32)
initial_h = weight_scale * np.zeros((2, input.shape[1], hidden_size)).astype(np.float32)
initial_c = weight_scale * np.ones(
    (2, input.shape[1], hidden_size)).astype(np.float32)

node = onnx.helper.make_node(
    'LSTM',
    inputs=['X', 'W', 'R', 'B', 'sequence_lens', 'initial_h', 'initial_c'],
    outputs=['Y', 'Y_h', 'Y_c'],
    activations=['Sigmoid', 'Tanh', 'Tanh', 'Sigmoid', 'Tanh', 'Tanh'],
    direction='bidirectional',
    hidden_size=hidden_size)

outputs = run_node(node, [X, W, R, B, sequence_lens, initial_h, initial_c])
Y = outputs["Y"]
Y_h_1 = outputs["Y_h"]
Y_c = outputs["Y_c"]


# Compute the prediction with ONNX Runtime
import onnxruntime as rt
import numpy
sess = rt.InferenceSession("test_lstm_bidirectional_c_simple.onnx")
input_name_X = sess.get_inputs()[0].name
input_name_W = sess.get_inputs()[1].name
input_name_R = sess.get_inputs()[2].name
input_name_B = sess.get_inputs()[3].name
input_name_S = sess.get_inputs()[4].name
input_name_H = sess.get_inputs()[5].name
input_name_C = sess.get_inputs()[6].name

label_name_Y = sess.get_outputs()[0].name
label_name_Y_h = sess.get_outputs()[1].name
label_name_Y_c = sess.get_outputs()[2].name

pred_onx = sess.run([label_name_Y, label_name_Y_h, label_name_Y_c], {input_name_X: X,
input_name_W : W,
input_name_R : R,
input_name_B : B,
input_name_S : sequence_lens,
input_name_H :initial_h,
input_name_C :initial_c})
```

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by snnn** [comment]
You feed in wrong input type. Please verify if your input tensor's element type matches the model's requirement.

**Comment by fjfjfan** [comment]
@snnn Thanks for your comments. Yes, from the error msg we could get that info. But if you modified to
`sequence_lens = np.repeat(input.shape[0], input.shape[1]).astype(np.float32)`
The error will be:
`TypeError: Value passed to parameter 'seq_lengths' has DataType float32 not in list of allowed values: int32, int64`

Also from https://github.com/onnx/onnx/blob/master/docs/Operators.md#LSTM, the type of sequence_lens should be T1 : tensor(int32)
The definition in the model and the data feed to the model in my code are np.int32, which is match the ONNX specification.
Thanks!

**Comment by pranavsharma** [comment]
@fjfjfan I ran your script. You're not labeling the inputs correctly. Here're the labels you assume

X type:  tensor(float)
W type:  tensor(float)
R type:  tensor(float)
B type:  tensor(float)
S type:  tensor(float)
H type:  tensor(float)
C type:  tensor(int32) <---- you assume this is C, when it should be sequence_lens

Here are the actual lables that are obtained from the session

B  type:  tensor(float)
R  type:  tensor(float)
W  type:  tensor(float)
X  type:  tensor(float)
initial_c  type:  tensor(float)
initial_h  type:  tensor(float)
sequence_lens  type:  tensor(int32)

Let me know if this doesn't fix the issue.

**Comment by pranavsharma** [comment]
This is the modification I did to your script

<code>
input_name_X = sess.get_inputs()[0].name
print(input_name_X, " type: ", sess.get_inputs()[0].type)
input_name_W = sess.get_inputs()[1].name
print(input_name_W, " type: ", sess.get_inputs()[1].type)
input_name_R = sess.get_inputs()[2].name
print(input_name_R, " type: ", sess.get_inputs()[2].type)
input_name_B = sess.get_inputs()[3].name
print(input_name_B, " type: ", sess.get_inputs()[3].type)
input_name_S = sess.get_inputs()[4].name
print(input_name_S, " type: ", sess.get_inputs()[4].type)
input_name_H = sess.get_inputs()[5].name
print(input_name_H, " type: ", sess.get_inputs()[5].type)
input_name_C = sess.get_inputs()[6].name
print(input_name_C, " type: ", sess.get_inputs()[6].type)
</code>

**Comment by fjfjfan** [comment]
@pranavsharma Thanks for your prompt response, that works for me, just one more question: where to get those info? since it has different input/out sequence of params from onnx or onnx-tf. Thanks a lot!

**Comment by pranavsharma** [comment]
Use sess.get_inputs()[0].name and sess.get_inputs()[0].type to get this info. Closing this now since your issue is resolved.
