### ISSUE TITLE
About output

### ISSUE THREAD

**Issue by hcsearch** [microsoft/onnxruntime#852]
If I want to get the network output of each layer, such as the activation value, then what should I do.
thanks.

**Comment by snnn** [comment]
Modify the model file, add them into model output.

**Comment by linkerzhang** [comment]
One more API in ONNX runtime will be added to allow customers specifying more outputs programmatically. Will keep this issue open to track the API adding task.

**Comment by haifenghan** [comment]
caffe2 has a API to export all outputs:

```
# Load the ONNX model
model = onnx.load('model.onnx')
# Run the ONNX model with Caffe2
backend = caffe2.python.onnx.backend.prepare(model)
outputs = backend.run([img])
blobs = backend.workspace.Blobs()
caffe2_outputs = {k: backend.workspace.FetchBlob(k) for k in blobs}
```

Could you export the similar API to us? Thanks

**Comment by faxu** [comment]
@hcsearch does this answer your question? if so, please close this issue, thanks!
