### ISSUE TITLE
Issues in loading Sklearn's SVC model in scala/Java with ONNX 

### ISSUE THREAD

**Issue by aakashveera** [microsoft/onnxruntime#8525]
For a demonstration of this issue, I have used IRIS as the data.
I have created models for IRIS data with sklearn's Randomforest, Logistic Regression and SVC and dumped all three using onxx library. 
Now while accessing the onxx models in scala with onnxruntime the RF model and logistic-reg model works as expected

![image](https://user-images.githubusercontent.com/54843933/127280588-604759af-f50d-4059-9b79-c70dcc0da60e.png)

Now while loading the SVC model trained and dumped in the same way it is giving some weird output as shown in the image and couldn't able to parse the results.

![image](https://user-images.githubusercontent.com/54843933/127280790-f21d91e7-3a27-4323-8eaf-28aaf71ff394.png)

(usually this happens when we print a java array. But this isn't a java array. Indexing causes error)

Initally had issues in saving svc model. Referred https://github.com/onnx/sklearn-onnx/issues/302 and was able to save the model. But now I am getting errors in parsing the output only in scala/Java. while loading the saved onnx model in Python the results were good as expected.

**Comment by Craigacp** [comment]
You can query the model once it's loaded into a session to see what the output looks like with `session.getOutputInfo()`. The SVC might be returning a sequence of maps, which you need to treat differently when you work with it on the JVM. You can see an example of parsing that out [here](https://github.com/oracle/tribuo/blob/main/Interop/ONNX/src/main/java/org/tribuo/interop/onnx/LabelTransformer.java#L119).
