### ISSUE TITLE
Any tutorial for c++ inference?

### ISSUE THREAD

**Issue by zyandtom** [microsoft/onnxruntime#8526]
I'm really new to this, and I found that even no docs for how to load the onnx model in cpp, or how to create tensor. Here I have met difficulties, this is my code:
```
#include <onnxruntime_cxx_api.h>
#include <iostream>
#include <sys/time.h>
using namespace std;
Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");

int main(int argc) {
  float time_use=0;
  struct timeval start;
  struct timeval end;
  try{
    const char* model_path = "./models/laneGCN.onnx";
    Ort::Session session{env, model_path, Ort::SessionOptions{nullptr}};

    //define example data

    //feats
    auto allocator_info = Ort::AllocatorInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU);

```
Last line shows that name followed by '::' must be a class or namespace name, which means Ort does not have an AllocatorInfo?

Platform: ubuntu 18

**Comment by snnn** [comment]
See: https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/MNIST

**Comment by zyandtom** [comment]
> See: https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx/MNIST

I have seen this before, thx, how about Linux version codes?

**Comment by snnn** [comment]
Currently we don't have one, but overall it should look the same. Onnx runtime APIs are the same on Windows and Linux.

**Comment by pranavsharma** [comment]
This should help. https://gist.github.com/pranavsharma/fe589e119e0995690b5e262b6d751397

**Comment by zyandtom** [comment]
thank you so much!
