### ISSUE TITLE
Need sample or document about batch predict

### ISSUE THREAD

**Issue by bitnick10** [microsoft/onnxruntime#853]
There's C API Sample so that I can usnig this lib in C API,but the C API Sample only provide predict once a time,I need one more Sample or document about batch predict.

**Comment by Varusnguyen** [comment]
Hi, @bitnick10. I am trying to use the example of onnx runtime for C++ API and now I am getting this kind of error even I included onnruntime_c_api.h and onnxruntime_cxx_api.h. Do you have any suggestions for me to resolve this problem? Thank you in advance,
![image](https://user-images.githubusercontent.com/49540574/57356086-23c0f680-71a2-11e9-8fa7-02a997516dfb.png)

**Comment by bitnick10** [comment]
@Varusnguyen ,Since C lib is the stable one for me ,I'm still using it, and wait someone who can help us add C++ API to vcpkg so that is would be very easy to use(which should be avoid your error code).
https://github.com/microsoft/onnxruntime/issues/931

**Comment by Varusnguyen** [comment]
@bitnick10. Thank you for your quick answer. I hope someone will help us to do this. I am really getting stuck in this problem for a while since my applications are all written in C++.

**Comment by bitnick10** [comment]
@Varusnguyen you are welcome,I'm stuck for very long time since all code written in C++,so finally I choice the C API even it's not very fast

**Comment by Varusnguyen** [comment]
@bitnick10.  Onnxruntime provided two header files: onnruntime_c_api.h and onnxruntime_cxx_api.h, so I thought that one of them will be used in C++ program and it will be directly included.  Do I make any misunderstanding here?

**Comment by bitnick10** [comment]
@Varusnguyen this header is new for me since it's not in the 0.3 ,I'll do some research and I'll see what I can do whit it

**Comment by bitnick10** [comment]
hi @Varusnguyen,till now I'm OK to run the [C++ example](https://github.com/microsoft/onnxruntime/blob/master/csharp/test/Microsoft.ML.OnnxRuntime.EndToEndTests.Capi/CXX_Api_Sample.cpp) My step:1.nuget onnxruntime;2.copy onnxruntime_cxx_api.h to your project folder;3.run

**Comment by Varusnguyen** [comment]
@bitnick10. Your support is so incredible to me and I very appreciate about that. Since I just move to C++ for a while, so a lot of things I need to study hard. Can you tell me how to NuGet onnx runtime ( is it the same way with load onnxruntime by NuGet in C#. I just choose project properties and choose to manage NuGet packages). Furthermore, the onnxruntime_cxx_api.h need to include the onnxruntime_c_api.h, so if you do not include onnxruntime_c_api.h, how it can be combined?

**Comment by bitnick10** [comment]
@Varusnguyen yeah,nuget the .net version so that it gives you the c header and dll which wrapped by C#.I'm using the c version of it. but without the C++ header.

**Comment by Varusnguyen** [comment]
@bitnick10 ,  your suggestion is so valuable for me so far, after installing the Nuget onnxruntime, I felt I have one step closer to what I expected. But there are some erros in my code as following pictures. Did you meet that when coding your program?
![image](https://user-images.githubusercontent.com/49540574/57363563-ea918200-71b3-11e9-921e-afd1eb335cdc.png)

**Comment by bitnick10** [comment]
@Varusnguyen I can run it well.You should troubleshooting the rest with [stackoverflow ](https://stackoverflow.com/)and google now.

**Comment by snnn** [comment]
Hi, I changed the title so that the dev team can focus on one specific problem and timely finished it. 
If you have more questions/requirements, please feel free to open a new issue.

**Comment by natke** [comment]
Fixed by #1372
