### ISSUE TITLE
new LearningModelSession not returning in Windows-Machine-Learning sample

### ISSUE THREAD

**Issue by lovettchris** [microsoft/onnxruntime#8531]
**Describe the bug**
Ultra slow performance trying to create new LearningModelSession using a LearningModelDevice with LearningModelDeviceKind.Cpu on AMD Ryzen 9 CPU.

**Urgency**
just sample not working nicely, so it will turn away folks who want to evaluate the onnx runtime, like me.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 version 21H1 build 19043.1110
- ONNX Runtime installed from (source or binary): C:\Windows\System32\Windows.AI.MachineLearning.dll
- ONNX Runtime version: 1.0.2007.1310
- Python version: N/A
- Visual Studio version (if applicable): VS 2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory:

**To Reproduce**
- git clone https://github.com/microsoft/Windows-Machine-Learning.git 
- build and run Samples\Tutorial Samples\YOLOv4ObjectDetection
- The 257mb LearningModel loads quickly from disk
- new LearningModelSession gets stuck, seemingly forever.  I've left it 30 minutes, still nothing and no busy CPU either.

**Expected behavior**
The new LearningModelSession should be quick.

**Screenshots**
N/A.

**Additional context**
I did have to change the .csproj to make it build on my machine, I had to change the windows 10 SDK version to a version I have installed, from 10.0.18362.0 to a newer version 10.0.19041.0, and I had to change Microsoft.NETCore.UniversalWindowsPlatform from 6.2.10 to a newer version 6.2.12.

**Comment by lovettchris** [comment]
Oh, just discovered the new LearningModelSession is throwing an exception saying:
```
The parameter is incorrect.

Failed to load model with error: Unknown model file format version.
```

**Comment by edgchen1** [comment]
Hi @lovettchris, I see you opened another issue: https://github.com/microsoft/Windows-Machine-Learning/issues/404
That's probably a good place for issues with that sample. Will close this one.

**Comment by lovettchris** [comment]
agreed, turns out the sample has a version of the .onnx model that only works on windows 11.
