### ISSUE TITLE
installation instructions links to wrong URL for "built from source"

### ISSUE THREAD

**Issue by garymm** [microsoft/onnxruntime#8534]
The current version of <https://www.onnxruntime.ai/docs/how-to/install.html>, "built from source" links to <https://www.onnxruntime.ai/docs/how-to/build.md>, which leads nowhere: "You've reached a page that doesn't exist. If you feel like something should be there, please open an issue on GitHub."

**Comment by faxu** [comment]
Thanks! I'll fix it. The correct link is: https://www.onnxruntime.ai/docs/how-to/build/inferencing.html

**Comment by natke** [comment]
Fixed by #14329
