### ISSUE TITLE
invalid HTTPS certificate on https://onnxruntime.ai

### ISSUE THREAD

**Issue by garymm** [microsoft/onnxruntime#8535]
Navigating to <https://onnxruntime.ai> triggers errors in Edge and Chrome:
`This server could not prove that it is onnxruntime.ai; its security certificate is from www.github.com. This may be caused by a misconfiguration or an attacker intercepting your connection.`

I think the HTTPS configuration on the GitHub pages repo needs to be changed to support the domain onnxruntime.ai, not just the existing www.onnxruntime.ai.

**Comment by prasanthpul** [comment]
Thanks to @natke the configuration should be fixed now. Please re-open if you still encounter any issue
