### ISSUE TITLE
Attempt to use the DefaultLogger but none has been registered, problem of "Microsoft.ML.OnnxRuntime.Gpu" in c#

### ISSUE THREAD

**Issue by BrutalHex** [microsoft/onnxruntime#8545]
**Describe the bug**
when I want to use the MakeSessionOptionWithCudaProvider notion I get the below error. I have an Nvidia graphic card with Cuda . the whole project works well with CPU but when it comes to using the  GPU, I get the below exception:

> Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:RuntimeException] /onnxruntime_src/include/onnxruntime/core/common/logging/logging.h:313 static const onnxruntime::logging::Logger& onnxruntime::logging::LoggingManager::DefaultLogger() Attempt to use DefaultLogger but none has been registered.
> at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
> at Microsoft.ML.OnnxRuntime.SessionOptions.MakeSessionOptionWithCudaProvider(Int32 deviceId)

**System information**
-  container **mcr.microsoft.com/azureml/onnxruntime:latest-cuda**
- ASP.net core 5.0
- Onnx nuget package Microsoft.ML.OnnxRuntime.Gpu 1.8.1

**To Reproduce**
` using (var option = SessionOptions.MakeSessionOptionWithCudaProvider(0)  )
                    {
                        var modelbyte = File.ReadAllBytes(pathToModel);
                        using (var session = new InferenceSession(modelbyte, option))
                      {
                                      var inputs = new List<NamedOnnxValue>();
                                        session.Run(inputs)
                     }
}
`

**Expected behavior**
to not throwing an exception or at least something meaning full.

**Additional context**
I have "Microsoft.ML.OnnxRuntime.Gpu" Version  "1.8.1" and also I have checked the 
existence of these dlls  at the output : onnxruntime_providers_cuda.dll , onnxruntime_providers_shared.dll
I have copied onnxruntime.dll too but it did not work.
we have another code based on python and it works great with the same docker image. 
something is wrong with c# Microsoft.ML.OnnxRuntime.Gpu code.
there is only one  GPU

![b1](https://user-images.githubusercontent.com/22192883/127477161-cb36b3f1-580f-433e-bf08-003775daf23b.png)

**Comment by snnn** [comment]
Can you try if this works: https://gist.github.com/pranavsharma/939d93fc7291c5a1638bfa3b190d72e3 ?

**Comment by snnn** [comment]
To debug the problem, please set up a break point at: 
https://github.com/microsoft/onnxruntime/blob/94c54718fbf2a6e0fbb5ce4cfcf43c5a056be2b7/csharp/src/Microsoft.ML.OnnxRuntime/OnnxRuntime.cs#L57

The function should be called before "SessionOptions.MakeSessionOptionWithCudaProvider" was made.

**Comment by BrutalHex** [comment]
thanks @snnn , which function should be called before "SessionOptions.MakeSessionOptionWithCudaProvider"  ?

**Comment by BrutalHex** [comment]
> Can you try if this works: https://gist.github.com/pranavsharma/939d93fc7291c5a1638bfa3b190d72e3 ?

when I replace **MakeSessionOptionWithCudaProvider** with  **option.AppendExecutionProvider_CUDA(gpuId);**  it throws an exception **OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library.**
I'm wondering that the  _Microsoft.ML.OnnxRuntime.Gpu 1.8.1_ nuget is not compatible with _mcr.microsoft.com/azureml/onnxruntime:latest-cuda_

**Comment by snnn** [comment]
When it said "Failed to load shared library", do you know it failed to load which library? 

Why we are talking dlls when this is a Linux docker? 

> I'm wondering that the Microsoft.ML.OnnxRuntime.Gpu 1.8.1 nuget is not compatible with

True.
"mcr.microsoft.com/azureml/onnxruntime:latest-cuda" is old and stopped having updates. You need to build the image from source from https://github.com/microsoft/onnxruntime/tree/master/dockerfiles .

**Comment by BrutalHex** [comment]
the problem is that , it does not say which share library is missing , but the cuda files are there as far as I have checked .
we are talking a bout dlls because we are publishing a .net core alication in a Linux machine and the nuget package "Microsoft.ML.OnnxRuntime.Gpu" has been produced by csharp project of microsoft/onnxruntime repository .

**Comment by BrutalHex** [comment]
I guess the best option is to build them using https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/docker/Dockerfile.ubuntu_gpu_training
but it has a line that I don't know what to put for the required argument:
/onnxruntime/tools/ci_build/github/linux/docker/scripts/install_python_deps.sh -p $PYTHON_VERSION -d gpu $INSTALL_DEPS_EXTRA_ARGS 
what should be the value of of INSTALL_DEPS_EXTRA_ARGS

**Comment by aorgish** [comment]
@BrutalHex , I had the same issue on fresh debian with cuda 11.4 installed.
To check missed dependencies run:
```
ldd libonnxruntime_providers_cuda.so | grep "not found" 
        libcudnn.so.8 => not found
```
```
ldd libonnxruntime_providers_shared.so | grep "not found"
```
In my case cudnn was not installed. 
1) Follow the instructions to install (cudnn 8.2.2 required for cuda 11.4) : https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-linux
2) set path using `export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH.`

In my case problem was fixed.

**Comment by BrutalHex** [comment]
thanks, @aorgish , after adding libonnxruntime_providers_cuda.so and libonnxruntime_providers_shared.so to $PATH the code runs on **GPU** but I got a new exception which **does not happen when I'm using CPU**, 

"[ErrorCode:Fail] Non-zero status code returned while running FusedConv node.
   Name:'Conv_118_Relu_119' Status Message: CUDNN error executing cudnnFindConvolutionForwardAlgorithmEx( CudnnHandle(),
   s_.x_tensor, s_.x_data, s_.w_desc, s_.w_data, s_.conv_desc, s_.y_tensor, s_.y_data, 1, &algo_count, &perf, algo_search_workspace.get(), AlgoSearchWorkspaceSize)"
   ,"Data":{},"InnerException":null,"HelpLink":null,"Source":"Microsoft.ML.OnnxRuntime","HResult":-2146233088}

**Comment by BrutalHex** [comment]
finally, I got it to work with the right Cuda image. the onnxruntime 1.8.1 only works with this image : 
**nvidia/cuda:11.0.3-cudnn8-devel-ubuntu20.04**
These are the parts of the docker file that helps to get it working:

`ARG ASPNET_VERSION=5.0.8
ARG DOTNET_VERSION=5.0.8

FROM amd64/buildpack-deps:buster-curl as installer
ARG DOTNET_VERSION
ARG ASPNET_VERSION
RUN curl -SL --output dotnet.tar.gz https://dotnetcli.azureedge.net/dotnet/Runtime/$DOTNET_VERSION/dotnet-runtime-$DOTNET_VERSION-linux-x64.tar.gz \
    && dotnet_sha512='8789609f3039dca1d0dc19562f23bc9bfe5d513a2d10639a8a779afe7656447b7ee953f9a8d9d0b07ba6ca4a346770c0efb5a34e5240b5d355d4d8198220e9b1' \
    && echo "$dotnet_sha512  dotnet.tar.gz" | sha512sum -c - \
    && mkdir -p /dotnet \
    && tar -ozxf dotnet.tar.gz -C /dotnet \
    && rm dotnet.tar.gz

RUN curl -SL --output aspnetcore.tar.gz https://dotnetcli.azureedge.net/dotnet/aspnetcore/Runtime/$ASPNET_VERSION/aspnetcore-runtime-$ASPNET_VERSION-linux-x64.tar.gz \
    && aspnetcore_sha512='77c9854f2bc947675025a9489baec2587cc9ef95e3be9351060c0d64fe0cede3e9c1395fe700715df520f106dccda9a21f7d21981df70653c49fd20418dc385f' \
    && echo "$aspnetcore_sha512  aspnetcore.tar.gz" | sha512sum -c - \
    && tar -ozxf aspnetcore.tar.gz ./shared/Microsoft.AspNetCore.App \
    && rm aspnetcore.tar.gz

FROM nvidia/cuda:11.0.3-cudnn8-devel-ubuntu20.04 AS base
EXPOSE 5010:5010
ARG DOTNET_VERSION
ENV DOTNET_VERSION=$DOTNET_VERSION
ARG ASPNET_VERSION
ENV ASPNET_VERSION=$ASPNET_VERSION
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y libicu66 wget  libssl-dev
WORKDIR /app
COPY --from=installer ["/dotnet", "/usr/share/dotnet"]
RUN ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
RUN apt-get -qq update && apt-get install -y libicu-dev
RUN apt install unzip && \
    curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /vsdbg
COPY --from=installer ["/shared/Microsoft.AspNetCore.App", "/usr/share/dotnet/shared/Microsoft.AspNetCore.App"]`

and also 

`FROM build AS publish
RUN dotnet publish "YourProject.csproj" -c Debug -o /app/publish --runtime "linux-x64"
RUN cp /app/build/runtimes/win-x64/native/onnxruntime.dll /app/publish
RUN mkdir -p /onnx
RUN cp /app/build/runtimes/linux-x64/native/* /onnx/

FROM base AS final
ENV PATH "$PATH:/onnx"
ENV LD_LIBRARY_PATH "$LD_LIBRARY_PATH:/onnx"
WORKDIR /app
COPY --from=publish /app/publish .
RUN mkdir -p /onnx
COPY --from=publish /onnx/ /onnx/
RUN export PATH=/onnx/:$PATH
RUN export LD_LIBRARY_PATH=/onnx/:$LD_LIBRARY_PATH
ENTRYPOINT ["dotnet", "YourProject.dll"]`

**Comment by s-trooper** [comment]
help, i got same error on windows.
```
[ErrorCode:RuntimeException] D:\a\_work\1\s\include\onnxruntime\core/common/logging/logging.h:313 onnxruntime::logging::LoggingManager::DefaultLogger Attempt to use DefaultLogger but none has been registered.
```
i've installed CUDA 10.2 and this package
```
Install-Package Microsoft.ML.OnnxRuntime.Gpu -Version 1.8.1
```
and my code is simple as this
```c#
using Microsoft.ML.OnnxRuntime;

namespace nav_net
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var options = new SessionOptions();
            options.AppendExecutionProvider_CUDA(0);
        }
    }
}
```

**Comment by nhannt95** [comment]
Hello @BrutalHex , I had same issue, Please help me~~
When I run:
var so = SessionOptions.MakeSessionOptionWithCudaProvider(0);
                so.LogSeverityLevel = OrtLoggingLevel.ORT_LOGGING_LEVEL_VERBOSE;
                _inferenceSession = new InferenceSession(weights, so);
Error:
[ErrorCode:RuntimeException] D:\a\_work\1\s\include\onnxruntime\core/common/logging/logging.h:313 onnxruntime::logging::LoggingManager::DefaultLogger Attempt to use DefaultLogger but none has been registered.

system information
Win 10
Cuda 11.4
CudNN 8.2.2
Microsoft.ML.OnnxRuntime.Gpu 1.9

**Comment by kyle99978** [comment]
Hello @BrutalHex
 I had the same bug, Please help me~~
2022-03-28 18:51:05.2605764 [E:onnxruntime:, sequential_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Conv node. Name:'892_nchwc' Status Message: D:\a\_work\1\s\include\onnxruntime\core/common/logging/logging.h:313 onnxruntime::logging::LoggingManager::DefaultLogger Attempt to use DefaultLogger but none has been registered.

**Comment by snnn** [comment]
You got this error message because OrtCreateEnv had not been invoked. 

https://github.com/microsoft/onnxruntime/blob/master/csharp/src/Microsoft.ML.OnnxRuntime/NativeMethods.shared.cs#L259
https://github.com/microsoft/onnxruntime/blob/master/csharp/src/Microsoft.ML.OnnxRuntime/OnnxRuntime.shared.cs#L57

So, please try to read the source code and set a breakpoint there. Create a new issue if you think you have called the function but it doesn't work as expected.

**Comment by BrutalHex** [comment]
> Hello @BrutalHex I had the same bug, Please help me~~ 2022-03-28 18:51:05.2605764 [E:onnxruntime:, sequential_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Conv node. Name:'892_nchwc' Status Message: D:\a_work\1\s\include\onnxruntime\core/common/logging/logging.h:313 onnxruntime::logging::LoggingManager::DefaultLogger Attempt to use DefaultLogger but none has been registered.
> 
> win11 cpu onncruntime 1.9.0

 I have placed the dockerfile , just run that dockerfile on your machine

**Comment by DonggiGwak** [comment]
I also experienced the same. But I solved it like this

Delete all C# executables
ex) C# bin\x64\Debug

onnxruntime nuget 1.10.0 (last version 1.11.0 not wroking)
CUDA 11.4
cudnn 11.4 win64 v8.2.2.26

You need to pay attention to version compatibility.
