### ISSUE TITLE
Static library usage

### ISSUE THREAD

**Issue by paper1235** [microsoft/onnxruntime#8555]
Hello,

I was wondering if it's possible to create a single static library to use for inference in cpp? I'm currently working with mlperf-cpp and have been trying to combine the static libraries to 1 static library, but it hasn't been successful. 

I also looked at this issue: https://github.com/microsoft/onnxruntime/issues/1472 , but some of the files in question are deleted and/or are related to windows, and I have to use Linux. 

Is there anyway to create a static library to use, or a way to use the static libraries individually to do inference?

Thanks!

**Comment by snnn** [comment]
onnxruntime depends on onnx. How would you handle onnx? The same question to ONNX. it's possible to create a single static library for ONNX? How will you install it and locate it?  Please let us more about your plan.

**Comment by paper1235** [comment]
I'm not too familiar with onnx, so I'm not sure if this is what you're looking for, but I've built onnxruntime for cpp, and am trying to use that. Could you clarify a bit further what you mean please?

**Comment by snnn** [comment]
Onnx runtime depends on some other libraries like onnx/protobuf/... . If we provided onnx runtime as a static library, you will still need these extra libraries to use. Here we have two choices:

1. onnxruntime distribute these third party libraries together within the same package. A drawback is we will force you using the versions we provide. You can't use a different version of onnx or protobuf. Generally speaking, I don't see people do this.  If your system has already installed protobuf, and we tried to provide a different on and override it ,...  It sounds dangerous.

2. onnxruntime  asks you get the third party libraries from somewhere and install it into your system. For example, you can get protobuf from  'apt-get' .  ONNX users can install onnx by:
```bash
apt-get install python3-pip python3-dev libprotobuf-dev protobuf-compiler
export CMAKE_ARGS="-DONNX_USE_PROTOBUF_SHARED_LIBS=ON"
pip install ...
```

But, when the problem comes to onnxruntime, we can't get ONNX from apt-get install. And there is no formal way to **install** ONNX as a C/C++ library. Second, onnxruntime depends on a beta version of eigen. You can't get it from any package manager. Though you still can install it manually. 

Theoretically it is possible to provide onnxruntime as a static library, but it's hard to use it correctly.

**Comment by goksinan** [comment]
If anyone interested in linking onnxruntime staticly on Windows, here are the steps I followed:
- Download onnxruntime (e.g. in C:\Software)
```
 git clone --recursive https://github.com/Microsoft/onnxruntime
 cd onnxruntime
```
- Build onnxruntime w/o the shared library option (as suggested in #1472)
`.\build.bat --config Release --parallel`

This will create all required `.lib` files into the build folder. Note that there is no `onnxruntime.lib`. In your application, you just need to link multiple libraries that onnxrunime uses.

- I used CMake to create a test application. In CMakeLists.txt file, add the following:
```
target_include_directories(
    ${PROJECT_NAME} PRIVATE 
    C:/Software/onnxruntime/include/onnxruntime
)

target_link_directories(
    ${PROJECT_NAME} PRIVATE
    C:/Software/onnxruntime/build/Windows/Release
)

target_link_libraries(
    ${PROJECT_NAME}
    Release/onnxruntime_session
    Release/onnxruntime_optimizer
    Release/onnxruntime_providers
    Release/onnxruntime_util
    Release/onnxruntime_framework
    Release/onnxruntime_graph
    Release/onnxruntime_mlas
    Release/onnxruntime_common
    Release/onnxruntime_flatbuffers
    Release/onnx_test_data_proto
    external/onnx/Release/onnx
    external/onnx/Release/onnx_proto
    external/protobuf/cmake/Release/libprotobuf-lite
    external/re2/Release/re2
    external/abseil-cpp/absl/base/Release/absl_base
    external/abseil-cpp/absl/base/Release/absl_throw_delegate
    external/abseil-cpp/absl/container/Release/absl_raw_hash_set
    external/abseil-cpp/absl/hash/Release/absl_hash
    external/abseil-cpp/absl/hash/Release/absl_city
    external/abseil-cpp/absl/hash/Release/absl_low_level_hash
)
```
- Finally, include the .h file in your main.cpp:
`#include "core/session/onnxruntime_cxx_api.h"`

**Comment by WilliamTambellini** [comment]
Same idea on Linux except that could be needed:
```
--cmake_extra_defines CMAKE_POSITION_INDEPENDENT_CODE=ON
```

**Comment by Eunsolfs** [comment]
> If anyone interested in linking onnxruntime statically on Windows, here are the steps I followed:
> 
> * Download onnxruntime (e.g. in C:\Software)
> 
> ```
>  git clone --recursive https://github.com/Microsoft/onnxruntime
>  cd onnxruntime
> ```
> 
> * Build onnxruntime w/o the shared library option (as suggested in [How to build and use onnxruntime static lib on windows?  #1472](https://github.com/microsoft/onnxruntime/issues/1472).
>   `.\build.bat --config Release --parallel`
> 
> This will create all required `.lib` files into the build/config folder you specified. Note that there is no `onnxruntime.lib`. In your application, you just need to link multiple libraries that onnxrunime uses.
> 
> * I used CMake to create a test application. In CMakeLists.txt file, add the following:
> 
> ```
> target_include_directories(
>     ${PROJECT_NAME} PRIVATE 
>     C:/Software/onnxruntime/include/onnxruntime
> )
> 
> target_link_directories(
>     ${PROJECT_NAME} PRIVATE
>     C:/Software/onnxruntime/build/Windows/Release
> )
> 
> target_link_libraries(
>     ${PROJECT_NAME}
>     Release/onnxruntime_session
>     Release/onnxruntime_optimizer
>     Release/onnxruntime_providers
>     Release/onnxruntime_util
>     Release/onnxruntime_framework
>     Release/onnxruntime_graph
>     Release/onnxruntime_mlas
>     Release/onnxruntime_common
>     Release/onnxruntime_flatbuffers
>     Release/onnx_test_data_proto
>     external/onnx/Release/onnx
>     external/onnx/Release/onnx_proto
>     external/protobuf/cmake/Release/libprotobuf-lite
>     external/re2/Release/re2
>     external/abseil-cpp/absl/base/Release/absl_base
>     external/abseil-cpp/absl/base/Release/absl_throw_delegate
>     external/abseil-cpp/absl/container/Release/absl_raw_hash_set
>     external/abseil-cpp/absl/hash/Release/absl_hash
>     external/abseil-cpp/absl/hash/Release/absl_city
>     external/abseil-cpp/absl/hash/Release/absl_low_level_hash
> )
> ```
> 
> * Finally, include the .h file in your main.cpp:
>   `#include "core/session/onnxruntime_cxx_api.h"`

hello sir I am learning how to build a static onnxruntime lib (MT), i tried your codes ".\build.bat --config Release --parallel" 
but the project still build in a shared dll mode.   So  can you give me  some help?  I really need yours help! THANKS A LOT!

**Comment by Eunsolfs** [comment]
thank you!



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/15/2022 15:43 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [microsoft/onnxruntime] Static library usage (#8555) |

If anyone interested in linking onnxruntime statically on Windows, here are the steps I followed:

Download onnxruntime (e.g. in C:\Software)
 git clone --recursive https://github.com/Microsoft/onnxruntime

 cd onnxruntime


Build onnxruntime w/o the shared library option (as suggested in How to build and use onnxruntime static lib on windows?  #1472.
.\build.bat --config Release --parallel

This will create all required .lib files into the build/config folder you specified. Note that there is no onnxruntime.lib. In your application, you just need to link multiple libraries that onnxrunime uses.

I used CMake to create a test application. In CMakeLists.txt file, add the following:
target_include_directories(

    ${PROJECT_NAME} PRIVATE 

    C:/Software/onnxruntime/include/onnxruntime

)



target_link_directories(

    ${PROJECT_NAME} PRIVATE

    C:/Software/onnxruntime/build/Windows/Release

)



target_link_libraries(

    ${PROJECT_NAME}

    Release/onnxruntime_session

    Release/onnxruntime_optimizer

    Release/onnxruntime_providers

    Release/onnxruntime_util

    Release/onnxruntime_framework

    Release/onnxruntime_graph

    Release/onnxruntime_mlas

    Release/onnxruntime_common

    Release/onnxruntime_flatbuffers

    Release/onnx_test_data_proto

    external/onnx/Release/onnx

    external/onnx/Release/onnx_proto

    external/protobuf/cmake/Release/libprotobuf-lite

    external/re2/Release/re2

    external/abseil-cpp/absl/base/Release/absl_base

    external/abseil-cpp/absl/base/Release/absl_throw_delegate

    external/abseil-cpp/absl/container/Release/absl_raw_hash_set

    external/abseil-cpp/absl/hash/Release/absl_hash

    external/abseil-cpp/absl/hash/Release/absl_city

    external/abseil-cpp/absl/hash/Release/absl_low_level_hash

)


Finally, include the .h file in your main.cpp:
#include "core/session/onnxruntime_cxx_api.h"

hello sir I am learning how to build a static onnxruntime lib (MT), i tried your codes ".\build.bat --config Release --parallel" but the project still build in a shared dll mode. So can you give me some help? I really need yours help! THANKS A LOT!

try build with --enable_msvc_static_runtime#1472

**Comment by RaiAmanRai** [comment]
can you guys please share the exact command to bulid ststic library of onnxruntime for linux.
also, if you could share a sample CMakeLists.txt, to test it out, would be really appreciable!

Thanks

**Comment by csukuangfj** [comment]
For those of you who are interested in static libraries of onnxruntime, please have a look at
https://github.com/csukuangfj/onnxruntime-libs/releases

For instance, if you want to have static onnxruntime lib for windows, please use

https://github.com/csukuangfj/onnxruntime-libs/releases/download/v1.16.0/onnxruntime-win-x86-static_lib-1.16.0.tar.bz2
https://github.com/csukuangfj/onnxruntime-libs/releases/download/v1.16.0/onnxruntime-win-x64-static_lib-1.16.0.tar.bz2

It contains a single onnxruntime.lib for windows, and a single libonnxruntime.a for macOS/Linux.

**Comment by snnn** [comment]
I will close this issue because the feature is not in our roadmap. I do not see a good way to distribute static libraries. Anyone who are interested in using ONNX Runtime as a static library please build it from source by yourself, or consider alternative 3rd-party solutions. For example, a lot of C/C++ package managers or Linux package managers have integrated ONNX Runtime.  You can get ONNX Runtime and its dependencies from the same place. I think that is better.

**Comment by abdullahaygun** [comment]
> For those of you who are interested in static libraries of onnxruntime, please have a look at https://github.com/csukuangfj/onnxruntime-libs/releases
> 
> For instance, if you want to have static onnxruntime lib for windows, please use
> 
> https://github.com/csukuangfj/onnxruntime-libs/releases/download/v1.16.0/onnxruntime-win-x86-static_lib-1.16.0.tar.bz2 https://github.com/csukuangfj/onnxruntime-libs/releases/download/v1.16.0/onnxruntime-win-x64-static_lib-1.16.0.tar.bz2
> 
> It contains a single onnxruntime.lib for windows, and a single libonnxruntime.a for macOS/Linux.


Hello, I am building the onnxruntime library statically, but when I link the .a files it does not work. The build in your repo consists of a single file. Can you share the code to build Linux-x86_64?
My build code: 
`./build.sh --config=MinSizeRel --update --build --parallel --minimal_build --disable_ml_ops --disable_exceptions --disable_rtti --enable_reduced_operator_type_support --skip_tests --allow_running_as_root --cmake_extra_defines CMAKE_INSTALL_PREFIX=prefix --cmake_extra_defines CMAKE_POSITION_INDEPENDENT_CODE=ON`

(NOTE: When I build statically, the files in the image below are created.)
![image](https://github.com/microsoft/onnxruntime/assets/81816237/4bfa95a3-56ce-4971-914a-133909932aec)

**Comment by olilarkin** [comment]
here is another ort-static lib builder project that i made: https://github.com/olilarkin/ort-builder

**Comment by csukuangfj** [comment]
> The build in your repo consists of a single file. Can you share the code to build Linux-x86_64?

@moondayyy 

Please see
https://github.com/csukuangfj/onnxruntime-build/blob/main/.github/workflows/linux.yaml

**Comment by rojvv** [comment]
It's interesting to me that to this day there's no officially supported way to do this. I believe that this issue should be reopened. There are just too many use cases for this.

**Comment by WilliamTambellini** [comment]
I would agree this issue should be reopened. Using onnxrt statically is one of the main advantage of onnxrt compared to its competitors (pytorch, trt, trtllm, ...). Without that feature, the appeal of onnxrt is thiner and thiner.

**Comment by snnn** [comment]
I have a draft example that uses vcpkg to manage the dependencies. VCPKG enforces that every lib only has one version, and it supports static linking.  I will open source it when I finish the current work.
