### ISSUE TITLE
Wrong inference result on onnxruntime-gpu, but onnxruntime result is correct.

### ISSUE THREAD

**Issue by shyTNT** [microsoft/onnxruntime#8580]
Hi guys，

I'm working on converting transformer(encoder part) model to onnx and then using onnxruntime to do inferencing. When I use onnxruntime(cpu version), I can get the same result with pytorch model for the same input, but longer duration. So I refer to onnxruntime-gpu. But when I uninstall onnxruntime and install onnxruntime-gpu, I got different wrong result. 

**System information**
- OS Platform and Distribution : Debian GNU/Linux 10
- ONNX Runtime installed from (source or binary): pip3 install onnxruntime/pip3 install onnxruntime-gpu
- ONNX Runtime version: 1.8
- Python version: 3.8
- CUDA/cuDNN version: 11.1/8.2

**To Reproduce**
My encoder model consists of one conv layer and then serveral self-attention blocks just like transformer structure. onnxruntime can output correct result while onnxruntime-gpu can't. They used the same onnx model converted from the original pytorch model.

I googled but didn't find a good explanation.  Could you please check this issue?

**Comment by edgchen1** [comment]
Would it be possible to share the model or provide more detailed steps to reproduce the issue?

**Comment by shyTNT** [comment]
> Would it be possible to share the model or provide more detailed steps to reproduce the issue?

session_options = onnxrt.SessionOptions()
session_options.enable_profiling = True

 encoder_session = onnxrt.InferenceSession('transformer.encoder.onnx', session_options)

Same code for onnxruntime and onnxruntime-gpu, different result in inferencing.

**Comment by edgchen1** [comment]
> > Would it be possible to share the model or provide more detailed steps to reproduce the issue?
> 
> ```
> > session_options = onnxrt.SessionOptions()
> > session_options.enable_profiling = True
> > 
> >  encoder_session = onnxrt.InferenceSession('transformer.encoder.onnx', session_options)
> ```
> 
> Same code for onnxruntime and onnxruntime-gpu, different result in inferencing.

Thanks. Could you also share the model?
