### ISSUE TITLE
Dynamic Input Reshape Incorrect

### ISSUE THREAD

**Issue by peiwenhuang27** [microsoft/onnxruntime#8591]
**Describe the bug**
I have a trained Tensorflow model that has two inputs:
> input0 shape: (64, 60, 257)
> input1 shape: (64, 257, 60, 1)

Then I converted it to ONNX model via [tf2onnx](https://github.com/onnx/tensorflow-onnx) with the command
```
# keras model
!python -m tf2onnx.convert \
--saved-model ./model/myModel \
--opset 11 \
--output ./model/myModel.onnx
```
and use it for inference with dynamic input shape by the following code:
```
model = onnx.load(ONNX_PATH)
# input0: 64, 60, 257 -> N, N, 257
# input1: 64, 257, 60, 1 -> N, 257, N, 1

model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = '?'
model.graph.input[0].type.tensor_type.shape.dim[1].dim_param = '?'
model.graph.input[1].type.tensor_type.shape.dim[0].dim_param = '?'
model.graph.input[1].type.tensor_type.shape.dim[2].dim_param = '?'

ONNX_PATH = './model/dynamicModel.onnx'
onnx.save(model, ONNX_PATH)
```
My inference code:
```
so = onnxruntime.SessionOptions()
so.graph_optimization_level = onnxruntime.GraphOptimizationLevel.ORT_DISABLE_ALL
ort_session = onnxruntime.InferenceSession(ONNX_PATH, sess_options=so)
ort_session.set_providers(['CPUExecutionProvider'])
# run inference
preds = ort_session.run([output_name], {input_name0: x[:32], input_name1: x_norm[:32]})
```
If I pass inputs as (64, 60, 257) and (64, 257, 60, 1), the session runs fine.
But when I tried to pass inputs shaped as (32, 60, 257) and (32, 257, 60, 1), I get the following error:
```
RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. 
Name:'StatefulPartitionedCall/model/1/Conv2D__36' 
Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:42 
onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. 
The input tensor cannot be reshaped to the requested shape. Input shape:{32,257,60,1}, requested shape:{64,1,257,60}
```

**Urgency**
I'm trying to keep up with my project deadline on Aug. 13.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.6.0
- Python version: 3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.
- [model link](https://drive.google.com/file/d/1kvUfHFJNYorUcJLVwNKcy1a8bJ1I6pZd/view?usp=sharing)

**Expected behavior**
The error occurs in the first operation `Reshape` as shown in this picture
<img width="1018" alt="Screen Shot 2021-08-03 at 11 31 36" src="https://user-images.githubusercontent.com/45028573/127953390-09e0c715-d3e5-4b1c-ab1c-7bf6c9cb931e.png">
The reshape op is supposed to reshape input of (64, 257, 60, 1) into (64, 1, 257, 60).
But the error message says `Input shape:{32,257,60,1}, requested shape:{64,1,257,60}`, which means the tensor was not reshaped correctly.

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by TomWildenhain-Microsoft** [comment]
Hey @peiwenhuang27 your can't just change the input shape by modifying the graph like that once it is converted.  There can be many ops within the graph that depend on the input shape matching what was initially declared.  You'll need to override the shape before converting to onnx.  Can you edit the tf model signature?  You can also override the shape with tf2onnx's --input flag   use -1 to indicate unknown dims

**Comment by peiwenhuang27** [comment]
Hi @TomWildenhain-Microsoft thanks for the reply! Sorry for my ignorance, but when I used the input flag `--inputs input0[-1,-1,257],input1[-1,257,-1,1]` to try to override the input shape, tf2onnx seems to have run successfully, part of the log looks like this:
```
2021-08-04 01:34:39,191 - INFO - Using tensorflow=2.5.0, onnx=1.10.1, tf2onnx=1.9.1/8e8c23
2021-08-04 01:34:39,191 - INFO - Using opset <onnx, 11>
2021-08-04 01:34:39,192 - INFO - Apply shape override:
2021-08-04 01:34:39,192 - INFO - 	Set input_noisy:0 shape to [None, None, 257]
2021-08-04 01:34:39,192 - INFO - 	Set input_noisy_norm:0 shape to [None, 257, None, 1]
2021-08-04 01:34:41,986 - INFO - Computed 0 values for constant folding
2021-08-04 01:34:47,385 - INFO - Computed 0 values for constant folding
2021-08-04 01:34:47,395 - INFO - Computed 0 values for constant folding
2021-08-04 01:34:47,417 - INFO - Computed 0 values for constant folding
2021-08-04 01:34:47,425 - INFO - Computed 0 values for constant folding
2021-08-04 01:34:47,640 - INFO - Optimizing ONNX model
```
Then I tried to load the model and print the input shapes:
```
dim {
  dim_param: "unk__89"
}
dim {
  dim_param: "unk__90"
}
dim {
  dim_value: 257
}

dim {
  dim_param: "unk__91"
}
dim {
  dim_value: 257
}
dim {
  dim_param: "unk__92"
}
dim {
  dim_value: 1
}
```
It looks ok, but when running it still shows the same error message as I attached in the previous comment.

**Comment by TomWildenhain-Microsoft** [comment]
In that case then unfortunately the TF model already has propagated the shape information through the graph and applied optimizations based on those assumptions.  Are you able to run the original TF graph on the input that you want?  It is also possible that the model is only trained for inputs of that shape, so it wouldn't work on other sizes.  You can always add a resize node at the top of the graph.  If you have any fully connected layers, those will only work on a specific shape.  What is the type of input data? images? audio?

**Comment by peiwenhuang27** [comment]
I initialized the TF graph with static input shapes, and intended to convert them to dynamic when using tf2onnx.
On the other hand, may I ask what you mean by adding a resize node at the top of the graph?

Also:
> If you have any fully connected layers, those will only work on a specific shape.

Does this mean I cannot train my model with a certain shape, then inference it with another shape? My use case is training the model with (64, 60, 257), (64, 257, 60, 1), and at inference time the data will be shaped as (1, 60, 1), (1, 257, 1, 1). The first dimension is batch size, which is then set to 1 for inference purpose. Because they are audio data, so the third dimension is related to the time sequence length, which cannot be set to the same as during training time.

**Comment by TomWildenhain-Microsoft** [comment]
> I initialized the TF graph with static input shapes, and intended to convert them to dynamic when using tf2onnx.

Yes, that will not work.  If you want the shape to be dynamic, you must declare it as such initially.

> On the other hand, may I ask what you mean by adding a resize node at the top of the graph?

One solution for images of unknown sizes is to scale them to the correct size.  If your model only supports 200 x 200 pixel images, for example, you can do inference on images of other sizes by resizing the image first to 200 x 200.  There's an op in ONNX that does this called Resize.  TF has a corresponding op.  Add tf.image.resize to the top of the model.  https://www.tensorflow.org/api_docs/python/tf/image/resize.  However this only works well for images.  The stretched/resized audio won't have the same properties.

> Does this mean I cannot train my model with a certain shape, then inference it with another shape? My use case is training the model with (64, 60, 257), (64, 257, 60, 1), and at inference time the data will be shaped as (1, 60, 1), (1, 257, 1, 1). The first dimension is batch size, which is then set to 1 for inference purpose. Because they are audio data, so the third dimension is related to the time sequence length, which cannot be set to the same as during training time.

Correct.  The batch size can vary, since it does not become one of the matrix dimensions in the fully connected layer, but the other dimension cannot change.  There are a number of methods in deep learning to deal with unknown lengths.  I think for audio you could do an rfft then a sequence of convolutional layers followed by a reduce mean.  You might be able to do a reshape as long as you do an rfft first, but I'm not a model architect.

https://towardsdatascience.com/audio-deep-learning-made-simple-part-1-state-of-the-art-techniques-da1d3dff2504

But these are all general ML questions not specific to tf2onnx/onnxruntime, so if you want more info I'd recommend looking up some common audio architectures.

**Comment by TomWildenhain-Microsoft** [comment]
@peiwenhuang27 I'm closing this issue.  If you have any problems with tf2onnx, please open an issue there.
