### ISSUE TITLE
Links to Vitis-AI Execution Provider information broken

### ISSUE THREAD

**Issue by ghweber** [microsoft/onnxruntime#8595]
The links to the Vitis-AI Execution Provider information on `https://onnxruntime.ai/docs/how-to/build/eps.html#vitis-ai` are broken. As far as I can tell the link `https://onnxruntime.ai/docs/how-to/reference/execution-providers/Vitis-AI-ExecutionProvider.md` should be `https://onnxruntime.ai/docs/reference/execution-providers/Vitis-AI-ExecutionProvider.html` instead and `https://onnxruntime.ai/docs/how-to/reference/execution-providers/Vitis-AI-ExecutionProvider.md#Hardware-setup` seems to be missing in the new version.

Also, the links to contribution information and guidelines also seem to be broken.

**Comment by faxu** [comment]
Thanks for reporting the issue. We moved some docs around and looks like these files were missed. I'll fix them. 

What link to contribution info/guidelines are you referring to?
