### ISSUE TITLE
module 'onnxruntime' has no attribute 'InferenceSession'

### ISSUE THREAD

**Issue by prabhuiitdhn** [microsoft/onnxruntime#8623]
**Describe the bug**
I have followed [https://onnxruntime.ai/docs/how-to/build/inferencing.html](this) to install/build onnxruntime for inference the onnx model; I wanted to add new custom operator for inference from onnx model (It contains _DCNv2 operator which is already being added in onnx ). But I am unable to load *onnxruntime.InferenceSession('model.onnx')*

**Urgency**
Please help me as soon as possible, I have an strict deadline for it.

**System information**
- Linux: 18.04 LTS
- ONNX Runtime installed from (source or binary): Yes
- ONNX Runtime version: 1.10.1
- Python version: 3.8
- Visual Studio version (if applicable): No
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 10.2
- GPU model and memory: Titan XP; 12192MiB

**To Reproduce**
```
Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime
>>> rts = onnxruntime.InferenceSession("/home/uidq6830/PycharmProjects/DEFT_inference/src/models/model_mot.onnx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'onnxruntime' has no attribute 'InferenceSession'
```

**Expected behavior**
onnxruntime should have InferenceSession

**Screenshots**

**Additional context**
The main reason of building ONNXRUNTIME from source is [https://github.com/microsoft/onnxruntime/issues/8436](this).

**Comment by snnn** [comment]
Please try to run the script in a different dir. For example: /tmp

**Comment by prabhuiitdhn** [comment]
Hi @snnn: Thank you for replying. I am sorry to say but It is not working. 

I do have environment named "deft4inference" and in this folder I have build onnxruntime and I am trying to run it on home directory but It is not working.

![image](https://user-images.githubusercontent.com/19517005/128459722-4a9788a1-f4d0-4a32-b89b-d9905a28c590.png)

Also, Just to know, I have to add new custom operator which is already customised in onnx, can I add/modify the custom operator in onnxruntime If I install through "pip install onnxruntime"?

**Comment by prabhuiitdhn** [comment]
Hi @snnn: I reinstall it using the following steps by following [this](https://onnxruntime.ai/docs/how-to/build/inferencing.html) link.

> git clone --recursive https://github.com/Microsoft/onnxruntime
> cd onnxruntime
> ./build.sh --use_cuda --cuda_version=10.2 --cuda_home=/usr/local/cuda-10.2 --cudnn_home=/usr/local/cuda-10.2 --config RelWithDebInfo --build_shared_lib --parallel

It passed 100% complete test.
100% tests passed, 0 tests failed out of 3

But I am not sure If this gives an error while building:

> 
> 1: 2021-08-06 16:01:25.467167505 [W:onnxruntime:Default, graph.cc:95 MergeShapeInfo] Error merging shape info for output. 'Y' source:{0,} target:{1,0}. Falling back to lenient merge.
> 1: 2021-08-06 16:01:25.467254768 [W:onnxruntime:NonZero, execution_frame.cc:761 VerifyOutputSizes] Expected shape from model of {0,} does not match actual shape of {1,0} for output Y
> 1: 2021-08-06 16:01:25.467322007 [W:onnxruntime:Default, graph.cc:95 MergeShapeInfo] Error merging shape info for output. 'Y' source:{0,} target:{1,1}. Falling back to lenient merge.
> 1: 2021-08-06 16:01:25.467401197 [W:onnxruntime:NonZero, execution_frame.cc:761 VerifyOutputSizes] Expected shape from model of {0,} does not match actual shape of {1,1} for output Y
> 
> 

If this is a successful installation then, why I am unable to import onnxruntime.InferenceSession?
I changed the source directory to run Python

> deft4inference) (base) uidq6830@ozd2283u:~/deft4inference/onnxruntime$ cd ..

> (deft4inference) (base) uidq6830@ozd2283u:~/deft4inference$ python

> Python 3.8.8 (default, Apr 13 2021, 19:58:26) 

> [GCC 7.3.0] :: Anaconda, Inc. on linux

> Type "help", "copyright", "credits" or "license" for more information.

> >>> import onnxruntime
> >>> import onnxruntime.InferenceSession
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'onnxruntime.InferenceSession'
> >>> import onnxruntime as rt
> >>> rt_s = rt.InferenceSession("/home/uidq6830/PycharmProjects/DEFT_inference/src/models/model_mot.onnx")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: module 'onnxruntime' has no attribute 'InferenceSession'

Any Help would be appreciated.

**Comment by snnn** [comment]
I got the same error:

![image](https://user-images.githubusercontent.com/856316/128532739-f5857352-5493-40c5-85f9-8db439d0d290.png)


"onnxruntime.InferenceSession" is not a module.  You don't need the second line.

**Comment by prabhuiitdhn** [comment]
@snnn:  Have you tried it?

> import onnxruntime as rt
> rt_s = rt.InferenceSession("/home/uidq6830/PycharmProjects/DEFT_inference/src/models/model_mot.onnx")
> print("Done..")

Please try to run it. See If this is working on your setup.

**Comment by prabhuiitdhn** [comment]
> I got the same error:
> 
> ![image](https://user-images.githubusercontent.com/856316/128532739-f5857352-5493-40c5-85f9-8db439d0d290.png)
> 
> "onnxruntime.InferenceSession" is not a module. You don't need the second line.

Hi @snnn: I have not fixed yet, It is still showing an error. Do you think I did mistake while building from source?
Follwoing steps:
Installation process:
```
>> created virtualenv deft4inference [created pyhton based virtualenvironment ]
>> source deft4inference/bin/activate [activated environment; Same "deft4inference" folder created at home directory]
>> cd deft4inference
>>  git clone --recursive https://github.com/Microsoft/onnxruntime [clone onnxruntime to deft4inference]
>> cd onnxruntime
>> ./build.sh --use_cuda --cuda_version=10.2 --cuda_home=/usr/local/cuda-10.2 --cudnn_home=/usr/local/cuda-10.2 --config RelWithDebInfo --build_shared_lib --parallel (build it) //it successfully built.
```

importing process:
```
current directory: onnxruntime
>>cd..
>>import onnxruntime as rt //It worked.
>>model = "model.onnx"
>>rts = rt.InferenceSession(model)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'onnxruntime' has no attribute 'InferenceSession'
```
I think I have installed it correctly but I am unable to understand why "InferenceSession" is giving an error?

**Comment by skottmckay** [comment]
It's not clear what output is coming from where in your "importing process:" information given `cd..` is not a valid python command.

Running `help(rt)` after `import onnxruntime as rt` will provide details of the onnxruntime module that was loaded so you can check it's coming from the expected location.

Your build command line didn't have `--build_wheel` so it would not be building the python wheel with the onnxruntime python module.

Once the build completes with that addition, to use the onnxruntime python package without installing it via something like pip you'd need to change to the build output directory (e.g. build/Linux/RelWithDebInfo). That should have an 'onnxruntime' directory for the python package, which will have subdirectories called capi, backend and quantization amongst others. When you run python from the build output directory 'import onnxruntime' will load from the local directory (i.e. running python from build/Linux/RelWithDebInfo will result in `import onnxruntime` loading from build/Linux/RelWithDebInfo/onnxruntime) . 

Alternatively you can install the whl (should be in build/Linux/RelWithDebInfo/dist after you build the wheel) and `import onnxruntime` should work from anywhere, provided there isn't a subdirectory called onnxruntime.

Note: if you run python from the top level of the onnxruntime repository you created with `git clone` when you do `import onnxruntime` it will attempt to read from the 'onnxruntime' directory there - but that's the root of the source code and not the python package so you'll get errors about missing things.

**Comment by prabhuiitdhn** [comment]
Hi @skottmckay, thank you so much for much awaited reply. I have followed [https://onnxruntime.ai/docs/how-to/build/inferencing.html](this) to install onnxruntime from source.

The steps are following:

>  git clone --recursive https://github.com/Microsoft/onnxruntime
>  cd onnxruntime
> ./build.sh --use_cuda --cuda_version=10.2 --cuda_home=/usr/local/cuda-10.2 --cudnn_home=/usr/local/cuda-10.2 --config RelWithDebInfo --build_shared_lib --parallel

But onnxruntime.InferenceSession(model.onnx) is not working.

Do i need to build using below command?

> ./build.sh --use_cuda --cuda_version=10.2 --cuda_home=/usr/local/cuda-10.2 --cudnn_home=/usr/local/cuda-10.2 --config RelWithDebInfo --build_shared_lib --parallel --build_wheel

**Comment by prabhuiitdhn** [comment]
Thank you so much @snnn and Much appreciated @skottmckay. Your one paragraph showed its magic and solved all problems/worries in a second. Thanks again, @skottmckay

**Comment by prabhuiitdhn** [comment]
@skottmckay: Can you please look into [https://github.com/microsoft/onnxruntime/issues/8635] (this problem too) I am working on it for last 5 days but have not solved it. It would be much appreciated If you look into this too. Thank you.

**Comment by Vashthareaper** [comment]
i wish there was a simple process to fix this for us plebs, i have no idea how to fix this error while running mimicmotion in comfyui
