### ISSUE TITLE
Non-zero status code returned while running Scaler node. Name:'Scaler' Status Message: D:\a\_work\1\s\include\onnxruntime\core/common/logging/logging.h:313 onnxruntime::logging::LoggingManager::DefaultLogger Attempt to use DefaultLogger but none has been registered.

### ISSUE THREAD

**Issue by Bhuvanamitra** [microsoft/onnxruntime#8624]
Hi,
I have trained a LightGBM classifier and converted the model into ONNX using these steps: http://onnx.ai/sklearn-onnx/auto_tutorial/plot_gexternal_lightgbm.html

I don't get any errors in converting and also while inferring in python. 
But, when I try to inference using C++, I get the above error which I stated in the Subject of this issue.

I have trained and converted another model using https://github.com/onnx/onnxmltools/blob/master/onnxmltools/convert/lightgbm/convert.py#L15 
this method and facing the same issue i.e, I can infer from that converted onnx model using python but not in C++

I am attaching my C++ inference code

Please, someone, help to resolve this. I am stuck here.
Thanks in Advance 

```c++
       Ort::Env env(ORT_LOGGING_LEVEL_WARNING, this->logid);
      
       Ort::SessionOptions session_options;
       session_options.SetIntraOpNumThreads(1);
       session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
  
       this->session = Ort::Session(env, model_path, session_options);        

        this->input_node_dims.at(0).at(0) = 1;
        this->input_tensor_size.at(0) = 1 * NUM_FEATURES;
        this->output_node_dims.at(0).at(0) = 1;
        this->output_tensor_size.at(0) = 1;
        
        vector<int64_t> output_vec(this->output_tensor_size.at(0));
        
        auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
        
        vector<Ort::Value> ip_tensors;
        ip_tensors.push_back(Ort::Value::CreateTensor<float>(
            memory_info, feature_vec.data(), this->input_tensor_size.at(0),
            this->input_node_dims.at(0).data(), this->input_node_dims.at(0).size()));
        
        vector<Ort::Value> op_tensors;
        op_tensors.push_back(Ort::Value::CreateTensor<int64_t>(
            memory_info, output_vec.data(), this->output_tensor_size.at(0),
            this->output_node_dims.at(0).data(), this->output_node_dims.at(0).size()));
        
        this->session.Run(Ort::RunOptions{ nullptr }, this->input_node_names.data(),
            ip_tensors.data(), this->num_input_nodes,
            this->output_node_names.data(), op_tensors.data(),
            this->num_output_nodes);
```

**Comment by snnn** [comment]
Please create a OrtEnv first. At the very beginning of "main".

**Comment by Bhuvanamitra** [comment]
Hi, Ort environment is created. I forgot to add that piece of code. But still, the error is there. Please look into this.

**Comment by snnn** [comment]
The information you gave me is not enough to reproduce or debug the error from my side.  So I can only give you some general suggestions:  There is only two reasons I can think of are:

1.   OrtEnv  was not created before the exception was thrown
2.   OrtEnv was created but has been destroyed before the exception was thrown

**Comment by Bhuvanamitra** [comment]
While I look into the suggestions you offered, I can share you the model if that helps in reproducing the error.

**Comment by snnn** [comment]
You may setup a breakpoint at the constructor/destructor of "Ort::Env" to see when they get called.  Is the constructor called before any other onnxruntime APIs?

**Comment by Bhuvanamitra** [comment]
Hi, Yes, the environment is created and it is the first thing I did before calling any other API from onnxruntime.
