### ISSUE TITLE
Padding effect quantizied ONNX quality

### ISSUE THREAD

**Issue by MoranMahabi** [microsoft/onnxruntime#8625]
**Describe the issue**
I’ve quantified ONNX model using quantize_dynamic function.
The accuracies of the ONNX model before quantiziation are the same as in the original Pytorch model (also with different padding), but the accuracies are different when I tested the quantified ONNX model on the same sentences but with different padding. My question: How padding effect quantizied ONNX quality?

**System information**
- OS Platform and Distribution: macOS Big Sur Version 11.4
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.8.1
- Python version: 3.7
- CPU model and memory: 2.3 GHz 8-Core Intel Core i9
- Memory: 32 GB 2667 MHz DDR4

**To Reproduce**
 1. load quantified ONNX model
 2. for each sentence padding sentence to specific max length and send it to the model

**Expected behavior**
Results:
<img width="635" alt="results" src="https://user-images.githubusercontent.com/37874078/128343775-5374696a-7741-4711-9740-241627d93adb.png">

I expected that quality (macro F) of quantified ONNX model will be the same for different padding max length like in Pytorch model and ONNX model. 

Thanks in advanced, 
Moran

**Comment by yufenglee** [comment]
@MoranMahabi, it is expected that quantization can introduce accuracy loss. It depends on the model how much accuracy loss there will be. You can try per-channel and reduce range and see if the option can improve the accuracy: https://onnxruntime.ai/docs/how-to/quantization.html#when-to-use-per-channel-and-reduce-range.

BTW, why do you do padding? OnnxRuntime/ONNX supports dynamic shape. Does it work for you case? Search dynamic_axes from https://pytorch.org/docs/stable/onnx.html if your original framework is PyTorch.

**Comment by MoranMahabi** [comment]
Thanks! 

I understand that quantization can introduce accuracy loss, but why accuracy is different with different padding on the same sentences?

I used padding since I want perform Batch inferencing as in [https://github.com/microsoft/onnxruntime/issues/8030](url).

**Comment by yufenglee** [comment]
So you are inferencing with multi-batch? As you are using dynamic quantization, the scale and zero point will be calculated dynamically with the whole batch data, so the scale and zero point will be different with different batch size. For an example, you have 2 different tensors [-2.f, 1.f], [-1.f, 2.f, 0.3f]. If you compute them one by one, the scales are 3.f/256 for both of them. If you compute them as batch, the scale will be 4.f/256, thus the result will be different with the cases that each sentence is computed one by one.

I don't see why the padding has impact on the accuracy though. Are you testing the result with random/different orders?

**Comment by MoranMahabi** [comment]
Thanks @yufenglee!

So, with multi-batch inferencing I should expect the results will be different if the batch size different in different runs?

Actually, in the results table above I computed the sentences one by one. I was interested in checking the running time per sentence but with different padding and I got different results. I didn't test the result with random/different orders, the order is the same order in different runs.

**Comment by yufenglee** [comment]
For batch [[-2.f, 1.f, 0.f], [-1.f, 2.f, 0.3f]], scale is computed with whole tensor, so it is (2-(-2))/256. So, yes, it is expected to get different results if batch size is different. 

If you are running sentences one by one, it is not caused by this. Could you share a set of input and model that can repro this issue?

**Comment by MoranMahabi** [comment]
Thanks!

I did some experiments. In the all experiment I run ONNX model and quantified ONNX model on the same 100 sentences, but I check in depth two sentences (the same sentences in all experiments):
1. The first sentence is with 38 tokens.
2. The second sentence is with 118 tokens.

**Experiment 1:** 
1. In both sentences, the results of ONNX model are the same with different padding (no padding, padding 118, padding 128, padding 512) - **as expected**. 
2. In both sentences, the results of quantified ONNX model are different with different padding (in the second sentence the results with no padding and padding 118 are the same since the number of tokens with no padding is 118) - **so maybe the padding affect on the results?**
3. The results of the first sentence are **different** with padding 128 and padding 512 with quantified ONNX model - if padding affect on the results, in this test should be the same results since the min_data_range and max_data_range are the same (128 > 38 and 512 > 38), but I got different results, so I think also the **position ids** of padding tokens affect on the results.


I the Experiment 2, Experiment 3, Experiment 4, I generated new ONNX model and new quantified ONNX model that got also position_ids as input. I used the same models in these experiments. 

**Experiment 2:** 
1. In both sentences, same results as in Experiment 1 - **as expected, since I send to model the default position_ids**. 

****Experiment 3:** send the same position_id to all padding tokens, for example [0,1,2,3,...,35,36,37,38,38,38,38,...,38]**
1. In both sentences, the results of ONNX model are the same with different padding (no padding, padding 118, padding 128, padding 512) - **as expected**. 
2. The results of the first sentence are different with no padding  and padding 118 with quantified ONNX model - as expected, if scale also dependent on padding weights. 
3. The results of the first sentence are the **same** with padding 128 and padding 512 with quantified ONNX model - as expected, if scale also dependent on padding weights and dependent on position embeddings weights - the min_data_range and max_data_range are the same (128 > 38 and 512 > 38). 



If this is not the expected behavior I will share the models and input example.

**Comment by yufenglee** [comment]
Yes, it is expected. I think if you always pad 0 for position_id and an ever existed token id for input_id, it will get same result as non-padding one.

**Comment by MoranMahabi** [comment]
I think so too.
Thank you @yufenglee!

**Comment by rohanshingade** [comment]
@MoranMahabi did you find a solution to run batch inference for quantized model? i tried batch inferencing, but results are varying

**Comment by MoranMahabi** [comment]
@rohanshingade, I run batch inference as in #8030. 

It is expected to get varying results if you test the results with random/different orders or different batch size as explained in https://github.com/microsoft/onnxruntime/issues/8625#issuecomment-894948296.
