### ISSUE TITLE
Why  ONNX Runtime Server has been deprecated?

### ISSUE THREAD

**Issue by li1191863273** [microsoft/onnxruntime#8655]
https://github.com/microsoft/onnxruntime/blob/master/docs/ONNX_Runtime_Server_Usage.md

This link note ONNX Runtime Server has been deprecated

Why deprecated?

How can I deploy onnxruntime like tf-serving?

**Comment by linkerzhang** [comment]
maybe use triton? which integrates ORT as a backend.

**Comment by li1191863273** [comment]
> maybe use triton? which integrates ORT as a backend.

But why  ONNX Runtime Server has been deprecated

**Comment by pranavsharma** [comment]
Triton is the recommended solution. We deprecated onnxruntime server in favor of other priorities. Triton is feature rich and fully supports onnxruntime.

**Comment by li1191863273** [comment]
https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html
I use this model in link in order to test performance

The  Result is:

pytorch cost 76.76434516906738ms, onnx runtime cost 12.56704330444336ms
tf_serving cost 411.729097366333ms
triton http cost 395.44177055358887ms, triton grpc cost 53.14993858337402ms

Triton is too slow compared with onnx runtime, So it seem Trition is not better solution.
