### ISSUE TITLE
c++ no constructor of instance "Ort:Session:Session" 

### ISSUE THREAD

**Issue by chwjshlwel** [microsoft/onnxruntime#8657]
**Describe the bug**
I build the onnxruntime newest version with cuda 11.3.1, cudnn 8.2, tensorrt 8.0.1.6, and it is done.
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows 10
- ONNX Runtime installed from (source or binary): git clone https://github.com/microsoft/onnxruntime
- ONNX Runtime version: newest version
- Python version:3.7
- Visual Studio version (if applicable):vs2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:11.3.1/8.2
- GPU model and memory: RTX 3080(10G)

**To Reproduce**
 
I use the follow c++ code:

   Ort::Env env(OrtLoggingLevel::ORT_LOGGING_LEVEL_WARNING,
        instanceName.c_str());
    Ort::Session session(env, modelFilepath.c_str(), sessionOptions);

but I got error:
E0289: no instance of constructor "Ort::Session::Session" matches the argument list 
 Please help me to solve this problem

**Comment by yuslepukhin** [comment]
The best way to see the arguments and the types required against what you supply. Check the path argument type. Your IDE might be helpful there.

**Comment by chwjshlwel** [comment]
thanks

**Comment by xuandu** [comment]
hello I have the same question
use   ort_session= new Session(null) is ok ;but I need  the paragram

**Comment by wimvanhenden-tool** [comment]
Hi everybody, I am facing the same issue:

![image](https://github.com/microsoft/onnxruntime/assets/125361595/b37a46c6-7ffe-4336-8f8e-46876cb98542)

I also tries using pointers but that result in a compile error:
![image](https://github.com/microsoft/onnxruntime/assets/125361595/d82e2829-f941-4d29-a664-e833034e4cee)

Thank you for your help,

Kind regeards

**Comment by sofienbensayadia** [comment]
> Hi everybody, I am facing the same issue:
> 
> ![image](https://private-user-images.githubusercontent.com/125361595/293391613-b37a46c6-7ffe-4336-8f8e-46876cb98542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjgwMTcsIm5iZiI6MTcwNzcyNzcxNywicGF0aCI6Ii8xMjUzNjE1OTUvMjkzMzkxNjEzLWIzN2E0NmM2LTdmZmUtNDMzNi04ZjhlLTQ2ODc2Y2I5ODU0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwODQ4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzVjZjljOTI3Nzk5NWMwMTlmMTk1MmU5N2ZiZTllN2I2ZDhjZGRhYmExMTgxZTE3NGI4NTk2YzgyZmQ2NzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gaPJxvrmbB5WZXmWsdiMUXeg9utEo4ddMYJoFeGIdCw)
> 
> I also tried using pointers but that result in a compile error: ![image](https://private-user-images.githubusercontent.com/125361595/293391661-d82e2829-f941-4d29-a664-e833034e4cee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjgwMTcsIm5iZiI6MTcwNzcyNzcxNywicGF0aCI6Ii8xMjUzNjE1OTUvMjkzMzkxNjYxLWQ4MmUyODI5LWY5NDEtNGQyOS1hNjY0LWU4MzMwMzRlNGNlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwODQ4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTIwZGM2NWRjODNjOTYyNDFkNzg1YWM4NjBjZTk1MjFlMWFhMTI1ODA3MzRlYzdhYzI5ZjE2Y2E0NTM1MDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f7vXfSzNILsug3td7UefECr6K80TtH94cEG6IfMWh9k)
> 
> Thank you for your help,
> 
> Kind regeards

Hi, I'm facing the same error. If you've resolved this problem, could you please share how? Thanks!

**Comment by OllyFawcett** [comment]
model_path needs to be const wchar_t* so you need to convert that like this:

bool initializeModel(const std::string& model_path) 
{
    Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "YOLOv7");
    Ort::SessionOptions options;
    std::wstring widestr = std::wstring(model_path.begin(), model_path.end());
    const wchar_t* widecstr = widestr.c_str();
    Ort::Session session(env, widecstr, options);
    return true;
}

**Comment by OeasyC** [comment]
![image](https://github.com/microsoft/onnxruntime/assets/91666203/ed560bcc-7dbd-4b83-afa3-b1ead832e068)
I have the same error.
![image](https://github.com/microsoft/onnxruntime/assets/91666203/c4508f2f-2caa-47b2-9009-a2626758bc34)
This is the solution.

> > Hi everybody, I am facing the same issue:
> > ![image](https://private-user-images.githubusercontent.com/125361595/293391613-b37a46c6-7ffe-4336-8f8e-46876cb98542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjgwMTcsIm5iZiI6MTcwNzcyNzcxNywicGF0aCI6Ii8xMjUzNjE1OTUvMjkzMzkxNjEzLWIzN2E0NmM2LTdmZmUtNDMzNi04ZjhlLTQ2ODc2Y2I5ODU0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwODQ4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzVjZjljOTI3Nzk5NWMwMTlmMTk1MmU5N2ZiZTllN2I2ZDhjZGRhYmExMTgxZTE3NGI4NTk2YzgyZmQ2NzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gaPJxvrmbB5WZXmWsdiMUXeg9utEo4ddMYJoFeGIdCw)
> > I also tried using pointers but that result in a compile error: ![image](https://private-user-images.githubusercontent.com/125361595/293391661-d82e2829-f941-4d29-a664-e833034e4cee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjgwMTcsIm5iZiI6MTcwNzcyNzcxNywicGF0aCI6Ii8xMjUzNjE1OTUvMjkzMzkxNjYxLWQ4MmUyODI5LWY5NDEtNGQyOS1hNjY0LWU4MzMwMzRlNGNlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwODQ4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTIwZGM2NWRjODNjOTYyNDFkNzg1YWM4NjBjZTk1MjFlMWFhMTI1ODA3MzRlYzdhYzI5ZjE2Y2E0NTM1MDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f7vXfSzNILsug3td7UefECr6K80TtH94cEG6IfMWh9k)
> > Thank you for your help,
> > Kind regeards
> 
> Hi, I'm facing the same error. If you've resolved this problem, could you please share how? Thanks!

![image](https://github.com/microsoft/onnxruntime/assets/91666203/ed560bcc-7dbd-4b83-afa3-b1ead832e068)
I have the same error.
![image](https://github.com/microsoft/onnxruntime/assets/91666203/c4508f2f-2caa-47b2-9009-a2626758bc34)
This is the solution.

**Comment by OeasyC** [comment]
> > Hi everybody, I am facing the same issue:
> > ![image](https://private-user-images.githubusercontent.com/125361595/293391613-b37a46c6-7ffe-4336-8f8e-46876cb98542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjgwMTcsIm5iZiI6MTcwNzcyNzcxNywicGF0aCI6Ii8xMjUzNjE1OTUvMjkzMzkxNjEzLWIzN2E0NmM2LTdmZmUtNDMzNi04ZjhlLTQ2ODc2Y2I5ODU0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwODQ4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzVjZjljOTI3Nzk5NWMwMTlmMTk1MmU5N2ZiZTllN2I2ZDhjZGRhYmExMTgxZTE3NGI4NTk2YzgyZmQ2NzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gaPJxvrmbB5WZXmWsdiMUXeg9utEo4ddMYJoFeGIdCw)
> > I also tried using pointers but that result in a compile error: ![image](https://private-user-images.githubusercontent.com/125361595/293391661-d82e2829-f941-4d29-a664-e833034e4cee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MjgwMTcsIm5iZiI6MTcwNzcyNzcxNywicGF0aCI6Ii8xMjUzNjE1OTUvMjkzMzkxNjYxLWQ4MmUyODI5LWY5NDEtNGQyOS1hNjY0LWU4MzMwMzRlNGNlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQwODQ4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTIwZGM2NWRjODNjOTYyNDFkNzg1YWM4NjBjZTk1MjFlMWFhMTI1ODA3MzRlYzdhYzI5ZjE2Y2E0NTM1MDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f7vXfSzNILsug3td7UefECr6K80TtH94cEG6IfMWh9k)
> > Thank you for your help,
> > Kind regeards
> 
> Hi, I'm facing the same error. If you've resolved this problem, could you please share how? Thanks!

I have the same problem and this is the solution to fix it
![image](https://github.com/microsoft/onnxruntime/assets/91666203/f3d611ec-465b-4f56-b337-faffd556627d)

**Comment by JothiGopal** [comment]
true, its working for me. thanks alot.
