### ISSUE TITLE
How to handle constant values in onnxruntime cpp inference

### ISSUE THREAD

**Issue by Bhuvanamitra** [microsoft/onnxruntime#8661]
I have converted a LightGBM model into ONNX. 
The output probabilities type is float32 (please refer to the attached image). 
So, I am having problem creating output tensor for probabilities.
How do I handle such constant value? How to create memory for that?   

**System information**
- OS Platform : Windows 10
- ONNX Runtime version: 1.7.0
- Visual Studio version : 16.9.3

**To Reproduce**
train a lightGBM model using https://github.com/onnx/onnxmltools/blob/master/onnxmltools/convert/lightgbm/convert.py#L15 convert method given here. Please mention zipmap=False
Later, convert the model into onnx and visualize it.

Please provide information about handling that probabilities type node.
Thanks in Advance.
![modelonnx](https://user-images.githubusercontent.com/7961570/128710940-c44b29ea-3840-4028-9bca-e349ff132baf.PNG)

**Comment by YUNQIUGUO** [comment]
Hi, can you please clarify a bit about your question? (Such as what do you mean by creating memory for constant value, etc.

And provide more details about how are you going to use the model converted from LightGBM to help us better address your question.

**Comment by Bhuvanamitra** [comment]
Hi, 
The model is a binary classifier. I will use the model converted from LightGBM to do binary classification on new records. I should do that inference in C++. 
So, I wrote a code referring the onnxruntime cpp inference examples and in that code, there is a step which allocates memory for input and output tensors. 

`this->input_node_dims.at(0).at(0) = 1;
        this->input_tensor_size.at(0) = 1 * NUM_FEATURES;

        // Label output node - [1] tensor
        this->output_node_dims.at(0).at(0) = 1;
        this->output_tensor_size.at(0) = 1;

        // Probability output node - 1 x 2 tensor
        this->output_node_dims.at(1).at(0) = 1;
        this->output_tensor_size.at(1) = 2;

        vector<int64_t> output_vec(this->output_tensor_size.at(0));
        vector<float> prob_vec(this->output_tensor_size.at(1));

        auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
        
        vector<Ort::Value> ip_tensors;
        ip_tensors.push_back(Ort::Value::CreateTensor<float>(
            memory_info, feature_vec.data(), this->input_tensor_size.at(0),
            this->input_node_dims.at(0).data(), this->input_node_dims.at(0).size()));
        
        vector<Ort::Value> op_tensors;
        op_tensors.push_back(Ort::Value::CreateTensor<int64_t>(
            memory_info, output_vec.data(), this->output_tensor_size.at(0),
            this->output_node_dims.at(0).data(), this->output_node_dims.at(0).size()));
        
        op_tensors.push_back(Ort::Value::CreateTensor<float>(
            memory_info, prob_vec.data(), this->output_tensor_size.at(1),
            this->output_node_dims.at(1).data(), this->output_node_dims.at(1).size()));
        
        this->session.Run(Ort::RunOptions{ nullptr }, this->input_node_names.data(),
            ip_tensors.data(), this->num_input_nodes,
            this->output_node_names.data(), op_tensors.data(),
            this->num_output_nodes);`

While this code worked fine for models with probabilities type as tensor (or vector), it is throwing "invalid vector subscript" error when I try with the model I showed in the question. That is because the probabilities type is a scalar in this model and I cannot create a tensor for single value. So, I looked up how to handle such scalar values and couldn't find anything helpful. 

So, my problem is, how to allocate memory for probabilities output, when it is just a single float32 value?

Hope this provided some insights about the problem. Will be happy to provide any further information. 
Thanks.
