### ISSUE TITLE
I wonder if the part I found has missing.

### ISSUE THREAD

**Issue by shp776** [microsoft/onnxruntime#8697]
**Describe the bug**

I have two questions.

1.
https://github.com/microsoft/onnxruntime/blob/caacf249c57d51eb435156d286ad3d7cf3d01429/onnxruntime/python/tools/transformers/gpt2_helper.py#L102

Why does the return value of class MyGPT2LMHeadModel_NoPadding in the link above not go through the postprocess function like class MyGPT2Model or MyGPT2LMHeadModel?

I was wondering if it was a code error.

2. 
![image](https://user-images.githubusercontent.com/42932221/129124296-ebf428e1-0d5e-4f73-adac-f6b04e2d60aa.png)

I modified the code of "Inference_GPT2_with_OnnxRuntime_on_CPU.ipynb" to get "MyGPT2LMHeadModel_NoPadding" model to in . And then I gave you an export it.

And then I exported the onnx file like the capture below, but an error has occurred.

![image](https://user-images.githubusercontent.com/42932221/129124713-9a8d3cca-acb2-484c-b577-21c46c558ba7.png)

How can I achieve my goal of getting onnx file which does not include position_ids and onnx oattention_mask inputts by calling up the No_padding model?

I look forward to your answer.

**Comment by tianleiwu** [comment]
You are right. The code missed post-processing since it works in older version of transformers. If you use latest version of transformers, you can change the class like the following:
```
class MyGPT2LMHeadModel_NoPadding(GPT2LMHeadModel):
    def __init__(self, config):
        super().__init__(config)

    def forward(self, input_ids, *past):
        result = super().forward(input_ids,
                                 past_key_values=past,
                                 return_dict=False)

        return MyGPT2Model.post_process(result, self.config.n_layer)
```

Then run in source directory like (example command in Windows):
```
D:\Git\onnxruntime\onnxruntime\python\tools\transformers>python convert_to_onnx.py --model_class GPT2LMHeadModel_NoPadding -m gpt2
```

**Comment by tianleiwu** [comment]
Fixed in master
