### ISSUE TITLE
ML.NET on Jetson Nano

### ISSUE THREAD

**Issue by keesschollaart81** [microsoft/onnxruntime#8767]
**Describe the bug** & **To Reproduce**
I would like to use ML.NET on my Jetson Nano to run a ONNX model. The NuGet does not seem to include the ARM64 library and CUDA bindings so I tried to do this myself.

Script run on my Jetson host:
```bash
git clone --depth 1 --branch v1.8.0 --recursive https://github.com/microsoft/onnxruntime.git
cd onnxruntime
./build.sh --update --config MinSizeRel --build --parallel --use_cuda --skip_tests --cuda_home /usr/local/cuda --cudnn_home /usr/lib/aarch64-linux-gnu
```

This completes with `libonnxruntime_providers_cuda.so`, `libonnxruntime_providers_shared.so` and `onnxruntime.so` in the `~/onnxruntime/build/Linux/MinSizeRel` folder.

Then I create new .NET Console app (on the Jetson host, where I installed the .NET 5.0 SDK):
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.8.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.8.0" />
  </ItemGroup>
</Project>
```

```cs
using System;
using Microsoft.ML.OnnxRuntime;

var inference = new InferenceSession("yolov3-10.onnx", SessionOptions.MakeSessionOptionWithCudaProvider());
```
When I then run:
`LD_LIBRARY_PATH=~/onnxruntime/build/Linux/MinSizeRel dotnet run`

It seems to be able to work with the native library. However, I get the following exception:

```
terminate called after throwing an instance of 'onnxruntime::NotImplementedException'
  what():  tensor type -1449813872 is not supported
```
Which seems to come from [here](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/framework/onnxruntime_typeinfo.cc#L212). 

I'm confident it has nothing to do with this specific ONNX file as changing my C# code to...
```cs
var inference = new InferenceSession("yolov3-10.onnx");
```
... does make it work, however, via CPU... Actually, when using the Cuda provider, it does not matter what filename/string you provide for the InferenceSession constructor as it does not even get to reading the file, it always end in this exception.

To be clear, I have no I idea if it is even remotely possible to get ML.NET to run on ARM64 / Jetson. This is as far as I've got. I hope to get some guidance if I missed a step. A 'this will not work' is sad news but at least I then know not to spend much more time on this...

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
   ```
   uname -a
   Linux jetson1 4.9.201-tegra #1 SMP PREEMPT Wed May 5 09:31:36 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux
   ```
- ONNX Runtime installed from (source or binary): source, v1.8.0 GH tag
- ONNX Runtime version: v1.8.0 GH tag
- Python version: 3.6.9
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): 
   gcc --version: 7.5.0
   cmake --version: 3.21.1
- CUDA/cuDNN version: V10.2.89
- GPU model and memory: Jetson Nano / 4gb

**Comment by skottmckay** [comment]
If it works for CPU I would expect it's possible for it to work for CUDA given the setup you've created and that you were able to add the CUDA execution provider to the session options.

Is the error occurring when creating the InferenceSession or when running it? If during creation it looks like we have a mismatch in the ordering of the entry points. Unfortunately those have to be manually maintained in a 1:1 order with code in the onnxruntime library.

**Comment by keesschollaart81** [comment]
The exception occurs at this line:
```cs
var inference = new InferenceSession("yolov3-10.onnx", SessionOptions.MakeSessionOptionWithCudaProvider());
```
So at creating the InferenceSession. I'm not sure if at that point the CUDA execution provider has already been found/loaded?

How would I be able to verify/dig-into your guess about the ordering of the entry points?

**Comment by skottmckay** [comment]
Did you try using the pre-built nuget package with CUDA included? Microsoft.ML.OnnxRuntime.Gpu

**Comment by keesschollaart81** [comment]
I dont think there is an ARM64 version of the onnxruntime.so in there, right?

**Comment by skottmckay** [comment]
Ahh right - sorry - overlooked the ARM64 aspect.

Can you run it in a debugger and set it to break on throw to get the callstack from where the onnxruntime::NotImplementedException is thrown? That should show with entry point it comes into the onnxruntime dll via.

**Comment by skottmckay** [comment]
I don't think it's an ordering issue as MakeSessionOptionWithCudaProvider calls OrtSessionOptionsAppendExecutionProvider_CUDA which is looked up by name (vs. entries in the OrtApi structure which have to be in sync). 

When you build with CUDA enabled the onnxruntime library should have a dependency on the onnxruntime_providers_shared library. That should provide the `OrtSessionOptionsAppendExecutionProvider_CUDA` entry point, and calling that will result in onnxruntime_providers_cuda and the cuda libraries being loaded.

I tested on a raspberry pi 4 (arm64 but no CUDA) with the DNNL EP as that has same setup as the CUDA EP in that it's a separate library accessed via onnxruntime_providers_shared, and the call to add the EP to the session options involves lookup by name. That was successful. 

I don't see anything else obvious in the setup that is off/different with adding the CUDA EP to the session options, so a callstack may be the best chance to get an idea of where things are going wrong.

Additionally you could separate the line into two pieces to narrow it down a little more. i.e.:
```
var so = SessionOptions.MakeSessionOptionWithCudaProvider();
var inference = new InferenceSession("mnist.onnx", so);
```

**Comment by keesschollaart81** [comment]
Ok, I got it to work! (with .NET 5, ML.NET 1.8.0 from NuGet and my Yolov5 ONNX model on my ARM64 Jetson Nano, ±5 FPS @ 512x512 input via CUDA provider) 

I'm not sure what I did differently compared to the code/steps mentioned in my OP. Your guess about the entrypoint made me start over from a clean Jetson/Image. My guess is that there was some kind of version mismatch in one of the .so files and the NuGet packages as I tried multiple versions in all my experiments. Now I made really sure everything was 1.8.0. 

I'll report back her after the weekend with an update / clear steps / repro for others on how to get it to work.

**Comment by skottmckay** [comment]
Awesome! Great to hear.

**Comment by keesschollaart81** [comment]
Not much more to add. Just compile the onnx runtime like mentioned in the OP and then make sure that the .so can be found. It really was me messing it up somewhere. Would be great to have a ARM64 onnxruntime available on NuGet. But that is something easier said than done, I guess.
