### ISSUE TITLE
onnnxruntime-training lists Windows as a supported platform on PyPI but doesn't have Windows wheels

### ISSUE THREAD

**Issue by NathanielMcVicar** [microsoft/onnxruntime#8772]
onnxruntime-training on PyPI lists Windows (and MacOS) as a supported platform here https://pypi.org/project/onnxruntime-training/ but doesn't include any Windows wheels (see here https://pypi.org/project/onnxruntime-training/#files) leading to a failure to install as follows:
```
E:\>python -m pip install onnxruntime-training==1.8.1
ERROR: Could not find a version that satisfies the requirement onnxruntime-training==1.8.1 (from versions: none)
ERROR: No matching distribution found for onnxruntime-training==1.8.1
```
Either Windows wheels should be provided or Windows should be removed from the classifiers. Thanks!

**Comment by thiagocrepaldi** [comment]
Indeed, you can compile and use ONNX Runtime on Windows and MacOS, but not `pip install` it on these platforms. We will look into it, thanks for reporting!

**Comment by sstamenova** [comment]
@thiagocrepaldi : Would it be possible to add the windows wheels instead? We are currently trying to use onnxruntime on both Linux and Windows and would like to be able to support both platforms.

**Comment by thiagocrepaldi** [comment]
> @thiagocrepaldi : Would it be possible to add the windows wheels instead? We are currently trying to use onnxruntime on both Linux and Windows and would like to be able to support both platforms.

@liqunfu We are looking into it internally, as there are several considerations for this (which windows versions, etc), but until there, we will at least fix the classifiers and save people's time :)

**Comment by bouachalazhar** [comment]
> > @thiagocrepaldi : Would it be possible to add the windows wheels instead? We are currently trying to use onnxruntime on both Linux and Windows and would like to be able to support both platforms.
> 
> @liqunfu We are looking into it internally, as there are several considerations for this (which windows versions, etc), but until there, we will at least fix the classifiers and save people's time :)

Same problem : 
```
Lazhar Bouacha@PC-LAZHAR MINGW64 ~
$ python -m pip install onnxruntime-training==1.14.1
ERROR: Could not find a version that satisfies the requirement onnxruntime-training==1.14.1 (from versions: none)
ERROR: No matching distribution found for onnxruntime-training==1.14.1

Lazhar Bouacha@PC-LAZHAR MINGW64 ~
$ python -m pip install onnxruntime-training==1.14.0
ERROR: Could not find a version that satisfies the requirement onnxruntime-training==1.14.0 (from versions: none)
ERROR: No matching distribution found for onnxruntime-training==1.14.0

Lazhar Bouacha@PC-LAZHAR MINGW64 ~
$ python -m pip install onnxruntime-training
ERROR: Could not find a version that satisfies the requirement onnxruntime-training (from versions: none)
ERROR: No matching distribution found for onnxruntime-training

Lazhar Bouacha@PC-LAZHAR MINGW64 ~
$ python -m pip install onnxruntime-training==1.7.0
ERROR: Could not find a version that satisfies the requirement onnxruntime-training==1.7.0 (from versions: none)
ERROR: No matching distribution found for onnxruntime-training==1.7.0
```

```
------------------
System Information
------------------
         Operating System: Windows 11 Home 64-bit (10.0, Build 22624) (22621.ni_release.220506-1250)
	          Version: 22H2
      System Manufacturer: ASUSTeK COMPUTER INC.
             System Model: ZenBook UX325EA_UX325EA
                Processor: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 CPUs), ~2.8GHz
		     Chip: Intel(R) Iris(R) Xe Graphics (iGPU)
                   Memory: 32768MB RAM, ~32GB
          DirectX Version: DirectX 12
```
