### ISSUE TITLE
Controlling number of ThreadAllocations (CPU) of ONNX Runtinme C++ API

### ISSUE THREAD

**Issue by luisfmnunes** [microsoft/onnxruntime#8777]
**Describe the bug**

I got the ONNX Runtime C++ API CPU release 1.8.1 from github and I linked into a project to use for graph inference. I'm trying to control the number of threads allocation from the application however what I've got so far was 11 threads instantiated with only 1 actually processing (Running) and the others asleep (Sleep). To check the results I'm using the command `top -H -b -n1 | grep binary_name` during inference runtime. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 8.2.2004
- ONNX Runtime installed from (source or binary):  Precompiled Linux Release
- ONNX Runtime version: 1.8.1
- Python version: -
- Visual Studio version (if applicable): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: -
- GPU model and memory: -

**To Reproduce**

A description of my workflow: I'm creating a single Env for 4 sessions (I have 4 different graphs along it). I have a session data struct that stores the Ort env and session pointers and I call the constructors by `new` command. Bellow is my following code.

```c++
    int intraOpNumThreads = 1;
    int interOpNumThreads = 1;
    
    OrtThreadingOptions *thOpt;
    OrtStatusPtr status;

    status = Ort::GetApi().CreateThreadingOptions(&thOpt);
    status = Ort::GetApi().SetGlobalIntraOpNumThreads(thOpt, intraOpNumThreads);
    status = Ort::GetApi().SetGlobalInterOpNumThreads(thOpt, interOpNumThreads);

    s->env = new Ort::Env(thOpt, ORT_LOGGING_LEVEL_FATAL, "run_env");
    Ort::SessionOptions session_options;

    session_options.SetIntraOpNumThreads(intraOpNumThreads);
    session_options.SetInterOpNumThreads(interOpNumThreads);
    session_options.SetExecutionMode(ORT_SEQUENTIAL);
    session_options.DisablePerSessionThreads();
    session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);

    s->net1_session = new Ort::Session(*(s->env), graph1, graph1_size, session_options);
    s->net2_session = new Ort::Session(*(s->env), graph2, graph2_size, session_options);
    s->net3_session = new Ort::Session(*(s->env), graph3, graph3_size, session_options);
    s->net4_session = new Ort::Session(*(s->env), graph4, graph4_size, session_options);
``` 

**Expected behavior**
With the current config I'm getting 11 threads (1 Running 10 Asleep) when I expected a single thread initialized and running.
Anything I'm missing here?

**Comment by chenfucn** [comment]
could you check name of those threads? by default ORT created thread names start with either "inter-op" or "intra-op"

**Comment by luisfmnunes** [comment]
After further evaluation I noticed that it wasn't the ORT that was creating the threads. So this works, thank you for the assistance.
