### ISSUE TITLE
CUDA kernel not found in registries for Op type: Tile 

### ISSUE THREAD

**Issue by mlizhardy** [microsoft/onnxruntime#8781]
**Problem Description**
I've created an onnx model from pytorch.  In one layer in my pytorch model I expand and repeat the tensor:
```mask = (control > 0).unsqueeze(-1).unsqueeze(-1).repeat(1, 3, 360, 640)```

in onnx this appears as expand -> Tile, but it appears this Tile or 'repeat' operation is not a capability in CUDA:

```[W:onnxruntime:log, cuda_execution_provider.cc:1983 GetCapability] CUDA kernel not found in registries for Op type: Tile node name: Tile_13```

**System information**
onnxruntime-gpu==1.8.1
using opset=11

any ideas on a work around or timeline for feature release?

**Comment by chenfucn** [comment]
It would be helpful if more detailed information can be shared, such as the model and the detailed repro instruction

**Comment by harshithapv** [comment]
Could you update to opset 12 or greater? We have CUDA kernel for Tile Op.

**Comment by mlizhardy** [comment]
here's a model example:

```python
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()

    def forward(x):
	return x.unsqueeze(-1).repeat(1,3)

model = Model().cuda().eval()
    torch.onnx.export(model,
                      (torch.FloatTensor(1)),
                      'segmentation_081804.onnx',
                      example_outputs=output,
                      opset_version=11, # 12 gives same error
                      input_names=['INPUT'],  # the model's input names
                      output_names=['OUTPUT'],  # the model's output names
                      dynamic_axes={'INPUT': {0: 'batch_size'},
                                    'OUTPUT': {0: 'batch_size'}})

```

opset 12 gives same error.

**Comment by mlizhardy** [comment]
came up with a workaround: can use torch.stack to repeat and unsqueeze the tensor:

`x.unsqueeze(-1).repeat(1,3) == torch.stack(tuple([x]*3),-1)`
