### ISSUE TITLE
build instractions are not found

### ISSUE THREAD

**Issue by xpmemeda** [microsoft/onnxruntime#8790]
the link writen in [README](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/c_cxx#option-2-build-from-source) of https://onnxruntime.ai/docs/how-to/build.html is invalid。

**Comment by nicholim** [comment]
Here is the build page https://onnxruntime.ai/docs/how-to/build/

**Comment by xpmemeda** [comment]
ok, thinks.
