### ISSUE TITLE
Missing mandatory parameter

### ISSUE THREAD

**Issue by EdwardDixon** [microsoft/onnxruntime#8795]
When this conversion script is run to process a single specific model rather than a folder of models, the script fails on this line, because the function that is being invoked now takes a second mandatory parameter (which is being supplied in the "process the whole folder" case).

https://github.com/microsoft/onnxruntime/blob/d6df5764d72cc2ac3b3fd1fc6c87db9228109654/tools/python/util/convert_onnx_models_to_ort.py#L31

**Comment by gwang-msft** [comment]
This was fixed by #8323, you can try to use ORT-nightly pypi package to convert the models to .ort format
