### ISSUE TITLE
Error message could be even better....

### ISSUE THREAD

**Issue by EdwardDixon** [microsoft/onnxruntime#8796]
I was using ONNX to create and save a model graph that had IR version 8 and was stumped by this error message.  Eventually, I realised I just need to go to the ONNX Runtime github repo, set the version tag, and read the original source code.  I really think a nice explicit error message along the lines of "your model has IR version 8, but we support up to IR 7" could save some time...

https://github.com/microsoft/onnxruntime/blob/96bb4b1ce83efd13b7dba54f707b27303354e480/onnxruntime/core/graph/model.cc#L111

Also, I actually love ONNX + ONNX Runtime, light and fast, I tell all my friends.

**Comment by edgchen1** [comment]
It has since gotten a bit better, I hope: https://github.com/microsoft/onnxruntime/commit/f6da9ac6d639dda67e100ad3015c6f88b990ef40

**Comment by EdwardDixon** [comment]
Perfect!

Love these tools.
