### ISSUE TITLE
"Failed to find kernel error" after building custom mobile ONNX iOS framework

### ISSUE THREAD

**Issue by scm007** [microsoft/onnxruntime#8797]
This is all for iOS.

"Unexpected error: Error Domain=onnxruntime Code=1 "inference_session.cc:1209 AssignNodesToEpsFromHashesImpl Failed to find kernel def hash in kernel registries: 13881250836434776192" UserInfo={NSLocalizedDescription=inference_session.cc:1209 AssignNodesToEpsFromHashesImpl Failed to find kernel def hash in kernel registries: 13881250836434776192}."

Here are the steps:

I converted my .onnx model into a .ort model using the standard parameters.

Running with the standard onnxruntime Pod framework failed due to missing  operator, ai.onnx;4;Concat.

Here are all the required_operators for my model.
ai.onnx;1;Conv
ai.onnx;4;Concat
ai.onnx;5;Reshape
ai.onnx;6;Relu
ai.onnx;7;Add
ai.onnx;8;MaxPool
ai.onnx;9;Gemm
com.microsoft;1;FusedConv,FusedGemm

I added all of these into the mobile_package.required_operators.config file and rebuilt the onnxruntime.framework using
python tools/ci_build/github/apple/build_ios_framework.py

This fixed the first error but now I have the kernel error. From the error clearly I am missing a kernel(?). Do I need to rebuild my .ort model with custom_op_library?

**Comment by chenfucn** [comment]
would you care to share your model that caused the problem?

**Comment by edgchen1** [comment]
It looks like the hash is for a Concat kernel: https://github.com/microsoft/onnxruntime/blob/19b82b438b6b7075df321284a79726b6208d344a/onnxruntime/test/testdata/kernel_def_hashes/onnx.cpu.json#L320

The error message can be improved.

It seems that the Concat kernel is still not there. In addition, would you mind sharing the command used to run build_ios_framework.py and the config file contents?

**Comment by gwang-msft** [comment]
If you are using `build.sh` or `build.py` to build the custom framework, please share the build command, your mobile_package.required_operators.config and the model file.
Please also try to revert all the changes in the onnxruntime project and rebuild the framework, since it is possible the missing kernel is excluded in a previous build.

**Comment by scm007** [comment]
Here is the command to initiate the build:
python3 tools/ci_build/github/apple/build_ios_framework.py tools/ci_build/github/apple/default_mobile_ios_framework_build_settings.json --config MinSizeRel --include_ops_by_config tools/ci_build/github/android/mobile_package.required_operators.config


Here is the contents of the required operators .config file:

# Android package for ORT Mobile operator and type reduction configuration
#
# The list of operators was generated from:
#  - the ONNX operators use by the tf2onnx tflite converter
#  - the operators used in a set of tflite models from tfhub, the tflite examples, and the mlperf mobile models
#     - models were optimized with optimizations set to 'basic', 'extended' and 'all' 
#     - see the readme file for full details

# allow float, int8, uint8. operators that manipulate shapes or indices have int32 and int64 enabled internally.
!globally_allowed_types;float,int8_t,uint8_t

# ops used by the tf2onnx tflite converter. same list for opsets 12 and 13.
ai.onnx;12;Abs,Add,And,ArgMax,ArgMin,AveragePool,Cast,Ceil,Clip,Concat,ConstantOfShape,Conv,ConvTranspose,Cos,CumSum,DepthToSpace,DequantizeLinear,Div,DynamicQuantizeLinear,Elu,Equal,Exp,Expand,Flatten,Floor,Gather,GatherND,Gemm,Greater,GreaterOrEqual,Identity,If,LRN,LeakyRelu,Less,LessOrEqual,Log,LogSoftmax,Loop,MatMul,Max,MaxPool,Mean,Min,Mul,Neg,NonMaxSuppression,NonZero,Not,Or,PRelu,Pad,Pow,QuantizeLinear,Range,Reciprocal,ReduceMax,ReduceMean,ReduceMin,ReduceProd,ReduceSum,Relu,Reshape,Resize,ReverseSequence,Round,ScatterND,Shape,Sigmoid,Sin,Size,Slice,Softmax,SpaceToDepth,Split,Sqrt,Squeeze,Sub,Sum,Tanh,ThresholdedRelu,Tile,TopK,Transpose,Unique,Unsqueeze,Where
ai.onnx;13;Abs,Add,And,ArgMax,ArgMin,AveragePool,Cast,Ceil,Clip,Concat,ConstantOfShape,Conv,ConvTranspose,Cos,CumSum,DepthToSpace,DequantizeLinear,Div,DynamicQuantizeLinear,Elu,Equal,Exp,Expand,Flatten,Floor,Gather,GatherND,Gemm,Greater,GreaterOrEqual,Identity,If,LRN,LeakyRelu,Less,LessOrEqual,Log,LogSoftmax,Loop,MatMul,Max,MaxPool,Mean,Min,Mul,Neg,NonMaxSuppression,NonZero,Not,Or,PRelu,Pad,Pow,QuantizeLinear,Range,Reciprocal,ReduceMax,ReduceMean,ReduceMin,ReduceProd,ReduceSum,Relu,Reshape,Resize,ReverseSequence,Round,ScatterND,Shape,Sigmoid,Sin,Size,Slice,Softmax,SpaceToDepth,Split,Sqrt,Squeeze,Sub,Sum,Tanh,ThresholdedRelu,Tile,TopK,Transpose,Unique,Unsqueeze,Where

# other ops found in test models 
ai.onnx;12;Erf,GlobalAveragePool,InstanceNormalization,HardSigmoid,MatMulInteger,QLinearConv,QLinearMatMul
ai.onnx;13;Erf,GlobalAveragePool,InstanceNormalization,HardSigmoid,MatMulInteger,QLinearConv,QLinearMatMul

# Control flow ops
#  - If and Loop are covered by the tflite converter list
#  - Scan tends to be used in speech models (it's more efficient than Loop) so include it for support of those
ai.onnx;12;Scan
ai.onnx;13;Scan

# internal ops added by optimizers
# Note: LayerNormalization is an internal op even though it is (incorrectly) registered in the ONNX domain.
ai.onnx;1;LayerNormalization
com.microsoft;1;DynamicQuantizeMatMul,FusedConv,FusedGemm,FusedMatMul,Gelu,MatMulIntegerToFloat,NhwcMaxPool,QLinearAdd,QLinearAveragePool,QLinearConv,QLinearGlobalAveragePool,QLinearMul,QLinearSigmoid

# NHWC transformer also uses this, so assuming it's valuable enough to include 
com.microsoft;1;QLinearLeakyRelu

# Quantized contrib ops that are registered but no usage was found. Excluding for now.
# com.microsoft;1;DynamicQuantizeLSTM,QAttention

# Custom ops necessary for the itracker onnx model
ai.onnx;1;Conv
ai.onnx;4;Concat
ai.onnx;5;Reshape
ai.onnx;6;Relu
ai.onnx;7;Add
ai.onnx;8;MaxPool
ai.onnx;9;Gemm

**Comment by gwang-msft** [comment]
Please use the `required_operators.config` generated by the onnx->ort conversion to build your custom framework, such as
```
python3 tools/ci_build/github/apple/build_ios_framework.py tools/ci_build/github/apple/default_mobile_ios_framework_build_settings.json --config MinSizeRel --include_ops_by_config <path to required_operators.config>
```
See, https://onnxruntime.ai/docs/how-to/mobile/model-conversion.html#basic-processing
Please revert the changes in the onnxruntime project before the build.

Also, please share the model, such that we can troubleshoot the issue.

**Comment by scm007** [comment]
Rebuilt with only the necessary operators:

```
2021-08-23 12:16:31.974756-0700 [1761:304519] 2021-08-23 11:16:31.974694 [V:onnxruntime:, base_op_builder.cc:50 AddToModelBuilder] Operator name: [Gemm_302] type: [Gemm] was added
Unexpected error: Error Domain=onnxruntime Code=1 "inference_session.cc:1209 AssignNodesToEpsFromHashesImpl Failed to find kernel def hash in kernel registries: 13881250836434776192" UserInfo={NSLocalizedDescription=inference_session.cc:1209 AssignNodesToEpsFromHashesImpl Failed to find kernel def hash in kernel registries: 13881250836434776192}.
```

I also see a lot of operators with supported = [0]

```
 2021-08-23 11:16:28.221184 [V:onnxruntime:, helper.cc:97 GetSupportedNodes] Operator type: [FusedConv] index: [325] name: [fused Conv_158] supported: [0]

[1761:304519] 2021-08-23 11:16:28.218332 [V:onnxruntime:, concat_op_builder.cc:72 IsOpSupportedImpl] Concat only support 4d shape for now, input is 2d shape

[1761:304519] 2021-08-23 11:16:28.218401 [V:onnxruntime:, helper.cc:97 GetSupportedNodes] Operator type: [Concat] index: [295] name: [Concat_299] supported: [0]

[1761:304519] 2021-08-23 11:16:28.218970 [V:onnxruntime:, helper.cc:97 GetSupportedNodes] Operator type: [FusedGemm] index: [304] name: [fused Gemm_300] supported: [0]
```

**Comment by skottmckay** [comment]
> Rebuilt with only the necessary operators:

Did you do something like `git reset --hard` prior to rebuilding? The build script won't undo any previously disabled operators so it's better to start fresh. The model is opset 9 so Concat version of 4 is correct and `ai.onnx;4;Concat` should have included the kernel in the build.

**Comment by skottmckay** [comment]
The messages from GetSupportedNodes is coming from the CoreML EP as there are limits to what we can run using that. The node will fallback to running on CPU if not supported on CoreML.
