### ISSUE TITLE
IO binding int64 type issue 

### ISSUE THREAD

**Issue by rinapch** [microsoft/onnxruntime#8800]
I'm having trouble with IO bindnig when inferencing a custom GPT model on GPU. The input to the model is a tensor with dtype int64. However, when trying to perform IO binding the bind_input function won't convert to the numpy array of the corresponding np.int64 type, throwing "No corresponding Numpy type for Tensor Type" error. 

![image](https://user-images.githubusercontent.com/61157346/130295170-be4f1035-64fa-4f9d-9bf1-ab08f796da16.png) 

It can be solved with setting element_type parameter to np.int32, however, the inference session won't start because it expects a tensor of int64, not int32 type, so there seems to be no obvious way out of this

**Comment by tianleiwu** [comment]
Try basic type numpy.longlong (https://numpy.org/doc/stable/user/basics.types.html) for int64.

**Comment by rinapch** [comment]
@tianleiwu thanks, it helped!
