### ISSUE TITLE
How can I set the empty ort_input?

### ISSUE THREAD

**Issue by shp776** [microsoft/onnxruntime#8809]
**Is your feature request related to a problem? Please describe.**

As you can see from the source of the gpt-2 model, initial past_state input is empty value.
I use the onnx model with past_state.
How can I set the empty ort_input?

There's no source to refer to. Please give me the sample code.

**System information**
- ONNX Runtime version (you are using):

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tianleiwu** [comment]
With IO Binding:
https://github.com/microsoft/onnxruntime/blob/62c0d24340691900ef64bfefd336dbab3acfcac2/onnxruntime/python/tools/transformers/gpt2_helper.py#L444-L450

You can debug `python convert_to_onnx.py -m gpt2 -o` to see how the function is used in inference.

**Comment by tianleiwu** [comment]
@shp776, 

The shape of empty past state is [2, batch_size, num_heads, past_seq_len, hidden_size/num_heads] where past_seq_len=0.

You can try the following APIs:
https://github.com/microsoft/onnxruntime/blob/8d737f977056444a307f1b7f0bcd402fba62d790/include/onnxruntime/core/session/experimental_onnxruntime_cxx_api.h#L62

https://github.com/microsoft/onnxruntime/blob/8d737f977056444a307f1b7f0bcd402fba62d790/include/onnxruntime/core/session/experimental_onnxruntime_cxx_inline.h#L91

You can pass any p_data that is not nullptr.
