### ISSUE TITLE
[Documentation Request]

### ISSUE THREAD

**Issue by hunterchenghx** [microsoft/onnxruntime#8839]
[Enter feedback here]
I did a yolo5 onnx model inference on a video due to the instruction. However, when I check nvidia-smi, I found no GPU is working during inference. In my code, '''onnxruntime.get_device()''' outputs GPU though. Would you please tell me the reason?
---
#### Document Details
* Title: CUDA
* Page: [https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html](https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html)
* Page Source: CUDA-ExecutionProvider.md

**Comment by snnn** [comment]
Because the implementation of onnx runtime doesn't know if you have GPU or not.
