### ISSUE TITLE
Running multiple models concurrently is not thread safe

### ISSUE THREAD

**Issue by sniper0110** [microsoft/onnxruntime#8854]
**Describe the bug**
We are facing a problem when running 2 models with 2 sessions concurrently in onnxruntime c++.
When running inference, it doesn't seem to be thread safe because we're getting different results when running the same process multiple times.
What is the best way to run multiple models concurrently in onnxruntime?
We've taken a look at OrtThreadingOptions and other things mentioned in the documentation about thread management but with no success.

Can you provide us with the best method to go about this? A small working example would be great!

**Urgency**
Very! We need this in production.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win64
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.8
- Python version: we're using C++
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Expected behavior**
To get the same results from our models each time we run inference.

**Additional context**
There is a possibility that we're just not using the api correctly and the documentation doesn't have any working examples on how to achieve this. So maybe just a small working example in C or C++ would be enough.

**Comment by sniper0110** [comment]
Btw we're running the tests on a database of around 3000 images.

**Comment by pranavsharma** [comment]
It's not clear how these objects are instantiated and used. If you follow the guidelines below you shouldn't see issues due to concurrent runs. 
* A session needs to be created only once per model. It can be used in multiple threads to inference the same model (corresponding to the session) concurrently.
* OrtEnv needs to be created only once per process (irrespective of the # of models you're inferencing).

**Comment by sniper0110** [comment]
We have updated our code to follow what you have suggested but we're still facing the same issue

```
#include "OrtCRNNModelHandler.h"
#include "onnxruntime_c_api.h"
#include <mutex>
#include <chrono>



//class definition
class OrtCRNNModelHandler
{
public:
	OrtCRNNModelHandler() = default;
	OrtCRNNModelHandler(void* model_data, int model_data_length, std::wstring vocabulary);
	~OrtCRNNModelHandler();

	std::wstring chars_from_probabilities(float* output_tensor, unsigned int output_count);

	std::wstring ctc_decode(std::wstring predicted_chars);

	std::wstring predict(float* image_data, int data_size);

protected:

	Ort::Session* m_session;
	std::wstring m_vocabulary;

	unsigned debug = 0;

};


static Ort::Env m_env;


OrtCRNNModelHandler::OrtCRNNModelHandler(void* model_data, int model_data_length, std::wstring vocabulary) {
	Ort::SessionOptions session_options = Ort::SessionOptions{};

	this->m_session = new Ort::Session(m_env, model_data, model_data_length, session_options);

	this->m_vocabulary = vocabulary;
}


OrtCRNNModelHandler::~OrtCRNNModelHandler() {
	delete m_session;
}


std::wstring OrtCRNNModelHandler::chars_from_probabilities(float* output_tensor, unsigned int output_count) {
	if (output_tensor == NULL) {
		return L"";
	}

	int vocab_length = this->m_vocabulary.size();

	int time_steps = output_count / vocab_length;

	std::wstring output_str = L"";

	if (output_count % vocab_length != 0) {
		return L"";
	}

	float* start_idx, * end_idx;
	int idx_max_probability = -1;
	char symbol;

	int i = 0;
	while (i < output_count) {

		start_idx = output_tensor + i;
		end_idx = output_tensor + i + vocab_length;

		idx_max_probability = std::distance(start_idx, std::max_element(start_idx, end_idx));

		symbol = this->m_vocabulary[idx_max_probability];
		output_str += symbol;

		i = i + vocab_length;
	}

	return output_str;
}


std::wstring OrtCRNNModelHandler::ctc_decode(std::wstring predicted_chars) {

	wchar_t saved_symbol = '-';
	wchar_t current_symbol;
	std::wstring final_str = L"";
	wchar_t empty_symbol = 'E';

	for (std::wstring::iterator it = predicted_chars.begin(); it != predicted_chars.end(); ++it) {

		current_symbol = *it;

		if (current_symbol != empty_symbol && current_symbol != saved_symbol) {

			final_str += current_symbol;
		}
		saved_symbol = current_symbol;

	}

	return final_str;
}


std::wstring OrtCRNNModelHandler::predict(float* image_data, int data_size)
{
	Ort::AllocatorWithDefaultOptions allocator;
	char* inputName = m_session->GetInputName(0, allocator);
	char* outputName = m_session->GetOutputName(0, allocator);

	std::vector<char*> inputNames = { inputName };
	std::vector<char*> outputNames = { outputName };

	std::vector<int64_t> input_shape = m_session->GetInputTypeInfo(0).GetTensorTypeAndShapeInfo().GetShape();
	input_shape[0] = 1;

	Ort::MemoryInfo memoryInfo = Ort::MemoryInfo::CreateCpu(OrtDeviceAllocator, OrtMemTypeCPU);
	Ort::Value inputOnnxTensor = Ort::Value::CreateTensor(memoryInfo,
		image_data, data_size,
		input_shape.data(), input_shape.size());

	Ort::RunOptions run_options;
	run_options.SetRunLogSeverityLevel(-1);
	run_options.SetRunLogVerbosityLevel(-1);

	std::vector<Ort::Value> outputValues = m_session->Run(
		run_options,
		inputNames.data(), &inputOnnxTensor, 1,
		outputNames.data(), 1);

	float* floats = outputValues[0].GetTensorMutableData<float>();
	const int floats_count = outputValues[0].GetTensorTypeAndShapeInfo().GetElementCount();

	std::wstring  raw_prediction = chars_from_probabilities(floats, floats_count);
	std::wstring predicted_string = ctc_decode(raw_prediction);

	allocator.Free(inputName);
	allocator.Free(outputName);

	return predicted_string;
}
```

**Comment by sniper0110** [comment]
We're currently putting together a more complete example using purely C++, this way you can run the code from your side. 
I'll get back to you once that example is finished.

**Comment by sniper0110** [comment]
Ok we've identified the problem, it's from our side! Thanks for the help, we're now following the guidelines you mentioned above.

**Comment by pranavsharma** [comment]
> Ok we've identified the problem, it's from our side! Thanks for the help, we're now following the guidelines you mentioned above.

What was the problem? Might be useful for others running into similar issues.
