### ISSUE TITLE
[Documentation Request] ONNX GPU IOBinding example

### ISSUE THREAD

**Issue by sam-writer** [microsoft/onnxruntime#8872]
In [the notebook linked to show how to use ONNX to accelerate BERT on GPU](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/notebooks/PyTorch_Bert-Squad_OnnxRuntime_GPU.ipynb), in section 4, there is a comment, `# TODO: use IO Binding (see https://www.onnxruntime.ai/python/api_summary.html) to improve performance.`

Is there an example of how to use IOBinding with HuggingFace? The examples in the [IOBinding Section](https://github.com/microsoft/onnxruntime/blob/master/docs/python/inference/api_summary.rst#iobinding) are helpful, but it is not immediately clear to me how to apply them.

Thank you

---
#### Document Details
* Title: Accelerate Hugging Face
* Page: [https://onnxruntime.ai/docs/tutorials/inferencing/huggingface.html](https://onnxruntime.ai/docs/tutorials/inferencing/huggingface.html)
* Page Source: huggingface.md

**Comment by natke** [comment]
Hi @sam-writer,

We have added some documentation that may help you with this. In this section https://onnxruntime.ai/docs/api/python/api_summary.html#data-on-device, there is an example of using PyTorch tensors on device.

We have also add a sample for this (currently in PR): https://github.com/natke/onnxruntime-inference-examples/blob/iobinding-sample/python/api/onnxruntime-python-api.py#L66, showing IO Binding with different PyTorch tensor types.

I tested IO Binding in the notebook you mentioned and it does not show a performance gain in this case (a batch size of 1 and a relative small sequence length). You can see the notebook here: https://github.com/natke/onnxruntime/blob/iobinding-huggingface/onnxruntime/python/tools/transformers/notebooks/PyTorch_Bert-Squad_OnnxRuntime_GPU.ipynb

We will endeavor to update the notebooks where the benefit is clear.

Thank you for reporting the issue and engaging with ONNX Runtime!

**Comment by sam-writer** [comment]
Thank you @natke ! These examples are very helpful.

**Comment by natke** [comment]
Awesome @sam-writer! I'll close this issue. Please reach out again if you need more help.
