### ISSUE TITLE
Inconsistent result for ONNX::Xor when number of elements vary

### ISSUE THREAD

**Issue by BowenBao** [microsoft/onnxruntime#8880]
**Describe the bug**

The result of `onnx::Xor(x, False)` is inconsistent between `x` having only 1 element, and more than 1 elements.
Running script in the below ``To Reproduce`` section will print

```
graph(%x : Bool(*, strides=[1], requires_grad=0, device=cpu),
      %6 : Bool(1, strides=[1], requires_grad=0, device=cpu)):
  %2 : Bool(*, device=cpu) = onnx::Cast[to=9](%x)
  %4 : Bool(*, device=cpu) = onnx::Xor(%2, %6)
  %5 : Bool(*, strides=[1], requires_grad=0, device=cpu) = onnx::Cast[to=9](%4) # repro_aug_git_floor.py:83:0
  return (%5)

Testing logical_xor ([True, False], False):
ort: [array([ True, False])]
torch: tensor([ True, False])

Testing logical_xor ([True], False):
ort: [array([False])]
torch: tensor([True])
```

Discovered from this issue opened against PyTorch ONNX exporter https://github.com/pytorch/pytorch/issues/60179

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.8.1
- Python version: 3.7.6
- PyTorch version: nightly

**To Reproduce**

```python
import onnxruntime as ort
import numpy as np
import torch

class M(torch.nn.Module):
    def forward(self, x):
        return torch.logical_xor(x, torch.tensor([False]))

x = torch.tensor([True, False])
import io
bitstream = io.BytesIO()
torch.onnx.export(M(), x, bitstream, opset_version=11, verbose=True, input_names=['x'], dynamic_axes={'x': [0]})

ort_sess = ort.InferenceSession(bitstream.getvalue())

ort_out = ort_sess.run(None, {ort_sess.get_inputs()[0].name: x.numpy()})
torch_out = M()(x)

print("Testing logical_xor ([True, False], False): ")
print('ort:', ort_out)
print('torch:', torch_out)

print("\nTesting logical_xor ([True], False): ")
x = torch.tensor([True])
ort_out = ort_sess.run(None, {ort_sess.get_inputs()[0].name: x.numpy()})
torch_out = M()(x)

print('ort:', ort_out)
print('torch:', torch_out)
```

edit: modified the repro script to be less pytorch version dependent.
edit: reopen as discovered turned out to be issue with xor instead of mod.

**Comment by BowenBao** [comment]
Closing for preparing a better repro

**Comment by hariharans29** [comment]
Interesting. Do you know if CUDA returns the right results ?

**Comment by BowenBao** [comment]
> Interesting. Do you know if CUDA returns the right results ?

CUDA returns right results. Did a quick validate with one ORT 1.8 gpu wheel I have in hand.
