### ISSUE TITLE
runtime error with DML: two nodes with same node name (Conv_xxx)

### ISSUE THREAD

**Issue by mrljwlm** [microsoft/onnxruntime#8905]
I export a yolact model with pytorch 1.7.1, when i load the model with C# api, it will come out this error:
[ErrorCode:RuntimeException]Exception during initialization: D:\3\s\onnxruntime\core\graph\function.cc260 onnxruntime::FunctionImpl::FunctionImpl status.IsOK() was false. This is an invalid model. Error: two nodes with same node name (Conv_xxx)

however, if i load the model with CPU or CUDA, i will be ok, this error just come out when using DML, anyone can give me some help? 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win10
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.6
- Python version: 3.8
- Visual Studio version (if applicable): vs2017
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by fdwr** [comment]
Can you open the "Yolact" model using Netron (https://github.com/lutzroeder/Netron, https://netron.app/) and verify if there are two nodes with the same name? If two nodes really do have the same name, then I'm unsure why CPU/CUDA execution providers work fine (maybe one node is optimized away somehow?), but it would definitely be a model bug if two nodes have the same name. Alternately, do you have a link to the converted .onnx model file? Thanks.

**Comment by mrljwlm** [comment]
> Can you open the "Yolact" model using Netron (https://github.com/lutzroeder/Netron, https://netron.app/) and verify if there are two nodes with the same name? If two nodes really do have the same name, then I'm unsure why CPU/CUDA execution providers work fine (maybe one node is optimized away somehow?), but it would definitely be a model bug if two nodes have the same name. Alternately, do you have a link to the converted .onnx model file? Thanks.

I have open the model using Netron, no nodes have the same name. Here is the model i used [model_yolact.rar](https://raw.githubusercontent.com/mrljwlm/hellow-world/master/model_yolact.rar)

**Comment by mrljwlm** [comment]
I found that when i disable the GraphOptimization using the below code, it will be OK
`session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_DISABLE_ALL);`

**Comment by fdwr** [comment]
Hmm, I'm not encountering any issues via [WinMLRunner](https://github.com/Microsoft/Windows-Machine-Learning/tree/master/Tools/WinMLRunner) with master (and I doubt it would be anything C# specific). There may have been fixes since then 🤔. Have you tried running it with ORT 1.8.2?

**Comment by jbrownkramer** [comment]
I'm having the same issue in ORT 1.9.0.  In my case the model is a slightly modified YOLOX model converted to onnx with the pytorch converted.  Works great on CPU, but claims there is a duplicated node name when I try to run on DirectML.  Works if I turn off optimizations.  There are 2 or 3 other issues on github with similar problems, so I think this is a real bug.

**Comment by fdwr** [comment]
@mrljwlm, @jbrownkramer  : Heads up, we have a pending fix for YoloV4, which very likely also applies to YoloX. https://github.com/microsoft/onnxruntime/pull/9929/files. It won't make ORT 1.10.0 release though, meaning it would need to be compiled from master (or possibly a 1.10.1 patch release).

**Comment by esawudi** [comment]
I'm having the same problem in 1.10.0 release  dml_provider.  cuda  cpu is working well. When will the next release be?

**Comment by fdwr** [comment]
@esawudi: Historically ORT releases (just looking at the releases page) have been every 2-3 months, but there might be a point release of 10.1. If so, we'll tag this PR with `rel-1.10.1` for the ONNX Runtime team to see (@faxu on ORT might know). Building source from master is an option too.

**Comment by esawudi** [comment]
Can I compile Based on 1.10.0 release source code , Just make this change you mentioned 
 https://github.com/microsoft/onnxruntime/pull/9929/files

**Comment by fdwr** [comment]
@esawudi : Yep, 9929 should be the only needed delta.

**Comment by esawudi** [comment]
Thank you for your patience.

**Comment by fdwr** [comment]
@esawudi Did applying that locally work for you? (https://github.com/microsoft/onnxruntime/pull/9929/ is completed in master either way)
