### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn’t export Python operator qfn

### ISSUE THREAD

**Issue by captain81** [microsoft/onnxruntime#8908]
Hi,
I’m trying to convert a pytorch model to onnx, but the conversion gives the following error:

RuntimeError: ONNX export failed: Couldn’t export Python operator qfn

The definition for qfn is:

class qfn(torch.autograd.Function):
@staticmethod
def forward(ctx, input, k):
n = float(2**k - 1)
out = torch.round(input * n) / n
return out

@staticmethod
def backward(ctx, grad_output):
    grad_input = grad_output.clone()
    return grad_input, None

qfn_tmp = qfn.apply

**Comment by faxu** [comment]
If this export is through PyTorch, could you open the issue in the PyTorch repo? https://github.com/pytorch/pytorch/issues
Please close this once the corresponding issue is filed.

**Comment by BowenBao** [comment]
@captain81 please check https://pytorch.org/docs/master/onnx.html#torch-autograd-functions how to properly export custom `torch.autograd.Function` classes.
