### ISSUE TITLE
Build for Android: No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

### ISSUE THREAD

**Issue by gdliang** [microsoft/onnxruntime#8946]
**Describe the bug**
**Hi, there is an error when i build the onnxruntime for android on windows(also on ubuntu18.04). The error is :**

> Task :stripDebugDebugSymbols FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripDebugDebugSymbols'.
> No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
29 actionable tasks: 28 executed, 1 up-to-date
make[2]: *** [CMakeFiles/onnxruntime4j_jni.dir/build.make:260: libonnxruntime4j_jni.so] Error 1
make[2]: *** Deleting file 'libonnxruntime4j_jni.so'
make[1]: *** [CMakeFiles/Makefile2:1067: CMakeFiles/onnxruntime4j_jni.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
Traceback (most recent call last):
  File "/e/3_DL/ONNX/onnxruntime2021083101/onnxruntime/tools/ci_build/build.py", line 2152, in <module>
    sys.exit(main())
  File "/e/3_DL/ONNX/onnxruntime2021083101/onnxruntime/tools/ci_build/build.py", line 2076, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/e/3_DL/ONNX/onnxruntime2021083101/onnxruntime/tools/ci_build/build.py", line 1067, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/e/3_DL/ONNX/onnxruntime2021083101/onnxruntime/tools/ci_build/build.py", line 581, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/e/3_DL/ONNX/onnxruntime2021083101/onnxruntime/tools/python/util/run.py", line 41, in run
    completed_process = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '--build', '/e/3_DL/ONNX/onnxruntime2021083101/onnxruntime/build/Android/Release', '--config', 'Release']' returned non-zero exit status 2.

I try to use different ndk version(eg:23.0  22.1  20.1 20.0) and gradle version(7.2 6.5 5.6 4.10), but it still throw the error.
I use the build command like this: 
./build.sh --config Release --android --android_sdk_path /d/libs/Android/Sdk --android_ndk_path /d/libs/Android/Sdk/ndk/20.0.5594570 --android_abi arm64-v8a --android_api 29 --build_java

and i'm sure the NDK toolchains folder has arm-linux-androideabi-4.9 folder. 

Thanks.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows10 and Ubuntu18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version:1.8.1
- Python version:3.8.5

**Expected behavior**
**I wish to build a whole android-onnxruntime aar file, as the prebuilt package has not some operators in my onnx model(eg, alone batchnormlization operator).**

**Comment by gwang-msft** [comment]
We don't yet support Gradle 7.
Please try Gradle 6.x (we use 6.8.3 in our pipeline), if it works, you can try to setup the Gradle wrapper under `<repro root>/java`, our java build script will use Gradle wrapper first.

**Comment by gdliang** [comment]
> We don't yet support Gradle 7.
> Please try Gradle 6.x (we use 6.8.3 in our pipeline) with NDK 21, if it works, you can try to setup the Gradle wrapper under `<repro root>/java`, our java build script will try to find Gradle wrapper there and use it first.
> 
> https://github.com/microsoft/onnxruntime/blob/06bb2ec561ff1012fac50fafb7a90a125b40839d/tools/ci_build/github/android/setup_gradle_wrapper.sh#L16-L19
> 
> Also please check if you have a different environment variable `ANDROID_NDK_HOME` than the actual `--android_ndk_path` in the build script.

I build successfully on ubuntu18.04 with ndk22.0 and gradle6.4 and get the aar files.(the error still exist on windows by using the same config. BTW, i use msys2 to build on windows).
Thanks.

**Comment by gwang-msft** [comment]
We tested our Windows Android cross build using Visual Studio 2019 + Gradle 6.5 + JDK 11, we have not tested using MinGW or mssys2
If there is C++ compiler issues related to MinGW, please see #7186

**Comment by gdliang** [comment]
> We tested our Windows Android cross build using Visual Studio 2019 + Gradle 6.5 + JDK 11, we have not tested using MinGW or mssys2
> If there is C++ compiler issues related to MinGW, please see #7186

Hi, there is another issue, if i can set the inference precision as fp16(default fp32) when running on android-cpu. I konw it is supported on nnapi. Thanks.

**Comment by gwang-msft** [comment]
For ONNX Runtime CPU execution provider, we do not support fp16 relaxation.
