### ISSUE TITLE
runing on two cpus machine is slower than one cpu machine

### ISSUE THREAD

**Issue by longpengcs** [microsoft/onnxruntime#897]
**Describe the bug**
I'm doing a project,and it has some cnn model,
1.  when I running the onnxruntime as the cnn backend in a machine which has one E5-2603v4 CPU (6 core @1.7GHZ with not open Hyper threading) it spend 5~6s ,but when we running it in a has two E5-2620 v3 (6 core @2.4GHZ with open Hyper threading) it just spend ~10s; On the other hand,when i using caffe2 as backend the first machine will be slower than second one.

2. when I running two same task in a machine with onnxruntime, them will be slower 4~5 times rather than 2 times, but when I using caffe2 as backend it close to 2 times slower.

3.  In the E5 2603 V4@1.7GHZ machine using onnxruntime faster than using caffe2 but in the E5 2620 v3@2.4GHZ machine them has same time spend，in addition，the caffe2 only using one cpu (6 core) but the onnxruntime will fill two cpu(12core).

I have no idea about the reason, the theoretical performance of the first machine is obviously lower than that of the second i think, does there were some mistakes?

Does there has performance loss when we using two cpus machine?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Centos7
- ONNX Runtime installed from (source or binary):docker 
- ONNX Runtime version:0.3.0
- Python version:3.5

**Comment by snnn** [comment]
How did you measure it? Were you using our onnxruntime_perf_test tool?

**Comment by longpengcs** [comment]
> How did you measure it? Were you using our onnxruntime_perf_test tool?

no, i'am using the time module in python to  statistics the time cost, just like:
  start = time.time()
  result = some_function_runing_cnn()
  print(time.time() - start)

**Comment by bitnick10** [comment]
if onnx using the six core with 12 hyper thread with a RAM frequecy less than 3200(assume E52620 support 2400MHZ) it would be the result that using more thread slower than the "right"(mabye 4 is fastest,depends on your model's input type float32 or float64) core using.it's RAM bottleneck.

**Comment by faxu** [comment]
@longpengcs Hi, is this still an issue you're experiencing?

**Comment by KeDengMS** [comment]
I think it might be related to [NUMA](https://software.intel.com/en-us/articles/optimizing-applications-for-numa). The recommendation is to create one process per NUMA node, so that weights would be placed in the memory for one NUMA node to access. You may set environment variable OMP_NUM_THREADS to control how many cpu cores to run in NUMA machines, and ideally it should be no more than cores in one NUMA node.

**Comment by jywu-msft** [comment]
followup to @KeDengMS's comment, one can use a combination of setting OMP_NUM_THREADS and numactl to force execution on the cpu cores of a specific NUMA node.
e.g. if a NUMA node has 12 cores,
export OMP_NUM_THREADS=12
numactl --physcpubind=0-11 --membind=0 ./your_application  

see https://www.unix.com/man-page/centos/8/numactl/

**Comment by longpengcs** [comment]
@jywu-msft @KeDengMS My model is very small and the machine has 128G memory, so i think there is a problem of muti-thread Scheduling. When I set the OMP_NUM_THREADS to a small value like 2 or 3, it get a better performance, and using numactl binding the process to one NUMA node can also get some improvement.

**Comment by jywu-msft** [comment]
closing as it sounds like OP's issue has been resolved.
