### ISSUE TITLE
ONNX runtime produces different inference results for the same input

### ISSUE THREAD

**Issue by lihan** [microsoft/onnxruntime#8970]
**Describe the bug**

ONNX runtime produces different inference results for the same input.

I worked out the issue being the use of `nn.RReLU()`

Please refer the below notebook.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab (Ubuntu 18.04.5 LTS)
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.8.1
- Python version: 3.7.11
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**

Please refer to this Google Colab notebook

https://colab.research.google.com/drive/123EBUIyhT-U-0N_-pxIM8E-nCoyvuLMw?usp=sharing

**Expected behavior**
It should produce the same outputs for the idential inputs

**Additional context**

* Use `nn.RReLU()` would cause this problem, tested other activation function like `LeackyReLu` does not cause the problem
* Not related to GPU, this is tested under only CPU

**Comment by lihan** [comment]
@hariharans29 Is there any update for this ticket? Thanks.

**Comment by hariharans29** [comment]
Hi @lihan - Thanks for checking in. I haven't had the chance to investigate this. Is this a blocking issue or are you able to use a different activation layer to unblock yourself ?

**Comment by hariharans29** [comment]
And does this repro with 1.9.0 as well ?

**Comment by lihan** [comment]
Hi @hariharans29 The issue remain in 1.9.0. For my use case, the ONNX deployment will be pending on this issue. Currently running on original Pytorch model.

**Comment by hariharans29** [comment]
Closing as this seems like the expected behavior. Please re-open if you have any concerns.

**Comment by SolomidHero** [comment]
@hariharans29
Hi, it is not expected on eval stage for model. Pytorch fixes slope when model is used to be in eval mode, but how is it possible to turn this exact behavior of slope fix to onnx model?
