### ISSUE TITLE
No implementation found for long ai.onnxruntime.OrtSession$SessionOptions.createOptions(long)

### ISSUE THREAD

**Issue by IdoZach** [microsoft/onnxruntime#8978]
Hi,
I'm trying to create an Android project that runs `onnxruntime` inference based on an `.ort` file, and I am following the instructions [here](https://onnxruntime.ai/docs/how-to/mobile/model-execution.html). 
I generated a `onnxruntime-1.8.2.jar` file by using the instructions from [here](https://onnxruntime.ai/docs/how-to/build/inferencing.html) and I included it in my project's `libs/` dir and gradle file. The code compiles, but when I execute the code, after the first line:
`SessionOptions session_options = new SessionOptions();`

I get a runtime error (on the phone, executing in Debug mode):
`No implementation found for long ai.onnxruntime.OrtSession$SessionOptions.createOptions(long) (tried Java_ai_onnxruntime_OrtSession_00024SessionOptions_createOptions and Java_ai_onnxruntime_OrtSession_00024SessionOptions_createOptions__J)`

I am not very familiar with Android projects, so any help would be appreciated. 

Edit: adding a few more notes - I'm developing on an x86 Linux and running the app on an arm64 phone. I'm trying (for now) to use a pre-built runtime and I'm following the [instructions](https://onnxruntime.ai/docs/how-to/mobile/model-execution.html) that only require adding a line to the gradle file.

**Comment by gwang-msft** [comment]
Android and Linux use different binaries, you cannot use `.jar` on Linux, if you prefer to build your own copy of onnxruntime, you will need to use the `<build folder>/Android/Release/java/build/android/outputs/aar/onnxruntime-[release/debug].aar`

**Comment by IdoZach** [comment]
I prefer to use a pre-built package - how do I use it? when I follow the instructions of pre-built runtime, where I don't need to add any file but only add a line in the gradle file, I get the same error I mentioned above.

**Comment by gwang-msft** [comment]
Please take a look at this example, although it is written in Kotlin
https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/image_classifications/android

**Comment by IdoZach** [comment]
Thanks.
