### ISSUE TITLE
How to apply "gpu_mem_limit" to CUDA Execution Provider in C#?

### ISSUE THREAD

**Issue by ThisIsBen** [microsoft/onnxruntime#8995]
I would like to apply "gpu_mem_limit" to CUDA Execution Provider in C#, but I can only find the examples that apply it in
Python and C/C++  in the following document.
https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements

I would be grateful if you could tell me how to apply "gpu_mem_limit" in C#.
Thanks in advance.

---
#### Document Details
* Title: CUDA
* Page: [https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html](https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html)
* Page Source: CUDA-ExecutionProvider.md

**Comment by skottmckay** [comment]
Currently that setting isn't exposed at the C# level. 

Is that required for your use case or just nice to have?

**Comment by hariharans29** [comment]
There are some open PRs that have attempted this:

https://github.com/microsoft/onnxruntime/pull/6291
https://github.com/microsoft/onnxruntime/pull/7315

If you want to contribute, please see the PR for exposing C# configuration knobs for the TRT EP: https://github.com/microsoft/onnxruntime/pull/7808. Using this PR as a template, some small changes to #6291 should enable the same for the CUDA EP as well.

**Comment by ThisIsBen** [comment]
@skottmckay Thank you for the quick reply.
"Applying "gpu_mem_limit" to CUDA Execution Provider in C#" is required for the system we are building.
We want to run 3 C# applications, and each of them uses an AI model for inference.
We only have one Nvidia GPU, so we attempted to make them share one Nvidia GPU ,but the GPU memory was not enough to go around. 
As a result, we need this feature badly to limit the GPU memory usage of each application to make them be able to share one GPU.

**Comment by ThisIsBen** [comment]
@hariharans29 Thank you for your response.
I want to give it a try to see whether I can help. 
I'm still a student and new to github. If possible, could you tell me how to start?

Are the following steps correct?
Step1 Fork microsoft/onnxruntime
Step2 Clone it and make a new branch in my local PC.
Step3 Refer to [#7808](https://github.com/microsoft/onnxruntime/pull/7808) and use it as a template
Step4 Refer to [#6291](https://github.com/microsoft/onnxruntime/pull/6291) to add "gpu_mem_limit" option to CUDA Execution Provider in C#
Step5 Push it to my github repo
Step6 Open a new pull request

**Comment by ThisIsBen** [comment]
@hariharans29 Thank you for your response.
I want to give it a try to see whether I can help. 
I'm still a student and new to github. 
If possible, could you please tell me how to start?

I was wondering whether the following steps are correct.
Step1 Fork microsoft/onnxruntime
Step2 Clone it and make a new branch in my local PC.
Step3 Refer to [#7808](https://github.com/microsoft/onnxruntime/pull/7808) and use it as a template
Step4 Refer to [#6291](https://github.com/microsoft/onnxruntime/pull/6291) to add "gpu_mem_limit" option to CUDA Execution Provider in C#
Step5 Push it to my github repo
Step6 Open a new pull request

**Comment by hariharans29** [comment]
Please see https://github.com/microsoft/onnxruntime/pull/10188
