### ISSUE TITLE
cannot convert from 'initializer list' to 'Ort::Session' using VS2019 community

### ISSUE THREAD

**Issue by roachsinai** [microsoft/onnxruntime#9001]
**Describe the bug**

Error	C2440	'<function-style-cast>': cannot convert from 'initializer list' to 'Ort::Session'	

**Urgency**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): download from github release
- ONNX Runtime version:1.8.1
- Python version:
- Visual Studio version (if applicable):2019 community lastest
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.1
- GPU model and memory:

**To Reproduce**

```
Ort::Session m_session; // this line in class definition
m_session = Ort::Session(m_env, m_modelPath.c_str(), sessionOptions); // in member function
```

**Screenshots**

![image](https://user-images.githubusercontent.com/9500049/132535336-9b1ef5e8-1f0d-40b1-b184-d731f8aef439.png)

Thanks in advance!

**Comment by HectorSVC** [comment]
Ort::Session m_session;  if this is in in class definition, 
m_session = Ort::Session(m_env, m_modelPath.c_str(), sessionOptions); -- then this should be in class constructor.
or you should use pointer.

**Comment by HectorSVC** [comment]
Let us know if you have further questions, otherwise we will close it in a day.

**Comment by roachsinai** [comment]
> It's relate to C/C++ language programming syntax. nothing wrong with Ort.
> Ort::Session m_session; if this is in in class definition,
> m_session = Ort::Session(m_env, m_modelPath.c_str(), sessionOptions); -- then this should be in class constructor.
> or you should use pointer.

Thank for your reply! But, it works well with g++ in Linux...

**Comment by lucasjinreal** [comment]
@HectorSVC

> It's relate to C/C++ language programming syntax. nothing wrong with Ort.
Ort::Session m_session; if this is in in class definition,
m_session = Ort::Session(m_env, m_modelPath.c_str(), sessionOptions); -- then this should be in class constructor.
or you should use pointer.

I am exactly write it, but windows not compile.

**Comment by Plwy** [comment]
I have encountered the same problem, it works well in linux but when i compile it in visual studio 2022, it reports error "cannot convert from 'initializer list' to 'Ort::Session' " , i don't know how to fix it.

**Comment by Plwy** [comment]
> 
I have already solved this problem. my code in linux：
```
std::string model_path = "model.onnx";
session_ = Ort::Session(env_, model_path.c_str(), session_options_);
```
I have modified it to the following code,and it works in windows.
```
std::string model_path = "model.onnx";
std::wstring wModel_path(model_path.begin(), model_path.end());
session_ = Ort::Session(env_, wModel_path.c_str(), session_options_);
```
 it is due to  the difference of `wchar_t*` in different platform.
