### ISSUE TITLE
cuda provider Ort::Session Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by BChunlei** [microsoft/onnxruntime#9011]
**Describe the bug**
When creatinig the session by Ort::Session session(env, model_path, session_options);  I got the error：Segmentation fault (core dumped). This is my code：

Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "");
  Ort::SessionOptions session_options;
  session_options.SetIntraOpNumThreads(1);
  session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);
  OrtCUDAProviderOptions cuda_options;
  cuda_options.device_id = 0;
  session_options.AppendExecutionProvider_CUDA(cuda_options);
  const char* model_path = "./yolov3_608.onnx";
  Ort::Session session(env, model_path, session_options);

I build the onnruntime from source:
./build.sh --build_shared_lib --cuda_home /usr/local/cuda-10.2 --cudnn_home /usr/lib/x86_64-linux-gnu/ --use_cuda --config Release --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=1.8.2

I use the following command to compile my code:
g++ onnx_infer.cpp -o infer onnxruntime/build/Linux/Release/libonnxruntime.so.1.8.2 -I onnxruntime/include/onnxruntime/core/session/ -std=c++11 `pkg-config opencv --cflags --libs` -D USE_CUDA=ON

It can compile successfully, but when I run ./infer, it shows the 'Segmentation fault (core dumped)'.

when I mark the following code, recompile it and do ./infer, it works. 
/*
OrtCUDAProviderOptions cuda_options;
cuda_options.device_id = 0;
session_options.AppendExecutionProvider_CUDA(cuda_options);
*/

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- ONNX Runtime installed from (source or binary):source 
- ONNX Runtime version:1.8.2
- Python version:3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):7.5.0
- CUDA/cuDNN version:10.2
- GPU model and memory:

**To Reproduce**
This is my onnx model：
link：https://pan.baidu.com/s/1875R9V_iUFUTk4N0eaPUpw 
code：p2pa

**Comment by BChunlei** [comment]
it's ok, my code has some pronlem.

**Comment by isgursoy** [comment]
What was it?
