### ISSUE TITLE
1.8.2 : DirectML inference performance of model opset-13 is ~x4 slower than opset-9

### ISSUE THREAD

**Issue by iperov** [microsoft/onnxruntime#9015]
**Describe the bug**

DirectML inference performance of model opset-13 is x4 slower than opset-9

both models are extracted from the same graph using code:
```
import tf2onnx
with tf.device("/CPU:0"):
    model_proto, _ = tf2onnx.convert._convert_common(
        output_graph_def,
        name='SAEHD',
        input_names=['in_face:0'],
        output_names=['out_face_mask:0','out_celeb_face:0','out_celeb_face_mask:0'],
        opset=9, # <<-- also with 13
        output_path=output_path)
```

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): source/wheel
- ONNX Runtime version: 1.8.2
- Python version: 3.7.9
- tf2onnx version: 1.9.2
- DirectML build: https://github.com/iperov/DeepFaceLive/releases/download/ort-dml/onnxruntime_directml-1.8.2-cp37-cp37m-win_amd64.whl
- GPU model and memory: RTX 3090

**To Reproduce**

download onnx models

https://github.com/iperov/DeepFaceLive/releases/download/trash/opset-9.onnx
https://github.com/iperov/DeepFaceLive/releases/download/trash/opset-13.onnx

inference with timeit:
```
import onnxruntime as rt
import timeit
import numpy as np

sess_options = rt.SessionOptions()
sess_options.enable_mem_pattern = False # for DML 
    
device_id = 1 # your device id
sess_opset_9  = rt.InferenceSession(r'opset-9.onnx',  providers=[ ('DmlExecutionProvider', {'device_id':device_id}) ], sess_options=sess_options)
sess_opset_13 = rt.InferenceSession(r'opset-13.onnx', providers=[ ('DmlExecutionProvider', {'device_id':device_id}) ], sess_options=sess_options)

img = np.zeros( (1,224,224,3), np.float32)

print('opset9 : ',  timeit.timeit(stmt="sess_opset_9.run(None, {'in_face:0': img})", number=100, globals=globals() ) )
print('opset13 : ', timeit.timeit(stmt="sess_opset_13.run(None, {'in_face:0': img})", number=100, globals=globals() ) )
```

result:
```
opset9 :  1.3559255
opset13 :  5.6362138
```

by the way opset9 model inference of DirectML matches the speed of onnxruntime-CUDA version

**Expected behavior**

expected not to downgrade performance of DirectML with model 13 opset version

**Comment by fdwr** [comment]
DirectML supports up to opset 12 in ORT master (yes, we're behind CPU support). So fallback to CPU is happening with GPU/CPU synchronization stalls. We will focus on catching up to current ONNX for the upcoming ORT release. If you don't use any ops specific to opset 13, does 12 exhibit the perf cliff?

**Comment by iperov** [comment]
@fdwr is it possible to fallback to lower opset version but GPU first ?

**Comment by fdwr** [comment]
@iperov: With how ONNX versioning works, if the model requires opset 13, then older code makes no assumptions about forward compatibility (backwards compatibility is maintained, but not the other way), because the opset could have changed an operator's attributes in an incompatible way (and they have). Looking at your .onnx files though, I didn't see anything 13-specific, just older operators. Can you retarget your ONNX model with the convertor you used to opset 12?

**Comment by iperov** [comment]
currently I am using opset-9.

I will wait official pypi onnxruntime-directml release with fully implemented opset 13 on gpu.

**Comment by fdwr** [comment]
(update) Was reading [here](https://github.com/onnx/tensorflow-onnx) that tf2onnx by default targets opset 9. So I'm guessing you passed `--opset 13` explicitly? We added more opset 13 in [ORT 1.10](https://github.com/microsoft/onnxruntime/releases/tag/v1.10.0) which should reduce the mixed fallback to CPU, but we still have some more gaps to fill.

**Comment by fdwr** [comment]
ONNX Runtime 1.12.1 is out, including opset 13-15 support. https://github.com/microsoft/onnxruntime/releases/tag/v1.12.1
