### ISSUE TITLE
[js/web] Unauthorized request when loading model from url

### ISSUE THREAD

**Issue by fadiatamny** [microsoft/onnxruntime#9031]
Hi, 
i am trying to load the weights file that is on a file server that is secure with credentials. 
any request that does not have credentials will be blocked.

as i see from the code the function loadModel in session.ts does not have support for fetchOptions object.

Would it be possible to add a quick fix to allow sending options for the fetch method ?

**Comment by fs-eire** [comment]
Thanks for your feedback. This issue is transferred to onnxruntime repo and will be implemented in ONNX Runtime Web.

**Comment by fadiatamny** [comment]
> Thanks for your feedback. This issue is transferred to onnxruntime repo and will be implemented in ONNX Runtime Web.

Ive went ahead and tried to implement the solution my self. i attempted to run tests locally but had issues with missing files and definitions. i hope what i've done is good enough and satisfies the code quality. let me know if i can help further. 

Have a nice day!

**Comment by fadiatamny** [comment]
For now a solution offered by @fs-erie is a 2 step method of fetching the file myself and then providing it as an ArrayBuffer to the loadSession function. code below is an example of how I got it to work.

```ts
        const session = new InferenceSession()
        const fetchOptions: RequestInit = { credentials: 'include' }
        const res = await fetch(uri, fetchOptions)
        const buff = await res.arrayBuffer()
        await session.loadModel(buff)
```

**Comment by guschmue** [comment]
assume this is fixed.
