### ISSUE TITLE
Invalid value of arena_extend_strategy

### ISSUE THREAD

**Issue by dgfiloso** [microsoft/onnxruntime#9038]
**Describe the bug**
I am using the CUDA Execution Provider to run an inference, but in runtime I am getting an error when assigning values to the ```OrtCUDAProviderOptions```. The error I am getting is an invalid value for ```arena_extend_strategy```. The error is:

```
2021-09-13 07:20:37.975714070 [E:onnxruntime:onnx_env, allocatormgr.cc:47 CreateAllocator] Received invalid value of arena_extend_strategy 260058
```

My code for assigning the CUDA options is the following:

```
pEnv_ = new Ort::Env(ORT_LOGGING_LEVEL_WARNING, "onnx_env");
sessionOptions_.SetIntraOpNumThreads(1);
sessionOptions_.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);

OrtCUDAProviderOptions cudaOptions;
cudaOptions.device_id = 0;
cudaOptions.arena_extend_strategy = 0;
cudaOptions.gpu_mem_limit = 1 * 1024 * 1024 * 1024;
cudaOptions.cudnn_conv_algo_search = OrtCudnnConvAlgoSearch::EXHAUSTIVE;
cudaOptions.do_copy_in_default_stream = 1;
sessionOptions_.AppendExecutionProvider_CUDA(cudaOptions);
```

The same code works fine for version v1.6.0, only changing ```gpu_mem_limit``` to ```cuda_mem_limit```.

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Docker container of image nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.8.2
- Python version: Not compiled
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 11.1 / 8
- GPU model and memory: GeForce GTX 750

**Comment by RyanUnderhill** [comment]
An additional field 'default_memory_arena_cfg' was added to OrtCUDAProviderOptions, can you check to be sure this is initialized to nullptr? If it is set, it will override the arena_extend_strategy.

**Comment by dgfiloso** [comment]
I was not aware of that new field. Just be adding it and setting it to ```nullptr``` my error has been solved. Thank you very much for your help.

**Comment by RyanUnderhill** [comment]
@dgfiloso Sorry that you ran into that, I'm pushing a fix that will auto initialize the structure with valid defaults if compiled under C++, so that this won't happen again: https://github.com/microsoft/onnxruntime/pull/9064

**Comment by dgfiloso** [comment]
> @dgfiloso Sorry that you ran into that, I'm pushing a fix that will auto initialize the structure with valid defaults if compiled under C++, so that this won't happen again: #9064

@RyanUnderhill Thank you for the quick support and fix.
