### ISSUE TITLE
NNAPI on Android works great with Samsung Galaxy S9 but not with Redmi Note 9

### ISSUE THREAD

**Issue by vltmrkls** [microsoft/onnxruntime#9039]
**NNAPI on Redmi Note 9 reported to be not working**

I have successfully deployed an Android App with onnxruntime 1.8.1 and would like to tune the performance on Android.
       
 ```
uint32_t nnapi_flags = 0;
Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_Nnapi(session_options, nnapi_flags));
```
i get 2 x faster inferences on my Samsung Galaxy S9 which is great!

On Redmi Note 9 device i get this error log:
**Failed to read /vendor/etc/nnapi_extensions_app_allowlist ; No app allowlisted for vendor extensions use.**
The activations are also incorrect.

any hint? 

**Urgency**
Very nice to have.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Big Sur
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.8.1
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by gwang-msft** [comment]
Can you be more specific about the error you encountered? Did ONNX Runtime throw or crash when you try to use NNAPI on Redmi Note 9?
The "Failed to read /vendor/etc/nnapi_extensions_app_allowlist ..." is an info level log and should not cause catastrophic error.

**Comment by vltmrkls** [comment]
The result of the inferencing is different than what is expected. The results are more or less random.

**Comment by gwang-msft** [comment]
Please try to force the NNAPI execution on CPU only to see if the inference result is correct, please change this line 
https://github.com/microsoft/onnxruntime/blob/be8069869880c5981f4df3f8af5cc6e534e0ef11/onnxruntime/core/providers/nnapi/nnapi_builtin/builders/model_builder.h#L158
to
```
  TargetDeviceOption target_device_option_{TargetDeviceOption::CPU_ONLY};
```
and recompile the ORT library and see if the execution result is correct

**Comment by vltmrkls** [comment]
i applied and recompiled the ORT with `TargetDeviceOption::CPU_ONLY` but the result is still wrong. The result is not as random but still incorrect. 
I debugged on a Xiaomi Redmi Note 8T.

further logs:
NnapiExecutionProvider::GetCapability, number of partitions supported by NNAPI: 7 number of nodes in the graph: 23 number of nodes supported by NNAPI: 17

**Comment by gwang-msft** [comment]
The CPU only option is only available on Android 10+ (API SDK 29+), the inconsistency of the inferencing result is probably related to the vendor driver, please report the issue to the hardware manufacturer. See the similar issue, #4993

For the partition logs, please share the model if possible.
