### ISSUE TITLE
build failure with gcc 10 and cuda 11.4

### ISSUE THREAD

**Issue by boxerab** [microsoft/onnxruntime#9046]
Using master branch on Ubuntu 20.10

cmake command:

```
 cmake -Donnxruntime_BUILD_SHARED_LIB=ON -DBUILD_TESTING=OFF -Donnxruntime_USE_CUDA=ON -Donnxruntime_CUDA_HOME=$CUDA_PATH -Donnxruntime_CUDNN_HOME=$CUDA_PATH cmake && make -j48 && sudo make install
```

Error:

```
/home/src/onnxruntime/onnxruntime/core/providers/cuda/cudnn_common.cc:118:5: error: use of typeid requires -frtti
    typeid(ElemType).name());
    ^
1 error generated.
```

**Comment by snnn** [comment]
Please set this option to OFF:

https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L113

**Comment by boxerab** [comment]
thank you, @snnn ! May I ask why the default is to disable RRTI  ? Also, is this setting needed only with GCC 10 and above ?

**Comment by boxerab** [comment]
this works, thanks.

**Comment by snnn** [comment]
My mistake. I will submit a PR to fix it.

**Comment by boxerab** [comment]
thank you

**Comment by snnn** [comment]
Could you help me test if the new fix works?  Delete your build dir , checkout "snnn-patch-4" branch and build it again.

**Comment by boxerab** [comment]
thanks, @snnn your branch builds without error.
