### ISSUE TITLE
Unsupported gpu architecture 'compute_86'

### ISSUE THREAD

**Issue by BChunlei** [microsoft/onnxruntime#9052]
**Describe the bug**
command:
./build.sh --build_shared_lib --cuda_home /usr/local/cuda-10.2 --cudnn_home /usr/lib/x86_64-linux-gnu/ --use_cuda --config Release --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=1.8.2 CMAKE_CUDA_ARCHITECTURES=86

error:
[  1%] Building CUDA object CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/workspace/onnxruntime/onnxruntime/test/shared_lib/cuda_ops.cu.o
[  1%] Built target onnxruntime_generate_def
[  1%] Built target flatbuffers
[  1%] Built target onnxruntime_mocked_allocator
Scanning dependencies of target libprotobuf-lite
[  1%] Performing update step for 'pybind11'
nvcc fatal   : Unsupported gpu architecture 'compute_86'
[  1%] Built target gtest
CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/build.make:81: recipe for target 'CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/workspace/onnxruntime/onnxruntime/test/shared_lib/cuda_ops.cu.o' failed
make[2]: *** [CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/workspace/onnxruntime/onnxruntime/test/shared_lib/cuda_ops.cu.o] Error 1
CMakeFiles/Makefile2:594: recipe for target 'CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_test_cuda_ops_lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

Makefile:181: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 2162, in <module>
    sys.exit(main())
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 2086, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 1064, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/workspace/onnxruntime/tools/ci_build/build.py", line 579, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/workspace/onnxruntime/tools/python/util/run.py", line 44, in run
    env=env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '/workspace/onnxruntime/build/Linux/Release', '--config', 'Release', '--', '-j12']' returned non-zero exit status 2.

**System information**
- onnxruntime:1.8.2
- CUDA/cuDNN version:10.2
- GPU model and memory:RTX 3080

Does onnxruntime:1.8.2 support RTX 3080 （CMAKE_CUDA_ARCHITECTURES=86）？

**Comment by jywu-msft** [comment]
cuda 10.2 doesn't support 86 cuda arch , you need to use CUDA 11.x for ampere support.

**Comment by BChunlei** [comment]
It's ok, thanks.
