### ISSUE TITLE
Use CONFIGURE_DEPENDS in file(GLOB*

### ISSUE THREAD

**Issue by letmaik** [Microsoft/onnxruntime#906]
ONNX RT makes heavy use of globbing to collect source files in the CMake scripts. This can lead to breaks when doing incremental builds where files are removed/added without otherwise touching the CMake files. This issue can be avoided either by explicitly listing all source files, or by using [`CONFIGURE_DEPENDS`](https://cmake.org/cmake/help/v3.13/command/file.html#glob-recurse) which re-runs glob during build to check whether CMake has to be re-configured.

Note that this is only an issue when not using the `tools/ci_build/build.py` script (which by default would do an `--update` that re-configures CMake each time) and instead running CMake directly. Using CMake directly is useful when consuming onnxruntime via `add_subdirectory` from another project.

**Comment by snnn** [comment]
For the two options, I'd prefer explicitly listing them, as it always works.

**Comment by letmaik** [comment]
I put the other alternative in the issue title as I had the feeling that the dev team prefers to touch CMake files as infrequently as possible, and listing all source files explicitly would mean more changes to CMake files when adding/removing/moving files. Before jumping to a PR for explicitly listing all files it would be good to get agreement from other devs as well, to avoid big surprises at PR time and potentially rejecting it at that point.

**Comment by snnn** [comment]
May I know how much does it bother you? It's not a problem for me because whenever I sync the code with remote or switch a branch, I always delete the whole build directory. CONFIGURE_DEPENDS will make incremental builds better, but, still, they are not reliable. I still need to empty the build dir frequently, then what's the difference?

**Comment by letmaik** [comment]
It's not a big problem, but still, would be nice to improve dev experience. Why do you think CONFIGURE_DEPENDS is not enough to make builds reliable? If there are other issues, then they should be fixed as well.

**Comment by pranavsharma** [comment]
CONFIGURE_DEPENDS seems like a good solution to me.

**Comment by pranavsharma** [comment]
@letmaik if this solution works for you feel free to contribute. Thanks!
