### ISSUE TITLE
doc page for execution providers doesn't exist.

### ISSUE THREAD

**Issue by sylvain-ri** [microsoft/onnxruntime#9078]
When googling execution providers on google, I end up on the following page, that does not exist:
https://onnxruntime.ai/docs/reference/execution-providers/

**System information**
window 10, chrome.

**Comment by cassiebreviu** [comment]
Hey @sylvain-ri, we recently reorganized and updated our docs. This page can be found here: https://onnxruntime.ai/docs/execution-providers.
Thanks!
Cassie

**Comment by sylvain-ri** [comment]
Okay thanks. Waiting for google search to update its results.
