### ISSUE TITLE
Op with name (Atan_994) and type (Atan) kernel not found in CPUExecutionProvider

### ISSUE THREAD

**Issue by cjwang528** [microsoft/onnxruntime#9090]
**Describe the bug**

After converting an onnx model into a ort model, I get the following error trying to execute the ort model on android devices

  ai.onnxruntime.OrtException: Error code - ORT_NOT_IMPLEMENTED - message: Failed to find kernel for Atan(7) (node Atan_1052). Op with name (Atan_1052) and type (Atan) kernel not found in CPUExecutionProvider. No matching hash for 6156207978523300880

Following is the required_operators.config

ai.onnx;1;GlobalAveragePool,Transpose
ai.onnx;5;Reshape
ai.onnx;6;Neg,Relu,Sqrt
ai.onnx;7;Add,Atan,Div,Mul,Sub
ai.onnx;8;Expand
ai.onnx;9;BatchNormalization,Cast,Greater,Less,Where
ai.onnx;11;Concat,Conv,Flatten,Gather,Gemm,ReduceL2,ReduceSum,Resize,ScatterND,Slice,Unsqueeze
ai.onnx;12;Clip,MaxPool,Pow
com.microsoft;1;FusedConv

How can I solve this problem? Thank you

**Comment by gwang-msft** [comment]
`Atan` is not part of our pre-built package, see [ONNX Runtime 1.8: Mobile Package Operator and Type Support](https://onnxruntime.ai/docs/reference/mobile/prebuilt-package/1.8%20ORTMobilePackageOperatorTypeSupport)

You will need to build your own custom built package for Android, see https://onnxruntime.ai/docs/tutorials/mobile/custom-build.html

**Comment by cjwang528** [comment]
thank you!
