### ISSUE TITLE
32 cores is not faster than 16 cores

### ISSUE THREAD

**Issue by sxk2009** [microsoft/onnxruntime#9096]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version: 1.4
- Python version: 3.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by sxk2009** [comment]
please help me workout

**Comment by hariharans29** [comment]
Please fill in the issue template with details with the relevant model and sample code and other details like platform, hardware, etc.
