### ISSUE TITLE
how to build on centos6.9

### ISSUE THREAD

**Issue by zhb0920** [microsoft/onnxruntime#9098]
undifined reference to 'memory@GLIBC_2.14'

centos6.9
无法升级

**Comment by chilo-ms** [comment]
Could you share more detailed information regarding what build command and Onnxruntime version you were using as well as pasting more error message if possible.

**Comment by zhb0920** [comment]
> Could you share more detailed information regarding what build command and Onnxruntime version you were using as well as pasting more error message if possible.
> 
> Your platform might miss some libraries. We have centos based [docker image](https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/docker/Dockerfile.manylinux2014_cuda11) and you can try it on this docker image.

`[  0%] Built target custom_op_library
[  0%] Built target clog
[  1%] Built target flatbuffers
[ 12%] Built target libprotobuf
[ 24%] Built target libprotoc
[ 24%] Built target protoc
[ 25%] Built target onnx_proto
[ 27%] Built target cpuinfo
[ 27%] Building CXX object CMakeFiles/onnxruntime_common.dir/home/zhb/code/onnxruntime/onnxruntime/core/common/logging/logging.cc.o
/home/zhb/code/onnxruntime/onnxruntime/core/common/logging/logging.cc: In constructor ‘onnxruntime::logging::LoggingManager::LoggingManager(std::unique_ptr<onnxruntime::logging::ISink>, onnxruntime::logging::Severity, bool, onnxruntime::logging::LoggingManager::InstanceType, const string*, int)’:
/home/zhb/code/onnxruntime/onnxruntime/core/common/logging/logging.cc:111:19: error: ‘is_always_lock_free’ is not a member of ‘std::remove_reference_t<std::atomic<void*>&> {aka std::atomic<void*>}’
     static_assert(std::remove_reference_t<decltype(DefaultLoggerManagerInstance())>::is_always_lock_free);
                   ^
/home/zhb/code/onnxruntime/onnxruntime/core/common/logging/logging.cc:111:105: error: expected ‘,’ before ‘)’ token
     static_assert(std::remove_reference_t<decltype(DefaultLoggerManagerInstance())>::is_always_lock_free);
                                                                                                         ^
/home/zhb/code/onnxruntime/onnxruntime/core/common/logging/logging.cc:111:105: error: expected string-literal before ‘)’ token
gmake[2]: *** [CMakeFiles/onnxruntime_common.dir/home/zhb/code/onnxruntime/onnxruntime/core/common/logging/logging.cc.o] Error 1
gmake[1]: *** [CMakeFiles/onnxruntime_common.dir/all] Error 2
gmake: *** [all] Error 2
Traceback (most recent call last):
  File "/home/zhb/code/onnxruntime/tools/ci_build/build.py", line 2324, in <module>
    sys.exit(main())
  File "/home/zhb/code/onnxruntime/tools/ci_build/build.py", line 2245, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/zhb/code/onnxruntime/tools/ci_build/build.py", line 1174, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/zhb/code/onnxruntime/tools/ci_build/build.py", line 625, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/zhb/code/onnxruntime/tools/python/util/run.py", line 45, in run
    env=env, shell=shell)
  File "/usr/local/python3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/zhb/code/cmake-3.18.0-Linux-x86_64/bin/cmake', '--build', '/home/zhb/code/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo']' returned non-zero exit status 2.
[root@zhb onnxruntime]#
`

**Comment by zhb0920** [comment]
> Could you share more detailed information regarding what build command and Onnxruntime version you were using as well as pasting more error message if possible.
> 
> Your platform might miss some libraries. We have centos based [docker image](https://github.com/microsoft/onnxruntime/blob/master/tools/ci_build/github/linux/docker/Dockerfile.manylinux2014_cuda11) and you can try it on this docker image.


centos6.9
gcc 5.4
g++ 5.4
cmakke 3.18

[  0%] Built target custom_op_library
[  0%] Built target clog
[  1%] Built target flatbuffers
[ 12%] Built target libprotobuf
[ 24%] Built target libprotoc
[ 24%] Built target protoc
[ 25%] Built target onnx_proto
[ 27%] Built target cpuinfo
[ 27%] Building CXX object CMakeFiles/onnxruntime_common.dir/home/zhb/code/onnxruntime/onnxruntime/core/common/logging/logging.cc.o
/home/zhb/code/onnxruntime/onnxruntime/core/common/logging/logging.cc: In constructor ‘onnxruntime::logging::LoggingManager::LoggingManager(std::unique_ptr<onnxruntime::logging::ISink>, onnxruntime::logging::Severity, bool, onnxruntime::logging::LoggingManager::InstanceType, const string*, int)’:
/home/zhb/code/onnxruntime/onnxruntime/core/common/logging/logging.cc:111:19: error: ‘is_always_lock_free’ is not a member of ‘std::remove_reference_t<std::atomic<void*>&> {aka std::atomic<void*>}’
     static_assert(std::remove_reference_t<decltype(DefaultLoggerManagerInstance())>::is_always_lock_free);
                   ^
/home/zhb/code/onnxruntime/onnxruntime/core/common/logging/logging.cc:111:105: error: expected ‘,’ before ‘)’ token
     static_assert(std::remove_reference_t<decltype(DefaultLoggerManagerInstance())>::is_always_lock_free);
                                                                                                         ^
/home/zhb/code/onnxruntime/onnxruntime/core/common/logging/logging.cc:111:105: error: expected string-literal before ‘)’ token
gmake[2]: *** [CMakeFiles/onnxruntime_common.dir/home/zhb/code/onnxruntime/onnxruntime/core/common/logging/logging.cc.o] Error 1
gmake[1]: *** [CMakeFiles/onnxruntime_common.dir/all] Error 2
gmake: *** [all] Error 2
Traceback (most recent call last):
  File "/home/zhb/code/onnxruntime/tools/ci_build/build.py", line 2324, in <module>
    sys.exit(main())
  File "/home/zhb/code/onnxruntime/tools/ci_build/build.py", line 2245, in main
    build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
  File "/home/zhb/code/onnxruntime/tools/ci_build/build.py", line 1174, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/zhb/code/onnxruntime/tools/ci_build/build.py", line 625, in run_subprocess
    return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
  File "/home/zhb/code/onnxruntime/tools/python/util/run.py", line 45, in run
    env=env, shell=shell)
  File "/usr/local/python3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/zhb/code/cmake-3.18.0-Linux-x86_64/bin/cmake', '--build', '/home/zhb/code/onnxruntime/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo']' returned non-zero exit status 2.
[root@zhb onnxruntime]#

**Comment by snnn** [comment]
Sorry it is not supported.

**Comment by snnn** [comment]
onnxruntime version < 1.8.0 can support CentOS6 with Red hat devtoolset.

**Comment by zhb0920** [comment]
> onnxruntime version <=1.4.0 can support CentOS6. Our official python packages were built on CentOS6. Later on we upgrade it to CentOS 7 because CentOS 6 is EOL. I don't know if onnxruntime 1.5/1.6/1.7/1.8 still can be built on CentOS6. You may try.

[54%] Building ASM object CMakeFiles/onnxruntime mLas.dir/home/zhb/Downloads/onnxruntime1.4.0/onnxruntime/core/mLas/lib/x86 64/QgemmU8S8KerneLAvx2.S.o ccl: error: unrecognized command line option "-mavx2" gmake[2]:*** [CMakeFiles/onnxruntimemLas.dir/home/zhb/DownLoads/onnxruntime-1.4.0/onnxruntime/core/mLas/lib/x86 64/QgemmU8S8KerneLAvx2.S.o] Error 1 gmake[1]:***[CMakeFiles/onnxruntime mLas.dir/all] Error 2 gmake:***[all] Error 2

**Comment by zhb0920** [comment]
> onnxruntime version <=1.4.0 can support CentOS6. Our official python packages were built on CentOS6. Later on we upgrade it to CentOS 7 because CentOS 6 is EOL. I don't know if onnxruntime 1.5/1.6/1.7/1.8 still can be built on CentOS6. You may try.

[54%] Building ASM object CMakeFiles/onnxruntime mLas.dir/home/zhb/Downloads/onnxruntime1.4.0/onnxruntime/core/mLas/lib/x86 64/QgemmU8S8KerneLAvx2.S.o ccl: error: unrecognized command line option "-mavx2" gmake[2]:*** [CMakeFiles/onnxruntimemLas.dir/home/zhb/DownLoads/onnxruntime-1.4.0/onnxruntime/core/mLas/lib/x86 64/QgemmU8S8KerneLAvx2.S.o] Error 1 gmake[1]:***[CMakeFiles/onnxruntime mLas.dir/all] Error 2 gmake:***[all] Error 2

**Comment by yufenglee** [comment]
> > onnxruntime version <=1.4.0 can support CentOS6. Our official python packages were built on CentOS6. Later on we upgrade it to CentOS 7 because CentOS 6 is EOL. I don't know if onnxruntime 1.5/1.6/1.7/1.8 still can be built on CentOS6. You may try.
> 
> [54%] Building ASM object CMakeFiles/onnxruntime mLas.dir/home/zhb/Downloads/onnxruntime1.4.0/onnxruntime/core/mLas/lib/x86 64/QgemmU8S8KerneLAvx2.S.o ccl: error: unrecognized command line option "-mavx2" gmake[2]:*** [CMakeFiles/onnxruntimemLas.dir/home/zhb/DownLoads/onnxruntime-1.4.0/onnxruntime/core/mLas/lib/x86 64/QgemmU8S8KerneLAvx2.S.o] Error 1 gmake[1]:_**[CMakeFiles/onnxruntime mLas.dir/all] Error 2 gmake:**_[all] Error 2

Same question as #9153
