### ISSUE TITLE
Quantization optimization for mobile

### ISSUE THREAD

**Issue by IdoZach** [microsoft/onnxruntime#9099]
Hi, following [this topic](https://github.com/microsoft/onnxruntime/issues/9054), I have the following floating point onnx model:
https://github.com/IdoZach/onnx/blob/master/model.onnx.gz , 
and the following statically quantized model: https://github.com/IdoZach/onnx/blob/master/model_quant.onnx.gz , what I quantized with a calibration dataset by using the following code:
```
quantize_static(model_in, model_out, Dataset(), quant_format=QuantFormat.QOperator, per_channel=False, weight_type=QuantType.QInt8)
```
According to the thread above, the model performs Quant/Dequant around the MaxPool layers, how can I further optimize this, and are there further optimizations that can be done to speed up the model inference?

Thanks.

**Comment by yufenglee** [comment]
@IdoZach , your model version is with opset 11, which doesn't support MaxPool with int8/uint8. Please upgrade your model to opset12 and above to remove the Quant/Dequant. You may refer to this wiki to upgrade your onnx version: https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md#converting-version-of-an-onnx-model-within-default-domain-aionnx

**Comment by IdoZach** [comment]
When using `opset=12`, I do get a cleaner onnx model (image below), but when I rebuild the onnxruntime libraries to match the requirements config (below), I get a runtime error when using the resulting ORT model, converted with _basic_ optimization level. I'm using, as before, NDK 21 and Android API 29, to build the libraries.

Config:
```
ai.onnx;10;DequantizeLinear,QLinearConv,QuantizeLinear
ai.onnx;12;MaxPool
com.microsoft;1;QLinearAdd
```
quantized model (excerpt):
![image](https://user-images.githubusercontent.com/25578860/133893065-e6660555-1412-4f5d-a3fa-843833fe1bd9.png)

Runtime error when starting the session:
```
E/Utils: NN_RET_CHECK failed (frameworks/ml/nn/common/Utils.cpp:520): type.scale > 0.f (type.scale = 0, 0.f = 0) ANeuralNetworksModel_addOperand invalid scale
    NN_RET_CHECK failed (frameworks/ml/nn/common/Utils.cpp:611): validateQuant8AsymmParams(type, tag) 
E/onnxruntime:  [E:onnxruntime:ort-java, graph_partitioner.cc:459 PartitionOrtFormatModelImpl] EP: NnapiExecutionProvider has Compile error: model_builder.cc:412 AddNewNNAPIOperand ResultCode: ANEURALNETWORKS_BAD_DATA
E/mainAct: session err
```

**Comment by yufenglee** [comment]
Add @gwang-msft for FYI. As the error info says, the scale of one QLinearAdd is 0.f, which is not allowed.
