### ISSUE TITLE
bad link to add-execution-provider doc page

### ISSUE THREAD

**Issue by trgardos** [microsoft/onnxruntime#9103]
**Describe the bug**
This link
https://onnxruntime.ai/docs/execution-provider/add-execution-provider.md
referenced from this page
https://onnxruntime.ai/docs/execution-providers/#add-an-execution-provider
does not exist.

**Comment by cassiebreviu** [comment]
PR submitted to fix issue. Thanks!

https://github.com/microsoft/onnxruntime/pull/9140
