### ISSUE TITLE
Tutorial of building onnxruntime to wasm and call it by c++

### ISSUE THREAD

**Issue by stereomatchingkiss** [microsoft/onnxruntime#9110]
Any plan to release document to show us how to build the onnxruntime to wasm and call the compiled libs by c++ api?Official doc lead me to this [post](https://cloudblogs.microsoft.com/opensource/2021/09/02/onnx-runtime-web-running-your-machine-learning-model-in-browser/). It would be better if we can compiled existing c++ codes into wasm rather then rewrite everything by js. Thanks

**Comment by fs-eire** [comment]
Thanks for the feedback. Consuming ORT in C++ for Web is an important scenario. We need to figure out how and update documents accordingly.

Some rough ideas:

- use dynamic linking: create `onnxruntime.so` for web and use Emscripten's [dynamic linking feature (experimental)](https://emscripten.org/docs/compiling/Building-Projects.html#dynamic-linking).

- use static linking: create `onnxruntime.a` for web. This file will be used in link phrase of a c++ web assembly project.

I haven't try either way yet, as my current focus is still on consuming from JavaScript side. But I will revisit this issue when I got some time.
