### ISSUE TITLE
[ORT JNI] OpenVINO EP cannot be added into session options

### ISSUE THREAD

**Issue by supercharleszhu** [microsoft/onnxruntime#9111]
**Describe the bug**
Hi team, our team is exploring the performance brought up by OpenVINO EP in ORT JNI solution. We have a local build pipeline that generates the ORT JNI library by the following shell: 
```bash
./build.sh --config Release --build_shared_lib --use_openvino CPU_FP32 --skip_submodule_sync --parallel --build_java --build_dir /workspace/build
```
When running with the following config
```java
try (OrtSession.SessionOptions opts = new OrtSession.SessionOptions()) {
          opts.setSessionLogLevel(OrtLoggingLevel.ORT_LOGGING_LEVEL_ERROR);
          opts.addOpenVINO("");
          OrtSession ortSession = _ortEnvironment.createSession(modelLocation.getPath(), opts);
          return ortSession;
        }
```
and run the ORT session for inference, it gives following error
```
/export/apps/jdk/JDK-11_0_8-msft/bin/java: symbol lookup error: /tmp/onnxruntime-java2533679640159920784/libonnxruntime4j_jni.so: undefined symbol: OrtSessionOptionsAppendExecutionProvider_OpenVINO
```

Seems that some Symbol is missing in the JNI C++ code. 

When removing the `opts.addOpenVINO("");` it works as expected.

Do you have any insights on this issue?

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS7
- ONNX Runtime installed from (source or binary): source 
- ONNX Runtime version: 1.8.0
- Python version: N/A
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): 7.3.1 
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
Same as the description above.

**Screenshots**
N/A

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by pranavsharma** [comment]
cc @jywu-msft @RyanUnderhill 0

**Comment by Craigacp** [comment]
OpenVINO doesn't work in Java in 1.8.0 because it's a shared library and Java only supports CUDA shared libraries in 1.8. Try building master.

**Comment by supercharleszhu** [comment]
Trying. Thanks for the quick response!

**Comment by supercharleszhu** [comment]
i rebuilt with master with the same config and get the following error when loading the jar file during gradle build:

```
ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: SessionOptionsAppendExecutionProvider_OpenVINO: Failed to load shared library
```

Do we need built shared object from the JNI building pipeline?

**Comment by Craigacp** [comment]
That should have worked. Did you clean the build environment first? Also check to see if the open vino execution provider is packaged into the jar. It should have been, but unlike the others that one isn't tested in the Java CI tests so I could have messed the Camera logic up.

**Comment by supercharleszhu** [comment]
I look into the built jar file and here is what I found: 
```
ls onnxruntime-1.9.0/ai/onnxruntime/native/linux-x64/     
libonnxruntime.so                    libonnxruntime_providers_openvino.so
libonnxruntime4j_jni.so              libonnxruntime_providers_shared.so
```
Is this expected?

**Comment by supercharleszhu** [comment]
seems that some dependencies are missing: 
```
ldd ai/onnxruntime/native/linux-x64/libonnxruntime_providers_openvino.so 
ldd: warning: you do not have execution permission for `ai/onnxruntime/native/linux-x64/libonnxruntime_providers_openvino.so'
        linux-vdso.so.1 =>  (0x00007ffda83dc000)
        libinference_engine.so => not found
        libinference_engine_c_api.so => not found
        libonnx_importer.so => not found
        libngraph.so => not found
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fd090c86000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fd090984000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd09076e000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fd0903a0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fd0911ff000)
```

We have not tried Python Openvino in the same environment yet.

**Comment by Craigacp** [comment]
Ok, I think that means you've not fully configured your OpenVINO environment, as it adds a bunch of libraries to your library path which is what ORT's OpenVINO executor is looking for. I think you need to make sure this script is executed in your terminal (https://docs.openvinotoolkit.org/latest/openvino_docs_install_guides_installing_openvino_linux.html#set-the-environment-variables), but I don't have access to an OpenVINO installation to test it with.

**Comment by supercharleszhu** [comment]
Got it. Since we build the JNI with openvino in another container, and the test machine doesn't have OpenVINO setups and shared libraries, that is the reason why it is not working. 

I have a noob question: Is it common practice not to put all the dependent shared object into the native folder in the jar file? Otherwise, we will have a fat executable where we don't need any of the dependencies.

**Comment by Craigacp** [comment]
We only put the ort binaries in the jar file. If we shipped the dependent libraries it will massively increase the jar file (e.g. CUDA is hundreds of megabytes), especially as the jars are cross platform so we'd need to put both Windows and Linux CUDA binaries.

**Comment by supercharleszhu** [comment]
Agreed. Will try to configure OpenVINO in the test host machine. Thanks very much!

**Comment by supercharleszhu** [comment]
I tried to set up the environment and install the openvino following the same step in docker image. Now I get 
```
ldd  libs-openvino/ai/onnxruntime/native/linux-x64/libonnxruntime_providers_openvino.so   
ldd: warning: you do not have execution permission for `libs-openvino/ai/onnxruntime/native/linux-x64/libonnxruntime_providers_openvino.so'
        linux-vdso.so.1 =>  (0x00007ffdfe3fc000)
        libinference_engine.so => /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/lib/intel64/libinference_engine.so (0x00007f854bc43000)
        libinference_engine_c_api.so => /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/lib/intel64/libinference_engine_c_api.so (0x00007f854b9f9000)
        libonnx_importer.so => /opt/intel/openvino_2021.2.200/deployment_tools/ngraph/lib/libonnx_importer.so (0x00007f854b3d9000)
        libngraph.so => /opt/intel/openvino_2021.2.200/deployment_tools/ngraph/lib/libngraph.so (0x00007f854abb0000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f854a8a8000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f854a5a6000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f854a390000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f8549fc2000)
        libtbb.so.2 => /opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib/libtbb.so.2 (0x00007f8549d5a000)
        libtbbmalloc.so.2 => /opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib/libtbbmalloc.so.2 (0x00007f8549aff000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f85498fb000)
        libinference_engine_transformations.so => /opt/intel/openvino_2021.2.200/deployment_tools/inference_engine/lib/intel64/libinference_engine_transformations.so (0x00007f85494ae000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8549292000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f854c1e2000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f854908a000)
```
Seems that all the libraries can be found.

However when I ran the JMH job with ORT JNI, it gave 
```
[E:onnxruntime:DEFAULT, provider_bridge_ort.cc:944 Get] Failed to load library libonnxruntime_providers_openvino.so with error: libtbb.so.2: cannot open shared object file: No such file or directory

```
libtbb.so.2 is located in `/opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib/libtbb.so.2`, and the $LD_LIBRARY_PATH also have `/opt/intel/openvino_2021/deployment_tools/inference_engine/external/tbb/lib`.  Do you have any idea on why this is happening?

**Comment by Craigacp** [comment]
Maybe we're now on it loading the fourth level dependencies (i.e. one of the OpenVINO libraries depends on tbb). I don't know why it can't find that, maybe someone from the ORT team who works on OpenVINO has a better idea? You could check `libinference_engine.so` etc with `ldd` to see if they have missing dependencies.

**Comment by jywu-msft** [comment]
adding some folks for assistance. +@MaajidKhan , @smkarlap

**Comment by MaajidKhan** [comment]
From OpenVINO-EP, we have never explored JAVA API options nor this has been validated.

I was trying today to re-produce the error. I am using Ubuntu 18.04 OS.

when I try build OpenVINO-EP or ONNXRuntime itself from master, the build fails with this error.

![ort_ov_ep_java_build_err](https://user-images.githubusercontent.com/29036417/134914558-649d8228-0234-4d46-8bca-8b050edaa378.JPG)

**command used:**
./build.sh --config Debug --use_openvino CPU_FP32 --build_wheel --build_shared_lib **--build_java** --parallel --skip_tests

I have installed gradle 6.8 version.

**JDK versions:**
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)

This error looks familiar and there was one similar onnxruntime thread with the same issue.

```
Plugin [id: 'com.diffplug.spotless', version: '5.9.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:5.9.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```

@Craigacp Any idea on this error? I have seen you respond to similar thread earlier.

**Comment by Craigacp** [comment]
That error is probably because gradle doesn't have the proxy configured. It's failing to find the spotless plugin which does code formatting. As it turns out you don't actually need that to build ORT, so can be commented out if you want to edit the build.gradle, but it does touch a bunch of lines.

**Comment by supercharleszhu** [comment]
Haven't ran into this issue before, I used this docker command to install Gradle in the image:

```
# Install Gradle and setup JAVA_HOME
RUN yum -y install zip
RUN curl -s "https://get.sdkman.io" | bash
RUN source "/root/.sdkman/bin/sdkman-init.sh" && sdk install gradle 7.2
ENV JAVA_HOME=/usr/java/jdk1.8.0_172-amd64
ENV GRADLE_HOME=/root/.sdkman/candidates/gradle/current
ENV PATH=$PATH:$GRADLE_HOME/bin
RUN gradle --version
```

**Comment by MaajidKhan** [comment]
Thanks @Craigacp  I commented out the spotless section, since I am on VPN and the build went through successfully for OpenVINO-EP.

@supercharleszhu  can you share me the ONNXRT Java sample and the steps to compile and test the application?

**Comment by supercharleszhu** [comment]
0. I used the below command to build the jar with OpenVINO EP:
```
./build.sh --config Release --build_shared_lib --use_openvino CPU_FP32 --skip_submodule_sync --parallel --build_java --build_dir /workspace/build
```
Have you built the jar successfully? If so, here are the steps to include the jar in gradle project and enable the OpenVINO EP from my side:
1. in build.gradle of project, include the jar file locally
```
dependencies {
...
  compile fileTree(include: ['*.jar'], dir: 'libs-openvino') //modify it to your library path
}
```
2. create ORT session with the following options:
```
try (OrtSession.SessionOptions opts = new OrtSession.SessionOptions()) {
//          opts.setExecutionMode(OrtSession.SessionOptions.ExecutionMode.PARALLEL);
          opts.addOpenVINO("");
          OrtSession ortSession = _ortEnvironment.createSession(modelLocation.getPath(), opts);
          return ortSession;
}
```
3. Running inference using 
```
OrtSession.Result result = ortSession.run(inputTensors, outputNames);
```

Unfortunately, I cannot share the exact model we are using to for testing. But can you follow the java example here to test it out? https://github.com/microsoft/onnxruntime/blob/master/java/src/test/java/sample/ScoreMNIST.java

**Comment by supercharleszhu** [comment]
Synced offline with Maajid, the OpenVINO EP works with default EP by splitting the model into subgraph and merge the results together. Currently we are meeting issue with the OpenVINO EP even with C++ APIs. (same issue here https://github.com/openvinotoolkit/openvino/issues/5205) . Therefore I will temporarily close this ticket and reopen it once we got a test model working with OpenVINO EP C++ APIs.
