### ISSUE TITLE
Possible duplicated source code

### ISSUE THREAD

**Issue by Z-Y00** [microsoft/onnxruntime#9116]
Hi, I found that for mlas lib, there are seperate amd64 and x86_64 source file.
They have pretty much the same function, what is the difference and purpose for these two folders?
If they are the same, why don't remove anyone of them?
For example, 
onnxruntime\core\mlas\lib\amd64\SconvKernelAvx512F.asm
and
onnxruntime\core\mlas\lib\x86_64\SconvKernelAvx512F.S

**Comment by yufenglee** [comment]
asm is for msvc assembly compiler and S is for gcc assembly compiler.
