### ISSUE TITLE
[js/web] "Only one thread was configured for parallel execution. Hence will use sequential execution."

### ISSUE THREAD

**Issue by benpm** [microsoft/onnxruntime#9117]
**Describe the bug**
When running a model with the wasm backend, I'm unable to get it to run in parallel. At first, I couldn't identify anything wrong, but eventually I realized that in order for the internal function `isMultiThreadSupported()` to return `true`, `SharedArrayBuffer` must be defined. So for now I'm just testing in Chrome with `--enable-features=SharedArrayBuffer`. Unfortunately, that didn't fix it, but I did get this warning message, which at least makes things a bit more clear:
> [W:onnxruntime:, utils.cc:589 ExecuteGraphImpl] Only one thread was configured for parallel execution. Hence will use sequential execution.

As far as I understand, I should be able to run in parallel. Here's my relevant setup:
```Javascript
const ort = require('onnxruntime-web');

async function runModel(imageArray) {
    if(imageArray) {
        try {
            const height = imageArray.shape[2];
            const width = imageArray.shape[3];
            ort.env.logLevel = "verbose";
            ort.env.debug = true;
            ort.env.wasm.numThreads = 16;
            ort.env.wasm.simd = true;
            const session = await ort.InferenceSession.create('./identity.onnx', {
                executionProviders: ["wasm"],
                logSeverityLevel: 0,
                logVerbosityLevel: 2,
                executionMode: "parallel"
            });

            const tensor = new ort.Tensor('uint8', imageArray.data, [1,3,height,width]);
            const feeds = { input: tensor };
            const results = await session.run(feeds);
            return results.output;
        } catch (e) {
            console.log("Broke");
            console.log(e)
            return undefined;
        }    
    } else {
        return undefined;
    }
}
```
This is the only place in my project where the ONNX Web Runtime is being used.

**Urgency**
N/A

**System information**
- OS Platform and Distribution: Ubuntu 20.10, Firefox 92
- ONNX Runtime installed: NPM Package
- ONNX Runtime version: onnxruntime-web 1.8.0, also tried 1.8.2-dev.20210831.0

**To Reproduce**
- Should be able to reproduce by using the provided function to run the model on a 4D Uint8 array, like from an image.
- [model.zip](https://github.com/microsoft/onnxruntime/files/7190910/model.zip) contains the identity.onnx I've used (I've also tried with several other models)

**Expected behavior**
The model should run in parallel.

**Screenshots**
Chrome console output:

![image](https://user-images.githubusercontent.com/10006314/133913730-39633a20-2d3e-4707-9e50-106b6cc575b2.png)

**Comment by fs-eire** [comment]
Thanks for the feedback.

The behavior is expected as we only set `numThreads` to intraop but always set interop to 1:
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/wasm/api.cc#L50-L51

This design decision is made by that we assume models for web scenario will not be a heavy model so that most of the time parallelization between kernels contributes to limited inferencing gain, especially when we use the limited CPU cores to perform intraop accelerations.

please note that parallelization inside a kernel (intra) still works no matter execution mode is "sequential" or "parallel" (inter).

**Comment by benpm** [comment]
So setting it to "parallel" execution mode has no effect?

**Comment by benpm** [comment]
Okay, so I understand now that the error message is expected. However, I'm not seeing any significant difference in run time between running the model with `numThreads: 1` and `numThreads: 16`.

`numThreads=16`: 6.294 sec
`numThreads=1`: 6.212 sec

Inspecting in htop, I can also see that there is only one core being heavily used:

![image](https://user-images.githubusercontent.com/10006314/134230840-114f3240-deb6-4c3f-bc79-379d8babe401.png)

**Comment by fs-eire** [comment]
did you check if the web worker threads are actually created? you can refer to the "Sources" tab in chrome's devtool. if there is only one thread, it means the browser environment is not capable to run multi-thread wasm (make sure `--enable-features=SharedArrayBuffer` is passed )

did you run warmups? the webworker threads are created asynchronously. if you call session.run() immediately after session created, the worker threads may not be ready yet.

did you try other numThreads configuration like, `numThreads=2` to compare with `numThreads=1`? sometimes too many threads may cause the overhead become significant to slow down the overall inference time

Also please try to disable verbose logging and debug mode.

**Comment by haydn-jones** [comment]
> did you check if the web worker threads are actually created? you can refer to the "Sources" tab in chrome's devtool. if there is only one thread, it means the browser environment is not capable to run multi-thread wasm (make sure `--enable-features=SharedArrayBuffer` is passed )
> 
> did you run warmups? the webworker threads are created asynchronously. if you call session.run() immediately after session created, the worker threads may not be ready yet.
> 
> did you try other numThreads configuration like, `numThreads=2` to compare with `numThreads=1`? sometimes too many threads may cause the overhead become significant to slow down the overall inference time
> 
> Also please try to disable verbose logging and debug mode.

Working on this with @benpm. Waiting for the threads to be ready may be a solution for us. We will do some testing and get back to you. Thanks!

**Comment by haydn-jones** [comment]
Waiting 1 second is consistently allowing the model to run in parallel, thanks for the tip!
