### ISSUE TITLE
[OpenVINO-EP] Windows Build broken for Debug Mode

### ISSUE THREAD

**Issue by MaajidKhan** [microsoft/onnxruntime#9122]
**Describe the bug**
For OpenVINO-EP, the windows build is broken for Debug Mode (Master branch).

**Urgency**
High

**System information**
- OS Platform and Distribution: Windows 10
- ONNX Runtime installed from (source or binary): Master
- ONNX Runtime version: 1.9
- Python version: Python 3.6.8
- Visual Studio version (if applicable): Visual Studio Community 2019 (16.11.2)
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
**Docx:** https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html
**Build steps:** https://onnxruntime.ai/docs/build/eps.html#openvino

**Expected behavior**
Build to be successfully completed. The issue is only seen in Debug mode. while the Release and RelWithDebInfo mode works fine.

**Screenshots**
![onnxrt_win_debug_build_failure_for_python_api](https://user-images.githubusercontent.com/29036417/133986286-f2504dff-9dcc-42ee-aa6d-60cec004c886.JPG)

The build fails when we try to build in debug mode and include python bindings (--build_wheel flag)

**command used to build:**
build.bat --config Debug --cmake_generator "Visual Studio 16 2019" --use_openvino CPU_FP32 --build_shared_lib --build_wheel --parallel --skip_tests

**Additional context**

![image](https://user-images.githubusercontent.com/29036417/133986906-13985bed-eed3-4255-82aa-ba6f437f2845.png)

with the above following change where we disable the /wx flag for debug mode, the build went through for debug mode (with --build_wheel flag) and we were able to infer the cpp sample (onnxruntime_perf_test).

but when we try to run any python sample, it gives this error.

<img width="722" alt="python_debug_mode_error" src="https://user-images.githubusercontent.com/29036417/133987133-fd8c9f8b-aba9-4751-971c-0b8fc6376a9b.PNG">

Though the onnxruntime_providers_openvino.dll is is available at the right location and all the system path/env path are set properly, it still throws this error saying - **"Load Library failed with error 126"**

**Comment by snnn** [comment]
To identify the problem:
1. Install [windbg](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools)
2.  Find the gflags.exe in the windbg install folder and start it, 

3. Select the image file tab
![image](https://user-images.githubusercontent.com/856316/74082914-91d96900-4a13-11ea-95eb-d73db8a5cf13.png)

4. Type python.exe then press the "tab" key, check "Show loader snaps" box

![image](https://user-images.githubusercontent.com/856316/74082958-b7667280-4a13-11ea-9eaf-6752695b4904.png)

5.  Start windbg, run python.exe with arguments of "test.py" (which is your test script)
![image](https://user-images.githubusercontent.com/856316/74083043-7d49a080-4a14-11ea-90fa-2960544a3dce.png)

6. in the command windows, type "g", then press the enter key
![image](https://user-images.githubusercontent.com/856316/74083078-d285b200-4a14-11ea-9df4-e86c421c5617.png)

7. You'll see a lot of outputs in the debugging windows.  Please search the lines that have "LdrpProcessWork - ERROR: Unable to load DLL", and put the result here.
e.g.
 "cublas64_100.dll", Parent Module: "C:\intelpython3\lib\site-packages\onnxruntime\capi\onnxruntime_pybind11_state.pyd", Status: 0xc0000135


Please post the log here if you can't find the problematic DLL by yourself.

**Comment by MaajidKhan** [comment]
@snnn I think we should revert these changes from the PR: https://github.com/microsoft/onnxruntime/pull/9130

This fix has introduced regression for python API in OpenVINO-EP.

The python API for OpenVINO-EP has this feature for dynamic device_type selection during runtime which allows the users to change the device_type during the run time.

since from the change in the PR mentioned above, the global variables config are being reset before calling the CreateProvider() method, which is clearing the device_id config set by the user to default build type.

Meaning, the python-API will always pick the device_type that was used during build time rather than changing the device_type during the run time.

Also this commit was made part of onnxrt v1.9.0 Release. I know onnxrt v1.9.0 is out few hours back, but is there any way you can revert this change and cherry pick the fix commit to v1.9.0?

**Comment by jywu-msft** [comment]
https://github.com/microsoft/onnxruntime/commit/45fa0daf4acb73ed5a6f343a0c1d3005b49bfd75 would fix it right?
let's fix it in master first and then later cherry pick into 1.9 branch?

**Comment by jywu-msft** [comment]
> @snnn I think we should revert these changes from the PR: #9130
> 
> This fix has introduced regression for python API in OpenVINO-EP.
> 
> The python API for OpenVINO-EP has this feature for dynamic device_type selection during runtime which allows the users to change the device_type during the run time.
> 
> since from the change in the PR mentioned above, the global variables config are being reset before calling the CreateProvider() method, which is clearing the device_id config set by the user to default build type.
> 
> Meaning, the python-API will always pick the device_type that was used during build time rather than changing the device_type during the run time.
> 
> Also this commit was made part of onnxrt v1.9.0 Release. I know onnxrt v1.9.0 is out few hours back, but is there any way you can revert this change and cherry pick the fix commit to v1.9.0?

separately, can you add some unit tests to beef up the test code coverage of this area ?

**Comment by MaajidKhan** [comment]
> [45fa0da](https://github.com/microsoft/onnxruntime/commit/45fa0daf4acb73ed5a6f343a0c1d3005b49bfd75) would fix it right?
> let's fix it in master first and then later cherry pick into 1.9 branch?

Yes George, this would fix the issue. Just verified from my end.

**Comment by jywu-msft** [comment]
> > [45fa0da](https://github.com/microsoft/onnxruntime/commit/45fa0daf4acb73ed5a6f343a0c1d3005b49bfd75) would fix it right?
> > let's fix it in master first and then later cherry pick into 1.9 branch?
> 
> Yes George, this would fix the issue. Just verified from my end.

I created a PR for master https://github.com/microsoft/onnxruntime/pull/9166
Re: release-1.9.0 branch, that's still TBD, we may not be able to update that branch at this point. will discuss with others.

**Comment by jywu-msft** [comment]
> > > [45fa0da](https://github.com/microsoft/onnxruntime/commit/45fa0daf4acb73ed5a6f343a0c1d3005b49bfd75) would fix it right?
> > > let's fix it in master first and then later cherry pick into 1.9 branch?
> > 
> > 
> > Yes George, this would fix the issue. Just verified from my end.
> 
> I created a PR for master #9166 Re: release-1.9.0 branch, that's still TBD, we may not be able to update that branch at this point. will discuss with others.

the fix will be included in https://github.com/microsoft/onnxruntime/tree/rel-1.9.1 which contains fixes for issues found with the 1.9 release.
