### ISSUE TITLE
Question for Populating String Tensors in ONNX Runtime - C++

### ISSUE THREAD

**Issue by adjhawar** [microsoft/onnxruntime#9123]
I have a byte buffer containing variable length null-terminated strings. These strings are to be input as tensor to an ONNX model. So how do I populate the tensor efficiently?
E.g: 
String str = {"abc","de","fghi","","","jklmn"}
Byte buffer contents = abc\0de\0fghi\0\0\0jklmn\0
Tensor shape = [6]
Tensor = [ abc , de , fghi, , , jklmn ]

The example given in https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/shared_lib/test_nontensor_types.cc uses same length tensors.

Could anyone please point me in the right direction?

**Comment by yufenglee** [comment]
The example also works for variable length null-terminated strings. Please also take a look at the [FillStringTensor](https://github.com/microsoft/onnxruntime/blob/6ae5f7a24478bf34b402db3a176020024b5d0567/include/onnxruntime/core/session/onnxruntime_c_api.h#L1098). 
Could you please say more about populating efficiently? ORT string tensor is essentially an array of pointer of std::string inside.

**Comment by yufenglee** [comment]
Close the issue. Please reopen it if it doesn't resolve your question.
