### ISSUE TITLE
1.8.2 onnx-tensorrt ‘kRNN’ is not a member of ‘nvinfer1::LayerType’ with TensorRT8

### ISSUE THREAD

**Issue by smijolovic** [microsoft/onnxruntime#9125]
When using --use_tensorrt to build ONNX runtime against TensorRT8, the following error occurs due to the removal of kRNN and the replacement with kRNN_v2: 

[ 57%] Building CXX object external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/onnx2trt_utils.cpp.o
onnxruntime/cmake/external/onnx-tensorrt/onnx2trt_utils.cpp: In function ‘bool onnx2trt::supportsShapeTensor(nvinfer1::LayerType, nvinfer1::ElementWiseOperation, nvinfer1::ReduceOperation)’:
onnxruntime/cmake/external/onnx-tensorrt/onnx2trt_utils.cpp:1594:35: error: ‘kRNN’ is not a member of ‘nvinfer1::LayerType’
 1594 |         case nvinfer1::LayerType::kRNN:
make[2]: *** [external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/build.make:118: external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/onnx2trt_utils.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2934: external/onnx-tensorrt/CMakeFiles/nvonnxparser_static.dir/all] Error 2

Based on this, there was a separate tree for onnx-tensorrt for TensorRT8 when it was EA, but it is GA now:
https://githubmemory.com/repo/onnx/onnx-tensorrt/issues/685

What is the procedure to pull the proper submodule for onnx-tensorrt using TensorRT8 to perform the build using build.sh on the release build of ONNXruntime?

**Comment by jywu-msft** [comment]
which ORT branch are you building?

**Comment by smijolovic** [comment]
When will the 1.9 release branch be pushed?

The information on the 8 EA tree for onnx-tensort did not articulate how to pull that submodule to build against the 1.8.2 branch, so the workaround is unclear. Would like to test that, so any information on the process to update that specific module would be helpful to move forward.

**Comment by stevenlix** [comment]
ORT1.9 will be released very soon. We recommend to use ORT master or 1.9 release for TRT8 GA. But if you really want to use previous ONNX-Tensorrt version, you can refer to this link to manually update the submodule. https://onnxruntime.ai/docs/build/eps.html#prerequisites-1

**Comment by smijolovic** [comment]
That worked.

For reference:

git clone --branch v1.8.2 https://github.com/microsoft/onnxruntime.git
cd onnxruntime
git submodule update --init
cd cmake/external/onnx-tensorrt
git remote update
git checkout release/8.0

Build was successful.
