### ISSUE TITLE
model load from memory

### ISSUE THREAD

**Issue by ChenCVer** [microsoft/onnxruntime#9146]
**Is your feature request related to a problem? Please describe.**

**System information**
- ONNX Runtime version (you are using):

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ChenCVer** [comment]
Does onnxruntime support loading models from memory?

**Comment by yufenglee** [comment]
Yes, here is the C API. There are corresponding APIs for other languages:
https://github.com/microsoft/onnxruntime/blob/1db21da5aeb93a4b08a92a40566a0c630dc2641b/include/onnxruntime/core/session/onnxruntime_c_api.h#L592

**Comment by ChenCVer** [comment]
> Yes, here is the C API. There are corresponding APIs for other languages:
> https://github.com/microsoft/onnxruntime/blob/1db21da5aeb93a4b08a92a40566a0c630dc2641b/include/onnxruntime/core/session/onnxruntime_c_api.h#L592

**Comment by ChenCVer** [comment]
corresponding C++ API is follow:  
Session(Env& env, const void* model_data, size_t model_data_length, const SessionOptions& options); 
ok?
