### ISSUE TITLE
How to optimize 32 bit memory/cpu usage in c++

### ISSUE THREAD

**Issue by MaialenUrbieta** [microsoft/onnxruntime#9152]
**Describe the performance question**
Part of the memory usage is from the model, but there is an additional ~160 MB usage we'd like to reduce as much as possible. Is there any way to lower this memory either changing some compilation or configuration option(s) in OnnxRuntime? 

Also, having several evaluating threads seems to consume as follows: 160 MB one thread, 310 MB with two threads and up to 610MB with 4 threads. We have several evaluating threads that share the session in this configuration but it seems that each additional thread requires a constant amount of memory that adds up to the total process. Is there a way to reduce this amount per thread? In this setup, evaluating threads run the session continuously (one after another) and we can notice that the more threads we have, the evaluation time takes also longer. The profiling output shows that costly operations take more kernel time than the same operations with fewer threads, is there a way to improve this, apart from using intrathreads (that seem to help more than inter threads)? 

I tried to use the ort model instead of the onnx model too, first exporting the model and with the following code:

```
Ort::SessionOptions session_options;
...

session_options.AddConfigEntry("session.load_model_format", "ORT");
```
But no significant change was found in memory/cpu usage. 

**Urgency**
Decision to include onnxruntime will be taken next week depending on memory/cpu usage.

**System information**
- OS Platform: Windows PC
- ONNX Runtime installed from (source or binary): Binary, downloaded from https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/
- ONNX Runtime version: 1.8.1
- CPU mode, c++ program compiled in 32bit 

**Labels**
type: performance, type:support

**Comment by yufenglee** [comment]
Did you try disabling enable_mem_pattern and enable_cpu_mem_arena?

**Comment by MaialenUrbieta** [comment]
Thanks Yufeng, those two options have helped. Now the memory usage is not that constant; cpu usage increases a bit but not a significant amount. Regarding memory usage, there are still some peaks that remind us of the same order of memory usage as before:  160 MB for one thread, 310 MB with two threads and up to 610MB with 4 threads. Are there any other configuration or even compilation options we might study? If that makes sense, we could even reduce functionality offered by Onnxruntime to adapt to our needs, but I recognize that this must be complicated. Any guidance is welcome.

**Comment by yufenglee** [comment]
@MaialenUrbieta, did you create an InferenceSession in each thread? Or the memory won't increase so much with multiple threading.

**Comment by MaialenUrbieta** [comment]
Threads share a common session, but if multiple threads call the Run method on the same inference session, maybe at times they overlap using more memory, up to the maximun of 610MB?. Would that make sense? In this 4 thread execution, the memory usage has been as follows (max. 592MB):

![Memory](https://user-images.githubusercontent.com/16615861/134917283-5bd3d166-1bb2-4571-98ea-5acf7cc93f8a.png)

Note that threads calling Run is quite intense.
