### ISSUE TITLE
centos6.9+onnxruntimme1.4 build error

### ISSUE THREAD

**Issue by zhb0920** [microsoft/onnxruntime#9153]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- centos6.9:
- ONNX Runtime installed from :source 
- ONNX Runtime version:1.4.0
- Python version:3.7
- GCC/Compiler version (if compiling from source):5.4

[ 58%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/zhb/Downloads/onnxruntime-1.4.0/onnxruntime/core/mlas/lib/x86_64/QgemmU8S8KernelAvx2.S.o
cc1: error: unrecognized command line option "-mavx2"
gmake[2]: *** [CMakeFiles/onnxruntime_mlas.dir/home/zhb/Downloads/onnxruntime-1.4.0/onnxruntime/core/mlas/lib/x86_64/QgemmU8S8KernelAvx2.S.o] Error 1
gmake[1]: *** [CMakeFiles/onnxruntime_mlas.dir/all] Error 2
gmake: *** [all] Error 2
Traceback (most recent call last):
  File "/home/zhb/Downloads/onnxruntime-1.4.0/tools/ci_build/build.py", line 1925, in <module>
    sys.exit(main())
  File "/home/zhb/Downloads/onnxruntime-1.4.0/tools/ci_build/build.py", line 1814, in main
    build_targets(args, cmake_path, build_dir, configs, args.parallel)
  File "/home/zhb/Downloads/onnxruntime-1.4.0/tools/ci_build/build.py", line 928, in build_targets
    run_subprocess(cmd_args, env=env)
  File "/home/zhb/Downloads/onnxruntime-1.4.0/tools/ci_build/build.py", line 422, in run_subprocess
    env=my_env, shell=shell)
  File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/zhb/code/cmake-3.18.0-Linux-x86_64/bin/cmake', '--build', '/home/zhb/Downloads/onnxruntime-1.4.0/build/Linux/RelWithDebInfo', '--config', 'RelWithDebInfo', '--', '-j1']' returned non-zero exit status 2.

**Comment by yufenglee** [comment]
@zhb0920, mavx2 is supported from gcc4.7. Could you please double confirm your gcc version?

**Comment by zhb0920** [comment]
> @zhb0920, mavx2 is supported from gcc4.7. Could you please double confirm your gcc version?

onnxruntime-linux-x64-1.4.0 里面的so只有10Mb,我编译出来的有330Mb，是什么原因？

**Comment by zhb0920** [comment]
solved after update devtoolset

**Comment by snnn** [comment]
You can strip it:
https://man7.org/linux/man-pages/man1/strip.1.html
