### ISSUE TITLE
Dynamic input/output batch size

### ISSUE THREAD

**Issue by paulgheorghecristian** [microsoft/onnxruntime#9156]
Hello,
Where can I find an example that runs an onnx with dynamic batch size for input?
Thank you!

**Comment by yufenglee** [comment]
This notebook is helpful:
https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/notebooks/PyTorch_Bert-Squad_OnnxRuntime_GPU.ipynb
