### ISSUE TITLE
Missing header in 1.9.0 win x64 GPU release

### ISSUE THREAD

**Issue by Deams51** [microsoft/onnxruntime#9165]
**Describe the bug**
The latest release fails to compile the C++ inference samples.
The header file `cuda_provider_factor.h` is reported as missing.
Adding it manually then triggers a missing include `core/framework/provider_options.h` in `cuda_provider_factor.h`
Replacing it with `provider_options.h` finally allow it to compile.

**Urgency**
None

**System information**
- Win10
- binary
- 1.9.0

**To Reproduce**
- Download 1.9.0 binaries
- Clone inference example repo: https://github.com/microsoft/onnxruntime-inference-examples
- Attempt to compile with GPU support enabled

**Expected behavior**
Examples compiling

**Additional context**
Related to https://github.com/microsoft/onnxruntime/issues/9148

**Comment by snnn** [comment]
It is expected. Please use the new  API. See: https://github.com/microsoft/onnxruntime/issues/9136#issuecomment-923784442
