### ISSUE TITLE
MKL linker error when building eager mode with torch 

### ISSUE THREAD

**Issue by ashari4** [microsoft/onnxruntime#9170]
**Describe the bug**

Building `onnxruntime` with eager mode enabled results in MKL libraries not found by the linker.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: commit hash 0888c6cc5926ac5debf85b105264933784591b82
- Python version: 3.9.5
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source): Clang 12
- CUDA/cuDNN version: None
- GPU model and memory:
- torch commit: `c78ab28441f5`

**To Reproduce**

```
./build.sh --cmake_generator=Ninja --enable_training --enable_pybind --build_eager_mode
```

**Expected behavior**
I expect a successful, but instead I observe:

```
[1335/1343] Linking CXX shared module onnxruntime_pybind11_state.so
FAILED: onnxruntime_pybind11_state.so

... 

/usr/bin/ld: cannot find -lmkl_intel_ilp64
/usr/bin/ld: cannot find -lmkl_core
/usr/bin/ld: cannot find -lmkl_intel_thread
```

**Additional context**
I am noticing that `-lmkl_intel_ilp64  -lmkl_core  -lmkl_intel_thread  -pthread  -lrt  -lpthread` are getting added as part of the `LINK_LIBRARIES` property of the `onnxruntime_pybind11_state` target, but I don't understand why this is. I am not explicitly specifying that the MKL libraries should be linked against.

In a python interpreter
```
>>> import torch
>>> torch.__config__.parallel_info()
```

results in 

```
'ATen/Parallel:\n\tat::get_num_threads() : 2\n\tat::get_num_interop_threads() : 2\nOpenMP 201811\n\tomp_get_max_threads() : 2\nIntel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications\n\tmkl_get_max_threads() : 2\nMKLDNN not found\nstd::thread::hardware_concurrency() : 4\nEnvironment variables:\n\tOMP_NUM_THREADS : [not set]\n\tMKL_NUM_THREADS : [not set]\nATen parallel backend: OpenMP\n'
```

**Comment by souptc** [comment]
it seems related with torch's cmake config. manually link with torch libs instead of link with torch cmake target will solve the issue. working on a PR now.

**Comment by baijumeswani** [comment]
closing this issue since it is quite old.
