### ISSUE TITLE
[WinML] Return wgi::BitmapBounds to caller of bind

### ISSUE THREAD

**Issue by aungthetnaing** [microsoft/onnxruntime#9171]
**Is your feature request related to a problem? Please describe.**
When VideoFrame is "bind" to model input, it might be cropped and scaled per while maintaining aspect ratio. reference: https://github.com/microsoft/onnxruntime/blob/4e5bc8365b882563088542f877d4a83f4c08a958/winml/lib/Api/ImageFeatureValue.cpp#L126.  For use case such as Object detection, the BitmapBounds info is important to map the output tensor values to detected boxes in image under evaluation. So, the collection of the BitmapBounds need to exposed to the called of the bind.

**System information**
- ONNX Runtime version (you are using): Microsoft.AI.MachineLearning 1.8.1

**Describe the solution you'd like**
API need to be extended to return the BitmapBounds to the caller.

**Describe alternatives you've considered**

**Additional context**

**Comment by nums11** [comment]
Thanks for posting, we'll look into this.
