### ISSUE TITLE
[WinML] Extend VideoFrame binding to have more option regarding scaling

### ISSUE THREAD

**Issue by aungthetnaing** [microsoft/onnxruntime#9172]
**Is your feature request related to a problem? Please describe.**
Current VideoFrame binding process crop the image at middle to keep aspect ratio. https://github.com/microsoft/onnxruntime/blob/4e5bc8365b882563088542f877d4a83f4c08a958/winml/lib/Api/ImageFeatureValue.cpp#L126. That reduced Field of view under evaluation. It might matter for some use cases. 

**System information**
- 1.8.1

**Describe the solution you'd like**
Provide option to ignore aspect ratio during scaling. In some use cases and models, training models already account for distortion caused by aspect ratio mismatch  between original image and tensor size.

**Describe alternatives you've considered**

**Additional context**

**Comment by nums11** [comment]
Closing but tracking internally.
