### ISSUE TITLE
set_providers with list

### ISSUE THREAD

**Issue by helion-du-mas-des-bourboux-thales** [microsoft/onnxruntime#9198]
`sess.set_providers('CPUExecutionProvider')`
should be replaced by 
`sess.set_providers(['CPUExecutionProvider'])`

---
#### Document Details
* Title: Execution Providers
* Page: [https://natke.github.io/onnxruntime/docs/reference/execution-providers/](https://natke.github.io/onnxruntime/docs/reference/execution-providers/)
* Page Source: index.md

**Comment by stevenlix** [comment]
Thanks for pointing it out. It has been fixed in the PR https://github.com/microsoft/onnxruntime/pull/9201
