### ISSUE TITLE
Error due to a combination of a condition, convolution and batchnorm layers

### ISSUE THREAD

**Issue by ig177** [microsoft/onnxruntime#9204]
**Describe the bug**
Please see this very simple model and code:
```
import numpy as np
import onnxruntime as ort
import torch.onnx
import torch.nn as nn

class MyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.conv = nn.Conv1d(in_channels=512, out_channels=512, kernel_size=3, stride=1, padding=2, dilation=1)
        self.bn = nn.BatchNorm1d(512)

    def forward(self, x: torch.Tensor):

        results_available = True

        if x.sum() > -1:
            results_available = False

        if results_available:
            x = self.conv(x)
            x = self.bn(x)

        return x


instance = MyModel()
instance.eval()

scripted_cell = torch.jit.script(instance)

x = torch.zeros((10, 512, 20))
torch_result = instance(x)
scripted_result = scripted_cell(x)

np.testing.assert_almost_equal(torch_result.detach().numpy(), scripted_result.detach().numpy(), 4)

torch.onnx.export(
    model=scripted_cell,
    args=(x,),
    f='net.onnx',
    verbose=True,
    input_names=['x'],
    output_names=['result'],
    example_outputs=torch_result,
    opset_version=13,
    dynamic_axes={
        'x': {0: 'batch_size', 2: 'timesteps'},
    },
)

ort_session = ort.InferenceSession("net.onnx")
outputs = ort_session.run(
    None,
    {
        'x': x.detach().numpy().astype(np.float32),
    }
)
```
It causes the following error:
```
Traceback (most recent call last):
  File "C:\PythonEnvs\onnx4\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-26a8cf333fb8>", line 52, in <module>
    ort_session = ort.InferenceSession("net.onnx")
  File "C:\PythonEnvs\onnx4\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 324, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\PythonEnvs\onnx4\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 358, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from net.onnx failed:Node (If_10) Op (If) [TypeInferenceError] Graph attribute inferencing failed: Size mismatch validating subgraph inputs. Got 0 inputs but subgraph has 1 inputs and requires 1 inputs. Either provide all subgraph inputs, or just the required inputs.
```

Note the I redacted my (obviously more complex) model to contain the bare minimum to reproduce this bug. Moreover, **note that removing any of the following components of the model above will eliminate the bug:**
1. The convolution operator.
2. Batch normalization.
3. Any of the if statements.

**Urgency**
Extremely urgent. We're already behind schedule because of our extensive attempts to hunt this bug down. An immediate workaround or a fix would be very appreciated.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, latest updates
- ONNX Runtime installed from (source or binary): pip install onnxruntime
- ONNX Runtime version: 1.9.0
- Python version: 3.6.4
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A (running on CPU)
- GPU model and memory: N/A (running on CPU)

**To Reproduce**
See above steps to reproduce. The model is attached.

**Expected behavior**
No errors. Smooth execution of the model.

**Screenshots**
N/A

**Additional context**
N/A

[net.zip](https://github.com/microsoft/onnxruntime/files/7240029/net.zip)

**Comment by garymm** [comment]
Tracked internally at Microsoft by https://msdata.visualstudio.com/Vienna/_workitems/edit/1432282

**Comment by BowenBao** [comment]
should be resolved by https://github.com/pytorch/pytorch/pull/66152
