### ISSUE TITLE
Does inference in Javascript support XGBoost models?

### ISSUE THREAD

**Issue by jessicayung** [microsoft/onnxruntime#9209]
**Describe the bug**

When I try to load in an XGBoost model using code adapted from https://github.com/microsoft/onnxruntime-inference-examples/blob/main/js/quick-start_onnxruntime-web-script-tag/index.html, I get the following error: ```ReferenceError: Buffer is not defined.```

**Main question: is this likely because XGBoost models are not supported for inference in JS, or is it because there is some other problem?**

Here is the code I used. I run the code within [Electron](https://github.com/electron/electron-quick-start). The error occurs in the second line (`const session = await ort.InferenceSession.create('./rf_iris.onnx');`) since `Loaded model` is not printed.  If I replace the model with another one, e.g. `model.onnx` in the [JS example](https://github.com/microsoft/onnxruntime-inference-examples/tree/main/js/quick-start_onnxruntime-web-script-tag), this code runs fine (with small adjustments to the model input and output names).

```
// "https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.min.js" is loaded in index.html before calling this script
async function main() {

 // create a new session and load the specific model.
 console.log('Try to load model')
 const session = await ort.InferenceSession.create('./rf_iris.onnx');
 console.log('Loaded model')
 // prepare inputs. a tensor need its corresponding TypedArray as data
 const dataA = Float32Array.from([1, 20, 466, 0]);
 const tensorA = new ort.Tensor('float32', dataA, [1, 4]);

 // prepare feeds. use model input names as keys.
 const feeds = { float_input: tensorA};

 // feed inputs and run
 const results = await session.run(feeds);

 // read from results
 console.log('Got results')
 const dataC = results.probabilities.data;
 console.log(`data of result tensor 'probabilities': ${dataC}`);
}

main();
```

I have included details about the XGBoost model in the Additional context section. You can also [find it here](https://github.com/jessicayung/artifacts-for-github-issues/blob/main/rf_iris.onnx).

**Urgency**
Ideally by 4 Oct for a project.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04.2 LTS (Windows Subsystem for Linux 2)
- ONNX Runtime installed from (source or binary): binary (pip install in conda env)
- ONNX Runtime version: 1.9.0
- Python version: 3.6.13
- Visual Studio version (if applicable): (not relevant, but 1.60.2)
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**To Reproduce**
- Run the code above within an index.html (e.g. as is done [here](https://github.com/microsoft/onnxruntime-inference-examples/blob/main/js/quick-start_onnxruntime-web-script-tag/index.html)) with [the ONNX model here](https://github.com/jessicayung/artifacts-for-github-issues/blob/main/rf_iris.onnx). 

**Additional context**
The XGBoost model was trained and saved using this code, which was taken from another issue:

```
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import onnxmltools
from xgboost import XGBClassifier
from skl2onnx.common.data_types import FloatTensorType

# Train a XGBoost model.
iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y)
clr = XGBClassifier()
clr.fit(X_train, y_train)

# Convert into ONNX format
initial_type = [('float_input', FloatTensorType([None, 4]))]
onx = onnxmltools.convert.convert_xgboost(clr, initial_types=initial_type)
with open("rf_iris.onnx", "wb") as f:
 f.write(onx.SerializeToString())
```
I have checked that it runs fine in Python using this code:
```
# ONNX Runtime
import onnxruntime as rt
import numpy as np
sess = rt.InferenceSession("rf_iris.onnx")
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[1].name

# Sample Test Input

predict_list = [1., 20., 466., 0.]
predict_array = np.array(predict_list).reshape((1,-1))

# Prediction from ONNX Runtime
pred_onx = sess.run([label_name], {input_name: predict_array.astype(np.float32)})[0]
print("Prediction of ONNX Runtime", pred_onx)
```

Thank you!

**Comment by josephrocca** [comment]
@fs-eire I'm also getting a `Buffer is not defined` error - not sure if it's related: https://github.com/microsoft/onnxruntime/issues/9757

**Comment by fs-eire** [comment]
this issue was fixed in https://github.com/microsoft/onnxruntime/pull/9839
