### ISSUE TITLE
Failed do Kind Kernel def Hash

### ISSUE THREAD

**Issue by filipeferreiradsr** [microsoft/onnxruntime#9245]
**Describe the bug**
I get this message when running the ORT model:
`AssignNodesToEpsFromHashesImpl Failed to find kernel def hash (4500561021631132744) in kernel registries for GatherElements(13) node with name 'GatherElements_354'`

I tried with diferent OPset versions, but all with the same result.

**Comment by gwang-msft** [comment]
Please create a well defined issue using the Bug/Performance issue template.
