### ISSUE TITLE
An error occurs while running with CUDAExecutionProvider on version 1.9.0

### ISSUE THREAD

**Issue by sipan17** [microsoft/onnxruntime#9247]
**Describe the bug**
An error is thrown while trying to do the inference on GPU, while the model works flawlessly on CPU

**Urgency**
I'd like to deploy my model with onnx on GPU, but this issue is blocking me. Help needed ASAP.

**System information**
- Linux Ubuntu 20.04
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 1.9.0
- Python version: 3.8
- CUDA/cuDNN version: 11
- GPU model and memory: RTX 3070, Tesla V100-SXM2-16GB

**To Reproduce**
onnx model: https://drive.google.com/file/d/1fTQWgXA9aRcLjgW9zzUHnQjOTuvbm3iA/view?usp=sharing
```
import numpy as np
import onnxruntime as rt

model_path = 'models/google_rand.onnx'

providers = ['CPUExecutionProvider', 'CUDAExecutionProvider']

inp1 = np.array([[26, 117, 49, 119, 15, 21, 37, 29, 57, 22, 1, 13, 117, 72, 22, 15, 36, 1, 24, 117, 59, 21, 29, 30, 7,
                  15, 106, 118, 59, 24, 58, 86, 117, 16, 72, 94, 57, 24, 1, 117, 52, 119, 15, 72, 118, 25, 98, 1, 21,
                  117, 49, 119, 24, 30, 59, 24, 30, 1, 117, 59, 15, 72, 90, 72, 42, 1, 37, 24, 15, 1, 15, 72, 29, 21,
                  117, 100, 32, 58, 86, 19, 1, 30, 117, 31, 119, 22, 1, 17, 52, 119, 86, 1, 29, 30, 117, 25, 119, 86,
                  19, 30, 118, 59, 22, 58, 36, 1, 58, 86, 117, 12, 98, 24, 15, 1, 39, 57, 1, 64, 22, 117, 25, 98, 13,
                  8, 33, 19, 119, 1, 49, 119, 86, 1, 15, 72, 32, 117, 59, 22, 57, 26, 72, 42, 1, 118, 16, 72, 117, 12,
                  72, 1, 30, 59, 21, 24, 117, 49, 119, 22, 57, 15, 106, 19, 36, 1, 37, 24, 15, 1, 26, 86, 117, 49, 119,
                  15, 100, 21, 30, 29, 1, 30, 57, 1, 30, 117, 16, 72, 21, 1, 21, 117, 59, 86, 1, 100, 32, 1, 117, 52,
                  119, 22, 1, 39, 57, 1, 26, 86, 57, 15, 117, 100, 21, 94, 57, 24, 1, 26, 86, 117, 49, 119, 29, 59, 29,
                  125, 36, 1, 29, 118, 25, 98, 1, 39, 37, 30, 1, 20, 31, 119, 1, 21, 37, 24, 1, 17, 117, 25, 98, 21,
                  57, 29, 1, 117, 25, 98, 24, 22, 19, 1, 118, 52, 24, 1, 20, 98, 86, 1, 29, 30, 117, 25, 119, 86, 19,
                  1, 21, 117, 49, 119, 24, 30, 59, 24, 30, 8]], dtype=np.int32)
# inp1 = inp1[:, :176] # RTX 3070
# inp1 = inp1[:, :278] # Tesla V100-SXM2-16GB
inp2 = np.full_like(inp1, 1, dtype=np.int32)

results = []
for provider in providers:
    session = rt.InferenceSession(model_path, providers=[provider])
    res = session.run(['mel'], {'phonemes': inp1, 'speakers': inp2})[0]
    print(provider, res.shape)
    results.append(res)
print(np.allclose(results[0], results[1]), np.abs(results[0] - results[1]).max())
```
```
Error: onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : 

Non-zero status code returned while running Compress node. Name:'Compress__751' Status Message: 

/onnxruntime_src/onnxruntime/core/framework/op_kernel.cc:78 OrtValue* 

onnxruntime::OpKernelContext::OutputMLValue(int, const onnxruntime::TensorShape&) status.IsOK() was false. 

Tensor shape cannot contain any negative value
```

Interestingly enough, if you uncomment this ( inp1 = inp1[:, :176] for RTX 3070 GPU or inp1 = inp1[:, :278] for Tesla V100-SXM2-16GB GPU ) the model doesn't throw any error.

**Expected behavior**
An ideal behavior would be to have the output of allclose as True, but when running with uncommented line the max abs difference is close to 1e-2. At least, the model should be able to the inference with CUDA provider
I accidentally found out that the issue is not present in version 1.8.1

**Comment by yuslepukhin** [comment]
The issue here is that the second input for Compress is expected to be of boolean type. However, the  model feeds output from [Div](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Div) which is anything but boolean. So the model is not good and we need to make sure it is detected.
However, we could also make our CUDA and CPU implementation more consistent. CPU code implicitly counts non-zeros in the condition to arrive at the total number of output items. CUDA code sums up what it thinks to be ones, but they are not. The result is a negative number because what is being fed is actually int8_t.

**Comment by yuslepukhin** [comment]
Thank you for submitting a good bug report!
