### ISSUE TITLE
TypeError: cannot resolve operator 'ConvTranspose' with opsets: ai.onnx v11

### ISSUE THREAD

**Issue by Ailanz** [microsoft/onnxruntime#9257]
**Describe the bug**
I ported a pytorch model over to ONNX. Im able to load the model it in python but when trying to load it via onnxruntime-web (React) v1.9.0 I get the error:

>  TypeError: cannot resolve operator 'ConvTranspose' with opsets: ai.onnx v11

loading as: 

> import * as ort from 'onnxruntime-web';
> import model_path from './latest_net_G.onnx'
> const session = await ort.InferenceSession.create(model_path);

Please assist. Thanks!

**Comment by jcwchen** [comment]
Hi @Ailanz,
According to the [Operators Support Table](https://github.com/microsoft/onnxruntime/blob/master/js/web/docs/operators.md) for ONNXRuntime Web, I think ConvTranspose has not been supported yet. I will tag it as an enhancement. Thanks!

**Comment by fs-eire** [comment]
ConvTranspose is not supported by WebGL backend for now. Please use WebAssembly backend:

```
// const session = await ort.InferenceSession.create(model_path);
const session = await ort.InferenceSession.create(model_path, { executionProviders: ['wasm']});
```

**Comment by ar-nowaczynski** [comment]
I did a [side-project](https://github.com/ar-nowaczynski/uttt) in which I used onnxruntime and I came across the same problem as described above. My neural network uses ConvTranspose2D layer, which is not supported by WebGL backend right now. I switched to WebAssembly backend and it works nicely.

Nonetheless, I'd like to upvote the idea of adding ConvTranspose2D to the list of supported WebGL operators.

**Comment by 101arrowz** [comment]
I would like to help contribute this operator. I think I should be able to write a naive implementation but I don't know if there's any particular technique I should employ to accelerate it (like `im2col` for standard conv). @fs-eire any suggestions?

**Comment by fs-eire** [comment]
@101arrowz first of all welcome to contribute !

I am not familiar with this particular operator, so I cannot suggest any advanced acceleration/optimization on ConvTranspose. I think you can start with the naive implementation, and for the optimization we can determine by measure the performance data

**Comment by 101arrowz** [comment]
Hi again @fs-eire! I've gotten a prototype of ConvTranspose to somewhat work locally, but I'm encountering a weird issue in my shader. For some reason the WebGL result seems to be out-of-order: the data should be like this:

```
0 1 2
3 4 5
6 7 8
```

WebGL returns the correct values, but like this:

```
0 3 6
1 4 7
2 5 8
```
This might be a mistake I made while porting the Python pseudocode I initially wrote to GLSL, but I can't see it. Is there any configuration that could cause this within the runtime?

**Comment by Yosshi999** [comment]
If your parameters of ConvTranspose is simple, you can use my workaround.

```python
def pseudo_conv_transpose2d(input, weight, bias=None, stride=1, padding=0, output_padding=0, groups=1, dilation=1):
  kernel_size = weight.shape[-2:]
  if isinstance(stride, int):
    stride = (stride, stride)
  if isinstance(padding, int):
    padding = (padding, padding)
  assert output_padding == 0 or output_padding == (0, 0)
  assert groups == 1
  assert dilation == 1 or dilation == (1, 1)
  assert stride[0] <= kernel_size[0] - padding[0]
  assert stride[1] <= kernel_size[1] - padding[1]

  bs, ch, height, width = input.shape
  inv_weight = weight.transpose(0, 1).flip([2, 3]).contiguous().cpu().detach().numpy() # to avoid Flip op

  h = input.unsqueeze(4).unsqueeze(5)
  h = F.pad(h, (
      0, stride[1]-1,
      0, stride[0]-1)) # padding is processed from the last axis
  h = h.transpose(3, 4).contiguous().view(bs, ch, height * stride[0], width * stride[1])
  h = F.pad(h, (
      kernel_size[1] - padding[1] - 1, kernel_size[1] - padding[1] - stride[1],
      kernel_size[0] - padding[0] - 1, kernel_size[0] - padding[0] - stride[0]))
  y = F.conv2d(h, torch.tensor(inv_weight), bias, stride=1, padding=0)
  return y
```

You can override `torch.nn.functional.conv_transpose2d` before exporting your model to onnx, and if no assertion fails, you can obtain an onnx model without ConvTranspose.

Here is the notebook of an experiment of my implementation.
https://gist.github.com/Yosshi999/7c05c6cc8c85c2702cb11da3e577dcd1

**Comment by 101arrowz** [comment]
@Yosshi999 good workaround, might be more performant than my solution due to lack of optimization.

I've successfully implemented ConvTranspose (the issue with row/col order DID end up being my code - I didn't realize that the `getX`/`getW`/`getB` functions took a different order for indices than NumPy). A PR is open: #11990
