### ISSUE TITLE
Clone failed

### ISSUE THREAD

**Issue by ivanov-wai** [microsoft/onnxruntime#9259]
**Describe the bug**

Got an error during repo cloning:

```
remote: A repository for this project does not exist yet.
fatal: repository 'https://gitlab.com/libeigen/eigen.git/' not found
fatal: clone of 'https://gitlab.com/libeigen/eigen.git' into submodule path '/build/onnxruntime/cmake/external/eigen' failed
```

**Urgency**
n/a

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): amazon linux 2
- ONNX Runtime version: 1.7.2

**To Reproduce**
Recursive clone

**Additional context**
https://gitlab.com/libeigen/eigen/-/issues/2336

**Comment by jcwchen** [comment]
Hi @ivanov-wai,
Thank you for catching this issue. `eigen` is finally back now: https://gitlab.com/libeigen/eigen. I can successfully git clone onnxruntime recursively right now. Could you please try again?

**Comment by ivanov-wai** [comment]
I confirmed it works fine now
