### ISSUE TITLE
Split operator is not working for String type input

### ISSUE THREAD

**Issue by imeckr** [microsoft/onnxruntime#927]
onnxruntime is not able to find the implementation for string type input

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-387-4777a6f2476d> in <module>()
----> 1 sess = rt.InferenceSession("custom_converter.onnx")

~/miniconda3/envs/ltr/lib/python3.6/site-packages/onnxruntime/capi/session.py in __init__(self, path_or_bytes, sess_options)
     27 
     28         if isinstance(path_or_bytes, str):
---> 29             self._sess.load_model(path_or_bytes)
     30         elif isinstance(path_or_bytes, bytes):
     31             self._sess.read_bytes(path_or_bytes)

RuntimeError: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node Split(2)
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary): pip
- ONNX Runtime version: 0.3.0
- Python version: 3.6.7(packaged by conda-forge)

**Comment by pranavsharma** [comment]
Can you attach custom_converter.onnx for further debugging?

**Comment by imeckr** [comment]
Here is the link to the [custom_converter.onnx](https://drive.google.com/open?id=1MiSq0lLR78r4jalwkVO343ieFMABJ-30)

Its a simple operation
![graph dot](https://user-images.githubusercontent.com/7942293/57137872-7b68f780-6d87-11e9-848e-69f17343f93d.png)
