### ISSUE TITLE
Onnxruntime in WSL with CUDA is much slower than windows

### ISSUE THREAD

**Issue by dlangerm** [microsoft/onnxruntime#9276]
**Describe the bug**
I'm running the windows 11 version of wsl with cuda enabled and the `onnxruntime-gpu` package. I'm running a straightforward batched image task on a small subset of all ~20k images I have. 

The exact same code running the same versions of all packages (when possible) in WSL takes ~2m58s to complete, whereas on Windows it takes ~19s. 

**Urgency**
It feels urgent to me but I'm sure it's pretty low on the list of priorities and I can make it work in the meantime by swapping this part of my workflow back to windows.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 11, WSL Ubuntu 20.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.9.0
- Python version: 3.9
- CUDA/cuDNN version: 
    - WSL:  `NVIDIA-SMI 470.63.01    Driver Version: 471.68       CUDA Version: 11.4`
    - Windows:  `NVIDIA-SMI 471.68       Driver Version: 471.68       CUDA Version: 11.4`
- GPU model and memory: RTX 3090, 24gb

**To Reproduce**
Run a basic model in wsl and run it on windows, observe the difference.

**Expected behavior**
I'd expect WSL to at least be in the ballpark of windows performance. I know there's some overhead but this seems execcisve.

**Additional context**
This is obviously only possible with the release preview of windows since it enables CUDA in WSL, so I expect this bug was easy to miss. Additionally, the GPU utilization when I run my kernels this way is extremely low, but not zero -- so it is using the GPU (I think) -- just not well. Contrast with windows where I can max out the utilization and memory.

**Comment by dlangerm** [comment]
It's probably also worth noting that I do get really good performance for other cuda apps in WSL. In fact the models I'm using for this were trained with pytorch in WSL, so I don't believe it's a configuration issue.

**Comment by skottmckay** [comment]
Did you explicitly enable the CUDA Execution Provider? 

https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#python

**Comment by dlangerm** [comment]
@skottmckay yes I did, I even disabled the CPU execution provider.

**Comment by dlangerm** [comment]
Here is what I see on WSL:
```
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import onnxruntime
>>> onnxruntime.__version__
'1.9.0'
>>> onnxruntime.cuda_version
''
>>> onnxruntime.get_device()
'GPU'
>>> onnxruntime.get_available_providers()
['CUDAExecutionProvider', 'CPUExecutionProvider']
```

**Comment by skottmckay** [comment]
Looks like something is preventing the CUDA EP from actually being used. If I run the following I see output showing the CUDA EP is used when run from Windows, but not when run from WSL. This is with Windows 10 so it seems to be a general WSL+CUDA issue. 

@RyanUnderhill is there a good way to debug whether the CUDA EP is being successfully loaded using the release package or would a debug build be required?

```
    model = 'FasterRCNN-10.onnx'
    providers = [
        ('CUDAExecutionProvider', {
            'device_id': 0,
            'arena_extend_strategy': 'kNextPowerOfTwo',
            'gpu_mem_limit': 2 * 1024 * 1024 * 1024,
            'cudnn_conv_algo_search': 'EXHAUSTIVE',
            'do_copy_in_default_stream': True,
        }),
        'CPUExecutionProvider',
    ]

    so = onnxruntime.SessionOptions()
    so.log_severity_level = 0
    ort_session = onnxruntime.InferenceSession(model, sess_options=so, providers=providers)

```

Windows:
> 2021-10-11 10:05:20.8702365 [V:onnxruntime:, inference_session.cc:159 onnxruntime::`anonymous-namespace'::VerifyEachNodeIsAssignedToAnEp]  Provider: [CUDAExecutionProvider]: [Unsqueeze (0), MaxPool (8), Conv (24), ...]


WSL:
> 2021-10-11 10:06:41.080253300 [V:onnxruntime:, inference_session.cc:154 VerifyEachNodeIsAssignedToAnEp] All nodes have been placed on [CPUExecutionProvider].
