### ISSUE TITLE
Is it on purpose that the combination of both build parameters '--x86' and 'msvc_toolset' impossible?

### ISSUE THREAD

**Issue by cr-orkunst** [microsoft/onnxruntime#9291]
### Discussed in https://github.com/microsoft/onnxruntime/discussions/9290

<div type='discussions-op-text'>

<sup>Originally posted by **cr-orkunst** October  6, 2021</sup>
Hi everyone,
I'm pretty new with onnxruntime, so please be nice :)
I'm having problems adjusting the build parameters and make them work as I would expect.

Environment details:
- Windows 10, 64-bit machine.
- VS2019 , version 16.11.1.
- MSVC v142 - VS 2019 C++ x64/x86 build tools (Latest)
- MSVC v141 - VS 2017 C++ x64/x86 build tools (v14.16)
- Windows 10 SDK (10.0.17763.0)

Following the [instructions here](https://onnxruntime.ai/docs/build/inferencing.html), I'm trying to build onnxruntime.dll for 32-bit, using the following command: "build.bat --config Release --x86 --build_shared_lib --parallel --msvc_toolset 14.16"
According to "onnxruntime/tools/ci_build/build.py" (master and rel-1.9.1), if the '--x86' parameter is passed, the '--msvc_toolset' parameter is ignored:
```
...
elif cpu_arch == '32bit' or args.x86:
    cmake_extra_args = [
        '-A', 'Win32', '-T', 'host=x64', '-G', args.cmake_generator
    ]
else:
    if args.msvc_toolset:
        toolset = 'host=x64,version=' + args.msvc_toolset
    else:
...
```

What am I missing? Is there a reason not to use both parameters at the same build?
Thanks!

</div>

**Comment by snnn** [comment]
No, it is not.  Welcome to help us improve it.

**Comment by snnn** [comment]
Should have been implemented.
