### ISSUE TITLE
help add this repo to vcpkg

### ISSUE THREAD

**Issue by bitnick10** [microsoft/onnxruntime#931]
https://github.com/Microsoft/vcpkg
https://github.com/Microsoft/vcpkg/issues/6077

**Comment by pranavsharma** [comment]
@bitnick10 We would love to see contributions here if you've the resources. Thanks.

**Comment by snnn** [comment]
I just gave a try, it's extremely hard. By default vcpkg builds protobuf but protobuf isn't designed to work well in that way.

**Comment by faxu** [comment]
Completed

**Comment by snnn** [comment]
Ort can consume packages from vcpkg, but itself is not in vcpkg yet.

**Comment by bitnick10** [comment]
Cool

**Comment by luncliff** [comment]
Now we have a `onnxruntime` port in vcpkg master branch. Leaving comment to append link between issues and PRs.

- https://github.com/microsoft/vcpkg/pull/36850
- https://github.com/microsoft/vcpkg/commit/2c9fdb85b4fbf193c0d0997dce81130e2433fe67
