### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException

### ISSUE THREAD

**Issue by guici123** [microsoft/onnxruntime#9324]
**Describe the bug**
I'm trying to write a converter for TfIdfVectorizer when analyser=='char'.I found two bugs while converting a TfIdfVectorizer. The first one comes from scikit-learn which creates ambiguities when trying to retrieve n-grams if the tokens contain spaces. The other bug initialization error, but  initialization sucess when analyser=='word'.

**Urgency**
2021.10.13

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):wind10
- ONNX Runtime installed from (source or binary):pip
- ONNX Runtime version:1.8.1
- Python version:3.7

**To Reproduce**
pipe = Pipeline([('tfidf', TfidfVectorizer(max_features=4000, min_df=5, max_df=0.5, analyzer='char')),
                 ('lr', LogisticRegression())])
pipe.fit(train_data, train_labels)
options = {id(pipe): {'zipmap': False}}
model_onnx = convert_sklearn(
    pipe, 'pipeline_lr',
    initial_types=[('input', StringTensorType([1, 1]))],
    target_opset=12, options=options)
sess = rt.InferenceSession("pipeline_lr.onnx")

onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Exception during initialization: D:\a\_work\1\s\onnxruntime\core\providers\cpu\nn\string_normalizer.cc:289 onnxruntime::StringNormalizer::StringNormalizer p.second was false. Duplicate stopwords not allowed

**Expected behavior**
onnxruntime  should initialization success.

**Comment by garymm** [comment]
@xadupre could you please take a look, at least to determine if this issue is an ORT issue or a SKLearn-ONNX issue?
