### ISSUE TITLE
ConvolutionTranspose padding mode SAME_UPPER/SAME_LOWER problem

### ISSUE THREAD

**Issue by yyyokata** [microsoft/onnxruntime#9370]
**Describe the bug**
In https://github.com/microsoft/onnxruntime/blob/22e3f8bf549e66ae2f0b6baa64ca01656e2865ad/onnxruntime/core/providers/cpu/nn/conv_transpose_attributes.h#L179, we have:
    if (pad_type == AutoPadType::SAME_UPPER) {  // pad more on head when total_pad is odd.
      pad_head = total_pad - total_pad / 2;
      pad_tail = total_pad / 2;
    } else {
      // for pad_type is NOTSET, SAME_LOWER or VALID
      // set pad_head as total_pad/2, pad_tail as total_pad-total_pad/2.
      // That said, we pad more on tail when total_pad is odd.
      pad_head = total_pad / 2;
      pad_tail = total_pad - total_pad / 2;
    }
but in ONNX https://github.com/onnx/onnx/blob/2e048660ffa8243596aaf3338e60c7c0575458f2/onnx/defs/nn/defs.cc#L1249, 
        if (auto_pad_attr->s() == "SAME_UPPER") {
          pads[i] = half_pad_small;
          pads[i + input_dims_size] = half_pad_big;
        } else if (auto_pad_attr->s() == "SAME_LOWER") {
          pads[i] = half_pad_big;
          pads[i + input_dims_size] = half_pad_small;
        }
It seems like the behavior of convtrans goes to the opposite under an odd total_pad situation.

**Urgency**
None.

**System information**
-

**To Reproduce**
-

**Expected behavior**
Should do as origin onnx def.

**Screenshots**
-

**Additional context**
-

**Comment by jcwchen** [comment]
Hi @yyyokata,
I have a pending PR for it (was waiting for ORT consuming the latest ONNX): https://github.com/microsoft/onnxruntime/pull/8769. I will try to forward it before next ORT release. Thank you for catching this.

**Comment by jcwchen** [comment]
It should be fixed by https://github.com/microsoft/onnxruntime/pull/12537. Thank you for catching this issue!
