### ISSUE TITLE
No Op registered for ConstantOfShape with domain_version of 11

### ISSUE THREAD

**Issue by BChunlei** [microsoft/onnxruntime#9384]
**Describe the bug**
I use c++ api to do inference with onnx model:
terminate called after throwing an instance of 'Ort::Exception'
  what():  Load model from ./faster_dianlan3.onnx failed:This is an invalid model. Error in Node:ConstantOfShape_1085 : No Op registered for ConstantOfShape with domain_version of 11
Aborted (core dumped)

but I find ConstantOfShape is supported bu onnxruntime 1.8.2. What's the problem?

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 18.04
- ONNX Runtime installed from (source or binary):source
- ONNX Runtime version:1.8.2
- Python version:
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Comment by skottmckay** [comment]
Are you able to share the model? Looks like almost all types are supported by ConstantOfShape from opset 9 and on. 

Are you excluding any operators via the build flags you are using? Could you share your build command line as well please?

<html>
<body>


ConstantOfShape | in input:T1out output:T2 | 9+ | T1 = tensor(int64)T2 = tensor(bool), tensor(double), tensor(float), tensor(float16), tensor(int16), tensor(int32), tensor(int64), tensor(int8), tensor(uint16), tensor(uint32), tensor(uint64), tensor(uint8)
-- | -- | -- | --



</body>
</html>

**Comment by BChunlei** [comment]
This is my build command:
./build.sh --build_shared_lib --cuda_home /usr/local/cuda-11.2 --cudnn_home /usr/lib/x86_64-linux-gnu/ --use_cuda --config Release --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=1.8.2 CMAKE_CUDA_ARCHITECTURES=86

This is the [model link](https://pan.baidu.com/s/19IW8oVMcvH3tkwsElsXbHw ), code：40hd

**Comment by skottmckay** [comment]
I'm not able to download the model from that link. Can you please put it somewhere where installing software is not required to download it?

**Comment by BChunlei** [comment]
The model is in the [repository](https://github.com/BChunlei/faster-rcnn-onnx)

**Comment by skottmckay** [comment]
I'm able to load and execute the model without any problems using the 1.9 ORT release package. Is there a reason you need to build from source?

The netron screenshot showing no input to the ConstantOfShape node is because the input is an initializer and not the output from another node. This is perfectly valid. 

![image](https://user-images.githubusercontent.com/979079/138029632-85b118d6-272a-482f-a88b-abef81c15710.png)

> --cmake_extra_defines ONNXRUNTIME_VERSION=1.8.2

The actual ORT version is whatever version you checked out from github. What does `git rev-parse  HEAD` report as your current commit id?

Are there any other changes to your local repo that `git status` reports?

**Comment by BChunlei** [comment]
Thank you very much! The error has been solved. I register the new op which is not supported in onnxruntime. 
As you said, I just modiy the code:
`Ort::CustomOpDomain custom_op_domain("");`
to:
`Ort::CustomOpDomain custom_op_domain("abc");`

**Comment by BChunlei** [comment]
I want to register the new op named 'MMCVRoiAlign' which is not supported in onnxruntime.
My understanding is I should register my op with a custom domain?
I just modify the code :

`Ort::CustomOpDomain custom_op_domain("");`
to:
`Ort::CustomOpDomain custom_op_domain("abc");`

More details:
```
  Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "");
  Ort::SessionOptions session_options;
  session_options.SetIntraOpNumThreads(1);
  session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_ALL);

  cudaStream_t compute_stream = nullptr;

  MMCVRoiAlign custom_op{"CUDAExecutionProvider", compute_stream};
  //ConstantOfShape custom_op2{"CUDAExecutionProvider", compute_stream};

  Ort::CustomOpDomain custom_op_domain("abc");

  custom_op_domain.Add(&custom_op);

  session_options.Add(custom_op_domain);

  int device_id = 0;
  Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, device_id));

  Ort::Session session(env, model_path, session_options);
```

When I use the custom domain "abc" , onnxruntime can't find the new registered op:
`Load model from ./faster.onnx failed:Fatal error: MMCVRoiAlign is not a registered function/op`
When I use default domain "", the above error disappear. But shows:
`Load model from ./faster.onnx failed:This is an invalid model. Error in Node:ConstantOfShape_1002 : No Op registered for ConstantOfShape with domain_version of 11`

**Comment by skottmckay** [comment]
Most likely the error doesn't disappear - the model just fails earlier due to the onnx kernel lookup failure when the domain is empty.

Does the MMCVRoiAlign node in the model have a domain of 'abc'? Should be able to check that using Netron.

**Comment by BChunlei** [comment]
![image](https://user-images.githubusercontent.com/44046955/140017900-ab5fe4f0-ea53-4890-bfa5-07a0c7283247.png)

It seems ok, the module "mmcv" should be the domain, right?

When I use following code:
`Ort::CustomOpDomain custom_op_domain("mmcv");`

both errors disappear.

By the way, where could I look for more details about onnxruntime or how to use onnxruntime.

**Comment by skottmckay** [comment]
For the model to load successfully what Netron is calling 'module' must be the domain.

Documentation is at https://onnxruntime.ai/
