### ISSUE TITLE
pkg-config include paths should include API dir

### ISSUE THREAD

**Issue by devrite** [microsoft/onnxruntime#9385]
**Describe the bug**
This reflects my opinion, maybe the current behavior is the better way.

The package config file only defines the top level include paths, so users have to add the API include paths (`core/session`) themselves, which for most packages you do not have to. The provided config normally works out of the box.

**Urgency**
Low, can be worked around by specifying the path manually.

**To Reproduce**
Nothing special just compile and/or look at `libonnxruntime.pc.in` and the way headers are included in the API examples

**Expected behavior**
A successful package config based search should produce the necessary include paths such that they match the documented way of usage (opinion). A user should normally not need to  add anything, at least this is true for most packages.

This could be done by either providing this path/include flag additionally or by specifying an additional pkg-config component that provides that path.

I could provide a PR if it is better to do a suggested.

BR

**Comment by devrite** [comment]
Just the generated libonnx

**Comment by skottmckay** [comment]
I'd be wary of adding the extra path segments to the include in CFlags in case `core/session/environment.h` clashed with another header of that name and caused build breakages. And as existing builds may already reference that header moving it would also potentially cause build breakages.

> or by specifying an additional pkg-config component that provides that path.

What would this look like and how would it be used?

**Comment by devrite** [comment]
OK.

The second option is basically just adding another package config file, e.g. onnxruntime-session.pc, which could include that path. Usually we do that only for extra components or modules, which are often extra addon packages. A good example for the latter is Gstreamer, which has the core package, vídeo, audio, extra plugins,.....

Or anything if that is not really desired and as you said it has caused clashes already I suggest either moving the API header to the top level dir, which would not cause further clashes as this path is already included or by updating the docs and the examples to rather use the relative path from top level dir to the API.

For backwards compatibility if some projects already, specified this path in their includes, when the header is TL, we could provide a header that includes the TL one or vice versa.

How are you using it? Or suggest using it? Do you add the path, which I currently do in my projects to keep the doc style or do you use the full relative path?
