### ISSUE TITLE
The Windows Debug build of onnxruntime fails with "fatal error C1128"

### ISSUE THREAD

**Issue by sstamenova** [microsoft/onnxruntime#9396]
**Describe the bug**
The Windows Debug build of onnxruntime fails with "fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj"

**Urgency**
None

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: commit da56f01ac20ac7e1793a3847ec6c8d3111b5e7a6
- Python version: 3.9
- Visual Studio version (if applicable): Visual Studio 2019 Developer Command Prompt v16.11.4
- GCC/Compiler version (if compiling from source): MSVC 19.29.30136.0

**To Reproduce**
- Describe steps/code to reproduce the behavior.
Build onnxruntime with `--config Debug`

**Expected behavior**
The build succeeds.

`/bigobj` should be added as one of the default CXX flags for the builds on Windows. This is default for `llvm-project` (and `mlir`), `onnx-mlir`, etc.

The full error is:
```
D:\a\_work\1\s\onnx-mlir\third_party\onnxruntime\orttraining\orttraining\python\orttraining_pybind_state.cc : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj [D:\a\_work\1\s\onnx-mlir\third_party\onnxruntime\build\Windows\Debug\onnxruntime_pybind11_state.vcxproj]
```

**Comment by yuslepukhin** [comment]
Would you like to create a PR with the change?

**Comment by snnn** [comment]
The flag is added.
