### ISSUE TITLE
Is python faster than c++?

### ISSUE THREAD

**Issue by Myxrf** [microsoft/onnxruntime#9407]
Why does it take 200ms for my onnx model to run under python, but 400ms for c++?

**Comment by stereomatchingkiss** [comment]
Please show us your codes, tell us your 

. platform(os)
. which onnxruntime version you are using
. compiler
. make file

Create a minimum example, this could help other's help you solve the issue.

**Comment by Myxrf** [comment]
@stereomatchingkiss 

1. platform  windows
2. python - onnxruntime-gpu 1.9.0    c++ - 1.8
3. python  code
`ort_session = ort.InferenceSession('maskrcnn_resnet50_fpn.onnx') 
 outputs = ort_session.run(None, {'image': img})
 time_start=time.time()
 outputs = ort_session.run(None, {'image': img})
 time_end=time.time()
 print('totally cost',time_end-time_start)`

4. c++ code
`    Ort::Env env(ORT_LOGGING_LEVEL_WARNING, "test");
    Ort::SessionOptions session_options;
    session_options.SetIntraOpNumThreads(1);
    session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED); 
    OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0);
    Ort::Session session(env, model_path, session_options);
 start = clock();
    std::vector<Ort::Value> output_tensors = session->Run(Ort::RunOptions{ nullptr }, input_node_names.data(), ort_inputs.data(), 1, output_node_names.data(), 4);
    std::cout << sizeof(output_tensors[1]) << endl;
    end = clock();		
    double endtime = (double)(end - start) / CLOCKS_PER_SEC;
`
5. 2080ti  cuda10.1

**Comment by skottmckay** [comment]
Additionally you have a warmup request in the python code but not in the C++ code.
