### ISSUE TITLE
failed to load yolov4 model when options.AppendExecutionProvider_DML(0)

### ISSUE THREAD

**Issue by wanglvhang** [microsoft/onnxruntime#9409]
**Describe the bug**
when i try load yolov4 model and set options.AppendExecutionProvider_DML(0); below error thrown:
Microsoft.ML.OnnxRuntime.OnnxRuntimeException:“[ErrorCode:RuntimeException] Exception during initialization: D:\a\_work\1\s\onnxruntime\core\graph\function.cc:459 onnxruntime::FunctionImpl::FunctionImpl status.IsOK() was false. This is an invalid model. Error: two nodes with same node name (StatefulPartitionedCall/model/tf_op_layer_strided_slice_1/strided_slice_1).

but when i set options.AppendExecutionProvider_CPU(0); the model loaded.

the yolov4 model is downloaded from:
https://github.com/onnx/models/blob/master/vision/object_detection_segmentation/yolov4/model/yolov4.onnx

btw: im using onnx in wpf application.

**System information**
- OS Platform and Distribution (windows 10 20H2):
- ONNX Runtime installed from (Microsoft.ML.OnnxRuntime.DirectML 1.9.0  / DirectML dll 1.7.0.0):
- ONNX Runtime version: 1.9.0 
- Python version: N/A
- Visual Studio version (2019 16.11.4):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: N/A
- GPU model and memory: GTX950 2G

**To Reproduce**
code:
            SessionOptions options = new SessionOptions();
            options.LogSeverityLevel = OrtLoggingLevel.ORT_LOGGING_LEVEL_INFO;
            options.AppendExecutionProvider_DML(0);
            _onnxSession = new InferenceSession(model_path, options); //the line error thrown

**Expected behavior**
load model successfully

**Screenshots**
N/A

**Additional context**
N/A

**Comment by fdwr** [comment]
@wanglvhang : We have a pending fix for this https://github.com/microsoft/onnxruntime/pull/9929/files. It won't make ORT 1.10.0 release though, meaning it would need to be compiled from master (or possibly a 1.10.1 patch release).

**Comment by fdwr** [comment]
This will be out soon in ORT 1.11. Please apply locally with the 1-line fix, build current master, or use 1.11 once out.

**Comment by sanxincao** [comment]
> **Describe the bug** when i try load yolov4 model and set options.AppendExecutionProvider_DML(0); below error thrown: Microsoft.ML.OnnxRuntime.OnnxRuntimeException:“[ErrorCode:RuntimeException] Exception during initialization: D:\a_work\1\s\onnxruntime\core\graph\function.cc:459 onnxruntime::FunctionImpl::FunctionImpl status.IsOK() was false. This is an invalid model. Error: two nodes with same node name (StatefulPartitionedCall/model/tf_op_layer_strided_slice_1/strided_slice_1).
> 
> but when i set options.AppendExecutionProvider_CPU(0); the model loaded.
> 
> the yolov4 model is downloaded from: https://github.com/onnx/models/blob/master/vision/object_detection_segmentation/yolov4/model/yolov4.onnx
> 
> btw: im using onnx in wpf application.
> 
> **System information**
> 
> * OS Platform and Distribution (windows 10 20H2):
> * ONNX Runtime installed from (Microsoft.ML.OnnxRuntime.DirectML 1.9.0  / DirectML dll 1.7.0.0):
> * ONNX Runtime version: 1.9.0
> * Python version: N/A
> * Visual Studio version (2019 16.11.4):
> * GCC/Compiler version (if compiling from source):
> * CUDA/cuDNN version: N/A
> * GPU model and memory: GTX950 2G
> 
> **To Reproduce** code: SessionOptions options = new SessionOptions(); options.LogSeverityLevel = OrtLoggingLevel.ORT_LOGGING_LEVEL_INFO; options.AppendExecutionProvider_DML(0); _onnxSession = new InferenceSession(model_path, options); //the line error thrown
> 
> **Expected behavior** load model successfully
> 
> **Screenshots** N/A
> 
> **Additional context** N/A

抄您的代码遇到同样的问题Google到此。。。。。
