### ISSUE TITLE
INT8 input & FP32 output for single op

### ISSUE THREAD

**Issue by mengniwang95** [microsoft/onnxruntime#9410]
Is it possible to pass int8 data into one op and outputs fp32 data directly?
Now I found it requires a dequant op to generate fp32 data which may harm the performance.

**Comment by skottmckay** [comment]
The ONNX spec defines input and output types for operators. https://github.com/onnx/onnx/blob/master/docs/Operators.md

If the operator can not produce fp32 output from int8 input, a DequantizeLinear or Cast would be required.

**Comment by mengniwang95** [comment]
I mean if it is possible for future op design: For example, set the output of QLinearConv to FP32, then the op will output fp32 data automatically without inserting Dequant op
