### ISSUE TITLE
CoreML provider (Python API): ANE/ GPU not used, falling back on CPU?

### ISSUE THREAD

**Issue by simonbunge** [microsoft/onnxruntime#9433]
**Describe the bug**

_What is the rationale for restricting CoreML inference to the CPU and would there be any reason to not change the methods'/ functions' signatures to include a parameter as to offer a _choice_ of Processing Unit Configuration?_

This may be a feature rather than a bug, but the rationale (possibly controlling inference precision?) for the current state is not obvious, hence before forking for my purposes and/ or proposing a PR, I figured it would be prudent to raise it as a question first.

Specifically, during the [loading of CoreML models](https://github.com/microsoft/onnxruntime/blob/5b65f1cb44eee6d82b9ba3b91a43b5b4a74ccae8/onnxruntime/core/providers/coreml/model/model.mm#L175-L198), model configuration is currently [set](https://github.com/microsoft/onnxruntime/blob/5b65f1cb44eee6d82b9ba3b91a43b5b4a74ccae8/onnxruntime/core/providers/coreml/model/model.mm#L189) to `MLComputeUnitsAll`, i.e. for the GPU and Apple Neural Engine (ANE) to be used.

However, at [prediction stage](https://github.com/microsoft/onnxruntime/blob/5b65f1cb44eee6d82b9ba3b91a43b5b4a74ccae8/onnxruntime/core/providers/coreml/model/model.mm#L200-L288), prediction options are [set ](https://github.com/microsoft/onnxruntime/blob/5b65f1cb44eee6d82b9ba3b91a43b5b4a74ccae8/onnxruntime/core/providers/coreml/model/model.mm#L215) to `MLComputeUnitsCPUOnly`.
This obviously renders the GPU and more importantly the ANE irrelevant. Which, for my use case, causes a _prohibitive_ performance impact, in other words: the models we're looking at _require_ acceleration.
Also, this setting is unfortunately _hard-coded_, i.e. can't be overridden by passing a parameter.

**Urgency**

Medium. This involves a business decision as to whether Apple Silicon is a viable alternative to CUDA-based Windows machines to be made by the end of the month.

**System information**

- OS Platform and Distribution: MacOS BigSur (MacBook Air M1)
- ONNX Runtime installed from: source (with CoreML support)
- ONNX Runtime version: v1.9.1

**Comment by skottmckay** [comment]
Isn't the setting based on the user specified coreml flags, meaning a user would have to explicitly request this behavior?

`  options.usesCPUOnly = coreml_flags_ & COREML_FLAG_USE_CPU_ONLY;`

The ability to specify CPU only is primarily for validation. 
 
https://github.com/microsoft/onnxruntime/blob/5b65f1cb44eee6d82b9ba3b91a43b5b4a74ccae8/include/onnxruntime/core/providers/coreml/coreml_provider_factory.h#L15-L17

**Comment by simonbunge** [comment]
I applied it to the original model and still ended up in the "Dynamic shape is not supported..." branch of the code. No in-depth analysis of the reasons done (for which hope you'll forgive me for that as I sincerely appreciate the effort you put into the hack!).

As you say, the absence of support for certain ops is the really pertinent point here as it determines the _practical_ feasibility of running these models in real time.
Your reference to HardSigmoid specifically relates to the onnxrt provider not currently supporting it, right? As opposed to the CoreML framework as such.

**Comment by skottmckay** [comment]
FWIW if the model had fixed input sizes, we could add support for Sub/Div/Mul/HardSigmoid to the ORT CoreML EP easily. Split/Slice/ReduceMean reasonable easily. Expand is not really needed. There's one Expand node per r?i input which converts the input to the actual shape required (which is why you can get away with passing in {1,1,1,1} for the initial state). If you provide those inputs with the correct shape those nodes aren't needed, but it's also fine for them to run on CPU as they're on the edge.

FWIW script to update the model so that the inputs/outputs have fixed sizes and the downsample_ratio is a constant value.

```python
import onnx
from onnx import shape_inference

r_shapes = [(1, 16, 135, 240),
            (1, 20, 68, 120),
            (1, 40, 34, 60),
            (1, 64, 17, 30)]

def update_model():
    m = onnx.load(r'rvm_mobilenetv3_fp32.onnx')

    def update_dim_values(value_infos, updates):
        for vi in value_infos:
            if vi.type.HasField("tensor_type"):
                shape = vi.type.tensor_type.shape
                if shape:
                    for dim in shape.dim:
                        if dim.HasField('dim_param') and dim.dim_param in updates:
                            dim_param = dim.dim_param  # save before Clear
                            dim.Clear()
                            dim.dim_value = updates[dim_param]

    def update_named_input_output(items, updates):
        for item in items:
            if item.name in updates:
                new_dims = updates[item.name]
                for idx in range(len(new_dims)):
                    item.type.tensor_type.shape.dim[idx].Clear()
                    item.type.tensor_type.shape.dim[idx].dim_value = new_dims[idx]

    def fix_downsample_ratio(graph):
        from onnx import helper
        from onnx import TensorProto
        if graph.input[len(graph.input) - 1].name == 'downsample_ratio':
            graph.input.pop()
            # add initializer instead
            ratio = helper.make_tensor('downsample_ratio', TensorProto.FLOAT, [1], [0.25])
            graph.initializer.append(ratio)

    input_updates = {
        'r1i': r_shapes[0],
        'r2i': r_shapes[1],
        'r3i': r_shapes[2],
        'r4i': r_shapes[3]
    }

    output_updates = {
        'r1o': r_shapes[0],
        'r2o': r_shapes[1],
        'r3o': r_shapes[2],
        'r4o': r_shapes[3]
    }

    updates = { 'batch_size': 1,
                'channels': 3,
                'height': 1080,
                'width': 1920 }

    update_named_input_output(m.graph.input, input_updates)
    update_named_input_output(m.graph.output, output_updates)

    update_dim_values(m.graph.input, updates)
    update_dim_values(m.graph.output, updates)
    update_dim_values(m.graph.value_info, updates)

    fix_downsample_ratio(m.graph)

    m1 = onnx.shape_inference.infer_shapes(m)
    onnx.checker.check_model(m1)
    onnx.save(m1, r'rvm_mobilenetv3_fp32.fixed.onnx')

update_model()

```
