### ISSUE TITLE
Inference time gets slower over time (gpu + multithread)

### ISSUE THREAD

**Issue by jpsalada** [microsoft/onnxruntime#9442]
**Describe the bug**
Inference time gets slower and slower over time, using gpu and multithread. Each thread has a session assigned to it.  I am exposing OnnxRuntime in a C++ dll, which is being used by a C#/.Net Framework Web API running in IIS.

**Urgency**
I have urgency with this. We have clients awaiting.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Same behavior with Windows Server 2019 and Windows 10
- ONNX Runtime installed from (source or binary): binaries
- ONNX Runtime version: 1.8.1
- Python version: NA
- Visual Studio version (if applicable): 2019
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: Occurs with Cuda 11.1 and 11.4
- GPU model and memory: RTX 2080, V100 and P40

**To Reproduce**
- Read video frames of a video in a C# application
- Deliver each video frame to a thread that will forward the frame to my C++ dll with Onnxruntime session.
- Compute the inference
- Inference time will get slower over time, and while it take 5ms at the beginning, after some hours running, it can take 1000ms.
- If I only use one thread, this behavior does not occur and everything seems stable.

**Expected behavior**
Inference time should not increase over time.

**Comment by skottmckay** [comment]
Have you checked memory usage for you app? This hasn't been reported as an issue anywhere else, including server based usage of ORT. Wondering if you're disposing of the ORT C# types correctly.

Additionally I would recommend having just one session and not a per-thread session. ORT supports concurrent calls so it's fine for a single session to be shared. Having multiple sessions means each one has it's own memory arena and thread pool so it's going to be far less efficient.

**Comment by cqray1990** [comment]
@jpsalada  how did you do inference with  multithread,did you seuccess? can u give me some advisement?thank u?
