### ISSUE TITLE
Errors When Calling onnxruntime.InferenceSession

### ISSUE THREAD

**Issue by demib72** [microsoft/onnxruntime#9465]
**Describe the bug**
When calling self.detection_model = onnxruntime.InferenceSession(checkpoint_path, providers=providers), I am greeted by the following errors: https://zerobin.net/?9b97f112edaeb163#obfaD/Fi0dXXfqE5Gnq5qU9xZ5qdy1RxYsuhz6Vak54=

**Urgency**
None, just throwing in the towel in trying to figure this out on my own.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Pop OS 21.04
- ONNX Runtime installed from (source or binary): Binary
- ONNX Runtime version: 1.9.0
- Python version: 3.8.8 (Conda)/3.9.7 (outside of Conda)
- CUDA/cuDNN version: 11.4/8.2.4
- GPU model and memory: RTX 2060 (Laptop), 6 GB

**To Reproduce**
- Code: https://zerobin.net/?33730c3660fdb0c9#VIrXgxBxFm88n4NqQ4Us/inKXDA3WFrRXvr0Tj4mvwA= (requires NudeNet from pip)
- https://github.com/notAI-tech/NudeNet/releases/download/v0/detector_v2_default_checkpoint.onnx

**Expected behavior**
Output the classification of the image. 

**Additional context**
I believe the onnx is converted from a tensorflow model (https://github.com/notAI-tech/NudeNet/releases/download/v0/detector_v2_default_checkpoint_tf.tar). Don't know if that is relevant or not, but figure I would mention it.

**Comment by demib72** [comment]
If it helps, I tried using the code with an earlier version of onnxruntime-gpu (1.8.1). It doesn't immediately dump, but it does end with the following errors: https://zerobin.net/?3ae768da40d0bd3d#ZGB8r85dX+FhP1HMfRQzqUg3hGQcMTBRfV6aay7zfHw=

**Comment by skottmckay** [comment]
If it's the same issue it should be fixed for both CPU and CUDA in the upcoming 1.10 release. That should be out in the next week or two, or you can build from source if you need something sooner.

**Comment by BlackJones** [comment]
> If it's the same issue it should be fixed for both CPU and CUDA in the upcoming 1.10 release. That should be out in the next week or two, or you can build from source if you need something sooner.

Thanks,look forward to the 1.10 version
