### ISSUE TITLE
"Float16" data type are not support in C# (Which mean it will impact to use the FP16 model in Onnxruntime)

### ISSUE THREAD

**Issue by NWH1111** [microsoft/onnxruntime#948]
**Is your feature request related to a problem? Please describe.**
When I tried to test with Float16 model, it will run with error - 
"Unexpected input data type. Actual: (class onnxruntime::NonOnnxType float) , expected: (class onnxruntime::NonOnnxType union onnxruntime::MLFloat16)". cause I cannot find any datatype to fulfill MLFloat16 requirement (so I put the float as input). 

It seems like there's lack of float16 support in onnxruntime. Can anybody know how to pass data to "float16" onnx models in C#? Thanks.

Here is the quick sample in my code:
var container = new List<NamedOnnxValue>();
container.Add(NamedOnnxValue.CreateFromTensor `<float>` (inputName, inputTensor));
using (var results = session.Run(container)) --> it will pop up an error "Unexpected input data type" like above

**System information**
- Microsoft.ML.OnnxRuntime.Gpu version (0.3.1):
- Windows 10 19H1 with RTX2080

**Describe the solution you'd like**
DataType<Float> can be used for Float16 model and it will auto convert from float32 --> float16

**Describe alternatives you've considered**
Provide any datatype can fulfill Float16 model

**Comment by raymondxyang** [comment]
Hi thanks for trying our C# support. If I remember correctly we have discussed this item before in the meeting @jignparm would you mind following up this issue?

**Comment by tannergooding** [comment]
The framework side of this is being tracked by https://github.com/dotnet/corefx/issues/25702 and is being prototyped under https://github.com/dotnet/corefxlab/issues/2635.

There are also discussions to ensure that it gets the appropriate language support in C# (and potentially other languages like F#).

**Comment by linkerzhang** [comment]
ORT will also need to expose the support via C# API, @faxu for tracking it.

**Comment by jignparm** [comment]
The ORT C#  API maps several tensor native types to C# system types (e.g. Int64 -> long, see below). Currently Bloat16 is not implemented. Ideal solution is to have  Bfloat16 implemented as a new type in C# as @tannergooding mentioned above.

https://github.com/microsoft/onnxruntime/blob/master/csharp/src/Microsoft.ML.OnnxRuntime/NamedOnnxValue.cs#L327

**Comment by tannergooding** [comment]
@jignparm, do you need both `bfloat16` (Google's format) and `float16` (the IEEE half-precision format)? 

We have proposals to support both currently and will likely end up implementing both, but I just want to make sure I have it tracked correctly.

**Comment by jignparm** [comment]
The TensorProto definition contains both Float16 as well as BFloat16 (see below). We would need to support both the formats in the C# API. There are currently a handful of Float16 models in the test suite (half-precision) which cannot be scored in C#, but are fine in native C++. Is there a timeline for the proposal? There seems to be a growing interest in 16-bit models.

https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/protobuf/onnx-ml.proto#L325

    // IEEE754 half-precision floating-point format (16 bits wide).
    // This format has 1 sign bit, 5 exponent bits, and 10 mantissa bits.
    FLOAT16 = 10;

    // Non-IEEE floating-point format based on IEEE754 single-precision
    // floating-point number truncated to 16 bits.
    // This format has 1 sign bit, 8 exponent bits, and 7 mantissa bits.
    BFLOAT16 = 16;

**Comment by Voxelworld** [comment]
I observed a similar problem when using the Python API after converting my model to float16 (using the ONNX [converter script](https://github.com/onnx/onnx-docker/blob/master/onnx-ecosystem/converter_scripts/float32_float16_onnx.ipynb)):
> RuntimeError: **Numpy_type 23 can't be converted to MLDataType**.

Is this related to the C# fix or should I open a new issue?

Tested with the CPU version of the onnxruntime 0.4.0 using `pip install onnxruntime`.

**Comment by tannergooding** [comment]
> Is there a timeline for the proposal? 

I believe the current target is .NET 5, but it also depends largely on prioritization and scheduling.

**Comment by pedramrezaei** [comment]
What is the latest on this?

**Comment by tannergooding** [comment]
.NET 5 is shipping `System.Half` as an interchange type: https://devblogs.microsoft.com/dotnet/introducing-the-half-type/

This means you can parse/format strings, do basic comparison/equality checks, and convert to/from `float` and `double`. Other operations, such as addition, subtraction, and language literals aren't available.

If language support is needed, I'd recommend opening an issue on dotnet/csharplang requesting it and detailing the requirements, reasons, and scenarios.

**Comment by pedramrezaei** [comment]
Thanks. TBH, whether .NET supports float16 or not is orthogonal to the issue here. ORT supports optimizing BERT like models to use FP16. However, the library provides no obvious way of consuming these models. Also, .NET 5 is not released and not an option at this time. Can the C# ORT internally convert FP32 to an equivalent of FP16?

**Comment by yuslepukhin** [comment]
Depends on https://github.com/microsoft/onnxruntime/issues/5679

**Comment by yuslepukhin** [comment]
I am curious as to what data types people are currently using in C# to deal with Float16 and BFloat16? I will introduce a struct type into C# API and it will serve well to feed and fetch such data. However, if you use your own type, you may need to copy which is not the best thing in the world. Is it really necessary to support some arbitrary type arrays that are  size of ushort and [blittable](https://docs.microsoft.com/en-us/dotnet/framework/interop/blittable-and-non-blittable-types) so you can feed your arrays. This comes at a cost of safety since the code would have to believe you that that you are doing things correct.

**Comment by TerminaD** [comment]
Hi, after using Microsoft.ML.OnnxRuntime.Float16 for input type, the C# ORT still throws an "Unhandled exception. System.InvalidOperationException: Unsupported ONNX scalar type: Float16". Is this expected behavior? Am I doing something wrong?

```
Unhandled exception. System.InvalidOperationException: Unsupported ONNX scalar type: Float16
   at Microsoft.ML.Transforms.Onnx.OnnxTypeParser.GetScalarDataViewType(Int32 elementType)
   at Microsoft.ML.Transforms.Onnx.OnnxTypeParser.GetDataViewType(TypeProto typeProto)
   at Microsoft.ML.Transforms.Onnx.OnnxModel..ctor(IHostEnvironment env, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, Boolean ownModelFile, IDictionary`2 shapeDictionary, Int32 recursionLimit, Nullable`1 interOpNumThreads, Nullable`1 intraOpNumThreads)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, IDictionary`2 shapeDictionary, Int32 recursionLimit, Nullable`1 interOpNumThreads, Nullable`1 intraOpNumThreads)
   at Microsoft.ML.Transforms.Onnx.OnnxScoringEstimator..ctor(IHostEnvironment env, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, IDictionary`2 shapeDictionary, Int32 recursionLimit, Nullable`1 interOpNumThreads, Nullable`1 intraOpNumThreads)
   at Microsoft.ML.OnnxCatalog.ApplyOnnxModel(TransformsCatalog catalog, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu)
   at Program.Main(String[] args) in C:\Users\v-gaoxiangye\source\repos\PCMAIModels\engine\AdPopRecoginze\Program.cs:line 44
```

```
public class ModelInput
{
    public struct InputSettings
    {
        public const int imageHeight = 224;
        public const int imageWidth = 224;
        public const int textTokenLength = 52;
    }

    [ColumnName("raw_image")]
    [ImageType(InputSettings.imageHeight, InputSettings.imageWidth)]
    public MLImage Image { get; set; }

    [ColumnName("_l_text")]
    [VectorType(InputSettings.textTokenLength)]
    public long[] TextTokens { get; set; }
}

public class ModelOutput
{
    [ColumnName("classification_head_1")]
    [VectorType(1)]
    public Float16[] Logit { get; set; }
}

public class Program
{
    public static void Main(string[] args)
    {
        string imageFolderPath = Path.GetFullPath(@"Assets\Images");
        string onnxModelPath = Path.GetFullPath(@"Assets\ONNXModel\test_fp16_dynamo_2.onnx");
        string tokenizerPath = Path.GetFullPath(@"Assets\Tokenizer\tokenizer.json");

        var watch = System.Diagnostics.Stopwatch.StartNew();
        var context = new MLContext();
        var pipeline =
            context.Transforms.ResizeImages(
                inputColumnName: "raw_image",
                outputColumnName: "resized_image",
                resizing: ImageResizingEstimator.ResizingKind.IsoPad,
                imageWidth: ModelInput.InputSettings.imageWidth,
                imageHeight: ModelInput.InputSettings.imageHeight)
            .Append(context.Transforms.ExtractPixels(
                inputColumnName: "resized_image",
                outputColumnName: "r_channel",
                colorsToExtract: ImagePixelExtractingEstimator.ColorBits.Red,
                offsetImage: (float)(-0.48145466 * 256),
                scaleImage: (float)(1 / 0.26862954)))
            .Append(context.Transforms.ExtractPixels(
                inputColumnName: "resized_image",
                outputColumnName: "g_channel",
                colorsToExtract: ImagePixelExtractingEstimator.ColorBits.Green,
                offsetImage: (float)(-0.4578275 * 256),
                scaleImage: (float)(1 / 0.26130258)))
            .Append(context.Transforms.ExtractPixels(
                inputColumnName: "resized_image",
                outputColumnName: "b_channel",
                colorsToExtract: ImagePixelExtractingEstimator.ColorBits.Blue,
                offsetImage: (float)(-0.40821073 * 256),
                scaleImage: (float)(1 / 0.27577711)))
            .Append(context.Transforms.Concatenate(
                inputColumnNames: new[] { "r_channel", "g_channel", "b_channel" },
                outputColumnName: "_l_image"))
            .Append(context.Transforms.ApplyOnnxModel(
                inputColumnNames: new string[] { "_l_image", "_l_text" },
                outputColumnNames: new string[] { "classification_head_1" },
                modelFile: onnxModelPath));
        var model = pipeline.Fit(context.Data.LoadFromEnumerable(new List<ModelInput>()));
        var predictionEngine = context.Model.CreatePredictionEngine<ModelInput, ModelOutput>(model);
```
