### ISSUE TITLE
Expose option to strictly enforce shape and type correctness

### ISSUE THREAD

**Issue by garymm** [microsoft/onnxruntime#9506]
#2199 made it so that shape and type errors (e.g. mismatches between the shape of an output as stated in in the ONNX graph and what is inferred) are not fatal UNLESS the model is using the latest opset version. This allowed a bug in the PyTorch-ONNX exporter to go unnoticed for several months (see https://github.com/pytorch/pytorch/pull/67121/commits/79e8bf58bb0e0ca690880fbd40a80ebd69040e2b).

Thus I'm requesting an API to explicitly request strict enforcement of correctness, regardless of opset version.

CC @BowenBao @skottmckay @gramalingam 

[AB#1681837](https://msdata.visualstudio.com/3adb301f-9ede-41f2-933b-fcd1a486ff7f/_workitems/edit/1681837)

**Comment by skottmckay** [comment]
Added task to backlog.

**Comment by snnn** [comment]
I  have the same concern. Even though ORT test ONNX  shape inference functions with every old ONNX opset, due to https://github.com/microsoft/onnxruntime/pull/2199 we can't notice such errors.  And when an shape inference error was thrown, I believe type inference is also interrupted. Then the model is useless, we can't run it.  So it's better to not ignore such errors. If there was something wrong, let's fix it. The ONNX community knows ORT is important, they valid their code with ORT before doing a release . This time it was handled by Liqun. So it's better to let it fail earlier.

**Comment by garymm** [comment]
@scottmckay would you approve a PR that makes strict enforcement the default, but lets people turn it off if they want? If not, what would you suggest instead?

**Comment by skottmckay** [comment]
Making strict the default with an option to disable would be nice, but if you do that you potentially break existing production scenarios if they upgrade ORT, until they discover they need to set a new value for their model for it to work again.  

I believe this was what happened when I added the strict check originally. To try and balance that we went with strict checking of the latest opset (we should be implementing kernels and tests for the new opset so should discover ONNX shape inferencing issues during that process). 

Do users care if we fall back to the lenient merge? I don't know if they'd even notice this happening, so it could be that scenarios where strict checking is required are the minority, and it would be safer to keep the existing setup but add a SessionOptions config param to manually set strict mode to on.

**Comment by garymm** [comment]
@scottmckay as a user I would be OK if things break with an easy fix that's noted in the release notes. Would you be OK with a PR that does that?

If that's not acceptable, a session option to enable strict mode would be OK for the use case that originally prompted this bug. Would you approve a PR that does that?

**Comment by skottmckay** [comment]
@pranavsharma what are your thoughts? 

I'd definitely prefer to avoid breaking a working production scenario and forcing the user to find an additional configuration option in the release notes (which I'm sure they study in great depth :P) to fix it. 

e.g. we have 1P users running online services that load many different models at random times. This breaking behavior may not be triggered in their release testing, so we'd potential create a livesite when ORT starts intermittently crashing when executing models that previously worked fine. That's time to diagnose, time to mitigate, time to resolve, and if you're unlucky that's at 2am in the morning for the DRI.  

I'm much more comfortable with the current behavior being preserved and a user being able to explicitly turn on strict mode for the session.

**Comment by pranavsharma** [comment]
+1 to what Scott said. We've a pretty large deployment base now. We simply cannot afford a livesite esp. in revenue impacting online services. Breaking existing scenarios is not acceptable. I strongly suggest adding an option to enforce strict checking. This will have zero impact on our existing users while allowing us to enforce the check in our tests to uncover any hidden exporter issues such as the one you identified or elsewhere.

**Comment by snnn** [comment]
Scott's last change works because we **usually** put type inference in the first line of a type/shape inference function.  Otherwise, if an exception was thrown before the type inference is done, the behavior is undefined.  I think this is quite general: if you throw an exception when you modifies a graph, you can't expect the exception is recoverable.  Even the change is local to just one node.

**Comment by garymm** [comment]
I spent some time looking at this and could use some advice.
It seems like this might make sense as a `Graph` `ResolveOption`:
https://github.com/microsoft/onnxruntime/blob/2679711bee9717f8ab77e20c163ddf2fe3a3f48d/include/onnxruntime/core/graph/graph.h#L1227

However to get something from `SessionOptions` to the first call to `Resolve` seems tricky.
Is it intentional that `Model::Model()` does not call `graph_->Resolve()` immediately after constructing it?
E.g., here:
https://github.com/microsoft/onnxruntime/blob/ec4362f8f326e076498ad2fde1aa44929b586f25/onnxruntime/core/graph/model.cc#L99

If we could call `graph_->Resolve()` there (and in the other constructor), then I propose:
1. Add new bool to `SessionOptions`.
2. Pass bool into `Model::Load()` calls from `inference_session.cc`.
3. Pass bool into `Model::Model()`.
4. Pass bool into `Graph::Resolve()` (via `ResolveOptions`).

If that is not acceptable, then another option would be to add the bool to `Graph::Graph()` constructor and have it save a member variable for use during `Resolve()`.

(I tried setting it only [here](https://github.com/microsoft/onnxruntime/blob/d1b2fb15addaa369660d617c6d39595c00e2a963/onnxruntime/core/session/inference_session.cc#L1396) since that was minimally invasive, but it seems that Resolve() is often a no-op because the Graph has already been resolved)

@skottmckay please advise.

**Comment by garymm** [comment]
@pranavsharma could you assign someone who could help advise me on this? See detailed questions above.

**Comment by skottmckay** [comment]
Would this be similar in expected usage to setting the environment variable to allow un-released ONNX opsets to be used? i.e. expert user/developer and not something a typical user would care about.

If so, would using an environment variable like we do here be an viable approach? 

https://github.com/microsoft/onnxruntime/blob/4a5b5328a46d1a5a869a7cbeadd821fdddc70137/onnxruntime/core/graph/model_load_utils.h#L19-L38

**Comment by pranavsharma** [comment]
The use of env variable for unreleased opsets was a bit special since we wanted to accommodate inflight changes in ONNX. If this functionality is going to be used only in your tests the usage of env variable is probably ok, but I would be a bit careful and rather suggest using a session option (at the cost of some plumbing between inference session and graph) because env variables are difficult to see when using the ORT API which can make debugging tricky. Having a single point of entry for ORT configs makes it easier to look in one place.

**Comment by garymm** [comment]
I personally agree that env variable is not as nice. It's essentially a global variable that goes around the layers of code in a way that is hard to trace.
But I will be happy to implement this however the code owners here prefer, please just tell me what to do :-)
If we're not going with an env variable, please see my detailed questions above.

@pranavsharma @skottmckay

**Comment by pranavsharma** [comment]
The determination to use strict mode or not is made using using_latest_onnx_opset_ when calling MergeShapeInfo ([here](https://github.com/microsoft/onnxruntime/blob/f468ea40e59c6f3d7ca06c3d0c0b6d325c185602/onnxruntime/core/graph/graph.cc#L2368
)). So, you could store this new override option in Graph as another member (enforce_strict_shape_type_inferencing_) and then call ```MergeShapeInfo(..., enforce_strict_shape_type_inferencing_|using_latest_onnx_opset_, ...)```. The default value of enforce_strict_shape_type_inferencing_  should obviously be false.

**Comment by yuanbyu** [comment]
I think that we should minimize the use of env variables as much as possible.

**Comment by garymm** [comment]
@pranavsharma to be clear I'd add the bool to the `Graph::Graph()` constructor and have it save a member variable for use later, right? I think there are a lot of overloads of the constructor so this will be a bit of a larger change in practice than it sounds like but I'm happy to do it that way.

If not that, can you please clarify how the bool would get from SessionOptions to the call to `MergeShapeInfo` ?

**Comment by pranavsharma** [comment]
> @pranavsharma to be clear I'd add the bool to the `Graph::Graph()` constructor and have it save a member variable for use later, right? I think there are a lot of overloads of the constructor so this will be a bit of a larger change in practice than it sounds like but I'm happy to do it that way.

There are only 3 Graph ctors where 2 of them delegate the call to the third. I can't think of any other way of plumbing the session option to the Graph class.

**Comment by garymm** [comment]
@pranavsharma sorry I guess it's the `Model` class that has a bunch of constructors and a bunch of Load functions, and the Model class is responsible for constructing the `Graph`. In any case I'll give it a shot.
