### ISSUE TITLE
Docker files are just wrong

### ISSUE THREAD

**Issue by dselivanov** [microsoft/onnxruntime#956]
This is very strange to see totally incorrect and untested docker files in the master branch.

### GPU

onnxruntime clearly states in depends on CUDA 9.1, but gpu images starts from 10.0 - https://github.com/Microsoft/onnxruntime/blob/628f4c3aa3bb03fb62fd580a897ec8b6de32e430/dockerfiles/Dockerfile.gpu#L9

On top of that it is based on ubuntu 16.04 and the most modern python from apt is 3.5. However docker installs `python 3.6` (mind space!!!)
https://github.com/Microsoft/onnxruntime/blob/628f4c3aa3bb03fb62fd580a897ec8b6de32e430/dockerfiles/Dockerfile.cpu#L17

And also installs unnecessary things like openssl, wget, etc.

It looks like this docker files are copy-paste from somewhere and even not tested to build. 

### CPU 
Same issues with CPU dockerfile

**Comment by snnn** [comment]
It's not wrong. At source code level,  onnxruntime supports multiple python versions and multiple cuda versions.

**Comment by snnn** [comment]
Sounds reasonable.

**Comment by vinitra** [comment]
Thank you for your feedback on the older versions of the dockerfiles, @dselivanov. I removed them in #987 and will address the suggested changes in a future PR!
