### ISSUE TITLE
Tokenizer fails if separators include special characters for regular expression

### ISSUE THREAD

**Issue by xadupre** [microsoft/onnxruntime#957]
**Describe the bug**
Last change changed the behaviour of the tokenizer by using regular expression when separators are used to split into words. The code fails if separators such '?', '.' are used. See 
https://github.com/Microsoft/onnxruntime/blob/master/onnxruntime/contrib_ops/cpu/tokenizer.cc#L99.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): all
- ONNX Runtime installed from (source or binary): github / master
- ONNX Runtime version: github / master
- Python version: 3.7

**To Reproduce**
Describe steps/code to reproduce the behavior: add a unit test similar to this one https://github.com/Microsoft/onnxruntime/blob/master/onnxruntime/test/contrib_ops/tokenizer_test.cc#L322 to check separators = special characters into regular expression

**Expected behavior**
Either a change to allow ?, either a change in the documentation to tell it is not supported

**Additional context**
The task is to split into sentances (with separators like . ? !)

**Comment by yuslepukhin** [comment]
@xadupre The documentation now states that separators are now regex. Therefore, if you want to use one of the regex special characters, they must be escaped. I can add this sentence to the doc. Would that work?

**Comment by xadupre** [comment]
That should work. I need to confirm. My first try doing that was not successful. I should try again.

**Comment by yuslepukhin** [comment]
@xadupre have had a chance to try escaping those characters?

**Comment by faxu** [comment]
@xadupre : any update on this?

**Comment by xadupre** [comment]
Yes, I checked. It works.
