### ISSUE TITLE
Quantizing DistilBERT models after optimizing with ORT leads to invalid node input names

### ISSUE THREAD

**Issue by mfuntowicz** [microsoft/onnxruntime#9573]
When trying to quantize DistilBERT model (ex: ) the EmbedLayerNormalization operator seems to generate some empty (`""`) input names as it can be seen on the Figure 1.

Then subsequent calls to `QuantizeHelper.quantize_onnx_model(...)` raises an Exception because some quantized inputs have invalid names: 

`embed_layernorm.py: L31`: 

```python
(quantized_input_names, zero_point_names, scale_names, nodes) = \
            self.quantizer.quantize_inputs(node, [2, 3, 4, 5, 6])
```

In this case node [4] input's name is set to "" which seems invalid: 

```python
ValueError: Invalid tensor name to quantize:  @graph scope/
````

BERT models seem not affected, see Figure 2.

=> **The issue seems to originate from the fact DistilBERT doesn't have `segment_ids`, `segment_embeds` parameter(s), would a potential fix be to filter out these input names from the set of inputs to be quantized?** 
=> If so, I'm happy to submit a PR for this one.

**Figure 1.**
![image](https://user-images.githubusercontent.com/2241520/139063614-c1a5f221-74e1-4865-b2f9-0c5d8eb839f8.png)

**Figure 2.**
![image](https://user-images.githubusercontent.com/2241520/139063635-055db5ad-64b9-455d-b04f-a0d256517d5f.png)

**Comment by mfuntowicz** [comment]
@tianleiwu I just tested with a fresh build from master branch and the problem seems already fixed by this PR: https://github.com/microsoft/onnxruntime/pull/9336

Especially the [following code](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/operators/embed_layernorm.py#L21): 

```python
if len(node.output) > 2:
    logging.info(f"Quantization is not applied to {node.name} since it has 3 outputs")
    return super().quantize()
```

Still, this doesn't really cover the initial "issue", but it prevents it from crashing. 

Should we close this ticket and stay like this for now? I'm happy to submit a PR if I spot a edge case not covered by the above lines.

**Comment by trajepl** [comment]
Met the same issues in onnxruntime==1.13.1. Failed to quantize distillery bert models after transformer optimizations.
