### ISSUE TITLE
Handling Ort::IoBinding for DirectML EP (C++)?

### ISSUE THREAD

**Issue by simonbunge** [microsoft/onnxruntime#9584]
Sorry, this is another request for information/ guidance rather than a genuine issue as such.
Any pointers to existing documentation (which I did look for but couldn't find) much appreciated.

The use case this pertains to is retaining recurrent model state in GPU memory, i.e. avoiding unnecessary back and forth copying.

For the CUDA EP, this looks roughly like this (not fully tested, so don't judge the quality/ treat as pseudo-code):

```cpp

(...)	
tf->session.reset(new Ort::Session(*tf->env, tf->model_filepath, session_options));
tf->memory_info_gpu = Ort::MemoryInfo("Cuda", OrtAllocatorType::OrtArenaAllocator, 0, OrtMemTypeDefault);
Ort::Allocator cuda_allocator(*(tf->session.get()), tf->memory_info_gpu);
tf->binding = Ort::IoBinding(*(tf->session.get()));

tf->binding.BindOutput("r1o", tf->memory_info_gpu);

const std::array<int64_t, 4> r1i_shape = {1, 1, 1, 1};
std::array<float, 4> r1i_values = {0.0f, 0.0f, 0.0f, 0.0f};
auto r1i_data = std::unique_ptr<void, CudaMemoryDeleter>(cuda_allocator.Alloc(r1i_values.size() * sizeof(float)), CudaMemoryDeleter(&cuda_allocator));
cudaMemcpy(r1i_data.get(), r1i_values.data(), sizeof(float) * r1i_values.size(), cudaMemcpyHostToDevice);
tf->bound_r1i = Ort::Value::CreateTensor(tf->memory_info_gpu, reinterpret_cast<float*>(r1i_data.get()), r1i_values.size(), r1i_shape.data(), r1i_shape.size(), ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT);
(...)
tf->binding.BindInput("r1i", tf->bound_r1i);
std::vector<Ort::Value> output_values = tf->binding.GetOutputValues();
tf->bound_r1i = std::move(output_values[2]);
(...)
```

What would the functional equivalent to bind to GPU look like for the DirectML EP?

Many thanks!

**Comment by pranavsharma** [comment]
As can be seen [here](https://github.com/microsoft/onnxruntime/commit/89618e8f1e8fee0354de57494bb71da96a445b71), CreateMemoryInfo doesn't support DML EP today, but if you know the shape of the output a priori and can allocate memory for it using the appropriate device allocator, you don't need it (memory info). We've had one other ask to support this in DML EP, so marking this as an enhancement.
cc @fdwr

**Comment by fdwr** [comment]
@simonbunge Coincidentally we are currently evaluating how to expose this in the API for other customers too. No need to apologize for information requests! Stay tuned...

**Comment by simonbunge** [comment]
> As can be seen [here](https://github.com/microsoft/onnxruntime/blob/3360024a0b2a55a9093ef477b097e4bbaa612cb5/onnxruntime/core/framework/allocator.cc#L58-L74), CreateMemoryInfo doesn't support DML EP today, but if you know the shape of the output a priori and can allocate memory for it using the appropriate device allocator, you don't need it (memory info). We've had one other ask to support this in DML EP, so marking this as an enhancement. cc @fdwr

Thanks, @pranavsharma! Assuming I can pre-determine the dimensions (tricky for my application, but probably doable): can you give me a hint how the allocation would work for the DML EP? As in: a code snippet that shows how to (without using CreateTensor() whose overloads would all seem to require a MemoryInfo) create a Value that I can feed to BindInput()/ BindOutput()?

**Comment by fdwr** [comment]
@simonbunge FYI the pending PR is here: https://github.com/microsoft/onnxruntime/pull/9686

**Comment by fdwr** [comment]
@simonbunge (clearing up old issues) For https://github.com/microsoft/onnxruntime/issues/10279, I shared a standalone sanity test app [here (main.cpp)](https://github.com/microsoft/onnxruntime/files/7917063/main.txt). Does that help?

**Comment by nums11** [comment]
Closing as resolved.

**Comment by fdwr** [comment]
@nums11 Would you share your IoBinding sample here, in case others come across this issue later?

**Comment by nums11** [comment]
Sure. The sample can be found [here](https://github.com/microsoft/Windows-Machine-Learning/tree/master/Samples/WinMLSamplesGallery/WinMLSamplesGallery/Samples/DXResourceBindingORT)
