### ISSUE TITLE
onnxruntime-react-native can't load model

### ISSUE THREAD

**Issue by DRSY** [microsoft/onnxruntime#9594]
**Describe the bug**
I have a pretrained Pytorch model and I exported it ONNX format. I have checked the validity of the exported onnx model file using onnxruntime on a Ubuntu server. When I tried to run it using onnxruntime-react-native I got an error saying "Can't load model No content provider: xxx.onnx", where xxx is the name of my model.

Any reason why this happened?
Thanks!

**System information**
- Pytorch version: 1.7.1
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary): npm/yarn
- ONNX Runtime version: 1.8.1
- react-native version: 0.66.1

**Comment by JonathanSum** [comment]
![image](https://user-images.githubusercontent.com/21982975/159850833-2a6d72cb-f323-4ca7-bea5-e64b26c694fb.png)

**Comment by JonathanSum** [comment]
I say it just can not load the model.

**Comment by faxu** [comment]
Here is the correct link: https://onnxruntime.ai/docs/reference/ort-format-models.html#convert-onnx-models-to-ort-format

You will need .ort models for this, which is why it cannot load the .onnx model

**Comment by JonathanSum** [comment]
@faxu I think the main issue is you can't load the model or even do inference as the ONNXJS. But the NPM doc "kind of" showed the ONNXJS way, which is most leading. Look!![Screenshot_20220411-210304.jpg](https://user-images.githubusercontent.com/21982975/162880698-49a9eb54-9d2e-4a3c-a5e7-5ed190eca626.jpg)

**Comment by guschmue** [comment]
I think this should be fixed.
