### ISSUE TITLE
wrong num_quantized_bins & num_bins

### ISSUE THREAD

**Issue by tianylijun** [microsoft/onnxruntime#9597]
file: onnxruntime/onnxruntime/python/tools/quantization/calibrate.py

def __init__(self, num_quantized_bins=128):    <-------------- here 128 shoud be 8001 same as mxnet
        self.histogram_dict = {}
        self.num_quantized_bins= num_quantized_bins   <-------------- here 128

    def get_histogram_dict(self):
        return self.histogram_dict

    def collect(self, name_to_arr):
        for tensor, data_arr in name_to_arr.items():
            data_arr = np.asarray(data_arr)
            data_arr = data_arr.flatten()

            if data_arr.size > 0:
                min_value = np.min(data_arr)
                max_value = np.max(data_arr)
            else:
                min_value = 0
                max_value = 0

            threshold = max(abs(min_value), abs(max_value))

            if tensor in self.histogram_dict:
                old_histogram = self.histogram_dict[tensor]
                self.histogram_dict[tensor] = self.merge_histogram(old_histogram, data_arr, min_value, max_value, threshold)
            else:
                # hist, hist_edges = np.histogram(data_arr, self.num_quantized_bins, range=(min_value, max_value))
                hist, hist_edges = np.histogram(data_arr, self.num_quantized_bins, range=(-threshold, threshold))   <-------------- here 128
                self.histogram_dict[tensor] = (hist, hist_edges, min_value, max_value, threshold)

def get_optimal_collection_result(self):
        histogram_dict = self.histogram_dict
        num_quantized_bins = self.num_quantized_bins <-------------- here 128

        thresholds_dict = {} # per tensor thresholds

        for tensor, histogram in histogram_dict.items():
            optimal_threshold = self.get_optimal_threshold(histogram, num_quantized_bins) <-------------- here 128
            thresholds_dict[tensor] = optimal_threshold

        return thresholds_dict

    def get_optimal_threshold(self, histogram, num_quantized_bins): <-------------- here 128
        from scipy.stats import entropy
        import copy

        hist, hist_edges, _, _, _ = histogram
        num_bins = hist.size                        <-------------- here 128
        zero_bin_index = num_bins // 2       <-------------- here 64
        num_half_quantized_bin = num_quantized_bins // 2   <-------------- here 64
        
        kl_divergence = np.zeros(zero_bin_index - num_half_quantized_bin + 1)
        thresholds = [(0, 0) for i in range(kl_divergence.size)] 

        for i in range(num_half_quantized_bin, zero_bin_index + 1, 1): <--------------  here (64,64)  wrong range !!!!!
            start_index = zero_bin_index - i 
            end_index = zero_bin_index + i + 1 if (zero_bin_index + i + 1) <= num_bins else num_bins

**Comment by chilo-ms** [comment]
Thanks for bringing out this issue. We will inspect it.

**Comment by chilo-ms** [comment]
> do kl_divergence quant scale can work? i get big drop of acc

Yes, it can work.

Please note that the [code](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/calibrate.py#L570) `num_bins = hist.size`  is not always 128 even though we explicitly set num_quantized_bins to 128.
The reason is that the range of tensor value's histogram might expand during histogram merging ([here](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/quantization/calibrate.py#L514)) which depends on the tensor value data the collector collects.
However, we will make num_bins and num_quantized_bins configurable in another PR and you can set different num_bins and num_quantized_bins to see whether it can achieve better accuracy.

**Comment by chilo-ms** [comment]
The PR https://github.com/microsoft/onnxruntime/pull/10204 now can make 'num_bins', 'num_quantized_bin' and 'percentile' configurable
