### ISSUE TITLE
Get nan as output 

### ISSUE THREAD

**Issue by kli017** [microsoft/onnxruntime#9629]
**Describe the bug**
Hello there,
I was implementing an conformer encoder onnx model, and it need 5 inputs. I printed and checked my input and found no problem with them. I tried both onnxruntime 1.8.2 and 1.9.0 and get nan as output. The weird things is on anther develop env and with the same model I can get correct outputs.  

**System information**
- OS Platform and Distribution: Linux Ubuntu 18.04:
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.8.2 and 1.9.0
- GCC/Compiler version (if compiling from source): CMake 3.14.0

**Comment by kli017** [comment]
[encoder_result.txt](https://github.com/microsoft/onnxruntime/files/7448453/encoder_result.txt)
The result is like this

**Comment by kli017** [comment]
I was wondering if the CUDA enviroment affect the output? Because one env is a pure ubuntu18.04 docker and the other one is NVIDIA-ubuntu18.04. Anyone met this problme before?

**Comment by kli017** [comment]
attached the model

**Comment by skottmckay** [comment]
Hard to investigate without the model and the input you're using. Are you able to share those? 

The CUDA EP will execute things differently to the CPU EP, so the usage of CUDA would definitely be a factor. Is it execution with CUDA that returns NaN?

What framework was the model created in (e.g. pytorch, tensorflow)? What results do you get from executing the model using that framework?

**Comment by kli017** [comment]
The model is from pytorch. It is an model for ASR and the input is Fbank features and cache features. The original model worked well, I transfered my own model from this link [https://github.com/Mashiro009/wenet-onnx](url).  The comment dont allowed me upload the model, Is there good way to share to you?

**Comment by skottmckay** [comment]
Can you share the model via something like OneDrive? I don't see any onnx models on https://github.com/Mashiro009/wenet-onnx

For input it would be best if you can provide the actual input data that was used when you saw the error.

**Comment by kli017** [comment]
@skottmckay what is your email address? I can share it by google drive.

**Comment by kli017** [comment]
Finally found the problem in my code. none business with the model. Thanks!

**Comment by kli017** [comment]
Hello，I reason of nan output is that two of my input are not initialized properly.  The inputs include feats, offset, samplecache, elayercache and cnncache five parts. To start the 3 cache parts should be initialzed with 0. I found the initial results are different while I slightly change the code.
`Ort::Value OnnxAsrDecoder::InitNullCache(const std::vector<int64_t>& cache_dims) {
  int cache_len = 1;
  for (const auto& cache_dim: cache_dims) {
    cache_len *= cache_dim;
  }

  std::vector<float> cache(cache_len, 0.0f);
  auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
  Ort::Value cache_onnx = Ort::Value::CreateTensor<float>(memory_info,
                                                          cache.data(),
                                                          cache.size(),
                                                          cache_dims.data(),
                                                          cache_dims.size());
  return cache_onnx;
}
`
`Ort::Value OnnxAsrDecoder::init_null_cache(const std::vector<int64_t>& cache_dims, std::vector<float>& cache) {
  int cache_count = 1;
  for (const auto& cache_dim: cache_dims) {
    cache_count *= cache_dim;
  }
  // std::vector<float> cache(cache_count);
  cache.clear();
  cache.resize(cache_count);
  for (int i = 0; i < cache_count; ++i) {
    cache[i] = 0.0f;
  }
  auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
  Ort::Value cache_onnx = Ort::Value::CreateTensor<float>(memory_info,
                                                          cache.data(),
                                                          cache.size(),
                                                          cache_dims.data(),
                                                          cache_dims.size());
  return cache_onnx;
}`

Using the first func I found the Ort::Value are not zero. But the second func is ok. I think the result of vector should be same in those two function, cannot figure out why the Ort::Value are different?

**Comment by skottmckay** [comment]
Ort::Value::CreateTensor does NOT copy the data, so in the first func the data storage from the `cache` vector goes out of scope and is freed, leaving the cache_onnx value pointing to invalid memory. 

[CreateTensor](https://onnxruntime.ai/docs/api/c/struct_ort_1_1_value.html#a3898146b5fc35b838bd48db807dd6c8e) wraps [CreateTensorWithDataAsOrtValue](https://onnxruntime.ai/docs/api/c/struct_ort_api.html#a2aad3ccd68c66d0b38bdb966467d9324) which says 

>Create a tensor with user's buffer. You can fill the buffer either before calling this function or after. **p_data is owned by caller**. ReleaseValue won't release p_data.
