### ISSUE TITLE
Is is possible to develop custom c++ op (with cuda support) without building onnxruntime?

### ISSUE THREAD

**Issue by luchangli03** [microsoft/onnxruntime#9636]
Is is possible to develop custom c++ op (with cuda support) without building onnxruntime, just like developing the custom op for TensorFlow that we only need to include header files and link the libtensorflow_framework.so ?

I have tried to use the code ./onnxruntime/onnxruntime/test/testdata/custom_op_library/custom_op_library.cc to build custom op so，I included headers in onnxruntime code repo and linked .so in pip installed  onnxruntime, but failed (version: onnxruntime v1.6.0).

**Comment by thiagocrepaldi** [comment]
Probably not as the publicly available packages are *not* built with `--enable_external_custom_op_schemas` by default.

@satyajandhyala and I discussed this a couple times and we should probably enable this by default soon

**Comment by snnn** [comment]
Is it for ORT training or inferencing?

**Comment by thiagocrepaldi** [comment]
> Is it for ORT training or inferencing?

good point. my answer was related to training, only

**Comment by luchangli03** [comment]
> > Is it for ORT training or inferencing?
> 
> good point. my answer was related to training, only

Why training or inferencing matters?

**Comment by pranavsharma** [comment]
> Is is possible to develop custom c++ op (with cuda support) without building onnxruntime, just like developing the custom op for TensorFlow that we only need to include header files and link the libtensorflow_framework.so ?

Yes for inferencing. See https://onnxruntime.ai/docs/reference/operators/add-custom-op.html#cuda-custom-ops

**Comment by luchangli03** [comment]
@pranavsharma  Thank you, I will try it.

**Comment by snnn** [comment]
> Why training or inferencing matters?

To find the best person to answer your question.  I wonder if you were asking something about ORT training module.
