### ISSUE TITLE
set devices_id

### ISSUE THREAD

**Issue by cqray1990** [microsoft/onnxruntime#9645]
**Describe the bug**
A clear and concise description of what the bug is. To avoid repetition please make sure this is not one of the known issues mentioned on the respective release page.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- ONNX Runtime installed from (source or binary):
- ONNX Runtime version:1.6
- Python version:2.6
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.2/8.0
- GPU model and memory:

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

when set gpu id with 

self.sess.set_providers(['CUDAExecutionProvider'], provider_options=[{'device_id': 0}])

but deviced_id 1  used, did the onnxruntime can select one gpu as we want to execute code?

**Comment by pranavsharma** [comment]
This is simply not possible. Please run ```nvidia-smi``` and see which process is using device 0 and 1.

**Comment by cqray1990** [comment]
![541499651](https://user-images.githubusercontent.com/32585434/139816599-1a85dd12-f5bd-4b77-bc56-7784b425e72b.jpg)
![1117368157](https://user-images.githubusercontent.com/32585434/139816621-386452b0-d646-4a95-9dcd-fdaed29f7773.jpg)

the tow pic shows １ card and 0 card,and  when set device_id =1  two process run of python3.6  and when set device_id=0,one process run

**Comment by cqray1990** [comment]
@ pranavsharma

**Comment by cqray1990** [comment]
it is really wired,i test serval models set device_id=1,two process run of python3.6

**Comment by cqray1990** [comment]
maybe it is a bug

**Comment by cqray1990** [comment]
@pranavsharma @mattetti @mtodd @sverrejoh help me please, thank u

**Comment by pranavsharma** [comment]
We've never heard from anyone where the device id specified by the user was not honored.

* Can you verify before starting inferencing using ORT there's nothing running on the GPUs?
* The 2 processes shown in the first fig have the same PID. So, they aren't 2 separate processes.
* Are you creating 2 separate sessions each corresponding to a separate device? If so, are they created in separate Python files and invoked?
* Can you try setting the device id [this way](https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#python) and see if it works for you? This is to rule out any unknown bugs with the set_providers API.

**Comment by cqray1990** [comment]
here is my code and model can you test it?
===================
import onnxruntime as ort
from PIL import Image
import numpy as np
import cv2
class AngleProcesss:
    def __init__(self,model_path,size_h = 32,size_w = 192):
        self.sess = ort.InferenceSession(model_path)
        self.sess.set_providers(['CUDAExecutionProvider'],  provider_options=[{'device_id': 1,'gpu_mem_limit':2 * 1024 * 1024 * 1024}])
        print("AngleProcesss:", self.sess.get_providers(), "\n", self.sess.get_provider_options(), "\n",
              self.sess.get_session_options())
        self._size_h = size_h
        self._size_w = size_w


    def infer(self,im):
        scale = im.size[1] * 1.0 / self._size_h
        w = im.size[0] / scale
        w = int(w)
        img = im.resize((w, self._size_h), Image.BILINEAR)

        if w < self._size_w:
            imgnew = Image.new('RGB', (self._size_w, self._size_h), (255))
            imgnew.paste(img, (0, 0, w, self._size_h))
        else:
            imgnew = img.crop((0, 0, self._size_w, self._size_h))

        img = np.array(imgnew, dtype=np.float32)

        img -= 127.5
        img /= 127.5
        image = img.transpose(2, 0, 1)
        transformed_image = np.expand_dims(image, axis=0)

        preds = self.sess.run(["out"], {"input": transformed_image.astype(np.float32)})

        pred = np.argmax(preds[0])

        return pred

    def infer_rbgs(self, imgs):
        nlen = len(imgs)
        res_sum = sum([self.infer(im) for im in imgs])
        return res_sum < nlen // 
if __name__=="__main__":
    _AngleMoel = AngleProcesss('./angle_net.onnx')
    img = Image.open("./1297885964.jpg")

    for i in range(10000):
        _AngleMoel.infer(img)

**Comment by cqray1990** [comment]
@pranavsharma

**Comment by pranavsharma** [comment]
> @pranavsharma can i build the latest code in master branch with cuda 11.2 or any cuda version,and get .whl files then install it by myself

yes, you can. Use --build_wheel option to build the wheel file.

**Comment by pranavsharma** [comment]
I tried your code and I can't reproduce the issue. I choose device id 1 and inferencing runs on the device specified.

![image](https://user-images.githubusercontent.com/2732907/140021063-40bd4e26-e99b-442c-b48d-f6c1e98363d1.png)

![image](https://user-images.githubusercontent.com/2732907/140021097-03dd0907-6ce9-49f1-9492-2e89940044e9.png)

**Comment by cqray1990** [comment]
did you  try onnxruntime_gpu 1.6.0? i meet this in that veersion

**Comment by pranavsharma** [comment]
Yes, just tried with 1.6.0 as well. 

```
(pranav_py8) pranav@OrtTrainingDev3:~$ LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64/ python issue_9645.py
version:  1.6.0
process id:  13009
```

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA Tesla V1...  Off  | 00000001:00:00.0 Off |                    0 |
| N/A   31C    P0    35W / 250W |    497MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA Tesla V1...  Off  | 00000002:00:00.0 Off |                    0 |
| N/A   30C    P0    40W / 250W |    657MiB / 16160MiB |     48%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA Tesla V1...  Off  | 00000003:00:00.0 Off |                    0 |
| N/A   29C    P0    26W / 250W |      4MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA Tesla V1...  Off  | 00000004:00:00.0 Off |                    0 |
| N/A   29C    P0    24W / 250W |      4MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     13009      C   python                            493MiB |
|    1   N/A  N/A     13009      C   python                            653MiB |
+-----------------------------------------------------------------------------+
```

**Comment by jewelc92** [comment]
> Yes, just tried with 1.6.0 as well.
> 
> ```
> (pranav_py8) pranav@OrtTrainingDev3:~$ cat issue_9645.py
> import onnxruntime as ort
> from PIL import Image
> import numpy as np
> import cv2
> import os
> 
> class AngleProcesss:
>     def __init__(self,model_path,size_h = 32,size_w = 192):
>         # print("here..")
>         self.sess = ort.InferenceSession(model_path)
>         self.sess.set_providers(['CUDAExecutionProvider'],  provider_options=[{'device_id': 1,'gpu_mem_limit':2 * 1024 * 1024 * 1024}])
> 
>         self._size_h = size_h
>         self._size_w = size_w
> 
> 
>     def infer(self,im):
>         scale = im.size[1] * 1.0 / self._size_h
>         w = im.size[0] / scale
>         w = int(w)
>         img = im.resize((w, self._size_h), Image.BILINEAR)
> 
>         if w < self._size_w:
>             imgnew = Image.new('RGB', (self._size_w, self._size_h), (255))
>             imgnew.paste(img, (0, 0, w, self._size_h))
>         else:
>             imgnew = img.crop((0, 0, self._size_w, self._size_h))
> 
>         img = np.array(imgnew, dtype=np.float32)
> 
>         img -= 127.5
>         img /= 127.5
>         image = img.transpose(2, 0, 1)
>         transformed_image = np.expand_dims(image, axis=0)
>         # print("calling run")
>         preds = self.sess.run(["out"], {"input": transformed_image.astype(np.float32)})
>         pred = np.argmax(preds[0])
>         # print("done with one run")
>         return pred
> 
>     def infer_rbgs(self, imgs):
>         nlen = len(imgs)
>         res_sum = sum([self.infer(im) for im in imgs])
>         return res_sum < nlen // 2
> 
> if __name__== "__main__":
>     print("version: ", ort.__version__)
>     print("process id: ", os.getpid())
>     _AngleMoel = AngleProcesss('./angle_net.onnx')
>     img = Image.open("./Sample-jpg-image-50kb.jpg")
>     for i in range(10000):
>         _AngleMoel.infer(img)
> ```
> 
> ```
> (pranav_py8) pranav@OrtTrainingDev3:~$ LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64/ python issue_9645.py
> version:  1.6.0
> process id:  13009
> ```
> 
> ```
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  NVIDIA Tesla V1...  Off  | 00000001:00:00.0 Off |                    0 |
> | N/A   31C    P0    35W / 250W |    497MiB / 16160MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> |   1  NVIDIA Tesla V1...  Off  | 00000002:00:00.0 Off |                    0 |
> | N/A   30C    P0    40W / 250W |    657MiB / 16160MiB |     48%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> |   2  NVIDIA Tesla V1...  Off  | 00000003:00:00.0 Off |                    0 |
> | N/A   29C    P0    26W / 250W |      4MiB / 16160MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> |   3  NVIDIA Tesla V1...  Off  | 00000004:00:00.0 Off |                    0 |
> | N/A   29C    P0    24W / 250W |      4MiB / 16160MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |    0   N/A  N/A     13009      C   python                            493MiB |
> |    1   N/A  N/A     13009      C   python                            653MiB |
> +-----------------------------------------------------------------------------+
> ```

I had the same problem, and in this reply you set device_id=1, but the gpu 0 is still ocupied with 493MiB, why?

**Comment by chengzhao000** [comment]
> 
I had the same problem, Have you solved it yet?
