### ISSUE TITLE
[build] Is the current behaviour of build.py --cmake_extra_defines intended?

### ISSUE THREAD

**Issue by horenmar** [microsoft/onnxruntime#9647]
Currently `--cmake_extra_defines` argument is defined with `nargs="+"`, default action, which means that invoking the `build.py` script like this:
```
build.py --cmake_extra_defines onnxruntime_BUILD_UNIT_TESTS=0 --cmake_extra_defines onnxruntime_PREFER_SYSTEM_LIB
```

adds only `-Donnxruntime_PREFER_SYSTEM_LIB` to the CMake invocation, not both of them, because the value of `args.cmake_extra_defines` is just `['onnxruntime=PREFER_SYSTEM_LIB']` -- in other words, only the last `--cmake_extra_defines` applies, the earlier ones are silently discarded.

_Silently discarding flags is annoying for hopefully obvious reasons._

The proper way to pass multiple cmake args is instead `--cmake_extra_defines onnxruntime_BUILD_UNIT_TESTS=0 onnxruntime_PREFER_SYSTEM_LIB`.

-----------------

I wonder whether the intention wasn't instead to have `--cmake_extra_defines` defined with no nargs, but with `action="append"` instead. However, this would break older scripts that use `--cmake_extra_defines` properly, so I think the best option might be to have `action="append", nargs="+"` and then explicitly flatten the resulting list of lists for the actual list of cmake args.

**Comment by snnn** [comment]
Welcome to help us improve it!

**Comment by horenmar** [comment]
@snnn I would like to, but first I need to know what is the intended behaviour.

**Comment by snnn** [comment]
Anything other than silently discarding the extra argument is good.

**Comment by snnn** [comment]
"cmake_extra_defines" is referenced by:
1. Our Azure devops yaml files
2. Docker files: https://github.com/microsoft/onnxruntime/tree/master/dockerfiles
3. tools\ci_build\github\linux\ort_minimal\build_full_ort_and_create_ort_files.sh

When you submit your PR, please be sure you have checked all these places.

**Comment by snnn** [comment]
#10953

**Comment by fs-eire** [comment]
#10953 is merged. closing this issue.
