### ISSUE TITLE
ort.env.wasm.numThreads seems not working on chrome 

### ISSUE THREAD

**Issue by RongchunYao** [microsoft/onnxruntime#9681]
My chrome version is Version 94.0.4606.71 (Official Build) (64-bit) and ort-web seems not to run with threaded version of wasm.

Ubuntu 18.04
using https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/ort.min.js

**Comment by hanbitmyths** [comment]
Chrome 92+ requires "cross-origin isolated" configuration to enable WebAssembly threads. Please refer to https://web.dev/coop-coep/ for more details.

**Comment by RongchunYao** [comment]
> Chrome 92+ requires "cross-origin isolated" configuration to enable WebAssembly threads. Please refer to https://web.dev/coop-coep/ for more details.

It is very helpful, thank you! Will you update the corresponding response header for your onnx-web CDN? It is inconvenient to download and re-serve them.

**Comment by josephrocca** [comment]
@RongchunYao No need to serve headers on the `ort.js`. You can use the CDN. You just need to serve your actual html page with these two headers:
```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```
So for example in express.js it would look something like this:
```js
app.get("/", function(req, res) {
  res.set("Cross-Origin-Embedder-Policy", "require-corp");
  res.set("Cross-Origin-Opener-Policy", "same-origin");
  res.sendFile("./index.html");
});
```
You can check if it's working by seeing the result of `self.crossOriginIsolated` in your browser console. It should be `true` if you want to use wasm threads.

**Comment by guschmue** [comment]
I tested that recently and it is fine.
