### ISSUE TITLE
windows vs2019 compile

### ISSUE THREAD

**Issue by xinsuinizhuan** [microsoft/onnxruntime#9683]
win10  vs2019 
I compile it，but it have no onnxrumtime.lib and onnxruntime.dll
![图片](https://user-images.githubusercontent.com/40679769/140607954-e15d370d-f8ad-401d-97c5-8ec9330c085d.png)
 compile with the comand:
.\build.bat --cudnn_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0" --cuda_home "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0" --use_tensorrt --tensorrt_home "D:\vison_software\NVIDIA\cuda11.0\TensorRT-8.2.0.6" --cuda_version=11.0

**Comment by snnn** [comment]
Please add “ --build_shared_lib” to your build command.
