### ISSUE TITLE
【BUG】：Register Type Can not find

### ISSUE THREAD

**Issue by KnightYao** [microsoft/onnxruntime#9695]
**Describe the bug**
I have add MLFloat16 type for RoiAlign to compute, and it can run successful,  and i run RoiAlign with float type, it run with error,  But when I move MLFloat16 behind float,  type of float will run ok, But MLFloat16 run with errorr, and i also try double type for RoiAlign , get error always; @snnn need help

Add MLFloat16
![image](https://user-images.githubusercontent.com/9350796/140707978-0a1d2b74-8227-4922-a15f-a6c14740d2f2.png)

Error Message
![image](https://user-images.githubusercontent.com/9350796/140708032-44fb5e69-03b6-474f-ad55-d3ac211b5e43.png)

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CenterOS 7.2
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version:1.7.1
- Python version:3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):gcc-5.4
- CUDA/cuDNN version:cuda-10.1  cudnn-7.6.5 
- GPU model and memory: T4 16GB

**Comment by snnn** [comment]
You may create a PR to show us what change you have made, or paste the diff file here.

**Comment by KnightYao** [comment]
> You may create a PR to show us what change you have made, or paste the diff file here.

Do not change any file also can get this error, Now ORT providers/cuda/object_detection/roialign.cc has register float and double type for input, But in providers/cuda/cuda_execution_providers.cc(line: 1430) doble type is register behind float type, then I run an op Roialign with double type for input, it will be error always, when I move float type behind double type, run double type for input is ok , but run float type was error.

**Comment by yuslepukhin** [comment]
> > You may create a PR to show us what change you have made, or paste the diff file here.
> 
> Do not change any file also can get this error, Now ORT providers/cuda/object_detection/roialign.cc has register float and double type for input, But in providers/cuda/cuda_execution_providers.cc(line: 1430) doble type is register behind float type, then I run an op Roialign with double type for input, it will be error always, when I move float type behind double type, run double type for input is ok , but run float type was error.

Have you created a RoiAlign implementation that supports MLFloat16 so you can register and use it?

**Comment by KnightYao** [comment]
> > > You may create a PR to show us what change you have made, or paste the diff file here.
> > 
> > 
> > Do not change any file also can get this error, Now ORT providers/cuda/object_detection/roialign.cc has register float and double type for input, But in providers/cuda/cuda_execution_providers.cc(line: 1430) doble type is register behind float type, then I run an op Roialign with double type for input, it will be error always, when I move float type behind double type, run double type for input is ok , but run float type was error.
> 
> Have you created a RoiAlign implementation that supports MLFloat16 so you can register and use it?

Yes I see, I have created a RoiAlign, add it also can run when I register before float type RoiAlign, But when i register MLFloat16 behind float, it can not work.@yuslepukhin @snnn

**Comment by yuslepukhin** [comment]
It would be helpful to see the error message that your implementation returns, the screenshot above is incomplete.

**Comment by KnightYao** [comment]
> It would be helpful to see the error message that your implementation returns, the screenshot above is incomplete. The error message seems to emanate from the implementation code, not from Registry as the issue title implies.

But I do not change any file for ORT source file, I run Roialign with double type(double type is register behind float type ), always get same error.

**Comment by KnightYao** [comment]
@snnn @yuslepukhin so how to fix this bug?
