### ISSUE TITLE
DML EP Error: Disallow using DML with the software adapter (Microsoft Basic Display Adapter)

### ISSUE THREAD

**Issue by YongHuangSJTU** [microsoft/onnxruntime#9708]
**Describe the bug**
I can run DML EP on my dev box with NVIDIA GPU installed, but I got this error when I ran it on another NVIDIA GPU server with same conda environment and same model:

_RxORT\external\onnxruntime_official\onnxruntime\core\providers\dml\dml_provider_factory.cc(107)\onnxruntime_pybind11_state.pyd!00007FF997C5401A: (caller: 00007FF997BB6B66) Exception(1) tid(2bdc) 80070057 The parameter is incorrect."_

I checked the code in line 107 dml_provider_factory.cc and seems this's because it can't find my NVIDIA GPU on the server. However I can run CUDA EP on same GPU machine. 
One major difference between my dev box and the server is OS, my dev box is Win10 and the server is Windows Server.

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows Server
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.9.1
- Python version: 3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: NVIDIA M60

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by wchao1115** [comment]
@YongHuangSJTU The error is to reject the `device_id` passing in because that id represents a software device. If you are calling the API that takes the device id, that device id you passed in isn't a valid GPU adapter.

**Comment by YongHuangSJTU** [comment]
Thanks @wchao1115. DML needs to run with WDDM mode on NVIDIA GPU and I was using TCC mode on my server. It works now after I changed it to WDDM. It'd be good to add this point to the [doc](https://onnxruntime.ai/docs/execution-providers/DirectML-ExecutionProvider.html)

**Comment by nums11** [comment]
Closing as resolved.
