### ISSUE TITLE
doesn't onnxruntime cpu support fp16?

### ISSUE THREAD

**Issue by zhb0920** [microsoft/onnxruntime#9731]
doesn't onnxruntime cpu support fp16?
if support .How to support？

**Comment by yuslepukhin** [comment]
ORT does support fp16. Certain ops may not support fp16.
Please, be more specific with your question.

**Comment by zhb0920** [comment]
> ORT does support fp16. Certain ops may not support fp16. Please, be more specific with your question.
ORT under x86 cpu also support fp16？eg.squeezenet

**Comment by zhb0920** [comment]
> ORT does support fp16. Certain ops may not support fp16. Please, be more specific with your question.
