### ISSUE TITLE
centos7 predict is slower than win10 on cpu?

### ISSUE THREAD

**Issue by w-Bro** [microsoft/onnxruntime#9732]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos7
- ONNX Runtime installed from (source or binary): pip install onnxruntime
- ONNX Runtime version: 1.9.0
- Python version: 3.7
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Additional context**
I have a ocr project with onnx models, and on win10(laptop), predict spends 2 seconds and on centos 7(server) it spends 7 seconds. Using `pip install onnxruntime` is a right way to install onnx? By the way, according to my observation, on win10, all cpu cores work together but usage of cpu is 200% on centos7(4 cores), anyone can help me?

**Comment by snnn** [comment]
Please manually set intra_op_num_threads to 4.

**Comment by w-Bro** [comment]
> Please manually set intra_op_num_threads to 4.

i set `intra_op_num_thread` by this, but it still slower.
```
logger.info(f"Before set inter_op_num_threads:{sess_options.inter_op_num_threads}")
sess_options.inter_op_num_threads = 4
logger.info(f"After set inter_op_num_threads:{sess_options.inter_op_num_threads}")
sess_options.execution_mode = ort.ExecutionMode.ORT_SEQUENTIAL
logger.info(f"set ExecutionMode:{ort.ExecutionMode.ORT_SEQUENTIAL}")
```
output:
```
[2021/11/12 10:17:52] root INFO: Before set inter_op_num_threads:0
[2021/11/12 10:17:52] root INFO: After set inter_op_num_threads:4
[2021/11/12 10:17:52] root INFO: set ExecutionMode:ExecutionMode.ORT_SEQUENTIAL
```
