### ISSUE TITLE
Linker flag /SAFESEH also on Linux 32bit build

### ISSUE THREAD

**Issue by pvavercak** [microsoft/onnxruntime#9744]
**Describe the bug**
Possible bug in CMake function [onnxruntime_add_shared_library_module](https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L1210). My Linux x86 CI job fails because of /SAFESEH linker option. This option is appended to linker flags [here](https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L1220). Linux 32bit build may not be your target platform but I think this can cause problems for many users targeting 32bit Linux.
Same story with [onnxruntime_add_executable](https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L1224)

**Urgency**
None

**System information**
- OS Platform and Distribution: CentOS 7
- ONNX Runtime installed from (source or binary): source
- ONNX Runtime version: 1.9.1
- Python version: 3.6
- Visual Studio version (if applicable): 
- GCC/Compiler version (if compiling from source): gcc 7.3
- CUDA/cuDNN version: -
- GPU model and memory: -

**To Reproduce**
Try building onnxruntime from tag v1.9.1 for Linux 32bit

**Expected behavior**
Working Linux 32bit build

**Additional context**
I can patch the sources so [the condition](https://github.com/microsoft/onnxruntime/blob/master/cmake/CMakeLists.txt#L1219) will be:
```cmake
if (onnxruntime_target_platform STREQUAL "x86" AND NOT onnxruntime_BUILD_WEBASSEMBLY AND MSVC)
    target_link_options(${target_name} PRIVATE /SAFESEH)
endif()
```
or something like this but as the CMakeLists.txt is changing with any further onnxruntime release, I end up updating this small patch every time I want to bump onnxruntime version.

**Comment by snnn** [comment]
Welcome to submit a pull request. Your change looks good.

**Comment by pvavercak** [comment]
I've prepared a commit on my branch but somehow, my ssh key does not work for this repo - I get Access denied from git push command. Is it something I have to set or you should give me the access rights?

**Comment by snnn** [comment]
Please follow this workflow: https://docs.github.com/en/get-started/quickstart/contributing-to-projects

**Comment by pvavercak** [comment]
I'm sorry for how long did it take to submit a PR, but hopefully, this little change is not something everybody depends on, so feel free to comment on my changes.

**Comment by goksinan** [comment]
@pvavercak Would you mind sharing the steps to build onnxruntime for 32-bit Linux? The documentation says it is not officially supported. I guess passing `--x86` argument works only for Windows.

**Comment by pvavercak** [comment]
I used a CMake toolchain file for this, for example
```cmake
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86)
```
can be your toolchain file.

Then you have to tell the build.sh script to use this toolchain file.
You can do it via `--cmake_extra_defines` parameter:
```bash
./build.py .... --cmake_extra_defines CMAKE_TOOLCHAIN_FILE=<path_to_toolchain.cmake> ....
```
I didn't try this with later versions, the version I'm using is still v1.9.1

**Comment by goksinan** [comment]
Thanks for sharing. I will give it a try.
