### ISSUE TITLE
Does Official Build for C Work with CUDA 10?

### ISSUE THREAD

**Issue by GuanLuo** [Microsoft/onnxruntime#975]
Hi, I notice that there are options to use CUDA 10 or CUDA 9 when I build from source, so I was wondering if the official GPU build for C will work with CUDA 10?

**Comment by snnn** [comment]
YES.

**Comment by GuanLuo** [comment]
I see. So the prebuilt binary is still with CUDA 9, is that correct?

If this is the case, it's there a future plan to also provide prebuilt binary with CUDA 10? Thanks.

**Comment by pranavsharma** [comment]
Official binaries are built with cuda 9.1. See here https://github.com/Microsoft/onnxruntime#system-requirements.
