### ISSUE TITLE
Crashes when relu is followed by a clip

### ISSUE THREAD

**Issue by lazycal** [microsoft/onnxruntime#9753]
**Describe the bug**
On opset version 11, when relu is followed by a clip (`clip(relu(x),-1,1)`), ORT raises segmentation fault.

**Urgency**
none

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.9.0
- Python version: 3.7.11
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 11.1/8.0.5
- GPU model and memory: RTX2080, 8GB
- PyTorch version: 1.10.0

**To Reproduce**
- Describe steps/code to reproduce the behavior.
```python
import torch
import onnx
import onnxruntime as ort


class Model(torch.nn.Module):
    @torch.no_grad()
    def forward(self, x):
        x = torch.relu(x)  # can run succesfully if comment out this line
        x = torch.clip(x, -1, 1)
        return x


model = Model()
inputs = (torch.randn(1, 1, 1, 1),)
output_names = ["output"]
torch.onnx.export(model, inputs, "1.onnx", verbose=False,
                  input_names=["input"], output_names=output_names, opset_version=11)

onnx_model = onnx.load("1.onnx")
sess = ort.InferenceSession(
    onnx._serialize(onnx_model))
res = sess.run(output_names, {"input": inputs[0].numpy()})
```
- Attach the ONNX model to the issue (where applicable) to expedite investigation.
Attached file: [1.onnx.zip](https://github.com/microsoft/onnxruntime/files/7531442/1.onnx.zip)

Plain text proto:
```proto
ir_version: 7
producer_name: "pytorch"
producer_version: "1.10"
graph {
  node {
    input: "input"
    output: "1"
    name: "Relu_0"
    op_type: "Relu"
  }
  node {
    input: "1"
    input: "7"
    input: "8"
    output: "output"
    name: "Clip_1"
    op_type: "Clip"
  }
  name: "torch-jit-export"
  initializer {
    data_type: 1
    name: "7"
    raw_data: "\000\000\200\277"
  }
  initializer {
    data_type: 1
    name: "8"
    raw_data: "\000\000\200?"
  }
  input {
    name: "input"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  output {
    name: "output"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
}
opset_import {
  version: 11
}
```

**Expected behavior**
Should not crash, but got segmentation fault.

**Screenshots**
![image](https://user-images.githubusercontent.com/7333325/141606798-db9eaaf6-98a0-42c0-a465-6be2a347ec6d.png)

**Comment by hariharans29** [comment]
Taking a look at this

**Comment by hariharans29** [comment]
@lazycal : Are you using the CUDA Python package or just the CPU  one ?

**Comment by lazycal** [comment]
@hariharans29 I'm using the CUDA one. Following is a list of onnx related packages and the version numbers installed with pip:
```
onnx                1.10.2
onnx-simplifier     0.3.6
onnxoptimizer       0.2.6
onnxruntime         1.9.0
onnxruntime-gpu     1.9.0
```

BTW I also tried passing `providers=["CUDAExecutionProvider"]` or `providers=["CPUExecutionProvider"]` to `ort.InferenceSession`, and they both resulted in segmentation fault.

**Comment by hariharans29** [comment]
Thanks, I think I root caused the issue. Will propose a solution soon.
