### ISSUE TITLE
`Buffer is not defined` when using WebGL runtime

### ISSUE THREAD

**Issue by josephrocca** [microsoft/onnxruntime#9757]
**Describe the bug**
On line 11711 of ort.js (v1.9.0) `Buffer.from(...)` is called, but `Buffer` is not defined:

```js
if (attr instanceof onnx_proto_1.onnx.AttributeProto) {
    var utf8String = value;
    return Buffer.from(utf8String.buffer, utf8String.byteOffset, utf8String.byteLength).toString();
}
```

I thought that this `Buffer` might have been a Node.js polyfill, but I tried importing the [feross/buffer](https://josephrocca.github.io/anime-gan-v2-web/onnx.html) polyfill and it didn't work - seems that Node's `Buffer.from` only takes 2 arguments.

**Urgency**
Not urgent

**System information**
- ONNX Runtime Version: https://cdn.jsdelivr.net/npm/onnxruntime-web@1.9.0/dist/ort.js
- Tested on Firefox 94 and Chrome 95 (latest versions)

**To Reproduce**
Visit this page: https://josephrocca.github.io/anime-gan-v2-web/onnx.html (switch to the WebGL runtime and then click "start")

The github repo is here: https://github.com/josephrocca/anime-gan-v2-web

**Screenshots**
![image](https://user-images.githubusercontent.com/1167575/141681620-3803900a-6791-4ea6-8f23-bc4ce0764ace.png)

**Additional context**
It works fine with the wasm runtime. The [original model](https://github.com/josephrocca/anime-gan-v2-web/blob/main/anime-gan-v2.onnx) used some int64 values (and the WebGL backend [does not support int64](https://github.com/microsoft/onnxruntime/issues/9724)) so I converted it to int32 using [this script](https://github.com/aadhithya/onnx-typecast). That said, I doubt this is relevant. Seems more likely to just be a bundling issue, or something like that.

**Comment by fs-eire** [comment]
"Buffer" is a Node.js type and should not be used in webgl. I will try if I can reproduce this issue. (I cannot reproduce the error described in #9757)

**Comment by josephrocca** [comment]
@fs-eire You can't reproduce it? That's strange - perhaps you didn't switch the drop-down menu to webgl? You can see the usage of `Buffer` by searching for `Buffer.from` (Ctrl+F) in [ort.js v1.9.0](https://cdn.jsdelivr.net/npm/onnxruntime-web@1.9.0/dist/ort.js) (line 11711, for example). Here's a video showing the bug in Firefox v94 and Chrome v95 (latest versions):


https://user-images.githubusercontent.com/1167575/141874644-2b8a92f3-3d54-4e51-9c97-9996c15ed0da.mp4

https://josephrocca.github.io/anime-gan-v2-web/onnx.html

**Comment by fs-eire** [comment]
I can reproduce it now. Looks like it uses Buffer for string encoding/decoding in attribute. I will do a fix on that
