### ISSUE TITLE
OrtException creating session on Android

### ISSUE THREAD

**Issue by marcoromelli** [microsoft/onnxruntime#9759]
**Describe the bug**
When I try to create the session object in my Android project I get the following error:
```ai.onnxruntime.OrtException: Error code - ORT_INVALID_ARGUMENT - message: Invalid fd was supplied: -1```

**System information**
- MacOS 10.15.7
- ONNX Runtime installed from gradle: implementation "com.microsoft.onnxruntime:onnxruntime-mobile:1.9.0"
- ONNX Runtime version: 1.9.0
- Python version: 3.6.0 used to train Pytorch model and convert ONNX model to ORT

**To Reproduce**
- Train simple CNN in PyTorch
- Save PyTorch model to ONNX
- Convert ONNX to ORT with Python 
- Put ORT model in resource folder in Android project
- Create onnxruntime session with `OrtEnvironment env = OrtEnvironment.getEnvironment();
            session = env.createSession(this.getClass().getResource(
                    "/model.ort").getPath());`

**Comment by skottmckay** [comment]
https://github.com/microsoft/onnxruntime-inference-examples/tree/main/mobile/examples/image_classification/android has an end-to-end example. In that it appears the model is added as a raw resource and loaded as bytes to pass to the createSession call. Could you possibly try that approach?

@gwang-msft Are the createSession variants that take a string for the file path valid on Android?

**Comment by gwang-msft** [comment]
Android does not allow direct access to the App's `asset/resource` files, there are two ways you can create an ORT session,
- Load the model as a byte array, and use the byte array to create an ORT session, this is an example in Koltin
https://github.com/microsoft/onnxruntime-inference-examples/blob/18f5702347789218c61729e3252ab53c64865340/mobile/examples/image_classification/android/app/src/main/java/ai/onnxruntime/example/imageclassifier/MainActivity.kt#L149-L159
- Extract the `asset/resource` and write it to a separate file, and then use the path to create an ORT session, see https://stackoverflow.com/questions/8474821/how-to-get-the-android-path-string-to-a-file-on-assets-folder

**Comment by marcoromelli** [comment]
Thanks @gwang-msft and @skottmckay . Loading from byte array did the trick for my use case.
