### ISSUE TITLE
when gpu is occupied, the inference slows down when i adopt a CUDA provider

### ISSUE THREAD

**Issue by tuotuoshao** [microsoft/onnxruntime#9766]
**Describe the bug**
I have used cuda_provider to accelerate my inference process and it works well, but when i'm runing an Unity process which occupies most of my gpu, the inference process would slow down, all my previous speed up would lose value. Another test, when i start two instance of my inference process, each of them would slow down. How could I sovle this problem while I have only one Gpu?

**System information**
- OS Platform and Distribution : windows 10
- ONNX Runtime installed from : source
- ONNX Runtime version: 1.9
- Visual Studio version : vs2019
- CUDA/cuDNN version: cuda=11.3 cudnn=8.2.1

**Expected behavior**
My inference time shuld not be influenced by any other gpu task.

**Screenshots**
<img width="686" alt="捕获" src="https://user-images.githubusercontent.com/51219602/141944777-b2e348c8-611a-4439-bf35-99baac9ad2fb.PNG">

**Comment by hariharans29** [comment]
Is it a reasonable justification that if the GPU is busy with other tasks or if there is a GPU resource contention (two instances of your inferencing app contending for the same resource), then all the programs requiring the GPU resources get affected ?  


As you say here: "i'm runing an Unity process which occupies most of my gpu,...", if this is the case, will this affect the performance of your other programs that needs access to the CUDA cores to run ?

**Comment by tuotuoshao** [comment]
@hariharans29  Yes, you're right. I think all the programs requiring the GPU resources get affected if the GPU is busy as I have tested two instances of my inferencing app at the same time and each of them speeds down.

But the impact of this case is far less than the Unity's impact to the inference time. What i want to do is to integrate my inference dll to the Unity, in this case, the inference time would increase several times.
