### ISSUE TITLE
C++ api slower than python api

### ISSUE THREAD

**Issue by maobaoqi** [microsoft/onnxruntime#9768]
Platform: windows10 with nvidia 3080mobile, the latest onnxruntime version. python api use about 0.7s and C++ api use 1.2s to process one frame.

**Comment by hariharans29** [comment]
This isn't enough to go on. Please fill in the GIthub issue template with code samples for C++/Python and a repro model and how you're measuring the latency. Almost every C++ vs Python perf/results discrepancy that has ever been opened has had something to do with the pre-processing/post-processing step related discrepancies. 

The core runtime is common between the language bindings and hence it is important that any comparison being made is apple-to-apple on the client side

**Comment by hariharans29** [comment]
Also, are you using the pre-built binaries or are you building from source ? If building from source, what are the build flags you are using ?

**Comment by hariharans29** [comment]
Closing this for lack of details to continue investigating. If the issue persists, please re-open with the requested details.
