### ISSUE TITLE
is there any python script for doing inference on yolo.onnx model?

### ISSUE THREAD

**Issue by akashAD98** [microsoft/onnxruntime#9781]
i have converted yolo-mish. weight into onnx & I want to do inferencing on using  .onnx model,is there any script available to this task

**Comment by hariharans29** [comment]
Whilst we don't have a script for every model, we do have some samples that you can use to build your own inferencing script. This is a pretty basic example: https://github.com/microsoft/onnxruntime/blob/871d3fb839a846a94ae1f7a20b0c97d5496c80f1/onnxruntime/test/python/onnxruntime_test_python.py#L337. See, if this helps build the inferencing script for your model.
