### ISSUE TITLE
Resize operator does not support FP16 tensor as input. 

### ISSUE THREAD

**Issue by collin-allen2** [microsoft/onnxruntime#9789]
The Resize operator does not support the 'scales' input in FP16. Quantizing a model to FP16 using onnxmltools creates a valid ONNX model, though the model will fail to run in onnxruntime due to this issue. onnxmltools converts all input tensors to FP16, so even though the scales tensor does not need to be an FP16 tensor, it would be best to have onnxruntime support models quantized by onnxmltools. 

**System information**
- Windows 10:
- ONNX Runtime installed from pip
- ONNX Runtime version: 1.9.0
- Python version: 3.9
- onnxmltools version: 1.10.0

**To Reproduce**
- Quantize a model with the Resize operator using onnxmltools then try to run through onnxruntime, or simply feed in an FP16 tensor to the Resize operator in onnxruntime.

**Comment by hariharans29** [comment]
As far as I can tell, looking at the [ONNX spec for Resize](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Resize), the 'scales' input is always fp32 even if the data being resized is fp16. If the 'scales' input is fp16 after quantization, is the resultant ONNX model even valid ?

**Comment by hariharans29** [comment]
We do have support for fp16 on CUDA for Resize: https://github.com/microsoft/onnxruntime/blob/20ec48129ba98d0697d5e057b358fa406020ae61/onnxruntime/core/providers/cuda/tensor/resize.cc#L46. I think we do not support fp16 on CPU for a lot of operators (not a common use-case)

**Comment by collin-allen2** [comment]
Valid in that the quantization operation completes fine and the model passes the onnx checker. It only fails when running through onnxruntime. If this is not meant to be supported then I suppose it is invalid, but I would hope this is a feature onnxruntime can I support. 

So far I get the same error running on CUDA as I get on CPU.

**Comment by hariharans29** [comment]
Onnxruntime is limited by what types it can support for operator inputs - it can't support types outside of what the ONNX standard prescribes. 

If you do have an ONNX model with the scales input being made fp16 and the ONNX checker doesn't report an issue, can you please report this to the ONNX project ? It should catch unsupported types for ops as part of its checking.

**Comment by wschin** [comment]
This is a bug in onnxmltools' quantization code. It should insert `Cast` before feeding `scale` to 'Resize`.

**Comment by hariharans29** [comment]
As @wschin says this is a bug in onnxmltools. Please open a ticket in that repo. Please re-open if you have further clarifications to seek.
