### ISSUE TITLE
Quantization for GRU

### ISSUE THREAD

**Issue by discort** [microsoft/onnxruntime#9796]
**Is your feature request related to a problem? Please describe.**
Currently onnx/ort models that use GRU are not quantizable.

**System information**
- ONNX Runtime version (you are using): '1.9.0'

**Describe the solution you'd like**
Please add quantization for GRU as you did for LSTM https://github.com/microsoft/onnxruntime/issues/5747

**Describe alternatives you've considered**
Pytorch [FX Graph Mode Quantization](https://pytorch.org/tutorials/prototype/fx_graph_mode_quant_guide.html)

**Additional context**
cc @yufenglee

**Comment by discort** [comment]
@hariharans29 @wschin 
is issue on your plate?

**Comment by yufenglee** [comment]
No, we don't have plan to support quantization of GRU.
