### ISSUE TITLE
Bad results during inference when using dynamic dimensions with the CUDA provider

### ISSUE THREAD

**Issue by UlrichFreitag** [microsoft/onnxruntime#9799]
## **Describe the bug**

When using a model as simple as possible (Identity) during inference with ONNXRuntime, some results are incorrect when running on CUDA. I noticed that it only occurs on:
* some shapes and it seems that it needs to be a high dimensional tensor for the bug to appear
* the inference session needs to be shared across several inferences (`ort_session.run()`)

You'll find below 2 scripts to reproduce this bug:
* `reproduce_bug_onnxrt_export.py`: exports an Identity onnx model
* `reproduce_bug_onnxrt_infer.py`: takes `test_bug.onnx` and proceeds with the inference and prints when it bugs

## **Urgency**

This is very problematic since we just cannot use ONNXRuntime in production on our model since it just gives bad results. Creating a session for each inference adds a latency that we cannot afford. So I would say: pretty urgent

## **System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux, Archlinux
- ONNX Runtime versions:
    * onnxruntime-gpu == 1.8.0
    * onnxruntime-gpu == 1.9.0
    * onnxruntime-gpu on master as of 2021-11-04 with a custom wheel build from this [commit](https://github.com/microsoft/onnxruntime/tree/ddb4c058526a0bc6f866be7c297354ed65f0fbc5)
- PyTorch version (required only if you want to export the onnx with a different partial shape): 1.10
- Python version: 3.9.0
- GCC/Compiler version (if compiling from source):
- CUDA version: 11.4
- cuDNN version: 8
- GPU model and memory: RTX 3090 (24GB), RTX 2070 (8GB), GTX 1070 Ti (8GB)

## **To Reproduce**
* You can download and unzip the model from here: [test_bug.onnx.zip](https://github.com/microsoft/onnxruntime/files/7565254/test_bug.onnx.zip)
* If you download the ONNX Model attached, you just need to run `reproduce_bug_onnxrt_infer.py`
* If you want to try with different shapes than the problematic provided one, you can change `reproduce_bug_onnxrt_export.py` and run it. PyTorch 1.10 is required in this case.

**`reproduce_bug_onnxrt_export.py`**:
```python
import torch
from torch import nn


PARTIAL_SHAPE = (16, 7, 5, 3, 3)  # Problematic shape
# PARTIAL_SHAPE = (7, 5, 3, 3)      # No errors occurs with this shape

ONNX_OPSET_VERSION = 14
ONNX_FILEPATH = "test_bug.onnx"
INPUT_NAMES = ["input"]
OUTPUT_NAMES = ["output"]
DYNAMIC_AXES = {"input": {"seq_length": 0}}
DYNAMIC_AXES = {"input": [0]}
ONNXRT_DEVICE = "cuda"
ONNXRT_DEVICE_IDX = 1


MODEL = nn.Identity()

example_tensors = [torch.ones(1, *PARTIAL_SHAPE)]
torch.onnx.export(
    model=MODEL,
    args=example_tensors,
    f=ONNX_FILEPATH,
    input_names=INPUT_NAMES,
    output_names=OUTPUT_NAMES,
    dynamic_axes=DYNAMIC_AXES,
    operator_export_type=torch.onnx.OperatorExportTypes.ONNX,
    opset_version=ONNX_OPSET_VERSION,
    do_constant_folding=True,
    verbose=False)
```
**`reproduce_bug_onnxrt_infer.py`**:
```python
import numpy as np
import onnxruntime as ort


PARTIAL_SHAPE = (16, 7, 5, 3, 3)  # Problematic shape
# PARTIAL_SHAPE = (7, 5, 3, 3)      # No errors occurs with this shape


ONNX_OPSET_VERSION = 14
ONNX_FILEPATH = "test_bug.onnx"
INPUT_NAMES = ["input"]
OUTPUT_NAMES = ["output"]
DYNAMIC_AXES = {"input": {"seq_length": 0}}
DYNAMIC_AXES = {"input": [0]}
ONNXRT_DEVICE = "cuda"
ONNXRT_DEVICE_CUDA_IDX = 0
ONNXRT_DEVICE_IDX = 0


def create_onnxrt_session(onnx_filepath, device):
    cuda_providers = [
        ("CUDAExecutionProvider", {
            "device_id": ONNXRT_DEVICE_IDX,
            "arena_extend_strategy": "kNextPowerOfTwo",
            "gpu_mem_limit": 2 * 1024 * 1024 * 1024,
            "cudnn_conv_algo_search": "EXHAUSTIVE",
            "do_copy_in_default_stream": True,
        })
    ]
    cpu_providers = ["CPUExecutionProvider"]

    providers = cuda_providers if device == "cuda" else cpu_providers
    sess_options = ort.SessionOptions()
    sess_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL
    return ort.InferenceSession(onnx_filepath, providers=providers, sess_options=sess_options)


def onnxrt_inference(ort_session, arr, device):
    upstreams_onnxrt = {  # removal of the unused inputs
        "input": ort.OrtValue.ortvalue_from_numpy(arr, device, ONNXRT_DEVICE_IDX)}

    outs = ort_session.run(
        input_feed=upstreams_onnxrt,
        output_names=OUTPUT_NAMES)
    assert len(outs) == 1
    return outs[0]


def print_result(device, is_session_shared):
    np.random.seed(42)
    session = create_onnxrt_session(ONNX_FILEPATH, device)

    is_good = True
    for seq_length in range(50):
        if not is_session_shared:
            session = create_onnxrt_session(ONNX_FILEPATH, device)
        inps = np.random.randn(seq_length, *PARTIAL_SHAPE).astype(np.float32)
        outs = onnxrt_inference(session, inps, device)
        if not np.allclose(inps, outs):
            max_diff = np.max(np.abs(inps - outs))
            print(f"BUG on seq_length: {seq_length}  -  max_diff: {max_diff}")
            is_good = False
            continue

    if is_good:
        print("Everything went fine")



print("Results with SINGLE inference Session for CPU")
print_result("cpu", is_session_shared=False)

print("Results with SHARED inference Session for CPU")
print_result("cpu", is_session_shared=True)

ONNXRT_DEVICE_IDX = ONNXRT_DEVICE_CUDA_IDX
print("Results with SHARED inference Session for CUDA")
print_result("cuda", is_session_shared=True)

print("Results with SINGLE inference Session for CUDA")
print_result("cuda", is_session_shared=False)
```

When running `reproduce_bug_onnxrt_export.py` this happens:
```
$ python reproduce_bug_onnxrt_infer.py
Results with SINGLE inference Session for CPU
Everything went fine
Results with SHARED inference Session for CPU
Everything went fine
Results with SHARED inference Session for CUDA
BUG on seq_length: 22  -  max_diff: 6.002031326293945
BUG on seq_length: 25  -  max_diff: 4.177934169769287
BUG on seq_length: 26  -  max_diff: 3.8129043579101562
BUG on seq_length: 30  -  max_diff: 5.353513717651367
BUG on seq_length: 31  -  max_diff: 4.263908863067627
BUG on seq_length: 32  -  max_diff: 4.85455846786499
BUG on seq_length: 33  -  max_diff: 5.498884677886963
BUG on seq_length: 35  -  max_diff: 5.532896995544434
BUG on seq_length: 36  -  max_diff: 5.7764482498168945
BUG on seq_length: 37  -  max_diff: 5.463088512420654
BUG on seq_length: 39  -  max_diff: 3.2731008529663086
BUG on seq_length: 41  -  max_diff: 5.865621566772461
BUG on seq_length: 43  -  max_diff: 4.208600044250488
BUG on seq_length: 44  -  max_diff: 3.8688738346099854
BUG on seq_length: 45  -  max_diff: 5.126763343811035
BUG on seq_length: 46  -  max_diff: 5.5629401206970215
BUG on seq_length: 47  -  max_diff: 4.548827648162842
BUG on seq_length: 48  -  max_diff: 5.481121063232422
Results with SINGLE inference Session for CUDA
Everything went fine
```

## **Expected behavior**

`Everything went fine` should be printed in each cases.

**Comment by hariharans29** [comment]
Thanks for the detailed and well articulated report.

We will have to take a look into this. Nothing jumps to my mind on first thought. 

Some follow-up questions:

1) What happens if you move away from the OrtValue setup (i.e.) just feed vanilla numpy arrays to the `session.run()` ? This will tell us if the issue is with the runtime itself or if there is something going on at OrtValue creation time.

2) Is this the only model you are able to repro this behavior with ? Are you able to repro this with a model without Identity in it ?

**Comment by hariharans29** [comment]
I tried building the latest master from this commit: 76715ad52560d762f1cfafb2202c962e17d85c44

And I couldn't repro this even after running the repro script a lot of times:
![image](https://user-images.githubusercontent.com/9969784/142527147-69087319-b5eb-4e34-af39-1d658ed1bdee.png)

**Comment by UlrichFreitag** [comment]
>     1. What happens if you move away from the OrtValue setup (i.e.) just feed vanilla numpy arrays to the `session.run()` ? This will tell us if the issue is with the runtime itself or if there is something going on at OrtValue creation time.
Nice! It worked just fine without the OrtValue setup! I have some questions then:
1. I thought it was something mandatory when reading the doc? 
2. Am I really using the GPU with that?
3.  What is the use of `ortvalue_from_numpy` in that case?

The function `onnxrt_inference` is now:
```python
def onnxrt_inference(ort_session, arr, device):
    upstreams_onnxrt = {  # removal of the unused inputs
        "input": arr # ort.OrtValue.ortvalue_from_numpy(arr, device, ONNXRT_DEVICE_IDX)
    }
    outs = ort_session.run(
        input_feed=upstreams_onnxrt,
        output_names=OUTPUT_NAMES)
    assert len(outs) == 1
    return outs[0]
```

>     2. Is this the only model you are able to repro this behavior with ? Are you able to repro this with a model without Identity in it ?
No, I just created a minimal example. But I had the issues with bigger models. I really think the cause comes from the OrtValue setup as you suggested.


> I tried building the latest master from this commit: [76715ad](https://github.com/microsoft/onnxruntime/commit/76715ad52560d762f1cfafb2202c962e17d85c44)
> 
> And I couldn't repro this even after running the repro script a lot of times

Weird! I just build/installed onnxruntime-gpu with this commit [76715ad](https://github.com/microsoft/onnxruntime/commit/76715ad52560d762f1cfafb2202c962e17d85c44) and I still can reproduce this issue :disappointed: - Can you reproduce it with onnxruntime-gpu 1.9.0 maybe?

However! I noticed that for some reasons, I had to change the line 53 of `reproduce_bug_onnxrt_infer.py` from `    for seq_length in range(50):` to `    for seq_length in range(200):` to have some errors at one moment... Weirdly I couldn't reproduced it either for like one minute or two with just 50 seq_lengths... :man_shrugging:. The only difference is that my GPUs are under heavy load right now and that I removed the OrtValue before (and I reconfirm that using plain numpy array works very well)

**Comment by UlrichFreitag** [comment]
Btw, since there is no Dockerfile to create plain whl file from master for Python 3.9, I created this Dockerfile inspired from your [CUDA Dockerfile](https://github.com/microsoft/onnxruntime/blob/master/dockerfiles/Dockerfile.cuda). I'm sharing this, because maybe I did something wrong? I doubt it since I can reproduce the bug from 1.9.0 with an official build... But we never know.

 I added the RTX 2070 (Turing), and RTX 3090 (Ampere) support by adding `75;80;86` to `CMAKE_CUDA_ARCHITECTURES`

```
FROM nvcr.io/nvidia/cuda:11.4.1-cudnn8-devel-ubuntu20.04

ENV PATH /usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}

ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN DEBIAN_FRONTEND="noninteractive" apt update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa && apt-get install -y python3.9 python3.9-dev python3-pip
RUN pip install virtualenv

ENV VIRTUAL_ENV=/opt/virtualenv
RUN virtualenv -p python3.9 $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN pip install numpy

ADD . /code
RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates g++ gcc make git aria2 && \
    aria2c -q -d /tmp -o cmake-3.21.0-linux-x86_64.tar.gz https://github.com/Kitware/CMake/releases/download/v3.21.0/cmake-3.21.0-linux-x86_64.tar.gz && \
    tar -zxf /tmp/cmake-3.21.0-linux-x86_64.tar.gz --strip=1 -C /usr
RUN cd /code && /bin/bash ./build.sh --skip_submodule_sync --cuda_home /usr/local/cuda --cudnn_home /usr/lib/x86_64-linux-gnu/ \
    --use_cuda --config Release --build_wheel --update --build --parallel --cmake_extra_defines ONNXRUNTIME_VERSION=$(cat ./VERSION_NUMBER) \
    'CMAKE_CUDA_ARCHITECTURES=37;50;52;60;70;75;80;86'
```

I just docker cp the wheel file after that to test it in my dev env for now.

**Comment by hariharans29** [comment]
Btw - are you able to run your script with 1.7 without issues ?

**Comment by UlrichFreitag** [comment]
Thank you very much for your reply! It solves my use case at least :partying_face: 


> Btw - are you able to run your script with 1.7 without issues ?

I had some issues, but I managed. The bug is still there on this version. You need to change the `ONNX_OPSET_VERSION` to 13 in the export script and comment the `gpu_mem_limit` argument of the cuda provider in the infer script.

Sadly I can't go before 1.7 since I don't have the proper Python version installed.

Here are the changes:
* New onnx file: [test_bug.onnx.zip](https://github.com/microsoft/onnxruntime/files/7567484/test_bug.onnx.zip)


**`reproduce_bug_onnxrt_export.py:`**
```python
import torch
from torch import nn


PARTIAL_SHAPE = (16, 7, 5, 3, 3)  # Problematic shape
# PARTIAL_SHAPE = (7, 5, 3, 3)      # No errors occurs with this shape

ONNX_OPSET_VERSION = 13
ONNX_FILEPATH = "test_bug.onnx"
INPUT_NAMES = ["input"]
OUTPUT_NAMES = ["output"]
DYNAMIC_AXES = {"input": {"seq_length": 0}}
DYNAMIC_AXES = {"input": [0]}
ONNXRT_DEVICE = "cuda"
ONNXRT_DEVICE_IDX = 1


MODEL = nn.Identity()

example_tensors = [torch.ones(1, *PARTIAL_SHAPE)]
torch.onnx.export(
    model=MODEL,
    args=example_tensors,
    f=ONNX_FILEPATH,
    input_names=INPUT_NAMES,
    output_names=OUTPUT_NAMES,
    dynamic_axes=DYNAMIC_AXES,
    operator_export_type=torch.onnx.OperatorExportTypes.ONNX,
    opset_version=ONNX_OPSET_VERSION,
    do_constant_folding=True,
    verbose=False)
```

**`reproduce_bug_onnxrt_infer.py:`**
```python
import numpy as np
import onnxruntime as ort


PARTIAL_SHAPE = (16, 7, 5, 3, 3)  # Problematic shape
# PARTIAL_SHAPE = (7, 5, 3, 3)      # No errors occurs with this shape


ONNX_OPSET_VERSION = 14
ONNX_FILEPATH = "test_bug.onnx"
INPUT_NAMES = ["input"]
OUTPUT_NAMES = ["output"]
DYNAMIC_AXES = {"input": {"seq_length": 0}}
DYNAMIC_AXES = {"input": [0]}
ONNXRT_DEVICE = "cuda"
ONNXRT_DEVICE_CUDA_IDX = 0
ONNXRT_DEVICE_IDX = 0


def create_onnxrt_session(onnx_filepath, device):
    cuda_providers = [
        ("CUDAExecutionProvider", {
            "device_id": ONNXRT_DEVICE_IDX,
            "arena_extend_strategy": "kNextPowerOfTwo",
            # "gpu_mem_limit": 2 * 1024 * 1024 * 1024,
            "cudnn_conv_algo_search": "EXHAUSTIVE",
            "do_copy_in_default_stream": True,
        })
    ]
    cpu_providers = ["CPUExecutionProvider"]

    providers = cuda_providers if device == "cuda" else cpu_providers
    sess_options = ort.SessionOptions()
    sess_options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_DISABLE_ALL
    return ort.InferenceSession(onnx_filepath, providers=providers, sess_options=sess_options)


def onnxrt_inference(ort_session, arr, device):
    upstreams_onnxrt = {  # removal of the unused inputs
        "input": ort.OrtValue.ortvalue_from_numpy(arr, device, ONNXRT_DEVICE_IDX)}
    outs = ort_session.run(
        input_feed=upstreams_onnxrt,
        output_names=OUTPUT_NAMES)
    assert len(outs) == 1
    return outs[0]


def print_result(device, is_session_shared):
    np.random.seed(42)
    session = create_onnxrt_session(ONNX_FILEPATH, device)

    is_good = True
    for seq_length in range(50):
        if not is_session_shared:
            session = create_onnxrt_session(ONNX_FILEPATH, device)
        inps = np.random.randn(seq_length, *PARTIAL_SHAPE).astype(np.float32)
        outs = onnxrt_inference(session, inps, device)
        if not np.allclose(inps, outs):
            max_diff = np.max(np.abs(inps - outs))
            print(f"BUG on seq_length: {seq_length}  -  max_diff: {max_diff}")
            is_good = False
            continue

    if is_good:
        print("Everything went fine")



print("Results with SINGLE inference Session for CPU")
print_result("cpu", is_session_shared=False)

print("Results with SHARED inference Session for CPU")
print_result("cpu", is_session_shared=True)

ONNXRT_DEVICE_IDX = ONNXRT_DEVICE_CUDA_IDX
print("Results with SHARED inference Session for CUDA")
print_result("cuda", is_session_shared=True)

print("Results with SINGLE inference Session for CUDA")
print_result("cuda", is_session_shared=False)
```

**Comment by hariharans29** [comment]
When `OrtValue.ortvalue_from_numpy()` is invoked, we use `cudaMemcpy()` to reflect the numpy buffer's contents to the device memory. 

This is what the CUDA Runtime API documentation says about this particular cudaMemcpy operation:

![image](https://user-images.githubusercontent.com/9969784/142802334-f921bf09-82c4-462f-a718-f43077577553.png)

I think what is happening is that sometimes, the numpy array's contents haven't reflected into the cuda device memory and we start processing the input before the copy is complete. We use a non-blocking stream in our sessions to do cuda operations using (i.e..) this stream does not implicitly sync with the default stream and this underlying race condition is the root cause for this bug.

If I add a line to do a default stream sync after the memcpy operation in this function, the bug goes away:
https://github.com/microsoft/onnxruntime/blob/16ddaf564c14436a3978a3f3f3316b899977a5cd/onnxruntime/core/providers/cuda/cuda_provider_factory.cc#L133

I will think about a solution for this. Thanks for reporting this.

**Comment by UlrichFreitag** [comment]
Ah! This makes sense! Well done and good news :smiley:

**Comment by yuslepukhin** [comment]
I think this may be related to [this PR](https://github.com/microsoft/onnxruntime/pull/9823)
