### ISSUE TITLE
kernel32.LoadLibrary():'cublas64_91.dll' not found

### ISSUE THREAD

**Issue by drapado** [microsoft/onnxruntime#980]
Hi, I'm trying to test in C# an ONNX model created from pytorch. I'm using the example code from [https://github.com/microsoft/onnxruntime/blob/master/docs/CSharp_API.md](https://github.com/microsoft/onnxruntime/blob/master/docs/CSharp_API.md).

I get this error in this lines of code: 
`int gpuDeviceId = 0; // The GPU device ID to execute on `
`var session = new InferenceSession(@"C:/Users/David/Downloads/regression.onnx", SessionOptions.MakeSessionOptionWithCudaProvider(gpuDeviceId));`

Error:
`Microsoft.ML.OnnxRuntime.OnnxRuntimeException
  HResult=0x80131500
  Message=[ErrorCode:NoSuchFile] kernel32.LoadLibrary():'cublas64_91.dll' not found. CUDA is required for GPU execution. . Verify it is available in the system directory=C:\Windows\system32. Else copy it to the output folder.`

However, the dll is placed in the C:\Windows\system32 folder and also in the Debug folder of the program.

I'm using cuda 9.1 with cudnn 7.1 in my GTX 1050. ONNX 0.4 installed from NuGet in visual studio 2017.

Any suggestion?
Thanks in advance!

![image](https://user-images.githubusercontent.com/45577687/57303410-8dc39800-70dd-11e9-8d16-b90d237b2605.png)

**Comment by jignparm** [comment]
The project failed to load cublas64_91.dll. Could you reinstall the  Cuda 9.1 toolkit again? There are probably some missing dependent dlls that need to be resolved. You can use dependency walker to see what libraries are missing.

Can you also provide a few more details about your project (e.g. is it .NetCore or .NetFramework, and what's the target (AnyCPU, x86 or x64))? If you don't have a preference, please try .NetCore with AnyCPU.

**Comment by jignparm** [comment]
Closing this out -- assuming no response means all is good. Reopen if required.

**Comment by drapado** [comment]
Hi, the error still persist. I'm setting a new system rigth now with the latest versions (onnx runtime 0.5 and cuda 10.0) and I get the same error. I follow the guide to install cuda and the deviceQuery test pass. I'm wondering why the code looks for the cuda dlls in the system32 folder (sorry if dumb question, I mostly work in linux so not much experience with windows)
Thanks for the help

**Comment by jignparm** [comment]
To see which CUDA  10 DLLs  are missing, you can use [dependency walker](http://www.dependencywalker.com/), and open onnxruntime.dll file in the NuGet package to view the resolved and missing libraries. The most likely cause is that some of the CUDA DLLs are not present on your  system PATH variable. Could you paste a screenshot of what dependency walker displays?

```
│
├───runtimes
│   ├───linux-x64
│   │   └───native
│   │           libonnxruntime.so
│   │
│   └───win-x64
│       └───native
│               onnxruntime.dll  <-- this one
│               onnxruntime.lib
│               onnxruntime.pdb
```

**Comment by drapado** [comment]
Dependency walker doesn't tell me much. But maybe it does to you, here is the screenshot!
![image](https://user-images.githubusercontent.com/45577687/62774119-ccf4e280-ba58-11e9-91f4-1b6dd11f0b1b.png)

**Comment by jignparm** [comment]
The original  error message in 0.4.0 was: _kernel32.LoadLibrary():'cublas64_91.dll' not found_. What error are you getting now with 0.5.0?

From the dependency walker screenshot, it shows that the CUDA libraries are available (i.e. either in system directories, or via the PATH environment variable).

**Comment by drapado** [comment]
Ok, problem solved. Stupid thingy, I just had to forced running on x64 mode. Noob error, but thanks a lot for your help!!
