### ISSUE TITLE
Onnx runtime threading is broken in gunicorn

### ISSUE THREAD

**Issue by moscicky** [microsoft/onnxruntime#9800]
**Describe the bug**
When running onnx runtime inside `gunicorn` server two issues occur:
- setting `intra_op_num_threads` to anything other than 1 doesn't have any effect - CPU utilization doesn't go up and inference time is the same
- setting `inter_op_num_threads` >= 2 and `exec_mode=PARALLEL` causes whole server to stuck infinitely in `InferenceSession#run`.  

**System information**
- MacOS BigSur native,  ubuntu 18 docker container on MacOS BigSur and Linux Ubuntu 16.04
- ONNX Runtime installed from pypi
- ONNX Runtime version: 1.8.1
- Python version: 3.7.8
- Default CPU executor
- gunicorn 20.0.4

**To Reproduce**
Create `InferenceSession` inside gunicorn server with:
- `intra_ops_num_threads` > 1, run inference and observe CPU utilization stay the same, e.g. via `htop`
- `inter_ops_num_threads` > 1 and `execution_mode=PARALLEL`, run inference - it should hang the server

**Expected behavior**
I expect onnx runtime to behave exactly the same as it does without `gunicorn` (tested with the same model) or in `bjoern` server (also tested with the same model) which means: respect `intra_ops` parameter and run correctly in `parallel` mode

**Additional context**
I assume this is not bug inside onnxruntime, though I would be thankful if you could point out why onnxruntime threading doesn't work correctly on `gunicorn` server

**Comment by yuslepukhin** [comment]
To deal with CPU utilization try setting the following [option](https://github.com/microsoft/onnxruntime/blob/38583384c7951892cca9be000470b07d004c1ffe/include/onnxruntime/core/session/onnxruntime_session_options_config_keys.h#L62) to zero.
I recommend using sequential executor with tuned number of threads.

**Comment by pranavsharma** [comment]
Do you've a repro? I couldn't repro it. See below.
Started gunicorn using ```gunicorn -w 4 my_gunicorn_app:app```
```
(pranav_py8) pranav@XXX:~$ cat my_gunicorn_app.py
import numpy as np
import onnxruntime as rt

def app(environ, start_response):
    data = b"Hello, World!\n"
    sess = rt.InferenceSession("squeezenet1.1-7.onnx")
    input_name = sess.get_inputs()[0].name
    X_test = np.random.rand(1,3,224,224)
    for x in range(10000):
        pred_onx = sess.run(None, {input_name: X_test.astype(np.float32)})[0]
    start_response("200 OK", [
            ("Content-Type", "text/plain"),
            ("Content-Length", str(len(data)))
    ])
    return iter([data])
```

<img width="473" alt="image" src="https://user-images.githubusercontent.com/2732907/142574364-50f0fc38-3abe-4e1a-8cc5-2de03bde47f8.png">

**Comment by moscicky** [comment]
I will provide a repro by the end of this week

**Comment by moscicky** [comment]
@pranavsharma turns out this was due to the fact that our ort session initialization was done before starting up the server. Initializing the session after the server startup solved the issue.
