### ISSUE TITLE
Problems with scan node when trying to run sklearn.gaussian_process.GaussianProcessRegressor()

### ISSUE THREAD

**Issue by tsimpkin** [microsoft/onnxruntime#9808]
**Describe the bug**
When trying to get output predictions from an inference session with a model that uses the SKLearn Gaussian Process Regressor, I get the following error message:

onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Scan node. Name:'Sc_Scan' Status Message: Subgraph must have the shape set for all outputs but next_out did not.

**System information**
- OS Platform and Distribution: Windows 10
- ONNX Runtime installed from: pypi
- ONNX Runtime version: 1.9.0
- Python version: 3.7.9

**To Reproduce**
Train any model using sklearn.gaussian_process.GaussianProcessRegressor() and try to output predictions from onnxruntime inference session.

- Describe steps/code to reproduce the behavior.
I first observed it when it was part of a stacking regressor model, but double checked it as a standalone as well. Here's a brief script to reproduce:

```
import numpy as np
from sklearn.datasets import make_regression
from sklearn.gaussian_process import GaussianProcessRegressor as GPR
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import make_pipeline
import onnxruntime as rt
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType

#Create and prepare data.
n_samples, n_features = 10000, 10
X, y = make_regression(n_samples, n_features)  
tx1,vx1,ty1,vy1 = train_test_split(X, y)

#Define model with scaling.
model = GPR()
pipe = make_pipeline(MinMaxScaler(feature_range=(-1, 1)), model)
pipe.fit(tx1, ty1)

#Convert to onnx and run predictions.
initial_type=[('data_in', FloatTensorType([None, X.shape[1]]))]
onx = convert_sklearn(pipe, initial_types=initial_type)
sess = rt.InferenceSession(onx.SerializeToString())
pred_ort = sess.run(None, {'data_in': vx1.astype(np.float32)})[0]

#Show output for comparison.
print(pred_ort[:10])
print(vy1[:10])
```

**Expected behavior**
This should output both predicted and actual values for comparison.

**Comment by wschin** [comment]
This looks like a converter bug. Maybe shape inference is not triggered for sub-graph?

**Comment by garymm** [comment]
If it's a bug in the converter, please open it in https://github.com/onnx/sklearn-onnx/

**Comment by tsimpkin** [comment]
Opened in https://github.com/onnx/sklearn-onnx/. Will close here once bug is confirmed to be on the converter side.
