### ISSUE TITLE
TopK return random value when Kth is inf

### ISSUE THREAD

**Issue by fefe982** [microsoft/onnxruntime#9843]
**Describe the bug**
When the input tensor contains a lot of `inf` values, and the Kth element is `inf`, TopK will return some random values and indices

**Urgency**

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS Linux release 8.2.2004
- ONNX Runtime installed from (source or binary): onnxruntime-gpu binary
- ONNX Runtime version: 1.9.0
- Python version: 3.9.2
- CUDA/cuDNN version: CUDA 11.4, cuDNN 8.2
- GPU model and memory: Tesla T4

**To Reproduce**
```python
from numpy.core.getlimits import _KNOWN_TYPES
import onnx
import onnx.checker
from onnx.onnx_ml_pb2 import IR_VERSION_2019_1_22
import onnxruntime as rt
import numpy

model = onnx.ModelProto(
    ir_version=IR_VERSION_2019_1_22,
    opset_import=[onnx.OperatorSetIdProto(version=11)],
    graph=onnx.GraphProto(
        name="graph",
        input=[
            onnx.ValueInfoProto(
                name="i",
                type=onnx.TypeProto(
                    tensor_type=onnx.TypeProto.Tensor(
                        elem_type=1,
                        shape=onnx.TensorShapeProto(
                            dim=[
                                onnx.TensorShapeProto.Dimension(dim_value=1),
                                onnx.TensorShapeProto.Dimension(dim_value=10000),
                            ]
                        ),
                    )
                ),
            ),
            onnx.ValueInfoProto(
                name="k",
                type=onnx.TypeProto(
                    tensor_type=onnx.TypeProto.Tensor(
                        elem_type=onnx.TensorProto.DataType.INT64,
                        shape=onnx.TensorShapeProto(dim=[onnx.TensorShapeProto.Dimension(dim_value=1)]),
                    )
                ),
            ),
        ],
        output=[
            onnx.ValueInfoProto(
                name="o",
                type=onnx.TypeProto(
                    tensor_type=onnx.TypeProto.Tensor(
                        elem_type=1,
                        shape=onnx.TensorShapeProto(
                            dim=[
                                onnx.TensorShapeProto.Dimension(dim_value=1),
                                onnx.TensorShapeProto.Dimension(dim_value=6),
                            ]
                        ),
                    )
                ),
            ),
            onnx.ValueInfoProto(
                name="o_idx",
                type=onnx.TypeProto(
                    tensor_type=onnx.TypeProto.Tensor(
                        elem_type=onnx.TensorProto.DataType.INT64,
                        shape=onnx.TensorShapeProto(
                            dim=[
                                onnx.TensorShapeProto.Dimension(dim_value=1),
                                onnx.TensorShapeProto.Dimension(dim_value=6),
                            ]
                        ),
                    )
                ),
            ),
        ],
        node=[onnx.NodeProto(input=["i", "k"], output=["o", "o_idx"], name="topk", op_type="TopK")],
    ),
)
onnx.checker.check_model(model)
onnx.save_model(model, "temp.onnx")

sess = rt.InferenceSession("temp.onnx", providers=["CUDAExecutionProvider"])
i = numpy.ones([1, 10000], dtype=numpy.float32) * -numpy.inf
i[0, 0] = 1
i[0, 1] = 2
print(i)
k = numpy.array([6], dtype=numpy.int64)
o = sess.run(["o", "o_idx"], {"i": i, "k": k})
print(o)
```
output on my env is
```
[[  1.   2. -inf ... -inf -inf -inf]]
[array([[2., 1., 0., 0., 0., 0.]], dtype=float32), array([[1, 0, 0, 0, 0, 0]], dtype=int64)]
```
The second line is the output of TopK, in which the last four elements are actually random.
With a larger and more complex graph, I can get any value in the last four elements.

As any value can appear in the result, with the result sorted, the random values might appear before the real result, for example:
`[[4.988, 2, 1, 0, 0, 0]]`

**Expected behavior**
The value output should be `[2., 1., -inf, -inf, -inf., -inf]`, and the last four elements of indices should be distinct but valid indices.

**Screenshots**

**Additional context**

**Comment by fefe982** [comment]
The reason for this might be that, when gathering elements equal to Kth elements, [RadixTopK](https://github.com/microsoft/onnxruntime/blob/4daa14bc74b5378d5fcb0d6de063a9fa8bd42eac/onnxruntime/core/providers/cuda/math/topk_impl.cu#L347) uses the following logic:
```cpp
    } else if (Equal(x, Kth) && equal_quota > 0) {
      auto to_i = TO(output_i);
      V[to_i] = x;
      I[to_i] = x_i;
      ++output_i;
      --equal_quota;
    }
```

And [Equal ](https://github.com/microsoft/onnxruntime/blob/4daa14bc74b5378d5fcb0d6de063a9fa8bd42eac/onnxruntime/core/providers/cuda/math/topk_impl.cu#L178)is defined as:
```cpp
__device__ __inline__ bool Equal(const float& t0, const float& t1) {
  auto t2 = t0 > t1 ? t0 - t1 : t1 - t0;
  return t2 < std::numeric_limits<float>::epsilon();
}
```
When Kth is `Inf`,  both `t0` and `t1` might be `Inf`, then `t2` would be `NaN` (`Inf` - `Inf`), which make the result for `Equal` `false`. 

In this case, elements equal to Kth are never filled, leaving them with random values.

**Comment by RyanUnderhill** [comment]
Amusing, but the Onnx spec for TopK doesn't mention any behavior for non finite numbers. Is this a valid use case for you?

**Comment by fefe982** [comment]
Yes. Most of the values in the tensor are masked out by -Inf. I met this when not enough finite values are left in the tensor.

**Comment by fefe982** [comment]
Even Inf is not a finite number, it is comparable with other finite numbers and with itself. So I think it should be handled properly.

**Comment by RandySheriffH** [comment]
@fefe982 - thanks for reporting this, I am fixing the case.
