### ISSUE TITLE
The ONNX graph converted from tf.image.crop_and_resize() function will fail to be inferenced by latest version of ORT.

### ISSUE THREAD

**Issue by fatcat-z** [microsoft/onnxruntime#9857]
**Describe the bug**
Clone the latest code of master branch and install it in local machine. The ONNXRUNTIME version should be 1.10.0. Try to execute the example script provided in this issue which is trying to inference an ONNX file generated by converting tf.image.crop_and_resize() op to ONNX via tf2onnx, it throws an exception: Segmentation fault

If we install the onnxruntime 1.9.0, this issue is gone.

**Urgency**
This might be an issue blocking the latest release.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):   Linux Ubuntu 18.04
- ONNX Runtime installed from (source or binary):    source
- ONNX Runtime version:   1.10.0
- Python version:  3.8

**To Reproduce**
- Download the attached zip file [crop_resize_issue.zip](https://github.com/microsoft/onnxruntime/files/7597104/crop_resize_issue.zip).
- Unzip it and execute the command "python crop_resize_issue.py" under this folder.

**Expected behavior**
It should display Pass without any exceptions.

**Comment by pranavsharma** [comment]
@fatcat-z  Is this model running in production or do you plan to deploy it to prod?
