### ISSUE TITLE
Can't extract the shape of the output of `SequenceAt`.

### ISSUE THREAD

**Issue by jantonguirao** [microsoft/onnxruntime#9868]
**Describe the bug**
Can't extract the shape of the output of `SequenceAt`.

I'd expect to be able to call `Shape` operator on the output of a `SequenceAt` operator, and still be able to get the actual shape, the same way as if I was invoking `Shape` directly on a tensor input.

**Urgency**
This slows down the progress of the experiments regarding the ONNX preprocessing working group.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04.3 LTS
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 1.9.0
- Python version: Python 3.8.10
- Visual Studio version (if applicable): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**To Reproduce**
- Describe steps/code to reproduce the behavior.
- Attach the ONNX model to the issue (where applicable) to expedite investigation.
```
#!/bin/python

import numpy as np  # type: ignore
import onnx
import onnxruntime

op = onnx.OperatorSetIdProto()
op.version = 14

nodes = []

const_node = onnx.helper.make_node(
        'Constant',
        inputs=[],
        outputs=['iter_count'],
        value=onnx.helper.make_tensor(
            name='iter_count_0',
            data_type=onnx.TensorProto.INT64,
            dims=(),
            vals=[0]
        )
    )

seq_at_node = onnx.helper.make_node(
        'SequenceAt',
        inputs=['seq_in0', 'iter_count'],
        outputs=['x_0']
    )

shape_node = onnx.helper.make_node('Shape', inputs=['x_0'], outputs=['x_shape'], name='x_shape')

graph1 = onnx.helper.make_graph(
    nodes=[shape_node],
    name='tensor_graph',
    inputs=[onnx.helper.make_tensor_value_info('x_0', onnx.TensorProto.FLOAT, [-1, -1, -1])],
    outputs=[onnx.helper.make_tensor_value_info('x_shape', onnx.TensorProto.INT64, [3])],
)

model1 = onnx.helper.make_model(graph1, producer_name='test', opset_imports=[op])
onnx.checker.check_model(model1)
onnx.save(model1, "model1.onnx")

session1 = onnxruntime.InferenceSession("model1.onnx", None)
result1 = session1.run(
    [],
    {
        'x_0' : np.zeros([10, 20, 3], dtype=np.float32)
    }
)
print(result1)

graph2 = onnx.helper.make_graph(
    nodes=[const_node, seq_at_node, shape_node],
    name='sequence_graph',
    inputs=[onnx.helper.make_tensor_sequence_value_info('seq_in0', onnx.TensorProto.FLOAT, [-1, -1, -1])],
    outputs=[onnx.helper.make_tensor_value_info('x_shape', onnx.TensorProto.INT64, [3])],
)

model2 = onnx.helper.make_model(graph2, producer_name='test', opset_imports=[op])
onnx.checker.check_model(model2)
onnx.save(model2, "model2.onnx")

session2 = onnxruntime.InferenceSession("model2.onnx", None)
result2 = session2.run(
    [],
    {
        'seq_in0' : [np.zeros([10, 20, 3], dtype=np.float32), np.zeros([10, 20, 3], dtype=np.float32)]
    }
)
print(result2)
```
shows:
```
[array([10, 20,  3], dtype=int64)]
[array([-1, -1, -1], dtype=int64)]
```

**Expected behavior**
I would expect the shape to be extracted in both cases

**Screenshots**
N/A

**Additional context**
N/A

**Comment by askhade** [comment]
@jantonguirao : Any particular reason you are setting the input shapes as [-1, -1, -1] ? If you want the shapes to be dynamic use symbols or leave them empty ['M','N','O'] or ['NONE','NONE','NONE'] should work.

**Comment by jantonguirao** [comment]
That worked. Thank you @askhade !
