### ISSUE TITLE
Bart examples

### ISSUE THREAD

**Issue by JaheimLee** [microsoft/onnxruntime#9871]
Hi, I saw you add a new Bart model type recently. So, is there any example to convert and optimize a bart model for inferencing?

**Comment by askhade** [comment]
What is the original framework that you are referring to? Did you run into any issues during conversion?

**Comment by natke** [comment]
Hi @JaheimLee ,

We have HuggingFace / ONNX Runtime tutorials here: **https://onnxruntime.ai/docs/tutorials/huggingface.html**

Specifically on the BART export, there is a HuggingFace notebook here: https://github.com/huggingface/notebooks/blob/master/examples/onnx-export.ipynb, which runs the steps to export and compare performance between PyTorch and ONNX Runtime. You should be able to replace the steps for BERT with BART to get the results you need. Please let us know how you go.

**Comment by JaheimLee** [comment]
> Hi @JaheimLee ,
> 
> We have HuggingFace / ONNX Runtime tutorials here: **https://onnxruntime.ai/docs/tutorials/huggingface.html**
> 
> Specifically on the BART export, there is a HuggingFace notebook here: https://github.com/huggingface/notebooks/blob/master/examples/onnx-export.ipynb, which runs the steps to export and compare performance between PyTorch and ONNX Runtime. You should be able to replace the steps for BERT with BART to get the results you need. Please let us know how you go.

Thanks a lot! I also found an example here: https://github.com/huggingface/transformers/tree/master/examples/onnx/pytorch/translation. Maybe it is a better way?

**Comment by askhade** [comment]
The notebook which @natke pointed you towards includes details regarding model optimization and benchmarking as well but if the link you pointed to works for you then thats good too! Closing this issue now. Please reopen if you still have open questions.

**Comment by nirmal2k** [comment]
Link's broken. Please update 🙏
> > Hi @JaheimLee ,
> > We have HuggingFace / ONNX Runtime tutorials here: **https://onnxruntime.ai/docs/tutorials/huggingface.html**
> > Specifically on the BART export, there is a HuggingFace notebook here: https://github.com/huggingface/notebooks/blob/master/examples/onnx-export.ipynb, which runs the steps to export and compare performance between PyTorch and ONNX Runtime. You should be able to replace the steps for BERT with BART to get the results you need. Please let us know how you go.
> 
> Thanks a lot! I also found an example here: https://github.com/huggingface/transformers/tree/master/examples/onnx/pytorch/translation. Maybe it is a better solution?

**Comment by natke** [comment]
Hi @nirmal2k, which link is broken? Thank you!

**Comment by nirmal2k** [comment]
@natke This [one](https://github.com/huggingface/transformers/tree/master/examples/onnx/pytorch/translation)

**Comment by natke** [comment]
You can try this link: https://huggingface.co/docs/transformers/serialization. It has documentation on exporting HuggingFace models to ONNX and includes BART
