### ISSUE TITLE
How to set the input layer to uint8 tensor instead of inserting 'QuantizeLinear'?

### ISSUE THREAD

**Issue by Goose-Bomb** [microsoft/onnxruntime#9887]
**System information**
- ONNX Runtime version (you are using): 1.9.0

**Describe the solution you'd like**
Currently, the onnxruntime static quantization tool will insert `QuantizeLinear` ops for all `fp32` inputs, however, I'd like the input tensor to be `uint8` type so it could directly accept 8bit image data. Is there any option for the quantization tool to achieve this?

**Comment by yufenglee** [comment]
No, there is not this kind of option now. The tool will keep the inputs and outputs of the model as it is. You can do a post processing by removing the QuantizeLinear node and make its inputs (X, scale, zero_point) as the model input with Onnx APIs: https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md.

And if you want to use uint8 as input, you need to do quantizaztion outside of the model.
