### ISSUE TITLE
FP16 model inference time is two times of FP32 model

### ISSUE THREAD

**Issue by MasterGG** [microsoft/onnxruntime#9892]
**Describe**
  when i use onnxmltools like this:

           from onnxmltools.utils.float16_converter import convert_float_to_float16
           half_onnx_model = onnxmltools.utils.load_model(input_onnx_model)

and do inference by onnxruntime, i found fp32 model is twice faster than fp16 model.
here is op used in my model:
**Conv, Relu, Sigmoid, Mul, Clip, Pow, GlobalAveragePool, Shape, Gather, Unsqueeze, Concat, Reshape, Gemm**

i want to make sure that whether it is Some operator showed in the picture does not have GPU implementation, or some other reasons caused the decrease.

here is my systemn information:
- OS Platform :Linux Ubuntu 16.04 / x86_64
- ONNX Runtime version: onnxruntime-gpu : 1.9.0
- Python version:  3.6.8
- CUDA/cuDNN version: 11.0
- GPU type: Tesla P100

**Comment by askhade** [comment]
There could be 2 reasons - 
1. GPU does not have FP16 implementation so the execution fallbacks to CPU: To see the placement decided by ORT, turn on verbose logging and look at the console output. 
2. There is no FP16 implementation in CPU either so we add Cast nodes to go from FP16 to FP32. Simply enable model serialization to see whether cast nodes were added: https://onnxruntime.ai/docs/performance/graph-optimizations.html#python-api-example
```
# To enable model serialization after graph optimization set this
sess_options.optimized_model_filepath = "<model_output_path\optimized_model.onnx>"
```

You can get more insights from profiling report as well. This is how you can enable profiling: https://onnxruntime.ai/docs/performance/tune-performance.html#profiling-and-performance-report

**Comment by MasterGG** [comment]
Thanks  @askhade , when i set batch size larger than 128 in V100, FP16 is faster than F32.
But i am doubt that whether it is run in GPU or not,
i set :
`sess = ort.InferenceSession(model_path, providers=["CUDAExecutionProvider"])
    print('EXECUTORS :', sess.get_providers())`
get log  : 
my provider: ['CPUExecutionProvider']
does it mean that the model inference is not in GPU mode?  how can i set it in GPU mode?


this is my GPU info:
$nvidia-smi
Fri Dec  3 20:12:55 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |

$nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

**Comment by MasterGG** [comment]
thank you, problems solved. I changed CUDA version to 11.4.2 and cudnn 8.2.4, print('EXECUTORS :', sess.get_providers()) got ['CUDAExecutionProvider', 'CPUExecutionProvider'] , and in such env when set batch size bigger than 512 ,FP16 is faster than F32.
