### ISSUE TITLE
android build error 

### ISSUE THREAD

**Issue by dachengai** [microsoft/onnxruntime#9907]
build command: 

./build.sh --android --android_sdk_path /home/android_sdk/ --android_ndk_path /home/android-ndk-r17c --android_abi armeabi-v7a --android_api 21

error info:  

home/onnxruntime/onnxruntime/core/optimizer/fast_gelu_fusion.cc:16:29: error: no viable constructor or deduction guide for deduction of template
      arguments of 'array'
static constexpr std::array gpu_supported_data_types{"tensor(float16)", "tensor(float)", "tensor(bfloat16)"};
                            ^
/home/android-ndk-r17c/sources/cxx-stl/llvm-libc++/include/__tuple:223:64: note: candidate function template not viable: requires 0 arguments, but 3
      were provided
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
/home/android-ndk-r17c/sources/cxx-stl/llvm-libc++/include/__tuple:223:64: note: candidate function template not viable: requires 1 argument, but 3
      were provided
/home/onnxruntime/onnxruntime/core/optimizer/fast_gelu_fusion.cc:17:29: error: no viable constructor or deduction guide for deduction of template
      arguments of 'array'
static constexpr std::array cpu_supported_data_types{"tensor(float)"};
                            ^
/home/android-ndk-r17c/sources/cxx-stl/llvm-libc++/include/__tuple:223:64: note: candidate template ignored: could not match 'array<_Tp, _Size>'
      against 'const char *'
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^

**Comment by snnn** [comment]
We didn't test r17. We are using r21/r22.

**Comment by snnn** [comment]
Is it gcc 4.9?

**Comment by dachengai** [comment]
> Is it gcc 4.9?

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

**Comment by dachengai** [comment]
> 

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

**Comment by dachengai** [comment]
> Is it gcc 4.9?

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

**Comment by snnn** [comment]
Sorry we dropped the support for gcc 5.x.

**Comment by dachengai** [comment]
> Sorry we dropped the support for gcc 5.x.

use gcc 9.3.0 same error happened

gcc -v 
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

**Comment by snnn** [comment]
> > Sorry we dropped the support for gcc 5.x.
> 
> use gcc 9.3.0 same error happened
> 
> gcc -v gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

That one is provided by **Ubuntu**. You are building an app for **Android**. Ubuntu's gcc doens't work for Android.

**Comment by dachengai** [comment]
build on  centos +gcc 7.5 + ndkr23  is ok

./build.sh --config Release --build_shared_lib --use_openmp --skip_tests --parallel --android --android_sdk_path /home/android-sdk/ --android_ndk_path /home/android-ndk-r23b/ --android_abi armeabi-v7a --android_api 21
