### ISSUE TITLE
C++ native nuget package AdditionalDependencies

### ISSUE THREAD

**Issue by IlTeo285** [microsoft/onnxruntime#9924]
The *.props file define 
`<AdditionalDependencies>$(MSBuildThisFileDirectory)../../runtimes/win-x64/native/onnxruntime.lib</AdditionalDependencies>`
that not append already present AdditionaDependencies, breaking the linking phase.
My suggestion is to update like this:
`<AdditionalDependencies>$(MSBuildThisFileDirectory)../../runtimes/win-x86/native/onnxruntime.lib;%(AdditionalDependencies)</AdditionalDependencies>`

- OS Platform and Distribution: Windows 10 Pro
- ONNX Runtime installed from: nuget package
- ONNX Runtime version: 1.9.1
- Visual Studio version: Version 17.1.0 Preview 1.0

**Comment by askhade** [comment]
@IITeo285 I dont quite understand what is breaking. Can you paste the linker error.

**Comment by IlTeo285** [comment]
I try to explain myself better.
Actually your nuget package doesn't use `%(AdditionalDependencies)`. That means that if you have other nuget packages installed into the project, depending on installation order, could be that you package break the link dependancy stack inheritance. As an instance I've got the problem installing your package after the vcpkg package. The solution stop build correctly because of link problem on vcpkg. Changing the nuget packages installation order the problem disappear
