### ISSUE TITLE
GPU builds with Azure Pipelines?

### ISSUE THREAD

**Issue by suo** [microsoft/onnxruntime#993]
Hey all, I work on PyTorch and I'm experimenting with using Azure Pipelines in our CI. I noticed that you have GPU pipelines set up and I was wondering how you did it. Are there Microsoft-hosted agents with GPU available? Or can we get GPU VMs from Azure and wire them up to work with Azure Pipelines? Curious what the best practices are.

If this is a bad place to ask this question feel free to redirect wherever

**Comment by pranavsharma** [comment]
We use self-hosted agents. Last I checked Azure Pipelines doesn't support GPU VMs.

**Comment by Borda** [comment]
Hi, is there any update about Azure Pipelines with support GPU VMs? Thx
