### ISSUE TITLE
Runtime exception with onnxruntime GPU

### ISSUE THREAD

**Issue by BttMA** [microsoft/onnxruntime#9939]
**Describe the bug**
I tried to execute my onnx model on gpu (after I install onnxruntime-gpu) but I got this runtime exception :

`[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running FusedMatMul node. Name:'MatMul_92_FusedMatMulAndScale' Status Message: /onnxruntime_src/onnxruntime/core/framework/bfc_arena.cc:331 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool) Failed to allocate memory for requested buffer of size 8388608000`

**Urgency**
The model tun perfectly when I try it on CPU. I just installed the gpu pack and it wont work anymore.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux (I use Colab for all of this)
- ONNX Runtime installed from (source or binary): `pip install onnxruntime-gpu -U`
- ONNX Runtime version: 1.9.0
- Python version: 3.7.12
- CUDA/cuDNN version: CUDA 11.2 
- GPU model and memory: Tesla V100-SXM2-16GB

**Additional context**
this what I did to save my model :
```
module.to_onnx("_model_gpu.onnx",
              (encoding.input_ids, encoding.attention_mask),
              input_names=input_names,
              output_names=output_names,
              opset_version=12,
              dynamic_axes={'input_ids' : {0 : 'batch_size'}, 'attention_mask' : {0 : 'batch_size'}, 'Classes' : {0 : 'batch_size'}},
              #operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK,
              export_params=True,
              do_constant_folding=True,
              )
```

and to test my model i use this snippet of code : 
```
import onnxruntime as ort
import torch
import numpy as np

ort_session = ort.InferenceSession("./_model__gpu.onnx")

outputs = ort_session.run(
    None,
    {"input_ids": input_ids_val.numpy(),
     "attention_mask": attention_masks_val.numpy()
     },
)
argmax = torch.argmax(torch.from_numpy(outputs[0]), dim=1)
print("argmax :", argmax, '\n')
```

**Comment by yuslepukhin** [comment]
We would need to see your model to look for what is wrong. Your Tesla V100 does not have that much memory to satisfy the request.

**Comment by BttMA** [comment]
Thanks for your comment :)
That is what I thought too but the message didn't come clear. I tested the model with less data and it worked! 
Maybe you should do something abut the message to be more clear :)

**Comment by garymm** [comment]
Seems the user's question has been answered so I'm closing. Feel free to re-open or open another issue if I'm wrong.
