### ISSUE TITLE
DML inferencing skipped on providing output tensor created by DML Allocator (command list not flushed)

### ISSUE THREAD

**Issue by wcpeter1988** [microsoft/onnxruntime#9962]
**Describe the bug**
"Run" skipped inference when using DML allocator to create output OrtValue.

**Urgency**
None

**System information**
- Not platform-specified
- ONNX Runtime installed from source:
- ONNX Runtime version: 2021/12/08 master branch,, build with --use_dml
- GPU model and memory: any

**To Reproduce**
Ort::MemoryInfo memory_info_memory("DML", OrtAllocatorType::OrtDeviceAllocator, 0, OrtMemTypeDefault);
memory_allocator = new Ort::Allocator(session, memory_info_memory);
std::vector<Ort::Value> inputs;
inputs.push_back(std::move(Ort::Value::CreateTensor<float>(*memory_allocator, input_shape, 1)));
std::vector<Ort::Value> outputs;
outputs.push_back(std::move(Ort::Value::CreateTensor<float>(*memory_allocator, output_shape, 1)));

// following line could submit Dml command list to D3D12CommandQueue
auto res = session.Run(runOpt, names, inputs.data(), sizeof(names) / sizeof(const char*), outNames, 1);

// following line will not submit Dml command list to D3D12CommandQueue
res = session.Run(runOpt, names, inputs.data(), sizeof(names) / sizeof(const char*), outNames, outputs.data(), 1);

**Expected behavior**
Inference is running correctly on providing output OrtValue created by DML allocator

**Additional context**
The issue is Dml Execution Provider queue OpKernel into commandList, and submit commandList to commandQueue is triggered by Flush in ReadbackFromGpu.
On using DML allocator to create the input/output tensor, onnxruntime skip input/output copy since input/output tensor and graph are on same device, which results in commandList submission also skipped.
A quick fix could be implementing OnRunEnd for Dml::ExecutionProvider.

**Comment by fdwr** [comment]
@wcpeter1988: Thanks. I'm unfamiliar with this class interface, but it sounds like we'd just need add `OnRunEnd` and call `Flush`.

    class ExecutionProvider : public onnxruntime::IExecutionProvider
    {
        ...
        onnxruntime::common::Status OnSessionInitializationEnd() override
        { 
            return m_impl->OnSessionInitializationEnd();
        }

        void OnRunEnd()
        {
            return m_impl->Flush(); // <<<<<<<<
        }

        void Flush()
        {
            return m_impl->Flush();
        }

Now I'm just trying to follow `SynchronizeBoundOutputs` to see whether the caller needs to explicitly wait, because I'm not seeing `IExecutionProvider::Sync` implemented either 🤔. I'll check with teammates...

**Comment by wcpeter1988** [comment]
Thanks for the quick response.

I suppose m_impl->Flush() is already waiting for command queue completion, and there are ResourceBarrier for OpKernel outputs. So Flush itself should be sufficient, at least for sequential executor.
For OnRunEnd, I am not sure whether it is the most suitable stage to call Flush, though implement OnRunEnd with single line "m_impl->Flush()", the inference works and the result is correctly filled into output allocation.

**Comment by fdwr** [comment]
@wcpeter1988: Thanks. (I'm out of office now but assigned this to another teammate.)

**Comment by wcpeter1988** [comment]
Happy new year.

**Comment by sumitsays** [comment]
@wcpeter1988 We have solved this issue as part of this [PR:10362](https://github.com/microsoft/onnxruntime/pull/10362). Please verify by building ORT from source.

**Comment by fdwr** [comment]
@wcpeter1988 This fix will be out soon in ORT 1.11. Closing.
