### ISSUE TITLE
Release notes: 1.10

### ISSUE THREAD

**Issue by david-macleod** [microsoft/onnxruntime#9963]
Hi

I noticed in the 1.10 release notes under the DML section it says `Add DynamicQuantizeLinear op`. I was just wondering if you could point me to where this is as I cannot find any recent commits/PRs.

Thanks!

**Comment by faxu** [comment]
@fdwr

**Comment by fdwr** [comment]
@david-macleod : https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/dml/DmlExecutionProvider/src/Operators/OperatorRegistration.cpp#L671

From https://github.com/microsoft/onnxruntime/pull/9765.

**Comment by david-macleod** [comment]
Great, thanks!
