### ISSUE TITLE
Find the operation of pytorch from onnx node information

### ISSUE THREAD

**Issue by Usernamezhx** [microsoft/onnxruntime#9964]
when I convert pytorch model to onnx. it will raise erro. Maybe some unsupported op in onnx. The model is so large that I can't find the corresponding operation in pytorch. Do you have good idea? thanks in advance.

**Comment by hanbitmyths** [comment]
can you share an error message?

**Comment by yuslepukhin** [comment]
[Netron](https://netron.app/) Ctrl+F

**Comment by Usernamezhx** [comment]
@yuslepukhin @hanbitmyths thanks for your reply. I don't think it is a pytorch issue. I convert the pytorch model to onnx. The onnx op graph is slight different from the pytorch model for optimising. When I convert onnx to openvino. it will raise node erro. If I familiar with the model and the model is shallow. I can find the node in pytorch easy. And then I will change the pytorch operation to convert successfully. But if the model is large and complex. I can't locate the erro node in pytorch model.

**Comment by FrancescoSaverioZuppichini** [comment]
Same here, is there a way to know the line of code used to create a specific node? Or just the module used

**Comment by thiagocrepaldi** [comment]
`torch.onnx.export` is in maintenance mode and we don't plan to add new operators/features.

Please try the new ONNX exporter and reopen this issue with a full repro if it also doesn't work for you: [quick torch.onnx.dynamo_export API tutorial](https://pytorch.org/tutorials/beginner/onnx/export_simple_model_to_onnx_tutorial.html) 

torch.onnx.dynamo_export does preserve the operator of origin as an onnx function. have fun
