### ISSUE TITLE
Do Value outputs need to be explicitly released?

### ISSUE THREAD

**Issue by admayber** [microsoft/onnxruntime#9992]
Asking here because I can't find documentation - how exactly does memory allocation work with this version of session.Run in the C++ API: https://onnxruntime.ai/docs/api/c/struct_ort_1_1_session.html#ae1149a662d2a2e218e5740672bbf0ebe

Do the output Ort::Value's need to be explicitly released? If not, what is controlling their lifetime?

**Comment by pranavsharma** [comment]
No. All CXX classes derive from Base that release the wrapped resources. See https://github.com/microsoft/onnxruntime/blob/567749b2dc57bce6412d05b3f40a88425dbbf9c9/include/onnxruntime/core/session/onnxruntime_cxx_api.h#L194 and https://onnxruntime.ai/docs/api/c/struct_ort_1_1_base.html#details

```
template<typename T>
struct Ort::Base< T >
Used internally by the C++ API. C++ wrapper types inherit from this.

This is a zero cost abstraction to wrap the C API objects and delete them on destruction. There is a secondary class 'Unowned<T>' that is used to prevent deletion on destruction (Used for return types that are not owned by the caller)
```

**Comment by admayber** [comment]
Ahh I see, thanks!
