### ISSUE TITLE
How to deploy a custom ONNX runtime in iOS app?

### ISSUE THREAD

**Issue by bhargav-kanda** [microsoft/onnxruntime#9999]
Hi,

I built a custom onnx runtime for an iOS app following the instructions shown here - https://github.com/microsoft/onnxruntime/tree/master/js#onnxruntime-react-native

I have the onnxruntime.framework folder that I zipped and placed the zip file in `<ORT_ROOT>/js/react_native/local_pods` folder and ran `pod install`. However when I run the `xcodebuild` command I get the following error:

`onnxruntime/js/react_native/ios/TensorHelper.h:8:9: fatal error: 'onnxruntime_cxx_api.h' file not found`

Am I missing any step? How to make the runtime I built available to the onnx inference session in the app? When I run `pod install` after copying the zip file, it doesn't seem to change the packages that are found.

Please guide me on this.

Thanks,

**Comment by hanbitmyths** [comment]
Thanks for the report. It's broken since onnxruntime-mobiile-c pod has XCFramework instead of Fat Framework. PR for fix will be out soon and we'll set up a pipeline to detect such issues earlier.

**Comment by bhargav-kanda** [comment]
Apologies, could not reply on this. This fixed the issue. Thank you!
